### PR TITLE
[nomaster] SI-7064 Reflection: forward compat for 2.10.1

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @retronym

**Comment by xeno-by** [comment]
Unfortunately `pendingSuperCall` will have to be disabled. It's probably possible to support both old-style and new-style encodings of primary constructor bodies in 2.10.1. But it'll be definitely impossible to support the new-style encoding in 2.10.0.

I don't think a revert is necessary - a simple boolean condition set to false should do. I think this way we'll have less problems merging later on.

**Comment by xeno-by** [comment]
Unfortunately the changes were much vaster than I remembered. I was forced to revert them altogether.

**Comment by retronym** [comment]
LGTM

**Comment by adriaanm** [comment]
PLS REBUILD/pr-checkin-per-commit@1093ce0b7c0d5e78dbd4cacc5c90cb264298afb0

**Comment by adriaanm** [comment]
BUILDLOG?

**Comment by xeno-by** [comment]
PLS SYNCH

**Pull request merged**
