### PR TITLE
Revert "SI-6387 Clones accessor before name expansion"

### PR DESCRIPTION
**Pull request by vigdorchik**
This reverts commit 4e10b2c833fa846c68b81e94a08d867e7de656aa.

Add relevant tests to pending.

Review by @retronym.

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

The problem we uncovered shows up:

``` scala
// Mixin.scala
        else if (settings.checkInit.value && !clazz.isTrait && sym.isSetter) {
          val getter = sym.getter(clazz) // returns NoSymbol
```

where: 
  `sym = method cache_= (with expanded name terminal0$$cache_$eq)`, and
  `sym.owner.info.decls = [... , method cache (no expanded name), ...]`

**Comment by retronym** [comment]
Yep, that's what I observed.

**Comment by vigdorchik** [comment]
FWIW I have a fixed version of the change ready, so if we don't need to merge immediately, maybe it's ok to close this and open a new one?

**Comment by retronym** [comment]
It is preferable to merge the revert first. If for some reason we have
to revert the second fix, we would be back in a clean state. You can
just base your next PR on this one.

**Comment by retronym** [comment]
For the record, this closed https://issues.scala-lang.org/browse/SI-7341.

**Pull request merged**
