### PR TITLE
similar in purpose to -Ygen-javap but with some advantages: -Ygen-asmp

### PR DESCRIPTION
**Pull request by magarciaEPFL**
Emitting a textual representation of bytecode is often useful. This PR adds that capability without requiring javap functionality.

review by @gkossakowski or @JamesIry or @paulp

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
BTW just noticed `ScalaSettings` still contains `Ygenjavap` , which isn't used anymore in the backend. Looks like it should enter a deprecation cycle.

**Comment by retronym** [comment]
I think it's okay to omit a test for this, but it would be nice to at least see the results of a manual test. Could you please add a comment here with a transcript that shows usage and a sample of the output?

**Comment by magarciaEPFL** [comment]
Usage:

```
  scalac -d <out-folder-classfiles> -Ygen-asmp <out-folder-asmp-files> ...
```

For example, when compiling the following:

```
object Test {
  def main(args: Array[String]) {
    (1 to 10) foreach { i => println(i) }
  }
}
```

The `-Ygen-asmp` output for `Test$.class` is:

```
// class version 50.0 (50)
// access flags 0x31
public final class Test$ {

  // compiled from: bt4.scala

  ATTRIBUTE Scala : unknown
  // access flags 0x9
  public static INNERCLASS scala/collection/immutable/Range$Inclusive scala/collection/immutable/Range Inclusive
  // access flags 0x9
  public static INNERCLASS Test$$anonfun$main$1 null null

  // access flags 0x19
  public final static LTest$; MODULE$

  // access flags 0x9
  public static <clinit>()V
    NEW Test$
    INVOKESPECIAL Test$.<init> ()V
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 0

  // access flags 0x1
  public main([Ljava/lang/String;)V
   L0
    GETSTATIC scala/runtime/RichInt$.MODULE$ : Lscala/runtime/RichInt$;
   L1
    LINENUMBER 4 L1
    GETSTATIC scala/Predef$.MODULE$ : Lscala/Predef$;
    ICONST_1
    INVOKEVIRTUAL scala/Predef$.intWrapper (I)I
    BIPUSH 10
    INVOKEVIRTUAL scala/runtime/RichInt$.to$extension0 (II)Lscala/collection/immutable/Range$Inclusive;
    NEW Test$$anonfun$main$1
    DUP
    INVOKESPECIAL Test$$anonfun$main$1.<init> ()V
    INVOKEVIRTUAL scala/collection/immutable/Range$Inclusive.foreach$mVc$sp (Lscala/Function1;)V
    RETURN
   L2
    LOCALVARIABLE this LTest$; L0 L2 0
    LOCALVARIABLE args [Ljava/lang/String; L0 L2 1
    MAXSTACK = 3
    MAXLOCALS = 2

  // access flags 0x2
  private <init>()V
   L0
    LINENUMBER 2825 L0
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    ALOAD 0
    PUTSTATIC Test$.MODULE$ : LTest$;
    RETURN
   L1
    LOCALVARIABLE this LTest$; L0 L1 0
    MAXSTACK = 1
    MAXLOCALS = 1
}
```

**Comment by magarciaEPFL** [comment]
Actually follow-up PRs that I'd like to submit depend on this one. A Looks Good would look good.

**Comment by paulp** [comment]
I would have said it needs a test but it seems retronym already gave you a pass. I'll say this LGTM anyway but I would appreciate it if you would submit a test. Command line options have to have some kind of minimal backstop or they will break, always.

**Pull request merged**
