### PR TITLE
SI-3971 error message carat mispoints at curried methods.

### PR DESCRIPTION
**Pull request by paulp**
I found it to be a general palliative to unwrap applies when reporting errors.
Point at the thing being applied, not at the opening paren of a possibly
distant argument list. This might be slightly less accurate in a few cases,
but it is vastly less inaccurate in most cases, so I think it is an easy
victory for the forces of clarity.

Thanks to retronym for figuring out why issuing a better error message broke
the compiler on non-erroneous compile runs. The changes to "treesInResult" are
the consequence.

### CODE REVIEW

**Comment by retronym** [comment]
I think I'd prefer to place the point at the start of the first argument list, rather that at the start of the callee.

Here's a perverse piece of code (actually, should this be allowed?!) whose error would be confusingly positioned otherwise (current positioning shown):

```
scala> ({"ab".reverse; "ba".equals})(0): String
<console>:8: error: type mismatch;
 found   : Boolean
 required: String
              ({"ab".reverse; "ba".equals})(0): String
                                           ^
```

**Comment by paulp** [comment]
@retronym you're right.

**Comment by retronym** [comment]
If you're going to tweak the commit anyway, s/carat/caret/.

**Comment by retronym** [comment]
I declare my perverse code to be downright [puzzling](https://groups.google.com/d/msg/scala-internals/qWjq6V6lbKw/XTecGqPfVpkJ).

**Comment by paulp** [comment]
@retronym tweak is past tense, I updated it a couple hours ago. And this is commit is plated with 24-carat goodness.

**Comment by retronym** [comment]
24-carats for a low, low price! Sold!

LGTM.

/cc @dragos I'm almost certain you guys don't use the point of error messages, but conceivably you could in quick fixes, so take note of this improvement.

**Pull request merged**
