### PR TITLE
SI-8398 - Compiler specifies lazy variables as methods

### PR DESCRIPTION
**Pull request by Feodorov**
Hi,
This is a fix for compiler warning on unused lazy val. I didn't discuss it in a mailing list, because it seems to be a trivial to fix.

### CODE REVIEW

**Comment by lrytz** [comment]
Hi @Feodorov, thanks for the contribution!

@som-snytt, do you know why `-Ywarn-unused`, `-Ywarn-unused-import` are not lint warnings?

**Comment by gourlaysama** [comment]
@lrytz they were noisy/buggy, forcing people to disable Xlint altogether: 1b1461f

**Comment by lrytz** [comment]
Thanks @gourlaysama. We could introduce a new [expanding lint option](https://github.com/scala/scala/pull/3939) `-Xlint:recommended` (or `default`), and then `-Xlint` without arguments would default to that.

**Comment by som-snytt** [comment]
So `-Xlint:_` means `-Xlint:noisy`?

That was me just thinking aloud. SGTM.

**Comment by lrytz** [comment]
Sounds good to me, too. Let's do that in a separate PR. @Feodorov, it seems you haven't signed the Scala CLA yet. Could you please do so? http://typesafe.com/contribute/cla/scala

Also, why did you add the `[nomaster]` mark in the commit message?

**Comment by Feodorov** [comment]
@lrytz 
1. Signed just a few minutes ago.
2. About the mark. I've read in pull request policy (https://github.com/scala/scala/wiki/Pull-Request-Policy):

```
when working on maintenance branches (e.g., 2.10.x), include [nomaster] if this commit should not be merged back into master
```

I thought that I should put this mark if my commit is for branch 2.11.x (not for master). Sorry if I misunderstood it.

**Comment by lrytz** [comment]
@Feodorov thanks! About `[nomaster]`: we regularly merge all changes from 2.10.x into 2.11.x, and also from 2.11.x into 2.12.x. If some commit should not be forwarded, then it should have the marker. This is not the case here, so just remove the marker from the commit message.

**Comment by Feodorov** [comment]
@lrytz thanks for explanation. Marker removed.

**Comment by Feodorov** [comment]
Didn't rebase while changing commit message. Probably, this is the reason for jenkins failure. Updated commit with rebase.

**Comment by gkossakowski** [comment]
Hi @Feodorov!

In our [pull request policy](https://github.com/scala/scala/wiki/Pull-Request-Policy) we have:

> overall, think of the first line of the commit as a description of the action performed by the commit on the code base, so use the present tense -- that also makes them easy to reuse in release notes

To follow that spirit, the commit message should read like this:

> SI-8398 - unused warning reports lazy val as a method
> 
> Compiler internals treat lazy vals as methods. Therefore, we need to have a special case for them when assembling the warning message.

Could you amend the commit message, please?

**Comment by Feodorov** [comment]
@gkossakowski Sure.

**Comment by gkossakowski** [comment]
@Feodorov, it seems like you picked up just the first line of the proposed commit message. Informative commit messages is something we care about a lot in Scala project. Could you put the whole commit message?

**Comment by Feodorov** [comment]
@gkossakowski Done

**Comment by gkossakowski** [comment]
LGTM.

Excellent! Thanks a lot for the patch!

**Pull request merged**
