### PR TITLE
Deprecate old-style constructor syntax

### LINKED ISSUE #11824: Scala 2 is blasé about procedure syntax constructors
Sorry, this must be pretty annoying at this point.

```
$ scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.5).
Type in expressions for evaluation. Or try :help.

scala> class C(c: Int) { def this() = this(42) }
defined class C

scala> class C(c: Int) { def this() { this(42) } }
defined class C
```
dotty by contrast
```
$ dotr
Starting dotty REPL...
scala> class C(c: Int) { def this() { this(42) } }
1 |class C(c: Int) { def this() { this(42) } }
  |                             ^
  |                             '=' expected, but '{' found
```
That is, I intended to resolve the issues I created.

### PR DESCRIPTION
**Pull request by som-snytt**
Ref https://github.com/scala/scala/pull/6325
Ref https://github.com/scala/scala/pull/3076

I wonder if there was a particular reason this wasn't done during the first round, besides that it was already a big delta.

Fixes scala/bug#11824

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks @som-snytt!

I think it makes sense to make this on par with Dotty.
In https://github.com/scala/scala/pull/6325/commits/1d4d901fcea0a162cd139836b246e85cc0130a6b I just flipped `settings.future` warning into non-future warning, and didn't think about the constructor case.

**Comment by hrhino** [comment]
Woah, that was fast! I noticed this but I was hoping to have my last scrap of procedure syntax to hold on to until Dotty hits and I lose it all.

I realized that my own JUnit tests tend to exercise the worst of Scala's style:
```scala
@Test def `it oughta work` {
 ...
} 
```
which I think looks closer to the more scalatesty
```scala
it should "work" in {
...
}
```
and the `(): Unit =` is kinda just line noise. It's especially irritating because you can't use non-`Unit` methods as JUnit tests, so leaving off the type ascription is dangerous.

At least this makes secondary-constructor syntax, always a bit of a second-class syntax, more regular.

**Comment by som-snytt** [comment]
@hrhino agree, and that was ichoran's argument for proc syntax. However, `nanotest` is going to be so much better. Possible missed opportunity for `nanu nanu test`.

**Comment by hrhino** [comment]
"Neener, neener, I removed your procedure syntax"-test.

I'm always glad to find out I'm in agreement with Ichoran.

**Pull request merged**
