### PR TITLE
new bytecode emitter, GenBCode, for now under a flag

### PR DESCRIPTION
**Pull request by magarciaEPFL**
review by @gkossakowski or @JamesIry or @retronym or @paulp

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
Good times ahead for scalac!

This PR adds the new bytecode emitter, for now under a flag,
which is part of a larger plan of upcoming PRs, summarized below,
to merge all of the new backend and optimizer:

(1) the new backend, under flag -neo:GenBCode
https://github.com/magarciaEPFL/scala/compare/master...f57ee84e7f25bb0ce58d38e7bb018cc4d0c260a1

(2) Level 1 of the new optimizer: intra-method optimizations
f715554

(3) "Late anon-closure-classes", ie materialized by the bytecode emitter
https://github.com/magarciaEPFL/scala/compare/f7155540c3a4fc56b05b68fc8c3899c6b01a873b...a137f13fcf9ec19589810589b223e565129396c3

(4) The rest of the new Optimizer, part 1 of 2: method inlining, stack-allocation of anon-closures
https://github.com/magarciaEPFL/scala/compare/a137f13fcf9ec19589810589b223e565129396c3...af553fc90a0b909835e68e8fd78fa4fd2d216089

(5) The rest of the new Optimizer, part 2 of 2: GC-savvy closures
https://github.com/magarciaEPFL/scala/compare/af553fc90a0b909835e68e8fd78fa4fd2d216089...ceab17f372da110bdbbf81ccd825f777cf6c5e72

(6) Minor improvements
https://github.com/magarciaEPFL/scala/compare/ceab17f372da110bdbbf81ccd825f777cf6c5e72...00bd32465bcb53de6eb2ad72faaa8505da9eeab1

(7) "Really static" modules and value-classes, ie no more invokevirtual but invokestatic
Actually there's some overlap with the very recent scala#2416
thus the new-backend-version of this functionality might change (all previous items remain unaffected)
https://github.com/magarciaEPFL/scala/compare/00bd32465bcb53de6eb2ad72faaa8505da9eeab1...76ead7ee9a1ce160de63e72935eedf23368d9b52

The functionality covered above (bytecode emitter + optimizations) is an area that's very well understood.
The new implementation draws on that experience, raising the bar on code quality, maintainability, and not to forget, compiler speed.

**Comment by magarciaEPFL** [comment]
Coming back to the new bytecode emitter (GenBCode). It's a drop-in replacement for GenASM, which means:
- any way you want to test it, GenASM should be subjected to that test. More on tests below.
- Just like the transition from GenJVM to GenASM went well, all the ingredients are there for the same to happen with GenBCode.

Regarding tests,

`files/neg/case-collision`
GenBCode also detects output classfiles differing only in case, the error message however differs from that of GenASM (collisions may be show in different order).
Thus the original test now has a flags file containing -neo:GenASM , and a new test (files/neg/case-collision2) has been added for GenBCode.
The .check files in each case show expected output.

`files/pos/t5031_3`
Currently it doesn't work with GenBCode (try with -neo:GenBCode in the flags file)
The root cause must be in the fix to https://issues.scala-lang.org/browse/SI-5031 , which among other things:
- weakened an assertion in GenASM (the original full assertion is used in GenBCode instead)
- the fix mentions the work "workaround"

`files/run/t7008-scala-defined`
This test also passes only under GenASM and not GenBCode, thus the flags file.
GenASM turns a bling eye to the following:

```
An AbstractTypeSymbol (SI-7122) has reached the bytecode emitter,
for which no JVM-level internal name can be found: ScalaClassWithCheckedExceptions_1.E1
```

Thus as you can see GenBCode is doing the right thing, not GenASM.

**Comment by retronym** [comment]
I really look forward to getting this merged. But I wonder if we can bring it in slightly smaller steps.

As an example, it would logically make sense to start without the pipelined `GenBCode`, allowing the reviewers to focus on the emitter, rather than the concurrency mechanisms. A followup PR could then introduce the pipelining, in which we could focus solely on the cleanest way to express that without obscuring the main function of the code.

Similarly, are all (or any?) of the optimizations necessary to bootstrap and pass the tests? e.g. could dead-code elimination be the subject of a followup PR?

We'll need a strategy for testing the new backend on Jenkins, ie a new PR validator build and a new nightly build that runs with `GenBCode` enabled. @adriaanm @lrytz might be able to comment here.

**Comment by adriaanm** [comment]
+1 on all of that! Great work, but it would really help to make it even more piecemeal.

We'll include it in PR validation as soon as the back-end is merged.

**Comment by adriaanm** [comment]
The test failure is my doing, sorry. I was testing an new script to publish maven artifacts for every PR so that we can include Eclipse builds in the PR validation process.

**Comment by magarciaEPFL** [comment]
OK, I'll break up this PR further, along the lines suggested by @retronym, and re-submit.

**Comment by retronym** [comment]
One tiny style issue to address in the resubmission: can you please consistently include a space after `if` and `while`?

**Comment by retronym** [comment]
Closing this in readiness for resubmission. Fellow reviewers: don't let this stop you getting a head start of the review! If you have any other concrete ideas for how to granularize this, chime in sooner rather than later to save Miguel too much re-work.

**Comment by gkossakowski** [comment]
I agree this should be broken into smaller pieces. Also, it would be good if commit message summarized architecture of GenBCode. How is it different from old backend and why particular design choices were made.

Moreover, this PR introduces a lot of functionality without almost any tests. Things like JumpChainsCollapser, LabelsCleanup, rephraseBackedgesInCtorArg, removeUnreachableCode, refreshInnerClasses should come with separate tests. Those can be either unit tests where you test only that functionality by passing ASM tree and asserting properties after transformation or bytecode tests that were added recently to partest.

**Pull request closed without merging**
