### PR TITLE
[ci: last-only] bump versions on 2.12.x branch for eventual 2.12.1

### PR DESCRIPTION
**Pull request by SethTisue**
not mergeable until 2.12.0 final is published, with modules

### CODE REVIEW

**Comment by SethTisue** [comment]
oh, we also need to merge 2.12.0 onto 2.12.x, since the last few 2.12.0 commits affected `versions.properties` as well. I'll add that

**Comment by SethTisue** [comment]
we'll need to hit rebuild on this after publishing scala-xml_2.12-1.0.6

**Comment by SethTisue** [comment]
note that despite the red X above, 18822ea did [pass validate-main](https://scala-ci.typesafe.com/job/scala-2.12.x-validate-main/3971/)

**Comment by adriaanm** [comment]
Darn. Missed that starr should be 2.12.0 now

**Comment by adriaanm** [comment]
I'll follow up.

**Comment by SethTisue** [comment]
followup PR is https://github.com/scala/scala/pull/5496

**Pull request merged**
