### PR TITLE
SI-6728 Fixes crash in parser on incomplete for expression

### PR DESCRIPTION
**Pull request by JamesIry**
The parser was trying to take the position of an empty expression
which would crash. Son on the empty expression case in TreeBuilder#
makeWhile it tries to do that and, if that failed, gets a position
that wraps both the condition and the body.

I also made a slight improvement to the UnsupportedOperationEx
messages in Position.

review @paulp

### CODE REVIEW

**Comment by paulp** [comment]
If I know about positions I'm doing my best to forget it, so I hope you're not looking to me as some sort of position authority. That said, looks good to me.

**Comment by JamesIry** [comment]
@paulp, To pick the reviewer I blindfolded myself, spun around in a circle while pointing, then took off the blindfold. I discovered two things. 1) Adriaan and Greg had suddenly stepped out of the office and 2) I was clearly pointing towards Oregon. Since the whole state wasn't available, I picked you.

**Comment by paulp** [comment]
Lets double check that whole state idea.

**Comment by JamesIry** [comment]
Too much state is a big source of our problems.

**Comment by paulp** [comment]
That's because you have been using partial state. Go whole or go home!

**Pull request merged**
