### PR TITLE
Either docs

### PR DESCRIPTION
**Pull request by mslinn**
I don't know why Adriaan's changed file (scripts/jobs/integrate/bootstrap) shows up in this PR 

I just changed `src/library/scala/util/Either.scala`. The change is trivial. If there is any complication to this PR I'll just delete it, it is not worth any fuss.

### CODE REVIEW

**Comment by SethTisue** [comment]
@mslinn can you [sign the CLA](https://www.lightbend.com/contribute/cla/scala)?

**Comment by mslinn** [comment]
Apologies for being difficult, but I have [more than the usual exposure to corporate law](https://www.micronauticsresearch.com/about/MikeSlinnResume.docx) than the average software person. That means I actually read documents critically before I sign them.

The CLA fails to mention the legal jurisdiction that is it subject to. It also fails to hold the grantor harmless in the face of any legal action against the copyright holder by third parties; in that sense it is a one-sided document.

I require a bilateral document (it would be only fair) and that the jurisdiction be stated for any document that I sign. I would be happy to sign a revised bilateral CLA that recognized the rights and needs of the grantor.

**Comment by SethTisue** [comment]
heh oops, I forgot I already got this in #5383

**Comment by mslinn** [comment]
Good. Thanks for the help with the licensing issue :)

**Pull request closed without merging**
