### PR TITLE
pattern matching efficiency: addresses SI-6686 and SI-6941, affects SI-5739

### PR DESCRIPTION
**Pull request by adriaanm**
- don't do null check when we know we've just done a type test
- don't store subpatterns bound to underscore in local val
  - note 1: under -optimize this is only done when correctness mandates it for mutable fields
  - note 2: mutable fields in case classes nested in the scala package are assumed not to be mutated by public methods, so that we don't have to store them (specifically for ::) --> this affects SI-5739
- eliminate local vals storing subpatterns when the vals aren't referenced  (their rhs's side-effect is not guaranteed anyway, and normally not observable)
- eliminate primitive value class type test when we statically know it can't fail
- test all this at the bytecode level by comparing bytecode of a match and the equivalent if/then/else/isInstanceOf/asInstanceOf/equals/...

review by @gkossakowski, @retronym

### CODE REVIEW

**Comment by adriaanm** [comment]
meh, I forgot to test under -optimize and it looks like the optimizer handles these methods differently

look at the pretty diffs, though

```
testing: [...]/files/jvm/patmat_opt_ignore_underscore                 [FAILED]
1  == TypeOp(NEW,SameBytecode$Foo)                                                                        | TypeOp(NEW,SameBytecode$Foo)
2  == Op(DUP)                                                                                             | Op(DUP)
3  == VarOp(ALOAD,0)                                                                                      | VarOp(ALOAD,0)
4  == Op(ICONST_1)                                                                                        | Op(ICONST_1)
5  == Method(INVOKESTATIC,(I)Ljava/lang/Integer;,boxToInteger,scala/runtime/BoxesRunTime)                 | Method(INVOKESTATIC,(I)/Integer;,boxToInteger,scala/runtime/BoxesRunTime)
6  == Ldc(LDC,a)                                                                                          | Ldc(LDC,a)
7  == Method(INVOKESPECIAL,(LSameBytecode;Ljava/lang/Object;Ljava/lang/String;)V,<init>,SameBytecode$Foo) | Method(INVOKESPECIAL,(ode;Ljava/lang/Object;Ljava/lang/String;)V,<init>,SameBytecode$Foo)
8  <> VarOp(ASTORE,1)                                                                                     | VarOp(ASTORE,2)
9  <> VarOp(ALOAD,1)                                                                                      | VarOp(ALOAD,2)
10 <> Jump(IFNULL,Label(17))                                                                              | Jump(IFNULL,Label(19))
11 <> VarOp(ALOAD,1)                                                                                      | VarOp(ALOAD,2)
12 <> Method(INVOKEVIRTUAL,()Ljava/lang/Object;,x,SameBytecode$Foo)                                       | Method(INVOKEVIRTUAL,()Ljava/lang/String;,y,SameBytecode$Foo)
13 <> TypeOp(INSTANCEOF,java/lang/String)                                                                 | VarOp(ASTORE,1)
14 <> Jump(IFEQ,Label(17))                                                                                | VarOp(ALOAD,2)
15 <> VarOp(ALOAD,1)                                                                                      | Method(INVOKEVIRTUAL,()Ljava/lang/Object;,x,SameBytecode$Foo)
16 <> Method(INVOKEVIRTUAL,()Ljava/lang/String;,y,SameBytecode$Foo)                                       | TypeOp(INSTANCEOF,java/lang/String)
17 <> Op(ARETURN)                                                                                         | Jump(IFEQ,Label(19))
18 <> Label(17)                                                                                           | VarOp(ALOAD,1)
19 <> FrameEntry(List(SameBytecode$Foo),List())                                                           | Op(ARETURN)
20 <> TypeOp(NEW,scala/MatchError)                                                                        | Label(19)
21 <> Op(DUP)                                                                                             | FrameEntry(List(0, SameBytecode$Foo),List())
22 <> VarOp(ALOAD,1)                                                                                      | TypeOp(NEW,scala/MatchError)
23 <> Method(INVOKESPECIAL,(Ljava/lang/Object;)V,<init>,scala/MatchError)                                 | Op(DUP)
24 <> Op(ATHROW)                                                                                          | VarOp(ALOAD,2)
25 <>                                                                                                     | Method(INVOKESPECIAL,(Ljava/lang/Object;)V,<init>,scala/MatchError)
26 <>                                                                                                     | Op(ATHROW)


testing: [...]/files/jvm/t6941                                        [FAILED]
1  == VarOp(ALOAD,1)                                                                          | VarOp(ALOAD,1)
2  == TypeOp(INSTANCEOF,scala/collection/immutable/$colon$colon)                              | TypeOp(INSTANCEOF,scala/collection/immutable/$colon$colon)
3  <> Jump(IFEQ,Label(10))                                                                    | Jump(IFEQ,Label(12))
4  == VarOp(ALOAD,1)                                                                          | VarOp(ALOAD,1)
5  == TypeOp(CHECKCAST,scala/collection/immutable/$colon$colon)                               | TypeOp(CHECKCAST,scala/collection/immutable/$colon$colon)
6  == VarOp(ASTORE,2)                                                                         | VarOp(ASTORE,2)
7  == VarOp(ALOAD,2)                                                                          | VarOp(ALOAD,2)
8  == Method(INVOKEVIRTUAL,()Ljava/lang/Object;,hd$1,scala/collection/immutable/$colon$colon) | Method(INVOKEVIRTUAL,()/Object;,hd$1,scala/collection/immutable/$colon$colon)
9  == Method(INVOKESTATIC,(Ljava/lang/Object;)I,unboxToInt,scala/runtime/BoxesRunTime)        | Method(INVOKESTATIC,(Ljava/lang/Object;)I,unboxToInt,scala/runtime/BoxesRunTime)
10 <> Op(IRETURN)                                                                             | VarOp(ISTORE,3)
11 <> Label(10)                                                                               | VarOp(ILOAD,3)
12 <> FrameEntry(List(),List())                                                               | Op(IRETURN)
13 <> TypeOp(NEW,scala/MatchError)                                                            | Label(12)
14 <> Op(DUP)                                                                                 | FrameEntry(List(),List())
15 <> VarOp(ALOAD,1)                                                                          | TypeOp(NEW,scala/MatchError)
16 <> Method(INVOKESPECIAL,(Ljava/lang/Object;)V,<init>,scala/MatchError)                     | Op(DUP)
17 <> Op(ATHROW)                                                                              | VarOp(ALOAD,1)
18 <>                                                                                         | Method(INVOKESPECIAL,(Ljava/lang/Object;)V,<init>,scala/MatchError)
19 <>                                                                                         | Op(ATHROW)


testing: [...]/files/jvm/patmat_opt_primitive_typetest                [FAILED]
1  == TypeOp(NEW,SameBytecode$Foo)                                                       | TypeOp(NEW,SameBytecode$Foo)
2  == Op(DUP)                                                                            | Op(DUP)
3  == VarOp(ALOAD,0)                                                                     | VarOp(ALOAD,0)
4  == Op(ICONST_1)                                                                       | Op(ICONST_1)
5  == Ldc(LDC,a)                                                                         | Ldc(LDC,a)
6  == Method(INVOKESPECIAL,(LSameBytecode;ILjava/lang/String;)V,<init>,SameBytecode$Foo) | Method(INVOKESPECIAL,(LSameBytecode;ILjava/lang/String;)V,<init>,SameBytecode$Foo)
7  <> VarOp(ASTORE,1)                                                                    | VarOp(ASTORE,2)
8  <> VarOp(ALOAD,1)                                                                     | VarOp(ALOAD,2)
9  <> Jump(IFNULL,Label(12))                                                             | Jump(IFNULL,Label(14))
10 <> VarOp(ALOAD,1)                                                                     | VarOp(ALOAD,2)
11 == Method(INVOKEVIRTUAL,()Ljava/lang/String;,y,SameBytecode$Foo)                      | Method(INVOKEVIRTUAL,()Ljava/lang/String;,y,SameBytecode$Foo)
12 <> Op(ARETURN)                                                                        | VarOp(ASTORE,1)
13 <> Label(12)                                                                          | VarOp(ALOAD,1)
14 <> FrameEntry(List(SameBytecode$Foo),List())                                          | Op(ARETURN)
15 <> TypeOp(NEW,scala/MatchError)                                                       | Label(14)
16 <> Op(DUP)                                                                            | FrameEntry(List(0, SameBytecode$Foo),List())
17 <> VarOp(ALOAD,1)                                                                     | TypeOp(NEW,scala/MatchError)
18 <> Method(INVOKESPECIAL,(Ljava/lang/Object;)V,<init>,scala/MatchError)                | Op(DUP)
19 <> Op(ATHROW)                                                                         | VarOp(ALOAD,2)
20 <>                                                                                    | Method(INVOKESPECIAL,(Ljava/lang/Object;)V,<init>,scala/MatchError)
21 <>                                                                                    | Op(ATHROW)
```

**Comment by adriaanm** [comment]
I implemented @retronym's review feedback and rebased. I added .flags files for all the tests so they are consistently run under -optimize.

**Comment by adriaanm** [comment]
it's ok, one of the earlier jobs will complete soon

**Comment by adriaanm** [comment]
i've also fixed the kitten to be less eager -- there shouldn't be any job duplication anymore

**Comment by gkossakowski** [comment]
LGTM.

In the future I find it to be a good practice to commit a test first that documents current behavior and then update the test along with the commit that improves fix. If the test is properly written (as here) you'll have a nice diff showing the improvement. It's a bit more work but makes reviewing a lot easier.

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
