### PR TITLE
SI-8607 Fix erasure for value class inheriting from private class

### PR DESCRIPTION
**Pull request by retronym**
Details in the commits.

Here's the full diff of scalac logging output to explain
how we led into the crash:

   https://gist.github.com/retronym/e533b3f35d6b5288c36b

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski

**Comment by retronym** [comment]
Gentle ping @gkossakowski

**Comment by gkossakowski** [comment]
LGTM

**Comment by gkossakowski** [comment]
I think this is the most bizarre issue I've seen in a while. :-)

**Pull request merged**
