### PR TITLE
SI-8275 allow to directly extract block contents of the case def

### PR DESCRIPTION
**Pull request by densh**
Due to the fact that blocks in cases are implicit one might expect to be
able to extract its contents with `..$`.

review @xeno-by

### CODE REVIEW

**Comment by retronym** [comment]
Lgtm.

**Comment by densh** [comment]
There is an additional problem I've noticed here so please don't merge it yet, I'll update soon with revised fix.

**Comment by xeno-by** [comment]
All in all sounds reasonable. I think `val q"()" = q"{}"` is a right thing to do.

**Pull request merged**
