### PR TITLE
SI-7548 askTypeAt returns the same type for full/ targeted typecheck (2.10.x)

### PR DESCRIPTION
**Pull request by dotta**
Re-opened https://github.com/scala/scala/pull/3177 to target 2.10.x

review by @retronym

~~P.S. This commit https://github.com/dotta/scala/commit/652b3b4b9dcbf990e7ace409e050cc4ba4e83b16 will fail the build because the commit is intended to show the issue. I expect this won't be a problem for merging the PR.~~ not true, see comment https://github.com/scala/scala/pull/3208#issuecomment-29605967

### CODE REVIEW

**Comment by retronym** [comment]
All commits must build. But 652b3b4 _should_ pass, as its checkfile contains the undesired result: `Foo.this.I.+: (other: Foo.I.type)Unit`.

My intention was to make the diff of that checkfile in the next commit informative: 02308c96910a76a09c2654db304a0696c0b603af

**Comment by retronym** [comment]
LGTM

**Comment by dotta** [comment]
Got it! Nice trick, I'll keep this in mind for the next PR I'm pushing :-)

**Comment by dragos** [comment]
BTW, what happens if there's an error in the program, and the method is never resolved (stays overloaded)?

**Comment by retronym** [comment]
I think that the typechecker will bubble up out of silent mode and then the IDE will see a tree with an overloaded type. Or maybe an error type.

@dotta Care to write a test for that case?

``` scala
def foo(a: Int) = a; def foo(a: String) = a; foo(true)
```

**Comment by dotta** [comment]
@retronym Will do.

**Pull request merged**
