### PR TITLE
SI-6736, SI-6747 sort out Range boundary problems

### PR DESCRIPTION
**Pull request by ihji**
When Range contains more than Int.MaxValue elements,
it should throw IllegalArgumentException before every
meaningful operation on it. It seems that the only
reason of delaying this exception is for allowing "by"
operation.

> (Int.MinValue to 0).contains(4) # should throw exception
> (Int.MinValue to 0 by 3).contains(4) # okay

The source of all evil here is irregular use of
`numRangeElements`. It returns -1 if Range object is
invalid. Some use sites of `numRangeElements` properly check
its validity before using it, but some of them miss this
check and cause the integer overflow problems (for example,
in `lastElements`).

I think better strategy is to make `numRangeElements` lazy
value and throw exception inside itself when initialized
but turned to be invalid.

Additionally, because they (`numRangeElements`,`lastElement`,
`terminalElement`) are completely undocumented and also have
better public alternatives (`last`,`length`), I propose to
make them private.

### CODE REVIEW

**Comment by ihji** [comment]
Review by @retronym

**Comment by paulp** [comment]
This class is a lot more subtle than you realize. A very great deal of blood has been spilt. The lazy val is a non-starter, as it inhibits optimization. Please see the many threads involving the attempted optimization of Range#foreach, of which this is only one representative example: https://groups.google.com/forum/#!msg/scala-internals/GDT0pCObRyU/1tS6-YiSilEJ

**Comment by ihji** [comment]
You're right. I've never thought about the possibility that `lazy val` precludes jitting.
The benchmark result I've just run also shows the same thing. `lazy val` introduces 2~3x overhead in most cases.

**Comment by ihji** [comment]
I ran additional benchmarks on:
- current master branch just before this commit
- this commit (using lazy val)
- vanilla 2.10.1
  range

raw data is here: https://gist.github.com/ihji/5503604

**Comment by paulp** [comment]
@ihji That data suggests that the lazy val can be tolerated, but only if it is not inlined. If you are up for a little more benchmarking, I suggest annotating the lazy vals @noinline and see what happens to *-Opt.

**Comment by ihji** [comment]
@paulp I ran the benchmark as you said and annotating @noinline had no effect in this case. Interestingly, I found that putting all lazy vals into the while loop normalises the performance in both cases (optimized: 60us -> 30us, unoptimized: 20us -> 30us).
range

**Comment by ihji** [comment]
The latest result. Now it shows competitive performance. I've run "--grep range" tests and they were all passed. Waiting for an all-green sign from the jenkins.
range
range

**Comment by ihji** [comment]
@paulp Let me close this one too.

**Pull request closed without merging**
