### PR TITLE
SAM conversion spec typo

### PR DESCRIPTION
**Pull request by som-snytt**
Capture results in nonzero-arg ctor.

### CODE REVIEW

**Comment by som-snytt** [comment]
It needs a rebase for a broken test, but I swear I only changed one word in the spec.

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
Did that count as another off-by-one error?

**Comment by som-snytt** [comment]
I'm pleasantly surprised that I understood it correctly. Or misunderstood it incorrectly.

**Comment by adriaanm** [comment]
You can color me a vivid shade of unsurprised.

**Pull request merged**
