### PR TITLE
SI-9508 fix classpaths in Eclipse configuration

### PR DESCRIPTION
**Pull request by performantdata**

### CODE REVIEW

**Comment by performantdata** [comment]
review @retronym

**Comment by performantdata** [comment]
Should I also axe the `asm` project in this PR?

**Comment by retronym** [comment]
Yes, it would make sense to remove `asm` at the same time.

**Comment by retronym** [comment]
For consistency with the existing Eclipse configuration, please refer to the ASM JAR in:

`M2_REPO/org/scala-lang/modules/scala-asm/5.0.4-scala-3/scala-asm-5.0.4-scala-3.jar`

We also copy them into `deps` so that we can refer to them easily from the IntelliJ classpath, which supports a reference to `deps/*.jar`. That approach means we don't have to update the IntelliJ configuration when we update the version of libraries.

AFAIK, Eclipse doesn't support that sort of classpath configuration.

We're missing an automated link here: we should try really try to generate the Eclipse configuration. Perhaps when we move to the SBT build as a standard, we'll be able to do that (although our SBT build is still exotic enough that it is likely trips up the IDE import).

**Comment by performantdata** [comment]
> For consistency with the existing Eclipse configuration, please refer to the ASM JAR in:
> 
> `M2_REPO/`...

That came from [a scala-internals post](https://groups.google.com/d/msg/scala-internals/In_r45sWvaw/6ruBIpGAjJQJ). Done.

> we don't have to update the IntelliJ configuration when we update the version of libraries.
> 
> AFAIK, Eclipse doesn't support that sort of classpath configuration.

Normally one would use M2Eclipse for that.

**Comment by performantdata** [comment]
> Yes, it would make sense to remove `asm` at the same time.

Done.

**Comment by performantdata** [comment]
Is that some kind of CI command?

**Comment by SethTisue** [comment]
yes, I see it wasn't documented though. now doc'ed: https://github.com/scala/scabot/pull/54

**Comment by performantdata** [comment]
@retronym I'm effectively done with commits for this PR, in case you were waiting on that. There may be more adjustments to the Eclipse config files, but these fix all the Eclipse build errors that I've seen.

**Comment by lrytz** [comment]
To match the commit granularity we usually have in this repo, could you squash the changes into a single commit? Then it looks all good.

**Comment by performantdata** [comment]
@lrytz Rebased.

**Comment by performantdata** [comment]
@lrytz is there anything holding this back, then?

**Comment by lrytz** [comment]
@performantdata I just tried it on my machine using scala IDE 4.2.0, following the instructions in https://github.com/scala/scala/blob/2.11.x/src/eclipse/README.md. I get "Unable to find a scala library. Please add the scala container or a scala library jar to the build path" for all projects - any ideas? https://dl.dropboxusercontent.com/u/4881107/eclipse.png

**Comment by performantdata** [comment]
I'm also on 4.2.0, with Luna (4.4.2). Have you tried the Eclipse Re- Dance (refresh, rebuild, reopen, restart)? I just checked out to my `issue/9508` branch and got 16 errors; refreshed all projects, errors gone.

**Comment by performantdata** [comment]
I just did

```
git clone https://github.com/performantdata/scala.git scala-issue-9508
cd scala-issue-9508
git checkout issue/9508
ant init
```

started Eclipse in a new workspace, imported the projects, got the errors about `SCALA_BASEDIR`. (We should have people set that before importing.) Set the `SCALA_BASEDIR`s, got
- an error pop-up about "Auto-ignore" "updating .../scala-issue-9508/build/quick/classes/.gitignore failed" "No such file or directory", and
- your 7 errors. (Not "all projects" have errors; `scala-library` and `scalap` don't.)

Added the JLine JAR. Don't get the "Access restriction" error.

Select all projects and refresh: still have the 7 errors, plus some new warnings.

Clean all projects (and rebuild automatically): now I have 19 errors, but none of the "Unable to find a scala library." These are "Project ... not built due to errors in dependent project(s) reflect", and "reflect's tests not built due to errors in dependent scope(s) main", but no errors from `reflect`'s scope `main`.

Select, close and re-open all projects: all errors are gone. Left with 16 warnings, mostly about deprecation.

Are you not a regular Eclipse user? The Re- Dance is undocumented S.O.P.

**Comment by lrytz** [comment]
Indeed, a few rounds of closing, re-opening and re-building helped. I'm not a regular eclipse user, so I didn't know.. All seems to work fine now!

**Comment by lrytz** [comment]
LGTM

**Comment by SethTisue** [comment]
thank you @performantdata! having the Eclipse building working increases our pool of potential contributors, so we're definitely glad to have this.

**Pull request merged**
