### PR TITLE
WIP New classpath and sourcepath implementation

### PR DESCRIPTION
**Pull request by afitz**
This is WIP branch pushed to consult it with Grzegorz Kossakowski.

Current implementation of classpath is not very efficient and it's quite abstract because it was created when e.g. .NET was supported. Therefore one of goals of new implementation is to improve efficiency by creation of dedicated classes for various file types characteristic for Scala with JVM backend - what allows us to create more efficient, more low-level operations. The second goal is to reduce memory consumption. To do that there's added caching for jar/zip files. So that we can reuse existing instances, when we create entries for the same files once again. Hopefully it will lead to significant reduction of used memory also in the case of e.g. ScalaPresentationCompilers.

One of the most important things took into account during creating this implementation was adding it as optional feature, which can be marked as experimental and turned on  using flag. At the beginning users will use old classpath implementation by default and they will be able to use new implementation when:
- they will want to test it (feedback)
- they will want to gain benefits which it provides

There are a lot of TODOs, some unused classes, temporary (?) benchmarks and maybe not very pretty solutions and names, but it's something, what will be discussed with Grzegorz. Definitely we need more unit tests. Right now existing tests (including partest) and also other, manually executed tests pass.

THIS PROGRAM IS SUBJECT TO THE TERMS OF THE BSD 3-CLAUSE LICENSE.
IN ADDITION, THE FOLLOWING DISCLAIMER APPLIES IN CONNECTION WITH THIS PROGRAM:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR
ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR
ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.
ONLY THE SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE, IF ANY, THAT ARE ATTACHED TO (OR OTHERWISE ACCOMPANY) THIS SUBMISSION (AND ORDINARY
COURSE CONTRIBUTIONS OF FUTURES PATCHES THERETO) ARE TO BE CONSIDERED A CONTRIBUTION.  NO OTHER SOFTWARE CODE OR MATERIALS ARE A CONTRIBUTION.

### CODE REVIEW

**Comment by mpociecha** [comment]
Regarding conflicts - I wasn't rebasing this branch for some time. I'm going to rebase it in the case of normal (not WIP) pull request.

Edit: Or, looking at all these messages from scala-jenkins, before next update.

**Comment by gkossakowski** [comment]
I'll have a look at this next week.

**Comment by retronym** [comment]
For future reference, it would be better to perform this review in a different repository until you are ready to submit the branch for testing. This PR took a big chunk of our build resources for a few hours as it has a large number of commits.

That said, I'm excited to see this work resuming!

**Comment by gkossakowski** [comment]
Overall is going in the right direction. We definitely need to squash a lot of commits from this branch. The 4cdec6c and 2734bd7 are independent from the rest of this PR so it can be cherry picked and submitted as separate PR. Could you do that?

Please rebase the PR on top of latest 2.11.x branch and squash many of the commits that make sense to be squashed. You don't need to achieve perfect commits in one step, but squashing the obvious candidates (those that fix up some other commits) is a good start.

Lastly, what's the status of partest tests? How many of them are passing and how many of them are failing when flat classpath is enabled by default? Can you bootstrap the compiler with new classpath implementation enabled?

**Comment by mpociecha** [comment]
As I wrote via mail some time ago: All tests from partest pass except these ones:
java 6
  [partest] !! 1435 - run/t7634.scala                           [output differs]
1 tests failed

java 7
  [partest] !! 570 - neg/t6289                                 [output differs]
  [partest] !!  581 - run/repl-javap-app.scala                  [output differs]
2 tests failed

which are not related to my changes. They were failing on my machine with Windows even on master. And I have commit which is alread merged to 2.11.x and everything passed on Jenkins while I also had problems with above tests on my machine when running tests before creating this previous, already merged PR.

"Can you bootstrap the compiler with new classpath implementation enabled?"
I think so. Didn't I have this in added benchmarks? And doesn't partest do that?

**Comment by gkossakowski** [comment]
That's great to hear that tests pass already!

No, partest doesn't bootstrap compiler. The way to test bootstrapping is to change default classpath implementation to flat and then run `ant all.clean && ant`. If compiler builds that way (using new classpath), then you are good to go.

**Comment by mpociecha** [comment]
I ran this with this additional "&& ant" and it works as always (BUILD SUCCESSFUL).

Edit: Ah, it was just about running full clean and build after that. Yes, I was doing that many times and even made some changes to make it working.

**Comment by gkossakowski** [comment]
Excellent news!

I think the next step would be cleaning up the PR as mentioned earlier.

**Comment by som-snytt** [comment]
@mpociecha  Does "works as always" mean the tests you said failed actually passed?

I'm asking because those tests should work on Windows.

**Comment by mpociecha** [comment]
@som-snytt:
I would have to check it but it seems to me that ant all.clean && ant didn't run tests. I meant that the build works.
But in general I tested these tests on two computers and there were problems on both.

Edit: And I'm not saying that problem is related to Windows for sure - just wanted to mark that I use Windows (different OS than probably most of you use).

Edit2: https://groups.google.com/forum/#!topic/scala-internals/P7mv3wmTSfs

**Comment by gkossakowski** [comment]
Closing this PR. A new iteration of it is coming shortly.

**Pull request closed without merging**
