### PR TITLE
Make unused-import warnings easier to silence (support filtering by `origin=`)

### LINKED ISSUE #12326: Unused imports difficult to silence
## reproduction steps

using Scala 2.13,

https://github.com/scala/scala-collection-compat/issues/240

demonstrates that the `collection.compat` import is difficult to selectively silence.

## problem

If unused import warning specified origin (the imported thing, minus any wildcard) it would be trivial to suppress `origin=scala.collection.compat`.

### PR DESCRIPTION
**Pull request by som-snytt**
This allows nowarn by regex matching the fully-qualified selector string. For `import a.{b, _}`, match `a.b` or `a._`.

Fixes scala/bug#12326

### CODE REVIEW

**Comment by som-snytt** [comment]
We need a label for "review-friendly!"

**Review by SethTisue — APPROVED** [review]
LGTM, but ideally @lrytz would take a look as well, let's see if we attract his attention

**Comment by som-snytt** [comment]
This work just stands on his shoulders.

**Review by lrytz — APPROVED** [review]
very nice :)

**Pull request merged**
