### PR TITLE
REPL: JLine 3: fix various issues

### LINKED ISSUE #692: JLine 3: fix //print
it sort of works but it ends up mangled:

```
scala> 2 + 2 //prin(2).+(2) // : Int(4)
```

### LINKED ISSUE #696: JLine 3: tab completion: showing method signatures is broken
as I said on the PR

> the behavior when you hit the TAB key more than once is a regression. It seems like a blocker to me

if you tab twice, instead of showing you the signature in an information area, it actually inserts it into your command line. here I typed `Predef.ident` and then double-tabbed

```
scala> Predef.def identity[A](x: A): A
```

whereas on JLine 2, the interaction looks as follows. it shows the signature and then gives you a whole new prompt:

```
scala 2.13.1> Predef.identity
   def identity[A](x: A): A

scala 2.13.1> Predef.identity
```

Ammonite behaves similarly (even though they're on JLine 3):

```
@ Predef.iden 
identity
@ Predef.identity 
def identity[A](x: A): A
@ Predef.identity
```

whereas Dotty doesn't seem to have this signature-showing feature

anyway, we need to either bring that behavior back or find another way to show this information, perhaps using JLine's "status" feature

https://github.com/scala/scala/pull/7645#issuecomment-454269972 : "It's nice that autocomplete doesn't burn lines of console anymore, the options are updated in-place on subsequent typing. now takes you into the matrix of completions to navigate with a cursor. Previously, we'd detect and emit the signature for the first candidate. I'm sure JLine3 has a better way to render this, perhaps in a status bar."

### LINKED ISSUE #697: JLine 3: tab completion behavior on tab after `.` is broken
if you `Predef.` and then tab, the completions you're offered include `.`:

```
scala> Predef.
.
```

And if you tab again, the cursor moves into the completions matrix but you lose the dot you typed

from one point of view you could call this minor, to me it seems both common enough and annoying enough to be considered a blocker, especially since it might have an easy fix (some off-by-one thing?)

the Dotty REPL does the right thing.

### LINKED ISSUE #703: JLine 3: `:paste` is misbehaving (continuation prompt should be suppressed)
reported by @bishabosha at https://github.com/scala/scala/pull/8036#issuecomment-604368493

### LINKED ISSUE #705: JLine 3: replay session when entry seems to have slain the compiler
Doesn't work anymore.
```
scala> case class Foo(x: Int) extends AnyVal
java.lang.NumberFormatException: For input string: "1$extension"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.reflect.internal.StdNames$TermNames.splitDefaultGetterName(StdNames.scala:520)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.rescindPrivateConstructorDefault$1(TypeDiagnostics.scala:595)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.isSyntheticWarnable(TypeDiagnostics.scala:598)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.isUnusedTerm(TypeDiagnostics.scala:603)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.$anonfun$unusedTerms$1(TypeDiagnostics.scala:628)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.unusedTerms(TypeDiagnostics.scala:628)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:76)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
	at scala.reflect.internal.Trees$ModuleDef.$anonfun$transform$3(Trees.scala:370)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.reflect.internal.Trees$ModuleDef.transform(Trees.scala:369)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.reflect.internal.Trees$Template.transform(Trees.scala:518)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
	at scala.reflect.internal.Trees$ModuleDef.$anonfun$transform$3(Trees.scala:370)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.reflect.internal.Trees$ModuleDef.transform(Trees.scala:369)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:316)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:316)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:162)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transformUnit(ReplGlobal.scala:65)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:36)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:737)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:949)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:529)
	at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:515)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:499)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:497)
	at scala.tools.nsc.interpreter.shell.ILoop.loop$1(ILoop.scala:868)
	at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:900)
	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:427)
	at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:434)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:452)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:954)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
	at sbt.Console.console0$1(Console.scala:48)
	at sbt.Console.$anonfun$apply$2(Console.scala:51)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)

[error] (run-main-0) scala.NotImplementedError: an implementation is missing
[error] scala.NotImplementedError: an implementation is missing
[error] 	at scala.tools.nsc.interpreter.jline.Reader.readOneKey(Reader.scala:31)
[error] 	at scala.tools.nsc.interpreter.shell.InteractiveReader.readYesOrNo(InteractiveReader.scala:28)
[error] 	at scala.tools.nsc.interpreter.shell.InteractiveReader.readYesOrNo$(InteractiveReader.scala:28)
[error] 	at scala.tools.nsc.interpreter.jline.Reader.readYesOrNo(Reader.scala:28)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.fn$1(ILoop.scala:407)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.applyOrElse(ILoop.scala:410)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.applyOrElse(ILoop.scala:391)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:452)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:954)
[error] 	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:78)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
[error] 	at sbt.Console.console0$1(Console.scala:48)
[error] 	at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:257)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit code: 1
```

For the session slayer see scala/bug#9910

### LINKED ISSUE #707: JLine 3: parse errors should be suppressed during JLine-initiated tokenizing
for example, when calling a method on the last REPL result, it works but a spurious error is printed, also

not sure how many people even know this feature exists, but:

```
scala 2.13.1> List(9)
res2: List[Int] = List(9)

scala 2.13.1> .length
res3: Int = 1
```

whereas on JLine 3 currently:

```
scala> List(9)
val res1: List[Int] = List(9)

scala> .length       ^
       error: illegal start of definition

val res2: Int = 1
```

funny that you get the right answer anyway.

the special handling for this is in `ReplCompletion#complete`

there should really be test coverage.

### PR DESCRIPTION
**Pull request by SethTisue**
adds some extra polish to https://github.com/scala/scala/pull/8036

* fixes scala/scala-dev#697
* fixes scala/scala-dev#703
* fixes scala/scala-dev#705
* fixes scala/scala-dev#707
* fixes scala/scala-dev#696
* fixes scala/scala-dev#692

### CODE REVIEW

**Comment by dwijnand** [comment]
I'm pretty sure I've seen support around REPL replaying (SessionTest iirc).  Isn't the fix for scala/scala-dev#705 testable?

**Comment by SethTisue** [comment]
> Isn't the fix for scala/scala-dev#705 testable?

The problem was specifically when connected to an actual terminal.

Whether session replaying is now perfect, I don't know, my ambitions were limited (for now anyway) to fixing the immediate blocker that prevented it from working at all (on a real terminal).

**Comment by h-vetinari** [comment]
Has someone reached out to the spark maintainers about the (impact of the) JLine 3 changes / [issues](https://github.com/scala/scala-dev/labels/t%3Ajline3)? It's 10 month after the release of 2.13.0, and they are still [blocked](https://issues.apache.org/jira/browse/SPARK-25075) on upgrading to 2.13 (and that despite @martijnhoekstra working tirelessly through the twitter dependency stack). One of the specific blockers is the [REPL interaction](https://issues.apache.org/jira/browse/SPARK-30090), so it would IMO be a pity if something that's needed for spark-on-2.13 were to narrowly miss 2.13.2, and it would be another 4-6 month until they'd be unblocked by the following point release.

**Comment by lrytz** [comment]
Example that doesn't work in `:paste -raw` with the current tip of this PR:

```
Welcome to Scala 2.13.2-20200402-045016-1060b72 (Java HotSpot(TM) 64-Bit GraalVM EE 19.2.1, Java 1.8.0_231).
Type in expressions for evaluation. Or try :help.

scala> :paste -raw
// Entering paste mode (ctrl-D to finish)

package pa {
  object T
}

package pu {
  object U
}

java.lang.IllegalArgumentException: requirement failed: wordCursor 2 should be in range TokenData(105,51,52,false)
	at scala.tools.nsc.interpreter.jline.Reader$ScalaParsedLine.<init>(Reader.scala:176)
```

**Comment by lrytz** [comment]
@h-vetinari we haven't done cross-testing with spark because there is no 2.13 spark branch currently that we could use for that, so there is really no good way for us to test this. The only thing I could imagine is back-porting the JLine 3 upgrade to 2.12, but there are older refactorings in the REPL codebase in 2.13 which are much more likely to affect how spark integrates the REPL.

That said, we are eager to work with spark contributors on the 2.13 upgrade as soon as possible. We have chimed in on many of the 2.13-related tickets already. But as you note, the upgrade is currently blocked on issues outside our reach.

**Comment by h-vetinari** [comment]
@lrytz 
Yeah, I wasn't talking about testing the JLine 3 things on spark yourselves, but maybe someone from the spark-maintainers would be able to immediately identify additional blocking issues among [the remaining ones](https://github.com/scala/scala-dev/labels/t%3Ajline3), for example.

It was just a thought; in any case, I think they'd very likely respond to a ping on GH/JIRA.

**Comment by SethTisue** [comment]
> Example that doesn't work in :paste -raw with the current tip of this PR

@lrytz weird... I'm not able to reproduce the problem

**Comment by lrytz** [comment]
> @lrytz weird... I'm not able to reproduce the problem

Hah, it seems to be unrelated to the code I posted, instead a trailing space trips it up. When I type `class C ` then return in `:paste` mode I get

```
class C
java.lang.IllegalArgumentException: requirement failed: wordCursor 2 should be in range TokenData(10,6,7,true)
	at scala.tools.nsc.interpreter.jline.Reader$ScalaParsedLine.<init>(Reader.scala:176)
	at scala.tools.nsc.interpreter.jline.Reader$ScalaParser.tokenize(Reader.scala:157)
```

**Comment by SethTisue** [comment]
@lrytz ah, good catch, fixed.

**Comment by SethTisue** [comment]
This doesn't fix every last blocker, but I think it's about time to get this stuff merged, for wider testing.

@som-snytt do you have the time+inclination to do the review honors...?

(review from others is of course welcome as well!)

**Comment by som-snytt** [comment]
I'll take a look when I have a few minutes to spare from social distancing.

If this is sanding off rough edges, then it feels like coming back from the beach when I was little, sand in my trunks and in my sneakers and everywhere.

**Review by lrytz — APPROVED** [review]

**Comment by SethTisue** [comment]
(rebased, no other changes)

**Comment by SethTisue** [comment]
merging, so we'll all be testing this. review feedback remains welcome

**Pull request merged**
