### PR TITLE
Default to IEEE floating point Orderings

### LINKED ISSUE #10511: Ordering methods are inconsistent for Double and Float
For:

- `Float.NaN`
- `Double.NaN`
- `-0.0f` and `0.0f`
- `-0.0d` and `0.0d`

the following inconsistencies exist:

- `Ordering.lt` can return false when `Ordering.compare` returns a negative number
- `Ordering.lteq` can return false when `Ordering.compare` returns a negative number or `0`
- `Ordering.equiv` can return false when `Ordering.compare` returns `0`
- `Ordering.equiv` can return true when `Ordering.compare` returns a non-zero value
- `Ordering.gteq` can return false when `Ordering.compare` returns a positive number or `0`
- `Ordering.gt` can return false when `Ordering.compare` returns a positive number

The reason for the inconsistency is that the convenience methods are overridden to use the primitive operators (`<`, `<=`, `==`, `>=`, and `>` respectively), which always return false for operations where at one of the operands is `NaN`. However `compare` is implemented by `java.lang.{Float, Double}.compare`, for which `NaN` is ordered as *larger* than all other values. Also, the primitive operators treat `-0.0` and `0.0` as equal, while `java.lang.{Float, Double}.compare` do not.

`Ordering.min` is inconsistent with `compare` as well; however, I'm not sure it is consistent with the other methods either. `Ordering.max` seems to be consistent with `compare` by chance.

It is possible that this behavior is intended, though counter-intuitive, but if so, it should probably be documented.

----------------

One result of these inconsistencies is that `TraversableOnce.min` and `.max` are non-deterministic (and wrong):

```
scala> import java.lang.Double.NaN
import java.lang.Double.NaN

scala> Seq(5.0, 3.0, NaN, 4.0)
res0: Seq[Double] = List(5.0, 3.0, NaN, 4.0)

scala> res0.min
res1: Double = 4.0

scala> res0.max
res2: Double = 4.0
```

Those methods could be fixed by using `Ordering.min` and `.max` internally, instead of `.lteq` and `.gteq`; however, they shouldn't need to.

### PR DESCRIPTION
**Pull request by NthPortal**
Un-deprecate default floating point `Ordering`s and
change them to use IEEE semantics where possible.

Fixes scala/bug#10511. One of 3 proposed solutions; the others are #8612 and #8614.

### CODE REVIEW

**Comment by Ichoran** [comment]
This restores parity with 2.12 IIRC, which makes it the most conservative (and therefore probably best) choice.

**Comment by NthPortal** [comment]
this doesn't appear to be the solution we're going with

**Comment by eed3si9n** [comment]
@NthPortal Could you reopen this as a contender?

**Comment by NthPortal** [comment]
@eed3si9n I guess, but I *really* don't like it. I am strongly against a solution where the default behavior is that you need to remember to use `compare` and not `lt` (or vice versa), because the other is "wrong".

**Comment by Ichoran** [comment]
@NthPortal - Is it better that your code silently changes behavior from underneath you with no warning from 2.12?

That is the choice.

**Comment by NthPortal** [comment]
I don't know.

tbh, I think throwing an exception when NaN is encountered may be the most sane thing to do by default

**Comment by eed3si9n** [comment]
@NthPortal 

> I guess, but I *really* don't like it. I am strongly against a solution where the default behavior is that you need to remember to use `compare` and not `lt` (or vice versa), because the other is "wrong".

I am very much sympathetic to not liking it. It hurts my brain that this "wrong" implementation is overall the least wrong solution.

One potential improvement might be to rename `IeeeOrdering` to `InconsistentButPragmaticOrdering` or `JavaCompatibleOrdering` when we are allowed to in Scala 3.1.

**Comment by NthPortal** [comment]
@eed3si9n `IeeeOrdering` *isn't* consistent with how Java handles floating point numbers in ordering-related contexts *at all*.

**Comment by eed3si9n** [comment]
@NthPortal Here's what I mean by Java-compatible in `JavaCompatibleOrdering`.

In Java, sorting is total or whatever we call `java.lang.Double.compare` is doing AND both `<` and `<` operator return `false` when you involve NaN.

```
$ jshell
|  Welcome to JShell -- Version 11.0.4
|  For an introduction type: /help intro

jshell> import java.lang.Double

jshell> Double.NaN < 1.0
$2 ==> false

jshell> Double.NaN > 1.0
$3 ==> false

jshell> import java.lang.Math

jshell> Math.min(Double.NaN, 1.0)
$5 ==> NaN

jshell> Math.max(Double.NaN, 1.0)
$6 ==> NaN
```

**Comment by NthPortal** [comment]
@eed3si9n as far as I'm concerned, `lt` et al. are just shorthand for `compare`, in much the same way that the methods on `SizeCompareOps` (returned by `sizeIs and lengthIs`) are shorthand for `sizeCompare`/`lengthCompare`. if you happen to be able to make them more efficient than calling `compare`, cool I guess? but they ought to be indistinguishable

**Comment by SethTisue** [comment]
I think we can close this PR. I believe it's not acceptable to change the runtime behavior of 2.13.2, relative to 2.13.0. (Relative to 2.12 is fine, as long as we have a migration or deprecation warning. We plan to replace the deprecation with a migration warning.)

**Pull request closed without merging**
