### PR TITLE
[SI-6502] fixed :cp command

### PR DESCRIPTION
**Pull request by machisuji**
by recreating interpreter for :cp command instead of merely resetting

Could not figure out how to the reset so that the compiler classpath is updated properly too.
Simply recreating (as was done before) does the job too though and all tests pass ... except the one for this commit that is ...

**NOT READY TO MERGE**

The test succeeds when I run `./test/partest test/files/run/cp-cmd/cp-cmd.scala` but fails with `./test/partest test/files/run/cp-cmd` which is what happens when the overall test suite is run, though. **Any ideas why that is?** The output is definitely correct (no difference between the run log and the check file).

**PathSetting**

PathSetting's `append` did not work correctly. Had to fix that to make the test pass as well.
The way it was implemented the `MutableSettings.SettingValue#postSetHook` was not triggered anyway which is unexpected behaviour IMO.

### CODE REVIEW

**Comment by som-snytt** [comment]
I have a different fix targeting 2.11; it's needs ironing. I was hoping for and/or wary of a big refactoring of ClassPath. The idea is that repl maintains a special location in the class path for its augmentedClassPath, and when you append to it using cp, it calls invalidateClassPathEntries (or an overload that takes the ClassPath entry directly instead of a String that is assumed to refer to a disk location).

It would still be nice to have this on 2.10, to work as well as 2.9.  Is there any reason it was disabled in this way, though?

Someone just had a question on SO about putting something on the REPL cp.  The answer was just use sbt console.  I was trying to think of a compelling use case where you want to try something out, then add a library, perhaps picking up some implicits, and try an expression again.

**Comment by som-snytt** [comment]
That's funny that you got mixed up in that class path setting.

I haven't figured it out yet, but I was using the append business in `newCompiler`:

```
    settings.lookupSetting("-classpath/a") foreach {
      case s: settings.StringSetting => s.value = ReplClassPathContext.ReplLocation
      case _ =>
    }
```

The hitch is that there is no "-classpath/a" to look up unless there is "-classpath" already.  I think.

**Comment by machisuji** [comment]
I definitely need to be able to add something to the classpath in 2.10. That's the reason I wanted a fix for that in the first place.

Still don't know why the test succeeds when run directly (the scala file) but fails when only the directory is used. The build would not fail if it weren't for that issue. I'm working on it.

**Comment by som-snytt** [comment]
Wait, is this actual build error?

https://scala-webapps.epfl.ch/jenkins/job/pr-scala-rangepos/1849/console

I'm distracted because my daughter is practicing piano and it sounds kind of good.

**Comment by machisuji** [comment]
Oh looks like it. I'm looking into it. You enjoy your daughter's performance.

**Comment by machisuji** [comment]
It would seem that my change to PathSettings causes the build to fail at _locker.comp_ which surprises me but of course I'm still far away from seeing the big picture.

**Comment by gourlaysama** [comment]
Oh, I had looked into this fixing this the same way you did, but somehow I can't find that branch anymore: It should work, but there is a catch.

Calling `closeInterpreter(); createInterpreter()` doesn't completely replace the old one with the new because of two lazy vals (`javap` and `power`). If they were accessed before calling `:cp`, they will retain a reference to the old `intp`. The old interpreter never gets released, and it breaks the `:javap` and `:power` command for the new.

You need to reset those vals (sadly, this means no lazy val anymore) after `closeInterpreter()`.

**Comment by som-snytt** [comment]
javap has to probe if it's on java6 or java7 etc, but maybe interactively it's no big deal to do that on every invocation?

**Comment by retronym** [comment]
It sounds like this PR still has some work involved. I'm closing this for now, but please do persist and resubmit!

**Comment by machisuji** [comment]
Will do!

**Pull request closed without merging**
