### PR TITLE
Make contains accept subtypes of A

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/scala/bug/issues/10831

This renames existing covariant `contains` method as `containsAny`
and introduces an invariant `contains` as an extension method.

### CODE REVIEW

**Comment by eed3si9n** [comment]
Here are some places that this `contains` found that might be suspicious.

```
[info] Compiling 2 Scala sources to /Users/eed3si9n/work/scala/build/quick/classes/compiler...
[error] /Users/eed3si9n/work/scala/src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala:317: type mismatch;
[error]  found   : SpecializeTypes.this.global.AliasTypeSymbol
[error]  required: SpecializeTypes.this.global.Type
[error]       (concretes contains AnyRefClass) || (concretes contains site.memberType(tvar))
[error]                           ^
[error] /Users/eed3si9n/work/scala/src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala:411: type mismatch;
[error]  found   : SpecializeTypes.this.global.AliasTypeSymbol
[error]  required: SpecializeTypes.this.global.Type
[error]     if (isBoundedGeneric(sym.tpe) && (types contains AnyRefClass))
[error]                                                      ^
[error] /Users/eed3si9n/work/scala/src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala:990: type mismatch;
[error]  found   : SpecializeTypes.this.global.Symbol
[error]  required: SpecializeTypes.this.global.Type
[error]         val tps1 = if (sym.isConstructor) tps filter (sym.info.paramTypes contains _) else tps
[error]                                                                                    ^
```

**Comment by lihaoyi** [comment]
I don't think a patch like this to special-case `Seq.contains` is worth doing, as explained [here](https://contributors.scala-lang.org/t/type-safe-contains/2334/20?u=lihaoyi)

**Comment by sjrd** [comment]
I think I've read somewhere that this trick would be ineffective in dotty, because its inference is smarter.

**Comment by Jacoby6000** [comment]
I don't think it makes sense to apply that logic to a valuable Scala change, but that involves an entire other discussion about how dotty and Scala shouldn't share a standard library, since they are different languages.

**Comment by SethTisue** [comment]
Scala 2.14 and 3.0 will share the same standard library, that remains a cornerstone of our migration plan.

I think we'd need consensus on this change (on https://contributors.scala-lang.org, I think, since it's a prominent change to something basic, and the discussion here was inconclusive) before it could become potentially mergeable.

**Pull request closed without merging**
