### PR TITLE
Adding JDK7 friendly build.

### PR DESCRIPTION
**Pull request by jsuereth**
Essentially this just disables swing if you're on JDK7 so you can actually build and use Scala.

FOR REALZ this time.

Review by @lrytz or @paulp

### CODE REVIEW

**Comment by paulp** [comment]
It fails in docs.lib - I guess swing has to be excluded there too.

I'm not sure what the "you can't build a distribution" line implies.  It's pretty inconvenient if it literally won't let me build a distribution without having to carry local hacks around.  I never use swing, most people never use swing, it isn't part of the distribution I'm interested in. "this-is-not-a-real-distribution" could be added to the version string.

**Comment by jsuereth** [comment]
No.  It needs scalacheck on the class path.   This also breaks the partest
artifact that I know one person uses for compiler plugin testing.  (I.e. we
have to distribute our version of scalacheck for largest to work now).

We can stop publishing pastest, or embed scalacheck etc.
On Jun 13, 2012 10:49 PM, "Paul Phillips" <
reply@reply.github.com>
wrote:

**Comment by paulp** [comment]
There were too many pronouns and nouns unknown to me, and I couldn't connect the dots.  What is "it" that needs scalacheck on the classpath, and why doesn't it have that? What is "No." in reference to? What is the "This" in "This also breaks" ? What is "largest", is that a typo or the name of something which does compiler plugin testing, and how does it figure into this? In general, which question/statement of mine, if any, are you addressing in the above?

**Comment by jsuereth** [comment]
Yeah, my brain wasn't working.  I was thinking of your partest fix which _does_ need to be discussed because it adds a dependency on scalacheck to partest that will break users of partest (all 3 of them outside the scala distribution).

I can fix the docs part of swing.  Which goal to you need to work?  I was just checking partest....

**Comment by jsuereth** [comment]
Closing until docs part of JDK7 build is fixed.

**Comment by paulp** [comment]
I need "fastdist" to work, although in truth what I really want is another goal which doesn't exist, "fasterdist", which does not build scaladoc.  It would be nothing but "pack" + "put that stuff into dist structure."

**Comment by jsuereth** [comment]
PartialDist?   I'll try that in the updated pull.
On Jun 14, 2012 8:11 AM, "Paul Phillips" <
reply@reply.github.com>
wrote:

**Pull request closed without merging**
