### PR TITLE
(2.10.x) codifies the state of the art wrt SI-8104

### PR DESCRIPTION
**Pull request by xeno-by**
As it was discovered in SI-8104, whiteboxity doesn’t apply equally to
type parameters and type members of materialized type classes.

During implicit search and subsequent type inference, whitebox type parameters
are consistently erased to wildcards, whereas whitebox type members sometimes
remain as is and get in the way of signature conformance checks.

Unfortunately, 2.10.x can’t make use of type parameter whiteboxity, because
it requires fundep materializers that were only merged into 2.11:
https://github.com/scala/scala/pull/2499, and therefore Si-8104 seems to be
a hard blocker for 2.10.x at the moment. Stay tuned for updates.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
@retronym Updated this pull request as well

**Comment by retronym** [comment]
LGTM

**Comment by retronym** [comment]
@xeno-by I left the JIRA ticket open; I'll let you decide what to do with it.

**Pull request merged**
