### PR TITLE
SI-6812 scaladoc can opt out of expanding macros 

### PR DESCRIPTION
**Pull request by xeno-by**
This is a temporary change, possible only because macros currently can't
affect the global symbol table (except for the case when they will steer
inference of a method's return type).

Later on, e.g. with the addition of c.introduceTopLevel in master,
we will have to upgrade Scaladoc to allow for separate generation of
documentation, because then we'll be forced to expand macros in order to
get the whole picture of the code.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym @harrah @vigdorchik @VladUreche

**Comment by xeno-by** [comment]
@harrah could you please also elaborate on your use case, which led to submission of SI-6812? If I understand everything correctly, we have separate build tasks for `docs.lib` and `docs.comp`. How come separate compilation works for us and not for you? What am I missing?

**Comment by retronym** [comment]
Can we rewire this to something like the following? Seems like we should perform a best effort to expand macros, and then fall back to the static return type of the macro.

```
try {
  expand(expandee)
catch {
  case _: MacroNotAvailableException if forScaladoc => expandee
}
```

**Comment by xeno-by** [comment]
@retronym Sure we can, but I think consistency is important here. Omitting only a part of expansions is, imho, just as bad as omitting everything. In the latter case it's at least predictable. WDYT?

I also thought about introducing a flag, which would disable macro expansion for Scaladoc. Or a flag, which would enable it, having "everything disabled" as a default. Though we already have quite a lot of flags.

**Comment by harrah** [comment]
@xeno-by scaladoc can't merge separately generated documentation.  In particular, you can't get a single landing page/index.

**Comment by retronym** [comment]
I think the majority of macro callers will call other peoples macros (including those in the stdlib). They will expect the inferred method types to work in Scaladoc. So we should expand by default.

On the other hand, we should fail gracefully in the (relatively rare) case when macro impls and calls are being ScalaDocced together. You could log a warning when that happens, and silence the warning with a flag, or even just a system property.

A broader change would be to avoid typing method bodies when the return type is explicitly ascribed, which would also reduce how often this situation arises. But when I tried to implement that it wasn't as localized as I hoped, so perhaps better to leave that one to a Scaladoc expert.

**Comment by harrah** [comment]
I'd be surprised if it is that rare relative to the number of projects defining macros, but certainly less common than those using the macros.  The guidelines being that return types should be explicitly annotated, I'm not sure we should consider the case of macros changing the return type as any more common.  Regardless, I have no problem with passing a flag.

**Comment by xeno-by** [comment]
@retronym Inferred return types will only work incorrectly when a macro expansion produces something having a type stricter than warranted by the signature of the macro def.

**Comment by retronym** [comment]
The new crop of macros that convert, for example, between case class and tuples will require the expanded return types. We should make a best effort to expand them.

**Comment by xeno-by** [comment]
That's why the commit message mentions that it's a temporary change. In 2.10.x we'll be fine in most of the most of cases. Later on we'd better fix scaladoc anyways, because otherwise we're going to suffer. Does this line of thought make sense to you?

**Comment by retronym** [comment]
To be safest, let's do this:

1) when reporting the the "cannot expand macro" error, check if `forScalaDoc` is active, and augment the error with a reference to the bug, instructions about a flag/system property to disable macro expansion under ScalaDoc.
2) add said flag

I really don't want to disadvantage projects that just consume macros by disabling expansion by default.

**Comment by xeno-by** [comment]
@retronym This sounds very convincing. Will do.

**Comment by VladUreche** [comment]
I had a look and I think @retronym is right: in the end, using the static type of a macro is not good enough in some cases. (declosurify comes to my mind as a usecase that won't work)

**Comment by gkossakowski** [comment]
Guys, just to chime in on system properties. Don't do that. They are not easily discoverable and Scala compiler is embedded in places (like IDE, sbt) where you might not have an easy control over System properties or you might want to configure this setting on per-project basis.

**Comment by xeno-by** [comment]
updated the patch as discussed

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
just reworded the commit message

**Comment by VladUreche** [comment]
LGTM, thanks for fixing this Eugene!

**Comment by xeno-by** [comment]
@retronym ping. Vlad seems happy about this PR. What about you?

**Comment by retronym** [comment]
Looks okay to me as a temporary measure. Next step would be for "best effort" macro expansion; the end-game is for Scaladoc to be compiled module-by-module with some aggregation.

**Pull request merged**
