### PR TITLE
Toning down the noise of -Xlint and allow `-optimise -Yinline:false`

### PR DESCRIPTION
**Pull request by retronym**
Motivation in the commit messages. I think the deluge of warnings
form unused imports is a regression that will turn away X-linters.

And we've had reports of spurios "unused local" warnings, too,
that suggest this feature needs more time to stabilize.

While I was in settings land, I implemented something I've been
missing for ages, the ability to disable individual settings within
a group.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm 

The first commit should be pretty uncontroversial, it just demotes the status of this warning. The second one is a convenience that isn't strictly necessary for 2.11, but does make it easier for people to configure `-Xlint` and `-optimize` when one of the components is playing up.

**Comment by adriaanm** [comment]
They all sound good to me. Most of my remaining blocker bugs are deprecation warnings, so I'll follow up with those later today.

**Comment by adriaanm** [comment]
I'll adopt this one.

**Comment by retronym** [comment]
@adriaanm Just pushed a fix. Test failure was a semantic merge conflict from a rebase, in which I decided to remove _both_ unused warnings out of the lint group.

**Comment by adriaanm** [comment]
LGTM I'm so glad we finally have true/false symmetry for boolean settings. Been wanting this for a long time!

**Comment by som-snytt** [comment]
That's great; I've needed granularity with just a little xlinting. Also, REPL has that `:se +Xlint` which should be retrofitted to `:se -Xlint:true`. (For example, assuming Xlint stays boolean instead of levels or whatever.)  I don't know if that code is tested in REPL; I'll check.

**Comment by retronym** [comment]
@som-snytt: I actually noticed that REPL command when looking for a command-line way to do this, I hadn't seen it before.

There is another opportunity that I couldn't grasp: replaceing `-Ynoptimise`, which is used in half a dozen tests, by `-optimize:false`. Here's my WIP: https://github.com/retronym/scala/tree/topic/no-nooptimise

**Comment by SethTisue** [comment]
I'm now on 2.11.0-RC1 and able to reinstate `-Xfatal-warnings` in my build. Yay!!

**Comment by adriaanm** [comment]
Glad to hear it! More in store at my report-filter branch.

**Pull request merged**
