### PR TITLE
further tweaks to the ant build

### PR DESCRIPTION
**Pull request by adriaanm**
review by review roulette

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @gkossakowski

**Comment by adriaanm** [comment]
TODO: this is waiting for one more commit (Eugene's fix in #2313)

**Comment by paulp** [comment]
I eagerly await this merge; I just blithely duplicated some of this work (not that I have any excuse.)

**Comment by gkossakowski** [comment]
I'll review it this afternoon.

On Wednesday, March 27, 2013, Paul Phillips wrote:

> I eagerly await this merge; I just blithely duplicated some of this work
> (not that I have any excuse.)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scala/scala/pull/2314#issuecomment-15538801
> .

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by som-snytt** [comment]
But wait, there's more?  The merge of Paul's Testicolor touches the test targets and adds test.suite.color.

**Comment by paulp** [comment]
@gkossakowski @adriaanm how are we doing here? The PR tubes are very clogged. There are already multiple "good to merge" PRs which are going to conflict with one another. I am reluctant to merge anything. If we can get this into 2.10.x and also finish merging 2.10.x into master it would help clarify the situation with the others (and it would be nice to fix ant - the impairment I endure from all the temporary struts is higher than I care to admit.)

**Comment by adriaanm** [comment]
I think this is all pretty safe to merge. I perhaps shouldn't have burdened @gkossakowski with this. I'll accept LGTM from (just about) anyone.

**Comment by gkossakowski** [comment]
Sorry for delay. I'm looking at it right now.

**Comment by gkossakowski** [comment]
I looked at everything but 3ec36bb and it looks good to me. I'll look at 3ec36bb more closely in an hour and then I'll give final stamp of approval.

**Comment by gkossakowski** [comment]
LGTM.

Thanks a lot for great work!

**Pull request merged**
