### PR TITLE
SI-6803: do not use java.net.URI, even more so incorrectly.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @harrah

**Comment by vigdorchik** [comment]
@harrah The idea behind using java.net.URI was to make it automatically escape special characters in file path. Given that, on a second check, URI doesn't escape any way, I have changed it to simple split, and now the clients have to make sure the path are escaped.

**Comment by vigdorchik** [comment]
@harrah Added the error, unfortunately it will be deferred until a lazy val is calculated. Unfortunately this calculation has to be lazy.

**Comment by adriaanm** [comment]
ping @harrah, I'd like to get this merged

**Comment by harrah** [comment]
@adriaanm Me too, sorry about that.

LGTM.

**Comment by adriaanm** [comment]
no prob -- thanks!

**Pull request merged**
