### PR TITLE
Merge master to 2.11.x

### PR DESCRIPTION
**Pull request by retronym**
master is now retired. 

Here's its final breath:

```
git show origin/master
commit af6941fbcf6f4f4efeb372a9a937463ff630b81c
Merge: 6f33b24 bdb1258
Author: Jason Zaugg <jzaugg@gmail.com>
Date:   Fri May 9 17:21:33 2014 +0200

    Merge pull request #3732 from retronym/revert/5905

    Revert "SI-5905 Clarify test case"
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by retronym** [comment]
```
git push origin :master
To git@github.com:scala/scala.git
 - [deleted]         master
```

**Comment by adriaanm** [comment]
Farewell, sweet master, we hardly knew ye.

**Comment by adriaanm** [comment]
Is bdb1258 supposed to be included in this one?

**Comment by retronym** [comment]
Good catch, fixed.

**Comment by adriaanm** [comment]
LGTM!

**Comment by gkossakowski** [comment]
:+1: to master being gone

**Comment by retronym** [comment]
PLS SYNCH

**Comment by retronym** [comment]
@adriaanm @lrytz 

I'm currently replacing references to `master` with `2.11.x` in relevant, enabled Jenkins jobs, based on:

```
% git grep --files-without-match 'disabled>true' | xargs git grep master
config.xml:        <string>scala-merge-reminder-master-to-2.11.x</string>
config.xml:        <string>scala-nightly-main-master</string>
config.xml:  <label>master</label>
jobs/a-pull-config/config.xml:  <assignedNode>master</assignedNode>
jobs/a-pull-config/config.xml:git pull origin master
jobs/a-push-config/config.xml:  <assignedNode>master</assignedNode>
jobs/a-push-config/config.xml:git checkout master
jobs/a-push-config/config.xml:git pull --rebase origin master
jobs/a-push-config/config.xml:git push origin master</command>
jobs/new-slave/config.xml:  <assignedNode>master</assignedNode>
jobs/ping-rev-lister/config.xml:      <command>wget http://scala-webapps.epfl.ch/rev-lister/origin/master%5E..origin/master &gt; /dev/null</command>
jobs/pr-scala-distpack/config.xml:          <defaultValue>master</defaultValue>
jobs/pr-scala-integrate-ide/config.xml:          <defaultValue>master</defaultValue>
jobs/pr-scala-integrate-partest/config.xml:          <defaultValue>master</defaultValue>
jobs/pr-scala-publish-core/config.xml:          <defaultValue>master</defaultValue>
jobs/pr-scala-rangepos/config.xml:          <defaultValue>master</defaultValue>
jobs/pr-scala-test/config.xml:          <defaultValue>master</defaultValue>
jobs/pr-scala/config.xml:          <defaultValue>master</defaultValue>
jobs/production_scala-lang.org-builder/config.xml:        <name>master</name>
jobs/scala-checkin-manual-rangepos/config.xml:  <description>Run the rangepos test suite on the specified branch merged into scala/scala master</description>
jobs/scala-dist-resolves/config.xml:wget https://github.com/scala/scala-dist/archive/master.zip
jobs/scala-dist-resolves/config.xml:unzip master.zip &amp;&amp; rm master.zip &amp;&amp; cd scala-dist-master
jobs/scala-dist/config.xml:  (Note: any git ref will do, as long as it exists both on scala/scala and scala/scala-dist. For example: master, 2.10.x.)&#xd;
jobs/scala-lang.org-builder/config.xml:        <name>master</name>
jobs/scala-merge-reminder-master-to-2.11.x/config.xml:We can retire this build after we retire the master branch.</description>
jobs/scala-merge-reminder-master-to-2.11.x/config.xml:          <defaultValue>master</defaultValue>
jobs/scala-nightly-publish/config.xml:          <defaultValue>master</defaultValue>
jobs/scala-release-2.11.x/config.xml:  Once this job completes, close the staging repo (see https://github.com/adriaanm/binfu/blob/master/sonafu.sh for scripts),&lt;br&gt;&#xd;
jobs/scalajs-matrix-build/config.xml:          <defaultValue>origin/master</defaultValue>
jobs/scalajs-nightly/config.xml:  <dsl>// Get SHA1 from master (must remain constant during run)
jobs/scalajs-nightly/config.xml:  if (fields[1] == &quot;refs/heads/master&quot;)
jobs/scalajs-nightly/config.xml:  throw new Exception(&quot;origin/master not found!&quot;)
jobs/scalajs-nightly/config.xml:  out.println(&quot;Building origin/master @ $resultSha&quot;)
jobs/scalajs-task-worker/config.xml:          <defaultValue>origin/master</defaultValue>
jobs/scalameter-wip-nightly/config.xml:        <name>master</name>
jobs/stage-pr-scala-integrate-ide/config.xml:          <defaultValue>master</defaultValue>
jobs/stage-pr-scala-integrate-partest/config.xml:          <defaultValue>master</defaultValue>
jobs/stage-pr-scala-publish-core/config.xml:          <defaultValue>master</defaultValue>
jobs/stage-pr-scala-rangepos/config.xml:          <defaultValue>master</defaultValue>
jobs/stage-pr-scala-test/config.xml:          <defaultValue>master</defaultValue>
org.jenkinsci.plugins.ghprb.GhprbTrigger.xml:            <target>master</target>
org.jenkinsci.plugins.ghprb.GhprbTrigger.xml:            <target>master</target>
org.jenkinsci.plugins.ghprb.GhprbTrigger.xml:            <target>master</target>
```

**Pull request merged**
