### PR TITLE
Backport fix for Zip RootEntry

### PR DESCRIPTION
**Pull request by som-snytt**
Backport https://github.com/scala/scala/pull/8447

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
Thank you!

**Comment by lrytz** [comment]
I didn't look closely, but it seems the original PR https://github.com/scala/scala/pull/8447 caused some issues in the test suite on windows, follow up was https://github.com/scala/scala/pull/8539. Not sure if any of that will be necessary here, let's keep an eye on it.

**Comment by som-snytt** [comment]
Possibly, I ported the latest version of the test, and the other test `t11802` isn't on `2.12.x`. Where is my shrug emoji?

**Comment by SethTisue** [comment]
@som-snytt in the ongoing saga of no good deed going unpunished, https://github.com/scala/scala-dev/issues/724

**Comment by som-snytt** [comment]
OK, found it `¯\_(ツ)_/¯`

**Pull request merged**
