### PR TITLE
Upgrade Dotty to latest release candidate

### PR DESCRIPTION
**Pull request by prolativ**

### CODE REVIEW

**Comment by SethTisue** [comment]
```
[error] -- Error: /home/travis/build/scala/scala/target/library/src_managed/main/scala3-library-src/scala/annotation/experimental.scala:14:6 
[error] 14 |class experimental extends StaticAnnotation
[error]    |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |use of @experimental is experimental and therefore may only be used with a nightly or snapshot version of the compiler
```

perhaps @anatoliykmetyuk could help us here...?

**Comment by anatoliykmetyuk** [comment]
We had the same problem when trying to release `3.0.1-RC1`. It was caused by the fact that for the release, we need to set TASTy version to disallow experimental features. But the Dotty's library uses them, and so we must make an exception to allow experimental features in it to produce bootstrapped compiler for the release. This was done in lampepfl/dotty#12672.

This commit tells the compiler that experimental features are allowed if the version of the compiler contains `nonbootstrapped`, therefore indicating that this compiler is used to compile the bootstrapped compiler.

I'm not sure what the scala/scala tries to test here with Dotty, but my guess would be that an attempt is made to compile the Dotty's standard library with a given version of Dotty. However, given the restrictions above, you can't really compile Dotty's standard library with any stable or RC release – only the nonbootstrapped compiler (unavailable publically) will work.

What exactly is being tested here, trying to compile the Dotty's library with a given Dotty release?

**Comment by SethTisue** [comment]
> What exactly is being tested here, trying to compile the Dotty's library with a given Dotty release?

The idea is that Scala 3 ought to be able to compile the Scala 2 standard library, for multiple reasons:

1) It helps QA the Scala 3 compiler.
2) It helps QA the Scala 2 standard library, since the Scala 3 compiler may reject bad code that Scala 2 accepts.
3) It helps make sure we are ready for the glorious future day when Scala 3.T (Scala 4?) breaks free of Scala 2 entirely and starts using a Scala-3-built standard library.

This was added to our CI by @smarter in #7800.

**Comment by SethTisue** [comment]
But why the sources of scala3-library would need to be part of this, I don't know. Maybe @smarter and/or @bishabosha can address that

20a1e68be473dfee7ac365cfea236e07859e365b seems relevant here (it was part of #8525). Guillaume wrote:

> When we compile the standard library with dotty, we actually compile the scala-library and dotty-library sources together in one go since we can't in general reuse a dotty-library compiled with an old scala-library.

which I don't really understand.

**Comment by smarter** [comment]
You can run into bootstrapping issues if you don't include scala3-library in the set of files being compiled: it means we fallback to depending on a published scala3-library which itself depends on a published scala-library while we're trying to compile a new binary-incompatible scala-library. This was especially problematic when transitioning from 2.12 to 2.13, but I don't know if anything would go wrong for this test if we dropped that today (compiling both together would definitely be needed if one wanted to put the new library on the compiler classpath, which I think would be a very useful thing to test but which isn't tested currently)

**Comment by dwijnand** [comment]
> while we're trying to compile a new binary-incompatible scala-library. This was especially problematic when transitioning from 2.12 to 2.13

We're not going to be compiling a new binary incompatible scala-library any time soon (even), as I see it.

> (compiling both together would definitely be needed if one wanted to put the new library on the compiler classpath, which I think would be a very useful thing to test but which isn't tested currently)

Which library and which compiler?  New scala3-library on scala-compiler's classpath?

Personally it sounds to me like we should switch to using the existing scala3-library jar, avoid the bootstrapping problem.

**Comment by smarter** [comment]
> Which library and which compiler? 

This is a digression from this issue but the idea is: We start with the jars of scala-library 2.13.6, scala3-library 3.0.1, scala3-compiler 3.0.1. We would like to recompile scala-library with scala 3 and put it on the scala 3 compiler classpath, but this also requires a recompiled scala3-library since the existing scala3-library links to the scala2-compiled scala-library which is not binary compatible with the recompiled one.

**Comment by SethTisue** [comment]
@prolativ do you plan on returning to this...?

**Comment by prolativ** [comment]
Not sure if this can be done now. For now we're still using 3.0.0 as the reference compiler in dotty's repo. The discussion about the behaviour of `@experimental` is still ongoing https://github.com/lampepfl/dotty/issues/13112 and our aim is to have this stabilized no later than in 3.1.0. I think this can be closed for now and we'll try to bump the version again as soon as we have a published (stable?) release of dotty which could be used as a reference compiler

**Comment by lrytz** [comment]
@nicolasstucki with https://github.com/lampepfl/dotty/pull/13305 merged, is there a Scala 3 version out now that we can update to?

**Comment by smarter** [comment]
Yes, 3.1.0-RC3 should work.

**Comment by SethTisue** [comment]
@prolativ can you update it? once 3.1.0 is out we want to ship 2.13.7 pretty promptly afterwards, so now would be an opportune time for this.

**Comment by SethTisue** [comment]
I was about to hit "approve" on this when I noticed that Travis-CI isn't running, so the change isn't being tested.

I've opened https://github.com/scala/scala-dev/issues/793 on that; we'll need to hold this PR until that's fixed

**Comment by lrytz** [comment]
Rebasing didn't help. Ah, it's not only about this PR...

**Comment by SethTisue** [comment]
@prolativ do you have time to return to this in time for 2.13.7? we're looking to release promptly right around November 1

**Comment by prolativ** [comment]
If we bump dottyVersion to 3.1.0 or 3.1.1-RC1 then it seems the only remaining problem is the definitions of 4 macros in the stdlib because they are marked as erased by the compiler (this behaviour originated here https://github.com/lampepfl/dotty/pull/8811). Since erased definitions are still experimental, the compilation fails because they're not defined in an experimental scope.
Actually there seem to be some hacks hardcoded in the compiler to make these special cases work (here https://github.com/lampepfl/dotty/blob/435207d6e9cfd29d8df467dc6796007525b3ff89/compiler/src/dotty/tools/dotc/core/SymDenotations.scala#L972 and here https://github.com/lampepfl/dotty/blob/435207d6e9cfd29d8df467dc6796007525b3ff89/compiler/src/dotty/tools/dotc/transform/PostTyper.scala#L162), which don't actually seem to be enough and probably should be removed.
@nicolasstucki @smarter what's the purpose of marking scala 2 macros as erased? Do you have any idea how this could be fixed?

**Comment by bishabosha** [comment]
> @nicolasstucki @smarter what's the purpose of marking scala 2 macros as erased? Do you have any idea how this could be fixed?

they were marked erased to distinguish them from scala 3 macro which are inline, but we are tracking the issue at https://github.com/lampepfl/dotty/issues/13793

**Comment by SethTisue** [comment]
@prolativ any news? it's starting to look like we might need to build 2.13.8 after only 1-2 months rather than 6 months like last time

**Comment by bishabosha** [comment]
lampepfl/dotty#13793 was merged and backported, so the issue for macros will be solved in the next patch Scala 3 release

**Comment by prolativ** [comment]
It looks like this should already work with dotty's latest master but we would need a stable release to use instead of 3.1.0-RC3. We could potentially backport the fix and release 3.1.1-RC2. But we'll have to discuss the details on Monday.

**Comment by SethTisue** [comment]
> the next patch Scala 3 release

@prolativ does that mean you can return to this once 3.1.1-RC2 is out?

**Comment by prolativ** [comment]
Yes, as soon as the release completes successfully

**Comment by SethTisue** [comment]
```
[error] Failed to parse `-Wconf` configuration: cat=unchecked&msg=The outer reference in this type test cannot be checked at run time.:s,cat=optimizer:is,cat=unused-nowarn:s
[error] unknown category: optimizer
[error] unknown category: unused-nowarn
[error] Note: for multiple filters, use `-Wconf:filter1:action1,filter2:action2`
[error]       or alternatively          `-Wconf:filter1:action1 -Wconf:filter2:action2`
[error] bad option '-Xlint' was ignored
[error] Flag -feature set repeatedly
[error] bad option '-Yerased-terms' was ignored
[error] four errors found
[error] (library / Compile / compileIncremental) Compilation failed
```

**Comment by nicolasstucki** [comment]
```
[error] bad option '-Yerased-terms' was ignored
```
Just remove the flag, it does not exist anymore in any form. Now we use language imports `scala.language.experimental.erasedDefinitions` but this should not be required to compile Scala 3.

**Comment by SethTisue** [comment]
@prolativ this passed locally for me. if CI likes it, can you squash/rebase, and we'll be done?

**Comment by lrytz** [comment]
``[error] Failed to parse `-Wconf` configuration: cat=unchecked&msg=The outer reference in this type test cannot be checked at run time.:s,cat=optimizer:is,cat=unused-nowarn:s``

**Comment by prolativ** [comment]
@lrytz when I compile the code I get only warnings about `-Wconf`, not errors. However it looks like CI is broken in some other way
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact org.scala-lang:scala-library:jar:2.13.8-bin-b452ddb-SNAPSHOT in temp (https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/)
```

**Comment by lrytz** [comment]
Yeah, our warnings are only fatal in CI: https://github.com/scala/scala/blob/f11f1f71c94511319f66913668eb8ca2cb64615f/build.sbt#L57

**Comment by lrytz** [comment]
> CI is broken

Yes, working on that.. EDIT: fixed

**Comment by prolativ** [comment]
Are we then going to actually get rid of all the warnings? There are quite a lot of them and they would require some changes in the implementation of stdlib.

**Comment by lrytz** [comment]
I haven't looked at those. The Scala 2 compiler is not giving any of those warnings on the library, so perhaps dotty has more accurate checks?

**Comment by prolativ** [comment]
Some of the warnings are about wrong value of `@nowarn`:
```scala
 Invalid message filter
 unknown filter: origin
```
There are some deprecation warnings which seem to be caused by the problem with `@nowarn`.

Some warnings are about pattern matching:
a) during type tests for generic types, e.g.
```scala
[warn] 214 |      case m: Map[K, V] => m
[warn]     |           ^
[warn]     |           the type test for Map[K, V] cannot be checked at runtime
```
but hopefully they should be easy to fix by replacing the unused types by underscores like `case m: Map[_, _] => m`
b) one exhaustivity check seems buggy in scala 3:
```scala
      unit match {
        case DAYS => FiniteDuration(length, unit)
        case HOURS => coarserOrThis(DAYS, 24)
        case MINUTES => coarserOrThis(HOURS, 60)
        case SECONDS => coarserOrThis(MINUTES, 60)
        case MILLISECONDS => coarserOrThis(SECONDS, 1000)
        case MICROSECONDS => coarserOrThis(MILLISECONDS, 1000)
        case NANOSECONDS => coarserOrThis(MICROSECONDS, 1000)
      }
```

```scala
[warn] 722 |      unit match {
[warn]     |      ^^^^
[warn]     |match may not be exhaustive.
[warn]     |
[warn]     |It would fail on pattern case: NANOSECONDS, DAYS, HOURS, MINUTES, SECONDS, MILLISECONDS
[warn]     |(More unmatched cases are elided)
```

c) regarding one check I'm not sure if this is a bug in exhaustivity checking or something indeed changed in the language that would make this not work
```scala
    def skipToQuote(q: Int) = {
      var escaped = false
      def terminal = in.charAt(pos) match {
        case _ if escaped => escaped = false ; false
        case '\\'         => escaped = true ; false
        case `q`          => true
        case _            => false
      }
      while (!done && !terminal) pos += 1
      !done
    }
```

```scala
[warn] 46 |        case `q`          => true
[warn]    |             ^^^
[warn]    |             Unreachable case
```

**Comment by lrytz** [comment]
Was `-Werror` actually enabled, so far, when compiling the library with Scala 3?

**Comment by prolativ** [comment]
As you pointed out `-Werror` is actually enabled in CI via sbt setting
```scala
Global / fatalWarnings := insideCI.value
```
However it looks like the implementation of `-Wconf` for scala 3 https://github.com/lampepfl/dotty/pull/12857 doesn't handle `origin` filter

**Comment by lrytz** [comment]
Oh, so this is the first upgrade to a Scala 3 version that supports `-Wconf`, and also `-Werror` (https://github.com/lampepfl/dotty/commit/da3dae83ca)?

Were these flags silently ignored before? Then I'd recommend not passing those flags to the Scala 3 compiler.

**Comment by prolativ** [comment]
Should I then simply set `Global / fatalWarnings` to false when compiling with scala 3?
Passing `-Wconf` as a compiler option doesn't seem to cause problems - the compiler complains about config placed inside annotations in the codebase

**Comment by SethTisue** [comment]
I don't think there was ever any intent for the library to compile on Scala 3 warnings-free.

**Comment by lrytz** [comment]
> Passing `-Wconf` as a compiler option doesn't seem to cause problems

It causes the ``Failed to parse `-Wconf` configuration`` error

**Comment by prolativ** [comment]
Right, I missed this one. But anyway would it be OK to disable `fatalWarnings` then or do you have a better idea? If we'd like to improve the compiler to get rid of these warnings the changes would probably get into the compiler not earlier than in 3.1.3-RC1 or 3.2.0-RC1 depending on what would be the next version after 3.1.2

**Comment by lrytz** [comment]
Yes, I'm suggesting to not pass `-Werror` and `-Wconf` to the Scala 3 compiler. You could do it here:

https://github.com/scala/scala/blob/f11f1f71c94511319f66913668eb8ca2cb64615f/project/DottySupport.scala#L42

**Comment by SethTisue** [comment]
Thanks Michał!

**Pull request merged**
