### PR TITLE
Preferred parens in junit tests

### PR DESCRIPTION
**Pull request by som-snytt**
Reduce build noise.

### CODE REVIEW

**Comment by som-snytt** [comment]
Or maybe increase build noise.
```
+Uncaught exception on thread Thread[Reflector-296,5,main]: java.lang.IndexOutOfBoundsException: -1 is out of bounds (min 0, max 1)
+java.lang.IndexOutOfBoundsException: -1 is out of bounds (min 0, max 1)
+	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:96)
+	at scala.reflect.internal.tpe.TypeConstraints.containsSymbol(TypeConstraints.scala:205)
+	at scala.reflect.internal.tpe.TypeConstraints.solveOne$1(TypeConstraints.scala:256)
+	at scala.reflect.internal.tpe.TypeConstraints.$anonfun$solve$8(TypeConstraints.scala:290)
+	at scala.reflect.internal.tpe.TypeConstraints.solve(TypeConstraints.scala:290)
+	at scala.reflect.internal.tpe.TypeConstraints.solve$(TypeConstraints.scala:218)
+	at scala.reflect.internal.SymbolTable.solve(SymbolTable.scala:28)
+	at scala.reflect.internal.Types$ExistentialType.withTypeVars(Types.scala:3209)
+	at scala.reflect.internal.tpe.TypeComparers.thirdTry$1(TypeComparers.scala:553)
+	at scala.reflect.internal.tpe.TypeComparers.secondTry$1(TypeComparers.scala:520)
+	at scala.reflect.internal.tpe.TypeComparers.firstTry$1(TypeComparers.scala:496)
+	at scala.reflect.internal.tpe.TypeComparers.isSubType2(TypeComparers.scala:616)
+	at scala.reflect.internal.tpe.TypeComparers.isSubType1(TypeComparers.scala:348)
+	at scala.reflect.internal.tpe.TypeComparers.isSubType(TypeComparers.scala:306)
+	at scala.reflect.internal.tpe.TypeComparers.isSubType$(TypeComparers.scala:268)
+	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:28)
+	at scala.reflect.internal.Types$Type.$less$colon$less(Types.scala:814)
+	at scala.reflect.internal.Types$Type.$less$colon$less(Types.scala:270)
+	at Test$.$anonfun$tasks$1(reflection-sync-subtypes.scala:7)
+	at Test$$anon$1.$anonfun$run$1(reflection-sync-subtypes.scala:15)
+	at Test$$anon$1.$anonfun$run$1$adapted(reflection-sync-subtypes.scala:15)
+	at Test$$anon$1.run(reflection-sync-subtypes.scala:15)
```

**Comment by som-snytt** [comment]
My bootstrap agrees with Travis.

**Review by dwijnand — APPROVED** [review]
LGTM.  Still draft?

**Pull request merged**
