### PR TITLE
SI-7918 Use scala.util.DynamicVariable instead of ad hoc implementations

### PR DESCRIPTION
**Pull request by qerub**
https://issues.scala-lang.org/browse/SI-7918

### CODE REVIEW

**Comment by som-snytt** [comment]
It probably doesn't matter for these use cases, but switching to thread locals is non-trivial.

It probably doesn't matter in the sense that everything is still assumed to be single-threaded and performance isn't critical.

**Comment by JamesIry** [comment]
LGTM. In general I vote for cleaner code rather than faster except in those few cases where faster can really be shown to be more important.

**Comment by paulp** [comment]
These examples in the repl don't make any difference, but there are dozens more of these in the compiler and I am sure you don't want to continue this substitution. That ThreadLocal is not a desirable change, and this will be way slower, which you won't have any trouble seeing it if you go after any remotely hot spot where those 3-4 lines of boilerplate exist.

When marked @inline, these calls are compiled ideally - no thunks, no thread locals, state managed on the stack. This is a local optimum, all directions away lead down. You might be able to reduce the boilerplate with a macro. That is the only change I can see making sense.

Here's a partial list of additional sites, which I offer to show how far this PR comes from eliminating these, and not as encouragement to change others. These are only the ones which matched regexp finally.*\= saved (which means I was most likely the author, or at least the tweaker) but it's not by any means complete.

```
src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:229:      finally smartParsing = saved
src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:311:      finally classContextBounds = saved
src/compiler/scala/tools/nsc/ast/parser/Parsers.scala:497:      finally inFunReturnType = saved
src/compiler/scala/tools/nsc/backend/icode/GenICode.scala:1775:      finally ctx.cleanups = saved
src/compiler/scala/tools/nsc/reporters/Reporter.scala:42:    finally _truncationOK = saved
src/compiler/scala/tools/nsc/reporters/Reporter.scala:51:    finally incompleteHandler = saved
src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala:388:        try body finally refs = saved
src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala:293:      finally outerParam = savedOuterParam
src/compiler/scala/tools/nsc/transform/Mixin.scala:1249:      finally localTyper = saved
src/compiler/scala/tools/nsc/transform/TailCalls.scala:193:      finally this.ctx = saved
src/compiler/scala/tools/nsc/transform/TailCalls.scala:396:      finally maybeTail = saved
src/compiler/scala/tools/nsc/transform/UnCurry.scala:393:        finally needTryLift = saved
src/compiler/scala/tools/nsc/transform/UnCurry.scala:412:        finally this.inConstructorFlag = saved
src/compiler/scala/tools/nsc/typechecker/Contexts.scala:189:      try a finally enclClass = saved
src/compiler/scala/tools/nsc/typechecker/Contexts.scala:314:        finally undetparams = saved
src/compiler/scala/tools/nsc/typechecker/Contexts.scala:373:      finally contextMode = saved
src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:118:      try body finally inPattern = saved
src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala:363:      finally validCurrentOwner = saved
src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala:63:    finally isTyperInPattern = saved
src/reflect/scala/reflect/internal/ExistentialsAndSkolems.scala:40:    finally skolemizationLevel = saved
src/reflect/scala/reflect/internal/Variances.scala:30:      try body finally inRefinement = saved
src/reflect/scala/reflect/internal/Variances.scala:131:        finally this.base = saved
src/reflect/scala/reflect/internal/pickling/UnPickler.scala:79:      try body finally readIndex = saved
src/reflect/scala/reflect/internal/tpe/TypeMaps.scala:198:      try body finally variance = saved
src/reflect/scala/reflect/internal/tpe/TypeMaps.scala:634:        finally if (wroteAnnotation) giveup() else wroteAnnotation = saved
src/repl/scala/tools/nsc/interpreter/ILoop.scala:92:    finally replayCommandStack = saved
src/repl/scala/tools/nsc/interpreter/ILoop.scala:97:    finally in = saved
src/repl/scala/tools/nsc/interpreter/IMain.scala:202:    finally printResults = saved
src/repl/scala/tools/nsc/interpreter/IMain.scala:208:    finally totalSilence = saved
src/repl/scala/tools/nsc/interpreter/IMain.scala:1137:    finally isettings.unwrapStrings = saved
src/repl/scala/tools/nsc/interpreter/session/FileBackedHistory.scala:28:    finally isPersistent = saved
```

**Comment by som-snytt** [comment]
Proof that @paulp still cares!  If the Scala store offered a "@paulp cares" t-shirt, I would order it right now.

+1 for walking that fine line between "not encouraging more of the same refactor" and "not discouraging more contributions."

+2 for a macro to encapsulate it.

**Comment by retronym** [comment]
DNLGTM. As Paul points out, this pattern is used widely, and in many places it is performance critical, so we can't eliminate it altogether. Let's stay consistent.

**Comment by retronym** [comment]
Here's a sketch of the macro if someone wants a fun little project:

``` scala
% tail -n 1000 sandbox/temporarily*
==> sandbox/temporarily-use.scala <==
import Temporarily._

object Test extends App {
  var x: Int = 0

  temporarily(x_=(2)) {
    println(s"temporarily: $x")
  }
  println(s"restored: $x")
}


==> sandbox/temporarily.scala <==
import reflect.macros.Context
import language.experimental.macros

object Temporarily {
  def impl[A](c: Context)(assign: c.Tree)(a: c.Tree): c.Tree = {
    val symTab = c.universe.asInstanceOf[reflect.internal.SymbolTable]
    val assign0 = assign.asInstanceOf[symTab.Tree]
    val a0 = a.asInstanceOf[symTab.Tree]
    import symTab._

    val result = assign0 match {
      case Apply(sel @ Select(qual, setter), lhs :: Nil) if sel.symbol.isSetter =>
        val getter = sel.symbol.getter(sel.symbol.owner)

        q"""
          val temp = ${qual.duplicate}.${getter}
          $assign0
          try $a0 finally ${qual.duplicate}.$setter(temp)
        """
      case _ => sys.error("TODO")
    }
    result.asInstanceOf[c.universe.Tree]
  }
  def temporarily[A](assign: Any)(a: A): A = macro impl[A]
}
```

```
% qbin/scalac sandbox/temporarily.scala && qbin/scalac -Xprint:typer sandbox/temporarily-use.scala && qbin/scala Test
[[syntax trees at end of                     typer]] // temporarily-use.scala
package <empty> {
  import Temporarily._;
  object Test extends AnyRef with App {
    def <init>(): Test.type = {
      Test.super.<init>();
      ()
    };
    private[this] var x: Int = 0;
    <accessor> def x: Int = Test.this.x;
    <accessor> def x_=(x$1: Int): Unit = Test.this.x = x$1;
    {
      val temp: Int = Test.this.x;
      Test.this.x_=(2);
      try {
        scala.this.Predef.println(scala.StringContext.apply("temporarily: ", "").s(Test.this.x))
      } finally Test.this.x_=(temp)
    };
    scala.this.Predef.println(scala.StringContext.apply("restored: ", "").s(Test.this.x))
  }
}

temporarily: 2
restored: 0
```

Unfortunately the macro implementation doesn't allow:

``` scala
temporarily(x = 2) {
  println(s"temporarily: $x")
}
```

as it treats it as a named argument. You could go for `temporarily(x, 2) { ... }` but that doesn't read quite as nicely IMO.

This sketch doesn't handle `Assign` nodes, just setters.

/cc @xeno-by

**Comment by gkossakowski** [comment]
One problem with macros in compiler's code base is that those of us that use IDEs to hack on compiler will lose some basic features like hyper linking. For example, Eclipse [doesn't](https://www.assembla.com/spaces/scala-ide/tickets/1001449-code-navigation-fails-when-macros-are-used) support code navigation as soon as macros are involved. My vote would be to not put any macros into Scala compiler's code base until tools catch up. I hope this will happen soon because I could see quite a few use cases for macros.

**Comment by JamesIry** [comment]
Okay, I'm convinced the other way now. Rescinding my LGTM on the basis that it is a common pattern and in this case cleaning up one spot actually hurts code understandability.

**Comment by JamesIry** [comment]
@qerub thanks for the PR. Sorry this one didn't make it, but please keep them coming!

**Comment by paulp** [comment]
For the record, I endorse the principles stated by submitter (eat your own dogfood) and lgtmer (clean is more important than fast in the absence of concrete evidence that it matters) but in this specific case there are a lot of factors pushing the other way.

**Comment by paulp** [comment]
> as it treats it as a named argument.

Good ol' AssignOrNamedArg.

**Comment by qerub** [comment]
@JamesIry No problem! I agree with your rationale and found the discussion enlightening.

Thanks for your time and brain cycles, all of you.

**Pull request closed without merging**
