### PR TITLE
ChainingOps: tapIf, pipeIf [ci: last-only]

### PR DESCRIPTION
**Pull request by gabrieljones**
Inspired by:
https://stackoverflow.com/a/65961480/263306
https://contributors.scala-lang.org/t/new-function-pipeif-proposal/5223

### CODE REVIEW

**Comment by som-snytt** [comment]
add `[ci: last-only]` to title to test only the last commit.

They are accepting API proposals at https://github.com/scala/scala-library-next but not here.

(I don't know when they expect to start evolving the standard library again.)

Edit: I need this right now.

**Comment by gabrieljones** [comment]
Here is an [alternative](https://stackoverflow.com/a/76860399/263306) that generalizes the notion of branching.

**Comment by Ichoran** [comment]
How much is it worth generalizing this?  `tapIfNot` and `pipeIfNot`?  `tapWith(A => B)(B => Unit): A` and `pipeWith(A => B)(B => Z): Z`?  `pipeWhile(A => Boolean)(A => A): A`?  `pipeUntil(A => Boolean)(A => A): A`?

I'm a little wary of the ad-hoc addition of one of a set of features.  (Also, what som-snytt said about this not being the right place.)

**Comment by He-Pin** [comment]
I would like to check the name in Kotlin too,

**Comment by SethTisue** [comment]
Thank you for the PR. Unfortunately, as per https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html , we cannot accept this because it would break forward binary compatibility. Eventually we will open the standard library up for additions again, and (as Som indicates) in the meantime we are collecting and discussing proposed future additions at https://github.com/scala/scala-library-next.

**Pull request closed without merging**
