### PR TITLE
Fix failing nightly build on java7

### PR DESCRIPTION
**Pull request by VladUreche**
Review by @lrytz

### CODE REVIEW

**Comment by VladUreche** [comment]
NOTE: This pull request should be merged into the java7 branch!

**Comment by VladUreche** [comment]
It should not come as a surprise that the build failed: it's trying to compile the java7 code for swing (with the added type parameters) against java6. Actually, this branch's scala-swing should not be compiled at all, no matter the version of the jvm:
- it's incompatible with java 6 as it has extra type parameters
- it's incompatible with java 7 as it wasn't maintained in some time (it wasn't built at all)

I guess scala-swing is in dire need of a maintainer...

**Comment by jsuereth** [comment]
yes.  TBH - I'm almost of the opinion we cut scala-swing out of our repository and make a new one for it.  There is nothing about scala-swing that requires to be in core, and with the new infrastructure we're building we can still include it in distributions in the future.

I can take a look at this when my task queue is down to "insane" quantities from "near death".

**Comment by VladUreche** [comment]
Thanks Josh. This patch is more of a band-aid for the failing nightlies on java7. Lukas pinged me about failing scaladoc and I made the minimum set of changes to get it working again. I guess we you could also review it so we get the java7 nightlies running again, if that's okay with you :)

**Comment by paulp** [comment]
If it's clear enough how you want it done, I'd be happy to extract swing into a separate repository.

**Comment by VladUreche** [comment]
Since this pull request hasn't seen activity in some time, I'm closing it.

**Pull request closed without merging**
