### PR TITLE
[WIP] AbstractSeq[+A] extends SeqOps[A, AbstractSeq, AbstractSeq[A]]

### LINKED ISSUE #10908: Seq(LazyList(2), Vector(3)) return too complex type in Scala 2.13.0-M4
screen shot 2018-05-26 at 21 33 34

similar issue https://github.com/scala/bug/issues/7402 (fixed. 5 years ago)

### PR DESCRIPTION
**Pull request by joroKr21**
Refining the type arguments of `SeqOps` in the appropriate parent simplifies the LUB by avoiding the refinement of methods defined in `SeqOps`.

fixes scala/bug#10908

Open questions:
- [ ] Should there be `AbstractIndexedSeq` and `AbstractLinearSeq`?
- [ ] Where else should the type arguments of `SeqOps` be refined?
- [ ] How about other ops and abstract classes, etc?

### CODE REVIEW

**Comment by lrytz** [comment]
Nice, thank you! I'd say let's add `AbstractIndexedSeq` and `AbstractLinearSeq`, as they will simplify some of the changes in this PR. I'd leave the rest as is.

Two tests need a check file update (t7747-repl, repl-transcript).

**Comment by joroKr21** [comment]
> Nice, thank you! I'd say let's add AbstractIndexedSeq and AbstractLinearSeq, as they will simplify some of the changes in this PR. I'd leave the rest as is.

I tried this but it's not possible. We end up in a situation where `immutable.AbstractIndexedSeq` has to extend both `collection.AbstractIndexedSeq` and `immutable.AbstractSeq`. So they have to be traits instead. Would this nullify the class size advantage of `AbstractSeq`?

I pushed the code for `trait AbstractIndexedSeq` as an example. The same would have to be done for `LinearSeqOps` and possibly `MapOps`, `SetOps`, `SortedMapOps`, `SortedSetOps`, `StrictOptimizedSeqOps` to ensure the LUB between any two collections would look good.

All things considered that might lead to the proliferation of intermediate traits, so the original solution with refined types doesn't look so bad to me.

**Comment by joroKr21** [comment]
> All things considered that might lead to the proliferation of intermediate traits, so the original solution with refined types doesn't look so bad to me.

Ah, that doesn't actually work (I'm not sure if it should?):
```scala
scala> implicitly[AbstractSeq[Int] <:< SeqOps[Int, AbstractSeq, AbstractSeq[Int]]]
res0: scala.collection.immutable.AbstractSeq[Int] <:< scala.collection.immutable.SeqOps[Int,scala.collection.immutable.AbstractSeq,scala.collection.immutable.AbstractSeq[Int]] = generalized constraint

scala> implicitly[IndexedSeq[Int] <:< SeqOps[Int, IndexedSeq, IndexedSeq[Int]]]
res1: IndexedSeq[Int] <:< scala.collection.immutable.SeqOps[Int,IndexedSeq,IndexedSeq[Int]] = generalized constraint

scala> implicitly[AbstractSeq[Int] with IndexedSeq[Int] <:< SeqOps[Int, AbstractSeq with IndexedSeq, AbstractSeq[Int] with IndexedSeq[Int]]]
                 ^
       error: Cannot prove that scala.collection.immutable.AbstractSeq[Int] with IndexedSeq[Int] <:< scala.collection.immutable.SeqOps[Int,scala.collection.immutable.AbstractSeq with IndexedSeq,scala.collection.immutable.AbstractSeq[Int] with IndexedSeq[Int]].
```

Anyway, I am still willing to give a go at the intermediate traits approach and we can decide if the code bloat is too much later.

**Review by szeiger — COMMENTED** [review]
I'd rather see a change in the opposite direction that prevents any of the abstract classes from leaking into types. They are supposed to be implementation helpers that the users should not see. But as seen in https://github.com/scala/bug/issues/10908 they already leak out, so making them leak in less awful ways looks like an improvement.

**Review by szeiger — APPROVED** [review]

**Comment by joroKr21** [comment]
I tried doing the same for other collection branches like linear sequences, sets, maps, etc. but it's too tedious. As pointed out this relies on implementation details and I think it's a way too brittle solution which requires knowledge of the entire collections inheritance hierarchy in detail.

The true solution comes with dotty's union types. In scalac one could try to prevent the inference of refined types for f-bounded types but I don't know if that's even possible. 

@szeiger although you approved the PR I lean towards closing it as it relies on too many assumptions for very little gain. Wdyt?

**Comment by szeiger** [comment]
@joroKr21 Sounds good. A solution based on improved type inference would be preferable. As far as I understand the problem, some previous cases now work in 2.13 but new ones have appeared because it depends on intricate details of the implementation. If we have a proper solution in Dotty I think we can live with this for a bit longer.

**Comment by joroKr21** [comment]
Agreed, closing. I will keep the branch around in case someone wants to try again, but I don't see it happening.

**Pull request closed without merging**
