### PR TITLE
SI-7491 fix typo in scala.App documentation

### PR DESCRIPTION
**Pull request by gourlaysama**
This is a really cheap PR, but hey, there was a ticket for it!

### CODE REVIEW

**Comment by som-snytt** [comment]
Since you have undertaken this onerous task, I would suggest stronger language.

```
For the normal use case, do not override `main`.  The whole class body becomes the "main method."
```

The other question is whether anyone who knows what they are doing would choose to override main.

**Comment by retronym** [comment]
How about:

``` scala
trait App { 
 ....
  @deprecatedOverriding("main should not be overriden", "2.11.0")
  def main(args: Array[String]) = {
```

Then we can make if final in 2.12.

**Comment by som-snytt** [comment]
That's super.  Preemptively, `s/overriden/overridden/`.

I'd forgotten about that deprecated mode. So basically, the upper limit on Scala features is what JZ can keep in his head.  There must be a test for that; then, you can plan Scala 3 around the result.

**Comment by gourlaysama** [comment]
Good point, I don't think anyone ever chose to override main anyway. Here is the new version.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
