### PR TITLE
moves the impl of quasiquotes to scala.reflect

### PR DESCRIPTION
**Pull request by xeno-by**
This brings consistency with scala.reflect.reify and scala.reflect.macros
already existing in scala-compiler. To the contrast, scala.tools.reflect,
the previous home of quasiquotes, is a grab bag of various stuff without
any central theme.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym @densh

**Comment by densh** [comment]
I wonder if we should do it the other way around: move more stuff to tools, as it's clearly not public api. Having stuff in `scala.reflect` directly really looks like it is a part of reflection api.

**Comment by densh** [comment]
Another reason why current place seems to be appropriate: it's alongside all other default fast-tracked macros (including default macro interpolators.)

**Comment by xeno-by** [comment]
I'm just not very fond of the `scala.tools.reflect` package to be honest. Currently it's a collection of random stuff, like you know `foo.bar.util`, and that's not very good imo.

**Comment by densh** [comment]
If we'll put all built-in macros in there it won't stop being that random any longer.

**Comment by xeno-by** [comment]
Well, reify is a built-in macro, and it's been in scala.reflect for a long time already.

**Comment by densh** [comment]
Type tag materializers and f interpolator are also built-in macros and they have been in scala.tool.reflect  for a long time already.

**Comment by xeno-by** [comment]
Tag materializers are just thin dispatchers to reify. f interpolator came much later. I don't mind the dispatchers for quasiquotes staying in scala.tools.reflect.

**Comment by som-snytt** [comment]
FWIW, as a casual user, I share the concern about what looks like api.  It's a little extra cognitive burden when it's not obvious where to look for stuff.  OTOH, finding f-interpolator in tools.reflect also felt like rummaging in the junk drawer for a screwdriver.  Sorry I don't have a good suggestion for naming.

**Comment by gkossakowski** [comment]
It seems like activity on this PR stalled so I'm closing it. @xeno-by, if you still would like to get this PR in, please submit a rebased version.

**Comment by xeno-by** [comment]
Let's have a review first before we do anything else. @retronym, what do you think?

**Comment by gkossakowski** [comment]
FYI, it might take another week or two before @retronym is back online.

**Comment by xeno-by** [comment]
This has been waiting for 10 weeks already, so I don't see why it can't wait for 2 more :)

**Comment by retronym** [comment]
I'm happy to merge the rebased version of this PR on the consistency argument. Sorry about the tardiness!

**Comment by xeno-by** [comment]
Rebased. Thanks!

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Allright, the build is green. Let's merge?

**Comment by gkossakowski** [comment]
Yep. LGTM.

**Pull request merged**
