### PR TITLE
Merge/v2.10.1 326 g4f8c306 to master

### PR DESCRIPTION
**Pull request by retronym**
```
git merge 77437ff
git merge 0ae7e55
git merge -s ours 4e64a27
git merge v2.10.1-326-g4f8c306

git log --graph --oneline  $(git merge-base v2.10.1-326-g4f8c306 master)...v2.10.1-326-g4f8c306
*   4f8c306 Merge pull request #2504 from scalamacros/ticket/7464
|\  
| * 5e71539 SI-7464 allows FieldMirror.set to update vals
* |   7415430 Merge pull request #2497 from scalamacros/topic/macro-qqq
|\ \  
| * | bc10715 easy way of writing not implemented macros
* | |   988e27a Merge pull request #2547 from paulp/issue/bogus-warning
|\ \ \  
| * | | b08c135 Fix for unreachable code warning.
|/ / /  
* | |   01716c8 Merge pull request #2537 from adriaanm/ticket-5886
|\ \ \  
| * | | e9c3f87 SI-5886 Remove check for packed type conformance.
* | | |   70e2ead Merge pull request #2515 from heathermiller/issue/6555
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | 963c4a7 Actual SI-6555 fix, Scaladoc filter works WITH keyboard shortcuts too
* | | |   487584c Merge pull request #2502 from viktorklang/wip-SI7383-EC-prepare-in-Future-apply-2.10-√
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | b32d294 SI-7383 - Call ExecutionContext.prepare in Future.apply to allow for capturing local context like ThreadLocals and then re-establishing them prior to execution, as per intention of EC.prepare
* | | |   76b8724 Merge pull request #2500 from phaller/topic/forkjoin-update
|\ \ \ \  
| |_|/ /  
|/| | |   
| * | | 77437ff SI-7442 Update bundled Fork/Join pool (JSR166y)
* | | |   aa7568e Merge pull request #2494 from scalamacros/ticket/5923
|\ \ \ \  
| * | | | 4e64a27 [nomaster] removes duplication in inferImplicitValue
| * | | | 3edde27 [nomaster] SI-7166 catches DivergentImplicit in c.inferImplicitXXX
| * | | | b4da864 [nomaster] SI-7047 fixes silent for c.inferImplicitXXX
| * | | | fdead2b [nomaster] SI-7291: No exception throwing for diverging implicit expansion
| * | | | 8168f11 [nomaster] SI-7167 implicit macros decide what is divergence
| * | | | bb73b96 [nomaster] macroExpandAll is now triggered in all invocations of typed
| * | | | 90ac5c4 [nomaster] SI-5923 instantiates targs in deferred macro applications
| * | | | 0c6927b [nomaster] temporarily breaks SI-5353
| |/ / /  
* | | |   0ae7e55 Merge pull request #2496 from igormoreno/2.10.x
|\ \ \ \  
| * | | | 7562499 Scaladoc: fixing small typo in PartialFunction.scala
|  / / /  
* | | |   616417b Merge pull request #2505 from scalamacros/topic/macros
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | 5751ddd pull request feedback
| * | | 75a3b88 replaces inferBootClasspath with a simple lookup at sun.boot.class.path
| * | | 35c0145 removes the traces of always on debug diagnostics
| * | | a3d03ab fixes a crash in ReflectionUtils.systemProperties
| |/ /  
* | |   082ca2e Merge pull request #2513 from scalamacros/topic/210x-breakage
|\ \ \  
| * | | f1040ea fixes a checkfile breakage in 2.10.x
|/ / /  
* | |   3b08917 Merge pull request #2481 from martinmcnulty/socket-timeout
|\ \ \  
| * | | 8325729 SI-5734 Allow setting of socket timeout for remote actors
|  / /  
* | |   1ee5cc4 Merge pull request #2456 from paulp/pr/jdk8-210x
|\ \ \  
| * | | b2c67b3 SI-7398 Add support for java8 default methods
| * | | fbb1363 Refactor DirectTest so java can be tested.
|  / /  
* | |   ece84b7 Merge pull request #2461 from scalamacros/ticket/7325
|\ \ \  
| * | | 25f49cb literal() now assigns a position to the tree it produces
| * | | cb1a427 SI-7325 cleans up corner cases of percent handling in StringContext.f
| * | | a8edefc SI-7271 fixes positions of string interpolation parts
|  / /  
* | |   34d28aa Merge pull request #2458 from paulp/issue/7426-210
|\ \ \  
| * | | df3cae7 SI-7426 Crash in pickler.
|  / /  
* | |   c34af08 Merge pull request #2473 from paulp/pr/2.10.2/5634
|\ \ \  
| * | | 3abdaf4 SI-5634 eliminate overly verbose error message
|  / /  
* | |   fb99a1e Merge pull request #2488 from paulp/issue/7441
|\ \ \  
| |/ /  
|/| |   
| * | e86832d SI-7441 Don't ramble on about inapplicable implicits.
|  /  
* |   5c77e01 Merge pull request #2472 from paulp/pr/2.10.2/7385
|\ \  
| * | d0a1f5b SI-7385 crash in erroneous code
|  /  
* |   0f74eda Merge pull request #2487 from paulp/issue/6091
|\ \  
| |/  
|/|   
| * 62cdd7f SI-6091 overeager warning for reference equality
* 48e80cb Merge pull request #2440 from retronym/ticket/6771
* 3009916 SI-6771 Alias awareness for checkableType in match analysis.
```

### CODE REVIEW

**Comment by retronym** [comment]
5e71539 was broken before the merge.

**Comment by xeno-by** [comment]
I might be missing something, but why are `[nomaster]` commits present here?

**Comment by retronym** [comment]
They are now part of the history, but were merged with the `-s ours` strategy, which means we don't have their content. Perhaps you could double check that for me?

**Comment by xeno-by** [comment]
@retronym I see now. Looks like nothing leaked from those `[nomaster]` commits.

**Comment by retronym** [comment]
Fixed the checkfiles and squashed the three merge commits into one manually crafted merge commit.

Used:

```
echo merge | git commit-tree head^{tree} -p v2.10.1-326-g4f8c306 -p be405eed
git commit --amend // edited comment
```

**Comment by retronym** [comment]
Review by @xeno-by

**Comment by xeno-by** [comment]
Will take a look tonight. When do we cut 2.10.2-RC1 and 2.11.0-M3?

**Comment by retronym** [comment]
@adriaanm / @JamesIry hope to tag and bag them by the end the San Franciscan Friday. But I'm taking a quick look at https://issues.scala-lang.org/browse/SI-7486 first.

**Comment by adriaanm** [comment]
Congratulations, @retronym! You have unlocked the git voodoo-master badge.

**Comment by xeno-by** [comment]
@retronym Could you please ping me again when all the tests pass? I'll be glad to review the PR, but I would prefer doing that when the sands are no longer shifting.

**Comment by paulp** [comment]
Superseded by #2554 .

**Pull request closed without merging**
