### PR TITLE
Added utility function shortClass.

### PR DESCRIPTION
**Pull request by paulp**
Pretty sick of names like

  scala> typeOf[List[Int]].getClass.getName
  res0: String = scala.reflect.internal.Types$TypeRef$$anon$1

I wrote this so I can see what the class of some arbitrary
thing is in a way which my little brain can understand.  For
the example above we get

  scala> shortClassOfInstance(typeOf[List[Int]])
  res0: String = ArgsTypeRef with AliasTypeRef

Let's pimp a "shortClassName" onto AnyRef and be happy.

### CODE REVIEW

**Comment by paulp** [comment]
Anyone can review this masterwork.

**Comment by retronym** [comment]
Looks useful/good to me.

Can we also do something to improve `TypeRef#toString`, along the lines of:

``` scala
if (sym.isAliasType)              new NoArgsTypeRef(pre, sym) with AliasTypeRef { override def toString = "<alias type>" }
```

I'm assuming we can't show something more informative in general to avoid initializing things as a side effect of `toString`. I'd like to understand that more precisely, pointers welcome.

**Comment by Blaisorblade** [comment]
What about having something like this in the public (reflection) library, instead of reflect.internal?

**Comment by paulp** [comment]
As implied by my suggestion to pimp it onto AnyRef, I want this available all the time, but I don't want to navigate the waters of where to put it or of making everyone happy with its choices of details.

**Comment by paulp** [comment]
"I'd like to understand that more precisely, pointers welcome."

It's only a matter of isolating all the unevaluated bits which one might evaluate from toString.  "Only", but it's tricky, as many tests can lead to symbol initialization and there's no way to know without following the execution path what those might be.  I think at this point Symbol's toString is properly isolated, or was last I checked.  I know that Type's is not.  One easy way to induce failure if failure is available to be induced is to try printing every type as it is created right from compiler startup.  This generally blows up pretty spectacularly.  We should definitely, should have long ago, get toString to the point where this can be done without the least concern, and it can print "?" while it's bootstrapping if necessary.

**Comment by paulp** [comment]
However in the TypeRef example, we can print things like the symbol's simple name and it's number of arguments, no problem.

**Comment by paulp** [comment]
I'm going to merge this; we can see about putting it somewhere more generally accessible.

**Pull request merged**
