### PR TITLE
Pullrequest/reflection docs

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by jsuereth** [comment]
WOW. what a set of documentation.  SO far LGTM, running it locally.

**Comment by heathermiller** [comment]
For your browsing pleasure, http://lampwww.epfl.ch/~hmiller/grouped/

**Comment by jsuereth** [comment]
OK, LGTM.  I'm cutting 2.10.0-RC1 now.

**Comment by VladUreche** [comment]
Champagne anyone? :D

**Pull request merged**
