### PR TITLE
SI-8893 Restore linear perf in TailCalls with nested matches

### PR DESCRIPTION
**Pull request by retronym**
Details in the individual commits. The one with SI-8893 in the commit
title offers the biggest win.

I'd ask for some help from the kindly reviewer to understand why
that fixed exponential performance, rather than just giving
a constant factor speedup.

Review by @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
Retrying IDE failures (https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/)

**Comment by adriaanm** [comment]
As soon as my import-comment is addressed, LGTM.

The fix looks sound to me, but I'll have to spend some more quality time with this phase to understand the change in computational complexity

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
Assigned to 2.11.4 as this one doesn't look like blocker.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@a52b9a7
PLS REBUILD/pr-scala@96f4764

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@a52b9a7

**Comment by Ichoran** [comment]
I haven't quite figured out how it is that the rest of the cases end up in `args`, but as you possibly already know the problem is that on line 376 (old code) you have a call to `yesTailTransform` which is recursive (transforms are recursive), followed by, when it is not successful, a call through to `noTailTransform`.  This means that at each level of the transformation, you have two recursive calls, leading to doubling of work at each level of the recursion (in the case where the tail transform is not applied).

**Comment by paulp** [comment]
A similar (but different) situation from the history books can be seen at 39f01d4f48 . I'm surprised such things don't strike more often (or maybe they do and people only notice when the recursion gets deep.)

**Comment by Ichoran** [comment]
Incidentally, have you verified whether, post-PR, all tail calls still get transformed (especially if there is a mix of tail and non-tail calls)?  I haven't, but the nature of the fix makes me wonder.

**Comment by retronym** [comment]
@Ichoran I've added a test that I think demonstrates this.

**Comment by retronym** [comment]
PLS SYNCH

**Comment by Ichoran** [comment]
@retronym - That is also a good test to have, but that is not what I meant.  Rather, if a method cannot be _entirely_ tail-recursive but some recursive calls are tail-recursive, will those be converted to jumps, leaving only non-tail recursion as actual method calls?  This is trickier to test--one way would be to have e.g. alternating tail- and non-tail-recursive calls in a match hierarchy and count number of lines in javap output where you get a genuine call.

**Comment by retronym** [comment]
Apparently flakey test in scala-refactoring reported as https://github.com/scala-ide/scala-refactoring/issues/69.

PLS REBUILD/pr-scala@cae09d760d8778c03d09957786522d766430b218

**Comment by retronym** [comment]
@Ichoran Oh, I get you now. I must admit that I didn't realise that partially tail recursive methods were so transformed! I think my test in the latest commit is sufficient to lock this in without needing to resort to a bytecode based test. WDYT?

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@cae09d760d8778c03d09957786522d766430b218

**Comment by retronym** [comment]
NOLITTER!

**Comment by Ichoran** [comment]
@retronym - My understanding of the code paths as they stand now is that the test is sufficient (because information about whether you're on the yes-tail- or no-tail- branch is not propagated recursively, so the yes-path testing will catch all the nested transforms, leaving the no-path to be fine without revisiting).  I guess if anyone rewrites this it's their job to assure that the partial transformation still occurs.

**Comment by retronym** [comment]
PLS SYNCH

**Comment by retronym** [comment]
LGTM echo

> My understanding of the code paths as they stand now is that the test is sufficient

**Pull request merged**
