### PR TITLE
Cull extraneous whitespace.

### PR DESCRIPTION
**Pull request by paulp**
One last flurry with the broom before I leave you slobs to code
in your own filth. Eliminated all the trailing whitespace I
could manage, with special prejudice reserved for the test cases
which depended on the preservation of trailing whitespace.

Was reminded I cannot figure out how to eliminate the trailing
space on the "scala> " prompt in repl transcripts. At least
reduced the number of such empty prompts by trimming transcript
code on the way in.

Routed ConsoleReporter's "printMessage" through a trailing
whitespace stripping method which might help futureproof
against the future of whitespace diseases. Deleted the up-to-40
lines of trailing whitespace found in various library files.

It seems like only yesterday we performed whitespace surgery
on the whole repo. Clearly it doesn't stick very well. I suggest
it would work better to enforce a few requirements on the way in.

### CODE REVIEW

**Comment by paulp** [comment]
Step right up and review a mere 1059 files changed. Who among you has the fortitude for the task? Perhaps @xeno-by is the one!

**Comment by paulp** [comment]
In an update I cut it down to 1056 files, to make review more manageable. Perhaps that will attract @retronym's interest. Who will be the hero of the age?

**Comment by retronym** [comment]
LGTM. Timing is good for this as 2.10.x isn't very active any more.

**Comment by retronym** [comment]
I reviewed by getting git to ignore space changes and checking the residuals: https://gist.github.com/retronym/6611363

**Comment by som-snytt** [comment]
That was interesting (--ignore_space_).  Github won't even just show the file without the diff, it just complains about the huge diff.

I liked the jenkins failure showing a diff with nothing to show. It's kind of eerie.

There are those new tests with an embedded repl transcript ending in "scala> " that would be a nuisance to update at this time.

If there is a white space policy, I hope it includes a newline at EOF.

**Pull request merged**
