### PR TITLE
SI-7733 reflective packages now more consistent with scalac

### PR DESCRIPTION
**Pull request by xeno-by**
Previously PackageScopes from scala.reflect ignored all classes that
had $'s in non-rightmost positions in their names.

Unfortunately this behaviour is inconsistent with how scalac does things,
and I reconciled this as usual, by pulling corresponding logic into
scala-reflect.jar and sharing it between runtime reflection and compiler.

This change has seprate pull requests for 2.10.x and 2.11.0. The latter
(which you're looking at right now) deprecates
`scala.tools.nsc.util.ClassPath.isTraitImplementation`, whereas the former
does not, because we can't deprecated members in minor releases.

### CODE REVIEW

**Comment by xeno-by** [comment]
This is a 2.11 version of https://github.com/scala/scala/pull/2809. review @gkossakowski

**Comment by xeno-by** [comment]
This is something really strange, because it worked for 2.10.x, and it works locally on my laptop. Let's try to rebuild. PLS REBUILD ALL.

**Comment by xeno-by** [comment]
The failure was spurious. See https://groups.google.com/forum/#!topic/scala-internals/rxgjQYGqhmU for an explanation.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@xeno-by: the better way to do it is to perform a merge of 2.10.x with master and then have a separate commit on top of it which introduces the deprecation.

This way we have just one commit present in both branches for the major part of the work. Let me check if it's hard to merge 2.10.x into master.

**Comment by gkossakowski** [comment]
FYI: I looked into merging 2.10.x into master and it's a little bit complicated, unfortunately. Still, the PR is coming (most likely) tomorrow.

**Comment by adriaanm** [comment]
@gkossakowski does this PR need to be reworked?

**Comment by xeno-by** [comment]
Looks like it does. The only remaining change in comparison with the 2.10.x to master merge is deprecation of `scala.tools.nsc.util.ClassPath.isTraitImplementation`.

**Pull request closed without merging**
