### PR TITLE
Partest PR up to the passing commit.

### PR DESCRIPTION
**Pull request by paulp**
Rebased and dropped the failer in the hopes of merging this.

### CODE REVIEW

**Comment by paulp** [comment]
This (if it passes) will supersede #2446.

**Comment by som-snytt** [comment]
OK, thanks.

I'll resubmit the other commit separately; it will include test clean-ups, scrubbed with a toothbrush, but educational for a plebe.

**Comment by paulp** [comment]
I'm giving this a not-real-rigorous LGTM because I really need to do some cleanup work on partest and I would like this in the rear view mirror.

**Comment by som-snytt** [comment]
I hear you. 

BTW, I noticed --self-test or whatever.

I like the cyan(++) on update. (Which I've been using.)

**Pull request merged**
