### PR TITLE
Remove deprecated -Y flags

### PR DESCRIPTION
**Pull request by larsrh**
Both flags have been deprecated for a while and are supposed to be dropped for 2.12.

* `-Yeta-expand-keeps-star`
* `-Yinfer-by-name`

### CODE REVIEW

**Comment by larsrh** [comment]
Rebased after #5376.

**Comment by retronym** [comment]
Related discussions: https://groups.google.com/forum/#!msg/scala-internals/03Is9E42sRg/Nr4eG_FVCWIJ

https://issues.scala-lang.org/browse/SI-6816

We can either merge this here, or retarget it to 2.13.x. Removing them in a minor release would be an exception to our usual process. But in this case, I'm feeling comfortable enough to swing the axe. Second opinion from @adriaanm?

**Comment by adriaanm** [comment]
Sounds good to me. -Y flags come with no guarantees

**Comment by larsrh** [comment]
Ready to merge then, I guess? :wink: :shipit:

**Comment by adriaanm** [comment]
🚢

**Comment by SethTisue** [comment]
thank you Lars! bragging rights on having a lifetime negative scala/scala lines added/removed total, awarded 🏆

**Comment by larsrh** [comment]
Not just that; it's also my very first contribution to the mothership!

**Pull request merged**
