### PR TITLE
[backport] Backports library changes related to SI-6566 from a419799

### PR DESCRIPTION
**Pull request by huitseeker**
The idea of backporting this occured while developing the -source flag for
SI-8126 : without this the library breaks at refchecks for any Scala compiler
that checks type aliases variance.

Should be BC and promote good hygiene. Review by @retronym.

### CODE REVIEW

**Comment by adriaanm** [comment]
Awesome!

**Comment by adriaanm** [comment]
LGTM

**Comment by huitseeker** [comment]
NOLITTER!
PLS REBUILD ALL

**Comment by huitseeker** [comment]
I'm not sure I understand why|how the validation fails. It seems to fail on sbt ([1](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/5398/console) [2](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/5398/console)).

I manage to build sbt without trouble locally, using [this](https://gist.github.com/huitseeker/8438274) script to build sbinary and [this one](https://gist.github.com/huitseeker/8438296) for sbt, and a [slight tweak](https://gist.github.com/huitseeker/8438240). Logs, binaries are at your disposal.

**Comment by adriaanm** [comment]
It fails because it tries to resolve org.specs2#specs2_2.10.4-806b6e4-SNAPSHOT;1.12.3
Note that it's fully binary cross-versioned with the version of Scala we're validating, which of course is going to fail.

@jsuereth or @cunei, please resolve this ASAP -- we're in the release crunch for both 2.11.0-M8 and 2.10.4-RC2 and can't merge PRs with confidence when IDE integration fails. Alternatively, revert  to https://github.com/typesafehub/sbt-builds-for-ide/commit/599b0a834009c27f246ad29291dd82fb3457bd37. I guess the uber-build script could also check out this commit rather than master for sbt-builds-for-ide (though that's suboptimal).

**Comment by adriaanm** [comment]
@cunei is submitting a PR as I write this, so the sbt integration issue should be resolved soon. Thank you all for your patience. I'll issue rebuild-alls when the fix is in place.

**Comment by adriaanm** [comment]
Sounds like it should be fixed! PLS REBUILD ALL

**Comment by huitseeker** [comment]
NOLITTER!
PLS REBUILD ALL

**Comment by huitseeker** [comment]
\o/ it worked !

**Comment by retronym** [comment]
LGTM

**Pull request merged**
