### PR TITLE
Rename Map stepper methods

### PR DESCRIPTION
**Pull request by NthPortal**
Rename `Map#{key,value}Stepper` to
`Map#{keys,values}Stepper`.

See https://github.com/scala/scala-dev/issues/628#issuecomment-496191304

### CODE REVIEW

**Comment by adriaanm** [comment]
```
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.MapOps.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.MapOps.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMap.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMap.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMapView.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMapView.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap4.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap4.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeMap.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeMap.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.HashMap.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.HashMap.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap3.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap3.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.VectorMap.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.VectorMap.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#EmptySeqMap.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#EmptySeqMap.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap2.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap2.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap1.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap1.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.TreeMap.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.TreeMap.valueStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.HashMap.keyStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.HashMap.valueStepper")
```
other direction:
```
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.MapOps.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.MapOps.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMap.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMap.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMapView.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.AbstractMapView.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap4.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap4.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeMap.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeMap.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.HashMap.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.HashMap.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap3.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap3.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.VectorMap.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.VectorMap.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#EmptySeqMap.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#EmptySeqMap.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap2.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap2.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap1.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.SeqMap#SeqMap1.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.TreeMap.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.TreeMap.valuesStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.HashMap.keysStepper"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.mutable.HashMap.valuesStepper")
```

**Comment by NthPortal** [comment]
thanks - I forgot about MiMa. I'll update all my PRs

**Comment by adriaanm** [comment]
No worries, sorry my copy/paste handiwork was not super useful, since you have to split them out into forward/backward. Grepped away a bit too much :)

**Comment by NthPortal** [comment]
@adriaanm do they get assigned to separate keys?

**Comment by dwijnand** [comment]
No, not for sbt's key config.

I guess Adriaan is used to non-prerelease scala/scala dev days where MiMa filters are added to the split https://github.com/scala/scala/blob/2.13.x/src/reflect/mima-filters/2.13.0.backwards.excludes and https://github.com/scala/scala/blob/2.13.x/src/reflect/mima-filters/2.13.0.forwards.excludes files.

**Comment by lrytz** [comment]
You missed a spot: https://github.com/scala/scala/blob/b616ff01fbb2a16678cd4a091b4cf857946fa3e4/src/library/scala/collection/convert/StreamExtensions.scala#L86-L87

I'll take a look at what test case is missing, why the tests didn't catch this.

**Comment by lrytz** [comment]
Hmm, I wonder, if we rename `keyStepper` to `keysStepper`, should we also rename the extension methods `asJavaSeqKeyStream` to `asJavaSeqKeysStream` etc?

**Comment by lrytz** [comment]
I dropped the tests for `asJavaParKeyStream` / `asJavaParValueStream` in https://github.com/scala/scala/commit/fa183ff11cdf4cf4871460c1435a47ff8eb0bb5a, instead of using a different collection... Pushed a commit to this PR to fix that.

**Comment by szeiger** [comment]
My original comment on Slack was: "Another oddity: `Map` has `keysIterator` and `valuesIterator` but `keyStepper` and `valueStepper`."

I would prefer consistency but I don't really like `keysStepper`. Try saying it out loud a few times. 

I think `keyIterator` and `valueIterator` would be better but do we really want to change them just to remove an extraneous "s"? We copied `keySet` from Java and `keyIterator` would be consistent with that. On the other hand, we have `keys` and `values` (and Java also has the latter), so `keysIterator` and `valuesIterator` make sense when interpreted as `keys.iterator` and `values.iterator`.

**Comment by adriaanm** [comment]
Given autocomplete, names matter a little less. Consistency is nice, but so is constancy :-)

**Comment by dwijnand** [comment]
> On the other hand, we have `keys` and `values` (and Java also has the latter), so `keysIterator` and `valuesIterator` make sense when interpreted as `keys.iterator` and `values.iterator`

`keyIterator` returns an iterator of the keys, like `keySet` returns the set of keys and `intStream` returns a stream of ints.  So for the same reason `keyStepper` is fine, and better IMO.

**Comment by adriaanm** [comment]
Ok, let’s keep things as they are and close this one.

**Comment by szeiger** [comment]
> `keyIterator` returns an iterator of the keys, like `keySet` returns the set of keys and `intStream` returns a stream of ints. So for the same reason `keyStepper` is fine, and better IMO.

Except that we call it `keysIterator`, not `keyIterator`

**Comment by NthPortal** [comment]
I guess we migrate to `keyIterator` in 2.14

**Comment by adriaanm** [comment]
keysiterator flows better than key-iterator
keys-stepper is harder to say than keystepper

**Comment by adriaanm** [comment]
There is consistency, you just have to chose the right metric :-)

**Comment by lrytz** [comment]
OK, I'll pull out my bugfixes that I pushed to this PR into a new one.

**Comment by dwijnand** [comment]
"Bob, I'm going to need to check this map.  Please give me either all the keys or give me a key iterator.  Either way, I going to have to check each key one-by-one."  Flows, no problem, IMO.

**Comment by adriaanm** [comment]
Either way, name bikeshedding doesn't really belong in the RC cycle.

**Pull request closed without merging**
