### PR TITLE
SI-7280 Scope completion not returning members provided by imports

### PR DESCRIPTION
**Pull request by skyluc**
Scope completion was not returning members provided by import declared in the same block as the given position, if the position was inside an expression which could not be typed successfully, or outside any expression (2 normal use cases when triggering completion in an IDE).

The first commit is a port of retronym/scala@e7ebf3825b4bc63e60ea1e7fcb8c74d509f5a0c6 on the 2.11 code base, to add support to test scope completion in parttest. The second one contains some basic tests for code completion (inheritance, multilevel definition, ...). And the last commit contains the actual fix, with the associated test.

review by @retronym, @odersky

### CODE REVIEW

**Comment by retronym** [comment]
Other than those minor points, and pending successful tests, LGTM. Nice work!

**Comment by adriaanm** [comment]
PLS REBUILD ALL

Sorry, the partest integration fail is my bad. Fixed by https://github.com/scala/jenkins-scripts/commit/766003ba7fbc94a76971018a282b9cbdd47d6df8. When #3129 was merged, I had to update partest, but forgot to bump the tag of partest against which we integrate.

I've rebuilt the pr-scala-integrate-partest job manually and it succeeded (see https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-partest/)

Should be all green soon!

**Comment by skyluc** [comment]
I pushed a small commit fixing the minor points.
I didn't know if you prefered that I squashed it right away, or just before the final merge.
I'll also remove the `fixes..` when I do the squash.

**Comment by retronym** [comment]
Thanks, squash at will!

**Comment by skyluc** [comment]
Squashed.
I think the kitty got confused when @adriaanm asked for the rebuild. The individual jobs are green, but the overall job is red. Hopefully it will be cleared up when testing the new commit.

**Comment by skyluc** [comment]
A type completion test has been added in master, I need to rebase the pull request.

**Comment by adriaanm** [comment]
The bot only polls every ten minutes, so during that window things can be out of synch.

**Comment by JamesIry** [comment]
@retronym, want to give a finial LGTM?

**Comment by retronym** [comment]
LGTM!

**Pull request merged**
