### PR TITLE
Fix performance regression around dep. typed extractors

### PR DESCRIPTION
**Pull request by retronym**
Offending PR: #6082

### CODE REVIEW

**Comment by retronym** [comment]
Benchmarks [scheduled](https://scala-ci.typesafe.com/grafana/dashboard/db/pr-validation?var-scalaSha=94cee79e%7C07a427735e%7Cc1c9c7c1ee%7Ce8cda7f7b9%7Cdd162eab63%7Ca90aae9662%7Ce100de3e8c%7C07a427735e%7C6629caa&var-source=All&var-bench=HotScalacBenchmark.compile&var-host=scalabench%40scalabench%40&from=1505260788931&to=1507081575828)

**Comment by retronym** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/5797/console

```
Build timed out (after 150 minutes). Marking the build as aborted.
Build was aborted
Archiving artifacts
Notifying endpoint 'HTTP:http://scala-ci.typesafe.com:8888/jenkins'
Notifying endpoint 'HTTP:https://scala-ci.typesafe.com/benchq/webhooks/jenkins'
Finished: ABORTED
```

image

First timeout was in fbc8abbacb5c44ef781642731f49ab26ecf0b41b. Infrastructure problem? Non-deterministic performance problem or hang somewhere?

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
A propos, would be interesting to see what the benchmarks look like under `-Xno-patmat-analysis`.

**Pull request merged**
