### PR TITLE
SI-6601 Close access loophole for value class constructors

### PR DESCRIPTION
**Pull request by retronym**
ExtensionMethods marks private constructors of value classes as
notPRIVATE before pickling. When the pickler reads the flags of this
symbol, the anti-shift mechanism folds this into the regular PRIVATE
flag, so the class is pickled as though it was public all along. A
seprately compiled client can then call this constructor.

To remedy this, we must:
- pickle `rawFlags`, rather than `flags`. This is symmetric with
  unpickling, which sets `rawFlags` with the value it reads.
- Add `notPRIVATE` to the flagset `PickledFlags`.

We cannot make this change in a minor version, as the pickler
and unpickler must agree on `PickledFlags`.

I believe that this won't change the size of pickled flags
for the majority of symbols (ie, those without the notPRIVATE flag)
due to the variable length encoding in `writeLongNat`.

This also improves the situation for SI-6608. Reflection and
scalap (and, by extension, IntelliJ), no longer will see
as public methods that have had their access widened in
SuperAccessors (which is done selectively to support inlining
under separate compilation.)

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
Let's throw in a review by @paulp, too, as pickling is a sensitive area.

**Comment by paulp** [comment]
Pickling and unpickling a notFLAG fills me with foreboding. At least I think that's foreboding.

**Comment by retronym** [comment]
I think that feeling is `notOPTIMISM`.

**Comment by retronym** [comment]
I forgot to mention the existing test, `pos/t6601`, which verifies that the `notPRIVATE` constructor participates correctly in the value class optimizations in `Erasure`.

**Comment by paulp** [comment]
Let the record show that paulp.flags |= notOPTIMISM, but I have no coherent basis for standing in the way. As you know @gkossakowski is out of commission for a bit so my notOPTIMISM will have to suffice.

**Pull request merged**
