### PR TITLE
SI-7174 Fix initialization issues

### PR DESCRIPTION
**Pull request by soc**
Without constant inlining, the compiler would not even bootstrap
because it depends on constant inlining hiding initialization issues
which would cause a NPE otherwise.

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks for fixing this! As this is pretty tricky stuff and resulted in a long mailing list thread, a slightly longer commit message that summarizes the discussion would be great.

**Comment by soc** [comment]
@adriaanm Done.
I'm wondering whether it makes sense to prevent stuff like `NoRunId` from getting inlined in the first place. I don't think we access these numbers in a hot loop. Reducing the number of almost global compile-time dependencies (I guess there not many files in the compiler which don't use `Global`/`SymbolTable`) seems to be a good thing.

**Comment by som-snytt** [comment]
@soc I don't understand the kerfuffle.  In `SubComponent`, `NoRunId` is meant to be a constant.  If you make it not a constant, then you have to update the compiler plugin writer's guide, right?  (This is aside from whether the compiler's own phases should early-init the global.)

Also, we might have to update the one-question FAQ.  Are constant values described there as workarounds for init-order?

**Comment by soc** [comment]
@som-snytt 
“If you make it not a constant, then you have to update the compiler plugin writer's guide, right?”
Why? I don't really get the question ... 

“Are constant values described there as workarounds for init-order?”
No, it should never work. That it worked in this case just shows that it is more or less impossible to predict/emulate runtime behavior at compile-time.

**Comment by som-snytt** [comment]
@soc My plugin phase is also a SubComponent, as for CPS, so I'll have to change it if early init of the global is required, right?  I haven't tried it with my old plugin, so maybe I'm missing something.  (Just kidding about the plugin guide, if there is one.)

**Comment by soc** [comment]
Code which is written this way is inherently broken. It is pure luck that it works as is. It might be possible to fix `SubComponent`/`global` by reordering the declarations or converting `val`s to `lazy val`s.

This commit just ensures that we don't rely on constant inlining to save our ass while bootstrapping the compiler itself.

**Comment by som-snytt** [comment]
Do you mean it's less broken if the constant is refactored to an object SymbolTableConstants?  That would have to be outside the global cake.  In other words, by "pure luck" you mean it's lucky that no one has come along before now and changed the constant "final val" and maybe caused an NPE that failed non-fast.  I agree with that.  Sorry for chat on the PR.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
