### PR TITLE
SI-6555 Scaladoc's class filter shouldn't drop the last character

### PR DESCRIPTION
**Pull request by kzys**
The event handler have to wait "keyup", not "keydown".

### CODE REVIEW

**Comment by VladUreche** [comment]
Review by @heathermiller I guess.

**Comment by VladUreche** [comment]
@kzys, please retarget this pull request at the `2.10.x` branch.

**Comment by heathermiller** [comment]
Ah yes, of course keyup would be better than keydown. Thanks @kzys! You have the LGTM, just name me as a reviewer when you reopen against 2.10.x.

Thanks!

**Comment by kzys** [comment]
Got it. Here is the new pull request.
https://github.com/scala/scala/pull/1872

**Pull request closed without merging**
