### PR TITLE
SI-7599 Modify methods to be non-tail-callable ...

### PR DESCRIPTION
**Pull request by soc**
... to prevent Avian from eliding the stack frames we want to inspect.

### CODE REVIEW

**Comment by soc** [comment]
Review by @adriaanm, please.

**Comment by adriaanm** [comment]
Could you please fix up the commit message? I suggest:
"[avian] prevent tail call optimization in test to inspect stack"

Other than that, LGTM.

**Comment by huitseeker** [comment]
[Valid](https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala/17/) w.r.t. ScalaIDE PR validation

**Comment by soc** [comment]
@adriaanm Updated!

**Comment by adriaanm** [comment]
LGTM

**Comment by soc** [comment]
Thanks!

**Pull request merged**
