### PR TITLE
Cleanup of crash output.

### PR DESCRIPTION
**Pull request by paulp**
I finally ran across the assert (or one of them) which produces such
voluminous output that it scares the cattle. When you see "decls" in an
assert, run.

After silencing that, I extended the journey into quieting the default crash
message down, way down. I assume this will be met only with sighs of relief.
And then most challenging of all for some reason, I convinced it to only print
the information once.

Volume of crash data generated when reproducing the fsc bug shown below:

```
  Before this commit  1158 lines
   After this commit    27 lines
```

Pretty sure there's more information in the 27 lines. To reproduce the crash:

```
fsc src/library/scala/collection/immutable/IntMap.scala
fsc src/library/scala/collection/immutable/IntMap.scala
```

The first compile succeeds quietly; the second throws warnings out of the
gate, then crashes. And the "after" output:

```
  error: Cannot create static reference to method equals because object GenMapLike$class has no source module
 error: fatal error:
      while compiling: /scala/trunk/src/library/scala/collection/immutable/IntMap.scala
         during phase: globalPhase=mixin, enteringPhase=cleanup
      library version: version 2.11.0-20130606-052937-392858b4f6
     compiler version: version 2.11.0-20130606-055515-1856bec71b
   reconstructed args: -d /tmp

    last tree to typer: Ident(key$2)
        tree position: line 377 of /scala/trunk/src/library/scala/collection/immutable/IntMap.scala
             tree tpe: Int
               symbol: value key$2 (flags: <param> <synthetic>)
    symbol definition: key$2: Int (a TermSymbol)
       symbol package: scala.collection.immutable
        symbol owners: value key$2 -> constructor IntMap$$anonfun$unionWith$2 -> anonymous class anonfun$unionWith$2
            call site: object IntMap$Nil in package immutable in package immutable

  == Source file context for tree position ==

    374       }
    375     case (IntMap.Tip(key, value), x) => x.updateWith[S](key, value, (x, y) => f(key, y, x))
    376     case (x, IntMap.Tip(key, value)) => x.updateWith[S](key, value, (x, y) => f(key, x, y))
    377     case (IntMap.Nil, x) => x
    378     case (x, IntMap.Nil) => x
    379   }
    380
```

### CODE REVIEW

**Comment by retronym** [comment]
The "last tree seen by Typer" is technically accurate but misleading when the crash comes from some distant part of the compiler backend.

Is it ever helpful to show that if we are not currently somewhere under `Typer#typed`?

**Comment by paulp** [comment]
You're right, I should elide the whole message if there's nothing on the "typed" stack - but I will need that stack, right? Not that I don't want it anyway.

**Comment by retronym** [comment]
If performance is a concern you could maintain `var depth: Int; var last: Tree`. Maybe start with that and try the more ambitious "Full Stack Solution" :tm: in a subsequent commit.

**Comment by paulp** [comment]
@retronym the lastTreeToTyper bits are all moved around in another imminent pull request (the beautification of -Ytyper-debug output) so it would be a lot easier if I can kick that over to that one. How's this look otherwise?

**Comment by retronym** [comment]
LGTM. If you are feeling in a testy mood, you could call this from a macro (after a few casts). See the commit comment of c598e764b9 for a similar example.

**Comment by paulp** [comment]
Don't worry, I'm always in a testy mood after someone suggests more tests.

**Pull request merged**
