### PR TITLE
SI-8402 Restore 2.10 variance behavior under -Xsource:2.10

### PR DESCRIPTION
**Pull request by paulp**
Review by @retronym.

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks, this also fixes SI-8265, right? Maybe we could also emit a deprecation warning under -Xsource:2.10 to pretend we deprecated this before fixing it. It's a pattern I'd like us to adopt for fixing things like this in 2.11.x.

**Comment by adriaanm** [comment]
Note to self: the fix that made this illegal again was logged as SI-6566

**Comment by paulp** [comment]
Grumble grumble review by @adriaanm

**Comment by paulp** [comment]
If you don't like the way I cut through the Gordian knot of "how the frack do I issue a deprecation warning" then you may opt for lumping it instead.

**Comment by adriaanm** [comment]
LGTM Thank you, really appreciate it.

**Comment by huitseeker** [comment]
LGTM ! (now where did I put the branch I had for that ?)

**Pull request merged**
