### PR TITLE
SI-7432 Range.min should throw NoSuchElementException on empty range

### PR DESCRIPTION
**Pull request by ihji**
For consistency, range.max and range.min should throw
NoSuchElementException on an empty range.

### CODE REVIEW

**Comment by soc** [comment]
Could you add tests and a reviewer please?

**Comment by ihji** [comment]
Review by @retronym

**Comment by paulp** [comment]
The CLA checker is lying and saying nobody has signed the CLA, so I'll punt and merge this. If you haven't signed the CLA though, please do. http://typesafe.com/contribute/cla

**Comment by paulp** [comment]
And thanks.

**Comment by som-snytt** [comment]
> The CLA checker is lying and saying nobody has signed the CLA

Sorry, we know now that the community supposed to self-police CLA status.  We dropped the ball.

Another way to confirm your CLA status is to buy an "I signed the CLA!" t-shirt from the Scala store.

Then your credit card will be on record.

**Comment by ihji** [comment]
I remember I already signed CLA, but anyway, I've just signed it again :smile:

**Pull request merged**
