### PR TITLE
sbt 1.5 (was 1.4)

### PR DESCRIPTION
**Pull request by SethTisue**
not for merge until 1.5.0 final, but let's make sure CI
likes it. cc @eed3si9n @adpi2

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
CI likes it. closing for now, will reopen when there's another version.

**Comment by eed3si9n** [comment]
Thanks for checking!

**Comment by SethTisue** [comment]
CI likes it. closing again until the next one

**Comment by SethTisue** [comment]
CI likes it on 1.5.0-RC2, too :+1:

**Comment by SethTisue** [comment]
(the change I just pushed was that Eugene's scalafix rules found a few places where `a in b` syntax hadn't been converted yet)

**Comment by SethTisue** [comment]
I think I'd be comfortable with merging this. Anybody have doubts?

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
