### PR TITLE
Refactor the ClosureOptimizer, run ProdCons only once per method

### PR DESCRIPTION
**Pull request by lrytz**
Refactor and clean up the ClosureOptimizer. The goal of this change
is to run the ProdCons analyzer only once per method, instead of
once per closure instantiation.

Bootstrapping scala with `-Yopt-inline-heuristics:everything` revealed
that ProdCons can take a very long time on large methods, for example

```
[quick.compiler] scala/tools/nsc/backend/jvm/BCodeBodyBuilder$PlainBodyBuilder#genArithmeticOp - analysis: 1 spans, 17755ms
[quick.compiler] scala/tools/nsc/typechecker/SuperAccessors$SuperAccTransformer#transform - analysis: 1 spans, 28024ms
[quick.compiler] scala/tools/nsc/backend/jvm/BCodeBodyBuilder$PlainBodyBuilder#genInvokeDynamicLambda - analysis: 1 spans, 22100ms
```

With this change and enough time and space (-Xmx6000m), bootstrapping
scala succeeds in this test mode.

### CODE REVIEW

**Comment by adriaanm** [comment]
Let's consider for M2-1, if you feel this is good to go, @retronym

**Comment by retronym** [comment]
@adriaanm If we could get a green `-Yopt:l:classpath` community build, I'd be happy to include this. The patch looks okay on a quick review.

**Comment by adriaanm** [comment]
Cleaned up some disk space, running on merge of #4619, #4621, #4622, #4623 into 2.12.x: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/66/console

**Comment by adriaanm** [comment]
all :green_heart:

**Comment by adriaanm** [comment]
Nice job, @lrytz! The whole community build passed with -Yopt:l:classpath. Took about 33.33% longer.

**Pull request merged**
