### PR TITLE
SI-7643 Enable newPatternMatching in interactive.

### PR DESCRIPTION
**Pull request by retronym**
Without it, the enclosed test fails with:

```
ArrayBuffer(Problem(RangePosition(partial-fun/src/PartialFun.scala, 62, 62, 77),type mismatch;
 found   : Int => Int
 required: PartialFunction[Int,Int],2))
```

And with that, we can remove this option altogether.

Review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
Closed until I refactor away the option altogether. The tests passed (yay!) https://scala-webapps.epfl.ch/jenkins/job/pr-scala/1905/

**Comment by dragos** [comment]
Thanks @retronym! :santa:

**Comment by retronym** [comment]
Review by @adriaanm @dragos @VladUreche

**Comment by adriaanm** [comment]
LGTM -- So it sneakily worked all along!? Thanks anonymous rangepos-fixer!

**Comment by VladUreche** [comment]
LGTM, thanks @retronym!

**Pull request merged**
