### PR TITLE
SI-5498 completes ModuleMirror.instance

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by adriaanm** [comment]
reviewer? commit message?

please take the pull request policy a bit more seriously

**Comment by xeno-by** [comment]
I planned to get a LGTM from Martin for all active pull requests after tomorrow's meeting. 

Commit message? I usually write those, but here it's completely self-explanatory. The linked bug says that ModuleMirror.instance wasn't implemented. I implemented it. Didn't meet any resistance, so nothing more to say. Right?

**Comment by xeno-by** [comment]
Superceded by https://github.com/scala/scala/pull/888

**Comment by xeno-by** [comment]
@adriaanm Could you please comment?

**Comment by adriaanm** [comment]
commit messages are not optional, no matter how trivial the fix was to you
take the extra minute to write down why it's trivial and i bet you'll find yourself writing another sentence that actually explains some new insight

**Comment by adriaanm** [comment]
also, don't think of this in terms of "just this one trivial commit" or "i'm the only one working on this right now" or "i'll get Martin to sign off when I see him at the coffee machine"

we need to standardize or we won't be able to scale our development efforts beyond where we are now

**Comment by xeno-by** [comment]
I didn't mean that the commit was trivial. I meant that the issue it references fully describes what was done. Can this provide an exemption?

Well okay. I could: 1) talk to Martin, we would take a look together (Martin never signs off stuff without looking into code!) and he'd write "LGTM" or I could: 2) slap "review by odersky" onto comments and do exactly the same as in 1. What's the point of extra work in 2?

**Comment by adriaanm** [comment]
I suggest you man the pull request queue for a week or two and I'm pretty sure you'll see the point of standardization.
Then I suggest you fix other people's bugs for a month to really value commit messages that divulge their reasons, possibly even surpassing the details in the ticket.

To be perfectly clear, I don't mean you should actually do this, but I hope just imagining doing this will provide answers to your own questions.

**Comment by gkossakowski** [comment]
I just wanted to support Adriaan in his request. I looked at the ticket and it tells me nothing: https://issues.scala-lang.org/browse/SI-5498

It's just a bunch of code dumped there. You should remember that people will be looking at your code in 2-3 years and won't be necessarily versatile with reflection issue and will still need to understand what's going on because something they care about doesn't work.

To give you specific example, see Flags discussion: https://groups.google.com/d/msg/scala-internals/UlWDoSQTzyw/dSOKu0JCPbsJ
The code wasn't really complicated and old. The commit messages were not explanatory enough to let me fix the bug I had. Martin had to jump on it and fix it. That's not what we want. If we want to scale we need other people to jump on code and be able to fix it.

And when it comes to reviewing I try to follow what's going on in reflection but with that kind of commit messages I have zero chance to comprehend reflection developments. See also:
https://issues.scala-lang.org/browse/SI-4023?focusedCommentId=58839&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-58839

**Comment by xeno-by** [comment]
Okay I'll think twice before pressing the "Submit" button when writing bug descriptions and commit messages. I thought that the exception text in the linked bug states the problem clearly, but apparently it doesn't, and I admit that this is my mistake, so in the future I'll try harder. Also thanks for the example!

**Comment by adriaanm** [comment]
> This has become a universal reply towards me.

please rest assured this is all as a-personal as it possibly can be
it's about the code, the commits, and the scala project in general, not individual people

I don't know how to prove this to you -- would my (private) communication with other people convince you?

**Comment by xeno-by** [comment]
No need to prove, of course. I was asking that because I thought I'm doing something extremely stupid that I don't notice. It's good that it's not that. This means that I'm adequate in self-reflection, so I can improve. (I'd prefer though if you didn't publicly quote emails written to you personally)

**Comment by adriaanm** [comment]
i didn't notice it was a private email, it just showed up in the gmail thread for this pull request
i have a lot of things going on at the same time, sorry

then again, I think we should be able to have these discussions out in the day light, don't you?

**Comment by xeno-by** [comment]
That email was half-rant, that's why I didn't want to publish it. Sure I should avoid writing rants in the first place, but in that case I felt it was a right thing to do. Justifying this decision here would be another rant, so I suggest we just wrap up :)

**Pull request closed without merging**
