### PR TITLE
SI-7159 Distinguish between assignability and subtyping in TypeKinds

### PR DESCRIPTION
**Pull request by JamesIry**
GenICode#adapt had some unreachable code. That's removed.

Another commit cleans up several spots in the back end related to adapting types.

TypeKinds said INT <:< LONG. But that's not true on the JVM, you need
a coercion to move up. And GenICode#adapt was checking for just that
special case. One commit fixes that up.

TypeKinds also said that BOOL, BYTE, CHAR, and SHORT were also subtypes of INT. That's not quite right. They're assignable to INT, but they aren't subtypes. Another commit fixes that.

### CODE REVIEW

**Comment by JamesIry** [comment]
review @gkossakowski

**Comment by JamesIry** [comment]
sure

**Comment by gkossakowski** [comment]
Cool! Other than that it's all golden! Feel free to amend your last commit.

**Comment by gkossakowski** [comment]
LGTM.

This definitively looks like progress!

**Pull request merged**
