### PR TITLE
add 0X... for hex number literal

### PR DESCRIPTION
**Pull request by advancedxy**

### CODE REVIEW

**Comment by soc** [comment]
LGTM.

**Comment by som-snytt** [comment]
DNLGTM  You'd have to apply the same change in section 13, the syntax summary, which is the reference.

The duplication is unfortunate.

**Comment by som-snytt** [comment]
That LGTM.

**Comment by ghost** [comment]
LGTM

**Comment by adriaanm** [comment]
Thanks, and congrats on your first specification fix, @advancedxy!

**Pull request merged**
