### PR TITLE
SI-5903 extractor macros are now expanded

### PR DESCRIPTION
**Pull request by xeno-by**
This patch alone only allows delegating to other extractors without
even a possibility to change the signature. Something more powerful
requires c.introduceTopLevel or comparable.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @adriaanm

**Comment by xeno-by** [comment]
Spurious failure of a performance test

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
A similar drill, I offer 73e54efb4f with my claimed improvements and a couple questions.

**Comment by xeno-by** [comment]
Will resubmit the PR later. See the comments to the Paul's commit for more info.

**Pull request closed without merging**
