### PR TITLE
SI-6784 Localize features imports in scala.swing

### PR DESCRIPTION
**Pull request by retronym**
Review by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
LGTM, thanks. I think it's kind of nuts that we're in this situation though. I import JRandomLibrary._ and my warnings go quiet? Bold new ground in programming language design.

**Comment by paulp** [comment]
@retronym I noticed a bit late that this is against master. We should backport this for 2.10.2, yes? We can avoid binary compatibility issues by leaving the package object lazy vals in place, just removing the "implicit".

**Comment by retronym** [comment]
I think we should just live with it on 2.10.x.

**Comment by paulp** [comment]
Okay. As you know I don't want the feature at all, which makes me bad at assessing the relevance of how well it works.

**Comment by retronym** [comment]
... multiplied by the relevance of scala-swing.

**Pull request merged**
