### PR TITLE
SI-7622 Clean Up Phase Assembly

### PR DESCRIPTION
**Pull request by som-snytt**
Allow phases (internal or external) to opt-out of assembly. In particular, plug-ins and optimizer phases that are not enabled will not be plugged in.

Otherwise, this PR is not a clean up so much as a hosing down the sidewalk.  "Phase assembly" itself deserves closer inspection.

Review by @gkossakowski

### CODE REVIEW

**Comment by som-snytt** [comment]
@adriaanm Can we submit partest fixes on the other repo and make a difference back here?

By fixing the java6 diff in partest, the PR reveals a tab inadvertently converted to space in a check file.

The other conclusion is that scala/partest needs a PR to fix --update-check to handle #ifdiff notation.

Yeah, I just made that up while I was typing.  "Par-Test, now with _#ifdiff!_" 

Could that make it into the release notes?  PR for PRs.

**Comment by adriaanm** [comment]
As long as partest hasn't been moved out of master, ports of PRs that change anything under src/partest are much appreciated over at scala/scala-partest. I hope to switch to a released partest next week.

**Comment by adriaanm** [comment]
PLS SYNCH

**Comment by adriaanm** [comment]
The IDE failures under the new PR validation scheme are because these commits don't seem to have the xml refactoring as a parent. We'll grandfather them into success.

**Comment by som-snytt** [comment]
Unlikely to get attention, and I can't bear to see the kitteh flail.  It's true that it's not unusual to see a cat engaged in some grotesque meaningless exercise; and sometimes a cat will just sit and stare.

**Comment by adriaanm** [comment]
I think all kitty wants is a rebase.

**Comment by som-snytt** [comment]
Rebased and maybe useful if anyone else thinks so.

**Comment by som-snytt** [comment]
Well, it did that thing where it sucks in other commits, so closing and superseding.

**Pull request closed without merging**
