### PR TITLE
SI-4339 Backpatch event errors and attr fix

### PR DESCRIPTION
**Pull request by som-snytt**
Improve attribute parsing and propagate errors
across event thread. Otherwise tests just hang.
This is tested, right?

### CODE REVIEW

**Comment by som-snytt** [comment]
Scala-ide is my nemesis.

**Comment by som-snytt** [comment]
PLS REBUILD ALL

**Comment by som-snytt** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
Are these cherry picked commits?

To make the mergemaster's life easier, the commits can be entitled as:

`[backport] SI-XXXX .........`

And the commit message should refer to the commit that is being backported. `git cherrypick -X` adds that reference for you.

**Comment by retronym** [comment]
I have a feeling we have a general problem with the IDE build on the 2.10.x branch. Try submitting an empty commit at the start of the PR to confirm that.

**Comment by som-snytt** [comment]
Thanks, I forget between backport or no-merge.

IIRC, a paulp refactor made a manual patch job quicker. The irony is that with the new xml module, the dry code is now cut and pasted.

**Comment by som-snytt** [comment]
OK, that about exhausts my git-fu. Lifelong education.

I remember now that the change is across repos and also the dirs are different so patch wasn't useful to me without a refresher course. And I was on winter break.

**Comment by som-snytt** [comment]
PLS REBUILD/pr-scala@47cf692c0195fb86e37e4b7afca3843e212cfced

**Comment by adriaanm** [comment]
This should pass on the new CI, which is more "forgiving" for IDE failures. Closing in favor of a rebased PR.

**Comment by som-snytt** [comment]
Superseded by https://github.com/scala/scala/pull/4307

**Pull request closed without merging**
