### PR TITLE
SI-7128 Fix regression in copyToArray for empty arrays

### PR DESCRIPTION
**Pull request by retronym**
As seen in Akka.

Review by @JamesIry

### CODE REVIEW

**Comment by soc** [comment]
LGTM

**Comment by viktorklang** [comment]
This is only half the fix. It should just do nothing if "len" is 0, no matter the start index. See: https://issues.scala-lang.org/browse/SI-7128

**Comment by retronym** [comment]
Thanks for the report. Pity we didn't catch this with the RC release; what happened there?

**Comment by viktorklang** [comment]
I think we need to request the submitters of tickets to validate the fix, to close the feedback loop.
Other suggestions?

**Comment by retronym** [comment]
@adriaanm asked all the projects to build with RC3 and report problems, we should have sought confirmation.

**Comment by paulp** [comment]
It would be great if the tracker would do that automatically. It's always a plus to have the reporter verify that the problem is fixed; but given that in the best case participation will be far south of 100%, we're still going to close the ticket before long.

**Comment by retronym** [comment]
Oh wait, I guess you worked around the problem in Akka, so we didn't test the fix that way. We should at least have invited you to review the change and test case. Sorry about letting this one slip through.

**Comment by viktorklang** [comment]
@paulp: Yes, of course we'll have to proceed without confirmation at times, 

@retronym There has definitely been some sort of comms mishap, we can't fix this retroactively so we'll just have to fix it for 2.10.2 and 2.11.0, and I'll try to make sure that Akka 2.1.2 will be working around it.

dbuild will also help us here.

**Comment by viktorklang** [comment]
Thinking more about this, I think this regression (nor not regression, depending on the spec of the method) should clarify the semantics of the method, see the current ScalaDoc here: http://www.scala-lang.org/archives/downloads/distrib/files/nightly/docs/library/index.html#scala.collection.Iterator

So question is, should it throw an exception when len == 0, even if input array is null and startIndex is Int.MinValue? Etc...

Currently we do not have problems in Akka itself, but the Spec (ScalaCheck) that verifies that the ByteStringIterator is behaving like Vector's Iterator fails with this new behavior. So the question is, is our Checker wrong or is the code still having a regression?

**Pull request merged**
