### PR TITLE
SI-9813 Add Java 1.6. and 1.8 java.lang.Math methods into scala.math

### PR DESCRIPTION
**Pull request by golem131**
Add Java 1.6. and 1.8 java.lang.Math methods into scala.math.package

### CODE REVIEW

**Comment by golem131** [comment]
Do we need some tests?

**Comment by janekdb** [comment]
This was merged recently: #5225

Kindly rebase and decide if you want maintain the Scaladoc groupings. If not I'll be happy to extend the groupings following the merge. Would be best to maintain the groupings as we go.

**Comment by golem131** [comment]
I have updated my pull request.
Are this ok?

**Comment by soc** [comment]
I'm a bit concerned about the copying of the ScalaDoc from OpenJDK. Can someone comment on whether this is acceptable?

**Comment by mpociecha** [comment]
Please squash commits.

**Comment by Ichoran** [comment]
I agree with @soc that copying the docs verbatim could be problematic.  Also, some of them would be a lot clearer rewritten (e.g. "scalb" where the exponentiation didn't come through).

**Comment by golem131** [comment]
@soc so, just remove them at all, or rewrite them or what?

**Comment by adriaanm** [comment]
I'm going to have to close this PR without looking at it, due to the risk entailed by copy/pasting docs from a codebase that's governed by a license that's not compatible with ours.

🚨  The prospect of violating another project's license is terrifying to an open source project! Please, _never_ derive docs or code and submit it for inclusion under our license unless the original license allows that. When you sign the CLA, that's one of the things you promise to do. 🚨

**Comment by janekdb** [comment]
@golem131 - I suggest you create a new PR which contains only the forwarding to the Java methods and suitable Scaladoc groupings, similar to the exact group. Leave the methods without descriptions on the basis that the person looking at the methoda will be know what they are looking at because they a familiar with numerical computing or they are able to infer they should read the JavaDocs.

When I was looking at some existing undocumented methods earlier I realised it would be impossible for a non-expert to document the methods with original text so decided documentation omission was less damaging that partial documentation.

**Comment by golem131** [comment]
@janekdb please check https://github.com/scala/scala/pull/5271

**Comment by SethTisue** [comment]
the replacement PR is #5314

**Pull request closed without merging**
