### PR TITLE
SI-9120  Implement breakable generators for sequence comprehensions.

### PR DESCRIPTION
**Pull request by erikerlandson**

### CODE REVIEW

**Comment by Ichoran** [comment]
Discussion on the ticket: https://issues.scala-lang.org/browse/SI-9120

**Comment by adriaanm** [comment]
Hi! PR validation requires #4272 be merged first. Unfortunately, you'll have to rebase once it is.

**Comment by erikerlandson** [comment]
@adriaanm that should be no problem, it's all added files

**Comment by retronym** [comment]
#4272 has now been merged. Can you please rebase on the latest 2.12.x branch now? Sorry for the hassle.

**Comment by lrytz** [comment]
I just took a look at the discussion about this addition on SI-9120. I agree that this change requires more discussion. Closing the PR for now to keep the PR queue (a bit more) tidy.

**Comment by erikerlandson** [comment]
I'm working on a stronger solution.  It's different enough that I'll probably just file a new PR for it.

**Pull request closed without merging**
