### PR TITLE
Renamed hasSymbol to hasSymbolField.

### PR DESCRIPTION
**Pull request by paulp**
Suggestion by retronym that the obvious implementation of
"hasSymbol" be called "hasSymbol" reminded me we have a method
called "hasSymbol" which does not have that implementation, and
which has burned us already with subtle bugginess. I think that
"hasSymbolField" is self-documenting.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @retronym .

**Comment by paulp** [comment]
The question is, what do I call the method we'd like to call "hasSymbol", but which I can't call that anytime soon.  hasMeaningfulSymbol? hasSymbolWhichExists? hasActualSymbol?

**Comment by paulp** [comment]
Also note the logic of interest is embedded in "hasSymbolWhich".

**Comment by xeno-by** [comment]
Btw I'm going to remove `hasSymbol` from the API. When trying to document it I didn't find that the hassle is worth its merit. The pull request (along with some other doc-related changes) will be prepared within the hour.

**Comment by retronym** [comment]
For the record, a few excerpts from the [pertinent thread](https://groups.google.com/d/msg/scala-internals/CVADSPJzqKo/leLtLtaBztcJ)

Quoth @paulp:

> The problem is that what it means to "have a symbol" is ill-defined.  "hasSymbol" would be better called "hasSymbolField" because that's what the implementation is really testing

@odersky concluded with:

> Essentially, `hasSymbol` means: `Tree` defines a `Symbol`. `Apply`, and `TypeApply` don't; they just forward.

Not sure I prefer one of `definesSymbol` and `hasSymbolField` over the other.

/cc @xeno-by Whatever it is called, it might be another candidate to strip out of `reflect.api` for now.

Regarding the new method (`def xxx = symbol ne null && symbol ne NoSymbol`): I don't think it will be that widely called; perhaps we need not obsess over the name. How about `hasSym`, with an explanatory note pinned above it? Otherwise I'd be fine with `hasActualSymbol`.

**Comment by xeno-by** [comment]
@retronym You read my mind!

**Comment by retronym** [comment]
@xeno-by JINX!

**Comment by xeno-by** [comment]
@retronym #1458

**Comment by paulp** [comment]
The comments in this thread were rather lacking in definitiveness.  This is a pure renaming so I'm going for the merge.  I can easily be persuaded the name should be definesSymbol - I have no preference.  But this one is already written and tested.

**Pull request merged**
