### PR TITLE
SI-8557 make scaladoc normalize paths of external jars.

### PR DESCRIPTION
**Pull request by gourlaysama**
Scaladoc compares (string representations of) the paths from
-doc-external-doc and the paths form `sym.underlyingSource`.
We now normalize on both ends before comparing them.

---

review by @VladUreche

### CODE REVIEW

**Comment by VladUreche** [comment]
Nice work @gourlaysama! 

Could you please add a test for this so we don't break it again later?
I think the test could indicate the `scala-library.jar` file via a relative path and make sure there's a link there (counting links is easy, see https://github.com/scala/scala/blob/2.12.x/test/scaladoc/run/links.scala#L27-L30).

**Comment by gourlaysama** [comment]
Thanks, I had failed to come up with a test for this. With your suggestion, it is very easy, see updated commit.

**Comment by som-snytt** [comment]
BTW, there is some history around partest support for running test/partest versus cd test ; ./partest.  Right now, I think, only test/partest works, so your path assumption is OK modulo that buggy behavior.  If that is ever fixed, then the path construction might need updating one day. But that is just theoretical.

**Comment by VladUreche** [comment]
Thanks @gourlaysama! LGTM

**Comment by VladUreche** [comment]
Regarding @som-snytt's comment, the test can also extract the path to scala-library.jar from the classloader. @gourlaysama @som-snytt, how do you feel about this solution?

**Comment by som-snytt** [comment]
I wouldn't want to hold up any trains.  Just for future ref, I remembered that partest.nest.PathSettings does jar locating.  An Adriaan comment from a year ago says he wants to refactor further.  There's no reason to build on shifting sands.  I peeked in here only to follow what's going on with testability.

**Comment by VladUreche** [comment]
Okay, thanks for the heads-up @som-snytt! I'll merge and we can deal with the fallout when refactoring partest.

**Pull request merged**
