### PR TITLE
Assortiment of cleanups and comments around the backend

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Tests went fine, review by @retronym

**Comment by lrytz** [comment]
Thanks @retronym for insisting on a before-after comparison: I found a serious issue and have to give up on introducing [`ownerAtCurrentPhase`](https://github.com/scala/scala/commit/187924c#diff-6cc67f90cb479803e84e8068d49663fbR1182). The problem is that the current phase in [`saveOriginalOwner`](https://github.com/lrytz/scala/commit/187924cf2495531938a0c838769d7b3774ebf5e3#diff-6cc67f90cb479803e84e8068d49663fbL67) can be anything, not necessarily the phase in which the owner was/is changed.

For example, the tree transformation in the lambdalift phase, which lifts definitions (and modifies their symbol's owner), is executed `afterOwnPhase`. Also, an owner might be modified in an info transformer, which are executed lazily.

I'll go back to just save the `originalOwner` for now. It's really hard to touch/improve incrementally around flags and owners that depend change depending on the phase :( I'm open to discuss things, but I think my time budget for that has run out long ago..

**Comment by lrytz** [comment]
[`-Ybackend:GenBCode` build](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1264/) ok

**Comment by lrytz** [comment]
removed `ownerAtCurrentPhase` again. review by @retronym, @gkossakowski

**Comment by gkossakowski** [comment]
LGTM.

In the future please emphasize the _why_ over _what_ when writing commit messages. A year from now it's going to be a lot easier to work out what has been changed in the diff than why it was done. I'd like to emphasize this point in our policy: https://github.com/scala/scala/wiki/Pull-Request-Policy

**Pull request merged**
