### PR TITLE
SI-8610 -Xlint is multichoice option

### PR DESCRIPTION
**Pull request by som-snytt**
Make -Xlint a "multichoice" option for purposes of option parsing.

This allows turning on "lint with these warnings" instead of only
"turn off these warnings but enable other lint warnings".

```
$ scalac -Xlint:warn-adapted-args linty.scala  # lint plus a warning
$ scalac -Xlint warn-adapted-args linty.scala  # same
$ scalac -Xlint linty.scala                    # same as now
$ scalac -Xlint -- linty.scala                 # ok, not necessary
$ scalac -Xlint _ -- linty.scala               # another funky underscore
```

This would also enable Xlint options that are not standalone options,
although that is not implemented in this commit.  For example,
`-Xlint:no-missing-interpolator` could be used to disable that
warning. (There is no `-Xoption:flavor=off` syntax.) (`no-` switches
would not be enabled by `_`.)

Review by @retronym who has expressed opinions about the warning group conundrum

### CODE REVIEW

**Comment by som-snytt** [comment]
Sorry, kitteh, I omitted a check file.

**Comment by retronym** [comment]
Maybe we should just mirror Java's approach and use `-XXX` rather than `noXXX`.

```
% javac -help -X
...
  -Xlint:{all,auxiliaryclass,cast,classfile,deprecation,dep-ann,divzero,empty,fallthrough,finally,options,overloads,overrides,path,processing,rawtypes,serial,static,try,unchecked,varargs,-auxiliaryclass,-cast,-classfile,-deprecation,-dep-ann,-divzero,-empty,-fallthrough,-finally,-options,-overloads,-overrides,-path,-processing,-rawtypes,-serial,-static,-try,-unchecked,-varargs,none} Enable or disable specific warnings
```

/cc @adriaanm as this seems to be in overlapping territory with his configurable warning system.

**Comment by retronym** [comment]
I'm in favour of consolidating the `-Y` options behind this mechanism. Also the currently anonymous ones that sit directly behind `-Xlint`.

Perhaps we could already deprecate the individual settings here and remove them on the `2.12.x` branch.

The more general error/warning config system could allow us to control these named warnings in a more fine grained way, ala `@SuppressWarnings` in javac.

**Comment by som-snytt** [comment]
I was within an eyelash of starting a discussion thread on the ML.

I didn't consult java this time; for the REPL's settings command, I personally found the dash ambiguous: +deprecation, -deprecation, because of the normal command line.

Since all the warnings start with warn, turning them off is always nowarn, like the mighty `-nowarn` itself. `scalac -Xlint:nowarn-missing-interpolator`.

But that breaks down in the general case, especially if we strip the somewhat redundant warn prefix.

**Comment by adriaanm** [comment]
Ping @retronym. To LGTM or -LGTM.

**Comment by retronym** [comment]
I'm going to close this one and then we can move over to #3792, which in addition to this change, starts to exercise the new feature (with `-Xlint:-warn-missing-interpolator`).

**Pull request closed without merging**
