### PR TITLE
SI-8233 Fix regression in backend with boxed nulls

### PR DESCRIPTION
**Pull request by retronym**
Regressed in SI-7015 / 1b6661b8.

We do need to "unbox" the null (ie, drop a stack from and load
a null) in general. The only time we can avoid this is if the
tree we are adapting is a `Constant(Literal(null))`.

I've added a test for both backends. Only GenICode exhibited
the problem.

Review by @gkossakowski, /cc @JamesIry

### CODE REVIEW

**Comment by gkossakowski** [comment]
I checked SI-8223 and there's no mention of null in that ticket. Is it some other ticket you meant?

**Comment by adriaanm** [comment]
It's SI-8233

**Comment by adriaanm** [comment]
We should really automate JIRA <> GitHub synch. I tried enabling it some time ago, but it doesn't work and I don't even know where to start in fixing it.

**Comment by retronym** [comment]
Yeah that's the one. It's a regression from 2.10 from jet brains. Another  report coming from Alexander tomorrow.

**Comment by gkossakowski** [comment]
@retronym: please fix the ticket number in the diff.

Other than that LGTM.

**Comment by retronym** [comment]
updated

**Pull request merged**
