### PR TITLE
rename source file with illegal-on-Windows name

### LINKED ISSUE #717: remove Windows-invalid characters from file path in 2.13.x branch
If you do `git pull` on scala repo in branch `2.13.x` on Windows you'll get

```
$ git pull
error: invalid path 'test/tasty/pos/src-3/tastytest_>>>/package.scala'
Updating b91a1445fc..a6e1a6f476
```
Note that `>` character is forbidden in Windows.
I could push the fix myself if I just could `git pull`, `rename`, `git push`, but I can't, cause.... I'm on Windows and `git pull` fails =D
Could you please rename the path to some Windows-friendly name?

### PR DESCRIPTION
**Pull request by SethTisue**
fixes scala/scala-dev#717

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/1451/

**Comment by SethTisue** [comment]
Windows run on Jenkins is green. Let's merge without waiting for further review as soon as the other CI runs are green

**Comment by som-snytt** [comment]
I was going to suggest `tastytest_$greater$greater$greater`...

**Pull request merged**
