### PR TITLE
immutable.LinkedHashMap

### PR DESCRIPTION
**Pull request by joshlemer**
Hi folks, I thought I would bring up yet an other `immutable.SeqMap` impelementation for discussion, which beats the current best implementation (VectorMap) in terms of:  
* memory usage (~16% less memory usage than VectorMap) 
* build time (from ~50% faster for small to ~15% faster for large maps)
* iteration (2x as fast as VectorMap)

, is equal to VectorMap in:  

* lookups

, and performs worse than VectorMap in:

* updates (VectorMap is ~30% faster)
* removals (VectorMap is ~43% faster)

I won't describe here the exact explanation of the data structure, since [there is a quite detailed explanation of the structure, as well as the algorithms for the above operations, included in the Scaladoc for the `immutable.LinkedHashMap` class itself](https://github.com/scala/scala/pull/8644/files#diff-4fb0a2a81364b15cd17f335f3a30c263R20).

### Benchmarks:

I have included benchmark results for the above operations in this gist :https://gist.github.com/joshlemer/af5dcfe6d7a7e34a9ddb0c4d0dcec79f which includes as well memory consumption for building.

### Arity 
`arity` is what I'm calling the maximum length of chains of forward-referencing Links in the Map (please see the scaladoc for a complete explanation). It can be finely tuned by changing the `LinkedHashMap.arity` method, but after playing around with it a bit, it seems that arity=2 strikes the best balance between iteration and writes. There's something like a 50% speedup in going from arity=1 to arity=2 with very little cost to writes, but going from arity=2 to arity=3, there's a significant slowdown to writes with diminishing benefits to iteration.

The general `updated` method is fully general over any arity, but it pays for that generality in speed. For this reason I've written hand-optimized versions of the method for when arity=1 and arity=2, these are the `updatedArity1` and `updatedArity2` methods respectively. Once an arity is decided on, we can just replace `updated` with the appropriate implementation.   
  
### Thoughts?

I've opened this draft PR just to get some feedback on if this data structure seems valuable? If folks here think that the gains in build/iteration/memory are worth the cost to updates/removals, and maybe for consideration as possibly the default SeqMap in much later versions of Scala?

 When 2.13 was released I think there were a few unknowns or work left to do but time kinda ran out before they could be fully thought through:

* which SeqMap to set as default (VectorMap or TreeSeqMap)
* which SeqMap to include at all (VectorMap, or VectorMap+TreeSeqMap)
* if we should deprecate ListMap (IMO, yes)
* Can VectorMap be further optimized? Maybe an implementation with RelaxedRadixBalancedVector would be make VectorMap strictly dominate TreeSeqMap and so TreeSeqMap would be rendered obsolete. Now with Stefan's improvements to Vector this is also worth revisiting IMO.
* Are there other potential contenders for best general SeqMap we haven't considered yet? (Enter: LinkedHashMap)

So this proposal / draft is just a continuation of that whole discussion. @odd @Ichoran

### CODE REVIEW

**Comment by szeiger** [comment]
How do you prevent the link chains from degenerating? Are chains ever split or concatenated?  Have you considered specializing the data structures for arity=2?

**Comment by joshlemer** [comment]
@szeiger Chains will degenerate in the case of successive removals, because `remove` will never fuse chains together. For arity > 2 it would update the remainder of the chain, and keep it in-tact (if the chain has 5 elements for example, it will update the 4 remaining to remain as a chain, but will not fuse the chain forwards or backwards to maintain size-5 chains). For arity=2, this is an unimportant detail because removing a link always results in a chain of length 1 or no chain at all. If it is length 1, it will not be fused forwards or backwards, and if 0, the two chains forwards and backwards remain separate as well.

I don't think that there is much specializing left to do after having implemented `updatedArity2` method. Though there is probably the opportunity to speed up `removed` a tiny bit by performing updates and removals to the hashmap in one bulk operation rather than 2 separate operations (here https://github.com/scala/scala/pull/8644/files#diff-4fb0a2a81364b15cd17f335f3a30c263R177)

**Comment by SethTisue** [comment]
for PRs that are unable to progress in 2.13.x, we are closing them but leaving them on the 2.14.0-M1 milestone so we can find them later

for context on this, see scala/scala-dev#661

**Comment by mkurz** [comment]
> for PRs that are unable to progress in 2.13.x, we are closing them but leaving them on the 2.14.0-M1 milestone so we can find them later

@SethTisue Does that mean you will re-open this pull request once you start working on Scala 2.14? (if there will be 2.14...)

**Comment by SethTisue** [comment]
> Does that mean you will re-open this pull request once you start working on Scala 2.14? (if there will be 2.14...)

There will not be a 2.14. The discussion on the status of such pull requests is at https://github.com/scala/scala-dev/issues/661

**Pull request closed without merging**
