### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by som-snytt** [comment]
The costs of trivial comment fixes are in git history and jenkins jobs.  Traditionally, such a change ranks with white space, or, these days, copyright updates.

Anyway, this particular typo would be funnier as `prescience` or, lower-brow, `presents`.

**Comment by adriaanm** [comment]
Luckily Git <3 Trivial Merges.

**Comment by som-snytt** [comment]
I meant that you go to look at git history and the latest trivial merge obscures the latest non-trivial.

But I just <3 that @adriaanm is full of <3.

**Comment by adriaanm** [comment]
There's always the pickaxe (for navigating history, not <3).

**Pull request merged**
