### PR TITLE
SI-4907 SI-4615 scala.bat now honors -J and -D options.

### PR DESCRIPTION
**Pull request by gourlaysama**
This makes scala.bat parse and use -J and -D arguments.

Specifically:
- Parameters starting with -J are stripped of the prefix, unquoted if
  necessary and appended to `%JAVA_OPTS%` or default values.
- Parameters starting with -D are unquoted if necessary and then
  appended to the others. The right-hand side of a property can be
  quoted or not.
- All of those are given to `java` before any other parameters.
- The above only happens on parameter preceding the first parameter
  that does not start with "-" (usually a class name).
- The exact arguments passed to scala.bat are also given as-is to
  the scala launcher (including -J and -D arguments).
  
  ``` bat
  set JAVA_OPTS=-Xmx512m
  scala -J-Xmx128m -Dprop1=42 -Dprop2="hello world" "-Dprop3=bar"
  "-J-Xms64m" Test foo
  ```
  
  will result in
  
  ``` bat
  java -Xmx512m -Xmx128m -Dprop1=42 -Dprop2="hello world" -Dprop3=bar
  -Xms64m [cp, scala main] -J-Xmx128m -Dprop1=42 -Dprop2="hello world"
  "-Dprop3=bar" "-J-Xms64m" Test foo
  ```

### CODE REVIEW

**Comment by som-snytt** [comment]
I can try it out next time I boot into Windows.  I reboot into Windows periodically so it can install security updates in smaller chunks.

What about -D?  Or did it already do -D?  I thought I once saw a PR that made this look hard.

**Comment by gourlaysama** [comment]
Yes, adding -D is messier because = is a delimiter like space, so cmd splits `-Dfoo=bar` in two parameters and then throws the = out. I'll try to add -D support later today in a second commit.

**Comment by gourlaysama** [comment]
@som-snytt added -D support alongside -J.
I only tested on Windows 7, but it seems fairly robust.

**Comment by som-snytt** [comment]
> fairy robust.

I bet you were thinking "fairy dust".

**Comment by gourlaysama** [comment]
Oops. So I almost used "Windows 7" and "fairy dust" in the same sentence. Scary.

Oh, I found the original ticket about -D options: [SI-4615](https://issues.scala-lang.org/browse/SI-4615), with PR #1957. I thought there wasn't one, I couldn't find it using JIRA's issue search...

Now I see what you meant, this is getting ugly. Looking at that ticket, my implementation is only "fairly robust assuming people do not quote things than should not be quoted". So very naive, actually.

Anyway, a new version is coming...

**Comment by som-snytt** [comment]
Ditto oops. We had a planned electric service interruption, so I booted into Windows, fetched 2.10.x + your branch and am building.  Next time I'll be ready.

Yes, that's the conversation I recall.  I had forgotten the suggestion to stick -Ds in the env and have a special entry point to tokenize.  That seems of general utility, since other tools suffer the same problem. (partest)

**Comment by gourlaysama** [comment]
Ok, this is my final-ish version. It is succinct enough to be maintainable and does pretty much everything than can be done without hand-tokenizing the whole command-line input.

It is sad that there is no automated way to test those scripts by the way...

**Comment by gkossakowski** [comment]
@som-snytt: do you want to take this one?

**Comment by gkossakowski** [comment]
Also, I'm wondering if merging this to 2.10.x is safe. What's the risk of any regression?

**Comment by gourlaysama** [comment]
Well, the scala main class is given the exact same arguments as before: the entire raw command-line content. That line isn't even changed by this commit (L113 in the new version). So scala is guaranteed to receive the same thing.

The only sort-of regression I can think of is when things happened to work because a property was ignored, and would stop working now. Like this (very stupid!) example:

``` bat
:: this worked fine before, but now breaks JLine!
scala -Dfile.separator=a
:: or we can break the JVM
scala -J-Xmx1k
```

But that only makes incorrect programs stop working. Hardly a regression.

**Comment by som-snytt** [comment]
Reporting from Windows, I have tried it out. I applaud the effort. In the last year, I sat down to learn enough windows shell to do it, but suffered from extreme lack of motivation.

Were you intending to handle:

```
C:\Users\apm>scala.bat "-Dmyfoo=my bar" -J-Xmx512M foo.scala
Error: Could not find or load main class bar
```

You will answer, "Of course not, if you'll take a moment to read the script and my previous comments on this issue."

Maybe something to document as a limitation.  I haven't tried it, but I thinking of people forking "scala.bat something" programmatically; easy to see extra quotes that way.

**Comment by gourlaysama** [comment]
Fixed.

Yes that was a limitation. but I actually forgot about it later. With what I added in my last attempt, it was easy to handle.

I also added special handling for `-e "whatever"` so that this works too:

``` bat
scala.bat -e "println(1+1)" -Dfoo=bar
```

Previously properties after this option were ignored.

**Comment by adriaanm** [comment]
ping @som-snytt, sounds like this is ready to go

**Comment by som-snytt** [comment]
LGTM and RTG.  The sooner it's in, the more daily exercise it gets.  I haven't taken the latest revision out for a walk yet.

**Pull request merged**
