### PR TITLE
Use faster way to lookup List.apply symbol

### PR DESCRIPTION
**Pull request by retronym**
I accidentally changed this to use Definitions.List_apply
in #6618.

### CODE REVIEW

**Comment by retronym** [comment]
This is a trivial fix, so merging without review.

**Comment by retronym** [comment]
The [benchmarks](https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark?orgId=1&from=1526263688969&to=1526855783878&var-branch=2.13.x&var-source=All&var-bench=HotScalacBenchmark.compile&var-host=scalabench%40scalabench%40) like it:

image

**Comment by adriaanm** [comment]
Why is this faster?

**Comment by retronym** [comment]
Rundefinitions is a cache of member symbols like Symbol.apply. It isn’t
correct to cache them in definitions, as they can vary from run to run in
IDE use cases

List_apply is unusual in that I didn’t remove the def from definitions
after factoring it into rundefinitions. I think this was because of
compatibility reasons.

**Pull request merged**
