### PR TITLE
[REJECTED] Allow null: Int

### PR DESCRIPTION
**Pull request by som-snytt**
The history of this restriction seems to be about unboxing anxiety.

Now that unboxing null has been sorted out:

```
scala> val x: Int = java.lang.Integer.valueOf(42)
x: Int = 42

scala> val x: Int = null
x: Int = 0

scala> def f: Int = null: Int
f: Int

scala> f
res0: Int = 0
```

### CODE REVIEW

**Comment by neontorrent** [comment]
Sorry I might have missed something, but when did we sort out unboxing nulls?

And if we allow null to be assigned to AnyVal, does that mean Null will be the lower bound for all Any from now on?

**Comment by som-snytt** [comment]
@texasbruce Not saying it's a good idea -- I just wanted to try out "draft" mode PR -- but it stems from the question whether null is allowed to participate in conversions such as `null -> 42`.

This is just boxing, since null is an Integer. It's an assignment of unboxed Int to `x`.

The enabling fix was that unboxing null works correctly now.

issues/4158
issues/6899
pull/2625
https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/cwEyQCmjX24

Actually dangerous things:
```
scala> { implicit val v = null ; implicitly[String] }
res0: String = null
```

**Review by smarter — CHANGES_REQUESTED** [review]
Please no, there's no reason to allow that, we're trying to move towards having null in less types, not more: https://github.com/lampepfl/dotty/pull/6344

**Comment by som-snytt** [comment]
My Java colleague asked why I use `Objects.isNull`, I said it's so I don't have to type the n-word.

**Comment by som-snytt** [comment]
Closing despite the useful coinage, "unboxing anxiety". ("If you see a suspicious package...")

I like the putty gray draft mode.

I think for smarter, github should have a button to "request no changes".

**Comment by neontorrent** [comment]
@som-snytt You can always use `Option[Int]` and None to indicate missing value. This is more idiomatic in Scala imo

**Comment by som-snytt** [comment]
Indeed. I was going more for idiotic than idiomatic.

Actually, it occurs to me that when they disallow underscore syntax:
```
var x: Int = null
var y: Int = null.asInstanceOf[Int]    // https://github.com/scala/bug/issues/11700
```
Edit: almost hit reopen by accident

**Pull request closed without merging**
