### PR TITLE
Replace Cloneable/Serializable traits with type aliases

### PR DESCRIPTION
**Pull request by smarter**
Fixes scala/bug#9080.

This commit is adapted from #5288 and is thus:

Co-authored-by: Simon Ochsenreither <simon@ochsenreither.de>

### CODE REVIEW

**Comment by smarter** [comment]
This PR doesn't actually compile currently, I get:
```scala
[debug]         /home/smarter/opt/scala/build/quick/classes/reflect:/home/smarter/opt/scala/build/quick/classes/library
scala.reflect.internal.MissingRequirementError: class scala.Serializable not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
        at scala.reflect.internal.Mirrors$RootsBase.ensureClassSymbol(Mirrors.scala:96)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:101)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:104)
        at scala.reflect.internal.Mirrors$RootsBase.requiredClass(Mirrors.scala:107)
        at scala.reflect.internal.Definitions$DefinitionsClass.SerializableClass$lzycompute(Definitions.scala:375)
        at scala.reflect.internal.Definitions$DefinitionsClass.SerializableClass(Definitions.scala:375)
        at scala.reflect.internal.Definitions$DefinitionsClass.isPossibleSyntheticParent$lzycompute(Definitions.scala:1378)
        at scala.reflect.internal.Definitions$DefinitionsClass.isPossibleSyntheticParent(Definitions.scala:1378)
```
This also happened at some point in #5288 but was apparently resolved: https://github.com/scala/scala/pull/5288#issuecomment-236427423. Assuming it actually worked then I don't see why it's failing now. Is it possible that the resolving rules have changed such that `scala.package.Serializable` is now preferred to  `scala.Serializable`?

**Comment by smarter** [comment]
Opened https://github.com/scala/scala/pull/6730 to try to solve the bootstrapping conundrum.

**Comment by lrytz** [comment]
I think we should merge #6730 and do the change here after M5.

Why doesn't this PR remove the Serializable / Cloneable traits?

**Comment by smarter** [comment]
> Why doesn't this PR remove the Serializable / Cloneable traits?

Done. This required tweaking https://github.com/scala/scala/pull/6730 more.

**Comment by lrytz** [comment]
Looks good! Let's reopen this after releasing M5. I marked https://github.com/scala/bug/issues/9080 as blocker and assigned it to RC1 to make sure we don't forget.

**Comment by smarter** [comment]
Reopened and rebased now that M5 is out.

**Review by lrytz — APPROVED** [review]
👍

**Comment by milessabin** [comment]
Somewhat to my surprise, git bisect is blaming this PR for shapeless's current brokeness in the community build: https://github.com/milessabin/shapeless/issues/857. Reverting 82fd5910a2862ccc9967e99c7e9828453eed195a confirms it.

I'll try and work out what's going on.

**Comment by milessabin** [comment]
It appears that the problem is that an intersection previously inferred as `Product with Serializable with Fruit` is now being inferred as `Product with Fruit with java.io.Serializable` which is being used in an invariant context where the two are incompatible.

I can't see any obvious way of tweaking the test which will cross build before and after this PR. It's not a huge deal in this case, and [I've commented out the test](https://github.com/milessabin/shapeless/commit/6b54d3c33c83cc730c472a91c9d874ac925f8147) without any real loss, but it suggests that this change might cause bigger problems elsewhere in the community build.

**Comment by SethTisue** [comment]
thanks, I'll keep an eye out for it.

**Pull request merged**
