### PR TITLE
FSC / REPL Bug Bonanza

### PR DESCRIPTION
**Pull request by retronym**
The big contribution here is to change `adaptInfos` to
start with a clean slate (a one element type history)
on subsequent runs. I did the same a while back for package
classes, this is an generalization of that idea. This ensures
that all info transformers are run, importantly the side-effecty
ones.

This fixes a regression in specialization in the REPL, which
was a latent bug uncovered by our recent fix to `perRunCaches`.

The other changes are similarly themed, being more disciplined
when reading or mutating the type history.

Submitting for a test run and initial review by @lrytz. The commit
messages might need some fleshing out as I've been a little bit
hand wavy in a few of my explanations where I wasn't able to
precisely explain _why_ the fix works.

### CODE REVIEW

**Comment by retronym** [comment]
Manually assigned to 2.11.4, we're too close to 2.11.3 for these changes.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@a654060
PLS REBUILD/pr-scala@24a0777

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@a654060

**Comment by retronym** [comment]
I've dumped SI-6782 into the too hard basket for now. My WIP is noted in that ticket's JIRA comments.

**Comment by retronym** [comment]
ping @lrytz

**Comment by lrytz** [comment]
I like the change, I think it's the right thing to do. It probably fixes more issues that went undiscovered until now.

I'm just wondering about performance for the IDE. Does the IDE create a new run for each typecheck? That would be quite often, and after this change all info transformers would run again on all symbols that are involved. WDYT?

**Comment by retronym** [comment]
The IDE only runs to the typer phase, so unless something during typer is travelling forward through the phases, there should be no difference.

**Comment by lrytz** [comment]
LGTM - of course :)

**Pull request merged**
