### PR TITLE
constructors phase refactoring (2nd attempt)

### PR DESCRIPTION
**Pull request by magarciaEPFL**
The `constructors` phase has grown over time, with sub-transformations being added to the all-encompassing `transformClassTemplate()` on an as-needed basis.

This PR breaks that method apart, encapsulating each sub-transformation in a trait dedicated to it. Documentation has been thrown in, too.

This PR essentially plays again the commits of https://github.com/scala/scala/pull/2599
adapted to `Constructors.scala` in its current form.

Those commits were once merged into master, but had an ephemeral existence:
they were inadvertently _overwritten_ by the merge of 2.10.2 into master,
see commit 767a25fe2178b00f494d55bdaae53535cd7fb57d 

This PR is a pre-requisite for an upcoming re-submission of https://github.com/scala/scala/pull/2665 ,
to make anon-closures retain fewer heap objects (currently, in some cases, more objects are retained via outer-refs than really needed).

Please merge this PR before Constructors.scala drifts again.

review by @JamesIry

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
@JamesIry , now that I come to think of it, last time we talked was 4 months ago in https://github.com/scala/scala/pull/2214 . Wow, time flies.

**Comment by gkossakowski** [comment]
@JamesIry: ping.

Also, I'll refresh status of this PR just to make sure all tests still pass.

@magarciaEPFL: sorry for the delay, we've been super busy on this side of the ocean.

**Comment by magarciaEPFL** [comment]
I can't reproduce the build failures. What I see is:
- check out master as of https://github.com/scala/scala/commit/4c62f7db6f3913eedd92d85daf8f631149cc97b2
- apply this PR
- build nightly

Everything works fine.

**Comment by adriaanm** [comment]
The problem is that these commits are integrated against the IDE, and the scala-xml refactoring (which is assumed by the IDE build) is not a parent of these commits. I'll look into rebasing.

**Pull request closed without merging**
