### PR TITLE
Avoid creating and flattening a List of Options.

### PR DESCRIPTION
**Pull request by diesalbla**
The existing code was creating a `relationships: List[Option[String]]`, which was immediately flattened into the `messages: List[String]`. Instead, we use a list buffer. This should save the allocations of the intermediate list and the `Some` objects created.

### CODE REVIEW

**Comment by som-snytt** [comment]
The current code is confusing, but the `Some("")` and `None` make it easy to see the cases.

I'm not sure eliminating the boxing saves much, except for the comment on `foundReqMsg` about avoiding work; I know there has been an issue about doing work on an error path that is discarded because it is recoverable or retried.

I see expensive `format` calls, and hitting the `None` case should short-circuit and avoid any further `mkMsg`; it should just build the string, keep a count, and short-circuit, avoiding the `filterNot` on empty messages. To be maximally listless, it should use `found.baseTypeSeq.toIterator` instead of `toList`.

I think if the code becomes a little harder to read, it might as well be a bit more optimized.

The real problem remains that the work is done in silent mode (if that's the case here); usually, extra diagnostics are allowed to be expensive because you're just erroring out anyway.

**Comment by diesalbla** [comment]
> I see expensive format calls, and hitting the None case should short-circuit and avoid any further mkMsg; it should just build the string, keep a count, and short-circuit, avoiding the filterNot on empty messages

On that note, I have noticed in several places that there is an over-use of `String` creation and concatenation, even for intermediate Strings that are immediately concatenated. That could be creating a lot of garbage. Perhaps it would be good to replace many of the uses of "Strings" with methods to write into a `StringBuilder`, as a Writer.

**Comment by diesalbla** [comment]
> I see expensive format calls, and hitting the None case should short-circuit and avoid any further mkMsg; it should just build the string, keep a count, and short-circuit, avoiding

If you mean using a `return ""`, I prefer to avoid using goto-like statements. As a matter of fact, and now that I am looking twice at the code, since there is a `return` statement inside the `foreach`, it looks as if this would only report the first element in the `baseTypeSeq` for which it does not yield `None`.

**Comment by retronym** [comment]
👎 for me. This code is rarely called (only generating type errors that are destined for the user), and it doesn't appear as an allocation hotspot in our profiles.

**Pull request closed without merging**
