### PR TITLE
new bytecode emitter, GenBCode (4th attempt)

### PR DESCRIPTION
**Pull request by magarciaEPFL**
Compared to the previous submission this PR adds functionality to GenBCode in stages, with additional documentation.

Testing against the community build will provide more information than isolated tests.
Bytecode tests are by their very nature fragile (e.g., testing first that pattern matching emits a chain of jump, only to make sure a moment later that chain of jumps has been collapsed by GenBCode). Concrete ideas and examples on how to balance usefulness vs brittleness are welcome.

Reviews about the content proper of the PR are most welcome.

review by @gkossakowski or @JamesIry or @retronym or @paulp

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
Beyond the two commits above, more refactoring (finer granularity, more focused commits) has been going on for the new backend:

https://github.com/magarciaEPFL/scala/compare/master...GenRefactored42

**Comment by magarciaEPFL** [comment]
Answering an offline question: nightly builds of scalac are no problem with the new backend / optimizer , under all optimization levels.

First, update build.xml to the desired optimization level:

```
-    <antcall target="@{name}"><param name="scalac.args.optimise" value="-optimise"/></antcall>
+    <antcall target="@{name}"><param name="scalac.args.optimise" value="-neo:o3"/></antcall>
```

Second, `ant all.clean && ant && ant replacelocker && ant nightly`

**Comment by magarciaEPFL** [comment]
Another time saving feature: to activate by default the new backend (thus making scalac 15% faster) simply change in `ScalaSettings`

```
  val neo = ChoiceSetting ("-neo", "choice of bytecode emitter", "Choice of bytecode emitter.",
                           List("GenASM", "GenBCode", "o1", "o2", "o3"),
                           "GenBCode") // in trunk "GenASM" should be the default
```

In fact, the default can be ticked up to `o1` (intra-method optimizations). The extra compilation time is negligible on, say, a two-core machine or better (negligible because those optimizations overlap in time with the compiler pipeline).

Take that, GenICode !!!

**Comment by paulp** [comment]
Yow, 6000 lines is going to take some time.

**Comment by magarciaEPFL** [comment]
I've been told the source comments in this commit read like a novel. For those moments when one just wants to chill out.

**Comment by paulp** [comment]
Does anyone know if there's some way to make github show me the whole diff without going to "view file"? The two giant files are presented with all the prominence of a nanochameleon. "3975 additions, 0 deletions not shown" is one way to hint that the several pages of diff they are showing me aren't everything, I guess. If I didn't know this commit had to be bigger I would most likely have never seen them.

**Comment by paulp** [comment]
As a first swing which will help with the rest, we do not need any more 4000 line files. There's no reason for code without the "legacy excuse" to be this large. As long as we have no better than file granularity for incremental recompilation, that should be reason enough to dramatically break this thing up. I'm sure some divisions suggest themselves.

**Comment by paulp** [comment]
> I've been told the source comments in this commit read like a novel. For those moments when one just wants to chill out.

Today's kids scorn the novel! You should read like twitter if you want a hit.

**Comment by magarciaEPFL** [comment]
Breaking up `BCodePhase.PlainClassBuilder` looks doable (that's the elephant in the room, 3 KLOC)

I'll break it up and re-submit.

**Pull request closed without merging**
