### PR TITLE
Mbileschi update string like documentation

### PR DESCRIPTION
**Pull request by mlbileschi**
Update StringLike Documentation to indicate what happens when you remove a prefix from a string, and the string doesn't have that prefix.

### CODE REVIEW

**Comment by lrytz** [comment]
this PR seems to include too many commits

**Comment by mlbileschi** [comment]
I have just created a new clone, remote updated, and pulled origin 2.12.x into my local branch. Any ideas?

**Comment by lrytz** [comment]
Pull origin/2.11.x for PRs that should go into 2.11.x (which is the current default for anything binary compatible).

**Comment by mlbileschi** [comment]
is the convention to open a new pull request, or to fix this one?

**Comment by lrytz** [comment]
You can push -f to this one, that's fine.

**Comment by mlbileschi** [comment]
pushed, don't know if the pushed changes are reflected.

**Comment by lrytz** [comment]
You branched off some quite old commit (https://github.com/mlbileschi/scala/commits/mbileschi-updateStringLikeDocumentation), try fetching.

**Comment by mlbileschi** [comment]
ugh. couldn't mend it, so i reposted here https://github.com/scala/scala/pull/3950

**Pull request closed without merging**
