### PR TITLE
Issue/6153

### PR DESCRIPTION
**Pull request by bhuber**
This is my patch for the BigDecimal.hashCode bug, as discussed at https://issues.scala-lang.org/browse/SI-6153 .  I'm quite new to Scala, so any suggestions for improvement are welcome.  Some things it fixes:
- BigDecimal still returns same hashCode for equivalent values (e.g. "2" and "2.00")
- BigInt and BigDecimal now return same hashCode for equivalent values
- BigDecimal returns same hashCode as for equivalent Int, Long, and
  Double values
- BigDecimal hashCodes are no longer "stratified", as discussed in the original bug report
- Although the new version is more expensive to compute than the old, the result is saved so it only has to be computed once

It's worth noting that since this changes the hashCode algorithms for BigInt and BigDecimal, it could break serialized data structures that rely on them (e.g. if someone serializes a hash table from an old version of Scala and tries to load it into a new one, it may cause problems).

--Bennet Huber

PS Thanks to Paul Phillips for initial patch skeleton

### CODE REVIEW

**Comment by paulp** [comment]
I'm less than convinced that those who use BigDecimals as hash keys (which seems like a really bad idea for the same reason it's a bad idea to test floats for equality) should benefit by penalizing everyone else who uses BigDecimal with an extra int of storage and the lazy val bitmap.

**Comment by ijuma** [comment]
"(e.g. if someone serializes a hash table from an old version of Scala and tries to load it into a new one, it may cause problems)"

As an aside, this should only happen for badly implemented serialization schemes. The correct way to serialize a hash table involves ignoring hash codes. This is a change I made for Scala collections a while ago. Of  course, much new code has been introduced since then and I haven't checked it all.

**Comment by soc** [comment]
I'm also very concerned about the additional storage requirements. Every bit matters there. Let's not make the same mistake as Java, which has a whopping 4 deprecated public `int` fields in `BigInteger` (and therefore also `BigDecimal`) which they will never get rid off again for the rest of Java's life.

**Comment by bhuber** [comment]
A couple of things:

First of all, here's why the build failed:

>  [partest] java.lang.AssertionError: assertion failed: Int.hashCode != Long.hashCode for value -342342
>  [partest] 
>  [partest]    at Test$.checkHashCode(t6153.scala:24)
>  [partest]    at Test$.main(t6153.scala:51)
>  [partest]    at Test.main(t6153.scala)

This is pretty weird; I'm not sure what's causing it.  The Java docs say that Long.hashCode is calculated by xoring the top 32 bits with the bottom 32 bits, so -342342 should have the same hashCode for both Long and Int types, and I've verified this is the case on my machine (openjdk-7 32 bit).  If anyone has any idea why this would be different on the build slave, I'd like to hear it.  When I get the chance I'll try testing it on some other JDKs and see if I can replicate it.

Second, regarding adding an extra 4 bytes for storing the hashCode: I'm definitely not married to this idea, and people seem to think it's not worth the tradeoff, so I'm happy to get rid of it.  Paul brings up a good point that storing BigDecimals in sets or dictionaries is probably not a typical use case.  I would like to investigate what the typical size of a BigDecimal object is though.  If it's like 200 bytes or something, adding an extra 2% memory usage would seem like a good tradeoff, but I suspect it's probably much less than that.  I'll follow up with results when I get a chance to test this.

Third, there's a much bigger problem with this fix that I encountered last night: for large BigDecimal values, the toPlainString() function - which the new version of hashCode relies on - will blow the heap and throw an exception.  A more intelligent solution is therefore in order.

I unfortunately will not be able to work on this again until Monday night at the earliest, but I'll leave the request open until then so people can continue to leave feedback.

**Comment by paulp** [comment]
FYI it's four bytes plus lazy val overhead, which is at minimum another boolean.

**Comment by jsuereth** [comment]
Review by @alex22 or @phaller

Also, have you signed the scala CLA?

**Comment by bhuber** [comment]
@jsuereth yes, I just got confirmation back from Danielle Chamberlain that she has received it.

**Comment by jsuereth** [comment]
Great.   I'm with paulp.  -1 on lazy val, go val or def.   having hashCode synchronize seems poor for performance.

**Comment by paulp** [comment]
If we can have a version of this with a slow, correct hashCode implemented via def, it will have my endorsement.

**Comment by bhuber** [comment]
Sounds good.  After reading up on the performance implications of the lazy keyword, I'm inclined to agree we shouldn't use it.  I'm hoping to get some time this week to take a second crack at the hashCode implementation and find a way to do it that won't explode the heap for large numbers.

**Comment by paulp** [comment]
Okay, we need to keep the hallway clear so I'm closing this.  Please reopen when you have something you'd like to see merged.

**Pull request closed without merging**
