### PR TITLE
SI-8927 Update OSGi stuff to get rid of bndlib warning

### PR DESCRIPTION
**Pull request by soc**
The way the desired OSGi frameworks are chosen has changed between
Pax Exam versions:

On earlier versions, specifying it in code was fine, but PAX Exam 4.x
runs the tests on the first OSGi framework it finds on classpath.

An exclusion for the transitive dependency org.osgi.core was added,
because it seems that artifact has broken dependecies (which would
have brought us back to square one).
Good thing is that it isn't needed here, because the OSGi framework JARs
contain all necessary classes.

### CODE REVIEW

**Comment by soc** [comment]
Thanks to and pre-review by @rkrzewski, work was done by him.

**Comment by rkrzewski** [comment]
The reason for test failure was that PAX Exam 4.x requires JDK 7.
I've checked locally that downgrading PAX Exam to version 3.5.0 allows the tests to pass on JDK 6.

**Comment by soc** [comment]
@rkrzewski Yes, I changed that, but now BasicTest is failing again ...

```
java.lang.NoSuchMethodError: org.osgi.framework.BundleEvent.<init>(ILorg/osgi/framework/Bundle;Lorg/osgi/framework/Bundle;)V
    at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4249)
    at org.apache.felix.framework.Felix.installBundle(Felix.java:2881)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)
    at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:138)
    at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:307)
    at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:175)
    at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)
    at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:278)
    at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:112)
    at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
```

**Comment by rkrzewski** [comment]
Weird. The stacktrace above indicates a classpath issue.
Here's what I've been testing: https://github.com/rkrzewski/scala/tree/SI-8927
I've recompiled everyting from scratch under JDK 1.6.0_45 and verified that `ant test.osgi` passes.
Can you send me `build/osgi/TEST-tools.test.osgi.BasicTest.xml` by email? I'd like to take a look at classpath details.

**Comment by soc** [comment]
Here it is: https://gist.github.com/soc/39598ec3c6b4bb0d5295

(I also removed the exclude `<exclusion groupId="org.osgi" artifactId="org.osgi.core"/>` but I think this shouldn't be the cause of the issue, right?)

**Comment by rkrzewski** [comment]
You shouldn't have. That precisely _is_ the issue ;)

**Comment by soc** [comment]
Oh dammit! Sorry, for that ... I'll fix it and `push -f` it again.

**Comment by soc** [comment]
Mhhh, based on commit history review by @adriaanm might be the best, I guess.

**Comment by adriaanm** [comment]
LGTM! Sweet! Thanks for figuring out the magic incantation. One step closer to noiseless builds!!

**Pull request merged**
