### PR TITLE
Fail early if self-referential LazyList runs out of elements

### PR DESCRIPTION
**Pull request by NthPortal**

### CODE REVIEW

**Comment by NthPortal** [comment]
How do I check how this change affects the size of `LazyList`s on the heap? cc @szeiger

**Comment by szeiger** [comment]
In simple cases where you want to compute the size of a single instance you can use [jol](https://openjdk.java.net/projects/code-tools/jol/). This is useful, for example, for checking if there's free space (due to alignment on a typical x64 JVM) for an extra field.

If you want to test sizes of larger object graphs where you might not even know all the anonymous classes involved, there's `scala.tools.testkit.AllocationTest` which checks actual heap sizes at runtime.

**Comment by szeiger** [comment]
Could this situation occur in a non-empty LazyList? Would it be better to treat such lists as empty instead of aborting?

**Comment by NthPortal** [comment]
`val ll: LazyList[Int] = 1 #:: ll.map(_ + 1).filterNot(_ % 2 == 0)` is an example that occurs in a non-empty `LazyList`. The intent (it seems) is to generate all the odd numbers; however, after `2` is filtered out, it runs out of elements to `map` (rather than moving on to `3`). It represents an error on the part of the client of the `LazyList`, rather than an error in the implementation of `LazyList`. This PR changes it from overflowing the stack to throwing a more descriptive exception.

I originally started looking into this problem because of [a question in the Scala discord](https://discordapp.com/channels/632150470000902164/632150470000902166/662857910950297602).

**Review by szeiger — APPROVED** [review]
(should be squashed when merging due to failing commit)

**Comment by NthPortal** [comment]
before:

```
scala.collection.immutable.LazyList object internals:
 OFFSET  SIZE                                        TYPE DESCRIPTION                                                    VALUE
      0     4                                             (object header)                                                01 00 00 00 (00000001 00000000 00000000 00000000) (1)
      4     4                                             (object header)                                                00 00 00 00 (00000000 00000000 00000000 00000000) (0)
      8     4                                             (object header)                                                05 f7 01 f8 (00000101 11110111 00000001 11111000) (-134088955)
     12     1                                     boolean LazyList.scala$collection$immutable$LazyList$$stateEvaluated   false
     13     1                                     boolean LazyList.bitmap$0                                              false
     14     2                                             (alignment/padding gap)
     16     4   scala.collection.immutable.LazyList.State LazyList.scala$collection$immutable$LazyList$$state            null
     20     4                             scala.Function0 LazyList.lazyState                                             null
Instance size: 24 bytes
Space losses: 2 bytes internal + 0 bytes external = 2 bytes total
```

after:

```
scala.collection.immutable.LazyList object internals:
 OFFSET  SIZE                                        TYPE DESCRIPTION                                                     VALUE
      0     4                                             (object header)                                                 01 00 00 00 (00000001 00000000 00000000 00000000) (1)
      4     4                                             (object header)                                                 00 00 00 00 (00000000 00000000 00000000 00000000) (0)
      8     4                                             (object header)                                                 05 f7 01 f8 (00000101 11110111 00000001 11111000) (-134088955)
     12     4                                         int LazyList.scala$collection$immutable$LazyList$$evaluationState   0
     16     1                                     boolean LazyList.bitmap$0                                               false
     17     3                                             (alignment/padding gap)
     20     4   scala.collection.immutable.LazyList.State LazyList.scala$collection$immutable$LazyList$$state             null
     24     4                             scala.Function0 LazyList.lazyState                                              null
     28     4                                             (loss due to the next object alignment)
Instance size: 32 bytes
Space losses: 3 bytes internal + 4 bytes external = 7 bytes total
```

that size increase (of 33%) is highly un-ideal; I'll see if I can fix that by either using another `boolean` or  by using a `byte` instead of an `int`

**Comment by NthPortal** [comment]
I decided to go with two booleans, as it made the code cleaner and clearer, and significantly reduced the diff size on the implementation.

new layout:

```
scala.collection.immutable.LazyList object internals:
 OFFSET  SIZE                                        TYPE DESCRIPTION                                                    VALUE
      0     4                                             (object header)                                                01 00 00 00 (00000001 00000000 00000000 00000000) (1)
      4     4                                             (object header)                                                00 00 00 00 (00000000 00000000 00000000 00000000) (0)
      8     4                                             (object header)                                                05 f7 01 f8 (00000101 11110111 00000001 11111000) (-134088955)
     12     1                                     boolean LazyList.scala$collection$immutable$LazyList$$stateEvaluated   false
     13     1                                     boolean LazyList.midEvaluation                                         false
     14     1                                     boolean LazyList.bitmap$0                                              false
     15     1                                             (alignment/padding gap)
     16     4   scala.collection.immutable.LazyList.State LazyList.scala$collection$immutable$LazyList$$state            null
     20     4                             scala.Function0 LazyList.lazyState                                             null
Instance size: 24 bytes
Space losses: 1 bytes internal + 0 bytes external = 1 bytes total
```

it uses one more byte than the layout before this PR, but that byte is lost to padding anyway (so we're still at 24 bytes). if that extra byte is a concern (it doesn't affect 32 bit size either though), I can change the code to use a byte (and possibly treat it as a bit field to retain clarity?)

**Comment by NthPortal** [comment]
@szeiger could I get a quick re-review?

**Review by szeiger — APPROVED** [review]

**Pull request merged**
