### PR TITLE
Move check for undefined members in objects from Namer to RefCheck

### PR DESCRIPTION
**Pull request by gzm0**
Alternative to #3375 (closed)

When writing an object (or an anonymous class) with declared but undefined members, the compiler complains specifically about the method which is not allowed:

```
object Foo {
  def x: Int  // will cause an error message
}
```

will emit

```
test.scala:16: error: only classes can have declared but undefined members
  def x: Int
      ^
```

This check has been performed by the Namer, unlike other checks for completeness of classes that are performed in the RefCheck phase. There are two issues with that:
1. The test in the Namer is conceptually wrong and only shallow (it e.g. does not check for unimplemented inherited abstract methods)
2. This does not allow compiler plugins to generate such code in a post-Typer but pre-RefCheck phase.
3. The testing code exists twice. So this commit removes some duplicate code.

This commit moves the check to the RefCheck phase. The example code above will now emit the following error:

```
test.scala:15: error: object creation impossible, since method x is not defined
object Foo {
       ^
```

The new test `undefined-members` verifies that behavior stays the same.

### CODE REVIEW

**Comment by soc** [comment]
This and #3375 look like they could be exactly what I need for `@enum`s, where I want to have undefined members in the enum class which the individual enum instances implement.

**Comment by gkossakowski** [comment]
@soc brought up a good point that with this change even blackbox macros will be able to provide implementation of undefined members in objects so:

``` scala
blackboxMacro {
  object foo { def bla: Int }
}
```

will now compile assuming blackboxMacro implements `bla`. I'm not exactly fond of opening up this new way of bending the language. I'd prefer blackbox macros to be transformers from valid Scala programs to valid Scala programs. This would mean moving more checks from refchecks to typer and not the other way around.

**Comment by xeno-by** [comment]
How would a blackbox macro be able to make generated classes/objects visible?

**Comment by gkossakowski** [comment]
It's visible within the scope of the argument to the blackbox macro. I'm talking about scenario like:

``` scala
blackboxMacro {
  object foo { def bla: Int }
  println(foo.bla)
}
```

that gets expanded to

``` scala
{
  object foo { def bla: Int = 12 }
  println(foo.bla)
}
```

With this change merged, you'll be able to write a blackbox macro that will do exactly that kind of transformation (which is not possible at the moment because the check for unimplemented members of objects will run before macro has a chance to run).

**Comment by gzm0** [comment]
@adriaanm Pinging as promised.

It turns out that the checks disallowing stuff like the following:

```
object A {
  type X
}
```

are actually against the Scala specification (§5.2):

> If the template forms part of a concrete class definition, stats may still contain declarations of abstract type members, but not of abstract term members.

Last commit fixes this.

**Comment by xeno-by** [comment]
@gzm0 Given its history, I would take what's written in SLS with a grain of salt. I definitely remember Martin telling me that allowing abstract members in classes, but not objects, was a deliberate decision.

**Comment by gzm0** [comment]
Hmm... I talked to Martin this morning, he said it's OK if we remove that check. Maybe I understood wrong. /cc @odersky

**Comment by gzm0** [comment]
Note that in any case, the check until now was only shallow:

```
trait Foo {
  type X
}

object Bar extends Foo
```

Compiles even without this PR.

**Comment by adriaanm** [comment]
It would be great to use this opportunity to nail down what's allowed and what isn't. I also remember some exceptions for allowing abstract type members in concrete classes/objects (I guess since they're erased anyway, and it brings us closer to Dotty).

Since we're now looking at a net effect of strictly removing code duplication (with minimal impact on the test suite), I believe we can let this in for RC1.

Please create a PR at scala/scala-dist that updates the spec, and squash the commits here, with a summary of the new spec in the commit message here.

Thank you!

**Comment by gzm0** [comment]
@adriaanm Squashed and updated commit message.

No formal modification to the specification was necessary (so the old behavior was actually against the spec).

Nevertheless, I added a clarification for object definitions in the specification (see PR scala/scala-dist#127).

**Comment by dragos** [comment]
I have to agree with Mirco here. This will remove a bunch of errors that you'd get in the presentation compiler, and defer them to a full build (the presentation compiler doesn't run refchecks, since its too slow).
- errors now are reported on the object, instead of the abstract member
- it's removing very little code, at the expense of a very important usability feature (the more errors you get _before_ building, the more time one saves).
- could plugins create abstract symbols, instead of trees? (at least, that's the path taken by many synthetic methods). This code seems to report errors on trees.
- it's very late in the 2.11 release cycle, and this might have unforeseen consequences (beside the ones discussed here).

**Comment by adriaanm** [comment]
Thanks for reminding us of the [dealbreaker](https://github.com/scala/scala/pull/3375#issuecomment-33143785). I agree this regression is too much to impose on all IDE users. Let's revisit once the IDE is able to run refchecks.

Sorry, but in the mean time, scala.js stubs will have to remain a little stubby (or use the suggested workaround of using traits) -- it's not like you read/write them all the time, anyway.

**Comment by sjrd** [comment]
I understand the reluctance to change anything in RC mode. So this will be my last attempt at changing your mind, and I do so only because I disagree with three of @dragos's comments:

> This will remove **a bunch of errors** that you'd get in the presentation compiler

Hardly a bunch! How many times do you forget the body of a method in an object, _compared to_ the number of times you do so for _concrete classes_, and most importantly for _inherited members_? For me it's like never, in comparison. I suspect it's the same for most people. But the other two classes of errors are already in refchecks.

> at the expense of a very important usability feature

This is a value judgment. I, for one, happen to _like_ these errors to display only when building, and even so only after other errors have disappeared. This way I can declare new methods I'll need, without a body (not even `= ???`), and use them elsewhere. Only when I have implemented the code using the method, and fixed all my type errors, then the compiler reminds me I haven't implemented certain methods yet. (If I wrote `= ???`, I would get my errors later, only as exceptions at runtime.)

> could plugins create abstract symbols, instead of trees? (at least, that's the path taken by many synthetic methods). This code seems to report errors on trees.

I have not the slightest idea where that comes from? You must have missed something somewhere. No plugin is creating anything here. The said declarations are written by the developer, not synthesized by any plugin. (The plugin we're talking about would synthesize the dummy body of these "abstract" declarations, not the declarations themselves, hence definitely not symbols.)

**Comment by dragos** [comment]
@sjrd, let me explain a bit more what I meant:
- moving this check later by one phase means that if people have a type-error (reported by typer) won't see these errors anymore (since refchecks won't run). I am convinced that any error that we delay is a usability regression. IDEs save a lot of time by reducing the number of time you need to do a full build.
- the new error loses precision (shows the object, instead of the abstract method)

> I have not the slightest idea where that comes from? You must have missed something somewhere.

It's the second point in the pull request description. What have I missed?

**Comment by dragos** [comment]
Oh, after reading the linked PR I understand what the compiler plugins use-case is.

**Comment by sjrd** [comment]
> It's the second point in your pull request description. What have I missed?

Oh OK it was a bit imprecise, I guess. What it meant is generating the dummy body `= ???`, not generating the declaration of the method. The declaration of the method is written by the developer in source code. Hence the symbols and trees for the declaration already exist.

Anyway, let us leave it at that for now, and as Adriaan said, revisit this when the IDE is able to run refchecks.

**Pull request closed without merging**
