### PR TITLE
Merge 2.12.x to 2.13.x [ci: last-only]

### PR DESCRIPTION
**Pull request by retronym**
The new support Scaladoc tables required some careful merging to replace use
of XML literals with the HTML DSL, which itself needed to be extended to support
`<table>`, etc.

The performance backport PR contained a bug fix to implicit that I merged forward.

I've heeded a TODO comment in the `Scope.filter` performance improvement, now that
we're on 2.13.x in which `List.filter` conserves when possible.

```
$ git fetch origin; git co -b merge/2.12.x-to-2.13.x-20180919 origin/2.13.x
Branch 'merge/2.12.x-to-2.13.x-20180919' set up to track remote branch '2.13.x' from 'origin'.
Switched to a new branch 'merge/2.12.x-to-2.13.x-20180919'
/code/scala on merge/2.12.x-to-2.13.x-20180919*
$ export PS1="
→ % "

% export MB=$(git merge-base origin/2.13.x origin/2.12.x)

% git log --oneline $MB..origin/2.12.x --graph --decorate | tail -r
* da62022a02 (origin/pr/7144) updates documentation of PriotityQueue
* df427e1d9f Merge pull request #7144 from martijnhoekstra/SI-11079
| * fa7ba07005 (origin/pr/6928, adriaanm/nonsense_eq_refine, pr/6928) Non-sensical comparison check checks erased type
|\
*   fdb100062d Merge pull request #6928 from adriaanm/nonsense_eq_refine
|/
| * 8bfc74557d (origin/pr/7177, adriaanm/opt-6928) Optimize non-sensical comparison check
|/|
| |/
|\ \
* |   892425711d Merge pull request #7177 from adriaanm/opt-6928
|  /
| * | 7d17726ffa (origin/pr/7073, hrhino/kill/uninitializederror) prepare to remove UninitializedError
|\ \
* |   62b4e35232 Merge pull request #7073 from hrhino/kill/uninitializederror
|  /
| * | 80f165a631 (origin/pr/6556) Replace UnApply to Apply in resetLocalAttris
|\ \
* |   37e39f5a36 Merge pull request #6556 from Atry/backport-unapply
|  /
| * | 73da4fc10d (origin/pr/7067, milessabin/topic/implicit-poly-prune-2.12.x) Prune polymorphic implicits more aggressively
|\ \
* |   1155e2dfae Merge pull request #7067 from milessabin/topic/implicit-poly-prune-2.12.x
|  /
| * | b83a6479c2 Check unused function params
| * | c1d7de48d9 (origin/pr/6518) No warn underscore in anon funs
|\ \
* |   04113f7690 Merge pull request #6518 from som-snytt/issue/10287
|  /
| * | e2f7ddc586 fix for equality of WrappedArray.ofRef
| * | 2537c32bc9 remove the always true canEqual
| * | 562a806349 (origin/pr/7156) remove the equals method, revert ofRef part of #5551
|\ \
* |   4ad99a18a8 Merge pull request #7156 from sadhen/fix_wrapped_array
|/ /
| * | f9f2a119f6 (origin/pr/7189) update "Scala Language Specification" URL
|\ \
* |   1c56139758 Merge pull request #7189 from xuwei-k/spec-url
|  /
| * | 79b7f2a564 (origin/pr/7089) Backport #6733 to 2.12.x
|\ \
* |   8e4a40a688 Merge pull request #7089 from ElfoLiNk/cherry-pick-6733
|/ /
| * | 5a72d7b791 (origin/pr/6043) Support GitHub Flavored Markdown version of tables in Scaladoc.
|/| |
| |/ /
|\ \ \
* | |   a3542af792 Merge pull request #6043 from janekdb/topic/2.12/scaladoc-tables
| |/|
| | |/
| * | | 17346b967f (retronym/topic/scope-filter-simple, origin/pr/7216, topic/scope-filter-simple) Avoid double evalution of predicate in Scope.filter
|\ \ \
* | |   25d596e52a Merge pull request #7216 from retronym/topic/scope-filter-simple
|  / /
| * | | 17fb78c1bf Optimize IndexedSeqOptimized.toList
| * | | 2062b3e63c Use AnyRefMap in hot parts of the compiler.
| * | | 833cf7ef13 Optimize nested class collection
| * | | 8398ca5c23 Optimize generic sig parser
| * | | 39a567b8de (retronym/perf-backport/6209-assorted-compiler-optimizations, perf-backport/6209-assorted-compiler-optimizations) Avoid nonEmpty in hot paths
| |  / /
| | * | | 3485981bdd Simplify specialization transformer
| | * | | 4381845a13 Tree convervation in specialization
| | * | | fb66b4f4c7 Optimize bookkeeping in specialization transform
| | * | | 88f4b37b77 (retronym/perf-backport/6214-optimizations-in-the-specialization-phase, perf-backport/6214-optimizations-in-the-specialization-phase) Avoid wasteful loading of unreferenced, high arity function and tuple classes
| |\ \ \
| * | |   6c0b70a81e Merge branch 'perf-backport/6214-optimizations-in-the-specialization-phase' into perf-backport/omnibus
| |  / /
| | * | | a24d7c0a21 (retronym/perf-backport/6234-reduce-overhead-of-ystatistics, perf-backport/6234-reduce-overhead-of-ystatistics) Reduce overhead of enabling -Ystatistics
| |\ \ \
| * | |   a4fee32dd2 Merge branch 'perf-backport/6234-reduce-overhead-of-ystatistics' into perf-backport/omnibus
| |  / /
| | * | | 19abe85e1a (retronym/perf-backport/6291-avoid-allocation-of-classtags-in-hot-code, perf-backport/6291-avoid-allocation-of-classtags-in-hot-code) Avoid allocation of ClassTags in hot code
| |\ \ \
| * | |   1561e1399a Merge branch 'perf-backport/6291-avoid-allocation-of-classtags-in-hot-code' into perf-backport/omnibus
| |  / /
| | * | | b10e25529d (retronym/perf-backport/6292-array-instantiation, perf-backport/6292-array-instantiation) Refactor typechecking of array instantiation for performance
| |\ \ \
| * | |   cc939a52d0 Merge branch 'perf-backport/6292-array-instantiation' into perf-backport/omnibus
| |  / /
| | * | | bcafc8ff4b (retronym/perf-backport/6297-imports-context-lookup, perf-backport/6297-imports-context-lookup) Avoid creation of temporary Lists of imports during Context.lookup
| |\ \ \
| * | |   15f13f1c9e Merge branch 'perf-backport/6297-imports-context-lookup' into perf-backport/omnibus
| |  / /
| | * | | 9d2500072c (retronym/perf-backport/6524-implicit-prune-bounds, perf-backport/6524-implicit-prune-bounds) Rule out more implicit based on bounds of type parameters
| |\ \ \
| * | |   940e3c2567 Merge branch 'perf-backport/6524-implicit-prune-bounds' into perf-backport/omnibus
| |  / /
| | * | | aa72ad50b3 Optimize isStable
| | * | | 18bc693f67 Optimize isStable by using normalize, which is cached
| | * | | 1ed41e6ad4 Avoid eager error buffer creation
| | * | | 10e3a47c6a (retronym/perf-backport/6597-front-end, perf-backport/6597-front-end) Avoid an array copy in the parser
| |\ \ \
| * | |   c9f04d0237 Merge branch 'perf-backport/6597-front-end' into perf-backport/omnibus
| |  / /
| | * | | 9d4aa224e7 Reduce allocation in patmat updateSubstitution
| | * | | 9785e1fc01 Reduce allocation patmat Logic.simplify
| | * | | cbf7813630 Optimize patmat substitution
| | * | | 8106106b26 Optimize patmat substitution
| | * | | 439264b928 Reduce allocation further in TypedSubstitution.<<
| | * | | da315ab118 (retronym/perf-backport/6599-allocation-patmat, perf-backport/6599-allocation-patmat) Specialize hasImpureAtom for common cases of small collections
| |\ \ \
| * | |   be571b66a2 Merge branch 'perf-backport/6599-allocation-patmat' into perf-backport/omnibus
| |  / /
| | * | | a4353563de (retronym/perf-backport/6604-classtag-unapply-newarray, perf-backport/6604-classtag-unapply-newarray) Enhance performance of unapply method of ClassTag
| |\ \ \
| * | |   3ac6c1e422 Merge branch 'perf-backport/6604-classtag-unapply-newarray' into perf-backport/omnibus
| |  / /
| | * | | 64899084df Solve Issue 492, "MethodTypes.isTrivial is allocation heavy"
| | * | | a17e79a72c Move fields into local variables.
| | * | | 93deeccb93 (retronym/perf-backport/6605-methodtype-istrivial, perf-backport/6605-methodtype-istrivial) Minor style changes and remove dead code
| |\ \ \
| * | |   f0c2db828c Merge branch 'perf-backport/6605-methodtype-istrivial' into perf-backport/omnibus
| |  / /
| | * | | f070e6ec0d Avoid needless LUB of the cases after patmat translation
| | |/ / /
| |\ \ \ \
| * | | |   ec4846288e Merge branch 'perf-backport/6607-needles-lub-match' into perf-backport/omnibus
| |  / / /
| | * | | | d0265db8d0 (retronym/perf-backport/6612-faster-implicit-search-lazy-msg, perf-backport/6612-faster-implicit-search-lazy-msg) Faster implicit search: lazier error messages
| |\ \ \ \
| * | | |   4ad2edc4a4 Merge branch 'perf-backport/6612-faster-implicit-search-lazy-msg' into perf-backport/omnibus
| |  / / /
| | * | | | 28686fbde4 (retronym/perf-backport/6615-efficiency-scope-lookup, perf-backport/6615-efficiency-scope-lookup) Reduce allocations in Context.lookup
| |\ \ \ \
| * | | |   798a04e84c Merge branch 'perf-backport/6615-efficiency-scope-lookup' into perf-backport/omnibus
| |  / / /
| | * | | | 293529f9c5 (retronym/perf-backport/6616-allocation-typing-transformer, perf-backport/6616-allocation-typing-transformer) Avoid allocation of Typer within typing transformers
| |\ \ \ \
| * | | |   f6c5093547 Merge branch 'perf-backport/6616-allocation-typing-transformer' into perf-backport/omnibus
| |  / / /
| | * | | | 437a1e9d0a (retronym/perf-backport/6617-dead-code, perf-backport/6617-dead-code) Improve efficiency of dead code checks
| |\ \ \ \
| * | | |   0e579bc13e Merge branch 'perf-backport/6617-dead-code' into perf-backport/omnibus
| |  / / /
| | * | | | 8cdcc2ed77 Remove the checkNoEscaping field from Typer
| | * | | | fa39e5a433 Expunge the transformed field from Typer
| | * | | | 00d72cca97 Remove the dyna field from Typer
| | * | | | 762c5acb17 Jettison runDefinitions field from Typer
| | * | | | 55a3654cae Run another runDefinitions field out of town
| | * | | | 71fbb6c67e Begone, toOrigin, approximateAbstracts, and AdjustedTypeArgs!
| | * | | | e09adccbc9 Send Typer.checkUnused to the glue factory
| | * | | | 21e459a177 One context field ought to be enough for Typer, don't you think?
| | * | | | 5df601ed57 Use faster way to lookup List.apply symbol
| | * | | | 1181fdd24b (retronym/perf-backport/6618-reduce-bulk-typer-inferencer, perf-backport/6618-reduce-bulk-typer-inferencer) Avoid double open when overwriting a classfile on non-Windows
| |\ \ \ \
| * | | |   1e8480cacf Merge branch 'perf-backport/6618-reduce-bulk-typer-inferencer' into perf-backport/omnibus
| |  / / /
| | * | | | 43350253e1 (retronym/perf-backport/6622-command-line-parser, perf-backport/6622-command-line-parser) CommandLineParser improvements
| |\ \ \ \
| * | | |   c5eb150b18 Merge branch 'perf-backport/6622-command-line-parser' into perf-backport/omnibus
| |  / / /
| | * | | | 1d366a8157 (retronym/perf-backport/6631-footprint-context, perf-backport/6631-footprint-context) Rework named/defaults bookkeeping as a tree attachment
| |\ \ \ \
| * | | |   81d6b754e5 Merge branch 'perf-backport/6631-footprint-context' into perf-backport/omnibus
| |  / / /
| | * | | | 606d7d126f (retronym/perf-backport/6664-list-apply-rundefinitions, perf-backport/6664-list-apply-rundefinitions) Cherry-picked into a different branch
| |\ \ \ \
| * | | |   e59db3921e Merge branch 'perf-backport/6664-list-apply-rundefinitions' into perf-backport/omnibus
| * | | | f3c70d9376 (origin/pr/6780) [nomerge] Remove test that doesn't apply on 2.12.x
| | * | | c02308d10f Add a test to show a problem in switch pattern translation
| | * | | a8de631d7d (retronym/perf-backport/6607-needles-lub-match, perf-backport/6607-needles-lub-match) Fix regression in switch pattern translation
| |\ \ \
| * | |   4a55ac81b1 Merge branch 'perf-backport/6607-needles-lub-match' into perf-backport/omnibus
| |  / /
| | * | | 3065bf6b83 (retronym/perf-backport/6967-needless-storage-scope, perf-backport/6967-needless-storage-scope) Avoid needless storage/lookup for constants in Scope
| |\ \ \
| * | |   00673bbf8f Merge branch 'perf-backport/6967-needless-storage-scope' into perf-backport/omnibus
| |  / /
| | * | | d8fc860613 Speedup some symbol lookups in Definitions
| | * | | fe7d11567b (retronym/perf-backport/6990-microopts-definitions, perf-backport/6990-microopts-definitions) Avoid some virtual call overhead to get to Symbol.equals
| |\ \ \
| * | |   b18f1ac81c Merge branch 'perf-backport/6990-microopts-definitions' into perf-backport/omnibus
| |  / /
| | * | | 3554a09b15 (retronym/perf-backport/7096-optimize-method-type-result, perf-backport/7096-optimize-method-type-result) Optimize MethodType.resultType
| |\ \ \
| * | |   799ab6c071 Merge branch 'perf-backport/7096-optimize-method-type-result' into perf-backport/omnibus
| |  / /
| | * | | 25be835eeb (retronym/perf-backport/7097-case-field-accessors, perf-backport/7097-case-field-accessors) Optimize caseFieldAccessors to avoid temporary object creation
| |\ \ \
| * | |   1a09b1574d Merge branch 'perf-backport/7097-case-field-accessors' into perf-backport/omnibus
| |  / /
| | * | | a2ffb7e113 (retronym/perf-backport/7098-constant-equals-hash, perf-backport/7098-constant-equals-hash) Optimize Constant.{equals,hashCode}
| |\ \ \
| * | |   492201babf Merge branch 'perf-backport/7098-constant-equals-hash' into perf-backport/omnibus
| |  / /
| | * | | fc47c26d64 (retronym/perf-backport/7102-erased-types, perf-backport/7102-erased-types) Avoid a virtual call for Phase.erasedTypes
| |\ \ \
| * | |   ad9820d4ff Merge branch 'perf-backport/7102-erased-types' into perf-backport/omnibus
| |  / /
| | * | | 4b680b398a (retronym/perf-backport/7103-shadower-outer, perf-backport/7103-shadower-outer) Move Shadower to outer level
| |\ \ \
| * | |   346b7ea6a8 Merge branch 'perf-backport/7103-shadower-outer' into perf-backport/omnibus
| |  / /
| | * | | 63bf292f21 (retronym/perf-backport/seq-unapply, perf-backport/seq-unapply) Avoid SeqFactory.unapplySeq in hot pattern matches.
| |\ \ \
| * | |   2cd6133323 Merge branch 'perf-backport/seq-unapply' into perf-backport/omnibus
| |  / /
| | * | | 94be00349d (retronym/perf-backport/7105-remove-indirection-typer, perf-backport/7105-remove-indirection-typer) Remove some indirections in Global and Typer
| |\ \ \
| * | |   b248c1d654 Merge branch 'perf-backport/7105-remove-indirection-typer' into perf-backport/omnibus
| |  / /
| | * | | 2ff34ca96b (retronym/perf-backport/7107-imports-implicits, perf-backport/7107-imports-implicits) Avoid expensive call to `imports` in implicit search
| |\ \ \
| * | |   a857be2e12 Merge branch 'perf-backport/7107-imports-implicits' into perf-backport/omnibus
| |  / /
| | * | | 100602f039 Use eq in lookupEntry
| | * | | 51ac7dc53b Make Name.start final
| | * | | adbb8308df Avoid List.equals in hot path
| | * | | e0edb2a8a3 Avoid double call to `dealias`
| | * | | 749ee88e75 Avoid repeated calls to Symbol.info
| | * | | 4bc8aa4340 (retronym/perf-backport/7109-pocketful-microopts, perf-backport/7109-pocketful-microopts) Remove hot assertion
| |\ \ \
| * | |   e46c4ba144 Merge branch 'perf-backport/7109-pocketful-microopts' into perf-backport/omnibus
| * | | e164092a73 Address binary incompatibilities
| * | | 03feb56902 Merge remote-tracking branch 'origin/2.12.x' into perf-backport/omnibus-first-pr
| * | | 6ea993a090 [mergeforward] Avoid leaking constraints between typechecking implicit candidates
| | |/ /
| | * | | 720b8a6efb Avoid temporary strings during classpath lookup
| | * | | 178c8b4ec5 (retronym/perf-backport/7128-temp-string-classpath, perf-backport/7128-temp-string-classpath) Use dotted keys in dirs map in other use sites of getDir
| |\ \ \
| * | |   6be348ac8d Merge branch 'perf-backport/7128-temp-string-classpath' into perf-backport/omnibus-first-pr
| | |/ /
| | * | | 30f599f606 (retronym/perf-backport/7149-cold-stats, perf-backport/7149-cold-stats) Optimize check for enabled statistics by specializing machinery to boolean flags
| |\ \ \
| * | |   87bcc75005 Merge branch 'perf-backport/7149-cold-stats' into perf-backport/omnibus-first-pr
| | * | 089ed4b5bc (retronym/perf-backport/7143-type-ref-equals, perf-backport/7143-type-ref-equals) Optimize TypeRef.equals with fast paths for eq elements
| |\ \
| * |   0e901ba834 Merge branch 'perf-backport/7143-type-ref-equals' into perf-backport/omnibus-first-pr
| * | 5d34c2dfab Address binary incompatibility
| * | 0a8e00cb18 [mergeforward] Make nested implicit type error suppression unconditional
| |\
| *   da58d8e4f1 Merge remote-tracking branch 'origin/2.12.x' into perf-backport/omnibus-first-pr
| * e387cafeca Revert change that is binary incompatible with the 2.12.6 build of macro paradise
| * 036143bad4 (retronym/perf-backport/omnibus-first-pr, origin/pr/7147, perf-backport/omnibus-first-pr) Make some methods protected that are used by scalameta's Typer subclass
|\
*   f2129b9690 (origin/2.12.x, 2.12.x) Merge pull request #7147 from retronym/perf-backport/omnibus-first-pr

% git merge 62b4e35232
% git merge -s ours 1155e2dfae
% git merge -s ours 04113f7690
% git merge 4ad99a18a8
% git merge -sours 1c56139758
% git merge -sours 8e4a40a688
% git merge a3542af792
% git merge 25d596e52a
% git commit -m "Heed TODO in Scope.filter"
% git merge -sours f2129b9690
% # Manually cherrypick changes from 6ea993a090 + 0a8e00cb18
% git commit -a --amend
```

### CODE REVIEW

**Comment by retronym** [comment]
@janekdb Would you mind trying out this branch to see if the Scaladoc table output is still working as expected?

Here's the [result](https://drive.google.com/open?id=1EwgnCzJiFeUlSn_WzRNiKET0mnz_0kAz) of running `./build/quick/bin/scaladoc -d /tmp/ /Users/jz/code/scala/test/scaladoc/resources/tables.scala`

**Comment by retronym** [comment]
[Running](https://scala-ci.typesafe.com/job/scala-2.12.x-validate-main/1137/console) pr-validate-main manually, @scabot doesn't deal with PRs with too many commits.

**Comment by janekdb** [comment]
@retronym Checked out and created the Scaladoc locally. Visually all examples are good and as expected,

image

I checked the HTML source for one of the tables. No problem! LGTM.

**Comment by adriaanm** [comment]
Let's merge this before we run into a conflict.

**Pull request merged**
