### PR TITLE
Fix optimizer bugs and enable -Yopt:l:classpath when building scala

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
review by @adriaanm

**Comment by lrytz** [comment]
https://issues.scala-lang.org/browse/SI-9364 keeps track of tests that are forced to GenASM and have to be ported to GenBCode (and the new optimzier).

**Comment by lrytz** [comment]
@adriaanm `validate-test` times out (150 minutes) with `-Yopt:l:classpath` enabled

**Comment by adriaanm** [comment]
:fireworks:

**Comment by adriaanm** [comment]
Was it heap or time?

**Comment by lrytz** [comment]
Neither..

I did `test/partest --run` with and without the new optimizer on my laptop for 6 minutes each. In each case it finished 160 tests, and the yourkit profile looks very similar: 162 vs 168 mb of allocated memory.

Then I noted that the last commit of this PR (which also has the new optimizer enabled, check the log) tested in 90 minutes https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/154/console

So I just did a `rebuild`. The two builds took 116 and 126 minutes (they were running at the same time on the same machine), so that is just like before: https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/buildTimeTrend

 Maybe it's not only my mac that's slowing down due to heat, but also amazon's datacenter :-)

**Comment by adriaanm** [comment]
:-) maybe we should reduce how many concurrent jobs we run?

**Comment by lrytz** [comment]
i think 2 would be a good number

**Comment by som-snytt** [comment]
Is the L in `-Yopt:l` for Lukas? b/c what glyph is that? It would be more obvious if `-Yopt:l:rytz` were an option.

**Comment by retronym** [comment]
LGTM

**Comment by adriaanm** [comment]
Yes indeed!

**Pull request merged**
