### PR TITLE
remove NumericRangeIterator

### LINKED ISSUE #11152: '(BigDecimal(1) to BigDecimal(s"1.${"0" * 32}1") by BigDecimal(s"0.${"0" * 33}1")).toList' cause infinite loop in Scala 2.13.0-M5
I think there are two reasons.

1. [Use MathContext in BigDecimal operations](https://github.com/scala/scala/commit/ace11c068b7a0ec67b70e67da465da23277e1287)
2. [NumericRange.NumericRangeIterator](https://github.com/scala/scala/blob/465aea6695c320ea6388c2856d439b4b2521ff5d/src/library/scala/collection/immutable/NumericRange.scala#L374)

not infinite loop when `toArray` because `toArray` does not use `NumericRange#iterator`.

```
Welcome to Scala 2.13.0-M5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> (BigDecimal(1) to BigDecimal(s"1.${"0" * 32}1") by BigDecimal(s"0.${"0" * 33}1")).toArray
res0: Array[scala.math.BigDecimal] = Array(1, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000, 1.000000000000000000000000000000000)
```

`toArray` result different from Scala 2.12.x due to [MathContext changes](https://github.com/scala/scala/commit/ace11c068b7a0ec67b70e67da465da23277e1287)

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> (BigDecimal(1) to BigDecimal(s"1.${"0" * 32}1") by BigDecimal(s"0.${"0" * 33}1")).toArray
res0: Array[scala.math.BigDecimal] = Array(1.0000000000000000000000000000000000, 1.0000000000000000000000000000000001, 1.0000000000000000000000000000000002, 1.0000000000000000000000000000000003, 1.0000000000000000000000000000000004, 1.0000000000000000000000000000000005, 1.0000000000000000000000000000000006, 1.0000000000000000000000000000000007, 1.0000000000000000000000000000000008, 1.0000000000000000000000000000000009, 1.0000000000000000000000000000000010)
```

`BigDecimal#+` difference Scala 2.12 <=> 2.13

```
scala> new java.math.BigDecimal(1).add(new java.math.BigDecimal(s"0.${"0" * 33}1")) // Scala 2.12.x BigDecimal#+
res0: java.math.BigDecimal = 1.0000000000000000000000000000000001

scala> res0 compareTo (new java.math.BigDecimal(1))
res1: Int = 1

scala> new java.math.BigDecimal(1).add(new java.math.BigDecimal(s"0.${"0" * 33}1"), java.math.MathContext.DECIMAL128)  // Scala 2.13.x BigDecimal#+
res2: java.math.BigDecimal = 1.000000000000000000000000000000000

scala> res2 compareTo (new java.math.BigDecimal(1)) // this cause infinite loop in NumericRangeIterator
res3: Int = 0
```

- `DECIMAL128` is default MathContext in `scala.BigDecimal` https://github.com/scala/scala/blob/v2.12.6/src/library/scala/math/BigDecimal.scala#L30
- `scala.BigDecimal#equals` use `java.math.BigDecimal#compareTo` not `java.math.BigDecimal#equals` 
  - https://github.com/scala/scala/blob/v2.12.6/src/library/scala/math/BigDecimal.scala#L534
  - https://github.com/scala/scala/blob/v2.12.6/src/library/scala/math/BigDecimal.scala#L445

### PR DESCRIPTION
**Pull request by xuwei-k**
fix https://github.com/scala/bug/issues/11152

### CODE REVIEW

**Comment by szeiger** [comment]
I'm pretty sure this is the wrong way to (try to) fix the problem but I'm not sure what they right way would be. The non-terminating `NumericRangeIterator` is a result of the underlying problem, not the cause. The `NumericRange` itself is still just as broken and produces incorrect results:

```
scala> (BigDecimal(1) to BigDecimal(s"1.${"0" * 32}1") by BigDecimal(s"0.${"0" * 33}1"))
res0: scala.collection.immutable.NumericRange.Inclusive[scala.math.BigDecimal] = NumericRange 1 to 1.000000000000000000000000000000001 by 1E-34

scala> res0(0)
res1: scala.math.BigDecimal = 1.000000000000000000000000000000000

scala> res0(1)
res2: scala.math.BigDecimal = 1.000000000000000000000000000000000

scala> res0(2)
res3: scala.math.BigDecimal = 1.000000000000000000000000000000000
```

The only reasonable fix I can think of is to extend the precision as necessary instead of holding on to a specific `MathContext`, i.e. do what Java's `BigDecimal` does by default. Since `NumericRange` has no control over the operator semantics (nor should it) the change has to go into `BigDecimal`, which means reverting https://github.com/scala/scala/pull/6884. Is there a reason why some operators originally propagated the `MathContext` but others did not? I don't know. Is propagating the `MathContext` a good idea at all? Maybe Java got it right in the first place.

**Comment by Ichoran** [comment]
`BigDecimal` should be able to handle the math, if the precision is set properly to begin with.  If `BigDecimal` propagates the correct MathContext, everything should be fine.  The trick is just to set the precision based on the string input, which should happen on _all_ creations of `BigDecimal`, most likely.

**Comment by szeiger** [comment]
@Ichoran That doesn't work. The precision is set correctly based on the string input but ever since https://github.com/scala/scala/pull/6884 all `BigDecimal` operations use the `MathContext` from the LHS, i.e. the start value of the range. If the step size is much smaller then the start value the start value's precision won't be sufficient. To ensure a correct result you need to extend the precision to cover both operands (which was the original behavior before https://github.com/scala/scala/pull/6884).

We could switch the operands to reduce the scope of this problem (based on the assumption that the start value will not usually need more precision than the step) but it will still be incorrect in some cases.

**Comment by SethTisue** [comment]
marking as WIP but leaving open since there are plausible paths forward but it's not mergeable as-is

**Comment by szeiger** [comment]
I took a look at the history of `BigDecimal`. Not propagating the math context for some operations was not an oversight but a deliberate change introduced in https://github.com/scala/scala/commit/3a1332c451c8bd9b987ab3dbe775ef5a08360705 to avoid a similar problem. I'll open a PR to revert #6884.

**Comment by szeiger** [comment]
Closing in favor of https://github.com/scala/scala/pull/7516

**Pull request closed without merging**
