### PR TITLE
SI-4989 Reject super.x if an intermediate class declares x abstract.

### PR DESCRIPTION
**Pull request by retronym**
This is in line with Java's treatment. Without this, an AbstractMethodError
is thrown at runtime.

Review by @hubertp

Discussion: https://groups.google.com/d/topic/scala-internals/1D9HEe-CIe0/discussion

Resubmission of #732 that excludes traits from the check.

### CODE REVIEW

**Comment by retronym** [comment]
Point for review (from the ML): does this restriction need to be specced?

**Comment by adriaanm** [comment]
I'd also like to get a LGTM from @odersky on this one

**Comment by odersky** [comment]
You got it. LGTM

**Comment by hubertp** [comment]
Indeed, looks good (sorry for the late review).

**Pull request merged**
