### PR TITLE
Added make not private logic for @inline accesses back to ExplicitOuter.

### PR DESCRIPTION
**Pull request by odersky**
As discussed in https://mail.google.com/mail/u/0/?hl=en&tab=Tm#search/inlining+changes+needed/1390c955960d7cb5, we need to move access widenings back to ExplicitOuter, so that outer fields are correctly widened. The previous logiv in SuperAccessors can go once the inliner is adapted to the new scheme. I leave SuperAccessors for the moment as is, in order not to slide back even further with inlining. Review by @magarciaEPFL, @gkossakowski

### CODE REVIEW

**Comment by odersky** [comment]
@magarciaEPFL: I convinced myself otherwise. The only difference is if we have an @inline method that has a nested
class 

```
@inline def foo() {
     class Bar extends Baz {
         private var x
         def foo = x
     }
     new Bar(): Baz
 }
```

But in that case the whole discussion is moot anyway because the class does not escape the method. So we can live with the standard @enclMethod code and do not need a new concept.

Unless there are other comments I'd vote on merging this now.

**Comment by VladUreche** [comment]
LTGM, but let's wait for Miguel to answer

**Comment by magarciaEPFL** [comment]
LGTM

**Comment by gkossakowski** [comment]
It's post merge but I'd love to see our (non-trivial) discussion on internals to be turned into a test-case. I'm not sure if I understand how to trigger problematic behaviour that was discussed but if somebody gives me an example I'm happy to turn into test.

**Comment by retronym** [comment]
This seems to have triggered this regression: [SI-6562](https://issues.scala-lang.org/browse/SI-6562)

And a non-GMail link to the discussion: https://groups.google.com/d/msg/scala-internals/iPkMCygzws4/LZHydgSjFSUJ

**Pull request merged**
