### PR TITLE
SI-6387 Copy overriding accessor when expanding its name

### PR DESCRIPTION
**Pull request by vigdorchik**
When the compiler wants to make certain symbol accessible, it elevates the symbol 
with otherwise private visibility and expands its name to append the full name of 
containing class to avoid clashes.

In the rare cases when the accessor overrides the member in base class, such 
expanding either results in AbstractMethodError when the base method is abstract, or, 
even worse, can change the semantics of the program.

To avoid such issues, we clone the accessor symbol, clear its ACCESSOR flag and enter the symbol with an unchanged name.

This change only adds lost overridden methods, so the PR targets 2.10.x

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @paulp

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
I did some modest reworking of this and resubmitted it as #2288.

**Comment by paulp** [comment]
Provisionally closing this in favor of #2288 to reduce the open PR count.

**Pull request closed without merging**
