### PR TITLE
remove some redundant calls to Symbol.sourceFile

### PR DESCRIPTION
**Pull request by mkeskells**
SymbolSourceFile can walk a tree if not root so can be expensive

### CODE REVIEW

**Comment by mkeskells** [comment]
performance figures based on 50 cycles,full compile
about 1.5 % but the noise is +/- 5% so not sure the figures are relyable as the 
**Update** looks ok now confirmed by @rorygraves 

```
after 10 90%

                  RunName	                AllWallMS	                   CPU_MS	                Allocated
       00_quick-baseline2	 996	 9,190.43 [-5.88% +5.48%]	 8,990.02 [-5.45% +4.63%]	 1,990.43 [-0.07% +0.07%]
     00_quick-sourceFile2	 996	 9,057.83 [-5.02% +3.63%]	 8,906.68 [-4.39% +3.33%]	 1,996.18 [-0.07% +0.06%]
```

**Comment by rorygraves** [comment]
On linux I measured this at ~2%
```
after 40 90%
                  RunName	                AllWallMS	                   CPU_MS	                Allocated
              00_baseline	3888	 5,188.69 [-2.46% +2.93%]	 5,154.17 [-2.73% +3.17%]	 1,899.37 [-0.09% +0.19%]
                01_caches	3888	 5,082.04 [-2.46% +2.82%]	 5,044.29 [-2.99% +3.10%]	 1,920.09 [-0.13% +0.09%]
```

**Comment by mkeskells** [comment]
2% on Linux is about the same as 1.5% on Windows due to the distortion by windows file writing in GenBCode

**Review by retronym — APPROVED** [review]

**Comment by retronym** [comment]
Benchmark running, will contribute points to each of these [charts](https://scala-ci.typesafe.com/grafana/dashboard/db/pr-validation?var-scalaSha=054e71765b%7C240f6c1173%7Cf2a1519438%7Cc6f7a1db21%7Cecb62c552f%7C7e259c28d3%7C5ca72a38ac%7Cf94a98a979%7Cdca3b06a88%7C4d86bf068c%7C6282dd4&var-source=All&var-bench=HotScalacBenchmark.compile&var-host=scalabench%40scalabench%40&from=1497826167577&to=1513637367577) in about an hour.

**Comment by retronym** [comment]
I see no discernable improvement our hot compilation benchmarks. I wonder why what's different: something about your choice of code base to compile (akka) vs the once we're using, or something in the benchmarking methodology (warmup / forks etc). That's a meta problem we need to solve by unifying our tools (https://github.com/scala/compiler-benchmark/issues/43 is a step towards that)

I'll merge this in any case as the patch is not controversial at all.

**Pull request merged**
