### PR TITLE
Generate static forwarders for object members in companion interface

### PR DESCRIPTION
**Pull request by retronym**
We used to disable generation of static forwarders when a object had a
trait as a companion, as one could not add methods with bodies to an
interface in JVM 6.

The JVM lifted this restriction to support default methods in interfaces,
so we can lift the restriction on static forwarders, too.

I've only commited the test using the default backend (GenBCode), but
I've also made the change and manaully verified the test works under
the soon-to-be-removed GenASM.

```
% qscalac -Ybackend:GenASM test/files/run/trait-static-forwarder/forwarders.scala && javac -d . -classpath . test/files/run/trait-static-forwarder/Test.java && qscala Test
./T.class: warning: Cannot find annotation method 'bytes()' in type 'ScalaSignature': class file for scala.reflect.ScalaSignature not found
1 warning
42
```

Fixes https://github.com/scala/scala-dev/issues/59

Review by @lrytz

### CODE REVIEW

**Comment by retronym** [comment]
Thanks to @ktoso for the nudge in this direction.

**Comment by lrytz** [comment]
```
/home/jenkins/workspace/scala-2.12.x-validate-publish-core/build-ant-macros.xml:337: java.lang.ClassFormatError: Illegal field modifiers in class scala/collection/GenTraversable: 0x100A
```

Field!? The flags `0x100A` are `ACC_SYNTHETIC | ACC_PRIVATE | ACC_STATIC`

**Comment by ktoso** [comment]
That's really awesome!
Will make our lifes maintaining parallel Java DSL's much simpler – thanks a lot Jason!

**Comment by retronym** [comment]
The problem here is that the backend tries to add a static field `$deserializeLambdaCache$` to the interface, which is still a no-no. I believe that we would have run into the same problem shortly when we attempted to use default methods for trait bodies.

```
  // access flags 0x100A
  private static synthetic Ljava/util/Map; $deserializeLambdaCache$

  // access flags 0x100A
  private static synthetic $deserializeLambda$(Ljava/lang/invoke/SerializedLambda;)Ljava/lang/Object;
    GETSTATIC scala/collection/GenTraversable.$deserializeLambdaCache$ : Ljava/util/Map;
    ASTORE 1
    ALOAD 1
    IFNONNULL L0
    NEW java/util/HashMap
    DUP
    INVOKESPECIAL java/util/HashMap.<init> ()V
    ASTORE 1
    ALOAD 1
    PUTSTATIC scala/collection/GenTraversable.$deserializeLambdaCache$ : Ljava/util/Map;
   L0
   FRAME APPEND [java/util/Map]
    GETSTATIC scala/runtime/LambdaDeserializer$.MODULE$ : Lscala/runtime/LambdaDeserializer$;
    INVOKESTATIC java/lang/invoke/MethodHandles.lookup ()Ljava/lang/invoke/MethodHandles$Lookup;
    ALOAD 1
    ALOAD 0
    INVOKEVIRTUAL scala/runtime/LambdaDeserializer$.deserializeLambda (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/util/Map;Ljava/lang/invoke/SerializedLambda;)Ljava/lang/Object;
    ARETURN
    MAXSTACK = 4
    MAXLOCALS = 2
```

The cache is for the reflective lookup of the method handle to the implementation method. In Javac's approach, this is cached at the each indy callsite within the big `$deserializeLambda$` method.

I can disable the use of the cache in interfaces to unblock things, but this needs some thought.

**Comment by retronym** [comment]
Closing for now. I'm working on the problem of avoiding static fields in traits over in https://github.com/scala/scala/compare/scala:2.12.x...retronym:topic/indy-rather-than-statics

**Comment by ktoso** [comment]
Cool, thanks for the continued work!

**Pull request closed without merging**
