### PR TITLE
Fix checkinit build

### PR DESCRIPTION
**Pull request by lrytz**
There was only one real bug, SI-8570.

### CODE REVIEW

**Comment by lrytz** [comment]
review @retronym

**Comment by retronym** [comment]
The patch to mixin warrants a bit more explanation. Would be nice to document that bit of code.

I trace back the original differentiation of `Literal(_)` to 562647a37a6675fbf328f72e081a7f88913dd004.

**Comment by lrytz** [comment]
ok, i'm doing some more archeology, thanks for the pointer

**Comment by lrytz** [comment]
i refactored the area a bit and added some comments.

**Comment by retronym** [comment]
Sorry to be a pain, but would be possible to separate the refactoring and the bug fix into two commits?

**Comment by lrytz** [comment]
Sure, no problem!

**Comment by lrytz** [comment]
does that help?

**Comment by retronym** [comment]
Almost there.
- The test should be in the "fix" commit.
- All things being equal, I would prefer the refactoring commit to come first. Ideally it should turn the fix into a one liner.

**Comment by lrytz** [comment]
> The test should be in the "fix" commit.

OK, Sure

> All things being equal, I would prefer the refactoring commit to come first. Ideally it should turn the fix into a one liner.

I think that doesn't make much sense, it would amount to adding control flow to the correct version, just to introduce a bug..

**Comment by retronym** [comment]
Fair enough.

**Comment by lrytz** [comment]
added missing check file

**Comment by retronym** [comment]
LGTM

**Pull request merged**
