### PR TITLE
make the 2.12 spec available on scala-lang.org

### PR DESCRIPTION
**Pull request by SethTisue**
reference: https://github.com/scala/scala-lang/issues/479

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @adriaanm

**Comment by adriaanm** [comment]
Did you create the 2.12 dir separately? Or is rsync going to do it. Can never predict what it does.

**Comment by SethTisue** [comment]
I just finished making it manually, just in case.

**Comment by adriaanm** [comment]
LGTM -- since the test suite has nothing new to say about this PR, immamergeit

**Comment by adriaanm** [comment]
https://travis-ci.org/scala/scala/jobs/163871119 passed, files still propagating from staging to webserver? I forget the details of the epfl setup, but thought that was done by https://scala-webapps.epfl.ch/jenkins/view/All/job/production_scala-lang.org-scala-dist-archive-sync/

**Comment by adriaanm** [comment]
Ugh. I don't get why the files are not showing up :-(

**Comment by SethTisue** [comment]
perhaps https://github.com/scala/scala/pull/5438 will fix it

**Comment by som-snytt** [comment]
I see it! I think there is an issue where `$x` in examples breaks formatting. I intended to fix the end of chapter 2.

**Pull request merged**
