### PR TITLE
fix partest on Cygwin

### PR DESCRIPTION
**Pull request by SethTisue**
manually tested on jenkins-worker-windows-publish

review by @adriaanm, @som-snytt

### CODE REVIEW

**Comment by SethTisue** [comment]
in case anyone was wondering what the removed line in the shell script did, in my testing it unhelpfully rewrote this working classpath:

```
Y:\\tisue\\scala\\build\\pack\\lib\\scala-library.jar;Y:\\tisue\\scala\\build\\pack\\lib\\scala-reflect.jar;Y:\\tisue\\scala\\build\\pack\\lib\\scala-compiler.jar;Y:\\tisue\\scala\\build\\pack\\lib\\scalap.jar;Y:\\tisue\\scala\\build\\pack\\lib\\scala-actors.jar;C:\\.m2\\repository\\org\\scala-lang\\modules\\scala-partest_2.11\\1.0.7\\scala-partest_2.11-1.0.7.jar;C:\\.m2\\repository\\com\\googlecode\\java-diff-utils\\diffutils\\1.3.0\\diffutils-1.3.0.jar;C:\\.m2\\repository\\org\\scala-sbt\\test-interface\\1.0\\test-interface-1.0.jar;C:\\.m2\\repository\\org\\scala-lang\\modules\\scala-xml_2.11\\1.0.4\\scala-xml_2.11-1.0.4.jar;C:\\.m2\\repository\\org\\scala-lang\\modules\\scala-parser-combinators_2.11\\1.0.4\\scala-parser-combinators_2.11-1.0.4.jar;C:\\.m2\\repository\\org\\scalacheck\\scalacheck_2.11\\1.11.6\\scalacheck_2.11-1.11.6.jar;Y:\\tisue\\scala\\build\\pack\\lib\\scala-partest-extras.jar;Y:\\tisue\\scala\\build\\pack\\lib\\scala-partest-javaagent.jar;Y:\\tisue\\scala\\test\\files\\lib\\annotations.jar;Y:\\tisue\\scala\\test\\files\\lib\\enums.jar;Y:\\tisue\\scala\\test\\files\\lib\\genericNest.jar;Y:\\tisue\\scala\\test\\files\\lib\\jsoup-1.3.1.jar;Y:\\tisue\\scala\\test\\files\\lib\\macro210.jar;Y:\\tisue\\scala\\test\\files\\lib\\methvsfield.jar;Y:\\tisue\\scala\\test\\files\\lib\\nest.jar
```

to this malformed one:

```
Y;//tisue/scala/build/pack/lib/scala-library.jar;Y;//tisue/scala/build/pack/lib/scala-reflect.jar;Y;//tisue/scala/build/pack/lib/scala-compiler.jar;Y;//tisue/scala/build/pack/lib/scalap.jar;Y;//tisue/scala/build/pack/lib/scala-actors.jar;C;//.m2/repository/org/scala-lang/modules/scala-partest_2.11/1.0.7/scala-partest_2.11-1.0.7.jar;C;//.m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar;C;//.m2/repository/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar;C;//.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.jar;C;//.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar;C;//.m2/repository/org/scalacheck/scalacheck_2.11/1.11.6/scalacheck_2.11-1.11.6.jar;Y;//tisue/scala/build/pack/lib/scala-partest-extras.jar;Y;//tisue/scala/build/pack/lib/scala-partest-javaagent.jar;Y;//tisue/scala/test/files/lib/annotations.jar;Y;//tisue/scala/test/files/lib/enums.jar;Y;//tisue/scala/test/files/lib/genericNest.jar;Y;//tisue/scala/test/files/lib/jsoup-1.3.1.jar;Y;//tisue/scala/test/files/lib/macro210.jar;Y;//tisue/scala/test/files/lib/methvsfield.jar;Y;//tisue/scala/test/files/lib/nest.jar
```

`cygpath --path` has file path smarts, not classpath smarts. ("ok boss, whatever you say," I can almost hear it muttering.)

**Comment by som-snytt** [comment]
I seem to remember a Star Trek (ST:TNG) episode where it took them a few deja vus before they noticed that they were stuck in a temporal loop. That previous commit on the bat file:

```
Normalized line endings.

This brings all the files into line with the .gitattributes
settings, which should henceforth be automatically maintained
by git.
```

**Comment by som-snytt** [comment]
My partest.properties on linux has backslashes in it, before the colons, so I can't pretend to know anything. Oh wait, I see the script snips them.

```
partest.classpath=/home/apm/projects/snytt/build/pack/lib/scala-library.jar\:/home/blah
```

`-m` says you're converting to windows but use forward slashes as God intended.

For drives on cygwin, it's `/cygdrive/c`.

In the old days, the path was built unix-style from scala home, `library.jar:continuations.jar`, so converting was the right thing to do. It looks correct not to convert

I used to develop under cygwin but not for years; next time I boot into windows, wait for updates to install, and then reboot a few times, I'll try it out.

Is this that Spielberg movie where an AI wakes up thousands of years in the future and tries to run the Windows build?

**Comment by som-snytt** [comment]
LGTM % test failure

**Comment by lrytz** [comment]
`+0 −105` - we should have more of those :)

**Comment by som-snytt** [comment]
OK, tried it out. What a trial. What's the emoji for sympathies for SethTisue? I guess it should be :tissuebox:

**Comment by adriaanm** [comment]
:,-D

**Pull request merged**
