### PR TITLE
macro constructors

### PR DESCRIPTION
**Pull request by xeno-by**
review @retronym

### CODE REVIEW

**Comment by adriaanm** [comment]
Neat, but I don't recall seeing this on the 2.11 roadmap...
Is it time for a 2.12 branch?

**Comment by xeno-by** [comment]
Well, it's an idea that I got just a week or so ago when chatting with Manuel Veiel who's researching virtual classes for Scala: https://groups.google.com/forum/#!topic/scala-internals/th7YmFmfKcc.

Since the scope of changes is miniscule, and the change itself qualifies more as a parser bugfix than a new feature, I suggest we include it in 2.11.

**Comment by adriaanm** [comment]
The first patch may be small, but what about the fall out, all things considered?

**Comment by xeno-by** [comment]
Given that we didn't allow macro constructors before and that the typechecker is untouched apart from one additional clause of a pattern match that could never be triggered before, I would say that the probability of regressions is very low.

**Comment by retronym** [comment]
The implementation overhead does look minimal, but I'm not that convinced of the utility. Many other macro flavours have come and gone: can we let this one percolate for a while to see if the is a real need?

**Comment by xeno-by** [comment]
Those ones that fell out of favor were completely new flavors, such as as type macros, or required new ways of doing expansion, e.g. untyped macros. 

Macro constructors are neither - they have the same flavor and the same expansion strategy as def macros. As I mentioned above, I think we can view this as a parser bugfix rather than a new feature.

**Comment by retronym** [comment]
Right now, one knows that `new Xxx` constructs a new instance and calls the constructor. This proposal means that we can't say that any more. This of course is great news to someone who wants to virtualize that language construct, but not necessarily good news for those who want to comprehend code.

Maybe its an acceptable tradeoff, but we have to consider this independently from how easy/hard it is to implement.

**Comment by xeno-by** [comment]
In my opinion, one of the biggest Scala's strengths is representing features with method calls. This gives a unique feeling of uniformity when different features can be customized and modularized using the same mechanism (method defs, first-class modules, imports). 

We're not 100% there though, as there exist features that remain special, but luckily their numbers are growing smaller with every release, making the language more orthogonal. Take, for example, Paul's recent change to how unapplies are handled. When we expressed the full spectrum of pattern matching primitives with methods, we've become able to remove the quasiquote unapplication hack and use standard language tools for that task.

This, of course, brings the question of how much is too much. How much do we allow to customize before we go insane? I think, we have two good empiric rules worked out here:
1. Locality, which requires macro expansions to be confined to the area occupied by c.macroApplication.
2. Typedness, which asks macros to provide type signatures for what they are doing.

In that regard, in my opinion this pull request is okay, because macro constructors are compatible with the both notions:
1. Constructor calls such as `new C` (desugared into `Apply(Select(New(tq"C")), nme.CONSTRUCTOR), List()))`) expand locally using the normal def macro rules - the entire `new C` is replaced with the expansion according to the symbol corresponding to the application target being a macro and no other trees need to be modified. 
2. Constructor expansions are typed - `new C` has type `C` and the expansion can only be typed as `C`. Moreover, signatures of constructors are nothing magic - they take something and produce `C`, which exactly describes what's going on, preventing something like misbehaving macro ctors that expand into unrelated types.

**Comment by retronym** [comment]
But we are lying when we say `new`. `new C() ne new C()` is a pretty fundamental thing to break. We have `apply` methods for cases when you want to use factories rather than constructors. Is it that big an imposition to make the constructor private and fixup the source code to call that explicitly?

**Comment by xeno-by** [comment]
For me, uniformity is very important, and this is one more aspect in which we can make Scala more uniform, so I'd say we should avoid having to do manual fixups if possible.

The `new C() ne new C()` invariant that you mentioning sounds like a valid concern that we, of course, should evaluate. Could you elaborate a bit more? Where is this invariant important?

**Comment by retronym** [comment]
For better or for worse, the Java and Scala expose object identity to the end user. This keyword 'new' has a specific meaning tied to that. 

Scala provides a means to abstract away from that with `apply` methods in factories. These can choose to use a cached value, or even upcast the result to a more general type (some people would prefer if the constructors for ADT's returns the parent type, for example).

This change might let you change your mind later down the track and switch from exposed constructors to factories without a deprecation period, at the expense of some clunky code in the class definition. How many people are asking for this?

**Comment by xeno-by** [comment]
Among the projects that could directly benefit from this feature I know the aforementioned virtual classes and also probably virtualization.

**Comment by gkossakowski** [comment]
I'm an external lurker but I'm with @retronym on this. The `new` keyword has a very specific meaning in Scala similar to one in Java that's specific here: http://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.9

It would be very confused to our users to see code that can have arbitrary semantics tied to `new`. If virtual classes need custom logic for dispatching constructor then virtual classes phase should be introduced that takes care of that. I don't think we should introduce a general purpose facility for that.

**Comment by xeno-by** [comment]
@retronym @gkossakowski Would be great if you could verbalize why you consider the special role of `new` to be important. What important invariants does this establish? Or is it just a habit? Note that neither Kotlin, nor Ceylon have the `new` keyword.

**Comment by gkossakowski** [comment]
@xeno-by: Since Kotnlin and Ceylon don't have `new` keyword then they don't have an issue of overloading its meaning.

It's important to our users to understand that `new` translates to object allocation, literally a `new` bytecode instruction. With macro constructor, `new` becomes completely opaque and can do arbitrary things. This is not great for person reading code that uses such capability. As @retronym pointed out, you can use `apply` method for factory calls and that's what we've been always doing in Scala. The `apply` method can be implemented as a macro without any problem.

**Comment by xeno-by** [comment]
@gkossakowski Why is it important to understand that `new` translates to object allocation? By referring to Kotlin and Ceylon, I wanted to say that this doesn't seem to be a necessity for other languages sharing the same runtime, so why should we take this as a given?

**Comment by adriaanm** [comment]
I agree we shouldn't be overloading the meaning of `new` -- definitely not this late in the cycle. We're not introducing any new features in the last two milestones. We're only 3 months away from 2.11.0 -- let's take that time to polish existing features, deprecate where appropriate so we don't get stuck with cruft, fix important bugs that require binary changes.

**Comment by retronym** [comment]
Closing this one.

**Comment by xeno-by** [comment]
@retronym @adriaanm @gkossakowski I understand that you're opposed to this pull request, but I still like it and in order to improve I would like to understand why exactly.

So far I can only see that you consider it mandatory that `new` have special semantics in comparison to other methods. Why's that? What benefits does this bring? What tasks does it make easier to perform?

**Comment by retronym** [comment]
We inherited `new` from Java. You can argue that its a language design mistake: in concert with `Any#eq`, it makes almost all Scala code referentially intransparent. Or you can say that it was a necessity for Java interop. But that's not directly relevant to this discussion.

We are just arguing that the presence of `new` in the language is a given, that it has specific semantics that are well understood and explicitly communicated by the name of the keyword, and that we are unwilling to virtualize those semantics.

**Comment by paulp** [comment]
Nobody asked, but +1 to the majority opinion.

**Comment by som-snytt** [comment]
I was going to try this out on @ implicitNotFound("missing $A"); minimally, the macro ctor would suppress the missing interpolator warning without special-casing this annotation. At least that was my wild hypothesis.

**Pull request closed without merging**
