### PR TITLE
Serialization compatibility for #8725

### PR DESCRIPTION
**Pull request by hrhino**
Explicit svUID and @transient.

Prevents scala/bug#11919 in 2.13.2.

### CODE REVIEW

**Comment by som-snytt** [comment]
Oh, I see there is "convert to draft" now! What a lifesaver!

The other PR should have put the new map next to the other maps of values in Enumeration.

Are they going to have a bonfire when they finally get rid of Enumeration? How much dev time was sunk into it, up in smoke?

**Review by som-snytt — APPROVED** [review]
I verified that the before test fails with the funny strings.

Wait, aren't they getting rid of java serialization? Aren't they getting rid of Enumeration?

**Review by lrytz — APPROVED** [review]
Thanks!

**Comment by som-snytt** [comment]
There was a check in run/enums.scala that Stefan said didn't work, but I uncommented it and it worked. If only we could ask Stefan. I put it in a PR just to burn some quarantine.

**Pull request merged**
