### PR TITLE
SI-7237 Always choose ForkJoinTaskSupport

### PR DESCRIPTION
**Pull request by soc**
ForkJoinTaskSupport works on Hotspot, Avian and J9,
while ThreadPoolTaskSupport causes the test
test/files/scalacheck/parallel-collections
to reliably hang on all three.

### CODE REVIEW

**Comment by soc** [comment]
This PR is equivalent to https://github.com/scala/scala/pull/2249, which I couldn't reopen.
The changes in https://github.com/scala/scala/pull/2252 to 2.10 and below are different (and marked as [backport]) to this one, because it doesn't try to create an impression of Java 5 support.

**Comment by Blaisorblade** [comment]
@axel22, sorry to bother, but could you propagate your LGTM from #2252 to here?

**Comment by axel22** [comment]
LGTM

**Comment by paulp** [comment]
Superseded by #2348.

**Pull request closed without merging**
