### PR TITLE
Change the signature of Array.unapplySeq for the benefits of Scala 3

### LINKED ISSUE #14693: Missed match on Array(1L) in Scala 3.1.1
## Observation

Consider the following code:
```scala
object MatchTest { 
  val a: Array[Long] = Array(1L)

  def test(x: Any) = x match { 
    case Array(i: Long) => println("Success!")
    case _              => println("Failure!") }

  def main(args: Array[String]): Unit = test(a) }
```
When run under [Scala 2.13.8](https://scastie.scala-lang.org/tEFTcPyhQ4CZCqo9nr183w) this produces `Success` whereas under [Scala 3.1.1](https://scastie.scala-lang.org/lBxvAXaEROmHNElxbaeBSQ) it produces `Failure`. For the latter [it does not matter](https://scastie.scala-lang.org/GBpXr4AKRe6uNyKhybXqIQ) if the compiler option `-source:3.0-migration` is used. 

## Expectation
Same behaviour under both versions or (at least) a warning that the match will fail. Current situation significantly changes runtime behaviour after migrating projects from Scala 2 to Scala 3.

### PR DESCRIPTION
**Pull request by smarter**
Fixes https://github.com/lampepfl/dotty/issues/14693, see discussion in the issue.

### CODE REVIEW

**Comment by julienrf** [comment]
IIUC, we change the signature of `unapplySeq` so that a typed pattern within a pattern sequence works. It seems to me that we are changing the type signature of `unapplySeq` to accommodate the internal way the Scala compiler handles such a combination of patterns.

What is the behavior of the following?

~~~ scala
val xs = Array(1L, true)
val ys = Array(1L, 2L)

def matched(any: Any): Unit =
  any match
    case Array(x: Long, _*) => println(x)

matched(xs)
matched(ys)
~~~

I would expect both to match.

**Comment by smarter** [comment]
>     case Array(x: Long, *) => println(x)

This isn't valid syntax, I assume you mean:
>     case Array(x: Long, _*) => println(x)

> What is the behavior of the following?

In Scala 3 before this PR, only the first matches. In Scala 3 after this PR, both match.

**Comment by smarter** [comment]
(and both still match in Scala 2 after this PR too)

**Review by NthPortal — APPROVED** [review]
I don't have any objection to this; at the same time, I'm not entirely convinced that the problem described by Julien lies here and not in the compiler

**Comment by smarter** [comment]
>  I'm not entirely convinced that the problem described by Julien lies here and not in the compiler

To restate what's going on: in general when typing the unapplySeq call we need to instantiate its type parameter as `Any` (especially in Julien's example, nothing else would fit). According to the specification, this means the pattern matching phase will generate a call to `isInstanceOf[Array[Any]]` which erases to `instanceof Object[]`.
This PR changes the unapplySeq argument type so that we instead generate a call to `isInstanceOf[Array[_ <: Any]]` which erases to `instanceof Object` (because primitive arrays are subtypes of `Array[_ <: Any]` but not of `Array[Any]`).
I don't see what the compiler could be doing differently here, and I can't reproduce the Scala 2 compiler behavior because it relies on a compiler bug as mentioned in https://github.com/lampepfl/dotty/issues/14693#issuecomment-1072461161.

**Comment by smarter** [comment]
>  in general when typing the unapplySeq call we need to instantiate its type parameter as Any 

... is what I thought until now, but it turns out that in Scala 3 this behavior is specific to unapplies defined in Scala 2 classes, so this might in fact be a compiler bug, mea culpa :). Investigation in https://github.com/lampepfl/dotty/issues/14693#issuecomment-1076907130

**Comment by smarter** [comment]
Closing, superceded by https://github.com/lampepfl/dotty/pull/14766

**Pull request closed without merging**
