### PR TITLE
Bump versions for 2.11.0-RC3

### PR DESCRIPTION
**Pull request by adriaanm**
To merge as soon as the release is on maven.

### CODE REVIEW

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
review by @gkossakowski

**Comment by gkossakowski** [comment]
LGTM

**Comment by adriaanm** [comment]
This merge will fix the scala-dist SNAPSHOT build. I'll kick a nightly now. /cc @huitseeker

**Pull request merged**
