### PR TITLE
SI-6841 Fix bug at the intersection of DelayedInit and named args

### PR DESCRIPTION
**Pull request by retronym**
The DelayedInit transformation analyses the constructor to partition
regular initialization from calls to super constructors / trait
initializers.

It failed to find such super calls if they were nested in a Block,
which can happens when using named or default arguments.

This commit makes that code peer into Blocks to correctly partition
the constructor statements.

This change doesn't affect the result of run/t4680.scala, which was
mentioned in nearby comments and which chronicles bugs with DelayedInit
when used in inheritance hierarchies.

Review by @paulp (the author of said comments)

### CODE REVIEW

**Comment by paulp** [comment]
I don't think the risk/reward for DelayedInit-motivated commits on the 2.10.x branch is very attractive.

**Comment by retronym** [comment]
This was reported by Play. It's a pretty straight forward fix, IMO, albeit not comprehensive.

**Comment by JamesIry** [comment]
I agree, the change seems quite low risk.

**Comment by soc** [comment]
LGTM.

**Comment by paulp** [comment]
I am still very doubtful, but on your heads be it.

**Pull request merged**
