### PR TITLE
Rebased #2696

### PR DESCRIPTION
**Pull request by adriaanm**
supersedes #2696

### CODE REVIEW

**Comment by som-snytt** [comment]
@adriaanm Thanks, I wouldn't mind doing the rebase, even though I am a mere journeyman rebaser.

**Comment by adriaanm** [comment]
Darn, looks like test/files/run/repl-paste-4 failed.

**Comment by adriaanm** [comment]
I did the rebase because I'm cutting M4 and wanted to get this one in. I guess there's always the next snapshot.

**Comment by som-snytt** [comment]
But the diff is empty!

Oh, if only we'd used command line diff or git diff, instead of a java library to ensure uniform output!

Just kidding.  I'm sure there's a perfectly logical explanation.  Like, Jenkins has had it in for me ever since I suggested, half-jokingly, that maybe he shouldn't imbibe such a hearty quantity of gin while he's testing our stuff.

**Comment by som-snytt** [comment]
I can't even clean build it -- fresh fetch, pulling my branch and fixing the minor collision:

```
quick.reflect:
    [mkdir] Created dir: /home/apm/projects/scala-pick/build/quick/classes/reflect
[quick.reflect] Compiling 147 files to /home/apm/projects/scala-pick/build/quick/classes/reflect
[quick.reflect] /home/apm/projects/scala-pick/src/reflect/scala/reflect/api/Quasiquotes.scala:12: error: macro implementation has wrong shape:
[quick.reflect]  required: (c: scala.reflect.macros.Context)(args: c.Expr[Any]*): c.Expr[Any]
[quick.reflect]  found   : : Nothing
[quick.reflect] number of parameter sections differ
[quick.reflect]       def apply(args: Any*): Any = macro ???
[quick.reflect]                                          ^
[quick.reflect] /home/apm/projects/scala-pick/src/reflect/scala/reflect/api/Quasiquotes.scala:13: error: macro implementation has wrong shape:
[quick.reflect]  required: (c: scala.reflect.macros.Context)(subpatterns: c.Expr[Any]*): c.Expr[Option[Any]]
[quick.reflect]  found   : : Nothing
[quick.reflect] number of parameter sections differ
[quick.reflect]       def unapply(subpatterns: Any*): Option[Any] = macro ???
[quick.reflect]                                                           ^
[quick.reflect] two errors found
```

**Comment by som-snytt** [comment]
Deleting build.properties fixed the build problem.  From cygwin days, I had a script to output git.commit properties and also the skip.locker flags.

**Comment by som-snytt** [comment]
@adriaanm I did a fresh rebase and build and ant test.suite passed on Linux.  Ah, but not -optimise!  Could that really make a difference here?  Between build cycles and reading Travis Brown's Metaplasm, I keep forgetting what the commit was for.

**Comment by som-snytt** [comment]
I just noticed there are \n in the test code.  That must be it.

**Comment by som-snytt** [comment]
@adriaanm Are the build artifacts archived?  ("Archiving artifacts") 

 I want to see the 

/localhome/jenkins/a/workspace/pr-checkin-per-commit/test/files/run/repl-paste-4-run.log

with my own eyes.

I took another look at the "git diff" code in partest.  It looks like it should work, but in Runner.diffIsOk, the code is knotty, and I can't tell by looking how bestDiff was generated.  If the output of the git Process doesn't give you lines of diff when you expect it to, there should be a red flag.

I changed this test to a SessionTest and rm'd the check file, but I don't see yet what failed.

**Pull request closed without merging**
