### PR TITLE
Allow skipping the xz archives

### PR DESCRIPTION
**Pull request by lrytz**
Using 'ant -Darchives.skipxz=true'

Will use that for checkin (and pr) builds, making them ~10 minutes faster.

review by @jsuereth

### CODE REVIEW

**Comment by jsuereth** [comment]
+20 from me.   On a side note: we should fix the nightly to use scala-dist in the future....

**Comment by jsuereth** [comment]
Oh LGTM

**Comment by adriaanm** [comment]
WOOHOO

**Comment by lrytz** [comment]
let me know if the option should be inverted - my reasoning was to not change the default behavior.

**Comment by lrytz** [comment]
sure, this commit is only band-aid, cleaning things up is overdue - ideally with a move to the sbt build.

**Comment by gkossakowski** [comment]
:sparkles::heart::sparkles:

I'd vote for making it default and introducing an option to opt-out.

**Comment by VladUreche** [comment]
Oh yeah! +INF

**Pull request merged**
