### PR TITLE
Topic/partest no actors

### PR DESCRIPTION
**Pull request by paulp**
We should merge this immediately, to improve the efficiency of the build bots if for no other reason.

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM

**Comment by gkossakowski** [comment]
Does this pull request change anything related to forking of vm for tests we run?

**Comment by paulp** [comment]
Not to my knowledge, but I wrote it a while ago and actors have always been kind of a mystery to me.

**Comment by heathermiller** [comment]
Since @phaller is the partest author/maintainer, maybe he should have a stab at a review as well?

**Comment by heathermiller** [comment]
Also-- if I recall correctly, @vjovanov had replaced actors with futures (as part of the actor migration, since actors are now deprecated) in partest sometime back. (Of course on some branch of his own somewhere)

**Comment by axel22** [comment]
Just for the record, pull: https://github.com/scala/scala/pull/862, fixes a broken test with the parallel collections that the partest scalacheck group previously failed to detect. If the related scalacheck issue has been fixed here, that pull should be merged also.

**Comment by paulp** [comment]
The "before" version of the diff says "class Worker(val fileManager: FileManager, params: TestRunParams) extends Actor", is that not an actor?

**Comment by heathermiller** [comment]
Have a look at the above comment before the snide-ish remark. Accidentally hit send too soon.

**Comment by vjovanov** [comment]
Hey, I did not replace actors in the partest because I have this idea of making it disttest. I will migrate partest to Akka when the situation with Akka is stable. It should be done in one week.

**Comment by paulp** [comment]
Okay, one week, sounds great, none of this should stand in the way of applying this now.

**Comment by heathermiller** [comment]
Except, perhaps, a review by the guy responsible for partest. As per the pull request policy that we all follow.

**Comment by paulp** [comment]
I'm sorry, by "now" I mean "as soon as all parties have had the opportunity to comment." What I object to is having finished, tangibly useful work tabled in favor of things which aren't done yet.

**Comment by jsuereth** [comment]
Just curious:  How are we creating a new partest based on Akka when we won't control the source code?  I think that's more than one week away.  Just saying.

Also, let's remember to be polite everyone.  We're all working towards the same goals!

**Comment by paulp** [comment]
To the extent that I have shown any impoliteness, I apologize - it is not my intention.

**Comment by paulp** [comment]
Oh I see, the "snide-ish remark" was intended to refer to me, I didn't get that at the time.  I didn't intend it as a snide remark; I was genuinely asking if that was not an Actor, because the implementations might have been changed and it was going through some compatibility layer.

**Comment by phaller** [comment]
LGTM

**Pull request merged**
