### PR TITLE
SI-7544 Interpolation message for %% literal 

### PR DESCRIPTION
**Pull request by som-snytt**
The new error text: "conversions must follow a splice; use %% for
literal %, %n for newline".

Review by @adriaanm

### CODE REVIEW

**Comment by xeno-by** [comment]
Looks very good. Thank you!

**Comment by som-snytt** [comment]
That's very kind of you to say.

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@9d5c97c

**Comment by som-snytt** [comment]
@adriaanm This is a no-brainer. You could commit it in a vegetative state.  Not sure about kitty.  That icon looks like a child's plastic footstool from IKEA.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
