### PR TITLE
SI-7859 Value classes may wrap a non-public member

### PR DESCRIPTION
**Pull request by retronym**
We allow value class constructors to be non-public, so to be regular,
we should also allow the same for the param accessor.

This commit uses the 'makeNotPrivate' machinery to ensure that
the backend can generate the requisite unboxing calls.

This commit:
- refactors the code that enforced the restrictions, improving
  a few error messages and positions. The remaining restrictions
  needed some rewording in light of this change.
- allows value classes to have non-public, val parameters.
  private[this] / protected[this] are still disallowed as value
  classes don't have a concept of `this`, and because trying to
  accomdate then would complicate the implementation.
  
  This means that `class C(x: Int) extends AnyVal` is not allowed,
  the user still must write `private val x: Int` or `val x: Int`.
- Outlaw `class C()()(val x: Int) extends AnyVal` to curtail any
  bugs that might lurk in such a formulation.

The tests:
- Show that the privacy is respected in the typer phase, under
  joint and separate compilation. We don't want a repeat performance
  of SI-6601.
- Show that code that needs compiler-generated unboxes works under
  both compilation scenarios
- Checks that the remaining restrictions are enforced and well
  communicated.

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
Updating the documentation: https://github.com/scala/scala.github.com/pull/250

**Comment by gkossakowski** [comment]
I must say that I'm not entirely happy with increased use of `makeNotPrivate` but I won't block this PR on that basis.

The problem with `makeNotPrivate` is:
- it hurts Java interoperability because we expose private members to Java classes
- there's one name space for instance, public members of a class so in order to avoid clashes we have to mangle names
- public names look confusing in tools like debuggers

I'd vastly prefer if we followed what `javac` does which is emitting _static_ accessor methods marked as synthetic methods (so debuggers and other tools ignore them). This would address all three points. The second point is addressed because static names sit in class name space (so they are not inherited).

I mention this only because I'm uneasy to see yet another use of suboptimal (in my opinion) mechanism.

I'll review this PR on Monday or Tuesday.

**Comment by retronym** [comment]
Just to link things together, here's @gkossakowski's ticket proposing a more Java-esque approach to access: https://issues.scala-lang.org/browse/SI-7085

**Comment by gkossakowski** [comment]
@retronym: thanks, I totally forgot that this is being tracked in JIRA. I must develop the habit of searching JIRA before I repeat myself again.

**Comment by retronym** [comment]
PLS SYNC

**Comment by retronym** [comment]
Just spotted the test failures. Will investigate.

**Comment by retronym** [comment]
Pushed an updated check file.

**Comment by retronym** [comment]
ping @gkossakowski

**Comment by gkossakowski** [comment]
LGTM.

**Pull request merged**
