### PR TITLE
Reflection Sealing

### PR DESCRIPTION
**Pull request by dgruntz**
This pull request seals the isXXX and asXXX methods in the traits
defined in the cake piece `scala.reflect.base.Symbols`. All isXXX
and asXXX methods which are known at a particular level to return
`false` or to throw an exception respectively (as defined in the
base abstraction) are overridden with a final method with the same
behavior as the overridden one.

Two of these methods cannot be overridden as this leads to a build
error (see https://issues.scala-lang.org/browse/SI-6298).

@paulp: Do you have an idea what happens here regarding this build problem?

Review: @xeno-by

### CODE REVIEW

**Comment by paulp** [comment]
I left you a comment at SI-6298.  It doesn't work because it isn't correct.  (Much as one might wish things to be so clean...)

**Comment by xeno-by** [comment]
oh I see. @dgruntz could you please adjust the patch accordingly, and then we can merge

**Comment by jsuereth** [comment]
Hey, what's the status on this?  If I don't see movement for 15 days I'm going to close it and you can reopen when ready.

**Comment by gkossakowski** [comment]
No activity for the last 16 days. Closing.

**Pull request closed without merging**
