### PR TITLE
showRaw can now print positions

### PR DESCRIPTION
**Pull request by xeno-by**
Would be great to simply add `printPos` argument to `show` and `showRaw`,
but we're bound by binary compatibility obligations for 2.10.x.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @retronym

**Comment by xeno-by** [comment]
also see https://github.com/scala/scala/pull/1753 w.r.t the binary- and source-compatibility guarantees for scala-reflect.jar

**Comment by paulp** [comment]
I don't like the approach of implementing something in a suboptimal fashion and dropping comments around it saying we should do it better when constraints are lifted. It means the commit is being delivered all bundled with a generous helping of technical debt, and our credit at the technical debt bank is already strained.

Adapting the desirable design to the constraints where necessary is going to work out far better than programming to the constraints and then attempting to improve it at some unknown later time. I would strongly favor that rather than enumerating caveats in this way, you should target 2.11 with a patch you can fully endorse and backport it to 2.10. We shouldn't let the tail of short-term limitations wag the dog.

**Comment by adriaanm** [comment]
probably best to keep this in macro-paradise for now

**Pull request closed without merging**
