### PR TITLE
exposes Symbol.children

### PR DESCRIPTION
**Pull request by xeno-by**
As requested in http://stackoverflow.com/questions/12078366/

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @paulp

**Comment by xeno-by** [comment]
Will resubmit

**Comment by paulp** [comment]
"children" is a highly suboptimal name for the api.  How about "sealedSubclasses" or anything which a) mentions "sealed" and b) is not as generic and multiple-meaning as "children".

**Comment by paulp** [comment]
Oh, wonderful, it isn't children.  I wonder what I was just looking at.

**Comment by paulp** [comment]
Oh I see, the pull request title is "exposes Symbol.children"

**Comment by paulp** [comment]
knownDirectSubclasses is fine btw.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scala/scala/pull/1202

**Pull request closed without merging**
