### PR TITLE
Fixes SI-3791

### PR DESCRIPTION
**Pull request by dgruntz**
review by @phaller or @retronym

After Float.Epsilon and Double.Epsilon have been deprecated for
2.9, they have been removed for 2.10. With this pull request, the
correct values for Epsilon are added for 2.11.

The definition for the machine epsilon is taken from the paper "What
Every Computer Scientist Should Know About Floating-Point Arithmetic"
by David Goldberg, published in the March, 1991 issue of the ACM
Computing Surveys.

I have also fixed the indentation of two doc comments in both sources.

### CODE REVIEW

**Comment by jsuereth** [comment]
This LGTM to me too.

**Comment by soc** [comment]
I would like to suggest leaving it out completely.

There were neither hordes of developers crying for getting their Epsilon back nor is there any definition of the actual value. It seems like every language thinks that it needs to define their own “most-correct” Epsilon value.

People who actually work with Epsilon will probably just define their own one anyways.

**Comment by paulp** [comment]
I agree with soc.  Any idea that there is no cost to even the apparently simple act of defining a constant is convincingly debunked by this very issue.  The many issues with the classes in scala.math.\* combined with what I hope is a low tolerance for incorrectness by the users of those classes mean that without stellar maintenance which it is apparent we cannot presently provide, we suffer the lose/lose scenario of pouring time into something which remains inadequate to its purpose.

This is just the tip of the iceberg, but I expect to reuse that rationale so I'm helpfully preparing everyone to start tuning me out.

**Comment by jsuereth** [comment]
Alright.  I'm switching sides.  @paulp + @soc have good points.   When doing epsilon/error code myself, you almost always want to define your own constant in line with your calculation and acceptable error.

**Comment by dgruntz** [comment]
I could live without a definition of Epsilon in Scala; I simply followed the route as outlined in SI-3791, namely to deprecate it for 2.9, remove it for 2.10 (which I made as a last-minute change) and to reintroduce it for 2.11 with the correct value. The constant defined in 2.9 was plain wrong, so that problem is now fixed with 2.10.

I agree that there are two definitions for the machine epsilon; they differ by a factor of 2. I took the definition which can be found in [Wikipedia](http://en.wikipedia.org/wiki/Machine_epsilon) and in the [Computing Surveys](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) article by Goldberg, and this definition is also consistent with the one in the [LAPACK](http://www.netlib.org/lapack/lug/node74.html) library. There are many wrong implementations and documentations (e.g. the one in [Apache Commons Math](http://commons.apache.org/math/apidocs/org/apache/commons/math3/util/Precision.html#EPSILON)). For me, this is a justification to define this value as a constant in classes `Float` and `Double` (with the documentation that this constant is an upper bound for the relative error when approximating a real by a floating-point number).

**Comment by paulp** [comment]
I fear that the historical record indicates we are better off staying out of such things.  If there are many wrong implementations and documentations, then some of the following will be true: we will ourselves have a wrong one, for some definition of wrong; one or more which is wrong is actually be right, because it will be more important to be consistent than to be correct, but ours is fixed; someone will propose a "typeclass pattern" for specifying "an implicit Epsilon"; the world will end in a conflagration.

I'd rather not see this go in and we need to keep the hallway clear, so I'm closing this for now; we have a long time until 2.11 to debate it.

**Pull request closed without merging**
