### PR TITLE
SI-7916: ScriptEngine support

### PR DESCRIPTION
**Pull request by som-snytt**
Refactor the ScriptEngine support to an adaptor atop the
IMain API.

Allow references to resolve to context attributes. (The
attributes must be defined at compilation time, though
they may resolve to updated values at evaluation time.)

This means that attributes are not bound statically in
REPL history. In particular, we forgo the trick of binding
attributes named "name: Type" as typed values.

Instead, an `x` bound in dynamic context is injected into
the script as a dynamic selection `$ctx.x` where `ctx`
performs the look-up in the script context.

When a compiled script is re-evaluated, a new instance of
the script class is created and defined symbols are
rebound.

### CODE REVIEW

**Comment by som-snytt** [comment]
@SethTisue Is it possible to get this into 2.11.8? It's to nail down the ScriptEngine support. A few more TODOs.

**Comment by som-snytt** [comment]
This PR reduces the explosion of constructors for IMain. Some tests use `new IMain(settings)`, so accommodating that.

**Comment by SethTisue** [comment]
sure, this still has a shot of making 2.11.8. marking "on hold" for now until you tell us those TODOs are DOne.

**Comment by som-snytt** [comment]
All I have to say is, it's gonna be really annoying when Ammonite has JSR 223.

**Comment by lrytz** [comment]
@som-snytt IUC the TODOs are not new, they are also TODOs in the current state of things, right?

**Comment by som-snytt** [comment]
@lrytz Yes, old TODOs, like SI-8422. The refactor was for general goodness and make it easier to do script engine more correctly. The previous code took attributes with colon-separated type, "s: String", to bind `s` as a string; a TODO is to ask if that's worth keeping. The new code adds `Dynamic` context, a different model. Also TODO is to exercise it a bit. I don't use it myself.

**Comment by SethTisue** [comment]
my hesitations around merging were:
- (general) we need to be especially cautious and conservative about merging stuff in to 2.11.x. a somewhat higher risk of ancillary breakage is acceptable on 2.12.x
- (specific) it didn't look like the testing code in test/junit/scala/tools/nsc/interpreter/ScriptedTest.scala was actually done (I thought that might be what you meant by TODO, in fact, but wanted Jenkins results in the meantime? I didn't really know what you meant, I guess I should have asked)

**Comment by SethTisue** [comment]
basically my question is, why merge this (and risk breaking 2.11.8 at almost the last minute) before the new-feature part is done?

**Comment by som-snytt** [comment]
This was previously a 2.12 target, but the three people who want to use javax.script badly enough to get mad about it probably don't want to wait. I also don't want to break clients of IMain. But I did the refactor a long time ago and didn't get it in; or we could just wait for ammonite.

Yeah, I was asking if there's time b/c risk etc. I'll make time for polish if it's worth it. Otherwise I won't.

**Comment by som-snytt** [comment]
OK, nm.

**Comment by SethTisue** [comment]
replaced with #4819

**Pull request closed without merging**
