### PR TITLE
WIP: SD-228 eliminate static super accessors in traits

### PR DESCRIPTION
**Pull request by lrytz**
WIP, don't merge: the first commit updates starr to a version on scala-release-temp that corresponds to the tip of this PR. This way I can find out if all commits in this PR pass CI validation.

The temporary starr is build from this branch: https://github.com/lrytz/scala/tree/traitSuperAccessorsTmp
It's the same as this PR, but without the starr update in the first commit. The bootstrap job that built it passed all tests (https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/593/)

For submission, the right procedure is probably to keep the current starr, have CI fail on the commits, and then re-starr right after merging it.

### CODE REVIEW

**Comment by sjrd** [comment]
FYI, I suspect this might break Scala.js, more specifically the commit "Make $init$ methods static during erasure instead of code gen". It might be good to launch a community build when this PR approaches merging. Or ping me to perform a local test on SJS.

**Comment by lrytz** [comment]
From the community build:

```
[scala-js] [error] error: java.lang.AssertionError: assertion failed:
[scala-js] [error]   Trying to access the this of another class: tree.symbol = trait LowPrioAnyImplicits, class symbol = object Any compilation unit:Any.scala
[scala-js] [error]      while compiling: /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-92f0738043e86c3eecf15c4e0c8376f84b56faf5/library/src/main/scala/scala/scalajs/js/Any.scala
```

That looks like an invalid AST from the Scala compiler (https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L1625-L1635).

I'll try to reproduce..

The rest of the community build is running here: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/620/console

**Comment by lrytz** [comment]
@sjrd here's a minimized example - it doesn't take much:

``` scala
trait T { val x = 0 } // has an $init$ method
class C extends T   // calls T.$init$(C.this)
```

The `$init$` method is static. The core issue is that there's no sensible AST corresponding to a reference to a static method:
- Ident(staticMethodSym) doesn't make sense: the method belongs to some class
- Select(CompanionModule, staticMethodSym) also doesn't make sense: the method is not in the module class
- Select(Class, staticMethodSym) also doesn't make sense, Class is a type, not a term

The current result of [`gen.mkAttributedRef(staticMethodSym)`](https://github.com/scala/scala/blob/2.12.x/src/reflect/scala/reflect/internal/TreeGen.scala#L155) is `Select(This(ownerClass), methodSym)`, which is weird too, but it's a way to get from a class symbol to a term tree.

The reason things don't crash in the JVM backend (we have the [same assertion in place](https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L312-L314) that crashed in SJS) is that for static calls, we simply skip code gen for the qualifier: https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L669

This is not the case in the SJS code gen, and `genExpr(receiver)` leads to the crash: https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L2305

What do you think is the best way forward? I guess so far you don't have support for static methods in SJS?

**Comment by lrytz** [comment]
The rest of the community build passed: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/620/console

**Comment by sjrd** [comment]
@lrytz Thanks for the detailed explanation. I guess the best way forward is for SJS to do a similar exception to avoid `genExpr(receiver)`. In fact we should somehow end up with the same treatment as for impl class method calls: https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L2298-L2299

The SJS IR has static methods (we've been using them for impl class methods for ages), so that is not a problem.

I'll work on this as soon as the camera ready for my Scala'16 paper is submitted (the deadline is tomorrow noon-ish).

**Comment by lrytz** [comment]
@sjrd thanks! No rush, and if it looks non-trivial, please wait until we reach a decision whether this PR gets merged or not - it's still open (https://github.com/scala/scala-dev/issues/228).

**Comment by sjrd** [comment]
@lrytz What resolvers do I need to get nightlies of scala-xml? The following was not enough:

```
> set resolvers in Global += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
> ++2.12.0-31505fe-SNAPSHOT
```

gave me

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang.modules#scala-xml_2.12.0-744b296-nightly;1.0.5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.scala-lang.modules:scala-xml_2.12.0-744b296-nightly:1.0.5
[warn]            +- org.scala-lang:scala-compiler:2.12.0-31505fe-SNAPSHOT (C:\Users\Sepi\Documents\Projets\scalajs\project\Build.scala#L515)
[warn]            +- org.scala-js:scalajs-compiler_2.12.0-31505fe-SNAPSHOT:0.6.13-SNAPSHOT ()
```

**Comment by SethTisue** [comment]
> What resolvers do I need to get nightlies of scala-xml

@sjrd `scripts/jobs/validate/publish-core` doesn't build scala-xml. so I don't think the artifact you need exists.

I started this Jenkins run https://scala-ci.typesafe.com/view/scala-2.12.0/job/scala-2.12.0-release-main/82/ which should publish what you need.

**Comment by SethTisue** [comment]
alternatively, you could clone the scala-xml repo and `publishLocal` the needed JAR yourself

**Comment by SethTisue** [comment]
alternatively, you can clone the scala-xml, repo add one more resolver `set resolvers in Global += "nightly" at "https://scala-ci.typesafe.com/artifactory/scala-release-temp/"`, and `++2.12.0-31505fe-SNAPSHOT publishLocal` should work (it worked for me, but I didn't try to use the resulting jar from Scala.js)

**Comment by sjrd** [comment]
Thanks @SethTisue, I manage to get it from the artifacts published by the build you mentioned.

I think the necessary changes are those in https://github.com/scala-js/scala-js/compare/master...sjrd:static-trait-init-rc2
However, I get a very strange error when compiling the helloworld with this branch (`> helloworld/compile`). After compiling the library and eventually arriving at the helloworld, I get:

```
[error] error while loading package, class file 'C:\Users\Sepi\Documents\Projets\scalajs\library\target\scala-2.12.0-315
05fe-SNAPSHOT\scalajs-library_2.12.0-31505fe-SNAPSHOT-0.6.13-SNAPSHOT.jar(scala/scalajs/js/package.class)' is broken
[error] (class java.lang.NullPointerException/null)
[error] error while loading JSApp, class file 'C:\Users\Sepi\Documents\Projets\scalajs\library\target\scala-2.12.0-31505
fe-SNAPSHOT\scalajs-library_2.12.0-31505fe-SNAPSHOT-0.6.13-SNAPSHOT.jar(scala/scalajs/js/JSApp.class)' is broken
[error] (class java.lang.NullPointerException/null)
[error] C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\HelloWorld.scala:14: illegal inheritance;
[error]  self-type helloworld.HelloWorld.type does not conform to scala.scalajs.js.JSApp's selftype scala.scalajs.js.JSA
pp
[error] object HelloWorld extends js.JSApp {
[error]                              ^
[error] three errors found
[error] (helloworld/compile:compileIncremental) Compilation failed
```

Note that this is about _class_ files being broken.

If I revert the change at declaration site of the `$init$` method, i.e., at https://github.com/scala-js/scala-js/compare/master...sjrd:static-trait-init-rc2#diff-c9a195a739d51194e79f0655bc93bd61R1322 (not at call site), and I rebuild everything (so after a full `clean`), then I can successfully compile the hello world (although not link it, obviously, since the call site and definition site don't match at the IR level).

If I revert the change when compiling the library (`library/package`), and then enable the change when compiling the hello world (`helloworld/compile`), compilation succeeds. So this seems to indicate that the issue happens when building the class files for the library, not when loading them.

Only _accessing_ `sym.isStaticMember` without using its value in the test is not sufficient to trigger the compile error, so it doesn't seem to be an issue caused by forcing. Yet somehow the presence of this test causes the class files to be broken or not.

I'm a bit lost right now. I think I'll let it rest until Monday, unless you guys have a hint for me.

FTR, I'm on Windows atm.

**Comment by lrytz** [comment]
@sjrd I did `clean` and `helloworld/compile`, and it succeeded for me. here's how i updated the scala version: https://github.com/scala-js/scala-js/compare/master...lrytz:static-trait-init-rc2?expand=1

I used the same scala version that's used in this PR as starr, it's published (together with modules) on `scala-release-temp`.

**Comment by lrytz** [comment]
At least it looks to me like it succeeded: some warnings are reported in sbt as `[error]`, but at the end there's a `[success]`:

```
> helloworld/compile
...
[info] Compiling 33 Scala sources to /Users/luc/scala/scala-js/compiler/target/scala-2.12.0-744b296-nightly/classes...
...
[info] Resolving org.scala-js#scalajs-compiler_2.12.0-744b296-nightly;0.6.13-SNAPSHOT ...
...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-js#scalajs-compiler_2.12.0-744b296-nightly;0.6.13-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] Unpacking Scala library sources to /Users/luc/scala/scala-js/scalalib/target/scalaSources/2.12.0-744b296-nightly...
...
[info] Packaging /Users/luc/scala/scala-js/compiler/target/scala-2.12.0-744b296-nightly/scalajs-compiler_2.12.0-744b296-nightly-0.6.13-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 102 Scala sources to /Users/luc/scala/scala-js/library/target/scala-2.12.0-744b296-nightly/classes...
[info] Compiling 4 Scala sources to /Users/luc/scala/scala-js/library-aux/target/scala-2.12.0-744b296-nightly/classes...
[info] Compiling 39 Scala sources to /Users/luc/scala/scala-js/javalanglib/target/scala-2.12.0-744b296-nightly/classes...
[info] Compiling 165 Scala sources to /Users/luc/scala/scala-js/javalib/target/scala-2.12.0-744b296-nightly/classes...
[info] Compiling 544 Scala sources to /Users/luc/scala/scala-js/scalalib/target/scala-2.12.0-744b296-nightly/classes...
[error] warning: 'icode' specifies no phase
[error] warning: 'icode' specifies no phase
[error] warning: 'icode' specifies no phase
[error] warning: 'icode' specifies no phase
[error] warning: there were 38 deprecation warnings (since 2.10.0)
[error] warning: there were 20 deprecation warnings (since 2.11.0)
[error] warning: there were two deprecation warnings (since 2.12)
[error] warning: there were 43 deprecation warnings (since 2.12.0)
[error] warning: there were 103 deprecation warnings in total; re-run with -deprecation for details
[error] warning: there was one feature warning; re-run with -feature for details
[error] 6 warnings found
[info] Packaging /Users/luc/scala/scala-js/library/target/scala-2.12.0-744b296-nightly/scalajs-library_2.12.0-744b296-nightly-0.6.13-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Scala source to /Users/luc/scala/scala-js/examples/helloworld/target/scala-2.12.0-744b296-nightly/classes...
[success] Total time: 116 s, completed Sep 26, 2016 12:52:53 PM
```

**Comment by sjrd** [comment]
Indeed, with your suggested settings to use the nightly version, I can compile and run the helloworld, as well as the test suite.

> At least it looks to me like it succeeded: some warnings are reported in sbt as [error], but at the end there's a [success]:

Those `[error]`s are expected. They're not `[warn]`s because the standard library is compiled with a forked scalac (instead of through sbt's incremental compiler) so we only have the stdout/stderr distinction.

**Comment by sjrd** [comment]
Here is a PR for Scala.js: https://github.com/scala-js/scala-js/pull/2608 so that our full CI runs on it.
Pending acceptance of the present PR in scala/scala

**Comment by lrytz** [comment]
Thanks for checking, @sjrd! Here's a re-run of the community built with scala-js pinned to your branch.

✅ https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/663/console

**Comment by lrytz** [comment]
we decided that we're not going to merge this, see https://github.com/scala/scala-dev/issues/228#issuecomment-250110357

**Pull request closed without merging**
