### PR TITLE
 fixed trivial error with printing of exception stack trace in verbose m...

### PR DESCRIPTION
**Pull request by rssh**
Fixed trivial error with printing internal compiler exception stacktrace in verbose mode: in original variant  pw.toString  show us something like PrintWriter@hashCode

### CODE REVIEW

**Comment by xeno-by** [comment]
What's interesting is that we already have `scala.tools.nsc.util.stackTraceString`, but everyone keeps reimplementing it (including me). 

There's even `getStackTraceString`, which is pimped onto `Throwable` in `Predef`. It works differently though, and its result, to be honest, leaves me wondering about why it's in so fundamental that it's been put in Predef.

```
scala> new Exception().printStackTrace
java.lang.Exception
        at $line8.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:30)
        at $line8.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)
        at $line8.$eval$.<init>(<console>:7)
        at $line8.$eval$.<clinit>(<console>)
        at $line8.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:731)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:980)
        at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:570)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:601)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:745)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:790)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:702)
        at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:566)
        at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:573)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:576)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:867)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:83)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

scala> scala.tools.nsc.util.stackTraceString(new Exception)
res1 @ 200483a5: String =
"java.lang.Exception
        at .<init>(<console>:30)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:731)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:980)
        at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:570)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:601)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:745)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:790)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:702)
        at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:566)
        at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:573)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:576)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:867)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:83)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
"

scala> new Exception().getStackTraceString
res2 @ 7736b039: String =
".<init>(<console>:30)
.<clinit>(<console>)
.<init>(<console>:7)
.<clinit>(<console>)
$print(<console>)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
java.lang.reflect.Method.invoke(Method.java:597)
scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:731)
scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:980)
scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:570)
scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:601)
scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:745)
scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:790)
scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:702)
scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:566)
scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:573)
scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:576)
scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:867)
scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:83)
scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by rssh** [comment]
btw ---  may be also give full stack trace when -Ydebug  ?

**Comment by xeno-by** [comment]
Might be useful, but let's ask @paulp first.

**Comment by paulp** [comment]
"What's interesting is that we already have scala.tools.nsc.util.stackTraceString, but everyone keeps reimplementing it (including me)." If only you knew how many existing facilities go unused...

I removed a lot of code a while back when it was suggested that there is too much code and that I had any responsibility for that, but if you wind trunk back six months or so and look at Exceptional.scala and some other files which work with it, you will see stack traces as I'd like to print them.  Given -Yrich-exceptions or something like that, it would find the source file and context associated with each line of the stack frame and print it as a sequence of 7 line (3 before, 3 after) code snippets showing the path of the exception.

The method pimped via predef is one of those zero-value things which date back to before my time.  This describes a high percentage of the standard library.

**Comment by adriaanm** [comment]
it would be great to restore Exceptional to its past [glory](https://github.com/scala/scala/blob/a7a1e3a1959f26c9b44b40b328ef217b4ebdbaba/src/compiler/scala/tools/nsc/util/Exceptional.scala), deprecate those dubious methods in Predef, and eradicate them as soon as we can .

@rssh, would you like to take that on?

**Comment by adriaanm** [comment]
In any case, this request looks like a valid clean up, so I'm going to go ahead an interpret those previous comments as LGTM and hit 'merge'.

**Comment by adriaanm** [comment]
Ah wait, sorry, @rssh, have you signed the [Scala CLA](http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf)?

**Comment by rssh** [comment]
Yes  (sign one when submit patch to play).

**Comment by rssh** [comment]
ohh - it's other than typesafe agreement.  So, will email scan tomorrow.

**Comment by adriaanm** [comment]
Thank you! I apologize for the inconvenience. We are hoping to streamline this whole process.

**Comment by rssh** [comment]
Signed,  scanned version is sent by e-mail,  paper version -  by snail mail

**Comment by adriaanm** [comment]
Thanks!

**Comment by adriaanm** [comment]
One more thing, in future, please format your commit messages according to https://github.com/scala/scala/wiki/Pull-Request-Policy

**Pull request merged**
