### PR TITLE
SI-7045 reflection now auto-initializes thisSym

### PR DESCRIPTION
**Pull request by xeno-by**
thisSym joins the happy family of flags, annotations and privateWithin,
which automatically trigger initialization, when used within runtime
reflection.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @retronym

**Comment by xeno-by** [comment]
Too many kitties?

**Comment by adriaanm** [comment]
I'm working on it.

**Comment by adriaanm** [comment]
I think I fixed the problem. Please post on scala-internals when you spot other problems with our dear kitten.

**Comment by xeno-by** [comment]
How did you spot this one? Do you have a github comment filter for the word "kitty"? :)

**Comment by adriaanm** [comment]
pure luck -- no, I do try to keep up with all comments everywhere, but it's not the most efficient notification system about kitten rampages

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

(this is testing latest improvements of kitten by @adriaanm)

**Comment by adriaanm** [comment]
PLS REBUILD ALL

testing the kitty

**Comment by xeno-by** [comment]
The failure is legit. I'll look into it soon.

**Pull request closed without merging**
