### PR TITLE
minor style updates for Scaladoc formatting

### PR DESCRIPTION
**Pull request by acjay**
review by @felixmulder, @heathermiller, & @VladUreche 

Prospective style improvements [mentioned by me on Gitter](https://gitter.im/scala/scala?at=56f9391d76b6f9de194bce20).

### CODE REVIEW

**Comment by VladUreche** [comment]
Thanks for the contribution @acjay! I think the best reviewer for this is @felixmulder.

**Comment by felixmulder** [comment]
Just arrived home from Milan - I'll have a look during the morning :)

**Comment by felixmulder** [comment]
LGTM :)

**Comment by adriaanm** [comment]
Thank you, and welcome @acjay!

**Comment by acjay** [comment]
:grinning:

**Pull request merged**
