### PR TITLE
Fix typos in compiler and reflect

### PR DESCRIPTION
**Pull request by janekdb**
**Miscellania**:

  Miscellania is a small island off the northernmost part of the Fremennik Isles - _RunScape Wiki_

**Miscellanea**:

  A collection of miscellaneous objects or writings - _Merriam-Webster_

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]

**Comment by janekdb** [comment]
Added `reviewed` label in case the `approved` status was not being looked for in the PR list.

not-easily-noticed

There should be just one way to indicate the reviewed status.

**Comment by janekdb** [comment]
The `reviewed` label needs adding.

**Comment by adriaanm** [comment]
there's a `review:approved` filter that I use to go through the PRs ready for merging. The reviewed label will be phased out.

**Comment by SethTisue** [comment]
the ticket on that is https://github.com/scala/scabot/issues/63

**Comment by SethTisue** [comment]
thanks Janek!

**Pull request merged**
