### PR TITLE
Name logic consistency

### PR DESCRIPTION
**Pull request by paulp**
Review by @adriaanm

### CODE REVIEW

**Comment by paulp** [comment]
What I'd really like to do is drag all the name logic out of the cake and into a more independent component, but that will be more demanding. At least we can start dropping some of these unnecessary methods.

**Comment by paulp** [comment]
I hate the ping-pong test. I can't reproduce that failure.

**Comment by paulp** [comment]
There are zero differences in the just-pushed commits except that I rebased. Hoping a different random walk wins over the ping pong test. Next I'll try deleting the ping pong test.

**Comment by JamesIry** [comment]
ping-pong hates you back.

**Comment by paulp** [comment]
Turns out ping pong had the goods this time.

**Comment by paulp** [comment]
Wow, github orders the pull request events and commentary according to the "ostensible time" of a commit, not the actual one? What are they thinking? I just push -f ed a new commit, and it showed it as "two days ago", including showing our two comments as coming after that commit. I rebased against with --ignore-date so it would get a now time and re-pushed, and it shows it at the right spot.

Who could possibly want that behavior?

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
PLS SYNCH

**Comment by paulp** [comment]
PLS HAVE MERCY

**Comment by adriaanm** [comment]
LGTM, though I must confess I have only to managed to skim it.

**Comment by paulp** [comment]
That's OK if you only managed to skim - I'm an acquired taste, like Joyce or Proust.

**Pull request merged**
