### PR TITLE
SI-5695 removes Context.enclosingApplication

### PR DESCRIPTION
**Pull request by xeno-by**
Apparently it's impossible to find out the enclosing Apply node
if you're an argument being typechecked.

This functionality is by far not a core feature of macros,
so I'm removing it.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @lrytz

**Comment by lrytz** [comment]
out of curiosity, why doesn't `enclosingApplication` work as expected?

and i guess you forgot to remove `test/pending/run/t5695.check`

**Comment by xeno-by** [comment]
When arguments are typechecked, the context doesn't include the apply node itself, so I figured out this means `enclosingApplication` won't work.

**Comment by lrytz** [comment]
right i see. lgtm

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Pull request merged**
