### PR TITLE
Fix to Scaladoc keyboard shortcuts for Firefox

### PR DESCRIPTION
**Pull request by heathermiller**
Trivial patch should fix bug in Firefox. 

Preview URL, working in Firefox, Chrome, and Safari: http://lampwww.epfl.ch/~hmiller/scaladoc/library

Anyone with IE, please now test the above URL and let me know if you have any issues.

### CODE REVIEW

**Comment by VladUreche** [comment]
Thanks a lot for the patch Heather!

My report for trying IE 8 and Firefox on Windows 7 and Firefox on Ubuntu:
- Tabbing works (you have to press tab twice to jump from one textbox to the other, as the first tab jumps back to the navigation panel filter textbox and the second tab jumps to the member filter textbox)
- Moving the cursor in the left navigation panel works, Enter works
- Once a class is selected, you can jump to the member filter
- PgUp and PgDown are not working in the class frame (not working for IE/FF on Windows, not working for FF on Ubuntu but working on Chromium on Ubuntu)
- Up and Down are working properly in all the browsers I tested
- IE8 is terribly slow at filtering, it stops responding for a couple of seconds before you see the results

And a question: in the class frame, after you press Up/Down or PgUp/PgDown, is the text you entered in the filter supposed to disappear?

**Comment by heathermiller** [comment]
Hey Vlad, thanks a lot for testing and passing along your observations.

> - Tabbing works (you have to press tab twice to jump from one textbox to the other, as the first tab jumps back to the navigation panel filter textbox and the second tab jumps to the member filter textbox)

To be expected. I figured more people would be searching for entities than members in general, so entities get the priority. 

> - Moving the cursor in the left navigation panel works, Enter works

Great. 

> - Once a class is selected, you can jump to the member filter

Great. 

> - PgUp and PgDown are not working in the class frame (not working for IE/FF on Windows, not working for FF on Ubuntu but working on Chromium on Ubuntu)

For the record, they do work... Just not when the right-panel's text filter is selected. Though I agree that it'd be more convenient if it worked as it does in Chrome. Will look into it.

> - Up and Down are working properly in all the browsers I tested

Great. 

> - IE8 is terribly slow at filtering, it stops responding for a couple of seconds before you see the results

Is that a regression? I'm not sure how my patch could have caused that. I do know that IE doesn't play nicely with jQuery. It could also have something to do with soc's recent update of jQuery? 

> And a question: in the class frame, after you press Up/Down or PgUp/PgDown, is the text you entered in the filter supposed to disappear?

Yes. Because page up/down seems most appropriately suited to browsing the full member list. Just filter if you don't want to page up/down (I thought that was the point of the filter).

**Comment by VladUreche** [comment]
> For the record, they do work... Just not when the right-panel's text filter is selected. Though I agree that it'd be more convenient if it worked as it does in Chrome. Will look into it.

Thanks!

> Is that a regression? I'm not sure how my patch could have caused that. I do know that IE doesn't play nicely with jQuery. It could also have something to do with soc's recent update of jQuery?

I have no idea, next time I log into Windows I can check if there's any slowdown compared to the 2.9 scaladoc. Btw, wasn't it Kato who updated jQuery?

> Yes. Because page up/down seems most appropriately suited to browsing the full member list. Just filter if you don't want to page up/down (I thought that was the point of the filter).

Oh, I see. I was trying to filter "map" and then scroll down to see all results with PgDown. Being able to go up/down on the members list and press Enter to expand would completely solve that use case. :)

**Comment by kzys** [comment]
Yeah, I upgraded jQuery. Honestly I can't reproduce the problem because I don't have IE8 now.

Is it slow during typing or after?

**Comment by VladUreche** [comment]
> Is it slow during typing or after?

It slows down while filtering members. Once the filtered members and shown, it's back to normal.

**Comment by kzys** [comment]
If so, I would like to try "throttling".
http://benalman.com/projects/jquery-throttle-debounce-plugin/

**Comment by VladUreche** [comment]
> If so, I would like to try "throttling".

Is it hard to implement? If not, let's try it.

**Comment by kzys** [comment]
Ok. I'll try it at night (in JST).

**Comment by VladUreche** [comment]
Cool, thanks a lot Kato! I'll boot up Windows as soon as you indicate a link to try out.

**Comment by jsuereth** [comment]
Quick question:  Can I merge this as is, or do you expect more to be done?

**Comment by heathermiller** [comment]
Merge as is. I'm reasonably certain that the slow-down on IE is unrelated. Vlad and Kato can likely discuss the jQuery tweaks elsewhere.

Yes, I'll submit a patch to fix any awkwardness between browsers in the future, but am too occupied weekdays to work on this. As it stands, with imperfections between browsers, it's still a huge improvement, and it's not broken or anything. (See response to Vlad above).

Regardless, this is a straggler commit that should have probably been in the original pull that was already merged.

**Comment by jsuereth** [comment]
Done!  I can't wait to see this next nightly.

**Comment by VladUreche** [comment]
Merge it Josh, there's no reason to believe the IE slowdown is related. Heather, is there any chance you'll implement Daniel's suggestions? ;;)

**Comment by heathermiller** [comment]
No chance. I don't fully agree with them as they seem too specific to his personal style of Scaladoc usage (I don't think the complaints are valid for 99.9% of Scaladoc users-- i.e. complaint: now impossible via keyboard to select objects, from my perspective, it was always basically impossible for most everyone.)

But like I said, I'll make some tweaks at some point when I have time to spend on bonuses like this.

**Pull request merged**
