### PR TITLE
Include library-aux sources in library sources jar

### LINKED ISSUE #12958: publish bootstrapping sources from `library-aux` in `-sources.jar` artefacts
This is needed to show documentation of definitions inside those classes inside IDE.
See https://youtrack.jetbrains.com/issue/SCL-22167 (with comments)

The sources are located here:
https://github.com/scala/scala/tree/2.13.x/src/library-aux

It's already done for scala docs—they are published in `-javadoc.jar` artifacts.

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/bug/issues/12958

### CODE REVIEW

**Comment by SethTisue** [comment]
@lrytz should, could you provide a link to a sample artifact for @unkarjedy to test...?

**Comment by lrytz** [comment]
@unkarjedy Scala version 2.13.14-bin-ed3dfc9-SNAPSHOT on resolver https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots if that helps?

```
➜ sandbox unzip -l $(cs fetch --sources -r=https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots org.scala-lang:scala-library:2.13.14-bin-ed3dfc9-SNAPSHOT) | grep Any.scala
     7268  01-01-2010 00:00   scala/Any.scala
```

**Comment by unkarjedy** [comment]
I was on a vacation. 
I will take a look at this this week.

**Comment by unkarjedy** [comment]
@lrytz  It works :)

image

image

**Comment by unkarjedy** [comment]
I want to use some Scala versions in tests now, while Scala 2.13.14 is not yet published.
Can I rely that this artifact won't be removed from the Artifactory?
> Scala version 2.13.14-bin-ed3dfc9-SNAPSHOT on resolver https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots if that helps?

**Comment by lrytz** [comment]
We clean up old (> 2 years) artifacts there from time to time.

**Comment by unkarjedy** [comment]
That suites us.
The version will be updated to 2.13.14 once it's released

**Pull request merged**
