### PR TITLE
Avoid spurious warning for `def foo = x.foo`.

### PR DESCRIPTION
**Pull request by retronym**
Followup to SI-6276 (#1275)

Review by @paulp, and by checking the build logs on Jenkins to ensure the new warning isn't issued spuriously any more.

### CODE REVIEW

**Comment by gkossakowski** [comment]
I was about to revert #1275 but I'll put this on hold if this fixes the problem @paulp discovered.

**Comment by retronym** [comment]
The build log is free from the spurious error.

**Comment by paulp** [comment]
Spurious Error has Left the Buildlog! LGTM.

**Comment by gkossakowski** [comment]
Cool, thanks for quick follow up! Merging.

**Pull request merged**
