### PR TITLE
Fix raw string interpolator

### PR DESCRIPTION
**Pull request by julienrf**

### CODE REVIEW

**Comment by paulp** [comment]
This commit message is insufficient.

**Comment by julienrf** [comment]
Hi Paul, I updated the commit message, let me know if it’s still insufficient.

**Comment by jsuereth** [comment]
OK this lgtm

**Comment by julienrf** [comment]
Just for information, why has this pull request been closed? I know that’s not an important bug and the fix is very simple but according to the current sources [the bug is still here](https://github.com/scala/scala/blob/master/src/library/scala/StringContext.scala#L59-69).

**Comment by paulp** [comment]
I'm sorry, that has to have been a mis-click.  With no comment, I can only have meant to merge it.

**Pull request merged**
