### PR TITLE
SI-9223: Use super.m only if by-name like me

### PR DESCRIPTION
**Pull request by som-snytt**
Superaccessors should not rewrite captured class parameter
to super.field if parameter is by-name but super.field is not.

### CODE REVIEW

**Comment by som-snytt** [comment]
Caused by: java.net.URISyntaxException: Illegal character in path at index 52: http://private-repo.typesafe.com/typesafe/ide-Select a Scala profile/org/scala-lang/scala-library/2.10.5-SNAPSHOT/scala-library-2.10.5-SNAPSHOT.pom

**Comment by som-snytt** [comment]
Fixed upstream. https://github.com/scala/scala/pull/4388

**Comment by retronym** [comment]
Sorry I missed this. The original bug report arrived back in my inbox on a boomerang while watching a talk at Scala Days, so given your minimization I took the chance to feel productive for a moment or two.

**Comment by som-snytt** [comment]
@retronym Wait, then why did you at-sign me to review your PR? I thought you were helping me get some education.

But this does confirm my suspicion that you fix bugs while watching talks. Also, I couldn't figure out from recent PRs what timezone you were in. Sorry I missed you at Fort Mason.

I commented on https://issues.scala-lang.org/browse/SI-5543 ...

**Comment by retronym** [comment]
> @retronym Wait, then why did you at-sign me to review your PR? I thought you were helping me get some education.

I noticed after submitting the PR that you had self-assigned the ticket and figured you'd been exploring the same murky waters of param aliasing.

**Comment by retronym** [comment]
> I commented on https://issues.scala-lang.org/browse/SI-5543 ...

:smile:

**Comment by retronym** [comment]
> Sorry I missed you at Fort Mason.

Next time...

Until then, I'll [ponder](http://www.wired.com/2012/09/so-if-designs-no-longer-the-killer-differentiator-what-is/):

> In other words, an artist is truly in it for themselves – not just for reasons of wanting to get rich, or get famous, or find a path to comfort. The artist needs to understand the truth that lies at the bottom of an enigma

**Pull request closed without merging**
