### PR TITLE
Modularized scaladoc and presentation compiler.

### PR DESCRIPTION
**Pull request by paulp**
They are now separately built targets and are not privileged from the standpoint of the rest of the compiler. There is no change to build products: they are still bundlled into scala-compiler.jar, but it would now be easy to create a scaladoc.jar and an interactive.jar should we be so inclined.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm, @dragos, @VladUreche

**Comment by adriaanm** [comment]
I'll go take away the kitten's ball of yarn and put it to work. the rebuild command should never be necessary

**Comment by VladUreche** [comment]
CC @vigdorchik

**Comment by VladUreche** [comment]
I will probably have a thorough look at this on Friday, until then I'm fully booked.

**Comment by paulp** [comment]
Oh good, the stability test. Now I really start paying for the inept ant build.

**Comment by paulp** [comment]
There are no change to these commits since the previous push, except I removed the last one (the one which made the stability test pass in the last commit) and rebased on top of #2209, which I hope will let all of them pass.

**Comment by dragos** [comment]
It will take us some time to get the IDE on top of this (not necessarily because of the changes here, but the 2.11 branch broke some code in scala-refactoring too). @huitseeker is on it, and I hope I can put some time tomorrow into it.

**Comment by adriaanm** [comment]
Awesome. Thanks, guys! We are under some time pressure for 2.11.0-M2, which
is supposed to be tagged on Monday. I realize this is cutting it a bit
fine. Just wanted you to be aware. Progress here greatly appreciated! Also,
happy to help.

**Comment by adriaanm** [comment]
I've verified that the IDE builds after merging this PR and #2216. I had to skip the tests, though, as they seemed to run out of memory/hang. Not sure why that is, but I don't think we should let that stop us from merging this PR.

I also verified that the stability tests pass for all commits once `tools/stability-test.sh` is changed along the lines of:

```
+for dir in library reflect compiler; do
+  # feel free to replace by a more elegant approach -- don't know how
+  if diff -rw -x '*.css' \
+              -x '*.custom' \
+              -x '*.gif' \
+              -x '*.js' \
+              -x '*.layout' \
+              -x '*.png' \
+              -x '*.properties' \
+              -x '*.tmpl' \
+              -x '*.tooltip' \
+              -x '*.txt' \
+              -x '*.xml' \
+              build/{quick,strap}/classes/$dir
+  then
```

I then foolishly proceeded to trying to fix the test/presentation/doc failure in ed57fbf and 4526490 (fixed in ff6d503). I  now think this is doomed. The clean separation in ed57fbf and 4526490 of the refactoring seems preferable to squashing all of the above three, which is the only way I see to fix that test (as it's an integration test of scaladoc and the presentation compiler).

**Comment by paulp** [comment]
How about moving the test into pending for three commits.

**Comment by adriaanm** [comment]
I dig it.

**Pull request closed without merging**
