### PR TITLE
Propsing a simple addition to collections API

### PR DESCRIPTION
**Pull request by hochgi**
I often find myself in need of a method like `groupWhile` (it similar in essence to `takeWhile`, and hence the name). so far I've written similar solutions using `foldLeft` or `span`, but it is less convinient to use.

### CODE REVIEW

**Comment by Ichoran** [comment]
The collections are going to stay mostly frozen for now.  You certainly can't add a new method to 2.11 since that would break binary compatibility.  But although this is a fairly common method, we're not going to add it now.  (Eventually there will be a more major reworking of the collections library, but probably not until 2.13.)

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@fccaad7fe43b9512ea1c3208e8ee6948c57baa90

**Comment by lrytz** [comment]
Closing this. @Ichoran do we have a list / document where we collect features that we'd like to have in the library for 2.13?

**Comment by Ichoran** [comment]
@lrytz - We do not, and it would be a good idea to have one.  This change in particular won't be forgotten by me, anyway, since I have it in my own collections extensions library.

**Comment by jozic** [comment]
don't also forget about `distinctBy` and `foldLeftWhile`. maybe some others from here https://github.com/jozic/scalax-collection as well

**Comment by lrytz** [comment]
I created https://issues.scala-lang.org/browse/SI-8958 for now

**Pull request closed without merging**
