### PR TITLE
SI-6780 Better handling of cycles in in-scope implicit search

### PR DESCRIPTION
**Pull request by retronym**
Implicit searches in the body of implicit members with inferred
types were leading to cycles. Before we used to resolve that
by saying there were no implicits in scope at all; now we just
skip the current context and still include the enclosing implicits.
Care is taken not to cache results under these circumstances.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
failure was due to github connection fail on jenkins, funnily enough, the flow plugin erroneously picks up the manual rebuild i did for pr-scala-integrate-ide

**Comment by adriaanm** [comment]
this failure can be ignored -- clicking on the "x" build status for 110fde0 shows it's fine

**Comment by adriaanm** [comment]
LGTM, though in principle I'd like us to disincentive implicits without return types by making them more buggy, not less :-)

**Pull request merged**
