### PR TITLE
[backport] 7768 completed future is not blocking

### PR DESCRIPTION
**Pull request by som-snytt**

### CODE REVIEW

**Comment by SethTisue** [comment]
prompted by https://github.com/scala/bug/issues/11903; unknown if it's actually connected

**Review by viktorklang — APPROVED** [review]
LGTM!

**Review by dwijnand — APPROVED** [review]
Sure

**Comment by SethTisue** [comment]
(as with other 2.12.x PRs right now, let's merge after cutting 2.12.11)

**Pull request merged**
