### PR TITLE
Add a request to presentation compiler to fetch doc comment information.

### PR DESCRIPTION
**Pull request by vigdorchik**
Refactor scaladoc base functionality to allow it to be mixed in with Global in the IDE.
Review by @dragos.

### CODE REVIEW

**Comment by dragos** [comment]
Looks good to me, except that we need to hook this new request in the _pickler_ library. The Presentation compiler uses "event-sourcing", and each request can be logged and replayed. The code is in [Picklers.scala](https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/interactive/Picklers.scala#L161).

**Comment by dragos** [comment]
Sorry, I have no idea how I could miss that. LGTM

**Comment by adriaanm** [comment]
In the future, please open a JIRA ticket to help us track the work, indicating a fix-by version and a priority.

**Pull request merged**
