### PR TITLE
Align copyright years

### PR DESCRIPTION
**Pull request by catull**
This PR addresses https://issues.scala-lang.org/browse/SI-6903 to align the copyright years to 2013.

### CODE REVIEW

**Comment by heathermiller** [comment]
Hi, thanks for the update. One issue though- most of those files are automatically generated by [genprod.scala](https://github.com/scala/scala/blob/master/src/build/genprod.scala), so many of these files need not be manually updated by hand, for those that are generated by genprod, only genprod would need to be updated (and genprod would need to re-generate all of those files).

@paulp or @jsuereth can likely confirm. But I'd imagine they'd want that update (as well as a signed CLA) before being able to merge this.

**Comment by xeno-by** [comment]
Btw copyright years at docs.scala-lang.org are off as well

**Comment by heathermiller** [comment]
Good point, Eugene. Fixed.

**Comment by catull** [comment]
I have a signed CLA from August last year.
Do you want me to forward it to you ?

**Comment by heathermiller** [comment]
If you've already signed it, then no-need to forward, we've got it on file. :-)

**Comment by adriaanm** [comment]
Thanks, @catull!

**Pull request merged**
