### PR TITLE
Corrects positions for Dynamic calls

### PR DESCRIPTION
**Pull request by retronym**
Rebase of #3190 to make it work with 2.10.x
- update `pointOrEnd` to work with both `Range`\- and `OffsetPosition`s
- update checkfiles for unrelated position differences between master and 2.10.x

We'll have to update the checkfiles when we merge to master. We can
also switch back to using `point`.

Review by @sschaef

### CODE REVIEW

**Comment by retronym** [comment]
Supercedes #3190

**Comment by adriaanm** [comment]
For non-trivial backports, please also submit a PR that merges 2.10.x into master with these fixes.

**Comment by kiritsuku** [comment]
Ok, now I see why I didn't get any failures. I aliased partest to my Scala master repo and not to 2.10.x. Sorry for that silly mistake.

LGTM

**Comment by retronym** [comment]
Don't apologize, that's an easy mistake to make. 

My setup is:

```
alias pt='test/partest'
alias pta='tools/partest-ack'
```

If you haven't tried `partest-ack` yet, give it a shot.

```
% pta dynamic  // all tests in files/folders with "dynamic" in the in the name, or with that text in the test/checkfile.
```

Thanks for getting all of these positions in order. I'm sure that @sjrd will be pleased as scala-js code uses `Dynamic` to interop with JavaScript.

**Comment by kiritsuku** [comment]
`pta` is nice, thanks!

**Pull request merged**
