### PR TITLE
Small Predef cleanup

### PR DESCRIPTION
**Pull request by adriaanm**
Rebased and improved #3553's fix for SI-8229.
Also rename Predef.conforms to Predef.$conforms so it can't accidentally be shadowed.

### CODE REVIEW

**Comment by adriaanm** [comment]
Would've liked to resuscitate more of #3217, but running out of time.

**Comment by adriaanm** [comment]
Another good example why we should've enforced binary compatibility for M8 and RC1.

**Comment by Alefas** [comment]
@retronym Just did it, thank you!

**Comment by retronym** [comment]
@adriaanm SBT 0.13 branch now fails because the following no longer hides the implicit:

main/actions/src/main/scala/sbt/CacheIvy.scala

```
    import Predef.{conforms => _, _}
```

Leading to:

```
[info] [info] Done updating.
[info] [info] Compiling 11 Scala sources to /localhome/jenkinsdbuild/workspace/Community-2.11.x-retronym/dbuild-0.7.1-M1/target-0.7.1-M1/project-builds/sbt-08b0b93c78203457815ae167510ed37c8496f3c8/main/actions/target/classes...
[info] [error] /localhome/jenkinsdbuild/workspace/Community-2.11.x-retronym/dbuild-0.7.1-M1/target-0.7.1-M1/project-builds/sbt-08b0b93c78203457815ae167510ed37c8496f3c8/main/actions/src/main/scala/sbt/CacheIvy.scala:109: ambiguous implicit values:
[info] [error]  both method $conforms in object Predef of type [A]=> <:<[A,A]
[info] [error]  and method inlineIvyToHL in object L5 of type => sbt.InlineIvyConfiguration => sbt.Types.:+:[sbt.IvyPaths,sbt.Types.:+:[Seq[sbt.Resolver],sbt.Types.:+:[Seq[sbt.Resolver],sbt.Types.:+:[Seq[sbt.ModuleConfiguration],sbt.Types.:+:[Boolean,sbt.Types.:+:[Seq[String],sbt.HNil]]]]]]
[info] [error]  match expected type I => J
[info] [error]  implicit def inlineIvyIC: InputCache[InlineIvyConfiguration] = wrapIn
[info] [error]                                                                 ^
```

**Comment by retronym** [comment]
Suggestion: change SBT in a source compatible way to instead opt-in to the parts of Predef it wants:

```
import Predef.{println, implicitly}
```

If that is the first import in the compilation unit, it will also disable `import Predef._`.

**Comment by adriaanm** [comment]
Will do. A good entry for style guide on how to shadow robustly.

**Comment by retronym** [comment]
@adriaanm https://github.com/sbt/sbt/pull/1135

**Pull request merged**
