### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by asakaev**

### CODE REVIEW

**Comment by asakaev** [comment]
Signed CLA.

**Review by NthPortal — COMMENTED** [review]
LGTM, but I am not really an expert on what the spec ought to look like.

Additionally, I don't know how others feel about formatting-only changes (due to the history changes). I think it's an improvement, but I can't speak for others.

**Review by dwijnand — APPROVED** [review]
I like it too.

**Comment by SethTisue** [comment]
hello @asakaev, and welcome!

we're generally cautious about accepting reformatting PRs like this one, unless the old formatting was definitely wrong and misleading, since such changes clutter up the version control history and cause merge conflicts.

writing by-name parameters in Scala as `=>T`, without the space, is fairly common (that's my informal impression, anyway) and neither clearly wrong nor definitely misleading

on the other hand, I did a little survey and it does seem that we're usually consistent about including the space:

```
~/dotty % git grep ': => A' | wc -l
     115
~/dotty % git grep ': =>A' | wc -l 
      14
~/dotty % git grep ': => T' | wc -l
     194
~/dotty % git grep ': =>T' | wc -l 
      20

~/scala.213 % git grep ': => A' | wc -l
     206
~/scala.213 % git grep ': =>A' | wc -l 
      16
~/scala.213 % git grep ': =>T' | wc -l
      25
~/scala.213 % git grep ': =>T ' | wc -l
       0

~/akka % git grep ': => A' | wc -l
      20
~/akka % git grep ': =>A' | wc -l
       0
~/akka % git grep ': => T' | wc -l
      65
~/akka % git grep ': =>T' | wc -l
       0
```

note that the akka repo uses scalafmt to enforce consistency, so apparently scalafmt uses the space as well.

on the balance, I think we could probably accept this, but let's wait and see what @adriaanm thinks

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
Thanks @asakaev!

**Pull request merged**
