### PR TITLE
Inliner for GenBCode

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
A [build with `-Ybackend:GenBCode -Yopt:l:classpath -Ydelambdafy:method`](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1375/consoleFull) (also used for partest) passed the test suite and stability.

**Comment by lrytz** [comment]
Note that the following warnings in the build log are not related to my the inliner commits, I will fix them soon in a separate PR:

```
[locker.library] /localhome/jenkins/a/workspace/scala-checkin-manual/src/library/scala/collection/parallel/immutable/package.scala:33: warning: Class scala.collection.parallel.immutable.Repetition$ParIterator$lambda$$psplit$2 differs only in case from scala.collection.parallel.immutable.Repetition$ParIterator$lambda$$psplit$2. Such classes will overwrite one another on case-insensitive filesystems.
[locker.library]         for ((start, end) <- incr.init zip incr.tail) yield new ParIterator(i + start, (i + end) min until, elem)
[locker.library]                           ^
```

**Comment by gkossakowski** [comment]
Have you considered running this through community build?

**Comment by lrytz** [comment]
right, i wanted to do that. can i use https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/ ?

**Comment by gkossakowski** [comment]
Yes, use build with parameters and point it at your branch of Scala. There's `scalac_opts`env variable where you can pass custom options.

**Comment by lrytz** [comment]
ok, thanks. in the meantime, review by ... [drumroll] ... @gkossakowski :)

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@2ede7944aafeb98d70c802032bb5c391c6dc830e

**Comment by lrytz** [comment]
[community build](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/124/) passed

**Comment by gkossakowski** [comment]
FYI: I provided all feedback I had for this PR.

**Comment by lrytz** [comment]
i close this one and create a new one for the new kitty

**Pull request closed without merging**
