### PR TITLE
Tweak deprecation messages for Ordering[{Float,Double}]

### PR DESCRIPTION
**Pull request by NthPortal**
Followup to [this comment](https://github.com/scala/scala/pull/6410#issuecomment-395309658). Sorry it took so long @dwijnand.

### CODE REVIEW

**Review by lrytz — COMMENTED** [review]
Thank you :)

**Comment by dwijnand** [comment]
No worries, thanks @NthPortal :)

**Comment by som-snytt** [comment]
Just wanted to say, I think it's great we're using gender-neutral singular-their.

The other way to order doubles is just to say, Make mine a double, and my friend'll have the same.

I forgot to ask if I followed the instructions correctly:

https://github.com/scala/scala/pull/8219/files#diff-91e1dcaa2b97f51d359c32d0ec8c36e0R30

It did actually take me a couple of tries to find the aforementioned antecedent. I went to Ordering, scrolled down, hit the bottom, tried the deprecated thing, then TotalOrdering, then known subclasses.

In Ordering, there are a bunch of traits for FooOrdering, so you skim that, nothing says Double, then the value members are not in alphabetical order, they start with Option, I didn't see Double snuck in further down in the middle.

If you're unhappy enough to write "double" in the search, Double is a member of Ordering way down in the right hand side, but not actually discoverable.

Revisiting the message text, and adding line breaks:
```
scala> implicitly[Ordering[Double]]
                 ^
       warning: object DeprecatedDoubleOrdering in object Ordering is deprecated
(since 2.13.0): There are multiple ways to order Doubles (Ordering.Double.TotalOrdering,
Ordering.Double.IeeeOrdering). Specify one by using a local import, assigning an implicit 
val, or passing it explicitly. See the documentation for details.
res0: Ordering[Double] = scala.math.Ordering$DeprecatedDoubleOrdering$@793d163b

scala> implicitly[Ordering[Double]]
                 ^
       warning: object DeprecatedDoubleOrdering in object Ordering is deprecated 
(since 2.13.0): Use either Ordering.Double.TotalOrdering or Ordering.Double.IeeeOrdering. 
See the documentation for Ordering.Double. Example usage: import Ordering.Double.TotalOrdering
```
I don't know if that's better, but I'm running a test at the office that takes a while to finish. My suggestion is to put the overview explanation on Double, then repeat the differences on each flavor: Next time I run my test, I'll do a quickie PR in case it does navigate more easily.

**Comment by NthPortal** [comment]
I also really like singular "their", but in this case it was referring to `TotalOrdering` and `IeeeOrdering`, which is plural.

**Pull request merged**
