### PR TITLE
SI-1118, finally.  Comments welcome!

### PR DESCRIPTION
**Pull request by acruise**

### CODE REVIEW

**Comment by acruise** [comment]
Dammit, I missed another change-the-whole-file diff, hang on...

**Comment by acruise** [comment]
Hmm, Github shows 5ea83bc as changing the whole file (presumably due to line endings), but when I look at it in IDEA it looks like just a small change.  Is it OK to pull as-is, or should I rewrite the affected commits?

**Comment by acruise** [comment]
I'll reopen for now until I hear back about 5ea83bc, sorry for the churn.

**Comment by soc** [comment]
On some related style fixes: It might sense to squash these commits into a single one probably.

**Pull request merged**
