### PR TITLE
Scala 3.1.2-RC1 (was 3.1.1-RC2)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
@bishabosha is the TASTy version in the comment still accurate?

and should we be going to 3.1.2-RC1 instead, actually?

**Comment by bishabosha** [comment]
> is the TASTy version in the comment still accurate?

yes that's right the tasty version remains the same - I made this script for convenience to check tasty versions - https://gist.github.com/bishabosha/0fa57393b034be23f5f9119b78f0b1ba

> and should we be going to 3.1.2-RC1 instead, actually?

The tasty version should remain the same within a minor version for RCs, it could be useful to always stay up to date if a sneaky regression gets added.

**Comment by SethTisue** [comment]
@bishabosha ha, well, so, I went to 3.1.2-RC1 and there's a failure. mind taking a look? probably just needs a small adjustment?

**Comment by bishabosha** [comment]
ok so it looks like there is just a new typing rule in Scala 3 that `erased` definitions can't be `Nothing`, so that would require updating the tests
Edit: I've added them

**Comment by SethTisue** [comment]
Thanks Jamie!

**Pull request merged**
