### PR TITLE
bump versions.properties now that 2.12.0-M2 is out

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by adriaanm** [comment]
/rebuild now that starr should be on maven

**Comment by adriaanm** [comment]
/rebuild

Now that starr should be on maven

**Comment by SethTisue** [comment]
do we have to wait for @rickynils to publish ScalaCheck for M2?

**Comment by adriaanm** [comment]
Ah, yes indeed.

**Comment by rickynils** [comment]
@SethTisue @adriaanm I've published ScalaCheck 1.11.6 and 1.12.4 for M2 now.

**Comment by lrytz** [comment]
thanks, @rickynils! the artifacts seem to be there: https://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.12.0-M2/

@SethTisue, maybe squash the two commits and `push -f`?

**Comment by SethTisue** [comment]
Squashed. I'll merge if Jenkins passes.

**Comment by adriaanm** [comment]
Thanks, @rickynils!

**Comment by SethTisue** [comment]
without @rickynils the whole house of cards collapses :-)

**Pull request merged**
