### PR TITLE
SI-8376 Fix overload resolution with Java varargs

### PR DESCRIPTION
**Pull request by retronym**
When comparing specificity of two vararg `MethodTypes`, `isAsSpecific`
gets to:

```
  case mt @ MethodType(_, _) if bothAreVarargs =>
    checkIsApplicable(mt.paramTypes mapConserve repeatedToSingle)
```

The formal parameter type of a Java varargs parameter is represented
as `tq"${defintions.JavaRepeatedParamClass}[$elemTp]"`. For a Scala
repeated parameter, we instead use `defintions.RepeatedParamClass`.

`bothAreVarargs` detects `JavaRepeatedParamClass`, by virtue of:

```
def isRepeatedParamType(tp: Type)      = isScalaRepeatedParamType(tp) || isJavaRepeatedParamType(tp)
```

But, `repeatedToSingle` only considers `RepeatedParamClass`.

This bug was ostensibly masked in 2.10.3, but became apparent after
a not-quite-refactoring in 0fe56b9770. It would be good to pin that
change down to a particular line, but I haven't managed that yet.

Review by @adriaanm / @gkossakowski.

I'll look at 0fe56b9770 a bit more tomorrow to try to explain why this
ever worked in to 2.10.3.

### CODE REVIEW

**Comment by retronym** [comment]
I've also thrown in a fix for type printing of Java varargs parameter types.

**Comment by retronym** [comment]
Discussion about the point of regression: https://github.com/scala/scala/commit/0fe56b9770331d258cc71b609af343e02be3f65f#commitcomment-5622115

**Comment by adriaanm** [comment]
LGTM, any further thoughts on the 2.10.3 side of the story?

**Comment by retronym** [comment]
Here's the material change: https://github.com/scala/scala/commit/0fe56b9770331d258cc71b609af343e02be3f65f#commitcomment-5649439

**Comment by adriaanm** [comment]
Great!

**Pull request merged**
