### PR TITLE
Trivial refactoring of scala / actors

### PR DESCRIPTION
**Pull request by jxcoder**
Updated versions from 2013 to 2015.
Removed empty lines at the end of file.

### CODE REVIEW

**Comment by jxcoder** [comment]
@VladUreche, is this not bad?

**Comment by VladUreche** [comment]
LGTM, but the actors should be reviewed by @vjovanov and/or @phaller.

**Comment by Ichoran** [comment]
We aren't updating copyrights by hand any more.  Firstly, if all you do is update the copyright (or, arguably, pointless whitespace), you don't _actually_ extend your copyright by law.  Secondly, things get forgotten.  The plan is to automate the process.  See https://github.com/scala/scala/pull/4184#issuecomment-65838186

**Comment by VladUreche** [comment]
@Ichoran thanks for the explanation. In this case I'll close the PR and ping @gkossakowski to add my `+1` to the automating idea.

**Comment by jxcoder** [comment]
Ok, thanks! It must be automatic)

**Pull request closed without merging**
