### PR TITLE
Support methodHandle / invokeDynamic constant pool entries in scalap

### PR DESCRIPTION
**Pull request by lrytz**
Add support in scalap to parse new constant pool entries
- MethodHandle
- MethodType
- InvokeDynamic

Spec: https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html

### CODE REVIEW

**Comment by lrytz** [comment]
review by @adriaanm

**Comment by adriaanm** [comment]
LGTM!  (ah, combinator parsers :neckbeard:)

**Comment by lrytz** [comment]
copypastor parsers for me :)

**Comment by adriaanm** [comment]
:smile_cat:

**Pull request merged**
