### PR TITLE
Migration improvements

### PR DESCRIPTION
**Pull request by soc**
Don't show migration messages from 2.7 for people needing migration
advice for their 2.9 -> 2.10 move, but keep all the information
for developers needing it.

Xmigration accepts a specific version like -Xmigration:2.8 now.
This will show only migration warnings since that version.

Default for -Xmigration is "2.9".

Adjusted tests, added some new. All tests pass.

Fixes SI-4990.

### CODE REVIEW

**Comment by soc** [comment]
Let me know if this needs adjustments, please.

**Comment by paulp** [comment]
Although I know the distribution has many of them, "catch _ => ..." is unacceptable.  I'll try to incorporate this patch, I just haven't done it because I want to do something different wrt versions and I have no time.

**Comment by adriaanm** [comment]
It'd be great if you could rework this patch to incorporate Paul's feedback and submit a new pull request. Thanks!

**Comment by soc** [comment]
@adriaanm Ok, will do that. I assumed from Paul's comments that he intended to change the things regarding the versions himself.
One problem without solution (currently) is how to make third-party users usages of migration annotation work. If, for example the version of some third-party lib adds an annotation with version "1.5", it won't be shown anymore, because the compiler only knows his own version numbers.

So either we have to specify that library writers should use the Scala version they target instead of their own library version (which doesn't make that much sense) or we need some way to differentiate between "Scala version numbers" and "other version numbers", so that the hiding only affects the Scala version numbers.

Any idea or suggestion?

**Pull request closed without merging**
