### PR TITLE
don't deprecate Either.left and Either.right yet

### PR DESCRIPTION
**Pull request by SethTisue**
as per https://github.com/scala/scala/pull/5135

review by @szeiger, @Ichoran, @soc, community.  (this will likely be
merged rapidly, but that doesn't mean additional changes, e.g. to the
Scaladoc, can't follow)

### CODE REVIEW

**Review by szeiger — APPROVED** [review]
I don't agree with the premise that source compatibility between two releases implies being able to build without warnings on both, but I'm in no hurry to deprecate these methods.

**Comment by SethTisue** [comment]
> I don't agree with the premise that source compatibility between two releases implies being able to build without warnings on both

noted. in the general case, I agree.

**Comment by Ichoran** [comment]
LGTM

**Comment by adriaanm** [comment]
I'm going to ignore the spurious test failures and merge this.

**Pull request merged**
