### PR TITLE
Improve tests for productElementName

### PR DESCRIPTION
**Pull request by som-snytt**

### CODE REVIEW

**Comment by lrytz** [comment]
This is an alternative to https://github.com/scala/scala/pull/9644 and fixes the related issue?

**Comment by som-snytt** [comment]
Yes, but I wanted to give the other PR a chance before following up. Investing in the process, including the learning process.

Thanks for improving my other PR, I almost added that comment and then ran out of energy, as it was a refactor too far.

**Comment by SethTisue** [comment]
@som-snytt #9644 is merged; should we just close this one, or is there something remaining her you want to keep?

**Comment by som-snytt** [comment]
This is absolutely a blocker and needs to get in ASAP. "Fix exception message from productElementName " and better tests!

**Pull request merged**
