### PR TITLE
release script for 2.12.0-M0

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
I created a temporary jenkins job (just in the UI, i guess it will disappear when we re-load the config): https://scala-ci.typesafe.com/job/release-2.12.0-M0/10/consoleFull

Review by @adriaanm

**Comment by adriaanm** [comment]
Could we use the same script (and the same jobs) instead of creating a new one, tag M0, then revert changes?

**Comment by lrytz** [comment]
It would take a number of changes to the main bootstrap script to prevent it from doing anything with modules. Once we have the first version of everything, it makes sense to adapt the bootstrap script to work on both 2.11 and 2.12, but for this one-time release I think the pragmatic solution saves time.

**Comment by adriaanm** [comment]
Ok!

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
