### PR TITLE
SI-7445 element order of ListMap.iterator should be reversed

### PR DESCRIPTION
**Pull request by ihji**
Since the underlying collection of ListMap is indeed a List,
order-related methods of ListMap should respect the order
of elements in the underlying List.

Since the underlying List of ListMap stores elements in a
reversed input order (i.e. LIFO), it is natural that
ListMap.iterator also returns elements in the same order.

### CODE REVIEW

**Comment by ihji** [comment]
Review by @paulp

**Comment by paulp** [comment]
It's not clear to me that this is the way forward. For sure, if I create an ordered collection like so

```
scala.collection.immutable.ListMap(1 -> 1, 2 -> 2, 3 -> 3, 4 -> 4)
```

I don't think it's reasonable to expect that the order is 4,3,2,1, regardless of whether the collection has "List" in its name. And hey, List itself is ordered, so let's see what it does:

```
scala> List(1, 2, 3, 4)
res5: List[Int] = List(1, 2, 3, 4)
```

Well yeah! Kind of difficult to imagine otherwise, yes?

If you still think this is a good way to go, can you raise the issue up on scala-debate or list of your choice? Thanks, closing for now.

**Comment by ihji** [comment]
@paulp Actually, this commit just suggests consistent behaviour between `immutable.ListMap` and `mutable.ListMap`. `mutable.ListMap` already works like that:

```
scala> val x = collection.immutable.ListMap(1->1,2->2,3->3)
x: scala.collection.immutable.ListMap[Int,Int] = Map(3 -> 3, 2 -> 2, 1 -> 1)

scala> val y = collection.mutable.ListMap(1->1,2->2,3->3)
y: scala.collection.mutable.ListMap[Int,Int] = Map(3 -> 3, 1 -> 1, 2 -> 2)

scala> (x.head, y.head)
res10: ((Int, Int), (Int, Int)) = ((3,3),(3,3))

scala> (x.tail.head, y.tail.head)
res11: ((Int, Int), (Int, Int)) = ((2,2),(2,2))

scala> (x.tail.tail.head, y.tail.tail.head)
res12: ((Int, Int), (Int, Int)) = ((1,1),(1,1))
```

IMHO, users can easily catch up that ListMap works as LIFO because Map does not provide a method to choose where to put a new element (+:, :+) into the underlying List, so LIFO is the optimal way for ListMap to guarantee O(1) in `head` and `tail`.

Anyway, if you still think that this is a big change, I will raise the issue up on the mailing list.
Thanks for your comment! :smile:

**Comment by paulp** [comment]
I'd like to believe this behavior is something to emulate... I must have entered some truly dark corner of computer science. What is the data structure at work which would allow me to predict this output? I'm pretty sure it's not known as a LIFO.

```
scala> scala.collection.mutable.ListMap[Int, Int]() ++= (1 to 10) zip (1 to 10)
res0: scala.collection.mutable.ListMap[Int,Int] = Map(10 -> 10, 8 -> 8, 6 -> 6, 4 -> 4, 2 -> 2, 1 -> 1, 3 -> 3, 5 -> 5, 7 -> 7, 9 -> 9)

scala> res0 foreach println
(10,10)
(8,8)
(6,6)
(4,4)
(2,2)
(1,1)
(3,3)
(5,5)
(7,7)
(9,9)

scala> res0 drop 1 foreach println
(9,9)
(5,5)
(1,1)
(4,4)
(8,8)
(6,6)
(2,2)
(3,3)
(7,7)
```

**Comment by som-snytt** [comment]
ScalaPuzzlers is on the phone.

**Comment by ihji** [comment]
Interesting. `mutable.ListMap` does not preserve its order between operations! Changing `remove` to tailrec in  e36327ac fixed `StackOverFlow` exception, but it seems that we also lost the order preserving nature of `mutable.ListMap`.

**Pull request closed without merging**
