### PR TITLE
SI-8705   Added example to Option.contains method.

### PR DESCRIPTION
**Pull request by jxcoder**
I added code which described how to **Option.contains** method works.

``` scala
// Returns true because Some instance contains string "something" which equals "something".
Some("something") contains "something"

// Returns false because "something" != "anything".
Some("something") contains "anything"

// Returns false when method called on None.
None contains "anything"
```

[SI-8705](https://issues.scala-lang.org/browse/SI-8705)

### CODE REVIEW

**Comment by jxcoder** [comment]
@vladureche, @heathermiller what do you think about this pull request?

**Comment by VladUreche** [comment]
LGMT, but let's wait for @som-snytt to also have a look at it.

**Comment by som-snytt** [comment]
Is the text aligned correctly?  It should be on a two-column boundary. Scaladoc may compensate, but it's easier to read by people reading code, who are usually coders, if it lines up.

I think it looks like a flag on a flag pole.  (mnemonic)

```
/** An important method.
 *  It would be cool if they renamed `Some` to `Som`.
 */
```

I did notice some other comment text is not aligned.

**Comment by jxcoder** [comment]
@som-snytt, I don't understand. What do you want to say? I used // comments. Is it wrong?

**Comment by som-snytt** [comment]
I mean the code doc comment, and not the code-within-the-code-comment:

https://github.com/jxcoder/scala/blob/1e2a21681a4a55469faa59b07473a3b269e70258/src/library/scala/Option.scala#L225

There are two spaces between `*` and the aligned text.

Sorry, that makes me sound like a crazy person.  It's just so easy for editors and IDEs to align text these days, it seems silly not to do it.

Note that I am slightly justified because the IDE doesn't do scaladoc hovers (they say).  So people will wind up reading it directly.  I do know aligned text looks better in vim.

**Comment by jxcoder** [comment]
@som-snytt, look at my [new commit](https://github.com/jxcoder/scala/commit/e3311073bbad6f6f0dfdd3ea09628d324b4b3614), please.

**Comment by som-snytt** [comment]
Yes, that's what I meant, modulo the boy scout rule.

**Comment by jxcoder** [comment]
Ok. @VladUreche, Ready to merge?

**Comment by VladUreche** [comment]
@som-snytt: By "boy scout rule" you mean squashing the two commits? Or is there something else @jxcoder should do?

**Comment by som-snytt** [comment]
@VladUreche I would have reflexively corrected the indentation for the whole comment, but that is so nit-picky, it's not worth mentioning. Plus, there's also the white space rule of not correcting it.

**Comment by VladUreche** [comment]
> I would have reflexively corrected the indentation for the whole comment, but that is so nit-picky, it's not worth mentioning

I see. I don't know, is it very hard to fix? I don't have strong feelings about indentation, save for no tabs. @som-snytt?

> Plus, there's also the white space rule of not correcting it.

What do you mean?

**Comment by som-snytt** [comment]
You know, avoid white space changes because it makes history harder to see. Unless the commit is 'change tabs to spaces', etc.

**Comment by jxcoder** [comment]
@som-snytt, I don't understand. What should I do with my pull request. Can you specify concrete requirements?

**Comment by som-snytt** [comment]
It's fine with me.

**Comment by VladUreche** [comment]
Amen!

**Pull request merged**
