### PR TITLE
Reject `@throws` annotation except where specifically allowed (methods, constructors)

### LINKED ISSUE #12324: Class annotated with @throws produces invalid Bytecode (invalid class type signature in classfile)
## reproduction steps

Using Scala 2.13.3 and Java 11.

Compile the following class into a class-file:

```scala
@throws(classOf[IllegalArgumentException])
class ScalaClass[T](someList: List[T]) {
   throw new IllegalArgumentException("Boom!")
}
```

## problem

The generated classfile/bytecode contains a type signature for `ScalaClass`. This type signature contains a _ThrowsSignature_ although these are only permitted as part of _MethodSignature_: 
https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-4.html#jvms-4.7.9.1

This issue was discovered while working with ClassGraph to do bytecode analysis:
https://github.com/classgraph/classgraph/issues/495#issuecomment-768105884
You can read up on the details from the linked comment onwards.

At first we thought the type signature parser of ClassGraph was missing something, but we're confident that the bytecode generated by Scala is invalid. Later on in that issue you can see that `javac` even rejects the classfile generated by Scala due to it being invalid:
https://github.com/classgraph/classgraph/issues/495#issuecomment-768307245

Attached is a minimal Scala/Maven project that produces the said invalid classfile for the class mentioned above:
[ClassGraphMinimalExample.zip](https://github.com/scala/bug/files/5881407/ClassGraphMinimalExample.zip)

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12324

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Diff LGTM

**Review by SethTisue — APPROVED** [review]
took me a little diff-groveling to see that it boils down to adding:

```scala
 if (!sym.isMethod && !sym.isConstructor && sym.hasAnnotation(ThrowsClass))
           reporter.error(tree.pos, s"`@throws` only allowed for methods and constructors")
```

this seems as expected (after a little thought, anyway, in the case of `lazy val`):

```
scala> class C { @throws[Exception] def x = 3 }
class C

scala> class C { @throws[Exception] lazy val x = 3 }
class C

scala> class C { @throws[Exception] val x = 3 }
                                        ^
       error: `@throws` only allowed for methods and constructors

scala> class C { @throws[Exception] var x = 3 }
                                        ^
       error: `@throws` only allowed for methods and constructors
```

**Comment by som-snytt** [comment]
@SethTisue I was about to comment that except for refactor to method, that was the change. With the second commit, I also commented on whether accessor to lazy vals deserve a throws, but I didn't pursue it. I noticed that not all annotations survive to refchecks for checking. They could rename `RefChecks` to `Rejects`.

Also funky is the extra error in the test because the bad annotation is copied over to method result; but that caret points at the function name.

**Comment by SethTisue** [comment]
> Also funky is the extra error in the test because the bad annotation is copied over to method result; but that caret points at the function name.

heh, I did not notice that #eagleeyesomsnytt

**Comment by dwijnand** [comment]
> They could rename `RefChecks` to `Rejects`.

NonTypeChecks.

**Pull request merged**
