### PR TITLE
Deprecate numeric conversions that lose precision (e.g., Long to Double)

### PR DESCRIPTION
**Pull request by som-snytt**
Int to Float, Long to Float and Long to Double are dangerous conversions and should never be done automatically.

Example:

```
scala> (33554435: Float).toInt
res0: Int = 33554436
```

Rebase https://github.com/scala/scala/pull/7405 and use ordinary warning system.

### CODE REVIEW

**Comment by som-snytt** [comment]
Maybe escalate to error under `-Xsource:3`.

**Review by lrytz — APPROVED** [review]
Thank you, @smarter & @som-snytt

**Comment by som-snytt** [comment]
@lrytz thanks for improving the comment. `#lazy`

**Comment by lrytz** [comment]
Except that it actually doesn't warn on the example I put in the comment 😄 (logged at https://github.com/scala/bug/issues/10773#issuecomment-581402724)

**Comment by som-snytt** [comment]
```
[warn] /home/jenkins/workspace/scala-2.13.x-validate-main@2/src/library/scala/jdk/DoubleAccumulator.scala:110:27: Automatic conversion from Long to Double is deprecated (since 2.13.1) because it loses precision. Write `.toDouble` instead.
[warn]         x(x.length - 1) = pv
[warn]                           ^
[warn] /home/jenkins/workspace/scala-2.13.x-validate-main@2/src/library/scala/jdk/DoubleAccumulator.scala:119:27: Automatic conversion from Long to Double is deprecated (since 2.13.1) because it loses precision. Write `.toDouble` instead.
[warn]         x(x.length - 1) = pv
[warn]                           ^
```
@lrytz it's a long getting stuck in the data array.

Also demonstrates that, like the `equals` warning in RefChecks, it's in your face.

**Comment by Sciss** [comment]
Is there a compiler switch to turn the warning off?

**Comment by som-snytt** [comment]
@Sciss 
```
scala> def f(i: Int): Float = i
                              ^
       warning: Widening conversion from Int to Float is deprecated because it loses precision. Write `.toFloat` instead.
def f(i: Int): Float

scala> :replay -Wconf:cat=deprecation&msg=conversion:s
replay> def f(i: Int): Float = i
def f(i: Int): Float


scala> 
```

**Comment by SethTisue** [comment]
@Sciss `-Wconf`, https://github.com/scala/scala/pull/8373

**Comment by SethTisue** [comment]
@Sciss see https://github.com/scala/scala/pull/8373 for full details on `-Wconf`

**Comment by som-snytt** [comment]
I recommend your favorite beverage and armchair and `scalac -Wconf:help`.

**Comment by lrytz** [comment]
@som-snytt @SethTisue it's heart-warming to see you both get up in the morning and be thinking about `-Wconf`

**Pull request merged**
