### PR TITLE
Merge 2.10

### PR DESCRIPTION
**Pull request by adriaanm**
Intermediate steps:

```
g merge -s ours e350bd2 2bfe0e7
g merge 25bcba5
g merge -s ours 50c8b39
g merge 075f6f2 e09a8a2
g merge 6045a05 # update check file for presentation/completion-implicit-chained
g merge -s ours 2.10.x
```

### CODE REVIEW

**Comment by adriaanm** [comment]
I redid the merge and it looks ok. Sorry, @som-snytt, I still had to drop 25bcba59ce -- too much had shifted around.

**Comment by adriaanm** [comment]
The failed intermediate commits are in the history, but their content was omitted using -s ours, so as long as the last commit passes the tests, I think this is good to go.

Review by @retronym

**Comment by adriaanm** [comment]
Btw, if you'd like to redo the merge, the second time around I did:

```
g merge -s ours 2bfe0e797c -m"Noop merge of 2bfe0e797c into master."
g merge e6a5e692f5
g merge -s ours 05681d4def -m"Noop merge of 50c8b39ec4 into master."
g merge 66c4135942 0354d4bea7 -m"Merge 6045a05b83, e09a8a2b7f, 075f6f260c into master."
g co bd53838125 test/files/presentation/completion-implicit-chained.check
g co bd53838125 src/interactive/scala/tools/nsc/interactive/Global.scala
g commit
g merge -s ours 2.10.x
```

**Comment by retronym** [comment]
I'll take a closer look tomorrow. For now, here's what I like to add to merge PRs to justify the merge sequence:

```
  /code/scala export MB=`git merge-base origin/2.10.x origin/master`
  /code/scala git log --graph --oneline $MB...origin/2.10.x
*   732fd26 Merge pull request #3116 from retronym/topic/backport-character-ignore
|\  
| * 1d29c0a [backport] Add buildcharacter.properties to .gitignore.
|/  
*   4156498 Merge pull request #3109 from adriaanm/faster-build-2.10
|\  
| * 31ead67 IDE needs swing/actors/continuations
| * 852a947 Allow retrieving STARR from non-standard repo for PR validation
| * 40af1e0 Allow publishing only core (pr validation)
| * ba0718f Render relevant properties to buildcharacter.properties
* |   e057fa5 Merge pull request #3110 from xeno-by/topic/7776-backport
|\ \  
| * | d15ed08 [backport] SI-7776 post-erasure signature clashes are now macro-aware
* | |   0354d4b Merge pull request #3105 from retronym/ticket/completion
|\ \ \  
| |/ /  
|/| |   
| * | 6045a05 Fix completion after application with implicit arguments
* | |   79788af Merge pull request #3097 from paulp/issue/6546-for-210
|\ \ \  
| |_|/  
|/| |   
| * | 075f6f2 SI-6546 InnerClasses attribute refers to absent class
| |/  
* |   66c4135 Merge pull request #3102 from VladUreche/issue/4012
|\ \  
| |/  
|/|   
| * e09a8a2 SI-4012 Mixin and specialization work well
|/  
*   05681d4 Merge pull request #3072 from retronym/backport/7519
|\  
| * 50c8b39e SI-7519: Additional test case covering sbt/sbt#914
| * ce74bb0 [nomaster] SI-7519 Less brutal attribute resetting in adapt fallback
* |   daa8694 Merge pull request #3053 from som-snytt/issue/6026-AFCL-findresource
|\ \  
| * | e350bd2 [nomaster] SI-6026 backport getResource bug fix
|  /  
* |   9c10212 Merge pull request #3052 from som-snytt/issue/6026-javap-loading
|\ \  
| |/  
|/|   
| * 2bfe0e7 SI-6026 REPL checks for javap before tools.jar
* e6a5e69 Merge pull request #3065 from retronym/ticket/7295
* 25bcba5 SI-7295 Fix windows batch file with args containing parentheses
```

**Comment by som-snytt** [comment]
I did see a failure notice and looked at it, but it looked like a build context issue.  Personally, I reserve my supreme faith for our ability to refactor everything every six to twelve months thereby making history irrelevant.

**Comment by retronym** [comment]
LGTM. The only wrinkle I see is in `g merge 66c4135942 0354d4`, merging `0354d4b` would have the same effect as 66c4135942 is in its history. With this in mind I'll let you do one last check of the sequence, but feel free to pull the trigger.

**Comment by adriaanm** [comment]
Thanks, I noticed that redundancy on the second go, but decided not to push -f since I verified the diff between the PR and my verification was empty.

**Pull request merged**
