### PR TITLE
Add more permgen space for test/partest

### PR DESCRIPTION
**Pull request by khernyo**
Running "test/partest --all" needs about 108MB permgen space, but the
default is less than that (85MB for me on Oracle Java 6 with no extra
options).

This commit bumps it to 128MB.

### CODE REVIEW

**Comment by adriaanm** [comment]
jenkins job pr-scala-testsuite-linux-opt: successful -- manually verified

**Comment by adriaanm** [comment]
jenkins job pr-rangepos: successful -- manually verified

**Comment by paulp** [comment]
@khernyo Although we can probably let it slide on a commit of this size, can you please sign the [CLA](http://www.typesafe.com/contribute/cla)?

**Comment by jozic** [comment]
So if permgen starts with 85m and will definitely grow to 108m could you add -XX:PermSize=128M as well to avoid GC?

**Comment by khernyo** [comment]
I believe I have signed the CLA when I contributed to Akka a couple of months ago. ... I just realized that I changed my github username since then, so I signed it again now.

**Comment by khernyo** [comment]
The permgen will not always grow to 108m, only when (almost) all the tests are run. The scalacheck tests push it above the 85m limit but running the scalacheck tests alone still fits in that limit. Anyway, I guess it won't hurt too much to bump it to 128m.

**Comment by paulp** [comment]
And permgen won't "definitely" grow to 108m, because you don't have to run every test every time you run partest. You can run, for instance, one test.

**Comment by paulp** [comment]
This no longer merged, so superseded by #1983.

**Pull request closed without merging**
