### PR TITLE
SI-3755: catch exception thrown by adaptToNewrun

### PR DESCRIPTION
**Pull request by adriaanm**
someone who knows adaptToNewRun (@lrytz ?), please review
I just added a try/catch to mimic what the other cases were doing

it would be nice to have a test for this, but you'd need to involve the repl,
as I couldn't trigger it using multiple scalac runs

### CODE REVIEW

**Comment by lrytz** [comment]
I cannot give a qualified answer, but Hubert will have a look at it, he's more familiar with that code.

**Comment by hubertp** [comment]
So the MissingTypeControl exception was originally thrown to avoid crashing the compiler on an assert(false, ...) and recover from the situation gracefully by assuming that the symbol has been adapted. Although we longer care about the build manager, this may still influence the resident compiler (and presentation compiler?) since they use similar mechanism. It should be easier to create a test case with the resident compiler.
My commit is: 2bf84d21a63fb6e19, Sean's commit (he put the assert originally): 6d9e1774b9d543. I think it would be better to maybe fix the underlying issue, if possible, and get rid of MissingTypeControl in general.

**Comment by hubertp** [comment]
Also, if you want to have a test case for this one, it might be easier to do it with the resident compiler than with REPL.

**Comment by paulp** [comment]
FYI it's easy to "involve the repl" in a test, grep for ReplTest in
test/ for a few dozen examples.

On Fri, Apr 27, 2012 at 1:21 AM, Adriaan Moors
reply@reply.github.com
wrote:

> it would be nice to have a test for this, but you'd need to involve the repl,
> as I couldn't trigger it using multiple scalac runs

**Pull request merged**
