### PR TITLE
Change += to + in example for aggregate method

### PR DESCRIPTION
**Pull request by mmilewski**
Since Set used as accumulator is immutable, it does not have += method.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Hi @mmilewski. Sorry for the delay in response, we've been a bit busy.

I noticed that you didn't sign Scala CLA. Could you sign it here: http://typesafe.com/contribute/cla/scala ?
It's online process and takes only a minute.

**Comment by mmilewski** [comment]
Hi,
Signing is not a problem for me but I have to check with my employer just
in case. I hope it will not take too long...

Best regards,
Marcin

**Comment by adriaanm** [comment]
The failure can be ignored -- please let us know when you were able to sign the CLA (or if there's a problem with it, how we can address it.)

**Comment by gkossakowski** [comment]
@mmilewski: Did you have a chance to look into CLA signing?

**Comment by mmilewski** [comment]
Yes, I did and it is currently being processed by legal department. I hope
to have the results soon, but can't say what exactly 'soon' mean.

## 

Best regards / Pozdrawiam
Marcin Milewski

**Comment by som-snytt** [comment]
Github is smarter than me and decided my reply should go after the kitty's message that she took ... 865! mins to fail the build. What a lazy cat.  Is she going to turn into one of those cats who sit around getting fat so people say, Ooh, are you going to have kittens?  No, I'm not having kittens!

**Comment by gkossakowski** [comment]
@mmilewski, @som-snytt: what's the status of this PR?

**Comment by som-snytt** [comment]
This one-character PR inspired this SO answer.

http://stackoverflow.com/a/18341620/1296806

What do I know, but I think the proposed change is based on a misunderstanding.

(Eleven days ago I knew nothing at all.)

**Comment by gkossakowski** [comment]
@som-snytt: are you saying that this PR shouldn't be merged?

**Comment by som-snytt** [comment]
@gkossakowski It's OK. If Marcin says it's less confusing this way, I take his word for it.

**Comment by mmilewski** [comment]
A status is that I still wait for the final answer. I got a partial answer but it doesn't really help me. You know, I would like to have clear information what I can publish with and without company's agreement. Sorry it takes so long... This is the first time, after that all should be clear.

In the matter of the topic: I am ok with many forms of this example, but don't you think `Set` should be distinguished from `mutable.Set`? So that every time I see `Set` I know it is immutable. That said, any of example below is fine for me (I can live with `pc`):

```
pc.aggregate(Set[Int]())(_ + process(_), _ ++ _)
pc.aggregate(mutable.Set[Int]())(_ += process(_), _ ++ _)
```

**Comment by gkossakowski** [comment]
Given the fact that legal issues are not cleared up yet I'm rescheduling it for M6.

**Comment by gkossakowski** [comment]
@mmilewski: our PR queue is very crowded so I'll close it and I'll let you resubmit once legal issues are cleared up on your side. Thanks for understanding.

**Comment by mmilewski** [comment]
Sure, no problem.

Best regards,
Marcin

**Pull request closed without merging**
