### PR TITLE
Fixes SI-6521, overrides Range#head to be faster

### PR DESCRIPTION
**Pull request by JamesIry**
Backport of 63ba3d64a7002ef67f7f13083a18fe1042a3adba

### CODE REVIEW

**Comment by JamesIry** [comment]
review by @adriaanm

**Comment by adriaanm** [comment]
LGTM

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
Anybody know why the kitteh is ignoring this PR? @jsuereth ?

**Pull request merged**
