### PR TITLE
SI-7190 macros no longer give rise to bridges

### PR DESCRIPTION
**Pull request by xeno-by**
Amazingly enough, this got through all the testing we performed. But now
erasure knows that it shouldn't generate bridges for macro methods.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym @JamesIry

**Comment by paulp** [comment]
Is it amazing? Presumably nothing is ever going to call the bridge methods, so unless they're inherently malformed, I would expect them to be quiet passengers in the bytecode.

**Comment by xeno-by** [comment]
I remember a few remotely related bugs, when macros tried to produce extraneous synthetic members past typer and caused crashes. So it's quite surprising that we didn't catch this one for the entire year.

**Comment by axel22** [comment]
Does this mean that the compiler won't generate the version with the primitive return type, only the one with the boxed return type?

**Comment by xeno-by** [comment]
Macro methods shouldn't generate any bytecode at all, just symbol information in Scala pickles.

**Comment by axel22** [comment]
Ah, true, that should've been obvious, thanks.

**Comment by JamesIry** [comment]
LGTM

**Comment by retronym** [comment]
So we've got static forwarders and bridges, is there anything else? Have we tested macros defined in a value classes?

**Pull request merged**
