### PR TITLE
Bump starr to M7, along with module versions.

### PR DESCRIPTION
**Pull request by adriaanm**
Allow extra-repo to make it easier to test e.g.,
a staged scalacheck while releasing modules.

TODO: replace desired.sha1's with jars for M7 starr so it's consistent
alternatively, we could just remove them -- no intention of allowing unreleased starr again

what say you, @gkossakowski, @retronym, @jamesiry et al?

### CODE REVIEW

**Comment by gkossakowski** [comment]
@adriaanm: I'd remove desire.sha1's for STARR altogether.

When it comes to extra-repo, I see it's enabled by default. Why is it needed by default? Having extra repos slows down dependency resolution and in general we should be careful with repositories we depend on so we can maintain reproducible builds (e.g. being able to rebuild old scala revisions a year later).

**Comment by retronym** [comment]
I'm also happy to require a tagged, maven published release of the core rather for starr. In many cases the previous milestone should be enough, in rare cases we can do an internal release.

That's easy enough to experiment with locally now with the new publish-local ant targets, and the publish step is also largely automated.

**Comment by adriaanm** [comment]
@gkossakowski, the extra repo only kicks in if you set -Dextra.repo.url, which allows https://github.com/scala/scala-modules-build/blob/master/build.sh to add a staging repo for e.g., scalacheck before it's actually released, to ensure that we can build partest and run the test suite against it. So, this does not affect regular builds, nor release builds. IT is also used during PR validation.

**Comment by adriaanm** [comment]
I'll add a follow-up commit that removes the shas.

**Comment by gkossakowski** [comment]
@adriaanm: ok, thanks for clarification. I misread the diff. In that case, LGTM.

**Comment by adriaanm** [comment]
i'll open a separate PR to replace our starr infrastructure by a maven-based approach

**Comment by xeno-by** [comment]
@adriaanm Would be great if we could leave the infrastructure in place. Otherwise, getting custom starrs for scala forks would require customizations to the build.

**Comment by adriaanm** [comment]
It would not. The follow-up PR I said "replace by maven-based approach", which will be vastly simpler.
You just do ant publish-core-local with a custom version number, and change starr.version.number to ir.

**Pull request merged**
