### PR TITLE
SI-8167 readLine shold flush output before reading input

### PR DESCRIPTION
**Pull request by retronym**
As reported on scala-user:

> Using `scala.Predef.readLine(text: String, args: Any*)`
> on Windows causes strange behavior. If I am leaving some
> part of `text` unforced to be flushed (say, "---\nEnter new
>  expression >") then "Enter new expression >" flushed only
> after Enter press. Still, it works fine on Ubuntu and (seems like)
> on MacOS.
> 
> My workaround is to force `java.lang.System.out` (that readLine
> depends on to write welcome string) to flush output like
> "---\nEnter new expression >\n".

Review by @ichoran

### CODE REVIEW

**Comment by xeno-by** [comment]
Ping @Ichoran

**Comment by xeno-by** [comment]
@retronym this pull request needs a rebase

**Comment by Ichoran** [comment]
Content LGTM.  (But the rebase is still needed.)

**Comment by gkossakowski** [comment]
@retronym: do you want me to rebase it?

**Comment by retronym** [comment]
That would be wonderful. Haven't been able to pop() my stack back down to this one.

**Pull request closed without merging**
