### PR TITLE
Actually remove @bridge.

### PR DESCRIPTION
**Pull request by hrhino**
Follow-up to scala/scala#6268 / 1eb0fba.

Turns out that `rm src/library/scala/annotation/bridge.scala` isn't the entire story: `Namers` references `bridge` by name, and scaladoc uselessly checks `isBridge` (the compiler doesn't set this flag until `erasure`, when the generated bridges show up).

Removed one of the scaladoc tests which tested that this annotation didn't do more than it was supposed to.

Thanks @SethTisue for keeping me honest about this.

### CODE REVIEW

**Comment by hrhino** [comment]
/sync

(Scabot, Y u No Cooperate)?

**Comment by NthPortal** [comment]
This overlaps a bit with #6319. I removed the annotation, but I missed the spots in the compiler where it's referenced indirectly (as a string, or a method containing `bridge`).

**Comment by NthPortal** [comment]
Would you be okay with me cherry-picking this into #6319?

**Comment by hrhino** [comment]
Ah, yeah, so you did. I missed that somehow. I don't mind you cherry-picking this across. LMK if/when you do and I'll close this out. Nice PR, btw.

**Comment by NthPortal** [comment]
Thanks!

I've cherry-picked this across as 1b5429d

**Comment by hrhino** [comment]
👍 thanks!

**Comment by NthPortal** [comment]
I just noticed you originally removed `@bridge` from STARR, so thank you as well!

**Pull request closed without merging**
