### PR TITLE
SI-4950 Add tests, looks like it has been fixed earlier

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @retronym, please.

**Comment by retronym** [comment]
LGTM, thanks!

**Comment by soc** [comment]
_sigh_

```
-  ... 68 elided
+  ... 70 elided
```

What's the best way to make this more robust?

**Comment by lrytz** [comment]
override `show`: https://github.com/scala/scala/blob/2.11.x/src/partest-extras/scala/tools/partest/ReplTest.scala#L43

**Comment by soc** [comment]
@lrytz Thanks!

**Pull request merged**
