### PR TITLE
Changes Tree and Type members from vals to defs.

### PR DESCRIPTION
**Pull request by paulp**
Explanatory email:

The reflection API defines a great many abstract vals. I would
like these all to be defs. I'm sending a pull request to that end.

Reasons: for starters, they should default to being defs. It's a
decision to use vals for which one should have to supply reasons.
The reason for THAT is that defs can be implemented with vals, but
not vice versa.

Why does this matter? I can't find my long writing on the subject
of TypeRef. In short, we waste a huge amount of memory on its
fields, because given the way TypeRef is defined, each one demands
a pre, a sym, and an args. Except that somewhere between 1/3 and
1/2 have prefix "NoPrefix", and somewhere between 1/3 and 1/2 have
args "Nil". We know it at creation time, but we give every typeref
the whole field anyway.

At present there's no way to fix this which has acceptable
performance - i.e. custom subclasses save us lots of memory, but
are too much slower for having to use an extractor - but there's
no reason we should have to choose, and I fully expect to fix it
eventually. Let's not make that fix into a breaking change by
abstractly defining "pre" and "args" as field-requiring vals.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @xeno-by .

**Comment by xeno-by** [comment]
LGTM

@jsuereth What do you think about this?

**Comment by jsuereth** [comment]
If/when we decide to do an RC2, I can merge this.   I'm 100% for prefering def over val (see Scala In Depth).

The real question is if this change, alone, necessitates an RC2.   Since reflection is under no BC requirements, I don't think this constitutes an RC2 emergency until we know we need an RC2.   I'd say hold of on merging to 2.10.0 for now, but definitely goes into 2.10.1.

**Comment by paulp** [comment]
Weird, I posted a comment and it appeared twice, so I deleted one and now it appears zero times.  Well, it's not important, but I will repeat it in case anyone saw it and now wonders why I would delete it: "The only way there is no RC2 is if nobody tries RC1."

**Pull request merged**
