### PR TITLE
Use private[this] to avoid accessor generation

### PR DESCRIPTION
**Pull request by retronym**
As suggested by @viktorklang over in #7207

### CODE REVIEW

**Comment by xuwei-k** [comment]
https://github.com/scala/scala/pull/7127

**Comment by som-snytt** [comment]
Maybe we're a step closer toward unqualified `private` meaning `private[this]`. Is that a mini-SIP or a maxi-SIP?

**Comment by viktorklang** [comment]
@som-snytt I was actually thinking the same thing yesterday.

**Comment by retronym** [comment]
I'll defer to the more comprehensive PR :)

**Comment by som-snytt** [comment]
I'd defer to a scalafix that performs all possible conversions, and also conversions to `private[C]` as happens in the famous Paul Thomas Anderson film with Daniel Day-Lewis about the ambitions of early language designers, `There Will Be Name-Mangling`.

**Comment by SethTisue** [comment]
sounds less scary than the one I was planning on watching tonight, _There Will Be FUD_

**Comment by som-snytt** [comment]
I'd be grateful just for the chance to open for @SethTisue next time he's on tour.

**Pull request closed without merging**
