### PR TITLE
SI-3425 erasure crash with refinement members.

### PR DESCRIPTION
**Pull request by paulp**
Checking that a refinement class symbol does not override any symbols does
mean it will have to be invoke reflectively; but the converse is not true. It
can override other symbols and still have to be called reflectively, because
the overridden symbols may also be defined in refinement classes.

```
scala> class Foo { type R1 <: { def x: Any } ; type R2 <: R1 { def x: Int } }
defined class Foo

scala> typeOf[Foo].member(TypeName("R2")).info.member("x": TermName).overrideChain
res1: List[$r.intp.global.Symbol] = List(method x, method x)

scala> res1 filterNot (_.owner.isRefinementClass)
res2: List[$r.intp.global.Symbol] = List()
```

And checking that "owner.info decl name == this" only works if name is not
overloaded.

So the logic is all in "isOnlyRefinementMember" now, and let's hope that
suffices for a while.

### CODE REVIEW

**Comment by retronym** [comment]
In my test case for this (now lost), I printed the caller to show whether or not a reflective call was used, and checked a few varieties like:

``` scala
trait A { val y = {println(Thread.currentThread.getStackTrace.apply(1));
((new A with B {}): (A { val y: Int }) with B { val y: Int }).y // no reflection

((new A with B {}): (Any { val y: Int }) with B { val y: Int }).y // reflection
```

**Comment by paulp** [comment]
@retronym Never let it be said I don't take reviewer comments seriously!

**Comment by retronym** [comment]
LGTM. Now you can answer the interview question: "Have you ever written code that... writes other code? Tell me about it...."

**Comment by paulp** [comment]
> Idle pondering: How much has String Interpolation lowered the activation energy these sort of endeavours?

Not nearly as much as it will if I ever get back to my combination-interpolator...

``` scala
object Main extends App with Generator {
  object interpolator extends StateInterpolator
  object pkg extends FreshMaker("p")
  import interpolator._

  def top: Arg       = "private protected"
  def term: Arg      = List("def", "var", "val", "lazy val")
  def access: Arg    = List("protected", "protected[this]", "")
  def classKw: Arg   = "class trait"
  def implKw: Arg    = "object class trait"
  def thisSuper: Arg = List("this.", "super.", "")
  def aLit: Arg      = "null true"

  val paths = (
    c"""|$classKw C1[T1] { outer =>
        |  $classKw D1[T2] {
        |    $access $term m1: ((T1, T2)) = null
        |    $access $term m2: String = decls(this)
        |  }
        |}
        |object C3 extends C1[String] { object D2 extends D1[String] { val m3 = m2 } }
        |"""
  )
```

**Pull request merged**
