### PR TITLE
[REVISIT] FormatInterpolator uses sequence arg [ci: last-only]

### PR DESCRIPTION
**Pull request by som-snytt**
Interpolations can receive `${List(s): _*}`, as the standard interpolators take `Any*`.

A use case for `f` is indexed format specifier.

This PR cherry-picks the updated interpolator that is stuck in the queue.

### CODE REVIEW

**Comment by SethTisue** [comment]
Not sure if I understand correctly. This is a user-visible change that has already been accepted for Scala 3?

**Comment by som-snytt** [comment]
I came across the edge case while backporting the error messages for `: _*`.

The Scala 3 ticket is https://github.com/lampepfl/dotty/issues/14564 ~which I will follow up~.

The syntax is broken on Scala 3. The syntax is (correctly) accepted on Scala 2, but the "built-in" interpolators (incorrectly) don't do a reasonable thing. (Presumably they did ~the right~ some thing in the past, modulo `f""`.)

The syntax makes sense because `s"X${ vs: _* }Y"` is defined to be `StringContext("X", "Y").s(vs: _*)`. The implementation has the choice of rejecting if `vs.size != 1`. For `s""`, I just let it concatenate the args when invoked this way, though failing (not compiling) would also be reasonable. `f""` accepts in order to support `"%8$d"` style arg indexing, where `8 < vs.size`.

**Comment by SethTisue** [comment]
LGTM, but let's not merge this until after the Scala 3 PR is merged.

**Comment by som-snytt** [comment]
There's no hurry for this edge case.

**Comment by SethTisue** [comment]
@som-snytt the Scala 3 PR was merged, so I guess this can move forward again? but there's a merge conflict?

**Comment by SethTisue** [comment]
@som-snytt interested in returning to this one...?

**Comment by som-snytt** [comment]
Dotty was fixated on the postfix error instead of fixing the parser:
```
scala> f"%2$$d${List(42,17): _*}%s"
-- [E031] Syntax Error: ------------------------------------------------------------------------------------------------
1 |f"%2$$d${List(42,17): _*}%s"
  |                      ^
  |                      * can be used only for last argument
  |
  | longer explanation available when compiling with `-explain`

scala> f"%2$$d${List(42,17)*}%s"
-- [E018] Syntax Error: ------------------------------------------------------------------------------------------------
1 |f"%2$$d${List(42,17)*}%s"
  |                     ^
  |                     expression expected but '}' found
  |
  | longer explanation available when compiling with `-explain`
```

As a refresher, this change was to let the interpolators handle what was already correctly parsed:

```
scala> s"HEAD${List(42,17): _*}TAIL" // print

scala.StringContext.apply("HEAD", "TAIL").s(((scala.`package`.List.apply[Int](42, 17)): `_*`)) // : String
```
which is like `List(42, 17).mkString("HEAD", "", "TAIL")` except written left-to-right.

The `oxford` interpolator would add commas.

This would usefully [sic] enable:
```
scala> f"%2$$d${42}${17}"
val res7: String = 174217

scala> f"%2$$d${List(42,17): _*}%s"
          ^
       error: Argument index out of range
```

Returning to hibernation until a more compelling interpolating DSL use case turns up.

**Pull request closed without merging**
