### PR TITLE
Make CHAMP HashMap and HashSet the default

### PR DESCRIPTION
**Pull request by szeiger**
The `Map` and `Set` delegate factories already used them but now they
are named `s.c.i.HashMap` and `s.c.i.HashSet`.

The old implementations are still available under `OldHashMap` and
`OldHashSet` and they can still be selected by setting the environment
variable `SCALA_COLLECTION_IMMUTABLE_USE_BASELINE` to `true`.

Now that @retronym's CHAMP changes have been merged we can rename the classes to make CHAMP the default. I deliberately renamed the old files (`HashSet.scala` -> `OldHashSet.scala`, same for Map) but not the new ones (`HashSet` is defined in `ChampHashSet.scala`) to make outstanding merges easier. We should clean that up when we remove the old implementations altogether (presumably for RC1).

### CODE REVIEW

**Comment by SethTisue** [comment]
> when we remove the old implementations altogether (presumably for RC1)

yup, that's https://github.com/scala/collection-strawman/issues/572

**Comment by plokhotnyuk** [comment]
BTW, how CHAMP HashMap/HashSet behave in case of weak hash codes (like in java.lang.String)? Will them suffer like others or they will have an ability to define/override a hashing strategy for keys?

Please, also, see:

https://events.ccc.de/congress/2011/Fahrplan/attachments/2007_28C3_Effective_DoS_on_web_application_platforms.pdf

https://vanilla-java.github.io/2018/07/26/Stringhash-Code-is-not-even-a-little-unique.html

https://vanilla-java.github.io/2018/08/12/Why-do-I-think-Stringhash-Code-is-poor.html

**Comment by szeiger** [comment]
Updated to fix the tests. Most of them were tests for specific layout and collision cases in the old implementations. I changed them back to use those classes for now, we can probably remove them together with the old implementations.

`ChampHashMap` was still missing the `merged` method from the old `HashMap`. I added a simple, non-optimized implementation and opened https://github.com/scala/bug/issues/11077 to fix this until RC1.

@plokhotnyuk There are no changes in this regard. The new implementations still use `##`.

**Comment by retronym** [comment]
Let's add a public constructor to make this continue to work:

```
Welcome to Scala 2.12.6 (GraalVM 1.0.0-rc1, Java 1.8.0_161).
Type in expressions for evaluation. Or try :help.

scala> new scala.collection.immutable.HashMap
res0: scala.collection.immutable.HashMap[Nothing,Nothing] = Map()```

**Comment by szeiger** [comment]
I've added the public constructor and made the scalacheck tests compile but I'm getting one seemingly unrelated error in them:

```
[info] ! unliftable.unlift scala.symbol: Exception raised on property evaluation.
[info] > Exception: java.lang.Error: bad constant value: 'foo of class class scala.Symbol
[info] scala.reflect.internal.Constants$Constant.<init>(Constants.scala:51)
[info] scala.reflect.internal.Constants$Constant$.apply(Constants.scala:33)
[info] scala.reflect.internal.Constants$Constant$.apply(Constants.scala:272)
[info] scala.reflect.quasiquotes.UnliftableProps$.$anonfun$new$26(UnliftableProps.scala:76)
[info] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info] scala.reflect.quasiquotes.Helpers.$anonfun$test$1(QuasiquoteProperties.scala:17)
[info] org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:307)
[info] org.scalacheck.PropFromFun.apply(Prop.scala:22)
[info] org.scalacheck.Prop$.$anonfun$delay$1(Prop.scala:476)
[info] org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:307)
[info] org.scalacheck.PropFromFun.apply(Prop.scala:22)
[info] org.scalacheck.Test$.workerFun$1(Test.scala:326)
[info] org.scalacheck.Test$.$anonfun$check$1(Test.scala:355)
[info] org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:355)
[info] org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[info] org.scalacheck.Test$.check(Test.scala:355)
[info] org.scalacheck.CustomScalaCheckRunner$$anon$2.executeInternal(CustomScalaCheckRunner.scala:113)
[info] org.scalacheck.CustomScalaCheckRunner$$anon$2.$anonfun$execute$10(CustomScalaCheckRunner.scala:105)
[info] org.scalacheck.CustomScalaCheckRunner$$anon$2.$anonfun$execute$10$adapted(CustomScalaCheckRunner.scala:104)
[info] scala.collection.IterableOnceOps.foreach(IterableOnce.scala:451)
[info] scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:449)
[info] scala.collection.AbstractIterable.foreach(Iterable.scala:881)
[info] scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:867)
[info] org.scalacheck.CustomScalaCheckRunner$$anon$2.execute(CustomScalaCheckRunner.scala:104)
[info] sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info] sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] java.lang.Thread.run(Thread.java:748)
[info] Elapsed time: 0.005 sec
```

@retronym any ideas?

**Comment by retronym** [comment]
https://github.com/scala/scala/commit/11af00fe8f6c301075328e7c31fbd3cf007ea714 removed support for `Constant`-s over `scala.Symbols`.

Perhaps we're getting a different compiler (STARR?) running over test/scalacheck/scala/reflect/quasiquotes/UnliftableProps.scala

```scala
  property("unlift scala.symbol") = test {
    val q"${s: scala.Symbol}" = q"'foo"
    assert(s.isInstanceOf[scala.Symbol] && s == 'foo)
  }
```

**Comment by retronym** [comment]
2.13.0-M4 expands `q"'foo"` to `Literal(Constant(Symbol.apply("foo")))`. Running that in the 2.13.x library would give the stack trace above.

**Comment by retronym** [comment]
The problem is that we ported the scalacheck test suite from partest to a regular SBT project, but didn't consider that we'd be compiling them with STARR. So testing macros like quasiquotes uses the wrong implementation, unless you do a bootstrap before running the tests, like we do in CI.

**Comment by SethTisue** [comment]
I've set a reminder to check that this test failure goes away once we re-STARR onto M5.

**Comment by nafg** [comment]
@plokhotnyuk did you read the counter blog posts and the Reddit threads?

**Comment by SethTisue** [comment]
> I've set a reminder to check that this test failure goes away once we re-STARR onto M5.

yup, all good:

```
> scalacheck/testOnly *UnliftableProps*
...
[info] Passed: Total 18, Failed 0, Errors 0, Passed 18
```

**Pull request merged**
