### PR TITLE
Add a regression test for issue #10134

### PR DESCRIPTION
**Pull request by seratch**
This pull request adds a new partest suite verifying if the issue #10134 has been fixed.

@lrytz This pull request adds a test you mentioned in this comment:
>Any volunteer for a regression test PR? I hope the infrastructure is in place to do scaladoc tests with mixed Java/Scala sources.

https://github.com/scala/bug/issues/10134#issuecomment-643947708

### CODE REVIEW

**Comment by seratch** [comment]
Hmm, it seems the test doesn't correctly verify the behavior yet. I'm still learning the way to write valid partests for doc task.

**Comment by seratch** [comment]
This pull request is not yet done. Currently, the test added by this PR fails as below.
```
# starting 1 test in run
!! 1 - run/t10134.scala                          [output differs]
% diff /Users/ksera/github/scala/test/scaladoc/run/t10134.check /Users/ksera/github/scala/test/scaladoc/run/t10134-run.log
@@ -1 +1,52 @@
-Done.
+newSource:1: error: value T10134_Row is not a member of object foo
+import foo.T10134_Row
+       ^
+newSource:2: error: not found: type T10134_Row
+@T10134_Row
+ ^
+java.lang.RuntimeException: Scaladoc Model Test ERROR: No universe generated!
+java.lang.RuntimeException: Scaladoc Model Test ERROR: No universe generated!
+	at scala.sys.package$.error(package.scala:27)
+	at scala.tools.partest.ScaladocModelTest.$anonfun$show$1(ScaladocModelTest.scala:75)
+	at scala.Option.getOrElse(Option.scala:201)
+	at scala.tools.partest.ScaladocModelTest.show(ScaladocModelTest.scala:75)
+	at scala.tools.partest.DirectTest.main(DirectTest.scala:111)
```

In the beginning, I assumed that I can easily add a new test suite by utilizing the existing test infra such as `ScaladocModelTest`. However, it seems I got it all wrong.

If I understand correctly, there is no existing test that loads multiple files from the `resources` directory yet. So, to add a test using two files (Scala source and Java source), I think we need to add a new test base class that covers the use case.

Although I may need some time for learning testing infra for scala project, I'm keen to complete this contribution. Let me know if you have suggestions on this.

**Comment by SethTisue** [comment]
is there someone watching the repo who could offer @seratch some help here?

**Comment by SethTisue** [comment]
@seratch it's plausible that there simply isn't anybody around who knows this code. But I looked at `ScaladocModelTest.scala` myself just now and I agree, it seems it would need work to support this. I see there is also `ScaladocJavaModelTest.scala`, I assume you looked at that as well? That seems like it could be generalizable?

Lukas's request for a volunteer was based on the hope that it might be possible to add a test without too much trouble. It appears you've investigated to the point where it's clear that it isn't that easy. So perhaps it simply isn't worth the effort at this point, since the bug is already fixed, and since it seems unlikely that other bugs are going to be found that would be able to take advantage of any new testing infrastructure you would add.

I poked around a bit to see if I could find some _other_ place where a test like this could go.

`test/script-tests` seems like it could possibly be suitable, but it also seems to be long-moribund, as per the README in that directory.

Support for mixed-Java-and-Scala compilation does exist in partest; there are plenty of tests in `test/files` that have both Scala and Java sources. But it doesn't seem that likely to me that it would be easier to add Scaladoc testing support there, rather than adding Java-and-Scala support to `ScaladocModelTest`/`ScaladocJavaModelTest`.

**Comment by seratch** [comment]
@SethTisue Thanks for the response here! Yes, I agree that working on this may require some efforts and probably it's not a priority for the team. As I'm not planning to make additional changes to this PR, let me close this now. But if someone wants to reuse some of the changes, please feel free to do so!

Through this experience, I learned how to work with partests. I'm keen to work on other tasks when I have time 👋

**Pull request closed without merging**
