### PR TITLE
SI-6811 Deprecate scala.util.parsing.json

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @paulp and/or @adriaanm, please.
Mailing list: https://groups.google.com/d/msg/scala-internals/axzOQ6fUNQg/ZCYl58m4X7MJ

**Comment by adriaanm** [comment]
LGTM -- assuming you got it all, we should probably track on JIRA what we'll say in the release notes and there we should recommend OSS alternatives for stuff we'll drop outright

**Comment by soc** [comment]
@adriaanm One open question is what's the future of the parser combinator library in general ... do we want to keep it? Like JSON and XML, this seems to be an area where type macros could be a huge change. E. g. having a type macro which compiles the parser combinator down to a simple state machine. I think I even saw something like that on the mailing list recently ... ah here it is: https://groups.google.com/d/topic/scala-language/sXC-f88Adiw/discussion

**Comment by adriaanm** [comment]
I agree staging is a great idea for combinator parsers -- I don't think you need type macros for that: blackbox macros should do. The parsers are one of those components that I intend to ship as a separate jar for 2.11.

Blackbox macros are those macros that look just like regular method calls (type signature fully specified).

**Comment by soc** [comment]
@adriaanm Alright, sounds nice. I'll add the intention to split parsers into a separate jar to SI-6811, so we don't forget it.

**Comment by paulp** [comment]
LGTM

**Pull request merged**
