### PR TITLE
merges scala.reflect.base into scala.reflect.api

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Reviewers man!  WE need us some reviewers.   I'll take a look.

**Comment by jsuereth** [comment]
LGTM, once tests pass.

**Comment by xeno-by** [comment]
Hmm interesting. Kitteh is capable of starting a new build while an old one is still in flight.

**Comment by xeno-by** [comment]
@jsuereth Please don't abort either of those. The first one shows me failed tests, and let's hope that it won't reveal the new ones, so that the second build passes in peace.

**Comment by xeno-by** [comment]
False hopes :(

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Duh... A scaladoc test failure!!

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
