### PR TITLE
SI-6648 copyAttrs must preserve TypeTree#wasEmpty

### PR DESCRIPTION
**Pull request by retronym**
This field tracks whether the type is an inferred
one, subject to removal in `resetAttrs`, or an explicit
type, which must remain.

In ae5ff662, `ResetAttrs` was modified to duplicate
trees, rather than mutate trees in place. But the
tree copier didn't pass `wasEmpty` on to the new tree,
which in turn meant that the subsequent typing run
on the tree would not re-infer the types. If the
type refers to a local class, e.g. the anonymous
function in the enclosed test case, the reference
to the old symbol would persist.

This commit overrides `copyAttrs` in TypeTree to
copy `wasEmpty`.

We might consider representing this as a tree
attachment, but this would need to be validated
for the performance impact.

Review by @lrytz

### CODE REVIEW

**Comment by hubertp** [comment]
Nice catch!

**Comment by retronym** [comment]
How I found it: add `val origin = Thread.currentThread.stackTrace` to `Tree`, and then at the spot where the polluted tree shows up, that stack trace implicated `TreeCopier`.

**Comment by paulp** [comment]
Have you discovered "Origins" yet? You might like it. Given a method like

```
def f = { ... }
```

You can add only this:

```
def f = Origins("f") { ... }
```

And at shutdown you will be given a detailed report about who called it. A second integer argument to Origins specifies the number of stack frames to track.

**Comment by retronym** [comment]
My val was named in honour of it. In this case I needed to track down the origin of one misbehaved tree.

**Comment by paulp** [comment]
> In this case I needed to track down the origin of one misbehaved tree.

You can use it selectively too:

```
if (tree.isMisbehaving)
  Origins("ain't misbehavin'")(tree)
```

**Comment by paulp** [comment]
This looks good to me by the way. Real purty.

**Comment by xeno-by** [comment]
Wow this `Origins` thing is cool. Thank you

**Comment by lrytz** [comment]
:clap: applause, lgtm

**Comment by adriaanm** [comment]
and it even comes with a Dylan reference

**Comment by adriaanm** [comment]
could you amend the commit message to reference SI-6648 please?

I get this doubling of the wrong letter all the time with my own name so I know how SI-6648 must feel when it gets called SI-6448

**Comment by retronym** [comment]
Done.

**Pull request merged**
