### PR TITLE
Punt on IDE validation in 2.12.x

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by adriaanm** [comment]
Until https://github.com/scala-ide/uber-build/issues/48 is fixed, punt on IDE integration testing.

**Comment by adriaanm** [comment]
See also the failure in #4286

**Comment by gkossakowski** [comment]
Let's link to https://github.com/scala-ide/uber-build/issues/48 right from the log message. It reduces number of hops one has to go through to see what's the current status of affairs.

**Comment by adriaanm** [comment]
message amended -- otherwise LGTY?

**Comment by gkossakowski** [comment]
Yep, LGTM but double check the message. I don't see the link yet.

**Comment by adriaanm** [comment]
The URL is there for me.

**Comment by adriaanm** [comment]
Going to merge so others can rebase on 2.12.x

**Pull request merged**
