### PR TITLE
CPS: enable return expressions in CPS code if they are in tail position

### PR DESCRIPTION
**Pull request by phaller**
Adds a stack of context trees to AnnotationChecker(s). Here, it is used to
adapt the annotation of a return expression if the expected type is a CPS type.

The remove-tail-return transform is reasonably general, covering cases such as
try-catch-finally. Moreover, an error is thrown if, in a CPS method, a return
is encountered which is not in a tail position such that it will be removed
subsequently.

Review by @adriaanm or @TiarkRompf

### CODE REVIEW

**Comment by adriaanm** [comment]
In addition  to my inline comment, will this work for (admittedly weird) code like

'''
return {foo; bar}
'''

(not a rethoric question)

I'll leave it to Tiark to comment on the cps type state annotations.

**Comment by phaller** [comment]
Code like `return { foo; bar }` is supported; commit 51c92f02229098d0b402a65a72267f7a17984022 adds a test case for that (`continuations-run/ts-1681-3.scala`).

**Comment by phaller** [comment]
Tiark (@TiarkRompf) has already reviewed an earlier version of the type state annotations. Most of his comments should be addressed in the current version. I've asked him to have another look, though.

**Comment by jsuereth** [comment]
Should I wait to merge, or can I merge now then?

**Comment by phaller** [comment]
OK, please go ahead and merge. If any other issues pop up I'll address them in a subsequent pull request.

**Comment by adriaanm** [comment]
retro-active thumbs-up!

**Comment by TiarkRompf** [comment]
I haven't had time for an in-depth review but I've just tried a few things in the REPL (latest master) and run into a couple of problems:

```
def foo(x:Int): Int @cps[Int] = x

def bar(x:Int): Int @cps[Int] = return foo(x)
error: return expressions in CPS code must be in tail position
```

Clearly, the return is in tail position, so the error is wrong.

```
def bar(x:Int): Int @cps[String] = return foo(x)
error: return expressions in CPS code must be in tail position
```

This should be a type error. Since the emitted error is issued by SelectiveANF, which runs after typer, this tells me that type checking misses the type error.

```
def bar(x:Int) = return foo(x)
```

This produces a compiler crash (NPE in hasPlusMarker called from addAnnotations).

I'll have a close look at the implementation, too, but these issues need to be addressed before I can give green light.

EDIT: Another one, which does not even involve cps code:

```
def bar(x:Int): Int = { return x; x }  // error: return expressions in CPS code must be in tail position
def bar(x:Int) = { return x; x }  // NPE
```

**Comment by phaller** [comment]
Thanks for your REPL experiments, Tiark. The problems you ran into should all be easy to fix. Will do that as soon as I get a chance.

**Pull request merged**
