### PR TITLE
SI-3452 Correct Java generic signatures for mixins, static forwarders

### PR DESCRIPTION
**Pull request by retronym**
[Parts of this patch and some of the commentary are from @paulp]

This took me so long to figure out I can't even tell you. Partly because
there were two different bugs, one which only arose for trait forwarders
and one for mirror class forwarders, and every time I'd make one set
of tests work another set would start failing. The runtime failures
associated with these bugs were fairly well hidden because you usually
have to go through java to encounter them: scala doesn't pay that much
attention to generic signatures, so they can be wrong and scala might still
generate correct code. But java is not so lucky.
## Bug in mixin forwarders

During mixin composition, classes which extend traits receive forwarders
to the implementations. An attempt was made to give these the correct
info (in method "cloneBeforeErasure") but it was prone to giving
the wrong answer, because: the key attribute which the forwarder
must capture is what the underlying method will erase to _where the
implementation is_, not how it appears to the class which contains it.
That means the signature of the forwarder must be no more precise than
the signature of the inherited implementation unless additional measures
will be taken.

This subtle difference will put on an unsubtle show for you in test
run/t3452.scala.

```
trait C[T]
trait Search[M] { def search(input: M): C[Int] = null }
object StringSearch extends Search[String] { }
StringSearch.search("test");  // java
// java.lang.NoSuchMethodError: StringSearch.search(Ljava/lang/String;)LC;
```

The principled thing to do here would be to create a pair of
methods in the host class: a mixin forwarder with the erased
signature `(String)C[Int]`, and a bridge method with the same
erased signature as the trait interface facet.

But, this turns out to be pretty hard to retrofit onto the
current setup of Mixin and Erasure, mostly due to the fact
that mixin happens after erasure which has already taken
care of bridging.

For a future, release, we should try to move all bridging
after mixin, and pursue this approach. But for now, what can
we do about `LinkageError`s for Java clients?

This commit simply checks if the pre-erasure method signature
that we generate for the trait forward erases identically to
that of the interface method. If so, we can be precise. If not,
we emit the erased signature as the generic signature.
## Bug in static forwarders

The same principle is at work, at a different location.
During genjvm, objects without declared companion classes
are given static forwarders in the corresponding class, e.g.

```
object Foo { def bar = 5 }
```

which creates these classes (taking minor liberties):

```
class Foo$ { static val MODULE$ = new Foo$ ; def bar = 5 }
class Foo  { static def bar = Foo$.MODULE$.bar }
```

In generating these, genjvm circumvented the usual process whereby one
creates a symbol and gives it an info, preferring to target the bytecode
directly. However generic signatures are calculated from symbol info
(in this case reusing the info from the module class.) Lacking even the
attempt which was being made in mixin to "clone before erasure", we
would have runtime failures of this kind:

```
abstract class Foo {
  type T
  def f(x: T): List[T] = List()
}
object Bar extends Foo { type T = String }
Bar.f("");    // java
// java.lang.NoSuchMethodError: Bar.f(Ljava/lang/String;)Lscala/collection/immutable/List;
```

Before/after this commit:

```
<   signature                                     f  (Ljava/lang/String;)Lscala/collection/immutable/List<Ljava/lang/String;>;

---
>   signature                                     f  (Ljava/lang/Object;)Lscala/collection/immutable/List<Ljava/lang/Object;>;
```

This takes the warning count for compiling collections under
`-Ycheck:jvm` from 1521 to 26.

### CODE REVIEW

**Comment by retronym** [comment]
By preserving the stronger mixin generic signature where possible, I am seeking to preserve backwards source compatibility with Java client code that didn't previously result in a `LinkageError`.

For example:
- test/files/pos/javaReadsSigs
- test/files/run/t4238

Many of the remaining `Ycheck:jvm` warnings are spurious and would be avoided if we rebase 66b7832f3daef3d2cd4957a6e6d7f8071772da90.

**Comment by gkossakowski** [comment]
@retronym: the failure seems genuine.

I'm a bit uneasy about merging this patch right before RC1. It's quite large and not particularly easy to review for me. Also, it's not like we have great test coverage for generic signatures so we don't need worry about regressions.

**Comment by paulp** [comment]
I think he means regressions in the sense of things which used to work no longer working, not in any sense which would be detectable via test failures.

**Comment by paulp** [comment]
Actually that test failure is illegitimate. It's testing very slight variations of how main methods materialize, partly to signal which something changes. It looks like its choice of error message changed in one case. Update check file.

**Comment by paulp** [comment]
@gkossakowski I suggest examining some affected bytecode before and after. My guess is you will have fewer reservations afterward.

**Comment by paulp** [comment]
@retronym Something to note somewhere is that if you do ever pursue the creation of more bridges - another category of missing bridges arises anytime primitives are used as type arguments, e.g. T => T becomes (I) and (Object)Object but there is no (Integer)Integer to be seen, and more importantly, Option[T] always erases to Option[Object] instead of Option[Integer] even when T is known to be "Int" (but of course is not really Int because the generic spec doesn't allow primitives as type arguments.)

The problems which arose from using Option[Integer] could all be eliminated as far as I know with additional bridges.

**Comment by retronym** [comment]
@gkossakowski I just realised that I had left unrelated chances in the patch. I had refactored `Erasure` to expose the bridge building facilities to `Mixin`. But in this more modest, bridge-free incarnation, that is not necessary. I've just pushed an update.

**Comment by gkossakowski** [comment]
@retronym: this makes it much easier to review. I'll have a look at it tomorrow.

**Comment by soc** [comment]
@retronym Is this handled correctly in GenBCode already, or existed this bug only in GenASM in the first place?

**Comment by retronym** [comment]
@soc good catch. I'll refactor this logic out and share it.

**Comment by gkossakowski** [comment]
@retronym: ok, my reservations vanished. I agree that the approach this PR is taking is sound and should vastly improve our signatures situation. The number of high quality test cases introduced here is also impressive. Plenty of :ice_cream: to @paulp and @retronym for this work!

I'll LGTM it once refactoring of GenASM and GenBCode is done.

**Comment by retronym** [comment]
@gkossakowski In the process of sharing the static forwarder side of this fix with `GenBCode`, I've taken a second look and realised it wasn't quite right. I've pushed an expanded test (that was still failing) with a modified version that works in the same manner as `Mixin`.

I've also cleaned up some low hanging code duplication. I know I should probably factor it to a shared spot rather than having `GenBCode` call `GenASM`, but I think this is largely a cosmetic issue, and the main point is to have just _one_ copy of the code.

**Comment by gkossakowski** [comment]
LGTM

Good catch in 640e279.

**Comment by gkossakowski** [comment]
@retronym: I'll let you close the tickets as I've got a little bit lost which ones we fix with this PR.

**Comment by adriaanm** [comment]
BTW, the t7374 test requires a new locker, in case anyone else comes across this failure when running fast and lose with locker.skip=1

**Pull request merged**
