### PR TITLE
STARR: use 2.11.0-M4, built with 2.11.0-M3

### PR DESCRIPTION
**Pull request by adriaanm**
Replaced starr jars with 2.11.0-M4, built with Scala 2.11.0-M3.

I used `ant replacestarr-opt -Dstarr.use.released=1`, with `starr.number`:

```
starr.version=2.11.0-M3
```

Then pushed the jars to artifactory after moving `lib/jline.jar` out of the way,
as it's no longer "desired" (i.e., not pulled from artifactory). Its presence
seemed to break `./push-binary-libs.sh $ARTIFACTORY_USER $ARTIFACTORY_PASS`.

You can by-pass the custom starr artifact download and use a (released) version
of Scala by changing your `build.properties` to include

```
starr.use.released=1
```

You may optionally change `starr.version` in `starr.number` to whichever version
that maven can resolve for you.

review by @retronym

### CODE REVIEW

**Comment by gkossakowski** [comment]
I'm not a reviewer for this change but since we have a mechanism for resolving starr from Maven repo, wouldn't it be better to use that one instead of our custom script?

**Comment by adriaanm** [comment]
We're allowing people to use both as long as the old mechanism is still there. This change updates both mechanisms.

**Comment by gkossakowski** [comment]
@adriaanm: oh yes, I just meant what we use by default. Would it make sense to switch to Maven resolution by default?

**Comment by adriaanm** [comment]
yep, that'll be a separate PR

**Comment by gkossakowski** [comment]
Ok, makes sense.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
