### PR TITLE
Hiding AnyRef specialization under a flag

### PR DESCRIPTION
**Pull request by VladUreche**
The current AnyRef specialization is still fragile, so we'll let the
users choose whether to use it or not via the -Xanyref-specialization
compiler flag. Source code can always be compiled against a previously
AnyRef-specialized classes, but will only be AnyRef-specialized itself
if the flag is set.

In this patch, an anti-annotation is introduced to mark the fact that
AnyRef specialization should be excluded (@specializedExcludeAnyRef).
This anti-specialization annotation is added automatically by the
compiler to all @specialized type parameters, iregardless of whether
the type parameter is going to be specialized on AnyRef or not. The
reason is that the logic necessary to decode the types involved in the
specialization should not be moved outside SpecializeTypes.scala.

Once @specializedExcludeAnyRef is set (in superaccessors) and pickled
into the class file, all further scalac runs will specialize the
signature for all given types except AnyRef.

The instrument.jar archive is generated from the current source, thus
there's no need for an extra bootstrapping commit.

Review by @paulp and @non.

### CODE REVIEW

**Comment by paulp** [comment]
The strategy seems inordinately indirect and complicated.  Maybe there is a good reason for it, but I can't be the guy to sign off on this.

**Comment by VladUreche** [comment]
Since the "I didn't specialize on AnyRef" information must be available for future compilations we need to do something about it before pickler. 

There are two possibilities:
1. expand the SpecializeGroups to types and knock out AnyRef -- that's #999, and it requires moving the specializedOn logic outside SpecializeTypes.scala -- I chose Definitions.scala, but it still looks ugly.
2. add the "I didn't specialize on AnyRef" information as an annotation in superaccessors and then filter AnyRef out in specializedOn -- requires minimal changes compared to the first option -- and that's what's implemented here.

Also, looking at the size of the pickled information favors solution 2: for the most common annotation, `@specialize T`:
- solution 1 pickles `@specialized(Unit, Boolean, Byte, Char, Short, Int, Float, Long, Double) T`
- solution 2 pickles `@specializedExcludeAnyRef @speiclaized T`

If you have a better suggestion on how to do it, I'd love to hear it. But that's the least complicated solution I could come up without spreading the specialization code all over the compiler.

**Comment by VladUreche** [comment]
I had another look at the diff and I noticed I let the changes in Definitions.scala from #999 slipped into this patch. I will resubmit the patch without those changes. 

@paulp:  please have another look at this, as it is important that we don't ship 2.10 with the AnyRef specialization on by default, which would prevent java users from using Function, Tuple and all other AnyRef-specialized classes (https://issues.scala-lang.org/browse/SI-5976) - Unless you can fix mixin before the release, better disable AnyRef specialization...

**Comment by VladUreche** [comment]
PLS REBUILD ALL

**Comment by VladUreche** [comment]
I will come up with another pull request that only removes the AnyRef specialization from the Scala library.

**Pull request closed without merging**
