### PR TITLE
SI-8226 Deduplicate JavaTokens/ScalaTokens

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
@sschaef So ... something failed in the IDE. I looked at the output, but couldn't find anything which looked like "!!!FAILED TEST!!!".

Can you give me a hint about what to look for?

**Comment by kiritsuku** [comment]
There are compilation errors in scala-refactoring. See at the bottom of [this log](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/5813/console)

```
...
[ERROR] /localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/scala-refactoring/org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceGenTest.scala:52: error: not found: value Tokens
[ERROR]       t.copy(mods = NoMods withPosition (Flags.PROTECTED, NoPosition) withPosition (Tokens.VAL, NoPosition)) setPos t.pos
[ERROR]                                                                                     ^
```

**Comment by soc** [comment]
@sschaef Oh, wow. Thanks! I didn't even find that log!
Mhhh ... should I revert the rename of `Tokens` to `ScalaTokens` then, or is there another way?

**Comment by kiritsuku** [comment]
When you want to change the API of the compiler you should first deprecate it to give third party code a chance to change. I don't think you can tell kitty to merge a PR to scala and scala-refactoring at the same time. And who knows, maybe someone else relies on this API.

**Comment by soc** [comment]
@sschaef Thanks, I just renamed `ScalaTokens` back to `Tokens` and called the common class `CommonTokens` instead.

**Comment by xeno-by** [comment]
@soc Seems like a non-spurious error:

```
locker.comp:
    [mkdir] Created dir: /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/build/locker/classes/compiler
[locker.compiler] Compiling 293 files to /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/build/locker/classes/compiler
[locker.compiler] /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/src/compiler/scala/tools/nsc/javac/JavaTokens.scala:9: error: type Tokens is not a member of package scala.tools.nsc.ast.parser
[locker.compiler] object JavaTokens extends ast.parser.Tokens {
[locker.compiler]                                      ^
[locker.compiler] /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/src/compiler/scala/tools/nsc/javac/JavaParsers.scala:49: error: not found: value EOF
[locker.compiler]       accept(EOF)
[locker.compiler]              ^
[locker.compiler] /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/src/compiler/scala/tools/nsc/javac/JavaParsers.scala:62: error: not found: value EOF
[locker.compiler]           case EOF =>
[locker.compiler]                ^
[locker.compiler] /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/src/compiler/scala/tools/nsc/javac/JavaParsers.scala:64: error: not found: value SEMI
[locker.compiler]           case SEMI =>
[locker.compiler]                ^
```

**Comment by soc** [comment]
Fixed it, thanks!

**Comment by adriaanm** [comment]
Review by @gkossakowski

**Comment by soc** [comment]
_Sigh_ C'mon I just rebased it ... aaargh.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
LGTM.

Thanks!

**Pull request merged**
