### PR TITLE
Scala 2.11.13 requires Java 8; improved Java 11 support (upgrade to asm 6.2)

### PR DESCRIPTION
**Pull request by adriaanm**
Require Java 8 to run scalac, as well as minimal platform of generated bytecode.
Upgrade to asm 6.2 for better Java 11 support.
Small updates to tests, and bump jline, sbt while we're at it.

### CODE REVIEW

**Comment by adriaanm** [comment]
https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-bootstrap/1233/console

**Review by lrytz — APPROVED** [review]

**Comment by adriaanm** [comment]
@lrytz I added another backport since your review. This would mean 2.11.13 would not run on Java versions prior to 8. Given all the available options, I think this is the expedient one. 2.11 is EOL, so if you can't live with the Java 8 requirement, it's still EOL for you at 2.11.12. I highly doubt we'll ever need Java 6 support in any future 2.11 (and if we do, we'll cross that bridge then).

**Comment by lrytz** [comment]
Sounds good 👍

**Review by lrytz — APPROVED** [review]

**Comment by adriaanm** [comment]
/nothingtoseehere  let’s keep the test failures in the history

**Pull request merged**
