### PR TITLE
Merge remote-tracking branch 'origin/2.11.x' into 2.12.x [ci: last-only]

### PR DESCRIPTION
**Pull request by SethTisue**
only trivial merge conflicts here.

not dealing with PR #4333 yet in this merge because there is a substantial
conflict there -- so that's why I stopped at
63daba33ae99471175e9d7b20792324615f5999b for now

### CODE REVIEW

**Comment by SethTisue** [comment]
the merge conflicts were:
- a few commits affected files which have been deleted in 2.12.x
- there were some overlapping minor changes in documentation files and/or comments. nothing in code.

**Comment by SethTisue** [comment]
``` text
% export MB=$(git merge-base origin/2.12.x 63daba3
% echo $MB | cut -c1-7
a77e34e
% git log --oneline --graph $MB...63daba3
*   63daba3 Merge pull request #4713 from SethTisue/batch-of-typos
|\  
| * fb4f9ad fix assorted typos
| * e3ae871 fix trivial error in spec
* |   6711c08 Merge pull request #4722 from janekdb/2.11.x-scaladoc-in-context-AnyVal
|\ \  
| * | 15c1237 Link to completed value classes SIP page instead of pending version
* | |   1629f61 Merge pull request #4706 from VladUreche/issue/tree-checker
|\ \ \  
| * | | 9d73937 Re-enable tree checkers
* | | |   8292bb3 Merge pull request #4704 from VladUreche/issue/9442
|\ \ \ \  
| * | | | 6b336f8 SI-9442 Fix the uncurry-erasure types
* | | | |   7d91f64 Merge pull request #4726 from janekdb/2.11.x-now-Oracle-urls
|\ \ \ \ \  
| * | | | | 7f79375 Update Java and Sun URLs to replacement Java and Oracle URLs
* | | | | |   7d2c0b3 Merge pull request #4715 from Ichoran/issue/9424
|\ \ \ \ \ \  
| |/ / / / /  
|/| | | | |   
| * | | | | 117ea7f SI-9424  Clarify behavior of PriorityQueue toString
| | |_|_|/  
| |/| | |   
* | | | |   1e47a73 Merge pull request #4701 from janekdb/2.11.x-scaladoc-in-context-Option
|\ \ \ \ \  
| |_|_|_|/  
|/| | | |   
| * | | | 681cc07 Improve implementation comments in Option.collect example
|  / / /  
* | | |   2ca3f8b Merge pull request #4692 from JanBessai/Fix-SI-6636
|\ \ \ \  
| * | | | 43d3eec SI-6636 Fix macro expansion in toolboxes
|  / / /  
* | | |   e077787 Merge pull request #4694 from janekdb/2.11.x-README
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | 3a2fccc Format and content enhance README.md
|  / /  
* | |   6426d0b Merge pull request #4707 from fthomas/topic/pins-link
|\ \ \  
| * | | 37180d0 Add link to online version of Programming in Scala
| | |/  
| |/|   
* | |   9fc52c8 Merge pull request #4710 from retronym/ticket/9450
|\ \ \  
| * | | 0b121d1 SI-9450 Fix triple quoted strings in REPL :power mode
| |/ /  
* | |   d6728ce Merge pull request #4703 from Ichoran/issue/8346
|\ \ \  
| |/ /  
|/| |   
| * | 3cb9a4f SI-8346  Re-established soundness of toSet (element type widening)
|/ /  
* |   79171ce Merge pull request #4705 from mpociecha/fix-typos3
|\ \  
| |/  
|/|   
| * 4b63953 Fix typo in the name of a private method
| * 31ae74f Fix typos in spec, docs and comments
|/  
*   f8a6d21 Merge pull request #4702 from janekdb/2.11.x-CONTRIBUTING-advice
|\  
| * a7e24ce Sync commit advice to README.md and fix Scabot URL
* | c3bdcf4 Merge pull request #4696 from janekdb/2.11.x-contributing
|/  
* 36b0138 Extend documentation contacts
```

**Comment by SethTisue** [comment]
review/merge by @adriaanm

**Comment by adriaanm** [comment]
LGTM!

**Pull request merged**
