### PR TITLE
Remove unused imports in Seq

### PR DESCRIPTION
**Pull request by kun-song**

### CODE REVIEW

**Comment by He-Pin** [comment]
There are more in the collection here and there, maybe the `scalafix` will help? @olafurpg ?

**Review by NthPortal — APPROVED** [review]
Thanks cleaning this up!

**Comment by olafurpg** [comment]
@hepin1989 I found 3 unused imports in scala-library on the 2.12.x branch that you can fix with scalafix

```sh
alias metac="coursier launch org.scalameta:metac_2.12.6:4.0.0 -- -cp $(coursier fetch -p org.scala-lang:scala-library:2.12.6)"
alias scalafix="coursier launch ch.epfl.scala:scalafix-cli_2.12.7:0.9.0 -M scalafix.v1.Main --"
# Inside scala/scala root directory
mkdir out
metac -d out -Ywarn-unused-import $(find src/library -type f | grep '.*\(scala\|java\)$')
scalafix --scalac-options -Ywarn-unused-import -r RemoveUnused --classpath $(coursier fetch org.scala-lang:scala-library:2.12.7 -p):out -f src/library
```

Produces the following diff

```diff
diff --git a/src/library/scala/collection/mutable/WrappedArray.scala b/src/library/scala/collection/mutable/WrappedArray.scala
index 26f955f0a8..8640e1212d 100644
--- a/src/library/scala/collection/mutable/WrappedArray.scala
+++ b/src/library/scala/collection/mutable/WrappedArray.scala
@@ -15,7 +15,6 @@ package collection
 package mutable
 
 import scala.reflect.ClassTag
-import scala.runtime.BoxedUnit
 import scala.collection.generic._
 import scala.collection.parallel.mutable.ParArray
 import scala.util.hashing.MurmurHash3
diff --git a/src/library/scala/concurrent/impl/ExecutionContextImpl.scala b/src/library/scala/concurrent/impl/ExecutionContextImpl.scala
index 4473f12226..5ec1eac4d9 100644
--- a/src/library/scala/concurrent/impl/ExecutionContextImpl.scala
+++ b/src/library/scala/concurrent/impl/ExecutionContextImpl.scala
@@ -12,8 +12,8 @@
 
 package scala.concurrent.impl
 
-import java.util.concurrent.{ ForkJoinPool, ForkJoinWorkerThread, ForkJoinTask, Callable, Executor, ExecutorService, ThreadFactory, TimeUnit }
-import java.util.concurrent.atomic.{AtomicInteger, AtomicReference}
+import java.util.concurrent.{ ForkJoinPool, ForkJoinWorkerThread, Callable, Executor, ExecutorService, ThreadFactory, TimeUnit }
+import java.util.concurrent.atomic.AtomicInteger
 import java.util.Collection
 import scala.concurrent.{ BlockContext, ExecutionContext, CanAwait, ExecutionContextExecutor, ExecutionContextExecutorService }
 import scala.annotation.tailrec

```

**Comment by kun-song** [comment]
I will remove all these in this PR.

**Comment by kun-song** [comment]
Since these unused imports only exist in 2.12.x, maybe another PR needed.

**Comment by olafurpg** [comment]
Scalafix doesn't support 2.13 yet so we can wait until 2.13 stable is to run scalafix on the scala/scala sources.

**Comment by He-Pin** [comment]
@olafurpg Thanks, I wandered that Scalafix could even do something like `remove unused Import` during the development cycle of Scala itself.

**Comment by SethTisue** [comment]
> Thanks, I wandered that Scalafix could even do something like remove unused Import during the development cycle of Scala itself

yes, a pull request adding automation around code quality would be welcome

**Comment by SethTisue** [comment]
thanks @satansk !

**Pull request merged**
