### PR TITLE
General formatting improvements in the spec

### PR DESCRIPTION
**Pull request by gourlaysama**
The spec always needs some love, so here I go:

**This is only about formatting, it does not change content or even wording.**
- syntax highlighting for scala code, using highlight.js: 
  - this is done in a way that _interacts nicely with MathJax_: one can use latex inside code blocks without problem (and still get syntax highlighting),
  - uses the latest highlight.js 8.2, with the Scala support freshly revamped by @non,
- individual HTML pages now have titles,
- no more broken links,
- fix or work around some latex problems with MathJax,
- mass-removal of trailing whitespace, while I was at it...

I uploaded a preview of the result [here](http://static.antoine.gourlay.fr/temp/spec/) to make reviewing easier.

### CODE REVIEW

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@e11fe9b

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@e11fe9b

**Comment by retronym** [comment]
PLS SYNCH

**Comment by retronym** [comment]
The code blocks exemplifiying the named arguments transformation are not displayed on a single line.

Before:

image

After:

image

**Comment by retronym** [comment]
I'm looking at the W3C link checker's [report](http://validator.w3.org/checklink?uri=http%3A%2F%2Fstatic.antoine.gourlay.fr%2Ftemp%2Fspec%2F&hide_type=all&recursive=on&depth=&check=Check) on your published static site.

Looking quite good now!

Here's one wrong link out to Scaladoc:
Wrong: http://www.scala-lang.org/api/current/index.html#scala.collection.immutable.StringLike
Should be: http://www.scala-lang.org/api/current/#scala.collection.immutable.StringLike

We still generate duplicate anchors, particular for examples. e.g in section 3, Types:

image

I see you changed section titles to avoid this problem when we needed to link to an example. I guess we can leave the untargetted examples as is for now (rather than coming up with unique names for them.)

**Comment by retronym** [comment]
Overall, this is an amazing contribution. Thank you, Antoine!

**Comment by gourlaysama** [comment]
@retronym I fixed the code block problem and the various other comments.

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@6e19162

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@d24ad90

**Comment by soc** [comment]
@gourlaysama Looks nice. Just as a note regarding examples: It would be nice if we could get rid of the examples-as-headings approach, but after spending a few hours on it, it looks like Jekyll supports exactly those parsers which make this impossible.

Two reasons for not having examples-as-headings:
- Better formatting options via stylesheets
- Not cluttering up the index

Status quo is that I have given up on a real solution for now and just converted all Example headings to h6 headings, which I don't show in my spec fork anyway.

Looks like the spec situation keeps regressing.

**Comment by soc** [comment]
PLS REBUILD/pr-scala@d24ad90

**Comment by retronym** [comment]
LGTM, a big improvement to the state of the art.

I would love to see a sidebar with navigation between sections. Any idea how to make that a reality?

**Comment by retronym** [comment]
FYI, these changes are published to http://www.scala-lang.org/files/archive/spec/2.11/ (that happens automatically after merging). I needed to do a force browser refresh to see the code highlighting. I assume the browser was caching a Javascript resource that we'd updated in the PR.

**Comment by som-snytt** [comment]
Me too.  Maybe there's a place on the doc page for a notice.

**Comment by gourlaysama** [comment]
@retronym I'm looking into a navigation sidebar. It should be possible with some Jekyll and jQuery magic.

@soc I agree examples as headings aren't great, but Markdown doesn't give a lot of options for encoding that kind of semantic information. At least it should be possible to keep them out the navigation. What kind of special formatting did you have in mind for code examples?

**Comment by soc** [comment]
@gourlaysama I settled on using block-quotes for now: http://oxnrtr.de/scala-spec/01-lexical-syntax.html (also note the navigation sidebar and the outline).

That means block-quotes can't be used for anything else except examples anymore, but I haven't found another use-case for them anyway.

**Pull request merged**
