### PR TITLE
exposes overridenSymbol/overridingSymbol in API

### PR DESCRIPTION
**Pull request by xeno-by**
it seems like we completely overlooked this functionality

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @paulp, @odersky

**Comment by paulp** [comment]
As I wrote in email, I vote for exposing a single method called overriddenSymbols.  I thought minimal was the plan, well that's minimal.

**Comment by xeno-by** [comment]
Done

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
That'll do.

**Pull request merged**
