### PR TITLE
improvements to GenBCode

### PR DESCRIPTION
**Pull request by magarciaEPFL**
- catching up with GenASM
- two fixes (overly restrictive asserts) 
- readability

Review by @gkossakowski

### CODE REVIEW

**Comment by adriaanm** [comment]
Welcome back, @magarciaEPFL!

PS: I've investigated how we can upgrade to asm 5 here: https://github.com/adriaanm/scala/tree/asm5
Assuming we can't use vanilla ASM, I think we should create a scala-asm module:
- depend on an official asm release
- add our wrappers
- shade under scala.tools.asm and republish (implemented in my branch above using jarjar, but I'd like the fork to move to sbt)

**Comment by magarciaEPFL** [comment]
The packaging of ASM5 merits its own discussion at https://issues.scala-lang.org/browse/SI-8089

**Comment by adriaanm** [comment]
Rebuilding the individual build step that failed with some weird dbuild error /cc @cunei, @dragos (since I think you've seen a similar failure somewhere)

https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4985/console

**Comment by adriaanm** [comment]
wiped out the workspace and retrying: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4994/console

**Comment by adriaanm** [comment]
It turned out to be a corrupted dbuild cache directory.

**Comment by adriaanm** [comment]
The last commit's fine. Glitch in the bot is keeping it from turning green (already tried PLS SYCNH)

**Comment by retronym** [comment]
ping @gkossakowski

**Comment by gkossakowski** [comment]
I remember about this PR and others assigned to me. I'll be catching up with my reviews tomorrow and over the weekend.

**Comment by gkossakowski** [comment]
LGTM.

The code in each commit looks fine although 7d1e8aa and 7ee1a83 show that we really need to streamline the code structure of our backend(s) to ease maintenance.

The commit messages could be a little bit improved but my biggest concern was address with the comment on a commit which is a fine compromise given the fact I was behind my review duties. I'll try to rebuild the last commit and if tests pass I'll merge this.

**Comment by gkossakowski** [comment]
[edit -- not necessary] please rebuild f9cbcbd

**Comment by adriaanm** [comment]
I never got around to making the syntax more user-friendly (i didn't want to implement look ahead), so the second part of the command has a slash instead of a space after rebuild.

**Comment by adriaanm** [comment]
As noted above, the build was fine but the reporting got into an inconsistent state.

**Pull request merged**
