### PR TITLE
Leverage this.type

### PR DESCRIPTION
**Pull request by som-snytt**
Useful observations from https://github.com/scala/scala/pull/10093

Additional case overlooked in https://github.com/scala/scala/pull/10194

### CODE REVIEW

**Comment by lrytz** [comment]
If me merge https://github.com/scala/scala/pull/10166, then this PR would be much smaller, right? If that one LGTY I'll merge it.

**Comment by som-snytt** [comment]
@lrytz probably I wasn't paying attention. For this PR, I was just trying to close my PRs. I forgot your PR, which I will look at during my next waking cycle. Thanks again for your patience. I just said somewhere, Lukas is too nice to say, Do you even know what you are talking about? I don't pretend that much.

**Comment by som-snytt** [comment]
oh, I see, that's for the extra `(_)` which are charming in their way.

**Comment by lrytz** [comment]
> oh, I see, that's for the extra `(_)` which are charming in their way

... ah, but even with https://github.com/scala/scala/pull/10166 merged, the emoji-style eta expansion has to stay until we restarr...  `( · _ · )`

**Review by lrytz — APPROVED** [review]

**Pull request merged**
