### PR TITLE
Disallows formerly deprecated case class definitions without parameter list

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
The commits/errors don't seem to be related to this pull request ... am I missing something or is Jenkins broken again?

**Comment by adriaanm** [comment]
unfortunately the commits listed there are not directly related to the job being run -- they're the log since the last time the job ran, not the commits in the PR (I think we'd have to write a jenkins plugin to fix that)

the failures seem legit

**Comment by paulp** [comment]
Failure singular I think, one scaladoc failure, due to this file. test/scaladoc/resources/Trac4325.scala

**Comment by soc** [comment]
See #1769.

**Pull request closed without merging**
