### PR TITLE
SI-6484 adds Universe.typeOf[T](x: T)

### PR DESCRIPTION
**Pull request by xeno-by**
This is a nice addition to Universe.typeOf[T], quite frequently useful
for inspecting ad-hoc types.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @retronym

**Comment by xeno-by** [comment]
This change looks backward compatible, right?

**Comment by retronym** [comment]
> This change looks backward compatible, right?

Introducing overloads runs a risk of source incompatibility. It can also make the API a little harder to understand ("which overload is this code calling?" / "which one of these overloads should I call?") and makes the error messages for inapplicable arguments harder to read.

But of course, it's sometimes convenient not to introduce a new name.

As an exercise, if overloading wasn't available, what name would you choose for the new methods? `typeOfInstance`, perhaps?

**Comment by xeno-by** [comment]
Or maybe `typeOfExpr`.

Actually we have several valid failures in the Jenkins log that expose some problems with these two overloads. I'll try to get to them tomorrow.

**Comment by paulp** [comment]
This situation comes up for me with some frequency. Anytime you have a nullary method with type parameters, then if a value of the right type comes along, it will be more convenient to pass the value and let type inference do the heavy lifting than it will be to apply the type explicitly. Overloading has noticeable downsides; so do all the other angles I am aware of. It would be nice to file down some of the friction somewhere such that there is a clearly best way to do it.

**Comment by xeno-by** [comment]
Needs further elaboration, which I don't have time to do right now.

**Pull request closed without merging**
