### PR TITLE
SI-6035 - retain specialized flag in separate compilation.

### PR DESCRIPTION
**Pull request by axel22**
This solution does not pickle the `specialize` flag on the symbol of the specialized type parameter.
Instead, it recreates the `specialize` flag on a type parameter during the unpickling process if it sees the `specialize` annotation on that type parameter.

Unable to include a test case, since this would require separate compilation,
which cannot be simulated in partest.

For documentation purposes, the test files in the specialized
test group are included.

https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/203/console

Review by @paulp, @gkossakowski, @VladUreche.

### CODE REVIEW

**Comment by VladUreche** [comment]
Alex, maybe you could you test it by including a .class file and unpickling the signature and checking it has the SPECIALIZED flag. Could that work?

**Comment by axel22** [comment]
I'm not completely sure how to obtain the class file produced by partest to test the newest compiler version.
I could either:
1) extract some class file from stdlib using the classloader
2) or call the compiler on a class file directly

Dunno, seems like fiddling to me. For that kind of tests, we need a proper infrastructure.
For separate compilation test-cases in particular.

**Comment by lrytz** [comment]
you can test separate compilation in partest, see https://github.com/scala/scala/tree/master/test/files/pos/t3864 for example

**Comment by axel22** [comment]
Isn't that just a test-directory with several files which get compiled in one compiler run (no pickling/unpickling involved)?

**Comment by VladUreche** [comment]
I don't understand what Lukas meant either...

**Comment by lrytz** [comment]
files with different postfixes (`_1`, `_2`) get compiled separately with previous classfiles on the classpath.

**Comment by axel22** [comment]
Talk about wizardry :) Kudos, man.

But r u sure it works outside `pos`?

**Pull request closed without merging**
