### PR TITLE
SI-7383 - call ExecutionContext.prepare in Future.apply

### PR DESCRIPTION
**Pull request by viktorklang**
https://issues.scala-lang.org/browse/SI-7383

Review by @phaller, @adriaanm

ExecutionContext.prepare is meant to be used as a way to capture context like ThreadLocals etc and then reinstating them when the the Runnable is executed.

### CODE REVIEW

**Comment by retronym** [comment]
2.10.x is merged to master as a matter of course, no extra PR is required.

**Comment by retronym** [comment]
Can you please expand the commit comment with a quick mention of the _why_ of this?

**Comment by viktorklang** [comment]
Added comment

**Comment by phaller** [comment]
LGTM!
I guess the comment could be part of the commit message, not only the PR summary.

**Comment by viktorklang** [comment]
Closing this PR so that the commit message will be prettier

**Comment by viktorklang** [comment]
Reopened due to Github being awesome.

Better commit message inc.

**Comment by gkossakowski** [comment]
@phaller: can you have another look?

**Comment by phaller** [comment]
LGTM

**Comment by soc** [comment]
LGTM, too.

**Pull request merged**
