### PR TITLE
SI-8395 Regression in pattern matching with nested binds

### PR DESCRIPTION
**Pull request by retronym**
Regressed in https://github.com/scala/scala/pull/2848. In particular,
see 0cf47bdb5b and 017460e63c.

Because of the regression, this pattern:

```
(s @ (_s @ (_: String)))
```

was translated into `typeTestStep`, rather than a `bindingStep`. This
came down the the use of `unbind` in the `TypeBound` extractor.

My first step was to remove the `unbind`. That led to another
problem: the tree now matches `SymbolAndTypeBound`, which extracted
`symbol = s, tpe = String`, ignoring the `_s`. I changed that
extractor to no longer recursively apply to the sub-pattern tree,
which is what `MaybeTypedBound` used to do.

I also checked for other uses of `unbind` in the match translation.
The only place I found it is in `BoundTree#pt`. I believe that this
usage is correct, or at least, not obviously incorrect.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm, /cc @paulp

**Comment by paulp** [comment]
Digression: nothing like one's own commits from 6+ months prior to heighten one's appreciation for minimal diff sizes. I bet someday tooling could translate some of these diffs into two-parters, one which purely moves code and the other which purely changes. Maybe a three parter: move, rename, modify.

 LGTM.

**Comment by som-snytt** [comment]
A regression digression!  A four parter would include white space changes. And doc comments.  And if a change is applied in a thousand places, maybe you could fold that somehow, instead of telling me the diff is too big, or worse, showing me all of them.  I hope that happens before the clock ticks over on any2stradd.

**Comment by adriaanm** [comment]
LGTM as well -- and yes, a lot of very interesting stuff could be done with teaching version control a thing or two about syntax and semantics.

**Pull request merged**
