### PR TITLE
Some refinement of -Xlint interpolation warning.

### PR DESCRIPTION
**Pull request by paulp**
I had covered a few more cases working on this recently.
The warnings in several more cases involving polymorphism,
currying, and selects vs. idents receive more refined
handling.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @som-snytt

**Comment by som-snytt** [comment]
LGTM, but I'll have to review before the final exam

**Comment by som-snytt** [comment]
What do you get for being #3000.  Did you basically just want to make sure that @retronym wasn't nr 3000?

**Comment by paulp** [comment]
Anything I can do to crush retronym's spirit.

**Pull request merged**
