### PR TITLE
SI-8001 spurious "pure expression does nothing" warning

### PR DESCRIPTION
**Pull request by xeno-by**
`isPureExprForWarningPurposes` doesn’t warn on `()`, but `(): Unit`
leaves it confused. This patch fixes the problem.

The fix is important in the context of the recent split between blackbox
and whitebox macros. Macro engines wrap expansions of blackbox macros
in type ascriptions, so a macro that expands into `()` would actually
produce `(): Unit`, which would trigger a spurious warning. Thanks
@milessabin for spotting this problem!

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
LGTM. An alternative would be to omit the `Typed` node if it is redundant, but I'm just as happy with this solution.

**Comment by som-snytt** [comment]
Moi aussi. I made the same change this afternoon as an exercise (though it's just busy work for you).

A useful secondary effect is that it no longer warns if the subtree is already error typed.

**Comment by retronym** [comment]
@xeno-by Looks like it needs a checkfile update.

**Pull request merged**
