### PR TITLE
Small code improvement in build definition

### PR DESCRIPTION
**Pull request by rituraj2342**

### CODE REVIEW

**Comment by som-snytt** [comment]
I'd suggest collecting one-liner style changes into a single PR, to reduce overhead of notifications and CI runs. These are minor edits.

**Comment by rituraj2342** [comment]
> I'd suggest collecting one-liner style changes into a single PR, to reduce overhead of notifications and CI runs. These are minor edits.

Sure @som-snytt . BTW, Is there any way, to test CI locally.?It will reduce time and unnecessary commits.

**Comment by som-snytt** [comment]
yes, see the github readme around `Build setup`, scrolling down. See the bootstrapping step. Depending on what you touch, there may be smaller bits to test, but frankly I have to study the build if I deviate from common usage. For a quick change to check that it works, I don't mind publishLocal and testAll just once.

**Review by SethTisue — APPROVED** [review]
I took the liberty of squashing this into a single commit. Let’s hit “merge” as soon as CI likes it.

**Comment by rituraj2342** [comment]
> I took the liberty of squashing this into a single commit. Let’s hit “merge” as soon as CI likes it.

@SethTisue All checks passed, You can merge this.

**Pull request merged**
