### PR TITLE
Escape dollar signs for variables in doc comments

### PR DESCRIPTION
**Pull request by ashawley**
This is the 2.13 follow-up of #8290.

### CODE REVIEW

**Review by som-snytt — APPROVED** [review]
We need more 2.13 follow-up. I'm not sure what backslash does inside backticks.

**Comment by lrytz** [comment]
Thanks @ashawley & @som-snytt

**Comment by ashawley** [comment]
> I'm not sure what backslash does inside backticks.

I had the same concern.  It seems variable expansion, including variable escaping,  is first.  This happens regardless of source context (backticks, code blocks, HTML...).

**Comment by som-snytt** [comment]
Thanks again for caring about escaped dollar signs. This is what makes the world go around, which may come as a surprise to other people who only care about dollar signs and assume they are responsible for the ongoing rotation of the globe.

**Pull request merged**
