### PR TITLE
taming outer refs: anon-closures that retain fewer heap objects

### PR DESCRIPTION
**Pull request by magarciaEPFL**
This PR supersedes https://github.com/scala/scala/pull/2633

Original discussion at https://groups.google.com/forum/#!topic/scala-internals/jQiRINTvhZQ

review by @JamesIry or @paulp

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
PLS SYNCH

**Comment by magarciaEPFL** [comment]
PLS NO SPURIOUS FAILURE

**Comment by adriaanm** [comment]
PLS REBUILD/pr-checkin-per-commit@266a117

**Comment by Blaisorblade** [comment]
As I mentioned in https://groups.google.com/d/msg/scala-internals/jQiRINTvhZQ/4zD7sVbkZiIJ, this can't go in as is, because it builds on what @paulp called "semantics out of a nightmare", to general agreement, just because final is overloaded.

**Comment by magarciaEPFL** [comment]
@Blaisorblade , it would help if you could provide a self-contained example, indicating what output you see and which one you would like to see.

It's also not clear whether the behavior you're talking about:
1. was there before this PR, or 
2. is introduced by this PR.

**Comment by Blaisorblade** [comment]
@magarciaEPFL, sorry if I wasn't clear enough. My email does contain a self-contained example (I double-checked, only the line number in the error is wrong; I can reproduce this with 2.10.2).

I'm talking about a behavior which was there before this PR and that you're extending. Namely (and I quote your mail):

"There's an optimization in the constructors phase that eliminates the outer-field of an inner-classes C (in particular, an anon-closure-class) when the following conditions are met:
- C is final
- its outer field is not accessed"

This optimization was found to be a very bad idea (I kind of explained why in my mail on scala-internals), and it was agreed to remove it from 2.11.

Should the above not be clear, please feel free to ignore my example and follow the link to the original discussion, which I already provided in my scala-internals mail. Here's again the link to the original discussion:
https://groups.google.com/d/msg/scala-internals/vw8Kek4zlZ8/LAeakfeR3RoJ

**Comment by magarciaEPFL** [comment]
@Blaisorblade , thanks for the pointer, I hadn't read the latest on that discussion. I'll catch up tomorrow and review this PR in that light.

**Comment by magarciaEPFL** [comment]
@Blaisorblade , The behavior in question (documented in https://issues.scala-lang.org/browse/SI-4440, lack of `outer$` comparison in `equals()` of a final inner case class) is indeed a bug, but unrelated to the constructors phase.

To see why, it's enough to look at the auto-generated `equals()` _before_ it reaches the constructors phase, as shown below. Indeed, for a final inner case class that comparison is missing. That's a bug, but not in constructors, and certainly not in this PR. Given the input AST, both constructors and this PR are doing the right thing (as they can't do otherwise, they can't fill-in the missing `outer$` comparison in the `equals()` method). Rather, the root cause of the bug must be fixed in the synthesizer of said `equals()`

``` scala
// with-final
[[syntax trees at end of              lambdalift]]

  class Outer extends Object {
    final case class Inner extends Object with Product with Serializable {


    . . .

      override <synthetic> def equals(x$1: Object): Boolean =
        Inner.this.eq(x$1).||(
        {
          case <synthetic> val x1: Object = x$1;
          case5(){
            if (x1.$isInstanceOf[Outer#Inner]().&&(true))
              matchEnd4(true)
            else
              case6()
          };
          case6(){
            matchEnd4(false)
          };
          matchEnd4(x: Boolean){
            x
          }
        }.&&({
          <synthetic> val Inner$1: Outer#Inner = x$1.$asInstanceOf[Outer#Inner]();
          Inner.this.n().==(Inner$1.n())
        })
        );
```

**Comment by magarciaEPFL** [comment]
@Blaisorblade , Additionally, to show that constructors and this PR do the right thing when the input AST contains the `outer$` comparison, it's enough to look at the AST for `equals()` after constructors, where it can be seen the `outer$` field hasn't been elided (to obtain correct input, as already noticed in the discussion, currently one has to omit the final modifier from the inner case class). Here's the snippet in question:

``` scala
// without-final
[[syntax trees at end of              constructors]]

  class Outer extends Object {
    case class Inner extends Object with Product with Serializable {


    . . .


      override <synthetic> def equals(x$1: Object): Boolean = Inner.this.eq(x$1).||({
  case <synthetic> val x1: Object = x$1;
  case5(){
    if (x1.$isInstanceOf[Outer#Inner]().&&(
     (x1.$asInstanceOf[Outer#Inner](): Outer#Inner).$outer().eq(Inner.this.$outer()))
    )
      matchEnd4(true)
    else
      case6()
  };
  case6(){
    matchEnd4(false)
  };
  matchEnd4(x: Boolean){
    x
  }
}.&&({
        <synthetic> val Inner$1: Outer#Inner = x$1.$asInstanceOf[Outer#Inner]();
        Inner.this.n().==(Inner$1.n()).&&(Inner$1.canEqual(Inner.this))
      }));
```

Deeply buried above:

``` scala
    if (x1.$isInstanceOf[Outer#Inner]().&&(
     (x1.$asInstanceOf[Outer#Inner](): Outer#Inner).$outer().eq(Inner.this.$outer()))
    )
```

**Comment by Blaisorblade** [comment]
And if the synthesizers of equals were fixed, then $outer would not be omitted? That's interesting.

Still, that's not the only example (if I provided a misleading example, my apologies).

Adriaan Moors wrote in https://issues.scala-lang.org/browse/SI-4440?focusedCommentId=58989#comment-58989:

> we used to drop outer accessors from nested final classes if the outer-accessor wasn't accessed anywhere
> however, for the sake of separate compilation and the outer checks inserted by the pattern matcher,
> we must assume they might be accessed anywhere

and later:

> In 2.11 we'll do the right thing: the final modifier is not a sufficient condition for omitting the outer pointer.
> If we can come up with some kind of optimization (hard to do if you can't assume a closed world), we'll optimize
> memory usage there.
> In the mean time, if you don't want an outer pointer, don't nest your class.

IMHO, that means that given:

```
class Outer {
  final case class Inner
}
```

you can still write _anywhere_ else:

```
def matchInner(o: Outer)
  v match {
    case o.Inner => ...
  }
```

and this code can only be translated correctly by the pattern matcher by checking `$outer`. If `Inner` is not private, anybody could come later and write code like `matchInner`, so $outer is part of the ABI and one can't check that it is not used. Hence, no `$outer` can be elided safely without extra side conditions. If the optimization is disabled, the optimization in this pull request will be disabled as well.

However, an alternative would be to fix the side conditions: `Inner` is private and no such pattern match appears would be sufficient. Maybe anonymous inner classes are also safe: how would you write `matchInner` if you can't name `Inner`? Finally, one could have an annotation to request the memory savings anyway.

**Comment by magarciaEPFL** [comment]
@Blaisorblade ,

It's not that
(1) constructors is eliding the `outer$` field and then the pattern matcher can't compare two `Outer.Inner` values properly

Instead,
(2) whoever synthesizes the `equals()` of `Outer.Inner` is eliding the `outer$` comparison (that must be, like, in the whereabouts of the pattern matcher)

The root cause is (2).

As a sideshow, constructors then elides the outer field. To repeat: as a consequence, not the root cause. Fix the root cause and constructors will do the right thing (which is: what it's doing today).

**Comment by Blaisorblade** [comment]
Please forget about `equals`, it's irrelevant. I apologize for using again a misleading example. Below's the fixed one, tested this time. Complete results, with the output of the relevant intermediate phases, are available under https://gist.github.com/Blaisorblade/5745026.

`$outer` should be there regardless of `equals`, to support **typed matches**, that is, `case x : o.Inner =>`, which needs to compare `x.$outer` with `o.$outer`. To see this, let's make `Inner` _not_ a case class, so that no equals is generated, yet typed pattern matches are possible.
File 1:

```
class Outer {
  final class Inner
}
```

Here, the constructors phase will drop the $outer field.

File 2:

```
object Matcher {
  def matchInner(v: Any, o: Outer) =
    v match {
      case v2: o.Inner =>
    }
}
```

Before explicitouter, the pattern match is [`if (x1.isInstanceOf[o.Inner]().&&((x1.asInstanceOf[o.Inner](): o.Inner).<outer>().eq(o)))`](https://gist.github.com/Blaisorblade/5745026#file-bugouterpart2-under-2-10-2-out-L12). After explicitouter, the condition becomes [`if (x1.isInstanceOf[o.Inner]().&&(true))`](https://gist.github.com/Blaisorblade/5745026#file-bugouterpart2-under-2-10-2-out-L40).

If `explicitouter` is fixed to not remove the `$outer` check, `constructors` must be fixed to not drop the field to prevent linker errors.

**Comment by magarciaEPFL** [comment]
That's a good catch. Let's see how the ticket gets fixed, your observation and example regarding explicitouter conveys the essence of the problem quite succinctly.

As to this PR and constructors, once the "right thing to do" is agreed upon, constructors and this PR can be adapted (in particular, this PR can focus on anon-closures, which should be safe, because the fact an inner class realizes an anon-closure is a leaky abstraction, an implementation decision that may change in the future).

**Comment by magarciaEPFL** [comment]
Thinking about the timing of the fix for SI-4440 and the (eventual) merge of this PR, I'd be still in favor of merging this PR, given that adapting it to "anon-closures only" is straightforward enough. Moreover, for anon-closures, all of the `outer$` elision analysis in constructors would still be necessary (even if that same analysis _should not_ be used for non-anon-closures).

**Comment by Blaisorblade** [comment]
That's a valid point. I agree on "anon-closures", and since the optimization probably can be adapted even beyond that case, I can see why this can make indeed sense.

**Comment by magarciaEPFL** [comment]
@Blaisorblade 

> Before explicitouter, the pattern match is `if (x1.isInstanceOf[o.Inner]().&&((x1.asInstanceOf[o.Inner](): o.Inner).<outer>().eq(o)))`. After explicitouter, the condition becomes `if (x1.isInstanceOf[o.Inner]().&&(true))`.

Just to add more details about where in `ExplicitOuter` that rewriting is performed, it's here: 

https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala#L499

The comment for that case-clause is:

``` scala
  // for the new pattern matcher
  // base.<outer>.eq(o) --> base.$outer().eq(o) if there's an accessor, else the whole tree becomes TRUE
  // TODO remove the synthetic `<outer>` method from outerFor??
  case Apply(eqsel@Select(eqapp@Apply(sel@Select(base, nme.OUTER_SYNTH), Nil), eq), args) =>
```

**Comment by gkossakowski** [comment]
@magarciaEPFL: this cannot be merged anymore. Can you rebase, please?

From the discussion I read in this PR it seems like we'll be able to merge it once it's rebased. However, this is rather tricky stuff so me or @JamesIry will need to review it once it's rebased.

**Pull request closed without merging**
