### PR TITLE
SI-5330, SI-6014 deal with existential self-type

### PR DESCRIPTION
**Pull request by adriaanm**
This has been broken since https://github.com/scala/scala/commit/b7b81ca2#L0L567.
The existential rash is treated in a similar manner as in fc24db4c.

Conceptually, the fix would be `def selfTypeSkolemized = widen.skolemizeExistential.narrow`,
but simply widening before narrowing achieves the same thing. Since we're in existential voodoo territory,
let's go for the minimal fix: replacing `this.narrow` by `widen.narrow`.

review by @odersky

### CODE REVIEW

**Comment by odersky** [comment]
This looks fishy and will be disastrous from a performance standpoint. Narrow is expensive unless the type is already a singleton type. Widen makes sure it isn't.

**Comment by odersky** [comment]
In fact, I think it would be OK to outlaw existential self types.

**Comment by retronym** [comment]
What could be outlawed in this case?

  https://github.com/scala/scala/pull/1074/files#L1R1

**Comment by retronym** [comment]
A couple ideas for performance:
1. Can we shortcut the `.widen.narrow` dance if the 'this' type doesn't contain existentials?
2. Can we avoid `self.memberType(other) matches symtpe` if `!(sym.isOverride && other.isOverridableSymbol)`.

I repeat @paulp's comments from `isOverriddingSymbol` which might be relevant in determining whether we can take the second shortcut.

``` scala
/** Equivalent to allOverriddenSymbols.nonEmpty, but more efficient. */
    // !!! When if ever will this answer differ from .isOverride?
    // How/where is the OVERRIDE flag managed, as compared to how checks
    // based on type membership will evaluate?
    def isOverridingSymbol = owner.isClass && (
      owner.ancestors exists (cls => matchingSymbol(cls, owner.thisType) != NoSymbol)
    )
```

**Pull request closed without merging**
