### PR TITLE
improves showRaw

### PR DESCRIPTION
**Pull request by xeno-by**
addresses concerns raised in http://groups.google.com/group/scala-user/browse_thread/thread/de5a5be2e083cf8e

### CODE REVIEW

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by odersky** [comment]
I think the logic that prints flags is a duplicate for something that's done in internal.Flags. Compare with flagToString there.

**Comment by xeno-by** [comment]
@odersky thanks for the hint - I suspected that something's not right. How do you like it now?

**Comment by odersky** [comment]
LGTM now.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Note: Failure looks accurate....  Did you miss a fixed test in the updated commit?

**Comment by xeno-by** [comment]
Yes, forgot to commit it. Fixed now.

PLS REBUILD ALL.

**Comment by jsuereth** [comment]
Note: The PLS is only needed if there's no corresponding new commit.  The build bot should detect a commit more recent than the last build status.

**Pull request merged**
