### PR TITLE
SI-6451: Rename classes in `unchecked-abstract.scala` test.

### PR DESCRIPTION
**Pull request by gkossakowski**
As reported Miguel, `Con` is problematic name of a class on Windows
and makes this test to fail. Renamed classes to something else which
hopefully make Windows build happy again.

Closes SI-6451.

Review by @magarciaEPFL or @paulp.

### CODE REVIEW

**Comment by paulp** [comment]
Not that I'm volunteering, but what we really need is some means of preventing this from happening again.  "Con" is not exactly a far-fetched name for a class, and nobody who doesn't use windows is ever going to have a clue it is a problem.  It isn't just this; it is all the platform-specific idiosyncrasies which exert constant friction against making certain kinds of improvements.  (The absence of any script tests, the paralyzation of jline, etc. etc.)

I realize the response is "sounds great, we need to fix this now though" and this gets fixed and we go back to waiting for the next occasion.  Only a very motivated windows-using person is likely to make any improvement in this situation.

**Comment by gkossakowski** [comment]
@paulp: I think we are a lot better than a few months ago. I looked recently at our build stability and since pull request validator has been introduced our stability dramatically improved.

I think we can easily afford hiccups from time to time. This is one of them.

Now, can we have your LGTM so our next nightly is green again? :-)

**Comment by retronym** [comment]
Just fascinating stuff:

> Windows forbids the use of the MS-DOS device names AUX, CLOCK$, COM1, …, COM9, CON, LPT1, …, LPT9, NUL and PRN, as well as these names with any extension (for example, AUX.txt), except when using Long UNC paths (ex. \.\C:\nul.txt or \?\D:\aux\con). (CLOCK$ may be used if an extension is provided.)

**Comment by gkossakowski** [comment]
@retronym: Interesting, where did you find this quote? :-)

Also, can we have LGTM for this finally?

**Comment by retronym** [comment]
LGTM.

The quote was from Wikipedia.

I was wondering how javac deals with this. You can't create a file `Con.java`, but you can sneak in a non-public class at the bottom of another file.

```
C:\Users\zgg>cat Test.java
public class Test {
}

class Con {
}
C:\Users\zgg>javac Test.java
╩■║¥   2
 ♥
 ♂ ♀☺ ♠<init>☺ ♥()V☺ ♦Code☺ ☼LineNumberTable☺
SourceFile☺     Test.java♀ ♦ ♣☺ ♥Con☺ ►java/lang/Object   ☻ ♥     ☺   ♦ ♣ ☺ ♠
↔ ☺ ☺   ♣*À ☺▒   ☺    ♠ ☺   ♦    ☻
```

**Comment by gkossakowski** [comment]
@retronym: What does weird characters mean then? :-)

**Comment by retronym** [comment]
That's javac writing the bytecode out to a `new FileOutputStream(new File("Con.class"))`. These go to the console:

```
C:\Users\zgg>echo foo
foo

C:\Users\zgg>echo foo > CON
foo

C:\Users\zgg>echo foo > NUL
```

The bytes are interpreted by the windows console according to the current ANSI code page.

I'm on [code page 850](http://en.wikipedia.org/wiki/Code_page_850):

```
C:\Users\zgg>chcp
Active code page: 850
```

Which, like [Code Page 437](http://en.wikipedia.org/wiki/Code_page_437#Interpretation_of_code_points_1.E2.80.9331_and_127) interprets control characters as some cute graphics:

> Code points 1–31 and 127 (00–1Fhex and 7Fhex) may be interpreted as control or graphic characters, depending on the context. When used in a memory-mapped video display buffer, the code point is displayed as the graphic shown in the table of special graphic characters below

Thus ends our history lesson into FAT and ANSI :)

**Comment by gkossakowski** [comment]
@retronym you've won a prize for best commentary on a pull request I saw in a while! :-)

**Comment by SethTisue** [comment]
https://twitter.com/Foone/status/1058676834940776450

**Pull request merged**
