### PR TITLE
Upgrade Dotty to 3.0.0-M3

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by SethTisue** [comment]
CI failure might go away with sbt 0.4.6->0.5.0 upgrade?

**Comment by anatoliykmetyuk** [comment]
I believe "combined" fails because the previous commit failed. The most recent commit appears to pass.

**Comment by lrytz** [comment]
👍 we usually squash changes into self-contained commits for a simpler git history

**Review by SethTisue — APPROVED** [review]
squashed; let's merge once CI likes it again

**Pull request merged**
