### PR TITLE
SI-7261 BooleanSetting to Boolean conversion

### PR DESCRIPTION
**Pull request by som-snytt**
Add an implicit for BooleanSetting to Boolean, since while we never expect the Spanish Inquisition, we do expect a boolean in an if clause.

The first cut put the implicit at AbsScalaSettings, but the more general case is at reflect/internal's MutableSettings.  There was no particular desire to privilege mutability.

There is an additional implicit to convert BooleanSetting to BooleanFlag, in the second commit.  Maybe you knew there was a BooleanFlag.

The second commit tries to be minimalist, just to 6x the `.value`.  There are two or three spots where an expression has been restructured, but no intentional changes in behavior.

Review by @paulp who liked the idea and @retronym who has already egged on.

### CODE REVIEW

**Comment by retronym** [comment]
Surely there are more place to take advantage of this.

**Comment by som-snytt** [comment]
If the concept is good, I'll add a commit that converts to conversions everywhere.

**Comment by som-snytt** [comment]
Closing until it comes again.

**Comment by som-snytt** [comment]
Reopening with advantages. The implicit is on reflect's MutableSetting.

Since I don't know why the PR has to show other history, would it help if I closed this and created a new PR?

**Comment by paulp** [comment]
Somehow there are 8 commits in this PR, most of which don't belong. Closing for repairs.

**Comment by som-snytt** [comment]
I wish I understood what sequence of keystrokes produced the bad PR after I pushed -f. It's like, excuse the metaphor, they keep insisting the transporter on the Enterprise is perfectly safe, you won't lose anything, then one day you're totally scrambled.

**Pull request closed without merging**
