### PR TITLE
Removals for 2.11 — The (hopefully) uncontroversial parts

### PR DESCRIPTION
**Pull request by soc**
Not removed:
- scala.collection.convert deprecations
- Manifests
- Code required by scala.xml or scala.actors

### CODE REVIEW

**Comment by paulp** [comment]
This all looks good to me, except the redblack scalacheck test appears salvageable. Those are generic red/black tree invariants, right? Can you keep the test and apply it to the new RedBlackTree?

**Comment by soc** [comment]
@paulp Luckily, that's already the case in test/files/scalacheck/redblack.scala!

**Comment by paulp** [comment]
It's duplicated? Of course, I should have known. Thanks.

**Comment by soc** [comment]
No problem. :-) Do you think I should split up this commit a bit? Or is it OK this way?

**Comment by paulp** [comment]
I guess it depends on whether you get any pushback. You won't get any from me.

**Comment by gkossakowski** [comment]
I'd prefer this change to be broken into smaller chunks focused on particular subject (e.g. removing conversions). The reason is that it's easier to revert if it turns out we have a very good reason to do that.

**Comment by soc** [comment]
As mentioned, the collection conversions are not in this commit, just a lot of “misc” stuff. Which subjects would you suggest?

**Comment by soc** [comment]
Ok, what do you think of:
- Collections
- Enumeration
- Cloneable
- Serializable
- Predef
- Annotations
- IO/Marshall/Testing
- Grammar
- misc.

**Comment by gkossakowski** [comment]
@soc: I misread your comment, if you didn't intend to touch conversions, what about: https://github.com/scala/scala/pull/1918/files#L11L297 ?

**Comment by soc** [comment]
That's related to the removal of `mutable.ConcurrentMap`. The wrapper was removed because the class is gone completely.

**Comment by soc** [comment]
I split it up, new PR is https://github.com/scala/scala/pull/1921.

**Pull request closed without merging**
