### PR TITLE
no Windows line endings in repo plz!

### PR DESCRIPTION
**Pull request by SethTisue**
CRLF line endings have been allowed to creep into a number of files in the repo. this fixes them.

CRLF = faux pas; LF = de rigeur. keep the repo comme il faut, eschew ASCIIa non grata.

at bare minimum, GenASM.scala ought to be fixed. the others are less important, but still good to have fixed, I think.

I tested this on Mac OS X by running `git clean -fdx` followed by `ant dist`; all tests passed.

### CODE REVIEW

**Comment by paulp** [comment]
I don't think this kind of maintenance is a necessary part of life.  How about we don't merge a commit like this without changing the buildbots so that _the build fails_ if you try to introduce the wrong line endings in the repo.  In the absence of a pre-commit hook, which would be better yet, we have to get computers involved here somewhere.  Talk about your "not worthy of a human" activities.

**Comment by adriaanm** [comment]
Unfortunately this doesn't merge anymore.

@jsuereth, could you add this to the automation todo list?

**Comment by jsuereth** [comment]
Sure.  We already have scripts to dos2unix everything.  I'll look into adding a line ending check to the build bot.

**Comment by xeno-by** [comment]
If you convert CRLF's to LF's in Windows batch files, they will stop working (same for the tmpl file used to generate Windows batch files).

**Comment by jsuereth** [comment]
Not 100% true.  Windows 7 works for me for some reason.
On Jul 16, 2012 7:32 PM, "Eugene Burmako" <
reply@reply.github.com>
wrote:

**Comment by paulp** [comment]
I don't know this firsthand, but as I understand things, the git repo on windows is supposed to get native line endings on checkout, which are turned into LF on checkin.  I think it's "core.autocrlf = input" in git.config.

**Comment by paulp** [comment]
Oh, it's "core.autocrlf=true" on windows, since input only converts going in.

**Comment by xeno-by** [comment]
I use `core.autocrlf = false`, so it's not a given that everyone on Windows will have native eolns.

But regardless of that I think we need to keep CRLF's in batch files, so that if anyone on Unix builds Scala, batch files get correct line endings.

**Comment by jsuereth** [comment]
Which breaks things, last I tried....
On Jul 17, 2012 12:01 PM, "Paul Phillips" <
reply@reply.github.com>
wrote:

**Comment by SethTisue** [comment]
fwiw, here's how to find all the text files with carriage return characters. works in both bash and zsh:

``` shell
git grep -lI $'\r'
```

I didn't know about `dos2unix`, thanks for that. `brew install dos2unix` ftw.

**Comment by lrytz** [comment]
The windows line endings in `GenASM.scala` are gone since a6b0250b81

**Comment by SethTisue** [comment]
ha you beat me by 2 seconds

**Comment by adriaanm** [comment]
ha! :-)

**Comment by SethTisue** [comment]
I recently learned that Git has improved support for EOL character handling. You add a `.gitattributes` file to the repo. It's better than the old `autocrlf` stuff. See http://timclem.wordpress.com/2012/03/01/mind-the-end-of-your-line/ for a full account.

**Comment by paulp** [comment]
Thanks a ton, I hadn't heard about this.

"This means that line endings can be encapsulated entirely within a repository and don’t depend on everyone having the proper global settings."

Slow, sarcastic clapping for git developers having figured out that depending on everyone making the same settings changes was suboptimal.

**Pull request closed without merging**
