### PR TITLE
Clean up Scala distribution a bit.

### PR DESCRIPTION
**Pull request by adriaanm**
Prompted by https://issues.scala-lang.org/browse/SI-4248, 
which pointed out we should include doc/licenses in the binary dist,
I finally decided to clean up the dist a bit -- even for 2.10.x.

No more:
- partest in the binary dist
- redundant examples in scala/scala -- they actually come from scala/scala-dist
- references to windows 95 in our readme
- unused android test

Also added the Typesafe attribution that was agreed on earlier.

Review by @retronym, /cc @heathermiller, @gkossakowski, @jsuereth

### CODE REVIEW

**Comment by adriaanm** [comment]
To build a release, https://github.com/scala/scala-dist/pull/110 will have to be merged first.

**Comment by adriaanm** [comment]
I've tested off-line and will take care of this as soon as this PR's merged.

**Comment by retronym** [comment]
LGTM

**Comment by adriaanm** [comment]
I don't see how this could cause:

```
Failed tests:   notEnoughArgumentsForCconstructorError_ShouldNotBeReported_t1000692(scala.tools.eclipse.pc.PresentationCompilerTest): expected 1 link, found 0 expected:<1> but was:<0>
```

Especially since this didn't fail for the subsequent (but otherwise unrelated) commits. Looks like a spurious fail. Need to ebase anyway, so we'll see. (See https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4599/console)
/cc @dotta

**Comment by dotta** [comment]
@adriaanm Looks indeed spurious. Will have a look, thanks! \cc @huitseeker

**Comment by adriaanm** [comment]
the diff to the [previously tested commit](https://scala-webapps.epfl.ch/jenkins/job/pr-scala/5131/) is solely rewording in docs/LICENSE:

```
g diff e96275..27a38602de --stat
 docs/LICENSE | 32 ++++++++++++++++----------------
 1 file changed, 16 insertions(+), 16 deletions(-)
```

Merging to get things going. PR bot is overloaded`

**Pull request merged**
