### PR TITLE
Offer “did you mean” for assignment ops

### PR DESCRIPTION
**Pull request by som-snytt**
Backport the latest Dotty research on recommending members of nearly identical spelling. (MONIS.)

Bumps the edit distance to consider, sorts the result, and presents up to 4 suggestions. Those that are not first-rank receive a qualifying, "or perhaps?" An ellipsis indicates when there are other candidates not presented to the user.

Avoid suggesting `wait` for `priv` or `name` (that is more of a Wordle move). The tweaked restriction is that the edit distance cannot exceed half the word length (for either user identifier or candidate), but if all the chars written by the user appear in the candidate string, then use it, since swaps and repetitions are common typos. For example, for `acb` suggest `abc` but not for `ade`. (Tempted to take `ade` because of the common prefix.)

Sample dotty:
```
scala> c.priv
-- [E008] Not Found Error: ---------------------------------------------------------------------------------------------
1 |c.priv
  |^^^^^^
  |value priv is not a member of C - did you mean c.wait?
1 error found
```

Avoid offering advice for setter, as in this dotty message:
```
1 |def v = c y_= 1
  |        ^^^^^
  |        value y_= is not a member of C - did you mean c.x_=?
```
but do advise on `++=`.

It is slightly incongruous to suggest `did you mean +++ or x_=?` probably because the shared element is the suffix `_=` or just `=`. Maybe edit distance should be 1 for the shortest identifiers. More precisely, when comparing two setters, strip the suffix first. Then normal criterion says don't recommend `x` for `y`, which would be tedious.

Dotty offers only one suggestion:
```
scala> "xyz".lengt
-- [E008] Not Found Error: ---------------------------------------------------------------------------------------------
1 |"xyz".lengt
  |^^^^^^^^^^^
  |value lengt is not a member of String - did you mean ("xyz" : String).length?
1 error found

scala> "xyz".lgnet
-- [E008] Not Found Error: ---------------------------------------------------------------------------------------------
1 |"xyz".lgnet
  |^^^^^^^^^^^
  |value lgnet is not a member of String - did you mean ("xyz" : String).lines?
1 error found
```
now we exclude `lines` in the first case (edit distance compared to token length) but include `length` in the second (because it is a word scramble):
```
scala> "xyz".lengt
             ^
       error: value lengt is not a member of String
       did you mean length?

scala> "xyz".lgnet
             ^
       error: value lgnet is not a member of String
       did you mean lines? or perhaps length?
```

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM but I'm wondering about 90c1fa888b3651f416de3e38381c5425d659f09a, what's that about?

**Comment by som-snytt** [comment]
@SethTisue https://discord.com/channels/632150470000902164/632628489719382036/1063609622113562724

I haven't tested javac on this score yet. I noticed `scalac files 2> errs` will announce `19 errors` on stdout. It is more obvious for all error output to go to stderr.

But what about warnings? Do they also print to stderr? I hope so. Yes, same for warnings.
```
➜  snips scalac -Xlint warn-only.scala 2> errs
1 warning
```

I vaguely recall considering this question, perhaps before the `reporters` re-refactor, but I didn't go that far back to check. This represents my current thinking.

Dotty uses only stderr, and I opened a ticket to beg them to reconsider.

**Comment by som-snytt** [comment]
I had to think too hard about what javac might warn about.

```
➜  snips javac -Xlint JWarn.java 2> errs
➜  snips cat errs
JWarn.java:5: warning: [empty] empty statement after if
                        ;
                        ^
JWarn.java:6: warning: [deprecation] getId() in Thread has been deprecated
                System.out.println(Thread.currentThread().getId());
                                                         ^
2 warnings
```

BTW scalac could include both the lint name and the `-Wconf` category `cat` name in the message.

**Comment by SethTisue** [comment]
Could 90c1fa888b3651f416de3e38381c5425d659f09a go in a separate PR, or is there some necessary connection to the rest of the changes here?

**Comment by som-snytt** [comment]
Yes, it could.

**Review by SethTisue — APPROVED** [review]
LGTM, but let's wait to merge until https://github.com/scala/scala-dev/issues/827 has been addressed so we can get a go-ahead from Jenkins

**Comment by som-snytt** [comment]
Squashed using artisanal squashing techniques.

**Comment by som-snytt** [comment]
Oh, I needed this today! Except...
```
➜  scala git:(tweak/not-member-help) ✗ scala
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> import collection.immutable.LazyList
import collection.immutable.LazyList

scala> 42 :: LazyList.empty
          ^
       error: value :: is not a member of scala.collection.immutable.LazyList[A]
       did you mean ++: or :++?

scala>
:quit
➜  scala git:(tweak/not-member-help) ✗ skala
Welcome to Scala 2.13.11-20230124-195821-e781990 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> import collection.immutable.LazyList
import collection.immutable.LazyList

scala> 42 :: LazyList.empty
          ^
       error: value :: is not a member of scala.collection.immutable.LazyList[A]
       did you mean +:, /:, :+, or :\? or...?
```
oh man, let me filter out those deprecations.
```
did you mean +: or :+? or perhaps ++: or :++?
```
d'oh! of course it doesn't do conversions yet.
```
scala> 42 :: LazyList.empty
          ^
       error: value :: is not a member of scala.collection.immutable.LazyList[A]
       did you mean #::, +:, or :+? or perhaps #:::? or...?
```
The full list of alternatives to present in this case
```
ALTS[List((1,#::), (1,+:), (1,:+), (2,#:::), (2,++:), (2,:++))]
```
So the final wistful `or...?` is an intimation of the last two results, which happen to be the two low-quality results in 2.13.10.

**Comment by SethTisue** [comment]
so did you want to wait to merge this until you add some of those improvements, or should we book the progress?

**Comment by som-snytt** [comment]
I'll add the commit in just a second. I just excluded `any2stringadd` from the results...

**Comment by som-snytt** [comment]
That second commit was an exceptionally low-throughput slog. "Just give me all the available implicits" and "I just want to exclude the arrow of pairing." Hey, Cupid's arrow is also for pairing. This Valentine's, we should celebrate tuples instead of couples.

**Comment by som-snytt** [comment]
The `run/analyzerPlugins.scala` test showed extra calls because expressions such as `i += 1` induce a failure (because int has no `+=` member). The third commit adds `DeferredTypeError` to capture the mechanism and crank the handle only if the string message is requested. This may be safe for short-term deferral, in this case, as it decides whether the expression can be rewritten or just fail with the error message. It would not be appropriate for long-lived warnings which are buffered indefinitely.

**Comment by som-snytt** [comment]
Maybe I can ask @lrytz to opine on the last commit about deferring the expensive string construction. I think this was an issue in the past, where messages were created and discarded. I haven't measured anything, but the counts in the test made it obvious.

**Comment by som-snytt** [comment]
@SethTisue I dropped the commit for "conversions help" until I review it further (for performance reasons). Rebased just the commit you approved.

**Comment by SethTisue** [comment]
One small step for a man, one giant leap for the Oxford comma.

**Pull request merged**
