### PR TITLE
improvements to HashCollisionMapNode (with array) [ci: last-only]

### PR DESCRIPTION
**Pull request by mkeskells**
only iterate once, reduce lambdas, use array rather then Vector[Tuple2]

### CODE REVIEW

**Comment by retronym** [comment]
If this is the right way forward, we'll want to do the same for `ChampHashSet`.

**Comment by mkeskells** [comment]
@retronym yes - didnt want to change the `Set` implementation at the same time, but we can keep them in-line when we have a winner

**Comment by lrytz** [comment]
Labelled wip; this needs a rebase, a review, and probably benchmarks?

**Comment by mkeskells** [comment]
closing as overtaken by the changes that @joshlemer made

**Pull request closed without merging**
