### PR TITLE
SI-9834 Improve error on failed op=

### PR DESCRIPTION
**Pull request by som-snytt**
If rewriting `x += y` fails to typecheck, emit error messages
for both the original tree and the assignment.

If rewrite is not attempted because `x` is a val, then say so.

### CODE REVIEW

**Comment by som-snytt** [comment]
Consider `s"Can't assign to $qual2"`. Similarly for `s"Missing update method."`.

**Comment by sbromberger** [comment]
Thank you for this PR!

**Comment by SethTisue** [comment]
Is this really high value and low risk enough to target 2.11.x rather than 2.12.x?

**Comment by som-snytt** [comment]
There's a chance it creates even whackier error messages, but they are only error messages.

**Pull request closed without merging**
