### PR TITLE
SI-6231 Report unsupported free var capture by a trait.

### PR DESCRIPTION
**Pull request by retronym**
_Does not close the ticket, merely advances a crasher to an implementation restriction._

If a class nested in a trait captures a free variable from
the enclosing scope of the trait, the transformation to
add that variable to the `init` method of the trait
implementation class happens _after_ the abstract trait
interface has been extracted. This would lead to a crash
when trying to find the corresponding interface method.

This commit detects this situation and reports an
implementation restriction. The enclosed test case
shows a workaround.

To lift this restriction, LambdaLifter should add the getters
and make sure they end up in the trait interface. Looks like
Martin tried this once:

```
// LambdaLift.scala
//
// Disabled attempt to to add getters to freeParams
// this does not work yet. Problem is that local symbols need local names
// and references to local symbols need to be transformed into
// method calls to setters.
// def paramGetter(param: Symbol): Tree = {
//   val getter = param.newGetter setFlag TRANS_FLAG resetFlag PARAMACCESSOR // mark because we have to add them to interface
//   sym.info.decls.enter(getter)
//   val rhs = Select(gen.mkAttributedThis(sym), param) setType param.tpe
//   DefDef(getter, rhs) setPos tree.pos setType NoType
// }
// val newDefs = if (sym.isTrait) freeParams ::: (ps map paramGetter) else freeParams
```

Review by @gkossakowski

### CODE REVIEW

**Comment by gkossakowski** [comment]
LGTM.

@retronym: I really enjoy reviewing your work. Minimal change, precise and elaborate (enough) commentary, good error message and good commit message.

Just a stupid question: couldn't we extract the functionality that extract interface for a trait into something many phases could use? Or is there something in between those two places that depends on `init`s signature so we cannot change it anymore?

**Comment by retronym** [comment]
I don't quite understand your suggestion. I think @odersky's [comments](https://github.com/retronym/scala/blob/f6168b8a4d661985b0fb4d6d3cbba256bfc69607/src/compiler/scala/tools/nsc/transform/LambdaLift.scala#L355) are the best guide we have on what might be the way forward.

**Comment by adriaanm** [comment]
jenkins job pr-scala-testsuite-linux-opt: successful -- manually verified

**Comment by adriaanm** [comment]
jenkins job pr-rangepos: successful -- manually verified

**Pull request merged**
