### PR TITLE
Custom LinkedHashSet subclass for match analysis

### PR DESCRIPTION
**Pull request by lrytz**
Workaround for https://github.com/scala/bug/issues/12760

### CODE REVIEW

**Comment by lrytz** [comment]
@KisaragiEffective is it possible for you to try version `2.13.11-bin-c1a11b1-SNAPSHOT`? In sbt it would be

```
resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
scalaVersion := "2.13.11-bin-c1a11b1-SNAPSHOT"
```

**Comment by lrytz** [comment]
or maybe @michelou?

**Comment by michelou** [comment]
> or maybe @michelou?

@lrytz I guess you are referring to #10258 (blocking Scala dependency in the Flix project). I'll have a try and will report any improvement.

**Comment by lrytz** [comment]
Yes, thanks @michelou.

**Comment by KisaragiEffective** [comment]
> @KisaragiEffective is it possible for you to try version `2.13.11-bin-c1a11b1-SNAPSHOT`? In sbt it would be
> 
> ```
> resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
> scalaVersion := "2.13.11-bin-c1a11b1-SNAPSHOT"
> ```

@lrytz sorry for delayed reply 😓 I've just verified that your approach works in [our organization project](https://github.com/GiganticMinecraft/SeichiAssist) :rocket: ([PR](https://github.com/GiganticMinecraft/SeichiAssist/pull/1925))

**Comment by SethTisue** [comment]
@michelou (we're still also interested in results of testing in the Flix context, of course)

**Comment by michelou** [comment]
@SethTisue @lrytz I confirm that the workaround does solve the performance issue observed when building [Flix](https://github.com/flix/flix) with the Scala option [-Ypatmat-exhaust-depth](https://github.com/michelou/flix/blob/master/build.gradle#L45). See my [comment](https://github.com/flix/flix/pull/4896#issuecomment-1509886116) in https://github.com/flix/flix/pull/4896 for further details.

**Comment by som-snytt** [comment]
@michelou now your follow-up PR can be titled, `pleasure: update Scala 2 version`.

**Comment by KisaragiEffective** [comment]
nitpick: L117 to L119 should be reflect https://github.com/scala/bug/issues/12760.

**Pull request merged**
