### PR TITLE
Fixes https://issues.scala-lang.org/browse/SI-5229

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by paulp** [comment]
You know initialize returns the symbol, right? All those methods in TreeBuildUtil can stay one-liners if you just add ".initialize" as the relevant point.

**Comment by xeno-by** [comment]
Updated the pull request

**Comment by paulp** [comment]
I'm sorry, I thought I could just fix it but you were so fast.

**Comment by paulp** [comment]
So this was merged under its slightly earlier incarnation. (Hopefully that initialize bit was the only change, else I'm losing them.)

**Pull request closed without merging**
