### PR TITLE
BackendPlugin

### PR DESCRIPTION
**Pull request by VladimirNik**
BackendPlugin - mechanism to write custom attributes into the class files emitted by the backend. The method to get required attributes during backend processing is:

``` scala
def pluginsCustomAttributes(sym: ClassSymbol): List[CustomAttr]
```

Pull request contains:
1) BackendPlugin implementation.
2) BackendPlugin support for GenASM and GenBCode.
3) Tests to check BackendPlugin with GenASM and GenBCode.

Original proposal: https://groups.google.com/forum/#!topic/scala-internals/VYAi-9_qf80
Discussion: https://gitter.im/scala/scala?at=55c0a6299fb911ea312a007f

### CODE REVIEW

**Comment by xeno-by** [comment]
@adriaanm @retronym Would be wonderful to have this in 2.11.8, because that'll help both scala.meta and scalac TASTY.

**Comment by lrytz** [comment]
I wonder if we shouldn't do something more generic instead, like `def pluginsModifyClass(sym: ClassSymbol, jclass: ClassWriter): Unit`. Having access to the `ClassWriter` would allow creating custom attributes with references to the constant pool, which can be good for sharing (example: https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/backend/jvm/opt/InlineInfoAttribute.scala#L33).

In the case of GenASM you only get a `ClassWriter`, so there's not too many things that can be done anyway - a plugin can basically only add things. For GenBCode on the other hand the `jclass` is actually a `ClassNode`, which gives access to (and possibility to modify) everything. So then the more general hook might be useful for other kinds of plugins.

Then we could also think about adding a similar hook for methods.

This PR picks a minimal interface, which is certainly not a bad idea, but other backend plugins will likely need something else / more. But trying to predict what other plugins might need in the future doesn't always succeed :) There are arguments for either direction. But in principle, what a plugin needs is the hooks in the right places (in your case: the per-class hook). Once we decided for a specific hook, I think it's a good idea to pass along all the information / data that is around and might be useful / relevant.

**Comment by VladimirNik** [comment]
@lrytz We thought about adding jclass parameter but the final decision was to have the minimal interface. Part of that discussion is here: 
https://gitter.im/scala/scala?at=55c0a6299fb911ea312a007f

**Comment by lrytz** [comment]
Thanks for the reference!

If I look at the current `AnalyzerPlugin`, there's a lot mutable things passed as argument (Symbols, Trees), so plenty of possibilities for a plugin author to create inconsistencies. I'd say we could give the same amount of power to backend plugins. Also, AnalyzerPlugins run during the type checker, they could quite easily break assumptions. BackendPlugins at least run "after the fact", when the entire class (or method) is generated. They could even be written as separate programs that modify classfiles, except that it would be a bit harder to get the corresponding ClassSymbol.

I'd like to hear a few more opinions on this.

**Comment by sjrd** [comment]
Can we call this a `JVMBackendPlugin`?

Also note that this opens a semi-official hook whose API directly depends on ASM. If a minimal API is desired, it might be better to have our own representation of custom attributes, and only expose that in the API.

**Comment by VladimirNik** [comment]
@lrytz One of the problems I see with powerful plugins is that it's hard to find one invocation point for them inside GenASM/GenBCode. For example, the documentation defines the order of actions that should be performed on ClassVisitor's object:

```
The methods of this class must be called in the following order: 
visit [ visitSource ] [ visitOuterClass ] ( visitAnnotation | visitAttribute )*
 ( visitInnerClass | visitField | visitMethod )* visitEnd.
```

And if inside backend plugin there is a method that can operate on entire ClassVisitor it will be problematic to connect its behaviour with default backend code generation behaviour (to guarantee that it works in accordance with the specification).

**Comment by VladimirNik** [comment]
scala.tools.asm dependency is removed.

**Comment by xeno-by** [comment]
Any chance to get this merged into 2.11.8?

**Comment by xeno-by** [comment]
@adriaanm @retronym @lrytz ping

**Comment by adriaanm** [comment]
Sorry about the silence -- been busy! We'll discuss inclusion soon. In any case, there's still time for 2.11.8, which will be delayed (possibly until after 2.12.0-M4).

**Comment by adriaanm** [comment]
Actually, whether there's time for 2.11.8 or not, could you elaborate on why this needs to go in 2.11.x, which will soon be EOL'ed (when 2.12.0 comes out)? I don't think we should do too much new feature development here, as a default position.

**Comment by xeno-by** [comment]
Merging this PR into 2.11.x will allow the scalahost plugin (which is the cornerstone of scala.meta support for scalac) to run on 2.11.x without reflective hijacking of the backend.

**Comment by adriaanm** [comment]
Ok, but, once 2.12.0 is out, 2.11.x will go into strict maintenance mode, so development will have to happen in 2.12.x. Once it's actually time to start experimenting with scala.meta & TASTY, I don't expect there to be a big demand for doing this on 2.11 -- do you? I was under the assumption we were going to do the scala.meta work in 2.12 & 2.13.

**Comment by xeno-by** [comment]
A part of scala.meta is already used in production (on Scala 2.11), and I'm actively developing another part that's also targetting production (it might also be ready well before Scala 2.12 hits).

The good thing about scala.meta, with respect to scalac development, is that so far it's very standalone. This backend hook, as well as a few new attachments (as we discussed with @retronym in gitter back then; I can no longer find our chat after the recent reorganization) - this is all that I need on the scalac side for scala.meta 0.1.

**Comment by adriaanm** [comment]
Ah, I didn't know. Could you elaborate on how it's being used in production? As always, the main cost of adding an API isn't writing the initial code, it's maintaining it and helping others use it correctly.

**Comment by xeno-by** [comment]
@adriaanm Current usages are about linking to scalameta as a library (no compiler plugins) and using its syntactic APIs (parsing, transformations, prettyprinting). 

In 0.1, I plan to implement persistence for typed scala.meta ASTs (that will require a compiler plugin that uses the new BackendPlugin interface), so that the current syntactic-only code analyses will be able to also run semantic queries.

**Comment by adriaanm** [comment]
I'm still not convinced this is a critical addition to 2.11.8, which is now well into maintenance-only territory. I don't want to compromise the stability of the maintenance release to support a future 0.1 feature. We have to focus all of our efforts on getting 2.12 out in time.

It seems completely acceptable to me that your planned 0.1 release requires the latest 2.12 for semantic analysis. Once we have users that actually request this feature, and it has proven to work in 2.12, we can consider backporting to 2.11.x.

I'm going to close this PR. If you'd like to discuss further -- always happy to do a hangout!

**Pull request closed without merging**
