### PR TITLE
Fix for overly eager package object initialization.

### PR DESCRIPTION
**Pull request by paulp**
A subtle change in the order in which symbol attributes were
inspected (now you know why I avoid vals in the compiler) led to a
cycle during initialization for slick. I'm afraid I don't know how
to reproduce the issue outside of slick and sbt, so I added some
logging instead.

After some challenges juggling general correctness and cycle
avoidance, I resorted to improving and documenting the logic
as well. I predict reviewer will be pleased.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm

**Comment by paulp** [comment]
Stupid isEffectivelyFinal also does some forcing. One more try, coming up.

**Comment by paulp** [comment]
Well, at least I'm apparently faster than jenkins.

**Comment by paulp** [comment]
PLS REBUILD ALL

(for lowish values of RE-)

**Comment by paulp** [comment]
Those failures are for the I-knew-it-would-fail version, despite the notifications coming after I implied jenkins had never built that version. "scala, jenkins, and github: when maximum confusion just isn't enough."

**Comment by paulp** [comment]
PLS REBUILD ALL KTHX

**Comment by adriaanm** [comment]
LGTM

RIP (reviewer is pleased)

**Pull request merged**
