### PR TITLE
[backport] Avoid retaining refs to previously added items after VectorBuilder.clear

### PR DESCRIPTION
**Pull request by He-Pin**
https://github.com/akka/akka/issues/25623
https://github.com/scala/scala/commit/845b0f0ffc59392b3dd59979f89d4f101e598236#diff-59f3462485b74027de4fd5e9febcc81bR627

I compared the code in Vector 2.13.x

### CODE REVIEW

**Comment by He-Pin** [comment]
@SethTisue I updated it, @jrudolph cc

@SethTisue is it possible to reschedule this to 2.12.16?

**Comment by lrytz** [comment]
This is basically a backport of https://github.com/scala/scala/pull/6779. I assume it could be a 1-1 backport (i.e., use `preClean`), but I this patch LGTM too.

Note that 2.13.0 Vector is different form current 2.13 Vector since 2.13.2, there was a complete rewrite (https://github.com/scala/scala/pull/8534). The 2.13 patch (https://github.com/scala/scala/pull/6779) was for the 2.13.0 version of Vector.

**Review by lrytz — APPROVED** [review]
👍

**Comment by som-snytt** [comment]
Nice. I love the "countdown" ordering. This was probably the last opportunity to correct the indentation of `VectorPointer`.

Relatedly, you might expect "The Pointer Sisters" to be a bigger meme in computing. Maybe it's not too late to right that wrong.

**Review by NthPortal — APPROVED** [review]
might be nice to have a test for this. there are a few GC tests in `junit` you can potentially look at for examples, such as `LazyListGCTest`

**Comment by som-snytt** [comment]
I'd like to point out that on the original ticket, retronym called it a "clear bug" and added "(ha!)" so future researchers would not miss it.

**Comment by som-snytt** [comment]
I pushed a test, I hope I did it right, I mean the git part. I didn't track down `*GCTest` but there is a helper for testing reachability. I noticed some unused imports and spurious warnings to quash.

**Pull request merged**
