### PR TITLE
Makes all private variables accessed from an @inline method non-private.

### PR DESCRIPTION
**Pull request by odersky**
inlining across classes requires that accessed variables from @inline methods are not private. Review by @adriaanm, @magarciaEPFL

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM

**Comment by magarciaEPFL** [comment]
There's a corner case, when `sym` denotes a protected, library-defined, member. For example:

``` scala
object Test extends scala.xml.PrettyPrinter(1, 2) {
  @inline def m() = { cur = 1 }
}
```

In the example, `makeNotPrivate()` runs for both `constructor PrettyPrinter` and `method cur_=` although in both cases `sym.sourceFile == null` (another possibility being `NoSourceFile`).

It's fine in the sense that none of those two symbols were private, but perhaps that manages to trip the inliner anyway (e.g., by indulging it to see as public sthg that at bytecode level isn't).

**Comment by odersky** [comment]
I don't think Miguel's comment applies, because makeNotPrivate does not affect protected members.

**Comment by jsuereth** [comment]
So should I merge?

**Pull request merged**
