### PR TITLE
Fix 2.13.13 regression in Scaladoc compilation when using Scala 3 definitions

### LINKED ISSUE #12955: Regression in scaladoc compilation when using in Scala 3 definitions
## Reproduction steps

Scala version: 2.13.13
Tested with Scala 3 versions for cross compiled project: 3.3.1 and 3.3.2

[reproduction-sbt.zip](https://github.com/scala/bug/files/14372699/repro.zip)
run with `sbt "base/publishLocal; projectC/publishLocal"`

1. Define ADT in Scala 3, create a jar out of it
```scala
package testlib

enum ADT:
  case SingletonCase
  case ClassCase(x: String)
```

2. Define Scala 2 project that uses Scala 3 JAR 
```scala
package app

object Main {
  def main(args: Array[String]): Unit = {
    println(testlib.ADT.SingletonCase)
    println(testlib.ADT.ClassCase("foo"))
  }
}
```

3. Try to create documentation for Scala 2 project, (`sbt Compile/doc`)

## Problem

Compilation fails with 
```
error] stack trace is suppressed; run last projectC / Compile / doc for the full output
[error] (projectC / Compile / doc) scala.reflect.internal.Types$TypeError: Unsupported Scala 3 generic tuple type scala.Tuple in bounds of type MirroredElemTypes; found in  scala.deriving.Mirror.<refinement>.
[error] Total time: 0 s, completed Feb 22, 2024, 11:42:57 AM
```

### PR DESCRIPTION
**Pull request by bishabosha**
`.tasty` files are no longer considered source files of a symbol.

Specifically the behavior observed in https://github.com/scala/bug/issues/12955 is caused by the top level class `scala.deriving.Mirror` not being filtered out from generating a doc page, because the `sourceFile` property on the Symbol wasn't null (i.e. it returned a ".tasty" file)

fixes https://github.com/scala/bug/issues/12955

### CODE REVIEW

**Comment by bishabosha** [comment]
not sure what's the best regression test for this, a sbt scripted test? or I can try to add a scaladoc invoker to the tasty test stuff

**Comment by SethTisue** [comment]
Hmm, I'm not sure either. Off the top of my head ,though: invoking Scaladoc directly rather than going through sbt seems simpler and more efficient. Maybe try that first and fall back to scripting sbt if you run into too many obstacles on the other path?

**Comment by SethTisue** [comment]
Note that I do think that it's important to do one or the other and not simply leave it untested.

Converting to draft for now until some testing is in place.

**Comment by bishabosha** [comment]
@SethTisue I have added the regression test

**Comment by lrytz** [comment]
```
[error] (tastytest / Compile / headerCheck) There are files without headers!
[error]   /home/travis/build/scala/scala/src/tastytest/scala/tools/tastytest/Scaladoc.scala
[error]   /home/travis/build/scala/scala/src/tastytest/scala/tools/tastytest/Scaladoc.scala
```

**Review by lrytz — DISMISSED** [review]
LGTM otherwise, thank you.

**Comment by bishabosha** [comment]
should be fixed now

**Pull request merged**
