### PR TITLE
SI-6654 & SI-7005 - Map#filterKeys and Map#mapValues not serializable

### PR DESCRIPTION
**Pull request by sullivan-**
Fixes SI-6654
Fixes SI-7005

Review by @axel22
Review by @rkuhn

### CODE REVIEW

**Comment by axel22** [comment]
LGTM

**Comment by rkuhn** [comment]
Since I was asked: the commit itself looks okay, but I disagree with the chosen strategy. FilteredKeys and MapValues are there for optimizing later operations, but the serialized representation should just be the filtered/transformed Map. Sending the closure over the wire might pull in the whole universe, or it might not work at all if done e.g. from within an Actor (which is fundamentally non-serializable and comes in typically via the $outer reference).

**Comment by axel22** [comment]
Hi Roland!

That is a good point.
I think this implicit forcing that we should then do with `FilteredKeys` 
and `MapValues`is the reason why general collection views were made not 
to be serializable in the first place - to make the user explicitly 
force the view before sending it over the wire, making the intention 
clear in the code.
One downside I can see with forcing the views implicitly is that after 
deserialization you would not have the same correspondence between the 
view and the collection it was obtained from.

Perhaps we should add a `force` method to `FilteredKeys` and `MapValues` 
so that clients interested in serializing must force explicitly, and 
then make these two non-serializable.

Cheers,
Alex

## 

Aleksandar Prokopec
Doctoral Assistant
LAMP, IC, EPFL
http://people.epfl.ch/aleksandar.prokopec

**Comment by sullivan-** [comment]
Thanks Roland. The whole bit about pulling the closure into the serialization hadn't occurred to me. Clearly a fix for SI-4776 would be best.

Just making these methods return things that are serializable might not be the best thing if in the future (after SI-4776) they return proper views that need a call to force to be serialized.

**Comment by JamesIry** [comment]
So should we close this PR?

**Comment by sullivan-** [comment]
OK by me

**Comment by rkuhn** [comment]
@axel22 While I agree with the argument for non-serializability of views I would not say that `mapValues` is a clear enough indication that this is indeed a view. And given that the result of `mapValues` equals the equivalent transformation done using `map` I also do not see a difficulty in implicitly forcing this “view”.

**Comment by axel22** [comment]
I do not feel very strongly about either option, but have a tendency to require the clients to explicitly state their intent in cases where the semantics might be unclear.

I guess this could be a candidate for a mailing list discussion.

**Pull request closed without merging**
