### PR TITLE
SI-6632 SI-6633 Fixes issues and data corruption in ListBuffer

### PR DESCRIPTION
**Pull request by soc**
- Disallow negative positions for ListBuffer#insert/insertAll/update
  - Fix data corruption issue in ListBuffer#insert

### CODE REVIEW

**Comment by soc** [comment]
Merged tests as suggested in #1597.

I didn't fix `updated` which suffers from the same issue. Is there a recommended place to fix it? The implementation in `SeqLike` doesn't really look like the right place. Better override `updated` in `ListBuffer`?

**Comment by paulp** [comment]
This lgtm.  I'm on my phone so I can't give an opinion on updated.

**Comment by jsuereth** [comment]
This LGTM

**Comment by soc** [comment]
The method `updated` needs the same fix. Can someone more familiar with the collection hierarchy comment on where the fix for `updated` should be added? I'm a bit reluctant to put it into `ListBuffer` because then it would be the only `CanBuildFrom`-style method overriden there, but on the other hand, adding a check to `SeqLike` also looks wrong, because then it would be the only method there with a bounds check (and a lot of other implementations would also be affected by it, too).

Opinions?

**Comment by jsuereth** [comment]
I need to dig in to figure out where to fix.   SeqLike is most likely wrong, thanks to views.   My opinion on collections is to be ultra conservative and expand as you gain confidence.

**Comment by jsuereth** [comment]
Merging this as is for now, let's discuss updated elsewhere.

**Pull request merged**
