### PR TITLE
highlights internal parts of scala.reflect.runtime

### PR DESCRIPTION
**Pull request by xeno-by**
By moving them to scala.reflect.runtime.internal.

Noone should be using those classes anyway, because everything except
JavaUniverse is private[XXX] and JavaUniverse itself has the "do not
instantiate" doc comment on it.

On the other hand, our runtime reflection APIs are exposed via
api.JavaUniverse, not via runtime.JavaUniverse, so nothing publicly
accessible refers to the runtime cake.

Finally, reifier is also not using runtime cake directly, preferring
api.JavaUniverse. It didn't have to, but I feel very relieved that I did
not tap into internal implementation details back then. Here's the code:
https://github.com/scala/scala/blob/v2.10.0/src/compiler/scala/reflect/reify/package.scala#L37

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym @paulp @adriaanm

**Comment by retronym** [comment]
I like this change. But we'd stil have to change the MIMA whitelist to exclude `reflect.runtime` to silence it's backward compat warnings. So it is worth to target 2.10.1 with this?

(I do think we should add reflect.runtime to the MiMa exclusions in 2.10.1)

**Comment by xeno-by** [comment]
As @adriaanm wrote, we'll need to discuss this change once he wakes up. I just decided to prepare the stage for the discussion. If the PR doesn't make it into 2.10.1, I wouldn't mind - it's easy to retarget :)

**Comment by xeno-by** [comment]
Thank you, kitty! PLS REBUILD ALL

**Comment by adriaanm** [comment]
See my comment at https://github.com/scala/scala/pull/2103#issuecomment-13358480.

Let's do this in master.

**Pull request closed without merging**
