### PR TITLE
Remove GenASM/ICode

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
This is not intended to be merged yet, as mentioned by retronym. Trying to compile here, because I get weird errors in `scala.runtime.java8` on my local machine ...

**Comment by retronym** [comment]
Note that there is a defacto API used by SBT that we need to preserve: https://github.com/scala/scala/commit/b17a291c2edf28aca1713aa4a30d8bba3886bc8d

**Comment by retronym** [comment]
In answer to your question on Gitter, tests of the old optimizer using `GenASM` should be ported.

This task is tracked as https://issues.scala-lang.org/browse/SI-9364

**Comment by soc** [comment]
@retronym I kept the skeleton of the code for SBT, I'll need to have a look at the SBT code to figure out if that's enough.

There are also some other minor things I want to look into, like having multiple implementations of BOOL, CHAR etc.

**Comment by soc** [comment]
Yes, I'll take care of the tests!

**Comment by lrytz** [comment]
I think it will be quite a bit of work to port the rest of the test suite to GenBCode. I'll close this for now to keep the PR queue a bit shorter.

**Pull request closed without merging**
