### PR TITLE
Quasiquotes

### PR DESCRIPTION
**Pull request by xeno-by**
Supersedes https://github.com/scala/scala/pull/2691

### CODE REVIEW

**Comment by xeno-by** [comment]
Copy/paste removed, quasiquote engine refactored to be much more clear, other comments from the previous pull request addressed. LGTM

**Comment by adriaanm** [comment]
Ok, I'll review this afternoon. M4 is scheduled for tomorrow, so in principle this can go in.

**Comment by adriaanm** [comment]
Excellent, thanks for splitting it up nicely!

I think this can go in M4 (I plan to tag my Wednesday morning). I listed some suggestions below that would be nice, time permitting -- I'd definitely like to see them addressed at some point, if not by M4.

My (ordered) wishlist:
- [x] if possible, leave a forwarder to `treeBuilder` in the parser for potential plugin users (or other compiler clients).
- [ ] add a little scaladoc to the  undocumented classes/traits that are introduced in `reflect.api`
- [ ] a comment in the parser on why the def case now comes before the expr case when parsing a template
- [ ] BNF-style syntax description of the modified fragment of Scala implemented by `QuasiquoteParser`

**Comment by xeno-by** [comment]
@adriaanm As I was testing out quasiquotes, making sure that things work well for M4, I discovered that relaxed macro impls (ones that allow their arguments and return types to be trees) don't work with subtypes of c.Tree, just with c.Tree itself. Since quasiquotes don't upcast their expansion to c.Tree, this causes problems. 

I thought this might be a very common stumbling point, so I took liberty to fix the bug and append the patch to this pull request, given that it's really small. Please let me know if you want me to resubmit the fix separarely.

**Comment by adriaanm** [comment]
Should be fine. I'll have a look in the next couple of hours

**Comment by xeno-by** [comment]
The failures were caused by the fix to SI-7507 not been applied to locker. When fixing the macro engine, I also did some code cleanup and removed a workaround for SI-7507. The patch compiled fine on my machine when I was working with quick, however it caused errors when jenkins tried to build locker. I removed the cleanup commit and pushed -f.

**Comment by adriaanm** [comment]
LGTM, great work, guys! :cake: for everyone.

I will be back to insist on those missing docs, though.

**Comment by adriaanm** [comment]
The check-init build discovered some likely initialization bugs: https://scala-webapps.epfl.ch/jenkins/view/All/job/scala-nightly-checkinit/1761/console:

```
 Uninitialized field: Reifiers.scala: 19
    at scala.tools.reflect.quasiquotes.Reifiers$Reifier.reifee(Reifiers.scala:19)
    at scala.tools.reflect.quasiquotes.Reifiers$Reifier.reifee(Reifiers.scala:16)
    at scala.reflect.reify.States$State.<init>(States.scala:43)
    at scala.reflect.reify.States$class.$init$(States.scala:22)
    at scala.reflect.reify.Reifier.<init>(Reifier.scala:15)
    at scala.tools.reflect.quasiquotes.Reifiers$Reifier.<init>(Reifiers.scala:18)
    at scala.tools.reflect.quasiquotes.Reifiers$ApplyReifier.<init>(Reifiers.scala:166)
    at scala.tools.reflect.quasiquotes.Quasiquotes$$anonfun$2.apply(Quasiquotes.scala:24)
    at scala.tools.reflect.quasiquotes.Quasiquotes$$anonfun$2.apply(Quasiquotes.scala:24)
    at scala.tools.reflect.quasiquotes.Quasiquotes.expandQuasiquote(Quasiquotes.scala:47)
```

**Pull request merged**
