### PR TITLE
Reduce build noise

### PR DESCRIPTION
**Pull request by som-snytt**
Following up by omitting "non-local return" warning, which is a recent addition to the stable of stable lint warnings.

Other minor clean-ups.

Pretty sure I did the partest already, but no idea where the commit went.

### CODE REVIEW

**Comment by som-snytt** [comment]
For some reason, there was an `import java.lang.String` in `mutable.HashMap`, not technically unused. OK, Martin added a `String` result type "needed for dotty" and also the import. Does dotty need the import? I tried to make time for dotty last year but barely succeeding in making time for myself. Maybe I'll just revert that change.

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
We can always put the import back if important.

**Comment by SethTisue** [comment]
@som-snytt I'm often seeing this in the build:

```
[error] '-nonlocal-return' is not a valid choice for '-Xlint'
```

is this a mistake/oversight, or will it go away when we re-STARR post-M5?

**Comment by som-snytt** [comment]
@SethTisue https://github.com/scala/scala/pull/7069 to wait for re-starr.

**Comment by SethTisue** [comment]
oh right.

**Comment by som-snytt** [comment]
Sorry to be that guy. I'll be on vacation soon with some time to hack a bit as necessary in support of your sane release train.

**Comment by SethTisue** [comment]
that guy who found himself in an unexpected-need-to-re-STARR situation? we're all that guy.

“_I'm_ STARRtacus!”

**Pull request merged**
