### PR TITLE
Bump version to 2.11.5 in build.number file.

### PR DESCRIPTION
**Pull request by gkossakowski**
Scala 2.11.4 release has been staged, we should start publishing snapshots
for Scala 2.11.5 now.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @lrytz or @xeno-by

**Comment by xeno-by** [comment]
Great news! Though I'm a bit out of the loop with scala/scala infrastructure, so I'll withhold the lgtm until Lukas gets here, allright?

**Comment by gkossakowski** [comment]
Sure.

**Comment by lrytz** [comment]
LGTM!

**Pull request merged**
