### PR TITLE
add support for MSys2 to bin/scala shell script

### PR DESCRIPTION
**Pull request by kirillkh**
See http://stackoverflow.com/questions/31734361/scala-under-msys2-failure-to-initialize-terminal/ for motivation.

### CODE REVIEW

**Comment by SethTisue** [comment]
review by, I don't know, @som-snytt (who committed a Cygwin-related fix to the same file in November 2012 and is now punished for it)? @retronym?

**Comment by retronym** [comment]
LGTM, although I don't have a system handy to test this.

**Comment by retronym** [comment]
@kirillkh Could you please post a transcript of the failing before and working after the patch?

**Comment by kirillkh** [comment]
@retronym Before

```
$ scala
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
    at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
    at jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
    at jline.WindowsTerminal.init(WindowsTerminal.java:82)
    at jline.TerminalFactory.create(TerminalFactory.java:101)
    at jline.TerminalFactory.get(TerminalFactory.java:158)
    at jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
    at jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
    at jline.console.ConsoleReader.<init>(ConsoleReader.java:209)
    at scala.tools.nsc.interpreter.jline.JLineConsoleReader.<init>(JLineReader.scala:61)
    at scala.tools.nsc.interpreter.jline.InteractiveReader.<init>(JLineReader.scala:33)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiate$1$1.apply(ILoop.scala:865)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiate$1$1.apply(ILoop.scala:862)
    at scala.tools.nsc.interpreter.ILoop.scala$tools$nsc$interpreter$ILoop$$mkReader$1(ILoop.scala:871)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$15$$anonfun$apply$8.apply(ILoop.scala:875)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$15$$anonfun$apply$8.apply(ILoop.scala:875)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$15.apply(ILoop.scala:875)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$15.apply(ILoop.scala:875)
    at scala.collection.immutable.Stream.map(Stream.scala:418)
    at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:875)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$apply$mcZ$sp$2.apply(ILoop.scala:916)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:916)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:911)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:911)
    at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:911)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
    at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.

scala>
```

After:

```
$ scala
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.

scala>
```

**Comment by kirillkh** [comment]
I must add that the patch had been tested only with cmd.exe-based environments (confirmed working with cmd.exe, ConEmu and Console2). I have just tried it with mintty (that ships with Msys2), and on my system `scala` freezes after I issue any command:

```
$ scala
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :help
```

I see identical behavior with scala.bat:

```
$ cmd //c scala.bat
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :help
```

If I run the unpatched `scala` shell script, I see the NoClassDefError as described above, but it doesn't freeze (the basic terminal functionality works), so I suppose you can say that the patch leads to regression with mintty.

**Comment by kirillkh** [comment]
Running `scala -Djline.internal.Log.trace=true` shows the source of the problem. The following is printed non-stop on stderr:

```
[DEBUG] read Windows console input error:
java.io.IOException: ReadConsoleInputW failed
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:765)
        at org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794)
        at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
        at jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:215)
        at jline.WindowsTerminal.access$000(WindowsTerminal.java:55)
        at jline.WindowsTerminal$1.read(WindowsTerminal.java:157)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:261)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:198)
        at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2349)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
        at scala.tools.nsc.interpreter.jline.InteractiveReader.readOneLine(JLineReader.scala:56)
        at scala.tools.nsc.interpreter.InteractiveReader$class.readLine(InteractiveReader.scala:38)
        at scala.tools.nsc.interpreter.jline.InteractiveReader.readLine(JLineReader.scala:27)
        at scala.tools.nsc.interpreter.ILoop.readOneLine(ILoop.scala:413)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:422)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:925)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:911)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:911)
```

There is nothing on Google about this error. The offending source code line is:
`https://github.com/fusesource/jansi-native/blob/master/src/main/java/org/fusesource/jansi/internal/Kernel32.java`, line 765

Unfortunately, the method doesn't call GetLastError() after receiving 0, so we can only guess what the actual error was.

**Comment by kirillkh** [comment]
All right, my problems were caused by the following line in my .bash_profile: `TERM=cygwin` and by the fact that the shell script does not stty for that value of TERM. Since other people may have "cygwin" as their TERM (in my case it was a useful workaround for Console2 deficiency), I added that to the patch as well.

Please re-review.

**Comment by SethTisue** [comment]
(just asked on Gitter scala/scala for reviewers)

**Comment by SethTisue** [comment]
LGTM. thank you @kirillkh for the contribution!

**Pull request merged**
