### PR TITLE
Added inverse method

### PR DESCRIPTION
**Pull request by kclick91**
The inverse method returns 1 / x in a double value unless used with BigDecimal.

### CODE REVIEW

**Review by kclick91 — COMMENTED** [review]
BigDecimal inv method is taken out.

**Comment by NthPortal** [comment]
The `inv` method needs to be defined for `BigDecimal`'s `Numeric` as well.

**Comment by kclick91** [comment]
Ok. Defined for BigInteger or BigDecimal? I added to the BigDecimal Numeric but I am considering making a Generic return type and return double unless it is a float or BigDecimal where float and BigDecimal are returned, respectively.

**Comment by NthPortal** [comment]
oops, typo. I meant `BigDecimal`

**Comment by martijnhoekstra** [comment]
Requires at least documentation and tests, but also justification and consensus that this should be in the stdlib (channelling my inner @sjrd )

**Comment by NthPortal** [comment]
I think if it does belong in the stdlib, it should have a reduced scope and be defined only for `Fractional`. This allows the return type to be the same as the argument, so no precision is lost for e.g. `BigDecimal`

**Comment by kclick91** [comment]
Well my justification is that it is a common and unique operation that should not have to even be in a separate math package. This would allow values to be easily inverted in equations.

**Comment by SethTisue** [comment]
@kclick91 to echo @NthPortal, why would this go on `Numeric` instead of on `Fractional`?

**Comment by kclick91** [comment]
I think I agree. Fractional would be better.

**Comment by NthPortal** [comment]
From a slightly different perspective, I think having the operation does make a lot of sense - we already have the additive inverse (`negate`), so we should probably also have the multiplicative inverse.

bikeshed: it might be worth calling it `recip` (or some other shortening of "reciprocal"), to be more precise; "inverse" is a more general property that exists, for example, on all groups. idk

**Comment by kclick91** [comment]
recip makes sense. I think that maintaining the accuracy of BigDecimal is important.

**Comment by SethTisue** [comment]
provisionally closing for inactivity. can be reopened if @kclick91 reappears or if someone else wants to pursue it

**Pull request closed without merging**
