### PR TITLE
SI-8910 BitSet sometimes uses exponential memory.

### PR DESCRIPTION
**Pull request by Lymia**
Because of an off-by-one error in scala.collection.mutable.BitSet, where a function (ensureCapacity) is passed a list length instead of an index, when ^=, &=, |=, or &~= are passed BitSets with the same internal capacity as the set the method is being invoked on, the size of the first BitSet is needlessly doubled.

This patch simply changes the ensureCapacity calls to pass the last index of the list, instead of the raw length.

### CODE REVIEW

**Comment by retronym** [comment]
Thanks for your contribution, @Lymia. Review, please, by @Ichoran.

**Comment by Ichoran** [comment]
LGTM assuming tests pass.

**Comment by som-snytt** [comment]
You could add a unit test under `test/junit` instead.  I might test `bs ^= BitSet.empty` as a boundary.  It only checks `idx < max` but anyway.

**Comment by Lymia** [comment]
Is the test failure a problem? I don't see how my changes could trigger this.

**Comment by som-snytt** [comment]
The IDE builds seem to be finicky.  You can comment PLS REBUILD as instructed by the kitteh, or if you decide to add test/junit/scala/collection/mutable/BitSetTest.scala instead and push -f, it will automatically rebuild.

**Comment by Lymia** [comment]
PLS REBUILD/pr-scala@ce4fdd1

**Comment by Ichoran** [comment]
@som-snytt - I guess testing `BitSet.empty` is good for future-proofing, but it really is orthogonal to this patch.  For now, there's a handy "blahblahmath max 1" in the creation of the words array that ensures that `nwords == 1` for `BitSet.empty`.

**Comment by Lymia** [comment]
Uh, I tried to write a test to make sure passing -1 to ensureCapacity doesn't break anything with `new BitSet(new Array[Long](0))`, but it seems I found an unrelated bug in the process.

```
scala> val bitSet = new collection.mutable.BitSet() + 100 + 200 + 300 + 400 + 500
bitSet: scala.collection.mutable.BitSet = BitSet(100, 200, 300, 400, 500)

scala> bitSet &= collection.mutable.BitSet.empty
res1: bitSet.type = BitSet(100, 200, 300, 400, 500)
```

What should I do in this case, as far as this PR is concerned?

**Comment by Ichoran** [comment]
@Lymia - Write a new bug, submit a new patch.  This one is good as it is; the fix to the other shouldn't block this one from going through.  Thanks for finding more bugs, by the way!

**Comment by Lymia** [comment]
I took a look at the JUnit tests, and it looks pretty simple so I figured it couldn't hurt to move my tests to a BitFieldTests file as suggested. Should I wait for this to be pulled so I can do that in the PR to fix the other bug, amend this one or something else?

**Comment by som-snytt** [comment]
I think it's nicer to have the unit test as a junit test.  It means fewer files in the big dir; and the junit tests are compiled together.  If you git mv it now and push -f, it might make for nicer git history.

But I'm just trying to be helpful, not slow you down.  It's great that you noticed that other bug.

**Comment by Ichoran** [comment]
I would not add the JUnit test for the _other_ bug in _this_ PR.  The whole point separate PRs is to keep fixes cleanly independent.  So rather than @Ignore, just don't include that method; then test it in the PR for 8917.  (You can wait for us to merge this one, I hope--there's enough attention here that I think the delay should be measured in hours.)

**Comment by Lymia** [comment]
Good point there. Thanks for helping out. :)
I'm sorta new to contributing to major projects.

**Comment by Ichoran** [comment]
LGTM.  @retronym shall I merge?

**Comment by retronym** [comment]
The PR queue for 2.11.x is on-hold until we cut 2.11.4. We're only addressing the blocker regressions discovered in 2.11.3.

Once that's done, we'll merge this. Please allow about a week.

/cc @scala/team-core-scala

**Pull request merged**
