### PR TITLE
Fix to push-jars to use same sha fixing that pull uses.

### PR DESCRIPTION
**Pull request by jsuereth**
This fixes the binary-repo-tools.sh so that both push and pull use the same mechanism of obtaining SHA.   This should fix the push script for windows.

Review by @lrytz @xeno-by

### CODE REVIEW

**Comment by lrytz** [comment]
i cannot really provide a competent review here.. as far as i can tell it looks good.

**Comment by jsuereth** [comment]
this one might local checkout/verify comments....

BUT HEY THE BUILD WORKED is going to be my excuse if no one can publish STARR after this.

**Comment by dgruntz** [comment]
push-binary-libs worked for me with the new script out of the box under
$ uname
CYGWIN_NT-6.1-WOW64

**Comment by jsuereth** [comment]
Awesome! that's two windows machines verified :)  I'm merging.

**Pull request merged**
