### PR TITLE
Upgrade Dotty to 0.22.0-RC1

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by lrytz** [comment]
```
[info] Unpacking dotty-library sources to /home/travis/build/scala/scala/target/library/src_managed/main/dotty-library-src...
[info] Compiling 611 Scala sources and 148 Java sources to /home/travis/build/scala/scala/build/quick/classes/library ...
[warn] -- Warning: /home/travis/build/scala/scala/src/library/scala/package.scala:19:15 
[warn] 19 |package object scala {
[warn]    |               ^
[warn]    |               object package is in the wrong directory.
[warn]    |               It was declared to be in package <empty>.scala
[warn]    |               But it is found in directory     scala
[error] -- Error: /home/travis/build/scala/scala/target/library/src_managed/main/dotty-library-src/scala/compiletime/package.scala:5:9 
[error] 5 |  erased def erasedValue[T]: T = ???
[error]   |         ^^^
[error]   |         end of statement expected but 'def' found
[error] -- [E040] Syntax Error: /home/travis/build/scala/scala/target/library/src_managed/main/dotty-library-src/scala/compiletime/package.scala:5:13 
[error] 5 |  erased def erasedValue[T]: T = ???
[error]   |             ^^^^^^^^^^^
[error]   |             ';' expected, but identifier found
[warn] -- Warning: /home/travis/build/scala/scala/src/library/scala/reflect/package.scala:72:11 
[warn] 72 |case class ScalaReflectionException(msg: String) extends Exception(msg)
[warn]    |           ^
[warn]    |           class ScalaReflectionException is in the wrong directory.
[warn]    |           It was declared to be in package scala
[warn]    |           But it is found in directory     scala/reflect
[error] -- [E006] Unbound Identifier Error: /home/travis/build/scala/scala/target/library/src_managed/main/dotty-library-src/scala/compiletime/package.scala:5:2 
[error] 5 |  erased def erasedValue[T]: T = ???
[error]   |  ^^^^^^
[error]   |  Not found: erased
[warn] two warnings found
[error] three errors found
[error] (library / Compile / compileIncremental) Compilation failed
```

**Comment by smarter** [comment]
dotty-library needs `-Yerased-terms` to compile. (the first warning is https://github.com/lampepfl/dotty/issues/7932, the second warning is a real issue in the standard library which has a class definition in the wrong directory)

**Comment by SethTisue** [comment]
```
[error] -- Error: /home/travis/build/scala/scala/src/library/scala/collection/concurrent/TrieMap.scala:620:26 
[error] 620 |  private[concurrent] def string(lev: Int): String = "CNode %x\n%s".format(bitmap, array.map(_.string(lev + 1)).mkString("\n"))
[error]     |                          ^
[error]     |error overriding method string in class BasicNode of type (lev: Int): String;
[error]     |  method string of type (lev: Int): String has weaker access privileges; it should be public
```

**Comment by smarter** [comment]
> [error]     |  method string of type (lev: Int): String has weaker access privileges; it should be public

I think Dotty is right here, any objection to making this method public ?

**Comment by lrytz** [comment]
> I think Dotty is right here, any objection to making this method public ?

No, you and dotty are right :-) https://github.com/scala/bug/issues/11881.

I tried to `push -f` to this PR but wasn't allowed.

**Comment by anatoliykmetyuk** [comment]
It doesn't seem like I can add you to the Dotty Collaborators team on dotty-staging. @smarter can you do it?

**Comment by lrytz** [comment]
Usually that's not necessary, and maintainers can push to other people's PRs (https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by anatoliykmetyuk** [comment]
Strange, I don't see the "Allow edits from maintainers" tickbox.

**Comment by lrytz** [comment]
I guess because `dotty-staging` is a GitHub organization...

**Comment by anatoliykmetyuk** [comment]
I mean I don't see the tickbox on the page of this PR, as on the screenshot in the docs you linked.

**Comment by lrytz** [comment]
Yeah, so that might be because the scala from which you submitted this PR belongs to a GitHub organization (https://github.com/dotty-staging), not to an ordinary GitHub user (https://github.com/anatoliykmetyuk). I'm just guessing.

**Comment by dwijnand** [comment]
https://github.com/isaacs/github/issues/1681 😄

**Comment by smarter** [comment]
I've given both of you admin rights on staging.

**Comment by dwijnand** [comment]
> I've given both of you admin rights on staging.

Could I have that (or be invited to the "Dotty Collaborators" team), please?  I'm trying to push to #8937, but can't for the same reason.

**Comment by smarter** [comment]
@dwijnand Done!

**Comment by dwijnand** [comment]
@smarter sorry, I need access to https://github.com/dotty-staging/scala.

**Pull request merged**
