### PR TITLE
Pull up `updated` operation from collection.immutable.Seq to collection.Seq

### PR DESCRIPTION
**Pull request by julienrf**
Fix scala/collection-strawman#549

### CODE REVIEW

**Review by lrytz — COMMENTED** [review]
I'm a bit on the fence on this one, because the deprecation doesn't suggest a straightforward alternative. The `view` examples in the test are not so exotic to demand for them to be rewritten.

I'm not sure what's the best solution. Add the method to SeqView? That seems a bit weird.

**Comment by julienrf** [comment]
Another solution would be to have an `immutable.SeqView` which would inherit from the non-deprecated version of `updated`. I’m not sure we want to multiply the branches of the view hierarchy, though…

**Comment by szeiger** [comment]
Since we already have `patch` and other methods on `collection.Seq` I'm changing my opinion on this one to not deprecate it for now.

The overall naming scheme is inconsistent (and not easily fixable) though. Immutable `map` vs in-place `mapInPlace`, immutable `patch` with no mutable counterpart, immutable `updated` with in-place `update`. At least `patch` could be renamed to `patched`. IMHO this would be clearer.

**Comment by lrytz** [comment]
@julienrf do you agree to bring it back non-deprecated?

@szeiger true that the naming is inconsistent. `update` is special because of the language support. I guess we could find other examples than `patch` where we could argue for a rename, but I fear that might be too big of a change, and also annoying for using immutable collections (the default).

So we have `update / updated`, `append / appended`, `prepend / prepended`. In a quick search I didn't find other `XYZed` methods. So maybe we can call these three the exceptions. All other methods are immutable/copying by default, with possibly an `inPlace` version. Maybe we could even make `update` the only exception and move to `append / appendInPlace`, `prepend / prependInPlace`? That would take a few deprecation cycles though...

**Comment by julienrf** [comment]
@lrytz I’ve force-pushed a commit that makes `updated` non deprecated.

**Comment by lrytz** [comment]
@julienrf all the test failures should go away if you rebase on current 2.13.x

**Review by lrytz — APPROVED** [review]

**Pull request merged**
