### PR TITLE
SIP-14 backport to 2.9.x

### PR DESCRIPTION
**Pull request by phaller**
Other than adding the new APIs, a few changes are required:
1. Build. The Java sources in "scala/concurrent/impl" need forkjoin.jar on the classpath. Thus, I replaced the "classpath" attribute in the respective `javac` ant tasks (locker.lib and quick.lib) with a "classpathref" attribute pointing to a classpath which includes also the forkjoin.jar. In the locker.lib target, exclude the duration package and everything that depends on it.
2. Dependent method types and SI-5958. The `duration` package relies on dependent method types, and requires a backport of SI-5958. This backport is available in PR #1726.
3. To avoid a backend bug involving `throw` expressions inside closures (exercised by the Try tests), a backport of the fix for SI-6188 is required. It is available in PR #1750.

Review by @jsuereth (build) @adriaanm (dependency on #1726)

### CODE REVIEW

**Comment by phaller** [comment]
PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by phaller** [comment]
PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by phaller** [comment]
PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by adriaanm** [comment]
I'm creating a PR that has this backport and the required bugfixes and closing the old PRs.

**Comment by adriaanm** [comment]
@phaller the stability failures were because build.xml was building quick with -Ydependent-method-types for all components (compiler, library, actors...), whereas strap only used it for library. Rectified in the follow up PR by only passing -Ydependent-method-types when compiling the library in quick & strap.

**Comment by phaller** [comment]
Ah, yes, good catch!

**Comment by phaller** [comment]
Thanks for creating an updated PR, Adriaan!

**Pull request closed without merging**
