### PR TITLE
[backport] SI-7237 Always choose ForkJoinTaskSupport

### PR DESCRIPTION
**Pull request by soc**
... on Java 6 and above.

ForkJoinTaskSupport works on Hotspot, Avian and J9,
while ThreadPoolTaskSupport causes the test
test/files/scalacheck/parallel-collections
to reliably hang on all three.

We keep ThreadPoolTaskSupport around to keep the hope
alive that we still have a glimpse of 1.5 support.

### CODE REVIEW

**Comment by soc** [comment]
This is targeted at 2.9, fixes against 2.10 and 2.11 were already merged a while ago.
@axel22, could you review the change?

**Comment by soc** [comment]
PLS REBUILD/pr-rangepos-per-commit@63deb62

**Comment by soc** [comment]
Weird, I'll check this again.

**Comment by soc** [comment]
I receive the following error when building it locally:

`BUILD FAILED
/home/soc/Entwicklung/scala/build.xml:354: The following error occurred while executing this line:
jar:file:/home/soc/Entwicklung/scala/lib/scala-compiler.jar!/scala/tools/ant/sabbus/antlib.xml:9: taskdef A class needed by class scala.tools.ant.sabbus.ScalacFork cannot be found: scala/reflect/io/Path
 using the classloader AntClassLoader[/home/soc/Entwicklung/scala/lib/scala-library.jar:/home/soc/Entwicklung/scala/lib/scala-compiler.jar:/home/soc/Entwicklung/scala/lib/fjbg.jar:/home/soc/Entwicklung/scala/lib/forkjoin.jar:/home/soc/Entwicklung/scala/lib/msil.jar:/usr/share/ant/lib/ant.jar]`

Any ideas?

**Comment by Blaisorblade** [comment]
You sure the build works before the change? The error doesn't mention build products.

**Comment by Blaisorblade** [comment]
Also, the build error reported by Jenkins is different and doesn't make any sense either - essentially, `locker` doesn't find the library source to build `quick` if I understand correctly:

```
warning: No classes or objects found in package.scala that go in package scalaprefixes differ: <empty>.scala,scala
```

@lrytz, could you please check if the kitteh still works on 2.9, or forward this to the right person? It doesn't look like this commit can cause the build to break so badly.

Update: See also the same error on 
https://scala-webapps.epfl.ch/jenkins/job/pr-rangepos-per-commit/1720/console, which affects 
https://github.com/scala/scala/pull/2413 (also for 2.9).

Kitteh marking this as "good to merge" doesn't increase my confidence in the kitteh-du-jour.

**Comment by paulp** [comment]
@adriaanm there have been four PRs titled "Always choose ForkJoinTaskSupport" open for 11 days now. That's 44 PR-days of PR queue noise. I can't figure out what the deal is with them, but someone should merge them or close them.

**Comment by paulp** [comment]
Sorry, three of them are titled "Always use ForkJoin in Scala actors". Whatever, text still works.

**Comment by adriaanm** [comment]
ping @axel22

**Comment by adriaanm** [comment]
> Kitteh marking this as "good to merge" doesn't increase my confidence in the kitteh-du-jour.

the build bot doesn't have control over "good to merge" directly, it's github who decides based on the commit status added by the build bot (see https://github.com/typesafehub/ghpullrequest-validator/blob/master/overview.md)

**Comment by adriaanm** [comment]
the rangepos job has never worked on 2.9 -- I haven't had a chance to disable it for this branch 
the checkin job is fine, so this is in fact good to merge as soon as a reviewer signs off

**Comment by adriaanm** [comment]
review by @phaller

**Comment by axel22** [comment]
LGTM

**Comment by phaller** [comment]
LGTM

**Pull request merged**
