### PR TITLE
The new reflection

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by adriaanm** [comment]
Could you elaborate a bit on the fast track infrastructure? 
[Okay, I found the comment: it's to bypass reflection.]

What are PDTs?

**Comment by xeno-by** [comment]
Path-dependent types.

Fast track is used to optimize performance of our own macros. Programmer-defined macros would go through reflection, we hardwire them to their implementations via FastTrack.scala. 

This has also a nice side-effect of allowing macros in scala-library.jar. To define a macro implementation one needs a reference to scala.reflect.makro.Context, which is located in scala-reflect.jar. Fast track mechanism solves this problem by letting us to right simply `def macroInLibrary = macro ???` and hardwiring an implementation in FastTrack.

**Comment by adriaanm** [comment]
Started jenkins job pr-scala-testsuite-linux-opt at https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/240/

**Comment by adriaanm** [comment]
(don't worry about the failure -- I aborted the first build to speed up the second one)

**Comment by adriaanm** [comment]
build SUCCESS --> congrats, Eugene!

let the post-commit reviewing, nightly-testing (and your weekend) begin!

**Pull request merged**
