### PR TITLE
SI-5920 enables default and named args in macros

### PR DESCRIPTION
**Pull request by xeno-by**
Fixes a tiny vararg mistake introduced in https://github.com/scala/scala/pull/3397, covers vararg expansion extensively, and additionally makes sure that new code paths are only taken by the code that didn't previously compile (named/default macro applications).

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym 

Please note that the fix amounted to simply adding `|| isVarArgsList(params)` to one of the branches in `macroArgs`, so this pull request might be low-risk enough.

Additional changes introduced in this pull request in comparison with the one merged yesterday are only about putting safeguards that would additionally protect us from possible craziness.

Feel free to decide on the target of this pull request, but it would be very nice if it was classified as a hotfix for RC1.

**Comment by adriaanm** [comment]
@xeno-by, I absolutely appreciate all your hard work, but please keep in mind that we're already past the scheduled deadline for RC1. We'll take this week to review and merge the long-running PRs that must be part of the 2.11.0 release, but absolutely no more. 

As agreed before, we will not be accepting fixes that can go into 2.11.1. Please close all of your PRs that can be delayed until then (since reflection is still experimental, scala.reflect.internal will remain exempt from binary compatibility restrictions).

**Comment by xeno-by** [comment]
@adriaanm Note that this can be considered a part of the pull request that was submitted 3.5 weeks ago (https://github.com/scala/scala/pull/3397). If we ran dbuild against that one earlier, the tiny fix I'm talking about would be submitted as a follow-up commit, and everyone would be happy. Given the unusual circumstances, how about we make an exception for this PR?

**Comment by adriaanm** [comment]
We've already made a 3000-line exception by letting a big API change into an RC (remember how I wanted to enforce binary compatibility between M8 & RC1?). The RC cycle, which started after M8, is supposed to be about fixing regressions. I know you've worked really hard to compensate for the fall out of your PRs, and I appreciate that, but this cycle was supposed to be about small, conservative improvements with low risk of regression or a high cost of not fixing them. Is not having default arguments in macros in 2.11.0 a regression?

**Comment by xeno-by** [comment]
I have to admit I lost perspective on this one. I was so caught in the moment of joint hacking in the last couple weeks that it was hard to stop. 

It is quite probable that this pull request represents a small and conservative improvement, as after today I'm fairly sure that it only enables previously uncompileable code to compile, leaving existing code paths untouched. However the time is indeed up, and there's still stuff to review, so I agree that this can wait until 2.11.1.

**Comment by adriaanm** [comment]
Thanks for your patience Eugene :-)

**Comment by ramnivas** [comment]
Is this going to be in a 2.11.x release? I have a use case that will benefit from this. http://docs.scala-lang.org/overviews/macros/changelog211.html mentions to expect this in 2.11.1.

**Pull request closed without merging**
