### PR TITLE
SI-8324 Fix regression in override checks for sealed classes

### PR DESCRIPTION
**Pull request by retronym**
adeffda25 changed `Symbol#isEffectivelyFinal` to help the optimizer
by inferring finality within sealed class hierarchies.

However, this change wasn't neccesarily welcome for other clients of
that method. In the enclosed test case, we see that overriding checks
in `RefChecks` regressed.

This commit moves the enhanced version into a new method and
selectively uses it in the optimizer (and the tail call optimizer).

Review by @adriaanm

### CODE REVIEW

**Comment by xeno-by** [comment]
Not sure about spelling, but it seems that `overridden` is supposed to have two d's: https://www.google.com/search?q=overridden&oq=overridden&aqs=chrome..69i57j0l5.1575j0j1&sourceid=chrome&espv=210&es_sm=91&ie=UTF-8#q=overriden.

**Comment by retronym** [comment]
cheers, fixed

**Comment by adriaanm** [comment]
LGTM

**Comment by paulp** [comment]
The test is misnamed pos/t8234.scala.

**Pull request merged**
