### PR TITLE
Refactor FastTrack to use composition instead of inheritance.

### PR DESCRIPTION
**Pull request by gkossakowski**
Instead of mixing in FastTrack into Macros trait just have a member
with an instance of FastTrack. The motivation for this change is to reduce
the overall use of inheritance is Scala compiler and FastTrack seems like
a nice target for first step. It's an implementation detail of Scala
compiler that we are free to modify.

Previously, `fastTrack` method would be inherited from FastTrack trait and
called from clients (sub classes). The `fastTrack` method returned Map.
Now, the `fastTrack` viariable is of type `FastTrack`. In order for clients
to continue to work we had to implement three operations called by
clients: contains, apply, get.

Alternatively, we could keep the `fastTrack` method and import it in
clients. This approach is likely to be more common in the future when
bigger pieces of code get refactored.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @xeno-by

**Comment by xeno-by** [comment]
In principle, I'm not against this change, but I'd like to learn more about what the reduction in inheritance is going to buy us. Could you elaborate please? Thank you!

**Comment by xeno-by** [comment]
Oh allright, now I see the post at scala-internals: https://groups.google.com/forum/#!topic/scala-internals/G8IvUgo_Dxo. LGTM.

**Comment by retronym** [comment]
Here's a list of most-frequently-touched files in the compiler. Maybe that provides some data to direct similar refactorings.

I'm also in favour of doing this on 2.11.x, as you did here, to minimize the divergence to 2.12.x.

```
git log --pretty=format: --name-only head@{4.years.ago}..head -- src/compiler src/reflect | sort | uniq -c | sort -rg | head -20
warning: Log for 'head' only goes back to Tue, 14 Jan 2014 11:55:44 +0100.
 902
  34 src/reflect/scala/reflect/internal/Types.scala
  29 src/reflect/scala/reflect/internal/Symbols.scala
  29 src/compiler/scala/tools/nsc/typechecker/Typers.scala
  25 src/reflect/scala/reflect/internal/StdNames.scala
  23 src/reflect/scala/reflect/internal/Definitions.scala
  23 src/compiler/scala/tools/reflect/quasiquotes/Reifiers.scala
  20 src/reflect/scala/reflect/internal/Printers.scala
  19 src/reflect/scala/reflect/internal/ReificationSupport.scala
  19 src/reflect/scala/reflect/api/Internals.scala
  18 src/reflect/scala/reflect/macros/Universe.scala
  17 src/reflect/scala/reflect/api/Symbols.scala
  16 src/reflect/scala/reflect/internal/Internals.scala
  16 src/reflect/scala/reflect/internal/BuildUtils.scala
  15 src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  14 src/reflect/scala/reflect/api/Types.scala
  13 src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  12 src/reflect/scala/reflect/internal/TreeInfo.scala
  12 src/compiler/scala/tools/reflect/quasiquotes/Parsers.scala
  11 src/reflect/scala/reflect/runtime/JavaMirrors.scala
```

**Comment by gkossakowski** [comment]
The challenge with traits/classes like `Types` or `Symbols` is that they are exposed through reflection API. Therefore, I think it might be difficult to turn them into composition without introducing a ton of boilerplate.

I think I want to focus first on pieces that are easy to refactor. Once I get number of bases classes and number of members of Global under control we can spend some time thinking about the more difficult cases.

**Pull request merged**
