### PR TITLE
new bytecode emitter, GenBCode (9th attempt)

### PR DESCRIPTION
**Pull request by magarciaEPFL**
This PR re-submission supersedes #2529 and takes into account review comments so far.

Testing against the community build will provide more information than isolated tests.
Bytecode tests are by their very nature fragile (e.g., testing first that pattern matching emits a chain of jumps, only to make sure a moment later that chain of jumps has been collapsed by GenBCode). Concrete ideas and examples on how to balance usefulness vs brittleness are welcome.

Reviews about the content proper of the PR are most welcome.

review by @gkossakowski or @JamesIry or @retronym or @paulp

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
Regarding SI-6720.

SI-6720 isn't a compiler bug as such but rather a VM bug, a VM bug that doesn't occur anymore in the latest version of Oracle JDK 7. Thus I'm calling it a VM bug confined to early releases of Oracle JDK 7, which is why the workaround for SI-6720 isn't carried over from the previous PR. We still can decide to bring back that "fix" for SI-6720 into GenBCode, but in that case a "fix" should also be included for GenASM.

**Comment by magarciaEPFL** [comment]
Regarding building with the new backend.

This PR doesn't add Ant tasks for GenBCode, for now the procedure is manual.
Moreover, the nightly build gets really interesting when using the new optimizer.
To run that build, currently one needs to look into upcoming PRs, ie 

  https://github.com/magarciaEPFL/scala/compare/master...GenRefactored56

On that branch the new backend is activated by default, and it only remains to change `build.xml`:

``` diff
-   <antcall target="@{name}"><param name="scalac.args.optimise" value="-optimise"/></antcall>
+   <antcall target="@{name}"><param name="scalac.args.optimise" value="-neo:o3"/></antcall>
```

Followed by

```
ant all.clean && ant && ant replacelocker && ant nightly
```

**Comment by xeno-by** [comment]
We're about to go into double digits!

**Comment by magarciaEPFL** [comment]
Colorful stats on our way to 15% compiler speedup: This PR has been re-submitted on average thrice a week. For the last three weeks.

**Comment by jrudolph** [comment]
If I would start looking into it, do I have to read through all the old PRs to get the complete discussion before?

**Comment by magarciaEPFL** [comment]
No need to look into previous versions of this PR, which takes into account feedback from reviews so far.

The very first submission included comments on where the new bytecode emitter fits in the larger picture of the new backend, the new optimizer, and upcoming PRs, as summarized in http://magarciaepfl.github.io/scala/ . None of that "larger picture" however is needed to review this PR.

Thanks, I hope you enjoy reviewing it!

**Comment by gkossakowski** [comment]
Hey,

I finally managed to catch up with my backlog so I can give this PR some attention. I haven't managed to go through all commits (this is super large PR) but so far I really like the quality of the code. From first impression, it looks like properly structured and commented.

I'd like to comment more on testing approach as I think testing is the weakest aspect of this PR. You wrote:

> Testing against the community build will provide more information than isolated tests.
> Bytecode tests are by their very nature fragile (e.g., testing first that pattern matching emits a chain of jumps, only to make sure a moment later that chain of jumps has been collapsed by GenBCode). Concrete ideas and examples on how to balance usefulness vs brittleness are welcome.

I agree that community build will be of invaluable help when it comes to testing. However, this will be Integration/System/Acceptance level of testing. See [this](http://en.wikipedia.org/wiki/Software_testing#Testing_levels) Wikipedia entry for explanation.

This PR is missing unit tests that test individual components of the backend. For example,  e7ec615 introduces [JumpChainsCollapser](https://github.com/magarciaEPFL/scala/commit/e7ec61597431507a68db70fcaa82bdd49a926e0e#diff-2) and it has a nice comment explaining what this class is supposed to do. What's missing is executable unit test that tests that particular class in isolation. If you test that individual class then you don't have an issue with brittle tests that depend on implementation details of the pattern matcher.

I know that we were not doing a great job when it comes to unit testing (I don't think we have any tests in the compiler of that kind) but I feel like a new backend is a perfect place to start writing those. The code structure seems to be very good so it should be fairly easy to write such tests.

Let me know what you think.

**Comment by magarciaEPFL** [comment]
I'm of the opinion that unit tests can be added later.

Merging this PR and the upcoming ones would move us forward to a solid 15% compiler speedup in a manner that no unit test can. To recap, the nightly has been passing at all optimization levels for months now for the new backend + optimizer, http://magarciaepfl.github.io/scala/

Yep, that's my opinion.

**Comment by gkossakowski** [comment]
Let's not mix compiler performance consideration with testing of its components. Those are two very different concerns.

My opinion is that if the code doesn't come with tests at the time it's being merged it will never get proper testing. There's plenty of historical evidence for that claim.

One of the biggest problems with old optimizer was lack of any testing so we were completely clueless which optimizations work and which doesn't. I think we should learn from that experience.

I would love to hear opinion of @JamesIry, @retronym and @paulp on that matter.

**Comment by paulp** [comment]
I'm with @gkossakowski. I'll help you write the tests though.

**Comment by magarciaEPFL** [comment]
@gkossakowski :  With tests in place for both GenBCode and GenBCodeOpt, following your logic, there would be no reason to prefer GenASM and the ICode-based optimizer over their new, more thoroughly tested and certainly better documented counterparts.

Do you agree?

**Comment by paulp** [comment]
It's a seductive argument I realize, but the only way you raise standards is by holding new things to higher standards.

**Comment by som-snytt** [comment]
> I'll help you write the tests though.

This is a noble sentiment that I hope registers with the community.

> I'm of the opinion that unit tests can be added later.

Even modulo context (performance tests vs tests of correctness), this sounds strange to a mere outsider.

"It is somewhat singular to talk of happiness among people who live in sepulchres, among the corpses and rags of an ancient nation which they know nothing of."

Quoted by Emerson.  I wish he'd written an essay on unit testing.  That would have been fascinating.  The quote is from the essay on "Manners."

From the same passage: "If the house do not please them, they walk out and enter another, as there are several hundreds at their command."  For house read programming language.

"What fact more conspicuous in modern history, than the creation of the unit test?"  Emerson says "the creation of the gentleman," but that's kind of the same thing.

**Comment by gkossakowski** [comment]
I agree with @paulp.

Here we are discussing conditions of including big piece of code into scala codebase under experimental flag. I would like to stay focused on that.

Just to answer your question: AFAIK, we agreed that any big change should go under experimental flag and stay that way for a while (probably one full major release) before we consider making it a default choice.

**Comment by magarciaEPFL** [comment]
Everyone: in case you'd like to shoot up your ranking at https://github.com/scala/scala/contributors consider this: YOUR TESTS ARE WELCOME !!!

**Comment by adriaanm** [comment]
> I'm of the opinion that unit tests can be added later.

No. Tests are mandatory. We agreed to this. Similarly, we agreed on small PRs that gradually build up to the full functionality so we can realistically review them and follow the evolution of your work (albeit retro-actively).

We simply do not have the resources to review huge PRs. Neither will we accept them simply because the attempt counter hits a certain threshold.

I expect the following PR to meet the criteria we all agreed to in our meetings:
- [ ] small (I leave it up to you whether you want to proceed bottom-up by first implementing a new optimization on top of the current back-end or whether you first introduce the straightforward non-optimizing part of your new back-end);
- [ ] comes with tests;
- [x] has documentation (there, I checked that one for you already as I know you have written plenty of that);
- [x] is quality code.

Your work is technically of very high quality, but I must insist we follow the guidelines we agreed to regarding process, which is just as important.

**Comment by jrudolph** [comment]
As I understand this PR this is just "the straightforward non-optimizing part of your new back-end". What doesn't mean that it couldn't get even smaller.

**Comment by magarciaEPFL** [comment]
@jrudolph 

> What doesn't mean that it couldn't get even smaller.

Could you elaborate?

**Comment by jrudolph** [comment]
Oh, I'm not capable to say if it can be made even smaller by taking the bottom-up approach or splitting this one up even further. I just wanted to say that to me it appeared as if the goal to split it down to "the straightforward non-optimizing part of your new back-end" is already done here, isn't it? And that seems to me like a definite progress compared to the previous PRs I glanced over.

**Comment by magarciaEPFL** [comment]
@jrudolph Clarifying a bit, I had read something along the lines of "the bytecode emitter (devoid of all optimizations) can be made smaller." The problem with breaking it up into several commits is that only at the end we get back a functioning bytecode emitter for Scala, ie one that can handle ASTs as delivered by the `cleanup` phase. In the meantime, I'll add tests for individual optimizations, starting with the intra-method ones.

**Comment by adriaanm** [comment]
I was just sketching the overall criteria we agreed to. Sorry about not being more specific. Do we need pipelining for our first attempt? I believe Jason had already suggested that simplification before.

**Comment by magarciaEPFL** [comment]
A bytecode emitter can still be useful without pipelining (just ask GenASM). In that sense, pipelining could be moved to another PR. On the other hand, when the time comes to review a PR with just pipelining, the reviewer would have first to gain context about the bytecode emitter.

The steep part of the learning curve about this PR is https://github.com/magarciaEPFL/scala/commit/adcea060d4a1186bcff76c3c59157ac36494b683 , and only that. Follow-up commits simply reuse that infrastructure already in place. Looking at it the other way, review of those follow up commits becomes almost straightforward with the mechanisms of https://github.com/magarciaEPFL/scala/commit/adcea060d4a1186bcff76c3c59157ac36494b683 fresh in mind.

**Comment by adriaanm** [comment]
Sounds like a great strategy for simplifying your first PR, then. Just cut it at the commit where it first starts working.

As my contribution to the testing process, I've created a dbuild job that builds akka-actors for a known working config, with the only changed variable being the switch to using the GenBCode from this PR: https://scala-webapps.epfl.ch/jenkins/view/dbuild/job/DBuild_2.11.x_devel-new-backend/2/console

**Comment by adriaanm** [comment]
Looks like it failed. I'll try the 10th attempt next.
I built with scalac as in https://github.com/adriaanm/scala/commit/2c86b0ce8a

**Comment by magarciaEPFL** [comment]
I'll look in more detail tomorrow, compilation fails because of the following assertion

```
[error] ExistentialType reached GenBCode: akka.dispatch.RequiresMessageQueue[_]
```

to give some context, that assertion is part of a wider net:

```
    // !!! Iulian says types which make no sense after erasure should not reach here, which includes the ExistentialType, AnnotatedType, RefinedType.
    case _: ExistentialType     => abort(s"ExistentialType reached GenBCode: $t")
    case AnnotatedType(_, w, _) => toTypeKind(w) // TODO test/files/jvm/annotations.scala causes an AnnotatedType to reach here.
    case _: RefinedType         => abort(s"RefinedType reached GenBCode: $t") // defensive: parents map toTypeKind reduceLeft lub
```

It'd be surprising if an existential type were actually reaching the bytecode emitter !!!

**Comment by magarciaEPFL** [comment]
Ah, I got it. GenASM is being more permissive than GenBCode. This is the GenASM counterpart to the last-line-of-defense above:

```
// !!! Iulian says types which make no sense after erasure should not reach here,
// which includes the ExistentialType, AnnotatedType, RefinedType.  I don't know
// if the first two cases exist because they do or as a defensive measure, but
// at the time I added it, RefinedTypes were indeed reaching here.
case ExistentialType(_, t)           => toTypeKind(t)
case AnnotatedType(_, t, _)          => toTypeKind(t)
case RefinedType(parents, _)         => parents map toTypeKind reduceLeft lub
```

**Comment by adriaanm** [comment]
Yeah, unfortunately it's not just your own potential bugs you need to fend with, it's all the crazy stuff that comes in from upstream or that can't be dealt with downstream. When implementing the new pattern matcher, I spent a large amount of my time in other parts of the compiler that got stirred up as a result of my rewrite. 

Luckily this seems like an easy symptom to fix. I don't think we should expect your first PR (for the new back-end) to fix bugs like this at the root, but it would still be interesting if we could resolve it there rather than work around it.

**Comment by paulp** [comment]
The important thing here, and you really have no excuse this time because I remember using the words "dead body" and "over my", anyway the important thing is this:

```
% ack "Iulian says types which make no sense after erasure" src/
src/compiler/scala/tools/nsc/backend/icode/TypeKinds.scala
391:    // !!! Iulian says types which make no sense after erasure should not reach here,

src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
519:        // !!! Iulian says types which make no sense after erasure should not reach here, which includes the ExistentialType, AnnotatedType, RefinedType.
```

It is exceedingly improbable that I wrote that comment bit-for-bit identically twice.

There is no compromise available when it comes to copy/pasting, and there is no acceptable amount to include. You should consider it pull request poison.

**Comment by magarciaEPFL** [comment]
@paulp I'll see what can be done to remove "code duplication", in the following context:
- GenASM and GenBCode won't stay side-by-side forever, ie any "eventual" (I'm not saying intentional) code duplication will also go away once GenASM goes away.

Still, your point remains. I'll see what can be done about the snippet in question. That snippet is part of the conversion from "Scala symbols" to the representation of types at the level of the bytecode-emitter. One of the important lessons from GenASM has been that reusing symbols for that representation forced on us non-concurrency, mutability, etc, for not much benefit. Plenty of advantages accrue from GenBCode's (and BCodeOpt's) relience on BType for that purpose (that's how the new optimizer manages to use task-parallelism, also overlapping with pipelining of class building). I'll see what can be done, but the convesion we're talking about differs in that regard between GenASM and GenBCode: the result is TypeKind vs BType (although the individual lines you mention are identical).

**Pull request closed without merging**
