### PR TITLE
Add serializations tests

### PR DESCRIPTION
**Pull request by ashawley**
Follow-up to https://github.com/scala/bug/issues/11192, but also for future work on https://github.com/scala/bug/issues/9237

Adds:
- More lists
- Function
- Abstract class
- Type classes

### CODE REVIEW

**Comment by SethTisue** [comment]
@ashawley rebase? it's just tests, so it's mergeable anytime

**Comment by ashawley** [comment]
@SethTisue I've rebased and resolved the conflicts.

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
Sorry this has another conflict. Could you rebase and then we should be good to go

**Comment by ashawley** [comment]
@adriaanm I've rebased and resolved the conflicts.

**Pull request merged**
