### PR TITLE
bug#10033 Remove scala.runtime.StringAdd

### PR DESCRIPTION
**Pull request by NthPortal**
Remove the last deprecated item from 2.12 and before (followup to #6319).

Resolves scala/bug#10033

### CODE REVIEW

**Comment by NthPortal** [comment]
review @SethTisue

**Comment by NthPortal** [comment]
I noticed we got an early re-STARR from merging the new collections, so I can actually do this before M4 is released

**Review by SethTisue — CHANGES_REQUESTED** [review]
there is a lingering `StringAdd` reference in `build.sbt`

**Comment by NthPortal** [comment]
@SethTisue I believe I have taken care of that reference

**Review by SethTisue — APPROVED** [review]

**Pull request merged**
