### PR TITLE
Revert "SI-6601 Publicise derived value contstructor after pickler"

### PR DESCRIPTION
**Pull request by retronym**
This reverts commit b07228aebe7aa620af45a681ef60d945ffc65665.

The remedy was far worse than the disease:

```
% cat sandbox/test.scala
class V private (val a: Any) extends AnyVal

% RUNNER=scalac scala-hash b07228aebe sandbox/test.scala
[info] b07228aebe => /Users/jason/usr/scala-v2.10.0-256-gb07228a

% scala-hash b07228aebe
[info] b07228aebe => /Users/jason/usr/scala-v2.10.0-256-gb07228a
Welcome to Scala version 2.10.1-20130116-230935-b07228aebe (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_27).
Type in expressions to have them evaluated.
Type :help for more information.

scala> def foo(v: V) = v.a == v.a
exception when typing v.a().==(v.a())/class scala.reflect.internal.Trees$Apply
constructor V in class V cannot be accessed in object $iw in file <console>
scala.reflect.internal.Types$TypeError: constructor V in class V cannot be accessed in object $iw
```

Review by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
Is there a test we can throw in which will flag the diseased remedy more quickly next time around?

**Comment by retronym** [comment]
@paulp test case added

**Comment by paulp** [comment]
Manual test run started, sigh, at https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/775/console

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
