### PR TITLE
SI-7258 Don't assume order of reflection values in t6223

### PR DESCRIPTION
**Pull request by soc**
test/files/run/t6223's check file expects a specific
ordering of the reflected values. The ordering is not
guaranteed by the runtime/reflection API and can change.

Therefore, sort the values before comparing them.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Simon, you forgot to choose a reviewer, per https://github.com/scala/scala/wiki/Pull-Request-Policy.
You get a LGTM from me, but since I'm no expert I might miss something.

**Comment by soc** [comment]
Thanks @Blaisorblade! Considering that specialization is involved, could @axel22 have a look?

**Comment by axel22** [comment]
This looks good to me from the specialization standpoint - all specialization tag characters are capital letters, so should work.

LGTM

**Comment by JamesIry** [comment]
LGTM (echoing @axel22 in a way that the build bot will pick up)

**Pull request merged**
