### PR TITLE
Scaladoc explicit companion and package links in title bar

### PR DESCRIPTION
**Pull request by dickwall**
Against issue #4161

Added context sensitive links for the companion toggle and package documentation on the right side of the title bar to make it more obvious that further documentation may exist related to this class. See attached screenshots for effect on each documentation type.

screenshot from 2014-11-25 07 25 34
screenshot from 2014-11-25 07 01 29
screenshot from 2014-11-25 07 00 49
screenshot from 2014-11-25 06 59 52

### CODE REVIEW

**Comment by dickwall** [comment]
By the way, although it may not seem like it from the screenshots, the font size is consistent across the different contexts, the object screenshot was just taken from a slightly larger window, making the text look smaller.

**Comment by retronym** [comment]
Thanks for the contribution, @dickwall!

May I ask you to attend to a few items of busywork?

It is a good practice to issue pull requests from a dedicated topic branch in your fork, rather than from 2.11.x. I would expect a single commit in this PR.

Can you also please reformat the commit message to:
- Start with the (newly created) JIRA issue number
- Limit the subject line to 70 chars

Example:

```
SI-9006 Scaladoc: explicit companion and package links

The existing navigation mechanisms have proved hard to discover for newcomers
to Scaladoc.

This commit adds textual links in the navigation bar to the docs of the
companion (if defined) and to those of the enclosing package.
```

**Comment by retronym** [comment]
I'm not a big fan of the text "Go to", this is sort of redundant with the fact there is a link. How about: 

_Related_ [object Foo](....) | [package p](....)

Stepping back a little bit from the problem, I wonder if it would instead be cleaner to show both companions one after the other in the same page? This would be comfortable for anyone used to Javadoc, and would make it easy to CTRL-F for a method when you don't know if it is defined in the class or the object.

**Comment by som-snytt** [comment]
+1 to the issue (which is not just for newbies, I can attest) and +1 to the radical idea of laying companions out on the same page.  Esp since recent javadoc has the "static" tab.

I know there's a user story in "navigate to package members", like the members of scala.concurrent always kill me.  I'm not sure about the workflow: where do I click first.  The package name and the index are both too small or something.

**Comment by dickwall** [comment]
Moving to ticket/9006 branch with corrections made as requested. Closing this PR

**Pull request closed without merging**
