### PR TITLE
SI-6651 Extension methods types may depend on the typed of the wrapped value

### PR DESCRIPTION
**Pull request by retronym**
This allows for the likes of:

```
class A[X](val x: X) extends AnyVal {
  def foo(xy: x.Y) {}
}
```

We have to do this in both directions, when synthesizing
the extension method in `Extender#transform`, and later on
when Erasure tries to find the corresponding extension
methods by backing out the original signatures from
the signatures of the synthesized methods in the companion.

In the first case, we have to be careful to use a stable
reference to the `self` parameter, which can satisfy the
dependent types.

Review by @paulp

### CODE REVIEW

**Comment by retronym** [comment]
This one also LGT- @odersky in a meatspace review.

**Comment by JamesIry** [comment]
@retronym looks like it needs some fixup, cannot be merged.

**Comment by retronym** [comment]
@JamesIry duly rebased.

@scala-jenkins PLS REBUILD ALL

**Comment by JamesIry** [comment]
LGTM and who am I to argue with @odersky.

**Pull request merged**
