### PR TITLE
new reference compiler is 2.13.11

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by som-snytt** [comment]
shoot for the starrs!

**Comment by SethTisue** [comment]
(Although I'm merging this, that doesn't mean the floodgates are open for merging stuff for 2.13.12...)

**Comment by som-snytt** [comment]
(I think that means someone is putting together a little merge party and wants to save merges for a drinking game called "merge and submerge", which is won by the last person still able to hit the merge button...)

**Comment by SethTisue** [comment]
before _too_ much longer, the wild merging rumpus will begin

**Pull request merged**
