### PR TITLE
[backport] SI-6567 Warning for Option(implicitView(foo))

### PR DESCRIPTION
**Pull request by retronym**
commit 284bd754fa5dfc8bc626b0c5ebe85d872dd044cb
Author: Jason Zaugg jzaugg@gmail.com
Date:   Sat Nov 3 16:19:46 2012 +0100

```
SI-6567 Warning for Option(implicitView(foo))

I've seen the reported problem before in the wild. It seems
worthy of a special warning, so long as we advocate Option.apply
as an alternative to `if (x == null) Some(x) else None`.

It is behind -Xlint at the moment, an option that could do with
some promotion.
(cherry picked from commit 0bcb9e9169146e3f589c6c9f65cc4a5523b78120)
```

### CODE REVIEW

**Comment by adriaanm** [comment]
jenkins job pr-scala-testsuite-linux-opt: successful -- manually verified

**Comment by adriaanm** [comment]
jenkins job pr-rangepos: successful -- manually verified

**Comment by paulp** [comment]
Manually verified? Good enough for me!

**Comment by fernandoracca** [comment]
I ran this code in scala 2.10.3 and the issue still exists for BigDecimals, as the bug reported: https://issues.scala-lang.org/browse/SI-6567  

It'll only work ok when using the workaround suggested.

**Comment by retronym** [comment]
We only added a warning. You need to compile with `-Xlint` to see it.

**Pull request merged**
