### PR TITLE
Add support for java8 default methods.

### PR DESCRIPTION
**Pull request by paulp**
And new starr including said support.

### CODE REVIEW

**Comment by retronym** [comment]
This will knock off https://issues.scala-lang.org/browse/SI-7398, can you mention that in the commit comment?

Can you comment on the lack of a test? (I presume it is because partest runs java sources through both scalac and javac and you can't assume JDK8 is around.) Perhaps you could drop down to a `DirectTest`?

**Comment by retronym** [comment]
You seem to have preemptively answered my questions on that ticket...

**Comment by paulp** [comment]
The lack of tests is a consequence of this taking like three hours longer than it should have due to infrastructure issues and my subsequent annoyance. I just figure something good might happen if I open the PR, which is unlikely if I just sit on the PR and burn my neighborhood down instead.

**Comment by paulp** [comment]
Hey, did I say "infrastructure issues" ?

```
Resolving [ccac40ec8de9b3e938b48edd8836ddc9f3531aa9/lib/scala-library-src.jar]
(23) Failed writing body
Error downloading /home/jenkins/.sbt/cache/scala/ccac40ec8de9b3e938b48edd8836ddc9f3531aa9/lib/scala-library-src.jar: response code: 200
http://repo.typesafe.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/ccac40ec8de9b3e938b48edd8836ddc9f3531aa9/lib/scala-library-src.jar
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by paulp** [comment]
Turns out the source parser doesn't work anyway. Will reopen.

**Pull request closed without merging**
