### PR TITLE
an amazing discovery made by Iulian

### PR DESCRIPTION
**Pull request by xeno-by**
Traces were stalling macro expansions by evaluating messages even when
-Ymacro-debug-\* flags were disabled.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp

**Comment by dragos** [comment]
OMG, I'm famous! 

LGTM, then!

**Comment by paulp** [comment]
Hmm, I wish I too could start from scratch anytime something was too complicated for me to understand quickly.

LGTM.

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
LGTM (echoing others in a way that the build bot will see)

**Pull request merged**
