### PR TITLE
Support the old library by allowing for missing Product.elementName

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by adriaanm** [comment]
Good catch!

**Review by adriaanm — APPROVED** [review]

**Comment by retronym** [comment]
It turned up in the `compiler-benchmark` job: https://scala-ci.typesafe.com/view/scala-bench/job/compiler-benchmark/1701/console

**Comment by retronym** [comment]
Merging to get that benchmark job working again.

**Comment by cb372** [comment]
Sorry, I just noticed this. Thanks for the fix!

**Pull request merged**
