### PR TITLE
Don't populate the concreteSpecMethod set in presentation compiler runs.

### PR DESCRIPTION
**Pull request by dragos**
This is safe because the presentation compiler never runs the tree transformer (where this map is needed). This is a source of serious memory leaks in the IDE, but it wasn't visible before because the IDE didn't run the info transformers far enough. Interestingly, this is not a leak in batch runs: each element of the set is removed when the tree is transformed.

For a nice graph of the effect of this change, see: http://i41.tinypic.com/xe0k7o.jpg

### CODE REVIEW

**Comment by paulp** [comment]
Wow, I wish all pull requests came with cool graphs.  What did you make that with?

**Comment by paulp** [comment]
By the way, concreteSpecMethods is not using perRunCaches.  In general I'd much rather do that than pepper the code with !forInteractive.  Will that solve the issue?

**Comment by dragos** [comment]
Good point. I'll generate another graph with perRunCaches and open another pull request (I made this one with Numbers, but I'll go for gnuplot or something I can run during the nightlies).

**Comment by dragos** [comment]
perRunCaches don't work. It looks to me that they are never cleared in the presentation compiler, because the `interactive.Global` does not call `compileSources`. Looks really fishy. I'll look into it.

And the nice graph: http://i43.tinypic.com/2eevo2g.png

**Comment by paulp** [comment]
With such nice graphs, we cannot be defeated!

**Comment by dragos** [comment]
One more, just for you! Seems like a good idea to call `perRunCaches.clearAll()` before each typecheck `Run` in the presentation compiler..

http://i40.tinypic.com/3176w5c.png

**Comment by paulp** [comment]
GO TEAM RED!

**Pull request merged**
