### PR TITLE
SI-9906: override ListBuffer.last/lastOption to run in O(1) time

### PR DESCRIPTION
**Pull request by chrisokasaki**
Also update scaladocs for those two methods.

review by @Ichoran

### CODE REVIEW

**Comment by Ichoran** [comment]
LGTM

**Comment by SethTisue** [comment]
thanks Chris!

**Comment by mosyp** [comment]
[2.11](https://github.com/scala/scala/blob/2.11.x/src/library/scala/collection/mutable/ListBuffer.scala) & [2.13](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/mutable/ListBuffer.scala) versions are missing the fix. Is there anyway to port it?

**Comment by NthPortal** [comment]
I don't think 2.11 is likely to get this (or almost any other) fix at this point. It should definitely be ported to 2.13.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/7386

**Pull request merged**
