### PR TITLE
Add disambiguating overrides for MapOps.mkString methods

### PR DESCRIPTION
**Pull request by szeiger**
Fixes https://github.com/scala/collection-strawman/issues/504

### CODE REVIEW

**Comment by sjrd** [comment]
Yet another case that would be fixed by removing the rule that says that overloads in a subclass are more specific than those in a superclass ...

**Comment by julienrf** [comment]
Can we easily experiment with removing this rule? Or do we need it anyway for other reasons?

**Comment by hrhino** [comment]
Isn't that the rule that makes the implicit "priority" pattern through subclassing work? Or would the implicit search rules work on "static overloading plus this subclass specificity criterion"?

**Comment by szeiger** [comment]
We rely on this prioritization to "override" methods like `[B]map(A => B):IterableCC[B]` with `[B : Ordering]map(A => B):SortedCC[B]`

**Review by lrytz — APPROVED** [review]

**Pull request merged**
