### PR TITLE
Switch to sbt mima plugin

### PR DESCRIPTION
**Pull request by 2m**
As of just released MiMa 0.1.15 it is now possible to load BC issue filters from files for the sbt-mima plugin. It also supports checking for both forward and backward BC issues. This PR adds sbt-mima plugin and migrates filters to project specific versioned filter files.

### CODE REVIEW

**Comment by lrytz** [comment]
Thanks, @2m! Could you push an additional commit that introduces binary incompatibilities in library and reflect, both forward and backward. Maybe also remove some of the excludes. Just to make sure everything works on CI. We can then remove that commit again.

**Comment by 2m** [comment]
Added one commit for reflect and one for library respectively. Each commit introduces one bc issue and removes one filter for both backwards and forwards compatibility. Therefore each commit should result in four bc issues reported.

**Comment by SethTisue** [comment]
this looks very nice! I'd be a liiiittle hesitant to merge before 0.13.16 final is out, though. (see also PR #5871)

**Comment by SethTisue** [comment]
0.13.16 final is out. let's merge #5871 first, then this

**Comment by SethTisue** [comment]
merged: e12ac748cda072a42c67cfd0a0151947fc9c36e3

**Comment by 2m** [comment]
Thanks, should we forward port it to 2.13.x branch as well with empty bc issue filters?

**Comment by SethTisue** [comment]
@2m I'll take care of it (and request your review)

**Comment by SethTisue** [comment]
I wish there was some way I could tell GitHub to consider this "merged" (https://github.com/isaacs/github/issues/2)

**Comment by SethTisue** [comment]
I guess it's a lesson that it's really better to get a clean PR one way or the other, then hit the actual "merge" button, rather than take a shortcut like I did.

**Comment by SethTisue** [comment]
@2m https://github.com/scala/scala/pull/6026

**Pull request closed without merging**
