### PR TITLE
Add -Xlint:non-local-return, to warn on non-local returns.

### PR DESCRIPTION
**Pull request by hrhino**
Inspired by conversation on scala/bug#10820.

I'm not prepared for arguments as to its appropriateness, but I'm very prepared for arguments over the wording.

### CODE REVIEW

**Comment by som-snytt** [comment]
It might annoy as `-Xlint` because it's an ordinary language feature easy to trigger. I would use just `-Y` until consensus.

Folks who really care will either have a scalafix to complain about any return, or are willing to add an option. Turning it off is harder.

**Comment by hrhino** [comment]
I hadn't prepared at all for flag bikeshedding.

I originally had `-Y` but the miniature Adriaan in my head said maybe not. Of course it doesn't actually change language semantics; it just potentially changes what compiles. On the other hand good old `-Yoverride-objects` could be said to work the same.

I'm okay with either, though. `-Ywarn-non-local-return`?

**Comment by hrhino** [comment]
(updated with [more examples from the ticket](https://github.com/scala/bug/issues/10820#issuecomment-380494738))

**Comment by som-snytt** [comment]
Partially superseded by the much less replete https://github.com/scala/scala/pull/6627, which has only one SO example.

**Pull request closed without merging**
