### PR TITLE
SI-8138 Fix bug with super-accessors / dependent types

### PR DESCRIPTION
**Pull request by retronym**
Super-accessors are generated as `DefDef`'s with `EmptyTree` as a
placeholder for the RHS. This is filled in later in `Mixin` in
`completeSuperAccessor`.

A change in `Uncurry` ( / 493197f), however, converted this
to a `{ EmptyTree }`, which evaded the pattern match in mixin.

This commit adds a special case to the dependent method treatment
in Uncurry to avoid generating redundant blocks.

### CODE REVIEW

**Comment by xeno-by** [comment]
Not sure what the error is about, so I'll just reset all attrs. PLS REBUILD ALL

**Comment by retronym** [comment]
@xeno-by I've reworked this with your suggestion.

**Comment by xeno-by** [comment]
To the best of my knowledge, LGTM

**Comment by xeno-by** [comment]
Still the same error:

```
sbt.ResolveException: unresolved dependency: org.specs2#specs2_2.10.4-1baf11a-SNAPSHOT;1.12.3: not found
```

What gives?

**Comment by retronym** [comment]
PLS REBUILD ALL

I understand that @gkosskowski / @jsuereth have fixed the glitch in our 2.10.x PR validation.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
