### PR TITLE
Fix for unnecessary InnerClasses for top-level objects.

### PR DESCRIPTION
**Pull request by gkossakowski**
Mirror classes (with static forwarders) for top-level
objects would get unnecessary InnerClasses entries
in some cases. See the following comment I introduced
to the place I fixed:

We need to make sure that we do not confuse inner classes
of the class  we mirror with inner classes of the class
we are mirroring. These two sets can be different as
seen in this case:

``` scala
 class A {
  class B
  def b: B = new B
 }
 object C extends A
```

Here mirror class of C has a static forwarder for
(inherited) method `b` therefore it refers to class `B`
and needs InnerClasses entry. However, the real class
for `C` (named `C$`) is empty and does not refer to `B`
thus does not need InnerClasses entry it.

NOTE: This logic has been refactored in GenASM and
everything is implemented in a much cleaner way by
having two separate buffers.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Ah, I should why there's no test attached. Well, we don't have any good infrastructure for bytecode testing and this specific thing is impossible to test with Java reflection (there's no access to InnerClasses attribute).

**Comment by paulp** [comment]
You can test it with tools/dump-class though.  AKA scala.tools.cmd.program.DumpClass.

Lots more will be testable that way pretty soon; everything really.

**Comment by gkossakowski** [comment]
I did test it with `tools/dump-class` (and `opendiff`) but this is still far from automated test. I feel like we really need a new partest category. Do you have this in mind by saying bytecode will be more testable soon?

**Comment by paulp** [comment]
Sure, although I'm always reluctant to enhance partest because it ties us down that much longer.  Have you seen scala.tools.partest.IcodeTest ?

**Comment by gkossakowski** [comment]
No, I haven't seen it before. It looks somehow close to what I would like to have. One thing I don't like about "dump everything" approach is that it lacks granularity. For example, in this particular case all I care are classes and their InnerClasses attributes. Specifically, I don't care about fields, method and their bodies.

I think, ideally, we would like to have an easy, programatic API for traversing and dumping relevant fragments of bytecode.

**Comment by paulp** [comment]
Yes, of course.  I haven't gotten around to the command line options, but this kind of data is not very far out of reach already.  But nothing is ever easy enough for me.

```
( scala.tools.cmd.program.DumpClass.deepInfos("/scala/trunk/build/quick/classes/library").toMap
    mapValues (_.innerClasses.toList)
    foreach { case (k, vs) => println(vs.mkString(k + "\n  ", "\n  ", "\n")) }
)
```

**Pull request merged**
