### PR TITLE
Add `toLazyList` method for `IterableOnceOps` trait

### PR DESCRIPTION
**Pull request by counter2015**

### CODE REVIEW

**Comment by NthPortal** [comment]
What's the motivation for adding this method over just using `.to(LazyList)`?

**Comment by counter2015** [comment]
Most collection have their `to<CollectionName>` converters. Such  as `toArray` 、 `toList`、`toVector`

It's also ok to just use 
```scala
Seq(1,2,3).to(List)
Seq(1,2,3).to(Vector)
```
etc.

Add this fucntion can keep style consistent. 

And IMO, `LazyList` replace `Stream`, so `toLazyList` should replace `toStream`.

Then user will not confused at why they can use `.toArray`  to get a `Array` but must use `to(LazyList)`  to get a `LazyList`.

**Comment by counter2015** [comment]
It seems some test failed, I will try to fix it later.

**Comment by counter2015** [comment]
I'm not familiar with binary compatibility problem, should I use `mimaBinaryIssueFilters` to skip this problem ?

**Comment by julienrf** [comment]
Hey @counter2015, thanks for your pull request. Unfortunately, this change is not forward binary compatible and we don’t want the 2.13.x series to break forward binary compatibility. You can find similar pull requests (that had to be closed) under the [2.14 milestone](https://github.com/scala/scala/milestone/78?closed=1).

That being said, my opinion on the content of this PR is that it is not necessary to introduce a `toLazyList` operation. I think it’s fine to use `to(LazyList)` instead.

**Comment by NthPortal** [comment]
To elaborate on what Julien said:

As per scala/scala-dev#661, this repository is not accepting binary-incompatible PRs at this time. There may be some time long in the future (3.1? 4.0?) when this repository accepts binary-incompatible changes, but at this time, we are closing such PRs rather than leaving them open for years. For this reason, I am closing this PR. However, I do not mean that to curtail discussion.

There may Soon™ be another path for the future of the library that includes changes that are not forward- and backward-compatible with 2.13, which this PR could target instead; that would leave only the question of whether or not there is a sufficiently compelling reason to add the method.

Regarding your claim that

> Most collection have [a] `to<CollectionName>` [method]

I would actually say that is not the case. There are `toMap` and `toSet` methods that return immutable `Map`s and `Set`s, but there are no such methods for mutable `Map`s and `Set`s, nor for particular implementations of `Map` and `Set` (e.g. `TreeMap`, `HashSet`), mutable or otherwise. `Array` merits its own method because it is a platform-specific collection with special properties, and is actually not a Scala collection type. I actually think `List` and `Vector` are the odd ones out in *having* their own `to<CollectionName>` methods. However, even if we decided that `List` and `Vector` no longer merit special methods, there is to much code that relies on those already existing methods for it to be worth breaking.

Incidentally, we have `toSeq`, `toIndexedSeq`, `toMap` and `toSet`, but not `toLinearSeq`; this seems like an oversight.

**Comment by SethTisue** [comment]
Note that historically, `.toList` and friends are very old; they predate the existence of `.to`. There are probably more of them than would be present in a fresh design. We are moving away from these methods, not towards them. In the long run, I could see them ending up deprecated.

`toList` was present at least as far back as Scala 2.7, perhaps farther. 2.10 added the `.to[List]` form, and then 2.13 changed it to `.to(List)` in order to support e.g. `Map`, which the old `.to[X]` way couldn't handle (because `Map` has two type parameters).

**Pull request closed without merging**
