### PR TITLE
SI-7070 Revert implementation restriction on companions in pkg objs

### PR DESCRIPTION
**Pull request by JamesIry**
The implementation restriction created from SI-5954 has two problems.

1) The problematic code works fine if compile with sbt. That means the
restriction is breaking some people needlessly.

2) It's not binary compatible.

The implementation restriction needs to be reverted.

This commit reverts 3ef487ecb6733bfe3c13d89780ebcfc81f9a5ea0

### CODE REVIEW

**Comment by adriaanm** [comment]
should probably tag the commit as [nomaster] so we don't also revert in master?

**Comment by JamesIry** [comment]
I think I'd rather merge to master since people are going to be using this construct.

**Comment by adriaanm** [comment]
Ah, right. I figured we could change behavior there as the actual bug is unlikely to be fixed in 2.11 and it's better to warn.

**Comment by JamesIry** [comment]
Good point. I'll convert the error to a warning.

**Pull request closed without merging**
