### PR TITLE
SI-3236 constant types for literal final static java fields

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
As mentioned in the original PR, this could be expanded to support (some) composite expressions, but it would be a bigger effort. For that, instead of trying to constant fold and assign types in the parser, I think we should just parse the expression and pass it on to the Scala type checker. But that's also not easy by any means :)

**Comment by lrytz** [comment]
I think the code here is an OK compromise, even with its limitations. For example, it treats `!1` as `-1`. But the Java compiler would reject that of course.

**Comment by lrytz** [comment]
@jrudolph please take a look.

**Comment by jrudolph** [comment]
On first glance, I think it looks good :+1: 

Would it make sense to add tests for the additional feature of implicitly converting the constants?

**Comment by lrytz** [comment]
yes, also some neg tests to make sure the limits are checked. will do.

**Comment by adriaanm** [comment]
One last test failure: test/files/run/t3236 doesn't compile.

**Comment by lrytz** [comment]
Added a neg test to frame the limitations

**Comment by lrytz** [comment]
review by @adriaanm

**Comment by jrudolph** [comment]
:+1: new tests LGTM

**Review by adriaanm — APPROVED** [review]
LGTM

**Comment by adriaanm** [comment]
Thanks!

**Pull request merged**
