### PR TITLE
Tweaks to ChainingOps

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Review by NthPortal — APPROVED** [review]
LGTM

**Review by xuwei-k — APPROVED** [review]
👍

**Comment by dwijnand** [comment]
*squeezes in at the back of the queue, just as the doors are closing*

**Comment by dwijnand** [comment]
@lrytz you suggested returning `self.type` [[1]](https://github.com/scala/scala/pull/6767#discussion_r194310053), given @xuwei-k's findings [[2]](https://github.com/scala/scala/pull/7007#issuecomment-411993259)[[3]](https://github.com/scala/scala/pull/7007#issuecomment-411994017) are you happy to change it to `A`?

**Comment by lrytz** [comment]
Sounds good. Could you add tests to this PR?

**Comment by dwijnand** [comment]
@lrytz Temporarily reverting the `self.type` result type _doesn't_ make the test fail, I'm not sure why. But the test should always pass, so I kept it.

Good to go, for you?

**Comment by eed3si9n** [comment]
Thanks for the cleanup.

**Pull request merged**
