### PR TITLE
Fixes SI-4929, with a test to verify.

### PR DESCRIPTION
**Pull request by stephenjudkins**
Also fixes potential issue with Parsers.phrase not being reentrant; however, I was unable to actually reproduce this issue in practice. (The order in which lastNoSuccess was being set and compared seemed to guarantee that it would never actually be a problem).

### CODE REVIEW

**Comment by paulp** [comment]
Can you verify you have signed and submitted the contributor agreement at http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf ?

**Comment by stephenjudkins** [comment]
Hi, I have submitted my contributor agreement.

**Comment by paulp** [comment]
Sorry about the turnaround speed.  You're in!

**Comment by dcsobral** [comment]
I'm sorry for barging in this late (the ticket did not have a component, so it escaped my filters), but was any benchmarking done? It seems to me that this would make `Parsers` much slower, and it isn't exactly a paragon of speed to begin with.

It seems to me that, in the course of a normal parsing, for each option considered and rejected, the following trade off happens:

Previously: `var` compared against `null`.

Now: `lazy val` have its `DynamicVariable` obtained, and a new closure is instantiated to map the resulting `Option`, which is then `getOrElse` extracted against `true`.

Now, if benchmarks show the resulting performance is about the same, I'm all for this patch. Otherwise, why not just mark `Parsers` as not thread-safe, and turn `JSON` object into a class?

**Comment by dcsobral** [comment]
At the very least, we could drop the `lazy`. Why make something lazy when all but the most trivial parser will use it?

**Comment by paulp** [comment]
See comment at https://issues.scala-lang.org/browse/SI-4929 .

**Comment by zsxwing** [comment]
I think `Parsers` is thread-safe since Scala 2.10. Right? It's hard to know it in SI-4929 since it was not closed explicitly.

**Comment by zsxwing** [comment]
We encountered the memory leak issue mentioned in SI-4929, and plan to change our `Parsers` to object (https://github.com/apache/spark/pull/8357). Just want to make sure it's thread-safe in Scala 2.10 and Scala 2.11.

**Comment by SethTisue** [comment]
Please open an issue at https://github.com/scala/scala-parser-combinators; the code no longer exists in this repo. Also, you have a better chance of getting expert help there.

**Pull request merged**
