### PR TITLE
SI-6516, macros comparing types with == instead of =:=.

### PR DESCRIPTION
**Pull request by paulp**
I gift-wrapped this ticket four months ago:

  'I think it will be enough to say "tpe =:= MacroContextClass.tpe"
   rather than == .'

Indeed. Had to open my own gift. Thanks, paulp!

### CODE REVIEW

**Comment by paulp** [comment]
Review by @xeno-by

**Comment by xeno-by** [comment]
Oh, you've just beaten one of my students to implementing this. Lgtm!

**Comment by retronym** [comment]
:+1: for a one-character patch

**Comment by paulp** [comment]
And a test-to-code ratio of 529:1. TIME TO RAISE YOUR GAMES, BOYS

**Pull request merged**
