### PR TITLE
 SI-6476 Improve error on escapement

### PR DESCRIPTION
**Pull request by som-snytt**
Behavior of escape processing under string interpolation can
be confusing.  This PR improves the exception message so
you know at least what sort of escapes are handled.

```
scala> s"\d".r
scala.StringContext$InvalidEscapeException: invalid escape '\d' not one of [\b, \t, \n, \f, \r, \\, \", \'] at index 0 in "\d". Use \\ for literal \.

scala> s"a\"
scala.StringContext$InvalidEscapeException: invalid escape at terminal index 1 in "a\". Use \\ for literal \.

t6476-bad-esc-d.scala:3: error: ';' expected but string literal found. (A trailing '\' escapes nothing. Use \\, $$ or $" for literal \, $ or ".)
  def f = s"\"abcdef\""
                     ^
```

Also enable $" under -Xfuture. This is the same as retronym's tweak,
but puts it under `-Xfuture` until the ecosystem catches up.

Also give the parser enough knowledge of `s` and `f`
to emit an error on the puzzling badly escaped
quote.  The error is emitted as supplemental
advice when a subsequent syntax error is encountered,
such as an unclosed literal.

The mechanism is non-ideal but serves to mitigate the pain of
many users from us hoi polloi all the way up to paulp.  Hoi paulpoi.

These are the remaining commits from #3695.

Review by @retronym

### CODE REVIEW

**Comment by som-snytt** [comment]
If not @retronym , maybe @densh for parser change.

**Comment by adriaanm** [comment]
Let's load balance to @densh

**Comment by retronym** [comment]
- The first commit looks like a non-controversial improvement.
- I'd suggest that support for `$"` should just be deferred for a string interpolation++ mini SIP.

The parser change seems a bit intrusive. Here are the errors today. Could we live with them?

```
scala> s"abc\"def"
<console>:1: error: ';' expected but 'def' found.
       s"abc\"def"
              ^
<console>:1: error: unclosed string literal
       s"abc\"def"
                 ^

scala> s"abc\$x"
<console>:8: error: not found: value x
              s"abc\$x"
                     ^
```

**Comment by som-snytt** [comment]
@retronym How about putting $" under -Xperimental for now?

Are there more ideas floating around for a SIP?  I'd be willing to write something up.

On "line advice", List vs Map, IIRC, it's normally empty or maybe one item or two on a line.  Whenever it emits line advice, advice for any other line is expunged.  So nothing is retained.

I agree that the parser change is annoying.  Aho and Ullman probably have nothing to add.

But it causes endless pain, or so they say.  If it were liveable, there wouldn't be long discussions on internals and questions on SO.

Sorry about the formatting diffs in Parsers.  The gist is to emit supplemental advice for the built-in interpolators (or their doppelgaengers) that is used only if you wind up with an error on the line.

Maybe there's a more frameworked approach, meaning either encapsulated or pluggable. Actually, that's not a bad idea, since custom interpolators may be used for all sorts of twisted ends.

**Comment by retronym** [comment]
The String Interopation SIP (SISIP?) I was thinking of trailed off: 

https://groups.google.com/d/msg/scala-sips/I-rK84V0sIU/LkEMfVbfxDsJ

Maybe I'm being overly conservative, but I'd rather not change the behaviour of the parser under a -X flag. Tools like IntelliJ, Scalariform have ASTs based on our specified grammar. We should change this stuff at major releases and give them time to implement.

**Comment by som-snytt** [comment]
I'm only half-Swiss, so I do think it's quite conservative to defer `$"`, which represents a severe defect, despite the workaround.  Other flags: `-Xfuture:sip-24` if pending, `-Xexperimental:sip-24` if not.  Or `import language.experimental.sip.interpolationFixed`.

SIP-24 went off-track because Martin breathed his mild suspicion.

The other day, in a discussion about language evolution, I mentioned his `+"reluctance"+` about interpolation, and how it's a popular feature but look at the holes (pun alert) in it.  So I'm sympathetic to caution.

The addition of backticked ids means the spec must decide whether arbitrary ids are OK for interpolation.  That's the obvious and regular choice.

So is this silly?

```
scala> val foo_ = 42
foo_: Int = 42

scala> val foo_* = 43
foo_*: Int = 43

scala> s"$foo_*"
res0: String = 42*
```

Then backticks would only have to come to the rescue for ids with dollars:

```
scala> s"$`Foo$`"
```

I think the reason I stuck this in here was just to update the advice and not add a comment about "// FIXME when SIP-24 is approved".

**Comment by som-snytt** [comment]
The more interesting edge case would be `f"$foo_\"`.  Insofar as it might be lint-worthy.

**Comment by som-snytt** [comment]
Closing to remove a commit and reconsider cleaner or modular supplemental advice, especially in light of other efforts in that direction for Context.

**Comment by som-snytt** [comment]
@som-snytt Dude, I think this fell off your radar.

**Pull request closed without merging**
