### PR TITLE
Delete useless type parameters from Left and Right (Either)

### PR DESCRIPTION
**Pull request by joroKr21**
See what breaks

### CODE REVIEW

**Comment by dwijnand** [comment]
Would be interesting to dig up if this was debated anywhere at any point...  Anyone remember anything?

**Comment by lrytz** [comment]
Some links
  - https://github.com/scala/scala/pull/7080, which is a follow-up to https://github.com/scala/scala/pull/7011, which is a follow-up to https://github.com/scala/scala/pull/6329
  - https://contributors.scala-lang.org/t/change-either-subclasses-type-parameters/1918/23
  - https://stackoverflow.com/questions/64656786/why-do-left-and-right-have-two-type-parameters

**Comment by joroKr21** [comment]
I wonder if it was considered to remove the type parameters though.
Thanks for the links, I will go through them later (and possibly resurrect some discussions).

**Comment by SethTisue** [comment]
rebased, and then let's do a community build run

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2234/ (2.13.5-bin-9c2a584-SNAPSHOT)

**Comment by joroKr21** [comment]
The problem is that a few projects block many others so I'm not sure how conclusive is that run 🤔

**Comment by NthPortal** [comment]
I'm a bit concerned by how many "core" projects are broken by this change, and how much that will likely propagate downstream if we have to change them

**Comment by joroKr21** [comment]
It depends on the type of breakage - if it's just implementations + a couple implicit instances it doesn't sound so bad.

**Comment by joroKr21** [comment]
But it's not clear to me - if I have a library compiled with the two parameter signatures and I use it with a newer Scala version with only one type parameter - is the source going to break? I don't know how `ScalaSignature` works.

**Comment by SethTisue** [comment]
> But it's not clear to me - if I have a library compiled with the two parameter signatures and I use it with a newer Scala version with only one type parameter - is the source going to break? I don't know how ScalaSignature works.

@dwijnand do you know the answer to this? is this https://github.com/lightbend/mima/issues/40 territory?

I'd be willing to explore this further in the community build context, since it appears that the few-projects-blocking-many-others only need small adjustments. but it's only worth doing that if the answer to Georgi's question is "it doesn't matter, it's okay"

**Comment by SethTisue** [comment]
@joroKr21 in some cases I think the failing repos can be adjusted in ways that are actually code improvement regardless of whether the change to `Left` and `Right` goes forward. so for example, at https://github.com/scala/scala-parser-combinators/pull/329 I'm submitting https://github.com/scala/scala-parser-combinators/pull/329/commits/df92b0868d45ea33cbac13414d9e78db83c3ff63 . also, didn't need them here but perhaps `withLeft`/`withRight` will be helpful in other repos

**Comment by SethTisue** [comment]
@joroKr21 let's move the community build aspect of this over to https://github.com/scala/community-build/pull/1320 and then we can summarize any resulting conclusions here

**Comment by sjrd** [comment]
I had not thought about @joroKr21's question before. I think it is a very real danger, and that it could severely damage the ecosystem. I am indeed afraid that we would experience a sort of "linkage error" at the Scala symbol level.

**Comment by joroKr21** [comment]
Here is a PR in cats that did something similar: typelevel/cats#3012

**Comment by dwijnand** [comment]
> > But it's not clear to me - if I have a library compiled with the two parameter signatures and I use it with a newer Scala version with only one type parameter - is the source going to break? I don't know how ScalaSignature works.
> 
> @dwijnand do you know the answer to this? is this [lightbend/mima#40](https://github.com/lightbend/mima/issues/40) territory?

MiMa only considers (and not well enough to have it on by default) `Signature` only, which is Java generic method signature.  I'm not sure how many cases there are of breaking changes that `ScalaSignature` sees but `Signature` wouldn't, because I don't know where `Signature`'s limits are.

But I can easily believe that this would break source compatibility, which I believe we generally don't mind, unless it's overwhelmingly used.  My gut tells me this should've landed in 2.13.0 and must wait 3.T now.

**Comment by lrytz** [comment]
Great observation, thanks! To make an example, say we start with

```scala
case class A[X, Y](x: X)
case class B(a: A[Int, Nothing])
object Test {
  def main(args: Array[String]): Unit = println(B(A(1)))
}
```

Then changing `A` to

```scala
case class A[X](x: X)
```

is binary compatible, we can re-compile only `A` and `Test` still runs.

But if we then try to re-compile only `Test` (with the new `A.class` and the original `B.class`), we get a type error

```
Test.scala:3: error: type mismatch;
 found   : A[Int]
 required: A[Int,Nothing]
    println(B(A(1)))
               ^
1 error
```

The symbol table is in an inconsistent state. It says that `A` has a single type parameter (`found: A[Int]`), but the type of `B`'s parameter is still `A[Int, Nothing]`, a `TypeRef` with two arguments, as that's what the compiler reads from `B`'s `ScalaSignature`. There's no error reported when this type is built, unpickling doesn't do any type checking.

**Comment by joroKr21** [comment]
@lrytz thanks for looking into that. I guess then this is a no-go. Cats probably got away with it because the typelevel ecosystem is usually quick to propagate updates.

**Comment by SethTisue** [comment]
@joroKr21 thanks for working on this. looking forward to revisiting it for Scala 3.T.

**Comment by SethTisue** [comment]
Summary of community build results from https://github.com/scala/community-build/pull/1320 : with only minor adjustments to a few repo's sources, we were able to get to 90 green repos (out of 200+), but the next blockers were Shapeless and Cats, and adapting those to this change would be more work, and could make cross-building of those libraries difficult — someone would have to see if some trick could make it cross-compilable.

**Comment by joroKr21** [comment]
> someone would have to see if some trick could make it cross-compilable.

I guess one would have to use version-specific type aliases.

**Comment by SethTisue** [comment]
Was just discussing this with @dwijnand, and I want to record some of my new and/or confirmed understandings, to spell things out for the record:

 In Lukas's example, imagine that `A` is the Scala standard library, `B` is library code, and `Test` is application code. Suppose we made this `Either` change in 2.13.5. Then end users (`Test`) would not be able to upgrade to 2.13.5 without also waiting for the author of `B` to recompile their library on 2.13.5. This breaks Scala's fundamental binary compatibility promise, which says that you can use any minor Scala version with any mix of libraries compiled on any mix of minor Scala versions.

We are (at least, I am) used to thinking of binary compatibility problems as occurring at runtime. Lukas's example shows that sometimes it's caught at compile time. Compile-time failures are better than runtime failures, but it's still a bincompat violation, as per previous paragraph.

What about MiMa, would MiMa catch this, should MiMa catch this? Answer: yes, it should and it presumably already does, or rather would, via `IncompatibleSignatureProblem` (https://github.com/lightbend/mima#incompatiblesignatureproblem). But such checking is opt-in, since (Dale says) it is inherently prone to false positives. Here in scala/scala we don't opt-in:

```
% git grep mimaReportSignatureProblems
project/MimaFilters.scala://  mimaReportSignatureProblems := true, // TODO: enable
```

And Cats (which I'm choosing as an example because of https://github.com/typelevel/cats/pull/3012) doesn't opt-in to this either afaict.

Dale, maybe you could say something about the feasibility of having scala/scala opt in to this?

**Comment by djspiewak** [comment]
This is really interesting. I'm not aware of any bug reports which arose from the scenario Lukas points out, but it indisputably existed. One thing which probably saves us a bit is the fact that the `Parallel` change was made between 1.x and 2.x. We soft-promised binary compatibility between the two, but none of the tooling assumes they're compatible and most library authors behave as if they aren't, so in practice we just avoided this issue entirely.

**Comment by dwijnand** [comment]
> Dale, maybe you could say something about the feasibility of having scala/scala opt in to this?

We'd have to significantly improve how MiMa parses and compares signatures, which currently supports: (1) == and (2) some type params were renamed.  Likely one could build a repertoire of such false positives by mining in the git history the ones that we had excluded before MiMa made it opt-in.  Otherwise we'll just go back to blindly excluding.

**Comment by martijnhoekstra** [comment]
For future reference, if this gets fixed in the next compatibility break, also take a look at `Failure[T]` which can maybe just be `Failure extends Try[Nothing]`, though there are more trade-offs there.

**Pull request closed without merging**
