### PR TITLE
correct dynamic pos 2.10.x

### PR DESCRIPTION
**Pull request by kiritsuku**
Follow up from #3188

### CODE REVIEW

**Comment by retronym** [comment]
LGTM. I appreciate the expanded commit messages, very clear now.

I'd appreciate a second pair of eyes from @dotta who was recently working on positions.

**Comment by dotta** [comment]
@retronym I'll look at it today. Thanks for pinging me!

**Comment by dotta** [comment]
LGTM!

@sschaef Great to have you working on positions! Really nicely done.

**Comment by kiritsuku** [comment]
@retronym Are there specific time frames when 2.10.x will be merged into 2.11.x? I'm just asking because I want to know when I can open a PR against scala-ide that is based on PR against scalac.

**Comment by retronym** [comment]
I will fast track the merge

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by dotta** [comment]
@retronym I was actually wondering, what would you think of converting all tests pushed with this PR into presentation compiler tests? My feeling is that they'd be a bit more robust, but I may be wrong.

**Comment by retronym** [comment]
I'm happy enough with the raw tests of positions. If they change, we'll be alerted of the fact.

But some other tests are now failing:

```
BUILD FAILED
/localhome/jenkins/b/workspace/pr-scala-test/scala/build.xml:1540: Test suite finished with 10 cases failing:
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/pos/t5726.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/neg/applydynamic_sip.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/t5733.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/applydynamic_sip.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/dynamic-selectDynamic.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/dynamic-applyDynamicNamed.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/t7617b [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/t6731.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/dynamic-applyDynamic.scala [FAILED]
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/dynamic-updateDynamic.scala [FAILED]
```

**Comment by dotta** [comment]
> I'm happy enough with the raw tests of positions. If they change, we'll be alerted of the fact.

@retronym Sounds good to me!

**Comment by kiritsuku** [comment]
I can't reproduce the failures locally. I think kitty doesn't like me. :(

Running the whole test suite right now, maybe that makes a difference.

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
I can reproduce the failures:

```
% pta pos/t5726
% tests with matching paths       ...  1
% tests with matching code        ...  0
# 1 tests to run.
/code/scala2/test/partest --show-diff                \
  test/files/pos/t5726.scala                         \


Testing individual files
Log file 'test/files/pos/t5726-pos.log':
java.lang.UnsupportedOperationException: Position.end on class scala.reflect.internal.util.OffsetPosition
    at scala.reflect.internal.util.Position.end(Position.scala:126)
```

**Comment by retronym** [comment]
> I can't reproduce the failures locally. I think kitty doesn't like me. :(

I guess you were running against master. Let's move over to #3196.

**Pull request closed without merging**
