### PR TITLE
SI-7747 Support class based wrappers as alternative through a switch.

### PR DESCRIPTION
**Pull request by ScrapCodes**
This is a re-implementation after feedback on #2788. 

Motivation: 
We at spark, have to customize scala repl to support our way of "code wrapping" for input code. The reason we want it that way is spark needs code serializable so that it can be executed on a remote worker.

 I wish it was possible to configure rather than port scala repl code for every scala release migration. This pull request may _only_ present my intention which is, we may not need a complete overhauling of scala REPL to support it and thus there should be a simpler solution to it.  It also has a sample customization which uses `class` instead of `object` for wrapping code to be executed. The sample customization is exactly what we would need for spark i.e. serializable. Actually there is more space for making things in the repl customizable, but then this is just a beginning. This has been done in this particular way only to achieve the goal in minimal code change at expense of elegance. Of course suggestions and reviews comments are welcomed for me being on lurker side trying to step into space that might not be welcoming for its technical depth. 

For Example

``` scala

scala> val a = 10
a: Int = 10

scala> val b = a * 2 // show
class $read extends Serializable {
  def <init>() = {
    super.<init>;
    ()
  };
  class $iwC extends Serializable {
    def <init>() = {
      super.<init>;
      ()
    };
    val $VAL1 = $line3.$read.INSTANCE;
    import $VAL1.$iw.$iw.a;
    class $iwC extends Serializable {
      def <init>() = {
        super.<init>;
        ()
      };
      val b = a * 2
    };
    val $iw = new $iwC.<init>
  };
  val $iw = new $iwC.<init>
}
object $read extends scala.AnyRef {
  def <init>() = {
    super.<init>;
    ()
  };
  val INSTANCE = new $read.<init>
}
b: Int = 20

scala> 

```

### CODE REVIEW

**Comment by retronym** [comment]
You've explained the motivation and implementation in the original pull request. Could you transfer some of that into the commit comment and internal documentation in the code?

**Comment by retronym** [comment]
I believe the code would be cleaner if all the `if (classBasedWrappers) .. else ..` were replaced by polymorphism. Could you please take a stab a that refactoring, and push it as a second commit?

**Comment by ScrapCodes** [comment]
Jason, Thank you so much for looking at this. I have tried to refactor to reduce the number of if else needed. Please take a look.

**Comment by retronym** [comment]
It's not quite there yet. Sorry I was a bit vague. I'd like to see exactly one if/else.

Could you try for this refactoring? If it gets stuck, let me know why.

``` scala
class IMain {
   // others could customise this by subclassing IMain and using a different wrapper.
   protected val wrapper: Wrapper = if (settings.YclassbasedWrapper) new ClassBasedWrapper else new ObjectBasedWrapper

}

// Wrapper.scala
trait Wrapper {
  // All code that is if/else-d has a hook in here.
}

trait ClassBasedWrapper {
  // your implementations
}

trait ObjectBasedWrappers {
  // your implementations
}
```

**Comment by som-snytt** [comment]
Coincidentally, yesterday I started a refactor of scripting for this use case. My WIP is at

https://github.com/som-snytt/scala/tree/issue/7747-replating

I move the default script runner wrapping from parser into a separate scripter phase.  With the ability to replace phases, the repl supplies its own scripter phase.  Customizations would do the same.  The custom scripter could be supplied via plugin.

I have to work out details of plumbing; I'll try to complete the concept anyway today.

**Comment by retronym** [comment]
If you're taking a look at scripting, let me contribute to the wishlist:

One other thing I'd like out the script runner for it to detect if the script is vanilla Scala (ie packages and top level classes/objects), then the compile it as such, detect if that compilation unit has an single object with a main method, and then run that.

Currently we have a super-hacky approach that detects if there is a single class with a method called 'main', and it transplants the contents into the script runner. See `def scriptBody` in `Parsers`.

**Comment by som-snytt** [comment]
Your wish is my command.  Once the genie is out of the bottle, it's easier to effect change.

I noticed your issue yesterday in a test case, where something got wrapped unexpectedly.  I sympathized with the comment there; everything is harder if you don't follow typer.

**Comment by ScrapCodes** [comment]
I am sorry, but there is barely anything that I could understand. How can scripting help this issue. Can you please explain, how this is related to 7747. Will it be possible to provide plugin for the way classes are wrapped in repl ?

**Comment by som-snytt** [comment]
I just sat down to the computer at the end of the day -- I know, it's a bad habit to check messages before coding -- but what I'm about to code is to refactor the code wrapping logic into a scripter phase of ReplGlobal.  I've already deleted the comment in ReplGlobal.scala where it says it doesn't do much.  There are two bits of munging, the first to add the synthetic `val res0 = lastTree` and then the object wrapper in Request.  So that phase just receives the incoming trees wrapped in a fake `<script>` package, and then does the munging.

Currently, REPL pre-parses a line to check for errors or incomplete input, and on success, wraps the line in text and submits it to the compiler.  In the new scheme, you submit just the line, and if it parses, the compiler client doesn't touch it again.  I'll also decouple post-processing from the scripter phase, "recording" the request in history, and eval and print.

Currently, the eval is invoked reflectively, but it seems to me the scripter might agree to conform to an interface, or alternatively specify arbitrary names (for which you'd pay the tax of reflection).

If that hangs together, I'll incorporate what you've tackled here to make it easy to select from two standard styles of wrapping or extend the model.  The other moving part to that is how imports are tracked.

**Comment by ScrapCodes** [comment]
That is so cool !, I think it will be much better from what I was thinking. I especially like the fact, that it will be possible to select from two(object and class based) styles of wrapping models. Thanks alot !

**Comment by retronym** [comment]
It seems like this needs a bit more time. Thanks for your patience and persistence!

Ideally this fix would be ready by mid-August for 2.11.0-M7 to make sure we get it into the release. Ping me if you need any help.

**Comment by adriaanm** [comment]
mid-october, of course ;-) looking forward to it!

**Pull request closed without merging**
