### PR TITLE
SI-6555 Better parameter name retention

### PR DESCRIPTION
**Pull request by retronym**
We were losing track of parameter names in two places:
1. Uncurry was using fresh names for the apply method
    parameters during Function expansion. (The parameter names
    in the tree were actually correct, they just had synthetic
    symbols with "x$1" etc.)
2. When adding specialized overrides, the parameter names
    of the overriden method were used, rather than the parameter
    names from the overriding method in the class to which we are
    adding methods.

The upshot of this is that when you're stopped in the debugger in
the body of, say, `(i: Int) => i * i`, you see `v1` rather than `i`.

This commit changes Uncurry and SpecializeTypes to remedy this.

Review by @dragos

### CODE REVIEW

**Comment by ijuma** [comment]
Nice.

**Comment by dragos** [comment]
LGTM. Thanks a lot!

**Comment by adriaanm** [comment]
Sorry, right after I hit merge I realized the bug number is wrong. This actually fixes https://issues.scala-lang.org/browse/SI-6655

**Comment by retronym** [comment]
Oops, I think we need a checksum bit.

**Pull request merged**
