### PR TITLE
Deconst  method result type and patmat label info

### LINKED ISSUE #10768: Typer crash related to literal singleton types
I haven't been able to reproduce this outside of the REPL, I assume this is related to literal singleton types since `val a = 1; foo(a)` does not trigger the crash:
```scala
Welcome to Scala 2.13.0-M3 (OpenJDK 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala> type Id[T] = T
defined type alias Id

scala> def foo(x: Int): Id[x.type] = x
foo: (x: Int)Id[x.type]

scala> foo(1)
scala.reflect.internal.Types$TypeError: assignment to non variable
        at scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1414)
        at scala.tools.nsc.typechecker.Contexts$ContextReporter.issue(Contexts.scala:1266)
        at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:584)
        at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:98)
        at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:91)
        at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AssignmentError(ContextErrors.scala:321)
        at scala.tools.nsc.typechecker.Typers$Typer.fail$2(Typers.scala:4413)
        at scala.tools.nsc.typechecker.Typers$Typer.typedAssign$1(Typers.scala:4416)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5628)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5657)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5664)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5733)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5674)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5679)
        at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5764)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3127)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3271)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3271)
        at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2461)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$98(Typers.scala:5622)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typerWithLocalContext$1(Typers.scala:493)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:493)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5657)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5664)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5733)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5674)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5679)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5775)
        at scala.tools.nsc.typechecker.Typers$Typer.typedIf$1(Typers.scala:4449)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5623)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5657)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5664)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5733)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5674)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5679)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3287)
        at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:484)
        at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3701)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$36(Typers.scala:3709)
        at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3709)
        at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3720)
        at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4792)
        at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4820)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5647)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5664)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5733)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5674)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5679)
        at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5764)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3127)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3271)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3271)
        at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2461)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$98(Typers.scala:5622)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typerWithLocalContext$1(Typers.scala:493)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:493)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5657)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5664)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5733)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5674)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5679)
        at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5915)
        at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2292)
        at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5601)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5663)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5733)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5674)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5679)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5760)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPos(Typers.scala:5767)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.typedPos(Fields.scala:541)
        at scala.tools.nsc.transform.AccessorSynthesis$CheckedAccessorTreeSynthesis$SynthLazyAccessorsIn.$anonfun$expandLazyClassMember$2(AccessorSynthesis.scala:298)
        at scala.tools.nsc.transform.AccessorSynthesis$CheckedAccessorTreeSynthesis$SynthLazyAccessorsIn.$anonfun$expandLazyClassMember$1(AccessorSynthesis.scala:298)
        at scala.tools.nsc.transform.AccessorSynthesis$CheckedAccessorTreeSynthesis$SynthLazyAccessorsIn.expandLazyClassMember(AccessorSynthesis.scala:298)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:736)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transformTermsAtExprOwner(Fields.scala:763)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.$anonfun$transformStats$3(Fields.scala:776)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:776)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:540)
        at scala.reflect.internal.Trees$Template.transform(Trees.scala:486)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:755)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:540)
        at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2565)
        at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:317)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:316)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:746)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.$anonfun$transformStats$4(Fields.scala:776)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:776)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transformStats(Fields.scala:540)
        at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:298)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:298)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.Fields$FieldsTransformer.transform(Fields.scala:755)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:155)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:400)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:400)
        at scala.collection.Iterator.foreach(Iterator.scala:938)
        at scala.collection.Iterator.foreach$(Iterator.scala:938)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1426)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1453)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1437)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:711)
        at scala.tools.nsc.interpreter.IMain$Request.$anonfun$compile$7(IMain.scala:918)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
        at scala.tools.nsc.interpreter.IMain.$anonfun$withoutWarnings$1(IMain.scala:95)
        at scala.tools.nsc.interpreter.shell.ReplReporterImpl.withoutPrintingResults(Reporter.scala:44)
        at scala.tools.nsc.interpreter.IMain.withoutWarnings(IMain.scala:90)
        at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:918)
        at scala.tools.nsc.interpreter.IMain.$anonfun$compile$2(IMain.scala:504)
        at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:504)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:498)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:481)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:892)
        at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:750)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:455)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:478)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$run$1(ILoop.scala:985)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:950)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:80)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:83)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:94)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:99)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

### LINKED ISSUE #10788: Inferred ConstantType type arguments are not properly deconsted resulting in bogus constant inlining
This appears to go way back ... it's present in 2.13.x, 2.12, 2.11 and 2.10 at least. Whilst literal types in 2.13.x provide more opportunities for manifesting it, the underlying problem is orthogonal to literal types. Related to https://github.com/scala/bug/issues/8564 (the fix reported there as being in the literal types PR clearly wasn't thorough enough) and possibly also to https://github.com/scala/bug/issues/10340.

No output is produced when the following is run,
```scala
object Test {
  class Box[T](t: T) {
    def foo: T = {
      println("effect")
      t
    }
  }

  object Box {
    def apply(x: String): Box[x.type] = new Box[x.type](x)
  }

  def main(args: Array[String]): Unit = {
    val bar = Box("foo").foo
  }
}
```
If we look at the trees following typer we can see why,
```scala
object Test extends scala.AnyRef {
  class Box[T] extends scala.AnyRef {
    <paramaccessor> private[this] val t: T = _;
    def foo: T = {
      scala.Predef.println("effect");
      Box.this.t
    }
  };
  object Box extends scala.AnyRef {
    def apply(x: String): Test.Box[x.type] = new Test.Box[x.type](x)
  };
  def main(args: Array[String]): Unit = {
    val bar: String = "foo";
    ()
  }
}
```
The definition of `bar`,
```scala
val bar = Box("foo").foo
```
has been transformed to,
```scala
val bar: String = "foo";
```
The cause of the problem is that the `Box` value is created with its type parameter `T` instantiated as `x.type` which is computed as the (internal) `ConstantType(Literal("foo"))`. This results in the subsequent application of `foo` also being seen as having a constant type and so being eligible to be inlined as the constant value, eliding the object creation, method call and effect.

### PR DESCRIPTION
**Pull request by adriaanm**
(Reworks #6452 with a more narrow fix.)

When a constant value is returned from a method --
even one without argument list -- we must deconst,
as we know nothing about the method's purity, and
thus cannot constant fold through that application.

By analogy to the nullary method case in adapt, deconst
result, unless it's a stable method invoked on safe to inline expr

Also, deconst result type of getters during fields phase:
constant folding time is over (that happens before, during typers),
but constant types have not yet been eliminated (that happens during erasure).

So, we must deconst the result type of methods to avoid treating
their application as a constant...

In patmat, deconst info of default label for collapsed switch

Now that we're more conservative about deconsting
the result of a method application (nullary or not),
a bug in the pattern matcher is revealed: before,
we would constant fold the jump to the default label,
as well as the labeldef itself (since its type wasn't deconsted).
but its disappearance was compensated by the disappearance
of the jump to it.

Now, the jump isn't deconsted, and neither is the label def.

Fix scala/bug#10788
Fix scala/bug#10768

### CODE REVIEW

**Comment by adriaanm** [comment]
Needs squashing, but otherwise I think the fix is ok.

**Comment by milessabin** [comment]
Nice one!

Any chance of a brief summary of what I was getting wrong in #6452?

**Comment by adriaanm** [comment]
The key difference is that we defer deconsting until the const type is at the top-level (I think it was an oversight it was not done for result types of method applications). The semantics of pushing deconst through type constructors etc as implemented in #6452 is not clear to me.

**Pull request merged**
