### PR TITLE
SI-2458 Explicit import should shadow def in other comp. unit

### PR DESCRIPTION
**Pull request by retronym**
Fixes the implementation of point 4. from SLS chapter 2:

> Definitions made available by a package clause not in the
> compilation unit where the definition occurs have lowest precedence.

We had code to deal with this:

```
if (defSym.exists && impSym.exists) {
  if (isPackageOwnedInDifferentUnit(defSym))
    defSym = NoSymbol
```

But, in the `pos/t2458a`, no `impSym` was around, due to filtering
in `depthOk`. The depth of the imported symbol was the same as the
depth of the defined symbol, which didn't pass:

```
imp.depth > symbolDepth
```

`depthOk` already had special handling for Java sources: if the
import is non-wildcard and depths are equal, retain the import.

This commit does the same thing for Scala sources, using the
`isPackageOwnedInDifferentUnit` as the criteria. It also makes
the check for the "imported ... is permanently hidden" warning
to avoid this spurious warning:

```
test/files/pos/t2458a/A.scala:3: warning: imported `BitSet' is permanently hidden by definition of class BitSet in package p
import scala.collection.BitSet
                    ^
```

I have retained compatibiltiy with the bug under -Xsource:2.10

Review by @adriaanm. I'l trigger a dbuild of this one to check for fallout.

### CODE REVIEW

**Comment by retronym** [comment]
Dbuild: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/

I expect it to fail on scala-io until we merge https://github.com/scala/scala/pull/3627

**Comment by adriaanm** [comment]
I'd rather introduce this in 2.11.1 under -Xsource:2.12 / -Xfuture. We shouldn't have RC2 break code that compiled in RC1 unless warranted by some serious regression.

**Comment by gkossakowski** [comment]
I agree with @adriaanm.

**Comment by retronym** [comment]
Righto. The ticket was marked as a blocker, but I guess that was when we thought it was a spec bug.

For the record, the dbuild passed. But I'll close this one for now.

**Comment by adriaanm** [comment]
I'm okay leaving it open under the 2.11.1-RC1 milestone.

**Comment by retronym** [comment]
I'll need to rework the way this is governed by `-Xsource` anyway.

**Pull request closed without merging**
