### PR TITLE
Simplify checking for already-published artifacts

### PR DESCRIPTION
**Pull request by retronym**
Use a maven incantation that allows download of a dependency
without needing to create a dummy project.

### CODE REVIEW

**Review by adriaanm — APPROVED** [review]
Nice!

**Comment by adriaanm** [comment]
Let's rebase this on 2.12.x, or I can also roll it into my travis PR

**Comment by retronym** [comment]
If and once 76b1abd builds, we should trigger a rebuild manually on Jenkins and check the logs to ensure that `publishCore` is skipped.

**Comment by retronym** [comment]
So far so good, this is the error we expect for the first run:

```
++ mvn -q -DremoteRepositories=https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ -DgroupId=org.scala-lang -DartifactId=scala-compiler -Dversion=2.12.5-bin-76b1abd-SNAPSHOT -Dtransitive=false dependency:get
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT in temp (https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/)
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file -DgroupId=org.scala-lang -DartifactId=scala-compiler -Dversion=2.12.5-bin-76b1abd-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there:
[ERROR] mvn deploy:deploy-file -DgroupId=org.scala-lang -DartifactId=scala-compiler -Dversion=2.12.5-bin-76b1abd-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR] org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] central-cache (https://scala-ci.typesafe.com/artifactory/central/, releases=true, snapshots=false),
[ERROR] temp (https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/, releases=true, snapshots=true)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
++ RES=1
++ set -e
++ '[' 1 == 0 ']'
++ debug 'org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT not found !'
++ echo '----- org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT not found !'
----- org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT not found !
++ RES=false
```

**Comment by retronym** [comment]
Looks good for the [re-run](https://scala-ci.typesafe.com/job/scala-2.12.x-validate-main/290/console) too:

```
++ echo '>>> Checking availability of Scala 2.12.5-bin-76b1abd-SNAPSHOT in https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/.'
>>> Checking availability of Scala 2.12.5-bin-76b1abd-SNAPSHOT in https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/.
++ checkAvailability org.scala-lang scala-library 2.12.5-bin-76b1abd-SNAPSHOT https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/
++ pushd /tmp/pr-scala.EGdH/tmp
/tmp/pr-scala.EGdH/tmp ~/workspace/scala-2.12.x-validate-main
++ rm -rf '*'
++ set +e
++ mvn -q -DremoteRepositories=https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ -DgroupId=org.scala-lang -DartifactId=scala-library -Dversion=2.12.5-bin-76b1abd-SNAPSHOT -Dtransitive=false dependency:get
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
++ RES=0
++ set -e
++ '[' 0 == 0 ']'
++ debug 'org.scala-lang:scala-library:jar:2.12.5-bin-76b1abd-SNAPSHOT found !'
++ echo '----- org.scala-lang:scala-library:jar:2.12.5-bin-76b1abd-SNAPSHOT found !'
----- org.scala-lang:scala-library:jar:2.12.5-bin-76b1abd-SNAPSHOT found !
++ RES=true
++ popd
~/workspace/scala-2.12.x-validate-main
++ libraryAvailable=true
++ checkAvailability org.scala-lang scala-reflect 2.12.5-bin-76b1abd-SNAPSHOT https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/
++ pushd /tmp/pr-scala.EGdH/tmp
/tmp/pr-scala.EGdH/tmp ~/workspace/scala-2.12.x-validate-main
++ rm -rf '*'
++ set +e
++ mvn -q -DremoteRepositories=https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ -DgroupId=org.scala-lang -DartifactId=scala-reflect -Dversion=2.12.5-bin-76b1abd-SNAPSHOT -Dtransitive=false dependency:get
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
++ RES=0
++ set -e
++ '[' 0 == 0 ']'
++ debug 'org.scala-lang:scala-reflect:jar:2.12.5-bin-76b1abd-SNAPSHOT found !'
++ echo '----- org.scala-lang:scala-reflect:jar:2.12.5-bin-76b1abd-SNAPSHOT found !'
----- org.scala-lang:scala-reflect:jar:2.12.5-bin-76b1abd-SNAPSHOT found !
++ RES=true
++ popd
~/workspace/scala-2.12.x-validate-main
++ reflectAvailable=true
++ checkAvailability org.scala-lang scala-compiler 2.12.5-bin-76b1abd-SNAPSHOT https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/
++ pushd /tmp/pr-scala.EGdH/tmp
/tmp/pr-scala.EGdH/tmp ~/workspace/scala-2.12.x-validate-main
++ rm -rf '*'
++ set +e
++ mvn -q -DremoteRepositories=https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ -DgroupId=org.scala-lang -DartifactId=scala-compiler -Dversion=2.12.5-bin-76b1abd-SNAPSHOT -Dtransitive=false dependency:get
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
++ RES=0
++ set -e
++ '[' 0 == 0 ']'
++ debug 'org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT found !'
++ echo '----- org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT found !'
----- org.scala-lang:scala-compiler:jar:2.12.5-bin-76b1abd-SNAPSHOT found !
```

**Pull request merged**
