### PR TITLE
[2.10.x] assorted fixes for vampire macros

### PR DESCRIPTION
**Pull request by xeno-by**
As eloquently elaborated and cleverly named by Travis Brown, macros
defined in structural types are useful:
http://meta.plasm.us/posts/2013/07/12/vampire-methods-for-structural-types/.

However, since such macros are on the intersection of a number of language
features, as usual, there are bugs. This pull requests fixes a couple of them.

### CODE REVIEW

**Comment by retronym** [comment]
From the [mailing list](https://groups.google.com/forum/#!topic/scala-internals/otRPlIRoEqs), @odersky said:

> After thinking some more about it, I want to come back to the suggestion of Stefan: Macros can never override but they can overload normal methods. We get the required subtyping between structural types without any further rules that way. 
> 
> Also, unlike what we thought at the meeting, we need not change the overloading rules to make this work well. In the primary use case of having a foreach macro on Range, that macro already takes precedence over any inherited method in overloading resolution, because it is defined in a subclass of IndexedSeq#foreach.
> 
> Finally, with that change, we can drop the rule that prevents a macro from overriding an abstract method, since no overriding is possible in the first place. Everything gets simpler across the board. 
> 
> Conclusion: I agree with the aims of the pull request, but we should pick a different mechanism to achieve them.

@xeno-by Does this PR need refurbishment in light of Martin's comments?

**Comment by xeno-by** [comment]
@retronym That's what I wanted to discuss yesterday, but we all were so carried away by hygiene :)

I suggest we wait until the next week's reflection meeting.

**Comment by retronym** [comment]
@xeno-by I'll be at the office again today, so we can discuss if you're @ EPFL.

**Comment by xeno-by** [comment]
Don't know whether I'll be at EPFL today - Strange Loop is nearing.

**Comment by retronym** [comment]
No probs. I'll close this PR for now.

**Comment by xeno-by** [comment]
Just discussed this at the reflection meeting and decided to reopen as is.

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
Btw would be great to have this in M6.

**Comment by xeno-by** [comment]
@adriaanm The build is green, but github is still yellow. Is this spurious?

**Comment by adriaanm** [comment]
This is how we encode that an earlier commit failed whereas the last one was fine. Github only looks at the last commit, so it needs to be marked "failed" if any earlier commit failed.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Okay since our discussion is going on at https://github.com/scala/scala/pull/2993, I'm closing this one for the time being.

**Pull request closed without merging**
