### PR TITLE
SI-6815 Loosen definition of stability in stable ID patterns

### PR DESCRIPTION
**Pull request by retronym**
Before, a stable identifier pattern was vetted by `isStable`,
which delegates to `isExprSafeToInline`. This requires that
the result type of the expression is non-volatile.

But, according to @adriaanm, while "it's unsound to select
types on a prefix with a volatile type", it "should be fine
to compare it for equality."

The infrastructure to perform the looser check was already
in place for reporting stability errors; this commit employs
it when checking stability of patterns.

The enclosed `neg` test shows that this doesn't overreach:
type selections are still disallowed.

Review by @adriaanm

### CODE REVIEW

**Comment by paulp** [comment]
Wouldn't this distinction better be encoded as

```
  def isStablePrefix = ...
  def isStableValue = ...
```

rather than having confusingly different ideas of "stable" running around?

**Comment by adriaanm** [comment]
+1, I'd also use this to decouple the checks from returning an (error) tree so that they compose

also, s/checkStableOrStableExceptVolatile/checkStableAdmittingVolatile/ ? or s/AdmittingVolatile/IgnoringVolatility/ ?

**Comment by retronym** [comment]
Those names sound much better; I'll rework tomorrow.

**Comment by retronym** [comment]
... though I'm not 100% sure of the detail of your proposals. Care to say it with a patch?

**Comment by adriaanm** [comment]
Ok.

**Comment by adriaanm** [comment]
While pulling on this thread, lots of ickiness in stability/volatility checking unravelled.
Here's something to get us on our way to cleaning this up: https://github.com/adriaanm/scala/compare/2.10.x...ticket-6815

**Comment by retronym** [comment]
That proposal looks great. Do you want me to pick that up, or do you plan to submit it?

**Comment by adriaanm** [comment]
Thanks. I'll discuss it in the compiler meeting and wrap it up if Martin approves.

**Comment by adriaanm** [comment]
Turned out to be more involved than I thought, but should only be a test case or two away: https://github.com/adriaanm/scala/compare/2.10.x...ticket-6815

**Pull request closed without merging**
