### PR TITLE
[indylambda] Support lambda {de}serialization

### PR DESCRIPTION
**Pull request by retronym**
To support serialization, we use the alternative lambda metafactory that
lets us specify that our anonymous functions should extend the marker
interface `scala.Serializable`. They will also have a
`writeObject` method added that implements the serialization proxy pattern
using `j.l.invoke.SerializedLamba`.

To support deserialization, we synthesize a `$deserializeLamba$` method in
each class. This will be called reflectively by
`SerializedLambda#readResolve`. This method in turn delegates to
`LambdaDeserializer`, currently defined [1] in `scala-java8-compat`, that
uses `LambdaMetafactory` to spin up the anonymous class and instantiate it
with the deserialized environment.

Note: `LambdaDeserializer` reuses the anonymous class on subsequent
deserializations of a given lambda, in the same spirit as an invokedynamic
call site only spins up the class on the first time it is run.

`LambdaDeserializer` will be moved into our standard library in the 2.12.x
branch, where we can introduce dependencies on the Java 8 standard library.

The enclosed test cases must be manually run with indylambda enabled. Once
we enable indylambda by default on 2.12.x, the test will actually test the
new feature.

```
% echo $INDYLAMBDA
-Ydelambdafy:method -Ybackend:GenBCode -target:jvm-1.8 -classpath
.:scala-java8-compat_2.11-0.5.0-SNAPSHOT.jar
% $INDYLAMBDA -e "println((() => 42).getClass)" class
Main$$anon$1$$Lambda$1/1183231938
% qscala $INDYLAMBDA -e "assert(classOf[scala.Serializable].isInstance(()
=> 42))"
% qscalac $INDYLAMBDA test/files/run/lambda-serialization.scala && qscala
$INDYLAMBDA Test
```

This commit contains a few minor refactorings to the code that generates
the invokedynamic instruction to use more meaningful names and to reuse
Java signature generation code in ASM rather than the DIY approach.

[1] https://github.com/scala/scala-java8-compat/pull/37

### CODE REVIEW

**Comment by retronym** [comment]
Review by @lrytz @adriaanm 

Builds on top of #4497.

I will add a commit to update our reference in build.xml to 0.5.0 of scala-java8-compat when we merge https://github.com/scala/scala-java8-compat/pull/37 and release a new version.

**Comment by lrytz** [comment]
High-level question: could we introduce `SerializableFunctionN` functional interfaces instead of switching to `altMetafactory`?

**Comment by retronym** [comment]
`metafactory` never generates the code to implement the serialization proxy pattern, it passes `isSerializable = false` [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/lang/invoke/LambdaMetafactory.java#299).

`altMetafactory` lets us [pass in that value](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/lang/invoke/LambdaMetafactory.java#454) via `FLAG_SERIALIZABLE`. If neither functional interface nor the provided marker interfaces extend `j.io.Serializable`, that is [automatically added](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/lang/invoke/LambdaMetafactory.java#459) as an additional marker.

**Comment by retronym** [comment]
Needs a bit more work, will reopen early next week.

I'm trying to test this out with:

```
import java.io._
import java.{net, util}

import scala.reflect.internal.util.ScalaClassLoader.URLClassLoader
import scala.reflect.io.Streamable

class C {
  def serializeDeserialize[T <: AnyRef](obj: T) = {
    val buffer = new ByteArrayOutputStream
    val out = new ObjectOutputStream(buffer)
    out.writeObject(obj)
    val in = new ObjectInputStream(new ByteArrayInputStream(buffer.toByteArray))
    in.readObject.asInstanceOf[T]
  }

  serializeDeserialize((c: String) => c.length)

}

object Test {
  def main(args: Array[String]): Unit = {
    roundTrip
  }

  def roundTrip(): Unit = {
    val loaderCClass = classOf[C]
    val loader = getClass.getClassLoader.asInstanceOf[URLClassLoader]
    def deserializedInThrowawayClassloader = {
      val throwawayLoader: java.net.URLClassLoader = new java.net.URLClassLoader(loader.getURLs, ClassLoader.getSystemClassLoader) {
        val junk = Array.ofDim(32 * 1024 * 1024)
      }
      val clazz = throwawayLoader.loadClass("C")
      assert(clazz != loaderCClass)
      clazz.newInstance()
    }
    (1 to 100) foreach { _ =>
      deserializedInThrowawayClassloader
    }
  }

}

```

**Comment by lrytz** [comment]
Thanks for the explanation why we need to use `altMetafactory`, I didn't realize `javac` does the same: it switches to `altMetafactory` if the functional interface extends serializable. Looking at the code you linked, this is actually a requirement: if you use `metafactory` for a serializable functional interface, it [generates](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/lang/invoke/InnerClassLambdaMetafactory.java#301) `writeObject` and `readObject` methods that throw.

**Comment by lrytz** [comment]
LGTM!

**Comment by adriaanm** [comment]
:rocket:

**Comment by lrytz** [comment]
:white_check_mark:

**Pull request merged**
