### PR TITLE
Calling Set#map raises a warning about information loss

### PR DESCRIPTION
**Pull request by IDoCodingStuffs**

### CODE REVIEW

**Comment by IDoCodingStuffs** [comment]
PR in reference to #11580 as a showcase, not intended as an actual solution without member input https://github.com/scala/bug/issues/11580

**Review by eed3si9n — CHANGES_REQUESTED** [review]
`Set#map` should return `Set`.
https://github.com/scala/bug/issues/11580#issuecomment-503764285

**Comment by IDoCodingStuffs** [comment]
@eed3si9n Could be more elaborate there

**Comment by IDoCodingStuffs** [comment]
Warning generation stub added for review

**Review by IDoCodingStuffs — COMMENTED** [review]
Requested change (Set return) added

**Comment by SethTisue** [comment]
as per my comments on the linked bug ticket, I don't think this should be merged.

even if I did agree a warning was merited, this kind of thing should always be a compile-time warning, not a runtime warning.

**Comment by dwijnand** [comment]
Closing in favour of this being discussed in contributors.scala-lang.org first.  Pull requests that clarify this in the documentation would also be well received.

**Pull request closed without merging**
