### PR TITLE
Fixed an error in the documentation for MapLike

### PR DESCRIPTION
**Pull request by ConnorDoyle**
As this trait is part of scala.collection.immuable.Map, this should be fairly high priority.  Please pull this documentation fix.

### CODE REVIEW

**Comment by heathermiller** [comment]
Good catch, thanks for submitting a pull for this. LGTM.

**Comment by ConnorDoyle** [comment]
Does EPFL need a signed contributor agreement for this?

**Comment by heathermiller** [comment]
Technically, yes. We're currently working out a better, paperless (and less-annoying way) of dealing with CLAs, but yes, even corrections to the documentation should come with a CLA. All we need is the first and final page of the [CLA](http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf) emailed to danielle.chamberlain@epfl.ch. So, if you can fill it out digitally, or take a picture of it with your cellphone or something, that also works :)

**Comment by adriaanm** [comment]
@ConnorDoyle, please let us know here once you've sent in your CLA. 
I apologize for the overhead. We're working on a more lightweight process.

**Comment by ConnorDoyle** [comment]
Signed and sent to Danielle.  Sorry for the delay!

**Pull request merged**
