### PR TITLE
Allow renaming imports from _root_

### PR DESCRIPTION
**Pull request by som-snytt**
Allow `import _root_.{x => y}`

Fixes scala/bug#9125

### CODE REVIEW

**Review by dwijnand — CHANGES_REQUESTED** [review]
As Jasper [mentions](https://github.com/scala/bug/issues/9125#issuecomment-772348578) this guard exists due to https://github.com/scala/bug/issues/283 in 4e45e9e07b15c77bf9091574fd4c80f751e9e407 without a test case.  Could you add that test case now so we don't accidentally regress on that, please?

**Comment by som-snytt** [comment]
@dwijnand Do you mean `import _root_._` as opposed to `_root_.p`?

**Comment by dwijnand** [comment]
I'm not sure if it's just that or that + the use of a static method.  So just the test case as it is in the ticket, IMO.

**Comment by som-snytt** [comment]
It's charming how back then sometimes they used parens and sometimes not.

Fixing a 3-digit ticket is pretty cool, but adding a 3-digit test case is a close second.

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
@lrytz final review/merge?

**Comment by SethTisue** [comment]
@som-snytt is there anything in the spec about this?

**Comment by som-snytt** [comment]
Spec 9.4 doesn't mention the previous limitation.

**Review by lrytz — APPROVED** [review]

**Pull request merged**
