### PR TITLE
Topic/valclasses2

### PR DESCRIPTION
**Pull request by odersky**
SI-6035 and other value classes fixes.

I am sorry I must have messed up the git history of this commit to a degree where I can't fix it anymore. Rebasing seems to duplicate commits instead of organizing them. Rather than losing more time on this (I alreayd spent two fruitless hours) I ask that this is pulled exceptionally provided it passes the tests. Thank you.

Review by @adriaanm

### CODE REVIEW

**Comment by lrytz** [comment]
If the intermediate commits don't build anyway, we can squash everything into one - it's not such a big changeset after all. I can do it if people agree.

**Comment by adriaanm** [comment]
we're moving 2.10 development to a branch, so i can take care of that while i migrate all the critical outstanding pull reqs there

**Comment by paulp** [comment]
Alternately, I rebased these commits and pushed it here:

  https://github.com/paulp/scala/tree/topic/valclasses2

They can from there easily be combined or commits can be dropped via

  git rebase -i master

**Comment by adriaanm** [comment]
thanks! will work from there

**Comment by odersky** [comment]
On Wed, Jul 11, 2012 at 4:16 PM, Adriaan Moors <
reply@reply.github.com

> wrote:
> 
> thanks! will work from there

Thanks for your help! I'll try to keep history straight next time.
- Martin

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/scala/scala/pull/868#issuecomment-6907745

## 

Martin Odersky
Prof., EPFL http://www.epfl.ch and Chairman, Typesafehttp://www.typesafe.com
PSED, 1015 Lausanne, Switzerland
Tel. EPFL: +41 21 693 6863
Tel. Typesafe: +41 21 691 4967

**Comment by adriaanm** [comment]
moved to #878

**Pull request closed without merging**
