### PR TITLE
Faster build 2.10

### PR DESCRIPTION
**Pull request by adriaanm**
Backport of #3108 -- provide hooks for jenkins jobs to specify which repository to publish to.
Also, publish only what's needed during PR validation to save time.
Finally, we're standardizing on putting all our java properties in versions.properties and passing that around between the jenkins pr validation jobs, having them consumed by the scripts and dbuild. This way we can keep all module versions in synch and don't need to change infrastructure (much) when new properties are needed.

### CODE REVIEW

**Comment by adriaanm** [comment]
New-style PR validator: https://scala-webapps.epfl.ch/jenkins/view/stage-pr-scala/job/stage-pr-scala/4/

**Comment by adriaanm** [comment]
Review by @JamesIry

**Comment by JamesIry** [comment]
PR needs a description plz.

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
