### PR TITLE
SI-8428 Fix regression in iterator concatenation

### PR DESCRIPTION
**Pull request by retronym**
Regressed in e3ddb2d7, which introduced `ConcatIterator` to
avoid super-linear runtime on chains of concatenated iterators.

`ConcatIterator` maintains a queue of thunks for the remaining
iterators. Both `next` and `hasNext` delegate to `advance`, which
evaluates the thunks and discards any empty iterators from the
start of the queue. The first non-empty iterator is stored in
the var `current`.

It also overrides `++`, and creates a new `ConcatIterator` with
the given `that` as an extra element in the queue. However, it
failed to copy `current` across, which led to data loss.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm @Ichoran

**Comment by adriaanm** [comment]
LGTM.

**Comment by retronym** [comment]
I pushed a commit that cleans this up a little bit further.

**Comment by adriaanm** [comment]
LEvenBetterTM modulo whitespace

**Comment by retronym** [comment]
Fixed the superfluous whitespace / comment proximity and appeased MiMa.

**Comment by adriaanm** [comment]
Looks like mima is appeased over at #3645

**Comment by retronym** [comment]
Okay, I've updated the whitelist on the correct branch this time.

```
% (ant build-opt test.bc > /dev/null) && echo phew
phew
```

**Pull request merged**
