### PR TITLE
SI-7426 Crash in pickler.

### PR DESCRIPTION
**Pull request by paulp**
I wonder if the supply of copy-pasted code, and the bugs
which always accompany it, will ever run low. Here we have
a couple hundred lines of tree traversal which appears
roughly identical in structure to a different couple hundred
lines of tree traversal, except one calls methods called
putXXX and the other calls methods called writeXXX.

Except there was one call to writeXXX among all the putXXX
calls. Guess where it was crashing.

This entire file should be expunged.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @gkossakowski

**Comment by soc** [comment]
LGTM.

**Comment by gkossakowski** [comment]
Thanks @soc for the review. I'll run my own independently tomorrow.

**Comment by paulp** [comment]
@gkossakowski When is tomorrow scheduled for?

**Comment by gkossakowski** [comment]
LGTM.

It took me a while to understand the root cause of the problem so I'll include my findings here.

In Pickler, we have two phases: Phase 1 which collects unique entries we want to write and Phase 2 where actual writing happens. The problem was that we tried to write some information at Phase 1 and then assertion was failing.

**Comment by gkossakowski** [comment]
@paulp: good timing, I was just reviewing this PR.

Sorry for all those delays. My schedule is very unpredictable these days. I thought 3 days ago that I got all of my issues sorted out but I didn't. I'll continue with my review queue tomorrow (for real or I'll be owing you lots of cappuccinos).

**Pull request merged**
