### PR TITLE
SI-9027 Backport xml parser fix

### PR DESCRIPTION
**Pull request by som-snytt**
Fingers crossed, I have no local java 6 here to test.

No test because no q"" on 2.10.

This is backport of #4185.

### CODE REVIEW

**Comment by som-snytt** [comment]
The test failure is whatever is in IDE's head at the moment.

FTR, I did download java 6, thanks to Ubuntu I didn't have to sign in to Oracle's vault, and ran the build in the background.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
Let's give IDE validation another try.

**Comment by gkossakowski** [comment]
The failure is persistent. I pinged IDE team to look at it. I think we can merge it but I'll ask @adriaanm for second pair of eyeballs.

**Comment by adriaanm** [comment]
LGTM

**Comment by som-snytt** [comment]
Technically, a third pair of eyeballs.

I'm such a tool, I'm uncomfortable if I can't trust my tool to tell me if something is fishy.

**Comment by ajozwik** [comment]
When will  the 2.10.5 be delivered?

**Comment by adriaanm** [comment]
2.10.5 (the last 2.10.x release) will be out by the end of Q1 of 2015, after 2.11.5 and 2.12.0-M1 are out. (We try to keep the overview at https://github.com/scala/scala/milestones up to date.)

**Comment by ajozwik** [comment]
sbt uses 2.10.4 - and it needs `xml parser fix`. Thank you for quick response.
See https://github.com/sbt/sbt/pull/1765

**Pull request merged**
