### PR TITLE
Cleaned up Duration for the standard library.

### PR DESCRIPTION
**Pull request by vjovanov**
- Removed Timeout from the library. Each library should provide its own implementation of Timeout
- Removed duration package object and replaced it with regular object
- Removed usages of post Java 1.5 TimeUnit members
- Added factory methods for FiniteDuration
- Cleaned up some unnecessary comments
- Merged duration DSL with Duration.scala file

### CODE REVIEW

**Comment by paulp** [comment]
Well, it turns out this is even worse, because the file and the class it generates are the same name with different case.  Build failure ensues.  Sorry that the tools are less than forgiving on this matter.  I'm not sure what to do, but I can't merge this.

05:24:51  [scalacfork] warning: Class scala.concurrent.util.duration not found - continuing with a stub.
05:24:51  [scalacfork] error: error while loading Duration, class file '/Users/paulp/.jenkins/workspace/scala-ant-clean-test/build/quick/classes/library/scala/concurrent/util/Duration.class' contains wrong class scala.concurrent.util.duration
05:24:51  [scalacfork] one warning found
05:24:51  [scalacfork] one error found
05:24:51  
05:24:51  BUILD FAILED
05:24:51  /Users/paulp/.jenkins/workspace/scala-ant-clean-test/build.xml:658: Compilation failed because of an internal compiler error; see the error output for details.

**Comment by vjovanov** [comment]
Sorry, I could not anticipate that as my ant tests were passing and I do not have a Jenkins handy. The only way to fix this issue is unfortunately to rename the class.

**Comment by paulp** [comment]
Don't worry, I didn't see it coming either, at least not from two directions. Actually, can you try constructing it with one commit which completely removes the duration file, and then a succeeding one which adds it back in with the right capitalization in file and class? It seems like it should work.

**Comment by vjovanov** [comment]
It is already done in this pull request. I did not separate it in two commits since the lowercase `duration` did not exist before so I guess it is OK to add it in just one commit.

**Pull request merged**
