### PR TITLE
Two fixes for the worksheet instrumenter

### PR DESCRIPTION
**Pull request by dragos**
This is Martin's fix for the worksheet, I'm just the messenger. I guess I can't be my own reviewer, so let's say review by @rytz.

(1) Handle empty worksheets
(2) Handle for expressions

Review by @dragos
(cherry picked from commit 20dc9cd7848863097b07d1cb84ae3f729f7e94da)

### CODE REVIEW

**Comment by jsuereth** [comment]
review by @lrytz

**Comment by lrytz** [comment]
What branch does 20dc9cd live in?

Should this really go in 2.10.x, or in 2.9.x, or both?

**Comment by dragos** [comment]
I cherry-picked it from Martin's repo, but I had to make a small change to fix the build.

It should go in both 2.10.x and 2.9.x

**Comment by lrytz** [comment]
LGTM

**Comment by jsuereth** [comment]
@dragos are you planning to open another pull request for 2.9?

**Comment by dragos** [comment]
Yes, I will shortly.

**Pull request merged**
