### PR TITLE
SI-7100 Fixed infinite recursion in duplicators

### PR DESCRIPTION
**Pull request by VladUreche**
Hopefully this simple fix will do...

Review by @JamesIry

### CODE REVIEW

**Comment by JamesIry** [comment]
LGTM, let's see what the kitteh says.

**Comment by JamesIry** [comment]
BUILDLOG?

**Comment by adriaanm** [comment]
https://api.github.com/repos/scala/scala/statuses/a53e1508660f849e86e34808e5d4230b078f7a3e says the pr-checkin job just finished at https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/373/

**Comment by adriaanm** [comment]
the kitten only wakes up evert 15 min, so you should see this baby go green soon

**Pull request merged**
