### PR TITLE
Fix encoding to show euro-sign of doc-source-url option correctly.

### PR DESCRIPTION
**Pull request by pocket7878**
Very little fix for [SI-8699](https://issues.scala-lang.org/browse/SI-8699).

review @vladureche

### CODE REVIEW

**Comment by VladUreche** [comment]
LGTM! Thanks for your contribution @pocket7878! Please sign the [Scala/Typesafe CLA](http://typesafe.com/contribute/cla/scala) so I can merge your commits into the code base.

Also, I think the explanation would benefit from a bit of rewriting to clarify it:

```
A URL pattern used to link to the source file; the following variables are available: €{TPL_NAME}, €{TPL_OWNER} and respectively €{FILE_PATH}. For example, for `scala.collection.Seq`, the variables will be expanded to `Seq`, `scala.collection` and respectively `scala/collection/Seq` (without the backquotes).
```

WDYT?

**Comment by pocket7878** [comment]
I think so too.
I'll update explanation.

**Comment by VladUreche** [comment]
By the way, we should also mention that `-sourcepath` should be set to obtain a relative path in the `€{FILE_PATH}` variable:

```
A URL pattern used to link to the source file; the following variables are available: €{TPL_NAME}, €{TPL_OWNER} and respectively €{FILE_PATH}. For example, for `scala.collection.Seq`, the variables will be expanded to `Seq`, `scala.collection` and respectively `scala/collection/Seq` (without the backquotes). To obtain a relative path for €{FILE_PATH} instead of an absolute one, use the ${settings.sourcepath.name} setting.
```

**Comment by pocket7878** [comment]
I updated explanation text. and signed CLA.

**Comment by VladUreche** [comment]
Once this is fixed, I the PR is ripe for merging! :+1:

**Comment by pocket7878** [comment]
I just updated to use string interpolation. Sorry for my misunderstanding.

**Comment by VladUreche** [comment]
Nice work @pocket7878! Thanks!

**Pull request merged**
