### PR TITLE
[backport] SI-10071 SI-8786 varargs methods

### PR DESCRIPTION
**Pull request by adriaanm**
Backport of the fix in #5556 as well as relevant earlier work in #5262 (which refactors the relevant code parts in UnCurry, backported as de361df). 

This PR rebases and slightly reworks @dragos's original backport in #5557 (to make testing work on java 6 and up).

### CODE REVIEW

**Comment by adriaanm** [comment]
Hrm, spurious failure we've been seeing more recently: `!!  496 - run/reflection-mem-typecheck.scala        [output differs]`

**Comment by SethTisue** [comment]
> Hrm, spurious failure we've been seeing more recently: !! 496 - run/reflection-mem-typecheck.scala [output differs]

note that on the 2.12.x branch we already nixed that test (in #5480)

**Comment by adriaanm** [comment]
Ah yes, thanks for the reminder!

**Comment by adriaanm** [comment]
/nothingtoseehere -- the earlier failure was in a flaky test that is no longer

**Comment by adriaanm** [comment]
weird, a timeout in scaladoc

**Comment by adriaanm** [comment]
Weird. Scaladoc hung until the job was aborted again. Could it be because of the info transform changes of 5b972dc?

**Comment by adriaanm** [comment]
Ok, all seems well.

**Pull request merged**
