### PR TITLE
SI-7515 Emit final in bytecode for final inner classes.

### PR DESCRIPTION
**Pull request by retronym**
As we did before a regression in 18efdedfb / SI-5676.

This commit tightens up the condition in which the FINAL
modifier is ommitted; it now _only_ does this for the module
classes of nested objects.

Review by @JamesIry

### CODE REVIEW

**Comment by retronym** [comment]
Submitting against 2.10.x; this was a regression from 2.9.2 to 2.10.0, so it would be nice to deliver the fix in 2.10.3.

**Comment by JamesIry** [comment]
I think this will be LGTM, but I want to make triple sure we're not concerned about binary compatibility issues. 

In particular this does create a binary incompatibility but one that will never be seen by people writing Scala. But what about people writing Java, could they have extended a final inner class that was missing the final attribute in its classfile? Do we care?

@adriaanm, @paulp, thoughts?

**Comment by soc** [comment]
If we ever cared about usage from Java, we wouldn't have `sealed` ...

**Comment by paulp** [comment]
@soc sealed is a compile-time feature which can't be enforced from java. This has literally zero bearing on how to assess binary-incompatible changes which can be observed from java.

**Comment by paulp** [comment]
It is abundantly non-obvious how this PR relates to SI-7515. Oh, it's SI-7151.

**Comment by paulp** [comment]
I am against a change like this which impacts binary compatibility, especially in the absence of any compelling motivation. If we were generating final too frequently, that would be one thing; it is harder to break things by relaxing restrictions than by tightening them. I think this should be master only.

**Comment by retronym** [comment]
Reopened against master as #2635. And fixed my JIRA dyslexia to boot.

**Pull request closed without merging**
