### PR TITLE
Deprecate #> of ProcessBuilder for Dotty compatibility

### PR DESCRIPTION
**Pull request by exoego**
Addresses https://github.com/scala/bug/issues/11133

I tried to refer the [Ammonite](http://ammonite.io) design, but could not find good resources (Any help is highly appreciated).
So I tried to alias based on their behaviors and use cases.

### CODE REVIEW

**Comment by NthPortal** [comment]
(vaguely related: can we deprecate the implicit conversion from `String` to `ProcessBuilder` while we're at it?)

**Comment by exoego** [comment]
@NthPortal
I prefer the explicitly calling extension method like`"cmd".toProcessBuilder.run` rather than the implicit conversion `"cmd".run`, as same as `JavaConverters` rather than `JavaConversions`.

If there is the design direction in Scala to recommend extension methods over implicit conversion, I will open a separate PR.

**Comment by SethTisue** [comment]
> I prefer the explicitly calling extension method like`"cmd".toProcessBuilder.run`

Might well as be `ProcessBuilder("cmd").run`, IMO. I think a separate PR deprecating the extension methods would have a chance.

**Comment by exoego** [comment]
@NthPortal @SethTisue 
question: What is a motivation to deprecate the implicit conversion `String => ProcessBuilder` ?

**Comment by NthPortal** [comment]
@exoego because the conversion is silly. you shouldn't be able to execute a string

**Comment by SethTisue** [comment]
@exoego it's kind of a big question, bigger this than PR. I'd suggest we have that discussion on either a new PR or a new https://contributors.scala-lang.org thread

**Comment by SethTisue** [comment]
I have doubts about this PR. I'll comment on https://github.com/scala/bug/issues/11133

**Comment by exoego** [comment]
@SethTisue 
I minimized this PR scope.
Now it deprecates only `#>` and add `ovewrite` alias, Dotty/Scala 3 compatibility in mind.

**Comment by lrytz** [comment]
I also think this change is not necessary (https://github.com/scala/bug/issues/11133#issuecomment-433932810).

**Comment by SethTisue** [comment]
`#>` in Dotty is just a proposal for now, and anyway 
https://github.com/scala/bug/issues/11133#issuecomment-433964922 , so I'm just going to close this. sorry @exoego! your PR helped us achieve more clarity on this, anyway

in other sys.process news, https://twitter.com/li_haoyi/status/1059650646616363008

**Pull request closed without merging**
