### PR TITLE
Fix `-release` on JDK 17 by updating optimizer class path

### LINKED ISSUE #12612: Inliner crash on Java 17 when using `-release`
```scala
object crash {
  def main(args: Array[String]): Unit = {
    val algo = "HmacSHA1"
    val charset = java.nio.charset.StandardCharsets.UTF_8
    val key = "totally secret key".getBytes(charset)
    val value = "totally real value".getBytes(charset)

    val mac = javax.crypto.Mac.getInstance(algo)
    mac.init(new javax.crypto.spec.SecretKeySpec(key, algo))
    val macced = mac.doFinal(value)

    println(new String(macced, charset))
  }
}
```

```
➜ sandbox sc -release 11 -opt:l:inline -opt-inline-from:'**' Test.scala
error: java.lang.IndexOutOfBoundsException
	at scala.tools.asm.tree.InsnList.get(InsnList.java:94)
```

Reported on https://users.scala-lang.org/t/solved-indexoutofboundsexception-in-scala-2-13-8-inliner/8583/4

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12612

This was nominally a follow-up to https://github.com/scala/scala/pull/10056 and https://github.com/scala/scala/pull/10059

The `IOOBE` grew very familiar. The reason `pos/t3420` failed was inlining `Integer.valueOf` to box the ints in `Map(1 -> 2)`.

### CODE REVIEW

**Comment by SethTisue** [comment]
@som-snytt 

>   val optDev          = "realeasy"     / "make life real easy for dev"  --?

mind providing a better description here? otherwise, looks mergeable

EDIT: "mergeable" sounds like damning with faint praise. no, not just mergeable. this is a PR that Scala 2 will clasp close to its heart forever.

**Review by SethTisue — CHANGES_REQUESTED** [review]
`realeasy` flag needs proper description

**Comment by som-snytt** [comment]
I forgot what it does. Sample:
```
sbt:root> partest --neg --realeasy
Partest version:     2.13.11-20221027-092700-e5606e6
...
Extraneous file: /home/amarki/projects/scala/test/files/neg/fool.check
Selected 1271 tests drawn from 1 named test categories
# starting 1271 tests in neg
ok    3 - neg/abstract-class-error
...
ok    8 - neg/abstraction-from-volatile-type-error.scala
!!    9 - neg/abstract.scala                        [output differs]
ok   10 - neg/accesses2.scala
...
!!   39 - neg/choices.scala                         [output differs]
...
!!  245 - neg/partestInvalidFlag.scala              [output differs]
...
ok 1272 - neg/warn-unused-privates.scala
# 1268/1272 passed, 4 failed in neg
# Failed test paths (this command will update checkfiles)
partest --update-check \
  /home/amarki/projects/scala/test/files/neg/abstract.scala \
  /home/amarki/projects/scala/test/files/neg/choices.scala \
  /home/amarki/projects/scala/test/files/neg/partestInvalidFlag.scala \
  /home/amarki/projects/scala/test/files/neg/spinner.scala
# There are uncommitted check files!
test/files/neg/abstract.check
test/files/neg/fool.check
[error] Failed: Total 1272, Failed 4, Errors 0, Passed 1268
[error] Failed tests:
[error]         partest
[error] (test / IntegrationTest / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 41 s, completed Oct 27, 2022, 2:45:12 AM
```
Shows the existing "Extraneous file" check at top, for legacy flags and check files that don't have a test file.

A couple of tests check options and fail when extra options supplied.

"uncommitted check files" shows test edit to abstract.check that failed that test.

Shows sample neg/spinner.scala failing because it uses Thread.onSpinWait.

```
sbt:root> partest --help
Usage: partest [options] [test test ...]

  Test categories:
    pos          run compilation tests (success)
...
  Other options:
    realeasy     real easy way to test --release 8 and check uncommitted checks
    version      show Scala version and exit
    help         show this page and exit

```

**Comment by som-snytt** [comment]
It would be nice if GitHub showed both create and update times for commits. I did not create the first commit an hour ago, it was a month ago, and that's why I don't remember it.

Stop gaslighting me!

**Comment by SethTisue** [comment]
I keep reading "realeasy" as "release-y"

**Comment by som-snytt** [comment]
That is the excellent pun. I'm pleased it didn't go unappreciated.

**Comment by som-snytt** [comment]
If I had this feature today, it would tell me I deleted a check file but not committed.

The requested change is up for review.

**Comment by som-snytt** [comment]
Woo-hoo I'm going to check out a branch and take it for a spin.

**Pull request merged**
