### PR TITLE
Remove -deprecation from partest default options.

### PR DESCRIPTION
**Pull request by paulp**
Who knows why it was ever like this; it's not like anyone
sees the deprecation warnings. In PR #1807 there is now a
test which depends on partest not making this move, so it's
a good time to finally expunge it.

### CODE REVIEW

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by som-snytt** [comment]
To employ a seasonal phrase, Hallelujah.  I remembered writing:

./neg/t5663-badwarneq.scala:/\* It's not possible to run partest without -deprecation.

Though I don't really follow the rest of the comment...
- Since detecting the warnings requires a neg test with
- -Xfatal-warnings, and deprecation terminates the compile,
- we'll just comment out the nasty part.  The point was
- just to show there's nothing special about a trait
- that extends a case class, which is only permitted
- (deprecatingly) by omitting the parens.

**Comment by xeno-by** [comment]
lgtm

**Comment by xeno-by** [comment]
Btw my test does depend on this behavior of partest, but I just updated the flags to include `-deprecation`.

**Comment by som-snytt** [comment]
BTW, the residual issue with partest is that pos doesn't use check; a compile must fail to compare a check file.  That's why my recent change made "info" output (-Xshow-phases) a failure.  Yes, I hail from the country of Klooj.

**Comment by paulp** [comment]
I believe the number of places there is reason to check "pos" output is acceptably small.

**Pull request merged**
