### PR TITLE
 Ensure display order of note tags and others matches source definition

### PR DESCRIPTION
**Pull request by janekdb**
Fixes scala/bug#10325

### CODE REVIEW

**Comment by Philippus** [comment]
there's a failing test in `test/scalacheck/scala/tools/nsc/scaladoc/HtmlFactoryTest.scala`, see https://github.com/scala/scala/pull/6095 :)

**Comment by janekdb** [comment]
Thanks @Philippus. Your update to `HtmlFactoryTest` is incorporated. This PR is now a strict superset of https://github.com/scala/scala/pull/6095.

**Comment by Philippus** [comment]
LGTM! I've closed my PR.

**Comment by janekdb** [comment]
Thanks @Philippus

**Comment by Atry** [comment]
LGTM! This PR makes [example.scala](https://static.javadoc.io/com.thoughtworks.example/unidoc_2.12/2.0.0/com/thoughtworks/example.html) more usable! Thank you!

**Review by Atry — APPROVED** [review]

**Review by lrytz — APPROVED** [review]

**Pull request merged**
