### PR TITLE
Color REPL under -Dscala.color

### PR DESCRIPTION
**Pull request by puffnfresh**
We already use -Dscala.color when using -Ytyper-debug

This tries to reuse the colors chosen from the debug flag:
- Bold blue for vals (e.g. "res0")
- Bold green for types (e.g. "Int")
- Magenta for the shell prompt (e.g. "scala>")

### CODE REVIEW

**Comment by retronym** [comment]
Looks like a flakey test in the scala-refactoring suite.

```
Results :

Failed tests: 
  ReusingPrinterTest.add_override_final_flags_to_lazy_val:138 expected:<...T extends T {
      [override final ]lazy val meth = 0
  ...> but was:<...T extends T {
      []lazy val meth = 0
  ...>
```

PLS REBUILD ALL

**Comment by retronym** [comment]
This change fulfils part I of https://issues.scala-lang.org/browse/SI-4223.

**Comment by retronym** [comment]
It is probably worthwhile to discuss what we would need to do to turn this on by default in the REPL.

To avoid the effecting tools that programatically drive the REPL, we could predicate it based on a suitable terminal environment:

``` scala
scala> new jline.console.ConsoleReader().getTerminal.isAnsiSupported
res3: Boolean = true
```

We could also have a system property to turn it off explicitly.

Maybe we'd target this change at 2.12 both to be conservative and to give the feature (and the colour pallette) some time to mature.

**Comment by retronym** [comment]
I think you might have missed a spot.

image

**Comment by puffnfresh** [comment]
@retronym I did, thank you.

**Comment by adriaanm** [comment]
Cool, more flair for the REPL! What's the status of the missed spot?

**Comment by gkossakowski** [comment]
Given missing activity, rescheduling for 2.11.4 (to happen at the end of November).

**Comment by puffnfresh** [comment]
I'm happy to work on this tonight, if that's not too late to get into this release.

**Comment by gkossakowski** [comment]
Hi @puffnfresh!
We are blocked by https://issues.scala-lang.org/browse/SI-8890 for which fix should arrive tomorrow. Let's give this PR another try, then. However, if you or us will feel tomorrow that this didn't have enough of time to fully bake, we'll reschedule it for 2.11.4, ok?

**Comment by puffnfresh** [comment]
@gkossakowski sounds great :+1:

**Comment by puffnfresh** [comment]
@gkossakowski good to go:

screen shot 2014-10-07 at 9 16 23 pm

**Comment by retronym** [comment]
How does it look on a light black-on-white themed terminal?

**Comment by puffnfresh** [comment]
@retronym as far as I know, most terminals choose colours which work on black or white. You be the judge, though:

screen shot 2014-10-07 at 9 21 16 pm

**Comment by retronym** [comment]
That looks good enough for now. If we turn it on by default in 2.12, we can polish that a little further. Thanks!

**Comment by puffnfresh** [comment]
Yeah, I'm hoping for a tiny amount of data before the bike shedding starts.

**Comment by jrudolph** [comment]
Yay, nice idea. :+1:

**Comment by jrudolph** [comment]
FTR: here's how to enable it automatically in sbt:

Put this into your `~/.sbt/0.13/user.sbt`:

``` scala
initialize ~= { _ =>
  val ansi = System.getProperty("sbt.log.noformat", "false") != "true"
  if (ansi) System.setProperty("scala.color", "true")
}
```

**Comment by jozic** [comment]
@jrudolph :+1:

**Comment by retronym** [comment]
I would suggest to predicate this on `sbt.ConsoleLogger.formatEnabled`, which [incorporates](https://github.com/sbt/sbt/blob/v0.13.6/util/log/src/main/scala/sbt/ConsoleLogger.scala#L75-L89) the checks for the system property `sbt.nologformat` and the capabilities of the terminal.

```
% sbt "eval sbt.ConsoleLogger.formatEnabled"
[info] Loading global plugins from /Users/jason/.sbt/0.13/plugins
[info] Set current project to scala (in build file:/Users/jason/code/scala/)
[info] ans: Boolean = true

% sbt -Dsbt.log.noformat=true "eval sbt.ConsoleLogger.formatEnabled"
[info] Loading global plugins from /Users/jason/.sbt/0.13/plugins
[info] Set current project to scala (in build file:/Users/jason/code/scala/)
[info] ans: Boolean = false
```

**Comment by lihaoyi** [comment]
Was this announced anywhere? This is probably the biggest improvement to the Scala REPL since the great war of 1939

**Comment by adriaanm** [comment]
;-) i believe it was included in forSome release notes, but happy to tout it again (handwritten.md over at scala/make-release-notes)

**Comment by lihaoyi** [comment]
Wherever you put it, Google can't find it, because I've googled this and clicked-through the JIRA ticket at least 5 times by this point =P

screenshot 2015-02-02 17 46 39

**Comment by som-snytt** [comment]
Typelevel Scala improvements are merged seamlessly upstream without fanfare. Nobody even blinks.

https://github.com/typelevel/scala/pull/63

I'd probably take issue so to speak with the notion that this improvement beats the `:slice bread` command.

**Comment by xring** [comment]
thank u~

**Pull request merged**
