### PR TITLE
SI-9068 Deprecate scala.collection.mutable.Stack

### PR DESCRIPTION
**Pull request by szeiger**
JIRA: [SI-9068](https://issues.scala-lang.org/browse/SI-9068)

### CODE REVIEW

**Comment by sjrd** [comment]
Can we fix it instead? E.g., using an `Array[AnyRef]` + `size` inside?

**Comment by chris-martin** [comment]
Jira link: [SI-9068](https://issues.scala-lang.org/browse/SI-9068)

**Comment by szeiger** [comment]
Updated `serialization-new.check` to accomodate the new deprecation warning. I was unable to produce the other test failures locally. Let's see what happens on the next build...

**Comment by lrytz** [comment]
> Can we fix it instead

not in 2.12, this should be part of a collections rework

**Comment by lrytz** [comment]
i agree though that it's not great to deprecate it without an alternative (other than a var over a list), it does make code harder to read at times. there are also a few uses within the compiler.

**Comment by SethTisue** [comment]
fyi @xuwei-k who tweeted a bad mutable.Stack bug recently

**Comment by szeiger** [comment]
rebased

**Comment by SethTisue** [comment]
LGTM

**Pull request merged**
