### PR TITLE
Change Scala license to unmodified 3-clause BSD.

### PR DESCRIPTION
**Pull request by adriaanm**
No longer using the slightly reworded 3-clause BSD license.
This does not change the meaning of the license,
just aligns it with the standard wording.

### CODE REVIEW

**Comment by gkossakowski** [comment]
@adriaanm: do I understand correctly that all decisions has been made and this should be merged?

**Comment by heathermiller** [comment]
Not sure

**Comment by xeno-by** [comment]
@gkossakowski I would say this needs a proper discussion first

**Comment by gkossakowski** [comment]
@xeno-by: I wasn't in the loop when it comes to license stuff so I'll let @adriaanm elaborate on it. I agree that licensing and copyright situation should be clarified with everybody working on Scala project.

**Comment by adriaanm** [comment]
Besides Typesafe's copyright, is there anything that needs to be discussed/clarified? It's just a re-alignment with the standard wording of the BSD license, instead of the old wording, which was improperly copy/pasted (and erroneously modified) from an older version of the same BSD license (e.g., it refers to the "regents" instead of the actual copyright holders).

I think Typesafe's copyright was part of the deal when Typesafe was founded and covers @odersky's work (on Scala 2.9) as a Typesafe co-founder.

**Comment by xeno-by** [comment]
1) The change to the license is indeed miniscule and looks okay to my untrained eye except for a couple copy/paste issues: a) "Neither the name of the EPFL nor the names of its contributors". Should this also mention Typesafe taking into account the proposed copyright change? b) "IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE". Why is the "copyright owner" singular?

I would also like to learn more about what the mentioned deal consists in, and what it entails for Scala contributors. 

2) Is there any information about it? For example, were the changes to Scala's copyright that it brings discussed on the mailing lists (public ones or LAMP ones)?

3) What about the old formulation used on the scaladoc website for quite a while: "Scala programming documentation. Copyright (c) 2003-2013 EPFL, with contributions from Typesafe"? Does it reflect the state of things well? Are there plans to change it too?

4) What does the new formulation cover? Is it only @odersky's work or also the work of @odersky's employees at LAMP? Should that be reflected in the copyright?

5) Given that the deal was established two years ago, why wasn't it codified back then?

6) How does retroactive copyright work? Will LAMP's and/or community's contributions from 2011 and onwards become counted as intellectual property of Typesafe?

7) In general, what does it mean for two entities to concurrently hold copyright? Are there any peculiarities to this in our case? 

Since it looks like there's quite a number of details to figure out about the copyright change, I think the matter at hand would benefit from more eyes looking at it. Therefore I propose that we: 1) start a discussion on scala-internals, as well as 2) highlight this particular change as a dedicated discussion point on the next core meeting

**Comment by adriaanm** [comment]
IANAL, so I can't answer your questions, sorry.

This is why we're using the standard BSD license. This is all taken
verbatim from http://opensource.org/licenses/BSD-3-Clause

You can have various authors (who retain their copyright) and and
organization that holds the license.
When you sign the CLA, you effective license your work to the "copyright
holder" organization (EPFL), who can do pretty much whatever they want with
it (including relicense).

**Comment by adriaanm** [comment]
I removed Typesafe's copyright line pending clarification.
I fully expect it to come back, as I think it's the right thing to do.
We'll take all the time needed to make everyone comfortable with this change before even submitting a PR.

I think it is urgent to clean up our license, so let's merge this PR first, and have a separate discussion about the Typesafe copyright.

**Comment by gkossakowski** [comment]
@xeno-by, @heathermiller: could you guys look at it and check if everything looks fine to you?

I looked at the diff and it looks good to me.

**Comment by gkossakowski** [comment]
@xeno-by, @heathermiller: ping.

**Comment by heathermiller** [comment]
Lgtm

**Comment by gkossakowski** [comment]
Thanks.

**Pull request merged**
