### PR TITLE
Optimize matching on tuples

### PR DESCRIPTION
**Pull request by adriaanm**
```
(e1,...,eN) match {
  case (p1, ..., pN) if g =>
  ...
  case (q1, ..., qN) if g' =>
  case _ if g'' =>
}
```

is compiled by introducing the prelude

```
val x1 = e1
...
val xN = eN
```

and then referring directly to the `xi` that corresponding to the `i`th subpattern,
in the translation of the match, rather than selecting the `_i` component of the tuple.

This eliminates the allocation of the tuple and the indirection of accessing its fields.

review by @paulp

### CODE REVIEW

**Comment by ijuma** [comment]
Nice optimisation.

**Comment by SethTisue** [comment]
applause

**Comment by adriaanm** [comment]
Part of this PR needs rethinking. Especially the CSE optimization, which was never my favorite.
It'll re-emerge soon on a master branch near you.

Thanks for the review, @paulp

**Comment by viktorklang** [comment]
Nice one Adriaan!

**Comment by siriux** [comment]
Hi,

I find this optimization really useful. 
Do you think it will be available on 2.10.x at some point? Or we will have to wait for 2.11

Thanks

**Comment by adriaanm** [comment]
Sorry, this will only be available on 2.11 initially. We do consider backports on a support-basis.

**Comment by siriux** [comment]
Thanks for your anwser

**Pull request closed without merging**
