### PR TITLE
Topic/unresolved overloads

### PR DESCRIPTION
**Pull request by paulp**
Specialization and overloaded types.  Review by @axel22

### CODE REVIEW

**Comment by paulp** [comment]
Since I realize this is not a tiny patch, another answer we would accept is "review by @retronym".  Hey, we're not choosy, we'll take anyone.

**Comment by paulp** [comment]
Also, this might be a good patch at which to remind people that appending '?w=1' to the url causes it to ignore whitespace changes.  We should probably do something about the fact that half of us add new trailing whitespace on every checkin and half of us remove it.

**Comment by retronym** [comment]
Here's one:

``` scala
trait LoadedOver[@specialized(Int) A] {
  def foo(x: Any): A
  def foo(xs: String): A
}

object Test {
  def loaded: AnyRef with LoadedOver[Int] = sys.error("")
  loaded.foo("")
}
```

This fails in Cleanup transforming an `ApplyDynamic` tree -- it would be interesting to track down where that comes from.

**Comment by retronym** [comment]
> it would be interesting to track down where that comes from.

https://github.com/scala/scala/blob/v2.10.0-M7/src/compiler/scala/tools/nsc/transform/Erasure.scala#L1002

**Comment by paulp** [comment]
If you can bring yourself to give me a "lgtm" I'll send another pull request today on these other points, @retronym .

**Comment by retronym** [comment]
lgtm it is then.

**Pull request merged**
