### PR TITLE
SI-8514 NumericRange[Double] take and drop are broken

### PR DESCRIPTION
**Pull request by Ichoran**
Fixes SI-8514, plus regressions associated with fix of SI-4370, plus other regressions from earlier commits regarding floating-point ranges.  This fixes only Double; Float is still broken.  Jumped through all sorts of hoops to (try to) preserve binary compatibility--this should be redone for 2.12.

### CODE REVIEW

**Comment by darabos** [comment]
It seems to me it does not fix SI-8514 for numbers that cannot be accurately represented in decimal.

scala> (0.0 to 100.0 by (1.0 / 3.0)).take(16).length
res0: Int = 15

**Comment by Ichoran** [comment]
@darabos - You seem to be right, and what's more Martin Odersky has indicated that he's inclined to deprecate the whole thing instead of trying to make a dubious action (getting correct numbers of steps) work for enough cases.  Do you have a compelling use case for these?  One of his arguments was that people in practice just don't use this.  (I know I've always shied away from them because I expected them to break.)

**Comment by darabos** [comment]
Deprecation sounds great to me!

**Comment by retronym** [comment]
Closing this one for now given the build failure, ongoing discussion and the imminent need to retarget this to the `2.11.x` branch as `master` is not long for this world.

**Comment by Ichoran** [comment]
Sorry, should have done it myself.  I think we're going for deprecation rather than a best-effort fix (still need to verify with you/Adriaan/whoever).

**Comment by adriaanm** [comment]
I'm in favor of deprecation. If a ton of users complain, we can un-deprecate and fix, but that seems unlikely.

**Pull request closed without merging**
