### PR TITLE
SI-6539 moves @compileTimeOnly away from scala-reflect

### PR DESCRIPTION
**Pull request by xeno-by**
The move is done to provide forward compatibility with 2.10.0.

The annotation isn't replaced with one of the macro-based solutions
right away (see comments for more information about those), because
we lack necessary tech in 2.10.x.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym @harrah

**Comment by retronym** [comment]
How about we just move it to `scala.reflect.internal`? That package is nothing close to forward binary compatible.

```
 git diff v2.10.0 -- src/reflect/scala/reflect/internal/ | grep '\+.*def' | wc -l
      57
```

**Comment by xeno-by** [comment]
Sounds good and doesn't require people to reference scala-compiler.jar. Any objections? @adriaanm @gkossakowski

**Comment by harrah** [comment]
Not sure the API comments need the added discussion of what might replace it.  Looks good otherwise.

**Comment by adriaanm** [comment]
as soon as scala-reflect stops being forward compatible, we're in trouble because of transitive dependencies
so, either all of scala 2.10.1 is forward compatible or none of it is

**Comment by retronym** [comment]
Can you elaborate? The `.internal` subpackage sort of off-limits for userland code; we should only need to support calls from within scala-reflect.jar.

**Comment by adriaanm** [comment]
i may have spoken too soon -- if code emitted by reify does not reference these additions to .internal, we're ok i guess

**Comment by xeno-by** [comment]
updated as discussed

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
I'll assume this is a spurious failure. PLS REBUILD ALL

**Comment by xeno-by** [comment]
@retronym Does this look good to you now?

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
yep, lgtm.

**Pull request merged**
