### PR TITLE
SI-8386 showCode fails to pretty print application to assign

### PR DESCRIPTION
**Pull request by VladimirNik**
1) Fix for SI-8386.
2) Tests for attributed trees are restored.

### CODE REVIEW

**Comment by VladimirNik** [comment]
Review by @densh

**Comment by densh** [comment]
@VladimirNik, it looks like tests are still commented out. Is it a bug or a feature?

**Comment by VladimirNik** [comment]
@densh, fixed, tests are uncommented.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
