### PR TITLE
SI-8125 SI-8130 position fixes for presentation compiler

### PR DESCRIPTION
**Pull request by dotta**
review by @retronym

@danchia This PR should make you happy ;-)

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

But additional review, please, by @dragos, last seen in the vicinity of this code: 3415436b67ae7889a11ce2537576ca49b328aecc

**Comment by dragos** [comment]
Looks like the test I added back then has failed...

**Comment by dotta** [comment]
@dragos All the failures seem "expected", and the fix should be as simple as updating the tests with a transparent position (instead of an opaque one) for syntehtic `apply`. I'm going to do so now.

EDIT: Actually, while what I said above holds for the test `t5064.scala`, it may be not true for the other two applyDynamic tests. I'll have to understand why my change affects the position of applyDinamic Trees.

EDIT2: Alright, the reason why the applyDynamic tests fail is that there is another bug (https://issues.scala-lang.org/browse/SI-8130). It's easy to fix, and since the fix in this PR for SI-8125 requires SI-8130 to be fixed as well, I'm going to restructure this PR to contain a fix for both tickets. Hopefully, that's ok.

**Comment by dotta** [comment]
There is a failing test now in scala-refactoring, I'm looking at it.

**Comment by dotta** [comment]
PLS REBUILD/pr-scala@82852d9

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by dotta** [comment]
@retronym this won't work until 

1) https://github.com/scala/scala/pull/3358 is merged in 2.10.x, and 2.10.x is merged into master.
2) At that point I need to update the Scala IDE codebase to use the new `askEnclosingTreesAt` instead of `askTypeAt`, otherwise some hyperlinking tests are failing after the position fix carried out in this PR (as I write, I'm preparing the PR for Scala IDE that uses the new `askEnclosingTreesAt`)

When the above two PR are merged, then this PR should finally get a green status.

**Comment by danchia** [comment]
@dotta although I don't profess to know half of what's going on, this looks very promising for completions =)

**Comment by dotta** [comment]
@danchia It's only because you are missing context. Once you understand how (Range/Transparent)Position affects the IDE behavior, the changes in this PR makes a lot of sense. If you are interested in the subject, I'm happy to elaborate more in the scala-ide-dev ML ;-)

**Comment by dotta** [comment]
I need more work on https://github.com/scala/scala/pull/3358, and because this PR depends on the former, I think it's wise to not rush it. Therefore, you can consider this one as **not** targeting M8.

**Comment by gkossakowski** [comment]
@dotta: what's the status of this PR?

**Comment by dotta** [comment]
@gkossakowski It needs more work and unfortunately I don't have time to allocate on this - work stealing is of course welcomed.

**Comment by retronym** [comment]
Okay, we'll close the PR for now. Let's push again for 2.11.1!

**Pull request closed without merging**
