### PR TITLE
2.12.x: Windows CI (GHA): add JDK 17 (alongside 8)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
since the Windows jobs are mergely, PR validation will not test the change.

I guess I'll add a commit that makes it run as part of PR validation. Then we can remove the commit once CI likes it.

**Comment by SethTisue** [comment]
```
Run actions/setup-java@v2
12
Trying to resolve the latest version from remote
13
Error: Could not find satisfied version for SemVer '17'. 
14
Available versions: 16.0.1+9, 16.0.0+36, 15.0.2+7, 15.0.1+9, 15.0.0+36, 14.0.2+12, 14.0.1+7.1, 14.0.1+7.1, 14.0.0+36.1, 13.0.2+8.1, 13.0.1+9.1, 13.0.0+33.1, 12.0.2+10.1, 12.0.1+12, 12.0.0+33, 11.0.11+9, 11.0.10+9, 11.0.9+101, 11.0.9+11.1, 11.0.9+11, 11.0.8+10, 11.0.7+10.2, 11.0.7+10.1, 11.0.7+10.1, 11.0.6+10.1, 11.0.5+10.1, 11.0.4+11.1, 11.0.3+7, 11.0.2+9, 11.0.2+7, 11.0.1+13, 11.0.0+28, 10.0.2+13.1, 9.0.4+11, 9.0.0+181, 8.0.292+10, 8.0.282+8, 8.0.275+1, 8.0.272+10, 8.0.265+1, 8.0.262+10, 8.0.252+9.1, 8.0.252+9.1, 8.0.242+8.1, 8.0.232+9.1, 8.0.222+10.1, 8.0.212+4, 8.0.212+3, 8.0.202+8, 8.0.192+12, 8.0.181+13
```

I'll have to poke around and see if there's a way to persuade the setup-java action to fetch us an early-access build.

**Comment by SethTisue** [comment]
On JDK 17 (`17-ea`), most tests pass, but more than a handful fail.

```
Error:  8 of 14 test tasks failed:
Error:  - junit/test
Error:    - junit/test:test failed: sbt.TestsFailedException: Tests unsuccessful
Error:  - scalacheck/test
Error:    - scalacheck/test:test failed: sbt.TestsFailedException: Tests unsuccessful
Error:  - partest run
Error:    - test/it:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
Error:  - partest pos neg jvm
Error:    - test/it:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
Error:  - partest instrumented presentation
Error:    - test/it:testOnly failed: sbt.TestsFailedException: Tests unsuccessful
Error:  - osgiTestFelix/test
Error:  - osgiTestEclipse/test
Error:  - library/mimaReportBinaryIssues
Error:    - library/mimaReportBinaryIssues failed
```

I wonder how many of these failures were already fixed on 2.13.x.

Let's scale back our ambitions and try 11 instead of 17.

**Comment by SethTisue** [comment]
2.13.x version is #9679

**Comment by SethTisue** [comment]
Upon further reflection: on 2.12.x we ought to be targeting JDK 11, rather than skipping 11 and going straight to 17.

**Comment by SethTisue** [comment]
gah, there are also plenty of failures on 11

@lrytz I'm going to focus on 2.13 instead for now

**Comment by retronym** [comment]
I've backported the test fixes in #9682. Once that is in we can revive this PR.

**Comment by SethTisue** [comment]
11 is [green](https://github.com/scala/scala/pull/9678/checks?check_run_id=3090051813). let's try 17 now

**Comment by SethTisue** [comment]
failures on 17:

* `scala.collection.immutable.StringLikeTest.testNumericConversion`
  * backporting this should fix it: 4b61e57314257f1d0ea3195ae16eac36e59e3fbd
* `jvm/scala-concurrent-tck.scala` (failure is not intermittent and not Windows-specific)
  * backporting this should fix it: 86fe04b22f8eeb2474264ef7f1bbf0bc54c5a562

**Comment by SethTisue** [comment]
hmm, backporting the 2.13 jvm/scala-concurrent-tck.scala fix isn't completely straightforward... @som-snytt overhauled it (🙇 !), and it now it makes extensive use of stuff from `testkit`, the 2.12 equivalent of which (`scala.tools.testing`) isn't on the classpath for partests (for lack of #7817 and its sequels)

plus I have to decide whether to backport _this_:

```scala
import TimeUnit.{MILLISECONDS => Milliseconds}
```

**Comment by SethTisue** [comment]
plus I have to decide whether to backport _this_:

```scala
import TimeUnit.{MILLISECONDS => Milliseconds}
```

**Comment by SethTisue** [comment]
ha, well, code improvements aside, this seems to boil down to just "wait longer... a LOT longer... for the thread to die". okay, that's easy enough to do

**Comment by SethTisue** [comment]
green. I'll remove the "DO NOT MERGE: temporarily enable Windows CI on pull requests" commit now

**Comment by SethTisue** [comment]
@retronym review/merge?

**Review by retronym — APPROVED** [review]

**Pull request merged**
