### PR TITLE
Further tweak version of continuations plugin in scala-dist.pom

### PR DESCRIPTION
**Pull request by retronym**
While we must use full version, rather than the cross version
(12720e699), we need to use latest non-snapshot version.

This should avoid failures like:

  https://jenkins.scala-ide.org:8496/jenkins/view/Scala%20Xsource%20flag%20nightlies/job/Akka/63/console

Such as:

```
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] ::          UNRESOLVED DEPENDENCIES         ::
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
[warn] :: org.scala-lang.plugins#scala-continuations-plugin_2.11.0-SNAPSHOT;1.0.1:
not found
[warn] ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency:
org.scala-lang.plugins#scala-continuations-plugin_2.11.0-SNAPSHOT;1.0.1:
```

Review by @gkossakowski / @huitseeker

### CODE REVIEW

**Comment by gkossakowski** [comment]
@retronym: this is going to break (silently, at runtime) as soon as we introduce a binary incompatible change in compiler's API. I'd like to ask @adriaanm for opinion.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

It seems like a spurious failure.

**Comment by retronym** [comment]
I believe that this an unavoidable consequence of modularization. We need a test to catch it, for sure. 

The remedies are:
- avoid BC breakages in the parts of the API used by the continuations
- publish an internal release immediately after the BC breakage and update continuations accordingly.

**Comment by retronym** [comment]
The failure looks legit:

```
[artifact:deploy] [INFO] Uploading repository metadata for: 'snapshot org.scala-lang:scala-library-all:2.11.0-b4d42e7-SNAPSHOT'
     [echo] Deploying /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.0-b4d42e7-SNAPSHOT/scala-dist/scala-dist.jar with /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.0-b4d42e7-SNAPSHOT/scala-dist/scala-dist-pom.xml.
     [copy] Copying 1 file to /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.0-b4d42e7-SNAPSHOT/scala-dist
[artifact:pom] An error has occurred while processing the Maven artifact tasks.
[artifact:pom]  Diagnosis:
[artifact:pom] 
[artifact:pom] Unable to initialize POM scala-dist-pom-filtered.xml: Failed to validate POM for project org.scala-lang:scala-dist at /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.0-b4d42e7-SNAPSHOT/scala-dist/scala-dist-pom-filtered.xml
```

**Comment by retronym** [comment]
Here's the published POM:

http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-dist/2.11.0-2ba0453-SNAPSHOT/scala-dist-2.11.0-2ba0453-20140403.104509-1.pom

Containing:

```
    <dependency>
      <groupId>org.scala-lang.plugins</groupId>
      <!-- plugins are fully cross-versioned. But, we don't publish with 2.11.0-SNAPSHOT, instead use full version of the last non-snapshot version -->
      <artifactId>scala-continuations-plugin_2.11.0-RC3</artifactId>
      <version>1.0.1</version>
    </dependency>
```

**Comment by huitseeker** [comment]
This LGTM !

**Comment by gkossakowski** [comment]
LGTM

Upon further reflection I realized that this change won't make it any worse than what we already have when it comes to modules.

**Pull request merged**
