### PR TITLE
Inliner for GenBCode

### PR DESCRIPTION
**Pull request by lrytz**
Re-submission of #4262

### CODE REVIEW

**Comment by lrytz** [comment]
Hi @gkossakowski :)

Review commets of #4262 are addressed, but I the last 3 commits are new (inlining from traits).

A build with [`-Ybackend:GenBCode -Yopt:l:classpath -Ydelambdafy:method` is green](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1385/).

Community build [with the same flags is also green](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/134/)

**Comment by lrytz** [comment]
Quite a number of spurious failures.. Jenkins :( cc @adriaanm 

Symptom:

```
  ...
  [partest] ok 10 - scalacheck/range.scala                  
  [partest] ok 11 - scalacheck/primitive-eqeq.scala         
  [partest] ok 12 - scalacheck/ReflectionExtractors.scala   
Finished: FAILURE
```
- https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/161/console
- https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/164/console
- https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/162/console

Another Symptom:

```
  [partest] ok 20 - scalacheck/treemap.scala                
  [partest] ok 21 - scalacheck/Unrolled.scala               
  [partest] ok 22 - scalacheck/nan-ordering.scala           
  [partest] ok 23 - scalacheck/parallel-collections         
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Sorry, this connection is closed.
    at com.trilead.ssh2.transport.TransportManager.ensureConnected(TransportManager.java:587)
    at com.trilead.ssh2.transport.TransportManager.sendMessage(TransportManager.java:660)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:407)
    at com.trilead.ssh2.channel.Channel.freeupWindow(Channel.java:347)
    at com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:943)
```
- https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/169/console
- https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/170/console

**Comment by lrytz** [comment]
I added yet another commit. This one needs a bit of discussion whether it's OK for 2.11.6, so cc @adriaanm @retronym. It changes the default backend (GenASM) to emit the new `ScalaInlineInfo` classfile attribute. This would allow the new backend to inline code compiled by the ordinary backend.

Otherwise, when using the 2.11.6 release and enabling the new backend, no code from the standard library could be inlined.

I'll add a bytecode size diff.

**Comment by gkossakowski** [comment]
The last commit makes me feel nervous. I think we'll need some time and solid testing to nail down stable format for `ScalaInlineInfo`.

Is this strictly necessary for the first round of testing the new optimizer?

Also, how about enabling this in Scala 2.12?

**Comment by lrytz** [comment]
What aspect is worrying you?

`ScalaInlineInfo` has a version number, so it can evolve. If we add more information to it in the future, we can always parse old versions and build an `InlineInfo` without that new information. The only consequence would be that some method cannot be inlined.

The change is not necessary for testing the new optimizer, but if the 2.11.6 distro is built without that change, the new optimizer won't be able to inline from its standard library.

**Comment by gkossakowski** [comment]
Oh, I didn't realize it's versioned. I don't have any specific objection apart from default reaction to introducing new things in minor release: we don't do that. However, I could be convinced for example by saying that this has been already battle-tested by running the entire community build with new optimizer enabled.

I'd love to hear from @adriaanm and @retronym, though.

**Comment by lrytz** [comment]
Me too! :)

JAR sizes. Before:

```
  480142 scala-actors.jar
15531408 scala-compiler.jar
 5543249 scala-library.jar
 4663078 scala-reflect.jar
  785953 scalap.jar
```

After:

```
  490491 scala-actors.jar   (102.1%)
15865500 scala-compiler.jar (102.1%)
 5722504 scala-library.jar  (103.2%)
 4788370 scala-reflect.jar  (102.7%)
  805890 scalap.jar         (102.5%)
```

**Comment by lrytz** [comment]
The [community build](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/134/) passed.

Note that it tests exactly what we've been discussing: the scala/scala project is built with the GenASM, which also adds the `InlineInfo` attribute (the community build does not use the additional compiler flags when building scala/scala).

All other projects are built with GenBCode and the inliner enabled.

**Comment by lrytz** [comment]
@gkossakowski as a reminder: you did review the commits up to "Workaround for SI-9111" in the previous pr (#4262), and i addressed the feedback. the commits "Inline final methods defined in traits" and newer are not yet reviewed.

**Comment by lrytz** [comment]
@gkossakowski added one more commit, reporting inliner warnings. It would be a nice bundle for 2.11.6 and Scala Days :-)

**Comment by gkossakowski** [comment]
FYI: I'm looking at the new commits now.

**Comment by gkossakowski** [comment]
I got halfway through 1fcfe13. I'll continue reviewing tomorrow.

**Comment by lrytz** [comment]
cool, thanks! i realized that a lot of tests fail under `-Ybackend:GenBCode -Yopt:l:classpath -Ydelambdafy:method` because we have more (better!) warnings - i'll have to tone down the inliner

**Comment by gkossakowski** [comment]
Could you share a sample so we can get an idea how much better? :)

On 17 February 2015 at 18:20, Lukas Rytz notifications@github.com wrote:

> cool, thanks! i realized that a lot of tests fail under -Ybackend:GenBCode
> -Yopt:l:classpath -Ydelambdafy:method because we have more (better!)
> warnings - i'll have to tone down the inliner
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/scala/scala/pull/4312#issuecomment-74709081.

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by lrytz** [comment]
Sure!

For example:

```
lucmac:sandbox luc$ cat Test.scala 
class C {
  @inline def f = 1
  def t = f
}
lucmac:sandbox luc$ qsc -Yinline-warnings -optimize Test.scala 
Test.scala:3: warning: At the end of the day, could not inline @inline-marked method f
  def t = f
          ^
one warning found
lucmac:sandbox luc$ qsc -Yinline-warnings -Ybackend:GenBCode -Yopt:l:classpath Test.scala 
Test.scala:3: warning: C::f()I is annotated @inline but cannot be inlined: the method is not final and may be overridden.
  def t = f
          ^
one warning found
```

No more "at the end of the day"! :smile: 

Another:

```
lucmac:sandbox luc$ cat T.scala Test.scala 
trait T {
  @inline final def f = 1
}
class Test {
  def m(t: T) = t.f
}
lucmac:sandbox luc$ qsc -Yinline-warnings -Ybackend:GenBCode -Yopt:l:classpath T.scala 
lucmac:sandbox luc$ rm T\$class.class 
lucmac:sandbox luc$ qsc -Yinline-warnings -Ybackend:GenBCode -Yopt:l:classpath Test.scala 
Test.scala:2: warning: failed to rewrite final trait method invocation T::f()I to the static implementation method.
The method f(LT;)I could not be found in the class T$class or any of its parents.
Note that the following parent classes could not be found on the classpath: T$class
  def m(t: T) = t.f
                  ^
Test.scala:2: warning: T::f()I is annotated @inline but cannot be inlined: the trait method call could not be rewritten to the static implementation method (see earlier warnings).
  def m(t: T) = t.f
                  ^
two warnings found
```

Finally, there are warnings which don't say "could not inline foo, even though it's marked @inline", but they say "i don't know whether I could inline foo, I could not gather the necessary information". Here's one (**TODO**: improve the message, tell the user that the java source file is the cause):

```
lucmac:sandbox luc$ cat A.java Test.scala 
public class A {
  public final int f() { return 1; }
}
class Test {
  def m(a: A) = a.f()
}
lucmac:sandbox luc$ qsc -Yinline-warnings -Ybackend:GenBCode -Yopt:l:classpath A.java Test.scala 
Test.scala:2: warning: failed to determine if f should be inlined:
The method f()I could not be found in the class A or any of its parents.
Note that the following parent classes could not be found on the classpath: A
  def m(a: A) = a.f()
                   ^
one warning found
```

Finally, when a class does not yet have the `ScalaInlineInfo` attribute:

```
lucmac:sandbox luc$ cat T.scala Test.scala 
class T {
  @inline final def f = 1
}
class Test {
  def m(t: T) = t.f
}
lucmac:sandbox luc$ scalac -version
Scala compiler version 2.11.4 -- Copyright 2002-2013, LAMP/EPFL
lucmac:sandbox luc$ scalac T.scala 
lucmac:sandbox luc$ qsc -Yinline-warnings -Ybackend:GenBCode -Yopt:l:classpath Test.scala 
Test.scala:2: warning: there was a problem determining if method f can be inlined:
The inline information for T::f()I may be incomplete:
The Scala classfile T does not have a ScalaInlineInfo attribute.
  def m(t: T) = t.f
                  ^
one warning found
```

The last two generate a number of test failures. I quickly discussed with @adriaanm, the plan is to turn `-Yinline-warnings` into a multi-choice option which allows you to enable additional warnings.

**Comment by retronym** [comment]
> The last two generate a number of test failures. 

Agreed, a backwards compatibility mode for warnings might help ease the transition with our test suite.

> No more "at the end of the day"! :smile:

I always imagined that those warnings were belted out, [Les Mis style.](https://www.youtube.com/watch?v=vHwyCp6ah6U) :)

I guess in a few years we'll be able to adapt "Look Down" to something like:

:musical_note: Now bring me ticket SI-24601
Your time is up
And your parole's begun
You know what that means.

Yes, it means I'm fixed.

No!
Follow to the letter your regression test
This badge of shame you'll show until you die
It warns you're a dangerous bug :musical_note: 

Let's hope we're not still on JIRA by then, the `SI-` prefix really throws off the rhythm.

**Comment by gkossakowski** [comment]
Could you rebase please? It's not mergeable anymore.

**Comment by lrytz** [comment]
@gkossakowski I rebased on top of 2.11.x.

I added a new commit: configurable inliner warnings. This commit also addresses the review feedback you provided so far.

**Comment by lrytz** [comment]
Launched a [community build](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/136/) and a [checkin-manual build](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1389/) with the new optimizer enabled.

**Comment by lrytz** [comment]
@gkossakowski @retronym any ideas what could be the cause of this community build failure while running the scalaz test suite?

```
...
[scalaz] [info] + scalaz.LazyEitherTest.monad error.monad.left identity: OK, passed 33 tests.
[scalaz] [info] + scalaz.LazyEitherTest.monad error.raisedErrorsHandled: OK, passed 33 tests.
[scalaz] [info] + scalaz.LazyEitherTest.monad error.errorsRaised: OK, passed 33 tests.
[scalaz] [info] + scalaz.LazyEitherTest.monad error.errorsStopComputation: OK, passed 33 tests.
[scalaz] [info] + scalaz.OptionalTest.:\/ instance tests: OK, proved property.
[scalaz] [info] + scalaz.OptionalTest.:Option instance tests: OK, proved property.
[scalaz] [info] + scalaz.OptionalTest.:Validation instance tests: OK, proved property.
[scalaz] [info] + scalaz.OptionalTest.:Maybe instance tests: OK, proved property.
[scalaz] [info] + scalaz.OptionalTest.:syntax test: OK, proved property.
An exception occurred.
java.util.concurrent.TimeoutException: Await termination timed out after [1 minute]
    at akka.actor.ActorSystemImpl$TerminationCallbacks.ready(ActorSystem.scala:735)
    at akka.actor.ActorSystemImpl$TerminationCallbacks.ready(ActorSystem.scala:705)
    at akka.dispatch.Await$.ready(Future.scala:64)
    at akka.actor.ActorSystemImpl.awaitTermination(ActorSystem.scala:604)
    at distributed.build.LocalBuildMain.dispose(LocalBuildMain.scala:62)
    at distributed.build.SbtBuildMain.run(SbtBuildMain.scala:234)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
    at xsbt.boot.Launch$.run(Launch.scala:57)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:65)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
Build step 'Execute shell' marked build as failure
No JDK named ‘(Domyślny)’ found
Sending e-mails to: jzaugg@gmail.com adriaan@typesafe.com grek@typesafe.com
Finished: FAILURE
```

it happened here: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/135/consoleFull

i ran the build a second time, now it's hanging at the same place since one hour or so: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/136/consoleFull

**Comment by gkossakowski** [comment]
Scalaz tests were failing [Community-2.11.x-Java8](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-Java8/) recently in non-deterministic way. I'm not sure what has happened because scalaz version we use in community build didn't change.

I just removed caches for manual job and rerun it once again to see if it hangs in the same place: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/137/

**Comment by gkossakowski** [comment]
I must say I had a bit of a hard time following what's going on in bf45c57879bf1ad4ea8b294a978d42d1f1c250e6. I'll have another look tomorrow.

**Comment by lrytz** [comment]
@gkossakowski maybe you can start reviewing this change at the file [BackendReporting.scala](https://github.com/scala/scala/commit/bf45c57879bf1ad4ea8b294a978d42d1f1c250e6#diff-bfeb63b5cc6efb92f5b3f6d28c74e9df). I introduced a class for each accumulated warning case, which allows selective reporting later on. I removed the `Valid` type alias and use `Either` directly because the left type (the warning) now varies across methods.

**Comment by lrytz** [comment]
@gkossakowski i can reproduce the hanging build locally when running the scalaz test suite, investigating now.

**Comment by lrytz** [comment]
@gkossakowski I identified the bug: re-writing trait calls to the impl method assumes that the mixed-in method would simply delegate to the static impl method.

Things are different for field accessors (getters, setters): we should not do anything! Now for normal accessors, the re-write fails because the there does not exist any matching static method in the impl class (the impl class only contains method implementations). For _lazy_ vals however, a matching member is found: the lazy val initializer! The call is incorrectly re-written. 

Here's a trace, note that the initializer of `x` is executed twice:

```
lucmac:sandbox luc$ cat Test.scala 
sealed trait T {
  lazy val x: String = { println("hai"); "fish" }
       val y: String = { println("moin"); "uhu" }
}

final class C extends T

object Test {
  def m1(t: T) = t.x
  def m2(t: T) = t.y
}
lucmac:sandbox luc$ qsc -Ybackend:GenBCode -Yopt:l:classpath -Yopt-warnings:_ Test.scala 
Test.scala:10: warning: there was a problem determining if method y can be inlined:
The method y(LT;)Ljava/lang/String; could not be found in the class T$class or any of its parents.
  def m2(t: T) = t.y
                   ^
Test.scala:3: warning: there was a problem determining if method T$_setter_$y_$eq can be inlined:
The method T$_setter_$y_$eq(LT;Ljava/lang/String;)V could not be found in the class T$class or any of its parents.
       val y: String = { println("moin"); "uhu" }
           ^
two warnings found
lucmac:sandbox luc$ qs
Welcome to Scala version 2.11.6-newopt (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_65).
Type in expressions to have them evaluated.
Type :help for more information.

scala> val c = new C
moin
c: C = C@52ecba8

scala> Test.m1(c)
hai
res0: String = fish

scala> Test.m1(c)
hai
res1: String = fish

scala> Test.m2(c)
res2: String = uhu
```

**Comment by gkossakowski** [comment]
Wow! Good find and excellent analysis! It's cool to see such subtle bugs being caught by community build! :-)

**Comment by gkossakowski** [comment]
> I removed the Valid type alias and use Either directly because the left type (the warning) now varies across methods.

Let's put this into a commit message. Ideally, this could be done in a separate commit (those diffs are getting pretty big to scan).

**Comment by gkossakowski** [comment]
> I introduced a class for each accumulated warning case, which allows selective reporting later on.

When is "later on"? This is one confusing thing about d10f3fa02dc08199ff2cfe3d5d67780e1d3ec604 and bf45c57879bf1ad4ea8b294a978d42d1f1c250e6. I can't figure out when warnings get actually reported. How long are they deferred for?

The answer should go into commit message. This kind of stuff is usually the most difficult to figure out from the code.

**Comment by lrytz** [comment]
> When is "later on"? This is one confusing thing about d10f3fa and bf45c57. I can't figure out when warnings get actually reported. How long are they deferred for?

Warnings get issued in the [Inliner class](https://github.com/scala/scala/commit/bf45c57879bf1ad4ea8b294a978d42d1f1c250e6#diff-5158a9f0244fae0dd67b78969168cb03), search for `backendReporting.inlinerWarning`

**Comment by gkossakowski** [comment]
That means, warnings are issues right after a single inlining request is performed, right?

**Comment by lrytz** [comment]
> That means, warnings are issues right after a single inlining request is performed, right?

Yes, so there are two stages: a first set of warnings is issued when [collecting callsites to inline](https://github.com/scala/scala/commit/bf45c57879bf1ad4ea8b294a978d42d1f1c250e6#diff-5158a9f0244fae0dd67b78969168cb03R72), typically when the callee is annotated `@inline`, but the inlining cannot be performed.

The second set of warnings is issued when trying to inline a callsite that was successfully selected, but inlining cannot be performed. In this case, method [`canInline` generates a warning](https://github.com/scala/scala/commit/bf45c57879bf1ad4ea8b294a978d42d1f1c250e6#diff-5158a9f0244fae0dd67b78969168cb03R457) which is then [issued here](https://github.com/scala/scala/commit/bf45c57879bf1ad4ea8b294a978d42d1f1c250e6#diff-5158a9f0244fae0dd67b78969168cb03L36)

**Comment by gkossakowski** [comment]
Could you summarise how Java-defined callsites are treated? In particular, what happens when we have just Java sources passed? What happens when we have both Java sources and corresponding bytecode  on the classpath?

**Comment by gkossakowski** [comment]
Ok. I review all commits pushed to this PR so far. Overall, they look good. However, d10f3fa and bf45c57 appear to be a bit thin on documentation. There are tricky design choices behind those commits. I'd love to some of the insights behind specific design choices to be made explicit.

When it comes to fixing the inline from traits bug you discovered today, could we postpone this to another PR?

**Comment by lrytz** [comment]
> Could you summarise how Java-defined callsites are treated? In particular, what happens when we have just Java sources passed? What happens when we have both Java sources and corresponding bytecode on the classpath?

If a java source file is passed to scalac and there's no bytecode for the class on the classpath, the inliner won't be able to
- inline any method in that java class
- inline any (scala-defined) method that invokes one of the methods in the java class. The reason here is that we need the bytecode of the invoked java-method to know whether it's accessible at the new location. see [here for a test](https://github.com/lrytz/scala/commit/bf45c57879bf1ad4ea8b294a978d42d1f1c250e6#diff-258cab490610e4d0401a4a2c1efba65cR111)

If a classfile is on the classpath inlining can be performed.

**Comment by lrytz** [comment]
> When it comes to fixing the inline from traits bug you discovered today, could we postpone this to another PR?

Without it we won't pass the community build - and it's a small patch. I add it here for now, if it's important for you I can remove it later and create a new PR.

**Comment by gkossakowski** [comment]
If it's a small patch then it's fine with me. I just don't want this PR to grow much larger as it's getting difficult to wrap my head around it. You probably noticed a bit of my confusion already ;)

**Comment by lrytz** [comment]
Check it out, I just pushed it. Community build [running here](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/139/console).

**Comment by lrytz** [comment]
https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/149/

**Comment by lrytz** [comment]
@gkossakowski the last commit avoids the `VerifyError` that occurs when inlining a super call into a different class.

**Comment by gkossakowski** [comment]
LGTM

Excellent work! Thanks for addressing all of my earlier feedback.

**Comment by gkossakowski** [comment]
:fireworks:

**Comment by lrytz** [comment]
woohoo!

**Comment by adriaanm** [comment]
Excellent work guys!

**Pull request merged**
