### PR TITLE
Restore reporter forwarders in CompilationUnit

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

**Comment by gkossakowski** [comment]
Why do we need to restore them? Is it the failure of continuations?

**Comment by adriaanm** [comment]
Yeah, I missed that one. I refactored continuations to not use `unit.error|warning` so we can remove them later. (See referenced PR.)

**Comment by gkossakowski** [comment]
Let's mention that in the commit message to aid future git-blamers.

**Comment by adriaanm** [comment]
It's more general than that, though. I assume plenty of plugins out there use this method. Should've been more conservative in my cleanup.

**Comment by gkossakowski** [comment]
The point to mention the reason behind restoration remains. The continuations plugin serves as a good example. :)

**Comment by adriaanm** [comment]
Done.

**Comment by gkossakowski** [comment]
Thank you. LGTM.

**Comment by adriaanm** [comment]
Man these network problems sure are getting old.

**Comment by adriaanm** [comment]
Manually rebuilding the failed jobs: 

https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7540/console
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-partest/6203/console

**Comment by adriaanm** [comment]
Ugh, looks like the pom wasn't deployed...

**Comment by adriaanm** [comment]
fi-nal-ly!

**Comment by adriaanm** [comment]
Retrying community build: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x/203/console

**Comment by xeno-by** [comment]
Yup, paradise was using them as well.

**Pull request merged**
