### PR TITLE
Merge 2.11 to 2.12 june 26

### PR DESCRIPTION
**Pull request by lrytz**
Brings closure elimination to 2.12.x

Work log:

```
➜  scala git:(2.12.x) git log --oneline -1 2.11.x
5b80736 Merge pull request #4582 from SethTisue/contributors-guide-tweaks


➜  scala git:(2.12.x) git log --oneline -1 2.12.x
d90d8b8 Merge pull request #4580 from lrytz/defaults


➜  scala git:(2.12.x) export MB=$(git merge-base 2.12.x 2.11.x)


➜  scala git:(2.12.x) ✗ git cob merge-2.11-to-2.12-june-26


➜  scala git:(merge-2.11-to-2.12-june-26) git log --graph --oneline --decorate $MB...2.11.x
*   5b80736 (upstream/2.11.x, scala/2.11.x, 2.11.x) Merge pull request #4582 from SethTisue/contributors-guide-tweaks
|\  
| * ab80d51 add note to contributor's guide about branches
| * e8e69c3 minor tweaks to contributor's guide
|/  
*   590436f Merge pull request #4581 from SethTisue/2.11.8-is-next
|\  
| * fbc49a6 Bump versions after 2.11.7 release
* |   bb102e7 Merge pull request #4570 from marconilanna/patch-1
|\ \  
| |/  
|/|   
| * 9b066dd Traits mistakenly set as 'Case Classes' subsection
*   4d78656 Merge pull request #4577 from janekdb/2.11.x-typos-j-l
|\  
| * 639f0b4 Fix 8 typos (j-l)
* 950bb26 Merge pull request #4552 from lrytz/opt/closureInlining
* 3e7776e Cast arguments where necessary before rewriting closure invocations
* 5be0722 Rewrite closure invocations to the lambda body method
* d159f14 Producers / Consumers Analysis



➜  scala git:(merge-2.11-to-2.12-june-26) git merge bb102e7
Auto-merging versions.properties
Auto-merging src/repl/scala/tools/nsc/interpreter/JavapClass.scala
CONFLICT (content): Merge conflict in src/repl/scala/tools/nsc/interpreter/JavapClass.scala
Auto-merging src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/GenBCode.scala
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/BCodeIdiomatic.scala
Automatic merge failed; fix conflicts and then commit the result.

-- fix the conflict.
-- 639f0b4 fixed typos in a part of JavapClass that is removed in 2.12.x


➜  scala git:(merge-2.11-to-2.12-june-26) git merge 590436f -s ours
Merge made by the 'ours' strategy.


➜  scala git:(merge-2.11-to-2.12-june-26) git lg
*   085b28d - (HEAD -> merge-2.11-to-2.12-june-26) Merge commit '590436f' into merge-2.11-to-2.12-june-26 (15 seconds ago) <Lukas Rytz>
|\  
| *   590436f - Merge pull request #4581 from SethTisue/2.11.8-is-next (2 days ago) <Seth Tisue>
| |\  
| | * fbc49a6 - Bump versions after 2.11.7 release (2 days ago) <Seth Tisue>
* | |   d785aed - Merge commit 'bb102e7' into merge-2.11-to-2.12-june-26 (26 seconds ago) <Lukas Rytz>



➜  scala git:(merge-2.11-to-2.12-june-26) git diff d785aed
-- empty diff - the changes to versions.properties don't apply to 2.12.x



➜  scala git:(merge-2.11-to-2.12-june-26) git merge 5b80736
Merge made by the 'recursive' strategy.
```

### CODE REVIEW

**Comment by lrytz** [comment]
review by @SethTisue - only the last commit has to build correctly.

**Comment by lrytz** [comment]
alternatively review by @adriaanm or @retronym.

**Comment by lrytz** [comment]
the merge commit built correctly.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
