### PR TITLE
SI-7870 Detect default getter clashes in constructors

### PR DESCRIPTION
**Pull request by retronym**
Default getters for constructors live in the companion module.
These eluded the check for clashes in default getter names due
to overloading, which aims to give a more user friendly error
than "double definition: meth$default$1".

This commit checks for default getters in the companion module,
in addition to those in the template itself.

Review by @lrytz

### CODE REVIEW

**Comment by som-snytt** [comment]
LGTM  One of my small contributions was another edge case in init default getters, but I missed this.

I'm not sure the comment and check at line 144 about ctors still applies. 

https://github.com/retronym/scala/blob/d882ec053c9a70d29e668bc80bb3f1aa830c0281/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala#L144

I see findMember does stop `bcs = if (name == nme.CONSTRUCTOR) Nil else bcs.tail` on init.

I'll add debug to clarify for myself; if I'm mistaken, then this note is just to say that it's not clear to me yet.

**Comment by lrytz** [comment]
LGTM

**Comment by retronym** [comment]
I should mention that this change is source incompatible with 2.10.x, as the restriction on "only one overloaded constructor can use defaults" is more severe than "no two constructors can use a default in the same position with the same type".

So arguably we should introduce this as a deprecation in 2.11. Thoughts, @gkossakowski?

**Comment by lrytz** [comment]
The 2.10 behavior is a bug, so IMO it should go in 2.10

**Comment by retronym** [comment]
It's not a critical bug in any case, so I don't plan to backport to 2.10.

@lrytz could you comment on the line that @som-snytt pointed out? I guess it is trying to allow:

```
class C(a: Int = 0)
class D(b: Int = 0) extends C()
```

Ah, it looks like `findMembers` is still buggy and returns superclass constructors

```
scala> typeOf[D].members.filter(_.name == nme.CONSTRUCTOR)
res0: $r.intp.global.Scope = Scopes(constructor D, constructor C)

scala> typeOf[D].member(nme.CONSTRUCTOR)
res1: $r.intp.global.Symbol = constructor D
```

Which reminds me, I've got an unfinished branch that tries to un-diverge `findMember` and `findMembers` which would fix this once and for all: https://github.com/scala/scala/commit/cc6a3c946d51d13805382271a9672ffb18fe48f4

**Comment by lrytz** [comment]
I see, it's a question of deprecation.

The example should be allowed, and it seems to work both in 2.10.2 and 2.11-M4 - so is there a bug?

**Comment by retronym** [comment]
No. We're just trying to understand that code. I think it makes things work, and is still needed so long as `findMembers` is buggy in that it returns super-class constructors.

**Comment by lrytz** [comment]
OK, I get it now. I guess I didn't think that `findMembers` could be buggy when I wrote the code..

**Comment by retronym** [comment]
I'm not sure why else you would have written that code! But let's not dwell on the past :)

**Comment by som-snytt** [comment]
This is OT, but kudos to you both on the spec PRs.

**Comment by som-snytt** [comment]
> Which reminds me, I've got an unfinished branch

Proof that @retronym has actually become @paulp .

**Pull request merged**
