### PR TITLE
Fix problems in Symbol Literal static caching

### PR DESCRIPTION
**Pull request by retronym**
Details in the commit messages.

Review by @soc / @lrytz

### CODE REVIEW

**Comment by soc** [comment]
Apart from the PR reference raised above, it LGTM.

**Comment by retronym** [comment]
Commit comment modified, test comments removed.

**Comment by retronym** [comment]
PLS SYNCH

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@4a8a5c1e5b37919d77c089bf4e3ccada4b5c3e81

**Comment by lrytz** [comment]
@retronym in both commit messages `s/3419/3149/`

**Comment by retronym** [comment]
Ooops (again.)

Fixed.

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
