### PR TITLE
Added example to Option.collect method.

### PR DESCRIPTION
**Pull request by jxcoder**
I added code which described how to **Option.collect** method works.

``` scala
// Returns Some(HTTP) because the partial function covers the case.
Some("http").collect({case "http" => "HTTP"})

// Returns None because the partial function doesn't cover the case.
Some("ftp").collect({case "http" => "HTTP"})

// Returns None because None is passed to the collect method.
None.collect({case value => value})
```

### CODE REVIEW

**Comment by jxcoder** [comment]
@vladureche, @heathermiller what do you think about this pull request?

**Comment by VladUreche** [comment]
LGTM

**Comment by som-snytt** [comment]
Kind of too bad about the extra parens in an official example.

**Comment by VladUreche** [comment]
@som-snytt: Ooops, that's a good point. I think showing the parentheses in one example is okay, but we should also have examples without: 

``` scala
// Returns Some(HTTP) because the partial function covers the case.
Some("http").collect {case "http" => "HTTP"}

// Returns None because the partial function doesn't cover the case.
Some("ftp").collect {case "http" => "HTTP"}

// Returns None because None is passed to the collect method.
None.collect {case value => value}

// Same as before, but using the operator notation:
None collect {case value => value}

// Same as before, but with explicit parentheses:
None.collect({case value => value})
```

@jxcoder, how about an additional PR?

**Comment by jxcoder** [comment]
@vladureche, I think that example must show usages of the method. The parentheses usages described in another document. I suggest this:

``` scala
// Returns Some(HTTP) because the partial function covers the case.
Some("http") collect {case "http" => "HTTP"}

// Returns None because the partial function doesn't cover the case.
Some("ftp") collect {case "http" => "HTTP"}

// Returns None because None is passed to the collect method.
None collect {case value => value}
```

**Comment by retronym** [comment]
This PR doesn't merge cleanly anymore. Can you please rebase on top of `origin/2.12.x`?

For future reference, a change like this could be submitted to the maintainence branch (currently, 2.11.x). That way it will be in the next minor release, rather than having to wait for 2.12.0.

**Pull request merged**
