### PR TITLE
upgrade sbt, logback, slf4j

### PR DESCRIPTION
**Pull request by SethTisue**
they are used only in build and testing, but regardless, let's do it

### CODE REVIEW

**Comment by htmldoug** [comment]
Makes sense. Scala steward?

**Comment by SethTisue** [comment]
I cannot remember why we don't have the steward enabled here. If there's even a reason. @lrytz have we discussed this before?

One capability that was added to the steward recently is https://github.com/scala-steward-org/scala-steward/blob/master/docs/faq.md#can-scala-steward-update-multiple-branches-in-a-repository , so we would now be able to request PRs to both the 2.12.x and 2.13.x branches. (We might close some of the 2.13.x PRs with the intention that we would merge the 2.12.x one instead and then merge change the forward, but that's okay.)

**Comment by lrytz** [comment]
> @lrytz have we discussed this before?

I don't remember us discussing this before, let's try it. I assume the need was low because we don't have many dependencies.

**Comment by SethTisue** [comment]
We're in! https://github.com/scala-steward-org/repos/pull/876

**Pull request merged**
