### PR TITLE
SI-6811 Scheduled removal of deprecated items for 2.11

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
@paulp, @gkossakowski could you have a look?

The first 10 commits are equal to the old, large one. The 11th is new.

**Comment by paulp** [comment]
Still looks good to me (but I took your word for it that I'd already seen the first ten.)

**Comment by adriaanm** [comment]
LGTM -- can we get a ticket for stuff that is to be resurrected? as in a386291, for example

**Comment by gkossakowski** [comment]
I reviewed all of those commits separately and they all LGTM.

Thanks for splitting them nicely!

For future archeologists: if you are wondering why tests for RedBlack trees got removed check discussion in #1918.

**Pull request merged**
