### PR TITLE
Revert linting until restarr

### PR DESCRIPTION
**Pull request by som-snytt**
The linting will be more reasonably verbose in future.

### CODE REVIEW

**Comment by SethTisue** [comment]
we have now re-STARRed

**Comment by SethTisue** [comment]
@som-snytt did you mean to return to this?

**Comment by som-snytt** [comment]
I think I accidentally left linting turned on in a PR somewhere, but I don't remember where.

**Comment by SethTisue** [comment]
@som-snytt should we uncomment these lines, or delete them, or what?

**Comment by som-snytt** [comment]
@SethTisue Does my commented code bug you? It's to save me 5-10 minutes every time I forget that `maxErrors` thing in sbt, which I remember now only because someone mentioned it recently.

Probably I did turn on the linting in a PR, but it was never merged.

I'm working on a debugging SIP called Meta-Optimized Operational Records for Scala, or MOORS, which we can use as inline pragmas instead of println and Xlint. A MOORS directive will print information about a value, including the git blame of the line that set it. `-Xmax-blame` does that for all lines that contribute to a calculation. `-Yassign` reduces the problem to only lines touched by retronym, so the ticket can be assigned directly to him.

**Comment by som-snytt** [comment]
Moors' Law: When you flip the switches back again, the errors will have increased exponentially:

```
[error] scala.reflect.internal.FatalError: object Predef does not have a member $eq$colon$eq
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.fatalMissingSymbol(Definitions.scala:1338)
```

**Comment by som-snytt** [comment]
@SethTisue I see it's because of https://github.com/scala/scala/commit/df29ebbd91481a8468dde2b06a96438291824f73 in https://github.com/scala/scala/pull/7350

It needs another restarr?

**Comment by som-snytt** [comment]
I confirmed that the linked PR went in after the last restarr, so building with diagnostics on crashes non-bootstrapped as above. Maybe there is a way to enable diagnostic options only when running a bootstrapped build? That would make it less useful, of course, since warnings would appear only in Jenkins output where Jenkins would politely ignore the mess.

**Pull request merged**
