### PR TITLE
Make optimizer work on JDK 13+ (update ASM to 7.3.1)

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/bug/issues/11671

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]
(I'll be sure and do a community build run not long after this is merged)

**Review by retronym — APPROVED** [review]

**Comment by SethTisue** [comment]
community build runs at https://github.com/scala/community-build/pull/1070

**Comment by mkurz** [comment]
ASM 9.0, which brings support for Java 15 and even Java 16 already just got released:
* https://gitlab.ow2.org/asm/asm/-/tags/ASM_9_0
* https://repo1.maven.org/maven2/org/ow2/asm/asm/9.0/
* https://asm.ow2.io/versions.html

**Comment by SethTisue** [comment]
ticket for the ASM 9 upgrade: https://github.com/scala/bug/issues/12328

**Pull request merged**
