### PR TITLE
Disable flaky tests

### PR DESCRIPTION
**Pull request by retronym**
- Reopens SI-7020 (non-determinism in virpatmat)
- presentation/doc awaits @huitseeker's Eureka! moment

### CODE REVIEW

**Comment by retronym** [comment]
Review by @xeno-by, /cc @adriaanm @huitseeker

**Comment by xeno-by** [comment]
lgtm

**Comment by som-snytt** [comment]
What is the difference between pending and disabled?

I think pending means: I should pass someday when the behavior I test works as expected.

Whereas disabled would mean: I'm on the disabled list because I break the build for other reasons, like consuming time and space, or not running on Windows, or outputting rude messages on the console.

**Comment by som-snytt** [comment]
So the headline perhaps should read: Pending tests for flaky behavior.  Add "o(u)r" where required.

**Comment by retronym** [comment]
I suppose in both cases the problem is the compiler, not the test, so you could make an argument for `pending`. But the compiler works 99% of the time, so I didn't want to offend it and blamed the tests instead.

**Pull request merged**
