### PR TITLE
SI-6488 Interrupt i/o threads on process destroy

### PR DESCRIPTION
**Pull request by som-snytt**
The previous fix uses Thread.stop to stop the threads which
drain outputs, but should do something orderly.

This commit interrupts the threads, which must check isInterrupted
before attempting further i/o.

The reading thread will suppress either the interruption or the
IOException cited in the ticket.

Similarly, i/o handlers must preserve and communicate interrupted
status.

The modest goal of this fix is to ameliorate any stack traces
when the process is destroyed.

The test runs itself as a sample process with output.

Supersedes https://github.com/scala/scala/pull/2478 which was corrupted by history.

Review by @soc and @harrah, hurrah.

### CODE REVIEW

**Comment by harrah** [comment]
I won't have time to review this for a while, sorry.

**Comment by som-snytt** [comment]
@harrah Ok thanks.  I just wanted to say, hurrah.

**Comment by soc** [comment]
LGTM, but I have a hard time wrapping my head around processes and threads, so don't trust me completely on that.

**Comment by som-snytt** [comment]
@soc So your position on Thread.stop was just a matter of policy? (kidding)

For the future reviewer, I'll try to add something persuasive.  That something is probably tests.

**Comment by soc** [comment]
:-) No, `Thread.stop` is fundamentally broken. Thread cancellation doesn't even work properly in C.

I can identify some broken parts, but I still lack the confidence to say “this is correct” in any concurrency-related code.

**Comment by som-snytt** [comment]
So @soc can confirm at least that the source text of the program no longer includes the character sequence "stop".

I enjoyed Rex's ML comment that threads are easy-peasy, lemon-squeezy.

**Comment by adriaanm** [comment]
Huzzah!

**Comment by som-snytt** [comment]
OMG, did that go through?

Is that on the @paulp basis that it can't be worse than what's already there?

I am also thinking about the other Process.destroy PR and related tests; right after I figure out how I broke plugins; but first I'm sending out resumes. Please supply the accent aigu on resume.

**Comment by adriaanm** [comment]
> Is that on the @paulp basis that it can't be worse than what's already there?

Sadly, yes (also, rejection fatigue).

Follow-up improvements will be greeted with sincere "huzzah"s.

**Pull request merged**
