### PR TITLE
uniform dealiasing and widening

### PR DESCRIPTION
**Pull request by paulp**
Supersedes (and retargets to master) #1789.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
We Pay Cash For LGTMs! Act now! @retronym @xeno-by @JamesIry

**Comment by soc** [comment]
Well, looks good to me. :-)

**Comment by xeno-by** [comment]
I don't think I can be a qualified reviewer for distinguishing where one needs `dealiasWiden` and where only `dealias` is appropriate. However I definitely appreciate extra clarity brough by this pull request. LGTM. Maybe the name of `dealiasWiden` might be improved a bit though.

**Comment by paulp** [comment]
I'm up for suggestions on alternative names - I'm not thrilled with it either but I will be even less thrilled about a name if it's longer, so it has to be shorter. We could use a word like "reduce", "simplify", etc. if we can all agree on the word.

reduce is appealing to me, maybe

```
def reduceOnce: Type // next step, either betaReduce or widen
def reduced: Type       // dealiasWiden
def reductionChain: List[Type] // dealiasWIdenChain
```

**Comment by xeno-by** [comment]
To me `reduce` sounds like `betaReduce`, which `dealiasWiden` is not. Maybe we could use the name `normalize` and give today's `normalize` a better name? 

Btw what exactly `normalize` does now? Its comment doesn't seem to cover all the logic buried in various `normalizeImpl` methods. And it's hard to infer its workings from its name.

upd. This suggests that `normalize` might not be the best name ever. Maybe we could rename it? And on a second thought `dealiasWiden` sounds quite good - at least, its name exactly conveys what it does.

**Comment by paulp** [comment]
normalize is closer to the worst name ever than the best; see numerous comments from me in the past that "we have too many things called normalize" (also used to be true of some other names like "widen", less so now.) In terms of communicative power, "normalize" is about as effective as "makeTypeLikeIWantIt".

**Comment by adriaanm** [comment]
I've rechopped this PR a bit. Running test suite on individual commits to make sure, but then I'll close this one unless someone objects.

**Comment by paulp** [comment]
Thanks a lot. I have a followup commit based on some of the feedback and further winnowing of unnecessary calls to normalize, but I'd be very happy to see this merged - I'll submit followup separately.

**Comment by paulp** [comment]
Hijacked/superseded by #1826.

**Pull request closed without merging**
