### PR TITLE
SI-6582 Use Tseitin transformation to convert propositional formulae into CNF.

### PR DESCRIPTION
**Pull request by gbasler**
This resolves the `AnalysisBudgetException` problem for big pattern matches.

Initial experiments indicate that the problem is even simpler than initially thought: all formulae I got from the exhaustiveness check could be transformed directly into CNF by formula simplification, neither expansion not Tseitin transformation where needed.
Thus the framework introduced here might be overkill and a much simpler implementation could work as well.

For Scala 2.11 I'd suggest to replace the DPLL procedure with Sat4j. See separate branch.

Review by @adriaanm

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
@gbasler

> For Scala 2.11 I'd suggest to replace the DPLL procedure with Sat4j. See separate branch.

Opening a ticket at https://issues.scala-lang.org/ would raise the visibility of this suggestion. Then comes classifying that ticket at "improvement" or "performance bug".

**Comment by soc** [comment]
Weird, do we have heavy load on the build servers?
`Build timed out (after 240 minutes). Marking the build as aborted.`

@gbasler I can't comment on the technical aspects, but let me know if you need help with the processes around contributing (this is your first PR on scala/scala, right?).

**Comment by adriaanm** [comment]
Thanks, @gbasler! Looks like one of the tests in test/files/pos/*.scala is causing the algorithm to loop? You can reproduce locally with `ant pack.done ; test/partest --pos`

**Comment by gbasler** [comment]
retest this please

**Comment by gbasler** [comment]
@adriaanm Thanks, I saw that the tests were not finishing but thought it was a problem with my setup (since it was one of the very last ones that failed). All test should pass now.

**Comment by gbasler** [comment]
@magarciaEPFL I've created a ticket here: https://issues.scala-lang.org/browse/SI-7663

@soc This is indeed my first PR, I might come back to your offer. I've just seen that there is a corresponding ticket here: https://issues.scala-lang.org/browse/SI-6582.

**Comment by adriaanm** [comment]
Cool! (Btw, the build bot rebuilds automatically as you push new commits to the PR)
I'll have a look on Monday!

**Comment by adriaanm** [comment]
So sorry this has been slipping -- I've been buried with other stuff.

**Comment by gbasler** [comment]
Don't worry ;-)
I'm in contact with the Sat4j guys and got SVN access. I'll rework the CNF translation part in to Sat4j a bit and eventually create a PR against the new Sat4j Scala interface for 2.11...

**Comment by adriaanm** [comment]
Perfect!

**Comment by gkossakowski** [comment]
@adriaanm: ping

**Comment by adriaanm** [comment]
This is outstanding work! I'm very sorry about the delay in reviewing, so I'll address my only review comment myself: I'd like to chop this up in a few smaller commits. Working on that today.

**Comment by adriaanm** [comment]
One performance question: this seems to undo the optimization added in f5397818aa -- is that necessary/safe now?

**Comment by gbasler** [comment]
@adriaanm The CNF conversion is not composable anymore (since each translation would need to know the auxiliary variables of the others and the mapping from subformulas to literals), thus the (CNF(...) + CNF(...) ...) approach doesn't work anymore. Even better, the simplification is not needed because 1) the conversion can't blow the stack anymore, 2) the formula is simplified as a whole before the conversion.

**Comment by adriaanm** [comment]
Ok, makes sense -- I'll merge the last two commits of the rework I submitted.

**Pull request closed without merging**
