### PR TITLE
SI-9026 Copyright update

### PR DESCRIPTION
**Pull request by heathermiller**
Updates all copyrights to 2015. Also squashes a little bit of whitespace along the way.

### CODE REVIEW

**Comment by mpociecha** [comment]
Hm, updating copyrights has become very popular - https://github.com/scala/scala/pull/4181

**Comment by kanielc** [comment]
We should close #4181 and go with this one since it covers next year as well.

**Comment by mpociecha** [comment]
On the other hand you modified more files so someone could check what's the difference (you both started from the same base revision).

Edit: @ down Sure, I know. I just thought there are some files omitted in this PR.

**Comment by kanielc** [comment]
Yeah, but my work would need to be done again in a month.  There were other inconsistencies in the headers that need changing, but that's for a different day.

**Comment by som-snytt** [comment]
I didn't have an opinion until I just went to look at history on 2.10 and the last commit on everything is the copyright update. That becomes visible through the magic of github. I hope the suggestion on the other commit prevails, namely, update to the year of the last update, preferably as a pre-merge check (possibly automated).

**Comment by heathermiller** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
I appreciate both PRs (thanks @heathermiller and @kanielc!), but I think it's time to invest in automation here, rather than bulk update every year.

**Comment by Ichoran** [comment]
@adriaanm Who is writing the tool?  No point duplicating effort again.

**Comment by adriaanm** [comment]
No-one is assigned to this yet, though it's in @gkossakowski general area of responsibility.

**Comment by vsalvis** [comment]
Copyrights are still outdated. The main question to answer seems: Can we/should we update copyrights if the file wasn't changed? See also discussion on https://github.com/scala/scala/issues/4181 and som-snytt's comment above.

If the answer is yes, then we could merge this PR and provide a script that can be run at the beginning of each year (possibly requiring some more standardization).

If the answer is no, we need a PR to bring copyrights up to the date of the latest commit, and then from there on a script that could be either:
- a pre-merge check: annoying at first, but people will learn quickly to update copyrights on all changed files, and this solves the problem som-snytt was mentioning.
- a pre-merge bot: seems like a bad idea, because people won't usually pull before rebasing or adding commits to their PR.
- part of the release cycle: less annoying, but will create a commit with copyright updates.

**Comment by adriaanm** [comment]
I'd vote for a pre-merge check. IDEs can automatically update copyrights on save, so maybe that will finally push us over the IDE-resistance hump :-)

In any case, we should only update copyrights for modified files, preferably as we update them.

**Comment by heathermiller** [comment]
Annual reminder that copyrights are still outdated and still no tool exists.

**Comment by Ichoran** [comment]
Whose general area of responsibility is this now, @adriaanm ?

**Comment by som-snytt** [comment]
After the machines win the war, they will write a tool and send it back through time to update the copyright notices.

The tool will bear an uncanny resemblance to heathermiller, because that's how they trick us into dropping our guard, so that we'll never be certain if the copyrights were updated by the real original heathermiller or the future replicant tool. I guess we'll figure it out if the notice says "Copyright 2029."

**Comment by adriaanm** [comment]
I for one welcome our future copyright-updating overloads.

**Pull request closed without merging**
