### PR TITLE
Refined isEffectivelyFinal logic for sealedness.

### PR DESCRIPTION
**Pull request by paulp**
If the enclosing class of a method is sealed and has only final
subclasses, then the method is effectively final in the sealed class if
none of the subclasses overrides it. This makes it possible to inline
more methods without explicitly marking them final.

Note that the test doesn't fail before this patch due to SI-6142,
a bug in the optimizer, but here's a bytecode diff to prove it:

  @@ -16,8 +16,10 @@ public final class Test$ {
       Code:
   : getstatic                      // Field Foo$.MODULE$:LFoo$;
   : invokevirtual                  // Method Foo$.mkFoo:()LFoo;
  +: pop
   : bipush
  -: invokevirtual                  // Method Foo.bar:(I)I
  +: iconst_1
  +: iadd
   : ireturn

And the test in neg, which is manually made to fail due to the absence
of inline warnings, correctly refuses to inline the methods.

Review by @dragos.

### CODE REVIEW

**Comment by jsuereth** [comment]
While I don't really know enough about the compiler, this LGTM and I'd like to merge.  @dragos ?

**Comment by paulp** [comment]
It's not a scary patch; go ahead and merge it, the floor will remain open for comments.

**Comment by dragos** [comment]
LGTM.

**Comment by dragos** [comment]
Sorry for the delay, I'm swamped, and github notifications are not helping. Is there a way to remove the build bot notifications? They burry everything,

**Comment by ijuma** [comment]
Nice one.

**Comment by jsuereth** [comment]
I'm gonna look into possibly having the build bot status displayed as some kind of plugin or other non-annoying mechanism when I get some time to dig back into it.

**Comment by retronym** [comment]
This one triggered a regression, see: #3573

**Pull request merged**
