### PR TITLE
SI-8948 resurrect the scaladoc for Any/AnyRef/Nothing/Null.

### PR DESCRIPTION
**Pull request by gourlaysama**
They disappeared in dc1cd96 when `scala.tools.nsc.doc.DocParser` lost
its `override def forScaladoc = true`, which used to trigger whether to
parse `DocDef` nodes. This was deprecated in favor of a custom global
when scaladoc was modularized out (#2226), but `DocParser` didn't get it
since it didn't override `forScaladoc` anymore...

I added back `forScaladoc` in `DocParser` for consistency with
`ScaladocGlobal`, although it doesn't do anything anymore.

### CODE REVIEW

**Comment by gourlaysama** [comment]
The second commit prevents `Any`'s scaladoc from showing a huge list of subclasses. I swear there was a ticket for this, but I can't find it...

**Comment by gourlaysama** [comment]
Review @VladUreche :)

**Comment by som-snytt** [comment]
Is it necessarily more useless than the big list of subclasses for Serializable?

It would be a flat list of all classes, which currently is not displayed anywhere.  (It's hard to locate a nested class.)  For example, `WrappedArray.ofBoolean` is in the list for `Serializable` but not in the searchable list.  I can find it in the member index instead, with some scrolling.

Maybe the harder challenge is navigating a big list of classes.

**Comment by VladUreche** [comment]
Thanks @gourlaysama! Have you checked the diagrams? Is the content diagram for `package scala` okay?

@som-snytt, are you okay with merging this? I think scaladoc searching should be a topic in its own, as we'll eventually have to come up with something that allows full search.

**Comment by som-snytt** [comment]
@VladUreche Absolutely. Just thinking out loud.

**Comment by VladUreche** [comment]
LGTM! (I checked the diagrams on my machine)

**Pull request merged**
