### PR TITLE
SI-9359 Fix InnerClass entry flags for nested Java enums

### PR DESCRIPTION
**Pull request by lrytz**
The access flags in InnerClass entries for nested Java enums were
basically completely off.

A first step is to use the recently introduced backend method
`javaClassfileFlags`, which is now moved to BCodeAsmCommon.
See its doc for an explanation.

Then the flags of the enum class symbol were off. An enum is
- final if none of its values has a class body
- abstract if it has an abstract method
  (https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.9)

When using the ClassfileParser:
- ENUM was never added. I guess that's just an oversight.
- ABSTRACT (together with SEALED) was always added. This is to
  enable exhaustiveness checking, see 3f7b8b5. This is a hack and we
  have to go through the class members in the backend to find out if
  the enum actually has the `ACC_ABSTRACT` flag or not.

When using the JavaParser:
- FINAL was never added.
- ABSTRACT was never added.

This commit fixes all of the above and tests cases (Java enum read
from the classfile and from source).

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @adriaanm. I think this should not go in 2.11.7.

**Comment by adriaanm** [comment]
ok, I reopened the milestone

**Comment by lrytz** [comment]
you missed the "not" 😮

**Comment by adriaanm** [comment]
not anymore :)

**Comment by adriaanm** [comment]
thanks

**Comment by lrytz** [comment]
@adriaanm @SethTisue I actually changed my mind, and I **do** think we **should** get this into 2.11.7. It fixes all failures of the [`-Ybackend:GenBCode` nightly](https://scala-webapps.epfl.ch/jenkins/view/2.11.x/job/scala-nightly-genbcode-2.11.x), and some of the failures look pretty bad:

```
java.lang.ClassFormatError: Illegal class modifiers in class scala/tools/nsc/interpreter/JavapClass$JavapTool7$JavapFileManager: 0x419
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
```

**Comment by lrytz** [comment]
Note that the above failure (`Illegal class modifiers`) would be a regression in 2.11.7, it's not there in 2.11.6. It was introduced when #4529 was merged.

**Comment by adriaanm** [comment]
LGTM

**Comment by lrytz** [comment]
GenBCode build [turned green](https://scala-webapps.epfl.ch/jenkins/view/2.11.x/job/scala-nightly-genbcode-2.11.x/417/).

**Comment by adriaanm** [comment]
!! :fireworks:  !!

**Pull request merged**
