### PR TITLE
Cooler couleurs take 3

### PR DESCRIPTION
**Pull request by adriaanm**
rereredid #2350

### CODE REVIEW

**Comment by adriaanm** [comment]
I'm just going to go ahead and merge this in before it goes stale; looks all green to me.

I'll clean up @paulp's mess with the partest classpath variable in a follow-up PR.

**Comment by som-snytt** [comment]
OMG, did u just merge?!  I thought maybe we could have a merge party on the one-yr anniversary of @paulp 's original branch.

Just kidding. Thanks, I'm going to pull right now and try it out.

**Comment by adriaanm** [comment]
Happy to revert and re-merge on the appropriate date.

**Comment by adriaanm** [comment]
Looks like we should've waited for the anniversary: https://scala-webapps.epfl.ch/jenkins/view/Enabled%20Scala%20jobs/job/scala-nightly-windows/1787/console

Not sure why this started happening.

**Comment by som-snytt** [comment]
That looks familiar, was it mixing java6+7? Don't quote me.  I'm heading out to pick up daughter, I'll think about it.

**Comment by xeno-by** [comment]
@som-snytt @paulp What's up with your new avatars?

**Comment by paulp** [comment]
@xeno-by um, good question. We're not exactly alone though, I see even scala is sporting some squares.

**Comment by retronym** [comment]
https://github.com/blog/1586-identicons

**Comment by som-snytt** [comment]
That is how we look to Google glasses.  If someone wearing them passes you on the sidewalk, it is updated automatically.

Apparently, at that resolution, I look like `Kilroy was here`.

**Pull request merged**
