### PR TITLE
Changed implementation comments from /** */ to /* */ for ScalaDoc

### PR DESCRIPTION
**Pull request by smessmer**
There were some comments saying "overridden for efficiency" in /*\* */ brackets
which then were shown in ScalaDoc as documentation for the function.

I changed them to /\* */

### CODE REVIEW

**Comment by jsuereth** [comment]
This LGTM -

Note, Have you signed the Scala CLA?  I hate to ask for simple fixes like this, but I wasn't sure.

Thanks for the fix!

**Comment by smessmer** [comment]
Didn't know I have to sign something. I now did and just sent the PDF to danielle.chamberlain@epfl.ch

Furthermore, this Pull Request should not only be merged into 2.10.x, but also into the other branches. Should I create several pull requests then?

**Comment by gkossakowski** [comment]
@smessmer: Thanks. We'll contact Danielle on Monday.

When it comes to other branches which do you have in mind? We constantly merge things from to 2.10.x to master. I don't know about 2.9.x, though.

**Comment by smessmer** [comment]
It also affects 2.9.x but I'm not sure about how you handle branching.
(By the way - is there a developer introduction on how to use the git repository, i.e. when to merge to which branch?)

**Comment by gkossakowski** [comment]
I got an email from Danielle confirming that CLA is on file. Merging it.

**Comment by gkossakowski** [comment]
@smessmer: Please reopen it against 2.9.x branch as well.

We don't have a good guide yet because our process has been a bit fluid. Once 2.10.0 is out we'll be working on polishing and documenting it. As for now we are still learning what's the best process we want to settle down on.

**Pull request merged**
