### PR TITLE
tags for AnyVal and AnyRef

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @odersky

**Comment by adriaanm** [comment]
Started jenkins job pr-scala-testsuite-linux-opt at https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-testsuite-linux-opt/412/

**Comment by xeno-by** [comment]
LGTM'd by Martin as per https://github.com/scalamacros/kepler/commit/f7808738698132f26270b75ee01ae8d5a7e0a2e7#commitcomment-1538863

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
