### PR TITLE
Avoid byte array allocation for non-vanilla source files

### PR DESCRIPTION
**Pull request by retronym**
References https://github.com/sbt/zinc/issues/770

### CODE REVIEW

**Comment by retronym** [comment]
There's a disk full / In Jenkins-ville.

**Comment by retronym** [comment]
```
Running on jenkins-worker-behemoth-1 in /home/jenkins/workspace/scala-2.12.x-validate-main@2
[Pipeline] stage
[Pipeline] { (test-ide)
[Pipeline] {
[Pipeline] echo
Starting stage test-ide to run scripts/jobs/integrate/ide on jenkins-worker-behemoth-1@0 in /home/jenkins/workspace/scala-2.12.x-validate-main
[Pipeline] stage
[Pipeline] { (test)
[Pipeline] checkout
No credentials specified
Fetching changes from the remote Git repository
[Pipeline] echo
Starting stage test to run scripts/jobs/validate/test on jenkins-worker-behemoth-1@1 in /home/jenkins/workspace/scala-2.12.x-validate-main@2
ERROR: Error fetching remote repo 'scala'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/scala/scala.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:909)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.plugins.git.GitException: Command "git config remote.scala.url https://github.com/scala/scala.git" returned status code 255:
stdout: 
stderr: error: could not lock config file .git/config: No space left on device
```

```
$ssh jenkins-master
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           799M   84M  716M  11% /run
/dev/xvda1      7.9G  4.6G  2.9G  62% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/xvdj        99G   77G   17G  83% /var/lib/jenkins
/dev/xvdk       493G  370G  101G  79% /var/opt/jfrog/artifactory/data
tmpfs           799M     0  799M   0% /run/user/1003
tmpfs           799M     0  799M   0% /run/user/1002
tmpfs           799M     0  799M   0% /run/user/1000
```

```
$ ssh jenkins-worker-behemoth-1
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
ssh 
udev            7.4G     0  7.4G   0% /dev
tmpfs           1.5G   12M  1.5G   1% /run
/dev/xvda1      7.9G  3.5G  4.0G  47% /
tmpfs           7.4G     0  7.4G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.4G     0  7.4G   0% /sys/fs/cgroup
/dev/xvdj       393G  267G  107G  72% /home/jenkins
tmpfs           1.5G     0  1.5G   0% /run/user/1001
```

**Comment by SethTisue** [comment]
> There's a disk full / In Jenkins-ville

I blew away a bunch of stuff on jenkins-worker-behemoth-1, should be okay now

**Review by diesalbla — APPROVED** [review]

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
