### PR TITLE
remove -Xstrict-inference

### PR DESCRIPTION
**Pull request by SethTisue**
"-Xstrict-inference was intended only as a coarse hacky start",
says Paul at https://github.com/scala/bug/issues/6680#issuecomment-292414918

GitHub search shows very few uses in the wild.  My best is that a few
people just enabled it because the name/description made it sound
good/safer.

### CODE REVIEW

**Comment by SethTisue** [comment]
this really should have been a `-Y` flag, so this falls under https://github.com/scala/scala-dev/issues/430 IMO

**Comment by S11001001** [comment]
I can't speak for other avoidance of it, but I never enabled it in any project I touched because I immediately encountered (and reported) serious bugs with it that made it effectively unusable for typing my code. That sort of thing may be a factor in its rarity of occurrence.

**Comment by adriaanm** [comment]
This change is already part of https://github.com/scala/scala/pull/6505/files#diff-3da64c3c223da7bbf9970ac26f9fb9b8L144

**Comment by SethTisue** [comment]
okay, I'll assume #6505 will go forward.

thanks Stephen for the confirmation.

**Pull request closed without merging**
