### PR TITLE
Carve up Types.scala

### PR DESCRIPTION
**Pull request by retronym**
Step one of a plan to bring some order and thread
safety to this neck of the woods.

More info:

  https://gist.github.com/retronym/5081754
  https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/MOvmcnbyb_g

Review by @lrytz @paulp

### CODE REVIEW

**Comment by retronym** [comment]
I'll submit a backport of this to `2.10.x` in day or two.

**Comment by paulp** [comment]
LGTM. I was going to suggest making a package just to feel useful, then saw you'd already done even that, robbing me of my token contribution.

**Comment by retronym** [comment]
Do you see a problem with a trait `Types` sitting beside the package of the same name?

**Comment by paulp** [comment]
@retronym It's definitely a problem; unfortunately it is a problem we already have in a bunch of other places (e.g. scala.collection.parallel / Parallel.) I hope at some point to at least warn about it. To future proof, yes, it would be best not to do that.

**Comment by gkossakowski** [comment]
@retronym: is there any particular reason why you cannot submit this against 2.10.x and handle merge conflict in master?

**Comment by retronym** [comment]
I'm basically just trying to get two patches in line that have the same change. The nature of the change makes normal merging pretty useless, instead its a matter of carefully replaying the steps on the 2.10.x branch. I don't really mind how we get them both merged, but I find it easier to think about them separately.

**Pull request merged**
