### PR TITLE
Add explicit result type to some non-private methods

### PR DESCRIPTION
**Pull request by nicolasstucki**
Add explicit result type to methods where Scala 2 and Scala 3 disagree with the inferred type. The aim is to have the same type in the Scala 2 pickles and the Scala 3 TASTy.

These where identified in https://github.com/lampepfl/dotty/pull/17975

### CODE REVIEW

**Comment by som-snytt** [comment]
I wonder if `-Xsource:3` would have agreed.

**Comment by nicolasstucki** [comment]
> I wonder if -Xsource:3 would have agreed.

I did not try that. Not sure how.

I identified them using TASTy MiMa.

**Comment by som-snytt** [comment]
I see `-Xsource:3` does infer the overridden types, but for bincompat the explicit narrow types are required, presumably.

Also because `sys.process` package object extends a trait, I learned you can't `@nowarn` a `package object`, it must be a `object package`, at least in Scala 2.

**Comment by nicolasstucki** [comment]
I did not include the explicit types for `scala.collection.[im]mutable.BitSet.bitSetFactory` from the original PR as TASTy MiMa complains for `scala.collection.mutable.BitSet.bitSetFactory`. This could be a false positive. I'll update those when I am sure they are correct.

**Review by lrytz — APPROVED** [review]
LGTM

**Comment by lrytz** [comment]
There's a similar case at https://github.com/scala/scala-xml/pull/655

Currently, `-Xsource:3` changes the way the compiler operates, but there are no warnigns emitted in either case. If someone wants to clean up their codebase and find all definitions that change under this condition, what can they do? Use MiMa?

I think a warning for this case under `-Xsource:3` would be good. @som-snytt wdyt?

```
➜ sandbox s

scala> trait A { def f: Object }; object B extends A { def f = "" }; B.f
val res0: String = ""


➜ sandbox s -Xsource:3

scala> trait A { def f: Object }; object B extends A { def f = "" }; B.f
val res0: Object = ""
```

**Comment by som-snytt** [comment]
@lrytz I'm about to try your other suggestion to make `-Xsource:3` migrations only warnings (for the quill explicit types issue), and I will include warning when inferred override changes.

**Comment by nicolasstucki** [comment]
Resoved a conflict in `JavaCollectionWrappers.scala`.

**Pull request merged**
