### PR TITLE
SI-6277 fix for isXXX methods in reflection

### PR DESCRIPTION
**Pull request by xeno-by**
The underlying problem is that some symbols require so-called initialization before certain methods (for example, the Symbol.isSealed method) return reliable results.

This doesn't bring much trouble in the compiler, because noone usually calls these methods before making sure that the symbol is initialized, but we cannot put this burden onto users of the reflection API.

Unfortunately we cannot just do automatic initialization in misbehaving methods, because that breaks the compiler, causing nasty cyclic reference errors. Quite probably this can be done, but not a few weeks before a major release.

Luckily there's a non-invasive fix. We can decorate runtime reflection symbols with a trait, which overrides the methods of interest and performs initialization prior to calling super. Then the compiler remains unaffected, and reflection users are happy.

---

The problem is that the cleanest implementation of the fix involves a de-optimization of the compiler (removal of final from Symbol.hasFlag and its buddies). 

There's also an alternative that requires some copy/paste and is more fragile (though the fragility is controlled by a unit test), but its performance characteristics are non-obvious.

Therefore I asked Greg to do performance testing, and these tests ended up with very controversial results. Greg reran the tests again, and the results are more realistic, though it's still unclear what to conclude:

**First test run**

```
[baseline] 630f1b4 minor cleanup for reflection
Vector_scala
Mean: 747.25ms ± 2.46ms (cov: 0.99%; 63:123)
scalap-src
Mean: 4317.65ms ± 13.60ms (cov: 0.95%; 35:95)

[approach #1] 6711d6e SI-6277 decorates runtime symbols with auto-init
Vector_scala
Mean: 783.92ms ± 2.59ms (cov: 0.99%; 69:129)
scalap-src
Mean: 4523.95ms ± 14.05ms (cov: 0.93%; 80:140)

[approach #2] 549267f an optimization for the previous commit
Vector_scala
Mean: 750.01ms ± 2.51ms (cov: 1.01%; 79:139)
scalap-src
Mean: 4262.53ms ± 14.12ms (cov: 1.00%; 40:100)
```

**Second test run**

```

[baseline] 630f1b4 minor cleanup for reflection
Vector_scala
Mean: 762.27ms ± 2.54ms (cov: 1.00%; 52:112)
scalap-src
Mean: 4249.28ms ± 13.90ms (cov: 0.98%; 34:94)

[approach #1] 6711d6e SI-6277 decorates runtime symbols with auto-init
Vector_scala
Mean: 797.82ms ± 2.50ms (cov: 0.94%; 58:118)
scalap-src
Mean: 4569.82ms ± 15.31ms (cov: 1.01%; 25:85)

[approach #2] 549267f an optimization for the previous commit
Vector_scala
Mean: 749.13ms ± 2.49ms (cov: 1.00%; 83:143)
scalap-src
Mean: 4321.25ms ± 14.20ms (cov: 0.99%; 34:94)
```

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @paulp @odersky @gkossakowski

**Comment by xeno-by** [comment]
My take on the results of the tests is that unfinalizing hasFlag is out of the question, and that the second approach is good enough to be merged.

**Comment by xeno-by** [comment]
Please, discuss, and in the meanwhile I'll rebase.

**Comment by xeno-by** [comment]
Oops I accidentally deleted the "started jenkins job pr-rangepos" kitteh message. Well anyways it didn't contain anything useful, since by the time kitteh started the pull request wasn't rebased yet.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
"This doesn't bring much trouble in the compiler, because noone usually calls these methods before making sure that the symbol is initialized, but we cannot put this burden onto users of the reflection API."

Yes it does, and no, people are not magic like that.  It is delusion that we get this right - or that a bunch of flesh and blood creatures each acting independently could ever get it right.  It's easy to demonstrate, as I have done before - log all calls to hasFlag and note what answer is given, and show them all at the end of the compiler run alongside what the answer should have been had it been initialized.

**Comment by paulp** [comment]
I think you should try throwing out all the synchronized traits, and writing all methods requiring synchronization like this:

```
abstract class Universe(final val needsSynchronization: Boolean) {  }
...
final def something () = {
  def impl() = { ... }

  if (needsSynchronization) synchronized(impl()) else impl()
}
```

I realize it would take some time, and with no certainty of paying off.  But my bet is that it will win in performance and it stands a better chance with correctness as well.

It would be awesome if we could macro our way to the different implementations, come to think of it.  But in the immediate term, we don't need it.

**Comment by xeno-by** [comment]
I'll try to do that in a follow-up pull request. In the meanwhile, I'm exploring your idea with `if (isCompilerUniverse)` in `hasFlag`.

**Comment by xeno-by** [comment]
@gkossakowski Could you please test the following three builds:
- `baseline`: [sources](https://github.com/scalamacros/kepler/commit/da3c5456d0d69ed20f1ba40cdb7b5efde9189d0b), [artifacts](http://scala-webapps.epfl.ch/artifacts-manual/da3c5456d0d69ed20f1ba40cdb7b5efde9189d0b/)
- `optimized #1`: [sources](https://github.com/scalamacros/kepler/commit/a62b5fc736fb578c965680fe39d26cd756cf310f), [artifacts](http://scala-webapps.epfl.ch/artifacts-manual/a62b5fc736fb578c965680fe39d26cd756cf310f/)
- `optimized #2`: [sources](https://github.com/scalamacros/kepler/commit/e0927ab531acbdbfb8ddf4715828d156ac3f1233), [artifacts](http://scala-webapps.epfl.ch/artifacts-manual/e0927ab531acbdbfb8ddf4715828d156ac3f1233/)

**Comment by gkossakowski** [comment]
@xeno-by: thanks for using jenkins job. It makes testing a lot easier for me (because I don't need to move files manually)! The tests are running now.

**Comment by gkossakowski** [comment]
I ran tests three times. Here are the results:

a62b5fc an optimization for the previous commit

```
Vector_scala
Mean: 736.28ms ± 2.47ms (cov: 1.01%; 81:141)
scalap-src
Mean: 4215.47ms ± 13.61ms (cov: 0.97%; 31:91)

Vector_scala
Mean: 727.73ms ± 2.40ms (cov: 0.99%; 77:137)
scalap-src
Mean: 4173.70ms ± 13.79ms (cov: 0.99%; 36:96)

Vector_scala
Mean: 719.27ms ± 2.41ms (cov: 1.01%; 76:136)
scalap-src
Mean: 4079.87ms ± 13.48ms (cov: 0.99%; 44:104)
```

da3c545 minor cleanup for reflection

```
Vector_scala
Mean: 727.07ms ± 2.63ms (cov: 1.09%; 86:146)
scalap-src
Mean: 4044.80ms ± 13.52ms (cov: 1.01%; 49:109)

Vector_scala
Mean: 722.38ms ± 2.41ms (cov: 1.00%; 71:131)
scalap-src
Mean: 4011.82ms ± 13.41ms (cov: 1.01%; 60:120)

Vector_scala
Mean: 700.02ms ± 2.34ms (cov: 1.00%; 79:139)
scalap-src
Mean: 4007.55ms ± 11.19ms (cov: 0.84%; 76:136)
```

e0927ab removes `@inline` annotations from flag-related methods

```
Vector_scala
Mean: 713.08ms ± 2.35ms (cov: 0.99%; 67:127)
scalap-src
Mean: 4159.5ms ± 13.93ms (cov: 1.01%; 36:96)

Vector_scala
Mean: 706.65ms ± 2.36ms (cov: 1.00%; 77:137)
scalap-src
Mean: 4117.28ms ± 13.59ms (cov: 0.99%; 61:121)

Vector_scala
Mean: 745.77ms ± 2.47ms (cov: 1.00%; 71:131)
scalap-src
Mean: 4183.13ms ± 13.60ms (cov: 0.98%; 31:91)
```

BTW. These results show perfectly how non-determinism of JIT...

**Comment by xeno-by** [comment]
How unlucky... All fixes noticeably degrade the performance.

Let's try something else:
- `baseline+`: [sources](https://github.com/scalamacros/kepler/commit/572b1e9480eaaa09d43dce76811d7383bb07beed), [artifacts](http://scala-webapps.epfl.ch/artifacts-manual/572b1e9480eaaa09d43dce76811d7383bb07beed/)
- `baseline++`: [sources](https://github.com/scalamacros/kepler/commit/5b38b42bc0632ce2c8680273f4dbbdb32a86297f), [artifacts](http://scala-webapps.epfl.ch/artifacts-manual/5b38b42bc0632ce2c8680273f4dbbdb32a86297f/)
- `optimized #0`: [sources](https://github.com/scalamacros/kepler/commit/375a85162b064c84d928b9c177610b096a9ce05e), [artifacts](http://scala-webapps.epfl.ch/artifacts-manual/375a85162b064c84d928b9c177610b096a9ce05e/)
- `something very different`: [sources](https://github.com/scalamacros/kepler/commit/2b78c5ae03a4124379cf18f2f767770ae8a3b17d), [artifacts](http://scala-webapps.epfl.ch/artifacts-manual/2b78c5ae03a4124379cf18f2f767770ae8a3b17d/)

NB! The builds are in progress and will be ready, I'd say, within 1-2 hours.
Upd. The builds are ready.

**Comment by gkossakowski** [comment]
Here the results:

572b1e9 fixes decorators for runtime reflection

```
Vector_scala
Mean: 734.92ms ± 2.44ms (cov: 1.00%; 81:141)
scalap-src
Mean: 4074.05ms ± 13.65ms (cov: 1.01%; 41:101)

Vector_scala
Mean: 745.93ms ± 2.43ms (cov: 0.98%; 54:114)
scalap-src
Mean: 4087.03ms ± 12.84ms (cov: 0.94%; 31:91)

Vector_scala
Mean: 736.35ms ± 2.45ms (cov: 1.00%; 80:140)
scalap-src
Mean: 4087.78ms ± 13.71ms (cov: 1.01%; 45:105)
```

5b38b42 distinguishes flag-agnostic completers

```
Vector_scala
Mean: 741.45ms ± 2.48ms (cov: 1.00%; 56:116)
scalap-src
Mean: 4105.53ms ± 13.52ms (cov: 0.99%; 50:110)

Vector_scala
Mean: 738.25ms ± 2.44ms (cov: 0.99%; 79:139)
scalap-src
Mean: 4098.65ms ± 12.81ms (cov: 0.94%; 31:91)

Vector_scala
Mean: 733.57ms ± 2.42ms (cov: 0.99%; 79:139)
scalap-src
Mean: 3999.25ms ± 13.26ms (cov: 1.00%; 74:134)
```

375a851 an original optimization

```
Vector_scala
Mean: 723.28ms ± 2.37ms (cov: 0.99%; 95:155)
scalap-src
Mean: 4139.18ms ± 13.68ms (cov: 0.99%; 37:97)

Vector_scala
Mean: 745.33ms ± 2.49ms (cov: 1.00%; 75:135)
scalap-src
Mean: 4149.33ms ± 13.54ms (cov: 0.98%; 30:90)

Vector_scala
Mean: 731.18ms ± 2.44ms (cov: 1.00%; 70:130)
scalap-src
Mean: 4041.20ms ± 12.82ms (cov: 0.95%; 43:103)
```

2b78c5a wip

```
Vector_scala
Mean: 728.18ms ± 2.40ms (cov: 0.99%; 99:159)
scalap-src
Mean: 4104.58ms ± 13.69ms (cov: 1.00%; 48:108)

Vector_scala
Mean: 729.50ms ± 2.41ms (cov: 0.99%; 73:133)
scalap-src
Mean: 4063.32ms ± 13.48ms (cov: 1.00%; 68:128)

Vector_scala
Mean: 696.30ms ± 1.50ms (cov: 0.65%; 128:188)
scalap-src
Mean: 4101.45ms ± 13.23ms (cov: 0.97%; 31:91)
```

**Comment by xeno-by** [comment]
I'll update the PR with an interpretation of these results today evening

**Comment by xeno-by** [comment]
Allrighty, so here's the summary of what I've tried. 

We start from a baseline at 4020 ms of scalap-src, and then have three options (some of the numbers are extrapolated from previous runs):
A) Decorate symbols + unfinalize and decorate getFlag = 4250 
B) Decorate symbols + finalize and don't decorate getFlag, but decorate isXXX instead = 4110
C) Don't decorate symbols + inject a lightweight check into getFlag = 4090

We've seen very well that JIT non-determinism can be wild, so these results should be taken with a grain of salt, but we can see the A is noticeably worse than both B and C, and B ≈ C. On the implementation side, personally I prefer C, because it doesn't require symbols being decorated, which means one less mechanism to break.

Therefore I propose to go for C, and will soon update the PR with corresponding commits.

upd. Unfortunately all known solutions to the bug at hand (A, B and C - all of those) introduce performance regressions. We're under severe time pressure, so there's no more time to explore. Therefore I suggest that it is reasonable to accept the 2% performance hit. According to Greg, we've just gained 6% from removing scala.reflect.base, and even before that we were well within our performance goal for 2.10.0-final.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
I think C is the runaway winner there.  And yes, you should get to apply some of the banked gain from eliminating the cake layer.

**Comment by xeno-by** [comment]
Shall we merge then?

**Comment by paulp** [comment]
It looks good enough to me, at least against the apparent constraints of doing something immediately and doing something about the initialization problem.

**Comment by xeno-by** [comment]
Great! Thank you very much for taking time to review.

**Pull request merged**
