### PR TITLE
move to latest Akka 2.3.x release

### PR DESCRIPTION
**Pull request by SethTisue**
Akka 2.3.15 was released in April 2016
http://akka.io/news/2016/04/01/akka-2.3.15-released.html

a similar previous PR was https://github.com/scala/scala/pull/5030

for 2.11.9. fyi @patriknw

### CODE REVIEW

**Comment by SethTisue** [comment]
haha so literally 1 minute after I submit this, I get a "Akka 2.3.16 released" email.

PR updated.

**Review by patriknw — COMMENTED** [review]
LGTM

**Comment by adriaanm** [comment]
/rebuild

Another appearance of https://github.com/scala/scala-dev/issues/251... We may need to get to the bottom of this before we can release 2.11.9...

**Comment by SethTisue** [comment]
checked just now, 2.3.16 is still current according to http://akka.io/docs/

**Pull request merged**
