### PR TITLE
Backport from paradise/macros

### PR DESCRIPTION
**Pull request by xeno-by**
review @paulp

Supersedes #1831

### CODE REVIEW

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Rebased against the updated `master`. Also, since we now have `c.introduceTopLevel`, unapply macro tests got an update.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Can one of the admins verify this patch?

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
rebased against `master`. PLS REBUILD ALL

**Comment by paulp** [comment]
Superseded by #1885.

**Pull request closed without merging**
