### PR TITLE
SI-8911  scala.collection.convert.Wrappers$MapWrapper not serializable

### PR DESCRIPTION
**Pull request by Ichoran**
Added `with Serializable` to `MapWrapper` and `SetWrapper`.

Test verifies that serialziation works in the simplest case.

### CODE REVIEW

**Comment by lrytz** [comment]
I think we should add an `@SerialVersionUID`, and maybe add the classes to https://github.com/scala/scala/blob/2.11.x/test/files/run/t8549.scala

**Comment by lrytz** [comment]
ping @Ichoran - do you agree we should add `@SerialVersionUID`s?

**Comment by Ichoran** [comment]
@lrytz - Yes, I agree.  I'll get to it this week.

**Comment by adriaanm** [comment]
Rex mentioned:

> [...] is it worth breaking binary compatibility in this case since it will, I think, only cause problems when serializing, and serialization is what's broken to begin with [...]

Note that this is causing trouble for Spark. /cc @pwendell

**Comment by Ichoran** [comment]
PLS REBUILD/pr-scala@5ceff5d9452d43c36c0f918b399a596fb9164d43

**Comment by pwendell** [comment]
Ping @joshrosen who reported this.

**Comment by Ichoran** [comment]
PLS REBUILD/pr-scala@5ceff5d9452d43c36c0f918b399a596fb9164d43

**Comment by JoshRosen** [comment]
To work around this issue, Spark uses its own modified copy of Scala's `MapWrapper` (see https://github.com/apache/spark/pull/3587 / [SPARK-3926](https://issues.apache.org/jira/browse/SPARK-3926)).  This patch won't eliminate the need for our own workaround, since we need to support Scala 2.10.x and 2.11.x, but it may help to avoid some pain for future application and library developers who write Scala libraries and use them from Java.

**Comment by adriaanm** [comment]
I'm going to close this PR so that we can retire the old build bot. For the new PR, please rephrase the commit title as an action on the codebase or a bullet item in the release notes ("SI-8911 allow serializing Scala Maps wrapped as Java ones")

**Pull request closed without merging**
