### PR TITLE
Added lock by default and did a minor amount of cleanup.  More to come h...

### PR DESCRIPTION
**Pull request by jsuereth**
...opefully.

This one gives a shout-out to @adriaanm who promised me cookies for this feature.

### CODE REVIEW

**Comment by adriaanm** [comment]
Retrying at https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-testsuite-linux-opt/160/console.
No idea what could've caused the failure.

This reminds me: would be nice to grep all build logs for a similar failure.

**Comment by adriaanm** [comment]
the retry built fine -- we should probably figure out a more convenient way to figure out why that happened,
but with the current jenkins interface, it's very tedious to know which commits differ between different builds

**Comment by adriaanm** [comment]
LGTM, except for the whitespace rule violations. One less cookie for you, young man.

**Comment by jsuereth** [comment]
Where's the whitespace rule violation?

**Comment by adriaanm** [comment]
X marks the spots

``` scala
+    val autoLockSettings: Seq[Setting[_]] =X
+      if(autoLock) Seq(compile in Compile <<= (compile in Compile, lock) apply { (c, l) =>X 
+        c flatMapR { cResult =>
+          val result = Result.tryValue(cResult)
+          l mapR { tx => result }
+        }
+      })X
```

**Pull request merged**
