### PR TITLE
Backport from paradise/macros

### PR DESCRIPTION
**Pull request by xeno-by**
Applies improvements to the macro engine from paradise/macros
to provide robustness and uniformity to different entrances of macro
expansion + to prepare for the unavoidable typemacro merge!

### CODE REVIEW

**Comment by xeno-by** [comment]
Follow-up for https://github.com/scala/scala/pull/1813, review @paulp.

It was a huge surprise for me to find out that https://issues.scala-lang.org/browse/SI-5903 doesn't need to be fixed at all, i.e. no changes are required for extractor macros to work. I swear that our prototype of quasiquote pattern matching didn't work without a typer patch for extractor macros (or so it seemed to us back then), but luckily the final revision works fine as is. See the comment in JIRA for more information.

However the idea of backporting as much stuff as possible from `paradise/macros` is a good one, and I'm glad to realize it here.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
rebased against `master`. PLS REBUILD ALL.

**Comment by xeno-by** [comment]
A spurious abort. PLS REBUILD ALL

**Comment by paulp** [comment]
I try not to ask for too much busywork of this kind, but I would like to see this as smaller commits before I try to review it.

**Comment by xeno-by** [comment]
Will do. Hopefully this year

**Pull request closed without merging**
