### PR TITLE
SI-8131 fixes residual race condition in runtime reflection

### PR DESCRIPTION
**Pull request by xeno-by**
review @retronym

### CODE REVIEW

**Comment by retronym** [comment]
```
qbin/scalac test/files/run/reflection-sync-potpourri.scala && (for i in {1..100}; do parallel -j 50 qbin/scala -J-Xmx1G Test ::: {1..10} || break; printf . ;done)
.......Exception in thread "Reflector-796" scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving trait Annotation
    at scala.reflect.internal.Symbols$Symbol$$anonfun$info$3.apply(Symbols.scala:1370)
    at scala.reflect.internal.Symbols$Symbol$$anonfun$info$3.apply(Symbols.scala:1368)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.reflect.internal.Symbols$Symbol.lock(Symbols.scala:489)
    at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1368)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:171)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:132)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:132)
    at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
    at scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:11)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:128)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:171)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:132)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.info(SynchronizedSymbols.scala:171)
    at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1528)
    at scala.reflect.internal.Definitions$DefinitionsClass.fullyInitializeSymbol(Definitions.scala:193)
    at scala.reflect.internal.Symbols$SymbolContextApiImpl.typeSignature(Symbols.scala:120)
    at scala.reflect.internal.Symbols$SymbolContextApiImpl.typeSignature(Symbols.scala:80)
    at Test$.force(reflection-sync-potpourri.scala:19)
    at Test$$anonfun$6$$anon$1$$anonfun$7.apply(reflection-sync-potpourri.scala:26)
    at Test$$anonfun$6$$anon$1$$anonfun$7.apply(reflection-sync-potpourri.scala:26)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.immutable.List.foreach(List.scala:302)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at Test$$anonfun$6$$anon$1.run(reflection-sync-potpourri.scala:26)
```

**Comment by xeno-by** [comment]
@retronym What about now?

**Comment by retronym** [comment]
Same result:

```
% git show --oneline --shortstat
22356a2 ensures that runtime reflection symbols are thread-safe
 2 files changed, 6 insertions(+)

% qbin/scalac test/files/run/reflection-sync-potpourri.scala && (for i in {1..100}; do parallel -j 50 qbin/scala -J-Xmx1G Test ::: {1..10} || break; printf . ;done)
........................Exception in thread "Reflector-992" scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving trait Annotation
    at scala.reflect.internal.Symbols$Symbol$$anonfun$info$3.apply(Symbols.scala:1370)
```

**Comment by xeno-by** [comment]
Oh God, I reproduced it on my laptop!!! It looks like -Xmx is the key here - one of my scripts was hijacking it before, and now after I fixed that everything started crashing. Pure joy!

**Comment by xeno-by** [comment]
Thank you Jason for all your patience!

**Comment by retronym** [comment]
I suspect the problem is that even though `_initializationStatus` is volatile, that doesn't help when you read it, decide to do something, then write back the current thread id. Two threads could evaluate `_initializationStatus == -1L` as `true` and then proceed as though they own the symbol.

**Comment by retronym** [comment]
The use of `Thread.currentThread.getId` looks pretty dodgy to me; it suggests we should to use something out of j.u.concurrent.

**Comment by xeno-by** [comment]
@retronym Writes to volatile vars are protected by the GIL. So even though multiple threads can simultaneously decide to initialize a symbol, only one of them will actually get to doing that.

**Comment by retronym** [comment]
BTW, I can't provoke a race under the pessimistic:

``` scala
    def gilSynchronizedIfNotThreadsafe[T](body: => T): T = {
      if (isCompilerUniverse) body
      else gilSynchronized { body }
    }
```

Which is at least an improvement over the status quo.

**Comment by retronym** [comment]
When we first discussed this fix, I remember we sketched out:

``` scala
   def markAllCompleted =  isInitialized = true
   @volatile var isInitialized = false
    def gilSynchronizedIfNotThreadsafe[T](body: => T): T = {
      if (isCompilerUniverse || isInitialized) body
      else gilSynchronized { body }
    }
```

Could you motivate your patch as compared to this idea?

**Comment by xeno-by** [comment]
@retronym Well, it's roughly the same, but complicated by the need for isInitialized to serve as a switch for auto-initialization of flags, privateWithin, annotations, etc. 

Especially the flags are a problem, because, depending on the completer, certain flags may or may not be definitively assigned even before isInitialized is true. Therefore we need to track the mask of initialized flags on per-completer (i.e. per-symbol basis), which makes us introduce `markFlagsCompleted` along with `markAllCompleted`.

`markBeingCompleted` might actually be unnecessary. I remember clearly needing it when I started working on this patch, but now in retrospect I can't remember why exactly. After I fix the current problem, I'll try to remove it and see what changes.

**Comment by xeno-by** [comment]
Closing for now

**Comment by som-snytt** [comment]
> Thank you Jason for all your patience!

+1 for us all.

**Pull request closed without merging**
