### PR TITLE
Added mapAll which will map/recover in a single PF

### PR DESCRIPTION
**Pull request by sksamuel**

### CODE REVIEW

**Comment by sksamuel** [comment]
PLS REBUILD/pr-scala@25f703d

**Comment by retronym** [comment]
Could you please coordinate this proposed change with the in-progress discussions to extend the Futures API

https://groups.google.com/forum/#!topic/scala-sips/4LIO5NpXYaE
https://docs.google.com/document/d/1Vza2-B3FzgtleX8RNs6rqRbhOn9jotrUfFB77h0DIGU/edit

See also:

https://groups.google.com/forum/#!topic/scala-sips/qi9X_E0FiEg

ping @viktorklang @richdougherty who might be more aware of that status of those discussions than me.

I will close this PR for now, in the interests of batching the API enhancements to Futures up a little bit to end up with a more coherent design.

**Comment by Ichoran** [comment]
I don't think the name is advisable, given that a partial function is perfectly free to map far less than "all".  It could cover less than either recover or map do.

**Comment by sksamuel** [comment]
That makes sense. We a new name then :)

**Comment by viktorklang** [comment]
See my work-in-progress for a SIP-14 update here: https://github.com/viktorklang/scala/pull/6

**Pull request closed without merging**
