### PR TITLE
Issue/5031

### PR DESCRIPTION
**Pull request by jsuereth**
Resubmit of PR #1208

@paulp gave me his personal approval for this patch, since he wrote it.  The only new thing added is ordering of partest files so that we beat cross-platform issues.

No further review needed, but if @phaller or @lrytz want to look at the partest fix, feel free.  It's two lines.

### CODE REVIEW

**Comment by lrytz** [comment]
do all of these commits pass the build? otherwise some rebasing should be applied.

**Comment by jsuereth** [comment]
No....  I'll rebase and push shortly

**Comment by jsuereth** [comment]
Also, I apologize for the oversight.   Being in a rush doesn't justify a bad patch

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
OK, should be good.  @lrytz any comments on largest fix?   The rest had a lgtm previously.

**Comment by lrytz** [comment]
lgtm, thanks

**Pull request merged**
