### PR TITLE
SI-7690 ghost error message fails compile [Rebase of #2763]

### PR DESCRIPTION
**Pull request by adriaanm**
[Rebase of #2763]

I won't even try to explain the error reporting code, because
it would have no basis in reality. However this change appears
to fix the symptom reported.

### CODE REVIEW

**Comment by adriaanm** [comment]
Botched the rebase, it seems.

**Comment by paulp** [comment]
LGTM

**Comment by adriaanm** [comment]
@paulp, `pos/t7690.scala` is failing in #2823 (and #2821). Both are based on this PR and seem unrelated. Is this test deterministic?

```
g log --oneline scala/pr/2804..scala/pr/2823
67d94f681f (scala/pr/2823) SI-7715 String inpatternation s"$_" for s"${_}"
```

**Comment by adriaanm** [comment]
Test suite logs: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-test/583/, https://scala-webapps.epfl.ch/jenkins/job/pr-scala-test/580

**Comment by adriaanm** [comment]
(Note: I've tried running it under heavy load locally and couldn't make the test fail.)

**Comment by paulp** [comment]
t7690.scala is going to be the world's best canary for, well, not anything being wrong, just anything changing. I think it's deterministic as long as the compiler doesn't change. As long as "correct" behavior depends on things like "has anything looked at the info of some symbol", then there will be stuff like this. I don't know what to do about it.

**Comment by adriaanm** [comment]
it looks like either #2797 or #2812 broke it, as those got merged between this pr and when validation was run for #2823

**Comment by paulp** [comment]
I'll be surprised if it's either of those - both look near-impossible. I almost think it's more likely #2821 and #2823 each induced the same failure independently. But I guess there's only way to find out.

**Comment by paulp** [comment]
Regardless, I absolutely cannot fix it. As you can see from the content of the commit which accompanied t7690.scala, I have _no idea_ how to handle the error reporting nondeterminism. As I said somewhere else as well, it is as big a single factor as anything else why I'm moving on.

**Comment by adriaanm** [comment]
Sure, I understand -- I'm on it. Consider all this FYI. The plot thickens. Same PR, different test runs: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-test/570/consoleText v https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-test/583/consoleText

**Comment by paulp** [comment]
Do pos tests get a completely brand new fresh compiler? The slightest deviation from that would be enough.

**Comment by adriaanm** [comment]
It was something along those lines. Explanation on scala-internals. About 1" away from reverting to the old PR validation jobs... We'd need the distpack validation job to propagate the sha of the master ref so that the downstream jobs can use the same one.

**Comment by som-snytt** [comment]
The pos tests must be run in separate rooms, preferably with sheathing.  Did you order the lead sheathing?  I know you're not running pos and neg together, right?  Because obviously they cancel each other out.  And they have to be carefully calibrated or else they'll cause disk errors. And don't even try running partest during the perseid meteor storm.

**Pull request merged**
