### PR TITLE
Dist cleanup

### PR DESCRIPTION
**Pull request by adriaanm**
1. Figured out why we were packaging extraneous jars.
2. Removed <distributionManagement> from POMs. I could close the staged repo without the distributionManagement tag, and all the docs I've seen indicate it's a maven-publishing-client kind of thing (not necessary for publishing to maven central).

Review by @jsuereth (not urgent)

### CODE REVIEW

**Comment by adriaanm** [comment]
ping @jsuereth, just making sure distributionManagement isn't actually needed to satisfy some weird maven policy -- verified I can still publish :)

**Comment by retronym** [comment]
http://jroller.com/holy/entry/releasing_a_project_to_maven

> B. Deploying Manually
> [...]
> In this case you do not need the distributionManagement section in your pom.xml (because you're providing all the information on the command line) but you still need to provide your login and password for the target repository (option -DrepositoryId=...) in your settings.xml as described above.

**Comment by retronym** [comment]
LGTM

**Comment by adriaanm** [comment]
Thanks, Jason.

**Pull request merged**
