### PR TITLE
Add Iterator.duplicate from 2.12.x

### PR DESCRIPTION
**Pull request by szeiger**
It was probably omitted earlier because the implementation needs mutable.Queue which was a very late addition to the new collections implementation.

Fixes https://github.com/scala/collection-strawman/issues/563.

In find the equality semantics and synchronization questionable and would leave out both in a greenfield design but it's probably not worth breaking compatibility in subtle ways now.

### CODE REVIEW

**Comment by SethTisue** [comment]
rebasing onto current 2.13.x will pull in #6575 and #6548 which should make the failure go away

**Review by julienrf — APPROVED** [review]

**Comment by lrytz** [comment]
(@julienrf feel free to hit "Merge" yourself!)

**Pull request merged**
