### PR TITLE
SI-6807 Deprecating the Actors library.

### PR DESCRIPTION
**Pull request by vjovanov**
All public classes, traits and objects marked as deprecated.
Added deprecation note on the package object.
Embedded external libraries (ThreadPool etc.) are not deprecated as they are intended for internal use only.

Review by: @phaller

### CODE REVIEW

**Comment by phaller** [comment]
Will have another look at it tomorrow

**Comment by JamesIry** [comment]
ping @phaller

**Comment by JamesIry** [comment]
ping @phaller

**Comment by phaller** [comment]
LGTM

**Pull request merged**
