### PR TITLE
SI-6406 Restore deprecated API

### PR DESCRIPTION
**Pull request by som-snytt**
The original patch for SI-6406 was intended for 2.10 but during
those volatile weeks of early autumn, it missed the boat.

A deprecated method was incorrectly tagged at 2.10 and later
removed; this restores the method and its test, and resets
the deprecation clock to 2.11.

The deprecation tool should confirm that changes occur on the
git timeline as claimed.

This partially reverts f931833df8cc69d119f636d8a553941bf7ce2349.

Review by @soc aka The Scourge of Deprecation

### CODE REVIEW

**Comment by huitseeker** [comment]
LGTM!

**Comment by adriaanm** [comment]
@soc, it'd be nice to get this into 2.11.0-M3, but that requires merging this by Friday
Could you please have a look?

**Comment by soc** [comment]
Yes, sure! It LGTM.

**Comment by adriaanm** [comment]
Thanks

**Pull request merged**
