### PR TITLE
Fixes SI-5031 for separate compilation scenario.

### PR DESCRIPTION
**Pull request by hubertp**
When you have a conflicting member in package object and normal package that share the same namespace we remove the latter ClassSymbol from the scope. Now, this has an unpleasant consequence that companionClass/companionModule/companionSymbol no longer work correctly as they rely on finding the correspondent symbol using decls of the owner.
This fixes the problem of SI-5031 for separate compilation. Why the above change matters for finding foo.bar.Foo? Because when parsing the class we needed information about the static module (and we have the correct module symbol when completing the info). It's just that 043ce6d0565c9d5d960 relied on no longer valid assumptions. So we were getting NoSymbol and sym.exist was failing.

Obviously a more complete solution would be better if we didn't rely on the scope but that's too big to change for 2.10.0.

Already discussed with @odersky, but it would be great to get a quick lgtm.

### CODE REVIEW

**Comment by hubertp** [comment]
Looks like one of those spurious random errors that haunts us from time to time. Tests are ok.

**Comment by adriaanm** [comment]
it was said during the meeting this reverts something -- can you pinpoint the commit?

**Comment by hubertp** [comment]
043ce6d0565c9d5d960. It's mentioned in the commit message.

**Comment by paulp** [comment]
You mean, it reverts that one line from that commit, right? I think of "reverting" as "wholesale reversal". This pull request with its laser-focused one-line reversion LGTM.

**Comment by hubertp** [comment]
Yes. I tried to look for similar usage but nothing else looks fishy to me.

**Pull request merged**
