### PR TITLE
Include scalap in the distro.

### PR DESCRIPTION
**Pull request by adriaanm**
I guess that shows how often this is used. No tweets complaining about it missing so far, but let's keep it in the distribution.

Review by @lrytz.

### CODE REVIEW

**Comment by lrytz** [comment]
LGTM - we should find a way to catch such issues.

**Comment by gkossakowski** [comment]
I think there are two orthogonal ways to address such issues:
- reduce number of things we maintain to things that people really need and use (we are doing that already)
- test, test, test

I think we've learnt the right reflex that we don't accept anything new without tests. If the runner for scalap was written in 2014 I'm pretty sure we would have a basic test for it.

**Comment by adriaanm** [comment]
I think the way to go is to add some smoke testing to the release build. Run all the command line tools. Compile a program that touches something from all included jars.

**Comment by lrytz** [comment]
I'm still unfamiliar with the release build process - but that shall change, since 2.11.2 is on my task list. I'll add such a test when working on that. In case it's clear for you where the test should go, i'd be glad for a hint.

**Comment by adriaanm** [comment]
That would be süper! I would make a new downstream job from https://scala-webapps.epfl.ch/jenkins/job/scala-release-2.11.x-dist/

**Pull request merged**
