### PR TITLE
Fix for SI-6357, cycle with value classes.

### PR DESCRIPTION
**Pull request by paulp**
Don't force the owner info.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @harrah

**Comment by paulp** [comment]
Review by @adriaanm

**Comment by harrah** [comment]
Sorry, forgot about this one.  This patch fixes the original problem as well as a crasher from @dotta on scala-internals.  I can't comment on whether it looks like the right fix internally, but the results LGTM.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
