### PR TITLE
Extend named tuple aliases up to 22.

### PR DESCRIPTION
**Pull request by szeiger**
See https://groups.google.com/forum/#!topic/scala-internals/UCQBU-XPCy0
for a discussion about this exciting feature.

Review by @paulp (obviously).

### CODE REVIEW

**Comment by retronym** [comment]
Let's also include Pentuple, Hextuple and Undecuple as some people are probably more familiar with those.

**Comment by paulp** [comment]
To show the courage of their convictions, the companion objects should be expressed in terms of the alias, not the staid TupleNN name. Also +1 to jason's suggestions for additional ones. Certainly there was a time when my reaction would have been "what on earth is a Hendecuple" given that in the US the standard curriculum only includes Undecuple. It is potentially as confusing as expressing distance in "Meters".

Given those changes this LGTM.

**Comment by som-snytt** [comment]
I thought undecuple was when people reconcile after a trial separation.

**Comment by adriaanm** [comment]
Wait, what? I thought we were deprecating the Uples we had.

**Comment by paulp** [comment]
Moors, moors. So naive.

**Comment by adriaanm** [comment]
Don't forget "bushy-tailed".

**Comment by paulp** [comment]
Who could forget encountering something like that?

**Comment by JamesIry** [comment]
Merge pull request #3107 from szeiger/wip_tuplification …

**Comment by xeno-by** [comment]
Hey, what about classes for 1-tuple and 0-tuple? Except for that, I'm also tending to LGTM.

**Comment by paulp** [comment]
NEVER FORGET

**Comment by som-snytt** [comment]
@xeno-by I'm going to add aliases for `Nuple` and `Identuple` to my REPL startup script right now.  I also added a feature to REPL to generate a `Ruple`, where it loops creating an arbitrarily large tuple until you hit ^D.

**Pull request closed without merging**
