### PR TITLE
fix typo in PartialFunction

### PR DESCRIPTION
**Pull request by Karl-WangSK**

### CODE REVIEW

**Comment by dwijnand** [comment]
It's not a typo, it's https://en.wikipedia.org/wiki/If_and_only_if

**Comment by martijnhoekstra** [comment]
While it's not a typo, it's redundant with "false otherwise".

**Comment by dwijnand** [comment]
Actually, true...  But "iff" seems more precise than "otherwise", but that might be just because the former is used in precise contexts.

**Comment by som-snytt** [comment]
It's redundant, but "false otherwise" is necessary to say it does not throw UntrueException otherwise. Therefore `iff` is spuriously precise.

**Comment by dwijnand** [comment]
```
* @return `'''true'''`, if `x` is in the domain of this function, `sys.exit(1)` otherwise.
```

**Comment by SethTisue** [comment]
@Karl-WangSK sorry, but Dale was just joking — it isn't actually appropriate to mention `sys.exit` here

as I understand it, the outcome of this discussion is that your original change, simply changing `iff` to `if`, was actually correct — just for a different reason than you initially thought

**Comment by Karl-WangSK** [comment]
> @Karl-WangSK sorry, but Dale was just joking — it isn't actually appropriate to mention `sys.exit` here
> 
> as I understand it, the outcome of this discussion is that your original change, simply changing `iff` to `if`, was actually correct — just for a different reason than you initially thought

^ ^

**Comment by som-snytt** [comment]
Happy Hackoween isn't for a few days yet, but I don't think it's too early for a t-shirt.

**Pull request closed without merging**
