### PR TITLE
Traverser and Pickler improvements.

### PR DESCRIPTION
**Pull request by paulp**
This is an improvement on #3019 which implements pickling and unpickling of Trees with Traversers rather than only describing the possibility.

### CODE REVIEW

**Comment by paulp** [comment]
#3019 was LGTMed from 1.5 locales and I believe this is a strict improvement, but review refresh by @retronym.

**Comment by paulp** [comment]
@retronym - @gkossakowski made a comment on -internals which sounded suspiciously like LGTM so I'm going to hear it that way unless you pipe up. You want source-to-source translation, this PR is your future friend.

**Comment by gkossakowski** [comment]
I like the direction of this PR but I didn't have time to review it thoroughly and I'd like to. I'll have time to do it tomorrow. Can we defer the merge until tomorrow?

**Comment by paulp** [comment]
Sure.

**Comment by paulp** [comment]
@gkossakowski If you're 8+ time zones ahead of me like I think you are, then tomorrow is today and today's almost over.

**Comment by gkossakowski** [comment]
@paulp: I had my head deep in M6 release process and circular dependencies. I didn't realize the whole day passed. I'm looking into this now.

**Comment by gkossakowski** [comment]
LGTM. Thanks!

I share @retronym's worry about pickling format being changed but it's only for trees so I hope we won't break the world. We'll see soon.

**Comment by paulp** [comment]
Thanks a lot.

For the next guy, there's a similar effort to be undertaken in having type traversal correspond to type pickling. That one will successfully break the world, and also requires a type traverser be written which hasn't been infiltrated by all manner of partially overlapping concerns in the way TypeMap has.

**Pull request merged**
