### PR TITLE
SI-8215: Document IllegalStateExceptions thrown by uninitialized MatchIterator from Regex (review by @heathermiller)

### PR DESCRIPTION
**Pull request by demobox**
Also cleans up a misaligned ASCII art class diagram which is duplicated by the Content Hierarchy anyway.

See https://groups.google.com/forum/#!topic/scala-language/2T2wKVQiyVg

### CODE REVIEW

**Comment by demobox** [comment]
Comments, screenshots and doc diff [here](https://github.com/demobox/scala/commit/cd0a216dae0b0cc3d345ecf2063360e048468278) (for 9956245) and [here](https://github.com/demobox/scala/commit/2621c41f24323241cd260a3b8accd9f7ec14ce28) (for 9c0ca62)

**Comment by demobox** [comment]
Output of `./tools/scaladoc-compare build/scaladoc-8215 build/scaladoc`:

```
build/scaladoc-8215/library/scala/util/matching/UnanchoredRegex.html.raw:
355,357c355
<  match, subgroups, etc. Attempting to retrieve information about a match before initializing
<  the iterator can result in java.lang.IllegalStateExceptions. See
<  scala.util.matching.Regex.MatchIterator for details.
---
>  match, subgroups, etc.



build/scaladoc-8215/library/scala/util/matching/Regex$$MatchIterator.html.raw:
18,23c18,19
<           A class to step through a sequence of regex matches. All methods inherited from scala.util.matching.Regex.MatchData will throw
<  an java.lang.IllegalStateException until the matcher is initialized by
<  calling hasNext or next() or causing these methods to be called, such as
<  by invoking toString or iterating through the iterator's elements.
<  Self TypeMatchIteratorSee alsojava.util.regex.Matcher
< 
---
>           A class to step through a sequence of regex matches
>  Self TypeMatchIterator



build/scaladoc-8215/library/scala/util/matching/Regex$.html.raw:
19,20c19,22
<  regex matches and helper objects.
< 
---
>  regex matches and helper objects. The class hierarchy
>  is as follows:MatchData
>          /      \
> MatchIterator  Match
105c107,108
<       A class to step through a sequence of regex matches.
---
>       A class to step through a sequence of regex matches
> 



build/scaladoc-8215/library/scala/util/matching/Regex.html.raw:
33,41c33
<  pattern match. Note that, when calling findAllIn, the resulting scala.util.matching.Regex.MatchIterator
<  needs to be initialized (by calling hasNext or next(), or causing these to be
<  called) before information about a match can be retrieved:<span class="kw">val</span> msg = <span class="lit">"I love Scala"</span>
< 
< <span class="cmt">// val start = " ".r.findAllIn(msg).start // throws an IllegalStateException</span>
< 
< <span class="kw">val</span> matches = <span class="lit">" "</span>.r.findAllIn(msg)
< matches.hasNext <span class="cmt">// initializes the matcher</span>
< <span class="kw">val</span> start = matches.start When Regex is used as an extractor in a pattern match, note that it
---
>  pattern match. Note, however, that when Regex is used as an extractor in a pattern match, it
439,441c431
<  match, subgroups, etc. Attempting to retrieve information about a match before initializing
<  the iterator can result in java.lang.IllegalStateExceptions. See
<  scala.util.matching.Regex.MatchIterator for details.
---
>  match, subgroups, etc.
```

**Comment by adriaanm** [comment]
Welcome, and thank you, @demobox! Please [sign the Scala CLA](http://typesafe.com/contribute/cla/scala)

**Comment by demobox** [comment]
> Please sign the Scala CLA

Will do. Thanks, @adriaanm! Any comments on the doc changes themselves..?

**Comment by demobox** [comment]
> Please sign the Scala CLA

"Thank you for signing the Typesafe CLA.

If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA."

**Comment by som-snytt** [comment]
Don't forget the release for when they write the "Scala Puzzlements" book, a copy on former trees of all the interesting conversations on Scala PRs.  Offhand, I don't recall if github gets a cut of that.  Did you know PR stands for "Puzzle Resolution"?

**Comment by demobox** [comment]
> Did you know PR stands for "Puzzle Resolution"?

They'd also make quite a nice Puzzler Repository, if that's the way we're thinking... ;-). Or perhaps better: "Puzzler Ramification"?

**Comment by adriaanm** [comment]
LGTM, though I'm sure the other reviewers will resolve to pitch in as well.

BTW, it's better to @-mention reviewers in the PR description, because github pings you every time a commit with your @name on it shuffles through the system (in other repos, on merges,...)

**Comment by demobox** [comment]
> BTW, it's better to @-mention reviewers in the PR description

Updated, thanks for the heads-up. Perhaps a good thing to clarify in the [PR policy](https://github.com/scala/scala/wiki/Pull-Request-Policy)?

**Comment by adriaanm** [comment]
> Updated, thanks for the heads-up. Perhaps a good thing to clarify in the PR policy?

[done](https://github.com/scala/scala/wiki/_compare/a884b97cb2db12eebb7ef4f7ad75a3c73e924c73...21c6f39662f47df4f063ecbabe58a1c6e7a8a3de)

**Comment by demobox** [comment]
> done

Thanks, @adriaanm!

**Pull request merged**
