### PR TITLE
SI-7289 Discard ill-kinded type constraints during inference

### PR DESCRIPTION
**Pull request by retronym**
Let's disect the reported test case.

Define the first implicit:

```
scala> trait Schtroumpf[T]
defined trait Schtroumpf

scala> implicit def schtroumpf[T, U <: Coll[T], Coll[X] <: Traversable[X]]
     |     (implicit minorSchtroumpf: Schtroumpf[T]): Schtroumpf[U] = ???
schtroumpf: [T, U <: Coll[T], Coll[X] <: Traversable[X]](implicit minorSchtroumpf: Schtroumpf[T])Schtroumpf[U]
```

Call it explicitly => kind error during type inference reported.

```
scala> schtroumpf(null): Schtroumpf[Int]
<console>:10: error: inferred kinds of the type arguments (Nothing,Int,Int) do not conform to the expected kinds of the type parameters (type T,type U,type Coll).
Int's type parameters do not match type Coll's expected parameters:
class Int has no type parameters, but type Coll has one
              schtroumpf(null): Schtroumpf[Int]
              ^
<console>:10: error: type mismatch;
 found   : Schtroumpf[U]
 required: Schtroumpf[Int]
              schtroumpf(null): Schtroumpf[Int]
                        ^
```

Add another implicit, and let implicit search weigh them up.

```
scala> implicitly[Schtroumpf[Int]]
<console>:10: error: diverging implicit expansion for type Schtroumpf[Int]
starting with method schtroumpf
              implicitly[Schtroumpf[Int]]
                        ^

scala> implicit val qoo = new Schtroumpf[Int]{}
qoo: Schtroumpf[Int] = $anon$1@c1b9b03

scala> implicitly[Schtroumpf[Int]]
<crash>
```

Implicit search compares the two in-scope implicits in `isStrictlyMoreSpecific`,
which constructs an existential type:

  type ET = Schtroumpf[U] forSome { type T; type U <: Coll[T]; type Coll[_] <: Traversable[_] }

A subsequent subtype check `ET <:< Schtroumpf[Int]` gets to `withTypeVars`, which
replaces the quantified types with type variables, checks conformance of that
substitued underlying type against `Schtroumpf[Int]`, and then tries to solve
the collected type constraints. The type var trace looks like:

```
[    create] ?T                       ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]] )
[    create] ?U                       ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]] )
[    create] ?Coll                    ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]] )
[   setInst] Nothing                  ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]], T=Nothing )
[   setInst] scala.collection.immutable.Nil.type( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]], U=scala.collection.immutable.Nil.type )
[   setInst] =?scala.collection.immutable.Nil.type( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]], Coll==?scala.collection.immutable.Nil.type )
[    create] ?T                       ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]] )
[   setInst] Int                      ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]], T=Int )
[    create] ?T                       ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]] )
[    create] ?U                       ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]] )
[    create] ?Coll                    ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]] )
[   setInst] Nothing                  ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]], T=Nothing )
[   setInst] Int                      ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]], U=Int )
[   setInst] =?Int                    ( In Test#schtroumpf[T,U <: Coll[T],Coll[_] <: Traversable[_]], Coll==?Int )
```

The problematic part is when `?Int` (the type var originated from `U`) is registered
as a lower bound for `Coll`. That happens in `solveOne`:

```
for (tparam2 <- tparams)
  tparam2.info.bounds.hi.dealias match {
    case TypeRef(_, `tparam`, _) =>
      log(s"$tvar addLoBound $tparam2.tpeHK.instantiateTypeParams($tparams, $tvars)")
      tvar addLoBound tparam2.tpeHK.instantiateTypeParams(tparams, tvars)
    case _ =>
  }
```

This commit changes `addHiBound` and `addLoBound` to discard non higher-kinded
bounds for higher-kinded type variables.

Review by @adriaanm

This is more of a review request than a pull request, I think more test cases are needed, and would appreciate your ideas there.

This didn't crash prior to c800d1fec (implicit search failure was correctly reported), but I don't know exactly why.

### CODE REVIEW

**Comment by paulp** [comment]
Here's a test for you. Whether it's doing the right thing, I leave to you...

```
object Test1 {
  trait Ext[T]

  implicit def f[A, Coll <: CC[A], CC[X] <: Traversable[X]](implicit xi: Ext[A]): Ext[Coll] = ???
  implicit val m: Ext[List[List[Int]]] = new Ext[List[List[Int]]]{}

  implicitly[Ext[List[Int]]]                    // fails - not found
  implicitly[Ext[List[List[Int]]]]              // compiles
  implicitly[Ext[List[List[List[Int]]]]]        // fails - not found

  // Making Ext[+T] incurs the same behavior as these.
  implicitly[Ext[_ <: List[Int]]]               // compiles
  implicitly[Ext[_ <: List[List[Int]]]]         // fails - ambiguous
  implicitly[Ext[_ <: List[List[List[Int]]]]]   // compiles

  // a.scala:7: error: could not find implicit value for parameter e: Test1.Ext[List[Int]]
  //   implicitly[Ext[List[Int]]]                // fails - not found
  //             ^
  // a.scala:9: error: could not find implicit value for parameter e: Test1.Ext[List[List[List[Int]]]]
  //   implicitly[Ext[List[List[List[Int]]]]]    // fails - not found
  //             ^
  // a.scala:12: error: ambiguous implicit values:
  //  both method f in object Test1 of type [A, Coll <: CC[A], CC[X] <: Traversable[X]](implicit xi: Test1.Ext[A])Test1.Ext[Coll]
  //  and value m in object Test1 of type => Test1.Ext[List[List[Int]]]
  //  match expected type Test1.Ext[_ <: List[List[Int]]]
  //   implicitly[Ext[_ <: List[List[Int]]]]          // fails - ambiguous
  //             ^
  // three errors found
}
```

**Comment by retronym** [comment]
@paulp Here's how that test goes with this patch:

``` scala
object Test1 {
  trait Ext[T]
  implicit def f[A, Coll <: CC[A], CC[X] <: Traversable[X]](implicit xi: Ext[A]): Ext[Coll] = ???
  implicit val m: Ext[List[List[Int]]] = new Ext[List[List[Int]]]{}

  implicitly[Ext[List[Int]]]                    // fails - not found
  implicitly[Ext[List[List[Int]]]]              // compiles
  implicitly[Ext[List[List[List[Int]]]]]        // fails - not found

  // Making Ext[+T] should incur the same behavior as these. (so says @paulp)
  implicitly[Ext[_ <: List[Int]]]               // compiles
  implicitly[Ext[_ <: List[List[Int]]]]         // fails - ambiguous
  implicitly[Ext[_ <: List[List[List[Int]]]]]   // compiles

  // But, we currently get:
  trait ExtCov[+T]
  implicitly[ExtCov[List[Int]]]                 // fails - not found
  implicitly[ExtCov[List[List[Int]]]]           // fails - not found
  implicitly[ExtCov[List[List[List[Int]]]]]     // fails - not found
}
```

**Comment by paulp** [comment]
That's weird, I had meant that to summarize the behavior with this patch. (Without this patch it just crashes.) I must have unintentionally and incorrectly extrapolated behavior.

**Comment by paulp** [comment]
@retronym But the idea that they SHOULD have the same behavior, although not what I set out to communicate, sounds right to me. Does "so says @paulp" imply you feel otherwise?

**Comment by retronym** [comment]
The only implication was that I hadn't formed an opinion of my own, and that I wanted to clarify what _your_ comment implied :)

**Comment by adriaanm** [comment]
sorry it took me so long, preparing a PR that extends `isRelatable` to take kind conformance into account:

```
    def isRelatable(tp: Type) = (
         shouldRepackType               // short circuit if we already know we've seen higher levels
      || !containsSkolemAboveLevel(tp)  // side-effects tracking boolean
      || enableTypeVarExperimentals     // -Xexperimental: always say we're relatable, track consequences
    ) && (
         !(isHigherKinded || tp.isHigherKinded)
      || kindsConform(List(typeSymbol), List(tp), NoPrefix, NoSymbol) //tp.prefix, tp.typeSymbol.owner)
    )
```

**Comment by adriaanm** [comment]
hmm, weird, i'm seeing the error in applyArgs in TypeVar, where I applied this patch

``` diff
-      else
-        throw new Error("Invalid type application in TypeVar: " + params + ", " + newArgs)
+      else {
+        val tv = TypeVar(typeSymbol)
+        tv.setInst(ErrorType)
+        tv
+      }
```

**Pull request closed without merging**
