### PR TITLE
sbt 1.7.1 (was 1.6.2)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
not for merge until sbt 1.7.0 final is available, but in the meantime let's see how CI likes it

**Comment by SethTisue** [comment]
CI likes it. closing for now, but I've set a private reminder to reopen it once sbt 1.7.0 final is available.

**Comment by SethTisue** [comment]
let's see how CI likes RC2...

**Comment by SethTisue** [comment]
CI likes it. closing again for now. fyi @eed3si9n

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
