### PR TITLE
SI-6856 Fix incorrect EBNF in comment in Parsers

### PR DESCRIPTION
**Pull request by retronym**
'&' isn't a prefix operator, perhaps to the chagrin of the C crowd.

### CODE REVIEW

**Comment by retronym** [comment]
Review by, erm, @densh.

**Comment by som-snytt** [comment]
LGTM

Was that formerly for, erm, `m _`?

as suggested in the old change log appendix. The same section where Adriaan gets a footnote.

**Comment by densh** [comment]
That line talks about unary operators. Are you sure that `&` can be used in unary position? Can you provide an example?

**Comment by soc** [comment]
```
class Foo { def unary_- = ???; def unary_& = ??? }
defined class Foo

scala> val f = new Foo
f: Foo = Foo@75ee2516

scala> -f
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
  at Foo.unary_$minus(<console>:8)
  ... 33 elided

scala> &f
<console>:8: error: not found: value &
              &f
              ^
```

Maybe it would make sense to reject `unary_X` named methods for symbols which are not allowed to be used in unary syntax?

**Comment by retronym** [comment]
That could be a rule in scala-abide, but there is nothing illegal about creating a method `unary_&`.

**Comment by retronym** [comment]
@densh This commit simply changes the syntax in the comment to reflect the spec + implementation.

**Comment by som-snytt** [comment]
@retronym I think you mean it reflects the spec `&` implementation.

**Comment by retronym** [comment]
:smile:

**Comment by densh** [comment]
Sorry but I'm not sure I understand how it this is correct reflection of the parser behaviour. That line enumerates all valid unary operators which are [enumerated here](https://github.com/scala/scala/blob/2.11.x/src/reflect/scala/reflect/internal/StdNames.scala#L842) and `&`  is definitely not one of them. Unless I'm missing some other meaning of `&` in infix position I believe this change is incorrect.

**Comment by densh** [comment]
I think I know why I'm so confused. The commit removes `&`, not adds it. LGTM

**Comment by retronym** [comment]
:smile: You can blame it on some temporary red/green colour blindness.

**Comment by lrytz** [comment]
Very funny that scalal once had `val f = &println`, i didn't remember. It was introduced in 2006 (https://github.com/scala/scala/commit/fde7c4cb46c91e05c7ff18a13d528e1b4a458422) and deprecated in 2007 (https://github.com/scala/scala/commit/e512079)

**Pull request merged**
