### PR TITLE
[resubmit] Experimental Single Abstract Method support (sammy meets world)

### PR DESCRIPTION
**Pull request by gkossakowski**
_This is resubmission of #3018 after merge conflict has been resolved._

Under `-Xexperimental`, `typedFunction` invokes `synthesizeSAMFunction` when the expected type for the function literal (`pt`) is not the built-in `FunctionN` type of the expected arity, but `pt` does have a SAM with the expected number of arguments.

`synthesizeSAMFunction` expands the following tree:

```
{ (p1: T1, ..., pN: TN) => body } : S
```

to:

```
{
 def apply$body(p1: T1, ..., pN: TN): T = body

 new S { def apply(p1: T1, ..., pN: TN): T = apply$body(p1,..., pN) }
}
```

The expansion assumes `S` (the expected type) defines a single abstract method (let's call that method `apply` for simplicity).
1. If `T` is not fully defined, it is inferred by type checking `def apply$body` without a result type before type checking the block. The method's inferred result type is used instead of `T`. [See test case](https://github.com/adriaanm/scala/blob/67062db57c1abef88e0049dac5d82d4f13375a48/test/files/pos/sammy_poly.scala)
2. To more easily enforce that `S`'s members are not in scope in `body`, that tree goes to the `apply$body` method that's outside the anonymous subclass of S. (The separate `apply$body` method simplifies the implementation of 1&2.) [See test case](https://github.com/adriaanm/scala/blob/67062db57c1abef88e0049dac5d82d4f13375a48/test/files/pos/sammy_scope.scala)
3. The following [restrictions](https://github.com/adriaanm/scala/commit/657e85fe2412cdadc5ee9dc348159b32dcdfcba7#diff-2b1bf15b53df94495f7155a69f822adeR727) apply to `S`:
   1. Its primary constructor (if any) must be public, no-args, not overloaded.
   2. S must have exactly one abstract member, its SAM
   3. SAM must take exactly one argument list
   4. SAM must be monomorphic

We may later relax these requirements to allow an implicit argument list, both on the constructor and the SAM. Could also let the SAM be polymorphic.

PS: We'll require `import language.sam` instead of `-Xexperimental`, as soon as the SIP is ready and there are more tests.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @retronym. This is identical to #3018 apart from the last commit which resolves the merge conflict against current master.

**Comment by gkossakowski** [comment]
@retronym: ping

The merge conflict was due to 83feb8609161bf19247a8a310f8c5a9e3d8469f5.

**Comment by retronym** [comment]
The merge looks correct.

LGTM

**Comment by gkossakowski** [comment]
Thanks!

**Comment by adriaanm** [comment]
Thanks!

**Comment by scottcarey** [comment]
> PS: We'll require import language.sam instead of -Xexperimental, as soon as the SIP is ready and there are more tests.

So, 'import language.sam' does not work on Scala 2.11.  I suppose the -Xexperimental part was not changed?  I can not find any info about this other than this PR, especially with respect to how to use it (via language import or experimental flag).  Any idea when it will be available by import?  2.12 (a long time from now) or 2.11.future (not too distant)?

**Comment by adriaanm** [comment]
It's available in 2.11.5-SNAPSHOT under -Xexperimental. Happy to hear about bugs! It [works for me ](https://github.com/adriaanm/talks/blob/master/scala-2.12-java8/devoxx%202014%20Scala%202.12%20and%20Java%208%20--%20more%20fun%20together.pdf) with the Java 8 Streams API except for a couple of rough edges around type inference because we do not support wildcard capture. Will be available under language flag in 2.12 but with same functionality.

**Comment by scottcarey** [comment]
Well, I'm not sure I'll enable -Xexperimental (and all the other undocumented stuff that may or may not turn on) on my builds for production code to test it out, and test whether or not it propagates through to everyone's development environments without issue. ScalaIDE is flaky enough as is.  

That is a lot more work than adding an import statement.
I'd happily import 'scala.language.experimental.sam' instead, and be forced to change the import statement once it was no longer experimental.

So far, its been easier to add some implicits for the SAM types I want.

**Comment by adriaanm** [comment]
Good to know, thanks for sharing your perspective. We're not ready to declare it non-experimental yet, though. We don't add new features to minor releases in any case.

**Comment by adriaanm** [comment]
We could expose it under an individual flag, say `-Xpreview-sip:24`?

**Comment by som-snytt** [comment]
+1. `-Ysip:24` is briefer.

**Comment by scottcarey** [comment]
That would work.  I'll still have to go through all of the development environment testing to ensure the flag works its way from maven through to the IDEs without manual intervention before pushing a change, but at least I would not need to wonder what else it enabled and it would be easier to explain and justify as a stand-alone item.

**Comment by scottcarey** [comment]
Sad news. 
ScalaIDE does not pick up the additional scalac arguments from the maven build, so although adding -Xexperimental to the build configuration allows for SAM typing to work with a command line build, it does not propagate to the IDE.   This means that every IDE developer would have to manually set -Xexperimental (or a new -Ysip:24) on all ~30 scala projects, one at a time, every time they re-imported the build configuration (~once a week).

As a result, until Scala IDE (and IntelliJ, which may or may not work as I have not tested) pick up the additional configuration flags automatically, setting this on non-sbt projects would probably get me hanged.  Of course, the non-sbt projects happen to be the java-scala hybrids, where this feature would be particularly useful.

I'll bring this up with the Scala IDE folk tomorrow, perhaps I'm missing something.

**Pull request merged**
