### PR TITLE
Merge 2.10.x/2.10.0-RC2 into master

### PR DESCRIPTION
**Pull request by paulp**
Based on #1574.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @jsuereth

**Comment by jsuereth** [comment]
I see you beat me to this :)

Seems we have a pretty spectacular merge-conflict-bug: 

```
  [partest] Log file '/localhome/jenkins/b/workspace/pr-scala-testsuite-linux-opt/test/files/run/deeps-run.log': 
  [partest] java.lang.NullPointerException
  [partest]     at scala.tools.nsc.backend.icode.TypeKinds$class.toTypeKind(TypeKinds.scala:378)
  [partest]     at scala.tools.nsc.backend.icode.ICodes.toTypeKind(ICodes.scala:20)
<snipped to protect innocent eyes/>
```

**Comment by paulp** [comment]
Strange, I thought I saw the tests pass. Maybe wrong window.

**Comment by paulp** [comment]
I've tried everything I can think of and I can't reproduce this.

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Not that I'm against trying again, but if two different jenkins runs failed the same way on the same test I believe it's a real bug, I just can't reproduce it on OSX (which I mention because it's the only difference I'm sure of.)

**Comment by paulp** [comment]
There's little question it's 8265175ecc

**Comment by paulp** [comment]
Okay, I guess there's some question since that commit isn't even in here.

**Comment by paulp** [comment]
This failure appears to have nothing to do with this merge.  One of the regular nightlies failed the same way.

**Comment by paulp** [comment]
Also I ran the tests again, all pass for me on test-opt.

**Comment by jsuereth** [comment]
Jason's patch is fixed, let's TRY AGAIN.

PLS REBUILD ALL

**Comment by paulp** [comment]
I don't know what the jenkins damage is, but it finished a while ago:

```
BUILD SUCCESSFUL
Total time: 39 minutes 19 seconds
Finished: SUCCESS
```

**Pull request merged**
