### PR TITLE
Hunting down eliminable :: allocations.

### PR DESCRIPTION
**Pull request by paulp**
With this commit, the number of :: allocations logged in total
after individually compiling each scala file in src/compiler
drops from 190,766,642 to 170,679,925.  Twenty million fewer
colon-colons in the world, it's a start.

For some heavily used lists like List(List()) I made vals so
we can reuse the same one every time, e.g.

  val ListOfNil = List(Nil)

The modifications in this patch were informed by logging call
frequency to List.apply and examining the heaviest users.

> > Origins tag 'listApply' logged 3041128 calls from 318 distinguished sources.

1497759   scala.reflect.internal.Definitions$ValueClassDefinitions$class.ScalaValueClasses(Definitions.scala:149)
 173737   scala.reflect.internal.Symbols$Symbol.alternatives(Symbols.scala:1525)
 148642   scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer.transform(SuperAccessors.scala:306)
 141676   scala.tools.nsc.transform.SpecializeTypes$$anonfun$scala$tools$nsc$transform$SpecializeTypes$$specializedOn$3.apply(SpecializeTypes.scala:114)
  69049   scala.tools.nsc.transform.LazyVals$LazyValues$$anonfun$1.apply(LazyVals.scala:79)
  62854   scala.tools.nsc.transform.SpecializeTypes.specializedTypeVars(SpecializeTypes.scala:427)
  54781   scala.tools.nsc.typechecker.SuperAccessors$SuperAccTransformer.transform(SuperAccessors.scala:293)
  54486   scala.reflect.internal.Symbols$Symbol.newSyntheticValueParams(Symbols.scala:334)
  53843   scala.tools.nsc.backend.icode.Opcodes$opcodes$CZJUMP.<init>(Opcodes.scala:562)
  ...     etc.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @gkossakowski of course.

**Comment by VladUreche** [comment]
Awesome! Thanks for looking into that Paul!

**Comment by gkossakowski** [comment]
I went through half of the patch and it looks good so far. Also, I started my benchmarks just to see reduced number of allocations myself. I'll do the rest of review tomorrow. It's already past midnight here.

**Comment by gkossakowski** [comment]
Ok, for that looks awesome. On my benchmarks we got rid of 16% of `::` allocations. That's a great result for such a simple change!

Rebase it and create a new pull request. It'll get LGMT from me right away!

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
@gkossakowski don't miss that there's #1149 for you too.

**Comment by ijuma** [comment]
Nice!

**Pull request merged**
