### PR TITLE
Merge 2.10.x into master

### PR DESCRIPTION
**Pull request by gkossakowski**
Another attempt at merging 2.10.x.

Recent merge of #2746 made this PR a little bit more difficult so I split the merge into two commits. The first commit resolves merge conflicts the same way as #2781 except for tests failures.

Hopefully this time all tests will pass.

Review by @retronym.

### CODE REVIEW

**Comment by gkossakowski** [comment]
@retronym: I'll need to get your LGTM stamp again. All tests pass this time.

**Comment by VladUreche** [comment]
Greg, are you sure you want to merge 504b5f3 in master? I'm asking because I submitted a different patch to master, 8329a64, which supersedes 504b5f3.

**Comment by gkossakowski** [comment]
@VladUreche: thanks for heads up. I'm merging the whole 2.10.x branch so that includes 504b5f3 (I can't merge everything else but that commit). However, since you 8329a64 submitted to master and it got merged this one takes precedence when merge occurs so the end result is the one you expect: https://github.com/gkossakowski/scala/blob/a72f79abf5845d25c847f7d7cde6d28a9d15612e/src/compiler/scala/tools/nsc/transform/Mixin.scala#L122

Also, the other way of looking at is:

```
git show a72f79abf5845d25c847f7d7cde6d28a9d15612e --name-status --format=short
commit a72f79abf5845d25c847f7d7cde6d28a9d15612e
Merge: 20cd947 1e5bfdb
Author: Grzegorz Kossakowski <grzegorz.kossakowski@gmail.com>

    Merge remote-tracking branch 'scala/2.10.x' into merge-2.10.x

MM      src/compiler/scala/reflect/reify/phases/Reshape.scala
MM      src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
MM      src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
MM      src/compiler/scala/tools/nsc/typechecker/Typers.scala
MM      src/library/scala/concurrent/Future.scala
MM      src/library/scala/concurrent/impl/Promise.scala
MM      src/library/scala/util/Properties.scala
MM      test/files/neg/macro-override-macro-overrides-abstract-method-b.check
```

You can see that Mixin is not affected in any way because 8329a64 won. Therefore, it's great that you submitted your patch against master because it saved me a merge pain.

**Comment by VladUreche** [comment]
Oh, that was the mixin patch, not the specialization in inner scopes. Sorry for the noise, I thought it's 3216321 (with 2285493 for the 2.10 branch), which was a bit tricky to port. Thanks for the explanation Greg!

**Comment by gkossakowski** [comment]
@retronym: ping

**Comment by retronym** [comment]
Lgtm

**Pull request merged**
