### PR TITLE
change intArrayOps and friends return types for efficiency

### PR DESCRIPTION
**Pull request by adriaanm**
Rework of #4297

### CODE REVIEW

**Comment by adriaanm** [comment]
Aha! Now we got to the (external) partest failure :)

**Comment by adriaanm** [comment]
@xuwei-k, sorry, I won't have time to get this in for 2.12.0-M1. I'm moving this to M2.

**Comment by adriaanm** [comment]
Re-reworked to leave non-implicit binary compatibility stubs in place.

**Comment by adriaanm** [comment]
Woohoo! :balloon: review by @lrytz

**Comment by lrytz** [comment]
LGTM!

**Pull request merged**
