### PR TITLE
Fix how "sbt" is written

### PR DESCRIPTION
**Pull request by dwijnand**
"sbt" is not an acronym (it used to be, but it isn't any longer).
It's a proper name, like "iPhone" or "eBay".

So, just like you wouldn't write "Get Started With EBay" or
"How To Reset Your IPhone", we don't write "Using the Sbt Build".

### CODE REVIEW

**Comment by smarter** [comment]
> "sbt" is not an acronym

I thought everyone knew that sbt stands for "sbt build tool" :)

**Review by lrytz — APPROVED** [review]

**Comment by dwijnand** [comment]
That was fast :) Thanks Lukas.

**Comment by lrytz** [comment]
Thanks to you :)

**Pull request merged**
