### PR TITLE
SI-8200 provide an identity liftable for trees

### PR DESCRIPTION
**Pull request by densh**
This liftable hasn't been originally included in the set of standard
liftables due to following contradiction:
1. On one hand we can have identity lifting that seems to be quite
   consistent with regular unquoting and splicing:
   
   ``` scala
   q"..${List(1,2)}"        <==> q"1; 2"
   q"${List(1,2)}"          <==> q"s.c.i.List(1, 2)"
   q"..${List(q"a", q"b")}” <==> q"a; b"
   q"${List(q"a", q"b")}"   <==> q"s.c.i.List(a, b)" // introduced by this pr, currently fails
   ```
   
   This is also consistent with how lisp unquoting works although they
   get lifting for free thanks to homoiconicity:
   
   ``` scala
   // scala
   scala> val x = List(q"a", q"b"); q"f($x)"
   q"f(s.c.i.List(a, b))"
   ```
   
   ``` scheme
   ;; scheme
   > (let [(x (list a b))] `(f ,x))
   '(f (list a b))
   ```
2. On the other hand lifting is an operation that converts a value into
   a code that when evaluated turns into the same value. In this sense
   `Liftable[Tree]` means reification of a tree into a tree that
   represents it, i.e.:
   
   ``` scala
   q"${List(q"a", q"b")}"
   <==>
   q"""s.c.i.List(Ident(TermName("a")), Ident(TermName("b")))"""
   ```
   
   But I belive that such lifting will be very confusing for everyone
   other than a few very advanced users.

This commit introduces the first option as a default Liftable for trees.

review @xeno-by @retronym

### CODE REVIEW

**Comment by densh** [comment]
The reason why I'm submitting it now is [the request from the end user to have option 1 as default](https://github.com/scalamacros/paradise/issues/21) which validates that it actually makes sense. It can't be introduced in 2.11.1 due to binary compatibility ties.

**Comment by xeno-by** [comment]
I was initially against this, but practical evidence of usefulness starts to overcome my initial doubts. Wdyt @retronym?

**Comment by retronym** [comment]
LGTM. As Quasiquotes are experimental, we could modify this behaviour in 2.12 if experience shows it is was a mistake. Furthermore, advanced users use scoping to bring in an alternative `Liftable[Tree]` for the reification use case, if the default doesn't work for them.

**Comment by xeno-by** [comment]
Great! Shall we merge?

**Pull request merged**
