### PR TITLE
Deprecate @remote

### PR DESCRIPTION
**Pull request by lrytz**
Also a few minor cleanups in the backend.

### CODE REVIEW

**Comment by soc** [comment]
What is the issue with `@remote`?

**Comment by lrytz** [comment]
i was assuming nobody is using that - i haven't discussed this with anyone, i might be completely wrong :)

it's the kind of annotations-compiler-magic that we're moving away from for a while (`@cloneable`, `@serializable`)

**Comment by soc** [comment]
Ok, agree. I'm slightly concerned overall with the introduction of new dependencies on Java types, but I can see that this is just following the direction into which we are going already.

**Comment by adriaanm** [comment]
+1 on the deprecation -- I very much doubt anyone was using this

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
