### PR TITLE
SI-5918 fixes ConstantType ugliness

### PR DESCRIPTION
**Pull request by xeno-by**
The problem that made me erect this ugly workaround has fixed itself.
The test attached failed to compile back then without a workaround, but
now it succeeds. Therefore I'm just reverting ConstantType.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp

**Comment by gkossakowski** [comment]
How it fixed itself?

**Comment by xeno-by** [comment]
Looking into that. And in the meanwhile, let the kitteh work.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Oops sorry I did this again. Pushed my intermediate progress, and it got picked up by github.

The updated test is going to fail by the way. This is the underlying reason for my fix back then. 

And it's still here. Previously failing test didn't fail in current trunk, because now we use a different logic to generate class tags, and the tainted code path doesn't get triggered.

**Comment by gkossakowski** [comment]
Oh, I see. Shall we close this pull request for now until you come up with the final solution?

**Comment by xeno-by** [comment]
I agree, that would be the best

**Pull request closed without merging**
