### PR TITLE
Don't Scaladoc scala.runtime

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by SethTisue** [comment]
@dwijnand is there some particular kind of review you want on this? if you've already tested that the change has the desired effect, then I think we can just merge it

**Comment by dwijnand** [comment]
OK, cool.  I had already tested the regex worked.  I've just now tested that after running `library/doc` there is no `build/scaladoc/library/scala/runtime/` directory.

**Comment by som-snytt** [comment]
I was going to say that I use `ScalaRunTime.stringOf` all the time, but it's already excluded anyway.

**Comment by dwijnand** [comment]
Well just be a careful emptor there...

**Comment by giorgiovinci** [comment]
What's the reason behind this choice? What's wrong with having it documented?

Ok, I actually was just wandering about the Rich* classes and this open issue answered me:

https://github.com/scala/bug/issues/11626

> In my opinion the RichXYZ classes should be moved outside of the runtime package. The runtime package is not supposed to be part of the public API.

**Pull request merged**
