### PR TITLE
reduce sharing between trees

### PR DESCRIPTION
**Pull request by paulp**
There's a very long way to go, but this reduces the amount of tree sharing.

Review by @retronym.

### CODE REVIEW

**Comment by retronym** [comment]
@paulp Any feeling on whether we need to check this for performance impact?

**Comment by paulp** [comment]
In the absence of something which tells me automatically, I'm not particularly concerned about it, nor would I be especially surprised if it caused a little blip. I'm all for knowing, I'm just not all for investing too much one-shot effort in finding out when I will undoubtedly find out eventually anyway.

**Comment by retronym** [comment]
Fair enough.

Could you please the PR description to explain why this is noble pursuit?

After that and the rechunking, LGTM.

**Comment by paulp** [comment]
Rechunked. I added the grandiose claims of nobility in the form of commit message rather than PR description; I don't know if you agree, but I find that to be superior long-term storage for my treatises and polemics.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
...even though I didn't change anything except which code which in went commit, and commit messages.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Thanks, random build aborting guy! That is supposed to say "Succeeded."

```
strap.scalacheck:
    [mkdir] Created dir: /localhome/jenkins/c/workspace/pr-scala-testsuite-linux-opt/build/strap/classes/scalacheck
[scalacfork] Compiling 14 files to /localhome/jenkins/c/workspace/pr-scala-testsuite-linux-opt/build/strap/classes/scalacheck
Build was aborted
Archiving artifacts
Finished: ABORTED
```

**Comment by adriaanm** [comment]
PLS REBUILD ALL diligently

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
I'm going to need some convincing that PRs with merges are a good idea concerning cleanliness of the history of the branch they will be merged into.

**Comment by gkossakowski** [comment]
@adriaanm: what's not clean about them? Also, how merge PR are different from any other PR?

**Comment by adriaanm** [comment]
a PR is either a merge of one branch into another (e.g., #1716) or a feature/bugfix (this one)

I'm saying it shouldn't be both (if I understand correctly, it complicates the parent graph for no good reason -- unless rebasing on top of master is not an option here for some reason)

**Comment by paulp** [comment]
Even if I have to rebase in the end, I think it's far better not to be push-dash-fing as I go, if for no other reason than that it obscures and confuses the github discussion. But also because of that other thing - I want people, myself and others, to be able to base work on open pull requests.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
i'm fine having a final rebase before merging, i just figured we had reached that finality by now

**Comment by paulp** [comment]
Counting eggs as if they were chickens reduces one's poultry yield.

**Comment by paulp** [comment]
Fox in the henhouse!

**Pull request merged**
