### PR TITLE
Update TASTy reader to support Scala 3.1

### PR DESCRIPTION
**Pull request by bishabosha**
As well as implementing changes for TASTy in Scala 3.1.0, also implements a few fixes:
- fix reading of singleton enum values in non-static inner class
- do not force annotations unnecessarily
- add existential flag to wildcard symbols

### CODE REVIEW

**Comment by bishabosha** [comment]
Open question: should we support `@experimental` annotation checks, so that you can't depend on a definition marked `@experimental` unless you are in also an experimental scope?

**Comment by SethTisue** [comment]
@bishabosha I don't seem to have permission to push to your branch, but it needs

```diff
diff --git src/compiler/scala/tools/nsc/tasty/bridge/TreeOps.scala src/compiler/scala/tools/nsc/tasty/bridge/TreeOps.scala
index 5a82115d65..82d82af03a 100644
--- src/compiler/scala/tools/nsc/tasty/bridge/TreeOps.scala
+++ src/compiler/scala/tools/nsc/tasty/bridge/TreeOps.scala
@@ -12,7 +12,7 @@
 
 package scala.tools.nsc.tasty.bridge
 
-import scala.tools.nsc.tasty.{TastyUniverse, TastyModes, ForceKinds}, TastyModes._, ForceKinds._
+import scala.tools.nsc.tasty.{TastyUniverse, TastyModes}, TastyModes._
 
 import scala.tools.tasty.TastyName
 import scala.reflect.internal.Flags
```

to remove unused imports. You can test this locally with `set every fatalWarnings := true`, which we normally only have enabled in CI.

**Comment by SethTisue** [comment]
> Open question: should we support @experimental annotation checks, so that you can't depend on a definition marked @experimental unless you are in also an experimental scope?

That seems desirable to me (but not a blocker for 2.13.7, of course).

**Comment by SethTisue** [comment]
otherwise LGTM, but perhaps @lrytz would like to give it a once-over

**Comment by timothyklim** [comment]
@bishabosha 

>fix reading of singleton enum values in non-static inner class

Can it read opaque type from a package? For example:
```
package a
opaque type A = Byte
object A:
  def apply(value: Byte): A = value
```

In Scala 2.13.6 opaque type must be inside object A otherwise compile error.

**Comment by bishabosha** [comment]
> Can it read opaque type from a package? For example:
> 
> ```
> package a
> opaque type A = Byte
> object A:
>   def apply(value: Byte): A = value
> ```
> 
> In Scala 2.13.6 opaque type must be inside object A otherwise compile error.

@timothyklim currently in 2.13, top level definitions from Scala 3 can only be used from their wrapper object, e.g. if that code was in `a/A.scala` then we need to import `a.A$package.A`

**Comment by lrytz** [comment]
LGTM too

**Comment by bishabosha** [comment]
I realised now that https://github.com/scala/scala/pull/9791/commits/783323246f58c9e0fc4a587eeda9414216caf7c5 is still forcing the annotation class (to get primaryConstructor), just not explicitly - it's still not causing an issue but something to note.

**Pull request merged**
