### PR TITLE
Feature/pc ctrie

### PR DESCRIPTION
**Pull request by axel22**

### CODE REVIEW

**Comment by paulp** [comment]
Hey - in a related matter, I had managed to eliminate all the "method cannot be inlined" messages one used to get when compiling under -optimise (ant build-opt) and the Ctrie code created a bunch of new ones.  Could you look into that? (The methods marked @inline are accessing private things.)

**Comment by axel22** [comment]
Ok, should I close the pull request and create a new one with the commits that eliminate the warnings?

**Comment by paulp** [comment]
No this one is fine, if you can eliminate them in a new one that's lovely.

**Comment by axel22** [comment]
Aye aye, capt'n!

**Comment by axel22** [comment]
This should do the trick.

**Pull request merged**
