### PR TITLE
SI-6930 adds documentation to reduceLeft in TraversableOnce

### PR DESCRIPTION
**Pull request by heathermiller**
Closes [SI-6930](https://issues.scala-lang.org/browse/SI-6930).

### CODE REVIEW

**Comment by heathermiller** [comment]
review by @jsuereth

**Comment by heathermiller** [comment]
Note- I noticed a typo I had wanted to change (instead of the docs saying "this traversable", I changed it to say "this $coll"). So I added it, committed, and rebased.

Hence the "Merge wit caution" and apparently the stopped build. Trying again...

PLS REBUILD ALL

**Comment by heathermiller** [comment]
Hmm. So all tests pass, yet at the top it says "Failed -- Merge build finished" and it links to the following: http://leaf:8080/job/scala-pull-requests/20/ which is of course local somewhere else.

I've been out of the loop lately, and it looks like our build setup has changed. Could someone let me know what's up or what I've done wrong in this PR? Thanks!

**Comment by lrytz** [comment]
i think it's just that kitty doesn't have its latest features all sorted out yet

**Comment by heathermiller** [comment]
Phew. Ok, thanks Lukas!

**Comment by paulp** [comment]
Sorry, that's my experiment with mutant kitties. (leaf is my desktop.) The comments from scala-jenkins are the only relevant ones.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
