### PR TITLE
Merge 2.11 to 2.12

### PR DESCRIPTION
**Pull request by lrytz**
```
lucmac:scala luc$ git log --pretty=oneline --decorate --abbrev-commit -n 1
56d7946 (HEAD, upstream/2.12.x, origin/2.12.x, merge/2.11-to-2.12-apr-21, 2.12.x) Merge pull request #4436 from adriaanm/rebase-4082

lucmac:scala luc$ export MB=$(git merge-base head upstream/2.11.x)


lucmac:scala luc$ git log --graph --oneline --decorate $MB..upstream/2.11.x
*   555f8f0 (upstream/2.11.x, origin/2.11.x, 2.11.x) Merge pull request #4454 from retronym/topic/indylambda-no-accessor
|\  
| * 1aa97cb Make lambda body public rather than using static accessor
|/  
*   b730937 Merge pull request #4451 from som-snytt/issue/3368-remediate
|\  
| * 498a07f SI-3368 Default to coalescing for 2.11
* |   64685a2 Merge pull request #4453 from adriaanm/repo-config-no-dup
|\ \  
| * | e0bec87 Derive repository info from (jenkins) env vars
|/ /  
* |   d2a174d Merge pull request #4449 from retronym/ticket/9273
|\ \  
| * | 4ff3abb SI-9273 Avoid unpositioned error for bare classOf
|/ /  
* |   029cce7 (gkossakowski/2.11.x) Merge pull request #4367 from retronym/topic/indylambda-specialization
|\ \  
| |/  
|/|   
| * ea61b3f Disable -Ydelambdafy:method for specialized FunctionN
*   8623c2b Merge pull request #4431 from adriaanm/rebase-4379
|\  
| * d44a86f Patmat: efficient reasoning about mutual exclusion
* |   6e7b326 Merge pull request #4373 from retronym/topic/indylambda-permutations-2
|\ \  
| * | 1e7a990 (retronym/topic/indylambda-permutations-2) SI-8359 Adjust parameter order of accessor method in Delambdafy
|  /  
* |   3cf7c95 Merge pull request #4306 from som-snytt/issue/3368-b
|\ \  
| * | ef7b552 SI-3368 Review
| * | 996d066 SI-3368 Promote xml option to -Xxml
| * | b60de05 SI-5699 Use ParserTest
| * | 4df81aa SI-3368 CDATA gets a Node
* | |   3ce8417 Merge pull request #4403 from gourlaysama/wip/t9239-generic-signature
|\ \ \  
| * | | e9bfa33 (gourlaysama/wip/t9239-generic-signature) SI-9239 fix java generic signature when traits extend classes
|  / /  
* | |   68e0570 Merge pull request #4386 from retronym/ticket/7741
|\ \ \  
| * | | bbd693a (retronym/ticket/7741) SI-7741 Tread more lightly during classfile parsing
|  / /  
* | |   9b009b4 Merge pull request #4428 from kzys/7601-img-alt-211
|\ \ \  
| * | | 9ad0302 [nomerge] SI-7601 Scaladoc: img elements must have an "alt" attribute
* | | |   fedbfd7 Merge pull request #4427 from gourlaysama/wip/t5795-scaladoc-empty-params
|\ \ \ \  
| * | | | 293f7c0 SI-5795 empty scaladoc tags should be omitted from output
| * | | | 83ea125 fix scaladoc issue with parsing of empty tags
| * | | | 2ce7ead fix Scaladoc html display when there are empty tags
| |/ / /  
* | | |   6e5c8f8 Merge pull request #4411 from xeno-by/ticket/9252
|\ \ \ \  
| * | | | 06b5bfa SI-9252 gets rid of custom logic for jArrayClass in runtime reflection
|  / / /  
* | | |   9a8f714 Merge pull request #4442 from retronym/topic/upgrade
|\ \ \ \  
| * | | | b4c88b5 Upgrade Ruby / Jekyll versions used to build the spec
| | |_|/  
| |/| |   
* | | |   213f0f8 Merge pull request #4439 from esfand-r/error-message-improvement
|\ \ \ \  
| * | | | 1ae8f30 Error message improvement 'may be not be' -> 'may not be'
| | |_|/  
| |/| |   
* | | |   338f385 Merge pull request #4438 from retronym/topic/plugin-api-regression
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | bb9bce7 Fix regression in plugin API
| |/ /  
* | |   476eef8 Merge pull request #4434 from gknauth/2.11.x
|\ \ \  
| * | | c81212d grammar it's -> its
|/ / /  
* | |   d88064d Merge pull request #4332 from Ichoran/opt-TravOnce-2.11.x
|\ \ \  
| * | | 56c1af9 Performance improvement: collectFirst in TraversableOnce
|  / /  
* | |   bbb5d20 Merge pull request #4413 from lrytz/opt/inliningEverything
|\ \ \  
| * | | 6becefe SI-9139 don't inline across @strictfp modes
| * | | a5dc9b7 Test case: cannot inline a private call into a different class.
| * | | 323d044 Don't inlinie if the resulting method becomes too large for the JVM
| * | | a40ee59 Don't force the GenASM backend when passing -optimize
| * | | 09f5752 Apply local variable index shift when inlining iinc instruction
| * | | 638ed91 Clean up the way compiler settings are accessed in the backend.
| * | | eb43d62 Don't try to inline native methods
| * | | fa110ed Eliminate unreachable code before inlining a method
| * | | 6cf17cc Command-line flag to control inlining heuristics
| * | | 093be1a Make class Invalid a ControlThrowable
|  / /  
* | |   9e2e633 Merge pull request #4432 from retronym/ticket/9264
|\ \ \  
| |/ /  
|/| |   
| * | a72eeb9 SI-9264 An even-better diagnostic for an unexplained crash
|/ /  
* |   214d798 Merge pull request #4370 from gbasler/ticket/SI-9181
|\ \  
| |/  
|/|   
| * fe2572c Bring back improvements from `SI-6942` that were lost during the switch to Tseitin's transformation, e.g., use
| * 081c1f1 Add a check to ensure that if the formulas originating from the exhaustivity / reachability analysis are too big to be solved in reasonable time, then we skip the analysis. I also cleaned up warnings.
* 29a960a Merge pull request #4419 from adriaanm/partest-bump
* 61df503 Bump partest to 1.0.6


lucmac:scala luc$ git merge fedbfd7

lucmac:scala luc$ git merge 9b009b4 -s ours

lucmac:scala luc$ git log --graph --pretty=oneline --decorate --abbrev-commit -n 4
*   15b1637 (HEAD, merge/2.11-to-2.12-apr-21) Merge commit '9b009b4' into merge/2.11-to-2.12-apr-21
|\  
| *   9b009b4 Merge pull request #4428 from kzys/7601-img-alt-211
| |\  
| | * 9ad0302 [nomerge] SI-7601 Scaladoc: img elements must have an "alt" attribute
* | |   efc1f19 Merge commit 'fedbfd7' into merge/2.11-to-2.12-apr-21
lucmac:scala luc$ git df efc1f19
lucmac:scala luc$ 

lucmac:scala luc$ git merge 555f8f0
```

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @adriaanm.

We can consider PR validation as successful:
- I started manually a jenkins job for the final merge commit (2586e6c)
- It had a spurious failure in validate-test, so I re-started (on jenkins) validate-test, which then passed

So basically all three validations (publish-core, validate-test, integrate-ide) passed for the final merge commit. The build bot didn't pick them up, probably because there are too many commits (pagination), the same happened last time I merged 2.11 to 2.12.

**Comment by adriaanm** [comment]
I verified 

```
$ g log --no-merges --topo-order --oneline 61df503..555f8f0 --grep nomerge
9ad0302886 [nomerge] SI-7601 Scaladoc: img elements must have an "alt" attribute
bb6a896b81 [nomerge] SI-8940 Scaladoc: Fix "Order by Alphabetical" button
```

are not included in the diff of this PR

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
