### PR TITLE
Bump the default memory setting in ANT_OPTS to 2G.

### PR DESCRIPTION
**Pull request by gkossakowski**
The reason is that `ant dist` fails with our current default (1.5G)
because Scaladoc needs more memory. This is being discovered by
newcomers every few weeks and they just go and adjust their own
environment variable `ANT_OPTS`. Let's save that trouble and fix
the default.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @JamesIry (picked at random)

**Comment by JamesIry** [comment]
LGTM

Sent from my iPhone.

**Comment by paulp** [comment]
That means you can't build with a 32 but vm. If there were some good
reason, ok, but scaladoc? How many people are downloading the compiler to
build scaladoc? Let us keep things in perspective. The thing to do is not
build scaladoc by default, not to inflict its ludicrous memory demands on
everything else.

**Comment by gkossakowski** [comment]
@paulp I might be disconnected from reality because I have latest MBP but how many people are using 32bit vms these days for development? Even on my 3 years old MBP I had 64bit VM.

Also, this is changing defaults. People can easily adjust them if they are on 32bit vm.
Here we are talking about `ant dist` which includes everything and among other things Scaladoc.

**Comment by lrytz** [comment]
irc it fails for memory leaks in ant. if you do "ant build-opt && ant dist" it will probably work - that's what we do in the checkin / nightly builds.

**Comment by paulp** [comment]
This difference used to be larger; still, 30 seconds is not trivial, and I can imagine the difference goes up with options tailored for java6/-d32.

```
% time JAVA_HOME=$(/usr/libexec/java_home -v 1.6) ANT_OPTS="-Xms1536M -Xmx1536M -Xss1M -XX:MaxPermSize=192M -XX:+UseParallelGC -d64" ant build
[stopwatch] [asm.lib.timer: 1.265 sec]
[stopwatch] [forkjoin.lib.timer: 1.350 sec]
[stopwatch] [locker.lib.timer: 1:00.432 sec]
[stopwatch] [locker.reflect.timer: 39.848 sec]
[stopwatch] [locker.comp.timer: 1:18.183 sec]
[stopwatch] [quick.lib.timer: 1:32.504 sec]
[stopwatch] [quick.reflect.timer: 39.333 sec]
[stopwatch] [quick.comp.timer: 1:17.727 sec]
[stopwatch] [quick.plugins.timer: 16.170 sec]
[stopwatch] [quick.scalacheck.timer: 17.357 sec]
[stopwatch] [quick.scalap.timer: 17.153 sec]
[stopwatch] [quick.partest.timer: 16.435 sec]

BUILD SUCCESSFUL
Total time: 7 minutes 50 seconds
470.256 real, 965.525 user, 28.517 sys


[paulp@bud trunk5 (master)]$ time JAVA_HOME=$(/usr/libexec/java_home -v 1.6) ANT_OPTS="-Xms1536M -Xmx1536M -Xss1M -XX:MaxPermSize=192M -XX:+UseParallelGC -d32 -server" ant build
[stopwatch] [asm.lib.timer: 1.228 sec]
[stopwatch] [forkjoin.lib.timer: 1.376 sec]
[stopwatch] [locker.lib.timer: 54.040 sec]
[stopwatch] [locker.reflect.timer: 39.793 sec]
[stopwatch] [locker.comp.timer: 1:11.409 sec]
[stopwatch] [quick.lib.timer: 1:24.129 sec]
[stopwatch] [quick.reflect.timer: 36.957 sec]
[stopwatch] [quick.comp.timer: 1:13.814 sec]
[stopwatch] [quick.plugins.timer: 15.753 sec]
[stopwatch] [quick.scalacheck.timer: 16.258 sec]
[stopwatch] [quick.scalap.timer: 16.085 sec]
[stopwatch] [quick.partest.timer: 15.702 sec]

BUILD SUCCESSFUL
Total time: 7 minutes 19 seconds
439.307 real, 968.584 user, 23.296 sys
```

**Comment by paulp** [comment]
"Also, this is changing defaults. People can easily adjust them if they are on 32bit vm."

People can easily adjust them if they have a need to run scaladoc. If we provided a decent target which created the compiler and put it in a properly named directory (that is, some fusion of "fastdist" and "partialdist", only less broken) that would enclose very few people - a lot fewer than might care to use a 32bit vm for the speed.

**Comment by gkossakowski** [comment]
Ok.

Closing as it didn't pass through peanut gallery.

**Pull request closed without merging**
