### PR TITLE
round of sbt build improvements

### PR DESCRIPTION
**Pull request by SethTisue**
the sbt build is still experimental so the bar for merging this probably
isn't too high. I did check that you can still build and package Scala,
run tests, generate doc.

review by @adriaanm or @retronym or @lrytz?

### CODE REVIEW

**Comment by som-snytt** [comment]
`libraryDependencies += "org.stuff" %% "stuff" % "1.0"`

or was this the test stuff?

`libraryDependencies += "org.stuff" %% "stuff" % "1.0" % "test"`

**Comment by SethTisue** [comment]
@som-snytt not sure what you're trying to tell us, but in any case, it inspired 049ccd9f19ebe7d09c6e5b215a977e99f690c414

**Comment by som-snytt** [comment]
@SethTisue me neither, but sometimes random associative humo(u)r is not useless.

Wait, did you take out the stuff about "stuff"? Maybe I'll create an issue over at sbt to make it possible to just depend on "stuff". Which is like the 80%.

**Comment by adriaanm** [comment]
LGTM -- yay, newer stuff!

**Pull request merged**
