### PR TITLE
SI-7469 Remove @deprecated scala.util.logging

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @paulp/@retronym, please.
This PR takes the feedback of #2522 into account.

**Comment by retronym** [comment]
LGTM

**Comment by soc** [comment]
@retronym Missed some tests, could you have a look again?
- 1 test was useless after the classes were removed
- 2 tests had useless imports

**Comment by retronym** [comment]
Thanks for letting me know; still LGTM. (even better!)

**Comment by soc** [comment]
Oh, also important: I added an @deprecated annotation to `src/library/scala/xml/factory/LoggedNodeFactory.scala`.

**Comment by adriaanm** [comment]
Awesome work, thanks!

**Pull request merged**
