### PR TITLE
Don't clear PRIVATE/PROTECTED flags from Java inner classes

### PR DESCRIPTION
**Pull request by hrhino**
Because javac didn't, and so we can't.

Happy New Year!

### CODE REVIEW

**Comment by szeiger** [comment]
So pretending that they are accessible by clearing the flags made the compiler think they are not accesible? This is confusing.

**Comment by hrhino** [comment]
That's how it is. It confused me too. More concretely, the problem is that `PROTECTED | notPROTECTED` doesn't mean `PUBLIC`; it means package-private (assuming the class comes from Java). So in order for protected access to be okay in `isJvmAccessible`, we need to keep it protected.

Thinking more on it, adding `notPRIVATE` probably wouldn't hurt. I'll try putting it back.

**Comment by hrhino** [comment]
Also, the reason that we do this bit at all is that we don't use the JVM notion of protection:
```scala
[haro@fidelis:/code/scala/sandbox]$ cat A.scala
protected class A { protected class B }

[haro@fidelis:/code/scala/sandbox]$ ../build/pack/bin/scalac -d . A.scala 

[haro@fidelis:/code/scala/sandbox]$ javap A.class A\$B.class 
Compiled from "A.scala"
public class A {
  public A();
}
Compiled from "A.scala"
public class A$B {
  public final A $outer;
  public A A$B$$$outer();
  public A$B(A);
}
```

but of course javac does.

**Review by lrytz — APPROVED** [review]
LGTM, but yeah it's a funny one.

**Pull request merged**
