### PR TITLE
Merge 2.10.x

### PR DESCRIPTION
**Pull request by adriaanm**
review by @paulp for:

```
    def unexpandedName(name: Name): Name = name lastIndexOf "$$" match {
      case -1 | 0 => name
```

review by @retronym for UnCurry conflict

### CODE REVIEW

**Comment by paulp** [comment]
Technically it should be lastIndexOf EXPAND_SEPARATOR_STRING, but other than that it looks good.

**Comment by adriaanm** [comment]
wish there was `git push -f --ninja`

**Comment by adriaanm** [comment]
PLS REBUILD/pr-checkin-per-commit@d7545ec36bde6a21e5f3edb1b5982e801a53f6a9

**Comment by adriaanm** [comment]
rerere repeatedly rears its ugly whitespace head

**Pull request closed without merging**
