### PR TITLE
Make all *.scala *.sbt *.txt *.md *.yml files end in a newline

### PR DESCRIPTION
**Pull request by Jasper-M**
On unix type operating systems all files typically have to end with a newline. I suspect most tools can handle offending files, but at the very least it's slightly irritating that git marks files as changed when some tool or editor automatically adds a newline to any offending file it touches.

I limited the change to file types which are most likely to appear in this repo and are probably ok with appending newlines to them.

Also @SethTisue asked for it.

### CODE REVIEW

**Comment by sjrd** [comment]
I agree, but this is a bit useless if it doesn't come with a CI script that checks that this is not violated in the future.

**Comment by sjrd** [comment]
I agree, but this is a bit useless if it doesn't come with a CI script that checks that this is not violated in the future.

**Comment by Jasper-M** [comment]
neg/t8630.scala fails. The error message remained the same, but the fact that there's no newline does seem to be part of the test.

**Comment by SethTisue** [comment]
> a CI script that checks that this is not violated in the future

a PR with that would be welcome, too.

but I'd also be happy to merge this as-is once CI likes it.

**Comment by Jasper-M** [comment]
I reverted the change to that one test file, so as to respect the original intentions of the test.

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
