### PR TITLE
(Do not merge) Deprecate package objects with inheritance

### PR DESCRIPTION
**Pull request by eed3si9n**
This deprecates package objects with inheritance, and removes it under -Xsource:2.14.

Ref https://github.com/scala/scala-dev/issues/488
Ref https://github.com/scala/scala-dev/issues/441

### CODE REVIEW

**Comment by xeno-by** [comment]
Is this a nomerge kind of an experiment to check whether the build is going to be green, or there is an intention to merge these changes into master? If it's the latter, I think we need a SIP and an approval from the SIP commitee first.

**Comment by eed3si9n** [comment]
> Is this a nomerge kind of an experiment to check whether the build is going to be green, or there is an intention to merge these changes into master? If it's the latter, I think we need a SIP and an approval from the SIP commitee first.

I came across an issue "Deprecate inheritance for package objects" that was created recently so I implemented it (as civilian in my off hours) assuming it was decided good to go in some SIP meeting.

If there hasn't been a consensus on this, I'll be happy to mark this dont-merge. To avoid divergence of discussion, could you also comment on https://github.com/scala/scala-dev/issues/441 there as well please?

**Comment by adriaanm** [comment]
Since this will take a while, I'm going to schedule this for after 2.13.0

**Comment by adriaanm** [comment]
(As our policy allows deprecations in a minor release.)

**Comment by SethTisue** [comment]
closing for now to get it out of the open PR queue. the scala-dev ticket is on the 2.13.1 milestone, so we won't lose track of it

**Pull request closed without merging**
