### PR TITLE
Increase partest timeout and emit warning when it hits.

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by adriaanm** [comment]
Merge 2.10.x into master after this is merged. This was a note to self.

**Comment by adriaanm** [comment]
Weird. It looks like hitting "done" on iPhone triggers the close & comment button and not the comment button.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
we've timed out a lot recently so I decided not to wait for a non-timed-out build for this change as it LGTM

**Comment by adriaanm** [comment]
hmm, wishful thinking -- the aborted builds we've been seeing recently were done with partest already
they got aborted after 3hrs whereas the jenkins time is 4hrs... I'm lost

@lrytz, do you have any thoughts on this?

**Comment by lrytz** [comment]
I don't understand. The build did not timeout (the jenkins timeout), it's individual tests that timed out (the partest timeout).

Which builds are you referring to?

**Comment by adriaanm** [comment]
sorry that was too vague, I was referring to the "grey builds" in https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/ 

e.g. https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/590/consoleText

**Comment by lrytz** [comment]
I think these are not timeouts. First, the timeout was at 240 minutes I think, and second, jenkins writes in the log when it times out, not just "ABORTED". I have no idea why they got aborted...

**Comment by paulp** [comment]
I can't find the string "ABORTED" anywhere in trunk.  At least that part originates with jenkins, yes?

**Comment by paulp** [comment]
From jenkins source:

```
/**
 * The build was manually aborted.
 *
 * If you are catching {@link InterruptedException} and interpreting it as {@link #ABORTED},
 * you should check {@link Executor#abortResult()} instead (starting 1.417.)
 */
public static final Result ABORTED = new Result("ABORTED",BallColor.ABORTED,4);
```

Supposition based on what is implied by the "if you are catching"
bit: increased concurrency accompanying my partest changes is causing
InterruptedExceptions to appear somewhere where it did not previously.
That something, perhaps a jenkins plugin, is aborting the build.

Suggestion: upgrade jenkins and disable nonessential plugins.

**Comment by lrytz** [comment]
yes sure, jenkins aborts the build, we just have no idea why.

**Comment by adriaanm** [comment]
it must be something in the jenkins setup/plugins (I don't have permission to look at those though)

pretty sure it's not us, as it once aborted after it was done already... 

```
....
BUILD SUCCESSFUL
Total time: 95 minutes 5 seconds
+ savedState=0
+ /localhome/hudson/workspace/pr-scala-testsuite-linux-opt/jenkins-scripts/archive-checkin
++ git rev-parse HEAD
+ revision=06b373878a044e0a83e5162bca661a6050957d04
+ rm -rf jenkins-artifacts
+ mkdir jenkins-artifacts
+ antWithMavenRev=81985e49cf9f492a4af6be8ed5c3125ca4861fbe
+ antNoMavenRev=0385e9835d6fac729b6672294fa8e4c6b1ea3c10
++ git rev-list 06b373878a044e0a83e5162bca661a6050957d04
++ grep 81985e49cf9f492a4af6be8ed5c3125ca4861fbe
+ [[ -n 81985e49cf9f492a4af6be8ed5c3125ca4861fbe ]]
+ antWithMaven
+ echo 'archiving antWithMaven'
archiving antWithMaven
+ buildPack
+ [[ -d build/pack ]]
+ tar czf jenkins-artifacts/pack.tgz -C build pack
+ distsLatest
+ [[ -L dists/latest ]]
+ tar czhf jenkins-artifacts/dist.tgz -C dists latest
Build was aborted
Finished: ABORTED
```

**Comment by lrytz** [comment]
i'm pretty sure we don't have any un-needed plugins, i keep track of that regularly. some unneeded ones are still installed, but not enabled.

**Comment by paulp** [comment]
My guess is it somehow comes back to the partest changes; on that front I have a day's worth of work i'm trying to finish up and pullrequestize.  If it doesn't fix it by accident, it will at least make it more debuggable.

**Pull request merged**
