### PR TITLE
SI-8363 Disable -Ydelambdafy:method in constructor position

### PR DESCRIPTION
**Pull request by retronym**
As @magarciaEPFL has done in his experimental optimizer [1], we can
avoid running into limitations of lambdalift (either `VerifyError`s,
ala scala/bug#6666, or compiler crashes, such as this bug), by using the
old style of "inline" lambda translation when in a super- or self-
construtor call.

We might be able to get these working later on, but for now we
shouldn't block adoption of `-Ydelamndafy:method` for this corner
case.

[1] https://github.com/magarciaEPFL/scala/blob/GenRefactored99sZ/src/compiler/scala/tools/nsc/transform/UnCurry.scala#L227

Review by @gkossakowski

### CODE REVIEW

**Comment by adriaanm** [comment]
spurious fail due to network error in IDE build -- manual rebuild: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/6668/console

**Comment by gkossakowski** [comment]
LGTM

I thought we did that already. The problem with lambdas in constructors was discovered by @JamesIry a long time ago. We decided that working it around by falling back to old translation scheme was the way to go.

**Comment by retronym** [comment]
@gkossakowski I think we just forced some tests for SI-6666 to use `-Ydelambdafy:inline` as the new tree shapes were no longer detected by the "this will cause a VerifyError" diagnostics I added for SI-6666.

**Comment by gkossakowski** [comment]
PLS REBUILD/pr-scala@814ecad

**Comment by gkossakowski** [comment]
@retronym: ah yes. That's right.

**Comment by gkossakowski** [comment]
In any case, we should merge this once tests pass.

**Pull request merged**
