### PR TITLE
correct dynamic pos

### PR DESCRIPTION
**Pull request by kiritsuku**
Review by @retronym
- I'm unable to assign tickets to me, could someone please activate my account for this (username on Jira is antoras)?
- I'm not completely sure about what positions have to be transparent. For example, I didn't make the parameters of `applyDynamicNamed` transparent because they occur in sources (but the created tuples do not). Thus, I'm not sure if this is correct.
- I used "complicated" DirectTests because I found no other way to react on positive compilation+check output

### CODE REVIEW

**Comment by adriaanm** [comment]
you should now be able to assign issues to yourself on jira!

**Comment by kiritsuku** [comment]
@adriaanm Thanks

**Comment by kiritsuku** [comment]
The integrate-ide failure seems not to be my fault, can it be resolved with a rebuild or does it require a fix?

**Comment by retronym** [comment]
I don't know how to troubleshoot that build error:

```
[info] Processing subproject: core
[info] [warn] **** Missing dependency: the library org.scalacheck#scalacheck is not provided by any project in this configuration file.
[info] [warn] The library (and possibly some of its dependencies) will be retrieved from the external repositories.
[info] [warn] In order to control which version is used, you may want to add this dependency to the dbuild configuration file.
[info] All Dependencies for subproject core:
[info]    org.scala-lang:scala-compiler:2.11.0-a1c0962-SNAPSHOT:scala-tool->default,optional(default)
[info]    org.scala-lang:scala-library:2.11.0-a1c0962-SNAPSHOT:scala-tool->default,optional(default)
[info]    org.scala-lang:scala-library:2.11.0-a1c0962-SNAPSHOT
[info]    net.sourceforge.fmpp:fmpp:0.9.14:fmpp
[info]    org.scalacheck:scalacheck:1.11.1:test
[info]    org.scala-lang.modules:scala-xml_2.11.0-a1c0962-SNAPSHOT:1.0-RC3
[info]    org.scala-lang.modules:scala-parser-combinators_2.11.0-a1c0962-SNAPSHOT:1.0-RC1
[info] Running build: core
[info] [warn] **** Missing dependency: the library org.scalacheck#scalacheck is not provided by any project in this configuration file.
[info] [warn] The library (and possibly some of its dependencies) will be retrieved from the external repositories.
[info] [warn] In order to control which version is used, you may want to add this dependency to the dbuild configuration file.
[info] [info] Updating {file:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-d74ef4c89e4d4e0309b5aeab56f04a042f2d76f6/}core...
[info] [info] Wrote /localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-d74ef4c89e4d4e0309b5aeab56f04a042f2d76f6/core/target/scala-2.11.0-a1c0962-SNAPSHOT/sbinary_2.11.0-a1c0962-SNAPSHOT-0.4.3-dbuildxd74ef4c89e4d4e0309b5aeab56f04a042f2d76f6.pom
[info] [info] Resolving org.scala-lang#scala-library;2.11.0-a1c0962-SNAPSHOT ...
[info] [info] Resolving org.scala-lang.modules#scala-xml_2.11.0-a1c0962-SNAPSHOT;1.0-RC3 ...
[info] [info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11.0-a1c0962-SNAPSHOT;1.0-RC1 ...
[info] [info] Resolving org.scalacheck#scalacheck_2.11.0-a1c0962-SNAPSHOT;1.11.1 ...
[info] [warn]   module not found: org.scalacheck#scalacheck_2.11.0-a1c0962-SNAPSHOT;1.11.1
[info] [warn] ==== ivy-build-local: tried
[info] [warn]   file:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-d74ef4c89e4d4e0309b5aeab56f04a042f2d76f6/.dbuild/local-repo/org.scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/ivys/ivy.xml
[info] [warn] ==== mvn-build-local: tried
[info] [warn]   file:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/./target-0.7.0/project-builds/sbinary-d74ef4c89e4d4e0309b5aeab56f04a042f2d76f6/.dbuild/local-repo/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== local: tried
[info] [warn]   /localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-d74ef4c89e4d4e0309b5aeab56f04a042f2d76f6/.dbuild/ivy2/local/org.scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/ivys/ivy.xml
[info] [warn] ==== pr-scala: tried
[info] [warn]   http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== public: tried
[info] [warn]   http://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== m2repo: tried
[info] [warn]   file:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/m2repo/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== sonatype-snapshots: tried
[info] [warn]   https://oss.sonatype.org/content/repositories/snapshots/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== java-annoying-cla-shtuff: tried
[info] [warn]   http://download.java.net/maven/2/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== typesafe-releases: tried
[info] [warn]   http://typesafe.artifactoryonline.com/typesafe/releases/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== typesafe-ivy-releases: tried
[info] [warn]   http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/ivys/ivy.xml
[info] [warn] ==== dbuild-snapshots: tried
[info] [warn]   http://typesafe.artifactoryonline.com/typesafe/temp-distributed-build-snapshots/org.scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/ivys/ivy.xml
[info] [warn] ==== sbt-plugin-releases: tried
[info] [warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/org.scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/ivys/ivy.xml
[info] [warn] ==== jgit-repo: tried
[info] [warn]   http://download.eclipse.org/jgit/maven/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
[info] [warn] ==== scala-fresh-2.10.x: tried
[info] [warn]   http://typesafe.artifactoryonline.com/typesafe/scala-fresh-2.10.x/org/scalacheck/scalacheck_2.11.0-a1c0962-SNAPSHOT/1.11.1/scalacheck_2.11.0-a1c0962-SNAPSHOT-1.11.1.pom
```

**Comment by retronym** [comment]
> Correct wrong position information for updateDynamic calls

Why was it wrong? Why are the new positions correct? Please share your insights in the commit messages to help educate us! We may avoid making the same mistakes next time :)

It would also be helpful if you demonstrated how the wrong positions led to sub-optimal behaviour in the IDE, and how this PR has been shown to improve that situation.

**Comment by retronym** [comment]
Ah, I see now that you've included the "why it was wrong" in the JIRA tickets.

In any case, it might be helpful to mention in the commit message something like: "the enclosed test used to cause a range position validation error"

**Comment by dragos** [comment]
@jsuereth might be able to help. Also, this failed:

```
[info] Sending outcome of project . to: qbranch@typesafe.com
[error] ERROR SENDING to qbranch@typesafe.com the outcome of project . using template email
[error] javax.mail.MessagingException: Could not connect to SMTP host: psemail.epfl.ch, port: 25, response: -1
[error]         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1949)
[error]         at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
[error]         at javax.mail.Service.connect(Service.java:295)
[error]         at javax.mail.Service.connect(Service.java:176)
[error]         at javax.mail.Service.connect(Service.java:125)
[info] --== Console Notifications ==--
```

**Comment by retronym** [comment]
Appears unrelated to this PR, I saw it on my last one, too.

Comparing https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4234/consoleText with https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4235/consoleText:

``` diff
-Started by build flow pr-scala#4754
+Started by build flow pr-scala#4757
 Building remotely on lampscalatst3-b in workspace /localhome/jenkins/b/workspace/pr-scala-integrate-ide
 Checkout:pr-scala-integrate-ide / /localhome/jenkins/b/workspace/pr-scala-integrate-ide - hudson.remoting.Channel@1f3a49af:lampscalatst3-b
 Using strategy: Default
@@ -9,8 +9,8 @@
 Checking out Revision 744425aab4f67805996388ea8620e81d1e4224b0 (origin/master)
 Cleaning workspace
 Resetting working tree
-Copied 2 artifacts from "pr-scala-publish-core" build number 457
-[pr-scala-integrate-ide] $ /bin/bash -ex /tmp/hudson7234967334914186107.sh
+Copied 1 artifact from "pr-scala-publish-core" build number 460
+[pr-scala-integrate-ide] $ /bin/bash -ex /tmp/hudson3889878342350520124.sh
 + [[ -d jenkins-scripts ]]
 + cd jenkins-scripts
```

``` diff
-[info] Cloning into '/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/./target-0.7.0/extraction/282974ea065a8c6a02767cf2b31c9551bf13dae2/projects/93025f6656a0393ea70ea2ee3cec38e7dfb0ad23'...
+[info] Cloning into '/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/./target-0.7.0/extraction/82bb09a77c6210d4d31411642cf0373f7220bf03/projects/93025f6656a0393ea70ea2ee3cec38e7dfb0ad23'...
 [info] done.
 [info] Branch 2.11 set up to track remote branch 2.11 from origin.
-[info] The following subprojects will be built in project sbinary: core
+[info] Extracting dependencies for: sbinary
+[info] Using project's standard Scala version during extraction.
+[info] Removing /localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/./target-0.7.0/extraction/82bb09a77c6210d4d31411642cf0373f7220bf03/projects/93025f6656a0393ea70ea2ee3cec38e7dfb0ad23/project/build.properties
+[info] Getting org.scala-sbt sbt 0.13.0 ...
+[info] :: retrieving :: org.scala-sbt#boot-app
+[info]     confs: [default]
+[info]     43 artifacts copied, 0 already retrieved (12440kB/)
+[info] Getting Scala 2.10.2 (for sbt)...
+[info] :: retrieving :: org.scala-sbt#boot-scala
+[info]     confs: [default]
```

**Comment by retronym** [comment]
The job is currently using the build script from https://github.com/adriaanm/uber-build
- Why the change from 2 to 1 artifacts? The file "mergetarget" is no longer an artifact as of https://scala-webapps.epfl.ch/jenkins/job/pr-scala-publish-core/459/
- Why is sbinary now being built?

**Comment by retronym** [comment]
Maybe: https://github.com/typesafehub/sbt-builds-for-ide/commit/08cfc9d1c40ac146be4373452e013e083eb463ef

**Comment by kiritsuku** [comment]
Thanks, Jason, for the review. I applied all your suggestions and wrote more detailed commit messages.

**Comment by retronym** [comment]
Do you want to target 2.10.4 with this, rather than just 2.11.x? If so, it makes our life easier if you open a PR against the 2.10.x branch. We merge 2.10.x to master regularly.

**Comment by kiritsuku** [comment]
Ok

**Comment by kiritsuku** [comment]
Follow up in #3190

**Comment by dragos** [comment]
@retronym I only know the answer to the second question: binary (in)compatibility. sbinary and sbt need to be built since there might be a change in the Scala library that breaks it.

No idea what is happening with mergetarget, nor what should be done about it. Does it come into play in this failure?

Adriaan forked the uber-build to keep things going, we're trying to catch up, but the changes are not yet merged in the uber-build branch. @skyluc is working on it, and should be done very soon.

**Comment by adriaanm** [comment]
Sorry about the breakage! Two balls up in the air here: [improvements to the sbt dbuild for the IDE](https://github.com/typesafehub/sbt-builds-for-ide/pull/16), and [scala PR validation using maven](https://github.com/scala/scala/pull/3108), and the [consequences for the IDE integration builds](https://github.com/scala-ide/uber-build/pull/22).

**Pull request closed without merging**
