### PR TITLE
Update build dependencies, jackson,jol and junit 

### PR DESCRIPTION
**Pull request by He-Pin**
Update the jackson,jol and junit ,so does the sbt.
I junit could be upgraded to junit 5 with migration lib, but that should not do in this one.

### CODE REVIEW

**Comment by SethTisue** [comment]
@hepin1989 why closed?

**Comment by He-Pin** [comment]
@SethTisue I should add an issue to the scala/bug then.

**Comment by SethTisue** [comment]
(it's totally fine to just open a pull request, not every PR needs to have an issue first)

**Review by SethTisue — APPROVED** [review]

**Comment by SethTisue** [comment]
a followup PR bumping sbt again (to 1.2.7) would be welcome :-)

**Pull request merged**
