### PR TITLE
Application is deprecated. Replaced with App

### PR DESCRIPTION
**Pull request by rnix**

### CODE REVIEW

**Comment by adriaanm** [comment]
great, long sha and short sha are treated differently:

https://api.github.com/repos/scala/scala/statuses/42744d7d1cdfe8d180fe96bbcbe8591185d20822
https://api.github.com/repos/scala/scala/statuses/42744d7

**Comment by gkossakowski** [comment]
@adriaanm: sounds like something worth reporting back to github.

**Comment by adriaanm** [comment]
issue reported to github

we have a real test failure here: https://scala-webapps.epfl.ch/jenkins/job/pr-rangepos-per-commit/453/

```
  [partest] testing: [...]/files/pos/t294                                         [FAILED]
  [partest] Test_1.scala:3: error: trait Ann2 is abstract; cannot be instantiated
  [partest] @Ann(nested = Array(new Ann2(10))) class Test {
  [partest]                     ^
  [partest] Test_1.scala:3: error: expected annotation of type <error>, found <error>
  [partest] @Ann(nested = Array(new Ann2(10))) class Test {
  [partest]                         ^
  [partest] Test_1.scala:4: error: trait Ann2 is abstract; cannot be instantiated
  [partest]   @Ann2(100) var ctx: Object = _
  [partest]    ^
  [partest] Test_1.scala:6: error: trait Ann2 is abstract; cannot be instantiated
  [partest]   @Ann(nested = Array(new Ann2(10), new Ann2(23))) val bam = -3
  [partest]                       ^
  [partest] Test_1.scala:6: error: trait Ann2 is abstract; cannot be instantiated
  [partest]   @Ann(nested = Array(new Ann2(10), new Ann2(23))) val bam = -3
  [partest]                                     ^
  [partest] Test_1.scala:6: error: expected annotation of type <error>, found <error>
  [partest]   @Ann(nested = Array(new Ann2(10), new Ann2(23))) val bam = -3
  [partest]                           ^
  [partest] Test_1.scala:6: error: expected annotation of type <error>, found <error>
  [partest]   @Ann(nested = Array(new Ann2(10), new Ann2(23))) val bam = -3
  [partest]                                         ^
  [partest] 7 errors found
```

**Comment by JamesIry** [comment]
LGTM, test failure is noise

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Pull request merged**
