### PR TITLE
Fix SI-6584, Stream#distinct uses too much memory.

### PR DESCRIPTION
**Pull request by paulp**
Nesting recursive calls in Stream is always a dicey business.

### CODE REVIEW

**Comment by jsuereth** [comment]
Failures look legitimate.

**Comment by paulp** [comment]
And overconfidence had been working out so well for me...

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
You're right about the doc comments I'm sure, but undoing other peoples' copy-pasting is not on my list of things to do more of.

**Comment by paulp** [comment]
But I will attempt to make my original material conform.

**Comment by paulp** [comment]
Geez, is it expected that I have to re-scaladoc the entire library to view any change? Any attempt to scaladoc Stream in isolation explodes horribly.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Review by @retronym

**Comment by retronym** [comment]
Looks like it wasn't _all_ copy/paste: a few hand crafted, `Stream` specific phrases and examples were added by Derek Wyatt way back in  DocSpree days. Those are left on the cutting room floor after this patch. Not sure if you meant that. I'd suggest that you revert those parts from this PR and we can address them in a separate change.

Sorry to have led you down this windy path.

The code changes LGTM.

**Comment by paulp** [comment]
Maybe this is why they don't let me near documentation, but I consider redundant docs as valuable as redundant code. Does Stream#reverse really merit a Stream specific example for us to watch bitrot? It's reverse.

**Comment by retronym** [comment]
I tend to agree with you. But it's not my area of expertise, either. I guess that "will terminate for infinite sequences" isn't an accessible description for all. I'd say the right compromise is to put a few expository examples in the class documentation. @heathermiller might have an opinion here.

But until then, I would decouple the doc changes from the functional changes (other than the obviously good parts of separating implementation comments from doc comments).

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Rogue aborter strikes again!

**Comment by paulp** [comment]
PLS REBUILD ALL

**Pull request merged**
