### PR TITLE
Update man pages for scala and scalac.

### PR DESCRIPTION
**Pull request by gourlaysama**
They had fallen quite a bit behind the output of
"scalac -X" and "scalac -Xshow-phases".

---

I always have to remember to query scalac directly instead of using the man page; well, not anymore :-)

Here is the resulting html man page : https://dl.dropboxusercontent.com/u/46938538/static/man/html/scalac.html
And the old one for comparison: http://www.scala-lang.org/files/archive/nightly/docs/manual/html/scalac.html

### CODE REVIEW

**Comment by som-snytt** [comment]
Use `scalac -Xshow-phases -Ydebug` to see all phases, including what is not enabled in the current run.

Or `scalac -Xshow-phases -optimise -P:continuations:enable`.

Also, `parser` is the default initial phase.  Just to check: `-Xprint:initial` gives a `warning: 'initial' specifies no phase`.

**Comment by som-snytt** [comment]
I was going to joke that `-Xdev` should say conscientious developer: `Indicates user is a developer - issue warnings about anything which seems amiss`.

Also, `scalac error: bad option: '-Xcheck-null'`

Also, I noticed there was an issue to turn `-Xplugin:path` into a class path for the plugin class loader, but the option wasn't updated.

**Comment by som-snytt** [comment]
Updated `-Xplugin` https://github.com/scala/scala/pull/3334

**Comment by gourlaysama** [comment]
Thanks, @som-snytt:
- Removed `-Xcheck-null`
- Added optimization and cps phases
- Removed `initial` pseudo-phase
- Added your updated syntax for `-Xplugin:paths` and co.

**Comment by adriaanm** [comment]
Thanks!!

**Comment by som-snytt** [comment]
What do you know, this was https://issues.scala-lang.org/browse/SI-7824

**Pull request merged**
