### PR TITLE
Default Xscript is Main

### LINKED ISSUE #12136: Default -Xscript to Main
## reproduction steps

See https://github.com/sbt/sbt/issues/5664

Normally the "scripting" entry point to parsing requires `-Xscript`.

But programmatic usage should not require that `-Xscript` is set or set reasonably.

## problem

Running a script should be robust against wrapping user code in a template that doesn't compile.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12136

### CODE REVIEW

**Comment by SethTisue** [comment]
I'm still getting the same error:

```scala
#!/usr/bin/env sbt -Dsbt.version=1.3.13 -Dsbt.main.class=sbt.ScriptMain                                                 

/***
scalaVersion := "2.13.4-bin-5333bba-SNAPSHOT"
*/

println("hi there")
```

```
[error] Error while emitting .scala
[error] String index out of range: 0
```

**Comment by som-snytt** [comment]
@SethTisue I commented on the ticket that I wouldn't handle `settings.script.value == ""`, a bad value set. Previously, it wasn't used.

I was about to add a second commit along the lines of
```
// support sbt
if (settings.script.value == null || settings.script.value == "")
```
but I suddenly grew tired.

The argument in favor is that templating is inherently fragile and we should make a best effort not to create broken code, even in the face of bad inputs.

**Comment by SethTisue** [comment]
>  I commented on the ticket

ah, I didn't grok that comment, now I do

**Comment by som-snytt** [comment]
OK, I gave in to Seth's charming persuasion. If Xscript seems a bit off, it assumes Main.

**Comment by SethTisue** [comment]
working now with `2.13.4-bin-694fe42-SNAPSHOT` 🎉 , thx Som

**Review by dwijnand — APPROVED** [review]
Change seems reasonable and if it works then let's go

**Pull request merged**
