### PR TITLE
upgrade sbt 0.13.16 -> 0.13.17

### PR DESCRIPTION
**Pull request by SethTisue**
not for merge, yet. let's wait until 0.13.17 final is out.

for now, let's just see if Jenkins likes it.

### CODE REVIEW

**Comment by SethTisue** [comment]
Jenkins likes it, fyi @eed3si9n @dwijnand 

I'm going to close this for now to get it out of the PR queue, but I'll set a reminder to come back to it once the final release is out

**Comment by SethTisue** [comment]
updated for 0.13.17 final

**Comment by dwijnand** [comment]
💚

**Comment by nafg** [comment]
Curious if the Scala build is not on SBT 1.x due to some hurdle or performance?

**Comment by SethTisue** [comment]
@nafg working on it. #6256

**Pull request merged**
