### PR TITLE
test for InnerClass and EnclosingMethod attributes

### PR DESCRIPTION
**Pull request by lrytz**
Some parts of the test assert (current) buggy behavior. This is marked
in the test file with TODO. It will be fixed in later work on the
backend.

The test also passes under `-Ybackend:GenBCode` (ran it locally).

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @gkossakowski

**Comment by gkossakowski** [comment]
Have you considered expressing this test as a junit test?

**Comment by lrytz** [comment]
It's a two phase test, it inspects generated bytecode. Can I do this in our junit infrastructure?

**Comment by gkossakowski** [comment]
I don't think you can at the moment. My question implied another question: have you considered extending our junit infrastructure so we can write such tests? We can do it in subsequent PR but I think this PR is an excellent occasion to consider extending junit infra. WDYT?

Meanwhile, LGTM!

**Comment by lrytz** [comment]
I promise to keep it in mind for the next time I write a bytecode test, which is certainly soon enough :)

**Pull request merged**
