### PR TITLE
Closes SI-5882

### PR DESCRIPTION
**Pull request by odersky**
I have added a restriction that value classes may not contain inner classes or objects. This makes sense as the "outer" field of any such classes or objects would be ephemeral, with surprising results. SIP-15 has been changed accordingly.

Review by @szeiger @moors

### CODE REVIEW

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by odersky** [comment]
Also added another validation check that guards against secondary constructors.

**Comment by retronym** [comment]
This will also close SI-6148.

**Comment by jsuereth** [comment]
Can I get a LGTM from someone else?  @szeiger is on vacation.  This LGTM, but I'm not sure I'm the best reviewer.

**Comment by jsuereth** [comment]
Ok, I'm pulling.

**Pull request merged**
