### PR TITLE
SI-9506 suppress Scala IDE-generated files in the Eclipse project dirs

### PR DESCRIPTION
**Pull request by performantdata**
I'll request review once I've made any similar commits that arise. Could be awhile.

### CODE REVIEW

**Comment by retronym** [comment]
I'd prefer a wildcard exclusion (`**/.cache-main`) in `/.gitignore`

**Comment by performantdata** [comment]
Me too, but I tried `*/.cache-main` in `src/eclipse/.gitignore`, and Eclipse ignored me. Guessing it's because Eclipse doesn't notice the `.gitignore` in directories above the project directory.

**Comment by retronym** [comment]
That file tells git to ignore some files in `./src/eclipse`, it isn't intended to tell eclipse what to ignore.

Instead, you want to add this config [right here](https://github.com/scala/scala/blob/2.11.x/.gitignore#L45)

**Comment by performantdata** [comment]
I tried your suggestion, but it doesn't work. Eclipse marks the `.cache-main` file icons with a "?" badge.

**Comment by SethTisue** [comment]
I don't think you need `**`. if you don't start the entry with a leading slash, that it applies anywhere in the tree. a trailing slash means "directory". so I would think this would do it:

```
.cache-main/
```

**Comment by performantdata** [comment]
According to the [docs](http://git-scm.com/docs/gitignore), `.cache-main` and `**/.cache-main` are equivalent.

`.cache-main` is a file, not a directory, at least in my release of the IDE. So `.gitignore` needs `.cache-main`, not `.cache-main/`.

I tried your suggestion anyway, but it doesn't work. I think you missed my point that Egit is ignoring the `.gitignore` files that are in proper ancestor directories of the Eclipse project directory (`src/eclipse/interactive/` et al.)

**Comment by performantdata** [comment]
@retronym I don't understand what you're thinking when you write

> That file tells git to ignore some files in `./src/eclipse`, it isn't intended to tell eclipse what to ignore.

It seems to me that Ecipse (Egit, I assume) should be interpreting the same files as Git (although, by some bug, we see that it doesn't).

**Comment by performantdata** [comment]
[This Eclipse bug comment](https://bugs.eclipse.org/bugs/show_bug.cgi?id=300964#c21) sounds similar. I'm using 4.4.2.

**Comment by performantdata** [comment]
review @retronym

**Comment by retronym** [comment]
LGTM, thanks for taking the time to smooth out the bumps on the ride while getting started contributing.

In the future, if you figure out a way to express our ignorance in a way that is both concise and comprehensible to EGit, we can collapse this all back into the `.gitignore` in the root folder.

**Pull request merged**
