### PR TITLE
SI-7242 Fix crash when inner object mixes in its companion

### PR DESCRIPTION
**Pull request by retronym**
Given:

```
class C {
  trait T { C.this }            // C$T$$$outer$ : C
  object T extends T { C.this } // C$T$$$outer$ : C.this.type
}
```

object T ended up with a definitions for both of the accessors.
These cannot co-exist, as they have the same erased type. A crash
ensued almost immediately in explitouter.

Fortunately, the solution is straightforward: we can just omit
the mixin outer accessor altogether, the objects own outer accessor
is compatible with it.

```
scala> :javap C.T
Compiled from "<console>"
public interface C$T{
    public abstract C C$T$$$outer();
}

scala> :javap C.T$
Compiled from "<console>"
public class C$T$ extends java.lang.Object implements C$T{
    public C C$T$$$outer();
    public C$T$(C);
}
```

I also added an assertion to give a better error message in
case we find ourselves here again.

Review by @paulp. I can't find any duplicates of the bug in JIRA, but it seems so easy to step into that I'm sure they must be in there. Can you summon any?

### CODE REVIEW

**Comment by paulp** [comment]
Yes, I reported it years ago. Here I go hunting.

**Comment by paulp** [comment]
https://issues.scala-lang.org/browse/SI-3994

**Comment by retronym** [comment]
Found it: https://issues.scala-lang.org/browse/SI-3994

**Comment by retronym** [comment]
You win.

**Comment by paulp** [comment]
I'm wearing my "extempore2 reported that years ago" shirt.

**Comment by retronym** [comment]
ping @paulp

**Comment by som-snytt** [comment]
This is pretty funny, it makes it sound like extempore has been gaming the system all along.
"Parenthetically, this is what SI-2969 was attempting to report."
"See SI-3994 for this bug reported in a more usable way."

What goes around comes around.
"Unfairly marking as a duplicate of the young upstart: SI-7242."

**Comment by paulp** [comment]
I like that. I'm "pocket vetoing" this PR in retaliation for closing SI-3994. Put that in your pipe and commit it, suckers!

LGTM.

**Pull request merged**
