### PR TITLE
SI-6023 reify abstract vals

### PR DESCRIPTION
**Pull request by martende**
SI-6023 reify abstract vals

Type trees created by MethodSynthesis for abstract val getters carry symless originals,
which are unusable for reification purposes
(or the result of reification will be unhygienic).

To combat this, type trees for such getters are now created empty,
i.e. without any `tpe` set, just having an original assigned.
Subsequent `typedTypeTree` invocations fill in the `tpe` and
update the original to be symful.

### CODE REVIEW

**Comment by xeno-by** [comment]
Could you please submit some tests as well?

**Comment by xeno-by** [comment]
It's always nice to see symful originals coming into reify. I especially like this trick with `typedTypeTree`.

Lgtm, but I'd really like a comment from @paulp regarding the MethodSynthesis part.

**Comment by paulp** [comment]
As you might suppose from the [big ol' comment](https://github.com/martende/scala/blob/821b99ceeaf5cd6db65b3fb744eb3026588df442/src/compiler/scala/tools/nsc/typechecker/MethodSynthesis.scala#L366-L373), I think it should be TypeTree() always, so expanding the set of trees done that way is all to the good to the extent it doesn't come with new failures. So lgtm.

**Comment by xeno-by** [comment]
Resubmitted against 2.10.x: https://github.com/scala/scala/pull/1660

**Pull request closed without merging**
