### PR TITLE
SI-7775 Harden against the shifting sands of System.getProperties

### PR DESCRIPTION
**Pull request by retronym**
If another thread writes a new system property (which can happen
in pretty innocuous code such as `new Date`!), the compiler startup
could fail with a `ConcurrentModificationException` as it iterated
all bindings in the properties map in search of a boot classpath
property for esoteric JVMs.

This commit uses `Properties#getStringProperties` to get a snapshot
of the keys that isn't backed by the live map, and iterates these
instead. That method will also limit us to bindings with String
values, which is all that we expect.

Review by @paulp, hat tip to @som-snytt

### CODE REVIEW

**Comment by som-snytt** [comment]
This one adds a `names` to `sys.SystemProperites.`

https://github.com/som-snytt/scala/tree/issue/7775-sysprop-CME

Didn't mean to tip my hand.

Doesn't actually address:

```
  // Todo: bring some sanity to the intersection of system properties aka "mutable
  // state shared by everyone and everything" and the reality that there is no other
  // mechanism for accomplishing some things on the jvm.
```

Update maybe this makes the diff easier to find?
https://github.com/scala/scala/pull/2869

**Comment by huitseeker** [comment]
[This failure](https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/1576/) (if it ever gets reported) is a network problem during the  validation run.

**Comment by retronym** [comment]
@som-snytt Did the closure of your competing pull request imply approval of this one? Lay the letters on me!

**Comment by som-snytt** [comment]
My PR adds a method, so would require MIMA white-listings. (I think I got the lingo right.)  So I figured I'd resubmit for 2.11.

LGTM for the succor of those poor souls languishing on 2.10.x.

**Comment by som-snytt** [comment]
@retronym You're paid to handle the backport to 2.9.x, right?

**Comment by retronym** [comment]
It will be forward-merged to 2.11.x but only critical bugs are backported to 2.9.x.

**Pull request merged**
