### PR TITLE
Progress with macros

### PR DESCRIPTION
**Pull request by xeno-by**
A short recap:
- Macro expansion now works finely for instance macro invocations
- Macros are now hidden behind -Fmacros
- Bodies of macros now have "import _context._" in their preamble
- Macros are now loaded from classpath, much like regular libraries
- Macros can now override methods (in that case macro expansion
  does not crash if macro is not found, it just falls back to super)

Review by @odersky.

### CODE REVIEW

**Comment by paulp** [comment]
What is the basis for the -F option? We should only be doing something like that as part of a plan which considers all the existing and on-their-way options (which maybe there is one but I haven't heard about it.) Otherwise it should be -Xmacros.

**Comment by xeno-by** [comment]
When we talked about a pull request, Martin wanted macros to be the first language feature to explore this mechanism. But, I agree, just saying -Fmacros instead of -Xmacros doesn't look like exploration - it's just fishy.

**Comment by xeno-by** [comment]
Updated the pull request

**Comment by paulp** [comment]
There is a test failure; I looked at it but I don't know the macro code well enough yet.

```
testing: [...]/files/pos/macros.scala                                 [FAILED]
macros.scala:5: error: not found: value glob (similar: glb)
      case (t1: glob.Type, t2: glob.Tree) => t2
                ^
macros.scala:5: error: not found: value glob (similar: glb)
      case (t1: glob.Type, t2: glob.Tree) => t2
                               ^
two errors found
```

**Comment by xeno-by** [comment]
Oh dear God, I've fixed that, but now when I look at this file, I see that my fix didn't get into a pull request. Weird. Gotta submit a fix asap

**Comment by xeno-by** [comment]
That should remedy the problem. To save you the trouble of reverting I've submitted a fix as a separate commit. Please, let me know if you want me to squash it together with the original changeset.

**Comment by paulp** [comment]
When a commit is flawed in such a way that we no longer build, then you should definitely squash them to minimize the number of unbuildable points in the history.  When it's something like this, an additional commit is no big deal.

**Pull request merged**
