### PR TITLE
SI-8817 Remove mention that shutdown hook is daemon thread

### PR DESCRIPTION
**Pull request by terma**
Please review by @VladUreche

### CODE REVIEW

**Comment by VladUreche** [comment]
@terma: Thanks for the patch! Please address the feedback of @som-snytt and ping me so I can merge.

**Comment by som-snytt** [comment]
@terma  Also worth mentioning that the usual workflow is to make an edit, commit it, squash it with rebase, the push -f to the same branch.  You can leave the PR open.

Or in this case, it's not even necessary to squash it. Just add another commit and push.

**Comment by terma** [comment]
Well, according to guide fix should have only one commit, no?

**Comment by som-snytt** [comment]
I was trying to make it easy.

**Comment by terma** [comment]
Thx, I just doublecheck.

**Pull request closed without merging**
