### PR TITLE
SI-5920 hardens macro engine against invalid inputs

### PR DESCRIPTION
**Pull request by xeno-by**
Due to an unexpected combination of c.abort's in Slick codebase (something
that I've yet to minimize), it was possible for a Block of erroneous macro
applications to enter macro engine, wreaking havoc in undoNamesDefaults.
This commit prevents this from ever happening again.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
Node that this is a regression that resulted from https://github.com/scala/scala/pull/3397 being merged yesterday, so I'm submitting this against 2.11.0-RC1.

**Comment by retronym** [comment]
This also breaks specs2:

```
[info] [warn] /localhome/jenkinsdbuild/workspace/Community-2.11.x-retronym/dbuild-0.7.1-M1/target-0.7.1-M1/project-builds/specs2-aaa8091b47a34817ca90134ace8b09a9e0f854e9/core/src/test/scala/org/specs2/text/EditDistanceSpec.scala:6: Unused import
[info] [warn] import DiffShortener._
[info] [warn]                      ^
[info] [error] /localhome/jenkinsdbuild/workspace/Community-2.11.x-retronym/dbuild-0.7.1-M1/target-0.7.1-M1/project-builds/specs2-aaa8091b47a34817ca90134ace8b09a9e0f854e9/core/src/test/scala/org/specs2/text/LinesContentDifferenceSpec.scala:7: exception during macro expansion: 
[info] [error] java.lang.UnsupportedOperationException: Position.point on NoPosition
[info] [error]  at scala.reflect.internal.util.Position.fail(Position.scala:53)
[info] [error]  at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:131)
[info] [error]  at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:126)
[info] [error]  at org.specs2.reflect.Macros$.sourceOf(Macros.scala:25)
[info] [error]  at org.specs2.reflect.Macros$.stringExpr(Macros.scala:19)
[info] [error]  at org.specs2.specification.S2Macro$$anonfun$13.apply(SpecificationStringContext.scala:128)
[info] [error]  at org.specs2.specification.S2Macro$$anonfun$13.apply(SpecificationStringContext.scala:128)
[info] [error]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info] [error]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info] [error]  at scala.collection.immutable.List.foreach(List.scala:302)
[info] [error]  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[info] [error]  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[info] [error]  at org.specs2.specification.S2Macro$.s2Implementation(SpecificationStringContext.scala:128)
[info] [error]  at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[info] [error]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] [error]  at java.lang.reflect.Method.invoke(Method.java:616)
[info] [error]  at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:34)
[info] [error]  at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:22)
[info] [error]  at scala.tools.nsc.typechecker.Macros$class.macroExpandWithRuntime(Macros.scala:782)
[info] [error] class LinesContentDifferenceSpec extends Specification with AllExpectations { s2"""
```

``` scala
ack stringExpr --scala --context=3
common/src/main/scala/org/specs2/execute/Snippets.scala
64-  def create[T](c: MContext)(code: c.Expr[T])(params: c.Expr[SnippetParams[T]]): c.Expr[Snippet[T]] = {
65-    import c.{universe => u}; import u._
66-    import Macros._
67:    val result = c.Expr(methodCall(c)("createSnippet", c.literal(c.macroApplication.pos.isRange).tree, stringExpr(c)(code), code.tree.duplicate, params.tree))
68-    c.Expr(atPos(c.prefix.tree.pos)(result.tree))
69-  }
70-}

common/src/main/scala/org/specs2/reflect/Macros.scala
15-    Apply(Ident(newTermName(name)), xs.toList)
16-  }
17-
18:  def stringExpr(c: Context)(variable: c.Expr[Any]): c.Tree =
19-    c.literal(sourceOf(c)(variable)).tree
20-
21-  def sourceOf(c: Context)(expr: c.Expr[_]): String = {

core/src/main/scala/org/specs2/specification/SpecificationStringContext.scala
125-        c.literal(Yrangepos).tree,
126-        toAST[List[_]](c)(texts:_*),
127-        toAST[List[_]](c)(variables.map(_.tree):_*),
128:        toAST[List[_]](c)(variables.map(stringExpr(c)(_)):_*)))
129-
130-    c.Expr(atPos(c.prefix.tree.pos)(result.tree))
```

I suggest that we revert the change.

**Comment by retronym** [comment]
Here's a PR that reverts the last commit of  #3397:  #3542.

**Comment by xeno-by** [comment]
@retronym What branch of specs2 are you using in the build?

**Comment by retronym** [comment]
Master. (The config is: https://github.com/retronym/community-builds/blob/jenkins/community-2.11.x.dbuild#L123)

**Comment by xeno-by** [comment]
How do you fix this:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalacheck#scalacheck_2.11.0-SNAPSHOT;1.11.3: not found
[warn]  :: org.scalaz#scalaz-core_2.11.0-SNAPSHOT;7.0.5: not found
[warn]  :: org.scalaz#scalaz-concurrent_2.11.0-SNAPSHOT;7.0.5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by retronym** [comment]
That build is run with: http://typesafehub.github.io/distributed-build/0.7.0/index.html which builds those projects from sources and rewires the dependencies.

An alternative is to:
- build specs with scalaVersion = 2.11.0-M8,
- `sbt> export subProject/compile`
- use the output to run the compiler from the command line, and point to your build

**Comment by xeno-by** [comment]
I see, thanks.

**Comment by xeno-by** [comment]
Will resubmit later.

**Pull request closed without merging**
