### PR TITLE
Merge 2.12 to 2.13 Mar 16

### PR DESCRIPTION
**Pull request by lrytz**
```
 scala3 git:(2.13.x) git checkout -b merge-2.12-to-2.13-mar-16

 scala3 git:(merge-2.12-to-2.13-mar-16) git lg -n 1 | cat
*   02e985d214 - (HEAD -> merge-2.12-to-2.13-mar-16, upstream/2.13.x, 2.13.x) Merge pull request #6409 from retronym/topic/scala-xml-js (3 days ago) <Seth Tisue>

 scala3 git:(merge-2.12-to-2.13-mar-16) git lg -n 1 upstream/2.12.x | cat
*   30a1428925 - (upstream/2.12.x) Merge pull request #6434 from lrytz/sona-clean (10 minutes ago) <Lukas Rytz>

 scala3 git:(merge-2.12-to-2.13-mar-16) export mb=$(git merge-base upstream/2.12.x 2.13.x)
 scala3 git:(merge-2.12-to-2.13-mar-16) git log --graph --oneline --decorate $mb..upstream/2.12.x | cat
*   30a1428925 (upstream/2.12.x) Merge pull request #6434 from lrytz/sona-clean
|\
| * 3634f78564 Run clean before sonatype publishSigned
|/
*   25364a5fd3 Merge pull request #6433 from lrytz/sbt-info
|\
| * 9b3ec8a942 Some cleanups in the build.
| * 415ba063fe Keep sbt's log level at info on travis / jenkins
* |   d532042fd4 Merge pull request #6422 from ryan-williams/bug-10775
|\ \
| |/
|/|
| * 8e2faf87b3 verify that ~/.credentials is not a directory
* | 89d79ddadc Clean better.
* |   30e33b08d2 Merge pull request #6431 from lrytz/ivy-cache
|\ \
| * | ccf99e7f7a fix IVY2_DIR, and ensure functions cd back to WORKSPACE
|/ /
* |   5f31d0d1e5 Merge pull request #6430 from lrytz/ivy-cache
|\ \
| * | d8473d2988 Clear scala parts of ivy cache on travis
|/ /
* |   cb5195913a Merge pull request #6429 from lrytz/sbt-fun
|\ \
| * | 9f651ee871 sbt fun: don't call `set ...` after `setupBootstrapPublish`
|/ /
* |   4e691cb5f8 Merge pull request #6428 from lrytz/pgp-settings
|\ \
| * | 47eac6312d Set sbt-pgp settings in the bootstrap script
|/ /
* |   b8f8753c5c Merge pull request #6427 from scala/quick-doc
|\ \
| |/
|/|
| * d203b870a9 Build scaladoc in quick
|/
*   1d51494599 Merge pull request #6419 from lrytz/windows-test
|\
| * d8ceec44ec Avoid ? in filename, not allowed in Windows
|/
*   64208ae4b2 Merge pull request #6177 from som-snytt/issue/10612
|\
| * b0a6c8343b Some comments about re-typing implicit applications
| * 3ce99cee35 Method values are always eta-expanded
| * 3bc6bab3fc Adapt method values more cannily, part 1
* |   3d8c826a07 Merge pull request #6414 from hrhino/kindness
|\ \
| * | 2789e264f9 Put back one-argument require for the convenience of downstream users.
* | |   66070c5989 Merge pull request #6412 from retronym/topic/classloader-cache
|\ \ \
| * | | 767ea02f41 Disable macro/plugin class loader caching, by default
* | | |   a575511371 Merge pull request #6400 from scalacenter/ticket/10764
|\ \ \ \
| * | | | 4ce0f67aae Handle escaping characters in URL -> file
* | | | |   85f684d9a6 Merge pull request #6362 from retronym/topic/mr-jar
|\ \ \ \ \
| * | | | | 3bbf53a5e0 Minor cleanups
| * | | | | 4fd0629488 Support multi-release JARs / compile for older platform (JEP 238/247)
| | |/ / /
| |/| | |
* | | | |   4a4667b08f Merge pull request #6316 from rorygraves/pkukielka/2.12.x_distinct
|\ \ \ \ \
| |_|_|/ /
|/| | | |
| * | | | b9be25c660 Reduce allocation and CPU usage in distinct
| * | | | 3e74e03faa Add JMH benchmarks for distinct
|  / / /
* | | |   34b5c42931 Merge pull request #6395 from retronym/ticket/10734-auto-module-name
|\ \ \ \
| * | | | dd1631348d Add Automatic-Module-Name attribute to library, reflect, compiler
* | | | |   352baae1c1 Merge pull request #6273 from som-snytt/issue/10695
|\ \ \ \ \
| * | | | | aaaf9e4421 Improve error messages for method references
* | | | | |   4924c38022 Merge pull request #6404 from adriaanm/t10763
|\ \ \ \ \ \
| |_|_|/ / /
|/| | | | |
| * | | | | 4485245611 `qual` is used in `qual.withFilter(fun)`, but `fun` is exempt
* | | | | |   3c50226407 Merge pull request #6408 from lrytz/travis-trigger-dist
|\ \ \ \ \ \
| |_|/ / / /
|/| | | | |
| * | | | | d474de9173 Travis: benchq webhook
|/ / / / /
* | | | |   30f2646b11 Merge pull request #6406 from lrytz/travis-trigger-dist
|\ \ \ \ \
| * | | | | 50b53334a3 travis: source scripts in publish stage...
* | | | | |   4c1ff6a405 Merge pull request #6403 from lrytz/travis-trigger-dist
|\ \ \ \ \ \
| |/ / / / /
| | | | | /
| |_|_|_|/
|/| | | |
| * | | | 2ea7b2e3f5 Trigger scala-dist after a successful build
| | |_|/
| |/| |
* | | |   2ef689ad8d Merge pull request #6402 from adriaanm/release-the-travis
|\ \ \ \
| |_|/ /
|/| | |
| * | | 47d38ecb21 Serialize env vars more robustly to build/env
* | | |   f64a20feb1 Merge pull request #6385 from dwijnand/build/inline-testAll-task-labels
|\ \ \ \
| |/ / /
|/| | |
| * | | fc9a95b0a0 Define testAll's task labels inline
| | |/
| |/|
* | |   94f6aa5dc8 Merge pull request #6399 from lrytz/pr6387
|\ \ \
| |_|/
|/| |
| * | d76263cb2e Add extra quotes to fix paths with spaces in them
|/ /
* |   3a95dabaf0 Merge pull request #6390 from adriaanm/release-the-travis
|\ \
| * | 4769a7df5c (upstream/release-the-travis) Hopefully last round of cleanups
| * | 2a0a742de7 Cleanups, skip tests for now
| * | 8fc5de23fb Review feedback from lrytz
| * | 9f54360df3 Exclude PR validation as a trigger
| * | 4d5ce80804 Pull structure of bootstrap script into .travis.yml,...
| * | 41e376a265 Switch to Travis CI for building releases
| |/
* |   e4c417877c Merge pull request #6389 from retronym/topic/cleanliness
|\ \
| * | aac690c6fb Adapt to changes in clean task in SBT 0.13.17+
* | |   38c3d8fa6d Merge pull request #6396 from retronym/topic/mvn-dep-get
|\ \ \
| * | | 76b1abdba6 Simplify checking for already-published artifacts
| | |/
| |/|
* | |   39b1116ba5 Merge pull request #6326 from rorygraves/mike/2.12_x_stats
|\ \ \
| * | | 54546fce25 Threadsafe simple stats
|  / /
* | |   5017ab0e0a Merge pull request #6380 from lrytz/t9155
|\ \ \
| |/ /
|/| |
| * | 6ca54f6fe2 Correctly synthesize `manifest[T]` when `T` is an alias
* | |   2ddc01b416 Merge pull request #6373 from som-snytt/issue/10757
|\ \ \
| * | | 02b6cdadd9 REPL command completion is cursor sensitive
| |/ /
* | |   baabc2306f Merge pull request #6359 from lrytz/b10619
|\ \ \
| * | | 910c563056 Report an error when using an unstable qualifier in a type selection
* | | |   655b659bd1 Merge pull request #6377 from retronym/topic/workaround-sbt-test-race
|\ \ \ \
| * | | | a6873a2ebe Disable parallelism in the scalacheck suite
* | | | |   1a8dfbb350 Merge pull request #6343 from scalacenter/topic/fix-original-tree-attachment
|\ \ \ \ \
| |_|_|_|/
|/| | | |
| * | | | a36b7383d3 Don't add original attachment for constant folded trees
|  / / /
* | | |   749a633545 Merge pull request #6353 from som-snytt/issue/10721
|\ \ \ \
| |/ / /
|/| | |
| * | | 45e53dac4e Test completion of char literal
| * | | 034c0bec4c Enable implicits to check completion enrichment
|  / /
* | |   d0f3c25be3 Merge pull request #6337 from Philippus/issue/10728
|\ \ \
| |_|/
|/| |
| * | 0714bfefea Set pointer-events to none in headings
|  /
* |   fc39f785ca Merge pull request #6240 from som-snytt/issue/respect-maxerrs
|\ \
| * | b53fdefee3 Review: be less annoying, more conforming
| * | 92e7a9fae8 Enforce maxerrs more robustly
|  /
* |   a52c91c571 Merge pull request #6252 from hrhino/better-java-module-kind
|\ \
| |/
|/|
| * 55da02d3c5 Improve error message when using a Java class as a value.
*   5a962cd93f Merge pull request #6249 from howtonotwin/fix/7420
|\
| * c5fb888d6c Fix typo
| * 566ed7164a Make Typer#dyna.mkInvoke more accurate
* 253005c6fa Merge pull request #6345 from hrhino/reflect-assert
* 32ad4a233f Also augment assertion errors raised in reflect.



 scala3 git:(merge-2.12-to-2.13-mar-16) git merge upstream/2.12.x
Auto-merging test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Removing test/junit/scala/tools/nsc/SampleTest.scala
Auto-merging test/files/neg/t7251.check
CONFLICT (content): Merge conflict in test/files/neg/t7251.check
CONFLICT (modify/delete): test/files/neg/t7187.scala deleted in HEAD and modified in upstream/2.12.x. Version upstream/2.12.x of test/files/neg/t7187.scala left in tree.
CONFLICT (modify/delete): test/files/neg/t7187.check deleted in HEAD and modified in upstream/2.12.x. Version upstream/2.12.x of test/files/neg/t7187.check left in tree.
CONFLICT (modify/delete): src/repl/scala/tools/nsc/interpreter/Completion.scala deleted in HEAD and modified in upstream/2.12.x. Version upstream/2.12.x of src/repl/scala/tools/nsc/interpreter/Completion.scala left in tree.
Auto-merging src/repl-frontend/scala/tools/nsc/interpreter/shell/LoopCommands.scala
CONFLICT (content): Merge conflict in src/repl-frontend/scala/tools/nsc/interpreter/shell/LoopCommands.scala
Auto-merging src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
Auto-merging src/reflect/scala/reflect/internal/Trees.scala
Auto-merging src/reflect/scala/reflect/internal/TreeGen.scala
Auto-merging src/reflect/scala/reflect/internal/Symbols.scala
Auto-merging src/reflect/scala/reflect/internal/SymbolTable.scala
CONFLICT (modify/delete): src/reflect/mima-filters/2.12.0.forwards.excludes deleted in HEAD and modified in upstream/2.12.x. Version upstream/2.12.x of src/reflect/mima-filters/2.12.0.forwards.excludes left in tree.
Auto-merging src/library/scala/collection/SeqLike.scala
Auto-merging src/compiler/scala/tools/util/PathResolver.scala
Auto-merging src/compiler/scala/tools/reflect/ToolBoxFactory.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Typers.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/typechecker/Typers.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/StdAttachments.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/typechecker/StdAttachments.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
Auto-merging src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
Auto-merging src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
Auto-merging src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
Auto-merging src/compiler/scala/tools/nsc/Global.scala
Auto-merging scripts/jobs/integrate/bootstrap
CONFLICT (content): Merge conflict in scripts/jobs/integrate/bootstrap
Auto-merging project/ScalaOptionParser.scala
Auto-merging build.sbt
Auto-merging .travis.yml
CONFLICT (content): Merge conflict in .travis.yml
Automatic merge failed; fix conflicts and then commit the result.
```

### CODE REVIEW

**Comment by lrytz** [comment]
A few minor things to merge manually
  - `.travis.yml` had a different `PRIV_KEY_SECRET` on 2.13.x (8066246f15964e33603ff1ca8f7ef27c98774483)
  - https://github.com/scala/scala/pull/6373 was easy to port from `nsc/interpreter/LoopCommands.scala` to `nsc/interpreter/shell/LoopCommands.scala`
  - two recent changes to the 2.13 bootstrap script: f5008f967953b98fafb8c489a3339897bb1f18c4, f938cd2148605739febb6701384735ac9e7d63fb

The rest was quite trivial

**Comment by lrytz** [comment]
Build passed, who'd like to review?

**Comment by SethTisue** [comment]
I'll review... I had taken my own stab at this but didn't finish before NE Scala prep hit, so I'm familiar with the changes

**Comment by SethTisue** [comment]
@hrhino you can deprecate the one-arg `require` and `assert` now

**Comment by SethTisue** [comment]
@lrytz https://travis-ci.org/scala/scala/jobs/354791778 failed with `sbt.ResolveException: unresolved dependency: org.scala-lang.modules#scala-xml_2.13.0-pre-1002705;1.1.0: not found`

**Comment by SethTisue** [comment]
community build likes it https://github.com/scala/community-builds/pull/695

**Comment by lrytz** [comment]
will fix the xml build thing, it's easy. just need to up my bash fu a bit to do it right.

**Pull request merged**
