### PR TITLE
Update stripPrefix/StringLike docs to talk about no op case

### PR DESCRIPTION
**Pull request by adriaanm**
rework of #3950:
- rebased on 2.11.x
- incorporated review comments by @som-snytt

### CODE REVIEW

**Comment by adriaanm** [comment]
I just built my window in the style of the existing ones. Hope they aren't all broken now.
More technically, I assumed returning those constants was somehow done for performance and who am I to question performance.

**Comment by som-snytt** [comment]
LGTM.  If the tests pass.  Adriaan has been away so long, he may not realize that Jenkins now automatically generates a newbie question on StackOverflow based on the scaladoc, and if an answer comes in that says RTFM, then it's good to go.  Then Jenkins either accepts the SO answer or deletes it as a duplicate.

**Comment by som-snytt** [comment]
I always forget whether substring was optimized or de-optimized in Java 7, and then I forget whether Scala is still on Java 6.  Until Jenkins complains that I used `Collections.emptyEnumeration`.  Jenkins would make the most annoying roommate ever.  You'd think it would be nice with such a tidy and helpful fellow, but his constant suggestions just grate on the nerves.

**Comment by gkossakowski** [comment]
Jenkins "Scala 2.12.x" edition might be turn to be a more palatable companion once we switch to Java 8. I hope this to happen before european kids start sliding on frozen puddles.

**Pull request merged**
