### PR TITLE
REPL: JLine: stop using deprecated JNA

### PR DESCRIPTION
**Pull request by SethTisue**
as @Friendseeker pointed out on https://github.com/sbt/sbt/pull/7811 , the JLine 3 doc says:

> Since JLine 3.24.0, JLine provides its own JNI based provider and native libraries. This is the best default choice, with no additional dependency.

At the time we initially moved from JLine 2 to 3, we didn't have any particular reason for picking JNA over JNI as best I can recall; the main past discussion I can find is https://github.com/scala/scala/pull/8036 

So, I suggest we fall in line with the new suggested default.

As well as falling in line with what sbt is doing at https://github.com/sbt/sbt/pull/7811

### CODE REVIEW

**Comment by lrytz** [comment]
that would be great!

we need to do manual testing: OSs x different terminals x (sbt, scala cli, vanilla) x ...

**Comment by SethTisue** [comment]
I suggest we merge the PR so that people can easily test using a nightly build. We could always revert later if necessary, though I think that's relatively unlikely to happen.

**Review by lrytz — APPROVED** [review]
sounds good to me

**Comment by SethTisue** [comment]
`scala-cli -S 2.nightly` now includes this change 👍

**Pull request merged**
