### PR TITLE
SI-6715 Scaladoc: Use an encoded name if a decoded name is ""

### PR DESCRIPTION
**Pull request by kzys**
In Scala, we can define a method named "$$" but Scaladoc couldn't treat
the method correctly because the decoded name of the method was "".

### CODE REVIEW

**Comment by paulp** [comment]
This is not the right fix, unless scaladoc is going to be the only thing affected by a symbol with an empty nameString, which seems pretty unlikely.

**Comment by kzys** [comment]
Got it. I moved it from Scaladoc to src/reflect/scala/reflect/internal/Symbols.scala.

**Comment by JamesIry** [comment]
since @paulp already started a review, I'll throw this his way.

**Comment by paulp** [comment]
I think this is still the wrong spot; "originalName" should never return the empty string.

Also, test/files/run/t6517.scala should presumably be test/files/run/t6715.scala.

**Comment by kzys** [comment]
Do you mean TermNames#originalName? Also I couldn't find a way to test the originalName directly.

**Comment by kzys** [comment]
Hmm, can we backport your unexpandedName as originalName in 2.10.x?
https://github.com/scala/scala/pull/2289/files#L17R361

**Comment by paulp** [comment]
That's kind of what I had my eye on, except I was avoiding selectively backporting; I was going for "convergence of implementation", so at least the logic would be consistent. I suggest you take the logic from that method and use it in originalName (which I guess amounts to backporting.)

**Comment by paulp** [comment]
LGTM. Thanks for your persistance.

**Pull request merged**
