### PR TITLE
Avoid bad generic signatures when mixin forwarders tparams shadow

### LINKED ISSUE #11523: investigate javac compilation error in akka testkit
Seems like https://github.com/scala/scala/pull/7966  did break something in akka testkit -- haven't looked beyond copy pasting the error from https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2087/consoleText:

```
akka-testkit/src/main/java/akka/testkit/JavaTestKit.java:150:1: <R>compose(scala.PartialFunction<R,T1>) in scala.runtime.AbstractPartialFunction cannot implement <R>compose(scala.PartialFunction<R,A>) in scala.PartialFunction
  return type scala.PartialFunction<R,R> is not compatible with scala.PartialFunction<R,java.lang.Object>
          new JavaPartialFunction<Object, Object>() {
akka-testkit/src/main/java/akka/testkit/JavaTestKit.java:561:1: <R>compose(scala.PartialFunction<R,T1>) in scala.runtime.AbstractPartialFunction cannot implement <R>compose(scala.PartialFunction<R,A>) in scala.PartialFunction
  return type scala.PartialFunction<R,R> is not compatible with scala.PartialFunction<R,T>
                  new CachingPartialFunction<Object, T>() {

(akka-testkit / Compile / compileIncremental) javac returned non-zero exit code
```

### PR DESCRIPTION
**Pull request by retronym**
... referenced type parameters of an enclosing class.

Rename the type parameters of mixin forwarders when shadowing is detected.

Fixes scala/bug#11523

### CODE REVIEW

**Comment by retronym** [comment]
We may also want to avoid hitting this automatic rename in API parts of the standard library by judiciously renaming a few type parameters manually.

```
Renaming type A (owned by method compose, a mixin forwarder hosted in scala.collection.AbstractSet) to avoid shadowing enclosing type parameter of scala.collection.AbstractSet)
Renaming type A (owned by method andThen, a mixin forwarder hosted in scala.collection.AbstractSet) to avoid shadowing enclosing type parameter of scala.collection.AbstractSet)
Renaming type R (owned by method compose, a mixin forwarder hosted in scala.runtime.AbstractPartialFunction) to avoid shadowing enclosing type parameter of scala.runtime.AbstractPartialFunction)
Renaming type C (owned by method andThen, a mixin forwarder hosted in scala.PartialFunction.AndThen) to avoid shadowing enclosing type parameter of scala.PartialFunction.AndThen)
Renaming type C (owned by method andThen, a mixin forwarder hosted in scala.PartialFunction.AndThen) to avoid shadowing enclosing type parameter of scala.PartialFunction.AndThen)
Renaming type A (owned by method compose, a mixin forwarder hosted in scala.PartialFunction.AndThen) to avoid shadowing enclosing type parameter of scala.PartialFunction.AndThen)
Renaming type C (owned by method andThen, a mixin forwarder hosted in scala.PartialFunction.Combined) to avoid shadowing enclosing type parameter of scala.PartialFunction.Combined)
Renaming type C (owned by method andThen, a mixin forwarder hosted in scala.PartialFunction.Combined) to avoid shadowing enclosing type parameter of scala.PartialFunction.Combined)
Renaming type A (owned by method compose, a mixin forwarder hosted in scala.PartialFunction.Combined) to avoid shadowing enclosing type parameter of scala.PartialFunction.Combined)
Renaming type B (owned by method map, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method appended, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method prepended, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method concat, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method appendedAll, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method prependedAll, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method sorted, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method startsWith, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method startsWith$default$2, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method endsWith, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method indexOf, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method indexOf, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method lastIndexOf, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method lastIndexOf$default$2, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method indexOfSlice, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method indexOfSlice, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method lastIndexOfSlice, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method lastIndexOfSlice, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method sameElements, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method corresponds, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method search, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method search, a mixin forwarder hosted in scala.collection.SeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.SeqView.Map)
Renaming type B (owned by method appended, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method prepended, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method map, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method concat, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method appendedAll, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method prependedAll, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method stepper, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method search, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type B (owned by method search, a mixin forwarder hosted in scala.collection.IndexedSeqView.Map) to avoid shadowing enclosing type parameter of scala.collection.IndexedSeqView.Map)
Renaming type A (owned by method compose, a mixin forwarder hosted in scala.collection.AbstractSeq) to avoid shadowing enclosing type parameter of scala.collection.AbstractSeq)
Renaming type K (owned by method groupBy, a mixin forwarder hosted in scala.collection.SortedMapOps.KeySortedSet) to avoid shadowing enclosing type parameter of scala.collection.SortedMapOps)
Renaming type K (owned by method groupMap, a mixin forwarder hosted in scala.collection.SortedMapOps.KeySortedSet) to avoid shadowing enclosing type parameter of scala.collection.SortedMapOps)
Renaming type K (owned by method groupMapReduce, a mixin forwarder hosted in scala.collection.SortedMapOps.KeySortedSet) to avoid shadowing enclosing type parameter of scala.collection.SortedMapOps)
Renaming type K (owned by method toMap, a mixin forwarder hosted in scala.collection.SortedMapOps.KeySortedSet) to avoid shadowing enclosing type parameter of scala.collection.SortedMapOps)
Renaming type K (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.MapKeyIterator) to avoid shadowing enclosing type parameter of scala.collection.immutable.MapKeyIterator)
Renaming type V (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.MapValueIterator) to avoid shadowing enclosing type parameter of scala.collection.immutable.MapValueIterator)
Renaming type K (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.MapKeyValueTupleIterator) to avoid shadowing enclosing type parameter of scala.collection.immutable.MapKeyValueTupleIterator)
Renaming type V (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.MapKeyValueTupleIterator) to avoid shadowing enclosing type parameter of scala.collection.immutable.MapKeyValueTupleIterator)
Renaming type K (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.MapKeyValueTupleReverseIterator) to avoid shadowing enclosing type parameter of scala.collection.immutable.MapKeyValueTupleReverseIterator)
Renaming type V (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.MapKeyValueTupleReverseIterator) to avoid shadowing enclosing type parameter of scala.collection.immutable.MapKeyValueTupleReverseIterator)
Renaming type V (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.MapKeyValueTupleHashIterator) to avoid shadowing enclosing type parameter of scala.collection.immutable.MapKeyValueTupleHashIterator)
Renaming type K (owned by method groupBy, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap1) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap1)
Renaming type K (owned by method groupMap, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap1) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap1)
Renaming type K (owned by method groupMapReduce, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap1) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap1)
Renaming type K (owned by method groupBy, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap2) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap2)
Renaming type K (owned by method groupMap, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap2) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap2)
Renaming type K (owned by method groupMapReduce, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap2) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap2)
Renaming type K (owned by method groupBy, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap3) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap3)
Renaming type K (owned by method groupMap, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap3) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap3)
Renaming type K (owned by method groupMapReduce, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap3) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap3)
Renaming type K (owned by method groupBy, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap4) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap4)
Renaming type K (owned by method groupMap, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap4) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap4)
Renaming type K (owned by method groupMapReduce, a mixin forwarder hosted in scala.collection.immutable.SeqMap.SeqMap4) to avoid shadowing enclosing type parameter of scala.collection.immutable.SeqMap.SeqMap4)
Renaming type V (owned by method toMap, a mixin forwarder hosted in scala.collection.immutable.VectorMap.$anon$2) to avoid shadowing enclosing type parameter of scala.collection.immutable.VectorMap)
Renaming type A (owned by method compose, a mixin forwarder hosted in scala.jdk.Accumulator) to avoid shadowing enclosing type parameter of scala.jdk.Accumulator)
```

**Comment by retronym** [comment]
Here's a straw man [patch](https://github.com/retronym/scala/tree/topic/renametparams) to with manual renames. I'm not sure how much of this we should actually do. Maybe just the changes to `scala.*Function` ?

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
Compiler changes look good. I'm torn on the manual renames. @lrytz, @szeiger WDYT?

**Comment by adriaanm** [comment]
Running community build for akka on this PR: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2107

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
I'm fine keeping the type param names we currently have

**Comment by adriaanm** [comment]
akka is green again in the community build, so --> merging!

**Comment by szeiger** [comment]
When would users encounter type parameters in mixin forwarders? Do they ever show up in Scala? Or when using Scala code from Java?

**Comment by adriaanm** [comment]
When using Java to extend a Scala class that mixed in bunch of traits.

**Comment by lrytz** [comment]
The type params of mixing forwarders don't show up when writing Scala code, but when using a Scala class with a mixin forwarder in Java. Note that type params are only renamed in this PR if they are actually conflicting, i.e., if the method signature references some other type param from the enclosing class that has a matching name.

**Pull request merged**
