### PR TITLE
SI-8010 Fix regression in erasure double definition checks

### PR DESCRIPTION
**Pull request by retronym**
Calls to `Symbol#info` during scope iteration considered harmful.

Looks like calling `info` during this Scope iteration is triggering
the ExplicitOuter info transformer, which "makes all super accessors
and modules in traits non-private, mangling their names.". This name
change necessitates a rehashing of the owning scope, which I suspect
is enough to corrupt the ScopeEntry-s being traversed in
`checkNoDeclaredDoubleDefs`.

The upshot was that we encountered the same symbol twice, which was
reported as being a double-definition.

This problem only showed up after 086702d8a74, which did nothing
worse then change the order in which `{e, e1}.sym.info` were
forced.

I inspected SymbolPairs/OverridingPairs which _appear_ to be immune
as they only test flags during scope iteration; infos are not used
until later, at which point we're iterating a temporary scope that
isn't part of the type of the owner of the symbols.

Review by @xeno-by

### CODE REVIEW

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
lgtm

**Comment by adriaanm** [comment]
@xeno-by when you merge PRs, please remember to close the associated JIRA ticket

**Comment by xeno-by** [comment]
@adriaanm I will. Sorry.

**Pull request merged**
