### PR TITLE
Use invokedynamic to statically cache materialized class tags (initially disabled by default)

### PR DESCRIPTION
**Pull request by retronym**
During compiler profiling, I've found cases where the repeated allocation 
of `s.r.ClassTags` (a wrapper over j.l.Class) contributed to allocation 
pressure.

This commit introduces a static cache at the materialization site using
invokedynamic. This is analagous to the way we cache Symbol literals.

### CODE REVIEW

**Comment by retronym** [comment]
Marking for (late) consideration for 2.13.0 because binary compatibility constraints would not allow us to add the bootstrap method in 2.13.x

**Comment by lrytz** [comment]
Could `ClassTag` be a value class / opaque type?

**Comment by retronym** [comment]
That sounds like a good use case for value classes, but it would take a bit of work to untangle the current design from `ClassManifest`

**Comment by NthPortal** [comment]
> Could `ClassTag` be a value class / opaque type?

One issue is that `ClassTag` also has a `newArray` method which `j.l.Class` does not

**Comment by retronym** [comment]
An alternative approach to `invokeydynamcic`-based, per-call-site caching, would be to use a global runtime cache. The JDK has a suitable data structure for this: `ClassValue`, and that is lock-free, and avoids classloader leaks.

https://github.com/scala/scala/pull/7879

**Comment by lrytz** [comment]
> it would take a bit of work to untangle the current design from `ClassManifest`

Yes :-) But maybe it's time to do that, instead of adding more complexity (even if hidden behind the scenes) to ClassTag?

> One issue is that `ClassTag` also has a `newArray` method which `j.l.Class` does not

I don't see why that wouldn't work though?

> `ClassValue`

Right, that seems like a good fit.

**Comment by retronym** [comment]
Pulling this thread a little further, I'm trying to unify symbol literal, structural call site, and class tag caching behind a single bootstrap method.

**Pull request closed without merging**
