### PR TITLE
Move lambda bodies to methods on their owning class

### PR DESCRIPTION
**Pull request by JamesIry**
This PR makes the bodies of lambdas ordinary inner methods, which
then get lifted to top level methods by LambdaLift. The anonymous
FunctionN class for the lambda now has a simple apply method that
delegates to the new method.

### CODE REVIEW

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by magarciaEPFL** [comment]
Regarding 6ebbe6f , some additional information, cross-referencing:

Related bug: https://issues.scala-lang.org/browse/SI-6730

Related discussion: https://groups.google.com/d/msg/scala-internals/tL2XB2-ErZU/VMlzEE_VLiQJ

**Comment by JamesIry** [comment]
BUILDLOG?

**Comment by JamesIry** [comment]
PLS REBUILD/pr-checkin-per-commit@a8e7ca9

**Comment by adriaanm** [comment]
It launched the new job, but it's showing the failure of the older one. This is new behavior. From the comments in the build bot: (yes, it has comments!)

```
// We want to ensure that a PR is only ok if all commits and all jobs are ok.
// Unfortunately, GitHub only looks at the most recent status of the last commit
// of the PR to determine the status of the whole PR. As we can only prepend new
// statuses to a commit while having to support multiple jobs per commit and
// multiple commits per PR, we implement the following strategy to implement the
// desired behaviour. For every commit, we copy error/pending jobs that have no
// corresponding success to the head of the list. For the last commit, we add a
// fake pending status if there are earlier commits that meet the above
// condition (having an error/pending status without corresponding success).
```

**Comment by JamesIry** [comment]
I'm going to regenerate this PR

**Comment by JamesIry** [comment]
Subsumed by https://github.com/scala/scala/pull/2218

**Pull request closed without merging**
