### PR TITLE
Spin off xml library as scala-library-xml.

### PR DESCRIPTION
**Pull request by adriaanm**
1. wean core sources (those built by locker: library/reflect/compiler) off xml
2. make compiler flexible: 
   - don't require scala.xml unless xml literals were parsed
   - when Predef.$scope does not exist, but scala.xml.TopScope does, alias the latter to $scope (our old xml library assumes $scope is always in scope)
3. spin off scala.xml.\* to src/library-xml and scala-library-xml.jar, and remove Predef.$scope (the last dependency of core sources on xml)

review by @retronym, @paulp, and anyone else who'd like to dance on scala.xml's shallow grave.

### CODE REVIEW

**Comment by soc** [comment]
Very nice.

Would it be possible to keep the directory name consistent with the package name? I know that having a directory called "xml" feels weird, but better than having a naming pattern which is followed except for one library, imho.

**Comment by adriaanm** [comment]
Thanks. I'd rather emphasize it's a module of the "standard" library.
By my count, only 20% of the directories under src/ have a name that matches the package name under the top-level package.

**Comment by adriaanm** [comment]
The idea would be that the pattern `library-*` matches all the modules that once were part of `library`.
I was actually planning to rework #2661 to follow this convention.

**Comment by soc** [comment]
The first 7 commits (those which compile) LGTM.

Names: Might be purely subjective, but I don't like the idea. The name prefix adds some significance to it, which those packages don't have. What about actors, swing?

Strategy in general: Would it be possible/make sense to move toward a design which allows arbitrary libraries to plug into the XML functionality? E. g. the compiler exposes an interface and looks up an appropriate implementation via the `java.util.ServiceLoader` API?

**Comment by adriaanm** [comment]
Agreed. Preparing new commits that follow your suggested naming.

**Comment by adriaanm** [comment]
> Strategy in general: Would it be possible/make sense to move toward a design which allows arbitrary libraries to plug into the XML functionality? E. g. the compiler exposes an interface and looks up an appropriate implementation via the java.util.ServiceLoader API?

This is already supported, though more hackily. You can plug in your own scala.xml library, as long as it exposes the same factory methods as used by the current scala.xml. We should probably document this, but I'd have to reverse engineer it myself as well.

The "interface" is implemented in https://github.com/adriaanm/scala/blob/a3be9e5d98b58be8eb8d7bd81920511e8d820f3e/src/compiler/scala/tools/nsc/ast/parser/SymbolicXMLBuilder.scala

**Comment by paulp** [comment]
The only methods you should willingly expose (and probably not like this, as it builds "I'll just pass you a pile of mutable state and you can mutate it and on we'll go" into the api) but in principle:

```
def xmlLiteral() : Tree
def xmlLiteralPattern() : Tree
```

That leaves the entirety of SymbolicXmlBuilder an unseen implementation detail, as it merits.

**Comment by adriaanm** [comment]
> That leaves the entirety of SymbolicXmlBuilder an unseen implementation detail, as it merits.

I was thinking of a scala-virtualized-style or a for-comprehension-style interface. We desugar <xml> into method calls, you better make sure you provide them methods.

**Comment by paulp** [comment]
Oh, I thought the mention of reverse engineering might mean you were a threat to publish the existing methods. It would be a shame to make a for-comprehension style hook specific to xml... imagine being able to register one's own XMLSTART.

**Comment by soc** [comment]
I think providing a bit of documentation on how to plug into the XML mechanism could make a huge difference to those other few XML libraries out there.
In the worst case, just like without documentation, nothing happens, but in the best case, we might get feedback and improvements back.

**Comment by adriaanm** [comment]
@soc, Definitely -- I was merely implying the documentation will have to be reverse engineered by me orrrrrr anyone else, really. I have had the good fortune of not being exposed to the xml library's implementation except for this PR.

@paulp, omg -- xml macros!

**Comment by adriaanm** [comment]
NOTE to potential merger: this must first be validated against sbt & the ide /cc @huitseeker, @harrah

**Comment by harrah** [comment]
From a brief review, I don't see any obvious breakages, so I leave it to the machines to validate further.  (Once xml is actually a separate jar, it will require some changes to the builds of projects that use xml.)

**Comment by gkossakowski** [comment]
@harrah: the idea is to rename `scala-library` to `scala-library-core` and then ship an aggregate pom.xml for `scala-library` which depends on all modules. This way we provide backwards compatibility for dependencies. However, tools that have hardcoded assumptions about `scala-library.jar` will probably break. Is this ok?

**Comment by harrah** [comment]
This is different from what has been previously discussed on scala-internals, which is what sbt 0.13 is based on.  The most recent discussion that I'm aware of: https://groups.google.com/d/topic/scala-internals/tT1pjH5GECE/discussion

**Comment by gkossakowski** [comment]
@harrah: oh yes, thanks for the pointer to that discussion. At the time I couldn't participate in it because I couldn't type. I think we should resume it. The problem with that proposal is that we won't be backwards compatible when it comes to dependencies. I don't think this is a good idea.

**Comment by adriaanm** [comment]
@cunei, @huitseeker, @harrah -- I think this is good to go, but since it affects your projects, I'd like a review from all of you. I explained my reasoning on Mark's thread: https://groups.google.com/d/topic/scala-internals/tT1pjH5GECE/discussion

**Comment by adriaanm** [comment]
@harrah, sorry I missed your comment above: the result of this PR will be a separate jar for the xml library -- in this commit: c1136920db

**Comment by harrah** [comment]
Ah, missed those later commits, sorry.  I think it will be hard to handle this without some transient breakage or different branches.  Some code in sbt uses xml literals, so it would need to have a dependency on the xml jar, but of course only a future 2.11 version will publish that module.  Aggregation wouldn't be any better, since sbt isn't set up to handle scala-library as the aggregate, so that wouldn't work in the near future either.  Since the IDE is the main consumer of sbt built against 2.11, I'll see what they want to do.

**Comment by cunei** [comment]
When dbuild scans the projects, during its initialization, it needs to know which artifacts will be produced later, during the compilation stage. This is necessary in order to be able to build a graph of all the dependencies, and to adapt them prior to the actual compilation of all the projects. Would it be possible to add a suitable ant task, or have a well-defined mechanism by which I can extract this information from the current Scala source checkout, moving forward? I see in this pull request a "docs.compiler.path", whose content is already somewhat close to what would be needed.
At the moment I am using the following hard-coded list, but a more stable mechanism would be preferable.

```
group = "org.scala-lang"
ProjectRef("scala-library", group)
ProjectRef("scala-reflect", group)
ProjectRef("scala-actors-migration", group)
ProjectRef("scala-actors", group)
ProjectRef("scala-swing", group)
ProjectRef("jline", group)
ProjectRef("scala-compiler", group)
ProjectRef("scalap", group)
ProjectRef("partest", group)
ProjectRef("continuations", group+".plugins")
```

Sorry if this is a bit tangential to the xml modularization per se, but it seems like a good opportunity to add the proper hook as well.

**Comment by adriaanm** [comment]
I'm going to drop the last two, build-altering, jar-producing commits from this PR, so that we can already get the bulk of the work in.

My goal would be to get everything split into source folders and once we have consensus on how to deal with the difference in jars produced, submit a PR that changes the build for all of the new modules so we only suffer this pain once.

**Comment by adriaanm** [comment]
@cunei, maybe we can track some kind of dbuild config file in the repo?

Let's discuss all this on scala-internals: https://groups.google.com/d/topic/scala-internals/tT1pjH5GECE/discussion

**Comment by gkossakowski** [comment]
Was this reviewed?

**Comment by adriaanm** [comment]
Yes: https://github.com/scala/scala/pull/2667#issuecomment-19791514 -- I dropped the un-reviewed commits as explained above.

**Comment by gkossakowski** [comment]
I missed @soc's review. Sorry.

**Pull request merged**
