### PR TITLE
SI-8679 Add support for ScalaLongSignature attribute in scalap

### PR DESCRIPTION
**Pull request by mpociecha**
scalap didn't support really big class files. It was returning an
empty String for such files. The reason was that there were only
ScalaSignatures taken into account.

This commit adds support for ScalaLongSignature. We try to get such
an attribute when we didn't find ScalaSignature. Also there's added
an additional case to the logic retrieving bytes for a signature.
Since ScalaLongSignature can contain many parts, we have to merge
their byte arrays.

Changes are tested by a new partest-based test. These two files are
really big, but it was required (t8679.scala is a reduced version of
BigScalaClass - an example attached to JIRA).

### CODE REVIEW

**Comment by mpociecha** [comment]
I created a ticked to refactor / get rid of duplicates in various places in a codebase, and added TODOs to this PR (as discussed with retronym).

**Comment by mpociecha** [comment]
Regarding validate-test which failed - it's quite strange and, I think, unrelated error.
It's exactly the same code which passed previously. I simply added 3 comments with TODOs. Also it builds locally.

**Comment by lrytz** [comment]
/rebuild - the test failure is https://issues.scala-lang.org/browse/SI-9264

**Comment by lrytz** [comment]
LGTM!

**Comment by mpociecha** [comment]
@lrytz It looks that servers are down:
https://scala-ci.typesafe.com/computer/
scala-2.11.x-validate-publish-core: "waiting - All nodes of label ‘public’ are offline"

**Comment by lrytz** [comment]
yes, i noticed, i'm looking into it

**Pull request merged**
