### PR TITLE
Added test for SI-5761.

### PR DESCRIPTION
**Pull request by hubertp**
Seems that my cleanup of SI-4842 also fixed that one.
Review by @paulp or @retronym.

### CODE REVIEW

**Comment by retronym** [comment]
The test case doesn't quite match the bug report, so it isn't crystal clear that it is solved. Could you add another test file with this variation?

``` scala
class D[-A](x: A) { }

object Test {
  println(new D[Int]{})   // crash
}
```

**Comment by hubertp** [comment]
But that's in Test1 object, right?

**Comment by retronym** [comment]
Before your fix for 4842, the errors reported for two files concatenated into one did not necessarily equal the sum of the parts. Maybe that's not relevant here... I'm just being conservative.

**Comment by hubertp** [comment]
That wasn't really the problem. In order to remove the reporter.hasErrors condition in 4842 I also had to fix the assertion. This assertion was apparently also triggering SI-5761, so I think it is safe to have those in one file.

**Comment by retronym** [comment]
Gotcha, lgtm.

**Comment by adriaanm** [comment]
@hubertp, which is the actual commit/pullreq that fixes SI-5761? #735?

**Comment by hubertp** [comment]
#769

**Pull request merged**
