### PR TITLE
SI-8269 tolerates CaseDefs with empty bodies

### PR DESCRIPTION
**Pull request by xeno-by**
This commit proposes to make `CaseDef(_, _, EmptyTree)` behave the
same as `CaseDef(_, _, Literal(Constant(())))` with respect to typechecking.

It's not like we absolutely have to have that, but it would be definitely
useful for people who don't remember default values of tree parts by heart.

### CODE REVIEW

**Comment by xeno-by** [comment]
Review @retronym. This bug is not a blocker, so feel free to reschedule the pull request if you don't consider it to be a serious problem. It is a regression, yes, but after all, if one assembles casedefs with qqs, emptytrees never happen, so it shouldn't be a problem for those who use only qqs.

/cc @densh. If we make emptytree-bearing casedefs typer-equivalent to unit-bearing casedefs, then probably we should treat them uniformly in quasiquotes. 

Btw, is unit inserted in bodies of casedefs considered to be synthetic unit according to syntactic APIs?

**Comment by densh** [comment]
I can't see how `CaseDef(_, _ q"()")` is equivalent to `CaseDef(_, _, EmptyTree)`.

btw You can't construct tree with EmptyTree in that position with quasiquotes syntactically:

```
scala> cq"_ =>".sr
res2: String = CaseDef(Ident(nme.WILDCARD), EmptyTree, Literal(Constant(())))
```

Tree with EmptyTree is just wrong and adding special case to support wrong shapes of trees looks like a straight road to madness.

This change doesn't look good to me.

**Comment by densh** [comment]
Every unit inserted by compiler and not specified by the user should be marked as SyntheticUnit.

**Comment by xeno-by** [comment]
So the unit inserted by the compiler for `case foo =>` is syntactic, right? Just making sure everything works fine.

**Comment by adriaanm** [comment]
Sorry, this is not an RC blocker

**Pull request closed without merging**
