### PR TITLE
add 'constantly' function to complement 'identity'

### PR DESCRIPTION
**Pull request by dk14**
Proposing to move const (renamed as constantly) and identity together to improve language consistency.
Little conversation about: https://groups.google.com/forum/#!topic/scala-language/IgMLwK3ztjk

### CODE REVIEW

**Comment by dk14** [comment]
Predef was chosen because these functions will be moved together if people will "clean up the trash"  before 2.12 release. Name "constantly" will not intersect with any existing or popular names and most of DSL's (as far as i know).

**Comment by retronym** [comment]
I've submitted a fix for that test case to make it less fragile: #4006.

**Comment by dk14** [comment]
thank you! i didn't realize that reason is just a number of line in stack trace (was thinking that some macro is broken)

**Comment by retronym** [comment]
I'm going to close this PR. My take on the discussion surrounding this change was we're willing to live with the small irregularity now rather than make it regular at the cost of moving/adding things. I hope this doesn't dissuade you from further contributions, we're just pretty conservative these days when it comes to `Predef`.

**Comment by dk14** [comment]
Your conservativity is useless when it actually doesn't solve any problems. You scare to remove useless things and on the same time scare to add useful. So in average the language becoming overdisigned: "Heavy is good, heavy is reliable. If it doesn't work… you can always hit them with it"(c). I rather will just use it (can't find any better for enterprise) than add something new.

**Comment by paulp** [comment]
> You scare to remove useless things and on the same time scare to add useful.

Since I know just what you mean, I suggest you have a look at https://github.com/paulp/psp-std where I hope to restore some of the conceptual integrity in which the scala library is so lacking.

**Comment by Ichoran** [comment]
We're saving most of our moving-stuff budget for Don Giovanni, and for when we have a tool that will reduce the cost of moves.  Then changes that suit particular stylistic preferences will (presumably--prediction is never easy) have a lower entry barrier.

**Comment by dk14** [comment]
@paulp thanks for the link to psp-std! 
@Ichoran Could you please provide some link to the prototype of such tool? And also i didn't find any links to the Aida / Don Giovanni releases or it's only on conversation stage yet?

**Pull request closed without merging**
