### PR TITLE
Delegate null test to Option

### PR DESCRIPTION
**Pull request by janekdb**
Option(null) is None while Option(v) is Some(v) which makes the null
test redundant.

### CODE REVIEW

**Comment by janekdb** [comment]
Review by @retronym, @adriaanm, @som-snytt .

**Comment by retronym** [comment]
Looks good.

I think we should also get rid of the temporary variables, e.g. `Option(underlying.put(k, v))`.

**Comment by janekdb** [comment]
Temporary variables removed.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
