### PR TITLE
Upgrade ASM to 5.0.2

### PR DESCRIPTION
**Pull request by lrytz**
Change log: http://asm.ow2.org/history.html
- Support for Java 8 annotations (on types and method parameters)
- Fixes for stack map frames generation, maxLocals calculation

The initial commit in this PR resets all our customizations and is just a 1:1 copy of the asm
source tree. This simplifies future upgrades, see README.

The build will fail for all the intermediate commits. I can squash them to generate fewer failures,
but I think it would be good to keep at least those with [asm-cherry-pick].

### CODE REVIEW

**Comment by lrytz** [comment]
review by @gkossakowski

**Comment by retronym** [comment]
All the commits from submitted pull requests will remain in the repo. So if you squash, you can reference this PR for the full history. I would vote for squashing to keep all commits building after review.

**Comment by lrytz** [comment]
> All the commits from submitted pull requests will remain in the repo. So if you squash, you can reference this PR for the full history. I would vote for squashing to keep all commits building after review.

Are you sure they won't disappear (eventually, after I deleted my branch and github does some GC)?

**Comment by lrytz** [comment]
I could create a branch on scala/scala that contains all the intermediate commits and link to that.

**Comment by retronym** [comment]
Nope, GitHub keeps a reference to those commits in this repo.

```
% git config --global alias.pr
!git fetch -fu ${2:-origin} refs/pull/$1/head:pr/$1 && :+1:

% git pr 1
From github.com:scala/scala
 * [new ref]         refs/pull/1/head -> pr/1

% git checkout pr/1
Switched to branch 'pr/1'

% git show
commit 51f5831b0c0d14c28938a6f537b93f183217d942
Merge: 88f4ad5 1026f09
Author: Paul Phillips <paulp@improving.org>
Date:   Wed Nov 30 19:47:47 2011 -0800

    Merge pull request #2 from skyluc/master

    A bit more work on the layout layout
```

**Comment by lrytz** [comment]
I don't get it, sorry. Does `pr/1` correspond to #1 ?

Are you saying that if I `push -f` the squashed commit to my branch for this PR, the commits that are now on my branch are in the scala/scala repo and will be reachable from this PR?

**Comment by retronym** [comment]
If you `push -f` to _this_ PR, the commits will be lost. I was suggesting to close this one after it is reviewed, and submit a new one.

**Comment by adriaanm** [comment]
A good a time as any to discuss the alternative: a shaded asm, as I explored here: https://github.com/adriaanm/scala/compare/asm5

**Comment by lrytz** [comment]
The tests fail because the (ICode) inliner fails on this example:

```
class C extends scala.tools.nsc.Global(null: scala.tools.nsc.Settings) {
  assert(true) // Global#assert, not Predef
}
```

saying

```
[log inliner] Failed to load scala.tools.nsc.Global. [assertion failed: could not find posAssigner: (<param> <synthetic> x$1: tools.nsc.Global)reflect.internal.Positions$PosAssigner in tools.nsc.ast.Positions$class, members are:
  <method> <java> def <init>(<param> <synthetic> x$1: tools.nsc.Global): ast.this.Object]
```

I'm looking into that.

**Comment by gkossakowski** [comment]
I just wanted to say that I agree with @retronym's suggestion.

@lrytz: ping me once this PR is ready for review.

**Comment by lrytz** [comment]
There's the issue with the inliner I'm working on, but you can go ahead and review it anyway.

**Comment by lrytz** [comment]
@gkossakowski my latest commit should make the tests pass.

**Comment by lrytz** [comment]
Build [failure in integrate-ide](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7047/console) seems to be this - any ideas?

```
[error] java.lang.RuntimeException: The reference 0.13-2.11 is not a valid branch, or tag, or commit of this git repository
[error]     at scala.sys.package$.error(package.scala:27)
[error]     at distributed.support.git.GitProjectResolver.resolve(ProjectResolver.scala:59)
[error]     at distributed.project.resolve.AggregateProjectResolver.resolve(ProjectResolver.scala:47)
[error]     at distributed.support.BuildSystemCore$class.resolve(BuildSystemCore.scala:18)
[error]     at distributed.support.sbt.SbtBuildSystem.resolve(SbtBuildSystem.scala:15)
```

**Comment by adriaanm** [comment]
Could be transient. Maybe hit rebuild on the jenkins job?

On Thursday, May 15, 2014, Lukas Rytz notifications@github.com wrote:

> Build failure in integrate-idehttps://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7047/consoleseems to be this - any ideas?
> 
> [error] java.lang.RuntimeException: The reference 0.13-2.11 is not a valid branch, or tag, or commit of this git repository
> [error]     at scala.sys.package$.error(package.scala:27)
> [error]     at distributed.support.git.GitProjectResolver.resolve(ProjectResolver.scala:59)
> [error]     at distributed.project.resolve.AggregateProjectResolver.resolve(ProjectResolver.scala:47)
> [error]     at distributed.support.BuildSystemCore$class.resolve(BuildSystemCore.scala:18)
> [error]     at distributed.support.sbt.SbtBuildSystem.resolve(SbtBuildSystem.scala:15)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scala/scala/pull/3747#issuecomment-43245652
> .

## 

JOIN US. REGISTER TODAY! http://www.scaladays.org/
Scala http://www.scaladays.org/
Days http://www.scaladays.org/
June 16th-18th, http://www.scaladays.org/
Berlin http://www.scaladays.org/

**Comment by lrytz** [comment]
It seems all of the recent pr-scala-integrate-ide builds failed that way, starting with the one on May 14, 2014 11:55:17 (lausanne time)

**Comment by retronym** [comment]
@jsuereth Deleted the 0.13-2-11 branch of the SBT repository. We should use the 0.13 branch now, as that supports cross building for 2.10 and 2.11.

**Comment by retronym** [comment]
Submitted a fix: https://github.com/typesafehub/sbt-builds-for-ide/pull/23

/cc @skyluc

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@4b54fcf

**Comment by lrytz** [comment]
Thanks, @retronym !

**Comment by lrytz** [comment]
@gkossakowski it might obfuscated by the kitty-meow, but this PR now builds fine and is ready for review.

**Comment by gkossakowski** [comment]
I'll review tomorrow's morning. Thanks for pinging!

**Comment by lrytz** [comment]
no hurry; we should merge it (in fact, its squashed version) anyway after tagging 2.11.1.

**Comment by gkossakowski** [comment]
LGTM

Thanks for writing down instructions for upgrading to newer version of ASM. I hope we'll figure out a way to switch to vanilla asm in the future. The patches that we apply are small so it looks doable.

**Comment by lrytz** [comment]
There's one change since the LGTM. Instead of reverting the ASM commit that introduced a bug (https://github.com/lrytz/asm/commit/b73909c4b807c65843bc445fc30be3b216351b52) in InnnerClass generation, the PR now contains the fix that ASM committed (https://github.com/lrytz/asm/commit/abc3759d2ddb89fda3ebbb3ed90abb72417af4d7)

**Pull request closed without merging**
