### PR TITLE
Fix for SI-6712, bug in object lifting.

### PR DESCRIPTION
**Pull request by paulp**
Review by @retronym

### CODE REVIEW

**Comment by retronym** [comment]
LG enough TM, although I'm not familiar enough with this code to offer much review.

@paulp: Perhaps you could further elaborate in the comments in which circumstances the module var is found and in which it must be created.

/cc @adriaanm regression alert. workaround is to pick a different name for the local object.

**Comment by adriaanm** [comment]
I'm afraid this will have to be a known issue. It figures prominently at the number 1 spot in the release notes' known issues list.

It is a worry, as people do like their nesting and name recycling.

**Comment by retronym** [comment]
@adriaanm same story for RC4?

**Comment by adriaanm** [comment]
Missed this one for the RC. Sorry. I only looked at JIRA issues to be fixed by then.

**Pull request merged**
