### PR TITLE
Optimize Queue.toList and Queue.iterator

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Ichoran** [comment]
A benchmark comparing performance would be great, especially in cases where the out/in ratio is varied (heavily in favor of one, the other, or about the same).  One would expect this to perform better, but there is a not-entirely-negligible amount of extra logic in `++`ed iterators, so this should be checked.
(As with the other performance-improvement patches, using a benchmarking framework with decent warmup etc. would be good so we have a better sense of whether to trust the numbers that come out.)

**Comment by szeiger** [comment]
Blocked by #5448. I haven't benchmarked it but since `List.reverseIterator` calls `List.reverse` the performance impact is probably negative without first optimizing `reverseIterator` as proposed in #5448.

**Comment by szeiger** [comment]
Here's a benchmark:

```scala
package scala.collection.immutable

import org.openjdk.jmh.annotations._
import org.openjdk.jmh.infra._
import org.openjdk.jmh.runner.IterationType
import benchmark._
import java.util.concurrent.TimeUnit

@BenchmarkMode(Array(Mode.AverageTime))
@Fork(2)
@Threads(1)
@Warmup(iterations = 5)
@Measurement(iterations = 5)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Benchmark)
class QueueBenchmark {
  @Param(Array("10", "100", "1000"))
  var size: Int = _

  @Param(Array("0", "50", "500"))
  var size2: Int = _

  var values: Queue[Any] = _

  @Setup(Level.Trial) def initKeys(): Unit = {
    values = Queue.empty
    var i = 0
    while(i < size) {
      values = values.enqueue(i)
      i += 1
    }
    //values = (0 to size).to[Queue]
    i = 0
    while(i < size2 && !values.isEmpty) {
      values = values.dequeue._2
      i += 1
    }
  }

  @Benchmark def toList = values.toList

  @Benchmark def toListNew = values.new_toList

  @Benchmark def iterator = values.iterator.foreach(_ => ())

  @Benchmark def iteratorNew = values.new_iterator.foreach(_ => ())
}
```

Without #5548 the change to `iterator` is a clear loss in all cases but the new `toList` is a huge improvement:

```
[info] # Run complete. Total time: 00:12:46
[info]
[info] Benchmark                   (size)  (size2)  Mode  Cnt      Score      Error  Units
[info] QueueBenchmark.iterator         10        0  avgt   10     44.528 ±    1.318  ns/op
[info] QueueBenchmark.iterator         10       50  avgt   10      1.371 ±    0.074  ns/op
[info] QueueBenchmark.iterator         10      500  avgt   10      1.434 ±    0.144  ns/op
[info] QueueBenchmark.iterator        100        0  avgt   10    533.640 ±   25.116  ns/op
[info] QueueBenchmark.iterator        100       50  avgt   10    109.416 ±    1.852  ns/op
[info] QueueBenchmark.iterator        100      500  avgt   10      1.421 ±    0.046  ns/op
[info] QueueBenchmark.iterator       1000        0  avgt   10   5590.824 ±  171.612  ns/op
[info] QueueBenchmark.iterator       1000       50  avgt   10   1937.320 ±   61.287  ns/op
[info] QueueBenchmark.iterator       1000      500  avgt   10   1004.551 ±   35.081  ns/op
[info] QueueBenchmark.iteratorNew      10        0  avgt   10    191.665 ±    9.677  ns/op
[info] QueueBenchmark.iteratorNew      10       50  avgt   10     16.345 ±    0.997  ns/op
[info] QueueBenchmark.iteratorNew      10      500  avgt   10     16.169 ±    0.384  ns/op
[info] QueueBenchmark.iteratorNew     100        0  avgt   10    844.926 ±  193.981  ns/op
[info] QueueBenchmark.iteratorNew     100       50  avgt   10    137.886 ±    2.513  ns/op
[info] QueueBenchmark.iteratorNew     100      500  avgt   10     16.100 ±    0.211  ns/op
[info] QueueBenchmark.iteratorNew    1000        0  avgt   10   9739.253 ±  232.876  ns/op
[info] QueueBenchmark.iteratorNew    1000       50  avgt   10   3380.716 ±   55.320  ns/op
[info] QueueBenchmark.iteratorNew    1000      500  avgt   10   1786.588 ±   52.566  ns/op
[info] QueueBenchmark.toList           10        0  avgt   10    523.262 ±   10.843  ns/op
[info] QueueBenchmark.toList           10       50  avgt   10     24.219 ±    1.045  ns/op
[info] QueueBenchmark.toList           10      500  avgt   10     23.853 ±    1.407  ns/op
[info] QueueBenchmark.toList          100        0  avgt   10   2186.261 ±  966.129  ns/op
[info] QueueBenchmark.toList          100       50  avgt   10   1543.367 ±   29.690  ns/op
[info] QueueBenchmark.toList          100      500  avgt   10     23.278 ±    0.623  ns/op
[info] QueueBenchmark.toList         1000        0  avgt   10  14995.048 ±  254.243  ns/op
[info] QueueBenchmark.toList         1000       50  avgt   10  29165.426 ± 3306.261  ns/op
[info] QueueBenchmark.toList         1000      500  avgt   10  14869.988 ±  298.400  ns/op
[info] QueueBenchmark.toListNew        10        0  avgt   10     37.283 ±    1.114  ns/op
[info] QueueBenchmark.toListNew        10       50  avgt   10      3.631 ±    0.070  ns/op
[info] QueueBenchmark.toListNew        10      500  avgt   10      3.740 ±    0.288  ns/op
[info] QueueBenchmark.toListNew       100        0  avgt   10    349.470 ±    3.543  ns/op
[info] QueueBenchmark.toListNew       100       50  avgt   10      3.709 ±    0.089  ns/op
[info] QueueBenchmark.toListNew       100      500  avgt   10      3.748 ±    0.229  ns/op
[info] QueueBenchmark.toListNew      1000        0  avgt   10   3654.988 ±   94.186  ns/op
[info] QueueBenchmark.toListNew      1000       50  avgt   10      3.686 ±    0.096  ns/op
[info] QueueBenchmark.toListNew      1000      500  avgt   10      3.634 ±    0.070  ns/op
```

**Comment by szeiger** [comment]
This is with #5448: Still clearly on the losing side:

```
[info] QueueBenchmark.iterator      10        0  avgt   10    195.615 ±   3.022  ns/op
[info] QueueBenchmark.iterator      10       50  avgt   10     54.400 ±   1.032  ns/op
[info] QueueBenchmark.iterator      10      500  avgt   10     54.138 ±   1.531  ns/op
[info] QueueBenchmark.iterator     100        0  avgt   10   1029.989 ±  26.227  ns/op
[info] QueueBenchmark.iterator     100       50  avgt   10    220.412 ±  85.142  ns/op
[info] QueueBenchmark.iterator     100      500  avgt   10     54.348 ±   0.823  ns/op
[info] QueueBenchmark.iterator    1000        0  avgt   10  16380.510 ± 464.122  ns/op
[info] QueueBenchmark.iterator    1000       50  avgt   10   3404.228 ±  64.503  ns/op
[info] QueueBenchmark.iterator    1000      500  avgt   10   1771.745 ±  41.621  ns/op
```

**Review by szeiger — CHANGES_REQUESTED** [review]
The change to `toList` looks good but I think you should remove the `iterator` change and add some benchmarking code.

**Comment by Atry** [comment]
Hi, @szeiger , do you know if there is any way to determine the impact to garbage collector?

**Comment by szeiger** [comment]
My usual strategy is to run tests with a large data set and low heap size to trigger GC. JMH also has some support for GC profiling but I haven't used that yet.

**Comment by adriaanm** [comment]
I'm closing this PR because it has been dormant for a while now. We'd be very happy to receive a new PR that addresses points raised by the reviewer.

**Pull request closed without merging**
