### PR TITLE
Document error in Regex

### PR DESCRIPTION
**Pull request by libratiger**
There are two errors in the ```Regex``` document.

The first one is lack of a }.
The other one is error for code example.

### CODE REVIEW

**Comment by libratiger** [comment]
@janekdb can you take a look at?

**Comment by som-snytt** [comment]
Thanks, it took me a while to recall what was supposed to happen in the example. It's not clear that advancing `start` without calling `next` is unconfusing enough. That is, `hasNext` could advance the underlying matcher, but `start` could report the previous. It is clear that advancing `start` to the first match without `next` is OK, because throwing was confusing.

**Comment by libratiger** [comment]
@som-snytt 

The real problem is that the origin code example is wrong, it is not necessary call the `next` , but I just try to guess the intention of the example, and calling the `next` can output the right answer.

```scala
val ns = num.findAllIn("1 2 3")
ns.start    // 0
ns.hasNext  // true
ns.start    // 2   <---- This is wrong, the output is 0.
```

**Comment by som-snytt** [comment]
Rephrasing previous comment: the example should demonstrate something. It's trying to show that calling MatchData methods immediately don't throw: `r.findAllIn(s).start`; and that calling `hasNext` will side-effect by advancing the underlying matcher: `r.findAllIn(s).hasNext` or when called after `next`.

So correctness is important, but if it takes me time to understand what the example is for, then it's a bad example.

**Comment by libratiger** [comment]
In fact, it takes me a little time to understand the origin example, the example modified by me is still not understand quickly at first。

do you have any idea to improve this example?

**Comment by som-snytt** [comment]
The junit test I linked to previously:

https://github.com/scala/scala/blob/2.12.x/test/junit/scala/util/matching/RegexTest.scala#L119

It's almost the same, showing `hasNext` bumping `start`. But the output is a bit more obvious.

The text for the example is confusing, too, because the API is confusing. `hasNext may advance the MatchIterator and change the current MatchData.` Then the second example could say: `use findAllMatchIn to produce Match objects that capture the current match.`

When I use this API, not often, I reach for `findAllMatchIn` first because it is not subtle.

**Comment by libratiger** [comment]
How about change the text for this example to the following.

>Also, calling `hasNext` or `next` in `findAllIn` may advance the `MatchIterator` and change the current match, 
while current matched object  in `findAllMatchIn` remain valid after the iterator is advanced. 


We just need to  stand out the `hasNext` or `next` may change something.

**Comment by som-snytt** [comment]
I applied the insights https://github.com/scala/scala/pull/5771 which may supersede this PR.

**Comment by adriaanm** [comment]
Welcome, @djvulee -- thanks for getting the ball rolling on this improvement! Should we close this PR in favor of #5771? We are no longer accepting new PRs for 2.11.9, by the way, so this will have to be 2.12-only.

**Comment by SethTisue** [comment]
I see a "I will close my pull request" over at the other PR, so I'll go ahead and close. thanks @djvulee for taking this on

**Pull request closed without merging**
