### PR TITLE
SI-7805 REPL -i startup

### PR DESCRIPTION
**Pull request by som-snytt**
Tested with a ReplTest that loads an include script.

ReplTests can choose to be `Welcoming` and keep a
normalized welcome message in their check transcript.

Review by @retronym

### CODE REVIEW

**Comment by som-snytt** [comment]
For the record, I wasn't totally lazy.  I did run `test/partest --grep ReplTest` before I submitted.

**Comment by som-snytt** [comment]
Updated `repl-trim-stack-trace.scala` which is a `SessionTest` that normalized its output before that was normal.

**Comment by retronym** [comment]
LGTM. Thanks for figuring out how to test this!

The reason the fix is needed is that we're using the completedness of `globalFuture` as a lock on the interpreter during startup. But that isn't reentrant. I sort of threw that code together in frustration at yet-another-duplicate-of-tab-completion-crashing being reported in JIRA. Looks a bit hacky now.

Maybe as a followup you could think about a cleaner way to structure that code of avoiding the TAB completion crashes on startup.

**Comment by som-snytt** [comment]
@retronym It's funny you should mention that, because that is on my list of things to think about.

I was aware of your hack, because that was when paulp said "you're my hero."  That must be a lot of pressure for you, so I understand why you had to act fast on this fix. (kind of kidding)

Repl tests actually look better with the welcome message.  It seemed excessive to update 70 tests with it, however.

"Welcome to Scala," a very Swiss sentiment, in the hospitality industry sense.

**Comment by som-snytt** [comment]
I meant to add a comment somewhere, "one line contributed by retronym".

**Pull request merged**
