### PR TITLE
SI-5294 Use bounds of abstract prefix in asSeenFrom

### PR DESCRIPTION
**Pull request by retronym**
ASF was failing to recognize the correspondence between a
prefix if it has an abstract type symbol, even if it is bounded by
the currently considered class.

Distilling the test cases, this led to incorrect typechecking of the
RHS of `G` in:

```
trait T {
  type A
  trait HasH { type H[U] <: U }
  type F[N <: HasH] = N#H[T]
  type G[N <: HasH] = F[N]#A // RHS was incorrectly reduced to T.this.A
}
```

In the fuller examples (included as test cases), this meant that
type level functions written as members of `HList` could not be
implemented in terms of each other, e.g. defining `Apply[N]` as
`Drop[N]#Head` had the wrong semantics.

This commit checks checks if the prefix has the candidate class
as a base type, rather than checking if its type symbol has this
as a base class. The latter formulation discarded information about
the instantation of the abstract type.

Using the example above:

```
scala> val F = typeOf[T].member(TypeName("F")).info
F: $r.intp.global.Type = [N <: T.this.HasH]N#H[T]

scala> F.resultType.typeSymbol.baseClasses // old approach
res14: List[$r.intp.global.Symbol] = List(class Any)

scala> F.resultType.baseClasses // new approach
res13: List[$r.intp.global.Symbol] = List(trait T, class Object, class Any)
```

It is worth noting that dotty rejects some of these programs,
as it introduces the rule that:

> // A type T is a legal prefix in a type selection T#A if
> // T is stable or T contains no abstract types except possibly A.
> final def isLegalPrefixFor(selector: Name)(implicit ctx: Context)

However, typechecking the program above in this comment in dotty
yields:

```
<trait> trait T() extends Object {
  type A
  <trait> trait HasH() extends Object {
    type H <: [HK$0] =>  <: HK$0
  }
  type F = [HK$0] => HK$0#H{HK$0 = T}#Apply
  type G = [HK$0] => HK$0#H{HK$0 = T}#Apply#A
}
```

As the equivalent code [1] in dotc's `asSeenFrom` already looks for a base type
of the prefix, rather than looking for a superclass of the prefix's
type symbol.

[1] https://github.com/lampepfl/dotty/blob/d2c96d02fccef3a82b88ee1ff31253b6ef17f900/src/dotty/tools/dotc/core/TypeOps.scala#L62

Review by @adriaanm @odersky

### CODE REVIEW

**Comment by adriaanm** [comment]
Looks like this uncovered a separate issue?

**Comment by retronym** [comment]
We're trying to lookup up `GenericParTemplate` in the base type seq of [`from.type`](https://github.com/scala/scala/blob/v2.11.6/src/library/scala/collection/generic/ParSetFactory.scala#L32).

However the base type sequence slot for that class contains:

```
scala.collection.generic.GenericParTemplate[_$1,CC] with scala.collection.generic.GenericParTemplate[_$1,scala.collection.parallel.ParSet] with scala.collection.generic.GenericParTemplate[_$1,scala.collection.parallel.ParIterable] forSome { type _$1 }
```

Perhaps that is why `dotc` uses `baseTypeRef`.

**Comment by retronym** [comment]
> Looks like this uncovered a separate issue?

@adriaanm Indeed, looks like that is the case.

Here's a distilled version of the failure:

``` scala
import scala.language.higherKinds;
object Test {
  trait T[+A, +CC] {
    def t: CC
  };
  def test[CC[X] <: T[X,String] with T[X,Int]](from: CC[_]): Unit = {
    val temp1: Int with String = from.t;
    (temp1: Int)
    (temp1: String)
  }
}
```

Looks like a bug in `BaseTypeSeq#typeSymbol`, which is employed by `baseTypeIndex` to peer through refinement types. It also needs to peer through existentials. I've pushed a preceding commit to fix that. Will revisit it tomorrow to fill in the commit comment.

**Comment by retronym** [comment]
The first commit fails to bootstrap with:

```
[quick.compiler] /home/jenkins/workspace/scala-2.12.x-validate-publish-core/src/compiler/scala/tools/nsc/ast/parser/MarkupParsers.scala:271: error: the type intersection scala.collection.mutable.AbstractSeq[_ >: Char with MarkupParsers.this.global.Tree] with scala.collection.mutable.IndexedSeq[_ >: Char with MarkupParsers.this.global.Tree] with scala.collection.IndexedSeqOptimized[Any,Cloneable with Mutable with Serializable with scala.collection.generic.Clearable with Equals] with scala.collection.mutable.Builder[Char with MarkupParsers.this.global.Tree,java.io.Serializable] with Serializable is malformed
[quick.compiler]  --- because ---
[quick.compiler] no common type instance of base types scala.collection.IndexedSeqLike[Any,Cloneable with Mutable with Serializable with scala.collection.generic.Clearable with Equals], and scala.collection.IndexedSeqLike[_253,scala.collection.mutable.IndexedSeq[_253]] with scala.collection.IndexedSeqLike[_253,IndexedSeq[_253]] forSome { type _253 >: Char with MarkupParsers.this.global.Tree } exists.
[quick.compiler]             t.attachments.get[handle.TextAttache] match {
[quick.compiler]                                                   ^
[quick.compiler] one error found
```

**Comment by retronym** [comment]
Trying again with a hopeful compensating change to `BaseTypeSeq#apply`.

**Comment by retronym** [comment]
Relegating the to too-hard-basket until we get 2.12.0-M2 out.

**Pull request closed without merging**
