### PR TITLE
SI-6188

### PR DESCRIPTION
**Pull request by magarciaEPFL**
review by @VladUreche or @dragos

### CODE REVIEW

**Comment by VladUreche** [comment]
LGTM! Thanks Miguel for fixing it and Heather for pointing it out.

**Comment by magarciaEPFL** [comment]
This patch fixes a critical bug, please merge into 2.10.x

**Comment by magarciaEPFL** [comment]
PLS REBUILD ALL

**Comment by VladUreche** [comment]
LGTM for the added commit, so LGTM overall.

**Comment by heathermiller** [comment]
Thanks a lot Miguel! I owe you a beer, or a yogurt, whatever you prefer! ;)

**Comment by magarciaEPFL** [comment]
:)

**Pull request merged**
