### PR TITLE
SI-8650 F-interpolator inlines literals

### PR DESCRIPTION
**Pull request by som-snytt**
FormatInterpolator emits a call to `String.format(s, args...)` and inlines
constant expressions in the string.

Indexed args are verified for correctness.

```
scala> final val pi = 3.14
pi: Double(3.14) = 3.14

scala> f"$pi%.1f %<s %1$$e"                    // just a string
res0: String = 3.1 3.14 3.140000e+00

scala> import System.{ currentTimeMillis => now }
import System.{currentTimeMillis=>now}

scala> f"$now%d"
res1: String = 1423615388758

scala> f"$now%tdth day of %<th"
res2: String = 10th day of Feb

scala> f"Today is the %1$$tdth day of %<th, epoch time $now%tQ"
res3: String = Today is the 10th day of Feb, epoch time 1423616802039

scala> f"${null}%#s"
<console>:8: error: Requires an instance of java.util.Formattable
              f"${null}%#s"
                         ^

scala> f"${42000}%,,d"
<console>:8: error: Duplicate flag ','
              f"${42000}%,,d"
                          ^

scala> f"${3.14}%f %<d"
<console>:8: error: Specifier '%<d' not compatible with indexed arg
              f"${3.14}%f %<d"
              ^
```

### CODE REVIEW

**Comment by adriaanm** [comment]
Since the 2.11.6 deadline is extremely nigh, I've tentatively postponed this PR (along with other recent ones) to 2.11.7. I'll make a pass through reviewed 2.11.7 PRs on Friday and move them back to 2.11.6 where feasible.

In the mean time, feel free to let me know if you'd like some help getting this reviewed by then.

**Comment by soc** [comment]
@som-snytt Would it make sense to macroify the s-interpolator, too? (Btw, any plans for regextractor?)

**Comment by retronym** [comment]
[Hmmmm.](https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/435/console)

```
quick.comp:
    [mkdir] Created dir: /home/jenkins/workspace/scala-2.11.x-validate-test@2/build/quick/classes/compiler
[quick.compiler] Compiling 316 files to /home/jenkins/workspace/scala-2.11.x-validate-test@2/build/quick/classes/compiler
[quick.compiler] /home/jenkins/workspace/scala-2.11.x-validate-test@2/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:868: warning: match may not be exhaustive.
[quick.compiler] It would fail on the following input: List(_)
[quick.compiler]         seenTypes(i) match {
[quick.compiler]                  ^
[quick.compiler] error: symbol value x2 does not exist in scala.tools.nsc.typechecker.Implicits$ImplicitSearch.isImpossibleSubType
[quick.compiler] error: scala.reflect.internal.FatalError: symbol value x2 does not exist in scala.tools.nsc.typechecker.Implicits$ImplicitSearch.isImpossibleSubType
[quick.compiler]    at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
[quick.compiler]    at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:17)
[quick.compiler]    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.genLoadIdent$1(GenICode.scala:885)
```

/rebuild

**Comment by retronym** [comment]
I've added a better diagnostic for that compiler crash in #4397. I can't see how it is related to this change.

/rebuild

**Comment by som-snytt** [comment]
@retronym  I did a quick rebase earlier today, something might have got munged...

**Comment by som-snytt** [comment]
FYI, I reverted this to the unrebased, and I'm trying out a fresh rebase on the other PR.

It was nice getting the green checks here for free. Jenkins has elephantine memory. Pachydermal recall.

**Pull request closed without merging**
