### PR TITLE
Merge 2.11.x to 2.12.x

### PR DESCRIPTION
**Pull request by retronym**
```
% export MB=$(git merge-base origin/2.11.x head)

% git --no-pager log --oneline --decorate --graph $MB..origin/2.11.x
*   aea6519 (origin/2.11.x) Merge pull request #3867 from lrytz/t8708
|\
| * 14fa7be (origin/pr/3867) SI-8708 Fix pickling of LOCAL_CHILD child of sealed classes
* |   4d3ede9 Merge pull request #3866 from Blaisorblade/issue/8677-backport
|\ \
| * | acab0fa (origin/pr/3866) [backport] SI-8677 Duration: Zero - Inf should be MinusInf
* | |   d1fa9ac (2.11.x) Merge pull request #3868 from adriaanm/report-filter
|\ \ \
| * | | 532ef33 (origin/pr/3868) Restore reporter forwarders in CompilationUnit
|/ / /
* | |   75ac225 Merge pull request #3820 from adriaanm/report-filter
|\ \ \
| * | | b384d50 (origin/pr/3820) Use countElementsAsString for summarized warnings.
| * | | 3066bd4 Encapsulate deprecation warning message synthesis.
| * | | 9fc68e1 Remove deprecationWarning, currentReporting from Reporting
| * | | b724201 Rip out reporting indirection from CompilationUnit
| * | | 59db57f Route type checker reporting through context
| * | | e087353 Track symbol that caused a deprecation warning.
| * | | 62c8f90 Uniformly route reporting through reporter.
| * | | 98216be Move reporting logic into Reporting trait
| * | | f2b76e8 Pure refactor: reorder definitions
| * | | ffb0e25 Unclutter Reporter. Move truncation to ReplReporter.
|/ / /
* | |   b38fc5e Merge pull request #3842 from Ichoran/issue/8335
|\ \ \
| |_|/
|/| |
| * | ff43de9 (origin/pr/3842) SI-8335  List.++ avoidably burns memory
|  /
* |   3f79f8e Merge pull request #3788 from som-snytt/issue/8494
|\ \
| * | fadb21d (origin/pr/3788) SI-8494 Javap filter includes specialized
| * | 7332240 SI-8494 Restore filtering javap output
|  /
* |   8ef3897 Merge pull request #3840 from Ichoran/issue/8638
|\ \
| |/
|/|
| * 36ef5c3 (origin/pr/3840) SI-8638  Empty UnrolledBuffer hangs on prepend.
*   4dcb51c Merge pull request #3841 from Ichoran/issue/5200
|\
| * 23ae5c4 (origin/pr/3841) SI-5200  Incorrect advice for implementing mutable.Set in scaladoc
*   300d646 Merge pull request #3839 from Ichoran/issue/7115
|\
| * 9ceab68 (origin/pr/3839) SI-7115  JMapWrapper.get can incorrectly return Some(null)
*   6a1e592 Merge pull request #3834 from Ichoran/issue/7577
|\
| * 1f53a0d (origin/pr/3834) SI-7577  Incorrect documentation: current default isn't Vector
*   dd36e57 Merge pull request #3736 from VladimirNik/print-types-issue-2.11.x
|\
| * e2fb217 (origin/pr/3736) TypeTree printing modified (SI-8447)
*   c9ab6b6 Merge pull request #3772 from densh/si/8609
|\
| * 56ed4fc (origin/pr/3772) SI-8609 Fix flattening of definitions and imports in quasiquotes
*   17d56e4 Merge pull request #3863 from adriaanm/rebase-3852
|\
| * b3c4e3a (origin/pr/3863) Document SuperAccessors
|/
*   2c08914 Merge pull request #3828 from retronym/ticket/8675
|\
| * 5ba1290 (origin/pr/3828) SI-8675 Add another test case for swallowed type errors
| * 7a16f76 SI-8675 Avoid unreported error after second try using implicit view
*   e67146c Merge pull request #3836 from gourlaysama/wip/t8292
|\
| * 5d63ef3 (origin/pr/3836) SI-8292 report error when scaladoc fails to find doclet.
* 1feda98 Merge pull request #3849 from gourlaysama/wip/t8690
* 4e29e9a (origin/pr/3849) SI-8690 BufferedSource.mkString mistakenly skipped the first char.
merge/2.11.x-to-2.12.x-20140714 ~/code/scala3 git merge origin/2.11.x
Merge made by the 'recursive' strategy.
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @lrytz

**Comment by retronym** [comment]
Technically I should have merged  acab0fa with the `ours` strategy as it was a backport from 2.12.x, but, given that the code was identical in 2.11.x, merging it with `recursive` had the same result.

This merge also edits the `bin-compat*` whitelists. BC checking is disabled in `build.xml` on the 2.12.x branch, so arguably those files should be empty. But leaving them as is results in the least merging friction, so I'll stick to that for now.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@75ac225
PLS REBUILD/pr-scala@7332240

I changed `pr-publish-scala-core` to be forgiving if the build hasn't produced a `versions.properties`. The file isn't produced when we short circuit building after detecting that the commit is part of a merge and doesn't need to be re-tested.

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@75ac225

kitty ignored this one..

for review, LGTM!

**Pull request merged**
