### PR TITLE
[SI-8990] Test and potential fix (please review)

### PR DESCRIPTION
**Pull request by ms-tg**
Hi Scala folks! I'm looking for advice on how to proceed here. 

I've added a junit file StreamTest with two tests:
1. Passes unless you uncomment line 25
2. Fails due to SI-8990

Uncomment StreamTest.scala line 25 to demonstrate
that simply having a StreamWithFilter present is
enough to prevent the garbage collection of a
Stream as it is processed.

To fix the pending test of SI-8990, it will be
necessary to find a solution to that, since the issue
is with using withFilter.

As mentioned on scala-internals, the heritage of 
Stream#StreamWithFilter to TraversableLike#WithFilter
means that there is a fairly baked-in assumption of
closing over a reference to the original instance, and
this is the cause of the inability to GC the stream as
it is processed.

Any suggestions?

### CODE REVIEW

**Comment by ms-tg** [comment]
After discussion with @paulp at nescala, and looking through the history of `Stream#filter` and `Stream#withFilter`, I am considering that the specialized implementation of `TraversableLike#WithFilter` should perhaps be replaced with a simpler implementation of `FilterMonadic` which relies on the alread-correct implementation of `Stream#filter` rather than re-implementing.

I'll update this PR as I know more, thanks for all who are interested and assisting with this.

**Comment by Ichoran** [comment]
@ms-tg - If you want the fix to be compatible with 2.11.x, you need to tread lightly (e.g. not change the class hierarchy or visible methods).  Is there a problem other than the reference to `self` in the `foreach` implementation?  Adding in a `private[this] var original = self` which you then use and update in the `foreach` would fix it.

**Comment by ms-tg** [comment]
@Ichoran: I will try that, but doubt it will work. Because the `Stream#StreamWithFilter` will exist on the stack frame for the duration of the `#foreach` (or `#map`, etc), and it has the self reference to outer class instance, won't that doom any such efforts to allow collection to fail?

**Comment by Ichoran** [comment]
There isn't any reason why the self reference needs to be maintained if you never refer to it outside of the initializer.  I thought it was enough to make sure to only refer to it in the initializer, but maybe that won't do it.  (Upon checking bytecode, I think you might be right.)

**Comment by ms-tg** [comment]
Hi @Ichoran and others, I've gone ahead and opened alternate PR https://github.com/scala/scala/pull/4281 to demonstrate my understanding of what you propose (and, I think, to demonstrate that it doesn't work?)

**Comment by Ichoran** [comment]
Unfortunately, it looks like because of how the bytecode is generated, it is necessary to retarget this for 2.12, at which point Paul's approach of deferring to Stream.filter is the way to go.

**Comment by ms-tg** [comment]
@Ichoran Sorry, I must not be understanding what you mean. I can understand that changing the return type of `Stream#withFilter` to be `FilterMonadic` will need to be targeted to 2.12. But I don't understand why this PR, or something substantially like it, wouldn't be the solution? Can you explain?

**Comment by Ichoran** [comment]
I was agreeing that this is the way to go.  Maybe I misunderstood whose idea it was that you should defer to Stream#filter.  It just needs to be retargeted to 2.12.

**Comment by ms-tg** [comment]
@Ichoran oh, awesome, sorry I misunderstood. I am very excited to get my first PR into Scala, as I'm sure you can understand ;). Too bad it has to be targeted to 2.12, but yeah I can't see any way to solve this without changing the type that is returned, so it seem unavoidable. Thanks! 

Please let me know if there's anything else I need to do -- I've already signed Typesafe CLA in the past, for example.

**Comment by ms-tg** [comment]
@Ichoran: should I make a new PR that is based on 2.12 branch, and is requested against it?

**Comment by Ichoran** [comment]
Yes, that's the thing to do.  Thanks!

**Comment by ms-tg** [comment]
As instructed, I am closing this PR in favor of https://github.com/scala/scala/pull/4284, which is targeted to 2.12.x.

**Pull request closed without merging**
