### PR TITLE
SI-7398 Add support for java8 default methods

### PR DESCRIPTION
**Pull request by paulp**
Now with test.

### CODE REVIEW

**Comment by paulp** [comment]
Here it is compiling the files under java/ in jdk8. Except Object.java, which causes a cyclic reference failure.

```
% pscalac $(find ./java -name '*.java' | grep -v 'Object.java') -Ydebug
[running phase parser on 1710 compilation units]
[running phase namer on 1710 compilation units]
[running phase packageobjects on 1710 compilation units]
[running phase typer on 1710 compilation units]
[running phase patmat on 1710 compilation units]
[running phase superaccessors on 1710 compilation units]
[running phase extmethods on 1710 compilation units]
[running phase pickler on 1710 compilation units]
[running phase refchecks on 1710 compilation units]
[running phase selectiveanf on 1710 compilation units]
[running phase selectivecps on 1710 compilation units]
[running phase uncurry on 1710 compilation units]
[running phase tailcalls on 1710 compilation units]
[running phase specialize on 1710 compilation units]
[running phase explicitouter on 1710 compilation units]
[running phase erasure on 1710 compilation units]
[running phase posterasure on 1710 compilation units]
[running phase lazyvals on 1710 compilation units]
[running phase lambdalift on 1710 compilation units]
[running phase constructors on 1710 compilation units]
[running phase flatten on 1710 compilation units]
[running phase mixin on 1710 compilation units]
[running phase cleanup on 1710 compilation units]
[running phase icode on 1710 compilation units]
[running phase inliner on 1710 compilation units]
[running phase inlineExceptionHandlers on 1710 compilation units]
[running phase closelim on 1710 compilation units]
[running phase dce on 1710 compilation units]
[running phase jvm on icode]
```

**Comment by paulp** [comment]
This time I'll let starr wait until it looks like it works.

**Comment by paulp** [comment]
It's quite the dizzying array of failure possibilities these days.

**Comment by paulp** [comment]
Review by @gkossakowski

**Comment by soc** [comment]
I'm not @gkossakowski, but it LGTM.

**Comment by gkossakowski** [comment]
Thanks @soc. I'll look into it today or tomorrow.

I have some doubts whether we should introduce new flags in 2.10.x branch.

On Monday, April 29, 2013, soc wrote:

> I'm not @gkossakowski https://github.com/gkossakowski, but it LGTM.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scala/scala/pull/2456#issuecomment-17167969
> .

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by gkossakowski** [comment]
Sorry, I got distracted by real life. I'm done with speaking at conferences for one week so I'll have time to review it tomorrow. This time for real :-)

**Comment by gkossakowski** [comment]
LGTM.

I had some doubts whether we should add new flags in 2.10.x but I think this is the cleanest solution that allows us to not choke on Java 8 bytecode.

Thanks for good work!

**Pull request merged**
