### PR TITLE
SI-8888 Avoid ClassFormatError under -Ydelambdafy:method

### PR DESCRIPTION
**Pull request by retronym**
The pattern matcher phase (conceivably, among others) can generate
code that binds local `Ident`s symbolically, rather than according
to the lexical scope. This means that a lambda can capture more than
one local of the same name.

In the enclosed test case, this ends up creating the following
tree after delambdafy

```
[[syntax trees at end of                delambdafy]] // delambday-patmat-path-dep.scala
matchEnd4({
  case <synthetic> val x1: Object = (x2: Object);
  case5(){
    if (x1.$isInstanceOf[C]())
      {
        <synthetic> val x2#19598: C = (x1.$asInstanceOf[C](): C);
        matchEnd4({
          {
            (new resume$1(x2#19598, x2#19639): runtime.AbstractFunction0)
          };
          scala.runtime.BoxedUnit.UNIT
        })
      }
    else
      case6()
  };
  ...
})
...
<synthetic> class resume$1 extends AbstractFunction0 {
  <synthetic> var x2: C = null;
  <synthetic> var x2: C = null;
  ...
}
```

After this commit, the var members of `resume$1` are given fresh
names, rather than directly using the name of the captured var:

```
<synthetic> var x2$3: C = null;
<synthetic> var x2$4: C = null;
```

Review by @lrytz or @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
This bug was proudly brought to you by the [BCode-Delambdafy community build](https://jenkins-dbuild.typesafe.com:8499/view/Shared/job/Community-2.11.x-BCode-Delambdafy/150/).

**Comment by lrytz** [comment]
LGTM. Side-question: was it not one of the goals of the pattern matcher to be able to re-typecheck trees? ([SI-5464](https://issues.scala-lang.org/browse/SI-5464))

**Comment by retronym** [comment]
It might also be prudent to adjust the pattern matcher to use fresh names. But I'm sure there are other offenders.

For macros, it is more important that the machinations of the namer/typer produce resettable trees, later phases aren't such a problem.

**Comment by adriaanm** [comment]
@lrytz yes, being able to re-typecheck patmat trees is a goal (/cc @DarkDimius)

@retronym, I'm not sure I interpret the fragment and the lack of hygiene correctly. Where does the x2 in `case <synthetic> val x1: Object = (x2: Object);` come from?

**Comment by lrytz** [comment]
@adriaanm There was one line missing:

```
lucmac:~ luc$ scala -Xprint:pat

scala> class C {
     |   final def resume: Unit = (this: Any) match {
     |     case x : C => (x: Any) match {
     |       case y : C =>
     |         () => (x, y) // used to trigger a ClassFormatError under -Ydelambdafy:method
     |     }
     |   }
     | }

[[syntax trees at end of                    patmat]] // <console>
[...]
          final def resume: Unit = {
            case <synthetic> val x1: Any = (this: Any);
            case5(){
              if (x1.isInstanceOf[C])
                {
                  <synthetic> val x2: C = (x1.asInstanceOf[C]: C);
                  matchEnd4({
                    case <synthetic> val x1: Any = (x2: Any);
                    case5(){
                      if (x1.isInstanceOf[C])
                        {
                          <synthetic> val x2: C = (x1.asInstanceOf[C]: C);
                          matchEnd4({
                            (() => scala.Tuple2.apply[C, C](x2, x2));
                            ()
                          })
                        }
                      else
                        case6()
                    };
                    case6(){
                      matchEnd4(throw new MatchError(x1))
                    };
                    matchEnd4(x: Unit){
                      x
                    }
                  })
                }
              else
                case6()
            };
            case6(){
              matchEnd4(throw new MatchError(x1))
            };
            matchEnd4(x: Unit){
              x
            }
          }
```

**Comment by adriaanm** [comment]
Thanks! Yeah, should fix that in patmat.

**Comment by lrytz** [comment]
I'll file a ticket

**Comment by adriaanm** [comment]
Thanks, please assign to me :)

**Comment by DarkDimius** [comment]
@lrytz straightforward porting of pattern matcher to Dotty showed that at least in Dotty  retypechecking of trees after pattern-matcher was originally not possible for various reasons, some of them:
- if `unapply` method call has type parameters they are always set to Nothing after typer(fixed in dotty) and pattern matcher tries to reconstruct the tree based on first argument of `unapply` but sometimes fails by getting types that violates type bounds.
- after rewriting the type tests pattern matcher can create `Ident`s that has type that doesn't match type of underlying symbol
- whole rewriting scheme needs a lot of adaptation to path dependant types, and singleton types, as any widening of type of either selector or the variable in pattern would loose typecheckability, both for the subtree itself and could also make the whole tree not conform to the expected type of the outer tree. This one was very tricky to implement in dotty and required introducing casts(eg casting an interger tree known to evaluate to constant to a constant type)

All this is fixed in dotty, where all phases are validated by Ycheck to not break owner chains and maintain typecheckability. In dotty pattern matcher is a mini-phase that constructs a correct tree with correct types and owners in a single run(ie no need for a second run to reconstruct the onwers).

But I'm not sure how much of those problems are there in scalac, AFAIK @VladUreche had to backtrack many of those things in his miniboxing plugin as he needs to retypecheck tree several times during LDL transformation. But I'm not sure how far he was able to get.

**Comment by adriaanm** [comment]
That's some great info, @DarkDimius! Could you and @VladUreche please backport the relevant fixes to scala/scala?

**Comment by DarkDimius** [comment]
@adriaanm I'll have a look if this could be ported straightforwardly, but a bit later, as now I want to rush and publish a paper about mini-phases in dotty. I'm not sure if code could be just simply ported as I rely on the fact that tree&types are always correct while some of comments in patmat indicated that this does not hold in scalac.

**Comment by adriaanm** [comment]
There's no rush. Ping me if there's anything I can do to help. Good luck with the paper!

**Comment by VladUreche** [comment]
@adriaanm, the AST type mismatches I found occured due to pattern matcher optimizations that replaced parts of the tree. The solution I took was to re-type-check the AST and when types don't match, insert `<tree>.asInstanceOf[...]` in `adapt`, trusting the pattern matcher to have done a correct job on the optimization, modulo the types assigned to AST nodes.

I don't think it's worth spending the time to fix the pattern matcher in scala for this, as only LDL-based transformations require re-typing the tree and I have a partial solution that's working. WDYT?

**Comment by VladUreche** [comment]
Btw, I'm really glad dotty builds are tested with `-Ycheck` enabled, this will guarantee LDL passes won't have any trouble transforming the program :+1:

**Comment by adriaanm** [comment]
Ok, thanks for the explanation! Probably no point then, no

**Comment by retronym** [comment]
Adding the casts might turn out to be pretty straight forward. I can't remember: is there a ticket to track the problem with a minimal example?

**Comment by VladUreche** [comment]
> Adding the casts might turn out to be pretty straight forward. 

It is: https://github.com/miniboxing/miniboxing-plugin/blob/wip/components/plugin/src/miniboxing/plugin/transform/prepare/MiniboxPrepareTreeTransformer.scala

> I can't remember: is there a ticket to track the problem with a minimal example?

There's a ticket for one of the symptoms on issues.scala-lang:
https://issues.scala-lang.org/browse/SI-8820 

For the other manifestations, there's a bug for the miniboxing plugin:
https://github.com/miniboxing/miniboxing-plugin/issues/123

**Pull request merged**
