### PR TITLE
Respect -Dpartest.scalac_opts when running the test suite through ANT

### PR DESCRIPTION
**Pull request by lrytz**
Used to enable `-Xcheckinit` (now also `-Ybackend:GenBCode`) when
compiling tests in the respective jenkins builds. This is currently
broken, as you can see in [recent build logs](https://scala-webapps.epfl.ch/jenkins/view/nightlies/job/scala-nightly-checkinit/2058/consoleFull), `-Xcheckinit` is
missing:

```
[partest] Scalac options are:  -optimise
```

Adds `.flags` files for macro tests (correct range positions not
enforced) and for tests failing due to SI-8560 or SI-8562.

Resubmission of #3709 (against 2.11 branch).

### CODE REVIEW

**Comment by retronym** [comment]
LGTM. I will merge master to 2.11.x, but new PRs can avoid the indirection and target that directly.

**Comment by lrytz** [comment]
Thanks, I didn't know. But `master` is going to disappear eventually, right?

This PR also shows that kitty seems to ignore PRs to 2.11.x

**Comment by retronym** [comment]
Yep, I just sent a status mail to scala-internals about the branches.

I thought that [this](https://github.com/scala/scala/issues/milestones/34/edit):

image

...was the right incantation to make the kitteh aware of this branch.

@adriaanm any ideas?

**Comment by retronym** [comment]
Oh wait, the build has started.

**Comment by lrytz** [comment]
oh, it seems to have started, sorry for the noise

**Comment by retronym** [comment]
Did you manually assign the milestone, or was that done automatically?

**Comment by lrytz** [comment]
i didn't do anything to the milestone manually

**Comment by adriaanm** [comment]
the buildbot assigns a milestone based on the milestone description -- note that it doesn't validate PRs that target a branch without a corresponding milestone

**Pull request merged**
