### PR TITLE
SI-6289 Partest in technicolor and showing javac errors

### PR DESCRIPTION
**Pull request by som-snytt**
Paulptest includes color and simplified test scarfing.

Scalap tests are moved to the conventional name and location.

In a grouped or staged or round-robin compilation, any file foo_1.scala can contribute a foo_1.flags to the group flags. That is for simplicity.  (Mnemonic: foo declares the flags it needs, and flags are gathered on a group basis.)

Just a few fixes from the Sept 2012 version: don't apply options more than once, since multi-valued settings like -Xplugin are cumulative; honor SCALAC_OPTS because ant relies on it for -Xpluginsdir.  Note that no names have been changed to make them appear innocent.

Paul's test that compilation round errors are reported is forthcoming.

Testicolor is due to one of Paul's branches on a timeline
that apparently did not include the destruction of planet
Earth and its colonies by the Xindi.

Thanks also to Szabolcs Berecz for his merge effort.  Merging
is thankless work, but not as thankless as merging in a
timeline that actually does terminate in the destruction of
your home world and Enterprise.

Archer had a supremely difficult choice: rescue humanity or
live out his retirement with T'Pol waiting on him hand and
foot? I'm sure I don't know how I'd choose.

Review by @paulp or maybe @khernyo would also prefer that paulp kept his eyes trained on the future instead of the distant past.  It's also possible that paulp is a transdimensional being for whom time has no meaning, and who is working, as we speak, on bugs that were fixed three years ago and on features of Scala 3 that won't appear until the next decade.  Or more mysteriously, he is working on bugs that were closed as WontFix or CantFix, but which will form the basis of a future and betterized Scala beyond our ability to comprehend.

### CODE REVIEW

**Comment by som-snytt** [comment]
Javac message differs on 6/7.

**Comment by khernyo** [comment]
I compared master and this branch and this is what I found:
- "ant test": presentation tests are run twice on this branch. This means "ant test" is slower (by two minutes here) but doesn't cause other problems. I think this could be fixed after merging into master to avoid more merge pains.
- some tests are executed on this branch which are missed by partest on master. E.g. presentation/forgotten-ask.scala
- "partest --scalap": broken on master, works fine on this branch
- "ant test.ant" and "partest --ant" are broken on both branches

I have not checked the code.

**Comment by som-snytt** [comment]
On finding more tests, I think Paul scrapped the old per-kind filters.  I remember that code was confusing. In my old refactor, I made the association look like modulo.  You can see why kinds of tests might have special extensions.  But the case of scalap shows that it helps if everything is normalized and consistent.  Goal: no one wastes an hour wondering why a test doesn't run, or why partest behaves differently from the build; and that no one ever says, We would have caught that bug if only that test had been running all this time.

```
val std = List(
  pos % stdFilter,
  neg % stdFilter,
  run % stdFilter,
  jvm % stdFilter,
  res % { x => x.isFile && (x hasExtension "res") },
  fsc % stdFilter,
  buildmanager % dirFilter,
  shootout % stdFilter,
  script % stdFilter,
  scalacheck % stdFilter,
  scalap % dirFilter,
  specialized % stdFilter,
  presentation % dirFilter,
  ant % antFilter
)
```

**Comment by paulp** [comment]
In the interests of heading off duplicated effort, I alert that I'm reintegrating this now that the build.xml changes have vanquished any hope of a smooth landing.

**Comment by paulp** [comment]
I pushed the work in progress since I'm going to sleep and who knows when I'll get back to it. It is probably only one classpath tweak away from all tests passing. But only for the final commit; given the extent of the build.xml changes I accepted master's version when they met, so once it's working build.xml will have to work its way backward a couple commits to unbreak the earlier ones.

https://github.com/paulp/scala/tree/wip/partest-2328-reintegrate

**Comment by retronym** [comment]
BTW, we'll need to update the build-kitty to be able to grep out failures, right now it has some hard-coded assumptions about the output.

https://github.com/typesafehub/ghpullrequest-validator/blob/master/src/main/scala/backend/PullRequestCommenter.scala#L55

It will still serve it's main duties, but it won't replicate the particular test failures in the PR comments.

**Comment by som-snytt** [comment]
I'll try to wip [sic] something up. Ha. 

I just wrote a test that has a plugin in the first _1 group to autogenerate scalac-plugin.xml, then a plugin built in _2 group with flags -d myplugin.jar, that's used in subsequent groups.  Ha, again.  But I wound up tweaking the silent-era partest instead of Testicolor to do it.

**Comment by som-snytt** [comment]
Closing for re-re-rebasing.

Superseded by https://github.com/scala/scala/pull/2350.

**Pull request closed without merging**
