### PR TITLE
Fix for SI-6245 with workaround for SI-2296.

### PR DESCRIPTION
**Pull request by namin**
protected/super accessor issue: Don't subvert the creation of the
standard protected accessor with the java interop accessor. For
SI-2296, the compiler emits an error instead of causing an illegal
access error at runtime.

Once 2.10 is released, we can investigate a full fix for Si-2296, which is tricky.

Review by @paulp.

### CODE REVIEW

**Comment by xeno-by** [comment]
Hi! Would be great if you could rebase against 2.10.x to get rid of the extraneous commit.

**Comment by namin** [comment]
done.

**Comment by jsuereth** [comment]
+1 from me.  Nice fix.

**Comment by paulp** [comment]
LGTM, thanks.

**Pull request merged**
