### PR TITLE
Optimize file metadata access

### PR DESCRIPTION
**Pull request by retronym**
Background: When profiling an application that was using the interpreter to compile
a script, a lot of time was reported in `exists`/`isDirectory`/`isFile`. I happened to be profiling on Windows. 

Turns out some of these calls are redundant, this PR eliminate two such places.

Here's an example of how it helps:

Taking a Hello, Akka! application, and compiling it with the compiler
and library on a directory classpath (ie, using build/quick):

```
class HelloActor extends Actor {
  def receive = {
    case "hello" => println("hello back at you")
    case _       => println("huh?")
  }
}

object Main extends App {
  val system = ActorSystem("HelloSystem")
  // default Actor constructor
  val helloActor = system.actorOf(Props[HelloActor], name = "helloactor")
  helloActor ! "hello"
  helloActor ! "buenos dias"
}

% qbin/scalac -Ystatistics -classpath ~/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.1.1.jar:/Users/jason/.ivy2/cache/com.typesafe/config/bundles/config-1.0.0.jar sandbox/test.scala 2>&1 | grep File
```

```
Before
----------------------------------
File.isFile calls           : 7620
File.isDirectory calls      : 8348
File.exists calls           : 5770

After
----------------------------------
File.isFile calls           : 7620
File.isDirectory calls      : 2319
File.exists calls           : 345
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @paulp. Is this as safe as it seems to me?

**Comment by retronym** [comment]
Oh, and I need to test this more to see if it is worth it, ie should we just rely on caching by the file system. On my machine (with SSD), I see a small but discernable bump in:

```
2.10.x ~/code/scala2 time /Users/jason/usr/scala-v2.11.0-M2-45-g2efc6d5/pack/bin/scala -e "List(1).reverse"

real    0m0.609s
user    0m0.432s
sys 0m0.049s
2.10.x ~/code/scala2 time /Users/jason/usr/scala-v2.11.0-M2-45-g2efc6d5/pack/bin/scala -e "List(1).reverse"

real    0m0.618s
user    0m0.439s
sys 0m0.050s
2.10.x ~/code/scala2 time /Users/jason/usr/scala-v2.11.0-M2-45-g2efc6d5/pack/bin/scala -e "List(1).reverse"

real    0m0.612s
user    0m0.447s
sys 0m0.052s
2.10.x ~/code/scala2 time /Users/jason/usr/scala-v2.11.0-M2-45-g2efc6d5/pack/bin/scala -e "List(1).reverse"

real    0m0.613s
user    0m0.440s
sys 0m0.048s
2.10.x ~/code/scala2 time qbin/scala -e "List(1).reverse"

real    0m0.589s
user    0m0.410s
sys 0m0.054s
2.10.x ~/code/scala2 time qbin/scala -e "List(1).reverse"

real    0m0.591s
user    0m0.409s
sys 0m0.054s
2.10.x ~/code/scala2 time qbin/scala -e "List(1).reverse"

real    0m0.595s
user    0m0.413s
sys 0m0.054s
```

**Comment by paulp** [comment]
Is it safe? All these filesystem operations are inherently racy, so it's only a matter of degree. There's nothing one can do to prevent an arbitrary path from being deleted or turning from a file into a directory, not without mandatory locking. If I were to do it again I'd build that reality in much more pervasively: everything is a Path, you can treat it like a File or a Directory and it will go along with whatever you say without checking, and catch the exceptions.

**Comment by paulp** [comment]
I'm not sure what is the "this" in "I need to test this more to see if it is worth it," can you clarify? Is this PR in a state you want to see merged?

**Comment by retronym** [comment]
I guess my question was: do we hold on to these iterators for long periods, or do we typically walk them quickly?

**Comment by paulp** [comment]
LGTM

**Comment by paulp** [comment]
> I guess my question was: do we hold on to these iterators for long periods, or do we typically walk them quickly?

Typically they're walked immediately, but "strange women lying in ponds distributing swords is no basis for a system of government", by which I mean "typically" is no basis for deciding on guarantees.

**Comment by retronym** [comment]
I'm happy with it functionally, but I was disappointed with the speedup. Arguably the modicum of extra complexity isn't worth it. But I hold out hope that it will prove worthwhile on a slower file system, so as long as the code is okay with you, let's go ahead.

**Comment by som-snytt** [comment]
Is there a consensus on using `io.File` vs SFile vs JFile? vs File?

As a tangential data point, I was curious about what ClassPath does to partest run times, and found that building scala-library.jar uncompressed (so no entry decompress) saves 30 sec; not huge but gratuitous and all CPU (which matters more on a test server).

As another irrelevant point, I have a mental block on AbstractFile vs Path, I forget what my val f is and what I can do with it. I think I just want a Path (as an enhanced java.io.File) and have a Java 7 filesystem provider that handles virtual files (in memory) -- maybe that's true of other kinds of caching, but I haven't thought about it.

The supplementary point of my mental block is, right now I often look at the source to remember API, so I wouldn't want to have to look at source to see if my f.isDir is doing what I expected.

I'll also try to give this PR a shot on my slow file system, and make up for my lame comments.

**Comment by paulp** [comment]
I started that at some point: https://github.com/paulp/scala/tree/java7-io-wrappers

There's more, somewhere.

All of the IO code in trunk should be thrown out, we should devise an extremely minimal path abstraction, and add behavior with extension methods.

**Comment by som-snytt** [comment]
I thought you might have a branch for that.

**Comment by som-snytt** [comment]
> I was disappointed with the speedup.
> Could it really be worth 10 sec in partest --pos?  Don't quote me yet.

I'll compare it to fastest, which has a virtual directory for output, and I think has a 10 sec advantage.  All the jar dir entries are virtual, and there's nothing else I think. But I thought fastest's edge came from smarter read/writes.

**Pull request merged**
