### PR TITLE
SI-7763 Avoid dropping casts in erasure

### PR DESCRIPTION
**Pull request by retronym**
466b7d29f avoided quadratic complexity in Erasure's treatment
of chained `asInstanceOf` calls. It did so by using the typechecked
qualifier, rather than discarding it.

However, that also dropped the cast altogether! In many cases this
was masked by later inclusion of a cast to the expected type
by `adaptToType`:

```
  at scala.tools.nsc.transform.Erasure$Eraser.cast(Erasure.scala:636)
  at scala.tools.nsc.transform.Erasure$Eraser.scala$tools$nsc$transform$Erasure$Eraser$$adaptToType(Erasure.scala:665)
  at scala.tools.nsc.transform.Erasure$Eraser.adapt(Erasure.scala:766)
  at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5352)
```

This commit re-wraps the typechecked `qual` in its original
`<qual>.asInstanceOf[T]` to preserve semantics while avoiding
the big-O blowup.

Review by @paulp, @magarcia

### CODE REVIEW

**Comment by paulp** [comment]
LGTM

**Comment by som-snytt** [comment]
Yep, that was visually non-obvious.

**Comment by magarciaEPFL** [comment]
Once tests pass, LGTM

**Comment by magarciaEPFL** [comment]
PLS REBUILD/pr-scala@53f68cb

**Comment by magarciaEPFL** [comment]
What is the status of this PR?

**Comment by retronym** [comment]
Thanks for the reminder, it fell off my radar.

Looks like the new test is failing:

``` scala
  -usejavacp \
  Test \
  jvm > t7763-run.log
java.lang.RuntimeException: no CCE!
    at scala.sys.package$.error(package.scala:27)
```

I'll take a look at that now. Perhaps the cast is still being dropped under `-optimize`, which is used in the SCALAC_OPTS for partest in the build.

**Comment by retronym** [comment]
Yep, it was DCE. @magarciaEPFL Could you please review my additional commit?

**Comment by retronym** [comment]
PLS SYNCH

**Comment by magarciaEPFL** [comment]
Good catch. That fix for the latent bug in DCE is a welcome bonus (in addition to the regression fix). LGTM.

**Comment by retronym** [comment]
LGTM echo (for the bot)

**Pull request merged**
