### PR TITLE
ICodeReader parses exception handlers from bytecode

### PR DESCRIPTION
**Pull request by magarciaEPFL**
review by @VladUreche or @paulp or @dragos

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
What's troubling is that:
- the test suite didn't detect the error that was (fixed in the 2nd commit) 
- had a spurious failure (t5165, shown below) 

```
  [partest] testing: [...]/files/pos/t5165                                        [FAILED]
  [partest] TestTrait.scala:2: error: trait TestAnnotation is abstract; cannot be instantiated
  [partest] @TestAnnotation(one=TestAnnotation.TestEnumOne.A, two=TestAnnotation.TestEnumTwo.C, strVal="something")
  [partest]  ^
```
- the two other failing tests, when run in Jenkins, mention inliner warnings that I can't reproduce locally.

```
  [partest] testing: [...]/files/pos/polymorphic-case-class.scala                 [FAILED]
  [partest] error: there were 6 inliner warnings; re-run with -Yinline-warnings for details
  [partest] one error found


  [partest] testing: [...]/files/pos/t4911.scala                                  [FAILED]
  [partest] error: there were 3 inliner warnings; re-run with -Yinline-warnings for details
  [partest] one error found
```

Also troubling is the fact that all of them pass locally when run individually:

```
  partest -- files/pos/t5165

  partest -- files/pos/polymorphic-case-class.scala

  partest -- files/pos/t4911.scala 
```

**Comment by magarciaEPFL** [comment]
PLS REBUILD ALL

**Comment by lrytz** [comment]
in cases like that the two commits should be squashed - you can just `push -f` to the branch from which you made the pull request. we should not merge in any commits that don't pass the build.

**Comment by magarciaEPFL** [comment]
Yes, you're right. I was planning to re-submit later anyway, but wanted to check how the build fails again. On the plus side, the PR could already receive comments from the reviewers, given that the remaining issues are related to error messages only (or so it seems).

**Comment by lrytz** [comment]
to check if a branch passes the build, please use the https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/ job - pull requests are out in the public and take other people's time..

**Comment by gkossakowski** [comment]
If there a chance to put a few lines of docs in job's description on jenkins that explains how to do that? I didn't know anybody can trigger a job there.

**Comment by magarciaEPFL** [comment]
@lrytz: I'll close this PR once the builds are over, giving more time to reviewers to chime in, and continue the discussion at scala-internals.
Here's the branch: https://github.com/magarciaEPFL/scala/tree/icodereader-gets-exception-handlers-2

**Comment by lrytz** [comment]
@gkossakowski just go to https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/build it should be self-explanatory. if you don't have permission, let me know.

**Comment by magarciaEPFL** [comment]
Let's continue this discussion at 
https://groups.google.com/d/topic/scala-internals/XqkwsrlMeRc/discussion

**Pull request closed without merging**
