### PR TITLE
Refutability strikes back

### PR DESCRIPTION
**Pull request by retronym**
Addresses an nasty regression in for-comprehension desugaring (SI-6968) with a reversion, and then claws back some of the lost ground via overdue renovations to the refutability handling in `RefChecks`.

See the commit comments for all the gory details.

We can jettison a little bit more code from `RefChecks` when this is merged to master, it's marked with TODO comments.

Refutation or otherwise by @paulp (any other ideas on how to save `(a, b) <- either.right`?), and by @adriaanm (for my trespass in the pattern matcher.)

### CODE REVIEW

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
```
quick.plugins:
    [mkdir] Created dir: /localhome/jenkins/d/workspace/pr-scala-testsuite-linux-opt/build/quick/classes/continuations-plugin
[scalacfork] Compiling 5 files to /localhome/jenkins/d/workspace/pr-scala-testsuite-linux-opt/build/quick/classes/continuations-plugin
[scalacfork] error: uncaught exception during compilation: java.lang.ClassCastException
[scalacfork] error: java.lang.ClassCastException: scala.None$ cannot be cast to scala.Option$WithFilter
[scalacfork]    at scala.tools.nsc.backend.opt.InlineExceptionHandlers$InlineExceptionHandlersPhase$$anonfun$scala$tools$nsc$backend$opt$InlineExceptionHandlers$InlineExceptionHandlersPhase$$applyBasicBlock$2.apply(InlineExceptionHandlers.scala:156)
```

**Comment by retronym** [comment]
Damn, looks like `withFilter` neuters this approach; eliding it in `xs.withFilter(...).map` is problematic as we'd end up with a different `map`, and have to retypecheck the result. I've restricted it to cases where that isn't the case (poorly written `withFilter`s or old-school `filter`-s to keep correctness, but I'm running short of ideas now.

Well one more: I was looking at the `Alternative` node with some evil intent, wondering whether we could pass _both_ trees through the typechecker, deferring any errors, and then letting `RefChecks`  pick a winner.

PLS REBUILD ALL

**Comment by retronym** [comment]
Rebased, PLS REBUILD ALL

**Comment by retronym** [comment]
One option open to the reviewers (PING @paulp / @adriaanm) would be to admit the first commit (just a rollback) for 2.10.1, and defer the integration with the pattern matchers refutability until a subsequent release. As it turns out, it hardly ever kicks in because we can't eliminate `withFilter` calls, which change the type. See the discussion on the [comments of SI-6968](https://issues.scala-lang.org/browse/SI-6968?focusedCommentId=62360&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-62360)

**Comment by adriaanm** [comment]
sounds good -- i'm going to try to flush my PR backlog tomorrow

**Pull request closed without merging**
