### PR TITLE
SI-7109 SI-7153 Generalize the API to get docComments: allow to force do...

### PR DESCRIPTION
**Pull request by vigdorchik**
...cTrees

for given fragments. Don't type-check when forcing doc comments, but rather
 do it directly. Test the new functionality as well as better tests for
the old one.

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @huitseeker.

**Comment by JamesIry** [comment]
ping @huitseeker

**Comment by vigdorchik** [comment]
Review by @dragos

**Comment by huitseeker** [comment]
I'm **very** sorry for the time it took me to get back to this review. This is a _great_ PR, which deserved swifter treatment (I'm marred by build problems I'm only solving now — again, I'm sorry). An unrelated test fails reliably (@dragos reproduced the problem : `test/files/run/reflection-java-annotations`), on this PR as well as its merge-base — it shouldn't hinder the merge in any way.

LGTM !

**Comment by xeno-by** [comment]
If you rebase against the head of 2.10.x, the test failure will be fixed.

**Comment by vigdorchik** [comment]
@JamesIry ping. Should I rebase?

**Comment by JamesIry** [comment]
Let's find out...

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
it builds ok: https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/856/console

merging so @paulp 's refactoring isn't blocked

**Comment by paulp** [comment]
@adriaanm but of course I really need it to make it all the way to master. I can merge 2.10.x into master if necessary, unless someone is already?

**Comment by adriaanm** [comment]
I just submitted a PR.

**Pull request merged**
