### PR TITLE
SD-208 Restore 2.11 names for arrayOps implicits

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/559/

(PR validation will fail because this is binary incompatible)

**Comment by retronym** [comment]
Review by @soc

**Comment by adriaanm** [comment]
The bootstrap is not strappy enough:

```
[info] Running scala.tools.docutil.ManMaker fsc, scala, scalac, scaladoc, scalap /home/jenkins/workspace/scala-2.12.x-integrate-bootstrap/target/scala-dist/resource_managed/main/doc/tools /home/jenkins/workspace/scala-2.12.x-integrate-bootstrap/target/scala-dist/resource_managed/main/genman
[error] (run-main-0) java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
    at scala.tools.docutil.ManMaker.setCommand(ManMaker.scala:26)
    at scala.tools.docutil.ManMaker$.delayedEndpoint$scala$tools$docutil$ManMaker$1(ManMaker.scala:65)

```

**Comment by adriaanm** [comment]
Maybe a new starr will do if we skip making the manual for it?

**Comment by retronym** [comment]
This looks fishy to me:

```
lazy val manual = configureAsSubproject(project)
  .settings(disableDocs: _*)
  .settings(disablePublishing: _*)
  .settings(
    libraryDependencies ++= Seq(scalaXmlDep, antDep),
    classDirectory in Compile := (target in Compile).value / "classes"
  )
  .dependsOn(library)
```

Surely `ManMaker` could just rely on the STARR library.

**Comment by sjrd** [comment]
Would it help if, instead of removing the deprecated methods, they were moved up the hierarchy into `DeprecatedPredef` and made abstract there?

Thanks to covariant result types, this should typecheck. A bridge will be generated to implement the inherited abstract methods, and that bridge will satisfy the binary interface of the old methods.

**Comment by retronym** [comment]
@sjrd That sounds like it would help in this instance, but I'm first [trying a different](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/561/) approach to setting up the classpath that runs the `ManMaker` utility, which should be a more general fix.

**Comment by retronym** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/562/

**Comment by retronym** [comment]
After fixing the ManMaker problem, it looks this change is binary compatible with partest without bootstrapping.

I didn't expect that, there are many references to the removed methods in partest according to:

https://gist.github.com/c5071683f39aab7ba5d78949aec20cca

**Comment by retronym** [comment]
Looks like a bug in our build, a binary incompatible change with partest results in:

```
[warn] one warning found
[error] Uncaught exception when running tests: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
Exception in thread "Thread-29" java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at sbt.React.react(ForkTests.scala:114)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
    at java.lang.Thread.run(Thread.java:745)
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
    at scala.tools.partest.sbt.PartestRunner.tasks(Framework.scala:26)
    at sbt.ForkMain$Run.runTests(ForkMain.java:253)
    at sbt.ForkMain$Run.run(ForkMain.java:139)
    at sbt.ForkMain.main(ForkMain.java:121)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for test/it:testOnly
[error] Uncaught exception when running tests: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
Exception in thread "Thread-33" java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at sbt.React.react(ForkTests.scala:114)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
    at java.lang.Thread.run(Thread.java:745)
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
    at scala.tools.partest.sbt.PartestRunner.tasks(Framework.scala:26)
    at sbt.ForkMain$Run.runTests(ForkMain.java:253)
    at sbt.ForkMain$Run.run(ForkMain.java:139)
    at sbt.ForkMain.main(ForkMain.java:121)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for test/it:testOnly
[error] Uncaught exception when running tests: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
Exception in thread "Thread-37" java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at sbt.React.react(ForkTests.scala:114)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
    at java.lang.Thread.run(Thread.java:745)
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
    at scala.tools.partest.sbt.PartestRunner.tasks(Framework.scala:26)
    at sbt.ForkMain$Run.runTests(ForkMain.java:253)
    at sbt.ForkMain$Run.run(ForkMain.java:139)
    at sbt.ForkMain.main(ForkMain.java:121)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for test/it:testOnly
[error] Uncaught exception when running tests: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
Exception in thread "Thread-41" java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at sbt.React.react(ForkTests.scala:114)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
    at java.lang.Thread.run(Thread.java:745)
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
    at scala.tools.partest.sbt.PartestRunner.tasks(Framework.scala:26)
    at sbt.ForkMain$Run.runTests(ForkMain.java:253)
    at sbt.ForkMain$Run.run(ForkMain.java:139)
    at sbt.ForkMain.main(ForkMain.java:121)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for test/it:testOnly
[error] Uncaught exception when running tests: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
Exception in thread "Thread-45" java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at sbt.React.react(ForkTests.scala:114)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
    at java.lang.Thread.run(Thread.java:745)
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
    at scala.tools.partest.sbt.PartestRunner.tasks(Framework.scala:26)
    at sbt.ForkMain$Run.runTests(ForkMain.java:253)
    at sbt.ForkMain$Run.run(ForkMain.java:139)
    at sbt.ForkMain.main(ForkMain.java:121)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for test/it:testOnly
```

Which, rather than failing, results in 0/0 tests passed.

**Comment by retronym** [comment]
Involved SBT code: https://github.com/sbt/sbt/commit/c60223330d6d390eb058361b93a3a8c4cde51f63

**Comment by retronym** [comment]
Trying another [bootstrap](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/563/) with an updated checkfile.

**Comment by retronym** [comment]
I've reported SBT's failure to fail as https://github.com/sbt/sbt/issues/2722

**Comment by retronym** [comment]
I've pushed a new commit to the beginning of this PR that ought to unmask the expected failure in the last one.

**Comment by retronym** [comment]
Another bootstrap with the latest SHA: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/565/console

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/563/console failed due to https://github.com/scala/scala/pull/5365#issuecomment-243649066

**Comment by adriaanm** [comment]
Ugh. Let's just disable that one unit test of the deprecated pagedseq. We're not going to change that code anyway so it's doing more harm than good.

**Comment by retronym** [comment]
>  Let's just disable that one unit test of the deprecated pagedseq.

I've added a commit to this PR to that effect.

**Comment by retronym** [comment]
5d4bcaa does report the partest linkage error for `test/it:test`, but does not do so for `test/it:testOnly` (the `InputTask` aliased by the command `partest` and used by `testAll`)

The underlying problem is being fixed in SBT, so I can abandon defensive workaround if I can't make it work.

**Comment by adriaanm** [comment]
Based on https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/565/ and the discussions over at https://github.com/sbt/sbt/pull/2730 & co, it looks like this can be merged once it is the last RC1 PR?

**Comment by adriaanm** [comment]
This is now the last RC1 PR. Shall we merge, @retronym?

**Comment by retronym** [comment]
Yep, so long as a release and restarr follows promptly.

**Comment by adriaanm** [comment]
Will do. I was thinking we could use the nightly produced from this PR as
starr

**Comment by adriaanm** [comment]
Last one!

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
