### PR TITLE
show developer guidelines when users open a pull request

### PR DESCRIPTION
**Pull request by adriaanm**
review by @heathermiller, @jsuereth

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM - but.  HOW DID YOU BREAK THE BUILD ADRIAAN!

**Comment by retronym** [comment]
master is broken, I have two PRs in queue, both should fix it.

BTW, I'm working on a code review checklist of my own. https://gist.github.com/4f893fabfb4f51f22c3b

**Comment by adriaanm** [comment]
good stuff! contributing to this guide should go into the policy for reviewers

**Comment by jsuereth** [comment]
PLS REBUILD ALL

@retronym I merged your fix.

**Comment by heathermiller** [comment]
I just submitted a pull request to @adriaanm 's fork which contains a bit of rewording and some typo fixes.

**Comment by heathermiller** [comment]
https://github.com/adriaanm/scala/pull/3

**Pull request closed without merging**
