### PR TITLE
Closes SI-6358. Move accessor generation for lazy vals to typers.

### PR DESCRIPTION
**Pull request by hubertp**
Until now lazy accessors were handled somehow special because their symbol was created in typers but the corresponding tree was only added in Refchecks. This irregularity caused serious problems for value classes. Also it now looks just better when lazy value is treated in a similar way as other fields.

I needed to adapt reifier so that it handles the new implementation correctly. Previously it had to recreate lazy val only by removing defdef and renaming. Now we basically need to recreate lazy val from scratch.

There is one minor change to cps plugin but that is still fine because lazy vals were never really part of the transformation.

Review by @odersky and @xeno-by

### CODE REVIEW

**Comment by hubertp** [comment]
Awesome, I think this is the first time I managed to cause rangepos failure myself. I will fix that.

**Comment by retronym** [comment]
Looks like this also fixes the problems with nested objects (`followModuleClass`); that will need a test case. @harrah 's [test case from SI-6358](https://issues.scala-lang.org/browse/SI-6358?focusedCommentId=60029&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60029) should also be included.

**Comment by hubertp** [comment]
Right, I missed that test but it works for it as well. That doesn't fix nested objects, they still crash.

**Comment by hubertp** [comment]
Looks like I broke some of Eugene's very recent tests. Well that's annoying -> closing.

**Comment by retronym** [comment]
I see. With a bit of luck, the nested object fix will be as simple as sprinkling `followModuleClass = true` somewhere else. (See https://github.com/retronym/scala/commit/c386066)

**Comment by hubertp** [comment]
Yes and no. It will work if we move accessor generator to typers, similarly as for lazy vals. Currently it is done in refchecks. Without that we can add this changeOwner in various places and it will feel hackish and I won't have a confidence to say that it will not break sth more complicated.

**Comment by hubertp** [comment]
After some digging, those are not my tests failing. They are caused by #1385 and 2.10 is now broken.

**Comment by gkossakowski** [comment]
@hubertp: Are you saying that rangepos tests are failing due to #1385?

**Comment by hubertp** [comment]
No, rangepos is a valid one. But for normal build all failures are because of #1385 - you will see that newer PRs also fail because of that.

**Comment by xeno-by** [comment]
Okay I'm going to look into the failure asap

**Comment by xeno-by** [comment]
Fixed in #1391

**Comment by hubertp** [comment]
PLS REBUILD ALL

**Comment by hubertp** [comment]
Given the recent discussion on the mailing list I will close this PR as this is not going into 2.10.0.

**Pull request closed without merging**
