### PR TITLE
[nomerge] fix (?) REPL test that intermittently fails on Windows

### PR DESCRIPTION
**Pull request by SethTisue**
the test was rewritten on the 2.13.x branch and (although I'm not positive) I don't remember seeing it fail there, so this backports the 2.13 version; fingers crossed that will put an end to the intermittent failures

references scala/scala-dev#831

### CODE REVIEW

**Comment by som-snytt** [comment]
That's a good idea. The test was rewritten when the REPL was rewritten.

The PR title should probably say `fix (?!)`.

**Comment by som-snytt** [comment]
I see I tried to reproduce on actual Windows a month ago but could not. I was just trying again with `partest run`, no luck yet. Or whatever the opposite of luck is. Destiny?

**Comment by som-snytt** [comment]
Oh I see an `X`! but I won't know which test failed until the summary. Wish me luck! or destiny.

**Comment by som-snytt** [comment]
gah!
```
!!    1 - run/t2318.scala                           [non-zero exit code]
```
or
```
Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
        at java.base/java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:666)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:567)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at Test$Mgr$.checkPermission(t2318.scala:16)
        at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
        at java.base/java.io.File.exists(File.java:829)
        at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1262)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:319)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:424)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at Test$Mgr$.checkPermission(t2318.scala:16)
        at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
        at java.base/java.io.File.exists(File.java:829)
        at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1262)
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:319)
```

**Comment by SethTisue** [comment]
t2318 is a notorious troublemaker

**Comment by som-snytt** [comment]
I couldn't decide what tattoo to get on my left forearm, but now I know it must be `t2318`.

**Pull request merged**
