### PR TITLE
Support JDK 24 in optimizer (via ASM upgrade)

### PR DESCRIPTION
**Pull request by Philippus**
asm 9.7.1 was released some days ago, see https://asm.ow2.io/versions.html. This PR can be applied after someone does the honours in https://github.com/scala/scala-asm.

### CODE REVIEW

**Comment by lrytz** [comment]
@SethTisue this time, rebasing our fork will take a few adjustments.

Their changelog: https://gitlab.ow2.org/asm/asm/-/compare/ASM_9_7...ASM_9_7_1?from_project_id=125&straight=false

From https://github.com/scala/scala-asm/commits/s-9.7/
  - The latest commit (cb80825) can be dropped, they made a different fix for the same issue (https://gitlab.ow2.org/asm/asm/-/merge_requests/390)
  - 1553657 can *almost* be dropped, it was upstreamed (https://gitlab.ow2.org/asm/asm/-/merge_requests/414, https://gitlab.ow2.org/asm/asm/-/merge_requests/415, https://gitlab.ow2.org/asm/asm/-/merge_requests/416). But it seems one call is still missing... (https://github.com/scala/scala-asm/commit/1553657cc6a79068abe0ef71dd3a3f8066400bab#diff-e3cef1a741402550a937ceecd54f89d44387dd163228137f5db0a48f27e6077cL405-R405). I'll submit another PR upstream (https://gitlab.ow2.org/asm/asm/-/merge_requests/418).

**Comment by SethTisue** [comment]
Lukas's PR was merged 5 days ago — that's nice to see.

It's still pretty early in the JDK 24 cycle, and 2.13.16 is at least a month off if not longer, so I'm going to let this sit for a few weeks and hope that an ASM 9.7.2 comes along. If it doesn't, then I'll go ahead with the shading for 9.7.1.

**Comment by SethTisue** [comment]
https://asm.ow2.io/versions.html has no 9.7.2, so I'll go ahead with the shading.

**Comment by SethTisue** [comment]
The cherry-picking and rebasing seem to have gone fine.

As for the publishing, we need to update the Travis-CI secrets to use a user token, instead of a normal name/password, since Sonatype now requires that.

But the `travis encrypt` command wasn't working anymore for me:

```
/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1417:in `rescue in block in activate_dependencies': Could not find 'ffi' (>= 1.15.0) among 117 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/tisue/.gem/ruby/3.3.0:/opt/homebrew/lib/ruby/gems/3.3.0:/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/gems/3.3.0:/opt/homebrew/Cellar/travis/1.14.0/libexec' at: /opt/homebrew/Cellar/travis/1.14.0/libexec/specifications/ethon-0.16.0.gemspec, execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/rubygems/specification.rb:1414:in `block in activate_dependencies'
```

so the two possible paths here are "get `travis encrypt` working" and "switch to GitHub Actions".

I futzed with `rbenv` and `gem install` and such for a while, but I give up, this Ruby environment stuff has always been mysterious to me, and learning it better seems low-value. I'll switch it to GitHub Actions; doing so doesn't look like it will pose any special difficulties.

**Comment by SethTisue** [comment]
It's better anyway to get on sbt 1 (from 0.13.18) and sbt-ci-release; this was the last repo on our old bespoke module publishing scripts.

Gory details at https://github.com/scala/scala-asm/pull/14

**Comment by SethTisue** [comment]
confirmed that this script fails with 2.13.15, but succeeds with the PR validation snapshot:

```scala
#!/usr/bin/env -S scala shebang --server=false

//> using jvm 24
//> using repository https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/
//> using scala 2.13.16-bin-a5f8c62-SNAPSHOT
//> using option -opt:l:method

println("hi there")
```

**Pull request merged**
