### PR TITLE
Prevent useless filter refresh in docs

### PR DESCRIPTION
**Pull request by Jentsch**
Hi,
this deals with the scala doc JS.

Currently if you type a key inside the input field top left, the list below will be recalculated. This happens even if the input doesn't change (e.g. pressing shift or moving with arrow keys). Since the list could be very long this action takes some time and is a little bit annoying.

I added some lines (3) inside the JS of the scala doc generator to prevent that the filter operation if the field stays unchanged.

Also under: https://groups.google.com/forum/#!topic/scala-internals/Y1MdwOxhjZo
I hope you like this very minor change.

### CODE REVIEW

**Comment by adriaanm** [comment]
Welcome and thank you, @Jentsch! Review by @heathermiller or @sjrd.

**Comment by sjrd** [comment]
The code itself LGTM, and I've tested some manual manipulations. There is indeed noticeable improvement!

I have two "administrative" remarks:

1) You should never create a pull request out of your master branch. You should instead create a separate branch, add your commit, and create pull request from there. Why? Because if you create a pull request from your master, and then add new commits to your master, they are added to the pull request. I guess this is how the Merge commit of this pull request arrived there.

2) You should [sign the Scala CLA](http://typesafe.com/contribute/cla/scala). Also, the e-mail address of your commit is not linked to your GitHub account, hence GitHub does not recognize your commit as being yours.

**Comment by Jentsch** [comment]
1) So I should fix that a create a new pull request?
"I guess this is how the Merge commit of this pull request arrived there." You're totally right :-)

2) Updated to my GitHub account, now it should work, or?

**Comment by sjrd** [comment]
1) Yes, that would be great.

2) Somehow, it still doesn't work. You can see that at
https://github.com/Jentsch/scala/commit/2675dbb530fdda749068f8e94526135b90796a5e
beside the commit author "Jentsch", you can see a blue question mark that tells you the commit author is not recognized.

**Comment by sjrd** [comment]
Can someone with the rights close this pull request, please? It's been superseded by #3074.

**Comment by Jentsch** [comment]
Doesn't know that I could do that.

**Pull request closed without merging**
