### PR TITLE
SI-8677 Duration: Zero - Inf should be MinusInf

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fixes #8677. Add basic tests.
This is a backport from 2.12.x of dead39dc5f21c6eac41788e93426c50ddd398c24.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
This was a quick shot at backporting, let's wait for Travis to see if cherry-pick was enough as I expected.
Review by @Ichoran.

**Comment by Ichoran** [comment]
LGTM

**Comment by adriaanm** [comment]
Please prefix your commit title with [backport] -- speeds up merging.

Maybe we should leave 2.11.x as the default branch for now? /cc @scala/team-core-scala

**Comment by Blaisorblade** [comment]
@adriaanm Done :-).

**Pull request merged**
