### PR TITLE
SI-8738  Regression in range equality

### PR DESCRIPTION
**Pull request by Ichoran**
Missed the case of comparing a non-empty range to an empty one.  Fixed by checking nonEmpty/isEmpty on other collection.

Added a test to verify the behavior.

### CODE REVIEW

**Comment by Ichoran** [comment]
@lrytz @retronym - At least one of you probably want to review this since it's supposed to go in tomorrow!

**Comment by retronym** [comment]
Does it fix this bug "report" too? https://twitter.com/extempore2/status/490880769695305728

**Comment by Ichoran** [comment]
@retronym - Yes, that's fixed.

**Comment by lrytz** [comment]
LGTM

**Comment by som-snytt** [comment]
That's pretty good turnaround.  Not to complain or anything, but any change to a Setting requires a clean build.  Right now, just waiting for the test suite.  Can't even enjoy a beer with it, because someone wants to go back to Great America.

**Pull request merged**
