### PR TITLE
SI-6122: Small changes to reflection API to make it safe for IDE use.

### PR DESCRIPTION
**Pull request by dragos**
- Removed `typeSymbol` and `termSymbol` from `reflect.api.base`, and pushed them down to
  `reflect.api`.
- extracted `TypeTree.symbol` to a top-level method so it can be overridden in lower cake layers (this is the only method in trees that can trigger type checking and therefore is not thread safe.

review by @odersky, @xeno_by

### CODE REVIEW

**Comment by xeno-by** [comment]
I'm @xeno-by, because github doesnt allow underscores in names. Other than that there are a few comments.
1) Would we be binary compatible if in the future we need to re-add TypeBase?
2) Can typeTreeSymbol be made inline, so that it doesnt degrade performance?

**Comment by dragos** [comment]
Sorry for misnaming :)

As for questions:

> 1) Would we be binary compatible if in the future we need to re-add TypeBase?

No, all methods that return the abstract type `Type` would change signature (since its erasure would move from `Object` to `TypeBase`). I don't if there are any methods like that, but I imagine there should be.

> 2) Can typeTreeSymbol be made inline, so that it doesnt degrade performance?

No, that method needs to be overridable, so it can't be final. I need to overwrite it in the IDE _cake_, and add the proper synchronization around the call to `typeSymbol`. But I don't think it's really slowing anything down, I doubt it's a hotspot.

**Comment by xeno-by** [comment]
I see, then I suggest we leave TypeBase as an empty abstract class.

**Comment by dragos** [comment]
Sure, I can do that. I'll `push --force` my changes.

**Comment by dragos** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
LGTM

**Pull request merged**
