### PR TITLE
(1 of 2) of the rest of the new bytecode emitter

### PR DESCRIPTION
**Pull request by magarciaEPFL**
After the discussion in https://github.com/scala/scala/pull/2802 about breaking up that PR into two parts, here's the first part, comprising the first four commits (for which no pending issues were identified during review).

As to the 2nd part, I'll submit a new PR incorporating review feedback, that will build upon the commits in this PR.

review by @gkossakowski

### CODE REVIEW

**Comment by soc** [comment]
[Edit by @adriaanm: when you're not listed as a reviewer, please don't start your comment with "LGTM", as that will mark the PR as reviewed. That gives the real reviewer a fake sense of security. See also: the bystander effect.] LGTM.

**Comment by magarciaEPFL** [comment]
In a nutshell, the "decouple" commits are baby steps towards pipelining of class building and class writing, ie allowing class building (which requires typer) and "the rest" (which doesn't) to run in parallel.

The comment below is reproduced from an upcoming commit. It's not part of this PR because, for ease of review, commits are fine-grained.

> GenBCode: pipelined class building and class writing
> 
> Traversing a ClassDef to build an ASM ClassNode requires typer and therefore must run single-threaded.
> 
> However, bytecode transformers that manipulate ClassNodes don't need typer and thus can run in parallel.
> 
> Two other activities that don't depend on typer either are:
> - encoding ClassNodes into the byte array representation of a classfile
> - writing classfiles to disk
> 
> The activities above (building ClassNodes, encoding, disk writing) are performed in different threads (for now, "encoding" is only lightly loaded, but in the future certain optimizations will run there).

**Comment by magarciaEPFL** [comment]
@gkossakowski , in case you want to add comments, I've incorporated your feedback so far into
https://github.com/magarciaEPFL/scala/compare/backendish40

I'm running the nightly on that branch. Seems best to submit a PR from there, and discard this one.

**Comment by magarciaEPFL** [comment]
Superseded by https://github.com/scala/scala/pull/2863

**Comment by soc** [comment]
@adriaanm Sorry, didn't know that.

**Pull request closed without merging**
