### PR TITLE
[backport] SI-7237 Always choose ForkJoinTaskSupport

### PR DESCRIPTION
**Pull request by soc**
ForkJoinTaskSupport works on Hotspot, Avian and J9,
while ThreadPoolTaskSupport causes the test
test/files/scalacheck/parallel-collections
to reliably hang on all three.

### CODE REVIEW

**Comment by axel22** [comment]
I think this will reliably crash any 1.5 version of the JVM.
While I think this is safe:

```
if (scala.util.Properties.isJavaAtLeast("1.7")) new ForkJoinSupport
else if (scala.util.Properties.isJavaAtLeast("1.6")) {
  val vendor = scala.util.Properties.javaVmVendor
  if ((vendor contains "Oracle") || (vendor contains "Sun") || (vendor contains "Apple")) new ForkJoinTaskSupport
  else new ThreadPoolTaskSupport
} else new ThreadPoolTaskSupport
```

I think this allows us to gracefully deprecate `ThreadPoolTaskSupport`:

```
if (scala.util.Properties.isJavaAtLeast("1.6")) new ForkJoinSupport
else new ThreadPoolTaskSupport
```

This, however:

```
new ForkJoinTaskSupport
```

will surely start crashing anybody on 1.5.
I am aware we no longer support 1.5, but maybe we shouldn't just shut 1.5 support (however weak it was) in a minor release.

**Comment by soc** [comment]
I'll test it on Java 5.

**Comment by soc** [comment]
Ok, I think @axel22's suggestion is the way to go. I did neither manage to build Scala (trunk/2.10.x) on Java 5 nor test it on Java 5.

**Comment by soc** [comment]
Ok, what I would do now is to go ahead with the fix suggested by @axel22 for 2.10 and reopen the original PR #2249 change against trunk, because they are now different.

This way we have a bit less to remember when the next deprecation/removal cycle happens.

**Comment by JamesIry** [comment]
ping @soc @axel22 what's the current status on this PR?

**Comment by axel22** [comment]
The change LGTM!

**Comment by JamesIry** [comment]
LGTM (echoing @axel22 in a way that the bot can see)

**Comment by soc** [comment]
What's left now is to reopen the PR #2249 and merge it into trunk.

**Pull request merged**
