### PR TITLE
remove outdated ENSIME info

### PR DESCRIPTION
**Pull request by SethTisue**
as suggested by @fommil

if up-to-date info on hacking Scala using ENSIME becomes
available in the future, better we simply link from our readme to that
info on the ENSIME site where it can be more easily updated

### CODE REVIEW

**Comment by fommil** [comment]
http://ensime.org/contributing/scalac/

**Comment by SethTisue** [comment]
@fommil thanks, I've pushed a revised commit that adds that link to README.md

**Comment by SethTisue** [comment]
see also https://github.com/ensime/ensime.github.io/pull/162

**Comment by SethTisue** [comment]
review by @lrytz?

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
