### PR TITLE
Fix for SI-6084, type alias crasher.

### PR DESCRIPTION
**Pull request by paulp**
"no need for pt.normalize here, is done in erasure"

ORLY? Review by @adriaanm.

### CODE REVIEW

**Comment by retronym** [comment]
The assertion in `mkCast` means we don't get as far as erasure. So the [original comment](https://github.com/scala/scala/commit/214c145#L11L1916) might have been accurate.

I'm curious now: what unseen evils might  `mkCast` be guarding against by checking that the type is normalized? Why not just normalize it defensively rather than trip the assertion?

**Comment by paulp** [comment]
You're right, I meant to suggest the comment that there was "no need" implied a fragile dependency on exactly what was to happen between there and erasure.

I thought the same thing, it's hard to believe "f(x.normalize)" isn't almost always superior to "assert(x eq x.normalize) ; f(x)".

**Comment by paulp** [comment]
Too much indirection in last sentence.  Rephrased: "f(x.normalize) is superior."

**Comment by paulp** [comment]
I guess I think the error is spurious.

PLS REBUILD ALL

**Comment by adriaanm** [comment]
I think the original assertion stems from the days when mkCast was only called from erasure. Since it's more universally applicable, I agree with @retronym that we should turn the assert in a defensive normalize (unless it turns out we do this often and it costs too much?). In any case, LGTM.

**Comment by retronym** [comment]
Cost isn't an issue as the assertion already calls normalize.

**Comment by paulp** [comment]
Good point.  What we can do, if there is some consensus that aliases arriving there represents a mistake rather than the normal mode of operation, is log them when they do arrive.  It'd be helpful to know what is the overarching reasoning under which we should consider this a mistake, though.

**Pull request merged**
