### PR TITLE
SI-7569 Fix end position in PostfixSelect tree

### PR DESCRIPTION
**Pull request by paulp**
introduced in 5b54681: the end position of Postfix operators should
take the operator length into account.

review by @som-snytt

### CODE REVIEW

**Comment by som-snytt** [comment]
LGTM in my rear-view mirror, too.  Though objects may be closer than they appear.

**Comment by som-snytt** [comment]
Except for the part where the test fails.

**Comment by adriaanm** [comment]
LGTM!

**Comment by dotta** [comment]
@adriaanm Thanks! Scala IDE nighlty builds against 2.10.3-SNAPSHOT are now back to a shiny blue!

**Pull request merged**
