### PR TITLE
SI-7438 Avoid a performance bug in our JSR166 redistribution

### PR DESCRIPTION
**Pull request by retronym**
Use `execute` unconditionally, rather than `fork`, which in some
fairly easy to provoke circumstances fails to utilize all available
cores.

The longer term fix is the update to the latest version of the JSR133
code, and then the restore the use of `fork`.

Benchmark and results:

  https://gist.github.com/retronym/5495585

Review by @phaller.

Even if we do decide to update FJ in 2.10.2, I think that we should start with this commit. This gives us better "rollback-ability" of the FJ update in case of some unexpected problem.

### CODE REVIEW

**Comment by retronym** [comment]
Perhaps we should pursue the upgrade, too.

http://cs.oswego.edu/pipermail/concurrency-interest/2013-May/011258.html

> > The most recent versions of jsr166y and jsr166e do not suffer from this bug.
> > 
> > A workaround using the revision of jsr166y shipped in Scala is not to use `fork`
> > in our global "execution context". However, this seems like a drastic measure,
> 
> Right, don't do this.

**Comment by phaller** [comment]
Yeah, that's what I had feared. Also, according to Doug, "jsr166y (i.e., updates of jdk7 functionality usable on JDK6+) hasn't changed incompatibly recently", which is good.

So, for better rollback-ability I'm OK with this commit, but we should definitely keep SI-7438 open, and prepare a PR with the FJ update.

**Comment by retronym** [comment]
Furthermore, AFAICT the parallel collections by default _don't_ use `ExecutionContextImpl`, and instead directly use `ForkJoinTaskSupport`, which calls `fork` as well.

``` scala
  private[parallel] def getTaskSupport: TaskSupport =
    if (scala.util.Properties.isJavaAtLeast("1.6")) new ForkJoinTaskSupport
    else new ThreadPoolTaskSupport

  val defaultTaskSupport: TaskSupport = getTaskSupport
```

This is contrary to the comment:

``` scala
/** A task support that uses an execution context to schedule tasks.
 *  
 *  It can be used with the default execution context implementation in the
 *  `scala.concurrent` package. It internally forwards the call to either a
 *  forkjoin based task support or a thread pool executor one, depending on
 *  what the execution context uses.
 *  
 *  By default, parallel collections are parametrized with this task support
 *  object, so parallel collections share the same execution context backend
 *  as the rest of the `scala.concurrent` package.
 *
 *  @see [[scala.collection.parallel.TaskSupport]] for more information.
 */
class ExecutionContextTaskSupport(val environment: ExecutionContext = scala.concurrent.ExecutionContext.global)
extends TaskSupport with ExecutionContextTasks
```

**Comment by phaller** [comment]
It seems `ExecutionContextTaskSupport` is unused. @axel22: maybe this was an oversight in 6aca8a074ac7c05d3bb2429bffa7ce922f9c8bd9 ? I suspect that it was meant to be:

``` scala
  private[parallel] def getTaskSupport: TaskSupport = new ExecutionContextTaskSupport
```

**Comment by viktorklang** [comment]
Doug clearly advises against _not_ using fork(), so I think the proper fix is to include a newer version of FJP, Doug should be able to point to a specific version.

However, it is important that we make sure that our Unsafe detection etc is ported to that version.

**Comment by axel22** [comment]
@phaller Yes, this is an oversight - it should be using the `new ExecutionContextTaskSupport`, that internally checks if the execution context is using the fork/join pool and then attempts to apply certain fork/join-related optimizations when spawning tasks.

**Comment by retronym** [comment]
Closing in favour of a straight FJ upgrade.

**Pull request closed without merging**
