### PR TITLE
Warn about `@elidable` under -Xsource:3

### PR DESCRIPTION
**Pull request by som-snytt**
Follow-up to https://github.com/scala/scala/pull/10408
~Addresses https://github.com/scala/docs.scala-lang/issues/2288~

### CODE REVIEW

**Comment by som-snytt** [comment]
or maybe that is too annoying, as there is no replacement idiom.

**Comment by lrytz** [comment]
Yeah, let's keep an eye on https://github.com/lampepfl/dotty/pull/17329 and close this for now.

**Comment by SethTisue** [comment]
`-Xmigration` exists for this kind of thing, though I suspect it's little-used.

**Comment by SethTisue** [comment]
(Another possible venue is the Scala 3 migration tool.)

**Comment by som-snytt** [comment]
At the definition, I would just deprecate, except we need deprecate under the unfortunate `-Xsource:3`.

Shall I reopen this for `elidable`? I suggested somewhere that dotty should warn that it doesn't support it, instead of silently ignoring it.

**Comment by som-snytt** [comment]
The replacement idiom in the doc (for Scala 3) almost works in Scala 2, except that the conditional is not inlined.

Normally, `if (false)` is elided in refchecks. Currently, the optimizer doesn't touch `if (1 == 1)`, for example, which is the result of inlining with constant value arg.

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
> Shall I reopen this for `elidable`?

You confused me there for a minute :)

**Pull request merged**
