### PR TITLE
Compiler optimizations for Scopes, checkDoubleDefs, Namer

### PR DESCRIPTION
**Pull request by retronym**
Resubmission of #3771, adds a unit test for Scope and
fixes the boostrap error from the previous attempt.

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
I've added two more optimizations in Namers, so review by @lrytz / @adriaanm.

**Comment by retronym** [comment]
Failures here are the presumed flaky IDE test that @dragos is investigating.

**Comment by adriaanm** [comment]
screenshot 2014-05-23 18 20 17
Infinity -- going into the weekend with a!!

**Comment by dragos** [comment]
@retronym, the flaky test _might_ be fixed by scala-ide/scala-ide#700.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@403ab0e

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
NOLITTER!

**Comment by gkossakowski** [comment]
> Double definitions of top level classes/objects are issued elsewhere, as demonstrated by the enclosed test. So we can omit the call to `checkNoDoubleDefs` in this content.

I think you wanted to say:

> Double definition errors of top level classes/objects are issued elsewhere, as demonstrated by the enclosed test. So we can omit the call to `checkNoDoubleDefs` in this context.

**Comment by gkossakowski** [comment]
Once commit message gets reworded and last commit gets squashed this will LGTM.

**Comment by lrytz** [comment]
LGTM, too.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@a6714f8

**Comment by retronym** [comment]
The test failure was in `run/t5293-map.scala`, a performance test for parallel collections. I assume it is sensitive to load on the machine.

**Comment by retronym** [comment]
PLS SYNC

image

**Pull request merged**
