### PR TITLE
Revert "SI-6039 Harden against irrelevant filesystem details"

### PR DESCRIPTION
**Pull request by paulp**
This reverts commit b0758f5cb9d966b940933d48bdbb45d17a80de66.

This commit sent startup time through the roof, at least in some circumstances
(it is presumably related to one's current working directory.)

### CODE REVIEW

**Comment by paulp** [comment]
Fast track to self-reversion.

**Comment by som-snytt** [comment]
Unless you're going to write something, I could try to come up with a protocol like `invalidateClassPathEntries` so that when Random is not in scala.util, before erroring out, and util is empty, ask it to rescan for something meaningful on the path.

**Comment by paulp** [comment]
I am wary of trying to apply this logic lazily.

**Comment by som-snytt** [comment]
OK, then, I'm lazy enough to try. Today is Kindergarten field day, for which I'm enlisted, so maybe this weekend. Except this weekend is the annual screening of Singin' in the Rain.  Gotta dance!  I'll see what I can come up with.

**Comment by paulp** [comment]
Oh, it's a wonderful bonus that that was the test creating root "util" directories. Let's not let that sort of thing slip in again.

**Comment by som-snytt** [comment]
I think I mentioned that you weren't rm-ing it at PR time; that's when you agreed it was time for a tmp dir for tests, which I haven't given further thought to (because I totally forgot about it; maybe my post-it fell off).

**Comment by paulp** [comment]
You did; I was going to fix it but was too slow, and someone else merged it. From that point I allowed it to nag at me until today.

**Pull request merged**
