### PR TITLE
Handle static fields correctly in Constructors

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by adriaanm** [comment]
Review by @JamesIry

**Comment by xeno-by** [comment]
Would be great to have a non-empty commit message.

**Comment by soc** [comment]
@xeno-by Agree, I'm working on adding more details.

The reason why I created the PR as-is is because of the code duplication which I want to fix. `findStaticCtor` and `addStaticInits` is basically copied from the private ones in Cleanup. I'd love to hear your opinion @JamesIry and @xeno-by what's the best place to move this functionality to.

**Comment by xeno-by** [comment]
Probably James would be the best person to answer this question, as I've almost never ventured outside namer and typer.

**Comment by soc** [comment]
I created a new PR with a detailed commit message: https://github.com/scala/scala/pull/3224

**Pull request closed without merging**
