### PR TITLE
Awaitable.result should have a throws annotation of TimeoutException and InterruptedException as well as Awaitable.ready 

### PR DESCRIPTION
**Pull request by takayahilton**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Seems reasonable to me!

**Comment by viktorklang** [comment]
Since the @throws-annotations are primarily for Java users, this change would be a breaking change, would it not?

**Comment by dwijnand** [comment]
Yeah, source-breaking for Java users.

**Comment by SethTisue** [comment]
or not source-breaking, since `@throws(classOf[Exception])` was already present?

merging regardless, it's okay to break source in this way.

**Pull request merged**
