### PR TITLE
REPL: upgrade JLine to 3.24.1 (was .22)

### PR DESCRIPTION
**Pull request by SethTisue**
relevant release notes:

* https://github.com/jline/jline3/releases/tag/jline-parent-3.23.0
* https://github.com/jline/jline3/releases/tag/jline-parent-3.24.0
* https://github.com/jline/jline3/releases/tag/jline-parent-3.24.1

unclear if any of our users will notice these changes. (maybe the Windows fixes?)

references scala/scala-dev#856

### CODE REVIEW

**Review by som-snytt — APPROVED** [review]
if you say so

**Comment by SethTisue** [comment]
Let's wait for 3.24.1, which will restore support for JDK 8, as per https://github.com/jline/jline3/issues/888#issuecomment-1787279373

**Comment by SethTisue** [comment]
I verified locally that 3.24.1 works on JDK 8, as advertised.

**Comment by som-snytt** [comment]
A much better outcome.

**Pull request merged**
