### PR TITLE
Merge 2.12.x into 2.13.x [ci: last-only]

### PR DESCRIPTION
**Pull request by dwijnand**
```
$ git log --oneline --graph $(git merge-base 2.12.x 2.13.x)..2.12.x    # see below
$ git merge -sours e32b224ee1
$ git merge c26463c096
$ git merge -sours 5997a61e30
$ git merge aab332980d
$ git merge -sours 4a26288168
$ git merge 3c16136033
$ git merge -sours 529f089f25
$ git merge 490e3e342a
$ git merge -sours 8e73c8c093
$ git merge bde271aae6
$ git merge -sours dc511c34a8
```

```
SKIP  *   dc511c34a8 (origin/2.12.x, 2.12.x) Merge pull request #9192 from retronym/t12140-map-merge
      |\
      | * 5a7ef0df3c Fix NPE regression in immutable.HashMap.merge
      |/
^SKIP *   e14e830e0d Merge pull request #9194 from dwijnand/partest-uses-scalap
      |\
      | * f04fcd8486 Add scalap to partest's IJ config
PICK  * |   bde271aae6 Merge pull request #9131 from retronym/ticket-12085
      |\ \
      | |/
      |/|
      | * 4746d541b0 Drop bug compatibility with Java privacy of inner classes
      | * f5ff2107ac Deterministic InnerClass attribute under joint/separate compilation
      | * 54a2bee380 Refactor DeterminismTest to expose internals as an app.
^PICK * |   24f3c54e12 Merge pull request #9163 from dwijnand/exhaust-tuple-unsealed-false-positive
      |\ \
      | * | e5bda188e8 Fix exhaustivity uncheckableType's logic for tuples
^PICK * | |   d3fb332bed Merge pull request #9191 from eatkins/settings-bin-compat
      |\ \ \
      | |_|/
      |/| |
      | * | ce8e3dfbfd Restore binary compatibility for doc.Settings
^PICK * | |   1264f2ae4d Merge pull request #9182 from dwijnand/java-annot-arrays
      |\ \ \
      | * | | 2569ed7e1d Handle NestedAnnotArg from Java sources
^PICK * | | |   73bb6312de Merge pull request #9184 from dwijnand/cleanup/java-parser-annots
      |\ \ \ \
      | |_|/ /
      |/| | |
      | * | | 3ecfc649ee Cleanup JavaParser.annotation
      | |/ /
SKIP  * | |   8e73c8c093 Merge pull request #9190 from lrytz/no-partest-module
      |\ \ \
      | * | | 03999190d4 [nomerge] no longer build external partest module in release scripts
      |/ / /
^SKIP * | |   975a9b65f6 Merge pull request #9102 from mkeskells/2.12.x_DoubleOps
      |\ \ \
      | |/ /
      |/| |
      | * | 95f0ba07d4 don't box primitive values  to call static methods on java.lang.Double/Float/Integer etc don't box primitives to call hashCode/toString copy with trees with side effect add tests to verify no boxing
PICK  * | |   490e3e342a Merge pull request #9179 from retronym/topic/xasync-stability
      |\ \ \
      | * | | 8d913c3dd4 Make async compiler output deterministic
SKIP  * | | |   529f089f25 Merge pull request #9178 from dwijnand/delambda-meth-ref-java-interfaces
      |\ \ \ \
      | * | | | 1b0e8a09c3 Fix -Ydelambdafy:method-ref on a Java annotation
      |/ / / /
^SKIP * | | |   d8f3e8b22b Merge pull request #9169 from dwijnand/2.12/wb-partest
      |\ \ \ \
      | |/ / /
      |/| | |
      | * | | 6651375f73 Drop flagsfile support, port test suite
      | * | | 1c0b8e4104 Kill pos checkfiles
      | * | | 8a125d3fa9 [nomerge][2.12] Welcome back Partest!
      |/ / /
^SKIP * | |   75221266e0 Merge pull request #9091 from mkeskells/2.12.x_array_copy
      |\ \ \
      | |/ /
      |/| |
      | * | 6ae4136d09 simplify mima exceptions
      | * | 31d6481b8a review feedback - use the ClassTag to hold the empty Arrays and WrappedArray
      | * | 7bba932953 simplify signature
      | * | 1fb249c635 Use java.util.Arrays.copyOf to extend or contract arrays, when  the content of the previous array is to be copied into the new Array
PICK  * | |   3c16136033 Merge pull request #8750 from retronym/topic/add-serializable-warnings
      |\ \ \
      | * | | 559f6fbdae Refactor prior fix to module class symbol cache invalidation
      | * | | bce614f1bb Heed warning about cache invalidation after making object Serializable
      |  / /
^PICK * | |   1de5f175c5 Merge pull request #9147 from dwijnand/exhaust-tuple
      |\ \ \
      | * | | 93d1a5e107 Check all bindings exhaustively, e.g. tuples components
SKIP  * | | |   4a26288168 Merge pull request #9159 from dwijnand/2.12/improve-IntelliJ-project-configuration
      |\ \ \ \
      | * | | | ceda795656 Improve IntelliJ project configuration
      | |/ / /
PICK  * | | |   aab332980d Merge pull request #9167 from mkeskells/2.12.x_remove_unneeded_conversion
      |\ \ \ \
      | * | | | 9416cb9066 remove unneeded conversion
      | | |_|/
      | |/| |
SKIP  * | | |   5997a61e30 Merge pull request #8986 from mkeskells/2.12.x_smallMap++
      |\ \ \ \
      | * | | | 3c548a7647 Map ++ without CBF should use the same optimised path as ++ with CBF also optimise for small map addition
      |  / / /
^SKIP * | | |   2838d04545 Merge pull request #9165 from mkeskells/2.12.x_import
      |\ \ \ \
      | |/ / /
      |/| | |
      | * | | 1b02a84e2e remove unused import
      |/ / /
PICK  * | |   c26463c096 Merge pull request #9160 from dwijnand/restarr
      |\ \ \
      | |/ /
      |/| |
      | * | 6c806e025a Add version/scalaVersion info to onLoadMessage
      | * | 67f9cb27a4 Add restarr/restarrFull custom commands
      |/ /
SKIP  * |   e32b224ee1 Merge pull request #9022 from dwijnand/indy-meth-refs
      |\ \
      | * | 7ec7251eed Emit method reference lambdas without helper method
      |  /
^SKIP * |   77f30f97f2 Merge pull request #9119 from ivanopagano/topic/t10035-2.12-backport
      |\ \
      | * | e5175d1e70 Add same changes from the PR #7178
      |/ /
^SKIP * |   ac3fb5f79a Merge pull request #9108 from lrytz/assertUtilBackport
      |\ \
      | * | eee6c24f47 [backport] Exchange stack for Stack in assertNotReachable
      | * | 0160f27ef6 [backport] Avoid race in test for firstCompletedOf
      | * | b3c0fc09c1 [backport] bring AssertUtil fixes to 2.12
      | |/
^SKIP * |   53f8d5ec04 Merge pull request #9116 from retronym/t12067-companion-determinism
      |\ \
      | * | 598bac4e44 Remove exploratory assertions
      | * | 604fc09089 Stabilize order of synthetic modules in enclosing class decls
      |/ /
^SKIP * |   33dd751281 Merge pull request #9115 from retronym/topic/2.12.12-restarr
      |\ \
      | |/
      |/|
      | * 71114c87df Bump to Scala 2.12.12
      |/
^SKIP *   cbe6ade174 (tag: v2.12.12) Merge pull request #9083 from lrytz/smallCleanups
      |\
      | * 5ba248e819 Add a comment to HashMap.castToThat
      | * e675917e22 [nomerge] small cleanups
^SKIP * d332b43d60 Merge pull request #9087 from retronym/topic/reusable-instance-2.12.x
      * 69d55a620e [backport] Disable all reusable instances in runtime reflection
      * 181eb8191a [backport] Rework recent, buggy change to immutable.TreeMap
```

### CODE REVIEW

**Comment by dwijnand** [comment]
@retronym mind looking at `DeterminismTest.testReferenceToInnerClassMadeNonPrivate` please (😴)?

**Comment by dwijnand** [comment]
@sjrd The ClassTag change in #9091 that affected Scala.js's build I skipped here, but that might follow in cherry-pick/forward-port PR.

**Review by lrytz — APPROVED** [review]

**Comment by retronym** [comment]
I've added a fix for https://github.com/scala/bug/issues/12156

**Comment by dwijnand** [comment]
Thanks, Jason!

**Pull request merged**
