### PR TITLE
Fixes SI-6214.

### PR DESCRIPTION
**Pull request by hubertp**
addSynthetics was calling typedStat that caused flushing error buffer. Typically that would result in errors being re-added but addSynthetics was the last thing to run in typedStats.
Instead of adding yet another check I used this as an opportunity to cleanup the once necessary workaround for typing stats. Since we are now chaining buffers of contexts manual handling is no longer necessary.

Review by @odersky (I recall that you were planning to cleanup that part at some point).

### CODE REVIEW

**Comment by paulp** [comment]
Patches like this look GREAT to me!

**Comment by hubertp** [comment]
does GREAT translate to LGTM?

**Comment by paulp** [comment]
Isn't Great > Good in everyone's language? LG+TM.

**Comment by hubertp** [comment]
I think I was blinded by this "GREAT" that I didn't read entirely the whole sentence ;)

**Pull request merged**
