### PR TITLE
Extracted abstract implicit vals from Types.

### PR DESCRIPTION
**Pull request by paulp**
These should be considered plumbing and not blended in with the
rest of the api.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @xeno-by

**Comment by xeno-by** [comment]
lgtm, i agree

**Comment by retronym** [comment]
In the old scheme or new, it would be nice to reflectively test that all the tree subclasses have a corresponding type tag.

**Comment by JamesIry** [comment]
echoing @xeno-by to get the build kitty to see it.

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
