### PR TITLE
Fix SI-9147 Override `getOrElseUpdate` in `concurrent.Map`.

### PR DESCRIPTION
**Pull request by axel22**
Also, add a ScalaCheck test.

### CODE REVIEW

**Comment by axel22** [comment]
Review by @Ichoran

**Comment by axel22** [comment]
With the change:

```
scala> Test.main(Array())
+ concurrent.TrieMap.concurrent getOrElseUpdate insertions: OK, passed 100 tests.
```

Without:

```
scala> Test.main(Array())
! concurrent.TrieMap.concurrent getOrElseUpdate insertions: Falsified after
   0 passed tests.
> Labels of failing property:
2 threads agree on who inserted [disagreement (differentResults, position)  = Some((Set(0, 1),1))]
> ARG_0: 2
> ARG_0_ORIGINAL: 13
> ARG_1: 2
> ARG_1_ORIGINAL: 3372
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
    at sbt.Defaults$$anonfun$consoleTask$1$$anonfun$apply$38.apply(Defaults.scala:766)
    at sbt.Defaults$$anonfun$consoleTask$1$$anonfun$apply$38.apply(Defaults.scala:766)
    at scala.Option.foreach(Option.scala:236)
    at sbt.Defaults$$anonfun$consoleTask$1.apply(Defaults.scala:766)
    at sbt.Defaults$$anonfun$consoleTask$1.apply(Defaults.scala:761)
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
    at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

**Comment by Ichoran** [comment]
LGTM

**Comment by axel22** [comment]
Thanks!
But overriding a method in a trait causes a binary compatibility issue, so I guess we can merge this only into 2.12.x.

**Comment by Ichoran** [comment]
Oops, I didn't check that it was 2.12.x.  I thought you were targeting that.  WLGTM when it's against 2.12.x....

**Comment by axel22** [comment]
Yep, I had opened both of them:

https://github.com/scala/scala/pull/4323

**Pull request closed without merging**
