### PR TITLE
Use java-diff-utils for diffing in partest.

### PR DESCRIPTION
**Pull request by adriaanm**
It's not clear to me how partest's classpath is managed, so I hacked it in.

review by @paulp, @phaller, @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
Would be nice to use the [versionMapper](http://maven.apache.org/ant-tasks/reference.html#versionMapper) facility to strip the `-1.3.0` from the JAR file so you don't need to repeat that all over the place. Disclaimer: I don't know how to use that, I just found it now...

**Comment by adriaanm** [comment]
Agreed in principle. I just feel I've had my fill after almost two weeks of XML.

**Comment by retronym** [comment]
In lieu of that, a comment at at the definition of that version number that points to the spots where it is duplicated would be needed.

**Comment by adriaanm** [comment]
You drive a tough bargain.

**Comment by gkossakowski** [comment]
Am I the only one that finds commit message of 81c357c insufficient?

What "hack it in" means here? Also, it's worth mentioning that the diff format has changed and that's why one of the test cases was touched.

**Comment by paulp** [comment]
Do we really need this dependency? What is wrong with running "diff" to diff things? Don't we only use diff to display checkfile differences to humans?

Adding a dependency has a high cost when all effects are properly accounted for, as you know. In one of my partest branches (maybe even the one which has a peer pull request to this one) I use git word diff if it's available, and regular diff otherwise. Even cygwin-or-whatever users will have diff. Why add complexity to the build?

**Comment by adriaanm** [comment]
My understanding is that we do quite a lot of diffing so it may not be that efficient to fork a git diff all the time. Maybe it is. I don't think this maven dependency is such a huge deal. Invoking external commands is just another, less explicit, dependency with other things that can go wrong.

**Comment by adriaanm** [comment]
The new commits are strictly a rewording of the commit message according to Greg's review.

**Comment by adriaanm** [comment]
working on rebasing this onto #2314

**Comment by paulp** [comment]
> My understanding is that we do quite a lot of diffing so it may not be that efficient to fork a git diff all the time.

I do not think we do quite a lot of diffing. On a successful test run, what diffs are there? There is a lot of string comparing, yes. Then if you have failing tests, there is diffing, but this is hardly something to optimize for. You will never in a million years feel the performance cost of spinning off a couple shells to run diff for your handful of failing tests.

The difference between a dependency on j random javalibrary and a dependency on a program which every system already has is that in the latter case, every system already has it. And if there ARE unix-like systems which don't have "diff", well again, this is hardly something to optimize for.

**Comment by som-snytt** [comment]
We always check check files.  In my private fastest branch, I added a strcmp before invoking diff, just for fun.  I don't know that it helped make fastest faster.  I did try building scala jars with compression turned off, and that took 30 secs off the test suite, which is 30 secs of CPU.  (I haven't tested the diff-on-failure tweak in Testicolor yet, due to lazy incompetence.  I'll try it on cygwin-or-whatever.)

**Comment by adriaanm** [comment]
I honestly don't see the big deal depending on a 30K jar for an internal testing tool. I think the integration is much nicer than dealing with forking on multiple platforms, acros multiple versions of diff. All that gives is us more potential for spurious test failures. If we worry about the size of our distribution, how about just not distributing partest at all -- isn't that the end goal anyway? (I.e., it becomes a separately distributed project.)

**Comment by adriaanm** [comment]
rebased onto #2330

**Comment by paulp** [comment]
It's not the size, it's the existence of an unnecessary dependency. I can't convince myself that "diff" is more likely to create issues than a java lib via maven.

We already use diff in partest scripts, as you know, e.g. tools/stability-test.sh. Is it your plan to rip existing usages out and make everything use the java lib? You basically have to do that, or we depend on both, which must be strictly inferior to depending on one or the other. But to be doing that, it does not seem like progress.

Will the java lib provide colorized word diffs like git does?

I'm not saying I don't see uses for a java diffing library; I do. And "big deal" is your characterization. My position is that it's suboptimal to ignore ubiquitous tools which can already perform the required task. And that nobody properly accounts for dependencies. I think the typical programmer (present company excepted of course) gauges the cost of a dependency the same way they estimate how long something will take: by envisioning best-case everything from here to eternity.

**Comment by som-snytt** [comment]
> I think the typical programmer ... by envisioning best-case everything from here to eternity.

Actually, we assume that a temporal incursion by a hostile alien will reset the time line to a point where the ship has not been destroyed and the captain is still alive and well and living in Nazi-occupied Brooklyn, NY.

**Comment by adriaanm** [comment]
My plan is to spend as little time on issues like this as possible while keeping us moving forward. I don't want to spend more time on this than I already have.

**Comment by gkossakowski** [comment]
LGTM.

When it comes to using external diff I think this should be an option and not a default. I know that you can run partest from ant on Windows and I wouldn't want to make this more difficult. If this dependency turns out to cause troubles we can always remove it. It's not like it's being used by some core logic in the compiler. I'm glad to see that we get rid of copy&pasted implementation of a diff algorithm from our code base.

**Comment by gkossakowski** [comment]
I'll merge once kitten is done with testing rebased commits.

**Pull request merged**
