### PR TITLE
Optimization in List.

### PR DESCRIPTION
**Pull request by paulp**
Mark all the closure-accepting methods which have implementations
within List as @inline final so the closures can be eliminated.
(All the methods are effectively final anyway, as Nil and :: are
the only possible subclasses.) And compromise with respect to
the inlining of inherited methods by overriding foreach (responsible
for over 300 closures) with an inlinable implementation.

Review by @gkossakowski.

### CODE REVIEW

**Comment by jsuereth** [comment]
Dunno about @gkossakowski, but it LGTM.   The one method override is sad, maybe we can put a ticket it to fix it with your proposal on the mailing list?

**Comment by paulp** [comment]
It's so far from the worst example of such things in our codebase (four lines buys 300 closures!) that I considered it below the noise threshold to worry about beyond commenting it.

**Comment by gkossakowski** [comment]
I'm not happy this got merged. We need to fix the inliner and make methods in `LinearSeqOptimized` final. That's the only sensible way to move forward.

Those 300 closure are not news for me. I was tweaking List implementation for quite a while, see:

https://github.com/gkossakowski/scala/commit/f7891ada0b26b045371a6dab2be5d5c552ef9532
https://github.com/gkossakowski/scala/commit/9243ec3d6284b6fd4fdae6a5eb09a95f6b674650

Notice that in the first commit I didn't put `foreach` because it turns out that at _runtime_ `forall` and `exists` cause far more closure allocations than `foreach`.

When it comes to optimizations I'd prefer if we first stated what we optimize for, then measure and then decide. Also, I'd prefer that we work on real fixes (to optimizer) that scale over copy pasting that really doesn't scale.

Having said all of that I don't want this patch to be reverted because I reviewed it too late. I just wanted to express my general thoughts on optimizations. If we have another patch like that coming I'm very likely to reject it (on time).

**Comment by jsuereth** [comment]
Perhaps we need some sort of "requirement" for optimisation enhancements?   I.e.   some statistics like runtime performance improvements in various scenarios as well as bytecode size?    That would make it a lot easier to make determinations and accurately know trade-offs.  I apologize for merging before you reviewed.

**Comment by gkossakowski** [comment]
I don't want to anybody to think I'm blowing this out of proportion. In the end, it's a few lines of code as Paul said. However, I'm trying to make it clear that with that approach we'll get nowhere, really. We need to work on fixes that scale.

When it comes to statistics I'm working on such a tool at the moment. I'm planning to write a bit on it once I have all data I need. At the moment I'm busy with gathering statistics for all scala commits since 1st of March. Benchmarks are running for a week now. Also, I'm working on visualisation part so we'll see nice charts of wallclock performance, object allocations (e.g. closure allocations), method call counts, etc. All this will be automated. That's part of working on solutions that scale.

**Comment by paulp** [comment]
It's not one or the other.  Try to make it one or the other and we go 5+ years with a glacial "1 to 100 foreach". As measures of expedience go, this is as innocuous as it gets.  If there's to be an absolute prohibition on anything short of perfect solutions that's fine, let's revert 99.9% of trunk.  If not, then you can't swing a dead cat without hitting a commit which is a bigger problem than this.

I don't know why you have all this energy to fight my commits (sight unseen in the case of partest) when there are 250,000 lines of scala in the repo which maybe you haven't seen yet; and boy, if you think four commented, purpose-designated, completely isolated, easily revertible lines are a problem, do I have some bad news for you.

**Comment by ijuma** [comment]
"make methods in LinearSeqOptimized final."

This would be a breaking change, right?

I understand the concerns about localised fixes instead of generic improvements, but it's important to strike the right balance instead of just blocking improvements with substantial benefits to users simply because a better solution may be implemented sometime in the undefined future. Particularly when the localised fix is as simple as this and can be reverted easily once the generic fix is implemented.

**Comment by gkossakowski** [comment]
@ijuma: In which sense it's breaking change?

I'm arguing here that this is not localized fix. In order to achieve anything with List for just one project (compiler) you need to copy&paste several more methods. It's slippery slope that leads you quickly to problems with collections as we had them in Scala 2.7 (that implementations were repeated in several places and diverging over time).

**Comment by retronym** [comment]
It would break existing code that overrides those methods. Fortunately, it's not needed; Paul outlined a plan to make the inliner smarter to consider a non-final method (e.g. `IndexedSeq#foreach`) inherited by a (effectively) final class (e.g. `List`) as inlinable. 

Once that is in place, it's clear that the copy/paste can and should be reverted.

**Comment by ijuma** [comment]
What @retronym said. Adding final to overridable methods in public classes is an incompatible change.

**Pull request merged**
