### PR TITLE
[backport] SI-9616 False positive in unused import warning

### PR DESCRIPTION
**Pull request by som-snytt**
This is a minimal backport of the fix for SI-9383.

Review by @retronym

### CODE REVIEW

**Comment by SethTisue** [comment]
/nothingtoseehere

(integrate-ide failure is unrelated to the PR)

**Comment by som-snytt** [comment]
It's like magic. It's like `/xyzzy`.

**Comment by retronym** [comment]
Backport of #4616

**Comment by retronym** [comment]
LGTM

**Pull request merged**
