### PR TITLE
SI-7960: add member keyword to the resultExtractionCode for ValHandler

### PR DESCRIPTION
**Pull request by esarbe**
first try; simply use the member keyword

### CODE REVIEW

**Comment by esarbe** [comment]
Can someone give me a hint on how to proceed?

**Comment by retronym** [comment]
A number of test cases need to have expectations updates because they compare the textual output of the REPL session with a reference "checkfile".

The Jenkins failure log includes:

```
# 1718/1784 passed, 66 failed in run

# Failed test paths (this command will update checkfiles)
partest --update-check \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/class-symbol-contravariant.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/constant-type.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/constrained-types.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/lub-visibility.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/reflection-equality.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/reflection-repl-classes.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/reflection-repl-elementary.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-assign.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-bare-expr.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-classbased.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-no-imports-no-predef-classbased.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-no-imports-no-predef-power.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-no-imports-no-predef.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-out-dir.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-parens.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste-2.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste-3.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste-4.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste-5.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste-6.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste-raw-b.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste-raw.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-paste.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-power.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-reset.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-save.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-serialization.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/repl-transcript.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t1500.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t1931.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t3376.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t4172.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t4216.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t4285.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t4542.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t4671.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t5072.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t5256d.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t5535.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t5537.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t5583.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t5789.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6086-repl.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6146b.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6187.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6273.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6320.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6329_repl.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6329_repl_bug.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6381.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6434.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6439.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6507.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6549.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t6937.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t7139 \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t7185.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t7319.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t7482a.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t7747-repl.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t7801.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t8843-repl-xlat.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t8918-unary-ids.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/t9749-repl-dot.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/tpeCache-tyconCache.scala \
  /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/xMigration.scala

[error] Failed: Total 1784, Failed 66, Errors 0, Passed 1718
[error] Failed tests:
[error] 	partest
```

**Comment by retronym** [comment]
Locally, you could just run `sbt "partest --update-check --run"`.

**Comment by esarbe** [comment]
@retronym Ah, thanks a lot! I'll take care of it.

**Comment by SethTisue** [comment]
closing for inactivity. we can reopen if activity resumes

**Pull request closed without merging**
