### PR TITLE
Prefer scala-cli pragmas [ci: last-only]

### PR DESCRIPTION
**Pull request by som-snytt**
Goal is to remove the old header parsing.

Global replace changes range positions in output. (Which also change in a recent PR.)

Conversion of `java:` and `javaVersion:` to follow. Edit: uses javaOpt, javacOpt. Edit: also jvm for javaVersion.

Edit: remove old header parsing. Remove one usage of `hide:` in favor of `DirectTest`. `filter` must be quoted if it has embedded spaces.

Follow-up to https://github.com/scala/scala/pull/10756

### CODE REVIEW

**Comment by som-snytt** [comment]
Missed a few pragmas that were slightly irregular.

One test failure confused me. It's actually testing that multiple pragmas (on different lines) are picked up, but that was broken. However, it happened to exercise the ambiguity between inherited member and def in scope. I guess it's a warning (2.13.14) that is promoted to error if -Xsource;3, but the message text is the same. But the reference is not ambiguous in the sense of erroneous; it's merely confusing.

I'm not sure what I was testing: maybe documenting status quo that "last pragma wins". The companion test shows both options in one pragma (with comma separation). scala-cli appears to accumulate and keep both pragmas, as it errors irrespective of the order of the two pragmas.

```
➜  scala git:(tweak/test-flags) ✗ skalac -d /tmp/sandbox test/files/neg/using-source3.scala
test/files/neg/using-source3.scala:14: warning: reference to f is ambiguous;
it is both defined in the enclosing class D and inherited in the enclosing class E as method f (defined in class C)
In Scala 2, symbols inherited from a superclass shadow symbols defined in an outer scope.
Such references are ambiguous in Scala 3. To continue using the inherited symbol, write `this.f`.
Or use `-Wconf:msg=legacy-binding:s` to silence this warning. [quickfixable]
    def g = f
            ^
1 warning
➜  scala git:(tweak/test-flags) ✗ skalac -Xsource:3 -d /tmp/sandbox test/files/neg/using-source3.scala
test/files/neg/using-source3.scala:14: error: reference to f is ambiguous;
it is both defined in the enclosing class D and inherited in the enclosing class E as method f (defined in class C)
In Scala 2, symbols inherited from a superclass shadow symbols defined in an outer scope.
Such references are ambiguous in Scala 3. To continue using the inherited symbol, write `this.f`.
Or use `-Wconf:msg=legacy-binding:s` to silence this warning. [quickfixable]
Scala 3 migration messages are issued as errors under -Xsource:3. Use -Wconf or @nowarn to demote them to warnings or suppress.
Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=scala3-migration, site=D.E.g
    def g = f
            ^
1 error

```

**Comment by SethTisue** [comment]
@som-snytt I'm sorry this was ignored so long. If you rebase it, I promise to review/merge promptly.

**Comment by som-snytt** [comment]
Who keeps pushing so-called improvements to partest? Nobody cares about partest. People have to get over themselves.

Squashed and resolved conflicts (in favor of this version, except for deleted tests). I may have stepped on my own toes.

**Comment by SethTisue** [comment]
Thank you! It's nice to reduce friction when moving test code back and forth between partest, vulpix, and scala-cli.

**Pull request merged**
