### PR TITLE
add test coverage for SI-8627 (Stream.filterNot)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
review/merge by @Ichoran?

**Comment by lrytz** [comment]
@SethTisue you could remove the override of `def filter`, it is no longer necessary in 2.12.x: https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/Stream.scala#L525

**Comment by SethTisue** [comment]
re `filter`, see #4640

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
