### PR TITLE
add to Enumaration withNameOpt returning Option

### PR DESCRIPTION
**Pull request by meirmaor**

### CODE REVIEW

**Comment by JamesIry** [comment]
I'm sympathetic to the desire to expose what's already happening under the covers, but do you have a case where having a special method is better than doing either Try(enum.withName("foo"))\* or enum.find(_.name = "foo") ?
- http://www.scala-lang.org/archives/downloads/distrib/files/nightly/docs/library/index.html#scala.util.Try

If you can make a good case for this then please also add tests for both the modified withName and the new withNameOpt methods. I know they're very simple methods, but we're trying to improve test coverage of the library in general and the only way to get there is incrementally.

**Comment by meirmaor** [comment]
Using Try(enum.withName("foo")) will cause an exception which is both ugly
and slow.
iterating over the values with find is less elegant and
is basically working with internals, we could theoretically have a better
implementation then find
I would like it hidden.
Obviously you can do find, but I think the library should provide it.
The library consistently provides two versions apply and get / getOrElse
for a Map, or Option
or head and headOption.

**Comment by som-snytt** [comment]
With an enum it's more clearly an error to ask for a bad name. Probably the macro-based enum someone comes up with won't even compile if handed a bad literal.

But I remember that in my first piece of sample code, I was miffed that the exception didn't tell me the bad string:

  /*\* Like withName, but throws a NoSuchElementException with a meaningful message.
   */
  def forName(n: String): Direction =
    (values find (_.toString == n) getOrElse { throw new java.util.NoSuchElementException(n) }
    ).asInstanceOf[Direction]

**Comment by soc** [comment]
In the hope that we can get rid of the current Enumeration implementation in the mid term I would prefer not increasing the surface area of Enumeration.
With the rise of extension methods, I think everyone can add a method like that to Enumeration himself/herself.

@som-snytt Yes, I think that would certainly be an option. The only thing preventing better enums are the impossibility(?) of emitting static members to bytecode.

**Comment by paulp** [comment]
I agree that this is not adequately motivated.

**Pull request closed without merging**
