### PR TITLE
fixes a crash in PatternMatching for positionless trees

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review @adriaanm

**Comment by gkossakowski** [comment]
What kind of code triggers this crash?

**Comment by xeno-by** [comment]
Trees generated by a quasiquote unapply macro, which currently lack positions. We will assign some meaningful positions to those trees later, but this doesn't diminish the fact that the check in PatternMatching needs to be hardened against trees that don't fit its assumptions.

**Comment by gkossakowski** [comment]
Well, that's my question: if the assumption is wrong or not. I thought that it's a bug that you don't have position assigned to a tree.

**Comment by xeno-by** [comment]
I don't know. The fact that after this patch has been applied positionless trees began to compile without crashes, suggests that in principle our compiler doesn't mind them. /cc @adriaanm @paulp

**Comment by gkossakowski** [comment]
It might only prove that it doesn't have enough of assertions. Did you try to run your code with -Yrangepos?

Also, IDE cares a lot about positions.

**Comment by xeno-by** [comment]
No I didn't test with `-Yrangepos`.

**Comment by adriaanm** [comment]
the compiler is not the only relevant party: as Greg mentioned, the IDE crucially relies on them
in general, an argument like "it doesn't crash" is not convincing.

you are working on core parts of the compiler: the kind of correctness arguments we make here must be much more rigorous

**Comment by xeno-by** [comment]
I thought the words "don't know" and "suggest" would convey the fact that I don't feel myself knowledgeable enough to provide any arguments.

Anyway, what's our verdict on the matter at hand?

**Comment by paulp** [comment]
Last I heard the IDE doesn't use positions after typer. Is that true, not true, was true but no longer? For sure there is some point beyond which positions are assumed to be hosed.

**Comment by gkossakowski** [comment]
@xeno-by: pull requests are not a way of making research or asking for opinion. We have mailing list for that.
The idea is that if you propose a change you did a few basic things:
1. You did your homework and you checked that your modification is aligned with general design goals of the compiler. If you are not sure err on the side of keeping things as-is.
2. You throughly tested your change (especially if you are playing around with assumptions).
3. You are confident enough that you can defend your change against grumpy reviewers (put your defense into commit message so we can safe time spent asking for it).

I vote for closing this pull request. I'll let @adriaanm make a final call as he is reviewer.

**Comment by xeno-by** [comment]
_here I posted a comment, which belongs to a different pull request_

**Comment by xeno-by** [comment]
http://groups.google.com/group/scala-internals/browse_thread/thread/79b7636fcd5b31b9

**Pull request closed without merging**
