### PR TITLE
Issue/8325 spec update

### PR DESCRIPTION
**Pull request by som-snytt**
Remove the clause in 3.2.8 that reserves `*` as a postfix
modifier thing.  For emphasis, the language that an infix
type name can be an arbitrary identifier is retained, sans buts.

### CODE REVIEW

**Comment by adriaanm** [comment]
For our reference, fixed by #444 & #3576. It's a bit late to ask, but, for my info, where was this change discussed? The tickets around this (https://issues.scala-lang.org/browse/SI-8325, https://issues.scala-lang.org/browse/SI-5702) are a bit terse.

**Comment by retronym** [comment]
Perhaps I was hasty in merging #3576. I assumed this was a bug fix in the parser, rather than an inconsistency in the spec.

**Comment by adriaanm** [comment]
It's probably fine, but it does introduce more look/peek-ahead (the only other instance I saw was also for something starry).

**Comment by som-snytt** [comment]
Sorry for the veneer of presumption.  

The pattern case was motivated around https://issues.scala-lang.org/browse/SI-3189.

Back then, I didn't know star was prohibited by the spec. In retrospect, maybe regular expression syntax did make it prohibitive, but that's just a guess.

The current fix is for regularity with that change; at some point I noticed that it was specified.

It seemed easy to disambiguate. As usual, would be nice to have a test ensuring that performance was not affected.

**Comment by adriaanm** [comment]
LGTM That it seemed more like a bug than a spec change says it all, I 'spose.

**Comment by som-snytt** [comment]
Seems? Nay, it is.  I know not seems.

**Pull request merged**
