### PR TITLE
Merge/2.11.x to 2.12.x 20160203 [ci: last-only]

### PR DESCRIPTION
**Pull request by retronym**
```
% git co -b merge/2.11.x-to-2.12.x-20160203 origin/2.12.x
Branch merge/2.11.x-to-2.12.x-20160203 set up to track remote branch 2.12.x from origin.
Switched to a new branch 'merge/2.11.x-to-2.12.x-20160203'

% export MB=$(git merge-base head origin/2.11.x)

% transcript git log --graph --oneline --decorate $MB...origin/2.11.x
https://gist.github.com/1a3acdfcb215a9f62756

% git merge bf599bc
Auto-merging versions.properties
CONFLICT (modify/delete): src/scaladoc/scala/tools/nsc/doc/html/resource/lib/jquery.layout.js deleted in HEAD and modified in bf599bc. Version bf599bc of src/scaladoc/scala/tools/nsc/doc/html/resource/lib/jquery.layout.js left in tree.
Auto-merging src/scaladoc/scala/tools/nsc/doc/html/page/Template.scala
CONFLICT (content): Merge conflict in src/scaladoc/scala/tools/nsc/doc/html/page/Template.scala
Auto-merging src/reflect/scala/reflect/internal/Symbols.scala
Auto-merging src/library/scala/math/package.scala
Auto-merging src/library/scala/concurrent/duration/Duration.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Contexts.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/typechecker/Contexts.scala
Auto-merging src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala
Auto-merging src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
Auto-merging src/compiler/scala/tools/nsc/transform/UnCurry.scala
Auto-merging src/compiler/scala/tools/nsc/transform/Constructors.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/transform/Constructors.scala
CONFLICT (modify/delete): src/compiler/scala/tools/nsc/backend/opt/ConstantOptimization.scala deleted in HEAD and modified in bf599bc. Version bf599bc of src/compiler/scala/tools/nsc/backend/opt/ConstantOptimization.scala left in tree.
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/opt/BytecodeUtils.scala
Auto-merging project/Osgi.scala
Auto-merging build.sbt
Automatic merge failed; fix conflicts and then commit the result.

% git commit -a
[merge/2.11.x-to-2.12.x-20160203 9535599] Merge commit 'bf599bc' into merge/2.11.x-to-2.12.x-20160203

% git log bf599bc..8c50d84
commit 8c50d842a39e2a5f02aca462b834ab2b0c2a14af
Author: Som Snytt <som.snytt@gmail.com>
Date:   Thu Jan 7 14:38:49 2016 -0800

    [backport] SI-9616 False positive in unused import warning

    This is a minimal backport of the fix for SI-9383.

% git merge -sours 8c50d84
Merge made by the 'ours' strategy.

% git merge cc6fea6
Auto-merging test/junit/scala/reflect/ClassTagTest.scala
Auto-merging src/library/scala/concurrent/Future.scala
Auto-merging src/compiler/scala/tools/nsc/ast/parser/TreeBuilder.scala
Auto-merging src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
Auto-merging src/compiler/scala/reflect/quasiquotes/Parsers.scala
Auto-merging scripts/jobs/integrate/bootstrap
CONFLICT (content): Merge conflict in scripts/jobs/integrate/bootstrap
Auto-merging build.sbt
CONFLICT (content): Merge conflict in build.sbt
Auto-merging README.md
Automatic merge failed; fix conflicts and then commit the result.

% git commit
[merge/2.11.x-to-2.12.x-20160203 b1a6fc2] Merge commit 'cc6fea6' into merge/2.11.x-to-2.12.x-20160203
```

### CODE REVIEW

**Comment by retronym** [comment]
Needed to merge 2.12.x onto this PR because of a new, trivial conflict in `versions.properties`.

**Comment by lrytz** [comment]
Anything to review, or all conflicts were easy to fix?

**Comment by retronym** [comment]
Review of the end result of `build.sbt` by @szeiger.

Other conflicts were straightforward enough. There was a big typo-fixing commit that caused some trivial conflicts.

**Comment by szeiger** [comment]
LGTM

**Pull request merged**
