### PR TITLE
SI-9029 Fix regression in extractor patterns

### PR DESCRIPTION
**Pull request by retronym**
The unified treatment of classical and named-based pattern matching
does not correctly handle the generalization of "tuple capture".

By "tuple capture", I mean:

```
scala> object Extractor { def unapply(a: Any): Option[(Int, String)] = Some((1, "2")) }
defined object Extractor

scala> "" match { case Extractor(x: Int, y: String) => }

scala> "" match { case Extractor(xy : (Int, String)) => }
warning: there was one deprecation warning; re-run with -deprecation for details

scala> :warnings
<console>:9: warning: object Extractor expects 2 patterns to hold (Int, String) but crushing into 2-tuple to fit single pattern (SI-6675)
              "" match { case Extractor(xy : (Int, String)) => }
                              ^
```

Name based pattern matching, new in Scala 2.11, allows one to
deconstruct the elements that structurally resembles `ProductN`:

```
scala> class P2(val _1: Int, val _2: String)
defined class P2

scala> object Extractor { def unapply(a: Any): Option[P2] = Some(new P2(1, "2")) }
defined object Extractor

scala> "" match { case Extractor(x: Int, y: String) => }
```

However, attempting to extract the `P2` in its entirety leads to
an internal error:

```
scala> "" match { case Extractor(p2: P2) => }
<console>:10: warning: fruitless type test: a value of type (Int, String) cannot also be a P2
              "" match { case Extractor(p2: P2) => }
                                            ^
<console>:10: error: error during expansion of this match (this is a scalac bug).
The underlying error was: type mismatch;
 found   : P2
 required: (Int, String)
              "" match { case Extractor(p2: P2) => }
                 ^
```

Note that this match was legal and warning free in 2.10.

This commit avoids the hard-coded assumption that the "tuple capture"
results in a `TupleN`, and instead keeps track of the product-ish
type from which we extracted the element types. I have also opted not
to limit the deprecation warning to `TupleN` extractors.

Review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
I've added an error message improvement for SI-8989.

**Comment by lrytz** [comment]
probably just needs an update-check on `neg/t4425b.scala`, the error messages changed (improved).

**Comment by retronym** [comment]
I'll need to double check that checkfile to see if the changes are intentional / desirable.

**Comment by retronym** [comment]
Okay, I'm happy to say the additional and more meaningful error messages in `neg/t4425b.scala` are a progression.

**Comment by retronym** [comment]
Review by @lrytz, perhaps?

**Comment by lrytz** [comment]
> I have also opted not to limit the deprecation warning to `TupleN` extractors.

IUC, that means you'd like to issue a deprecation warning for non-tuple extractors, which is not the case after this PR: the warning is [only emitted for tuple types](https://github.com/retronym/scala/commit/f1e553ecfbea25bcc7e13294f6104d599336f460#diff-20d2fda1a1aa8a03cadc629ba46214dfR149), the [test doesn't produce any warning](https://github.com/retronym/scala/commit/f1e553ecfbea25bcc7e13294f6104d599336f460#diff-6df1b2d488e80094881921f7f359b3cc).

**Comment by retronym** [comment]
Issuing a deprecation warning for non-tuple extractors would be more regular. But looking at that test case, I'm not sure that even the opt-on warning is as justifiable as the tuple version, so I chose not to make previously warning-free programs emit a warning.

**Comment by retronym** [comment]
> the method tupleExtractor is now unused, should be removed

Removed

**Comment by lrytz** [comment]
That makes sense to me. It's just that the wording in the commit message seems a bit ambiguous, so I wanted to double-check.

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
