### PR TITLE
SI-7781 REPL stack trunc shows cause

### PR DESCRIPTION
**Pull request by som-snytt**
The handy stack trace truncation in REPL doesn't show cause like a regular trace.

This commit fixes that and also adds the usual indicator for truncation, viz, "... 33 more".

The example from the ticket produces:

```
    scala> rewrapperer
    java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Point of failure
      at .rewrapper(<console>:9)
      at .rewrapperer(<console>:10)
      ... 32 elided
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Point of failure
      at .wrapper(<console>:8)
      ... 34 more
    Caused by: java.lang.RuntimeException: Point of failure
      at .sample(<console>:7)
      ... 35 more
```

Suppressed exceptions on Java 7 are handled reflectively.

```
    java.lang.RuntimeException: My problem
      at scala.tools.nsc.util.StackTraceTest.repressed(StackTraceTest.scala:56)
      ... 27 elided
      Suppressed: java.lang.RuntimeException: Point of failure
        at scala.tools.nsc.util.StackTraceTest.sample(StackTraceTest.scala:29)
        at scala.tools.nsc.util.StackTraceTest.repressed(StackTraceTest.scala:54)
        ... 27 more
```

Review by @qerub

### CODE REVIEW

**Comment by som-snytt** [comment]
Rebased again in case that helps Jenkins not fail, presumably spuriously.  It compiles for me, with all the fixin's.

**Comment by retronym** [comment]
Looks to me like this requires Java7 to build.

``` scala
  val suppressable = isJavaAtLeast("1.7")
  type Suppressing = { def addSuppressed(t: Throwable): Unit }

  def repressed: String = try { sample } catch {
    case e: Throwable =>
      val t = new RuntimeException("My problem")
      if (suppressable) {
        val s: Suppressing = t
```

It would need an `asInstanceOf` to compile against both 6 and 7.

**Comment by som-snytt** [comment]
I thought I built it both ways.  OK, thanks.  So much for coding at 3 a.m.

Edit: It's in my history, but maybe I got the time line wrong at that time of morning.

> bigant6 all.clean ; bigant6 ; bigant6 test.run

**Comment by som-snytt** [comment]
Possibly I didn't notice the build error, and then tests appeared to run OK because all.clean wasn't yet cleaning the junit dir, so the old test classes were still getting run.  I noticed that when I changed the name of the test class, hence the second commit.

**Comment by som-snytt** [comment]
Updated.  Thanks @retronym .  test.junit runs, but I just saw a failure under test.run.  It's unsupported class version, run/t6168b.  Hopefully it's just something lame in my setup.  The output says it used java 6 for build and test, but I've been lied to before.  Occasionally, I've lied to myself. 

Edit: sorry, kitteh, I owe you an apology.  I take back all the mean things I muttered under my breath.

Footnote to self: looks like running ./partest from the test dir broke with the change to make it possible to run test/partest.

Update: partest uses partest.javac_cmd (javac) to run whatever happens to run, irrespective of JAVA_HOME.  Despite all vagaries, I'm sure I used to run v6 tests. Maybe something changed. Or, maybe previously the javac on the path was always v6.

**Comment by som-snytt** [comment]
Updated to filter out the frame count from the result to check.  I'd swear I had also run an optimised build at some point, but even so, "69 elided" could change with any backend change.

Tests can declare filters for check files, I recently recalled, but for now the SessionTest must do it manually.

**Comment by som-snytt** [comment]
In a different context, I just realized why the build system behaves as it does.  It's Schroedinger's kitteh.

**Comment by gkossakowski** [comment]
@som-snytt: what's the status of this PR?

**Comment by gkossakowski** [comment]
Also, assigned to @retronym who already looked into that.

**Comment by som-snytt** [comment]
@gkossakowski Thanks.  The "... elided" marker is the cat's meow.  I already posted what must be the first elided stack trace on SO, but for some reason I didn't get one of those badges.

This is just further work on what @qerub started, and at one point I said to myself, I can't believe it's -- whatever year it is -- and I'm writing code to print a stack trace!  This is my second stack trace fix, after the script line nums.

I haven't reviewed this myself yet, but I know that with @retronym eyes on it, it won't end up crappy and might get spun into gold.  They should call him @retrostiltskin.

**Comment by som-snytt** [comment]
Thanks @qerub .  I was lazy that night because kitteh was so slow; I wanted to delete the extra parens too but didn't dare touch anything.

This tweak makes it a bit more natural. 

There's also a question about when to force `code` and `expected`.  I was previously annoyed that `eval` is an iterator; but now I see that everything should be lazy, for the reasonable case of a test of many, possibly infinite lines of source that will terminate usefully.

Currently, `DirectTest` still takes `code` as a String.

I just realized that it is github's annoying refresh that is sending me to the top of the page. I rare UI mis-step by github.

The default ant target wasn't building partest-extras. Partest and its extras are not just a test artifact, they are a first-class product of the build!

It was an error of the maven people who saw test as something subsequent to the product. But test is more like the compiler, either precedent or at least coterminous with other artifacts required for producing the product.

**Comment by som-snytt** [comment]
@qerub I just noticed you had updated the "session" transcript.  That's interesting, because my idea was for the session to be a straight copy/paste.  Right now, partest has no --update option to fix these inline session transcripts, but maybe someday. (Normalizing both expected and actual means it just works.)

**Comment by som-snytt** [comment]
Removed the last commit with a build tweak for partest-extras.

**Comment by qerub** [comment]
> @qerub I just noticed you had updated the "session" transcript. That's interesting, because my idea was for the session to be a straight copy/paste. 

Uh… That wasn't part of my original plan. Updated patch: https://github.com/qerub/scala/commit/02a23494581d30a7c5d86e94f9af174ecd4c3326

**Comment by gkossakowski** [comment]
@retronym: could you have a look and determine if we can merge this by tomorrow's end of the day (SF time)?

**Comment by retronym** [comment]
LGTM. It is tricky stuff, but well tested.

**Comment by som-snytt** [comment]
I think @retronym meant, "It is tricky stuff, but, well, tested."  Commas are significant.

The semantics of this code don't pop out as they ought. Unfortunately, you can't test the local defs.  I'm sure that has been said before, but really, if you agitate for local defs, they must be testable like anything else. Note to self.

**Pull request merged**
