### PR TITLE
AbstractFile.getDirectory does not return null when outDir is "."

### PR DESCRIPTION
**Pull request by rjolly**

### CODE REVIEW

**Comment by retronym** [comment]
Can you please tell me how to trigger this with a JSR-233 test? I'm happy to write the test, but I need to know how to set things up.

**Comment by rjolly** [comment]
iirc, you just have to run the script engine from an applet. I don't know if a suitable environment can be set up in the tests. You must have security enabled and signed library files.

**Comment by retronym** [comment]
I can install a custom security manger in a test that will simulate security restrictions for particular file operations; these can be predicated on the path that is looked up, for example.

Here's what I was playing with:

``` scala
import javax.script._, collection.JavaConverters._;

def eval {
  val manager = new ScriptEngineManager
  manager.getEngineByName("scala").eval("0")
}

eval

import java.lang.SecurityManager
import java.security.Permission
import java.io.FilePermission

object NoFileAccess extends SecurityException

object NoFileSystemAccessSecurityManager extends SecurityManager {
  var secure = false
  override def checkPermission(p1: Permission) {
    p1 match {
      case fp: FilePermission =>
        if (fp.toString.contains(".scala_history"))
          ()// ignore
        else {
          println(fp)
          throw NoFileAccess
        }
      case _ =>
    }
  }

  override def checkPermission(p1: Permission, p2: Any) {
    checkPermission(p1)
  }
}
val saved = System.getSecurityManager
System.setSecurityManager(NoFileSystemAccessSecurityManager)
def secure(f: => Any) = {
  NoFileSystemAccessSecurityManager.secure = true
  try f finally NoFileSystemAccessSecurityManager.secure = false
}
secure(eval)
```

But I really need to know which particular file operations to allow, and which to block.

**Comment by rjolly** [comment]
For an applet, basically nothing is allowed except for the few things in $JAVA_HOME/jre/lib/security/java.policy (in the case of the appletviewer).

**Comment by rjolly** [comment]
Jason, I don't think it is possible to test the script engine as long as scala-library.jar is not "listed" (see http://github.com/rjolly/jarlister ). I have discussed doing it in the build process with Adrian, but he prefers waiting for the repl to be modularized (i.e. have its own artifacts etc.) before allowing me to.

**Comment by retronym** [comment]
LGTM.

I would _really_ love some tests around this, but I don't see a straight forward way to get there just yet.

**Pull request merged**
