### PR TITLE
SI-6295: Make DocType take optional ExternalID, as documented.

### PR DESCRIPTION
**Pull request by samskivert**
Deprecates non-optional constructor and adds additional apply method. The
latter allows one to construct DocType("html"), which suffices if one intends
only to support modern web browsers.

Adds a note regarding the incorrect extractor. No mechanism exists to deprecate
or otherwise warn users of the upcoming change which will render use of the
current extractor silently non-functional.

### CODE REVIEW

**Comment by samskivert** [comment]
Hrm. There was an error in the documentation in the first commit. I force pushed a fix in hopes that Github would replace the old commit with the new one in this pull request, but that seems to have not worked.

How does Scala handle changes made to pull requests as a result of review? Do we just tack on new commits and let them all go into trunk when the pull request is merged, cluttering things up? Or should I open new pull requests with an amended commit? Or is there a way to amend the commits in a pull request without causing the old commits to stick around, messing things up?

**Comment by paulp** [comment]
"that seems to have not worked."

Are you sure? It looks like ec7f7852e4 is the commit in the pull request and in your branch. The github web page is confusing after you push --force because it says you "added" a commit, but it actually replaces the old with the new.

**Comment by samskivert** [comment]
Ah, great. Then I did the right thing force pushing the fixed commit over the old one. Everything should be kosher.

**Comment by paulp** [comment]
Sorry to only be commenting on the "content" of the patch now, but - as a rule I hate methods which accept Option[X] parameters.  When tempted, I've never failed to find a better way.  If there is a DocType.NoExternalID, then why is there also an Option[ExternalId]? Usually the reason one creates a "null object" like NoExternalId is to make Option[Foo] unnecessary, you just use Foo or NoExternalId == None.

**Comment by samskivert** [comment]
Well if we're going to do that, the whole business cleans up quite nicely. :) See updated patch.

This also dodges the backward compatibility bullet. If the addition of NoExternalID isn't too burdensome a growth of the public API, then I think this is a slam dunk.

**Comment by paulp** [comment]
Yep, this looks good to me.

**Pull request merged**
