### PR TITLE
Modularize parsing

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by adriaanm** [comment]
this depends on the #2667 (to avoid conflicts in build.xml), will rebase once that's merged

**Comment by adriaanm** [comment]
review by @soc

**Comment by adriaanm** [comment]
I'll also create an eclipse project before merging this PR.

**Comment by soc** [comment]
Looks pretty good to me, although I wonder whether the rest of `src/compiler/scala/tools/cmd/` isn't pretty pointless now ... Wouldn't it make more sense to keep `src/compiler/scala/tools/cmd/Parser.scala` and get rid of `src/compiler/scala/tools/nsc/util/CommandLineParser.scala` instead?

Edit: Having looked into it, I definitely think that the one in `cmd` should be kept. The package is pretty much consistent and self-contained and not some bag of random functionality like `scala.tools.nsc.util`.
In fact, I'm currently cleaning up `scala.tools.partest.nest` to use the functionality of `src.compiler.scala.tools.cmd` and the results look promising. See https://github.com/soc/scala/commit/987c37adac2195893cdd4c3e868c16954c090781.

**Comment by adriaanm** [comment]
Ok, cool. Make sure to also look at what the IDE & SBT are using, if anything. I'll close this PR in the mean time.

**Comment by soc** [comment]
@adriaanm What's your plan? Do you want to push the XML stuff forward first?
I can pick up your parser changes and incorporate them into my partest improvements, if you want.

**Comment by adriaanm** [comment]
Sounds good, thanks. Yeah, I'll do the xml one first. I'm busy with life
this weekend, so it'll have to wait until next week. Also need to
coordinate with SBT and IDE.

**Comment by som-snytt** [comment]
@soc FWIW, a branch using command-line paulptions. 

https://github.com/som-snytt/scala/blob/topic/partest-fast/src/partest/scala/tools/partest/fast/Main.scala

Whenever I see another CLI option lib, I wish paulptions was standalone.

Yes, I just started calling it paulptions a second ago, and now I can't stop.

**Comment by soc** [comment]
Ah nice, yes, that's what I meant.

**Comment by adriaanm** [comment]
@soc, I'm assuming I'll push this to the finish line unless I hear otherwise.

**Comment by soc** [comment]
Yes, sure that would be nice ... my workstation display died today, which has a negative effect on my productivity. There wasn't much left to do anyway, right? Except the `CommandLineParser` thing, it looked pretty good.

**Comment by adriaanm** [comment]
Ok. Hope you get a new/fixed display soon!

**Comment by adriaanm** [comment]
To be clear, I don't plan on reworking partest more than I absolutely have to, so I intend on shipping this PR as-is (modulo addition of the forgotten bnd file). I think the first step should be a minimal rewrite that allows us to cut some cords.

**Comment by soc** [comment]
@adriaanm What I meant was we should just switch our treatment for `Parser` and `CommandLineParser`.
Instead of deleting `Parser` and fixing `CommandLineParser`, apply the fixes to `Parser` and delete `CommandLineParser`.

**Comment by adriaanm** [comment]
Ok, this is ready for re-review, @soc.

/cc @harrah, @huitseeker

**Comment by adriaanm** [comment]
Note that this does not change which jars we build, but it does change some of the internal api in scala.tools.nsc.util

**Comment by harrah** [comment]
LGTM.  sbt doesn't use CommandLine\* that I know of or could find.

**Comment by soc** [comment]
@adriaanm My recommendation is to keep using `Parser` as a name, it will reduce the amount of unrelated changes due to the rename. Additionally, I think it would make sense to move `CommandLine` to `cmd`, too.

Anyway, I'm a bit confused ... everything you need is in `cmd` already, why refactor stuff which has been marked as "obsoleted by `cmd`"?

Nevertheless, let's get this moving.
LGTM, I'll do the remaining cleanup afterwards.

**Comment by adriaanm** [comment]
I wanted to move away from `Parser` since we have one of those and it does a very different thing.
Have to change package names anyway..

Thanks for the prompt reviews guys!

**Comment by adriaanm** [comment]
> Anyway, I'm a bit confused ... everything you need is in cmd already, why refactor stuff which has been marked as "obsoleted by cmd"?

Sorry, I don't follow. The only changes under scala/tools/nsc/util are removals and name changes.

**Pull request merged**
