### PR TITLE
SI-5923 instantiate targs in deferred macro applications 

### PR DESCRIPTION
**Pull request by xeno-by**
Supersedes the incorrect fix to SI-5923, which has been merged into trunk in https://github.com/scala/scala/pull/1844. See https://issues.scala-lang.org/browse/SI-5923 to learn more about the problem, which is now fixed.

Submitting this against 2.10.x, since the fix brings a significant feature on the table, which I wouldn't like to delay until 2.11. For instance, Play could use the fix to completely eliminate serialization boilerplate (http://mandubian.com/2012/11/11/JSON-inception/) /cc @mandubian.

Even though the fix per se doesn't bring binary incompatibilities, it might cause source incompatibilities, namely: materialization macros, whose usages would compile under 2.10.2 wouldn't compile under 2.10.0 and 2.10.1. Not sure whether that's acceptable, but it's definitely worth a try.

Review @paulp @retronym @adriaanm

### CODE REVIEW

**Comment by xeno-by** [comment]
Duh this one is nasty. Previously we masked a type inference / bytecode generation bug (https://issues.scala-lang.org/browse/SI-5353) with a classtag materializer bug (https://issues.scala-lang.org/browse/SI-5923). Now when the latter is fixed, we have to deal with the former :)

**Comment by xeno-by** [comment]
Requires a fix to SI-5353, which was submitted here: https://github.com/scala/scala/pull/2466

**Comment by xeno-by** [comment]
Okay, since the fix for SI-5353 isn't easy and, what's worse, it might have implications on binary compatibility, it'd be tricky to include it into this patch. 

Therefore I suggest we disable the `files/neg/r5353.scala` test and move on. After all, it's not a big deal to temporarily break that specific test, because it's just one of the possible manifestations of array lub unsoundness. If for instance, we say `Array[Nothing]()` instead of just `Array()` in the snippet from the bug report: https://issues.scala-lang.org/browse/SI-5353, then things will blow up in unmodified `2.10.x`.

**Comment by paulp** [comment]
While there is a certain logic to what you say, disabling inconvenient tests is a slippery slope that we've already spent plenty of time sliding around on. And such inconvenience may be my only hope of seeing some of these bugs fixed. So I oppose this suggestion.

**Comment by xeno-by** [comment]
I'm very interested in getting this PR into 2.10.x, but a fix to SI-5353 will probably require 2.11 because of the potential for binary incompatibilities. Otherwise, I'd just wait for a fix to arrive.

Protection against SI-5353 was based on the fact that we couldn't do `Array()`, as that would summon `materializeClassTag[T]` whose expansion would be delayed forever. How about I put a backward compatibility hack, which prohibits `Array()`, maybe even with the same error message?

**Comment by paulp** [comment]
Speaking for myself I would be fine with making Array() a compile time error. I'd be fine with this as a permanent resolution in fact. Array[Nothing] is an extremely problematic construct and the need for it is very low. We need not be slaves to the pursuit of uniformity. Arrays are different.

**Comment by xeno-by** [comment]
Closing for now, though I'm still shooting for 2.10.2.

**Pull request closed without merging**
