### PR TITLE
refines api.FlagSets

### PR DESCRIPTION
**Pull request by xeno-by**
In the current vision of flags, they should only be used to construct trees,
because tests are subsumed by the numerous isXXX methods that we have.

Hence we need to remove `hasFlag` and the flags that don't make sense being
added to tree modifiers manually.

A good example of that is MODULE. There's an isModule check, so hasFlag MODULE
is redundant. On the other hand, you don't need MODULE to construct a ModuleDef
so it's redundant in this department as well.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @adriaanm or @paulp

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
i probably won't have time to review this one, but will look at #1101 asap

**Comment by xeno-by** [comment]
Thank you. Who should I ask for a review of this pull request?

**Comment by adriaanm** [comment]
i'm sure Paul will have an opinion about this :)

**Comment by jsuereth** [comment]
@paulp do you have an opinion? (on this)

**Comment by xeno-by** [comment]
If this helps, we discussed this stuff with Martin yesterday, and he found it reasonable.

**Comment by paulp** [comment]
Hang in there, I'll opine.

**Comment by paulp** [comment]
I am not sure I see the argument for being half-hearted about whether we directly expose flags.  We will suffer about the same if only a few are exposed as if they are all exposed.  At least if we expose them indirectly we can move/change them, something we should do a lot of since many of them could be eliminated and we should be pursuing that.

Most of my observations about flags are not directly related to this pull request so I'll just say this looks fine in a narrow sense.

**Comment by jsuereth** [comment]
I guess this is an endorsement, though not ringing.  I'll merge this then.

**Pull request merged**
