### PR TITLE
SI-5753 macros cannot be loaded when inherited from a class or a trait

### PR DESCRIPTION
**Pull request by martende**
enclClass should be taken from Tree otherwise we can jump to declaration
class/trait.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
Lgtm - it's very nice that the patch is so small and therefore very readable.

Could you please also submit a failing test that was originally in the description of the issue in JIRA?

**Comment by martende** [comment]
hmm what test do you mean ? original ? that produce error ? 
i have submitet 2 tests one with generic and another with just type they are both can not be compiled without a patch 

import scala.reflect.makro.{Context => Ctx}

trait Impls {
  def impl(c: Ctx)(x: c.Expr[Any]) = x
}

import scala.reflect.makro.{Context => Ctx}

object Macros extends Impls {
  def foo(x: Any) = macro impl
}

object Test extends App {
  import Macros._
  println(foo(42))
}

this ? 

where should i pack it

**Comment by xeno-by** [comment]
Yeah this one. Put it into test/files/neg. Take a look at the nearby tests in neg for more details.

**Comment by retronym** [comment]
lgtm

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
