### PR TITLE
SI-3235 Deprecate {Double,Float}#{round,ceil,floor}

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Alternative: Just cherry-pick this commit: https://github.com/soc/scala/commit/603293c068f09398669cf44bddb3d501bb69eecd

**Comment by soc** [comment]
@non Opinions?

**Comment by Ichoran** [comment]
Only round is dangerous; the others will change the type and that will alert you that something unexpected happened.  Cherry-picking the other commit would be good, though.

**Comment by adriaanm** [comment]
Thanks for putting your suggestion into code. I'd like to reach consensus over at #3556, where, as a compromise, I suggested we remove `rint` to get closer to your proposal.

**Pull request closed without merging**
