### PR TITLE
[backport] Fixes implicit `javaBigDecimal2bigDecimal` to return `null`, when a `null` is used by the implicit

### PR DESCRIPTION
**Pull request by guizmaii**
Backports https://github.com/scala/scala/pull/9221 and https://github.com/scala/scala/pull/10593 to Scala 2.12

### CODE REVIEW

**Comment by guizmaii** [comment]
CI seems to be failing because of:
```java
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 15363e3d-e851-408d-a466-719b292a76b8
java.io.IOException: No space left on device
```

**Comment by som-snytt** [comment]
@SethTisue has sufficient magic to restore Jenkins

**Review by som-snytt — APPROVED** [review]
smooth backport

**Review by lrytz — APPROVED** [review]
Invited the new kid to the party.

**Pull request merged**
