### PR TITLE
Fixes scala/bug#11629

### PR DESCRIPTION
**Pull request by Jin-H**
detail : https://github.com/scala/bug/issues/11629

### CODE REVIEW

**Comment by csaltos** [comment]
Thanks Jin !!

**Comment by joshlemer** [comment]
I believe this is a duplicate of https://github.com/scala/scala/pull/8192

**Comment by som-snytt** [comment]
Indeed, closing as duplicate. The edit is an interesting alternative.

As a footnote, I'd be suspicious of tests that change stdout.

**Comment by Jin-H** [comment]
It's really embarrassed that I do duplicating job. I may read existing pr next times and thanks for pointing out it.

**Comment by joshlemer** [comment]
@Jin-H Definitely no need to feel embarrassed 😄

**Comment by Jin-H** [comment]
@joshlemer thanks :smile:

**Pull request closed without merging**
