### PR TITLE
SI-6408: Aligns SIP-15 and compiler implementation

### PR DESCRIPTION
**Pull request by odersky**
I reworked SIP 15 and brought the compiler restrictions inline with it. Review by @harrah @paulp @hubertp

### CODE REVIEW

**Comment by hubertp** [comment]
@odersky, can you please rebase? There are some conflicts.

**Comment by odersky** [comment]
Will rebase and resubmit

**Comment by odersky** [comment]
Rebased. PLS REBUID ALL

**Comment by harrah** [comment]
Compiler crashes on:

``` scala
class X(val i: Int) extends AnyVal {
  class Inner(val q: Int) {
    def plus = i + q
  }
}
```

case classes nested in a universal trait give the error message: `nested object is not allowed in universal trait extending from class Any`.

**Comment by odersky** [comment]
Fixed the crash.

I think the error message "nested object not allowed" is acceptable, because it's clear that case classes generate objects (and there are several other places where we make the same assumption in error messages).  We can special case it, but each such special case increases the size and complexity of the compiler, and therefore decreases its speed. It's a tradeoff, which I will leave to others.

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by harrah** [comment]
These crash the compiler:

1.

``` scala
class X(val s: String) extends AnyVal {
  trait I2 {
   val q: String
   def z = s + q
  }

  def y(x: X) = {
    val i2 = new I2 { val q = x.s }
    i2.z
  }
}
```

2.

``` scala
class X(val s: String) extends AnyVal {
  private[this] class I2(val q: String)

  def y(i: Int) = {
    val i2 = new I2(i.toString)
    i2.q + s
  }
}
```

**Comment by odersky** [comment]
I am leaving to Greg to close this one, once the merge with Jason's restrictions is in place.

**Comment by gkossakowski** [comment]
Yes, I'm on it right now.

**Comment by jsuereth** [comment]
I'm closing this since greg's pull request made it through.

**Pull request closed without merging**
