### PR TITLE
Make implicit divergence checking PolyType aware.

### PR DESCRIPTION
**Pull request by retronym**
Only a two-line patch, but probably needs a more experienced hand
to rework it to ensure:
- it solves this problem completely
- it doesn't risk a cycle in SymCollector

Fixes SI-5318.

Review, when time allows, by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
To elaborate: this patch enables `Implicits#dominates` to find the divergence. It uses the `SymCollector` `freeTypeParametersNoSkolems` to find abstract types in the two candidate implicits, which are stripped and replaced with wildcards.

https://github.com/scala/scala/blob/1f5584fb/src/compiler/scala/tools/nsc/typechecker/Implicits.scala#L349

**Comment by adriaanm** [comment]
So, `SymCollector` is inherited thrice: `typeRefs` is dead code, and now the other two subclasses are diverging.

I think we should push down SymCollector to the two remaining subclasses, inlining their `includeCondition`, get rid of SymCollector, and move `freeTypeParametersNoSkolems` closer to where it's actually used. I think turning the `tp.normalize` into a `tp.dealias` may also remove the need for considering `PolyType`s, as type constructors will stay `TypeRef`s (`normalize` eta-expands them). 

It's a tough call, and I'm not entirely sure, but I think factoring out `SymCollector` is an over-abstraction.

**Comment by adriaanm** [comment]
Alternatively, if changing `normalize` to `dealias` in the super class works, maybe that's a better fix.

**Comment by retronym** [comment]
I'll try out the alternatives; sounds like a good way to learn some more.

**Comment by retronym** [comment]
More discussion on `SymCollector`: https://groups.google.com/d/topic/scala-internals/W027wq_ZBWU/discussion

**Comment by retronym** [comment]
@adriaanm Is this what you had in mind? 

I'll squash and resubmit once we've converged to a acceptable solution.

**Comment by retronym** [comment]
Resubmitted in #620.

**Pull request closed without merging**
