### PR TITLE
Avoid creating the temporary StreamIterator

### PR DESCRIPTION
**Pull request by Atry**
When using list comprehension on TraversableOnce without Iterable or Iterator,
original MonadOps would create a temporary StreamIterator.

My patch avoids that.

### CODE REVIEW

**Comment by paulp** [comment]
Thus lgtm, although it would be nice to lose a few bushels of curly braces and vertical whitespace.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Failures are random build aborts yet again. @jsuereth if this can't be fixed we should abandon jenkins.

**Comment by jsuereth** [comment]
PLS REBUILD ALL

@paulp if you can give us a viable alternative, I'm all ears.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
...one of the "hidden" costs of frequent failure is that we all tend to be slow to recognize real failure. The failing test is test/files/run/t4582.scala, which asserts that "it" in the following expression is never evaluated:

```
(Iterator(Iterator(1)) ++ Iterator(it)).flatten
```

**Comment by paulp** [comment]
Closing this pending failure resolution.

**Pull request closed without merging**
