### PR TITLE
SI-8657 don't miss tailrec defs in more positions

### PR DESCRIPTION
**Pull request by jrudolph**
1) First operand of boolean expression using `&&` or `||`. Second operands of
   those boolean exprs were already treated specially here but handling for first
   operands was missing.
2) Condition of `If`.

This may be a candidate for backporting as well.

### CODE REVIEW

**Comment by retronym** [comment]
I also spotted that we don't look inside pattern guards:

``` scala
        case CaseDef(pat, guard, body) =>
          deriveCaseDef(tree)(transform)
```

Can you also add (or ensure existence) of a test for:

``` scala
import annotation._

object Tail {
  def foo {
    () => {
      @tailrec def foo: Int = foo + 1
    }
  }
}
```

This currently works (ie, it descends into the function body and reports the error), but if we let `Function` nodes with non-trivial bodies persist after `Uncurry` it might stop working.

**Comment by retronym** [comment]
I think this change makes sense for 2.11.x, it is easier to directly target that branch than to start here and backport.

**Comment by jrudolph** [comment]
Ok, will adapt.

**Comment by jrudolph** [comment]
> I also spotted that we don't look inside pattern guards

I don't know how to trigger this case. It seems that guards at this point have already been moved inside the rhs of the CaseDef. Are there situations where this would not be the case?

**Comment by retronym** [comment]
The patmat phase leaves `CaseDef`s in exception handlers.

``` scala
object Test {
  try {
    ???
  } catch {
    case _: RuntimeException if { @annotation.tailrec def foo: Int = {foo + 1}; "".isEmpty } =>
  }
}
```

**Comment by jrudolph** [comment]
> The patmat phase leaves CaseDefs in exception handlers.

That's not what I am seeing. Instead, this becomes just a case of a tailrec def inside the if-condition which is already fixed.

Maybe I just add an assertion and a comment to be sure it isn't overlooked if pattern matching is changed in the future:

``` scala
        case CaseDef(pat, guard, body) =>
          assert(guard.isEmpty)
          deriveCaseDef(tree)(transform)
```

**Comment by jrudolph** [comment]
I'm gonna reopen this PR based on 2.11.x.

**Comment by retronym** [comment]
Oh you're right. Sort of funny that it maps onto the case you've just fixed!

For the record, `CaseDef`-s in catches can last beyond the `patmat` phase if all cases are simple type tests.

+1 for the assertion.

**Comment by jrudolph** [comment]
> Sort of funny that it maps onto the case you've just fixed!

Yes, it also took me half an hour to realize why your test case didn't fail for me any more :)

**Comment by viktorklang** [comment]
:+1: :)

**Pull request closed without merging**
