### PR TITLE
Partition options by function: -V verbose, -W warnings, preserving current aliases

### PR DESCRIPTION
**Pull request by eed3si9n**
Especially notable changes include:
* `-Werror` is recommended over `-Xfatal-warnings`

Breaking changes include:
* `-Xprint:all` is no longer accepted; use `-Vprint:_`
* `-warn-option` is no longer accepted; use `-Woption`

This is a rebase of #7686

### CODE REVIEW

**Comment by SethTisue** [comment]
@som-snytt would you mind editing the PR title and description to indicate that more options are affected than just `-warn-option`? then I'll make a corresponding change in the 2.13.0 release notes

**Comment by som-snytt** [comment]
@SethTisue you mean like the "and friends" part of "Werror and friends"? I thought maybe the show would go into syndication as "Werror and friends."

**Comment by som-snytt** [comment]
I still think it would be so cool to have `-Z` options. I understand the need to save something for future expansion.

**Comment by martijnhoekstra** [comment]
-Zzz to passive agressively blame the compilet for allowing what it
shouldn't.

**Comment by SethTisue** [comment]
I've added some bullets to the PR description with some specific changes I personally have found especially notable. We can add more.

**Pull request merged**
