### PR TITLE
SI-7406 crasher with specialized lazy val

### PR DESCRIPTION
**Pull request by paulp**
This reverts a tiny bit of f7d5f45aa7 where the crasher was introduced. The
enclosed test case compiles and runs under 2.9, but prints the wrong answer.
It crashes in 2.10 and until this patch. Now it compiles and prints the right
answer.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @vladureche

**Comment by VladUreche** [comment]
Thanks for the patch Paul! LGTM, I played around a bit and it works well.

Now, what I don't understand is why the generic accessor is okay to be lazy, but not its specialized overload:

``` scala
  class Arne[@specialized(scala.Long) T >: Nothing <: Any] extends Object {
   ...
    lazy protected[this] var lazyVal: T = _;
    <stable> <accessor> lazy def lazyVal(): T = {
      Arne.this.lazyVal = Arne.this.x;
      Arne.this.lazyVal
    };
    <stable> <accessor> <specialized> **removed lazy** def lazyVal$mcJ$sp(): Long = Arne.this.lazyVal().asInstanceOf[Long]();
   ...
  };

  <specialized> class Arne$mcJ$sp extends Arne[Long] {
    ...
    override <stable> <accessor> lazy <specialized> def lazyVal(): Long = Arne$mcJ$sp.this.lazyVal$mcJ$sp();
    override <stable> <accessor> <specialized> **removed lazy** def lazyVal$mcJ$sp(): Long = {
      Arne$mcJ$sp.this.lazyVal = Arne$mcJ$sp.this.x$mcJ$sp;
      Arne$mcJ$sp.this.lazyVal
    };
    ...
  }
}

```

The pre-patch error message doesn't help much:

``` scala
[log mixin(->cleanup)] cast(Arne$mcI$sp#25394.this, Int#302.type): Arne$mcI$sp#25394.this.$asInstanceOf#5280[Int#302.type]()
[log mixin(->cleanup)] adapting Arne$mcI$sp#25394.this.$asInstanceOf#5280[Int#302.type]().unbox#7855:(<param> x#29637: Object#1739)Int#300 : List() to Int#300
[log mixin(->cleanup)] [context] ++ NoCompilationUnit / Apply(method unbox#7855)
[log mixin(->cleanup)] adapting Arne$mcI$sp#25394.this.$asInstanceOf#5280[Int#302.type]().unbox#7855:(<param> x#29637: Object#1739)Int#300 : List() to Object#1739
[log mixin(->cleanup)] casting Arne$mcI$sp#25394.this.$asInstanceOf#5280[Int#302.type]().unbox#7855:(<param> x#29637: Object#1739)Int#300 to Object#1739 at phase: cleanup
error: uncaught exception during compilation: java.lang.AssertionError
error: java.lang.AssertionError: assertion failed: 
     while compiling: xxx.scala
        during phase: global=mixin, atPhase=cleanup
     library version: version 2.10.4-20131212-114029-5cbb5a7f62
    compiler version: version 2.10.4-20131218-233119-d57ea36d2a
  reconstructed args: -Xprint:flatten -Xprint:spec -Ydebug -Ylog:mixin -uniqid

  last tree to typer: TypeTree(module class Int#302)
              symbol: module class Int#302 in package scala#23 (flags: <module>)
   symbol definition: <module> class Int#302 extends AnyValCompanion#1491
                 tpe: Int#302.type
       symbol owners: module class Int#302 -> package scala#23
      context owners: method lazyVal$mcI$sp$lzycompute#29700 -> class Arne$mcI$sp#25394 -> package <empty>#3

== Enclosing template or block ==

Apply( // <method> <triedcooking> def unbox#7855(<param> x#29637: Object#1739): Int#300 in module class Int#302
  "unbox" // <method> <triedcooking> def unbox#7855(<param> x#29637: Object#1739): Int#300 in module class Int#302, tree.tpe=(<param> x#29637: Object#1739)Int#300
  Arne$mcI$sp#25394.this.$asInstanceOf#5280[Int#302.type]()."unbox" // <method> <triedcooking> def unbox#7855(<param> x#29637: Object#1739): Int#300 in module class Int#302, tree.tpe=(<param> x#29637: Object#1739)Int#300
)

== Expanded type of tree ==
...

== Current unit body ==
...

Arne$mcI$sp#25394.this.$asInstanceOf#5280[Int#302.type]().unbox#7855
    at scala.Predef$.assert(Predef.scala:179)
    at scala.tools.nsc.Global.assert(Global.scala:239)
    at scala.tools.nsc.ast.TreeGen.mkCast(TreeGen.scala:249)
    at scala.tools.nsc.Global$gen$.mkAttributedCast(Global.scala:105)
    at scala.tools.nsc.transform.Erasure$Eraser.cast(Erasure.scala:678)
    at scala.tools.nsc.transform.Erasure$Eraser.scala$tools$nsc$transform$Erasure$Eraser$$adaptToType(Erasure.scala:707)
    at scala.tools.nsc.transform.Erasure$Eraser.adapt(Erasure.scala:816)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5637)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer.withCondConstrTyper(Typers.scala:498)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer.loop$1(Typers.scala:3069)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArgs(Typers.scala:3074)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$handleMonomorphicCall$1(Typers.scala:3331)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$doTypedApply$2.apply(Typers.scala:3376)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$doTypedApply$2.apply(Typers.scala:3376)
    at scala.tools.nsc.typechecker.TypeDiagnostics$TyperDiagnostics$checkDead$.updateExpr(TypeDiagnostics.scala:462)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3375)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4604)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4636)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5541)
    at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:835)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5619)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5681)
    at scala.tools.nsc.typechecker.Typers$Typer.typedPos(Typers.scala:5686)
    at scala.tools.nsc.transform.Erasure$Eraser.unbox1(Erasure.scala:662)
    at scala.tools.nsc.transform.Erasure$Eraser.scala$tools$nsc$transform$Erasure$Eraser$$unbox(Erasure.scala:610)
    at scala.tools.nsc.transform.Erasure$Eraser.scala$tools$nsc$transform$Erasure$Eraser$$adaptToType(Erasure.scala:705)
    at scala.tools.nsc.transform.Erasure$Eraser.adapt(Erasure.scala:816)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5637)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2433)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5547)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5547)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:507)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
    at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:835)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5619)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5822)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2257)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
    at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:835)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5619)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5681)
    at scala.tools.nsc.typechecker.Typers$Typer.typedPos(Typers.scala:5686)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.scala$tools$nsc$transform$Mixin$MixinTransformer$$typedPos(Mixin.scala:483)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.attributedDef$1(Mixin.scala:653)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.scala$tools$nsc$transform$Mixin$MixinTransformer$$addDef$1(Mixin.scala:664)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.mkSlowPathDef$1(Mixin.scala:785)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.mkFastPathBody$1(Mixin.scala:796)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.mkFastPathLazyBody$1(Mixin.scala:791)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.scala$tools$nsc$transform$Mixin$MixinTransformer$$mkLazyDef$1(Mixin.scala:863)
    at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$scala$tools$nsc$transform$Mixin$MixinTransformer$$dd$1$2.apply(Mixin.scala:908)
    at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$scala$tools$nsc$transform$Mixin$MixinTransformer$$dd$1$2.apply(Mixin.scala:904)
    at scala.reflect.internal.Trees$class.deriveDefDef(Trees.scala:1598)
    at scala.reflect.internal.SymbolTable.deriveDefDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.scala$tools$nsc$transform$Mixin$MixinTransformer$$dd$1(Mixin.scala:904)
    at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$addCheckedGetters$1$1.apply(Mixin.scala:946)
    at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$addCheckedGetters$1$1.apply(Mixin.scala:945)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.addCheckedGetters$1(Mixin.scala:945)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.addNewDefs(Mixin.scala:1013)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.scala$tools$nsc$transform$Mixin$MixinTransformer$$postTransform(Mixin.scala:1147)
    at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$transform$1.apply(Mixin.scala:1261)
    at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$transform$1.apply(Mixin.scala:1261)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at scala.tools.nsc.Global.afterMixin(Global.scala:1103)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1261)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:471)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1258)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:471)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1297)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1258)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:471)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)
```

Do you have any insight? If not, I can also debug it myself and add the conclusion to the thread.

**Comment by paulp** [comment]
I don't have a clue really. I created this patch because I saw I had pinpointed the regression commit and it wasn't a large one, so it was relatively quick to isolate.

**Comment by VladUreche** [comment]
Still, let's merge it, since it does the job, and I'll come back to it when I get to https://github.com/miniboxing/miniboxing-plugin/issues/59.

**Comment by VladUreche** [comment]
Thanks @paulp and @retronym!

**Pull request merged**
