### PR TITLE
SI-9557 Backquoted id spec

### PR DESCRIPTION
**Pull request by som-snytt**

### CODE REVIEW

**Comment by aryairani** [comment]
Where are `charNoBackQuoteOrNewline`, `UnicodeEscape`, `charEscapeSeq` defined?

**Comment by som-snytt** [comment]
@refried They are informal (but not imprecise) with certain descriptive terminals, see multiLineChars:

https://github.com/scala/scala/blame/2.12.x/spec/13-syntax-summary.md#L67

Anyone sufficiently motivated ought to be able to track down:

https://github.com/scala/scala/blame/2.12.x/spec/13-syntax-summary.md#L14

https://github.com/scala/scala/blame/2.12.x/spec/13-syntax-summary.md#L33

**Comment by lrytz** [comment]
It seems a backquoted identifier can contain a non-escaped double quote:

```
scala> val `/"\\` = "Eyjafjallajökull"
/"\: String = Eyjafjallajökull
```

IUC, the proposed spec would not allow this.

**Comment by som-snytt** [comment]
@refried Actually, there is another ticket where defining all productions precisely in the spec text is requested.

@lrytz I'm not sure where double quote is outlawed here. But is Eyjafjallajökull that volcano in Iceland? oh nm, I googled it. I wasn't sure if it meant Icelandic yokel.

**Comment by lrytz** [comment]
I thought that, because `stringLiteral ::= ‘"’ {stringElement} ‘"’`, `stringElement` cannot contain `"`. This PR inlines `stringElement`.

**Comment by SethTisue** [comment]
@som-snytt rebase?

**Comment by som-snytt** [comment]
Maybe the folks doing the spec tweaks want to formalize things like multilineChars and others mentioned; and also there's a populist movement to put all syntax productions in the main text.

**Comment by SethTisue** [comment]
@som-snytt rebase?

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
