### PR TITLE
Don't evaluate devWarning conditions unless under -Xdev [resubmission]

### PR DESCRIPTION
**Pull request by adriaanm**
Resubmission of #7174, rebased and without the last (experimental) commit. 

The original description:

The shape of `devWarningIf` is such that the inliner produces bytecode
similar to

```scala
if (global.isDeveloper) {
  if (condition) {
    devWarning(() => msg)
  }
}
```

so that the closure allocation and the condition evaluation are both guarded by the `isDeveloper` check. (This does mean that the bytecode for the condition gets emitted into the containing method; it could be tweaked so it gets pushed into a closure as well.)

Several of these `devWarning` conditions were based on list traversals or other non-constant-time conditions, so this should speed that up a bit. No benchmarks while I'm travelling; I'll see what I can do tonight.

### CODE REVIEW

**Comment by adriaanm** [comment]
The travis failure was a network issue, it passed on jenkins

**Comment by adriaanm** [comment]
Merging this to book progress, happy to consider followups (though perhaps on 2.13?)

**Comment by hrhino** [comment]
Thank you!

**Comment by som-snytt** [comment]
Way to flatten the cake. Is pancake a pattern? Also, why isn't there `isSoftwareEngineer`? Under `isDeveloper`, emit useful advice, under `isSoftwareEngineer`, emit obscure links to the documentation. Someone could spend a day "consulting" the docs; oh, is that why they're called consultants?

**Pull request merged**
