### PR TITLE
Statistics reorganization

### PR DESCRIPTION
**Pull request by odersky**
Statistics were broken since the move to reflect.internal. They are now
re-organized, made more robost and modular.

Review by @lrytz, @adriaanm

### CODE REVIEW

**Comment by lrytz** [comment]
it might be worthwhile to allocate all the counters only if `-Ystatistics` is enabled - what do you think?

**Comment by odersky** [comment]
On Wed, Jun 13, 2012 at 2:26 AM, Lukas Rytz <
reply@reply.github.com

> wrote:
> 
> it might be worthwhile to allocate all the counters only if `-Ystatistics`
> is enabled - what do you think?
> 
> There are not that many, only 200 run-objects or so. But it's a
> possibility. But before I have to figure out why the build is failing.

Cheers
- Martin

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/scala/scala/pull/703#issuecomment-6289357

## 

Martin Odersky
Prof., EPFL http://www.epfl.ch and Chairman, Typesafehttp://www.typesafe.com
PSED, 1015 Lausanne, Switzerland
Tel. EPFL: +41 21 693 6863
Tel. Typesafe: +41 21 691 4967

**Comment by jsuereth** [comment]
[partest] Exception in thread "Timer-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
Build timed out (after 240 minutes). Marking the build as failed.

Think this is transient and we should try again?

**Comment by adriaanm** [comment]
I checked and nothing else was running on chara at that time (at least according to jenkins).
Retrying is cheap, of course: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/275/

**Comment by adriaanm** [comment]
Build failed in the same way, unfortunately.

**Comment by jsuereth** [comment]
Ok, I'm closing this one as broken then.   We'll have to take a look at what's causing the OOM thne.

**Pull request closed without merging**
