### PR TITLE
SI-5189 detect unsoundness when inferring type of match

### PR DESCRIPTION
**Pull request by adriaanm**
GADT skolems encode type slack that results from pattern matching on variant type constructors
I thought they would not longer be relevant after cases have been typed,
and since they caused weird issues with the old pattern matcher, I deskolemized in typedCase

however, when we don't have an expected type for the match, we need to keep the skolems around
until the skolemized type makes it out of the match and it becomes the result of type inference for that match
when you do have an expected type, it will propagate to the case-level and the confrontation will thus
already take place when typing individual cases

review by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
I think it would be wonderful if you discovered the period. This little-known bit of punctuation has been one of the best kept secrets of sages and scribes for millennia. Now, for a limited time, the secrets of the period can be yours for only $29.99. Once you have experienced the startling lucidity which accompanies what some people call "sentence delimiters", you may never again feel whitespace is sufficient for all your word-bounding needs.

**Comment by som-snytt** [comment]
I, for one, am, naturally, quite thankful for the advent of whitespace delimiters; that would suffice for me if, in fact, semi-colon inference inferred that last semi.

http://en.wikipedia.org/wiki/File:P46.jpg

**Comment by paulp** [comment]
Oh but other than the period thing, looks good to me.

**Comment by adriaanm** [comment]
I will try to watch my period in the future.

**Pull request merged**
