### PR TITLE
Wonderfulizing isSameType

### PR DESCRIPTION
**Pull request by paulp**
Review by @adriaanm.

### CODE REVIEW

**Comment by adriaanm** [comment]
PLS REBUILD/pr-checkin-per-commit@470a918

**Comment by adriaanm** [comment]
the bot diligently notified of succes: https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/1461/, just at the shorter sha

**Comment by paulp** [comment]
I spurn the bot's flailing and pushed three new commits to fix the spelling mistake caught by diligent reviewer.

**Comment by retronym** [comment]
I was curious about the now-failing test, so I took a look at the difference. Code to do so is here: https://github.com/retronym/scala/commit/0814c238e

The new implementation hits `registerTypeEquality`, the old doesn't. `BoundedWildcardType` is at play. That's as far as I have dug for now.

```
[log typer] isSameTypeNew(mutable.this.Map[<empty>.this.bar, mutable.this.Set[<empty>.this.bar]], ?scala.reflect.internal.Types$BoundedWildcardType?): false
[log typer] isSameTypeOld(mutable.this.Map[<empty>.this.bar, mutable.this.Set[<empty>.this.bar]], ?scala.reflect.internal.Types$BoundedWildcardType?): false
regTypeEq: (?A,?scala.reflect.internal.Types$BoundedWildcardType?,class scala.reflect.internal.Types$BoundedWildcardType,in LHS,)
[log typer] isSameTypeNew(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
[log typer] isSameTypeOld(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
--
[log typer] isSameTypeNew(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
[log typer] isSameTypeOld(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
regTypeEq: (?B,?scala.reflect.internal.Types$BoundedWildcardType?,class scala.reflect.internal.Types$BoundedWildcardType,in LHS,)
[log typer] isSameTypeNew(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
[log typer] isSameTypeOld(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
--
[log typer] isSameTypeNew(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
[log typer] isSameTypeOld(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
regTypeEq: (?A,?scala.reflect.internal.Types$BoundedWildcardType?,class scala.reflect.internal.Types$BoundedWildcardType,in LHS,)
[log typer] isSameTypeNew(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
[log typer] isSameTypeOld(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
--
[log typer] isSameTypeNew(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
[log typer] isSameTypeOld(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
regTypeEq: (?B,?scala.reflect.internal.Types$BoundedWildcardType?,class scala.reflect.internal.Types$BoundedWildcardType,in LHS,)
[log typer] isSameTypeNew(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
[log typer] isSameTypeOld(=??<none>, ?scala.reflect.internal.Types$BoundedWildcardType?): true
```

**Comment by paulp** [comment]
@retronym It used to instantly return when it encountered a BoundedWildcardType, whatever the result of the containsType call. I changed that and other things such that the search continues until either something says "yes, these are the same type" or it runs out of avenues of investigation. This must have led to something relevant happening after the first sighting of a BoundedWildcardType, where it formerly returned early. I imagine my way (correctly) picks up another constraint, rendering the implicit conversion unsuitable.

**Comment by adriaanm** [comment]
LWTM

**Pull request merged**
