### PR TITLE
Fix several tests under GenBCode

### PR DESCRIPTION
**Pull request by lrytz**
- private-inline, t8601-closure-elim, inline-in-constructors
  - test closure inlining / elimination, which is not yet implemented
    in GenBCode. noted in https://github.com/scala-opt/scala/issues/14.
- constant-optimization, t7006
  - no constant folding in GenBCode yet.
    noted in https://github.com/scala-opt/scala/issues/29.
- patmat_opt_ignore_underscore, patmat_opt_no_nullcheck, patmat_opt_primitive_typetest
  - not all optimizations in GenBCode yet.
    noted in https://github.com/scala-opt/scala/issues/30.
- t3234
  - tests a warning of trait inlining - trait inlining works in
    GenBCode
- synchronized
  - ignore inliner warnings (they changed a bit)
- t6102
  - account for the changed outputo of -Ydebug has under GenBCode

### CODE REVIEW

**Comment by lrytz** [comment]
review by @retronym

**Comment by lrytz** [comment]
Added the second commit from https://github.com/scala/scala/pull/4505/commits

**Comment by retronym** [comment]
LGTM

**Comment by lrytz** [comment]
need to fix `innerClassAttribute` under `-Ydelambdafy:method`

**Comment by lrytz** [comment]
fixed now, had to [make a name logner](https://github.com/scala/scala/commit/2be2c0d9866352286470e74a9bd878cbe3b37222#diff-82c1450b05b0a1a593bf50ff400943b7L536) while https://github.com/scala/scala/pull/4505 is not yet in.

**Pull request merged**
