### PR TITLE
SI-7488 REPL javap finds new style delayedEndpoint

### PR DESCRIPTION
**Pull request by som-snytt**
The REPL :java -app command is a convenience to locate
the body of DelayedInit code.  Now it will look for
new style delayedEndpoints on the class before it
falls back to showing the apply method of the
delayedInit$body closure.

```
apm@mara:~/tmp$ skala
Welcome to Scala version 2.11.0-20130711-153246-eb1c3137f5 (OpenJDK 64-Bit Server VM, Java 1.7.0_21).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :javap -pv -app delayed.C
  public final void delayedEndpoint$delayed$C$1();
    flags: ACC_PUBLIC, ACC_FINAL
    Code:
      stack=2, locals=1, args_size=1
         0: getstatic     #29                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
         3: ldc           #31                 // String this is the initialization code of C
         5: invokevirtual #35                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
         8: return
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
               0       9     0  this   Ldelayed/C;
      LineNumberTable:
        line 11: 0

scala> :q
apm@mara:~/tmp$ rm delayed/*.class
apm@mara:~/tmp$ scalac delayed.scala
apm@mara:~/tmp$ skala
Welcome to Scala version 2.11.0-20130711-153246-eb1c3137f5 (OpenJDK 64-Bit Server VM, Java 1.7.0_21).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :javap -pv -app delayed.C
  public final java.lang.Object apply();
    flags: ACC_PUBLIC, ACC_FINAL
    Code:
      stack=2, locals=1, args_size=1
         0: getstatic     #13                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
         3: ldc           #15                 // String this is the initialization code of C
         5: invokevirtual #19                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
         8: getstatic     #25                 // Field scala/runtime/BoxedUnit.UNIT:Lscala/runtime/BoxedUnit;
        11: areturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
               0      12     0  this   Ldelayed/C$delayedInit$body;
      LineNumberTable:
        line 11: 0
        line 10: 8
```

Review by @paulp because he has that app on his phone for approving and merging repl changes.  Also, because I use PartialFunction.cond.  Remember that recent not-a-bug where someone didn't know where their DelayedInit code went?  The people need this.

### CODE REVIEW

**Comment by som-snytt** [comment]
The test must be updated to succeed under java 6.

**Comment by som-snytt** [comment]
Thanks to Jenkins and the Kitteh, I just spliced the diff from the failure into the check file and it worked the first time.

I took a moment to contemplate what a weird brave new world this is.

**Comment by adriaanm** [comment]
We're PRing in the future, I'm telling you!

**Comment by som-snytt** [comment]
@adriaanm  The dose of reality is that I can't test the feature against 2.10 scalac -- at least not until partest is spun off and partest's fanatical base in the community starts contributing.

**Comment by som-snytt** [comment]
Hey, I just posted an answer on SO that used this feature.  Thanks, guys, for fixing it!

http://stackoverflow.com/a/17691572/1296806

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
