### PR TITLE
Add JUnit support

### PR DESCRIPTION
**Pull request by gkossakowski**
As discussed on [scala-internals](https://groups.google.com/d/msg/scala-internals/qPbD5d15kvA/p0Nn2-YKvtkJ) adding JUnit support is probably a good idea. We write unit tests in partest which wasn't designed for that.

This PR adds a basic infrastructure for running JUnit tests:
- an Ant task `test.junit` that runs all JUnit tests defined in `test/junit` directory
- an Eclipse project definitions that allows us one to import all the tests to Eclipse

There will be a follow up PR for master which merges this PR and migrates WeakHashMap test to be a junit test.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @JamesIry.

**Comment by som-snytt** [comment]
Does using ScalaTest make the team liable for supporting it?  Sorry it didn't come up more specifically on the ML.

**Comment by gkossakowski** [comment]
@som-snytt: it's a bootstrapping problem. Scalatest is fairly big Scala library with additional Scala dependencies. We don't want to risk a situation that Scalatest doesn't build for whatever reason (e.g. regression in compiler) and we cannot run our tests anymore.

Also, it seems like JUnit is good enough for us for now.

**Comment by paulp** [comment]
scalacheck has been a huge burden, and it has NO dependencies. I can't even imagine scalatest, something I've rarely been able to build under the best of circumstances.

**Comment by JamesIry** [comment]
LGTM and can't wait to use it

**Pull request merged**
