### PR TITLE
Repairs unexpected failure of test t6200.scala

### PR DESCRIPTION
**Pull request by Ichoran**
Added extra ()'s to get rid of deprecation warning for inferring unit arg.

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks for fixing this. We normally don't merge PRs until the build bot gives the green light, though.

**Comment by Ichoran** [comment]
Given that everyone's going to get yelled at by the build bot until this goes through, it seemed like merging was the lesser of two evils.  The worst that could happen is that everyone still gets yelled at.

**Comment by som-snytt** [comment]
Just for fun, `1 -> {}` works.  It may be too eccentric to become scala style.

**Comment by adriaanm** [comment]
Sure, but commits are forever -- like diamonds. Would rather not have (potentially) rough ones sitting in our history.

**Comment by Ichoran** [comment]
Fair enough.  I'll at least let you make the call in the future.

**Pull request merged**
