### PR TITLE
SI-7102 Override isEmpty for bitsets with an efficient implementation 

### PR DESCRIPTION
**Pull request by vigdorchik**
rather than use default checking for size == 0.

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @JamesIry.

**Comment by JamesIry** [comment]
Looks good but I'd rather see commit messages along the lines of

---

SI-7102 Give bitsets an efficient isEmpty method

Bitsets currently use the default "size == 0" implementation of
isEmpty, which isn't very efficient. This commit overrides the 
isEmptyMethod on BitsetLike to compare each word in the bitset

## to 0, avoiding the need to look at individual bits.

Or something to that effect. I know that seems redundant since the change is pretty obvious. But somebody reading through git logs to track down an issue doesn't want to jump in to look at each code change.

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
