### PR TITLE
SI-8815  mutable.LongMap makes different choices for splitAt vs etc.

### PR DESCRIPTION
**Pull request by Ichoran**
It turns out that take/drop/splitAt/takeWhile/dropWhile inherit a smattering of foreach vs. iterator-based implementations.  These aren't consistent unless they iterate in the same order.  This probably reflects an undesirable underlying weakness, but in this particular case it was easy to make LongMap's foreach order agree with iterator.

Made traversal order of other foreach-like methods match also.

Also fixed a bug where Long.MinValue wasn't iterated.

### CODE REVIEW

**Comment by lrytz** [comment]
I think we should add some unit tests for these fixes. Or do we rely on the upcoming test generator?

**Comment by gkossakowski** [comment]
ping @Ichoran

**Comment by Ichoran** [comment]
@lrytz @gkossakowski - I was not going to bother with extra unit tests because the collections test generator catches these (that's how I found them in the first place).  In fact, once the test generator is in place I'd like to rip out a bunch of unit tests that are no longer necessary to speed up the tests.  Maybe I should add a test for Long.MinValue, though--that isn't part of the testing.

**Comment by Ichoran** [comment]
@lrytz @gkossakowski - I added a unit test to test potentially special values.

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
