### PR TITLE
The new reflection

### PR DESCRIPTION
**Pull request by xeno-by**
Highlights:
- Architecture has undergone a dramatic rehash.
- Universes and mirrors are now separate entities:
  universes host reflection artifacts (trees, symbols, types, etc),
  mirrors abstract loading of those artifacts (e.g. JavaMirror loads stuff
  using a classloader and annotation unpickler, while GlobalMirror uses
  internal compiler classreader to achieve the same goal).
- No static reflection mirror is imposed on the user.
  One is free to choose between lightweight mirrors and full-blown
  classloader-based mirror (read below).
- Public reflection API is split into scala.reflect.base and scala.reflect.api.
  The former represents a minimalistic snapshot that is exactly enough to
  build reified trees and types. To build, but not to analyze - everything smart
  (for example, getting a type signature) is implemented in scala.reflect.api.
- Both reflection domains have their own universe: scala.reflect.basis and
  scala.reflect.runtime.universe. The former is super lightweight and doesn't
  involve any classloaders, while the latter represents a stripped down compiler.
- Classloader problems from 2.10.0-M3 are solved.
- Exprs and type tags are now bound to a mirror upon creation.
- However there is an easy way to migrate exprs and type tags between mirrors
  and even between universes.
- This means that no classloader is imposed on the user of type tags and exprs.
  If one doesn't like a classloader that's there (associated with tag's mirror),
  one can create a custom mirror and migrate the tag or the expr to it.
- There is a shortcut that works in most cases. Requesting a type tag from
  a full-blown universe will create that tag in a mirror that corresponds to
  the callsite classloader aka `getClass.getClassLoader`. This imposes no
  obligations on the programmer, since Type construction is lazy, so one
  can always migrate a tag into a different mirror.

Migration notes for 2.10.0-M3 users:
- Incantations in Predef are gone, some of them have moved to scala.reflect.
- Everything path-dependent requires implicit prefix (for example, to refer
  to a type tag, you need to explicitly specify the universe it belongs to,
  e.g. reflect.basis.TypeTag or reflect.runtime.universe.TypeTag).
- Some of the functions have been renamed or moved around.
  The rule of thumb is to look for anything non-trivial in scala.reflect.api.
  Some of tree build utils have been moved to Universe.build.
- staticModule and staticClass have been moved from universes to mirrors
- ClassTag.erasure => ClassTag.runtimeClass
- For the sake of purity, type tags no longer have erasures.
  Use multiple context bounds (e.g. def foo[T: ru.TypeTag : ClassTag](...) = ...)
  if you're interested in having both erasures and types for type parameters.
- reify now rolls back macro applications.
- Runtime evaluation is now explicit, requires import scala.tools.reflect.Eval
  and scala-compiler.jar on the classpath.
- Macro context now has separate universe and mirror fields.
- Most of the useful stuff is declared in c.universe,
  so be sure to change your "import c.universe._" to "import c.mirror._".
- Due to the changes in expressions and type tags, their regular factories
  are now really difficult to use. We acknowledge that macro users need to
  frequently create exprs and tags, so we added old-style factories to context.
  Bottom line: almost always prepend Expr(...)/TypeTag(...) with "c.".
- Expr.eval has been renamed to Expr.splice.
- Expr.value no longer splices (it can still be used to express cross-stage
  path-dependent types as specified in SIP-16).
- c.reifyTree now has a mirror parameter that lets one customize the initial
  mirror the resulting Expr will be bound to. If you provide EmptyTree, then
  the reifier will automatically pick a reasonable mirror (callsite classloader
  mirror for a full-blown universe and rootMirror for a basis universe).
  Bottom line: this parameter should be EmptyTree in 99% of cases.
- c.reifyErasure => c.reifyRuntimeClass.

Future work:
- Today/tomorrow I will move scala.reflect.api, scala.reflect.internal,
  scala.reflect.runtime and scala.reflect.makro into scala-reflect.jar.
  This is a new jar in Scala distribution and a new artifact in Maven.

Known issues:
- API is really raw, need your feedback.
- All reflection artifacts are now represented by abstract types.
  This means that pattern matching against them will emit unchecked warnings.
  Adriaan is working on a patch that will fix that.
- There is a noticeable performance degradation. We're working on fixing it.

### CODE REVIEW

**Comment by xeno-by** [comment]
Fixed the failing presentation compiler test, launched another Jenkins session: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/56/console.

**Comment by adriaanm** [comment]
"935 changed files with 14,320 additions and 9,749 deletions."

I'm sorry, but we really have to find a way to split this up into more manageable commits.

**Comment by adriaanm** [comment]
btw, you should be able to trigger the buildbot here: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/build?delay=0sec

simply enter the pull request number and the branch to merge it into ("master")

**Comment by xeno-by** [comment]
Speaking of manageable commits, I've spent several hours merging against the month of commits in trunk. Splitting the blob into several commits, hmmm, that's even more time. I'd better do performance testing, to be honest. What would you advice in this situation?

Also, I'm not sure how easy it will be to factor our meaningful, individually sound commits from the blob. The scope of the change is huge, and everything is interconnected.

upd. Well, this one can be definitely factored out: https://github.com/scalamacros/kepler/commit/0c7d5eb864d1b9ce7c9618291508f776780f3656, but I'm not sure how useful that would be. Also, take into account that a lot of changes (I'd guess, about 60-80%) are tests.

**Comment by harrah** [comment]
> we really have to find a way to split this up into more manageable commits.

Having tried to review just the parts related to the class loader changes, I would find this useful.

**Comment by adriaanm** [comment]
Having multiple commits will make performance testing easier as well.
In fact, it will make everything easier.

I'm going to insist it's well worth the time spent -- you've worked so hard on this,
now make it count. It's like a top chef who spends a day in the kitchen and
then just slaps everything onto one big plate and sends it to the table.

**Comment by xeno-by** [comment]
Performance testing can be done with bisect on a scratchpad branch Martin and I used this month, so this is not an issue.

But anyways I find your arguments reasonable. I'll try to do what you ask (after fixing the performance), but don't expect much - most of the stuff is interconnected, so I seriously doubt it'll be possible to factor something useful out.

@harrah. Martin is preparing a document that explains the stuff. In the meanwhile, the classloader change is enabled by several synergistic changes: 1) decoupling mirrors from universes (see `src/library/scala/reflect/base/MirrorOf.scala`), 2) making tags and exprs into factories rather than wrappers (see example of produced code in `src/compiler/scala/reflect/reify/utils/Extractors.scala`, 3) having `src/compiler/scala/reflect/runtime/JavaMirrors.scala`, a special flavor of mirrors that have a classloader.

**Comment by adriaanm** [comment]
I'm glad you find my arguments reasonable. I just want to insist one more time because I want to be very clear about what I mean.

I disagree with "Performance testing can be done ... on a scratchpad branch ... _so this is not an issue_."

I think this is still very much an issue, because these commits (or in the current state, _this_ commit) are (is) going to be in our history forever. One day down the road, some poor soul is going to have to read it and figure out its impact because there is going to be a bug related to it.

Now replace the variables "_one_ day", "_some_ poor soul", and "_a_ bug" by the actual counts of these incidents/involved people and multiply. That's going to be a pretty big number. (To judge the impact even better, assume this abstract poor soul is going to be future-you, concretely ;-)).

**Comment by xeno-by** [comment]
Testing the updated pull request here: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/221/console

**Comment by jsuereth** [comment]
Build failed, again.  Try running `ant distpack-opt`

**Comment by xeno-by** [comment]
Yeah, right, that's because I've not yet merged Vlad's pull request that fixes scaladoc.

**Comment by xeno-by** [comment]
Will be resubmitted

**Pull request closed without merging**
