### PR TITLE
Handle repeated singleton types

### LINKED ISSUE #12041: Migrating code to scala 2.13 : compiler crashes with "head of empty list" error
## reproduction steps

Clone this repository: https://github.com/gaospina/bac-a-sable.git

Compile the code with SBT or IntelliJ.

## problem

I want to migrate a project from Scala 2.12 to Scala 2.13. Of course, the code has several issues on deprecated code, and I solved the majority of those issues. But at the end I always get an error from the Scala compiler that is not directly related to the source code: 

```
Error:scalac: Error: head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:629)
	at scala.collection.immutable.Nil$.head(List.scala:628)
	at scala.reflect.internal.Types$TypeRef.customToString(Types.scala:2675)
	at scala.reflect.internal.Types$TypeRef.safeToString(Types.scala:2702)
	at scala.reflect.internal.tpe.TypeToStrings.typeToString(TypeToStrings.scala:55)
	at scala.reflect.internal.tpe.TypeToStrings.typeToString$(TypeToStrings.scala:34)
	at scala.reflect.internal.SymbolTable.typeToString(SymbolTable.scala:28)
	at scala.reflect.internal.Types$Type.toString(Types.scala:943)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
	at scala.collection.AbstractIterable.addString(Iterable.scala:920)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBoundsErrorMessage(ContextErrors.scala:1214)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBounds(ContextErrors.scala:1222)
	at scala.tools.nsc.typechecker.Infer$Inferencer.issueBoundsError$1(Infer.scala:982)
	at scala.tools.nsc.typechecker.Infer$Inferencer.check$1(Infer.scala:988)
	at scala.tools.nsc.typechecker.Infer$Inferencer.checkBounds(Infer.scala:992)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTypeApply(Typers.scala:4385)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:953)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:812)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:631)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1222)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1257)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1314)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1743)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
	at scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
	at scala.tools.nsc.Global$$anon$5.inferImplicitFor(Global.scala:482)
	at scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:272)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:888)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:492)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1305)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6035)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:6118)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5964)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6109)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1128)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1735)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1909)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1873)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:875)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2057)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2055)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2050)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1541)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1513)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1702)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5620)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6098)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2572)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5938)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5973)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:6297)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5928)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6098)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2082)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1912)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5929)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6098)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5629)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5932)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:117)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:105)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1505)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1489)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1616)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:42)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:43)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:117)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:109)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:95)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:53)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

## running environment

Scala 2.13.2
SBT 1.13.12

## expectation

The code should compile with several warnings (deprecation and migration warnings I didn't see yet because of this weird error). With some slight modifications the code compiles in Scala 2.12.11. A compile error related to the migration to Scala 2.13 may still be possible.

### PR DESCRIPTION
**Pull request by joroKr21**
Fixes scala/bug#12041

### CODE REVIEW

**Comment by SethTisue** [comment]
The change here seems logical enough, but it also seems a bit ad hoc, a random check added in a random place. I wondered if there might be some more general fix, is there some more general transform from "type as it appears in a parameter list" to "type as it will appear in the method body"? Or are repeated parameters the only case where such a transform is even needed?

I looked around at where else `repeatedToSeq` is called, but calls are rare. In fact, `Definitions.scala` goes so far as to claim:

> // We don't need to deal with JavaRepeatedParamClass here, as `repeatedToSeq` is only called in the patmat translation for Scala sources.

which this change would make not-true-anymore... but it also makes me wonder if there's a form of this bug that affects Java repeated params, and if so, if this fix misses it.

Anyway, I have no specific objection to merging this, but I'm not confident enough to say "Approve", either. Anyone else have further thoughts?

**Comment by dwijnand** [comment]
> > // We don't need to deal with JavaRepeatedParamClass here, as `repeatedToSeq` is only called in the patmat translation for Scala sources.
> 
> which this change would make not-true-anymore..

There's actually already a non-patmat usage in Typer... so the comment is stale (as is the CTA from Eugene to Paul :D)

I also think it's quite random to be doing this, but from the comments around `repeatedToSeq`'s usage in Typer (`vanillaAdapt`) it looks like the state of the RepeatedParam type is just in a bit of a state, and if we're going to do some single type caching we need to do same kind of adhoc adapting there too...

So I'm ok with this.  Thoughts on the fix yourself, @joroKr21?

**Comment by joroKr21** [comment]
Here are my thoughts to the raised questions.

> The change here seems logical enough, but it also seems a bit ad hoc, a random check added in a random place.

I tried other places before that were even more random. I think this is a good place because a singleton type with an underlying repeated type makes no sense. Repeated types are not "proper" types of their own and the rest of the compiler does not expect to encounter them after widening a singleton type as evidenced by the crash.

> I wondered if there might be some more general fix, is there some more general transform from "type as it appears in a parameter list" to "type as it will appear in the method body"?

A singleton type of a parameter is still a singleton type in the method body. Which means that the method doing this transformation just passes through singleton types. Note also that you can't pass a splat where a singleton is expected. 

> Or are repeated parameters the only case where such a transform is even needed?

Another similar case are by-name parameters but they are not stable values and cannot be used as singletons. 

> but it also makes me wonder if there's a form of this bug that affects Java repeated params, and if so, if this fix misses it.

I don't think we have to worry about Java varargs, because Java doesn't have singleton types. 

> There's actually already a non-patmat usage in Typer... so the comment is stale (as is the CTA from Eugene to Paul :D

Yeah those comments are stale, LMK if I should remove them :smile: but in this case it's also true that we don't have to worry about Java varargs, because Java doesn't have singleton types.

**Comment by joroKr21** [comment]
I didn't check what happens in Scala 3 though. I don't have my laptop right now but I could check after Christmas.

**Comment by SethTisue** [comment]
Scala 3's fine with all this:

```
Starting scala3 REPL...
scala> object Test {                                                                                                    
     |    def foo(xs: Int*) = new util.Random().shuffle(xs)
     |    def dup[T](x: T)(y: x.type) = (x, y)
     |    def bar(xs: Int*) = dup(xs)(xs)
     |  } 
// defined object Test
```

**Review by SethTisue — APPROVED** [review]

**Pull request merged**
