### PR TITLE
Moved inline logic before pickler.

### PR DESCRIPTION
**Pull request by gkossakowski**
The test case failed due to separate compilation. The problem was
that we don't pickle the fact that the field was made public.

Original patch by @odersky. Cleaned up by me. Changes I made:
- removed stale test-case
- reduced whitespace changes

Supersedes #1089.

Review by @odersky and @adriaanm.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Let's see if it's not a spurious failure.
PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by adriaanm** [comment]
yeah i think this one tends to flake out from time to time

**Comment by gkossakowski** [comment]
The last failure is spurious. All tests passed, and the build was successful.

Also, I checked whether inlining warnings went away with this change. Almost none of them did. Investigating into it now. This is not a blocker to merge this change.

**Comment by lrytz** [comment]
i fixed the build script, sorry 'bout that https://github.com/lrytz/jenkins-scripts/commit/f101de7879cd7afddfd3e36208ba2b797336abf2

**Comment by VladUreche** [comment]
PS: Merged with Martin's approval and verbal LGTM, as he wanted to try this change asap.

**Pull request merged**
