### PR TITLE
SI-8392 Guards QuasiquoteClass against non-availability in scala-reflect

### PR DESCRIPTION
**Pull request by huitseeker**
This assimilates behavior on Quasiquotes to the one on Reflection : if we
don't have the right resource on classpath, we do without rather than
throwing.

See the bug report for more on rationale (-Xsource flag, early quasiquote
loading in Analyzer through FastTrack, etc).

Review by @gkossakowski or @xeno-by

### CODE REVIEW

**Comment by xeno-by** [comment]
Could you reflect the rationale in a comment?

**Comment by huitseeker** [comment]
@xeno-by done.

**Comment by xeno-by** [comment]
LGTM

**Comment by adriaanm** [comment]
Excellent. Thanks, @huitseeker .

**Comment by dragos** [comment]
:+1:

**Pull request merged**
