### PR TITLE
Add firstKey and lastKey to LongMap, fixing SI-5151

### PR DESCRIPTION
**Pull request by thorpe-dev**
https://issues.scala-lang.org/browse/SI-5151

### CODE REVIEW

**Comment by adriaanm** [comment]
jenkins job pr-scala-testsuite-linux-opt: successful -- manually verified

**Comment by adriaanm** [comment]
jenkins job pr-rangepos: successful -- manually verified

**Comment by paulp** [comment]
@mt2309 can you please sign the [CLA](http://www.typesafe.com/contribute/cla)?

**Comment by paulp** [comment]
Closing pending CLA signature due to pull request overcrowding.

**Comment by thorpe-dev** [comment]
Sorry, I signed the CLA last night, forgot to update the PR with the info.

**Comment by paulp** [comment]
Thanks!

**Comment by thorpe-dev** [comment]
Closing this and reopening another PR because I'm failing at git.

**Pull request closed without merging**
