### PR TITLE
remove unused import, fix the build

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
Old PR, fatal warnings now on.

**Comment by dwijnand** [comment]
Weird:

```
ERROR: /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/tasty/neg/src-2/SColourOps_fail.scala failed, unexpected output.
--- check
+++ output
@@ -1,11 +1,1 @@
-SColourOps_fail.scala:6: warning: match may not be exhaustive.
-It would fail on the following inputs: Blue, CMYK(_, _, _, _), Green, RGB(_, _, _)
-    def red: Int = c match { // error: non-exhaustive
-                   ^
-SColourOps_fail.scala:9: warning: match may not be exhaustive.
-It would fail on the following inputs: CMYK(_, _, _, _), Green, RGB(_, _, _), Red
-    def blue: Int = c match { // error: non-exhaustive
-                    ^
-error: No warnings can be incurred under -Werror.
-2 warnings
-1 error
+
[error] Test scala.tools.tastytest.TastyTestJUnit.neg failed: scala.tools.tastytest.TestFailure: 1 error. These sources either compiled or had an incorrect or missing check file: /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/tasty/neg/src-2/SColourOps_fail.scala., took 10.747 sec
```

**Comment by dwijnand** [comment]
Very weird

```
compiling sources in /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/tasty/run/src-2 with scalac.
[error] Test scala.tools.tastytest.TastyTestJUnit.run failed: java.util.NoSuchElementException: None.get, took 5.521 sec
[error]     at scala.None$.get(Option.scala:627)
[error]     at scala.None$.get(Option.scala:626)
[error]     at scala.reflect.internal.Symbols$Symbol.rec$1(Symbols.scala:2146)
[error]     at scala.reflect.internal.Symbols$Symbol.caseFieldAccessors(Symbols.scala:2151)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$ExtractorCallProd.tupleSel(MatchTranslation.scala:521)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$ExtractorCall.productElemsToN(MatchTranslation.scala:417)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$ExtractorCall.subPatRefs(MatchTranslation.scala:450)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$ExtractorCallProd.treeMakers(MatchTranslation.scala:516)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.extractorStep(MatchTranslation.scala:120)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.nextStep(MatchTranslation.scala:164)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.translate(MatchTranslation.scala:172)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translatePattern(MatchTranslation.scala:322)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translatePattern$(MatchTranslation.scala:322)
[error]     at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translatePattern(PatternMatching.scala:103)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateCase(MatchTranslation.scala:319)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateCase$(MatchTranslation.scala:317)
[error]     at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translateCase(PatternMatching.scala:103)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch(MatchTranslation.scala:232)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator.translateMatch$(MatchTranslation.scala:200)
[error]     at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translateMatch(PatternMatching.scala:103)
[error]     at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:69)
[error]     at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:63)
```

**Comment by lrytz** [comment]
same again...

```
[error] Test scala.tools.tastytest.TastyTestJUnit.neg failed: scala.tools.tastytest.TestFailure: 1 error. These sources either compiled or had an incorrect or missing check file: /home/jenkins/workspace/scala-2.13.x-validate-main@3/test/tasty/neg/src-2/SColourOps_fail.scala., took 12.132 sec
[error]     at scala.tools.tastytest.TastyTest$.scalacNeg(TastyTest.scala:247)
```

```
[error] Test scala.tools.tastytest.TastyTestJUnit.run failed: java.util.NoSuchElementException: None.get, took 7.202 sec
[error]     at scala.None$.get(Option.scala:627)
[error]     at scala.None$.get(Option.scala:626)
[error]     at scala.reflect.internal.Symbols$Symbol.rec$1(Symbols.scala:2146)
[error]     at scala.reflect.internal.Symbols$Symbol.caseFieldAccessors(Symbols.scala:2151)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$ExtractorCallProd.tupleSel(MatchTranslation.scala:521)
```

**Comment by bishabosha** [comment]
PR https://github.com/scala/scala/pull/9008 broke the tasty stuff

**Comment by martijnhoekstra** [comment]
Oh no! What can I do to fix it?

**Comment by lrytz** [comment]
@bishabosha do you agree to `@Ignore` these tests until we figured it out?

**Comment by bishabosha** [comment]
I believe that it is due to private local fields not being created in tasty reader for class params that have public getters - so that can be done, but temporarily it is fine to block those tests

**Comment by lrytz** [comment]
@bishabosha could you clarify? I compiled src/compiler/scala/tools/tasty with current 2.13.x, and with https://github.com/scala/scala/pull/9008 reverted, and the bytecode is identical.

**Comment by bishabosha** [comment]
so currently Tasty reader does not create symbols for local fields when there is a `val` in a primary constructor. This means `constrParamAccessors` on a case class, compiled with dotty, returned an empty list, which causes the crash

**Pull request merged**
