### PR TITLE
SI-6028 Avoid needless symbol renaming in lambdalift

### PR DESCRIPTION
**Pull request by retronym**
Preserve names of all referenced free vars. This is achieved
in a slightly roundabout manner:
1. they are renamed (as before this change)
2. the code that references them is lifted
3. the original names are restored.

The resulting natural beauty is evident in the [diff of t6028.check](https://github.com/retronym/scala/commit/22f2e355#diff-3).

This subsumes the treatment in 0e170e4 that ensured named parameter
calls cannot see mangled names; pos/t6028 confirms as much.

Review by @lrytz

### CODE REVIEW

**Comment by lrytz** [comment]
Hi Jason - it took me a long time to get an idea of how this patch works, so I think it needs more documentation for people (like me) that don't know the internals of lambdalift, e.g. show the generated code for `def closure(x: Int) = { () => x }` and where it comes from.

I assume that the lifted code is generated by looking at the parameter symbol names, but then it's type-checked and receives new symbols? Therefore the original symbols can keep their original names, correct?

Maybe another way to achieve the same is to look at the `renamable` map when generating the lifted code? Then the two renamings could be avoided, no?

The `files/run/t6028.scala` test is nice - but do you think that tree printing is stable enough so that it doesn't become a nuisance?

**Comment by retronym** [comment]
Thanks for the review.

I chose this approach as the path of least resistance, which didn't require major surgery to the existing code. But I'll try to rewrite this to avoid the double rename. I think I can see where to start. Perhaps @odersky could comment about whether such an approach is worth pursuing?

Having a few tests based on tree-printing seems worthwhile to me; the output is stable, and if tree printing itself changes `partest --update-check` helps out.

**Comment by retronym** [comment]
@lrytz I've rewritten to avoid the convoluted double renaming: the proxies for free variables are now left alone, and only their proxies use the fresh names.

PLS REBUILD ALL

**Comment by lrytz** [comment]
In order to have this fix in 2.10 I guess you have to submit a new pr against the 2.10.x branch - this one is for to master.

The patch LVGTM, thanks!

Unrelated to your changes, the existing code could use a bit more documentation, it's not easy to understand what exactly all the HashMaps contain (e.g. `renamable` vs `free.values.flatten`).. we'll get there someday!

**Comment by adriaanm** [comment]
I'll close this one and submit a new one for 2.10.x

**Pull request closed without merging**
