### PR TITLE
Initialize BlockContext thread local to null to avoid a leak

### PR DESCRIPTION
**Pull request by havocp**
Generally considered bad to have an initialValue that points to something we might want to GC.

This doesn't change public API behavior in any known-detectable way, other than potentially allowing more stuff to GC without shutting down the thread.

Review by @phaller or @axel22 for example.

### CODE REVIEW

**Comment by viktorklang** [comment]
We don't want this into master only, we want it into 2.10.x AND master.
And it's critical since it fixes a memory leak issue.

I'll start reviewing this now.

**Comment by viktorklang** [comment]
LGTM

**Comment by axel22** [comment]
Looks good to me.

**Comment by havocp** [comment]
is master not 2.10? or is the point to add it to M5?

If I need to submit another pull let me know. I'm sure this commit will cherry-pick cleanly also. I don't know what the release process/rules are for the branch.

**Comment by axel22** [comment]
No, pulls to 2.10.x will go into 2.10, and later be merged into master.
So if you want things to go into both, you submit pull requests to 2.10.x. If you want the changes only in releases after 2.10, you submit a pull to master.

**Comment by havocp** [comment]
The jenkins results seem to be about the wrong commit...

**Comment by adriaanm** [comment]
I think it's building the right one, based on this fragment of the output:

```
+ git checkout -B pull-931-merge
Switched to a new branch 'pull-931-merge'
+ git fetch origin +pull/931/head:pullreq/931
From github.com:scala/scala
 * [new branch]      refs/pull/931/head -> pullreq/931
+ git merge pullreq/931
Updating 1e68d3b..2cf8389
Fast-forward
 src/library/scala/concurrent/BlockContext.scala |   13 +++++++------
 1 file changed, 7 insertions(+), 6 deletions(-)
```

it's pretty tricky to spot which pull request is being built, though, I agree
I'm also completely baffled by the test failure.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by viktorklang** [comment]
I just love build kitteh

**Comment by adriaanm** [comment]
@havocp, should I merge this into master? Or close and wait for the 2.10.x pull request?
Note that the window for inclusion into M6 is closing tomorrow.

(This was communicated to scala-internals a few weeks ago and is tracked on https://github.com/scala/scala/issues/milestones)

**Comment by viktorklang** [comment]
Hi Adriaan,

you can close this without merging, we're currently packaging the endgame changes to SIP-14 of which this change will be included.

Thanks,
√

**Pull request closed without merging**
