### PR TITLE
Test REPL valueOfTerm

### PR DESCRIPTION
**Pull request by som-snytt**
User test for scala/bug#12390 which progressed on 2.13

### CODE REVIEW

**Comment by som-snytt** [comment]
Not sure it's worth the cycles, but it was a weird failure mode.

**Comment by SethTisue** [comment]
Thank you!

**Comment by lrytz** [comment]
Windows doesn't do this test...
```
+scala.MatchError: Error (of class scala.tools.nsc.interpreter.Results$Error$)
+	at Test$.$anonfun$main$1(t12390.scala:35)
```
https://github.com/scala/scala/actions/runs/3328826676/jobs/5505274199#step:6:6549

**Comment by som-snytt** [comment]
I guess it must be testing something. Maybe it's line endings? I'll nail it down.

**Comment by som-snytt** [comment]
It's just some error, in some way.
```
  /** The line was erroneous in some way. */
  case object Error extends Result
```

**Comment by SethTisue** [comment]
```
% git grep -i 'in some way' | wc -l
       4
% git grep -i 'for some reason' | wc -l
      14
```

**Comment by som-snytt** [comment]
I try `sbt -Dsbt.color=false -no-colors` but still
```
←[?1h←=←[?2004hsbt:root> sbt "←[1@p←[1@a←[C←[1@←[11C
←[?1l←>←[?1000l←[?2004l

```
under cygwin where `TERM=xterm`. This is why, I'm reminded, I never try stuff out on Windows, even though I'm on a Windows box still.

**Comment by som-snytt** [comment]
Unfortunately, it passes under cygwin.

Update: it fails under PowerShell, collecting the output:
```
BAD [        Source.fromFile("t12390.scala").getLines().mkString("/n")
                            ^
On line 2: error: invalid escape character
        Source.fromFile("t12390.scala").getLines().mkString("/n")
                                  ^
On line 2: error: invalid escape character
        Source.fromFile("t12390.scala").getLines().mkString("/n")
                                        ^
On line 2: error: invalid escape character
        Source.fromFile("t12390.scala").getLines().mkString("/n")
                                                      ^
On line 2: error: invalid escape character
]
```
makes me think the buffer is somehow corrupted. Probably it will be some obvious foolery in retrospect.

Oh, absolute path is interpolated, of course:
```
[C:Usersandrescala-projectscala  est♀iles]
```
My favorite has to be `\f` as `♀`.

**Pull request merged**
