### PR TITLE
Correct collections variable definitions to avoid many scaladoc warnings.

### PR DESCRIPTION
**Pull request by vigdorchik**
Running 'ant docs.lib' produces such a long warning list that nobody seems to care. Consequently the documentation for stdlib contains many errorneous signatures.

This PR addresses most of the "Unresolved $Coll when documenting XXX" warnings and reduces scaladoc output from 1600 to 400 lines. Since this is a pure documentation change, it is safe to merge in 2.11.x

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @Ichoran

**Comment by soc** [comment]
Wow, thanks!

**Comment by paulp** [comment]
Please consider taking this opportunity to harden the policy so such garbage does not thrive indefinitely.

**Comment by vigdorchik** [comment]
Right, I think if we remove the last warning that 'String' is not found in
scala package object, we can make this warning an error in 2.12 branch.

**Comment by vigdorchik** [comment]
So the rest of the work should target 2.12 and be in a separate PR.

**Comment by retronym** [comment]
Ping @Ichoran, this is a big patch and it would be nice to get it merged before it accumulates merge conflicts.

**Comment by vigdorchik** [comment]
@Ichoran ping, this is taking too long. Can you please take a look?

**Comment by Ichoran** [comment]
LGTM

It is a little too large for me to verify each change (I read them and they look fine, but I didn't build and check the docs with/without each change).  If there are remaining issues I think it is better to fix those on top of this patch.

**Pull request merged**
