### PR TITLE
prevents using reify and quasiquotes in the compiler

### PR DESCRIPTION
**Pull request by xeno-by**
Kind of prevents us from using quasiquoting facilities in scalac,
because those depend on internal APIs that can easily diverge from starr,
creating problems similar to https://groups.google.com/forum/#!topic/scala-internals/K4EoU6q0dek.

This hack doesn't strictly prohibit those facilities from being used,
since I have no good idea about how to do that reliably, but rather
makes reification/quasiquoting print swaths of debug output that are
going to catch someone's eye.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by densh** [comment]
I'd personally add `-Yno-quasiquote` and make quasiquotes abort with nice error message if the flag is present. Printing debug information will be just confusing.

**Comment by xeno-by** [comment]
Yes, I considered that, but I didn't like introducing a compiler option that's going to be used just to compile the compiler.

**Comment by retronym** [comment]
You will first need to localize this to our production code.

https://scala-webapps.epfl.ch/jenkins/job/pr-scala-test/5146/consoleFull

```
test.osgi.comp:
    [mkdir] Created dir: /localhome/jenkins/c/workspace/pr-scala-test/scala/build/osgi/classes
[scalacfork] Compiling 5 files to /localhome/jenkins/c/workspace/pr-scala-test/scala/build/osgi/classes
[scalacfork] reifying = tools.test.osgi.reflection.basic.C
[scalacfork] universe = scala.reflect.runtime.`package`.universe
[scalacfork] mirror = <empty>
[scalacfork] reification = {
[scalacfork]   val $u: scala.reflect.runtime.`package`.universe.type = scala.reflect.runtime.`package`.universe;
[scalacfork]   val $m: $u.Mirror = scala.reflect.runtime.`package`.universe.runtimeMirror(Predef.this.classOf[tools.test.osgi.reflection.basic.BasicReflectionTest].getClassLoader);
[scalacfork]   $u.TypeTag.apply[tools.test.osgi.reflection.basic.C]($m, {
[scalacfork]     final class $typecreator1 extends TypeCreator {
[scalacfork]       def <init>() = {
[scalacfork]         super.<init>();
[scalacfork]         ()
```

**Pull request closed without merging**
