### PR TITLE
Reduce scope of val and improve some names

### PR DESCRIPTION
**Pull request by janekdb**

### CODE REVIEW

**Comment by janekdb** [comment]
`sbt test` failed but so did `HEAD~`,

`HEAD~` #5683
```
11:16 $ git recent 
b59a72f adriaan@lightbend.com 35 hours ago     Merge pull request #5683 from SethTisue/remove-deprecated-predef-stuff
5b9ed75 seth@tisue.net       4 days ago       Merge pull request #5638 from som-snytt/issue/10137
c057e9e seth@tisue.net       6 days ago       remove deprecated stuff from Predef, scala._, scala.runtime
7e49927 som.snytt@gmail.com  5 weeks ago      SI-10137 Correct Queue.enqueue(collection.Iterable)
d56d66d lukas.rytz@gmail.com 9 weeks ago      Merge pull request #5599 from lrytz/pr5342
27dc56e zizheng.tai@gmail.com 9 weeks ago      Make SearchImpl a value class to improve performance
2493d8c lukas.rytz@gmail.com 9 weeks ago      Merge pull request #5548 from janekdb/issue/SI-9813-to-2.13.x
50148db janekdb@gmail.com    9 weeks ago      SI-9813: Complete addition of Java 1.6 and 1.8 java.lang.Math methods
196bd10 p.petlinsky@rambler-co.ru 9 weeks ago       * restructure to groups new functions in scala.math package
8066246 adriaan@lightbend.com 9 weeks ago      New keypair for 2.13 spec forced command
36d6e48 lukas.rytz@gmail.com 9 weeks ago      Merge pull request #5591 from xuwei-k/stableSort-ClassTag
7083c57 6b656e6a69@gmail.com 9 weeks ago      remove unnecessary ClassTag in Sorting.stableSort
87c75a7 seth@tisue.net       10 weeks ago     Merge pull request #5581 from SethTisue/twelve-going-on-thirteen
5e62f13 seth@tisue.net       10 weeks ago     2.12 -> 2.13 in the most important places
92b695c seth@tisue.net       2 months ago     Merge pull request #5582 from SethTisue/keep-2.13-spec-separate

✔ ~/workspaces/public/scala [2.13.x|…19⚑ 33] 
11:16 $ sbt compile
[info] Loading project definition from /home/jdb/workspaces/public/scala/project/project
[info] Loading project definition from /home/jdb/workspaces/public/scala/project
[info] Updating {file:/home/jdb/workspaces/public/scala/project/}scala-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] *** Welcome to the sbt build definition for Scala! ***
[info] Check README.md for more information.
[info] Compiling 35 Scala sources to /home/jdb/workspaces/public/scala/build/quick/classes/library...
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/HashMap.scala:524: object error is not a member of package sys
[error]       case _ => sys.error("section supposed to be unreachable.")
[error]                     ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/parallel/mutable/ParArray.scala:639: object error is not a member of package sys
[error]       case _ => sys.error("Can only split scan tree internal nodes.")
[error]                     ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/parallel/package.scala:242: object error is not a member of package sys
[error]           sys.error("Unexpected combiner type.")
[error]               ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/HashSet.scala:473: object error is not a member of package sys
[error]       sys.error("cannot serialize an immutable.HashSet where all items have the same 32-bit hash code")
[error]           ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/HashSet.scala:478: object error is not a member of package sys
[error]       sys.error("cannot deserialize an immutable.HashSet where all items have the same 32-bit hash code")
[error]           ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/concurrent/duration/Duration.scala:563: not found: type TimeUnit
[error] final class FiniteDuration(val length: Long, val unit: TimeUnit) extends Duration {
[error]                                                        ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/concurrent/duration/Duration.scala:379: not found: type TimeUnit
[error]   def unit: TimeUnit
[error]             ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/concurrent/duration/Duration.scala:25: not found: type TimeUnit
[error]   def apply(length: Double, unit: TimeUnit): Duration     = fromNanos(unit.toNanos(1) * length)
[error]                                   ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/concurrent/duration/Duration.scala:31: not found: type TimeUnit
[error]   def apply(length: Long, unit: TimeUnit): FiniteDuration = new FiniteDuration(length, unit)
[error]                                 ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/concurrent/duration/Duration.scala:91: not found: type TimeUnit
[error]   protected[duration] val timeUnit: Map[String, TimeUnit] =
[error]                                                 ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/RedBlackTree.scala:197: object error is not a member of package sys
[error]       else sys.error("Defect: invariance violation; expected black, got "+t)
[error]                ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/RedBlackTree.scala:206: object error is not a member of package sys
[error]       sys.error("Defect: invariance violation")
[error]           ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/RedBlackTree.scala:215: object error is not a member of package sys
[error]       sys.error("Defect: invariance violation")
[error]           ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/RedBlackTree.scala:242: object error is not a member of package sys
[error]       sys.error("unmatched tree on append: " + tl + ", " + tr)
[error]           ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/RedBlackTree.scala:373: object error is not a member of package sys
[error]         sys.error("Defect: unexpected empty zipper while computing range")
[error]             ^
[error] /home/jdb/workspaces/public/scala/src/library/scala/collection/immutable/RedBlackTree.scala:362: object error is not a member of package sys
[error]         sys.error("unmatched trees in unzip: " + left + ", " + right)
[error]             ^
[error] 16 errors found
[error] (library/compile:compileIncremental) Compilation failed
[error] Total time: 26 s, completed 15-Feb-2017 11:16:52
✘-1 ~/workspaces/public/scala [2.13.x|…19⚑ 33] 
```

**Comment by SethTisue** [comment]
well, I don't understand this part at all: "Found earlier commit(s) marked failure: d27135, fc1aea, 208faa"

but _your_ commit, 014b104e3ce4d8f060cc77b5dadac0d783ddafea, passed validation

I'm not able to locally reproduce the compilation failures you're seeing. does it happen even after `sbt clean` or `git clean`? what does `git status` say?

**Comment by janekdb** [comment]
Following `sbt clean` and `git clean -f`  `sbt compile` completed,

```
...
[info] Compiling 11 Scala sources and 1 Java source to /home/jdb/workspaces/public/scala/build/quick/classes/partest-extras...
[warn] there were two unchecked warnings; re-run with -unchecked for details
[warn] one warning found
[success] Total time: 236 s, completed 16-Feb-2017 11:43:54
```

Probably related to switching between 2.12.x and 2.13.x without `sbt clean`. Issue gone!

**Review by lrytz — APPROVED** [review]

**Pull request merged**
