### PR TITLE
makes sense of implicit macros! now in master

### PR DESCRIPTION
**Pull request by xeno-by**
This is a port of https://github.com/scala/scala/pull/2494 from 2.10.x. Depending on your preference we can either get it in 2.11.0-M3, since it's already been reviewed and merged in 2.10.2, or we can delay it until 2.11.0-M4.

review @paulp @retronym

### CODE REVIEW

**Comment by xeno-by** [comment]
Details of the port:
- https://github.com/scala/scala/commit/0c6927b4845633f262794aadda9b188b140717b6 => unnecessary, since SI-5353 is already broken in master
- https://github.com/scala/scala/commit/90ac5c4e1350493f6f47c674572c2dcb97b2b9eb => https://github.com/scalamacros/kepler/commit/adef4b526833a804dcbc160ff67c83e42c9fc2ee
- https://github.com/scala/scala/commit/bb73b9669a96410bc9c513d061d090f5bd3c075e => https://github.com/scalamacros/kepler/commit/a35b6bc8e4369db8983d6d0d9881f37d7affbadd
- https://github.com/scala/scala/commit/8168f118c9f71d63404880de89f20471043949fe => https://github.com/scalamacros/kepler/commit/c539ae2f56fe9f565cffb4afd6ab131bda89acb7
- https://github.com/scala/scala/commit/fdead2b3793fd530e05331649e655576f30e59e9 => unnecessary, was already fixed in master
- https://github.com/scala/scala/commit/b4da864247ccaaee4f987fbf433b312e1d744a8f => https://github.com/scalamacros/kepler/commit/b1538804043bdd7036a6378a9146b685db03a4ba
- https://github.com/scala/scala/commit/3edde2727bad9b00cbaf5475f5bf234f08c26cbd => unnecessary, was already fixed in master
- https://github.com/scala/scala/commit/4e64a2731d6e4c27e2fd4c75559e118708e79ad5 => https://github.com/scalamacros/kepler/commit/966f51c9cb23c788f22dc0b71a534508e3eed4e3

**Comment by xeno-by** [comment]
PLS REBUILD/pr-rangepos-per-commit@910ffaa

**Comment by xeno-by** [comment]
Any chance this patch can see the light of 2.11.0-M3?

**Comment by xeno-by** [comment]
Look it builds fine, it was reviewed in 2.10.x. Why not?

**Comment by retronym** [comment]
I'm in support of this for 2.11.0-M3. I just need to review the patch. We're not cutting the release Wednesday(-ish).

**Comment by retronym** [comment]
LGTM. Merging now, as the work was already more widely reviewed in the 2.10.x branch.

**Pull request merged**
