### PR TITLE
An option for real repl output.

### PR DESCRIPTION
**Pull request by paulp**
There have been many requests to expose the products of
the repl in some way outside in-memory. This does that.

  scala                        # usual in-memory behavior
  scala -Yrepl-outdir ""       # make up a temp dir
  scala -Yrepl-outdir /foo/bar # use /foo/bar

### CODE REVIEW

**Comment by retronym** [comment]
How will this behave over subsequent runs of the REPL? I'd presume that existing class files are ignored and possibly overrwritten from time to time.

**Comment by paulp** [comment]
That's correct, they'll be ignored and/or overwritten, but you correctly anticipate that this is in part setup for persistence.

**Comment by paulp** [comment]
Review by @retronym

**Comment by retronym** [comment]
lgtm

**Pull request merged**
