### PR TITLE
SI-7486 Regressions in implicit search.

### PR DESCRIPTION
**Pull request by paulp**
Revert e86832d7e8 and dd33e280e2.

### CODE REVIEW

**Comment by retronym** [comment]
The more I think about this, the more I think that we can't implement this error message pruning. Heisenberg will get us every time. Either we consider the type of the implicit unknowable, or we don't.

In any case, I will try continue to try to capture the Scalatest regression in a test.

**Comment by JamesIry** [comment]
LGTM

**Comment by retronym** [comment]
Here's a test case for the (broken) status quo.

``` scala
trait M[+A]
object M {
  implicit def M: M[String] = null
}

object Test extends App {
  def foo(implicit s: M[String]) = ()

  {
    foo

    implicit val bar = new M[String] { } // should be disqualified: inferred type, after the point of the search
    ()
  } // :: Nil   // add this and the above expands to `foo(bar)`, rather than `foo(M.M)`
}
```

Still digging...

**Comment by paulp** [comment]
Excellent test case; it should serve double duty, also silencing anyone who was thinking of defending the current behavior.

**Comment by retronym** [comment]
LGTM, too. The additional test cases can target master in due course.

**Pull request merged**
