### PR TITLE
SI-8525 Clarify usage of -Xlint:_,flag

### PR DESCRIPTION
**Pull request by som-snytt**
Align more with javac -Xlint:all,-flag,flag where once a flag is
explicitly enabled it cannot be disabled, but where the wildcard
is a backstop only.

-Xlint and -Xlint:_ just set a flag which is consulted by any
unset lint warning.

Some tests are corrected. Also, option order is no longer
significant, see the unit test.

### CODE REVIEW

**Comment by lrytz** [comment]
I kind of lost the overview here; I assume just providing `-Xlint` will have the same effect as before, i.e. enable a set of default warnings.

What does `-Xlint:_` do? What about `-Xlint:all`? How do you add / remove a specific warning? If you just add/remove, do you get the (other) defaults?

All these questions should be answered in the command-line usage, which currently (i.e. on the branch of this PR) reads

```
-Xlint:<warning>               Enable recommended additional warnings: adapted-args,by-name-right-associative,delayedinit-select,doc-detached,inaccessible,infer-any,missing-interpolator,nullary-override,nullary-unit,option-implicit,package-object-classes,poly-implicit-overload,private-shadow,unsound-match.
```

**Comment by som-snytt** [comment]
The test failure is due to unwarranted cleverness in the previous PR of uncommenting an old paulp warning without enabling it, see warnValueOverrides used in SyntheticMethods.  Nobody likes commented-out code, right?

```
// Without a means to suppress this warning, I've thought better of it.
```

The current PR makes the warning enabled by `-Xlint`, though it won't take `-Xlint:value-overrides`.

It did occur to me that the table of lint warnings is unwieldy, and this confirms it.  It exceeds my ability to keep things in my head by a factor of two or three.

I'll disable that warning for now, and save the improvement for later.

**Comment by som-snytt** [comment]
@lrytz `-Xlint:_` is by analogy to `-language:_`.  Or more than analogy, by the way settings works.

I could special-case "all", but maybe underscore is more special and Scalaic.  Open to consensus, of course.

I'll improve the message.  To something.

javac -X says -Xlint:{all,foo,bar,-foo,-bar}  Enable or disable specific warnings.

If javac can go to church in a golf shirt, so can we. (By which I mean, baggy and comfortable but not terribly stylish or fitting.)

Maybe help could be more verbose under -verbose.

**Comment by som-snytt** [comment]
I wouldn't be averse to `Xlint:help` that explains your options, as `-Ybrowse:help` could list phases, etc.

**Comment by lrytz** [comment]
> `Xlint:help`

I like that, the usage line is already way to long now.

**Comment by gourlaysama** [comment]
So, in the end, this would lead to:
- `-Xlint:_` to enable all warnings (with `-Xlint` as a shorthand),
- `-Xlint:foo,bar` to enable only foo and bar,
- `-Xlint:_,-bar` to enable all except bar,
- `-Xlint:help` to get the list of warnings and help about the syntax,
- and order doesn't matter, explicitly enabling a warning always wins.

That looks pretty good.

**Comment by som-snytt** [comment]
Here's a good one:

```
$ scalac -X:false
```

**Comment by lrytz** [comment]
LGTM, thank you!

**Comment by som-snytt** [comment]
I didn't have a chance to run tests before taking off this morning.  Something has to fail, because I think there are tests for help messages.

Making MutableSettings.add less private is wrong, but the alternative is to upgrade the sig of the creator methods somehow, which involves touching multiple files because of the way the Settings realm functions.

I made -Xlint:help to output the descriptions, but -language has no descriptions yet.

**Comment by som-snytt** [comment]
I considered adding `-Xlint:all` not just as a synonym for `_`, but to include the noisy experimental flags. If someone says that's a great idea, I'll try it, and if someone says that's too confusing, I won't.

I like the idea of being able to turn on miscellaneous noise; there are six such flags now, one for each of the states of California.  Impossible to remember or enable one by one.

We can save that feature for later.

**Comment by som-snytt** [comment]
Thx for the review or scourge, @som-snytt.  I mostly took your suggestions.  I don't know why github doesn't autocomplete your handle.

```
$ skalac -language:help -Xlint:help
Enable or disable specific warnings:
  adapted-args              Warn if an argument list is modified to match the receiver.
  by-name-right-associative By-name parameter of right associative operator
  delayedinit-select        Selecting member of DelayedInit
  doc-detached              A ScalaDoc comment appears to be detached from its element.
  inaccessible              Warn about inaccessible types in method signatures.
  infer-any                 Warn when a type argument is inferred to be `Any`.
  missing-interpolator      A string literal appears to be missing an interpolator id.
  nullary-override          Warn when non-nullary `def f()' overrides nullary `def f'.
  nullary-unit              Warn when nullary methods return Unit.
  option-implicit           Option.apply used implicit view.
  package-object-classes    Class or object defined in package object
  poly-implicit-overload    Parameterized overloaded implicit methods are not visible as view bounds
  private-shadow            A private field (or class parameter) shadows a superclass field.
  unsound-match             Pattern match may not be typesafe

Enable or disable language features:
  dynamics                  Allow direct or indirect subclasses of scala.Dynamic
  postfixOps                Allow postfix operator notation, such as `1 to 10 toList'
  reflectiveCalls           Allow reflective access to members of structural types
  implicitConversions       Allow definition of implicit functions called views
  higherKinds               Allow higher-kinded types
  existentials              Existential types (besides wildcard types) can be written and inferred
  experimental.macros       Allow macro defintion (besides implementation and application)
```

For the general options:

```
$ skalac -help
[snip]
  -language:<_,feature,-feature>  Enable or disable language features: `_' for all, `-language:help' to list
$ skalac -X
[snip]
  -Xlint:<_,warning,-warning>    Enable or disable specific warnings: `_' for all, `-Xlint:help' to list
```

Really, there should be an `import language.feature.postfix.toList` just for the 80/20 rule.

**Comment by lrytz** [comment]
Thanks! I really like how you guys pushed this thing forward :)

**Comment by retronym** [comment]
Unfortunately this has caused a regression in the treatment of of multiple `-language` options.

```
% scala-hash f81ec8d1~1 -feature -language:higherKinds -language:implicitConversions -Xfatal-warnings -nc -e 'def foo[M[_]] = ???'

% scala-hash f81ec8d1 -feature -language:higherKinds -language:implicitConversions -Xfatal-warnings -nc -e 'def foo[M[_]] = ???'
/var/folders/s2/g6fgtpk52hl8njjvx8vyzr9r0000gn/T/scalacmd7608576357516882493.scala:1: warning: higher-kinded type should be enabled
by making the implicit value scala.language.higherKinds visible.
This can be achieved by adding the import clause 'import scala.language.higherKinds'
or by setting the compiler option -language:higherKinds.
See the Scala docs for value scala.language.higherKinds for a discussion
why the feature should be explicitly enabled.
def foo[M[_]] = ???
        ^
error: No warnings can be incurred under -Xfatal-warnings.

% scala-hash f81ec8d1 -feature -language:higherKinds -Xfatal-warnings -nc -e 'def foo[M[_]] = ???'

% git what-branch --reference=2.11.x f81ec8d1
f81ec8d1 used the following minimal temporal path:
  merged to 2.11.x @Fri Jul 18 13:58:40 2014
    Merge pull request #3885 from som-snytt/issue/8525-cleanup

  2.11.x is on 2.11.x
```

Lodged as [SI-8736](https://issues.scala-lang.org/browse/SI-8736), marked as a blocker for 2.11.2.

**Comment by lrytz** [comment]
Thanks, Jason. I'm taking a look at this one.

**Comment by som-snytt** [comment]
Hey, I'm stuck at home, so I was looking at it. @lrytz

**Comment by lrytz** [comment]
Oh, great, thanks for the heads up! Let us know how things progress and if you can use any help.

**Comment by som-snytt** [comment]
Thx.  My skill at creating stupid regressions is eclipsed only, albeit slightly, by my skill at progressing them.

**Pull request merged**
