### PR TITLE
SI-5940 impls are no longer in macro def pickles

### PR DESCRIPTION
**Pull request by xeno-by**
The first officially released version of macros persisted
macro def -> impl bindings across compilation runs using a neat trick.

The right-hand side of macro definition (which contains a reference to an impl)
was typechecked and then put verbatim into an annotation on macro definition.

This solution is very simple, but unfortunately it's also lacking. If we use it
then signatures of macro defs become transitively dependent on scala-reflect.jar
(because they refer to macro impls, and macro impls refer to
scala.reflect.macros.Context defined in scala-reflect.jar).
More details can be found in https://issues.scala-lang.org/browse/SI-5940.

Therefore we have to avoid putting macro impls into binding pickles and
come up with our own serialization format. Situation is further complicated
by the fact that it's not enough to just pickle impl's class and method names,
because macro expansion needs knowledge about the shape of impl's signature
(which we can't pickle). Hence we precompute necessary stuff (e.g. the layout
of type parameters) when compiling macro defs.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @odersky

**Comment by xeno-by** [comment]
normal checkin build works fine: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/285/console

**Comment by xeno-by** [comment]
Changes made to the commit in comparison with the stuff that's been built by `scala-checkin-manual` are purely cosmetic - I just added a few lines of comments and didn't touch the code.

**Comment by xeno-by** [comment]
Started a rangepos build: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/287/console

**Comment by xeno-by** [comment]
By the way, it's so nice that we've hidden system macros behind the fast track! Otherwise we'd have to restarr painfully, because the new binding format is incompatible with the old one.

**Comment by VladUreche** [comment]
Hi Eugene, what do you mean by "behind the fast track"?

**Comment by xeno-by** [comment]
There's a backdoor in the macro expansion mechanism. 

If the compiler knows about the macro it comes across (by "knows" I mean if that macro is mentioned in the fast track registry [1]), then it skips most of the standard processing and just invokes the expansion callback registered for that macro. As a result, system macros are a more performant (since they don't use reflection) and are super-resilient to changes in the macro engine.

[1] https://github.com/scala/scala/blob/master/src/compiler/scala/tools/reflect/FastTrack.scala

**Comment by VladUreche** [comment]
Now I see what you mean. Thanks!

**Comment by xeno-by** [comment]
Verdict: investigate an alternative solution that combines Paul's recently proposed stub symbols and usage of native Scala reflection for invoking macro implementations.

**Pull request closed without merging**
