### PR TITLE
Silence pos/t3960's -Ycheck output.

### PR DESCRIPTION
**Pull request by paulp**
Someday someone will have to straighten out where output goes.
Clearly under current conditions, Console.err is not a good place.
I rerouted through unit.warning so the output will be swallowed
like all the other warnings.

### CODE REVIEW

**Comment by paulp** [comment]
Not a lot of review to do here. @densh, @som-snytt, @xeno-by, @retronym? We'll take whoever is awake.

**Comment by paulp** [comment]
PR #2960 in reference to SI-3960. We strive for equality modulo 1000. It does leave kind of a small window for fixes though.

**Comment by retronym** [comment]
Do you know what changed recently to make this noisy? Something in partest?

**Comment by retronym** [comment]
LGTM in any case.

**Comment by paulp** [comment]
@retronym It was me in 288b12e48a. I naively thought sending debug output to stderr instead of stdout would be progress. Not yet.

**Comment by som-snytt** [comment]
I was awake and ran the test before scootering to first grade, but didn't have the noisy cog yet.  We're up early because someone realized the early bird can fix her own cheerios instead of waiting for oatmeal.

The asterisk reduction in the panic message suggests another use of the star name: instead of log.warn or is it warning, just `log ** "Looks serious"` and `log **** "Oh this is bad"` kind of like wiki syntax for headers.

**Pull request merged**
