### PR TITLE
SI-5353 Fix Array unsoundness [Rebase of #2703]

### PR DESCRIPTION
**Pull request by adriaanm**
[Rebase of #2703]

### CODE REVIEW

**Comment by adriaanm** [comment]
PLS REBUILD ALL
NOLITTER!

**Comment by paulp** [comment]
LGTM, but I guess I'm just patting myself on the back here.

**Comment by adriaanm** [comment]
I'm open to fixing this, and, thanks, @soc, for reviving this branch, but this will need some documentation.
This stuff is way too subtle to be merged with a one-line commit message and undocumented tests (imagine your future self, facing the added tests failing -- how would you tell whether it's spurious?).

@soc, please remedy this, possibly based on the comment at https://github.com/scala/scala/pull/2806/files#L6R713.

**Comment by paulp** [comment]
I realized I should be glad when you close my pull requests. So I will be glad instead.

**Pull request closed without merging**
