### PR TITLE
Add convenience attribute operator to NodeSeq

### PR DESCRIPTION
**Pull request by rtyley**
Compared to the current method of reading the string text of an attribute:

```
(x \ "@bar").text
```

...the new operator removes the need for a pair of parenthesis and shortens the overall expression by 7 chars :

```
x \@ "bar"
```

Discussion on scala-internals:

https://groups.google.com/d/topic/scala-internals/BZ-tfbebDqE/discussion

Review by @phaller

### CODE REVIEW

**Comment by soc** [comment]
What about `\\@`?

**Comment by rtyley** [comment]
@soc interesting question - `\\@` would mean _'give me the (concatenated or traversable?) values of **every** attribute with this name under the current nodeseq'_ - although it could be a useful shortcut, I typically wouldn't read the value of an attribute without first knowing the name of the element it belonged to.

For me, this means that although I feel comfortable with `\@`, I would rather not have `\\@` included.

**Comment by rtyley** [comment]
btw, I have mailed a signed copy of the Scala CLA to Danielle Chamberlain.

**Comment by adriaanm** [comment]
ping @phaller

**Comment by phaller** [comment]
LGTM

**Pull request merged**
