### PR TITLE
SI-6840 fixes weird typing of quasiquote arguments

### PR DESCRIPTION
**Pull request by densh**
Previously quasiquote arguments were type checked against Any
which caused weird inference that made splicing of complex expressions
unusable:

``` scala
   val l1 = List(q"foo")
   val l2 = List(q"bar")
   q"f(..${l1 ++ l2})" // argument type checked as Any instead of List[Tree]
```

This is fixed by forcing compiler to type check against type
variable which itself isn't used in any other way.

review by @retronym

### CODE REVIEW

**Comment by xeno-by** [comment]
This is a real breakthrough, but it'd be great to get an insight about what exactly made this work.

**Comment by densh** [comment]
There has been some related discussion on https://issues.scala-lang.org/browse/SI-6155.

**Comment by paulp** [comment]
Has anyone investigated using WildcardType as the expected type when Any is the explicit type? I think the types inferred will be much improved.

**Comment by retronym** [comment]
Only macros can tell the difference as they can peek at the type of arg trees even if the formal type is fully defined. Avoiding needless Lubs when the pt is fully defined is a performance optimization we don't want to do without.

**Comment by paulp** [comment]
I see that was already suggested in SI-6155, "The problem could be reduced by having the typechecker special-case Any as a target type, and treating it as WildcardType." But I think you could do it when you needed to without punting on performance.

Not to mention that this is an example of overloading Any in the same way Nothing is overloaded. All such overloaded uses are bad. It should not require sorcery to recognize the difference between "Any" expressed to mean "Any" and "Any" expressed to mean "that's what macros make me do so I can work it out inside the macro."

**Comment by retronym** [comment]
`Any` isn't really relevant in this case. The macro could have declared it wanted any other fully defined type, and been equally disappointed that the argument didn't arrive with something more refined.

If it wants the type checker to compute a type for it, declaring a type parameter seems a reasonable way to do it. That's how you'd do it for regular methods.

`def foo[T <: C](t: T): X`

This won't fly if the macro needs to override a method `(c: C)X`.

BTW, there used to be an experimental flavour of macros that didn't typecheck the arguments at all:

`def foo(c: _) = macro ...`

**Comment by paulp** [comment]
Does that last translate (in principle, after adjusting for the unlikelihood of existentials working correctly in concert with a macro) to `def foo(c: T forSome { type T }) = macro ...` ? Syntactically that's what it could/should mean, and not just for macros - for any method.

**Comment by retronym** [comment]
The argument to an untyped macro was any syntactically valid tree, untyped, and not necessarily typable. The macro implementation could choose whether, when, and with which expected type to type it. Those were the days...

**Comment by paulp** [comment]
I curse thee with nothing but BLACK BOXES for as long as ye shall live!

**Comment by retronym** [comment]
LGTM.

**Pull request merged**
