### PR TITLE
Removing deprecated code.

### PR DESCRIPTION
**Pull request by paulp**
Code which has been deprecated since 2.10.0 and which allowed for
straightforward removal.

### CODE REVIEW

**Comment by adriaanm** [comment]
```

scala-refactoring/org.scala-refactoring.library/src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala:11: error: object RangePosition is not a member of package scala.tools.nsc.util
import tools.nsc.util.RangePosition
       ^
scala-refactoring/org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceHelperTest.scala:11: error: object SourceFile is not a member of package scala.tools.nsc.util
import tools.nsc.util.SourceFile
       ^
scala-refactoring/org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/SourceHelperTest.scala:12: error: object BatchSourceFile is not a member of package scala.tools.nsc.util
import tools.nsc.util.BatchSourceFile
       ^
three errors found
```

**Comment by adriaanm** [comment]
We'll need some time to catch up scala-refactoring. @misto, could you have a look at fixing these deprecation warnings in your build?

**Comment by misto** [comment]
Fixed!

**Comment by adriaanm** [comment]
Wow -- that was fast! Thanks!

**Comment by paulp** [comment]
Despite its fixedness I restored the imports because I assume this isn't being tested against up-to-the-second artifacts.

**Comment by misto** [comment]
Au contraire! I've verified that it works against 2.10.4, and my build server tells me that it's fine on 2.10.3 as well.

**Comment by soc** [comment]
Nice! :-)

**Comment by adriaanm** [comment]
We actually build against master for scala-refactoring. Living on the edge! (https://github.com/scala-ide/uber-build/blob/master/config/validator.conf#L57)

**Comment by dragos** [comment]
Thanks @misto!

**Comment by retronym** [comment]
LGTM.

**Pull request merged**
