### PR TITLE
SI-7329 duplicate default getters for specialized parameters.

### PR DESCRIPTION
**Pull request by vigdorchik**
The default getter is generated with @specialized annotation if the
type parameter corresponding to the type of the parameter is
specialized. Consequently specialize pass tries to generate overloads.

Rather than pruning overloads to exclude duplicates, let's notice
that default getter specialization is not needed at all:
- The dynamic scope of default getter doesn't include specialized
  method or class constructor.
- generic default getter is called even when calling specialized
  method.

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @paulp.

**Comment by VladUreche** [comment]
Eugene, is there no way to:
1) Generate default getters such that there are no duplicate methods?
2) Rewire the default getters to the specialized overload?
It seems to me the default getters are legitimately specializable methods, which should return a value without boxing, no? 

Maybe I'm wrong, but to me it seems it's just a matter of duplicating them correctly and then actually using them, rather than a question of not needing them at all.

**Comment by paulp** [comment]
@VladUreche you may be right, but I think such ambition is misdirected. The future of the current approach to specialization is grim. If this patch fixes the "it generates bytecode which will not run" problem, then whether or not the default getter is specialized is of little relevance. In fact I would prefer the simpler patch.

**Comment by VladUreche** [comment]
Good point @paulp, thanks for chiming in!
I created https://issues.scala-lang.org/browse/SI-7368 to remind us to specialize them after we cleanup specialization.

On the other hand, @vigdorchik, can you please squish the three commits? When this is done, you have my LGTM.

**Pull request merged**
