### PR TITLE
Warn when combining -optimise with -Ybackend:GenBCode

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
review by @adriaanm

**Comment by adriaanm** [comment]
The test suite is not happy with it, but LGTM otherwise :)

**Comment by lrytz** [comment]
will fix the tests

**Comment by lrytz** [comment]
CI passes `-optimise` to all tests, with `GenBCode` being the default backend. So we get the new warning all over.

I have to rebase this on top of #4602, which changes the flag to `-Yopt:l:classpath` (or just integrate it in that PR)

**Comment by lrytz** [comment]
added those patches to PR #4602

**Pull request closed without merging**
