### PR TITLE
SI-9208 Phase out ad-hoc, incorrect implicit shadowing detection

### PR DESCRIPTION
**Pull request by retronym**
Paraphrasing Greenspun:

> Any sufficiently complicated Implicit Search program contains an
> ad hoc, informally-specified, bug-ridden, slow implementation of
> half of `typedIdent`.

The shadowing detection code that is being phased out was exactly
this. We have since heeded the aphorism above and perform
shadowing detection after typechecking a candidate implicit
(in 9129cfe911).

But, we didn't remove the pre-filtering of candidated based on
the old shadowing checks. This commit does exactly that. As this
introduces a minor source incompatibility, it is predicated on
-Xsource:2.12.

Review by @som-snytt, @adriaanm

### CODE REVIEW

**Comment by som-snytt** [comment]
This PR is an instant classic. Also it's the only PR related to implicits that I understand.

**Comment by som-snytt** [comment]
I'll try building with the update to see if any ambiguous implicits go away... But it's still a classic.

**Comment by retronym** [comment]
I've pushed a commit that shows the latent bug that is exposed by removing the shadow-filter.

**Comment by retronym** [comment]
The latest version seeks to fix the double counting in `Context#implicitss` for good.

**Comment by lrytz** [comment]
```
  [partest] !! 877 - neg/t729.scala                            [expected compilation failure]
```

**Comment by retronym** [comment]
I'll have to come back to this when I can tease apart the subtle change in `neg/t729.scala`. I thought I could get class-owned implicits from the `ownerThisType.implicitMembers`, but this needs more finesse if the owner is currently being intitialized. Before, we used to at least find its decls if we were nested in there scope...

**Comment by som-snytt** [comment]
@retronym I'll take another look.

Actually `neg/t729.scala` is supposed to compile.  `coerce` is overloaded in the usual way. Nothing is shadowed and both methods are eligible. (The `super.coerce` correctly gives a `Node <: this.NodeImpl`.)  

We'd be wrong to introduce a notion of "implicit shadowing" that is different from ordinary shadowing; that's the history of the issue in a nutshell. 
```
import scala.language.implicitConversions

trait Parser {
  type Node <: NodeImpl
  implicit def coerce(n: NodeImpl): Node = n.self
  trait NodeImpl {
    def self: Node
  }
  trait Link {
    def from: NodeImpl
  }
}

trait ScalaParserAutoEdit extends Parser {
  type Node <: NodeImpl
  implicit def coerce(node: NodeImpl): Node = node.self
  type SN = super[Parser].NodeImpl
  trait NodeImpl extends super[Parser].NodeImpl {
    def self: Node
    def foo = {
      var link: Link = null
      val xxx: NodeImpl = coerce(link.from)  // intended to show that it can be invoked but isn't eligible
      val f: SN => Node = coerce      // the desired implicit is accessible without a prefix
      val yyy: NodeImpl = link.from   // used to fail due to broken notion of "implicit shadowing"
    }
  }
}

```

**Comment by som-snytt** [comment]
I had forgotten I'd previously looked at the test; instead I re-analyzed for the other ticket. Now I'll have to review retronym's remarks here again, on my 18-month cycle.

**Comment by som-snytt** [comment]
I'm falling behind, now I'm on a 24-month cycle.

**Comment by som-snytt** [comment]
Probably @martijnhoekstra didn't intend to reopen this. See https://github.com/scala/scala/pull/8109 Oh, I see, instead of the laugh emoji they hit open.

**Pull request closed without merging**
