### PR TITLE
Spec improvements

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
- adopted the typography of the PDF spec
- adopted the ideas of @gourlaysama regarding the TOC staying above on small screens
- made the layout reactive (changes at 1400px width or horizontal viewing)
- limited the content width to ~120 characters to ease reading
- eliminated the index page
- added the old changelog
- adaptive font size of chapter bar
- add an interactive outline/scrollbar to use the space on the right side

Preview is here: http://oxnrtr.de/scala-spec/05-classes-and-objects.html

WDYT @gourlaysama?

**Comment by lrytz** [comment]
I mostly like having the reactive TOC on the left.
- Not sure if the scroll thingie on the right is all that useful
- Font size in chapter navigation is very small (noted by @gourlaysama on gitter)
- Cannot scroll in TOC on the left (try http://oxnrtr.de/scala-spec/15-changelog.html)

**Comment by soc** [comment]
@lrytz 
- Not sure if the scroll thingie on the right is all that useful

Yes. I just looked for some idea to use the space for something. We can't increase the width of the content much further, so it's basically dead space anyway. I found it to be neat, but if there is something nicer, let's replace it.
- Font size in chapter navigation is very small (noted by @gourlaysama on gitter)

Yes, the font adjusts itself to the width of the window, so that all chapters are always visible. I didn't find a better solution for this. Ideas?
- Cannot scroll in TOC on the left (try http://oxnrtr.de/scala-spec/15-changelog.html)

I'll see how I can fix this! Thanks!

**Comment by soc** [comment]
I reduced the padding in the chapers, so the font should be slightly bigger now.

I reduced the number of subchapters in Changelog. That's certainly not optimal, but making the left scrollable would lose the ability to scroll the content from there.

**Comment by gourlaysama** [comment]
Just a thought: for the sidebar on the right, that would be the perfect place for some meta-information, like comments, additional links, or footnotes (except there aren't even 20 footnotes in the whole spec...)

**Comment by soc** [comment]
@gourlaysama I agree. I'd propose to keep it like it is for now and replace it when we have found a better use for it.

**Comment by soc** [comment]
Needed a rebase due to https://github.com/scala/scala/commit/b4c88b5d33d2e99c2ed78e587e4c492be6e6a22b.

**Comment by adriaanm** [comment]
Nice! The back/forward button does not work when the anchor points to a section. To reproduce, navigate by clicking on links in the per-page TOC menu and then hit back/forward.

I think it would also be nice to keep the macro TOC as a landing page.

**Comment by soc** [comment]
Ok, this is weird ... looks like one has to press back/forward twice. Does someone with more JavaScript knowledge see the issue (before I start digging into it)?

Do you want a custom page, or just the Preface to stand in as a landing page?

**Comment by adriaanm** [comment]
Either is fine with me. Either the old preface + toc or just the toc and keep the preface as chapter 0 :-)

Could I throw in one more request? I would love a button on top of each page that says "edit in github" instead of the current link at the old preface.

**Comment by soc** [comment]
@gourlaysama @adriaanm Better? http://oxnrtr.de/scala-spec/ I adopted the design regarding the GitHub link from scala-lang.org.

**Comment by adriaanm** [comment]
LGTM! Beautiful! (Nitpick: the kerning is a bit off for me, see e.g., the `T` overhanging the `y` in kerning)

**Comment by soc** [comment]
@adriaanm Weird, it looks right on my system. T and y are a bit further apart, and most importantly, they aren't touching. Are you by chance using some kind of Apple font renderer? (OSX, iOS, ...)?

**Comment by adriaanm** [comment]
yep, chrome on OS X -- ah well

**Comment by adriaanm** [comment]
It looks fine using Georgia -- maybe stick to that?

**Comment by soc** [comment]
The problem is that Georgia has an incompatible x-height with the mono-spaced font. I really looked for decent replacements right in the beginning before I made the choice, but I ended up with exactly the same font choices the original spec made, because it's one of the very few combinations that work (and have non-commercial licenses).

Even just finding a mono-spaced font which works well inside text is a huge issue. There are plenty of fonts if one needs "just" a mono-spaced font, but mono-spaced + text font is hard.

I'd propose keeping it this way, and looking into the various webkit-related CSS properties (I think there are a few to change anti-aliasing).

Also, don't merge it yet, looks like I broke the TOC links completely now. JavaScript ... what a mess.

**Comment by adriaanm** [comment]
Ok, I wasn't aware. Thanks for looking into it!

**Comment by soc** [comment]
I just checked it, I was wrong: It wasn't the x-height, but the general glyph-width. Georgia is more condensed than the Utopia font.

**Comment by soc** [comment]
Now I just need to debug some third-party library with open bugs from 2013 with exactly this issue caused by yet-another library copy-and-pasted into the one I'm using.

**Comment by lrytz** [comment]
@soc do you think it's possible to allow scrolling in the TOC pane on the left when it doesn't fit in the browser height?

**Comment by soc** [comment]
@lrytz Scrolling should work properly now (although I had to move the scrollbar to the left, to prevent it from disappearing behind the main element.

@adriaanm All links should work now. ... I was soooo close to throwing it all away and implementing these third-party libraries in Scala.js ... but it should work now.

Minor nitpick: Is it possible to tell Jekyll how the anchors should be named? Would it be possible to prefix the anchors in lower hierarchies with the name of the parent heading to prevent it from clashing?

**Comment by smarter** [comment]
- Clicking on '5 Eta Expansion' in the menu on the left on http://oxnrtr.de/scala-spec/06-expressions.html does not link to '6.26.5 Eta Expansion' but instead link to the paragraph named 'Eta Expansion' in '6.26.2 Method Conversions'
- It's a matter of opinion, but I think that the outline on the right is distracting and not very useful: the menu on the left is already an outline. White space is fine, having some visual breathing room is nice (look at the design of github for example).

**Comment by adriaanm** [comment]
Getting close, @soc! Thanks for taking a JavaScript for the team ;-)

+1 on the breathing room on the right

**Comment by adriaanm** [comment]
I don't think we can configure anchor naming, sadly.

**Comment by soc** [comment]
@adriaanm Ok, removed it.

@smarter Yes, that's why I asked if the anchor naming scheme for headings can be adapted. Otherwise we need to go through the whole spec and rename headings. That's one thing I'd like to avoid, because it is easy to introduce a heading which conflicts with an existing one in future edits. I'd like to explore different options (outside of this PR) before throwing the towel.

**Comment by lrytz** [comment]
LGTM!

**Comment by adriaanm** [comment]
LGTM! Thanks for polishing!

I'd like to see follow-up PRs (at some point) for:
- font tweaking on mac/(...?)
- rename anchors to make them unique or some other workaround
- hide link menu when there are no subsections

**Comment by retronym** [comment]
@soc We've lost the permalink anchors as a result of this change. See the references to `octicons` in the diff. Did you have trouble integrating them into the new layout, or was this an oversight?

**Comment by soc** [comment]
@retronym This was unintentional ... I'll need to have a look what that did before, I wasn't really aware that we lost something.

**Comment by adriaanm** [comment]
I think the issue is that we used to get a little anchor to show you can deep-link into the spec using the id of the Hn node. The ids are still there ([example](http://www.scala-lang.org/files/archive/spec/2.11/08-pattern-matching.html#variable-patterns)), but the indicator isn't: screenshot <-- example from the [README](https://github.com/scala/scala#handy-links)

**Comment by adriaanm** [comment]
That little linked chain is gone from the spec when you hover over headings.

**Comment by soc** [comment]
Ah right! Thanks!

**Pull request merged**
