### PR TITLE
Make the CharSequence wrappers in Predef non-implicit, for JDK 15

### LINKED ISSUE #12172: JDK 15: new JDK method means we can't call "isEmpty" on an Array[Char] due to ambiguous implicit conversions and can't compile scala.collection.mutable.StringBuilder
## reproduction steps

run `sbt compile` in current 2.13.x branch
https://github.com/scala/scala/tree/8c86b7d7136839538cca0ff8fca50f59437564c0

## problem

```
scala/scala/src/library/scala/collection/mutable/StringBuilder.scala:41:13: cannot override a concrete member without a third member that's overridden by both (this rule is designed to prevent ``accidental overrides'')
[error] override def isEmpty: Boolean (defined in trait SeqOps)
[error]   with <defaultmethod> def isEmpty(): Boolean (defined in trait CharSequence)
[error] final class StringBuilder(val underlying: java.lang.StringBuilder) extends AbstractSeq[Char]
[error]             ^
```

`java.lang.CharSequence` has `isEmpty` method since JDK 15

https://github.com/openjdk/jdk/commit/113c48f5da32b26a4f820ccd0e43dae3eba7b73e

```
Welcome to Scala 2.13.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
Type in expressions for evaluation. Or try :help.

scala> classOf[scala.collection.mutable.StringBuilder].getInterfaces
val res0: Array[Class[_]] = Array(interface scala.collection.mutable.ReusableBuilder, interface scala.collection.mutable.IndexedSeq, interface java.lang.CharSequence, interface java.io.Serializable)
```

### PR DESCRIPTION
**Pull request by dwijnand**
This change is binary compatible, but not source compatible. Users will need to update callsites to explicitly convert to `CharSequence`, since the conversions are no longer implicit.

* `ArrayCharSequence` is no longer needed and will be deprecated in 2.12.13 and 2.13.5. Instead, use `java.nio.CharBuffer.wrap` to convert an `Array[Char]` to a `CharSequence`.
* `SeqCharSequence` remains useful, but now must be explicitly constructed.

Why was this necessary? In JDK 15 CharSequence has an isEmpty method with a default implementation, which clashes with our Array[Char]#isEmpty, IndexedSeq[Char]#isEmpty, as well as our StringBuilder and reflect's Name.

Fixes https://github.com/scala/bug/issues/12172

### CODE REVIEW

**Comment by smarter** [comment]
> IndexedSeq[Char]#isEmpty

isEmpty is defined directly on Seq, so I don't think that an implicit conversion also defining isEmpty leads to a clash.

**Comment by dwijnand** [comment]
I added it mostly to get rid of the other way CharSequence, which we don't control, can break us.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2065/
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2066/

**Comment by SethTisue** [comment]
scala-parser-combinators needed changes: https://github.com/scala/scala-parser-combinators/pull/306

**Comment by SethTisue** [comment]
scala-parser-combinators needed changes: https://github.com/scala/scala-parser-combinators/pull/306/files

**Comment by SethTisue** [comment]
```
[scalatest] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.17/project-builds/scalatest-9ef9d9cffb656ae59e49995e0000b4e93882aa5d/jvm/refspec/src/main/scala/org/scalatest/refspec/RefSpec.scala:1386:39: polymorphic expression cannot be instantiated to expected type;
[scalatest] [error]  found   : [B >: Char]Array[B]
[scalatest] [error]  required: CharSequence
[scalatest] [error]       val bytes = Codec.toUTF8(toHash.toArray)
[scalatest] [error]                                       ^
```

**Comment by SethTisue** [comment]
do we want to deprecate these and suggest people write `new ...`?

```
   def SeqCharSequence(sequenceOfChars: scala.collection.IndexedSeq[Char]): SeqCharSequence = new SeqCharSequence(sequenceOfChars)
   def ArrayCharSequence(arrayOfChars: Array[Char]): ArrayCharSequence = new ArrayCharSequence(arrayOfChars)
```

in the `ArrayCharSequence` case, note that you can call `java.nio.CharBuffer.wrap` instead. which tempts me to suggest we deprecate `ArrayCharSequence` in its entirety

**Comment by smarter** [comment]
> do we want to deprecate these and suggest people write new ...?

Bit of a mixed message with http://dotty.epfl.ch/docs/reference/other-new-features/creator-applications.html :)

> in the ArrayCharSequence case, note that you can call java.nio.CharBuffer.wrap instead. which tempts me to suggest we deprecate ArrayCharSequence in its entirety

Yep that's what I suggested in the previous PR too.

**Comment by SethTisue** [comment]
We'll have better community build results by tomorrow (run 2067).

**Comment by dwijnand** [comment]
> > do we want to deprecate these and suggest people write new ...?
> 
> Bit of a mixed message with http://dotty.epfl.ch/docs/reference/other-new-features/creator-applications.html :)

Just `SeqCharSequence(myCharList).substring(..)` without the `new`.

I agree to deprecating `ArrayCharSequence` and pointing to CharBuffer wrap.

**Comment by SethTisue** [comment]
community build results for 2.13.4-bin-0230f94-SNAPSHOT are in.

my conclusion: this stuff is rarely used. it is okay to go ahead with this.

details follow:

~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2065/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2066/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2067/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2068/

scala-parser-combinators needed changes to 3 call sites in 3 different source files: https://github.com/scala/scala-parser-combinators/pull/306 — it is using `SeqCharSequence` in a way that actually kind of makes sense in my glance at it (namely, to avoid copying)

scalatest was just using `ArrayCharSequence` in a single call site in a single source file, and only in an currently silly/unnecessary way (perhaps justified at some point in the distant past? idk): https://github.com/SethTisue/scalatest/commit/2f6a176cdc95890efa1c8cb3de2e6485c8e4b48f

I had to fix those (and, separately, scalatest-3-0) in order to get a usable run.

The remaining failures are: `FAILURES (UNEXPECTED): twirl,scalafix,scoverage; BLOCKING DOWNSTREAM: twirl (12), scalafix (1)`

the twirl failure is actually about that the exhaustivity changes and not about this. so that leaves scalafix and scoverage

in scalafix, four call sites in a single source file is affected; in scoverage, two call sites in a single source file

this all seems well within the range of acceptability to me

**Review by SethTisue — APPROVED** [review]

**Comment by smarter** [comment]
One thing that I don't think has been discussed: should this be backported to 2.12? Or perhaps the original idea of hacking implicit search would be more appropriate there? Or Java 15+ should just be declared unsupported? (Might be problematic given that Java 17 is not that far away and will be an LTS release).

**Comment by dwijnand** [comment]
Yeah, we'll want to backport this to 2.12, though it's not as critical as 2.13.4 for it to be in 2.12.13, IMO.  PR's welcome.

**Comment by lrytz** [comment]
> Yeah, we'll want to backport this to 2.12

I agree.

> `SeqCharSequence(myCharList).substring(..)` without the `new`.

A good replacement would be `asJavaCharSequence` in https://github.com/scala/scala/blob/2.13.x/src/library/scala/jdk/CollectionConverters.scala, but binary compatibility. scala-library-next? Or a ticket to remember for the next std lib?

> I agree to deprecating `ArrayCharSequence` and pointing to CharBuffer wrap.

That wasn't done in the end, it seems?

**Comment by SethTisue** [comment]
> > I agree to deprecating ArrayCharSequence and pointing to CharBuffer wrap.
> That wasn't done in the end, it seems?

At this point, I think we should let that slide for 2.12.13 / 2.13.4, but get it in the next round.

But first I want to ask @sjrd: does Scala.js support `java.nio.CharBuffer.wrap`? Because if it doesn't, that could be a reason not to deprecate `ArrayCharSequence`.

**Comment by smarter** [comment]
looks like it does: https://github.com/scala-js/scala-js/blob/effa32e3c43d04d98df6ec0974bcc55500b5b7d1/javalib/src/main/scala/java/nio/CharBuffer.scala#L26

**Comment by SethTisue** [comment]
PR deprecating `ArrayCharSequence` on 2.12.x, also to be forward-merged (at some point) to 2.13.x: #9321 

PR backporting this PR to 2.12.x: #9322

**Comment by sjrd** [comment]
> But first I want to ask @sjrd: does Scala.js support `java.nio.CharBuffer.wrap`? Because if it doesn't, that could be a reason not to deprecate `ArrayCharSequence`.

Yes, it's supported. I even already used it as a replacement in one of our tests that was relying on `ArrayCharSequence`. ;)

**Comment by retronym** [comment]
Another way the source incompatibility can be experienced, for the record.

```
Welcome to Scala 2.12.12 (Java HotSpot(TM) 64-Bit Server VM, Java 14).
Type in expressions for evaluation. Or try :help.

scala> object X { val sb = new StringBuilder(); println(sb.length())}
defined object X
```

```
Welcome to Scala 2.12.13-20201208-103432-471ea9d (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> object X { val sb = new StringBuilder(); println(sb.length())}
<console>:11: error: Int does not take parameters
object X { val sb = new StringBuilder(); println(sb.length())}
                                                          ^
```

**Pull request merged**
