### PR TITLE
[backport] no longer warns on calls to vampire macros

### PR DESCRIPTION
**Pull request by xeno-by**
As eloquently elaborated and cleverly named by Travis Brown, macros
defined in structural types are useful:
http://meta.plasm.us/posts/2013/07/12/vampire-methods-for-structural-types/.

However, since such macros are on the intersection of a number of language
features, as usual, there are bugs.

This commit fixes an unwanted interaction of macros defined in structural
types with the scala.language.reflectiveCalls guard. Since macro calls
aren't going to be carried to runtime, there's no need to warn about them.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by soc** [comment]
I first read "An eloquently elaborated and cleverly named Travis Brown [...]" ... looks good to me otherwise. :-)

**Comment by xeno-by** [comment]
Ping @retronym

**Comment by retronym** [comment]
LGTM

**Pull request merged**
