### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by NthPortal**
Add CODEOWNERS file with entries for NthPortal.

### CODE REVIEW

**Comment by NthPortal** [comment]
Opening this PR to start a discussion on whether or not we want to go down this route.

**Comment by SethTisue** [comment]
according to https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners , the main effect of this is:
 
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own

(There's also some behavior if "someone with admin or owner permissions has enabled required reviews", which we don't have.)

This seems helpful and non-intrusive to me. (Caveat: I haven't experienced this firsthand in other repos.)

It seems appropriate to me for us to use this for some files that do have obvious de-facto reviewers-of-first-recourse. The files in this PR are good examples, another good example would be @viktorklang and `src/library/scala/concurrent`. We wouldn't make any effort to assign owners to the vast majority of files.

**Comment by Ichoran** [comment]
It seems like code owners is the wrong concept for the Scala codebase.  It's a big project; people come and go.  The people who are responsible now aren't necessarily the ones who created it originally.  The idea of ownership in the project-management sense still survives, but it can be confused with the idea of authorship (and of legal ownership).  If it's called "CODEOWNERS" but it's an automatic hook to alert someone with expertise who is active, sure.  Especially if we can say that this is what it actually is.

Otherwise, I'd call the file something else, like EXPERTICE or somesuch, if it's just for us to read.

I'm not convinced that we can actually codify this better than we can just handle on the fly.  But it doesn't seem like it's likely to hurt much, and if it just gets stale and isn't helpful, it's not hard to delete.

**Review by dwijnand — APPROVED** [review]
Let's give it a shot and tear it out if it becomes stale or a PITA.

**Comment by NthPortal** [comment]
the real question here is who wants to put their name on `Ordering`

**Comment by NthPortal** [comment]
> but it's an automatic hook to alert someone with expertise who is active, sure

that's my primary motivation

**Comment by diesalbla** [comment]
Along the way, could we also request specific reviewers for the Collections library, as well as for the concurrent library (I guess @viktorklang would be a suitable one).

**Review by diesalbla — APPROVED** [review]

**Comment by NthPortal** [comment]
do you want me to add more names/files in this PR, or another?

**Comment by diesalbla** [comment]
We can do it in another PR. :)

**Pull request merged**
