### PR TITLE
SI-5920 enables default and named args in macros

### PR DESCRIPTION
**Pull request by xeno-by**
Hopefully third time's a charm. review @retronym

### CODE REVIEW

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
The IDE also has problems with names/defaults, and would benefit from being able to see the original application. So I think we can come up with something that has value beyond macros.

But, I'd really like to compare the "undo" approach with an alternative that changes names/defaults itself to store an attachment on the desugared application that would contain a record of original order of the arguments and which ones called on defaults.

Here's the related IDE ticket: https://github.com/scala-ide/scala-refactoring/issues/44

I'm trying to dig up a branch of mine that prototyped the changes to names/defaults.

**Comment by lrytz** [comment]
@xeno-by should we close this for now, while investigating the approach using attachments?

**Comment by xeno-by** [comment]
Ohhhh man! Do you think it would be possible to merge this as is, so that it makes it into 2.11.2? Then I would be glad to reimplement undoNamesDefaults with attachments and submit it as a follow-up pullrequest.

**Comment by retronym** [comment]
There is also question of performance in hot paths in the typer. I don't think this one makes it past the cost/benefit threshold yet.

**Comment by xeno-by** [comment]
Speaking of performance testing for this pull request, you previously mentioned that you had something in mind. Could you share?

**Comment by retronym** [comment]
Compare warmed up times and Yourkit profiles of compiling, say, scalap before and after.

**Comment by xeno-by** [comment]
@retronym How do you reliably measure compilation times?

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@retronym Also, by "performance in hot paths of the typer" do you mean just https://github.com/scala/scala/pull/3753/files#diff-4eab1aad4533a31c10565971e90f73eaL1099 or there's something else?

**Comment by retronym** [comment]
Reassigning to 2.11.3. As we've discussed, I'd like to make this work by preserving information in `NamesDefaults`, rather than by reconstructing it later.

**Comment by retronym** [comment]
I'm going to close this PR rather than leaving it in limbo. I still a in favour of the feature, and hope we get it back for the next minor release.

**Comment by xeno-by** [comment]
What would be our plan here? Who does what?

**Comment by retronym** [comment]
I think the fastest approach would by for you and @lrytz to spend an afternoon together and find the right way to hook into `NamesDefaults`.

**Comment by retronym** [comment]
Unfortunately, I've been unable to locate my branch that attempted this.

**Pull request closed without merging**
