### PR TITLE
Repl should early-init its phase global

### PR DESCRIPTION
**Pull request by som-snytt**
They're threatening to throw NPE if your SubComponent doesn't
have an early definition of global, so change it now in REPL.

Also, contribute replPhase as an internal phase.

### CODE REVIEW

**Comment by som-snytt** [comment]
It would be nice if Jenkins didn't only annotate with a green check, but occasionally would award a gold star, as in grammar school. :star: or even :star2:

**Comment by retronym** [comment]
Does this serve any purpose other than the line of logging?

I can't reverse engineer any meaning from it. It was added in https://github.com/scala/scala/commit/4a6f54b5f16b3179b23a44f2f1d83f080e218f72#diff-c451007ede711ff9613880cc2335b13bR40

Doubleplusshiny star on offer if you can just delete it.

**Comment by som-snytt** [comment]
I could. In my repl from a couple of years ago, where the compiler does script wrapping in a distinct phase and repl replaced that phase for templating/wrapping, that was the work done by the repl phase. Actually, it was a separate component. I always assumed repl would get back to contributing a phase.

https://github.com/som-snytt/scala/blob/8a799b42f43eb0f27955574ad38d25dcb28724b0/src/repl/scala/tools/nsc/interpreter/IMain.scala#L246

**Comment by som-snytt** [comment]
I noticed ammonite had a conflict by requiring to run right after typer. At least old repl was flexible that way.

**Comment by retronym** [comment]
LGTM. You've got to be quick on the draw to delete dead code with @soc around! :smile:

**Comment by retronym** [comment]
I've rebased this to squash the commits in #4821. I also removed the custom typer in the same spring-cleaning spirit.

**Pull request closed without merging**
