### PR TITLE
Small implicit optimizations, and SI-7678 RunDefinitions

### PR DESCRIPTION
**Pull request by retronym**
The first two commits should be pretty uncontroversial. They speed up
implicit search a little.

I then tried to cache per-run some member symbols that were being
looked up and stuffed into a map per-implicit search. This led to the 
introduction of RunDefinitions, which in turn let me address SI-7678,
in which the presentation compiler shows up places where we incorrectly
were caching member symbols per-global, rather than per-run.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski  @xeno-by 

Opinions, cautionary tales, pithy comments from @paulp also welcome.

**Comment by paulp** [comment]
No opinions, cautionary tales, or pithy comments to be had - looks sensible enough to me. I went with option four, scooby doo reference.

**Comment by gkossakowski** [comment]
@JamesIry: cursory look suggests this is fine but I'd like to educate myself a little bit more when it comes to initialization and caching issues as I wasn't aware of that particular case. I'm offline tomorrow so I'll respond only during the weekend or on Monday (worst case).

**Comment by retronym** [comment]
No hurry, I can run you through this next week if you don't get a chance earlier.

**Comment by JamesIry** [comment]
ping @gkossakowski

**Comment by gkossakowski** [comment]
@retronym educated me on those issues so I can confidently review this PR. However, the PR doesn't merge anymore. @retronym rebase and I'd be happy to review it.

**Comment by retronym** [comment]
@gkossakowski rebased.

**Comment by gkossakowski** [comment]
LGTM.

Caching is hard, especially when life cycles and invalidation contracts are not clearly spelled out.

**Pull request merged**
