### PR TITLE
Added the method to read implicit value if option is empty

### PR DESCRIPTION
**Pull request by technical-harsh90**

### CODE REVIEW

**Comment by technical-harsh90** [comment]
I have signed the Scala CLA.

**Comment by SethTisue** [comment]
is this equivalent to `.getOrElse(implicitly)`?

**Comment by technical-harsh90** [comment]
@SethTisue In some situations, but not most of the times.
Have a look at below, when we have chain of optional values to fetch,

```
val dataOpt: Option[List[Option[String]]] = Some(List(Some("A"), Some("B"), None))

dataOpt.getOrElse(implicitly[List[Option[String]]]).map { listOfString =>
      listOfString.getOrElse(implicitly[String])
    }

dataOpt.byImplicit.map { listOfString => listOfString.byImplicit }
```

Not only in this area, but also it works with well while working with optional values at Json parsing also.

Example : Suppose we are getting large json structure from an Api, and we have to follow some structure, where we know that, in case any particular key is not found, then we have to return some default value everywhere. In this case we can directly use this method in short.

**Comment by SethTisue** [comment]
our existing methods such as `getOrElse` allow a supertype, rather than being restricted to `A` specifically; it's `def getOrElse[B >: A](default: => B): B`, not `def getOrElse(default: => A): A =`. should this one also?

**Comment by SethTisue** [comment]
@technical-harsh90 interested in returning to this?

**Comment by sjrd** [comment]
I'm not convinced by this one. At the very least, it should come with a good motivation.

**Comment by dwijnand** [comment]
Same.  It's an interesting idea, but I've never seen code that could use this method.

**Comment by lrytz** [comment]
I agree. Closing.

**Pull request closed without merging**
