### PR TITLE
SI-6503 Fix doctype, remove processing instructions, ...

### PR DESCRIPTION
**Pull request by soc**
... and add alt attributes to image tags.

### CODE REVIEW

**Comment by soc** [comment]
Index page and content iframe pass validation as HTML5 on both http://validator.w3.org/ and http://html5.validator.nu/.

**Comment by retronym** [comment]
Can you please improve the commit message? The subject should fit on one line, and give a little context. e.g 

```
Improve generated HTML for Scaladoc

  - fixed the doctype, it was incorrectly set to ..., now it is ....
  - ...
```

**Comment by soc** [comment]
@retronym Yes, will do that.

**Comment by soc** [comment]
@retronym Updated the commit message, I hope this one is better.

**Comment by retronym** [comment]
Thanks, that commit message is much more explanatory.

Perhaps you could publish the generated site so reviewers (@heathermiller / @vladureche) could check the results with a few browsers?

**Comment by soc** [comment]
@retronym I'm on it.

**Comment by soc** [comment]
@retronym, @heathermiller, @vladureche: It's still uploading, but most things should already be available: http://oxnrtr.de/scala/docs/

**Comment by JamesIry** [comment]
What's the status on this PR?

**Comment by soc** [comment]
I rebased it against current trunk, @JamesIry I think it is still waiting for feedback from @heathermiller /@vladureche.

**Comment by soc** [comment]
@JamesIry/@heathermiller /@vladureche: Is there anything missing to get this moving?

**Comment by retronym** [comment]
@soc Things are a little slow right now in preparation for Scala Days. Please bear with us for a tiny bit longer.

**Comment by retronym** [comment]
In the meantime, could you please address my review comment? The commit message should provide more context for the casual observer about what was wrong, what you've changed, and why that's right.

**Comment by soc** [comment]
@retronym Updated, I hope it's better now.

**Comment by retronym** [comment]
LGTM. I'm going to merge now and encourage @heathermiller / @vladureche to review this one post-factum.

**Comment by VladUreche** [comment]
hi @soc, sorry for the delay in the review, html is not really my area. The patch LGTM, post-merge.

**Pull request merged**
