### PR TITLE
[nomaster] macro expansions are now auto-duplicated

### PR DESCRIPTION
**Pull request by xeno-by**
The fix still requires macro developers to be careful about sharing trees
by references, because attributed DefTrees will still bring trouble.

However this is an improvement, because it doesn't make matters worse
and automatically fixes situations similar to one in the test.

A much more thorough discussion with a number of open questions left:
http://groups.google.com/group/scala-internals/browse_thread/thread/492560d941b315cc

Was fixed ages ago in master in one of the paradise backports.
Never got to 2.10.x, but it's very useful, so I'm backporting it now.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
I'm a little bit scared of this one for 2.10.x. Let's discuss the risks when I'm next in Lausanne (wed + thur this week.)

**Comment by xeno-by** [comment]
Yes, let's do that.

**Comment by JamesIry** [comment]
@retronym, @xeno-by please update when you have figured it out. RC1 is approaching.

**Comment by JamesIry** [comment]
Ping

**Comment by xeno-by** [comment]
Jason and I have taken a look and made sure that duplicators only recreate
trees and don't do anything suspicious to symbols and types. After that
Jason told me that we just need a test case, and then it would look good. I
will submit a test today evening and then, from what I understand,
everything should be fine. Do we still make it into 2.10.3?

**Comment by xeno-by** [comment]
@retronym I've just updated the PR with a test that fails under 2.10.x and passes thanks to this patch.

**Comment by JamesIry** [comment]
@retronym wanna give it a final yay or nay for 2.10.3?

**Comment by retronym** [comment]
LGTM. Okay for 2.10.3

**Pull request merged**
