### PR TITLE
Prepare for the 2.12.0-M1 release

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @adriaanm

**Comment by lrytz** [comment]
I've seen this spurious error three times in this PR: once in validate-test, twice in integrate-ide:

```
Archiving artifacts
ERROR: Failed to archive artifacts: build/junit/TEST-*,build/osgi/TEST-*
java.io.IOException: Failed to extract /home/jenkins/workspace/scala-2.11.x-validate-test@3/transfer of 87 files
    at hudson.FilePath.readFromTar(FilePath.java:2299)
    at hudson.FilePath.copyRecursiveTo(FilePath.java:2208)
    at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:61)
    at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:219)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
```

**Comment by lrytz** [comment]
And then other times I hit [SI-9264](https://issues.scala-lang.org/browse/SI-9264), here's an example: https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/687/console

```
[quick.compiler] error: symbol value x2#821102 does not exist in scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1, which contains locals value x#821118,value x1#821099,value subst#534851,value subst#534599,value okArgs#534598,value okParams#534597,value x#821090,value o7#821098,value x1#821085,value x$12#534596,value x#821080,value x2#821077,value x1#821076,value x$10#534759,value x$11#534758,value targs#534595,value tvars#534540,value itree3#534433,value x#821049,value x2#821046,value x1#821045,value x#821025,value x1#821023,value x#821035,value o7#821043,value x1#821030,value itree2#534432,value ex#534897,value itree1#534287,value implicitMemberName#534318,variable eqEqTemp$13#1297688,value itree0#534286,variable eqEqTemp$12#1297685,value isScalaDoc#534285,value isLocalToCallsite#534283,value info#534282.
```

**Comment by adriaanm** [comment]
Ugh! I'll check the logs for the io error. Maybe disk space or network problem. UPDATE: no signs of trouble on the machines themselves. Working on moving jenkins master to a bigger machine this week, so hopefully won't run into disk space issues for sure soon enough.

**Comment by retronym** [comment]
We should run community build on this one, too.

**Comment by lrytz** [comment]
The `Archiving artifacts ERROR` keeps coming back on rebuilds. Everything else is green, so I think we can ignore this failure.

Running a community build here: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/163/parameters/

```
[scala:error] java.lang.RuntimeException: Cannot find artifacts dir for: org.scala-lang#scala-actors
```

**Comment by lrytz** [comment]
```
[scala:error] java.lang.RuntimeException: Cannot find artifacts dir for: org.scala-lang#scala-actors
```

**Comment by retronym** [comment]
Looks like it dbuild builds in some assumptions about scala-actors:

```
  /code/distributed-build % git grep \"scala-actors\"
support/src/main/scala/com/typesafe/dbuild/support/scala/ScalaBuildSystem.scala:        Seq(ProjectRef("scala-library", "org.scala-lang"), ProjectRef("scala-compiler", "org.scala-lang"), ProjectRef("scala-actors", "org.scala-lang"))),
support/src/main/scala/com/typesafe/dbuild/support/scala/ScalaBuildSystem.scala:      Project("scala-actors", "org.scala-lang",
support/src/main/scala/com/typesafe/dbuild/support/scala/ScalaBuildSystem.scala:        Seq(ProjectRef("scala-actors", "org.scala-lang")),
support/src/main/scala/com/typesafe/dbuild/support/scala/ScalaBuildSystem.scala:        Seq(ProjectRef("scala-library", "org.scala-lang"), ProjectRef("scala-actors", "org.scala-lang"))))
```

**Comment by lrytz** [comment]
Thanks, I created https://github.com/typesafehub/dbuild/issues/164

**Comment by lrytz** [comment]
It might be a few days until dbuild is updated for the removed modules, see https://github.com/typesafehub/dbuild/issues/164#issuecomment-95946695.

**Comment by adriaanm** [comment]
Could you comment on how the removal of some of these tests was decided? Were they all specifically checking scala-actors, or could there be collateral damage because some test happened to use a class from scala.actors to trigger a bug not related to the actors?

Otherwise, LGTM! Thanks for clarifying the docs in the process!

**Comment by lrytz** [comment]
Thanks or asking, I should have mentioned the removed tests. I checked the JIRA tickets for those removed, they are testing the actors library. There's a small number of tests that used the actors library to test something else, I adapted those, e.g., https://github.com/lrytz/scala/commit/5b73e75943dd89dabda84b0fc3a651837c4a2113#diff-6a840e29218519c40dc5c882254a19ff and https://github.com/lrytz/scala/commit/5b73e75943dd89dabda84b0fc3a651837c4a2113#diff-9dd58d339244667e7138a0e96d0ba3ab.

**Comment by adriaanm** [comment]
LGTM! Excellent!

**Pull request merged**
