### PR TITLE
Adjust ArrayDeque resizeIfNecessary

### PR DESCRIPTION
**Pull request by isaacl**
We only need to grow if len >= array.length

### CODE REVIEW

**Review by diesalbla — APPROVED** [review]

**Review by Ichoran — APPROVED** [review]
Looks fine, but it's hard to run every use case in my head.  Have you checked what tests exist to verify the behavior?

**Comment by isaacl** [comment]
@Ichoran The tests for ArrayDeque are sparse.  But generally this structure uses a single null sentinel element, so that start is only equal to end when the structure is empty:
```scala
def isEmpty = start == end
```

If `len == array.length - 1`, there is still a sentinel spot, and we do not need to resize. So the check should only return true if `len >= array.length`

**Comment by Ichoran** [comment]
@isaacl - Thanks, yeah, that was my understanding also.  What I couldn't quite convince myself of was that every use site actually obeyed that single-sentinel-spot logic.  So it looks good to me as far as I can evaluate it, but I'm not super-confident that I understood how it was used in every spot.

**Comment by isaacl** [comment]
@pathikrit @julienrf could one of you take a look?

**Comment by pathikrit** [comment]
Sorry I should have documented that `-1` better but FWIW, this is the commit that introduced it: https://github.com/pathikrit/collection-strawman/commit/0c470561ba8c2bd10c5857062564f62cd0024fe8

I vaguely remember it had something to do with the sizeHint in the same commit (that may or may not be needed). If tests pass, then LGTM.

Also, these were the original tests which prove that pits `ArrayDeque` against `ArrayBuffer` - it would be better if we add this back:
https://github.com/pathikrit/collection-strawman/blob/0519263c9fe8fb57820b01a76852a0dd97348786/benchmarks/time/src/main/scala/strawman/collection/mutable/ArrayDequeBenchmark.scala

**Comment by isaacl** [comment]
> If tests pass, then LGTM.

tests pass :-)

**Pull request merged**
