### PR TITLE
Regex.unapplySeq should not take Any (Fixes SI-6406)

### PR DESCRIPTION
**Pull request by som-snytt**
This deprecates unapplySeq(Any) and adds overloaded
unapplySeq(CharSequence) and unapplySeq(Match), with the
putative advantage that you can't try to extract the unextractable.

Regex is massaged so that the underlying Pattern is primary,
rather than the String-valued expression.  Regex and its
unanchored companion (I almost wrote unmoored) share a
Pattern object, so that unapplySeq(Match) can easily test
whether the Match was generated by this Regex; in that case,
the match result is used immediately, instead of reapplying
the regex to the matched string.

The documentation is massaged to reflect unanchored and also to
align with the underlying terminology, e.g., "subgroup" really
just means "group."

Review by @jsuereth

### CODE REVIEW

**Comment by som-snytt** [comment]
Needs for review for consensus that it's a good idea, and that deprecation is correct.

**Comment by paulp** [comment]
It seems like a reasonable idea, but it is easy for a change like this to have unintended consequences. I don't think it would be wise to merge this for 2.10.0.

**Comment by gkossakowski** [comment]
So this has to go into master, right? I'm closing it but please respond so we can still incorporate @som-snytt's work.

**Comment by som-snytt** [comment]
But this was a PR against master, right?

**Comment by paulp** [comment]
Sorry, I'm an idiot.  2.10.x on the brain.

**Comment by som-snytt** [comment]
There's a not-so-subliminal green bar that says Milestone 2.10, but I don't pretend to be a github power user.

**Comment by gkossakowski** [comment]
When it comes to Milestone 2.10 that's been another idiot in neighborhood. I removed it.

**Comment by paulp** [comment]
I think there's no time like the present.

**Comment by som-snytt** [comment]
I was doing some matching and had forgotten that this change hadn't made it into the current release, what with the Labor Day push to get it out before New Year's.  (Calendar year, not Jewish New Year.)

The reason @paulp had 2.10 on the brain was that the deprecation is wrongly set for 2.10.0.  I must have forgotten that by the time it came up for review.  Does this not rise to the level of a ticket?

I had a feeling that my slice-of-the-2.10-pie stats were a little low.

**Comment by SethTisue** [comment]
thanks. this caught some bad code of mine.

**Pull request merged**
