### PR TITLE
sbt 1.6 (was 1.5)

### PR DESCRIPTION
**Pull request by SethTisue**
not for merge until 1.6 final, but let's see if any issues turn up

### CODE REVIEW

**Comment by SethTisue** [comment]
fyi @eed3si9n: this experiment was successful (Jenkins is green)

the Travis-CI failure is for an unrelated reason, namely https://github.com/scala/scala-dev/issues/788

**Comment by eed3si9n** [comment]
Great news.

**Comment by SethTisue** [comment]
reopening temporarily as a way to test https://github.com/scala/scala-dev/pull/789

**Comment by SethTisue** [comment]
seen enough: `[info] welcome to sbt 1.6.0-M1 (Temurin Java 1.8.0_302)`

**Comment by SethTisue** [comment]
Jenkins fails with the following, and it isn't transient:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact org.scala-lang:scala-library:jar:2.13.8-bin-67ec63f-SNAPSHOT in temp (https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/)
```

it seems reasonable to assume that the cause is https://github.com/sbt/sbt/issues/6737 and we should just wait for the next RC. fyi @eed3si9n

**Comment by SethTisue** [comment]
I don't understand why this is failing (on Jenkins only). [The log](https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/15656/console) just has:

```
[error] 18 of 19 test tasks failed:
[error] - junit/testOnly -- +v
[error] - scalacheck/test
[error] - partest run
[error] - partest pos neg jvm
[error] - partest res scalap specialized
[error] - partest instrumented presentation
[error] - partest --srcpath scaladoc
[error] - partest --srcpath macro-annot
[error] - partest --srcpath async
[error] - tasty/test
[error] - osgiTestFelix/test
[error] - osgiTestEclipse/test
[error] - library/mimaReportBinaryIssues
[error] - reflect/mimaReportBinaryIssues
[error] - testJDeps
[error] - testJarSize
[error] - bench/compile
[error] - doc
[error] Failure due to previous errors
[error] (testAll) Failure due to previous errors
```

with no other indication of what went wrong, afaict.

**Comment by SethTisue** [comment]
I can reproduce the problem locally by running `sbt -Dstarr.version=2.13.8-bin-67ec63f-SNAPSHOT` followed by `testAll`. This fails with both 1.5.6 and 1.6.0-RC1, so either the bootstrapped compiler isn't getting published in the first place, or it does publish but then we can't resolve it.

In the log, we see:

`++ sbt -sbt-version 1.6.0-RC1 -Dsbt.override.build.repos=true -Dsbt.repository.config=/home/jenkins/workspace/scala-2.13.x-validate-main@2/scripts/sbt-repositories-config -warn 'setupPublishCore https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/' publish`

but I see no indication of the log of it going wrong. I compared it to a log of a successful run but nothing is different.

Given the existence of https://github.com/sbt/sbt/issues/6737 , I'm not sure it makes sense to troubleshoot further. I suggest we wait until that's fixed and RC2 is published, then try again.

**Comment by dwijnand** [comment]
> either the bootstrapped compiler isn't getting published in the first place, or it does publish but then we can't resolve it.

Likely to be the latter, given https://github.com/scala/scala-dev/issues/801?

**Comment by SethTisue** [comment]
>  scala/scala-dev#801?

hmm, that does seem plausibly related, except I'm not sure why sbt 1.5 vs 1.6 would matter.

**Comment by SethTisue** [comment]
hey @eed3si9n it went green! 🕺

**Comment by SethTisue** [comment]
Closing for now, until the next RC or the final release.

**Comment by eed3si9n** [comment]
nice. thanks for testing this.

**Comment by eed3si9n** [comment]
Dear Jenkins:
retest this please

**Comment by SethTisue** [comment]
We have a 2.12.x version of this PR as well, but I'm leaving this one open since the 2.12 one isn't going to merge forward cleanly.

**Comment by SethTisue** [comment]
(As with other 2.13.x PRs at present, let's not hit "merge" until after 2.13.8 is out, to spare us the trouble of having to make a release branch.)

**Pull request merged**
