### PR TITLE
SI-7969 REPL -C columnar output

### PR DESCRIPTION
**Pull request by som-snytt**
Let `ConsoleReaderHelper.printColumns` print in a vertical
orientation (similar to `ls -C`) instead of horizontally (`ls -x`).

To support the old behavior, add a property `-Dscala.repl.format=across`
where "across" is the presumptive mnemonic for `-x`.

Extend column formatting to make columns only as wide as
their widest element. 

Example that really benefits, witness the skinny columns:

```
scala> math.

BigDecimal                     PartiallyOrdered             cosh      rint
BigInt                         Pi                           exp       round
E                              ScalaNumber                  expm1     signum
Equiv                          ScalaNumericAnyConversions   floor     sin
Fractional                     ScalaNumericConversions      hypot     sinh
IEEEremainder                  abs                          log       sqrt
Integral                       acos                         log10     tan
LowPriorityEquiv               asin                         log1p     tanh
LowPriorityOrderingImplicits   atan                         max       toDegrees
Numeric                        atan2                        min       toRadians
Ordered                        cbrt                         package   ulp
Ordering                       ceil                         pow
PartialOrdering                cos                          random

```

### CODE REVIEW

**Comment by som-snytt** [comment]
Perhaps @retronym or @adriaanm could review.  This includes a unit test for REPL code.  Also, perhaps we could discuss adding expecty to junit testing. I can't do TDD without expecty anymore. It's not obvious to me if that would work better as an external or internal forked dependency.  Did I see a message somewhere that @retronym 's trace macro made a build fail?  Nothing is trivial.

**Comment by JamesIry** [comment]
Every time we add scala dependencies to the build of scala we regret it because bootstrapping is hard. I wouldn't count on expecty ever making into our suite of testing tools so I'd prefer seeing the pending tests moved into the active folders sans the expecty dependency.

**Comment by som-snytt** [comment]
Updated the test without expectytations.

**Comment by adriaanm** [comment]
LGTM -- purdy!

**Pull request merged**
