### PR TITLE
SI-7548 askTypeAt returns the same type whether the file was fully type-checked or targeted type-checked

### PR DESCRIPTION
**Pull request by dotta**
When asking for targeted typecheck, the located tree may have overloaded types
is the source isn't yet fully typechecked (e.g., a select tree for an
overloaded method). This is problematic as it can lead to unknown 'hovers',
broken hyperlinking that suddenly starts working, unresolved ScalaDoc comments,
and similar, in the Scala IDE.

With this commit we are hardening the contract of `askTypeAt` to return the
same type whether the file was fully type-checked or targeted type-checked.
This is done by preventing the typechecker to stop too early if the `located`
tree has an overloaded type.

Unfortunately, there is no easy way to provide a test together with this fix.
The faulty behavior is hard to consistently reproduce, as it depends on timing.
However, I've manually tested this by inserting a `Thread.sleep` just before
typechecking in `Global.backgroundCompile`, and checked that an `askTypeAt` on
an select tree for an overloaded method now does return a fully resolved symbol.

review by @dragos

Is this too risky to backport?

### CODE REVIEW

**Comment by dragos** [comment]
LGTM. It would be good to get one from @odersky too.

**Comment by adriaanm** [comment]
LGTM too -- probably best to ping @odersky in person

**Comment by retronym** [comment]
> Unfortunately, there is no easy way to provide a test together with this fix.
> The faulty behavior is hard to consistently reproduce, as it depends on timing

I would like to hear a more fleshed out theory of why this is the case. What is the source of non-determinism? The race between a full typecheck and the client putting the next work item on the queue to be cause that full typecheck to be interrupted by `checkForMoreWork`?

Can we introduce a testing mode to make things deterministic?

**Comment by adriaanm** [comment]
I'd say this PR is a (completely acceptable) workaround for a deeper issue: type checking is not really interruptible. It happens in steps. I think we could make it deterministic (thus testable and more robust in general) by coming up with a better criterion to determine when we're done type checking. (While still allowing fine-grained "preemptive multitasking" in the type checker.)

**Comment by retronym** [comment]
Perhaps another useful condition to add here is `!context.bufferErrors`, to check that we're not in silent mode, during which we try one thing, then fall back to another. The intermediate states in that sequence might not lead to overloaded types.

For example, you might observe that `Foo.bar` is of type `(Int)Int` if you were interrupted between the first and second try below.

``` scala
object Test {
  object Foo {
    def bar(a: Int) = 0
  }
  implicit class RichFoo(f: Foo.type) {
    def bar(a: String) = 0
  }
  Foo.bar("")
}
```

```
% qbin/scalac -Ytyper-debug sandbox/test.scala
...
|    |-- Foo.bar("") BYVALmode-EXPRmode (site: value <local Test> in Test)
|    |    |-- Foo.bar BYVALmode-EXPRmode-FUNmode-POLYmode (silent: value <local Test> in Test)
|    |    |    |-- Foo EXPRmode-POLYmode-QUALmode (silent: value <local Test> in Test)
|    |    |    |    \-> Test.Foo.type
|    |    |    \-> (a: Int)Int
|    |    |-- "" : pt=Int BYVALmode-EXPRmode (silent: value <local Test> in Test)
|    |    |    \-> <error>
|    |    second try: (a: Int)Int and ""
|    |    |-- RichFoo BYVALmode-EXPRmode-FUNmode-POLYmode (silent: value <local Test> in Test) implicits disabled
|    |    |    \-> (f: Test.Foo.type)Test.RichFoo
|    |    [adapt] RichFoo adapted to (f: Test.Foo.type)Test.RichFoo based on pt Test.Foo.type => ?{def bar(x$1: ? >: String("")): ?}
|    |    |-- (f: Test.Foo.type)Test.RichFoo EXPRmode-POLYmode-QUALmode (site: value <local Test> in Test)
|    |    |    \-> Test.RichFoo
|    |    |-- Test.this.RichFoo(Test.this.Foo).bar BYVALmode-EXPRmode-FUNmode-POLYmode (silent: value <local Test> in Test)
|    |    |    \-> (a: String)Int
|    |    \-> Int
```

**Comment by dotta** [comment]
@retronym @adriaanm Turns out that writing a test for this is simple! It's enough to perform a targeted type-check on a not-yet-loaded source file. I've updated the commit + message accordingly, let's ship it! ;-)

Also, can this be considered for a 2.10.4 backport? \cc @dragos

**Comment by retronym** [comment]
What about the `!context.bufferErrors` check to avoid interrupting the compiler while it's doing "throwaway" typechecking?

**Comment by dotta** [comment]
@retronym TBH, I have no clue about what `!context.bufferErrors` is :-)

**Comment by dotta** [comment]
@retronym My current understanding of typer doesn't really allow me to elaborate much on the need of checking for `!context.bufferErrors`, maybe @adriaanm can comment on this. One thing I'm wondering is, would it be possible to "simply" set the `interruptsEnabled` flag to `false` when the compiler does <quote>"throwaway" typechecking</quote>?

**Comment by retronym** [comment]
The regular compiler doesn't see `interruptsEnabled`, though, as it is defined in the `interactive.Global`.

A little background on what `bufferErrors` means. In the default mode of of the typer, any time an error or warning is detected, it is directly emitted to the `Reporter`. This shows it to the user. But, when doing some exploratory typechecking (usually under `Typer#silent { ... }`), these are instead written into a buffer. The caller then can recover from an error.

Here's an example, that tries to recover from type errors in `xs.withFilter(...)` by trying `xs.filter(...)`:

``` scala
      // temporarily use `filter` as an alternative for `withFilter`
      def tryWithFilterAndFilter(tree: Select, qual: Tree): Tree = {
        def warn() = unit.deprecationWarning(tree.pos, s"`withFilter' method does not yet exist on ${qual.tpe.widen}, using `filter' method instead")
        silent(_ => typedSelect(tree, qual, nme.withFilter)) orElse { _ =>
          silent(_ => typed1(Select(qual, nme.filter) setPos tree.pos, mode, pt)) match {
            case SilentResultValue(res) => warn() ; res
            case SilentTypeError(err)   => WithFilterError(tree, err)
          }
        }
      }
```

It doesn't make sense to stop halfway through this process. If you allow interrupts in silent mode in my typer trace above, you might observe the `""` as the type `<error>`. I haven't experimented to see if `pollForWork` actually is ever called in this scenario, but I think its likely.

But, I have a strong feeling that this condition is the right one.  It would, of course, be great to motivate it with a test. But if it can't be pinpointed, I would suggest to do it anyway.

**Comment by dotta** [comment]
@retronym Thanks a lot for the detailed explanation! What you are saying makes sense to me. However, it seems a different issue than the one described in SI-7548. If you agree, let's merge this PR, file a ticket, and open new PR for ignoring interrupts during exploratory typechecking (of course, I can have a stub at it).

**Comment by retronym** [comment]
In this case, I think its the same issue. The comments in the ticket talk of the contract of `askTypeAt`: it should return the same result whether or not the file was already typechecked. Guarding against `OverloadedType` is a good start, but is a symptomatic fix.

I've managed to motivate my suggestion with a test case, and have submitted a patch to your branch: https://github.com/dotta/scala/pull/1

**Comment by dotta** [comment]
@retronym Oooh, I didn't realize that checking for `OverloadedType` was only a workaround for a deeper issue. Thanks a lot Jason for taking the time, really appreciated! 

Btw, since your commit reverts my fix, how should we proceed? Do you want me to close this PR, and you'll issue a new one with the correct fix? Alternatively, I could merge your fix and squash commits, but I would be taking credit for something I haven't done myself... ;-)

**Comment by retronym** [comment]
You can just merge my fixes to this PR and we can merge the lot. Every commit builds, and together they tell a story.

**Comment by retronym** [comment]
Also, I think this change is quite safe to target 2.10.4. If you agree, it would make like easy if you submit the PR to that branch. (It will be merged to master shortly after as a matter of course.)

**Comment by dotta** [comment]
Perfect. I'm closing this, and will and re-open it against 2.10.4 branch tomorrow.

**Pull request closed without merging**
