### PR TITLE
SI-7782 Derive type skolems at the ground level

### PR DESCRIPTION
**Pull request by retronym**
Rather than at the current value of `skolemizationLevel`,
which could be influenced by an in-flight existential
subtype computation.

This method is called in `PolyTypeCompleter`, which
could be constructed by the lazy type completer of the
enclosing class. So currently it is closing over a mutable
variable; hence the Heisenbug.

This issue was exposed by the changes in b74c33e,
which was introduced in Scala 2.10.1.

Review by @adriaanm, /cc @lrytz

### CODE REVIEW

**Comment by adriaanm** [comment]
I always thought that was intensional. Could you check with @odersky?

**Comment by retronym** [comment]
I'll check tomorrow. The status quo seems pretty messed up: the `PolyTypeCompleter` for a method can trigger at any old time, and it picks up the `skolemLevel`-de-jour, which isn't related at all to that method.

**Comment by retronym** [comment]
@odersky suggests that skolemLevel = 0 makes sense for these internal type parameter skolems. We did wonder whether we should capture the current value of `skolemLevel` at the creation of the type completer (which would be tricky; it needs to be done at the creation of the class type completer, not the method type completer which itself is lazily created!), but he couldn't think of any reason to do this.

**Comment by retronym** [comment]
paging @adriaanm for approval.

**Comment by adriaanm** [comment]
LGTM. Thanks for the explanation. It would be good to document the dynamic scope of `skolemLevel`, but I won't hold up this PR for that.

**Pull request merged**
