### PR TITLE
Refactor lookupCompanion

### PR DESCRIPTION
**Pull request by retronym**
- Check for module class up front to use sourceModule
  - Consolidate most of the logic in Contexts

Followup for #5654

### CODE REVIEW

**Comment by lrytz** [comment]
Weird: PR #5654 is merged and includes 1d41aef53506a4e697f848e790e03f204d05885d, but that same commit still shows up in the "Commits" section of this PR. Maybe a bug on GitHub's side?

**Review by lrytz — APPROVED** [review]
Refactoring LGTM

**Comment by retronym** [comment]
@lrytz There was a merge conflict with a typo fix that needed rebase.

**Comment by lrytz** [comment]
Needs another rebase due to due to `@showAsInfix`, see https://github.com/scala/scala/pull/5712.

**Pull request merged**
