### PR TITLE
Topic/unpickle resilience 2

### PR DESCRIPTION
**Pull request by paulp**
This is an improved rework of #1053.

### CODE REVIEW

**Comment by xeno-by** [comment]
I don't have the experience to judge the `ClassfileParser` part, but other stuff looks good.

**Comment by jsuereth** [comment]
Legit error

**Comment by paulp** [comment]
Sigh, my bad.  Brutal day of interruptions.

**Comment by paulp** [comment]
Same commit minus the unnecessary change which broke the world.

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by lrytz** [comment]
seems this one is good to go.

**Pull request merged**
