### PR TITLE
partest: document '--debug' keeps generated files

### PR DESCRIPTION
**Pull request by raboof**
review by @som-snytt, @lrytz, @SethTisue ?

### CODE REVIEW

**Review by som-snytt — APPROVED** [review]
+1 just for the alignment. I'm surprised debug doesn't enable verbose, or does it?

**Comment by raboof** [comment]
Doesn't look like it: without `--verbose` I don't get the `% scalac ...` line in the output.

**Review by hrhino — APPROVED** [review]
Very nice. I didn't know about this until today.

I'm so glad to see people helping with partest that I won't mention the comma splice. I think that's local style in the compiler, anyways.

**Comment by som-snytt** [comment]
I'll endorse the comma splice here, it's quite poetic, like something out of Old English verse.

**Pull request merged**
