### PR TITLE
Parser and position improvements.

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
Review by @retronym, also @dragos if you're available. I fear that any change to positions probably "breaks" tests elsewhere.

**Comment by paulp** [comment]
@densh These are reasonable observations, but my situation is this: I'm no longer employed by typesafe and am now working for free. I don't intend to undertake anything which is not directly motivated by range positions, at least not until such time as I am at a stopping point with range positions.

**Comment by retronym** [comment]
I don't find the change to point for `new Xxx` to be an improvement. What's your take on it?

``` diff
 found-req-variance.scala:23: error: type mismatch;
  found   : Inv[C]
  required: Inv[A]
 Note: C <: A, but class Inv is invariant in type T.
 You may wish to define T as +T instead. (SLS 4.5)
   def f3 = Set[Inv[A]]() + new Inv[C]
-                           ^
+                               ^
```

**Comment by paulp** [comment]
You don't? The error being issued here has nothing to do with the instantiation, it's about the type. From my POV ideally the only time the point is on "new" is when the error is directly related to construction, like calling a private constructor or supplying the wrong number of arguments. Which is not to say we're anywhere near any uniform policy being implemented, but the point changes in this commit I thought were improvements or at worst neutral.

**Comment by paulp** [comment]
Oh, and there are plenty of examples of the point moving from "new" to the type in just the situations I described, so I have no principled stand here. The truth is that it is ridiculously difficult to modify positions without breaking somewhere, and ridiculously time consuming to find out where that break took place. The point bounced between new and the type half a dozen times while I tried to achieve the seemingly small goal of getting the point inside the start-end range -- which is what this is really all about. If I can't make start <= point < end an invariant of positions, then the efficiency of the encoding will suffer because I can't assume a positive offset.

**Comment by retronym** [comment]
The other point changes looked okay, it is just this one that I wasn't sure about.

But it does seem to be consistent with:

```
scala> def `new`[C]: C = ???
new: [C]=> C


scala> val x: String = `new`[Int]
<console>:8: error: type mismatch;
 found   : Int
 required: String
       val x: String = `new`[Int]
                            ^
```

@dragos, what do think of that one?

**Comment by retronym** [comment]
LGTM.

**Pull request merged**
