### PR TITLE
[nomaster] nightly tests binary compat and osgi

### PR DESCRIPTION
**Pull request by adriaanm**
Together with af0da51e1b, this reenables testing binary compatibility
as part of PR validation, on check-in of every commit, and during the nightly.

NOTE: depends on https://github.com/typesafehub/migration-manager/pull/30 and a new migration manager release

### CODE REVIEW

**Comment by JamesIry** [comment]
BUILD FAILED
/localhome/jenkins/b/workspace/pr-checkin-per-commit/build.xml:3008: The following error occurred while executing this line:

## /localhome/jenkins/b/workspace/pr-checkin-per-commit/build.xml:2659: Unable to resolve artifact: Missing:

1) com.typesafe:mima-reporter_2.9.2:jar:0.1.5-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.typesafe -DartifactId=mima-reporter_2.9.2 -Dversion=0.1.5-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.typesafe -DartifactId=mima-reporter_2.9.2 -Dversion=0.1.5-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) com.typesafe:mima-reporter_2.9.2:jar:0.1.5-SNAPSHOT

---

1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:jar:2.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

**Comment by retronym** [comment]
snapshot deps aren't admissible, even for a little while.

https://github.com/scala/scala/commit/af0da51e1b#commitcomment-2669452

**Comment by adriaanm** [comment]
yes, sorry -- my mistake

**Comment by adriaanm** [comment]
note that this is expected to fail for now as 0.1.5 is not released yet afaik
I just wanted to get this off of my todo list and onto github, apologies for taking your time with this

**Comment by JamesIry** [comment]
I'll close it for now so we don't keep looking at it. When 0.1.5 is ready we can reopen and rebuild.

**Pull request closed without merging**
