### PR TITLE
SI-6609, eliminate special case in pattern matcher.

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by retronym** [comment]
The only risk I see here is [fatter bytecode](https://gist.github.com/retronym/4007067). Is there an appreciable difference in JAR size?

Miguel's work in the experimental optimizer would mitigate this a little as he caches module references within blocks.

**Comment by adriaanm** [comment]
Good point. I think we could still move this to the pattern matcher logic.
And by "we" I mean "me".

**Comment by retronym** [comment]
While the original fix was motivated by pattern matcher deficiencies, it applied to non-pattern-matching code as well. So a more general optimization would be need to restore the status quo (if we deem it worthwhile.) Maybe we get it already under `-optimize`?

**Comment by paulp** [comment]
So... I'll close this then. I once lost half a day which eventually led back to that little chunk of code, and it's always making bleating sounds in the back of my mind, so that's my motivation.

**Pull request closed without merging**
