### PR TITLE
SI-4270 Disqualify in scope implicits that are shadowed.

### PR DESCRIPTION
**Pull request by retronym**
If an expression wouldn't type check explicitly, it shouldn't be
allowed implicitly.

Employs `typedIdent`, which already does this sort of thing rather well,
instead of continuing to reimplement it in `Implicits`.

Remove check for non-implicit synonym, which is subsumed by typing an `Ident`.

Also fixes SI-5376.

Typing the `Ident` will be a touch slower, but I don't get consistent build times for `quick.comp` on my laptop at the best of times, so I couldn't determine if is a problem.

Resubmission of #692 that accommodates Scaladoc's usage of implicit search.

Review by @adriaanm.

### CODE REVIEW

**Comment by adriaanm** [comment]
could you add another commit that disables allocating the `shadowed` set when not needed?
otherwise, LGTM

**Comment by jsuereth** [comment]
BTW - I'm going to update the build bot in about an hour.  He will now automatically rebuild on updated commits.  You can also force rebuilds with `PLS REBUILD ALL` anywhere in the commit message.    This commit will then be rebuilt and we can merge it.  I'd like to keep this here until then as a test case, if possible!

**Comment by jsuereth** [comment]
Ok, I'd like to merge this.  @adriaanm did you give it a LGTM?

**Comment by adriaanm** [comment]
LGTM!

very nice tidying-upping, @retronym!
(I assume the extra indirection through the Shadower is ok, performance-wise, since there are only two subclasses.)

**Pull request merged**
