### PR TITLE
fix scaladoc

### PR DESCRIPTION
**Pull request by xuwei-k**
Review by @heathermiller or @vladureche

### CODE REVIEW

**Comment by VladUreche** [comment]
LGTM. @xuwei-k can you please also include @vigdorchik for scaladoc reviews. He is going to take over scaladoc maintenance and needs to be up to date with the changes.

**Comment by gkossakowski** [comment]
PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by jsuereth** [comment]
LGTM - also, scaladoc _comments_ should fall under their maintainers for that library/code, so @axel22 @paulp @phaller or myself are good targets for this PR.

The scaladoc tool itself is a different story.   

Thanks for the fix!!!!

**Comment by axel22** [comment]
lgtm!

**Pull request merged**
