### PR TITLE
Use jline bundle built against Java 8

### PR DESCRIPTION
**Pull request by sideeffffect**
The default jline bundle contains classes built against Java 22, which is causing unnecessary issues.

related:
 * https://github.com/scala/scala/pull/10827#issuecomment-2415258547
 * https://github.com/jline/jline3/pull/1097

### CODE REVIEW

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/12994#issuecomment-2095217493

I haven't looked yet, but the comment at the end of that ticket says jline just fields the `UnsupportedClassVersionError`.

I wonder if jline should be a multi-release jar. Is a tool justified in assuming it can load a class file that is not versioned? The service loader shouldn't even see the class.

**Comment by SethTisue** [comment]
@som-snytt thanks for surfacing scala/bug#12994 — I'd forgotten about it 

the JLine ticket with the most informative discussion is https://github.com/jline/jline3/issues/937

@sideeffffect what symptoms are you seeing that show the need for this, what are the "unnecessary issues" you refer to? this is only the second complaint we've received, even though Scala 2.13.14 came out six months ago. what is your "pipeline" doing that is even noticing this?

also, before merging this, I'd want to know what is the potential impact of excluding FFM support. might that make the REPL work less well for some users?

**Comment by sideeffffect** [comment]
> excluding FFM support. might that make the REPL work less well for some users

AFAIK we're not using any of this newly introduced functionality. We should be safe to switch to the jdk8 variant :crossed_fingers:

**Comment by SethTisue** [comment]
thank you! I did not know this existed

**Pull request merged**
