### PR TITLE
Suppress match analysis under -Xno-patmat-analysis

### PR DESCRIPTION
**Pull request by adriaanm**
NoSuppression doesn't suppress. FullSuppression does.
Now using the latter when running under `-Xno-patmat-analysis`.

I should really have tested. /me hides under a rock

### CODE REVIEW

**Comment by retronym** [comment]
Let's test it if it tripped us up.

**Comment by adriaanm** [comment]
Ok, I'll whip up a pos/ test in combination with -Xfatal-warnings

**Comment by adriaanm** [comment]
@retronym, test and one more exemption added.

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
