### PR TITLE
SI-7681 Remove Phases, clean up TableDef

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @adriaanm, please.

**Comment by som-snytt** [comment]
LGTM.  I had just removed Phases locally, while futzing with phases.

But, is the policy that something deprecated at 2.10.anything is removed in 2.11.0, or does it have to be deprecated by 2.10.0?  The anything policy means that you have until the last 2.11 RC to add deprecations in 2.10.x and remove them simultaneously in 2.11.  That goes against the notion of adequate notification.

Note Phases was already using the import, right?

**Comment by adriaanm** [comment]
We've lawyered our way out of it by declaring the compiler jar internal. Only scala.reflect.\* is public (except for the internal bits :-)).

**Comment by gkossakowski** [comment]
There's only one reason that makes me anxious to merge it: potential IDE breakage. @adriaanm, what's the status of IDE validation for PRs?

**Comment by gkossakowski** [comment]
LGTM.

I grepped manually through IDE's code. There's no mention of Phases or TableDef.

**Pull request merged**
