### PR TITLE
Fixes and Improvements for the new inliner

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
review by @retronym

**Comment by retronym** [comment]
Could rebase on https://github.com/scala/scala/pull/4414 to avoid the flaky test failures.

**Comment by retronym** [comment]
LGTM. Nicely structured!

**Comment by lrytz** [comment]
@retronym added one more commit: 8c18cf4fac60fbf8d7c89e47b66615ac18acd108

**Comment by lrytz** [comment]
Actually, two more commits since your LGTM: 8c18cf4fac60fbf8d7c89e47b66615ac18acd108 and 6531e1fb8f0043d2e6257405167cdf83621229d6

**Comment by lrytz** [comment]
@retronym the PR should be ready now

**Comment by gkossakowski** [comment]
LGTM

@lrytz: I reviewed last 3 commits you added. Shall we merge?

**Comment by lrytz** [comment]
sure :)

**Pull request merged**
