### PR TITLE
SI-7292 Fixes test failures by updating *.check files

### PR DESCRIPTION
**Pull request by soc**
Looks like partest's confusion about / vs. \ was fixed between
the original Jenkins run of the fix for SI-7292 and its merge.

### CODE REVIEW

**Comment by soc** [comment]
Review by @adriaanm or anybody who has time, please.

Sorry about this ...

**Comment by som-snytt** [comment]
I think your comment spurred the latest slash handling. LGTM, with my sympathies.

Your observation suggests a PR tactic such as people use for "smog tests" on cars: rig the test runner, which is easy because even paulp never more than glanced at partest tweaks, then submit your PR so it passes.

**Comment by adriaanm** [comment]
LGTM, thanks for the quick resolution, @soc

**Comment by soc** [comment]
Thanks!

**Pull request merged**
