### PR TITLE
Gradual optimizations of findMember method

### PR DESCRIPTION
**Pull request by odersky**
findMember takes about 30% of typechecking aggregate, 20% if we discount nested calls to asSeenFrom.
I have tried ten different things to make it faster. The end result is less impressive than I had hoped for. I get about 16% reduction in wall-clock time for findMember, but my timings might be off. Still, every small improvement is worth it. 

I left all 10 changes as separate commits, so that we have a chance of measuring what works and what doesn't when Greg's benchmarking code is done.

### CODE REVIEW

**Comment by odersky** [comment]
I don't get it. I did (where upstream is scala/scala):

git checkout -t upstream/2.10.x
git checkout optimize/findmembers
git rebase -i 2.10.x

The rebase showed my commits Attempt #1 to # 10 and nothing else.

push -f, and pull request.

But now the pull request contains these other commits by viktor and others. How did they get in there?

**Comment by adriaanm** [comment]
your local `2.10.x` pointer (ref) was probably behind the actual `upstream/2.10.x`

when you do a `git fetch upstream`, it will update the `upstream/2.10.x` ref,
but it won't change your local `2.10.x` pointer (you have to do a `git pull` in that branch for that, which amounts to a `git fetch` immediately followed by a `git merge upstream/2.10.x` -- or a `rebase`, depending on how you configured the branch)

To fix this, please try:

```
git fetch upstream
git checkout optimize/findmembers
git rebase -i upstream/2.10.x
git push origin -f
```

the variation that does this for master is abbreviated to `grim` on my machine (inherited that one from  @paulp)
it's one of my most often used git aliases

ps: you only need to `git checkout -t upstream/2.10.x` once -- to bring your local `2.10.x` up to date, do `git checkout 2.10.x; git pull` -- if all you need is the ref of the current head of upstream's `2.10.x` branch, it's enough to do `git fetch upstream` and refer to `upstream/2.10.x`

**Comment by adriaanm** [comment]
also, was this pull request really intended for master?

as explained on scala-internals, I switched the default branch back to master 
(we shouldn't encourage people to submit for inclusion into 2.10.)

**Comment by paulp** [comment]
This is probably helpful for most people: https://github.com/aanand/git-up

Summary: "git up" and all your tracking branches will be up to date.

gem install git-up

**Comment by odersky** [comment]
Sent from my phone

On Jul 14, 2012, at 12:23, Adriaan Moors <reply@reply.github.com 

> wrote:
> 
> also, was this pull request intended for master?
> 
> as explained on scala-internals, I switched the default branch back  
> to master
> (we shouldn't encourage people to submit for inclusion into 2.10.)
> 
> I missed that one. I think the pullreq is safe for 2.10. If something  
> was wrong in the new logic we'd know it by now.

Cheers

   Martin

**Comment by adriaanm** [comment]
ok, i'll close this one an submit a new one

**Pull request closed without merging**
