### PR TITLE
Add support for backticks in scaladoc links

### PR DESCRIPTION
**Pull request by danicheg**
Fixes [#12628](https://github.com/scala/bug/issues/12628).
If this will be merged, It'd be cool to get ported to 2.13 too.

### CODE REVIEW

**Comment by danicheg** [comment]
Should I clarify something to get this PR viewed?

**Review by SethTisue — APPROVED** [review]
LGTM!

And we'll take care of merging it forward onto the 2.13.x branch in time for the Scala 2.13.9 release.

**Comment by SethTisue** [comment]
Thank you @danicheg !

**Comment by danicheg** [comment]
@SethTisue thank you for your review!

**Comment by danicheg** [comment]
@SethTisue will this PR be included in the forthcoming 2.13 release? I can do a backport if it's needed.

**Comment by lrytz** [comment]
@danicheg all changes in 2.12.x end up in 2.13.x, this one was ported in https://github.com/scala/scala/pull/10119

**Comment by danicheg** [comment]
@lrytz oh, didn't see it, great!

**Pull request merged**
