### PR TITLE
tests for idempotency issues in the typechecker

### PR DESCRIPTION
**Pull request by xeno-by**
For more details see https://issues.scala-lang.org/browse/SI-5464.

Check files are intentionally very precise, so that we can monitor
how the situation changes over time.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @retronym

**Comment by retronym** [comment]
Can you add a comment to each of the test files to the effect that: "this is the current behaviour, rather than the desired behavior; see SI-XXXX".

**Comment by xeno-by** [comment]
@retronym done

**Comment by retronym** [comment]
lgtm; be sure to mention these tests on the related JIRA tickets, too.

**Comment by paulp** [comment]
I'm thinking there should be a whole test category for tests which exist as coal-mine canaries, not as agents of enforcement - I know I've written a handful of them. Maybe in spatter.

**Comment by paulp** [comment]
lgtm. l-valuable-tm, also.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
