### PR TITLE
SI-8686: scala.io.Source now implements java.io.Closeable

### PR DESCRIPTION
**Pull request by hamnis**
allows users to write a single function for dealing with Input/Output
streams and Sources. It also allows Source to be used in
"try-with-resources" statements in Java > 7.

No tests since this is a binary and source compatible change.

### CODE REVIEW

**Comment by hamnis** [comment]
I have signed the Contributer agreement.

**Comment by adriaanm** [comment]
Welcome and thank you, @hamnis! Sorry, we've been a bit busy recovering from Scaladays ;-) Will get to your PR soon!

**Comment by adriaanm** [comment]
review by @Ichoran

**Comment by Ichoran** [comment]
LGTM

**Pull request merged**
