### PR TITLE
Cleanup tools/*

### PR DESCRIPTION
**Pull request by retronym**
Details in the commit comments.

Review / stay of execution by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
I use *{cp, _scalac} pretty often; probably I'm the only one because nobody ever finds anything, but I can attest to their usefulness. I don't mind if you remove them, I'm recentering on a repository I control anyway.

**Comment by adriaanm** [comment]
LGTM! Safari feels a bit snappier after merging this.

**Comment by paulp** [comment]
Safari is snappier because of your new monster cables with the gold connectors.

**Comment by adriaanm** [comment]
I splurged and got the carbon fiber ones this time. They're just a tad lighter. And stylish to boot!

**Comment by retronym** [comment]
I'm going to merge now. But since this discussion I have become an avid locker_scalac fan and will bring at least that one back with some module-awareness before too long.

**Pull request merged**
