### PR TITLE
SI-9277 Downgrade marginal javap features

### PR DESCRIPTION
**Pull request by som-snytt**
Drop Java 6 support, -app, -fun, and -raw options.

### CODE REVIEW

**Comment by som-snytt** [comment]
The tests are run under java 6, so closing until it's appropriate to drop java 6 support. Alternatively, check for java version in tests. One test is obsolete.

@adriaanm Is there a plan yet to migrate 2.12 builds to java 8? Is that something I could look at some weekend?

```
/home/jenkins/workspace/scala-2.11.x-validate-test/build-ant-macros.xml:764: Test suite finished with 4 cases failing:
fail - run/repl-javap-mem.scala  [output differs]% scalac repl-javap-mem.scala
% /usr/lib/jvm/jdk1.6.0_45/jre/bin/java \
  -Dfile.encoding=UTF-8 \
  -server \
  -XX:+AggressiveOpts \
  -XX:+UseParNewGC \
  -Xmx2G \
  -Xss1M \
  -XX:MaxPermSize=512M \
  -XX:ReservedCodeCacheSize=128M \
  -Dpartest.threads=4 \
  -classpath \
  /home/jenkins/workspace/scala-2.11.x-validate-test/test/files/run/repl-javap-mem-run.obj
```

**Comment by adriaanm** [comment]
I've been flip-flopping on M1/2 for the Java 8 jump. Current thinking is that M1 will focus on move to the sbt build, M2 will jump to Java 8. @retronym and @lrytz have been working on the upgrade, so I'll let them comment on weekendable efforts in this zone.

**Comment by retronym** [comment]
This is where I got to on the modernization: https://github.com/scala/scala/compare/2.12.x...retronym:topic/require-java-8

I think `-raw` has a decent cost/benefit ratio and could stick around.

Maybe we can resurrect `-fun` after we turn on indylambda support; the current Javap output is pretty annoying. Notice below that the line between the lambda capture site in `test` and the lambda target `$line3$$read$C$$$anonfun$1` isn't displayed under `:java -c`:

```
%  qscala -Ydelambdafy:method -Ybackend:GenBCode -target:jvm-1.8
scala> class C { def test = () => "" }
defined class C

scala> :javap -c C
Compiled from "<console>"
public class C {
  public scala.Function0<java.lang.String> test();
    Code:
       0: invokedynamic #34,  0             // InvokeDynamic #0:apply:()Lscala/compat/java8/JFunction0;
       5: checkcast     #36                 // class scala/Function0
       8: areturn

  public static final java.lang.String $line3$$read$C$$$anonfun$1();
    Code:
       0: ldc           #40                 // String
       2: areturn

  public C();
    Code:
       0: aload_0
       1: invokespecial #44                 // Method java/lang/Object."<init>":()V
       4: return
}
```

Using `-v` instead, we can establish the connection by looking at the bootstrap method `#0`:

```
scala> :javap -v C
...
BootstrapMethods:
  0: #22 invokestatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #24 ()Ljava/lang/Object;
      #29 invokestatic C.$line3$$read$C$$$anonfun$1:()Ljava/lang/String;
      #30 ()Ljava/lang/String;
```

**Comment by retronym** [comment]
As you can see the impact on the Ant build is pretty minor. I don't think we necessarily need to wait the coronation of the SBT build. One thing I didn't get around to yet is removing the redundant tests (or parts thereof) that are conditional on `java.version < 8`

**Comment by som-snytt** [comment]
`-raw` defaults on, so WYSIWYG. The idea is that, at this level, it's easier to mentally filter the REPLications (i.e. wrappings), and avoid the occasions when `StrippingWriter` is confusing.

The surgery happened to stop when fragile `C#test` filtering syntax still worked; but it seems to me that modularity/composability is desirable, along the lines of `javap | filter C#test`. Similarly, `javap | unwrap`.

Right now, of course, there's no facility for that. Similarly, it wants a reflective way to chase lambdas, App bodies, companion objects, etc; having a real `scalap` to do that as well as select members to print code for would be a goal. And debugger support.

**Comment by som-snytt** [comment]
I'll contribute a PR for version-dependent tests, since the fragile `#` tag mechanism was my fault.

**Comment by som-snytt** [comment]
I guess I needed that mechanism in order to test `:javap -app`.

**Comment by som-snytt** [comment]
Restored stripped output as `-filter` option.

**Comment by som-snytt** [comment]
Testing the waters.

**Comment by retronym** [comment]
This needs a rebase on 2.12.x (specifically, 8d2d3c).

**Comment by som-snytt** [comment]
Still doesn't do anything useful, so I'll give it a rest.
```
ERROR: Failed to run DSL Script
java.lang.NullPointerException: Cannot get property 'file' on null object`
```

**Comment by retronym** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-validate-publish-core/66/console

```
quick.repl:
    [mkdir] Created dir: /home/jenkins/workspace/scala-2.12.x-validate-publish-core/build/quick/classes/repl
    [javac] Compiling 1 source file to /home/jenkins/workspace/scala-2.12.x-validate-publish-core/build/quick/classes/repl
[quick.repl] Compiling 47 files to /home/jenkins/workspace/scala-2.12.x-validate-publish-core/build/quick/classes/repl
[quick.repl] OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[quick.repl] OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
[quick.repl] /home/jenkins/workspace/scala-2.12.x-validate-publish-core/src/repl/scala/tools/nsc/interpreter/JavapClass.scala:485: error: type mismatch;
[quick.repl]  found   : List[String]
[quick.repl]  required: String
[quick.repl]   def helpText: String = helps map { case (name, help) => f"$name%-12.12s$help%n" }
[quick.repl]                                ^
[quick.repl] one error found

BUILD FAILED
/home/jenkins/workspace/scala-2.12.x-validate-publish-core/build.xml:80: The following error occurred while executing this line:
/home/jenkins/workspace/scala-2.12.x-validate-publish-core/build.xml:1112: The following error occurred while executing this line:
/home/jenkins/workspace/scala-2.12.x-validate-publish-core/build-ant-macros.xml:275: The following error occurred while executing this line:
/home/jenkins/workspace/scala-2.12.x-validate-publish-core/build-ant-macros.xml:284: The following error occurred while executing this line:
/home/jenkins/workspace/scala-2.12.x-validate-publish-core/build-ant-macros.xml:221: Compilation failed because of an internal compiler error; see the error output for details.

Total time: 7 minutes 9 seconds
Build step 'Execute shell' marked build as failure
```

**Comment by som-snytt** [comment]
Sorry about that. Must have been the merge-induced brain aneurysm, but that's no excuse.

**Comment by som-snytt** [comment]
This failure is a scalap test failure.

`test/files/scalap/packageObject.scala`

https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/44/console

I can take a brief look over the weekend, but maybe someone has an idea. Yes, I mean that someone.

**Comment by retronym** [comment]
/rebuild

```
Caused by: java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:151)
    at scala.tools.scalap.scalax.rules.scalasig.ByteCode.<init>(ClassFileParser.scala:38)
    at scala.tools.scalap.scalax.rules.scalasig.ByteCode.take(ClassFileParser.scala:43)
    at scala.tools.scalap.scalax.rules.scalasig.ByteCode.next(ClassFileParser.scala:41)
    at scala.tools.scalap.scalax.rules.scalasig.ByteCodeReader$$anonfun$bytes$1.apply(ClassFileParser.scala:93)
    at scala.tools.scalap.scalax.rules.scalasig.ByteCodeReader$$anonfun$bytes$1.apply(ClassFileParser.scala:93)
    at scala.tools.scalap.scalax.rules.Rules$DefaultRule.apply(Rules.scala:69)
    at scala.tools.scalap.scalax.rules.Rules$DefaultRule.apply(Rules.scala:67)
    at scala.tools.scalap.scalax.rules.Rule$$anonfun$flatMap$1.apply(Rule.scala:35)
```

**Comment by som-snytt** [comment]
/rebuild

```
/scala-2.12.x-validate-test/test/files/scalap/paramClauses.scala
Caused by: java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:151)
    at scala.tools.scalap.scalax.rules.scalasig.ByteCode.<init>(ClassFileParser.scala:38)
    at scala.tools.scalap.scalax.rules.scalasig.ByteCode.take(ClassFileParser.scala:43)
```

**Comment by som-snytt** [comment]
That t8679 failed previously for #4526 so maybe something else is going on with those scalap tests?

Disconcertingly, different tests are reported below.

I see there is a TODO in the partest Runner around reflective invocation of ByteCode.

IIRC, InputStream::available doesn't mean total bytes in the stream as [seems to be used here](https://github.com/scala/scala/blob/2.12.x/src/scalap/scala/tools/scalap/scalax/rules/scalasig/ClassFileParser.scala#L19).

```
  [partest] !! 20 - scalap/t8679.scala                        [output differs]

BUILD FAILED
/home/jenkins/workspace/scala-2.12.x-validate-test/build.xml:1492: The following error occurred while executing this line:
/home/jenkins/workspace/scala-2.12.x-validate-test/build-ant-macros.xml:762: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error running /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/scalap/paramClauses.scala
```

**Comment by adriaanm** [comment]
The build issues turned out to be a hotspot bug (see https://github.com/scala/scala/pull/4578#issuecomment-115051647). All green now!

**Comment by som-snytt** [comment]
Thx, @adriaanm , I noticed your comment and goosed this. I also sent that info to the team at the office on why we test against specific versions of things.

**Comment by retronym** [comment]
LGTM

**Comment by som-snytt** [comment]
This failed to notice a usage of `-raw` in test/files/run/t8608-no-format.scala which didn't notice because it was busy proving a negative.

**Pull request merged**
