### PR TITLE
Nullness Analysis for GenBCode

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Recommended path for reviewing:
1. The [big comment in NullnessAnalyzer](https://github.com/lrytz/scala/commit/57b8da4cd88f820b21506b13250bd7ecfc5db102#diff-6bec7adfb4c64da1a80ad79617889ab9R14)
2. The [NullnessAnalyzerTest](https://github.com/lrytz/scala/commit/57b8da4cd88f820b21506b13250bd7ecfc5db102#diff-135307e300269dcc2516cc785288ae6f)
3. The [AliasingFrame class](https://github.com/lrytz/scala/commit/57b8da4cd88f820b21506b13250bd7ecfc5db102#diff-dda4d7641f85f94ca2596a637a40328a)
4. The [NullnessAnalyzer](https://github.com/lrytz/scala/commit/57b8da4cd88f820b21506b13250bd7ecfc5db102#diff-6bec7adfb4c64da1a80ad79617889ab9) and the rest

Review by @retronym.

**Comment by lrytz** [comment]
Build failed to resolve the upgraded `org.scala-lang.modules:scala-asm:jar:5.0.4-scala-1`. Note that it's there on maven central (https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/5.0.4-scala-1/), and the scala-ci artifactory has maven central as a remote repository defined (https://scala-ci.typesafe.com/artifactory/webapp/repositoryconfig.html?5). So I don't know.. cc @adriaanm

**Comment by adriaanm** [comment]
https://github.com/scala/scala-jenkins-infra/pull/62

**Comment by adriaanm** [comment]
Ugh, jenkins why you abort jobs and call them a success???

**Comment by adriaanm** [comment]
I restarted the validate-test for the commit currently failing because jenkins helpfully scheduled both jobs on the same worker, even though we have a whole behemoth sitting idle... shot

**Comment by adriaanm** [comment]
See also https://github.com/scala/scala-jenkins-infra/issues/33

**Comment by lrytz** [comment]
for the first job, scabot shows `main` as failed even though `test` is still running..

**Comment by adriaanm** [comment]
thats because jenkins doesn't recognize the rebuild as part of that flow

**Comment by adriaanm** [comment]
https://github.com/scala/scabot/issues/2

**Comment by lrytz** [comment]
aha!

**Comment by lrytz** [comment]
Started a bootstrap with the optimizer and nullness analysis enabled: it didn't get far :) https://scala-webapps.epfl.ch/jenkins/view/All/job/scala-checkin-manual/1390/console

Will look at it next week.

**Comment by lrytz** [comment]
I accidentally submitted this to 2.12 - resubmitted in #4519

**Pull request closed without merging**
