### PR TITLE
Merge 2.10.x into master

### PR DESCRIPTION
**Pull request by gkossakowski**
After the merge, the test/run/t7733 started to fail on Jenkins.
I tried to reproduce it locally but I couldn't so I think it's
system dependent failure. Per @retronym's suggestion I moved it to pending
to not block the whole merge.

Conflicts:
    bincompat-backward.whitelist.conf
    bincompat-forward.whitelist.conf
    src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
    src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
    src/compiler/scala/tools/nsc/typechecker/Macros.scala
    src/compiler/scala/tools/nsc/typechecker/Namers.scala
    src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
    src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
    src/compiler/scala/tools/nsc/util/MsilClassPath.scala
    src/compiler/scala/tools/reflect/ToolBoxFactory.scala
    src/reflect/scala/reflect/internal/ClassfileConstants.scala
    src/reflect/scala/reflect/internal/Importers.scala
    src/reflect/scala/reflect/internal/Trees.scala
    src/reflect/scala/reflect/runtime/JavaMirrors.scala
    test/files/run/macro-duplicate/Impls_Macros_1.scala
    test/files/run/t6392b.check
    test/files/run/t7331c.check

Review by @retronym

### CODE REVIEW

**Comment by gkossakowski** [comment]
I'll assign reviewers once I make sure that tests pass.

**Comment by gkossakowski** [comment]
@xeno-by: could you look into this test failure? I tried to reproduce it on my machine in multiple ways and I couldn't. I believe it might be system-dependent. I tried to reproduce it on Mac. Do you have Linux box where you could try to build it and run the test suite?

**Comment by retronym** [comment]
I repeat my recommendation to shift that test to pending, reopen the ticket, and proceed with the merge. I recommended that the IDE team, who raised this issue, use IMain rather than ToolBoxes for conditional breakpoints for other reasons, so this one isn't critical.

**Comment by gkossakowski** [comment]
@retronym: ok. I'll do that tomorrow (my timezone).

**Comment by xeno-by** [comment]
@retronym What's wrong with toolboxes in this case?

**Comment by retronym** [comment]
They were already using _both_ ToolBoxes (for conditional break points) and IMain (for REPL-at-a-breakpoint). They didn't see originally how to use IMain for the first use case until I offered some advice. Given that they can do both with IMain, I recommended that they use it exclusively to minimize their exposure to different moving parts.

**Comment by xeno-by** [comment]
From what I remember, the problem with repl for breakpoints was speed. How did you address that?

**Comment by retronym** [comment]
They should compile a `Function` and apply that each time the breakpoint condition is evaluated. Only need to interact with the compiler once.

**Comment by xeno-by** [comment]
Hah! Makes sense.

**Comment by gkossakowski** [comment]
@retronym: Ok I followed your suggestion and I moved the failing test to pending. The PR is ready for review.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
