### PR TITLE
SI-6478 Fixing JavaTokenParser.ident

### PR DESCRIPTION
**Pull request by jroper**
JavaTokenParser.ident doesn't accept many valid Java identifiers, including `MODULE$` (very common in Scala land), and anything containing unicode characters.

See https://issues.scala-lang.org/browse/SI-6478 for more details.

### CODE REVIEW

**Comment by paulp** [comment]
That's lovely; can you please throw in a simple test case?

**Comment by jroper** [comment]
Simple test case thrown in.

**Comment by jsuereth** [comment]
Just so you know, this is targetting 2.11. If you want to see this in 2.9.3 or 2.10.1, we'll need to backport it.

**Comment by jroper** [comment]
No urgency here, I happened to come across it when fixing a bug in Play framework, it's easy enough to work around.

**Comment by paulp** [comment]
LGTM.

**Pull request merged**
