### PR TITLE
Allow main method without parameters [WIP]

### PR DESCRIPTION
**Pull request by lrytz**
Feedback welcome

```
object C {
  def main: Unit = {
    println("hi")
  }
}
```

When there's a main without paramters (no param list, or single empty param list), inherited or declared, and there's no inherited or declared main method with an `Array[String]` parameter, generate a main method that forwards to the user-defined one.

If we go there:
  - deprecate App
  - do some cleanups
  - make sure jar entry points still work
  - tests
  - ...

### CODE REVIEW

**Comment by sjrd** [comment]
> deprecate App

Er, seriously? The only thing that was keeping `App` alive was `(args: Array[String])`!? Because if that was it, we should have deprecated it the day it was introduced. This is a very small syntax price to pay for the complexity of `DelayedInit`.

Honestly, I do not understand this change. If the above snippet is considered good enough, why isn't the variant with `(args: Array[String])` good enough? And if that variant is good enough, why do we need more magic to generate a bridge with `args` to call the one without `args`?

**Comment by lrytz** [comment]
We'd like to get rid of DelayedInit in Scala 3, so App is one of the things that would go away. DelayedInit does quite some magic and can have unintended effects, such as

```
$ cat Test.scala
object A extends App {
  val x = "hi"
}

object B extends App {
  println(A.x)
}
$ scalac Test.scala && scala B
null
```

The goal of `App` always was to have something less keystroke-heavy than `def main(args: Array[String]): Unit = { ... }`, I think nullary `main` is easy to understand and not too much magic.

**Comment by sjrd** [comment]
I understand the motivation to get rid of `DelayedInit`.

But I disagree that avoiding the few keystrokes of `(args: Array[String])` outweigh the cost of the magic for a parameterless `main` method. My point is: we should just tell people to write down the full signature, instead of introducing yet another non obvious special case in the language for the sake of a main method.

**Comment by lrytz** [comment]
OK, thanks for your input! Let's see what others say :)

**Comment by hrhino** [comment]
Thinking on it some, I'd be inclined to agree with @sjrd here. If you're writing an application, the effort to type `def main(args: Array[String]): Unit = {}` is a drop in the bucket compared to writing the rest of the code; if you're writing a script the `scala` launcher can run it without a `main` method already. 

Getting rid of `DelayedInit` is +:100:, but adding another synthetic method here is similarly magical.

There's also this:

```scala
Welcome to Scala 2.13.0-20180417-185126-e0b96a8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_161).
Type in expressions for evaluation. Or try :help.

scala> class Main { def main: Unit = println("hi") } ; object Main extends Main
defined class Main
defined object Main

scala> Main.getClass.getDeclaredMethods
res0: Array[java.lang.reflect.Method] = Array()
```

which is something done even in the compiler! (`scala.tools.nsc.Driver`). I don't know if that's inconsistent enough to actually trip anyone up, but it does at least seem strange to me.

**Comment by SethTisue** [comment]
I like this. `main` is a special case on the JVM anyway; making it slightly more special in this way weighs about 1/1000th as much as `DelayedInit` and will ease the on-ramp for new Scala learners.

**Comment by hrhino** [comment]
I wonder how many Scala newcomers are also JVM newcomers. If you're a Java programmer you're used to the `public static void main` shenanigans. If you're coming from C (or are just like me) you may be tripped up that `def main(): Int = ...` doesn't work. It's probably too much to ask for that, though. What I said above notwithstanding I don't think this is all that bad, but it is another special case.

Is there somewhere this could be documented? Preferably around the Tour, if the main target is new users.

**Comment by julienrf** [comment]
In the case of Scala.js web application, the `args` make no sense, I’d like to be able to write `def main: Unit = …`.

**Comment by SethTisue** [comment]
> The only thing that was keeping App alive was (args: Array[String])!? Because if that was it, we should have deprecated it the day it was introduced

iirc from past years, Martin felt very strongly about the value `extends App` as a way of helping new users get started quickly and give them a good impression of Scala, a better impression than Java's `public static void main ...` gives.

then `DelayedInit` came later as a way of preserving `extends App` while avoiding the pitfalls of having everything in the constructor.

> we should have deprecated it the day it was introduced

indeed, with hindsight, I now wish it had never been added. (I don't claim to have had this wisdom at the time.)

**Comment by som-snytt** [comment]
There is a ticket (or more) to unify the experience of REPL script (definitions are members), Scala script (source is local to a synthetic main method) and App. Also running under sbt.

The compiler could bridge the platform entry point to any of `run()`, `main(String*)`, etc., also `apply()`, `apply(Array[String])`, etc.

There's an option for specifying `main-class` for manifest; the option could specify our entry-point that would be bridged as required.

I don't know who came up with the muscle t-shirt that says "No pain, No main."

**Comment by martijnhoekstra** [comment]
Alternative colors for this shed:

```
@runnable
object Foo {
  /* body */
}

```
generates an additional 

```
object Foo$Main {
  def main(args: Array[String]): Unit = { Foo; (); }
}

```
or a main annotation that emits a similar bridge for any method with the right signature (or an error if such a bridge is impossible)

**Comment by lrytz** [comment]
I remember some old discussions that it's not a good idea for performance on JVM to run an entire application as part of a constructor (of the `Foo` object in the example above)

**Comment by SethTisue** [comment]
a good blog post to read to get in the right mindset for considering this: https://sofiavaughanjones.com/2018/04/16/learning-how-to-code-with-scala-hello-world/

**Comment by som-snytt** [comment]
That's a nice blog post. I'm impressed that Seth found the person using 2.12.5.

One purpose of the "exact signature" rule is discoverability, if you don't want sbt to suggest many possible things to run.

Everyone forgot to upvote my last comment, so I'm going to edit it. Basically, I'd at least like the lower hassle factor of `main(String*)` and `main()`. IIRC, `ScalaClassLoader` is more forgiving than `java`.

**Comment by lihaoyi** [comment]
> iirc from past years, Martin felt very strongly about the value extends App as a way of helping new users get started quickly and give them a good impression of Scala, a better impression than Java's public static void main ... gives.

Not sure if this is too far out there, but here's another idea:

What if we made the Scala compiler recognize `src-root/foo/bar/Qux.sc` files, and wrap the code within them as you would a Scala script, with an `object Qux` in `package foo.bar` with a standard JVM main method, so after compilation you could run it via `scala foo.bar.Qux`?

This would give newcomers an even better impression of Scala: no `object`, no random curlies, just:

```scala
// Qux.sc
println("Hello World")
```

And you're off to the races! As you write more code in multiple files, you may fall back to the full `Foo.scala` file format, as is currently done in SBT builds. `Foo.scala` and `Foo.sc` could be intermixed and happily interact, with the only difference being that in `Foo.sc` we'd wrap things in the `package`/`object` boilerplate automatically (exactly what wrapping strategy, e.g. whether class-based or object-based, can be discussed later).

For newcomers coming from languages like Python/Ruby/Javascript/VB/etc., usage of the `.sc` would be an even bigger win: simple enough to not even need explanation. *Of course* you would just put code you want in a file and run it!

Furthermore, this `.sc` format is already pretty standard within our ecosystem: the `scala` command lets you run such scripts directly, the Scala REPL already supports a dialect of it for use interactively, SBT uses a dialect for `build.sbt`, IntelliJ supports a dialect for Scala Worksheets, Ammonite supports a dialect in Scala Scripts, as does Mill (through Ammonite). Granted these dialects are all slightly different & divergent, but even so 

1. People are already used to the concept of a `.sc` script file that can be run without a main method, despite the differences in dialect

2. If we started supporting such a format in the core compiler, that would give us a foundation to start unifying all the various dialects under a standard "lightweight Scala" `.sc` format.

Perhaps this is a bigger change than is initially proposed in this PR, but given the goals & constraints being discussed, it could be worth consideration. Rather than the ad-hoc measures we have now in DelayedInit, or baby steps like using an annotation or removing `args: Array[String]` from the main method, we would invest more effort but get both huge wins in syntactic conciseness as well as reaching a sweet spot of familiarity where the learning cost for the new syntax is basically zero.

**Comment by jvican** [comment]
Even if `sc` was supported by the compiler, wouldn't you need a way in the scripted to access arguments that you can pass in to `scala foo.bar.Qux`?

**Comment by lihaoyi** [comment]
> Even if sc was supported by the compiler, wouldn't you need a way in the scripted to access arguments that you can pass in to scala foo.bar.Qux?

Sure, it can be injected as an `args` member of the wrapper object just like how `scala.App` works now

**Comment by som-snytt** [comment]
People's thumbs are so sore from texting that they're too tired to 👍 .

I'm not sure `scalac` has a notion of `src/main/scala` root from which to deduce a package, but maybe `-Xmain-class` can be rejiggered to support `-Xmain-class foo.bar.Qux` and do the obvious thing.

The capacity could be called the `Qux` capacitor.

Another possibility would be package-level stuff, `package foo.bar ; val msg = "hello, world"; println(msg)` with `Qux` inferred, or (speculating) this is how you specify a package object and `Qux.main` just references the package object.

I have to go ice my thumbs now.

**Comment by lihaoyi** [comment]
> I'm not sure scalac has a notion of src/main/scala root from which to deduce a package, but maybe -Xmain-class can be rejiggered to support -Xmain-class foo.bar.Qux and do the obvious thing.

We could also just drop the idea of package inference, ask people to put a `package foo.bar` declaration in their scripts if they want it in a package, otherwise it defaults to `Qux` object being in the root package. Not a huge loss; most of the convenience comes from being able to get started writing code without wrapper-object/method boilerplate, not from package-declaration-inference

**Comment by lrytz** [comment]
Right now the compiler doesn't know the "root of sources" folder(s), except when you pass `-sourcepath`, but that's basically a sepcial case used only for compiling the standard library. It would be a pretty fundamental change, because it would be the first step of putting functionality into the compiler that traditionally was the build tool's job.
There are other proposals to blur the line between compiler and build tool, e.g., to make the compiler responsible for incremental compilation.
So I think we can consider  the `.sc` file idea longer term (post 2.13). In the meantime, the proposal here is simple, non-breaking, and IMO really practical.

**Comment by jvican** [comment]
I think there's not a lot of value in adding this to the compiler... Nobody uses `scalac` directly from the CLI and the syntactic sugar here discussed it's completely compiler agnostic. I think we're better off having this outside the compiler, as an independent tool that we can reuse, and that works for both Dotty/Scalac and God knows what more compilers in the future.

**Comment by som-snytt** [comment]
The comment that no one uses the command line and therefore no one uses Scala scripts reminded me to submit a PR so I don't have to use `-nc` whenever I run a Scala script (non-amm).

**Comment by ashawley** [comment]
I thought the intention of`App` was good, but it was a little confusing and I eventually did get bit by the `DelayedInit` bug.  The proposal to support `Main.main` without parameters seems to be of similar spirit to `App` and a good alternative going forward. 

PS.  I can't tell whether recent comments are responding to the PR or Li Haoyi's counter-proposal.

**Comment by Ichoran** [comment]
@jvican - I don't use `scalac` directly from the command line because it can't do stuff like this.  If I could

```scala
import with "com.github.pathikrit" %% "better-files"
import better.files._
import File._
file"Hello.txt" < "Hello, world!"
```

I would do it all the time, especially if there was a preamble feature that I could pull out of some common directory.

When a tool is inconvenient for a particular use-case, people don't use it for that use-case.  It doesn't follow that they wouldn't if the use-case was made convenient.

**Comment by ashawley** [comment]
What's not clear about the proposal is whether the user gets to access `args` in a parameter-less `main`:

```scala
object Main {
  def main: Unit = {
    args.foreach(println)  // error not found: value args
  }
}
```

I'd vote that that not be the case.

**Comment by adriaanm** [comment]
Let's continue the discussion, but we likely won't be able to include this in 2.13.0. Collections take priority.

**Comment by ashawley** [comment]
Kotlin has recently released a similar feature:

https://kotlinlang.org/docs/reference/whatsnew13.html#parameterless-main

**Comment by He-Pin** [comment]
So it will support both `def main(): Unit` and `def main: Unit`?

**Comment by tarsa** [comment]
I think the main advantage of App trait is the possibility of very concise ready to compile examples (that 99%+ of the time don't even use args parameter). If the example grow longer than few lines or one object then the gain from not having to type main method diminishes. Therefore I think that we need to focus on simplifying already simple cases.

My proposal is to remove all special handling in the compiler and make a new class instead:
```scala
// this could be put into standard library
abstract class MyApp(body: => Unit) {
	def main(args: Array[String]): Unit =
		body
}
// such constructs would be allowed then out of the box
object Main extends MyApp({
	class Name(val raw: String)
	val whoToGreet = new Name("World")
	println(s"Hello ${whoToGreet.raw}!")
})
```
Above Main object looks very close to what it would look if using current App trait. The only distinction is additional pair of parentheses.

**Comment by lihaoyi** [comment]
Wrote up a post on a more holistic approach to this problem https://contributors.scala-lang.org/t/proposal-simplifying-the-scala-getting-started-experience/2978

**Comment by som-snytt** [comment]
Thanks @ lihaoyi, I commented approvingly. I don't like the drudgery of the transitions you describe, although frankly I only use the regular repl for scripting; sometimes I just `-d app.jar` if necessary.

Thanks @ tarsa I just reread your previous comment and laughed approvingly at "simplifying the simple".

I look forward to hearing that phrase in Martin's next keynote on the goals of dotty. Also "Scalify the Scala." "It was not simple enough, nor was it Scala enough."

**Comment by SethTisue** [comment]
https://contributors.scala-lang.org/t/pre-sip-program-foo-println-hello-world/2974/22 is also a raging torrent of posts at the moment

it sounds like we might be converging on a `@main` annotation, but let's wait and see

for now, let's close this to get it out of the queue. nothing will happen in 2.13.0

**Comment by SethTisue** [comment]
new SIP thread on the Scala 3 proposal in this area: https://contributors.scala-lang.org/t/proposal-main-methods-main/4183

**Pull request closed without merging**
