### PR TITLE
More JDK 21 fixes

### PR DESCRIPTION
**Pull request by SethTisue**
- fix a warning on JDK 21
- for now, skip TASTy tests on JDK 21

### CODE REVIEW

**Comment by som-snytt** [comment]
Forever 21!

**Comment by SethTisue** [comment]
we'll see how https://github.com/scala/scala/actions/runs/5018243645 does with these changes

@som-snytt if only Seth version 21 was LTS and I could downgrade to that edition whenever I wanted

**Comment by som-snytt** [comment]
Yes, most people prefer to stick with Long Term Seth as a known quantity. (Or quality.)

**Comment by SethTisue** [comment]
Yay, green! Thus concludes the JDK 21 work... except for the Scala 3 port. And the community build testing.

**Comment by som-snytt** [comment]
Green as Seth at 21.

**Pull request merged**
