### PR TITLE
SI-2968 Fix brace healing for `^case (class|object) {`

### PR DESCRIPTION
**Pull request by retronym**
The scanner coalesces the pair of tokens into CASEOBJECT or
CASECLASS, but fails to set `offset` back to the start of `case`.
Brace healing is then unable to correctly guess the location of
the missing brace.

This commit resets `offset` and `lastOffset`, as though
caseobject were a single keyword. Only the former was neccessary
to fix this bug; I haven't found a test that shows the need for
the latter.

review by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
Thanks a lot.  LGTM.  Idea for future work: there's no reason to reparse the entire file to find the missing brace.  When there is a correctly parsed top-level class, the "parsing frontier" should move just beyond it.  That sort of sanity check would have prevented the original error, since it reported a position in the middle of a correctly parsed unit - it would at least be able to say "I have no idea" or be silent.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

(with a cherry on top)

**Comment by adriaanm** [comment]
(or is AWS's outage causing the lack of build bot activity?)

**Comment by jsuereth** [comment]
I'll look into it.

**Pull request merged**
