### PR TITLE
SI-5744 evidence params are now SYNTHETIC

### PR DESCRIPTION
**Pull request by u-abramchuk**
The macro def <-> macro impl correspondence check compares names of the
corresponding parameters in def and impl and reports an error if they
don't match. This was originally designed to avoid confusion w.r.t named
arguments (which ended up being never implemented as described in SI-5920).

Sometimes parameter names are generated by the compiler, which puts the
user in a tough position. Luckily, there's an escape hatch built it, which
omits the name correspondence check if one of the parameters are SYNTHETIC.
Everything went well until we realized that evidences generated by
context bounds aren't SYNTHETIC, which led to the bug at hand.

Marking auto-generated evidence parameters SYNTHETIC was only the first
step, as the correspondence checker uses parameter symbols, not parameter
trees. Why's that a problem? Because SYNTHETIC doesn't get propagated from def
trees to their underlying symbols (see ValueParameterFlags).

Unfortunately one cannot just change ValueParameterFlags, because that
would break printouts generated in TypeDiagnostics, which is designed to not
print synthetic symbols.

Therefore now we not only check paramSym.flags, but also paramDef.mods.flags
when doing corresponce sweeps. This fixes the problem and doesn't mess up
error messages and debug printouts.

### CODE REVIEW

**Comment by retronym** [comment]
Could you add a tests for:
- the case when both context bounds and an explicit implicit parameter section are provided?
- view bounds?
- multiple bounds?

``` scala
implicit val s = ""
def foo[U: Numeric : Equiv, Y <% String](x: U)(implicit s: String) = macro foo_impl[U]
```

I think they should fall out naturaly, so pending that test, lgtm. Have you signed the Scala CLA?

**Comment by adriaanm** [comment]
I think this should target master. Feel free to convince me otherwise.

**Comment by xeno-by** [comment]
Would be cool if you motivated your decision. The change is minor and is in time for the feature freeze.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scala/scala/pull/2086

**Pull request closed without merging**
