### PR TITLE
SI-9918 object in trait mixed into package object

### PR DESCRIPTION
**Pull request by adriaanm**
TODO: done.

JIRA: https://issues.scala-lang.org/browse/SI-9918

### CODE REVIEW

**Comment by adriaanm** [comment]
@SethTisue, could you see about adding `xuwei-k/scalikejdbc#Scala-2.12.0-RC1` to the community build? (`sbt ++2.12.0-RC1 "project root211" test:compile`) /cc @xuwei-k

**Comment by SethTisue** [comment]
roger (but not right away): https://github.com/scala/community-builds/issues/279

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
