### PR TITLE
SI-8460 Fix regression in implicit divergence recovery

### PR DESCRIPTION
**Pull request by adriaanm**
Minor rework of #3667.

Review by @retronym.

### CODE REVIEW

**Comment by adriaanm** [comment]
Dbuild: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/10/console

**Comment by adriaanm** [comment]
Hmm, I should've seen this coming: Travis's green light comes before ours. I should probably not use travis and make a jenkins job for the spec...

**Comment by adriaanm** [comment]
Yep, and I'm pretty vertiginous. Just don't look down. Don't look doooooooooo

**Comment by adriaanm** [comment]
This one's all green. Closing the other PR.

**Comment by retronym** [comment]
Okay, so shapeless 1.2.4 does build under this patch.

But my concern is that even though `neg/t2031.scala` does terminate again, it does so after discarding a lot more divergent implicits than before:

```
% qbin/scalac -Xlog-implicits test/files/neg/t2031.scala 2>&1 | grep diverg | wc -l
     815
% scalac-hash v2.10.4 -Xlog-implicits test/files/neg/t2031.scala 2>&1 | grep diverg | wc -l
      20
```

**Comment by retronym** [comment]
I haven't managed to distill anything more about this today as I'm suffering from a bit of a head cold. I'm leaning to including this patch based on the overall results (from the tests we have its closer to 2.10.4 than we were before this.)

**Comment by adriaanm** [comment]
Ok, I don't see the full picture here to be honest (something I intend to resolve over the next months), but it seems we're just more persistent in ignoring divergence before we fail (and only before we fail anyway?). The new approach also seems slightly easier to explain (but the bar is admittedly pretty low).

As one last step to assure ourselves, I wonder how scoobi compilation times fare. 

PS: feel better! send me an email I you'd like me to take this release.

**Comment by retronym** [comment]
LGTM. Well as G as we're going to get for now.

**Pull request merged**
