### PR TITLE
SI-7462 Qualify types and terms which come from java.lang._

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
I created this pull request so that the potential impact can be evaluated.

Popular types from `java.lang`:
- `Class`
- `ClassLoader`
- `System`
- `Thread`
- `Runnable`
- `CharSequence`
- `Runtime`
- `ThreadLocal`
- `Integer`
- `Character`
- `String`
- `Object`
- `Number`
- Misc. exception types: `ClassNotFoundException`, `SecurityException`, `IllegalStateException`, `NoSuchMethodException`, `AbstractMethodError`, `AssertionError`, `NoSuchMethodError`, `NoClassDefFoundError`

Popular static members:
- `Thread`: `currentThread` and friends
- `Class`: `forName`
- `System`: `out`, `err`, `getProperties`, `currentTimeMillis`, `identityHashCode`, `arraycopy`
- `Runtime`: `getRuntime`
- `String`: `valueOf`
- `Integer`: `bitCount` and friends
- `Character`: `isDigit` and friends

Some notes:
- How many `Properties` abstraction do we need?
- Do we really have to have dozens of `System.currentTimeMillis` pairs whereever we want to time an operation?
- What's the purpose of renaming imports if we keep using the old name anyway?

@paulp What do you think?

**Comment by soc** [comment]
My tentative impression so far:
- Add the exception types (imho it doesn't make much sense to alias only half of them).
- Would be nice to have a companion object forwarder for `String` and `Class`. The type is already aliased.
- I'm not sure what to do with `Thread`, `ClassLoader`, `Runnable` and `CharSequence`, but I'd keep them out:
  - `Thread` and `ClassLoader` are too low-level and hard to get right to expose them by default. Imho they are too platform-dependent, too.
  - `Runnable`: We have our own, better abstraction, right?
  - `CharSequence`: Smells like a failed abstraction.
- Don't alias/forward `Void`, `Boolean`, `Byte`, `Character`, `Short`, `Integer`, `Float`, `Long`, `Double`, `Number`, `Runtime`, `System`. Move popular methods to better places.

Apart from that, I don't have a strong opinion, but I don't see any type which feels like it absolutely needs to be aliased/forwarded.

**Comment by paulp** [comment]
Clearly Properties have run a little wild. It'd be great to lose all those currentTimeMillis in favor of some simple standard nanoTime timer. No lack of those either. You might have to be a little more specific about renaming imports and using the old name; my mind reading abilities are on the fritz. (There are 175 files changed, I'm not going to go dredging the diff to read your meaning.)

**Comment by soc** [comment]
Sorry for that. I had things like this in mind:
- `import java.lang.Package => jPackage`: https://github.com/scala/scala/pull/2507/files#L138R11 ...
- ... but keep using `Package` in a few places.

I'm not even sure whether this is a bug or a feature.
Both options (either that `import Foo.{Bar => Baz}; import Foo._` and `import Foo.{Bar => Baz, _}` behave differently or that one import can effect an earlier one) are scary.

**Comment by retronym** [comment]
Thanks for going through these to show us the scope of that dependency on the auto import. I'm going to close the PR for now, as I don't think we would want to do this until we decide whether and when to stop that import.

**Pull request closed without merging**
