### PR TITLE
SI-7553 Propagate type of unstable args through dependent methods

### PR DESCRIPTION
**Pull request by retronym**
After a soundness fix in , instantiation of dependent
method type results behaved differently for if the argument
from which we were propagating information had a stable type
or not. This is particular to substutition into singleton types
over the parameter in question.

If the argument was stable, it was substituted into singleton
types, such as the one below in the prefix in `a.type#B`
(which is the longhand version of `a.B`)

```
scala> class A { type B >: Null <: AnyRef }
defined class A

scala> object AA extends A { type B = String }
defined object AA

scala> def foo(a: A): a.B = null
foo: (a: A)a.B

scala> foo(AA)
res0: AA.B = null
```

But what if it isn't stable?

```
scala> foo({def a = AA; a: A { type B <: String}})
res3: a.B = null
```

This commit changes that to:

```
scala> foo({def a = AA; a: A { type B <: String}})
res1: a.type with A{type B <: String}#B = null
```

That oddly printed type is missing parens: it should be:

```
(a.type with A{type B <: String})#B
```

It is is a projection from refinement that combines:
  a) the singleton type on the parameter
  b) the type of the argument

Review by @adriaanm

### CODE REVIEW

**Comment by paulp** [comment]
`found   : cs.type with MatchTranslator.this.TypeTestTreeMaker.TypeTestCondStrategy{type Result = Boolean}#<none>` I guess that'll be easy enough to address one way or another.

**Comment by retronym** [comment]
... if I could reproduce it locally. Puzzling.

**Comment by paulp** [comment]
It reproduces for me.

**Comment by paulp** [comment]
coevolveSym returns NoSymbol when TypeTestCondStrategy{type Result = Boolean} is used as a prefix and then asSeenFrom is called.

**Comment by paulp** [comment]
Yep, it compiles if I also merge in #3482 .

**Comment by retronym** [comment]
What in interconnected world we live in! In the meantime, I just force pushed a variation that might sidestep the need for working coevolution.

**Comment by retronym** [comment]
``` patch
 git diff 3460eee
diff --git a/src/reflect/scala/reflect/internal/tpe/TypeMaps.scala b/src/reflect/s
index 97ea6b6..f2deb90 100644
--- a/src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
+++ b/src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
@@ -872,7 +872,7 @@ private[internal] trait TypeMaps {
       def unapply(param: Symbol) = Some(params indexOf param) filter (_ >= 0)
     }

-    def apply(tp: Type): Type = mapOver(tp) match {
+    def apply(tp: Type): Type = tp match {
       // unsound to replace args by unstable actual #3873
       case SingleType(NoPrefix, StableArg(arg)) =>
         arg
@@ -884,11 +884,10 @@ private[internal] trait TypeMaps {
       // see depmet_implicit_oopsla* test cases -- typically, `param.isImplicit`
       case tp1 @ TypeRef(SingleType(NoPrefix, Arg(pid)), sym, targs) =>
         val arg = actuals(pid)
-        val res = typeRef(arg, sym, targs)
-        if (res.typeSymbolDirect.isAliasType) res.dealias else tp1
-      // don't return the original `tp`, which may be different from `tp1`,
-      // due to dropping annotations
-      case tp1 => tp1
+        val targs1 = targs map (t => mapOver(t))
+        val res = typeRef(arg, sym, targs1)
+        if (res.typeSymbolDirect.isAliasType) res.dealias else mapOver(tp1)
+      case tp1 => mapOver(tp1)
     }

```

**Comment by paulp** [comment]
There's an interesting bonus wrinkle to be had: this PR in combination with #3482 creates a new test failure which neither has individually.

```
% ./build/quick/bin/scalac  -d /tmp ./test/files/pos/t3731.scala
./test/files/pos/t3731.scala:9: error: type mismatch;
 found   : Test.ZW[Int]{type T = Stream[Int]}#T
    (which expands to)  scala.collection.immutable.Stream[A]
 required: Stream[Int]
  meh[Int]: Stream[Int]
     ^
one error found
```

The test case is

```
object Test{
  trait ZW[S]{type T}
  def ZipWith[S, M <: ZW[S]]: M#T = sys.error("ZW")

  // meh must be parameterised to force an asSeenFrom that
  // duplicates the refinement in the TR's pre without updating its sym
  def meh[A] = ZipWith[A, ZW[A]{type T=Stream[A]}]

  meh[Int]: Stream[Int]
}
```

That looks like a consequence of going top down instead of bottom up - Stream[A] hasn't yet been substituted. Walk that high wire!

**Comment by paulp** [comment]
@retronym In case you were wondering the above is no longer true with the latest version of #3482. It compiles with both PRs merged.

**Comment by adriaanm** [comment]
Haven't had a chance to take a closer look here, but I was thinking we may be able to simplify the logic a bit here using a single existential, à la captureThis. Will take a stab at it in the morning.

**Comment by retronym** [comment]
Cool!

I was a bit hesitant about using the `RefinedType` over the `SingleType`, which isn't well trodden turf, as the type-printing problem suggests. Happy to hand the reins over to you on this one given the interplay with SI-8177.

**Comment by adriaanm** [comment]
Sounds good.

**Pull request closed without merging**
