### PR TITLE
Presentation compiler friendliness for macros

### PR DESCRIPTION
**Pull request by xeno-by**
- Retain macro expansion in the tree in the presentation compiler
   under a new setting -Ymacro-expand:discard.
- Deprecate -Ymacro-no-expand, in favour of -Ymacro-expand:none
- Prevent range position validation errors in macro expansions (even
   though the preceding change means they no longer impact the IDE.)

I trialled the "discard-the-macro-expansion" approach recently in
scala-async (it can actually all be driven from a suitably ambitious
macro), and the results in the IDE were pleasing: hyperlinking works
as expected.

Future work: Add `-Ymacro-expand:discard-whitebox-only` to avoid expanding
blackbox macros altogether. This would be handy when troubleshooting
performance problems in the IDE.

### CODE REVIEW

**Comment by xeno-by** [comment]
Supersedes https://github.com/scala/scala/pull/3287

**Comment by xeno-by** [comment]
review @retronym @adriaanm

**Comment by xeno-by** [comment]
The failure is caused by a github error. PLS REBUILD/pr-scala@7e0eee2

**Comment by retronym** [comment]
The extra commit LGTM, thanks for that, and for the rebase.

**Comment by retronym** [comment]
PLS SYNCH

**Comment by xeno-by** [comment]
Your commits are LGTM for me :)

**Comment by retronym** [comment]
BUILDLOG?

**Comment by retronym** [comment]
I am certain that the reported errors here are glitches:

94eb751 is green in Jenkins: https://scala-webapps.epfl.ch/jenkins/job/pr-scala/5636/

Git network error for  7e0eee2

```
----- com.typesafe.sbt:incremental-compiler:jar:0.13.0-on-2.11.0-7e0eee2-SNAPSHOT-for-IDE-SNAPSHOT found !
>>>>> Scala Refactoring
>> Fetching update for git://github.com/scala-ide/scala-refactoring
fatal: The remote end hung up unexpectedly
```

**Pull request merged**
