### PR TITLE
SI-7571 Allow nesting of anonymous classes in value classes

### PR DESCRIPTION
**Pull request by retronym**
5d9cde105e added deep prohibition of nested classes within
a value class. This has the undesirable side effect of
prohibiting partial functions literals in method bodies
of a value class.

The intention of that prohibition was to avoid problems
in code using Type Tests, such as:

```
class C(val inner: A) extends AnyVal {
  class D
}
def foo(a: Any, other: C) = a match { case _ : other.D }
```

Here, the pattern usually checks that `a.$outer == other`.
But that is incongruent with the way that `other` is erased
to `A`.

However, not all nested classes could lead us into this trap.
This commit slightly relaxes the restriction to allow anonymou
classes, which can't appear in a type test.
The test shows that the translation generates working code.

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
@gkossakowski I've changed the condition to `!sym.isAnonymousClass`, and updated the comments to justify this. I think we could go further and also allow local classes, but I'm not 100% sure.

**Comment by gkossakowski** [comment]
@retronym: do you understand this failure?

**Comment by retronym** [comment]
That was your test for the original restrictions. I've just pushed a suitably relaxed version of that.

**Comment by gkossakowski** [comment]
@retronym: ah, oh right. I was confused by the output partest generated.

I'll wait for the build to pass and then I'll review your change. I'm interested in looking into bytecode we get for `foo` in your test case.

**Comment by retronym** [comment]
`foo` would not be allowed because the restrictions still prevent declaring `C` as an inner class of a value class.

**Comment by gkossakowski** [comment]
@retronym: sorry, I meant foo `Foo.foo` from your test case. I wonder if we get boxed version or not and whether outer access is properly handled for both boxed and unboxed version of value class.

**Comment by gkossakowski** [comment]
FYI: I'll experiment with this tomorrow.

**Comment by retronym** [comment]
``` scala
cat test/files/run/t7571.scala
class Foo(val a: Int) extends AnyVal {
  def foo = { {case x => x + a}: PartialFunction[Int, Int]}
}
ticket/7571 ~/code/scala2 qbin/scalac -Xprint:jvm test/files/run/t7571.scala
[[syntax trees at end of                       jvm]] // t7571.scala
package <empty> {
  final class Foo extends Object {
    <paramaccessor> private[this] val a: Int = _;
    <stable> <accessor> <paramaccessor> def a(): Int = Foo.this.a;
    def foo(): PartialFunction = Foo.foo$extension(Foo.this.a());
   ...
  };
  <synthetic> object Foo extends Object {
    final def foo$extension($this: Int): PartialFunction = (({
      new anonymous class anonfun$foo$extension$1($this)
    }: PartialFunction): PartialFunction);
    ...
  };
  @SerialVersionUID(0) final <synthetic> class Foo$$anonfun$foo$extension$1 extends runtime.AbstractPartialFunction$mcII$sp with Serializable {
    final override def applyOrElse(x1: Int, default: Function1): Object = {
      case <synthetic> val x1: Int = (((x1: Int): Int): Int);
      case4(){
        matchEnd3(scala.Int.box(x1.+(Foo$$anonfun$foo$extension$1.this.$this$1)))
      };
      matchEnd3(x: Object){
        x
      }
    };
    final def isDefinedAt(x1: Int): Boolean = {
      case <synthetic> val x1: Int = (((x1: Int): Int): Int);
      case4(){
        matchEnd3(true)
      };
      matchEnd3(x: Boolean){
        x
      }
    };
    final <bridge> def isDefinedAt(x: Object): Boolean = Foo$$anonfun$foo$extension$1.this.isDefinedAt(scala.Int.unbox(x));
    final override <bridge> def applyOrElse(x: Object, default: Function1): Object = Foo$$anonfun$foo$extension$1.this.applyOrElse(scala.Int.unbox(x), default);
    <synthetic> <paramaccessor> private[this] val $this$1: Int = _;
    def <init>($this$1: Int): anonymous class anonfun$foo$extension$1 = {
      Foo$$anonfun$foo$extension$1.this.$this$1 = $this$1;
      Foo$$anonfun$foo$extension$1.super.<init>();
      ()
    }
  }
}
```

**Comment by gkossakowski** [comment]
Ok, you convinced me that everything is fine.

LGTM.

**Pull request merged**
