### PR TITLE
Expanded unused warnings.

### PR DESCRIPTION
**Pull request by paulp**
Review by @jsuereth.

### CODE REVIEW

**Comment by paulp** [comment]
We will also accept @retronym.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
I can only suppose it didn't manage to pull the new commit, because those tests all pass for me.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
Those minor comments aside, this looks great. Future directions for the work (best addressed if we can extract it into a standalone lint tool):
- more fine grained warning policies (e.g. I might not want a warning about unused bindings in constructor patterns like `case Foo(start, end) => end`)
- consider framework annotations (i.e. Hibernate might be the one two set a private var reflectively)
- report unused imports
- expose the warnings to the IDE so that the fixes can be automated.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
"consider framework annotations (i.e. Hibernate might be the one two set a private var reflectively)"

Yeah, ant was an issue here too.

**Comment by paulp** [comment]
"report unused imports" I should do this next - especially wildcard imports which have no impact would be great to lose. We have some sick files with years of cruft in them. But what I really look forward to is -Yassume-closed-world, because although removing about 200 unused private/local members is pretty good, there may be an even larger set of unused public members in the compiler.

**Comment by retronym** [comment]
`-Yassume-closed-world` could also find things that 'could be private', 'could be final', 'could be non-implicit', ...

**Comment by retronym** [comment]
Oh, and in a similar vein, we had a bit of luck patching [SCCT](http://mtkopone.github.com/scct/) to have a manageable overhead on a large codebase, I'm hoping we can plug it into the the build to get some more useful data.

**Comment by ijuma** [comment]
-Yassume-closed-world would also be awesome from an optimisation perspective.

**Pull request merged**
