### PR TITLE
Warn on function literal as statement

### PR DESCRIPTION
**Pull request by som-snytt**
A function literal in statement position
is probably an error due to syntax.

After updating tests, wish I'd targeted 2.13 in case of conflicts.

TODO:
  - [x] this should target 2.13.x

### CODE REVIEW

**Comment by lrytz** [comment]
LGTM, thanks! Given that this warning is enabled by default, I think this should target 2.13. But I can be convinced otherwise :)

**Comment by hrhino** [comment]
This is certainly a contender for the "most test files changed per line of source code" award.

**Comment by som-snytt** [comment]
@hrhino There's a scala-dev by Lukas about the pure expr warning in if/else branches, and I had already forgotten about this PR; I looked at and got scared, what had I done in so many files?

@lrytz Like I said, I've already forgotten this one. If it's useful, please do, I don't mind where or how.

One of my earliest PRs was a one-liner that resulted in a bug much later, so please just don't cc me, I've already forgotten it.

**Comment by adriaanm** [comment]
Yeah, this should go to 2.13.x. Sounds like you'd be happy for someone to rebase the PR for you. Adding help-wanted label.

**Comment by som-snytt** [comment]
Someone did, but who knows if he did it right. It's all a big plot to get people to work on 2.13.

It needs a `help-received` label. Or also, when you have to return to a PR before it finally gets in, `second-helping`.

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
Thanks everyone involved in this team effort!

**Pull request merged**
