### PR TITLE
make Future scaladoc examples up-to-date and compilable

### PR DESCRIPTION
**Pull request by jozic**
Hi There, 
I've stumbled upon some examples in Future's scaladoc which are obsolete and will not compile. That's definitely not a critical thing, but I think it should go to 2.10.x b/c Future is a new "feature" class in 2.10 and lots of users who are going to migrate to 2.10 can find that confusing. 
There are also two unrelated minor corrections to ArrayBuffer and BigInt scaladocs.
~
Eugene

review by @heathermiller, @axel22

### CODE REVIEW

**Comment by jozic** [comment]
I did sign the CLA

**Comment by axel22** [comment]
LGTM

**Comment by heathermiller** [comment]
Thanks for the cleanups! LGTM!

On an aside... Note to committers: I noticed a number of disabled Akka-related tests that we should probably remove. I can do that real quick.

Files in question:
- `test/disabled/presentation/akka/src/akka/dispatch/Future.scala`
- `test/disabled/presentation/akka/src/pi.scala`
- `test/disabled/jvm/scala-concurrent-tck-akka.scala`

All of these contain calls to now-no-longer method `await`. (We have the `Await` companion object instead. For a while now.)

**Comment by heathermiller** [comment]
Just opened a pull to address my comments above: https://github.com/scala/scala/pull/2135

**Pull request merged**
