### PR TITLE
SI-6736, SI-6747 (alternative impl.) sort out Range boundary problems

### PR DESCRIPTION
**Pull request by ihji**
When Range contains more than Int.MaxValue elements,
it should throw IllegalArgumentException before every
meaningful operation on it. It seems that the only
reason of delaying this exception is for allowing "by"
operation.

> (Int.MinValue to 0).contains(4) # should throw exception
> (Int.MinValue to 0 by 3).contains(4) # okay

The source of all evil here is irregular use of
`numRangeElements`. It returns -1 if Range object is
invalid. Some use sites of `numRangeElements` properly check
its validity before using it, but some of them miss this
check and cause the integer overflow problems (for example,
in `lastElements`).

This commit adds missing checks.

Additionally, because they (`numRangeElements`,`lastElement`,
`terminalElement`) are completely undocumented and also have
better public alternatives (`last`,`length`), I propose to
make them private.

### CODE REVIEW

**Comment by ihji** [comment]
I will close https://github.com/scala/scala/pull/2477 if reviewer accepts this implementation.
This implementation has no performance degradation (as you might guess).

**Comment by ihji** [comment]
Review by @paulp

**Comment by soc** [comment]
LGTM. Not sure whether the mentioned members can be made private immediately, or whether they need to be `@deprecated("This method will be made private", 2.11)` first.

**Comment by ihji** [comment]
I think it's also good to take #2477 instead because #2477 has cleaner implementation and performance issue doesn't exists anymore.

**Comment by paulp** [comment]
Okay, here's the real thing: as you observed, all this craziness is to work around the way "by" is applied. We don't have to live with the mistakes of the past forever. We can write a new range and keep source compatibility via implicit as necessary.

I have to think something like this will blow the doors off our current range: https://github.com/paulp/scala/blob/5732b9a7020e3ef5f836583dd7feb17a4eacb52f/src/library/scala/collection/immutable/IntRange.scala

If you wanted to keep that benchmark boat sailing a little longer you'd get lots of points with me! I think foreach will be fastest this way, but there's also the while loop.

**Comment by paulp** [comment]
@ihji Any thoughts on this? I realize it's uncool of me to throw a whole different implementation at you after you've modified this one and I apologize for that, but the fiddling with range has gone on for so many eons and I'm morally certain it can be put to bed if we just create the range sensibly.

**Comment by ihji** [comment]
@paulp I agree with you and IntRange looks good to me. I don't mind to close these pull requests if there is a better solution. Anyway, I've learned a lot from this benchmarking by digging into JVM and it was fun. Thank you for asking me.

**Pull request closed without merging**
