### PR TITLE
Merge 2.10.x into master.

### PR DESCRIPTION
**Pull request by paulp**
@retronym ExtensionMethods could use a good look to make sure I didn't butcher something. It's all starting to look like swahili to me.

I'm morbidly curious to see how someone else will fare with one of these backport-heavy merge offerings.

### CODE REVIEW

**Comment by retronym** [comment]
ExtensionMethods LGTM; I assume you looked at the (as yet unmerged) backport of SI-6482, #1972,  in the opposite direction?

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
(sorry, deleted your comment accidentally)

I meant to refer to #1976, which seems to have the same conflict resolutions as this PR.

e.g. https://github.com/retronym/scala/commit/4ed88363f6867e5b4ebedfde10b88c0167f24f23#L0R165
https://github.com/retronym/scala/commit/4ed88363f6867e5b4ebedfde10b88c0167f24f23#L0R105

But that merge isn't part of 2.10.x yet.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
@retronym Sigh, I sure wish I'd seen that. Obviously I did see it since I reviewed it, but I didn't "see" it. I also wish I'd found it straightforward to resolve. But if I ended up with the same resolution, then I'll take it.

**Comment by retronym** [comment]
That resolution was pretty fresh, you probably reviewed it before I had to rebase. The merges are spookily similar.

**Comment by paulp** [comment]
You're right, there's no way mine isn't derived from yours. But I don't even know how that happened. Actually maybe I do... you're in my git repo by virtue of all pullrequest commits being in here, and when struggling with it one thing I did was

```
git log --all -- src/compiler/scala/tools/nsc/transform/ExtensionMethods.scala
```

I forgot that might turn up revisions which aren't master, 2.10.x, or me.

**Comment by paulp** [comment]
I'm going to merge this because I have to take a few days to focus on something which isn't the pull request queue and I don't want to leave this hanging.

**Pull request merged**
