### PR TITLE
Fix for SI-6597, implicit case class crasher.

### PR DESCRIPTION
**Pull request by paulp**
It seems to me like every call to scope.lookup in the
compiler is a latent bug. If a symbol is overloaded, you
get one at random. (See the FIXME comment in f5c336d5660
for more on this.)

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
LGTM with capital G

**Comment by jsuereth** [comment]
Any chance we can get this against 2.10.x?  The original ticket wasn't a regression, but man would I like the fix in 2.10.1

**Comment by paulp** [comment]
I think you can get it against 2.10.x just by clicking your heels three times and cherrypicking it.

**Comment by paulp** [comment]
But if #1521 turns up in master then I will be in a magnanimous mood and could move it myself.

**Comment by adriaanm** [comment]
I'll backport as my penance for taking so long with #1521. It's a lot to digest but I've been looking at it.

**Comment by paulp** [comment]
"I'll backport as my penance"

The one line backport! Don't beat yourself up like that, it's not like you killed someone.

**Comment by adriaanm** [comment]
Thanks, I feel better already.

**Pull request merged**
