### PR TITLE
part 2 of the big error reporting refactoring

### PR DESCRIPTION
**Pull request by adriaanm**
The big refactoring, pt 2. review by @retronym when the 2.11.2 dust has settled

### CODE REVIEW

**Comment by retronym** [comment]
This all is L-ing pretty GTM.

**Comment by dragos** [comment]
I'll have a look at the IDE failures

**Comment by adriaanm** [comment]
Thanks! I assume they are due to load since they start failing on a commit
that only adds a comment. Maybe we should load balance/throttle
jenkins better.

**Comment by adriaanm** [comment]
Successful rebuilds of the IDE tests:

https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7681/console
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7682/console
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7683/console
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7687/console
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7685/console
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7686/console

**Comment by adriaanm** [comment]
TODO: verify this doesn't break ensime

**Comment by hubertp** [comment]
LGTM

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@ca9f64d

**Comment by adriaanm** [comment]
Looks like IDE flakiness. I think this is ready for review. I'm going offline until the end of the week. Will have some time to deal with review feedback over the weekend.

**Comment by gkossakowski** [comment]
PLS REBUILD/pr-scala@ca9f64d

**Comment by gkossakowski** [comment]
@retronym, do you have enough bandwidth for this PR?

**Comment by retronym** [comment]
Yep, I reviewed the first parts already, and started yesterday reviewing the more recent commits. Will have some more time tomorrow to finish the review.

**Comment by retronym** [comment]
LGTM.

I've minimized the `AbstraliaMethodError` worked around in this PR and added it to a related open ticket: https://issues.scala-lang.org/browse/SI-6608

**Comment by gkossakowski** [comment]
Excellent! Merging.

**Comment by lrytz** [comment]
yay!

**Pull request merged**
