### PR TITLE
new bytecode emitter, GenBCode (2nd attempt)

### PR DESCRIPTION
**Pull request by magarciaEPFL**
Compared to the previous submission, this PR adds functionality to GenBCode in stages, with additional documentation.

Testing against the community build will provide more information than isolated tests.
Bytecode tests are by their very nature fragile (e.g., testing first that pattern matching emits a chain of jump, only to make sure a moment later that chain of jumps has been collapsed by GenBCode).

However concrete ideas and examples on how to balance usefulness vs brittleness are welcome.

And of course, reviews about the content proper of the PR are most welcome.

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
review by @gkossakowski or @JamesIry or @retronym or @paulp

**Comment by magarciaEPFL** [comment]
Explanation: one of the tests added in this PR, run/t7407b, was intended for GenBCode only, however the optimized build with options

```
-Yinline -Yclosure-elim -Yinline-handlers -neo:GenBCode -Yconst-opt
```

overrules the .flags file, and GenASM runs (and fails).

**Comment by retronym** [comment]
A note on the progression of commits: when I suggested to bring in the pipelined approach as a second step, I didn't spell out what I expected from the first step: it should be written in the most straight forward way possible, rather than being tailored to flick a switch to introduce the pipelining. I feel that the pipelining needs to be introduced in a way that doesn't obscure the core code, and think that we could get there if it were delayed to a later PR.

**Comment by magarciaEPFL** [comment]
I agree pipelining is an essential feature to GenBCode (but to the optimizer). Although queues and the Workers to process them appear rather prominently at the top of GenBCode.scala , in fact code generation proper is encapsulated elsewhere, in PlainClassBuilder and the two other builders (for mirros and bean classes). However, if it helps with readability, I can also postpone to follow-up commit the queues and Workers. They can even be left for the next PR (which is, Level 1 of the optimizer, where they are needed).

**Comment by magarciaEPFL** [comment]
A typo: I wanted to say, pipelining is _not_ essential to classfile building, but to realize a quick optimizer.

**Comment by magarciaEPFL** [comment]
As usual in these cases (I had already re-submitted before getting to see your comment) let's collect some more review comments at https://github.com/scala/scala/pull/2485 to include them all in the next submission.

**Pull request closed without merging**
