### PR TITLE
SI-7474 Parallel collections: End the exception handling madness

### PR DESCRIPTION
**Pull request by soc**
"What's wrong with an API which non-deterministically returns either
type A or type B(Set(A, ...))?"

This is pretty much what the exception handling behavior of the
parallel collections does: If exceptions of type A occur, either an
exception of type A or an exception of type B, wrapping multiple
exceptions of A's, are returned.

This behavior is incredibly broken and so unintuitive, that even
people writing tests don't handle it correctly.
See files/run/t5375.scala.

Concerning “non-deterministic”:
How many exceptions are observed before the operation is aborted
depends on the machine, the available cores and hyper-threading,
the operating system, the threadpool implementation and
configuration, the size of the collection and the runtime itself.

In fact, files/run/t5375.scala is failing on both jdk7u and Avian
because of this issue.

With this change, we just pass the "first" exception which occurs.
This seems to be what C# and Java both do, too.

“Why don't we wrap everything in CompositeThrowables?”
Even consistently returning CompositeThrowable doesn't make much
sense (because we have fail-fast behaviour and don't wait until
all tasks have finished or have thrown an exception).
Therefore, there is no useful semantic in having a
CompositeThrowable which returns "some" exceptions.

Either
a) gather and return all the exceptions or
b) just return one, instead of wrapping a non-deterministic
   number of exceptions into a completely unrelated wrapper type.

Considering that changing the parallel collection semantics in
such a profound way as described in a) is out of question, the
second option is chosen.

As soon as Scala targets Java > 7 Throwable#addSurpressed can be
used to add further exceptions to the one which gets returned.

### CODE REVIEW

**Comment by soc** [comment]
Review by @som-snytt and @axel22, please.

**Comment by soc** [comment]
I'll have to revise the commit message. Further investigation has shown that C# does something even more broken and elaborate.

**Comment by axel22** [comment]
I thought that the conclusion of the mailing list discussion was to have parallel collections always throw a composite throwable and having a special handler that traverses all the exceptions in a syntax-friendly way.

I do not see how `a)` is out of the question.
People who do exception handling on parallel collections already are taking `CompositeThrowable` into account in their cases, and should handle it successfully after the change as well.

**Comment by soc** [comment]
As mentioned on the mailing list that I went the other way, after realizing that trying to aggregate exceptions didn't make any sense. The behavior is now in line with what Java 8 does instead of trying to replicate .NET's chaos with PLINQ.

a) Would mean that if we had a collection with 1.000.000 items and the first one failed, we would still process the other 999.999 items, just in case one of those would fail, too.

People who are only handling `CompositeThrowable` have broken code anyway, which they need to fix.

**Comment by axel22** [comment]
I don't think you have to process all the elements - as soon as the first one fails, you can inform the other threads that they can stop working.
If some of them in the meantime produced some additional exceptions, these can be included in the resulting exception.

I can imagine cases where you are interested only in the first exception (e.g. you're interested only in whether the operation works, and you'll fix one exception at a time), as well as the cases where you want all of them (e.g. you want to log all of them so that they can be fixed all at once later - note that you will never have more than the number of workers exceptions).
Perhaps the right solution is to provide both through a setting the `TaskSupport` object and default to, say, taking only the first exception.

**Comment by soc** [comment]
> I don't think you have to process all the elements - as soon as the first one fails, you can inform the other threads that they can stop working.
> If some of them in the meantime produced some additional exceptions, these can be included in the resulting exception.

That's exactly the point I'm making: `CompositeException` as-is is completely worthless. Either we want _all_ failures or _one_, not something non-deterministic in-between.
As _all_ seems to be crazy, take _one_ and don't bother wrapping it, because it is _one_ exception anyway.
There is no useful semantic which can be gained from accumulating _some_ exceptions. You can't use it for control-flow, you can't use it for debugging, etc. It's like a `NullPointerException`. You don't catch those, you fix them and test again.

The thing I'm proposing is simple, deterministic, in line with sequential collections and in line with Java 8 `parallel()`.
I think adding more settings is out of question. No one tests non-default stuff anyway and I'd like to stop shipping broken code.

**Comment by axel22** [comment]
Well, my argument and the alternate design proposed on the mailing list discussion still stand. If you want a use-case - logging is a valid use-case for catching more than a single exception.

Since I wouldn't like to prolong this argument too much and the alternative configuration can be added later - LGTM.

**Comment by soc** [comment]
Ok, let me just adjust the commit message before anything is pulled or merged ...

**Comment by soc** [comment]
Done.

**Comment by JamesIry** [comment]
@soc, needs a rebase

**Comment by soc** [comment]
@JamesIry Done.

**Comment by JamesIry** [comment]
@soc gracias

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Pull request merged**
