### PR TITLE
SI-7848 Xlint says what looks interpolated

### PR DESCRIPTION
**Pull request by som-snytt**
The motivating use case was an Expecty debug string
getting flagged for `$eq`.

The test case demonstrates a different bug, in which
the position of the literal tree is changed when typer
gets rid of the unused local, so that when the tree is
re-typed in erasure, a second, spurious warning is
emitted at the start of the method. Specifically, the
second warning is not suppressed because of the
different position.

### CODE REVIEW

**Comment by retronym** [comment]
Relatedly, we could also turn off the warning on the grounds the `eq` requires arguments.

Roughly:

``` diff
-context.lookupSymbol(n, _ => true).symbol.exists
+
+ def requiresArgLists(sym: Symbol) = sym.paramss match {
+  case Nil | ListOfNil => false
+  case (p :: _) :: Nil if p.isImplicit => false
+  case _ => true
+}
+context.lookupSymbol(n, _ => true).symbol.alternatives.exists(sym => !requiresArgLists(sym))
```

**Comment by retronym** [comment]
Far more tangentially related, today I fell prey to:

``` scala
val x = 0
s"""
${foo($x)}
"""
```

Okay, it's a compiler error so after a little head scratching one figures it out. But a super nice compiler might offer a suggestion.

**Comment by som-snytt** [comment]
I'll add the turn-off here.

I wanted a macro sic"$foo" or stat"$foo" called the unterpolator, to satisfy Xlint and also for the hypothetical compiler switch to default to s"$foo" on uninterpolated "$foo".

That doesn't work if foo must be available; I was going to investigate whether a macro could fix things before typing of the args happens. Maybe that will be tangentially related.

I've often thought Xlint needs modes.  With paulp off the clock, one could sneak in -Xlint:super-nice to supplement the default voice.  Just kidding.  I did just notice that I can't think of a word for that default mode, though.

**Comment by retronym** [comment]
The breaking IDE build: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/2205/ is due to a bad commit in the history which has since been fixed on master. Could you please rebase to be sure?

**Comment by som-snytt** [comment]
I'll rebase and fix:

```
scala> { def foo = "x" ; s"hi $$foo" }
<console>:8: warning: `$foo` looks like an interpolated identifier! Did you forget the interpolator?
              { def foo = "x" ; s"hi $$foo" }
```

**Comment by retronym** [comment]
Tests passed:

6ff756  https://scala-webapps.epfl.ch/jenkins/job/pr-scala/2719/
40d57d  https://scala-webapps.epfl.ch/jenkins/job/pr-scala/2763/
a5bae8  https://scala-webapps.epfl.ch/jenkins/job/pr-scala/2761/

**Comment by retronym** [comment]
LGTM.

**Comment by som-snytt** [comment]
Hey, DNLGTM, I just went to rebase and noticed the premature merge.  (Should have closed before.)

**Comment by retronym** [comment]
Sorry, I've been drowning in kitty litter today. Please submit the followup as a separate pull request.

**Pull request merged**
