### PR TITLE
Respect `java.lang.Deprecated` annotation even in Scala sources

### LINKED ISSUE #12845: Scalac should notice Java Deprecated on Scala program elements
## Reproduction steps

Scala version: 2.13.11

```scala
scala> @Deprecated def f = 42
def f: Int

scala> f
val res0: Int = 42
```

## Problem

`scalac` does nothing with `@Deprecated` on Scala elements.

It should either warn that it is a typo for `@deprecated` or just use it.

Noticed at https://github.com/scala/bug/issues/12714#issuecomment-1677824530

### PR DESCRIPTION
**Pull request by kapunga**
Fixes scala/bug#12845
Removes the restriction of `java.lang.Deprecated` to just Java source.

### CODE REVIEW

**Comment by SethTisue** [comment]
(Thanks! Note that we're currently winding up 2.13.12, so it might be a few weeks before we consider this for 2.13.13.)

**Comment by He-Pin** [comment]
I missed this very much, thanks.

**Comment by SethTisue** [comment]
It may be confusing to users that both annotations exist and are supported. May I suggest adding something to the Scaladoc for the Scala annotation that explains why one might wish to use it instead of the Java one...?

**Comment by lrytz** [comment]
@kapunga are you interested in coming back to this (see Seth's comment above)?

Also, could you extend the existing lint for deprecations to suggest using `scala.deprecated` when encountering Java's Deprecated? See here:

https://github.com/scala/scala/blob/v2.13.12/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L4206-L4207

Currently (with this PR):

```scala
➜ sandbox qs -Xlint
Welcome to Scala 2.13.12-20230828-034507-4cb2928 (OpenJDK 64-Bit Server VM, Java 17.0.6).
Type in expressions for evaluation. Or try :help.

scala> @deprecated def f = 1
        ^
       warning: Specify both message and version: @deprecated("message", since = "1.0")
def f: Int

scala> @Deprecated def g = 1
def g: Int

scala> g
       ^
       warning: method g is deprecated
val res0: Int = 1
```

**Comment by som-snytt** [comment]
> it might be a few weeks before we consider this

that is dog weeks

**Comment by lrytz** [comment]
Pushed my changes. Review by @som-snytt?

**Review by som-snytt — APPROVED** [review]
Very accommodating. It's possible the commit title at-mentions Herr Edeling.

**Comment by som-snytt** [comment]
To clarify, Daniel Edeling's handle is "deprecated".

**Pull request merged**
