### PR TITLE
Moving ActorRef API to scala.concurrent.

### PR DESCRIPTION
**Pull request by vjovanov**
Moving ActorRef API to scala.concurrent. 

Adding Actor Migration Kit tests.

Fixed SI-6305 which was also accidentally merged to master.  

Review by @phaller

### CODE REVIEW

**Comment by phaller** [comment]
I think after moving those files we're good.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL.

**Comment by vjovanov** [comment]
Fixed the reveiw comments.

**Comment by phaller** [comment]
LGTM

**Comment by gkossakowski** [comment]
PLS REBUILD pr-rangepos

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Pull request merged**
