### PR TITLE
SI-6434 Pretty print function types with by name arg as (=> A) => B

### PR DESCRIPTION
**Pull request by JamesIry**
We were pretty printing a function type with one by name arg as
=> A => B, but because => is right associative that's formally
equivalent to => (A => B) and that's entirely a different thing. This
commit changes the pretty printer in Typers.scala to check for a
byname argument on a function type and wrap it in parens. A REPL test
is included.

review @paulp

### CODE REVIEW

**Comment by paulp** [comment]
Wonderful!

**Comment by JamesIry** [comment]
This was merged prematurely as it broke test/files/run/reify_magicsymbols.scala

**Comment by paulp** [comment]
So I have observed. Well, this is life without infrastructure.

**Comment by paulp** [comment]
It's funny, I broke the build a lot less (a LOT less) back before I had "help" from the pull request bot.

**Comment by JamesIry** [comment]
https://github.com/scala/scala/pull/1967

**Pull request merged**
