### PR TITLE
Remove special casing of sourcepath when settings.isScaladoc.

### PR DESCRIPTION
**Pull request by vigdorchik**
It's a poor coincidence that scaladoc uses sourcepath for its purposes, that has
to be fixed in 2.11, but for 2.10 it makes sense to simply remove that code. [nomerge]

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @VladUreche.

**Comment by VladUreche** [comment]
LGTM

**Comment by VladUreche** [comment]
Hi Eugene, why did you close the PR? Did you find a better way to do this?

**Pull request closed without merging**
