### PR TITLE
Incorrect parsing of -Xplugin

### PR DESCRIPTION
**Pull request by dotta**
# Commit Message

-Xplugin value passed by the Eclipse IDE are incorrectly parsed when it contains whitespaces.

Assume -Xplugin is given the value (in the Eclipse IDE)

  C:\Programs Files\plugins\Aplugin.jar C:\Programs Files\plugins\Bplugin.jar

Calling `tryToSetFromPropertyValue` with the above value will always result
in a total mess, no matter what, because it will split the string at
whitespaces.

The proposed solution is to change the implementation of
`tryToSetFromPropertyValue` to use `,` (comma) as the splitting character

Further, I'm quite convinced that the current implementation of
`MultiStringSetting.tryToSetFromPropertyValue` has never worked, that is why I
did not create an overload of `tryToSetFromPropertyValue` where the splitting
character (or string) can be passed as argument.

For more information, there is also an Eclipse Scala IDE ticket associated to this issue:

  http://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1000917
# Note

Ideally, this should also be merged in 2.9.x (and be available in the next 2.9.2 release).

### CODE REVIEW

**Comment by paulp** [comment]
For future reference (I know this is not documented or even hinted at anywhere) when you intend something for multiple branches it is easiest by far if you work on the base-2.8.x-2.9.x-2.10.x branch, which I made for this purpose and is in the git histories of all three branches, so I can merge it directly into each of the three others.f

**Comment by paulp** [comment]
What the... splitting on whitespace.  Boy do we need a proper argument parser.

**Comment by paulp** [comment]
It's in the 2.9.x branch too.

**Comment by dotta** [comment]
Thanks a lot Paul. Splitting at whitespaces was indeed a great idea for introducing a sure bug that most likely only shows up on Windows ;)

I didn't know about the base-2.8.x-2.9.x-2.10.x branch, I will make sure to use it next time. Maybe it is worth mentioning this in the README.

**Comment by paulp** [comment]
> Maybe it is worth mentioning this in the README.

Ha ha, documentation!

**Pull request merged**
