### PR TITLE
SI-8447 fix TypeTree printing (2.11.x)

### PR DESCRIPTION
**Pull request by VladimirNik**
Added TypeTree printing based on tpe to CodePrinter (if original is not available) - [SI-8447](https://issues.scala-lang.org/browse/SI-8447)

Previous [version](https://github.com/scala/scala/pull/3710) of this pull request

### CODE REVIEW

**Comment by VladimirNik** [comment]
Review by @xeno-by @densh

**Comment by xeno-by** [comment]
@retronym Could you also take a look please?

**Comment by lrytz** [comment]
ping @xeno-by - does this look good to you?

**Comment by xeno-by** [comment]
I'd like to have some time to do a proper review, but unfortunately I still can't get it. How about we defer until ScalaDays?

**Comment by lrytz** [comment]
That's fine for me, thanks.

**Comment by adriaanm** [comment]
LGTM -- looks like a pretty straightforward cleanup to me.

**Pull request merged**
