### PR TITLE
SI-5920 enables default and named args in macros

### PR DESCRIPTION
**Pull request by xeno-by**
When producing an initial spec for macros two years ago, we sort of glossed
over named/default arguments in macro applications, leaving them for future work.

Once the aforementioned future has come, I’ve made several attempts at
making things operational (e.g. last summer), but it’s always been unclear
how to marry the quite complex desugaring that tryNamesDefaults performs
with the expectations of macro programmers to see unsugared trees
in macro impl parameters.

Here’s the list of problems that arise when trying to encode named/default
arguments of macro applications:
1) When inside macro impls we don’t really care about synthetic vals
that are typically introduced to preserve evaluation order in non-positional
method applications. When we inline those synthetics, we lose information
about evaluation order, which is something that we wouldn’t like to lose
in the general case.
2) More importantly, it’s also not very exciting to see invocations of
default getters that stand for unspecified default arguments. Ideally,
we would like to provide macro programmers with right-hand sides of those
default getters, but that is: a) impossible in the current implementation
of default parameters, b) would anyway bring scoping problems that we’re
not ready to deal with just yet.

Being constantly unhappy with potential solutions to the aforementioned
problems, I’ve been unable to nail this down until the last weekend,
when I realized that: 1) even though we can’t express potential twists in
evaluation order within linearly ordered macro impl params, we can use
c.macroApplication to store all the named arguments we want, 2) even though
we can’t get exactly what we want for default arguments, we can represent
them with EmptyTree’s, which is not ideal, but pretty workable. That’s
what has been put into life in this commit.

As a pleasant side-effect, now the macro engine doesn’t have to reinvent
the wheel wrt reporting errors about insufficient arg or arglist count.
Since this logic is intertwined with the tryNamesDefaults desugaring,
we previously couldn’t make use of it and had to roll our own logic
that checked that the number of arguments and parameters of macro applications
correspond to each other. Now it’s all deduplicated and consistent.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
PLS REBUILD/pr-scala@f5f921f

**Comment by xeno-by** [comment]
PLS SYNCH

**Comment by xeno-by** [comment]
Rebased the pull request.

**Comment by xeno-by** [comment]
@retronym Here's another more or less easy one.

**Comment by xeno-by** [comment]
Rebased again.

**Comment by xeno-by** [comment]
PLS REBUILD/pr-scala@c32dee8

**Comment by xeno-by** [comment]
Omg IDE jobs are producing a tremendous amount of spurious failures these days. Is this possible to work around? /cc @retronym

**Comment by xeno-by** [comment]
PLS SYNCH

**Comment by xeno-by** [comment]
@retronym Everything's green. Can be reviewed.

**Comment by retronym** [comment]
LGTM

It's not a small change, but the chance of regressions is mitigated by the fact the names/default macro application used to be an error. It's also good to get rid of the ad-hoc varargs handling in macro expansion and use the regular logic. The test coverage also looks healthy.

I think we'll revisit the mechanics in 2.12 to avoid the "undo" part; maybe the names/defaults transformation can leave some breadcrumbs to make it easier the application with all defaults resolved, but without the qualfier/argument lifting.

**Comment by julienrf** [comment]
How can I use this feature? Will it be in the next 2.11 milestone? Is it already available in paradise?

**Comment by xeno-by** [comment]
Will be available in 2.11.0-RC1. Not yet implemented in paradise, and probably would be quite difficult to just hack it onto paradise without backporting to 2.10.5.

**Comment by xeno-by** [comment]
@julienrf This PR has been reverted and will have to wait for 2.11.1-RC1 (or 2.11.1-SNAPSHOT, to be more precise).

**Comment by julienrf** [comment]
Yes, I saw that :)

**Comment by xeno-by** [comment]
Superseded by https://github.com/scala/scala/pull/3684

**Pull request merged**
