### PR TITLE
Avoid unused import warnings in REPL

### LINKED ISSUE #7722: REPL + -Ywarn-unused-import (or, since 2.12.2 `-Xlint`) = spurious "Unused import" warnings
```
Welcome to Scala version 2.11.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0-ea).

scala> import java.util.ArrayList
<console>:7: warning: Unused import
       import java.util.ArrayList
                        ^
```

oh you silly REPL!

### PR DESCRIPTION
**Pull request by som-snytt**
Context avoids spurious warnings for history imports, REPL's bread and butter.

When compiling user input that is only imports, turn off the warning. (It would always warn, trivially.)

Users builds may have mitigations for this which may now be removed.

Fixes scala/bug#7722

### CODE REVIEW

**Comment by sjrd** [comment]
Related in Scala 3: https://github.com/scala/scala3/pull/20310

**Comment by som-snytt** [comment]
@sjrd that is what inspired this rash undertaking

**Review by lrytz — APPROVED** [review]
QoL!

**Comment by SethTisue** [comment]
nice to finally have this fixed 👍

**Pull request merged**
