### PR TITLE
Merge 2.12.x to 2.13.x [ci: last-only]

### PR DESCRIPTION
**Pull request by SethTisue**
merge conflicts were trivial except for the `isEmacsShell` stuff in the REPL. I resolved it by removing `isEmacsShell` entirely, since it was deprecated in 2.12.6.

```
% git fetch origin                                       
% git checkout -b merge-2.12.x-to-2.13.x-20180428
Switched to a new branch 'merge-2.12.x-to-2.13.x-20180428'
% export MB=$(git merge-base origin/2.13.x origin/2.12.x)
% git log --graph --oneline --decorate $MB..origin/2.12.x | tail -r
* 957780fa25 Don't compute `locations` in macroclassloader cache
* cb5f0fc1ba Merge pull request #6446 from scalacenter/ticket/scala-dev/458
|/  
| * 4053968c5a [nomerge] Use temporary repository for bootstrapping
| * 46596b42a5 [nomerge] Streamline the bootstrap script
|/|   
| |/  
|\ \  
* |   8120af87ca Merge pull request #6472 from lrytz/wip/local-bootstrap-repo
| |/  
| * | 1f7468f0f3 Fix up embarrassing typo.
|\ \  
* |   d032bf65c4 Merge pull request #6474 from hrhino/logic-error
|  /  
| * | c6544d408b Explicit type annotations and !isEmpty replace with nonEmpty
|\ \  
* |   022588844f Merge pull request #6355 from sh0hei/explicit-type
| |/  
| * | 109f03e56c No warn-unused:params for unimplemented method
|\ \  
* |   32fddebc24 Merge pull request #6384 from som-snytt/issue/nowarn-unimpl
| |/  
| * | 532c56d446 Add a `completions` command similar to the one found in sbt
|\ \  
* |   b57e88a440 Merge pull request #6379 from hvesalai/tmp/completionsCmd
| |/  
| * | d078c498ec Bump JarJar version to avoid invalid bytecode on Java9
|\ \  
* |   d2c0864198 Merge pull request #6477 from retronym/bump/jarjar
| * 41d81b1bf6 Apply no warn attachment to binds
| * 0e8cf52860 Rename attachment to NoWarn
|\  
*   c9c88fa0df Merge pull request #6473 from som-snytt/issue/refute
* 84112e8029 Update to Jline 2.14.6 (#6478)
|/  
| * 43653fe789 [backport] Remove mentions of named functions in Return Expressions
| * 9046d698a3 [backport] restrict applicability to user defined methods
| * 0a8daf257c Spec: say "method" instead of "function"
| * 464df60bb2 Spec: update dynamic selection
| * 3c81f1bfb6 Spec-ify the spec update
|/|   
| |/  
|\ \  
* |   cb320be595 Merge pull request #6519 from adriaanm/spec-method
| * b0b684e578 Update test case to changed JDK behavior
|/|   
| |/  
|\ \  
* |   409ed5fdac Merge pull request #6548 from lrytz/b10835
| |/  
| * | 70d41ffe63 Fix tests on windows
|\ \  
* |   7547709b60 Merge pull request #6562 from lrytz/windows-build
| * 340b899536 Deprecate Float range and Double range
|\  
*   d7ae7a8b96 (tag: v2.12.6) Merge pull request #6550 from eed3si9n/wip/deprecate-float-range
|/  
| * 82a3a2e729 bump version to 2.12.7, restarr onto 2.12.6
|\  
*   ed50887242 (origin/2.12.x) Merge pull request #6568 from SethTisue/restarr-onto-2.12.6
% git log --merges --oneline --decorate $MB..origin/2.12.x | tail -r
cb5f0fc1ba Merge pull request #6446 from scalacenter/ticket/scala-dev/458
8120af87ca Merge pull request #6472 from lrytz/wip/local-bootstrap-repo
d032bf65c4 Merge pull request #6474 from hrhino/logic-error
022588844f Merge pull request #6355 from sh0hei/explicit-type
32fddebc24 Merge pull request #6384 from som-snytt/issue/nowarn-unimpl
b57e88a440 Merge pull request #6379 from hvesalai/tmp/completionsCmd
d2c0864198 Merge pull request #6477 from retronym/bump/jarjar
c9c88fa0df Merge pull request #6473 from som-snytt/issue/refute
cb320be595 Merge pull request #6519 from adriaanm/spec-method
409ed5fdac Merge pull request #6548 from lrytz/b10835
7547709b60 Merge pull request #6562 from lrytz/windows-build
d7ae7a8b96 (tag: v2.12.6) Merge pull request #6550 from eed3si9n/wip/deprecate-float-range
ed50887242 (origin/2.12.x) Merge pull request #6568 from SethTisue/restarr-onto-2.12.6
% git merge -sours 4053968c5a
Merge made by the 'ours' strategy.
% git merge -sours 46596b42a5
Merge made by the 'ours' strategy.
% git merge origin/2.12.x
Auto-merging versions.properties
CONFLICT (content): Merge conflict in versions.properties
Removing test/files/run/t2873.check
Auto-merging src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
CONFLICT (content): Merge conflict in src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
Auto-merging src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
Auto-merging src/reflect/scala/reflect/internal/TreeGen.scala
Auto-merging src/library/scala/collection/immutable/Range.scala
Auto-merging src/compiler/templates/tool-windows.tmpl
Auto-merging src/compiler/templates/tool-unix.tmpl
Auto-merging src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
Auto-merging src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
Auto-merging spec/06-expressions.md
CONFLICT (content): Merge conflict in spec/06-expressions.md
Auto-merging project/plugins.sbt
Auto-merging build.sbt
CONFLICT (content): Merge conflict in build.sbt
Recorded preimage for 'build.sbt'
Recorded preimage for 'spec/06-expressions.md'
Recorded preimage for 'src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala'
Recorded preimage for 'versions.properties'
Automatic merge failed; fix conflicts and then commit the result.
% emacs versions.properties 
% git add -u versions.properties
% emacs spec/06-expressions.md 
% git add -u spec/06-expressions.md
% emacs build.sbt 
% git add -u build.sbt
% e src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
% e src/repl-frontend/scala/tools/nsc/interpreter/shell/ShellConfig.scala
% e src/compiler/scala/tools/nsc/Properties.scala
% e src/repl-frontend/scala/tools/nsc/interpreter/shell/ShellConfig.scala
% git add -u
% git commit
```

### CODE REVIEW

**Comment by SethTisue** [comment]
gah, `:completions` doesn't work. investigating...

**Comment by SethTisue** [comment]
something in Adriaan's refactorings made it so that `ReplTest` doesn't see the `override def shellCompletion` in `ILoop.scala`, so completion of REPL commands themselves isn't available. This results in an exception when it tries to go down the Scala-code-completion path on a REPL command, and then that exception is suppressed by the `catch { case NonFatal(e) => ...` in `ReplCompletion#codeCompletion` so you get no output.

**Comment by SethTisue** [comment]
okay that wasn't tooooo hard to straighten out

**Comment by SethTisue** [comment]
integrate-windows green again at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/544/

**Comment by SethTisue** [comment]
@hvesalai heh, I forgot about #6382 here

**Comment by retronym** [comment]
I believe there was a merge error here:

```
% git log --graph --oneline --decorate $MB..origin/2.12.x | tail -r
* 957780fa25 Don't compute `locations` in macroclassloader cache
* cb5f0fc1ba Merge pull request #6446 from scalacenter/ticket/scala-dev/458
|/  
| * 4053968c5a [nomerge] Use temporary repository for bootstrapping
| * 46596b42a5 [nomerge] Streamline the bootstrap script
|/|   
| |/  
|\ \  
* |   8120af87ca Merge pull request #6472 from lrytz/wip/local-bootstrap-repo
```

```
% git merge -sours 4053968c5a
Merge made by the 'ours' strategy.
% git merge -sours 46596b42a5
Merge made by the 'ours' strategy.
```

The changes in 957780fa25 didn't make it to 2.13.x. I think the first merge command should have been `git merge cb5f0fc1ba`. I'll submit a PR to bring that across. We really need to get Java 10 into our build matrix in some capacity.

**Pull request merged**
