### PR TITLE
In-source sbt compiler bridge [ci: last-only]

### PR DESCRIPTION
**Pull request by lrytz**
Previous attempt: https://github.com/scala/scala/pull/8531. I think it was just closed because there was no strong reason to do it.

This time there is a good reason: to support "quick fixes" / code actions that the Scala 2.13.12 compiler delivers with warnings and errors, the bridge needs to be changed. This cannot be done in a source-compatible manner, i.e., the bridge sources need to be different for 2.13.11 and 2.13.12. Instead of having multiple versions of the bridge sources for 2.13 compiler versions, releasing the bridge as binary with every Scala release might be easier. Details at https://github.com/sbt/zinc/discussions/1214.

This PR includes the git history of the compiler bridge. Documentation how it was done:
  - https://github.com/lrytz/scala/commit/80e8df93f854e8bb5ba7971c2af4d85671ccda08
  - https://github.com/lrytz/scala/commit/b8cebccd3f93fd90ab1f8e653dd98d3e63c3b496

The bridge tests from the zinc repo were also migrated (without history).

Advantages of in-sourcing the bridge
  - No more "'compiler-interface' not yet compiled..." for users
  - We can more easily improve / clean up the bridge sources without worrying about older compilers
  - Alignment with what Scala 3 does

A new `scala2-sbt-bridge` artifact will be published with every Scala release.

New sbt releases can use the binary bridge instead of compiling it from source.

The binary bridge can be used with existing sbt versions by setting the `scalaCompilerBridgeBinaryJar`. Here's how I tried it - probably there are more elegant solutions:

```scala
scalaCompilerBridgeBinaryJar := {
  val b = (nix / Compile / dependencyClasspath).value.filter(_.data.getName == "scala2-sbt-bridge.jar").headOption
  b.map(_.data)
}
val nix = project.in(file("nix")).settings(
  autoScalaLibrary := false,
  libraryDependencies += "org.scala-lang" % "scala2-sbt-bridge" % scalaVersion.value
)
```

~I haven't managed yet to make an end-to-end test for quick fixes with metals in VS code, WIP / discussion here https://github.com/sbt/zinc/discussions/1214#discussioncomment-6468903~

### CODE REVIEW

**Comment by lrytz** [comment]
After more testing, this is looking fine. The binary bridge seems to work as intended in a test project, I can compile, doc, run the Scala repl in the sbt console.

We managed to get a code action from the Scala compiler all the way to VS Code and apply it.

fix

------

There are a couple of changes that still need to happen for code actions to "just work" with 2.13.12:
  - [ ] The semanticdb compiler plugin overrides the wrong `doReport` method, [details here](https://github.com/sbt/zinc/discussions/1214#discussioncomment-6486775)
    - Once 2.13.12 is out, Tomasz will apply the necessary patch and then back-release semanticdb _2.13.12
    - This patch is not needed for this PR, it's for https://github.com/scala/scala/pull/10406 which added the `CodeAction` parameter to reporters
  - [ ] Bloop needs to be changed to [use the new binary bridge released with the compiler](https://github.com/scalacenter/bloop/blob/41a45f28f2ac983a3e18c712e8af488702a33be0/backend/src/main/scala/sbt/internal/inc/BloopComponentCompiler.scala#L46-L68)
  - [x] Bloop currently seems to drop the actual code changes from "actions", so in VS code we see "Quick Fix" available, but no change is applied. @tgodzik is looking into that.
    - Fixed in https://github.com/scalacenter/bloop/pull/2122 (not yet released as of bloop 1.5.9)
  - [ ] sbt needs to be changed to [use the binary bridge](https://github.com/sbt/sbt/blob/fe4c5159a127dd6261c1c2f53942458261b7487b/zinc-lm-integration/src/main/scala/sbt/internal/inc/ZincLmUtil.scala#L85-L100), also other build tools that use zinc. But nothing will break if they don't do that immediatly, zinc will continue to ship with the bridge sources.
  - [x] When using `sbt` as build server, problems are sent via bsp twice. The second report (which clears out the first one) doesn't contain quick fixes, [details here](https://github.com/sbt/zinc/discussions/1214#discussioncomment-6488763), I'm checking with @eed3si9n how to best address that.
    - Fixed with sbt 1.9.3 (https://github.com/sbt/zinc/pull/1226) and the last commit of this PR

From these changes, only the last one will require a follow-up in the bridge source code. Even so, this PR is ready for review (only the last 10 commits, the rest is zinc git history).

**Comment by lrytz** [comment]
I added a commit to avoid dropping code actions in problems reported through the `AnalysisCallback` (vs the reporter), see https://github.com/sbt/zinc/pull/1226. Same PR for dotty: https://github.com/lampepfl/dotty/pull/18322.

With this we can get quick fixes to work reliably in VS code. The remaining changes to make them work out of the box are outside of scala/scala and may need to wait for 2.13.12 to be released. So I think this PR is ready @SethTisue.

To get it working:
  - Use VS code with metals extension 1.24.1, metals server 1.0.0
  - Check out this PR
  - Apply this patch to work around the SemanticDB issue (see comment above): https://gist.github.com/lrytz/b81535bdd4541f5856f250c317dfad14
  - in sbt run `setupPublishCoreNonOpt` and `publishLocal`
  - create an sbt project using `sbt.version=1.9.3` with the following build definition:

```
ThisBuild / scalaVersion := "locally-published-scala-version"

ThisBuild / scalacOptions ++= List("-deprecation")

semanticdbCompilerPlugin := ("org.scalameta" % "semanticdb-scalac_2.13.11" % semanticdbVersion.value)

scalaCompilerBridgeBinaryJar := {
  val b = (nix / Compile / dependencyClasspath).value.filter(_.data.getName == "scala2-sbt-bridge.jar").headOption
  b.map(_.data)
}

val nix = project.in(file("nix")).settings(
  semanticdbEnabled := false,
  autoScalaLibrary := false,
  libraryDependencies += "org.scala-lang" % "scala2-sbt-bridge" % scalaVersion.value
)
```

  - Import the project in VS Code using `sbt` as build server (not bloop)
  - `def f { println }` should give two quick fixes (procedure syntax, auto-application)

**Comment by lrytz** [comment]
Added one more commit to mark `scala2-sbt-bridge`'s dependencies (scala-compiler and compiler-interface) "provided". This aligns with Scala 3: https://central.sonatype.com/artifact/org.scala-lang/scala3-sbt-bridge/3.3.0?smo=true.

The difference was discovered by @tgodzik while updating bloop to use the binary interface.

**Comment by SethTisue** [comment]
@eed3si9n @tgodzik do either of you have any concerns you want to raise before this is merged? I can't think of any objection or concern to raise, but the interaction of the compiler with build tools isn't an area where I have much expertise

**Comment by eed3si9n** [comment]
I am guessing that the details are ok, but I'd like to communicate the tradeoff here.

Neither compiler nor Zinc promises API, and both can independently add or break features. Thus far Scala 2.x has relied on Zinc's bridge that is specific to the latest Zinc. By  switching to the binary bridge model (like Dotty), Scala 2.x will carry the responsibility of keeping up with the changes + end users will be forced to bump to the latest patch version to take advantage of the latest Zinc features.

**Comment by tgodzik** [comment]
> @eed3si9n @tgodzik do either of you have any concerns you want to raise before this is merged? I can't think of any objection or concern to raise, but the interaction of the compiler with build tools isn't an area where I have much expertise

Nothing from me, as far as I can see this should be simple to support in Bloop, The only issues might be the trade offs Eugene mentioned.

**Comment by SethTisue** [comment]
@eed3si9n thanks

@lrytz we're comfortable with that, yes?

After all, we remain committed to pumping out 2.13.x releases indefinitely.

(...from now until the heat death of the universe, under our "VLTS" (Very Long Term Support) designation, which we have scrawled on a mirror with lipstick for anyone to consult...)

**Comment by lihaoyi** [comment]
FWIW the Mill build tool has its own set of pre-compiled bridges that it checks for before falling back to on-demand compilation. It works great. If new Scala versions come with their own bridges then that would save us the hassle of manually publishing a new bridge every Scala release https://github.com/com-lihaoyi/mill/pull/2424

**Comment by smarter** [comment]
A cool thing you can explore doing once the compiler is responsible for calling into zinc is to start recording dependencies during typechecking, We've [just started doing this in Scala 3 to keep track of mirrors](https://github.com/lampepfl/dotty/pull/18310), but it could be used for macros and other areas where we tend to under-compile (though for macros especially we might need something like @lihaoyi's [bytecode-level target invalidation](https://github.com/com-lihaoyi/mill/pull/2417)).

In any case, I strongly recommend porting the [zinc scripted tests]( https://github.com/sbt/zinc/tree/develop/zinc/src/sbt-test)) along with the compiler bridge itself (for reference, in dotty we keep them in https://github.com/lampepfl/dotty/tree/main/sbt-test). This is useful for tracking new regressions of course, but it seems that zinc itself only runs its scripted tests on Scala 2.12 which has already led to undiscovered regressions in 2.13: https://github.com/sbt/zinc/issues/1229

**Comment by lrytz** [comment]
> @lrytz we're comfortable with that, yes?

IMO yes 👍

> I strongly recommend porting the [zinc scripted tests](https://github.com/sbt/zinc/tree/develop/zinc/src/sbt-test) along with the compiler bridge itself

Thanks, will take a look!

**Comment by SethTisue** [comment]
(Zinc scripted tests can wait for a separate PR.)

**Comment by SethTisue** [comment]
if anybody wants to test a published bridge (please do, if you can, so we know this is going to work for 2.13.12!), there's one here:

https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala2-sbt-bridge/2.13.12-bin-86f40c2/

Once 2.13.12 proper is out, its bridge will be on Maven Central, of course.

**Comment by SethTisue** [comment]
discussion thread for tooling authors: https://contributors.scala-lang.org/t/scala-2-13-12-in-source-sbt-compiler-bridge-clarifications/6289

**Pull request merged**
