### PR TITLE
This is a cleanup of scaladoc code.

### PR DESCRIPTION
**Pull request by vigdorchik**
It fixes the following inefficiences or code style violations:

```
- Explicit asInstanceOf calls.
- Boxing symbols instead of using plain NoSymbol.
- Matching `this` instead of late-binding.
```

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @VladUreche or @heathermiller.

**Comment by retronym** [comment]
Can you please edit the first commit comment to have a subject line that doesn't wrap?

```
Improve code style in the Scaladoc implementation.

It fixes the following inefficiences or code style violations:

    - Explicit asInstanceOf calls.
    - Boxing symbols instead of using plain NoSymbol.
    - Matching `this` instead of late-binding.
```

**Comment by vigdorchik** [comment]
Done.

**Comment by retronym** [comment]
PLS SYNCH

**Comment by retronym** [comment]
LGTM

**Pull request merged**
