### PR TITLE
new version of incremental compiler

### PR DESCRIPTION
**Pull request by odersky**
Take 2: Implemented functionality to invalidate classpath entries, to enable incremental compiles.

### CODE REVIEW

**Comment by odersky** [comment]
This replaces pull 641, fixing the problems that @pvlugter noted and generalizing to multiple classpath entries.
Review by @pvlugter, @harrah, @adriaanm

**Comment by odersky** [comment]
I noted I accidentally squashed the first installment that was already in master. Preparing a new one.

**Comment by adriaanm** [comment]
I don't think this commit was in master. GitHub would have complained if you tried to submit a pull request that doesn't merge cleanly.

**Comment by odersky** [comment]
On Wed, May 30, 2012 at 6:28 PM, Adriaan Moors <
reply@reply.github.com

> wrote:
> 
> I don't think this commit was in master. GitHub would have complained if
> you tried to submit a pull request that doesn't merge.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/scala/scala/pull/644#issuecomment-6014466

It only said it can't be merged automatically. I tried manually and got
conflicts because my previous squash included the original incremental
compiler commit, which was already pulled.
- Martin

## 

Martin Odersky
Prof., EPFL http://www.epfl.ch and Chairman, Typesafehttp://www.typesafe.com
PSED, 1015 Lausanne, Switzerland
Tel. EPFL: +41 21 693 6863
Tel. Typesafe: +41 21 691 4967

**Comment by pvlugter** [comment]
Should be closed again. Replaced by #645.

**Pull request closed without merging**
