### PR TITLE
Basic TreeSet/TreeMap benchmark

### PR DESCRIPTION
**Pull request by mkeskells**
baseline results for me are in https://gist.github.com/mkeskells/b2519ea2577d118fc93be65770fab705

### CODE REVIEW

**Comment by diesalbla** [comment]
@mkeskells Which sbt command did you use to get those results?

**Comment by mkeskells** [comment]
Sample commands are  in comments on the benchmark. --prof gc if the bit that give the gc and allocation stats. Also I sometimes use --rf csv to get csv output for graphing and more detailed analysis

**Comment by szeiger** [comment]
AFAIR the interface between `RedBlackTree` and `TreeMap`/`TreeSet` didn't really change with all the new algorithms and micro-optimizations I implemented in 2.13. It should be possible to use the 2.13 version in 2.12.

**Comment by mkeskells** [comment]
updated base benchmark in https://gist.github.com/mkeskells/76c6badb92a72c21f948990cee40b2ce

**Comment by mkeskells** [comment]
> AFAIR the interface between `RedBlackTree` and `TreeMap`/`TreeSet` didn't really change with all the new algorithms and micro-optimizations I implemented in 2.13. It should be possible to use the 2.13 version in 2.12.

I will update https://github.com/scala/scala/pull/8749 to pull in the 2.13 tree and improved TreeSet/TreeMap API

**Review by retronym — APPROVED** [review]

**Pull request merged**
