### PR TITLE
Added better warning message if you've forgotten to run pull-binary-libs...

### PR DESCRIPTION
**Pull request by jsuereth**
Fixes the issue where someone checks out the scala repository fresh and ANT just issues a big old ugly error message rather than _telling_ you that you have to run the pull-binary-deps.sh script.

Review by @soundrabbit or @paulp

### CODE REVIEW

**Comment by soc** [comment]
Thanks! I hit exactly this problem before.

**Comment by paulp** [comment]
I just had ant run the script.  I don't know what happens on windows though.

**Comment by jsuereth** [comment]
Probably better it issue a warning an then try to run the script....  should I alter this?

**Comment by paulp** [comment]
Well, it does echo a message.  I thought it would be a warning but it just says "info".  I guess echo level="warn" was a bad guess.

init.starr:
     [echo] Downloading bootstrap libs.  (To do this by hand, run ./pull-binary-libs.sh)
     [exec] Obtaining [/scratch/trunk4/docs/examples/plugintemplate/lib/scalatest.jar] from binary repository...
     [exec] Downloading from http://typesafe.artifactoryonline.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/8b6ba65c8146217333f0762087fe2340d572e832/docs/examples/plugintemplate/lib/scalatest.jar
     [exec] Obtaining [/scratch/trunk4/lib/ant/ant-contrib.jar] from binary repository...

**Pull request closed without merging**
