### PR TITLE
Generate links to external projects in scaladoc.

### PR DESCRIPTION
**Pull request by vigdorchik**
Review by @VladUreche.

### CODE REVIEW

**Comment by VladUreche** [comment]
LGTM given in #1400.

**Comment by VladUreche** [comment]
Btw, I filed https://issues.scala-lang.org/browse/SI-6430 for the TODO.

**Comment by VladUreche** [comment]
Sorry for closing, I accidentaly pressed Comment & Close instead of Comment.

**Comment by gkossakowski** [comment]
@VladUreche: Do you think it's safe to merge it given we are so close to RC1? I don't want to shut it down jus double checking because it's looks fairly big.

**Comment by VladUreche** [comment]
I think it's a safe bet to include it, because most of the stuff is just moving code around and refactoring it. And it only touches new scaladoc features (introduced in 2.10), which all come with comprehensive tests.

**Comment by gkossakowski** [comment]
Cool. Thanks for explanation. I'm feeling better about merging now.

**Pull request merged**
