### PR TITLE
Block bidirectional conversions in Scaladoc for JavaConversions

### PR DESCRIPTION
**Pull request by janekdb**
- Makes the list of conversions easier to scan
- Makes main comment formatting internally consistent

### CODE REVIEW

**Comment by janekdb** [comment]
Question for reviewers. Should the code style formatting be extended to `JavaConverters` and `DecorateAsJava`? IMHO the formatting of the conversion tables in `JavaConversions` is much easier to read than the bulleted styles in `JavaConvertors` and `DecorateAsJava`.

(`DecorateAsScala` gets no representation here as it's missing a main comment.)

I welcome discussion about consolidating the conversion documentation but really want to give readers improved formatting of existing documentation as a first step.

javaconvertors-and-friends-with-conversions-2 11

**Comment by janekdb** [comment]
Review by @heathermiller, @dickwall, @kanielc .

**Comment by janekdb** [comment]
@SethTisue - Build error is unrelated to change

    [ERROR] /home/jenkins/workspace/scala-2.11.x-integrate-ide/
    target/scala-ide/org.scala-ide.sdt.core/src/org/scalaide/core/internal/decorators/semantichighlighting/
    classifier/SafeSymbol.scala:5: error:
       object PimpedTrees is not a member of package scala.tools.refactoring.common
    [ERROR] import scala.tools.refactoring.common.PimpedTrees

**Comment by SethTisue** [comment]
@janekdb I've opened https://github.com/scala/scala-dev/issues/87 on the integrate-ide failure

**Comment by SethTisue** [comment]
I think this should target 2.12. Now that 2.11.8 is shipping, we're getting even more conservative about what happens on the 2.11.x branch. This looks like a nice improvement, but it is not actually a fix.

**Comment by janekdb** [comment]
Replaced by #5013

**Pull request closed without merging**
