### PR TITLE
SI-7810 Reflect private constructor

### PR DESCRIPTION
**Pull request by som-snytt**
`JavaMirror.constructorToJava` uses `getDeclaredConstructor` now
instead of `getConstructor`. This enables reflecting a private ctor.

### CODE REVIEW

**Comment by xeno-by** [comment]
lgtm

**Comment by gkossakowski** [comment]
I know you guys might hate me for that but: the test doesn't rely on any partest features. How about we convert it to JUnit test? Benefits: can be easily run from IDE (both Eclipse and IntelliJ) which includes debugging, is executed much, much faster than partest test.

**Comment by som-snytt** [comment]
I wouldn't mind junitizing, but junit tests can run in parallel, as a rule, and reflection is "not thread safe" in some capacity.

I don't actually use the IDE, but that wouldn't stop me from acquiescing in this change.

The extraneous check file did bug me.

**Comment by xeno-by** [comment]
Is JUnit now the official way to write new tests?

**Comment by gkossakowski** [comment]
@xeno-by: I'd argue that for unit tests, yes. For functional tests, partest is probably still the best choice. See #2920 for my take on testing. I'm open for discussing this and hearing your opinion.

**Comment by retronym** [comment]
I think the thread-safety issues in runtime reflection are sufficient to leave this in partest for now. Not sure if we use a parallel JUnit runner yet, but we should leave ourselves open to that possibility.

**Pull request merged**
