### PR TITLE
Merge 2.12.x to 2.13.x [ci: last-only]

### PR DESCRIPTION
**Pull request by retronym**
```
PICK    *   61701c2290 (origin/2.12.x) Merge pull request #8396 from retronym/topic/reflection-thread-safety-tycon
P       |\
P       | * 67e4d95df9 Fix thread safety issue in runtime reflection
P       | * 65122fadf1 Synchronize Symbol.typeSymbol in runtime reflection
SKIP    * |   3797ff9f08 Merge pull request #8397 from retronym/backport/phase-order-regression
S       |\ \
S       | * | f85b3877f8 [backport] A more conservative fix for phase assembly performance.
S       | * | 5d2f04f2d0 [backport] Revert buggy phase assembly optimizations
        | |/
PICK    * |   f93c5c334d Merge pull request #8317 from eed3si9n/wip/foldleft
P       |\ \
P       | * | 1a3e7ca37d [nomerge] Use foldLeft instead of /:
        |  /
SKIP    * |   3973a578d8 Merge pull request #8395 from exoego/2.12.x/panzoom
S       |\ \
S       | |/
S       |/|
S       | * 6981cfa228 Update jquery.panzoom to 3.2.3 which is compatible with jQuery 3.4.x
        |/
PICK    *   d70893c99c Merge pull request #8371 from retronym/faster/object-ref
P       |\
P       | * 5b487b7c98 Avoid ObjectRefs in two hot paths in compiler
P       *   4b81bc5565 Merge pull request #8357 from ashawley/library-rootdoc
P       |\
P       | * 6ca40bd4a8 Add links to GitHub for Scala modules [nomerge]
P       *   cb469a970e Merge pull request #8356 from retronym/ticket/11664-alloc
P       |\
P       | * 2ebec700bb Optimize the classpath implementation
P       | * 33f11d3e33 Benchmark for classpah lookup
P       *   c2a22307e6 Merge pull request #8358 from retronym/faster/all-settings-hashmap
P       |\
P       | * f6bfdf0046 Optimize setting initialization with large classpaths
PICK    *   55fc769b20 Avoid using the "lines" method. (#8333)
P       |\
P       | * 446f5c0752 Avoid using the "lines" method.
        |/
SKIP    * 89c2aec7fc [backport] Fix regression in phase assembly with consecutive ru… (#8347)
S       * 4d241c7bd1 Fix regression in phase assembly with consecutive runsRightAfter
```

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/9705/testReport/test.files/run_/colltest1_scala/ `scala.tools.partest.sbt.TestFailedThrowable: output differs  !!    1 - run/colltest1.scala`

**Comment by szeiger** [comment]
colltest1 just needs an `--update-check`. The number of deprecation warnings has been reduced by 2 due to the change in the file (replaced two deprecated calls by non-deprecated calls). I didn't dig into the history of the file in 2.12. The same thing should have happened there. I assume the corresponding change wasn't included because the number had already changed so there was a merge conflict.

**Comment by SethTisue** [comment]
(marked as blocker since 2.13.1 ought to include everything 2.12.10 does)

**Comment by retronym** [comment]
Restarted a stuck Travis job:

```
[warn] It would fail on the following inputs: FrameEntry(_, _, _), Incr(_, _, _), IntOp(_, _), Invoke(_, _, _, _, _), InvokeDynamic(_, _, _, _, _), Jump(_, _), Label(_), Ldc(_, _), LineNumber(_, _), LookupSwitch(_, _, _, _), NewArray(_, _, _), Op(_), TableSwitch(_, _, _, _, _), TypeOp(_, _), VarOp(_, _)

[warn]     val assignedInConstr = getMethod(k, "<init>").instructions.filter(_.opcode == Opcodes.PUTFIELD) map {

[warn]                                                                                                         ^

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received


```

Is this something we're seeing from time to time? I think I've seen it once or twice before?

We could [adjust](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) the timeout.

**Comment by SethTisue** [comment]
I know we've seen timeouts before, but I've never tried to track or investigate them. Especially lately, since general Travis-CI reliability went through a rough patch recently. I'll try to start paying attention again.

**Comment by SethTisue** [comment]
ticket on the Travis-CI timeouts: https://github.com/scala/scala-dev/issues/653

**Pull request merged**
