### PR TITLE
[Dates fixing]

### PR DESCRIPTION
**Pull request by FelAl**
Second part of fixed files.

@Ichoran
@adriaanm

### CODE REVIEW

**Comment by janekdb** [comment]
I suggest this message `[Fix Copyright Dates]` as a standard message to use when this is done.

The benefits are,
-  More specific than 'Dates`
- Uses imperative voice

See
https://github.com/scala/scala#user-content-git-hygiene
https://github.com/erlang/otp/wiki/Writing-good-commit-messages

> Write the summary line and description of what you have done in the imperative mode, that is as if you were commanding someone. Start the line with "Fix", "Add", "Change" instead of "Fixed", "Added", "Changed".

**Comment by FelAl** [comment]
Thank you for comment.
Done.

**Comment by FelAl** [comment]
Is there something wrong with this PR?

Or maybe I should to change something?
And there also https://github.com/scala/scala/pull/5119 .

**Comment by Ichoran** [comment]
This PR looks fine, but what about the PR with the tool (alone)?  I would tend to want that one merged first, followed by the two that actually contain the changed files.

**Comment by FelAl** [comment]
Ok

**Comment by lrytz** [comment]
agree, it would be good to have the tool in a separate commit, first.

**Pull request closed without merging**
