### PR TITLE
Remove dead code from `Global`.

### PR DESCRIPTION
**Pull request by gkossakowski**
This is clearly dead-code (`phaseTimings` is not referred
anywhere else in `Global.scala`) and it's safe to remove it since
`phaseTimings` is private.

This dead-code is leftover from 317a1056.

Review by @paulp.

### CODE REVIEW

**Comment by retronym** [comment]
`Phases#{Model, TimingModel}` become dead after this change, too.

**Comment by lrytz** [comment]
hope we reach a fixpoint before scalac vanishes!

**Comment by adriaanm** [comment]
lol

**Comment by paulp** [comment]
Right, there's no point in removing those two lines without removing the classes which they represent the only use of.

I will keep ER docs on call in case scalac gets close to vanishing. They can administer an extraneous code infusion in seconds.

**Comment by gkossakowski** [comment]
@retronym, @paulp: I deprecated `Phases` object. I didn't remove it right away because it's public. Let me know if I missed something else.

**Comment by retronym** [comment]
Personally, I would have just swung the axe. But this one might have already exceeded its review budget, so lgtm either way.

**Pull request merged**
