### PR TITLE
SI-8947 Avoid cross talk between tag materializers and reify

### PR DESCRIPTION
**Pull request by retronym**
After a macro has been expanded, the expandee are expansion are
bidirectionally linked with tree attachments. Reify uses the back
reference to replace the expansion with the expandee in the reified
tree. It also has some special cases to replace calls to macros
defined in scala-compiler.jar with `Predef.implicitly[XxxTag[T]]`.
This logic lives in `Reshape`.

However, the expansion of a macro may be `EmptyTree`. This is the case
when a tag materializer macro fails. User defined macros could do the
also expand to `EmptyTree`. In the enclosed test case, the error
message that the tag materializer issued ("cannot materialize
class tag for unsplicable type") is not displayed as the typechecker
finds another means of making the surrounding expression typecheck.

However, the macro engine attaches a backreference to the materializer
macro on `EmpytyTree`!

Later, when `reify` reshapes a tree, every occurance of `EmptyTree`
will be replaced by a call to `implicitly`.

This commit expands the domain of `CannotHaveAttrs`, which is mixed
in to `EmptyTree`. It silently ignores all attempts to mutate
attachments.

Unlike similar code that discards mutations of its type and position,
I have refrained from issuing a developer warning in this case, as
to silence this I would need to go and add a special case at any
places adding attachments.

Review by @xeno-by @densh

### CODE REVIEW

**Comment by xeno-by** [comment]
Thanks for the explanation! I've been indeed able to track `EmptyTree` to https://github.com/scala/scala/blob/bdae51d6a8f18a5456a32c350cb551d42a3cb6c6/src/compiler/scala/reflect/reify/Taggers.scala#L72. An unexpected fact is that `c.typecheck(EmptyTree)` actually succeeds, which skips `c.abort`.

My suggestion is three-fold:
1. How about we check for `EmptyTree` over there and just call `c.abort` if we encounter it? That would fix the problem at its root. 
2. Additionally, we could safeguard the line of code that does the attachment (https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/typechecker/Macros.scala#L619) by checking for CannotHaveAttrs.
3. Now, we could have attachment-related functionality in CannotHaveAttrs throw exceptions.

What do you think?

**Comment by retronym** [comment]
I like all of that, but I would prefer dev warnings to an error, as we do elsewhere in cannothaveattrs. Could I ask you to submit that?

**Comment by retronym** [comment]
@xeno-by I've added a commit with your suggestions. Could you please review?

**Comment by xeno-by** [comment]
LGTM

**Comment by retronym** [comment]
PLS REBUILD ALL

**Pull request merged**
