### PR TITLE
Eliminate LaTeX-style quotations from compiler output

### LINKED ISSUE #10253: Eliminate LaTeX-style quotations from compiler output
Some compiler messages use LaTeX-style quotations, for example:

```scala
scala> object T {
     |   def x = 0
     |   locally {
     |     import T.x
     |     def x = 1
     |   }
     | }
<console>:15: warning: imported `x' is permanently hidden by definition of method x
           import T.x
                    ^
defined object T
```

As you can see, this upsets GitHub's Scala syntax highlighter. What a convincing reason to change a programming language!

### PR DESCRIPTION
**Pull request by thestuckster**
changed orphan ' to `

fixed test cases after modifying compiler output

Fixes scala/bug#10253

### CODE REVIEW

**Comment by SethTisue** [comment]
replaces #6397

**Comment by SethTisue** [comment]
sorry @thestuckster, we should have merged this sooner, but now it needs rebasing. would you mind taking care of it? once done, I'll hit "merge" promptly.

**Comment by thestuckster** [comment]
@SethTisue  Thanks for the heads up! I'll get on it as soon as I can

**Comment by dwijnand** [comment]
@thestuckster I'm not sure how much this conflicted in April, but it currently conflicts with:

```
src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
src/compiler/scala/tools/nsc/settings/Warnings.scala
src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
test/files/neg/sd128.check
test/files/neg/t521.check
test/files/neg/t5429.check
test/files/neg/trait_fields_conflicts.check
test/files/run/MeterCaseClass.check
test/files/run/t6329_repl.check
test/files/run/t6329_repl_bug.check
```

Let me know if you don't have a chance to get to this, because I might be able to help push this through myself! 😁

**Comment by thestuckster** [comment]
I tried my best haha, this is a pretty big code base to rebase into so I might have missed something some where

**Comment by SethTisue** [comment]
looks like the rebase itself went haywire, the PR now includes a huge number of commits?

**Comment by thestuckster** [comment]
yeah I tried to do it within IntelliJ and all hell broke loose, I thought I sorted it out but I was mistaken

**Comment by thestuckster** [comment]
alright, reset it to back before the apocalypse 0_0

**Comment by dwijnand** [comment]
How did you change them originally?

I've been trying to find a solution that applies this across the whole codebase, so we can just re-apply it on the HEAD of 2.13.x instead.

Here's what I got to (using ripgrep):

```
rg "\`([a-zA-Z\.$]+?)'"
```

next was trying to feed that into `sed` (https://github.com/BurntSushi/ripgrep/issues/74#issuecomment-376659557)

**Comment by thestuckster** [comment]
@dwijnand someone suggested a grep command on the actual ticket that I ran and manually changed the files

```grep \` $(find src -name "*.scala") | grep \" | grep \'```

**Comment by SethTisue** [comment]
@thestuckster want to come back to this...?

**Comment by SethTisue** [comment]
closing for inactivity. would a volunteer like to make a new PR and get this over the finish line?

**Comment by joroKr21** [comment]
Another attempt: #7583

**Pull request closed without merging**
