### PR TITLE
SI-9377 ScalaVersion init no longer fails if versionless

### PR DESCRIPTION
**Pull request by som-snytt**
If the version string was empty, ScalaVersion would
indignantly refuse to initialize. Now it takes a missing
property as "none".

### CODE REVIEW

**Comment by som-snytt** [comment]
Per https://github.com/scala/scala/pull/4352#issuecomment-118122608

**Comment by som-snytt** [comment]
Per https://github.com/scala/scala/pull/4352#discussion_r26995561

**Comment by som-snytt** [comment]
And https://github.com/scala/scala/pull/4352#issuecomment-118191122

**Comment by som-snytt** [comment]
Review by @adriaanm @lrytz 

This round is on me.

**Comment by lrytz** [comment]
LGTM, merci! :)

**Pull request merged**
