### PR TITLE
Update Queue.scala

### PR DESCRIPTION
**Pull request by sinanspd**
Fix typo in the docs. "from element" should be the "first element"

### CODE REVIEW

**Comment by SethTisue** [comment]
this is of course mergeable as-is, but I also notice that later on the same line, "return" should be "returns"

**Comment by sinanspd** [comment]
> this is of course mergeable as-is, but I also notice that later on the same line, "return" should be "returns"

Fixed that as well while at it. Good catch.

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
