### PR TITLE
SI-6567 Warning for Option(implicitView(foo))

### PR DESCRIPTION
**Pull request by retronym**
I've seen the reported problem before in the wild. It seems
worthy of a special warning, so long as we advocate `Option.apply`
as an alternative to `if (x == null) Some(x) else None`.

It is behind `-Xlint` at the moment, an option that could do with
some promotion.

Review by @paulp (is it time for Lint.scala?)

### CODE REVIEW

**Comment by paulp** [comment]
To be honest I think Option.apply was a mistake, so I hesitate based on the 'so long as we' clause. The mistake is that "Option(x)" and "Some(x)" read too similarly - not the way they're spelled, but the way they're encoded in the brain. And because Some(null) is not even an error, it is not as strong as it should be.

If you like -Xlint, go give my pull req from this morning a LGTM and there's almost no noise left under -Xlint on trunk.

**Comment by paulp** [comment]
Additionally, there is understandable reluctance for builtin compiler warnings to get too narrow in scope. Maybe you'd like to join me in lifting a whole bunch of warning code out of the compiler, and simultaneously making the compiler more amenable to a pluggable warning system.

**Comment by retronym** [comment]
I don't think `Option.apply` is all that bad. Sure, newcomers write `Option(new Foo)` (hey, another lint check!) until they are gently guided otherwise, but after that the difference it pretty clear. But this interaction of inference and implicits gives even an expert cause to double take. On that ground, and given that `Option.apply` is still here, this check might pay its way.

I wonder if there are other places where you might want to exclude implicitly converted arguments. If so, the code could be generalized. But I can't think of any other use cases.

``` scala
object Option {
  def apply[T :> Null](t: @noImplicitView T)
```

A standalone lint would be great, I'll definitely pitch in. But there is a big advantage to shipping something with standard distribution. Ideally we would ship a stable version of said lint plugin with the compiler, but also offer it as a separate download that could evolve more quickly.

I'm sure there are a bunch of things that need to be done to make this possible, but one that came to mind today was to expose whether a `TypeTree` was explicitly provided or inferred. This would let us pull `-Ywarn-infer-any` out of `Infer`.

**Comment by paulp** [comment]
"A standalone lint would be great, I'll definitely pitch in. But there is a big advantage to shipping something with standard distribution."

I still want to ship it with the standard distribution; I just want it to be easy to add more specific warnings which aren't sufficiently generally applicable, so generality doesn't become the enemy of utility.

"whether a TypeTree was explicitly provided or inferred."

I have a branch somewhere which records it, to good effect.

**Comment by paulp** [comment]
"I wonder if there are other places where you might want to exclude implicitly converted arguments."

My guess is there are, but they will all revolve around null.

**Comment by paulp** [comment]
As long as this isn't contributing to our total option count (which I see it isn't, thank you -Xlint) then I'll take your word for it that it happens in the wild. LGTM.

**Pull request merged**
