### PR TITLE
SI-7967 Account for type aliases in self-type checks

### PR DESCRIPTION
**Pull request by retronym**
These eluded the check for "illegal inheritance; self-type does not
conform" as AliasTypeRef doesn't forward `typeOfThis`.

This commit dealiases before calling `typeOfThis`. That seems to be
the most localised change.

Without the dealias, we had:

```
parent.tpe            = TypeRef(pre, sym = AliasTypeSymbol("CC"), Nil)
parent.tpe.typeOfThis = parent.tpe.transform(sym.typeOfThis) = CC
```

After:

```
parent.tpe.dealias            = TypeRef(pre, sym = ClassSymbol("C"), Nil)
parent.tpe.dealias.typeOfThis = C with B
```

Review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
ping @adriaanm, I fixed the typo that crept into the original PR that prevented compilation

**Comment by adriaanm** [comment]
LGTM -- Not sure if the failure in the scala-refactoring test suite is legit /cc @misto

[Failed test](https://github.com/scala-ide/scala-refactoring/blob/master/org.scala-refactoring.library/src/test/scala/scala/tools/refactoring/tests/sourcegen/PrettyPrinterTest.scala#L1192)

[Test output](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4205/artifact/target/scala-refactoring/org.scala-refactoring.library/target/surefire-reports/scala.tools.refactoring.tests.sourcegen.PrettyPrinterTest.txt)

**Comment by misto** [comment]
Hm, I have no idea why my test failed.. I guess we can ignore it.

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Thanks, @misto! Looks like it was spurious.

**Pull request merged**
