### PR TITLE
SI-7445 ListMap.tail is returning wrong result

### PR DESCRIPTION
**Pull request by rklaehn**
Reverted the commit that introduced the bug, and modified HashMap to no
longer assume that tail is O(1).

Review by @Ichoran, @soc

### CODE REVIEW

**Comment by soc** [comment]
LGTM. Thanks for looking into this, I really couldn't find the time to do it.

**Comment by adriaanm** [comment]
Thank you indeed! What should we do about the docs while we're on the topic?

**Comment by rklaehn** [comment]
You mean documenting the ordering properties of ListMap? We might as well document them since we have to guarantee them in any case. 

It's a bit annoying that the behavior of ListSet and ListMap is so different, but I guess we can't change one to match the other.

Are documentation PRs still OK while in the RC phase of a release?

**Comment by adriaanm** [comment]
Yeah, documentation is always more than ok! :-)

**Comment by dmanchester** [comment]
Hi,

I came across this pull request while researching immutable ListMaps. I had been wondering whether the behavior I had presumed and have observed--that iteration order reflects insertion order--is guaranteed (Scala 2.9.2 output follows):

scala> import scala.collection.immutable._
import scala.collection.immutable._

scala> val map = ListMap("F" -> "Frank", "G" -> "George")
map: scala.collection.immutable.ListMap[java.lang.String,java.lang.String] =
  **Map(F -> Frank, G -> George)**

scala> val map2 = map + ("H" -> "Henry", "I" -> "Ida")
map2: scala.collection.immutable.ListMap[java.lang.String,java.lang.String] =
  **Map(F -> Frank, G -> George, H -> Henry, I -> Ida)**

Based on Rüdiger's comment above, it sounds like that behavior is indeed guaranteed?

**Comment by rklaehn** [comment]
Hi,

Yes, we have to guarantee the that iteration order reflects insertion
order, because many people have come to rely on it, and also ordering
behaviour is one of the few reasons one would use a ListMap in the first
place. (Note that confusingly, in ListSet the ordering of the elements is
the reverse order in which they have been added)

I am currently busy with the day job and the kids, but when I have some
time I will do a PR to update the docs accordingly.

By the way: it's a shame ListMap is called ListMap. If we would back it by
a vector which has quick append, we could guarantee the order without the
large cost of reversing the iterator every time.

**Comment by dmanchester** [comment]
Great--thanks for confirming, Rüdiger.

Regarding the name, might there be support for adding an **InsertionOrderedMap** and **InsertionOrderedSet** (or something like that)? The map could take advantage of optimizations like the one you propose, and the set could address ListSet's unexpected ordering.

**Pull request merged**
