### PR TITLE
Avoid repr call in ArrayOps

### PR DESCRIPTION
**Pull request by cryptom-dev**
This PR is part of fixes for issue: rorygraves#23. It means to improve the performance of ArrayOps @mkeskells spotted.

This PR replaced the ofDim call, which involved Manifest resolving, for :+ and +: method in ArrayOps with constructor of scala Array.
According to jprofiler, the call percentage reduced from 14.4% (ofDim) to 3.5% (constructor of Array)

### CODE REVIEW

**Comment by ackratos** [comment]
This PR is for issue: https://github.com/rorygraves/scalac_perf/issues/23

**Comment by cryptom-dev** [comment]
jprofiler comparation (ofDim call in first image has been removed):

Baseline call tree:
arrayopsofdim_before

Improved call tree:
arrayopsofdim_after

**Comment by mkeskells** [comment]
I think that we can go further in this pr

I think that to common case is non widening so for some operations we can use Arrays.copyof via delegation.

The jvm is sensitive to the gap between array creation and fill as  to meet his spec the content is defined to be default values. I think that the scala calls will not be recognised as a safe combination so this will be an allocate then fill then copy then add sequence when in general the fill can be removed. IM me directly is this doesn't make sense

This will require additional test cases and we should include specific widening and non widening cases and some widening will move from primitive types to wrappers

All of this is subject to it performing better though :-)

**Comment by mkeskells** [comment]
Can you share the result of the JMH benchmark here

**Review by lrytz — APPROVED** [review]
Even though this can be refined, let's get the current improvement in. In 2.13 ArrayOps will really be only extension methods (https://github.com/scala/collection-strawman/pull/479)

**Pull request merged**
