### PR TITLE
SI-3809 Avoid cycles during classfile parsing

### PR DESCRIPTION
**Pull request by retronym**
Manually tested with:

```
scalaHome := Some(file("/code/scala/build/pack"))
libraryDependencies += "com.datastax.cassandra" % "dse-driver" % "1.0.0"
```

```
class Test {
  new com.datastax.driver.dse.DseCluster.Builder()
}
```

I was also able to compile `pos/cycle{-jsoup,}` without the experimental
`-Ybreak-cycles`. I've removed the entire `-Ybreak-cycles` option and
supporting code in favour of the approach in this patch.

What's changed? I've used lazy types for methods infos, which is analagous
to what we do in `Unpickler` for scala originated types.

### CODE REVIEW

**Comment by retronym** [comment]
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 123207680 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   In 32 bit mode, the process size limit was hit
# Possible solutions:
```

**Comment by retronym** [comment]
I've realized that the addition of laziness here will increase the footprint: the `ConstantPool`, which we access in the type completer, references `$outer.in.buf`, the entire contents of the class file.

I've just pushed a WIP commit to might alleviate this problem.

**Comment by Swoorup** [comment]
This is also occuring on dotty. https://github.com/lampepfl/dotty/issues/9492
Any ideas how to port the fix over? @retronym

**Pull request closed without merging**
