### PR TITLE
Check unused params of function literals

### PR DESCRIPTION
**Pull request by som-snytt**
Forward port of https://github.com/scala/scala/pull/6518

Both for explicit anon funs and those introduced
by for expr desugarings.

Improved by excellent review suggestion on linked PR.

review by @hrhino

### CODE REVIEW

**Comment by SethTisue** [comment]
needs rebase.

@hrhino are you available, or should we find a different reviewer?

**Comment by som-snytt** [comment]
I'll rebase. @hrhino is so available. I'll make it worth his while, with puns if necessary.

**Comment by som-snytt** [comment]
Squashed because fixing check files months later in the middle of some commits is too much.

**Review by hrhino — APPROVED** [review]
yes, this looks about right to my relatively rusty eyes.

Sorry for the delay in reviewing, and thanks for the (unintentional) poke.

**Pull request merged**
