### PR TITLE
restore / rewrite various tests

### PR DESCRIPTION
**Pull request by lrytz**
separate commits to simplify reviewing, will squash before merging.

when were these tests disabled?
- some when switching default backend to delambdafy:method and GenBCode (https://github.com/scala/scala/pull/4580)
  noted in https://issues.scala-lang.org/browse/SI-9364
- some when integrating SAM function types from java8-compat (https://github.com/scala/scala/pull/4597)
  also noted in https://issues.scala-lang.org/browse/SI-9364
  some noted in https://issues.scala-lang.org/browse/SI-9374
  - t8960 restored in https://github.com/scala/scala/pull/4603
  - reify tests restored in https://github.com/scala/scala/pull/4599
- some when enabling -Yopt:l:classpath (https://github.com/scala/scala/pull/4602)
  also noted in https://issues.scala-lang.org/browse/SI-9364
- some when removing GenASM (https://github.com/scala/scala/pull/4814)
  noted in https://docs.google.com/document/d/1P1oZEL3To0mMUx98Z6PKIaFHV_80kPhase0Zbn4699Q/edit
  restored in https://github.com/scala/scala/pull/4916
- some by searching for `-optimi` in .flags files
  noted in https://github.com/scala/scala-dev/issues/65
- some by searching for `GenASM`
  noted in https://issues.scala-lang.org/browse/SI-9364
  also found private-inline

### CODE REVIEW

**Comment by lrytz** [comment]
The commit "Improve simplifyJumps" (80043c7d66ba98b911b5e90baa2cb1c410b313fd) is review by @retronym.

For the others, @soc, would you lend a hand?

As mentioned above, I'll squash things into 2 commits after reviewing.

**Comment by retronym** [comment]
LGTM

**Comment by soc** [comment]
LGTM!

**Comment by retronym** [comment]
I've looked through these and it all seems to be faithfully restored. Will look GTM after the squash.

**Comment by lrytz** [comment]
squashed

**Pull request merged**
