### PR TITLE
SI-8609 Fix flattening of definitions and imports in quasiquotes 

### PR DESCRIPTION
**Pull request by densh**
Quasiquotes allow to unquote trees with ..$ with block flattening
semantics to simplify composition:

```
  val onetwo = q"1; 2"
  val onetwothree = q"..$onetwo; 3" // same as q"1; 2; 3"
```

If there is no block it will be equivalent to $ unquoting:

```
  val one = q"1"
  val onetwo = q"..$one; 2" // same as q"1; 2"
```

But the inconsistency here is that currently only terms support
this single-element semantics. This commit extends this functionality
to also support definitions and imports. So that following code works:

```
  val q1 = q"val x = 1"
  val q2 = q"..$q1; val y = 2" // same as q"val x = 1; val y = 2"
```

review @retronym @xeno-by

### CODE REVIEW

**Comment by lrytz** [comment]
soft ping for review by @xeno-by

**Comment by xeno-by** [comment]
@densh Why not just flatten everything?

**Comment by densh** [comment]
@xeno-by This is only meant for statements. Flattening of types doesn't really make any sense for example.

**Comment by xeno-by** [comment]
Can we make sure that we didn't miss any trees this time as well?

**Comment by densh** [comment]
It's not clear what you mean under "miss any trees this time". This functionality is only intended for statements and they could be either terms or definitions or imports as far as i know.

**Comment by xeno-by** [comment]
@retronym, did we miss anything?

**Comment by retronym** [comment]
LGTM

**Pull request merged**
