### PR TITLE
SI-7033 Be symful when creating factory methods.

### PR DESCRIPTION
**Pull request by retronym**
Implicit class factory methods were synthesizing the
reference to the class as `Ident(classDef.name)`, which
was unhygienic in case of `implicit class X[X]`.

To use symbols without causing a cycle, I switched from
`REF(symbol)` to `Ident(symbol)`. The former calls into:

```
at scala.reflect.internal.TreeGen.mkAttributedSelect(TreeGen.scala:184)
at scala.reflect.internal.TreeGen.mkAttributedRef(TreeGen.scala:124)
at scala.reflect.internal.TreeGen.mkAttributedRef(TreeGen.scala:130)
at scala.tools.nsc.ast.TreeDSL$CODE$.REF(TreeDSL.scala:307)
```

which seems to force the enclosing module and blow up.

Review by @paulp
- have I lost something by using `Ident(classSym)` here.
- in general, when would one choose `REF(_)` over `Ident(_)`?

### CODE REVIEW

**Comment by paulp** [comment]
"in general, when would one choose REF(_) over Ident(_)?"

I tried to decode the matter and confusion reigns. The implementation of def Ident is

```
def Ident(sym: Symbol): Ident = Ident(sym.name) setSymbol sym
```

So I don't know how that is any more hygenic than

```
def mkAttributedIdent(sym: Symbol): RefTree = Ident(sym.name) setSymbol sym setType sym.tpeHK
```

which is what is called by way of  REF/mkAttributedSelect. Are you sure it was a hygiene problem?

**Comment by retronym** [comment]
Before, it was using `Ident(name)`. I first changed it to `Ref(classSym)`, which triggered a cycle (snippet below, full details in the ticket). `Ident(sym)` didn't. 

```
    at scala.reflect.internal.Types$Type.memberType(Types.scala:779)
    at scala.reflect.internal.TreeGen.mkAttributedSelect(TreeGen.scala:184)
    at scala.reflect.internal.TreeGen.mkAttributedRef(TreeGen.scala:124)
    at scala.reflect.internal.TreeGen.mkAttributedRef(TreeGen.scala:130)
    at scala.tools.nsc.ast.TreeDSL$CODE$.REF(TreeDSL.scala:307)
```

**Comment by retronym** [comment]
The test failure is spurious.

```
[partest] testing: [...]/files/run/t6987.scala                                  [FAILED]
  [partest] did not get the string expected, full results were:
  [partest] Fast Scala compiler version 2.10.1-20130128-143318-109fab96e4 -- Copyright 2002-2013, LAMP/EPFL
  [partest] [Given arguments: -shutdown -verbose]
  [partest] [Transformed arguments: -shutdown -verbose -current-dir /localhome/jenkins/d/workspace/pr-scala-testsuite-linux-opt]
  [partest] [VM arguments: ]
  [partest] java.net.ConnectException: Connection refused
  [partest] [Connecting to compilation daemon at port 36096 failed; re-trying...]
  [partest] [No compilation server running.]
```

**Comment by retronym** [comment]
The difference is that the `REF(classSymbol)` creates a `Select`, using `sym.owner.thisType` as the prefix.

```
  /** Builds a reference to given symbol. */
  def mkAttributedRef(sym: Symbol): Tree =
    if (sym.owner.isClass) mkAttributedRef(sym.owner.thisType, sym)
    else mkAttributedIdent(sym)
```

**Comment by paulp** [comment]
I guess if classSymbol has an "interesting" prefix, you're going to lose it via Ident(sym). Try for instance nesting the class in a polymorphic enclosing class, and having some object extend the enclosing class with actual type arguments, and see how things fare when the inherited implicits are referenced from the object.

**Comment by retronym** [comment]
I can't construct a counter example. I intuit that location of the reference in the companion makes the following three ways to reference the `C` are identical.

``` scala
class Owner {
  class C
  object C {
     Ident(symOf[C])
     mkUnattributedRef(symOf[C])
     mkAttributedRef(symOf[C])
  }
```

But unable to argue the case strongly (oh for `scalacheck.Arbitrary[Symbol]`!), I've settled for the middle ground of `mkUnattributedRef`. Do we trust that `typed(mkUnattributedRef(sym)) == mkAttributedRef(sym)`?

**Comment by paulp** [comment]
mkUnattributedRef says "Requires the symbol to be static" which this one isn't. I'd just go with Ident(sym) given your failed and presumed good faith effort to break that.

**Comment by retronym** [comment]
That's the sort of thing that makes me question my good faith.

I don't really trust [that comment](https://github.com/scala/scala/commit/348c8fac9f897f9661f84e32949b8a4e0c99e93a#L14R35), which is new on master; @xeno-by is that meant for both overloads of `mkUnattributedRef`?

**Comment by xeno-by** [comment]
@retronym Yes, it was, but now I see that I broke `mkUnattributedRef` when introducing my change by removing the non-static branch altogether. Should've inserted an assert to enforce the requirement in the comments. Then we would've detected this problem earlier. Sorry.

**Comment by retronym** [comment]
@paulp We're back to `Ident(clazz)`, given the location of the reference I can see no issue with this.

**Comment by adriaanm** [comment]
> which triggered a cycle

sym.tpe can cause cycles as it forces info

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
