### PR TITLE
[SUPERSEDED] Test inferred type bounds is checked

### PR DESCRIPTION
**Pull request by som-snytt**

### CODE REVIEW

**Comment by som-snytt** [comment]
The issue suggests the ticket is external.

**Comment by SethTisue** [comment]
Eh?

**Comment by lrytz** [comment]
Discussion here: https://github.com/scala/bug/issues/12481#issuecomment-960230085

**Comment by SethTisue** [comment]
but what does "the ticket is external" mean?

**Comment by som-snytt** [comment]
I don't know what he meant, but maybe "not a bug, an actual issue with the example code".

An ongoing semantic problem is using "issue" and "ticket" interchangeably.

**Comment by joroKr21** [comment]
I think it's a bug

**Comment by som-snytt** [comment]
but whose bug?

Also, I should have left the test line where I checked that it compiles without OptManifest but with "ordinary" user implicit.

**Comment by joroKr21** [comment]
It's a Scala bug. The problematic piece of code is `classOf[Universe[_$1]]` - the manifest is just the way to generate it.

**Pull request closed without merging**
