### PR TITLE
Fixes SI-6358

### PR DESCRIPTION
**Pull request by odersky**
Local lazy accessors are an annoying irregular case. This change makes them work with value classes.

### CODE REVIEW

**Comment by odersky** [comment]
Review by @paulp @hubertp

**Comment by jsuereth** [comment]
Can we get a test case for this too?

**Comment by jsuereth** [comment]
Note to self ->  Add this test:

```
class Y[T](val i: Option[T]) extends AnyVal {
   def q: List[T] = {
      lazy val e: List[T] = i.toList
      e
   }
}
```

**Comment by odersky** [comment]
I'll look into the failures and resubmit once I fixed them.

**Pull request closed without merging**
