### PR TITLE
fix indent

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by SethTisue** [comment]
needs rebase

**Review by som-snytt — APPROVED** [review]
Finally, a PR I'm qualified to review! My university degree was in Whitespace Studies. Well, it was more of a certificate. Please also send Scaladoc comment star alignment PRs my way; I did some postdoc research. Well, it was mostly archival work.

**Comment by SethTisue** [comment]
I wander’d off by myself,
In the mystical moist night-air, and from time to time, 
Look’d up in perfect silence at the Scaladoc comment stars.

**Comment by som-snytt** [comment]
I thought it was, Beheld the perfect alignment of the Scaladoc comment stars. That was why I chose this profession, to have that experience for myself, however fleeting. Now I'll have to rethink the basis of everything in my life.

OTOH, there's still a chance to stop all those unused imports. It's the only instance in which my interests are shared by the current administration, who are also trying to stop all imports.

**Pull request merged**
