### PR TITLE
Si 6198

### PR DESCRIPTION
**Pull request by rklaehn**
Create a HashSet1 instead of a HashSetCollision1 if the list of colliding keys has only one entry.

To do this efficiently it was necessary to change ListSet so that head and tail are both O(1) with low overhead.

Based on 2.10.x this time.

### CODE REVIEW

**Comment by adriaanm** [comment]
could someone review this please?

**Comment by jsuereth** [comment]
Great changes!   I would say LGTM but I'd love to see at least one test to prevent regression.

Obviously O(1) behavior isn't possible to test currently, but we could check the runtime class for small sixed hashes after changes.

Thanks much for the hard work.  I want this in 2.10.x, just need a test to feel comfy

**Comment by rklaehn** [comment]
I added a test. Please check if this is OK.

I used getClass.getSimpleName to check which of the implementation classes
HashSet1/HashSetCollision1 is being used because both these classes should
become private[immutable] at some point in the future. Is that the correct
way to do it, or should the test use package scala.collection.immutable to
be able to access e.g. HashSetCollision1?

**Comment by jsuereth** [comment]
Great.   I may revamp the test a bit when I get the chance to do more transitions.   It's fine for now.

**Comment by rklaehn** [comment]
Is there a reason there are no asserts in HashTrieSet? I saw some
assertions on other data structures in scala.collection.immutable, so there
is no policy against assertions in general.

I think the best way to ensure the integrity of e.g. a HashTrieSet would be
an assert to make sure all the rules of HashTrieSet are satisfied:
- A HashTrieSet must have at least two elements, or one element of type
  HashTrieSet
- The number of one bits in the bitmap must be equal to the number of
  elements in the array
  (- some other more expensive assertions like making sure that size is
  correct etc.)

To do that you would have to change a few things, but that would be well
worth it because this will prevent any regressions in the future and also
document the assumptions of a HashTrieSet.

**Pull request merged**
