### PR TITLE
SI-6507 do not call .toString on REPL results when :silent is on.

### PR DESCRIPTION
**Pull request by gourlaysama**
Member handlers used to always call .toString on REPL results, even when
:silent was on, which could force evaluation or cause unwanted side
effects.

This forwards the current value of `printResults` to the member
handlers (through Request) for them to decide what to do when the
results must not be printed.

2 handlers now do not return any extraction code when silent:
- ValHandler, so that it doesn't call toString on the val
- Assign, so that it doesn't call toString on the right-hand side
  of the assignement.

---

Review by @som-snytt, please :)

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM

ignoring spurious partest integration fail

**Comment by som-snytt** [comment]
Actually, I tried this out.

It's only an issue if your toString has side effects.  That's the basis of this puzzler http://scalapuzzlers.com/index.html#pzzlr-025 which would behave differently under :silent.  Daniel Sobral's comment on the ML was that it only breaks code that's broken.

My other comment is that the fix is OK, but it would be nice to put the check higher up in Request. That is, if you're silent, you're not going to generate resultExtractionCode for anything.  The other idea is that the evaluation should happen lazily; since we're generating the code, don't generate a string, generate the call to generate the string.

Not a big deal, it can get refactored when REPL templating, or replating, happens.

**Comment by adriaanm** [comment]
Sorry for hasty merge -- I wanted to catch up with the PR backlog I co-created with our favorite butler.

**Comment by gourlaysama** [comment]
You're right, this bug only creates problems for broken code, but it still sort of violates the principle of least astonishment. That, and there are still things in the library that have side-effecting `toString`...

In retrospect that wasn't the best way to do this, but skipping handlers altogether seemed to have some side effects. That's what I wanted your feedback on. I guess this can be changed later. 

Actually maybe sooner than later, I'm also working on [colored output](https://dl.dropboxusercontent.com/u/46938538/static/repl-colors.png) in the REPL, and I need to change stuff in there to make (basic) syntax highlighting possible.

**Comment by som-snytt** [comment]
paulp will wish he were around for COLOREPL.

**Pull request merged**
