### PR TITLE
new bytecode emitter, GenBCode (7th attempt)

### PR DESCRIPTION
**Pull request by magarciaEPFL**
Compared to the previous submission this PR keeps line count reasonably small for all source files added.

This PR contains commits beyond those in the initial submission (that PR covered only the first two commits in this PR) with the aim of providing a better perspective on why the first two commits include the functionality they include. For example, dead-code elimination follows naturally bytecode generation, thus whenever GenBCode runs in the future it will perform dead-code elimination out of the box. That can be seen from commit "GenBCode tightens code before serializing classfiles"

Testing against the community build will provide more information than isolated tests.
Bytecode tests are by their very nature fragile (e.g., testing first that pattern matching emits a chain of jumps, only to make sure a moment later that chain of jumps has been collapsed by GenBCode). Concrete ideas and examples on how to balance usefulness vs brittleness are welcome.

Reviews about the content proper of the PR are most welcome.

review by @gkossakowski or @JamesIry or @retronym or @paulp

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
Those are good suggestions, I'll apply them in an upcoming version of this PR.

**Comment by retronym** [comment]
Can you also make sure that the Ant build is parameterizable so that we could replace `-optimize` with `-neo:... -gen:BCode` in the dedicated Jenkins build for these options? In the instructions you sent out recently, one still had to patch `build.xml`.

**Comment by magarciaEPFL** [comment]
Regarding how to make easier for builds to use the new backend, I'm starting to address that. I guess additional Ant tasks of the form `build-neo-opt` and `nightly-neo-opt` would make it. In the next few days I'll also set up (help is welcome!) published builds of the Scala IDE with the new backend / optimizer.

I'd prefer if the PR covering the new bytecode emitter (after applying review comments) can be merged before the build automation support (for the new backend) is there. The latter could take more days.

**Comment by gkossakowski** [comment]
Sorry for not being responsive about reviews. I was busy with conferences and travelling in general.

I'll be able to look into this PR next week (probably around Wednesday).

**Pull request closed without merging**
