### PR TITLE
Merge 2.10.1 into 2.10.x

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @gkossakowski

**Comment by gkossakowski** [comment]
BUILDLOG?

**Comment by gkossakowski** [comment]
LGTM.

@adriaanm: All looks fine when it comes to code but I don't understand the status. Even buildlog doesn't help me but I might not know how to read it.

**Comment by adriaanm** [comment]
I'm working on fixing this (reporting) bug in the build bot.

**Pull request merged**
