### PR TITLE
Platform independence for a test-case.

### PR DESCRIPTION
**Pull request by retronym**
I'm still not sure _why_ this only started breaking the windows
build after cff8b569c39fb2ce57157fa6adf4ab9289721033.

But in the interests of a working windows nightly, this commit
avoids assuming '\n' as a separator when parsing compiler output.

### CODE REVIEW

**Comment by retronym** [comment]
Windows build: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/22/console

**Comment by retronym** [comment]
```
hudson.plugins.git.GitException: Command "git fetch -t origin +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: ssh: Could not resolve hostname github-fs122-cp1-prd.iad.github.net.: Temporary failure in name resolution
fatal: The remote end hung up unexpectedly
```

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by som-snytt** [comment]
(aside): I took a look at why it started failing but just wound up taking strolls down Reporter Alley.  That was interesting but I didn't get anywhere, and finally just took a cab back to the hotel.

In the modular world, I noticed, you can observe a bump in the partest version, then realize you have no idea if that represents an interesting delta, then realize you're out of the partest loop.  (I know, it's called information hiding.)

There is not yet one spot where the build announces "partest 1.0, diffutils 1.0.3, ant 1.8.3 etc". That would assist correlation.

**Comment by retronym** [comment]
@dragos threw up an interesting theory that we might have been experiencing a different form of name corruption whereby a name itself contained a newline.

**Comment by retronym** [comment]
I'll push this after I look at it in the light of a new day, but it does appear to solve the problems:

``` diff
commit 83fea97133cb932b089e75b2a9bd4d5a4d134db8
Author: Jason Zaugg <jzaugg@gmail.com>
Date:   Wed Oct 2 10:26:23 2013 +0200

    Rework cff8b569 to heal the windows build.

     - change newTermName to fix negative length names
       rather than reject them
     - restore the old logic in unspecializedName

    Why does fix the windows build? I am still none the wiser.

diff --git a/src/reflect/scala/reflect/internal/Names.scala b/src/reflect/scala/reflect/internal/N
index f998d95..493823b 100644
--- a/src/reflect/scala/reflect/internal/Names.scala
+++ b/src/reflect/scala/reflect/internal/Names.scala
@@ -88,11 +88,12 @@ trait Names extends api.Names {
    *  (e.g. if a name has the string "$class" in it, then fail if that
    *  string is not at the very end.)
    */
-  final def newTermName(cs: Array[Char], offset: Int, len: Int, cachedString: String): TermName =
+  final def newTermName(cs: Array[Char], offset: Int, len0: Int, cachedString: String): TermName
     def body = {
-      require(offset >= 0, "offset must be non-negative, got " + offset)
-      require(len >= 0, "length must be non-negative, got " + len)
+      val len = math.max(len0, 0)
+      //require(len >= 0, "length must be non-negative, got " + len)
       val h = hashValue(cs, offset, len) & HASH_MASK
+      require(offset >= 0, "offset must be non-negative, got " + offset)
       var n = termHashtable(h)
       while ((n ne null) && (n.length != len || !equals(n.start, cs, offset, len)))
         n = n.next
diff --git a/src/reflect/scala/reflect/internal/StdNames.scala b/src/reflect/scala/reflect/interna
index 4990596..c6c0b83 100644
--- a/src/reflect/scala/reflect/internal/StdNames.scala
+++ b/src/reflect/scala/reflect/internal/StdNames.scala
@@ -420,18 +420,15 @@ trait StdNames {
      */
     def unspecializedName(name: Name): Name = (
       // DUPLICATED LOGIC WITH `splitSpecializedName`
-      if (name endsWith SPECIALIZED_SUFFIX) {
-        val idxM = name.lastIndexOf('m')
-        val to = (if (idxM > 0) idxM - 1 else name.length - SPECIALIZED_SUFFIX.length)
-        name.subName(0, to)
-      }
+      if (name endsWith SPECIALIZED_SUFFIX)
+        name.subName(0, name.lastIndexOf('m') - 1)
       else name
     )

     /** Return the original name and the types on which this name
     *  is specialized. For example,
     *  {{{
-    *     splitSpecializedName("foo$mIcD$sp") == ('foo', "D", "I")
+    *     splitSpecializedName("foo$mIcD$sp") == ('foo', "I", "D")
     *  }}}
     *  `foo$mIcD$sp` is the name of a method specialized on two type
     *  parameters, the first one belonging to the method itself, on Int,
@@ -441,16 +438,13 @@ trait StdNames {
     */
     def splitSpecializedName(name: Name): (Name, String, String) = {
       // DUPLICATED LOGIC WITH `unspecializedName`
-      if (name endsWith SPECIALIZED_SUFFIX) {
-        val name1 = name dropRight SPECIALIZED_SUFFIX.length
-        val idxC  = name1 lastIndexOf 'c'
-        val idxM  = name1 lastIndexOf 'm'
-        if (idxC > idxM && idxM > 0)
-          (name1.subName(0, idxM - 1), name1.subName(idxC + 1, name1.length).toString, name1.subN
-        else
-          (name.subName(0, name.length - SPECIALIZED_SUFFIX.length), "", "")
-      }
-      else (name, "", "")
+      val name1 = name dropRight SPECIALIZED_SUFFIX.length
+      val idxC  = name1 lastIndexOf 'c'
+      val idxM  = name1 lastIndexOf 'm'
+
+      (name1.subName(0, idxM - 1),
+      name1.subName(idxC + 1, name1.length).toString,
+      name1.subName(idxM + 1, idxC).toString)
     }

     // Nominally, name$default$N, encoded for <init>
```

**Pull request closed without merging**
