### PR TITLE
List extends scala.Serializable

### PR DESCRIPTION
**Pull request by sashasochka**
List should extend scala.Serializable, not java.io.Serializable. Because of `import java.io._` java.io.Serializable has higher priority than scala.Serializable which is not good (Personally I found this problem not being able to pass List as an argument of type scala.Serializable). 

This is clearly a bug.

### CODE REVIEW

**Comment by sashasochka** [comment]
I signed the CLA.

**Comment by adriaanm** [comment]
Hi and welcome, @sochka! I apologize for the lack of timely feedback! We've been a bit overloaded while preparing for ScalaDays etc. We're working our way through the queue.

**Comment by adriaanm** [comment]
The test failures look like noise to me. The check files can be updated by running `test/partest --update-check test/files/run/lub-visibility.scala test/files/run/t2251b.scala`. Please amend your commit and push -f to the branch you submitted this PR from.

review by @retronym

**Comment by retronym** [comment]
@sochka We should also address:

```
// List.scala
private class SerializationProxy[A](@transient private var orig: List[A]) extends Serializable {

ListBuffer
```

@lrytz My understanding is that this change is basically cosmetic; our backend treads both `scala.Seriazable` and `java.io.Serializable` the same way:

``` scala
def isSerializable      = info.baseClasses.exists(p => p == SerializableClass || p == JavaSerializableClass)
```

See:  4be5e11

Maybe there was a difference when we supported the .NET backend.

**Comment by sashasochka** [comment]
@adriaanm, I have no possibility to do that for any time soon. Could you push it yourself please?

**Comment by retronym** [comment]
I'll shepherd this one.

**Comment by lrytz** [comment]
> My understanding is that this change is basically cosmetic; our backend treads both scala.Seriazable and java.io.Serializable the same way:
> 
> def isSerializable      = info.baseClasses.exists(p => p == SerializableClass || p == JavaSerializableClass)
> See: 4be5e11
> 
> Maybe there was a difference when we supported the .NET backend.

IRC, the reason to have scala.Serializable was indeed the .NET backend. However, removing it from the `scala` package would require everybody to write / import `java.io.Serializable`, so I think we should keep it.

I also think we should keep using `scala.Serializable` in the standard library. Otherwise, if somebody writes a `def serialize(o: Serializable)` method, a List would no longer conform.

For the specific fix, I think it would be good to change `import java.io._` only import specific classes (and search for the same wildcard import in other parts of the library).

**Comment by retronym** [comment]
We need a few test cases updated to accommodate this change. Here's how.

```
./test/partest --update-check test/files/run/lub-visibility-run.scala test/files/run/t2251b.scala
git commit -a --amend
git push -f
```

**Comment by gkossakowski** [comment]
@sochka, could you rebase your patch on top of latest 2.12.x branch? Please update test cases as suggested by @retronym.

**Comment by soc** [comment]
Over the long run I think it would make sense to replace Scala's `Serializable` trait with a type alias for the corresponding platform's marker trait.

Not a big issue, but I occasionally see confusion and problems because people assume Scala's `Serializable` =:= Java's `Serializable`, but of course only `scala.Serializable` <: `java.io.Serializable` is true, but not the other way around.

Should I have a look?

**Comment by sashasochka** [comment]
Good point, I agree

**Comment by retronym** [comment]
Superseded by #3965

**Pull request closed without merging**
