### PR TITLE
Optimization of RichXX in runtime

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
scala/bug#11685. remove `ScalaNumberProxy.scala`.

I haven't modified the test yet. Even if I refer to [sjrd's draft pr](https://github.com/scala/scala/compare/2.13.x...sjrd:efficient-rich-primitives), I'm still not sure whether it is implemented correctly. Especially I know little about binary compatibility.

### CODE REVIEW

**Comment by jxnu-liguobin** [comment]
@SethTisue I look forward to your suggestion very much. 😄

**Comment by dwijnand** [comment]
The breaks MiMa though...  We can only merge a solution that doesn't do that.

**Comment by SethTisue** [comment]
(I'm at ScalaCon this week and on vacation next week, so it would be very much welcome for other reviewers to step in here.)

**Comment by sjrd** [comment]
MiMa is configured in backward *and forward* mode for patch releases. When the next version will be 3.1.0, it will be configured in backward only.

**Comment by jxnu-liguobin** [comment]
mima report 🥱 
Failed binary compatibility check against org.scala-lang:scala-library:2.13.5! Found 374 potential problems (filtered 10)

**Comment by SethTisue** [comment]
@sjrd so is there no possibility to address scala/bug#11685 in either Scala 2 or 3.0.x?

**Comment by sjrd** [comment]
Not with a library-based solution, no. If you're very determined, you could of course rewrite all those patterns at compile-time.

**Comment by SethTisue** [comment]
@jxnu-liguobin thanks for pushing on this, at least we achieved clarity :-)

**Pull request closed without merging**
