### PR TITLE
Avoid throwing exceptions in macro context.

### PR DESCRIPTION
**Pull request by hubertp**
This eliminates probably the last place where type errors are thrown
in an obvious way - reporting errors is off for whitebox macros, which
makes it pretty annoying if you are trying to understand the decision
process of implicit search (any c.abort will throw a type error rather
than simply buffering an error like in every other normal case).

As a bonus we get more messages that are reported during (failed) macro
expansion (see updated test case).

### CODE REVIEW

**Comment by hubertp** [comment]
Review by @xeno-by

**Comment by xeno-by** [comment]
I wonder why I wrote that comment... But anyway this patch looks like an improvement! LGTM.

**Comment by retronym** [comment]
> I wonder why I wrote that comment

@xeno-by You also made it a few lines below. Could you please take another look at the diff and see if you can recall any context?

https://github.com/scala/scala/commit/ac430ac8ba554d1b976d44598400d95ce5cf3816#diff-05c273d837c49f8b6278b19592a541beR651

@hubertp Could you spell out why this change improves the error reporting in that test? I just would like to understand that step by step, in order to help think of any ways that it could cause a problem. All too often a bug fix unmasks a latent bug that was depending on the first one...

**Comment by hubertp** [comment]
@retronym I believe that throwing an exception simply meant that all the previous errors in the buffer were discarded. I will run some tests and confirm (sorry, was busy last week).

**Comment by hubertp** [comment]
Closing for now, I don't have time to dig in the details for @retronym, but will reopen once I have a free moment.

**Pull request closed without merging**
