### PR TITLE
SI-9026: Update Outdated Copyrights

### PR DESCRIPTION
**Pull request by kanielc**
In many of the headers and other files, the copyright notices only run
to 2013. Also added link to scala-lang.org in headers where it was
missing.

Sorry for the tedium of this PR...

### CODE REVIEW

**Comment by kanielc** [comment]
There is also SI-5817 from May 2012 which can be closed pretty easily by adding the header to language.scala and languageFeature.scala.

Will do that after this one if approved.

**Comment by retronym** [comment]
See also my unfinished attempt, #4055.

Quite a few files are missing copyright notices, we should fix that to.

For a change of this size (which we can't easily review), it is important to explain the methodology. Best would be to contribute a reusable script into ./tools so we can run it again in a few short weeks :)

**Comment by mpociecha** [comment]
Just FYI: https://github.com/scala/scala/pull/4055 and https://github.com/scala/scala/pull/4056

Edit: Ups, too late.

**Comment by Ichoran** [comment]
Are we allowed to update the copyright on files that haven't otherwise changed?  I would think the thing to do would be to ask Git to tell us the date of the last revision on each file and, as part of the release process (when things are frozen anyway) automatically extend the copyright notice on any file that's been touched.  Assuming we can't just say: Copyright WhateverGitSays

**Comment by retronym** [comment]
I don't know the answer to that. Thoughts, @adriaanm?

I do agree we need a script for this. In #4056 I included a script to add missing headers to mine the initial year from git, but I just used the current year as the end.

**Comment by retronym** [comment]
BTW, Thanks for raising this issue, @kanielc!

**Comment by kanielc** [comment]
I didn't use a script, but I should be able to whip one up.  What I'd rather aim for is a common header format too, as I noticed some formatting differences as I was going through the changes.

What I did was a search and replace for "-2013" to "-2014", then manually reviewed and corrected the changes :$

Do I close this then?

**Comment by adriaanm** [comment]
> Are we allowed to update the copyright on files that haven't otherwise changed?

IANAL, but I think we can say pretty much anything we want here :-) I would vote for consistency & uniformity through automation.

**Comment by adriaanm** [comment]
I did some googling, and https://wikis.oracle.com/display/GlassFish/Copyrights confirms @Ichoran's statement. So, perhaps we should invest in PR validation for lazy updating of the copyright date range?

**Comment by kanielc** [comment]
It seems the pattern of the changes here are pretty simple
Let YearNow = current year

Replace `(c) Year1-Year2` with `(c) Year1-YearNow`
and 
Replace `Copyright Year1-Year2` with `Copyright Year1-YearNow`

The alignment should all be the same.
Thoughts?

**Comment by retronym** [comment]
Some files only have a single year. I tried

```
% git grep -l --null Copyright | xargs -0 -n 1 perl -p -i -e 's/(Copyright\s+(20\d\d-|))(20(\d\d))(\b.*(LAMP|Typesafe).*)/${1}2014$5/g'
```

**Comment by kanielc** [comment]
Closing in favour of #4184

**Comment by som-snytt** [comment]
Amen to lazy updating of dates.  Maybe automate the update and let the robot perform whitespace changes at the same time.

**Pull request closed without merging**
