### PR TITLE
Fix scala/bug#11380

### PR DESCRIPTION
**Pull request by Jasper-M**
Fix scala/bug#11380

### CODE REVIEW

**Comment by Jasper-M** [comment]
@joshlemer review?

**Review by joshlemer — APPROVED** [review]
Looks good to me, though wouldn't these tests be more appropriately junit tests?

**Comment by Jasper-M** [comment]
> wouldn't these tests be more appropriately junit tests?

Ideally they would, but as long as all BitSet unit tests are in partest instead of in junit I guess it's better to at least keep them together.

**Pull request merged**
