### PR TITLE
Update scala version to 2.11.5 for Intellij 14

### PR DESCRIPTION
**Pull request by romanowski**
Update scala version to 2.11.5 for Intellij 14

### CODE REVIEW

**Comment by lrytz** [comment]
Hi @romanowski, Thanks for your contribution! Even though this is a small commit, could you sing the Scala CLA? http://www.typesafe.com/contribute/cla/scala

For the change, it would be great if we could change the [setup.sh](https://github.com/scala/scala/blob/2.11.x/src/intellij-14/setup.sh) script to read the `starr.version` from [versions.properties](https://github.com/scala/scala/blob/2.11.x/versions.properties) and generate the right `scala.ipr` - do you have time to look into this?

**Comment by romanowski** [comment]
CLA signed, generating valid scala versions - done. I tested it only on my machine (Ubuntu 14.04).

**Comment by lrytz** [comment]
thank you!

**Comment by mpociecha** [comment]
I tested it on Windows using Git Bash and seems to be okay.

**Comment by som-snytt** [comment]
> could you sing the Scala CLA?

What key would you like it in?

CLA = Code Lover's Anthem.

**Comment by mpociecha** [comment]
Good one. :D

**Comment by romanowski** [comment]
Scala CLA singed... At least first few first lines...

**Comment by adriaanm** [comment]
:notes:  :-D  :notes: 

Thanks!

**Pull request merged**
