### PR TITLE
[SUPERSEDED/RESUB] Override check uses useful position

### PR DESCRIPTION
**Pull request by som-snytt**

### CODE REVIEW

**Comment by som-snytt** [comment]
on Heroes, I love when Claire revives Peter.

**Review by lrytz — APPROVED** [review]
LGTM, thank you!

**Comment by SethTisue** [comment]
> Fixes https://github.com/scala/bug/issues/12851

Does it? It looks to me like you're avoiding the crash, but the spurious warning is still emitted.

(Which is an appropriate ambition level for 2.13.12, but I want to double check our understanding.)

**Comment by lrytz** [comment]
Oh I didn't read carefully, I missed that there's a spurious warning. I'll take a quick look.

**Comment by som-snytt** [comment]
It's not spurious!

```
trait T1 {
  def f: Int
}
trait T2 {
  def f() = 42
}
class C extends T1 with T2
```

The warning is at `C`.

**Comment by SethTisue** [comment]
To spell it out for anyone else confused: at the time I reviewed this PR, it just contained a single test case, different from the one in 12851, and I didn't spot the difference.

Som has now amended the PR to include both the new test case (in which T2 doesn't extend T1), _and_ the one from 12851 (in which T2 does extend T1).

**Comment by SethTisue** [comment]
Okay, I see that you've now amended the PR to include two different test cases, t12851 (in which T2 extends T1, as in the case in the ticket) and t12851b (in which T2 does not extend T1, but C mixes in both traits).

t12851b makes sense to me.

t12851 still puzzles me. Shouldn't the argument be issued when T2 is compiled, rather than when C is compiled?

**Comment by som-snytt** [comment]
I have to switch to `partest --realeasy` because I keep forgetting to commit test files.

Refchecks notes don't trigger inherited deprecations, so maybe the same for this case.

Or maybe the concrete class inherits the sins of the parents.

Take Me On unplugged has me rethinking everything. https://www.youtube.com/watch?v=-xKM3mGt2pE

Also Sinéad https://www.youtube.com/watch?v=4kPgo3lPxSQ and Dolores https://www.youtube.com/watch?v=KxbtgLXn4bY remind me that the expression matters.

Let's not forget that life is short, like release cycles, so our window of expression is finite.

**Comment by som-snytt** [comment]
When Dolores O'Riordan sings Did you have to let it linger? she was asking about unreviewed PRs.

**Comment by som-snytt** [comment]
Added a commit that removes the check file for the test that was moved to pos.

If I had accidentally moved the check to pos, it would have told me!
```
if (checkFile.exists) genFail("unexpected check file for pos test (use -Werror with neg test to verify warnings)")
```

~Still needs the improvement for valdefs. That came up on an odd ticket so I keep forgetting about it.~

**Comment by som-snytt** [comment]
`neg/t0513` fails with a third error on
```
    [170:203]private[this] val test2: [174]Test.Test[Test.Y[Nothing,Int]] = [182:203][182:203][182:203]new [182:203]Test.Test[Test.Y[Nothing,Int]]();
    [174:179]<stable> <accessor> def test2: [174]Test.Test[Test.Y[Nothing,Int]] = [174][174]Test.this.test2
```
The 3rd error appears now because the first error has a different position `[174]` vs `[174:179]`. That should be the symbol pos, not the tree pos.

I see from further reading that I don't know all the constraints on fields and accessors.

```
      // only one symbol can have `tree.pos`, the others must focus their position
      // normally the field gets the range position, but if there is none, give it to the getter
```

The original type tree is the RHS, the LHS is inferred or propagated. It would be nice if we knew that and refchecked only the original. That is probably out of scope.

**Comment by som-snytt** [comment]
Only squashed commits someone may not have yet rebased upon.

**Comment by SethTisue** [comment]
@som-snytt Thanks for doing such a thorough job addressing the underlying issue!

@lrytz Given that we're already in the RC phase (and we don't want to slip the release date by resetting the testing clock unless truly necessary), do you think this is sufficiently safe to merge for 2.13.12, or would it be better to merge https://github.com/scala/scala/pull/10509 for 2.13.12 and hold this one for 2.13.13...?

**Comment by som-snytt** [comment]
I approved the other PR, as it is of notably smaller scope. It also now comes with a test! which I'm afraid has bloated the PR, sorry!

**Comment by lrytz** [comment]
Re-submitted in https://github.com/scala/scala/pull/10520

Except for the namePos change, which is in https://github.com/lrytz/scala/compare/pr10512...lrytz:scala:pr10512a?expand=1

**Comment by som-snytt** [comment]
@lrytz will you handle further uptake of the namePos or whatever? That is, you don't need me to rework something?

**Comment by lrytz** [comment]
Yeah, I'll re-submit the namePos change (for 2.13.13) as a new PR once https://github.com/scala/scala/pull/10520 is merged.

**Pull request closed without merging**
