### PR TITLE
[backport] sbt 1.9.0 (was 1.8.3)

### PR DESCRIPTION
**Pull request by SethTisue**
not for merge until 1.9.0 final, but let's see how CI likes it. fyi @eed3si9n

### CODE REVIEW

**Comment by SethTisue** [comment]
CI likes it

the `IntegrationTest` deprecation prints a bunch of warnings, but that's expected. before merge, we might want to see if we really need to be using `IntegrationTest` or whether that's just a relic

**Comment by SethTisue** [comment]
let's not merge before 2.12.18 is announced, as per https://github.com/sbt/sbt/issues/7276

**Comment by SethTisue** [comment]
Well, @lrytz went ahead with the 2.13 version at https://github.com/scala/scala/pull/10426. The decision he made there was to ignore the `IntegrationTest` deprecation. That seems like a reasonable choice in a mature project like this one, so I'll do the same here.

**Comment by som-snytt** [comment]
That does sound like the mature choice. That is why Lukas is the adult.

**Comment by SethTisue** [comment]
🎵 ...forever young... 🎵 

Let's merge once CI likes it.

**Comment by lrytz** [comment]
> The decision he made there was to ignore the `IntegrationTest` deprecation

... for now - we can address it if / when it becomes more pressing.

**Pull request merged**
