### PR TITLE
Performance optimization - SeqLike

### PR DESCRIPTION
**Pull request by Ichoran**
Big improvements to updated and patch by not creating intermediate collections.

Moderate improvement to sorted by not using extra ArraySeq wrapper.

Small improvements to diff, intersect, and padTo by watching for duplicate or slow operations a bit more carefully.

```
Performance summary (all timings JDK 1.8.0_25 Linux):

method        reason
===========   ===============================================================
diff          1.1x speedup on big seqs - avoid double map lookup
intersect     1.1-1.2x speedup - avoid double map lookup
padTo         avoid multiple calls to length (good if length is slow)
patch         2.4-4.0x speedup - avoid intermediate collections
sorted        1.2-1.5x speedup - use array directly
updated       3.5-9.6x speedup - avoid intermediates (but children override)
```

### CODE REVIEW

**Comment by retronym** [comment]
The bootstrap failure is due to a bug in the new implementation of `patch`.

```
% cat sandbox/test1.scala
object Test {
  def main(args: Array[String]): Unit = {
    val thiz = List(1, 2, 3)
    val from = 1
    val patch = List(10, 11)
    val replaced = 1
    val result = thiz.patch(from, patch, replaced)
    println(result.toList)
  }
}

% scalac-hash v2.11.5 sandbox/test1.scala && scala-hash v2.11.5 Test
List(1, 10, 11, 3)

% qscalac sandbox/test1.scala && qscala Test # this PR
List(1, 10, 11)
```

**Comment by Ichoran** [comment]
Oops.  I should run the collections tests on all these patches.  Will fix shortly.

**Comment by adriaanm** [comment]
Since the 2.11.6 deadline is extremely nigh, I've tentatively postponed this PR (along with other recent ones) to 2.11.7. I'll make a pass through reviewed 2.11.7 PRs on Friday and move them back to 2.11.6 where feasible.

In the mean time, feel free to let me know if you'd like some help getting this reviewed by then.

**Comment by Ichoran** [comment]
@adriaanm - I've included performance boosts in the comment so we can somewhat better decide whether the improvements are worth trying to get a review through.  FWIW, immutable collections tend to override the biggest ones (patch, override) because they are also after structural sharing.  Things like `WrappedArray` see the performance benefits.  (I benchmarked with custom classes.)

**Comment by soc** [comment]
This LGTM.

**Comment by gkossakowski** [comment]
Thanks.

**Pull request merged**
