### PR TITLE
Rename module to object

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Everything mentioned in https://github.com/scala/scala/pull/1065 and https://groups.google.com/forum/#!topic/scala-internals/vEFtAdiybyk/discussion still applies.

I updated the patch so that it isn't forgotten after 2.10.0 ships and added some additional `module` methods for smoother transition.

**Comment by paulp** [comment]
isObject and isObjectClass are unacceptable names, period.

**Comment by paulp** [comment]
Closing this since it no longer merges and because I reiterate that "isObject" is a name which would have to traverse my dead body. I'm not opposed to the pursuit of consistency, far from it; but other qualities such as sensibility are also a high priority.

**Comment by soc** [comment]
Is it an issue because of objects in the sense of "instances of classes" or due to `java.lang.Object`?
I'll try to come up with some ideas, but I think the design space is pretty much exhausted by earlier decisions.

**Comment by paulp** [comment]
It is an issue for both those reasons; because we maintain a distinction between "Object" and "Any"; because the paradigm in which we work is called "object-oriented programming", and has been for decades; because that something "is an object" is sure to mean many things to many people, and rarely would it mean what is intended here. You can call it a "fizzbuzz" or a "glarkle" for all I care (not that those are likely to fly) as long as you don't pick the most overloaded word in programming. That the language itself picked it is regrettable but it is not a reason to infect the source code with the same confusion.

**Pull request closed without merging**
