### PR TITLE
Fixes SI-6271 - Missing isEmpty override for views.

### PR DESCRIPTION
**Pull request by jsuereth**
GenIterableView didn't override isEmpty for filter to look at _filtered_ iterator, but was instead pulling
unfiltered iterator and causing issues.   Chalk up another bizzare bug to lack of insight/visibility into
linearization and what havoc overriding new methods can spew on our library.

Review by @alex22, @paulp or anyone who loves inheritance (not the $$ kind).

### CODE REVIEW

**Comment by jsuereth** [comment]
Realizing everyone's on vacation, adding @lrytz as a possible reviewer :)

**Comment by lrytz** [comment]
sorry, i don't know enough about the implementation of views and i cannot say if that's the correct fix.. on a very superficial level it looks like there should be a more principled solution.

how about other views like `TakenWhile`, don't they have the same problem?

**Comment by jsuereth** [comment]
It's very possible.   I could override abstract transformed as well.

With views, the issue right now is your visibility into where methods are drawn from is non existent, and the dangers of overriding are huge.

This fixes the direct bug in the minimalistic "touch little,break little" motif.

I can investigate moving to abstract transformed for iterable views,  the issue is when someone fixed/sped up isEmpty, the overridden methods bleed into views unless we cut them off at the right location.   I'll circle back with another fix, and try to exercise potential bad behavior.

Note:  we have 0 insight into performance, but perhaps that's of little concern given the broken behavior right now.

**Comment by jsuereth** [comment]
@lrytz OK, I migrated the "iterator" method up.  Note: This _may_ 'slow down' views where creating iterators is expensive, but I think correctness is preferred at this point.

**Comment by lrytz** [comment]
thanks, to me it looks good, but a comment by @axel22 would be great.
let's squash the two commits though

**Comment by jsuereth** [comment]
Will do.  Isn't @axel22 out right now?

**Comment by lrytz** [comment]
he was back from vacation last week, but he might be away again, haven't seen him around these days..

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Alright, since Alex/Phillip are out, I'm merging. Thanks for the review Lukas!

**Pull request merged**
