### PR TITLE
API docs: reflection fixes, AnyVal/Any documentation additions, errata

### PR DESCRIPTION
**Pull request by heathermiller**
This PR resolves a couple of documentation blockers:
- SI-6132 Reflection docs, corrections, typo fixes
- SI-6399 AnyVal and Any docs to reflect the existence of value classes and universal traits
- SI-6606 Removes a placeholder icon for abstract types Scaladoc (class icon) with one that makes sense for abstract types

Other fixes:
- A typo-fix to scala.concurrent.Future docs
- The addition of "Experimental" labels across scala.reflect.api and scala.reflect.macros

### CODE REVIEW

**Comment by heathermiller** [comment]
Review by @xeno-by

**Comment by heathermiller** [comment]
The reflect.api generated docs are viewable here:
http://lampwww.epfl.ch/~hmiller/reflection-errata/#scala.reflect.api.package

**Comment by xeno-by** [comment]
Hmm a lot of EXPERIMENTAL EXPERIMENTAL EXPERIMENTAL labels here: http://lampwww.epfl.ch/~hmiller/reflection-errata/#scala.reflect.api.package. Scary!

**Comment by heathermiller** [comment]
Upon your request though

**Comment by xeno-by** [comment]
Thanks for putting all these things together!

**Comment by densh** [comment]
Experimental marks looks good. That wasn't emphasized enough before.

**Comment by xeno-by** [comment]
lgtm

**Comment by jsuereth** [comment]
LGTM too.

**Pull request merged**
