### PR TITLE
SI-9475 Dependent PolyTypes are dependent types

### PR DESCRIPTION
**Pull request by VladUreche**
Such that uncurry can correctly un-dependify them.

### CODE REVIEW

**Comment by VladUreche** [comment]
Review by @retronym and @adriaanm.

**Comment by adriaanm** [comment]
LGTM

**Comment by VladUreche** [comment]
Thanks Adriaan!

**Comment by retronym** [comment]
LGTM, too.

**Comment by VladUreche** [comment]
Thanks for the reviews and merge guys! With this PR and #4706 the miniboxing plugin won't have any more trouble re-typechecking the AST after uncurry.

**Pull request merged**
