### PR TITLE
Cleanup tools.cmd, by moving most to partest

### PR DESCRIPTION
**Pull request by SethTisue**
resubmission of @dwijnand's #6639, with an additional commit I picked
out of @som-snytt's pocket

### CODE REVIEW

**Comment by SethTisue** [comment]
I found this under a pile of laundry in the corner of my bedroom.

**Comment by SethTisue** [comment]
well this is weird. CI is failing because

```
[error] /Users/tisue/scala.213/src/partest/scala/tools/partest/nest/RunnerSpec.scala:51:78: postfix operator --? needs to be enabled
[error] by making the implicit value scala.language.postfixOps visible.
[error] ----
[error] This can be achieved by adding the import clause 'import scala.language.postfixOps'
[error] or by setting the compiler option -language:postfixOps.
```

but the file in question _already has_ `import language.postfixOps` at the top, so what gives?

**Comment by SethTisue** [comment]
maybe this underhanded trick that src/partest/scala/tools/partest/nest/package.scala pulls:

```
  // make some language features in this package compile without warning
	  implicit def implicitConversions = scala.language.implicitConversions
	  implicit def postfixOps = scala.language.postfixOps
```

is involved somehow

and also, I bet the problem didn't turn up locally when I was rebasing because of some obscure interaction between package objects and incremental compilation

**Comment by SethTisue** [comment]
ah, and I see that c83cacb6d8ca32dae7b2a81f83855bd1ba271f56 removes the dirty trick

**Comment by SethTisue** [comment]
GitHub's propensity to display commits in the wrong order isn't helping 😠

**Comment by SethTisue** [comment]
perhaps the CLA checker is confused because author != committer?

anyway, this is ready for review

**Comment by dwijnand** [comment]
> GitHub's propensity to display commits in the wrong order isn't helping 😠

`git rebase --ignore-date d82fd5b10b` (where d82fd5b10b is the last commit showing in the right order, selected manually)

**Comment by dwijnand** [comment]
Hehe.  Nope, that still shows Som's change before mine (when it's actually after), because with `--ignore-date` they occurred on the same second.

**Comment by dwijnand** [comment]
Check out this beauty:

```
git rebase d82fd5b10b --force-rebase --exec "sleep 1" --exec "git commit --amend --no-edit --date=now"
```

**Review by dwijnand — APPROVED** [review]
Thank you, Seth.  You are a Scala contributor.  Welcome.

**Comment by SethTisue** [comment]
this already got reviewed the first time around, so the sanity check from Dale seems sufficient for merge

**Pull request merged**
