### PR TITLE
SI-6309 Test case for early-init / private[this] crasher.

### PR DESCRIPTION
**Pull request by retronym**
This has worked since 98daf03, "Overhauled local/getter/setter name logic.".

I didn't narrow the progression down to a particular part of the patch.

Jubilant review from the overhauler himself, @paulp.

### CODE REVIEW

**Comment by som-snytt** [comment]
> I don't know if this affected anything

I think we need another word for the butterfly effect in software.

The use case was, in fact, subverting shadowing of local names.

**Comment by som-snytt** [comment]
This goes to a question I had recently while thinking about tests: Do `pos` tests really tell you anything?  Is the failure to crash reassuring?  Or must a test always assert something non-trivial about its output (the byte code, or the result of running the byte code)?

**Comment by JamesIry** [comment]
Let's take the discusion on the value of pos tests to scala-internals and leave PR discussions focused on the PR being reviewed.

**Comment by som-snytt** [comment]
Specifically, my example code outputs "7", so the check file is needed.  But maybe this test should just be pos.  See above question.

I think it was 7 and not 5.

**Comment by retronym** [comment]
It's a fair question; nay a good question. In the past I've converted `pos` tests to `run` tests after finding hidden `VerifyErrors`. Naturally I had then hoped to run all `pos` tests through bytecode verification. But that turned out to be tough to do meaningfully without _really_ running the code (at least, static initializers in the code.)

In this case I erred on the side of `run`. I'll push a checkfile post haste.

**Comment by retronym** [comment]
"This time with a CheckFile" :tm:

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
