### PR TITLE
Fixes SI-4042, challenges with NumericRange's contains.

### PR DESCRIPTION
**Pull request by paulp**
Cleans up some sketchy and inadequate casting in favor of
using a dummy implicit to overload contains.  This way if
you're doing something reasonably sensible like

  1L to 10L contains 3

It will be both fast and correct.  And if you're doing
something sensible but less convenient for the implementor like

  1L to 10L contains BigInt(3)

..then it will still be correct.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @jsuereth .  For the record I'd vote for this to go into 2.10, but the pull is against master.

**Comment by jsuereth** [comment]
What about:

```
val x: Seq[Int] = 1L to 10L
x contains 1L
```

I'd hate to also lose performance here, but maybe there's no pleasing the covariance overlord.

**Comment by paulp** [comment]
@jsuereth that code wouldn't compile, so I'm not sure what you're asking.

**Comment by jsuereth** [comment]
Sorry should have been

```
val x: Seq[Long] = 1L to 10L
x contains 1L
```

**Comment by paulp** [comment]
Can't cover that in NumericRange without bringing back all the original problems.  But what would be good/sensible is a custom LongRange class, which would solve all the problems for the most useful non-Int range by far.

**Comment by jsuereth** [comment]
I remain unconvinced that this is all win.  The ambiguity of contains from your parent class seems a nightmare waiting to surprise users.   I think we have time in the 2.11 series to think through an alternative, better behaved solution.   If pushed, I'll even propose my own implementation, although my stack of "todos" is still cutting off the breathable air in the Pitts.

**Comment by paulp** [comment]
Okay, I'll leave this class for the next sucker.

**Pull request closed without merging**
