### PR TITLE
SI-8370 fixes an infinite loop in repl init

### PR DESCRIPTION
**Pull request by xeno-by**
Under a weird coincidence of circumstances provided by `sbt console-quick`,
new XML parsing logic in compiler plugin initialization could lead to stack
overflow errors.

Here's the abridged sequence events that led to this unfortunate problem
(full description can be found on the JIRA issue page):

1) Initialization of the compiler underlying the REPL would kick off
plugin initialization.

2) PluginDescription.fromXML would call into DocumentBuilderFactory, i.e.
DocumentBuilderFactory.newInstance.newDocumentBuilder.parse(xml).

3) That thing would call into javax.xml.parsers.SecuritySupport.getResourceAsStream,
requesting META-INF/services/javax.xml.parsers.DocumentBuilderFactory.

4) That request would get serviced by TranslatingClassLoader provided
by the REPL to expose dynamically compiled code.

5) TranslatingClassLoader would call translatePath that would call into
IMain.symbolOfIdent trying to map the requested resource onto one of the
classes defined by the REPL (which don't exist yet, because REPL hasn't
yet finished initializing).

6) IMain.symbolOfIdent would request IMain.global, which is exactly the
instance of the compiler that underlies the REPL, and that's currently
being initialized.

7..inf) Repeat until a StackOverflowError.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Why is TranslatingClassLoader involved in REPL initialization? I thought it should be used only once REPL is initialized already, no?

**Comment by xeno-by** [comment]
I have no answer to that question.

**Comment by retronym** [comment]
It might come up via:

``` scala
  // Set the current Java "context" class loader to this interpreter's class loader
  def setContextClassLoader() = classLoader.setAsContext()
```

**Comment by som-snytt** [comment]
That's a good one.  I added the comment in AbstractFileClassLoader.getResourceAsStream that its delegation order is inverted.  (I was fixing the findResource bug, which I just hit again because the fix is in 2.10.4, so 2.10.3 :javap still is broken, d'oh.)  So if delegation were correct, you'd see this SOE only if the plugin file were missing, since the parent CL would find it otherwise.

I also remember suggesting an alternative to @adriaanm 's xml parsing, to use a regex pattern match to pull out the plugin name -- the joke was that the string is the same for both composing and decomposing, but google doesn't yield it up -- the downside was less flexibility.

**Comment by adriaanm** [comment]
Yeah, I also enjoyed how all these things came together for some constructive proof of "what could possibly go wrong".

**Comment by adriaanm** [comment]
LGTM

**Comment by som-snytt** [comment]
Answering the question on the ticket, I wrote a ReplTest that does the `setContextClassLoader` prematurely, but got a weird NPE instead of the desired SOE. That resulted in an unexpected WTF.  I'll contribute it when I've fixed it properly.

SBT is doing this for initialCommands, so a better approach might be something like the following:

```
      override def chooseReader(settings: Settings) =
        if (initialCommands.nonEmpty) InitialReader() else InteractiveReader()

      private def InitialReader(): InteractiveReader = {
        import java.io._
        val in = new BufferedReader(new StringReader(initialCommands))
        new SimpleReader(in, SimpleReader.defaultOut, interactive = false) {
          override def readOneLine(prompt: String) = {
            val s = super.readOneLine(prompt)
            if (s != null) s else {
              val replacement = InteractiveReader()
              in = replacement
              replacement.readOneLine(prompt)
            }
          }
        }
      }
```

I don't normally build sbt, so maybe there are issues with supporting 2.8, etc, as I see from the code comments.

**Comment by adriaanm** [comment]
Thanks, @som-snytt.

**Pull request merged**
