### PR TITLE
Replacing isDefined flag in SyncVar by using the Option API

### PR DESCRIPTION
**Pull request by shaulzorea**
Usage of isDefined flag is redundant since:
1. isDefined and value are private to the class 
2. All accesses to isDefined occur within synchronised blocks.
3. isDefined is true iff value is assigned.

### CODE REVIEW

**Comment by som-snytt** [comment]
Why isn't it more natural to eliminate the `Option` boxing? The only API returning an `Option` is `get(timeout)`. It was made an Option to avoid setting the field to null, apparently. 74062e352955afa6869636d84035011e3518d7d4

**Comment by shaulzorea** [comment]
@som-snytt I think using `Option` results in a cleaner implementation.
It spares the need to toggle the `isDefined` flag each time a value is set or unset by setting both the encapsulated value and the state in one go.

**Comment by som-snytt** [comment]
I bet @Ichoran will have a gut feeling as to whether a collection of one should add a box. Maybe it's obvious that a `SynchronizedOption` is a terrible choice where performance matters.

Too bad it's not like amazon where you can ask for the gift wrapping at checkout.

**Comment by SethTisue** [comment]
To expand a bit on Som's comments about Option: originally `Option` was not used; @phaller introduced the use of Option in 74062e352955afa6869636d84035011e3518d7d4; the comment says "fix memory leak", and the diffs added `value = None` which definitely plugged a leak, but it seems to me that it could equally well have been plugged with `value = null.asInstanceOf[A]`.

**Comment by SethTisue** [comment]
As for the main question here, about whether `isDefined` is needed, it seems to me that @shaulzorea is right and it is not, and should have been removed at the time Option was added.

It'd be nice to have a confirmation from somebody who's already been around the block at least once with this code (@phaller, @axel22, @heathermiller, @paulp), not sure if any of them want to hear about it in 2015 though.

**Comment by Ichoran** [comment]
@som-snytt - Indeed.  I don't like boxes in code that might be heavily used.  Without testing I wouldn't assume this variant is as fast.  I'm not sure how heavily this code is used, though. You gain way more from ejecting the superfluous Option than the Boolean (unless the use site consists of a bunch of calls to `get`, and in that case, the current approach is likely best).

**Comment by som-snytt** [comment]
I'll put a different spin on my previous observation. This class has such a sordid history, for what it does, that the best course is to leave the Option in so as to render it useless so that no one actually uses it.

**Comment by SethTisue** [comment]
"what it does" isn't even clear — there seems to be some difference of opinion about whether it's a "mutable cell" or some kind of queue-like thing of length 1. the latter camp deprecated `set()` (but without deprecating `isSet()`?), but apparently Mark Harrah was in the former camp, so he copied and pasted it into sbt's copy of the Process library (https://github.com/sbt/sbt/commit/fa591364f710df12883e031a6533371f9c19b8e5), while the copy of Process in the standard library continues calling the deprecated one. oy.

**Comment by axel22** [comment]
I was looking at this some a few weeks back when this question popped out:

http://stackoverflow.com/questions/31061779/scala-syncvar-usage-of-isdefined-flag/31062083#31062083

The `isDefined` is, after that commit, indeed no longer necessary.
However, I agree with Seth's and Ichoran's comment that `null.asInstanceOf[A]` is an equally good plug that avoids unnecessary boxing and garbage allocation. I would recommend refactoring to that.

Also, would be good if this PR added a ScalaCheck test.

**Comment by SethTisue** [comment]
@shaulzorea looks like everyone has had their say on this. would you like to revise it?

**Comment by shaulzorea** [comment]
@SethTisue yeah, I'll follow @axel22's suggestion.

**Comment by SethTisue** [comment]
@shaulzorea still interested in finishing this up? we plan to cut 2.11.8 circa ~~Oct 25~~ Nov 25

**Comment by SethTisue** [comment]
marking on-hold for now for inactivity

**Comment by SethTisue** [comment]
superseded by #4834. (thank you, @shaulzorea, for getting the ball rolling here)

**Pull request closed without merging**
