### PR TITLE
Enable -YclasspathImpl:flat by default

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
review by @retronym

**Comment by retronym** [comment]
LGTM

Tricky stuff. Hopefully we'll shed some complexity with the next steps to remove the `recursive` implementation, and after that using NIO.

**Comment by lrytz** [comment]
Indeed, if we were to keep the `recursive` implementation this patch would come with more abstractions and less casting around.

**Comment by lrytz** [comment]
community build running here: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/350 - continuation: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/351

**Comment by soc** [comment]
Yay! Thanks, @lrytz!

**Comment by lrytz** [comment]
community build status is being discussed here: https://github.com/scala/scala-dev/issues/108 (looks good overall, there don't seem to be any issues related to this PR)

**Pull request merged**
