### PR TITLE
SI-7630 [Avian] Skip test run/repl-javap-outdir-funs on Avian

### PR DESCRIPTION
**Pull request by soc**
The test fails, because the REPL command reports that no anonfuns were
found. I have spent a considerable amount of time to figure out what's
the issue here with no success.

Skip it for now, so that we don't lose sight of the big picture.

### CODE REVIEW

**Comment by som-snytt** [comment]
I'll try it when I can; I couldn't see what it might be by inspection.

**Comment by soc** [comment]
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang.modules#scala-xml_2.11.0-M4;1.0-RC2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by adriaanm** [comment]
Maybe it's time to start looking into a platform-specific blacklist of tests. I'm not a great fan of making tests sneakily depend on platforms like this. I'll merge for now, but please add an item to your TODO list to remove this irregularity when we're in a state where we can more easily hack partest to support a feature like that.

**Comment by soc** [comment]
@adriaanm Yes, that has been my plan. I thought about throwing some kind of `TestSkippedThrowable` so that the skipped test can be properly marked in partest's output (and can be displayed in the summary at the end).
Maybe @som-snytt has a good idea what's the best way here.

**Pull request merged**
