### PR TITLE
Backported fix for SI-7753 to 2.10.x.

### PR DESCRIPTION
**Pull request by milessabin**

### CODE REVIEW

**Comment by adriaanm** [comment]
Awesome, thanks @milessabin!

**Comment by milessabin** [comment]
Well, _you_ did all the hard work ... thanks! :-)

**Comment by adriaanm** [comment]
Welcome! Can't do it without a long tail of much appreciated contributions, like this one.

**Comment by adriaanm** [comment]
2.11 fix originally merged in #3518

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
