### PR TITLE
SI-7516 Revert "SI-7234 Make named args play nice w. depmet types"

### PR DESCRIPTION
**Pull request by retronym**
This reverts commit 83c9c764b528a7a1c1d39c480d22c8e3a71d5a58.

The tests are shunted to 'pending'.

Whitespace fixes and identifier renaming were not reverted.
Why revert this seemingly innocous commit? 83c9c76 generates a ValDef whose
tpt TypeTree has no original; this contains a reference to the symbol for `d`.
resetAttrs and the retypecheck assigns a new symbol for d and leaves a the
reference to the prior symbol dangling. The real bug is the resetAttrs concept.

Review by @paulp

### CODE REVIEW

**Comment by lrytz** [comment]
commit message should say why

**Comment by paulp** [comment]
Agree reversions should say something helpful in the commit message. Otherwise LGTM.

**Comment by JamesIry** [comment]
@retronym The RC2 submission window is closing tomorrow morning (US west coast time). I can submit a new PR with more info in the commit message if you don't have time to do it.

**Comment by retronym** [comment]
@JamesIry updated.

**Comment by JamesIry** [comment]
LGTM

**Comment by JamesIry** [comment]
Ugh "Error deploying artifact 'org.scala-lang:scala-library:jar': Error deploying artifact: Authorization failed: Access denied to: http://typesafe.artifactoryonline.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-library/2.10.2-851e399-SNAPSHOT/scala-library-2.10.2-851e399-20130529.184834-1-javadoc.jar"

**Comment by adriaanm** [comment]
that failure can be ignored -- it happens after everything else was ok already
it's because the double-publish bug isn't fixed in 2.10.2

**Comment by adriaanm** [comment]
You can rebuild if you prefer -- I've disabled the publishing for now.

**Pull request merged**
