### PR TITLE
fix some compiler warnings

### PR DESCRIPTION
**Pull request by SethTisue**
once we have `@silent` we'll be able to eliminate some more, but
we might as well do this batch now

### CODE REVIEW

**Comment by som-snytt** [comment]
Or just merge https://github.com/scala/scala/pull/8714

**Comment by som-snytt** [comment]
I hope this doesn't trigger merge errors...

**Comment by SethTisue** [comment]
> I hope this doesn't trigger merge errors...

We can handle it. Stay strong!

**Review by som-snytt — COMMENTED** [review]
oh my review is pending, but there is no approve for a merged PR?

You can tell this was the Valentine's week I got covid.

**Pull request merged**
