### PR TITLE
a few missing deprecations in proxy collections.

### PR DESCRIPTION
**Pull request by gourlaysama**
SeqProxy was properly deprecated, so were the CollProxyLike classes, and
the ones in collection.immutable, but these four somehow survived
the Big Proxy Deprecation (tm).

### CODE REVIEW

**Comment by gourlaysama** [comment]
See https://groups.google.com/d/topic/scala-internals/HyAn-6f-5zY/discussion

@retronym can this even go into 2.11.x (adding deprecation warnings and all) or does it have to wait for 2.12?
If the latter, that means the other (already deprecated) proxy classes will have to stay in 2.12 too :(

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@bb2c246

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@bb2c246

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@bb2c246

**Comment by Blaisorblade** [comment]
> @retronym can this even go into 2.11.x (adding deprecation warnings and all) or does it have to wait for 2.12?
> If the latter, that means the other (already deprecated) proxy classes will have to stay in 2.12 too :(

a) `-Xfatal-warnings -deprecation` is often a supported configuration. I think somebody proposed some way around that, to have deprecations visible under -Xfuture (but then, you'd need the deprecation version to be `2.12.0`, **IIRC**).

b) [2.12 won't drop deprecated methods](http://www.scala-lang.org/news/2.12-roadmap), because 2.12 is (library-wise) very close to 2.11 recompiled for Java 8. Quoting:

> Hassle-free cross-building between 2.11 and 2.12 through full backward source compatibility (we won’t remove deprecated methods, but will support optional deprecation errors).

[...]

> We’ll check 2.11/2.12 cross-building by running the same community build on both versions. To improve backwards source compatibility, Scala 2.12 will not remove deprecated members. The 2.12 compiler will however (by default) emit deprecation errors for usage of members deprecated <= 2.11.0. (In principle, if we were to compile the 2.12 library for Java 6, it should be backwards binary compatible with 2.11.)

**Comment by retronym** [comment]
I think we can bend the rules for this one as we are correcting an oversight in a little used corner of the collections framework.

We'll support configurable filtering of deprecation warnings soon, so we can offer the committed fatalists a way to avoid meeting with the swift death of "no warnings can be incurred under -Xfatal-warnings"

**Comment by Ichoran** [comment]
LGTM

**Pull request merged**
