### PR TITLE
Update Java and Sun URLs to replacement Java and Oracle URLs

### PR DESCRIPTION
**Pull request by janekdb**
For each URL
- Where it redirected the target of the redirection was used
- Where is no longer existed a replacement was selected

### CODE REVIEW

**Comment by janekdb** [comment]
Review by @heathermiller, @dickwall, @som-snytt.

**Comment by SethTisue** [comment]
LGTM

**Comment by som-snytt** [comment]
ALGTSMBG, anything looking good to SethTisue must be great!

**Comment by mpociecha** [comment]
GREAT, great :)

**Comment by SethTisue** [comment]
thank you Janek!

**Pull request merged**
