### PR TITLE
Fix for rangepos crasher.

### PR DESCRIPTION
**Pull request by retronym**
wrapClassTagUnapply was generating an unpositioned tree
which would crash under -Yrangepos.  See SI-6338 / SI-6754

Review by @adriaanm (I've bumped this to a 2.10.0 blocker
after the reports or problems in the IDE with Akka.)

Cherry-pick from #1447.

### CODE REVIEW

**Comment by xeno-by** [comment]
If it's a cherry-pick, we're going to have problems propagating this commit to `master`. Maybe we could rather merge it into `2.10.0-wip` retaining the SHA?

**Comment by retronym** [comment]
I don't know what you mean. If we merge, the entire history of that branch is now the history of 2.10.0-wip. I thought git was pretty forgiving of cherry picks getting merged back.

**Comment by xeno-by** [comment]
Your commit's sha and Paul's commit's sha are different. Hence to the best of my knowledge we'll have merge conflicts, even though patch contents are identical.

**Comment by adriaanm** [comment]
That doesn't necessarily cause a merge conflict, I think.

**Comment by adriaanm** [comment]
LGTM, thanks for cleaning up after sloppy, sloppy me, @paulp

**Comment by paulp** [comment]
While there is no doubt plenty of cleaning-up-after-you credit to be given, I think retronym is the right target in this case. (And yes, git is forgiving of cherry-picks - you lose "fast forward merges", but that's irrelevant when we're talking about branches which have meaningfully diverged, as these have.)

**Comment by adriaanm** [comment]
sorry, i haven't been super coherent the last two days.. more affected by that jetlag thingy than i'd care to admit

**Pull request merged**
