### PR TITLE
SI-7350 Close all pipe threads when destroying a PipedProcess

### PR DESCRIPTION
**Pull request by jamespic**
This is a fix for issue 7350

### CODE REVIEW

**Comment by adriaanm** [comment]
Hi @jamespic, this seems to be your first contribution -- welcome and thank you!
Please sign the Scala CLA: http://typesafe.com/contribute/cla/scala/

**Comment by jamespic** [comment]
I've signed the CLA

**Comment by som-snytt** [comment]
I happened to look at related code recently in
https://github.com/scala/scala/pull/2478

This is interesting code.  The fix has the desired effect of unblocking the i/o threads.  But destroy seeks to interrupt the working thread: modulo race conditions and correct handling of interrupted status, I haven't convinced myself it ought to get stuck as it is.  (If you're in a dead state, don't bother blocking indefinitely.)

I'm not sure a test should sleep for five seconds.  A latch could be tripped when the process is run and when i/o is copied, for instance.

I did notice that a small delay before destroy allows more threads to spool up.  There are seven: PipeSource, PipeSink, the dummy process runner, and two threads each for the Dummy and CompoundProcess to run it and fetch the exit value.  Evil spawn!  If I blink, I forget how it all fits together.  I'll follow up later.

**Comment by jamespic** [comment]
I think the reason it gets stuck is that the `PipeSink` and `PipeSource` threads don't know they're in a dead state. Calling `destroy()` interrupts the `PipedProcess` thread, but the `PipedProcess` doesn't (or didn't) attempt to propagate this to the `PipeSink` and `PipeSource` threads (which nothing else knows about).

The patch rectifies this by sending `None` to `currentSource` and `currentSync` (which is how they usually find out about a finished process). Thinking about it though, it might make more sense just to interrupt the `PipeSink` and `PipeSource` threads directly - I can imagine a badly behaved process might force `SyncVar.put` to block or hang.

All this talk of `Thread.interrupt()` does make me wonder about race conditions, though. What happens, for example, if `destroy()` gets called on a process that's currently being destroyed (so it's already in the `InterruptException` handling block).

Oh, and you're right about the 5 second wait. I don't like it either, but I couldn't think of a non-racy way to wait until the threads (ought to) die. A latch in the process or the IO can only be tripped whilst the process or IO threads are running.

**Comment by retronym** [comment]
Review by @harrah, please.

**Comment by harrah** [comment]
I won't have time to review this for a while, sorry

**Comment by som-snytt** [comment]
I'm still grokking the package and improving the test; I have an additional test that looks like that other PR, i.e., forks itself as a real process with real i/o. I'll try to propose something later tonight. Probably @harrah won't have time for the other PR either.

Pic's last comments are germane.

As @paulp would say, it looks like an improvement at least. My initial discomfort was the test; a solid test makes you more confident about the problem space.

I got a little caught up in design issues out of scope, sorry.

**Comment by adriaanm** [comment]
Sorry, we can't do tests that rely on 5s being enough. Our build slaves get really overloaded sometimes and then 5s doesn't cut it.

**Comment by JamesIry** [comment]
What's the status on this PR? Does it it need to be redone?

**Comment by som-snytt** [comment]
I think I wrote a test that night when I said I'd propose something that night.  You'd think I'd've learned like in the last millennium not to say something like that.  Anyway, I'll soon PR on James's branch, I think that's the workflow.

Today I got snagged on sbt's new private SyncVar.  SyncVar has a fascinating history, in that you'd think it would be easier to nail down.  Learning that lesson, I assume this has to be a difficult PR to get just right, or else it would be done already, right?

I think my last impression was that this fix looked good, but what do I know without tests?

**Comment by JamesIry** [comment]
I'm going to close pending a better test.

**Pull request closed without merging**
