### PR TITLE
non symbolic method name equivalents for ProcessBuilder

### PR DESCRIPTION
**Pull request by MasseGuillaume**
thanks to the [feedback from reddit /r/scala](https://www.reddit.com/r/scala/comments/4vuq8r/naming_symbolic_method_for/)

### CODE REVIEW

**Comment by SethTisue** [comment]
we cannot now add new API in 2.12.x, so this needs to be retargeted against the new 2.13.x branch

**Comment by retronym** [comment]
Retargetted

**Comment by MasseGuillaume** [comment]
I will give it another shot. aliasing `!` to `exitValue` is not explicit about the fact that the process started. Maybe `runThenExitValue` or `runExitValue`? Others suggested `exitCode` instead of `exitValue`

**Comment by soc** [comment]
So we have running, blocking and waiting for exit code? `runAndWaitForExitCode` maybe?

**Comment by MasseGuillaume** [comment]
| Signature | Proposed Name | Scaladoc |
| :-- | :-- | :-- |
| `!(log: ProcessLogger): Int` | runAndWaitForExitCode | Starts the process represented by this builder, blocks until it exits, and returns the exit code. |
| `!: Int` | runAndWaitForExitCode | Ibid. |
| `!<(log: ProcessLogger): Int` | runAndWaitForExitCodeStdIn | Ibid. |
| `!<: Int` | runAndWaitForExitCodeStdIn | Ibid. |
| `!!(log: ProcessLogger): String` | runAndWaitForOutput | Starts the process represented by this builder, blocks until it exits, and returns the output as a String. |
| `!!: String` | runAndWaitForOutput | Ibid. |
| `!!<(log: ProcessLogger): String` | runAndWaitForStdIn | Ibid. |
| `!!<: String` | runAndWaitForStdIn | Ibid. |
| `###(other: ProcessBuilder): ProcessBuilder` | also | Constructs a command that will run this command and then other. |
| `#&&(other: ProcessBuilder): ProcessBuilder` | and | Constructs a command that runs this command first and then other if this command succeeds. |
| `#│(other: ProcessBuilder): ProcessBuilder` | pipeTo | Constructs a command that will run this command and pipes the output to other. |
| `#││(other: ProcessBuilder): ProcessBuilder` | orElse | Constructs a command that runs this command first and then other if this command does not succeed. |
| `#<<(f: File): ProcessBuilder` | read | Append the contents of a `java.io.File` to this file |
| `#<<(u: URL): ProcessBuilder` | read | Append the contents from a `java.net.URL` to this file |
| `#<<(i: => InputStream): ProcessBuilder` | read | Append the contents of a `java.io.InputStream` to this file |
| `#<<(p: ProcessBuilder): ProcessBuilder` | read | Append the contents of a [[scala.sys.process.ProcessBuilder]] to this file |
| `#> (f: File): ProcessBuilder` | write | Writes the output stream of this process to the given file. |
| `#>> (f: File): ProcessBuilder` | append | Appends the output stream of this process to the given file. |
| `#>(out: => OutputStream): ProcessBuilder` | write | Writes the output stream of this process to the given OutputStream. The argument is call-by-name, so the stream is recreated, written, and closed each time this process is executed. |
| `#>(b: ProcessBuilder): ProcessBuilder` | write | Writes the output stream of this process to a [[scala.sys.process.ProcessBuilder]]. |
| `lineStream_!(log: ProcessLogger): Stream[String]` | runAndOutputToStream | Starts the process represented by this builder. |
| `lineStream_!: Stream[String]` | runAndOutputToStream | Ibid. |

**Comment by soc** [comment]
Or we use runThen... to give people a better intuition for things like exit code & stdin? `runThenWaitForExitCodeAndStdIn`.

... Or rather `runReadingStdInThenWaitForExitCode`?

**Comment by MasseGuillaume** [comment]
I wont have time to hack on this. I think the java ProcessBuilder is enough: https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html

**Pull request closed without merging**
