### PR TITLE
Don't avoid to load trait impl .class without inliner.

### PR DESCRIPTION
**Pull request by sjrd**
This follows from the discussion in #2963, remove the logic that avoids to load `$class.class` files when the inliner is off.

An alternative could be never to load `$class.class` files (instead of always load them). @gkossakowski said in #2963 that inlining does not work anyway for methods of traits.
However I think this is less regular, and it would definitely take one step _behind_ of fixing that issue.
After all, we do load `.class` files for inner classes, which is also pointless in the absence of inlining. So if we really want to do this, we should also avoid loading all the `.class` files not corresponding to a top-level symbol.

See also:
https://issues.scala-lang.org/browse/SI-4767 Methods defined in traits are not inlined

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gkossakowski, when you have time.

**Comment by retronym** [comment]
I traced this logic back to b80d1e378e586d461b. /cc @dragos

**Comment by sjrd** [comment]
Nice finding. I tried to trace it but did not succeed. I got lost when I reached ee02ad59ce2c42758712a1385f33ce962ae4107c.

**Comment by retronym** [comment]
It was quite a search:

```
  815  git log -S'if (settings.inline)' -- src/compiler/scala/reflect/ --all
  816  git log -S'scalacShouldntLoadClassfile'
  817  git log -S'if (settings.inline) new JavaContext'
  818  git log -S'if (settings.inline.value) new JavaContext'
  819  git show 388a0c0d1db3e41e3acbebd6e1e4c79f7d176ca3
  820  git log -S'if (s.inline.value) new JavaContext'
  823  git show 6e76af56f708d345bda2fff580634107945ef3fb
  824  git log -S'object DefaultJavaContext'
  826  git log -S'override def isValidName'
  827  git show 982baae07693ff1a566b4d90e47be60291342e82
  828  git log -S'// Unless inlining is on, we can exclude $class.class'
  830  git show 7c19904e484f2021b186a81d335fa564a0638baf
  832  git log -S'Why this is necessary is something which should really be documented'
  833  git show 2d487cd460dd5b5064383ebf968d6fb47c7c696d
  834  git log -S'(!className.endsWith("$class") || XO)'
  835  git show ee02ad59ce2c42758712a1385f33ce962ae4107c
  836  git log -S'name.length() > 0 && (!name.endsWith("$class") || settings.XO.value)'
  837  git show b80d1e378e586d461b2b368a8e2612b55e79efc1
``
```

**Comment by dragos** [comment]
IIRC, that was needed in order to "fix" separate compilation. Maybe in the mean time the root cause was fixed. I doubt there is any meaningful test for separate compilation, so I wouldn't rely on "all tests pass".

Regarding parsing inner classes, you'd still need to parse _Java_ inner classes, and AFAIK there's no way to decide that based only on the name.

**Comment by retronym** [comment]
I wonder how many bugs we could flush out by writing a separate compilation tester. It would be easy to write: checkout a project, compile it all, then recompile random subsets of the sources.

@dragos Do you have any clues as to why the optimizer is relevant? One theory: you didn't want to lose inlining from traits (let's pretend that it once worked) so you had to let the bug persist under -optimize.

Let's be conservative with this PR as follows: make this change, but add a -Y option to restore the current behaviour. If someone the stumbles into this bug after the release of 2.11.0, they could compile with the option.

**Comment by sjrd** [comment]
OK I can add the option tomorrow. Any idea for the name of that option? -Yno-load-impl-class-unless-optimize?

**Comment by dragos** [comment]
Your theory is correct. Another benefit of parsing less classfiles is, well, faster symbol loading.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
