### PR TITLE
DefDef.name is now TermName again

### PR DESCRIPTION
**Pull request by xeno-by**
Now when there's no hope left for type macros, it's reasonable to provide
a more specific type for DefDef.name.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
LGTM

**Comment by soc** [comment]
I'm wondering whether there isn't a more appropriate place than `scala.annotation` ...

**Comment by xeno-by** [comment]
@soc You meant this pull request: https://github.com/scala/scala/pull/2810?

**Pull request merged**
