### PR TITLE
Fix for community build blocker.

### PR DESCRIPTION
**Pull request by paulp**
As two character bugfixes go, this was a doozy.
I will forego elaborating at length and offer generic
instructions for elucidation:

% git log --grep=tpeHK

### CODE REVIEW

**Comment by jsuereth** [comment]
wow.  Separate compilation necessary?

LGTM

**Comment by paulp** [comment]
Not just separate compilation - source files have to come in specific order.  Flip them around, it's okay.

**Comment by paulp** [comment]
By which I mean, separate compilation not necessary.  But file ordering is.

**Comment by jsuereth** [comment]
Looks like I need a better debug/triage method/setup.   Thanks for finding/fixing.

**Comment by paulp** [comment]
I had the distinct advantage of having [been here before](https://issues.scala-lang.org/browse/SI-4070), and it still took me a long time.

**Pull request merged**
