### PR TITLE
Merge 2.11 to 2.12

### PR DESCRIPTION
**Pull request by lrytz**
Follow-up for #5054

```
$ git log --decorate --oneline -1 intellij-2.11 | cat
5f5cc18 (origin/intellij-2.11, intellij-2.11) Update IntelliJ build for use with sbt

$ git log --decorate --oneline -1 2.12.x | cat
ad48e59 (HEAD -> merge-2.11-to-2.12-mar-21, upstream/2.12.x, origin/2.12.x, 2.12.x) Merge pull request #5043 from dongjoon-hyun/fix_typos_in_spec_and_comments

$ export MB=$(git merge-base 2.12.x intellij-2.11)

$ git checkout 2.12.x
$ git checkout -b merge-2.11-to-2.12-mar-21

$ git log --graph --oneline --decorate $MB...intellij-2.11 | cat
* 5f5cc18 (origin/intellij-2.11, intellij-2.11) Update IntelliJ build for use with sbt
* afb1458 (upstream/2.11.x, origin/2.11.x, 2.11.x) Merge pull request #5030 from SethTisue/newer-akka
* 22b7905 Merge branch '2.11.x' into newer-akka
* bd4926f bundle a newer Akka actors jar

$ git merge afb1458 -s ours
Merge made by the 'ours' strategy.
$ git diff 2.12.x | cat
$

$ git merge 5f5cc18
$ git status -sb
## merge-2.11-to-2.12-mar-21
M  .gitignore
M  build.sbt
UU project/plugins.sbt
  - fix conflict
A  project/project/plugins.sbt
UU src/intellij/README.md
  - pick version from 2.11
DU src/intellij/actors.iml.SAMPLE
  - keep
D  src/intellij/asm.iml.SAMPLE
M  src/intellij/compiler.iml.SAMPLE
D  src/intellij/diff.sh
DU src/intellij/forkjoin.iml.SAMPLE
  - keep
M  src/intellij/interactive.iml.SAMPLE
UU src/intellij/junit.iml.SAMPLE
  - pick 2.11 version
M  src/intellij/library.iml.SAMPLE
M  src/intellij/manual.iml.SAMPLE
M  src/intellij/partest-extras.iml.SAMPLE
M  src/intellij/partest-javaagent.iml.SAMPLE
M  src/intellij/reflect.iml.SAMPLE
R  src/intellij/test-junit.iml.SAMPLE -> src/intellij/repl-jline.iml.SAMPLE
M  src/intellij/repl.iml.SAMPLE
M  src/intellij/scala-build.iml.SAMPLE
M  src/intellij/scala.iml.SAMPLE
UU src/intellij/scala.ipr.SAMPLE
  - fix conflict
M  src/intellij/scaladoc.iml.SAMPLE
M  src/intellij/scalap.iml.SAMPLE
D  src/intellij/setup.sh
UU src/intellij/test.iml.SAMPLE
  - fix conflict
D  src/intellij/update.sh
```

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @szeiger. The changes to the sbt import scripts for 2.12.x are in a separate commit. The change of the akka-actors in 2.11.x doesn't apply to 2.12.x (we don't pull in akka-actors anymore).

**Comment by szeiger** [comment]
@lrytz This contains the original version of the IntelliJ import commands without the improvements and fixes in the latest PR. Do you want to update this PR with the latest version or follow up with a manual update?

Apart from that, LGTM

**Comment by lrytz** [comment]
i'll merge #5054 into 2.11.x and then append a commit here that merges the latest 2.11.x, OK?

**Comment by szeiger** [comment]
sounds good

**Comment by lrytz** [comment]
here's the log for the second part of the merge (commits pushed):

```
$ git log --decorate --oneline -1 HEAD | cat
3721775 (HEAD -> merge-2.11-to-2.12-mar-21, origin/merge-2.11-to-2.12-mar-21) Updates to IntelliJ files for 2.12.x

$ git log --decorate --oneline -1 2.11.x | cat
1fcfdd8 (upstream/2.11.x, origin/2.11.x, 2.11.x) Merge pull request #5054 from lrytz/intellij-2.11

$ export MB=$(git merge-base HEAD 2.11.x)

$ git log --graph --oneline --decorate $MB...2.11.x | cat
*   1fcfdd8 (upstream/2.11.x, origin/2.11.x, 2.11.x) Merge pull request #5054 from lrytz/intellij-2.11
|\
| * 2b3696e (origin/intellij-2.11, intellij-2.11) Cleanup IntelliJ integration based on review feedback
*   4ef1429 Merge pull request #5056 from viktorklang/wip-SI9488-Future.toString-√
|\
| * d832346 SI-9488 - adds the same default toString format to Scala Futures as 2.12.x
* 46595fb Merge pull request #5026 from SethTisue/scala-xml-version-bump
* 1ae6fc0 Merge branch '2.11.x' into scala-xml-version-bump
* 76f633c upgrade to latest scala-xml (namely 1.0.5)


  - #5026 changed scala-xml.version.number to 1.0.5, which is already the case in 2.12.x
  - #5056 added Promise.toString and tests, which both already exist in 2.12.x (see #4042)

$ git merge 4ef1429 -s ours
Merge made by the 'ours' strategy.
$ git diff 3721775 | cat
$

$ git merge 1fcfdd8
Auto-merging build.sbt
CONFLICT (content): Merge conflict in build.sbt
  - conflict in the list of modules for which to update intellij (no actors/forkjoin in 2.12.x)
```

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
