### PR TITLE
SI-8711 ScalaVersion.unparse doesn't produce valid versions

### PR DESCRIPTION
**Pull request by gourlaysama**
There is no dot between `major.minor.rev` and `-build` in a scala
version, yet that's what unparse returns for:

```
// was "2.11.3.-SNAPSHOT"
ScalaVersion("2.11.3-SNAPSHOT").unparse
```

### CODE REVIEW

**Comment by dragos** [comment]
Sorry guys, this and other builds since around 11 CET this morning are failing due to an error in our uber-build script. Should be fixed now.

**Comment by dragos** [comment]
PLS REBUILD/pr-scala@c90be86

**Comment by som-snytt** [comment]
It's an old song, but the test could be a unit test.

**Comment by gourlaysama** [comment]
PLS REBUILD ALL

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
