### PR TITLE
give better suggestion for unused pattern

### PR DESCRIPTION
**Pull request by martijnhoekstra**
As suggested in https://gitter.im/scala/scala?at=5d653f4f0221796a241083ec

### CODE REVIEW

**Comment by matanox** [comment]
And/or please someone explain why @_ could be useful in some way I guess ...

**Comment by Jasper-M** [comment]
This warning probably also appears for less trivial cases like this, where `case _ =>` doesn't work.

```
case Foo(a, b) => s"not using a but am using $b"
```

I think the intended use case of the message was probably for complicated patterns where you want to name some parts for doc purposes even though you're not using them.

**Comment by martijnhoekstra** [comment]
@Jasper-M that makes sense. Closing for now

**Comment by som-snytt** [comment]
Yes, in particular, people want "named args" for patterns but can't have them, which would be especially useful when you have several parameters (perhaps more than is wise):
```
case class C(a: Int, b: Int, c: Int, d: Int)
x match { case C(c = 42) => }  // hypothetical syntax for matching C.c == 42 ?
x match { case C(c = c) => }  // hypo syntax for c = C.c ?
x match { case C(_, _, c, _) => } // lots of underscores
x match { case C(a@_, b@_, c, d@_) => } // documentary placeholders
x match { case C(a@_, b@_, c @ 42, d@_) => }  // matching 42
x match { case x: C => import x._ }   // you can't be bothered
```
`case a @ _` is the general form of `case a`, so it is regular syntax, but leveraged for folks who like `-Wunused:patvars`. 

Come to think of it, `a@_` is reminiscent of `import x.{a => _}`. It doesn't have the force of "don't used me". You can't annotate a pattern, but now one could honor:
```
x match { case C(a: Int @unused, b: Int @unused, c, d: Int @unused) => }
```
The message is not emitted under normal `-Xlint` recommendations, but only if the user asks for it with `-Wunused`. Anyone who wants `-Wunused:patvars` should understand the ergonomics of the feature, as documented here.

**Comment by nafg** [comment]
@Jasper-M isn't that just a criticism of showing the `=>` in the message?

Just to put these side by side,

Old:

```scala
s"pattern var ${v.name} in ${v.owner} is never used; `${v.name}@_` suppresses this warning"
```

Proposed:
```scala
s"pattern var ${v.name} in ${v.owner} is never used: consider _ => instead. `${v.name}@_` suppresses this warning"
```

The change was to insert "consider _ => instead", and the issue IIUC with that is that we don't know that the pattern is adjacent to the arrow.

However the broader point IIUC is that `<name>@_`, when <name> is not used, is AFAICT completely equivalent to `_` but more verbose.

So, what is the argument against changing the message to
```scala
s"pattern var ${v.name} in ${v.owner} is never used. You can use an underscore instead of a name to avoid this warning.
```

Or the more conservative

```scala
s"pattern var ${v.name} in ${v.owner} is never used: consider _ instead. `${v.name}@_` suppresses this warning"
```

?

**Comment by martijnhoekstra** [comment]
IMO a good message should both suggest the underscore, and indicate the
suppression, so that if you do really want to use an unused name, you have
a way to suppress.

**Comment by martijnhoekstra** [comment]
reopened with a little more care.

**Pull request closed without merging**
