### PR TITLE
SI-7622 Clean Up Phase Assembly

### PR DESCRIPTION
**Pull request by som-snytt**
Asking kitteh for sanity check.

"Clean" here means that a component can declare cleanly if it is "enabled",
whether it is an "initial" or "terminal" phase, and the user can tell from
-Xshow-phases what phases are configured, and by adding -Ydebug, what
components are available but not turned on.

Disabled components are listed with an icon instead of a phase number:
xx for phases that are not enabled (such as by a compiler option),
and oo for phases that disabled by -Yskip.

Compiler options that take phases as settings ("PhasesSettings") are now
sanity-checked at phase assembly.

As usual, phases can be specified as name prefixes or ranges of ids.

The few options that exclude a phase from the run (-Yskip and -Ystop) are
required to name the phase. (A future improvement may be to permit
-optimise -Yskip:23-27, i.e., turn on the flag but skip the phases without
writing -Yskip:inline,inlinehandlers,etc.)

Generating the .dot file is an "info" option like -Xshow-phases. If "phase assembly"
hits an error, it will dump the .dot file instead of asking you to re-run.  That's
because if a phase assembly caused the problem it might not be easy to
reproduce.

The current "phase assembly" code works a lot better when the object you
put into hash tables actually have meaningful hash codes.  The unstable
test of detecting cycles is moved out of pending.

### CODE REVIEW

**Comment by som-snytt** [comment]
Thanks for the insanity check, kitteh.  I was indeed fearful that runsRightAfter would torpedo it.  IMHO, a useless thing to require of every component.  Only intimate components want to follow each other.  Case in point, global has a comment for patmat not to follow typer because sbt wants to; "as long as we run before superaccessors", but then doesn't set runsBefore.

**Comment by som-snytt** [comment]
Maybe.

**Comment by som-snytt** [comment]
I knew the tests had to deal with -optimise, then I forgot.

**Comment by som-snytt** [comment]
Includes partest fixes and enhancement to allow a checkfile to ifdef -optimise (or any arg in SCALAC_OPTS).

The changes are split across ten commits.  That was good git practice.

I didn't run the whole ant build locally for each commit like kitteh can do, but I did partest --neg --run.  Yeah, that's one of the partest fixes.

Thanks to @paulp for the previous "compiler chain" init with the init order issues resolved, which I merely bike-shedded, though as Wallace tells Gromit, "It's amazing what a lick of paint will do."

**Comment by adriaanm** [comment]
Please submit partest fixes to https://github.com/scala/scala-partest. I think the test category one is covered.

**Comment by som-snytt** [comment]
This is not yet rebased around the new regime, but fixes the bad checkfile merges, and also an extra space in a check file that took forever and a day to track down, hence extra debug support in partest. Let's see if the last tests pass ok.

**Comment by som-snytt** [comment]
This is no longer clean from a github perspective.

**Pull request closed without merging**
