### PR TITLE
Copy propagation, remove unused values (closures!) and local variables

### PR DESCRIPTION
**Pull request by lrytz**
See individual commit messages.

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @retronym

**Comment by lrytz** [comment]
Community build running here: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/205/parameters/

**Comment by lrytz** [comment]
The community build found some issues, will look at those next week:

```
[spire:error] java.lang.NullPointerException
[spire:error]   at scala.tools.nsc.backend.jvm.opt.BytecodeUtils$FrameExtensions$.peekStack$extension(BytecodeUtils.scala:490)
[spire:error]   at scala.tools.nsc.backend.jvm.opt.LocalOpt.replaceByPop$1(LocalOpt.scala:404)
[spire:error]   at scala.tools.nsc.backend.jvm.opt.LocalOpt.scala$tools$nsc$backend$jvm$opt$LocalOpt$$$anonfun$9(LocalOpt.scala:411)
[spire:error]   at scala.tools.nsc.backend.jvm.opt.LocalOpt.scala$tools$nsc$backend$jvm$opt$LocalOpt$$$anonfun$9$adapted(LocalOpt.scala:410)
[spire:error]   at scala.tools.nsc.backend.jvm.opt.LocalOpt$$Lambda$8395/1251991824.apply(Unknown Source)
[spire:error]   at scala.collection.TraversableLike$WithFilter.scala$collection$TraversableLike$WithFilter$$$anonfun$40(TraversableLike.scala:778)
[spire:error]   at scala.collection.TraversableLike$WithFilter$$Lambda$4644/409134695.apply(Unknown Source)
[spire:error]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[spire:error]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[spire:error]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
[spire:error]   at scala.tools.nsc.backend.jvm.opt.LocalOpt.eliminateStaleStores(LocalOpt.scala:410)
```

also akka and twitter-util failed, the rest passed.

**Comment by SethTisue** [comment]
(the twitter-util failure is unrelated to your changes)

**Comment by lrytz** [comment]
Fixed the bugs uncovered by the community build, second iteration is running: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/212/console

**Comment by lrytz** [comment]
community build (with the optimizer enabled) succeeded: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/213/

**Comment by retronym** [comment]
I'll take another pass over this tomorrow.

**Comment by lrytz** [comment]
closing in favor of #4858

**Pull request closed without merging**
