### PR TITLE
[MORIBUND] String input for process

### PR DESCRIPTION
**Pull request by som-snytt**
https://github.com/scala/bug/issues/11668

### CODE REVIEW

**Comment by SethTisue** [comment]
see also https://github.com/scala/scala/pull/8323

**Comment by som-snytt** [comment]
M1 is just in time for the winter holiday gift-giving season, which also coincides with the gift-receiving season. I can't wait!

This PR is complementary to jroper's and differs from it in ways I no longer remember.

Would it be OK if I started a contest on the forum to name the `!!<<` operator? I was going to propose `Bang Bang Kiss Kiss`.

**Comment by som-snytt** [comment]
I'll reopen if 2.14.

**Comment by som-snytt** [comment]
If they revived 2.14 for release on 2/14, they could put `Bang Bang Kiss Kiss` on one of the heart-shaped candies.

**Pull request closed without merging**
