### PR TITLE
Avoid storing source file contents twice

### PR DESCRIPTION
**Pull request by Blaisorblade**
BatchSourceFile instances contain two almost identical character arrays,
content0 and content. What's worse, content0 is even public. Instead,
content0 should just be a constructor parameter. This seems the residual
of an incomplete refactoring.

I observed this waste of memory during debugging; after applying this
patch, I've verified by hand that the second field indeed disappears.

I don't expect a measurable difference, but this patch is not premature
optimization because it makes code more logical.

Review by @retronym .

### CODE REVIEW

**Comment by Blaisorblade** [comment]
FWIW, I tracked the "residual of an incomplete refactoring" down to #924, 32fd97df41bb2e99018f024f41b06490e41bd7ad, and originally https://github.com/paulp/scala/commit/4868d655ad8769f58f923154a1a31373ead71a45, which doesn't have the problem, so it looks like a slip in the merge — this was written pre-reflection, and merged post-reflection.

**Comment by xeno-by** [comment]
@retronym I think fix looks very much worth inclusion in RC1, granted it's so minimal and provides a clear performance win.

**Comment by Blaisorblade** [comment]
@xeno-by That's very much appreciated. I've just seen the inside of the sausage factory & GADT type refinement, I badly need a break.

**Comment by gkossakowski** [comment]
LGTM.

I'm doing some work stealing to ease @retronym's reviewing load.

**Comment by som-snytt** [comment]
Good catch.  I've had to look at that code and read the comment.  At least the bug had the salutary effect of punishing those who don't put a newline at the end of source files.

**Pull request merged**
