### PR TITLE
SI-9375 fix de-serialization of nested modules [dirty prototype]

### PR DESCRIPTION
**Pull request by lrytz**
see the issue description for the problem. my first comment on the
issue proposes the solution prototyped here.

### CODE REVIEW

**Comment by lrytz** [comment]
@retronym, what do you think about the approach?

**Comment by retronym** [comment]
This seems like a truly awful problem.

To help me understand the tradeoffs, given:

``` scala
class Outer { object Inner { var x = "initial"; def outer = Outer.this }
val o1 = new Outer
val data = serialize(o1.Inner)
o1.Inner.x = "b"
val innerDeserialized = deserialize(data).asInstanceOf[o.Inner forSome { val o: Outer }]
```

Which of these assertions holds? Why/why not?

``` scala
assert(innerDeserialized.outer eq o1) 
assert(innerDeserialized.x == "initial")
assert(innerDeserialized.outer.Inner eq innerDeserialized)
```

**Comment by lrytz** [comment]
for serialization, the outer field is just like any other field. so when serializing an inner object, its outer field is serialized with it. since the outer class is an ordinary class (not a module with some readResolve), a new instance is created upon de-serialization.

that is the same before and after this patch. the following you can paste into 2.11.7:

```
import java.io._

def serialize(obj: AnyRef): Array[Byte] = {
  val buffer = new ByteArrayOutputStream
  val out = new ObjectOutputStream(buffer)
  out.writeObject(obj)
  buffer.toByteArray
}

def deserialize(a: Array[Byte]): AnyRef = {
  val in = new ObjectInputStream(new ByteArrayInputStream(a))
  in.readObject
}

def serializeDeserialize[T <: AnyRef](obj: T) = deserialize(serialize(obj)).asInstanceOf[T]

object P {
  trait I {
    def x: String
    def outer: Outer
  }
  class Outer extends Serializable { object Inner extends I with Serializable { var x = "initial"; def outer = Outer.this } }
}
import P._
val o1 = new Outer
val data = serialize(o1.Inner)
o1.Inner.x = "b"
val innerDeserialized = deserialize(data).asInstanceOf[I]

innerDeserialized eq o1.Inner // false
innerDeserialized.outer eq o1 // false
innerDeserialized.x == "initial" // true
o1.Inner.x == "b" // true
innerDeserialized.outer.Inner eq innerDeserialized // true
```

**Comment by lrytz** [comment]
now i'm actually wondering what happens if we just get rid of the `readResolve` method for inner (i.e., non-static) objects.

**Comment by lrytz** [comment]
that was a long detour ending at a one-liner: https://github.com/scala/scala/commit/ddde37f710ac1ac95ad8d8c9fe037198626cd311. submitted in #4671

**Pull request closed without merging**
