### PR TITLE
SI-7200 Test case for fixed type inference error.

### PR DESCRIPTION
**Pull request by retronym**
Broken in 2.9.2 and 2.10.0, but working in 2.10.1

``` patch
--- sandbox/2.10.0.log
+++ sandbox/2.10.1.log
       def coflatMap[A >: Nothing <: Any, B >: Nothing <: Any](f: Test.Nel[A] => B): Test.Nel[A] => Test.Nel[B] = ((l: Test.Nel[A]) => Test.this.Nel.apply[B](f.apply(l), l.tail match {
         case immutable.this.Nil => immutable.this.Nil
-        case (hd: A, tl: List[A])scala.collection.immutable.::[A]((h @ _), (t @ _)) => {
-          val r: Test.Nel[Nothing] = NelFoo.this.coflatMap[A, Nothing](f).apply(Test.this.Nel.apply[A](h, t));
+        case (hd: A, tl: List[A])scala.collection.immutable.::[?A1]((h @ _), (t @ _)) => {
+          val r: Test.Nel[B] = NelFoo.this.coflatMap[A, B](f).apply(Test.this.Nel.apply[A](h, t));
           {
-            <synthetic> val x$1: Nothing = r.head;
-            r.tail.::[Nothing](x$1)
+            <synthetic> val x$1: B = r.head;
+            r.tail.::[B](x$1)
           }
         }
       }))
```

b74c33eb86 represents the exact moment of progression. Comments
in pos/t7200b.scala, a minimal test that demonstrates the problem
without type constructors or code execution, pinpoint the line of
code responsible for the fix.

Incidentally, I'm currently on a train somewhere between Solothurn
and Biel, and am consequently without the power of scala-bisector.
Undeterred, and inspired by a line I saw in Skyfall last night
("sometimes the olds ways are better"), I just pulled off a two-hop
bisection. Take that, O(log N)!

The one remaining worry is the appearance of the type variable
?A1 in the output of -Xprint:typer for run/t7200.scala.

Review by @lrytz

### CODE REVIEW

**Comment by retronym** [comment]
And review by @adriaanm for insights into that stray `?A1`.

**Comment by paulp** [comment]
The appearance of A1 can be reduced to this:

```
case class X[A](xs: List[A])
class Y { def f[A](xs: List[A]) = X(xs match { case _ :: t => t }) }

/*** 2.10.0 vs. 2.10.1
<       case (hd: A, tl: List[A])scala.collection.immutable.::[A](_, (t @ _)) => t
---
>       case (hd: A, tl: List[A])scala.collection.immutable.::[?A1](_, (t @ _)) => t
***/
```

Intuitively, it looks right/necessary to me, based on my recollections of the unsoundnesses in pattern matching with covariant members.

**Comment by retronym** [comment]
But shouldn't `TypeVars` be ephemeral? I would have expected that the post-typer tree should not have them.

> A class representing a type variable: not used after phase `typer`.

**Comment by paulp** [comment]
Yeah, you're right of course.

**Comment by paulp** [comment]
```
% qscalac -Xdev -d /tmp a.scala 
a.scala:2: warning: GADT skolem survived typer in (hd: A, tl: List[A])scala.collection.immutable.::[?A1]
class Y { def f[A](xs: List[A]) = X(xs match { case _ :: t => t }) }
                                                      ^
```

The locations hit when compiling src/library:

```
./src/library/scala/collection/convert/WrapAsJava.scala:32: warning: GADT skolem survived typer in (underlying: java.util.Iterator[?A1])scala.collection.convert.Wrappers.JIteratorWrapper[?A1]
    case JIteratorWrapper(wrapped) => wrapped.asInstanceOf[ju.Iterator[A]]
         ^
./src/library/scala/collection/convert/WrapAsJava.scala:50: warning: GADT skolem survived typer in (underlying: java.util.Enumeration[?A2])scala.collection.convert.Wrappers.JEnumerationWrapper[?A2]
    case JEnumerationWrapper(wrapped) => wrapped.asInstanceOf[ju.Enumeration[A]]
         ^
./src/library/scala/collection/convert/WrapAsJava.scala:68: warning: GADT skolem survived typer in (underlying: Iterable[?A3])scala.collection.convert.Wrappers.JIterableWrapper[?A3]
    case JIterableWrapper(wrapped) => wrapped.asInstanceOf[jl.Iterable[A]]
         ^
./src/library/scala/collection/convert/WrapAsJava.scala:84: warning: GADT skolem survived typer in (underlying: java.util.Collection[?A4])scala.collection.convert.Wrappers.JCollectionWrapper[?A4]
    case JCollectionWrapper(wrapped) => wrapped.asInstanceOf[ju.Collection[A]]
         ^
./src/library/scala/collection/convert/WrapAsJava.scala:138: warning: GADT skolem survived typer in (underlying: java.util.List[?A5])scala.collection.convert.Wrappers.JListWrapper[?A5]
    case JListWrapper(wrapped) => wrapped.asInstanceOf[ju.List[A]]
         ^
./src/library/scala/collection/convert/WrapAsJava.scala:233: warning: GADT skolem survived typer in (underlying: java.util.Map[A,?B1])scala.collection.convert.Wrappers.JMapWrapper[A,?B1]
    case JMapWrapper(wrapped) => wrapped.asInstanceOf[ju.Map[A, B]]
         ^
```

**Comment by paulp** [comment]
Oh yeah, and, it's a TypeRef around a gadt skolem, not a TypeVar.

**Comment by retronym** [comment]
ping @lrytz for review and any theories on the stray GADT skolems

**Comment by JamesIry** [comment]
also ping @adriaanm

**Comment by adriaanm** [comment]
I unfortunately don't have additional insights to offer.

**Pull request merged**
