### PR TITLE
SI-7469 Remove deprecated elements in Java{Conversions,Converters}

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Regarding the failed test: It seems like `AsJava`/`AsScala` is not accessible more with these type aliases gone, or am I mistaken?
Is this intentional?

**Comment by paulp** [comment]
It looks like it's intentional, as much as I can figure out past-me. JavaConverters may need to be tweaked to work as it did. See the convert package object for the granular offering.

```
package object convert {
  val decorateAsJava  = new DecorateAsJava { }
  val decorateAsScala = new DecorateAsScala { }
  val decorateAll     = new DecorateAsJava with DecorateAsScala { }
  val wrapAsJava      = new WrapAsJava { }
  val wrapAsScala     = new WrapAsScala { }
  val wrapAll         = new WrapAsJava with WrapAsScala { }
}
```

**Comment by soc** [comment]
Yes, I did look at the convert object before assuming that this capability is gone. I'll look into rationale of the test and then either rewrite or remove it. (We want to get rid of view bounds anyway, right?)

**Comment by soc** [comment]
@paulp So what's your opinion on how we should approach this?

**Comment by paulp** [comment]
I don't have much of one. You can probably just kill or reduce the test.

**Comment by soc** [comment]
Ok, will do. Thanks.

**Comment by soc** [comment]
@paulp Updated.

**Comment by paulp** [comment]
I got sidetracked trying to fix the bug which underlies the test you removed. It's an incredibly sketchy show in there. LGTM.

**Pull request merged**
