### PR TITLE
SI-9473 Cleaner references to statically owned symbols

### PR DESCRIPTION
**Pull request by retronym**
Ever wonder why `identity("")` typechecks to
`scala.this.Predef.identity("")`?

It turns out that `mkAttributedRef` was importing
`q"$scalaPackageClass.this.Predef._"` for all these years,
rather than `q"$scalaModule.Predef._"`.

This commit makes `mkAttributedRef` special case static owners
by referring the the corresponding module, instead.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @lrytz 

I tried an followup commit that uses more concise trees, so a reference to `ScalaRuntime` could just be `Ident(ScalaRuntimeModule)`, rather than `Select(Select(ScalaPackageClass.sourceModule, "runtime"), TermName("ScalaRuntime"))`. 

This broke some assumptions about trees in some tests, so I didn't pursue it further.

**Comment by lrytz** [comment]
the test output suggests that a qualifying package is now missing - i think it should still be there:

```
% diff /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/presentation/t8941-presentation.log /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/presentation/t8941.check
@@ -3,5 +3,5 @@ reload: Source.scala
 askType at Source.scala(6,7)
 ================================================================================
 [response] askTypeAt (6,7)
-scala.Predef.???
+Predef.???
 ================================================================================
```

```
% diff /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/presentation/random-presentation.log /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/presentation/random.check
@@ -4,7 +4,7 @@ askType at Random.scala(18,14)
 ================================================================================
 [response] askTypeAt (18,14)
 val filter: Int => Boolean = try {
-  java.lang.Integer.parseInt(args.apply(0)) match {
+  lang.Integer.parseInt(args.apply(0)) match {
     case 1 => ((x: Int) => x.%(2).!=(0))
     case 2 => ((x: Int) => x.%(2).==(0))
```

**Comment by retronym** [comment]
Pushed updated checkfiles.

**Comment by retronym** [comment]
Pushed updated checkfiles, for real this time.

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
