### PR TITLE
Unused warning checks self-type for overrides

### LINKED ISSUE #10314: -Xlint:unused false positive with self type, in Scala 2.12.2
(related: #10313)

E.g. 

    trait Tx

    trait Base {
      def foo(implicit tx: Tx): Unit
    }

    trait MixIn {
      self: Base =>
    
      def foo(implicit tx: Tx): Unit = println("Hello")
    }

Obviously this shouldn't produce a warning.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#10314

`self` is `thisType` not `typeOfThis`. It seems sufficient to take `bases` as `self.baseClasses` instead of `base.baseClasses`.

### CODE REVIEW

**Comment by som-snytt** [comment]
"I'll just call it `self`. No one ever calls anything `self`. After all, there can't be more than one `self`, right?"

Edit: to clarify, bootstrap broke because of self-type this-name `self` conflicting with `self` member of pairs cursor, due to revised name binding rule. Hard to believe the early-pandemic change finally slipped in under lrytz's guidance last late pandemic December.

**Comment by SethTisue** [comment]
Quoth the raven, “Needs rebase.”

**Comment by som-snytt** [comment]
That's OK. Under my new "system", there must be a reason it's in draught mode.

**Comment by SethTisue** [comment]
draft mode is when you say the hell with it and head down to the pub

**Comment by som-snytt** [comment]
The paper title is "Continuation-Passing to Direct Style: Typed and Tight", which is open to all sorts of crude jokes, but I would have said stumbling home late after a conference.

**Comment by som-snytt** [comment]
The non-strict mode exclusion is for extracting a value and assigning it to a value of the same name:
```
val n = x match { case P(n) => n }   // obviously a useful alias, never warn
```
also for narrowing the scrutinee
```
x match { case x: Y => f(x) }   // shadows an `x` in scope which is the scrutinee
```
but it seems to me that this common pattern needs assistance:
```
        case Block(Nil, expr) => expr
```
where `expr` is guaranteed to shadow something somewhere, but it's "obviously" used as intended.

Possibly the more useful heuristic is warn if `expr` is unused (on the RHS, perhaps an addendum to the unused warning), or maybe warn immediately if `-Wunused:patvars` is off.

The broader question is whether shadowing is usually bad. Certainly it's easy to lose track of which term `qual` is intended. To me, this sort of shadowing is poor style and confusing:
```
def f(xs: X*) = { def g(xs: X*) = xs.map(h); g(xs: _*) }
```
If `g` is recursive, maybe the param is `remaining`.

But it's harder to get creative with names like `tree`, `expr`, `qual`. Here it would be useful to write `case P(expr') =>` where the single quote means introduce a shadowing variable.

**Comment by som-snytt** [comment]
When I claim to be the goat, I literally mean the guy in my profile picture.

**Review by lrytz — APPROVED** [review]

**Pull request merged**
