### PR TITLE
Scaladoc: Better icon for annotations

### PR DESCRIPTION
**Pull request by m-sp**
Use an `@` and a lighter shade of green for classes that extend `Annotation`
For a screenshot take a look at the issue.

Fixes scala/bug#4489

### CODE REVIEW

**Comment by m-sp** [comment]
rebased and for anybody interested: https://m-sp.github.io/4489/demo/tailrec.html

**Comment by hrhino** [comment]
Personally, I think the `@` looks a little bit higher than vertically centered; maybe move it down a few px?

EDIT: I like [how you had it](https://github.com/scala/bug/issues/4489#issuecomment-386410477) on the issue:

like this...

**Comment by m-sp** [comment]
thanks for taking a look!
seems like it's a font issue. different fonts are used on different operating systems.
I guess you are using mac?

I'll try to fix that!

**Comment by hrhino** [comment]
yep, I'm on OS X. It looks like this:

on os x

**Comment by m-sp** [comment]
moved it down a couple of pixels. should hopefully look better now under mac.

**Review by lrytz — APPROVED** [review]
Very nice work, thank you!

**Pull request merged**
