### PR TITLE
[REVISIT MAYBE] Script parser preserves target module

### LINKED ISSUE #12889: scala runner renames main object
## Reproduction steps

Scala version: 2.13.12

```scala
➜  snips cat mainly.scala

class C(private val c: Int)

object C {
  def main(args: Array[String]): Unit = {
    println(new C(42).c)
  }
}
➜  snips scalac -d /tmp/sandbox mainly.scala
➜  snips scala -Vprint mainly.scala
mainly.scala:6: error: value c in class C cannot be accessed as a member of C from object Main
    println(new C(42).c)
                      ^
[[syntax trees at end of                     typer]] // mainly.scala
package <empty> {
  class C extends scala.AnyRef {
    <paramaccessor> private[this] val c: Int = _;
    <stable> <accessor> <paramaccessor> private def c: Int = C.this.c;
    def <init>(c: Int): C = {
      C.super.<init>();
      ()
    }
  };
  object Main extends scala.AnyRef {
    def <init>(): Main.type = {
      Main.super.<init>();
      ()
    };
    def main(args: Array[String]): Unit = scala.Predef.println(new C(42).<c: error>)
  }
}
```

## Problem

For some reason, the `scala` runner rudely assumes it can rename my object that has a `main` method.

Probably I am the last person on Earth to use the old `scala` runner.

Noticed while trying out a snippet submitted for a Dotty bug (a different bug).

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12889

Allow adding main to an existing object.

It takes a prefix of top-level statements which remain top-level (which helps with any issues with local methods).

If the "target" module was already defined at the "bottom of the file", so that it winds up in the "main" method, then also synthesize a call to its existing main method or just initialize the lazy object if there is no main method. [TODO]

### CODE REVIEW

**Comment by som-snytt** [comment]
I tried reviewing this and now I can't stop yawning.

**Comment by SethTisue** [comment]
Is the TODO in the PR description still a TODO? (And for this PR, or for some hypothetical future PR?)

**Comment by som-snytt** [comment]
🥱 

I believe that todo was aspirational, in the medical sense of

> Aspiration is when something you swallow "goes down the wrong way" and enters your airway (trachea or windpipe) or lungs.

trying to snack while yawning uncontrollably.

**Comment by SethTisue** [comment]
@som-snytt I'm going to go into schoolmarm mode here and say: I'm not sure I understand you, and also, this isn't only about it's about whether I personally understand. For the PR to be considered ready for review, can you edit the PR description to reflect the current state, as clearly as you possibly can? It's generally okay to be more freewheeling in our back-and-forth in the comments, but PR descriptions are documentation.

**Comment by som-snytt** [comment]
Yes, I'll get back to this before 2.13.~14~15!

Edit: oh, I see I marked it ready for review. Maybe I wanted feedback on whether it's worth trying for 2.13.13, but it's not critical; it's just a nuisance when testing code snippets.

**Comment by SethTisue** [comment]
Yeah, offhand I'd say this looks eventually-mergeable, but 2.13.14 would be fine.

**Comment by som-snytt** [comment]
I needed this today. Ticket has
```
object Bug {
  def main(args: Array[String]): Unit = {
    sealed trait Step {
```
but `Bug` is rewritten to `Main`. Just run the code.

**Comment by som-snytt** [comment]
Happened again the other day. Worse than `-Vprint`, it was when scanning `javap` output. Hard enough to locate lambdas and App code without changing class names. I'll clean up this PR finally.

**Review by lrytz — APPROVED** [review]
LGTM already

**Comment by SethTisue** [comment]
@som-snytt shall we revive this one?

**Comment by som-snytt** [comment]
This is a bit fiddly (not in the sense of bit-fiddling) and probably I'm the only person affected by it.

I spent time debugging dotty's scalaQ because of the bug where it prefers local class files to its own output. At least scala-cli works right, so maybe I should check that here, too.

**Comment by SethTisue** [comment]
okay, can't say I've hit it myself

**Pull request closed without merging**
