### PR TITLE
SI-8215: Correcting typo and splitting a long sentence in MatchIterator doc

### PR DESCRIPTION
**Pull request by demobox**
Follow-up to 9c0ca62. The typo comes from the fact that I didn't take into account the full rendering of exception names:

image

Also taken the opportunity to split a sentence that seems a bit long into two.

Review by @adriaanm @heathermiller

Sorry that we need this fixup!

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM No worries, I appreciate the attention to detail!

**Comment by demobox** [comment]
@adriaanm Anything else you need from me on this one..?

**Comment by adriaanm** [comment]
Nope, merging!

**Comment by demobox** [comment]
Thanks!

**Pull request merged**
