### PR TITLE
SI-5313 Disable dead local store optimization on ref and array types

### PR DESCRIPTION
**Pull request by JamesIry**
Storing to local variables of reference or array type is indirectly
observable because it potentially allows gc to collect an object. So
this commit gets rid of dead store optimization on reference and array
types.

review @gkossakowski

### CODE REVIEW

**Comment by adriaanm** [comment]
jenkins job pr-scala-testsuite-linux-opt failed: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/2266/consoleText

**Comment by JamesIry** [comment]
Oh the pain. Not eliminating the store means other stuff upstream doesn't get eliminated. In particular closures that have been inlined are still kept around.

**Comment by paulp** [comment]
I guess I'm impressed we had test coverage.

**Comment by paulp** [comment]
Closing pending resolution of this new revelation.

**Pull request closed without merging**
