### PR TITLE
SI-8504 fix NPE in the Java wrapper for a Scala Map.

### PR DESCRIPTION
**Pull request by gourlaysama**
MapWrapper blindly calls .hashCode on keys that can very well be null.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @Ichoran

**Comment by paulp** [comment]
Although the change as given here is the right change in principle, don't forget that https://issues.scala-lang.org/browse/SI-7396 is still in play.

**Comment by gourlaysama** [comment]
Hum, SI-7396 breaks the Scala map already, so the Java wrapper can't do much:

``` scala
scala> val a: String = null
a: String = null
scala> Map(1 -> (a: Predef.Ensuring[_]))
warning: there were 1 feature warning(s); re-run with -feature for details
java.lang.NullPointerException
  at scala.Predef$Ensuring$.hashCode$extension(Predef.scala:252)
  at scala.Predef$Ensuring.hashCode(Predef.scala:252)
  [...]
```

**Comment by retronym** [comment]
LGTM

**Pull request merged**
