### PR TITLE
Fixes and features for javap (fixing SI-6894)

### PR DESCRIPTION
**Pull request by som-snytt**
Output filtering is refactored for javap6.

That means javap6 also supports -raw.

Handling of # is: Foo#foo filter on foo,
Foo# filter on apply, -fun Foo#foo for anonfuns of foo,
-fun Foo# anonfuns filtering on apply.

One is loath to add command options, so it's not possible
to ask for "only apply methods in anonfuns pertaining to
a method."  Hypothetical syntax to say "show me the
apply only": -fun Foo#foo(), for future reference.

This is supplemental to #1849 which I ought to have closed while I was push -f'ing more stuff late nights.

An additional use case is to ask for the App init body:
scala> :javap -app grouped.Test#
  public final java.lang.Object apply();

Review by @paulp

### CODE REVIEW

**Comment by som-snytt** [comment]
Grr, or whatever sound an angry kitteh makes.

**Comment by som-snytt** [comment]
PLS REBUILD ALL

**Comment by som-snytt** [comment]
PLS REBUILD ALL

**Comment by som-snytt** [comment]
@paulp I put the test restore in a separate commit out of abundance of caution.  The squashed refactor for javap6 was actually small (you can tell because it worked right away); I was under the mistaken impression that the javap6 tool interface was somehow incorrigible.  I started looking at the backport to 2.10; I handled the lack of your November naming changes with a couple of extension methods and promptly crashed the compiler.  Let me know if the right thing is to backport your changes first (because why wouldn't we). (But it's horrible to think of tool support depending on a diverging code base. When does 2.11 come out? etc)

**Comment by paulp** [comment]
This looks sane enough to me, but my standards for sanity are nothing you want to emulate.

**Comment by som-snytt** [comment]
Actually, it's really dirty, but soon I'll be able to do most of the dirty work with scala.reflect, right?  And I'll volunteer now to do the update, even if I have to miss Saturday night ST:TOS to get it done.  (I did expect you maybe to call me on introducing a maintenance nightmare.  But once merged, I won't have to maintain a scala just to do javap.  Please don't emulate my standards of sanitation, as my spouse is quick to remind anyone who will listen; I'm a dog person, as you know, but she is not.)

**Comment by paulp** [comment]
Hey, why does the repl think nothing is longer than about four lines?

```
scala> :javap -v scala.Predef#genericArrayOps
public static scala.collection.mutable.ArrayOps genericArrayOps(java.lang.Object);
  Code:
   Stack=2, Locals=1, Args_size=1
   0:   getstatic   #16; //Field scala/Predef$.MODULE$:Lscala/Predef$;
   3:   aload_0
   4:   invokevirtual   #255; //Method scala/Predef$.genericArrayOps:(Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
   7:   areturn
  Signature: length = 0x2
   02 5E 

scala>
```

That's a big method in real life.

**Comment by som-snytt** [comment]
This real life?  `:javap scala.Predef$#genericArrayOps`

I switched the "precedence" of symbol term and type, because otherwise there's no way to specify the companion class in the presence of a companion module, er, object.

So the burden is on asking for the object when you have to.

Maybe it can learn to ignore static forwarders, though.

BTW, I just went to cut/paste your javap command, but forgot to ctl-c (since I'm used to X), and what I pasted was the Paul Simon page on wikipedia; my French connection didn't know the song, so I forwarded him the link.

**Comment by som-snytt** [comment]
"Prefer companion class to object, otherwise it's not showable;
for object, require dollar when both exist."
https://github.com/som-snytt/scala/commit/942f078720cb05c9238913bae8e62900558c2c45#L0L956

**Comment by paulp** [comment]
"So the burden is on asking for the object when you have to." That would maybe be reasonable were there no forwarders; as it stands I will frequently be routed to methods in which I have no interest. It would be great if it could be taught about forwarders. They're pretty easy to spot I think. I can handle the '$', but it would be nice if the masses didn't have to. And I'm sure they're coming now, what with all these new javap features.

**Comment by som-snytt** [comment]
Ideation: after the improvement, backticks `Predef#genericArrayOps` to mean show me the crummy forwarder, don't second-guess me.

**Pull request merged**
