### PR TITLE
Fix for SI-5717, crash in GenASM.

### PR DESCRIPTION
**Pull request by paulp**
If there is a file in the way when generating classfiles,
remove it and proceed. If you had wanted to keep it, you
wouldn't have left it lying around in an output directory
with a name which stands between you and the filesystem.

This is too difficult to write a test for under partest.

### CODE REVIEW

**Comment by retronym** [comment]
Would the approach taken in https://github.com/scala/scala/blob/079296632/test/files/run/t6440.scala help to test this?

**Comment by paulp** [comment]
Yep. Thanks.

**Comment by paulp** [comment]
I'll reopen this with less murderous intent.

**Comment by som-snytt** [comment]
Coincidentally, I noticed you removed Path.isValid, "// Validation: this verifies that the type of this object and the contents of the filesystem are in agreement.  All objects are valid except File objects whose path points to a directory and Directory objects whose path points to a file."  We could have emitted "Path not valid!" for this case.  Or maybe, "Filesystem not in agreement."

**Pull request closed without merging**
