### PR TITLE
[backport] SI-8787 Backport Regex doc

### PR DESCRIPTION
**Pull request by som-snytt**
Backport the doc with two material changes:
1. need to use Groups to extract from Match,
   so say that in lieu of the 2.11 advice that
   the Regex instance can be used without
   recomputing the match;
2. and relatedly, in 2.10 there is no secondary
   constructor, so the doc for group names is
   moved back up to the class doc.

Original doc update on PR #3923 was:

0e26910

f98c53c

Review by @lrytz

### CODE REVIEW

**Comment by som-snytt** [comment]
Reverted a local var -> val change from 2.11, to appease mima.

**Comment by som-snytt** [comment]
Mima is right again.  `Match.matcher` was privatized in 2.11, perhaps to avoid side-effects like `matcher.reset` by nosy users.  Will revert the edit.

**Comment by som-snytt** [comment]
As we know from that tv ad, mima is Chinese for password, so I hope I guessed right this time.

This was a little less fun than I'd imagined.

**Comment by som-snytt** [comment]
This morning I was reflecting on things which are totally not worth it without automation.  I was thinking of mima whitelists.  But for the rest of the day, I saw everything through the frame of busywork and automation.

**Comment by lrytz** [comment]
I think we label backports as `[backport]` now, instead of `[nomaster]`. Also, could you link to the original commits and summarize the diff between this PR and the original change, if any?

**Comment by som-snytt** [comment]
Repushed with amended commit message.

The original enumerated the differences, but now it enumerates with numbers.

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@8876227

**Comment by som-snytt** [comment]
PLS REBUILD/pr-scala@8876227

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
