### PR TITLE
Rename Numeric.Ops and Ordering.Ops to OrderingOps and NumericOps

### PR DESCRIPTION
**Pull request by allanrenucci**
Class shadowing is forbidden in Dotty

### CODE REVIEW

**Comment by allanrenucci** [comment]
I need some guidance to fix the failing test

**Comment by NthPortal** [comment]
This particular shadowing issue has bitten me in the past, so thank you for fixing it!

**Comment by NthPortal** [comment]
If you look at the top of `SerializationStabilityTest.scala`, you will find the following comment

```
// This test is self-modifying when run as follows:
//
//    junit/testOnly scala.SerializationStabilityTest -- -Doverwrite.source=test/junit/scala/SerializationStabilityTest.scala
//
// Use this to re-establish a baseline for serialization compatibility.
```

Running the specified sbt command will update `SerializationStabilityTest` (to take into account the structural changes to classes/traits in your PR which cause serialization to change). After running the sbt command, `SerializationStabilityTest` will pass.

Modifying `SerializationStabilityTest` is okay before a major release (e.g. before 2.13.0), because there is no prior version with which serialization compatibility is required. However, modifying `SerializationStabilityTest` is not okay before a minor release (e.g. after 2.13.0 but before 2.13.1), because the new minor release must have its serialization be compatible with the previous minor version.

**Review by NthPortal — COMMENTED** [review]
LGTM, but I will defer to someone more knowledgeable as to whether or not this will subtly break something else

**Comment by dwijnand** [comment]
This is https://github.com/scala/scala/pull/4832, but targeting 2.13.x rather than 2.12.x, where @adriaanm says:

> Given the binary compatibility concerns, we'll probably have to settle for deprecating in 2.12 and reworking in 2.13.

Any subtle breakages can be forward fixed after this lands.

So let's land it.

**Review by dwijnand — APPROVED** [review]

**Pull request merged**
