### PR TITLE
Faster PR validation

### PR DESCRIPTION
**Pull request by adriaanm**
This reworks the build so we can speed up PR validation, publishing Scala to maven once, and consuming that downstream in the other jobs (by maven/sbt/dbuild)

We're standardizing on putting all our java properties in versions.properties and passing that around between the jenkins pr validation jobs, having them consumed by the scripts and dbuild. This way we can keep all module versions in synch and don't need to change infrastructure (much) when new properties are needed.

### CODE REVIEW

**Comment by adriaanm** [comment]
The new-style validator is running here: https://scala-webapps.epfl.ch/jenkins/job/stage-pr-scala/1/console  (for the first time)

**Comment by adriaanm** [comment]
Looks like the second time'll be the charm:  https://scala-webapps.epfl.ch/jenkins/job/stage-pr-scala/2

**Comment by adriaanm** [comment]
Review by @JamesIry

**Comment by adriaanm** [comment]
The first 2 commits were submitted earlier in #3087

**Comment by adriaanm** [comment]
(Sorry to tack a somewhat unrelated commit on to this one -- trying to avoid conflicts in versions.properties.)

**Comment by JamesIry** [comment]
There ya go, paying the price for unrelated commits.

**Comment by JamesIry** [comment]
LGTM once the incompatibilities are sorted

**Comment by adriaanm** [comment]
Dropped last two commits. I'll figure out the version issue entirely separately.

**Pull request merged**
