### PR TITLE
REPL versioned prompt includes -Xsource

### PR DESCRIPTION
**Pull request by som-snytt**
For extreme perspicacity, add `-Xsource` value (if set) to the REPL versioned prompt (as enabled by `-Dscala.repl.info=true`).

```
scala 2.13.13-20231217-200123-a7b9a34 -Xsource:3.0.0>
```

### CODE REVIEW

**Comment by SethTisue** [comment]
I like it, but I think there should be a space before the addition, so that it's clearly not part of the version number itself.

**Comment by som-snytt** [comment]
`scala 2.13.13-20230909-051255-0d0d219 <3> 42` maybe, because `<3`.

**Comment by SethTisue** [comment]
Ice cream? Yes please! <3

**Comment by som-snytt** [comment]
Since Seth is the only person who might use this feature, I am glad to accommodate him.

I just noticed that `3>` is a bikini.

**Comment by som-snytt** [comment]
needs to follow whatever the `3-X` convention is.

**Comment by som-snytt** [comment]
I guess you couldn't be bothered with a test? so we could verify what it looks like?

The OP was edited to show it.

```
➜  scala git:(tweak/info-prompt) skala
Welcome to Scala 2.13.13-20231221-165835-1829ecf (OpenJDK 64-Bit Server VM, Java 21).
Type in expressions for evaluation. Or try :help.

scala> 42
val res0: Int = 42

scala>
:quit
➜  scala git:(tweak/info-prompt) skala -Xsource:3.0.1
Welcome to Scala 2.13.13-20231221-165835-1829ecf -Xsource:3.0.1 (OpenJDK 64-Bit Server VM, Java 21).
Type in expressions for evaluation. Or try :help.

scala> 42
val res0: Int = 42

scala>
:quit
➜  scala git:(tweak/info-prompt) skala -Xsource:3.0.1 -Dscala.repl.info
[info] started at Tue Jan 16 13:40:42 PST 2024
Welcome to Scala 2.13.13-20231221-165835-1829ecf -Xsource:3.0.1 (OpenJDK 64-Bit Server VM, Java 21).
Type in expressions for evaluation. Or try :help.

scala 2.13.13-20231221-165835-1829ecf -Xsource:3.0.1> 42
val res0: Int = 42

scala 2.13.13-20231221-165835-1829ecf -Xsource:3.0.1>
```
The "extended version" shows up in the REPL welcome message, and additionally in the prompt under `-Dscala.repl.info`.

**Comment by SethTisue** [comment]
@som-snytt is there a reason to show `-Xsource:3.0.0` instead of `-Xsource:3`? It seems peculiar.

**Comment by som-snytt** [comment]
@SethTisue I'm glad you understand what I meant by "extreme perspicacity". Does this work with `3-cross`?

**Comment by SethTisue** [comment]
> Does this work with 3-cross?

Yes, it shows `-Xsource:3-cross` as expected.

**Pull request merged**
