### PR TITLE
[ci: last-only] merge 2.12.x onto 2.13.x (Feb 17, 2017)

### PR DESCRIPTION
**Pull request by SethTisue**
this was a nice clean merge, only trivial merge conflicts to resolve

```
*   db8520e5c4 (origin/HEAD, origin/2.12.x) Merge pull request #5710 from SethTisue/sd-303
|\
| * 2b3d017d5f fix recent regression: macro paradise + Java sources = MatchError
* |   419a639404 Merge pull request #5701 from SethTisue/merge-2.11.x-to-2.12.x-20170214
|\ \
| |/
|/|
| *   71a8a4429f Merge branch '2.12.x' into merge-2.11.x-to-2.12.x-20170214
| |\
| |/
|/|
* |   c8b80053bd Merge pull request #5693 from markusjura/lineStream-warnings
|\ \
| * | 55d542732a Changing deprecation warning to lineStream
* | |   1758e0071e Merge pull request #5697 from som-snytt/issue/10164
|\ \ \
| * | | 6c71379344 SI-10164 BitSet.tail zigs where it zagged
* | | |   d5aad25db7 Merge pull request #5712 from SethTisue/mima-fixup
|\ \ \ \
| * | | | 78eee86fc0 update MiMa whitelist for infix annotation
|/ / / /
* | | |   c8e550420a Merge pull request #5684 from SethTisue/partest-sbt-only-plz
|\ \ \ \
| * | | | f207ffc429 fix annoying extra space in tab completion of sbt `partest` command
| * | | | 0bf343e000 (SethTisue/partest-sbt-only-plz) run partest from sbt always, command line never
* | | | |   98a7d4ce02 Merge pull request #5694 from janekdb/topic/2.12.x-scaladoc-spelling-corrections-2
|\ \ \ \ \
| * | | | | 1eb331b419 Fix typos in compiler and reflect
* | | | | |   955b779b63 Merge pull request #5648 from som-snytt/issue/10148
|\ \ \ \ \ \
| * | | | | | a262aaba15 SI-10148 Follow Java for float literals
* | | | | | |   7b4567627c Merge pull request #5688 from Philippus/fix-scaladoc-base-references
|\ \ \ \ \ \ \
| * | | | | | | c895b36849 fixed broken references after move from 'model' to 'base'
| | |_|_|_|/ /
| |/| | | | |
* | | | | | |   111286e0f6 Merge pull request #5674 from Philippus/issue/9519
|\ \ \ \ \ \ \
| * | | | | | | 47bb6be1b6 SI-9519 removed the usecase section of the ++-method
| | |_|_|/ / /
| |/| | | | |
* | | | | | |   813324a8e7 Merge pull request #5687 from retronym/ticket/10177
|\ \ \ \ \ \ \
| * | | | | | | d1dbf1864c SI-10177 Override lazy operations to preserve TrieMap's semantics
* | | | | | | |   e2be7c498d Merge pull request #5589 from allisonhb/feature/si-4700
|\ \ \ \ \ \ \ \
| * | | | | | | | fab1db5a38 SI-4700 Make infix notation default for symbolic types.
| * | | | | | | | 8badcadbe5 SI-4700 Show infix types with as few parentheses as needed.
| * | | | | | | | e60768b621 SI-4700 Add `@infix` annotation for type printing
|  / / / / / / /
* | | | | | | |   c10d251353 Merge pull request #5546 from som-snytt/issue/9636
|\ \ \ \ \ \ \ \
| * | | | | | | | f1aa0b3795 SI-9636 More precise error pos on apply inference
* | | | | | | | |   e62e9e2390 Merge pull request #5662 from teldosas/SI-9675
|\ \ \ \ \ \ \ \ \
| * | | | | | | | | 6864d32fbd Add warning about non-sensible equals in anonymous functions
| | |/ / / / / / /
| |/| | | | | | |
* | | | | | | | |   aa9a62739a Merge pull request #5679 from som-snytt/issue/sliding-doc
|\ \ \ \ \ \ \ \ \
| * | | | | | | | | 86889b2707 Nuance doc for sliding
| | |_|/ / / / / /
| |/| | | | | | |
* | | | | | | | |   ee20de4321 Merge pull request #5692 from lrytz/remove-py
|\ \ \ \ \ \ \ \ \
| * | | | | | | | | d2ff9c5b7e Delete some unused scripts
| |/ / / / / / / /
* | | | | | | | |   9e59dc6bf0 Merge pull request #5587 from lrytz/t10072
|\ \ \ \ \ \ \ \ \
| * | | | | | | | | 0f3f635d30 SI-10072 cast Function nodes to environment in specialization
* | | | | | | | | |   b990e51051 Merge pull request #5542 from retronym/ticket/10066
|\ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | 944db65d63 SI-10066 Fix crash in erroneous code with implicits, dynamic
|  / / / / / / / / /
* | | | | | | | | |   05d5338ff4 Merge pull request #5696 from SethTisue/bootstrap-no-parsers-no-swing
|\ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | 1371a216d8 during bootstrap, don't build scala-parser-combinators or -swing
| | |/ / / / / / / /
| |/| | | | | | | |
| | | | | | | | | *   04c45e15f1 Merge commit '0965028809' into merge-2.11.x-to-2.12.x-20170214
| | | | | | | | | |\
| | | | | | | | | | *   0965028809 Merge pull request #5695 from SethTisue/fix-indexedseqtest-under-ant
| | | | | | | | | | |\
| | | | | | | | | | | * e08bccb3d0 fix IndexedSeqTest to work in both Ant and sbt
| | | | | | | | | | |/
| | | | | | | | | | *   214a158f67 Merge pull request #5664 from adriaanm/rework-coll-perf
| | | | | | | | | | |\
| | | | | | | | | | | * f24c2603d0 Handle WrappedArray the same way as ArrayOps for binary compatibility
| | | | | | | | | | | * 7e89663931 Add benchmark for List.mapConserve
| | | | | | | | | | | * eb5c51383a Optimised implementation of List.filter/filterNot
| | | | | | | | | | | * d540bf01fe Optimize slice and take in ArrayOps, WrappedArray
| | | | | | | | | | | * 4f9faff937 Test IndexedSeq, including ArrayOps, WrappedArray.
| | | | | | | | | | | * e803cf64b2 Avoid creating ListBuffer in List.mapConserve
| | | | | | | | | | |/
| | | | | | | | | | *   6644017dad Merge pull request #5631 from adriaanm/ticket/9013
| | | | | | | | | | |\
| | | | | | | | | | | * a75d3fdda2 SI-1459 two bridges for impl of java generic vararg method
| | | | | | | | | | | * dc7ff5dd84 SI-9013 SI-1459 Tests for inherited @varargs annotations
| | | | | | | | | | |/
| | | | | | | | | | *   90a764bcba Merge pull request #5645 from sjrd/avoid-array-oob-in-rbtree-iterator-from
| | | | | | | | | | |\
| | | | | | | | | | | * 648eba62b0 Fix the size of the stack used by RedBlackTree.iteratorFrom.
| | | | | | | | | | |/
| | | | | | | | | * |   6be69d6d5e Merge commit 'a5d38ea334' into merge-2.11.x-to-2.12.x-20170214
| | | | | | | | | |\ \
| | | | | | | | | | |/
| | | | | | | | | | *   a5d38ea334 Merge pull request #5630 from adriaanm/rebase-5557
| | | | | | | | | | |\
| | | | | | | | | | | * 359b0bce8e [backport] SI-6412 remove flaky test
| | | | | | | | | | | * 8ad55f8515 Simplify creation of varargs forwarder symbol
| | | | | | | | | | | * c603449b3e Don’t run the uncurry info transformer on Java symbols.
| | | | | | | | | | | * 5b972dc10f SI-10071 Separate compilation for varargs methods
| | | | | | | | | | | * de361dfe4f SI-8786 fix generic signature for @varargs forwarder methods
| | | | | | | | | | | * f841dab6c2 support --show-log for partest command
| | | | | | | | | * | |   3e99598973 Merge commit '36967321c7' into merge-2.11.x-to-2.12.x-20170214
| | | | | | | | | |\ \ \
| | | | | | | | | | |/ /
| | | | | | | | | | * |   36967321c7 Merge pull request #5632 from adriaanm/ticket/9114
| | | | | | | | | | |\ \
| | | | | | | | | | | * | 9165886936 SI-9114 Fix crasher in pattern matcher with type aliases
| | | | | | | | | | | |/
| | | | | | | | | | * |   fac487e397 Merge pull request #5633 from adriaanm/ticket/9331
| | | | | | | | | | |\ \
| | | | | | | | | | | * | 8138e24bbd SI-9331 Fix canEqual for case classes with HK type params
| | | | | | | | | | | |/
| | | | | | | | | * | |   2324405ca0 Merge commit '32a7461037' into merge-2.11.x-to-2.12.x-20170214
| | | | | | | | | |\ \ \
| | | | | | | | | | |/ /
| | | | | | | | | | * |   32a7461037 Merge pull request #5635 from adriaanm/jline-2.14.3
| | | | | | | | | | |\ \
| | | | | | | | | | | |/
| | | | | | | | | | |/|
| | | | | | | | | | | * f070a76780 SI-9762 Remove workaround after upstream fix in jline
| | | | | | | | | | | * 2113a7c88e SI-9762 Update to JLine 2.14.3
| | | | | | | | | | |/
| | | | | | | | | | *   4f5c30e10a Merge pull request #5615 from monkey-mas/modify-ArrayBuilder-reusability-bug-2016-12-24
| | | | | | | | | | |\
| | | | | | | | | | | * 23040fe8da [Backport] Modify ArrayBuilder and WrappedArrayBuilder to be reusable
| | | | | | | | | | * |   1b6b19b701 Merge pull request #5626 from adriaanm/rebase-5566
| | | | | | | | | | |\ \
| | | | | | | | | | | * | 1e82a92f01 Simplify HashTable.index further
| | | | | | | | | | | * | 02c30a174d Changed HashMap.getOrElseUpdate to only calculate the index once
| | | | | | | | | | | * | 276db03285 Changed hashing bit rotation to use Integer.rotateRight
| | | | | | | | | | | * | 26ad9cc73c Changed modulo to bitwise AND in hash calculation
| | | | | | | | | | | * | 5fd422b6aa Optimized HashTable.index
| | | | | | | | | | | * | f31745ac9b SI-8774 Null link fields in mutable hash maps on removal.
| | | | | | | | | | | * | cb7192c79f Restarr on 2.11.8-18269ea
| | | | | | | | | | |/ /
| | | | | | | | | | * |   18269eabe1 Merge pull request #5612 from adriaanm/patmat_cleanup
| | | | | | | | | | |\ \
| | | | | | | | | | | * | da986839d1 SI-9630 Fix spurious warning related to same-named case accessors [backport]
| | | | | | | | | | | * | 80ce23103c More robust outer test for patmat
| | | | | | | | | * | | |   3fc5059a1e Merge commit '014ebc4' into merge-2.11.x-to-2.12.x-20170214
| | | | | | | | | |\ \ \ \
| | | | | | | | | | | |/ /
| | | | | | | | | | |/| |
| | | | | | | | | | * | | 014ebc4606 Small cleanups to pattern matcher
| | | | | | | | | | | |/
| | | | | | | | | | |/|
| | | | | | | | | * | |   e04e281835 Merge commit '8367bf68c1' into merge-2.11.x-to-2.12.x-20170214
| | | | | | | | | |\ \ \
| |_|_|_|_|_|_|_|/ / / /
|/| | | | | | | | | | /
| | | | | | | | | | |/
| | | | | | | | | |/|
| | | | | | | | | * |   8367bf68c1 Merge pull request #5624 from Jasper-M/patch-1
| | | | | | | | | |\ \
| | | | | | | | | | |/
| | | | | | | | | |/|
| | | | | | | | | | * f618939a3b Fix documentation of immutable.Queue
| | | | | | | | | |/
* | | | | | | | | |   4ae37504ca Merge pull request #5654 from retronym/ticket/10154
|\ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | 1d41aef535 SI-10154 Fix implicit search regression for term-owned objects
* | | | | | | | | | |   ed9352a43a Merge pull request #5686 from propensive/make-abstractvar-context-error-more-precise
|\ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | 9d26d60144 Correct the AbstractVar error message
* | | | | | | | | | | |   264836dd0b Merge pull request #5682 from Philippus/issue/9780
|\ \ \ \ \ \ \ \ \ \ \ \
| |_|_|_|_|_|_|_|_|_|/ /
|/| | | | | | | | | | |
| * | | | | | | | | | | 5f1ec53659 SI-9780 use @see annotations
| * | | | | | | | | | | 2a1263fb4c SI-9780 qualify the reference links so they can be found and use @see annotations
| | |_|/ / / / / / / /
| |/| | | | | | | | |
* | | | | | | | | | |   9ea5010480 Merge pull request #5691 from som-snytt/issue/eol
|\ \ \ \ \ \ \ \ \ \ \
| |_|_|_|_|_|_|_|_|/ /
|/| | | | | | | | | |
| * | | | | | | | | | f7c17d2d8f EOL is System.lineSeparator
| | |_|_|_|_|_|/ / /
| |/| | | | | | | |
* | | | | | | | | |   4bbb7afabe Merge pull request #5676 from som-snytt/issue/10173
|\ \ \ \ \ \ \ \ \ \
| |/ / / / / / / / /
|/| | | | | | | | |
| * | | | | | | | | 93dc3badee SI-10173 Crash output shows true line number
| |/ / / / / / / /
* | | | | | | | |   502e3c6296 Merge pull request #5618 from monkey-mas/fix-indent-of-arrayops-2016-12-28
|\ \ \ \ \ \ \ \ \
| |_|/ / / / / / /
|/| | | | | | | |
| * | | | | | | | 5340e88423 Fix indent and comment of ArrayOps.scala
* | | | | | | | |   14521835ff Merge pull request #5680 from SethTisue/deprecation-policy
|\ \ \ \ \ \ \ \ \
| * | | | | | | | | 16e2d15e50 update and improve description of deprecation policy
| | |/ / / / / / /
| |/| | | | | | |
* | | | | | | | |   d6837aef05 Merge pull request #5245 from dwijnand/trailing-commas
|\ \ \ \ \ \ \ \ \
| * | | | | | | | | d55bad8310 SIP-27 Tweak and test wildstar in REPL
| * | | | | | | | | c95e6bb6ae SIP-27 Test varargs, "@", and ": _*"
| * | | | | | | | | 7966edd724 SI-4986 SIP-27 Trailing Comma (multi-line only) support
* | | | | | | | | |   c5c391c7d6 Merge pull request #5522 from ruippeixotog/issue/9886
|\ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | 155d06a500 SI-9507 Make Stream #:: and #::: allow type widening
* | | | | | | | | | | 1aa864372f Bump Swing version for 2.0.0 release (#5678)
* | | | | | | | | | |   5dbcea224d Merge pull request #5669 from dwijnand/partest-glob-path
|\ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | 702deae96d Make partest --grep glob paths, not just filenames
* | | | | | | | | | | |   869416c7cc Merge pull request #5647 from som-snytt/issue/10130
|\ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | 7e07ec715a SI-10130 Ignore extra parse warnings
| | |_|_|_|_|_|_|_|_|/ /
| |/| | | | | | | | | |
* | | | | | | | | | | |   36f83e01c8 Merge pull request #5646 from som-snytt/issue/8685
|\ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | 48a4f06b61 SI-8685 Warn on deprecated case ctor
| |/ / / / / / / / / / /
* | | | | | | | | | | |   02a240aab6 Merge pull request #5642 from janekdb/topic/MB-calculation-correction
|\ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | 2268aabbcb Calculate MB instead of MiB
| |/ / / / / / / / / / /
* | | | | | | | | | | |   8035fb298e Merge pull request #5628 from martijnhoekstra/walkfilterdoc
|\ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | c2356bed16 fix doc for walkfilter and walk
* | | | | | | | | | | | |   8038924acb Merge pull request #5673 from retronym/topic/hashmap-contains
|\ \ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | | 43e9c90535 Fix copy/pasto references to mutable package in benchmark
| * | | | | | | | | | | | | 44f2f0db98 Optimizations in immutable.Map.{get, contains}
| * | | | | | | | | | | | | a58de0e81e Benchmark for immutable.HashMap.{get, contains}
| | |_|_|/ / / / / / / / /
| |/| | | | | | | | | | |
* | | | | | | | | | | | |   5f944cca7e Merge pull request #5625 from gourlaysama/parser-combinators-version-bump
|\ \ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | | c29d7d28fc Update to scala-parser-combinators v1.0.5
* | | | | | | | | | | | | |   40d01f3a44 Merge pull request #5585 from som-snytt/issue/10097
|\ \ \ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | | | b775f4f580 SI-10097 Adapt unless -Xsource:2.13
| * | | | | | | | | | | | | | 32a05ddfef SI-8704 Also warn if effectively multiple implicit
| * | | | | | | | | | | | | | ca7bbcfb17 SI-8704 Error on bad implicit sections
| * | | | | | | | | | | | | | 9df6d16f9b SI-10097 Error if no non-implicit case class param
* | | | | | | | | | | | | | |   40236b0378 Merge pull request #5579 from edmundnoble/queue-concat
|\ \ \ \ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | | | | 409f84d29f Improve Queue.++ when building another Queue
* | | | | | | | | | | | | | | |   575c342039 Merge pull request #5665 from som-snytt/issue/8662-file-complete
|\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \
| |_|_|_|_|_|_|_|_|/ / / / / / /
|/| | | | | | | | | | | | | | |
| * | | | | | | | | | | | | | | c994b59d0d SI-8662 Repl completions
| | |_|_|_|_|_|_|_|_|_|_|/ / /
| |/| | | | | | | | | | | | |
* | | | | | | | | | | | | | |   7311a29a99 Merge pull request #5666 from Philippus/issue/10030
|\ \ \ \ \ \ \ \ \ \ \ \ \ \ \
| * | | | | | | | | | | | | | | dc951d996c SI-10030 - added quotes in case the path contains a space and an 8.3-compliant path is not available
| |/ / / / / / / / / / / / / /
* | | | | | | | | | | | | | |   e7ed71b8d5 Merge pull request #5667 from som-snytt/issue/maxerrs
|\ \ \ \ \ \ \ \ \ \ \ \ \ \ \
| |_|_|_|_|/ / / / / / / / / /
|/| | | | | | | | | | | | | |
| * | | | | | | | | | | | | | 633e6effa3 SI-9729 -Xmaxerrs to limit messages
| |/ / / / / / / / / / / / /
* | | | | | | | | | | | | |   fff1732044 Merge pull request #5668 from dwijnand/failblog
|\ \ \ \ \ \ \ \ \ \ \ \ \ \
| |_|_|_|_|_|_|/ / / / / / /
|/| | | | | | | | | | | | |
| * | | | | | | | | | | | | e69524c559 Finish resolving conflicts from rebasing commits within #5661
|/ / / / / / / / / / / / /
* | | | | | | | | | | | |   6d4782774b Merge pull request #5661 from SethTisue/direct-scalacheck
|\ \ \ \ \ \ \ \ \ \ \ \ \
| |/ / / / / / / / / / / /
|/| | | | | | | | | | | |
| * | | | | | | | | | | | 35edd8f9bc Update IntelliJ template configuration
| * | | | | | | | | | | | bba5f5ad3c Move scalacheck test suite sources to folders corresponding packaging
| * | | | | | | | | | | | 33f6c07e87 Move Scaladoc's Partest base classes to partest-extras
| * | | | | | | | | | | | 4386b948a0 run ScalaCheck tests directly, not through partest
| * | | | | | | | | | | | 27c10db549 adjust to partest 1.1.0's new mixed Java/Scala compilation
|/ / / / / / / / / / / /
* | | | | | | | | | | |   b9d4089d19 Merge pull request #5651 from rorygraves/2.12.x_symbol_marking
|\ \ \ \ \ \ \ \ \ \ \ \
| |_|_|_|_|_|_|_|/ / / /
|/| | | | | | | | | | |
| * | | | | | | | | | | 9f2aa0d112 Improve performance of Symbol marking
| | |_|_|_|/ / / / / /
| |/| | | | | | | | |
* | | | | | | | | | |   82b2470ff6 Merge pull request #5637 from ichaki5748/Sl-10113
|\ \ \ \ \ \ \ \ \ \ \
| |/ / / / / / / / / /
|/| | | | | | | | | |
| * | | | | | | | | | dfd540a700 SI-10113 mutable.TreeMap.range does not work added missing overrides for TreeMapView
| | |_|_|/ / / / / /
| |/| | | | | | | |
* | | | | | | | | |   827d69d48e Merge pull request #5636 from adriaanm/jline-2.14.3-2.12.x
|\ \ \ \ \ \ \ \ \ \
| |/ / / / / / / / /
|/| | | | | | | | |
| * | | | | | | | | cd1006c75e Revert "Repl prints '\n' as newline, not "^J""
| * | | | | | | | | 55f596b142 Upgrade to jline2 2.14.3
|/ / / / / / / / /
* | | | | | | | |   c94a9b2919 Merge pull request #5621 from som-snytt/issue/9936-more
|\ \ \ \ \ \ \ \ \
| |_|_|_|_|/ / / /
|/| | | | | | | |
| * | | | | | | | a75e4a7faf SI-9936 LinearSeqOptimized.indexWhere
|/ / / / / / / /
* | | | | | | |   bf9b00ebed Merge pull request #5607 from adriaanm/rebase-5551
|\ \ \ \ \ \ \ \
| * | | | | | | | ce80124ca9 Override equals and hashCode for WrappedArray
* | | | | | | | |   c4dcc9948a Merge pull request #5583 from lrytz/t10093
|\ \ \ \ \ \ \ \ \
| * | | | | | | | | 34dad77513 SI-10093 don't move member traits to constructor body in constructors
| | |_|_|_|_|/ / /
| |/| | | | | | |
* | | | | | | | |   a3135bf857 Merge pull request #5610 from dwijnand/sbt
|\ \ \ \ \ \ \ \ \
| |_|_|_|_|_|_|/ /
|/| | | | | | | |
| * | | | | | | | f678a57df8 Fix how "sbt" is written
|/ / / / / / / /
* | | | | | | |   246653f024 Merge pull request #5608 from retronym/merge/2.11.x-to-2.12.x-20161220
|\ \ \ \ \ \ \ \
| * \ \ \ \ \ \ \   079e8dc617 Merge remote-tracking branch 'origin/2.11.x' into merge/2.11.x-to-2.12.x-20161220
| |\ \ \ \ \ \ \ \
| | |_|/ / / / / /
| |/| | | | | | /
| | | |_|_|_|_|/
| | |/| | | | |
| | * | | | | |   23548c4301 Merge pull request #5605 from szeiger/wip/fix-07-links
| | |\ \ \ \ \ \
| | | * | | | | | bde9bf6eb2 Fix spec links to `07-implicits.html`
| | |  / / / / /
| | * | | | | |   6cf2c046ef Merge pull request #5604 from sjrd/scalajs-friendly-assertthrows
| | |\ \ \ \ \ \
| | | * | | | | | 97e8ee7f43 Use ClassTag instead of Manifest in AssertUtil.assertThrows.
| | |/ / / / / /
| | * | | | | |   bf54f1ff8e Merge pull request #5487 from lrytz/java-constants
| | |\ \ \ \ \ \
| | | * | | | | | 9b27a08f78 neg test for parsing constants in Java sources
| | | * | | | | | 74c613bd45 Support implicit converstions from java literals
| | | * | | | | | 81d2c6185e SI-3236 constant types for literal final static java fields
| | |  / / / / /
| | * | | | | |   e231c09c41 Merge pull request #5454 from som-snytt/issue/9834-2.11
| | |\ \ \ \ \ \
| | | * | | | | | 76598e8bf8 SI-9834 Show expansion of update on error
| | | * | | | | | 55c6ad4f8a SI-9834 Improve error on failed op=
| | |  / / / / /
| | * | | | | |   103cb78da8 Merge pull request #5590 from 2m/mima-0.1.13-scala-2.11
| | |\ \ \ \ \ \
| | | * | | | | | 695049d72f Upgrade MiMa to 0.1.13
| | | | |/ / / /
| | | |/| | | |
| | * | | | | |   587a28e5d0 Merge pull request #5574 from ptrcarta/patch-1
| | |\ \ \ \ \ \
| | | * | | | | | a95b468814 fix eBNF error by removing wrong closing brace
| | | |/ / / / /
| | * | | | | | 738ac6d7d3 SI-10086 NumericRange.min|max with custom Integral (#5575)
| | |/ / / / /
* | | | | | |   0924e73180 Merge pull request #5598 from retronym/topic/jdk9-bootcp-repl-javap
|\ \ \ \ \ \ \
| |/ / / / / /
|/| | | | | |
| * | | | | | a346b77932 Support extra module references in the REPL
| | |_|_|_|/
| |/| | | |
* | | | | |   56fb917275 Merge pull request #5539 from som-snytt/issue/10068
|\ \ \ \ \ \
| * | | | | | 582c8a2fdd SI-10068 Only permit elidable methods
| | |_|_|/ /
| |/| | | |
* | | | | |   bba42ff5d4 Merge pull request #5541 from retronym/ticket/10067
|\ \ \ \ \ \
| |_|_|_|_|/
|/| | | | |
| * | | | | 14451a9c91 SI-10067 Don't speculatively emit outer tests for inner Java classes
| * | | | | d2d33ddf8c SI-10067 Java defined inner classes don't have outer accessors
|  / / / /
* | | | |   a9802c317a Merge pull request #5588 from retronym/ticket/10098
|\ \ \ \ \
| |/ / / /
|/| | | |
| * | | | 60ea98e412 S-10098 Fix regression in Unix runner script with JAVA_HOME unset
* | | | |   b91b415b4f Merge pull request #5602 from retronym/ticket/SD-290
|\ \ \ \ \
| * | | | | 64a0ec4709 Modules w. serializable type alias "companions" are not serializable
|/ / / / /
* | | | |   4c0a9f13e4 Merge pull request #5558 from larsrh/topic/deprecated-y-flags
|\ \ \ \ \
| * | | | | ae9a194b3a delete dead code
| * | | | | c7b818fdd7 remove deprecated compiler flag "-Yinfer-by-name"
| * | | | | 0153522910 remove deprecated compiler flag "-Yeta-expand-keeps-star"
* | | | | |   7ae0aec7a2 Merge pull request #5593 from ashawley/spec-jekyll-3
|\ \ \ \ \ \
| * | | | | | 1f4cd50fa4 Update spec build to Jekyll 3.3
| | |_|/ / /
| |/| | | |
* | | | | |   0a3e2b62bd Merge pull request #5531 from tabdulradi/SI-10060
|\ \ \ \ \ \
| * | | | | | 5370f271df fixup! SI-10060 Fixes NumericRange.max bug on empty ranges
| * | | | | | 99b971e78c SI-10060 Fixes NumericRange.max bug on empty ranges
|  / / / / /
* | | | | |   8b872daacb Merge pull request #5543 from retronym/ticket/10069
|\ \ \ \ \ \
| * | | | | | 880aec04e8 SI-10069 Fix code gen errors with array updates, Nothing
|  / / / / /
* | | | | |   2d90142eca Merge pull request #5527 from som-snytt/fix/use-modern-replace
|\ \ \ \ \ \
| * | | | | | f0d4e1efd9 String.replaceAllLiterally is String.replace
|  / / / / /
* | | | | |   d34e44e994 Merge pull request #5550 from retronym/ticket/3772
|\ \ \ \ \ \
| * | | | | | 9502a061fa Refactor companion lookup methods after code review
| * | | | | | 37037fe706 SI-3772 Fix detection of term-owned companions
|  / / / / /
* | | | | |   623f0a72ba Merge pull request #5569 from paplorinc/rotr
|\ \ \ \ \ \
| * | | | | | bc91223012 Changed hashing bit rotation to use Integer.rotateRight
|  / / / / /
* | | | | |   84484df5b9 Merge pull request #5594 from retronym/topic/JEP-193
|\ \ \ \ \ \
| |/ / / / /
|/| | | | |
| * | | | | 1ff714b837 Compiler support for JEP-193 VarHandle polymorphic signatures
|/ / / / /
* | | | |   3de1c0c56e Merge pull request #5545 from paplorinc/vectorCleanup
|\ \ \ \ \
| * | | | | 74db1d358a Applied further cleanup to Vector
| * | | | | e06d383727 Changed >> to >>> in Vector to unify style
| * | | | | 5ae77a7ea9 Applied suggestions to Vector cleanup
| * | | | | 95a29f2ab3 Deleted leftover code-comments from Vector
| * | | | | fd338a7526 Deleted leftover debug method from Vector
| * | | | | 6af55b0271 Unified masks in Vector
| * | | | | f4ae496f92 Removed redundant casts from Vector
| | |/ / /
| |/| | |
* | | | |   c71e41e918 Merge pull request #5584 from xuwei-k/patch-2
|\ \ \ \ \
| |/ / / /
|/| | | |
| * | | | ad2fda140b add project/build.properties for benchmark project
|/ / / /
* | | |   5ed47bca1f (2.12.x) Merge pull request #5580 from SethTisue/starr-is-now-2.12.1
|\ \ \ \
| * | | | c488a680a4 bump version (now 2.12.2) + and STARR (now 2.12.1)
|/ / / /
* | | |   2787b47396 (tag: v2.12.1) Merge pull request #5570 from adriaanm/t10075
|\ \ \ \
| |_|_|/
|/| | |
| * | | 7bf8ffa155 Drop annotations from trait static super accessor
| * | | 7a57c6eec6 SI-10075 annotations go to lazy val's underlying field
|  / /
* | |   ee1c02b374 Merge pull request #5573 from adriaanm/revert-part-5376
|\ \ \
| * | | 891ecbfade Revert existential infer part of #5376
* | | |   ccfa36071f Merge pull request #5385 from retronym/topic/JEP-220
|\ \ \ \
| |/ / /
|/| | |
| * | | 159480f250 Support Java 9 modular runtime images
| * | | bfa7ade0db Adapt to the removal of sun.boot.class.path
| * | | 5b269e9259 SI-9833 Fix -nobootcp in the Unix scala script
|/ / /
* | |   aacef6d66e Merge pull request #5572 from SethTisue/merge-2.11.x-to-2.12.x-dec-1
|\ \ \
| |/ /
|/| |
| * |   212c525fc1 (SethTisue/merge-2.11.x-to-2.12.x-dec-1) Merge remote-tracking branch 'origin/2.11.x' into merge-2.11.x-to-2.12.x-dec-1
| |\ \
|/ / /
| | _
| *   264cc5f20c Merge pull request #5571 from SethTisue/mima-upgrade
| |\
| | * 6e35e2de50 upgrade MiMa to 0.1.12
| |/
| * 76183a21eb Update to mathjax 2.6-latest [2.12.x backport]
*   c2eb299b0e Merge pull request #5284 from milessabin/topic/si-7046
|\
| * dde13b56f4 Partial fix for SI-7046
* 038c15e405 Merge pull request #5376 from milessabin/topic/clean-experimental
* 1870f1af7e Typevar experimentals now default; t5729 pos -> neg.
* 6ec56abd80 Pattern matching virtualization now guarded by -Yvirtpatmat.
```

### CODE REVIEW

**Comment by SethTisue** [comment]
apparently Scabot is dumbfounded by this spectacle.

**Comment by SethTisue** [comment]
manually triggered validate-main run: https://scala-ci.typesafe.com/job/scala-2.12.x-validate-main/4877/

**Comment by SethTisue** [comment]
green. who needs Scabot anyway?

**Comment by som-snytt** [comment]
Are scabots those wooden shoes they wear in Belgium? Do we already speak of `scabotage`?

**Comment by adriaanm** [comment]
scabot gets a little overwhelmed by >100 commits because paging isn't implemented. Looks like its  dottyland doppelganger does deal. Would be a nice botport.

**Pull request merged**
