### PR TITLE
Don't return unimportables from importedSymbol.

### PR DESCRIPTION
**Pull request by retronym**
Hardening against the symptom of SI-6745, which yielded:

```
wat.scala:4: error: too many arguments for constructor Predef: ()object Predef
  def this() = this(0)
           ^
```

The fix for the underlying problem in that bug
has been targetted at branch 2.10.x.

Review by @paulp.

I was tempted to add a `devWarning` for this one, but before I did that I would need to check if we hit that code path under non-warnable circumstances.

### CODE REVIEW

**Comment by paulp** [comment]
I think you will be safe adding a devWarning, and that it is a good idea. The only interesting question wrt this patch is the placement of this check - where it is now, or inside the while loop, which would allow for finding an importable symbol somewhere beyond the faux-importable one.

**Comment by paulp** [comment]
This lgtm, although I suggest a little commentary to both effects (that a warning is most likely merited for someone, and that the placement of the test may bear reconsideration.)

**Comment by retronym** [comment]
Commentary expanded.

**Comment by paulp** [comment]
lgtm.

**Pull request merged**
