### PR TITLE
SI-8022 Backwards compatibility for Regex#unapplySeq

### PR DESCRIPTION
**Pull request by retronym**
The change in ce1bbfe / SI-6406 introduced overloades of
`unapplySeq` with wider static and dynmaic result types
than the now-deprecated alternative that accepted `Any`.

This is subtly source incompatible and the change was noticed
in Specs2.

This commit uses `List` as the static and runtime type for
the new overloads.

For consistency, the same is done for the new method added
in SI-7737 / 93e9623.

Review by @som-snytt

### CODE REVIEW

**Comment by retronym** [comment]
I wonder whether there is latitude for a `Lint` warning when using `::` to match on `Seq`, as in : https://github.com/retronym/scala/compare/topic/warn-match-seq-list

**Comment by som-snytt** [comment]
Bummer.  IIRC, this was a conscious change, though not a point of emphasis. Specs2 is a rather demanding codebase.

**Comment by retronym** [comment]
We're tantalizingly [close](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x/39/consoleFull) to having nightly builds that will catch this.

Overloading and source compatibility is a bit of a minefield.

**Comment by som-snytt** [comment]
LGTM.  I'll study why 2.11 is not carte blanche on compatibility.

**Comment by adriaanm** [comment]
Because we want people to upgrade. Recompiling is about all you can ask for. (And compiling with deprecations as fatal warnings.)

**Comment by retronym** [comment]
This change was so subtle that it could go unnoticed. It took me a number of hours to pin it down in specs. The meta problem is that pattern matching makes type tests so easy that changing even the runtime types can be a breaking change

**Comment by som-snytt** [comment]
That makes me feel worse about it.  BTW, I looked at the string interp warning; just trying to see how to detect we were a macro expansion; I saw code that looked like there's an attachment, but my test to look for it didn't work the first time; I'll get back to it soon.

**Comment by retronym** [comment]
The string interp thing is pretty specific to specs2, as it does some strange tricks to extract a chunk of source code (sort of undoing the parsers work) and synthesizes a string literal from that. I guess you've seen that, based on your mention of macros. The attachment you mention might not be added until after the warning has been issued. Let me know if you can't find a suitable way to detect this, and I'll help find a way.

**Comment by som-snytt** [comment]
BTW, touching on consistency,

```
scala> Groups unapplySeq ("a(b)c".r findFirstMatchIn "abc").get
res1: Option[Seq[String]] = Some(Vector(b))
```

**Pull request merged**
