### PR TITLE
Merge 2.10.x to master

### PR DESCRIPTION
**Pull request by retronym**
Which was a no-op.

```
% export MB=`git merge-base master origin/2.10.x`

% git log --graph --oneline --decorate $MB...origin/2.10.x
*   daa77d1 (origin/pr/3648, origin/2.10.x) Merge pull request #3602 from xeno-by/topic/backport-vampire-warni
|\
| * db300d4 (xenoby/topic/backport-vampire-warning, origin/pr/3602) [backport] no longer warns on calls to vam
* |   43e06be Merge pull request #3643 from gkossakowski/2.10.5-nightlies
|\ \
| |/
|/|
| * a16e003 (origin/pr/3643) Bump version to 2.10.5 for nightly builds.
|/
*   b66a396 (tag: v2.10.4-RC3, tag: v2.10.4, xenoby/2.10.x, huit/2.10.x) Merge pull request #3491 from retrony
|\
| * 5f4011e (retronym/backport/7902, origin/pr/3491) [backport] SI-7902 Fix spurious kind error due to an unit
|/
*   5720e97 Merge pull request #3430 from som-snytt/issue/8205-backport
|\
| * 8ee165c (origin/pr/3430) SI-8205 [nomaster] backport test pos.lineContent
*   50453ce Merge pull request #3415 from xeno-by/topic/reify210x
|\
| * d167f14 (origin/pr/3415) [nomaster] corrects an error in reify’s documentation
|/
*   6557570 Merge pull request #3359 from huitseeker/issue/VarianceAdaptations
|\
| * 806b6e4 (origin/pr/3359, huit/issue/VarianceAdaptations) Backports library changes related to SI-6566 from
* d9ee69f Merge pull request #3367 from retronym/backport/3363
* ff13742 (retronym/backport/3363, origin/pr/3367) [nomaster] SI-8146 Fix non-deterministic <:< for deeply nes
* cbb88ac [nomaster] Update MiMa and use new wildcard filter

% git merge -s ours daa77d1
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski

**Comment by retronym** [comment]
The build error on daa77d1 is because of an accidental pull request of the `2.10.x` branch to `master` by @mandeep-raj-shrestha.

**Comment by gkossakowski** [comment]
> The build error on daa77d1 is because of an accidental pull request of the 2.10.x branch to master by @mandeep-raj-shrestha.

Do you mean accidental merge? @retronym, you appear to be an author of daa77d1 so I'm wondering why @mandeep-raj-shrestha got pinged. I'm really confused :confused:.

**Comment by retronym** [comment]
He submitted a pr to master based on the 210 branch. The pr validator failed with a merge error when it tried to locally merge.

**Comment by gkossakowski** [comment]
Oh, I missed the fact that it got attached to a commit and commit can be referred to from multiple branches.

**Comment by gkossakowski** [comment]
PLS REBUILD/pr-scala@daa77d1

Let's clear up the situation.

**Comment by adriaanm** [comment]
PLS SYNCH

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
