### PR TITLE
SI-7690 ghost error message fails compile

### PR DESCRIPTION
**Pull request by paulp**
I won't even try to explain the error reporting code, because
it would have no basis in reality. However this change appears
to fix the symptom reported.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Needs reviewer. Seems like @hubertp would be a good candidate. @hubertp, can you have a look?

**Comment by som-snytt** [comment]
Participating.  (I don't know how to tell the octogriffin I'm interested in the thread.)

**Comment by hubertp** [comment]
@paulp to answer your question in the code: it is because of the way `issueCommon` is defined. It will not hit the partial function but it will buffer the error which will get reporter later. Maybe instead we should just have a simple issue which doesn't buffer errors?
Sorry for the late review, I was on holiday.

**Comment by hubertp** [comment]
Unfortunately I do not really see any better approach atm. The easiest would be to ignore saving the buffer in this particular case but then other tests fail.

**Comment by adriaanm** [comment]
I'll look into rebasing.

**Pull request closed without merging**
