### PR TITLE
SI-6240 synchronization for runtime reflection

### PR DESCRIPTION
**Pull request by xeno-by**
Unlike its predecessors, this pull request is for realz! 

I have several stress tests for reflection, and I also have successfully run parallel tests in a couple of projects, whose authors reported crashes when using runtime reflection.

review @paulp @adriaanm @retronym

### CODE REVIEW

**Comment by xeno-by** [comment]
The most controversial part of this PR is e2efc0c. Take a good look at it.

**Comment by xeno-by** [comment]
Reminds me of ScalaDays 2012 and desperate attempts to get reflection working by building a blob of boilerplate. @paulp is probably going to hate me again, for the very same reason.

**Comment by xeno-by** [comment]
PLS REBUILD ALL?

**Comment by xeno-by** [comment]
Jenkins shows no active jobs. Kitty, where are you?

**Comment by adriaanm** [comment]
I'll reboot it asap.

**Comment by paulp** [comment]
"Reminds me of ScalaDays 2012 and desperate attempts to get reflection working by building a blob of boilerplate. @paulp is probably going to hate me again, for the very same reason."

In that case, I don't think I have to even look.  DNLGTM.

**Comment by xeno-by** [comment]
@paulp Maybe you could still take a look and give an improvement advice?

**Comment by paulp** [comment]
@xeno-by soon as I can. I wasn't really not going to look.

**Comment by xeno-by** [comment]
@paulp My sarcasm detector has broken. Sorry :)

**Comment by paulp** [comment]
@xeno-by it's my fault because I like for people not to be entirely sure whether or not I'm kidding.

**Comment by xeno-by** [comment]
BUILDLOG?

**Comment by xeno-by** [comment]
Oh, look - all green! Now it's only a matter of an lgtm or two to get this into 2.10.x :)

**Comment by adriaanm** [comment]
PLS REBUILD/pr-rangepos-per-commit@d1d5ad7e9e6c8a4605e48c3b07e3654ea8f0df9d

**Comment by xeno-by** [comment]
@adriaanm Why was that a rebuild all?

**Comment by JamesIry** [comment]
Moving to 2.10.2-RC1 unless somebody can convince that it's both needed and safe for 2.10.1

**Comment by xeno-by** [comment]
There weren't too much excited reviews, so I guess we should indeed omit this PR from 2.10.1's feature set.

**Comment by retronym** [comment]
The patch looks okay to me. It is a pity not to book some progress on this, as the real world usage of the result would help to flush out residual problems. But I agree the timing of the release makes this all difficult.

**Comment by JamesIry** [comment]
LGTM from @retronym, but some per commit tests are failing. We've branched so when this PR is ready it can be merged to 2.10.x which now targets 2.10.2-RC1.

**Comment by xeno-by** [comment]
@adriaanm There's a bunch of spurious failures. How do I best deal with them?

**Comment by adriaanm** [comment]
I'm not sure. Are you sure they are spurious? The "results" link takes you straight to the jenkins output and for the ones I clicked on, it looks like it doesn't compile because `pendingSuperCall` was removed.

**Comment by xeno-by** [comment]
Oh. I'm very sorry. Indeed, the failures are genuine.

**Comment by xeno-by** [comment]
Rebased against the new 2.10.x. PLS REBUILD ALL

**Comment by adriaanm** [comment]
sorry i was just changing the jenkins scripts as described on scala-internals
I'll make sure it gets built.

**Comment by adriaanm** [comment]
PLS REBUILD pr-rangepos-per-commit

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
PLS SYNCH

**Comment by JamesIry** [comment]
ping @adriaanm I think we should merge this puppy and see what it breaks.

**Pull request merged**
