### PR TITLE
Merge 2.12.x to 2.13.x [ci: last-only]

### PR DESCRIPTION
**Pull request by SethTisue**
nothing release-note-worthy here

PICK #10257 JQuery 3.6.3
PICK #10256 sbt 1.8.2
SKIP #10260 (spec fix backport)
SKIP #10126 (private[this] backport)
PICK #10254 copyright 2023
~PICK~ SKIP #10248 ListSet (forward-port: #10271)

~@som-snytt for #10248 I merged the test changes forward but the code changes didn't seem applicable for forward-merging; you might double-check to see if there's anything you wanted brought forward~

### CODE REVIEW

**Comment by som-snytt** [comment]
@SethTisue maybe just skip it. The test doesn't merge forward because it's pre-testkit! How did anyone get any work done back then?

**Comment by som-snytt** [comment]
:tada: this included sbt 1.8.2, right? I surprised myself at how annoyed I felt behind the curve. Thanks! Let's never assume these "mechanical" tasks are achieved by an automated mechanism.

**Comment by SethTisue** [comment]
> this included sbt 1.8.2, right? 

yup

the Steward upgraded 2.12.x, so that part's automated

**Comment by som-snytt** [comment]
Does Stew have your private number?

It's comforting to know that Scala's compatibility guarantee is forward, backward, and Steward.

**Pull request merged**
