### PR TITLE
Deprecate varargs -= in Shrinkable

### PR DESCRIPTION
**Pull request by som-snytt**
Follow-up to https://github.com/scala/scala/pull/6719

### CODE REVIEW

**Review by julienrf — COMMENTED** [review]
LGTM, thanks!

BTW, are we sure that infix operations with multiple args are effectively going to be deprecated?

**Comment by dwijnand** [comment]
Yep.

**Review by dwijnand — APPROVED** [review]

**Comment by som-snytt** [comment]
But are you *sure* sure?

**Comment by japgolly** [comment]
Minor typo in description, should be `-=`. Mentioning because it could lead to misleading release notes later :)

**Comment by som-snytt** [comment]
@japgolly Thanks for the sharp eyeballling!
@SethTisue Thanks for the improved wording!

**Pull request merged**
