### PR TITLE
upgrade to sbt 0.13.16

### PR DESCRIPTION
**Pull request by SethTisue**
not to be merged until 0.13.16 final is out.  for now, we just
want Jenkins' opinion.  @eed3si9n @dwijnand

### CODE REVIEW

**Comment by dwijnand** [comment]
Looks like Jenkins likey.

**Comment by SethTisue** [comment]
(looks like work on 0.13.16 got set aside in favor of getting 1.0.0 out the door)

**Comment by SethTisue** [comment]
(we can always reopen)

**Comment by dwijnand** [comment]
0.13.16 is due out soon, particularly given https://github.com/sbt/sbt/issues/3325.

**Comment by SethTisue** [comment]
green on 0.13.16-RC1

**Pull request merged**
