### PR TITLE
Migration rework #1:

### PR DESCRIPTION
**Pull request by soc**
- The @migration annotation can now be used like @deprecation, old syntax is still supported, but deprecated.
  - Improved the wording and the consistency of most migration messages, migration warnings now also show the version the change occurred.
  - Adjusted test.
  - Partially fixes SI-4990.

Some tests in specialized fail with "value integerBoxCount is not a member of object scala.runtime.BoxesRunTime", but it could also be my old machine I'm currently testing on ...

### CODE REVIEW

**Comment by paulp** [comment]
This looks pretty good.  Since "2.8" and "2.9" are technically not versions of scala, can you change all those strings to "2.8.0" and "2.9.0".  Also, can you please read http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html and author your commit messages accordingly.

**Comment by soc** [comment]
I left out the patch number because I decided that I didn't want to check every single migrated method when it changed exactly. I'll change it and add ".0".

**Comment by paulp** [comment]
Nothing which merits a migration warning should ever be introduced in a point release (which isn't to say it never happened, but it'll at worst be the rare exception.)

**Comment by soc** [comment]
Ok. New pull request is up.

**Pull request closed without merging**
