### PR TITLE
SI-6345 Remove scala.runtime.ScalaRunTime.Try

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Mailing list: https://groups.google.com/forum/#!topic/scala-internals/dihnxkX9ofQ

**Comment by jsuereth** [comment]
+1 from me!

**Comment by retronym** [comment]
> This code looks like it dates from the Nixon administration, so deleting it might be better.

75d02a1

Apparently Nixon couldn't afford AST nodes for try/catch: ca9f4fbb

+1 to eradication.

**Comment by paulp** [comment]
One of those classes I've been dragging around for all eternity... looks great to me.

**Pull request merged**
