### PR TITLE
Add support for -Dpartest.scalac_opts to the partest command

### PR DESCRIPTION
**Pull request by dwijnand**
Seems to work for me, but review by @retronym / @eed3si9n who I know know more about sbt parsers than me.

### CODE REVIEW

**Comment by szeiger** [comment]
Can this be extended to support the other properties for partest? Ideally it would suggest the ones it knows for completion but allow arbitrary `-D` arguments.

**Comment by dwijnand** [comment]
This was the only one I was after to fix, so, as a middle ground, I've opened this branch for additional commits if you'd like to improve on it.

**Comment by adriaanm** [comment]
Thanks! Let's make a concerted effort to polish our build and make our CI scripts more configurable after 2.12.0. I'll retarget this to 2.12.1.

**Comment by dwijnand** [comment]
Sure. Changed the target branch to 2.12.x and rebased.

**Comment by szeiger** [comment]
LGTM

**Comment by dwijnand** [comment]
Merge? Or is this awaiting a review from @retronym?

**Pull request merged**
