### PR TITLE
Remove unnecessary lower bounds on Eithers joinLeft and joinRight

### PR DESCRIPTION
**Pull request by kiritsuku**
Because <:< is contravariant in its first type parameter it is not
necessary that both type parameters of Either are lower bounded in
joinLeft and joinRight.

---

I don't know if you want to have a ticket for this. If yes, just tell me and I create one.

### CODE REVIEW

**Comment by paulp** [comment]
The ticket I could really go for is the one pointing out that the compiler could tell you when you use a type parameter in a useless way.

**Comment by soc** [comment]
LGTM, considering that I can't remember when I've last seen a `leftJoin`/`rightJoin` with explicit type parameters.

**Comment by kiritsuku** [comment]
I created the ticket [SI-7382](https://issues.scala-lang.org/browse/SI-7382).

I'm not experienced enough to think about how to solve the backwards compatibility problem. Feel free to close the PR, if no solution comes up.

**Comment by retronym** [comment]
Closing this. A knowing break in source compatibility requires a consensus, and I don't think these methods are important enough to warrant that discussion.

**Pull request closed without merging**
