### PR TITLE
Implement @static annotation on singleton object fields.

### PR DESCRIPTION
**Pull request by axel22**
This commit introduces the `@static` annotation on fields of static singleton objects.

A static singleton object is a top-level singleton object or an object nested within
a static singleton object.

The field annotated with `@static` is generated as a true static field in the companion
class of the object. The initialization of the field is done in the static initializer of the
companion class, instead of the object itself.

Here's an example. This:

```
object Foo {
  @static val FIELD = 123
}
class Foo
```

generates :

```
object Foo {
  def FIELD(): Int = Foo.FIELD
}
class Foo {
  <static> val FIELD = 123
}
```

The accessor in `object Foo` is changed to return the static
field in `class Foo` (the companion class is generated if it is
not already present, and the same is done for getters if `FIELD`
is a `var`).

Furthermore, all the callsites to accessor `Foo.FIELD` are rewritten
to access the static field directly.

It is illegal to annotate a field in the singleton object as `@static` if there is
already a member of the same name in `class Foo`.

This allows better Java interoperability with frameworks which rely on static fields being
present in the class.
The `AtomicReferenceFieldUpdater`s are one such example. Instead of having
a Java base class holding the `volatile` mutable field `f` and a static field containing
a reference to the `AtomicReferenceFieldUpdater` that mutates `f` atomically,
and extending this Java base class from Scala, we can now simply do:

```
object Foo {
  @static val arfu = AtomicReferenceUpdater.newUpdater(
    classOf[Foo], classOf[String], "f"
  )
}
class Foo {
  @volatile var f = null
  import Foo._
  def CAS(ov: String, nv: String) = arfu.compareAndSet(this, null, "")
}
```

In summary, this commit introduces the following:
- adds the `@static` annotation
- for objects without a companion class and `@static` members, creates a companion class
  (this is done in `CleanUp`)
- checks for conflicting names and if `@static` is used on static singleton object member
- creates the `static` field in the companion class for `@static` members
- moves the field initialization from the companion object to the static initializer of
  the class (the initialization of `@static` members is bypassed in the `Constructors` phase,
  and added to static ctors in `CleanUp`)
- all callsites to the accessors of `@static` are rewritten to access the static fields directly
  (this is done in `GenICode`)
- getters and setters to `@static` fields access the static field directly, and the field in the
  singleton object is not emitted (this is done in `GenICode`)
- changes in `GenJVM`, `GenASM` - now computing local var indices in static initializers
  as well - this was an oversight before, now is necessary

Future work: allow the @static annotation on methods as well - this will
be added next.

Review by @odersky
Review by @dragos

### CODE REVIEW

**Comment by paulp** [comment]
I haven't looked at the code yet, but this is very welcome!

**Comment by ijuma** [comment]
Agreed, this is great.

**Comment by soc** [comment]
Hi @axel22!

I don't know how long I waited for this, thanks!

One thing perhaps: I remember that there was an earlier hack included to fix an issue with Android compatibility, I think it would make sense to remove that hack now and check that "static" also works for this "real world use case".

Bye,

Simon

**Comment by soc** [comment]
Found it! Look for `isParcelableClass` in GenJVM, `JAndroidBuilder` in GenASM and the whole `GenAndroid` file.

**Comment by axel22** [comment]
Apparently, we're supposed to submit pulls only to 2.10.x branch, they will be automatically merged into master.

**Comment by weihsiu** [comment]
+10

**Pull request closed without merging**
