### PR TITLE
SI-7151 Emit final in bytecode for final inner classes.

### PR DESCRIPTION
**Pull request by retronym**
As we did before a regression in 18efdedfb / SI-5676.

This commit tightens up the condition in which the FINAL
modifier is omitted; it now _only_ does this for the module
classes of nested objects.

Review by @JamesIry

### CODE REVIEW

**Comment by retronym** [comment]
Closing and submitting against 2.10.x; this was a regression from 2.9.2 to 2.10.0, so it would be nice to deliver the fix in 2.10.3.

**Comment by retronym** [comment]
@JamesIry could you please re-review now that I have targeted master?

**Comment by gkossakowski** [comment]
@JamesIry: ping

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
