### PR TITLE
don't merge: refchecks changes for community build testing [ci: last-only]

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by adriaanm** [comment]
@SethTisue could you schedule a 2.12 community build against this?

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4138/

**Comment by SethTisue** [comment]
results are promising. better-files failure is unrelated, akka-more and scala-js failures are likely intermittent. I've queued a followup at
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4142/ but it's probably not really necessary

EDIT: gah, run 4142 was plagued by transient resolution errors. queued https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4145/

**Comment by SethTisue** [comment]
community build results: there are a few unrelated failures, but the Scala.js failure looks real, @adriaanm and @sjrd I think you'll want to look at that and see what's up

**Comment by sjrd** [comment]
For Scala.js, there are lots of new warnings in the compilation of the scalalib, which I guess you also see in the scala/scala repo.

The errors happen during the compiler tests, which are our "neg" tests. Apparently the changes in this PR cause some errors to be duplicated, reported at two different positions. We might be able to work around that in Scala.js itself, but it might also be a symptom of something wrong in scala/scala. I don't have time to investigate this further at the moment.

**Comment by adriaanm** [comment]
Thanks, I believe those new errors are indeed problems in the old stdlib. The reason they are duplicated is that they are due to mixing in traits, and now we check and report on each time they are mixed in. I’ll take a look next week if we can recover the old behavior under a flag, or maybe we should skip this fix.

**Pull request closed without merging**
