### PR TITLE
Adds Swing wrappers for ColorChooser and PopupMenu

### PR DESCRIPTION
**Pull request by ingoem**
This integrates pending non-controversial pull requests from Andy Hicks and John Sullivan.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Needs reviewer.

**Comment by ingoem** [comment]
review @gkossakowski

**Comment by gkossakowski** [comment]
Well, I don't know anything about Swing so I don't think I'm good reviewer, sorry.

@jsuereth is taking care of library in general so I'll leave up to him to decide what to do with this PR.

**Comment by paulp** [comment]
Due to the high degree of isolation swing has from everything else, and also due to the fact that swing doesn't build with java7 anyway, I think you can merge this in good conscience.  (I know very little about swing but I offer my LGTM since I do know something about risk.)

**Comment by ingoem** [comment]
Is anything gonna happen with this request?

**Comment by paulp** [comment]
I think @jsuereth has been otherwise occupied the last week; I predict we'll see him again soon.

**Comment by jsuereth** [comment]
It's all completely new code, doesn't touch existing classes.   This is fine for 2.10.1.

Lgtm

**Pull request merged**
