### PR TITLE
SI-7335 Simpler bootstrapping the standard library

### PR DESCRIPTION
**Pull request by retronym**
- mandate that Predef parents are defined in Predef.scala
- fix bugs / add logging in related code

Review by @namin (for confirmation that this will be okay for scala-virtualized), and @lrytz

### CODE REVIEW

**Comment by lrytz** [comment]
For the special case to not import Predef in Predef, I vote for removing altogether it if everything still compiles / bootstraps.

A comment on `def exists` in `Symbols` would be helpful - what does it test for, i.e. which symbols don't exist? I can't infer that easily from the source.

The test `test/files/run/t7335.scala`, does it not require a check file?

Finally, having a test for the source-file-order-independence is not easily possible I guess..

**Comment by namin** [comment]
LGTM

**Comment by retronym** [comment]
@lrytz If I change `Symbol#reallyExists` to:

``` scala
def reallyExists(sym: Symbol) = {
      if (isStale(sym)) {
        sym.setInfo(NoType)
        false
      }
      else sym.rawInfo != NoType && sym.exists
    }
```

(i.e. avoid calling `sym.exists` if it can only return false), we _never_ return false from `sym.exists` when compiling the library with `quick/bin/scala`. Maybe things can be different under a bootstrap compilation (no previously compiled classfiles), or under the IDE?

Let's discuss this tomorrow to figure out and document `Symbol#exists` reason to exist.

Perhaps also of interest: the 'stale' symbols that show up in a compilation of the stdlib are `ClassSymbols` for `scala.xml.Null` / `scala.xml.Source`. In the sources, we only have modules by those names. I wonder where those class symbols come from?

**Comment by retronym** [comment]
I didn't mean to checkin `test/files/run/t7335.scala`, I've just removed it.

**Comment by paulp** [comment]
LGTM. @retronym Those class symbols come from blindly creating both class and module symbols for every classfile encountered without regard for whether they both exist. This is also the cause of a bunch of the pain with package objects. Take a look at #2362 if you haven't already, I have another commit which fixes all the package object bugs I am aware of (but I admit haven't looked that hard.) At least it fixes all the ones discussed in SI-4695.

**Comment by retronym** [comment]
@lrytz I'm unable to provide more useful documentation for `Symbol#exists`. I've added one more commit to include the import of `Predef._` in Predef.scala, (ie, remove the special case that tried to prevent this.)

**Pull request merged**
