### PR TITLE
Simpler SubstSymMap to leverage reusable instance

### PR DESCRIPTION
**Pull request by som-snytt**
Follow-up to (includes and supersedes) https://github.com/scala/scala/pull/9039

with an opinionated commit that simplifies the classes and just commits to mutable (instead of a forked hierarchy; there were vars anyway).

### CODE REVIEW

**Comment by som-snytt** [comment]
Travis queued but didn't start the Scala 3 leg of the journey.

**Comment by som-snytt** [comment]
Apparently this must be lazy
```
-    object mapTreeSymbols extends TypeMapTransformer {
+    val mapTreeSymbols = new TypeMapTransformer {
```
because after trying it locally
```
[error] Caused by: sbt.ForkMain$ForkError: java.lang.NullPointerException: Cannot load from object array because the return value of "scala.reflect.internal.SymbolTable.phaseWithId()" is null
```
It forces `rootMirror` and fails a phase check which it can't report.

**Comment by som-snytt** [comment]
Forcing the fresh build of the first commit, rebased, shows the intermittent errors. For example,
```
scala.tools.partest.sbt.TestFailedThrowable: output differs  !!    1 - run/reflection-tags.scala                 [output differs] 
% diff /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/run/reflection-tags.check /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/run/reflection-tags-run.log @@ -1 +1,85 @@ 
+Uncaught exception on thread Thread[Reflector-771,5,main]: java.lang.IndexOutOfBoundsException: -1 is out of bounds (min 0, max 28) +java.lang.IndexOutOfBoundsException: -1 is out of bounds (min 0, max 28) 
+ at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:91) 
+ at scala.reflect.internal.Symbols.cloneSymbols(Symbols.scala:3776) 
+ at scala.reflect.internal.Symbols.cloneSymbols$(Symbols.scala:3772) 
+ at 
```
That is what I saw locally but intermittently.

**Comment by som-snytt** [comment]
Looking at it again, just realized that it's the test I mentioned yesterday that is multi-threaded. When it fails, its stack traces pollute the output of random other tests!
```
at Test$$anon$1.run(reflection-sync-subtypes.scala:15)
```

**Comment by SethTisue** [comment]
@retronym can we interest you in reviewing this?

**Comment by som-snytt** [comment]
If they are opening down under, I don't mind contributing a voucher of some kind, perhaps for a family restaurant? I know "Outback" is a chain, but do they actually have them in the Outback? [Wikipedia](https://en.wikipedia.org/wiki/Australian_cuisine) mentions "A typical Australian meat pie with tomato sauce." I could order a care package with a bunch of those. But please tell me it's not kangaroo meat.

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
this sealed `SubstMap`, Scalafix wants to extend it; let's discuss on #9630

**Pull request merged**
