### PR TITLE
SI-6471 Update jquery from 1.4.2 to 1.8.2

### PR DESCRIPTION
**Pull request by VladUreche**
This reopens SI-6170 that was fixed by 1be1f760. I don't want to start
a revert war, but I see two reasons we should stick to newer jquerys:
- they provide better compatibility to new browsers
- having diagrams not working is much more annoying than having the
  splitter not work

### CODE REVIEW

**Comment by VladUreche** [comment]
Review by @ingoem since @heathermiller is not here.

**Comment by ingoem** [comment]
LGTM

**Comment by jsuereth** [comment]
What's the trade-off here?  The "splitter" doesn't work?

**Comment by VladUreche** [comment]
Yep, you can't adjust the navigation panel width anymore (shown/autohide/hidden still works).

**Comment by VladUreche** [comment]
@ingoem said he'll have a look if the splitter can be replaced with a better component and since diagrams are completely crippled in this state I'd vote for merging asap.

**Pull request merged**
