### PR TITLE
Revamp of some repl mechanisms.

### PR DESCRIPTION
**Pull request by paulp**
This includes some large simplifications and consistentifications in the repl. Review by @som-snytt.

### CODE REVIEW

**Comment by paulp** [comment]
We will also accept @retronym, @jsuereth, or frankly anyone with a heartbeat. I should make a macro to mention everyone I know by name.

**Comment by som-snytt** [comment]
I'm looking, too, ATM.  I can only say UPC/UPQ until I understand enough for the L acronym.  (Usual paulp code, usual paulp quality.)

**Comment by som-snytt** [comment]
Is this the correct and desired change in message?  I haven't looked back in the source yet, but I built the branch (but maybe not cleanly, because if Jenkins can't have reproducible builds, why should little me).

For a private val,
import f.x
val z = x

changed from
value x in class Foo cannot be accessed in localaccess.Test.Foo
to
not found: value x

The message on unimported reference is the same,
val zz = f.x

I remember a discussion about whether you should be able to import what you can't access, especially for wildcard._.

(I saw the different -Yissue-debug in typedIdent in my versions of trunk and the branch.  I could also see from the repl that importableMembers works.  I'm not set up to build scala-ide yet for debug.)

**Comment by som-snytt** [comment]
Should I have said lgtm.  Veni, vidi, wowee.  He saw that it was good.

**Comment by paulp** [comment]
I am indebted for your reviewing efforts. Actually I still have bookmarked a pull req which I think you closed for lack of a reviewer, does that sound true? You can play your "get a review free" card anytime.

**Comment by som-snytt** [comment]
I think I made a comment there, No one is clamoring to reduce boilerplate for plugins.  So maybe I'll hold that card until I really need it.

Wait a sec, for the record, "review by: @paulp who cares" meant "paulp, who cares," not "paulp. Who cares?"

I can't use -Xshow-phases anymore, though.  I just can't.

The other development is that you called for the removal of unused and commented code, and I remember there was a commented version of a method, You'd think it would be easier to write it this way.

What we need is an annotation for tools to link to alternate branches (besides a github URL).
https://github.com/som-snytt/scala/blob/issue/6446-plugin-desc/src/compiler/scala/tools/nsc/plugins/PluginDescription.scala#L63
An editor could display it folded or side-by-side, build tools could grab it based on a flag.

**Comment by paulp** [comment]
Yeah, more "code dimensions" is something I am all in favor of.

Jenkins is still kicking it in Tahiti but my personal jenkins approves of my rebase.

**Pull request merged**
