### PR TITLE
replace private val/var with private[this].

### PR DESCRIPTION
**Pull request by takayahilton**
`private [this] val/var` is translated to direct field access

### CODE REVIEW

**Comment by dwijnand** [comment]
What's the motivation behind this change?

It's the more restrictive option which is both good and bad (as things evolve you might have to micromanage this detail).  Also it's more verbose.  Also this is targeting 2.12.x.

**Comment by plokhotnyuk** [comment]
what about `private def`?

**Comment by takayahilton** [comment]
@dwijnand 
`private [this] val/var` is converted to direct field access, I guess it will perform slightly better than ` private val/var`.

And class file size will also be smaller.
(But I'm not sure)

**Comment by takayahilton** [comment]
@plokhotnyuk 
I think there is no difference on byte code between` private [this] def` and `private def`.

**Comment by plokhotnyuk** [comment]
@takayahilton It can be a case for objects:
https://stackoverflow.com/questions/36849761/when-is-privatethis-def-a-performance-advantage-over-private-def

**Comment by lrytz** [comment]
I'm not in favor of this change, unless we have some (benchmark) evidence that there's an advantage. From my experience, I would not expect to see any performance benefit (getters/setters are small enough to be inlined unconditionally by the JVM). cc @retronym.

**Comment by xuwei-k** [comment]
scala-library.jar size

before: 5187871 byte a995c4dfdc5308e2d8651fa61fbdf1881385edea
after: 5178546 byte 98fd6ffb6c09b4b4c3b9aca1b653455a389dbb69
diff: 9325 byte

**Comment by lrytz** [comment]
@xuwei-k out of curiosity, how did you build the jars? in particulari, was the optimizer enabled?

**Comment by xuwei-k** [comment]
> how did you build the jars? 

`library/packageBin`

**Comment by retronym** [comment]
Here's the bytecode diff (generated with the help of [scafu](https://github.com/adriaanm/binfu/blob/master/scafu.sh) and [`jardiff`](https://github.com/scala/jardiff):

```
$ jardiff $(scala-classpath $(scala-ref-version a995c4d))  $(scala-classpath $(scala-pr-version 8199))| tee /tmp/private-this.diff
```

 https://gist.github.com/retronym/1707779d4428e48c013c33ee89ce04a6

The bytecode size savings are due to avoiding emitting the getter/setter methods. There should be no difference in runtime performance in HotSpot due to the policy to unconditionally inline accessors. Perhaps one would save a few millisecond of startup cost due to less work for JIT to do.

**Comment by lrytz** [comment]
Thanks. Do you agree to close this one?

**Comment by retronym** [comment]
Yeah, I think I'd prefer to improve the backend's handling of plain-old-private vals and vars.

It could:
  - emit `getfield` / `setfield` (to save the JIT from needing to do the inlining)
  - stop creating the accessors as an opt-in optimization. I don't think we can safely do this by default because some folks might be relying on them via Scala/Java reflection.

**Comment by som-snytt** [comment]
I hope the language finds its way to make `private[this]` the default and requiring `private[C]` for current semantics.

I know what private means in ordinary language. If I have a clone, an identical twin, or a Doppelgänger, I don't want that person reading my diary or rifling through my sock drawer or coming into the bathroom when it's my turn. Frankly, I don't even want my Doppelgänger shadowing me in the streets and showing up at parties unexpectedly.

**Comment by lrytz** [comment]
Started a discussion at https://contributors.scala-lang.org/t/change-private-to-mean-private-this/3493

**Pull request closed without merging**
