### PR TITLE
updating resolveDups() to use MethodTFA.mutatingInterpret()

### PR DESCRIPTION
**Pull request by magarciaEPFL**
Without this patch ICodeReader doesn't load bytecode for some Java-compiled class files (those containing DUP_X-style instructions).

review by @VladUreche or @dragos

### CODE REVIEW

**Comment by VladUreche** [comment]
The patch LGTM, but can you add a test to make sure we don't fail again?

**Comment by VladUreche** [comment]
How I picture the test:

```
test/files/run/inline-trait/toinline_1.scala // contains the method to be inlined and object Test extends App {}
test/files/run/inline-trait/inlinedhere_2.scala // contains the inline target and:
object Test extends IcodeTest {
  override def printIcodeAfterPhase = "inliner"
}
```

the diff should compare the inlined version vs the non-inlined version
WDYT?

**Comment by magarciaEPFL** [comment]
A refinements to the idea: "to_inline_1" should be Java file whose compiled version contains one ore more DUP_X-style instructions.

With the compiler on the classpath, we could skip that file, because one of the scala.tools.asm Java files satisfies the property above.

Before getting there, I'm checking what can be done about two other backend bugs, SI-6102 and SI-6157.

**Comment by VladUreche** [comment]
Good point Miguel, so we can use a single test file :)

**Comment by jsuereth** [comment]
Should I merge or not?

**Comment by magarciaEPFL** [comment]
I'm for merging even though a test is missing (as before). This patch addresses a "corner case" alright, but that corner case used to work in 2.9, thus we're talking about a regression.

**Comment by VladUreche** [comment]
@jsuereth: Since there are still 49 critical and blocker bugs, I would opt for merging once we have a test for this, so we don't increase our technical debt without a strong reason.

@magarciaEPFL: I've been thinking about your suggestion of inlining the ASM code and I think we shouldn't do that -- the asm code might change, so we would end up basing the test on a more or less moving target -- I really don't think we want to revisit the test each time we update asm, so we'd be better off having our own file, even if it's copied from ASM's code.

**Comment by jsuereth** [comment]
I too would like ot have a test case here.  I wasn't sure if you were planning to include it in a later commit that I hadn't seen or what.   I'll wait to merge for the test case.

**Comment by magarciaEPFL** [comment]
Let's continue the discussion at https://issues.scala-lang.org/browse/SI-6174 , resubmit coming later.

**Comment by VladUreche** [comment]
I had a look at adding a test for this -- it's very tricky to produce the right bytecode, as the java compiler will not generate it for simple test cases. It is also incorrect to link to the asm bytecode, thus I tend to accept this patch without a test, as it's just too hard to produce one. Miguel, WDYT?

**Comment by magarciaEPFL** [comment]
Let's merge what we have now.

**Pull request merged**
