### PR TITLE
SI-4695 Fix separate compilation of package objects

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @retronym, please.

**Comment by retronym** [comment]
See also #2362 and https://groups.google.com/forum/#!topic/scala-internals/8bwPH8_65XE 

The test case for the reporting code should not be in pending. To compare the compiler output to a checkfile, you cou use the approach taken by `run/t6555.scala`.

**Comment by retronym** [comment]
Could you determine the code coverage afforded by the enclosed tests (insert ??? into the diffs one by one and run the tests). In the previous incarnation of this PR, some paths were untested.

**Comment by soc** [comment]
@retronym thanks for the pointers. I'll have a look at it after my exams on Friday.

**Comment by soc** [comment]
@retronym I made the changes you suggested in https://github.com/soc/scala/commit/d2857e91afde12badcff8b0962f209fc1a40e58c, but it still doesn't print anything to the checkfile. Ideas?

**Comment by gkossakowski** [comment]
I'm cleaning up the PR queue so I'll close it for now. You can ask me to reopen once the test problems are resolved.

**Comment by soc** [comment]
@retronym Looks like `-D`  settings don't survive `DirectTest`.

**Pull request closed without merging**
