### PR TITLE
SI-7246 Make $outer pointer elision Java aware

### PR DESCRIPTION
**Pull request by retronym**
In e0853b3, a space-saving optimization elided the outer pointer
of inner classes if the the (protected) outer pointer of the
immediate parent class was guaranteed to point to the same instance.

But, this check failed to account for Java parent classes, which
don't follow the Scala scheme. This commit disables the optimization
in that case.

The original test case in e0853b3 was anemic, I've fleshed it out to:
- test the presense or absense of $outer pointers with Java reflection
- test the optimization works in the presense of aliased and annotated
  aliased types. (The former worked already, the latter required a
  change to the implementation.)
- Test the negative case when the prefixes don't line up and the
  subclass in fact needs its own $outer.

This patch is based on work by Euguene Vigdorchik with some
additions by Jason Zaugg.

Targeted at 2.10.x because this the change is binary compatible other than the rare case of extending an annotated type. We don't do that ourselves, and could rely on MiMa to tell us if we do. (For a Java defined parent class, as shown in the enclosed test, the compiler used to crash.)

Review by @vigdorchik

Supersedes #2256

### CODE REVIEW

**Comment by retronym** [comment]
PLS SYNCH

**Comment by retronym** [comment]
I've addressed the review comments, @vigdorchik, could you please re-review?

**Comment by retronym** [comment]
Oops, I've removed that duplicate line. Ready for the (last?) review...

**Comment by paulp** [comment]
We have to do something about the confusion github sows under push -f. I know eugene had comments on this PR; they are completely missing now, there's no "Foo discussed an older version of this code." This has happened a bunch of times. It makes it impossible to know where people stand on anything or whether something has been adequately addressed.

**Comment by paulp** [comment]
LGTM.

**Pull request merged**
