### PR TITLE
The alternative, flat representation of classpath elements

### PR DESCRIPTION
**Pull request by mpociecha**
This pull request provides an alternative, more efficient implementation of classpath handling in the compiler. This feature will be delivered in 2.11.5 but it's _off_ by default. To try it out, you must enable it with `YclasspathImpl:flat` compiler option. The largest performance gain will be observed when multiple instances of the Scala compiler are used within the same JVM. Examples include Scala IDE (one instance per open project in Eclipse) or parallel builds in sbt. Compiler-derived tools like REPL also benefit from the same optimisations.

Below is the original description of this PR with all remaining details.

---

This is another PR created for the flat classpath representation. This time the target is changed to 2.11.x branch.

It's finished work started and abandoned by @gkossakowski
Related discussion: https://groups.google.com/forum/#!msg/scala-internals/xgb5YbKvQcw/7bcbsvKkzQkJ

The main goal of Grzegorz was to improve the efficiency of classpath. At the end it turned out that the efficiency improvement is not significant so Grzegorz stopped working on that. 

On the other hand it was worth to continue these works due to several reasons:
- it's possible to reduce memory consumption significantly
- each possible efficiency improvement is important
- the old classpath is maybe too complex because it was created when e.g. .NET was supported - it can be simpler

New (flat) classpath has dedicated classes for various file types characteristic for Scala with JVM backend - what allows us to create more efficient, more low-level operations.
To reduce memory consumption there's added caching for jar/zip files. So that we can reuse existing instances, when we create entries for the same files once again.

One of the most important things took into account during creating this implementation was adding it as an optional feature, which can be marked as experimental and turned on using flag. At the beginning users will use an old classpath implementation by default and they will be able to use the new implementation when:
- they will want to test it (feedback)
- they will want to gain benefits which it provides

I took into account also planned better support for JSR-223. So it supports for instance ManifestResources introduced here: https://github.com/scala/scala/pull/2238
There was no proper description what's going on with these changes and how to test them but @rjolly sent me some useful papers.
This particular type of classpath can be tested using e.g. command:
jrunscript -classpath scala-compiler.jar;scala-reflect.jar;scala-library.jar -l scala
where scala-library.jar was modified using https://github.com/rjolly/jarlister

I tested flat classpath in several ways:
- First of all obviously all tests (there are added certain new ones especially for this implementation) pass and bootstrapping also works.
- I built Scala IDE using my version of Scala and tested it with a very large codebase with about 100 projects. I turned off the closing of unused presentation compilers which I added lately. And after that I did certain custom operation which does a deep refresh of all projects (close projects, regenerate the workspace, open projects).

The flat classpath with turned on caching allowed me to reduce allocated memory in old gen from about 6GB (for current classpath) to about 750MB. So in the case of IDE and presentation compilers the gain is really significant.
- The efficiency of both implementations in real use cases seems to be similar but probably it could be tested better. In small benchmarks the flat one was winning.
- On the other hand there are situations when the gain is quite significant. When running a whole Scala's test suite:

Tests using a computer with SSD:

| Time type: | recursive classpath | flat classpath |
| --- | :-: | --: |
| avg of 4 repetitions | 29 minutes 34 seconds | 27 minutes 15 seconds |
| min | 29 minutes 28 seconds | 27 minutes 6 seconds |
| max | 29 minutes 41 seconds | 27 minutes 32 seconds |

Tests using other computer with the scala project directory moved to some external HDD connected via USB cable:

| Time type: | recursive classpath | flat classpath |
| --- | :-: | --: |
| avg of 4 repetitions | 56 minutes 43 seconds | 52 minutes 38 seconds |
| min | 55 minutes 40 seconds | 52 minutes 8 seconds |
| max | 58 minutes 26 seconds | 53 minutes 0 seconds |

Note: I changed the classPath method in Global to the dynamic dispatch. And now there's returned a base class of the old and the new classpath with common interface based on a part of API of the old classpath. I tested it with sbt and there's no problem with compiling projects etc. Previously Grzegorz created certain hack for sbt's compiler interface where current classpath was calling the flat one, when it was needed. I changed this ugly solution to this mentioned dynamic dispatch and removed a hack. We can return to something like this, if it'd turn out that it's necessary.

Thanks to Grzegorz for hints and his initial implementation.

Lastly, the below disclaimer is required by the lawyers:

THIS PROGRAM IS SUBJECT TO THE TERMS OF THE BSD 3-CLAUSE LICENSE.

THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR
ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.
ONLY THE SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE, IF ANY, THAT ARE ATTACHED TO (OR OTHERWISE ACCOMPANY) THIS SUBMISSION (AND ORDINARY
COURSE CONTRIBUTIONS OF FUTURES PATCHES THERETO) ARE TO BE CONSIDERED A CONTRIBUTION. NO OTHER SOFTWARE CODE OR MATERIALS ARE A CONTRIBUTION.

### CODE REVIEW

**Comment by mpociecha** [comment]
@gkossakowski @adriaanm I hope this time it's okay.

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@7935085a583c8497a7153996113ca27875ad1c38

**Comment by adriaanm** [comment]
This looks really, really good! Thanks for going all the way, @mpociecha!

**Comment by gkossakowski** [comment]
I looked at the 7448377..672c119 range and it looked really good! With vastly improved commit messages and split of changes into separate, small commits it's really easy to review the code.

I'll continue the review of the rest of commits tomorrow.

**Comment by adriaanm** [comment]
@mpociecha, sorry about the radio silence -- my understanding is that we'll most likely be able to merge this as-is in the next few days.

**Comment by gkossakowski** [comment]
For documentation purposes: previous iterations of this PR are #4060 and #3962.

**Comment by gkossakowski** [comment]
I just finished reviewing all commits. I'm really impressed with quality of this PR. Really good work on both documentation (in commit messages and in the code) and the code itself! Also the structure of commits is really good.

Here're the things that hold me from giving LGTM and merging:
- [x] determine status of "Copyright (c) 2014 Contributor. All rights reserved." headers added to the contributed code. I understand they are required by lawyers but we have to make sure we can merge code like this. Scala is a bit special because it has its own license and CLA. I'll defer this decision to @adriaanm
- [x] turn off flat classpath by default; I understand that it was enabled so we can test it on CI and that was a good move; however, we have to turn it off, let's do that in separate commit appended to at the end of the list of commits

I just kicked community build that will use scala compiler version submitted by this PR: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/102/console

However, even if we find some issues with it we can fix them in subsequent PRs. For now only the two tasks I outlined above are needed to be done for merging this PR.

**Comment by mpociecha** [comment]
1. I'm not sure but probably you can just change them after merging this PR. ;)
2. Okay. It's exactly like my last sentences in the last commit:
   "Also flat classpath implementation is set as a default one to test it
   on Jenkins. This particular change must be reverted when all tests
   will pass because for now it's not desirable to make it permanently
   the default representation."

I'll read your questions/remarks and answer to them soon.

**Comment by adriaanm** [comment]
I double checked and the copyright header is fine.

**Comment by mpociecha** [comment]
@gkossakowski Error messages and a value name in t6502.scala are corrected directly in "Integrate flat classpath with the compiler". The last commit fixes everything else.

**Comment by gkossakowski** [comment]
LGTM

The whole community build passed with flat classpath enabled. Excellent work! :clap: :clap: :clap:

**Comment by lrytz** [comment]
nice! :boom:

**Comment by mpociecha** [comment]
Thank you all for your help and patience.

**Comment by gkossakowski** [comment]
@mpociecha, since this PR receives a fair amount of traffic (3500 views already) I edited the original description to provide a very high level info first. In particular, I mentioned how to test it and in which scenarios it makes sense to do it.

**Comment by mpociecha** [comment]
Ok, thanks. I didn't know there are such statistics. :)

**Comment by retronym** [comment]
> parallel builds in sbt

@gkossakowski I remember we were going to validate that the SBT setup would profit from this setting. Was this done?

**Comment by gkossakowski** [comment]
It wasn't until now. I created sbt project with the following config:

``` scala
resolvers in Global += Resolver.sonatypeRepo("snapshots")
scalaVersion in Global := "2.11.5-SNAPSHOT"
//scalacOptions in Global += "-YclasspathImpl:flat"
// allow 20 different compiler instances to run in parallel
concurrentRestrictions in Global := Tags.limitAll(20) :: Nil
lazy val project1 = project
lazy val project2 = project
...
lazy val project19 = project
lazy val project20 = project
```

Each project has one source file and no extra dependencies apart from standard Java and Scala dependencies.

I attached Yourkit profiler, ran `compile` and observed memory consumption. After that, I enabled flat classpath, forced gc and rerun `compile` again. The chart I got is:

image

If you measure memory consumption caused just by compilation (by subtracting the memory consumed by sbt itself) you get:

| Classpath impl | Memory consumed |
| --- | --- |
| recursive (old) | 440 MB |
| flat (new) | 264 MB |

The difference in memory consumption is not as dramatic as reported originally in the PR but still very noticeable. The gain we get depends on classpath's size. Standard classpath is small.

**Comment by retronym** [comment]
Thanks for verifying this.

**Pull request merged**
