### PR TITLE
Don't use a function `rebind()`.

### PR DESCRIPTION
**Pull request by utam0k**
I think that `rebind()` is not used already.

### CODE REVIEW

**Comment by utam0k** [comment]
I did sign the CLA.

**Review by dwijnand — APPROVED** [review]
Dead since 9f8961c58a01e83cf4bc782ac03dd9919983ce30.

**Review by diesalbla — APPROVED** [review]

**Comment by som-snytt** [comment]
No, this is useful.
```

     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/  version 2.13.0-20190506-064551-8cc69ad

scala> $intp
res0: scala.tools.nsc.interpreter.Repl = scala.tools.nsc.interpreter.IMain@59b32539

scala> import tools.nsc.interpreter._
import tools.nsc.interpreter._

scala> $intp.asInstanceOf[IMain].rebind(NamedParam("$intp", $intp.asInstanceOf[IMain]))

res1: tools.nsc.interpreter.Results.Result = Success

scala> $intp
res2: scala.tools.nsc.interpreter.IMain = scala.tools.nsc.interpreter.IMain@59b32539
```
Probably it could be more useful.

**Review by adriaanm — CHANGES_REQUESTED** [review]
@utam0k, thanks for proposing this! As som-snytt said, though, this method is used/useful in repl sessions. It was my mistake to omit it from the `Repl` interface (see https://github.com/scala/scala/pull/5903) -- we should probably add it [there](https://github.com/scala/scala/blob/c02e4ae4c359ca808d123a3bc78236258c75fb83/src/repl/scala/tools/nsc/interpreter/Interface.scala#L146) instead of removing it.

**Pull request closed without merging**
