### PR TITLE
[Sync copyright dates]

### PR DESCRIPTION
**Pull request by FelAl**

### CODE REVIEW

**Comment by adriaanm** [comment]
Thank you for cleaning this up, as well as for being patient with us! We're currently super busy with wrapping up 2.12.0-M5 (has to ship before Scala Days Berlin), and are weary of committing big changes that are not truly crucial to M5 in 2.12.x for that reason. We'll spend some time on the 2.11.9 queue as soon as we can and get this effort merged!

**Comment by FelAl** [comment]
No problem, take your time.

**Comment by FelAl** [comment]
Can I help somehow with this PR(and second https://github.com/scala/scala/pull/5195)? @adriaanm

**Comment by SethTisue** [comment]
@FelAl sorry for the long delay. 2.12.0 is pretty much done so we're returning now and working on 2.11.9 again

pardon me if I've forgotten previous history on this, but did you use a script to do this? if so, can we see the script?

**Comment by FelAl** [comment]
https://github.com/scala/scala/pull/5145
@SethTisue 
Hello, now I'm going to merge this script to `sbt-header` plugin, I'll start to work on it on the next week.

**Comment by SethTisue** [comment]
sounds awesome. using sbt-header for this sounds perfect.

I'm going to close this and the other PR. a new sbt-header based PR would be extremely welcome. feel free to target 2.12.x instead, where the sbt build is more mature.

**Pull request closed without merging**
