### PR TITLE
Tests on the ConstantFolder in the typechecker

### PR DESCRIPTION
**Pull request by da-tubi**
Tests constant folding on:
+ String
+ Boolean

### CODE REVIEW

**Comment by da-tubi** [comment]
Already signed CLA using the @da-tubi  account.

**Comment by SethTisue** [comment]
squashing this into a single commit should make CI like it. (our CI requires that every commit in a PR be green; that's the "combined" check.)

**Review by SethTisue — APPROVED** [review]

**Review by dwijnand — APPROVED** [review]
Thank you!

**Comment by SethTisue** [comment]
(If anyone's wondering, the context for this is https://github.com/scala/scala-dev/issues/29.)

**Pull request merged**
