### PR TITLE
SI-6120 Suppress extra warnings

### PR DESCRIPTION
**Pull request by som-snytt**
Sensibility checks in refchecks were shown to be redundant.

This commit includes a mild refactor to reduce tabbage, and
uses a local var to flag that a warning has already been emitted.

The flag is used at line 1020 to 1040.

It would be better to have the checks return true if warned,
to facilitate `nonSensically || unrelatedly`, etc. But that's a lot
of elses.

Review by? @retronym ?  I bet @paulp would rise from the grave for this one.

### CODE REVIEW

**Comment by paulp** [comment]
>  I bet @paulp would rise from the grave for this one.

It looooooooooks goooooooooooood to meeeeeeeeeeeee....... he comments, spoooooookily

**Comment by som-snytt** [comment]
I'll just make it pass some tests first.

**Comment by som-snytt** [comment]
Reverted those other check files from paulp's PR.

I just got a tingly feeling down my spine.

**Comment by adriaanm** [comment]
LGTM as well

**Pull request merged**
