### PR TITLE
fixes SI-5999

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @adriaanm and @odersky

**Comment by adriaanm** [comment]
overall impression: thanks for the extra effort in writing good commit messages

LGTM except for minor tweak to 3ad7700 and dropping 8626e6e

**Comment by xeno-by** [comment]
scala-checkin-manual is out of available executors, so I'm hijacking the kitteh in hope that here my commits will get tested faster and that all the tests will pass

**Comment by adriaanm** [comment]
LGTM

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Strange. I remember the kitteh used to automatically detect changes in pull requests and rebuild them without any pls-rebuild-all. Was that changed? Is current behavior a bug?

**Comment by adriaanm** [comment]
probably a bug, the build bot could do with some TLC

**Comment by xeno-by** [comment]
Back to the drawing board.

**Comment by xeno-by** [comment]
@adriaanm I've rebased the pull request, so all the commits appear to be changed, however I adjusted only the last three. 

First of all I'm really stupid for not remembering why I put that `BaseUniverseClass.typeConstructor` there. That was done to construct the type `base.Universe # TypeTag[$tpe]`, so that tag materialization can try to reuse tags from whatever universe before performing actual materialization. Neither `appliedType`, not `BaseUniverseClass.thisType` won't fit here. I've written a comment for that.

Secondly quite a few tests failed because of my latest change to staticModule/staticPackage. I've administered the fixes by replacing staticModule with staticPackage where appropriate (because the former doesn't work with packages and the latter doesn't work with modules). In the meanwhile I've added the "evicts calls to reify from our codebase" commit to simplify reflection rehashes until we freeze the API.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

kitteh stop caching failed builds and failing them again and again, pretty please

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
@xeno-by The build kitteh has a race condition.   After he tells jenkins to start a job, he has no guarantee which job # it will assign, nor when it will get scheduled.   He must poll until the job has started.   If his delay to check for start is _too short_ (i.e. jenkins is backed up, which has been happening frequently), then he pulls an old build.   If you open a JIRA INF ticket for me, I'll add it to my TODO list.  Along with more meowing.

**Comment by xeno-by** [comment]
Yay! Success!! Can I has merge? (see the comments above covering the recently introduced changes)

**Comment by adriaanm** [comment]
merge & ticket closing in progress -- good work!

**Pull request merged**
