### PR TITLE
Fixes SI-6521, overrides Range#head to be faster

### PR DESCRIPTION
**Pull request by dlwh**
Super trivial change.

### CODE REVIEW

**Comment by paulp** [comment]
I am curious whether you encountered something which led you not to mix IndexedSeqOptimized into Range, because on the face of it we should do that (and into NumericRange) but I have dark suspicion that it could hurt as much as it helps, or more.

**Comment by dlwh** [comment]
Reasonable question, and it was the first thing I tried. Alas it does not compile, because Range cannot inherit from IndexedSeqLike in a useful way. 

   with collection.IndexedSeqOptimized[Int, Range]:

```

[scalacfork] /Users/dlwh/src/scala/src/library/scala/collection/immutable/Range.scala:45: error: overriding method newBuilder in trait TraversableLike of type => scala.collection.mutable.Builder[Int,scala.collection.immutable.Range];
[scalacfork]  method newBuilder in trait GenericTraversableTemplate of type => scala.collection.mutable.Builder[Int,scala.collection.immutable.IndexedSeq[Int]] has incompatible type


```

Actually, I can do IndexedSeqOptimized[Int, IndexedSeq[Int]], can't I? (I hadn't thought to try that...)

Sadly, the performance is certainly not as "Optimized" as one would like. 

Based on the benchmark in the ticket. Times in seconds.
old: 41 
Optimized: 39 
manual override: 7

(Variation is usually like +-.5seconds) Actually, if I use the _exact same_ function in Range that's in IndexedSeqOptimized (just copying and pasting), I get about the same speed. The only difference is I used start and they used apply(0)...

Oh... Hello boxing my old friend: (Sorry for bytecode dump, take a look at 28 and a few lines following in both of the listings.)

```
  // Manual Override
  public long foo(int);
    Code:
       0: iconst_0      
       1: istore_2      
       2: lconst_0      
       3: lstore_3      
       4: getstatic     #19                 // Field scala/runtime/RichInt$.MODULE$:Lscala/runtime/RichInt$;
       7: getstatic     #24                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      10: iconst_3      
      11: invokevirtual #30                 // Method scala/LowPriorityImplicits.intWrapper:(I)I
      14: iload_1       
      15: invokevirtual #34                 // Method scala/runtime/RichInt$.extension0$until:(II)Lscala/collection/immutable/Range;
      18: astore        5
      20: iload_2       
      21: iload_1       
      22: if_icmpge     41
      25: lload_3       
      26: aload         5
      28: invokevirtual #40                 // Method scala/collection/immutable/Range.head:()I
      31: i2l           
      32: ladd          
      33: lstore_3      
      34: iload_2       
      35: iconst_1      
      36: iadd          
      37: istore_2      
      38: goto          20
      41: lload_3       
      42: lreturn   


// IndexedSeqOptimized

  public long foo(int);
    Code:
       0: iconst_0      
       1: istore_2      
       2: lconst_0      
       3: lstore_3      
       4: getstatic     #19                 // Field scala/runtime/RichInt$.MODULE$:Lscala/runtime/RichInt$;
       7: getstatic     #24                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      10: iconst_3      
      11: invokevirtual #30                 // Method scala/LowPriorityImplicits.intWrapper:(I)I
      14: iload_1       
      15: invokevirtual #34                 // Method scala/runtime/RichInt$.extension0$until:(II)Lscala/collection/immutable/Range;
      18: astore        5
      20: iload_2       
      21: iload_1       
      22: if_icmpge     46
      25: lload_3       
      26: aload         5
      28: invokeinterface #40,  1           // InterfaceMethod scala/collection/IndexedSeqOptimized.head:()Ljava/lang/Object;
      33: invokestatic  #46                 // Method scala/runtime/BoxesRunTime.unboxToInt:(Ljava/lang/Object;)I
      36: i2l           
      37: ladd          
      38: lstore_3      
      39: iload_2       
      40: iconst_1      
      41: iadd          
      42: istore_2      
      43: goto          20
      46: lload_3       
      47: lreturn       

```

**Comment by dlwh** [comment]
Nevertheless, I would vote for also mixing in scala.collection.IndexedSeqOptimized[Int, IndexedSeq[Int]], just for when methods get added to the collections lib. Probably as many as possible should be at a minimum copied and pasted into Range if its performance is worth the byte code bloat, unless the optimizer really can "optimize simple fors" at this point. I'd say it's worth it, just because performance gotchas are always annoying.

Of course, when specialized works and is finally in the collections library all this will be moot. (A man can dream, right?)

**Comment by paulp** [comment]
"Of course, when specialized works and is finally in the collections library all this will be moot."

My guess is macros will save us before specialization does.

**Comment by jsuereth** [comment]
This LGTM - We can probably also port to 2.10.x safely.

**Pull request merged**
