### PR TITLE
OSGi: Restrict Import-Package for scala.*

### PR DESCRIPTION
**Pull request by lefou**
Restrict the Import-Package OSGi manifest entry to match only binary compatible scala.\* packages. This is necessary, because the Scala OSGi versions do not match the OSGi semantic versioning policy and are not binary compatible between their OSGi minor versions. This means that e.g. the scala-compiler-2.11 bundle will never work if it imports a scala.\* package from 2.10 or 2.12. Thus this patch enforces a tight version range, only accepting versions within the same minor version. E.g. Applied to version 2.11.1 the range would expand to "[2.11,2.12)".

This PR also enforces a Java 6/7 execution environment for the bundles.

This PR has already a discussion history as #3697

### CODE REVIEW

**Comment by huitseeker** [comment]
This LGTM ! (it inherits my LGTM from #3697)

**Comment by lefou** [comment]
@adriaanm @retronym Is this ok for you, too?

**Comment by adriaanm** [comment]
LGTM, thanks!

**Comment by lefou** [comment]
So, what's the status? I hoped, this fix would be part of 2.11.1 release, but unfortunately, it isn't.

**Comment by adriaanm** [comment]
Sorry, we wanted to keep 2.11.1 as small as possible because it fixes a serious regression. I'm still talking to the IDE team about OSGi. 2.11.2 is no more than two months away!

**Comment by adriaanm** [comment]
@skyluc, since we're discussing OSGi, is there anything else left to do beyond this PR for scala to play nice with the IDE? I remember we discussed this recently, but I'm not sure of our conclusions, sorry.

**Comment by adriaanm** [comment]
I guess we'll find out if anything else is necessary soon then... Merging! :)

**Comment by lefou** [comment]
We will. Thanks!

**Comment by adriaanm** [comment]
Thank you for patiently pushing this through!

**Pull request merged**
