### PR TITLE
REPL handles assignment ops like Assign

### LINKED ISSUE #12894: REPL doesn't report op= mutations
## Reproduction steps

Scala version: 2.13

```scala
scala 2.13.12> var x = 42
var x: Int = 42

scala 2.13.12> x = 17
// mutated x

scala 2.13.12> x += 10

scala 2.13.12> x
val res1: Int = 27
```

## Problem

It should say that x was mutated by assignment `+=`.

### PR DESCRIPTION
**Pull request by som-snytt**
REPL decides rendering from untyped tree, so it doesn't see expansion of assignments.

This fix just handles "assignment operators" and hopes for the best.

Fixes scala/bug#12894

### CODE REVIEW

**Comment by som-snytt** [comment]
Added tweak from my previous branch `issue/12894-op=` which is a cooler name, I should have kept it.

Does not yet update what to display on mutation. Was the original reason to hesitate to display the mutated value that printing would force too much? For example, `var it = Iterator.continually(42)`.

If I update a mutable map, do I want to see the whole map or just what I updated? That "diff" view is helpful for `m += computed`.

**Comment by SethTisue** [comment]
(I'll take a look after 2.13.14 is out.)

**Review by SethTisue — APPROVED** [review]
very nice!

**Comment by SethTisue** [comment]
> Was the original reason to hesitate to display the mutated value that printing would force too much?

I don't know, but that's my best guess as well.

**Pull request merged**
