### PR TITLE
upgrade to asm 9.0, for JDK 16 support

### PR DESCRIPTION
**Pull request by SethTisue**
fixes scala/bug#12328

### CODE REVIEW

**Comment by SethTisue** [comment]
I tested locally by publishing 2.12.14-bin-2a60c31-SNAPSHOT locally and then in the community build doing `./narrow utest` (utest is one of the repos that was failing on JDK 16) and `version=2.12.14-bin-2a60c31-SNAPSHOT ./run.sh -l`, and lo and behold:

```
[info] Project utest-----------------------: SUCCESS (project rebuilt ok)
```

so that's promising.

**Comment by SethTisue** [comment]
full community build run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk16-integrate-community-build/16/ queued

**Review by dwijnand — APPROVED** [review]
LGTM and the community build went green too

**Comment by smarter** [comment]
This upgrade should also allow you to add entries to https://github.com/scala/scala/blob/74b0e304b5a44b30d14f24d4d3928208c2fa89d0/src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala#L73-L80 which I think is needed for`-target` to work with newer versions.

**Comment by SethTisue** [comment]
@smarter #9481

**Pull request merged**
