### PR TITLE
SI-6766 Create a continuations project in eclipse

### PR DESCRIPTION
**Pull request by JamesIry**
We're missing a continuations dependency when we try to build reflect
in eclipse which causes things to die horribly. This commit adds an
eclipse project for the library portion of continuations, makes
projects that depend on the scala-library also depend on
continuations-library, and adds another bullet to the eclipse readme to
turn on the continuations plugin.

This is a resubmit of https://github.com/scala/scala/pull/1715 to the 2.10.x branch

### CODE REVIEW

**Comment by adriaanm** [comment]
It's probably good to add a project-specific setting that enables the continuations (-Pcontinuations:enable) for the continuations-library project (cmd-i on that project / scala compiler / ...)

**Comment by adriaanm** [comment]
(it's fine to amend the commit and push -f)

**Comment by JamesIry** [comment]
Sorry. Didn't amend. I think it's a bad habit to amend pushed commits.

**Comment by adriaanm** [comment]
LGTM

**Comment by dragos** [comment]
For the record, I think it's a bad thing for the compiler to crash if the continuations.jar is not present on the classpath. Maybe the required types should be simply part of the standard library, if one can not live without the other.

**Comment by paulp** [comment]
Also for the record, I agree with iulian - although my preferred resolution would be breaking the connection between the standard library and continuations completely. But pulling whatever is needed into the standard library is certainly in second place, whereas having a poorly understood pseudo-dependency on the continuations lib which manifests as overt runtime failure, or worse, as covert runtime failure (I don't know if that's still a problem, where code compiled against the continuations lib would just run and do the wrong thing if the lib were missing at runtime) is a distant third.

**Pull request merged**
