### PR TITLE
the rest of the new bytecode emitter

### PR DESCRIPTION
**Pull request by magarciaEPFL**
Building upon the barebones bytecode emitter of https://github.com/scala/scala/pull/2620 , this PR adds features that GenASM supports and were missing so far in GenBCode, as well as net improvements over GenASM. In detail:
- only the main thread talks to typer, ASM-only operations are off-loaded to worker threads
- dead-code elimination and jump-chains collapsing are performed (btw, these rewritings are examples of ASM-level-only rewritings and don't require typer).

With the above, the capability gap with GenASM is closed. As a bonus, GenBCode doesn't exhibit bugs that GenASM still suffers from (see included tests for details).

review by @gkossakowski

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
Quoting from https://github.com/scala/scala/pull/2620#issuecomment-20295797

> Now let's get this baby tested and optimized.

Yea, exactly. If you want that then you'll love this this PR and the following ones.

Regarding "optimized",
- GenBCode (with this PR merged) is 30% faster than (GenICode + GenASM).

Regarding "tested", to recap, once more, here's the list of bugs fixed in the new backend and optimizer:
- [SI-5850](https://issues.scala-lang.org/browse/SI-5850) Inlined code shouldn't forget null-check on the original receiver
- [SI-5950](https://issues.scala-lang.org/browse/SI-5950) Inlining creates duplicates when anon-closure-class can't be eliminated after all
- [SI-6105](https://issues.scala-lang.org/browse/SI-6105) Conditional optimization: `true || x == true, false && y == false`
- [SI-6164](https://issues.scala-lang.org/browse/SI-6164) pipeline classfile building and writing (GenASM, GenBCode) 
- [SI-6191](https://issues.scala-lang.org/browse/SI-6191) spurious `SCOPE_EXIT` warnings
- [SI-6288](https://issues.scala-lang.org/browse/SI-6288) Wrong line number information in bytecode
- [SI-6546](https://issues.scala-lang.org/browse/SI-6546) Optimizer leaves references to classes that have been eliminated by inlining 
- [SI-6723](https://issues.scala-lang.org/browse/SI-6723) 2.10 regression: inliner warnings with Map literal and `-optimize` 
- [SI-6759](https://issues.scala-lang.org/browse/SI-6759) Seek clarification about necessary and sufficient conditions for inclusion in InnerClasses JVM attribute 
- [SI-7050](https://issues.scala-lang.org/browse/SI-7050) phase closelim is a mess 
- [SI-7182](https://issues.scala-lang.org/browse/SI-7182) Finally blocks are duplicated for each 'return' in a try/catch/finally 
- [SI-7407](https://issues.scala-lang.org/browse/SI-7407) return inside try + pattern-match inside finally causes VerifyError
- [SI-7518](https://issues.scala-lang.org/browse/SI-7518) inliner destroys line number information
- [SI-7540](https://issues.scala-lang.org/browse/SI-7540) Optimizer changes behavior when pattern matching Some(X) scrutinee when X's type assumed wrong
- [SI-7560](https://issues.scala-lang.org/browse/SI-7560) the ICode optimizer doesn't DCE-away trivial branches 
- [SI-7589](https://issues.scala-lang.org/browse/SI-7589) VerifyError under `-Yinline -Yinline-handlers`
- [SI-7607](https://issues.scala-lang.org/browse/SI-7607) optimizer changes behavior of IDIV, LDIV, IREM, LREM bytecode instructions when the result is dropped  
- all `ICodeReader` bugs (not used anymore)

**Comment by magarciaEPFL** [comment]
@gkossakowski , @adriaanm , @JamesIry

Don't miss the opportunity to have GenBCode in full in M4, merge this PR!

**Comment by gkossakowski** [comment]
FYI: I'm under the water with paperwork and other non-technical stuff so I don't think I'll have time to review it tomorrow, sorry. In any case, I'm not a fan of last-minute merges.

However, I've heard rumors that we are speeding up release process so we'll have another milestone in a month and not two so it should be ok.

If others can have a look at this PR before M4 and are willing to merge it then go for it.

**Comment by soc** [comment]
LGTM, and the documentation is pretty great, but some minor annoyances:
- Why `_root_.scala....`, `_root_.java....`?
- The headers are probably wrong (author/year)
- Why `scala/tools/asm/optimiz` but `scala/tools/nsc/backend/opt` (optimiz vs. opt)?

What's the reason behind your multi-threading approach? (E. g. "why not just use the ForkJoin framework?")

**Comment by magarciaEPFL** [comment]
> Why `_root_.scala....`, `_root_.java....` ?

It's just to be really-sure about what gets imported. Quoting from https://wiki.scala-lang.org/display/SYGN/Language+FAQs#LanguageFAQs-HowdoIimport 

> to make package names absolute, we can prefix them with root:
> `import _root_.scala.collection.mutable.Map`
> 
> Why `scala/tools/asm/optimiz but`scala/tools/nsc/backend/opt` (optimiz vs. opt)?

Both packages started their life in different situations. As to `asm/optimiz` it's slightly more accurate than other "opt"-prefixed words that might come to mind in connection with compilers.

> What's the reason behind your multi-threading approach? (E. g. "why not just use the ForkJoin framework?")

It's master-slave in both cases, of the most basic form. That division of labor is also shown clearly by the synchronization approach: all communication between master and slaves is mediated by the concurrent queues (fixed in number). It's as simple as it gets already.

**Comment by soc** [comment]
> It's just to be really-sure about what gets imported. Quoting from https://wiki.scala-lang.org/display/SYGN/Language+FAQs#LanguageFAQs-HowdoIimport

My impression is that this style has fallen out of favor and fixing the source of the issue (there shouldn't be one here) instead of working around it is now preferred. Maybe someone else can comment on that, but at least that's my impression of the current style of Scala.

Thanks for the explanations!

**Comment by magarciaEPFL** [comment]
Merging this PR will enable applying the refactoring described in
- [SI-7621](https://issues.scala-lang.org/browse/SI-7621) defensive code in bytecode emitter made redundant by existing fix to SI-5604

**Comment by magarciaEPFL** [comment]
In the meantime I've noticed that the new backend actually fixes a few more bugs in addition to those listed above:
- [SI-3882](https://issues.scala-lang.org/browse/SI-3882) Regression with -optimise: "Illegal index: 0 overlaps List((variable par1,LONG))"
- [SI-5286](https://issues.scala-lang.org/browse/SI-5286) avoid duplicating more than once a closure body when inlining a closure
- [SI-7524](https://issues.scala-lang.org/browse/SI-7524)  pathologically slow compilation time with -optimize and named/default arguments

**Comment by magarciaEPFL** [comment]
Now that the announcement [1] in scala-user mentions GenBCode is available in M4, it would be great if this PR were merged.

(as you know, only the minimally working subset of the bytecode emitter is included in M4, users trying out that version will arrive to a sub-optimal impression about GenBCode's capabilities, thanks guys).

[1] https://groups.google.com/forum/#!topic/scala-user/MxBFrqacLhQ

**Comment by adriaanm** [comment]
Yep, note that the release notes mention this PR as pending for the next milestone: https://github.com/scala/scala/releases/tag/v2.11.0-M4

**Comment by magarciaEPFL** [comment]
Just to dispel any doubt, all of the following 
- new bytecode emitter
- Level 1 of the new optimizer (intra-method optimizations)
- method inlining

are completely independent from the late-closure-classes vs. lifted-lambda-bodies business. No need to wait for that! 

Regarding closure inlining, it can be easily adapted to whatever approach is finally chosen to emit anon-closures late in the pipeline.

**Comment by gkossakowski** [comment]
Ok. I finally had time to skim through this PR. I have couple of questions:
1. Why part of the optimizer code in our fork of asm library? I believe we want to keep source code in `src/asm` to be a pristine copy of asm source code modulo package renamings
2. You listed impressive number of tickets the new backend fixes, how many of those issues listed above are covered by automatic tests so we are sure to not regress over time?
3. The tests included in the PR look nice but I'm wondering if it would be possible to have true unit tests which exercise your classes only in isolation from the rest of the compiler?

BTW. Review of this PR is not hold by parallel work of @JamesIry on delayed lambda translation. It's just big PR so it requires significant time window that I struggled to find in last few weeks. I dedicated time to the review this week so we can iterate more quickly now.

**Comment by adriaanm** [comment]
In addition to detecting inevitable regressions, tests aid the review process and code understanding in general.
GitHub says "Showing 24 changed files with 1,863 additions and 78 deletions.", and I count 5 tests.
That's a good start, but I'm sure there's more functionality in here that could be exercised by a test.

**Comment by adriaanm** [comment]
Also, as @gkossakowski points out, src/asm is not intended to be a fork of asm, it's a poor-man's namespaced (shaded) version of asm. Maybe it's time to spin it off to a separate project ('asm-optimizer'?) and have scalac depend on it as a true dependency. We will not, however, fork asm in this repository. That's the opposite of the direction the rest of the project is going.

**Comment by magarciaEPFL** [comment]
> Why part of the optimizer code in our fork of asm library?
> I believe we want to keep source code in src/asm to be a pristine copy of asm source code modulo package renamings

Part of the optimizer code now lives in a dedicated package within the asm directory because:
- it builds upon the ASM library
- the new optimizer is part of the compiler, thus it can't go into a separate project.

Additionally, a few additions are made to the ASM (non-optimizer) files proper: two getters are added, a class was made public. Those changes aim at simplifying the usage of ASM, are extremely easy to maintain (for example) once a new version of the ASM library comes along. First, because there are no drastic refactorings in ASM across versions (the JVM spec doesn't change that much); and second because any omission to re-apply our additions (in the example, getters) will be detected at compile time.

> You listed impressive number of tickets the new backend fixes,
> how many of those issues listed above are covered by automatic tests so we are sure to not regress over time?

The list of all bugs fixed applies to the new backend as a whole. For this PR, the functionality being added is tested. To help with code review (and in the future, maintenance) besides tests this PR includes precise, complete technical documentation, something sorely missing in the previous backend and optimizer.

> The tests included in the PR look nice but I'm wondering if it would be possible
> to have true unit tests which exercise your classes only in isolation from the rest of the compiler?

The functionality added in this PR is correct, and it is being tested in the context of the compiler which is a more realistic (and demanding) environment than other forms of testing. I don't see any shortcoming there.

**Comment by soc** [comment]
@magarciaEPFL I largely agree with your reasoning regarding tests, but maybe it helps to have a look at the issues which are a) fixed by your backend and b) have reproductions attached.

Converting these reproductions from the ticket to tests and adding them to this PR might make more people happy which are currently concerned about test coverage.

**Comment by gkossakowski** [comment]
> Part of the optimizer code now lives in a dedicated package within the asm directory because:
> - it builds upon the ASM library
> - the new optimizer is part of the compiler, thus it can't go into a separate project.
> 
> Additionally, a few additions are made to the ASM (non-optimizer) files proper: two getters are added, a class was made public. Those changes aim at simplifying the usage of ASM, are extremely easy to maintain (for example) once a new version of the ASM library comes along. First, because there are no drastic refactorings in ASM across versions (the JVM spec doesn't change that much); and second because any omission to re-apply our additions (in the example, getters) will be detected at compile time.

As @adriaanm mentioned we want to fork less of our dependencies not more. If your optimizations build _upon_ ASM then I see no reason for that code to be _part_ of ASM. Your optimizations should just depend on ASM.

Also, did you try to submit your small changes to existing code back to ASM maintainers? I think it makes sense to merge them upstream so we can get rid of ASM sources from Scala repo completely (eventually). Maintaining local modifications is a step in the opposite direction.

When it comes to testing you need both:
- testing in context of compiler; those are functional or integration tests
- unit tests which make a contract for the component in _isolation_ explicit and automatically tested

The second kind is very important for numerous reasons. It makes the job for the next guy maintaining the code much easier because he can learn about component's design from unit tests and easily verify if his changes are adhering component's contract. If they don't unit tests provide very direct feedback. Integration tests provide much less direct feedback because they are less specific; they are testing integration with the rest of components.

I'd really like to see some real unit tests for functionality that is being submitted here.

**Comment by magarciaEPFL** [comment]
@soc I guess there's no disagreement on adding tests but probably a misunderstanding. Of the list of bugfixes that I included at the top of this PR, I can't add tests for each of them because not all of the commits addressing those bugs are part of this PR. Those commits will be part of upcoming PRs.

**Comment by magarciaEPFL** [comment]
@gkossakowski 

> Also, did you try to submit your small changes to existing code back to ASM maintainers?
> I think it makes sense to merge them upstream so we can get rid of ASM sources
> from Scala repo completely (eventually). Maintaining local modifications is a step in the opposite direction.

Just to clarify your requirement on this PR: are you saying that we should wait until the ASM maintainers accept our improvements, before we can benefit from them in our compiler? I'm asking because that may well never happen, no matter how useful our improvements. As you know, ASM favors primarily small code size, specifically catering for the embedded market. The field of optimization clearly falls under user-level extensions, and it won't (ever) be part of the ASM framework proper.

That leaves the getters being added to ASM proper. That seems nowhere near the serious maintenance hurdle that "going in the wrong direction" implies. If one understands how ASM works then a few extra getters are the least of one's troubles.

**Comment by magarciaEPFL** [comment]
Regarding the discussion on unit tests vs integration tests. Let's take a concrete example: https://github.com/magarciaEPFL/scala/commit/0e2bb9bacc384e17d090e7c18152b36d42427f5c

That's the test for dead-code elimination. Following your criteria, it should:
1. make a contract for the component in isolation explicit
2. learn about component's design
3. provide very direct feedback

Which of the criteria above isn't met by that test?

**Comment by adriaanm** [comment]
Changing anything under src/asm is not acceptable under any circumstances except for an urgent critical bug, with a PR submitted upstream so we can revert it as soon as it's fixed there.

The recent change I was referring to was moving to the official jline. Over the years, our fork had developed fixes that were replicated (differently) in the main repo, some weren't, etc. etc. It's a huge maintenance burden and a liability that we cannot afford.

The only acceptable changes to src/asm are:
- removing it and namespacing/shading jars resolved through maven (what we should've done in the first place)
- merging from upstream.

For your back-end, I suggest you either work with vanilla ASM or fork it somewhere and publish jars. I'm fine depending on it through maven. We're also happy to provide support in getting this set up on jenkins etc.

**Comment by magarciaEPFL** [comment]
@adriaanm Unless someone else chimes in, I'll assume that's the official position of Typesafe regarding the ASM library (in effect saying: there's no in-house maintainer for ASM).

**Comment by adriaanm** [comment]
Yes. I am the official Typesafe position when it comes to Scala.

**Comment by gkossakowski** [comment]
> Regarding the discussion on unit tests vs integration tests. Let's take a concrete example: magarciaEPFL@0e2bb9b
> 
> That's the test for dead-code elimination. Following your criteria, it should:
> 1. make a contract for the component in isolation explicit
> 2. learn about component's design
> 3. provide very direct feedback
> 
> Which of the criteria above isn't met by that test?

All of them actually.

If you are testing dce which is about making sure that some code is eliminated you are counting NOPs? You say in the test that if you change a flag it'll be full of NOPs but the connection between DCE and NOPs is not clear.

Also, imagine that we have some earlier phase (working on trees) that does some very trivial DCE for simple cases like:

``` scala
def foo = { return 42; ... }
```

so optimizer never even sees deadcode anymore. Your test would pass but your dce code wouldn't be even exercised anymore. Now, imagine that somebody else comes along and breaks DCE's logic. It goes undetected because the earlier phase is getting rid of dead code in simple cases.

Half a year later yet another person refactors the earlier phase to not do DCE because optimizer is supposed to do it and dead code after earlier phase is needed for, for example, issuing warnings. Now, your test will break but it'll break because of the regression introduced a half year before. Therefore your test is not providing a very direct feedback.

That kind of scenarios happen all the time in Scala compiler and we should be dedicated to taming them. I believe that this should be everybody's responsibility at Scala team and people contributing to Scala.

**Comment by retronym** [comment]
The review comments about `src/asm` highlight a real issue but perhaps could be clearer about what steps are expected. Would this be satisfactory?
1. relocate `scala.tools.asm.optimiz._` to `scala.tools.nsc.backend.optimiz`, under `src/compiler`
2. Add a README to src/asm to document the small number of local changes made from the upstream (e.g. making MethodVisitor public), with links to pull requests or tickets against the official ASM repository. 

I think there is a place for this sort of temporary, documented local changes if the delay in upstream changes is measured in months or the alternative workaround is the copy/paste swathes of code into our code base.

With regards to testing compiler phases in isolation, one approach that might provide decent bang-for-buck would be a style of partest test that diffs the Textified ASM bytecode before/after the phase in question, and compares that against a checkfile.

**Comment by adriaanm** [comment]
@retronym, if there is no way around it, I'm willing to accept temporary deviations, but only if the upstream maintainers have already agreed in principle to merge the required changes. We should be able to "rebase" on upstream as soon as it changes. Synchronization is of course the responsibility of whoever requires the deviation.

**Comment by magarciaEPFL** [comment]
I can't reproduce the build failures. What I see is:
- check out master as of https://github.com/scala/scala/commit/4c62f7db6f3913eedd92d85daf8f631149cc97b2
- apply this PR
- build nightly

Everything works fine.

**Pull request closed without merging**
