### PR TITLE
Deprecate unicode arrows `⇒`, `←` and `→`

### LINKED ISSUE #585: Deprecate spec-defined and standard-library-defined unicode operators (⇒, ←, →)
From [the spec](https://www.scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html):

> The Unicode operators \u21D2 ‘⇒’ and \u2190 ‘←’, which have the ASCII equivalents => and <-, are also reserved.

And from the [standard library](https://github.com/scala/scala/blob/cac6383e6658dc5956540b76b9b46c3b664774ac/src/library/scala/Predef.scala#L249):
```scala
  def →[B](y: B): Tuple2[A, B] = ->(y)
```

While they're very cute, they're all likely to confuse users for very little benefits. And people who like symbols can simply use a coding font with special ligatures such as [Fira Pro](https://github.com/tonsky/FiraCode) which does a much better job at solving this problem.

(It's also worth noting that → in particular is problematic because it doesn't have the same associativity as `->`: https://github.com/scala/bug/issues/11210)

### LINKED ISSUE #11210: Priorities of arrow operators variants
There are different priorities for two variants of arrow operators:
```
$ scala
Welcome to Scala 2.12.7 (OpenJDK 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> "a" -> "b" -> "c"
res0: ((String, String), String) = ((a,b),c)

scala> "a" → "b" → "c"
res1: ((String, String), String) = ((a,b),c)

scala> "a" → "b" -> "c"
res2: ((String, String), String) = ((a,b),c)

scala> "a" -> "b" → "c"
res3: (String, (String, String)) = (a,(b,c))

scala> "a" + "b" -> "c"
res4: (String, String) = (ab,c)

scala> "a" + "b" → "c"
res5: String = a(b,c)
```
Unicode arrow "→" has higher priority then "->". Moreover there are some operators that have priority higher than "->" and lower than "→". It was unexpected for me when I got a broken code after replacement "->" with "→".

### PR DESCRIPTION
**Pull request by smarter**
Fixes scala/scala-dev#585
Fixes https://github.com/scala/bug/issues/11210

### CODE REVIEW

**Comment by som-snytt** [comment]
More like :cupid: an arrow through the heart.

**Comment by He-Pin** [comment]
I could only rely on the formatter to help me input these arrows.

**Comment by som-snytt** [comment]
Will we ever get the arrows back as operator characters? Page one of the spec should clarify.

**Comment by SethTisue** [comment]
I'm in favor, because of the precedence considerations (https://github.com/scala/bug/issues/11210). also more generally it just seems better to me to not go the Unicode-symbol path at all, rather than maybe have it piecemeal here and there for a few things

any other @scala/committers opinions?

**Review by dwijnand — APPROVED** [review]
LGTM

**Comment by olafurpg** [comment]
I agree https://github.com/scala/bug/issues/11210 is a good reason to deprecate unicode arrows but want to note that unicode arrows are widely used (it was a heavily requested Scalafmt feature). Scalafmt supports rewriting unicode to ascii and vice-versa. If unicode arrows are deprecated in the language we will likely remove the option to go to unicode and by default rewrite unicode into ascii.

**Comment by adriaanm** [comment]
Yeah, I think we should discuss more widely. I’ve also seen this in the
Akka code base quite a bit.

**Comment by dwijnand** [comment]
The Akka Team's fine with losing them.  🙂

**Comment by hrhino** [comment]
I've always thought they were kinda cute, and generally harmless. The precedence bug puts the lie to harmlessness, though, so I'm okay with dropping them and relying on my fancy ligature font.

**Comment by NthPortal** [comment]
I'm in favour of removing them

**Comment by mdedetrich** [comment]
Also in favor of removing them, use font-ligatures (which are now very widely supported in basically every editor) if you want these symbols

**Comment by smarter** [comment]
Rebasing and merging since there appears to be consensus.

**Comment by SethTisue** [comment]
> Will we ever get the arrows back as operator characters? Page one of the spec should clarify

I think that could happen at the time of actual removal

**Review by SethTisue — APPROVED** [review]

**Comment by retronym** [comment]
IntelliJ IDEA now ships with JetBrains Mono, a programming font with great ligature support for constructs used in Scala code. It will be the default font in the upcoming IDE release. https://www.jetbrains.com/lp/mono/

**Pull request merged**
