### PR TITLE
SI-6441 Cull scala.swing.SwingWorker

### PR DESCRIPTION
**Pull request by retronym**
It appears to do nothing much at all, refers to the now-deprecated
scala.actor package, and has a name clash with an important class
from java.swing.

Note that the POM for scala-swing does not declare the dependency.

The final nail in the coffin is it aides and abets the crash in
the crash in SI-6440.

Obviously removal of a class isn't binary compatible with 2.10.0.
Things could play out a few ways:
- RC3 is required for some other reason, and this change is
  admitted to 2.10.0
- Or, an exeption to the binary/source compatibility policy
  is made for this class
- Or, this is deferred until 2.11.0, or at least until the
  spin-off of scala-swing to a standalone repo.

For now, I'll submit this to 2.10.x for now and leave those
choices up to the release managers.

Review by @ingoem, @jsuereth

### CODE REVIEW

**Comment by retronym** [comment]
:cat: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/664/console

**Comment by paulp** [comment]
Looks woooonderful to me.

**Comment by jsuereth** [comment]
I love the idea, but perhaps for now I fix the swing pom, and we just deprecate the classes.   I don't think our policy lets us up and remove public classes without a deprecation period.

**Comment by retronym** [comment]
Perhaps it's not obvious at first glance, but `SwingActor` was already commented out.

So all we are discussing is the removal of one undocumented class that does nothing. Can we take this to the board of appeals?

``` patch
--- a/src/swing/scala/swing/SwingWorker.scala
+++ /dev/null
@@ -1,21 +0,0 @@
-package scala.swing
-
-import scala.actors._
-
-object SwingWorker {
-
-}
-
-abstract class SwingWorker extends Actor {
-  def queue() {
-
-  }
-
-  def done() {
-
-  }
-
-  private var _cancelled = false
-  def cancelled: Boolean = _cancelled
-  def cancelled_=(b: Boolean) { _cancelled = b }
-}
\ No newline at end of file
-- 
```

**Comment by som-snytt** [comment]
I commented on the ticket that my first Scala toy included a SwingWorker; I don't know that it had any magical properties, or probably I was porting a Java toy that used it; I do remember marvelling at the complicated event merge.  Anyway, is this another case where Swing guys write their own if you don't supply it, so there are dozens of exemplars in the wild?  I also remember finding this class and noting that it didn't even tell me what it would do if it were implemented.

**Comment by retronym** [comment]
@jsuereth Did you have a chance to reconsider? We should take a decision one way or the other. Bear in mind the class we propose to remove has no discernable behaviour or purpose.

**Comment by adriaanm** [comment]
Sorry about missing this in RC3, 4 _and_ 5. Maybe we need some kind of protocol that counteracts my forgetfulness -- ticket perhaps? I guess now the fixBy should be 2.11.0-M1.

**Comment by retronym** [comment]
Even if we remove it in 2.11.0, we're still breaking our deprecation policy. Just saying...

**Comment by retronym** [comment]
One solution might be to deprecate it and move it to `scala-actors.jar`.

**Pull request closed without merging**
