### PR TITLE
Revert "SI-8315 Better debugging facility for ICode"

### PR DESCRIPTION
**Pull request by adriaanm**
This reverts commit 0561dd084b5f3c2678eb032a40b85cb25bb6d589.

When the windows nightly broke, git bisect pointed its unwavering finger at this poor soul.

Build passes again after the revert: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/39/console

I have no idea why, but the machines don't lie (and I don't have time right now to dig deeper).
Ok, if I had to guess, I'd say the longer filenames for the .icode files confused windows somehow.

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @gkossakowski

**Comment by adriaanm** [comment]
See https://issues.scala-lang.org/browse/SI-7773

**Comment by gkossakowski** [comment]
LGTM

I'm sad to let 0561dd0 go because it helped me in my recent debugging session of our beloved (old) optimizer. However, I agree that machines do not lie. To be looked at later in 2.11.x cycle.

**Comment by adriaanm** [comment]
The old behaviour is still available under -Ydebug. Whyyyy debug?

**Pull request merged**
