### PR TITLE
SI-6895 Test cases to explain the limitations in tcpoly inference

### PR DESCRIPTION
**Pull request by retronym**
And an improvement to error messages.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by retronym** [comment]
Spurious failure

```
[quick.compiler] /home/jenkins/workspace/scala-2.11.x-validate-publish-core@3/src/compiler/scala/tools/nsc/typechecker/AnalyzerPlugins.scala:372: warning: match may not be exhaustive.
[quick.compiler] It would fail on the following input: List(_)
[quick.compiler]       results.flatMap { case (p, Some(result)) => Some((p, result)); case _ => None } match {
[quick.compiler]                       ^
[quick.compiler] /home/jenkins/workspace/scala-2.11.x-validate-publish-core@3/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:868: warning: match may not be exhaustive.
[quick.compiler] It would fail on the following input: List(_)
[quick.compiler]         seenTypes(i) match {
[quick.compiler]                  ^
[quick.compiler] error: symbol value x6#805243 does not exist in scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$BoundTree.nextStep, which contains locals value o38#805305,value o36#805299,value o34#805297,value x#805287,value x#805282,value x1#805185.
```

**Comment by smarter** [comment]
> SI-6985 ...

It's actually SI-6895: https://issues.scala-lang.org/browse/SI-6895 :)

**Comment by retronym** [comment]
@smarter oops, fixed.

**Comment by retronym** [comment]
Build is green now.

**Comment by adriaanm** [comment]
LGTM

**Comment by Blaisorblade** [comment]
Was this intended to close https://issues.scala-lang.org/browse/SI-2712, as just auto-done by JIRA, maybe because "SI-2712" (but not SI-2712) is mentioned in the commit message?
I'm guessing that was unintentional, and JIRA-GitHub integration is overly eager.

**Comment by adriaanm** [comment]
Yeah, we should probably just turn this off.

**Comment by eed3si9n** [comment]
Got super excited until I saw the commits though.

**Comment by adriaanm** [comment]
Haha, sorry all, that ticket will remain open for the foreseeable future. :crying_cat_face:

**Comment by adriaanm** [comment]
It would be nice if we could figure out how to configure Jira so that it only closes tickets when they are mentioned as the first word of the title, and interprets everything else as mentions. We'll probably have Scabot do this at some point.

**Comment by Blaisorblade** [comment]
This is a reunion of Scala aficionados! So I tried to help celebrate the most loved Scala bug.



Redirect OT reactions onto https://twitter.com/Blaisorblade/status/616020901776203776 :wink:

**Pull request merged**
