### PR TITLE
SI-5933 do the new patmat translation for scaladoc

### PR DESCRIPTION
**Pull request by adriaanm**
especially because it benefits from nicer type inference for partial functions

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @VladUreche /cc @retronym

**Comment by VladUreche** [comment]
I can't say I fully understand the benefits of this change, but I can see two potential pitfalls:
- we need to check if there's any interaction with the default arguments printer, which extracts the information from the tree -- what if one of the default parameters is a pattern match? We'll get the expanded code in the scaladoc page instead of the pattern match, right?
- we should also be very careful about performance -- scaladoc is now running very close to 1.5G, so if the tree expansion takes anything more than 50M for the library+reflection, we shouldn't do it.

**Comment by adriaanm** [comment]
The benefits are documented by the issue and the commit message: the new way of synthesizing partial function implementations for matches has better type inference.
- yes, you'd get the expanded tree in your default value, but writing a pattern match as a default -- really?
- scaladoc performance: that surely is a problem, but I don't see how this fix would tip the scale... the checkin tests passed, so apparently the memory budget isn't exhausted yet -- or what does that '1.5G' refer to?

**Comment by adriaanm** [comment]
what if you specify a block with a lazy val, or a while loop for a default? all these will look pretty weird if you simply print the tree after type checking; by the way, is macro expansion also disabled for scaladoc?

**Comment by VladUreche** [comment]
Good point! I should check these two cases.

**Comment by jsuereth** [comment]
Um, do we have a LGTM for this or not?

**Comment by VladUreche** [comment]
Sorry Josh, not yet, that's my fault. I need to check how this interacts with displaying default parameter trees, and I didn't get to that yet. I'll have an answer by Sunday evening, I promise.

**Comment by adriaanm** [comment]
so, Vlad, can we pull the trigger on this one please?

**Comment by VladUreche** [comment]
I'll look into it tonight and also provide a test for it.

**Comment by VladUreche** [comment]
Resubmitted as https://github.com/scala/scala/pull/1084

**Pull request closed without merging**
