### PR TITLE
Fixed instrumented.jar and scalacheck.jar location

### PR DESCRIPTION
**Pull request by khernyo**
Depending on the file order in the directory, PathSettings.srcSpecLib
could end up as "instrumented.jar.desired.sha1" instead of "instrumented.jar"
which would cause all the specialized tests to fail.

The same goes for scalacheck.jar

### CODE REVIEW

**Comment by khernyo** [comment]
I just realized that lib could be a directory also... Fixing up

**Comment by dcsobral** [comment]
Does this fix specialized tests? If so, I'm forever grateful to you! Also, I'd like some classes in how to track down this kind of problem. :-)

**Comment by khernyo** [comment]
Yes, this fixes those tests, but currently it finds the first file or directory named "instrumented_.jar". I figured it would match better the original behavior if it would look for a directory named "instrumented_" or a file named "instrumented*.jar". I think, giving priority to the directory would also make sense. So, this is what I'm gonna do now.

To be honest, I can't remember how I found this bug. :)

**Comment by khernyo** [comment]
I just realized that the original didn't accept directories, only files, just like this fix, so I'm reopening.

**Pull request merged**
