### PR TITLE
Add java varargs forwarders to mirror classes

### PR DESCRIPTION
**Pull request by lrytz**
They were accidentally dropped in #6531.
Fixes scala/bug#11057.

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
@lrytz can you add this test to prevent further regressions: https://github.com/MasseGuillaume/scala/commit/d6f71e74226f15f27747b5cb08c0da20e7829832 ?

**Comment by lrytz** [comment]
I updated test/files/jvm/varargs instead as regression test

**Comment by MasseGuillaume** [comment]
Ahh I see, it's only because it comes from an object that the bytecode is not generated.

**Comment by SethTisue** [comment]
@retronym would be good to get this merged if we can, since it's blocking Akka on 2.13

**Comment by SethTisue** [comment]
ping @retronym

**Review by retronym — APPROVED** [review]

**Pull request merged**
