### PR TITLE
StringBuilder append,delete,insert are this.type

### LINKED ISSUE #12608: StringBuilder operations return StringBuilder instead of this.type
## Reproduction steps

```scala
[warn] .../scala/src/compiler/scala/reflect/quasiquotes/Placeholders.scala:37:16: unused value
[warn]       sb.append(value)
[warn]                ^
```

## Problem

`-Wnonunit-statement` warns unnecessarily because `append` is not defined with result `this.type`, unlike `Growable` et al.

### PR DESCRIPTION
**Pull request by som-snytt**
There is probably more to the story.

Fixes scala/bug#12608

### CODE REVIEW

**Comment by som-snytt** [comment]
Travis
```
sdk: command not found
no matching JDK found: 8
```

**Comment by lrytz** [comment]
LGTM. The

> method with dependent type cannot be converted to function value

observation is interesting though. Is it an implementation restriction, or an intended restriction? Scala 3 widens dependent function types

```scala
scala> val f: (x: String) => x.type = x => x
val f: (x: String) => x.type = Lambda$1287/0x0000000800554410@40cf6254

scala> val g: String => String = f
val g: String => String = Lambda$1287/0x0000000800554410@40cf6254
```

**Comment by som-snytt** [comment]
I undrafted the PR which also asked Nth for a review. That wasn't intentional, but who wouldn't like a review from Nth?

**Review by dwijnand — APPROVED** [review]

**Comment by som-snytt** [comment]
@lrytz `typedEtaExpansion` says
```
if (tree.tpe.isDependentMethodType) DependentMethodTpeConversionToFunctionError(tree, tree.tpe) // TODO: support this
```

**Pull request merged**
