### PR TITLE
Pattern matcher: extractors become name-based.

### PR DESCRIPTION
**Pull request by paulp**
An extractor is no longer required to return Option[T], and
can instead return anything which directly contains methods
with these signatures:

```
  def isEmpty: Boolean
  def get: T
```

If the type of get contains methods with the names of
product selectors (_1, _2, etc.) then the type and arity
of the extraction is inferred from the type of get. If
it does not contain _1, then it is a single value
extractor analogous like Option[T].

This has significant benefits and opens new territory:
- an AnyVal based Option-like class can be used which
  leverages null as None, and no allocations are necessary
- for primitive types the benefit is squared (see below)
- the performance difference between case classes and
  extractors should now be largely eliminated
- this in turn allows us to recapture great swaths of
  memory which are currently squandered (e.g. every
  TypeRef has fields for pre and args, even though these
  are more than half the time NoPrefix and Nil)

Here is a primitive example:

```
  final class OptInt(val x: Int) extends AnyVal {
    def get: Int = x
    def isEmpty = x == Int.MinValue // or whatever is appropriate
  }
  // This boxes TWICE: Int => Integer => Some(Integer)
  def unapply(x: Int): Option[Int]
  // This boxes NONCE
  def unapply(x: Int): OptInt
```

As a multi-value example, after I contribute some methods to TypeRef:

```
  def isEmpty = false
  def get     = this
  def _1      = pre
  def _2      = sym
  def _3      = args
```

Then its extractor becomes

```
  def unapply(x: TypeRef) = x
```

Which, it need hardly be said, involves no allocations.

### CODE REVIEW

**Comment by paulp** [comment]
I didn't want to mess with #2835 because it has those green check marks. This commit ends up at almost exactly the same place, but with much more granularity in the key commit.

```
was: 14 files changed, 1011 insertions(+), 806 deletions(-)
now: 9 files changed, 333 insertions(+), 419 deletions(-)
```

The only change in the end result is a bugfix which I found trying to compile scalariform involving nested bindings like b1 @ (b2: Foo). I couldn't reproduce the overloading issue seen in jenkins, but maybe somehow it will turn out to be related to that fix.

**Comment by paulp** [comment]
@dragos wasn't what I thought. Hopefully a905d0e will involve real-passing instead of faux-passing.

**Comment by paulp** [comment]
For ease of reference:

```
[INFO] org.scala-ide.sdt.build ........................... SUCCESS [0.523s]
[INFO] org.scala-ide.sdt.aspects ......................... SUCCESS [5.057s]
[INFO] org.scala-ide.sdt.core ............................ SUCCESS [52.015s]
[INFO] org.scala-ide.sdt.core.tests ...................... SUCCESS [2:06.068s]
[INFO] org.scala-ide.sdt.spy ............................. SUCCESS [4.982s]
[INFO] org.scala-ide.sdt.debug ........................... SUCCESS [14.482s]
[INFO] org.scala-ide.sdt.debug.tests ..................... SUCCESS [58.897s]
[INFO] org.scala-ide.sdt.weaving.feature ................. SUCCESS [0.127s]
[INFO] org.scala-ide.sdt.feature ......................... SUCCESS [0.135s]
[INFO] org.scala-ide.sdt.dev.feature ..................... SUCCESS [0.133s]
[INFO] org.scala-ide.sdt.source.feature .................. SUCCESS [0.079s]
[INFO] org.scala-ide.sdt.update-site ..................... SUCCESS [3.463s]
```

**Comment by paulp** [comment]
All those happy successes are after a905d0e. After 6d77da3 it went back to failing, but I can't for the life of me make any sense of the six megabytes of console output. Whether the failure is spurious or not, I'd think it would be better if it would not abandon ship at the first sniff of something wrong. I'm just going to assume it's spurious unless someone tells me otherwise.

```
 [INFO] org.scala-ide.sdt.build ........................... SUCCESS [0.479s]
 [INFO] org.scala-ide.sdt.aspects ......................... SUCCESS [4.516s]
 [INFO] org.scala-ide.sdt.core ............................ SUCCESS [43.115s]
 [INFO] org.scala-ide.sdt.core.tests ...................... FAILURE [1:57.485s]
 [INFO] org.scala-ide.sdt.spy ............................. SKIPPED
 [INFO] org.scala-ide.sdt.debug ........................... SKIPPED
 [INFO] org.scala-ide.sdt.debug.tests ..................... SKIPPED
 [INFO] org.scala-ide.sdt.weaving.feature ................. SKIPPED
 [INFO] org.scala-ide.sdt.feature ......................... SKIPPED
 [INFO] org.scala-ide.sdt.dev.feature ..................... SKIPPED
 [INFO] org.scala-ide.sdt.source.feature .................. SKIPPED
 [INFO] org.scala-ide.sdt.update-site ..................... SKIPPED
```

**Comment by dragos** [comment]
@paulp I'm going to have a look.

**Comment by dragos** [comment]
@paulp That failure is spurious.

**Comment by adriaanm** [comment]
@paulp, thanks for splitting up the PR further -- LEG(TM)

**Comment by adriaanm** [comment]
(The 'E' reminded me of another adjective. Epic.)

**Comment by adriaanm** [comment]
LGTM -- let's merge this tomorrow-Tuesday

**Comment by paulp** [comment]
I'm resolving the merge conflict. I'm not rebasing since I'll lose those 44 green checkmarks. Let me know if I should rebase anyway.

**Comment by adriaanm** [comment]
No, thanks for resolving the conflict. I was about to merge this PR, so I'll wait until 01f771e goes green to merge anything else.

**Comment by paulp** [comment]
@adriaanm it has gone to state "happy green", now initiating breath holding sequence.

**Comment by adriaanm** [comment]
Hope you haven't turned blue yet. Stay happy green!

**Comment by adriaanm** [comment]
I was doing some quick local checking. Will hit merge button in 5 4

**Comment by adriaanm** [comment]
:fireworks:

**Comment by paulp** [comment]
> Hope you haven't turned blue yet. Stay happy green!

https://wiki.jenkins-ci.org/display/JENKINS/Green+Balls

**Comment by adriaanm** [comment]
The green is a bit... radio-active, but otherwise this could very well turn out to be my favorite jenkins plugin. (Not the hardest contest.)

**Comment by SethTisue** [comment]
followup PR merged for 2.13: https://github.com/scala/scala/pull/7068

**Pull request merged**
