### PR TITLE
SI-5739 (bis) vals for subpatterns when -g:patmatvars

### PR DESCRIPTION
**Pull request by adriaanm**
To facilitate debugging pattern matches, we store the values for
sub-patterns of extractor (synthetic or user-defined) patterns when -g:patmatvars.
Normally we inline them directly unless compiling under -g:patmatvars

For soundness, SI-5158, SI-6070, we must always store the values of mutable case class fields.

We don't always do this since it may affect performance.
Also, the total cost in byte code size is about 1% for the compiler&stdlib
when run with -optimize and -g:patmatvars
(but see SI-6193: dead case class field accessor calls are not eliminated).

There were suspicions that emitting this many local variables may impact run-time performance
(it surely affects compiler performance) thus, I've decided to make these definitions opt-in.
Simply pass `-g:patmatvars` to scalac to facilitate debugging of pattern matches.

### CODE REVIEW

**Comment by jsuereth** [comment]
Review by?

**Comment by adriaanm** [comment]
still pondering whether we should actually do this, so no reviewer yet

**Comment by adriaanm** [comment]
I've thought about it and think we should hide this behind a flag as the deluge of local variables slows down the optimizer considerably.

review by @paulp /cc @odersky

**Comment by dotta** [comment]
This is relevant for the Scala IDE debugger, it would be good to get Luc's opinion (this was also discussed on scala-internals http://groups.google.com/group/scala-internals/browse_thread/thread/d38fdf2fcd74e038) \cc @skyluc

**Comment by adriaanm** [comment]
based on discussion during the scala meeting, predicating emission of local vals for subpats on absence of -optimize

PLS REBUILD ALL

**Comment by adriaanm** [comment]
fixed flags file so optimized and non-optimized invocations of partest behave consistently
(by adding -optimize to t4425.flags)

PLS REBUILD ALL

**Pull request merged**
