### PR TITLE
doc: fix README link

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by thefourtheye** [comment]
review by @SethTisue, @heathermiller, @dickwall, @janekdb

**Comment by SethTisue** [comment]
Looks like a little @adriaanm humor there

**Comment by thefourtheye** [comment]
I think it was introduced in https://github.com/scala/scala/commit/65599fc2a439c57bd05c9f432a37ce7b6954fc66 by @adriaanm. Looks like a typo to me. They wanted to remove the `not` following `README`, by pressing <kbd>Ctrl</kbd> + <kbd>H</kbd> three times, which is normally interpreted as backspace in most of the environments.

**Comment by adriaanm** [comment]
🎃  At least I wasn't trapped in vi, desperately trying to ESC. 👻

**Pull request merged**
