### PR TITLE
SI-8030 Restore thread safety to the parser

### PR DESCRIPTION
**Pull request by retronym**
In addition to the invariant "parsing doesn’t enter new symbols",
which was respected and tested in 760df9843a910d6, we also must
ensure that "parsing doesn't call Symbol#info".

That happend indirectly if we call `companionModule`.

This commit just converts the name of `class TupleN` to a term
name, rather than getting the name of its companion.

No test is included. This is tested upstream in:

```
https://jenkins.scala-ide.org:8496/jenkins/view/Memory%20Leak%20Tests/job/scalac-memory-leaks-test-2.11.0/
```

Review by @densh / @dragos

### CODE REVIEW

**Comment by dragos** [comment]
LGTM. Thanks for the quick turnaround!

**Comment by densh** [comment]
If we fix it this way I'd love see a test that checks that checks this property holds:

``` scala
TupleClass.seq.foreach { tc => assert(tc.name.toTermName == tc.companionModule.name) }
```

I understand that this invariant is unlikely to break but it would be great to have a test just in case.
Another alternative would be just to add companionModules to the list of pre-initialized symbols.

**Comment by retronym** [comment]
It's a diligent idea, but companions are defined by having the same name, so I think its not really needed here.

**Comment by densh** [comment]
I see, was just thinking that Tuples are special case that might be represented differently.

LGTM

**Pull request merged**
