### PR TITLE
SI-8024 Fix inaccurate message on overloaded ambiguous ident

### PR DESCRIPTION
**Pull request by retronym**
More details in the commit messages.

Review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@8e23589
PLS REBUILD/pr-scala@fb0818b

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@a443bae

**Comment by retronym** [comment]
PLS REBUILD ALL:

Spurious breakage: Scalacheck failure in https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4784/console, on a commit that only adds a pending test:

```
[info] [info] ! Prop.within: Falsified after 22 passed tests.
[info] [info] > Labels of failing property: 
[info] [info] Timeout
[info] [info] > ARG_0: 100
[info] [info] > ARG_1: 10
```

**Comment by retronym** [comment]
And later: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4776/console

```
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.typesafe:typesafeDummy:war:1.0-SNAPSHOT: Could not find artifact com.typesafe.sbt:incremental-compiler:jar:0.13.0-on-2.11.0-b2b9cf4-SNAPSHOT-for-IDE-SNAPSHOT in pr-scala (http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
    ... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact com.typesafe.sbt:incremental-compiler:jar:0.13.0-on-2.11.0-b2b9cf4-SNAPSHOT-for-IDE-SNAPSHOT in pr-scala (http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
    ... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact com.typesafe.sbt:incremental-compiler:jar:0.13.0-on-2.11.0-b2b9cf4-SNAPSHOT-for-IDE-SNAPSHOT in pr-scala (http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
    ... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.typesafe.sbt:incremental-compiler:jar:0.13.0-on-2.11.0-b2b9cf4-SNAPSHOT-for-IDE-SNAPSHOT in pr-scala (http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots)
```

/cc @jsuereth

**Comment by adriaanm** [comment]
drad! you are the third person foiled by this error that isn't -- @skyluc, could we please filter it and produce some friendlier logging, like "artifact not found", rather than "OMG BUILD ERROR LOOK NO FURTHER"

@retronym, the log actually goes one:

```
>> Building Zinc using dbuild
>> Adding remote git repo git://github.com/typesafehub/sbt-builds-for-ide
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by adriaanm** [comment]
LGTM -- integration should be fixed by https://github.com/scala-ide/uber-build/pull/26, but since it was ok in later commits, merging to clear out PR queue a bit

**Pull request merged**
