### PR TITLE
fix a few string interpolation typos

### PR DESCRIPTION
**Pull request by gourlaysama**
The ones in scala-reflect were caught by Xlint (who knew building with
Xlint was actually useful...), the other was just luck.

That nice little `-Dscala.repl.vids` feature regressed in f56f9a3c, but
there was no test to catch that. So there is one now.

### CODE REVIEW

**Comment by gourlaysama** [comment]
Hmm, of course, having a hashcode in a check file was a bad idea. The test for `-Dscala.repl.vids` will have to go...

**Comment by som-snytt** [comment]
Quoting https://issues.scala-lang.org/browse/SI-7931, 

```
This is a reminder to consider what features are useful, tested and could be more useful.
```

**Comment by gourlaysama** [comment]
So there was a ticket for this...

This reminded me of [SI-7900](https://issues.scala-lang.org/browse/SI-7900) and the need for a thing that documents the REPL and its (many) bells and whistles...

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
