### PR TITLE
SI-8843 AbsFileCL acts like a CL

### PR DESCRIPTION
**Pull request by som-snytt**
Let the AbstractFileClassLoader override just the usual suspects.

Normal delegation behavior should ensue.

That's instead of overriding `getResourceAsStream`, which was intended
that "The repl classloader now works more like you'd expect a classloader to."
(Workaround for "Don't know how to construct an URL for something which exists
only in memory.")

Also override `findResources` so that `getResources` does the obvious thing,
namely, return one if `getResource` does.  (If `getResources.size > 1`, the others come
from parent/system loaders.)

The translating class loader for REPL only special-cases `foo.class`: as
a fallback, take `foo` as `$line42.$read$something$foo` and try that class file.
That's the use case for "works like you'd expect it to."

There was a previous fix to ensure `getResource` doesn't take a class name.
The convenience behavior, that `classBytes` takes either a class name or a resource
path ending in ".class", has been promoted to `ScalaClassLoader`.

Review by @retronym

### CODE REVIEW

**Comment by som-snytt** [comment]
The `:javap` command uses `translatePath`, so added a replacement method for use by `findAbstractFile`.

It's clear that the original intention was for `TranslatingClassLoader` to work uniformly, as the doc comment now explains:

```
$intp.classLoader classBytes "Bippy" or $intp.classLoader getResource "Bippy.class" just work.
```

**Comment by gkossakowski** [comment]
I'll try to review this one after late lunch.

**Comment by gkossakowski** [comment]
LGTM

**Comment by gkossakowski** [comment]
Thanks a bunch!

**Pull request merged**
