### PR TITLE
Assert that TypeVars with wildcard origins are not instantiated

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Comment by adriaanm** [comment]
@sethtisue can we get a round of community build over here?

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2402/

**Comment by joroKr21** [comment]
Looks like it didn't start properly:

> Error reading configuration file:
An exception occurred.
com.typesafe.config.ConfigException$Parse: configs/community.dbuild: 855: in value for key 'extra.commands': List should have ended with ] or had a comma, instead had token: ':' (if you want ':' to be part of a string value, then double-quote it)

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2412/

**Comment by joroKr21** [comment]
Looks good, I don't see any triggered assertion errors.

**Comment by joroKr21** [comment]
This was just for the community build and served its purpose.

**Pull request closed without merging**
