### PR TITLE
SI-8538 Test or example for Source.report

### PR DESCRIPTION
**Pull request by som-snytt**
It's possible to supply an arbitrary `Positioner` to a
custom `Source` that wants to override `report`.

This obviates the need to expose the deprecated `Position` class.

The default report method consumes the underlying iterator, which
is not desirable and produces unexpected results.

The expected outcome is that no one uses or extends the legacy
position handling code.

In 2.12, use a Reporter instead. Probably the source should be a `PositionReporter` so that a `Reporter` knows what position to report?

Review by @adriaanm , "a mild-mannered reporter"

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks! Could you incorporate the essence this example/test into BufferedSource's docs? The original ticket is unlikely to be addressed by a test since it's unlikely to be discovered by OP.

**Comment by som-snytt** [comment]
Sure, if you think that would be helpful.

I was thinking maybe `@deprecatedInheritance`. @adriaanm

**Comment by adriaanm** [comment]
Yes, locking it down would be even better.

**Comment by som-snytt** [comment]
@adriaanm It's impossible to tell, but I was joking about deprecation. I guess the truest words are said in jest.

**Comment by som-snytt** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Jenkins has broken down again. It looks like some config files were wiped
out on the EPFL side -- looking into it.

**Comment by som-snytt** [comment]
@kitteh Or not.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
