### PR TITLE
SI-7694 @uncheckedBounds, an opt-out from type bounds checking

### PR DESCRIPTION
**Pull request by retronym**
Synthetic defs introduced by transforms like named/default arguments,
ANF (in scala-async) often introduce a type tree (the tpt of the temporary)
that are based on the types of expressions. These types are scrutinized in
RefChecks to check that type parameter bounds are satisfied.

However, the type of the expression might be based on slack a LUB that
fails to capture constraints between type parameters.

This slackness is noted in `mergePrefixAndArgs`:

```
// Martin: I removed this, because incomplete. Not sure there is a
// good way to fix it. For the moment we just err on the conservative
// side, i.e. with a bound that is too high.
```

The synthesizer can now opt out of bounds by annotating the type as follows:

   val temp: (<expr.tpe> @uncheckedBounds) = expr

This facility is now used in named/default arguments for the temporaries
used for the reciever and arguments.

The annotation is hidden under scala.reflect.internal, rather than in
the more prominent scala.annotation.unchecked, to reflect the intention
that it should only be used in tree transformers.

Targetting 2.10.3 as this fix is needed by a customer.

**UPDATE** 

It occurred to me that we should be robust against running the 2.10.3 compiler with the 2.10.2 library, so I've split this PR into two commits. More details in their comments.

### CODE REVIEW

**Comment by retronym** [comment]
Closing while I assess the test failures.

**Comment by retronym** [comment]
```
/localhome/jenkins/c/workspace/pr-checkin-per-commit/build.xml:1522: Test suite finished with 3 cases failing:
/localhome/jenkins/c/workspace/pr-checkin-per-commit/test/files/neg/classmanifests_new_deprecations.scala [FAILED]
/localhome/jenkins/c/workspace/pr-checkin-per-commit/test/files/neg/t0513.scala [FAILED]
/localhome/jenkins/c/workspace/pr-checkin-per-commit/test/files/run/t4542.scala [FAILED]
```

**Comment by gkossakowski** [comment]
I'll make sure to get @adriaanm's attention next week. It might not closer to Thursday. From Monday to Wednesday we are busy lobbying for cool, new features in JVM at JVM Language Summit.

**Comment by soc** [comment]
@retronym Not sure if it LGTM, but it looks at least plausible to do it this way if fixing LUZ computation is too hard. (Do we have a ticket for that?)
@gkossakowski "lobbying for cool, new features in JVM at JVM Language Summit" hahaha, good joke. :-)

**Comment by adriaanm** [comment]
I'm sure I'll find a moment between talks. Please ping me to remind me.

**Comment by retronym** [comment]
Martin suggested a different approach: code generators (e.g. scala-async, named/default args) that synthesize type trees for based on potentially inferred types could annotate the types with `@uncheckedBounds`. RefChecks would eliminate the annotation but disable bound checking.

His worry was that even with the check for `currentOwner.isSynthetic` (which, BTW, might be stronger with `.isArtifact`), we'd omit checks that ought shouldn't be omitted.

This approach is a little unappealing given that it would require action from named args, scala-async, and any other macro that wants to be immune from this issue. That said, even under my proposal, macros would need to mark the enclosing symbol as SYNTHETIC, which is actually nigh-on-impossible for most macros.

**Comment by adriaanm** [comment]
Could we (ab)use `TypeTreeWithDeferredRefCheck` to customize checking?

**Comment by retronym** [comment]
@adriaanm 

I did look at that, but currently `TTWDRC` can't be used as `TTWNoBoundsCheck`.

``` scala
          case tpt@TypeTree() =>
            if(tpt.original != null) {
              tpt.original foreach {
                case dc@TypeTreeWithDeferredRefCheck() =>
                  transform(dc.check()) // #2416 -- only call transform to do refchecks, but discard results
                  // tpt has the right type if the deferred checks are ok
                case _ =>
              }
            }

            val existentialParams = new ListBuffer[Symbol]
            doTypeTraversal(tree) { // check all bounds, except those that are existential type parameters
              case ExistentialType(tparams, tpe) =>
                existentialParams ++= tparams
              case t: TypeRef =>
                checkTypeRef(deriveTypeWithWildcards(existentialParams.toList)(t), tree)
              case _ =>
            }
```

**Comment by adriaanm** [comment]
You're right, but it seems like a doable refactoring. Or at least not harder than adding an annotation. I'm weary of adding surface syntax for suppressing bounds checking.

**Comment by retronym** [comment]
@odersky suggested that the annotation could be just part of scala-compiler.jar so user code couldn't see it. It would be eliminated after refchecks, so we should get away with that.

**Comment by retronym** [comment]
I also suggested a Tree annotation.

**Comment by adriaanm** [comment]
Ok, if the annotation is hidden, maybe it makes more sense to go that route. Should we rather put it in reflect.internals?

**Comment by retronym** [comment]
Closing temporarily, back soon.

**Comment by adriaanm** [comment]
```
   [mima]             {
     [mima]                 matchName="scala.reflect.internal.Types.uncheckedBounds"
     [mima]                 problemName=MissingMethodProblem
     [mima]             },
     [mima]             {
     [mima]                 matchName="scala.reflect.internal.SymbolTable.uncheckedBounds"
     [mima]                 problemName=MissingMethodProblem
     [mima]             },
     [mima]             {
     [mima]                 matchName="scala.reflect.internal.Definitions#DefinitionsClass.UncheckedBoundsClass"
     [mima]                 problemName=MissingMethodProblem
     [mima]             },
     [mima]             {
     [mima]                 matchName="scala.reflect.internal.annotations.uncheckedBounds"
     [mima]                 problemName=MissingClassProblem
     [mima]             }
     [mima]         ]
```

**Comment by retronym** [comment]
Sigh. Rebased, updated the whitelists, this time is a lock.

**Comment by retronym** [comment]
@adriaanm Whatever could be wrong with that last run? I see [red](https://scala-webapps.epfl.ch/jenkins/job/pr-scala/908/), but no explanation in the console output on Jenkins.

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
:facepunch: :kissing_cat:

**Comment by adriaanm** [comment]
Sorry, this is because of my switching to a new jenkins setup for integrating the IDE in parallel with the test suite etc. The jenkins build flow plugin is incredibly buggy (I've lost close to a week to this by now). https://scala-webapps.epfl.ch/jenkins/job/pr-scala/908/console shows everything went well, but then the flow, which is just orchestration mysteriously fails.

I've looked at the implementation of the plugin and now understand why this can never work. Shared mutable state + concurrency = :facepunch:^2

https://github.com/jenkinsci/build-flow-plugin/blob/master/src/main/groovy/com/cloudbees/plugins/flow/FlowDSL.groovy#L386 -- enough said

**Comment by JamesIry** [comment]
What's the status on this one? RC1 is coming up fast.

**Comment by retronym** [comment]
> Cannot mkdir: No space left on device

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
We'd really like this in RC1, it's ready for review by @adriaanm

**Comment by adriaanm** [comment]
We'll make sure it can go in, delaying the RC if necessary. Not sure why jenkins is complaing about disk space -- that slave has 16 GB according to the dashboard.

**Comment by adriaanm** [comment]
Good catch on binary compatibility!

**Comment by adriaanm** [comment]
LGTM, with the caveat that I'm not sure this'll work for bounds checking of type constructors (those are bound-checked in `typedTypeApply`). Since we're only really interested in kind-\* types, it's probably not important.

**Comment by adriaanm** [comment]
rebasing due to conflict with #2809

**Pull request closed without merging**
