### PR TITLE
SI-9018 Fix regression: cycle in LUBs

### PR DESCRIPTION
**Pull request by retronym**
SI-9018 Fix regression: cycle in LUBs

Regressed in 4412a92d, which admirably sought to impose some structure
on the domain of depths, but failed to preserve an imporatnt part of
said structure.

When calculating LUBs and GLBs, the recursion depth is limited by
propagating a decreasing depth parameter. Its initial value is
the recursion limit, and is calcluated from the maximum depth of
the types fed into the calculation.

Here are a few examples that give a flavour of this calculation:

```
scala> class M[A]
defined class M

scala> class N extends M[M[M[M[A]]]]
<console>:34: error: not found: type A
       class N extends M[M[M[M[A]]]]
                               ^

scala> class N extends M[M[M[M[Int]]]]
defined class N

scala> lubDepth(typeOf[N] :: Nil)
res5: scala.reflect.internal.Depth = Depth(4)

scala> type T = M[Int] with M[M[Int]]
defined type alias T

scala> lubDepth(typeOf[T] :: Nil)
res7: scala.reflect.internal.Depth = Depth(3)
```

One parts of the LUB calculation, `lub0`, truncates the lub to
`Any` when the depth dives below zero.

Before 4412a92d:

```
------------------
value  decr   incr
------------------
   -3    -3     -2 (= AnyDepth)
   -2    -3     -1
   -1    -2      0
    0    -1      1
    1     0      2
    ...
```

After 4412a92d:

```
-----------------------
value      decr    incr
-----------------------
-MaxInt -MaxInt -MaxInt (= AnyDepth)
      0 -MaxInt       1
      1       0       2
      ...
```

The crucial difference that triggered the regression is that
decrementing a depth of zero now goes to the sentinel value,
`AnyDepth`, rather than to `-1`.

This commit modifies `Depth` to allow it to represent `-1`, which
can be reached by deprecmenting `Depth(0)`.

To better understand what was happening, I added tracing to the
calculation and diffed the before and after:

  https://gist.github.com/retronym/ec59608eecc52bb497fa

Notice that when `elimSub(ts, depth = 0)` recursively calls `lub`,
it does so with the variant that caluculates the allowable depth
from the shape of the given types. We can then infinitely recurse.

Before 4412a92d:

```
|-- elimSub(depth = 0, ts = List(Comparable[_ >: TestObject.E.Value with String <: Comparable[_ >: TestObject.E.Valu
|   |-- lub(depth = -1, ts = List(TestObject.E.Value with String, TestObject.C))
|   |   |-- lub0(depth = -1, ts0 = List(TestObject.E.Value with String, TestObject.C))
|   |   |   |-- elimSub(depth = -1, ts = List(TestObject.E.Value with String, TestObject.C))
|   |   |   |== List(TestObject.E.Value with String, TestObject.C)
|   |   |   |-- Truncating LUB to
|   |   |   |== Any
|   |   |== Any
|   |== Any
|== List(Comparable[_ >: TestObject.E.Value with String <: Comparable[_ >: TestObject.E.Value with String <: java.io
|-- lub(depth = 0, ts = List(java.lang.type, java.lang.type))
|   |-- lub0(depth = 0, ts0 = List(java.lang.type, java.lang.type))
|   |   |-- elimSub(depth = 0, ts = List(java.lang.type, java.lang.type))
|   |   |== List(java.lang.type)
|   |== java.lang.type
|== java.lang.type
|-- elimSub(depth = 0, ts = List(Object, Object))
|== List(Object)
|-- elimSub(depth = 0, ts = List(Any, Any))
|== List(Any)
```

After 4412a92d:

```
|-- elimSub(depth = 0, ts = List(Comparable[_ >: TestObject.E.Value with String <: Comparable[_ >: TestObject.E.Valu
|   |-- lub(depth = _, ts = List(TestObject.E.Value with String, TestObject.C))
|   |   |-- lub(depth = 3, ts = List(TestObject.E.Value with String, TestObject.C))
|   |   |   |-- lub0(depth = 3, ts0 = List(TestObject.E.Value with String, TestObject.C))
|   |   |   |   |-- elimSub(depth = 3, ts = List(TestObject.E.Value with String, TestObject.C))
|   |   |   |   |== List(TestObject.E.Value with String, TestObject.C)
|   |   |   |   |-- lub1(depth = 3, ts = List(TestObject.E.Value with String, TestObject.C))
|   |   |   |   |   |-- elimSub(depth = 3, ts = List(scala.math.Ordered[TestObject.E.Value], scala.math.Orde
|   |   |   |   |   |== List(scala.math.Ordered[TestObject.E.Value], scala.math.Ordered[TestObject.C])
```

Review by @adriaanm

AFAICR ('r' for reason), this patch should only cause programs that hang the
compiler to compile again, so I'm targetting 2.11.x.

### CODE REVIEW

**Comment by adriaanm** [comment]
Why don't we bring back something closer to the old code from https://github.com/scala/scala/commit/4412a92d3609d23f7369fc67bf5a67ddedf3511e#diff-ecaa4198a04261cd0e00a708b695eafbL96?

```
object Depth {
  final val _bottom = -3  // magic marker! (also, make sure it's constant folded)
  final val AnyDepth = new Depth(_bottom)

  @inline final def apply(depth: Int): Depth =
    if (depth <= _bottom) AnyDepth else new Depth(depth)
}
```

**Comment by adriaanm** [comment]
I think the conservative choice would be to mimic the old behavior as closely as possible, to avoid spending more time in deciphering the meaning of the old `-3` (this bug shows we did care about its value after all) and its potential for further regressions.

**Comment by retronym** [comment]
I did that originally, but was a bit unsatisfied not understanding what part of the change was really in error. After tracing out the code, I reasoned that it was important to be able to decrement the depth from `0` (the bath is fully drained) to `-1` (we've punched a hole in the bottom of the bath), but that it isn't possible/necessary to go any further.

Conceptually, `Int.MaxValue` would be a better sentinel value for `AnyDepth`, as it means "fill the bath with as much water as needed for these types").

But I'll add a commit with the additional conservative reversion in any case.

**Comment by adriaanm** [comment]
Sounds good! -3 is such an intriguing magic constant...

**Comment by retronym** [comment]
How's this?

**Comment by adriaanm** [comment]
Nice cleanup, but it seems we can no longer decrement our way to `AnyDepth` (ignoring overflow), which may be necessary because `isAnyDepth` used to become `true` after a couple of decrements?

**Comment by retronym** [comment]
So we go back to -3?

**Comment by retronym** [comment]
That's what's in the latest commit.

**Comment by adriaanm** [comment]
LGTM

Sadly, I much prefer the least exciting alternative here.

**Pull request merged**
