### PR TITLE
hotfix for runtime reflection on java7

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp

**Comment by paulp** [comment]
The second commit which comments out the assert is enough, right? If it is, I would say merge only that and don't rush into anything else. Not that you shouldn't break the dependency on runtime reflection, but it isn't broken unless there's a test which will catch it if the dependency comes back - there's no point in half measures.

**Comment by xeno-by** [comment]
@paulp Makes sense. I will wait for jenkins to approve the hotfix (my local java7 tests have already finished with a success), then rebase and merge.

**Comment by xeno-by** [comment]
Merged and started the nightly build to redeploy the artifacts: https://scala-webapps.epfl.ch/jenkins/job/scala-nightly-main-master/1960/.

@paulp Could you verify that the fix works for you?

**Comment by paulp** [comment]
It'll be a little bit - I think you can safely assume it works until I'm delivered a new build which confirms it.

**Comment by xeno-by** [comment]
The bug is fixed and the hotfix is reverted in https://github.com/scala/scala/pull/3057

**Pull request merged**
