### PR TITLE
Update link pointing to Scala development tutorials

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by mpociecha** [comment]
As for me the previous version anyway redirects to the new one. Also it would be nice to have these two commits squashed.

**Comment by SethTisue** [comment]
Thanks for calling this to our attention.

But, there's no need for rootdoc.txt to exist at all anymore, IMO. I'll make a PR removing it from the 2.11.x branch, relocating content to README.md as necessary (I think it might already be there).

**Comment by SethTisue** [comment]
(I haven't done this yet, but I haven't forgotten, either)

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/5513

**Pull request closed without merging**
