### PR TITLE
uniform dealiasing and widening

### PR DESCRIPTION
**Pull request by adriaanm**
rebase #1797 into fewer commits

### CODE REVIEW

**Comment by paulp** [comment]
It's too much; I don't want test.scaladoc or test.stability.

**Comment by paulp** [comment]
If you're wondering whether this lgtp, let me tell you it lgtm.

**Comment by adriaanm** [comment]
moved the change to `test/files/run/existentials3-old.check` from `394cc42` (formerly `0eadfa0`) to `3bf5118` (formerly `25d7bace13`), where it's actually needed -- it breaks the test suite for the older commits

**Comment by paulp** [comment]
I don't know where things stand, but

PLS REBUILD ALL

just in case.

**Comment by paulp** [comment]
My thirst for uniformity must be slaked.

**Pull request merged**
