### PR TITLE
SI-7711 Do not emit extra argv in script body

### PR DESCRIPTION
**Pull request by som-snytt**
Take away `argv` and make `args` the standard parameter name.

This is a quick fix to avoid "unused local" lint error.  All
the examples use `args`; in particular, "Step 4. Write some
Scala scripts" in "Programming in Scala" uses `args`.

I see the footnote there is also where Odersky concatenation is
specified, `"Hello, "+ args(0) +"!"` with no space next to the
literals.

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM -- I did a quick git grep argv in sbt, which came up empty (you never know)

you did miss a one-line opportunity for bumping your negative-lines count:

```
    val argv : NameType                = "argv"
```

**Comment by som-snytt** [comment]
That was intentional, because I hate to throw anything away.

Is it OK to deface the Wall of Names?

**Comment by adriaanm** [comment]
I prefer to GC stale names.

**Comment by som-snytt** [comment]
OK, that's done. Sniff. Without ceremony.

I checked that it works, but I also intended to add a test case if this was a go.  I think we know how.

**Comment by som-snytt** [comment]
PLS REBUILD/pr-scala@1dceb39

**Pull request merged**
