### PR TITLE
New TermSymbol.resolveOverloaded

### PR DESCRIPTION
**Pull request by clhodapp**
review by @cvogt and @odersky

Updated: rebased to include some just-merged fixes.

This commit replaces the resolveOverload method in TermSymbols in order to bring it more into line with what happens in the compiler. It supports a number of language features that the existing version does not, including expected return type, call-by-name parameters, and default-argument parameters. It also has a lot more tests.

I am sure that there are still many behavioral differences between this implementation and the one in the compiler as 1) I've just written it and 2) It is not the same code. Therefore, they should really be unified in reflect.jar in the future. That said, this is a significant improvement over what is in place now.

### CODE REVIEW

**Comment by cvogt** [comment]
I think this should go into M5 as is. This is a big step forward. We can solve the remaining inconsistencies until M6 or the RC.

**Comment by clhodapp** [comment]
I've hastily added scaladoc. I will be driving for the next ~10 hours and would have to pull off the road in order to respond, so please bear that in mind if I am slow to respond to queries.

**Comment by clhodapp** [comment]
I've also temporarily given you both push access to my repository, so if you need to make tweaks to my docs (again, they were hastily done), you can. I know it's not ideal, but it's better than you asking me to make changes and me not getting to them.

**Comment by cvogt** [comment]
Good to go, please merge. @adriaanm

**Pull request merged**
