### PR TITLE
Fixing -Xlint and acting on its advice for 2.10.

### PR DESCRIPTION
**Pull request by paulp**
Some fixes -Xlint told me about.

Moved dead code out of the standard lint, as it has become super
noisy for some reason. Un-overloaded implicits (don't overload
implicits!) Eliminated non-nullary method overriding nullary method
in the Future/Promise code. Made access levels consistent in some
collections classes.

### CODE REVIEW

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Review by @jsuereth

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
Does not merge anymore. Closing.

I'll discuss with @jsuereth if it makes sense to reopen it against 2.10.0. Those mostly cleanups that are not very essential for release right?

Are any of those code changes source or binary incompatible so they cannot be introduced in 2.10.1?

**Comment by paulp** [comment]
It is a mistake to discard a patch like this as "not essential for release." The difference between an appealing piece of software and an annoying one is in the small things.  Without this patch -Xlint is basically useless.  There is nothing in this patch which presents any threat.  It also contains material fixes, like not overloading implicit conversions.  It changes access levels, which of course impacts binary compatibility.

I don't know what is my capacity for seeing my work tossed aside; I know it's finite and the horizon is visible.  It is the thankless work which nobody else even considers doing, to come up with warnings like these and to act on them in our own codebase.  If the only thing I ask is that you not stand in the way, and I can't even get that, then I fear we may have crossed to the other side of the line delineating my tolerance for process.

**Comment by jsuereth** [comment]
Hey Paul,

greg and I talked.  FIRST - LGTM.   If the merge conflict is gone, this makes it into 2.10.0.

Specifically -
- final/private[collection] changes are huge
- Xlint dead flag move
- () vs not changes

All are both innocuous and help prevent further bugs/reports.  If you have time, can we split up the commits?  If not, fixing the merge conflcits is  good for me.

**Comment by gkossakowski** [comment]
@paulp: Everybody cares about his bit of work he did. I had a long discussion with Hubert yesterday because he worked hard on lazy vals refactoring and then we said it cannot go into 2.10.0 because it's too late.

I have those discussions every day and all I'm asking is a bit of understanding that you cannot get closer to release without setting up some deadline and stabilizng. Also, I totally do not understand why people care so deeply to get into 2.10.0? We'll have 2.10.1 4 months after 2.10.0 is out which is not a huge amount of time. I'm going to do all I can to make sure that we are on time.

One week ago you complained that nobody knows when 2.10.0 will be out and we are merging waay to many commits compared to what we discussed in Stockholm. I shared your frustration and took it seriously. We are getting closer to RC1 and that means it's getting closer (soon almost impossible) to get anything in for 2.10.0.

Having said all of that, you opened your pull request before deadline and @jsuereth said he'll review it if you fix merge conflicts. I'm fine with that.

**Comment by paulp** [comment]
"One week ago you complained that nobody knows when 2.10.0 will be out and we are merging waay to many commits compared to what we discussed in Stockholm."

That wasn't what I meant by that.  I meant that the estimate of "50" missed the lower bound by an order of magnitude, not that it would have been a good idea to ship with only 50 more commits.

**Comment by gkossakowski** [comment]
Oh, I see. Yeah, I misunderstood.

Anyway, let's focus on getting 2.10.0 out and yes, it means we'll have to turn down pull requests (does not apply to this one).

**Comment by paulp** [comment]
It is rebased on 2.10.x (which happened cleanly, I wonder why github lost the ability to merge it automatically) and broken into bite-sized pieces.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
It seems josh already says this LGTH now that I've swaddled the individual commits in merge blankets.

**Pull request merged**
