### PR TITLE
Move check for undefined members in objects from Typer to RefCheck

### PR DESCRIPTION
**Pull request by gzm0**
Alternative PR: #3407 

When writing an object (or an anonymous class) with declared but undefined members, the compiler complains specifically about the method which is not allowed:

```
object Foo {
  def x: Int  // will cause an error message
}
```

will emit

```
test.scala:16: error: only classes can have declared but undefined members
  def x: Int
      ^
```

This check has been performed by the Typer, unlike other checks for completeness of classes that are performed in the RefCheck phase. There are two issues with that:
1. The test in the typer is conceptually wrong and only shallow (it
   e.g. does not check for unimplemented inherited abstract methods)
2. This does not allow compiler plugins to generate such code in a
   post-Typer but pre-RefCheck phase.

This commit moves the check to the RefCheck phase. Error messages remain the same, except for the additional "object creation impossible" message emitted from the RefCheck phase. The example code above will now emit the following errors:

```
test.scala:15: error: object creation impossible, since method x is not defined
object Foo {
       ^
test.scala:16: error: only classes can have declared but undefined members
  def x: Int
      ^
```

There is no need for additional tests since `neg/nested-fn-print` and `neg/t565` already verify this behavior.

### CODE REVIEW

**Comment by xeno-by** [comment]
> This does not allow compiler plugins to generate such code in a post-Typer but pre-RefCheck phase

Could you elaborate on that?

**Comment by gzm0** [comment]
Specifically, for Scala.js, we would like to require that facade types for JS raw types (anything that extends `js.Any`) do not have implementations:

```
object Date extends js.Object {
  def getTime(): js.Number
}
```

for this we add a phase after the Typer (to be able to check for the inheritance) but before RefCheck (which supposedly does these checks). However, the particular case of abstract methods defined in objects (or anonymous functions) is caught by the Typer. Hence, the upper snipped doesn't even reach our phase where we can "fix" things.

After this change, we can require the implementations to be empty and add stubs where required to make RefCheck happy (and later drop them again in our backend). One could imagine that some other compiler plugin generates useful code there.

**Comment by adriaanm** [comment]
Note that this will make the IDE report fewer errors (/cc @dotta),
also illustrated by a change in check file that this may happen during regular compilation: https://github.com/scala/scala/pull/3375/files#diff-3

**Comment by sjrd** [comment]
To give more context of why Scala.js would need this:

In Scala.js we can define so-called facade types for JavaScript APIs. Any class/trait/object that extends indirectly `js.Any` (`scala.scalajs.js.Any`) is known by the compiler to be a facade type, which means it must not generate code for these methods, and instead enable the magic to bridge against "native" JavaScript code. Unfortunately, because these classes/traits/objects are not abstract, methods, vals and vars must be given dummy rhs'es to sooth the compiler's soul, even though the backend will discard them. Some excerpts from the DOM facade types:

``` scala
class EventTarget extends js.Object {
  def removeEventListener(`type`: js.String,
      listener: js.Function1[Event, Unit], useCapture: js.Boolean): Unit = ???
  def removeEventListener(`type`: js.String,
      listener: js.Function1[Event, Unit]): Unit = ???
  def addEventListener(`type`: js.String,
      listener: js.Function1[Event, Unit], useCapture: js.Boolean): Unit = ???
  def addEventListener(`type`: js.String,
      listener: js.Function1[Event, Unit]): Unit = ???
  def dispatchEvent(evt: Event): js.Boolean = ???
}

trait Location extends js.Object {
  var hash: js.String = ???
  var protocol: js.String = ???
  var search: js.String = ???
  var href: js.String = ???
  var hostname: js.String = ???
  var port: js.String = ???
  var pathname: js.String = ???

  def reload(flag: js.Boolean): Unit = ???
  def reload(): Unit = ???
  def replace(url: js.String): Unit = ???
  def assign(url: js.String): Unit = ???
}

object WheelEvent extends js.Object {
  val DOM_DELTA_PIXEL: js.Number = ???
  val DOM_DELTA_LINE: js.Number = ???
  val DOM_DELTA_PAGE: js.Number = ???
}
```

This is not particularly nice. It would look a lot better if the right-hand-side could be omitted.

With a plugin phase between `typer` and `refchecks`, it is possible to add dummy rhs's to deferred members of classes and traits extending `js.Any`. However, the early check done in `namer` concerned by this PR prevents us from doing the same for objects.

**Comment by retronym** [comment]
How about defining the API in and trait and  having the object extend that?  I'm not actually opposed to this change, but it would be good to weigh it up against this alternative.

**Comment by adriaanm** [comment]
I agree that -- in principle -- this check belongs in refchecks, and in fact it looks like it already is: https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala#L646
I quickly verified and it looks like only the removal part of this PR is necessary to achieve your goal.

Since we're in RC mode and this is not technically a critical bug, we should be extra careful. Willing to bend the rules a bit to allow scala.js to make progress, so I'm inclined to let this in, under the condition all due diligence is performed.

So, I'd like to ask for better test coverage for this area: please add a test that shows the behavior is not changed (module timing of the error message: namer/refchecks) by removing the early check in namers (i.e., that is was duplicated with respect to the existing tests in refchecks).

**Comment by sjrd** [comment]
@retronym That would be a work-around, indeed. Not as nice as it could be, but definitely better than the ???s if this PR ends up being rejected.

@adriaanm Thanks for considering the PR despite the RC mode! I think that @gzm0 (correct me if I'm wrong) did only the removal part first and that was fine, but added the add part to stay closer to the error messages emitted by M8 and before. Would you prefer only the removal part, and more .check changes?

**Comment by adriaanm** [comment]
Removing duplicated code would be a perk -- it would also help to understand the difference.

That said, I would of course prefer to entirely avoid changes that aren't fixing critical bugs/blocking scala.js.

**Comment by densh** [comment]
I'd expect that a person who knows scala, digs into sources and finds:

``` scala
object API {
   def endpoint: Bazinga
}
```

would be infinitely confused. So this is an object with abstract member? Whoa? Does the spec allow it? Can I do the same? What does it really mean?

**Comment by xeno-by** [comment]
Would it be possible to use macro annotations for the same purpose?

```
@scala.js.stub
object API {
  def endpoint: Bazinga
}
```

**Comment by sjrd** [comment]
@densh We're not talking about modifying the Scala language; we're talking about the Scala.js dialect. Facade types must inherit from `js.Any`, so the object looks more like

``` scala
object API extends js.Object {
  def endpoint: Bazinga
}
```

and in the Scala.js dialect, this is known as a facade type to JavaScript APIs. Seriously, how is the previous form more confusing than

``` scala
object API extends js.Object {
  def endpoint: Bazinga = ???
}
```

which suggests that the body of the function is actually `???`. Of course, we could define something like `js.native` or `js.foreign` to be a replacement for `???` in that case, but it still makes a lot of noise when you read and write these facade types.

When I read facade types, I interpret `def endpoint: Bazinga` not as meaning "the method is abstract", but rather "the method exists, but its body is not here".

@xeno-by If macro annotations can inspect the types of the parents (we have to tell whether API extends `js.Any`), and they kick in before the check concerned by this PR, then yes. But I cannot reasonably make this _core_ feature of Scala.js be dependent on macro paradise. It is a bit redundant too to need the macro annotation in addition to inheriting from `js.Object`, so this is about as nice/ugly as @retronym's workaround.

**Comment by xeno-by** [comment]
@sjrd Yes and yes.

**Comment by dotta** [comment]
> Note that this will make the IDE report fewer errors (/cc @dotta)

@adriaanm Thanks for pinging me. From an IDE perspective, having the presentation compiler to report less errors is definitely not desiderable. It's a bit unfortunate that this important change is happening so late in 2.11, as it doesn't gives us much room for finding a proper solution. For instance, I imagine we could consider running the presentation compiler up to `refcheck` instead of `typer`, and hence this change would not affect us. But of  course it's too late for this, as we would need to properly weight pros and cons.

It looks like you guys are discussing possible workarounds to avoid making the change. So, what if for 2.11 we go with a workaround that does not affect the presentation compiler, and we work on finding a proper solution for 2.12?

\cc @dragos

**Comment by gzm0** [comment]
Note the alternative PR #3407 without the additional error messages and an additional test.

**Comment by gzm0** [comment]
Closing this in favor of #3407.

**Pull request closed without merging**
