### PR TITLE
Stabilize args of apply

### LINKED ISSUE #11397: Error in code execution order, possibly related to stabilization issues
Possibly related to https://github.com/scala/bug/issues/10714 which was fixed in https://github.com/scala/scala/pull/6312

The following code demonstrates an error in code execution order. 
An assertion placed show exactly where the error occurs.
```scala
trait MyAny {
  type TSomething
  type This <: MyAny
}

class MyBool extends MyAny {
  type TSomething = DummyImplicit
  type This = MyBool
}

object Test extends App {
  val i = new MyBool
  var call = 0

  final class MyMatch[MV <: MyAny](val matchVal : MV)  {
    def myCase[MC](pattern : Boolean)(block : => Unit)(
      implicit patternBld : matchVal.TSomething
    ) : MyMatch[MV] = {
      call -= 1
      block
      this
    }
  }

  def myMatch[MV <: MyAny](matchValue : MV) : MyMatch[matchValue.This] = {
    assert(call == 0)
    call += 1
    new MyMatch[matchValue.This](matchValue.asInstanceOf[matchValue.This])
  }

  myMatch(i)
    .myCase(true) {
      myMatch(i)
        .myCase(true) {

        }
    }
}
```
Affected Scalac version: from 2.13.0-M4
2.13.0-M2 is OK. 2.13.0-M3 causes a crash as demonstrated in https://github.com/scala/bug/issues/10714
The reason I'm thinking it's related to the stabilization bug is that if we change the code to the following, there is no error:
```scala
  myMatch(i)
    .myCase(true) {
      val noErrorNow = myMatch(i)
        .myCase(true) {

        }
    }
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#11397

### CODE REVIEW

**Comment by milessabin** [comment]
Is the essence of the change here that instead of lifting the stabilisers out to the top level they're instead lifted only as far as necessary?

**Comment by som-snytt** [comment]
Yes, except "stabilizers." Probably I should have split the "refactor" into a separate commit. The difference is when it sees an Apply that applies to our tree. (My first intuition was to look for a Block, but there is no Block in this case; in fact, introducing a Block is the workaround.)

Edit: before I forget, it recurses for the "enclosing tree" test, which is special-cased for Apply, as described. Probably it would look better as `test(tree) && !enclosingTest(enclosingTree)` with two methods. I'll try that edit before my lunch break is over.

**Review by milessabin — APPROVED** [review]

**Comment by som-snytt** [comment]
I pushed the simpler diff. It's obvious now that the change is when testing the enclosing context. My previous attempt was due to late-night coding. I also aligned the arrows. Can't wait for scalafix.

**Comment by milessabin** [comment]
While you're in the area ... this looks related: https://github.com/scala/bug/issues/11609.

**Comment by som-snytt** [comment]
I'm actually at the office now, but I'm happy to take a look, thanks.

**Review by diesalbla — APPROVED** [review]

**Comment by lrytz** [comment]
Thank you, @som-snytt!

**Pull request merged**
