### PR TITLE
bundle a newer Akka actors jar

### PR DESCRIPTION
**Pull request by SethTisue**
might as well let people have the current stuff. I asked the
Akka folks and nobody saw a reason not to upgrade.  this
version of Akka is the latest in the 2.3.x series, but is
also some months old, so no stability worries.

(this would have been included in 2.11.8 if I had thought of
it in time)

### CODE REVIEW

**Comment by SethTisue** [comment]
fyi @patriknw

**Comment by patriknw** [comment]
thanks

**Comment by SethTisue** [comment]
integrate-ide failure is unrelated; it's being tracked at https://github.com/scala/scala-dev/issues/97

**Comment by SethTisue** [comment]
review by @adriaanm, now that Jenkins signed off?

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
