### PR TITLE
Make tree traversal uniform.

### PR DESCRIPTION
**Pull request by paulp**
There's a huge amount of tree traversal related duplication
which is hard to eliminate only because trees aren't properly
traversed. Key not-quite-tree bits of key trees are ignored
during traversals, making it impossible to write e.g. a
pretty printer without duplicating almost the entire traversal
logic (as indeed is done for printing purposes in more than one
place.) And almost the entire pickler logic is redundant with
Traverser, except since it's all duplicated of course it diverged.

The not-quite-trees not quite being traversed were Modifiers and Name.
This commit contains two key contributions, one to traversal and one
to pickling:
- traverse every case field of every tree
- do all pickling in an order consistent with tree traversal

There had been ad hoc adjustments to the pickling scheme here and
there, probably in pursuit of tiny performance improvements.
For instance, a Block was pickled expr/stats instead of stats/expr,
a TypeDef was pickled rhs/tparams instead of tparams/rhs.
The benefits derived are invisible compared to the cost of having
several hundred lines of tree traversal code duplicated in half a
dozen or more places.

It's now possible to eliminate all the pickler tree traversal
code and use regular traversers (but unfortunately that step does
not accompany this commit.) For illustration, here's what DefDef
looks like in Pickler now:

```
  case DefDef(mods, name, tparams, vparamss, tpt, rhs) =>
    putMods(mods)
    putEntry(name)
    putTrees(tparams)
    putTreess(vparamss)
    putTree(tpt)
    putTree(rhs)
```

Here's what it looks like in Trees#itraverse:

```
  case DefDef(mods, name, tparams, vparamss, tpt, rhs) =>
    atOwner(tree.symbol) {
      traverseModifiers(mods)
      traverseName(name)
      traverseTrees(tparams)
      traverseTreess(vparamss)
      traverse(tpt)
      traverse(rhs)
    }
```

I leave the details of how one might use the tree traverser
to eliminate this redundancy as an exercise for Dear Reviewer.
It is ALSO now possible to write a vastly cleaner tree printer
than the ones presently in trunk, but this too is an exercise
for Dear Reviewer.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @xeno-by or @retronym. And, I'm sorry to keep playing this card but I beg you not to go looking for more for me to do. I keep finding work of this kind as I go through my branches (still hundreds remain) and it seems like a crime to just delete it. But it always takes at least a couple hours to clean it up for pull request and that's two more hours of me working for free and not getting on with my life. So if necessary I can rm -rf /l/residual-trunk, but I think that would be kind of nuts given the value of a commit like this.

Anyway. Let's say my code review from this point forward is "Pass/Fail". When I fail I'll leave the PR in a branch where perhaps Simon or another good soul can tutor it.

**Comment by paulp** [comment]
Notice that def readTree is designed to enforce by construction (literally) the honesty of the pickler. Excerpt:

```
+        case DEFDEFtree          => DefDef(modsRef, termNameRef, rep(tparamRef), rep(rep(vparamRef)), ref, ref)
+        case EXISTENTIALTYPEtree => ExistentialTypeTree(ref, all(ref))
+        case FUNCTIONtree        => Function(rep(vparamRef), ref)
```

If the tree is constructed immediately, as they all are, there's no opportunity to do a bunch of order-shuffling of the parameters. Either they come out in that order or it doesn't work. (Of course one could use named parameters to circumvent this, but one doesn't.)

**Comment by paulp** [comment]
I just noticed that "make tree traversal uniform" sounds like I want you to sew one, to be worn only on special tree traversal occasions.

**Comment by som-snytt** [comment]
Maria made them out of old drapes in The Sound of Music.

**Comment by retronym** [comment]
The main obstacle I see to merging this is the breaking change to the pickle format. This may well go unnoticed as there aren't too many applications of tree pickling.

Notice below how the stats/expr of the `Block` are reversed on unpickling.

``` scala
% cat sandbox/test.scala
@deprecated({"".reverse; ""}, "")
class C

% scalac-hash v2.11.0-M5 sandbox/test.scala
[info] v2.11.0-M5 => /Users/jason/usr/scala-v2.11.0-M5-0-gd6fe890
pr/3019 ~/code/scala qbin/scala
Welcome to Scala version 2.11.0-20131005-123348-bc880d5f0f (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_37).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :power
** Power User mode enabled - BEEP WHIR GYVE **
** :phase has been set to 'typer'.          **
** scala.tools.nsc._ has been imported      **
** global._, definitions._ also imported    **
** Try  :help, :vals, power.<tab>           **

scala> typeOf[C].typeSymbol.annotations
warning: there were 2 deprecation warning(s); re-run with -deprecation for details
res0: List[$r.intp.global.AnnotationInfo] =
List(deprecated({
  "";
  scala.this.Predef.augmentString("").reverse
}, ""), deprecated("see corresponding Javadoc for more information.", ""))
```

@adriaanm I see a few options:
- ignore this breakage on the grounds it doesn't apparently effect the ecosystem in our PR validation
- minimize the exposure to the breakage by merging this just before a milestone
  - or, more conservatively, merge it just after a "technical milestone" and follow that with a new milestone with just that change.
- bump PickleFormat.MajorVersion and make the unpickler backwards compatible with the previous format.

**Comment by retronym** [comment]
We'll also need to update the docs in `PickleFormat`, and then delete the duplicated copy of those docs in scalap.

`scalap` itself doesn't bother to unpickle trees, so we don't have to update it.

```
% qbin/scalap C
@scala.deprecated
class C extends scala.AnyRef {
  def this() = { /* compiled code */ }
}
```

**Comment by retronym** [comment]
> When I fail I'll leave the PR in a branch where perhaps Simon or another good soul can tutor it.

Submitting a PR is sufficient. Even if it is closed the commits live on in the Scala repo, accessible with the "checkout branch" button or via `refs/pull`. I interact with them with:

```
# ~/.gitconfig
[alias]
    co = checkout
    ci = commit
    pub = "!f() { git push -u ${1:-retronym} `git symbolic-ref HEAD`; }; f"
    pullify = config --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'
    pr = !git fetch -fu ${2:-origin} refs/pull/$1/head:pr/$1 && :
    pr-clean = "!git for-each-ref refs/heads/pr/* --format='%(refname)' | while read ref ; do branch=${ref#refs/heads/} ; git branch -D $branch ; done"
```

```
# checkout just one PR
% git pr 3019

# checkout all PRs
% git pullify
% git checkout origin
```

**Comment by adriaanm** [comment]
@retronym, I defer to you -- offline for the next 7 days
I think the pickle format change is low risk, but maybe that's just cause i'm going offline for 7 days. (Yes, @paulp, I'm going on another of those irresponsible vacations!)

**Comment by retronym** [comment]
LGTM. I'll leave the merge decision up to @gkossakowski who is going to cut M6.

**Comment by paulp** [comment]
I'll simplify and say I worked on it a bit longer and decided it's not as done as I'd like. I will resubmit.

**Comment by som-snytt** [comment]
So the joke about Sound of Music and tree traversal is more resonant if you recall that the adults are driving back when they notice the children in the drapery uniforms climbing in the trees. So Paul's "tree traversal uniform" still makes me laugh.

**Pull request closed without merging**
