### PR TITLE
SI-6112 exposes symbol mutators in macro universe

### PR DESCRIPTION
**Pull request by xeno-by**
In makro.Universe we expose the most hardcore fragments of the compiler API
that don't make sense / can't be made use of in runtime reflection API.

makro.Universe is already refining Tree to include setters for
symbols, types and positions. Now we bring Symbol up to speed.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @adriaanm

**Comment by adriaanm** [comment]
won't this conflict with #983?

also, `..` seems pretty terse for documentation, even for trivial stuff like this
might be better to leave off the comment entirely -- or is this how you inherit docs these days?

**Comment by xeno-by** [comment]
I guess there won't be a conflict, since in #983 makro.Universe simply gets renamed. I hope git is smart enough to merge renaming and modification of the renamee automatically.

As to `..` that's my equivalent of todo for reflection docs. I'd comment these methods right now, but imho documenting the entire reflection in a batch will take less time and produce more coherent result.

**Comment by adriaanm** [comment]
You're right about git. And fair enough regarding documenting in one go,
but experience has shown these doc comment stubs tend to stick around.

I'd rather not add them at all until they have some actual content.

"Oh, would you like some docs? Ha! Made you look."

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
