### PR TITLE
Error on failing to mix in compatible superaccessor

### PR DESCRIPTION
**Pull request by adriaanm**
Fix scala/bug#11351

### CODE REVIEW

**Comment by smarter** [comment]
Note that we actually decided to emit an error instead of using a different member: https://github.com/lampepfl/dotty/pull/5604

**Comment by adriaanm** [comment]
Ah, thanks! Will update this PR

**Comment by adriaanm** [comment]
Updated with error

**Comment by adriaanm** [comment]
🤦‍♂️ 
```
/src/reflect/scala/reflect/runtime/JavaUniverse.scala:30:7: illegal trait super target found for method unique required by trait SynchronizedTypes;
 found   : protected def unique: ([T <: _1.Type](tp: T)T) forSome { val _1: reflect.runtime.JavaUniverse } in trait Types
 expected: protected def unique: ([T <: _1.Type](tp: T)T) forSome { val _1: reflect.runtime.JavaUniverse } in trait Types
class JavaUniverse extends InternalSymbolTable with JavaUniverseForce with ReflectSetup with RuntimeSymbolTable { self =>
```

**Review by retronym — COMMENTED** [review]
LGTM

**Pull request merged**
