### PR TITLE
add `dequeueOption` to immutable.Queue

### PR DESCRIPTION
**Pull request by ziggystar**
Currently it's not possible to use `immutable.Queue` easily in a functional way, since the essential method `deque` throws an exception in a common situation (dequeue on an empty Queue). Of course you can convert the exception into an Option on the user-side, but this is awkward to code, and simply annoying.

This pull-request implements `dequeueOption` in the spirit of `headOption` for `Seq`, yielding `Option[(A,Queue[A])]`, with `None` in case of empty queue. 

A possible different type signature might have been `(Option[A],Queue[A])`, though this appears a bit strange, since `q.dequeueOption._2` would return `q` for the empty case and `q` with first element removed, else.

### CODE REVIEW

**Comment by adriaanm** [comment]
I'm very sorry this went without feedback for so long. I've been mulling this over, and I'm not sure about the benefit of adding another method for this -- also, Option-boxing is a performance killer. What say you, @ichoran?

**Comment by Ichoran** [comment]
@adriaanm - Option-boxing is way, way, way less of a performance-killer than is throwing an exception.  Although in general I would rather deprecate methods than add more, I agree with @ziggystar that this is key missing functionality given that we support headOption.  The closest equivalent is `if (q.isEmpty) None else Some(q.dequeue)`, which is rather awkward.  Also, LGTM.

**Comment by ziggystar** [comment]
@adriaanm I think wrapping `Option` around the result does not matter that much performance-wise. After all, `dequeue` already creates a Tuple and a new `Queue` instance.

But on the other hand, one can locally add Ichoran's `if-else` code as an extension method - presumably without a substantial performance hit compared to putting it into the library. So basically it boils down to "How many batteries are included?".

At least I am using `Map.get` and `Seq.headOption` frequently, only seldomly switching away for performance reasons. Thinking about it, if performance matters I'm switching to mutable collections; this only works if you don't need the persistence.

**Comment by adriaanm** [comment]
Ok! Please squash the commits and align your PR with our [PR Policy](https://github.com/scala/scala/wiki/Pull-Request-Policy): please add a JUnit test under `test/junit` -- run with `ant test.junit`. Here's a recent example: https://github.com/scala/scala/commit/03bf97e0893b227812125f7c049fdac254181cb2

**Comment by adriaanm** [comment]
Sorry, I use eclipse. /cc @retronym who's our intellij expert.

**Comment by adriaanm** [comment]
https://github.com/dotta/scala/blob/master/src/eclipse/README.md
https://github.com/dotta/scala/blob/master/src/intellij/README

**Pull request closed without merging**
