### PR TITLE
Require Ant >= 1.8.2

### PR DESCRIPTION
**Pull request by retronym**
Reportedly our build fails with earlier incarnations. Time to raise the
bar.

Tested by temporarily setting the requirement to 1.8.5 and observing:

```
% ant init
Buildfile: /Users/jason/code/scala/build.xml

desired.jars.uptodate:

boot:

init:

BUILD FAILED
/Users/jason/code/scala/build.xml:216: Ant version 1.8.5 is required. You are running Apache Ant(TM) version 1.8.4 compiled on May 22 2012
```

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
In 2.10.x, the requirement for Ant 1.7.0 was documented in the README.

For master, the trimmed down README doesn't mention that anymore, nor the [Hacker's Guide](http://www.scala-lang.org/contribute/hacker-guide.html). So I don't think there is any documentation to update (which is good, self documenting checks in the build are more robust.)

I'll notify scala-internals about this change on the [thread](https://groups.google.com/d/msg/scala-internals/9BL-Oy1cySI/lBi9lL2JraYJ) that raised the issue.

**Comment by adriaanm** [comment]
LGTM

**Comment by retronym** [comment]
Successful test run: https://scala-webapps.epfl.ch/jenkins/job/pr-scala/2430/

**Comment by gkossakowski** [comment]
LGTM.

Sorry, I'm behind the email due to Strange Loop and poor wifi access.

**Pull request merged**
