### PR TITLE
SI-5894 Don't emit static forwarders for macros.

### PR DESCRIPTION
**Pull request by retronym**
With a little opportunistic `Gen{AS, JV}M` duplication avoidance en-route.

Review by @magarcia, /cc @paulp, @xeno-by

### CODE REVIEW

**Comment by paulp** [comment]
I was confused, because I wrote this code a long time ago? But maybe this is the patch which I refused to check in after discovering the degree of GenJVM/ASM duplication.

**Comment by retronym** [comment]
Yep, that appeared to be the course of events.

**Comment by magarciaEPFL** [comment]
GenJVM has been EOL'd. That means GenJVM will be removed at the latest in 2.11. Duplicate code that is factored out will become "de-duplicated" by then anyway. Just saying, factored-out code is great, greater still if also standalone (ie not depending on GenJVM being there, because hopefully it will go away rather sooner than later). BTW, why not remove GenJVM now???

**Comment by JamesIry** [comment]
I can take-on whacking GenJVM in master. Do we have an issue open for it?

**Comment by retronym** [comment]
This fix was targeted at 2.10.x, where we will probably need to keep GenJVM for another 12-18 months. So with that in mind, I've just refactored the parts that I needed to maintain, plus the parts that were straight forward to extract. I have no problem with the re-inlining these when we delete GenJVM.

**Comment by magarciaEPFL** [comment]
@JamesIry: I don't remember a discussion or ticket about the earliest release when it's safe to remove `GenJVM`. The release team will have a say on this. In particular, @gkossakowski has spent quality time with both `GenJVM` and `GenASM`.

**Comment by JamesIry** [comment]
@margarciaEPFL cool, moved discussion to scala-internals so as to let this pull continue to be requested without our noise.

**Comment by adriaanm** [comment]
yes, before pulling the trigger, let's wait until @gkossakowski is back so that we can have a proper discussion among gentlemen about this (he's back today, I think)

I see no reason why not to

in the mean time, @JamesIry, please open a ticket that targets 2.11.0-RC1
(there's already a similar one for putting old patmat out to pasture, btw)

**Comment by magarciaEPFL** [comment]
LGTM

**Pull request merged**
