### PR TITLE
Remove deprecated scala-reflect 2.10 compatibility layer

### PR DESCRIPTION
**Pull request by joroKr21**
Deprecated since 2.11.0

### CODE REVIEW

**Comment by SethTisue** [comment]
as @xuwei-k has noted at https://twitter.com/not_xuwei_k/status/1089592626255409153 , and as I have also been noticing myself in the Scala 2.13 community build, there are definitely still projects using these APIs in their 2.10–2.11–2.12 crossbuilds.

the needed code changes will often force or at least strongly encourage dropping 2.10 and replacing with a 2.11–2.12–2.13 crossbuild.

am I having second thoughts about this PR? well, some. do I want it reverted? meh, I don't know, probably not.

we should remain especially eager to eliminate deprecated stuff from parts of the scala/scala codebase that will carry forward to Scala 3. which basically means all of regular stdlib, but it doesn't include scala.reflect. scala.reflect isn't evolving anymore, so removing deprecated stuff for 2.13 and 2.14 doesn't have a huge upside. (perhaps _some_ upside.)

on the balance, I guess I'm okay with this PR, but: I do think we need to seriously question merging anything _else_ like this for RC1 or 2.13.0, and start deferring for later releases. merging breaking changes at this point makes work for me in the 2.13 community build and makes work for library maintainers at a time we can ill afford that. things need to settle down now.

**Comment by joroKr21** [comment]
Hmm, I thought most projects would be using macro-compat with quasiquotes but I guess I was wrong. If this breaks too much we should revert it but ultimately it's your call.

**Comment by adriaanm** [comment]
So, 2.10 (and 2.11) users won't get upgrades of third party libraries that decide to stop cross-building once 2.13 is out. If you're on an ancient version of Scala, you're likely having to live with more than one old dependency.

**Comment by SethTisue** [comment]
note that people really determined to continue 2.10-2.11-2.12-2.13 crossbuilds (I think this will be rare, I see open source projects dropping 2.10 support left and right, that's been going on for some time already) won't be dead in the water. they can add a little bit of Scala-version-specific source code, and/or use macro-compat

**Pull request merged**
