### PR TITLE
Deprecate "isTraversableAgain".

### PR DESCRIPTION
**Pull request by flomebul**

### CODE REVIEW

**Review by som-snytt — COMMENTED** [review]
It was added to Iterable and IterableOnce. (Should be deprecated in both places, if deprecated.)

The comment says Iterators can be TraversableAgain, so the type test is not equivalent.

I'm not sure of the use case. It is overridden in parallel collections.

**Comment by flomebul** [comment]
Oh, more complex than I expected. In fact, the real solution ois probably to introduce a replacement method like `isIterableAgain`, but this is probably not possible in short term.

**Comment by SethTisue** [comment]
@scala/collections

**Comment by joshlemer** [comment]
Mostly this is correct but an exception is `Option` which extends `IterableOnce` but not `Iterable`. It gets around that by having an implicit conversion

**Comment by julienrf** [comment]
Thank you @flomebul for your contribution. Could you please elaborate on the motivation behind this change? Maybe link the relevant issue, or discussion, in the PR description.

**Comment by flomebul** [comment]
I see that `isTraversableAgain` is the only reference to `Traversable` which is not yet deprecated. May I propose a PR to just add a `TODO` comment for 2.14.+ ?

**Comment by julienrf** [comment]
I agree that it would be more consistent to name it `isIterableAgain`, but I think the usage of “traversable” in the current method name is okay because we still understand what it means. Feel free to open a PR adding a comment about that, and thank you for your input!

**Pull request closed without merging**
