### PR TITLE
Remove build.number.maven

### PR DESCRIPTION
**Pull request by retronym**
I can't find any justification for having this information
in both build.number and build.number.maven.

They have drifted apart on the 2.10.x branch, although that
doesn't matter because build.number is correct, and loaded first,
and Ant properties are write-once.

I'm assuming that the Ant tasks in src/build/pack.xml are only
invoked through the <antcall>-s in ./build.xml.

Here's a test of that from the 2.10.x branch:

```
% cat build.number
#Tue Sep 11 19:21:09 CEST 2007
version.major=2
version.minor=10
version.patch=3
# This is the -N part of a version.  if it's 0, it's dropped from maven versions.
version.bnum=0

# Note: To build a release run ant with -Dbuild.release=true
# To build an RC, run ant with -Dmaven.version.suffix=-RCN

% cat build.number.maven
version.major=2
version.minor=10
version.patch=0

% git diff
diff --git a/build.xml b/build.xml
index 3a83aa4..5cb952c 100644
--- a/build.xml
+++ b/build.xml
@@ -62,6 +62,9 @@ TODO:
   <target name="distpack" depends="dist.done, docs.done">
     <ant antfile="${src.dir}/build/pack.xml" target="pack-all.done" inheritall="yes" inh

+  <target name="distpack.maven.info">
+    <ant antfile="${src.dir}/build/pack.xml" target="pack-maven.info" inheritall="yes" i
+
   <target name="distpack-maven" depends="dist.done, docs.done">
     <ant antfile="${src.dir}/build/pack.xml" target="pack-maven.done" inheritall="yes" i

diff --git a/src/build/pack.xml b/src/build/pack.xml
index 20c4034..56863ff 100644
--- a/src/build/pack.xml
+++ b/src/build/pack.xml
@@ -133,6 +133,10 @@ MAIN DISTRIBUTION PACKAGING
     <mkdir dir="${dists.dir}/maven/${version.number}"/>
   </target>

+  <target name="pack-maven.info">
+    <echo message="version.patch = ${version.patch}"/>
+  </target>
+
   <target name="pack-maven.libs" depends="pack-maven.start">
     <macrodef name="mvn-copy-lib">
       <attribute name="mvn.artifact.name"/>

% ant distpack.maven.info
Buildfile: /Users/jason/code/scala2/build.xml

distpack.maven.info:

pack-maven.info:
     [echo] version.patch = 3
```

Notice how the stale `version.patch=0` in build.number.maven is
ignored.

Review by @lrytz @jsuereth @gkossakowski

### CODE REVIEW

**Comment by gkossakowski** [comment]
I can't see why this is needed either. It would be great if @lrytz could chime in.

I'll also grep through our jenkins configs just to make sure we are not breaking something.

**Comment by lrytz** [comment]
I lost track of what's going on there...

Apparently `build.number` got removed at some point (fbd5efe49cf23b446762dfa5026e8bac82ab04fc), then added back due to maven (58ab20ba9b6a17c81f2f89f31f7265d2ed3b166b), then renamed to `build.number.maven` (f1d04997c4b35357c542062926c7b3ce4253f099), then added back again (c3bff042546a343f260e2ef8be01665671db1043), and since modified a few times by Josh.

I guess @jsuereth knows most about these files.

**Comment by jsuereth** [comment]
The main reason this file existed is so we can modify the version number via external scripts.   Since build.number still exists, that's the one we should use for now. AFAIK - Everyone else is back on build.number, so this LGTM.

Ping me once this is through, though, and I'll run a few scripts to make sure everything is gravy.

**Comment by gkossakowski** [comment]
Thanks @jsuereth!

Merging it now.

**Pull request merged**
