### PR TITLE
No longer crash on NoSymbol.owner.

### PR DESCRIPTION
**Pull request by paulp**
Historically calling NoSymbol.owner has crashed the compiler.
With this commit, NoSymbol owns itself. This is consistent with
the way ownership chains are handled elsewhere in the compiler
(e.g. NoContext.owner is NoContext, NoSymbol.enclClass is
NoSymbol, and so on) and frees every call site which handles
symbols from having to perform precondition tests against
NoSymbol.

Since calling NoSymbol.owner sometimes (not always) indicates
a bug which we'd like to catch sooner than later, I have
introduced a couple more methods for selected call sites.

```
  def owner: Symbol       // NoSymbol.owner is self, log if -Xdev
  def safeOwner: Symbol   // NoSymbol.owner is self, ignore
  def assertOwner: Symbol // NoSymbol.owner is fatal
```

The idea is that everyone can call sym.owner without undue anxiety
or paranoid null-like tests. When compiling under -Xdev calls to
`owner` are logged with a stack trace, so any call sites for which
that is an expected occurrence should call safeOwner instead to
communicate the intention and stay out of the log. Conversely, any
call site where crashing on the owner call was a desirable behavior
can opt into calling assertOwner.

This commit also includes all the safeOwner calls necessary to
give us a silent log when compiling scala.

### CODE REVIEW

**Comment by lrytz** [comment]
i'm not sure.. owners are a thing that often gets messed up when implementing / changing a transformer in the compiler. i remember fixing multiple bugs which manifested in weird behavior in later phases, just because owners were messed up some time earlier, they are hard. by eliminating the NOPE we might get more of these hard-to-debug.

**Comment by paulp** [comment]
I agree they are hard, I just don't see crashing more frequently as a remedy. Perhaps a compromise is to continue using "safeOwner" or something where it is innocuous, and logging with devWarning when NoSymbol.owner is called. But given how many NSDNHO crashes are something stupid like trying to print a type nicely, it's not reasonable to kill the compiler for everyone as a default state of affairs.

**Comment by paulp** [comment]
@adriaanm this is 25 days old, any opinions? If the consensus is that crashing is the optimal handling of NoSymbol.owner then I will gladly close this.

Sometimes I find it edifying to imagine the "after" is the status quo and someone is sending a pull request for the "before", and think of how that would go over.

**Comment by adriaanm** [comment]
I'm making my way through the queue for M5. Considering this one as well.

**Comment by adriaanm** [comment]
My thoughts:
- @paulp, I agree in principle we shouldn't crash with NSDNHO when running in production.
- @lrytz has a good point: sometimes these crashes are informative, so we should at least give ourselves a way to retain them where/when sensible: -Xdev, perhaps?
- As a compromise, we could differentiate `exists` and `assertExists`, where the latter fails under `-Xdev` for cases where `exists == false` indicates a bug
- I don't like the commit message: it'd be more useful if it started with explaining the change ("Use combinator methods and `exists` on `Symbol` rather than comparing to `NoSymbol`. `NoSymbol.owner` now returns `NoSymbol` rather than crashing"). The motivation can come after.
- The new style of dealing with `NoSymbol` should also be documented in the code at `Symbol`/`NoSymbol`.

**Comment by paulp** [comment]
@adriaanm please re-review.

**Comment by adriaanm** [comment]
LGTM now. I like the `assertOwner` as dead code compromise.

**Pull request merged**
