### PR TITLE
[after #9141] growing builder

### PR DESCRIPTION
**Pull request by mkeskells**
add ++= to GrowingBuilder, to allow mutable implementations to optimise bulk addition

### CODE REVIEW

**Comment by mkeskells** [comment]
Mima issue - 
```
method ++=(scala.collection.TraversableOnce)scala.collection.mutable.GrowingBuilder in class scala.collection.mutable.GrowingBuilder does not have a correspondent in other version
```

**Comment by dwijnand** [comment]
Yeah, that's our darned forward-compatibility guarantee.  I guess we can safely land this if/once #9141 lands.

The fix to `clear` can land sooner than that, if you'd like.

**Comment by mkeskells** [comment]
> Yeah, that's our darned forward-compatibility guarantee. I guess we can safely land this if/once #9141 lands.
> 
> The fix to `clear` can land sooner than that, if you'd like.

made it draft until #9141 is merged

**Comment by dwijnand** [comment]
Going to add this to the list in https://github.com/scala/bug/issues/11804#issuecomment-738879217, and otherwise close this one as we cannot land it without that.

**Pull request closed without merging**
