### PR TITLE
Remove "throws InvalidEscapeException" from StringContext.raw doc

### PR DESCRIPTION
**Pull request by dhgarrette**
Since StringContext.raw doesn't escape its input, it does not call `treatEscapes` and cannot throw the InvalidEscapeException.

### CODE REVIEW

**Comment by som-snytt** [comment]
So long as you're in the neighbo(u)rhood, the example is wrong, too.

0x23 is tic-tac-toe, 0x25 is %. Not sure which makes a better example.

Runnable examples, anyone?

https://github.com/dhgarrette/scala/blob/2.11.x/src/library/scala/StringContext.scala#L108

**Comment by dhgarrette** [comment]
@som-snytt, Now updated with a fix for that one too.

**Comment by dhgarrette** [comment]
review by @heathermiller

**Comment by gkossakowski** [comment]
LGTM.

@som-snytt, feel free to steal some reviews and stamp pull requests with LGTM yourself.

**Comment by som-snytt** [comment]
@gkossakowski OK. Didn't want to overstep by straying outside my domain of expertise, viz, 7-bit ASCII minus some of those weird control chars.

**Pull request merged**
