### PR TITLE
ever catch a falling STARR?

### LINKED ISSUE #605: re-STARR (February 2019)
it's been quite a while (scala/scala#7430) since we re-STARRed

and the desire for it came up at https://github.com/scala/scala/pull/7069 /cc @som-snytt 

Adriaan suggested re-STARR-ing after the RC1 queue is empty, but I'd like to do it now, also. if nothing goes wrong, then no harm done, and if something does go wrong, we'll have bought ourselves more time to deal with it

### PR DESCRIPTION
**Pull request by SethTisue**
fixes scala/scala-dev#605

### CODE REVIEW

**Comment by SethTisue** [comment]
```
!! 15 - jvm/future-spec                           [output differs][duration 18.30s]
% diff /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/jvm/future-spec.check /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/jvm/future-spec-jvm.log
@@ -1 +1,137 @@
 warning: there were 5 deprecation warnings (since 2.13.0); re-run with -deprecation for details
+A future with custom ExecutionContext should:
+- shouldHandleThrowables
+[FAILED] java.lang.AssertionError: assertion failed: 2 is not 4
```

2 is not 4. it is inarguable

**Comment by som-snytt** [comment]
I also just had a spurious failure in future-spec. Thought I'd browse recent failures for it.

https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/7286/testReport/junit/test.files/jvm/future_spec/

```
!! 12 - jvm/future-spec                           [output differs][duration 19.53s]
% diff /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/jvm/future-spec.check /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/jvm/future-spec-jvm.log
@@ -1 +1,137 @@
 warning: there were 5 deprecation warnings (since 2.13.0); re-run with -deprecation for details
+A future with custom ExecutionContext should:
+- shouldHandleThrowables
+[FAILED] java.util.concurrent.TimeoutException: Future timed out after [5 seconds]
+scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:213)
+scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:226)
+scala.concurrent.Await$.$anonfun$result$1(package.scala:197)
+scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
+scala.concurrent.Await$.result(package.scala:124)
+FutureTests.$anonfun$new$2(FutureTests.scala:71)
+scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
+MinimalScalaTest$$anon$1.in(main.scala:54)
+sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
+sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+java.lang.reflect.Method.invoke(Method.java:498)
+FutureTests.$anonfun$new$1(FutureTests.scala:38)
+MinimalScalaTest$$anon$1.should(main.scala:48)
+sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
+sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+java.lang.reflect.Method.invoke(Method.java:498)
+FutureTests.<init>(FutureTests.scala:38)
+Test$.main(main.scala:13)
+Test.main(main.scala)
```
versus
```
!! 15 - jvm/future-spec                           [output differs][duration 18.30s]
% diff /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/jvm/future-spec.check /home/jenkins/workspace/scala-2.13.x-validate-main/test/files/jvm/future-spec-jvm.log
@@ -1 +1,137 @@
 warning: there were 5 deprecation warnings (since 2.13.0); re-run with -deprecation for details
+A future with custom ExecutionContext should:
+- shouldHandleThrowables
+[FAILED] java.lang.AssertionError: assertion failed: 2 is not 4
+MinimalScalaTest$$anon$2.mustBe(main.scala:68)
+sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
+sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+java.lang.reflect.Method.invoke(Method.java:498)
+FutureTests.$anonfun$new$2(FutureTests.scala:73)
+scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
+MinimalScalaTest$$anon$1.in(main.scala:54)
+sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
+sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+java.lang.reflect.Method.invoke(Method.java:498)
+FutureTests.$anonfun$new$1(FutureTests.scala:38)
+MinimalScalaTest$$anon$1.should(main.scala:48)
+sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
+sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
+sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
+java.lang.reflect.Method.invoke(Method.java:498)
+FutureTests.<init>(FutureTests.scala:38)
```

**Comment by som-snytt** [comment]
I understand that the worker thread isn't scheduled in the first case, so no work is done, and the test thread times out waiting for it.

In the second case here, the intention is to create a single-threaded pool by using parallelism = 1, which should ensure that `map` also forces side-effects. Increasing parallelism shows the race condition. What assumption is broken in the test case that failed here?

**Pull request merged**
