### PR TITLE
Moves annotationError outside typedAnnotation

### PR DESCRIPTION
**Pull request by xeno-by**
This refactoring allows everyone from the compiler, e.g. the macro engine
which expands annotation-emitting macros, to produce annotation errors.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @lrytz @hubertp

**Comment by hubertp** [comment]
lgtm

**Comment by adriaanm** [comment]
unfortunately, this is not forward compatible -- please move it to macro-paradise for now

**Comment by adriaanm** [comment]
(https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/IApLHqVt-9M)

**Pull request closed without merging**
