### PR TITLE
Temporarily insource Scalacheck

### PR DESCRIPTION
**Pull request by retronym**
This is a temporary measure until we release Scala
2.12.0. It means we are able to release milestones,
and RCs of Scala without needing a public release of
Scalacheck.

After we release Scala 2.12.0, we'll revert to a binary
dependency on the standard Scalacheck.

This uncovered an existing bug in our SBT build related to
STARR being favoured on the classpath when performing test
discovery. This has be worked around by customizing the
`testLoader` setting.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @szeiger

**Comment by szeiger** [comment]
Should we merge https://github.com/scala/scala/pull/5190 first (it only needs a final approval, everything is ready) and port it to 2.12.x? This would avoid conflicts in build.sbt and make CI run with sbt (since the ant build is not being updated here). Is sbt sufficient anyway? `bootstrap` still uses ant at the moment.

**Comment by retronym** [comment]
@szeiger Yes, let's merge the SBT changes first, then merge to 2.12.x, then rebase this PR. I'll also add Ant changes.

**Comment by adriaanm** [comment]
SBT changes in #5190 are now in 2.12.x via #5242

**Pull request closed without merging**
