### PR TITLE
SI-6280 Scaladoc: Reloading preserves anchors

### PR DESCRIPTION
**Pull request by VladUreche**
Scaladoc redirects from */package.html pages to index.html with the
qualified package name as the anchor. This is done to pop up the left
navigation panel whenever someone links directly to the page. (so
users may navigate the rest of the scaladoc pages)

When linking members directly, one can use _/package.html#<signature>,
which translates to index.html#_.package@<signature>. The problem was
that the redirection javascript did not take the <signature> into
account, so it would redirect to the top of the package page instead
of scrolling to the member.

Note: this is a layout change, so there's no test for it.

### CODE REVIEW

**Comment by VladUreche** [comment]
Review by anyone who's around these days, it's 5 lines of javascript really.

**Comment by xeno-by** [comment]
Does this work in Opera? :)

**Comment by VladUreche** [comment]
I just fired up jenkins to build the branch. Can you please try it out once it's built? (I don't have Opera on my machine)

The following link should take you to def breakout in scala.collection: https://scala-webapps.epfl.ch/jenkins/view/scaladoc/job/scaladoc-diagram-nightly/ws/build/scaladoc/library/scala/collection/package.html#breakOut[From,T,To](CanBuildFrom[Nothing,T,To]):CanBuildFrom[From,T,To]

**Comment by xeno-by** [comment]
Huh neat! It didn't work before, now it does :)

**Comment by VladUreche** [comment]
Review by @heathermiller, since nobody else dares review my 5 lines of javascript :p

**Comment by heathermiller** [comment]
LGTM! (In the future, just mention me from the start)

**Pull request merged**
