### PR TITLE
Closes SI-6072, crasher with overloaded eq.

### PR DESCRIPTION
**Pull request by paulp**
You don't want to do name-based selections in later phases
if you can help it, because there is nobody left to resolve
your overloads.  If as in this example you're calling a
known method, use the symbol.  Review by @hubertp.

### CODE REVIEW

**Comment by hubertp** [comment]
Awesome, thanks Paul. It must have been really late as I couldn't see the reduced test.
lgth.

**Comment by retronym** [comment]
Next cab off the rank: https://issues.scala-lang.org/browse/SI-6090

**Comment by paulp** [comment]
Funny, I had the same idea about doing some cabspotting.  I made a warning (I don't know if it has false positives yet.)

```
a.scala:6: warning: Select received overloaded type during posterasure, but typer is over.
We are likely doomed to crash in the backend.
new ...#X.<init>().== has these overloads:
  <method> <triedcooking> def ==(<param> other: ...#X): ...#Nothing
  <method> final <triedcooking> def ==(<param> <synthetic> x$1: ...#Object): ...#Boolean

    new V(new X) == new V(new X)
                 ^
java.lang.Throwable
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedSelect$1(Typers.scala:4398)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5096)
    at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:748)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5203)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$88.apply(Typers.scala:4240)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$88.apply(Typers.scala:4240)
    at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:728)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4240)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5032)
    at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:748)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5203)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5254)
    at scala.tools.nsc.transform.PostErasure$PostErasureTransformer.transform(PostErasure.scala:58)
    at scala.tools.nsc.transform.PostErasure$PostErasureTransformer.transform(PostErasure.scala:32)
```

**Comment by retronym** [comment]
Oh that's nice a nice dragnet; assuming you've get enough obscure routes to exercise the compiler's mastery of [The Knowledge](http://en.wikipedia.org/wiki/Taxicabs_of_the_United_Kingdom).

[SI-6091](https://issues.scala-lang.org/browse/SI-6091) demonstrates another class of problems.

**Comment by hubertp** [comment]
heh, I only looked into Mixin for similarities. Should have been more persistent.

**Pull request merged**
