### PR TITLE
SI-8926 default visbility RUNTIME for java annotations

### PR DESCRIPTION
**Pull request by lrytz**
When parsed from source, java annotation class symbol are lacking the
`@Retention` annotation. In mixed compilation, java annotations are
therefore emitted with visibility CLASS.

This patch conservatively uses the RUNTIME visibility in case there is
no @Retention annotation.

The real solution is to fix the Java parser, logged in SI-8928.

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @soc, @gkossakowski

**Comment by soc** [comment]
LGTM.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
(Cross-ref with #4026, where it regressed, for future reference.)

**Comment by lrytz** [comment]
See also https://github.com/sbt/website/pull/64

**Pull request merged**
