### PR TITLE
SI-4438 PC Completer, SI-1931 Hide any+str in REPL, SI-5408 Post paste prompt

### PR DESCRIPTION
**Pull request by som-snytt**
The presentation compiler completer is the result of a weekend retreat on which they had nothing better to do. The completion strategy can be selected with `-Ycompletion:pc,adhoc,none`.

The usual trick for hiding `any2stradd` works in REPL.

After pasting a partial transcript in REPL, it will return you to the prompt to finish the code, e.g., if you want to modify a function def.

The merge conflicts over jline refactors and repl imports are surmounted.

### CODE REVIEW

**Comment by som-snytt** [comment]
Just one of those things. I'll let the professionals take a look.

FATAL: Failed to fetch from https://github.com/scala/scala.git
hudson.plugins.git.GitException: Failed to fetch from https://github.com/scala/scala.git
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:623)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:855)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:880)

**Comment by adriaanm** [comment]
My Jenkins school tuition is really paying off. Acutely out of disk space. Cleaning up his litter box.

**Comment by som-snytt** [comment]
I think you must have been on scholarship.

**Comment by adriaanm** [comment]
Actually, jenkins school pays you to attend.

**Comment by adriaanm** [comment]
I think GitHub shows them in commit date order, not topological order.

**Comment by lrytz** [comment]
yeah, and they use a too coarse time unit. after re-basing multiple commits (making their timestamps very close), they usually show up in the wrong order on github.

**Comment by retronym** [comment]
@som-snytt Thanks for getting this into shape!

I've refactored things a little here: https://github.com/retronym/scala/tree/review/4659

I'm trying to decouple the useful parts from the REPL as much as possible, might move some of it back into src/interactive. Also trying to avoid making assumptions about how the UI works (e.g. we shouldn't filter the list of members ahead of time.)

I'll continue on that branch tomorrow.

**Comment by retronym** [comment]
I've pushed a few more functional improvements. Give it a try side-by-side with the old completion and let me know if you find any differences, I think we're getting close to parity with the subtle details of the way multiple TABs are treated.

**Comment by som-snytt** [comment]
@retronym I haven't had time yet, but the unfiltered `<init>` is a poke in the eye. I'll be away soon, but I'll take a quick look.

It annoyed me that `// show` doesn't show you what is compiled, so console line numbers correspond to nothing you can witness. I tried a quick pos fix as for ScriptSource, but now wonder if it would be neat to report `$line` the package name. Or maybe lines in history. That doesn't address the use case of stable lines for testing. `-Dscala.repl.lines=source,input,history`.

**Comment by som-snytt** [comment]
@retronym I tried it out but didn't see the tabbing detail. One idea is likely candidates, then extension methods, then Any methods. The thing I was going to address is sorting the results.

**Comment by retronym** [comment]
Closing in favour of #4725

**Pull request closed without merging**
