### PR TITLE
NullPointerException when putting a Singleton type in an AnyVal

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
scala/bug#11659

emit Field while field is `SingletonType`

### CODE REVIEW

**Comment by SethTisue** [comment]
Would the tests also pass if you changed the definition of `memoizeValue` itself, instead of only changing one of the call sites? (Or even if they do pass, could a test be constructed that would fail?)

**Comment by jxnu-liguobin** [comment]
> Would the tests also pass if you changed the definition of `memoizeValue` itself, instead of only changing one of the call sites? (Or even if they do pass, could a test be constructed that would fail?)

My test passed, but I didn't try to trigger CI. So I'm not sure. I'll try it when I'm free.

**Comment by dwijnand** [comment]
The default definition of `memoizeField` is 

```scala
def memoizeValue(sym: Symbol) = 
  !sym.info.resultType.isInstanceOf[FoldableConstantType]
```

Which makes

```scala
if (emitField || statSym.info.resultType.isInstanceOf[SingletonType])
```

an obfuscated way of saying `if (true)`.

In order to merge this I feel we should review the whole notion of not emitting fields, and figure out why this is tripping up the usage here.  How are non-initialised foldable fields being used in other contexts?  When does the constant folding happen (what phase)?  Why isn't it happening here?

So, instead of re-emitting the field, can we find the fix to make it emit:

```scala
scala.Predef.println(new Foo("x"))
```

?

**Comment by SethTisue** [comment]
On the one hand the change here progresses a test case and the other tests still pass. So that argues for this being mergeable.

On the other hand, Dale and I are concerned about regressions that wouldn't show up as test failures; emitting an unnecessary field doesn't fail tests but does bloat JARs a little and could impact performance a little.

So I'm not confident the risk/reward ratio here is good, given that the bug is longstanding and doesn't seem to be one that people hit often. (Though admittedly a runtime crash is pretty bad. We never want to blow up at runtime for no good reason, so that argues for the bug being significant enough to address.)

@jxnu-liguobin Did you pick this bug because you have a real interest in seeing it fixed, or were you just trying to be helpful and learn things? If you feel the issue really deserves a fix, then we can go deeper into this (and maybe we can nerd-snipe @som-snytt into weighing in further), but as Dale indicates above, the water here might be deeper than you would have hoped.

**Comment by jxnu-liguobin** [comment]
> Did you pick this bug because you have a real interest in seeing it fixed, or were you just trying to be helpful and learn things? If you feel the issue really deserves a fix, then we can go deeper into this (and maybe we can nerd-snipe

I'm amazed at runtime errors. But considering the performance, it is understandable not to repair.

**Comment by SethTisue** [comment]
I see that actually this did regress other tests :-)

**Comment by jxnu-liguobin** [comment]
> I see that actually this did regress other tests :-)

it seems that we can't do this. Waiting for a better solution

**Comment by SethTisue** [comment]
Is there anyone watching the repo who has an interest in this and wants to see if there is a way for it to progress?

**Comment by SethTisue** [comment]
Closing for inactivity, since this seems stalled. (As always, we can reopen a stale PR if activity resumes.)

**Pull request closed without merging**
