### PR TITLE
Bug#10324 Check whether a directory can be read before trying to list its files while looking for classpath entries.

### PR DESCRIPTION
**Pull request by izeigerman**
Fix for https://github.com/scala/bug/issues/10324 . 
The root cause is described here: https://github.com/scala/bug/issues/10324#issuecomment-372034617

### CODE REVIEW

**Comment by izeigerman** [comment]
The CLA has been signed.

**Comment by izeigerman** [comment]
@SethTisue please review.

**Review by SethTisue — APPROVED** [review]
LGTM

(one wonders whether there are other `isDirectory` calls in the compiler that ought to be similar protected. but, I don't think we need to go on a fishing expedition to try and find out.)

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
