### PR TITLE
SI-1672 Catches are in tail position without finally.

### PR DESCRIPTION
**Pull request by retronym**
So we can eliminate tail calls within.

Review by @dragos, who once opined "I think this is safe as long as there is no `finally`".

### CODE REVIEW

**Comment by dragos** [comment]
I'd add a test with a try inside an expression where the evaluation stack is not be empty, say 

```
b || try { .. } catch { recursiveCall(..) }
```

this is because later in `uncurry` (not sure about the phase actually), `try` expressions like these are lifted to local methods because of the way exceptions clean the stack on `throw`.

Another interesting test case is a tail recursive call inside a catch inside a catch:

```
try {
..
} catch {
  try {.. } catch { recursiveCall(..) }
}
```

I'd also make sure some of these tests get to run, as the verifier gets picky when it comes to exception handlers and interesting jumps.

**Comment by retronym** [comment]
Thanks for the fast feedback; I'll try out all those ideas.

**Comment by retronym** [comment]
@dragos tests added.

**Comment by dragos** [comment]
LGTM, sorry for being slow on this one.

**Pull request merged**
