### PR TITLE
Address/workaround issue SI-3452 and related problems

### PR DESCRIPTION
**Pull request by Blaisorblade**
The content is discussed in the bug tracker: https://issues.scala-lang.org/browse/SI-3452?focusedCommentId=57712#comment-57712

This pull request should therefore be reviewed by Paul Phillips. To express this, based on 
https://issues.scala-lang.org/browse/SI-4461?focusedCommentId=57692#comment-57692, I'm adding the following tags (sorry for the noise if it's not the correct way, I did not find relevant docs).

review by @extempore
review by @paulp

### CODE REVIEW

**Comment by lrytz** [comment]
@magarciaEPFL @gkossakowski can you please review?

**Comment by Blaisorblade** [comment]
FYI, I and Paul Phillips are still discussing commit 244a1e1 in the bug tracker entry; please feel free to review the rest.

**Comment by gkossakowski** [comment]
I'll review it more carefully tomorrow but it looks fine to me.

**Comment by Blaisorblade** [comment]
Quoting from Paul Phillips:

> Signature verification wasn't on by default for performance reasons, so you will probably want to measure the asm impact.

@magarciaEPFL this verification comes from your code (the GenASM backend), do you have an idea whether this concern is motivated?

I could try some serious benchmarking, but it would take more time than writing this little code.

Also, there are some (unreliable) data from the build bot:

//a pristine compiler (starr) compiling locker:
[stopwatch] [locker.lib.timer: 1:58.526 sec]
[stopwatch] [locker.comp.timer: 3:56.169 sec]

//the altered compiler (locker) compiling quick:
[stopwatch] [quick.lib.timer: 2:44.179 sec]
[stopwatch] [quick.comp.timer: 3:58.680 sec]

We should conclude that there's negligible difference on the compiler but a lot of difference on the library - if the machine is otherwise idle (which I wouldn't really expect). The simplest explanation is that the slowdown is due to external load on the machine, but of course it could not be.

Still, there are currently incorrect binaries being produced, which sounds more important than performance.

**Comment by magarciaEPFL** [comment]
Regarding performance of 

``` scala
SignatureChecker checkMethodSignature sig
SignatureChecker checkFieldSignature  sig
SignatureChecker checkClassSignature  sig 
```

perhaps avoiding calls to `getChar(String, Int)` would make them faster, ie. scanning automata-like an `Array[Char]` . Additionally, returning `false` rather than throwing an exception would spare the try-catch in GenJVM and GenASM. 

I guess that can be discussed at the ASM mailing list http://mail.ow2.org/wws/info/asm

That's a good thing about ASM. Contributions as two-way street (plus, you get code review by ASM authors for free).

**Comment by lrytz** [comment]
@Blaisorblade the "locker.lib" builds less files than "quick.lib" (actors, swing)

**Comment by Blaisorblade** [comment]
@lrytz Ah good, that makes sense.

Given that, it sounds like performance should be fine; if you require it to accept the pull request, I would try profiling the bootstrapping process to verify if the new code shows up in profiling, but I would assume it doesn't.

> perhaps avoiding calls to getChar(String, Int) would make them faster, ie. scanning automata-like an Array[Char]
> I assume that `Scanner` in `src/compiler/scala/tools/nsc/ast/parser/Scanners.scala` should be efficient enough. Assuming a sufficiently smart JIT inlining as much as possible, the difference is that strings have also their own displacement.

I investigated whether a lexer generator would work, but I'd guess that the language of generic signatures is not regular; note the mutual recursion on FieldTypeSignature -> ClassTypeSignature -> SimpleClassTypeSignature -> TypeArguments -> TypeArgument -> FieldTypeSignature:
http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3.4

Anyway, 

> Additionally, returning false rather than throwing an exception would spare the try-catch in GenJVM and GenASM.

That should only be a performance problem if there are a lot of exceptions, since try is for free.
I currently have results only _with_ Paul Philipps' commit on top, i.e. paulp/scala@11c11f0efc, but they show that when building the whole quick, only 47 files give warnings (and only 99 ones).

# Statistics on warnings, with this pull request + paulp/scala@11c11f0efc:

Legend: N. warnings, n. files with warnings, average warnings per affected file.

```
$ grep 'warning: compiler bug: created generic signature' testLog-v2.10.0-M3-322-gc2cb4d9-20120521-04.44|sed -ne 's!\[scalacfork\] \([A-Za-z/.]*\):.*!\1!p'|uniq -c|awk '{sum+=$1} END {print sum, NR, sum/NR}'
99 47 2.10638
```

Files and warnings:

```
$ grep 'warning: compiler bug: created generic signature' testLog-v2.10.0-M3-322-gc2cb4d9-20120521-04.44|sed -ne 's!\[scalacfork\] \([A-Za-z/.]*\):.*!\1!p'|uniq -c|sort -nrk1
  11 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/ParIterableLike.scala
  10 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/ParIterableViewLike.scala
   9 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/ParSeqViewLike.scala
   8 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/ParSeqLike.scala
   6 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/Actor.scala
   5 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/InternalActor.scala
   3 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/InternalReplyReactor.scala
   3 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/Channel.scala
   2 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/Predef.scala
   2 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/cmd/CommandLine.scala
   2 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/ReactChannel.scala
   2 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/InputChannel.scala
   2 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/Future.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/swing/scala/swing/SwingWorker.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/scalacheck/org/scalacheck/Test.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/partest/scala/tools/partest/nest/Worker.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/util/parsing/json/Parser.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/util/parsing/combinator/testing/RegexTest.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/util/parsing/combinator/syntactical/StandardTokenParsers.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/util/parsing/combinator/lexical/Lexical.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/util/parsing/combinator/Parsers.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/runtime/AbstractPartialFunction.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/concurrent/ops.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/mutable/ParHashMap.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/immutable/package.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/ParSeqView.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/parallel/ParIterableView.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/collection/TraversableViewLike.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/library/scala/Responder.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/util/CommandLineParser.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/typechecker/TreeCheckers.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/typechecker/Namers.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/typechecker/Duplicators.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/transform/Erasure.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/matching/Patterns.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/javac/JavaParsers.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/interpreter/ReplGlobal.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/ReflectGlobal.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/nsc/Global.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/cmd/package.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/tools/cmd/Parser.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/reflect/runtime/Universe.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/compiler/scala/reflect/runtime/SynchronizedOps.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/remote/Proxy.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/Reactor.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/ActorProxy.scala
   1 /Users/pgiarrusso/Documents/Research/Sorgenti/scala/src/actors/scala/actors/ActorCanReply.scala
```

**Comment by adriaanm** [comment]
we've sneakily introduced a pull request policy since you submitted this one: https://github.com/scala/scala/wiki/Pull-Request-Policy

it makes you responsible for choosing/prodding your reviewers :-)

**Comment by Blaisorblade** [comment]
That's good, I'll keep you updated - I already identified and fixed (somewhat reasonably) the two most common sources of the warnings I see; I'll contact scala-internals over the weekend for these changes and SI-3452 (those changes are a bit less trivial).

**Comment by Blaisorblade** [comment]
I'm preparing a better pull request with more fixes, which will require new testing, hence I am closing this one; I will contact scala-internals soon.

**Pull request closed without merging**
