### PR TITLE
Use URI to compute Scaladoc URI [ci: last-only]

### LINKED ISSUE #12846: Scaladoc 2.13.11 failing on illegal URI character in file name
## Reproduction steps

Scala version: 2.13.11

```scala
final case class `X-Upload-Content-Type` private (contentType: ContentType)
```

Run scaladoc (i.e. `doc` in sbt) to generate Scaladoc from the above Scala code

## Problem

With the above code I get the following error

```
[error] java.net.URISyntaxException: Illegal character in path at index 143: https://github.com/apache/incubator-pekko-connectors/tree/main/google-common/src/main/scala/org/apache/pekko/stream/connectors/google/scaladsl/`X-Upload-Content-Type`.scala#L37
```

This appears to be a regression in Scala 2.13.11 as it works fine in Scala 2.13.10, see https://github.com/apache/incubator-pekko-connectors/pull/139 for more context

Complete stacktrace can be seen here https://gist.github.com/mdedetrich/43d822f08e329f98d72e8131fd807e94

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12846

`toUri` will perform escapes, but `URI` constructor will not.

Also clean up some imports. Avoid `collection._`. Prefer `raw"".r` for constructing a regex.

### CODE REVIEW

**Comment by som-snytt** [comment]
That test seems to succeed trivially, because of course it does.

(I tested manually.)

**Comment by som-snytt** [comment]
Adjusted the milestone because it is a regression, and because of the terribly important adjustments to imports in the code base.

**Comment by som-snytt** [comment]
Learned the minimum (barely) about `ScaladocModelTest` to output the computed URL in the test.

**Review by lrytz — APPROVED** [review]
Dankeschön!

**Pull request merged**
