### PR TITLE
SI-5994 battling implicits for String.lines

### PR DESCRIPTION
**Pull request by Ichoran**
Deprecated ProcessBuilder's lines method and renamed it streaming.

stream was another possibility, but that seemed more likely to cause conflicts.

Also updated tutorial in ProcessBuilder.

I am sure this will break some tests, but because of the name conflict it's hard to be sure where they are.  So Jenkins gets to find the problems for me.

### CODE REVIEW

**Comment by dcsobral** [comment]
What about streamLines instead?

**Comment by Ichoran** [comment]
I considered that, but this is inconsistent with the naming scheme in the rest of the class.  Everything is very brief.  But if streamLines is more popular, I can of course switch.

**Comment by som-snytt** [comment]
I don't envy you this simple task.

My first reaction: streaming is "live streaming."  How about "lineStreaming" (jokey pun).

Then there is "streamLiner" by reference to the Dreamliner aircraft that suffers from battery fires.

More soberly, there's outputLines, linesOfOutput, outputAsLines.

Also lineByLine, or byLine.  But that invites future conflict, as you point out.

By "Everything is very brief" I guess you don't mean "!".  Because that's a hard act to follow.

But wait a sec, if the problem is to distinguish "lines", then why not just add a useful operator char?

E.g., change `lines` to `lines_?` and be done.  Or `lines_>`. Etc.

**Comment by dcsobral** [comment]
Or `lineStream`. I think that looks better than `streamLines`, and `toLineStream` doesn't make sense, since there's no `Line` type.

**Comment by gourlaysama** [comment]
+1 for `lineStream`. It is short and unambiguous.

**Comment by gkossakowski** [comment]
@Ichoran: ping

**Comment by gkossakowski** [comment]
I also like `lineStream`.

**Comment by Ichoran** [comment]
@gkossakowski - lineStream it is.

**Comment by gkossakowski** [comment]
LGTM.

**Pull request merged**
