### PR TITLE
SI-4339 Backpatch event errors and attr fix

### PR DESCRIPTION
**Pull request by som-snytt**
Improve attribute parsing and propagate errors
across event thread. Otherwise tests just hang.

### CODE REVIEW

**Comment by som-snytt** [comment]
Mima!

**Comment by som-snytt** [comment]
Fixed the test, which asserted a design flaw.

**Comment by gkossakowski** [comment]
@som-snyt: what's the status of this PR?

**Comment by som-snytt** [comment]
The status is no one cares about xml. There were a cluster of something last year related to xml. I thought it all started with sbt. The lesson is don't waste everyone's time with unprioritized PRs. It only tries Jenkins' patience.

**Comment by gkossakowski** [comment]
Shall we reap your investment by merging this?

**Comment by som-snytt** [comment]
@gkossakowski In that sense, the status is this is my best shot. The tests pass. It is reapable.

**Comment by gkossakowski** [comment]
LGTM

**Comment by som-snytt** [comment]
@gkossakowski  Thanks for reviewing.

**Pull request merged**
