### PR TITLE
SI-8657 don't miss tailrec defs in more positions

### PR DESCRIPTION
**Pull request by jrudolph**
1) First operand of boolean expression using `&&` or `||`. Second operands of those boolean exprs were already treated specially here but handling for first operands was missing.
2) Condition of `If`. Also added a test for guards.

### CODE REVIEW

**Comment by jrudolph** [comment]
Supersedes #3831.

**Comment by jrudolph** [comment]
It seems I changed some whitespace in a test after writing the check file so the line numbers weren't accurate any more. 

I fixed the commit. Is jenkins automatically picking up `git push -f` changes?

**Comment by jrudolph** [comment]
> Is jenkins automatically picking up git push -f changes?

Seems so...

**Comment by retronym** [comment]
Failing IDE test. It might be a flaky test, I'll retry.

```
Results :

Tests in error: 
  previousVersionBuildSucceeds(org.scalaide.core.sbtbuilder.MultiScalaVersionTest): Marker id 126 not found.
```

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
LGTM, thanks!

**Pull request merged**
