### PR TITLE
Fix inverted condition in s.c.c.Map#filterInPlaceImpl

### PR DESCRIPTION
**Pull request by NthPortal**

### CODE REVIEW

**Comment by NthPortal** [comment]
genuinely quite surprised this only broke one test in the community build. a bit concerned, even

**Comment by SethTisue** [comment]
> genuinely quite surprised this only broke one test in the community build. a bit concerned, even

perhaps there's some missing tests in https://github.com/scala/scala-collection-laws

**Review by johnynek — APPROVED** [review]

**Comment by NthPortal** [comment]
might be time for me to poke at collection-laws

**Comment by SethTisue** [comment]
> genuinely quite surprised this only broke one test in the community build. a bit concerned, even

turns out it's two repos, actually. the twitter-util hang was preventing other projects from running, but once I excluded that test, there were test failures in sbt-io

I verified just now that this PR (2.13.7-bin-4bfd6ae-SNAPSHOT) fixes both repos 👍

**Comment by lrytz** [comment]
uh oh... sorry i didn't catch this while reviewing

**Comment by NthPortal** [comment]
it's no worries. it's *really* subtle, and we didn't catch it either

**Pull request merged**
