### PR TITLE
use Travis for (vastly simpler) PR validation

### PR DESCRIPTION
**Pull request by SethTisue**
use only sbt, avoid using external shell scripts and environment
variables.  we just need a few simple commands right here in
`.travis.yml`

doesn't publish anything to Artifactory.  let's discuss the way
forward on that at https://github.com/scala/scala-dev/issues/507

see #6621 for previous tortuous flailings on this, this PR is
the cleaned up version

### CODE REVIEW

**Comment by SethTisue** [comment]
* at 11 minutes, `publishLocal` finishes
* at 22 minutes, `test:compile` (which rebuilds library/compiler/reflect too, since STARR has changed) finishes and tests start to run
* at 25 minutes, `junit/test` finishes
* at 41 minutes, `scalacheck/test` finishes (nearly all of this time is spent on parallel collections which are out on 2.13.x)
* at 85 minutes, the whole thing finishes (mostly partest run tests)

by comparison, the Jenkins 2.12 job timings are typically 50–70 minutes, 2.13 timings are 25–60 minutes, depending on how much else the behemoths are doing

I see a comment in the config file about maybe paying Travis-CI for faster “premium” instances. note that we could free up $$$ by shutting down most of our Jenkins nodes — both publishing nodes, and 1 or 2 behemoths.

**Review by lrytz — APPROVED** [review]
Looks good for a first step! Since jenkins is still doing its thing, we can go step by step for travis.

**Comment by SethTisue** [comment]
yeah so we'll need to:

* merge this onto 2.13.x too
* let time pass, since in-flight PRs won't pick it up until next rebase
* let even more time pass and see how it goes on actual PRs
* other todos at https://github.com/scala/scala-dev/issues/507
* .......
* eventually disable the Jenkins checks once we're satisfied

but, good to have this in motion.

**Comment by SethTisue** [comment]
merge to 2.13.x: https://github.com/scala/scala/pull/6651

**Pull request merged**
