### PR TITLE
Merge 2.12 to 2.13 mar 20

### PR DESCRIPTION
**Pull request by lrytz**
```
 scala3 git:(2.13.x) git checkout -b merge-2.12-to-2.13-mar-20
Switched to a new branch 'merge-2.12-to-2.13-mar-20'
 scala3 git:(merge-2.12-to-2.13-mar-20) export mb=$(git merge-base upstream/2.12.x 2.13.x)
 scala3 git:(merge-2.12-to-2.13-mar-20) git log --graph --oneline --decorate $mb..upstream/2.12.x | cat
* 005dcf91ab (upstream/2.12.x) Merge pull request #6444 from lrytz/travis-fixes
* 363c377f5e remove some cruft in bash scripts
* a111acb1ab Fix return value of sbtResolve
 scala3 git:(merge-2.12-to-2.13-mar-20) git merge upstream/2.12.x
Auto-merging scripts/common
Merge made by the 'recursive' strategy.
 scripts/common | 49 ++++---------------------------------------------
 1 file changed, 4 insertions(+), 45 deletions(-)
```

### CODE REVIEW

**Comment by lrytz** [comment]
review by @szeiger

**Comment by retronym** [comment]
Does this address the:

```
[error] (compiler/*:update) sbt.ResolveException: unresolved dependency: org.scala-lang.modules#scala-xml_2.13.0-pre-1002705;1.1.0: not found
[error] Total time: 304 s, completed Mar 17, 2018 6:38:52 PM
```

failures as seen since https://travis-ci.org/scala/scala/jobs/354791778 ?

**Comment by lrytz** [comment]
That's the goal!

**Comment by retronym** [comment]
I tried running the old [boostrap-benchmark job on 2.13.x](https://scala-ci.typesafe.com/view/scala-bench/job/bootstrap-benchmark/642/console) (trying to get a build to run a benchmark), but ran into:

```
+++ sbt -sbt-version 0.13.17 -sbt-version 0.13.17 -ivy /home/jenkins/workspace/bootstrap-benchmark/.ivy2 -Dsbt.override.build.repos=true -Dsbt.repository.config=/home/jenkins/workspace/bootstrap-benchmark/scripts/sbt-repositories-config 'set baseVersionSuffix in Global := "SHA"' generateBuildCharacterPropertiesFile
[info] Loading global plugins from /home/jenkins/.sbt/0.13/plugins
[info] Updating {file:/home/jenkins/.sbt/0.13/plugins/}global-plugins...
[info] Resolving com.typesafe.sbt#sbt-pgp;0.8.1 ...

[info] Resolving com.typesafe.sbt#sbt-pgp;0.8.1 ...
[warn] 	module not found: com.typesafe.sbt#sbt-pgp;0.8.1
[warn] ==== local: tried
[warn]   /home/jenkins/workspace/bootstrap-benchmark/.ivy2/local/com.typesafe.sbt/sbt-pgp/scala_2.10/sbt_0.13/0.8.1/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/jenkins/.sbt/preloaded/com.typesafe.sbt/sbt-pgp/0.8.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/jenkins/.sbt/preloaded/com/typesafe/sbt/sbt-pgp_2.10_0.13/0.8.1/sbt-pgp-0.8.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-pgp_2.10_0.13/0.8.1/sbt-pgp-0.8.1.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-pgp/0.8.1/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-pgp/0.8.1/ivys/ivy.xml
```

Not sure if that job is meant to work any more, so this is just FYI.

**Review by retronym — APPROVED** [review]

**Comment by lrytz** [comment]
Yeah, the pgp thing is a known issue, just haven't gotten around to fix it. The bootstrap job is supposed to work on jenkins too.

**Comment by retronym** [comment]
https://travis-ci.org/scala/scala/jobs/356308750 🍏

**Comment by retronym** [comment]
But:

image

**Comment by retronym** [comment]
I was impatient, [benchmark is running now](https://scala-ci.typesafe.com/view/scala-bench/job/compiler-benchmark/1054/console).

**Comment by lrytz** [comment]
yay! :-)

**Pull request merged**
