### PR TITLE
Correct a typo.

### PR DESCRIPTION
**Pull request by shlomif**
Inspired by this bug report from Debian:

https://rt.cpan.org/Ticket/Display.html?id=85962 .

### CODE REVIEW

**Comment by paulp** [comment]
Can you please batch changes of this nature? I would place the minimum threshold for opening a pull request at perhaps one hundred inconsequential spelling mistakes. Please consider the fact that we have incredibly limited resources, and every pull request consumes some of those resources.

**Comment by som-snytt** [comment]
What if, @paulp , the PR validator didn't fail for spelling errors but, at some threshold, auto-created a ticket.  If there is already such a ticket, update it. Then someone of the spelling persuasion could have at it. Or, they would have something to have at.

**Comment by paulp** [comment]
Some sort of accumulation mechanism sounds nice in theory; in practice it will suffer from the same problem, that the imposition levied on the time of the few will never be low enough. Certainly anything which requires code to be written and maintained is already a lose when we are talking about correcting spelling errors, something which can already be done opportunistically and which humans are quite capable of batching without machine assistance.

**Comment by paulp** [comment]
Oh, and to clarify, the limited resources to which I referred were not machines to run the test suite, but humans to look at the pull request.

**Comment by som-snytt** [comment]
The day after the annual doc spree, they can hold the annual spelling spree.

Very wise to note that no code is so trivial that it's not work.  Recently, I looked at the history of SyncVar.  It's just a var!  and it's sync'ed!

**Pull request closed without merging**
