### PR TITLE
improvements for type tags

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @paulp and/or @gkossakowski

**Comment by paulp** [comment]
I think WeakTypeTag is a great name, the best I've heard.

**Comment by xeno-by** [comment]
Credit goes to Martin - he suggested it yesterday at the meeting.

**Comment by xeno-by** [comment]
The failure is legitimate. I'm looking into it.

**Comment by jsuereth** [comment]
Cool, I was about to as well.

**Comment by xeno-by** [comment]
Manually cancelled the build. @jsuereth I thought the kitteh only rebuilds the pull request when you ask it to?

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Allright, guys, can I get an lgtm? This patch involves a new starr, so I'd love to have it in asap. /cc @paulp, @retronym

**Comment by paulp** [comment]
I think wannabe leaves something to be desired as far as parameter names go. Other than that, lgtm.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
