### PR TITLE
Rewrite of transformTypeTagEvidenceParams.

### PR DESCRIPTION
**Pull request by paulp**
This fixes what a bug where the prefix seems to be checked but
is ignored; however I rewrote this method purely out of a desire
for tighter code.  I would consider it a great personal
favor if you would study the before/after and endeavor to
internalize the mechanisms I applied.

Points of particular note:
- Before you write Option[Symbol], remember we already have
  an Option[Symbol], and it's Symbol.  None == NoSymbol.
- flatMap can be to an Option, you don't have to create a
  one element List for flatMap's enjoyment
- lastOption and headOption are rarely the way to go
  ... especially if you start with if (xs.isEmpty) return
- The method which checks for emptiness is ".isEmpty",
  it is NOT ".length == 0"

I should add a pattern matcher warning for when you have a lower
case name in scope (like "contextParam") and then use a lower case
pattern variable of the same name, which of course ignores the
one outside the pattern and matches everything.

Review by @xeno-by.

### CODE REVIEW

**Comment by xeno-by** [comment]
I'll incorporate this into my pull request. Let's close this one, because it will conflict with mine?

**Comment by xeno-by** [comment]
By the way it was really enlightening to study my own half-a-year-old code. Since my critical bugs are now fixed, it seems that now I should spend my free time cleaning up a long overdue mess.

**Comment by xeno-by** [comment]
@paulp I've already rebased my wip branch against this branch. Maybe we can close this pull request and let the kitteh have a rest?

**Comment by paulp** [comment]
Sure.

**Comment by xeno-by** [comment]
That was me aborting these jobs, so that they don't consume computational resources.

**Pull request closed without merging**
