### PR TITLE
Scala dist maven

### PR DESCRIPTION
**Pull request by adriaanm**
review by @gkossakowski

The idea is that a Scala distribution is a simple repackaging of artifacts already available on maven.

We already publish the following to maven: typical jars for the artifacts (classes, sources, scaladoc).
This PR adds: the bin/, doc/, and man/ directories, packaged up in scala-dist.

To simplify this, move the contents that should end up in the distribution
from docs/ to doc/, create the man/ directory with the manpages,
and include the scripts in bin/.

These directories are packaged in the scala-dist jar and published to maven,
with a dependency on scala-library-all and scala-compiler,
for the jars that should end up in the distribution.

This way, a scala dist can be built by resolving scala-dist,
and moving all the class-file jars of its depencies to lib/
(use api/ for scaladoc jars, and src/ for the source jars).

### CODE REVIEW

**Comment by adriaanm** [comment]
The corresponding dist-building work is happening in https://github.com/adriaanm/scala-dist/tree/dist-smplfy-211

**Comment by adriaanm** [comment]
Once this is merged, https://github.com/scala/jenkins-scripts/pull/68 should be merged and jenkins updated.

**Comment by adriaanm** [comment]
> > Remove @{dir} abstraction.
> 
> What was the purpose of this abstraction? Why it's not needed anymore?

we used to include the plugins, which were in a different directory from the other jars

**Comment by adriaanm** [comment]
I've addressed the previewer's feedback, and hopefully fixed the build glitches.

This is now ready for the official review, @gkossakowski

**Comment by adriaanm** [comment]
build passed: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1155/console

**Comment by gkossakowski** [comment]
LGTM.

Please merge whenever it's convenient.

**Comment by adriaanm** [comment]
Thanks! Just finished battle testing it on jenkins: https://scala-webapps.epfl.ch/jenkins/view/scala-release-2.11.x/job/scala-release-2.11.x/

**Pull request merged**
