### PR TITLE
Don't read dirs as jars

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes scala/bug#12019

### CODE REVIEW

**Comment by SethTisue** [comment]
```
error: java.lang.NullPointerException
	at java.util.Arrays.sort(Arrays.java:1438)
	at scala.tools.nsc.classpath.JFileDirectoryLookup.listChildren(DirectoryClassPath.scala:118)
	at scala.tools.nsc.classpath.JFileDirectoryLookup.listChildren$(DirectoryClassPath.scala:102)
```

**Comment by dwijnand** [comment]
Too low priority to investigate.

**Comment by som-snytt** [comment]
I had done a quickie but the test took me a while! I targeted the two places that test isJarOrZip.

**Comment by SethTisue** [comment]
#9034 is the new #9021

**Pull request closed without merging**
