### PR TITLE
Fix type of the custom `ClassTag` in `PatternMatching.scala`

### PR DESCRIPTION
**Pull request by gkossakowski**
In fb315772 custom ClassTags were introduced to optimize array
creation in hot places. The idea was that if `Array[T]` is allocated
through `ClassTag[T]` (which is essentially a factory for Array[T])
we would introduce a custom class implementing `ClassTag[T]` interface
and would have specialized array allocation instruction instead of
having reflective call as it's being done with default (compiler
synthesized) implementation of `ClassTag[T]`.

In case of `PatternMatching.scala` I made a mistake of providing
`ClassTag[Array[Clause]]` instead of `ClassTag[Clause]` so that value
would never be used and compiler still would resolve implicit through
default mechanism. This has been discovered thanks to @paulp's work
on unused value detection.

Review by @paulp.

### CODE REVIEW

**Comment by retronym** [comment]
I suggest to explicitly pass the `ClassTag` to the hot `toArray` call.

**Comment by gkossakowski** [comment]
There's more than one such call. I believe that if we have Xlint working properly that is good enough to detect regressions when implicit value is not being used anymore.

**Comment by paulp** [comment]
Maybe if we flip on -Xlint somewhere. I haven't been too impressed with the number of regressions caught by options which aren't on by default and aren't used in jenkins.  This LGTM though.

**Comment by adriaanm** [comment]
Indeed, we should have -Xlint builds:  https://issues.scala-lang.org/browse/INF-148

**Pull request merged**
