### PR TITLE
SI-5938 Test for a FSC bug with mixin, duplicate static forwarders

### PR DESCRIPTION
**Pull request by retronym**
Under resident compilation, we were getting multiple copies of static
forwarders created for mixed in methods. It seems like the bug was
fixed as a by-product of #4040.

This commit adds a test to show this. I've confirmed that the test
fails appropriately with 2.11.4.

For future reference, before I figured out how to write the test
for this one (test/resident doesn't seem to let you run the code
after compiling it), I was using bash to test as follows:

```
(export V=2.11.x; (scalac-hash $V sandbox/t5938_1.scala; (for i in 1 2; do echo sandbox/t5938.scala; done; printf '\n') | scalac-hash $V  -Xresident); stty echo; scala-hash $V X ; echo ':javap -public X' | scala-hash $V);
```

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
```
created
[artifact:deploy] Uploading: org/scala-lang/scala-library/2.11.5-f75dbdb-SNAPSHOT/scala-library-2.11.5-f75dbdb-20141109.103942-1.jar to repository pr-scala at http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/
[artifact:deploy] Transferring 5446K from pr-scala
[artifact:deploy] Unexpected end of file from server
[artifact:deploy] An error has occurred while processing the Maven artifact tasks.
[artifact:deploy]  Diagnosis:
[artifact:deploy] 
[artifact:deploy] Error deploying artifact 'org.scala-lang:scala-library:jar': Error deploying artifact: Error transferring file
[artifact:deploy] Unexpected end of file from server

```

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
