### PR TITLE
Deprecate numeric widening of numeric literals which are not representable with Float/Double

### LINKED ISSUE #10773: Weak conformance to Float and Double are incorrect
Related: https://contributors.scala-lang.org/t/can-we-get-rid-of-cooperative-equality/1131/85
Related: https://github.com/scala/scala/pull/6398

## steps

```scala
scala> Set[Float](2147483584, 2147483645, 2147483646, 2147483647)

scala> Set[Double](99999999991234561L, 99999999991234562L, 99999999991234563L)

```

## problem

```scala
scala> Set[Float](2147483584, 2147483645, 2147483646, 2147483647)
res1: scala.collection.immutable.Set[Float] = Set(2.14748365E9)

scala> Set[Double](99999999991234561L, 99999999991234562L, 99999999991234563L)
res2: scala.collection.immutable.Set[Double] = Set(9.999999999123456E16)
```

## expectation

It should not compile. Similar to using literal in `Set[Byte]`.

```scala
scala> Set[Byte](1, 2)
res0: scala.collection.immutable.Set[Byte] = Set(1, 2)

scala> Set[Byte](1, 2, 128)
                       ^
       error: type mismatch;
        found   : Int(128)
        required: Byte
```

## note

Here's what SLS says: https://github.com/scala/scala/blob/2.13.x/spec/03-types.md

> ### Weak Conformance
>
> In some situations Scala uses a more general conformance relation.
> A type $S$ _weakly conforms_ to a type $T$, written $S <:_w T$,
> if $S <: T$ or both $S$ and $T$ are primitive number types and $S$ precedes $T$ in the following  ordering.
>
> ```scala
> Byte  $<:_w$ Short
> Short $<:_w$ Int
> Char  $<:_w$ Int
> Int   $<:_w$ Long
> Long  $<:_w$ Float
> Float $<:_w$ Double
> ```

### IEEE floats

https://en.wikipedia.org/wiki/IEEE_754 has nice writeup of IEEE floats. The useful part is the notion of significand. Float has 24 bits of it, and Double 53 bits. 

Given that Int has 32 bits, Float is unable to represent all integers `Int` can represent.
Same goes for `Long` vs `Double`.

### Option 1: Split the floats

My suggestion would be to remove "Long  <:_w Float" from the spec.

The breaking change about this is that small integers like `0` and `1` no longer will automatically "widen" to `Float` and `Double`, but I am personally ok with it.

### PR DESCRIPTION
**Pull request by fabianpage**
follow up for: https://github.com/scala/scala/pull/8679
fixes https://github.com/scala/bug/issues/10773

### CODE REVIEW

**Comment by fabianpage** [comment]
I forgot to do the same check for Doubles, working on that now.

**Comment by som-snytt** [comment]
How does it compare to https://github.com/scala/scala/pull/8730 ?

**Comment by fabianpage** [comment]
@som-snytt i don't have enough knowledge of the compiler to answer that question. I could add your tests to my solution to check if they also warn.

**Comment by lrytz** [comment]
(context: https://twitter.com/darjutak/status/1232599151537512448, we're on the left in the first photo. i missed / didn't remember your PR, @som-snytt)

**Comment by som-snytt** [comment]
Thanks, I see. Previously, I was only reading tpolecat on twitter, but now I will also read darjutak. I may even read darjutak first. Maybe we could use a spree tag here.

The "roundtrip" test in the other PR, borrowed from doti, is more generous.

**Comment by fabianpage** [comment]
But with the roundtrip you will have Integer values which are okay, but the value one bigger or one smaller would not be okay. In my opinion it's nicer to war a soon as you start to truncate.

**Comment by som-snytt** [comment]
Yes, I don't have a strong opinion about the ergonomics. I was trying to "align with doti" a bit, but dotty has sharp edges, such as `Array(3.14f, 0x_7FFF_FFFE)` infers `Float` unlike `Seq[AnyVal]`.

The use case is if I can get my integral value out again, for example it's a sentinel, then there is no reason to warn. If I am computing with it, the opinion on the other ticket was not to warn about operations; I asked why is `3.14f + 1` different from any other `f(1: Float)`?

What is the use case for warning about conversion to a float that is never used in a computation? I computed an int, but my spreadsheet report generator only takes a float?

The doti use case is just about the type inference.

**Review by lrytz — APPROVED** [review]

**Comment by fabianpage** [comment]
@lrytz @som-snytt thanks for your work!

**Comment by lrytz** [comment]
Thanks for your contribution and the friendly pair-coding!

**Pull request merged**
