### PR TITLE
SI-6577 Make actors-migration an external module

### PR DESCRIPTION
**Pull request by jsuereth**
- Removes actors-migration hooks from partest
- Removes actors-migration code
- removes actors-migration tests
- removes actors-migration distribution packaging.

Review by @vjovanov

### CODE REVIEW

**Comment by vjovanov** [comment]
LGTM, thanks.

Optionally we could remove a couple of private classes from ActorRef.scala. They were left in Scala actors as the code was changing and it was not certain where they are needed. The diff is attached to the issue (https://issues.scala-lang.org/browse/SI-6577).

**Comment by jsuereth** [comment]
@vjovanov Since you know which classes to remove, do you want to follow up this pull request with that?

**Comment by vjovanov** [comment]
Sure, although I already prepared the fix in a form of a patch (attached to the issue). All we need to do is `git apply actorref-cleanup`.

**Comment by jsuereth** [comment]
Gotcha.   I'll try to add that shortly.

**Comment by vjovanov** [comment]
I am on it. Pull request coming to your pull request, soon. I will also clean up the classes from ActorRef.

**Comment by vjovanov** [comment]
This pull request needs to be rebased with 2.10.0-wip again. I have the pull request ready so maybe it would be good that I submit it from scratch. WDYT?

**Comment by jsuereth** [comment]
Ok, pulled in the patch, let me know what you think (note: It will attach my name to it .... )

**Comment by vjovanov** [comment]
LGTM. Checked one more time for following case insensitive expressions "actors-","actorsm", "actor-", "actorm".

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by vjovanov** [comment]
rm test/files/jvm/actmig-*

The file was added with a fix for SI-5681, assumed that you removed it when rebasing.

**Comment by jsuereth** [comment]
nope, will fix shortly.

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Pull request merged**
