### PR TITLE
No longer support unreleased STARR.

### PR DESCRIPTION
**Pull request by adriaanm**
[Best viewed per-commit. The first commit just moves some xml around.]

The STARR ("stable reference") compiler is used to bootstrap the compiler.
It is now always resolved from maven, based on the `starr.version`
property (stored in `versions.properties`).

Before, we used the `.desired.sha1` mechanism to pull a set of jars
that define the compiler used to build locker ("local reference"),
which then builds quick.

From now on, we only support officially released versions of STARR.
Milestones are allowed of course, which means that, instead of
breaking change, STARR evolution must support old and new behavior
for at least one milestone cycle.

For local development, use the `replacestarr` target as before.
It builds quick (core only) and publishes it to your local maven repo
with a generated version number, which is saved as `starr.version`
in `build.properties` for convenience (overriding `versions.properties`),
so that your next build will use this version of the compiler for STARR.

You may now think of STARR as STAble Reference Release -- if you will.

Review by @gkossakowski /cc @xeno-by, @paulp, @retronym, @jamesiry.

### CODE REVIEW

**Comment by adriaanm** [comment]
https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1143/console

**Comment by gkossakowski** [comment]
I agree it's good idea to move ant macro definitions to other file which makes it a little bit more clear what's declaration and what's action. However, I wonder if we could pick a bit more unambiguous name like `build-ant-macros.xml` for the file?

Other than that it looks great. You've made my dream to bootstrap Scala compiler with tagged, easily available version of Scala come true. Thanks! :cocktail:

**Comment by adriaanm** [comment]
You're welcome! :-) I shied away from "macros" in the file name because, even if you also include ant, it seems more likely for people to infer it's part of the scala-macros build.

**Comment by gkossakowski** [comment]
I agree "macros" alone would be confusing. However, what do you think about "ant-macros"?

**Comment by adriaanm** [comment]
Looks like we recovered from a spurious IDE test failure:

```
Tests in error: 
  errorClassDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest): None.get
```

failed: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/4280/
ok: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/4282/

/cc @skyluc, @dragos

**Comment by adriaanm** [comment]
As I implied above, I don't think people make such nuanced inferences. Once "macros" is in there, it doesn't matter what else you add. Anyway, if you feel strongly about this, I'll rename.

**Comment by gkossakowski** [comment]
I'm not particularly attached to "ant-macros" but I don't like "support" and I'm trying to be positive by suggesting some alternative :-)

If you got any other ideas how to name it feel free to throw them here. Sorry for a little bit of bike shedding.

**Comment by adriaanm** [comment]
renamed

**Comment by retronym** [comment]
The IDE tests failure: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4296/artifact/target/scala-ide/org.scala-ide.sdt.core.tests/target/surefire-reports/TEST-scala.tools.eclipse.TestsSuite.xml

```
<testcase time="0.007" classname="scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest" name="listDescriptor">
<error message="None.get" type="java.util.NoSuchElementException">
java.util.NoSuchElementException: None.get
 at scala.None$.get(Option.scala:322)
 at scala.None$.get(Option.scala:320)
 at scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest$$anonfun$withTargetTree$1.apply(ScalaJavaMapperTest.scala:113)
 at scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest$$anonfun$withTargetTree$1.apply(ScalaJavaMapperTest.scala:111)
 at scala.tools.eclipse.InteractiveCompilationUnit$$anonfun$withSourceFile$1.apply(InteractiveCompilationUnit.scala:68)
 at scala.tools.eclipse.InteractiveCompilationUnit$$anonfun$withSourceFile$1.apply(InteractiveCompilationUnit.scala:68)
 at scala.tools.eclipse.ScalaPresentationCompilerProxy$$anonfun$apply$1.apply(ScalaPresentationCompilerProxy.scala:72)
 at scala.tools.eclipse.ScalaPresentationCompilerProxy$$anonfun$apply$1.apply(ScalaPresentationCompilerProxy.scala:72)
 at scala.Option.flatMap(Option.scala:170)
 at scala.tools.eclipse.ScalaPresentationCompilerProxy.apply(ScalaPresentationCompilerProxy.scala:72)
 at scala.tools.eclipse.InteractiveCompilationUnit$class.withSourceFile(InteractiveCompilationUnit.scala:68)
 at scala.tools.eclipse.javaelements.ScalaSourceFile.withSourceFile(ScalaSourceFile.scala:77)
 at scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest.withTargetTree(ScalaJavaMapperTest.scala:111)
 at scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest.listDescriptor(ScalaJavaMapperTest.scala:31)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:597)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
 at 
```

image

**Comment by adriaanm** [comment]
Looks spurious. It failed and succeeded once before already.

**Comment by adriaanm** [comment]
Retrying: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4303/console

**Comment by adriaanm** [comment]
Succeeded on the retry

**Comment by retronym** [comment]
Spooky story: the partial function one line down in that IDE code was the very place that was crashing under the recently refactored `Uncurry` before  `ClassInfoType#parents` substitution.

It would be handy to know it the new starr arrangements are okay for `scala-virtualized`, @namin.

**Comment by adriaanm** [comment]
:-s I did not connect the dots on that one...

**Comment by adriaanm** [comment]
@JamesIry, could you investigate? I don't think this failure should hold this PR back, though.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

hopefully we get lucky this time

**Comment by namin** [comment]
For Scala-Virtualized, we're now only tracking 2.10.x -- is this new starr scheme going to be backported to 2.10.x as well?

**Comment by adriaanm** [comment]
I'm not planning to, but most of it is already implemented there under a
switch (starr.use.released, which is on by default). This pr removes the
switch.

**Comment by gkossakowski** [comment]
LGTM.

Thanks for the rename! Also, I would be surprised if scala-virtualized was affected even when it moves to 2.11. The last time I checked it didn't modify compiler in a way that required non-standard compiler to compile the code.

@adriaanm, feel free to press merge button at the time convenient for you.

**Pull request merged**
