### PR TITLE
Javap for Java 7 (Fixes SI-4936)

### PR DESCRIPTION
**Pull request by som-snytt**
Add support for reflective invocation of javap under jdk7,
using the quasi-javax.tools API.

Under -Ygen-javap, warn if you can't.

Since JAVA_HOME is used to locate tools.jar, the script is
updated to convert it for cygwin.

Update Javap for simpl repl.

Also, reduce clutter of JavaxTools as suggested.

JavapTool7 evades repl truncating if enabled; the truncating PrintWriter
is not line-oriented but string-oriented.

Review by @paulp

### CODE REVIEW

**Comment by som-snytt** [comment]
Bumping for review by @paulp (who cares), @retronym (who cures), @jsuereth (who scares).  Every so often, there seems to be a window of opportunity for review, when an RC looks to be final; now perhaps I realize that I must add more comments so that a reviewer can give it a TCBACI? (That couldn't break anything, could it?) if not the L-acronym.  I mean, even if this contribution doesn't work at all, it at least contributes to a feature that doesn't work at all.

**Comment by retronym** [comment]
Looks like it's already drifted and will need a rebase.

**Comment by som-snytt** [comment]
I'm all for removing unused and M I S C bits.  But I haven't run the test suite on this push yet.  Would anyone buy a t-shirt with "git milk?"  I just thought of that one and ATM it's really funny to me. Ha, ha.  I don't even care about javap, it just seemed like a safe third rail to touch, because, like, who cares about javap?  My other recent slogan is for mergeable universes, called Scalision: When Universes Collide.  But I can't think of how to spell it to adequately evoke "collision."

**Comment by paulp** [comment]
It was less of a drift than a five-car smashup when it hit my repl patch. I'm really the one who should merge it - we should avoid punishing people with extra merging when the merging is no fault of the submitter.

**Comment by som-snytt** [comment]
This wasn't a merge but a delete-the-diff.  Another idea that occurred to me, following the thread about 2+ pairs of eyeballs per merge, was that if I ("the contributor") had something I really cared about (and was therefore non-trivial), I ought to drum up some beta testers of my branch before submitting a PR.  If I can't find say two testers willing to try it out, then it's probably not intensely useful.  I mean two besides you.  That seems like a reasonable bar for outside contributions.  Because otherwise, if there's no bandwidth to review really easy contributions like mine, or as my daughter says, easy peasy lemon squeezy, then there's no point in trying.

**Comment by som-snytt** [comment]
BTW, LLIAD (Looks like it already drifted) was not the L-acronym I'd hoped for.  Did I mention "git milk?"  That just cracks me up.

**Comment by paulp** [comment]
I'm sure trying to get a pull request accepted does feel comparable in difficulty to defeating Troy. "The LGTMy and the LLIAD." 

It seems not to work for repl-defined classes, which takes a lot of oomph out of the sails.

```
scala> class Dingo { def f = 1 }
defined class Dingo

scala> :javap -v Dingo
Failed: java.io.FileNotFoundException: Could not find class bytes for 'Dingo'
```

Whereas the same works under java6. Perhaps 1841114e6c will come in handy - I did have this in mind when I checked it in.

**Comment by som-snytt** [comment]
That was going to be my follow-up.  "Commit early and often."  I didn't bother (excuse the expression) to look why it doesn't have the class bytes when it obviously does; we shouldn't need to bother the user about output dirs, right?  OK, OK, I'll take a look at it.  (I had the same thought about LLIAD.  Also, tangentially, that LGTM rhymes with lobotomy, at least in a certain style of doggerel, so that perhaps the build bot should refer to that bot, since builds ought to be brainless.)

**Comment by paulp** [comment]
"we shouldn't need to bother the user about output dirs, right?"

No, I was picturing: the first time :javap is used under java7, it flips the setting on (using a generated temporary directory) and works from the filesystem without ever mentioning anything about it.

**Comment by som-snytt** [comment]
This fixes the classloader so it finds the in-memory classfile.  So right now we're just accumulating entries in the virtual dir, right?  I had expected to do something fancy-kludgy to unload them like I'd done for partest; I assume you assumed javap wanted an external file?

Sorry it took me so long to get back to this.

**Comment by paulp** [comment]
Please, do not apologize. Thank you for your patience with the turnaround times.

I had the external classfile dir in mind for this, without any certainty it would be necessary; it's all the better if it's not.

The only issue I have left is that the java6 version performs the same rewriting as is done everywhere else, so that a repl-defined class looks like this

```
scala> :javap -v Bippy
Compiled from "<console>"
public class Bippy extends java.lang.Object
...
public Bippy();
  Code:
   Stack=1, Locals=1, Args_size=1
```

Instead of like this:

```
:javap -v Bippy
...
  Compiled from "<console>"
public class $line3.$read$$iw$$iw$Bippy
...
  public $line3.$read$$iw$$iw$Bippy();
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
```

There are arguments to be made for both presentations; but tradition, consistency, and noise avoidance all point toward the existing approach. A comment to the effect that the names shown do not reflect reality may be in order, and/or an option to control it may eventually be in order, but they are not super pressing since we've made it this long without those things and I can't remember anyone ever complaining about it in this context specifically. (They do bring it up with respect to the repl in general.)

If you can route the output through the same channel as the java6 javap, I will decree this lgtm.

**Comment by som-snytt** [comment]
I meant to ask about the name translation.

I don't think javap ever worked for me; scala -toolcp tools.jar doesn't work on cygwin because of path separator not converted.  But now that I've used it, it's very useful.  Good tasting and good for you.

Should I restore single option decoding like javap -pcl?  Long form is mildly annoying. Soon it won't matter because of a shiny new scalap.

There's a test/run/showraw_aliases where an id changes from 64 to 65.  Couldn't be my fault? Has to be my fault?

Update: I remember now, I didn't actually notice the naming.unmangle(str) in ReplStripper.

The problem is that TruncatingWriter is string-oriented, not line-oriented, so my big string output is always elliptic.  So shall we prefer StrippingNontruncating for javap7, or make the truncater line-ending-aware?

**Comment by paulp** [comment]
The 64/65 are positions. Since the code is in an embedded string, I will hazard a guess it's an LF turning into a CRLF and boosting the position by one. Although that should boost both numbers or neither, so maybe not. Still, whitespace somehow seems likely.

**Comment by paulp** [comment]
What is the shiny new scalap to which you refer? I like single option decoding but I can live without it. Of higher interest is something like this:

```
javap -v Bippy#f

// shows me only the methods named f in Bippy
```

in case you are looking for a sequel to this one.

**Comment by som-snytt** [comment]
I updated my prev comment that I circumvented the Stripper because of Truncating.  (by calling the other write method, ha.)

**Comment by paulp** [comment]
Ug. I'll say, you choose the shortest path to the right output, and that'll be fine for now. With the change to using scopes to manage the namespace, I'm not too far from all the mangling and $iw stripping becoming unnecessary.

**Comment by som-snytt** [comment]
I just feed it lines now.  I was about to do it the Java way when I noticed Source.fromString.getLines, so all suffering has a purpose.  I added javap -raw to use withoutUnwrapping, but it didn't take.  If you prefer javap -wouw, now is the time to speak up.

**Comment by adriaanm** [comment]
@paulp, can we get that four-letter acronym?

**Comment by paulp** [comment]
His most recent comments didn't seem to come with any code; I tried this out last night and it still prints the raw $iw.$iw.Bippy names by default. Maybe I dropped some bits somewhere, but AFAIK I'm still waiting on that.

**Comment by som-snytt** [comment]
I'm about to add a commit.  Still very sick from a daughter-induced plague, plus yesterday I had to take her to see Lion King.  The commit has -raw, and javap mymethod will do the enclosing iw. Thought I'd look at why nested classes don't translate.  I can see why the repl is kind of addictive.

**Comment by som-snytt** [comment]
At first I thought Adriaan meant, can we get javap -wouw.  

To do: javap - for last line result.  Or maybe continuous under -Ygen-javap.

**Comment by som-snytt** [comment]
Quick build wasn't clean enough with change in visibility.

**Comment by paulp** [comment]
javap - , sweet! This looks bueno to me. I'll handle the minor merge conflict. Thanks for your patience.

**Comment by paulp** [comment]
Superseded by #1751 ; hopefully the tests will pass and then I'll merge it.

**Comment by som-snytt** [comment]
There's a foo drop 1 that should be foo.tail; I did a build when we went out to bike around the complex, but didn't have a chance to verify paranoidally.

**Pull request closed without merging**
