### PR TITLE
SI-7253: respect binary compatibility constraints

### PR DESCRIPTION
**Pull request by Blaisorblade**
From the JLS one can prove that moving a method to a superclass is a binary
compatible change, both forward and backward. That's because when compiling a
method call `c.foo()`, where c: C, the output descriptor _must_ refer to `C` and
not to the class where `foo()` is actually defined.

This patch just ensures that, and adds a test comparing generated descriptors
against the Javac output.

The sample code is from Paul Philipps, the fix and the bytecode comparison code
from me.

From 2006 (9954eafffd5e60676238369ab0ed5797c92b4a7b, a fix for bug 455 in the
old bug tracker, http://www.scala-lang.org/sites/default/files/aladdin/displayItem.do%3Fid=455.html) until 2.9, Scalac has followed this rule "often" (that is, when C is _not_ an interface).

This behavior was wrong, but the bug was hard to trigger. AFAICS, this can
create problems only when moving a method to a super interface in a library and
expecting forward binary compatibility - that is, compiling some Scala client
code against the new version of the library, and trying to run this code against
the old version of the library. This change grows an interface, so it is valid
only if clients are supposed to _not_ implement the library.  Apparently, this
is so rare that nobody noticed.

Since 2.10 (0bea2ab5f6b211a83bbf14ea46fe57b8163c6334), Scalac follows this rule
_only_ when C is an interface (I assume by oversight, since the main change was
an accessibility check), so the bug was finally triggered.

The new code will have to emit INVOKEINTERFACE instead of INVOKEVIRTUAL a bit
more often, compared to 2.9 (but not to 2.10). I don't know whether
INVOKEINTERFACE is noticeably slower (it shouldn't be); but this is the safest
fix since this behavior is mandated by the JLS.
If somebody disagrees and believes the 2.9 is significantly faster, IMHO he
should send a separate pull request (although ProGuard is probably a better
place for the change).

Please let me know if I missed some other duplicated backend - the code I changed is identical in GenASM and GenJVM.

Review by @paulp, @JamesIry (who discussed the bug) or @dragos (who wrote the original code in 2005-2006 and is responsible for the backend).

### CODE REVIEW

**Comment by paulp** [comment]
LGTM. Thanks a lot.

**Comment by Blaisorblade** [comment]
I finally signed the Typesafe CLA. I'm taking a look at the failures.

**Comment by Blaisorblade** [comment]
`scala.tools.reflect.WrappedProperties` is a trait, yet when compiling `this.getClass` inside the trait, scalac generates:

```
$ javap -c -classpath build/quick/classes/compiler/ 'scala.tools.reflect.WrappedProperties$class'
...
public static java.lang.Class pickJarBasedOn(scala.tools.reflect.WrappedProperties);
  Code:
   0:   aload_0
   1:   invokevirtual   #19; //Method scala/tools/reflect/WrappedProperties.getClass:()Ljava/lang/Class;
   4:   areturn
...
```

It seems that for `WrappedProperties`, we should have isTrait = true, and lateINTERFACE flag (probably) set. Still, the code behaves as if isInterface were false.

I'm checking what happens if I use isTrait there.

**Comment by paulp** [comment]
> Still, the code behaves as if isInterface were false.

When flags are false when it seems like they shouldn't be, it's often because the symbol is not initialized. Try sym.initialize.whatever. (Writing these words makes me ill... I just work here.)

**Comment by Blaisorblade** [comment]
Sorry for the noise, I retract my comment: `getClass` is defined on `Object`, and that's special-cased in a fragile way. I just changed the handling and got the compiler to bootstrap. Now I'm delegating the rest of the testsuite to Jenkins (please tell me if that's against the kitteh-iquette).

I believe you took care of initializing symbols by this funny code:

```
        // info calls so that types are up to date; erasure may add lateINTERFACE to traits
        hostSymbol.info ; methodOwner.info
```

**Comment by Blaisorblade** [comment]
@paulp, can you check again now that the kitteh approved my code? The change is still small.

**Comment by Blaisorblade** [comment]
Note that the commit I just added (above) is just a set of (manual) refactorings of the code I touched.

**Comment by paulp** [comment]
It still looks good to me. My only reservation is that if it goes into 2.10.x it implies we will release a 2.10.2 which intentionally produces code which is binary incompatible with 2.10.1 and 2.10.0. Apparently such situations never arise for the scala distribution itself, since the green light indicates mima passed; and perhaps we are living up to our promises, since AFAIK we only ever discuss the binary compatibility of the artifacts we ship, not the binary compatibility of the code we produce; even with those caveats, it does not appear to me to live up to the "drop-in replacement" standard.

An alternative possibility might be to put the fix behind -Xfuture, so it is available to people who need it, and turn it on for 2.11. I will leave this determination to others: @adriaanm @gkossakowski @jsuereth @retronym @JamesIry any thoughts.

**Comment by Blaisorblade** [comment]
I've also wondered about that, but I don't think the output is binary incompatible in any significant way, since it has the same interface and it expects (I believe) a strictly _weaker_ interface of other code.

Given source code calling `foo` on an expression with static type `B`, the new output will require that `B.foo` exists (a requirement we just weakened) and, I believe, it will require that `o: B`. The latter requirement might have been weaker before this patch:  if `foo` is defined by `A >: B`, the old code required just that `o: A`.

However, I don't think there's any difference. The second requirement should be guaranteed by soundness of typechecking (even from the limited soundness of Java typechecking), and I believe that binary compatible changes can't break the second requirement.

But I didn't check in detail in the JLS, and I know that in some cases the JVM is happy to run bytecode which only makes _some_ sense.

**Comment by JamesIry** [comment]
If user source doesn't change the bytecode produced will be both forward and backward compatible with prior 2.10.x versions, just different. 

This patch will improve binary compatibility when source changes in the way that happened in SI-7253. That improvement won't be available in prior 2.10.x versions so in that sense this commit is a change in behavior. But since the old behavior was to create a linkage error I'm okay with that change.

**Comment by paulp** [comment]
Then based on all available opinions, I hereby bless thee with the Sceptre of Logotome.

**Comment by SethTisue** [comment]
LGTM — I can't find anything in the JVM spec contradicting the discussion above.

**Pull request merged**
