### PR TITLE
Upgrade Ruby / Jekyll versions used to build the spec

### PR DESCRIPTION
**Pull request by retronym**
I've given this a dry-run in a separate repository:

   https://travis-ci.org/retronym/scala-spec/builds/57744110

I haven't verified that the output is the same, though.

Review by @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM. I'm sure we'll notice if it does change something.

**Comment by retronym** [comment]
Here's the build: https://travis-ci.org/scala/scala/builds/57753248

**Comment by retronym** [comment]
A spot check of http://www.scala-lang.org/files/archive/spec/2.11 looks okay.

**Comment by adriaanm** [comment]
:+1:

**Comment by adriaanm** [comment]
It does take a while for changes to be propagated from staging to the actual server (30 min if memory serves). I'll try to remember to double check tomorrow.

**Comment by retronym** [comment]
I just triggered https://scala-webapps.epfl.ch/jenkins/job/scala-lang.org-scala-dist-archive-sync/, if that's the one you mean. Still looks okay, but I'm not sure if the content is new or not.

**Comment by adriaanm** [comment]
I think it's https://scala-webapps.epfl.ch/jenkins/job/production_scala-lang.org-scala-dist-archive-sync/ that pushes things into prod, and it runs on a 15 min schedule -- just checked. (Sorry, was on phone earlier.) Thanks for making extra-double-sure the version bump is good :-)

**Pull request merged**
