### PR TITLE
11113 allow literal before type apply

### PR DESCRIPTION
**Pull request by psilospore**
Fixes https://github.com/scala/bug/issues/11113

With lotsa help from @hrhino

### CODE REVIEW

**Review by som-snytt — CHANGES_REQUESTED** [review]
The test should be pos/t11113.scala. It doesn't need a package statement, it just needs to compile.

**Comment by som-snytt** [comment]
I also noticed it's not a recent rebase, which may not matter but makes it a little bit harder to review. (Or maybe there was a semantic change since spring and it does matter.)

**Review by som-snytt — APPROVED** [review]
Thanks! That was a good one. I wonder why it hasn't come up before, you'd think people would be all over that syntax. It would be nice to squash with rebase -i and push -f again.

**Comment by psilospore** [comment]
Happy to help @som-snytt!

**Review by hrhino — APPROVED** [review]
Nice, thanks!

Could you rebase/squash your commits together? then lgtm

**Comment by som-snytt** [comment]
Has anyone tried the "squash and merge" button on the "merge pull request" drop down?

**Comment by psilospore** [comment]
Oh sorry missed the squash comment the first time

**Comment by som-snytt** [comment]
Thanks. There is actually a squash and merge button, as well as rebase and merge, in case it sounded like I was making it up. I understand it can be hard to tell sometimes. I don't know if the buttons do the obvious thing, though.

**Comment by SethTisue** [comment]
> Has anyone tried the "squash and merge" button on the "merge pull request" drop down?

I use it in some other repos, but in scala/scala we want the merge commits.

**Comment by lrytz** [comment]
> > Has anyone tried the "squash and merge" button on the "merge pull request" drop down?
> 
> I use it in some other repos, but in scala/scala we want the merge commits.

Also, after you use it, you have to be **really** careful next time you merge a PR, because the default changes to "Squash and merege"

**Comment by som-snytt** [comment]
This is why we need the brave members of Team Scala: to be the first to press the button!

**Review by lrytz — APPROVED** [review]

**Pull request merged**
