### PR TITLE
Don't process ignored escapes for raw

### LINKED ISSUE #12976: `raw"\u"` wrongly rejected by `-Xsource:3-cross`
## Reproduction steps

```scala
Welcome to Scala 3.4.2-RC1-bin-SNAPSHOT-git-a36849f (21.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> def f(c: Char) = raw"\u%04X".format(c.toInt)
def f(c: Char): String

scala> f('a')
val res0: String = \u0061

Welcome to Scala 2.13.13 (OpenJDK 64-Bit Server VM, Java 21.0.2).
Type in expressions for evaluation. Or try :help.

scala> def f(c: Char) = raw"\u%04X".format(c.toInt)
                              ^
       error: invalid unicode escape at index 2 of \u%04X

scala>
:quit

Welcome to Scala 2.13.13 -Xsource:3-cross (OpenJDK 64-Bit Server VM, Java 21.0.2).
Type in expressions for evaluation. Or try :help.

scala> def f(c: Char) = raw"\u%04X".format(c.toInt)
                              ^
       error: invalid unicode escape at index 2 of \u%04X
```

## Problem

under `-Xsource:3-cross`, do not check whether my ignored escape would have been valid if not ignored.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12976

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
Thanks!

**Comment by lrytz** [comment]
Moved to 2.13.14 but leaving to @SethTisue to merge or move back.

**Comment by som-snytt** [comment]
The example idiom might be the only usage that is affected, but I can attest it made me wonder if `-Xsource:3-cross` doesn't do what I thought it did.

**Comment by SethTisue** [comment]
Note to self: we'll need to update https://docs.scala-lang.org/scala3/guides/migration/tooling-scala2-xsource3.html at release time

**Pull request merged**
