### PR TITLE
Opt-in REPL banner

### PR DESCRIPTION
**Pull request by som-snytt**
Edit: the banner is hidden behind `-Dscala.repl.welcome=banner`.

The old welcome message is available under
`-Dscala.repl.info`.

This got a vote on gitter, so posting for feedback.

```
apm@mara:~/projects/snytt$ skala -Dscala.repl.info
Welcome to Scala 2.12.4-20170814-072151-1b7d57f (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.
[info] started at Sun Aug 20 23:07:26 PDT 2017

scala 2.12.4-20170814-072151-1b7d57f> :quit
apm@mara:~/projects/snytt$ 
apm@mara:~/projects/snytt$ 
apm@mara:~/projects/snytt$ skala

     ________ ___   / /  ___  
    / __/ __// _ | / /  / _ | 
  __\ \/ /__/ __ |/ /__/ __ | 
 /____/\___/_/ |_/____/_/ | | 
                          |/  version 2.12.4-20170814-072151-1b7d57f

scala> :quit
apm@mara:~/projects/snytt$ skala -help
Usage: scala <options> [<script|class|object|jar> <arguments>]
   or  scala -help

All options to scalac (see scalac -help) are also allowed.

The first argument to scala after the options designates what to run.

If no argument is given, the Scala REPL, an interactive shell, is started.

Otherwise, the Scala runner will try to run the named target, either as
a compiled class with a main method, a jar file with a Main-Class manifest
header, or as a Scala source file to compile and run.

The REPL accepts expressions to evaluate. Try `:help` to see more commands.

The script runner will invoke the main method of a top-level object if
it finds one; otherwise, the script code is run locally to a synthetic
main method with arguments available in a variable `args`.

Options to scala which reach the Java runtime:

 -Dname=prop  passed directly to Java to set system properties
 -J<arg>      -J is stripped and <arg> passed to Java as-is
 -nobootcp    do not put the Scala jars on the boot classpath (slower)

Other startup options:

 -i <file>    preload <file> before starting the REPL
 -I <file>    preload <file>, enforcing line-by-line interpretation
 -e <string>  execute <string> as if entered in the REPL
 -save        save the compiled script in a jar for future use
 -nc          no compilation daemon: do not use the fsc offline compiler

If the runner does not correctly guess how to run the target:

 -howtorun    what to run <script|object|jar|guess> (default: guess)

When running a script or using -e, an already running compilation daemon
(fsc) is used, or a new one started on demand.  Use the -nc option to
create a fresh compiler instead.
```

Spark doesn't use this mechanism, but overrides the printWelcome method in the REPL.

### CODE REVIEW

**Comment by sjrd** [comment]
-1
That's a lot of visual noise for absolutely no reason. Would make me choose `node` over `scala` for most of my small computation uses, only resorting to `scala` if I need Scala, and it'd bother me.

**Comment by som-snytt** [comment]
I may or may not try it again under a flag, and may or may not keep the edit to the help text.

The purpose of the banner is to make you forget that the compiler is initializing.

I also like the visual break for the start of a repl session, but maybe that's just my bad eyesight.

**Comment by som-snytt** [comment]
I put the banner behind `-Dscala.repl.welcome=banner`.

My use case is that I often scroll my terminal back, and the banner helps me locate my last experiment. Also, arguably, it's friendly.

I already had a custom message to remove `Type in expressions for evaluation. Or try :help.` For some reason, that line is more noisome to me, as far as visual noise goes.

This PR would be 2.12 only, no-merge, and is maybe a way to try out ergonomics for 2.13. It doesn't really address https://github.com/scala/bug/issues/10472. Maybe `scala.repl.welcome` should be taken as a file name instead of a string. The power banner can be a file name.

**Comment by adriaanm** [comment]
While neutral on adding an opt-in, the feature would have to be forward ported to 2.13, since changes to the repl won't merge cleanly anymore after someone went and boy scouted all over the place.

**Comment by som-snytt** [comment]
This was research on customizing. Hopefully it will be very easy in 2.13.

I commented that it's no-merge, but I forgot the mechanism: "[no-merge]" in the title?

**Comment by adriaanm** [comment]
Yes indeed.

**Review by lrytz — COMMENTED** [review]
LGTM, just add `[nomerge]` to the two commit message titles.

**Review by lrytz — APPROVED** [review]

**Pull request merged**
