### PR TITLE
Fix encoding problems in output of scaladoc -help

### PR DESCRIPTION
**Pull request by Blaisorblade**
From the output of `scaladoc -help`:

```
  -doc-source-url <url>                       A URL pattern used to
  build links to template sources; use variables, for example:
  ?{TPL_NAME} ('Seq'), ?{TPL_OWNER} ('scala.collection'),
  ?{FILE_PATH} ('scala/collection/Seq')
```

The ? should be €. Fix that in the source, using the correct encoding (which is already UTF-8).

The encoding problem was introduced in 2011 by commit 2621ee63285808785159a3c24c9e5a5a723b8b9c, and seems to not have been reported till now.

---

To make the above work, the output should also be encoded correctly.
On my system, this requires the _default JVM encoding_ to be UTF-8 when the script is run, that is, passing `-Dfile.encoding=UTF-8`.

So, after this commit, the euro sign is garbled in the output of `./qbin/scaladoc -help` and correctly displayed in the output of `./qbin/scaladoc -Dfile.encoding=UTF-8 -help`.

That change might be necessary:
1. in general, or
2. only on systems with UTF-8 terminals and non-UTF-8 default encoding.

For option 1, I attach a commit making that option the default, and with bigger potential for bugs, so probably this should not go in 2.10.3.
For option 2, the first commit is enough, and it's trivial enough for 2.10.3.

What do you think?

### CODE REVIEW

**Comment by Blaisorblade** [comment]
I'm not sure who the reviewers should be, but I'll try.
Review by: @vladureche (for scaladoc), @jsuereth (about encoding issues, can't guess a better name). Please feel free to reassign.

**Comment by adriaanm** [comment]
Since you're targeting the 2.10.3 branch, please motivate why this is a blocker.
Otherwise, please target 2.10.x for inclusion in 2.10.4-RC1.

**Comment by Blaisorblade** [comment]
It's not a blocker, only a quickfix; and if the first commit is enough, it's a oneliner affecting a comment.

Before reopening, I'd appreciate a review on the second commit. But if you prefer, I'll just reopen for `2.10.x` with the oneliner.

**Comment by Blaisorblade** [comment]
The failure seems spurious. From https://scala-webapps.epfl.ch/jenkins/job/pr-scala-rangepos/2775/consoleText:

```
  [partest] testing: [...]/files/run/t6968.scala                                  [  OK  ]
Build was aborted
Aborted by retronym
Notifying upstream projects of job completion
Finished: ABORTED
```

**Comment by Blaisorblade** [comment]
Also https://scala-webapps.epfl.ch/jenkins/job/pr-scala/2942/ shows aborted. I'm not triggering a rebuild, since the build bot seems to have problems (the commits were hanging there for 12 days!) - @retronym, should I rebuild?

**Comment by retronym** [comment]
The build bot has gone rogue. There is nothing specifically wrong with this PR.

**Comment by retronym** [comment]
Closing, this needs to be retargetted to the 2.10.x.

**Pull request closed without merging**
