### PR TITLE
SI-7747 Added .INSTANCE accessor to classBasedWrappers in REPL.

### PR DESCRIPTION
**Pull request by ScrapCodes**
This patch will free us from maintenance burden of our own port of scala repl. 

I may not have done good job in explaining things well. Specific questions can help me do better. Hopefully code comments are enough to explain the patch. I have tried with this patch - there will be no need to port the repl code in our repository(Apache Spark) again. 

I wish - it could go in for 2.11.7 :) 

review: @gkossakowski and @som-snytt

### CODE REVIEW

**Comment by mpociecha** [comment]
Regarding @gkossakowski. AFAIK he doesn't work on scalac anymore (he decided to focus on other things).

**Comment by ScrapCodes** [comment]
ahh snap, My bad it was @retronym. PTAL. This PR has some context. https://github.com/apache/spark/pull/2615.

**Comment by som-snytt** [comment]
App-based wrapper will require merge.  https://github.com/scala/scala/pull/4349

**Comment by retronym** [comment]
Hi @ScrapCodes, thanks for the PR. I haven't had a chance to review this yet, but will find some time later this week.

**Comment by ScrapCodes** [comment]
Hi @retronym, thanks !. I will be around to address the review comments.

**Comment by ScrapCodes** [comment]
I have updated the code a bit.

**Comment by adriaanm** [comment]
Hi, @ScrapCodes! Thanks for the PR. I'll let @retronym do the in-depth review, but in the mean time, please expand the commit message a bit, and make sure the title fits into 55 characters, as explained in [our guidelines](https://github.com/scala/scala/#git-hygiene).

**Comment by ScrapCodes** [comment]
Do we have limit on number of lines for "subsequent lines" ? 

Pasting the commit message verbatim.

---

SI-7747 Added .INSTANCE accessor to classBasedWrappers in REPL.

The changes to wrappers are explained as follows.

$ scala -Yrepl-class-based

``` scala

scala> val a = 10 
a: Int = 10

scala> case class A(a: Int)
defined class A

scala> A(a) // show
class $read extends Serializable {
// ... some uninteresting stuff elided.
   class $iw extends Serializable {
// ...
    val $VAL1 = $line5.$read.INSTANCE; // <-- First points of interest.
    import $VAL1.$iw.$iw.a;           //  <--
    import $line6.$read.INSTANCE.$iw.$iw.A; // <- Second point of interest.
    import $line6.$read.INSTANCE.$iw.$iw.A;
    class $iw extends Serializable {
// ...
      val res0 = A(a)
    };
    val $iw = new $iw.<init>
  };
  val $iw = new $iw.<init>
}
object $read extends scala.AnyRef {
// ...
  val INSTANCE = new $read.<init>
}
res0: A = A(10)

scala>

```

(a) First point of interest.

(1) Originally -Yrepl-class-based would import the same thing as follows:

``` scala
import $line6.$read.$iw.$iw.a;
```

(2) This patch changes it to following:

``` scala
val $VAL1 = $line5.$read.INSTANCE; // <-- First points of interest.
import $VAL1.$iw.$iw.a;
```

From my understanding, In (1) we directly import a value `a`, when this code
is shipped to a remote executor leads to initializing all the classes wrapping
`a`, not just that `a` itself had lots of imports around it
( because we do not finesse on imports to allow implicits. ) when it was wrapped
. Then this leads to bubbling up
( in a chain initializing the classes involved in those imports.), way up to
where we initialized the first thing in the repl. All of these classes are
reinitialized on the remote repl. This is undesirable in most cases.

In (2) we break the import between a val pointing to a already created
instance and then importing it. This leads to importing the deserialized
instance of the accessor `.INSTANCE` and does not lead to bubbling up
phenomenon mentioned above.

 (b) Second point of interest.

It is as it was originally, this lead to adding a special case for class
declaration. In this patch it was changed to finesse on what we import,
since when we declare a class - implicit imports are not needed.
This fine list of import avoids referring to unnecessary things class
declaration needed. And the bubbling up phenomenon is avoided and not eliminated.
 If at all it happens, it does so in expected way.
This was not changed to above style(mentioned in (a)) to prevent isomorphism
that would result from importing from different val ids
(eg : `$VAL1` and `$VAL2` referring to same type would be treated as different).

**Comment by retronym** [comment]
I've just edited your comment, the title should include the bug id. Otherwise it looks good.

Sorry I didn't review last week, it is still on my list though.

**Comment by ScrapCodes** [comment]
Thanks !, I was afraid if it exceed 55 char limit. Which it does now, so if it is alright - can I update the commit message to the latest edited comment above ?

**Comment by retronym** [comment]
GitHub doesn't wrap the commit subject before 72 characters. I think the 55 char limit is to allow for one ore two `RE:` a prefixes to accumulated when exchanging patches by email. I can never fit in that myself.

@adriaanm Shall we loosen the guidelines for the subject?

**Comment by adriaanm** [comment]
Sure, happy to relax it a bit more explicitly. Thank you for the excellent commit message, @ScrapCodes!

**Comment by ScrapCodes** [comment]
You are welcome @adriaanm !. @retronym Did you get a chance to look at it ?

**Comment by retronym** [comment]
Hi @ScrapCodes. Sorry about the delay. I've just taken a good look at the code. The changes themselves look okay, but I still don't have a clear picture about how this change impacts the number of classes initialized during deserialization. 

> From my understanding, In (1) we directly import a value `a`, when this code
> is shipped to a remote executor leads to initializing all the classes wrapping
> `a`, not just that `a` itself had lots of imports around it (because we do not
> finesse on imports to allow implicits) when it was wrapped.
> 
> Then this leads to bubbling up (in a chain initializing the classes involved
> in those imports.), way up to where we initialized the first thing in the repl.
> All of these classes are reinitialized on the remote repl. This is undesirable
> in most cases.

How would I go about writing a test case that simulated this behaviour? What object would I serialize/deserialize?

**Comment by ScrapCodes** [comment]
Simulating everything like (a remote fetching classloader + isolated jvm executor etc..) can be a bit involved. I have a bunch of test suits [1] written in spark to work against this branch of scala. Do you think that can be useful ? We can speak offline if you like ?
1. https://github.com/ScrapCodes/spark-1/tree/SI-7747/tryout-repl see project repl. 

To run the tests:

$ `build/sbt -Dscala-2.11 -Phive`

$ > `assembly/assembly` (will take about 5mins)

$ > `test-only *ReplSuite`

**Comment by retronym** [comment]
Can you show a transcript of one of those tests failing before your patch?

Is the example in the commit comment sufficient to understand the difference? Here's a better look at the change in the desugaring: https://gist.github.com/retronym/28b85ddb1fa817db6a1e

**Comment by ScrapCodes** [comment]
> Can you show a transcript of one of those tests failing before your patch?

yes, here is [one](https://gist.github.com/ScrapCodes/232ea0d36af0bd6017d6). But I am not sure how useful it will be. 
Also this work of modification of repl was originally proposed by @mateiz for spark and I happened to remember his comment in 2013, which explains it well. [comment](https://github.com/mesos/spark/pull/535#discussion_r3541925). Hopefully he might be able to help us. 

> Is the example in the commit comment sufficient to understand the difference? Here's a better look at the change in the desugaring: https://gist.github.com/retronym/28b85ddb1fa817db6a1e

Yes, this is more exhaustive. I have excluded one detail `object $read extends $read` is changed. Do you want me to update the commit message in some way, like including the link to the gist above ?

**Comment by retronym** [comment]
That explanation really clears things up for me. I've created a test case in https://github.com/scala/scala/compare/scala:2.11.x...retronym:review/4493

I still need to take a look at the use of `val VAL1 =` to check that the test fails without that, and to understand why. Thanks for your patience as I get my head around this!

**Comment by retronym** [comment]
I've submitted a version of this in #4522.

**Comment by som-snytt** [comment]
Thx for the old comment link; it's good to know.

**Pull request closed without merging**
