### PR TITLE
SI-8870 Fix markup errors in the Types section of the spec

### PR DESCRIPTION
**Pull request by retronym**
Bad: `T'_n`
Good: `T_n'`

Review by @gourlaysama

### CODE REVIEW

**Comment by retronym** [comment]
image

**Comment by retronym** [comment]
Oddly enough, `a'_i` is rendered correctly. I wonder what the difference is.

```
% git grep "\\w'_" -- spec
spec/03-types.md:      for $a'_i$.
spec/03-types.md:    - The variance of $a_i$ must match the variance of $a'_i$, where covariance
spec/03-types.md:      type parameter clauses of $a_i$ and $a'_i$.
spec/05-classes-and-objects.md:and each `$xs_i$` denotes the parameter names of the parameter section `$ps'_i$`. The value
spec/05-classes-and-objects.md:parameters `$ps'_{1,j}$` of first parameter list have the form `$x_{1,j}$:$T_{1,j}$=this.$x_{1,j}$`,
spec/05-classes-and-objects.md:the other parameters `$ps'_{i,j}$` of the `copy` method are defined as `$x_{i,j}$:$T_{i,j}$`.
spec/06-expressions.md:it has the form $x_i=e'_i$ and $x_i$ is one of the parameter names
spec/06-expressions.md:positional arguments and to $e'_i$ for named arguments of the form
spec/06-expressions.md:`$x_i=e'_i$`. Then, for every parameter which is not specified
spec/06-expressions.md:the anonymous function `($u'_1$, ... $u'_n$) => $e'$`
Binary file spec/public/images/classhierarchy.pdf matches
```

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by gourlaysama** [comment]
LGTM

**Comment by gourlaysama** [comment]
For the curious ones out there, whether `T'_b` works (or not) is context-sensitive: it depends on markdown believing the underscores are delimiters for text in italics or not... The rules are kind of messy. This could put the closing `$` in italics, which breaks mathjax. And somehow this is worse when the underscore is preceded by a single quote. Oh, the joys of markdown parsers...
For example, you could backslash-escape all `_` characters in those two paragraphs, it would work too (it would just be uglier).

**Comment by retronym** [comment]
Gotcha, thanks for the explanation!

**Comment by retronym** [comment]
And we thought Scala was the only language with a confusing `_`!

:smile:

**Pull request merged**
