### PR TITLE
Merge 2.10.x

### PR DESCRIPTION
**Pull request by adriaanm**
Patches applied:
- rename of `dropRepeatedParamType` to `dropIllegalStarTypes` -- required since 8886d22
- fixed test/files/neg/t6406-regextract.flags -- how could this have worked before?

Conflicts:
    src/compiler/scala/tools/nsc/interpreter/TypeStrings.scala
    src/library/scala/collection/LinearSeqOptimized.scala
    src/library/scala/util/Properties.scala
    test/files/run/streams.check
    test/files/run/streams.scala

review by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
Re "how could this have worked before?", see 9575ee9961. Everything was magically compiled under deprecation in partest, until now.

**Comment by paulp** [comment]
Looks good to me. Less code than I thought accumulated over there; I guess we're all going for the mini-patches on that branch.

**Comment by som-snytt** [comment]
Re "how could this have worked before?", sorry, I should have supplied -deprecation explicitly at the time.  Elsewhere I commented that I was unable to test code that exercised a deprecated feature (no-arg case class?) because fatalWarnings had to be on.  Probably I was the only one who was hyperaware of this partest behavior.  

As a footnote, I think tests should be clean, so -deprecation is good policy, but the paradox is that you shouldn't use deprecated API, but you still have to test it during the deprecation period. Or emend the deprecation message to add, "...besides, we don't even test this stuff anymore."

Maybe for boolean flags, .flags could handle -undeprecation. Or --deprecation=false. Or, file that under nothing good happens after midnight.

**Comment by adriaanm** [comment]
No need to apologize, it's great we have a test for this! Finally a compelling argument for options that go both ways -- I've always preferred it for the symmetry, now I can illustrate the utility.

**Pull request merged**
