### PR TITLE
Decrease stack size for JUnit tests to 1M (same as the old ant build)

### PR DESCRIPTION
**Pull request by szeiger**
Follow-up to #5362 (see discussion there). I'll kick off some bootstrap builds to see how well it behaves with 1M.

### CODE REVIEW

**Comment by szeiger** [comment]
First bootstrap build: https://scala-ci.typesafe.com/view/scala-2.12.0/job/scala-2.12.0-integrate-bootstrap/75/

**Comment by szeiger** [comment]
First build green. Next attempt: https://scala-ci.typesafe.com/view/scala-2.12.0/job/scala-2.12.0-integrate-bootstrap/76/

**Comment by adriaanm** [comment]
LGTM -- both ✅

**Comment by SethTisue** [comment]
it failed today: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/563/consoleFull

**Comment by retronym** [comment]
SBT might consume more of the stack with framework code than Ant.

**Pull request merged**
