### PR TITLE
Small cleanup after the IterableCC PR (7929)

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
I also looked into the [`TODO why is this ascription needed?`](https://github.com/scala/scala/pull/7929/files#diff-e145bcb98a7fee322b757db17e25bea8R18). The same ascriptions are needed in [BuildFrom.scala](https://github.com/scala/scala/pull/7929/files#diff-9c9cc04f5de1e9c7f61e70dd091cdd6d).

Here's a minimization: https://gist.github.com/lrytz/82910a7754f5d33b1dc2693f9eb37071

The problem is, Iterable defines `def iterableFactory: ItFact[It] = It`, before it was `def iterableFactory: ItFact[ItCC] = It`

When you have `CC[X] <: It[X] with ItOps[X, CC, _]`, then `(foo: CC[A]).iterableFactory` has type `ItFact[It]`, not `ItFact[CC]`

@adriaanm says he'll take a look.

**Comment by SethTisue** [comment]
is this possibly a 2.13.0-RC1 issue?

**Comment by adriaanm** [comment]
I think this is the best we can do due to the way linearisation works.

**Comment by lrytz** [comment]
OK, but this PR can be merged I'd say

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
Yes, sorry -- too many plates in the air.

**Pull request merged**
