### PR TITLE
More tailrec in handling long seq

### LINKED ISSUE #12757: Compiling large collections of strings literals using scala 2.13 leads to StackOverFlow
## Reproduction steps
Using this helper program `create_strings.scala`
```scala
import java.io._

val pw = new PrintWriter(new File("large_list_of_string_literals.scala"))
pw.write("object Test {\nval myStrigns: List[String] = List(\n")
(0 to 4000).foreach( i =>
  pw.write(s"  \"$i\",\n")
)
pw.write(")}")
pw.close
```
and compiling the results
```shell
$ scalac --version
Scala compiler version 2.13.10 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.
scala create_strings.scala
scalac large_list_of_string_literals.scala
error: java.lang.StackOverflowError
	at scala.reflect.internal.tpe.TypeComparers.secondTry$1(TypeComparers.scala:519)
	at scala.reflect.internal.tpe.TypeComparers.firstTry$1(TypeComparers.scala:495)
	at scala.reflect.internal.tpe.TypeComparers.isSubType2(TypeComparers.scala:615)
	at scala.reflect.internal.tpe.TypeComparers.isSubType1(TypeComparers.scala:347)
	at scala.reflect.internal.tpe.TypeComparers.isSubType(TypeComparers.scala:305)
	at scala.reflect.internal.tpe.TypeComparers.isSubType$(TypeComparers.scala:267)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:28)
	at scala.reflect.internal.tpe.TypeComparers.retry$2(TypeComparers.scala:440)
	at scala.reflect.internal.tpe.TypeComparers.isSubType2(TypeComparers.scala:443)
	at scala.reflect.internal.tpe.TypeComparers.isSubType1(TypeComparers.scala:347)
	at scala.reflect.internal.tpe.TypeComparers.isSubType(TypeComparers.scala:305)
	at scala.reflect.internal.tpe.TypeComparers.isSubType$(TypeComparers.scala:267)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:28)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$elimSub$1(GlbLubs.scala:225)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$elimSub$1$adapted(GlbLubs.scala:225)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$maxTypes$1(GlbLubs.scala:203)
	at scala.reflect.internal.tpe.GlbLubs.$anonfun$maxTypes$1$adapted(GlbLubs.scala:203)
	at scala.collection.immutable.List.noneIn$1(List.scala:515)
	at scala.collection.immutable.List.filterCommon(List.scala:581)
	at scala.collection.immutable.List.filterNot(List.scala:504)
	at scala.reflect.internal.tpe.GlbLubs.loop$1(GlbLubs.scala:203)
	at scala.reflect.internal.tpe.GlbLubs.loop$1(GlbLubs.scala:203)
...
```

### Problem
I would expect scala to compile the program with the default jvm stack size.

### Some more information
This is only problem in 2.13 both scala 2.12 and scala 3 seems to compile the code without issues. This seems to be lated to literal types I think the overflow seems to happen we call the function `scala.reflect.internal.tpe.GlbLubs.loop$1` with literal types in the collection.

Doing the same instead with ints we do not get a stackoverflow. e.g program `create_int.scala`
```
import java.io._

val pw = new PrintWriter(new File("large_list_of_int_literals.scala"))
pw.write("object Test {\nval myInts: List[Int] = List(\n")
(0 to 4000).foreach( i =>
  pw.write(s"  $i,\n")
)
pw.write(")}")
pw.close
```
compiles without issues
```
scala create_int.scala
scalac large_list_of_int_literals.scala 
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12757

[edit]: optimization in TypeConstraints reverted in https://github.com/scala/scala/pull/10452

### CODE REVIEW

**Review by lrytz — COMMENTED** [review]
seems good to me but also smokes my brain 🤯 @dwijnand could you take another look?

**Comment by som-snytt** [comment]
I'll take another look before Dale wastes his time. Having my second coffee now, in preparation.

This reminds me of the attribute filtering, a right fold where elements are eliminated while winding back.

But I looked at this local refactor and wondered how can that be right.

Edit: also thought again, I'd like a way to test local functions.

Edit: my local branch has a few debug commits, apparently I was trying to convince myself that the extra list building was worth it. Did I learn in March that ints are special-cased? I recall it was sad that String is a challenge. Probably I thought it would be more useful to handle "many string", as "many disparate things" is not a use case.

Edit: while soup is cooking, I took a look and now I see how it works, but the variable names are not clarifying. I wonder if I will still remember after lunch.

**Comment by som-snytt** [comment]
Previous tweaks on the branch include probing list length before doing hard labor. (Also whitespace edits as I added and removed printlns, sorry, I hope that is not too annoying. That was a sin by past me.)

At the last minute, I also pick the old vs new loop based on whether it looks like a usual (up to 5) number of types.

@lrytz may have an opinion on TypeConstraints special casing string, not unlike numbers: if there is currently one string, and the new one is also a string, only keep one. They are not the same literal type (they are different strings). I left the condition that the candidate is constant type, but I intended to revisit that.

The third test, which is a large list of mixed types, is the test that fails with the "old loop". The partest tweak is required to show the SOE (on jdk 20) because the message is null. The test with all Strings now reduces to one `lobounds`, similar to the second test of ints where the lobound is numeric.

I provided improved var names and up to two comments, which is about my limit. Except on PRs, then my comments are unlimited and completely free to you.

**Review by lrytz — APPROVED** [review]
Thank you! I did some smoke testing 🚬

**Comment by som-snytt** [comment]
@lrytz Thanks. It goes without saying (so I'll say it) that your excellent, eagle-eyed reviews have been a great experience for me. (Remaining defects are my own, etc.)

**Comment by som-snytt** [comment]
See linked PR for sample defect.

**Pull request merged**
