### PR TITLE
Granted scaladoc its own Global.

### PR DESCRIPTION
**Pull request by paulp**
An incremental step on the road to disentangling
scaladoc from the compiler sources. This pushes the
elements in typer outward so scaladoc can subclass
Global like everyone else.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm

**Comment by heathermiller** [comment]
Would probably be good if @VladUreche was also notified of this PR. Just so he's in the loop about Scaladoc-related changes to the compiler.

**Comment by adriaanm** [comment]
LGTM -- what say you, @VladUreche?

**Comment by VladUreche** [comment]
LGTM, thanks Paul!

**Pull request merged**
