### PR TITLE
Add QualifierTypedAnnotationInfo

### LINKED ISSUE #11870: 2.13.1 scalac StackOverflowError when annotation argument references the annottee
Consider the example:
```scala

class Invariant(condition: Unit => Boolean) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Invariant( _ => x.length == 3 )
  def x: String = "foo"
}
```

This code results in the `java.lang.StackOverflowError` through `scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo$lzycompute(AnnotationInfos.scala:158)` ([scalac-SOE-stack.txt](https://github.com/scala/bug/files/4129572/scalac-SOE-stack.txt) has the full stack trace if you need it). As far as I can tell, the stack trace is different from those encountered in #7449, #1632, #1667 and #10421. Increasing the stack `-Xss128m` just makes the SOE stack trace longer, so it looks like cyclic init.

Some pointers to help narrow the problem.

1. The annotation argument does not have to be a lambda. The following snippet yields the same SOE: 
```scala
class Annot(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot(x)
  def x: String = "foo"
}
```

2. The following example compiles fine.
```scala
class Annot(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot(y)
  def x: String = "foo"
  def y: String = "bar"
}
```

3. However, if you put the annotation on the second field as well, there is the SOE again
```scala
class Annot(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot(y)
  def x: String = "foo"

 @Annot(x)
  def y: String = "bar"
}
```

4. Finally, the code below causes SOE even when the annotations are different.
```scala
class Annot1(arg: Any) extends scala.annotation.StaticAnnotation
class Annot2(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot1(y)
  def x: String = "foo"

  @Annot2(x)
  def y: String = "bar"
}
```

Thank you!

### PR DESCRIPTION
**Pull request by changvvb**
fixes scala/bug#11870
Following https://github.com/scala/scala/pull/9023#issuecomment-645757880, add QualifierTypedAnnotationInfo used to match AnnotationInfo type without fully typechecked

### CODE REVIEW

**Review by lrytz — COMMENTED** [review]
Thank you @changvvb for this patch! I apologize it took so long to get a first review.

I think the existing `LazyAnnotationInfo` is already a dubious workaround, and the proposed change here pushes that complexity a bit too far.

I'm wondering if we could have a single `AnnotationInfo` class that has lazy fields, and add support for lazy annotations directly in `typer.typedAnnotation`. So I started looking at `typedAnnotation` and, as a first step, did some cleanups / simplifications. I'm testing them here: https://github.com/scala/scala/pull/9189.

**Comment by changvvb** [comment]
@lrytz Simplifying AnnotationInfo will be a great breakthrough.

**Comment by dwijnand** [comment]
@lrytz with #9189 landed, where does this PR stand?

**Comment by lrytz** [comment]
I'd like to get back to it and attempt the AnnotationInfo overhaul I hinted at above, at some point when I have time.

**Comment by lrytz** [comment]
Superseded by https://github.com/scala/scala/pull/9302

**Pull request closed without merging**
