### PR TITLE
Lint-like fixes found by Semmle

### PR DESCRIPTION
**Pull request by lexspoon**

### CODE REVIEW

**Comment by lexspoon** [comment]
I played around with Semmle's whole-program code scanner on the Scala
repository, and I found a few lint-like issues that seem worth
cleaning up. These queries are fun in that they aren't limited to the files
available in any single compilation run. For example, they can find unsealed
case class hierarchies that aren't extended in another file.

**Comment by adriaanm** [comment]
LGTM, thanks!

**Comment by soc** [comment]
LGTM!

**Comment by adriaanm** [comment]
Conclusion: IDE still compiles, so good to merge.

**Pull request merged**
