### PR TITLE
Take the N^2 out of the compiler's TreeSet.

### PR DESCRIPTION
**Pull request by paulp**
If we're going to have custom reimplementations of standard
collections, it seems like they should have some demonstrable
performance advantage. With this commit the time to compile
a particular piece of generated code dropped from this:

```
  % time scalac3 ./target/generated/src.scala
  Mar 28 13:20:31 [running phase parser on src.scala]
  ...
  Mar 28 13:21:28 [running phase lazyvals on src.scala]
  Mar 28 13:21:28 [running phase lambdalift on src.scala]  <-- WHOA
  Mar 28 13:25:05 [running phase constructors on src.scala]
  ...
  Mar 28 13:25:19 [running phase jvm on icode]
  316.387 real, 438.182 user, 8.163 sys
```

To this:

```
  % time pscalac ./target/generated/src.scala
  Mar 28 13:18:47 [running phase parser on src.scala]
  ...
  Mar 28 13:19:44 [running phase lazyvals on src.scala]
  Mar 28 13:19:44 [running phase lambdalift on src.scala]
  Mar 28 13:19:46 [running phase constructors on src.scala]
  ...
  Mar 28 13:19:57 [running phase jvm on icode]
  99.909 real, 223.605 user, 7.847 sys
```

That's lambdalift dropping from 217 seconds to 2 seconds. Which
should really call into question whether the "demonstrable"
standard is being met. The number of bugs like this is going to be
proportional to the number of distinct implementations. How many
different logical paths do we need to concatenate iterators?

This should be exhibit A as to why the collections should
bundle far less code and behavior. It seems even we, the authors
of the collections, find them too heavyweight to use in our
primary application, favoring instead stripped down versions
of the same data structures. And here we see a huge performance
bug because of it. Wouldn't it be nice if we could use the same
battle-tested code everyone else does?

### CODE REVIEW

**Comment by paulp** [comment]
Review by @gkossakowski

**Comment by gkossakowski** [comment]
@paulp: can you share code that you compiled to test this change?

**Comment by paulp** [comment]
Yep, here it is: https://www.dropbox.com/s/8xlk3o9zjdo9q56/generated-src.scala

**Comment by paulp** [comment]
Oh, and I just realized I should point out that those numbers are from this patch on master - I cherrypicked back to 2.10.x to submit this PR. I can't imagine how it could matter, but on the chance you're trying to reproduce it.

**Comment by gkossakowski** [comment]
I reproduced the performance improvement. Great work!

However, it's not entirely clear to me where O(n^2) is coming from in the old version. Is it because of calls to `Iterator.++`? Could you update commit message with answer to that question?

When it comes to reason why this class exists in the compiler I think the answer might be different: it's been added way before we even had `TreeSet` in the library or even collections of current design. The `TreeSet` we have in the compiler was added 7 years ago (in ac849228490d5a0e2d3f048d649297d5c59b6ade). We probably should closer look and see if we could switch to standard `TreeSet`. I guess @JamesIry might interested to hear about those findings.

**Comment by gkossakowski** [comment]
I realized that `TreeSet.scala` was added earlier (8 years ago) in this commit: 184a284ccc9c842adaaec728914f11a2cad33c18

The ac84922 just moved it.

**Comment by paulp** [comment]
It's not 100% clear to me either. The stack traces I collected implicate hasNext, like it's walking someone's very long hasNext chain on every call as it works its way through a composed iterator. It's this line in lambdalift which is churning, not sure if it's for the whole four minutes, but probably.

```
      val allFree: Set[Symbol] = free.values.flatMap(_.iterator).toSet
```

**Comment by paulp** [comment]
It might be tied up with Iterator.++ being by-name, something which has in the past been behind any number of confusing iterator behaviors.

**Comment by gkossakowski** [comment]
I think it's useful to find out and include the findings in the commit message. I'll dig into this tomorrow and see if I can understand what's going on.

**Comment by paulp** [comment]
Regarding TreeSet (and Set, HashSet) being old, that doesn't exactly explain why the largest data structure in the compiler is using a custom collection. There have been many trips through that area of the code looking to optimize. Why is uniques still a util.HashSet?

**Comment by gkossakowski** [comment]
@paulp: i reproduced the problem with iterators and logged the ticket: https://issues.scala-lang.org/browse/SI-7316
Could you amend commit message with reference to that ticket saying that O(n^2) is coming from using `Iterator.single` and `Iterator.++`? Once you do that I'll LGTM it.

When it comes to uniques I don't have any good answer but we should be looking into this: https://issues.scala-lang.org/browse/SI-7149. This means we'll still need custom collection but at least for a good reason: to reduce memory consumption.

**Comment by paulp** [comment]
@gkossakowski  updated.

**Comment by gkossakowski** [comment]
LGTM.

I like the way you phrased commit message which makes it easy to see what's going on in this commit and why it improves performance.

**Pull request merged**
