### PR TITLE
Avoid duplicate imports

### PR DESCRIPTION
**Pull request by som-snytt**
Reduced inflammatory remark. Improved bookkeeping for imports.

### CODE REVIEW

**Comment by som-snytt** [comment]
In the same vein as the sentiment that LOC is not a measure of productivity but of cost, we should not be warning about unused imports but about used ones.

**Comment by som-snytt** [comment]
Maybe @hrhino can comment on whether `makeImportContext` is a good idea before retronym says it's a bad idea. That's to avoid seeing the import multiple times and then `distinct`. The rest is just refactor.

**Comment by hrhino** [comment]
I was going to comment but I'm not sure I understand exactly what this is trying to do.

**Comment by som-snytt** [comment]
The first commit converts `foreach` to recursion.

The second commit notices that instead of tracking `import foo.bar` once, it adds it to the list of imports every time context makes a child context that is an import context, i.e., multiple times for multiple typechecks. But the front door for imports is Namers, so I have Namer call a special "make context" for the first time the import is seen. That happens once, and that's when it's added to the list of imports to check later, to see they were used.

The third commit is just to walk that list of imports as it was built instead of reversing first. The list of unused imports is short compared to the list of all imports. Looking at the list of selectors for each import is no longer tailrec, but that is a short list.

Maybe this is more a Diego thing. I even sound like Diego! Except I haven't benchmarked yet.

**Review by lrytz — APPROVED** [review]

**Pull request merged**
