### PR TITLE
Change flags from Int to Long, and remove hasFlag(flag: Int) method.

### PR DESCRIPTION
**Pull request by ccjoywang**
Performance report:
https://gist.github.com/ccjoywang/8b99fca36e05d3a7a61d6502109e2095

another run with 100 iterations 5 processors:
-----
```
ALL
                 Run Name	Cycle	samples	           Wall time (ms)	       All Wall time (ms)	                  CPU(ms)	           Idle time (ms)	           Allocated(MBs)
                     base	   1	 100	8,677.92 [-8.45% +150.87%]	8,677.92 [-8.45% +150.87%]	5,447.52 [-13.10% +211.77%]	       0.00 [ NaN%  NaN%]	1,695.55 [-0.34% +11.73%]
                     base	   2	 100	8,682.64 [-8.27% +122.24%]	8,682.64 [-8.27% +122.24%]	5,440.05 [-13.55% +182.33%]	       0.00 [ NaN%  NaN%]	1,719.55 [-0.26% +11.10%]
                     base	   3	 100	8,399.41 [-5.27% +122.19%]	8,399.41 [-5.27% +122.19%]	5,293.33 [-9.09% +178.94%]	       0.00 [ NaN%  NaN%]	 1,728.22 [-0.93% +9.76%]
                     base	   4	 100	8,574.71 [-4.85% +120.57%]	8,574.71 [-4.85% +120.57%]	5,465.21 [-11.09% +171.02%]	       0.00 [ NaN%  NaN%]	1,722.77 [-0.39% +11.07%]
                     base	   5	 100	8,542.09 [-5.71% +121.99%]	8,542.09 [-5.71% +121.99%]	5,395.94 [-9.38% +177.12%]	       0.00 [ NaN%  NaN%]	1,712.81 [-0.44% +11.20%]
                    after	   1	 100	9,240.10 [-11.97% +166.23%]	9,240.10 [-11.97% +166.23%]	5,591.61 [-12.82% +162.11%]	       0.00 [ NaN%  NaN%]	1,691.40 [-0.39% +11.32%]
                    after	   2	 100	8,383.17 [-5.41% +125.62%]	8,383.17 [-5.41% +125.62%]	5,312.51 [-11.47% +178.23%]	       0.00 [ NaN%  NaN%]	1,716.79 [-0.40% +10.56%]
                    after	   3	 100	8,536.65 [-5.22% +122.52%]	8,536.65 [-5.22% +122.52%]	5,416.58 [-9.15% +166.83%]	       0.00 [ NaN%  NaN%]	1,710.51 [-0.35% +11.52%]
                    after	   4	 100	8,611.46 [-5.53% +136.80%]	8,611.46 [-5.53% +136.80%]	5,478.93 [-9.60% +171.49%]	       0.00 [ NaN%  NaN%]	1,719.18 [-0.37% +11.79%]
                    after	   5	 100	8,429.95 [-5.40% +124.45%]	8,429.95 [-5.40% +124.45%]	5,340.49 [-9.32% +176.19%]	       0.00 [ NaN%  NaN%]	1,701.43 [-0.30% +10.92%]

```

### CODE REVIEW

**Comment by SethTisue** [comment]
what's the motivation for the change...?

**Comment by mkeskells** [comment]
it just getting rid of the Int -> Long conversions as run time

**Comment by mkeskells** [comment]
@ccjoywang do you have a current benchmark to share ( after 50%)
@rorygraves can you assist to run a benchmark for this

**Comment by ccjoywang** [comment]
Reopen from rory's repo https://github.com/scala/scala/pull/6567

**Pull request closed without merging**
