### PR TITLE
Actual SI-6555 fix, Scaladoc filter works now WITH keyboard shortcuts too

### PR DESCRIPTION
**Pull request by heathermiller**
Commit daefab18b8b0c170c372991022357413ec69b2af attempted to fix a bug related to Scaladoc filtering, meanwhile breaking Scaladoc keyboard shortcuts.

Before commit daefab18b8b0c170c372991022357413ec69b2af, Scaladoc's filter wouldn't consider the last character of a search term entered into the (left) Scaladoc filter pane, but toggling with the `tab` key between filter panes did work.

After daefab18b8b0c170c372991022357413ec69b2af, Scaladoc's left pane filter correctly searches for the full search term, but pressing the `tab` key causes the "focus" of the input bar to be stuck on the filter panel in the right Scaladoc filter pane, rendering it useless.

End result: annoying Scaladoc interface bug present in 2.10.1, but which wasn't present in 2.10.0.

This pull request fixes this, enabling both behaviors. The `tab` key toggle needed to be triggered on a `keydown` event, while everything else is fine to be triggered on a `keyup` event. This pull request enables the correct behavior by binding both a `keydown` and a `keyup` event rather than lumping everything all together in a `keyup` event (as was the case before).

### CODE REVIEW

**Comment by heathermiller** [comment]
Review by @kzys and @sjrd

**Comment by kzys** [comment]
Sorry for introducing the issue. LGTM.

**Comment by heathermiller** [comment]
Don't worry about it. That's how life is when you're dealing with javascript. Not easy to test at all :-/

**Comment by heathermiller** [comment]
Besides, I didn't realize that keydown was required for the tab switching until just yesterday. Details, details ;-)

**Comment by sjrd** [comment]
LGTM too. Including a manual test on Linux/Firefox.

**Pull request merged**
