### PR TITLE
Removed restriction on final vars, SI-2418.

### PR DESCRIPTION
**Pull request by paulp**
The original fix for SI-2418 excluded final vars entirely, but
the problem was not final vars per se, but the emission of ACC_FINAL
in combination with ACC_VOLATILE.  Since vars never get ACC_FINAL
now, this is no longer an issue.

Review by @dragos.

### CODE REVIEW

**Comment by paulp** [comment]
Jenkins meant to say "passed" - the only failure is master's own doing.

**Comment by viktorklang** [comment]
:+1: <-- but hey, I'm biased

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by viktorklang** [comment]
Someone will curse me one day for inspiring Paul to add the final volatile vars, I know it... ;-)
But I am convinced that it is great for optimizability.

**Comment by dragos** [comment]
LGTM

**Pull request merged**
