### PR TITLE
Drop scala.{Immutable,Mutable}

### PR DESCRIPTION
**Pull request by hrhino**
They were used as marker traits in the old collections, but don't appear to be used in the new collections. I'm suspicious of marker traits in general, so I propose we drop them rather than hook them into the new collections library.

### CODE REVIEW

**Comment by SethTisue** [comment]
never even knew these had existed

**Comment by martijnhoekstra** [comment]
Now that I know it existed, I will not miss that I could have an `object Foo extends Mutable with Immutable`

**Comment by julienrf** [comment]
Should we deprecate them before removing them?

**Comment by hrhino** [comment]
> Should we deprecate them before removing them?

@julienrf: I thought about it, but since the only use of these traits in 2.12 was as superclasses of im/mutable data structures, it seems that anyone who was using them in the context of the stdlib is already going to have their code broken by the collections redesign not using them. So the only danger is codebases which use these traits for their own purposes, and I think it's reasonable to ask them to make their own marker traits.

That all said, I'm completely willing to deprecate them in 2.12.7 if they'll be removed in 2.13.

> Now that I know it existed, I will not miss that I could have an `object Foo extends Mutable with Immutable`

You've probably got ~6 months or so before 2.13 is out the door (not like I'd know)... I for one am sneaking this into my work codebase while I still can.

**Comment by julienrf** [comment]
I would just remove these traits and simply document that.

**Review by dwijnand — APPROVED** [review]
LGTM!

**Pull request merged**
