### PR TITLE
SI-9113 Converting `null` collection Java<->Scala yields `null`

### PR DESCRIPTION
**Pull request by adriaanm**
Rewording of #4267, already reviewed.

### CODE REVIEW

**Comment by adriaanm** [comment]
@retronym, @axel22 -- I couldn't parse your previous review comments with absolute certainty, so could you please take a quick look at the commit message to make sure I understood correctly?

**Comment by RomanHargrave** [comment]
[_This is a copy of a comment I left in the former PR_](https://github.com/scala/scala/pull/4267#issuecomment-74299092)

@retronym Just had a thought at random this morning. Wouldn't it make more since for the decorated converters (.asJava, .asScala) to throw exceptions, but for the implicit converters to return null? My logic is that it would make debugging simpler. For instance, when passing an X collection to a function that wants a Y collection with implicit conversion, it will appear in source form as if that reference is being passed to said function (when there is really an intermediate function call inserted during compilation), and as such, it would make more sense for that function to throw the exception from within. On the other hand, when using the decorative method, it appears as if you are calling a function provided by X collection to get a Y collection. In the latter (decorator) case, it would make more sense to throw an exception from inside the conversion method, as it would be clear that the programmer _explicitly_ wanted to call a member function of X collection, rather than pass the reference to X to the method (whether it be null or not). What do you think?

**Comment by axel22** [comment]
That sounds like an interesting idea.
My primary concern is, still, with breaking existing code.

@adriaanm The commit message sounds right.

**Comment by retronym** [comment]
I've been thinking about this one, and I agree with @axel22's concerns about compatibility.

I don't think we can change the eagerness of these `NullPointerException`s in a minor release. Let's retarget this to 2.12.x.

**Comment by adriaanm** [comment]
Ok, I'll resubmit for 2.12.x

**Comment by adriaanm** [comment]
See #4343

**Pull request closed without merging**
