### PR TITLE
Infer function parameter types from partially eta-expanded methods (backport  #7316 and #7333)

### PR DESCRIPTION
**Pull request by adriaanm**
Backport a fix for scala/bug#9745 (#7316) and improve type inference for partial eta-expansion (#7333)

This improves inference of function parameter types for partially eta-expanded methods (i.e., when only some arguments are omitted using `_`)

Example from the test, given `def repeat(x: Int, y: String) = y * x`, partial eta-expansion recovers fun param types from the definition of the selected method:
```
val sayAaah = repeat(_, "a") // place holder syntax
val thrice = x => repeat(3, x) // explicit version
val repeatFlip = (x, y) => repeat(y, x) // explicit version, two params
```

### CODE REVIEW

**Comment by lrytz** [comment]
It's not a small diff, and touches a quite heavily used and non-trivial part of the type checker. On the other hand, the fact that it's heavily used (in 2.13, exercised by collections) gives it a good coverage. So I'm +1.

**Comment by adriaanm** [comment]
Note that I dropped one behavior change from the 2.13 version: we still report errors in bodies of functions that have params with missing types.

**Review by retronym — APPROVED** [review]
I'm happy to align 2.12 with 2.13 here.

It would be great to write a short doc describing the various changes and fixes to type inference of lambdas so that @niktrop et al can bring them into IntelliJ.

**Comment by SethTisue** [comment]
I think this is release-note worthy for 2.12.8, so that's another reason for the PR description to be updated to describe the user-facing parts.

**Pull request merged**
