### PR TITLE
Fix repl-save test

### PR DESCRIPTION
**Pull request by som-snytt**
Running by the validator; I'll have to reboot to test in Windows -- I'll do that in a bit.  But it seems like it might work.

Make the test a SessionTest, where the file name appears just
once, in the transcript, and is trivially compared against itself.

The contents of the saved file are still output and compared with
the check file.

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks, I'll run the windows validation on our jenkins.

**Comment by adriaanm** [comment]
Running here: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/1/console

Sorry, we don't yet have a nice way of opening this up.

**Comment by adriaanm** [comment]
Frigging windows, make that https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/4/console

**Comment by som-snytt** [comment]
Lends a new slant on, "I don't do windows." 

Glad it passed, thanks.

**Comment by adriaanm** [comment]
LGTM, thanks!

**Pull request merged**
