### PR TITLE
SI-7968 Use an intrinsic for the next power of two calculation.

### PR DESCRIPTION
**Pull request by RajivKurian**
Fixes issues raised in #3126.
The nextPowerOfTwo function is replaced by nextPositivePowerOfTwo which provides the following improvements:

1) Uses the Integer.numberOfLeadingZeros intrinsic for the actual implementation.
2) If the input is already a power of two it just returns the number instead of returning the next power of two.
3) Works for negative numbers and zero as input. The output is 1 in both cases.

### CODE REVIEW

**Comment by RajivKurian** [comment]
Also I signed the CLA.

**Comment by adriaanm** [comment]
Welcome, and thank you , @RajivKurian! Please squash your commits (we require each individual commit to pass the test suite) and rebase them on top of master as soon as #3114 is merged (there was an issue with our testing infrastructure that should be fixed in the next couple hours).

**Comment by adriaanm** [comment]
Update:  #3114 has been merged, please do something along the lines of:
`git checkout OpenHashMap-nextPowerOfTwo-implementation && git pull --rebase https://github.com/scala/scala.git master`. To squash your commits, something like `git rebase -i HEAD^^` should work.
Once all that's done, do a `git push -f git@github.com:RajivKurian/scala.git HEAD:OpenHashMap-nextPowerOfTwo-implementation`

**Comment by RajivKurian** [comment]
@adriaanm I think I followed your suggestions correctly.

**Comment by adriaanm** [comment]
You correctly rebased on master, but to squash the commits you'll have to edit the rebase todo list (the one you get after doing `git rebase -i HEAD^^`) to look something like:

```
pick 3b6cdf4 Use an intrinsic for the next power of two calculation and also return the input as is if it is already a power of two
fixup 25be768 typo
```

the "fixup" command tells git to amend the previous commit, discarding the message of the current commit (it just says typo anyway)

**Comment by RajivKurian** [comment]
@adriaanm Thanks for your patience - had another go at it :)

**Comment by adriaanm** [comment]
No worries! Thanks for contributing to Scala!

**Comment by JamesIry** [comment]
review by @ichoran plz

**Comment by Ichoran** [comment]
LGTM.  Note that this does change behavior, but the new behavior is arguably more correct (i.e. when you ask for 8 you get 8 instead of 16).  You can no longer have arrays of length 0, which might also be more correct.

**Pull request merged**
