### PR TITLE
Restore backend tests that were removed together with GenASM

### PR DESCRIPTION
**Pull request by lrytz**
Restores the tests that were moved to "pending" when GenASM was removed (#4814).

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @soc

**Comment by soc** [comment]
LGTM!

**Comment by SethTisue** [comment]
@lrytz should https://issues.scala-lang.org/browse/SI-9364 be closed, then?

**Comment by lrytz** [comment]
possibly - i'm still checking a few issues on jira, this one is on the list

**Pull request merged**
