### PR TITLE
Insert missing copyright headers

### PR DESCRIPTION
**Pull request by retronym**
Review by @gourlaysama

### CODE REVIEW

**Comment by mpociecha** [comment]
Is Martin Odersky an author of each of them? Really?

Maybe just?

```
/* NSC -- new Scala compiler
* Copyright 2012-2014 LAMP/EPFL
*/
```

**Comment by retronym** [comment]
The convention used elsewhere in the repository is to put Martin as the author of all files.

**Comment by gourlaysama** [comment]
Shouldn't the ones in the library get the library header (the "Scala API" one with ASCII-art)?

**Comment by mpociecha** [comment]
@retronym Sure, I saw this. But it doesn't mean that it has to be a good convention. But obviously this is your project - not mine. ;)

**Comment by retronym** [comment]
I'll reopen this shortly with better handling of compiler vs library copyright.

**Comment by retronym** [comment]
@mpociecha I understand it to mean that he's the primary author of the compiler, rather than the file.

**Comment by som-snytt** [comment]
http://en.wikipedia.org/wiki/What_Is_an_Author%3F

**Pull request closed without merging**
