### PR TITLE
Move side-effecting call out of debuglog(). Fixes SI-6223.

### PR DESCRIPTION
**Pull request by non**
This change fixes a situation in which method calls aren't being properly
specialized. All the existing tests pass; in addition, it likely fixes other
specialization bugs (and improves performance of specialized code).

Review by @VladUreche or @paulp.

P.S. As I said on list, this is a very small change and it would be great
to backport to 2.10! I can send another pull request if this seems like a good idea.

### CODE REVIEW

**Comment by paulp** [comment]
LGTM (for both branches.)

**Comment by paulp** [comment]
Although we should require a test case.

**Comment by non** [comment]
Oh, sorry! I'll write a test case ASAP!

**Comment by non** [comment]
Alright, that test case makes sure that the specialized subclass defines all the methods we'd expect (without the patch it fails missing bar$mIc$sp and bar$mIcI$sp).

**Comment by paulp** [comment]
LGTM again.

**Comment by VladUreche** [comment]
LGTM too. Should I merge?

**Comment by non** [comment]
Please do. :)

**Comment by VladUreche** [comment]
Wait, shouldn't this be against 2.10.x?

**Comment by non** [comment]
I was going to prepare a separate pull request for that. It's an issue in 2.10.x and master both.

**Comment by VladUreche** [comment]
Then I'll merge into 2.10.x directly as soon as you file the pull request - the 2.10.x branch is constantly merged into master afaik.

**Comment by non** [comment]
Alright, I'm closing this pull request. The new one is at https://github.com/scala/scala/pull/1130.

**Pull request closed without merging**
