### PR TITLE
SI-8774 Null link fields in mutable LinkedHashMap (and friends) on remove

### PR DESCRIPTION
**Pull request by varming**
It is about time to close SI-8774.

I bootstrapped the compiler to verify that my solution does not hit the bug mentioned in SI-8774.

### CODE REVIEW

**Comment by szeiger** [comment]
LGTM. Considering the discussion in #3911 it would make sense to keep SI-8774 open or open a new ticket for possible changes to the collection specification regarding fail-fast behavior for 2.13.

**Comment by varming** [comment]
Dear @szeiger,

Thank you for the review.

By fast fail I assume you are hinting at throwing ConcurrentModificationException exceptions. I would open a new ticket to get a fresh discussion about potential implementations and their performance impact.

**Comment by szeiger** [comment]
Great, thanks. Please link to #3911 and SI-8774 in the new ticket.

**Comment by varming** [comment]
@szeiger, I don't have an jira account, do you mind opening the ticket?

**Comment by adriaanm** [comment]
We'll also take tickets over at https://github.com/scala/scala-dev/issues. Friends don't make friends use jira :-)

**Pull request merged**
