### PR TITLE
Delay delambadficaion and put the lambda's body into the containing class

### PR DESCRIPTION
**Pull request by JamesIry**
This is an experimental work in progress PR to bring us closer to using method handles. It will be entirely protected by a flag until it is as solid as the current mechanism.

With the flag enabled the compiler will defer final translation from lambda to class until very late in the pipeline, and it will put the body of the lambda in a method in the original class.

This PR leaves two key things undone

1) Specialization still needs to be handled.
2) Logic that partially prevents the use of 'this' in a super constructor call is bypassed. That logic needs to be redone in order to have fewer holes and be less brittle.

### CODE REVIEW

**Comment by adriaanm** [comment]
:cake:!

**Comment by retronym** [comment]
Commit comments need a little brush up to follow the "Subject... \n\nBody" convention.

**Comment by huitseeker** [comment]
The multiple fails of the validator on this PR, e.g. [this](https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/1643/) IDE failure on [52cdea193ee91301197b40823ac7a9354bd60a14](https://github.com/JamesIry/scala/commit/52cdea193ee91301197b40823ac7a9354bd60a14) 
are genuine.

**Comment by sjrd** [comment]
I couldn't resist, so I hacked this:
https://github.com/sjrd/scala-js/commit/3c913fae14c868d3faa5c6c8ff35484bcf1b87f5
over the last 2.5 hours.
Support for -Ydelambdafy:method for Scala.js, based on this pull request.
Seems to work, but I'm too tired to really reason about it thoroughly. I did compile the entire standard library + the reversi demo with -Ydelambdafy:method, and it worked well :)

Basically there is one concrete class per arity, e.g.,

``` scala
final class AnonFunction1[-T1, +R](f: js.Function1[T1, R]) extends AbstractFunction1[T1, R] {
  override def apply(arg1: T1): R = f(arg1)
}
```

and all anonymous functions are simply translated into an instantiation of the appropriate `AnonFunctionN` with a JavaScript lambda as parameter.

@JamesIry From your code and from output trees, I inferred the following:

> Anonymous functions survive until the backend only under
> `-Ydelambdafy:method`
> and when they do, their body is always of the form
> `EnclosingClass.this.someMethod(arg1, ..., argN, capture1, ..., captureM)`
> where `argI` are the formal arguments of the lambda, and `captureI` are local variables or the enclosing def.

Is it indeed true? Did I get it right?

**Comment by magarciaEPFL** [comment]
The point raised by @sjrd is relevant for future compatibility with JDK 8, quoting from https://github.com/magarciaEPFL/scala/commit/2cee8fd7fe1214b1323ad6e3f1f5a6b7afd29de8

> A LambdaMetaFactory in JDK8 delivers lambdas that assume
> the (hoisted) target method to have arguments for all captured values and for apply-args (in that order).
> In contrast, "hoisted target methods" emerge from LambdaLift with formal-params for captured values appended  after those for apply-args.
> Moreover, for mixins, the first formal of an endpoint in an implementation class denotes the self-reference.

**Comment by magarciaEPFL** [comment]
Any preliminary benchmark on how much faster the compiler compiles under `-Ydelambdafy:method` ? Yes, I know no benchmark is perfect, but the following helps: compile the compiler and let us know the wall-clock time.

**Comment by sjrd** [comment]
> A LambdaMetaFactory in JDK8 delivers lambdas that assume the (hoisted) target method to have arguments for all captured values and for apply-args (in that order).

As a matter of fact, it is also the ordering best supported by `Function.prototype.bind` in JavaScript.
Given that both systems would be "more comfortable" with captures before, I suggest that delambdafy follow that scheme.

**Comment by magarciaEPFL** [comment]
This PR contains several commits that are refactorings or fixes unrelated to "delamb". Perhaps it's best to factor them out into their own PR, review them, merge (they should be far less controversial). A preliminary list of candidates follows.

Looks like each of the following doesn't depend on any other. 
- Symbol.toString https://github.com/JamesIry/scala/commit/f77ddaf3768912dfee9ce67b075243fb5410677e
- future-spec-related constructors which  https://github.com/JamesIry/scala/commit/3ce5c97d074f7b98d3740afcd95cc970eaf8da95
- uncurry-related https://github.com/JamesIry/scala/commit/15ef90d01b3feb10260fad6fa00cea3c12f342de
- GenASM-related https://github.com/JamesIry/scala/commit/4cd850dac1ed7b41f61e1aea11d6bc2759ac229d
- specialization-related https://github.com/JamesIry/scala/commit/0b9c3f7a3f67ef2eb6c1f09ce4e5a63edda0fa6d

The following one is also independent of the previous ones but with a "delamb" smell to it:
- erasure-related https://github.com/JamesIry/scala/commit/8411cd3e9e2de1d4f6e3d6c08d89fd6fa00f8c45

That leaves only six other commits as the real payload of this PR.

HTH!

**Comment by JamesIry** [comment]
Thanks for the feedback everyone.

@retronym I've got a fix for the test failure. It has to do with self types vs inheritance.
@magarciaEPFL I'll pull the Symbol.toString commit into a different PR. All the others are directly related to the story of the PR in the sense that delayed delambdafication doesn't work without the previous steps.
@sjrd I'll reorder the arguments with the next iteration of this PR.

**Comment by magarciaEPFL** [comment]
@JamesIry 

> All the others are directly related to the story of the PR in the sense that delayed delambdafication doesn't work without the previous steps.

Yes, I know. The suggestion to merge them earlier was motivated because in general I'm in favor of merging sthg as soon as it's known to work well. For example, commit https://github.com/JamesIry/scala/commit/3ce5c97d074f7b98d3740afcd95cc970eaf8da95 is useful on its own.

I guess as long as this PR doesn't take that long to review it's ok to keep them bundled. Otherwise those commits "useful on their own" should be merged earlier.

**Comment by adriaanm** [comment]
Temptingly close, but alas! This will slip to M6.

**Comment by retronym** [comment]
The build kitteh was misbehaving and jobs from this PR were being built over and over. I've tried to manually cancel them in Jenkins to clear the congestion. Please disregard the latest build failures.

**Comment by retronym** [comment]
NOLITTER!

**Comment by retronym** [comment]
Closing in part due to the merge conflicts and in part due to the fact the build kitteh is in an endless build loop at the moment and this PR has been built a dozen times over the weekend.

**Pull request closed without merging**
