### PR TITLE
Override equals and hashCode for WrappedArray

### PR DESCRIPTION
**Pull request by adriaanm**
Rebase of #5551 (also removed mima filter that should no longer be needed)

### CODE REVIEW

**Comment by lrytz** [comment]
The whitelist change moved from `bincompat-forward.whitelist.conf` to `bincompat-backward.whitelist.conf`, which seems to be wrong

**Comment by lrytz** [comment]
I `git push -f`'d to your branch, how evil! 🙈

**Comment by adriaanm** [comment]
🙉

**Comment by alexeyr** [comment]
@lrytz It seemed wrong to me to, but that's what I had to do to avoid MiMa errors. Maybe MiMa had a bug fixed since then?

**Pull request merged**
