### PR TITLE
SI-7246: javac doesn't add $outer field.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by retronym** [comment]
Could you please add a little more detail to the commit message?

**Comment by vigdorchik** [comment]
Review by @retronym

**Comment by retronym** [comment]
The commit message format doesn't meet the [guidelines](https://github.com/scala/scala/blob/master/CONTRIBUTING.md): 

```
SI-1234 Short summary of the change goes here.

Some background on the problem. Word wrap manually
to 70 chars.

Overview of solution.

  - bullet points of specific changes
```

Could you add a test in which the Java class extends a Scala class, which provides the outer field? `Scala.Inner1 <:< Java.Inner2 <: Scala.Inner3`.

**Comment by vigdorchik** [comment]
@retronym I changed the commit message, and also added the second test. Actually the second test tests the superset of the first, so I would leave only it, but is the policy that we have to keep original testcase intact?

**Comment by retronym** [comment]
After reviewing the existing code that you were changing, I was motivated to clean up a few things; see #2270

**Pull request closed without merging**
