### PR TITLE
SI-7520 bug in subtyping.

### PR DESCRIPTION
**Pull request by paulp**
isSubType, if given two SingleTypes, would check =:= and stop there. It is
necessary to continue with weakening the left hand side, because (for
instance) the singleton type on the left hand side could be a refinement
class carrying parents which are themselves single or constant types.

### CODE REVIEW

**Comment by JamesIry** [comment]
Who wants to own the review? @adriaanm ?

**Comment by adriaanm** [comment]
Ok.

**Comment by adriaanm** [comment]
The fix itself LGTM, but 2ac21de should be split.

**Comment by adriaanm** [comment]
LGTM, though there's now a nice opportunity for improving naming:
The `2` in `isSubType2` could be replaced with something that means some, say `PreChecked`

**Comment by paulp** [comment]
I'll devote myself to improving on that 2 in a commit to be named later.

**Pull request merged**
