### PR TITLE
SI-7600 [Avian] Skip tests r/stream_length and r/t4294

### PR DESCRIPTION
**Pull request by soc**
The issue is that Avian's GC is currently not precise enough to
determine the exact lifetime of each local/stack reference, and
therefore considers the this reference to be reachable in situations
where it could have been collected.

This can cause issues (as seen in run/stream_length and run/t4294:
`java.lang.OutOfMemoryError`) if code relies on the garbage collection
of these values to keep memory consumption constant.

This commit simply skips these two tests on Avian until the GC
implementation is fixed.

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM

**Comment by som-snytt** [comment]
LGTM. I think the !avian bit is the first feature I've contributed that anyone uses, since no one seems to use repl's javap under java7.

I'll go celebrate now.

**Comment by huitseeker** [comment]
LGTM

**Comment by adriaanm** [comment]
This somehow breaks a refactoring test in the IDE: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/236/console

**Comment by soc** [comment]
This looks pretty spurious to me ... maybe someone from the IDE team can comment?

**Comment by adriaanm** [comment]
Yep, I'm sure it is spurious. "Somehow" probably wasn't clear enough ;-)

**Comment by soc** [comment]
@adriaanm What should we do about it? Is it possible to tell kitty to run the IDE tests again? Or should we ignore it?

**Comment by adriaanm** [comment]
We're not set up yet to give IDE integration veto rights (soon, though!), so it was more of an FYI.

**Pull request merged**
