### PR TITLE
chore: fix some comments

### PR DESCRIPTION
**Pull request by luozexuan**

### CODE REVIEW

**Comment by SethTisue** [comment]
Thanks! Mind signing the CLA?

**Comment by luozexuan** [comment]
> Thanks! Mind signing the CLA?

Thanks. Signed.

Please review again

**Comment by lrytz** [comment]
@luozexuan I still get `false` here: https://www.lightbend.com/contribute/cla/scala/check/luozexuan. To sign it, go here: https://www.lightbend.com/contribute/cla/scala. Thanks!

**Comment by luozexuan** [comment]
> @luozexuan I still get `false` here: https://www.lightbend.com/contribute/cla/scala/check/luozexuan. To sign it, go here: https://www.lightbend.com/contribute/cla/scala. Thanks!

Sorry, I misunderstood your meaning. I thought it meant signing the submission. The CLA has now been signed

image

Please review again.

**Comment by lrytz** [comment]
Thanks!

**Pull request merged**
