### PR TITLE
[ci: last-only] merge 2.11.x onto 2.12.x (February 14, 2017)

### PR DESCRIPTION
**Pull request by SethTisue**
many of the PRs merged for 2.11.9 were backports, so we proceed
by considering each PR individually.

`git log --merges origin/2.11.x ^origin/2.12.x` shows:

* 0965028809 - Merge pull request #5695 from SethTisue/fix-indexedseqtest-under-ant (6 hours ago) <Seth Tisue>
* 214a158f67 - Merge pull request #5664 from adriaanm/rework-coll-perf (6 days ago) <Adriaan Moors>
* 6644017dad - Merge pull request #5631 from adriaanm/ticket/9013 (3 weeks ago) <Adriaan Moors>
* 90a764bcba - Merge pull request #5645 from sjrd/avoid-array-oob-in-rbtree-iterator-from (3 weeks ago) <Adriaan Moors>
* a5d38ea334 - Merge pull request #5630 from adriaanm/rebase-5557 (5 weeks ago) <Adriaan Moors>
* 36967321c7 - Merge pull request #5632 from adriaanm/ticket/9114 (5 weeks ago) <Adriaan Moors>
* fac487e397 - Merge pull request #5633 from adriaanm/ticket/9331 (5 weeks ago) <Adriaan Moors>
* 32a7461037 - Merge pull request #5635 from adriaanm/jline-2.14.3 (5 weeks ago) <Adriaan Moors>
* 4f5c30e10a - Merge pull request #5615 from monkey-mas/modify-ArrayBuilder-reusability-bug-2016-12-24 (5 weeks ago) <Stefan Zeiger>
* 1b6b19b701 - Merge pull request #5626 from adriaanm/rebase-5566 (6 weeks ago) <Adriaan Moors>
* 18269eabe1 - Merge pull request #5612 from adriaanm/patmat_cleanup (6 weeks ago) <Adriaan Moors>
* 8367bf68c1 - Merge pull request #5624 from Jasper-M/patch-1 (6 weeks ago) <Lukas Rytz>

5612 is a special case: part backport, part not.  I consulted with
Adriaan and he said to handle 3 commits as follows:

* 014ebc4 merge forward, resolving easy merge conflict manually
* 80ce231 do not merge, 2.12 already has the fix
* da98683 backport, do not merge

to avoid extra merge commits, we don't need to merge every PR individually,
we can chunk them according to whether they are backports or not.  so that yields:

```
git merge                 8367bf68c1   # 5624
git merge                 014ebc4      # 5612
git merge --strategy=ours 32a7461037   # 5612, 5626, 5615, 5635
git merge                 36967321c7   # 5633, 5632
git merge --strategy=ours a5d38ea334   # 5630
git merge                 0965028809   # 5645, 5631, 5664, 5695
```

### CODE REVIEW

**Comment by SethTisue** [comment]
this is WIP. let's see what Jenkins says about tests and about MiMa.

the MiMa piece of this is not done yet. 5664 produced nasty merge conflicts in the whitelist files, which I plan to deal with by just seeing what Jenkins says and using that as a guide for what I need to add to the whitelist files.

**Comment by SethTisue** [comment]
test failure: t1459 gives slightly different output because of 27c10db549e6f43571663d0162b58fc04fbb34bf

hmm, in 0a6eb70 I added the compiler warning to the check file, but now that I look closer at 27c10db5 I see that adding `@SafeVarargs` to the test sources might be a better solution. well, let's let Jenkins chew on it first

**Comment by SethTisue** [comment]
> adding @SafeVarargs to the test sources might be a better solution

bah, it's an interface, so we can't do that. http://stackoverflow.com/questions/37829160/safevarargs-on-interface-method#37959022

**Comment by SethTisue** [comment]
Jenkins is rushing from PR to PR like the protagonist of William Pène du Bois's “The Twenty-One Balloons” on the balloon platform. hang in there, Jenkins.

**Review by adriaanm — APPROVED** [review]
A (non-critical) follow-up item: are all mima entries needed on 2.12? 99% sure the answer is yes, so let's merge, but may want to double check.

**Pull request merged**
