### PR TITLE
SI-7074 Fix xml attribute sorting

### PR DESCRIPTION
**Pull request by khernyo**

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks! Could you please sign the Scala CLA electronically here: http://typesafe.com/contribute/cla/scala ?

**Comment by khernyo** [comment]
I've already signed that. Twice :)

**Comment by adriaanm** [comment]
I expected as much, and I do apologize, but we just switched to a centralized way of electronically signing the CLAs. 

I manually imported the CLAs I could get my hands on, but the secretary at EPFL who was in charge of tracking the scanned-in CLAs recently went on a sabbatical, so some CLAs may have been lost.

I apologize for the inconvenience. On the bright side, the new way of signing is 1 min of work.

**Comment by adriaanm** [comment]
(And allows us to automate this process.)

**Comment by khernyo** [comment]
That's understandable, but I have only ever signed it digitally, so you might have lost some of the digitally signed CLAs. Anyway, I have done it again just to be sure.

**Comment by adriaanm** [comment]
That is indeed worrisome. Are you referring to the Typesafe CLA, perhaps? We just started signing the Scala CLA electronically yesterday.

**Comment by adriaanm** [comment]
In any case, thanks for signing again, and thank you for your contributions!

**Comment by paulp** [comment]
The signing process is spectacularly confusing; for me at least, it presented the typesafe CLA and the scala CLA in quick succession, and you had to be an expert in "Where's Waldo" to realize you were being presented with a new, different, second thing (yet being required to enter your mailing address and etc. all over again.)

**Comment by khernyo** [comment]
You are right, I didn't realize it's a new thing, so I was referring to the Typesafe CLA. But the one I signed yesterday (about 16 hours ago) is the Scala CLA, I checked it in my mailbox.

**Comment by JamesIry** [comment]
review @gkossakowski

**Comment by adriaanm** [comment]
> it presented the typesafe CLA and the scala CLA in quick succession

I must have blinked and missed the Typesafe one, as I went through the process as well before sending out the link and all I saw was the Scala CLA.

**Comment by paulp** [comment]
Did you have to enter your info twice? If not, I would suppose it had you on file already for one and not the other.

**Comment by gkossakowski** [comment]
@khernyo: I think your fix looks correct (it's great you attached a good test-case) but a few sentences of explanation what was wrong before and why your fix is correct should be added to a commit message. I looked into linked JIRA issue and I had rather hard time understanding what's the real issue here. For benefit of future generations, we should provide a summary of that discussion.

**Comment by khernyo** [comment]
OK, I will do that.

**Comment by gkossakowski** [comment]
LGTM.

Thanks a lot for improved commit message. Now it's clear what the fix is.

**Pull request merged**
