### PR TITLE
add JDK 21 Early Access to nightly CI

### PR DESCRIPTION
**Pull request by SethTisue**
prompted by https://github.com/scala/bug/issues/12783

### CODE REVIEW

**Comment by SethTisue** [comment]
I had hoped that this would be as easy adding `21-ea`, but nooooooooooo, `Error: Could not find satisfied version for SemVer '21'`

**Comment by SethTisue** [comment]
okay, I got the CI config correct I think

but the new jobs are now failing because of https://github.com/scala/bug/issues/12783 (which is the root cause of https://github.com/sbt/sbt/issues/7235)

and note that it fails trying to even start sbt

so, eventually we do want to merge this PR, but we won't able to use this PR's setup to test the fix for 12783, because of the circularity involved

we'll need to make the fix, locally publish a Scala with the fix (2.12.18-M2, say), then test that it fixes https://github.com/sbt/sbt/issues/7235 by starting sbt with that Scala version (will we need to build a new sbt, or can we tell the launcher directly to use 2.12.18-M2?). if that succeeds, then we're good

@eed3si9n if I have 2.12.18-M2 published locally, can I tell sbt to use it without having to rebuild sbt?

**Comment by eed3si9n** [comment]
> @eed3si9n if I have 2.12.18-M2 published locally, can I tell sbt to use it without having to rebuild sbt?

You could try something like launch


```bash
sbt -Dsbt.scala.version=2.12.18-M2
```

with potentially needing `project/plugins.sbt`:

```scala
// Global / resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
def scala212 = "2.12.18-M2"
scalaVersion := scala212
dependencyOverrides += "org.scala-lang" % "scala-library" % scala212
dependencyOverrides += "org.scala-lang" % "scala-compiler" % scala212
```

**Comment by SethTisue** [comment]
after #10397 goes through, this one can come next

**Comment by SethTisue** [comment]
in my local testing on top of #10397, I'm seeing some test failures:

```
!!  665 - run/repl-no-imports-no-predef.scala       [output differs]
!!  672 - run/repl-parens.scala                     [output differs]
!!  699 - run/sammy_after_implicit_view.scala       [output differs]
!!  711 - run/sammy_restrictions_LMF.scala          [output differs]
!! 1295 - run/t5535.scala                           [output differs]
!! 1338 - run/t5789.scala                           [output differs]
!! 1465 - run/t6434.scala                           [output differs]
!! 1643 - run/t7747-repl.scala                      [output differs]
!!  141 - neg/macro-exception                       [output differs]
!!  150 - neg/macro-invalidret                      [output differs]
```

a number of tests are sensitive to a `toString` change for lambdas, resulting in diffs like:

```diff
-res17: () => Int = <function>
+res17: () => Int = $Lambda/0x000000080177c430@52449bdb
```

the failing neg tests are because of test sensitivity to exact stack trace contents:

```diff
-   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
+   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

and `run/sammy_restrictions_LMF` fails with an exception, cause not immediately obvious. I'll look into it later

**Comment by lrytz** [comment]
> `toString` change for lambdas

Probably needs an adjustment here:

https://github.com/scala/scala/blob/418f76d33bb7dff9e24033e11f72dd335126af58/src/partest/scala/tools/partest/ReplTest.scala#L78-L79

**Comment by som-snytt** [comment]
```
  private val lambdaless = """\$Lambda\$\d+/(?:0x[a-f0-9]{16}|\d+)(@[a-fA-F0-9]+)?""".r
  private val lambdaless = """\$Lambda(?:\$\d+)?/(?:0x[a-f0-9]{16}|\d+)(@[a-fA-F0-9]+)?""".r
```
optional bit after `$Lambda`, probably I should test it if I'm going to say it.

OK also make that last group noncapturing.
```
val lambdaless = """\$Lambda(?:\$\d+)?/(?:0x[a-f0-9]{16}|\d+)(?:@[a-fA-F0-9]+)?""".r
```

**Comment by som-snytt** [comment]
@SethTisue thanks for early action on EA. I pushed a tweak. I feel so nerdy pushing to 2.12.

**Comment by SethTisue** [comment]
rebased as #10400

**Pull request closed without merging**
