### PR TITLE
SI-2818 Makes List#foldRight work for large lists

### PR DESCRIPTION
**Pull request by JamesIry**
Uses length compare to determine if the list is "large" (currently
meaning 10 or more elements). If so, it reverses the list and does a
a fold left with the flip of the supplied function. For small lists it
uses the default foldRight implementation.

The code was written by @paulp. I'm just packaging it up and adding
some tests.

review @gkossakowski

### CODE REVIEW

**Comment by paulp** [comment]
My suspicion is that 5 is a better threshold.

**Comment by JamesIry** [comment]
Did it pass or not? PLS REBUILD ALL

**Comment by seanparsons** [comment]
I think that threshold can go higher not lower: https://gist.github.com/4464286#file-output

**Comment by JamesIry** [comment]
@seanparsons, your results are bizarre. For lists above the threshold the alternative should take at or above the time for the revers/foldLeft version.  But then I did a 2 dimensional benchmark to vary the threshold and also got the same weirdness. :-)

https://gist.github.com/4684881

**Comment by JamesIry** [comment]
I spent awhile looking for an equilibrium point. A point where if the list is length n, then making the threshold n - 2 or n + 2 had little impact on the time, i.e. either branch takes about the same time to do a fold right. That magic number seems to be ~110 on my computer.  For significantly smaller or larger n fixing the list length to n and then varying the threshold from n - 2 to n + 2 had a significant impact on the foldRight time.

**Comment by paulp** [comment]
That is only part of the story; also at issue is the frequency distribution of list lengths. But I'm having trouble convincing myself of how exactly to apply that data. If 98% of all lists have 5 or fewer elements, how should that inform the question? I'm going to give myself permission not to think about it anymore.

I forget, did I try out always doing the normal fold implementation and catching the stackoverflow and continuing from there? I wonder if that's feasible. Probably a terrible idea.

**Comment by gkossakowski** [comment]
@paulp: catching `StackOverflow` tends to disable JIT optimizations.

**Comment by paulp** [comment]
That's interesting for a whole bunch of reasons, among which are:
- people catch it all the time, by virtue of "catch _: Throwable"
- people catch it all the time, by virtue of "try foo catch bar" where bar is a partial function, because the partial function has to work by catching throwable and then rethrowing those throwables for which it is not defined

That second point has been bothering me for a while on the suspicion that it is deoptimizing us where used. With type macros or what have you we could synthesize a catch block which only caught the right types, at least when people aren't performing arbitrary computations to decide what they're catching.

**Comment by paulp** [comment]
And if you're saying it disables optimizations transitively - like I catch it in foo() and then call bar(), where all the real work is - then we're really screwed. If it's not transitive, then that's what we could do in foldRight.

**Comment by JamesIry** [comment]
I should have made clear on my equilibrium comment above. Reverse/foldLeft is faster on smaller lists (up until 110 or so), while stock foldRight is faster above that.

But since the stack is hard to predict, I think we should simplify everything and always do reverse/foldLeft. It will be a bit slower for that middle range of lengths where stock foldRight wins and doesn't blow the stack, but I can live with that.

**Comment by gkossakowski** [comment]
@paulp: I don't know all the details, unfortunately. I observed it only once when @adriaanm introduced catching `StackOverflowException` to new pattern matcher and our warm performance dropped by 8-10%. I verified that removing just that one catch would bring back the performance. I managed to reproduce it on 2 different machines. I didn't dig deeper to understand all the aspects of that phenomenon, though.

**Comment by paulp** [comment]
Okay, but that information alone doesn't tell us it has anything to do with catching StackOverflowException. For instance removing the catch could have reduced the method size such that it crossed the inlinable boundary. You tried catching different exceptions without making any other changes and didn't see the same thing, or...?

**Comment by ijuma** [comment]
About the option of always reversing, also worth taking into account the allocation profile of that option which matters more in real applications where GC pressure can be higher than a micro benchmark with a generous heap.

**Comment by JamesIry** [comment]
1) for smaller lists the memory alloc/dealloc will often be pointer bumps because its all short lived objects.
2) For really large lists this version requires more heap. The old version exploded the stack. I know which I prefer.
3) There is a middle ground where the old version was better all the way around - micro benchmark, heap allocation profile, etc.  I DON'T CARE. Or rather, I do care, I just don't see how to predict what the upper bound on that range is.

Please can we get more usable version of foldRight shipped and take alternative optimization strategies to the mailing lists.

**Comment by paulp** [comment]
@JamesIry I'm with you on putting this thing to bed, but I think the original implementation is more conservative than is always reversing.

**Comment by JamesIry** [comment]
You mean the one that checked length and decided whether to reverse or not? I can go back to that one if that's what it takes to make this pain in the ass go away.

**Comment by paulp** [comment]
I'm not putting my foot down or anything, I just prefer it. Either that or this LGTM.

**Comment by gkossakowski** [comment]
@paulp: yes, the bytecode size is an alternative explanation. We would need to dig deeper so let's drop it for now.

@JamesIry: I agree. LGTM. If anybody thinks this PR is suboptimal please move the discussion to mailing list. We can always improve it later.

**Pull request merged**
