### PR TITLE
Actually fixes SI-5055. Also adds keyboard shortcuts to Scaladoc- makes browsing fun again.

### PR DESCRIPTION
**Pull request by heathermiller**
Makes Scaladoc a zillion times less annoying to use-- no more uncontrollable anchoring to the top of the page (though it still anchors, now it's anchors more seldomly). Makes copying/pasting, page up/down, etc are once again possible in Scaladoc.
### New keyboard shortcuts:
- **Browse Scaladoc with arrow keys.** Search for something in the left side bar, hit the **down arrow**. Use the up/down arrow keys to move to packages/objects/classes/traits, and hit _Enter_ to load the corresponding page in the right panel.
- **Toggle between panes with tab key** Hitting the tab key will toggle between the text filter in the left pane, and the text filter in the right pane. 
- **Up arrow key overrides auto-focus in right pane** When the right pane's text filter is selected (and the input panel annoyingly sticks to the top of the page), pressing the **up arrow** will automatically scroll to the top. Nice when you want to read the API comments.
- **Escape resets filters** (oldie but goodie).

Preview here: http://lampwww.epfl.ch/~hmiller/scaladoc/library/

Regarding review; since I'm responsible for the front-end of Scaladoc, I'm not sure who would review this.

### CODE REVIEW

**Comment by VladUreche** [comment]
Bravooo! +1000
I noticed a small problem: whenever I click a page in the left navigation panel, a new tab is open instead of opening the page in the left frame. What could be causing this?

My browser is Firefox on Ubuntu 12.04. (Chromium works well though...)

**Comment by VladUreche** [comment]
One more crazy idea (not sure it's possible though): Can we also scroll and expand the the class members? It's probably hard to implement, but it would be incredibly nice to have!

**Comment by adriaanm** [comment]
Sweet! Shortcuts ftw! (Can we use the konami code to see the matrix^W the compiler's view of the types?)

**Comment by heathermiller** [comment]
@VladUreche I just fixed the weird issue with the left navigation panel and the new tab. It's the world's stupidest fix-- a two-character change. Will now submit a new pull request. Good news; it'll now work in Firefox.

No idea about IE though-- if anyone receiving this can check how it looks in IE, please do!

**Comment by heathermiller** [comment]
Actually-- take my last comment back. The Firefox issue needs a bit more investigation. As of this moment, the above preview URL is my (currently buggy) test directory. Anyone with IE-- don't experiment with it just yet.

**Comment by dcsobral** [comment]
I think this is better than what we have. However, there things lost, and things I do not understand.
- There isn't any way to navigate through hyperlinks anymore.
- There isn't any way to mouselessly select an object anymore (well, it was pretty hard before, so it isn't quite a loss).
- I hate the up-arrow movement. Home seems to do what up-arrow is now doing just fine, but having up-arrow _not_ be the inverse of down-arrow is very painful. This I'd really like to see reverted.
- Also, there isn't _any_ way at all to mouselessly scroll up and down without clearing the search. I don't see why do this, if ESC clears it.

So, I'd prefer to:
- Remove the clearing of search by arrow and pgup/pgdn.
- Revert the special treatment of up-arrow -- leave that to Home.
- Make side-arrows navigate between links and, possibly, select object/class on the left tab.

**Pull request merged**
