### PR TITLE
Don't warn about auto-application for nullary methods overriding nilary

### PR DESCRIPTION
**Pull request by lrytz**
Let's call

    def f: Int   // nullary
    def f(): Int // nilary

When overriding a nilary method with a nullary one, the compiler
converts the override in Namers and adds the `()` parameter list.

    trait T { def f(): Int }
    class C extends T { def f: Int = 1 } // converted to `def f(): Int`

Calling `(c: C).f` makes the compiler insert `()`, and warn about that
fact under `-Xsource:2.14`.

This PR adds an annotation to `C.f` to remember that the method was
originally nullary. I initially tried with a symbol attachment, but that
doesn't survive pickling, so doesn't work for separate compilation. The
annotation is just a WIP hack, we'd need to hide the secret handshake
better IRL.

The adaptation still leaks though. For example:

    trait T { def f(): Int }
    class A           { def f: Int = 0 }
    class B extends T { def f: Int = 0 }
    (new A).f() // error: Int does not take parameters
    (new B).f() // ok

Maybe, instead of adding more hacks to selectively undo the adaptation,
it would be better to teach the compiler about the fact that `f` may
override `f()`.

### CODE REVIEW

**Comment by lrytz** [comment]
This PR is an alternative to https://github.com/scala/scala/pull/8296, https://github.com/scala/scala/pull/8010. It fixes https://github.com/scala/bug/issues/11657, https://github.com/scala/bug/issues/11639.

**Comment by som-snytt** [comment]
Wow!

What if every distinction we thought was supremely important really doesn't matter much?

**Comment by sjrd** [comment]
> Maybe, instead of adding more hacks to selectively undo the adaptation,
it would be better to teach the compiler about the fact that f may
override f().

If you go down that path, could we extensively discuss it? Because for JS types in Scala.js, whether a `def` is *defined* with `()` or without makes a big difference for runtime semantics. They are not interchangeable.

Currently the fact that overrides inherit the `()` of their overridees is the correct thing to do for Scala.js. If you extend a class or an interface that was correctly written for interop, then you as a user can't get it wrong, because the missing `()` will be added for you.

If however the `()` are not added, and call sites are made more tolerant instead, then you can silently write a non-compliant override, and code will horribly break at run-time.

**Comment by som-snytt** [comment]
I added the rocket emoji because we just watched the end of season four of the 100, where they launch themselves back into space to escape the next apocalyptic wave of radiation on the ground.

sjrd's "code will break horribly at run-time" is a wonderful cliff-hanger. I can't wait for the next episode!

**Comment by lrytz** [comment]
> could we extensively discuss it?

Absolutely!

> whether a `def` is _defined_ with `()` or without makes a big difference for runtime semantics

Could show why / how that is?

> If you extend a class or an interface that was correctly written for interop, then you as a user can't get it wrong, because the missing `()` will be added for you.

Maybe the compiler (or the Scala.js plugin) could identify this situation and either do the adaptation, or warn about it?


> If however the `()` are not added, and call sites are made more tolerant instead

Maybe I'm misunderstanding what you mean by "call sites are made more tolerant"; we're making call sites less tolerant in 2.14, i.e., `def f` cannot be called as `f()`, and `def f()` cannot be called as `f` (except if `f` is defined in Java).

**Comment by lrytz** [comment]
Note that today, the adaptation only happens in one direction.

```scala
trait T {
  def f: Int
  def g(): Int
}
class C extends T {
  def f(): Int = 1  // not adapted
  def g: Int = 2    // adapted to `def g()`
}
```

**Comment by sjrd** [comment]
> > whether a def is defined with () or without makes a big difference for runtime semantics
>
> Could show why / how that is?

In JavaScript, you have field, properties (with getter/setter), and methods. To access a field, you write `x.f`. To access a property, you write `x.p`, and to call a method, you write `x.m()`. But in fact, even for a method, `x.m` is valid and returns a function value. So you really have to know at call site whether you're supposed to write `x.a` or `x.a()`. The target object knows, however, whether `x.a` is a field or a property, and will call a getter or setter where appropriate.

In Scala.js, we chose a long time ago to model this as:
* `val f` and `var f`s represent fields. If you write `x.f` in Scala.js, it translates to `x.f`.
* `def p` and `def p_=(v)` represent properties with getter and optional setter. If you write `x.p` in Scala.js, it translates to `x.p`; and if you call `x.p_=(v)` (typically with the syntactic sugar `x.p = v`), it translates to `x.p = v`.
* `def m()` represents methods. If you write `x.m()` in Scala.js, it translates to `x.m()`.
  * If you write `x.m` in Scala.js, due to adaptation, it also translates to `x.m()`. So if you get the definition right, you can call it the way you like and things will work out.
  * And if you *override* `def m()` with a `def m` (or implement for an abstract one), then the current adaptation will also make sure that you define a method, and not a property (the distinction being critical for callers).

> Maybe I'm misunderstanding what you mean by "call sites are made more tolerant"; we're making call sites less tolerant in 2.14, i.e., def f cannot be called as f(), and def f() cannot be called as f (except if f is defined in Java).

Oops, yes, "call site" was entirely the wrong concept. I meant at *overriding site*. Because if you remove the adaptation of the override, and instead tolerate that `def f` truly overrides `def f()`, then it's a lie for JS classes in Scala.js, because at run-time `def f` will be incompatible with `def f()` (as explained above).

> Maybe the compiler (or the Scala.js plugin) could identify this situation and either do the adaptation, or warn about it?

That would be the bare minimum, yes, but it would have to be an *error* rather than a warning, because the resulting code would be completely broken. That means that (potentially a lot of) existing code would not compile anymore.

**Comment by lrytz** [comment]
> * If you write `x.m` in Scala.js, due to adaptation, it also translates to `x.m()`.

Note that this is deprecated in 2.14 - is this problematic for Scala.js?

> * if you _override_ `def m()` with a `def m` (or implement for an abstract one), then the current adaptation will also make sure that you define a method, and not a property (the distinction being critical for callers).

If you override `def m()` with `def m`, callers have to write `m()` or `m` depending on the static type.

Is it that in the generaded JS, `def m()` and `def m` are represented differently (while in the classfile they are the same)? And then dynamic lookup doesn't work as expected, i.e., a property `m` would not override a method `m()`?

**Comment by sjrd** [comment]
> Is it that in the generaded JS, def m() and def m are represented differently (while in the classfile they are the same)? And then dynamic lookup doesn't work as expected, i.e., a property m would not override a method m()?

Yes, exactly. But only in JS types (so everything that extends `js.Any`, but nothing else).

> Note that this is deprecated in 2.14 - is this problematic for Scala.js?

It could be annoying for people who want to call without `()` side-effect free 0-arg methods in JS libraries (like JVM people want to call side-effect free 0-arg Java methods like that sometimes). But it won't be *problematic* as far as the language semantics and compiler are concerned.

**Comment by lrytz** [comment]
Ultimately this is a language design question. Scala allows overriding a `f()` with `f` and vice-versa, and this doesn't seem to be up for discussion (at least I never saw a discussion around it).

The fact that the current implementation adapts `f` to `f()` very early if it overrides some `f()` is an implementation detail (note that there's no adapatation in the inverse case).

Given that in Scala.js, overriding a JS-defined `f()` with `f` breaks, the Scala.js compiler should handle this situation (either by requiring the empty parameter list, or by inserting it). What happens toady in Scala.js in the inverse case, when overriding a JS-defined `f` with `f()`? Does it break at run-time?

> JVM people want to call side-effect free 0-arg Java methods like that sometimes

There is an exception, the compiler allows calling `f()` as `f` if it's defined in Java. You might want to do the same for JS-defined functions?

**Comment by sjrd** [comment]
> What happens toady in Scala.js in the inverse case, when overriding a JS-defined f with f()? Does it break at run-time?

Hum, looks like it breaks at run-time, yes :( I did not know that was allowed, actually.

Given that, I think the only reasonable option is for the Scala.js to detect those things and flag them as compile errors.

> There is an exception, the compiler allows calling f() as f if it's defined in Java. You might want to do the same for JS-defined functions?

Unfortunately, I cannot do that, because I do not control the type checker nor refchecks. And "JS-defined" functions are Scala-defined as far as scalac is concerned, because their facade types are written in Scala.

**Comment by lrytz** [comment]
> "JS-defined" functions are Scala-defined as far as scalac is concerned, because their facade types are written in Scala.

I see. Is it up to the author of the facade to select `f()` or `f`, or does he have to to the correct choice depending if the underlying JS definition is a method or a property?

**Comment by sjrd** [comment]
They have to do the correct choice depending on whether the underlying JS definition is a method or a property, indeed. In general facade authors have to use the correct form of definitions for everything based on what the JS library does underneath.

**Comment by lrytz** [comment]
For the record, here's where the adaptation was added: https://github.com/scala/scala/commit/b739c4a2ec. It's unclear at this point what the exact reason was ("should fix problems with toString"), but all the downstream consequences of this change are accidental, not intended. For example this inconsistency:

```scala
scala> class C { def name = "C"; override def toString = name }
defined class C

scala> (new C).name(0)
res0: Char = C

scala> (new C).toString(0)
                        ^
       error: no arguments allowed for nullary method toString: ()String
```

**Comment by som-snytt** [comment]
> The fact that the current implementation adapts f to f() very early if it overrides some f() is an implementation detail 

I guess you mean the fact that it is early is the implementation detail. It is specified in 5.1.4 Overriding.

In the last example, `toString` "really is nilary" is no stranger than `class C` "really is nilary". For some reason, it became urgent for `case class C`, maybe because of the signature of `C.apply`.

There is a lint for the "inverse" case, `-Xlint:nullary-override`. It was probably always considered problematic.

**Comment by lrytz** [comment]
> It is specified in 5.1.4 Overriding.

Ah, bummer.. So I'm arguing for a spec change it seems. Luckily I have [Scala 3 on my side](https://scastie.scala-lang.org/ToQRsanlT2qlUDfgkNxRcA).

**Comment by adriaanm** [comment]
See also #7625

**Pull request closed without merging**
