### PR TITLE
Doc: capitalize doesn't handle non-BMP characters

### PR DESCRIPTION
**Pull request by martijnhoekstra**
After a brief discussion on Gitter with @Ichoran, documenting the behaviour is preferable over changing it.

### CODE REVIEW

**Comment by soc** [comment]
If it doesn't do what it advertises, I'd rather just deprecate it.
Without taking a locale argument, capitalization is not well-defined anyway.

**Comment by Ichoran** [comment]
It does what is advertised for almost everyone in almost all cases.  That
there are a couple of corner cases it doesn't catch is not reason to take
the functionality away from everyone.   (Not in a world where you can
randomly index into the middle of a multi-byte character in a string and
get nonsense.) The missing cases should be documented, though.

**Comment by soc** [comment]
I'm not sure how you come to this conclusion. "Capitalization" without specifying a locale is not a well-defined operation.

I disagree on your broken-window stance here. Other things being broken does not excuse having additional, unrelated things being broken.

The implementation fails on basic it's-2016-and-this-shouldn't-be-broken tests.

**Comment by martijnhoekstra** [comment]
Documenting current behaviour seems like a reasonable first step, that neither requires nor hinders further discussion on whether capitalizing without further context is a reasonable thing to support in the stdlib

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
