### PR TITLE
SI-6411 SI-7328 value class fixes for runtime reflection

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
Looks like an improvement.

Is there an interaction between by-name and value class to test for?

**Comment by xeno-by** [comment]
@retronym Nothing special has to be done in that case, because when used in by-name position value classes are always boxed. I have updated the test to ensure that everything keeps working as it should in the future.

**Comment by retronym** [comment]
What about unboxed value classes in the return value? We need to wrap them, right?

**Comment by xeno-by** [comment]
That's what I'm doing right now - fixing https://issues.scala-lang.org/browse/SI-7328

**Comment by xeno-by** [comment]
@retronym I've redone the pull request to be performance-friendly. I also unified methods and constructors, and implemented wrapping/unwrapping on getter/setter boundaries.

**Comment by retronym** [comment]
LGTM, sorry for the slow review.

**Pull request merged**
