### PR TITLE
SI-7532 Fix regression in Java inner classfile reader

### PR DESCRIPTION
**Pull request by retronym**
395e90a modified the detection of top-level classes in
ClassfileParser in two ways:
1. used `Name#containsChar` rather than `toString.indexOf ...` (good!)
2. decoded the name before doing this check (bad!)

That code is actually only run for non-Scala classfiles, whose
names don't need decoding. Attempting to do so converted `R$attr`
to `R@tr`, which no longer contains a '$', and was wrongly treated
as a top level class.

This commit reverts the use of `decodedName`, and inlines the method
to its only call site for clarity.

Review by @paulp and @JamesIry (for 2.10.2-RC2 inclusion)

### CODE REVIEW

**Comment by JamesIry** [comment]
LGTM (I'm hijacking from Paul)

**Comment by paulp** [comment]
I swear I did this in reaction to observing :: returning false for isTopLevel. But when I try to reproduce that I can't, so I will assume I just booched this. Thanks. You could maybe leave more than 7 hours during which I am asleep between pull request and merge though, especially when you're reverting code I wrote.

**Comment by retronym** [comment]
I'll take a second look at this, It would be easy to draw the wrong conclusions from the sea of `vars` that is `ClassfileParser`. But, the tests from 395e90a didn't defend this, so maybe it was a red herring in your original bug chase.

**Comment by retronym** [comment]
I was wrong with my comment about this being "Java only". It's only "not Scala only".

```
scala> (::).toString
scala.collection.immutable.$colon$colon isTopLevel = false, clazz = class ::#11265, poolSym = class ::#11265
```

Also of note:

```
scala.Function1$mcJF$sp isTopLevel = false
```

The code in question:

``` scala
    val isTopLevel = !(currentClass containsChar '$') // Java class name; *don't* try to to use Scala name decoding (SI-7532)
    println(s"$currentClass isTopLevel = $isTopLevel")

    val c = if (isTopLevel) pool.getClassSymbol(nameIdx) else clazz
    if (isTopLevel) {
      if (c != clazz) {
        if ((clazz eq NoSymbol) && (c ne NoSymbol)) clazz = c
        else mismatchError(c)
      }
    }

    addEnclosingTParams(clazz)
    parseInnerClasses() // also sets the isScala / isScalaRaw flags, see r15956
```

Here's the genesis of this `isTopLevel` condition: https://github.com/scala/scala/commit/2ea69162973#L1R355

Falsely thinking that `::` is not top level will:
1. bypass error checking for mis-named class files
2. disable the fallback to the symbol obtained from the constant pool when `clazz eq NoSymbol`

Falsely thinking that `R$attr` is top level will lead to the bug reported here, a spurious error about a misnamed class file.

The most pressing question I have is: when can `clazz` be `NoSymbol`?

/cc @dragos

**Comment by retronym** [comment]
About all I can think to do is:

``` patch
-    val isTopLevel = !(currentClass containsChar '$') // Java class name; *don't* try to to use Scala name decoding (SI-7532)
+    val isDefinitelyTopLevel = !(currentClass containsChar '$')
```

**Comment by retronym** [comment]
BTW, the fallback on `clazz = c` comes from the beloved commit, ["Another massive IDE checkin"](https://github.com/scala/scala/commit/322c98023#L14R332).

**Comment by paulp** [comment]
> The most pressing question I have is: when can clazz be NoSymbol?

I think it's going to be when it goes looking for a class before it has been populated in the pool, i.e. circular references. Such things are not exactly our strongest point anyway, e.g. SI-3809, SI-2464.

**Comment by retronym** [comment]
I also found one case in the test suite. I've elaborated on that here: https://github.com/retronym/scala/commit/282288c03. 

t5303_3 tests a companion-wannabe type alias. In that case, the type alias in the package object delivers the aliased type, `Function1`, when we lookup `getClassSymbol(nameIndex)`. This happens during `parse(Foo.class, object Foo)`.

That doesn't sound like a great idea. But in the my variation, where I bypass this by adding `$` to the name, a crash ensues.

**Comment by paulp** [comment]
There's plenty of other grist for the dollar sign mill at SI-2806, etc. Remember to apply the de-jira-conversion-icator whenever you see 2+ dollar signs, except when they were all there before -- the impossibility of which nicely parallels that of the problem which it is obscuring.

**Pull request merged**
