### PR TITLE
SI-6017 Scaladoc: Fix dangling links on index.html

### PR DESCRIPTION
**Pull request by kzys**
As @heathermiller and @VladUreche commented in #1861, I removed `<a>` and use `<span>` instead when there is no page to link to.

### CODE REVIEW

**Comment by adriaanm** [comment]
needs a rebase

**Comment by kzys** [comment]
Hmm... I'm little bit confused about GitHub. Could you merge f950e25 and 5359c11 easily?

**Comment by heathermiller** [comment]
Hey @kzys looks like you still need a rebase. It's showing some 23 commits and 50 changed files. Are you working off of a branch that you branched off of 2.10.x?

**Comment by VladUreche** [comment]
Afaik the quickest solution is to do this:

```
git remote add trunk https://github.com/scala/scala.git
git checkout trunk/2.10.x -b trunk/2.10.x
git cherry-pick 5359c11
git cherry-pick f950e25 
git cherry-pick 485d815 
git cherry-pick 033b6c1 
git cherry-pick 831bffd 
git rebase -i HEAD~6 
# in the editor: 
#  for the first commit you'll need to replace pick by edit
#  for the rest of your commits, you'll need to replace pick by squash
git commit
# now add a common message for all your commits
git push -f origin jira-6017-v2
```

Maybe @paulp has some scripts for it, he's always got a trick up his sleeve :)

**Comment by paulp** [comment]
```
% git rebase origin/2.10.x
 src/compiler/scala/tools/nsc/doc/model/ModelFactory.scala            | 15 +++++++++------
 src/library/scala/concurrent/impl/ExecutionContextImpl.scala         | 34 ++++++++++++++++++++++++++--------
 src/library/scala/concurrent/impl/Promise.scala                      |  2 +-
 src/reflect/scala/reflect/api/Exprs.scala                            |  2 ++
 src/reflect/scala/reflect/internal/Definitions.scala                 |  2 +-
 src/reflect/scala/reflect/internal/annotations/compileTimeOnly.scala | 31 +++++++++++++++++++++++++++++++
 src/reflect/scala/reflect/macros/compileTimeOnly.scala               | 16 ----------------
 test/files/jvm/future-spec/FutureTests.scala                         | 14 +++++++++++++-
 test/files/neg/t6539/Macro_1.scala                                   |  2 +-
 test/files/neg/t6539/Test_2.scala                                    |  6 ++++++
 test/scaladoc/run/package-object.check                               |  1 +
 test/scaladoc/run/package-object.scala                               |  1 +
 12 files changed, 92 insertions(+), 34 deletions(-)
 create mode 100644 src/reflect/scala/reflect/internal/annotations/compileTimeOnly.scala
 delete mode 100644 src/reflect/scala/reflect/macros/compileTimeOnly.scala
First, rewinding head to replay your work on top of it...
Applying: SI-6017 Generate Scaladoc's index links in Scala side
Applying: SI-6017 Scaladoc: Show all letters without dangling links

% git log origin/2.10.x..
commit 94afd9ae9a0c698b30cfb6d2caf777802b8dc66e (HEAD, pr-2050)
Author: Kato Kazuyoshi <kato.kazuyoshi@gmail.com>
Date:   31 hours ago

    SI-6017 Scaladoc: Show all letters without dangling links

    Use <span> instead of <a href="..."> if there is no page on the letter.

commit a53315818bae28dc7620844192257081330681e9
Author: Kato Kazuyoshi <kato.kazuyoshi@gmail.com>
Date:   4 weeks ago

    SI-6017 Generate Scaladoc's index links in Scala side

    There is no reason to do it in JavaScript.
```

**Comment by VladUreche** [comment]
Thanks @paulp! 
@kzys, please ignore what I wrote in the previous comment and do the rebase as Paul suggested.

**Comment by kzys** [comment]
Thanks. How about this?

**Comment by VladUreche** [comment]
LGTM, thanks Kato!

**Pull request merged**
