### PR TITLE
Improve PartialFunction/Function1 docs

### PR DESCRIPTION
**Pull request by Blaisorblade**
TODO: if this is what we want, all FunctionX should be documented as "_partial_ function of X arguments" like I did for `Function1`.

Prompted by https://groups.google.com/d/msg/scala-language/QuYtWldPNi8/hW2FjM0x96QJ. Apparently https://issues.scala-lang.org/browse/SI-5370's earlier doc fix wasn't enough (EDIT: I misattributed the fix to myself, while I just reported a bug).

A question on the API: I get why isDefinedAt = true still allows for exceptions (changing that would require solving the halting problem, for compiler-generated partial functions), but I don't get why isDefinedAt = false does not require exceptions. The new doc explains this, and I don't assume this could be changed, but I'm still curious about the rationale.

Review by @phaller (for the library) & @heathermiller (for the docs).

### CODE REVIEW

**Comment by Ichoran** [comment]
I do not think this helps matters.  It probably will hurt for everyone except mathematicians and those with graduate-level CS.  And half of them probably won't appreciate it.

The problem is that "partial function" and "total function" are not clear enough in the heads of most people.  When they are clear, everyone should say: but of _course_ you cannot, in a Turing-complete language, guarantee that your function is total!  Why are you even telling me this?

For people who are already less than entirely crisp on the concepts, using the phrase "partial function" in Function is more likely to confuse than help.  ("Wait, huh?  Function is a partial function, and PartialFunction is also a partial function, but you use Function everywhere and PartialFunction only in places where you want a partial function but Function IS a partial function so...?!?!  Wait, maybe this is because of that other partial function application thing???")

Instead, I would explain clearly what Function1 does/guarantees, with at most a brief parenthetical note to set the terminology straight.  Likewise with PartialFunction.

Allowing `exists(x => f.isDefinedAt(x) != Try{ f(x) }.isFailure)` is for efficiency.  If isDefinedAt is going to be used as a guard anyway, you needn't necessarily recompute the guard.

**Comment by Blaisorblade** [comment]
Thanks for the comments; I believe you're right on beginners.
Right now things are confusing even for graduate CS - after all, you could
have a TotalFunction1, even though the compiler can't check an
implementation is correct and it would be somewhat inconvenient to use.

On efficiency: isn't the fast-path applyOrElse anyway?
And removing the redundant isDefinedAt call should be a job for a better

## optimizer.

Paolo Giarrusso

**Comment by Ichoran** [comment]
Scala doesn't have checked exceptions, and the JVM doesn't insist on checking, and you can't solve the Halting problem anyway, so it would just be convention that it was total.  I would hope that a CS grad wouldn't need more than a brief hint to realize this.

And anyway, the convention _is_ typically that Function1 is total, and we do exhaustiveness checking to help make it so.  I don't think stressing the necessary partiality of any potentially Turing-machine-equivalent computation is addressing the most essential features.

**Comment by Blaisorblade** [comment]
> Instead, I would explain clearly what Function1 does/guarantees, with at most a brief parenthetical note to set the terminology straight.

I still agree on that, but less on the rest.

> Scala doesn't have checked exceptions, and the JVM doesn't insist on checking, and you can't solve the Halting problem anyway, so it would just be convention that it was total. I would hope that a CS grad wouldn't need more than a brief hint to realize this.

I'm a CS PhD student, I see your reasoning, I don't share your assumptions: why do you expect that all contracts are enforceable by the compiler? It'd be cool, yes, because non-compiler-enforced constraints will unfortunately get broken without extra attention, and there are ways to achieve that (e.g. dependently-typed languages, and many others), but Scala just does not allow that. The Java standard library specifies lots of pre-/postconditions through their JavaDocs (which aren't compiler-enforced). The Scala API has often similar restrictions, they are just not documented.

I concede `Function1` is a bit special just because Scalac creates them, but that wouldn't apply to a `TotalFunction`.

> I don't think stressing the necessary partiality of any potentially Turing-machine-equivalent computation is addressing the most essential features.

The problem is that `PartialFunction` is a bad naming choice. You have both `Function1` and `PartialFunction`: of course (one would think) they won't both represent partial functions! In fact, in Scala they do.

**Comment by Ichoran** [comment]
Well, let's think about to what extent `Function1` is expected to be total.  First, we agree that it's impossible to enforce.  Let's see, how do we create a partial function `Function1` anyway, without non-terminating (Halting problem stuff)?

```
scala> val f: (Option[Int] => Int) = { case Some(x) => x }
<console>:13: warning: match may not be exhaustive.
It would fail on the following input: None
       val f: (Option[Int] => Int) = { case Some(x) => x }
                                     ^
f: Option[Int] => Int = <function1>
```

Doesn't that look to you like an attempt at helping `Function1` be total?

**Comment by Blaisorblade** [comment]
Yes, but since it does not address other causes of non-termination, one can ask whether there's a point. Is `Function1` total? "Kind-of" is a worse answer than "yes" and "no". In particular, a client cannot take advantage of the "kind-of" totality of `Function1` to implement any behavior, except if it wants to "kind-of" adhere to the specification.

Moreover, the whole `PartialFunction` specification turns out to be overly complex and badly designed (at least according to [semantic design](http://lukepalmer.wordpress.com/2008/07/18/semantic-design/)). This is just one reason causing the multiple misunderstandings. I suspect that might explain the lack of PartialFunction analogues in many other functional languages.

If you try to make types have a simple meaning, some interesting points in the design space are:
- `Function1` is a partial function — the standard concept.
- `KnownDomainFunction1` is a partial function that allows testing whether an input is in the domain or not. In a total language, the compiler could generate that from an incomplete pattern matching. In Scala, only a programmer can check by hand that a function respect such an interface. The set of values of `KnownDomainFunction1[A, B]` is isomorphic to the total function space from `A` to `Option[B]`, but the performance characteristics might be different.
- `NonExhaustivePatternMatch` represent a pattern match which the compiler cannot prove to be exhaustive, and allows testing whether an input succeeds or fails the pattern match. This specification is much closer to `PartialFunction`, except that `PartialFunction` tries to be more general, without much success. The specification allows `exists(x => f.isDefinedAt(x) != Try{ f(x) }.isFailure)` for "efficiency", but `NonExhaustivePatternMatch` cannot take advantage of this extra efficiency (because the pattern match must be repeated)*, while clients are forced to call both `isDefinedAt` and `apply`. `applyOrElse` avoids the problem altogether if you override it, but the default implementation suffers this slowdown as well.
- Or... ahem... does `PartialFunction.apply` skip guards?

`PartialFunction` is a badly named mixture of all that, forcing you to do more defensive programming than you'd expect. It is convenient neither for implementors nor for clients.

Concretely: I've seen, written and upvoted on StackOverflow tons of times an isomorphism between `PartialFunction[A, B]` and `A => Option[B]` and related utilities, and I've never even noticed the conditions under which the code I wrote actually worked, let alone documented them.

However, this is increasingly becoming the wrong place for this discussion. I might still try to write good documentation for `PartialFunction`, but I'd rather redesign it in some fork.

**Comment by Blaisorblade** [comment]
Just noticed: `PartialFunction` might maybe be salvageable by redefining "domain" to mean something else — "inputs where no `MatchError` is thrown" (though even this specification is probably wrong, since a PartialFunction might still do a partial pattern match).

**Comment by Ichoran** [comment]
A proposed redesign would be very interesting.  I do not like how inheritance is used here, but have been unable to think of alternatives that perform well, don't require more effort than is warranted, and can be made to work with SAMs (for Function1).

**Comment by Blaisorblade** [comment]
Agreed. I suspect we have slightly different goals though, performance-wise — I'm not willing to compromise design cleanliness to address lack of the optimizations, though I do respect your choice of "performance today" over "maybe tomorrow" (you're writing programs today).

Specifically, what I'd do here:

> Allowing exists(x => f.isDefinedAt(x) != Try{ f(x) }.isFailure) is for efficiency. If isDefinedAt is going to be used as a guard anyway, you needn't necessarily recompute the guard.

is to mark `isDefinedAt` as `@pure` in the interface and let the optimizer remove duplicated calls. (`applyOrElse` seems to make that moot as well, though).

**Pull request closed without merging**
