### PR TITLE
more precise isMacroApplication check

### PR DESCRIPTION
**Pull request by xeno-by**
Replaces the `symbol.isMacro` check with `symbol.isTermMacro`.
Doesn’t make any difference to trunk but helps a lot with macro annotations.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
@retronym @adriaanm @gkossakowski Could we have this fix in M7, so that it gets into a new starr? This might come very handy for macro-based lifters for case classes, which currently can't be defined in scala-reflect.jar because of this bug.

**Comment by xeno-by** [comment]
Oops, my bad. The comment above was directed at a different pull request (https://github.com/scala/scala/pull/3137).

**Comment by retronym** [comment]
LGTM

**Pull request merged**
