### PR TITLE
Remove Manifest and friends 

### PR DESCRIPTION
**Pull request by smarter**
It's been deprecated for 5 years, it's time to say good bye :wave: .

This PR cannot be merged until we have a STARR that contains https://github.com/scala/scala/pull/6742

### CODE REVIEW

**Comment by mkeskells** [comment]
you will mess up all of the benchmarks @retronym looks after by deleting the code to make scalac compiling faster 😆

**Comment by xeno-by** [comment]
Manifests are part of the language specification: https://www.scala-lang.org/files/archive/spec/2.12/07-implicits.html#manifests. I suggest that their removal goes through the SIP process.

**Comment by dwijnand** [comment]
> It's been deprecated for 5 years, it's time to say good bye 👋 .

When were they deprecated? Last I knew (6 years ago) they were _un_-deprecated in https://github.com/scala/scala/pull/1455 (for 2.10.0).

**Comment by smarter** [comment]
> Manifests are part of the language specification: https://www.scala-lang.org/files/archive/spec/2.12/07-implicits.html#manifests. I suggest that their removal goes through the SIP process.

No objection from me.

> When were they deprecated? Last I knew (6 years ago) they were un-deprecated in #1455 (for 2.10.0).

Indeed. I guess I assumed they were, and in practice they pretty much are.

**Comment by dwijnand** [comment]
> I guess I assumed they were, and in practice they pretty much are.

They're pretty much in use, though, as well.. I don't think we can just drop them in 2.13.0-M5.

**Comment by retronym** [comment]
The problem with removing Manifests is that the replacement (`TypeTag`) is extremely heavyweight and only provided in an experimental Scala module (scala-reflect).

**Comment by lrytz** [comment]
We also need to look at this in the context of Scala 3 - what's going to happen to scala.reflect? We should make that plan first before taking any actions.

**Comment by lrytz** [comment]
Closing, as this needs discussion / decission outside the PR queue.

**Comment by smarter** [comment]
> Closing, as this needs discussion / decission outside the PR queue.

Can we define one place for such discussion? Otherwise it's likely to spread randomly.

**Comment by lrytz** [comment]
I really think the bigger underlying topic is scala.reflect vs Scala 3 - are there any past discussions on that topic?

**Comment by dwijnand** [comment]
@odersky mentions in https://contributors.scala-lang.org/t/what-kinds-of-macros-should-scala-3-support/1850/14:

> The future Scala 3 macro design is intended to replace the existing def macros and the `scala.reflect` infrastructure.

But I don't think creating a new thread in https://contributors.scala-lang.org/ that's specifically about `Manifest` would wrong. We can then link it to or from other locations.

**Comment by smarter** [comment]
I think it's pretty clear that scala.reflect if it exists in Scala 3 won't be recognizable since the current API exposes implementation details.

**Comment by dwijnand** [comment]
Bootstrapped the thread: https://contributors.scala-lang.org/t/scala-reflect-and-scala-3/1967

**Pull request closed without merging**
