### PR TITLE
show developer guidelines on opening pull request

### PR DESCRIPTION
**Pull request by adriaanm**
Improvements and typo fixes to CONTRIBUTING.md by @heathermiller
as well as feedback from @retronym.

### CODE REVIEW

**Comment by heathermiller** [comment]
Ack- oops, I was sitting here thinking that if I opened up a pull request (rather than saying line by line, typo here, reword this, reword that), and if I made my pull request to adriaanm/scala on same branch that you made your pull request from to scala/scala... That you would be able to just accept the pull request, and that it would be like adding a commit to the PR. So then there would be two commits. I didn't intend to create any more work for you! (Thought I was helping). Sorry if I made you make an additional pull for a bunch of not-so-important typo fixes and rewording!

**Comment by adriaanm** [comment]
@heathermiller, no worries at all! It took me 5 minutes or so. I had kind of forgotten to create branches for this in the first place. Your approach would have worked under that assumption.

It was easy enough though: i started with a `hub checkout https://github.com/adriaanm/scala/pull/3` and then cherry-picked my way to laziness :-)

once done in master, I scripted it:

```
git checkout guidelines-2.10.x
grh scala/2.10.x
git cherry-pick 48e8d1d7f7
git push -f origin
git checkout guidelines-2.9.x
grh scala/2.9.x
git cherry-pick 48e8d1d7f7
git push -f origin
```

I also have a `newpull` bash function to quickly open a new pull request from the command line. Laziness ftw.

``` bash
function newpull() { 
  curr_branch=$(git symbolic-ref -q HEAD)
  curr_branch=${curr_branch##refs/heads/}
  curr_branch=${curr_branch:-HEAD}

  open https://github.com/adriaanm/scala/pull/new/scala:$1...${2:-$curr_branch} 
}
```

usage: `newpull $targetBranch $localBranch`

**Comment by heathermiller** [comment]
Nice- didn't know I could make a PR from the command line. I should really look at `hub`. Thanks for the pointers :)

**Comment by som-snytt** [comment]
For the record (the github record), when I saw @heathermiller 's PR, I thought, what a neat way to contribute, i.e. what a neat workflow.  Scala school, or if I may, la scuola della Scala, is always in session.  We innocent bystanders thank you all for sharing the knowledge.  Sorry to sound maudlin.

**Comment by adriaanm** [comment]
Figurati.

**Pull request merged**
