### PR TITLE
Cleanup of scalap.

### PR DESCRIPTION
**Pull request by folone**
These things seem not to be used anywhere. People who need monads/applicatives/functors use scalaz nowadays. What is the reason for having them in scalap?

### CODE REVIEW

**Comment by folone** [comment]
Review by @soc (I was [told](https://twitter.com/larsr_h/status/360160550052835330), he is an expert on this kinds of things).

**Comment by soc** [comment]
You get a big WTF from me ... and also a LGTM. :-)

I guess history needs to be rewritten ... it turns out that we shipped that stuff since 2009.

**Comment by folone** [comment]
Yeah, you never know what `grep` can dig out from the darkest corners of scala repository :smile:

**Comment by paulp** [comment]
Looks great to me.

**Comment by som-snytt** [comment]
The precedent was that if you wanted to copy/paste a fork of something, you'd have to disguise it in subtle ways.  Then they'd never find it!

If you needed an HList, you could scarf some shapeless, but you couldn't call it that; it would have to be something like shipshapeless.  kitteh's plagiarism filter isn't smart enough to catch it.

I think I just saw that Miguel was trying to smuggle in some asm. You can't do that.  You'd have to rename it to chasm or some other asm pun.  Is punasm a word?

**Comment by paulp** [comment]
> some other asm pun

https://github.com/paulp/awesome

**Comment by som-snytt** [comment]
The day I looked at it, and I guess it was just a day because I was busy working on SIP-00006, I was already in the spirit of it, judging from the local build settings.

```
apm@halyard /cygdrive/m/apm/projects/awesome
$ lt
total 7
drwxr-xr-x+ 1 apm Administrators    0 Mar 30  2012 src
drwxrwxrwx+ 1 apm Administrators    0 Apr  2  2012 target
-rw-r--r--  1 apm Administrators  172 Apr  3  2012 README
drwxr-xr-x+ 1 apm Administrators    0 Apr  3  2012 bin
-rwxr-xr-x  1 apm Administrators  584 Apr  3  2012 run
drwxr-xr-x+ 1 apm Administrators    0 Apr  3  2012 runner
-rwxr-xr-x  1 apm Administrators  305 Apr  3  2012 exec
drwxr-xr-x+ 1 apm Administrators 4096 Jul 27 04:08 project

apm@halyard /cygdrive/m/apm/projects/awesome
$ head project/Build.scala 
import sbt._
import Keys._

object Awesome extends Build {
  lazy val root = Project("sarcasm", file("."), settings = Defaults.defaultSettings ++ awesomeSettings)

  def awesomeSettings = Seq(
    name := "plasma", // paul's lightweight asm accommodation
    organization := "com.github.som-snytt",
    version := "0.5.3-SNAPSHOT",

apm@halyard /cygdrive/m/apm/projects/awesome
$ 
```

**Comment by paulp** [comment]
If I'd thought of "sarcasm", awesome would never have been (still)born. I like plasma too. Hmm, I just thought of "miasma", I might like that best of all.

**Comment by som-snytt** [comment]
For completeness, today it occurred to me, asmatic, but I'm not sure how to use it in a sentence. Sounds like a killer dev app, though.

**Comment by gkossakowski** [comment]
Oh wow. That's a find of a month @folone!

Thanks a lot.

**Pull request merged**
