### PR TITLE
SI-6942 more efficient CNF conversion in patmat analysis

### PR DESCRIPTION
**Pull request by adriaanm**
Avoid blowing the stack/the analysis budget by more eagerly translating
the propositions that model matches to CNF.
First building a large proposition that represents the match,
and then converting to CNF tends to blow the stack.
Luckily, it's easy to convert to CNF as we go.

removeVarEq may throw an AnalysisBudget.Exception

review by @retronym

### CODE REVIEW

**Comment by retronym** [comment]
Otherwise looks good to me superficially and on account of the test. It would take me a while to get my head around the algorithm again to offer anything more insightful.

**Comment by adriaanm** [comment]
Right, should've added that flag. I'll also try to do a better job of explaining the change while I'm making --amends.

The essence of the patch is that `CNF(P1 /\ ... /\ PN) == CNF(P1) ++ CNF(...) ++ CNF(PN)`.

Normalizing a conjunction of propositions
     yields the same formula as 
concatenating the normalized conjuncts.

CNF conversion is expensive for large propositions,
so we push it down into the conjunction and
then concatenate the resulting arrays of clauses (which is cheap).

(CNF converts a free-form proposition into an `Array[Set[Lit]]`, where:
- the Array's elements are /\'ed together;
- and the Set's elements are \/'ed;
- a Lit is a possibly negated variable.)

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@adriaanm: good call to use buffer for concatenating those formulas. You wen't down from O(n^2) to O(n) algorithm.

**Comment by retronym** [comment]
@adriaanm Does this change impair our ability to bail out of the analysis when we exceed the analysis budget? I ask this with SI-6726 in mind.

Also, running Hubert's test case from that ticket with N=2000, I see that 50% of the time is spent in `Sym#equals`. I was going to try Might it be worthwhile to hash cons it, did you try anything like that already?

The calls to `equals` are all coming from `f.filterNot(_.contains(unitLit)).map(_ - negated)` in `dropUnit`.

**Comment by adriaanm** [comment]
I missed this. Sorry. I know you have #1994 for hash consing. I don't think this PR causes trouble for our budget monitoring as the rewrite (which may now cause these exceptions) has moved into the relevant try/catch.

**Pull request merged**
