### PR TITLE
Clean up SerializationStabilityTest

### PR DESCRIPTION
**Pull request by szeiger**
Some classes should be stable in 2.13.x regardless of -Xcheckinit
because they now use serialization proxies. Others are no longer
relevant.

### CODE REVIEW

**Comment by dwijnand** [comment]
Shall we wait until the changes in #8778 have been merged into 2.13.x first?

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/8778 was merged to 2.13.x in https://github.com/scala/scala/pull/8786 (with `-s ours`, as the change doesn't apply, TreeMap serializes differently in 2.13.x).

@szeiger sorry for being ignorant about the details, but it looks like a few more TODOs were nuked at https://github.com/scala/scala/pull/8778/files#diff-f902cea1239346244c50f9198db286f5 - these changes don't apply to 2.13.x?

**Comment by dwijnand** [comment]
There's the 

> Reinstate serialization compatibility tests for this and other
collections that were temporarily disabled due to an interation
with -Xcheckinit. Now, we simply skip the test when we detect
that the build is using that option.

part of that PR that would be good to keep, with updated serialisation references.

**Comment by szeiger** [comment]
@lrytz I hadn't seen #8778 until after created this PR. The changes here are the ones that are compatible with checkinit in 2.13. We can disable the test for checkinit builds like in 2.12 to enable the remaining ones, too.

**Comment by dwijnand** [comment]
@lrytz want to take care of landing this?  Or maybe it doesn't need to anymore (I didn't look in depth).

**Comment by lrytz** [comment]
We should take another go at merging the changes here, and including the parts of https://github.com/scala/scala/pull/8778 that apply to 2.13.x.

**Pull request merged**
