### PR TITLE
SI-4733 - fsc no longer creates a single temp directory for all users.

### PR DESCRIPTION
**Pull request by melloc**
fsc previously created a single temporary directory called
"scala-devel". This is an issue, since the directory belongs to whoever
created the directory. Depending on the user's umask, this directory may
only be writable for the creator. This causes problems for any other
users who then try to use fsc or invoke fsc indirectly.

Other programs usually solve this issue by creating a separate directory
for each user, either by appending the username to a base directory name
or creating a new direcotory with a random name with a program like
"mktemp". This commit changes CompileSocket to use the first method.

Fixes SI-4733
backport to 2.10.x

### CODE REVIEW

**Comment by paulp** [comment]
Well, normally we'd want a test, but seeing as I just had to disable the only test for fsc because it caused spurious build failures, the smart money says LGTM. LGTM.

**Comment by paulp** [comment]
Except, belatedly, can you please target 2.10.x. It is a lot less work when the commit goes into the older branch and is merged into master than vice versa.

**Comment by melloc** [comment]
I saw the part about testing under the information on commits, but I wasn't sure what would be suitable here.

And sure! Should I just submit another pull request? Or is there a way to change this one?

**Comment by melloc** [comment]
Alright, I just made a pull request for 2.10.x.

**Pull request closed without merging**
