### PR TITLE
kills introduceTopLevel

### PR DESCRIPTION
**Pull request by xeno-by**
As we've figured out from the practice, introduceTopLevel is seductively
useful but unfortunately not robust, potentially bringing compilation
order problems.

Therefore, as discussed, I'm removing it from the public macro API.
Alternatives are either: 1) delving into internals, or
2) using macro paradise and experimenting with macro annotations:
http://docs.scala-lang.org/overviews/macros/annotations.html.

### CODE REVIEW

**Comment by xeno-by** [comment]
This PR's predecessor has already got an LGTM. Waiting for the kitty to confirm that a rebase didn't break anything.

**Comment by xeno-by** [comment]
It would be very useful if we could get this in 2.11.0-M5. That's a significant API change, and we should give people more time to prepare themselves for the final release.

**Comment by adriaanm** [comment]
Agreed.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
