### PR TITLE
SI-7637 Repl edit command

### PR DESCRIPTION
**Pull request by som-snytt**
This PR still has usability issues for console editors, in that you can't use them, but gedit WFM.  Also working on a unit test, since jline is turned off for tests; it might entail fattening the "common history interface" just to enable testing; otherwise, the history support is jline-specific.  Comments welcome; assume there is a generous latency period before this will receive attention.

Open an editor with historical text.

:edit id will use the complete text of the defining line, including
a multiline expression or template definition.  The id must be a term
or type in scope, in particular, defined in the current session.

:edit line will use the specified line(s) from history, as a line
number (123), range (123-130), offset (123+7), remaining (123-) or
previous (-10 for last ten lines).

The env var EDITOR is used to specify an editor to invoke.

If EDITOR is not set or if :line command is used, the selected text
is added to the end of history.

Text is still added to history one line at a time (cf SI-1067).

### CODE REVIEW

**Comment by adriaanm** [comment]
I'm no replxpert, but LGTM.

**Comment by som-snytt** [comment]
@adriaanm I'll follow up with usability enhancements, secure in the knowledge that no one will use the feature or even become aware of its existence.  Unless Paul is lurking on jira.  That wouldn't be the first "Paul is dead" rumour to be debunked.  Do you know that if you `save` a REPL session and then `replay` it backward, you wind up with a REPL that converges on the result "turn me on, dead man."

**Comment by som-snytt** [comment]
@adriaanm I just used the feature for the first time, someone was confused by a dumb little sample on stackoverflow, not even worth the time to explain, but then I realized I could edit my REPL history!  I totally got a burst of adrenaline!

I suppose until now people just edit a file and $colon load it.

http://stackoverflow.com/a/17628368/1296806

**Comment by kiritsuku** [comment]
@som-snytt Som, not sure if you read the issue queue. If not take a look at this bug: https://issues.scala-lang.org/browse/SI-7682

**Comment by som-snytt** [comment]
@sschaef Thanks! I'll submit a fix soonish.  The big bug is console editors don't work; haven't looked at it yet. I'll address this at the same time, under your issue.

**Comment by som-snytt** [comment]
@sschaef Sorry, I see from the PR text that EDITOR not set is supposed to be OK. More mea culpas.  Or mea culpae.

But if EDITOR happens to be set to gedit, it's pretty useful. :)

**Comment by kiritsuku** [comment]
I set EDITOR to subl which is even more useful ;) Just noted that something doesn't work if EDITOR is not set.

**Comment by som-snytt** [comment]
Usually my ed is vi, but one xterm has gedit.  Woe is me if I'm not in the gedit window when I try :ed.

**Comment by kiritsuku** [comment]
Btw, I just stumbled upon two further things about your REPL changes, I posted them on scala-internals. If you want to take a look...

**Pull request merged**
