### PR TITLE
Merge/2.10.3 to 2.10.x

### PR DESCRIPTION
**Pull request by retronym**
Review by @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM

**Comment by retronym** [comment]
What is the build up to?

image

image

**Comment by retronym** [comment]
Well, it shook its way out out of it. But it was doing apparently nothing for 30m or longer.

**Comment by adriaanm** [comment]
30 min, that's nothing! Here's a report of 6 hours of finger twiddling: https://issues.jenkins-ci.org/browse/JENKINS-19208

**Pull request merged**
