### PR TITLE
minor corrections in Macros.scala

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by adriaanm** [comment]
what does this commit do more precisely? it may seem minor to you, but even a one letter change can have a major impact

**Comment by adriaanm** [comment]
Since this commit is going to need a rewrite to explain why the change to the classpath is needed (and why it's minor),
I'm closing it. Please submit a new request (on 2.10.x if it's critical or on master if not).

**Comment by xeno-by** [comment]
This just fixes a typo - didn't think that it needs an explanation.

**Comment by adriaanm** [comment]
```
-      val classpath = toURLs(settings.XmacroFallbackClasspath.value
+      val classpath = toURLs(settings.XmacroPrimaryClasspath.value)
```

ok, so what's the fallback classpath and what's the primary one?
why should it be the primary here and not the fallback one

**Comment by xeno-by** [comment]
Primary should be here, because a test a few lines up checks whether
primary != "". Hence usage of fallback here is just a typo.

Primary and fallback classpaths were designed for situations when library
classpath are not enough (e.g. for bootstrapping libraries that don't get
onto tool classpaths). Originally I planned to use them to bootstrap
scala-library, however, there's always a starr/locker on a tool classpath,
so we don't need special treatment of this case. After I realized that, I
decided to keep advanced classpath switches, because others might not be as
lucky as we are.

On 11 July 2012 16:17, Adriaan Moors <
reply@reply.github.com

**Comment by adriaanm** [comment]
ok great, please resubmit with this explanation in the commit message

**Comment by xeno-by** [comment]
Superceded by https://github.com/scala/scala/pull/888

**Pull request closed without merging**
