### PR TITLE
Fixes binary repo push for new typesafe repo layouts.

### PR DESCRIPTION
**Pull request by jsuereth**
This adds a new/fixed push.jar and adapts the binary-repo-lib script to use different URLs
for pulling than pushing.

Review by @lrytz + use by @xeno-by  / @paulp

Note to self: Cherry pick this against 2.9.x when able.

### CODE REVIEW

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by lrytz** [comment]
hey josh, i'm really swamped in other stuff currently and then on vacation until october 6, so i can't make reviews for a few days... :( sorry

**Comment by jsuereth** [comment]
No problem!   Review by @xeno-by / @paulp

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
I manage to push a jar with this, so it LGTM without much of the L part.

**Comment by xeno-by** [comment]
Same as Paul - I succeeded with pushing a new starr. However at first `pull-binary-libs.sh` failed me, and I had to download `push.jar` manually before I could do `push-binary-libs.sh`.

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
Just to check: can we still pull starrs when we checkout old versions of the repo? (ie, from http://typesafe.artifactoryonline.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap)

**Comment by jsuereth** [comment]
Yes.   It appears the issue is with syncing the two.   I'll revert using
both and this will start passing.

**Comment by jsuereth** [comment]
PLS REBUILD ALL

Ok, gave up on using the fast server.  It's hosed, talking to JFrog about that.

**Pull request merged**
