### PR TITLE
In the spirit of https://github.com/scala/scala/pull/2285

### PR DESCRIPTION
**Pull request by huitseeker**
Changed unrecognized doc comments from Doc to C style, silencing scaladoc some
more

This has been obtained automatically by processing scaladoc log output, then checked manually
(for e.g. comments tha tshould be recognized as scaladoc)

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

**Comment by som-snytt** [comment]
I had suggested at some point that I would seek to tune the warning.

https://github.com/scala/scala/pull/2396

I did notice that you didn't align the comment spacing on multiline comments.  I don't suggest doing so, unless changing the comment style is actually worth doing (and therefore worth doing right).

For the record, after some initial hesitation and uncertainty, I really like the scaladoc double-star convention, with its extra space, compared to javaland.  It looks to me like a flag or banner, on a pole and flying to the right.

**Comment by adriaanm** [comment]
For future commits, please limit the commit subject to 55 chars and phrase it in the active mode:
For example: ``Change unrecognized scaladoc comments to C-style''

This and more is explained in https://github.com/scala/scala/blob/master/CONTRIBUTING.md

**Comment by som-snytt** [comment]
Github needs a box to enter a subtitle.  SI-1234 Type infer uses implicits: Or, how I learned to stop worrying and love higher-kinded types.

#2396 doesn't silence two warnings, in GenICode and Mixin. I'm not persuaded that this beautiful doc should be ignored.  But that's a feature question.

**Comment by huitseeker** [comment]
Well, since this is tool-generated, it's _very_ easy to improve on.

**Pull request closed without merging**
