### PR TITLE
SI-4767 Inline @inline final trait methods

### PR DESCRIPTION
**Pull request by VladUreche**
A trait consists of an interface and an implementation class. From a
JVM perspective, a class that extends a trait will actually implement
the interface and unless it overrides the member, will get a forwarder
to the implementation class:

for:

```
  trait Foo { @inline final def foo(x: Int) = println(x) }
  class Baz extends Foo
```

Baz is compled down to:

```
  class Baz extends Object with Foo {
   @inline final def foo(x: Int): Unit = Foo$class.foo(FooImpl.this, x)
   ...
  }
```

Now, say we have:

```
  def bar(y: Foo) = y.foo(7)
```

The type of `Foo` is `interface Foo`. Thus there's no way for the
inliner to load the bytecode for foo. The first part of this patch
addresses this problem, by transforming the call to `y.foo(7)` to
`Foo$class.foo(y, 7)` if the foo method is final and @inline marked.

The second part is actually inlining the static call to `Foo$class.foo`.
Now, the trick is that the inliner actually expects the calls it
inlines to have an instance on which they're run. I relaxed the inline
conditions to include static calls and changed the inliner to generate
correct code for static calls. (the VerifyError was caused by this)

The third part was adapting the ICodeReader to be able to pick up the
code from implementation classes. I think the ICodeReader needs a real
maintainer, I was only after getting the test cases to pass, but there
are still some failures visible with -Ydebug -Ylog:inliner.

Finally, added a couple of tests using Greg's instrumented partest
addon, and it's awesome!

Thanks to @magarciaEPFL, @lrytz and @xeno-by for their help!

Mandatory review by @paulp if we're going to get this in 2.10.

### CODE REVIEW

**Comment by VladUreche** [comment]
A short explanation why the forwarder is generated in `Mixin` instead of loading the implementation code in the `Inliner` or patching the code in `ICodeReader` -- in short, the answer is that working with traits and especially with traits with self-types requires casts. Thus there's a lot of ceremony to avoid getting `VerifyErrors` when simply inlining. On the other hand, in `Mixin`, we can access the corresponding implementation symbols in a clean way and run the typer to correctly generate the necessary casts, thus making it easier to generate the code.

[This commit](https://github.com/VladUreche/scala/commit/410c4250e51cf9353e877bd09a1d106f5dcad67b) shows how much code is necessary in GenICode to get all the types right without calling the typer.

**Comment by paulp** [comment]
This looks great so far, will look more closely.  It is interesting to notice that after inlining, the "Foo" isn't used at all.  There's probably some optimization to be had in those cases.  Anyway, will look later tonight.

**Comment by paulp** [comment]
See my email to scala-internals; it looks like Predef.assert is no longer being inlined.

**Comment by VladUreche** [comment]
In the light of the List method copy-pasting idea, I'm happy to redo this pull request against master as soon as I get a stable version.

**Pull request closed without merging**
