### PR TITLE
SI-7757 disallow constructor annotations on traits

### PR DESCRIPTION
**Pull request by densh**
Previously it was possible to define constructor annotations on traits
with really weird side-effects (parser lost the body of the trait). Now
constructor annotations on traits will cause appropriate syntax errors.

### CODE REVIEW

**Comment by retronym** [comment]
LGTM. Good catch.

**Comment by xeno-by** [comment]
Needs a test where the annotation comes on the next line.

**Comment by densh** [comment]
Why and what exactly is it going to test ?

**Comment by xeno-by** [comment]
Scala sometimes allows newlines mid-definition and sometimes not. E.g. this is valid:

```
class C
(val x: Int)
```

What will it test? Correct behavior in such cases.

**Comment by adriaanm** [comment]
We can ignore the partest failures.

**Pull request merged**
