### PR TITLE
Use travis-wait-enhanced

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Tested with  https://github.com/scala/scala/pull/8437 and the missing errors showed up.

It generates a bit of noise.

```
# starting 1909 tests in run
Note: test execution will be non-parallel under -Dpartest.exec.in.process
........................................................................
........................................................................
....................................................travis-wait-enhanced INF Still running at Wed, 25 Sep 2019 10:35:22 UTC...
....................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
........................................................................
.................travis-wait-enhanced INF Still running at Wed, 25 Sep 2019 10:44:22 UTC...
.......................................................
........................................................................
........................................................................
```

Maybe `travis-wait-enhanced` could be improved to print its messages only if there's no output from the command.

I'd be fine merging this as-is.

**Review by retronym — APPROVED** [review]

**Comment by SethTisue** [comment]
@lrytz recent builds at https://travis-ci.org/scala/scala/builds are failing, it isn't obvious to me what the problem is

**Comment by SethTisue** [comment]
(and publishing of mergely builds is affected as well, so e.g. 2.13.2-bin-238a16a didn't publish)

**Comment by lrytz** [comment]
Hmm, no idea... I don't see any failure, but the build just seems to stop after the `removeExistingBuilds` step, before the first invocation of `travis-wait-enhanced`. We should probably revert this PR.

**Comment by SethTisue** [comment]
> We should probably revert this PR.

#8453

**Pull request merged**
