### PR TITLE
further polishing of reflection

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @paulp

**Comment by xeno-by** [comment]
"Exposes Symbol.sourceModule": also review by @odersky

**Comment by paulp** [comment]
This all looks like improvement to me, except that I think hiding the existence of "modules" vs. "module classes" was the right thing to do, and that it could be done but would require labor to do so.  In a similar vein, if it were me I'd do everything possible to avoid the need to expose deSkolemize.

**Comment by paulp** [comment]
So that's LGTM if unclear.

**Comment by xeno-by** [comment]
@paulp Also please review the late commit that introduces `isVal` and `isVar`.

**Comment by xeno-by** [comment]
Cancelled these jobs manually to accommodate for an additional commit - it's not the kitteh's fault.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Still needs @odersky review.

**Comment by xeno-by** [comment]
Wrote Martin an email.

**Comment by xeno-by** [comment]
@paulp What's your take on https://github.com/scalamacros/kepler/commit/23cf705ba64641a3ba45e84984702cf97cdd0ccf. It's a small additional commit that snuck in-between kitteh reports, so it might have slipped past you.

**Comment by paulp** [comment]
I heartily endorse methods like "isVal" and "isVar", sorely needed islands of usefulness and self-explanatoriness.  This all looks good to me except for "deSkolemize", but that can wait.  LGTM.

**Pull request merged**
