### PR TITLE
Value class Depth.

### PR DESCRIPTION
**Pull request by paulp**
It's the obvious translation from a raw Int into a value class.

It wasn't that long ago one could find a signature like this:

```
  def merge(tps: List[Type], variance: Int, depth: Int): Type
```

Do you feel lucky, method caller? Well, do ya?

Anyway, now it is:

```
  def merge(tps: List[Type], variance: Variance, depth: Depth): Type
```

Forget for a moment the fact that you'd probably rather not pass variance
for depth and depth for variance and look at the type signatures:

```
  (List[Type], Variance, Depth) => Type
  (List[Type], Int, Int) => Type
```

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
LGTM. Thanks for making at least these commits materialize on the other side of the wormhole.

**Comment by retronym** [comment]
I doubt that it matters in this case, but in general we should be aware that this sort of refactoring prevents specialization.

**Comment by paulp** [comment]
@retronym True, but it seems like the sort of thing which either specialization improves to handle or it wasn't that important that it be specialized.

**Pull request merged**
