### PR TITLE
SI-8955 Fix hanging fork-join pool via parallel collections

### PR DESCRIPTION
**Pull request by retronym**
A recent change [1] to Scala's default fork join thread pool caused
intermittent deadlocks. This is only visible in the development series
of Scala, 2.12.0-SNAPSHOT.

We changed our thread factory to place a hard limit the number of
threads created (equal to the desired parallelism.)

I have extracted a test case [2] that uses jsr166e directly, rather
than using Scala's parallel collections and abstractions on top of FJ.

In the comments of the bug, Viktor suggests this was too aggressive
and instead we ought to increase the limit to parallelism + 256
(with a system property override.)

He explained:

> The number 256 is going to be the default for the max threads for
> FJP in Java9 (down from 32k) so this change will harmonize the
> settings while making it possible to override from the outside.
> 
> The cause of the deadlock is twofold:
> 
> 1) The test uses ExecutionContext.global, which is not designed
>    for typical ForkJoin workloads since it has async = true
>    (FIFO instead of LIFO)
> 2) And we capped the default max number of threads to be created
>    when doing managed blocking from 32k to number of cores
>    (a tad too aggressive it seems)

Through testing, I found that for this example I could trigger the
hang with:

```
parallelismLevel | maxThreads
-----------------------------
               2 | <= 4
               4 | <= 9
               8 | <= 11
              16 | <= 15
```

I have emailed concurrency-interest [3] to help analyse the problem
further, but in the interest of avoiding hangs in the
scalacheck/parallel-collections test, I'm implementing Viktor's
suggestion in the interim.

[1] https://github.com/scala/scala/pull/4042
[2] https://gist.github.com/retronym/2e14cdab6d5612562d95
[3] http://markmail.org/message/czphdyjxpkixeztv

### CODE REVIEW

**Comment by retronym** [comment]
Review by @viktorklang

**Comment by retronym** [comment]
BUILDLOG?

**Comment by viktorklang** [comment]
This is not the patch I proposed. maxExtraThreads should be in addition to parallelism, as we don't want the pool to grow beyond parallelism unless there is managed blocking.

**Comment by retronym** [comment]
Doesn't `numThreads + getInt("scala.concurrent.context.maxExtraThreads", "256")` satisfy this requirement?

**Comment by retronym** [comment]
Oh, I think I see my error.

**Comment by retronym** [comment]
How's this?

**Comment by viktorklang** [comment]
:+1: @retronym, great work!

**Comment by retronym** [comment]
LGTM echo, for the bots sake.

**Comment by viktorklang** [comment]
LGTM ;)

**Comment by fommil** [comment]
btw, this means that we are now seeing several hundred threads on an app that previously had a handful and the extra overhead of OS thread scheduling is impacting performance.

At least there is a workaround: `"-Dscala.concurrent.context.maxExtraThreads=0"`

**Comment by alexandru** [comment]
@fommil  The default fork-join pool available in `global` uses that maximum as a limit for threads created when `blocking` operations happen (via [BlockContext](https://www.scala-lang.org/api/current/scala/concurrent/BlockContext.html)).

Without that you would end up with deadlocks, because blocking operations *can wait on Runnables*  that have nowhere left to execute. Quite the contrary, people have been bitten by that maximum limit, with apps freezing because `global` has a maximum limit.

The workaround is not to set that environment variable to zero, because you'll break other people's code that depends on `global` behaving just the way it is. The workaround is to configure your own thread pool.

**Comment by fommil** [comment]
@alexandru from a position that all blocking operations are already assigned their own thread pool, my workaround is the correct if one must interact with legacy CPU bound `Future` code instead of using `IO`.

**Comment by alexandru** [comment]
This problem has nothing to do with `Future` or `IO`.

If you're having hundreds of threads, then you've got blocking operations running on `global`.

**Comment by fommil** [comment]
@alexandru the thread factory does not check if something is blocking or not blocking, it just assigns threads when asked, unless the logic is implemented in some corner of the code that is not obvious. That can happen if non-blocking CPU-heavy work is scheduled all at once, while work is ongoing, creating "cores + 256" `Thread`s. I think this is what I was seeing, but it's hard to confirm since threads are created and destroyed pretty quickly and I'm trying to eyeball how many threads are alive at once from a memory snapshot that I cannot easily rerun. Certainly I have hundreds of threads alive over a very short period of time where I would not have expected any threads to have reason to be killed. None of that work is blocking, to the best of my knowledge.

If I were to create my own execution context for CPU bound work, as you suggest, it would look much like `DefaultThreadFactory`, except it is `private` and I cannot access it, so it would be a lot of duplicated code. Therefore the easiest thing for me to do is to disable the unnecessary headroom with `"-Dscala.concurrent.context.maxExtraThreads=0"` and ensure that nobody puts blocking operations in the global context, which would be a performance bug with or without deadlock (in fact, the manifestation of blocking as deadlock is good because it turns performance bugs into functional bugs, easier to spot).

Re: why I mentioned `IO`, you suggested that my workaround was not the full picture and offered an alternative workaround. So I let you glimpse something of the full picture, in which `Future` is a performance problem in my app and moving to `IO` is the solution. That digression is not relevant to this particular ticket, and you have no way of knowing all the details, but I feel I must correct your strong assertion that my problem is "nothing to do with Future or IO" when it **is** and you don't have all the facts. I'd rather not digress any further in that direction, if that's ok with you.

Back to the topic of the ticket, my proposed workaround seems to have cleared things up, although it's hard to say anything definitive about these sorts of micro optimisations. Certainly it was a surprise to see "256 threads" appear out of nowhere. I would much rather have "99 red balloons".

**Comment by edmundnoble** [comment]
The fact is that when the fork-join pool asks for a new thread, the `ThreadFactory` *has no way of knowing why it's asking*. It could be, and often is the case that the fork-join pool is asking for new threads because *all of the queues are full and it'd like to have available workers*, even if the `parallelism` number has been exceeded by the number of threads. And the `ThreadFactory`'s `maxThreads` is still used to limit *those* threads.

So increasing the number of threads to `256 + numCpus` *could* have an impact on the number of threads in the pool even without blocking, it *could* cause massive context-switching for CPU-bound code, and even removing all of your blocking won't fix that (even though blocking does make it worse).

EDIT: @fommil tried a demo of this, and the FJP may not be requesting many extra threads beyond parallelism. Not sure about this. It may be the case that limited use of `blocking` is ruining the performance of the other threads in the pool.

EDIT 2: It looks like if you have any code that uses `blocking` it ruins the performance of non-blocking tasks which are submitted after the blocking ones are, if you're out of threads. That's basically just https://github.com/scala/bug/issues/10810, though, so that's not new.

**Comment by fommil** [comment]
I am more and more convinced that I was just counting dead threads from a very difficult to profile application in a difficult to reach environment. However, the experience led me into reading this code. Now I feel exactly like I did that time I went to a sausage factory.

**Comment by SethTisue** [comment]
> Now I feel exactly like I did that time I went to a sausage factory

I'm hungry, too.

**Pull request merged**
