### PR TITLE
Reflection API: Module to Object refactoring

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
@xeno-by This first commit is pretty much an updated version of the commit you reviewed here: https://github.com/scala/scala/pull/1517

Could you and probably @adriaanm comment whether any additional deprecated `module` items should  be added?

I tried to address @paulp's concerns regarding the naming in the second commit: https://github.com/scala/scala/pull/1065

I have looked into possible name clashes in the source code and the major one I identified is `ObjectClass`. I made the decision here that our concept (`object` as a singleton/companion) should have higher priority than Java's (`java.lang.Object`), considering that we have already renamed/aliased it to `AnyRef` in Scala anyway.

I renamed `ObjectClass` to `JavaLangObjectClass`, with the result that `object` in the reflection/compiler API has now only a single, well-defined meaning: it refers to the constructs with the keyword of the same name. Having the consistency of `ClassDef`, `ObjectDef`, `DefDef`, `ValDef` is really great, imho.

The question about renaming the old pattern matcher's `isObject` method to `isInstance` I brought up in the old PR has solved itself, because it has been removed.

A potential issue with naming similarities between `Module` and `Modifier` (there was a lot of stuff called `m`, `mod`, `mods`) has now also been solved with the new name.

Opinions?

**Comment by soc** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
I added some further deprecations to make SBT happy (and for better compatibility).

**Comment by paulp** [comment]
A patch like this has to be written with more effort put into not breaking things. Many of these methods have been around for years. That they are not officially supported does not mean we should go around breaking everything which relies upon them.

I count 67 public or protected methods which appear on the "-" side of this diff. Some of the list may be spurious - I only spot-checked it - but it's easy to see that plenty of them aren't. Most of these methods must be given a deprecated forwarder before we can consider the patch. And methods are the easiest part of providing compatibility; to the extent possible, everything else should be given shims as well. To save us another go-around, please take a look at every type, class, object, and val which underwent a name change and if possible add a deprecated one with the original name.

```
def ArrayModule
def ArrayModule_apply
def ArrayModule_genericApply
def ArrayModule_overloadedApply
def ListModule
def ModuleUsingCompanionClassDefaultArgsErrror
def NilModule
def NoneModule
def SomeModule
def addModuleInstanceField
def caseModule
def caseModuleApplyMeth
def caseModuleDef
def caseModuleUnapplyMeth
def companionModule
def companionModule0
def companionModuleDef
def companionModuleOf
def connectModuleToClass
def createModuleClassSymbol
def createModuleSymbol
def deriveModuleDef
def enterClassAndModule
def enterModule
def enterModuleDef
def enterModuleSymbol
def findOrCreateModuleVar
def getMemberModule
def getModuleByName
def getModuleIfDefined
def getRequiredModule
def inferModulePattern
def initAndEnterClassAndModule
def initClassAndModule
def initModule
def isModuleFlag
def isModuleOrModuleClass
def isModuleRoot
def isModuleVar
def isStaticModule
def isTopLevelModule
def mainModuleName
def moduleBody
def moduleClass
def moduleClassFlags
def moduleClassTypeCompleter
def moduleDef
def moduleFileName
def moduleMessage
def moduleName
def moduleQual
def moduleSuffix
def moduleVarName
def modules
def needsModuleSuffix
def newLinkedModule
def newModule
def newModuleAndClassSymbol
def newModuleClass
def newModuleClassSymbol
def newModuleSymbol
def newModuleVarSymbol
def openPackageModule
def setModuleClass
def stripModuleSuffix
def testInnerModule
def typedModuleDef
```

**Comment by soc** [comment]
@paulp Thanks for the review, I'll add deprecated forwarders to the compiler parts, too.

**Comment by soc** [comment]
I think I found and fixed all of them now, except a few which where methods nested inside (private) methods, like `findOrCreateModuleVar`, `mainObjectName`, `objectFileName`. Let me know if you want deprecated members for them, too.

**Comment by soc** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
@paulp Would it make sense to mark all deprecated methods as `@inline`?

**Comment by gkossakowski** [comment]
@soc: no, unless they call a method that is marked `@inline` _and_ takes closure as argument. Regular methods are best inlined by JIT in almost all cases.

**Comment by soc** [comment]
My assumption was that it could reduce the amount of binary dependencies on these deprecated methods, but considering the current binary compatibility policy, that won't change much I guess.

**Comment by paulp** [comment]
I think we're converging onto something we can run with, but there are at least a few names which still need improvement.

Can you apply the following renamings:
- [ ] isObjectClass  becomes  isSourceObjectImpl
  (the same applies to every method which once referred to a "module class")
- [ ] isObject becomes isSourceObject
  (the same applies to every method which once referred to a "module")
- [ ] isImplClass  becomes  isTraitImpl
  (the same applies to every method which once referred to an "impl class")

After giving the naming matter our full attention for an unreasonably long time, that's the best we came up with. Given the paucity of appealing options, I think they are good names. If you think you have better ones, we're all ears, but otherwise I believe this routes names into meanings about as well as the landscape will allow.

**Comment by soc** [comment]
I think that sounds reasonable, except the `isSourceObject` because it breaks the symmetry with `isClass` and isn't in line with the actual keyword. What's the reasoning here?

**Comment by paulp** [comment]
> What's the reasoning here?

1) isObject is unacceptable.
2) we need a name.

I'm not clear on how "isSourceObject" isn't in line with the keyword "object". The symmetry with "isClass" is not real anyway; isClass includes a whole lot of things which were never declared with the word "class", but isSourceObject will (almost) only include things which were declared with the word "object". The only ones I can think of offhand which aren't declared "object" are those derived from "case class" declarations, where object is implied.

As I said, if you have a better name, we are all ears.

**Comment by soc** [comment]
Why is `isObject` unacceptable? It's the most simple, straightforward name which actually matches the language construct.
We are incredibly close to only having a single word and definition for each of `object`, `instance` and (in the future) `module`. Why not cross the finishing line?

`isSourceObject` feels like a unnecessary complication for users and is potentially confusing, because users will wonder which additional `object`-related thing is out there which lead to choosing a non-straightforward name. If I read `isSourceObject`, I would immediately wonder which `object`s the `source` part in excluding and which additional `is???Object` methods I'm missing.

If we would complicate the API over minor details, `isClass` would be even less correct than `isObject`, as you mention. But still, we have `isClass` and everyone seems to be happy with it.

**Comment by gkossakowski** [comment]
@soc: because there's more than one concept behind word `object`. With `isObject` call you might be lead to think that you are asking if symbol represents `java.lang.Object`. I'd definitively think so if I saw a method like that. We cannot afford to introduce confusion of that kind.

**Comment by soc** [comment]
There is or should only be a single definition of what an `object` should be.

Scala made that decision a long time ago by sticking with `isInstanceOf` and `asInstanceOf` (instead of `isObjectOf`, `asObjectOf`), as well as `Any` and `AnyRef` (instead of `Object`), and naming `object` “object”.

`java.lang.Object` is a mere implementation detail of the backend. The user doesn't need to know anything about it.
I really think that the argument of “other languages messed it up completely” should not cause us to come up with a worse solution than necessary.
Additionally, I addressed that in my second commit by making `java.lang.Object` more explicit. It's now called `JavaLangObjectClass` instead of `ObjectClass`. I checked and double-checked the code and I didn't find any remaining issues in the reflection/compiler API which could allow people to confuse `object` with `java.lang.Object`.
Apart from that, there is nothing which could clash with `object`. Please report it if you find anything still missing here.

Look at all the languages which use “instance” and “object” for the same thing as well as calling their top type “Object”. It's a horrible, confusing mess.
Scala clears up a lot of confusion in that regard by naming it `AnyRef`. Calling `object` “object” would be one of the last missing pieces here.
We don't need to make up a new, completely unused and unknown term for it. Especially not if we have to give up on the appropriate name for a first-class concept in Scala to a third-class implementation detail of the compiler dealing with a completely different language.

Let's not confuse users, we really don't need a Scala version of “instance” vs. “object”.

**Comment by paulp** [comment]
I'm never going to agree to isObject, if that simplifies matters at all. We are open to a better name, and that is not it.

**Comment by soc** [comment]
I would have promised that if we looked back at it in half a year, we would all laugh about the idea of not calling `object`s “object” consistently.

> I'm never going to agree to isObject

But ok, no idea then. Introducing a different yet-another-name doesn't really improve on the current situation of having yet-another-name.

**Comment by paulp** [comment]
I'm not sure how you can display any surprise about this. Everyone has been abundantly clear on this point - you can refresh your memory via [this thread](https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/vEFtAdiybyk).

That you "would have promised" you were certain to overcome unqualified opposition from martin and myself suggests your objectivity is compromised.

**Comment by soc** [comment]
I'm not surprised. I tried to counter unqualified opposition with actual working code. There is always the possibility that implicit assumptions about how X can be confusing/foreign/ugly/... can be changed when X is put into context.

That doesn't mean that I'm not objective when I predict that in retrospective, this would have been a complete no-brainer.

**Pull request closed without merging**
