### PR TITLE
SI-5751 cleans up toolboxes for the release

### PR DESCRIPTION
**Pull request by xeno-by**
Removes the `freeTypes` parameters on `typeCheckExpr` and `runExpr`,
since we now have public `substituteTypes` on both trees and types.

Also implements long-awaited `inferImplicitValue` and `inferImplicitView`
(thanks to Miles Sabin for nudging me!)

### CODE REVIEW

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
I tried to give you a review, but this is a bit beyond my knowledge.  DO you have an intended reviewer?  I"m always jumpy to get improvements like this in quickly.

**Comment by xeno-by** [comment]
Only Martin and I know about toolboxes. 

However the changes I made were simple. First, I synchronized toolbox and macro typechecking facilities (i.e. exposed `inferImplicit` in toolbox API). Second, I factored out some common logic, so that @paulp's copypaste-o-meter doesn't explode.

**Comment by xeno-by** [comment]
review by @odersky and/or tomorrow's reflection meeting

**Comment by paulp** [comment]
Good to know all the whistling from those pressure gauges has some effect!

**Comment by odersky** [comment]
LGTM

**Pull request merged**
