### PR TITLE
SI-6017 Scaladoc's Index should be case-sensitive

### PR DESCRIPTION
**Pull request by kzys**
In the alphabetical index page (index-$letter.html), the entries are not case-sensitive. For example, "STAR" and "Star" are listed under "STAR".

(Cherry-picked from #1861)

### CODE REVIEW

**Comment by JamesIry** [comment]
@heathermiller you want to review this one or pass the baton to somebody else?

Also, last built a long time ago, PLS REBUILD ALL

**Comment by JamesIry** [comment]
ping @VladUreche Need some help moving this 25 day old PR forward.

**Comment by heathermiller** [comment]
I think that this one was already LGTM'ed in #1861 

Here:

> Btw, those comments above pertain to the first of your two commits, c18984b. I'd just like to open the floor up to discussion about how to handle the index given that we plan on eventually getting rid of it anyway.
> 
> As far as the second commit goes, 50735ab, LGTM!
> 
> Thanks Kato!

**Comment by heathermiller** [comment]
Admittedly, the discussion got kind of full of noise, and the LGTM was never carried over-- sorry!

**Comment by JamesIry** [comment]
No problem. Merging.

**Comment by adriaanm** [comment]
We require every commit in a PR to pass the test suite. This is an example where that wasn't the case.
In the future, please squash commits when necessary.

**Comment by JamesIry** [comment]
I'll look for that in the future before merging.

**Pull request merged**
