### PR TITLE
SI-9488 - adds the same default toString format to Scala Futures as 2…

### PR DESCRIPTION
**Pull request by viktorklang**
….12.x

Includes tests to verify the toString representations.

### CODE REVIEW

**Comment by viktorklang** [comment]
@retronym Could you have a look? (https://issues.scala-lang.org/browse/SI-9488)

**Comment by retronym** [comment]
LGTM

Thanks!

**Comment by lrytz** [comment]
IDE failure due to https://github.com/scala/scala-dev/issues/104

**Comment by viktorklang** [comment]
Thanks Lukas!

**Comment by lrytz** [comment]
btw, since i went trough the exercise of understanding the binary compatibility impact, here's why i think it's safe. adding a concrete method to a trait requires re-compiling all sublcasses, here's an what happens otherwise:

```
➜ cat A.scala
trait A {
  override def toString = "hjai"
}
➜ cat B.scala
class C extends A
object Test extends App {
  println((new C).toString)
}
➜ scalac A.scala B.scala
➜ scala Test
hjai
➜ rm A*.class
➜ cat A1.scala
trait A {
  //override def toString = "hjai"
}
➜ scalac A1.scala
➜ scala Test
java.lang.ClassNotFoundException: A$class
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
```

`trait Promise[T]` is `private[concurrent]` and its subtypes are
- either also private (and being recompiled as part of the same codebase)
-  `class DefaultPromise` is a class, so the mix-in is generated

so it looks safe.

**Comment by viktorklang** [comment]
@lrytz yes, exactly. That's why I put the code in that trait and not the Future-trait itself :)

**Pull request merged**
