### PR TITLE
Add missing @serialversionuid on collections

### PR DESCRIPTION
**Pull request by regadas**
Hi 👋 

I recently stumbled upon https://github.com/scala/bug/issues/5046 while trying to run some scala jobs on Flink. I see that this made it to 2.13 but Flink still runs 2.11/2.12 and per @SethTisue [comment](https://github.com/scala/bug/issues/5046#issuecomment-662011066) I backported some of the changes.

Also, per @lrytz https://github.com/scala/collection-strawman/issues/418 i thought I could set the new `@SerialVersionUID` to `2L` and keep the already set ones as is.

Let me know what you think! Thanks!

### CODE REVIEW

**Comment by regadas** [comment]
Hi @SethTisue and @lrytz not sure who to ping. Any thoughts? Thanks!

**Review by NthPortal — COMMENTED** [review]
I believe the UIDs should be `3L` not `2L`, as collections are not compatible across Scala versions.

Other than that, LGTM!

**Comment by lrytz** [comment]
> the UIDs should be `3L` not `2L`

Note that this PR targets 2.12.x

----

I *think* we remain serialization compatible between minor releases, the test [t8549.scala](https://github.com/scala/scala/blob/2.12.x/test/files/run/t8549.scala) ([SerializationStabilityTest.scala](https://github.com/scala/scala/blob/2.13.x/test/junit/scala/SerializationStabilityTest.scala) in 2.13.x) checks that (at least to some degree).

Java's default serialization always includes the serial version UID. If not specified explicitly (using an annotation in Scala, a field in Java), the value is calculated based on the class structure. When the UID doesn't match on deserialization, an `InvalidClassException` is thrown.

Therefore I don't think we can just set the serial version UID to 2 (or 3) for classes that currently don't have an annotation, as it will break serialization compatibility.

What we can do however is make the calculated UID explicit and put it into an annotation. The `serialver` command line tool displays calculated UIDs:

```
$> serialver -classpath $(cs fetch -p org.scala-lang:scala-library:2.11.12) 'scala.collection.immutable.BitSet$BitSet2'
scala.collection.immutable.BitSet$BitSet2:    private static final long serialVersionUID = 5802956648923438352L;
```

**Comment by lrytz** [comment]
Let me add that adding an explicit `@SerialVersionUID` is very much recommended, because the one that's calculated automatically is sensitive to changes that don't actually affect serialization compatibility, such as adding a public method. Ideally this should come with a test that checks the stability of the serialized form.

See https://github.com/scala/scala-dev/issues/237.

**Comment by NthPortal** [comment]
> Note that this PR targets 2.12.x

gah, I always miss that. sorry!

**Comment by SethTisue** [comment]
@regadas interested in continuing with this?

**Comment by regadas** [comment]
Hi @SethTisue yeah sorry for the delay! I was on vacation recently and I was still catching up! I'll have a look at the comments! Thx for the poke!

**Comment by SethTisue** [comment]
@regadas closing for inactivity, but we can reopen anytime

**Comment by mallman** [comment]
I'm confused. Is this going to be fixed in 2.12? I'm running into this problem with Spark 3.0.1 on Scala 2.12. Spark 3.0.1 seems to bundle 2.12.10, which is not compatible with 2.12.12 due to this issue. I believe the incompatibility was introduced by https://github.com/scala/scala/commit/b8226e1b135b7c12565ab78923fee12f8db93178.

**Comment by SethTisue** [comment]
@mallman since we haven't heard from @regadas in a while, you (or another contributor) are free to submit a new PR on the same theme

**Comment by mallman** [comment]
I don't know how to fix this. Revert the commit?

**Comment by SethTisue** [comment]
> I don't know how to fix this.

see @lrytz's https://github.com/scala/scala/pull/9166#issuecomment-688206155 — followup questions welcome

**Comment by mallman** [comment]
Let's make sure we're on the same page. Is this serialization issue a bug?

**Comment by SethTisue** [comment]
yes, it is https://github.com/scala/bug/issues/5046, which was fixed for 2.13 but not for 2.12

**Comment by regadas** [comment]
Hi @SethTisue Sorry for this, tbh i completely forgot to follow up on this! Let me revive this this week as I have some time now /cc @mallman

**Comment by mallman** [comment]
I'm going to stick with 2.12.10 for now. I don't have the time to work on a PR for this.

**Comment by mallman** [comment]
> Hi @SethTisue Sorry for this, tbh i completely forgot to follow up on this! Let me revive this this week as I have some time now /cc @mallman

Thank you @regadas.

**Comment by regadas** [comment]
@SethTisue Thanks for poking me on this!

@lrytz Thank you for the review and +1 on keeping serialisation compat. That makes total sense to me!

Let me know if I missed anything!

**Review by lrytz — APPROVED** [review]
Thank you!

**Comment by lrytz** [comment]
@retronym up to you if this should be in 2.12.13 or not. This PR sets the `@SerialVersionUID`s to the values that the classes have in 2.12.12. I took a quick look, and there are two cases where the vm-computed UID changed between 2.12.12 and 2.12.x:
  - https://github.com/scala/scala/pull/9192 changed the UID for `scala.collection.immutable.HashMap$HashMap1`
  - https://github.com/scala/scala/pull/9131 changed the UID for `scala.collection.mutable.PriorityQueue$ResizableArrayAccess`

If we merge this after 2.12.13, we should update these two UIDs to their 2.12.13 value.

**Comment by SethTisue** [comment]
Jason agrees we should hold this until 2.12.14.

**Review by dwijnand — CHANGES_REQUESTED** [review]
> If we merge this after 2.12.13, we should update these two UIDs to their 2.12.13 value.

2.13.13 is now out, so once we've done the above we can merge this.

**Comment by mallman** [comment]
> If we merge this after 2.12.13, we should update these two UIDs to their 2.12.13 value.

Sorry, maybe I misunderstand. To be clear, will 2.12.14 be fully serialization-compatible with 2.12.10?

**Comment by lrytz** [comment]
> will 2.12.14 be fully serialization-compatible with 2.12.10?

I don't think so, there are classes without `@SerialVersionUID` that changed between 2.12.10 and 2.12.14, so instances serialized in 2.12.10 cannot be de-serialized in 2.12.14. De-serialization will fail because the (calculated) `SerialVersionUID` is different.

The best we can do is to add `@SerialVersionUID` annotations that correspond to the calculated value of the last release, which is what this PR does (currently, this PR sets the values of 2.12.12). However, there are two cases where the calculated value changes between 2.12.12 and 2.12.13, so we need to update this PR to use the 2.12.13 values.

**Comment by dwijnand** [comment]
An example of how to get the SerialVersionUID: https://github.com/scala/scala/pull/8778#discussion_r386187358.

**Comment by regadas** [comment]
Hello 👋 I can update this to reflect the recent 2.12.13 release. /cc @lrytz @dwijnand

**Comment by mallman** [comment]
> The best we can do is to add @SerialVersionUID annotations that correspond to the calculated value of the last release, which is what this PR does (currently, this PR sets the values of 2.12.12). However, there are two cases where the calculated value changes between 2.12.12 and 2.12.13, so we need to update this PR to use the 2.12.13 values.

Let me give some more background around my query. Spark 3.0.1 ships with Scala 2.12.10. When I try to run a Spark job with Scala 2.12.12 I encounter a serialization failure:

```
java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; local class incompatible: stream classdesc serialVersionUID = 3456489343829468865, local class serialVersionUID = 1028182004549731694
```

From a practical perspective, I'm hoping to see Spark 3.0.1 (+) become compatible with maintenance releases of Scala 2.12 moving forward, so we are not stuck with Scala 2.12.10. I know that the OP referenced Flink compatibility issues as well. Is that a shared goal here, and is it achievable?

**Comment by SethTisue** [comment]
(MiMa part needs rebase because of #9436)

**Comment by lrytz** [comment]
@mallman sorry for my late reply!

We probably could set the explicit `SerialVersionUID`s in this PR to the values that were valid in 2.12.10, but that would be quite an arbitrary choice (current Spark is using it, but other projects might be on a different version). So I believe that the best way forward is to use the values of our latest release (2.12.13). Once there's a spark release built with 2.12.13 out, a `WrappedArray$ofRef` serialized on a newer minor Scala releases (2.12.13+) will work.

Does that sound OK?

@regadas do you have time to rebase this to fix the merge conflicts, and to update the annotations to the 2.12.13 values?

**Comment by mallman** [comment]
> @mallman sorry for my late reply!
> 
> We probably could set the explicit `SerialVersionUID`s in this PR to the values that were valid in 2.12.10, but that would be quite an arbitrary choice (current Spark is using it, but other projects might be on a different version). So I believe that the best way forward is to use the values of our latest release (2.12.13). Once there's a spark release built with 2.12.13 out, a `WrappedArray$ofRef` serialized on a newer minor Scala releases (2.12.13+) will work.
> 
> Does that sound OK?
> 
> @regadas do you have time to rebase this to fix the merge conflicts, and to update the annotations to the 2.12.13 values?

Hi @lrytz. Your perspective makes sense—let's not break things that were built against 2.12.12 or 2.12.13.

I'm not sure if the Spark team is aware of this issue. I didn't find anything from performing a cursory search of their issue tracker.

Their current master pom.xml still lists Scala 2.12.10, and Spark 3.1.1 is at rc2 at this point. I will try to raise an issue and submit a PR to upgrade to Spark to Scala 2.12.13, but I think it's unlikely it will be merged in time for Spark 3.1.1.

Thank you.

**Comment by smarter** [comment]
>  I will try to raise an issue and submit a PR to upgrade to Spark to Scala 2.12.13

That upgrade was previously tried and reverted due to a bug: https://github.com/apache/spark/pull/31223#issuecomment-768066319 (the fix for that bug will be in 2.12.14).

**Comment by mallman** [comment]
> > I will try to raise an issue and submit a PR to upgrade to Spark to Scala 2.12.13
> 
> That upgrade was previously tried and reverted due to a bug: [apache/spark#31223 (comment)](https://github.com/apache/spark/pull/31223#issuecomment-768066319) (the fix for that bug will be in 2.12.14).

Thank you for pointing that out.

**Comment by regadas** [comment]
@lrytz I'll spend some time on this today.

**Comment by regadas** [comment]
@lrytz I think I addressed everything let me know If I missed smth.

**Review by lrytz — APPROVED** [review]
Thank you @regadas!

**Pull request merged**
