### PR TITLE
Made worksheet output wrap around after custimizable # of output columns

### PR DESCRIPTION
**Pull request by odersky**
Review @dragos

### CODE REVIEW

**Comment by dragos** [comment]
LGTM

**Comment by odersky** [comment]
Review by @dotta.

**Comment by odersky** [comment]
PLS REBUILD ALL

**Comment by dotta** [comment]
LGTM

**Comment by jsuereth** [comment]
PLS REBUILD pr-scala-testsuite-linux-opt KTHX kitteh

**Pull request merged**
