### PR TITLE
[backport] SI-6428 / SI-7022 Value class with bounds

### PR DESCRIPTION
**Pull request by retronym**
Review by @paulp. There was one merge conflict, but it was straight forward to resolve.

### CODE REVIEW

**Comment by paulp** [comment]
Looks good to me.

**Comment by paulp** [comment]
Thanks for the backport.

**Comment by JamesIry** [comment]
@retronym needs fixup, "cannot be automatically merged"

**Comment by adriaanm** [comment]
Started jenkins job pr-scala-testsuite-linux-opt at https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/2587

**Pull request merged**
