### PR TITLE
[SI-9454] Add isAlive method into sys.process.Process trait

### PR DESCRIPTION
**Pull request by slothspot**
review @SethTisue.
proposed patch for https://issues.scala-lang.org/browse/SI-9454

### CODE REVIEW

**Comment by SethTisue** [comment]
thanks for the PR. saw your tweets too. returning from a US holiday, swamped for now, will look before too long.

**Comment by SethTisue** [comment]
I did some manual testing and this seems to work fine.

but this comment in Process.scala should be removed:

``` text
*  Presently, one cannot poll the `Process` to see if it has finished.
```

**Comment by slothspot** [comment]
@SethTisue Updated and rebased

**Comment by SethTisue** [comment]
@Ichoran can you take a quick look?

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
