### PR TITLE
introduces Mirror.typeOf

### PR DESCRIPTION
**Pull request by xeno-by**
I just realized that our tag-based shortcuts were incomplete, because
they only work with root mirrors (doing just u.typeTag[T].tpe means that
the type is going to be resolved in u.rootMirror because that's the default).

This commit fixes this oversight. I'm hoping for 2.11.0-RC3, but also feel
free to reschedule to 2.12.0-M1 if it becomes clear that RC3 isn't happening.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
Ping all. If we're having an RC4 anyway, this small strictly incremental change might be a good candidate.

**Comment by xeno-by** [comment]
Hey @retronym, what about this one for RC4? It doesn't change any existing APIs and does something that we'll have to wait for 2.12.0 to introduce.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
