### PR TITLE
[ SI-7514 ] Introduce Source.fromClassPath(resource) method

### PR DESCRIPTION
**Pull request by jdevelop**
Returns Source from named classpath resource
Simplifies

 val src = io.Source.fromInputStream(classOf[ClassInst].getResourceAsStream("/name"))

to

 val src = io.Source.fromClassPath("/name")

### CODE REVIEW

**Comment by SethTisue** [comment]
I like it, but this would need to target 2.12, not 2.11

**Comment by jdevelop** [comment]
@SethTisue do I need to do something about it? Thanks!

**Comment by SethTisue** [comment]
GitHub doesn't allow retargeting an existing PR to a new branch, so a new PR is needed

**Comment by jdevelop** [comment]
@SethTisue ok, thanks! Done. 

https://github.com/scala/scala/pull/4561

**Pull request closed without merging**
