### PR TITLE
Fixed typo in ProcessBuilder scaladoc.

### PR DESCRIPTION
**Pull request by secwall**
ProcessBuilder creation sample code did not complie due to an error
in import statement.

### CODE REVIEW

**Comment by adriaanm** [comment]
jenkins job pr-scala-testsuite-linux-opt: successful -- manually verified

**Comment by adriaanm** [comment]
jenkins job pr-rangepos: successful -- manually verified

**Comment by paulp** [comment]
@secwall Although we can probably let it slide on a commit of this size, can you please sign the [CLA](http://www.typesafe.com/contribute/cla)?

**Comment by paulp** [comment]
Slid.

**Pull request merged**
