### PR TITLE
SI-2807 Resurrect and refine the promiscuous catch warning.

### PR DESCRIPTION
**Pull request by retronym**
The previous incarnation didn't survive 4fb3473.

This version can be cleared by using a typed pattern: `catch { case _: Throwable => }`.

This is motivated by the recent appearance of such a catch in `util.Try`, and by battle
scars left by one too many processes bravely but stupidly catching and logging OutOfMemoryErrors.

I would really like to skip the -Y status and promote this to the default armory of warnings.

Review by @paulp

### CODE REVIEW

**Comment by odersky** [comment]
I agree this would be a good idea.

**Comment by retronym** [comment]
Here are the warnings generated for the Scala distribution itself: https://gist.github.com/2950132

**Comment by jsuereth** [comment]
I'm for adding it to the default warnings. And the _man_ (@odersky) said it's a good idea.   Would you like to do so before we merge this commit?

**Comment by adriaanm** [comment]
ok, so it sounds like this one can be closed -- also, I'd like a "signed off by @odersky" on #745 before merging that one

**Pull request closed without merging**
