### PR TITLE
IMPORTANT: Base your PR on this one --> New PR validation <--

### PR DESCRIPTION
**Pull request by adriaanm**
NOTE: you must (re)base future PRs on this PR, as we are moving over to https://scala-ci.typesafe.com for PR validation. More details coming to scala-internals.

### CODE REVIEW

**Comment by adriaanm** [comment]
Looks like jenkins config issue because the validation job is now run against multiple repos. Attempted fix: https://github.com/adriaanm/scala-jenkins-infra/commit/5a39307c6c

**Comment by adriaanm** [comment]
Very funny, jenkins. The main flow picked up later failures in the test job while I was experimenting....

**Comment by adriaanm** [comment]
LGTM

**Comment by adriaanm** [comment]
LGTM

**Comment by adriaanm** [comment]
@scala/team-core-scala, please have a look and merge this so that future PRs can include the scripts.

**Comment by adriaanm** [comment]
The next step will be to add integration testing, as tracked here: https://github.com/adriaanm/scala-jenkins-infra/issues/7

**Comment by lrytz** [comment]
LGTM

**Comment by adriaanm** [comment]
Alright! Green enough!

**Comment by retronym** [comment]
Something seems to be wrong with file encodings. This manifests as failures in tests in `test.interactive` for tests with checkfiles containing the Unicode arrow symbol.

I have a feeling this is triggered by reusing a Jenkins workspace, as opposed to using a fresh checkout.

Right now, we can see the following in the `.check` and `.log` files, as viewed by the Jenkins web UI:

image

image

Diffing the failing build on #4271 and the last successful build:

``` patch
-Started by upstream project "scala-2.11.x-validate-main" build number 118
+Started by upstream project "scala-2.11.x-validate-main" build number 137
 originally caused by:
  Started by user scala-jenkins
 Notifying endpoint 'HTTP:http://scala-ci.typesafe.com:8888/jenkins'
 Building remotely on jenkins-worker-behemoth-1 (public linux) in workspace /home/jenkins/workspace/scala-2.11.x-validate-test
- > git rev-parse --is-inside-work-tree # timeout=10
-Fetching changes from the remote Git repository
+Cloning the remote Git repository
+Cloning repository https://github.com/scala/scala.git
+ > git init /home/jenkins/workspace/scala-2.11.x-validate-test # timeout=10
+Fetching upstream changes from https://github.com/scala/scala.git
+ > git --version # timeout=10
+ > git -c core.askpass=true fetch --tags --progress https://github.com/scala/scala.git +refs/heads/*:refs/remotes/scala/*
+ > git config remote.scala.url https://github.com/scala/scala.git # timeout=10
+ > git config remote.scala.fetch +refs/heads/*:refs/remotes/scala/* # timeout=10
  > git config remote.scala.url https://github.com/scala/scala.git # timeout=10
 Fetching upstream changes from https://github.com/scala/scala.git
- > git --version # timeout=10
  > git -c core.askpass=true fetch --tags --progress https://github.com/scala/scala.git +refs/heads/*:refs/remotes/scala/* +refs/pull/*/head:refs/remotes/scala/pr/*/head
- > git rev-parse 7e6efaaf6adfcb2fc9676e076bb3c58506772356^{commit} # timeout=10
-Checking out Revision 7e6efaaf6adfcb2fc9676e076bb3c58506772356 (detached)
+ > git rev-parse 80d56a40755e0806d33959ad991acb282cd0ba54^{commit} # timeout=10
+Checking out Revision 80d56a40755e0806d33959ad991acb282cd0ba54 (detached)
  > git config core.sparsecheckout # timeout=10
- > git checkout -f 7e6efaaf6adfcb2fc9676e076bb3c58506772356
+ > git checkout -f 80d56a40755e0806d33959ad991acb282cd0ba54
  > git rev-list 7e6efaaf6adfcb2fc9676e076bb3c58506772356 # timeout=10
 Cleaning workspace
  > git rev-parse --verify HEAD # timeout=10
 Resetting working tree
  > git reset --hard # timeout=10
  > git clean -fdx # timeout=10
-[scala-2.11.x-validate-test] $ /bin/bash -ex /tmp/hudson141772193023165892.sh
+[scala-2.11.x-validate-test] $ /bin/bash -ex /tmp/hudson4621020309136467389.sh
```

**Comment by retronym** [comment]
The Scala Jenkins master node appears to be started with `-Dfile.encoding=UTF-8`. 

image

I don't have access to the Script Console on the new Jenkins clusters to contrast this setting.

**Comment by retronym** [comment]
https://github.com/adriaanm/scala-jenkins-infra/pull/14

**Pull request merged**
