### PR TITLE
STARR now includes source

### PR DESCRIPTION
**Pull request by jsuereth**
Not that it gives us full reproducibility, but it's a start.

Also STARR now uses pack libs.  Testing appears to work.

Review by @lrytz @xeno-by @dragos

especially need to check IDE with this.

### CODE REVIEW

**Comment by hubertp** [comment]
Should this really go for M4? Given that IDE might fail maybe this can until Tuesday?

**Comment by jsuereth** [comment]
No problem having it wait.  Just getting my PRs out today.

**Comment by jsuereth** [comment]
BTW - This only affects new STARRs.  It should not break the IDE unless someone uses this to make a new STARR.

**Comment by xeno-by** [comment]
I have several pending critical reflection bugs, and, who knows, maybe one of them will make me resubmit a starr. What procedure should I follow?

**Comment by jsuereth** [comment]
I would like to have a commit with STARR sources regardless of this commit.   However, maybe we start enforcing that after M5?   It needs to happen.

**Comment by lrytz** [comment]
lgtm - i also don't think it affects the ide.

**Pull request merged**
