### PR TITLE
Fix memory leak related to default arguments in presentation compiler.

### PR DESCRIPTION
**Pull request by lrytz**
This bug exists for a long time, but was triggered / discovered only lately
by the default argument of mkParams in 118aef558f.

This reverts the workaroud commit 19b6ad5ee4.

The fix is tested by test/files/presentation/memory-leaks which runs the
presentation compiler several times on Typers.scala. I could not reproduce
the memory leak in a smaller test case.

Build: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/9/console

### CODE REVIEW

**Comment by adriaanm** [comment]
Cool! Did you try using scala.tools.nsc.util.WeakHashSet directly instead of the Set[WeakReference]?

**Comment by lrytz** [comment]
no - is it preferable? then i can do that change.

**Comment by adriaanm** [comment]
I would prefer it as it seems a bit more encapsulated, but I haven't looked at it in detail, so maybe it's subtly different?

Both patterns seem to be in use in the compiler (on casual inspection by grepping for "Set[WeakReference").

**Comment by lrytz** [comment]
Agree about more encapsulated, but `WeakHashSet` does not have `withDefaultValue`, so in this case the code would get more clumsy. I don't have a strong preference though.

**Pull request merged**
