### PR TITLE
SI-7155 Remove deprecated private s.c.m.AVLTree

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
The code is `private[scala.collection.mutable]`, so it can't be used in the wild except with reflection or people placing their own code in the `scala.collection.mutable` package.

Review by @Ichoran?

**Comment by SethTisue** [comment]
LGTM

**Comment by SethTisue** [comment]
thank you Simon for keeping up with the deprecations. much appreciated

**Comment by Ichoran** [comment]
@soc - Thanks for keeping track of this!  It's especially time to get rid of it since we have a full-fledged mutable Red-Black tree in 2.12.x now.

**Pull request merged**
