### PR TITLE
Address/workaround issue SI-3452 and related problems, try #2

### PR DESCRIPTION
**Pull request by Blaisorblade**
Workaround issue SI-3452 (1) and fix some of the underlying bugs (2).
(1) To workaround SI-3452, enable by default a warning (which was enabled by -Ycheck:genjvm) which omits faulty generic signatures. This was part of the previous pull request and nobody objected.
(2) Address some of the underlying bugs, by changing some generated generic signatures (which were incorrect before): one is a problem with intersection types (see 34d8f03007e849f8600a479fe6ae41e1cb4153f6), the other a false mismatch between `Nothing` and `Nothing$`.
Note that Paul Phillips had objections originally to how I solved the intersection types problem, and did not comment on it later: since the new behavior for generic signatures is simply coherent with the behavior of erasure, this should not be a problem.
(3) Reenable -Xverify and update its docs.

Some "related" cleanups are also included.

This pull request incorporates some feedback from scala-internals. It also supersedes https://github.com/scala/scala/pull/584, described in:
https://issues.scala-lang.org/browse/SI-3452?focusedCommentId=57712#comment-57712

Review by @magarciaEPFL
Review by @gkossakowski

### CODE REVIEW

**Comment by Blaisorblade** [comment]
I forgot to discuss the remaining bugs which form SI-3452. I have some understanding of them, and Paul Phillips wrote some code which fixes most of the other warnings but introduces regressions, visible in commit [Blaisorblade/scala@466fe7b88dd48819ac233505652161801d269186].
[As discusses on scala-internals](https://groups.google.com/forum/?fromgroups#!topic/scala-internals/K2dELqajQbg), I identified why that patch causes regressions and I believe that another approach addresses the problem better, I will try discussing/implementing that again later.

**Comment by gkossakowski** [comment]
FYI: I'm on vacations until Monday and I won't be able to do any code reviews by that time.

**Comment by retronym** [comment]
Does this need new tests cases, or is there a `-Xverify` build the repurposes the existing body code to this purpose?

**Comment by Blaisorblade** [comment]
I don't get precisely your comment, but I'll try to answer anyway. I reintroduced `-Xverify` as available in 2.9 using code from `GenASM.scala`, hence the same tests should apply to `-Xverify` in both cases; moreover, I'm not aware of any known `-Xverify` bug - that is, `scalac` seems to never generate non-well-formed signatures. To check that, I'm rebuilding `locker` and `quick` with `-Xverify`.
EDIT: -Xverify indeed triggers no warnings;  to verify this, I've set `scalac.args` to `-Xverify` in `build.xml`, and grepped for `created invalid generic signature` in the output, finding no match.

The partial fixes for SI-3452 would instead benefit from test cases; currently their effect is reducing the number of warnings. Most testcases for SI-3452 are introduced by Paul Phillips' fix.

**Comment by Blaisorblade** [comment]
@gkossakowski, @magarciaEPFL: anything I can do to help your review? I don't want to be annoying, yet by the pull-request policy I'm responsible for reminding you. Should I mail scala-internals?

**Comment by magarciaEPFL** [comment]
Java signatures has been an area where @gkossakowski has made good progress, so I'm looking forward to see those skills applied here! :)

**Comment by magarciaEPFL** [comment]
Java signatures has been an area where @gkossakowski has made good progress, so I'm looking forward to see those skills applied here! :)

**Comment by adriaanm** [comment]
Greg will be back next week. I'll leave the pull request open until then.
Thanks for keeping the show going, @Blaisorblade.

**Comment by gkossakowski** [comment]
Sorry for the long overdue. I had to find a window of time long enough to dig into this issue. The review will come shortly.

**Comment by gkossakowski** [comment]
Hi, I spent a fair amount of time trying to understand what's the problem and what's the solution presented in this pull request. I think lots of things in this pull request make sense but if you look at diff you can see it comes with no tests.

Honestly speaking, I cannot see what exactly those changes fix because of the lack of test-cases. If I understand @Blaisorblade correctly those changes are meant to fix wrong signatures that make some java code not compile. If so then why not add tests to `test/files/jvm` that show with minimal example (e.g. one that doesn't depend on the library) what's being fixed here?

I could infer that from lengthy discussions that surround this pull request but I think just having test-cases is better.

Closing this for now. Please reopen once you rebase your changes to include tests. Don't be discouraged by this outcome. I can promise to review it more quickly if there are easy to understand test-cases (which usually comes in a form of little pieces of code + some comments on them).

**Comment by Blaisorblade** [comment]
Understood :-). I'm not discouraged, it'll just take some time.

Do you think your idea would fit in https://github.com/scala/scala/wiki/Pull-Request-Policy or something like that?

Now I also understand @retronym's comment better: one can look at the warnings which disappear with this pull request, but that's not as robust, and it's hard to review.

**Comment by gkossakowski** [comment]
Yes, follow the Pull request policy. The most important bit is really to have tests that are:
- focused and easy to understand, e.g. have a small piece of Scala code that when compiled cannot be called from Java
- those tests should be added in the same commit as the fix

What I'm going to do is to partially revert your commits so tests stay in place but fix is reverted. When I see test failing I'll bring back the rest of your commit to see that it indeed fixes the issue. Thus, both conditions must be met: test-case fails before the fix (so we are addressing the real problem) and it passes after the fix.

When it comes to looking at warnings I agree it's less ideal. I'd prefer tests that crash javac or java (because javac produces a wrong bytecode by being confused by broken signatures scala emtis).

Does this sound good to you?

**Comment by Blaisorblade** [comment]
Makes sense. Only remark: my point is that the pull request policy says nothing about this. If what you just described helps not just here, may I suggest to fit your explanation in there as a tip for submitters, to use if appropriate? Just an idea.

**Comment by gkossakowski** [comment]
Good idea. I'll discuss this with others on internals.

**Comment by acruise** [comment]
@gkossakowski, one problem here is that neither scalac nor javac fails to compile; the Java code throws a NoSuchMethodError _at runtime_.  At least it does in the case of SI-6050.

**Comment by gkossakowski** [comment]
@acruise: Sorry for being confused. In any case, you can put your tests into `files/run` so they will be compiled and ran. I can help with writing tests.

**Comment by acruise** [comment]
@gkossakowski no need for apologies! :) I'm not familiar enough with partest, can it handle the sequence:
- compile Scala file
- compile Java file
- run a compiled class

?

Thanks for spending time on this issue!

**Comment by adriaanm** [comment]
yep, that's within the realm of possibility
suffixing test files with _NNN where NNN indicates the desired compilation order should do the trick
e.g. t3452_1.scala, ClassName_2.java

**Comment by gkossakowski** [comment]
We have examples of that:

```
find files/run -name '*_2.java'
files/run/t3897/J_2.java
files/run/t4317/J_2.java
files/run/t4891/J_2.java
```

You can run `./partest files/run/t3897 --verbose` to see what partest does exactly.

**Comment by Blaisorblade** [comment]
@acruise: it looks like you're going to write testcases before I would have time for it. That's good!

I took a look at SI-6050, and I believe it's a subcase of SI-3452 which is not addressed fully by this pull request. I'd expect that with this code, scalac will produce a warning on your code, emit no generic signature, so that Javac will work, while using [this other experimental branch](https://github.com/Blaisorblade/scala/commits/issue/3452), with code from Paul Phillips (extempore) should emit no warning. The other branch, however, has still some regressions.

**Pull request closed without merging**
