### PR TITLE
Fix tasty/TestLogarithms.scala failed in some platform

### LINKED ISSUE #12759: Tasty test case TestLogarithms failed
## Reproduction steps

Scala version: scala/scala 2.13.x branch

```
sbt:root> restarrFull
sbt:root> compile
sbt:root> tasty/test
```

## Problem
Test case tastytest.TestLogarithms failed.
```
ERROR: tastytest.TestLogarithms failed: AssertionError 1 error at iteration 0:
AssertionError in TestLogarithms.`test`: assertion failed in 
  tastytest.Suite.runImpl(Suite.scala:59)
  tastytest.Suite.main(Suite.scala:40)
  tastytest.TestLogarithms.main(TestLogarithms.scala)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  scala.tools.tastytest.internal.Runner$.$anonfun$run$2(Runner.scala:26)
  scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
  scala.Console$.withErr(Console.scala:193)
  ....................
  com.novocode.junit.JUnitTask.execute(JUnitTask.java:64)
  sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  java.base/java.lang.Thread.run(Thread.java:829)
[error] Test scala.tools.tastytest.TastyTestJUnit.run failed: java.lang.AssertionError: scala.tools.tastytest.TestFailure: 1 error. Fix tastytest.TestLogarithms., took 3.747 sec

```
My environment:
MacOS M1 platform. 
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Homebrew (build 11.0.18+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.18+0, mixed mode)

I have done some investigation. The following codes have unexpected result:
```
scala> math.exp(math.log(math.exp(math.log(2)) + math.exp(math.log(3))))
val res0: Double = 5.0

```
In another platform(xx86_64), the result is:
```
scala> math.exp(math.log(math.exp(math.log(2)) + math.exp(math.log(3))))
val res0: Double = 4.999999999999999
```

I think it is M1 arm64 platform issue. Need to try it on other arm64 platform.

### PR DESCRIPTION
**Pull request by liang3zy22**
Update the test case since it failed on arm64 platform. also to fix scala/bug#12759.

### CODE REVIEW

**Review by bishabosha — COMMENTED** [review]
maybe (to avoid the `||`) there are some powers that don't have unportable precision, like powers of 2 maybe?

**Comment by sjrd** [comment]
Better idea: use `StrictMath.log` and `StrictMath.exp` everywhere. That is guaranteed to be portable.

**Review by sjrd — APPROVED** [review]

**Comment by liang3zy22** [comment]
Only use StrictMath.log and StrictMath.exp still have double precision issue. And StrictMath don't have log2 function. So I used StrictMath.log10 and StrictMath.pow(10.0,num) to use base 10 instead.

**Review by bishabosha — APPROVED** [review]

**Comment by bishabosha** [comment]
Thanks for taking a look into this!

**Pull request merged**
