### PR TITLE
SI-7616 Avoid ClassCastException in scala.concurrent.impl.ExecutionConte...

### PR DESCRIPTION
**Pull request by phaller**
...xtImpl

Adds test to scala-concurrent-tck

### CODE REVIEW

**Comment by phaller** [comment]
Review by @axel22 or @heathermiller or @viktorklang

**Comment by heathermiller** [comment]
Wow– strange that we missed this. Good, but also weird that 2.10.x missed this. I guess we have a tendency to overlook `ExecutorService` a bit more than FJ.

LGTM!

**Comment by axel22** [comment]
LGTM

**Comment by viktorklang** [comment]
LGTM

**Comment by viktorklang** [comment]
I think the reason it's different  is because FJ is not an ExecutorService in 2.9?

**Comment by heathermiller** [comment]
Ah, true. Makes sense.

**Comment by demobox** [comment]
> Job pr-rangepos-per-commit failed for 092d75e (results):

The [build failure](https://scala-webapps.epfl.ch/jenkins/job/pr-rangepos-per-commit/3065/) references a different commit: https://github.com/scala/scala/commit/325943d5c34e4dfc901d589dec6e97f9fcfd1372

**Comment by adriaanm** [comment]
> The build failure references a different commit: 325943d

We don't use the git plugin, so that line is misleading. The build does test the right commit:

```
     [echo]        build time: 27 June 2013, 10:34:04
     [echo]      java version: Java HotSpot(TM) 64-Bit Server VM 1.6.0_33
     [echo]         java args: -Xms1536M -Xmx1536M -Xss1M -XX:MaxPermSize=256M -XX:ReservedCodeCacheSize=128M -XX:+UseParallelGC -Dpartest.threads=4 
     [echo]        javac args: 
     [echo]       scalac args: 
     [echo]          git date: 20130627-102335
     [echo]          git hash: 092d75e257
     [echo]     maven version: 2.9.3-SNAPSHOT
     [echo]      OSGi version: 2.9.3.v20130627-102335-092d75e257
     [echo] canonical version: 2.9.3-20130627-102335-092d75e257
```

**Comment by demobox** [comment]
> We don't use the git plugin, so that line is misleading.

Ah, sorry, thanks for explaining, @adriaanm . I take it then that the build failure does indeed signal a problem with this PR, or..?

**Comment by adriaanm** [comment]
Sorry, I missed this and I also missed that this targets 2.9. Rangepos is "known" to fail here.
LGTM.

**Pull request merged**
