### PR TITLE
Merge 2.11.x to 2.12.x [ci: last-only]

### PR DESCRIPTION
**Pull request by retronym**
We really need this commit in place before shipping a milestone with
GenBCode enabled:

  b17a291 GenBCode: fix incrementatal compilation by mimicing GenASM

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm @SethTisue

**Comment by SethTisue** [comment]
Adriaan says no worries on the red commits, "with a merge, that sometimes happens"

**Comment by adriaanm** [comment]
Community build is :+1:!

**Comment by adriaanm** [comment]
To clarify, we should strive to avoid red builds also for merge commits. We now run merge validation and should make sure conflicting merges are dealt with ASAP.

**Pull request merged**
