### PR TITLE
SI-4427 document package objects appearing in implicit scope

### PR DESCRIPTION
**Pull request by Blaisorblade**
The implicit scope of `a.A` includes package object `a`. Document this, following the text posted by @odersky in the ticket (hoping my manual diff is correct).

Fixes #4427.

Warning: please make sure `2.11.x` is the branch where I should send this.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
The failure is spurious _and_ repeatable (see https://github.com/scala/scala/pull/3903#issuecomment-50731636 and https://groups.google.com/d/msg/scala-internals/XKJa5WffDXg/LuRgQ4KPSsoJ).

**Comment by som-snytt** [comment]
Ever since Adriaan updated the kitteh script to rebuild the implementation automatically incorporating deltas from the spec, you can't change punctuation without a test breaking.

Unfortunately, kitteh updates the compiler based on its _interpretation_ of the spec.  And it gets smarter with each change, so that eventually it learns to just ignore anything you put in.  Usually it just tweaks the error messages a bit so you think you've achieve some clarity.  Recently it added some Xlint levers.

**Comment by Blaisorblade** [comment]
> Ever since Adriaan updated the kitteh script to rebuild the implementation automatically incorporating deltas from the spec, you can't change punctuation without a test breaking.

I didn't realize you were writing science fiction until that point :laughing:

**Comment by som-snytt** [comment]
Not sure it was clear that, on the ticket, I was quoting the current spec, after the bullet list.

If you think that line is unclear or duplicates your change, you might want to amend it.  I couldn't find where it crept into the @adriaanm edition.  I'm not up to digging for bones.

**Comment by Blaisorblade** [comment]
> Not sure it was clear that, on the ticket, I was quoting the current spec, after the bullet list.

Aaaaah!! No, I completely didn't realize, sorry. I'd also have appreciated a quote tag, which I added (though I also hate using JIRA's markup) - I hope that was okay.

### On what's best to write

One can argue that the current language exposes an implementation detail.
Or that the current language uses (in an unstructured way and only here) an _elaboration semantics_, that is it documents how constructs are desugared to core constructs. However, things are much more complicated, so I'm against doing this just locally, and I still prefer Odersky's language.

I'll take a closer look later.

**Comment by lrytz** [comment]
Thanks @Blaisorblade & @som-snytt for tracking down the details - in order not to duplicate things, let's keep the spec the way it is now (the existing clarification is in the same paragraph as the one added by this PR). I'm closing this PR and the related issue.

**Comment by som-snytt** [comment]
Yeah, jira markup deserves all the hate emails it gets. I only know `{code}`; anything else and I have to scroll through the help pop-up. Thanks for fixing it.

On the language, "internally represented" or whatever it is, I was going to make a pertinent joke about "it's how the spec represents it internally to itself" or whatever, but obviously the jokey wording didn't pop into my head.

**Pull request closed without merging**
