### PR TITLE
Scaladoc update for collection.mutable.MultiMap

### PR DESCRIPTION
**Pull request by kiritsuku**
Addition of source code example on how to use a MultiMap and its
defined methods. Minor correction in documentation for method
`removeBinding`.

This is my first PR to scala-library, please tell me if I can do something better.

For possible future PRs, shall I assign documentation updates to specific people?

### CODE REVIEW

**Comment by jsuereth** [comment]
This looks great!   A few questions:

 ( 1) have you signed the cla?
 ( 2) Could you target this at 2.10.x branch so that it goes into the 2.10 series?

Currently the master branch is for 2.11.0

**Comment by kiritsuku** [comment]
To 1: I already commited to scala-ide, thus when the CLA there counts also for scala, I have signed it, yes.
To 2: Do I need to create a new PR for this or is it somehow possible to change the current one?

**Comment by adriaanm** [comment]
2) I'm afraid a new PR is needed. I don't know of a way to change the merge target.

**Comment by kiritsuku** [comment]
Follow-up in https://github.com/scala/scala/pull/1641

**Comment by juanmirocks** [comment]
One thing that was not obvious to me at first was that I had to import mutable.Set too. Otherwise using the default and always visible immutable.Set, the compiler throws a very long list of strange inheritance problems.

Should this fact be stated more explicitly in the documentation?

**Comment by kiritsuku** [comment]
I added the needed import to the code example. Nevertheless it can be that it must be stated more explicitly. The problem is that most types/methods in Scala lack good code examples and information about pitfalls. After some discussion on the mailing list, it came out that Scaladoc needs to be improved to support such code examples and documentation about pitfalls.

**Comment by juanmirocks** [comment]
Definitely, and I liked your documentation :) And thanks that I saw your import of immutable.Set I got my problem fixed. But at the beginning, coding in eclipse, MultiMap and HashMap were automatically imported but not mutable.Set. I didn't know what to do for quite a while. I guess more people will have this problem.

Or perhaps is the actual type definition wrong/confusing in MultiMap and it should clearly state that it needs a mutable.Set?

**Comment by kiritsuku** [comment]
I share your frustration about underdeveloped documentation 
possibilities either for Scaladoc itself as well as for the not yet 
existing Scaladoc integration in Eclipse. I plan to change that but at 
the moment I don't have enough time work heavily on that.

**Comment by juanmirocks** [comment]
Thanks Christian. I would like to help. I will get involved in the mailing list of scala-ide to see what needs to be done. If you can give me other directions/hints, I would appreciate it.

**Comment by kiritsuku** [comment]
Contributions are welcome, if you want to fix something in the Scala 
IDE, just look at: 
https://www.assembla.com/spaces/scala-ide/support/tickets

There should be enough tickets to pick one out. ;)

**Pull request closed without merging**
