### PR TITLE
SI-7861 Don't execute internal callbacks on the user Executor

### PR DESCRIPTION
**Pull request by retronym**
Callbacks internal to the implementation of Futures should be
executed with the `InternalCallbackExecutor`, rather than the
user supplied `Executor`.

In a refactoring da54f34a6, `recoverWith` and `flatMap` no longer
played by these rules. This was noticed by a persnickety test in
Play.

Before this patch, the enclosed test outputs:

```
% scala-hash v2.10.3-RC2 test/files/run/future-flatmap-exec-count.scala
mapping
execute()
flatmapping
execute()
execute()
recovering
execute()
execute()
```

Review by @viktorklang. I'm being conservative here and marking this as a blocker for 2.10.3, but I'm open to other opinions.

### CODE REVIEW

**Comment by viktorklang** [comment]
@retronym LGTM, thanks!

**Comment by retronym** [comment]
Damn, forgot the .check file.

**Comment by richdougherty** [comment]
FYI, here's the class we use in Play to check that `execute()` is called the correct number of times: https://github.com/playframework/playframework/blob/master/framework/src/iteratees/src/test/scala/play/api/libs/iteratee/TestExecutionContext.scala

It also checks that `prepare()` is called in the correct thread (see SI-7846 for some preparation bugs).

**Comment by retronym** [comment]
Cheers. I distilled this test case from that code.

**Comment by retronym** [comment]
Successful test run: https://scala-webapps.epfl.ch/jenkins/job/pr-scala/2433/

**Pull request merged**
