### PR TITLE
More scaladoc speed optimization:

### PR DESCRIPTION
**Pull request by vigdorchik**
Don't parse doc comment if the word 'deprecated' is not mentioned.
Review by @VladUreche.

### CODE REVIEW

**Comment by VladUreche** [comment]
Eugene, did you actually notice any speedup? It seems like a useless complication to look for "deprecated" in the doc comment. Especially since most deprecation annotations appear as scala annotations.

**Comment by vigdorchik** [comment]
Vlad, I did notice some speedup. Also I base my optimization on yourkit profile. Below is the profile of backtraces of 'deprecation':

Back traces

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
|                                                                                             Name                                                                                              |    Time (ms)    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+
|  +---scala.tools.nsc.doc.model.ModelFactory$MemberImpl.deprecation()                                                                                                                          |  43,171  100 %  |
|    |                                                                                                                                                                                          |                 |
|    +---scala.tools.nsc.doc.model.Entity$.scala$tools$nsc$doc$model$Entity$$isDeprecated(Entity)                                                                                               |  35,937   83 %  |
|    | |                                                                                                                                                                                        |                 |
|    | +---scala.tools.nsc.doc.model.Entity$$anonfun$EntityOrdering$1.apply(Entity)                                                                                                             |                 |
|    |   |                                                                                                                                                                                      |                 |
|    |   +---scala.tools.nsc.doc.model.Entity$$anonfun$EntityOrdering$1.apply(Object)                                                                                                           |                 |
|    |     |                                                                                                                                                                                    |                 |
|    |     +---scala.math.Ordering$$anon$5.compare(Object, Object)                                                                                                                              |                 |
|    |       |                                                                                                                                                                                  |                 |
|    |       +---scala.math.Ordering$$anon$5.compare(Object, Object)                                                                                                                            |                 |
|    |         |                                                                                                                                                                                |                 |
|    |         +---java.util.Arrays.sort(Object[], Comparator)                                                                                                                                  |                 |
|    |           |                                                                                                                                                                              |                 |
|    |           +---scala.collection.SeqLike$class.sorted(SeqLike, Ordering)                                                                                                                   |                 |
|    |             |                                                                                                                                                                            |                 |
|    |             +---scala.collection.AbstractSeq.sorted(Ordering)                                                                                                                            |                 |
|    |               |                                                                                                                                                                          |                 |
|    |               +---scala.tools.nsc.doc.html.page.Template.<init>(Universe, DiagramGenerator, DocTemplateEntity)                                                                           |                 |
|    |                 |                                                                                                                                                                        |                 |
|    |                 +---scala.tools.nsc.doc.html.HtmlFactory.scala$tools$nsc$doc$html$HtmlFactory$$writeTemplate$1(DocTemplateEntity, Function1, HashSet, DiagramGenerator)                  |                 |
|    |                   |                                                                                                                                                                      |                 |
|    |                   +---scala.tools.nsc.doc.html.HtmlFactory$$anonfun$scala$tools$nsc$doc$html$HtmlFactory$$writeTemplate$1$2.apply(DocTemplateEntity)                                     |                 |
|    |                     |                                                                                                                                                                    |                 |
|    |                     +---scala.tools.nsc.doc.html.HtmlFactory$$anonfun$scala$tools$nsc$doc$html$HtmlFactory$$writeTemplate$1$2.apply(Object)                                              |                 |
|    |                       |                                                                                                                                                                  |                 |
|    |                       +---scala.collection.TraversableLike$$anonfun$map$1.apply(Object)                                                                                                  |                 |
|    |                         |                                                                                                                                                                |                 |
|    |                         +---scala.collection.TraversableLike$$anonfun$map$1.apply(Object)                                                                                                |                 |
|    |                           |                                                                                                                                                              |                 |
|    |                           +---scala.collection.immutable.List.foreach(Function1)                                                                                                         |                 |
|    |                             |                                                                                                                                                            |                 |
|    |                             +---scala.collection.TraversableLike$class.map(TraversableLike, Function1, CanBuildFrom)                                                                     |                 |
|    |                               |                                                                                                                                                          |                 |
|    |                               +---scala.collection.AbstractTraversable.map(Function1, CanBuildFrom)                                                                                      |                 |
|    |                                 |                                                                                                                                                        |                 |
|    |                                 +---scala.tools.nsc.doc.html.HtmlFactory.scala$tools$nsc$doc$html$HtmlFactory$$writeTemplate$1(DocTemplateEntity, Function1, HashSet, DiagramGenerator)  |                 |
|    |                                   |                                                                                                                                                      |                 |
|    |                                   +---scala.tools.nsc.doc.html.HtmlFactory$$anonfun$scala$tools$nsc$doc$html$HtmlFactory$$writeTemplate$1$2.apply(DocTemplateEntity)                     |                 |
|    |                                                                                                                                                                                          |                 |
|    +---scala.tools.nsc.doc.html.page.Template.inside$1(boolean, String, MemberEntity, boolean)                                                                                                |   7,015   16 %  |
|    |                                                                                                                                                                                          |                 |
|    +---scala.tools.nsc.doc.html.page.Template.memberToCommentBodyHtml(MemberEntity, DocTemplateEntity, boolean, boolean)                                                                      |     171    0 %  |
|    |                                                                                                                                                                                          |                 |
|    +---scala.tools.nsc.doc.html.page.Template$$anonfun$3.apply(MemberEntity)                                                                                                                  |      46    0 %  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+

Generated by YourKit Java Profiler 9.5.6 04-Oct-2012 20:10:14

**Comment by VladUreche** [comment]
What I mean is: did you notice an overall speedup? Since comment is a lazy val that is always computed in the end, the fact that you don't compute it now results in moving the computation later, but not getting rid of it. Am I missing something?

**Comment by VladUreche** [comment]
Okay, we have two possible explanations for this:
- either by doing this we save a couple of parser runs (which is the easy explanation)
- or there's some JIT sweet spot we found, which is interesting to understand and use more often :)

Eugene, can you please test the first hypothesis by logging the parsed comments and checking whether it's different with and without the patch?

**Pull request closed without merging**
