### PR TITLE
Typevar suspension

### PR DESCRIPTION
**Pull request by paulp**
Review by @adriaanm.

### CODE REVIEW

**Comment by paulp** [comment]
Note this commit is much smaller than it appears, because git/github really punish you for having to change the indentation of something.  Append '?w=1' and drop the many whitespace-only lines.

**Comment by adriaanm** [comment]
delectable -- LGTM

The amount of noise is unfortunate, though. It can indeed be somewhat reduced with ?w=1 (though not entirely).
Unfortunately, github does not seem to support commenting when whitespace is being suppressed. 

In an ideal world, we'd have a no-op beautification commit and a commit with the actual fix. My future selves thank yours.

**Comment by adriaanm** [comment]
oh, one more thing: while I'm all for rigor, I worry that the higher-order elegance in findMember might be incompatible with our performance quest

**Comment by paulp** [comment]
Perhaps it will be shown otherwise, but I think findMember will be fine.  You'll notice if I was really going for elegance I would have wrapped the inner function unconditionally in suspendTypeVars, because if this.isGround there is nothing to suspend.  So the closure creation only kicks in when suspension is a possibility, which I think is far enough the minority case.  But again, I didn't measure - my faith is in Team Performance to alert me if I'm wrong about my wild suppositions.

**Pull request merged**
