### PR TITLE
SI-9173 Either extends Product with Serializable

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by retronym** [comment]
LGTM. Usually I'd prefer a little more detail in the commit message, but the motivation is pretty well laid out in the linked bug so I'm happy to merge as is.

**Comment by retronym** [comment]
I don't see a corresponding PR for the change to `Try`. It would be good to deal with both of these tickets at once.

**Comment by soc** [comment]
Ok, I'll create another PR for Try.

**Comment by soc** [comment]
@retronym Done: https://github.com/scala/scala/pull/4405

**Pull request merged**
