### PR TITLE
SI-6221 inference with Function1 subtypes.

### PR DESCRIPTION
**Pull request by paulp**
There appears to be no upper bound on the number of places we have to remove
calls to typeSymbol and introduce calls to baseType. This one was type
inference for function parameter types: worked when expected type was A => B,
but not if there was an implicit conversion from A => B to the expected type.

### CODE REVIEW

**Comment by xeno-by** [comment]
Here's also one more test case:

```
import language.experimental.macros
import language.implicitConversions
import scala.reflect.macros.Context
import scala.reflect.runtime.universe.Tree

class ReflectiveClosure[A, B](val tree: Tree, fn: Function1[A, B]) extends Function1[A, B] {
  def apply(x: A) = fn(x)
}

object ReflectiveClosure {
  implicit def reflectClosure[A, B](f: Function1[A,B]): ReflectiveClosure[A, B] = macro Macros.reflectiveClosureImpl[A, B]
}

object Macros {
  def reflectiveClosureImpl[A, B](c: Context)(f: c.Expr[Function1[A, B]]) = {
    import c.universe._
    val u = treeBuild.mkRuntimeUniverseRef
    val m = EmptyTree
    val tree = c.Expr[scala.reflect.runtime.universe.Tree](Select(c.reifyTree(u, m, f.tree), newTermName("tree")))
    c.universe.reify(new ReflectiveClosure(tree.splice, f.splice))
  }
}
```

```
object Test extends App {
  implicit class PimpedList[T](val list: List[T]) {
    def query(predicate: ReflectiveClosure[T, Boolean]): List[T] = {
      println(predicate.tree)
      list filter predicate
    }
  }

  List(1, 2, 3).query(x => x % 2 == 0)
}
```

**Comment by paulp** [comment]
Review by @retronym

**Comment by retronym** [comment]
How about pattern matching anonymous functions?

I'm actually in two minds about this one. It seems quite useful, but it feels a bit sketchy to infer the parameter types based on the base type just to leave things open for an implicit to finish the job.

**Comment by paulp** [comment]
What is the rest of the "how about" ? Pattern matching anonymous functions are still Function1, right?

These non-uniformities which arise when one tries to accomplish something via implicit method instead of extension are huge friction contributors.

**Comment by retronym** [comment]
> What is the rest of the "how about" ? Pattern matching anonymous functions are still Function1, right?

I'd like to see tests for a pattern matching anonymous function with an expected type of `MyFunction1`, and one with expected type of `MyPartialFunction`.

**Comment by gkossakowski** [comment]
@paulp: what's the status of this PR? Are we waiting for additional tests?

**Comment by retronym** [comment]
I'd like to discuss this one in the broader context of SAM types. /cc @JamesIry @adriaanm

**Comment by heathermiller** [comment]
Just a short note + some context on this PR. The resolution of this ticket is essential for spores to be able to be integrated into Spark. Without this, we lose the ability to support a lot of existing Spark programs (as most folks rely upon type inference for function literals when passing them to Spark combinators). The reason this ticket is relevant is because the goal was for Spark to provide an implicit conversion from Function1 to Spore. Not resolving this before 2.11 would likely mean not having Spark on board as a user of spores (initially, Spark was the motivating use-case, and would be a huge user of spores).

On the topic of the broader context of SAM types– sure, it's a great question, and we will eventually need to solve the problem of type inference for general SAM types once the need for Java 8 support draws nearer. But, when chatting with @adriaanm at ScalaDays about how to approach this issue from an organizational/release standpoint, since spores could immediately reap those benefits, the sentiment was that that this would be very unlikely before 2.11.

Given that, I think it's essential that we have something in trunk (at some point before the release of 2.11) which will address the (less general) issue raised in this ticket so we can at least have type inference for spores.

**Comment by ryanlecompte** [comment]
+1 - this will be a boon to Spark.

**Comment by adriaanm** [comment]
A partial fun test would be good, but the implementation LGTM.

**Comment by adriaanm** [comment]
Also, SAM types are on our TODO for M4/5, but this can go in already, I'd say.

**Comment by adriaanm** [comment]
So, I've been thinking about this and it's a pure bug fix to me. Whenever you see symbol tests followed by extraction of type arguments, it's a bug and `baseType` is the fix.

This is related to SAM types (I'm working on those next week), but I don't see any way in which it could interfere.

I'll leave another day for reviewing, but merging tomorrow unless I hear opposition.

**Comment by retronym** [comment]
The compiler is only able to synthesize the exact type of `FunctionN`.

I find it analogous to this implicit search:

``` scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

trait Creator[+A] {
  def create: A
}

class Base
object Base {
  implicit def base: Creator[Base] = new Creator[Base] { def create = new Base }
}

class Sub extends Base

def create[T: Creator]: T = implicitly[Creator[T]].create

create: Sub

// Exiting paste mode, now interpreting.

<console>:37: error: could not find implicit value for evidence parameter of type Creator[T]
              create: Sub
              ^
```

We don't try `create[Base]` in the hope that we can adapt the result with an implicit `Base => Sub`.

You could imagine that SAM support might provide a `Creator[Sub]` into the search.

The spec seems to be pretty intentional with requiring an exact type:

> If the expected type of the anonymous function is of the form `scala.FunctionN[S1,...,Sn, R]`, the 
> expected type of `e` is `R` and the type `Ti` of any of the parameters `xi` can be omitted, in
> which case `Ti = Si` is assumed. If the expected type of the anonymous function is some
> other type, all formal parameter types must be explicitly given, and th expected type of
>  `e` is undefined.

I can definitely see the utility of this change, but I'm concerned about the ad-hoc-iness.

**Comment by retronym** [comment]
The interference with SAM types might come if the SAM type was itself a subclass of `FunctionN`. Would SAMs be tried before or after this approach?

**Comment by adriaanm** [comment]
This somehow breaks a refactoring test in the IDE. https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/253/console

**Comment by adriaanm** [comment]
As far as the spec goes, I think it's reasonable to interpret "a type T is of the form TC[U1,..., UN]"
as taking `U1,..., UN` from `T.baseType(TC.typeSymbol).typeArgs`.

**Comment by adriaanm** [comment]
We should not consider a SAM type a subtype of the corresponding FunctionN type since that will create problems with overloading. The SAM functionality I propose is purely target-typing as in PartialFunction synthesis: when the expected type is a SAM type, and we have a Function, synthesize an instance of the SAM type with its method given by the Function body, similar to what we do when expecting a PartialFunction with a Match in hand.

**Comment by adriaanm** [comment]
Sorry, could you elaborate a bit on your example? The implicit isn't found because `Create[Base]` is not a subtype of the expected `Create[Sub]`. I don't see how that relates to SAM typing (under the assumption that SAM typing does not affect subtyping in any way -- it's just a convenience in synthesizing anonymous classes based on expected type, like for PartialFunction).

**Comment by adriaanm** [comment]
(pending) LGTM, in other words :-)

**Comment by retronym** [comment]
I was wondering about what might happen if you has a SAM type that happened to subclass the existing Function types. That is the what is handle by this patch pre-SAM-support: the compiler will adapt use base type at `FunctionN` to infer the parameter type, and hope it can adapt the result to the subtype with an implicit view.

``` scala
class Fun extends (Int => Int)
(a => a): MyFun  // implicitly[(Int => Int) => Fun]((a: Int) => a)
```

Where would the adaptation to SAMs live? We need to extract the parameter type to drive inference, so the typing of Function nodes has to be SAM aware; we can't wait for `adapt`.

``` scala
trait Sam { def apply(a: Int): Int }
(a => a): Sam     // new Sam { def apply(a: Int) = a
```

My example with `Create` was trying to model the compilers synthesis of `FunctionN` and `PartialFunction` with a typeclasses. With such an approach, I wouldn't expect a creator of `Base` to step up to the plate when I'm really after a `Sub`, and of course type inference doesn't suggest that.

What error message will we give under this patch for the following? I'm worried it will be `found (Int => String), required List[String]`

``` scala
def foo(xs: List[String]) = ???
foo( x => x )
```

I would prefer to err on the side of conservatism and SIP this change together with SAMs. Maybe we can discuss on Tuesday?

**Comment by odersky** [comment]
Adriaan writes:

"As far as the spec goes, I think it's reasonable to interpret "a type T is of the form TC[U1,..., UN]"
as taking U1,..., UN from T.baseType(TC.typeSymbol).typeArgs."

I agree. In fact that seems to be already the case for PartialFunction. So I believe the change is good to go.

I believe once we go for SAM types we should change the spec to something like this:

If the expected type of the anonymous function is a SAM type with a single abstract method
of type (S1, ..., Sn)R, the expected type of e is R and the type Ti of any of the parameters xi can be omitted, in
which case Ti = Si is assumed. If the expected type of the anonymous function is some
other type, all formal parameter types must be explicitly given, and th expected type of
e is undefined.

Question: How to handle SAM types with polymorphic applies? Right now I do not see how we could accommodate them. No way to infer the type parameter and no way to write it either. But that's a restriction we could live with IMO.

**Comment by retronym** [comment]
I'll withdraw my objection for now then.

**Comment by paulp** [comment]
@retronym you were in the right ballpark:

```
scala> def foo(xs: List[String]) = ???
foo: (xs: List[String])Nothing

scala> foo( x => x )
<console>:9: error: type mismatch;
 found   : Int
 required: String
              foo( x => x )
                        ^
```

As opposed to without this patch:

```
scala> foo( x => x )
<console>:9: error: missing parameter type
              foo( x => x )
                   ^
```

We may have beaten him into submission, but it sure does make me nervous to proceed with something jason thinks is boneheaded (not that he'd put it that way.)

**Comment by adriaanm** [comment]
Agreed, I'll defer merging until we can discuss this in the meeting.

**Comment by adriaanm** [comment]
```
[adriaan@feather scala (master *$>)]$ qs
Welcome to Scala version 2.11.0-20130628-170316-bfda11426f (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> abstract class Foo { def meh(x: String): Int }
defined class Foo

scala> (x => 1): Foo
res0: Foo = $anonfun$1@308c6f69

scala> abstract class Foo { def meh(x: String): Int; def bla = meh("bla") }
defined class Foo

scala> val res3 = { (x => 1): Foo }
res3: Foo = $anonfun$1@7e383efa

scala> res3.bla
res1: Int = 1

scala> new Thread{() => println("hello sammy world")}.start()

scala> abstract class  Sam { def apply(a: Int): Int }
defined class Sam

scala> (a => a): Sam     // new Sam { def apply(a: Int) = a
res3: Sam = $anonfun$1@393cd5b5

scala> def foo(xs: List[String]) = ???
foo: (xs: List[String])Nothing

scala> foo( x => x )
<console>:9: error: type mismatch;
 found   : Int
 required: String
              foo( x => x )
                        ^


scala>  abstract class MyFun extends (Int => Int)
defined class MyFun

scala> (a => a): MyFun
res5: MyFun = <function1>

scala> res5(1)
res6: Int = 1
```

**Comment by adriaanm** [comment]
I agree the snippet below is problematic. The error should be about `x => x` not being a `List[String]`.

```
scala> def foo(xs: List[String]) = ???
foo: (xs: List[String])Nothing

scala> foo( x => x )
<console>:9: error: type mismatch;
 found   : Int
 required: String
              foo( x => x )
                        ^
```

**Comment by adriaanm** [comment]
Prototype: https://github.com/adriaanm/scala/tree/sammy

**Comment by adriaanm** [comment]
@retronym, I see what you mean now regarding the confusion with SAM types that extend FunctionN.

I propose the following rule:
1. If the expected type is a SAM but not `FunctionN` itself, use the SAM translation (derive parameter types from the sam method).
2. Else, if the expected type is a subtype of `FunctionN`, use the regular Function translation (derive parameter types from `pt baseType FunctionN` -- as implemented by this PR)

**Comment by retronym** [comment]
Sounds okay, other than cases like `class Sam extends (() => Unit) { def apply() = (); def sam(a: Int) = 0 }`. But I doubt that would come up much in practice.

Incidentally, what's our story for SAMs vs existing implicit conversions?

``` scala
trait A { def sam(a: Int): Int }
def foo(r: A)
implicit def f2r(f: (a: Int) => Int)) = { new A { def sam(a: Int) = f(a) } }
foo((a: Int) => 22)
```

Would we try the SAM before or after implicits? (Or at the same time?)

**Comment by JamesIry** [comment]
We've been thinking that SAMs should come after because
a) a user imported implicit may be something more specific that the user really wants, and
b) using SAMs before implicits could break existing code

**Comment by adriaanm** [comment]
In this implementation, SAM conversion actually comes first.
Traits aren't supported yet, but

```
scala> abstract class A { def sam(a: Int): Int }
defined class A

scala> def foo(r: A) = ???
foo: (r: A)Nothing

scala> implicit def f2r(f:  Int => Int) = { println("OHNOES"); new A { def sam(a: Int) = f(a) } }
warning: there were 1 feature warning(s); re-run with -feature for details
f2r: (f: Int => Int)A

scala> foo((a: Int) => 22)
scala.NotImplementedError: an implementation is missing
```

Btw, have a look at https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/928/console for the three test failures that may shed some light on the change in behavior.

**Comment by gkossakowski** [comment]
FYI: I started a thread discussion our definition of a SAM: https://groups.google.com/forum/#!topic/scala-internals/kPcw8OAXOoI

**Comment by adriaanm** [comment]
This will soon be subsumed by sammy.

**Comment by adriaanm** [comment]
(where sammy == https://github.com/adriaanm/scala/compare/sammy?expand=1)

**Comment by adriaanm** [comment]
I won't get my branch in shape in time for 2.11.0-M4, so let's already get this in.

**Comment by adriaanm** [comment]
LGTM

**Comment by heathermiller** [comment]
:D

**Comment by mateiz** [comment]
Haha, that is exciting! So is the idea that with this change, we can have an API that takes Spore, but still add an implicit conversion macro from Function1 to Spore? That definitely sounds doable.

**Comment by retronym** [comment]
Spore will need to extend `Function1` in addition to having that implicit conversion. But yeah, you can rig this up.

**Comment by adriaanm** [comment]
We're planning to add Java 8-style SAM support to Scala, so the compiler will synthesize the anonymous subclasses of SAM types based on a provided function literal.

**Comment by adriaanm** [comment]
(Implementation is here: https://github.com/adriaanm/scala/tree/sammy)

**Comment by heathermiller** [comment]
@mateiz yes, that's the goal. A revision of the SIP is soon forthcoming as well as a revised implementation to go along with the SIP revisions.

**Pull request merged**
