### PR TITLE
SI-7790 No ScriptEngine in 2.10 build

### PR DESCRIPTION
**Pull request by som-snytt**
The service entry was inadvertendly added in
`e3b5e0ba40447970d621cfeed5cc1770df69884f`,
"Sanity for build.xml: exscriptus&positus delendus est,"
which is ant latin for: "Reduced copy/pasting to the best
of my antabilities."

With that degree of hubris, it was inevitable that the
commit introduced a copy/paste bug.  What is the Attic
Greek for copy/paste?

I'm pretty sure that in fifth century Athens they would
just pound one inscription to rubble using a bigger
inscription. They had slaves for that kind of work.
You never hear about Socrates tweaking the build script.
That's the reason he never wrote anything down.

Review by @adriaanm

### CODE REVIEW

**Comment by som-snytt** [comment]
@JamesIry It would be nice if it made it into 2.10.3, as the ticketer requested.

**Comment by retronym** [comment]
Can you prefix the commit subjest with `[nomaster]` so it isn't merged to master? As an added safety, is there a test in master that would break with this removed?

**Comment by som-snytt** [comment]
Nomaster, I mean, Yes, master!

**Comment by adriaanm** [comment]
LGTM. I humbly accept thy fix.

**Comment by som-snytt** [comment]
The build system was a legendary task, somewhere between Tantalus and Sisyphus, with a touch of Herakles cleaning out the Antean Stables.

@retronym I'll add a test to verify the service entry on 2.11

**Pull request merged**
