### PR TITLE
Port old 2.10 release script to new CI.

### PR DESCRIPTION
**Pull request by adriaanm**
To fit in with the new flow, we upload to S3 instead of
using the copy artifact plugin.

Review by @gkossakowski

### CODE REVIEW

**Comment by adriaanm** [comment]
The relevant config of the old job (not public): https://github.com/scala/jenkins-config/blob/master/jobs/scala-dist/config.xml

**Comment by adriaanm** [comment]
Validated by https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-bootstrap/61/

**Comment by adriaanm** [comment]
@gkossakowski, shall we get this merged?

**Comment by gkossakowski** [comment]
Yep, LGTM

**Pull request merged**
