### PR TITLE
chore: Call Arrays.copyOf directly

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
I think it's better to just invoke the intrinsic one directly.

### CODE REVIEW

**Review by Ichoran — COMMENTED** [review]
I'm not sure about this one.

It's true that the OpenJDK implementation of `copyOf(x, n)` is just `copyOf(x, n, x.getClass)`.  But the API doesn't promise that this is true, and we _do_ rely on it being true here.

I would probably leave it alone.  It's not an obvious win, given that it's just avoiding a forwarder (the JVM will easily inline it, so it ought not matter).

**Comment by He-Pin** [comment]
we can change it back once the origin code marked `@IntrinsicCandidate`

**Comment by lrytz** [comment]
I agree with @Ichoran. This somewhat reminds me of https://github.com/scala/scala/pull/10526.

**Comment by He-Pin** [comment]
> I agree with @Ichoran. This somewhat reminds me of https://github.com/scala/scala/pull/10526.

Good memory

**Comment by He-Pin** [comment]
I submit it because in CE, they just use system.arraycopy directly, anyway, this is stdlib, not jctool.

**Comment by He-Pin** [comment]
BTW, I have a pr in pekko to just call Java‘s System.arraycopy directly too, which is faster in jmh than Scala's copyOf

**Pull request closed without merging**
