### PR TITLE
Print full type names in `-Vimplicits` and `-Vtype-diffs` error messages

### PR DESCRIPTION
**Pull request by mrdziuban**
Updates the error messages printed by `-Vimplicits` and `-Vtype-diffs` to use a type's full name, including its package path. Infix types and certain [shorthand types](https://github.com/scala/scala/blob/207c01b8efa96b9ba556bedcffc13458be2eafbd/src/reflect/scala/reflect/internal/Types.scala#L5286) are still printed as just the type's unprefixed name.

### CODE REVIEW

**Comment by lrytz** [comment]
Hmm... why can't we print the full path always, like we do for normal messages with a few exceptions? https://github.com/scala/scala/blob/207c01b8efa96b9ba556bedcffc13458be2eafbd/src/reflect/scala/reflect/internal/Types.scala#L5286

```scala
package a.b {
  class C
}

package x.y {
  class C
  class D
  object T {
    def t1: C = new a.b.C()
    def t2: D = new a.b.C()
    def t3: C = new D()
  }
}

class T {
  val t1: a.b.C = new x.y.D()
  val t2: a.b.C = new x.y.C()
}
```

shows as

```
A.scala:9: error: type mismatch;
 found   : C (in a.b)
 required: C (in x.y)
    def t1: C = new a.b.C()
                ^
A.scala:10: error: type mismatch;
 found   : a.b.C
 required: x.y.D
    def t2: D = new a.b.C()
                ^
A.scala:11: error: type mismatch;
 found   : x.y.D
 required: x.y.C
    def t3: C = new D()
                ^
A.scala:16: error: type mismatch;
 found   : x.y.D
 required: a.b.C
  val t1: a.b.C = new x.y.D()
                  ^
A.scala:17: error: type mismatch;
 found   : C (in x.y)
 required: C (in a.b)
  val t2: a.b.C = new x.y.C()
                  ^
5 errors
```

Scala 3 also prints full paths.

**Comment by mrdziuban** [comment]
@lrytz I don't have any reason not to, was just initially aiming for a solution that didn't change current behavior. Just pushed up a commit that updates the logic to always print the full qualified type, unless it's one of the `shorthands`, let me know if the updated test output looks how you'd expect

**Review by lrytz — APPROVED** [review]
This LGTM. @tek wdyt?

**Comment by tek** [comment]
no objections!

**Comment by SethTisue** [comment]
@mrdziuban can you update the PR title and description to match reality?

**Comment by mrdziuban** [comment]
@SethTisue updated!

**Pull request merged**
