### PR TITLE
Want a 25% partest speedup?*

### PR DESCRIPTION
**Pull request by VladUreche**
... well then, don't compile twice!

Explanation:
The compilation process in partest happens in 3 stages:
- scala + java files, all fed to scalac (so the java signatures are
  loaded and the scala bytecode is generated)
- java files, fed to javac (so the java bytecode is generated)
- scala files, fed to scalac (so the scala bytecode correctly links
  to the javac-generated bytecode)

While this mechanism is great to have, for simple 1-file scala tests
it's overkill by compiling scala files twice. So I adjusted the compile
procedure to only run the first step if java files are empty, leading
to a 25% partest speedup.*

Review by @paulp.

\* as measured on test.scaladoc

### CODE REVIEW

**Comment by VladUreche** [comment]
PLS REBUILD pr-scala-testsuite-linux-opt
(spurious faliure with the abstract annotation)

```
  [partest] testing: [...]/files/pos/t5165                                        [FAILED]
  [partest] TestTrait.scala:2: error: trait TestAnnotation is abstract; cannot be instantiated
  [partest] @TestAnnotation(one=TestAnnotation.TestEnumOne.A, two=TestAnnotation.TestEnumTwo.C, strVal="something")
  [partest]  ^
  [partest] one error found
```

**Comment by VladUreche** [comment]
Jenkins job aborted? Wassup with the scala kitteh, is it sick or sth?!?
PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by VladUreche** [comment]
@som-snytt: indeed, that was the original fix. But then I thought why create a closure, do foldLeft and all if we can just compile directly? 

If the consensus is to use !javaFiles.isEmpty, I can change it.

**Comment by jsuereth** [comment]
Hmmm, I don't see a LGTM and there seems to be concerns here.   I'll wait for an "official" LGTM

@odersky Are we going to support scala-once compilation?

**Comment by VladUreche** [comment]
The patch was discussed during the scala meeting, and Martin was the one who explained why there are three steps to compiling and pointed out that without java source code we can compile only once.

@paulp, does it look okay to you?

**Comment by jsuereth** [comment]
AH, gotcha.   Let's get this in then.

**Comment by paulp** [comment]
> But then I thought why create a closure, do foldLeft and all if we can just compile directly?

Because duplicating code for no reason is bad.  This is not some tight inner loop, it's one call per test out of billions.  If you really care about avoiding the closure, the method can be rewritten to do so, but I'm sure your time would be better spent elsewhere.

> If the consensus is to use !javaFiles.isEmpty, I can change it.

This will LGTM if it's that minimal diff.

**Comment by VladUreche** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Ok, this looks like a minimal diff now.   LGTM.

**Pull request merged**
