### PR TITLE
[backport] Fix for SI-6154, VerifyError originating in uncurry.

### PR DESCRIPTION
**Pull request by retronym**
Lhs still might be an Ident.  Miguel did all the work,
I just wrote it down in code form.
(cherry picked from commit 48f8235822a2a100d6c4e8d3d7349df565ac6d40)

Backport of #1021 

Review by @magarciaEPFL

### CODE REVIEW

**Comment by retronym** [comment]
Just ignore that failure:

```
  [partest] testing: [...]/files/run/t6987.scala                                  [FAILED]
  [partest] did not get the string expected, full results were:
  [partest] Fast Scala compiler version 2.10.1-20130129-191820-d3f3394fbd -- Copyright 2002-2013, LAMP/EPFL
  [partest] [Given arguments: -shutdown -verbose]
  [partest] [Transformed arguments: -shutdown -verbose -current-dir /localhome/jenkins/b/workspace/pr-scala-testsuite-linux-opt]
  [partest] [VM arguments: ]
  [partest] java.net.ConnectException: Connection refused
  [partest] [Connecting to compilation daemon at port 44936 failed; re-trying...]
  [partest] [No compilation server running.]
  [partest] 
```

**Comment by lrytz** [comment]
it seems to be failing quite often. should we revert 1dab5bf or just disable the test?

**Comment by retronym** [comment]
Seems like it was already disabled in master in #1985 , so let's backport that.

_EDIT_  Done https://github.com/scala/scala/pull/2010

**Comment by magarciaEPFL** [comment]
LGTM

**Pull request merged**
