### PR TITLE
Faster diagnostic for unimplemented method stubs

### LINKED ISSUE #12691: Compiler takes ages to emit errors for a simple large file
## Reproduction steps

Scala version: 2.13.10

The file to compile will be too large in whole, but it looks like this:

```scala
class Example {
  val f1: Int
  val f2: Int
  val f3: Int
  val f4: Int
  val f5: Int
  val f6: Int
  val f7: Int
  val f8: Int
  val f9: Int
// ...
}
```

You can generate the whole thing like this:

```
//> using scala "2.13.10"
import java.nio.file.Files
import java.nio.file.Paths

object demo extends App {

  //2^16 - 14 is the max amount of fields I could fit into a Java class
  val fields = (1 until (Math.pow(2, 16).toInt - 14))
    .map { i =>
      s"  val f$i: Int"
    }
    .mkString("\n")

  val fileText = s"""class Example {
                    |$fields
                    |}""".stripMargin

  Files.writeString(Paths.get("Example.scala"), fileText)
}
```

## Problem

scalac has been compiling this file for over 10 minutes on an M1 Max machine. javac deals with a Java counterpart in around a second.

## Extra info

Profiling the compiler shows me that the worst offenders are

```
scala.reflect.internal.Symbols$Symbol.needsFlatClasses()
scala.reflect.internal.Symbols$Symbol.name()
scala.reflect.internal.tpe.FindMembers$FindMembers.membersScope()
```

Here's a flame graph:

image

And a profiler sample (20 seconds should be enough?):

[Main_2022_11_12_171812.jfr.zip](https://github.com/scala/bug/files/9995397/Main_2022_11_12_171812.jfr.zip)

### PR DESCRIPTION
**Pull request by som-snytt**
Omit expensive help when there is too much help to give.

Fixes scala/bug#12691

### CODE REVIEW

**Comment by lrytz** [comment]
LGTM, but 3 MB in diff.. could we generate this at test-runtime, in memory or on disk?

**Comment by som-snytt** [comment]
Yes, I considered that but ran out of casual interest. My other concern was that it runs fast on command line and slower in partest, presumably for reasons of memory. I suspect there's not a good reason to the upper limit, so the test should test something else. It's nice that the existing test succeeds, within whatever the timeout is under CI, but that is crude.

Pragmatically, I also wondered if worrying about resources at this scale makes me sound old.

**Comment by som-snytt** [comment]
I'm changing the tests just to check the behavior below and above the limit (100 or whatever).

I notice that partest has a problem with the large check file, so there must be something suboptimal with diffing. (I've wanted to verify that the filtering etc isn't resource intensive, so I'll look at it now.)

```
"pool-2-thread-1" #23 [10926] prio=5 os_prio=0 cpu=36767.18ms elapsed=36.90s tid=0x00007f8750252040 nid=10926 runnable  [0x00007f878c9f9000]
   java.lang.Thread.State: RUNNABLE
        at scala.collection.StrictOptimizedLinearSeqOps.loop$2(LinearSeq.scala:274)
        at scala.collection.StrictOptimizedLinearSeqOps.drop(LinearSeq.scala:275)
        at scala.collection.StrictOptimizedLinearSeqOps.drop$(LinearSeq.scala:271)
        at scala.collection.immutable.List.drop(List.scala:79)
        at scala.collection.immutable.List.drop(List.scala:79)
        at scala.collection.LinearSeqOps.apply(LinearSeq.scala:130)
        at scala.collection.LinearSeqOps.apply$(LinearSeq.scala:128)
        at scala.collection.immutable.List.apply(List.scala:79)
        at scala.collection.convert.JavaCollectionWrappers$SeqWrapper.get(JavaCollectionWrappers.scala:93)
        at com.github.difflib.algorithm.myers.MeyersDiff.buildPath(MeyersDiff.java:115)
        at com.github.difflib.algorithm.myers.MeyersDiff.computeDiff(MeyersDiff.java:58)
        at com.github.difflib.DiffUtils.diff(DiffUtils.java:125)
        at com.github.difflib.DiffUtils.diff(DiffUtils.java:103)
        at com.github.difflib.DiffUtils.diff(DiffUtils.java:62)
        at scala.tools.partest.nest.FileManager$.compareContents(FileManager.scala:80)
        at scala.tools.partest.nest.Runner.currentDiff(Runner.scala:333)
        at scala.tools.partest.nest.Runner.diffIsOk(Runner.scala:399)
        at scala.tools.partest.nest.Runner.checked$1(Runner.scala:555)
        at scala.tools.partest.nest.Runner.$anonfun$runNegTest$3(Runner.scala:558)
        at scala.tools.partest.nest.Runner$$Lambda$963/0x00000008014196b8.apply(Unknown Source)
        at scala.Option.map(Option.scala:242)
        at scala.tools.partest.nest.Runner.$anonfun$runNegTest$1(Runner.scala:558)
        at scala.tools.partest.nest.Runner$$Lambda$141/0x00000008011276b0.apply(Unknown Source)
        at scala.tools.partest.nest.Runner.runInContext(Runner.scala:422)
        at scala.tools.partest.nest.Runner.runNegTest(Runner.scala:549)
        at scala.tools.partest.nest.Runner.run(Runner.scala:649)
```
Recall the diff
```
- val diffUtilsDep      = "com.googlecode.java-diff-utils" % "diffutils"                        % "1.3.0"
+ val diffUtilsDep      = "io.github.java-diff-utils"      % "java-diff-utils"                  % "4.11"
```

**Review by lrytz — APPROVED** [review]
👍

**Pull request merged**
