### PR TITLE
Switch off exhaustivity warnings for unsealed types (by default)

### PR DESCRIPTION
**Pull request by dwijnand**
Replaces `-Xno-unsealed-patmat-analysis` with `-Xlint:strict-unsealed-patmat`, so that you must opt-in if you want this strictness.

:(

However, at least by being in the Xlint family, it's on if you opt-in to `-Xlint`.

Reverts commit 0416c57a01a2b0feafc340893d64cd54ca7ae84c (w/ tweaks).

### CODE REVIEW

**Comment by dwijnand** [comment]
🤔 I'll fold this change into https://github.com/scala/scala/pull/9140, but perhaps this PR should be a link in the "exhaustivity" section of the release notes.

**Comment by retronym** [comment]
`patmat` is something of an insider's term for the pattern matcher compiler phase. How about something `strict-unsealed-patterns` instead? Sorry to 🚲 🏚️ ...

**Comment by dwijnand** [comment]
Sure.  We _do_ also have `-Xno-patmat-analysis`, `-Vpatmat`, `-Ypatmat-exhaust-depth`, `-Vstatistics:patmat`/`-Vprint:patmat`, but I guess `-Xlint` is even more general user-facing than those.

**Comment by retronym** [comment]
Hmmm.... let's leave it as is in this PR.

**Comment by SethTisue** [comment]
to repeat in public some points from our internal discussions:

Martin and Guillaume both expressed reservations about making this warn by default, for now anyway, especially since the changes to the pattern matcher are so new so we don't have much experience with them yet. Going forward, we'll want to coordinate with the Scala 3 team about any further changes to defaults (e.g. on https://contributors.scala-lang.org where others can weigh in as well).

Making it part of the `-Xlint` defaults seems like a  pretty good compromise in that just about anybody who cares about code quality should be using `-Xlint` and a great many people actually do, so this is still gives the new warnings fairly prominent placement, so we will probably still get good feedback from users this way.

Note also that over at https://github.com/scala/scala/pull/7525 @som-snytt is exploring ideas such as perhaps backporting Scala 3's `case` syntax for marking matches as might-fail.

**Comment by som-snytt** [comment]
`-Xlint` options are magical and obscure, but that is that status quo. Users are "expected" to take the defaults and opt-out if necessary.

The current option is `valpattern              Enable pattern checks in val definitions.` (I had to look it up in the help.) Maybe that is subsumed by the new options?

Also, `-Xsource:3` is likely underused. It enables some new features and also assumes something like `-source 3.1`. That is, IIUC it tries to be noisy about migration.

**Review by lrytz — APPROVED** [review]

**Comment by sjrd** [comment]
Could someone trigger an update of https://raw.githubusercontent.com/scala/community-builds/2.13.x/nightly.properties now that this PR has been merged, please? That would allow to restore our nightly-against-nightly build, to make sure we're not hitting something else among the recent changes.

**Comment by SethTisue** [comment]
~@sjrd that's already in flight at https://github.com/scala/community-build/pull/1284 — it’s nearly certain to cross the finish line in the next 1-2 days~

**Comment by SethTisue** [comment]
whoops, I got confused — 1284 is about project SHAs, not Scala SHAs. I made a new PR advancing the Scala SHA: https://github.com/scala/community-build/pull/1286

**Pull request merged**
