### PR TITLE
Move mapInPlace from mutable.SeqOps to mutable.IndexedSeqOps

### PR DESCRIPTION
**Pull request by julienrf**
Fixes scala/bug#10947

### CODE REVIEW

**Comment by julienrf** [comment]
Note that `mapInPlace` is still defined (though not anymore inherited from `mutable.SeqOps`) on `UnrolledBuffer`, `ListBuffer` and `JListWrapper`, whose implementations are O(n).

**Review by Ichoran — APPROVED** [review]
LGTM.  (It's a simple change--there isn't much else to say!)

**Review by szeiger — COMMENTED** [review]
Looks OK as far as the implementation goes but I don't think the solution is ideal. There ought to be a way to define a useful abstraction for LinearSeqs that allows an efficient implementation. And in cases where that doesn't work so well you could still override it.

**Comment by Ichoran** [comment]
@szeiger - For `LinearSeq` you need an editing iterator that can insert and remove elements as it traverses.  That works okay for lists, but `UnrolledBuffer` is a problem.

**Comment by szeiger** [comment]
@Ichoran for `mapInPlace` you only need to mutate the current element. This should be easy for any mutable Seq. I agree that in-place versions of operations like `filter` and `flatMap` would be difficult / inefficient for data structures like `UnrolledBuffer`.

**Comment by Ichoran** [comment]
Oh, right, this is only `mapInPlace`.  I'm not sure it's worth making a special iterator just for this?  But I guess

```
trait TransformingIterator[A] extends Iterator[A] {
  def transformNext(f: A => A): Boolean
}
```

would be one way to go.  But each collection would have to implement it.  I'm not entirely sure it's worth the maintenance burden.  (Could also have an argument `f: (A, A => ()) => ()` if the transformation should be optional.)

**Comment by szeiger** [comment]
I'd go for a more imperative style for flexibility and performance. Iterators are mutable anyway.

```scala
trait Mutator[A] extends Iterator[A] {
  /** Update the last element returned by `next`. No calls to other methods allowed in between. */
  def update(x: A): Unit
}
```

**Review by NthPortal — APPROVED** [review]
LGTM as well.

I like @szeiger's idea, and it may be worth exploring. I'm not sure whether or not it should hold up this PR, however; it's a much bigger change.

**Comment by Ichoran** [comment]
@szeiger - The `Mutator` requires a more finicky implementation for a lot of iterators, though I agree it would probably be faster.  The reason is that `next` right now often contains an advancing step, which would have to be refactored to a conditional-advance-later.  For instance, in the case of a mutable list, the obvious thing to do is follow the `next` pointer--but you then can't mutate the one you left.

It might be the better choice anyway.  I suggested the more-like-Java-Spliterator style to reduce implementation burden for people who had made their own `mutable.IndexedSeq`, but that might not be the right thing to optimize.

I also agree with @NthPortal that adding `Mutator` or somesuch shouldn't hold up _this_ PR.  It's not that hard to mostly-revert this change if we get `Mutator` or `TransformingIterator` in place and are satisfied with it.

**Pull request merged**
