### PR TITLE
SI-8335  List.++ avoidably burns memory

### PR DESCRIPTION
**Pull request by Ichoran**
Changed to check the identity of the CanBuildFrom instead of the identity of the generated builder to shortcut building.  Should reduce memory churn on ++ a little.

### CODE REVIEW

**Comment by adriaanm** [comment]
Nice. Did you check that `bf(this).isInstanceOf[ListBuffer[_]]` implies `bf eq List.ReusableCBF` for most/all `bf`?

**Comment by Ichoran** [comment]
I haven't done a full bytecode analysis, but I did not find any evidence in the library source that List.++ had any ListBuffer-producing cbfs aside from List.ReusableCBF.  In any case, if there are some they will de-optimize more than just this method.

**Comment by adriaanm** [comment]
Ok, sounds good.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
