### PR TITLE
SI-8764 fix return type of case class productElement under Xexperimental

### PR DESCRIPTION
**Pull request by gourlaysama**
Under `-Xexperimental`, `productElement` now returns the lub instead
of the weak lub of case class parameter types (numeric widening
shouldn't magically happen _inside_ `productElement`).

### CODE REVIEW

**Comment by gourlaysama** [comment]
review by @retronym :)

**Comment by som-snytt** [comment]
The test could be reduced to some asserts about TypeTags, no neg or check files.  Modulo the -X flag, it could be a junit test.

Also, it looks like most -Xexperimental tests are no longer (they were for virtpatmat, etc). A nice test linter could check that.  Similar to the problem with pending tests, you never know if they're still pending, and it's all bit rot.

I'd still like an example of what Paul meant in the code comment; it's too allusive for me.  That would be a pending test for whether this feature is ready for prime time.  If it's not experimental but really a niche -Y, you could decide that, too.

**Comment by gourlaysama** [comment]
Oh, right, I always forget about junit. I'll move that there then.

I wouldn't mind this moving out of `-Xexperimental`. It already does too many things that people might not actually want (`-Yinfer-argument-types`, `-Yoverride-objects`, `-Yoverride-vars`, SAMs, virtualized matches, experimental TypeVars and this). Someone that wants to enable SAMs should be able to do it without things breaking somewhere completely unrelated (maybe `-Xexperimental` should be turned into a MultiChoiceSetting).

**Comment by retronym** [comment]
We no longer attempt to make case classes extends `ProductN` (even experimentally). Maybe we should also revert, rather than tweak, the special casing of `productIterator` too.

These two features arrived together in e412524fee2. `ProductN` parentage was gradually disabled and removed through 70996f8, d7f498ac9cccd7473be8f416a1620548ca8fca9b, b7395e9f50 and 317a1056cd.

We would probably need to target that change against 2.12.x, though.

**Comment by som-snytt** [comment]
I wouldn't mind implementing multichoice -Xexperimental, as an opportunity to illustration the usage and maybe simplify and comment that code. Lukas is using it for -Ystats but I think it might break.

In any case, it would be nice if it were crystal-clear how multichoice generalizes. (It sounds like it should be obvious.)

On the Product case class, I was going to ask when is this even useful?  Answered.

**Comment by gourlaysama** [comment]
Ok, then if it is not useful, let's remove it. I opened a PR for 2.12.x: #3970

**Comment by gkossakowski** [comment]
Closing this PR given #3970 got merged. @gourlaysama, is this ok with you?

**Comment by gourlaysama** [comment]
@gkossakowski sure. Technically this could still be merged (with `[nomaster]`) to fix it for 2.11.x until it all goes away in 2.12, but maybe that's not useful...

**Comment by gkossakowski** [comment]
Yeah, given the fact you've spent the time implementing the fix, it makes sense to ship it. Reopening the PR. Please amend commit message and ping me.

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@e01b461

**Comment by gourlaysama** [comment]
@gkossakowski done :)

**Comment by gkossakowski** [comment]
LGTM!

Thanks a lot!

**Pull request merged**
