### PR TITLE
SI-6908 Makes FlatHashTable as well as derived classes support nulls

### PR DESCRIPTION
**Pull request by JamesIry**
This change adds a null sentinel object which is used to indicate that a null
value has been inserted in FlatHashTable. It also makes a strong distinction
between logical elements of the Set vs entries in the hash table. Changes
are made to mutable.HashSet and ParHashSet accordingly.

review by @adriaanm

### CODE REVIEW

**Comment by paulp** [comment]
It's pretty sad that there is this protected method "removeElem" which insists on allocating a Some and returning the removed element in it - which is then NEVER USED ANYWHERE. The only uses to which the return value are put are "isDefined" and tossing it aside. Given that object FlatHashTable is private[collection], it's pretty unlikely it does that for the benefit of code which is not in trunk.

**Comment by JamesIry** [comment]
That's hardly the saddest thing about this.

**Comment by paulp** [comment]
There can be many sad winners today.

**Comment by adriaanm** [comment]
I'm also in favor of changing removeElem's return type to Boolean based on @paulp's comment.
We're in master. We can do this kind of stuff.

**Comment by JamesIry** [comment]
removeElem as Boolean is totally worth doing, but unrelated to this change. Created https://issues.scala-lang.org/browse/SI-6916

**Comment by adriaanm** [comment]
LGTM

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Pull request merged**
