### PR TITLE
[nomerge] ensure forward/backward compatibility for SortedMap/Set

### PR DESCRIPTION
**Pull request by mkeskells**
WRT making RedBlackTree mutable

### CODE REVIEW

**Comment by lrytz** [comment]
Should we add this test to https://github.com/scala/scala/blob/2.12.x/test/files/run/t8549.scala? In 2.13.x, the test moved to JUnit (https://github.com/scala/scala/blob/2.13.x/test/junit/scala/SerializationStabilityTest.scala)

**Comment by SethTisue** [comment]
@mkeskells care to respond to Lukas's feedback?

**Comment by mkeskells** [comment]
> Should we add this test to https://github.com/scala/scala/blob/2.12.x/test/files/run/t8549.scala? In 2.13.x, the test moved to JUnit (https://github.com/scala/scala/blob/2.13.x/test/junit/scala/SerializationStabilityTest.scala)

Sorry for the late reply
Hallpy to move it - Should that be done only on 2.13 or on 2.12 as well?

**Comment by mkeskells** [comment]
> @mkeskells care to respond to Lukas's feedback?

Sorry for the late reply.
This PR is subsumed by https://github.com/scala/scala/pull/8794 which is not merged, so closing this one

**Comment by mkeskells** [comment]
subsumed bt https://github.com/scala/scala/pull/8794

**Pull request closed without merging**
