### PR TITLE
Merge master to 2.11.x

### PR DESCRIPTION
**Pull request by retronym**
```
% git show --oneline
972244d Merge pull request #3721 from lrytz/t7852

% export MB=$(git merge-base origin/2.11.x origin/master)

% git log --graph --oneline --decorate $MB..origin/master
*   b5392a0 (origin/master, origin/HEAD) Merge pull request #3704 from gourlaysama/wip/t8504
|\
| * c6b5028 (origin/pr/3704) SI-8504 fix NPE in the Java wrapper for a Scala Map.
*   6dd0a36 Merge pull request #3689 from xeno-by/ticket/8523
|\
| * 2d37cc0 (origin/pr/3689) makes bundles friendly to -Ywarn-dead-code
*   63b91bf Merge pull request #3706 from gourlaysama/wip/t8550
|\
| * b3243e8 (origin/pr/3706) SI-8550 fix scaladoc for the default s.c.LinearSeq.
*   a4e56ef Merge pull request #3711 from retronym/ticket/8549-2
|\
| * 2dbd269 (retronym/ticket/8549-2, origin/pr/3711) SI-6988 Test case for non-literal / non-constant SerialVersionUID
| * e7ab41e SI-8549 Enforce serialization stability for selected collections
| * ecbc9d0 SI-8549 Honour the @SerialVersionUID annotatation
*   e8ed2d2 Merge pull request #3703 from huitseeker/issue/SI-8537
|\
| * 8317266 (origin/pr/3703) SI-8537 Puts SI-8157 fix under Xsource
* e735cb3 Merge pull request #3576 from som-snytt/issue/8325
* b0fe135 (origin/pr/3576) SI-8325 Accept infix star type outside patterns

% git checkout -b merge/master-to-2.11.x
Switched to a new branch 'merge/master-to-2.11.x'

% git merge b5392a0
```

No conflicts

### CODE REVIEW

**Comment by retronym** [comment]
Review by @lrytz 

The build failure above is from a PR I merged that only touched Scaladoc that ran afoul of PR validation for reasons unknown.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@41f33d5

**Comment by retronym** [comment]
BUILDLOG?

**Comment by retronym** [comment]
The first attempt to [publish the core JARs](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-publish-core/2927/consoleText) to the private repository failed:

```
[artifact:deploy] Uploaded 4325K
[artifact:deploy] [INFO] Uploading project information for scala-reflect 2.11.1-b3243e8-20140430.194005-1
[artifact:deploy] [INFO] Retrieving previous metadata from pr-scala
[artifact:deploy] [INFO] Uploading repository metadata for: 'snapshot org.scala-lang:scala-reflect:2.11.1-b3243e8-SNAPSHOT'
[artifact:deploy] [INFO] Retrieving previous metadata from pr-scala
[artifact:deploy] [INFO] Uploading repository metadata for: 'artifact org.scala-lang:scala-reflect'
[artifact:deploy] [INFO] Retrieving previous build number from pr-scala
[artifact:deploy] Uploading: org/scala-lang/scala-reflect/2.11.1-b3243e8-SNAPSHOT/scala-reflect-2.11.1-b3243e8-20140430.194005-1-sources.jar to repository pr-scala at http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/
[artifact:deploy] Transferring 542K from pr-scala
[artifact:deploy] Uploaded 542K
     [echo] Deploying /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.1-b3243e8-SNAPSHOT/scala-compiler/scala-compiler-[pom.xml|src.jar|docs.jar].
     [copy] Copying 1 file to /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.1-b3243e8-SNAPSHOT/scala-compiler
[artifact:deploy] Deploying to http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/
[artifact:deploy] [INFO] Retrieving previous build number from pr-scala
[artifact:deploy] [INFO] repository metadata for: 'snapshot org.scala-lang:scala-compiler:2.11.1-b3243e8-SNAPSHOT' could not be found on repository: pr-scala, so will be created
[artifact:deploy] Uploading: org/scala-lang/scala-compiler/2.11.1-b3243e8-SNAPSHOT/scala-compiler-2.11.1-b3243e8-20140430.194005-1.jar to repository pr-scala at http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/
[artifact:deploy] Transferring 13338K from pr-scala
[artifact:deploy] Uploaded 13338K
[artifact:deploy] [INFO] Retrieving previous metadata from pr-scala
[artifact:deploy] [INFO] repository metadata for: 'snapshot org.scala-lang:scala-compiler:2.11.1-b3243e8-SNAPSHOT' could not be found on repository: pr-scala, so will be created
[artifact:deploy] [INFO] Uploading repository metadata for: 'snapshot org.scala-lang:scala-compiler:2.11.1-b3243e8-SNAPSHOT'
[artifact:deploy] [INFO] Retrieving previous metadata from pr-scala
[artifact:deploy] [INFO] Uploading repository metadata for: 'artifact org.scala-lang:scala-compiler'
[artifact:deploy] [INFO] Uploading project information for scala-compiler 2.11.1-b3243e8-20140430.194005-1
[artifact:deploy] [INFO] Retrieving previous build number from pr-scala
[artifact:deploy] Uploading: org/scala-lang/scala-compiler/2.11.1-b3243e8-SNAPSHOT/scala-compiler-2.11.1-b3243e8-20140430.194005-1-sources.jar to repository pr-scala at http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/
[artifact:deploy] Transferring 2031K from pr-scala
[artifact:deploy] Uploaded 2031K
     [echo] Deploying /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.1-b3243e8-SNAPSHOT/scala-actors/scala-actors-[pom.xml|src.jar|docs.jar].
     [copy] Copying 1 file to /localhome/jenkins/c/workspace/pr-scala-publish-core/scala/dists/maven/2.11.1-b3243e8-SNAPSHOT/scala-actors
[artifact:deploy] Deploying to http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/
[artifact:deploy] [INFO] Retrieving previous build number from pr-scala
[artifact:deploy] [INFO] repository metadata for: 'snapshot org.scala-lang:scala-actors:2.11.1-b3243e8-SNAPSHOT' could not be found on repository: pr-scala, so will be created
[artifact:deploy] Uploading: org/scala-lang/scala-actors/2.11.1-b3243e8-SNAPSHOT/scala-actors-2.11.1-b3243e8-20140430.194005-1.jar to repository pr-scala at http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/
[artifact:deploy] Transferring 463K from pr-scala
[artifact:deploy] Uploaded 463K
[artifact:deploy] [INFO] Uploading project information for scala-actors 2.11.1-b3243e8-20140430.194005-1
[artifact:deploy] [INFO] Retrieving previous metadata from pr-scala
[artifact:deploy] [INFO] Uploading repository metadata for: 'snapshot org.scala-lang:scala-actors:2.11.1-b3243e8-SNAPSHOT'
[artifact:deploy] An error has occurred while processing the Maven artifact tasks.
[artifact:deploy]  Diagnosis:
[artifact:deploy] 
[artifact:deploy] Error deploying artifact 'org.scala-lang:scala-actors:jar': Error installing artifact's metadata: Error while deploying metadata: Resource to deploy not found: File: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-actors/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml.md5 does not exist
```

The [subsequent rebuild](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-publish-core/2927/consoleText) then skipped this step, because _some_ of the JARs were published.

```
BUILD SUCCESSFUL
Total time: 14 seconds
>>> Checking availability of Scala 2.11.1-b3243e8-SNAPSHOT in http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/.
Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-library/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml
Downloading: https://moxie.typesafe.com:8497/nexus/content/groups/everything/org/scala-lang/scala-library/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml
Downloading: https://moxie.typesafe.com:8497/nexus/content/groups/everything/org/scala-lang/scala-library/2.11.1-b3243e8-SNAPSHOT/scala-library-2.11.1-b3243e8-20140430.194005-1.pom

Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-library/2.11.1-b3243e8-SNAPSHOT/scala-library-2.11.1-b3243e8-20140430.194005-1.pom
Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-library/2.11.1-b3243e8-SNAPSHOT/scala-library-2.11.1-b3243e8-20140430.194005-1.jar
----- org.scala-lang:scala-library:jar:2.11.1-b3243e8-SNAPSHOT found !
Downloading: https://moxie.typesafe.com:8497/nexus/content/groups/everything/org/scala-lang/scala-reflect/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml
Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-reflect/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml
Downloading: https://moxie.typesafe.com:8497/nexus/content/groups/everything/org/scala-lang/scala-reflect/2.11.1-b3243e8-SNAPSHOT/scala-reflect-2.11.1-b3243e8-20140430.194005-1.pom

Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-reflect/2.11.1-b3243e8-SNAPSHOT/scala-reflect-2.11.1-b3243e8-20140430.194005-1.pom
Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-reflect/2.11.1-b3243e8-SNAPSHOT/scala-reflect-2.11.1-b3243e8-20140430.194005-1.jar
----- org.scala-lang:scala-reflect:jar:2.11.1-b3243e8-SNAPSHOT found !
Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml
Downloading: https://moxie.typesafe.com:8497/nexus/content/groups/everything/org/scala-lang/scala-compiler/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml
Downloading: https://moxie.typesafe.com:8497/nexus/content/groups/everything/org/scala-lang/scala-compiler/2.11.1-b3243e8-SNAPSHOT/scala-compiler-2.11.1-b3243e8-20140430.194005-1.pom

Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.11.1-b3243e8-SNAPSHOT/scala-compiler-2.11.1-b3243e8-20140430.194005-1.pom
Downloading: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.11.1-b3243e8-SNAPSHOT/scala-compiler-2.11.1-b3243e8-20140430.194005-1.jar
----- org.scala-lang:scala-compiler:jar:2.11.1-b3243e8-SNAPSHOT found !
Scala core already built!
```

@adriaanm Advice?

**Comment by retronym** [comment]
I just re-pushed the merge commit with a new SHA to sidestep the caching problem. We'll see if we hit the same problem deploying `actors`.

**Comment by adriaanm** [comment]
I can also go to the repo and delete the artifacts if necessary.

**Comment by retronym** [comment]
I don't see that error in any other recent builds, FWIW.

```
% for i in {2800..2929}; do curl --silent https://scala-webapps.epfl.ch/jenkins/job/pr-scala-publish-core/$i/consoleText > $i.log; done/tmp/logs

%  ls
2800.log    2815.log    2830.log    2845.log    2860.log    2875.log    2890.log    2905.log    2920.log
2801.log    2816.log    2831.log    2846.log    2861.log    2876.log    2891.log    2906.log    2921.log
2802.log    2817.log    2832.log    2847.log    2862.log    2877.log    2892.log    2907.log    2922.log
2803.log    2818.log    2833.log    2848.log    2863.log    2878.log    2893.log    2908.log    2923.log
2804.log    2819.log    2834.log    2849.log    2864.log    2879.log    2894.log    2909.log    2924.log
2805.log    2820.log    2835.log    2850.log    2865.log    2880.log    2895.log    2910.log    2925.log
2806.log    2821.log    2836.log    2851.log    2866.log    2881.log    2896.log    2911.log    2926.log
2807.log    2822.log    2837.log    2852.log    2867.log    2882.log    2897.log    2912.log    2927.log
2808.log    2823.log    2838.log    2853.log    2868.log    2883.log    2898.log    2913.log    2928.log
2809.log    2824.log    2839.log    2854.log    2869.log    2884.log    2899.log    2914.log    2929.log
2810.log    2825.log    2840.log    2855.log    2870.log    2885.log    2900.log    2915.log
2811.log    2826.log    2841.log    2856.log    2871.log    2886.log    2901.log    2916.log
2812.log    2827.log    2842.log    2857.log    2872.log    2887.log    2902.log    2917.log
2813.log    2828.log    2843.log    2858.log    2873.log    2888.log    2903.log    2918.log
2814.log    2829.log    2844.log    2859.log    2874.log    2889.log    2904.log    2919.log

% grep "Error deploying artifact" *
2927.log:[artifact:deploy] Error deploying artifact 'org.scala-lang:scala-actors:jar': Error installing artifact's metadata: Error while deploying metadata: Resource to deploy not found: File: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-actors/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml.md5 does not exist
2927.log:/localhome/jenkins/c/workspace/pr-scala-publish-core/scala/build-ant-macros.xml:537: Error deploying artifact 'org.scala-lang:scala-actors:jar': Error installing artifact's metadata: Error while deploying metadata: Resource to deploy not found: File: http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/org/scala-lang/scala-actors/2.11.1-b3243e8-SNAPSHOT/maven-metadata.xml.md5 does not exist
```

Is that short circuit an optimization, or to avoid errors on double-publishing?

**Comment by adriaanm** [comment]
It's an optimization. Double-publishing should be allowed in this repo.

**Comment by adriaanm** [comment]
Hmm, or maybe it's rather _could_ be allowed.

**Comment by retronym** [comment]
This commit is effectively green; the merge commit passed validation. The history contains an unvalidated commit, which is somewhat oddly reflected in the overall status. That commit only touched Scaladoc, so I ignored the glitch in the build on that PR.

So review by @adriaanm, as he was last seen in the neighbourhood.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
