### PR TITLE
Remove notes about -doc-title and -doc-version not being used

### PR DESCRIPTION
**Pull request by janekdb**
Confirmed these options are used by editing build-ant-macros.xml and viewing
the output,

```
               <scaladoc docRootContent="${src.dir}/@{project}/${@{project}.docroot}"
                 destdir="${build-docs.dir}/@{project}"
-                doctitle="${@{project}.description}"
+                doctitle="${@{project}.description} - test-title"
                 docfooter="epfl"
-                docversion="${version.number}"
+                docversion="${version.number} - test-version"

```

### CODE REVIEW

**Comment by janekdb** [comment]
Review by @dickwall, @heathermiller .

**Comment by janekdb** [comment]
@adriaanm - This commit only changes comments. The build failure has these unit test failures in IDE,

https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-ide/1870/console

```
noAccessToPrivateThisOutsideOfInstance(org.scalaide.core.ui.completion.AccessibilityTests):
  There are expected completions that do not exist. expected:<[secretPrivate(): Unit

noAccessToPrivateInSubclass(org.scalaide.core.ui.completion.AccessibilityTests):
  There are expected completions that do not exist. expected:<[secretProtected(): Unit

accessToPrivateThisInsideOfInstance(org.scalaide.core.ui.completion.AccessibilityTests):
  There are expected completions that do not exist. expected:<[secretPrivate(): Unit

noAccessToPrivateInUnrelatedClass(org.scalaide.core.ui.completion.AccessibilityTests):
  There are expected completions that do not exist.
    expected:<[secretProtectedInPackage](): Unit>
    but was:<[protected[noAccessToPrivateInUnrelatedClass] secretProtectedInPackage(): Unit
```

**Comment by SethTisue** [comment]
@dragos?

**Comment by lrytz** [comment]
LGTM, thanks!

**Pull request merged**
