### PR TITLE
SI-10190 Elide string to empty instead of null

### PR DESCRIPTION
**Pull request by som-snytt**
Avoid NPE when eliding string-valued functions.

For example, `log(s"$cheap$expensive")` needn't print null.

This is a natural and inexpensive way to elide strings.

Also avoid using assert when testing elide-below.

### CODE REVIEW

**Comment by som-snytt** [comment]
You'd think any other ref type would be required to be `Option` and elide to `None`.

**Comment by Ichoran** [comment]
I'm not very fond of this idea.  In particular, it doesn't match the output of `"%s".format(null: String)`

**Comment by Ichoran** [comment]
(Sorry, I misunderstood what you meant.  Never mind!)

**Comment by lrytz** [comment]
sounds good to me

**Review by lrytz — APPROVED** [review]

**Pull request merged**
