### PR TITLE
kills resetAllAttrs

### PR DESCRIPTION
**Pull request by xeno-by**
review @retronym

### CODE REVIEW

**Comment by retronym** [comment]
Do calls to `resetAllAttrs` exist in any of the bigger open source projects you know of (shapeless, specs, scalatest, play, spire)? If so, we should proactively alert them to the change in RC1, so as to improve the changes of building the ecosystem.

**Comment by retronym** [comment]
@densh created a related ticket today: https://issues.scala-lang.org/browse/SI-8248

**Comment by xeno-by** [comment]
@retronym Yes, both the ticket and my PR resulted from our earlier discussion from Denys.

**Comment by retronym** [comment]
Could you please add the ticket number to the relevant commit(s)? Maybe just broaden the scope of that ticket to match this entire PR.

**Comment by xeno-by** [comment]
@retronym Not to the best of my knowledge. Also announced the change at https://twitter.com/xeno_by/status/431787958635855872 :)

**Comment by xeno-by** [comment]
@retronym Oh, there's actually https://github.com/xeno-by/specs2/blob/remove-warnings-for-2.11/matcher-extra/src/main/scala/org/specs2/matcher/MatcherMacros.scala#L133. /cc @etorreborre

**Comment by etorreborre** [comment]
So basically I should go for `resetLocalAttrs` with the upcoming RC1?

**Comment by xeno-by** [comment]
@etorreborre Yes. You could do that even in 2.10. `resetAllAttrs` shouldn't have been exposed in the first place, as `resetLocalAttrs` should be able to cover 99.99% of its use cases.

**Comment by retronym** [comment]
LGTM. Thank you for finally putting it to the sword!

**Pull request merged**
