### PR TITLE
Pullreq 1306

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
Review by @retronym, @xeno-by .

**Comment by xeno-by** [comment]
Heh, you beat my refactoring by 15 minutes. Okay, the ball's in your court now :)

**Comment by xeno-by** [comment]
I think `assocs` should be a `lazy val`. Other than that lgtm

**Comment by paulp** [comment]
Re: failed, I cleverly neglected to mention this was totally untested.  I'll lazyvalify and fix whatever I broke.

**Comment by paulp** [comment]
It failed because of this, which seems problematic:

```
scala> classOf[Array[_]].isArray
res0: Boolean = false
```

**Comment by xeno-by** [comment]
`classOf[Array[_]]` is `Object`, which makes sense, because `Object` is the best possible erasure here. But why did this lead to a test failure?

Btw if you don't have time to mess with this pull request, there's always mine (linked here in comments), which is also pretty cleaned up.

**Comment by paulp** [comment]
Actually it failed because this method takes an "Any" argument.

```
def arrayElementClass(schematic: Any): jClass[_]
```

...thus depriving me of the knowledge I was passing it the wrong thing.  It's why we invented types!

**Comment by paulp** [comment]
PLS REBUILD ALL

**Pull request merged**
