### PR TITLE
SI-7469 Remove @deprecated scala.util.logging

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @paulp, please.

**Comment by soc** [comment]
Argh.
Opinions on the following options?
- Make it private and move it to `scala.xml.logging` for now
- Remove the `log` stuff from the xml classes
- Move the "code" from the logging traits into the xml classes

**Comment by retronym** [comment]
I suggest to do the last of those three suggestions. Closing the PR in the meantime.

**Comment by soc** [comment]
@retronym Weird, I can't seem to reopen this PR, so here is a new one: https://github.com/scala/scala/pull/2543

**Pull request closed without merging**
