### PR TITLE
Fix for SI-6499, regression in type inference.

### PR DESCRIPTION
**Pull request by paulp**
I can't do any better than a reproduced comment:

For some reason which is still a bit fuzzy, we must let Nothing
through as a lower bound despite the fact that Nothing is always
a lower bound. My current supposition is that the side-effecting
type constraint accumulation mechanism depends on these subtype
tests being performed to make forward progress when there are
mutally recursive type vars. See pos/t6367 and pos/t6499 for the
competing test cases.

### CODE REVIEW

**Comment by paulp** [comment]
All I know is that it builds; I'll let kitteh run the tests.  Review (and penance, if there's any justice in the world) by @adriaanm .

**Comment by paulp** [comment]
Okay, tests passed for me.  (I see kitteh is awol.)

**Comment by adriaanm** [comment]
LGTM

(I'll do a couple of Rosemaries or something, but I was really just standing on the shoulders of giants here.)

**Comment by paulp** [comment]
"If I have seen less far than other men, it is because I am waist-deep in the footprints of giants."

**Comment by paulp** [comment]
Also, "Rosemary's Baby" would be more fitting.

**Comment by jsuereth** [comment]
JENKINS IS DOWN, THE KITTEH IS OUT CHASING MICE!

**Pull request merged**
