### PR TITLE
Saving symbol lookup from typedIdent.

### PR DESCRIPTION
**Pull request by paulp**
Anticipating the appeals to performance, I offer this coarse measurement. My times are the good ones. Better measurements are welcome, but I convinced myself at least that I wasn't hurting anything.

```
% for i in 1 2 3; do time scalac3 -J-Xmx1g -d $(mktemp -dt foo) $(find /scratch/trunk5/src/library/scala/collection/mutable -name '*.scala') ; done
28.139 real, 68.872 user, 1.186 sys
30.963 real, 70.071 user, 1.260 sys
29.741 real, 73.389 user, 1.249 sys
% for i in 1 2 3; do time ./pack-whats-in-a-name/bin/scalac -J-Xmx1g -d $(mktemp -dt foo) $(find /scratch/trunk5/src/library/scala/collection/mutable -name '*.scala') ; done
28.129 real, 68.396 user, 1.176 sys
27.571 real, 67.318 user, 1.081 sys
27.240 real, 66.336 user, 1.046 sys
```

Review by @odersky, @adriaanm.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Just for FYI: I was about test those changes for performance but I realized that before leaving Lausanne I was doing some refactoring of my performance infrastructure so I'd get better accuracy for my benchmarks. I changed how data is being produced but not how it's being analyzed. I need to fix it it will take a while :-(

**Comment by paulp** [comment]
Take all the time you need, as long as you won't stand in the way of progress. This gives every sign of being better in terms of performance, and that's its least attractive feature.

**Comment by paulp** [comment]
Has it really only been 5 days? Feels like 50. The amount of work involved in a patch like this is obscene. (Nothing like a few undiscovered pattern matcher bugs to liven things up, too.) I would like to merge it.

**Comment by adriaanm** [comment]
It wasn't a pattern matcher bug. I added a comment about why it failed last week: https://github.com/scala/scala/pull/1521#commitcomment-2048261

**Comment by paulp** [comment]
It was a pattern matcher bug in the ordinary sense that a) there was a pattern and b) I tried to match with it and c) it didn't do the right thing. "pattern matcher bug" is not to my knowledge an appellation which requires a formal entrance exam.

**Comment by adriaanm** [comment]
i believe the matcher's behaviour is as spec'ed. Those objects are actually different because the outer pointers are different.

**Comment by adriaanm** [comment]
the cast I quoted above, `localTyper.context1.asInstanceOf[d.Context]`, tricks the typechecker into believing  `d.Context =:= localTyper.context1.type`, so it'll let the match go through, but since the object you're matching on is created once per instance of Typer (and we have two different ones here: `d` and `localTyper`) you'll actually be comparing an apple (`d.LookupNotFound`) and an orange (`localTyper.LookupNotFound`)

**Comment by paulp** [comment]
Okay, then why does the case class match? Shouldn't d.LookupNotFound() and localTyper.LookupNotFound() also be from different fruit bins?

**Comment by adriaanm** [comment]
I'm going to say because the outer pointer cannot be tested, but it's a good question and I should find out.

**Comment by adriaanm** [comment]
the green bytecode from https://github.com/scala/scala/pull/1521#commitcomment-2042571 seems to support my hypothesis

Trying to figure out why the fruits are on different trees now.

**Comment by paulp** [comment]
When can and cannot the outer pointer be tested, exactly? Should I now expect that moving a block of code between files without changing it or touching the visible semantics might start cases to start matching or stop matching? Have we considered what a bad idea this is?

Proposal: warn 100% of the time if a case would have matched, but does not due to the outer pointer check. Frequency with which this warning will be spurious noise: 0.1%. Frequency with which it will catch deadly silent not-matches where it was never intended that there be multiple "families" of some class: 99.9%. (I would like to meet the programmers for whom the outer pointer test is an intentional element of their design upon which correctness depends... because I have seen the old pattern matcher from the inside.)

**Comment by adriaanm** [comment]
Well, testing outer pointers has always been part of the spec. It was poorly implemented, but it is required for type soundness. Types selected on different prefixes should not be treated equal.

It is unfortunate that we cannot always test outer pointers (which was recently made harder by https://github.com/scala/scala/pull/954).

**Comment by adriaanm** [comment]
That said, the type system will not even let you compare those classes unless you sneakily cast the prefix to something it is not.

**Comment by paulp** [comment]
Down comes the house of cards! https://issues.scala-lang.org/browse/SI-6583

**Comment by adriaanm** [comment]
PLS REBUILD ALL 

(it seems it wasn't triggered on the last commit -- just to be sure...)

**Pull request merged**
