### PR TITLE
TrieMapIterator's advance should be private.

### PR DESCRIPTION
**Pull request by takayahilton**

### CODE REVIEW

**Comment by lrytz** [comment]
We probably cannot do this in a minor release due to binary compatibility. If it was a very serious issue we might make an exception, but in this case I think we should just do it in 2.14.

**Comment by takayahilton** [comment]
I understood it.

**Comment by lrytz** [comment]
We don't have a 2.14.x branch yet, unfortunately.. I'll put it on my todo list for the time when we create one. Thanks, @takayahilton!

**Comment by SethTisue** [comment]
> We don't have a 2.14.x branch yet, unfortunately 

for context on this, see scala/scala-dev#661

**Pull request closed without merging**
