### PR TITLE
SI-9045 Error on recursive ctor

### PR DESCRIPTION
**Pull request by som-snytt**
If the constructor invokes itself, say so.

### CODE REVIEW

**Comment by som-snytt** [comment]
Review by @janekdb who has the knack.

**Comment by soc** [comment]
(LGTM)

**Comment by janekdb** [comment]
With the caveat that `Typers` and `ContextErrors` were unfamiliar to me prior to this, this 4-point check
- improved error message matching the requirement
- the reduced `if` nesting (nice)
- appropriate location of the `ConstructorRecursesError` def
- covering tests

and @soc's parenthetical level of support compel me to go LGTM.

**Comment by janekdb** [comment]
LGTM

**Pull request merged**
