### PR TITLE
SI-6488 Interrupt i/o threads on process destroy

### PR DESCRIPTION
**Pull request by som-snytt**
The previous fix uses Thread.stop, but should do something orderly.

This commit interrupts the threads, which must check isInterrupted
before attempting further i/o.

Similarly, i/o handlers must preserve and communicate interrupted
status; see the test.

There was a recent ML thread on whether there is a judicious use of stop.

In this case, the process code owns the threads performing the reads, but also invoke arbitrary callbacks.

One could argue that the callbacks are arbitrary and this might be a Coursera exercise so use stop, or inversely, don't stop arbitrary callbacks; or stop if the thread is still alive after some period.

### CODE REVIEW

**Comment by soc** [comment]
> The previous fix uses Thread.destroy [...]

That's guaranteed to fail 100% of the time, because it has never been implemented. All implementations I have ever seen throw a `NoSuchMethodError`.

**Comment by som-snytt** [comment]
I misspoke.  I had destroy on the brain.  I'll correct it to "stop".

**Comment by soc** [comment]
What happened to this pull request?

**Comment by som-snytt** [comment]
Just stewing a bit.

**Comment by soc** [comment]
Alright, this seems to have a become a fashion lately. :-)

**Comment by som-snytt** [comment]
Updated to reflect lame comment by @som-snytt.

Thread is interrupted tout court, no waiting, and i/o thread ignores both interrupted and i/o exception (if interrupted).

**Comment by som-snytt** [comment]
Since the PR has picked up various other commits like burrs when I rebased, I'll close this and try, try again.

**Pull request closed without merging**
