### PR TITLE
new bytecode emitter, GenBCode (8th attempt)

### PR DESCRIPTION
**Pull request by magarciaEPFL**
This PR re-submission supersedes https://github.com/scala/scala/pull/2529 and takes into account review comments so far. 

Testing against the community build will provide more information than isolated tests.
Bytecode tests are by their very nature fragile (e.g., testing first that pattern matching emits a chain of jumps, only to make sure a moment later that chain of jumps has been collapsed by GenBCode). Concrete ideas and examples on how to balance usefulness vs brittleness are welcome.

Reviews about the content proper of the PR are most welcome.

review by @gkossakowski or @JamesIry or @retronym or @paulp

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
Regarding SI-6720.

SI-6720 isn't a compiler bug as such but rather a VM bug, which moreover doesn't occur anymore in the latest version of Oracle JDK 7. Thus I'm calling it a VM bug confined to early releases of Oracle JDK 7, which is why the workaround for SI-6720 isn't carried over from the previous PR. We still can decide to bring back that "fix" for SI-6720 into GenBCode, but in that case a "fix" should also be included for GenASM.

**Comment by magarciaEPFL** [comment]
Regarding building with the new backend.

This PR doesn't add Ant tasks for GenBCode, for now the procedure is manual.
Moreover, the nightly build gets really interesting when using the new optimizer.
To run that build, currently one needs to look into upcoming PRs, ie 

  https://github.com/magarciaEPFL/scala/compare/master...GenRefactored56

On that branch the new backend is activated by default, and it only remains to change `build.xml`:

``` diff
-   <antcall target="@{name}"><param name="scalac.args.optimise" value="-optimise"/></antcall>
+   <antcall target="@{name}"><param name="scalac.args.optimise" value="-neo:o3"/></antcall>
```

Followed by

```
ant all.clean && ant && ant replacelocker && ant nightly
```

**Comment by magarciaEPFL** [comment]
The test failure above is due to:

```
  [partest] !! 18 - presentation/implicit-member              [output differs]
```

In detail:

```
% diff /localhome/jenkins/a/workspace/pr-checkin-per-commit/test/files/presentation/implicit-member-presentation.log /localhome/jenkins/a/workspace/pr-checkin-per-commit/test/files/presentation/implicit-member.check
@@ -15,7 +15,7 @@ def formatted(fmtstr: String): String
 def hashCode(): Int
 def toString(): String
 def →[B](y: B): (Implicit.type, B)
-final class AppliedImplicit[A] extends AnyRef
+final class AppliedImplicit[A <: <?>] extends AnyRef
 final def !=(x$1: Any): Boolean
 final def !=(x$1: AnyRef): Boolean
 final def ##(): Int
```

**Comment by retronym** [comment]
That test has been flaky recently. We should move it to `disabled` and address the non-determinism.

**Pull request closed without merging**
