### PR TITLE
Cleaning up the implicits in the reflection api

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
Review by @xeno-by, @adriaanm

**Comment by soc** [comment]
Is the removal of the documentation intentional?

**Comment by paulp** [comment]
No, I slipped and accidentally deleted 500 lines. Come on.

**Comment by paulp** [comment]
I do not see how that can be considered documentation in any case. For one thing, nobody is going to discover the need for implicit tags by looking for implicit tags. It's the pattern matcher which somehow must communicate this.

**Comment by paulp** [comment]
It seems due to https://issues.scala-lang.org/browse/SI-7348 this will not work. Sigh. Dropping the commit which does the thing I was actually after.

**Pull request closed without merging**
