### PR TITLE
Deprecate maven deploy

### PR DESCRIPTION
**Pull request by adriaanm**
Set the scene for `src/build/maven-deploy.xml` aka `dists/maven/latest/build.xml`'s timely demise.

For a while now, you can just call `ant publish` to publish a build (or `ant build-opt publish` for an optimized build).

From now on, `ant nightly` also publishes, so that our jenkins set up is vastly simplified.

/cc @cunei as dbuild relies on this
/cc @huitseeker / @skyluc for the impact on uber-build

as soon as these two dependencies are removed, the duplicated maven-deploy.xml will be removed.

review by @soc please (See, I promised test.continuations.suite would be gone soon :-))

### CODE REVIEW

**Comment by adriaanm** [comment]
I verified scala/jenkins-config and scala/jenkins-scripts don't rely on the deprecated behavior anymore.
Once this is merged, the scala-nightly-publish jenkins job should just do nothing (can't remove it because the nightly jobs are run in the same way for all branches)

**Comment by adriaanm** [comment]
I </3 xml.

**Comment by cunei** [comment]
dbuild currently needs the targets `distpack-maven-opt` and `deploy.local`. The latter is being deprecated in this pull request, with `publish.local` as a replacement.
I will need some way to determine whether to invoke the old `deploy.local`, or the new `publish.local`, but in ant there seemingly is no straightforward manner to determine (from a command line ant) whether a target exists or not. If I invoke new target regardless, then cannot distinguish between an error due to the target non being there vs the target just failing. So, if `deploy.local` is removed, I'm sort of stuck. Can we possibly preserve `deploy.local` as an alias for `publish.local`, moving forward?

**Comment by adriaanm** [comment]
(for the record, we discussed using ant -p to detect the available targets; when target `publish-local` exists, it's all you need to publish)

**Comment by adriaanm** [comment]
Incorporating this in my other PR.

**Pull request closed without merging**
