### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by kiritsuku**
This fixes compilation errors about adapted argument lists and
a type error between CharSequence and String

---

I have no idea how the type error between CharSequence and String happened. Compiling it in the IDE doesn't work whereas on the command line everything is ok.

### CODE REVIEW

**Comment by adriaanm** [comment]
#3260 deprecated () insertion, maybe you somehow enabled that in the IDE and not on the command line?

**Comment by kiritsuku** [comment]
I don't mean the deprecated () but the missing toString call.

**Comment by som-snytt** [comment]
In the package object session there's

```
private[interpreter] implicit def charSequenceFix(x: CharSequence): String = x.toString
```

**Comment by adriaanm** [comment]
Review by @gkossakowski

**Comment by gkossakowski** [comment]
@sschaef: I'm confused what kind of compilation errors does this fix and for which project?

**Comment by kiritsuku** [comment]
The () insertion fixes Xlint errors in 2.11. For the other one I don't understand why the implicit conversion is not found. The IDE is broken at the moment, I can't investigate further.

I'm closing this until I found out why the latter fails.

**Pull request closed without merging**
