### PR TITLE
SI-8460 Fix regression in implicit divergence recovery

### PR DESCRIPTION
**Pull request by retronym**
Review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
Shapeless 1.2.4 before:

```
(remotes/origin/shapeless-1.2.4-scala-2.11.x) ~/code/shapeless sbt test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
[info] Loading global plugins from /Users/jason/.sbt/0.13/plugins
[info] Loading project definition from /Users/jason/code/shapeless/project
[info] Set current project to shapeless (in build file:/Users/jason/code/shapeless/)
[info] Updating {file:/Users/jason/code/shapeless/}shapeless...
[info] Updating {file:/Users/jason/code/shapeless/}shapeless-core...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-library;2.11.0-RC3 ...
[info] Updating {file:/Users/jason/code/shapeless/}shapeless-examples...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[info] Resolving com.novocode#junit-interface;0.7 ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for shapeless/test:test
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[info] Compiling 24 Scala sources to /Users/jason/code/shapeless/core/target/scala-2.11.0-RC3/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.0-RC3. Compiling...
[info]   Compilation completed in 10.371 s
[info] Compiling 23 Scala sources to /Users/jason/code/shapeless/examples/target/scala-2.11.0-RC3/classes...
[info] Compiling 14 Scala sources to /Users/jason/code/shapeless/core/target/scala-2.11.0-RC3/test-classes...
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/deepsearch.scala:77: diverging implicit expansion for type shapeless.examples.DeepSearchExamples.Searchable[shapeless.::[String,shapeless.::[String,shapeless.::[(String, String),shapeless.HNil]]],String]
[error] starting with method hlistishSearchable in object DeepSearchExamples
[error]   assert(("yes", "maybe", ("no", "why")).deepFind(p) == Some("no"))
[error]                                                  ^
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/deepsearch.scala:78: diverging implicit expansion for type shapeless.examples.DeepSearchExamples.Searchable[shapeless.::[String,shapeless.::[(String, String),shapeless.::[String,shapeless.HNil]]],String]
[error] starting with method hlistishSearchable in object DeepSearchExamples
[error]   assert(("a", ("b", "c"), "d").deepFind(p) == None)
[error]                                         ^
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/deepsearch.scala:81: diverging implicit expansion for type shapeless.examples.DeepSearchExamples.Searchable[shapeless.::[Int,shapeless.::[String,shapeless.::[(Symbol, Char),shapeless.HNil]]],String]
[error] starting with method hlistishSearchable in object DeepSearchExamples
[error]   assert((1, "two", ('three, '4')).deepFind(p) == Some("two"))
[error]                                            ^
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/deepsearch.scala:84: diverging implicit expansion for type shapeless.examples.DeepSearchExamples.Searchable[shapeless.::[Int,shapeless.::[String,shapeless.::[(Symbol, Char),shapeless.HNil]]],Char]
[error] starting with method hlistishSearchable in object DeepSearchExamples
[error]   assert((1, "two", ('three, '4')).deepFind((_: Char) == 52) == Some('4'))
[error]                                            ^
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/deepsearch.scala:93: diverging implicit expansion for type shapeless.examples.DeepSearchExamples.Searchable[shapeless.::[String,shapeless.::[String,shapeless.::[List[String],shapeless.HNil]]],String]
[error] starting with method hlistishSearchable in object DeepSearchExamples
[error]   assert(Foo("four", "three", List("two", "one")).deepFind(p) == Some("two"))
[error]                                                           ^
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/deepsearch.scala:94: diverging implicit expansion for type shapeless.examples.DeepSearchExamples.Searchable[shapeless.::[String,shapeless.::[String,shapeless.::[List[String],shapeless.HNil]]],String]
[error] starting with method hlistishSearchable in object DeepSearchExamples
[error]   assert(Foo("a", "b", "c" :: Nil).deepFind(p) == None)
[error]                                            ^
[warn] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/kindpoly.scala:49: Adaptation of argument list by inserting () has been deprecated: this is unlikely to be what you want.
[warn]         signature: ArrowAssoc.->[B](y: B): (A, B)
[warn]   given arguments: <none>
[warn]  after adaptation: ArrowAssoc.->((): Unit)
[warn]   sameTypeCtor(Map(23 -> "foo"), Map(true -> ()))
[warn]                                           ^
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/ordering.scala:37: diverging implicit expansion for type Ordering[shapeless.::[Int,shapeless.::[String,shapeless.HNil]]]
[error] starting with method hlistIsoOrdering in object OrderingExamples
[error]   implicitly[Ordering[Int :: String :: HNil]]
[error]             ^
[error] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/ordering.scala:58: diverging implicit expansion for type Ordering[shapeless.examples.OrderingExamples.Foo]
[error] starting with method hlistIsoOrdering in object OrderingExamples
[error]   implicitly[Ordering[Foo]]
[error]             ^
[warn] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/staging.scala:111: inferred existential type mirror.universe.Expr[String] forSome { val mirror: reflect.runtime.universe.Mirror }, which cannot be expressed by wildcards,  should be enabled
[warn] by making the implicit value scala.language.existentials visible.
[warn] This can be achieved by adding the import clause 'import scala.language.existentials'
[warn] or by setting the compiler option -language:existentials.
[warn] See the Scala docs for value scala.language.existentials for a discussion
[warn] why the feature should be explicitly enabled.
[warn]     val consumeExpr = mkExpr[String](currentMirror)(consumeTree)
[warn]                                                    ^
[warn] two warnings found
[error] 8 errors found
[info] Passed: Total 84, Failed 0, Errors 0, Passed 84
[error] (shapeless-examples/compile:compile) Compilation failed
[error] Total time: 65 s, completed Mar 31, 2014 11:53:13 AM
```

After:

```
(remotes/origin/shapeless-1.2.4-scala-2.11.x) ~/code/shapeless sbt -scala-home /code/scala/build/pack test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
[info] Loading global plugins from /Users/jason/.sbt/0.13/plugins
[info] Loading project definition from /Users/jason/code/shapeless/project
[info] Set current project to shapeless (in build file:/Users/jason/code/shapeless/)
[info] Defining */*:scalaHome
[info] The new value will be used by shapeless-core/*:allDependencies, shapeless-core/*:ivyConfigurations and 18 others.
[info]  Run `last` for details.
[info] Reapplying settings...
[info] Set current project to shapeless (in build file:/Users/jason/code/shapeless/)
[info] Updating {file:/Users/jason/code/shapeless/}shapeless-core...
[info] Updating {file:/Users/jason/code/shapeless/}shapeless...
[info] Resolving org.scala-tools.testing#test-interface;0.5 ...
[info] Done updating.
[info] Updating {file:/Users/jason/code/shapeless/}shapeless-examples...
[info] Done updating.
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11.0-RC3;1.0.1 ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for shapeless/test:test
[info] Resolving org.scala-tools.testing#test-interface;0.5 ...
[info] Done updating.
[info] Compiling 24 Scala sources to /Users/jason/code/shapeless/core/target/scala-2.11.0-RC3/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.0-20140331-114354-f65ec9a0e9. Compiling...
[info]   Compilation completed in 10.13 s
[info] Compiling 23 Scala sources to /Users/jason/code/shapeless/examples/target/scala-2.11.0-RC3/classes...
[info] Compiling 14 Scala sources to /Users/jason/code/shapeless/core/target/scala-2.11.0-RC3/test-classes...
[warn] /Users/jason/code/shapeless/examples/src/main/scala/shapeless/examples/kindpoly.scala:49: Adaptation of argument list by inserting () has been deprecated: this is unlikely to be what you want.
...
[warn] 30 warnings found
[info] Compiling 1 Scala source to /Users/jason/code/shapeless/examples/target/scala-2.11.0-RC3/test-classes...
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[info] Passed: Total 84, Failed 0, Errors 0, Passed 84
[success] Total time: 66 s, completed Mar 31, 2014 11:54:58 AM
```

**Comment by retronym** [comment]
"dbuildin, across the universe": https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/9/console

**Comment by densh** [comment]
Wow, excellent achievement!

**Comment by gkossakowski** [comment]
@retronym: excellent work!

**Comment by retronym** [comment]
The Travis CI failure is spurious, see #3668

**Comment by retronym** [comment]
The failure in `neg/t2031.scala` is legit. It's cycling.

**Comment by adriaanm** [comment]
[EDIT: nevermind -- Could we fix that by filtering DivergentImplicitTypeError errors out of the buffer instead of flushing it?
Trying that now.]

**Comment by adriaanm** [comment]
@retronym, how about this:

``` patch
diff --git i/src/compiler/scala/tools/nsc/typechecker/Implicits.scala w/src/compiler/scala/tools/nsc/typechecker/Implicits.scala
index 8d9ccbfbd1..3e4bd9586b 100644
--- i/src/compiler/scala/tools/nsc/typechecker/Implicits.scala
+++ w/src/compiler/scala/tools/nsc/typechecker/Implicits.scala
@@ -839,6 +839,9 @@ trait Implicits {
           if (divergentError.isEmpty) divergentError = Some(err)
         }

+        def savedDivergentError(other: DivergentImplicitTypeError) =
+          divergentError exists (err => err eq other)
+
         def issueSavedDivergentError() {
           divergentError foreach (err => context.issue(err))
         }
@@ -883,16 +886,20 @@ trait Implicits {
         case Nil      => acc
         case i :: is  =>
           val typedImplicitResult = typedImplicit(i, ptChecked = true, isLocalToCallsite)
-          // We don't want errors that occur during checking implicit info
-          // to influence the check of further infos. But we do need to pass the errors
-          // to `DivergentImplicitRecovery` so that it can note `DivergentImplicitTypeError` that is
-          // being propagated from a nested implicit search; this will be re-issued if this level
-          // of the search fails.
-          val recoveredResult = DivergentImplicitRecovery(typedImplicitResult, i, context.flushAndReturnBuffer())
+          // Pass the errors to `DivergentImplicitRecovery` so that it can note the first `DivergentImplicitTypeError`
+          // that is being propagated from a nested implicit search;
+          // this one will be re-issued if this level of the search fails.
+          val recoveredResult = DivergentImplicitRecovery(typedImplicitResult, i, context.errors)
           recoveredResult match {
             case sr if sr.isDivergent =>
               Nil
             case sr if sr.isFailure =>
+              // We don't want errors that occur during checking implicit info
+              // to influence the check of further infos, but we should retain divergent implicit errors
+              // (except for the one we already squirreled away)
+              context.reportBuffer.retainErrors {
+                case err: DivergentImplicitTypeError => !DivergentImplicitRecovery.savedDivergentError(err)
+              }
               rankImplicits(is, acc)
             case newBest        =>
               best = newBest
```

**Comment by adriaanm** [comment]
The new pos/ test still compiles and the old neg/ test terminates. That's about all the evidence I have....

**Comment by milessabin** [comment]
Belated thanks ... much appreciated :-)

**Comment by retronym** [comment]
@milessabin Turns out this patch doesn't actually retain 2.10 behaviour for shapeless-examples.

I traced through what was happening in `DeepSearchExample`, and determined that the implicit search indeed was divergent, and that 2.10 was at fault.

In this commit, I show how to guide the search away from divergence for an example that captures the essense of `DeepSearchExample`: https://github.com/retronym/scala/commit/638fa4741473f02cf19c6ab3d42dbc1ec83a0c93

**Comment by milessabin** [comment]
Yes, it appears I had made a similar change on the shapeless 2.0.0/Scala 2.11.x branch quite some time ago and backported to shapeless/master for Scala 2.10.x for consistency.

**Pull request closed without merging**
