### PR TITLE
Fix version to be the first word.

### PR DESCRIPTION
**Pull request by vigdorchik**
Current scheme doesn't work (because the files don't contain jar_name?).

### CODE REVIEW

**Comment by gkossakowski** [comment]
I believe the description is insufficient to really see what this change does. What's broken, how this is going to be fixed? What caused you to look into this file?

**Comment by vigdorchik** [comment]
Sorry for not wording it at full.
I installed a clean scala repo. As a part of initial building I had to pull artifacts from typesafe artifactory.
This failed for me. When I debugged the problem, I got to this place in shell file. As I understand, it gets the version from the desired.sha file. Currently it does so by stripping off jar name from the contents of the file. The problem is that such file doesn't contain jar_name directly, but has a '*' prefix. Instead I just use the first word as a version string.

**Comment by jsuereth** [comment]
That seems to be a fundamental difference in how your SHA files are generated vs. mine.  Can you point me at a SHA file that uses the \* instead of ? in it?   I need to find out who committed that and what they use to genreeate SHA files.   That's a serious issue of compatibility across platforms.   This will fix the issue temporarily and break it long term.

**Comment by jsuereth** [comment]
Also, when making "build" patches, please mark me as reviewer using:  review by @jsuereth

**Comment by vigdorchik** [comment]
@jsuereth For instance in lib/fjbg.jar.desired.sha1 I see:
8acc87f222210b4a5eb2675477602fc1759e7684 *fjbg.jar
BTW I use cygwin to build if it matters.

Regardless, I think my change that gets the first word is safe and less fragile.
I'll mark you as the reviewer in the future, sorry for not doing it this time.

**Comment by jsuereth** [comment]
It's cool.  Give me a bit to dig in.  I have a few other higher priority bugs.   If it's less fragile I want it.  It appears cygwin, mac (posix) and linux (gnu) differ in their `sha1sum -p` implementations.  Yay.

**Comment by jsuereth** [comment]
Ok, it appears we have a misbehaving OS somewhere that's putting \* instead of ?.  I'll fix the SBT buld appropriately too.  I wanted to keep that jarname in there for validation that the SHA file is really correct, but oh well.

LGTM.

**Pull request merged**
