### PR TITLE
Fixing small doc. typo in PartialFunction.scala

### PR DESCRIPTION
**Pull request by igormoreno**
Fixing a one-letter typo in the documentation of PartialFunction.scala (from "an plain" to "a plain").

### CODE REVIEW

**Comment by igormoreno** [comment]
It just occur to me that I probably shouldn't have made a pull request straight to "master" but rather to another branch, right?

**Comment by soc** [comment]
Probably against 2.10.x ... but let's see what those in charge have to say.

**Comment by igormoreno** [comment]
I'm sorry. I can do it against the other branch. Is there a way to cancel this pull request?

**Comment by paulp** [comment]
It's always better to target the older branch with documentation patches if what is being fixed is in both branches, because the merge river flows from older to newer.

**Comment by igormoreno** [comment]
ok. which branch would it be better to modify? should i create another pull request using a different branch?

**Comment by soc** [comment]
@igormoreno Yes, just rebase your changes against 2.10.x and create a new pull request. trunk merges changes from the 2.10.x branch periodically.

**Pull request closed without merging**
