### PR TITLE
SI-6381 Honour -Yrangepos in the REPL

### PR DESCRIPTION
**Pull request by retronym**
The motivation for this, aside from simple consistency, is to make range positions a little more accessible for macro tinkerers.

I wasn't able to find any prior discussion about why this needs to be an option at all, ie why we can't have range positions all the time. Performance? Robustness?

This is a followup to #1307, which applied the same fix to the Ant tasks.

Review by @paulp or @hubertp

### CODE REVIEW

**Comment by hubertp** [comment]
Paul implemented that some time ago. I cannot find relevant discussion nor branch atm but Martin stopped it due to perf.

**Comment by retronym** [comment]
I guess this was the start of the discussion:

https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/H-ROUV5jg4I

**Comment by paulp** [comment]
You missed the obvious google!

```
"range positions" "paul phillips"
```

**Comment by paulp** [comment]
I just never came back to it.  I'm sure it could be finished.  There's a lot of work in there somewhere.

**Comment by paulp** [comment]
Oh, but turning them on for the repl only is a no-brainer.  LGTM.

**Pull request merged**
