### PR TITLE
SI-6488: Fix for race with open I/O fds

### PR DESCRIPTION
**Pull request by possiblywrong**
Unless the I/O threads for error and output are closed prior to Process.destroy() there is a potential race condition that ends in the I/O threads raising an IOException.

### CODE REVIEW

**Comment by jsuereth** [comment]
Three questions:

(1) have you signed the scala cla?
(2) can you target this at 2.10.x
(3) can you include a small test case

The code looks good, but I need that test case to prevent regression.

**Comment by adriaanm** [comment]
closing for lack of progress 

@possiblywrong, please re-open or resubmit after addressing the review comments

**Comment by possiblywrong** [comment]
(1) Signed and submitted, it was delayed going through my employer's legal process, hence the lack of apparent progress.
(2) Can do, but should I resubmit the patch & test against master or 2.10.x? or do you mean change the fix version in SI-6488?
(3) Someone needs to give me a pointer to where in the mass of tests I should best put a test case. It's really not that obvious.

**Comment by adriaanm** [comment]
Thanks! Resubmitting against the 2.10.x branch would be perfect.
Tests that need to run go under test/files/run -- you need a t6488.scala with a Test object that has a main method,
and t6488.check (the latter contains the expected output of running the former).

The original repro for the issue is not a good test as it take 10s. We have a lot of tests to run, so each should be as fast as possible (and deterministic of course).

**Pull request closed without merging**
