### PR TITLE
SI-5513: add inplace set-theoretic operations for mutable bitsets.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @JamesIry

**Comment by JamesIry** [comment]
The same operations logically make sense for all mutable Sets. So a better design might be to have a default impl on mutable.Set and then specialize it in mutable.BitSet when the rhs is also a mutable.BitSet. WDYT?

**Comment by vigdorchik** [comment]
On Tue, Mar 12, 2013 at 9:53 PM, James Iry notifications@github.com wrote:

> The same operations logically make sense for all mutable Sets. So a better
> design might be to have a default impl on mutable.Set and then specialize
> it in mutable.BitSet when the rhs is also a mutable.BitSet. WDYT?
> 
> Not sure this is coherent with the general design of  mutable vs. immutable
> collections:

scala> val b = new ArrayBuffer[String]
b: scala.collection.mutable.ArrayBuffer[String] = ArrayBuffer()

scala> b + "aa"
res4: String = ArrayBuffer()aa

scala> b
res5: scala.collection.mutable.ArrayBuffer[String] = ArrayBuffer()

scala> b += "add"
res6: b.type = ArrayBuffer(add)

scala> b
res7: scala.collection.mutable.ArrayBuffer[String] = ArrayBuffer(add)

So even for mutable collections operations like +/- don't touch the
collections themselves, but the analogs with '=' do. That's why I think
bitsets should follow the same route.

**Comment by paulp** [comment]
He's not suggesting what you think he's suggesting. I would clarify if I could think of a better way to say it; since I can't at the moment, I'll suggest re-reading it.

**Comment by vigdorchik** [comment]
Two hurdles that make me think we can't add this to mutable sets:
1) 'This' parameter in 'SetLike' is declared covariant, which means we can't have it in parameter position.
2) Currently corresponding immutable methods have names like 'diff' or 'union', while bitsets have names '&~' or '|'.
I would not like to promote the difference in naming style to mutable.Set, though in retrospective I think we should've been more consistent.

**Comment by vigdorchik** [comment]
@JamesIry to summarize I don't think we can add to mutable Sets.

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
