### PR TITLE
Scaladoc: Load scripts at the bottom, and with a defer attribute

### PR DESCRIPTION
**Pull request by kzys**
To improve latency on modern browsers (which supports defer) and old browsers:
- https://www.webkit.org/blog/1395/running-scripts-in-webkit/
- http://developer.yahoo.com/blogs/ydn/posts/2007/07/high_performanc_5/

### CODE REVIEW

**Comment by kzys** [comment]
@VladUreche @heathermiller Could you review this request?

**Comment by heathermiller** [comment]
While definitely a good idea to defer loading, I'm not entirely sure I like the `val scripts` approach. It's just that a `val`  in the middle of `Index.scala` and `Template.scala` is not where you would first think to look when you want to see what js is loaded on a page. Usually, the way people work is to go to the last `body` tag or to the `header` of the DOM.

It's a minor nitpick though. If I'm the only one that's picking at this, then feel free to merge.

This one gets a LGTM from me so long as at least one other person gives a LGTM.

**Comment by heathermiller** [comment]
PS, correction: `scripts` isn't in the middle of `Index.scala` and `Template.scala`, it's directly after the header, so it's not far off from where it should be.

Anyway, LGTM so long as someone else thinks this isn't a big deal.

**Comment by kzys** [comment]
Thanks Heather. I'm ok to move the val scripts from just after the header to just after the body. However I still think it would be nice to define the scripts separately because the definition of the body is seriously long (especially in Template).

**Comment by adriaanm** [comment]
6 days says "silent agreement" to me -- merging

**Pull request merged**
