### PR TITLE
Backporting from 2.12.x to 2.11.x

### PR DESCRIPTION
**Pull request by gourlaysama**
Backports of all those PR sent to 2.12.x that could have been targeted to 2.11.x:
- scaladoc improvements: #3898, #3918, #3892, #3891, #3880, #3857, #3864, #3853, #3822, #3819, #3810
- actual code changes (in the scaladoc tool): #3881, #3875 (last two commits here)

Changes to `src/library` only happen within scaladoc comments. It doesn't get more binary compatible than that.

### CODE REVIEW

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@c52bceb

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@f18db59

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@5321b1b

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@7717244

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@40beefb

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@c52bceb

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@e54b772

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@b70b074

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@7bcb316

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@5321b1b

**Comment by gourlaysama** [comment]
PLS SYNCH

**Comment by gourlaysama** [comment]
\o/ Yay, finally, a nice column of green check marks, and it only took 11 comments and 27 jenkins builds.

**Comment by lrytz** [comment]
LGTM, thanks a lot!

**Comment by lrytz** [comment]
I merged 2.11.x (was non-clean), and created a new PR #3947

**Pull request closed without merging**
