### PR TITLE
SI-6923 Context now buffers warnings as well as errors

### PR DESCRIPTION
**Pull request by puffnfresh**
First pull request!

https://issues.scala-lang.org/browse/SI-6923

I want this change in 2.10.x but what's the procedure for porting this to 2.11/master?

---

Code that was silently typed would not report warnings, even if it
returned a successful result.

This appeared in the following code which didn't show warnings even
with -Ywarn-adapted-args:

```
def foo(a: Any) = a; foo(1, 2)
```

While the following would show the expected warning:

```
def foo[A](a: Any) = a; foo(1, 2)
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @hubertp

@pufuwozu Thanks for the patch! "Name your reviewer" and few other guidelines are listed in the [Pull Request Policy](https://github.com/scala/scala/wiki/Pull-Request-Policy) In particular, could you please sign the [CLA](http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf)?

2.10.x is merged every week or so to master, you don't have to do anything special.

**Comment by puffnfresh** [comment]
@retronym CLA submitted.

**Comment by adriaanm** [comment]
ping @hubertp

**Comment by hubertp** [comment]
lgtm

**Pull request merged**
