### PR TITLE
Revert "SI-8346 Rebuild invariant sets in #toSet, avoiding CCE"

### PR DESCRIPTION
**Pull request by adriaanm**
Reverts scala/scala#3791 since CLA was not and will not be signed by the author.

### CODE REVIEW

**Comment by soc** [comment]
@adriaanm What was the issue with the CLA?

**Comment by adriaanm** [comment]
You'll have to ask Stephen.

**Comment by adriaanm** [comment]
IDE failure due to misconfiguration somewhere, tracked at https://github.com/scala/scala-jenkins-infra/issues/116

**Pull request merged**
