### PR TITLE
Add a FAQ on the repo workflow to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by folone**
Hello folks,

I've been playing with scala repo for several months. Finding my way around was (and is) not an easy job. Watching @retronym, @xeno-by, @adriaanm, @paulp, @densh, @soc and others perform huge refactorings/changes is always amazing. How do they know where those things are? How do I even check that the thing I've just added does what I want it to?

The way I gathered information presented in this PR was by asking scala-internals and bothering people via email. I can imagine, this might be quite annoying – answering same newbie questions over and over again. Do you think it makes sense to have some centralized place to keep these kinds of tips? Does it make sense to have it here, or should this be somewhere under http://docs.scala-lang.org? There's a lot of unwritten folklore around this repo, and writing it down would certainly help people find their way around, and attract new contributors. It would definitely help me.

Not sure about the format: my knowledge is very sparse here, so can be most easily presented as a FAQ. Just wanted to kick off the conversation and see if there are more people struggling with these kinds of things, or if I'm the only one having those problems.

Thanks.

### CODE REVIEW

**Comment by paulp** [comment]
The answer to the quasiquotes question should be "yes, and sorry it took this long." ("Should be" - I don't know what the real answer is.) Bootstrapping isn't a valid reason for no given that it's done with 2.11.

**Comment by folone** [comment]
Indeed! I did not think about this in the context of 2.11 release, thanks. Are contributors encouraged/discouraged to use them? Or is there no official answer, decisions are made for each specific case, and I should just remove that question?

**Comment by retronym** [comment]
Thanks for writing this down. I think there is some overlap with the [Hacker Guide](http://www.scala-lang.org/contribute/guide.html) (part of our [Contribute](http://www.scala-lang.org/contribute/) section). I'd vote to expand that guide, and link to it from our README here.

**Comment by paulp** [comment]
@folone I can't comment on the real answer, but if you are interested in a compiler with fewer bugs than infinity, not only should all new tree generation be required to be done with quasiquotes, there should be a grand and sustained effort to convert all the existing tree generation code to quasiquotes.

**Comment by folone** [comment]
@retronym Cool, I did not know about the Hacker Guide. Will have a look and try to add more info to it. I believe it needs more visibility though: I actually googled for resources on developing/contributing to scala compiler, and it did not show up in the results.

@paulp makes sense.

Thanks for your input. Closing this, will continue work in https://github.com/scala/scala-lang/.

**Comment by heathermiller** [comment]
Thanks a lot @folone for posing these questions here. I'm on @retronym's side here – given the effort that @xeno-by already invested in the Hacker Guide, it's probably best to consolidate all of this sort of advice there.

Thanks for taking this up :)

**Comment by som-snytt** [comment]
+1.  I had to understand the f-interpolator, but I didn't follow the paragraph about that.  An alternative advice would be, Take your best shot, and xeno-by or densh will chime in with assistance.

Love the explanation for compatibility.  Why don't people just say that backward compatibility is evil?  I guess that like evil in the world we know, it has its place in the greater plan.

I didn't know there was a partest guide.

The test advice should include that anything unit-testable should be under test/junit.  You don't currently have the (useful) option to run a unit test in isolation with partest.  IIUC.  This is sustainable until there are enough unit tests that running them is excruciating.

**Pull request closed without merging**
