### PR TITLE
SI-6562 Shuffle around Inliner based access widening, part III

### PR DESCRIPTION
**Pull request by retronym**
Initial review by @odersky @magarcia. Additional pairs of eyes are very welcome.

The first commit is sufficient to resolve the reported crash.

But when considering what should and should not land in 2.10.0, we must carefully weigh the risk of these late changes against the risk of leaving the access widening in `SuperAccessors`, which is a significant deviation from 2.9.2, and might have as-yet-undiscovered impacts on other clients of pickled signatures (scalap / Salat / Reflection?). It would might also hamper our ability to deliver the full fix in 2.10.1 on grounds of binary compatibility.

### CODE REVIEW

**Comment by odersky** [comment]
LGTM for 2.10.1. As to whether this should go into 2.10.0, I believe the first commit definitely needs to go in there because it fixes a blocker ticket. For the rest, I am not sure, but would tend to wait for 2.10.1. I would like to understand better the risk of binary compatibility here. I do not see how moving logic from super accessors to explicit outer will affect binary compatibility. If someone shows an example where it is affected, I have to reconsider my recommendation.

**Comment by magarciaEPFL** [comment]
I'm midway through a new, fantastic, closure-elimination technique I'll report about in a few hours, so my review won't arrive before then.

**Comment by adriaanm** [comment]
Agreed with Martin. Let's get the first commit into 2.10.0-wip, everything else will have to wait unfortunately.

(edited: @gkossakowski will deal with it)

**Comment by gkossakowski** [comment]
@retronym: if you are working on optimizer I strongly encourage you to make use of instrumented tests:
https://github.com/scala/scala/tree/master/test/files/instrumented

Also, I'm very reluctant (to the point of rejecting patches) to inliner as long as we do not have high-level document describing how it is supposed to work especially when it comes to separate compilation and binary compatibility.

I understand the idea behind the first patch so I'll follow up with new pull request that cherry-picks that one.

**Comment by retronym** [comment]
> I would like to understand better the risk of binary compatibility here. I do not see how moving logic from super accessors to explicit outer will affect binary compatibility.

I'm considering the pickled signatures as part of the binary contract.

```
// PR #1526

scala> class C { private val x: Any = 0; @inline def foo = x }
defined class C

scala> val cm = reflect.runtime.currentMirror
cm: reflect.runtime.universe.Mirror = JavaMirror with ...

scala> val c = cm.universe.typeOf[C]
c: cm.universe.Type = C

scala> c.declaration(cm.universe.newTermName("x"))
res0: cm.universe.Symbol = value x

scala> c.declarations.map(_.name)
res1: Iterable[cm.universe.Name] = List(<init>, x, x , foo)
```

I'd call the following a bug. Sure, reflection is experimental, but it also could pre-reflection users of pickled signatures. Salat and IntelliJ (via scalap) come to mind.

```
// 2.10.0-wip

// ...

scala> c.declaration(cm.universe.newTermName("x"))
res1: cm.universe.Symbol = <none>

scala> c.declarations
res2: cm.universe.MemberScope = SynchronizedOps(constructor C, value x, value x, method foo)

scala> c.declarations.map(_.name)
res3: Iterable[cm.universe.Name] = List(<init>, $line3$$read$C$$x, $line3$$read$C$$x , foo)
```

Another aspect of the compatibility problem will crop up when the 2.10.1 Inliner encounters class files compiled with 2.10.0 (or, come to think about it, vice versa.) It can no longer [assume](https://github.com/retronym/scala/commit/1288db) that an outer pointer referenced in an inline-marked method was made public; instead we'll need to carry this information through from the Java signatures. (Admittedly, that's probably a good idea in any case.) Seemingly small improvements to the inliner carry a far greater testing burden if we have to support and verify interop between 2.10.0 / 2.10.1.

> if you are working on optimizer I strongly encourage you to make use of instrumented tests

They look pretty handy, but in this case I think the `-Yinline-warnings` based `run` tests are sufficient

> Also, I'm very reluctant (to the point of rejecting patches) to inliner as long as we do not have high-level document describing how it is supposed to work especially when it comes to separate compilation and binary compatibility.

I'm all for documentation, but if you are apply this standard uniformly, we would simply be reverting the preceding commits that this PR is attempting to remedy. I'm not against that course of action, but I don't know how much we've come to rely on inlining improvements that were booked in this release.

**Comment by retronym** [comment]
> but it also could pre-reflection users of pickled signatures. Salat and IntelliJ (via scalap) come to mind.

Concretely, private members will appear as public in the scalap output, and IntelliJ will offer these as autocompletion options.

Test.scala

``` scala
package sandbox

class C {
  private val x: Any = 1
  @inline def foo = x
}
```

Scalap output:

``` scala
package sandbox
class C extends java.lang.Object {
  def this() = { /* compiled code */ }
  val x : scala.Any = { /* compiled code */ }
  @scala.inline
  def foo : scala.Any = { /* compiled code */ }
}
```

Another fun angle on the problem:

```
ticket/6562-3 ~/code/scala cat sandbox/test.scala 
package sandbox

class C {
  private val x: Any = 1
  @inline def foo = x
}
ticket/6562-3 ~/code/scala cat sandbox/test_2.scala 
package sandbox

object Test {
  new C().sandbox$C$$x
}
ticket/6562-3 ~/code/scala /Users/jason/usr/scala-v2.10.0-RC1-15-g2c55424/pack/bin/scalac -classpath . -d . sandbox/test.scala  && /Users/jason/usr/scala-v2.10.0-RC1-15-g2c55424/pack/bin/scalac -classpath . -d . sandbox/test_2.scala 
ticket/6562-3 ~/code/scala 
```

**Comment by retronym** [comment]
These residual issues are now tracked in [SI-6608](https://issues.scala-lang.org/browse/SI-6608)

**Pull request closed without merging**
