### PR TITLE
Compiler determinism for synthetic companions

### LINKED ISSUE #12066: Compilation of code with synthetic companion objects is non-deterministic
This new test case fails in `DeterminismTest`

```scala
  @Test def testSyntheticModuleLocationInDecls(): Unit = {
    def code = List[SourceFile](
      source("a.scala",
        """
          | object A {
          |   class C(val a: Any) extends AnyVal
          |   implicit class I1(a: String)
          |   implicit class IV(val a: String) extends AnyVal
          |   case class CC()
          | }
          |
      """.stripMargin),
      source("b.scala",
        """
          | object B {
          |   // Order here reversed from definition order in A
          |   A.CC()
          |   A.IV("")
          |   A.I1("")
          |   new A.C("")
          | }
          |
      """.stripMargin)
    )
    test(List(code))
  }
```

### PR DESCRIPTION
**Pull request by retronym**
Fixes scala/bug#12066

Relates to scala/scala-dev#405

### CODE REVIEW

**Comment by retronym** [comment]
Marking for consideration for 2.13.2. /cc @lrytz

**Comment by som-snytt** [comment]
That's pretty clever, to simplify the import exclusion. So now you get one shot at exclusion; it can be triggered by an arbitrary lookup, but the idiom must be a preceding package level import? If the source has two packagings, does order matter? I'd have to try it. Actually, an import in a sibling packaging would not be an enclosing context. Maybe you choose not to support that; it might trigger the error; in addition, I now think this is a terrible feature anyway and should receive minimal support.

Also, I verified that the determinism test fails, but the scala signature diff is not meaningful to me. The test for ordering of the implicit class defs is more obvious.

The repl knows if it has to insert the import somewhere, but maybe the template breaks the test t11897. t1931 is also repl, a SessionTest!

neg/predef-masking.scala should just work. Oh, is it because the import already triggers lookup? So the second import no longer excludes `-Yimports:hello.world.minidef`.
```
import hello.{world => hw}
import hw.minidef.{Magic => Answer}
```

**Comment by som-snytt** [comment]
I'll take a look; my speculation was wrong, so I'll have to refresh how namers works...

**Comment by retronym** [comment]
A solution for the non-determinism for root import exclusion (https://github.com/scala/bug/issues/11867) eludes me, so I've reduced this PR to solving the issue of stabilizing the order synthetic modules in Scopes (scala/bug#12066).

**Review by lrytz — APPROVED** [review]

**Pull request merged**
