### PR TITLE
Remove unnecessary dependency on parallel collections in ScalaRunTime.

### PR DESCRIPTION
**Pull request by nicolasstucki**
This change is required for Scala.js compatibility.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
Thanks! I'd like to see some more details in the form of a commit message that explains why the dependency is unnecessary (if we have a case for GenIterable, why do we need Iterable?) and some test cases to ensure we didn't/won't regress. Runtime behavior with arrays can be counter-intuitive.

**Comment by nicolasstucki** [comment]
We would not need `Iterable` anymore, it was a mistake to leave it. 

Someone added `case x: ParIterable[_]` to make the `ScalaRuntime.stringOf(arg: Any, maxElements: Int)` work properly for parallel collections, before it would simply fall in the `case x` and ignore the `maxElements`.

Before the change it would have been:

``` scala
scala> stringOf(Iterable.range(0, 10), 3)
res1: String = List(0, 1, 2)

scala> stringOf(ParIterable.range(0, 10), 20)
res2: String = ParArray(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
```

An now it is:

``` scala
scala> stringOf(ParIterable.range(0, 10), 20)
res2: String = ParArray(0, 1, 2)
```

But the same should hold for any `GenIterable[_]`.
Furthermore, this way we avoid depending on parallel collections which are not supported in Scala.js.

I'll remove the `case x: Iterable[_]`, add info in the commit message and add some tests.

**Comment by adriaanm** [comment]
LGTM! Excellent, thank you!

**Pull request merged**
