### PR TITLE
a fork of isValueType and isNonValueType

### PR DESCRIPTION
**Pull request by xeno-by**
fixing the stuff while Paul's sleeping

### CODE REVIEW

**Comment by gkossakowski** [comment]
So guys, what's the status of this one?

**Comment by xeno-by** [comment]
@gkossakowski You beat me by a few seconds! Wanted to ask the same

**Comment by xeno-by** [comment]
The original pull request looks good to me. I learned a lot from it. But since I'm also involved in it, I cannot give a lgtm. @retronym, could you please, chime in?

**Comment by paulp** [comment]
I guess I can't really give it a LGTM either, but it LGTM (for now - we should press further on these definitions.)

**Comment by gkossakowski** [comment]
Actually you can I think. The point of reviewing is  to have a second pair
of eye balls looking at the code being submitted.

If you both happy and stamp it with LGTM we are all good for merge.

## 

Sent from my Android
Grzegorz

**Comment by paulp** [comment]
All systems go!

**Comment by xeno-by** [comment]
Acknowledged!

**Comment by xeno-by** [comment]
Okay Greg since you're not here, I'm merging

**Pull request merged**
