### PR TITLE
Merge branch '2.12.x' into 2.13.x

### PR DESCRIPTION
**Pull request by SethTisue**
merge details in commit message

motivation: merging #5791 through to cut down on noise when doing
2.13 work (such as deprecated removals)

### CODE REVIEW

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
Maybe next time don't add all the log to the commit message as it crates a lot of cross-links on github?

**Comment by SethTisue** [comment]
> Maybe next time don't add all the log to the commit message as it crates a lot of cross-links on github?

oops... yeah, OK. I had come across some past merges in the history that included the log and liked it, but I hadn't considered the cross-links issue.

**Comment by lrytz** [comment]
@SethTisue something went wrong in this merge:
  - There's only a single commit in this PR (17633b2db358fa82581c797aab5bfc2d6936a048)
  - The git log for 2.13.x looks like this:

```
*   87c8eb713c - (HEAD -> 2.13.x, upstream/2.13.x) Merge pull request #5830 from lrytz/cut-deps (4 days ago) <Lukas Rytz>
|\
| * f540fa66bb - (origin/cut-deps, cut-deps) Avoid `sys.process` (4 days ago) <Adriaan Moors>
| * 4a0bc09674 - Avoid `sys.exit` (4 days ago) <Adriaan Moors>
...
* | | |   26504fe7f5 - Merge pull request #5794 from SethTisue/merge-2.12-to-2.13-mar-21 (3 weeks ago) <Lukas Rytz>
|\ \ \ \
| |_|/ /
|/| | |
| * | | 17633b2db3 - Merge branch '2.12.x' into 2.13.x (3 weeks ago) <Seth Tisue>
|/ / /
* | |   e2a2cbacd0 - Merge pull request #5603 from szeiger/wip/modularize-parallel-collections (4 weeks ago) <Seth Tisue>
|\ \ \
| * | | d205a63cd1 - Remove parallel collections from scala-library (4 weeks ago) <Stefan Zeiger>
...
```

  - the diff contains the full merge, squashed
  - the commits of the merge are not actually part of 2.13.x, for example the last commit (96cdfb4403cddedddbbf7a2bc5403fb617f4d35e):

```
> git branch --contains 96cdfb4
  2.12.x
>
```

  - `git merge-base upstream/2.12.x upstream/2.13.x` gives me a21daecee216565907331206e14c649dff062139, which is the parent of the first commit (cba77cece58625706bd218e28482beb1abe0bc06) of the merge in this PR

Maybe I clicked "Squash and Merge" or "Rebase and Merge" by mistake, I don't know.

So to fix it I merge 96cdfb4403cddedddbbf7a2bc5403fb617f4d35e (the 2.12.x commit that was used in the merge here) into 2.13.x:

```
> git lg upstream/2.13.x -n 1 | cat
*   87c8eb713c - (upstream/2.13.x) Merge pull request #5830 from lrytz/cut-deps (4 days ago) <Lukas Rytz>

> git merge 96cdfb4
Auto-merging versions.properties
CONFLICT (content): Merge conflict in versions.properties
Automatic merge failed; fix conflicts and then commit the result.

> git add versions.properties

> git commit
[2.13.x f23e092737] Merge commit '96cdfb4' into 2.13.x

> git diff upstream/2.13.x | cat
>
```

The diff is empty, so that seems to be the correct fix.

**Comment by SethTisue** [comment]
> Maybe I clicked "Squash and Merge" or "Rebase and Merge" by mistake, I don't know

I can't think of another likely explanation. I'm sure this PR didn't originally look like that

**Comment by lrytz** [comment]
OK, I'll submit the fix with my upcoming merge.

**Pull request merged**
