### PR TITLE
SIP-36 - Adding prefix types

### PR DESCRIPTION
**Pull request by soronpo**
Implements SIP-36- Adding prefix types.
https://docs.scala-lang.org/sips/adding-prefix-types.html

Status: SIP is pending. Will be merged into TLS to get more response from users.

### CODE REVIEW

**Comment by SethTisue** [comment]
what did the SIP committee conclude about this...? let's have a link here

**Comment by soronpo** [comment]
> what did the SIP committee conclude about this...? let's have a link here

Updated the head of the thread.

**Comment by SethTisue** [comment]
thanks. closing, can always be reopened later should the situation change.

**Comment by soronpo** [comment]
I'm unsure about closing. TLS acceptance policy is to have an (open?) PR against LBS https://github.com/typelevel/scala#how-to-contribute-to-typelevel-scala

**Comment by SethTisue** [comment]
well, our motivation is that we don’t want lots of open stale PRs sitting around in the queue. dauntingly large PR queue causes neglect cause even more dauntingly large PR queue, which is the cycle we’ve been in lately. it’s just bookkeeping, I’m sure the TLS folks can clarify and/or adapt their rules if needed

**Comment by soronpo** [comment]
@milessabin your thoughts?

**Comment by milessabin** [comment]
I think that we'll have to revise the TLS policy ... we've had quite a few important PRs closed due to slow progress rather than outright rejection and we don't want to drop them from TLS on just those grounds.

Nb. I think it's perfectly reasonable to want to clean up the scala/scala PR queue.

**Pull request closed without merging**
