### PR TITLE
SI-6162 Adds private[scala] @deprecatedInheritance/@deprecatedOverriding

### PR DESCRIPTION
**Pull request by retronym**
Second try submission of #1026

Review by @paulp, @soc

### CODE REVIEW

**Comment by retronym** [comment]
If this goes in, we should ask around in -internals for any other places we can slap these annotations. `TupleN`, perhaps?

**Comment by jsuereth** [comment]
This lgtm

**Comment by gkossakowski** [comment]
LGTM from me as well. Can we squash pull request feedback commit?

**Comment by retronym** [comment]
I can't squash it right now, but feel free to do so when merging. Personally, I like leaving a single "pull request feedback" commit (maybe itself squashed with a few iterations of feedback.) in the history, so long as the previous commits are not broken.

**Comment by gkossakowski** [comment]
I agree that leaving them is fine but I'd prefer to have a bit better commit message than just `Pull request feedback`.

This commit is trivial so `Pull request #1284 feedback`. Those numbers turn to be useful for grepping and general scanning through commit.

For this one I'll go ahead and merge.

**Comment by retronym** [comment]
BTW, if you want to answer the question: "what pull request contained this commit", you can configure git to [fetch all the pull requests](https://gist.github.com/3342247) and then use the usual git commands, e.g `git branch --contains <hash>`

**Comment by gkossakowski** [comment]
Ah yes. Thanks for good suggestion!

**Pull request merged**
