### PR TITLE
fixes incorrect handling of Annotated in lazy copier

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp

**Comment by xeno-by** [comment]
PLS REBUILD ALL and pls don't abort

**Comment by paulp** [comment]
If this can go undiscovered for 6 years, a test case would be valuable, even if only to demonstrate where this happens.  I assume you found this by eyeball.

**Comment by xeno-by** [comment]
Actually I found this be helping out someone in the lab - we couldn't make a transformer transform a tree, even though the rewriting logic was definitely triggered. Apparently the copier was sneakily discarding the changes we applied. The test is a good idea, I agree.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@paulp Added the test

**Comment by paulp** [comment]
Looks like a fun test. LGTM.

**Pull request merged**
