### PR TITLE
SI-6419 Repl save session command

### PR DESCRIPTION
**Pull request by som-snytt**
A simple save command to write out the current replay stack.

One can imagine a distinct "store session" command that saves state. (`:store` and `:restore`)

```
scala> val i = 7
i: Int = 7

scala> val j=  8
j: Int = 8

scala> i * j
res0: Int = 56

scala> :save multy.script

scala> :q
apm@mara:~/tmp$ cat multy.script
val i = 7
val j=  8
i * j
apm@mara:~/tmp$ skala
Welcome to Scala version 2.11.0-20130626-204845-a83ca5bdf7 (OpenJDK 64-Bit Server VM, Java 1.7.0_21).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :load multy.script
Loading multy.script...
i: Int = 7
j: Int = 8
res0: Int = 56

scala> :load multy.script
Loading multy.script...
i: Int = 7
j: Int = 8
res1: Int = 56
```

The commit omits to cite:

```
scala> :save foo
No replay commands in session

scala> :save
File name is required.
```

Review by @retronym who might give me a two-fer favor for paste -raw.

### CODE REVIEW

**Comment by adriaanm** [comment]
I'm no replxpert, but LGTM.

**Comment by adriaanm** [comment]
The test fails on windows: https://scala-webapps.epfl.ch/jenkins/view/All/job/scala-nightly-windows/1756/console

**Comment by som-snytt** [comment]
Until recently I tested on cygwin so I'd see every such error.  Where should I apply the fix, a separate commit on my branch?

**Comment by som-snytt** [comment]
@adriaanm  There is a fix at https://github.com/som-snytt/scala/tree/issue/fix-repl-save-test

**Pull request merged**
