### PR TITLE
Make :: type alias covariant

### PR DESCRIPTION
**Pull request by julien-truffaut**

### CODE REVIEW

**Comment by julien-truffaut** [comment]
I just signed the CLA.

**Review by julienrf — APPROVED** [review]

**Review by hrhino — APPROVED** [review]

**Review by lrytz — APPROVED** [review]
LGTM, I'm curious though if there's a way to observe the difference.

**Comment by julien-truffaut** [comment]
@lrytz Yes, you can observe it.

```scala
class Foo[+A] {
  def nel: ::[A] = ???
}
```

fails with: 

```
Error:(4, 7) covariant type A occurs in invariant position in type => ::[A] of method nel
  def nel: ::[A] = ???
```

but if you desalias it, it works fine:

```scala
 class Foo[+A] {
  def nel: scala.collection.immutable.::[A] = ???
}
```

**Comment by lrytz** [comment]
@julien-truffaut thanks. Could you add this as a test case? For example here: https://github.com/scala/scala/blob/2.13.x/test/junit/scala/PredefTest.scala

**Comment by julien-truffaut** [comment]
@lrytz Sure, should it be in `scala/tree/2.13.x/test/files/pos` ? What's the naming convention for the file?

**Comment by lrytz** [comment]
`test/files/pos` is good. Thank you!

**Comment by lrytz** [comment]
Oh, naming convention if we have no ticket, i'm not sure :-) Alternatively, add it to `PredefTest.scala` (which I liked above)

**Comment by SethTisue** [comment]
@julien-truffaut does https://github.com/scala/scala/pull/8651 have implications here?

**Comment by julien-truffaut** [comment]
@SethTisue Sorry I don't know.

**Pull request merged**
