### PR TITLE
new approach to access-level widening for inlining

### PR DESCRIPTION
**Pull request by magarciaEPFL**
review by @odersky or @paulp

Comments on performance impact are welcome /cc @gkossakowski

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
What's the contract of `Run.compiles()` ? This pull contains a workaround for:

```
// TODO `currentRun.compiles()` returns false for, say, the outer-field of an anon-closure-class
```

**Comment by magarciaEPFL** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@magarciaEPFL: To me it's not clear how this relates to access widening done in earlier phase (implemented by @odersky). Can you explain? (I tried to read comments but I didn't get the clear answer to that question).

**Comment by magarciaEPFL** [comment]
This PR had its origin in a discussion on Inliner improvements (culminating in [1]). 

Summing up, it's a variation on the current policy of 
  (a) making public everything an @inline-marked method touched. 
  (b) The other piece of the current policy (ie in 2.10.x) involve's Inliner's `canMakePublic()`. 

The new policy (favored at the time, however later nobody LGTM'd it) is implemented in this PR. 

It keeps the (a) part, however not in `ExplicitOuter` but in `LazyVals`, so as to catch some outer fields that currently aren't made public. 
Additionally, (b) was re-worked to be more selective about which additional fields it makes public. Without (b), many closures can't be inliend (after all, their apply methods aren't marked at-inline).

Assuming the new policy is still favored (big question mark), then it remains to also revert scala/scala@5d4e4e2 .

[1] https://groups.google.com/d/msg/scala-internals/iPkMCygzws4/MIDPK6-3vwMJ

**Comment by gkossakowski** [comment]
I see. Since this change comes with no test-cases and I don't have time to verify it manually it'll need to hang for a while. In principle, I'd strongly prefer to stop merging changes to optimizer that do not come with comprehensive test-cases.

I'll be away for one week so somebody else will need to make decision what to do with this pull request.

**Comment by gkossakowski** [comment]
Cannot be merged anymore. Closing.

**Pull request closed without merging**
