### PR TITLE
SI-7546 Use likely monotonic clock source for durations

### PR DESCRIPTION
**Pull request by soc**
System.currentTimeMillis is affected by wall-clock time, which means
things can appear to jump back in time.
Use System.nanoTime which is more likely¹ to be monotonic instead.

¹ See http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6458294
  "nanoTime affected by system clock change on Linux (RH9) or in
   general lacks monotonicity".

### CODE REVIEW

**Comment by soc** [comment]
> [ERROR] Failed to execute goal on project typesafeDummy: Could not resolve dependencies for project com.typesafe:typesafeDummy:war:1.0-SNAPSHOT: Could not find artifact com.typesafe.sbt:incremental-compiler:jar:0.13.0-on-2.11.0-57023b7-SNAPSHOT-for-IDE-SNAPSHOT in pr-scala (http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots)

**Comment by soc** [comment]
PLS REBUILD/pr-scala@57023b7

**Comment by adriaanm** [comment]
I see you've also been foiled by that error message that isn't (an error). It's only saying the artifact wasn't found on maven, so it has to be built. There surely was an error after that -- github connectivity issues, most likely.

**Comment by som-snytt** [comment]
I'm pretty sure `typesafeDummy` is the test mannequin they strap into the compiler right before they crash it, just to see what the damage is.

**Comment by adriaanm** [comment]
The dummy's muzzled by https://github.com/scala-ide/uber-build/pull/26

**Comment by adriaanm** [comment]
Please tone down the commit message. We don't need this in our history forever. Otherwise, LGTM

**Comment by soc** [comment]
@adriaanm Done, added a link to the bug report, thanks.

**Comment by adriaanm** [comment]
Thanks

**Comment by adriaanm** [comment]
Huh, that's an unlikely IDE failure.

Failed tests:   relevanceSortingTests(scala.tools.eclipse.completion.CompletionTests): Relevance expected:<List[]> but was:<List[ ]>

**Comment by soc** [comment]
PLS REBUILD/pr-scala@a3a5e4a

**Comment by soc** [comment]
@adriaanm Seems like the failure was spurious.

**Comment by adriaanm** [comment]
Great! merging -- already notified IDE team

**Pull request merged**
