### PR TITLE
Remove experimental status from sbt build in load message

### PR DESCRIPTION
**Pull request by janekdb**
sbt is now the preferred build tool.

### CODE REVIEW

**Comment by janekdb** [comment]
sbt-load-message-sans-experimental-status

**Comment by janekdb** [comment]
Review by @retronym

**Comment by dwijnand** [comment]
Personally I think the whole `onLoadMessage` should go - the messaging as of this PR is more noisy than useful IMO.

**Comment by dwijnand** [comment]
Also, while I only use the sbt build myself, morally I see the sbt build as experimental until it's at least used for PR validation (current iteration #5190).

**Comment by retronym** [comment]
LGTM. The link the to README is still worthwhile, as things like configuring IntelliJ and bootstrapping aren't discoverable without reading the docs.

**Pull request merged**
