### PR TITLE
SI-8367 revert SI-8192's change to primaryConstructor when isJavaDefined

### PR DESCRIPTION
**Pull request by xeno-by**
this is some weird stuff

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
LGTM

**Comment by adriaanm** [comment]
I would really like to understand why the error points at a comment (see my comment on the ticket). Also, why only for certain names? Are we seeing cross-talk between the java-defined symbols and the ones defined in the scala source? Overall, you shouldn't be putting stuff in the java.lang package, so I'm not _as_ worried, but it's still worrying.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
