### PR TITLE
Inliner heuristic for higher-order methods

### PR DESCRIPTION
**Pull request by lrytz**
First version of an inlining heuristic that favors inlining higher-order methods.

Also closes https://issues.scala-lang.org/browse/SI-8334.

### CODE REVIEW

**Comment by adriaanm** [comment]
:rocket:

**Comment by lrytz** [comment]
Launched a community build: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/156/parameters/

**Comment by retronym** [comment]
> If both the callsite method and the callee have exception handlers, the exception tables of the two methods would need to be merged correctly. This is not straightforward, so we don't inline in this case for now.

How does this limitation compare with the old optimizer?

**Comment by adriaanm** [comment]
How does this relate to `backend/opt/InlineExceptionHandlers.scala`? I can see it's not the same thing, but it sounds like it was meant to alleviate not inlining in the presence of try/catch?

**Comment by lrytz** [comment]
right, i should have checked the old optimizer. it _does_ inline if both the callsite method and the callee have handlers. it emits handlers in the correct order: it just prepends (instead of appends, what the new inliner is doing): https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/backend/opt/Inliners.scala#L638.

thinking of it, that seems to be correct. i was thinking of the general problem of putting arbitrary handlers in the correct order, that would be hard to solve. but here we know that the handlers of the inlined code cover the instructions that were inlined, and none of the existing instructions in the callsite method. so we can just put the inlined handlers first.

**Comment by lrytz** [comment]
Community build [went green](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/159/), thanks to @SethTisue's [patch](https://github.com/SethTisue/community-builds/commit/f22858187557827091ead7cc06e3b65704020b09) that removes `-Xfatal-warnings` from shapeless' build options.

**Comment by retronym** [comment]
LGTM, nice work.

**Comment by lrytz** [comment]
I did a little bit of benchmarking: running the compiler, and three of the [scala.js benchmarks](https://github.com/sjrd/scalajs-benchmarks).

Compiler (compiling `src/library/scala/collection/immutable/*.scala`), "opt" means running a compiler that was built with `-Yopt:l:classpath`, "noopt" means a compiler that was built without that flag. They are equally fast (or slow).
- opt: 13.82 ± 0.49
- noopt: 13.27 ± 0.34

DeltaBlue, "opt" means the benchmark was compiled with `-Yopt:l:classpath`, oldopt means 2.11.7 with `-optimize`. opt is 5% slower than noopt
- opt: 127.08 ± 1.34
- noopt: 121.36 ± 1.00
- oldopt: 123.93 ± 1.05

Richards: 10% faster
- opt: 56.48 ± 0.25
- noopt: 62.66 ± 0.69
- oldopt: 56.00 ± 0.21

Sudoku: same speed (large stdev), it seems the old optimizer manages to pull some tricks on it
- opt: 1346.63 ± 65.22
- noopt: 1413.38 ± 54.75
- oldopt: 1264.42 ± 13.55

I think we shouldn't draw any conclusions at this point, except that it seems safe to merge this PR. The heuristics are still in flux, and there are things that I know are still to do in the new optimizer. Once the core is done, I will start the benchmark-driven work.

**Pull request merged**
