### PR TITLE
Add curly brace (zero-or-more) in grammar for Bindings

### PR DESCRIPTION
**Pull request by soc**
Missing closing curly brace as reported by Andre at https://groups.google.com/forum/#!topic/scala-language/4Zb6dc6EEFM.

### CODE REVIEW

**Comment by soc** [comment]
Review by @som-snytt?

**Comment by som-snytt** [comment]
When Simon S. joked about time travel, I was about to respond that it was an excellent opportunity for the OP to serve as reviewer, especially since you don't have to sign away any software rights in that role.  I should have hit send instead of delete.

I wonder if there's a reason it isn't exactly the same as 6.23.  Or conversely.  Maybe someone will do a macro system to enforce consistency.

```
Bindings        ::=  `(' Binding {`,' Binding} `)'
```

LGTM nevertheless

**Comment by som-snytt** [comment]
LGTM

**Comment by gkossakowski** [comment]
Thanks chaps!

**Pull request merged**
