### PR TITLE
SI-9027 Parser no longer consumes space after multi XML elements

### PR DESCRIPTION
**Pull request by som-snytt**
Once the parser starts looking for more <elements>, it should
still lookahead speculatively, leaving any remaining whitespace,
including newlines, after the last element.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Missing JUnit test?

**Comment by som-snytt** [comment]
I must emulate the clever test at https://github.com/scala/scala/commit/8d175b907d41323333a5613e419303f10beddc76

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@db8d5476537902760d33d29839afd813ff369ac8

**Comment by lrytz** [comment]
LGTM!

**Comment by rkrzewski** [comment]
This problem affects sbt (https://github.com/sbt/sbt/issues/1666, https://github.com/sbt/sbt/issues/1738) and sbt is still using Scala 2.10. Would it be possible to have it backported?

**Comment by som-snytt** [comment]
Sure. A quick test shows it introduces a mima bc error. Maybe I'll just start a PR and someone can tell me about whitelisting.

**Comment by ajozwik** [comment]
+1

**Pull request merged**
