### PR TITLE
SI-7441 Don't ramble on about inapplicable implicits.

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by hubertp** [comment]
lgtm. thanks for fixing it so quickly.

**Comment by adriaanm** [comment]
```
[quick.compiler] /Users/adriaan/git/scala/src/compiler/scala/tools/nsc/typechecker/Implicits.scala:1002: warning: patterns after a variable pattern cannot match (SLS 8.1.1)
[quick.compiler]               case tp                => tp <:< sym.tpe.finalResultType
[quick.compiler]                    ^
[quick.compiler] /Users/adriaan/git/scala/src/compiler/scala/tools/nsc/typechecker/Implicits.scala:1003: warning: unreachable code due to variable pattern 'tp' on line 1002
[quick.compiler]               case _                 => false
[quick.compiler]                                         ^
```

**Comment by paulp** [comment]
Oops, that was ME? I saw that of course, I just figured it couldn't have been me. I'll fix it.

**Comment by som-snytt** [comment]
-Xlint would have told you not to do that.  We just need -Xlint:blame which would tell _you_ not to do that.

**Comment by paulp** [comment]
#2547

**Pull request merged**
