### PR TITLE
Honour the "maven.repo.local" property while building

### PR DESCRIPTION
**Pull request by cunei**
If the property "maven.repo.local" is defined, then use
its value as the local Maven cache repository while
obtaining artifacts.

Note that this does not change the location of the
settings file, which is still in ~/.m2/settings.xml

### CODE REVIEW

**Comment by adriaanm** [comment]
I'm weary of adding `<artifact:localRepository refid="local-repo"/>
` to dependencies that end up in the release, because it's dangerous to have the local repository leak artifacts into releases. Could you elaborate on the use case?

**Comment by cunei** [comment]
The aim is to prevent the artifacts downloaded by Maven from polluting ~/.m2, similar to the rationale for https://github.com/scala/jenkins-scripts/blob/master/pr-scala-common#L198
I have limited maven-fu, but my understanding is that localRepository just modifies the location of the directory that is normally ~/.m2/repository, aka the Maven cache. In dbuild I essentially need to use a private cache for each build.
How do you solve this issue in the pr validation? Since the test failed (but runs on my machine), I suppose you have some way to convince the scala build to use a private .m2, correct? I can't find in what manner LOCAL_M2_REPO is supposed to be used by the scala build. I banged on Ant for a while, but this diff is the only approach that managed to leave ~/.m2 untouched for me. Cheers.

**Comment by adriaanm** [comment]
I tackled it the other way around: prevent maven and sbt from seeing the ~/.m2 stuff, but let ant just have its evil ways. I guess it would be enough to just change the local repo path build.xml -- I'd rather not add references to it in the dependency blocks.

**Comment by adriaanm** [comment]
Here's a shorter script that does this with sbt for the release: https://github.com/scala/jenkins-scripts/blob/master/job/scala-release-2.11.x#L66 (Note that https://github.com/scala/jenkins-scripts/blob/master/repositories-scala-release does not even list a "local" repo, and the module builds don't define one themselves, so they won't see ~/.m2 at all, IIUC)

The problem we're solving on jenkins is slightly different, btw, in that we simply don't want to share the m2 repo between jobs, which can be done (for maven) by changing ~/.m2/settings.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <!-- 
    Maven repos are not safe for concurrent access, thus give each job its own.
    The WORKSPACE env var is set by jenkins to the path of the current job's workspace.
    This settings file will cause ant/maven to break if WORKSPACE is not set (to a writeable directory).
    I don't know how to encode a fall back, but I assume it's not needed as this is ~jenkins/.m2/settings.xml
  -->
  <localRepository>${WORKSPACE}/m2repo</localRepository>
```

**Comment by cunei** [comment]
Hm. It is a goot idea, but when using dbuild I cannot change the user's global ~/.m2/settings.xml, which is why in the diff I used localRepository. I will try changing HOME before calling ant, so that a different settings.xml is used; that could be an alternative. I hope the forking in ant doesn't confuse it, though. I'll try and report.

**Comment by adriaanm** [comment]
Ok, to be clear: I'm fine changing the location of the local repository in build.xml. I just don't want to add the local resolver everywhere,.

**Comment by cunei** [comment]
The localRepository in build.xml needs to be specified in each "artifacts:dependencies" section, from what I could find in the docs, and there is a whole bunch of them in the script. Maybe those sections could be consolidated into a single one, however. Let me check with a custom settings.xml file first, though: I'd prefer to minimize the changes to build.xml, if possible.

**Comment by cunei** [comment]
OK, I've been banging on Ant for hours: convincing it to use a different user home directory is nigh impossible. The jvm in general seemingly derives its user.home from the system, ignoring the HOME environment variable. Even calling ant with "-Duser.home=..." leads just to the frustrating:

```
[info]      [echo] user.home = /home/cunei/activities/dbuild-0.5.1-SNAPSHOT/target-0.8.1-SNAPSHOT/project-builds/scala-2-ac559d98a77bc6b3edb2490cc255192461753a39/.dbuild
[...]
[info] [artifact:dependencies] Using local repository: /home/cunei/.m2/repository
```

When redefining user.home as above, ant in any case looks for settings.xml in the original login home. As a consequence, redefining localRepository as described in this pull request would probably be the cleanest approach.
BUT, I found an alternative. Ugly as sin, but it works. It relies on the little-known (and undocumented) variable `_JAVA_OPTIONS`: using it to set the user.home property DOES work, for all the nested jvm invocations. Not even `JAVA_OPTIONS` will work, but `_JAVA_OPTIONS` does. Go figure.
Since I have a working solution, I'm closing the pull request. Changing build.xml would still be somewhat cleaner, but I'm still hoping that ant will be superseded by sbt on the long term, so for the time being things are good. This was also the source of the problems I was seeing, related to -Dlocker.skip in dbuild. All looks ok now.

**Pull request closed without merging**
