### PR TITLE
Suppressed 'possible cause' mis-warning.

### PR DESCRIPTION
**Pull request by paulp**
I have seen this warning a bunch of times and it has not yet
been close to right.

### CODE REVIEW

**Comment by paulp** [comment]
I expanded into some other 2.10 intended error polishing and bugfixing.  Review by @retronym .

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
That's an all pass except missed checkfile, no reason to re-run tests.

**Comment by paulp** [comment]
Now why didn't I think of that.

**Comment by paulp** [comment]
Looks like that one is a little short on workingness.

**Comment by retronym** [comment]
I'd like to see a few tests around `sm"""`, but the meat of this request LGTM. 

Out of curiosity, could `fullyInitializeXxx` have be written in terms of existing type/symbol traversers?

**Comment by gkossakowski** [comment]
@retronym: Should I go ahead and merge it? Not sure if your LGTM was firm enough.

**Comment by retronym** [comment]
The `sm` string interpolator needs to be fixed / tested before merging.

**Comment by paulp** [comment]
Reopening without the ill-fated sm interpolator.

**Pull request closed without merging**
