### PR TITLE
Merge 2.11.x to 2.12.x

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
```
% export MB=$(git merge-base head origin/2.11.x)
% git --no-pager log --graph --oneline --decorate $MB..origin/2.11.x | pbcopy

*   ddb29a8 (origin/2.11.x) Merge pull request #3815 from retronym/topic/java8-support-2
|\  
| * ca3fb25 (retronym/topic/java8-support-2, origin/pr/3815, topic/java8-support-2) Support Java 8 in the checkfile for neg/t6289
| * eec8ba0 Java 6-8 agnosticism for a test
* |   95278db Merge pull request #3818 from som-snytt/issue/repl-javap-app8
|\ \  
| * | 3073ab4 (origin/pr/3818) Java 8 support for run/repl-javap-app.check
* | |   e1126fd Merge pull request #3812 from retronym/merge/2.10.x-to-2.11.x-20140604
|\ \ \  
| * \ \   a6ecfa6 (retronym/merge/2.10.x-to-2.11.x-20140604, origin/pr/3812, merge/2.10.x-to-2.11.x-20140604) Merge remote-tracking branch 'origin/2.10.x' into merge/2.10.x-to-2.11.x-20140604
| |\ \ \  
| | * | | 300db2a (origin/2.10.x) Merge pull request #3799 from retronym/topic/8596-2.10
| | * | | d288790 (origin/pr/3799) SI-8596 Fix rangepos crasher with defaults, poly methods
| |  / /  
* | | |   0ba6d1c Merge pull request #3800 from som-snytt/issue/8503
|\ \ \ \  
| * | | | 56e6726 (origin/pr/3800) SI-8503 -version is info setting
| * | | | c8f8782 SI-8503 Clean up interpolation of help message
|  / / /  
* | | |   d2b6eed Merge pull request #3787 from tvierling/concurrent-doc-nits
|\ \ \ \  
| |_|/ /  
|/| | |   
| * | | 0d5fa2a (origin/pr/3787) Add documentation to parts of scala.concurrent.
| |/ /  
* | |   4573276 Merge pull request #3816 from lrytz/bcode/bugs
|\ \ \  
| * | | 5fc16e4 (origin/pr/3816) Test: classfile reading during inlining works if there is dead code
| * | | ee6ffbf Make test repl-javap-app independent of precise constant pool indices
| * | | c4ec53e Tone down the noise in the output of t7974
| * | | 6264820 Don't crash on dead code in ICodeReader
* | | |   726d384 Merge pull request #3813 from retronym/ticket/8642-disable-osgi-tests
|\ \ \ \  
| |/ / /  
|/| | /   
| | |/    
| |/|     
| * | 86fc1ce (retronym/ticket/8642-disable-osgi-tests, origin/pr/3813) Disable OSGi tests under Java 8
| |/  
* |   e10ea0c Merge pull request #3811 from lrytz/bcode/arrayClone
|\ \  
| * | 56f9140 (origin/pr/3811) Fix emitting Array(1).clone() in GenBCode
| |/  
* |   a7ed0eb Merge pull request #3743 from ruippeixotog/issue/8553
|\ \  
| |/  
|/|   
| * 7f08e00 (origin/pr/3743) SI-8553 WrappedArray throws exception on lastIndexWhere when index out of range
*   b24e757 (2.11.x) Merge pull request #3803 from xeno-by/ticket/8637
|\  
| * c98aa6f (origin/pr/3803) SI-8637 fixes toolbox phase corruption
*   f0daf47 Merge pull request #3796 from som-snytt/issue/8630
|\  
| * 5277fb4 (origin/pr/3796) SI-8630 lineToString no longer long by one at eof
*   1b280b3 Merge pull request #3795 from som-snytt/issue/8475
|\  
| * d4f664c (origin/pr/3795) SI-8475 GroupedIterator is also lazy when padded
*   d17c098 Merge pull request #3789 from clhodapp/fix/SI-6678
|\  
| * b3166d1 (origin/pr/3789) SI-6678 Make currentMirror macro hygenic
*   bed5c02 Merge pull request #3786 from tvierling/deprecate-fixes-2.11.x
|\  
| * 60ef974 (origin/pr/3786) To have effect, @deprecated needs to be an annotation.
* 20609cd Merge pull request #3798 from adriaanm/scalap
* 2cee3b6 (origin/pr/3798) Include scalap in the distro.
```

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
d17c098 seems like a spurious fail

**Comment by retronym** [comment]
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-publish-core/3341/console

```
Archiving artifacts
ERROR: No artifacts found that match the file pattern "versions.properties, mergetarget". Configuration error?
ERROR: ‘versions.properties’ doesn’t match anything, but ‘scala/versions.properties’ does. Perhaps that’s what you mean?
Build step 'Archive the artifacts' changed build result to FAILURE
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@d17c098

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
