### PR TITLE
Use Java 7 redirection and avoid a thread

### LINKED ISSUE #7963: Console.readLine broken after running a Process with connectInput=true
```scala
// ConnectInput.scala
import scala.sys.process._
object FooApp extends App {
  "ls -l".run(true).exitValue()
  Console.readLine("Foo bar ? ")
}
```

When running this code, one needs to press enter twice in order to exit the process. This problem does not occur when using run(false) instead, so it must somehow be related to how the standard input is connected.

(still got the issue by using scala.io.ReadStdin instead of Console).

I've found a similar issue described here => http://stackoverflow.com/questions/15774987/scala-process-exits-but-doesnt-clean-up-threads/15817760#15817760

### PR DESCRIPTION
**Pull request by som-snytt**
Simplifies the previous contribution and goes further to avoid the useless thread.

Fixes scala/bug#7963

### CODE REVIEW

**Comment by som-snytt** [comment]
Mima strikes again.

**Comment by som-snytt** [comment]
@adriaanm maybe you are the authority that package private members are ok to white list for mima.

I wish mima had an option like partest's `--update` to reconcile the white list file.

**Comment by szeiger** [comment]
The changes should be safe to whitelist:
```
[error]  * method connectNoOp()scala.Function1 in object scala.sys.process.BasicIO does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.sys.process.BasicIO.connectNoOp")
[error]  * method connectToStdIn()scala.Function1 in object scala.sys.process.BasicIO does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.sys.process.BasicIO.connectToStdIn")
```

Both methods are package-private. We have allowed this in similar cases in the past. It can lead to linkage errors if you subvert Scala's access restrictions from Java code because they are JVM-public but it should be safe when used from Scala.

**Comment by som-snytt** [comment]
Added the mima exclusions to build.sbt, rebased on previous additions, it seems to work. The other PR had created a file of exclusions. There's no guidance for the new regime; last time I did this, there was a special file at the root. Normally I like externalizing config, but when a noob contributor like me comes along, it's like where do I add the exclusion?

**Comment by szeiger** [comment]
It would be best to keep an empty filter list around after a release instead of removing the setting entirely. This makes it easier to add new filters when needed (which is almost inevitable).

**Review by szeiger — APPROVED** [review]

**Comment by szeiger** [comment]
I rebased this, reverting the `ProblemFilters.exclude` import to reduce the potential for conflicts with other PRs that touch the MiMa filters list.

**Comment by som-snytt** [comment]
Thanks, although I liked that import. :(

**Comment by szeiger** [comment]
We can reintroduce it after 2.13.1 when the whitelist is reset

**Pull request merged**
