### PR TITLE
Eliminate breaking relative names in source.

### PR DESCRIPTION
**Pull request by paulp**
These things are killing me.  Constructions like

  package scala.foo.bar.baz
  import foo.Other

DO NOT WORK in general.  Such files are not really in the
"scala" package, because it is not declared

  package scala
  package foo.bar.baz

And there is a second problem: using a relative path name means
compilation will fail in the presence of a directory of the same
name, e.g.

  % mkdir reflect
  % scalac src/reflect/scala/reflect/internal/util/Position.scala
  src/reflect/scala/reflect/internal/util/Position.scala:9: error:
    object ClassTag is not a member of package reflect
  import reflect.ClassTag
         ^
  src/reflect/scala/reflect/internal/util/Position.scala:10: error:
    object base is not a member of package reflect
  import reflect.base.Attachments
                 ^

As a rule, do not use relative package paths unless you have
explicitly imported the path to which you think you are relative.
Better yet, don't use them at all. Unfortunately they mostly work
because scala variously thinks everything scala.\* is in the scala
package and/or because you usually aren't bootstrapping and it
falls through to an existing version of the class already on the
classpath.

Making the paths explicit is not a complete solution -
in particular, we remain enormously vulnerable to any directory
or package called "scala" which isn't ours - but it greatly
limts the severity of the problem.

### CODE REVIEW

**Comment by paulp** [comment]
For obvious reasons I would like to merge this as soon as humanly possible.  After it's in 2.10 I'll merge 2.10 into master.

**Comment by paulp** [comment]
As a side note, if we had a principled bootstrap sequence this would never have gotten as bad as it is because nothing would bootstrap.  I know because that's why I finally had to fix it.

**Comment by paulp** [comment]
Review by @jsuereth

**Comment by jsuereth** [comment]
HOLY CONSISTENCY BATMAN!  +1 on general principles, but let me dig through for a bit.

**Comment by jsuereth** [comment]
Well, LGTM, assuming tests pass.

**Comment by paulp** [comment]
Grr, I ran them myself already, they passed.  I don't know what that failure is.

**Comment by paulp** [comment]
Oh, it must because I rebased it after I ran the tests, and although it went cleanly, dragged in an old name.

**Comment by paulp** [comment]
Nope, the real 2.10.x has a single AbsTypeTag reference in it.

**Comment by paulp** [comment]
So who merged a pull request which not only wasn't tested, but didn't even build...

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
I believe that's my fault

**Pull request merged**
