### PR TITLE
Fixes deprecation annotations for 2.10.0

### PR DESCRIPTION
**Pull request by jsuereth**
Review by @soc and @gkossakowski

### CODE REVIEW

**Comment by soc** [comment]
The change in `TraversableOnce` is duplicated.

**Comment by gkossakowski** [comment]
@soc: I don't understand your comment. Can you be more specific?

**Comment by soc** [comment]
The change to `TraversableOnce` was already done in https://github.com/scala/scala/pull/1424/files#L4L365.

**Comment by gkossakowski** [comment]
Oh, I see. Yeah, that's not a huge problem because it merges cleanly.

LGTM.

**Pull request merged**
