### PR TITLE
Fixing OSGi distribution.

### PR DESCRIPTION
**Pull request by jsuereth**
Apparently you have to resort to all manners of awesome in ant.  Probably better to
filter in what you awnt to copy rather than overwrite.  So far ths works.

Review by @lrytz or @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
could you comment on why only these files are needed and not some of the others I see in the lib directory of an older distribution?

**Comment by jsuereth** [comment]
It's a matter of where they come from.   If you look at the context, you can see the filtered ones are non-osgi while the osgi bundles are copied from a different location.

**Comment by jsuereth** [comment]
See newly improved comment.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
