### PR TITLE
Avoid key lookup unless null is involved

### PR DESCRIPTION
**Pull request by som-snytt**
Only if Java Map.compute says current value is null,
look up key to distinguish absence from null value.

This is the solution proposed after fatigue had set in at https://github.com/scala/scala/pull/9344#issuecomment-734962035

### CODE REVIEW

**Comment by som-snytt** [comment]
It says

> [The build](https://app.travis-ci.com/github/scala/scala/builds/247209439) errored.

but means

> The build erred.

Travis would like to know why would anyone use yaml?

Maybe @SethTisue knows. I thought "expand the matrix" was when they film another sequel.

**Comment by SethTisue** [comment]
I restarted the job.

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
cc @Ichoran, as you were in the discussions at https://github.com/scala/scala/pull/9344

**Comment by som-snytt** [comment]
sorry to wake @Ichoran

**Comment by SethTisue** [comment]
The monster-movie classic “Godzilla vs. Ichoran” (Toho Co., 1962) makes cinematically vivid the potential dangers of awakening "Tyrannosaurus" Rex Kerr from his centuries-long slumber beneath the waves.

Let's merge in another week or so if there is isn't any further feedback from @scala/collections or from the fearsome giant predator himself.

**Pull request merged**
