### PR TITLE
REPL: Indicate deprecated methods when displaying signatures

### LINKED ISSUE #12279: REPL: display of method signatures should indicate when a method is deprecated
```
scala 2.13.4> "foo".pr<TAB>
prefixLength( (deprecated)   prepended(                   prependedAll(                product(
```

so far so good, but now:

```scala> "foobar".prefixLength<TAB>
final def prefixLength(p: Char => Boolean): Int
```

this should also have a `(deprecated)` after it, IMO

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
Appending a description to a method signature

Fixes scala/bug#12279

### CODE REVIEW

**Comment by dwijnand** [comment]
Very nice PR, @jxnu-liguobin, thank you and welcome!

You mentioned "It's not clear how to write tests for println" in the issue: we have some existing tests you can copy from, look for tests in `test/files/run` that have `extends ReplTest` and let us know if you run into any problems with that.

**Comment by jxnu-liguobin** [comment]
@dwijnand 
image

**Comment by jxnu-liguobin** [comment]
Solved, the original need to execute SBT in the root directory. By the way, how is the ```Tab``` expressed in the test?

**Comment by dwijnand** [comment]
Oh yeah, good point. 😄   Have a look at test/files/run/repl-completions.scala or generally look for "completions" maybe there are other ways.

**Comment by jxnu-liguobin** [comment]
> Oh yeah, good point. 😄 Have a look at test/files/run/repl-completions.scala or generally look for "completions" maybe there are other ways.

Oh, No,The completions command does not return to the method's desc, even the match is successful

**Comment by jxnu-liguobin** [comment]
@SethTisue 
Excuse me, I've seen a lot of test code, but I can't find an example that needs to trigger println through tab. The test I put in run will be compiled, as follows:
```
-scala> "foo".prefixLength
-             ^
-       error: missing argument list for method prefixLength in trait SeqOps
-       Unapplied methods are only converted to functions when a function type is expected.
-       You can make this conversion explicit by writing `prefixLength _ ` or `prefixLength(_ )` instead of `prefixLength`.
```
but expect is(This result is not from compiled or run)
```
final def prefixLength(p: Char => Boolean): Int (deprecated)
```

**Comment by dwijnand** [comment]
The other one I couldn't remember is `CompletionTest.scala`, but maybe you've looked at that one already too :-/

**Comment by jxnu-liguobin** [comment]
> The other one I couldn't remember is `CompletionTest.scala`, but maybe you've looked at that one already too :-/

Yes, this bug is related to println(when use tab), not to completioncandidate

**Comment by SethTisue** [comment]
This would be easier to test if `cc.defString` itself were altered to include the additional string. Then the UI code, which is hard to test, could remain unchanged.

Would doing it that way break anything...? As far as I can recall, `defString` is only intended for presentation in the UI anyway?

**Comment by jxnu-liguobin** [comment]
> As far as I can recall, `defString` is only intended for presentation in the UI anyway?

```defString``` will be added to the value of newCandidates, So, if  modify defString directly, the value of Jline will be modified.

```scala
    def candidateForResult(cc: CompletionCandidate): Candidate = {
      val value = cc.defString // The value that will be used for the actual completion
      ... ....
      new Candidate(value, displayed, group, obtainDesc(cc), suffix, key, complete)
    }
```

**Comment by SethTisue** [comment]
@jxnu-liguobin there is a weird hack (it predates me, and I don't know why it was done this way) where the code uses `defString` in two different ways, as indicated by this comment:

```scala
      // the presence of the empty string here is a signal that the symbol
      // is already complete and so instead of completing, we want to show
      // the user the method signature. there are various JLine 3 features
      // one might use to do this instead; sticking to basics for now
      case "" :: defStrings if defStrings.nonEmpty =>
```

in this code path, `defString` contains different data. rather than containing just a method name, it contains an entire signature. this does not affect normal tab completion.

the other half of this hack is in `PresentationCompilation.scala`:

```
      def defStringCandidates(matching: List[Member], name: Name, isNew: Boolean): Candidates = {
        val ccs = for {
          member <- matching
          if member.symNameDropLocal == name
          sym <- if (member.sym.isClass && isNew) member.sym.info.decl(nme.CONSTRUCTOR).alternatives else member.sym.alternatives
          sugared = sym.sugaredSymbolOrSelf
        } yield {
          val tp = member.prefix memberType sym
          CompletionCandidate(
            defString = sugared.defStringSeenAs(tp),
            arity = memberArity(member),
            isDeprecated = isMemberDeprecated(member),
            isUniversal = isMemberUniversal(member))
        }
        (cursor, CompletionCandidate("") :: ccs.distinct)
      }
```

and `defStringCandidates` is only called when `tabAfterCommonPrefixCompletion || doubleTab` is true

so it seems to me that it should be safe for `defStringCandidates` to add the " (deprecated)" itself, rather than waiting and letting the UI code do it downstream. but I haven't tried it, so it's certainly possible I'm missing something.

this business with `""` is definitely ugly and ideally would be refactored, but at the moment, it's the code we have.

**Comment by jxnu-liguobin** [comment]
@SethTisue I tried it, the original single test no problem, seems to be ok? And ```Reader``` and ```RresentationCompilation ```should be changed carefully in the future.

**Review by SethTisue — APPROVED** [review]
Great! I've squashed it into a single commit; let's merge once CI likes it again.

Thank you, and welcome to the repo!

While I was reviewing this, I happened to notice a closely related bug: https://github.com/scala/bug/issues/12338 — perhaps you'd be interested in tackling that one next 😉

**Pull request merged**
