### PR TITLE
Fix dependant => dependent

### PR DESCRIPTION
**Pull request by julio**

### CODE REVIEW

**Comment by heathermiller** [comment]
Heh good catch, thanks, I never even noticed that one! LGTM!

**Comment by adriaanm** [comment]
thanks, have you signed our CLA already? (if you find some typos in that, I guess we're stuck)

**Comment by paulp** [comment]
Can one of the admins verify this patch?

**Comment by JamesIry** [comment]
I think @adriaanm is waiting on a CLA for this one.

**Comment by julio** [comment]
I'll send the CLA today.

**Comment by julio** [comment]
Just emailed the CLA pdf to Danielle Chamberlain, per the instructions.

**Comment by julio** [comment]
Danielle's auto-respond message says she won't have access to her inbox until July 2013.

**Comment by xeno-by** [comment]
@all IIRC Danielle is on a vacation right now. Maybe there's another contact person?

**Comment by julio** [comment]
Danielle's auto-respond message suggested another contact for urgent matters. I'm not sure this PR qualifies as urgent, but I forwarded the CLA anyway.

**Comment by adriaanm** [comment]
@julio Thanks a lot for jumping through all these hoops! We'll update the CLA instructions with contact info for someone who's available in a slightly nearer future. Sorry about that.

**Pull request merged**
