### PR TITLE
Don't just swallow `Throwables` while parsing bytecode. Print a warning

### PR DESCRIPTION
**Pull request by dragos**
..and go on.

This has caused hours of debugging, only to find out that 'package X does not have a member Y' were caused by a `NullPointerException`.

### CODE REVIEW

**Comment by dragos** [comment]
@lrytz or @hubertp, please? :)

**Comment by hubertp** [comment]
Any test case?

**Comment by dragos** [comment]
No. This is more a defense to find other bugs. If I knew a way to trigger an NPE or StackOverflowException, I'd fix that one instead. I believe catching `Throwable` silently is enough of a bad practice on its own.

**Comment by hubertp** [comment]
Seems reasonable. lgtm.

**Pull request merged**
