### PR TITLE
Correctly detect double defs involving param accessors & nilary methods

### PR DESCRIPTION
**Pull request by som-snytt**
NOTICE: This PR was substantially revised by #10846 — users should consult that PR description rather than this one.

**Old description:**

Conflicting definitions of class parameters and methods were incorrectly permitted, and now will error in Scala 2, as in Scala 3.

For example, the double definitions of `hasNext` and `next` are disallowed:
```
class MyIterator[T](hasNext: T => Boolean, next: T => T) extends AbstractIterator[T] {
  private var s: T = _
  override def hasNext: Boolean = hasNext(s)
  override def next(): T = next(s)
}
```

Noticed at https://github.com/scala/scala3/issues/20006

### CODE REVIEW

**Comment by som-snytt** [comment]
Sometimes code doesn't need more comments but just a better variable name.

**Review by lrytz — APPROVED** [review]
I can follow the new logic and not the old one, so that's very good :)

**Comment by lrytz** [comment]
This is probably worth "release-notes" for people who run into it after upgrading. Could you update the PR description, add a small example?

**Comment by lrytz** [comment]
Travis build https://app.travis-ci.com/github/scala/scala/jobs/625096268

```
[info] Main Scala API documentation to /home/travis/build/scala/scala/build/scaladoc/partest...
[error] /home/travis/build/scala/scala/src/partest/scala/tools/partest/instrumented/Profiler.java:65:31: method isProfiling is defined twice;
[error]   the conflicting variable isProfiling was defined at line 28:32
[error]         public static boolean isProfiling() {
[error]                               ^
[error] one error found
...
[error] (partest / Compile / doc) Scaladoc generation failed
```

**Comment by lrytz** [comment]
Also this used to work in 2.13.14, I wonder if there's a lot of code out there that relies on it

```
Welcome to Scala 2.13.14 (OpenJDK 64-Bit Server VM, Java 21.0.1).
Type in expressions for evaluation. Or try :help.

scala> class T {
     |   private[this] var x: Int = 0
     |   def x(): Int = x
     |   def x_=(n: Int) = x = n
     | }
class T

scala> val t = new T
val t: T = T@573870cb

scala> t.x()
val res0: Int = 0

scala> t.x = 42
// mutated t.x

scala> t.x()
val res1: Int = 42
```

**Comment by lrytz** [comment]
Test case for the Java issue, `-Ypickle-java` is useful to make the compiler force all Java members: https://github.com/scala/scala/compare/2.13.x...lrytz:scala:i20006-java?expand=1

**Comment by lrytz** [comment]
Submitted https://github.com/scala/scala/pull/10844 for the Java interop issue.

We might have to tone down the tighter check to a warning first before making it fatal in a next release, or maybe even make it a Scala 3 migration warning? Seth will say more about community build failures. We're not in a rush to change it: the Scala 2 behavior is not as specced, but it's benign.

**Comment by som-snytt** [comment]
I didn't notice the long tail because I've started unsubscribing from done things, so I won't see a notification unless mentioned.

I agree to make it a migration warning, which is more useful and not harmful. I'll submit that PR in case you want to review it.

(I didn't at-mention anyone here.)

**Comment by lrytz** [comment]
@som-snytt thanks! @som-snytt i guess at-mentioning is considered an escalation, so i didn't. always happy to review @som-snytt PRs, this time even without delay because we'll include it in 2.13.15.

**Comment by som-snytt** [comment]
OK I heard you. I'll submit at my next waking moment.

**Comment by SethTisue** [comment]
> I agree to make it a migration warning, which is more useful and not harmful

Agree that's the best course here.

**Pull request merged**
