### PR TITLE
SI-7602 Avoid crash in LUBs with erroneous code

### PR DESCRIPTION
**Pull request by retronym**
If a class contains a double defintion of a method that overrides
an interface method, LUBs could run into a spot where filtering
overloaded alternatives to those that match the interface method
fails to resolve to a single overload, which crashes the compiler.

This commit uses `filter` rather than `suchThat` to avoid the crash.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
Could you add a note to future refactorer/optimizer explaining why not `suchThat`?

**Comment by retronym** [comment]
done

**Comment by adriaanm** [comment]
LGTM!

**Comment by adriaanm** [comment]
actually, sorry, could you `s/multiple symbols/overloaded symbols/`?

**Comment by retronym** [comment]
Sure, done.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

I've taken three Jenkins nodes offline that seem to be failing (`typesafe-a2-*`).

**Comment by retronym** [comment]
Forgot a check file, that is the only change in the latest commit.

**Pull request merged**
