### PR TITLE
Fixes cut sentences in the generated scaladocs

### PR DESCRIPTION
**Pull request by dgruntz**
This commit changes all first sentences of library functions which
contain `i.e.` or `e.g.` and adds a `,` to prevent that the scaladoc
summary sentence is cut after this abbreviation.

This is possible as [pull/3824](https://github.com/scala/scala/pull/3824) fixed how Scaladoc parses the first
sentence of a method description into a sumary sentence (now the first
sentence has to end with a dot followed by whitespace).

Only docs in the core library are changed (src/library/*_/_.scala)
by this pull request and only if they occur in a first sentence.

Review by @heathermiller

### CODE REVIEW

**Comment by heathermiller** [comment]
Thanks @dgruntz :) LGTM

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by som-snytt** [comment]
I just noticed the one in Regex, remembered this PR and checked that you'd caught it. Nicely done.

**Comment by som-snytt** [comment]
...except I just noticed that this PR is against 2.12 and I'm working on 2.11...

**Comment by dgruntz** [comment]
I thought that I have to add new stuff to the newest branch and assumed, that if this is wrong, then the PR might be merged into the correct branch. If that is no longer possible then I could open a new pull request with the same changes against 2.11.

**Comment by gourlaysama** [comment]
Having 2.12.x as the default branch isn't so great for commits like this... anyway, that's another problem.

@dgruntz I just included your commit into a mass-backport PR (#3926) for 2.11.x, so you don't have to do anything :)

**Comment by som-snytt** [comment]
Just parking my observation here: Function.chain has an ellipsis with the same effect.

**Comment by dgruntz** [comment]
You mean the `andThen ... andThen`. But how could that be fixed (if no HTML can be used)? One could ignore dots within a backquote marked part, but I would prefer a simpler solution.

**Pull request merged**
