### PR TITLE
Actors - allow setting of timeout for opening remote Socket connections

### PR DESCRIPTION
**Pull request by martinmcnulty**
This is a fix for the issue raised by Chris Marshall in SI-5734 which should alleviate problems where opening a Socket to a remote Node blocks (for up to a minute in our experience) not allowing other remote messages to be sent during this time.  An optional timeout can be set through a system property that is passed to the Socket when it is connected.

Default behaviour is unchanged, since the property defaults to 0, which signifies "no timeout" to the java.net.Socket.

### CODE REVIEW

**Comment by retronym** [comment]
Thanks for the contribution.

Can you please squash the two commits into one and change the message to:

```
SI-5734 Allow setting of socket timeout for remote actors

Description of what was wrong before.

What you changed, and how that fixes the problem.

How to verify the change works.
```

More details on commit message style: https://github.com/scala/scala/blob/master/CONTRIBUTING.md

BTW, Scala Actors are in the process of deprecation in favour of Akka actors, so to accept contributions in this area, we need to make them easy to review (well documented/tested/etc.)

**Comment by martinmcnulty** [comment]
Thanks @retronym, I've squashed the commits and updated the message.  Sorry for not reading to the end of the guidelines before.  I realise Scala Actors are deprecated but we have an app in production that would be difficult to migrate to Akka.  This patch has fixed the problems we were having with it in production, so I thought I'd share it.

**Comment by adriaanm** [comment]
@martinmcnulty, thanks for your contribution! Unfortunately, there won't be another 2.10.1 release, so could you please target the 2.10.x branch instead? Thanks!

**Comment by martinmcnulty** [comment]
@adriaanm - thanks.  Reopened as #2480.  I've targeted master, with a note to backport to 2.10.x because I think it should be included in future 2.11.x releases as well.  Hope that's ok.

**Pull request closed without merging**
