### PR TITLE
Changes around lint

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @paulp

**Comment by paulp** [comment]
This will LGTM after the -> in foreachEntry becomes a direct tuple creation.

**Comment by vigdorchik** [comment]
It did already. Please take another look and sorry for not notifying.

**Comment by paulp** [comment]
Weird, this is some kind of github fail. I thought I had seen that changed, but looking at it today I only saw the arrow.

**Comment by paulp** [comment]
So if I look at the individual commit 1bcdca4, I see the arrow. If I look at "files changed", I see the tuple. But the commits listed for the pull requests are 1bcdca4 and  c899887. This is not increasing my confidence in what github is representing.

**Comment by paulp** [comment]
Now I see the right commits. I'll hope it's bad browser cache or something. LGTM.

**Pull request merged**
