### PR TITLE
SI-3368 Default to coalescing for 2.11

### PR DESCRIPTION
**Pull request by som-snytt**
Preserve current behavior (no PCData nodes, only Text)
for 2.11.

The coalescing flag is on if enabled or if source level
is not 2.12 and no flag was supplied.

The subtle change is that adjacent Text nodes are thereby
coalesced. This happens in the presence of CData sections,
but this is at the discretion of the parser anyway.

Also, no PCData nodes are emitted under coalescing, even
if there were no sibling text nodes. That is the correct
behavior: the general idea is that coalescing mode says,
I only want to deal with text.

### CODE REVIEW

**Comment by som-snytt** [comment]
This is a tweak to https://github.com/scala/scala/pull/4306

**Comment by som-snytt** [comment]
/rebuild

Guessing spurious because ide. `changingManyPreferencesAtOnce` is the failure and it looks sensitive to slow CI, what with `maxIdlenessLengthMillis` and little sleeps.

I have no idea what this means --

```
// decrease max length to lower than current inactivity duration but disable closing
```

but next time someone asks, How ya doin'?, I'm going to reply, Lower than current inactivity duration.

**Comment by adriaanm** [comment]
I've bene looking into saving time here, e.g.: https://github.com/scala-ide/uber-build/pull/71

**Comment by adriaanm** [comment]
Scabot doesn't expose fine-grained enough rebuild, sadly -- I've been hitting rebuild directly on jenkins to avoid redoing validate-test. I'm going to cancel the full rebuild since the IDE-only rebuild was already pending. Behemoth numero duo was slow to come up, it seems.

Another fine day in infrastructure land.

**Comment by adriaanm** [comment]
/nothingtoseehere -- the IDE run will pop up soon

**Comment by adriaanm** [comment]
/nothingtoseehere -- the IDE run will pop up soon

**Comment by adriaanm** [comment]
My priority is to get our nightly back up, and it will run before the IDE job will finish, so I'm going to merge this, as it LGTM, and will take it upon me to fix the IDE build if for some bizarre reason it fails for reals.

**Comment by adriaanm** [comment]
LGTM -- thanks, @som-snytt!

**Comment by som-snytt** [comment]
OK @adriaanm , thx, I guess I can't break the build worse at this point.

I tried to bounce the ball back quicker, but it turns out that a setting with `default = coalescing` means what is enabled for `-Xxml` with no flag, as for `-Xlint`, obviously. Sometimes the obvious is elusive.

**Comment by adriaanm** [comment]
No worries -- the breakage was due to some pretty dubious test in scala-xml, of course.

Sorry, I'm having a hard time parsing 

>  that a setting with `default = coalescing` means what is enabled for `-Xxml` with no flag, as for `-Xlint`, obviously

**Comment by som-snytt** [comment]
I tried and failed to make coalescing default to true by using the wrong mechanism, is all. I shouldn't have called the parameter "default" when you create a MultiChoiceSetting; a year later, that simple thing wasted some of my time. Ha. I don't know the emoji for that. A snake biting itself in the ass?

**Comment by adriaanm** [comment]
:orobourous:?

**Comment by som-snytt** [comment]
I was gonna add, if snakes had asses, but this is close :dragon: Or that might actually be "chasing your own tail".

**Pull request merged**
