### PR TITLE
Catch up with 2.11.x

### PR DESCRIPTION
**Pull request by adriaanm**
transcript:

```
g merge -s ours 9422e7a
g merge 011cc7e
g merge -s ours 3f437a2 -m"Merge 2.11.x into 2.12.x\n\nSkip to 3f437a2 Merge pull request #5730"
g merge 828a892
g merge -s ours 363d9e5 -m"Merge 2.11.x into 2.12.x\n\nSkip to 363d9e5 Merge pull request #5781"
g merge 99f41a1
g merge -s ours 6008e4b -m"Merge 2.11.x into 2.12.x\n\nSkip to 6008e4b Bump versions on 2.11.9 release"
g merge 94dd1dc
g revert f24c260
g revert eb5c513
g revert d540bf0
g merge -s ours 7fa3823 -m"Merge 2.11.x into 2.12.x\n\nSkip to 7fa3823 (2.11.x HEAD)"
```

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]

**Comment by SethTisue** [comment]
@adriaanm did you want to wait for @szeiger to have a look, or shall we just hit merge?

**Comment by adriaanm** [comment]
I think this is good to go

**Pull request merged**
