### PR TITLE
Render scala.full.version to versions.properties.

### PR DESCRIPTION
**Pull request by adriaanm**
When called with -Dupdate.versions, the build will render its current
set of versions to versions properties. This is used during releases,
when bootstrapping to a consistent set of modules that constitute
a release.

Particularly, scala.full.version is the non-SNAPSHOT full version
of scala that's closed to maven.version.number. It's similar in
spirit to the module build's snapshotScalaBinaryVersion,
except that it's always the full version, so, e.g., 2.11.1 rather than 2.11.

This version is so far only used to determine the dependency on
scala-continuations-plugin in scala-dist.

Review by @retronym. See also https://github.com/scala/jenkins-scripts/pull/91

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

Maybe also a good idea to duplicate the essence of this commit comment in versions.properties.

**Comment by adriaanm** [comment]
Good point.

**Comment by adriaanm** [comment]
Updated.

**Comment by adriaanm** [comment]
Note the pending reversion in the linked PR.

**Pull request merged**
