### PR TITLE
SI-8214 AnyRefMap should not be final

### PR DESCRIPTION
**Pull request by Ichoran**
AnyRefMap is now not final; instead, the interrelated core methods for retrieval/removal are marked final.

Additionally, the defaultEntry field has been removed, and the overriding method for specifying a default has been restored.

The same changes have been made to LongMap also (as that has the same design).

Tests have been modified appropriately.

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

**Comment by adriaanm** [comment]
Thanks for doing the rework, @Ichoran. Could you please add a scaladoc paragraph on the class that specifies which methods should be overridden together?

I made a quick overview using power mode:

```
Welcome to Scala version 2.11.0-6b4048b-SNAPSHOT (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_65).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :power
** Power User mode enabled - BEEP WHIR GYVE **
** :phase has been set to 'typer'.          **
** scala.tools.nsc._ has been imported      **
** global._, definitions._ also imported    **
** Try  :help, :vals, power.<tab>           **

scala> typeOf[scala.collection.mutable.AnyRefMap[_,_]].
     nonPrivateMembers.
       filterNot(_.isFinal).
       filterNot(_.isSpecialized).toList.
         groupBy(_.owner).mapValues(x => 
           x.sortBy(_.name).map(_.initialize.defString)).toList.
         sortBy{ case (owner, _) => owner.name }.
         foreach { case (owner, members) =>
           println(s"Defined in $owner:"); members foreach (m => println(s"\t$m"))}

Defined in class AnyRefMap:
    def <init>(initialBufferSize: <?>): scala.collection.mutable.AnyRefMap[K,V]
    def <init>(): scala.collection.mutable.AnyRefMap[K,V]
    private[package collection] def <init>(initialBufferSize: Int,initBlank: Boolean): scala.collection.mutable.AnyRefMap[K,V]
    override def clone(): scala.collection.mutable.AnyRefMap[K,V]
    override def default(key: K): V
    override def empty: scala.collection.mutable.AnyRefMap[K,V]
    override def foreach[A](f: ((K, V)) => A): Unit
    def foreachKey[A <: <?>](f: <?>): Unit
    def foreachValue[A <: <?>](f: <?>): Unit
    protected[package collection] def initializeTo(m: <?>,sz: <?>,vc: <?>,hz: <?>,kz: <?>,vz: <?>): Unit
    def iterator: Iterator[(K, V)]
    def mapValuesNow[V1 <: <?>](f: <?>): scala.collection.mutable.AnyRefMap[K,V1]
    def transformValues(f: <?>): AnyRefMap.this.type
Defined in trait Builder:
    def mapResult[NewTo <: <?>](f: <?>): scala.collection.mutable.Builder[Elem,NewTo]
    def sizeHint(coll: <?>,delta: <?>): Unit
    def sizeHint(coll: <?>): Unit
    def sizeHint(size: <?>): Unit
    def sizeHintBounded(size: <?>,boundingColl: <?>): Unit
Defined in trait Function1:
    def compose[A](g: A => T1): A => R
Defined in trait GenMapLike:
    override def equals(that: Any): Boolean
    override def hashCode(): Int
Defined in trait GenericTraversableTemplate:
    def flatten[B](implicit asTraversable: A => scala.collection.GenTraversableOnce[B]): CC[B]
    def genericBuilder[B]: scala.collection.mutable.Builder[B,CC[B]]
    def transpose[B](implicit asTraversable: A => scala.collection.GenTraversableOnce[B]): CC[CC[B] @scala.annotation.unchecked.uncheckedVariance]
    def unzip[A1, A2](implicit asPair: A => (A1, A2)): (CC[A1], CC[A2])
    def unzip3[A1, A2, A3](implicit asTriple: A => (A1, A2, A3)): (CC[A1], CC[A2], CC[A3])
Defined in trait Growable:
    def +=(elem1: A,elem2: A,elems: A*): Growable.this.type
    def ++=(xs: <?>): Growable.this.type
Defined in trait Iterable:
    override def companion: scala.collection.generic.GenericCompanion[scala.collection.mutable.Iterable]
Defined in trait IterableLike:
    override def canEqual(that: Any): Boolean
    override def copyToArray[B >: A](xs: Array[B],start: Int,len: Int): Unit
    override def drop(n: Int): Repr
    def dropRight(n: Int): Repr
    override def exists(p: A => Boolean): Boolean
    override def find(p: A => Boolean): Option[A]
    override def foldRight[B](z: B)(op: (A, B) => B): B
    override def forall(p: A => Boolean): Boolean
    def grouped(size: Int): Iterator[Repr]
    override def head: A
    override def reduceRight[B >: A](op: (A, B) => B): B
    def sameElements[B >: A](that: scala.collection.GenIterable[B]): Boolean
    override def slice(from: Int,until: Int): Repr
    def sliding(size: Int,step: Int): Iterator[Repr]
    def sliding(size: Int): Iterator[Repr]
    override def take(n: Int): Repr
    def takeRight(n: Int): Repr
    override def takeWhile(p: A => Boolean): Repr
    override protected[this] def thisCollection: Iterable[A]
    override protected[this] def toCollection(repr: Repr): Iterable[A]
    override def toIterable: Iterable[A]
    override def toIterator: Iterator[A]
    override def toStream: scala.collection.immutable.Stream[A]
    override def view(from: Int,until: Int): scala.collection.IterableView[A,Repr]
    override def view: scala.collection.IterableView[A,Repr]
    def zip[A1 >: A, B, That](that: scala.collection.GenIterable[B])(implicit bf: scala.collection.generic.CanBuildFrom[Repr,(A1, B),That]): That
    def zipAll[B, A1 >: A, That](that: scala.collection.GenIterable[B],thisElem: A1,thatElem: B)(implicit bf: scala.collection.generic.CanBuildFrom[Repr,(A1, B),That]): That
    def zipWithIndex[A1 >: A, That](implicit bf: scala.collection.generic.CanBuildFrom[Repr,(A1, Int),That]): That
Defined in trait Map:
    def $init$(): Unit
    override def seq: scala.collection.mutable.Map[A,B]
    def withDefault(d: <?>): scala.collection.mutable.Map[A,B]
    def withDefaultValue(d: <?>): scala.collection.mutable.Map[A,B]
Defined in trait MapLike:
    override def -(elem1: A,elem2: A,elems: A*): This
    override def -(key: A): This
    override def --(xs: scala.collection.GenTraversableOnce[A]): This
    override def +[B1 >: B](elem1: (A, B1),elem2: (A, B1),elems: (A, B1)*): scala.collection.mutable.Map[A,B1]
    def +[B1 >: B](kv: (A, B1)): scala.collection.mutable.Map[A,B1]
    override def ++[B1 >: B](xs: scala.collection.GenTraversableOnce[(A, B1)]): scala.collection.mutable.Map[A,B1]
    def clear(): Unit
    override protected[this] def newBuilder: scala.collection.mutable.Builder[(A, B),This]
    override protected[this] def parCombiner: scala.collection.parallel.Combiner[(A, B),scala.collection.parallel.mutable.ParMap[A,B]]
    def remove(key: <?>): Option[B]
    def result(): This
    def retain(p: <?>): MapLike.this.type
    def transform(f: <?>): MapLike.this.type
    override def updated[B1 >: B](key: A,value: B1): scala.collection.mutable.Map[A,B1]
Defined in trait MapLike:
    protected class DefaultKeySet extends AbstractSet[A] with Set[A] with Serializable
    protected class DefaultValuesIterable extends AbstractIterable[B] with Iterable[B] with Serializable
    protected class FilteredKeys extends AbstractMap[A,B] with DefaultMap[A,B]
    protected class MappedValues[C <: <?>] extends AbstractMap[A,C] with DefaultMap[A,C]
    override def addString(b: StringBuilder,start: String,sep: String,end: String): StringBuilder
    def filterKeys(p: A => Boolean): scala.collection.Map[A,B]
    override def filterNot(p: ((A, B)) => Boolean): This
    def isDefinedAt(key: A): Boolean
    override def isEmpty: Boolean
    def keySet: scala.collection.Set[A]
    def keys: Iterable[A]
    def keysIterator: Iterator[A]
    def mapValues[C](f: B => C): scala.collection.Map[A,C]
    override def stringPrefix: String
    override def toBuffer[C >: (A, B)]: scala.collection.mutable.Buffer[C]
    override def toSeq: Seq[(A, B)]
    override def toString(): String
    def values: Iterable[B]
    def valuesIterator: Iterator[B]
Defined in class Object:
    protected[package lang] def finalize(): Unit
Defined in trait Parallelizable:
    def par: ParRepr
Defined in trait PartialFunction:
    override def andThen[C](k: B => C): PartialFunction[A,C]
    def applyOrElse[A1 <: A, B1 >: B](x: A1,default: A1 => B1): B1
    def lift: A => Option[B]
    def orElse[A1 <: A, B1 >: B](that: PartialFunction[A1,B1]): PartialFunction[A1,B1]
    def runWith[U](action: B => U): A => Boolean
Defined in trait Shrinkable:
    def -=(elem1: A,elem2: A,elems: A*): Shrinkable.this.type
    def --=(xs: <?>): Shrinkable.this.type
Defined in trait TraversableLike:
    def ++[B >: A, That](that: scala.collection.GenTraversableOnce[B])(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    def ++:[B >: A, That](that: Traversable[B])(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    def ++:[B >: A, That](that: scala.collection.TraversableOnce[B])(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    protected[this] type Self = Repr
    class WithFilter extends FilterMonadic[A,Repr]
    def collect[B, That](pf: PartialFunction[A,B])(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    def dropWhile(p: A => Boolean): Repr
    def filter(p: A => Boolean): Repr
    def flatMap[B, That](f: A => scala.collection.GenTraversableOnce[B])(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    def groupBy[K](f: A => K): scala.collection.immutable.Map[K,Repr]
    def hasDefiniteSize: Boolean
    def headOption: Option[A]
    def init: Repr
    def inits: Iterator[Repr]
    def last: A
    def lastOption: Option[A]
    def map[B, That](f: A => B)(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    def partition(p: A => Boolean): (Repr, Repr)
    def repr: Repr
    def scan[B >: A, That](z: B)(op: (B, B) => B)(implicit cbf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    def scanLeft[B, That](z: B)(op: (B, A) => B)(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    def scanRight[B, That](z: B)(op: (A, B) => B)(implicit bf: scala.collection.generic.CanBuildFrom[Repr,B,That]): That
    private[package scala] def sliceWithKnownBound(from: Int,until: Int): Repr
    private[package scala] def sliceWithKnownDelta(from: Int,until: Int,delta: Int): Repr
    def span(p: A => Boolean): (Repr, Repr)
    def splitAt(n: Int): (Repr, Repr)
    override def tail: Repr
    def tails: Iterator[Repr]
    override def to[Col[_]](implicit cbf: scala.collection.generic.CanBuildFrom[Nothing,A,Col[A @scala.annotation.unchecked.uncheckedVariance]]): Col[A @scala.annotation.unchecked.uncheckedVariance]
    def toTraversable: Traversable[A]
    def withFilter(p: A => Boolean): scala.collection.generic.FilterMonadic[A,Repr]
Defined in trait TraversableOnce:
    def :\[B](z: B)(op: (A, B) => B): B
    def /:[B](z: B)(op: (B, A) => B): B
    def addString(b: StringBuilder): StringBuilder
    def addString(b: StringBuilder,sep: String): StringBuilder
    def aggregate[B](z: => B)(seqop: (B, A) => B,combop: (B, B) => B): B
    def collectFirst[B](pf: PartialFunction[A,B]): Option[B]
    def copyToArray[B >: A](xs: Array[B]): Unit
    def copyToArray[B >: A](xs: Array[B],start: Int): Unit
    def copyToBuffer[B >: A](dest: scala.collection.mutable.Buffer[B]): Unit
    def count(p: A => Boolean): Int
    def fold[A1 >: A](z: A1)(op: (A1, A1) => A1): A1
    def foldLeft[B](z: B)(op: (B, A) => B): B
    def max[B >: A](implicit cmp: Ordering[B]): A
    def maxBy[B](f: A => B)(implicit cmp: Ordering[B]): A
    def min[B >: A](implicit cmp: Ordering[B]): A
    def minBy[B](f: A => B)(implicit cmp: Ordering[B]): A
    def mkString: String
    def mkString(sep: String): String
    def mkString(start: String,sep: String,end: String): String
    def nonEmpty: Boolean
    def product[B >: A](implicit num: Numeric[B]): B
    def reduce[A1 >: A](op: (A1, A1) => A1): A1
    def reduceLeft[B >: A](op: (B, A) => B): B
    def reduceLeftOption[B >: A](op: (B, A) => B): Option[B]
    def reduceOption[A1 >: A](op: (A1, A1) => A1): Option[A1]
    def reduceRightOption[B >: A](op: (A, B) => B): Option[B]
    protected[this] def reversed: List[A]
    def sum[B >: A](implicit num: Numeric[B]): B
    def toArray[B >: A](implicit evidence$1: scala.reflect.ClassTag[B]): Array[B]
    def toIndexedSeq: scala.collection.immutable.IndexedSeq[A]
    def toList: List[A]
    def toMap[T, U](implicit ev: <:<[A,(T, U)]): scala.collection.immutable.Map[T,U]
    def toSet[B >: A]: scala.collection.immutable.Set[B]
    def toVector: Vector[A]
```

**Comment by adriaanm** [comment]
Seriously, though... I disagree (and I know you do as well) with making AnyRefMap non-final until we have clear documentation that explains how to deal with all these methods when subclassing.

**Comment by Ichoran** [comment]
Everything that should be overridden together is marked final, or is no worse for `AnyRefMap` than for `HashMap` and friends.  This way we at least aren't any _less_ safe than we were before, and we are more consistent with `HashMap`.  So, if you knew how to override `reduceLeft` for `HashMap`, you know how to for `AnyRefMap`.  If you didn't, well, hopefully you have enough sense not to think it's better with `AnyRefMap` than `HashMap`.

I agree that eventually we want to move towards knowing how to override everything that's overridable, and have everything else non-overridable.  But I'm not sure this is the time to do it; this is a pretty sizable goal, and 2.11 is just around the corner.  (Leaving `AnyRefMap` final would also serve this interest equally well.)

**Comment by adriaanm** [comment]
Thanks, sorry if I wasn't clear: I was trying to make the case for just leaving AnyRefMap final, since the precondition for letting people inherit it safely is prohibitively hard to satisfy.

**Pull request closed without merging**
