### PR TITLE
upgrade to newer scala-xml (namely 1.0.5)

### PR DESCRIPTION
**Pull request by SethTisue**
there shouldn't be user-visible changes since 1.0.4, but regardless,
it's good to depend on the latest

### CODE REVIEW

**Comment by SethTisue** [comment]
integrate-ide failure is unrelated; it's being tracked at https://github.com/scala/scala-dev/issues/97

**Comment by SethTisue** [comment]
review by @lrytz ?

**Comment by lrytz** [comment]
LGTM!

**Comment by SethTisue** [comment]
1.0.6 was released in September 2016. there aren't reports of regressions, but maybe most people aren't using the new version, either. it's a judgment call, but I would lean towards just sticking with 1.0.5 for 2.11.9

**Pull request merged**
