### PR TITLE
Improve type printing (toString/debugging)

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
@paulp Could you have a look if everything is to your liking?

**Comment by adriaanm** [comment]
The first two commits LGTM modulo minor cleanups. We should consider e505f8f in a separate PR and make sure SBT and the IDE are not affected.

**Comment by soc** [comment]
I removed the third one. I can't put the third one into a separate PR until this PR is merged, because it depends on `typedInternal` which was added in 4d6be05.

**Comment by adriaanm** [comment]
LGTM -- I'll merge on Friday.

We're also trying to manoeuvre to a known-good state for the IDE, and this may require changes to the test suite there, so I'd like to at least give it another day for one IDE validation to pass before we move away from equilibrium again.

**Comment by paulp** [comment]
I have been too fully liberated from this code to add anything. It cannot look anything but good to me if it is destined for mergeville.

**Comment by gkossakowski** [comment]
@adriaanm: ping

**Comment by adriaanm** [comment]
ide validation passed

**Comment by retronym** [comment]
:clap: 

For full impact, run with:

```
JAVA_OPTS=-Dscala.color scalac
```

image

**Comment by paulp** [comment]
Unless you have something nonstandard going on in your runner world, you can `scalac -Dscala.color`.

Although I guess JAVA_OPTS offers a place to have it going all the time.

**Comment by paulp** [comment]
Also, color always requires iteration before it's any good. This was just my first whack at it.

**Comment by retronym** [comment]
Hmmm, I wonder what is going on here:

`/code/scala sh -x qbin/scalac -Dscalac.color -Ytyper-debug sandbox/test.scala`
image

**Comment by retronym** [comment]
PEBKAC. `s/scalac.color/scala.color/`.

**Comment by paulp** [comment]
Oh PEBKAC, will you ever stop supplying us with bugs.

**Comment by paulp** [comment]
I've been vaguely fantasizing about "typechecking" this sort of thing though.

**Pull request merged**
