### PR TITLE
Fixes SI-5857.

### PR DESCRIPTION
**Pull request by axel22**
Override `min` and `max` in `Range` and `NumericRange`
to check if a default `Ordering` for the numeric type
in question is used.
If so, bypass traversal and compute the minimum or
maximum element.

Review by @retronym.

### CODE REVIEW

**Comment by retronym** [comment]
Implementation looks okay, if a little tricky. I wonder if it's really worth to add even more complexity to `NumericRange`?

**Comment by axel22** [comment]
Personally, I think it's not paramount to have this on `NumericRange`, as I don't think too many people make a living from calling `max` on it :), but I did it for the sake of consistence.

We can also just keep this thing on the `Range`.
Of course, if you have another idea how to hack around the implicit `Ordering` on `min` and `max`, I'm open to suggestions.

**Comment by jsuereth** [comment]
So.. should I merge this?

**Comment by axel22** [comment]
As far as I see things, we can keep the `min` and `max` overrides in `NumericRange`s for now, for consistency reasons.
I think opinions against are not very strong.

So, I think we can merge.

**Pull request merged**
