### PR TITLE
Si 6663 2.10.x fix type parameter on selectDynamic

### PR DESCRIPTION
**Pull request by jannic**
The first commit fixes the bug reported in [SI-6663](https://issues.scala-lang.org/browse/SI-6663), the second one another similar case as noted in [a comment](https://issues.scala-lang.org/browse/SI-6663?focusedCommentId=60935&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60935) on that bug report.

I'd guess that there are other possible contents of cxTree not yet handled. Is there a better way to fix this than to add all such cases manually to mkInvoke?

Same as [pull request 1619](https://github.com/scala/scala/pull/1619), but targeted at 2.10.x, as requested by @retronym.

Review by @namin (also requested by @retronym)

### CODE REVIEW

**Comment by namin** [comment]
LGTM.

**Comment by adriaanm** [comment]
please squash these commits and update your pull request by `push --force`ing to your repo on github

these fixes for the same ticket are small enough to go in one commit so we keep our history easy to follow

**Comment by jannic** [comment]
ok, done.
(and sorry for screwing up the rebase first, in case someone noticed)

**Comment by adriaanm** [comment]
awesome, thanks!

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Thanks for the fix!

**Pull request merged**
