### PR TITLE
Unifying -Ydelambdafy:{inline, method}

### PR DESCRIPTION
**Pull request by retronym**
Avoid code duplication and use a common approach for
symbol substituion.

I asked Martin "why did the apply method just reuse the parameter symbols
of the lambda verbatim", to which he suggested at the time substitution
wasn't up to scratch to risk anything more principled.

Turns out it still isn't, but I've taken steps to remedy that
in this incarnation of the pull request.

### CODE REVIEW

**Comment by JamesIry** [comment]
LGTM!

**Comment by retronym** [comment]
I'd like @odersky or @adriaanm to opine on the change to `SubstMap` as that is pretty core.

**Comment by adriaanm** [comment]
I think substituting in a ClassInfoType's parents is the right thing to do. I believe it was a performance optimization because those types were believed to be "more inert" (one, now invalid, assumption could be that they don't occur outside a class symbol's info).

I'd like this change to get its own commit though (and be squashed with b4ca1b10ec25fc0249583f17625b2e64bbabbd5e) -- otherwise, LGTM.

**Comment by retronym** [comment]
@adriaanm  I have so shuffled the deck of commits.

**Comment by adriaanm** [comment]
LGTM!

**Pull request merged**
