### PR TITLE
SI-8362: Support for Future without sun.misc.Unsafe.

### PR DESCRIPTION
**Pull request by mchv**
Since the  [work](https://github.com/scala/scala/pull/454/files) on `Future` performances, `AbstractPromise` is using `Unsafe` breaking the ability for `Future` to be executed on GAE.
At that time, @viktorklang [suggested to implement a fallback](https://github.com/scala/scala/pull/454#issuecomment-36927964) in case `Unsafe` is not available.
@carey [proposed an implementation](https://github.com/carey/scala/commit/72e1927793c6dc808d9896e5571a97f136fd1a4e), but as far as I know he never created a pull request for it, so there it is.

Please comment if some improvement or changes are needed, so I could try to improve. 

See [SI-8362](https://issues.scala-lang.org/browse/SI-8362) for more details.

### CODE REVIEW

**Comment by adriaanm** [comment]
/rebuild -- having issues with jenkins spuriously disconnecting from workers

**Comment by viktorklang** [comment]
I think I prefer the 2.12.x solution: https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/impl/Promise.scala#L181

**Comment by carey** [comment]
I had a lot of trouble getting the Scala build tests to run, and getting Hotspot to tell me if it wasn't getting any slower, and eventually I gave up.

For the 2.12.x solution, that's extending `AtomicReference` instead of using `AtomicReferenceFieldUpdater`? That's much more elegant.

Until 2.12.x is released and Google App Engine supports Java 8, at least this change here would make Scala work on GAE without changing the superclass of `AbstractPromise`.

**Comment by He-Pin** [comment]
in fact AtomicReferenceFieldUpdater save bytes.
http://normanmaurer.me/blog/2013/10/28/Lesser-known-concurrent-classes-Part-1/

**Comment by carey** [comment]
Not the way Scala 2.12.x does it. 2.11's `AbstractPromise` contains a single field `_ref`, while 2.12 _extends_ `AtomicReference` which contains a single field `value`. However, `AtomicReferenceFieldUpdater.compareAndSet()` isn't necessarily even inlined by Hotspot, while `AtomicReference.compareAndSet()` should be compiled down to the machine's CAS instruction.

I'm quite impressed by how Scala 2.12.x does it.

For this pull request, as far as I could tell the Hotspot compiler would always notice that `_ref` was always -1, and generate the same code as before the patch. On GAE it will be a bit slower, but you wouldn't use that for raw performance.

**Comment by viktorklang** [comment]
@carey Thanks for the kind words regarding the 2.12.x implementation. What about the following proposal: Remove the Unsafe-usage from `AbstractPromise` in 2.11.x and make AbstractPromise extend AtomicReference?

**Comment by He-Pin** [comment]
if there is large instance of Promise,using the AtomicReferenceFieldUpdater will reduce the memory footprint.but one drawback is you have to write java code.

**Comment by viktorklang** [comment]
@hepin1989 Yes, compared to composing an AtomicX, but not extending one.

**Comment by carey** [comment]
The project manager in me isn't happy with a change like that in a minor release; on the other hand, I've just tested a simple version of it on App Engine and it works fine:

```
package scala.concurrent.impl;

class AbstractPromise extends java.util.concurrent.atomic.AtomicReference<Object> {
    protected final boolean updateState(Object oldState, Object newState) {
        return compareAndSet(oldState, newState);
    }

    protected final Object getState() {
        return get();
    }
}
```

**Comment by viktorklang** [comment]
@carey Given that it is a package-protected class in an `impl` package, it should be safe. @adriaanm wdyt?

**Comment by adriaanm** [comment]
So, what exactly would the 2.12 solution entail? Adding a new package-protected class to an impl package? (I tried to figure it out based on the commits/linked diff, but not sure.)

**Comment by viktorklang** [comment]
@adriaanm Like: https://github.com/scala/scala/pull/4313#issuecomment-74042035

**Comment by mchv** [comment]
I was suspicious changing implementation to match 2.12.x will break binary compatibility, and effectively it does:

```
Checking backward binary compatibility for scala-library (against 2.11.0)
     [mima] Found 1 binary incompatibiities (3 were filtered out)
     [mima] =====================================================
     [mima]  * the type hierarchy of class scala.concurrent.impl.Promise#DefaultPromise
     [mima]    has changed in new version. Missing types {java.lang.Object}
     [mima] Generated filter config definition
     [mima] ==================================
     [mima] 
     [mima]     filter {
     [mima]         problems=[
     [mima]             {
     [mima]                 matchName="scala.concurrent.impl.Promise$DefaultPromise"
     [mima]                 problemName=MissingTypesProblem
     [mima]             }
     [mima]         ]
     [mima]     }
     [mima] 
```

I have used following implementation

``` java
package scala.concurrent.impl;


import java.util.concurrent.atomic.AtomicReference;



abstract class AbstractPromise extends AtomicReference<Object> {

    protected final boolean updateState(Object oldState, Object newState) {
        return compareAndSet(oldState, newState);
    }

    protected final Object getState() {
        return get();
    }
}
```

**Comment by viktorklang** [comment]
@mchv 

DefaultPromise is in (https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/impl/Promise.scala#L153) which is  [`private[concurrent]`](https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/impl/Promise.scala#L44) so I don't see that it would cause any issues, but @adriaanm would know more.

**Comment by mchv** [comment]
The [jenkins failing build log](https://scala-ci.typesafe.com/job/scala-2.11.x-validate-test/228/console) of `AbstractPromise` extending `AtomicReference` (see https://github.com/scala/scala/pull/4313#issuecomment-74382139)

**Comment by viktorklang** [comment]
@mchv Yep, so it needs a mima exception added.

**Comment by mchv** [comment]
@viktorklang It looks to me that [ignoring private classes is currently unsupported by mima](https://github.com/typesafehub/migration-manager/issues/53), do you know if there is a way to specify explicitely a qualified classname to ignore?

**Comment by viktorklang** [comment]
@mchv I'm unsure, perhaps @dotta could elucidate us.

**Comment by mchv** [comment]
@viktorklang @dotta nevermind I just found [documentation about it](https://github.com/typesafehub/migration-manager/wiki/MiMa-Command-Line-Tool) and [associated filters file](https://github.com/scala/scala/blob/2.11.x/bincompat-backward.whitelist.conf) in codebase. I will update the pull request

**Comment by mchv** [comment]
@dotta may you review my changes related to mima?

**Comment by dotta** [comment]
@mchv The filter rules seems correct (and the build bot is happy).

Maybe one day someone will work on https://github.com/typesafehub/migration-manager/issues/34.

**Comment by adriaanm** [comment]
In general, I can't think of any real issue with adding a superclass (which contributes only final methods) to a class in an implementation package (as long as those methods were not introduced in any illicit subclasses of said class). 

I think this actual plays in favor of @viktorklang's solution in 2.12. If we're going to change superclasses, why not do it closest to the source? This is both clearer and more focussed, leaving those subclasses of `AbstractPromise` we never heard of unaffected. We could also deprecate `AbstractPromise` -- even in 2.11.6, since it's an internal class.

EDIT: forgot that java classes are package protected by default (in casu, `AbstractPromise`)

Since binary compatibility mistakes can tank whole releases, I'd like a second opinion from the others in @scala/team-core-scala

**Comment by adriaanm** [comment]
Since the 2.11.6 deadline is extremely nigh, I've tentatively postponed this PR (along with other recent ones) to 2.11.7. I'll make a pass through reviewed 2.11.7 PRs on Friday and move them back to 2.11.6 where feasible.

In the mean time, feel free to let me know if you'd like some help getting this reviewed by then.

**Comment by mchv** [comment]
@adriaanm @scala/team-core-scala Any update on planning to merge this for `2.11.7` ?

**Comment by gkossakowski** [comment]
FYI: I'll give binary compatibility thought today.

**Comment by lrytz** [comment]
[A burnt child dreads the fire](https://issues.scala-lang.org/browse/SI-8899). Still, to me it looks good in terms of binary compatibility.

**Comment by gkossakowski** [comment]
I also we are fine here when it comes to binary compatibility.

**Comment by adriaanm** [comment]
I'll adopt this PR. Going to have a look at some jars in the wild to see if there are any dependencies we may have missed.

**Comment by Ichoran** [comment]
It doesn't take much code to generate a problem:

``` scala
package scala.concurrent.impl
class AbPro extends AbstractPromise { def u = AbstractPromise.updater }
```

But I guess people normally don't do that (or we don't support them doing that; that's not what we mean by "binary compatibility"), so otherwise it should be good.  The optimizer doesn't seem to slurp anything untoward into the bytecode for concurrent.Promise.

**Comment by adriaanm** [comment]
Indeed -- i was going to just grep for any mention of scala.concurrent.impl.AbstractPromise. If you still have those jars expanded, maybe that would be convenient for you to pick up?

**Comment by Ichoran** [comment]
@adriaanm - I'm not sure where they went, actually.  I think I might have copied them from a USB drive to /tmp, then lost the USB drive.  I can do it anyway, though, if you'd like.  (Might need to tell me the best incantation to grab the right jars from Maven.)

**Comment by adriaanm** [comment]
Ok, no prob -- I'll look into it then.

**Comment by adriaanm** [comment]
Closing in favor of the rebased & slightly reworked #4443.

**Pull request closed without merging**
