### PR TITLE
Bump sbt.version to 0.13.12, without breaking

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes https://github.com/scala/scala-dev/issues/218

### CODE REVIEW

**Comment by dwijnand** [comment]
Fixes https://github.com/scala/scala-dev/issues/218

**Comment by SethTisue** [comment]
testing 0.13.13-RC1 over at https://github.com/scala/scala/pull/5409

**Comment by dwijnand** [comment]
Amended the commit to bump the version in `scripts/common` too (following the lead in #5409).

**Comment by SethTisue** [comment]
LGTM

**Pull request merged**
