### PR TITLE
SI-8388 consistently match type trees by originals

### PR DESCRIPTION
**Pull request by xeno-by**
Due to the fact that all TypTrees are transformed into TypeTrees
during typechecking one couldn't treat typed type trees in the same
way as they treat untyped type trees.

This change implements support for pattern matching of TypeTrees as their
corresponding TypTree equivalent using tree preserved in the original.

The implementation itself is a trivial wrapping of regular TypTree
extractors into MaybeTypeTreeOriginal.

### CODE REVIEW

**Comment by xeno-by** [comment]
Supersedes https://github.com/scala/scala/pull/3652

**Comment by retronym** [comment]
Another worry I have here, as discussed today:

``` scala
val tt = TypeTree(typeOf[String]).setOriginal(tq"scala.String")

t match { case t @ q"$a.$b" => t.tpe } // null?
```

An alternative would be to provide a tree transformer to convert all `TypeTree`-s in a tree to their originals (possibly duplicated with the `.tpe` fields set). One would need to explicitly call this before using quasiqotes to seek out `TypTree`s to deconstruct.

**Comment by densh** [comment]
@retronym I believe that we can work around this issues in minor updates in 2.11.x series if it turns out to be problematic (and meanwhile we can document current state of things with recommendation to extract types rather than match on original whenever possible). On the other hand if we don't make the first step in terms of adding syntactic equivalents of typtrees this decision will have to be fixed in stone for all of the 2.11 series due to binary compatibility constraints.

**Comment by retronym** [comment]
LGTM I'm feeling more optimistic about this today. You only get into the odd situations I described when you "opt in" by destrucuting types as `TypTree`s and you can always use `Liftable[Type]` to get to the contents of a `TypeTree`.

**Comment by densh** [comment]
Excellent, really glad that it made it in RC4! :cake:

**Pull request merged**
