### PR TITLE
wip: sammy always on [ci: last-only]

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by adriaanm** [comment]
yay -- looks like i can start rebasing :)

**Comment by sjrd** [comment]
:+1: 

(I'm so glad we've been testing Scala.js with `-Xexperimental` since the dawn of ages, now :-p)

**Comment by adriaanm** [comment]
Closing while I apply final coat of polish.

**Comment by adriaanm** [comment]
Moved to #4945

**Pull request closed without merging**
