### PR TITLE
SI-8143 Regressions with override checks, private members

### PR DESCRIPTION
**Pull request by retronym**
These regressed in e609f1f20b, which excluded all private methods from
overriding checks. We should only exclude private[this] members on the
low end of a pair, as was done before that commit, and, we must also
exclude private members on the high side.

Why? Warning: reverse engineered intuition follows.

We need to report an error when if a private method in a subclass
has matches a less-private method in the super class and report an
error, lest the user be fooled into thinking it might be invoked
virtually. On the other hand, adding a private method to a super
class shouldn't invalidate the choice names of public members in
its superclasses.

I've removed the test case added by that commit and will lodge a
reworked version of it that Paul provided as a new issue. That shows
a bug with qualified private + inheritance.

In addition, the expectation of `neg/accesses.check` is reverted
to its 2.10.3 version, which I believe is correct. When it was
changed in e609f1f20b it sprouted a variation, `neg/accesses-2`,
which has now changed behaviour. The intent of that test will
be captured in the aforementioned issue covering qualified private
inheritance.

Review by @adriaanm.

### CODE REVIEW

**Comment by paulp** [comment]
I don't know what's going on in the test which was checked in, but this is what I was trying to say.

```
package p1.p2 {
  abstract class A {
    private[p2] def f(): String = "A"
    override def toString = s"A:f=$f"
  }
  class C1 extends A {
    // Compiles, extending A directly
    override def toString = super.toString + " " + s"C1:f=$f"
  }
  class C2 extends p1.p3.B1 {
    // SHOULD compile - the f() defined in the superclass B1 is private,
    // so this f should refer to the f() inherited from A, which is visible
    // to us since we are in the same package. The f() defined in B1 should
    // not affect us in any way. That's what "private" means.
    override def toString = super.toString + " " + s"C2:f=$f"
    // a.scala:10: error: method f in class B1 cannot be accessed in p1.p2.C2
    //     override def toString = super.toString + " " + s"C2:f=$f"
    //                                                            ^
    // one error found
  }
  class C3 extends p1.p3.B2 {
    // Compiles, extending B2 which extends A.
    override def toString = super.toString + " " + s"C3:f=$f"
  }
}

package p1.p3 {
  abstract class B1 extends p1.p2.A {
    // SHOULD compile - the f() defined in the superclass A is private with a
    // scope which excludes us. That means it should not affect us in any way.
    // That's what "private" means.
    private def f(): String = "B1"
    // a.scala:24: error: overriding method f in class A of type ()String;
    //  method f has weaker access privileges; it should not be private
    //     private def f(): String = "B1"
    //                 ^
    // one error found
    override def toString = super.toString + " " + s"B1:f=$f"
  }
  abstract class B2 extends p1.p2.A {
    // Letting f pass through
    override def toString = super.toString + " " + "B2"
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    println(new p1.p2.C1)
    println(new p1.p2.C2)
    println(new p1.p2.C3)
  }
}
```

**Comment by paulp** [comment]
That test case is my whole review, because as everyone should know by now, I don't what access is supposed to do.

**Comment by retronym** [comment]
Closing temporarily as this still needs some work.

Expanding the test case:

``` scala
class Foo { def f = 5 }
class Bar extends Foo { private def f = 10 }


class Foo1 { private def f = 5 }
class Bar1 extends Foo1 { def f = 10 } // okay

class Foo2 { private def f = 5 }
class Bar2 extends Foo2 { private def f = 10 } // okay

class Foo3 { private[this] def f = 5 }
class Bar3 extends Foo3 { private def f = 10 } // okay

class Foo4 { private def f = 5 }
class Bar4 extends Foo4 { private[this] def f = 10 } // okay
```

shows the following two incorrect compiler errors wrt 2.10:

```
/Users/jason/code/scala/test/files/neg/t8143a.scala:6: error: overriding method f in class Foo1 of type => Int;
 method f cannot override final member
class Bar1 extends Foo1 { def f = 10 } // okay
                              ^
/Users/jason/code/scala/test/files/neg/t8143a.scala:9: error: overriding method f in class Foo2 of type => Int;
 method f has weaker access privileges; it should not be private
class Bar2 extends Foo2 { private def f = 10 } // okay
                                      ^
```

I'll have to restrict myself to regressions in this pass and push the fixes for qualified private to a new ticket. I don't see anything in `findMember` that corresponds to the specification that qualified private members "are also inherited only from templates inside C ." But thanks for the test case as it shines a clear light on the problem.

**Comment by paulp** [comment]
The bugs with this go on essentially forever, as I have long known. Because I am cruel, here are more.

```
package p {
  trait A {
    private[p] def f(): String = "A"
  }
  trait B extends A {
    // Here we're implementing a method with the same signature
    // as an inherited one, and we can see the inherited one, and
    // we are not required to override.
    private[B] def f(): String = "B/" + super.f()

    def hmm(x: B): String = {
      // Both implementations are visible externally, depending on static
      // type of receiver.
      val s1 = (x: A).f()
      val s2 = (x: B).f()
      "" + ((s1, s2))
    }
  }
  trait C extends B {
    // Written like this, fails as shown:
    //
    // private[p] def f(): String = "C"
    // a.scala:16: error: overriding method f in trait A of type ()String;
    //  method f needs `override' modifier
    //     private[p] def f(): String = "C"
    //                    ^
    // one error found
    //
    // But we can't call the method we're required to override!
    // Written like this, fails as shown:
    //
    // override private[p] def f(): String = "C" + super.f()
    // a.scala:27: error: method f in trait B cannot be accessed in p.B
    //       override private[p] def f(): String = "C" + super.f()
    //                                                         ^
    // one error found
  }

  object Test {
    def main(args: Array[String]): Unit = {
      val b = new B { }
      println(b hmm b)
      // prints: (A,B/A)
    }
  }
}
```

**Comment by retronym** [comment]
I've lodged your two test cases touching qualified private as SI-8155. I won't be able to address them for 2.11.

The workaround is to install a pair of methods: a final, qualified private accessor, which exposes a protected virtual method.

**Comment by paulp** [comment]
I don't think you will be able to address it, period. Access as presently semi-specified cannot be made consistent, and that's before we throw in the jvm-related challenges. So as long as it will be addressed never, I think it's okay not to address it for 2.11.

**Comment by adriaanm** [comment]
Plenty of wrongness in the privacy department, here's another one Martin pointed out to me last week:

```
class A {
  private val foo = 1
  (new B).foo // refchecks, but should not
}

class B extends A
```

**Comment by paulp** [comment]
>   (new B).foo // refchecks, but should not

Why not? If it were private[this] val foo, okay, but A can see the privates of another A, which a B certainly is. This shapes up to be either a mistake or a fascinating revelation.

**Comment by retronym** [comment]
Unqualified private members are not inherited, so should not be members of `B`.

I'll add this example to SI-7475 which is similar if not the same.

**Comment by paulp** [comment]
> Unqualified private members are not inherited, so should not be members of B.

It's not a member of B, it's a member of A! How can this be reconciled with LSP? Is a B an A or not?

**Comment by paulp** [comment]
What about this?

```
class A {
  private val foo = 1
  ((new B): A).foo
}
class B extends A
```

Are we saying the compiler isn't allowed to infer that it's an A? We insist on inferring a uselessly general type all over the place, on what basis would we pursue the opposite extreme in this case?

**Comment by paulp** [comment]
And in any case, is there not an implicit conversion from B to A by way of conforms? How on earth could this not typecheck?

**Comment by adriaanm** [comment]
private members are exempt from the substitution principle, as LSP only talks about the interface that can be observed from the outside (where the "outside" is either an inheritance client or an external method call)

**Comment by paulp** [comment]
1) What source instructs us "where the "outside" is either an inheritance client or an external method call" ?
2) There are still two more things to explain away: the compiler inferring a more general type and the implicit conversion from B to A.

**Comment by Ichoran** [comment]
Private members are not exempt from LSP because they are part of the supertype's self-interface.  private[this] members are exempt.  You can see why it is hopeless to do otherwise:

``` scala
  class A {
    private var p: String = ""
    def myKin(a: A) = a
    val b: B = new B
    b.p = "You claim I should be forbidden"
    def set(a: A) { a.p = "but of course I am allowed" }
    myKin(b).p = "and thus I am also allowed, what gives?"
  }
  class B extends A {}
```

**Comment by adriaanm** [comment]
To rephrase, LSP talks about types, and the private members of a class are not conceptually part of the type that describes that class (hence the use of nonPrivateMembers internally to drop them from ClassInfoType)

**Comment by paulp** [comment]
@Ichoran Well _I_ can see why it's hopeless to do otherwise, but prevailing opinion is going the other way. It's worth taking a moment to appreciate this achievement: language has been around for 10+ years but basic issues are still shrouded in a fog of mystery. Should there be a lot of 2-2 votes among the four of us?

**Comment by adriaanm** [comment]
```
class A {
  private val foo = 1
  def bar = println(((new B): A).foo)
  def baz = println((new B).foo)
}

class B extends A {
  // no override necessary, because it's unrelated to A's foo
  val foo = 2
}
```

**Comment by adriaanm** [comment]
I don't think it makes sense for the baz method to compile when there's no foo member in B, because when you add one and compile B separately from A, B's foo won't be called by A's baz.

**Comment by paulp** [comment]
It may be helpful to forget about LSP and make some attempt to deal with the implicit conversion from B to A, because LSP is academic.

```
    2. In a selection e.m with e of type T, if the selector m does not denote
       a member of T. In this case, a view v is searched which is applicable
       to e and whose result contains a member named m.
```

**Comment by adriaanm** [comment]
How about separate compilation? Is that academic? It's not unrelated to LSP.

**Comment by paulp** [comment]
"I don't think it makes sense for the baz method to compile when there's no foo member in B, because when you add one and compile it separately, it won't be called."

The inconveniences posed by separate compilation are not the least bit relevant to what is specified. If that's the argument here, then just say "we ignore the specification because it's too hard," don't say that a B isn't an A or that an implicit which applies everywhere else doesn't apply here.

**Comment by adriaanm** [comment]
I believe the implicit conversion is explained by my comment above that says private members are not part of the type.

**Comment by adriaanm** [comment]
The specification is designed to enable separate compilation.

**Comment by paulp** [comment]
Some parts of the spec which are followed are designed to enable separate compilation; others which are ignored are ignored probably for separate compilation. (One of the first and two of the second can be found in my last comment at https://issues.scala-lang.org/browse/SI-2568 ) I agree that enabling separate compilation is a common theme.

I'm going to chalk this up to "implementation considerations trump ability to reason about code" and go re-read some richard gabriel in the forest.

**Comment by Ichoran** [comment]
It's not about separate compilation per se, is it?  Just technical limitations.  If `B` does not declare a `foo`, then `A` can't call the `B` version of `foo`, only its own.  If you alter `B` later to add a `foo` method, you still can't have called it from `A` (just the same as if you try to call a `quux` method on `B` which didn't exist when you compiled `A`) unless you recompile `A`.  But you need to catch your mistakes somehow.

Not allowing `(new B).foo` is to avoid getting confused: simplifying, not necessary, though I admit that solving the mutual dependency problem is hard without that simplification.  Maybe impossible with the JVM, as `A` would need to declare that `B` has no `foo` so that when `B` is loaded it would generate an error.  If it could do that, everything would be LSP-compliant (at different levels of visibility) and safe for separate compilation.

Is it true that simply declaring that private members aren't part of the type will solve the theoretical problems?  How is it that instances of `A` know about the private members of other `A`s if it's not part of a type?  Surely, for example, `this.type <: A` for an instance of `A`, yet `this.type` has all the private members of `A` available.

**Comment by retronym** [comment]
The boundary comes down to whether or not they are inherited in subclasses.

This must compile:

``` scala
trait U
trait T {
  self: T with U =>
  private def foo = 0
  self.foo
}
```

So the private member in `U` is part of the compound type. My first naive attempt to fix SI-7475 broke this case.

**Comment by adriaanm** [comment]
It's not an implementation consideration. Both are pretty easy to implement, as shown by the existence of the bug.

**Comment by adriaanm** [comment]
> as A would need to declare that B has no foo so that when B is loaded it would generate an error.

yep, this is huge obstacle to implementing virtual classes, as the "accidental override" problem is much more pressing in that setting

**Comment by adriaanm** [comment]
> It's not about separate compilation per se, is it?

separate compilation is a proxy for modular reasoning about your code -- to avoid getting confused

**Comment by paulp** [comment]
> It's not an implementation consideration. 

SI-2568 isn't an implementation consideration?

**Comment by adriaanm** [comment]
> SI-2568 isn't an implementation consideration?

It is, but I thought we were talking about another it.

**Comment by retronym** [comment]
>  In this case, a view v is searched which is applicable to e and whose result contains a member named m.

The candidate, `Predef.conforms`, is not allowed as a view.

**Comment by paulp** [comment]
> The candidate, Predef.conforms, is not allowed as a view.

And that's completely unspecified, right? Maybe I'm not seeing it; the word "conforms" appears a lot.

```
      private def isIneligible(info: ImplicitInfo) = (
           info.isCyclicOrErroneous
        || isView && (info.sym eq Predef_conforms)
        || shadower.isShadowed(info.name)
        || (!context.macrosEnabled && info.sym.isTermMacro)
      )
```

I just kind of wonder how any user of the language could possibly know to expect this behavior.

**Comment by retronym** [comment]
You are right, that's outside of the spec (the special case, and the existence of conforms itself.)

I was actually thinking about this one today and trying to reverse engineer the reason. Couldn't get there with a thought experiment alone.

Here's one thing (heavily in the "implementation issues" end of the spectrum) that breaks with that special case removed.

``` scala
object Ding {
  protected class Foo3(name: String) { }
} 
object P {
  implicit def id[A](a: A): A = a

  // error: stable identifier required, but id[Ding.type].apply(Ding)
  new Ding.Foo3("abc")
}
```

**Comment by adriaanm** [comment]
yeah, conforms is a wart that should not exist in Predef -- I think it was in the <:< companion at some point, and we should probably re-introduce it there, deprecating Predef.conforms, but immediately removing its implicit status. Interestingly, I was sitting next to Martin last week when he ran into this discrepancy between dotty (which doesn't special-case conforms) and the current compiler.

**Comment by retronym** [comment]
Fascinating as these musings are, I also need a review here. @adriaanm ?

I was just about to lodge this bug:

``` scala
scala> trait T { def foo = "t" }; class C(private val foo: String) extends T
defined trait T
defined class C

scala> new C("C").foo
<console>:14: error: value foo in class C cannot be accessed in C
              new C("C").foo
                         ^

scala> (new C("C"): T).foo
java.lang.ClassFormatError: Duplicate method name&signature in class file C
  at java.lang.ClassLoader.defineClass1(Native Method)
```

Until I realised that it wouldn't be allowed after we fix this regression:

``` scala
scala> trait T { def foo = "t" }; class C(private val foo: String) extends T
<console>:7: error: overriding method foo in trait T of type => String;
 value foo has weaker access privileges; it should not be private
       trait T { def foo = "t" }; class C(private val foo: String) extends T
                                                      ^
```

**Comment by retronym** [comment]
See also #3440, which addresses another invasion of privacy.

**Comment by adriaanm** [comment]
LGTM

Sorry I got a little side-tracked by the discussion. The actual change is fine.

**Pull request merged**
