### PR TITLE
[nomaster] Carve up Types.scala

### PR DESCRIPTION
**Pull request by retronym**
Step one of a plan to bring some order and thread
safety to this neck of the woods.

More info:

  https://gist.github.com/retronym/5081754
  https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/MOvmcnbyb_g

Hand crafted backport of the #2201.

### CODE REVIEW

**Comment by retronym** [comment]
Darn, I branched this from a stale 2.10.x branch. Closing until I fix that up.

**Comment by retronym** [comment]
Let me know how you want me to deal with MiMa here. Just copy the suggested whitelist across? Can we do anything with a wildcard exclusion?

**Comment by adriaanm** [comment]
Yes, we can ignore changes in `scala.reflect.internal`. I see a couple of `scala.reflect.runtime` differences as well, though.

**Comment by retronym** [comment]
Getting closer:

```
     [java] Found 1 binary incompatibiities (165 were filtered out)
     [java] =======================================================
     [java]  * the type hierarchy of class scala.reflect.internal.Types#CommonOwnerMap
     [java]    has changed in new version. Missing types
     [java]    {scala.reflect.internal.Types$TypeTraverserWithResult,scala.reflect.internal.Types$TypeTraverser,scala.reflect.internal.Types$TypeMap}
     [java] Generated filter config definition
```

I'll be back in 24h to put this to bed.

**Comment by adriaanm** [comment]
Awesome. In the mean time, enjoy your own bed :-)

**Comment by retronym** [comment]
False dawn. The subsequent forward binary compatibility breakages are not resolvable.

e.g.

```
     [echo] Checking forward binary compatibility for scala-reflect
     [java] Found 146 binary incompatibiities (61 were filtered out)
     [java] ========================================================
     [java]  * the type hierarchy of class scala.reflect.runtime.JavaUniverse has
     [java]    changed in new version. Missing types
     [java]    {scala.reflect.internal.tpe.CommonOwners,scala.reflect.internal.tpe.TypeToStrings,scala.reflect.internal.tpe.TypeComparers,scala.reflect.internal.tpe.GlbLubs,scala.reflect.internal.tpe.TypeConstraints,scala.reflect.internal.tpe.TypeMaps}
     [java]  * the type hierarchy of trait scala.reflect.runtime.SymbolTable has changed
     [java]    in new version. Missing types
     [java]    {scala.reflect.internal.tpe.CommonOwners,scala.reflect.internal.tpe.TypeToStrings,scala.reflect.internal.tpe.TypeComparers,scala.reflect.internal.tpe.GlbLubs,scala.reflect.internal.tpe.TypeConstraints,scala.reflect.internal.tpe.TypeMaps}
     [java]  * the type hierarchy of trait scala.reflect.runtime.SynchronizedTypes has
     [java]    changed in new version. Missing types
     [java]    {scala.reflect.internal.tpe.CommonOwners,scala.reflect.internal.tpe.TypeToStrings,scala.reflect.internal.tpe.TypeComparers,scala.reflect.internal.tpe.GlbLubs,scala.reflect.internal.tpe.TypeConstraints,scala.reflect.internal.tpe.TypeMaps}
     [java]  * the type hierarchy of trait scala.reflect.runtime.SynchronizedOps has
     [java]    changed in new version. Missing types
     [java]    {scala.reflect.internal.tpe.CommonOwners,scala.reflect.internal.tpe.TypeToStrings,scala.reflect.internal.tpe.TypeComparers,scala.reflect.internal.tpe.GlbLubs,scala.reflect.internal.tpe.TypeConstraints,scala.reflect.internal.tpe.TypeMaps}
     [java]  * the type hierarchy of class
     [java]    scala.reflect.runtime.SynchronizedTypes#SynchronizedUndoLog has changed in
     [java]    new version. Missing types
     [java]    {scala.reflect.internal.tpe.TypeConstraints$AbsUndoLog}
```

I don't see any way around these given the policy that on `scala.reflect.runtime`.

**Comment by JamesIry** [comment]
@retronym should we close this one and retarget 2.11?

**Comment by retronym** [comment]
It's already in 2.11, this was a backport attempt. But our hands are bound too tightly to pull it off, so I'll close.

**Pull request closed without merging**
