### PR TITLE
Improve Scaladoc for Either:

### PR DESCRIPTION
**Pull request by soc**
- remove text on projections
- add for comprehensions

### CODE REVIEW

**Comment by soc** [comment]
Brought up by @xuwei-k in https://github.com/scala/scala/pull/5135

**Comment by soc** [comment]
Review by @xuwei-k? Thanks!

**Comment by swaldman** [comment]
It would probably be helpful to document which features of for comprehensions are and are not supported.

**Comment by szeiger** [comment]
LGTM

**Pull request merged**
