### PR TITLE
WIP: rebase of #3117

### PR DESCRIPTION
**Pull request by adriaanm**
WIP: rebase of #3117

### CODE REVIEW

**Comment by adriaanm** [comment]
@JamesIry, it looks like at least d7d63e9's a win. The other commits indeed fail similarly to what you saw when trying to remove duplication.

**Comment by retronym** [comment]
Disecting the first failure:

https://scala-webapps.epfl.ch/jenkins/job/pr-scala-rangepos/4559/console

Appear to have created a memory leak in the toolbox compiler. Or, we might have exacerbated an existing leak to the point where we it triggers the threshold of the test. I fixed a major leak in `perRunCaches` on my performance branch, which _might_ be the culprit.

```
% diff /localhome/jenkins/c/workspace/pr-scala-rangepos/scala/test/files/run/reflection-mem-typecheck-run.log /localhome/jenkins/c/workspace/pr-scala-rangepos/scala/test/files/run/reflection-mem-typecheck.check--- empty
+++ reflection-mem-typecheck-run.log
@@ -1,0 +1,12 @@
+FAILED
+57.100128 Mb
+59.02272 Mb
+61.242728 Mb
+62.779808 Mb
+64.616376 Mb
+66.494376 Mb
+68.165672 Mb
+70.616904 Mb
+73.170872 Mb
+74.72272 Mb
+74.722768 Mb
```

And, a failure in the [IDE test suite](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4088/consoleText):

```
Tests run: 525, Failures: 0, Errors: 7, Skipped: 35, Time elapsed: 94.345 sec <<< FAILURE!

Results :

Tests in error: 
  intDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)
  listDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)
  primitiveArrayDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)
  refArrayDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)
  innerClassDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)
  typeVarClassDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)
  errorClassDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)
```

I don't see any details of that failure in the console output above, nor in archived artifacts. @dragos could you please help us to diagnose that failure?

**Comment by retronym** [comment]
I've updated the configuration of that Jenkins job to archive the test logs (`**/surefire-reports/*`) as build artifacts.

The particular failure is indeed a `LinkageError`.

```
errorClassDescriptor(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest)  Time elapsed: 0.021 sec  <<< ERROR!
java.lang.AbstractMethodError: scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest$$anonfun$withTargetTree$1$$anonfun$1.isDefinedAt(Ljava/lang/Object;)Z
    at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1625)
    at scala.reflect.internal.Trees$TreeContextApiImpl.collect(Trees.scala:118)
```

```
javap -classpath ./org.scala-ide.sdt.core.tests/target/classes/ 'scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest$$anonfun$withTargetTree$1$$anonfun$1'
Compiled from "ScalaJavaMapperTest.scala"
public final class scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest$$anonfun$withTargetTree$1$$anonfun$1 extends scala.runtime.AbstractPartialFunction implements scala.Serializable{
    public static final long serialVersionUID;
    public final java.lang.Object applyOrElse(scala.reflect.internal.Trees$Tree, scala.Function1);
    public final boolean isDefinedAt(scala.reflect.internal.Trees$Tree);
    public final java.lang.Object applyOrElse(java.lang.Object, scala.Function1);
    public scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest$$anonfun$withTargetTree$1$$anonfun$1(scala.tools.eclipse.structurebuilder.ScalaJavaMapperTest$$anonfun$withTargetTree$1);
}
```

We're missing a bridge this pattern matching anonymous partial function:

``` scala
      val targets = compiler.loadedType(srcFile).left.toOption.get collect {
        case t: compiler.DefDef if t.name.toString startsWith "target" => t
      }
```

**Comment by dragos** [comment]
@retronym It looks like to successfully tracked down the IDE failure?

**Comment by retronym** [comment]
@dragos: Yep, I've got it now. Next time, with the new artifact pattern, we won't need to run locally to see the full test failures.

The failure is legit:

``` scala
class C
class A { class C }

object Test {
  val f = (a: A) => {
    { case _ => "" }: PartialFunction[a.C, String]
  }

  def main(args: Array[String]) {
    val a = new A
    f(a).isDefinedAt(null)  
  }
}
// java.lang.AbstractMethodError: Test$$anonfun$1$$anonfun$apply$1.isDefinedAt(Ljava/lang/Object;)Z
//  at Test$.main(test.scala:11)
//  at Test.main(test.scala)
```

**Comment by retronym** [comment]
And simplified a little

``` scala
trait M[X] {
  def m(x: X): Boolean
}

class C
class A { class C }

object Test {
  val f = (a: A) => {
    new M[a.C] { def m(x: a.C) = true}
  }

  def main(args: Array[String]) {
    val a = new A
    f(a).m(null)  
  }
}

```

**Comment by JamesIry** [comment]
My previous de-dupe iteration also caused linkage errors in the IDE tests but I seem to recall they were caused by lambda argument order getting changed rather than a missing bridge.

**Comment by retronym** [comment]
Next roll of the dice: #3165

**Pull request closed without merging**
