### PR TITLE
Revert "SI-8253 Fix incorrect parsing of <elem xmlns={f("a")}/>"

### PR DESCRIPTION
**Pull request by retronym**
This reverts commit 8d175b907d41323333a5613e419303f10beddc76.

This commit broke compilation of the test suite of scala-xml:

```
[error] /localhome/jenkins/c/workspace/scala-release-2.11.x/scala-xml/src/test/scala/scala/xml/XMLTest.scala:604: type mismatch;
[error]  found   : scala.xml.Text
[error]  required: String
[error]     <wsdl:definitions name={ serviceName } xmlns:tns={ Text("target3") }>
[error]                                                            ^
[error] one error found
[error] (test:compile) Compilation failed
```

Review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
Reopens SI-8253. I think I need to resort to a deprecated special case in the typer to fix this bug but retain backwards compatibility. The bug isn't critical, so that can wait.

**Comment by som-snytt** [comment]
Say it ain't so, Joe!

**Comment by retronym** [comment]
Here's a fix for the test in scala-xml: https://github.com/scala/scala-xml/pull/36

If we merge that, we don't need to merge this. I'll leave the decision up to @adriaanm, to whom I owe a stable release build.

**Comment by adriaanm** [comment]
Let's fix the test instead -- the only external fallout of the original fix would be someone's xml that relies on capturing `Text` or is doing similarly shady matching of the produced AST.

**Comment by adriaanm** [comment]
It ain't so. scala-xml 1.0.3's tests will be less breaky

**Pull request closed without merging**
