### PR TITLE
SI-6276 Warn on def or val that trivially loops infinitely

### PR DESCRIPTION
**Pull request by retronym**
Review by Mr Lint, aka @paulp.

### CODE REVIEW

**Comment by jsuereth** [comment]
+1 from me.   Please keep em coming!

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL, Sam.

**Comment by gkossakowski** [comment]
LGTM from me. Shall we wait for @paulp ?

**Comment by retronym** [comment]
Merge at will.

**Comment by paulp** [comment]
```
[scalacfork] Compiling 13 files to /scala/trunk/build/quick/classes/reflect
[scalacfork] /scala/trunk/src/reflect/scala/reflect/internal/Symbols.scala:952: warning: method enclClassChain in class Symbol does nothing other than call itself recursively
[scalacfork]     def enclClassChain: List[Symbol] = owner.enclClassChain
[scalacfork]                                              ^
[scalacfork] /scala/trunk/src/reflect/scala/reflect/internal/Symbols.scala:2094: warning: method associatedFile in class Symbol does nothing other than call itself recursively
[scalacfork]     def associatedFile: AbstractFile = enclosingTopLevelClass.associatedFile
[scalacfork]                                                               ^
```

**Comment by gkossakowski** [comment]
Ooops. @retronym can you have a look?

**Comment by retronym** [comment]
Will do; please revert until then.

**Pull request merged**
