### PR TITLE
SI-6547: elide box unbox pair only when primitives match

### PR DESCRIPTION
**Pull request by magarciaEPFL**
review by @VladUreche

### CODE REVIEW

**Comment by VladUreche** [comment]
LGTM, thanks Miguel! 

I think you can also close [SI-6547](https://issues.scala-lang.org/browse/SI-6248), which is essentially the same issue. I had a more complicated patch for it, in case you want to have a look: 03b3b959

**Comment by VladUreche** [comment]
Actually, Miguel, maybe you should have a look at the old patch, it seems it covers one more case -- UNBOX(BOX(loc)) -- which can only be reduced if we get the same type out.

**Comment by magarciaEPFL** [comment]
@VladUreche, I took a look at the test case in [SI-6248](https://issues.scala-lang.org/browse/SI-6248) . With the fix in this PR that test case produces the same results whether optimized or not , so it looks like this PR in its present form already handles that case. But I haven't inspected the resulting bytecode. In case you find something unexpected for [SI-6248](https://issues.scala-lang.org/browse/SI-6248) please let me know.

**Comment by VladUreche** [comment]
@magarciaEPFL The test case for SI-6248 is only triggered by aggressive inlining. If you set isScoreOK to true in the inliner and check the testcase you should see the compiler crashing. But now that I think of it, with GenBCode just around the corner, I think we can let this slip away, there's no need to overengineer an EOL backend.

**Comment by gkossakowski** [comment]
This pull request does not fix critical ticket therefore it's not being considered for 2.10.0-wip branch. Please reopen it against appropriate branch.

**Comment by adriaanm** [comment]
i.e., 2.10.x

**Pull request closed without merging**
