### PR TITLE
SI-6318 fixes ClassTag.unapply for primitives

### PR DESCRIPTION
**Pull request by xeno-by**
ClassTag.unapply now takes a class tag itself, so that it can preserve
boxiness of value classes when performing subtyping tests.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @jsuereth

**Comment by jsuereth** [comment]
LGTM

**Comment by jsuereth** [comment]
Aborted build?

**Comment by xeno-by** [comment]
That wasn't me. PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@jsuereth could you please take another look? I stumbled upon an issue with patmat and had to completely redo the implementation

**Comment by jsuereth** [comment]
Does the issue pop up with any value class or just primitives?

 Could you add an anyval test?  Something simple like class X(val y: Int) extends AnyVal

I'm paranoid about them now.

Other than that LGTM, although it seems odd.   Can you describe what virtpatmat was freaking out on?

Im

**Comment by xeno-by** [comment]
Only with primitives, yet I have a test that checks derived value classes: `test/files/run/t6318_derived.check`.

The patmat was saying: `warning: The outer reference in this type test cannot be checked at run time`. 

Here's the dump of -Xprint:specialize (the phase before explicitouter) for when I added the type parameter to the signature of unapply: `unapply[T](x: T)` instead of `unapply(x: Any)`. The lines marked with the `>>>` sign (added by me right now, not present in the original printout) are the ones that appeared after that change. I believe that T was inferred to be Extractors.this.T and this scared the patmat into inserting additional checks.

```
trait Extractors {
  type T
  implicit val tTag: ClassTag[T]
  object ExtractT {
    def unapply(x: T) = Some(x)
  }
  def apply(a: Any) = a match {
    case ExtractT(x)  => 
  }
}

myke compile C:\Projects\Kepler\sandbox\Test.scala -Xprint:specialize
git: branch = ticket/6318, commit = c2a95d1352 SI-6318 fixes ClassTag.unapply for primitives (Eugene Burmako, 06.09.2012 12:41:42 +02:00)
psi: filename = cmd.exe, arguments = /C c:\PROGRA~1\Java\JDK\bin\java.exe -cp "C:\Projects\Kepler\test\files\codelib\code.jar;C:\Projects\Kepler\lib\jline.jar;C:\Projects\Kepler\lib\fjbg.jar;C:\Projects\Kepler\build\locker\classes\compiler;C:\Projects\Kepler\build\asm\classes;C:\Projects\Kepler\build\libs\forkjoin.jar;C:\Projects\Kepler\build\locker\classes\reflect;C:\Projects\Kepler\build\locker\classes\library" -Dscala.usejavacp=true -Dscala.repl.vids=1 -Dscala.repl.autoruncode=C:\Users\xeno.by/.scala_autorun -Dscala.repl.maxprintstring=0 scala.tools.nsc.Main -language:experimental.macros -Xprint:specialize Test.scala, home = C:\Projects\Kepler\sandbox
[[syntax trees at end of                specialize]] // Test.scala
package <empty> {
  abstract trait Extractors extends Object {
    def /*Extractors*/$init$(): Unit = {
      ()
    };
    type T;
    implicit <stable> <accessor> def tTag(): scala.reflect.ClassTag[Extractors.this.T];
    object ExtractT extends Object {
      def <init>(): Extractors.this.ExtractT.type = {
        ExtractT.super.<init>();
        ()
      };
      def unapply(x: Extractors.this.T): Some[Extractors.this.T] = new Some[Extractors.this.T](x)
    };
    @volatile <synthetic> private[this] var ExtractT$module: Extractors.this.ExtractT.type = _;
    <stable> def ExtractT(): Extractors.this.ExtractT.type = new Extractors.this.ExtractT.type();
    def apply(a: Any): Unit = {
      case <synthetic> val x1: Any = a;
      case8(){
        >>> if (x1.isInstanceOf[Extractors.this.T]().&&((x1.asInstanceOf[Extractors.this.T](): Extractors.this.T).<outer>().eq(Extractors.this)))
          {
            >>> val x3: Extractors.this.T = (x1.asInstanceOf[Extractors.this.T](): Extractors.this.T);
            {
              val o11: Option[Extractors.this.T] = Extractors.this.tTag().unapply[Extractors.this.T](x3, Extractors.this.tTag());
              if (o11.isEmpty().unary_!())
                {
                  val p2: Extractors.this.T = o11.get();
                  {
                    val o10: Option[Extractors.this.T] = Extractors.this.ExtractT().unapply(p2);
                    if (o10.isEmpty().unary_!())
                      {
                        val x: Extractors.this.T = o10.get();
                        matchEnd7(())
                      }
                    else
                      case9()
                  }
                }
              else
                case9()
            }
          }
        else
          case9()
      };
      case9(){
        matchEnd7(throw new MatchError(x1))
      };
      matchEnd7(x: Unit){
        x
      }
    }
  }
}

warning: there were 1 unchecked warnings; re-run with -unchecked for details
one warning found
```

**Comment by jsuereth** [comment]
Lgtm to me too.  Sorry for the email shared accounts.

**Comment by xeno-by** [comment]
My pull request has been approved by the kitteh!

**Comment by xeno-by** [comment]
Omg that's embarassing. PLS REBUILD ALL

**Pull request merged**
