### PR TITLE
Make methods in StringContext private

### PR DESCRIPTION
**Pull request by lrytz**
Scala ships with some funny interpolators

    scala> standardInterpolator"oh ${_*2} hai ${Seq(1,2)}"
    res0: String = oh oh 1 hai  hai 2

    scala> checkLengths"swush ${Seq(0)} gone"

    scala>

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]

**Comment by som-snytt** [comment]
I'm embarrassed that this wasn't a puzzler. @demobox

**Comment by demobox** [comment]
> I'm embarrassed that this wasn't a puzzler.

Ha, nice! I wonder what the expected behaviour in general would have been - perhaps "does not compile"? Is this considered a bug?

**Comment by SethTisue** [comment]
> Is this considered a bug?

hmmm... is what considered a bug? not sure what you're asking

**Comment by SethTisue** [comment]
revised somewhat in https://github.com/scala/scala/pull/6868

**Comment by som-snytt** [comment]
@demobox It's only a bug if it bugs you. Similarly, it's only a puzzler if it puzzles you.

**Pull request merged**
