### PR TITLE
Remove -Yrepl-sync

### PR DESCRIPTION
**Pull request by som-snytt**
Follows up recent effort to remove divisive -Y flags.

### CODE REVIEW

**Review by adriaanm — APPROVED** [review]
So long! I feel a bit lighter already.

**Comment by SethTisue** [comment]
I've only ever used it to see if some REPL bug went away when it was enabled.

**Comment by som-snytt** [comment]
I considered instead adding `-Ywarn-unused-useless-options`.

**Comment by hrhino** [comment]
The alternative is a pull request to add it to `sbt-tpolecat`, since no one reads all of those anyways.

**Comment by retronym** [comment]
This breaks SBT, we should probably leave a deprecated setting shim.

```
[info] Non-compiled module 'compiler-bridge_2.13.0-M2' for Scala 2.13.0-20180529-050640-b395c5c. Compiling...
/var/folders/b7/xcc2k0ln6ldcv247ffpy2d1w0000gp/T/sbt_5ceddff0/xsbt/ConsoleInterface.scala:99: error: value Yreplsync is not a member of scala.tools.nsc.Settings
    settings.Yreplsync.value = true
             ^
/var/folders/b7/xcc2k0ln6ldcv247ffpy2d1w0000gp/T/sbt_5ceddff0/xsbt/InteractiveConsoleInterface.scala:89: error: value Yreplsync is not a member of scala.tools.nsc.Settings
    settings.Yreplsync.value = true
             ^
```

**Comment by som-snytt** [comment]
@retronym I changed the title to "unused by us and useless."

**Comment by som-snytt** [comment]
Maybe `sbt` shouldn't have a `console` command anymore.

```
  def sync(options: List[String], log: Logger): Settings = {
    val settings = apply(options, log)
    settings.Yreplsync.value = true
    settings
  }
```

**Comment by som-snytt** [comment]
I just said, "sync or shim." So maybe it was worth it.

**Pull request merged**
