### PR TITLE
SI-7349 SI-7358 SI-7409 Par-Test inches forward

### PR DESCRIPTION
**Pull request by som-snytt**
A failing scalacheck test generates a test failure instead of allowing the build to succeed.
The failure log is added to the transcript.

Updates Scalacheck to 1.10.1 and invokes it using the
test-interface API.  This obviates kludgy output checking for result
status.

Also, Partest testnum field width is sensitive to total tests.

Allow the hyphens to line up on a column within the output
for a test category or "kind".

Users are notified when check files are updated, and also when the compiler crashes instead of updating their check files.

Review by @soc and @adriaanm for build changes to use test-interface.jar.
Further review by @retronym who crept the feature.

Illustrations of behavior follow.  Here it is in black and white.  (In color at a screen near you.)

```
$ partest files/neg/t4134.scala --run
Selected 1348 tests drawn from 1 named test categories, specified tests

# starting 1 test in neg
ok 1 - neg/t4134.scala

# starting 1347 tests in run
ok    1 - run/absoverride.scala
ok    2 - run/amp.scala
ok    3 - run/adding-growing-set.scala
```

Partest --timeout "30 seconds" to time out the test run.  "I hang with Par-Test" no more!

```
ok   62 - pos/five-dot-f.scala                    
ok   63 - pos/functions.scala                     
Thread pool timeout elapsed before all tests were complete!
63/1067 passed, 1004 skipped (elapsed time: 00:00:30)
Test Run PASSED
```

```
$ partest files/neg/failtest.scala
Selected 1 tests drawn from specified tests

# starting 1 test in neg
!! 1 - neg/failtest.scala                        [output differs]
#0/1 passed, 1 failed in neg

##### Transcripts from failed tests #####

# partest files\neg\failtest.scala
% scalac files\neg\failtest.scala
failtest.scala:3: error: value really is not a member of object Foo
    this.really("doesn't compile")
         ^
one error found

% diff files\neg\failtest-neg.log files\neg\failtest.check--- a
+++ b
@@ -1,4 +1,0 @@
-failtest.scala:3: error: value really is not a member of object Foo
-    this.really("doesn't compile")
-         ^
-one error found

0/1 passed, 1 failed (elapsed time: 00:00:01)
Test Run FAILED

apm@halyard /cygdrive/m/apm/projects/scala-second/test
$ partest --update-check files/neg/failtest.scala
Selected 1 tests drawn from specified tests

# starting 1 test in neg
++ 1 - neg/failtest.scala                        [updated check file]

1/1 passed (elapsed time: 00:00:01)
Test Run PASSED

apm@halyard /cygdrive/m/apm/projects/scala-second/test
$ partest --update-check files/neg/failtest.scala
Selected 1 tests drawn from specified tests

# starting 1 test in neg
ok 1 - neg/failtest.scala                      

1/1 passed (elapsed time: 00:00:01)
Test Run PASSED

```

```
$ partest --update-check files/neg/t7223.scala
Selected 1 tests drawn from specified tests

# starting 1 test in neg
unhandled exception while transforming t7223.scala
!! 1 - neg/t7223.scala                           [compilation failed]
#0/1 passed, 1 failed in neg

##### Transcripts from failed tests #####

# partest files\neg\t7223.scala
% scalac files\neg\t7223.scala
error: no-symbol does not have an owner
[** transcript abbreviated **]
0/1 passed, 1 failed (elapsed time: 00:00:02)
Test Run FAILED
```

### CODE REVIEW

**Comment by som-snytt** [comment]
I wimped out and called the timeout option --timeout.  (Per-test timeout could be --fail-after or similar.)

The merge failure was because another PR got merged in the middle of this PR validation.

**Comment by Blaisorblade** [comment]
There seems to be in fact no merge failure - right now, the red dot seems just the kitteh being stuck.

**Comment by som-snytt** [comment]
This is the rebased push -f.

Kitteh likes to play with its prey and just swat it around for a while.

**Comment by adriaanm** [comment]
PLS SYNCH

**Comment by adriaanm** [comment]
build changes LGTM

**Comment by som-snytt** [comment]
@soc had previously liked the field width (since it was his idea) -- but I can't anticipate when a push will make comments disappear on github.  @soc or @adriaanm might also like to like --timeout as mentioned on the ML.

The first commit fixes that a failing scalacheck wouldn't fail the build; but the test-interface commit supersedes it somewhat.

**Comment by Blaisorblade** [comment]
> @soc had previously liked the field width (since it was his idea) -- but I can't anticipate when a push will make comments disappear on github.

AFAIK, comments stick with commits, not with pull requests, and don't migrate when for instance rebase changes the hash of the commit.

**Comment by soc** [comment]
LGTM ... one question: Is there a way to specify this when running the tests with Ant? E. g. `ant test.suite.color --timeout "30 seconds"?

**Comment by som-snytt** [comment]
I haven't tried it, but I would think, ant -Dpartest.timeout="30 seconds".  Your quoted mileage may vary depending on platform.  I needed extra quotes for cygwin partest.

**Comment by soc** [comment]
Ah thanks, I'll try that!

Is there a chance to merge this now, so I can start running the complete test-suite on Avian? :-)

**Comment by soc** [comment]
Suggestion: I think it would be better to have the test status at the right, so that the line with the test number and the test file can be printed _before_ the test is executed. When the test is finished, the result is added at the right side.

E. g.

```
& starting 1347 tests in run
   1 - run/absoverride.scala                             ok
   2 - run/amp.scala                                     ok 
   3 - run/adding-growing-set.scala                      
```

In the above example, test 3 would be running.

In cases where a test hangs, it is extremely annoying to not immediately see on which test partest is stuck.
It would also make test failures more intuitive, because the e. g. stacktrace would come _after_ and not _before_ the test number/file name/test status line.

**Comment by som-snytt** [comment]
> test status at the right

My fastest branch takes different test listeners where that is possible, including a green progress bar in Swing.  If you create the issue, I'll volunteer for it.

(Fastest reports in submit order and can time out a test.)

Only people working on weird backends see errors and hangs.  Feel free to order an "I hang with Par-Test!" t-shirt from the Scala store (if there are any left in stock).

**Comment by soc** [comment]
@som-snytt Here you go: https://issues.scala-lang.org/browse/SI-7416

You'll have to set the Asignee yourself, I didn't find find your name in JIRA.

Thanks!

**Comment by paulp** [comment]
I don't have the heart to look too closely at a partest commit of this size, but the one thing which is absolutely mandatory is that updating the scalacheck sources happens in its own commit, which does nothing but update the scalacheck sources.

**Comment by som-snytt** [comment]
That's why @paulp is not a reviewer. (Because you don't have the heart; or, I would have said the time. Or maybe the stomach.)

Maybe eventually this PR will include a feature that someone wants enough to review, but like the title says, it's nothing astounding.

For the record, my interest was in looking at how @paulp did CompileRound and nextTestAction.

Split commit pending.

**Comment by som-snytt** [comment]
Do you know what happens if you're in the middle of rebase -i, in a cycle of add, commit, stash, build, pop, and you stick a few lines of code into a tmp file called "head" lower case?

I didn't actually notice until a commit or two later that I was no longer on my working branch.

This PR is superseded by a less ambitious split.

$ git stash save
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate filenames from revisions
Saved working directory and index state WIP on (no branch): 3b0be57 more
HEAD is now at 3b0be57 more

apm@halyard /cygdrive/m/apm/projects/scala-second
$ mv head imps

apm@halyard /cygdrive/m/apm/projects/scala-second
$ git stash list
stash@{0}: WIP on (no branch): 3b0be57 more

apm@halyard /cygdrive/m/apm/projects/scala-second
$ git status
& Not currently on any branch.

**Pull request closed without merging**
