### PR TITLE
WIP uncurry tiding

### PR DESCRIPTION
**Pull request by retronym**
/cc @JamesIry

### CODE REVIEW

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@f595a6c
PLS REBUILD/pr-scala@e14190d

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@f595a6c

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@e14190d

**Comment by adriaanm** [comment]
(Should work now: https://github.com/scala/jenkins-scripts/commit/475f637c417500d4df032b6cfc1ce879a4f7a6ef)

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Sorry, rebasing this on master should fix the OSGi breakage. I had to upgrade to a new pax-aether (https://github.com/adriaanm/scala/commit/a24e7fa688cad6bd12d8541a76b5e0b04291a070#diff-2cccd7bf48b7a9cc113ff564acd802a8R268)

**Comment by adriaanm** [comment]
rebased at #3150

**Pull request closed without merging**
