### PR TITLE
Sanity for build.xml: exscriptus&positus delendus est.

### PR DESCRIPTION
**Pull request by adriaanm**
Reduced copy/pasting to the best of my antabilities. The next person to duplicate anything without written permission will be sentenced to a week in xmhell.

While I was at it, made sure that layering is respected. The quick phase exclusively uses the locker compiler for building.

The jar task will fail when trying to create an empty jar.

Replaced the crazy if/unless/depends constructs by if/then/else. Version suffix computation should now be comprehensible. I threw in some validation to make sure the various suffixes are consistent.

Also, no more init/pre-foo tasks unless absolutely necessary.

Introduce a couple of macros to capture the essence of staged compilation. For example, this is the entirety of the locker phase:

```
<target name="locker.lib" depends="locker.start" unless="locker.locked">
  <staged-build with="starr" stage="locker" project="library" srcpath="${src.dir}/library" includes="lib.includes">
    <pre><staged-javac stage="locker" project="library" args="-XDignore.symbol.file"/></pre>
  </staged-build></target>

<target name="locker.reflect" depends="locker.lib"     unless="locker.locked">
  <staged-build with="starr" stage="locker" project="reflect"/></target>

<target name="locker.comp"    depends="locker.reflect" unless="locker.locked">
  <staged-build with="starr" stage="locker" project="compiler"/></target>
```

Notes:
- remove lib.extra, standardize on aux.libs
- collapse *.javac.path and *.build.path
- rename starr.classpath to starr.compiler.path
- only repl needs jline, locker.compiler.path = locker.comp.build.path + forkjoin
- more uniform build.paths (compiler = reflect + library)
  - uniformity means slightly bigger classpaths
    (e.g. forkjoin is only used in library,  but inherited by compiler)
  - pruned: some spurious dependencies removed
  - compilerpathref = compiler build path
- silence test.osgi, by hook or by crook
- centralized clean tasks
- reduce duplication in property usage
- fix pack.xml to pack scaladoc/partest instead of scaladoc/scala-partest
- TODO: -XDignore.symbol.file necessary for library? only needed for forkjoin?
- document usage from jenkins, fix typo: partest.scalac___opts

New targets:
- quick-opt
- strap-opt
- test.bc
- test.osgi
- test.osgi.comp
- test.osgi.init
- test.stability-opt

Removed/replaced targets:
- asm.clean asm.lib asm.start
- bc.run
- dist.latest dist.latest.unix dist.latest.win dist.start
- docs.all docs.manmaker docs.pre-comp docs.pre-continuations-plugin
- docs.pre-jline docs.pre-lib docs.pre-man docs.pre-partest docs.pre-scalap
- forkjoin.clean forkjoin.lib forkjoin.pack forkjoin.start
- graph.clean
- init.build.nopatch.release init.build.patch.release init.build.release
- init.build.snapshot init.build.suffix.done init.extra.tasks
- init.fail.bad.jdk init.hasbuildnum init.hasmavensuffix init.jars
- init.jars.check init.maven.jars init.maven.tasks init.osgi.suffix
- init.osgi.suffix.final init.osgi.suffix.snapshot init.testjava6
- init.version.done init.version.git init.version.release init.version.snapshot
- init.warn.jdk7 locker.pre-comp locker.pre-lib locker.pre-reflect
- locker.unlock.comp locker.unlock.lib locker.unlock.pre-comp
- locker.unlock.pre-lib locker.unlock.pre-reflect locker.unlock.reflect
- osgi.clean osgi.test osgi.test.comp osgi.test.init
- pack.clean pack.pre-bin pack.pre-comp pack.pre-lib pack.pre-partest
- pack.pre-plugins pack.pre-reflect pack.pre-scalap pack.start
- palo.comp palo.lib palo.pre-bin palo.pre-comp palo.pre-lib palo.pre-reflect
- palo.reflect palo.start quick.pre-bin
- quick.pre-comp quick.pre-interactive quick.pre-lib quick.pre-partest
- quick.pre-plugins quick.pre-reflect quick.pre-repl quick.pre-scalacheck
- quick.pre-scaladoc quick.pre-scalap
- sbt.clean sbt.compile sbt.done sbt.libs sbt.start
- starr.clean
- strap.clean strap.pre-comp strap.pre-lib strap.pre-reflect strap.start
- test.debug test.pre-run

### CODE REVIEW

**Comment by adriaanm** [comment]
Review by everyone. @paulp, @jsuereth, @retronym, @xeno-by, @gkossakowski, @JamesIry 

Working on a backport to 2.10.x,

**Comment by adriaanm** [comment]
Also, I'm quite pleased to point to this little nugget:

> Use `ant -Dstarr.version="2.11.0-M2" -Dlocker.skip=YESSIR`, to build quick using 2.11.0-M2 (skipping locker, using starr instead).

**Comment by adriaanm** [comment]
Also, even with more docs and features, build.xml shed 913 lines of bloat.

**Comment by adriaanm** [comment]
In smaller pieces: https://github.com/adriaanm/scala/compare/master...build-cleanup

**Comment by retronym** [comment]
```
java.lang.ClassCastException: org.codehaus.plexus.DefaultPlexusContainer cannot be cast to org.codehaus.plexus.PlexusContainer
```

Probable solution from [MANTTASKS-203](http://jira.codehaus.org/browse/MANTTASKS-203):

> I had the same issue. The problem occurs, when mvn-init target will be called twice. You can solve it using the "unless" attribute. For example:

**Comment by retronym** [comment]
``` xml
<macrodef name="staged-docs">
    <attribute name="project"/>
    <attribute name="dir" default="@{project}"/>
    <attribute name="title"/>
    <attribute name="docroot" default="NOT SET"/>
    <element name="includes" implicit="true"/>

    <sequential>
      <staged-uptodate stage="docs" project="@{project}">
        <check><srcfiles dir="${src.dir}/@{dir}"/></check>
        <do>
          <stopwatch name="docs.@{project}.timer"/>
          <mkdir dir="${build-docs.dir}/@{project}"/>
          <if><equals arg1="@{classpathref}" arg2="NOT SET"/><then>
            <scaladoc
```

The predicate should be based on `docroot`, `classpathref`.

**Comment by retronym** [comment]
``` xml
  <target name="distpack-opt" description="Builds an optimised distribution."> <optimize name="distpack"/></target>
  <target name="distpack-maven-opt" description="Builds an optimised maven distribution."><optimize name="distpack-maven"/></target>
...
  <macrodef name="optimized" >
    <attribute name="name"/>
    <sequential>
      <antcall target="@{name}"><param name="scalac.args.optimise" value="-optimise"/></antcall>
    </sequential>
  </macrodef>
```

s/optimize/optimized`

**Comment by retronym** [comment]
I found two more typos calls to the `optimized` macro (`replacestarrwin-opt` and `replacelocker-opt`).

The "NOT SET" checks are something of a wart. Did you try using a reference to an empty pathset as the default instead? If you're calling one of our Ant tasks, it could be modified to to treat that as an omitted argument.

But that shouldn't hold this up, so LGTM pending fixes to the other issues I noted.

**Comment by adriaanm** [comment]
Thanks! I'm out for the rest of the weekend. Will fix these on Sunday.

On Saturday, March 23, 2013, Jason Zaugg wrote:

> I found two more typos calls to the optimized macro (replacestarrwin-optand
> replacelocker-opt).
> 
> The "NOT SET" checks are something of a wart. Did you try using a
> reference to an empty pathset as the default instead? If you're calling one
> of our Ant tasks, it could be modified to to treat that as an omitted
> argument.
> 
> But that shouldn't hold this up, so LGTM pending fixes to the other issues
> I noted.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scala/scala/pull/2290#issuecomment-15339385
> .

## 

See you at Scala Days http://scaladays.org (June 10–12, NYC)!

**Comment by adriaanm** [comment]
> If you're calling one of our Ant tasks, it could be modified to to treat that as an omitted argument.

I spent several hours trying to do just that, but had to punt for now as extricating our antlib proved tricky.
We should definitely get that out of here, but http://ant.apache.org/manual/Tasks/script.html + #2206 looks like a more exciting way of doing that.

**Comment by paulp** [comment]
Oh. I checked if it had already been fixed before I suggested fixing it, but I see I checked the build.xml work which had actually been merged, which was in 2.10.x, which of course didn't need this change.

**Pull request merged**
