### PR TITLE
SI-3235 Add round/ceil/floor to integral number types

### PR DESCRIPTION
**Pull request by soc**
This is a stopgap measure to prevent implicit conversions to
floating point numbers which cause issues like

  123456789.round == 123456792

### CODE REVIEW

**Comment by Ichoran** [comment]
The first commit is good.  The second is a major policy change that needs far broader discussion than has been had thus far.  The third depends conceptually on the outcome of the second.

**Comment by som-snytt** [comment]
The issue number and PR number nearly coincide.  Unless it was a rounding error.

There should be an umbrella issue for the paulp laundry list.  I was inclined to retitle SI-8000 "We're Doing it All Wrong."  Then you can close it with PR 8000.

**Comment by soc** [comment]
One question is whether I should, instead of just defining those methods in `RichX`, add the methods to `ScalaNumberProxy`.
A part of me hopes that we will get rid of implicit widening conversions in the future, so that this hack wouldn't be necessary anymore.

I'm wondering whether it makes sense to have these methods defined for "all" numbers, regardless of this issue (and probably also add them to `Numeric`).

Maybe @non can comment on that?

**Comment by non** [comment]
You could add those methods to `ScalaNumberProxy` but that would box the results. Since `RichInt` &co are value classes I think the strategy you used here is preferable.

Also, there are some number types where these methods don't make sense, so I'd prefer to leave them off of `ScalaNumber`.

**Comment by soc** [comment]
@non What about those methods when working with `Numeric`? I could imagine that they are kind of useful, even if they are no-ops for some number types.

**Comment by non** [comment]
I don't use `scala.math.Numeric` so I don't any have any particular feeling about it.

I guess folks need to decide how strict the type class is expected to be? It doesn't support division, so my sense is that it probably wouldn't support these methods either. But I don't feel strongly about it.

**Comment by soc** [comment]
@non I asked you because you have a lot of experience with Numeric in Spire. If you say "we found it useful to have those methods in Numeric in Spire", I'll also add them to the Scala ones, so that migration gets easier.

**Comment by non** [comment]
So in Spire we use `Numeric` as a best effort to supporting all "common" numeric operations, so we would definitely have those methods (and they could crash if necessary). That approach implies putting `/` and `%` on `Numeric` as well as many other operations.

**Comment by non** [comment]
I do find it handy to have a "best effort" numeric type class, so if Typesafe/EPFL want to use `scala.math.Numeric` to fill that role, then adding these methods is smart.

**Comment by soc** [comment]
Ok, then I'll add round/ceil/floor to Numeric. Just because people messed up with division, doesn't mean we have to repeat it. I'll amend the commit accordingly.

Anyway, I think everything which makes Scala's Numeric closer to Spire's Numeric is a net win.
I'm still hoping to replace Scala's code with parts of Spire.

Maybe I should start deprecating Integral and friends ...

**Comment by Ichoran** [comment]
I personally view Numeric as a lost cause and wouldn't waste time on it, but I don't think it would otherwise hurt to add floor/round/ceil.

**Comment by soc** [comment]
Am I the only one who thinks it is pretty annoying that all numbers have a no-arg `round` method, except `BigDecimal`, which calls it `rounded` instead? WTF?

**Comment by Ichoran** [comment]
That was me, following the naming convention of "updated".  And it's a different name because it _doesn't round to the nearest integer_.  Maybe I should also add a no-arg `round` method that rounds to the nearest integer.

**Comment by soc** [comment]
@Ichoran I think this would be absolutely nice. Was this only added recently? Could we overhaul that part of the BigDecimal API without breaking compatibility or was this shipped already?

**Comment by soc** [comment]
Proposal:
- Deprecate `round(MathContext)` and introduce `roundWith(MathContext)` as a replacement
- Add `round`, which rounds to whole numbers
- Keep `rounded` as is

What do you think?

**Comment by Ichoran** [comment]
I think this pull request is totally the wrong place for this discussion.  Propose on scala-internals?

**Comment by soc** [comment]
@Ichoran Agree. This is basically what I'm proposing: https://github.com/soc/scala/commit/4b250e91a6e7950ec851fb72c57637c52616cc3a?w=1

**Comment by soc** [comment]
Done: https://groups.google.com/forum/#!topic/scala-internals/MSUIi3NuI2s

**Comment by Ichoran** [comment]
The new PR is a bad idea in the context of Java.  The C standard is that round converts float to float, but unfortunately this dramatically violates the principle of least surprise for Java programmers.

**Comment by adriaanm** [comment]
@Ichoran, which new PR are you referring to, or do you mean the current PR as it currently stands?
Please edit your LGTM comment to reflect accordingly if necessary. The bot looks at comments that start with LGTM to label PRs that should be ready for merge, so that the merger need not look at other comments

**Comment by Ichoran** [comment]
@adriaanm - Fixed comment.  The first commit is good.  Other two I'm not sold on yet.  (I think the second is probably a bad idea, and the third is appealing but without the second there's less reason for it.)

**Comment by soc** [comment]
@adriaanm The point is that the second/third commit move the semantics of `round` to a consistent behavior across numeric types (and also btw with ceil/floor).

The issue with the current approach is that `Float`'s/`Double`'s `round` converts the rounded number to a different numeric type afterwards, which breaks any assumption that the value returned is actually the rounded value of the value passed in.

Imho, it is extremely dangerous and hard to debug, because it works with small values, but breaks with larger ones.
`11111111.111f.round != 11111111` is one case of that issue, the behavior around values which are larger then what integral types can represent is another one, and `NaN` is a third one.

The change moves the semantics is in line with languages/libraries like C# by just not doing the unnecessary conversion after rounding. ("Java did that mistake" is not a good reason to keep repeating that mistake in Scala.)

In that sense, the first commit is a stop-gap measure, which wouldn't be necessary if we had a sane handling of numeric types (no crazy conversions between integral and floating-point values), while the second and third one are necessary even without fixing our numeric hierarchy.

**Comment by soc** [comment]
I think this comment by @non explains the issue in a great way:

> If you agree with Rex (that round being A => A would be a dealbreaker
> due to divergence with Java) then obviously it's a problem. I respect
> this position, and it has certainly driven many other library
> decisions in Scala.
> 
> Personally I think this change would be a net win for the language in
> the long term. But like I said before it's not my job to worry about
> these kinds of trade-offs; I prefer to continuously move toward
> "better" even if it causes some temporary confusion [1].
> 
> -- Erik
> 
> [1] I have seen Scala developers using round() without realizing it
> has only a limited range where it is "safe" (and otherwise it produces
> a drastically wrong answer). I imagine this issue hurts Java
> developers less since they must annotate more of their types.
> 
> So the balancing act is between confusing Java programmers and
> confusing Scala programmers IMO. And since Double => Long is not a
> valid promotion, I doubt any programmer hoping to use round() to get a
> Long will be confused for long upon seeing the type error. 

¹ https://groups.google.com/d/msg/scala-internals/MSUIi3NuI2s/TdXo1FAY5AMJ

**Comment by Ichoran** [comment]
I want to make clear that `round` behavior is _already_ consistent: round (with no parameters) converts from a floating-point type to the most similarly-sized integer type.  The first commit catches an unpleasant consequence of this by making sure that if you're already an integer type, `round` keeps you there (so with the first commit, the rule is: whatever you are, `round` takes you to the most similarly-sized integer type).

The second and third commits decide upon a different type of consistency: instead of the closest-sized integer type, keep the _same_ type but round to an integer (or as close as you can manage).  This has advantages of _simplicity_ but not of _consistency_ since the old way was already consistent.

I am unconvinced that this significant behavioral change (note that `rint` is the method that already does what `round` is slated to do--and yes, it's a travesty that they're labeled the way they are) is worth the breakage it will cause just for simplicity.  (Especially since it will add a barrier to adoption for people who know `java.lang.Math`, because we obviously can't change that.)

**Comment by soc** [comment]
Imho, not fixing this bug because "that's what Java does" is a huge disservice for everyone not coming from the Java world, in addition to the 98% of the Java people who don't know that `round` doesn't round reliably outside of toy examples.

If "that's what Java does" is supposed to be the argument why we shouldn't fix this, we should go straight ahead and deprecate/remove `Double#round`, `Float#round` altogether, because Java doesn't have these methods either.

**Comment by Ichoran** [comment]
@soc - Round does what it says: it rounds.  Whether the type reflects the change is not something one can easily intuit; people will stumble on it either way.  Same deal with `atan2`; you need to read the docs to know whether x or y comes first.

Numeric convenience methods are there to be convenient.  It's bad when they just clobber your code in unexpected ways (123456789.round), so the first commit is a great fix.  Otherwise, though, gratuitous changes to behavior that _some_ know (especially experts from the biggest target audience) is inadvisable.

Adding methods whose behavior is more immediately obvious is less problematic.  For example, given methods roundInt, roundLong, roundDouble on Double, I'm pretty sure I could guess what each did.  iround, lround, and dround are pretty clear too when viewed together.  (Docs wouldn't sort them together, though.)

**Comment by Ichoran** [comment]
@soc - Also, counterarguments mentioning "toy examples" aren't very helpful, since they are contradicted by complex projects using java.lang.Math's round.  If you want to make a counterargument, you should argue that jl.Math isn't _self_-consistent and we're just fixing that.  You sort of did parenthetically?

Also, leaving things deprecated without a solution isn't very nice for people who dislike wading through dozens of deprecation messages.  If you're trying to make a strong case that this is a good idea, you shouldn't leave people's code in such a mess with no canonical way to fix it.

Also, `signum` is still "broken".  (Admittedly, less "broken" than `round`.)

What do you think about, deprecation or no, just introducing `whole` to mean what you wanted `round` to mean (and what `rint` means now)?

**Comment by soc** [comment]
@Ichoran 

> Round does what it says: it rounds.

Rounding certainly doesn't imply returning a different number type, especially when that number type can't even represent the result of the rounding correctly.
Pretty much every person who is not intimately familiar with numerics will easily miss that `round` will behave more like `rand` in some cases.
Almost everyone knows what rounding is supposed to mean since it was taught way back in school. Violating this assumption is not a good idea.

> Otherwise, though, gratuitous changes to behavior that some know (especially experts from the biggest target audience) is inadvisable.

I'm not building a language for "experts". Experts can easily deal with it and get the behavior they want. I care about the 99% of non-experts, which don't have that chance currently.

> For example, given methods roundInt, roundLong, roundDouble on Double, I'm pretty sure I could guess what each did.

Which is what I more or less did in commit number 2. Those who want their numbers to be broken can easily get that behavior back.

> since they are contradicted by complex projects using java.lang.Math's round

"Some people can deal with it" is not an argument which holds much water for me. I want all people to be able to deal with it, not a chosen few.

> If you want to make a counterargument, you should argue that jl.Math isn't self-consistent and we're just fixing that. You sort of did parenthetically?

Yes, jl.Math is not consistent with many standard libraries out there, which treat rounding correctly.
Really, I could probably come up with tons of examples where Scala is not "consistent" with PHP, or JavaScript or whatever. Should we care? Should we change our libraries to be more "familiar" to PHP developers? Let's not put our quality standards this low. I'm not seeing why "this is what Java does" should defy our quality standards here.

> Also, leaving things deprecated without a solution isn't very nice for people who dislike wading through dozens of deprecation messages.

I'm certainly open to suggestions. I'm thinking of replacing the `@deprecated` with an `@migration`. What do you think? The message could also be improved too to point out that adding `.toInt` keeps the code behaving as is in both older versions as well as in versions after the change.

> Also, signum is still "broken". (Admittedly, less "broken" than round.)

This has been discussed before. As Erik mentioned, the problem is that `signum` is pretty performance sensitive. This needs further thought.

> What do you think about, deprecation or no, just introducing whole to mean what you wanted round to mean (and what rint means now)?

No. If we can't make things work, we should deprecate and remove them, not add additional confusion. Adding `whole` just means we need to play even more games of "defending against lossy conversions". I'd like to get rid of that mess, not add even more methods to it.

I don't care whether we have a method which does rounding. I care about not having a method called `round` which doesn't round.

So either deprecate -> change, or deprecate -> remove. If it makes people happy, we can also have deprecate -> remove -> reintroduce.

**Comment by Ichoran** [comment]
That _you_ think rounding doesn't imply returning a different number type says something about you, but not about the name of the method.  If you round, you move from x in R to x in Z in mathematics.  That--along with ceiling and floor--does effectively change your domain, though if you continue to use operations in the field R, you will well, stay in R (whereas if you change to using operations on the ring Z, you'll stay in Z).  Floating point numbers are just weird mathematically, so you cannot have good intuition from math.  You must look up the docs, and continually remember that you're working with an approximation.  (E.g. `(0.1 + 0.2) == 0.3` is false.  This is nuts.  But I don't think we should deprecate binary floating point in Scala and insist we use only binary-coded decimals.)

Anyway, the point remains: if you charge into using floating point numbers without paying attention, you are likely to get burned.  It's unfortunate, but that's the way things are not with Java but with _mathematical computation in general_.  In this context, particular idealized notions of what `round` ought to do are not very good guides.  The same reasoning will lead you to abandon floating point entirely if followed to logical (reasonable, even) conclusions.

If we accept that people need to learn that `(0.1 + 0.2) != 0.3` and that `atan2(0,1) = atan(0)`, then adding that `round` returns `Long` is no big deal.  Having `123456789.round` clobber your number is horrible because it means that even when you _don't_ have any intention of dealing with floating point, it might come bite you.  But you fixed that already.

Anyway, one might argue (since you have not): `floor` and `ceil` stay within the same type.  We should provide a method for rounding that does the same.  It is, a little unfortunately, called `rint`, but that is our trio and that is what we'll provide: `floor`, `rint`, and `ceil`.  If you want something called `round`, it is your job to decide whether you want it to do what everyone expects it to do (who has any expectation that's worth anything, i.e. they know something about using floating point numbers on the JVM, meaning with the Java libraries), or whether you want it to be the type-consistent member of the trio along with `floor` and `ceil`.

As far as messages go, @migration adds as much clutter as @deprecation, so that issue isn't really resolved.  If you don't have anywhere to migrate to, it's not a very nice thing to do unless it's so broken that it can't reasonably be used properly.  This is workable.  Not great, but workable.  (Note that blanket `.toInt` isn't a fix either, since `Float` rounds to `Int` but `Double` rounds to `Long`.)

**Comment by soc** [comment]
> That you think rounding doesn't imply returning a different number type says something about you, but not about the name of the method.

Oh thanks. I guess this was meant as a compliment.

> Anyway, the point remains: if you charge into using floating point numbers without paying attention, you are likely to get burned.

... and I remember who fought tooth and nail to keep it that way. "I prevented a fix for X, so please take that bugginess-level as a standard for further work"? The first commit wouldn't even need to exist otherwise.

> If we accept that people need to learn that (0.1 + 0.2) != 0.3 and that atan2(0,1) = atan(0), then adding that round returns Long is no big deal.

There is some complexity which is required by IEEE754 and unnecessary complexity which we have because we repeated mistakes of others. Having the first doesn't mean we have to accept the second one, too.

> who has any expectation that's worth anything, i.e. they know something about using floating point numbers on the JVM, meaning with the Java libraries

I'm kind of disturbed how you keep insulting people.

> If you don't have anywhere to migrate to, it's not a very nice thing to do unless it's so broken that it can't reasonably be used properly.

??? They have somewhere to migrate to. It's spelled out right in the deprecation message.

**Comment by Ichoran** [comment]
> I'm kind of disturbed how you keep insulting people.

Guess I'm not doing a very good maintaining an even tone in the face of things like

> in addition to the **98% of the Java people who don't know** that round doesn't round reliably outside of **toy examples**

which kind of insults 100% of Java people and whichever Scala people already use `round` (as everything they're using it for must be a "toy example").

Lowering the tension level of the rhetoric would be advisable all around.

That way we could more rapidly discover that I didn't see the end of the deprecation message (scrollbar issue), so didn't see the `roundToInt` part.  That's less bad.  You don't provide it for `Float` or `Double`, though, so people have to change `(x + y - 1).round` to `roundToLong(x + y - 1)`, which is rather annoying.  And you didn't add `roundToInt` to e.g. `Int` so if people get their types wrong the original issue still exists.

However, the fundamental issue is that you are protective of the ease of adoption of Scala (which is great) at the expense of maintaining working code (which is not great).  If you can provide some evidence that `round` confuses people for more than a few seconds ("Huh?...read docs...oh, okay."), I'm happy to change my mind.  If people can't in practice notice that round returns an int or long, and this causes buggy code, then we should fix it.  But after going through about a hundred questions on round on StackOverflow, I only found one that shows any indication of the kind of confusion you're worried about: http://stackoverflow.com/questions/13301612

And then one has to ask--if you are trying to round something which can't even represent sequential integers much less fractions of one, do you really have the problem under control?  Maybe not?

"I want to break a bunch of difficult-to-write code for unclear benefit" is not something that gets my approval very often.  I do prefer `round` over `rint` as the option between `floor` and `ceil` for aesthetic reasons (or maybe just because I learned C before Java and still remember that `round`), but I am not going to put my aesthetic sense above the time and effort of a sizable number of other people who may well have been doing something difficult.  Absent evidence of actual significant confusion (beyond what is already fixed with adding `round` to `RichInt` and such), and absent a PR that does its utmost to preserve existing effort, I think this change would cause more problems than it solves, especially in the short-to-medium term.

(And, incidentally, I don't think it's objectively clear whether `floor` and `ceil` should go to integer-types along with `round`, or whether all should keep the floating-point type, even if I do think it's better that all three have the same policy.)

**Comment by Ichoran** [comment]
Were you going to open a new PR with the non-contentious and useful/protective part of this PR?  Despite the fuss over the latter part, that was really valuable IMO.  Or would you prefer me to?

**Comment by soc** [comment]
No. Just leave it as-is. The cost of that hack is not worth the benefit.
SI-3235 is closed as "Won't Fix" anyway.

**Comment by adriaanm** [comment]
I appreciate both of you hashing this out in detail, but let's please try to remain [dispassionate](http://devblog.avdi.org/2014/02/10/the-passion-gospel/):

> The word “dispassionate” is defined thus: “not influenced by strong emotion, and so able to be rational and impartial.” I submit that taking a dispassionate position is more likely to result in writing good software, especially when working in a team. When it comes to solving problems with code, it’s not a contest for who feels the strongest about their solution.

We all agree the first commit is a net-win, but the gain of the others is not clear. @soc, please do consider submitting that part of your PR, or the refinement that was discussed later. We do have an overall philosophy in Scala, and while I respect you may not like it, this is not the place nor the time to change that.

Given how much time everyone's already spent on this PR, I think it would be good to conclude with a merge rather than a close.

Thanks & have a nice weekend!

**Comment by Ichoran** [comment]
Offered a minimal PR for the non-contentious part (hopefully?) at https://github.com/scala/scala/pull/3556

**Pull request closed without merging**
