### PR TITLE
SI-9924: Fix: Spec. refers to U+007F (DELETE) as printable character

### PR DESCRIPTION
**Pull request by dsbos**
Fixed "\u0020 - \u007F" to "\u0020 - \u007E".
(Also fixed/clarified punctuation and grammar.)

### CODE REVIEW

**Comment by som-snytt** [comment]
LGTM

I'm not sure the grammar of the sentence actually implies that 0x7f is printable, but putting the range in parens or commas, as a parenthetical, does imply it.

Using `that` for the restrictive clause is a clear win for the Coders Who Care movement.

The PR comment has an obvious typo.

**Comment by dsbos** [comment]
> The PR comment has an obvious typo.

Ack!  It was in my commit comment too.  I've amended the commit to fix that and re-pushed.

> I'm not sure the grammar of the sentence actually implies that 0x7f is printable, but putting the range in parens or commas, as a parenthetical, does imply it.

Right, the grammar probably didn't necessarily imply that "all printable ASCII characters" was the same as (the characters represented by) "\u0020 - \u007F."  

However, there doesn't seem to be any point in listing a character range that is a (proper) superset.  (Although having the range in the text "all printable ASCII characters in the range "\u0000 - \u007F" wouldn't make anything false, it wouldn't add any information.)  

Therefore, it seemed that the intent of the original author(s) was to specify what "printable ASCII character" meant.  My proposed punctuation/wording changes try to specify that more clearly.

**Comment by som-snytt** [comment]
I just noticed https://github.com/scala/scala/blame/2.12.x/spec/13-syntax-summary.md#L32

> ./13-syntax-summary.md:printableChar    ::= // all characters in [\u0020, \u007F] inclusive

Thanks, grep.

Update: I tweaked that in https://github.com/scala/scala/pull/5407

**Comment by SethTisue** [comment]
I'll figure out what the (unrelated) test failure is about (in the next few days, hopefully)

**Comment by SethTisue** [comment]
can you rebase this against the current head of the `2.12.x` branch, please? I don't know what else to suggest.

**Comment by SethTisue** [comment]
I rebased it myself (with GitHub's new feature that allows upstream repo committers as collaborators on PR branches in forks) — it was 965 commits behind, so no wonder. presumably Jenkins will pass now

**Comment by SethTisue** [comment]
oboy — ok, I'll into it this week sometime :-(

**Comment by dsbos** [comment]
Oops.  I merged (instead of rebasing) and already pushed that merge commit (695dac4).

(How do I delete 695dac4 from this PR's branch on my GitHub repository?)

**Comment by SethTisue** [comment]
fixed with `git push -f dsbos 4289842:dsbos-SI-9924`

**Comment by lrytz** [comment]
Kind of related: why does `Random.nextPrintableChar` exclude 32 (space)? https://github.com/scala/scala/blame/2.12.x/src/library/scala/util/Random.scala#L92-L99

**Comment by lrytz** [comment]
Is there a definition in the spec itself of "printable ASCII character"?

I was also wondering if the compiler (parser? scanner?) uses some definition of "printable ASCII character", but couldn't find anything in the code (except for `Random.nextPrintableChar`).

**Comment by dsbos** [comment]
> Is there a definition in the spec itself of "printable ASCII character"?

The addition of parentheses in my change makes the text say (though not as strongly as it could be specified) that "printable ASCII characters" means the characters from U+0020 to U+007E (inclusively).

There's also a definition of non-terminal printableChar in the syntax summary.

**Comment by dsbos** [comment]
Is the ball in my court to do something (including pinging someone about approving and merging or giving further feedback about this PR) to keep this PR alive, or is it in someone else's court (just waiting for them to have time to get to it)?

**Comment by SethTisue** [comment]
sorry, the 2.12.1 queue is mostly stalled while we try to get 2.12.0-RC2 and 2.12.0 out the door. we’ll get to it

**Comment by SethTisue** [comment]
thanks @dsbos!

**Pull request merged**
