### PR TITLE
SI-8650 F-interpolator inlines literals

### PR DESCRIPTION
**Pull request by som-snytt**
FormatInterpolator checks that indexed specifiers (like %3$d) refer to
arguments that are compatible with the specifier.

When arguments are literal constants, aka constant value expressions,
they are inlined using the specifier.

Sample debug output showing that only one arg is evaluated at runtime:

```
scala> :load -v test.script
Loading test.script...

scala> def x = System.currentTimeMillis ; final val i = 17 ; final val pi = 3.14 ; final val s = "hello, world"
x: Long
i: Int(17) = 17
pi: Double(3.14) = 3.14
s: String("hello, world") = hello, world

scala> f"$x $pi%f %<s $i%d $s %1$$d"
Format '%s 3.140000 3.14 17 hello, world %1$d' with 1 tmps and 1 args
res0: String = 1422731811259 3.140000 3.14 17 hello, world 1422731811259
```

It doesn't attempt (bother) to inline enum symbols and class constants.

I ran out of patience getting the "incompatible arg" error caret
position correct. Is there a list of "things that should be trivial"?

### CODE REVIEW

**Comment by retronym** [comment]
```
fail - neg/stringinterpolation_macro-neg.scala
fail - run/stringinterpolation_macro-run.scala
```

**Comment by som-snytt** [comment]
@retronym Thanks, I had a few LOF (fixes) from early this morning. This is maybe worth it, but niggling work.

**Comment by som-snytt** [comment]
The update does a couple of more tricks to avoid exceptions.

```
scala> f"${null}%#s"
<console>:8: error: Requires an instance of java.util.Formattable
              f"${null}%#s"
                         ^

scala> f"${42000}%,,d"
<console>:8: error: Duplicate flag ','
              f"${42000}%,,d"
                          ^

scala> f"${3.14}%f %<d"
<console>:8: error: Specifier '%<d' not compatible with indexed arg
              f"${3.14}%f %<d"
              ^
```

**Comment by som-snytt** [comment]
He forgot to mention that it encodes directly to `String.format(fstring, args...)` now.

**Comment by som-snytt** [comment]
Requires more manual constant expression evaluation.

**Comment by som-snytt** [comment]
Moving on: https://github.com/scala/scala/pull/4316

**Pull request closed without merging**
