### PR TITLE
SI-8321 bundles can't be whitebox

### PR DESCRIPTION
**Pull request by xeno-by**
review @retronym

### CODE REVIEW

**Comment by retronym** [comment]
LGTM. Well tested and presented. Macro bundles are themselves a new feature, so the surface area for regressions is low.

@adriaanm I recommend this one for RC1, but I'll let you make the call on that as its hard to argue that this is a blocker, other than noting that by _not_ fixing these quirks now, we're probably locked into them for 2.11.N

**Comment by xeno-by** [comment]
Hey guys! Everything is green, so how about we merge? Please, let this thing in - I would be very ashamed if macro bundles will be released like that.

**Comment by adriaanm** [comment]
What Jason said. Merging.

**Comment by xeno-by** [comment]
Oh yeah! This made my weekend!!

**Pull request merged**
