### PR TITLE
Fix bounds of higher-kinded existentials pt. 2

### PR DESCRIPTION
**Pull request by joroKr21**
I missed that in #6123

### CODE REVIEW

**Comment by milessabin** [comment]
I think the old error message in the failed neg test is more readable ... can you persuade it to have the same form after your change?

Otherwise :+1:

**Comment by joroKr21** [comment]
Any suggestions how to do that? I guess modifying the printer?

**Comment by joroKr21** [comment]
That's frustrating:
```scala
scala> class Functor[F[_]]
defined class Functor

scala> new Functor[Any]
res0: Functor[Any] = Functor@5707f613

scala> new Functor[Nothing]
res1: Functor[Nothing] = Functor@7c453c34

scala> new Functor[({ type F[x] = Any })#F]
res2: Functor[[x]Any] = Functor@1689527c

scala> new Functor[({ type F[x] = Nothing })#F]
res3: Functor[[x]Nothing] = Functor@70f4abc1
```
How do we know if `Any` / `Nothing` appear in kind-polymorphic context?

**Comment by milessabin** [comment]
There probably needs to be some normalizing of `Any` and `Nothing` to the non-`PolyType` form ... cp. https://github.com/scala/scala/blob/2.13.x/src/reflect/scala/reflect/internal/Types.scala#L4896-L4910

**Comment by joroKr21** [comment]
Wait a minute, are you saying you find `Option <: [x]Any` more readable or `Option <: Any`? It seems that the printer is being dumb and prints whatever given. We can go from `[x]Any` to `Any` with the functions you linked, but not the other way.

**Comment by milessabin** [comment]
I find `Option <: Any` more readable.

**Comment by joroKr21** [comment]
Somehow rebasing changed the error message back to `Option <: [X]Any`

**Comment by joroKr21** [comment]
I misread the diff - it's actually `Option <: Any`

**Pull request merged**
