### PR TITLE
Prevent creation of one element HashSetCollision1

### PR DESCRIPTION
**Pull request by rklaehn**
if there is one element, there is no collision!

A problem with this might be that size for ListSet is O(N), and there is no other way to figure out if a ListSet contains exactly one element. Also, head might not be efficient for ListSet. 

But clearly having a HashSetCollision1 with one element is undesirable.

### CODE REVIEW

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Again, why 2.9.x?   We're pushing a 2.10.x release shortly.  2.9.x gets fixes on an as needed basis.

**Comment by rklaehn** [comment]
Hi Josh,

sorry, that was a mistake.

**Comment by rklaehn** [comment]
Closing this because it was against 2.9.x. Will open a new one against 2.10.x.

**Pull request closed without merging**
