### PR TITLE
SI-8339 remove deprecated rewrite of withFilter -> filter

### PR DESCRIPTION
**Pull request by adriaanm**
Let's try this again. Cross-ref #3566

### CODE REVIEW

**Comment by szeiger** [comment]
Did you run a community build for this PR?

**Comment by adriaanm** [comment]
Not yet.

**Comment by adriaanm** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/470/console

**Comment by adriaanm** [comment]
(rebased to latest 2.12.x to see if that fixes the community build fail?)

**Comment by adriaanm** [comment]
community build is green

**Comment by adriaanm** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/472/console

**Comment by szeiger** [comment]
`nme.filter` is also referenced in `RefChecks` and `ReificationSupport`. It looks to me like these special cases can also be removed.

**Comment by adriaanm** [comment]
I removed the one from refchecks, but settled for a TODO in ReificationSupport as I didn't have time to dig into what this is meant to do.

**Comment by szeiger** [comment]
LGTM

**Pull request merged**
