### PR TITLE
[nomaster] backports 609047ba37

### PR DESCRIPTION
**Pull request by xeno-by**
review @retronym @gkossakowski

### CODE REVIEW

**Comment by gkossakowski** [comment]
Please link to commit that is in master. The 609047ba37 points at your repo.

**Comment by xeno-by** [comment]
Hmm, for me the link says `https://github.com/scala/scala/commit/609047ba37`

**Comment by gkossakowski** [comment]
Weird. It works now. Sorry for the noise.

**Comment by gkossakowski** [comment]
When it comes to backport itself I'm not really qualified to asses the risk so I'll leave it to @retronym.

**Comment by xeno-by** [comment]
Can it still become part of 2.10.4? Would be quite helpful, because it's probably the third or fourth time recently I get a question about this behavior.

**Comment by retronym** [comment]
We've already cut RC3, unfortunately. So lets leave this in queue until we conform that we don't need a RC4. (we haven't bothered to branch for 2.10.4 this time)

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Can we merge this now, since RC3 is cut anyway?

**Comment by retronym** [comment]
We'll wait until rc3 becomes final.

**Comment by xeno-by** [comment]
Ping @retronym

**Comment by retronym** [comment]
Can you amend the commit message to be more like a typical got cherry pick -X?

**Comment by xeno-by** [comment]
Here you go.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
