### PR TITLE
Minor code improvement under`nsc.settings`

### PR DESCRIPTION
**Pull request by rituraj2342**

### CODE REVIEW

**Comment by som-snytt** [comment]
Since retronym noticed https://github.com/scala/scala/pull/6209/commits/1bc77ca1bb41a789c35b633e06568952f65084ff, we're all afraid to use `nonEmpty`. 

I think such changes should be motivated, since evaluating whether it is an improvement is not trivial.

Consider that Scala 3 enforces that all fixes be "minimal", that is, don't "polish" code outside the motivating feature or bug fix.

**Comment by rituraj2342** [comment]
Got it. Thanks for the info..

**Comment by rituraj2342** [comment]
@som-snytt All checks are passed. Can you please merge it..

**Comment by SethTisue** [comment]
I'm curious if this some kind of classroom requirement you're trying to fulfill. If so, please be open with us about that.

If this _isn't_ for a class, please help us understand your motivations. Are you trying to learn the ropes so you can move on to submitting more ambitious changes? If so, then there's value for us in spending time assisting you. If not, then as Som says, it's not clear that the cost/benefit for us as reviewers is there.

**Comment by rituraj2342** [comment]
@SethTisue These changes are just to minimize build complexity which are observed in CI.

**Comment by SethTisue** [comment]
Okay — if we can help you find something you'd like to work on here, let us know. We're also available for chat about contribution ideas on the #scala-contributors channel on the Scala Discord, and on the https://contributors.scala-lang.org forum too.

**Comment by rituraj2342** [comment]
Thanks for the info @SethTisue

**Comment by som-snytt** [comment]
I forgot to mention that I noticed retronym had an earlier PR that included changing `isEmpty` tests on lists to `ne Nil`.

I think I've written `case Nil` as `case _: Nil.type`. Note that it is rewritten from `scala.package.Nil` in Cleanup.

Checks on `NoSymbol`, by contrast, are less effective because the reference must indirect through the cake.

**Comment by SethTisue** [comment]
Must. Not. Micro. Optimize.

except when one must :-)

**Pull request closed without merging**
