### PR TITLE
Make scalac's argument-file processing more like javac's in handling spaces and line breaks

### LINKED ISSUE #12732: Make argfile work (more) like javac
## Reproduction steps

Scala version: 2.13.10

`scalac @file` expects an arg per line instead of parsing argfile lines. This breaks existing argfiles.

Instead, respect `javac` conventions (which appear to be similar to previous behavior):

> An argument file can include command-line options and source file names in any combination. The arguments within a file can be separated by spaces or new line characters. If a file name contains embedded spaces, then put the whole file name in double quotation marks.

`javac` tolerates the following variant quotations:

```scala
-d "target dir"
```

```scala
-d "target di"r
```

```scala
-d "targ"et
```

```scala
-d "target
```

```scala
-d 'target dir'
```

The following creates the output dir `target dir"`, and demonstrates that `javac` does not model fine behavior.
```scala
-d 'target dir"
```

## Problem

Maintain compatibility with once and future versions, including WWJD.

Per the doc for `javac`, quotation is intended to support spaces in file paths, as opposed to shell-style command lines.

Noticed at https://github.com/scala/scala/pull/10316

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12732; the ticket has details on the behavior differences

### CODE REVIEW

**Comment by michelou** [comment]
@som-snytt Your changes work for me, thanks. I closed PR #10316 in favor of your PR after testing your changes with several Scala 2 code examples. I also patched the 2.13.10 installation (i.e. `scala-compiler.jar`) on my machines until version 2.13.11 is available.

**Comment by som-snytt** [comment]
@michelou Thanks for trying out the fix. I will probably not further tweak to be bug-compatible with Java.

To summarize, the change in 2.13.10 arrived in 2.13.9 but deemed too late in the cycle to refine, so it was reverted and deferred, but then did not receive further scrutiny; I see it got the "release notes" label, but only the `-Vprint-args` feature was highlighted.

I was hoping to use the same tokenizer for `sys.process` and arg files. That is a pipe dream. (`sys.process` pun.)

I'd forgotten this bug mentioned in my PR, which makes it sound like JDK has quoting bugs in both places:
https://bugs.openjdk.org/browse/JDK-8282008

The context is complicated by the reverts, but the original PRs were:
https://github.com/scala/scala/pull/10114
https://github.com/scala/scala/pull/10123

**Review by SethTisue — APPROVED** [review]
thanks @michelou for bringing this to our attention, and thanks @som-snytt for untangling the history

**Comment by SethTisue** [comment]
@som-snytt I improved the title and PR description a bit. not sure whether to put additional effort into it; on the one hand it's an incompatible change, so people need to know, but otoh I doubt the feature is widely used

**Comment by som-snytt** [comment]
@SethTisue yes, I think is really a reversion. If I could go back in time and live my life over again, this is what I would do differently.

I only work on features that nobody uses, so it should be safe.

**Comment by michelou** [comment]
@SethTisue Just one reminder to make sure this fix will go into release 2.13.11 : [**Kotlin**](https://kotlinlang.org/docs/compiler-reference.html#argfile) and [**Scala 3**](https://github.com/lampepfl/dotty) do behave the same as [**Java**](https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html) in respect to the handling of argument files passed on the command line.

**PS.** I make use of argument files in most build scripts (bash, batch, Makefile) available from my Github repositories (e.g. [`kotlin-examples`](https://github.com/michelou/kotlin-examples), [`dotty-examples`](https://github.com/michelou/dotty-examples), [`akka-examples`](https://github.com/michelou/akka-examples), etc..) when invoking the commands [`javac`](https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html), [`kotlinc`](https://kotlinlang.org/docs/compiler-reference.html), and [`scalac`](https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala) (v3).

**Comment by SethTisue** [comment]
yes. I've been fighting other fires. but this will make 2.13.11.

**Review by lrytz — APPROVED** [review]

**Pull request merged**
