### PR TITLE
Bump version for 2.12.x

### PR DESCRIPTION
**Pull request by retronym**
For this step, we still depend on _2.11 libraries (partest, xml,
parser-combinators).

After we release the first milestone of 2.12, we will update
versions.property to bootstrap to 2.12 dependencies.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski or @adriaanm

**Comment by gkossakowski** [comment]
LGTM

**Comment by retronym** [comment]
```
++ [[ -f /localhome/jenkins/c/workspace/pr-scala-publish-core/mergetarget ]]
++ git rev-parse FETCH_HEAD
++ git checkout --detach -f FETCH_HEAD
HEAD is now at 251616a... Merge pull request #3686 from densh/topic/re-enabled-typechecked-types
++ git clean -fxd
++ git merge 87e2d7ff7663ab2b73c9bfdbec9a0aa287e3c9d2
Updating 251616a..87e2d7f
Fast-forward
 build.number |    4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
++ echo 'Building commit 87e2d7ff7663ab2b73c9bfdbec9a0aa287e3c9d2 of #3715 (merged into 2.12.x).'
Building commit 87e2d7ff7663ab2b73c9bfdbec9a0aa287e3c9d2 of #3715 (merged into 2.12.x).
++ cd /localhome/jenkins/c/workspace/pr-scala-publish-core/
++ ./jenkins-scripts/job/pr-scala-publish-core
Dry run? 
Removing build.number.sh
Resolving [ddd7d5398733c4fbbb8355c049e258d47af636cf/lib/forkjoin.jar]
Resolving [2c61d6e9a912b3253194d5d6d3e1db7e2545ac4b/lib/ant/vizant.jar]
Resolving [7b456ca6b93900f96e58cc8371f03d90a9c1c8d1/lib/ant/ant.jar]
Resolving [943cd5c8802b2a3a64a010efb86ec19bac142e40/lib/ant/ant-contrib.jar]
Resolving [7e50e3e227d834695f1e0bf018a7326e06ee4c86/lib/ant/maven-ant-tasks-2.1.1.jar]
Resolving [3fc1e35ca8c991fc3488548f7a276bd9053c179d/lib/ant/ant-dotnet-1.0.jar]
Resolving [e737b123d31eede5594ceda07caafed1673ec472/test/files/codelib/code.jar]
Resolving [cd33e0a0ea249eb42363a2f8ba531186345ff68c/test/files/lib/nest.jar]
Resolving [be8454d5e7751b063ade201c225dcedefd252775/test/files/lib/methvsfield.jar]
Resolving [981392dbd1f727b152cd1c908c5fce60ad9d07f7/test/files/lib/enums.jar]
Resolving [02fe2ed93766323a13f22c7a7e2ecdcd84259b6c/test/files/lib/annotations.jar]
Resolving [b1ec8a095cec4902b3609d74d274c04365c59c04/test/files/lib/genericNest.jar]
Resolving [3794ec22d9b27f2b179bd34e9b46db771b934ec3/test/files/lib/macro210.jar]
Resolving [346d3dff4088839d6b4d163efa2892124039d216/test/files/lib/jsoup-1.3.1.jar]
Resolving [1b11ac773055c1e942c6b5eb4aabdf02292a7194/test/files/speclib/instrumented.jar]
Resolving [a1883f4304d5aa65e1f6ee6aad5900c62dd81079/tools/push.jar]
mv: cannot stat `/localhome/jenkins/c/workspace/pr-scala-publish-core/scala/buildcharacter.properties': No such file or directory
Build step 'Execute shell' marked build as failure
```

https://github.com/scala/jenkins-scripts/commit/3c92eead33ea0969c6fedba37ab46ae1f52397f5 ?

**Comment by retronym** [comment]
PLS REBUILD ALL

https://github.com/scala/jenkins-scripts/pull/105

**Comment by retronym** [comment]
Here's the problem with `-integrate-partest`

``` scala
object ScalaModulePlugin extends Plugin {
  val snapshotScalaBinaryVersion = settingKey[String]("The Scala binary version to use when building against Scala SNAPSHOT.")
  ...
  def deriveBinaryVersion(sv: String, snapshotScalaBinaryVersion: String) = sv match {
    case snap_211 if snap_211.startsWith("2.11") &&
                     snap_211.contains("-SNAPSHOT") => snapshotScalaBinaryVersion
    case sv => sbt.CrossVersion.binaryScalaVersion(sv)
  }
```

**Comment by retronym** [comment]
Updating `sbt-scala-modules` https://github.com/scala/sbt-scala-modules/pull/7

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
NOLITTER!
PLS REBUILD ALL

**Comment by retronym** [comment]
I've disabled IDE validation for 2.12.x branch for now. We'll aim to have that up and running again in two weeks.

**Pull request merged**
