### PR TITLE
Fixes first sentence delimiters

### PR DESCRIPTION
**Pull request by dgruntz**
Scaladoc places the first sentence in the method summary table and index. The first sentence is defined as the sequence of chars up to the first period (not as in JavaDoc where the sentence ends with the first period _followed by a blank_). As a consequence, the clause starting with `i.e.` ends the first sentence at a wrong position. This request replaces `i.e.` with `i&period;e&period;`. Alghough a valid HTML code, I do not know whether this change is compatible with other tools. And I assume that this is not the only source file affected.
An alternative fix would be to reformulate the summary of methods `onSuccess` and `onFailure`.

### CODE REVIEW

**Comment by som-snytt** [comment]
Are you aware of https://issues.scala-lang.org/browse/SI-8672 ?

I think ScalaDoc is markdown and not html. 

Personally, I prefer my i.e.'s and e.g.'s set off by, e.g., commas.

**Comment by gourlaysama** [comment]
It does work (scaladoc doesn't escape html escapes), but som-snytt's commas have the benefit of keeping the plain-text readable: `(i.e., with a value)`.

**Comment by dgruntz** [comment]
Thanks for the comments. I was not aware of the fix of https://issues.scala-lang.org/browse/SI-8672, so I followed the recommendation given by @som-snytt.

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
