### PR TITLE
Upgrade to ASM 7 for improved JDK 12 compat

### PR DESCRIPTION
**Pull request by lrytz**
improves compatibility with JDK 12

### CODE REVIEW

**Comment by SethTisue** [comment]
release-notes-able, I think. if this resolves any known issues or improves JDK 11 (or 9+) compat, could you say so in the PR description...?

**Comment by SethTisue** [comment]
https://www.lightbend.com/contribute/cla/scala/check/lrytz is as expected, so idk what's up with the CLA check, `/sync` isn't fixing it

**Comment by mkurz** [comment]
Close - Reopen pull request?

**Comment by SethTisue** [comment]
sigh. as for the Travis-CI failure,

```
[warn] there were 475 inliner warnings; re-run enabling -opt-warnings for details, or try -help
[warn] 8 warnings found
[error] ## Exception when compiling 161 sources to /home/travis/build/scala/scala/build/quick/classes/reflect
[error] null
[error] scala.reflect.internal.transform.Erasure.transformInfo(Erasure.scala:395)
[error] scala.reflect.internal.transform.Erasure.transformInfo$(Erasure.scala:389)
[error] scala.tools.nsc.transform.Erasure.transformInfo(Erasure.scala:22)
[error] scala.tools.nsc.transform.InfoTransform$Phase$$anon$1.transform(InfoTransform.scala:45)
[error] scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1634)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1551)
[error] scala.reflect.internal.Symbols$Symbol.tpeHK(Symbols.scala:1476)
[error] scala.reflect.internal.Types$Type.computeMemberType(Types.scala:736)
[error] scala.reflect.internal.Types$Type.memberType(Types.scala:733)
[error] scala.tools.nsc.typechecker.Infer$Inferencer.checkAccessible(Infer.scala:298)
[error] scala.tools.nsc.typechecker.Typers$Typer.makeAccessible(Typers.scala:584)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:5207)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedIdentOrWildcard$1(Typers.scala:5222)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5673)
[error] scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:797)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5721)
[error] scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:722)
[error] scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:797)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5721)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$39(Typers.scala:4795)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:704)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4797)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4825)
```

and many more such lines follow.

**Comment by lrytz** [comment]
Rebased to include the Xss from https://github.com/scala/scala/pull/7392

**Comment by mkurz** [comment]
Any chance to get this merged?

**Comment by SethTisue** [comment]
> release-notes-able, I think. if this resolves any known issues or improves JDK 11 (or 9+) compat, could you say so in the PR description...?

@lrytz ping

**Comment by lrytz** [comment]
I don't think there's a noticable change for users, it's mostly interesting for us because our fork is now very close to the official release.

**Comment by SethTisue** [comment]
as per https://github.com/scala/community-builds/issues/864 and https://github.com/scala/bug/issues/11372, this improves JDK 12 compat (projects that don't compile on JDK 12 on 2.13.0-M5 do compile on recently nightlies that include this PR), so I've added the release-notes tag and updated the PR description to say "improves compatibility with JDK 12"

**Comment by SethTisue** [comment]
submitted 2.12.x back port at #7780

**Comment by mkurz** [comment]
ASM 7.1 released, includes bug fixes: https://asm.ow2.io/versions.html

**Pull request merged**
