### PR TITLE
Make Rich* classes keep theirs "self"s non-public

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by adriaanm** [comment]
Needs two test updates:
  - https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/3751/testReport/junit/test.files/presentation/infix_completion/
  - https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/3751/testReport/junit/test.files/presentation/infix_completion2/

**Comment by SethTisue** [comment]
why `protected` and not `private`?

should `Proxy` be part of this? it seems orthogonal to other stuff and less clearly desirable since it isn't about extension methods

**Comment by dwijnand** [comment]
`protected` because `private` wasn't available, because `Proxy` is part of the inheritance chain of those classes. So I went with the next best thing, which is fine because `protected` on a `final` class is effectively `private`.

**Comment by SethTisue** [comment]
but does it make sense, is it desirable, for `Proxy` to hide `self`? it's a breaking change

**Comment by dwijnand** [comment]
I don't know `Proxy`, so I don't know. Doesn't look like any test broke from making it `protected`.

If anyone has a suggestion on how to achieve the desired result I'm happy to implement it.

**Comment by SethTisue** [comment]
@dwijnand I'd suggest just leaving `Proxy` alone

**Comment by dwijnand** [comment]
Can't. It's a parent and you can't reduce visibility.

**Comment by SethTisue** [comment]
> Can't. It's a parent and you can't reduce visibility.

sorry, I'm not following. why must this PR touch `Proxy.scala` at all?

**Comment by dwijnand** [comment]
All the Rich* classes extend `Proxy`, indirectly. So to make `self` non-public for them I changed `Proxy`.

**Comment by SethTisue** [comment]
ok, got it

and I see that in 2.12 `Proxy` was used in `scala.collection`, too, but in 2.13, not anymore, so yay for that.

the only other place in stdlib I see `Proxy` being used is in `scala/ref/ReferenceWrapper.scala`. the whole `scala.ref` package is (as per https://github.com/scala/scala/pull/5677) a candidate for being booted out of stdlib, but it looks to me like doing so is nontrivial (perhaps not really hard, but not trivial)

one possibility would be for `Rich*` to stop using `scala.Proxy`; you could just copy the code into `scala.runtime` and make it private to that package. what do you think? then the changes you want to make in this PR would no longer be hostage to either `scala.Proxy`'s past or its future

**Comment by dwijnand** [comment]
Might be wrong, but I fear the Rich* types extending `Proxy` will be relevant. Like in the compiler somewhere.

But let's have a look at that idea, and see how it turns out.

**Comment by SethTisue** [comment]
note that `self` being protected means that instead of it being completely hidden, as if it didn't exist, instead we get:

```
scala> 1.self
         ^
       error: value self in class RichInt cannot be accessed in scala.runtime.RichInt
        Access to protected method self not permitted because
        enclosing object $iw is not a subclass of
        class RichInt in package runtime where target is defined
```

**Comment by SethTisue** [comment]
having `self` protected results in:

```
scala> true.self
            ^
       error: value self in class RichBoolean cannot be accessed in scala.runtime.RichBoolean
        Access to protected method self not permitted because
        enclosing object $iw is not a subclass of
        class RichBoolean in package runtime where target is defined
```

this is not as satisfying as one might have hoped for.

if `self` were `private`, then we'd get a straight up "self is not a member of Boolean" error

does having our own private copy of `Proxy` make this problem solvable...?

**Comment by dwijnand** [comment]
Good point.

Only ways I can think are:

1. by inlining everything the 8 Rich* types need, or
2. by making the compiler do it

which both don't seem like good choices.

Do you think this is still worth doing?

**Comment by dwijnand** [comment]
@SethTisue Let's put it another way, any downside from merging this?

**Comment by adriaanm** [comment]
Didn’t follow the whole discussion because vacation, but how about name mangling? __self? __lostesso?

**Comment by SethTisue** [comment]
@dwijnand why close/delete? I haven't responded only because M5 tickets come first

**Comment by dwijnand** [comment]
Just lost interest in babysitting this PR.

**Comment by dwijnand** [comment]
> * by inlining everything the 8 Rich* types need, or

I tried revisiting this, seeing if I could inline everything, with property-based tests to back that everything is still as correct as in the original.

I'd classify it as not viable.  I hadn't noticed until now that `ScalaNumberProxy` (which is a supertype of every rich wrapper but `RichBoolean`) mixes in `ScalaNumericAnyConversions`, which are another 19-21 methods (2 are protected, not public)...

It also led me to realise the problem isn't just "self" it's also "underlying"...

```scala
scala> 1.self
res3: Int = 1

scala> 1.underlying
res4: AnyRef = 1
```

**Pull request closed without merging**
