### PR TITLE
SI-8375 saner binary incompat errors for macros

### PR DESCRIPTION
**Pull request by xeno-by**
Inspired by Brian McKenna's RC1 migration experience, this commit improves
macro impl binding validation in order to provide more helpful diagnostic
for this quite frequent class of errors.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
Can we specifically detect macros compiled with 2.10.x and report something more understandable than "incompatible macro engine?"

**Comment by xeno-by** [comment]
@retronym How about this one: https://github.com/xeno-by/scala/commit/3d92578645e0bf42ec80bffb7a61a2a028ea14da#diff-2a6890e4a6f54dc1abc26d3b7214ea5eL1?

**Comment by retronym** [comment]
Better, but that message will be incorrect in 2.12 unless we remember to
change it. Maybe just use "this version" rather than "2.11"

**Comment by xeno-by** [comment]
Done

**Comment by retronym** [comment]
LGTM

**Pull request merged**
