### PR TITLE
SI-1448 Deprecate conversion of numeric values types by casts

### PR DESCRIPTION
**Pull request by gzm0**
**Attention**: This is an alternative PR to #3294. Do **NOT** merge both.

Casts of AnyVals had inconsitent behavior depending on whether they were boxed:

```
1L.asInstanceOf[Int]        // -> 1
(1L: Any).asInstanceOf[Int] // -> ClassCastException
```

This PR fixes this by deprecating casts for conversion. I.e. in future scala versions, both calls will fail (although the first at compile time).

PR #3294 contains some discussion why this version might be desirable above the other.

After checkfile update to accomodate deprecation warnings, all partests succeed. However, run/t7868 does now emit a deprecation warning due to the code generated by the pattern matcher (no difference in matching behaviour is observed). If we proceed with this option, this warning will have to be fixed in the pattern matcher.

**UPDATE** This does not deprecate casts from `null` to a value type.

### CODE REVIEW

**Comment by paulp** [comment]
See https://issues.scala-lang.org/browse/SI-4437 for previous rejected attempt to do the same. There might be more test case material there too.

**Comment by soc** [comment]
Imho, deprecating conversions with casts is not the right way to go. Especially in generic contexts, you often don't have the `toX` methods available. Additionally, as far as I see the check is shallow by design and as soon as one uses it with generics the deprecation doesn't work anyway.

**Comment by gzm0** [comment]
Currently, the _conversion_ doesn't work with generics anyway (unless you specialize them):

```
scala> def foo[T](x: T) = x.asInstanceOf[Int]
foo: [T](x: T)Int

scala> foo(1L)
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer

scala> foo(1)
res1: Int = 1
```

So currently, the conversion _only_ works when the types are primitive at runtime. The compiler even translates this in a `toX` method (see [`numericConversion`](https://github.com/gzm0/scala/blob/aad291610628d365738bc00495aa1c8a6762038e/src/compiler/scala/tools/nsc/transform/Erasure.scala#L39)), so you certainly do have it available in situations where the conversion currently works.

If we want to make the conversion happen in the boxed case, unboxing requires an additional `instanceof` check due to the fact that we have to check for `Character` as well (see PR #3294).

I'll try to illustrate all possible cases, how they currently and what we could do:

Cast from:
- Primitive numeric type (PNT):
  - Represented as box
  - Represented as primitive
- Other type (uninteresting)

Cast to:
- Statically known primitive numeric type (Stat PNT)
- Other type (OT), potentially PNT but unknown at compile time

What's happening:

| From | To | Comment | Current | PR #3294 | PR #3295 |
| --- | --- | --- | --- | --- | --- |
| PNT Box | Stat PNT | Cast as box | No Conversion | Conversion | No Conversion |
| PNT Box | OT | Cast as box | No Conversion | Conversion | No Conversion |
| PNT Primitive | Stat PNT | Cast as primitive | Conversion | Conversion | No Conversion |
| PNT Primitive | OT | Cast as box | No Conversion | Conversion | No Conversion |

So only in the case where both types are known statically a conversion actually happens. This makes proper deprecation easy:
1. We can always emit a warning
2. It is trivial to replace the call with a `toX` in the code (again, the compiler already does that)

**Comment by soc** [comment]
@gzm0 Sorry, I wasn't really precise. I had a scenario in mind where both value and cast are generic. See https://issues.scala-lang.org/browse/SI-5866 vs. https://issues.scala-lang.org/browse/SI-8097 for a related issue where putting band-aid around the simple cases is easy, but fixing the issue for good is hard/expensive.

**Comment by gzm0** [comment]
@soc I see that this is an issue when casting `null`. I have been looking into this, and it seems indeed hard to get rid of it at this stage (you may also want to look at [SI-4437](https://issues.scala-lang.org/browse/SI-4437)). I am not proposing in this PR to disallow casts from `null` to a value type. This is only about casting from value types to value types (`null.asInstanceOf[Int]` does not emit a deprecation warning)

In a fully generic context, or when the target type is generic, boxing happens anyway (and the cast therefore currently fails):

```
scala> def foo[T](x: Int) = x.asInstanceOf[T]
foo: [T](x: Int)T

scala> foo[Long](1)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

scala> def bar[T,U](x: T) = x.asInstanceOf[U]
bar: [T, U](x: T)U

scala> bar[Int,Long](1)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
```

**Comment by gkossakowski** [comment]
I had a first pass over both PRs and I need some time to do more research and think about it. I'll be back soon.

**Comment by Ichoran** [comment]
Keep this in mind:

scala> def zero[@specialized Z] = { var z: Z = _; z }
<console>:7: error: local variables must be initialized
       def zero[@specialized Z] = { var z: Z = _; z }

scala> def zero[@specialized Z] = { var z: Z = null.asInstanceOf[Z]; z }
zero: [Z]=> Z

scala> zero[Boolean]
res0: Boolean = false

How do you do this if you deprecate the behavior?  (On the other hand, you don't want the runtime version to work; casts are supposed to declare that one thing is another, not make it so, typically.)

**Comment by gzm0** [comment]
@Ichoran both PRs do not alter casts of the form

```
null.asInstanceOf[Int]
```

so your example will still be allowed.

(although personally I would prefer having something like `Predef.zeroOf[T]` / `Predef.defaultOf[T]`)

**Comment by soc** [comment]
@Ichoran I have basically the same feeling. `asInstanceOf` is basically some kind of runtime low-level operation. We should not try to layer our own idea of what is allowed on top of a construct which basically means "go away, I know what I do".

@gzm0 I have thought about something like `defaultOf`, but as far as I see it, we can't make it work for value types. Until we can solve this, I prefer to "misuse" `asInstanceOf` because everyone is aware of the dangers of it.

**Comment by Ichoran** [comment]
@gzm0 - I meant not that your PR did away with `null.asInstanceOf[Int]`, but that this is exactly in the style of `1L.asInstanceOf[Int]`.  Taking this PR to its logical conclusion _would_ do away with `null.asInstanceOf[Int]`.  I prefer the status quo than a change that does not actually increase simplicity since there is an equally non-simple special case that is left behind and which we can't easily remove without losing an important capability.

@soc - There's also the issue of not wanting to introduce more reserved words, even if the existing word isn't the best fit.

**Comment by gzm0** [comment]
About `defaultOf`: I haven't thought about the thorough details of how this could be implemented. However, for value types, don't either of the following two always hold:
1. We know the runtime type at compile time (unboxed representation)
2. We don't know the exact type and the value is boxed

In the first case, we can simply calculate the default. In the second case, we can substitute with `null` and defer default calculation until unboxing. The huge difference IMHO is that the `null` is not apparent to the programmer.

@Ichoran I agree that disallowing `null.asInstanceOf[Int]` is the logical conclusion if this PR is merged (and I would like to do that, but see that it is extremely hard to transition safely to such a thing). However, the current situation is even worse, as the casts disallowed by this PR only work when a value type is not boxed (which is something that should be transparent to the programmer). In that sense `asInstanceOf` is broken, since its behavior cannot be accurately specified. With this PR (or #3294), `asInstanceOf` might have unintuitive behavior, but at least specifiable behavior.

**Comment by odersky** [comment]
I think restricting the language here is not what we want. It will make programs fail and cause people to spend time on something that worked now.

I'd much rather have both casts succeed than both casts being outlawed.

It seems we can do this only with one additional isInstanceOf tests. This is OK, but only as long as the extra test only affects explicit casts, and leaves implicit casts inserted by unboxing conversions alone. It would be inacceptable to make boxing conversions more expensive than they are now.

**Comment by adriaanm** [comment]
Closing this PR and continuing the discussion over at #3294

**Pull request closed without merging**
