### PR TITLE
Configure OSGI bnd tool for reproducible builds 

### PR DESCRIPTION
**Pull request by retronym**
We already set use the Git timestamp for the OSGi version number,
but we were still getting diffs in the META-INF/MANIFEST.MF
file in the `Bnd-LastModified` header.

This commit sets the REPRODUCIBLE flag to tell the OGSi bundler tool
to omit that header and ensure that the current timestamp does not
leak into other Zip entry metadata.

Together with the upgrade to SBT 1.5.x this seems to make the
resulting JARs successively builds from a given commit identical.

TODO: 
  - [x] Compare the OSGi metadata generated by the new version of BND vs the status quo.
  - [x] Update the outdated comment about in `project/Osgi.scala` about why we don't use sbt-osgi

### CODE REVIEW

**Comment by retronym** [comment]
Inspired by @raboof / https://github.com/raboof/sbt-reproducible-builds, although we seem to be able to achieve the result without needing to do use that plugin in a post-processing step.

**Comment by retronym** [comment]
There are real differences (problems, I think) in the new OSGi metadata.

```
$ sbt -Dscala.build.bndlib.version=2.4.1 setupPublishCore publishLocal &&  rm -rf /tmp/baseline/* && cp -R $(find build target  -name pack -o -name '*.pom') /tmp baseline
$ sbt setupPublishCore publishLocal &&  rm -rf /tmp/updated1/* && cp -R $(find build target  -name pack -o -name '*.pom') /tmp updated1
```

Extracting the manifests and normalizing whitespace (`s/\n\s//`, `s/;/;\n/`), then diffing:

https://gist.github.com/retronym/48a56b850644aaa731139b7b5446d350/revisions

```diff
commit b770163e056c26a9774ffd9eb303de0ff47b418c
Author: Jason Zaugg <jzaugg@gmail.com>
Date:   Sat Jul 3 16:24:26 2021 +1000

diff --git a/scala-compiler.jar-META-INF-MANIFEST.MF b/scala-compiler.jar-META-INF-MANIFEST.MF
index 62b8416..a0ee817 100644
--- a/scala-compiler.jar-META-INF-MANIFEST.MF
+++ b/scala-compiler.jar-META-INF-MANIFEST.MF
@@ -2,7 +2,6 @@
 +++ MANIFEST.MF
 Manifest-Version: 1.0
 Automatic-Module-Name: scala.tools.nsc
-Bnd-LastModified: 1625292864677
 Bundle-ManifestVersion: 2
 Bundle-Name: Scala Compiler
 Bundle-RequiredExecutionEnvironment: JavaSE-1.8
@@ -10,15 +9,7 @@ Bundle-SymbolicName: org.scala-lang.scala-compiler
 Bundle-Version: 2.12.15.v20210703-050957-52d9dbd
 Class-Path: scala-reflect.jar scala-library.jar
 Created-By: 1.8.0_272 (AdoptOpenJDK)
-Export-Package: LICENSE;
-version="2.12.15.v20210703-050957-52d9dbd",NOTICE;
-version="2.12.15.v20210703-050957-52d9dbd",compiler.properties;
-version="2.12.15.v20210703-050957-52d9dbd",jquery.min.js;
-version="2.12.15.v20210703-050957-52d9dbd",jquery.slim.min.js;
-version="2.12.15.v20210703-050957-52d9dbd",rootdoc.txt;
-version="2.12.15.v20210703-050957-52d9dbd",scala-asm.properties;
-version="2.12.15.v20210703-050957-52d9dbd",scala-buildcharacter.properties;
-version="2.12.15.v20210703-050957-52d9dbd",scala.reflect.macros.compiler;
+Export-Package: scala.reflect.macros.compiler;
 version="2.12.15.v20210703-050957-52d9dbd";
 uses:="scala,scala.collection,scala.collection.immutable,scala.collection.mutable,scala.reflect,scala.reflect.internal,scala.reflect.internal.tpe,scala.reflect.internal.util,scala.reflect.macros.util,scala.runtime,scala.tools.nsc,scala.tools.nsc.typechecker,scala.util",scala.reflect.macros.contexts;
 version="2.12.15.v20210703-050957-52d9dbd";
@@ -193,18 +184,80 @@ version="[2.12,2.13)",scala.reflect.internal.util;
 version="[2.12,2.13)",scala.reflect.io;
 version="[2.12,2.13)",scala.reflect.macros;
 version="[2.12,2.13)",scala.reflect.macros.blackbox;
+version="[2.12,2.13)",scala.reflect.macros.compiler;
+version="[2.12,2.13)",scala.reflect.macros.contexts;
+version="[2.12,2.13)",scala.reflect.macros.runtime;
+version="[2.12,2.13)",scala.reflect.macros.util;
 version="[2.12,2.13)",scala.reflect.macros.whitebox;
+version="[2.12,2.13)",scala.reflect.quasiquotes;
+version="[2.12,2.13)",scala.reflect.reify;
+version="[2.12,2.13)",scala.reflect.reify.codegen;
+version="[2.12,2.13)",scala.reflect.reify.phases;
+version="[2.12,2.13)",scala.reflect.reify.utils;
 version="[2.12,2.13)",scala.reflect.runtime;
 version="[2.12,2.13)",scala.runtime;
 version="[2.12,2.13)",scala.runtime.java8;
 version="[2.12,2.13)",scala.sys;
 version="[2.12,2.13)",scala.sys.process;
 version="[2.12,2.13)",scala.text;
+version="[2.12,2.13)",scala.tools.ant;
+version="[2.12,2.13)",scala.tools.asm;
+version="[2.12,2.13)",scala.tools.asm.commons;
+version="[2.12,2.13)",scala.tools.asm.signature;
+version="[2.12,2.13)",scala.tools.asm.tree;
+version="[2.12,2.13)",scala.tools.asm.tree.analysis;
+version="[2.12,2.13)",scala.tools.asm.util;
+version="[2.12,2.13)",scala.tools.cmd;
+version="[2.12,2.13)",scala.tools.fusesource_embedded.hawtjni.runtime;
+version="[2.12,2.13)",scala.tools.fusesource_embedded.jansi;
+version="[2.12,2.13)",scala.tools.fusesource_embedded.jansi.internal;
+version="[2.12,2.13)",scala.tools.jline_embedded;
+version="[2.12,2.13)",scala.tools.jline_embedded.console;
+version="[2.12,2.13)",scala.tools.jline_embedded.console.completer;
+version="[2.12,2.13)",scala.tools.jline_embedded.console.history;
+version="[2.12,2.13)",scala.tools.jline_embedded.internal;
+version="[2.12,2.13)",scala.tools.nsc;
+version="[2.12,2.13)",scala.tools.nsc.ast;
+version="[2.12,2.13)",scala.tools.nsc.ast.parser;
+version="[2.12,2.13)",scala.tools.nsc.ast.parser.xml;
+version="[2.12,2.13)",scala.tools.nsc.backend;
+version="[2.12,2.13)",scala.tools.nsc.backend.jvm;
+version="[2.12,2.13)",scala.tools.nsc.backend.jvm.analysis;
+version="[2.12,2.13)",scala.tools.nsc.backend.jvm.opt;
+version="[2.12,2.13)",scala.tools.nsc.classpath;
+version="[2.12,2.13)",scala.tools.nsc.doc;
+version="[2.12,2.13)",scala.tools.nsc.doc.base;
+version="[2.12,2.13)",scala.tools.nsc.doc.base.comment;
+version="[2.12,2.13)",scala.tools.nsc.doc.doclet;
+version="[2.12,2.13)",scala.tools.nsc.doc.html;
+version="[2.12,2.13)",scala.tools.nsc.doc.html.page;
+version="[2.12,2.13)",scala.tools.nsc.doc.html.page.diagram;
+version="[2.12,2.13)",scala.tools.nsc.doc.model;
+version="[2.12,2.13)",scala.tools.nsc.doc.model.diagram;
+version="[2.12,2.13)",scala.tools.nsc.interactive;
+version="[2.12,2.13)",scala.tools.nsc.interactive.tests.core;
+version="[2.12,2.13)",scala.tools.nsc.interpreter;
+version="[2.12,2.13)",scala.tools.nsc.interpreter.session;
+version="[2.12,2.13)",scala.tools.nsc.io;
+version="[2.12,2.13)",scala.tools.nsc.javac;
+version="[2.12,2.13)",scala.tools.nsc.plugins;
+version="[2.12,2.13)",scala.tools.nsc.profile;
+version="[2.12,2.13)",scala.tools.nsc.reporters;
+version="[2.12,2.13)",scala.tools.nsc.settings;
+version="[2.12,2.13)",scala.tools.nsc.symtab;
+version="[2.12,2.13)",scala.tools.nsc.symtab.classfile;
+version="[2.12,2.13)",scala.tools.nsc.transform;
+version="[2.12,2.13)",scala.tools.nsc.transform.async;
+version="[2.12,2.13)",scala.tools.nsc.transform.patmat;
+version="[2.12,2.13)",scala.tools.nsc.typechecker;
+version="[2.12,2.13)",scala.tools.nsc.util;
+version="[2.12,2.13)",scala.tools.reflect;
+version="[2.12,2.13)",scala.tools.util;
 version="[2.12,2.13)",scala.util;
 version="[2.12,2.13)",scala.util.control;
 version="[2.12,2.13)",scala.util.hashing;
 version="[2.12,2.13)",scala.util.matching;
-version="[2.12,2.13)",javax.management,javax.management.openmbean,javax.script,javax.swing,javax.swing.border,javax.swing.event,javax.swing.tree,javax.tools,javax.xml.parsers,org.w3c.dom
+version="[2.12,2.13)",com.cloudius.util,com.sun.management,javax.management,javax.management.openmbean,javax.script,javax.swing,javax.swing.border,javax.swing.event,javax.swing.tree,javax.tools,javax.xml.parsers,org.w3c.dom,sun.misc
 Require-Capability: osgi.ee;
 filter:="(&(osgi.ee=JavaSE)(version=1.8))"
-Tool: Bnd-2.4.1.201501161923
+Tool: Bnd-5.3.0.202102221516
\ No newline at end of file

```

**Comment by raboof** [comment]
> Inspired by @raboof / https://github.com/raboof/sbt-reproducible-builds

:heart: 

> although we seem to be able to achieve the result without needing to do use that plugin in a post-processing step.

That's great! indeed the post-processing is meant to be a temporary measure until those can be solved upstream - I haven't checked in a while whether some (or all) of them can be dropped already. Great to hear you can already get there without it!

**Comment by retronym** [comment]
First and subsequent build with this PR are byte-for-byte identical. Timestamps of generated JARs themselves differ but that's okay, we only care about stray timestamps inside Zip/JARs.

```
$ for i in in 1 2; do sbt clean setupPublishCoreNonOpt dist/mkPack && cp -R ./build/pack /tmp/scala-pack-$i; done
...
$ find /tmp/scala-pack-{1,2}
/tmp/scala-pack-1
/tmp/scala-pack-1/bin
/tmp/scala-pack-1/bin/scalac.bat
/tmp/scala-pack-1/bin/fsc.bat
/tmp/scala-pack-1/bin/scaladoc
/tmp/scala-pack-1/bin/scalap.bat
/tmp/scala-pack-1/bin/scaladoc.bat
/tmp/scala-pack-1/bin/scalac
/tmp/scala-pack-1/bin/fsc
/tmp/scala-pack-1/bin/scalap
/tmp/scala-pack-1/bin/scala.bat
/tmp/scala-pack-1/bin/scala
/tmp/scala-pack-1/lib
/tmp/scala-pack-1/lib/scala-repl-jline.jar
/tmp/scala-pack-1/lib/scala-library.jar
/tmp/scala-pack-1/lib/scala-compiler.jar
/tmp/scala-pack-1/lib/scala-swing_2.12-2.0.3.jar
/tmp/scala-pack-1/lib/scala-compiler-doc.jar
/tmp/scala-pack-1/lib/scala-partest.jar
/tmp/scala-pack-1/lib/jline.jar
/tmp/scala-pack-1/lib/scala-repl-jline-embedded.jar
/tmp/scala-pack-1/lib/scala-reflect.jar
/tmp/scala-pack-1/lib/scalap.jar
/tmp/scala-pack-1/lib/scala-xml_2.12-1.0.6.jar
/tmp/scala-pack-2
/tmp/scala-pack-2/bin
/tmp/scala-pack-2/bin/scalac.bat
/tmp/scala-pack-2/bin/fsc.bat
/tmp/scala-pack-2/bin/scaladoc
/tmp/scala-pack-2/bin/scalap.bat
/tmp/scala-pack-2/bin/scaladoc.bat
/tmp/scala-pack-2/bin/scalac
/tmp/scala-pack-2/bin/fsc
/tmp/scala-pack-2/bin/scalap
/tmp/scala-pack-2/bin/scala.bat
/tmp/scala-pack-2/bin/scala
/tmp/scala-pack-2/lib
/tmp/scala-pack-2/lib/scala-repl-jline.jar
/tmp/scala-pack-2/lib/scala-library.jar
/tmp/scala-pack-2/lib/scala-compiler.jar
/tmp/scala-pack-2/lib/scala-swing_2.12-2.0.3.jar
/tmp/scala-pack-2/lib/scala-compiler-doc.jar
/tmp/scala-pack-2/lib/scala-partest.jar
/tmp/scala-pack-2/lib/jline.jar
/tmp/scala-pack-2/lib/scala-repl-jline-embedded.jar
/tmp/scala-pack-2/lib/scala-reflect.jar
/tmp/scala-pack-2/lib/scalap.jar
/tmp/scala-pack-2/lib/scala-xml_2.12-1.0.6.jar
$ diff -r /tmp/scala-pack-{1,2}
$ 
```

**Comment by retronym** [comment]
Rechecked this vs the baseline of origin/2.12.x. Again, after normalizing whitespace and the version numbers, the only material diff looks like a true progression:

image

image

image

**Review by lrytz — APPROVED** [review]
Courageous to touch OSGi :-)

**Pull request merged**
