### PR TITLE
comment / question in typers

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by jsuereth** [comment]
review by?

**Comment by lrytz** [comment]
rebased on current master so that the test doesn't fail. review by @jsuereth or whoever merges it, it's really trivial.

**Comment by jsuereth** [comment]
My question is:  SHould this question be asked elsewhere?

**Comment by lrytz** [comment]
ideally, yes, i guess. it's a question of time: i was not about to change anything there, that would require to look at things more profoundly. i was just looking at the code and stumbled on this surprising bit. so i added a comment for the next guy to save some time.

**Comment by lrytz** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
OK. LGTM

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Pull request merged**
