### PR TITLE
SI-6811 Split scala.util.parsing and move it to its own jar

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by adriaanm** [comment]
Close! Looks like all you need is some more copy/pasting to add a strap.parsing target and have the strap.comp depend on it.

**Comment by soc** [comment]
I'll look into it shortly, I'm still fighting my paulp withdrawal symptoms.
Never thought harder about what I want to work on for the rest of my life. Or wherever such a single thing even exists.

**Comment by soc** [comment]
Review by @adriaanm, @gkossakowski please.
One remaining question is whether `scala-parsing.jar` is a good name for the jar file. It feels like the name makes it look more important than it is. Should we look for a better name, maybe something like `scala-parsercombinators.jar`?

**Comment by paulp** [comment]
+1 on different name. (Or +0.4 or whatever's left.)

**Comment by gkossakowski** [comment]
Yes, I think `scala-parsing-combinators.jar` is better name. Our parsing combinators is not general purpose parsing library (e.g. for performance reasons) and the name should clearly suggest that.

**Comment by soc** [comment]
@gkossakowski `parsING-combinators`? What's the difference in meaning compared  to `parsER-combinators`?

**Comment by som-snytt** [comment]
:+1:  parsing `parsing` vs `parser` :)  Sein oder Seindes, ontic, ontological.

**Comment by soc** [comment]
Yes, but what point are we trying to make? Searching for “parsing combinators” gives ~3 times the results of “parser combinators”, but Scala is using “parser combinators” consistently everywhere (except the package name).
I have not much of an opinion here, I just try to understand the reasoning.

**Comment by soc** [comment]
@adriaanm, @paulp, @som-snytt, @gkossakowski: More opinions on parser vs. parsing?

**Comment by adriaanm** [comment]
I vote for scala-parser-combinators.jar

or scala-parsec
or scala-parser-combo
or scala-parslow

**Comment by som-snytt** [comment]
Apparently, you'll have to deprecate `scala.util.parsing`, rename it to `parser` in 2.12, and then split off into scala-parser-...jar after that.  I do hope you use the second hyphen when that happens.

**Comment by adriaanm** [comment]
Can't we get away with naming the jar something sensible and shipping it with the distribution, so we don't need to deprecate. It's still there!

**Comment by gkossakowski** [comment]
@adriaanm: I don't follow your last argument. Can you elaborate?

**Comment by som-snytt** [comment]
> I vote for scala-parser-combinators.jar
> +1

@adriaanm sorry for being jokey about deprecation.  I should know better, since I learned the religious root of the word.  I'm getting harassed by mima on an unrelated matter, and I was letting off some steam.

**Comment by adriaanm** [comment]
I'm working on a version where the compiler doesn't depend on the parser combinators, reusing your build fixes -- thanks!. Closing this one.

**Pull request closed without merging**
