### PR TITLE
SI-9406 fix doc for Range.takeRight

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @dickwall

**Comment by soc** [comment]
Not @dickwall, but LGTM.

**Comment by dickwall** [comment]
Can't see how this could have broken anything, but let's try a /rebuild anyway

**Comment by SethTisue** [comment]
(I don't think it's enough to just say "/rebuild" somewhere in a comment, it has to be a comment in itself.)

**Comment by SethTisue** [comment]
sigh. failed again. investigating

**Comment by SethTisue** [comment]
My old commit had the totally wrong parent. Not sure how I managed that. New commit should be good.

**Comment by SethTisue** [comment]
hah, I know how I managed it. unlike the upstream repo, my fork of the scala repo still had a `master` branch, so when I accidentally did `git checkout master && git checkout -b issue/9406` instead of `git checkout 2.11.x && git checkout -b issue/9406`, I didn't get an error. now fixed so the same mistake again won't be possible (deleted the master branch from my fork and made 2.11.x default)

**Comment by dickwall** [comment]
Seth Tisue, in case I forget to say it again, you're my hero.

**Comment by SethTisue** [comment]
wait until I commit a TWO line fix before I become your hero :-)

**Pull request merged**
