### PR TITLE
SI-6913 Reapplies a lost fix by @viktorklang

### PR DESCRIPTION
**Pull request by heathermiller**
https://issues.scala-lang.org/browse/SI-6913

This somehow got lost. Thanks to @rkuhn for pointing it out. 
https://groups.google.com/forum/#!topic/scala-internals/X1bgCpINb60

### CODE REVIEW

**Comment by retronym** [comment]
Could you please flesh out the commit message? In particular, the commit title should summarize the functional change, not the author that lost it :)

https://github.com/viktorklang/scala/commit/1bbe8545562762d12942a2eb59257f0429e9868a

**Comment by heathermiller** [comment]
Done

**Comment by heathermiller** [comment]
Btw, I'm not sure how this got lost. As far as I understand, other commits were pulled in from the same PR. :-/

**Comment by phaller** [comment]
Thanks!

**Comment by retronym** [comment]
@adriaanm The 2.10.x branch has a different failure mode for `pr-scala-integrate-ide`: 

Should we just ignore that build until it is restabilized?

https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4216/console

```
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      ::          UNRESOLVED DEPENDENCIES         ::
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      :: org.scala-lang#scala-actors;2.10.4-ba88410-SNAPSHOT: not found
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] java.lang.RuntimeException: Ivy resolution failure
``
```

**Comment by adriaanm** [comment]
That failure was due to trying out a new proposed version of the IDE build.
I since switched back to the working build but forgot to rebuild this PR.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Could be spurious -- not sure:

```
  [partest] java.lang.AssertionError: assertion failed
  [partest]     at scala.Predef$.assert(Predef.scala:165)
  [partest]     at TestBase$class.once(scala-concurrent-tck.scala:25)
  [partest]     at Test$.once(scala-concurrent-tck.scala:767)
  [partest]     at FutureCombinators$class.testFallbackToFailure(scala-concurrent-tck.scala:344)
  [partest]     at Test$.testFallbackToFailure(scala-concurrent-tck.scala:767)
  [partest]     at FutureCombinators$class.$init$(scala-concurrent-tck.scala:373)
  [partest] testing: [...]/files/jvm/scala-concurrent-tck.scala                   [FAILED]
```

**Comment by phaller** [comment]
It doesn't seem to be spurious. As far as I can see `testFallbackToFailure` is testing the wrong/old behavior.

**Comment by adriaanm** [comment]
Ping @phaller  -- the RC1 deadline is coming up.

**Comment by phaller** [comment]
PLS REBUILD ALL

**Comment by phaller** [comment]
LGTM

**Comment by phaller** [comment]
Ping @JamesIry -- good for merge?

**Pull request merged**
