### PR TITLE
Significant improvements to make-release-notes script

### PR DESCRIPTION
**Pull request by jsuereth**
Specifically, it should generate exactly the HTML Toni needs for the website.

Review by @lrytz and/or @cunei

### CODE REVIEW

**Comment by lrytz** [comment]
i guess the merge from master should not be in this pull request (the first commit)

**Comment by jsuereth** [comment]
Most likely not, let me squash it.

**Comment by lrytz** [comment]
oh i see now that the pr is against master, then it's not a big deal.

**Comment by jsuereth** [comment]
AND, I'm dumb.  Accidentally pushed to origin rather than jsuereth.   I need to use convention when setting up my local repos....  In any case, if you're against it let me know and I'll revert.

**Comment by lrytz** [comment]
oh i see, so it's already in master :) it looks good to me anyway - but also ask toni.

yeah, having permission to push to scala/scala comes with drawbacks.. better chose a very clear name for that remote.

**Pull request merged**
