### PR TITLE
SI-7683 Enable -Ystop-before:typer

### PR DESCRIPTION
**Pull request by som-snytt**
Allows a plugin to run before typer without incurring typechecking.

The test is that a plugin doesn't run when stopping after parser,
and that the truncated compilation run also succeeds, since
updating check files for the output of -Xshow-phases is tedious.

### CODE REVIEW

**Comment by lrytz** [comment]
ping @som-snytt to rename that parameter :)

**Comment by som-snytt** [comment]
That's really pushing the Boy Scout rule.  I think you have to finish abide complaining about legacy comments and params to local defs. @lrytz

**Comment by lrytz** [comment]
Allright, Scouts also need to move on eventually, otherwise they're stuck forever helping people cross that same intersection :)

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
