### PR TITLE
Restarr on 2.13.0

### PR DESCRIPTION
**Pull request by lrytz**
First! 🙂

Also removing the mima-filters file for reflect - it seems easier to handle excludes in build.sbt - or did I miss something?

### CODE REVIEW

**Comment by ashawley** [comment]
The filter files were added to 2.12 in #6006, so @2m may be a good person to ask.

**Comment by dwijnand** [comment]
There are pros and cons.  One of the pros for the external files is that you can add to them and you don't have to reload the build.

I feel MiMa filters are so rare in Scala (once stable) that it doesn't matter much, no?

**Comment by 2m** [comment]
Keeping filters in files automatically versions them. So it is not necessary to remove filters after a new version is released. That also means, when a new version gets released, its BC filter list becomes empty automatically, which is not the case, if the filter list is kept static in the build file.

Generally I find it less of a maintenance burden to keep filters in files. This was also the motivation behind introducing them while developing Akka, as filter lists become quite large over there.

**Comment by dwijnand** [comment]
> That also means, when a new version gets released, its BC filter list becomes empty automatically

Yeah, that's the downside I've found: I need to copy the X filters I had in `x.y.0.backwards.excludes` in the `x.y.1.backwards.excludes` file (etc for each new version).

**Comment by SethTisue** [comment]
and in this repo bincompat only resets every 2 years, so we practically never benefit from "BC filter list becomes empty automatically"

**Review by ashawley — APPROVED** [review]

**Review by dwijnand — APPROVED** [review]

**Comment by 2m** [comment]
> Yeah, that's the downside I've found.

For me it is usually an upside apart for the filters for classes that are allowed to break binary compatibility (for example in the `impl` package). But those kind of filters, should be placed in, for example, `2.13.x.backwards.excludes` file. Note that `x` here will make sure to apply these fitlers for every patch version.

**Comment by dwijnand** [comment]
> Note that `x` here will make sure to apply these fitlers for every patch version.

TIL!

**Comment by SethTisue** [comment]
the nightly that was built for this PR was `2.13.0-pre-0b8a538`, it should have been `2.13.0-bin-0b8a538`, apparently some further change is needed

**Comment by SethTisue** [comment]
I found the logic for this:

```
    def cross = base match {
      case Patch(p) if p.toInt > 0 => "bin"
      case _ => "pre"                                                                                                                                        
    }
```

we need to move the version number to 2.13.1. I'll PR it

**Pull request merged**
