### PR TITLE
SI-8210 Scaladoc: Fix @inheritdoc warning on accessors

### PR DESCRIPTION
**Pull request by kzys**
This fix is just for the false positive warning. Probably we can skip
setters, but I'm not entirely sure.

### CODE REVIEW

**Comment by kzys** [comment]
s/the false positive warning/the false negative warning/. I've fixed the commit message.

**Comment by lrytz** [comment]
Hi @kzys, the change looks good, but it should go in the 2.11.x branch. Can you submit a new PR for this?

Our current workflow: all changes that are binary compatible go into the 2.11.x branch for now. From time to time we merge the 2.11.x branch into 2.12.x ([example here](https://github.com/scala/scala/pull/4424)), so you don't need to do anything else to get your bugfix into 2.12.

**Comment by adriaanm** [comment]
Closing this PR, since it will be subsumed by the 2.11 PR.

**Comment by kzys** [comment]
Sorry for the late reply and ignoring the workflow. I've just opened #4531.

**Pull request closed without merging**
