### PR TITLE
better unreachability for selections

### PR DESCRIPTION
**Pull request by adriaanm**
Consts are hashconsed modulo static-approximation-for-dynamic-value-equality
thus, two value-equality tests in patterns should reuse the same ValueConst
if and only if the tested values are guaranteed to be equal in all possible executions

the implementation uses unique types to track unique consts
for an Ident with a stable symbol, we simply use the corresponding singleton type
for a Select, we have to indirect some more: we store all the unique trees we've encountered and a unique type for each of them; this unique type is then used to find the unique const that approximates the run-time value

this may seem roundabout, but we need to standardize on types for representing "value" tests,
since a type test against a singleton type must give rise to the same ValueConst
as a value test using a tree that refers to the same symbol as the singleton type test
(also, it's easier to go from values to types than vice versa)

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @retronym or @gkossakowski please

**Comment by retronym** [comment]
How about this case?

``` scala
import WARNING._

(0: Int) match {
  case WARNING.id =>
  case INFO.id => // reachable
  case id => // unreachable?
}
```

**Comment by adriaanm** [comment]
Restarted build at: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/253/
(after equalsStructure0 -> correspondsStructure)

**Comment by adriaanm** [comment]
the trees have to have the same structure, otherwise it won't work (in the current impl)
if your example turns out to be common, we should improve the analysis, otherwise I think it's fine like this

**Comment by retronym** [comment]
In that case, LGTM.

**Comment by adriaanm** [comment]
build successful: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/253/console

**Comment by adriaanm** [comment]
this should fix the spurious error in the eclipse build, @dragos

**Pull request merged**
