### PR TITLE
SI-5959 type equality now accounts for mirrors

### PR DESCRIPTION
**Pull request by xeno-by**
TypeRef(ThisType(<package1>), sym, args) should always be equal to
TypeRef(ThisType(<package2>), sym, args) regardless of whether
package1 and package2 actually represent the same symbols of not.

Same goes for subtyping (<:<) and type equality (=:=).

This is done to account for the fact that mirrors share normal symbols,
but never share package symbols. Therefore at times it will occur that
the same types loaded by different mirrors appear different because of
the package symbols. More details: https://issues.scala-lang.org/browse/SI-5959.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @odersky, @adriaanm.

please, also see the discussion at http://groups.google.com/group/scala-internals/browse_thread/thread/4bef4e6987bb68fe.

**Comment by adriaanm** [comment]
couldn't you distinguish these last two TypeRefs by matching on them?
"alias to Int" and Int will be different symbols, and == will allow you to see the difference between the different prefixes

**Comment by odersky** [comment]
We just have to document that == is not =:= and that =:= is what Scala considers to be type equality. It's pretty obvious, really, that AnyRef != Object, yet nevertheless AnyRef =:= Object. There's a fundamental difference between the two comparisons.

**Comment by xeno-by** [comment]
I'm not sure how intuitive this will be for reflection users... Also, it will definitely be misleading, because sometimes == will work, and we cannot prohibit people from using it altogether.

**Comment by xeno-by** [comment]
@odersky okay, the whole =:= idea starts growing on me. I'll resubmit the pull request with the changes to equals and hashcode reverted

**Pull request closed without merging**
