### PR TITLE
SI-7848 Xlint no warn on $sym with params

### PR DESCRIPTION
**Pull request by som-snytt**
This idea brought to you by retronym.

Also improve implicitNotFound detection at typer;
and avoid checking the standard interpolation
expression for cases like s"some $$x".

Some minor refactorings of implicitNotFound strings.

The intersobralator allows extra spaces, i.e., trims.

(This merge faked me out somehow.  Here's to workflow. Looks like the earlier
commits were unchanged.)

### CODE REVIEW

**Comment by adriaanm** [comment]
Could you elaborate a bit on the idea in the commit message for future reference?

**Comment by som-snytt** [comment]
Not sure which you mean. "idea by zaugg" means "don't warn on $foo if foo is foo(args)."

By coincidence, zaugg also updated the implicitNotFound check.  I wanted to add some sensitivity to: um, it's already interpolated, so don't check anything (so, no need to detect "$$foo").  I noticed the implicitNotFound filter didn't do anything.

The better correction is to do this check in refchecks, but it turns out the context isn't correct for the case `s"some ${ "$foo is an arg" }" where for the foo string, context is the method, not the apply.

**Comment by som-snytt** [comment]
"idea by zaugg" sounds like a fashion label.

**Comment by adriaanm** [comment]
>  "don't warn on $foo if foo is foo(args)."

which warning? why not? what's the difference?

**Comment by som-snytt** [comment]
As they say on American tv, "Previously, on SI 7848," https://github.com/scala/scala/pull/2956, expecty elicited a warning on "$eq".  Our young hero exclaimed, "Avast! [this is a BBC period drama]," indicating that we can hold our fire if the sym requires args in a sensible application.

**Comment by paulp** [comment]
Oops, I independently did this on the plane taking the warning count down to zero. I'm glad to use yours though. LGTM. I completely agree with the heuristic - you can't write $foo(a, b, c) thinking string interpolation is going to work if you've ever used it.

**Comment by som-snytt** [comment]
Old, poetically just comment from this development effort:

D'oh is me!

My warning about a missing interpolator was missing its interpolator.

test/files/neg/t7848-interp-warn.scala:9: warning: looks like an interpolated expression! $suggest

**Comment by paulp** [comment]
Hah. Well I have a followup PR coming today anyway.

**Pull request merged**
