### PR TITLE
Nuance advice when var in multidef could be val

### LINKED ISSUE #7530: _Slightly_ inaccurate 'it could be a val' warning
Scala Migrations [1] has the following snippet in Migration.scala [2]

```scala
  private def indexNameFor(tableName: String,
                           columnNames: Array[String],
                           options: IndexOption*): (String, List[IndexOption]) = {
  ...
  }

  final def addIndex(tableName: String,
                     columnNames: Array[String],
                     options: IndexOption*) {
    if (columnNames.isEmpty) {
      throw new IllegalArgumentException("Adding an index requires at " +
        "least one column name.")
    }

    var (name, opts) = indexNameFor(tableName, columnNames, options: _*)

    var unique = false
    for (opt @ Unique <- opts) {
      opts = opts filter { _ ne opt }
      unique = true
    }
```

2.11.0 gives the following warning:

```scala
[warn] /var/lib/jenkins/tomcat7/jenkins/jobs/scala-migrations-gerrit/workspace/src/main/scala/com/imageworks/migration/Migration.scala:357: local var name in method addIndex is never set - it could be a val
[warn]     var (name, opts) = indexNameFor(tableName, columnNames, options: _*)
[warn]          ^
```

Since `opts` is modified, I cannot make the `var` a `val` without other changes, such as copying `opts` to `os` and then modifying that.

I don't know if this counts as a real bug, since it is correct, but the fix is more than what the warning suggests.  Maybe the warning text just needs to be tweaked.

[1] http://code.google.com/p/scala-migrations/
[2] https://github.com/imageworks/scala-migrations/blob/master/src/main/scala/com/imageworks/migration/Migration.scala

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#7530

### CODE REVIEW

**Review by joroKr21 — APPROVED** [review]
It's better but I wonder if this warning makes sense at all. Some people are sticklers for immutability, others don't like to repeat themselves.

**Comment by som-snytt** [comment]
I would be more likely to click on the "quickfix" button.
```
val (xs, i0) = init()
var i = i0
```
or even
```
var i: Int = uninitialized
val xs = { val (xs0, i0) = init(); i = i0; xs0 }
```
or wait
```
var i: Int = uninitialized
val xs = init().pipe { case (xs0, i0) => i = i0; xs0 }
```
People who would shrug will not enable the lint.

Application developers should not be using mutation. It's not that "casual users use var".

When Ichoran is writing his `while` loops, he will want the lint, because that's when you want extra clarity. "Imperative style is hard enough without forgetting which variables are mutable."

**Comment by joroKr21** [comment]
I would shrug 😄

**Comment by som-snytt** [comment]
🤷

**Review by lrytz — APPROVED** [review]
👍 thanks!

**Comment by som-snytt** [comment]
I see from a stale branch that my original intention was not to warn.

Comparable to `implicit val (x: Int, y: String) = (42, "hi")` where only one element is needed to be implicit.

**Pull request merged**
