### PR TITLE
Adds extractors for TypeName, TermName and Modifiers

### PR DESCRIPTION
**Pull request by densh**
This change allows to pattern match over type names, term names and
modifiers. Otherwise it can be quite painful to match over complex trees
as each name or modifiers requires a guard.

This pull request also changes the name of default constructor for term
and type names i.e. TypeName(s) instead of newTermName(s). This is
shorter to type, more consistent with the rest of reflection api and
consistent with the way it will be pattern matched later on.

### CODE REVIEW

**Comment by adriaanm** [comment]
relaying a comment from @paulp, we are striving to maintain binary compatibility for scala-reflect in 2.10.x (will publicize this on the mailing lists today) so this will need to be considered when reviewing this PR (it sounds like it won't be compatible and is thus better targeted at master)

**Comment by xeno-by** [comment]
As the comments indicate, this PR was designed from the ground up with binary compatibility in mind. In a nutshell it deprecates a couple of methods and introduces a few more + adds a couple of companion objects => looks totally binary compatible to me.

**Comment by paulp** [comment]
In brief, due to factors beyond our control, it isn't enough. "Totally binary compatible" means you cannot add methods at all. What you are describing is "backward binary compatible" (I think - maybe I'm swapping the terms) but it is likely we also have to produce forward compatibility. Elaboration will follow in the near future.

**Comment by xeno-by** [comment]
Forward compatibility would mean macro paradise will only be able to be merged in 2.11, because the first candidate for the paradise, type macros, require an additional API for macro context.

**Comment by paulp** [comment]
That's one of the issues which makes the entire situation intractable; we are attempting to articulate things so we can make a conscious decision about what has to give.

**Comment by adriaanm** [comment]
Based on our discussion on [scala-internals](https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/IApLHqVt-9M), this would need to be annotated @since, if we decide to drop forward compatibility. In the mean time, it probably makes more sense to merge this into macro-paradise.

**Pull request closed without merging**
