### PR TITLE
Repl prints '\n' as newline, not "^J"

### PR DESCRIPTION
**Pull request by adriaanm**
Work around a weird bug in JLine.
Fix https://github.com/scala/scala-dev/issues/240

### CODE REVIEW

**Comment by som-snytt** [comment]
Instead of `"""x^Jy^Jz""" // : String("x\ny\nz\n")`,

```
scala> """x
     | y
     | z""" //print
   """x
y
z""" // : String("x\ny\nz")
     | z""" //print
res4: String =
x
y
z
```

but I still get

```
That entry seems to have slain the compiler.  Shall I replay^Jyour session? I can re-run each line except the last one.^J[y/n]
```

which is the one you see more often...

**Comment by som-snytt** [comment]
That's fixed by:

```
@@ -106,7 +109,7 @@ private class JLineConsoleReader extends jconsole.ConsoleReader with interpreter
   }

   def readOneKey(prompt: String) = {
-    this.print(prompt)
+    this._rawPrint(prompt)
     this.flush()
     this.readCharacter()
   }
```

Since it's useful, maybe drop the "scare underscore" from `rawPrint`.

I'm not sure about `readLine(prompt)`.

**Comment by som-snytt** [comment]
I guess jline-native `readLine` is already OK:

```
$ scalam -Dscala.repl.prompt="Thursday        
hello> "
Welcome to Scala 2.12.0-RC1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_92).
Type in expressions for evaluation. Or try :help.
Thursday
hello> 42
res0: Int = 42
Thursday
hello> 
```

**Comment by adriaanm** [comment]
Thanks! I used `_rawPrint` more liberally, but sadly the non-scare-score name is not available due to name clash with the package protected "super" implementation...

**Comment by som-snytt** [comment]
LGTM

I would have understood the naming convention if I'd actually reviewed the code and read the comments.

I just re-encountered a one-liner I'd under-reviewed a few years ago. In fact, that recent movie is about a code review risen to wreak revenge, "The Revenant," which is French for "Review not."

"Review rot" must be when a review seems sufficient, but with the passage of time is shown to be full of holes.

**Comment by adriaanm** [comment]
Fixed upstream in jline 2.14.3: https://github.com/jline/jline2/commit/01969b55a356057eadd7a624fbb1e38222b05ffa

**Pull request merged**
