### PR TITLE
Remove () from iterator

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/collection-strawman/issues/520

### CODE REVIEW

**Comment by julienrf** [comment]
If this gets merged we should:
- update the [FAQ](https://github.com/scala/collection-strawman/wiki/FAQ) to always write `iterator` (without parens),
- close https://github.com/scala/scala-collection-compat/pull/7

**Comment by julienrf** [comment]
As mentioned here https://github.com/scala/collection-strawman/issues/520#issuecomment-388336449, we should also remove the parens to the `XxxFactory#newBuilder` operation. And probably to `IterableOps#newSpecificBuilder` as well (though this one didn’t exist in 2.12, so it’s not a problem to keep the parens, but we should just use the same convention everywhere…)

**Comment by lrytz** [comment]
I just did that, just need to push the changes

**Comment by sjrd** [comment]
Because of the change in `newBuilder` especially, we'll need this PR to land (and a -pre- to be built from it) before we can finalize changes in Scala.js, so the sooner it gets merged, the likelier it gets that Scala.js can be ready (almost) in time for the release.

**Review by julienrf — APPROVED** [review]

**Comment by sjrd** [comment]
@lrytz Hum for `newBuilder`, don't you also want to remove the `()` in [`IterableFactory.newBuilder[A]()`](https://github.com/scala/scala/blob/1a8fdb7048f609283989108f72c2d7e955c1c187/src/library/scala/collection/Factory.scala#L124) and all its implementations?

Also [`MapFactory.newBuilder[K, V]()`](https://github.com/scala/scala/blob/1a8fdb7048f609283989108f72c2d7e955c1c187/src/library/scala/collection/Factory.scala#L337).

**Comment by julienrf** [comment]
Good catch @sjrd. Indeed we should remove the `()` here too.

**Comment by lrytz** [comment]
I think I caught them all now. Also added a commit for `ArrayBuilder.make`.

**Comment by lrytz** [comment]
`ArrayBuilder.make` actually had `()` in 2.12, so this is a breaking change. https://github.com/scala/scala/blob/v2.12.6/src/library/scala/collection/mutable/ArrayBuilder.scala#L34

**Review by szeiger — APPROVED** [review]
I'm not a fan of adding another breaking change but it makes it consistent with the rest.

**Pull request merged**
