### PR TITLE
SI-7444 docs: null Executor is allowed in ExecutionContext factories

### PR DESCRIPTION
**Pull request by retronym**
Update the ScalaDoc for the factory methods for `ExecutionContext`
which allow a null `Executor`.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @huntc

**Comment by soc** [comment]
Shouldn't we come up with a better way of saying "I want a new Fork/Join based ExecutorService with default configuration" than passing `null` somewhere?

**Comment by retronym** [comment]
I agree the API is rather unidiomatic, but I'm only on a drive-by documentation run this time. Maybe @viktorklang remembers the rationale, was this to make this API Java accessible?

**Comment by huntc** [comment]
LGTM re. documenting existing behaviour. Thanks.

**Comment by viktorklang** [comment]
Personally I don't think we should state that it will be a Fork/Join ExecutorService, since all it returns is an ExecutorService.

If you want a ForkJoinPool with default configuration: `new ForkJoinPool()`

**Comment by retronym** [comment]
We document that already on `Implicits.global` which goes through the same code path. That's why I chose to be explicit about what you get here.

**Comment by viktorklang** [comment]
@retronym Then I suggest the opposite, removing that piece of documentation from Implicits.global. (Since it is not possible to view it as a FJP from the outside, it is not meaningful to depend on that as an implementation detail.) Do you agree?

**Comment by retronym** [comment]
I don't think it as cut and dried. I would think we need to say _something_ about what `Implicits.global` actually returns, even if it a bit weaselly to allow us to change the implementation later.

**Comment by viktorklang** [comment]
@retronym Perhaps a good middle ground is to describe the System Properties by which it can be controlled?

**Comment by retronym** [comment]
I agree the system properties that can configure the pool should be documented. But perhaps they should live in http://docs.scala-lang.org/overviews/core/futures.html, rather than inline in the Scaladoc.

I'm happy to remove `ForkJoin` here in favour of "a new ExecutorService will be created with default configuration`.

But first, ping @phaller, who crafted the commentary in question in: 26b77aca9498775968cc9138c7537dbfbc52e3fd

**Comment by phaller** [comment]
Here is my proposal: https://github.com/scala/scala/pull/4132

I agree with @viktorklang that we probably shouldn't mention `ForkJoin` explicitly here. Therefore, I've replaced my original doc comments on `Implicits.global` and `ExecutionContext.global`. However, I think @retronym has a good point that we should give _some_ indication of the nature of the created `ExecutionContext`.

My proposal for documenting `Implicits.global` and `ExecutionContext.global` is to simply say:

> The default `ExecutionContext` implementation is backed by a work-stealing thread pool.
> By default, the thread pool uses a target number of worker threads equal to the number of
> available processors.

To also fix the original SI-7444, I used @retronym's suggestion to simply remove `ForkJoin`, but I also turned "default configuration" into a link pointing to `ExecutionContext.global`.

WDYT?

**Comment by viktorklang** [comment]
@phaller We do need to be careful though, as we fall back to a TPE: https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/impl/ExecutionContextImpl.scala#L86

**Comment by phaller** [comment]
Also, of note, the "available processors" in the doc comment for `ExecutionContext.global` (and `Implicits.global`) is a link pointing to https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#availableProcessors--. This is analogous to how [java.util.concurrent.Executors.newWorkStealingPool()](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newWorkStealingPool--) is documented.

**Comment by phaller** [comment]
@viktorklang It would be good to document in which cases we're expecting an exception at that point, triggering the fall back.

**Comment by phaller** [comment]
@viktorklang Also, it seems dangerous to just create _some_ `ExecutionContext`, without the user knowing exactly what they're going to get.

**Comment by viktorklang** [comment]
@phaller Fortunately though, do we need to fix this for 2.11.x or should we just wait for 2.12.x and have the global be backed by ForkJoinPool.commonPool and defer to that documentation?

**Comment by phaller** [comment]
@viktorklang OK, so the fall back is only triggered due to the following:

> SecurityException - if a security manager exists and the caller is not permitted to modify threads
> because it does not hold RuntimePermission("modifyThread")

The other exceptions can never be thrown. Thus, we probably shouldn't do a catch-all.

**Comment by viktorklang** [comment]
@phaller Nice catch!

**Comment by phaller** [comment]
@viktorklang For 2.12.x I also think `global` should be backed by `ForkJoinPool.commonPool`. Fortunately, my doc comment will be fully-correct then. :-)

Thus, why not provide a general description right in the ScalaDoc, and then, on 2.12.x, refer to the `commonPool` docs for details?

I could add a comment about `SecurityException` to `ExecutionContext.global`. WDYT?

Also, we should probably have a companion PR for 2.12.x at this point.

**Comment by phaller** [comment]
@viktorklang I found another issue: by setting the system properties `scala.concurrent.context.{minThreads, numThreads, maxThreads}` to 0 or something negative, then the fall back can also be triggered because of an `IllegalArgumentException`.

**Comment by phaller** [comment]
@viktorklang Good thing you pointed out the fall back logic! :-)

**Pull request closed without merging**
