### PR TITLE
Modularize scaladoc... almost

### PR DESCRIPTION
**Pull request by adriaanm**
We postponed the actual modularization to 2.12, because dealing with the fall out of this refactoring would take too much time away from 2.11's stabilisation phase.

### CODE REVIEW

**Comment by adriaanm** [comment]
Great, need to make sure modules are published with snapshot versions when the core is.

**Comment by adriaanm** [comment]
Review by @JamesIry

**Comment by adriaanm** [comment]
You're right, sorry -- I meant to update the commit message to explain that this is intended as a compromise between not doing the modularisation yet, but still merging as much of the work as possible so it doesn't get lost. I'd rather not have to rebase changes to xml in three months.

**Comment by adriaanm** [comment]
ping @gkossakowski -- could you sign off? (I mean on not doing wildcard exclude?)

**Comment by JamesIry** [comment]
I'm looking at it now

**Comment by adriaanm** [comment]
ping @JamesIry -- I'd like to clear the PR queue today as much as possible

**Comment by JamesIry** [comment]
pong

**Comment by JamesIry** [comment]
LGTM

**Comment by gkossakowski** [comment]
Sorry. I misunderstood you. I thought you want to update that commit
message in the end. :-)

Thanks @JamesIry for helping me!

W dniu środa, 13 listopada 2013 użytkownik Adriaan Moors napisał:

> ping @gkossakowski https://github.com/gkossakowski -- could you sign
> off?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scala/scala/pull/3112#issuecomment-28421036
> .

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by adriaanm** [comment]
I did update the commit message, and was wondering about the trade-offs in wildcards.

**Comment by gkossakowski** [comment]
Oops. I have no idea how I missed that. Sorry for that!

I just read your commit messages and they make perfect sense now. Thanks
for writing it down!

W dniu środa, 13 listopada 2013 użytkownik Adriaan Moors napisał:

> I did update the commit message, and was wondering about the trade-offs in
> wildcards.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scala/scala/pull/3112#issuecomment-28423098
> .

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by adriaanm** [comment]
No worries -- thanks :-)

**Pull request merged**
