### PR TITLE
SI-8680  Stream.addString is too eager

### PR DESCRIPTION
**Pull request by Ichoran**
Used the standard method of sending out two iterators, one twice as fast as the others, to avoid hanging on .force, .hasDefiniteSize, and .addString.

.addString appends a "..." as the last element if it detects a cycle.  It knows how to print the cycle length, but there's no good way to specify what you want right now, so it's not used.

Added tests in t8680 that verify that cyclic streams give the expected results.

scala/bug#8680

### CODE REVIEW

**Comment by adriaanm** [comment]
Ping @Ichoran:

```
test.bc:
     [echo] Checking backward binary compatibility for scala-library (against 2.11.0)
     [mima] Found 3 binary incompatibiities
     [mima] ===============================
     [mima]  * synthetic method
     [mima]    scala$collection$immutable$Stream$$loop$6(Int,Int,scala.Function1)scala.collection.immutable.Stream
     [mima]    in object scala.collection.immutable.Stream does not have a correspondent in
     [mima]    new version
     [mima]  * synthetic method
     [mima]    scala$collection$immutable$Stream$$loop$5(Int,scala.collection.immutable.Stream,java.lang.Object)scala.collection.immutable.Stream
     [mima]    in class scala.collection.immutable.Stream does not have a correspondent in
     [mima]    new version
     [mima]  * synthetic method
     [mima]    scala$collection$immutable$Stream$$loop$4(scala.collection.immutable.Set,scala.collection.immutable.Stream)scala.collection.immutable.Stream
     [mima]    in class scala.collection.immutable.Stream does not have a correspondent in
     [mima]    new version
     [mima] Generated filter config definition
     [mima] ==================================
     [mima] 
     [mima]     filter {
     [mima]         problems=[
     [mima]             {
     [mima]                 matchName="scala.collection.immutable.Stream.scala$collection$immutable$Stream$$loop$6"
     [mima]                 problemName=MissingMethodProblem
     [mima]             },
     [mima]             {
     [mima]                 matchName="scala.collection.immutable.Stream.scala$collection$immutable$Stream$$loop$5"
     [mima]                 problemName=MissingMethodProblem
     [mima]             },
     [mima]             {
     [mima]                 matchName="scala.collection.immutable.Stream.scala$collection$immutable$Stream$$loop$4"
     [mima]                 problemName=MissingMethodProblem
     [mima]             }
     [mima]         ]
     [mima]     }
     [mima] 
```

**Comment by Ichoran** [comment]
@adriaanm - Yeah, I meant to talk to you about this.  These are inner recursive methods that nobody should ever call or know about.  What is the policy with these?  I couldn't keep the same interface anyway, due to different requirements for the loops.  I can put dead loops back in just to keep the formal method list the same.  Or is it okay to drop these since nobody should use them except the body of methods that I've changed (in otherwise binary compatible ways)?

**Comment by adriaanm** [comment]
Yeah, since these methods are effectively private, we can just add them to the mima whitelist.

**Comment by retronym** [comment]
ping @Ichoran

**Comment by Ichoran** [comment]
I might have fixed this--added the filters to my branch.  But there seems to be a bincompat problem unrelated to this code that's sneaked through...?

**Comment by retronym** [comment]
(Just a guess.)

You have to run `ant clean build-opt test.bc`. Running `ant clean build test.bc` is known to fail.

**Comment by Ichoran** [comment]
Well, I did exactly what is known to fail, so no surprise there I guess!

**Comment by gkossakowski** [comment]
ping @Ichoran

**Comment by Ichoran** [comment]
PLS REBUILD/pr-scala@6d69d5f

**Comment by gkossakowski** [comment]
Pinging @lchoran again. Maybe rebase would help too?

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
