### PR TITLE
Trees of named defs get NamePos used for symbol

### LINKED ISSUE #12735: Shrink range of diagnostics to prevent them from hiding other diagnostics
Scala version: 2.13.8

## Motivation

Some diagnostics span the entire body of, for instance, a class or method. In most cases I think we should shrink the range of the diagnostics to the declared identifier of the class or method. My arguments are:
- Spanning the entire body does not bring much information
- The bigger range can hide smaller ones. This compromise the readability of reports in IDEs.
- In Scala 3, some ranges have already been shrunk.

A typical example of a diagnostic that can be huge and hide many other diagnostics is the missing implementation. Here it spans 400 lines of code.

image

I give below a non-exhaustive list of diagnostics, with reproduction steps, that could potentially be shrunk.

## Missing implementation

```scala
package example

trait A {
  def x: String
}

class B[+T] extends A {
  def y(t: T): Unit = ()
}
```

image

In this example the "Missing implementation" warning hides a "covariant type T occurs in contravariant position".

In Scala 3, the range only contains the identifier of the class.

## Unused method

```scala
// build.sbt
scalaVersion := "2.13.8"
scalacOptions += "-Wunused:_"
```

```scala
package example

class UnusedMethod {
  private def m: String = {
    List(1) match {
      case Nil => "nil"
    }
  }
}
```

image

Here the "Unused method" warning hides the "match may not be exhaustive warning". Again the range should only contain the identifier.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12735

### CODE REVIEW

**Comment by som-snytt** [comment]
~Optimistically advanced to 2.13.11~ because it is low-risk but user-facing. (For users of certain tools.)

**Comment by som-snytt** [comment]
A difference between `def m: Int` and `object X {` is where the name is deemed to have ended.

**Comment by lrytz** [comment]
> A difference between `def m: Int` and `object X {` is where the name is deemed to have ended.

Pushed a change to use `lastOffset` to address this

**Review by lrytz — APPROVED** [review]
LGTM, to merge after 2.13.11

**Comment by som-snytt** [comment]
> ~Optimistically advanced to 2.13.11~ because it is low-risk but user-facing.

Hey, there's still time!

**Comment by som-snytt** [comment]
Reminder needs a follow-up see linked ticket.

**Pull request merged**
