### PR TITLE
Optimize findmember

### PR DESCRIPTION
**Pull request by adriaanm**
resubmission of #905

From its description:

findMember takes about 30% of typechecking aggregate, 20% if we discount nested calls to asSeenFrom.
I have tried ten different things to make it faster. The end result is less impressive than I had hoped for. I get about 16% reduction in wall-clock time for findMember, but my timings might be off. Still, every small improvement is worth it.

I left all 10 changes as separate commits, so that we have a chance of measuring what works and what doesn't when Greg's benchmarking code is done.

review by @odersky

### CODE REVIEW

**Comment by adriaanm** [comment]
spurious?

```
  [partest] testing: [...]/files/presentation/t5708                               [FAILED]
  [partest] reload: Completions.scala
  [partest] 
  [partest] askTypeCompletion at Completions.scala(17,9)
  [partest] TIMEOUT: Completions.scala:17:9
  [partest] testing: [...]/files/presentation/implicit-member                     [FAILED]
  [partest] reload: ImplicitMember.scala
  [partest] 
  [partest] askTypeCompletion at ImplicitMember.scala(7,7)
  [partest] TIMEOUT: ImplicitMember.scala:7:7
  [partest] testing: [...]/files/presentation/visibility                          [FAILED]
  [partest] reload: Completions.scala
  [partest] 
  [partest] askTypeCompletion at Completions.scala(14,12)
  [partest] TIMEOUT: Completions.scala:14:12
```

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by odersky** [comment]
I also had intermittent failures in presentation compiler. I'd like to benchmark the failing tests to see whether there is a real slowdown. Let's leave the pull request in the queue until that is done.

**Comment by adriaanm** [comment]
timeouts also appeared in other test runs, so they're less likely to be related to this pull request
thus, merging

**Pull request merged**
