### PR TITLE
Fix method name reference in Predef documentation

### PR DESCRIPTION
**Pull request by janekdb**
Review by @heathermiller, @dickwall, @som-snytt.

### CODE REVIEW

**Comment by janekdb** [comment]
Needs a rebuild after the repo problem is solved:

http://www.codehaus.org/mechanics/maven/ - Codehaus no longer serves up Maven repositories,

**Comment by som-snytt** [comment]
LGTM

But I wonder if there is any such static analysis tool.

Also, it says the "declaration" asserts something about the contract instead of "definition".

**Comment by adriaanm** [comment]
Thanks, @janekdb! Infra issue tracked at https://github.com/scala/scala-jenkins-infra/issues/116

**Pull request merged**
