### PR TITLE
Bug fixes in divergent implicits checker

### LINKED ISSUE #10080: unexpected "diverging implicit expansion" errors
Trying to compile the following code:

```scala
object W {
  implicit def tuple2[A: W, B: W]: W[(A, B)] = new W[(A, B)] {}
}
trait W[P]

class WC[T1: W, T2: W, T3: W]() {
  val wc = implicitly[
    W[((T3, T1), T2)]
  ]
}
```

yields the following compiler error:

```scala
OC.scala:27: diverging implicit expansion for type W[((T3, T1), T2)]
starting with value evidence$9 in class WC
  val wc = implicitly[
                     ^
```

This is probably a bug, because when I change the WC class to a method, it compiles without errors: 

```scala
object WC {
  def wc[T1: W, T2: W, T3: W]() = 
    implicitly[W[((T3, T1), T2)]]
}
```

The error can be also fixed by changing WC to: 

```scala
class WC[T1: W, T2: W, T3: W]() {
  val wc = implicitly[
    W[((T3, T1), T2)]
  ](W.tuple2[(T3, T1), T2](implicitly, implicitly))
}
```

This error is probably the reason, why Ordering with nested tuples can not be implicitly constructed in classes:

```scala
class OC[T1: Ordering, T2: Ordering]() {
  val ordering = implicitly[
    Ordering[((Int, T1), T2)]
  ] // /* uncommenting the following fixes the compile error */ (Ordering.Tuple2[(Int, T1), T2](implicitly, implicitly))
}
```

### LINKED ISSUE #11768: Diverging implicit expansion in Scala 2.13
The following code compiles in Scala 2.12.10, fails with a diverging implicit error in Scala 2.13.0:

```scala
object A {
  trait B[T]
  implicit def c[T <: Singleton]: B[T] = ???
  implicit def d[T1: B, T2: B]: B[Tuple2[T1, T2]] = ???
  implicit def e[T: B]: B[Option[T]] = ???

  implicit def f[C[_] <: Iterable[_], T](implicit r: B[T]): B[C[T]] = ???
}
object G{
  class H[T: A.B, V: A.B](t: Option[(V, T)]){
    implicitly[A.B[Option[(V, T)]]]
  }
  def h[T: A.B, V: A.B](t: Option[(V, T)]){
    implicitly[A.B[Option[(V, T)]]]
  }
}
```

`class H` is what fails to compile, even though `def h` compiles just fine. 

As far as I can tell this is a minimal repro. Removing `def f` also is sufficient to make everything (including `class H`) compile. Converting the `Tuple2` to a `Seq` also makes things compile.

This is a regression and causes spurious compile errors when trying to use uPickle with Scala 2.13

### PR DESCRIPTION
**Pull request by joroKr21**
We can't rely on type equality (`=:=`) to indicate domination
or covering when the types contain wildcards (`?`) because
wildcards are equal to anything by definition (e.g. `? =:= (?, ?)`).
But we explicitly add those wildcards in the `stripped` method.
Since type equality is not essential to the computation we omit it,
unless the complexity is exactly equal, then we need to check. 

To offset the possible perfomance degradation we optimize:
  * Don't allocate `Option[Boolean]` in `existsDominatedImplicit`
  * Eliminate redundant calls to `stripped(core(tp))`
    in `dominates` and `coversPt`

Also removed some unused pattern bindings in the area.

Fixes scala/bug#11768 and fixes scala/bug#10080

### CODE REVIEW

**Comment by adriaanm** [comment]
Could I ask to split the commit in two? The first one focused on correctness (and nothing else), and the second for optimizations and any other refactorings. We may not even need the second if the benchmarks hold steady.

**Comment by joroKr21** [comment]
Sure, good point :+1:

**Comment by joroKr21** [comment]
> Could I ask to split the commit in two?

Done. I think the refactoring is still valuable though, it helped me to understand the code and actually fix the bug.

**Comment by SethTisue** [comment]
@adriaanm do you intend to review this any further? and/or, should we find another reviewer?

**Review by adriaanm — APPROVED** [review]
LGTM, thanks! @lrytz let's keep an eye on the performance charts for this one

**Comment by SethTisue** [comment]
@joroKr21 should this be in the release notes, do you think? in order to include it, we'd need 1) your, or someone's, opinion that it's of sufficiently broad interest, and 2) an issue title and description that makes the nature of that interest clear — we'd need to try harder to help the reader understand when this fix is relevant and what new powers having it fixed gives them, that kind of thing

(most bug fixes aren't mentioned individually in the release notes, so we should default to "no" here unless we can put together a good case for "yes")

**Comment by joroKr21** [comment]
The only relevant example for the user we know of is when summoning implicits for tuples in a class (the one from scala/bug#11768). On one hand that's probably an edge case, on the other it's a bug that's hard to diagnose and contributes to the general frustration about implicits.

Either way I don't have a strong case for including it in the release notes 😄

**Comment by lrytz** [comment]
Benchmarks [seem stable](https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark?orgId=1&var-branch=2.13.x&var-source=All&var-bench=HotScalacBenchmark.compile&var-host=scalabench@scalabench@&from=1580879774045&to=1581587304392), but we're also not compiling any type-level heavy code there.

**Comment by SethTisue** [comment]
@joroKr21 @fthomas the following came up in the community build. does it seem like a progression or a regression?

* https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3199/artifact/logs/refined-build.log
* https://github.com/scalacommunitybuild/refined/commit/6f99d91e4167592405642b3f585e40bd8a85c4f8

**Comment by fthomas** [comment]
Looks like a progression to me.

**Pull request merged**
