### PR TITLE
correctly fails implicit search for invalid implicit macros

### PR DESCRIPTION
**Pull request by xeno-by**
There was a rare corner case when implicit search wouldn’t discard
an invalid implicit macro (e.g. the one with mismatching macro impl or
the one with macro impl defined in the same compilation run) during
typechecking the corresponding candidate in typedImplicit1. This is now fixed.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by adriaanm** [comment]
PLS REBUILD ALL

Sorry, the partest integration fail is my bad. Fixed by https://github.com/scala/jenkins-scripts/commit/766003ba7fbc94a76971018a282b9cbdd47d6df8. When #3129 was merged, I had to update partest, but forgot to bump the tag of partest against which we integrate.

I've rebuilt the pr-scala-integrate-partest job manually and it succeeded (see https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-partest/)

Should be all green soon!

**Comment by xeno-by** [comment]
@retronym @adriaanm @gkossakowski Could we have this fix in M7, so that it gets into a new starr? This might come very handy for macro-based lifters for case classes, which currently can't be defined in scala-reflect.jar because of this bug.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@adriaanm is handling the M7 release so it's up to him to decide. Also, this hasn't been reviewed yet.

**Comment by retronym** [comment]
How do we end up with an erroneous tree but no errors reported in the `Context`? This patch looks okay as a backstop, but I need to know a bit more about how we get into this situation.

**Comment by xeno-by** [comment]
When a macro impl is invalid (doesn't match a macro def or is defined in the same compilation unit), then upon an attempt to expand an invocation of a corresponding macro def, the macro engine marks the symbol of macro def as erroneous and ignores further attempts towards expansion.

This however sends a signal to `checkAccessible` that all trees that contain a reference to that macro def should be marked as erroneous, without reporting any errors: https://github.com/scala/scala/blob/ab77f2af52b41f70f161891be51d8737b9086d53/src/compiler/scala/tools/nsc/typechecker/Infer.scala#L266. That makes `typed1` in `typedImplicit1` return an erroneous tree in https://github.com/scala/scala/blob/ab77f2af52b41f70f161891be51d8737b9086d53/src/compiler/scala/tools/nsc/typechecker/Infer.scala#L266. Unfortunately, that goes unnoticed by `typedImplicit1`, because all that it does is checking for `context.hasErrors` and catching `TypeError`'s.

**Comment by retronym** [comment]
LGTM. Thanks for the explanation.

I think the [strap failure](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-test/3677/console) is another general problem and not specific to this PR.

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Sorry, M8 it is!

**Pull request merged**
