### PR TITLE
Disable test t2868

### PR DESCRIPTION
**Pull request by lrytz**
it keeps failing randomly, e.g. http://scala-webapps.epfl.ch/artifacts/e3b0c7abbf637dacce7bcd7b69d5655820e8e714/buildLog.txt

### CODE REVIEW

**Comment by lrytz** [comment]
review by @gkossakowski

**Comment by paulp** [comment]
That link is "BUILD SUCCESSFUL" so I take it you mean some other log.  You don't need to dig it up, I believe it; but it'd be nice to record something somewhere.  The test could be viewed as a valuable means of demonstrating non-deterministic behavior with annotations.

**Comment by jsuereth** [comment]
LGTM

**Comment by lrytz** [comment]
right, it used to be the correct failure, but i restarted that build, which
overwrote the file.

**Pull request merged**
