### PR TITLE
SI-5508 Fix crasher with private[this] in nested traits

### PR DESCRIPTION
**Pull request by retronym**
Currently, this is done late in the game as the Mixin tree transformer
treats the trait.

```
// Mixin#addLateInterfaceMembers
val getter = member.getter(clazz)
if (getter == NoSymbol) addMember(clazz, newGetter(member))
```

`addMember` mutates the type of the interface to add the getter.

However, if an inner class or anonymous function of the trait
has been flattened to a spot where it precedes the trait in the
enclosing packages info, this code hasn't had a chance to run,
and the lookup of the getter crashes as mixins postTransform
runs over a selection of the not-yet-materialized getter.

```
// Mixin#postTransform
case Select(qual, name) if sym.owner.isImplClass && !isStaticOnly(sym) =>
  val iface  = toInterface(sym.owner.tpe).typeSymbol
  val ifaceGetter = sym getter iface
```

This commit ensures that Flatten lifts inner classes to
a position _after_ the enclosing class in the stats of the
enclosing package.

Bonus fix: SI-7012 (the followup ticket to SI-6231 / SI-2897)

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski

**Comment by retronym** [comment]
I ran this bug by @odersky a few weeks back. He suggested that moving this accessor generation into the mixin info transformer, and avoiding doing that in its tree transformer, sounds like the most principled fix. Second favourite was this approach: living with the order-dependency and being more careful to lift doubly-nested members out after the enclosing nested member. I've gone for the second one for now.

**Comment by retronym** [comment]
ping @gkossakowski for review

**Comment by retronym** [comment]
I don't want to try to fix this by moving the logic into the mixin tree transformer for 2.11.

**Comment by gkossakowski** [comment]
LGTM.

Thanks for detailed explanation of what was happening. It helped me a lot while reviewing the change.

Sorry it took me so long to review it. I just forgot about this PR.

**Pull request merged**
