### PR TITLE
Merge 2.12.0 to 2.12.x [ci:last-only]

### PR DESCRIPTION
**Pull request by retronym**
```
% git log --oneline --decorate --graph $MB..origin/2.12.0
* 6114b7c (origin/2.12.0, adriaanm/2.12.0, 2.12.0) Make stability test optional.
* 2164eb7 Make sbtBuildTask configurable in bootstrap
*   6a5ffa4 Merge pull request #5457 from retronym/topic/restarr
|\
| * db6c152 (retronym/topic/restarr, origin/pr/5457, topic/restarr) Restarr to fix InterfaceMethodRef after closure inlining
* |   813c222 Merge pull request #5456 from adriaanm/i244
|\ \
| |/
|/|
| * b2b4591 (origin/pr/5456, adriaanm/i244) Detect clash of mixedin val and existing member.
|/
*   1e81a09 Merge pull request #5429 from lrytz/sd224
|\
| * 550e47b (origin/pr/5429, lrytz/sd224) Test cases for super calls
| * 0e0614c Default -Xmixin-force-forwarders to true
| * 759b0da Explicit SerialVersionUID for all ClassTags / Manifests
| * 9246348 re-enable two tests (starr is up to date now)
| * 96fe4c3 Error message for super calls to indirect java parent interfaces
*   95b1427 Merge pull request #5442 from adriaanm/t9943
|\
| * 2089664 (origin/pr/5442, adriaanm/t9943) SI-9943 final/sealed class does not yield SAM type
*   d7fe049 Merge pull request #5452 from lrytz/sd242
|\
| * e794e51 (origin/pr/5452, lrytz/sd242) Fix the interface flag when re-writing a closure call to the body method
* |   876401b Merge pull request #5445 from retronym/ticket/9946b
|\ \
| |/
|/|
| * ef14a9a (retronym/ticket/9946b, origin/pr/5445, ticket/9946b) SI-9946 don't null field in lazy accessors that turn out to be live
| * 55c0581 SI-9946 make nullification of lazy val dependencies module aware
|/
* ada6b6b Merge pull request #5443 from SethTisue/disable-SI-5293-tests
* 5b04e9c (origin/pr/5443) SI-5293 delete flaky collection performance tests

% git merge origin/2.12.0
Removing test/files/run/t5293.scala
Removing test/files/run/t5293-map.scala
Merge made by the 'recursive' strategy.
 scripts/jobs/integrate/bootstrap                                         |  20 +++-
 spec/06-expressions.md                                                   |   1 +
 src/compiler/scala/tools/nsc/backend/jvm/opt/ClosureOptimizer.scala      |   3 +-
 src/compiler/scala/tools/nsc/settings/ScalaSettings.scala                |   4 +-
 src/compiler/scala/tools/nsc/transform/AccessorSynthesis.scala           |  66 +------------
 src/compiler/scala/tools/nsc/transform/Constructors.scala                |  20 ++--
 src/compiler/scala/tools/nsc/transform/Fields.scala                      |  24 ++---
 src/compiler/scala/tools/nsc/transform/Mixin.scala                       |  86 ++++++++++++++++-
 src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala            |   4 +-
 src/library/scala/collection/immutable/Set.scala                         |   1 +
 src/library/scala/reflect/ClassManifestDeprecatedApis.scala              |  20 ++--
 src/library/scala/reflect/ClassTag.scala                                 |   1 +
 src/library/scala/reflect/Manifest.scala                                 |  20 ++++
 src/reflect/scala/reflect/internal/Definitions.scala                     |   4 +-
 src/reflect/scala/reflect/internal/TypeDebugging.scala                   |   2 +-
 test/files/neg/t1960.check                                               |  11 ++-
 test/files/neg/t1960.scala                                               |   7 +-
 test/files/neg/t4749.check                                               |   2 +-
 test/files/neg/t5148.check                                               |  16 ++++
 test/files/{pos => neg}/t5148.scala                                      |   0
 test/files/pos/issue244.scala                                            |   2 +
 test/files/pos/t9943.scala                                               |   9 ++
 test/files/run/mixin-signatures.check                                    |  21 ++--
 test/files/run/sd242.scala                                               |  13 +++
 test/files/run/t5293-map.scala                                           |  88 -----------------
 test/files/run/t5293.scala                                               |  83 ----------------
 test/files/run/t5652.check                                               |   1 +
 test/files/run/t8549.scala                                               |  26 ++---
 test/files/run/t9946a.scala                                              |  14 +++
 test/files/run/t9946b.scala                                              |  12 +++
 test/files/run/t9946c.scala                                              |  10 ++
 test/files/run/trait-super-calls.scala                                   | 127 ++++++++++++++++++++++++
 test/junit/scala/collection/mutable/BitSetTest.scala                     |   2 +-
 test/junit/scala/collection/mutable/OpenHashMapTest.scala                |   7 +-
 test/junit/scala/lang/traits/BytecodeTest.scala                          | 217 +++++++++++++++++++++++++++++++++++++++---
 test/junit/scala/tools/nsc/backend/jvm/DirectCompileTest.scala           |   4 +-
 test/junit/scala/tools/nsc/backend/jvm/opt/BTypesFromClassfileTest.scala |   6 +-
 test/junit/scala/tools/nsc/backend/jvm/opt/InlinerTest.scala             |   8 +-
 test/junit/scala/tools/nsc/backend/jvm/opt/ScalaInlineInfoTest.scala     |   5 +-
 test/junit/scala/tools/nsc/symtab/StdNamesTest.scala                     |   7 +-
 versions.properties                                                      |   2 +-
 41 files changed, 620 insertions(+), 356 deletions(-)
 mode change 100644 => 100755 scripts/jobs/integrate/bootstrap
 create mode 100644 test/files/neg/t5148.check
 rename test/files/{pos => neg}/t5148.scala (100%)
 create mode 100644 test/files/pos/issue244.scala
 create mode 100644 test/files/pos/t9943.scala
 create mode 100644 test/files/run/sd242.scala
 delete mode 100644 test/files/run/t5293-map.scala
 delete mode 100644 test/files/run/t5293.scala
 create mode 100644 test/files/run/t9946a.scala
 create mode 100644 test/files/run/t9946b.scala
 create mode 100644 test/files/run/t9946c.scala
 create mode 100644 test/files/run/trait-super-calls.scala
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @scala/team-core-scala

**Comment by SethTisue** [comment]
ha, you beat me to this by a few minutes.

this will fix the recent scala-2.12.x-integrate-windows failure on Jenkins

**Comment by retronym** [comment]
```
!!  478 - run/reflection-mem-typecheck.scala        [output differs]
% diff /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/reflection-mem-typecheck-run.log /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/reflection-mem-typecheck.check--- empty
+++ reflection-mem-typecheck-run.log
@@ -1,0 +1,12 @@
+FAILED
+94.273056 Mb
+99.405848 Mb
+102.40572 Mb
+102.963016 Mb
+104.516032 Mb
+107.015664 Mb
+109.950304 Mb
+112.637656 Mb
+114.901648 Mb
+116.761352 Mb
+116.765824 Mb
##### Log file '/home/jenkins/workspace/scala-2.12.x-validate-test/test/files/run/reflection-mem-typecheck-run.log' from failed test #####

FAILED
94.273056 Mb
99.405848 Mb
102.40572 Mb
102.963016 Mb
104.516032 Mb
107.015664 Mb
109.950304 Mb
112.637656 Mb
114.901648 Mb
116.761352 Mb
116.765824 Mb
```

Last patch to that test:

``` diff
-  override def maxDelta = 10
+  // I'm not sure this is a great way to test for memory leaks,
+  // since we're also testing how good the JVM's GC is, and this is not easily reproduced between machines/over time
+  override def maxDelta = 12
```

**Comment by SethTisue** [comment]
this should also fix the recent scala-2.12.x-integrate-community-build failures (well the kxbmap-configs part of the failure anyway, which is because of SI-9946, the fix for which is part of this merge — the simulacrum failure is https://github.com/scala/community-builds/issues/347)

**Pull request merged**
