### PR TITLE
Revert "GenASM: pipeline disk-write with building of classfiles"

### PR DESCRIPTION
**Pull request by dragos**
This reverts commit 5d12fa4b791e73d5c99a0e145d28cbaba12823d2.

This is a temporary solution to unblock the IDE for M5. A background thread can't make changes to the Eclipse workspace without acquiring the proper locks.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Worth mentioning that @magarciaEPFL proposed this (temporary) solution. If build passes then it gets LGTM from me.

**Comment by dragos** [comment]
Yes, sorry I forgot to mention that, and a reviewer. There, review by @gkossakowski, @magarciaEPFL

**Comment by magarciaEPFL** [comment]
LGTM

**Comment by adriaanm** [comment]
@dragos, I was just reminded of this PR -- looks like the "temporary" measure is still in place :-)
Could we bring back the parallelism in 2.11.1?

**Comment by dragos** [comment]
It's been on my todo list for a while now. Since we moved to the Sbt builder, it should be possible now. The simplest next step would be to open a PR with this change, and let the PR validation do its thing.

**Comment by adriaanm** [comment]
Cool! Will do for 2.11.1-RC1.

**Pull request merged**
