### PR TITLE
SI-6167 Faster Vector#isEmpty (and head, tail, last, init)

### PR DESCRIPTION
**Pull request by soc**
Avoid building a VectorIterator just to check if iterator.hasNext
is false.

### CODE REVIEW

**Comment by soc** [comment]
@retronym suggested that instead of overriding `isEmpty` in Vector (see #1036) I should override it in `SeqLike`.

**Comment by adriaanm** [comment]
this caused a test to fail

**Comment by soc** [comment]
I'll investigate!

**Comment by jsuereth** [comment]
review by @alex22

**Comment by soc** [comment]
The issue is that in the `view` test code the first element is evaluated when invoking `tail`. I'm not sure how a correct fix would look like here.

**Comment by paulp** [comment]
The fix for that would look like this: #1131

Can you open a new pull request against the 2.10.x branch after #1131 is merged? This being performance oriented and non-threatening, I want to get it into 2.10.

**Comment by jsuereth** [comment]
Agree wtih @paulp

**Comment by Blaisorblade** [comment]
@soc: #1131 is merged but SI-6167 is still open, can you take a look and possibly resubmit?

**Comment by soc** [comment]
The code has been merged in both 2.10.x https://github.com/scala/scala/blob/2.10.x/src/library/scala/collection/SeqLike.scala#L95 and master https://github.com/scala/scala/blob/master/src/library/scala/collection/SeqLike.scala#L95, so I'll close the ticket.

**Pull request closed without merging**
