### PR TITLE
Merge 2.10.x to master

### PR DESCRIPTION
**Pull request by retronym**
Review by @adriaanm 

The conflict resolution in dist.doc is the main spot to check.

```
export MB=`git merge-base origin/2.10.x origin/master`
merge/2.10.x-to-master ~/code/scala4 git --no-pager  log $MB...origin/2.10.x --oneline --graph
* 9cdbe28 Fixup #3248 missed a spot in pack.xml
*   4aaee3b Merge pull request #3249 from retronym/ticket/7912
|\
| * 006e2f2  Be defensive calling `toString` in `MatchError#getMessage`
* |   0b77398 Merge pull request #3251 from retronym/ticket/8060
|\ \
| * | bb427a3  Avoid infinite loop with higher kinded type alias
| |/
* |   f405417 Merge pull request #3248 from adriaanm/dist-cleanup-licenses
|\ \
| |/
|/|
| * 27a3860 Update README, include doc/licenses in distro
| * 139ba9d Add attribution for Typesafe.
| * e555106 Remove docs/examples; they reside at scala/scala-dist
| * dc6dd58 Remove unused android test and corresponding license.
| * f8d8f7d Do not distribute partest and its dependencies.
* |   0c92704 Merge pull request #3222 from skyluc/issue/completion-import-vals-210-7995
|\ \
| * | 5ed834e  completion imported vars and vals
* | |   a444ed7 Merge pull request #3244 from rtyley/si-8019-swing-publisher-check-pf-defined
|\ \ \
| |_|/
|/| |
| * | c955cf4  Make Publisher check PartialFunction is defined for Event
|/ /
* |   db19ddf Merge pull request #3229 from retronym/ticket/8029
|\ \
| * | fdcc262  Avoid multi-run cyclic error with companions, package object
| |/
* |   4d439dd Merge pull request #3230 from retronym/backport/7439
|\ \
| * | 8d74fa0 [backport]  Avoid NPE in `isMonomorphicType` with stub symbols.
* | |   a774157 Merge pull request #3223 from retronym/ticket/8010-2.10.x
|\ \ \
| * | | 9036f77  Fix regression in erasure double definition checks
| | |/
| |/|
* | |   f6c6846 Merge pull request #3232 from xeno-by/topic/macro-error-messages-210x
|\ \ \
| |_|/
|/| |
| * | 3faa2ee [nomaster] better error messages for various macro definition errors
|/ /
* | 7e996c1 Merge pull request #3209 from dotta/-on-2.10.x
* |   7d74884 Merge pull request #3181 from heathermiller/issue/6913
|\ \
| |/
|/|
| * 7063439  Fixing semantics of Future fallbackTo to be according to docs
|/
* 7c1d114 Merge pull request #3208 from dotta/si-7548-on-2.10
* 02308c9  Pres. compiler must not observe trees in silent mode
* 652b3b4  Test to demonstrate residual exploratory typing bug
* b7509c9  askTypeAt returns the same type whether the source was fully or targeted type-checked
```

### CODE REVIEW

**Comment by retronym** [comment]
```
% git merge 7e996c1
% git merge -s ours f6c6846
% git merge a774157
% git merge -s ours 4d439dd
% git merge 0c92704
% git merge 9cdbe28
```

**Comment by adriaanm** [comment]
thank you thank you thank you! I (barely) started doing this yesterday and got interrupted. This was next on my list :-)

**Comment by adriaanm** [comment]
LGTM, there's a slight typo in `<copy toDir="${dist.dir}/doc/api" overwrite="true" flatten="true">` (`s|doc/api|api|`), but I have to rework this a bit anyway, so I'll get that in a follow up (it won't break anything, but I believe the release scripts will miss these jars)

**Comment by adriaanm** [comment]
all spurious failures in the IDE due to the github connectivity fail -- going to rebuild the last one just to make sure

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@3bfd839

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@44ccf7f
PLS REBUILD/pr-scala@18fd31d
PLS REBUILD/pr-scala@e1c6dd9
PLS REBUILD/pr-scala@3bfd839

**Comment by adriaanm** [comment]
Rebuild should fix this once https://github.com/scala-ide/uber-build/pull/26 is merged.

**Comment by adriaanm** [comment]
Validating last commit manually with uber-build fix in my fork. https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/4808/console

**Comment by adriaanm** [comment]
Manual validation passed. Merging this without further ado because our queue is backing up.

**Pull request merged**
