### PR TITLE
Remove partiality of `+` method from SortedMap

### PR DESCRIPTION
**Pull request by puffnfresh**
`SortedMap#+` threw an `AbstractMethodError` if it was not overridden. It should instead be a compile error.

### CODE REVIEW

**Comment by retronym** [comment]
This changes looks great but I need to do some archaeology to know why that abomination was there in the first place.

**Comment by retronym** [comment]
39fdbddb8812 doesn't tell me much. To hazard a guess: an attempt to be source compatible (under a perverse definition thereof) with the 2.7 collections in 2.8.0. I'll ask the parties involved.

**Comment by puffnfresh** [comment]
@retronym thanks! Someone on #scalaz linked to it so I thought I'd just run the tests then send a pull request.

Thanks for looking into it!

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@e1fb817

**Comment by retronym** [comment]
Seeking the backstory: https://groups.google.com/d/msg/scala-internals/OA8THul9ly8/Y6zQOteL-moJ

**Comment by adriaanm** [comment]
Could be because linearisation favors concrete methods, so you get this return type, but still need to provide an implementation.

**Comment by retronym** [comment]
Sorry I haven't come to a conclusion on this one yet. As that thread and Adriaan point out, it might be, well, complicated. I haven't figured out whether or not this method is in the same boat as the others. Or even catalogued the others. Will leave this PR open to remind me to so.

**Comment by JamesIry** [comment]
What's the current thinking on this PR?

**Comment by retronym** [comment]
I fear we are missing tests that show that the hack was needed and that
making this abstract could be a breaking change. I haven't had time to try
to construct those tests yet.

**Comment by adriaanm** [comment]
I'm going to close this -- @retronym feel free to reopen.

**Comment by JamesIry** [comment]
Worth creating a bug to track it?

**Comment by puffnfresh** [comment]
Is nobody confident enough to touch this stuff? It'd suck to just leave it without a conclusion.

**Comment by retronym** [comment]
I'm confident that we don't have tests to cover us against changes in linearisation like this. Once you let unknown third parties extend a class, it is pretty hard to reason about even the smallest change like this. The specific concern is that Scala, unlike Java, has a rule that says that concrete always overrides abstract, regardless of the order that the owners of the two methods appear in the list of parent classes. You can also inherit a return type from your directly overridden member. Changing a method from concrete to abstract can change this.

Let's open a ticket so the problem is not lost.

```
git log -S'throw new AbstractMethodError'
commit 8fa8118e341cc0174d789b508b8b6ebab3571582
Author: Martin Odersky <odersky@gmail.com>
Date:   Thu May 14 09:36:49 2009 +0000

    cleaned up collection builder framework

commit 39fdbddb881220f7e64e5cb9016458edc9e314e5
Author: Martin Odersky <odersky@gmail.com>
Date:   Tue May 12 18:33:22 2009 +0000

    changes to maps and sets
```

**Comment by adriaanm** [comment]
Exactly. This is one of the reasons why we're [deprecating overriding of many collection classes](https://github.com/scala/scala/pull/3103).

**Pull request closed without merging**
