### PR TITLE
SI-5744 evidence params are now SYNTHETIC 

### PR DESCRIPTION
**Pull request by xeno-by**
The macro def <-> macro impl correspondence check compares names of the
corresponding parameters in def and impl and reports an error if they
don't match. This was originally designed to avoid confusion w.r.t named
arguments (which ended up being never implemented as described in SI-5920).

Sometimes parameter names are generated by the compiler, which puts the
user in a tough position. Luckily, there's an escape hatch built it, which
omits the name correspondence check if one of the parameters are SYNTHETIC.
Everything went well until we realized that evidences generated by
context bounds aren't SYNTHETIC, which led to the bug at hand.

Marking auto-generated evidence parameters SYNTHETIC was only the first
step, as the correspondence checker uses parameter symbols, not parameter
trees. Why's that a problem? Because SYNTHETIC doesn't get propagated from def
trees to their underlying symbols (see ValueParameterFlags).

Unfortunately one cannot just change ValueParameterFlags, because that
would break printouts generated in TypeDiagnostics, which is designed to not
print synthetic symbols.

Therefore now we not only check paramSym.flags, but also paramDef.mods.flags
when doing corresponce sweeps. This fixes the problem and doesn't mess up
error messages and debug printouts.

### CODE REVIEW

**Comment by xeno-by** [comment]
Already LGTM'd. Waiting for the kitty and merging.

**Comment by gkossakowski** [comment]
@xeno-by: I think it was clear that there was a disagreement if this should go into 2.10.x branch.

Why is it safe to merge it? Is this fixing clearly a bug or not?

**Comment by lrytz** [comment]
i assume it's fixing 5744, as the title says.. why should it not go to 2.10?

**Comment by xeno-by** [comment]
Right, thank you, Greg. With all the pull requests flying around, I completely overlooked to propagate the discussion from the PR superseded by this one. 

To quote @adriaanm, "I think this should target master. Feel free to convince me otherwise". I asked about the motivation of that decision, and there was no answer so far. Of course, I won't be merging until we clarify this.

**Comment by xeno-by** [comment]
@gkossakowski I assume this is safe to merge, because the surface of the affected code is really small (the `SYNTHETIC` flag doesn't propagate from def trees to their symbols, so it's not affecting anyone who's only interested in `sym.isSynthetic`). Moreover, it's an improvement, because it fixes SI-5744. What would be the risks?

**Comment by gkossakowski** [comment]
@xeno-by: oh I didn't realize that this information doesn't get propagated to Symbol. Is this by design? If so, why?

Also, the only client I can think of that looks at trees is IDE. I know that the care about things being marked synthetic. Let's cc @dragos on this matter.

**Comment by xeno-by** [comment]
@gkossakowski As the description says, `ValueParameterFlags` doesn't include `SYNTHETIC`, but I don't know why this happens. We tried to change it to include `SYNTHETIC`, but that broke some other tests, so we decided to leave things as they are.

Thanks for reminding about the IDE. Let's see whether Iulian will mind evidence parameters being marked as synthetic.

**Comment by lrytz** [comment]
part of the problem is that synthetic is not very well defined, @paulp could say more about it i think..

i feel that the symbols should also be marked synthetic, having the modifiers and symbol flags be different seems inconsistent. but we should compare with other synthetic symbols, see if all of them have the flag, or which don't..

**Comment by u-abramchuk** [comment]
I've signed the CLA.

**Comment by JamesIry** [comment]
BUILDLOG?

**Comment by adriaanm** [comment]
I agree with @gkossakowski: we'll have to understand the impact of changing the SYNTHETIC flag on that tree better before changing this so close to RC1.

**Comment by paulp** [comment]
Touching SYNTHETIC on symbols would be unwise. I'm not aware of anything which cares about it on trees. Which is not to say there isn't anything. But if it doesn't break anything internally, and someone vouches for it not breaking the ide, then it's probably okay.

**Comment by JamesIry** [comment]
ping @dragos for input.

**Comment by JamesIry** [comment]
Until something moves on this PR, I'm moving to 2.10.2-RC2

**Comment by xeno-by** [comment]
Let's do that, I agree.

**Comment by JamesIry** [comment]
We've branched so when this PR is ready it can be merged to 2.10.x which currently targets 2.10.2-RC1

**Comment by paulp** [comment]
"As the description says, ValueParameterFlags doesn't include SYNTHETIC, but I don't know why this happens. We tried to change it to include SYNTHETIC, but that broke some other tests, so we decided to leave things as they are."

@xeno-by Can we pursue the above a little please. In the abstract, propagating SYNTHETIC from tree to symbol is much better than creating an artificial distinction, especially if the motivation is that it broke some tests to do otherwise. "It broke some tests" is almost always meaningless in terms of whether a change is bad or good; it's even a positive indicator to some extent, because at least it's not a no-op. What tests broke, and how exactly?

In my mind the question is: are you ever going to create a synthetic DefTree which is the basis of the creation of a non-synthetic symbol? Why would that ever happen? So without some reasoning why that would be a desirable sequence, the simple/obvious approach should win.

**Comment by u-abramchuk** [comment]
Tests broken were t5452-new and t5452-old. The reason of the failure is that when evidence param is marked as implicit method methodTypeErrorString (in TypeDiagnostics.scala) no longer prints its name (for example, before the change: `(implicit evidence$1: Manifest[CoffeesTable])Nothing`, and after the described changes: `(Manifest[CoffeesTable])Nothing`). Possible solution is to change method methodTypeErrorString to always print synthetic param names. But I doubt if this is the behavior this method is supposed to have, as indeed in the most of cases generated names of synthetic params provide no more information than just their type.

As I'm new to scala internals I can't answer about synthetic DefTree use cases right now. I have to do some investigation.

**Comment by paulp** [comment]
"after the described changes: (Manifest[CoffeesTable])Nothing)."

Other than the unfortunate interaction with how "implicit" is encoded, this doesn't seem like a problem to me. We can always print the names of synthetic parameters, or we can not print them (but we still have to print "implicit", so the printer has to be modified to discover that even on synthetic parameters.) Either way, you can propagate the flag from tree to symbol. Update the checkfiles and call it a day. 

Parameter lists should be first-class constructs; this is another example of why. "Implicit" is a property of a parameter list, not of a parameter, but because there is no list which can be so designated, it is shoehorned onto the parameter instead.

**Comment by u-abramchuk** [comment]
So do I understand you right that the better way to fix this issue is to keep tree modifiers in sync with symbol flags (as alternative solution imposes), i.e. to add SYNTHETIC flag to ValueParameterFlags and adjust methodTypeErrorString method? 

There are two questions that would help me to understand this issue better:
1. Why flags from tree are not propagated to symbols now? 
2. Why ValueParameterFlags doesn't include SYNTHETIC flag?

While fixing this issue I thought that this behavior was implemented with certain intention so I didn't want to change it.

Thank you in advance.

**Comment by paulp** [comment]
> 1. Why flags from tree are not propagated to symbols now? 

Because that's the way it happened.

> 1. Why ValueParameterFlags doesn't include SYNTHETIC flag?

Because nobody ever had a problem which they chose to solve by so doing.

>  I thought that this behavior was implemented with certain intention so I didn't want to change it.

If you'd like to save an enormous amount of time, accept this as provisionally true: given any particular implementation detail, it is far more likely that it is as it is for no particular reason than that there is some unknown but coherent plan holding things together. Trust your own eyes; everything else should come bearing evidence.

Since this example is an effective illustration of this truism, here are the appearances of the three flags which are propagated from trees to symbols in the case of value parameters.

[2005-04-28](https://github.com/scala/scala/commit/0baff379#L42R71)
[2005-12-02](https://github.com/scala/scala/commit/1d724260#L5R308)
[2009-05-30](https://github.com/scala/scala/commit/390ccacf#L50R530)

Spanning four years and two people, all of it written 4-8 years before now. We don't have to work too hard to conform to a plan which resides in our imaginations. Let us impose order upon chaos.

**Comment by u-abramchuk** [comment]
Thank you for clarification. I'll implement the alternative fix (with adding SYNTHETIC flag to ValueParameterFlags) and add to this PR.

**Comment by xeno-by** [comment]
You'll have to close this one and submit your own PR.

**Pull request closed without merging**
