### PR TITLE
SI-7624 Fix -feature and some -Xlint warnings

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
This supersedes @adriaanm's https://github.com/scala/scala/pull/2799 and and addresses @gkossakowski's comments.

**Comment by soc** [comment]
**Sigh**

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalacheck#scalacheck_2.11.0-2a03dc0-SNAPSHOT;1.10.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by retronym** [comment]
See: https://github.com/scala/scala-partest/commit/cd2ac5460ed1755c86fd9a669fcf667d94cc582d#commitcomment-3858462

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@soc: there's one remaining issue to be resolved in `LazyCombiner` and we'll be good to go. To save my reviewer's time and your trouble just push another commit which moves the import. Once that is done we'll be good to go.

And thanks a lot for all this work!

**Comment by soc** [comment]
@gkossakowski I fixed the issue, but because I had to redo things anyway (introduced some unwanted code changes by not rebasing it correctly), I just rolled it into the appropriate commit.

The rest is identical, sans the rebase issues which caused the compilation failure.

**Comment by soc** [comment]
Can we please please please get this merged before stuff breaks again?

**Pull request merged**
