### PR TITLE
Rewrite TailCalls for performance and immutability.

### PR DESCRIPTION
**Pull request by paulp**
While logging symbols created after typer, I discovered that
TailCalls was far and away the largest creator. It turns out
this was due to a bug where thousands of labels were eagerly
created during tail call analysis, even if the method weren't
tail recursive and no label would ever be required.

This commit shaves 10% off the total number of method symbol
creations (compiling quick.lib drops from 88K to 80K.)

### CODE REVIEW

**Comment by paulp** [comment]
Review by, I DON'T KNOW, @JamesIry.

**Comment by paulp** [comment]
Ping @JamesIry

**Comment by paulp** [comment]
Day 13! Someone review me please, @retronym @adriaanm @gkossakowski

**Comment by adriaanm** [comment]
I think @JamesIry is well-placed to review this. What's up, James?

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
