### PR TITLE
Merge/2.10.2 to 2.10.x

### PR DESCRIPTION
**Pull request by retronym**
Review by @JamesIry

### CODE REVIEW

**Comment by adriaanm** [comment]
I've highlighted the corresponding step in the release process doc. It was there, just got skipped this time.

**Comment by adriaanm** [comment]
The pragmatic alternative could be to skip creating the 2.10.3 branch and simply use 2.10.x. This would mean halting 2.10.4 development until 2.10.3 is released, but maybe that's ok. Or maybe 2.10.4 should go to a branch that gets merged into 2.10.x as soon as 2.10.3 is  released. We're less likely to forget that, as that would be the focus of work.

**Comment by gkossakowski** [comment]
I like the idea of merging 2.10.3 into 2.10.x as soon as 2.10.3 is released. This way you don't need to block any merges. I think that the fact that we forgot to do this once does not give enough of data points to decide whether our process is suboptimal.

**Comment by retronym** [comment]
Best would be a nightly Jenkins build that asserts that if the release tag is cut, the release branch must be merged. I think we can set this up once and for all based on the naming conventions.

**Comment by adriaanm** [comment]
@retronym sounds good -- you now have admin rights on jenkins :)

**Comment by JamesIry** [comment]
LGTM

**Comment by JamesIry** [comment]
We need to merge into the 2.10.3 branch as well for the RC2 cut.

**Comment by JamesIry** [comment]
Here it is https://github.com/scala/scala/pull/2878

**Pull request merged**
