### PR TITLE
SI-6436 Handle ambiguous string processors

### PR DESCRIPTION
**Pull request by retronym**
Before, we got in an inifinite loop by chasing
the error typed result of adaptToMemberWithArgs.

One point of befuddlement remains: why did t6436 and t6436b
behave differently before this change?

Review by @hubertp

### CODE REVIEW

**Comment by paulp** [comment]
Has to be the positions I think.  The synthetic ones all have the same position, but errors beyond the first at the same position are suppressed.

```
 [216][216]StringContext([216]"a").[216]"q"
 [254][241]StringContext([255]"a").[260]"q"
```

**Comment by retronym** [comment]
Oh, interesting. If an error falls in a part of the forest where the reporter no longer hears it, does it really happen?

**Comment by hubertp** [comment]
I agree it looks like positions fault. lgtm.

**Comment by gkossakowski** [comment]
So we can merge that one?

**Comment by hubertp** [comment]
Yeap.

**Pull request merged**
