### PR TITLE
[backport] Upgrade to scala-asm 6.2

### PR DESCRIPTION
**Pull request by ElfoLiNk**
Backport #6733 to 2.12.x in order to fix https://github.com/scala/bug/issues/10717

### CODE REVIEW

**Comment by lrytz** [comment]
@retronym how do you estimate the risk for regressions?

**Comment by retronym** [comment]
I'd be happy to get this change into 2.12.x.

As one test, we do a `jardiff` analysis to see how this change affects our bootstrapped distribution. I can't find a record of that analysis for the change on the 2.13.x branch, although I recall doing it.

ASM seems to be pretty well tested itself these days.

**Comment by adriaanm** [comment]
@lrytz could you do this diff and merge if it looks good?

**Comment by retronym** [comment]
I've published a bootstrapped distribution as `2.12.7-bin-1ee376b-SNAPSHOT`

```
$ git co  79b7f2a
$ git commit --allow-empty -m "restarr"
$ sbt -Dstarr.version=2.12.7-bin-79b7f2a-SNAPSHOT 'setupPublishCore https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/' clean publish
...
[info]      published scala-library to https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots;build.timestamp=1536716050731/org/scala-lang/scala-library/2.12.7-bin-1ee376b-SNAPSHOT/scala-library-2.12.7-bin-1ee376b-SNAPSHOT.jar
```

And produced a `jardiff`:

```
$ jardiff $(scala-classpath 2.12.7-bin-79b7f2a-SNAPSHOT) $(scala-classpath 2.12.7-bin-1ee376b-SNAPSHOT) | gist --filename pr-7089.diff
WARN: unable to invoke scalap on: /scala/concurrent/duration/package.class: Unexpected failure
WARN: unable to invoke scalap on: /scala/concurrent/duration/package.class: Unexpected failure
```
https://gist.github.com/25b1cf35e039d8a6fb3ab838e98dfa6f

The diff has only one class of change:

```diff
   // access flags 0x1
   public <init>(Lscala/util/matching/Regex$MatchIterator;)V
-    // parameter final  $outer
+    // parameter final synthetic  $outer
     ALOAD 1
     IFNONNULL L0
     ACONST_NULL
```

What's the cause of that?

**Comment by retronym** [comment]
The same change occured when the original PR was merged to 2.13.x. I don't think we noticed.

Javac marks its outer parameters with `ACC_MANDATED`. The outer field itself is `ACC_SYNTHETIC`.

```java
class Test {
    class Inner {};
}
```

```
 $ javac -d /tmp -parameters /tmp/Test.java && javap -v -cp /tmp 'Test$Inner'
Classfile /tmp/Test$Inner.class
  Last modified 12/09/2018; size 320 bytes
  MD5 checksum bd152caf1f1244b3f249316a2662a89f
  Compiled from "Test.java"
class Test$Inner
  minor version: 0
  major version: 52
  flags: ACC_SUPER
Constant pool:
   #1 = Fieldref           #3.#14         // Test$Inner.this$0:LTest;
   #2 = Methodref          #4.#15         // java/lang/Object."<init>":()V
   #3 = Class              #17            // Test$Inner
   #4 = Class              #20            // java/lang/Object
   #5 = Utf8               this$0
   #6 = Utf8               LTest;
   #7 = Utf8               <init>
   #8 = Utf8               (LTest;)V
   #9 = Utf8               Code
  #10 = Utf8               LineNumberTable
  #11 = Utf8               MethodParameters
  #12 = Utf8               SourceFile
  #13 = Utf8               Test.java
  #14 = NameAndType        #5:#6          // this$0:LTest;
  #15 = NameAndType        #7:#21         // "<init>":()V
  #16 = Class              #22            // Test
  #17 = Utf8               Test$Inner
  #18 = Utf8               Inner
  #19 = Utf8               InnerClasses
  #20 = Utf8               java/lang/Object
  #21 = Utf8               ()V
  #22 = Utf8               Test
{
  final Test this$0;
    descriptor: LTest;
    flags: ACC_FINAL, ACC_SYNTHETIC

  Test$Inner(Test);
    descriptor: (LTest;)V
    flags:
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: aload_1
         2: putfield      #1                  // Field this$0:LTest;
         5: aload_0
         6: invokespecial #2                  // Method java/lang/Object."<init>":()V
         9: return
      LineNumberTable:
        line 2: 0
    MethodParameters:
      Name                           Flags
      this$0                         final mandated
}
```

@lrytz thoughts?

**Comment by retronym** [comment]
Related? https://github.com/scala/bug/issues/10880

**Comment by retronym** [comment]
Oh, my mistake. The baseline for comparison should be a self-bootstrapped build of the base commit to include #6672, which adds the `ACC_SYNTHETIC` flag to the outer parameter.

**Review by retronym — APPROVED** [review]

**Comment by lrytz** [comment]
Thanks @retronym - and thanks @ElfoLiNk!

**Comment by SethTisue** [comment]
this made a bunch of projects become green again in the Scala 2.12-on-JDK-10 community build 🎉

**Comment by mkurz** [comment]
Scala 2.12.7 is [due today](https://github.com/scala/scala/milestone/73). However given that Java 11 [will be released next week](http://www.java-countdown.xyz/) and a couple of days later ASM 7.0 [will be released](https://mail.ow2.org/wws/arc/asm/2018-09/msg00001.html) as well would it make sense to postpone the Scala 2.12.7 release for like 10 days to also pull in ASM 7.0?
Otherwise maybe there will be incompatibilities with Java 11 and Scala 2.12.7... And Scala 2.12.8 [is due in February 2019](https://github.com/scala/scala/milestone/76), long time to wait...

**Comment by adriaanm** [comment]
I find it too risky to pull in a major version bump of ASM like that on 2.12. (Let alone that I hope to merge the last PR for 2.12.7 this morning ;-)) 

We'll definitely look into ASM 7 for 2.13.x, and possibly back port to 2.12.x later. Note that we only officially support Java 8 both on 2.12 and 2.13. We will try to improve JDK 11 support for the 2.12 series over time, but I think Feb is a reasonable time frame given that 2.12.0 will soon have been out for two years. 

PS: If you need faster support, we do have commercial offerings for that...

**Comment by mkurz** [comment]
@adriaanm Thanks, I understand.

**Comment by adriaanm** [comment]
Ok, thanks for raising this in any case! I don't follow the ASM list myself, so it's a good reminder we should bump soon at least on 2.13.x :-)

**Comment by SethTisue** [comment]
(https://github.com/scala/community-builds/issues/742 can't catch every possible issue, but it does assure that 2.12.7 can't have a JDK compatibility bug as bad as the one that forced the withdrawal of 2.12.5. so there's that.)

**Comment by mkurz** [comment]
@adriaanm @SethTisue ASM 7.0 beta [released](https://mail.ow2.org/wws/arc/asm/2018-09/msg00009.html)! The final release should happen "[_Problably in a few weeks._](https://mail.ow2.org/wws/arc/asm/2018-09/msg00010.html)". Let's use it in Scala 2.13?

**Comment by mkeskells** [comment]
Asm 7 provides support for java 11. Java 11 is the next lts version after java 8 so a big deal for corporates
It could be fortuitous if the port is not too big for 2.12 8 as well

**Comment by mkurz** [comment]
@mkeskells See [above comment](https://github.com/scala/scala/pull/7089#issuecomment-422318055).

**Comment by mkeskells** [comment]
@mkurz I saw it - that's **why** I made the comment

**Comment by SethTisue** [comment]
is there at least one specific known issue that upgrading to ASM 7 for 2.12.8 would fix...? that would change the benefit vs. risk calculation.

perhaps we could do the upgrade for 2.13.x and then decide later whether known issues justify a backport for 2.12.8

**Comment by mkeskells** [comment]
there isn't a specific issue that we are looking for, and see what issues occur on 2.13 seems like a good plan, and then its an down to seeing which is harder - maintaining the differences and backport/forward-port issues or upgrading

**Comment by mkurz** [comment]
ASM 7 released!
https://mail.ow2.org/wws/arc/asm/2018-10/msg00008.html
http://central.maven.org/maven2/org/ow2/asm/asm/7.0/

Would it be nice to have that in `2.13.0-RC1` :wink:?

**Comment by mkurz** [comment]
Any chance you upgrade to ASM 7 until `2.13.0-RC1`? Is that on your roadmap?

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/7384 :-)

**Comment by mkurz** [comment]
@lrytz Nice! Thanks!

**Comment by xuwei-k** [comment]
> is there at least one specific known issue that upgrading to ASM 7 for 2.12.8 would fix...?

https://github.com/scala/bug/issues/11372

**Pull request merged**
