### PR TITLE
SI-4742 Make -Xcheckinit aware of constants.

### PR DESCRIPTION
**Pull request by retronym**
Members defined as `final val x = <literal>` are given
a ConstantType. The constant is folded into the accessor
method `x`, and the field itself is never initialized.
(Related discussion: SI-4605)

As such, -Xcheckinit spuriously warns when calling that
accessor.

This commit disables the checks for constants.

This will also fix the checkinit build (failure tracked as SI-7839),
which is the victim of this a spurious scolding.

Review by @adriaanm

### CODE REVIEW

**Comment by som-snytt** [comment]
Instead of ducking a bug, you slap it back.

My previous thought about this issue was: is it possible to witness the uninit'd field due to access widening and separate recompilation, or does name mangling ensure that doesn't happen.  I'll have to check again.

Footnote: I didn't see the CI failures; I have no means of subscription and I don't check scala jenkins when I check email in the morning. Should there be a scala-jenkins list for those community members who want to be apprised of build failures?  Even if we can't help fix it, it would alert us not to be rebase on master today.

**Comment by adriaanm** [comment]
I agree the mailing (almost typoed it to mauling) list is a good idea. What to name it!? scala-bot-chatter? scala-infranoise? scala-dev-alerts?

**Comment by adriaanm** [comment]
LGTM!

**Comment by retronym** [comment]
You could route the [RSS feed for failed nightlies](https://scala-webapps.epfl.ch/jenkins/view/2.10.x/job/scala-nightly-main-2.10.x/rssFailed?flavor=rss20) to your inbox with https://www.feedmyinbox.com/. I use read them as RSS with feed.ly.

One thing I've been meaning to add to the build kitteh is @-mentioning the PR submitter on its comments. Then I can filter those ones more easily into my inbox.

**Comment by som-snytt** [comment]
@retronym Interesting info on feeds, thanks. You guys are no mere scalac hackers.
@adriaanm "What to name it!?"  I'm thinking: "The Cat Signal."

**Pull request merged**
