### PR TITLE
SI-7337 Error out on missing -d directory.

### PR DESCRIPTION
**Pull request by retronym**
This check was removed without comment in 3a30af154, the addition
of JSR-223 support for the interpreter.

After this commit, I manually tested that JSR-223 support works.

```
scala> import javax.script._, collection.JavaConverters._; val manager = new ScriptEngineManager; manager.getEngineByName("scala").eval("List(1)")
import javax.script._
import collection.JavaConverters._
manager: javax.script.ScriptEngineManager = javax.script.ScriptEngineManager@4418f61b
res1: Object = List(1)
```

3a30af154 did not include a test case, so I don't know whether I've
broken some other aspect of it. I tried the above as a `run` test,
but hit two problems, one of them seemingly our fault, and the other
a MacOS JDK wrinkle.
1. scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
2. java.lang.UnsatisfiedLinkError: no AppleScriptEngine in java.library.path

I can't find my way to fix these, so JSR-223 remains untested. I don't
think that #2238 was really up to standard; it could handle additional
review, documentation, and testing. It might even be modularized so as
not to pollute the REPL itself.

Review by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
You're right; it's my fault. I'm going to do some reworking of the relevant code.

**Comment by rjolly** [comment]
The problem is that in some restricted environments, scala.reflect.io.Path.apply(jfile) is unable to decide if jfile is a directory, due to a SecurityException. When called from the interpreter, the output dir is in a virtual file system anyway, but the test is made against the real file. I didn't know how to fix it but with commenting it, but I shouldn't have. And in any case I should have put explanations, sorry for that.

**Comment by rjolly** [comment]
This should be fixed by https://github.com/scala/scala/pull/2399

**Comment by retronym** [comment]
Merging this on the grounds that it's just restoring code that shouldn't have been commented out. We can follow up on the more niche issues of JSR-233 support in a Applet environment in #2399

**Pull request merged**
