### PR TITLE
Adds extractors for TypeName, TermName and Modifiers

### PR DESCRIPTION
**Pull request by densh**
This change allows to pattern match over type names, term names and
modifiers. Otherwise it can be quite painful to match over complex trees
as each name or modifiers requires a guard.

This pull request also changes the name of default constructor for term
and type names i.e. TypeName(s) instead of newTermName(s). This is
shorter to type, more consistent with the rest of reflection api and
consistent with the way it will be pattern matched later on.

### CODE REVIEW

**Comment by xeno-by** [comment]
lgtm

**Comment by xeno-by** [comment]
After discussing test failures, we decided that we need to change:
- Tests to use the new APIs
- `showRaw` and `-Yreify-copypaste` to use the new APIs
- Name reification logic

**Comment by densh** [comment]
PLS REBUILD ALL

**Comment by densh** [comment]
Accidentally did wrong rebase. Will reopen it later.

**Pull request closed without merging**
