### PR TITLE
SI-6991 Remove warning message about ClassfileAnnotation ...

### PR DESCRIPTION
**Pull request by soc**
... not being visible at run-time. That's the whole point of a
ClassfileAnnotation, compared to a hypothetical RuntimeAnnotation.

### CODE REVIEW

**Comment by lrytz** [comment]
i think we should improve the warning message instead of removing it. the correct warning would be something like

```
Implementation restriction: Usages of annotations extending ClassfileAnnotation will not be written to the
classfiles in the Java annotation format. Instead, they will only be persisted in the Scala signature
of the classfile. If you want your annotations to be written to the classfile as Java annotations, you
must write the annotation class in Java.
```

**Comment by paulp** [comment]
Unless there is to be some means of suppressing it - is there? - the warning must go. We should not punish people with spurious warnings which they cannot eliminate (least of all ourselves) and if we do want to do that, I can think of better warnings to punish them with.

**Comment by lrytz** [comment]
it's not a spurious warning - there is no reason to extend `ClassfileAnnotation`, unless you want your annotations to be java-serialized; which is unfortunately not implemented.

if we remove the warning we also have to remove the class.

**Comment by paulp** [comment]
It's certainly a spurious warning in the case where I see it 100 times a day: SerialVersionUID.

**Comment by lrytz** [comment]
Well, only since it has been [changed](https://github.com/scala/scala/commit/426744441c22fa3153b7192bead46f8b244c4f12) to extend `ClassfileAnnotation`. Maybe we should introduce a new `ConstantAnnotation` class between `StaticAnnotation` and `ClassfileAnnotation`, which would enforce its arguments to be constant?

**Comment by paulp** [comment]
That would be fine, but I'm not seeing the big picture. Why are we determined to retain a class which cannot usefully be used? Now we're talking about creating another class which is needed solely because we want to use the (otherwise) useless class. Doesn't a more direct solution suggest itself?  Is ClassfileAnnotation strictly a placeholder waiting for someone to implement the missing feature? It has been waiting for 5+ years; that is good evidence that we should pursue a different approach.

**Comment by lrytz** [comment]
As I said before, I'm not against removing it.

**Comment by paulp** [comment]
Okay, let's deprecate it and move the warning into the deprecation message.

**Comment by paulp** [comment]
Also, you said "if we remove the warning we also have to remove the class" which does not mean "I am not against removing the class", and in fact I read it to mean the opposite.

**Comment by soc** [comment]
Imho we just need to sit down an implement the missing functionality. I can have a look at it as soon as I'm happy with the enum situation (which suffers from pretty much the same issues).

There is just no sane reason why we need to live in this bizarre NIH-universe where reasonable expectations are broken left and right.

**Comment by lrytz** [comment]
sorry i was not clear. so i'd also vote for deprecating it and introducing a new `ConstantAnnotation` class to be used with `SerialVersionUID`. if there's an implementation that's obviously also good, but that seems very unlikely be soon (as paul says, it didn't happen in 5+ years, and i don't think it's high enough priority for somebody).

**Comment by soc** [comment]
I think it should be kept, fixed and a `RuntimeAnnotation` should be added, so that our stuff matches with the existing Retention levels.

There is no reason why it can't be fixed, even after 5 years. There are probably tons of things which where broken for a longer time.

As mentioned, I'm interested in improving the situation. I just can't guarantee any time-frame, though, because this is obviously not my full-time job and I also have a full-time masters course which needs a bit of time.

**Comment by paulp** [comment]
"There is no reason why it can't be fixed, even after 5 years. There are probably tons of things which where broken for a longer time."

The second statement is a complete non-sequitur; it might be still be fixable after 500 years, but if nobody fixes it then it won't be fixed. The quantity "five years" is relevant because it informs our estimate of the probability someone will be along to fix it soon. It is a low estimate. I am sure you want to fix it; I too want to fix it; our intentions are not relevant at this point, only code is.

**Comment by soc** [comment]
Regardless of fixing vs. killing annotations, is there any remaining work to be done before this can be merged?

**Comment by lrytz** [comment]
I think this pull request goes in wrong direction, the warning is correctly issued. I agree with removing the warning but only if we also remove `ClassfileAnnotation`.

**Comment by soc** [comment]
No, the warning is wrong. Even if annotations were correctly implemented, the warning is still wrong. A class-file annotation is not supposed to show up at run-time.

**Comment by lrytz** [comment]
OK, we can change the warning text as I originally suggested. But only removing the warning is, in my opinion, not the right thing to do.

**Comment by soc** [comment]
Ok ... so now I'm torn between changing the warning, removing the class, etc.

I think part of the solution should be to make `SerialVersionUID` a source annotation (Java parlance, what did we call that class again? And why exactly do we use a different name for it?).

I just realize that `SerialVersionUID` extending `ClassfileAnnotation` has been wrong from the beginning, because saving `SerialVersionUID` to the class-file is not the point of that annotation, instructing the compiler to do “something special” is.

Is ...
- ... making `SerialVersionUID` a source annotation
- ... fixing the warning the way you suggested

an acceptable solution in your opinion?

**Comment by lrytz** [comment]
What do you mean by "source annotation"? My preferred solution would be to
- remove `ClassfileAnnotation` (and the warning)
- introduce `ConstantAnnotation` do to exactly what `ClassfileAnnotation` does now, but without a warning
- make `SerialVersionUID` extend `ConstantAnnotation`

**Comment by paulp** [comment]
I second lukas's proposal.

**Comment by soc** [comment]
What's with that sudden onslaught of annotation types?
We already have
- `Annotation`
- `StaticAnnotation`

I think `StaticAnnotation` is exactly what we want.

**Comment by lrytz** [comment]
Nope, `StaticAnnotation` marks annotations that are persisted (in the scala signature, aka pickle). But it doesn't require the arguments to be constants, in fact, the arguments are serialized compiler trees. When the annotation is read from bytecode, the argument trees are de-serialized by the UnPickler.

**Comment by soc** [comment]
I think I give up on the `ClassfileAnnotation` part ... I think it is OK to get rid of it until we have a working implementation.

Regarding `StaticAnnotation`: Either enforce the constant rules for `StaticAnnotation` or if this is completely impossible (because tons of people rely on passing arbitrary trees around) introduce a new one, extending `StaticAnnotation`.

But please, no new names. Let's use `SourceAnnotation`. Everyone who used annotations in Java will exactly know what can be done and what cannot be done with such an annotation: http://docs.oracle.com/javase/7/docs/api/java/lang/annotation/RetentionPolicy.html

**Comment by lrytz** [comment]
Changing `StaticAnnotation` is not an option, lots of people depend on having arbitrary trees in annotation arguments.

I'm not sure if we should follow java here. Scala has only two levels: The default (same as SOURCE in java) and persisted (`StaticAnnotation`, same as RUNTIME in java). All persisted annotations are visible in (Scala) reflection (and of course in the compiler). I think this works well and I don't see much reason for adding a third level.

The thing we are discussing here is completely orthogonal: it's is about enforcing constant arguments. It's just a tool we give to annotation writers. They should be able to use it with normal and with static annotations.

Java compatibility (i.e. writing java-compatible annotations), finally, is yet another orthogonal issue. To emit java annotations we'd need to enforce constants, and on top of that we might also want to support the three java persistence levels. The latter could be achieved with meta-annotations. But let's not confuse things here.

**Comment by soc** [comment]
My interest is mainly to prevent having 6 or 7 different classes which do largely the same thing.

For instance, I would prefer not ending up with two different classes where the biggest difference is that one gets saved into a `ScalaSignature` attribute and the other one gets saved into a `Runtime[In]visible` attribute.
Same with having `Annotation` and some `SOURCE` annotation.

**Comment by lrytz** [comment]
We'll have `Annotation`, `StaticAnnotation`, `TypeConstraint` and `ConstantAnnotation`. Seems good to me.

If we ever get to do the java compat thing we can check what's the best way to reuse existing stuff, but that should not influence the current Scala design.

**Comment by JamesIry** [comment]
ping @soc, @lrytz, @paulp. Any final decision on this PR?

**Comment by lrytz** [comment]
i vote for closing and creating a ticket.

**Comment by lrytz** [comment]
ups, closed it by clicking wrong button.

**Comment by JamesIry** [comment]
That's one way to vote.

**Comment by paulp** [comment]
I still think we should do exactly what lukas said a ways up the page:

```
remove ClassfileAnnotation (and the warning)
introduce ConstantAnnotation do to exactly what ClassfileAnnotation does now, but without a warning
make SerialVersionUID extend ConstantAnnotation
```

and leave everything else for future squabbles. I really do not care to see that warning another billion times.

**Comment by adriaanm** [comment]
please squabble here: https://issues.scala-lang.org/browse/SI-7041

**Pull request closed without merging**
