### PR TITLE
Refactorings in GenBCode, remove Tracked

### PR DESCRIPTION
**Pull request by lrytz**
Note 1: the first bunch of commits in this PR (the ones from June 22) is being reviewed in a separate PR (#3826), ignore them here.

Note 2: the commits marked [squash-after-review] don't build (except for the last). They exist to make reviewing easier, I'll squash them into one before merging.

For the big commit ("Remove Tracked, ..."), I'll add some comments to the diff on GitHub.

Review by @gkossakowski

[`-Ybackend:GenBCode` build succeeded](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1255/)

### CODE REVIEW

**Comment by gkossakowski** [comment]
What is the motivation for moving the code around? Is it to enable the last commit?

**Comment by lrytz** [comment]
> What is the motivation for moving the code around? Is it to enable the last commit?

What code are you referring to? In case you haven't, please take a look at the PR message, and at the individual commit messages before reviewing.

**Comment by gkossakowski** [comment]
I was referring to all commits marked [squash-after-review]. It's great you split the diff into easier to review chunks but I'm still missing the big picture hence my question.

I did read both PR and commit messages. I decided to go wholesale with the review because I found earlier commits to be interesting too.

**Comment by lrytz** [comment]
> I'm still missing the big picture

You mean why do the refactoring at all? Mainly to have the definitions global-independent representations in a place where no global is available. It's to have less mutability, less nulls and more precise types for the representations of classType-information and inner class information.

**Comment by lrytz** [comment]
@gkossakowski this PR will require a rebase, the first bunch of commits are obsolete now, see #3826. But I'll keep it as-is for now, in order not to lose the comments we already have.

**Comment by gkossakowski** [comment]
The  1b750c1 is large enough that I can't review with one hand in a cast. I'll schedule a video call with @lrytz.

**Comment by gkossakowski** [comment]
I finished reviewing this PR. All feedback is in the comments.

**Pull request closed without merging**
