### PR TITLE
Fix SI-8217

### PR DESCRIPTION
**Pull request by Blaisorblade**
Realign the compiler with the proposed spec update: scala/scala-dist#127

I know I'll need to rewrite the commit message.

Review by @retronym.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
@retronym, ping?

**Comment by adriaanm** [comment]
Sorry about the lack of feedback, we've been super-busy. To begin with, this will need a commit message that explains the fix. What was wrong, why, and how is it fixed now. 
Also, the title should be something like `SI-8217 allow abstract type members in objects`. While you're at it, would be good to make our tests more systematic: what are the possible nestings / valid combinations? Does this suddenly allow methods with undefined type members (yep...).

This is a pretty fundamental part of the compiler, so please thread lightly. I tried it out with [pr_dist](https://github.com/adriaanm/binfu/blob/master/scafu.sh#L48):

```
$ pr_dist 3442
[info] Loading global plugins from /Users/adriaan/.sbt/0.13/plugins
....
[info]  [SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.0-61b5614-SNAPSHOT!scala-reflect.jar (4204ms)
[info] Done updating.
[success] Total time: 50 s, completed Feb 15, 2014 3:24:43 PM
To run the repl for #3442:
/Users/adriaan/git/scala-dist/target/universal/stage/bin/scala

$ /Users/adriaan/git/scala-dist/target/universal/stage/bin/scala
Welcome to Scala version 2.11.0-61b5614-SNAPSHOT (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_65).
Type in expressions to have them evaluated.
Type :help for more information.

scala> def foo = {type T }
foo: Unit
```

**Comment by Blaisorblade** [comment]
Point taken on the commit messages. And on the tests.

>  def foo = {type T }

I assume you mean that's wrong, right? It certainly was not intentional. I dare say it might be useful to encode existentials — such variables exist in pattern matches. But somehow, neither vObj nor DOT seems to allow for such constructions (unless you can encode methods in the vObj-style in DOT) — vObj forbids abstract types in concrete objects altogether. Moreover, the rest of the compiler wasn't designed to deal with such types.

Hence, for now I'll try to forbid this construct.

**Comment by adriaanm** [comment]
Yep, you could argue they should be allowed, but I'd prefer not to go there. One way to look at this is that type members give you a nicer way of opening an existential and naming the resulting skolems, but, again, I don't think we should go there. The difference with an object is that they are stable values, and they can already inherit abtract type members, so we should be consistent.

**Comment by Blaisorblade** [comment]
Also, "this is forbidden by core calculi" seems enough for avoiding a feature (even though it might sound safe).

For avoiding the behavior, I suspect that one should just forbid abstract types for non-classes, following the current logic:

```
else if (!symbolAllowsDeferred && ownerRequiresConcrete || sym.isAbstractType && !sym.owner.isClass)
          fail(AbstractVar)
```

This forbids your example and allows types in objects, but it's a bit ugly, so I'll try to make this nicer. (And run the other tests, and look for new ones).

**Comment by Blaisorblade** [comment]
Closing for now. I suppose this shouldn't go in for 2.11.0-RC1 anyway, especially given the need for more extensive testing.

**Pull request closed without merging**
