### PR TITLE
SI-6188 ICodeReader notes exception handlers, Inliner takes them into account

### PR DESCRIPTION
**Pull request by phaller**
Backport of bugfix of SI-6188 (part of #1059) to 2.9.x.

Note: this backport is required for the backport of SIP-14 (futures) to 2.9.x (#1745).

Review by @magarciaEPFL

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
The proposed backport should work as-is (it doesn't rely on previous fixes itself). I'll look for any merge-related problems.

**Comment by phaller** [comment]
Great, thanks a lot, Miguel!

**Comment by magarciaEPFL** [comment]
Manually cracted backport of SI-6188:
  https://github.com/magarciaEPFL/scala/commit/ddf8aa2ba662f6ac5cc45c91f81379c2b9a0f4ab

**Comment by retronym** [comment]
As discussed, another way to fix this would be to `@noinline` selected methods in `Try`. But it would best get to the bottom of the stability problems.

**Comment by magarciaEPFL** [comment]
`@noinline` is an equally valid solution. Regarding stability, I can't reproduce yet because after applying the manually crafted backport mentioned above (_not_ this PR) `ant test.stability` passes OK. I'm running the nightly.

BTW, is a backport of SI-6157 necessary too? I haven't included that in the manually crafted backport.

**Comment by phaller** [comment]
Good news that the manually-crafted backport passes the stability test.

A backport of SI-6157 does not seem to be necessary. Therefore, I suggest you create a new pull request with the manually-crafted backport, and if all goes well, I can base the SIP-14 backport off of that. We could then close this pull request.

**Comment by magarciaEPFL** [comment]
PR #1755 was ok with `ant nightly`. No stability problems in sight.

**Pull request closed without merging**
