### PR TITLE
Fix reentrancy issue in LongMap/AnyRefMap.getOrElseUpdate

### LINKED ISSUE #13048: getOrElseUpdate does not behave as it should on mutable.LongMap
Here's a self-contained example that shows the incorrect behavior:

```scala
import scala.collection.mutable
import scala.collection.immutable.SortedSet
import scala.util.Random

class Bug(m: mutable.Map[Long, Unit]):
   def test(useGetOrElseUpdate: Boolean): Set[Long] =
      val rand = Random(1)
      def n()  = rand.nextInt(30)

      def f(d: Int): Unit =
         if d > 0 then
            g(n(), d - 1)
            g(n(), d - 1)

      def g1(x: Long, d: Int): Unit = m.getOrElseUpdate(x, f(d)) // use getOrElseUpdate

      def g2(x: Long, d: Int): Unit = if !m.contains(x) then m(x) = f(d) // do it as in MapOps

      lazy val g = if useGetOrElseUpdate then g1 else g2

      f(10)
      m.keys.to(SortedSet)

@main def RunTest(): Unit =
   println(Bug(mutable.Map.empty[Long, Unit]).test(useGetOrElseUpdate = true))
   println(Bug(mutable.LongMap.empty[Unit]).test(useGetOrElseUpdate = true))
   println()
   println(Bug(mutable.Map.empty[Long, Unit]).test(useGetOrElseUpdate = false))
   println(Bug(mutable.LongMap.empty[Unit]).test(useGetOrElseUpdate = false))
```
(I use Scala 3 syntax but this is a Scala 2 library issue).
The output is:
```
TreeSet(0, 2, 3, 4, 6, 7, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 25, 26, 27, 28, 29)
TreeSet(0, 2, 3, 4, 6, 7, 9, 10, 12, 13, 14, 15, 16, 19, 20, 23, 25, 26, 27, 28, 29)

TreeSet(0, 2, 3, 4, 6, 7, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 25, 26, 27, 28, 29)
TreeSet(0, 2, 3, 4, 6, 7, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 25, 26, 27, 28, 29)
```
Notice how `mutable.Map` and `mutable.LongMap` produce different outputs when `getOrElseUpdate` is used. When not used, it is replaced with an implementation similar to what's in `MapOps` (I use `contains` instead of `get` because I ignore values, but the behavior is the same with `get`).

I believe this is a bug because `LongMap#getOrElseUpdate` should behave as the default `MapOps` implementation and because `LongMap[Unit]` should behave like `Map[Long,Unit]` (in a single-threaded context).

One could argue that `getOrElseUpdate` makes no such guarantees when the by-value code modifies the map, but:

- the documentation is silent about that;
- it's not an unreasonable scenario (my actual application is a memoized recursive function, without randomness);
- there is a comment inside the `LongMap#getOrElseUpdate` source that says:
    ```
        // It is possible that the default value computation was side-effecting
        // Our hash table may have resized or even contain what we want now
        // (but if it does, we'll replace it)
    ```
    which suggests that an effort was made to handle this situation.

I'm using Scala 3.5.2 (which seems to be using the 2.13.14 collections) in my experiments.

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/bug/issues/13048

### CODE REVIEW

**Comment by SethTisue** [comment]
@scala/collections

**Comment by som-snytt** [comment]
I was going to say LGTM, but thought it would be nice if there were a cheap test for "dirty".

Now I see that this issue has a long history. (Edit: where these issues are previously raised)

The previous test is in https://github.com/scala/scala/commit/f97e2d42eb211d429b27f79fe993bf48c92e9740

`SetMapConsistencyTest` because of the Ichoran itch for testing across implementations.

There is discussion for `HashMap` at
https://github.com/scala/scala/pull/5719
https://github.com/scala/bug/issues/10187

where it's considered whether to specify "don't do that" (per Java `computeIfAbsent`). (But Java also pinky-swears to throw `ConcurrentModification`. I remember Nth added mutation checks somewhere.)

Seth concurs on the previous ticket https://github.com/scala/bug/issues/8213 that it is `wontfix`.

Why should everyone suffer for the bad behavior of a few? Or are we waiting for Caprese to contain the issue?

**Comment by lrytz** [comment]
Thanks, I didn't dig into the history. I still see it as a bug that should be fixed.

`seekEntryOrOpen` seems cheap, except for the `equals` call in `AnyRefMap`. I added a "dirty" check which I believe is correct.

**Comment by SethTisue** [comment]
note that I don't actually _object_ to fixing it if it can be fixed without contortions :-)

**Comment by lrytz** [comment]
This could go in 2.13.16, maybe @som-snytt can ✅it

**Review by som-snytt — APPROVED** [review]
Includes excellent pluralizations. It would be nice if lrytz finally signed the CLA.

**Comment by lrytz** [comment]
> It would be nice if lrytz finally signed the CLA

Just adding a few more commits before I sue EPFL.

**Comment by SethTisue** [comment]
Knives out!

**Pull request merged**
