### PR TITLE
Annotate as inline more consistently in Option

### PR DESCRIPTION
**Pull request by NthPortal**
Annotate all methods taking a `Function` of some sort
(by-name, partial, or regular) as `@inline`.

Annotate all methods consisting only of a boolean negation
as `@inline`.

### CODE REVIEW

**Comment by SethTisue** [comment]
Do we have any evidence that this will actually ever affect emitted bytecode? On the one hand, sprinkling `@inline` around the standard library probably can't hurt, but I'm not sure we should do it unless we're pretty sure it actually helps. (Especially if this PR is the first of a planned series.)

At https://www.lightbend.com/blog/scala-inliner-optimizer, @lrytz says straight-up:

> In general, our recommendation is to avoid using these annotations [...] the annotations are well-intended and benign, but in reality unnecessary.

and suggests we just trust the inliner heuristics.

What's the justification for disobeying our own advice in the case of `Option`?

**Comment by som-snytt** [comment]
I had the same question but was too embarrassed to ask, so I waited for a senior member of the team to chime in.

**Comment by NthPortal** [comment]
> Especially if this PR is the first of a planned series.

it's not

> What's the justification for disobeying our own advice in the case of `Option`?

the motivation is twofold:

1. consistency. most of the other methods are already annotated as such, so it's consistent to annotate similar members (e.g. if `flatMap` is annotated, why not `flatten`?). this doesn't particularly apply to `isDefined` and `nonEmpty`.
2. `-Yopt-inline-heuristic` allows you to specify the heuristic the inliner uses, one of which is `at-inline-annotated`. as its name suggests, it *only* inlines definitions or callsites annotated with `@inline`. one might want to inline from the scala library using that heuristic, in order to benefit from inlining (primarily) function literals and by-name parameters, and that would be much safer than inlining from the scala library using the default heuristic.

it's not actually clear to me that our advice is good in light of the `at-inline-annotated` heuristic. I suspect the advice predates that heuristic (and perhaps the `-Yopt-inline-heuristic` option as well)

**Comment by lrytz** [comment]
>     2\. one might want to inline from the scala library using that heuristic

I can see that, but I beleive there is no system whatsoever behind what is currently annotated `@inline` in the standard library.

Anecdotal, but still: at some point I removed all `@inline` annotations from the compiler and standard library, and compiler performance was unchanged.


>     2\. that would be much safer than inlining from the scala library using the default heuristic

Can you share your thoughts or observations when the default heuristic is causing issues?


> I suspect the advice predates that heuristic

You mean the advice not to use `@inline`? No, I wrote that with the current state of the optimizer in mind. But it's only my advice, not more widely supported.

**Comment by NthPortal** [comment]
> I beleive there is no system whatsoever behind what is currently annotated @inline in the standard library.

while it is certainly used quite inconsistently throughout the standard library, there are a few patterns I've noticed:

- symbolic aliases tend to be annotated `@inline`
- utilities in `Predef`, especially those taking function or by-name arguments, tend to be annotated `@inline`
- `Option` is mostly annotated `@inline` (idk if this is big enough to be called a "pattern")

> Can you share your thoughts or observations when the default heuristic is causing issues?

absolutely. as you said in the blog post Seth linked,

> Don’t inline from your dependencies when publishing a library, it breaks binary compatibility

at some point before before reading that post, I enabled inlining from everywhere (with the default heuristic) in the build for one of our applications at work, that also in some ways acts as a library. everything was fine for a while, and we started importing some of the modules into ammonite scripts. but at some point, the version of scala used in our application build desynced from the one that ammonite used, and one of the scripts started crashing at runtime. since we were treating the application modules as libraries, and we didn't follow the advice you gave of not inlining from dependencies, we had bincompat issues. after that, I changed the application build to only inline from its base package (`-opt-inline-from:com.company.appname.**`).

I have not attempted to enable inlining from everywhere with the `at-inline-annotated` heuristic in any of my projects, both because I only learned of it recently, and because it would significantly reduce the number of potential inlining sites and (I suspect) worsen optimisation within that project's own code. however, I suspect that inlining from dependencies using the `at-inline-annotated` heuristic would be relatively safe from a bincompat perspective (at least in the stdlib); certainly that is my impression from what I've seen of the use of `@inline`. that's also my motivation for wanting support for multiple heuristics.

**Comment by lrytz** [comment]
Another point I can make is that the inliner heuristic changed over time, while the `@inline` annotations in the standard library didn't. In particular, aliases/forwarders and higher-order methods are inlined by the default heuristic.

So changing the `@inline` in the standard library would basically only affect what happens under `at-inline-annotated`.

I like your idea of providing a way to enable the inliner without breaking binary compatibility across minor/patch versions. `Option` is a good example, all of the `@inline` annotated methods are implemented only using public API, so it would be safe.

However, the current `@inline` annotations were not written with this in mind, neither in the standard library nor in other libraries, so it's not safe to just go ahead and turn this on.

We could build some tooling, e.g.,
  - check implementations of `@inline` annotated methods
  - make the compiler suggest methods where the annotation would make sense
  - add a parameter to `@inline` to indicate when methods that don't break bin compat

**Comment by NthPortal** [comment]
I might try to have a look through all the public methods annotated `@inline` in the standard library and see if they all happen to only call public methods

**Comment by dwijnand** [comment]
Parking in long term storage, for now..

**Pull request closed without merging**
