### PR TITLE
Tweak messages on REPL paste

### PR DESCRIPTION
**Pull request by som-snytt**
Follow-up https://github.com/scala/scala/pull/9350#issuecomment-1690738823

Improve messages incrementally, and remove some extra newlines.

### CODE REVIEW

**Comment by som-snytt** [comment]
For future reference, I was fooled by the clever REPL partests which use the `ReplTest` `code` string as the session text instead of the check file. Such a test should verify that there is no check file. I did not notice `git status` that the check file was local only, so when I `partest --update-check`, the test passed but the check file was not checked in and `git diff` is not sufficient. Notice I failed to `partest --realeasy`, which is on me.

**Review by SethTisue — APPROVED** [review]
I will suppress my humor-police urge to suggest that "nothing pasted, nothing gained" has expired and it's time to rotate in a new joke, or none.

`\n//` is a three-armed mutant drowning

**Comment by som-snytt** [comment]
I don't disagree. I think it says `Improve messages incrementally` because every tweak is fraught. Why does it use an ellipsis instead of a semicolon?

In third grade, a poet visited class, and a structured exercise had me write, "I opened myself up and ................", which the poet read aloud as, "Just a lot of dots." I think I intended an infinite ellipsis because I would be dead.

**Comment by som-snytt** [comment]
Rebased and zapped the last jokey vibe in all of REPLdom.

**Comment by som-snytt** [comment]
"Java paste -- now in cans!"

**Comment by som-snytt** [comment]
rebased to merge greenies

**Comment by SethTisue** [comment]
Why do some of the checkfiles say "now interpreting" and some say "now compiling with scalac"?

**Comment by som-snytt** [comment]
It says "compiling" for so-called "raw" and "interpreting" otherwise, for regular wrapped code.

It's the same as interpretive dance.

**Pull request merged**
