### PR TITLE
cleanup of old stuff from the GenJVM era

### PR DESCRIPTION
**Pull request by magarciaEPFL**
review by @JamesIry or @gkossakowski

### CODE REVIEW

**Comment by gkossakowski** [comment]
Once comment about magic number is added this is good to go. I know that the comment wasn't there before and the magic number was but since we are touching this piece of code it would be good to document it. Also, it would be good to explain what `fitsInOneString` is supposed to be used for. It's not really clear to me.

**Comment by magarciaEPFL** [comment]
A second opinion is welcome, but looks like the Looks Good conditions have been met.

**Comment by paulp** [comment]
LGTM2.

**Comment by gkossakowski** [comment]
LGTM. Thanks a lot for the comment! I learnt something from it, actually. :+1:

**Pull request merged**
