### PR TITLE
SI-7251, compiler crash with $.

### PR DESCRIPTION
**Pull request by paulp**
We don't need to assert our way out of tight spots, we can issue
an error. Or so I once thought.

It turns out lots of assertions have been disappearing before
being heard thanks to "case t: Throwable". Under such conditions,
a failed assertion is a no-op, but an error is an error.

The crash associated with SI-7251 is best avoided by removing the
assertion, which allows an error to be issued in the normal course
of events.

In the course of trying to figure out the above, I cleaned up
ClassfileParser somewhat.

### CODE REVIEW

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
@adriaanm PLS HELP KILL KITTEN

**Comment by paulp** [comment]
Oh, confusingly it's still "merge with caution" at the bottom but "good to merge" at the top.

**Comment by retronym** [comment]
PLS SYNCH

**Comment by paulp** [comment]
Review by anyone with unbroken wrists: @adriaanm @retronym @JamesIry ?

**Comment by paulp** [comment]
Hey @adriaanm @retronym @JamesIry this PR took me like an entire day, since it's the one where catch-everything caught the failing assertion, but changing it to an error broke it. Throw me a review bone.

**Comment by adriaanm** [comment]
So it looks like the fix amounts to removal of the assert, and the rest of the patch is a refactoring?

**Comment by paulp** [comment]
"Refactoring" is such a neutral word. How about "Betterizing."

Yes, that's almost true, except for this fix which I had thought I noted somewhere but maybe that part got cleaved.

```
private def currentIsTopLevel = !(currentClass.decodedName containsChar '$')
```

Checking the decodedName rather than the name means that a top-level class like :: will be considered top level.

**Comment by som-snytt** [comment]
I liked that line, and would have ventured the desired acronym, except I didn't understand it.

I'm aware that the org invites reviews from the community, and I'll try to step up to the plate.  That's a baseball metaphor, nothing to do with restaurants.

I just had a discussion with my little one about "forgive us our debts" (as they say the pater noster in presbyterian circles) instead of "trespasses" (as I grew up with).  So I would invite a discussion about synonyms for technical debt.

**Comment by adriaanm** [comment]
It all looks better to me, for sure. The decodedName v toString part of the patch makes sense, but not sure I grasp the full significance of why we were using toString in the first place.

**Comment by paulp** [comment]
because ("Foo": TypeName) != ("Foo": TermName) and because Name has no abstraction integrity (half of them are made by jumbled name/string concatenation to termname to typename) people punt and compare strings.

**Comment by adriaanm** [comment]
LGTM

**Comment by adriaanm** [comment]
... and this is why I wasn't a fan of refactoring: the merge piper demands his dues. Please open a PR on master that merges your PR into master -- my vision is going blurry catching up with our merge backlog in https://github.com/adriaanm/scala/commits/merge-2.10.x

**Comment by paulp** [comment]
No problem, I can pull my weight.

**Comment by adriaanm** [comment]
Thanks. Piper happy.

**Pull request merged**
