### PR TITLE
SI-7568 Adding Serializable to ResizableArrayAccess inner class

### PR DESCRIPTION
**Pull request by rjfwhite**
Serialization troubles were caused by an inner class not being Serializable. 

I'd like to include a test for this, some guidance would be appreciated.

### CODE REVIEW

**Comment by rjfwhite** [comment]
CLA has been signed.

**Comment by adriaanm** [comment]
Thanks, @rjfwhite! A test would indeed by awesome :-)

I'd recommend junit, something along the lines of https://github.com/scala/scala/blob/master/test/junit/scala/collection/TraversableOnceTest.scala, perhaps.

Use `ant test.junit` to run the junit tests. It's pretty fast.

**Comment by rjfwhite** [comment]
Thanks for the help :) 

Candidate test has been added

**Comment by adriaanm** [comment]
LGTM! Congrats on your first Scala PR, @rjfwhite!

**Comment by rjfwhite** [comment]
Awesome, thanks!

**Pull request merged**
