### PR TITLE
Ultimate reflection pull request

### PR DESCRIPTION
**Pull request by xeno-by**
Unifies https://github.com/scala/scala/pull/1017, https://github.com/scala/scala/pull/1031 and https://github.com/scala/scala/pull/1035.

All of those were LGTM'd by Martin, but couldn't be merged cleanly w.r.t each other. So now we only have to see that their superposition passes all the tests.

### CODE REVIEW

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/277/console

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@jsuereth The kitteh has failed with some spurious errors, but scala-checkin-manual linked above has succeeded. Let's merge?

**Comment by jsuereth** [comment]
The kitteh appears dead, or Jenkins APi is.

Did you run a manual checkpos build?   If not @dragos will beat me with the "failure to test" stick.  

Note:   I'm technically on vacation now but have github notifications on high alert since I'm the merge guy this week.   Ping my email if I miss something.

**Comment by xeno-by** [comment]
I don't know how to run checkpos manually - it seems that there's only scala-checkin-manual, but not scala-checkpos-manual.

**Comment by hubertp** [comment]
I don't think there is a manual rangepos checkin job. To build it manually do "-Dscalac.args=-Yrangepos\"". And please do not merge before rangepos build is ok - I am usually the one responsible for fixing it and I will refuse to do it when it happens.

**Comment by xeno-by** [comment]
https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/282/console

**Comment by xeno-by** [comment]
```
...
  [echo]       scalac args: -Yreify-copypaste -Yrangepos  -optimise
...
Finished: SUCCESS
```

Success! Allrighty, go-go merge!!

**Comment by hubertp** [comment]
Actually this was only half of the truth: -Dpartest.scalac_opts="-Yrangepos" is also needed (for future reference).

**Comment by xeno-by** [comment]
Oh sorry didn't know

**Pull request merged**
