### PR TITLE
[ROUNDLY REJECTED] Pre-SIP: Take omitted Unit for procedure syntax

### PR DESCRIPTION
**Pull request by som-snytt**
The weakness of procedure syntax was that
    it is easy to accidentally leave out an
    equals sign, especially as a beginner.
    
    The strength of procedure syntax was that
    it was a strong visual signal for an
    experienced eye that the method is Unit-valued.
    
    This commit takes an omitted result type
    as explicit Unit: `def f(): = ()`.
    
    The extra colon over an inferred result type
    means that it is not an easy beginner trap,
    but it is also pithy and easy to spot for
    experienced eyes.
    
    For aesthetics, also accept `:=` for this
    idiom, since an identifier is not otherwise
    valid in this position.
    
    This identifier was once proposed as
    the Ur-assignment operator, so this syntax
    has the added benefit of triggering one's
    spidey sense, or Speyside sense, depending
    on the time of day. It is also familiar
    from sbt in a different usage.

### CODE REVIEW

**Comment by edmundnoble** [comment]
Does this have an associated SIP?

**Comment by som-snytt** [comment]
@edmundnoble You mean as in "Sucks Imagination from Project"? No, this is a SPOCK, Scala Proof of Code Konzept. In the unlikely event that folks want to muck with syntax (even to the extent of this elegant idea) in service of procedures, I don't mind writing a document, but I'd need a few days' lead time to work up some puns.

Edit: oh wait, "Ur-Ass" is probably enough bun pun for one SIP.

**Comment by Ichoran** [comment]
I think this is strictly worse than procedure syntax: it is less brief, but no less weird or prone to confusion.

We could potentially allow the empty tuple/single inhabitant of `Unit` to be used instead of `Unit`, though, since logically `()` (the 0-arity tuple) should be usable as a return value.

```
def wistful(): () = println("I still miss procedure syntax.")
```

**Comment by som-snytt** [comment]
Just to be clear, this proposal is a compromise so that we're not stuck writing `def f(): Unit =`. It's assumed that procedure syntax is history and not just put behind a language flag. I think using `()` as a synonym for `Unit` type has been floated elsewhere; of course that is even less brief.

**Comment by SethTisue** [comment]
> Does this have an associated SIP?

Yes in the sense that it's under the umbrella of https://contributors.scala-lang.org/t/proposal-to-remove-procedure-syntax/2143/96 . This PR won't move forward without approval by the SIP committee.

**Comment by lrytz** [comment]
For me, the two possible paths forward are keeping the current procedure syntax, or removing it. Adding another syntax can cause more confustion, work for the community, etc.

**Comment by adriaanm** [comment]
We owe you a Speyside (sip, don't shoot). Let's keep the procedure syntax decision binary, though.

**Pull request closed without merging**
