### PR TITLE
SI-6388 Remove deprecated items scheduled for 2.11

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by jsuereth** [comment]
Appears to be valid failure....

**Comment by soc** [comment]
Yes, will fix it, just pretty busy at the moment.

**Comment by soc** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
@jsuereth I think this should be good to go ...

**Comment by adriaanm** [comment]
LGTM

Thanks for the cleanup, @soc!

/cc @axel22 for library changes, @jsuereth fyi

**Comment by soc** [comment]
This commit removes items for 2.10, not 2.11. The title is wrong.

**Pull request merged**
