### PR TITLE
Fix performance bug in GenASM.

### PR DESCRIPTION
**Pull request by paulp**
It was going through missingHook looking for android classes
every time something was compiled, which means four failing
missingHook calls for every line in the repl.

### CODE REVIEW

**Comment by jsuereth** [comment]
Review by?

**Comment by paulp** [comment]
Review by @jsuereth

**Comment by jsuereth** [comment]
LGTM

**Comment by paulp** [comment]
Oh wonderful, all the logging output is printed unconditionally. Is this what eugene tried to patch and was rejected?

**Comment by adriaanm** [comment]
I'm more than happy to merge #1527 wherever he wants it, just not in 2.10.0-wip.

Reflection is experimental, so I don't see how bugs there can be blockers during an RC.

**Comment by paulp** [comment]
I wasn't demanding an explanation, just asking the question you see.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
