### PR TITLE
SI-9709 Change -Yclasspath default to flat

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by lrytz** [comment]
Started a community build: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/347/

**Comment by soc** [comment]
And just when I thought this would be easy ...

```
    [junit] Running scala.tools.nsc.interpreter.CompletionTest
    [junit] Tests run: 12, Failures: 12, Errors: 0, Skipped: 0, Time elapsed: 7.247 sec
```

**Comment by retronym** [comment]
@soc I'll adapt the REPL presentation compiler before we remove the recursive setting. For now, just make it explicitly use the old implementation with:

``` diff
diff --git a/src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala b/src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
index 3a2177a..539cf01 100644
--- a/src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
+++ b/src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
@@ -61,6 +61,7 @@ trait PresentationCompilation {
       val s = new Settings(_ => () /* ignores "bad option -nc" errors, etc */)
       s.processArguments(global.settings.recreateArgs, processAll = false)
       s.YpresentationAnyThread.value = true
+      s.YclasspathImpl.value = scala.tools.nsc.settings.ClassPathRepresentationType.Recursive
       s
     }
     val storeReporter: StoreReporter = new StoreReporter
```

**Comment by retronym** [comment]
You might need to also do this for the global instance in the REPL itself, too, in order to support the `:require` command, which calls `addUrlsToClassPath`, `extendCompilerClassPath`:

``` scala
  /** Extend classpath of `platform` and rescan updated packages. */
  def extendCompilerClassPath(urls: URL*): Unit = {
    if (settings.YclasspathImpl.value == ClassPathRepresentationType.Flat)
      throw new UnsupportedOperationException("Flat classpath doesn't support extending the compiler classpath")

    val newClassPath = platform.classPath.mergeUrlsIntoClassPath(urls: _*)
    platform.currentClassPath = Some(newClassPath)
    // Reload all specified jars into this compiler instance
    invalidateClassPathEntries(urls.map(_.getPath): _*)
  }

```

**Comment by lrytz** [comment]
@soc fyi, i'm looking into this; if you plan to work on it please coordinate with me!

**Comment by soc** [comment]
@lrytz Feel free to take it!

**Comment by lrytz** [comment]
working on it in #5048

**Pull request closed without merging**
