### PR TITLE
SI-4664 Make scala.util.Random Serializable

### PR DESCRIPTION
**Pull request by jedesah**
review by @phaller

### CODE REVIEW

**Comment by phaller** [comment]
Could you please add a test? You could use either `test/files/jvm/serialization.scala` or `test/files/jvm/serialization-new.scala`. Thanks.

**Comment by jedesah** [comment]
What's up with Jenkins? I recall it ran the test suite when I uploaded a new commit for review as part of a pull request.

Not that I didn't run the test suite locally...

**Comment by paulp** [comment]
When the date is in the past (notice you added some commits "9 days ago") jenkins doesn't notice.

**Comment by jedesah** [comment]
I am not sure I understand. It does say added some commits 9 days ago, but it also says on my latest commit that it was authored 12 hours ago which is correct.

And I far as I know there is nothing special with my commit. I didn't rewrite history or anything like that. I just pushed up my latest commit.

**Comment by retronym** [comment]
I believe the build bot is out of action and its maintainer, @jsuereth, is in transit.

**Comment by paulp** [comment]
You didn't push -f ? That is not consistent with my experience. When I push new commits without -f, it says I added some commits "just now", and it distinguishes between the actually newly added ones and the preexisting ones. When I "push -f" which does rewrite history, it says I "added some commits", supposedly at the original time/date, and shows all the commits in the branch as having been added. The behavior here tracks the "push -f" pattern perfectly.

**Comment by jedesah** [comment]
I'm pretty sure I didn't use -f but who knows.

**Comment by adriaanm** [comment]
okay, test case added -- LGTM, then

**Pull request merged**
