### PR TITLE
SI-8677 Duration: Zero - Inf should be MinusInf

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fixes #8677.
(Extra tests still missing).
To be sure, this PR is just to get the "obvious" change built and run through basic tests.

### CODE REVIEW

**Comment by retronym** [comment]
So far, so good!

Please resubmit when you get a chance to add the tests.

/cc @Ichoran

**Comment by Ichoran** [comment]
I guess Infinity - Infinity = -Infinity?  This is mathematically questionable, but does it deliver the least surprise?  If yes, then it's the thing to do.  (Certainly it's good to fix the sign!)

**Comment by Blaisorblade** [comment]
@Ichoran, the pull request only affects f - i where f: FiniteDuration and i.isFinite = False. See https://github.com/scala/scala/pull/3843/files#diff-06098254e7547f6ba2255191f3e7e565L54. I've named you reviewer on #3843, hope it's OK.

**Comment by Ichoran** [comment]
My mistake.  LGTM

**Pull request closed without merging**
