### PR TITLE
Fix typo in Scaladoc

### PR DESCRIPTION
**Pull request by greenrd**

### CODE REVIEW

**Comment by cvogt** [comment]
LGTM, better commit message would have been
fixed typo in GenTraversableLike.groupBy doc comment

**Comment by huitseeker** [comment]
LGTM
@cvogt as per the [guidelines](https://github.com/scala/scala/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages) it's best to keep commit message's first line in active voice and <60 chars

**Comment by cvogt** [comment]
@huitseeker The guidelines says <70 lines and highlights. "It should be possible to fully understand what the commit does by just reading this single line.". (like the one I proposed ;)).

**Comment by soc** [comment]
Less than 50 characters is actually correct *runs for cover*

**Comment by huitseeker** [comment]
[Valid](https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala/9/) w.r.t. Scala-IDE PR validation.

**Comment by adriaanm** [comment]
Welcome, @greenrd! Could you please sign the http://typesafe.com/contribute/cla/scala -- it only takes a minute.

Regarding the commit message, the active voice is preferred.
Personally, I'd write "[doc] Fix typo in GenTraversableLike.groupBy", but I'm happy to merge as soon as the CLA is signed.

**Comment by greenrd** [comment]
Yes, I have already signed the CLA.

**Comment by adriaanm** [comment]
Sorry, we ask that you sign the Scala CLA, which you haven't signed yet according to the json api: http://typesafe.com/contribute/cla/scala/check/greenrd

**Comment by greenrd** [comment]
Ah, sorry, I missed that there were two different CLAs. I've signed it now.

**Comment by adriaanm** [comment]
Thanks a lot. Very sorry to make you jump through all these hoops. Really appreciate it!

**Pull request merged**
