### PR TITLE
Compiler speed optimizations take 2

### PR DESCRIPTION
**Pull request by odersky**
I rebased everything on latest 2.10.x.

### CODE REVIEW

**Comment by retronym** [comment]
I wonder if a less-haste-more-speed approach would be prudent.

``` scala
(tree @splitCases) match {
  case x: Case1 =>
     ...  //  compiled to a separate method
}
```

Pertinent: [[scala-internals] starting to optimize the virtualizing pattern matcher](https://groups.google.com/d/msg/scala-internals/yItqW9Ybpvc/sSspwyNVG4QJ)

> it might be interesting to consider ways to split the generated code into smaller methods (as is done for guards at the moment.) AFAIK, large methods are less likely to receive attention from hotspot.
> 
> Earlier this year, Alexander converted [1] the pattern matches that implements type conformance in the IDEA plugin to polymorphic dispatch and saw big performance improvement. My hunch was that breaking it into smaller methods might have been the telling factor, rather than the difference between dispatching based on instanceOf vs invokeVirtual.

**Comment by retronym** [comment]
A small contribution to the war effort: by reusing constant functions, you could save\* creation of about 400 `$anonfun`-s from the compiler, and 750 in total from the distribution.

https://github.com/retronym/scala/compare/topic/closure-sharing

I haven't had time to further quantify the benefits, but feel free to run with the idea if you're trying to shed a few more pounds.

_\_not accounting for any closures that might have been otherwise eliminated by the optimizer, so the real benefit might be smaller*

**Comment by retronym** [comment]
Thanks for the purr of feline approval!

**Comment by jsuereth** [comment]
Wow.   Didn't know responding to email made me a cat.

**Comment by odersky** [comment]
I think the constant function proposal is worth trying out. Can we integrate that into the branch and see what we get?

As to method splitting, I actually think it's usually better to do this in the source. A humongous method is just as hard on the reader as the JIT compiler. I took pains to clean up the code for typed1, did not have the time to do the same for all the other split methods. But we should do it, the code would be clearer in the end, I think.

**Comment by odersky** [comment]
The added commits undo some previous optimizations where I suspect they don't help and might even hurt. Greg will go over all commits at some point and verify the performance impact of each one. If we see we are wrong with one of the "de-optimizations" we should revert them.

**Comment by odersky** [comment]
I have gone ahead integrating Jason's constant method patch. Amended pull request will follow shortly.

**Comment by odersky** [comment]
One more tweak: I pushed map and flatMap under 35 bytes to make them inlinable. If current Hotspot documentation is to be believed 35 byte is the limit for inlined methods. 

https://wikis.oracle.com/display/HotSpotInternals/Inlining

This means that map and flatMap were not inlined before, so all the improvements from monomorphic calls we say were that the call was monomorphic, not that it was inlined. It's hard to know what's going on without digging deeper. Anyway, we should have a good performance comparison now, to see whether the change helped.

**Comment by gkossakowski** [comment]
I built the old branch (`topic/opt`) commit after commit and got test failures:
https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/358/console

The first failing commit is 0a1e1d62fc8. I'll rebuild this (rebased) branch and see what happens. @odersky, in meantime, can you have a look into that test failure?

**Comment by gkossakowski** [comment]
So we are having lots of failures:
- 197e04707043db15002081ae867ebd84980ca430 - https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/398/console
- 7ec2c520f55486889adc4ed6490e084cc5ff4cce - https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/400/console
- 9a2ba5c9f9133a81953d61ed94b8f06d743f084b - https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/401/console

Build failures should be easy to fix but I'll wait for all of them to finish and then I'll start fixing obvious problems. If there any non-obvious problems I'll provide references here.

**Comment by odersky** [comment]
The test failure is a well known one; it existed for iterations where paramTypes in method type was changed (it was reverted back later). I thought our re-organization merged all commits affecting paramTypes?

Generally, can you say which commits have the failures?

**Comment by gkossakowski** [comment]
Yeah, the commit reorganization should have taken care of that.

Now, the rebased branch fails due to simple build failure (sources do not compile). I'll let jenkins finish all commits and will report back tonight.

**Comment by retronym** [comment]
> I have gone ahead integrating Jason's constant method patch. Amended pull request will follow shortly.

If my constant function patch doesn't show clear performance wins, or could be implicated for these build problems, please drop it and we can defer it until after 2.10. It seems a bit riskier than the others changes proposed here.

> As to method splitting, I actually think it's usually better to do this in the source. A humongous method is just as hard on the reader as the JIT compiler. I took pains to clean up the code for typed1, did not have the time to do the same for all the other split methods. But we should do it, the code would be clearer in the end, I think.

I agree, manual splitting is often worthwhile. But in other cases, it will be nice to have the compiler do this for us. I'm trying to create such a facility: https://github.com/retronym/scala/compare/topic/method-per-case, but it's not quite there.

**Comment by odersky** [comment]
There's a test failure for files/res/t5167 which was introduced by

d0b7ada964b01de46fb846500f2b2f6d83cf20fb

This commit was a merge of Jason's changes with what I had. I can try to clean up, unless Greg is already on it?
What I think we need to do:
- eliminate the merge and have Jason's patch properly rebase
- combine my two commits on map/flatMap.

**Comment by retronym** [comment]
@odersky Please roll back my change altogether, I think it's a straight up bug, not a merge problem. (I didn't run the `res` tests originally)

I'll see if I can brush it up tomorrow, but it might be better as a separate pull request.

(As a happy coincidence, I fixed SI-5167 not so long ago, so I should be able to figure out how my patch led to the regression.)

**Comment by gkossakowski** [comment]
The current verdict brought by Jenkins is that 197e04707043db15002081ae867ebd84980ca430..5c4ffe28716aba086546334b26714c1ce504cc22 are broken for one reason or another (you can check it https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/, build numbers 398..405).

Then we have a nice sequence of successful builds until 20aa3cf5e1070e78e3e079b217b1225cff85f7a5 which is @retronym's commit that you already now that is problematic. I'm on those earlier failures. I'll see tomorrow's morning if I can fix them and report back.

**Comment by gkossakowski** [comment]
I believe I fixed some of our problems. Jenkins is building my `topic/opt-rebased2` branch now.

**Comment by odersky** [comment]
Cool! Greg, I am offline until Monday evening. Can you remove Jason's commit and squash my two last map-related commits into one? We should merge with 2.10 by Monday noon if possible so that Josh can cut an M7. Thanks!

**Comment by gkossakowski** [comment]
Yes, I already dropped @retronym's commit. I'll take care of squashing too.

Now, the only problem I see is this mysterious failure: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/430/console

It goes away in subsequent commits so I might be able to eventually figure out how to fix it but if you have an idea right away let me know.

**Comment by paulp** [comment]
No guarantees, but I suspect from the stack trace that that mysterious failure has the same underlying cause as did the bug I fixed last night, which is at the tip of the 2.10.x branch - d46818e4e1 .

**Comment by jsuereth** [comment]
I have community build timings (avg of 10) right now I can use for quick
validation on other projects.   I'll kick off a build against Greg's branch
today and compare to before.  I'm curious if we can find pathological
problems.

**Comment by retronym** [comment]
I have fixed my const function patch. It's based on master.

  https://github.com/retronym/scala/compare/topic/closure-sharing-2 .

@gkossakowski If it's easy enough to do so, you could run it through the benchmarker. But don't give this priority, I'm not that optimistic about a benefit. 

BTW, it would be good if your tool tracked the size of each of the JARs in the distribution, which might fluctuate with more aggressive inlining.

-jason

**Comment by gkossakowski** [comment]
@paulp: rebasing didn't help: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/459/console

I'm digging into it but I have only one hour left before boarding on a plane. If don't find what's wrong I'd definitively use some help from a different time zone.

**Comment by gkossakowski** [comment]
@retronym: My priority is to get what we have to pass all tests. I think your commit can go as a separate pull request.

**Comment by paulp** [comment]
I also am imminently boarding a plane.  In fact they just called my group!

**Comment by gkossakowski** [comment]
@paulp Ok. Thanks for letting me know!

**Comment by paulp** [comment]
I fixed it on the plane - only question is whether I will have time to checkin. If I don't it's check for no symbol in specializesSym - it used to call alternatives which is nil for no symbol.

**Comment by paulp** [comment]
No time for pull req (it was that close) but I pushed it.

**Comment by paulp** [comment]
The baggage loader managed to drive into our plane so we're sitting here awaiting the damage report.  So I guess I can point to the actual commit.  fa2a39023d

**Comment by gkossakowski** [comment]
@paulp: Insanely helpful. Thanks a lot!

I squashed your commit into original one and I'm rebuilding it on Jenkins. Hopefully, everything will be ready tomorrow's morning.

**Comment by gkossakowski** [comment]
Jenkins finished it's work. All commits are green. A new pull request is coming.

**Pull request closed without merging**
