### PR TITLE
SI-6387 Clones accessor before name expansion

### PR DESCRIPTION
**Pull request by paulp**
When a symbol's name is expanded due to a conflict during mixin
composition (e.g. multiple traits with same-named members, but
which are not both visible at the language level in the concrete
class) the compiler renames some symbols with expanded names which
embed the name of the declaring class to avoid clashes.

In the rare cases when the accessor overrides the member in base
class, such expansion either results in AbstractMethodError when
the base method is abstract, or, even worse, can change the
semantics of the program.

To avoid such issues, we clone the accessor symbol, clear its
ACCESSOR flag and enter the symbol with an unchanged name.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @vigdorchik, I propose this to supersede #2273.

**Comment by paulp** [comment]
@adriaanm Is the kitteh on vacation?

**Comment by adriaanm** [comment]
It went to Deadlockia but has since returned.

**Comment by vigdorchik** [comment]
Thank you Paul. I'll pay more attention to my PR messages in the future.. Just two comments:
- expandName happens not only when composing mixins, In SI-6387 expanding happens in specialize:
  https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala#L1308
- when expanding, the full name of the declaring class is prepended, not just the name.

**Comment by paulp** [comment]
Thanks, I made those clarifications. I didn't mean "during mixin composition" as "during phase mixin", but as "during the process of composing code units", but it was not optimal phrasing.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
@vigdorchik, please add a comment that starts with LGTM, if it indeed now looks good to you (this will make the buildbot add the tested label)

**Comment by vigdorchik** [comment]
LGTM Thanks Paul!

**Pull request merged**
