### PR TITLE
Move StringBuilder to its own file

### PR DESCRIPTION
**Pull request by isaacl**
- minor cleanup of the new`appendAll(IterableOnce)`: check type first, instead of starting with knownSize.

### CODE REVIEW

**Comment by dwijnand** [comment]
Hey @isaacl. Thanks for the PR. Two notes:

1. It's a little hard (at least in GitHub's web UI) to review changes if they're mixed with file move/splits: best done in two commits.
2. I think the Scala project, for git history (log, blame) and forward/back-porting reasons is generally against changes like splitting a file in two. So it's possible that change might be rejected on those grounds (just a heads up).

**Comment by isaacl** [comment]
@dwijnand totally fine. the file move was proposed by @som-snytt in one of my previous PRs, so was just following up.

**Comment by SethTisue** [comment]
> generally against changes like splitting a file in two

in general often yes, but this particular case seems particular illogical and egregious to me, and collections stuff is getting moved around and changed like crazy anyway in the 2.13 cycle, so 👍

**Review by SethTisue — APPROVED** [review]

**Comment by dwijnand** [comment]
ok

**Pull request merged**
