### PR TITLE
SI-7533 Adds Symbol.isAbstract

### PR DESCRIPTION
**Pull request by xeno-by**
Amazingly enough, we've missed the fact that non-type symbols can also
be abstract. Having been enlightened by this, I'm exposing isDeferred
and merging it along with isAbstractType and isAbstractClass into the
unified Symbol.isAbstract method.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by paulp** [comment]
I'm not sure we've missed the fact that non-type symbols can be abstract; it's called "isDeferred".

I have my doubts about the wisdom of this. Few are the moments when I am interested in "abstractness" as an abstract concept in a way which is equally applicable to types and terms. So unifying them just gives one more way for symbols to appear as something they aren't - since we don't actually know how to use types, all we have are "Symbols" everywhere. Different methods for "is it an abstract value" and "is it an abstract type" go a little ways to help protected me from such typeless entities.

**Comment by xeno-by** [comment]
So you suggest we have three different methods for `isAbstractClass`, `isAbstractMethod` and `isAbstractType`?

**Comment by paulp** [comment]
I didn't suggest anything.

**Comment by paulp** [comment]
I do suggest that we encode the fact that classes aren't methods and methods aren't types in the type system; and failing that I'm against any change to the status quo, because the only thing worse than unworkable code is unworkable code which is changing.

**Comment by xeno-by** [comment]
Well, we already have a way to encode that distinction by having `MethodSymbol`, `ClassSymbol`, `TypeSymbol`, etc. From your words I understand that this status quo is not good enough. Could you please elaborate on why?

**Comment by paulp** [comment]
Those aren't types, those are classes. Types are things you actually use. When a method is invoked on a MethodSymbol, what percentage of the time was the receiver statically typed as a MethodSymbol and not as a Symbol? Those statistics can be collected. It will be a tiny number. Which means they accomplish little except organizing bytecode.

Types are constructs which protect you from asking a method what kind of type alias it is, or a package what its type arguments are. At minimum.

**Comment by xeno-by** [comment]
In our current design, `Symbol` only introduces universally applicable notions: `name`, `typeSignature`, `annotations`, etc. Things like `getter`, `isParamWithDefault` or `typeParams` are declared in subclasses. What do you think about that?

**Comment by paulp** [comment]
You might have to tell me what "our current design" refers to before I can answer that.

**Comment by xeno-by** [comment]
Would it be possible for you to answer the question if we replace "in our current design" with "currently"?

**Comment by paulp** [comment]
Honestly I thought you were talking about something you're working on which I haven't seen. Because you said that Symbol "only introduces universally applicable notions", but appended is what I find in scala.reflect.api.Symbol (at least according to reflection.) Almost nothing on this list is applicable to everything which hides under "Symbol" in the compiler. Even "name" isn't universal. Count how many symbols there are with the name `<refinement>` sometime. When there are 100K+ symbols with the same "name", the symbols don't have "names". They have a "name field".

The downcasting methods are the furthest thing from universal. Few of the boolean tests are universal. I suppose a method like "isMethod" can be considered "trivially universal" - indeed everything is either a method or it is not a method - but if you think I want to perform runtime tests to find the methods among my agglomeration of Symbol-stuff then I'm definitely not making my point.

Just to be concrete, the symbols I consider universally applicable in that list are: map, filter, suchThat, orElse, isErroneous, owner. We could throw in a couple more. The general proportion is the important thing.

Let me ask it this way: how often do you create lists which contain Strings and Ints, and then identify the individual elements by calling isString and isInt? Would you set out to write methods which returned "a String or an Int, work it out at runtime" ? 

All of this is simply exported compiler complexity. A symbol's life is ad hoc from the day it is born (or cloned) to the day it is collected. The reflection interface reproduces that experience with high fidelity. But it is not a desirable quality.

```
def allOverriddenSymbols: List[Symbol]
def annotations: List[Annotation]
def asClass: ClassSymbol
def asFreeTerm: FreeTermSymbol
def asFreeType: FreeTypeSymbol
def asMethod: MethodSymbol
def asModule: ModuleSymbol
def asTerm: TermSymbol
def asType: TypeSymbol
def associatedFile: scala.reflect.io.AbstractFile
def companionSymbol: Symbol
def filter(cond: Symbol => Boolean): Symbol
def fullName: String
def isAbstractOverride: Boolean
def isClass: Boolean
def isErroneous: Boolean
def isFinal: Boolean
def isFreeTerm: Boolean
def isFreeType: Boolean
def isImplementationArtifact: Boolean
def isImplicit: Boolean
def isJava: Boolean
def isLocal: Boolean
def isMacro: Boolean
def isMethod: Boolean
def isModule: Boolean
def isModuleClass: Boolean
def isOverride: Boolean
def isPackage: Boolean
def isPackageClass: Boolean
def isParameter: Boolean
def isPrivate: Boolean
def isProtected: Boolean
def isPublic: Boolean
def isSpecialized: Boolean
def isStatic: Boolean
def isSynthetic: Boolean
def isTerm: Boolean
def isType: Boolean
def map(f: Symbol => Symbol): Symbol
def name: Name
def newClassSymbol$default$2: Position
def newClassSymbol$default$3: FlagSet
def newClassSymbol(name: TypeName,pos: Position,flags: FlagSet): ClassSymbol
def newMethodSymbol$default$2: Position
def newMethodSymbol$default$3: FlagSet
def newMethodSymbol(name: TermName,pos: Position,flags: FlagSet): MethodSymbol
def newModuleAndClassSymbol$default$2: Position
def newModuleAndClassSymbol$default$3: FlagSet
def newModuleAndClassSymbol(name: Name,pos: Position,flags: FlagSet): (ModuleSymbol, ClassSymbol)
def newTermSymbol$default$2: Position
def newTermSymbol$default$3: FlagSet
def newTermSymbol(name: TermName,pos: Position,flags: FlagSet): TermSymbol
def newTypeSymbol$default$2: Position
def newTypeSymbol$default$3: FlagSet
def newTypeSymbol(name: TypeName,pos: Position,flags: FlagSet): TypeSymbol
def orElse(alt: => Symbol): Symbol
def owner: Symbol
def privateWithin: Symbol
def suchThat(cond: Symbol => Boolean): Symbol
def typeSignature: Type
def typeSignatureIn(site: Type): Type
```

**Comment by xeno-by** [comment]
Okay, closing then.

**Pull request closed without merging**
