### PR TITLE
SI-8205 [nomaster] backport test pos.lineContent

### PR DESCRIPTION
**Pull request by som-snytt**
Verifies previous behavior.

### CODE REVIEW

**Comment by retronym** [comment]
LGTM, great idea to backport!

**Comment by adriaanm** [comment]
weird... https://scala-webapps.epfl.ch/jenkins/job/scala-checkin/8236/consoleFull failed

**Comment by adriaanm** [comment]
potentially because 8ee165c's parent is 4 months old and PR validation tests the result of merging into 2.10.x, whereas checkin is probably doing a detached head checkout

**Comment by som-snytt** [comment]
Ack, acktually, I had checked out a tag to test, then didn't switch to 2.10.x.

Let me know if I should resubmit.

Who knew that backporting was also an art.

**Comment by adriaanm** [comment]
I vaguely remember learning about gefundenes Fressen in some high school art class.
No need to redo anything -- 't was a good refresher of our various validators.

**Pull request merged**
