### PR TITLE
[rework] Modularized scaladoc and presentation compiler.

### PR DESCRIPTION
**Pull request by adriaanm**
They are now separately built targets and are not privileged from the standpoint of the rest of the compiler. There is no change to build products: they are still bundlled into scala-compiler.jar, but it would now be easy to create a scaladoc.jar and an interactive.jar should we be so inclined.

rework of #2208

### CODE REVIEW

**Comment by paulp** [comment]
I owe you 1 (or 11.) I'm still thoroughly out of commission.

**Comment by adriaanm** [comment]
Can I pick my own unit?

**Comment by paulp** [comment]
You know Unit is defined as (). We may be able to make allowances for RichUnit or BoxedUnit, although supplies of those are limited. Here: () () () () () () () () () () ().

**Comment by paulp** [comment]
LGTM by the way.

**Comment by adriaanm** [comment]
I think we've done our due diligence. The IDE builds, the SBT interface builds, all the tests pass, and I've had a pretty close look at the code in the course of my rework.

Merging.

**Comment by retronym** [comment]
We should reflect the new structure in `src/{eclipse, intellij}`, too.

**Pull request merged**
