### PR TITLE
fix mobile styling for scaladoc

### PR DESCRIPTION
**Pull request by felixmulder**
I replaced all occurrences of absolute font sizing with relative ones. The resulting changes should be minimal. Please verify by looking at the resulting docs on dropbox:

https://dl.dropboxusercontent.com/u/358427/scaladoc/library/index.html#scala.Boolean

:santa: :christmas_tree:

### CODE REVIEW

**Comment by felixmulder** [comment]
cc: @VladUreche

**Comment by VladUreche** [comment]
Thanks @felixmulder!

Do you have any idea why the page looks like this on my phone? Maybe I'm doing something wrong...

screenshot_2015-12-24-22-18-57

**Comment by VladUreche** [comment]
So the problems I see are:
- disproportionately large font for the main text
- fixed size for the signatures (aka `abstract def`)
- too small font for the method/operator name
- too large font for the arguments and description

**Comment by felixmulder** [comment]
screenshot_20151225-012758
screenshot_20151225-012803

Make sure it looks the same for you. This should preferably be tested on multiple devices. I've only managed to test this on a Nexus 5 (res: 1080x1920)

I added some media queries for making the right hand side a bit more responsive. For instance, if the screen is small enough - it will adjust the left margin of the member definition (this can be seen in a normal desktop browser).

**Comment by VladUreche** [comment]
Amazing!!! In the name of everyone who ever tried browsing Scaladoc from a mobile, a huge THANK YOU! :+1:

There must be something wrong on my side, but I don't see the triple lines to open the side bar:

screenshot_2015-12-25-02-26-23

**Comment by VladUreche** [comment]
Just noticed another minor issue: I can't read the page description, since it's hidden behind the title bar (this is the top of the page, if I try to pull down the page, it refreshes):

screenshot_2015-12-25-02-32-32

**Comment by VladUreche** [comment]
Btw, ping @heathermiller: you'll be thrilled :)

**Comment by felixmulder** [comment]
What phone/tablet are you using, @VladUreche?

**Comment by VladUreche** [comment]
Sony Xperia Z1 Compact with Android 4.4.4 and the browser is Chrome 46.0.2490.76.

**Comment by felixmulder** [comment]
Hmm, would have thought it was something bigger. I'll adjust the media queries to include rules for your device.

Going to Italy next week, this might lie in wait after tonight.

**Comment by VladUreche** [comment]
Thanks for all the great work you've done! And have a wonderful holiday!
PS: Passing by Lausanne on your way? Let's grab a beer!

**Comment by felixmulder** [comment]
Allright, I've relaxed the media-queries a bit. If you feel like experimenting - see line 1048 in `template.css` and downward. (If I haven't caught your phone/tablet, that's the two places to add their dimensions.)

Original plan was actually to go via Geneva, but now we'll be going through Turin instead. Rain-check Vlad! :smile:

EDIT: if your phone is caught by the media queries the then the text should be visible. Regarding the triple lines, it's simply a UTF8-font. But perhaps the default font on your system is missing that glyph. I'll check if it's possible to style it differently.

**Comment by felixmulder** [comment]
So I think I managed to fix the missing trigram (tripple line menu thingy) by adding some black magic CSS. Should work on all browsers, tested it on my droid and friend's iPhone 6.

**Comment by VladUreche** [comment]
Awesome! It works well on my phone now. Here's one last snag i caught while browsing: the annotations (e.g. `@throws@`, `@author`, `@see` ...) force one more indent, which for small resolutions is too much. It would be better if for mobiles the text would start on the next line, with no indentation. WDYT?

screenshot_2015-12-26-10-19-35

**Comment by felixmulder** [comment]
No wifi at our apartment. Will fix it when I'm back next Saturday. Cheerios!

**Comment by VladUreche** [comment]
Thanks! Have a wonderful vacation!

**Comment by felixmulder** [comment]
@VladUreche: I've supposedly fixed the indentation of the annotations you mentioned above. This commit should also fix the scroll-bar appearing in code snippets on:

https://dl.dropboxusercontent.com/u/358427/scaladoc/reflect/index.html#scala.reflect.api.Universe

This screenshot is what the resulting changes look like on my Nexus 5:

screenshot_20160103-224116

As an added bonus, I added some space between the entity icons as per /u/predef's suggestion in the reddit thread, I'll get to the rest of his feedback in the week to come. Since it is not mobile related, I'll make a separate PR.

The rebased commit message has the full list of changes.

**Comment by VladUreche** [comment]
Wohoooooooo! That's awesome, thanks @felixmulder!

**Comment by VladUreche** [comment]
@felixmulder, I just noticed one more issue, still related to those pesky signatures at the top of the page:

screenshot_2016-01-04-00-02-09

Can you make the entire "abstract class Universe extends ..." scroll up with the rest of the page? Right now it's hiding some of the documentation and it's stuck at the top, rendering only 40% of the screen estate usable :(

**Comment by VladUreche** [comment]
Oh, and by the way, it's covering the documentation again, I can't scroll to the lines above "link symbol" -- if I try, chrome refreshes the page.

**Comment by VladUreche** [comment]
Found another snag, for long class names it's moving the title to the next line (which is over the signature):

screenshot_2016-01-04-02-03-32

@felixmulder, it's up to you if you want to still address these. The patch is a clear win over what's out there atm, so when you're tired of fixing snags, just tell me and I'll merge as-is (and we file the rest as bugs).

**Comment by felixmulder** [comment]
I'll change the behavior of the entity definition to scroll with the rest of the view on mobile.

Since these bugs are so obvious that you keep finding them by browsing the docs I'll keep fixing them. That should be the fastest solution. Once the frequency of new issues drops or we're past RC1, filing them in bug reports might be the most transparent course of action. What do you think?

**Comment by VladUreche** [comment]
@felixmulder That sounds amazing! Thanks!

**Comment by felixmulder** [comment]
Your issues should now be fixed. In the latest commit:
- Dynamic offset for the entity signature 
- Resized header fonts for mobile browsers
- Removed "EXPERIMENTAL" button from mobile view in shortcomment divs - they're still there if the member is expanded or navigated to

**Comment by felixmulder** [comment]
Hmm, a lot of pressure on the jenkins server? I wonder if I can force it to rebuild

**Comment by felixmulder** [comment]
@VladUreche - feels like this PR is complete. Next up I'm going to fix the style of your inheritance graphs (separate PR) :smile:

**Comment by VladUreche** [comment]
Awesome, thanks @felixmulder!

**Comment by VladUreche** [comment]
Looking forward to the newly styled diagrams!

Btw, here's a tiny snag, but it may also be my phone -- I can't scroll to see the rightmost code in the code boxes. Can you try on your nexus?

screenshot_2016-01-05-12-01-05

**Comment by felixmulder** [comment]
Hmm, I think there's something wrong with your phone @VladUreche, you better give me your credit card information :wink: 

It is working fine in Firefox on Android, but not Chrome as you said. I'll see if I can find a solution for it and sneak it into the next commit.

I've been thinking of doing something about search as well. One idea would be as someone else mentioned in #4877 to add a little drop-down menu when entering a search string in the top left filter box saying something like "Press enter to search for members". Upon pressing enter the relevant results would be displayed in an overlay on the right pane.

This is along the lines of what @heathermiller suggested regarding search. I'll need to generate a more thorough index - which sounds a lot more exciting than GUI-related things anyway :smile:

If you (both) have any suggestions on what you'd like it to contain I'm all ears!

**Comment by VladUreche** [comment]
Thanks @felixmulder! Full member search would be an awesome addition! If you need any help on the technical side, let's chat directly on skype or hangouts.

**Comment by heathermiller** [comment]
I wouldn't do a full member search in the way you suggest. It would confuse how the down key and enter key is already used to move down to select filtered entities. I tried to explain what I think would work better in the earlier PR in a weak hand-wavy way, but I don't think I was clear ;) What I think would be more intuitive would be:
- search results broken down into two sections: entities and members
- clear headers separating each section of results
- entities: should look like they look now
- members: should look like they look in the index. Take note of members like `result` which are implemented on _many_ classes. http://scala-lang.org/api/current/#index.index-r 

Do you see what I mean?

**Comment by heathermiller** [comment]
RE:

> members: should look like they look in the index. Take note of members like result which are implemented on many classes. http://scala-lang.org/api/current/#index.index-r

Perhaps to reduce the amount of cognitive noise, we could have a clickable ellipsis that unfolds the full list of entities that that member is implemented on for search results that take up too much space...

**Comment by felixmulder** [comment]
All right! I think I'm starting to grasp how you'd like it @heathermiller. Albeit, I'm still somewhat confused :sweat_smile: bear with me!

Do you want to keep the incremental filtering of top-level entities? If so - I reckon there are two use cases for the top left input:
1. Incremental filtering of the top-level entities (real time, same as now)
2. If the user presses enter after entering a search string, the full member search is performed and results are listed in the right pane

Or! Do you want to kill the incremental filtering? In that case, only number 2 above would apply.

Either way - the part that is difficult is presenting the full member search with intuitive results. I've read through your ideas, and I'm not sure how it should all hang together. For the sake of progress, I've created a mockup of results that I think are intuitive. It might not be exactly what you specified, but here it is:

screen shot 2016-01-06 at 09 31 18

As you can see it displays in order by package - then by entity (trait/class followed by object). It highlights the search string in the results. On a technical note, I quite like this ordering. It would allow for the search to be performed in an incremental way - i.e. allowing us to show results as they are found.

It also sort of eliminates the need for the A-Z index - but it could of course be kept if it's a popular feature or if it feels like a "quicker" way of getting from A to B.

If you have a better idea / improvements - would you mind drawing them? (Or illustrating them in some other way)

I'm sorry for any misunderstanding, gonna get my :coffee: now - let's create something great :)

**Comment by VladUreche** [comment]
@felixmulder Thanks for the mockup, it looks like something I wanted to have in scaladoc for a very long time.

For the  entities, keep in mind that there may be several levels of nesting. For example, you have method `typeSignature` in `(a) Symbol` in `(t) Universe`: http://www.scala-lang.org/api/2.12.0-M3/scala-reflect/index.html#scala.reflect.api.Symbols$Symbol@typeSignature:Symbols.this.Type.

I guess there are two ways of showing this:
(1) use the package as top-level entity and several levels of nesting
(2) use `Universe` as the top-level entity and a single level of nesting

What do you think, which one would be easier to implement? @heathermiller wdyt?

**Comment by felixmulder** [comment]
@heathermiller will probably have a better understanding of the entity indexing than I do. But for the sake of offering an outside perspective I'll say this:

I don't believe the results should be nested further than `package => entity => member`.

`Symbol` could be displayed as a member of `scala.reflect.api.Symbols`. `Universe` would also have it as a member.

Will having entities like `Symbol` stand on their own result in too many top-level entities? Otherwise that could also be done. We (or I) have time on our hands to try these things out luckily :smile:

**Comment by VladUreche** [comment]
The thing is you want to show it in `Universe` and not in `Symbols` or `SymbolsApi`, otherwise the users won't know how to get their hands on a symbol.

**Comment by heathermiller** [comment]
Hey @felixmulder! I totally understand the struggle of displaying something meaningful. If you didn't understand my suggestion, no worries – it's my fault for not making it clear, not yours :)

Here's a picture of what I mean:
fullsizerender 2

In the above image, there are two "sections" of the search results displayed in the following order:
- classes/traits/objects
- members

Under classes/traits/objects, I'd do the filtering in the sidebar exactly as we do it now. Order by package, and list in alphabetical order within the package. For the member section, I'd display as we do in the index – we don't worry about the signatures, we just show that "map" is implemented on the following entities: AbstractMap, etc, etc.

Do you see what I mean?

I was also thinking that we could add some way to toggle member-only searching in case people don't want the entities to show up as well or viceaversa. But I'm not sure how we'd add that without adding more annoying buttons

**Comment by heathermiller** [comment]
PS, and yes, you're right, we could totally drop the index this way! (It's not popular at all, almost no one realizes how to use it!)

**Comment by felixmulder** [comment]
All right, great - I now think I understand your suggestion semi-fully, two questions!
1. Would you want all entities and all members (i.e. the search results) to be displayed in the left pane initially? Or with members only on search?
2. The vertical ellipses you have drawn, are they what you meant by expandable & clickable?

Searching for something like "map" in the current API, yields roughly 60 results in top level entities from ~10 different packages. This would effectively hide the member results, with this approach. Which was one of the reasons behind the mockup I posted earlier.

On the other hand - with the approach I suggested, it has a different behavior compared to the one that is currently there + there'd probably have to be some rewriting of the index generation.

I think the approach you're suggesting is pretty much "all there" already - so it should be pretty simple to implement. As such, we could implement it - and then I could experiment with some ideas and we'll see what we like best in the end.

**Comment by heathermiller** [comment]
> Would you want all entities and all members (i.e. the search results) to be displayed in the left pane initially? Or with members only on search?

Yes. I know it seems a bit weird from a "how do I design this interaction" standpoint. But for users, I think it's most intuitive. I think a lot of novice users likely search for members in the current sidebar without realizing that it only searches entities. I think being able to search for both in the same filter would be a lot more intuitive to new users.

> The vertical ellipses you have drawn, are they what you meant by expandable & clickable?

Good question. In my drawing, I only wanted to highlight that there could be many more entities with that member. What I had in mind for the expansion would be something like:

fullsizerender 3

> Searching for something like "map" in the current API, yields roughly 60 results in top level entities from ~10 different packages. This would effectively hide the member results, with this approach. Which was one of the reasons behind the mockup I posted earlier.

Yep, so this is the reason for the "toggle member-only searching" bit I had posted. I think it would be a good idea to think of a way to toggle between results for cases like these – so toggle "members only", "entities only", or the default which would be both. We could do a simple toggle button that appears on mouseover or something. I haven't worked out exactly how best to let the user interact with this. A keyboard shortcut would be nice, or something similar to what you had earlier suggested where, as someone is typing, a dropdown appears and gives them the choice? Maybe we could even work keyboard shortcuts in that dropdown, e.g., arrow left selects the members-only toggle, arrow right selects entities-only toggle? Just brainstorming :)

**Comment by felixmulder** [comment]
I wonder how many people have tried writing something in the search box and then pressing enter. Google inbox has a pretty nice implementation of search, displaying stuff incrementally and then the full search results on enter. More spitballin' :smile:

**Comment by heathermiller** [comment]
You're probably right about the pressing enter thing – I would bet that people only arrow down and hit enter, if they hit enter at all. In Gmail, I admit that I never hit enter at all from the search bar, I just arrow down to the message I'm looking for, and then hit enter. I seldom go to the full search result. 

Good ideas :)

**Comment by heathermiller** [comment]
Btw, my above drawings etc are only a suggestion. By no means do I want to limit you to that. Just wanted to share what I came up with.

**Pull request merged**
