### PR TITLE
Bump to scala-partest 1.0.14

### PR DESCRIPTION
**Pull request by retronym**
This should fix the bootstrap build by incorporating
https://github.com/scala/scala-partest/pull/58

Review by @lrytz

### CODE REVIEW

**Comment by retronym** [comment]
Here's the in-progress [bootstrap build](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/407/console) using this tag of scala-partest.

**Comment by lrytz** [comment]
LGTM

**Comment by retronym** [comment]
/nothingtoseehere

Just force pushed a modified version of this PR that also updates the eclipse classpath.

**Pull request merged**
