### PR TITLE
Make global-showdef a DirectTest

### PR DESCRIPTION
**Pull request by som-snytt**
The test test/files/run/global-showdef.scala was outputting
to the cwd instead of the test output dir.

Good behavior is now inherited from DirectTest.

Test frameworks, of any ilk or capability, rock.

Issue was revealed by https://github.com/scala/scala/pull/4024

Review by @retronym

### CODE REVIEW

**Comment by som-snytt** [comment]
The second commit reduces the compile time a bit. Stop after typer (which also obviates the first commit, except for readability).  Show multiple things at once, modulo limitations.

It turns out, in that delta, that `-Xshow-object ""` is OK, but I didn't bother to update at this time.

**Comment by som-snytt** [comment]
PLS REBUILD/pr-scala@a69fc239462cfa6b2f01beecc611f2ebf319969c

**Comment by som-snytt** [comment]
PLS REBUILD/pr-scala@a69fc23

**Comment by som-snytt** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
LGTM

**Pull request merged**
