### PR TITLE
Critical bugfixes/leak fixes/API corrections + ScalaDoc for SIP-14

### PR DESCRIPTION
**Pull request by phaller**
Review by @axel22 and @heathermiller

### CODE REVIEW

**Comment by phaller** [comment]
I should point out that the commit of @viktorklang has already been reviewed extensively by @axel22 and @heathermiller , but for consistency they're required to sign off.

**Comment by viktorklang** [comment]
The more signatures the merrier!

**Comment by heathermiller** [comment]
LGTM (I have some trivial documentation-related comments on this one, but can address it at some other point :-) )

**Comment by axel22** [comment]
LGTM!

**Pull request merged**
