### PR TITLE
SI-6742 undeprecates certain manifest methods

### PR DESCRIPTION
**Pull request by xeno-by**
Makes sure all manifest-related (but not classmanifest-exclusive) APIs
are undeprecated in 2.10. Let's hope we'll get them deprecated back
again in 2.11.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @jsuereth 

Submission against 2.10.0-wip is intentional.

**Comment by jsuereth** [comment]
Sorry for the delay in review.  I'm still curious why this change.   We talked about it earlier and decided the existing behavior of `<;<` needed to be depreacted.  While TypeTags aren't "stable" yet, the behavior of `<:<` is something we want people not to use regardless of whether or not TypeTags become stable...

**Comment by xeno-by** [comment]
Oh sorry I didn't remember our previous conversation. If we decided that deprecation of `<:<`, `>:>` and `typeArguments` is intentional, then we need to close this PR and mark https://issues.scala-lang.org/browse/SI-6742 as Won't Fix.

**Comment by adriaanm** [comment]
well, they are truly broken afaik

**Pull request closed without merging**
