### PR TITLE
SI-6661 - Remove obsolete implicit parameter of scala.concurrent.promise method

### PR DESCRIPTION
**Pull request by phaller**
Review by @axel22

### CODE REVIEW

**Comment by jsuereth** [comment]
Is there a blocker ticket associated with this?  Not sure if there was any discussion, but I'll give it a LGTM from a code perspective unless @adriaanm overrules.

**Comment by adriaanm** [comment]
I'm not aware of any discussion nor a ticket. It's been in there like this for 11 months.
Granted, it wasn't officially released, but how can we expect people to use milestones and RCs for testing if we're then going to change public API at the last minute?

**Comment by retronym** [comment]
The floor is open for discussion.

https://groups.google.com/d/topic/scala-sips/WtaLJEW0fZc/discussion

**Comment by axel22** [comment]
LGTM.

**Comment by phaller** [comment]
The associated ticket is [SI-6661](https://issues.scala-lang.org/browse/SI-6661)

**Comment by heathermiller** [comment]
(cross-posting)

This is an inconsistency introduced after refactoring implicit ExecutionContexts. In this commit: https://github.com/scala/scala/commit/1dfce90246f7d334e34d110afb8b1517180995fc#diff-1

...the implicit ExecutionContexts were removed from everything else in Promise.scala, but it appears that method `promise` was missed in the scala.concurrent package object, which would've made sense to remove back then.

So this looks like a welcome correction.

**Comment by jsuereth** [comment]
It's a new API and minimal change, I'm willing to let it in, but we do need to try to avoid these kinds of RC fixes in the future.

This one is a bit unique because of binary compatibility restrictions.

**Comment by adriaanm** [comment]
Ok. I think fixing is the right thing to do since it was an oversight, it should be mostly source-compatible and we wouldn't be able to fix it later. I'd like to emphasize what Josh said, though.

In future, when we need to fix things like this, please announce on the mailing lists first.

**Comment by gkossakowski** [comment]
In this particular example the problem is not with the patch itself but with the commit message.

I do git archeology very often to avoid writing e-mails to people that worked on piece of code I'm trying to understand. For this process to be effective commit messages must clear and provide context. I'll point you to my own recent work: 90f12c4d31e661eebb57bf37b1d0f86b700306bd, ffc728c054740ca810f740d5dbc69f402414183f.

In 90f12c4d31e661eebb57bf37b1d0f86b700306bd I didn't just say "We do not need to retransform classes once they are loaded." The next sentence explains _why_ we do not to retransform those classes. The next paragraph explains what inspired me to introduce that change and what kind of problem it addresses.

Writing a good commit messages that make sense in a year is a long-term investment.

Once @heathermiller's comment is incorporated into commit message this change is ready to go.

**Comment by phaller** [comment]
Amended the commit message to include the clarifying comments of @heathermiller

**Comment by gkossakowski** [comment]
@phaller: thanks!

**Pull request merged**
