### PR TITLE
SI-7747 Support class based wrappers in REPL

### PR DESCRIPTION
**Pull request by som-snytt**
This is @ScrapCodes proposal with simplifications.

The original commits are squashed and pass tests.

The simplification removes changes to the typical $read.$iw.$iw.value paths. The same name ($read or $iw) is used for both the type of the wrapper and the value term at each level of nesting. So the path looks the same for both templates.

The same command option (-Yrepl-class-based) is used to pick one of two Wrapper subtypes. Wrapper is just a CodeAssembler. The wrapper is also passed to the imports wrapping code.

Review by @retronym

### CODE REVIEW

**Comment by adriaanm** [comment]
I have no idea why the IDE build failed. It's probably my fault, though. First it successfully downloads the jar from maven, then it says it can't find it. Investigating.

**Comment by adriaanm** [comment]
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/3919/console

```
Caused by: java.io.IOException: No space left on device
```

Great.

**Comment by adriaanm** [comment]
Found a couple of old floppies lying around. https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/3920/console

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by som-snytt** [comment]
@adriaanm Thanks. I'm hoping this gets into the M7 pipeline by Monday's COB.  Is that when the sun sets on Guam or something?  I have to take another look at the test diff on the first commit -- I thought I'd fixed it.  if it frustrates me, I'll have to squash the commits -- I only wanted to preserve the original commit from ScrapCodes, for the record in case it reveals something about the use case.

**Comment by som-snytt** [comment]
This `push -f` updates the check on the first commit, and updates the -Y help in the second.

**Comment by adriaanm** [comment]
Samoan deadlines ftw. Milestone granted.

**Comment by adriaanm** [comment]
LGTM -- thanks!

**Pull request merged**
