### PR TITLE
Fixes SI-8065 Regression in implicit resolution

### PR DESCRIPTION
**Pull request by rjolly**
This is just to see if tests pass. I will close it afterwards.

### CODE REVIEW

**Comment by retronym** [comment]
This will break the test cases added in 210dbc7887bc42eed4154de65d0ff5f46ca5ee58.

I spent a few hours looking at your test case when you submitted it. I was actually unable to figure out the exact set of rules that enabled it to compiler under 2.10.x. I'd really recommend that you seek a slightly less esoteric means to structure your implicits so you don't walk in this murky area at the edges of our understanding of implicits..

**Comment by rjolly** [comment]
Well, your simplified test case will not be uncommon. This is an important feature to me, see http://jscl-meditor.sourceforge.net/catc.pdf for an introduction to my project. On the other hand, this showed that the change was premature and needs a lot more thinking. The fact that it works the second time makes me think it might be related to your cache mechanism introduced in https://github.com/scala/scala/commit/3dba9932fcc79ce0ea6f7c9282320c14c95d133f so maybe there is a way to solve it without reverting Eugene's commit ?

**Comment by retronym** [comment]
I'm having a fresh look at it. Seems like we're hitting the dreaded "divergent implicit" failure, which means that implicit search results in a tree that itself needs an implicit search, and along the way we detect that this isn't progressing and bail out.

We have a recovery mechanism whereby one divergent implicit doesn't automatically fail the entire implicit search, other candidate implicits are tried.

I suspect the apparent non-determinism in my reduced test case comes from the second implicit search evaluating the candidates in a different order, and hitting two divergent candidates before the successful one. The order of the candidates is determined by a cache designed to try the most likely candidates first.

In the first search of the small test, we decide that this a divergence:

``` scala
inferImplicit: scala.this.Function1[i.type,?{<method> def f: ?}]
MyApp.this.coef2rf[scala.this.Int, R, C](<dummy argument>: Int)(<nested implicit search for view args>)
   inferImplicit: scala.this.Function1[scala.this.Int,C]
   MyApp.this.coef2rf[scala.this.Int, scala.this.Nothing, scala.this.Nothing]
       inferImplicit: scala.this.Function1[scala.this.Int,scala.this.Nothing]
       candidate: conforms: [A]=> $less$colon$less[A,A]
        DIVERGENT! pt=scala.this.Function1[scala.this.Int,scala.this.Nothing] which dominates scala.this.Function1[scala.this.Int,C]
```

**Comment by rjolly** [comment]
Can we put it artificially in the state of the second attempt ?

**Comment by retronym** [comment]
I think its best to find a way (either in your code, or in the compiler) to find a means to avoid the divergence in both attempts. But I don't have a concrete suggestion yet.

**Comment by rjolly** [comment]
Sorry, I meant : make it remain in the state of the first attempt (since the second one fails). Changing my code is not easy, because I need this implicit chaining from coef to poly to rational function and so on. And I cannot define an upper bound the the coef type because thanks to type classes, coefs can be of any type (including primitive). Can we (try to) disable the cache to force it to remain in the first state ? Is there a significant performance impact ?

**Comment by retronym** [comment]
Even though the first attempt recovers from the divergent implicit, I don't recommend relying on that. 

If you want to try disabling the pre-sorting, try removing this sorting line in `Implicits.scala`:

```
        // most frequent one first
        matches sortBy (x => if (isView) -x.useCountView else -x.useCountArg)
```

The whole problem is really quite hard to debug because your views are contending with standard library views `conforms` `int2double` etc). I was trying `-Yno-predef` to avoid some of those problems, but I still don't have a clear picture on how you could change this. I was looking for a way for to replace:

``` scala
   implicit def coef2poly[D <% C, C](value: D)(implicit factory: Poly[C]) = factory(value)
```

with 

``` scala
   implicit def coef2poly[D](value: D)(implicit factory: Poly[D]) = factory(value)
   implicit def polyView[C, D](implicit c: Poly[C], f: C => D): Poly[D]
```

But i find it hard to get to the essence of your code in its current form.

**Comment by rjolly** [comment]
Using a higher-kinded type, i.e. replacing:

class E2[R, C] extends E1[E2[R, C]]

by:

class E2[R[C], C] extends E1[E2[R, C]]

, I am able to compile in several cases, but unfortunately not all. Removing sortBy in Implicits.scala solves the problem in every cases I have tried. I have amended my commit with that change, and a test that fails without it despite a higher-kind.

**Comment by retronym** [comment]
I'm glad the source of non determinism is confirmed! 

Maybe we can special case predef.conforms in that sort order. We can disable it altogether for performance reasons.

**Comment by rjolly** [comment]
Note that I need Predef.conforms. Typically I have conversions like:
Int => Poly[Int] => Poly[Poly[Int]]
, but sometimes it degenerates to:
Int => Int => Poly[Int]
, i.e. evidence = conforms (formerly identity).

**Comment by retronym** [comment]
My idea is to try conforms last so it doesn't consume the budget of divergent recoveries (1).

**Comment by adriaanm** [comment]
I think we should revisit whether Predef should have an implicit def conforms. Can't we just put the implicit witness in the <:< object?

**Comment by retronym** [comment]
That won't be in the implicit scope of a search for function1

**Comment by adriaanm** [comment]
Ah, I see. I've been too fixated on getting rid of the special case for conforms, but maybe another special case is what must be done.

**Comment by rjolly** [comment]
Couldn't we just go with the list unsorted ?
Could we reopen the PR to see if it breaks something ?
My commit is now https://github.com/scala/scala/commit/e157e9fce5de57e74f3a7b97e0558558e8fd2ee8

**Comment by retronym** [comment]
Your code will still break if you reorder the definitions of the two implicits that you define.

I am leaning to adding an unsupported option for your code that mimics the 2.10 behaviour, but we don't guarantee. In the same vein, we might be able to make the divergent implicit recovery threshold user configurable.

**Comment by rjolly** [comment]
Yes, I saw that. As far as I can tell, it only happens with your reduced test case, which is a bit different from my use case (see test/files/pos/t8065.scala in commit above). And it would be OK as long as there exist an order that does compile. A compiler option is all right with me. Not sure what you mean with 2.10 behaviour, as a quick look shows that sortBy is already here ?

**Comment by retronym** [comment]
SI-3346 changes the order the type arguments to views are inferred to make it consistent with the way that implicit parameters are inferred. I think this change is fundamentally at odds with your design.

**Comment by rjolly** [comment]
Well, my design proves to be compatible with these change... provided the list is not sorted. Sorting was introduced in this commit https://github.com/scala/scala/commit/57ea3841d29a5c3d48eee68868780b19f1a49166 . Perhaps we should ask Paul whether it is really needed ?
/cc @paulp

**Comment by retronym** [comment]
It is a performance optimization. We're already slow, we can't give that one up.

**Comment by rjolly** [comment]
Here are a few timings that prove that it is insignificant at best:

```
locker.library.timer      : 3:34.661 sec \
locker.reflect.timer      : 4:20.708 sec |    2.11.0-M7
locker.compiler.timer     : 6:04.651 sec /

quick.library.timer       : 3:48.294 sec \
quick.reflect.timer       : 4:25.815 sec |
quick.compiler.timer      : 6:20.021 sec |
quick.repl.timer          : 2:09.484 sec |
quick.scaladoc.timer      : 1:50.152 sec |    2.11.0-M8-without-sortBy
quick.interactive.timer   : 1:19.505 sec |
quick.scalap.timer        : 1:14.774 sec |
quick.actors.timer        : 1:00.832 sec |
quick.partest-extras.timer: 43.095 sec   /

locker.library.timer      : 3:35.132 sec \
locker.reflect.timer      : 4:14.765 sec |    2.11.0-M7
locker.compiler.timer     : 6:11.075 sec /

quick.library.timer       : 3:52.033 sec \
quick.reflect.timer       : 4:25.367 sec |
quick.compiler.timer      : 6:40.339 sec |
quick.repl.timer          : 2:10.139 sec |
quick.scaladoc.timer      : 1:51.957 sec |    2.11.0-M8
quick.interactive.timer   : 1:19.454 sec |
quick.scalap.timer        : 1:16.879 sec |
quick.actors.timer        : 1:01.517 sec |
quick.partest-extras.timer: 42.443 sec   /

ScAS compile time:

Total time: 85 s    <---------------------    2.11.0-M8
Total time: 93 s    <---------------------    2.11.0-M8-without-sortBy

Total time: 75 s    <---------------------    2.11.0-M8
Total time: 75 s    <---------------------    2.11.0-M8-without-sortBy

Total time: 73 s    <---------------------    2.11.0-M8
Total time: 71 s    <---------------------    2.11.0-M8-without-sortBy

Total time: 70 s    <---------------------    2.11.0-M8
Total time: 68 s    <---------------------    2.11.0-M8-without-sortBy
```

**Comment by paulp** [comment]
The impact isn't evenly distributed. Projects which use a lot of implicits will feel it a lot more.

**Comment by rjolly** [comment]
Prove it.

**Comment by paulp** [comment]
I was offering information; I don't care who believes it.

**Comment by Blaisorblade** [comment]
@rjolly, you're the one trying to prove some performance optimization is irrelevant.

The patch mentions Tiark (Rompf), and I happen to know more relevant benchmarks for implicit resolution performance:
- lightweight modular staging (LMS) (https://github.com/TiarkRompf/virtualization-lms-core) and Delite (https://github.com/stanford-ppl/Delite/), most probably the original testcase. But they need a (small) compiler fork.
- My own research project (https://github.com/ps-mr/LinqOnSteroids) — the code is similar to LMS, but I dare mention it because does not need a compiler fork, and pushes Scalac in interestingly different directions.
- The most used code using the same pattern is Slick with the direct embedding. However, I'm not sure how big are the clients.

**Comment by Blaisorblade** [comment]
> We have a recovery mechanism whereby one divergent implicit doesn't automatically fail the entire implicit search, other candidate implicits are tried.

I did fear this was the case, but I hoped I was misguessing Scalac's implementation.

**Comment by rjolly** [comment]
```
LinqOnSteroids

Total time: 548 s <- 512M 2.10.4-RC1
Total time: 551 s <- 512M 2.10.4-RC1-without-sortBy

Total time: 558 s <- 768M 2.10.4-RC1
Total time: 552 s <- 768M 2.10.4-RC1-without-sortBy

Slick

Total time: 886 s <- 512M 2.10.4-RC1
Total time: 878 s <- 512M 2.10.4-RC1-without-sortBy

Total time: 867 s <- 768M 2.10.4-RC1
Total time: 870 s <- 768M 2.10.4-RC1-without-sortBy
```

**Pull request closed without merging**
