### PR TITLE
[nomerge] Backport windows test fix

### PR DESCRIPTION
**Pull request by som-snytt**

### CODE REVIEW

**Comment by som-snytt** [comment]
@SethTisue Just carved the turkey, half is going to a potluck tonight. That was a fine bird. Fingers crossed for this quickie change. All I remember from the other PR is the pain and suffering.

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/1568/

**Comment by som-snytt** [comment]
I was going to say Nothing but dots, baby! but it doesn't run in terse mode.

**Comment by SethTisue** [comment]
thanks! 🦃

**Pull request merged**
