### PR TITLE
SI-6863 Fix verify error in captured var created from try/catch

### PR DESCRIPTION
**Pull request by JamesIry**
If a var is assigned from a try/catch and it's captured into a ref
then we were generating invalid byte code. The fix basically
undoes commit b2f3fb271342d7862cc045f5ee5cff6815ac9722
and adds a test to make sure this case doesn't regress again.

review @magarciaEPFL, @paulp

### CODE REVIEW

**Comment by paulp** [comment]
Huh, there's definitely more story to that commit than is apparent on the surface. I was executing somebody else's will on the matter. "It wasn't me, it was the one-armed man!" No, really. But I can't remember the details.

**Comment by paulp** [comment]
Okay, it sure looks like when I removed that code, it WAS redundant. There was a whole phase with a copy-pasted copy of that code. Here is the code which remained in LiftCode even after the removal cited in this ticket.

```

    /**
     * PP: There is apparently some degree of overlap between the CAPTURED
     *  flag and the role being filled here.  I think this is how this was able
     *  to go for so long looking only at DefDef and Ident nodes, as bugs
     *  would only emerge under more complicated conditions such as #3855.
     *  I'll try to figure it all out, but if someone who already knows the
     *  whole story wants to fill it in, that too would be great.
     *
     *  XXX I found this had been cut and pasted between LiftCode and UnCurry,
     *  and seems to be running in both.
     */
    private val freeLocalsTraverser = new Traverser {
      var currentMethod: Symbol = NoSymbol
      var maybeEscaping = false

      def withEscaping(body: => Unit) {
        val saved = maybeEscaping
        maybeEscaping = true
        try body
        finally maybeEscaping = saved
      }

      override def traverse(tree: Tree) = tree match {
        case DefDef(_, _, _, _, _, _) =>
          val lastMethod = currentMethod
          currentMethod = tree.symbol
          try super.traverse(tree)
          finally currentMethod = lastMethod
        /** A method call with a by-name parameter represents escape. */
        case Apply(fn, args) if fn.symbol.paramss.nonEmpty =>
          traverse(fn)
          for ((param, arg) <- treeInfo.zipMethodParamsAndArgs(tree)) {
            if (param.tpe != null && isByNameParamType(param.tpe))
              withEscaping(traverse(arg))
            else
              traverse(arg)
          }

        /** The rhs of a closure represents escape. */
        case Function(vparams, body) =>
          vparams foreach traverse
          withEscaping(traverse(body))

        /**
         * The appearance of an ident outside the method where it was defined or
         *  anytime maybeEscaping is true implies escape.
         */
        case Ident(_) =>
          val sym = tree.symbol
          if (sym.isVariable && sym.owner.isMethod && (maybeEscaping || sym.owner != currentMethod)) {
            freeMutableVars += sym
            val symTpe = sym.tpe
            val symClass = symTpe.typeSymbol
            atPhase(phase.next) {
              def refType(valueRef: Map[Symbol, Symbol], objectRefClass: Symbol) =
                if (isValueClass(symClass)) valueRef(symClass).tpe
                else appliedType(objectRefClass.typeConstructor, List(symTpe))

              sym updateInfo (
                if (sym.hasAnnotation(VolatileAttr)) refType(volatileRefClass, VolatileObjectRefClass)
                else refType(refClass, ObjectRefClass))
            }
          }
        case _ =>
          super.traverse(tree)
      }
    }
```

Then five months later along came ffc2389840 and

```
    Major cleanup of reification:
    * LiftCode phase has been removed
    * Code has been deprecated and will be removed as we roll a new starr
    * Logic related to type-directed lifting has been purged
```

**Comment by JamesIry** [comment]
My code archeology skills failed to figure out the whole story.

I dont' see the redundant code in the stuff that was removed. But there must be redundancy because we're basically duplicating the effort of determining when a var needs to be stuffed in a Ref. Which is of course your comment that I resurrected about the CAPTURED flag.

**Comment by paulp** [comment]
You don't see the redundant code in the stuff that was removed? After comparing it to the code in my comment above?  The similarity should jump out before too long... it's identical!

**Comment by paulp** [comment]
To re-emphasize, the large code passage above is not the code which was removed in b2f3fb2. It is the code which _remained_ after b2f3fb2.

**Comment by JamesIry** [comment]
Right. I mean I don't see the similar code being removed in ffc2389840, so it must have disappeared earlier.

**Comment by paulp** [comment]
And because it may be confusing the issue, there is ALSO redundancy with the CAPTURED flag. But that's a "two overlapping implementations" style of redundancy, whereas the commit you are reverting was an (unforgivable, really) "copy and pasted across phases" style redundancy.

**Comment by paulp** [comment]
Oh, I hadn't looked that far. Let me see where it disappeared. Because it is possible/likely that is a better place to be reverting something.

**Comment by JamesIry** [comment]
exactly.

**Comment by paulp** [comment]
Okay, take a good look at beb8751879 .

**Comment by JamesIry** [comment]
Haha. Now I'm getting a headache.

**Comment by paulp** [comment]
So if the comment can be believed, it's in LambdaLift where something should change.

**Comment by JamesIry** [comment]
lambdalift happens after uncurry and all the trylifting logic is currently in uncurry. The trylifting stuff probably doesn't belong there, but moving it seems like a bigger risk than we want to eat for 2.10.x.  If you agree I'll leave this PR as-is and create another issue targeted to master to refactor trylifting out of uncurry.

**Comment by paulp** [comment]
I agree with minimizing the change for 2.10.x, but un-reverting a pile of code which has been gone for 14 months with even its doppelganger gone for a year makes me pretty nervous.

**Comment by JamesIry** [comment]
Shows the value of having a test or two every now and again.

**Comment by gkossakowski** [comment]
Rather epic story. I agree about tests. Whenever you touch code, write tests for it they are missing. That should be our standard practice I think. (And yes, I think our practices are improving).

**Comment by adriaanm** [comment]
I can't think of a more minimal change for 2.10.x than reverting the removal of some code that worked dandily for quite some time.

**Comment by adriaanm** [comment]
ping @magarciaEPFL, @paulp for final review

**Comment by paulp** [comment]
The resurrected code doesn't indicate its status ("has returned from beyond the grave - was once the victim of a fatal cloning experiment, now sells sea shells by the seashore") and it seems like it should at least do that. If that is done I will find a way to live with this pet sematary situation.

**Comment by magarciaEPFL** [comment]
There is a (way) simpler solution (I think) as described at https://issues.scala-lang.org/browse/SI-6863?focusedCommentId=62230&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-62230

**Comment by JamesIry** [comment]
superseded by https://github.com/scala/scala/pull/1927

**Pull request closed without merging**
