### PR TITLE
Add `def Double.signum: Double`.

### PR DESCRIPTION
**Pull request by kamilkloch**
Fixes https://github.com/scala/bug/issues/11386

### CODE REVIEW

**Review by Ichoran — APPROVED** [review]
This looks like the best way to do it all things considered.

**Comment by Ichoran** [comment]
This isn't ready to merge, though, because of the test failures!  I'm trying to figure out what's happened--something isn't the right priority any more is my guess (that is, something relies on the Long and Double conversions being at the same priority level).

**Review by Ichoran — CHANGES_REQUESTED** [review]
Can you leave the normal wrappers at the same level and add `floatSignumWrapper` at a higher (or intermediate) level so that the `float` and `double` implicits don't end up at a lower priority than all the others?  Maybe that will fix the changes.  Some changes are expected, but the ones I see in the error log don't look right to me.

**Comment by Ichoran** [comment]
I'm pretty sure that what's going on is that by pushing `RichDouble` to lower priority than `RichLong` etc., the presentation compiler assumes that `1.` is a method call on `Long` rather than the start of a `Double`.  So I think the original conversions all need to stay at the same level, and a new higher level for `signum` alone needs to be introduced (if it doesn't already exist).

**Comment by kamilkloch** [comment]
@Ichoran 

> Can you leave the normal wrappers at the same level and add `floatSignumWrapper` at a higher (or intermediate) level so that the `float` and `double` implicits don't end up at a lower priority than all the others? Maybe that will fix the changes. Some changes are expected, but the ones I see in the error log don't look right to me.

I end up having a diverging implicit conversion for `1.signum`:
- 1.toDouble.doubleSignumWrapper.signum
- 1.richInt.signum

I have failed to find a solution which keeps all richXXX wrappers on the same level.

**Comment by Ichoran** [comment]
I mean you should add a level _above_ the existing one for the floating point `signum`s, so that all the `RichX` extensions can be at the same level.

**Comment by kamilkloch** [comment]
> I mean you should add a level _above_ the existing one for the floating point `signum`s, so that all the `RichX` extensions can be at the same level.

This is exactly what I tried - to keep `RichX` in `LowPriorityImplicits` unchanged and add `signum`s in `Predef`. It does not work for the reason described above- diverging implicits for `(1: Int).signum`.

EDIT (Illustration of the problem):
```scala
  object Implicts extends LowPriorityImplicits {
    implicit class DoubleOps(x: Double) {
      def bar: Double = { println("DoubleOps"); x }
    }
  }


  abstract class LowPriorityImplicits {
    implicit class LowPriorityIntOps(x: Int) {
      def bar: Int = { println("LowPriorityIntOps"); x}
    }

    implicit class LowPriorityDoubleOps(x: Double) {
      def bar: Int = { println("LowPriorityDoubleOps"); x.toInt}
    }
  }
```
Now,
```scala
  import Implicts._
  println(1.0.bar)
```
works fine:
```
DoubleOps
1.0
``` 
but
```scala
  import Implicts._
  println(1.bar)
```
results in
```scala
[error] [...] type mismatch;
[error]   Int|? {method bar = ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method LowPriorityIntOps in class LowPriorityImplicits of type (x: Int)RichDoubleTests.Implicts.LowPriorityIntOps
[error]  and method DoubleOps in object Implicts of type (x: Double)RichDoubleTests.Implicts.DoubleOps
[error]  are possible conversion functions from Int(1) to ?{def bar: ?}
[error]   println(1.bar)
[error]           ^
[error] [...] value bar is not a member of Int
[error]   println(1.bar)
[error]             ^
[error] two errors found
```

**Comment by Ichoran** [comment]
Oh, hm.  That's annoying.  Implicits don't normally chain like that, but I guess with primitive numbers, weak conformance doesn't count as an implicit.

I guess you'll have to add a special signum implicit for _everything_ (at the same level), so the right signum is looked up.  Annoying, but I don't see a better way.  @szeiger - what do you think?

**Comment by Ichoran** [comment]
This also has implicit precedence problems :(  By moving things around I'm sure we could _eventually_ get it to work, but this seems potentially fragile.  What if other people are relying on the precedence structure to but just the way it is now?

Instead, I suggest a different approach: add an extra `sgn` or `sign` method onto `Float` and `Double` that has the property that you get a return value of the same type as the class it's on, and return `NaN` if the original value is `NaN`.  This way you aren't under any illusions that `signum` will tell you about NaN in generic numeric code (it won't!), and you can get the behavior that you want if you want it.

**Comment by kamilkloch** [comment]
I agree. Will make the changes, albeit in 3 weeks (currently AFK).

**Comment by Ichoran** [comment]
Three weeks is past the RC1 deadline.  I guess I'll pick this one up instead.

**Comment by adriaanm** [comment]
Thanks for getting the ball rolling on this! Merged Eugene's version.

**Pull request closed without merging**
