### PR TITLE
Fix broken URL for MathJAX Javascript dependency.

### PR DESCRIPTION
**Pull request by retronym**
Loaded using an DNS alias for the CDN, as per the
[instructions](http://docs.mathjax.org/en/latest/configuration.html)

I also switched from `latest` to `2.3-latest`, so that we don't
automatically perform major upgrades.

Review by @lrytz

### CODE REVIEW

**Comment by retronym** [comment]
I noticed the problem here: http://www.scala-lang.org/files/archive/spec/2.11/05-classes-and-objects.html#overriding

While we're looking at this:

http://validator.w3.org/unicorn/check?ucn_uri=www.scala-lang.org%2Ffiles%2Farchive%2Fspec%2F2.11%2F05-classes-and-objects.html&doctype=Inline&charset=(detect%20automatically)&ucn_task=conformance#

http://validator.w3.org/checklink?uri=http%3A%2F%2Fwww.scala-lang.org%2Ffiles%2Farchive%2Fspec%2F2.11%2F05-classes-and-objects.html%23overriding&hide_type=all&depth=&check=Check

**Comment by som-snytt** [comment]
That wasn't to keep tlc from figuring out the secret sauce?

**Comment by retronym** [comment]
My heart would sing for joy if forkers spent more time in `./spec`. I don't think sauce secrecy is really the limiting factor :)

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
