### PR TITLE
Revert "SI-5920 enables default and named args in macros"

### PR DESCRIPTION
**Pull request by retronym**
This reverts commit a02e053a5dec134f7c7dc53a2c1091039218237d.

Review by @xeno-by

### CODE REVIEW

**Comment by retronym** [comment]
This will re-open issue SI-5920

**Comment by xeno-by** [comment]
Let me see what's up with https://github.com/scala/scala/pull/3541. If it's going to be bad, I'll revert.

**Comment by retronym** [comment]
I prefer to revert first, take your time with a fix, then go forward.

**Comment by xeno-by** [comment]
Pinged you in gtalk.

**Pull request merged**
