### PR TITLE
Replace UnApply to Apply in resetLocalAttrs

### LINKED ISSUE #8825: resetLocalAttrs does not work with unapplySeq
```scala
Welcome to Scala version 2.11.2 (Java HotSpot(TM) Client VM, Java 1.7.0_55).
Type in expressions to have them evaluated.
Type :help for more information.

scala> object Mover {
     |   import scala.reflect.macros.Context
     |   def moveTreeMacro(c: Context)(e: c.Expr[Any]): c.Expr[Any] = {
     |     import c._
     |     import c.universe._
     |     val ee = c.Expr(c.resetLocalAttrs(e.tree))
     |     reify {
     |       new AnyRef {
     |         def moved = {
     |           ee.splice
     |         }
     |       }
     |     }
     |   }
     |   import scala.language.experimental.macros
     |   def moveTree(e: Any): Any = macro moveTreeMacro
     | }
warning: there were two deprecation warnings; re-run with -deprecation for details
defined object Mover

scala> Mover.moveTree {
     |   val l = List(1, 2, 3)
     |   l match {
     |     case _ :: Nil => 
     |     case Nil => 
     |     case _ =>
     |   }
     | }
res0: AnyRef{def moved: Unit} = $anon$1@60a55c

scala> Mover.moveTree {
     |   val l = List(1, 2, 3)
     |   l match {
     |     case List(_) => 
     |     case List() => 
     |     case _ =>
     |   }
     | }
ReplGlobal.abort: unexpected UnApply immutable.this.List.unapplySeq[Int](<unapply-selector>) <unapply> (_)
error: unexpected UnApply immutable.this.List.unapplySeq[Int](<unapply-selector>) <unapply> (_)
scala.reflect.internal.FatalError: unexpected UnApply immutable.this.List.unapplySeq[Int](<unapply-selector>) <unapply> (_)
	at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
	at scala.tools.nsc.interpreter.IMain$$anon$1.scala$tools$nsc$interpreter$ReplGlobal$$super$abort(IMain.scala:237)
	at scala.tools.nsc.interpreter.ReplGlobal$class.abort(ReplGlobal.scala:20)
	at scala.tools.nsc.interpreter.IMain$$anon$1.abort(IMain.scala:237)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5245)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5257)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$114$$anonfun$apply$56.apply(Typers.scala:5406)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$114$$anonfun$apply$56.apply(Typers.scala:5406)
	at scala.tools.nsc.typechecker.Contexts$Context.withMode(Contexts.scala:374)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$114.apply(Typers.scala:5406)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$114.apply(Typers.scala:5406)
	at scala.tools.nsc.typechecker.TypeDiagnostics$class.typingInPattern(TypeDiagnostics.scala:62)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.typingInPattern(ReplGlobal.scala:23)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPattern(Typers.scala:5406)
	at scala.tools.nsc.typechecker.Typers$Typer.typedCase(Typers.scala:2367)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedCases$1.apply(Typers.scala:2407)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedCases$1.apply(Typers.scala:2406)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedCases(Typers.scala:2406)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMatch(Typers.scala:2418)
	at scala.tools.nsc.typechecker.Typers$Typer.typedVirtualizedMatch$1(Typers.scala:4218)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5250)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5257)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2349)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5214)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5250)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5257)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5360)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5451)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:876)
	at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1210)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1527)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1539)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:778)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:777)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:777)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1566)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:777)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:769)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1681)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1689)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1679)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1429)
	at scala.reflect.internal.Symbols$Symbol.tpe_$times(Symbols.scala:1392)
	at scala.reflect.internal.Symbols$Symbol.tpe(Symbols.scala:1357)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$scala$tools$nsc$typechecker$Typers$Typer$$matchesVisibleMember$1$1.apply(Typers.scala:2322)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$scala$tools$nsc$typechecker$Typers$Typer$$matchesVisibleMember$1$1.apply(Typers.scala:2320)
	at scala.collection.LinearSeqOptimized$class.exists(LinearSeqOptimized.scala:79)
	at scala.collection.immutable.List.exists(List.scala:83)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$matchesVisibleMember$1(Typers.scala:2320)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$38.apply(Typers.scala:2331)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$38.apply(Typers.scala:2327)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at scala.reflect.internal.Scopes$Scope.filter(Scopes.scala:381)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2315)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5214)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5250)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5257)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Macros$DefMacroExpander$$anonfun$21.apply(Macros.scala:623)
	at scala.tools.nsc.typechecker.Macros$DefMacroExpander$$anonfun$21.apply(Macros.scala:623)
	at scala.tools.nsc.typechecker.Contexts$Context.withMode(Contexts.scala:374)
	at scala.tools.nsc.typechecker.Macros$DefMacroExpander.typecheck$1(Macros.scala:623)
	at scala.tools.nsc.typechecker.Macros$DefMacroExpander.onSuccess(Macros.scala:635)
	at scala.tools.nsc.typechecker.Macros$MacroExpander$$anonfun$expand$1.apply(Macros.scala:577)
	at scala.tools.nsc.typechecker.Macros$MacroExpander$$anonfun$expand$1.apply(Macros.scala:564)
	at scala.tools.nsc.Global.withInfoLevel(Global.scala:198)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:563)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:551)
	at scala.tools.nsc.typechecker.Macros$class.standardMacroExpand(Macros.scala:712)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.standardMacroExpand(ReplGlobal.scala:23)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:400)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:397)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$class.invoke(AnalyzerPlugins.scala:369)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$class.pluginsMacroExpand(AnalyzerPlugins.scala:397)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.pluginsMacroExpand(ReplGlobal.scala:23)
	at scala.tools.nsc.typechecker.Macros$class.macroExpand(Macros.scala:705)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.macroExpand(ReplGlobal.scala:23)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1100)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1155)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5307)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5360)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5451)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:876)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1378)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1530)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1539)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:778)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:777)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:777)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1566)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:777)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:769)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1681)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1689)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1679)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1429)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1576)
	at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$class.addDerivedTrees(MethodSynthesis.scala:181)
	at scala.tools.nsc.typechecker.Namers$Namer.addDerivedTrees(Namers.scala:53)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1879)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1879)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1816)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1813)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1879)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1779)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5207)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1892)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1779)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5207)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1892)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1779)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5207)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4916)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5209)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:410)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1557)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1542)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1537)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:391)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:807)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:766)
	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:942)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:937)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:534)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:522)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:520)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:754)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:772)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:772)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:772)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:772)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:772)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:772)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:772)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:666)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:433)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:450)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:868)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:854)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:854)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:95)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:854)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
```

### PR DESCRIPTION
**Pull request by Atry**
This change fixes scala/bug#8825

### CODE REVIEW

**Comment by SethTisue** [comment]
@Atry needs rebase for Jenkins to kick in

**Comment by Atry** [comment]
Rebased

**Comment by Atry** [comment]
Can we backport this PR to 2.12?

**Comment by Atry** [comment]
Test updated

**Comment by adriaanm** [comment]
The heart of the fix is right, but it belongs in `untypecheck`, in my opinion.  It should not affect resetAttrs, which is only supposed to drop symbols and types, and is used in many parts of the compiler.

I'm closing the backport for now -- please wait with backport PRs until the original PR has been approved. We're trying to keep the depth of the PR queue lower, so that we are able to spend a bit more time on all active PRs.

**Comment by Atry** [comment]
IIRC, `resetAttrs` is the internal name of `untypecheck`. I don't know if there is any other usages of `resetAttrs` other than preparing for retypechecking.

**Comment by adriaanm** [comment]
Ok, let's book the progress and bikeshed naming later :-) Sorry about the delay

**Comment by SethTisue** [comment]
#10009 has some followup work

**Pull request merged**
