### PR TITLE
Remove invalidation from Global.scala

### PR DESCRIPTION
**Pull request by mpociecha**
@gkossakowski stated that this code is unnecessary and probably it still exists only by accident

It has to be taken into account during making changes so it's better to remove this code, if it's really unnecessary..

### CODE REVIEW

**Comment by mpociecha** [comment]
By the way, this invalidation has been introduced exactly in these commits (maybe it will help in some way to decide whether it's really unnecessary):

https://github.com/scala/scala/commit/167309afd10f9b65b35e6874a30ea6340a1ddc44
https://github.com/scala/scala/commit/ace051ff0abe112b767c3912f846eb4d50e52cf5
https://github.com/scala/scala/commit/e156d4a7cf4afdab91b7c281a0e8ae6e4743cc4a

**Comment by gkossakowski** [comment]
The PR/commit message is a bit short on rationale why it's safe to remove this functionality. It was added originally to support an exeriment with resident compilation. The experiment was performed in sbt and dropped in sbt/sbt@6def08e029e474dc35af04b7403a2aeaddd0dec6.

Since then we concluded to not work on resident compilation so it's safe to drop unused code supporting it.

Once all tests pass we should include this explanation in the commit message.

**Comment by som-snytt** [comment]
That's too bad.  I had versions of partest and REPL that used it, for test isolation and the colon cp command, respectively.  Both tools are somewhat "resident" by nature.

That's from a while ago, but I thought eventually it would get revived.  I suppose that if it's workable, it can be reworked; and there was also the promise of a new classpath mechanism for the compiler anyway.

**Comment by gkossakowski** [comment]
The motivation for this PR was to make it easier to bring alternative classpath implementation. @mpociecha is looking into that.

We can also bring back the minimal functionality later on that works with the new classpath implementation.

@mpociecha, since tests passed, can you edit commit message to include the background information including the commits mentioned in this PR? We should document why we think this code is safe to be removed.

**Comment by gkossakowski** [comment]
LGTM

Thanks!

**Comment by chipsenkbeil** [comment]
I'll reiterate my comment from [SI-6502](https://issues.scala-lang.org/browse/SI-6502).

So, is there a recommended way to append to the compiler's classpath and get the entries reloaded (in case the jar has been updated)? For commands like :cp, throwing out the interpreter and replaying commands is not an ideal solution, especially not in Spark's case. 

And this still doesn't work in the Scala REPL as of 2.11.2, not just the 2.10.x branch:

screen shot 2014-08-13 at 4 48 39 pm

**Comment by fommil** [comment]
@mpociecha @gkossakowski @rcsenkbeil we just added a dependency in ENSIME on this functionality, are you really sure it's not used anywhere?

Will this break our codebase when 2.11.3 comes out? (it certainly looks like it will unless you're just moving things around)

We're using it to allow us to add the compiled classes of a project onto the presentation compiler classpath, so that only the user's active source files need to be loaded... resulting in dramatic performance improvements.  https://github.com/ensime/ensime-server/commit/3ef913698301f97dc2155e27fa4ef198f9d025c4#diff-deb75fcaf9fcae72050f24a45f6f32bcR192 What is the alternative?

BTW, if you know this code well then perhaps you can also advise on how we could do this for the 2.9 presentation compiler.

@edani were you aware that this was being removed?

**Comment by mpociecha** [comment]
Ok, people use invalidation so maybe would it be better to revert these changes? As long as there won't be the invalidation working for flat classpath, I can just add checks, which classpath implementation is used, and use the invalidation only in the case of the old one. In the case of flat classpath I could throw UnsupportedOperationException or something like that.

**Comment by fommil** [comment]
@mpociecha thanks, putting it back in again would be good especially for any bugfix releases of 2.11.

Can you please add ensime-server to your list of integration test projects to avoid this kind of problem in the future?

**Comment by retronym** [comment]
We've just opened up our [community build](https://github.com/scala/community-builds) to contributions to enable a broader set of integration testing. Could you either open a pull-request or an issue against that repository so we include ensime and avoid accidental breakage (at least in minor releases)?

**Comment by fommil** [comment]
@retronym thanks we'll do that.

@gkossakowski since this didn't work out in zinc, can you please advise if there is a better way for us to do this in ENSIME/presentation compiler? The problem we are trying to solve is to minimise the number of open files in the presentation compiler by leveraging existing class files for the rest of the project (e.g. output by the continuous compilation from a zinc server).

**Comment by edani** [comment]
I wasn't aware that this was being removed either. I'm also curious how other Scala IDEs handle changes that come from rebuilding a project... maybe they just instantiate a new presentation compiler?

**Comment by gkossakowski** [comment]
@fommil, it wasn't used in any project we knew about at the time of merging this PR.

Regarding leveraging class files, would restarting presentation compiler instance be an option? Given that Scala compilation is rather slow, restarting presentation compiler shouldn't add significant portion to the total turnaround time.

**Comment by edani** [comment]
It looks like there is very little penalty with restarting the presentation compiler so we'll go with that in ENSIME,

**Comment by gkossakowski** [comment]
Excellent! Thanks for letting us know!

**Pull request merged**
