### PR TITLE
Name boolean arguments (rebased)

### PR DESCRIPTION
**Pull request by paulp**
Rebased version of #2164 since I took long enough to review it that it started conflicting with retronym's later patches. Supersedes #2164.

### CODE REVIEW

**Comment by paulp** [comment]
LGTM. Reverse-review-self by @retronym.

**Comment by retronym** [comment]
LGTM. I'll offer my vaguest promise to kill off a some boolean parameters at some time in the unspecified future as thanks....

**Comment by paulp** [comment]
Aaaand rebased once more.

**Comment by retronym** [comment]
It's going to be that sort of day :)

**Pull request merged**
