### PR TITLE
Don’t expose Map.WithDefault in return types

### PR DESCRIPTION
**Pull request by szeiger**
Fixes https://github.com/scala/bug/issues/11314

### CODE REVIEW

**Comment by joshlemer** [comment]
We explicitly made WithDefault part of the public API in https://github.com/scala/scala/pull/6943. I think that the Map.WithDefault class is useful and that a better solution to that bug report is to either:

* annotate the type as Map

```scala
var m: Map[String, String] = Map("foo" -> "bar").withDefaultValue("baz")
m += "a" -> "b"
```

or use the non-symbolic method:

```scala
var m = Map("foo" -> "bar").withDefaultValue("baz")
m = m.updated("a", "b")
```

or to un-finalize `+=` so that `WithDefault` can override it to return `Map.WithDefault`

```scala
var m = Map("foo" -> "bar").withDefaultValue("baz")
m += "a" -> "b"
```

**Comment by szeiger** [comment]
I haven't done any benchmarking specifically for this case but I expect it to be similar to https://github.com/scala/bug/issues/11159, i.e. a small but measurable performance cost for all users to get some convenience for a corner case. I don't think that's a good trade-off. Realistically, our options are:
- Merge this PR to restore compatibility with 2.12 and revert in 3.0 or 3.1 when we can do it better.
- Keep the current state that breaks compatibility (for a corner case) for more precise types (in the same corner case).

**Comment by som-snytt** [comment]
If you're taking user votes, I hope this PR is accepted and `withDefault` is just a Map. I don't see the discussion that adumbrates why the narrow type is a good idea, but I see the hesitations on the tickets about whether it's worth the fragility/trouble/hassle. To me, it's obvious that breaking assignment syntax is a non-starter. The previous comment that it's an override demonstrates that the situation is too complex is see clearly (as what's at stake is the rewrite, not an override on mutable.Map). If you want a riot, just tell me I have to add explicit types. So, since it was never a clear win, I'd suggest calling it a day on the competing effort for the narrow result type. I also hope there is no effort to add `withDefaultWiden`.

**Comment by joroKr21** [comment]
If we had  `Function extends PartialFunction` (which is sane) instead of the opposite it would make sense for `Map` to be a `ParttialFunction`and `Map.WithDefault` to be a total function. But as it stands it doesn't make things much more type-safe.

**Review by julienrf — APPROVED** [review]

**Pull request merged**
