### PR TITLE
Revert a tiny recent refactoring in SelectiveCPSTransform

### PR DESCRIPTION
**Pull request by retronym**
The refactoring in 7e6c723df means that we can't build the CPS
plugin if we skip locker in development mode.

This commit backs out the refactoring and leaves a TODO comment
to perform it at a later date.

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
Or review by @paulp, who seems to still be up and might have his rubber stamp at hand.

**Comment by gkossakowski** [comment]
LGTM.

However, see #2931.

**Comment by gkossakowski** [comment]
Also, I'm surprised we do not skip locker by default. I'll fix that tomorrow.

**Comment by retronym** [comment]
Previous discussions of locker skipping by default:

https://github.com/scala/scala/pull/2658
https://groups.google.com/forum/#!topic/scala-internals/gp5JsM1E0Fo/discussion

**Pull request merged**
