### PR TITLE
[backport] deprecate symbolic foldLeft (/:)

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref https://github.com/scala/bug/issues/11411
Ref https://github.com/scala/scala/pull/6646

This backports the /: deprecation to aid the transition from 2.12.x to 2.13.x.

### CODE REVIEW

**Review by diesalbla — APPROVED** [review]

**Comment by xuwei-k** [comment]
https://travis-ci.org/scala/scala/jobs/568179209

```
!!   91 - run/collections.scala                     [output differs]
% diff /home/travis/build/scala/scala/test/files/run/collections-run.log /home/travis/build/scala/scala/test/files/run/collections.check
@@ -1,4 +1,3 @@
-warning: there was one deprecation warning (since 2.12.10); re-run with -deprecation for details
 ***** mutable.HashSet:
 test1: 14005
 test2: 25005003, iters = 5000
```

```
!!   92 - run/colltest1.scala                       [output differs]
% diff /home/travis/build/scala/scala/test/files/run/colltest1-run.log /home/travis/build/scala/scala/test/files/run/colltest1.check
@@ -1,4 +1,3 @@
-warning: there were two deprecation warnings (since 2.12.10); re-run with -deprecation for details
 new test starting with List()
 10: List(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
 9: List(2, 3, 4, 5, 6, 7, 8, 9, 10)
```

```
!!  912 - run/t2818.scala                           [output differs]
% diff /home/travis/build/scala/scala/test/files/run/t2818-run.log /home/travis/build/scala/scala/test/files/run/t2818.check
@@ -1,4 +1,3 @@
-warning: there were four deprecation warnings (since 2.12.10); re-run with -deprecation for details
 105
 499999500000
 0
```

**Review by SethTisue — APPROVED** [review]

**Comment by eed3si9n** [comment]
@SethTisue What do you think about closing https://github.com/scala/bug/issues/11411 after this PR, unless there's something specific?

**Comment by SethTisue** [comment]
@eed3si9n suits me. no need to keep the ticket open indefinitely just because we vaguely think we might have missed something

**Comment by SethTisue** [comment]
the confused emoji's reaction to its own deprecation is, of course, itself
Screen Shot 2019-09-04 at 9 48 23 AM

**Pull request merged**
