### PR TITLE
[sammy] Turn on SAM by default

### PR DESCRIPTION
**Pull request by ilinum**

### CODE REVIEW

**Comment by ilinum** [comment]
I'm having trouble figuring out why the build failed. Could someone point me in the right direction please?

**Comment by lrytz** [comment]
Hi @ilinum, you hit a new bug in sammy, unfortunately.. I minimized and logged it at https://issues.scala-lang.org/browse/SI-9489.

**Comment by retronym** [comment]
I've tried to fix the bug in #4822. I've also [rebased this patch on my bug fix](https://github.com/scala/scala/compare/2.12.x...retronym:ticket/9178-enable-default?expand=1) to see if we can [flush out](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-validate-main/626/console) any further problems,

**Comment by ilinum** [comment]
@retronym interesting :)
Should I close this PR?

**Comment by retronym** [comment]
Yep, let's close this one and consolidate the discussion to #4822.

**Pull request closed without merging**
