### PR TITLE
Error for SI-6355, overloading of applyDynamic.

### PR DESCRIPTION
**Pull request by paulp**
As long as it can never be called anyway, seems like we'd be
doing people a kindness to fail the compile rather than letting
it be ambiguous at every use site.

Also quieted down currently noisy -Xlint warning.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @harrah

**Comment by gkossakowski** [comment]
Why two concerns (applyDynamic) and Xlint are mixed in the same pull request?

**Comment by paulp** [comment]
Because it is my ambition to ruin scala and this will be my foot in the door. WOULD HAVE been anyway.

**Comment by gkossakowski** [comment]
So how about not ruining Scala for now and split this into two independent changes? :-)

**Comment by adriaanm** [comment]
party pooper

**Comment by paulp** [comment]
All right there bubs, let me know if I can get you a cappuccino or anything.

**Comment by harrah** [comment]
LGTM.

**Comment by paulp** [comment]
PLS REBUILD ALL

**Pull request merged**
