### PR TITLE
Change Predef.$conforms type from A <:< A to A => A 

### PR DESCRIPTION
**Pull request by smarter**
As suggested in the comment above $conforms

<hr>

This PR depends on https://github.com/scala/scala/pull/7350, only the last commit is new.

### CODE REVIEW

**Comment by lrytz** [comment]
I guess this is the least risky change for `$conforms`. LGTM.

**Comment by smarter** [comment]
What more risky change did you have in mind? :)

**Comment by lrytz** [comment]
Rename it (as it's now just an implicit identity), or move it to the companion of `Function1`. But since we don't have a strong reason to do any of that, it's probably better not to.

**Comment by SethTisue** [comment]
another of the recent spate of works-on-Jenkins, fails-on-Travis. https://github.com/scala/scala-dev/issues/570

**Comment by lrytz** [comment]
@smarter could you rebase this one?

**Comment by smarter** [comment]
Done.

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
Thanks!

**Pull request merged**
