### PR TITLE
Merge 2.10.x

### PR DESCRIPTION
**Pull request by adriaanm**
review by @retronym

```
$ g co 2.10.x && g pull scala 2.10.x && g co master && g pull scala master
$ export MB=`git merge-base 2.10.x master` # 9cdbe28c00b39c51ae9afe3066c8b44a6e5f6f96
$ git log --graph --oneline $MB...2.10.x

*   b3ad7534fb (scala/2.10.x, 2.10.x) Merge pull request #3364 from retronym/ticket/8152
|\  
| * 9df2dcc584 (scala/pr/3364) [nomaster] SI-8152 Backport variance validator performance fix
* |   d5801b9eee Merge pull request #3328 from retronym/ticket/8111
|\ \  
| |/  
|/|   
| * c91d373a78 (scala/pr/3328) SI-8111 Expand the comment with a more detailed TODO
| * 2c770ae31a (scala/pr/3327) SI-8111 Repair symbol owners after abandoned named-/default-args
* |   a8122413c0 Merge pull request #3345 from retronym/ticket/8114
|\ \  
| * | 5876e8c621 (scala/pr/3345) [nomaster] SI-8114 Binary compat. workaround for erasure bug SI-7120
* | |   aefe3fb844 Merge pull request #3344 from jamesward/fix/ec-implicit-error
|\ \ \  
| |/ /  
|/| |   
| * | bd4adf5c97 (scala/pr/3344) More clear implicitNotFound error for ExecutionContext
|/ /  
* |   1f2cd7e512 (origin/2.10.x) Merge pull request #3329 from retronym/ticket/6563
|\ \  
| |/  
|/|   
| * 255c51b3dd (scala/pr/3329) SI-6563 Test case for already-fixed crasher
|/  
*   370d6d6188 Merge pull request #3312 from xeno-by/topic/fine-points-of-whiteboxity-210x
|\  
| * c0cb1d891a (scala/pr/3312) [nomaster] codifies the state of the art wrt SI-8104
|/  
*   97b9b2c06a Merge pull request #3282 from retronym/ticket/8085
|\  
| * 7e85b59550 (scala/pr/3282) SI-8085 Fix BrowserTraverser for package objects
| * a12dd9c3b6 Test demonstrating SI-8085
|/  
*   5cbb5a7f62 (tag: v2.10.4-RC1) Merge pull request #3268 from adriaanm/support-3021
|\  
| * 3fa2c97853 (scala/pr/3268, adriaanm/support-3021) Report error on code size overflow, log method name.
|/  
* 2aa9da578e Partially revert f8d8f7d08d.
*   ba7bf5e229 Merge pull request #3261 from adriaanm/ticket-6426
|\  
| * 47562e7adb (scala/pr/3261, adriaanm/ticket-6426, ticket-6426) Revert "SI-6426, importable _."
* da919ec24c Merge pull request #3253 from retronym/ticket/8062
* f0d913b51d (scala/pr/3253) SI-8062 Fix inliner cycle with recursion, separate compilation

$ g log --oneline --no-merges $MB..97b9b2c06a
7e85b59550 (scala/pr/3282) SI-8085 Fix BrowserTraverser for package objects
a12dd9c3b6 Test demonstrating SI-8085
3fa2c97853 (scala/pr/3268, adriaanm/support-3021) Report error on code size overflow, log method name.
2aa9da578e Partially revert f8d8f7d08d.
47562e7adb (scala/pr/3261, adriaanm/ticket-6426, ticket-6426) Revert "SI-6426, importable _."
f0d913b51d (scala/pr/3253) SI-8062 Fix inliner cycle with recursion, separate compilation

$ g log --oneline --no-merges 97b9b2c06a..370d6d6188
c0cb1d891a (scala/pr/3312) [nomaster] codifies the state of the art wrt SI-8104

$ g log --oneline --no-merges 370d6d6188..aefe3fb844
bd4adf5c97 (scala/pr/3344) More clear implicitNotFound error for ExecutionContext
255c51b3dd (scala/pr/3329) SI-6563 Test case for already-fixed crasher

$ g log --oneline --no-merges aefe3fb844..a8122413c0
5876e8c621 (scala/pr/3345) [nomaster] SI-8114 Binary compat. workaround for erasure bug SI-7120

$ g log --oneline --no-merges a8122413c0..d5801b9eee
c91d373a78 (scala/pr/3328) SI-8111 Expand the comment with a more detailed TODO
2c770ae31a (scala/pr/3327) SI-8111 Repair symbol owners after abandoned named-/default-args

$ g log --oneline --no-merges d5801b9eee..2.10.x
9df2dcc584 (scala/pr/3364) [nomaster] SI-8152 Backport variance validator performance fix

$ g merge 97b9b2c06a
$ g merge -s ours 370d6d6188
$ g merge aefe3fb844
$ g merge -s ours a8122413c0
$ g merge d5801b9eee
$ g merge -s ours 2.10.x

```

### CODE REVIEW

**Comment by adriaanm** [comment]
https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1166/console
https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/34/console

**Comment by adriaanm** [comment]
SI-8111 can be closed once this PR is merged

**Comment by adriaanm** [comment]
checkin-manual succeeded: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1168/console

**Comment by retronym** [comment]
LGTM. Super clear presentation made it easy to review.

**Comment by adriaanm** [comment]
Thanks.

**Pull request merged**
