### PR TITLE
Avoid the parentSymbols method: less allocations.

### PR DESCRIPTION
**Pull request by diesalbla**
The "Type" abstract class defines a method "parentSymbols" that is implemented by getting the list of parents of the type, and then performing a "map" to get each parent's type symbol. This map is allocating a list. Looking at the usages of this method, we confirmed that most of the calls to this method were followed by a "fold" on the list, such as an "contains", or a "find". In some cases, the list is not used at all.

To save allocations, we replace the calls to "parentSymbols" with the calls to its implementation, "info.parents", and replace the "contains" methods with "exists(_.typesymbol)". This is another example of merging a `map` into a `fold` using the fold laws.

### CODE REVIEW

**Comment by retronym** [comment]
Analogously, we have `Symbol.ownerChain` and `Symbol.ownersIterator`, and use the latter to avoid temporary allocations.

So we could consider introducing `parentSymbolsIterator` alongside `parentSymbols` to follow this pattern while still encapsulating the fact that this comes from `.info.parents.map(...)`.

**Comment by diesalbla** [comment]
> So we could consider introducing parentSymbolsIterator alongside parentSymbols to follow this pattern while still encapsulating the fact that this comes from .info.parents.map(...).

Wouldn't that always perform two extra allocations (the `ListIterator` and the `AbstractIterator` for the `map`)? Is the `.info` field brittle enough to hide it away? 

To be clear: are you asking just to introduce the `parentSymbolsIterator` method, or to _use it_ instead of `.info.parents`?

**Comment by retronym** [comment]
Yes, there will be a fixed, small number of allocations, but that's better than something proportional of the length of the list of parents. You can get it down to one allocation with a hand-rolled iterator, rather than using `.iterator.map(f)`, but I tend to think what you've got will be okay.

**Comment by retronym** [comment]
In my allocation profile prior to this PR, I only see 1/3501 samples of allocations involving `parentSymbols`, so this wasn't really a hotspot in the first place. I'm happy enough with the addition of the `iteratorVersion`.

I'd prefer if you could use profile data to guide your future optimization efforts. This lets your work have the biggest impact, and reduces the risk of accidentally changing behaviour in refactorings.

**Review by retronym — APPROVED** [review]

**Pull request merged**
