### PR TITLE
SI-7294 Towards finality for TupleN

### PR DESCRIPTION
**Pull request by retronym**
- Treat TupleN as final under -Xfuture for static analysis
- Deprecate inheritance from TupleN.

Review by @lrytz @paulp (it's a change to a core class, so a few opinions are needed.)

### CODE REVIEW

**Comment by paulp** [comment]
@ijuma which are the too-noisy ones? I would like to move all the warning configuration into a config file and you can enable/disable them at will, it's just one of those tasks which is full of tedium.

**Comment by paulp** [comment]
LGTM other than the test case comment which mentions -Xlint (not that I think people are deriving a lot of knowledge from test case comments.)

**Comment by ijuma** [comment]
-Ywarn-nullary-unit and -Ywarn-adapted-args are the two that are currently disabled (using 2.10.1). I tried hard to keep the second one, but it was problematic due to libraries that rely on it in their DSLs (both Squeryl and lift-json have the issue if I recall correctly).

**Comment by retronym** [comment]
edited to `s/lint/future/`.

**Comment by retronym** [comment]
I agree, something as simple as a regex based warning filter would be really useful.

**Pull request merged**
