### PR TITLE
SI-7901 Bump module versions.

### PR DESCRIPTION
**Pull request by dragos**
Upgrade to the latest releases of modules. This fixes OSGi
clients, since previous module releases don't have correct
MANIFEST files.

For consistency, I bumped the partest version as well.

### CODE REVIEW

**Comment by dragos** [comment]
@jsuereth is looking into why dbuild fails to build sbt with this PR.

**Comment by dragos** [comment]
So, it looks like typesafehub/sbt-builds-for-ide#12 is merged, we'd need to trigger a rebuild here.

**Comment by dragos** [comment]
PLS REBUILD/pr-scala@de1b1d8

**Comment by adriaanm** [comment]
ping @jsuereth, @dragos, @gkossakowski, @cunei

**Comment by dragos** [comment]
@adriaanm, how do you normally bump these versions? Is my assumption correct that once new versions of modules have been published, master can depend on them? I'm not sure what I can do here, other than close it if that's not the right way, but I'd be interested to know what's the normal procedure.

**Comment by adriaanm** [comment]
yes, as soon as they are published, we should bump the versions in this file.

**Comment by adriaanm** [comment]
My understanding was that this was blocked because the sbt-republish job had hard-coded versions, rather than parsing versions.properties. (E.g., https://github.com/typesafehub/sbt-builds-for-ide/blob/master/sbt-on-2.11.x#L6 should be derived from this properties file, which is available during PR validation.)

**Comment by dragos** [comment]
Thanks, I didn't realize it was still hard-coded. I thought `versions.properties` was already used (and the reason why a lot of PRs used to fail, needing a rebase on top of Scala master when this file was added). /cc @jsuereth

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Versions have been bumped a bit more since. I'll submit a new PR with the most recent ones ASAP.

**Pull request closed without merging**
