### PR TITLE
Remove unnecessary imports and import braces

### PR DESCRIPTION
**Pull request by janekdb**

### CODE REVIEW

**Comment by rorygraves** [comment]
👍

**Comment by lrytz** [comment]
Thanks!

**Comment by SethTisue** [comment]
(was this discovered with an automated tool? if so, it might be nice, in the future, if such commits indicated what tool was used)

**Comment by dwijnand** [comment]
It would be even nicer if any such tool were setup to mechanically enforce these changes, rather than require constant supervision and/or manual maintenance: fix not just the issue, but the fact that the issue can arise. (But avoid https://xkcd.com/1319/)

**Pull request merged**
