### PR TITLE
SI-7523 Deprecate abstract methods without result type

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by lrytz** [comment]
there's a specific special case in the spec to allow it.

4.6.3 Procedures: "A procedure declaration [**not definition**] is a function declaration where the result type is omitted."

**Comment by retronym** [comment]
I think this PR is premature. You can't assume that a few days of discussion on the mailing lists is sufficient to push through this sort of change; not all interested parties would have had time to discuss. A better approach would be to ask us to schedule the item for discussion at the weekly Scala meeting.

**Comment by som-snytt** [comment]
> there's a specific special case in the spec to allow it.

Even before I look it up in the spec, I'm going to order the t-shirt.  No wait, I'll take the hoodie!

**Comment by soc** [comment]
@lrytz Yes, saw that. With this fix, the complete chapter 4.6.3 can be removed.

@retronym Agree. I just prefer having some working code to discuss.

Anyway, I can neither schedule it for discussion at the meeting, nor can I attend the meeting nor do I (or everyone else) get information out of the meeting (when were the last meeting notes published? A short search for "scala meeting report" tells me "2012/05/01".) ... so I hope you can understand that it's not and can't be of high priority for me.

**Comment by lrytz** [comment]
> With this fix

i would not call it a fix, it's a language change

**Comment by soc** [comment]
@lrytz Agree. "Fix" was meant in the sense of "killing bizarre special cases".

**Comment by lrytz** [comment]
> I just prefer having some working code to discuss

that's valuable, but it should not be in the form of a pull request IMO. these are intended for things that are agreed to go in. PRs take a lot of people's time, and objects in the PR queue should be short lived. we already have enough points to consider: does it pass the tests? is it reviewed? there should not be the question of "do we actually want that to be in?"

**Comment by soc** [comment]
Closing.

**Comment by adriaanm** [comment]
The expedient way to introduce this could be an -Xlint option. I'd be in favor of compiling with it once that lands.
No public member should have its type inferred. Especially not implicit values.

**Pull request closed without merging**
