### PR TITLE
Partial unification unconditional; deprecate -Xexperimental

### PR DESCRIPTION
**Pull request by milessabin**
Partial unification is now enabled unless `-Xsource:2.12` is specified. The `-Ypartial-unification` flag has been removed and the `-Xexperimental` option, which is now redundant, has been deprecated.

### CODE REVIEW

**Comment by Daenyth** [comment]
Does it make sense to preserve the `-Ypartial-unification` flag but have it be a no-op, printing a warning, to ease build.sbt transitions?

**Comment by milessabin** [comment]
According to @adriaanm, no, because `-Y` options were always subject to change without notice. If you can persuade him otherwise I'd be happy to update the PR.

**Comment by SethTisue** [comment]
Maybe there’s another possibility here, of doing something stronger than deprecation, namely refusing to accept the flag, but also printing something more helpful than “huh? -Ypartial-unification`? never heard of it”.

(thinking out loud)

**Comment by dwijnand** [comment]
> Maybe there’s another possibility here, of doing something stronger than deprecation, namely refusing to accept the flag, but also printing something more helpful than “huh? -Ypartial-unification`? never heard of it”.

Sounds like @eed3si9n's "Restligeist macro" idea: https://twitter.com/eed3si9n/status/770584274819055617

We have those in sbt 1 for the old sbt 0.9-0.12 operators: https://github.com/sbt/sbt/blob/v1.1.1/main-settings/src/main/scala/sbt/std/TaskMacro.scala#L129-L130.

**Comment by SethTisue** [comment]
/rebuild

(last one gave `Build timed out (after 150 minutes). Marking the build as aborted.`)

**Comment by SethTisue** [comment]
@adriaanm Jenkins seems wedged on this one, won't rebuild

@milessabin try rebasing?

**Comment by milessabin** [comment]
Rebased.

**Comment by milessabin** [comment]
This appears to have completed successfully, but is still showing as building here.

**Comment by milessabin** [comment]
synch did it :-)

**Comment by adriaanm** [comment]
The jenkins upgrade appears to have broken the job notification plugin. No idea what's wrong. The start of job notification arrives fine, end of job is logged as sent on the jenkins side, but never arrives at scabot. 🤔

**Comment by milessabin** [comment]
Rebased.

**Comment by milessabin** [comment]
Is there any more that needs to be done before this can be merged?

**Review by SethTisue — APPROVED** [review]

**Comment by milessabin** [comment]
Rebased ... also ... bump!

**Comment by milessabin** [comment]
@adriaanm is there anything blocking this from being merged now?

**Comment by milessabin** [comment]
Hurrah!

**Pull request merged**
