### PR TITLE
Align with Scala 3: Support Scala 3.5 in TASTy reader

### PR DESCRIPTION
**Pull request by bishabosha**
restores pipelining tests on windows - (3.4.0 actually fixed the underlying problem with writing to Jars)

scala 3.5.0-RC4 changed the constructor of its ConsoleReporter - so patched that here.

also the experimental definition error message changed again :)

also test compilation of std library with 3.5.0

### CODE REVIEW

**Comment by bishabosha** [comment]
Added tracked param and flexible types (i.e. ignore them, but don't crash)

reject when you see the new quote, splice, quote pattern, splice pattern.

Done as far as I see

**Comment by bishabosha** [comment]
@SethTisue @lrytz the Scala 2.13 library is refusing to build due to a warning about not being allowed to pass implicit arguments explicitly without `(using ...)` - might need some advice here or another PR needed to prepare

EDIT: for now I set to use the current dotty version for building the library - and latest for testing tasty reader

**Comment by SethTisue** [comment]
got good news for ya! `using` is already accepted, even without `-Xsource:3` (as per https://github.com/scala/scala/pull/10075)

**Comment by SethTisue** [comment]
@bishabosha this necessitates releasing 2.13.15 fairly quickly after 3.5.0 final comes out, yes? as per our usual practice?

**Comment by bishabosha** [comment]
it should be like usual yeah

**Comment by bishabosha** [comment]
@SethTisue ci looks good

**Review by SethTisue — APPROVED** [review]

**Pull request merged**
