### PR TITLE
JDK 21 (was 21-ea), sbt 1.9.6 (was .4)

### PR DESCRIPTION
**Pull request by SethTisue**
- GitHub Actions: remove JDK 21-ea, add JDK 21
- sbt 1.9.6 (was .4)

### CODE REVIEW

**Comment by som-snytt** [comment]
"And now for our special segment, Today's News in sbt..."

**Comment by He-Pin** [comment]
Use Zulu for now？

**Comment by SethTisue** [comment]
> Use Zulu for now？

Yeah we'll have to, since GitHub has now pulled `21-ea`, and that's failing jobs at https://github.com/scala/scala/actions now

**Comment by SethTisue** [comment]
Temurin folks are working on it: https://fosstodon.org/@sxa/111098188725062282

**Pull request merged**
