### PR TITLE
BitSet.iteratorFrom: proposal for a new, foreach-inspired implementation

### PR DESCRIPTION
**Pull request by nmarasoiu**
.. which is more than 10x faster, at least on sparse bitsets (with few elements and far in between). It is also true that it is slightly more complex & holds slightly more variables in the iterator closure returned. Welcoming any advice. I can also compress the code, I will push now the reduction of the boolean expression, and I could also inline the methods used just once. Also, the max(0, start), intended to safeguard for negative values, may not be needed? Thank you

### CODE REVIEW

**Comment by retronym** [comment]
The glaring omissions from scala's `BitSet` implementations is `nextSetBit` / `prevSetBit` (which are available in the corresponding Java implementation.) `nextSetBit` would be suitable as a base implementing `iterator` / `iteratorFrom`. Direct use of `nextSetBit` would be more efficient as it doesn't incur the overhead of boxing.

**Comment by retronym** [comment]
I just noticed that in 2.13.x we now have an implementation of the new `Stepper` abstraction for `BitSet`.

```
scala> val bs = scala.collection.immutable.BitSet(1, 4, 5, 9)
bs: scala.collection.immutable.BitSet = BitSet(1, 4, 5, 9)

scala> val stepper = bs.stepper
stepper: scala.collection.IntStepper with collection.Stepper.EfficientSplit = scala.collection.convert.impl.BitSetStepper@48d5ca17

scala> while (stepper.hasStep) { println(stepper.nextStep()) } // no boxing
1
4
5
9

scala> bs.stepper.iterator.foreach(println(_))
1
4
5
9
```

It could make sense to generalize `BitSetStepper` to start at value, and then change `BitSet.iteratorFrom` to call `BitSetStepper.from(this, from).iterator`.

**Comment by lrytz** [comment]
`stepper.iterator` boxes though. java8-compat had higher-order methods on steppers that would avoid boxing, but we removed them in order to have a minimal dependency in scala.collection, https://github.com/scala/scala/pull/7458/commits/81a9e4ffdeb34d107f3693bab29da88fc6659352. We can bring them back as extension methods.

**Comment by nmarasoiu** [comment]
Hi, thanks, I would have two questions:
- could you please explain to me how the stepper works internally? just out of curiosity, I did not yet understand the shifting with 6 bits and the way it works
- would it make sense to do a pull request on Scala 12 with this iteratorFrom implementation which is faster?
Thanks

**Comment by SethTisue** [comment]
@Ichoran @lrytz perhaps one of you could help with these questions, now that the 2.13.0 release madness and Scala Days madness have died down?

**Comment by lrytz** [comment]
I don't know the BitSetStepper implementation, @Ichoran did it... As for 2.12.x, if you provide a binary compatible, more efficient implementation we can certainly merge that.

**Comment by dwijnand** [comment]
@nmarasoiu sorry this has been sitting like this for so long.  Would you be interested in returning to this?  We can renew our efforts to provide you with advice and assistance.

**Comment by mkeskells** [comment]
There are other BitSet improvements in https://github.com/scala/scala/pull/9118/ https://github.com/scala/scala/pull/9059 if we can work out the the compatibility in 
https://github.com/scala/scala/pull/9141 or https://github.com/scala/scala/pull/9187

At least the benchmark should be useful :-)

**Comment by Ichoran** [comment]
@nmarasoiu - Sorry, I didn't notice this thread when it was active in June!

However, I don't understand the questions.  What do you mean by "the shifting with 6 bits"?  Do you mean the log word length?  Shifting by the log of the word length is equivalent to multiplying or dividing by the word length (but possibly faster).  So if you fit 64 bits into your underlying array (log2(64) = 6), then to look in index i, you want to actually look in bin b = (i / 64) = (i >> 6) at bit i - (b*64) = i - (b << 6).  Is that what you mean?

(You never see the number 6 there.  It's all LogWL, which could be 5 or whatever.)

https://github.com/scala/scala/blob/v2.13.3/src/library/scala/collection/convert/impl/BitSetStepper.scala is the current implementation of the stepper.

Also, the layout of BitSet did not change between 2.12 and 2.13, so the same logic as in the Stepper will work for 2.12 also.  (Is this what you were asking?)

**Comment by dwijnand** [comment]
Closing for inactivity.  But a rebase and resubmit remains possible.

**Pull request closed without merging**
