### PR TITLE
Upgrade scala-asm to 5.2-scala-2

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Jardiff of the non-bootstrapped versions (on scala-pr-validation-snapshots) is empty, except for the changes in the asm classes (which are included into scala-compiler.jar).

**Review by adriaanm — APPROVED** [review]

**Comment by mkurz** [comment]
A new version is available - `v6.0.0-scala-1`: https://github.com/scala/scala-asm/releases

**Comment by lrytz** [comment]
It's already in use since https://github.com/scala/scala/pull/6180

**Comment by mkurz** [comment]
@lrytz Yes in the 2.12 branch, however in the 2.13 it's still 5.2: https://github.com/scala/scala/blob/2.13.x/versions.properties#L23

**Comment by lrytz** [comment]
We merge 2.12.x to 2.13.x from time to time, so it will land there eventually (before the next release for sure).

**Comment by mkurz** [comment]
Alright, didn't know that. Thanks for the information.

**Pull request merged**
