### PR TITLE
Fixed SI-6092. Fixed leaky annotations

### PR DESCRIPTION
**Pull request by dragos**
and relaxed the conditions under which a try-catch is lifted out to an inner method.

Less known fact: lazy values null-out their dependent values is they're accessed only from
their initializer. The analysis is not context-dependent (meaning the owner where a reference
happens needs to be exactly that lazy value).
- Removed no-op code around positions in `LazyAnnotationInfo`
- Don't lift expressions that have no `catch` clause

The two changes combined fix a memory leak that's been plaguing the IDE: an annotation
(even when forced) would hang on to a namer, through the outer field of its call-by-name
parameter.

The memory leak test is in the IDE project (couldn't find a simple way to reproduce it outside
the IDE). I added a test to make sure the field is nulled after the lazy val is initialized.

### CODE REVIEW

**Comment by dragos** [comment]
Review by @gkossakowski, @hubertp.

**Comment by hubertp** [comment]
Looks like the test is failing. Can you have a look please?

**Comment by dragos** [comment]
Sorry... I have no idea how it passed on my system.. I'll merge 2.10.x and try again, maybe there are changes upstream.

**Comment by dragos** [comment]
Interesting, I rebased on the latest `2.10.x` and the test passes (run individually, with `partest --show-log test/files/run/nullable-lazyvals.scala`. What version of java should I use? (I'm using java 6 on Mac OS X).

**Comment by hubertp** [comment]
log says: 
java version: Java HotSpot(TM) Server VM 1.6.0_31 (1.6)

**Comment by hubertp** [comment]
With optimize?

**Comment by dragos** [comment]
Thanks! That was it. Now who fixes optimizer bugs? :)

**Comment by dragos** [comment]
Ok, it's inlineExceptionHandlers. It passes with `-optimize -Yskip:inlineExceptionHandlers`..

**Comment by hubertp** [comment]
That sounds like @VladUreche

**Comment by hubertp** [comment]
Now he has been summoned twice. That sounds serious.

**Comment by dragos** [comment]
https://issues.scala-lang.org/browse/SI-6102

**Comment by dragos** [comment]
I pushed a workaround in my test, waiting for the bot to build..

**Comment by hubertp** [comment]
lgtm

**Pull request merged**
