### PR TITLE
Merge 2.10.x into master

### PR DESCRIPTION
**Pull request by gkossakowski**
Merge remote-tracking branch 'scala/2.10.x' into master
Conflicts:
    bincompat-backward.whitelist.conf
    bincompat-forward.whitelist.conf
    src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
    src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
    src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
    src/compiler/scala/tools/nsc/util/MsilClassPath.scala
    src/compiler/scala/tools/reflect/ToolBoxFactory.scala
    src/reflect/scala/reflect/internal/Importers.scala
    src/reflect/scala/reflect/runtime/JavaMirrors.scala
    test/files/run/t6392b.check

This merge was rather involved.
Review resolution of merge conflicts in `Importers.scala` and `JavaMirrors.scala` by @xeno-by
The rest review by @retronym

### CODE REVIEW

**Comment by gkossakowski** [comment]
@xeno-by: also, please check if my merge resolution of [nomaster] commits is correct.

**Comment by adriaanm** [comment]
Sorry, I was going through the PR backlog and caused conflicts. Probably best to wait with this merge until next week.

**Comment by gkossakowski** [comment]
@adriaanm: I don't understand. Why do we need to wait?

**Comment by adriaanm** [comment]
GitHub says the PR doesn't merge

**Comment by adriaanm** [comment]
(Because of the [merge] conflicts I created merging the other PRs into master)

**Comment by gkossakowski** [comment]
Well, then I need to perform another merge, that's not a big deal. An update will come shortly.

**Comment by gkossakowski** [comment]
@adriaanm: I synced with latest master. In case there are more conflicts caused by other PRs being merged I can easily sync again.

**Comment by adriaanm** [comment]
Ok great.

**Comment by adriaanm** [comment]
Adding the "on-hold" label to indicate it should be merged last. Don't want to risk causing conflicts in PRs currently open.

**Comment by xeno-by** [comment]
My [nomaster] commits lgtm

**Comment by adriaanm** [comment]
failure in https://scala-webapps.epfl.ch/jenkins/job/pr-scala-rangepos/910/consoleFull

**Comment by xeno-by** [comment]
Something's not right. When I c/o `gkossakowski:merge-2.10.x`, compile it and run `run/t7733` (one of the failing tests), it comes out green.

**Comment by gkossakowski** [comment]
Same here. I cannot reproduce failing `run/t7733`. However, I could reproduce other failures.

**Comment by gkossakowski** [comment]
I fixed test failures I could reproduce. Let's see if this helps.

**Comment by adriaanm** [comment]
> Something's not right. When I c/o gkossakowski:merge-2.10.x, compile it and run run/t7733 (one of the failing tests), it comes out green.

did you run it under -Yrangepos?

**Comment by xeno-by** [comment]
Shouldn't affect this particular test, but I ran it anyway. `SCALAC_OPTS=-Yrangepos partest run/t7733`, with the same successful result.

**Comment by retronym** [comment]
You might just shunt t7733 to `disabled` and reopen the ticket pending investigation, rather than blocking this merge. I'll review the rest of this in more detail tomorrow.

**Comment by retronym** [comment]
LGTM, aside from the test failure.

**Comment by gkossakowski** [comment]
I'll be looking into test failure today.

**Comment by gkossakowski** [comment]
I tried to reproduce this problem in multiple ways and I failed. I'll start from scratch.

**Pull request closed without merging**
