### PR TITLE
Deprecate all JVM 1.5 targets and make 1.6 default.

### PR DESCRIPTION
**Pull request by gkossakowski**
Add a check if deprecated target is being used. I put
that check into `checkDeprecatedSettings`. I tried to
invent some general mechanism for deprecating choices
in ChoiceSetting but I gave up eventually. It wasn't
worth it the complexity. Also, with current approach
I'm able to provide nice, customized deprecation
warning.

Make `jvm-1.6` a default backend.

Altered test for SI-5957 because it crashes the backend.
However, the problem is not with backend but with symbol
creation. We get two different symbols with the same
internal name and both are used in trees that reach
GenASM. See SI-6109 for details.

Also, I went through `build.xml` and I updated all `javac`
invocations so they target 1.6 byte-code as well.

Review by @magarciaEPFL, @paulp and @jsuereth.

### CODE REVIEW

**Comment by SethTisue** [comment]
joy!

**Comment by paulp** [comment]
Jenkins should be configurable to make multiple attempts to hit the repo;
this is another brand of spurious error we could live without.

```
ERROR: Problem fetching from origin / origin - could be unavailable.
```

Continuing anyway
    hudson.plugins.git.GitException: Command "git fetch -t
git@github.com:scala/scala.git
+refs/heads/_:refs/remotes/origin/_" returned status code 128:
    stdout:
    stderr: ssh_exchange_identification: Connection closed by remote host

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by magarciaEPFL** [comment]
LGTM

**Pull request merged**
