### PR TITLE
Harden against synthetics being added more than once.

### PR DESCRIPTION
**Pull request by paulp**
Don't add synthetic methods if they already contain synthetic
methods from the set we're about to add.

### CODE REVIEW

**Comment by paulp** [comment]
I agree this patch is not risky, so if it is fixing a regular crasher it is being the wrong kind of conservative to exclude it from RC2.

**Comment by adriaanm** [comment]
How do we know the crashes are because of this bug? Or that they will be resolved by this fix?

Should we break our RC policy for something that may reduce the frequency of something by an unknown amount?

When we went into RC mode we all agreed we were basically ready to ship, except for some potentially extremely serious bugs that we didn't know of at the time (we knew the presentation compiler was unstable before going into RC mode AFAIK), and that could only be discovered by unleashing an RC on our users so that they can test it for us.

Should we have staid in Milestone mode longer?

**Comment by jsuereth** [comment]
Martin, 

As discussed w/ Adriaan and Martin, this will have to be targeted for 2.10.1, which already has RC1 dates.  

For further notice:

The policy during an RC process is any _blocker_ fixes.  "Blocker" during RC refers to anything that has absolutely no workaround.   Pull requests _must_ include tests and be well written.

This PR is fine to target 2.10.1, but not 2.10.0 at this point.  It's a few months behind the 8 ball.  Doors have closed, but 2.10.x is open and inviting.  They even have free cookies over there.

**Comment by jsuereth** [comment]
Whooops! wrong pull request.

**Comment by jsuereth** [comment]
SO - This is targetting 2.10.1 (had my windows crossed).    Martin gave it an LGTM, but without tests I'd like to see at least one more.  @dotta still ok with this one?

**Comment by dotta** [comment]
My take on this is here: https://github.com/scala/scala/pull/1523#issuecomment-9742431

It would be more meaningful to get @adriaanm opinion.

**Comment by dragos** [comment]
I don't think it is the right decision to move this to 2.10.1. We all agreed that presentation compiler bugs are blockers (they definitely have no workaround). I specifically remember this discussion with you Adriaan. If that's no longer the case, then yes, we should have stayed in milestone mode longer.

Is the missing test the only problem? I'm pretty sure this code should have been written like that in the first place.

**Comment by dotta** [comment]
@dragos I think you should move this comment in the [PR against 2.10.0-wip](https://github.com/scala/scala/pull/1523#issuecomment-9742431). Josh is only waiting for an additional LGTM to merge this in 2.10.x.

**Comment by jsuereth** [comment]
@dragos - As I stated elsewhere, with _no open ticket_ marked blocker, the only context we had here was "nice for IDE".   I hope you agree that a bug fix with no open ticket and no test _and_ merely covers over a symptom without understanding the cause does not qualify for inclusion during an RC (pre-RC is fine of course).

I see you've taken care of the ticket and it is indeed a blocker.   Now we can talk about this fix.

**Comment by adriaanm** [comment]
Iulian (@dragos), I'm all for fixing blocking presentation compiler bugs. We crucially rely on the work of you and your team when hacking SBT, the compiler and so on. We want (and need) it to be every bit as good as you want it to be.

However, I am against fixing them blindly (without some form of testing, be it manual or otherwise) and without planning (i.e. tracked as a ticket). I know these things are hard to test, but a shot in the dark is not appropriate for an RC cycle. It needs to be tested (manually, at the very least) to verify that it actually improve the situation. Otherwise, we're taking the risk of a regression (sorry, I don't buy the "look, it's such a simple fix, what could possibly go wrong!?" argument simply on its own merit.) without any tangible benefit.

A bug cannot be identified as a blocker without some testing (can it be worked around? does it actually happen that often? does it happen less often after the fix? does everything else still work after the fix?). Maybe this testing has happened in private, but I have not seen any traces of it anywhere.

Part of the reason why we must be reluctant to fix things during RC cycles is to get milestones to be taken more seriously. Otherwise, we'll never get out of the vicious cycle of milestones-not-considered-interesting-enough-to-test-against-and-thus-we-only-discover-bugs-during-the-RC-cycle-when-it's-too-late. Milestones need to become interesting enough for people to use and test them so we can track our progress/regress on a monthly basis. RC cycles should be short.

**Comment by adriaanm** [comment]
Closing this request in favor of the old one for 2.10.0-wip

**Pull request closed without merging**
