### PR TITLE
Set max-width for subpackage-spacer (fix https://github.com/scala/bug/issues/10354)

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by lrytz** [comment]
@Atry thanks! Could you update the commit message according to https://github.com/scala/scala/blob/2.12.x/CONTRIBUTING.md#clean-commits-clean-history (summary in first line, some description, "fixes ..." at the end)?

**Comment by Atry** [comment]
@lrytz commit message updated

**Comment by lrytz** [comment]
Thanks! @estsauver, would you like to review this?

**Comment by lrytz** [comment]
Tested locally

**Review by lrytz — APPROVED** [review]

**Pull request merged**
