### PR TITLE
Describe type parameter interpolation in @implicitNotFound documentation

### PR DESCRIPTION
**Pull request by ceedubs**
Using this feature is necessary for helpful error messages, so it should be documented.

### CODE REVIEW

**Comment by som-snytt** [comment]
There is an issue to allow general string interpolation, so I wouldn't specify "EL syntax."  I would just say, "type parameters in expression syntax `${A}` are interpolated using corresponding type arguments. (No interpolator prefix is required.)"

https://issues.scala-lang.org/browse/SI-7411

Types aren't values, obviously; so that would need to be specified.

Too bad "Missing $T" identifier syntax isn't supported, in anticipation of 7411.

**Comment by adriaanm** [comment]
Thanks, @ceedubs! I agree it may not be immediately obvious what "EL syntax" means, though.
Here's my suggestion of making this more concrete:

```
When an implicit of type `C[T1,..., TN]` cannot be found, and `C` (with type parameters `X1`,...,
`XN`) has the `@implicitNotFound` annotation, all occurrences of `${Xi}` in the string `msg` will
be replaced by the string representation of the corresponding type argument `Ti`.
```

**Comment by som-snytt** [comment]
What he said.

**Comment by ceedubs** [comment]
Excellent suggestions. @adriaanm I just added a tiny bit about the result being used for the error message. How does that look?

**Comment by adriaanm** [comment]
Thanks. Sorry to nitpick, but I find "default ImplicitNotFound error message" confusing. This leads me to the following solution: make the description more direct:  

> To customize the error message that's emitted when an implicit of type `C[T1,..., TN]` cannot be found, annotate the class `C` with `@implicitNotFound`. Assuming `C` has type parameters `X1`,..., `XN`, the error message will be the result of replacing all occurrences of `${Xi}` in the string `msg` with the string representation of the corresponding type argument `Ti`.

Also, could you please squash these commits by going a git rebase -i master, replacing the `pick` in each but the first line in the rebase todo list by `s` (for squash).

**Comment by adriaanm** [comment]
LGTM -- Thanks!

**Pull request merged**
