### PR TITLE
add scaladoc canonical name

### PR DESCRIPTION
**Pull request by jamesward**
One of the challenges I've had learning and using Scala is the use of symbol methods like `++:` because they lack a name.  Without a name symbols are hard to comprehend, search for, and talk about.  I find it is hard to mentally parse code that uses symbols that I don't have a name for.  Also, trying to search StackOverflow or DuckDuckGo for symbols is usually impossible or difficult.  An attempt was made to use a `Google Tag for Scala` (gt4s) that would provide a searchable name for symbols.  However this doesn't seem to have caught on possibly because the tag names were derived (lacking meaning) and because the ScalaDoc UI didn't plainly expose them.

This pull request tries a different approach by adding a new ScalaDoc tag, `@canonical` which allows symbol authors to provide a canonical name for a symbol.  That name is then displayed in the ScalaDoc signature:
scaladoc-canonical

This pull request includes two symbol names in `GenTraversableLike.scala` which are likely the wrong names but included as examples.

### CODE REVIEW

**Comment by dhinojosa** [comment]
Love it.

To bring it even further, for every symbolic method name there should be a alternate canonical method name much the same way as `/:` and `foldLeft` work.  This way `@canonical` would not only provide a description but perhaps a cross-reference to the canonical method that does the same thing.  Leave it to the programmer to decide which one to use.

**Comment by jamesward** [comment]
Thanks @dhinojosa.  What I'd really love is the ability to provide aliases, like: `def /:,foldLeft` but that is a much bigger change.  Apparently due to operator precedence `/:` and `foldLeft` can actually work differently so today they can't be considered the same like an alias would be.  If we did someday get aliases it would be nice to always use the canonical name in the bytecode to make debugging easier.

**Comment by som-snytt** [comment]
This is especially true if an operator is "called something" in the literature.

In pre-K, they called it "take-away", and now in 1st grade, I insist my kid call it subtraction. Both are three syllables.

BTW, I'm pretty sure `++:` is the `seamonkey` operator.  Or was that `++>:`?  Maybe one was baby seamonkey.

**Comment by adriaanm** [comment]
@jamesward, great stuff! A test failed, unfortunately. Let me know if you need help diagnosing it.

**Comment by jamesward** [comment]
Thanks @adriaanm. Diagnosing now.

**Comment by jamesward** [comment]
Looks like Jenkins rebuilt against the wrong commit.  But there is another job still running against the right one.  We'll see what happens.

**Comment by jamesward** [comment]
I think I should also integrate the canonical name into the index & search.  So maybe we should hold off until that is done.  WDYT @adriaanm?

**Comment by heathermiller** [comment]
Cool stuff!! :)

You'd have to work out a way to include it in the index, not really the search – searching only shows "entities" (classes/objects/traits) and not members. The index shows members. Perhaps if `@canonical` also worked for entities as well, it'd make sense to show in the search?

Also – this approach makes it so two "names" are concatenated after the `def` in the list of members. The "canonical" name is listed first. I'm not sure that's the best approach – while you're right that we should have intelligible names for some of these symbols, it's just that putting `addCollection` (the canonical name) before `++` (the real name) might imply that the actual name of the method is `addCollection` and not `++` which might lead to some confusion. People might think that they can do `List(1, 2) addCollection List(3, 4)` or something, when indeed that's not the case.

Alternatively, maybe one idea is to put the "canonical" name following the signature? so in the example highlighted above, it could look something like:

**def ++[B](that: GenTraversableOnce[B]): Seq[B]** _(addCollection)_

**Comment by jamesward** [comment]
Yeah, I agree this could be confusing.  If it is at the end I think it will be easy to miss, especially with long signatures.

What about on a new line, like:

```
def ++[B](that: GenTraversableOnce[B]): Seq[B]
Canonical / Searchable Name: addCollection
[use case] Returns a new sequence containing the elements from the left hand ...
```

**Comment by heathermiller** [comment]
True, good point. Yeah, putting it on the next line is also a good idea, looks great!

**Comment by heathermiller** [comment]
Ah, btw, something that might be interesting/of use is: http://scalex.org/
It doesn't explain much about what a given method does, but it makes it easier to globally search for some method.

**Comment by jamesward** [comment]
Cool.  I'll make that change and get the canonical name into the index.

**Comment by heathermiller** [comment]
Awesome :)

**Comment by dhinojosa** [comment]
I still would like a cross reference if that is possible, for example `++` should cross reference `union` since that is a method that I believe does the same thing.  Perhaps have a canonical method name for every symbolic method name. 

```
scala> List(1,2,3) ++ List(1,2,3)
res12: List[Int] = List(1, 2, 3, 1, 2, 3)

scala> List(1,2,3) union List(1,2,3)
res13: List[Int] = List(1, 2, 3, 1, 2, 3)
```

**Comment by gkossakowski** [comment]
@jamesward: this is considered to be included in M5 release but has to be reviewed and merged by Wednesday (Sept 4th).

**Comment by jamesward** [comment]
Ok, this is now on a new line.
canonical-new-line

But I still want to get the canonical name into the index.  Investigating that now.

**Comment by cvogt** [comment]
This approach seems weird to me. addCollection is not the name of the method. Calling it "canonical name" and making it camel cased (like a method name) is misleading.

I very much like two aspects of your idea, though: improving searchability and textual names for symbolic methods.

Regarding textual names, why not just add them as actual (delegating) methods to the standard library? These names should be well chosen, though, not ad-hoc. A possibly better alternative to "addCollection" would be "concat" for example.

Regarding seachability, we could think about allowing to just add keywords to methods, which appear in the index. Less misleading and more universal. This would allow us to improve searchability not only for symbolic methods, but also other methods, where Scala newbies are likely to search for the terminology other languages use instead of the method name we chose for Scala.

**Comment by cvogt** [comment]
I thought more about (callable) textual aliases for symbolic method names. Probably a bad idea. It would give people who overdo symbolic operators an excuse to do it even more and require people who read code written against such an API to likely have to know both, the symbolic and the textual name.

I really like the keywords idea for improving searchability though. WDYT :)?

**Comment by som-snytt** [comment]
I remember a presentation where they called `|@|` the oink operator.  At least I think I remember that.  Google only yields http://pitchfork.com/news/37608-oink-operator-found-not-guilty/ and similar.

But supposing someone did like to call it that, it would be fun if you could search on that colloquial term.

And similarly for less scalaz-ish operators, and so on.

I'm not sure off-hand where the best place to declare such colloquialisms would be.

Also +1 for the use case of newbies searching for common terms.  It's probably not reasonable to expect a feature where "biggest" yields "max", but something in that direction. (Someone on the ML just needed an expert to point out max in lieu of sorted.last, so the use case is not far-fetched.)  (Maybe -Xlint could warn on idioms like sorted.last, if there were a compilation of such misusages.)

**Comment by jamesward** [comment]
@cvogt The name `addCollection` is definitely just an example.  One that actually highlights the need for a canonical name since I don't know what to call it.  :)

Apparently the problem with using a delegate method is that the delegate and target could have different precedence which means the behavior could differ between the two.  So unless Scala had a way to provide an actual method alias this doesn't seem like a possible option.

Can you describe the keyword idea more?  It sounds like what you are describing is essentially what the canonical name is intended to be.

**Comment by cvogt** [comment]
@jamesward You are right. I only found the term "canonical name" misleading. If you rename @canonical to @keywords that's basically it. It should be intended though that you can use multiple keywords. Allowing multi-word keywords may be worth a consideration and using let's say "," as the separator.

**Comment by jamesward** [comment]
I don't think that `@keywords` accomplishes what I'm after.  I want to know what to call these symbolic methods.  Symbolic things are symbols for something that have a name.  To me a keyword doesn't assign a name.  And if we can have multiple, then I no longer know what to call the thing or what to search for.  What I'm really after is THE name.  For instance, I don't think the name of `++` is `plus-plus` since that doesn't actually describe anything about what it does.  Perhaps the name is `concat` but then how is it different from `++:`?  That is the kind of confusion I think we need to clear up via names.  But since these can't technically be names (since they can't actually be referenced by their names in code), they are just the canonical name.

**Comment by cvogt** [comment]
Thank you, I understand a lot better now what you are trying to achieve and you are right @keywords does not accomplish what you're after. I am still a bit scared that "canonical names" that look like method names could lead to confusion for new Scala users. But you're approach makes a lot more sense now. Thank you for the clarification.

**Comment by jamesward** [comment]
Yeah, I agree with you that the camel casing does make it seem like the canonical name could be used in code.  And that is a problem.  Perhaps the canonical name for `++` on `GenTraversableLike` should be `Concat Collections`?  That would give it a name and give me something to search for.  It just isn't as easily searchable / unique as `concatCollections` or `Concat-Collections`.  Or maybe we just need a style guide for the canonical name.  Avoiding spaces would definitely help with searchability which I think was the original motivation for the camel casing.

**Comment by jamesward** [comment]
PLS REBUILD/pr-scala@52574d7

**Comment by jamesward** [comment]
I think this is ready to go with the exception of needing better example canonical names.  Any suggestions on what those should be?

**Comment by cvogt** [comment]
For ++, Java calls it addAll(http://docs.oracle.com/javase/7/docs/api/java/util/Collection.html), Python calls it concat (http://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range), Haskell calls it append (http://www.haskell.org/ghc/docs/latest/html/libraries/base/Data-List.html).

**Comment by jamesward** [comment]
What does Scala call it?  And what would the name be for `++:`?

**Comment by retronym** [comment]
I don't have answers to these questions, but I would like to plug SymbolHound: http://www.symbolhound.com/?q=%2B%2B%3A

**Comment by retronym** [comment]
I would also offer my opinion that coming up with the canonical names is likely a bigger task than providing this facility. We also have a bad track record of following through with that sort of thing (e.g. we have a new ability to deprecate  extension from a class, but have only used it once or twice in the standard library.)

So I'd like to see a more substantial set of these names added as part of this request. By doing so, we are likely to learn something more about the requirements.

**Comment by cvogt** [comment]
I usually call it "concatenate" when talking to people. Regarding ++:, maybe "prependAllTo", but I question if a canonical name would make sense for ++:, which only differs in a very subtle way from ++, which is hard to reflect in a name. Also ++: is probably rarely used, so that people would likely not even remember the name if it had one.

I am still a little suspicious about the usefulness of this whole feature. What are your driving use cases? I understand that this suddenly allows talking about operators using standard textual names, but has this been a problem? Regarding searchability, multiple non-unique keywords would improve the situation significantly and not force us to find the perfect canonical name. We could just add commonly used synonyms. Camel casing only improves searchability if you know exactly what you are searching for. Otherwise Google is better at matching text against white-space- or dash-separated words.

**Comment by dhinojosa** [comment]
@jamesward @cvogt I thought it was `union` https://github.com/scala/scala/pull/2872#issuecomment-23292655

**Comment by cvogt** [comment]
@dhinojosa union sounds more like a set operation to me...

**Comment by gkossakowski** [comment]
Since there's no definitive conclusion (yet) on the status of this PR I'd like to defer it until M6 so we have enough time for discussion.

**Comment by jamesward** [comment]
Where is the best place to have this discussion?  Here or the scala-internals list?

**Comment by retronym** [comment]
scala-internals will have a broader audience. Make a convincing argument that we'll end up with more than a few instances of these, and that we have a clear and cogent way to pick the names. This is a little harder for a project without a tech writer.

**Comment by gkossakowski** [comment]
It doesn't merge anymore and it seems like consensus hasn't been reached it. Please reopen once remaining issues are fleshed out.

**Pull request closed without merging**
