### PR TITLE
kills introduceTopLevel

### PR DESCRIPTION
**Pull request by xeno-by**
As we've figured out from the practice, introduceTopLevel is seductively
useful but unfortunately not robust, potentially bringing compilation
order problems.

Therefore, as discussed, I'm removing it from the public macro API.
Alternatives are either: 1) cast to Global and invoke compileLate,
2) use macro paradise and experiment with macro annotations:
http://docs.scala-lang.org/overviews/macros/annotations.html.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym @adriaanm

**Comment by retronym** [comment]
LGTM. I'm happy to shed this code. I support the removal without deprecation (we deprecated APIs in scala.reflect during 2.10.x but always reserved the right to make breaking changes in 2.11.0), so long as our PR validation chain of projects isn't using this somewhere.

**Comment by gkossakowski** [comment]
@retronym: what do you mean by PR validation chain exactly?

@xeno-by: never recommend people to cast to Global and use functionality from there because we'll be removing stuff from there. Also, I find compileLate to have very iffy semantics so it's probably not a good idea to use it from anywhere.

**Comment by xeno-by** [comment]
@gkossakowski What would you propose as a replacement fo `compileLate`? This is in essence very similar to what IDEs do and what we do when compiling scala-library.jar, right?

**Comment by gkossakowski** [comment]
@xeno-by: using BrowsingLoaders or equivalent. Ideally, we should create all top-level symbols before we start forcing infos. This way we would have clearly defined stages of populating the symbol table.

**Comment by xeno-by** [comment]
@gkossakowski Changed the recommendation to a generic "delve into internals" for now.

As for `BrowsingLoaders`, doesn't compileLate do essentially the same wrt entering symbols? It will take a given compilation unit and immediately name it, which eagerly creates and names top-level symbols.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
LGTM

**Comment by retronym** [comment]
This will have to be rebased and resubmitted after a `push -f` incident. Details: https://groups.google.com/d/msg/scala-internals/ND_AwFBT4Ww/RGJetofIDpMJ

**Comment by xeno-by** [comment]
Done: https://github.com/scala/scala/pull/2843

**Pull request merged**
