### PR TITLE
Dependent & precise result type for 'implicitly'

### PR DESCRIPTION
**Pull request by adriaanm**
Let's see what the test suite says

### CODE REVIEW

**Comment by adriaanm** [comment]
Looks like `T` is not constrained when comparing the result type (`e.type`) to the expected type.

**Comment by SethTisue** [comment]
@xuwei-k has a ticket on this: https://github.com/scala/bug/issues/11124

**Comment by adriaanm** [comment]
Yeah this will be harder than I thought.

**Pull request closed without merging**
