### PR TITLE
Another bug bites virtpatmat's dust.

### PR DESCRIPTION
**Pull request by retronym**
Test case closes SI-5029.

In 2.9, one saw:

``` scala
test/files/pos/t5029.scala:2: error: unreachable code
        (Vector(): Seq[_]) match { case List() => true; case Nil => false }
                                                                    ^

[[syntax trees at end of explicitouter]]// Scala source: t5029.scala
package <empty> {
  final object Test extends java.lang.Object with ScalaObject {
    def this(): object Test = {
      Test.super.this();
      ()
    };
    {
      <synthetic> val temp1: Seq[_$1] = (scala.`package`.Vector().apply[Nothing](immutable.this.Nil): Seq[Any]);
      if (temp1.isInstanceOf[List[A]]().&&(temp1.asInstanceOf[List[A]]().isInstanceOf[object Nil]()))
        {
          true
        }
      else
        throw new MatchError(temp1)
    }
  }
}
```

### CODE REVIEW

**Comment by adriaanm** [comment]
thanks for going through all these! this one's more of an un-feature for now, though (still working on unreachability/exhaustivity), but it's good to have the test case already!

**Comment by adriaanm** [comment]
right, sorry didn't spot that one right away -- glad (though not surprised ;-)) the implementation did :-)

**Comment by retronym** [comment]
Yep, needs a bit more thought.

2.10:

```
scala> (Vector(): Seq[_]) match { case List() => true; case Nil => false }
res0: Boolean = false
```

2.9

```
scala> (Vector(): Seq[_]) match { case List() => true; case Nil if 1 < 2 => false }
<console>:8: error: unreachable code
              (Vector(): Seq[_]) match { case List() => true; case Nil if 1 < 2 => false }
                                                                                   ^
scala> (Vector(): Seq[_]) match { case List() if true => true; case Nil => false }
warning: there were 1 unchecked warnings; re-run with -unchecked for details
scala.MatchError: Vector() (of class scala.collection.immutable.Vector)
        at .<init>(<console>:8)
        at .<clinit>(<console>)
```

**Comment by adriaanm** [comment]
actually the 2.10 behaviour, I think, is as spec'ed, since `List`'s `unapplySeq` is only applicable to a `List[_]`, but `Nil == (Vector(): Seq[_])`  (the eq vs == waters are a bit murky, but we'd break lots of code going to eq in this case)

**Comment by retronym** [comment]
More thought called, and told me this.

``` scala
scala> List.unapplySeq(List())
res10: Some[List[Nothing]] = Some(List())

scala> List.unapplySeq(Vector())
<console>:8: error: type mismatch;
 found   : scala.collection.immutable.Vector[Nothing]
 required: List[?]
              List.unapplySeq(Vector())
                                    ^

scala> List() == Vector()
res12: Boolean = true
```

`unapplySeq` comes from `GenSeqFactory`.

``` scala
  def unapplySeq[A](x: CC[A]): Some[CC[A]] = Some(x)
```

It's unfortunate to the point of being dangerous that `case List()` and `case Nil` don't mean the same thing, but given that we're using `unapplySeq` there doesn't seem to be any need for the yet-to-be-implemented exhaustiveness/reachability checking here: Both cases are statically reachable.

**Comment by paulp** [comment]
Be aware that the implementation selectively rewrites List() to Nil.  This is unfortunate to the point of inducing hulk-like breakdowns in extempore - it cost me so much time once.  [Source](https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L2970).

**Pull request merged**
