### PR TITLE
SI-8502 Improve resiliance to absent packages

### PR DESCRIPTION
**Pull request by retronym**
When unpickling a class, we create stub symbols for references
to classes absent from the current classpath. If these references
only appear in method signatures that aren't called, we can
proceed with compilation. This is in line with javac.

We're getting better at this, but there are still some gaps.
This bug is about the behaviour when a package is completely
missing, rather than just a single class within that package.

To make this work we have to add two special cases to the unpickler:
- When unpickling a `ThisType`, convert a `StubTermSymbol` into
  a `StubTypeSymbol`. We hit this when unpickling
  `ThisType(missingPackage)`.
- When unpickling a reference to `<owner>.name` where `<owner>`
  is a stub symbol, don't call info on that owner, but rather
  allow the enclosing code in `readSymbol` fall through to
  create a stub for the member.

The test case was distilled from an a problem that a Spray user
encountered when Akka was missing from the classpath.

Two existing test cases have progressed, and the checkfiles are
accordingly updated.

Review by @gkossakowski

### CODE REVIEW

**Comment by gkossakowski** [comment]
LGTM. Needs rebase, though.

**Comment by gkossakowski** [comment]
Ping @retronym

**Comment by gkossakowski** [comment]
Ping @retronym again.

**Comment by retronym** [comment]
> Ping @retronym again.

`git pong -f`

I'm working without access to mains power in the aftermath of the Brisbane super storm. This rebase was hand-cranked.

**Comment by gkossakowski** [comment]
LGTM again.

It's great to see that even a super storm can't stop you! :fist:

**Pull request merged**
