### PR TITLE
Remove scala.Symbol literal singleton types

### PR DESCRIPTION
**Pull request by smarter**
Symbol literals may be removed in the future, as discussed in
https://github.com/scala/scala-dev/issues/459. SIP-23 added literal
singleton types for all supported literals, but it seems more prudent to
not allow Symbol literal singleton types until we're sure that Symbol
literals will not be dropped.

### CODE REVIEW

**Comment by smarter** [comment]
Bootstrapping is a bit messy. I've bumped the pickling format version to 5.2 but it should really either be 5.0 (since it's exactly the same as before) or 6.0 (if we insist on monotonicity, since it's not backwards-compatible with 5.1), but either of these things breaks the tests since apparently we run the tests with the standard library compiled with STARR. So it seems like doing a major bump of the pickling format is impossible, how was this done in the past?

**Comment by adriaanm** [comment]
I agree, we shouldn't add stuff we know will cause migration pain. Should just String instead of Symbol literals. What do you think, @milessabin?

**Comment by milessabin** [comment]
I take the position that if there are literals then there should be corresponding literal types.

If Dotty is going to remove symbol literals then the literal types should go with them. In the meantime I think it would create more irregularity in Scala to take them out now.

**Comment by milessabin** [comment]
FTR I'm all in favour of symbol literals being removed from Dotty.

**Comment by smarter** [comment]
> I take the position that if there are literals then there should be corresponding literal types.

The problem is, if Symbol literal types exist they need to be present in the pickled format, if Scala 2.14 ends up using TASTY as a backend, that means that they need to be part of TASTY and handled by Dotty. It also means that removing them would be a breaking change for TASTY, which is exactly the kind of things we don't want to do. Alternatively you could introduce the feature in 2.13 and remove it in 2.14, but then what's the point, except confuse and make it harder for users to upgrade?

**Comment by milessabin** [comment]
@smarter I agree that that sounds awkward, but I think I would be more concerned about inflexibility in TASTY if what you describe is really the case. Is there any current TASTY documentation you can point us at?

**Comment by smarter** [comment]
We don't have worked out documentation yet, the best I can give you is the comment on top of https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/tasty/TastyFormat.scala

>  I think I would be more concerned about inflexibility in TASTY if what you describe is really the case.

I don't understand what you mean, this isn't specific to tasty, this is just the definition of an incompatible change: if a feature is removed from a format, then any existing file of this format using this feature cannot be used with a tool that implements the new version of the format.

**Comment by xeno-by** [comment]
I suggest that before merging this PR, we go through the SIP process. For better or worse, symbol literals are part of the language now and are even part of the pervasive metadata format, so the potential for breakages is non-trivial and should be discussed by the SIP committee.

**Comment by smarter** [comment]
I disagree.  This PR is about disallowing symbol literals as singleton types, not about removing symbol literals. Literal singleton types are a new feature of 2.13 so nothing will break.

**Comment by xeno-by** [comment]
@smarter Literal singleton types have been formally accepted by the SIP committee in https://docs.scala-lang.org/sips/42.type.html. As a committee member, I am against informally backing out of anything that we formally ratified.

**Comment by smarter** [comment]
Ok, so can we agree that this should be decided at the next SIP meeting? There's not much time left until 2.13 RC1 and it's binary compatibility requirements kick in.

**Comment by smarter** [comment]
In fact, since this change may require a new starr (still not sure about that, see my first comment), it should be done before the M5 release ideally.

**Comment by xeno-by** [comment]
> Ok, so can we agree that this should be decided at the next SIP meeting?

I'm not sure whether the process allows for on-the-spot decisions, but I'll leave that to the process lead (/cc @jvican). Otherwise, I don't mind discussing this topic at the next meeting if it makes it into the meeting agenda.

**Comment by jvican** [comment]
This wasn’t in my radar, thanks for looping me in @xeno-by. I’ll add this to the next sip meeting, it’s definitely something that needs a formal discussion and approval of the Committee. @smarter can you create a small sip motivating this change so that we can discuss it in our upcoming meeting?

**Comment by smarter** [comment]
Does this really really need a SIP? I think @adriaanm understands the issue well enough and will be present at the meeting.

**Comment by jvican** [comment]
Yes, it needs it so that we can all discuss it and go through the normal number-review procedure. A short proposal with a clear motivation suffices, nothing fancy.

**Comment by sjrd** [comment]
I suggest a new concept:a SIP *amendment*, which wouldn't need to be numbered nor reviewed for months etc. but would just be a lightweight way to amend an approved SIP before it has reached a production version. It would basically be two paragraphs (what changes and why) and could be dealt with within one meeting.

**Comment by jvican** [comment]
It sounds like a good idea, but how would you know that such an amendment wouldn’t take more time to review and approve? When to draw the line between that and a proposal ?

Technically speaking, there’s no reason why a proposal cannot have a short introduction and motivation (two paragraphs as you mention) and be numbered and approved in the same day. People associate sips with heavyweight proposals but that ain't need to be the case!

A proposal may be an amendment. And we’ll need one if we want to discuss this in our next meeting... it should take 30 min, really.

**Comment by SethTisue** [comment]
M5 is now imminent. I suggest we merge this for M5 and then revert it later if the SIP committee decides we need to. @adriaanm wdyt?

(removes Scala-team hat, dons SIP-committee hat)

Speaking as a SIP committee member, I will certainly listen with an open mind to any discussion on this at the next meeting, but: we've already had a fair amount of discussion right here on the ticket, and so far I think the TASTY argument trumps the consistency argument. Especially since `Symbol` is pretty minor, obscure stuff.

**Comment by xeno-by** [comment]
Why not wait until the SIP committee decision before merging? I understand that M5 implies a feature freeze, but if lifting the feature freeze for a revert of this PR is on the table, then it would make sense for lifting the feature freeze for a merge of this PR to also be on the table.

@SethTisue I agree that this is a pretty minor language feature, but I would still like to suggest that we don't set the precedent of cutting corners, especially on the verge of the Scala 2 to Scala 3 transition, where we'll have to apply unprecedented rigor to ensure a smooth migration path for the Scala community.

Moreover, as proposed in https://github.com/scala/scala/pull/6719#issuecomment-410844147, let's set aside some time during a SIP meeting (e.g. the next one) to discuss the role that the SIP committee should play in vetting changes to the Scala compiler. E.g. should we discuss deprecation warnings for language features? What kind of compatibility guarantees should we uphold? Etc etc. I can volunteer to kickstart a discussion thread at contributors.scala-lang.org. /cc @jvican

**Comment by adriaanm** [comment]
Relative to the impact of this PR (removing something that has not shipped in a final release, which shouldn't have been added in the first place), I find what you're proposing too heavyweight. Given how full the SIP plate is with 2.14/3.0 stuff, I would argue the opposite: let's keep our process focussed on the big picture, and not sweat the small stuff.

I'm merging this PR. Happy to discuss this particular change and the meta level at the next SIP meeting. If the committee feels this needs to be reverted, we can do so for RC1.

**Comment by adriaanm** [comment]
https://github.com/scala/docs.scala-lang/pull/1127

**Comment by milessabin** [comment]
@smarter This appears to have broken `scalacheck/testOnly scala.reflect.quasiquotes.UnliftableProps`.

@adriaanm The fact that this passed CI suggests that `scalacheck/test` isn't being run ... is that intentional?

**Comment by SethTisue** [comment]
> The fact that this passed CI suggests that scalacheck/test isn't being run ... is that intentional?

https://travis-ci.org/scala/scala/jobs/398908991 shows:

```
[0m[[0minfo[0m] [0m[32m+ unliftable.unlift scala.symbol: OK, proved property.[0m
[0m[[0minfo[0m] [0mElapsed time: 0.005 sec [0m[0m
```

and https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/2803/artifact/target/scalacheck/test-reports/scala.reflect.quasiquotes.UnliftableProps.xml/*view*/ shows

```
<testcase classname="scala.reflect.quasiquotes.UnliftableProps" name="symbol" time="-0.001">
                                                 
                                               </testcase>
```

so both CIs are running the test.

**Comment by SethTisue** [comment]
presumably it's because CI does:

```
      # pull request validation (w/ mini-bootstrap)
      - stage: build
        if: type = pull_request
        script:
          - sbt -warn setupPublishCore generateBuildCharacterPropertiesFile publishLocal
          - STARR=`cat buildcharacter.properties | grep ^maven.version.number | cut -d= -f2` && echo $STARR
          - sbt -Dstarr.version=$STARR -warn setupValidateTest test:compile info testAll
```

which isn't happening when you just do `scalacheck/testOnly scala.reflect.quasiquotes.UnliftableProps` locally

so I expect the local test failure will go away once we re-STARR onto M5.

**Pull request merged**
