### PR TITLE
Check backwards binary compatibility against 2.11.0-M4.

### PR DESCRIPTION
**Pull request by adriaanm**
We're going to start testing (and partially enforcing) backwards binary compatibility of subsequent 2.11 milestones. This is necessary to allow modules built with, say 2.11.0-M4 to be used in an M5 context. Once this PR is merged, `ant test.bc` will be run during PR validation. Please make sure to run it before submitting (it's pretty quick, assuming you already have a build of your PR).

Concretely, scala-xml, scala-parser-combinators and scala-partest (which depends on scalacheck) will soon only be rebuilt for every milestone, published, and then used for the next milestone cycle (scala-actors will get the same treatment, and a lot of this also holds for e.g. SBT and the Eclipse plugin). 

We do not want to break any of these modules. We'll go through a quick deprecation cycle. Module authors must fix deprecation warnings (detected via nightly builds that run with -deprecation -Xfatal-warnings) at the latest by the next milestone, after which we can safely break binary compatibility for these (now) unused methods/classes.

On the Scala end, we'll be using mima (mostly preventatively) to detect incompatibilities during PR validation, so that we're at least aware of where we're breaking compatibility. We'll initially be pretty liberal about additions to bincompat-backward.whitelist.conf, but will tighten as the end of the 2.11 release cycle approaches. Additionally, we'll soon use dbuild to build these modules as an additional early warning mechanism.

Think of this as a feasibility study of full (backwards) binary compatibility across major Scala releases. We're not ready to commit to this yet, but we're working towards this goal (e.g. via modularization to reduce the core that must be stable.)

review by everyone (@gkossakowski, @retronym -- cc @huitseeker)

### CODE REVIEW

**Comment by retronym** [comment]
Do any of those modules depend on scala-reflect? If not, we could exclude that from these checks.

**Comment by adriaanm** [comment]
```
 scala-partest (master $>)]$ g grep scala.reflect
README.md:45:  - `partest.reflect`: the path of scala-reflect (jar or class dir) being tested
src/main/scala/scala/tools/partest/CompilerTest.scala:8:import scala.reflect.runtime.{universe => ru}
src/main/scala/scala/tools/partest/TestUtil.scala:3:import scala.reflect.{ classTag, ClassTag }
src/main/scala/scala/tools/partest/nest/ConsoleRunner.scala:14:import scala.reflect.internal.util.Collections.distinctBy
src/main/scala/scala/tools/partest/nest/DirectCompiler.scala:13:import scala.reflect.io.AbstractFile
src/main/scala/scala/tools/partest/nest/DirectCompiler.scala:14:import scala.reflect.internal.util.Position
src/main/scala/scala/tools/partest/nest/FileManager.scala:24:import scala.reflect.io.AbstractFile
src/main/scala/scala/tools/partest/nest/FileManager.scala:26:import scala.reflect.internal.util.ScalaClassLoader
src/main/scala/scala/tools/partest/nest/FileManager.scala:127:        case "reflect"  => Class.forName("scala.reflect.api.Symbols", false, testClassLoader)
src/main/scala/scala/tools/partest/nest/Runner.scala:16:import scala.reflect.internal.FatalError
src/main/scala/scala/tools/partest/package.scala:15:  type SFile        = scala.reflect.io.File
src/main/scala/scala/tools/partest/package.scala:16:  type Directory    = scala.reflect.io.Directory
src/main/scala/scala/tools/partest/package.scala:17:  type Path         = scala.reflect.io.Path
src/main/scala/scala/tools/partest/package.scala:22:  val SFile        = scala.reflect.io.File
src/main/scala/scala/tools/partest/package.scala:23:  val Directory    = scala.reflect.io.Directory
src/main/scala/scala/tools/partest/package.scala:24:  val Path         = scala.reflect.io.Path
src/main/scala/scala/tools/partest/package.scala:202:  import scala.reflect.macros.Context
```

**Comment by retronym** [comment]
Darn. That will somewhat neuter my plans to whitelist `scala.reflect.internal` with this MiMa enhancement: https://github.com/typesafehub/migration-manager/pull/44

I'd rather not leave dependencies from the modules back to `internal` packages in `scala/scala`.

The principled approach is to sprout another module (scala-compiler-utils) for internal consumption only. Or we cave and copy/paste some code, or reimplement in terms of a more stable IO library (e.g apache-commons-io).

**Comment by adriaanm** [comment]
I think we can get there pretty soon. By quick inspection, very few of these dependencies are crucial.

**Comment by gkossakowski** [comment]
@adriaanm: what's the status of this PR?

**Comment by adriaanm** [comment]
It should be closed until M5. I'm sure rebuilding it would fail.

**Pull request closed without merging**
