### PR TITLE
SI-8475 Fix off by one in GroupedIterator when Streaming

### PR DESCRIPTION
**Pull request by jedesah**
This also affected sliding and grouped since they defer to GroupedIterator

### CODE REVIEW

**Comment by jedesah** [comment]
Review by @Ichoran, @som-snytt

**Comment by jedesah** [comment]
I'm trying to figure out why we even need `takeDestructively`. I can't seem to get a handle on why `self.take(n).toSeq` cannot do the job.

**Comment by som-snytt** [comment]
I guess you saw the old commit message?  There must have been a reason five years ago anyway, "can't update the original iterator" or something.

I notice that the padding logic has the same flaw, testing hasNext before the count, "so we don't calculate length unless there's reason," except that length is cheaper than hasNext, unless this is relic from the old regime, where the take is lazy.  The destructive (eager) take maybe repairs that, but the count test should therefore happen before hasNext, as in the current fix.

If you have a time machine to go back five years and ask paulp, let me know, because there's some stuff I'd like to do differently.

**Comment by Ichoran** [comment]
LGTM.

**Comment by retronym** [comment]
Superceded by #3733, which corrects the packaging of the unit test (it should be in the corresponding package of the class it tests), and which targets the newly sprouted 2.11.x branch

**Comment by som-snytt** [comment]
> "can't update the original iterator" or something

I just added a speculative comment.  I haven't tested it yet, but self.take.toSeq wraps self in a splice iterator for the take and a stream for the toSeq.  That's OK if the first thing you do is fetch the group, but if you try to self.hasNext (or whatever), then self has not been consumed as far as you think.  The scaladoc says don't use iter after iter.take.

**Pull request closed without merging**
