### PR TITLE
move test files that fail spuriously to pending

### PR DESCRIPTION
**Pull request by adriaanm**
I have this sneaky suspicion that part of these spurious failures
are caused by the recent partest optimizations.

Since the tests and/or their corresponding fixes are more likely to blame than the test framework,
moving them out of the way until their owners can get them back in line
and they stop throwing primate wenches into our build.

We should bring them back as soon as possible, though.

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @paulp, @lrytz, @axel22

**Comment by axel22** [comment]
I believe t5293 might be failing due to some change in the test suite. Basically, that one relies on the fact that the test suite will not run more tests at a time than there are available processors, a that might skew the performance measurement (this might be a wild guess, but if the problem appeared after partest changes, it might also be related).

What we could do is take a longer measurement, i.e. repeat each `benchX` call multiple times and compare the total times in the assertion at the end.

Are there any logs of that one failing? I could not find them in checking or nightly builds.

**Comment by adriaanm** [comment]
they failed in the pr-validators queue
I think this one should move to a separate test category that should just log but not fail

**Comment by axel22** [comment]
I agree - a test category like that is what we need for these kind of tests.

**Pull request merged**
