### PR TITLE
silences optional logs in reflection

### PR DESCRIPTION
**Pull request by xeno-by**
Some parts of the compiler call `SymbolTable.log` to dump information
about the progress of compilation, type inference, etc.

In Global.scala, `log` checks the -Ylog configuration setting to approve
or reject incoming messages.

However in runtime reflection (scala.reflect.runtime.JavaUniverse)
`log` always prints its argument, which is annoying. Here's why
this is happening.

In runtime reflection -Ylog is inapplicable, because this is a
phase-based setting, whereas reflection does not have a notion of phases.
Moreover reflection doesn't expose `settings` to the programmers
(the corresponding `def settings` definition is declared in
scala.reflect.internal.Required).

Therefore there's no obvious solution to conditional printing in `log`
when invoked in reflective setting. The situation is tough and needs to
be addressed in a principled manner. However we're in between RC1 and RC2
at the moment, so I don't fancy significant changes right now.

Nevertheless we need to fix the annoyance right away, therefore I change
reflective `log` to use -Ydebug. This is inconsistent w.r.t how Global
works, and also there's no way to enable logging short of casting to
`scala.reflect.runtime.SymbolTable`, but it looks like a decent
temporary measure.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @jsuereth

**Comment by adriaanm** [comment]
You're right that we're in RC mode. That's why only absolutely critical fixes can go in. Is this one?
There's always 2.10.1.

**Comment by xeno-by** [comment]
Printing random stuff to the console when doing something as trivial as `typeOf` looks pretty critical to me. Also the fix is a one-liner, which looks obviously correct.

These are the two reasons why I decided to submit this PR against the `2.10.0-wip` branch.

**Comment by adriaanm** [comment]
I agree this fix is not going to kill the release, but let's try to look at the bigger picture.
This is not the only change that someone wants to have merged.
All of them together amount to death by a million paper cuts.

We're in RC mode and that means everybody was comfortable with master being released. Maybe we weren't ready, but that ship has sailed, and it's good to keep in mind for next time when we make that switch. It's a serious decision.

Now we must focus on getting 2.10.0 out of the door in a reasonable amount of time and shift our focus to 2.10.1.

Every little non-blocking fix (and sorry, this is not a blocker) pushes the release date a little but further down the road.

First mentions of going into RC mode date back to April. Half a million "just one more feature/bugfix/hotfix/tweak/paper cut" later, it's almost november and we're at RC2. No more.

**Comment by jsuereth** [comment]
Eugene -  Please target 2.10.x.   Unless this is a blocker (which, sorry to say, reflection runtime is unable to cause blockers thanks to the experimental flag), _NO_ pull requests during RC phase.  Sorry.

Again, 2.10.x is an open door at this point, and will follow 2.10.0 closely.   Best try to do a more advanced fix for that.

**Pull request closed without merging**
