### PR TITLE
[backport] Adapt to changes in Java 9

### PR DESCRIPTION
**Pull request by retronym**
Backports of a few changes in Scala 2.12.3 that remove some impediments to running on Java 9.

### CODE REVIEW

**Comment by sjrd** [comment]
If there's going to be a 2.10.7 version for the sake of Java 9 support, could https://github.com/scala/scala/commit/72076e59257da72f962d4101d87ff5507da28e4f also be ported please? It is necessary for parallel collections not to crash on Java 9. This [caused issues in Scala.js](https://github.com/scala-js/scala-js/issues/2798), which forced us to plain *disable* parallelism in the Scala.js optimizer on Java 9.

**Comment by dwijnand** [comment]
:+1: on what Sébastien said, #5276 was also mentioned in playframework/playframework#7879.

[edit: Oh, it has been cherry picked into this PR]

**Comment by sjrd** [comment]
Thanks! :bowing_man:

**Review by lrytz — APPROVED** [review]

**Comment by adriaanm** [comment]
Oh version numbers!
```
  [partest] java.lang.NumberFormatException: Not a version: 1.71
  [partest] 
  [partest] 	at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:184)
  [partest] 	at scala.util.Properties$.isJavaAtLeast(Properties.scala:16)
  [partest] 	at Test$delayedInit$body.apply(t7265.scala:12)
  [partest] testing: [...]/files/run/t7265.scala                                  [FAILED]
```

**Comment by dwijnand** [comment]
I don't mean to throw more weight on the backport wagon, but I hit this exact thing yesterday when doing some JDK 9 related work in a 2.11 cross-built codebase. And had to resort to some variant of isJavaAtLeast. (https://github.com/sbt/librarymanagement/pull/173). So backporting _that_ fix too would be ace..

**Comment by retronym** [comment]
I've backported the accumulated fixes and tests for `isJavaAtLeast`. I've also added a commit to use `javax.tools` (the API for javac) as a way to support the `jrt://` file system directly, which will mean the SBT no longer needs to export `rt.jar`.

**Comment by SethTisue** [comment]
trying another Jenkins validate-main run with the new commits: https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-validate-main/3157/consoleFull  (as Adriaan realized, although Scabot ignores the 2.10.x branch, you can manually trigger a 2.10.x run of validate-main using the 2.11.x job)

**Comment by SethTisue** [comment]
publish-core succeeded (`2.10.6-05cdf51-SNAPSHOT` was published)

but,

```
     [echo] Checking backward binary compatibility for scala-reflect (against 2.10.0)
     [mima] Found 2 binary incompatibiities (60 were filtered out)
     [mima] ======================================================
     [mima]  * method underlyingSource()scala.Some in class
     [mima]    scala.reflect.io.ZipArchive#Entry has now a different result type; was:
     [mima]    scala.Some, is now: scala.Option
     [mima]  * method underlyingSource()scala.Some in class scala.reflect.io.ZipArchive
     [mima]    has now a different result type; was: scala.Some, is now: scala.Option
     [mima] Generated filter config definition
     [mima] ==================================
     [mima] 
     [mima]     filter {
     [mima]         problems=[
     [mima]             {
     [mima]                 matchName="scala.reflect.io.ZipArchive#Entry.underlyingSource"
     [mima]                 problemName=IncompatibleResultTypeProblem
     [mima]             },
     [mima]             {
     [mima]                 matchName="scala.reflect.io.ZipArchive.underlyingSource"
     [mima]                 problemName=IncompatibleResultTypeProblem
     [mima]             }
     [mima]         ]
     [mima]     }
```

**Comment by SethTisue** [comment]
@retronym since this PR is what we're testing as possible-future-2.10.7, I'd suggest rebasing onto current 2.10.x in order to get the #6128 and #6129 changes

**Comment by lrytz** [comment]
which asm version was in there before? i could not easily find out looking at the git history.
  - https://github.com/scala/scala/commits/2.10.x/src/asm/scala/tools/asm
  - https://github.com/scala/scala/commits/d3bb612195dbaa8996ff98187cd51452a5f72f6c/src/compiler/scala/tools/asm

**Comment by retronym** [comment]
@lrytz The 2.10.x version at least predates f9053e5ac67db484e8a9f2acc39cf8d39a2f1f33 which upgrades to ASM 4.1. I'm pretty sure that it is 4.0.

**Comment by retronym** [comment]
Disk space problem on jenkins-worker-behemoth-2?

```
Caused by: hudson.plugins.git.GitException: Command "git config remote.scala.url https://github.com/scala/scala.git" returned status code 4:
stdout: 
stderr: error: failed to write new configuration file /home/jenkins/workspace/scala-2.11.x-validate-publish-core/.git/config.lock
```

**Comment by SethTisue** [comment]
> Disk space problem

yeah https://github.com/scala/community-builds/issues/617

**Comment by retronym** [comment]
```
++ ant '-Dmaven.version.suffix="-2ae75e9-SNAPSHOT"' -Dremote.snapshot.repository=https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ -Drepository.credentials.id=pr-scala -Dremote.release.repository=noyoudont deploy-core.snapshot
Buildfile: /home/jenkins/workspace/scala-2.11.x-validate-publish-core/dists/maven/2.10.6-2ae75e9-SNAPSHOT/build.xml

init.properties:
     [echo] Using server[pr-scala] for maven repository credentials.
     [echo]        Please make sure that your ~/.m2/settings.xml has the needed username/password for this server id
     [echo]      

init.maven:

deploy.remote.init:

deploy-core.snapshot:
     [copy] Copying 1 file to /home/jenkins/workspace/scala-2.11.x-validate-publish-core/dists/maven/2.10.6-2ae75e9-SNAPSHOT/scala-library

BUILD FAILED
/home/jenkins/workspace/scala-2.11.x-validate-publish-core/dists/maven/2.10.6-2ae75e9-SNAPSHOT/build.xml:288: The following error occurred while executing this line:
/home/jenkins/workspace/scala-2.11.x-validate-publish-core/dists/maven/2.10.6-2ae75e9-SNAPSHOT/build.xml:184: The following error occurred while executing this line:
/home/jenkins/workspace/scala-2.11.x-validate-publish-core/dists/maven/2.10.6-2ae75e9-SNAPSHOT/build.xml:134: settingsFile does not exist: /home/jenkins/.m2/settings.xml

```

😕

**Comment by retronym** [comment]
Restored that file, I'm guessing it was accidentally deleted in a manual purge of `~/.m2/repository`

**Comment by lrytz** [comment]
LGTM, a bit of squashing. ASM update looks good too, I went through asm changes in 2.12.x. Curious, why did you backport the fix for https://github.com/scala/bug/issues/9393?

**Comment by lrytz** [comment]
Actually, why did you move the asm sources from `src/asm` to `src/asm/java` in https://github.com/scala/scala/pull/6113/commits/c3d8750f4da48186d259fd2aa3f5f3da21805047, was that intended?

**Comment by retronym** [comment]
> Curious, why did you backport the fix for scala/bug#9393?

I adapted GenASM to set the `itf` parameter (newly added in ASM 5.2) which controls whether an `InterfaceMethodRef` or `MethodRef` is used. This logic is based in part of `isJavaInterface`, which gave a false negative for annotations. Two `run` tests in test suite that called methods on runtime retained annotations failed with a verify error.

> was that intended?

Nope, that was a mistake. I'll move them back.

I'll also do a jardiff after a bootstrap to doublecheck things are okay.

**Comment by retronym** [comment]
Only one diff, but one that I can't immediately explain.

```diff
diff --git a/scala/collection/parallel/ParIterableLike.class.asm b/scala/collection/parallel/ParIterableLike.class.asm
index e7ebdef..0c753e0 100644
--- a/scala/collection/parallel/ParIterableLike.class.asm
+++ b/scala/collection/parallel/ParIterableLike.class.asm
@@ -157,9 +157,9 @@
   // access flags 0x1
   public INNERCLASS scala/collection/parallel/ParIterableLike$CreateScanTree scala/collection/parallel/ParIterableLike CreateScanTree
   // access flags 0x401
-  public abstract INNERCLASS scala/collection/parallel/ParIterableLike$Accessor$class scala/collection/parallel/ParIterableLike Accessor$class
-  // access flags 0x401
   public abstract INNERCLASS scala/collection/parallel/ParIterableLike$ScanTree$class scala/collection/parallel/ParIterableLike ScanTree$class
+  // access flags 0x401
+  public abstract INNERCLASS scala/collection/parallel/ParIterableLike$Accessor$class scala/collection/parallel/ParIterableLike Accessor$class
   // access flags 0x1
   public INNERCLASS scala/collection/parallel/ParIterableLike$$anonfun$min$1 null null
   // access flags 0x1
diff --git a/scala/tools/nsc/symtab/SymbolTrackers$SymbolTracker$Node$.class.asm b/scala/tools/nsc/symtab/SymbolTrackers$SymbolTracker$Node$.class.asm
index 878393a..7d6f2af 100644
--- a/scala/tools/nsc/symtab/SymbolTrackers$SymbolTracker$Node$.class.asm
+++ b/scala/tools/nsc/symtab/SymbolTrackers$SymbolTracker$Node$.class.asm
@@ -187,9 +187,7 @@
     INVOKEVIRTUAL scala/collection/immutable/Set$.canBuildFrom ()Lscala/collection/generic/CanBuildFrom;
     INVOKEINTERFACE scala/collection/SetLike.map (Lscala/Function1;Lscala/collection/generic/CanBuildFrom;)Ljava/lang/Object;
     CHECKCAST scala/collection/GenTraversableOnce
-    GETSTATIC scala/collection/immutable/Set$.MODULE$ : Lscala/collection/immutable/Set$;
-    INVOKEVIRTUAL scala/collection/immutable/Set$.canBuildFrom ()Lscala/collection/generic/CanBuildFrom;
-    INVOKEINTERFACE scala/collection/immutable/Set.$plus$plus (Lscala/collection/GenTraversableOnce;Lscala/collection/generic/CanBuildFrom;)Ljava/lang/Object;
+    INVOKEINTERFACE scala/collection/immutable/Set.$plus$plus (Lscala/collection/GenTraversableOnce;)Lscala/collection/Set;
     CHECKCAST scala/collection/immutable/Set
     ALOAD 0
     GETFIELD scala/tools/nsc/symtab/SymbolTrackers$SymbolTracker$Node$.$outer : Lscala/tools/nsc/symtab/SymbolTrackers$SymbolTracker;
```

Produced with:

```
% rm build.properties
% ant -Dhas.java7=true locker.unlock all.clean pack.done
% cp -R build/pack /tmp/bootstrapped
% ant -Dhas.java7=true -Dlocker.skip=1 locker.unlock all.clean pack.done
% cp -R build/pack /tmp/skip
% jardiff /tmp/skip/lib/scala-compiler.jar /tmp/bootstrapped/lib/scala-compiler.jar
```

**Comment by retronym** [comment]
Okay, I see now that I was in fact testing differences in using 2.10.3 (starr.version) and the tip of this PR in code generation. Something seems to have changed overload resolution between 2.10.3 and 2.10.4, which is unrelated to this PR.

**Review by lrytz — APPROVED** [review]
just a bit of squashing left to do, looks all good otherwise.

**Comment by retronym** [comment]
I left this unsquashed for now to make it a bit easier to create the forward merge to 2.11.x, scala/scala#6151. I've got that PR green now, so I could rebase/squash this and turn the 2.11.x version into a single commit.

**Comment by adriaanm** [comment]
+1 I think it's fine to leave the history in place for expediency as well as future archeology

**Comment by xuwei-k** [comment]
😢  https://github.com/scala/bug/issues/10603

**Comment by retronym** [comment]
FTR, I've had a report of this exception when using Java 9, SBT 0.13.17, which uses the new code here to compile `build.sbt` etc.

```
java.lang.NullPointerException
        at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:242)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
        at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:308)
        at scala.tools.nsc.util.DirectoryClassPath.x$16$lzycompute(ClassPath.scala:317)
        at scala.tools.nsc.util.DirectoryClassPath.x$16(ClassPath.scala:317)
        at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:317)
        at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:317)
        at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:297)
        at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPat
```

I believe this is due to using a JRE rather than JDK, which gives a null from `getSystemJavaCompiler` in:

```scala
val fileManager = ToolProvider.getSystemJavaCompiler.getStandardFileManager(new DiagnosticCollector, java.util.Locale.getDefault, Charset.defaultCharset)
```

**Pull request merged**
