### PR TITLE
Add methods for manual proof

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by sjrd** [comment]
Is there any previous discussion/rationale/motivation about this?

**Comment by Atry** [comment]
Not yet.

https://github.com/mpilquist/simulacrum will benefit from this PR. The `@typeclass` macro can use `implicitly[A =:= X].invariant[F].apply(fa)`, instead of `fa.asInstanceOf[F[X]]` at the moment.

**Comment by soc** [comment]
I think we had a PR like this before. might make sense to compare and discuss why this is supposed to be better.

**Comment by Atry** [comment]
@soc I could not find the PR. Could you paste it here?

**Comment by Atry** [comment]
Looks like https://github.com/scala/scala/pull/3992

**Comment by Atry** [comment]
There are only three basic atomic rules `asymmetry`, `invariant` and `covariant`.

 `andThen`, `compose` and all other helpers can be implemented from `invariant` and `covariant`.

`invariant` and `covariant` are especially important for type safety, because the two methods give a chance to manually prove subtyping or equality. They are not necessary to be `implicit` though.

**Comment by Ichoran** [comment]
It would really help to have more extensive justification, documentation, and a full set of tests.

You don't use contravariant or asymmetry at all.  What problem do they solve?  What behavior ought they have?  Do they actually have that behavior?

(Some of them look wrong to me.)

**Comment by SethTisue** [comment]
the test failure is spurious and should go away if you rebase on top of current head

**Comment by SethTisue** [comment]
@Atry rebase?

**Comment by adriaanm** [comment]
We can't change the public API of 2.12 anymore, targeting for 2.13.

**Comment by Atry** [comment]
@adriaanm There is not such a 2.13.x branch yet

**Comment by Atry** [comment]
Regardless the ability of covariance/contravariance of introduced by this PR, there is another issue make `<:<` less useful - type applying with type constraints.

``` scala
trait MyTypeClass[+A]
final class MyTypeClassForByteSeq[+A <: Seq[Byte]] extends MyTypeClass[A]

// Does not work because `<:<` is meaningless for type constraints
def myTypeClassForByteSeq[A0](implicit ev: A0 <:< Seq[Byte]): MyTypeClass[A0] = new MyTypeClassForByteSeq[A0]
```

**Comment by SethTisue** [comment]
Closing for 2.12.x. 2.13.x branch exists now, if you want to make a new PR (or reopen and retarget this one).

**Pull request closed without merging**
