### PR TITLE
Interactive / ScalaDoc housekeeping

### PR DESCRIPTION
**Pull request by huitseeker**
Those are the leftovers of what should have been a larger bugfix PR, but that's finally not meant to be.

No issue, since the changes are straightforward & compiler warnings-driven, but I'd be happy to create one.

Should probably be merged into 2.12.

review by @jaguarul, who kindly agreed to look at what should be boring improvements

### CODE REVIEW

**Comment by dragos** [comment]
LGTM

**Comment by huitseeker** [comment]
PLS REBUILD ALL

**Comment by huitseeker** [comment]
The failures there:
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7752/console
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7748/console
... are spurious

**Comment by huitseeker** [comment]
Adaptation PR for scala-refactoring is out :
https://github.com/scala-ide/scala-refactoring/pull/60

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@huitseeker, could you rebase on top of latest `2.11.x` branch? I hope IDE failures would go away.

**Comment by gkossakowski** [comment]
Closing for lack of activity.

**Pull request closed without merging**
