### PR TITLE
Upgrade Maven Gpg plugin from 1.3 to 1.5 version.

### PR DESCRIPTION
**Pull request by gkossakowski**
Hopefully, this will help with failing uploads to the JFrog repo that
breaks PR validation.

### CODE REVIEW

**Comment by retronym** [comment]
I believe the failure is coming from `artifact:deploy`, which comes from the Maven Ant Tasks. We are using version 2.1.1, we can try upgrading to 2.1.3: http://maven.apache.org/ant-tasks/download.cgi

**Comment by retronym** [comment]
I'm trying this as #4127

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
Review by @retronym 

Even if this didn't succeed in fixing the JFrog issue I think it's still worth it to upgrade.

**Comment by retronym** [comment]
If we are touching this anyway, let's extract the version to a single property.

**Comment by gkossakowski** [comment]
I'll be offline until January 7th. Let's close it for now.

**Pull request closed without merging**
