### PR TITLE
SI-6422: add missing Fractional and Integral alias in scala package

### PR DESCRIPTION
**Pull request by Blaisorblade**
In scala/package.scala we see:

``` scala
type Fractional[T] = scala.math.Fractional[T]
type Integral[T] = scala.math.Integral[T]

type Numeric[T] = scala.math.Numeric[T]
val Numeric = scala.math.Numeric
```

But Fractional and Integral have an associated object as well, and they should be aliased as well for consistency.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Needs reviewer. Maybe @jsuereth ?

**Comment by jsuereth** [comment]
Hey, sorry for the late review.   Can you explain why we need these type aliases?   Right now I'd prefer to keep them in the math package.

**Comment by Blaisorblade** [comment]
Not a problem, there were more urgent things. The _type_ aliases are already there, it's just the objects which are not aliased, and I strongly assume that's an oversight or otherwise should be motivated (IMHO). I think my pull request description mislead you: I show code which is _already_ in `Predef`.

**Comment by jsuereth** [comment]
Ah.  I see.  Yeah, so adding this in is fine then, since the type aliases are there.  Whether or not they should be there, I still question....

LGTM

**Comment by Blaisorblade** [comment]
Are there binary compatibility problems, since this is going in in 2.10.1?

**Pull request merged**
