### PR TITLE
Only create a HashTrieSet if necessary.

### PR DESCRIPTION
**Pull request by rklaehn**
If allow HashTrieSets with one element, you can get a degenerate tree that is six levels deep yet contains only one element by first building a large tree and then removing elements

### CODE REVIEW

**Comment by jsuereth** [comment]
Can we get a test? Otherwise lgtm

**Comment by rklaehn** [comment]
How do I submit a test? Just put somewhere in the test directory (where?)
and add another commit to the pull request?

What kind of test do you want. The smallest possible example that fails in
the old version and succeeds in the new one? Or something more complex?

**Comment by jsuereth** [comment]
Add another commit.    Look in test/files/run for examples or test/files/scalacheck for scalacheck examples.

**Comment by jsuereth** [comment]
A test that gives confidence that new code is correct is all I need.   Cover the corner cases.   We should try to avoid regressions on refactoring.   A good broken test is great documentation of these issues.

**Comment by adriaanm** [comment]
a test for this would probably go into test/files/run/tNNNN.scala if there's a SI-NNNN or else some descriptive name

for test/files/run/myTest.scala there should be a corresponding test/files/run/myTest.check that is checked to contain the output of running the Test object (which must thus contain a main method) that is produced by compiling myTest.scala

**Comment by rklaehn** [comment]
OK. I will try to write some tests ASAP. However, I can't promise anything
this weekend.

This week my wife and kids were away, so I had some time to hack on scala
in the evening.

**Comment by rklaehn** [comment]
OK. Here is a very small test just to prevent a regression.

I didn't know how to test that a HashTrieSet with one element is allowed if the element is itself a HashTrieSet. But if you don't allow that the whole thing completely blows up and hundreds of other misc tests fail (I know because I did not consider that case in the beginning and had test failures all over the place :-)

**Comment by jsuereth** [comment]
Hmm.   We'll have to look at those failing tests then.

**Pull request merged**
