### PR TITLE
[backport] SI-7710 fix memory performance of RegexParsers in jdk7u6+

### PR DESCRIPTION
**Pull request by gourlaysama**
Backport of scala/scala-parser-combinators@91584dc.

See scala/scala-parser-combinators#17.

---

Starting with 1.7.0_06 [1], String.substring no longer reuses the internal
char array of the String but make a copy instead. Since we call
subSequence twice for _every_ input character, this results in horrible
parse performance and GC.

With the benchmark from the (duplicate) ticket SI-8542, I get:

BEFORE:
    parseAll(new StringReader(String))
    For 100 items: 49 ms
    For 500 items: 97 ms
    For 1000 items: 155 ms
    For 5000 items: 113 ms
    For 10000 items: 188 ms
    For 50000 items: 1437 ms
    ===
    parseAll(String)
    For 100 items: 4 ms
    For 500 items: 67 ms
    For 1000 items: 372 ms
    For 5000 items: 5693 ms
    For 10000 items: 23126 ms
    For 50000 items: 657665 ms

AFTER:
    parseAll(new StringReader(String))
    For 100 items: 43 ms
    For 500 items: 118 ms
    For 1000 items: 217 ms
    For 5000 items: 192 ms
    For 10000 items: 196 ms
    For 50000 items: 1424 ms
    ===
    parseAll(String)
    For 100 items: 2 ms
    For 500 items: 8 ms
    For 1000 items: 16 ms
    For 5000 items: 79 ms
    For 10000 items: 161 ms
    For 50000 items: 636 ms

[1] http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6924259

### CODE REVIEW

**Comment by gourlaysama** [comment]
This is weird. Should Mima complain about adding a new package private class? Also, Mima was happy with this exact same commit in the scala-parser-combinators repository...

And as an added bonus, I don't get the same error when I run `ant test.bc` locally...

**Comment by gourlaysama** [comment]
Ok, with `ant clean build-opt test.bc`, mima gives me the same error.

@adriaanm: can I whitelist that class? I am not sure of anything when it comes to mima. Or I can make it a private class in the RegexParsers trait...

**Comment by lrytz** [comment]
@gourlaysama the change is binary compatible in both directions as far as I can tell, so you can add the class to the whitelist.

**Comment by gourlaysama** [comment]
@lrytz done :)

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
