### PR TITLE
Copy bytes directly instead of using scala.reflect.io.Streamable

### PR DESCRIPTION
**Pull request by rochala**
Forward port from https://github.com/sbt/zinc/pull/1395

### CODE REVIEW

**Comment by som-snytt** [comment]
Alternatively, stick the classic loop in Streamable where it says "fall back on relative inefficiency", and then add `unsafeFromByteArray` (to `reflect.io.VirtualFile`) to set `content` instead of copying through `BAOS`, or `fromInputStream`.

**Comment by rochala** [comment]
That can be another fix to be made, but also take into consideration that this change was also made directly in Zinc. I think that we should keep them aligned in that case.

**Comment by lrytz** [comment]
> stick the classic loop in Streamable where it says "fall back on relative inefficiency"

certainly worthwhile

too bad there's no one-liner in the standard library (https://stackoverflow.com/questions/4905393/scala-inputstream-to-arraybyte)

> we should keep them aligned

that's not really a goal (we might clean up the bridge and more tightly integrate things with the compiler now that it's in the same codebase).

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
Oh [word], sorry @SethTisue, we're in release freeze. Should we revert this for 2.13.15?

**Comment by SethTisue** [comment]
I'll see if it's possible for me to build the release from the preceding merge commit. If not, I'll revert.

**Comment by SethTisue** [comment]
It looks like it's going to be fine to just make a `release-2.13.15` branch and release from that.

UPDATE: That's what I did, it's fine.

**Pull request merged**
