### PR TITLE
SI-6811 Deprecate scala.text

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @jsuereth, please.

**Comment by som-snytt** [comment]
My kingdom for a package deprecation.  https://issues.scala-lang.org/browse/SI-3115

**Comment by SethTisue** [comment]
some (supportive) discussion at https://groups.google.com/d/msg/scala-internals/axzOQ6fUNQg/4hijJvAQQ6AJ

**Comment by adriaanm** [comment]
LGTM -- I was thinking of making a jar scala-misc.jar  (or maybe even scala-deprecated.jar) that has these deprecated packages/classes on which the std lib does not depend

**Comment by gkossakowski** [comment]
LGTM. Thanks.

**Pull request merged**
