### PR TITLE
Backport "Make Stream.withFilter.{map,flatMap} run in constant stack space" against 2.9.x

### PR DESCRIPTION
**Pull request by Blaisorblade**
This is a backport of https://github.com/scala/scala/pull/1167. I produced the backport using `git cherry-pick` and got no conflict; I could reproduce the failure with `2.9.x` current HEAD, and no failure after applying this fix.

Review by @axel22

### CODE REVIEW

**Comment by Blaisorblade** [comment]
`ant test` completes fine here, so I would suspect a spurious test failure; I'm trying to reproduce the failure here with:

``` bash
ant locker.clean && ant -Dscalac.args.optimise=-optimise locker.done && ant '-Dscalac.args="-Yrangepos"' '-Dpartest.scalac_opts="-Yrangepos"' build-opt
```

**Comment by Blaisorblade** [comment]
I correct - pr-rangepos seems broken on 2.9.x even without my patch, both in April and on the current head. It seems that pr-rangepos was not enabled on 2.9.x some time ago (https://github.com/scala/scala/pull/806) - @jsuereth, is pr-rangepos expected to pass on 2.9.x?

**Comment by jsuereth** [comment]
pr-rangepos is not expected to pass on 2.9.x, sorry for spurious failures.

**Comment by axel22** [comment]
lgtm

**Comment by jsuereth** [comment]
Thanks!! A great thing to fix.  Note: We may have a 2.9.3 release at some point, need to have that discussion later.

**Pull request merged**
