### PR TITLE
SI-5675 Discard duplicate feature warnings at a position

### PR DESCRIPTION
**Pull request by retronym**
When -feature has not been enabled, we were double counting
identical feature warnings that were emitted at the same position.
Normal error reporting only reports the first time a warning
appears at a position; feature warning counter incrementing
should behave the same way.

Review by @hubertp

### CODE REVIEW

**Comment by hubertp** [comment]
Kitty seems to be pretty stubborn about those three tests. Do you want me to have a look (I imagine you have other PRs to work on)?

**Comment by retronym** [comment]
@hubertp: that would be great, I can't get back to this until Friday evening. It's probably just needs checkfile updates.

**Comment by hubertp** [comment]
ok, I will have a look in the evening.

**Comment by hubertp** [comment]
@retronym there is a PR waiting on your fork with minor changes.

**Comment by adriaanm** [comment]
BUILDLOG?

**Comment by retronym** [comment]
@hubertp cheers, I'll push that tonight, feel free to resubmit it yourself before then...

**Comment by hubertp** [comment]
Done.

**Comment by JamesIry** [comment]
superseded by https://github.com/scala/scala/pull/2095

**Pull request closed without merging**
