### PR TITLE
SI-8292 report error when scaladoc fails to find doclet.

### PR DESCRIPTION
**Pull request by gourlaysama**

### CODE REVIEW

**Comment by gourlaysama** [comment]
review by @VladUreche :)

**Comment by VladUreche** [comment]
Thanks @gourlaysama! Good catch, I never used the alternative doclet feature.

There's a little rewording you could do to make the error more friendly:

```
s"Cannot load the doclet generator class ${settings.docgenerator.value} (specified with ${settings.docgenerator.name}): The class is not found. Leaving the default settings will generate the html version of scaladoc."
```

Did you try what happen if:
1) the class doesn't have a nullary constructor?
2) the class is not a subtype of Universer?
Could the `documentError` function catch these case too?

**Comment by gourlaysama** [comment]
@VladUreche I am now catching all errors that the reflective instantiation of the doclet can throw (leaving the rest alone). I am not sure this is the best thing to do (a doclet can also throw an exception; maybe we should just catch everything).

The alternative doclet feature could be useful, except that the doclet has to be given with `-toolcp`, which won't work from sbt or similar... 
(I found this out while trying to write a json doclet)

**Comment by VladUreche** [comment]
LGTM! Thanks a lot @gourlaysama!

**Pull request merged**
