### PR TITLE
Bump versions after 2.11.6 release.

### PR DESCRIPTION
**Pull request by adriaanm**
Review by @retronym

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

Checked against 85f3548b1b7254f7de555dd7c801b9b7f9101d13.

**Comment by adriaanm** [comment]
Good thing you pointed me at the previous commit. I missed scala.full.version -- I was wondering why that was mentioned in the checklist. It seems Monday also isn't a good day to do stuff like this.

**Comment by adriaanm** [comment]
Gah. https://repo1.maven.org/maven2/org/scala-lang/scala-dist/2.11.6/scala-dist-2.11.6.pom points to the wrong continuations plugin (and has been lagging by at least one release forever...)

**Comment by adriaanm** [comment]
This is something that should be fixed in https://github.com/scala/scala/blob/2.11.x/scripts/jobs/integrate/bootstrap#L441 -- it should use SCALA_VER, not SCALA_FULL_VER

**Comment by adriaanm** [comment]
Spurious failure, since the second commit passes where the first one failed, even though the diff between those commits is in a script that's completely unrelated.

**Comment by retronym** [comment]
LGTM.

**Pull request merged**
