### PR TITLE
SI-8264 scala.collection.immutable.HashSet#- returns broken Set

### PR DESCRIPTION
**Pull request by Ichoran**
Was an error in HashSet's handling of removal of an element when a HashTrieSet should turn into a HashSet1.

Also slightly modified HashMap's filter0 to more closely match HashSet (by adding the same comment).

### CODE REVIEW

**Comment by adriaanm** [comment]
Looks fixed, but would it make sense to add a unit test?

```
Welcome to Scala version 2.11.0-7a7b397-SNAPSHOT (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_65).
Type in expressions to have them evaluated.
Type :help for more information.

scala>  Set(-2147483648, 1, -45023380, -1, 1971207058, -54312241, -234243394) - -1
res0: scala.collection.immutable.Set[Int] = Set(-2147483648, 1, -45023380, 1971207058, -54312241, -234243394)

scala> res0.toList.toSet == res0
res1: Boolean = true

scala> res0 == res0.toList.toSet
res2: Boolean = true
```

**Comment by Ichoran** [comment]
Yes, it would make sense.  I intended to, just forgot.

**Comment by Ichoran** [comment]
@adriaanm - Unit test is in.

**Comment by adriaanm** [comment]
LGTM!

**Pull request merged**
