### PR TITLE
SI-8918 Unary ids are plain ids

### PR DESCRIPTION
**Pull request by som-snytt**
Allow +,-,!,~ to be used as unprefixed identifiers.

As prefix operators, they must be followed by
a simple expression, so otherwise, consume the
id itself as the start of a simple expression.

### CODE REVIEW

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
This change requires a change to the spec as well as coordination with other Scala parsers (I know of scalariform and IntelliJ). I don't think it is suitable for 2.11.

**Comment by paulp** [comment]
Can you point me to what in the specification requires changing?

**Comment by paulp** [comment]
Oh, I guess you mean the grammar. Are there any normal words outside the grammar which would lead one to that conclusion?

**Comment by retronym** [comment]
I just looked the grammar.

**Comment by som-snytt** [comment]
Did I check the grammar?   I'm not sure it passes muster.  I'll look again and retarget for Don Giovanni if it looks tempting.  I say the end of Don Giovanni when hell itself opens up and demons drag us down for our manifold sins.

**Comment by som-snytt** [comment]
@retronym I just checked the grammar and I don't see a change. 

Let me know if you'd still like this targeted for 2.12, since it doesn't change how previously accepted source is parsed.

Normally, you expect `a?a` to match what it can, e.g., `- -`, taken as `-.unary_-`, and `-` as without the optional first part.

Right now, it matches `unaryop simple | nonunaryoppable_simple`, as not specked.

Current implementation already takes backquoted unaries correctly; so that doesn't change; it merely incorrectly does not take unary-oppable idents as non-unary ops.

I may take my old "Unstoppable!" t-shirt and modify it to read, "Unaryoppable!"

**Comment by lrytz** [comment]
I move this out of the 2.11.5 milestone, it needs more discussing (for example with the IntelliJ people).

**Comment by lrytz** [comment]
opinions on this change? maybe in 2.12? /cc @adriaanm @gkossakowski @retronym @Alefas

**Comment by gkossakowski** [comment]
Although it doesn't change grammar, I'd be in favour of putting this into 2.12.x and highlighting in release notes.

**Comment by adriaanm** [comment]
+1 on moving to 2.12

**Comment by som-snytt** [comment]
OK, OK! Agreed. It's not backwardly source-bug-compatible, so if you used it in your 2.11.6 project, I couldn't compile with 2.11.5.

It means that folks won't be able to do this for a long time. I hope they don't riot.

Or lodge too many [duplicate issues](https://issues.scala-lang.org/browse/SI-9118).

**Pull request closed without merging**
