### PR TITLE
Mark single-use field MUTABLE for nullification

### PR DESCRIPTION
**Pull request by leitoh0**
Fixes scala/bug#11781

### CODE REVIEW

**Comment by hrhino** [comment]
Thanks! Could I ask you to add a test, please? (The normal CI doesn't run on Java 11 yet, but we may as well put it in anyways.)

Something as simple as adding a file `test/files/run/t11781.scala` containing the code from your issue:
```scala
object Test extends App {
  class Foo(x: String) {
    lazy val y = x.length
 }
 new Foo("hi").y
}
```
should suffice; you can run it with `partest test/files/run/t11781.scala`.

**Comment by leitoh0** [comment]
As it turns out, the exception in question is behind >= java9 check (at least in OpenJDK), so unless the test file is compiled with 9+ target it won't fail. I suppose this might make this PR moot for 2.12.x if 2.12 never gets Java 9+ support.

However, I could just check the field's access for a test.

**Review by retronym — APPROVED** [review]

**Comment by retronym** [comment]
I don't think this will do any harm on 2.12.x but as you've noted, it doesn't have a material difference combined unless with `-target:9` with is only available on 2.13.x.

**Comment by lrytz** [comment]
👍

**Pull request merged**
