### PR TITLE
Avoid triple-quoting triple quotes in printer

### PR DESCRIPTION
**Pull request by som-snytt**
The boolean test for triples was inadvertently flipped.

Adds test for pretty printed multiline strings.

As discovered https://github.com/scala-exercises/scala-exercises/issues/350

Supersedes https://github.com/scala/scala/pull/5232

### CODE REVIEW

**Comment by andyscott** [comment]
Is there anything I can do to help? I'd also like to see this fix on 2.11, so I could port it there.

**Comment by som-snytt** [comment]
@andyscott I was going to cherry-pick the first commit only to backport to 2.11, but feel free to help out! I think they say `[nomerge]` in the PR title so it's not merged forward.

**Comment by andyscott** [comment]
I'm not terribly familiar with contributing to Scala, so I wouldn't mind giving it a go-- although it will have to be on Monday.

**Comment by som-snytt** [comment]
We'll see who gets around to it. :)

**Comment by som-snytt** [comment]
https://github.com/scala/scala/pull/5236

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
