### PR TITLE
constructors phase refactoring for readability

### PR DESCRIPTION
**Pull request by paulp**
Rebase of #2586.

### CODE REVIEW

**Comment by paulp** [comment]
@adriaanm Is there a way to say "PLS REBUILD FAILED", and/or does (or can) "PLS REBUILD ALL" imply that? Also, I don't know about anyone else but I am never going to use anything except "PLS REBUILD ALL" so it may as well be "PLS REBUILD" or even dare I say it "REBUILD".

**Comment by adriaanm** [comment]
Happy to implement those. Could you file an issue on the GitHub project for
the pr validator?

On Monday, May 27, 2013, scala-jenkins wrote:

> (kitty-note-to-self: ignore 18510566)
> [image: :cat:] Roger! Rebuilding for ac6504bhttps://github.com/scala/scala/commit/ac6504b8,
> ac7bbc8 https://github.com/scala/scala/commit/ac7bbc8f, b7add15https://github.com/scala/scala/commit/b7add151,
> bf2b753 https://github.com/scala/scala/commit/bf2b7536, 6eeafe5https://github.com/scala/scala/commit/6eeafe58,
> 955c8fc https://github.com/scala/scala/commit/955c8fce, b77dcddhttps://github.com/scala/scala/commit/b77dcdd5,
> ef68aee https://github.com/scala/scala/commit/ef68aee5, 4837fa3,
> 63325fe0, 7a3c9b42, 478e31a7, 0ee622f8, 073cc200. [image:
> :rotating_light:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scala/scala/pull/2599#issuecomment-18510654
> .

## 

See you at Scala Days http://scaladays.org (June 10–12, NYC)!

**Comment by paulp** [comment]
typesafehub/ghpullrequest-validator#39

**Comment by magarciaEPFL** [comment]
Once this PR is merged, I can submit an optimization that prevents heap retantion, in particular for closures handed out from actors.

With the optimization in place, the actor reference (which is used by the closure only as springboard to obtain another outer instance) isn't captured anymore. Instead, only the (nearmost) target outer instance _that is actually needed_ is captured.

Once this PR is merged, I can re-base that optimization:
  https://github.com/magarciaEPFL/scala/compare/constructors-refactoring-4...constructors-refactoring-5

The optimization isn't specific to actors, nor to closures, but applies to any final nested class (for now, lacking itself nested classes, but it can be generalized).

Motivation:
  https://groups.google.com/forum/#!topic/scala-internals/jQiRINTvhZQ

**Comment by adriaanm** [comment]
PLS SYNCH

**Comment by soc** [comment]
I have read through all of them, except https://github.com/paulp/scala/commit/b77dcdd566fdbf9c91735a31d3ca7dfc11f30749 and https://github.com/paulp/scala/commit/63325fe072aeac54e3651af9184dd8499c617d6d and stuff looks good to me.

**Comment by adriaanm** [comment]
I think it would be good for @JamesIry to have a look as well.
Not sure why I was assigned except for the build bot improvements.

**Comment by magarciaEPFL** [comment]
@paulp Thanks for the improvements to this PR. Any chance you might also give the final push towards the repo?

**Comment by JamesIry** [comment]
LGTM . I'll make the kitty retest everything then submit.

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Pull request merged**
