### PR TITLE
Fix 23 typos (m-o)

### PR DESCRIPTION
**Pull request by janekdb**
Lattes on me!

### CODE REVIEW

**Comment by janekdb** [comment]
Review by @heathermiller, @dickwall.

**Comment by janekdb** [comment]
This is the cause of the build failure. I will take a look at removing this change from the PR.

```
test.bc:
     [echo] Checking backward binary compatibility for scala-library (against 2.11.0)
     [mima] Found 1 binary incompatibiities (3 were filtered out)
     [mima] =====================================================
     [mima]  * method noTraceSupression()scala.sys.BooleanProp in object
     [mima]    scala.sys.SystemProperties does not have a correspondent in new version
     [mima] Generated filter config definition
     [mima] ==================================
     [mima] 
     [mima]     filter {
     [mima]         problems=[
     [mima]             {
     [mima]                 matchName="scala.sys.SystemProperties.noTraceSupression"
     [mima]                 problemName=MissingMethodProblem
     [mima]             }
     [mima]         ]
     [mima]     }
     [mima] 
```

**Comment by janekdb** [comment]
Removed the corrections from `noTraceSupression` -> `noTraceSuppression` from `NoStackTrace.scala` and `SystemProperties.scala` to avoid breaking backward binary compatibility.

If I wanted to provide a separate PR to fix that what is the best approach?

**Comment by heathermiller** [comment]
Hi @janekdb LGTM! Though since you're actually renaming methods (in addition to pure documentation) I'd ping @adriaanm and @retronym for their opinion just in case.

Regardless, thanks for your contribution!

**Comment by janekdb** [comment]
Review by @adriaanm and @retronym.

**Comment by dickwall** [comment]
Yes, looks good to me too, but like Heather I think because of the code changes, we should have one of the compiler folks sign off too before merging. I'll ping them this week.

**Comment by janekdb** [comment]
The method name changes have been moved to #4589. This PR is now just documentation and comments updates.

**Comment by dickwall** [comment]
OK - I think that was a good call - thanks Janek. I'll just wait to see green on the build and I'll merge in the changes. Thanks.

**Pull request merged**
