### PR TITLE
evicts eponymous packages and objects from tests

### PR DESCRIPTION
**Pull request by xeno-by**
As I figured out from http://groups.google.com/group/scala-internals/browse_thread/thread/ace970a799dcf7a0,
current behavior with same-named objects silently taking precedence over
same-named packages is a bug and shouldn't be relied upon.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @lrytz @paulp

**Comment by lrytz** [comment]
i think having lower and upper case versions of the same name also has unspecified behaviour..

**Comment by lrytz** [comment]
(on some platforms at least - i would not be surprised if things fail on windows)

**Comment by xeno-by** [comment]
nice catch! PLS REBUILD ALL

**Comment by lrytz** [comment]
lgtm

**Comment by paulp** [comment]
lgtm too. Yes, differing only by case is poison, I'm sorry we don't have a warning yet.

**Pull request merged**
