### PR TITLE
SI-7181 Eliminate unnecessary duplicates of finally blocks

### PR DESCRIPTION
**Pull request by JamesIry**
The main body of a try and each exception handler were getting a copy of
the finally block for the "normal" flow case (i.e. where they don't
throw an uncaught exception or use "return" to exit early). But that's
 not necessary.

With this commit the try body and each exception handler can all jump
to the same copy of the finally block on a normal exit.

Two tests are included. One is a run style test that shows that
try/catch/finally logic remains unchanged. The other is a byte code
test that ensures we're getting fewer copies of the finally.

### CODE REVIEW

**Comment by JamesIry** [comment]
Hmm, one test is the exception inlining test, which, okay that needs a fixup. But the other is the test I'm submitting here and that one works for me. Huh?

**Comment by paulp** [comment]
-optimise?

**Comment by JamesIry** [comment]
@paulp That would explain it because the exception inliner would add another copy of one finally block. But, I don't have -optimize in this test's flag so I shouldn't get optimize code in the test...right? Do I have to have an empty .flags file?

**Comment by paulp** [comment]
All the tests are run under -optimise when you run test-opt, which is what the usual jenkins does.

**Comment by JamesIry** [comment]
[sigh]

**Comment by JamesIry** [comment]
might as well lean into it I guess.

**Comment by retronym** [comment]
btw, you can use `SCALAC_OPTS=-optimize ./test/partest path/to/test` to run an individual test under that flag.

**Comment by JamesIry** [comment]
@retronym Yeah, I've created an alias now that I know the automated build always runs under optimize.

@gkossakowski Actually I think that test needs to be rewritten. It's testing more than my intended change. The other test, run/t7181.scala, already does a comprehensive test to make sure try/catch/finally as a whole works.

**Comment by JamesIry** [comment]
PLS SYNCH

**Comment by adriaanm** [comment]
The [build](https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/765/) has finished since the kitten last visited this PR. It should notice this on the next visit.

I'm working on improving the logic that sets the commit status message.

Ah, there we go -- it went green while I was typing the above :-)

**Comment by JamesIry** [comment]
Hooray.

review @gkossakowski

**Comment by gkossakowski** [comment]
LGTM.

Great that you split this into two commits. Work prepared like the is pure pleasure to review.

**Pull request merged**
