### PR TITLE
macro args now correctly preserve range positions

### PR DESCRIPTION
**Pull request by xeno-by**
Somewhen in the 2.11.0 development cycle we started duplicating macro arguments
for increased robustness. What wasn't taken into account though is that
Tree.duplicate destroys range positions. This commit fixes the problem.

2.10.x is unaffected by this bug, because it doesn't duplicate the args yet.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
Btw do you think we should duplicate args in 2.10.x as well?

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
I'm running [this PR](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/27) and, as a baseline, [2.11.x](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/27) through the Community Build with `-Yrangepos` enabled in all projects.

image

**Comment by xeno-by** [comment]
Looks like the community build suceeded. Do we merge?

**Comment by retronym** [comment]
LGTM

**Pull request merged**
