### PR TITLE
Merge 2.11.x to 2.12.x

### PR DESCRIPTION
**Pull request by retronym**
```
% export MB=$(git merge-base origin/2.12.x origin/2.11.x)

% git log --oneline -1
73f4056 Merge pull request #4526 from adriaanm/rework-4523

% transcript git log --graph --oneline --decorate $MB...origin/2.11.x
https://gist.github.com/2bc8a21fff6d43474b4a

... No commits marked with nomerge or backport

% transcript git diff --stat $MB...origin/2.11.x
https://gist.github.com/5f170c8b4825e969fd3b

% git merge 2.11.x
Auto-merging versions.properties
Auto-merging test/scaladoc/scalacheck/HtmlFactoryTest.scala
Auto-merging test/junit/scala/tools/nsc/backend/jvm/opt/MethodLevelOpts.scala
Auto-merging test/junit/scala/collection/IteratorTest.scala
CONFLICT (content): Merge conflict in test/junit/scala/collection/IteratorTest.scala
Auto-merging test/files/neg/names-defaults-neg.scala
Auto-merging test/files/neg/names-defaults-neg.check
Auto-merging src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
Auto-merging src/scaladoc/scala/tools/nsc/doc/html/page/diagram/DotDiagramGenerator.scala
Auto-merging src/scaladoc/scala/tools/nsc/doc/html/page/Template.scala
Removing src/repl/scala/tools/nsc/interpreter/session/JLineHistory.scala
Auto-merging src/repl/scala/tools/nsc/interpreter/Tabulators.scala
Removing src/repl/scala/tools/nsc/interpreter/JLineReader.scala
Removing src/repl/scala/tools/nsc/interpreter/Delimited.scala
Auto-merging src/repl-jline/scala/tools/nsc/interpreter/jline/FileBackedHistory.scala
Auto-merging src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
Auto-merging src/reflect/scala/reflect/internal/Symbols.scala
Auto-merging src/reflect/scala/reflect/internal/StdNames.scala
Auto-merging src/manual/scala/man1/scalac.scala
CONFLICT (content): Merge conflict in src/manual/scala/man1/scalac.scala
Auto-merging src/library/scala/util/Try.scala
Auto-merging src/library/scala/collection/mutable/ListBuffer.scala
Auto-merging src/library/scala/collection/immutable/Stream.scala
Auto-merging src/library/scala/collection/immutable/List.scala
Auto-merging src/library/scala/collection/Iterator.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Typers.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Infer.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Auto-merging src/compiler/scala/tools/nsc/transform/UnCurry.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/transform/UnCurry.scala
Auto-merging src/compiler/scala/tools/nsc/transform/Erasure.scala
Auto-merging src/compiler/scala/tools/nsc/transform/Delambdafy.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/transform/Delambdafy.scala
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/GenASM.scala
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
Auto-merging src/compiler/scala/tools/nsc/backend/icode/GenICode.scala
Auto-merging src/compiler/scala/tools/nsc/ast/DocComments.scala
Auto-merging src/compiler/scala/tools/nsc/Global.scala
Auto-merging build.xml
CONFLICT (content): Merge conflict in build.xml
Auto-merging build.sbt
Auto-merging bincompat-forward.whitelist.conf
Automatic merge failed; fix conflicts and then commit the result.

% ant -q all.clean test.suite test.scaladoc

...

```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @lrytz

**Comment by retronym** [comment]
Conflicts in build.xml were `actors` vs `repl-jline` subproject changes. Other conflicts were in code that I had changed related to indylamdbda vs removal of `jvm:1.{5,6,7}` targets.

**Comment by lrytz** [comment]
now there's a [different failure](https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/70/consoleFull):

```
  [partest] !! 20 - scalap/t8679.scala                        [output differs]
```

Adriaan mentioned seeing the exact same failure yesterday when building the 2.12 branch, so it's unrealated to the merge. Interestingly it passed in the previous run (before you updated the `t8918-unary-ids` test), see https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/69/consoleFull, so it seems to be flaky.

Started a rebuild.

**Comment by lrytz** [comment]
hmm, again.. i cannot reproduce it locally, tried in various ways.

**Comment by lrytz** [comment]
Still cannot reproduce.

I ran the same command as jenkins

```
ant -Dstarr.version=2.12.0-1f7417c-SNAPSHOT -Dscalac.args.optimise=-optimise -Dlocker.skip=1 -Dextra.repo.url=https://scala-ci.typese.com/artifactory/scala-pr-validation-snapshots/ test.suite
```

on my machine. Even tried on a linux machine with OpenJDK and the same `ANT_OPTS`. Never saw `scalap/t8679.scala` failing.

Re-building one last time.

**Comment by lrytz** [comment]
nope. still the same. i don't know what's up. `/home/jenkins/workspace/scala-2.12.x-validate-test/test/files/scalap/t8679-scalap.log` is empty.

**Comment by adriaanm** [comment]
Here's the list of PRs that saw scalap failures like this one: #4460, #4504, #4514, #4526, #4547, #4556, #4561, #4562, #4565, #4578, #4580

**Comment by adriaanm** [comment]
In other words, let's not be blocked by the flakiness, even though we should probably find out what's causing it... I suggest we disable the huge test and see if it's flake-inducing.

**Comment by adriaanm** [comment]
@retronym thinks it's due to a hotspot bug, based on https://groups.google.com/forum/#!msg/scala-user/0GsO0Hv9yfA/NF941LpsqEAJ

**Comment by adriaanm** [comment]
I upgraded our jenkins workers to ubuntu vivid to get `java 1.8.0 update 45 build 14`, to get a fix for https://bugs.openjdk.java.net/browse/JDK-8058847?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel, which we suppose was causing flaky test failure for scalap test

**Pull request merged**
