### PR TITLE
SI-9030 make BoxesRunTime.equalsNumChar public

### PR DESCRIPTION
**Pull request by lrytz**
When comparing a Number and a Character, the backend directly emits a
call to this method.

### CODE REVIEW

**Comment by Ichoran** [comment]
This isn't binary compatible (post-patch you can generate a call to a method that pre-patch you don't have access to).  Shouldn't it go in 2.12?  (Which backend directly emits this call?)

**Comment by lrytz** [comment]
hmm, good point.. do you know why MIMA didn't catch that?

both backends are emitting calls to that method ([GenICode](https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/backend/icode/GenICode.scala#L1498), [BenBCode](https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L1228)).

we can push the fix to 2.12, and make the 2.11 backends use the more generic [equalsNumObject](https://github.com/scala/scala/blob/2.11.x/src/library/scala/runtime/BoxesRunTime.java#L142), that would be binary compatible.

**Comment by Ichoran** [comment]
@lrytz - No idea about MIMA; I have only the vaguest idea how it works.  The more conservative approach sounds fine, as long as you have the right boxing in place.

**Comment by lrytz** [comment]
PLS REBUILD ALL - just to test if PR validation still works after the Jenkins upgrade

**Comment by adriaanm** [comment]
Closing this due to (undetected!) binary incompat.

**Comment by lrytz** [comment]
binary compatible fix in #4196

**Pull request closed without merging**
