### PR TITLE
Enforce explicit return type for macros [ci: last-only]

### PR DESCRIPTION
**Pull request by som-snytt**
The previous warning already expired.
    
Fix offending tests.

Apologies in advance if there's a good reason the stern warning was never followed up.

### CODE REVIEW

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
@SethTisue could you coordinate merging this based on the community build?

**Comment by SethTisue** [comment]
test run: 
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1299/

**Comment by SethTisue** [comment]
the run shows that scalatest and specs2 need updating for this, and then probably other projects downstream, too.

let's take care of it after M5 is out the door

**Comment by SethTisue** [comment]
I'll deal with the community build breakage, gradually.

**Pull request merged**
