### PR TITLE
reflection now correctly supports inner classes and modules

### PR DESCRIPTION
**Pull request by xeno-by**
This is a quick and dirty solution to `Class.getDeclaredClasses` not working for some corner cases of name mangling w.r.t inner classes and modules. In future we might investigate cleaner solutions to the problem.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @odersky

**Comment by odersky** [comment]
LGTM for now. It would be good to factor this whole inner classes thing out into something aproaching sanity at some point. But not right now.

**Comment by jsuereth** [comment]
reflection sanity checks failing.

**Comment by xeno-by** [comment]
Yep my fault - I'll deal with it once I get home

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
so this means the earlier commits won't pass the test suite? if that's the case, please combine the fixup commit with the original broken commit so we don't get any failures in scala-checkin

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
