### PR TITLE
remove @since and @version tags from Scaladoc

### PR DESCRIPTION
**Pull request by SethTisue**
the `@version` tags are well and truly useless, afaict.
I suspect some IDE templating thing inserted them,
back in the day.

perhaps the `@since` tags have some small nonzero value, but they
were never consistently applied. most classes don't have them,
and the ones that exist are often for really ancient versions.
it seems like noise to me.

separate commits in case there's dissent on the `@since`.

### CODE REVIEW

**Comment by eed3si9n** [comment]
I am 👍 on the removal. In addition, maybe we should add a section in the CONTRIBUTING noting that we don't want `@since` and `@version` so we can point at it if we notice them during PR.

**Review by dwijnand — APPROVED** [review]
LGTM.

Did we grow back some `@author`s?  I thought you'd removed those already, but I see some in the diff.

**Comment by SethTisue** [comment]
> maybe we should add a section in the CONTRIBUTING noting that we don't want @since and @version so we can point at it if we notice them during PR

I doubt that's going to be a problem, I think people were sometimes still just putting them in because they'd seen them elsewhere in the codebase.

**Comment by SethTisue** [comment]
> Did we grow back some @authors? I thought you'd removed those already, but I see some in the diff

I didn't bother doing `src/compiler` in that PR, I primarily targeted `src/library`. (Not for any special reason really, `src/library` is just higher visibility in general.)

**Comment by SethTisue** [comment]
fwiw, `@since` and `@version` show up in the rendered doc, `@author`  does not

**Comment by ashawley** [comment]
I also consider this noise, and helped remove `@version` in #6586, even changing some to `@since`.

Scala's APIs became relatively stable for ten years, so there was probably no reason to either use nor maintain `@since` entries.

**Pull request merged**
