### PR TITLE
[backport] upgrade to ASM 7

### PR DESCRIPTION
**Pull request by SethTisue**
2.12.x backport of #7384

goal: improve compatibility with JDK 12, as per [scala/community-builds#864](https://github.com/scala/community-builds/issues/864) and [scala/bug#11372](https://github.com/scala/bug/issues/11372)

fixes scala/bug#11372

### CODE REVIEW

**Comment by SethTisue** [comment]
in a local partial community build run on JDK 12, I verified that several projects that failed before are green now: scalaz,scala-async,scala-partest

but let's do a full JDK 12 run on Jenkins, too, just in case: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk12-integrate-community-build/24/

**Comment by SethTisue** [comment]
I verified locally that https://github.com/scala/bug/issues/11372 goes away with `2.12.9-bin-1220d3c-SNAPSHOT`

**Comment by SethTisue** [comment]
> let's do a full JDK 12 run on Jenkins, too, just in case

the results show that this PR raises the number of green projects in the community build from 98 to 139, and without introducing any additional failures

@adriaanm @retronym shall we merge?

**Comment by SethTisue** [comment]
(one additional piece of due diligence: https://asm.ow2.io/versions.html shows that 7.0 is still the most recent ASM version)

**Comment by smarter** [comment]
As far as I can tell, the compilation errors only happen when the backend optimizer is turned on, since that's what triggers ASM looking into classfiles from your dependencies, why not degrade gracefully and have the optimizer not look into classfiles it can't read ? Or if that's not possible, at least make the optimizer output an error message explaining to the user that he needs to downgrade his JVM, disable the optimizer, or upgrade his scalac.

**Comment by SethTisue** [comment]
> As far as I can tell, the compilation errors only happen when the backend optimizer is turned on

yes, likely correct, I didn't get to the bottom of every individual failure, but every one I did look at it turned out to involved the optimizer

> why not degrade gracefully

seems like a good suggestion, but it exceeds my own ambitions for this PR. perhaps someone else will take it up

**Comment by SethTisue** [comment]
I'm going to go ahead and merge this because I think we should have nightly builds that work on JDK 12. And for the community build.

**Comment by SethTisue** [comment]
this raised the number of green jobs at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk12-integrate-community-build/ from 97 to 147

**Pull request merged**
