### PR TITLE
merge 2.11 to 2.12 Oct 16

### PR DESCRIPTION
**Pull request by SethTisue**
details are in the merge commit (3141fdd6628df5c123db0250abc8ccfcf20d7eff)

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @lrytz

**Comment by lrytz** [comment]
```
/home/jenkins/workspace/scala-2.12.x-validate-test@2/build.xml:1457: Test scala.collection.mutable.OpenHashMapTest failed
```

**Comment by lrytz** [comment]
```
Testsuite: scala.collection.mutable.OpenHashMapTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.035 sec

Testcase: maintainsDeletedCount took 0.024 sec
    Caused an ERROR
scala$collection$mutable$OpenHashMap$$deleted
java.lang.NoSuchFieldException: scala$collection$mutable$OpenHashMap$$deleted
    at java.lang.Class.getDeclaredField(Class.java:2070)
    at scala.collection.mutable.OpenHashMapTest.maintainsDeletedCount(OpenHashMapTest.scala:31)
```

**Comment by lrytz** [comment]
The test uses reflection to read the private `deleted` field. Not sure why it cannot find it, maybe name mangling is different in 2.12? I didn't take a closer look.

**Comment by SethTisue** [comment]
arghh. sorry, these most recent pushes are bad. working on it.

**Comment by SethTisue** [comment]
fixed. Jenkins is green now. re-review by @lrytz

**Comment by lrytz** [comment]
LGTM!

**Pull request merged**
