### PR TITLE
Remove deprecated MurmurHash

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by hrhino** [comment]
Cool! Since this removes public API (and is therefore not [binary-compatible](https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html)), you should rebase it onto the `2.13.x` branch, and the build will pass.

**Comment by naferx** [comment]
@hrhino Could you give me guidance here, please ?. I got confused

**Comment by hrhino** [comment]
So what you want to do is rebase your commit on top of `2.13.x`. You can do this by:

```bash
git checkout remove-murmurhash
git reset --hard origin/2.13.x
git cherry-pick 2e57b59
```

which moves `remove-murmurhash` onto `2.13.x` and then cherry-picks your one commit back onto that branch.

Then you can edit this PR to set the destination branch to `2.13.x`, and you should be good.

**Comment by naferx** [comment]
Thanks a lot! @hrhino
Hope all is well now

**Review by SethTisue — APPROVED** [review]

**Comment by adriaanm** [comment]
Thank you @naferx -- removing deprecated stuff is a great help for 2.13! Also, thanks @hrhino for the coaching :-) ❤️

**Comment by naferx** [comment]
@adriaanm  My pleasure :)

**Pull request merged**
