### PR TITLE
Small documentation fixes & small fix to Scaladoc @see formatting

### PR DESCRIPTION
**Pull request by heathermiller**
- updates some old links to point to doc site
- massaging of doc comments on `Try` so as to make them actually appear (on method `flatten`)
- fixes formatting of "See also" Scaladoc tag for multi-line "See also"s

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM, but just to make sure a real scaladoc guy checks it out:

Review by: @VladUreche

**Comment by VladUreche** [comment]
Josh, if there are any problems with Heather's patch, we should file bugs against scaladoc :p

**Comment by heathermiller** [comment]
Hi guys. This is a really trivial patch. Really. And it touches just one line of Scaladoc. Otherwise it's only doc comments.

**Comment by heathermiller** [comment]
(And that one line of Scaladoc only prevents an extra line break when you have multiple `@see` tags)

**Comment by jsuereth** [comment]
Just wanted someone to look at the one line.  Ye ole code review process in action.  Thanks!

**Pull request merged**
