### PR TITLE
Add JavaConversions and JavaConverters concurrent.Map support.

### PR DESCRIPTION
**Pull request by axel22**
This required deprecating several old methods for converting ConcurrentMap.
Also, several new wrappers were introduced for concurrent.Map. Once we
remove ConcurrentMap in 2.11, we can remove its corresponding wrappers and
conversions in JavaConversions and JavaConverters.

### CODE REVIEW

**Comment by ijuma** [comment]
It would be nice if we could get atomic getOrElseUpdate in concurrent.Map instead of having to use putIfAbsent. Java 8 is getting something like it by the way.

**Comment by ijuma** [comment]
I guess this is a random spot to leave this comment, but the pull request reminded me. ;)

**Comment by axel22** [comment]
Sounds like it could be interesting, provided that it can be atomically implement in terms of the other 4 primitives (so that wrapping in JavaConversions can work correctly). Can you point me to a relevant discussion/announcement about the getOrElseUpdate in Java?

**Comment by ijuma** [comment]
Sure:

http://cs.oswego.edu/pipermail/concurrency-interest/2011-August/008176.html

The method is called computeIfAbsent in Java.

**Comment by axel22** [comment]
At first glance it seems that computeIfAbsent could be implemented using putIfAbsent.

`at`tailrec def computeIfAbsent(key: K, compute: =>V): Option[V] = {
  get(key) match {
    case Some(v) => Some(v)
    case None => putIfAbsent(key, compute) match {
      case Some(v) => computeIfAbsent(key, compute)
      case None => None
    }
  }
}

or just:

def computeIfAbsent(key: K, compute: =>V): Option[V] = {
  get(key) match {
    case Some(v) => Some(v)
    case None => putIfAbsent(key, compute) match {
      case Some(v) => Some(v)
      case None => None
    }
  }
}

**Comment by ijuma** [comment]
Yes, I would be happy with the second implementation even if it has different semantics to what they are implementing in Java 8.

**Comment by axel22** [comment]
So this:

```
 *         'at'return the current (existing or computed) value associated with
 *         the specified key.
```

is the difference? Interesting, then there is no way of knowing if the key was already in there or not.

But, if our semantics are even slightly different, we should name it differently, so that we avoid subtle surprises.

**Comment by paulp** [comment]
Unfortunately this pull req is a barrage of merge conflicts because JavaConversions/JavaConverters were heavily reorganized.  Can you reformulate it against current trunk?

**Comment by axel22** [comment]
I'll take care of it and resubmit the pull request.

**Comment by ijuma** [comment]
Another difference is that computeIfAbsent performs some locking to avoid computing the same thing more than once if called concurrently. If we implement it in terms of putIfAbsent, then we don't get that. The locking is useful in some cases, but not in others. My preference is to provide another structure for the case where locking is required and leave the main one simple.

**Comment by axel22** [comment]
But the locking is data-structure-specific.
I'm not sure if it's sensible to require `computeIfAbsent` to do locking to guarantee that the computation occurs only once, in the `concurrent.Map` trait. It's too restrictive for some data-structures (e.g. concurrent skip lists).

We could instead say that the computation will occur up-to-once, but this does not mean that the result will be stored in the map.

**Comment by ijuma** [comment]
I agree that we should not require that.

**Pull request closed without merging**
