### PR TITLE
Change unrecognized scaladoc comments to C-style

### PR DESCRIPTION
**Pull request by huitseeker**
This is a re-work of https://github.com/scala/scala/pull/2394

### CODE REVIEW

**Comment by huitseeker** [comment]
[FYI](https://github.com/scala/scala/pull/2394#issuecomment-16380521)

**Comment by som-snytt** [comment]
Hey, it lines up!

I don't understand what the build is doing, but on the other PR, I see GenICode still has its unmoored doc. (That was one of the two actual pretty doc comments.)

The other one, though, in SyntheticMethods is actually

```
    /****
    def productNMethods = {
```

So the position on the error isn't right, which is at the // comment.  I'll check that in my PR.

I wonder if quad-star comments are reportable.  I've never wondered if javadoc requires exactly two stars.

LGTM, too, FYI.

**Comment by huitseeker** [comment]
@som-snytt Yes, I removed GenICode from comments affected by this PR after eyeballing it. If you're confident it's an actual scaladoc snippet too, I'll report this as a bug against scaladoc.

The one in SyntheticMethods is unaffected by this PR.

**Comment by som-snytt** [comment]
My observation was that it's a shame to lose perfectly good doc comments which don't happen to be public or protected.

SI-3807 says scaladoc 2 dropped support for -access:private.  Maybe I'll take that on, and include local defs, which is where all the work gets done and therefore where all the explaining is needed.

It would be really neat to look at "developer doc" and see not only documented innards but compilation details (inlining, mangled names).

**Comment by retronym** [comment]
LGTM

**Pull request merged**
