### PR TITLE
SI-6086 magic symbols strike back

### PR DESCRIPTION
**Pull request by xeno-by**
Some of the symbols inside the compiler get created on the fly,
because there are no physical entities in classfiles corresponding to them.

This curious fact needs to be taken into account when loading symbols,
so that the magic symbols get correctly loaded by reflective mirrors.

magicSymbols (as defined in Definitions.scala) include not only
top-level classes, but some other stuff (e.g. String_+ or methods on Any).
Hence a filtering was done to exclude the stuff that's irrelevant
to reflective symbol loading.

Unfortunately a filter was configured to accept only _.isClass,
which consequently ruled out scala.AnyRef (that is a type alias).

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @adriaanm

**Comment by xeno-by** [comment]
A spurious failure. What do I do next?

**Comment by adriaanm** [comment]
You take the spurious failure out back and "deal" with it.

(I'm removing it in a pull request coming up shortly.)

**Comment by adriaanm** [comment]
PLS REBUILD ALL (hopefully it'll be luckier this time)

**Comment by gkossakowski** [comment]
I just wanted to express my satisfaction with the commit message. I can easily understand what's going on with this change :-)

**Comment by adriaanm** [comment]
LGTM, though I'm still skeptical of the duplication of magic lists of symbols around the compiler

**Pull request merged**
