### PR TITLE
Fixed two grammar mistakes.

### PR DESCRIPTION
**Pull request by awl**
First was clearly just a typo, second was using e.g. ("exepli gratia" or "for example) when it should be using i.e. ("id est" or "that is")

### CODE REVIEW

**Comment by Blaisorblade** [comment]
> "For instance, both will present as incomplete, or as completed with the same result value."

I mostly like that, but I'd like "complete" (no d) for extra parallelism:

"For instance, both will present as incomplete, or as complete with the same result value."

And I'd stick to "appear" for simplicity. The text already uses "appear" with a pretty clear meaning: "[linked promises] will appear, to external callers, to have [...]". This suggests that the actual status is encapsulated; and the actual status is only relevant to the implementation, not to users of a class.

**Comment by Blaisorblade** [comment]
Warning to reviewers: #3186 is alternative to this PR.

**Comment by adriaanm** [comment]
@awl, thanks for getting the ball rolling! May you win the grammar wars next time :-)

**Comment by som-snytt** [comment]
At least you can say that @awl had a point.  (awful pun alert)

**Comment by awl** [comment]
Sorry, but I really think that you guys got this one wrong. "For instance" is not the right wording here, which is exactly why I changed it from "e.g.," which essentially means "for instance," to "i.e.," which means, essentially, "that is." "For instance" should be used to give an example that clarifies a previous phrase, but here you are enumerating _the only two_ possible outcomes, not providing an example, and this means that you should replace "For instance" with something like "that is," "meaning," or, in fact, nothing at all.

Any of these are proper, but I adamantly believe that "for instance" is distinctly wrong. 

This means that two DefaultPromises that are linked will appear, to external callers, to have exactly the same state and behaviour -- both will appear as incomplete, or as complete with the same result value.

This means that two DefaultPromises that are linked will appear, to external callers, to have exactly the same state and behaviour, i.e. both will appear as incomplete, or as complete with the same result value.

This means that two DefaultPromises that are linked will appear, to external callers, to have exactly the same state and behaviour, meaning both will appear as incomplete, or as complete with the same result value.

**Comment by som-snytt** [comment]
It's confusing that it says there are "three possible states", complete, incomplete and linked.  You're right, "to external callers," incomplete and complete completely enumerate the states, and that is the emphasis.  I could even go for `viz.` here. 

(I also noticed `impl` isn't in the generated docs.)

**Comment by Blaisorblade** [comment]
That is, "to external callers", a `Promise[T]` contains as much information as `Cell[Option[T]]`, with different method names, and where `Cell[T]` is a mutable cell which allows reading and writing its value? If that were right, then you could use "that is".

However, I chose "for instance" because there's more to a Promise. I wanted to use `future` as an example of behavior which already goes beyond that, but then I read the [documentation of `link`](https://github.com/scala/scala/blob/1d8e8ffa0f9e3334d4387b6dc074f924b41410ce/src/library/scala/concurrent/impl/Promise.scala#L291), which is more precise about the "externally-visible state", that is, what's visible to "external callers":

> Link this promise to another promise so that both promises share the same
> externally-visible state. Depending on the current state of this promise, this
> may involve different things. For example, any onComplete listeners will need
> to be transferred.
> 
> It's confusing that it says there are "three possible states", complete, incomplete and linked.

That's because this ScalaDoc does not just describe the behavior for "external callers". In fact, it distinguishes linked promises from the original ones, and it draws this distinction because [they're not fully equivalent](https://github.com/scala/scala/blob/1d8e8ffa0f9e3334d4387b6dc074f924b41410ce/src/library/scala/concurrent/impl/Promise.scala#L122):

> the concept of linking promises together needed to become an explicit feature of the DefaultPromise implementation.

The concept of linked promises can be hidden to "external callers" but only as long as they behave themselves nicely — for instance, they better not call eq (which brings me back to https://twitter.com/extempore2/status/392337604831498241).

> (I also noticed impl isn't in the generated docs.)

Which ones? I see it [here](http://lampwww.epfl.ch/~hmiller/scaladoc/library/scala/concurrent/impl/Promise$$DefaultPromise.html), though I'm not sure whether that's supposed to be an up-to-date nightly build.

**Comment by som-snytt** [comment]
Nightly doc is http://www.scala-lang.org/files/archive/nightly/docs-master/library/#package

**Comment by Blaisorblade** [comment]
I see — `impl` is indeed missing there. Is that a problem? Or does that mean this is internal documentation?

**Pull request closed without merging**
