### PR TITLE
SI-5090: Expose the current size of ArrayBuilder

### PR DESCRIPTION
**Pull request by thorpe-dev**

### CODE REVIEW

**Comment by soc** [comment]
Hi @mt2309, could you add more information to your commit message, please?

**Comment by thorpe-dev** [comment]
@soc done :)

**Comment by paulp** [comment]
@mt2309 "length" is an ambiguous name. Since it is the java-hardcoded name for native Arrays, one might easily imagine that it refers to the length of the Array inside the ArrayBuilder. But it doesn't mean that.

I think you should change the name of "private var size" to something else, and call this "size".

**Comment by som-snytt** [comment]
@mt2309 @paulp I also thought

> "length" is an ambiguous name

but I wasn't sure about size.  Consider "sizeHint". So "size" is also ambiguous.  It could mean "expected result size."

We want "instantaneous size."  I get "instantaneous" not from high school calculus, but from the gas mileage display on the car.

I was too shy to suggest that, and couldn't think of something better.  It has to express, "if you asked for a result right now, its size would be..."  That is, "resultSize".  Or to give a hint of instantaneity, "resultingSize".

**Comment by retronym** [comment]
There doesn't seem to be a consensus about the name of this method. Can you please send a mail to scala-internals with a summary of the options and see if one emerges? I'll close this PR in the meantime, but just add a comment here when it is ready to reopen.

Naming == hard...

**Pull request closed without merging**
