### PR TITLE
Ystats

### PR DESCRIPTION
**Pull request by som-snytt**
Reduce book-keeping Lukas's cleanup by using an Enumeration and a ValueSet or two.

Enumeration rocks!

See if this passes tests this morning.

I wanted to PR against lrytz, but the UI doesn't show me how. :(

### CODE REVIEW

**Comment by som-snytt** [comment]
That didn't get very far.  Obviously, it worked on my machine...  I'll take it up later in the evening.

**Comment by lrytz** [comment]
this fuzzy feeling when scalac doesn't manage to unify paths of dependent types. i'm continuing on this one now.

**Comment by som-snytt** [comment]
I found a few minutes to convince myself there's a correct idiom in today's Scala, but I hadn't got back to the PR yet.  You like the idea or is it hokey? @lrytz 

Actually, I think my last experiment pushed the type member into a type param.  I'll check it out quickly and see what happened. Oh yeah, I noticed on SO that some things are inferred now.  http://stackoverflow.com/a/25574902/1296806

**Comment by lrytz** [comment]
Honestly, I'm not a big fan of enumeration, but I like all of your other changes. I'll take enum out, if you don't mind.

**Comment by som-snytt** [comment]
I don't mind doing it.  The real problem is that if you want to look something up, you need the enum hanging around.  Let me know if you want me to try cleaning it up.

**Comment by lrytz** [comment]
Yes, I see what you say. Let me work on it a bit, if it goes well I keep enum. I have some other stuff that depends on the MultiChoice change, so I want to push it through now.

**Comment by som-snytt** [comment]
I think bagging enum is the right thing; it can use a bit set internally.  Why don't you use your other PR, and I'll resubmit this as an optimization?  The API stays the same on settings.

**Comment by lrytz** [comment]
I need the configurable defaults, and I prefer to work on top of this PR, makes things easier. The enum types thing should be very easy to fix.

**Comment by som-snytt** [comment]
OK, let me know if you want me to do something.  Today is a holiday here; Java-free day. I'm not wedded to the enum idea.  I see there were a couple of tweaks in my local repo: your comment was addressed, and for instance

```
diff --git a/src/compiler/scala/tools/nsc/MainBench.scala b/src/compiler/scala/tools/nsc/MainBench.scala
index eb56c8a..ee77d79 100644
--- a/src/compiler/scala/tools/nsc/MainBench.scala
+++ b/src/compiler/scala/tools/nsc/MainBench.scala
@@ -24,7 +24,8 @@ object MainBench extends Driver with EvalLoop {
     var start = System.nanoTime()
     for (i <- 0 until NIter) {
       if (i == NIter-1) {
-        theCompiler.settings.YstatisticsPhases.value = theCompiler.settings.YstatisticsPhases.default.get
+        //theCompiler.settings.YstatisticsPhases.value = theCompiler.settings.YstatisticsPhases.default.get
+        settings processArguments (List(settings.YstatisticsPhases.default mkString ("-Ystatistics:", ",", "")), processAll = true)
         Statistics.enabled = true
       }
```

showing some impedance mismatch between string and enum.  OTOH, maybe processArguments is better, etc.

**Comment by som-snytt** [comment]
I moved the type member to type param, but I actually had to write a 75 LOC test file, mimicking the Settings hierarchy, and jigger the self types to finally make it compile.  But the real thing still has one error...

```
[locker.compiler] /home/apm/clones/review/lrytz/src/compiler/scala/tools/nsc/settings/MutableSettings.scala:681: error: overloaded method value contains with alternatives:
[locker.compiler]   ((v: _351.Value)Boolean) forSome { val _351: D } <and>
[locker.compiler]   (elem: _353.Value)Boolean <and>
[locker.compiler]   (elem: _356.Value)Boolean
[locker.compiler]  cannot be applied to (MultiChoiceSetting.this.domain.Value)
[locker.compiler]     def contains(s: String)   = value contains (domain withName s)
[locker.compiler]                                       ^

```

That one was unexpected.

**Pull request closed without merging**
