### PR TITLE
SI-5022 Retain precise existentials through pattern matching

### PR DESCRIPTION
**Pull request by retronym**
From the dawn of scalac's existentials, the typer widens
existentials pt-s by substituting wildcard types in places
of existential quantifiers.

In this example:

```
class ForSomeVsUnapply {
  def test {
    def makeWrap: Wrap = ???
    def useRep[e](rep: (e, X[e])) = ()

    val rep = makeWrap match {
      case Wrap(r) => r
    };

    useRep(rep) // error
  }
}
```

the type of `r` is the result of typechecking:

```
Apply(
 fun = TypeTree(
   tpe = (rep#12037: (e#12038, X#7041[e#12038]) forSome { type e#12038 })
 args = Bind(r @ _) :: Nil
}
```

This descends to type the `Bind` with:

```
pt = (e#12038, X#7041[e#12038]) forSome { type e#12038 }
```

`dropExistential` clobbers that type to `Tuple2#1540[?, X#7041[?]]`,
which doesn't express any relationship between the two instances
of the wildcard type. `typedIdent` sort of reverses this with a call
to `makeFullyDefined`, but only ends up with:

```
pt = (Any#3330, X#7041[_1#12227]) forSome { type _1#12227; type e#12038 }
```

I suspect that this existential dropping only makes sense outside of
typechecking patterns. In pattern mode, type information flows from the
expected type onwards to the body of the case; we must not lose precision
in the types.

For SIP-18 friendly existentials, one `dropExistential` is invertable with
`makeFullyDefined`, so this hasn't been such a big problem.

The error message improvement conferred by SI-4515 took a hit.
That might be a good example to consider when reviewing this change:
Does it tell us anything interesting about this `dropExistential`
business?

Review by @adriaanm.

If we go forward with this, I can address the two FIXME's introduced in this patch before merging.

### CODE REVIEW

**Comment by soc** [comment]
LGTM.

**Comment by adriaanm** [comment]
Wow! This sure looks like the way to go! I've really struggled with existentials in the new pattern matcher (which is stricter in typing the transformed code). There's probably several make-fully-defined fixer-upper hacks that can be dropped if one takes a more principled stance.

I'd like to sleep over my LGTM, but it sure has a lot of LGTMiness to it.

**Comment by gkossakowski** [comment]
@adriaanm: Do you have enough of confidence to give this PR final LGTM stamp?

**Comment by adriaanm** [comment]
LGTM

**Comment by gkossakowski** [comment]
@retronym: does this fix SI-5022? If so, I'd like to close the ticket.

**Comment by retronym** [comment]
Yep, I've just closed it. We should work on the assumption that if the PR is entitled `SI-XXXX ....` and no qualification is provided in the message that it is closable.

**Comment by gkossakowski** [comment]
Ok. I'll take that into account in the future.

**Pull request merged**
