### PR TITLE
SI-8494 Restore filtering javap output

### PR DESCRIPTION
**Pull request by som-snytt**
Regressed in support for new delayedEndPoint, where it must
pick what to filter for.

`s/claas/klass/` and similar.

Review by @retronym who had to manually snip some output, to my chagrin

### CODE REVIEW

**Comment by som-snytt** [comment]
PLS REBUILD/pr-scala@7332240

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
LGTM

**Comment by som-snytt** [comment]
Feel free to make fun of my adriaanesque "claas."  That seemed so stylish at the time.

Sorry again that #foo didn't work for you when you wanted it. hashtag shame.

**Comment by som-snytt** [comment]
Offhand, I'm not sure how to view the log artifact from the IDE build failure.

**Comment by adriaanm** [comment]
Some of them are stashed over at https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/ws/target/scala-ide/org.scala-ide.sdt.core.tests/target/surefire-reports/

**Comment by adriaanm** [comment]
Scraatch thaat, they are archived for every build: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7441/artifact/target/

**Comment by som-snytt** [comment]
Daanke.

There was a kind of failure, but I don't know what it means, yet.  Which PR was this again?

```
org.junit.ComparisonFailure: The completion 'ident2' does not exist. expected:<ident[2]> but was:<ident[ity[A](A): A
```

Um.  It's like a unit test pun.

```
[testfile.scala]: exception during background compile: java.lang.AssertionError: assertion failed: private[this] val ident1: Int = 0


java.lang.AssertionError: assertion failed: private[this] val ident1: Int = 0


        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$BaseGetter.validate(MethodSynthesis.scala:376)

        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$DerivedFromValDef$class.derive(MethodSynthesis.scala:327)

        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$BaseGetter.derive(MethodSynthesis.scala:369)

        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$$anonfun$2.apply(MethodSynthesis.scala:184)

        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$$anonfun$2.apply(MethodSynthesis.scala:184)

        at scala.collection.immutable.List.map(List.scala:278)
```

There's another failure that smacks of spuriousness:

```
[org.eclipse.jdt.launching] error can't determine modifiers of missing type org.eclipse.pde.internal.ui.wizards.imports.PluginImportHelper
when weaving type org.eclipse.jdt.internal.launching.JREContainerInitializer
```

I wouldn't want to waste kitteh's time and resources with rebuilds.

Of course, what else does kitteh have to do except sit in the window and stare at passersby?

**Comment by adriaanm** [comment]
It likes to play with threads. I tried not to disturb it and hit rebuild myself: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/7490/console

**Comment by adriaanm** [comment]
PLS SYNCH

**Comment by adriaanm** [comment]
Looks like the spurium was resolved, which kitteh telepathically picked up on.

**Comment by som-snytt** [comment]
If I were a superhero, and full disclosure I'm not, spurium would be the rare element that leaves me writhing helpless and superpowerless.

@adriaanm Thx.

**Pull request merged**
