### PR TITLE
Fix for SerialVersionUID instability.

### PR DESCRIPTION
**Pull request by paulp**
Can hardly believe this has been broken for a decade or so, but
there it is - see test case. Four classes attempt to set their
SerialVersionUID to 13. One succeeds. No warnings or errors. The
output before this patch (for me anyway - your random numbers may
differ) was:

  860336111422349646
  13
  8409527228024057943
  -7852527872932878365

There was already code in place for rejecting annotations
with non-constant args when constant args are required, but
that check is only performed on ClassfileAnnotations, and
SerialVersionUID was a StaticAnnotation. Maybe people don't
reach for ClassfileAnnotation because of this giant warning
which I see no way to suppress:

  warning: Implementation restriction: subclassing Classfile does
  not make your annotation visible at runtime. If that is what you
  want, you must write the annotation class in Java.

Why did I change the name of the field from uid to value?
If you don't use the name 'value', you have to name the argument
every time you use it, even if it's the only parameter. I didn't
relish breaking every usage of scala's @SerialVersionUID in the
known universe.

### CODE REVIEW

**Comment by paulp** [comment]
Opened against master because it's presumably binary-incompatible.

**Comment by paulp** [comment]
Review by anyone with a clue about serialization. @jsuereth, @lrytz ?

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
Okay, review by @harrah, you must know something about serialization.

**Comment by harrah** [comment]
LGTM

**Comment by paulp** [comment]
Did "I didn't relish breaking every usage of scala's @SerialVersionUID in the known universe" win any prestigious irony awards?

**Comment by som-snytt** [comment]
"Known universe" was too restrictive a domain, so it was actually up for Understatement.  But the other comment that "it's presumably binary-incompatible" won one of those technical awards they give out the day before the big event which no one attends except of a couple of stringers.  I think the category was, "Irony in an observation that applies to everything except this."  But next year they're starting a special category to recognize binary incompatibility; the statuette shows one hand washing another, with the inscription on the base: "mea paulpa."

**Pull request merged**
