### PR TITLE
Fix SI-7224.

### PR DESCRIPTION
**Pull request by dragos**
Don't focus positions assigned to the TypeTree of a parent of a Template
when the parent exists in the source. A focused position (instance
of `OffsetPosition`) makes it invisible to the presentation compiler
when it looks for the innermost enclosing tree of a given position
(breaking hyperlinking, for example). See [IDE ticket #1001553](https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1001553).

(I couldn't find a way to reproduce the pr-ragepos build locally, as I couldn't find the definition of the corresponding Jenkins job)

review by @huitseeker, @hubertp

### CODE REVIEW

**Comment by adriaanm** [comment]
ragepos is a good name -- the PR validation jobs are here: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/

**Comment by dragos** [comment]
@adriaanm hehe.. you're right, but I can't see the job definitions.

**Comment by lrytz** [comment]
you can see all shell commands that are executed in the log of any build, e.g. https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-rangepos-per-commit/994/consoleFull
that helped me once to get the scala ide building :)

**Comment by adriaanm** [comment]
The shell script run by jenkins for rangepos is:
https://github.com/lrytz/jenkins-scripts/blob/master/job/scala-checkin-rangepos

**Comment by huitseeker** [comment]
LGTM ! (Note to self: not [focusing](https://github.com/scala/scala/blob/master/src/reflect/scala/reflect/internal/util/RangePosition.scala#L21) on a position amounts to not dropping any range information present in the original position — so this changes defers the responsability of creating an `OffsetPosition` for a synthetic identifier to the creator of `supertpt`.)

**Comment by hubertp** [comment]
lgtm

**Comment by dragos** [comment]
Yeah, @paulp suggested https://github.com/scala/epfl-jenkins but that's empty. Good to know, I'll start watching @lrytz repositories form now on ;-)

**Comment by lrytz** [comment]
> I'll start watching @lrytz repositories form now on ;-)

actually we should move that stuff (and also some other) to @lampepfl - that didn't exist back when i started

**Pull request merged**
