### PR TITLE
SI-9011 Speculative fix for CCE in Scala IDE

### PR DESCRIPTION
**Pull request by retronym**
Based on the reported stack trace and what I know of Scala IDE,
I've changed `InteractiveNamer#enterExistingSymbol` to be `DocDef`
aware.

I haven't provided a test as this was not minimized from Scala IDE.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @dragos

**Comment by lrytz** [comment]
PLS REBUILD ALL

**Comment by dragos** [comment]
LGTM.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Pull request merged**
