### PR TITLE
SIP-11 String Interpolation Simplification

### PR DESCRIPTION
**Pull request by dgruntz**
Changed StringContext.f which implements the formatted string interpolator.

Any '%' not in formatting position is left in the resulting string literally. 
However, instead of adding '%s' format holders and extending the args with 
"%" expressions, these '%' are replaced by '%%'. The formatter then converts
'%%' (percent formatter) to the literal % (\u0025). This also simplifies the
spec.

The interpolation tests still pass.

I am a git newbie -- therefore this pull request also contains the bugfix SI5614
which I pulled some hours ago.

### CODE REVIEW

**Comment by paulp** [comment]
Can you verify you have signed and submitted the contributor agreement at http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf ?

**Comment by dgruntz** [comment]
no, I haven't. I will sign the agreement immediately. To whom can I hand over the signed agreement? Btw, I am currently on Sabbatical and I am working at LAMP (here in Lausanne) -- actually we met virtually at the last Sala meeting two weeks ago.
Best wishes
Dominik

**Comment by dgruntz** [comment]
Now I have read the agreement. All questions answered. Will hand it over to Danielle.
Domini

**Comment by dgruntz** [comment]
I have signed the agreement and handed it over to Danielle.

**Pull request merged**
