### PR TITLE
SI-7704 Fix partest's test category selection

### PR DESCRIPTION
**Pull request by soc**
My recent changes to command line parsing in 609070953c broke partest's
functionality of picking test categories (e. g. --pos or --run).

The breakage was caused because scala.tools.cmd._ stored the command
line options with the `--` prefix, but TestKinds.standardKinds did not.

### CODE REVIEW

**Comment by soc** [comment]
Review by @adriaanm / @som-snytt / @gkossakowski / @retronym / anyone who has time ... would be great to get this merged soon.
See https://groups.google.com/forum/#!topic/scala-internals/f5-5XNr8TiE.

**Comment by retronym** [comment]
Could you please split into two commits? One for the explicit return types, and one for the behavioural fix.

**Comment by soc** [comment]
@retronym Done.

**Comment by adriaanm** [comment]
Please move your fixes that affect stuff under src/partest to a PR on https://github.com/scala/scala-partest, which is where partest is going after #2774. I also believe the test category selection is fixed by https://github.com/scala/scala-partest/commit/d27865c9bda04660fc81ae1253bd5e9990272213, right?

**Comment by gkossakowski** [comment]
I don't PRs should be blocked by partest move. Once it's completed, we should just cherry pick whatever new commits appeared.

**Comment by soc** [comment]
@adriaanm See https://groups.google.com/d/msg/scala-internals/f5-5XNr8TiE/8SxMR4U5WYkJ

**Comment by adriaanm** [comment]
> I don't PRs should be blocked by partest move. Once it's completed, we should just cherry pick whatever new commits appeared.

Well, both PRs are in the queue, but only one of them will be mergeable as-is. Are you saying I should close my PR and resubmit after this one is merged?

**Comment by adriaanm** [comment]
> @adriaanm See https://groups.google.com/d/msg/scala-internals/f5-5XNr8TiE/8SxMR4U5WYkJ

I had read that -- what did I miss? Greg fixed the same bug in the commit I link to aboce.

**Comment by gkossakowski** [comment]
@adriaanm: No. I'm saying that we shouldn't block each other while PRs are reviewed. If there are new commits merged to partest since the commit you based your PR on we should just resync by cherry picking to the new repo. It's not a big deal and in this case you'll need to do nothing because two different commits fix the same thing.

**Comment by adriaanm** [comment]
Im saying that these PRs conflict. Mine deletes files that this one touches, so as soon as one of them is merged, the other will have to be redone. Since my PR fixes the same bug in partest as this PR, it's a bit redundant.

**Comment by gkossakowski** [comment]
@adriaanm: this PR has been hanging for 2 weeks now. What would like to do with it?

**Comment by soc** [comment]
PLS REBUILD ALL!

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
