### PR TITLE
Don't call `updateInfo` during typing.

### PR DESCRIPTION
**Pull request by dragos**
We resort to `setInfo`, basically removing the previous info. This "fixes" a possible race condition
in typing ModuleDefs by making the typer always 'win'. See the assertion stack trace in SI-6429.

review by @odersky, @gkossakowski

### CODE REVIEW

**Comment by paulp** [comment]
LGTM.

And I've wondered about the basis of that updateInfo call for the LONGEST TIME.

**Comment by paulp** [comment]
This is uncontroversial; merging.

**Comment by gkossakowski** [comment]
Just for reference: it's uncontroversial because it corresponds to https://issues.scala-lang.org/browse/SI-6429 which has been marked critical because it affects IDE badly.

Just saying so there's no impression that some pull requests are treated differently from others.

**Comment by paulp** [comment]
Fair enough, thank you.

**Pull request merged**
