### PR TITLE
11191 Attempt at optimizing exhaustivity 

### PR DESCRIPTION
**Pull request by psilospore**
https://github.com/scala/bug/issues/11191 
I know there was hesitance at doing this in the linked issue but I was interested in attempting it anyway and if we don't like this then I would have at least got to learn something.

Edit: I'm looking for guidance before I proceed.

## Summary

So in summary this is what I understand from the conversation:
* We can optimize for Boolean and sealed sum types safely.
* Optimizing for other cases could cause an NPE but we could make it opt-in with an annotation.
* Optimization should produce something equivalent to `case _ => ...` for the last case.

Here's my attempt. I believe I was able to optimize the Boolean case so far and I have other WIP stuff as well.

In my test I have:
```
  def optimizeDefault(b: Boolean): Int = b match {
        case true  => 10
        case false => 11
      }
```

That should ideally produce something identical to:
```
  def optimizeDefault(b: Boolean): Int = b match {
        case true  => 10
        case _ => 11
      }
```

`MatchOptimization.optimizeCases` was provided as a hint in the linked issue. So I thought all I would have to do is create the same output as `case _ => ` for an exhaustive pattern match.

However with my changes running my test with `-Vprint:patmat -Vprint-types -d` still produces a `case[number](){...throw new MatchError{MatchError}...}` although it seems to not call that method.

Without my change the test would generate this:
```
-        matchEnd5{(x: Int)Int}(11{Int(11)}){Int} 
+        if (false{Boolean(false)}.=={(x: Boolean)Boolean}(x1{Boolean}){Boolean})
+          matchEnd5{(x: Int)Int}(11{Int(11)}){Int}
+        else
+          case8{()Int}(){Int}{Int} //This is not called anymore so case8() is dead code and would be eliminated?
...
      case8(){
        matchEnd5{(x: Int)Int}(throw new MatchError{MatchError}{(obj: Any)MatchError}(x1{Boolean}){MatchError}{Nothing}){Int}
      }{Int};
```

Ideally it should generate the same output for `case _ => 11` and `case false => 11` if I'm right but if the method isn't called and I'm right that it would be eliminated later than that seems like that would effectively make it the same.

## TODOs

- Make annotation work
- Verify if the usage of the annotation should 
- Should I match the output of `case _ =>` or is this good enough?
- Sealed sum types should be optimized without annotation by default as well
- Should I be concerned with performance of `MatchAnalyzer.exhaustive`? Although it would only be called if it's one of the three conditions (Boolean, sealed sum type, and annotation).

### CODE REVIEW

**Comment by dwijnand** [comment]
> * Sealed sum types should be optimized without annotation by default as well

I think this is teetering towards a SIP-level change (just my opinion): what does it mean to add a variant to a sealed sum type?

Currently, it means it's "just" a runtime failure (MatchError), which is bad, but not as bad as erroneously running the wrong code branch.

I see the following spectrum of decisions:
1. go for it, adding to a sealed sum type, under separate compilation, can mean running the wrong code - caveat emptor
2. add a definition-side annotation, for algebraic sum types that won't change (e.g. `@closed sealed trait Option[+A]`)
3. add a use-site annotation, for hot code that could use the optimisation ( e.g. `(either: @exhaustive) match { case Left(..) => ..; case Right(..) => ..; }`)
4. don't do anything for sealed sum types, just do it for `Boolean`

Also: what are we doing with `null`?  (I'm not sure what the current status quo is.)

**Comment by szeiger** [comment]
You could make it an optimizer feature for sealed ADTs: Remove the check for the final case only if inlining from the definition site of the ADT is enabled.

**Comment by psilospore** [comment]
Hey anyone following this,
It seems like I won't have time to follow up on this in the near future. I spoke to @dwijnand on gitter and we thought to externalize a summary of our conversation.

* This might be a SIP level change. Not sure what that takes but I would be willing to look into that if it's required.
* We should go with 3 and 4 mentioned earlier. That is optimize for booleans by default, and a use site annotation e.g. `(either: @exhaustive) match { case Left(..) => ..; case Right(..) => ..; }`
* The proposed solution might not get accepted because it may not be worth the compiler complexity
* I wasn't sure about 2 

If we don't require a use-site annotation and optimize for example an Option we could run into this case:
Before:
```
(null: Option[Int]) match {case Some(3) => "hi" case None => "bye"}
scala.MatchError: null
  ammonite.$sess.cmd0$.<clinit>(cmd0.sc:1)
```
might instead do something like:
```
 (null: Option[Int]) match {case Some(3) => "hi" case _ => "bye"}
res1: String = "bye”
```

A use-site annotation communicates that I accept the risks.

lmk if I should just close this

**Comment by dwijnand** [comment]
> It seems like I won't have time to follow up on this in the near future.

Thanks for leaving a nice summary.  I'm going to close this, just to drop it from the queue.  But it's not deleted or rejected - it can be re-opened or re-submitted at a later date.

**Pull request closed without merging**
