### PR TITLE
small code improvement in build definition

### PR DESCRIPTION
**Pull request by aashish2054**

### CODE REVIEW

**Comment by SethTisue** [comment]
Can we be sure that the call to `.getCanonicalPath` wasn't necessary?

**Comment by SethTisue** [comment]
As in, do we have any idea what someone _thought_ they were doing, there, even if we suspect they were wrong?

**Comment by som-snytt** [comment]
I wasn't aware of this whole dotty incursion. Original version:
```
      object DottyLibrarySourceFilter extends FileFilter {
        def accept(file: File): Boolean = {
          val name = file.name
          val path = file.getCanonicalPath
          file.isFile &&
          (path.endsWith(".scala") || path.endsWith(".java")) &&
          !file.getCanonicalPath.contains("src-non-bootstrapped") &&
          // Copies of files already present in the scala-library present until
          // Dotty switches to 2.13.
          !path.endsWith("scala/runtime/ModuleSerializationProxy.java") &&
          !path.endsWith("scala/ValueOf.scala") &&
          // Corresponding files have been copied in this repo
          !path.contains("scalaShadowing")
        }
      }
```
The comment on the subsequent edit 3 yrs ago: "Additionally, I also removed the other exclusions done to files in
dotty-library because they're no longer necessary." I don't actually follow any of the details.

**Comment by SethTisue** [comment]
good detective work. looks like in the original code `path` was there primarily to support tests like `path.endsWith("scala/runtime/ModuleSerializationProxy.java")`, but then happened to get used in tests where `file` would have served equally well. so that seems to indicate we should accept this change

**Comment by som-snytt** [comment]
```
src/partest/scala/tools/partest/package.scala:    def isScala       = f.isFile && (sf hasExtension "scala")
src/compiler/scala/tools/nsc/classpath/FileUtils.scala:    def isScalaOrJavaSource: Boolean = !file.isDirectory && (file.hasExtension("scala") || file.hasExtension("java"))
```
utils we need in a core toolkit available to the build.

Also note, "an extension named `hasExtension`".

Would you expect `hasExtension` to be case-sensitive? When does it matter? It is case-insensitive in these utilities.

Oh wait, Seth's question was how do you know the weird `getCanonicalPath` wasn't necessary? Does that lowercase on Windows or something edge case like that?

Offhand, I don't know how to exercise this change on Windows.

**Comment by som-snytt** [comment]
The Javadoc only says:

> The precise definition of canonical form is system-dependent.
>
> ... converting drive letters to a standard case (on Microsoft Windows platforms).

**Review by SethTisue — APPROVED** [review]
I'm going to make an executive decision here and approve it, and if it breaks on Windows someday, so be it. At present I think the whole `DottySupport` thing only runs on Travis-CI anyway, and thus only on Linux. 🤷

@aashish2054 Although we appreciate the PR, note that we don't generally encourage these sorts of individual spot cleanups — unless you're also doing other work on the code in question, or unless the code flaw in question seems actively problematic (as opposed to merely non-optimal). At some point, the effort that goes into reviewing the change exceeds the value.

**Comment by som-snytt** [comment]
Besides "nothing is as trivial as it seems," the other constructive feedback is, "Please supply a meaningful commit message."

**Pull request merged**
