### PR TITLE
Microoptimization in implicit search

### PR DESCRIPTION
**Pull request by retronym**
Avoid creating a throwaway list of parameter types.

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
BTW, I am ramming my head against the performance brick wall: https://github.com/retronym/scala/compare/topic;opt2?expand=1.

**Comment by JamesIry** [comment]
LGTM except for the misspelling of microoptimization in the commit comment :)

**Comment by gkossakowski** [comment]
LGTM as well.

I'll leave it up to @retronym's mood whether he wants to apply a microfix to his commit message :)

**Comment by gkossakowski** [comment]
@retronym: cool! It'd be great to diminish implicit search contribution to overall compile time even more than it is now so we can move to other things. If only cleaner profiles come out of your work that's already a big improvement. If we can't see where the time is spent for real we are unlikely to fix bigger performance problems.

**Pull request merged**
