### PR TITLE
Improves name-based patmat.

### PR DESCRIPTION
**Pull request by paulp**
Some internal documentation and logic separation, and fixing the
specific-to-name-based-patmat bugs I know about.

Over to you, @adriaanm.

### CODE REVIEW

**Comment by adriaanm** [comment]
Roger, @phillips.

**Comment by adriaanm** [comment]
I'll be busy preparing a talk about macros or something, so I'll look at this on Wednesday.

**Comment by som-snytt** [comment]
Everyone is really looking forward to a talk on something 3.0.

**Comment by adriaanm** [comment]
Mine is very much 2,0 alpha (I miss the comma)

**Comment by retronym** [comment]
> and fixing the specific-to-name-based-patmat bugs I know about.

See also SI-8045, a regression in regular extractors. I started on a patch, working backwards from `typesOfSelectorsOrSelf`, but it was slow going without having written that code.

**Comment by paulp** [comment]
@retronym SI-8045 fixed by this PR already. I added a test case.

**Comment by paulp** [comment]
@adriaanm That's Wednesday on the New Galactic Calendar then?

**Comment by adriaanm** [comment]
Wednesdays.nextRandom -- when you least expect it.

**Comment by paulp** [comment]
"When I least expect it" is "anytime soon", so if I can expect it when I least expect it that's perfect.

**Comment by adriaanm** [comment]
I knew I shouldn't have gotten myself into a gamble with you. I'm being a lazy slacker for a couple of days, but I'll shepherd this in.

**Comment by xeno-by** [comment]
Could you also take a look at https://github.com/scala/scala/pull/3235?
Would be nice to enter the new year with a hackless paradise build :)

**Comment by adriaanm** [comment]
I'll do my best. Supposed to be on one of those "vacay-shuns".

**Comment by retronym** [comment]
The following are now dead code: `definitions.{elementTypeOfLastSelectorOrSelf, typeOfLastSelectorOrSelf, typesOfSelectorsOrSelf}`. Maybe more?

**Comment by paulp** [comment]
Also typeOfMemberNamedGetOrSelf and typesOfCaseAccessors. Some sentency names there.

**Comment by retronym** [comment]
I'm expanding the test cases for this one.

**Comment by retronym** [comment]
WIP: https://github.com/retronym/scala/tree/topic/pr-3275-review

**Comment by retronym** [comment]
I don't consider the issues I've found so far to be blockers and the needn't hold up this PR from M8.

**Comment by retronym** [comment]
I've noted the residual issues in https://issues.scala-lang.org/browse/SI-8127. I'll probably have to defer that to 2.11.1.

Otherwise:

LGTM

One blocker left in the normal pattern matcher as a consequence of the name based patmat is: https://issues.scala-lang.org/browse/SI-8128.

**Comment by retronym** [comment]
I've just issued a one-commit PR against this PR to fix the existential regression in the specific case of 2.10-style extractors: https://github.com/paulp/scala/pull/13

@adriaanm  I think this should be included in M8.

**Comment by paulp** [comment]
No thanks on the test failure.

**Comment by retronym** [comment]
@dotta That's your recently merged test:

```
% diff /localhome/jenkins/c/workspace/pr-scala-test/scala/test/files/presentation/context-bounds1-presentation.log /localhome/jenkins/c/workspace/pr-scala-test/scala/test/files/presentation/context-bounds1.check
@@ -40,7 +40,10 @@ askHyperlinkPos for `A` at (5,25) ContextBounds.scala
 [response] found askHyperlinkPos for `A` at (4,12) ContextBounds.scala
 ================================================================================

-No symbol is associated with tree: implicitly[Foo[A]].foo
+askHyperlinkPos for `foo` at (5,36) ContextBounds.scala
+================================================================================
+[response] found askHyperlinkPos for `foo` at (10,7) ContextBounds.scala
+================================================================================

 askHyperlinkPos for `A` at (10,14) ContextBounds.scala
 ================================================================================
```

Could you please take a look tomorrow, and move the test to `pending` if things aren't clear?

**Comment by adriaanm** [comment]
Yep, this is definitely M8 material.

**Comment by paulp** [comment]
Jenkins went all green again in a subsequent commit.

**Comment by dotta** [comment]
@retronym That test was introduced with the intent of preventing a regression ([here is the commit](https://github.com/dotta/scala/commit/ccacb06c4928fd6aebc2c2539d7565cb079dc625)). It's unfortunate that it actually exposes a real bug. I'd like to know why do we get `No symbol is associated with tree: implicitly[Foo[A]].foo`, but my knowledge of Typers is weak, and I don't have an educated guess to offer - maybe you guys can help with this \cc @dragos. I'm going to move that test under pending and open a ticket.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@9dae742

**Comment by retronym** [comment]
PLS SYNCH

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@9dae742

**Comment by paulp** [comment]
@adriaanm @retronym Now that I idiotically wasted an hour I didn't have opening a ticket for a bug fixed in this PR, can someone please merge this?

**Comment by adriaanm** [comment]
I'm very sorry about the delay. We're working through the backlog and will get this into M8.  I don't believe the criteria for merging require the submitter to waste an hour on something, though. Or, wait, I meant s/requirement/sufficient condition/.

**Comment by paulp** [comment]
s/requirement/sufficient condition/ is a no-op.

**Comment by adriaanm** [comment]
I usually interpret them as different sides of the double implication arrow.

**Comment by adriaanm** [comment]
LGTM

I relished the beauty of each commit and have nothing to add to Jason's LGTM -- except my own.

**Pull request merged**
