### PR TITLE
Fix bug where `-Vtype-diffs` sometimes lost error type information

### PR DESCRIPTION
**Pull request by tribbloid**
Fix for scala/bug#12561

### CODE REVIEW

**Comment by SethTisue** [comment]
settings on CI are stricter than local defaults; you can `set Global / fatalWarnings := true` from the sbt prompt to get the same errors locally

**Comment by tribbloid** [comment]
Sorry it was a copy-paste typo (`def` twice), strangely IDE didn't correct me immediately

**Comment by tribbloid** [comment]
now it is working, not a draft anymore

**Comment by tribbloid** [comment]
Sorry @SethTisue now all checks have passed, can it be integrated?

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
thank you @tribbloid !

**Pull request merged**
