### PR TITLE
Emit mixin forwarders as bridges to avoid needing generic signatures

### LINKED ISSUE #8905: Methods inherited from generic traits sometimes have types erased to Object
It seems that methods inherited from generic traits sometimes have their types erased to Object, which causes compilation or runtime errors when calling these methods from Java.  This seems like it it might be related to #3452.

Here's a simple reproduction ([also available as a gist](https://gist.github.com/JoshRosen/4e833694961e06c16263) with a build.sbt, in case you want to clone it to quickly test this out):

In Scala:
```scala
import java.util.Comparator

trait RDDLike[T] {
  def max(comp: Comparator[T]): T = {
    (1.0).asInstanceOf[T]
  }
}

class DoubleRDD extends RDDLike[java.lang.Double] { }
```

In Java:
```scala
import java.util.Comparator;

public class Test {
  private static class DoubleComparator implements Comparator<Double> {
    public int compare(Double o1, Double o2) {
      return o1.compareTo(o2);
    }
  }

  public static void main(String[] args) {
    DoubleRDD rdd = new DoubleRDD();
    RDDLike<Double> rddLike = rdd;

    // This call works fine:
    double rddLikeMax = rddLike.max(new DoubleComparator());
    // In Scala 2.10.4, this code compiles but this call fails at runtime:
    // java.lang.NoSuchMethodError: DoubleRDD.max(Ljava/util/Comparator;)Ljava/lang/Double;
    double rddMax = rdd.max(new DoubleComparator());
  }

}
```

In Scala 2.10.4, this code compiles fine but throws a NoSuchMethodError at runtime when I call the `max` method via the `DoubleRDD` class.  In all versions of Scala 2.11 that I've tested, the Java code fails to compile:

```scala
error: incompatible types
[error]     double rddMax = rdd.max(new DoubleComparator());
[error]                            ^
[error]   required: double
[error]   found:    Object
[error] 1 error
```

Based on `javap`, it seems that Scala 2.10.4 emits the right signature for DoubleRDD.max:

```scala
javap -s target/scala-2.10/classes/DoubleRDD.class
Compiled from "RDD.scala"
public class DoubleRDD implements RDDLike<java.lang.Double> {
  public java.lang.Double max(java.util.Comparator<java.lang.Double>);
    Signature: (Ljava/util/Comparator;)Ljava/lang/Object;

  public DoubleRDD();
    Signature: ()V
}
```

Scala 2.11.2 seems to erase to Object:

```scala
javap -s target/scala-2.11/classes/DoubleRDD.class
Compiled from "RDD.scala"
public class DoubleRDD implements RDDLike<java.lang.Double> {
  public java.lang.Object max(java.util.Comparator);
    Signature: (Ljava/util/Comparator;)Ljava/lang/Object;

  public DoubleRDD();
    Signature: ()V
}
```

However, if I override the implementation of the `max` method in my class, then everything works fine.  This compiles and runs as expected:

```scala
class DoubleRDD extends RDDLike[java.lang.Double] {
  override def max(comp: Comparator[java.lang.Double]): java.lang.Double = {
    (1.0).asInstanceOf[java.lang.Double]
  }
}
```

Surprisingly, though, the generated bytecode now contains *two* `max` methods:

```scala
javap -s target/scala-2.10/classes/DoubleRDD.class
Compiled from "RDD.scala"
public class DoubleRDD implements RDDLike<java.lang.Double> {
  public java.lang.Double max(java.util.Comparator<java.lang.Double>);
    Signature: (Ljava/util/Comparator;)Ljava/lang/Double;

  public java.lang.Object max(java.util.Comparator);
    Signature: (Ljava/util/Comparator;)Ljava/lang/Object;

  public DoubleRDD();
    Signature: ()V
}
```

This happens in both 2.10.4 and 2.11.2.

### PR DESCRIPTION
**Pull request by smarter**
[edit] reverted in https://github.com/scala/scala/pull/8037

The compiler spends a lot of effort trying to generate correct generic
signatures for mixin forwarders, but is still not correct as witnessed
by scala/bug#8905 among others. However, it seems that if we just emit
them with the BRIDGE flag set, both javac and ecj (the Eclipse Java
Compiler) will be smart enough to go look for the signature in the
overridden methods, which is exactly what we want.

~~This means that we should be able to get rid of `cloneBeforeErasure` and
related code, though that would conflict with #7752.~~ EDIT: That's not actually a problem, see https://github.com/scala/scala/pull/7843#issuecomment-471621656

Because history always repeats itself, it turns out that this used to be
how mixin forwarders were emitted until
fe94bc7a144921f6c3dcbedbedd2c5c884a77bbd changed this 7 years ago. The
commit only says that this "has deleterious effects since many tools
ignore bridge methods" which is too vague for me to do anything about.

Fixes scala/bug#8905 and probably countless others.

### CODE REVIEW

**Comment by smarter** [comment]
Looks like the travis CI is broken /cc @SethTisue:
> [warn] 	[FAILED     ] org.scala-lang.scala-sha-bootstrap.test.files.lib#methvsfield;be8454d5e7751b063ade201c225dcedefd252775!methvsfield.jar: The HTTP response code for https://repo.lightbend.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/be8454d5e7751b063ade201c225dcedefd252775/test/files/lib/methvsfield.jar did not indicate a success. See log for more detail. (2117ms)

**Comment by smarter** [comment]
I've added a second commit that removes `cloneBeforeErasure` and the tests still pass as expected. However, I also tried turning off the bridge flag and it looks like the t8905 test I added is the only one directly testing that javac gets the correct signature, so the lack of good test coverage makes it difficult to evaluate this PR, hopefully the community build will help ?
Another problem is that if we get the second commit in, then https://github.com/scala/scala/pull/7752 can no longer go in, thus making @sjrd very sad :). I think for his usecase what's really needed is a way to go from the forwarder symbol to the original symbol, perhaps this could be done by adding an annotation on the forwarder?

**Comment by lrytz** [comment]
I like it :-) One area to look for issues this may cause is overloading. See https://github.com/scala/bug/issues/11271 where adding the `bridge` flag to static forwarder methods generated in companion classes of top-level modules caused problems.

**Comment by lrytz** [comment]
I'd like to add that we're in unspecified territory here, as far as I can tell. The jvm spec just says "The `ACC_BRIDGE` flag is used to indicate a bridge method generated by a compiler for the Java programming language". In the language spec I only found "Implementations can enforce these semantics by creating bridge methods".

So it's not really clear which methods can be marked bridge, and how different tools react to that. So we'd have to test a lot.

**Comment by smarter** [comment]
> See scala/bug#11271 where adding the bridge flag to static forwarder methods generated in companion classes of top-level modules caused problems.

I did see that issue but was a bit confused by the back-and-forth, tell me if my understanding of things is wrong here:

1. scalac was emitting methods that javac considered ambiguous
2. Emitting these methods as BRIDGE fixed the issue for javac
3. ... but it didn't fix them for ejc and the intellij java compiler
4. So you ended up completely removing these methods

So my question is: were the methods considered ambiguous by ejc and intellij when they were emitted without the BRIDGE flag ? If so, then adding the BRIDGE flag somewhere shouldn't break these compilers.

**Comment by lrytz** [comment]
The methods only became ambiguous in ejc/IntelliJ once we added the flag. In the case of static forwarders, the end goal was to remove bridge versions anyway, we just didn't do it initially in 2.12 because it's (potentially) binary incompatible. But due to the overloading issues, we finally back-ported the change from 2.13 which removes the bridge overloads. The story is also summarized here: https://github.com/scala/scala/pull/7469.

For mixin methods this cannot be done obviously, we need the mixin methods.

**Comment by smarter** [comment]
My guess is that things started to go wrong because you were emitting bridge methods that don't override anything which javac would never do, mixin forwarders by definition override something, and moreover they forward to at least one of the method they override, so that seems closer to being correct.

**Comment by lrytz** [comment]
That's a promising guess.

Another data point is what javac produces. Example:
```java
public class A {
  public static abstract class U<T> {
    public abstract <P> T foo(P p);
  }
  public static class V extends U<String> {
    public <P> String foo(P p) { return ""; }
  }
}
```

We get (ASM syntax):

```
// access flags 0x421
// signature <T:Ljava/lang/Object;>Ljava/lang/Object;
// declaration: A$U<T>
public abstract class A$U {

  // access flags 0x401
  // signature <P:Ljava/lang/Object;>(TP;)TT;
  // declaration: T foo<P>(P)
  public abstract foo(Ljava/lang/Object;)Ljava/lang/Object;
}
```

```
// access flags 0x21
// signature LA$U<Ljava/lang/String;>;
// declaration: A$V extends A$U<java.lang.String>
public class A$V extends A$U  {

  // access flags 0x1
  // signature <P:Ljava/lang/Object;>(TP;)Ljava/lang/String;
  // declaration: java.lang.String foo<P>(P)
  public foo(Ljava/lang/Object;)Ljava/lang/String;

  // access flags 0x1041
  public synthetic bridge foo(Ljava/lang/Object;)Ljava/lang/Object;
}
```

So the bridge also doesn't have a signature.

**Comment by smarter** [comment]
I've pushed an extra commit to exercise overload resolution, and not only do things appear to still work correctly, the test now passes on ecj whereas it considers the overload ambiguous on master!

As an aside, I think It'd be really useful and not much work to run all the tests involving .java files with both javac and ecj.

**Comment by smarter** [comment]
More good news: I was able to take a few existing test cases and verify that javac and ecj now see better types for them, see latest commit (static forwarders are still screwed up, but I think this really ought to be solved by generating them pre-erasure as has been suggested a few times in the past).

**Comment by sjrd** [comment]
Besides conflicting with #7752, this PR already breaks Scala.js: `@Test` methods in traits are not recognized anymore, because their bridges are ignored by Scala.js, due to
https://github.com/scala-js/scala-js/blame/f524bbeff87e888c21a3d7cc1a9e75ea669bc4ce/junit-plugin/src/main/scala/org/scalajs/junit/plugin/ScalaJSJUnitPlugin.scala#L263
which was introduced to fix another issue, the latter was caused by scalac starting to copy annotations to mixin forwarders.

**Comment by smarter** [comment]
@sjrd So I just checked and JUnit will run test methods with the BRIDGE flag set, so I'd say Scala.js is the one doing something weird here, do you have a test case that demonstrates the issue that lead you to implement this check ?

**Comment by sjrd** [comment]
> do you have a test case that demonstrates the issue that lead you to implement this check ?

Yes, pretty much every test. Without that check, the test suite cannot be compiled without crashing the compiler using Scala >= 2.12.5.

**Comment by sjrd** [comment]
Well ... "retournement de situation", as we say in French: it turns out this PR *also* fixes https://github.com/scala-js/scala-js/issues/3538, which was the issue that #7752 was meant to fix on Scala.js' side. So this PR does not conflict with #7752 as much as superseding it.

And for the issue with `@Test` methods which I mentioned earlier, it only happens for one shady test method in our test suite whose signature is
```scala
@Test def toString()(): Unit = ...
```
which somehow gets a bridge generated for it. (Yes, the double `()()` is in the code.)

So I'll :+1: this PR.

**Comment by smarter** [comment]
@SethTisue Could you run the community build on this PR ? If possible it would also be interesting to run it on https://github.com/scala/scala/commit/46cda53 which is this PR + don't emit the bridge flag for mixin forwarders, to see if this actually influences the community build at all.

EDIT: Started a community build for this PR: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1843/console
And one to check the coverage: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1845/console

**Comment by retronym** [comment]
> The commit only says that this "has deleterious effects since many tools
ignore bridge methods" which is too vague for me to do anything about.

[Spring Framework](https://github.com/spring-projects/spring-framework/blob/e3a9826e56e8fcb9e57f31b255998a095d8f8155/spring-core/src/main/java/org/springframework/core/type/StandardAnnotationMetadata.java#L145) skips `ACC_BRIDGE` methods when reflectively compiling a list of annotated methods.

Here's analagous logic [in Hibernate](https://github.com/search?q=org%3Ahibernate+isBridge&type=Code).

Graal seems to [assume certain bytecode shapes](https://github.com/oracle/graal/blob/5cf484ee9f75ae5560b4a0583c6bd659876ed4d7/compiler/src/org.graalvm.compiler.bytecode/src/org/graalvm/compiler/bytecode/BridgeMethodUtils.java#L49-L102) within bridge methods (must delegage to a method with the same name). I don't know the context of this.

**Comment by smarter** [comment]
> Spring Framework skips ACC_BRIDGE methods when reflectively compiling a list of annotated methods.

It looks like things are more complicated than that, I found https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/BridgeMethodResolver.java which in particular lead me to the notion of "visibility bridge method" described in http://stas-blogspot.blogspot.com/2010/03/java-bridge-methods-explained.html which is very interesting since it describes a case where **javac emits a bridge from a subclass to a superclass!**, and the way Spring checks for that should cover the bridges in this PR too. 

So arguably, any annotation framework that doesn't handle this is broken for Java too, but since it's a fairly rare thing, to be conservative we could choose to treat mixin methods with runtime-visible annotations specially:
- If they don't need a forwarder for semantics, just don't emit one (since we would only be emitting it for cold performance reasons, which you probably don't care about if you're using an annotation-heavy Java framework)
- If they do need a forwarder for semantics, either output an error, or emit the method without the bridge flag (so the generic signature will be missing, but that's not worse than the status-quo where some of the mixin forwarders we generate also have missing generic signatures).

**Comment by smarter** [comment]
The [community build run](https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1843/console) looks OK to me given that the "unexpected failures" match the failures in a [recent commit from master](https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1842/consoleFull).

**Comment by lrytz** [comment]
I think this looks very good. Let's keep it open for a bit more to see if someone finds other ways to break it.

**Comment by retronym** [comment]
@axel22 @vjovanov Do you have any insight into how the [code in found in Graal](https://github.com/scala/scala/pull/7843#issuecomment-471851411) might behave if we start to use `ACC_BRIDGE` on things that don't quite look like `javac` generated bridges?

**Review by lrytz — APPROVED** [review]

**Comment by smarter** [comment]
@lrytz @retronym What about the special case for methods with runtime-visible annotations I suggested in https://github.com/scala/scala/pull/7843#issuecomment-471879538 ? Emitting less forwarders would be binary incompatible so there's not much time left to experiment with that.

**Comment by lrytz** [comment]
I'd keep it as it is now and see if we can avoid special cases like this..

**Comment by smarter** [comment]
OK. I guess there's always the option of keeping these forwarders for binary-compatibility but dropping the BRIDGE flag for them.

**Comment by vjovanov** [comment]
The code in Graal is used mostly for things in our core which are all in Java and was written for the bytecode that is emitted by Eclipse and `javac`. We can easily change this to support the new pattern as well.

For this particular case, I think it is more time-efficient to fix this issue if someone encounters it by using Scala for core Graal things. 

@retronym thanks for letting us know about the change.

**Pull request merged**
