### PR TITLE
Revert "Generate shallower ASTs in pattern translation"

### PR DESCRIPTION
**Pull request by retronym**
This reverts commit fcd99c5228588df6f6f9e5ddf3f5cdbfb9281d10.

While the shallowers ASTs are better for limiting stack usage of
scalac in post-patmat phases, the subtle change this made to the
bytecode control flow leads to drastically slower analysis of large
patterns by ASM. We use this analysis to generate the stackmap
frames during code generation and during optimization.

Perhaps a better way forward would be to explicitly generate
the stackmap frames during code generation, which AFAIK is not
computationally expensive while when we still have the AST in hand.

The challenge would be to use this as a basis for ASM to incrementally
add missing stack map frames for code that is transformed by our
optimizer phases.

`MethodWriter` has a mode that sounds promising:

```
  /**
   * Indicates that the stack map frames of type F_INSERT must be computed. The other frames are not
   * computed. They should all be of type F_NEW and should be sufficient to compute the content of
   * the F_INSERT frames, together with the bytecode instructions between a F_NEW and a F_INSERT
   * frame - and without any knowledge of the type hierarchy (by definition of F_INSERT).
   */
  static final int COMPUTE_INSERTED_FRAMES = 3;
```

https://gitlab.ow2.org/asm/asm/blob/ASM_7_1/asm/src/main/java/org/objectweb/asm/MethodWriter.java#L58-64

Fixes scala/bug#11667

### CODE REVIEW

**Comment by lrytz** [comment]
> The other frames [...] should all be of type `F_NEW`

and the docs on `F_INSERT`

> This kind of frame is only used when an unconditional jump is inserted in a method while expanding an ASM specific instruction

sounds maybe a bit too narrow for what we'd need after the inliner / optimizer's changes..

**Comment by lrytz** [comment]
Looking at the generated bytecode, I realized that 

```
        if (o14.isEmpty)
          case12();
```

is emitted as `ifeq; goto`. changing that to `ifne` reduces the number of generated branches and fixes https://github.com/scala/bug/issues/11667.

Here's a wippy wip: https://github.com/scala/scala/compare/2.12.x...lrytz:patmat-simpler-jumps?expand=1

Maybe the problem persists if parameters are passed to the label apply. @retronym wdyt?

**Comment by retronym** [comment]
Sounds a good way to have our 🎂 and eat it too. I’ll give the question of
label args some more thought tomorrow.

**Comment by retronym** [comment]
The label apply params are only used for the result expression of the match, so there is only one such `Apply` per `case`. Performance of the reproduction in the bug seems fine with your patch as is.

**Comment by retronym** [comment]
@lrytz What course of action do you think we should take for 2.12.10? I'd vote to use your patch, but we alternatively do that work on 2.13.x and just revert the change here.

**Comment by retronym** [comment]
On second thoughts, I think the best course of action is to just merge this reversion. 

That will fix the last 2.12.9 regression I'm aware of, so we can already encourage some testing of nightlies ahead of 2.12.10.

We can then revert the reversion and apply https://github.com/scala/scala/compare/2.12.x...lrytz:patmat-simpler-jumps?expand=1 as a second step (without rushing). That could happen on 2.12.x or 2.13.x as we see fit.

**Comment by SethTisue** [comment]
I vote for being cautious here and proceeding with this only on 2.13.x

**Pull request merged**
