### PR TITLE
Damage control related to AnyRef specialization

### PR DESCRIPTION
**Pull request by retronym**
- Remove its use from `AbstractPartialFunction`
- Reject `Name`-s with negative length or offset.
- Harden and test `unspecializedName` / `splitSpecializedName`

I stop short of removing this facility altogether. When we do, we should remember to touch the group `Specialized.All`.

Review by @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@5aa8091

PLS REBUILD/pr-scala@81e4db1

**Comment by retronym** [comment]
Oh, I'll bet the breakages:

```
Caused by: java.lang.NoClassDefFoundError: org/scalacheck/util/CmdLineParser$$anonfun$1
    at org.scalacheck.util.CmdLineParser$class.$init$(CmdLineParser.scala:68)
    at org.scalacheck.Test$$anon$1.<init>(Test.scala:206)
    at org.scalacheck.Test$.cmdLineParser$lzycompute(Test.scala:206)
    at org.scalacheck.Test$.cmdLineParser(Test.scala:206)
    at org.scalacheck.ScalaCheckFramework$$anon$1.run(ScalaCheckFramework.scala:70)
```

Are a binary incompatibilty of some sort by removing `AnyRef` specialization from from `AbstractPartialFunction`. Ouch.

**Comment by retronym** [comment]
But I don't see it locally:

```
qbin/scala -classpath /Users/jason/code/scala/test/files/lib/scalacheck.jar
Welcome to Scala version 2.11.0-20130916-124550-81e4db1409 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_37).
Type in expressions to have them evaluated.
Type :help for more information.

scala> Class.forName("org.scalacheck.util.CmdLineParser$$anonfun$1")
res0: Class[_] = class org.scalacheck.util.CmdLineParser$$anonfun$1

scala> res0.getSuperclass
warning: there were 1 feature warning(s); re-run with -feature for details
res2: Class[?0] forSome { type ?0 >: ?0; type ?0 } = class scala.runtime.AbstractPartialFunction$mcIL$sp
```

**Comment by retronym** [comment]
I could reproduce locally after a clean build, which removed the classfiles for `AnyRef` specialized variants.

I've amended this PR to manually include a few specialized subclasses that are needed by Scalacheck.

**Comment by gkossakowski** [comment]
LGTM.

Great work and great test! Unit testing FTW! :rainbow:

**Pull request merged**
