### PR TITLE
SI-6559 Fix raw string interpolator: string parts which were after the first argument were still escaped

### PR DESCRIPTION
**Pull request by retronym**
Review by @jsuereth

Only touches new code.

Backport from master.

### CODE REVIEW

**Comment by jsuereth** [comment]
Why not back port the fix from 2.10.x or do we want merge conflicts?

**Comment by jsuereth** [comment]
Oh, otherwise  lgtm

**Comment by jsuereth** [comment]
Sorry, forgot to mention, this fix is already in 2.10.x _with different tests_ oddly enough.  

In any case, this LGTM but we may want to look at the diff between master/branches.

**Comment by retronym** [comment]
I've merged the extra tests, too.

**Comment by jsuereth** [comment]
Nice!  Lgtm.

PLS REBUILD ALL

**Comment by retronym** [comment]
PLS REBUILD ALL

**Pull request merged**
