### PR TITLE
SI-8336: add `fold` & `toEither` to `util.Try`

### PR DESCRIPTION
**Pull request by adriaanm**
Rebase, slight reword of #4082, originally by @cchantep.

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM by @Ichoran at original PR.

**Comment by Ichoran** [comment]
LGTM here too.

**Comment by cchantep** [comment]
Thanks guys

**Comment by adriaanm** [comment]
:fireworks: Thanks for your contribution & patience, @cchantep!

**Comment by cchantep** [comment]
Thanks guys

**Pull request merged**
