### PR TITLE
SI-7492 Remove -Ystruct-dispatch and associated code

### PR DESCRIPTION
**Pull request by soc**
This means that the private option is gone as well as the untested
code for no-cache and mono-cache and the non-working code for
invoke-dynamic.

poly-cache is now always used. For the future it probably makes more
sense to let the backend decide how it wants to treat structural
dispatch instead of allowing the user to “mix and match” backends
with structural dispatch implementations.

### CODE REVIEW

**Comment by soc** [comment]
Review by @adriaanm, @retronym or @gkossakowski, please.

It looks as if the fixing of indentation caused GitHub's diff tool to turn the simple change into a huge mess. Let me know if I should separate the removal and the indentation fix.

**Comment by paulp** [comment]
LGTM.

**Comment by retronym** [comment]
In general, its a good idea to break up the commits: remove the code, reformat, change to string interpolation. They are easier to review, and its easier to revert selectively.

But you can have a free pass on for a Friday night, LGTM too.

**Comment by soc** [comment]
I'll change it. Every future me would be happy about it.

**Comment by adriaanm** [comment]
LGTM Pass granted. I'll merge now since the M3 window is closing.

**Pull request merged**
