### PR TITLE
SI-6844  SI-8076 improve handling of function parameters in quasiquotes

### PR DESCRIPTION
**Pull request by densh**
Fixes two bugs related to handling of function parameters:
- [SI-6844](https://issues.scala-lang.org/browse/SI-6844) restrict splicing in parameter position
- [SI-8076](https://issues.scala-lang.org/browse/SI-8076) improve support for implicit argument list

Best viewed per commit. 

review @retronym

### CODE REVIEW

**Comment by densh** [comment]
ping @retronym

**Comment by retronym** [comment]
I'll take a look at this on Friday. Sorry about the delay.

**Comment by retronym** [comment]
LGTM

**Comment by som-snytt** [comment]
> What does unapplied away mean?

I'll take an "unapplied away" t-shirt in black, medium.

**Pull request merged**
