### PR TITLE
Fix typo in Quasiquote doc that was confusing

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by xeno-by** [comment]
LGTM

**Comment by som-snytt** [comment]
LGTM

I guess "confusing" means "wrong".  API is at http://www.scala-lang.org/api/2.11.6/scala-reflect/index.html#scala.reflect.api.Quasiquotes@QuasiquoteextendsAnyRef

**Comment by som-snytt** [comment]
I might have reworded "easily"

```
With their help you can easily manipulate Scala reflection ASTs.
```

as

```
...you have some shot at successfully...
```

**Comment by jedesah** [comment]
@som-snytt I wish Github had a like button for comments! :-)

**Pull request merged**
