### PR TITLE
SI-8755 Phase Assembly is broken

### PR DESCRIPTION
**Pull request by misberner**
```
- Fixes various bugs in the phase assembly of the Scala compiler (see below and JIRA ticket)
- Plugins with empty after and rightAfter constraints are no longer ignored
- runsRightAfter no longer causes other constraints to be ignored
- constraint systems are now accepted iff they are solvable
- No more illegal modifications of objects contained in hash sets (hash code no longer dependent on field values, identity semantics sufficient)
- Realized constraint solving by well-known topological sort algorithm (due to Kahn (1962))
- Fixes #8755
- backport to 2.11.x
```

### CODE REVIEW

**Comment by retronym** [comment]
Thanks for taking a look at this bug. I'd like to see a test case included in this pull request to keep things fixed.

Here are existing test cases that exercise the compiler plugin infrastructure.

```
% find test -name 'scalac-plugin.xml'
test/files/neg/macro-incompatible-macro-engine-a/scalac-plugin.xml
test/files/neg/macro-incompatible-macro-engine-b/scalac-plugin.xml
test/files/neg/t6446-additional/scalac-plugin.xml
test/files/neg/t6446-list/scalac-plugin.xml
test/files/neg/t6446-missing/scalac-plugin.xml
test/files/neg/t7494-after-terminal/scalac-plugin.xml
test/files/neg/t7494-before-parser/scalac-plugin.xml
test/files/neg/t7494-multi-right-after/scalac-plugin.xml
test/files/neg/t7494-no-options/scalac-plugin.xml
test/files/neg/t7494-right-after-before/scalac-plugin.xml
test/files/neg/t7494-right-after-terminal/scalac-plugin.xml
test/files/neg/t7622-cyclic-dependency/scalac-plugin.xml
test/files/neg/t7622-missing-dependency/scalac-plugin.xml
test/files/neg/t7622-multi-followers/scalac-plugin.xml
test/files/run/macroPlugins-macroArgs/scalac-plugin.xml
test/files/run/macroPlugins-macroExpand/scalac-plugin.xml
test/files/run/macroPlugins-macroRuntime/scalac-plugin.xml
test/files/run/macroPlugins-typedMacroBody/scalac-plugin.xml
```

One more thing: it would be preferable to submit this directly to the 2.11.x branch. It will be then included in 2.11.3 and 2.12.0.

**Comment by som-snytt** [comment]
Ditto on thanks for taking it on.  I touched the code once and intended to get back to it.  I'll try to contribute eyeballs. And maybe tests.

In fact, maybe I broke it by not noticing the vars:

https://github.com/scala/scala/commit/508ee772ff211d290e0fadc81d8cea70595b7984

I don't remember the symptom re testability for identity hash.

**Comment by som-snytt** [comment]
To expand on the comment in the issue on fragility of parser, I remember my REPL version that had the compiler respect a "scripting" phase after parser, made the initialPhase arbitrary.

OK, I just checked out the old branch, and the key commit was "SI-7747 Phases are subject to replacement" so you could swap in your own scripter phase via a plugin.  I think there were a couple of things I needed from phase assembly, so doing it right is a good thing.

**Comment by som-snytt** [comment]
I don't remember if that test that went pos was just documenting current behavior?

Oh I see, "Tests for status quo"...  I really forgot all about it. "Some of the plugin tests make phase assembly throw."

https://github.com/som-snytt/scala/commit/4ab66d1613da276712692001ed8f9f3c009736ab

**Comment by misberner** [comment]
The test that I moved to pos should not fail, as it is an instance of where the current Phase Assembly is being too strict (see "Solvable constraint systems are rejected" in the [JIRA Ticket](https://issues.scala-lang.org/browse/SI-8755)).
What should be tested (and maybe that was intended, but not realized) is to test that a plugin which wants to run _between_ (using after and before, but not rightAfter) two phases that are linked through hard links is rejected. But this does not apply to "refchecks" and "erasure".

**Comment by som-snytt** [comment]
Yeah, that's what confused me just now.  I did check that the constraints didn't change in Global.  I don't remember what I intended or realized.

**Comment by som-snytt** [comment]
Your other problem just needed a clean build, is that right?

**Comment by misberner** [comment]
Yes. That's why I removed the comment, but I maybe should have rather edited it for clarification.

**Comment by som-snytt** [comment]
Thx, I keep forgetting that I can delete my dumb comments.  Sometimes I can't see comments on old diffs, etc, so I was just checking.  I'll delete this later...

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@misberner, did you have a chance to look into latest round of test failures?

**Comment by gkossakowski** [comment]
ping @misberner

**Comment by gkossakowski** [comment]
Closing for lack of activity. @misberner, please submit a new PR when you have a chance to work on this again. Don't forget to reference this PR so we don't lose access to previous reviews.

**Pull request closed without merging**
