### PR TITLE
Make LazyList#withFilter more lazy

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by julienrf** [comment]
I think we should fix this issue with a more general approach like in #6880.

**Review by szeiger — APPROVED** [review]
LGTM. Let's wait for @NthPortal's work on updating https://github.com/scala/scala/pull/6880 though. If we end up with a completely new `LazyList` it doesn't make sense to merge this PR because `Stream` wouldn't benefit from it.

**Comment by NthPortal** [comment]
Yeah, I think the new `LazyList` (see #7000) will not need this change, because its state is already fully lazy.

**Comment by SethTisue** [comment]
closing since it looks like #7000 is going forward

**Comment by SethTisue** [comment]
@NthPortal can you check if the test @xuwei-k added here ought to be in #7000, if it isn't already?

**Comment by NthPortal** [comment]
@SethTisue I don't think there's a test covering `withFilter`'s laziness yet.

I'd actually like to add a bunch of tests for most/all of the methods to assert complete laziness (e.g. for `filter`, `drop`, `dropWhile`, `scanLeft`, `map`, etc.). However, I don't think I can get done by tomorrow's deadline.

Are you okay with pushing the deadline for those tests (which will include/cover this) to RC1? If not, I'm happy to copy this test over, but it will probably end up abstracted out into a more general method in the end.

**Comment by SethTisue** [comment]
RC1's fine 👍

**Comment by NthPortal** [comment]
Just noting here that I have written the test case for this (though I haven't pushed/PRed it yet)

**Pull request closed without merging**
