### PR TITLE
SI-6033 Closed. Provides implicit conversion from BigInteger to BigInt

### PR DESCRIPTION
**Pull request by dgruntz**
Adds an implicit conversion from java.math.BigInteger to BigInt. This way, 
BigDecimal (which also provides such a conversion) and BigInt are consistent.

Review: ??? (who is responsible for the library (beyond collections, concurrent)?)

### CODE REVIEW

**Comment by dgruntz** [comment]
Martin agreed on [scala-language](https://groups.google.com/forum/?fromgroups#!topic/scala-language/AFUamvxu68Q) that BigInt and BigDcimal should be consistent.

**Comment by jsuereth** [comment]
@odersky is technically the one responsible if there is no other owner.

Also, this change LGTM too.

**Comment by odersky** [comment]
@phaller and @alex22 are the library czars.

On Fri, Jul 6, 2012 at 2:26 AM, Josh Suereth <
reply@reply.github.com

> wrote:
> 
> @odersky is technically the one responsible if there is no other owner.
> 
> Also, this change LGTM too.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/scala/scala/pull/831#issuecomment-6794482

## 

Martin Odersky
Prof., EPFL http://www.epfl.ch and Chairman, Typesafehttp://www.typesafe.com
PSED, 1015 Lausanne, Switzerland
Tel. EPFL: +41 21 693 6863
Tel. Typesafe: +41 21 691 4967

**Comment by dgruntz** [comment]
Thanks. Adriaan just updated the page at https://github.com/scala/scala/wiki/Pull-Request-Policy.

**Pull request merged**
