### PR TITLE
Colour REPL names and their types, in the shell (UI)

### LINKED ISSUE #11548: No colours in the REPL?
It looks to me like there are no more colours in the REPL:

image

Using `-Dscala.color=true` doesn't fix it either.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes scala/bug#11548

### CODE REVIEW

**Review by som-snytt — APPROVED** [review]

**Comment by dwijnand** [comment]
@adriaanm's traveling, so let's see if he has a spare second next week to look this over.  (2.13.2 is planned for in 2 weeks.)

I think this would be nice to have back in 2.13.2, but then I'm pretty biased here.  😄

**Comment by som-snytt** [comment]
My only gripe is that it's "color". Let's find a reviewer who can spell, note that it needn't be a speaker of American English.

I'm OK with "velour", though.

Edit: spit take, "Two weeks!"

**Comment by som-snytt** [comment]
Re: Adriaan and travel, today, I came across:
```
thanks to Tiark for helping me figure it out on a terrace in Barcelona
```

**Comment by SethTisue** [comment]
(I don't think this requires Adriaan-level approval)

> thanks to Tiark for helping me figure it out on a terrace in Barcelona

ah, Scala, the JVM's most European language. meanwhile here in 🇺🇸, “thanks to Bob and Frank for helping me figure it out in a booth at Arby’s"

**Comment by dwijnand** [comment]
I just wondered if he felt it was sufficiently "in the shell" as he'd suggested when he tore it out.  Upwards and onwards!

**Comment by som-snytt** [comment]
I just realized this is a long weekend; now I don't know whether to get out of town or not leave the apartment and just code.

I had thought a tiny bit about how a REPL protocol would divide the work: does the backend give me strings, or something structured that I can e.g. "colourise".

There's an ad for pistachios with an irate tortoise complaining about their "no shells" slogan.

Maybe Sheldon the Tortoise would do a pitch for REPL. "It's in the shell!"

**Comment by adriaanm** [comment]
I'm happy with this PR and the progress. As far as my colourvision on this general topic: syntax highlighting the user's input, and -- ideally -- the shell's replies should be done by parsing and highlighting them outside of the compiler (i.e., in the shell). (That's why I've been nudging the repl's way of printing results to be valid scala code as much as possible.)

**Pull request merged**
