### PR TITLE
SI-7620 Remove floating-point-literals-without-digit-after-dot

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by adriaanm** [comment]
Why did you remove the test/files/neg/ambiguous-float-dots test instead of updating its checkfile?

**Comment by soc** [comment]
@adriaanm There are two versions of it, one for deprecation, one for removal. I deleted the deprecation one and removed `-Xfuture` from the other.

**Comment by gkossakowski** [comment]
@adriaanm: This is good to go, right?

Is IDE validation working now?

**Comment by adriaanm** [comment]
LGTM -- sorry about the delay!

**Pull request merged**
