### PR TITLE
SI-8525 -Xlint:nowarn-missing-interpolator

### PR DESCRIPTION
**Pull request by som-snytt**
Turn warn-missing-interpolator into an -Xlint choice. Allow choice negation with prefix "no".  Refactor choice logic from MultiString to MultiChoice. Update set of choices all together.

The mechanism between MutableSettings and concrete settings could be further over-engineered. Rube Goldberg is occupied on another project at the moment.  For instance, no easy way to override `def wildcards = choices // filter (!_.isSetByUser)`.

Depends on #3776

Review by @retronym as follow-up to #3776

### CODE REVIEW

**Comment by som-snytt** [comment]
@retronym Changing the negatory prefix to minus.  I'll add a commit that converts anonymous lint flag tests to named, deprecates -Ywarn-foo, and makes the lint option -Xlint:foo.

**Comment by som-snytt** [comment]
Sorry, kitteh, I was too lazy to run the test suite.  Is there any chance of getting the test suite to run in under, say, ten minutes?  Wow, I never heard a kitteh laugh like that before.  The Cheshire cat would smile, but when did a cat ever cackle so witch-like?  Or are you a witch's familiar?  That would explain a lot.

**Comment by som-snytt** [comment]
@retronym Some lint options are anonymous for a good reason, that no summary name springs to mind, such as your:

```
unit.warning(pos, s"Suspicious application of an implicit view (${view.fun}) in the argument to Option.apply.") // SI-6567
```

What do you think of `-Xlint:6567`?  Too cheesy?

It would show up more likely as `-Xlint:-6567`. Not that I like it.

The available combinations of "implicit", "polymorphic", "unused", "overloaded", "adapted" and "inaccessible" limit the number of encodings.

`-Xlint:-the-one-about-Option-and-implicits`

Programmatically, maybe a lint macro, `linting(6567) { ... }`, which also obviates the otherwise inevitable comment.  Then the setting, 

```
@lints(6567) val warnSomeStuff = LintSetting("user-friendly", "some help")
```

But I guess the goal is really not to have linting code, except as a lint tool.  Just thinking aloud. Never mind.

**Comment by som-snytt** [comment]
The lints have names, and the test respects that.

Note that the point at which you name lint, the way Horton named a dust speck Whoville, is the point of no return.

**Comment by lrytz** [comment]
tests failing :crying_cat_face:

**Comment by som-snytt** [comment]
@lrytz Yup, thx.

**Comment by som-snytt** [comment]
Cleans up the lint list, adds deprecation to legacy -Y flags.  Thx to @retronym for Enabling, I didn't see a quicker (one-minute) solution to avoid two flags, one to carry the deprecation.

**Comment by retronym** [comment]
LGTM. I really like where this has ended up.

Let's also run this by @adriaanm before merging, though.

**Comment by retronym** [comment]
One variation on this would be to defer the deprecations until the 2.12.x branch.

**Comment by som-snytt** [comment]
A few tests to update; possibly lint flags are enabled that weren't?

**Comment by som-snytt** [comment]
BTW, the problem with closing a PR for fixing is that it gets lost in the heap of closed PRs, unless I missed the button for "sort by recent activity."  I don't keep in my head the branch names of side projects, etc, so it's easy to forget what I was in the middle of doing; also, my fault for not deleting enough old branches.

**Comment by retronym** [comment]
I know the feeling. `git log -g --decorate --oneline` is super helpful for chronic branch hoppers.

**Comment by som-snytt** [comment]
Thx, learning a great git command makes it all worthwhile. I keep intending to read the man pages.

My original take on this PR had something like: -Xlint turns on anonymous lint options; but now there is no notion of anonymous options, only of deprecated -Y variants.

I hope I don't have to revisit that wrinkle; otherwise, I'll iron it out.

**Comment by retronym** [comment]
LGTM

@adriaanm Could you make a call on this one for 2.11.2?

**Comment by adriaanm** [comment]
LGTM! A buffet of lintability!

**Comment by som-snytt** [comment]
Thx.  I'll leave the ironing board out, and the iron hot, for when someone complains about a wrinkle.  Though starched collars would be out of scope.

**Comment by som-snytt** [comment]
A bullet of lintability:

```
$ skala -Ywarn-nullary-unit:false
Welcome to Scala version 2.11.2-20140710-092751-3b89c168b4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0).
Type in expressions to have them evaluated.
Type :help for more information.

scala> 
[init] warning: there was one deprecation warning; re-run with -deprecation for details
warning: there was one deprecation warning; re-run with -deprecation for details
warning: there was one deprecation warning; re-run with -deprecation for details

$ skala -Ywarn-nullary-unit:false -deprecation 
Welcome to Scala version 2.11.2-20140710-092751-3b89c168b4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0).
Type in expressions to have them evaluated.
Type :help for more information.

scala> [init] warning: -Ywarn-nullary-unit is deprecated: Enable -Xlint:nullary-unit
warning: -Ywarn-nullary-unit is deprecated: Enable -Xlint:nullary-unit
warning: -Ywarn-nullary-unit is deprecated: Enable -Xlint:nullary-unit

```

**Comment by retronym** [comment]
Maybe the conservative thing to do is to undeprecate the old aliases until we can avoid the noise.

**Comment by gourlaysama** [comment]
So, if I understand correctly, `-Xlint:adapted-args` doesn't mean _I only want the `adapted-args` warning_, it means _I want all the default linters + `adapted-args`_ (that is to say, it is the same as `-Xlint`)?

Ok, it's still pretty cool to be able to selectively disable a warning :)

**Comment by som-snytt** [comment]
@gourlaysama No, that's a bug.  It was introduced in that last change to remove the -warn prefixes; it used to enable anonymous lints, but there are no more anon options, and now the condition is broken. I guess I'll fix it when I revert the deprecations? @retronym

**Comment by retronym** [comment]
It's probably the least surprising to follow the javac approach and require you to list them out explicitly once you mention this option. So please include that in the de-deprecation.

It's probably over-engineering, but `-Xlint:+defaults,-adapted-args` might be nice.

**Comment by som-snytt** [comment]
I think the syntax was intended `-Xlint:-package-object-classes,_`.

We inherit underscore from `-language:_` etc.

The behavior that fell out of favor is that `-Xlint -Xlint:-adapted-args` is sensitive to order, where first wins silently.  Enabling doesn't preserve how a setting was set.

Maybe simpler heuristic is: turning off always wins.

Except:

```
apm@mara:~/tmp$ javac -Xlint:cast,-cast warn.java
warn.java:3: warning: [cast] redundant cast to String
    String s = (String) "Hello!";
               ^
Note: warn.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
```

I didn't even realize java's lint had absorbed deprecation.

I think I'm experiencing lint envy.

**Comment by som-snytt** [comment]
Clarification: https://github.com/scala/scala/pull/3885

**Pull request merged**
