### PR TITLE
SI-6184 don't introduce dummies in checkableType

### PR DESCRIPTION
**Pull request by adriaanm**
this should fix the crash in asSeenFrom that resulted from calling
baseTypeSeq on a type that had an unbound type parameter in it

also, simplify widenToClass

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @paulp

**Comment by paulp** [comment]
This seems just as crashy after the change as before.

**Comment by paulp** [comment]
Oh, you added a commit while I was deciding that.

**Comment by adriaanm** [comment]
bazinga!

**Comment by paulp** [comment]
Can you elaborate on what is "plain wrong" with "Foo[TroubleSome]#T" ? It looks to me like what you will get if you do this:

```
val s = intp.types("s.Foo")
s.tpe.member("T": TypeName).tpe.asSeenFrom(s.tpe, s)
```

I assume you mean that the type parameter/argument dummy "TroubleSome" is wrong, but since that always looks wrong to me, I've had to drag myself toward it looking right or at least not burning my eyes out.  What should I expect to see here? Boy, "dummies" seems more apt every day, I tell you.

**Comment by adriaanm** [comment]
Yeah, the dummies are the problem I think. As usual. I wonder why they were not in undet and thus didn't get inferred.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
PLS REBUILD ALL

one of these push --force's I'm going to get it right... it might even be this time

**Comment by adriaanm** [comment]
spurious failure

**Comment by adriaanm** [comment]
I think this is now ready for scrutiny, @paulp

**Comment by jsuereth** [comment]
Review?

**Comment by paulp** [comment]
OCD me couldn't help adding on - I opened #1120 - but #1120 looks good to me.

**Comment by paulp** [comment]
Right.

**Pull request closed without merging**
