### PR TITLE
Tweak pattern for cntrl chars in REPL

### PR DESCRIPTION
**Pull request by som-snytt**
As noticed at https://github.com/scala/scala/pull/9451#issuecomment-792773836

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
```
scala> "Dankeschön"
val res0: String = Dankeschön
```

**Comment by SethTisue** [comment]
marking as "internal" since the regression never made it into a release.

**Comment by som-snytt** [comment]
Most of my regressions never find release but are kept internal. Not sure it's a healthy way to live.

**Comment by lrytz** [comment]
It made it to 2.13.5..

**Comment by SethTisue** [comment]
oh, oops! thanks for the correction

**Comment by som-snytt** [comment]
When it is about to print `???`, it should print `WTF` instead, and then `WTF?`. Or maybe `huh` or an ellipsis `...`.

The missing label is `infernal`.

Anyhoo, thanks again. This was TIL in regex, and also the PR discussion did not tease out the important question. So I remain humble with respect to code review. There is the meme about code is read more than it is written, but we ought to say, PRs are submitted once or twice and then squashed, but code reviewed many times.

**Comment by SethTisue** [comment]
We now retroactively have a corresponding bug report :-)  https://github.com/scala/bug/issues/12360

**Pull request merged**
