### PR TITLE
New CI validation scripts

### PR DESCRIPTION
**Pull request by adriaanm**
Still playing catch-up. Re-introduced 2.10-specific parts of scala-jenkins-scripts into CI scripts as they stand in 2.11.x right now.

Review by @retronym.

### CODE REVIEW

**Comment by retronym** [comment]
```
Total time: 1 minute 15 seconds
++ mv buildcharacter.properties jenkins.properties
mv: cannot stat 'buildcharacter.properties': No such file or directory
```

**Comment by adriaanm** [comment]
The IDE now fails in the same way as before in 
#4186 (https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/9174/console), so I'm going to silence it for now. Same issue as on 2.12.x -- mentioned over at https://github.com/scala-ide/uber-build/issues/48.

**Comment by adriaanm** [comment]
Should be good to go now.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
