### PR TITLE
allow $" escapes in interpolations

### PR DESCRIPTION
**Pull request by martijnhoekstra**
Closes scala/bug#6476 in spirit. Or crushes its spirit. Or at least someones spirit.

This is the least ambitious and hopefully least controversial proposal around that issue. Previous PRs, SIPs and/or SLIPs had this change as a rider, or had this change with a rider of various other interpolation improvements.

This makes it a lot easier to write a single quote in an interpolated string, by escaping it with a `$` character. This can't break anyones code, since the sequence `$"` in an interpolation is a parse error now.

I also don't believe that this gets in the way of any other work regarding interpolations, which may still be brewing.

### CODE REVIEW

**Comment by som-snytt** [comment]
You have to write scala/bug#

Since nothing is without controversy, I think the proposal needs a mini-SIP. Or a solid thread on the forum. Or whatever the low bar is these days. `s"$"low$" bar"`. Why can't Scala have normal-looking interpolation again?

**Comment by martijnhoekstra** [comment]
https://contributors.scala-lang.org/t/pre-sip-mini-sip-escapes-in-interpolations/2076 kicks of the pre-SIP dicsussion that is needed before this can be proposed as a SIP

**Comment by SethTisue** [comment]
closing for inactivity, can be revived & reopened whenever

**Pull request closed without merging**
