### PR TITLE
first stab at serialization of exprs and tags

### PR DESCRIPTION
**Pull request by xeno-by**
Includes 5 commits from https://github.com/scala/scala/pull/1017, because both this pull request and that one deploy a new starr, so I saved us all a starr-rebuilding merge.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @odersky and @adriaanm

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Merge conflicts!  Seems to always hit these reflection things.

**Comment by xeno-by** [comment]
Prepping a pullrequest that would unite https://github.com/scala/scala/pull/1017, https://github.com/scala/scala/pull/1031 and https://github.com/scala/scala/pull/1035. ETA: 15 minutes.

**Comment by xeno-by** [comment]
https://github.com/scala/scala/pull/1039

**Pull request closed without merging**
