### PR TITLE
SI-3761: Overload resolution fails on by-name parameter

### PR DESCRIPTION
**Pull request by som-snytt**
Minimized. This version should help in review for correctness. No attempt is made to address holes in the spec or to correct indentation.

We saw Yellow Submarine over the weekend and I must have got carried away by the lyric, "There's nothing you can do that can't be done."

When isAsSpecific checks if method m applies to args of types of
formal params of m1, a by-name parameter was converted to its
underlying result type for the params (of m) but not the args (of m1).
This had the useful effect of making m(A) more specific than m(=>A),
which is the specified prioritization for implicit views,
but also made m(=>A) and m(=>A, B*) ambiguous.  To handle this edge
case, the isCompatible test for A and =>A is made explicit, and
by-name params are no longer converted.

### CODE REVIEW

**Comment by lrytz** [comment]
build success https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/23/console

**Comment by lrytz** [comment]
A quick chat with @odersky revealed that he is surprised about the following:

```
scala> object t { def f(a: Int) = 0; def f(a: => Int) = 1 }
defined module t

scala> t.f(0)
res0: Int = 0
```

He says he'd expect the two to be ambiguous. So maybe the right fix for SI-3761 is to make these two ambiguous.

**Comment by som-snytt** [comment]
It just occurred to me that obviously implicit search sees ambiguity across contexts; that's the sense in which by-value is preferred.

**Comment by lrytz** [comment]
discussed more with martin, concluded that your patch is the correct fix. details coming later, have to run.

**Pull request merged**
