### PR TITLE
SI-8019 Make Publisher check PartialFunction is defined for Event

### PR DESCRIPTION
**Pull request by rtyley**
_re-submission of https://github.com/scala/scala/pull/3205 rebased against the 2.10.x branch - @adriaanm points out that post 2.10.x, swing has moved to https://github.com/scala/scala-swing_

Reactions are PartialFunctions, so if events come through indiscriminately that the listener is not defined for, errors occur. Eg:

```
Exception in thread "AWT-EventQueue-0" scala.MatchError: FocusGained(scala.swing wrapper scala.swing.TextField
```

A Coursera thread with people affected by this issue: https://class.coursera.org/reactive-001/forum/thread?thread_id=1315

_I've signed the Scala CLA._

### CODE REVIEW

**Comment by rtyley** [comment]
https://github.com/scala/scala/pull/3243 was incorrectly requested against `master` rather than `2.10.x`.

**Comment by adriaanm** [comment]
I tried to diagnose what went wrong here, and it seems the bot is still trying to merge into master, even though the PR is correctly targeted at 2.10.x. Could you see about rebasing?

I hope this will do the trick:

```
git checkout si-8019-swing-publisher-check-pf-defined
git pull --rebase https://github.com/scala/scala.git 2.10.x
git push -f origin si-8019-swing-publisher-check-pf-defined
```

**Comment by rtyley** [comment]
The rebase seems to have done the trick - build passed this time!

**Comment by adriaanm** [comment]
Thanks!

**Comment by adriaanm** [comment]
LGTM! This will go into 2.10.4-RC1, which should be out next week!

**Comment by rtyley** [comment]
> This will go into 2.10.4-RC1, which should be out next week!

That is _awesome_ :sparkles:

**Pull request merged**
