### PR TITLE
Bump akka-actor version to 2.3.3 (ref SI-8549)

### PR DESCRIPTION
**Pull request by adriaanm**
Because serialization affected akka, we're upgrading the included
akka-actor to 2.3.3, which is built with Scala 2.11.1.

Review by @retronym

### CODE REVIEW

**Comment by retronym** [comment]
What's the steps in the release dance (release 2.11.1 / release Akka / merging this PR) ?

**Comment by adriaanm** [comment]
This PR must be merged first, because versions.properties determines the scala-library-all pom. The bump won't affect anything besides distribution building, so we have some margin to coordinate.

**Comment by adriaanm** [comment]
After merging this PR, I'll stage the 2.11.1 build. Once akka is staged as well, we can build the distribution.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
