### PR TITLE
Upgrade Dotty to 0.18.1-RC1

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by biboudis** [comment]
The deprecated `do .. while ... ` are responsible for the CI failure.

**Comment by ashawley** [comment]
If you enable `-language:Scala2` it might get further along.

**Comment by biboudis** [comment]
I will update the PR with manual rewrites today.

**Comment by SethTisue** [comment]
curious why Travis failed here though Jenkins passed, is there a discrepancy in how those two builds are configured? did we add Dotty to `.travis.yml` but not to the Jenkins script?

**Comment by biboudis** [comment]
Ah, maybe the `-Dscala.build.compileWithDotty=true library/compile` is missing for the Jenkins one?

**Comment by biboudis** [comment]
I have updated the PR and I would like to ask some questions.

1. What is the `combined — Found earlier commit(s) marked failure: a9b9b6`? 🌮🤣 
2. The CI runs `sbt -Dscala.build.compileWithDotty=true library/compile` and it now passes but running a `junit/test` afterwards reveals not only more do-whiles but also a compiler crash. Just FWI, I have run the partest (of course without compiling with dotty and it passed, so the while-based logic seems OK, at least for correctness). Is `library/compile` good enough for now, for the CI?
3. The implementation is while-based and I have a WIP, recursive one. Do you think a recursive `collect` fits into the picture of `s.c.i.List`?

**Comment by SethTisue** [comment]
> What is the combined — Found earlier commit(s) marked failure: a9b9b6

in this repo, _every_ commit in a PR is expected to pass CI, not just the final commit. (this facilitates later use of `git bisect` to pinpoint the sources of bugs)

so when a commit fails CI, you'll need to rebase and force-push eventually, before the PR is merged. for modest PRs, doing so early is usually fine. for more complex PRs that evolve and/or get a lot of reviewer comments, it's sometimes helpful to reviewers to save the squashing/rebasing until reviewers have signed off.

(I'll let someone else answer your other two questions.)

**Comment by SethTisue** [comment]
> Is library/compile good enough for now, for the CI?

@smarter opinion?

**Comment by smarter** [comment]
Yeah, compiling the tests is not possible yet, because the dotty typer drops primitive classes, so the produced scala-library is incomplete.

**Comment by SethTisue** [comment]
> The implementation is while-based and I have a WIP, recursive one. Do you think a recursive collect fits into the picture of s.c.i.List

@szeiger wdyt?

**Comment by szeiger** [comment]
In principle a recursive implementation is preferable because it allows the head of the list to be dereferenced while traversing. This is not as big an issue here as it is in LazyList because the list itself is already evaluated and cannot grow any further while being traversed but you have a similar case when collecting only a few elements and computing much larger objects from them.

But a lot of micro-optimizations go into these core methods so any change needs to be backed up by benchmarks.

**Comment by biboudis** [comment]
So I am leaving this as is, when the CI passes it will be ready for review. There may be an optimisation opportunity to rewrite `s.c.Iterator.filterImpl.hasNext` tail recursively but I may investigate separately for fun.

**Comment by smarter** [comment]
Ping for review.

**Pull request merged**
