### PR TITLE
SI-6120 multiple warnings at same position.

### PR DESCRIPTION
**Pull request by paulp**
An error suppresses all further warnings at the same
position, but multiple warnings can be heard.

### CODE REVIEW

**Comment by retronym** [comment]
LGTM. Really good!

**Comment by xeno-by** [comment]
Is suppression of warnings after an error a deliberate choice, or it's another bug remaining to be fixed?

**Comment by retronym** [comment]
@xeno-by That's by design. Get the code compiling, then address warnings.

**Comment by paulp** [comment]
Thanks for not making me chase down the revealed-as-redundant warnings in equality sensibility checking. However someone with a longer time horizon than me might want to do that.

**Comment by som-snytt** [comment]
For "sensibility" warnings, it occurred to me you could prefix warnings at the same position with: "Moreover,..."  or "And furthermore,.." or "You might also consider that..."  and then it all makes sense again, or at least it reads OK.

**Comment by xeno-by** [comment]
:)

**Pull request merged**
