### PR TITLE
Added -Xdev setting... you know, for devs

### PR DESCRIPTION
**Pull request by paulp**
A setting we developers can give all the time and expect to
hear useful things without being buried in debugging output.
As the comment says:

  This is for WARNINGS which should reach the ears of scala
  developers whenever they occur, but are not useful for normal
  users. They should be precise, explanatory, and infrequent. Please
  don't use this as a logging mechanism. !!! is prefixed to all
  messages issued via this route to make them visually distinct.

This is what I always intended for "debugwarn", the method
I have deprecated in favor of the more accurate:

  def devWarning(msg: => String): Unit

In this VERY SAME COMMIT, I performed the CLOSELY RELATED
task of quieting down an -Xlint warning which had become too
noisy thanks to implicit classes tickling it. I tightened that
warn condition to include both -Xlint and -Xdev.

### CODE REVIEW

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
Great idea. So basically I'd have `scala -deprecation -Xmigration -Xfuture -Xdev` now ... would it make sense to combine `-Xmigration` and `-Xfuture`? I tried to implement some changes to make `@migration` less specific to the 2.7-to-2.8 switch and more usable for developers, but those changes never went in. I don't think that toggling `-Xmigration` has any useful warnings currently (although I would have a lot of uses for it).

**Comment by paulp** [comment]
-Xmigration is supposed to tell you when you are using a construct the semantics of which have changed in the most recent version; -Xfuture is supposed to change the behavior of the compiler to do what it will do in a not-yet-released version. Those are different things, I don't think they are combinable. I agree -Xmigration is either useless or close to it right now, it is unfortunately not something which remains useful without a fair bit of ongoing attention.

**Comment by soc** [comment]
> -Xmigration is supposed to tell you when you are using a construct the semantics of which have changed in the most recent version; -Xfuture is supposed to change the behavior of the compiler to do what it will do in a not-yet-released version. Those are different things, I don't think they are combinable.

Yes, that's right. I agree.

> I agree -Xmigration is either useless or close to it right now, it is unfortunately not something which remains useful without a fair bit of ongoing attention.

I'll have a look whether my old patches can be revived. I think the main issue in the past was the version field and how it should be used in the user's libraries. (Libraries usually don't line up their deprecation cycles with Scala releases, etc.) But maybe it would even be beneficial to tell library authors that they should do exactly that?

If you want to make the decision that the migration version should track Scala versions only, I'll look for my old pull request again and update it.

**Comment by adriaanm** [comment]
please rebase and reopen

**Pull request closed without merging**
