### PR TITLE
[nomerge] Backport REPL big print fix

### PR DESCRIPTION
**Pull request by som-snytt**
Surprisingly painless. (jinx)

### CODE REVIEW

**Comment by som-snytt** [comment]
How did github know to recommend hrhino as reviewer? That's so eerie.

**Comment by dwijnand** [comment]
Any reason this doesn't contain `test/files/run/t10956.scala` from https://github.com/scala/scala/pull/6860/files?w=1?

**Review by hrhino — COMMENTED** [review]
yes, the test may be nice to have.

**Review by hrhino — APPROVED** [review]

**Comment by som-snytt** [comment]
Serves me right for commenting how painless it was, "jinx" notwithstanding.

**Comment by SethTisue** [comment]
@som-snytt this is failing on Windows at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/1038/consoleFull , probably line endings nonsense as usual

**Comment by som-snytt** [comment]
I so jinxed myself. How could I have been so foolish? I'll take a look. I love line endings, I love to just plunge my arms up to the elbows in a bucket of line endings.

**Comment by SethTisue** [comment]
@som-snytt want me to take care of it?

**Comment by som-snytt** [comment]
@SethTisue Sorry I forgot, I'll take a look to clean up after myself.

**Comment by som-snytt** [comment]
I guess it truncates the output differently because it counts the CRs when it decides where to snip.

"In the contest between humans, nature, and machines, I stand firm on the side of nature; unfortunately, nature's on the side of the machines."

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/6949

**Pull request merged**
