### PR TITLE
SI-4976 Scaladoc: Add a source link to package objects

### PR DESCRIPTION
**Pull request by kzys**
If a package has a package object, the source link should point the source file of the package object.

Review by @heathermiller

### CODE REVIEW

**Comment by JamesIry** [comment]
ping @heathermiller for review or naming somebody else.

**Comment by JamesIry** [comment]
ping @VladUreche Need some help moving this 16 day old PR forward.

**Comment by heathermiller** [comment]
This seems fine to me (i.e. LGTM), and it works as advertised. But I'm not the Scaladoc model expert, I don't know if this breaks some sort of special case, so I'll let @VladUreche step in for the final LGTM.

**Comment by VladUreche** [comment]
Post-merge LGTM from me too, thanks Kato! :p

**Comment by som-snytt** [comment]
Just ran into this in the online docs, thanks from me, too.

**Pull request merged**
