### PR TITLE
SI-8591 Scaladoc: Problem with scrolling under Safari on iOS

### PR DESCRIPTION
**Pull request by mkubala**
This PR resolves some 'small but snippy' problem with scrolling scaladoc contents under Safari on iOS.

To ease reviewing my changes, I've published two versions of generated documentation:
1. Version without fix (you can't scroll the right frame): http://scaladoc-permalinks.herokuapp.com/index.html#scalaz.CoyonedaInstances0@finalize():Unit
2. Version with CSS fix: http://scaladoc-ios.herokuapp.com/index.html#scalaz.CoyonedaInstances0@finalize():Unit

My branch came out from 2.12.x but I can rebase it if needed.

I've signed Scala CLA.

OT: I regret that I didn't fix it before I finished reading 'scala puzzlers' - exploring scaladocs would be then much more comfortable. Maybe it's worth to publish this fix before that book will be published? There is not so much to review..

### CODE REVIEW

**Comment by VladUreche** [comment]
Thanks Marcin!
LGTM for me on Linux. Can someone with a mac check this please?

**Comment by vendethiel** [comment]
I can confirm that this fixes the issue on safari iOS for me

**Comment by demobox** [comment]
> Maybe it's worth to publish this fix before that book will be published?

That would be nice, @mkubala! Otherwise, we might have to add a warning to the introduction ;-)

**Comment by VladUreche** [comment]
@demobox @mkubala: Keep in mind this change will only become available once the first milestone of Scala 2.12 is released. If you want the see the results sooner, how about targeting 2.11.x?

**Comment by mkubala** [comment]
For me it will be even better if I could benefit from this fix in 2.11.x, but I leave this decision up to you.
I could rebase my branch If review will pass without any objections - that's no problem.

**Comment by retronym** [comment]
2.11.x is the right place for this sort of fix. Thanks for the contribution!

**Comment by mkubala** [comment]
Ok, I'm going to rebase it :)

**Comment by mkubala** [comment]
New PR for 2.11.x is available here: #3756

**Pull request closed without merging**
