### PR TITLE
SI-6388 Remove deprecated items scheduled for 2.11

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @paulp @gkossakowski, please.

I currently left out the Application/Predef changes, because something triggers a ScalaDoc test failure and I haven't found the cause yet.

**Comment by soc** [comment]
Mhhh. What's the recommended action here? Fix SBT? Or drop the change?

**Comment by gkossakowski** [comment]
It's cool we have tests for sbt!

I'd say drop the change so the rest of your changes are not blocked and then try asking on sbt's mailing list what would be preferred way of moving forward with this.

**Comment by soc** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
Sigh ... why do these SBT compiler interfaces even exist, if they keep depending on deprecated functionality?

**Comment by gkossakowski** [comment]
SBT has to work across many versions of the compiler (probably including 2.8, 2.9, 2.10 and 2.11). Still, the details should be discussed with @jsuereth and @harrah.

**Comment by harrah** [comment]
@gkossakowski is correct.  Patches are welcome that work across those versions.  Already released versions of sbt, such as 0.12.0, should be considered as well when making changes for 2.10.

**Comment by jsuereth** [comment]
BTW - The SBT interface is now used by Maven (Zinc), Gradle (Zinc) and hopefully ANT soon.

You can think of it as the compiler's exposed interface, where deprecated features have to remain for a _long_ time.   While we pretend we don't have this inside the compiler the truth is SBT has been doing the work for us.

I won't entertain any patch that breaks SBT without a suitable migration path.   We have too many users of these interfaces.   

I _would_ entertain the possibility of a default implementation of the interface in Scala 2.11 that users can pull but could be overridden by build tools if they find the interface is buggy.

In any case, thanks for trying to remove deprecated features.   Most of us won't have much time to help out / divide our attention from 2.10.0-RC1 at this point, but in a few weeks I'll be able to offer what help I can.

**Comment by soc** [comment]
Maybe I'm missing something crucial here, but isn't exactly this interface supposed to be shielding us from breaking build tools when changes happen to the compiler? Why is it not possible to update the SBT interface?

**Comment by gkossakowski** [comment]
@jsuereth: Do not impersonate kitten please! :-)

**Comment by soc** [comment]
I guess it makes sense to leave out the `Predef` parts for now, get the rest merged and then have a look at the SBT stuff again.

**Comment by gkossakowski** [comment]
Yes, I agree. Let's work on this in a new pull request. I'll close this one.

**Pull request closed without merging**
