### PR TITLE
SI-4563 friendlier behavior for Ctrl+D in the REPL

### PR DESCRIPTION
**Pull request by gourlaysama**
Closing the REPL with Ctrl+D does not issue a newline, so the user's
prompt displays on the same line as the `scala>` prompt. This is bad.
We now force a newline before closing the interpreter, and display
`:quit` while we're at it so that people know how to exit the REPL
(since `exit` doesn't exist anymore).

The tricky part was to only add a newline when the console is
interrupted, and _not_ when it is closed by a command (like `:quit`),
since commands are processed after their text (including newline) has
been sent to the console.

### CODE REVIEW

**Comment by gourlaysama** [comment]
review by @som-snytt

An interesting consequence is that all REPL test outputs end with `:quit` now. On the one hand, maybe `ReplTest` should run with `interactive = false`, since it really isn't interactive, but on the other hand, it is supposed to simulate a user writing in the REPL, which would always end with `:quit` now.

**Comment by gourlaysama** [comment]
Oh, seems like this broke a few more tests than anticipated.

**Comment by som-snytt** [comment]
I'd guess.  How about not hardcoding it?  You can set the shell.prompt, probably you have to be able to customize this behavior, too.  People reuse the repl.

In fact, I think will change my exit string to `Bye. :)`.  Now _that's_ a friendly repl.

**Comment by gourlaysama** [comment]
You mean allowing users to disable this (go back to the previous behavior), or allowing them to change the text written when exiting?

**Comment by gourlaysama** [comment]
Ok, I went for both, with `:quit\n` by default.

@som-snytt

**Comment by gourlaysama** [comment]
PLS REBUILD/pr-scala@ed9dfee

**Comment by lrytz** [comment]
LGTM!

**Comment by som-snytt** [comment]
@gourlaysama It just said quit to me!  It's the little things that matter. :+1:

**Pull request merged**
