### PR TITLE
SI-8596 Fix rangepos crasher with defaults, poly methods

### PR DESCRIPTION
**Pull request by retronym**
Regressed in SI-7915 / 3009a525b5

We should be deriving the position of the synthetic `Select`
from `basefun1`, rather than `basefun`. In the new, enclosed
test, the difference amounts to:

```
new Container().typeParamAndDefaultArg[Any]()
`------------ basefun1 --------------'
`----------------- basefun ---------------'
```

For monomorphic methods, these are one and the same, which is
why `presentation/t7915` was working. I've extended that test
to a polymorphic method to check that hyperlink resolution works.

Review by @dotta

Targetting to 2.10.x as the regression was backported to 2.10.4

### CODE REVIEW

**Comment by retronym** [comment]
Or, review by @lrytz

**Comment by lrytz** [comment]
LGTM, thanks!

**Comment by dotta** [comment]
:+1:

**Comment by sksamuel** [comment]
Thanks for fixing this guys.

**Pull request merged**
