### PR TITLE
Partest toolargs caching [ci: last-only]

### PR DESCRIPTION
**Pull request by som-snytt**
Reduce reading/parsing of partest "toolArgs" from test headers.

Supported "tool" names are enumerated (as in dotty, the thought leader). Only "filter" is unparsed.

Note "javaVersion" is only used as a lower bound, "19+", as in dotty, the thought leader, so for simplicity [sic] a range must be written without spaces, "11-19".

### CODE REVIEW

**Comment by SethTisue** [comment]
Could/should this be a single commit? It wasn't obvious to me as reviewer that these were distinct chapters of a story, except maybe the usual "in the end I got it working" story :-)

**Comment by som-snytt** [comment]
I didn't want anybody's 🤯 as it is a lot to take in.

**Comment by som-snytt** [comment]
also, I've started ci: last-only if I sense that I will squash later. Reviewer can review all changes at once, per pleasure. Don't be fooled by the fact that only one file changed! Partest is basically one file now.

**Comment by som-snytt** [comment]
@SethTisue you were correct, I intended to squash after review. Other PRs are unsquashed. I'll wait a while to give you time to tell me if you have an opinion on whether I should pre-squash; otherwise I will go ahead and squash in the interest of time.

**Comment by som-snytt** [comment]
@SethTisue this PR has a semantic conflict and causes a compile error in partest. I will dispatch a PR to fix.

**Comment by SethTisue** [comment]
>  I will dispatch a PR to fix.

I beat you to it

> I intended to squash after review

no worries

**Pull request merged**
