### PR TITLE
fix 11551. use == instead of equals in BitmapIndexedSetNode

### LINKED ISSUE #11551: Set broken in Scala 2.13.0-RC3
```
Welcome to Scala 2.13.0-RC3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
Type in expressions for evaluation. Or try :help.

scala> val x = Set[AnyVal](1L, (), 28028, -3.8661012E-17, -67)
x: scala.collection.immutable.Set[AnyVal] = HashSet((), 28028, -3.8661012E-17, -67, 1)

scala> val y = Set[AnyVal](1, 3.3897517E-23, ())
y: scala.collection.immutable.Set[AnyVal] = Set(1, 3.3897517E-23, ())

scala> val z = x ++ y
z: scala.collection.immutable.Set[AnyVal] = HashSet((), 28028, -3.8661012E-17, -67, 3.3897517E-23, 1, 1)

scala> println(z.toList.toSet == z)
false

scala> println(z.toList.toSet)
HashSet((), 28028, -3.8661012E-17, -67, 1, 3.3897517E-23)
```

```
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
Type in expressions for evaluation. Or try :help.

scala> val x = Set[AnyVal](1L, (), 28028, -3.8661012E-17, -67)
x: scala.collection.immutable.Set[AnyVal] = Set((), 28028, -3.8661012E-17, -67, 1)

scala> val y = Set[AnyVal](1, 3.3897517E-23, ())
y: scala.collection.immutable.Set[AnyVal] = Set(1, 3.3897517E-23, ())

scala> val z = x ++ y
z: scala.collection.immutable.Set[AnyVal] = Set((), 28028, -3.8661012E-17, -67, 1, 3.3897517E-23)

scala> println(z.toList.toSet == z)
true

scala> println(z.toList.toSet)
Set((), 28028, -3.8661012E-17, -67, 1, 3.3897517E-23)
```

### PR DESCRIPTION
**Pull request by xuwei-k**
fix https://github.com/scala/bug/issues/11551

### CODE REVIEW

**Review by hrhino — APPROVED** [review]

**Comment by NthPortal** [comment]
What I don't understand is why that change fixes anything (and/or why it was broken in the first place). `equals` works fine for `j.l.Integer`.

**Comment by SethTisue** [comment]
I've tentatively put this on a new 2.13.0 milestone, since it seems like something that could mergeable without a further RC. @adriaanm will make the final call

**Comment by dwijnand** [comment]
@NthPortal you need to pick to either use equals and hashCode and ignore collaborative equality/hashing (which is faster but some things are "weird"), or you use `==` and `##` (and pay the performance cost).  When you're inconsistent these issues crop up (subjectively, worst of both worlds).  Notice the use of `##`s in HashSet.

**Review by joshlemer — APPROVED** [review]

**Comment by NthPortal** [comment]
oh oops - I didn't notice that one was `1` and one was `1L`

**Comment by adriaanm** [comment]
Let's ship this in 2.13.0. Thank you, @xuwei-k!

**Pull request merged**
