### PR TITLE
merge 2.12.0 onto 2.12.x [ci: last-only]

### PR DESCRIPTION
**Pull request by SethTisue**
main motivation here is to get the STARR bump

no manual merging needed

### CODE REVIEW

**Comment by SethTisue** [comment]
updated with latest batch of merged 2.12.0 PRs

**Comment by adriaanm** [comment]
/rebuild (bumped behemoth 2 to bigger instance type)

**Comment by SethTisue** [comment]
Jenkins failed because https://github.com/scala/scala-jenkins-infra/issues/181

**Comment by SethTisue** [comment]
@adriaanm shall we merge? this is now several weeks' worth of commits

**Comment by adriaanm** [comment]
Thanks, please do! (And no need to wait for me in the future for clear wins like this.)

**Pull request merged**
