### PR TITLE
Add JDK 11 by OpenJDK to Travis CI matrix

### PR DESCRIPTION
**Pull request by eed3si9n**
ref https://github.com/scala/scala/pull/7026

### CODE REVIEW

**Comment by xuwei-k** [comment]
I have fixed some tests in `2.13.x` branch. (should be backport to `2.12.x`)

- https://github.com/scala/scala/pull/7271
- https://github.com/scala/scala/pull/7273
- https://github.com/scala/scala/pull/7288


still fail some tests https://github.com/scala/scala-dev/issues/559#issuecomment-425125666

**Comment by adriaanm** [comment]
Given the work on Java 11 compatibility already done in 2.13.x by xuwei-k and others, I propose we focus our effort there, and backport to 2.12.x once it's done.

**Comment by eed3si9n** [comment]
@adriaanm Yea. I agree doing the actual fixes in 2.13.x. I just want to get to the test phase in Travis CI so we know how many tests fail for 2.12.x on JDK 11.

**Comment by adriaanm** [comment]
Closing, since the experiment has delivered its results. Feel free to reopen for another run, of course.

**Comment by SethTisue** [comment]
this finally went forward at https://github.com/scala/scala/pull/9579

**Pull request closed without merging**
