### PR TITLE
Merge 2.11.x to 2.12.x

### PR DESCRIPTION
**Pull request by retronym**
```
% git fetch origin

% git checkout origin/2.12.x

HEAD is now at 132a058... Merge pull request #3715 from retronym/topic/bump

% git checkout -b merge/2.11.x-to-2.12.x
Switched to a new branch 'merge/2.11.x-to-2.12.x'


% export MB=$(git merge-base origin/2.11.x origin/2.12.x)

% git log --decorate --oneline --graph $MB...origin/2.11.x
*   7523ed3 (origin/2.11.x) Merge pull request #3719 from retronym/ticket/8546
|\
| * 1ba2d7b (origin/pr/3719) SI-8546 Pattern matcher analysis foiled by over-widening
*   7bac372 Merge pull request #3727 from retronym/ticket/8531
|\
| * b154269 (origin/pr/3727, origin/pr/3696) SI-8531 Better space efficiency for patmat analysis
*   d32459b Merge pull request #3729 from retronym/merge/master-to-2.11.x
|\
| *   a132314 (retronym/merge/master-to-2.11.x, origin/pr/3729, merge/master-to-2.11.x) Merge commit 'b5392a0' into merge/master-to-2.11.x
| |\
| | *   b5392a0 Merge pull request #3704 from gourlaysama/wip/t8504
| | |\
| | | * c6b5028 (origin/pr/3704) SI-8504 fix NPE in the Java wrapper for a Scala Map.
| | *   6dd0a36 Merge pull request #3689 from xeno-by/ticket/8523
| | |\
| | | * 2d37cc0 (origin/pr/3689) makes bundles friendly to -Ywarn-dead-code
| | *   63b91bf Merge pull request #3706 from gourlaysama/wip/t8550
| | |\
| | | * b3243e8 (origin/pr/3706) SI-8550 fix scaladoc for the default s.c.LinearSeq.
| | *   a4e56ef Merge pull request #3711 from retronym/ticket/8549-2
| | |\
| | | * 2dbd269 (retronym/ticket/8549-2, origin/pr/3711) SI-6988 Test case for non-literal / non-constant SerialVersionUID
| | | * e7ab41e SI-8549 Enforce serialization stability for selected collections
| | | * ecbc9d0 SI-8549 Honour the @SerialVersionUID annotatation
| | *   e8ed2d2 Merge pull request #3703 from huitseeker/issue/SI-8537
| | |\
| | | * 8317266 (origin/pr/3703) SI-8537 Puts SI-8157 fix under Xsource
| | * e735cb3 Merge pull request #3576 from som-snytt/issue/8325
| | * b0fe135 (origin/pr/3576) SI-8325 Accept infix star type outside patterns
* |   d757662 (topic/merge-2.10.x-to-2.11.x-2, 2.11.x) Merge pull request #3726 from lrytz/unreachable
|\ \
| |/
|/|
| * cee2ad2 (origin/pr/3726) Disable 'unreachable' test for GenBCode
* |   972244d Merge pull request #3721 from lrytz/t7852
|\ \
| * | 30610d5 (origin/pr/3721) BCodeICodeCommon through composition rather than inheritance
| * | 8402340 SI-7852 for GenBCode
|  /
* |   a469cab Merge pull request #3728 from retronym/topic/merge-2.10.x
|\ \
| * \   b7f91a2 (retronym/topic/merge-2.10.x, origin/pr/3728) Merge commit 'ec05aeb' into topic/merge-2.10.x
| |\ \
| | * \   ec05aeb (origin/2.10.x, 2.10.x) Merge pull request #3678 from retronym/ticket/8479
| | |\ \
| | | * | c4561c1 (retronym/ticket/8479, origin/pr/3678) SI-8479 Fix constructor default args under scaladoc
| | |  /
| | * |   c74e132 Merge pull request #3655 from retronym/ticket/8442
| | |\ \
| | | * | 8262ed2 (retronym/ticket/8442, origin/pr/3655) SI-8442 Ignore stub annotation symbols in `AnnotationInfo#matches`
| | |  /
| | * |   2af68ee Merge pull request #3551 from xeno-by/topic/typecheck-member-def
| | |\ \
| * | \ \   ac8b44d Merge commit '3314d76' into topic/merge-2.10.x
| |\ \ \ \
| | | |/ /
| | |/| |
| | * | | 3314d76 (origin/pr/3551) [nomaster] typecheck(q"class C") no longer crashes
| |  / /
| * | |   81f79a0 Merge commit '876590b' into topic/merge-2.10.x
| |\ \ \
| | |/ /
| | * | 876590b Merge pull request #3614 from retronym/ticket/8196
| | * | 540963f (retronym/ticket/8196, origin/pr/3614) SI-8195 Test case to show this is a dup of SI-8196
| | * | 7b72f95 SI-8196 Runtime reflection robustness for STATIC impl details
| |  /
* | |   6a0b661 Merge pull request #3725 from gkossakowski/fastTrack-composition
|\ \ \
| |_|/
|/| |
| * | f52d31f (origin/pr/3725) Refactor FastTrack to use composition instead of inheritance.
* | |   c26b4cc Merge pull request #3724 from gkossakowski/classpath-doLoad
|\ \ \
| * | | a4151c0 (origin/pr/3724) Get rid of Platform.doLoad method.
| |/ /
* | |   069cb86 Merge pull request #3723 from gkossakowski/partest-eclipse-project
|\ \ \
| |/ /
|/| |
| * | bab1740 (origin/pr/3723) Make partest to depend on Scala compiler Eclipse project.
|/ /
* |   cc58870 Merge pull request #3717 from retronym/topic/mima
|\ \
| |/
|/|
| * fff4722 (retronym/topic/mima, origin/pr/3717, topic/mima) Use 2.11.0 as the MiMa baseline for 2.11.x
* 9ad96d0 Merge pull request #3718 from lrytz/partestArgs
* 10d77e9 (origin/pr/3718) Respect -Dpartest.scalac_opts when running the test suite through ANT

% git show fff4722
commit fff4722157d89cd6350ebc888efd3ba95b29c1a0
Author: Jason Zaugg <jzaugg@gmail.com>
Date:   Wed May 7 11:14:13 2014 +0200

    Use 2.11.0 as the MiMa baseline for 2.11.x

    Rather than 2.11.0-RC3.

diff --git a/build.xml b/build.xml
index a66c138..ed12eb0 100755
--- a/build.xml
+++ b/build.xml
@@ -1505,7 +1505,7 @@ TODO:
                                   BINARY COMPATIBILITY TESTING
 ============================================================================ -->
   <target name="bc.init" depends="init" unless="maven-deps-done-mima">
-    <property name="bc-reference-version" value="2.11.0-RC1"/>
+    <property name="bc-reference-version" value="2.11.0"/>

     <property name="bc-build.dir" value="${build.dir}/bc"/>
     <!-- Obtain mima -->


% git merge origin/2.11.x
Auto-merging build.xml
Merge made by the 'recursive' strategy.
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
LGTM -- yay for 'recursive'

**Comment by retronym** [comment]
PLS SYNCH

**Comment by retronym** [comment]
@adriaanm 'recursive' just keeps on giving, one more merge commit to review. (I'm seeking a green end to the week for https://scala-webapps.epfl.ch/jenkins/view/2.N.x/)

**Comment by retronym** [comment]
PLS SYNCH

**Pull request merged**
