### PR TITLE
SI-7479 Make test/files/run/tailcalls.scala pass on Avian

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @retronym, please.

Mailing list: https://groups.google.com/d/topic/scala-internals/FDuwuP1daAg/discussion

**Comment by soc** [comment]
PLS REBUILD ALL

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f02c5645c34, pid=17101, tid=139649711859456
#
# JRE version: 6.0_33-b04
# Java VM: Java HotSpot(TM) 64-Bit Server VM (20.8-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x329c34]  CardTableExtension::scavenge_contents_parallel(ObjectStartArray*, MutableSpace*, HeapWord*, PSPromotionManager*, unsigned)+0x134
#
# An error report file with more information is saved as:
# /localhome/jenkins/c/workspace/pr-checkin-per-commit/hs_err_pid17101.log
#
# If you would like to submit a bug report, please visit:
#   http://java.sun.com/webapps/bugreport/crash.jsp
#
/localhome/jenkins/c/workspace/pr-checkin-per-commit/jenkins-scripts/build: line 33: 17101 Aborted                 ant $antArgs $scalacArgs nightly
```

*sigh*

**Comment by som-snytt** [comment]
The mechanism isn't sufficiently general, but did you consider something like
https://github.com/scala/scala/blob/master/test/files/neg/javac-error.check
?
There's a kludgy check on the keyword in partest.nest's Runner.scala.

**Comment by soc** [comment]
Thanks @som-snytt, I'll look into it.

**Comment by soc** [comment]
@som-snytt, I added support for this in the second commit of https://github.com/scala/scala/pull/2532, could you review that?

**Comment by retronym** [comment]
PLS REBUILD/pr-checkin-per-commit@45f2cdd

**Comment by retronym** [comment]
DNLGTM. I don't like repeating the checkfile contents.

I think the test should throw call a method `skipped("reason")`, which throws a `SkippedException`. Partest should be tweaked to catch this and mark a test ask skipped, but not fail the build.

If this proves to be too difficult, I might support an alternative, in which you read the checkfile and print the contents. But I would really prefer some indication in the output of which tests were skipped.

**Comment by retronym** [comment]
Closing the PR now as the queue is too full; please reopen when you're ready.

**Comment by soc** [comment]
@retronym As mentioned in the linked commit, I'll be using partest's functionality to specify multiple results for different runtimes.

**Comment by som-snytt** [comment]
There's another test that also wants to declare that it doesn't know how to run.

```
 // todo signal test runner that test is skipped
  new File("/bin/ls")  // innocuous
```

**Pull request closed without merging**
