### PR TITLE
Merge 2.11.x to 2.12.x

### PR DESCRIPTION
**Pull request by retronym**
```
% git log --oneline -1 --decorate
4210262 (HEAD, origin/2.12.x, 2.12.x) Merge pull request #4474 from lrytz/versionsUpdate

% git log --oneline -1 --decorate origin/2.11.x
6a185e3 (origin/2.11.x, 2.11.x) Merge pull request #4471 from smarter/spec/remove-NotNull

% git co -b merge/2.11.x-to-2.12.x-20150501
Switched to a new branch 'merge/2.11.x-to-2.12.x-20150501'

% export MB=$(git merge-base head origin/2.11.x)

% git merge origin/2.11.x
Auto-merging test/files/run/classfile-format-52.scala
Auto-merging test/files/run/classfile-format-51.scala
Auto-merging src/reflect/scala/reflect/internal/Types.scala
Auto-merging src/reflect/scala/reflect/internal/TreeGen.scala
Auto-merging src/reflect/scala/reflect/internal/Symbols.scala
Auto-merging src/library/scala/sys/process/BasicIO.scala
Auto-merging src/library/scala/concurrent/duration/Duration.scala
Auto-merging src/library/scala/collection/immutable/Stream.scala
Auto-merging src/library/scala/collection/concurrent/Map.scala
Auto-merging src/library/scala/Predef.scala
Auto-merging src/interactive/scala/tools/nsc/interactive/Global.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Typers.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Infer.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Contexts.scala
Auto-merging src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
Removing spec/public/scripts/navigation.js
Auto-merging spec/public/scripts/LICENSE-highlight
Removing spec/public/images/scala-logo-red-spiral-dark.png
Auto-merging spec/11-annotations.md
Auto-merging spec/07-implicits.md
Auto-merging build.xml
Merge made by the 'recursive' strategy.
 .gitignore                                                             |   6 +
 README.md                                                              |   9 +
 build.sbt                                                              | 443 +++++++++++++++++
 build.xml                                                              |   8 +-
 compare-build-dirs-ignore-patterns                                     |   8 +
 compare-build-dirs.sh                                                  |   5 +
 project/ScalaTool.scala                                                |  44 ++
 project/build.properties                                               |   1 +
 project/plugins.sbt                                                    |   1 +
 spec/01-lexical-syntax.md                                              | 348 +++++++-------
 spec/02-identifiers-names-and-scopes.md                                |   4 +-
 spec/03-types.md                                                       |  26 +-
 spec/04-basic-declarations-and-definitions.md                          |   4 +-
 spec/05-classes-and-objects.md                                         |  10 +-
 spec/06-expressions.md                                                 |  20 +-
 spec/{07-implicit-parameters-and-views.md => 07-implicits.md}          |  12 +-
 spec/08-pattern-matching.md                                            |   6 +-
 spec/10-xml-expressions-and-patterns.md                                |   2 +-
 spec/{11-user-defined-annotations.md => 11-annotations.md}             |  31 +-
 spec/12-the-scala-standard-library.md                                  |   6 +-
 spec/13-syntax-summary.md                                              |   6 +-
 spec/15-changelog.md                                                   | 823 ++++++++++++++++++++++++++++++++
 spec/README.md                                                         |   2 +-
 spec/_includes/numbering.css                                           |   2 -
 spec/_layouts/default.yml                                              |  72 +--
 spec/_layouts/toc.yml                                                  |  26 +-
 spec/index.md                                                          |  21 +-
 spec/public/fonts/Heuristica-Bold.woff                                 | Bin 0 -> 106188 bytes
 spec/public/fonts/Heuristica-BoldItalic.woff                           | Bin 0 -> 104316 bytes
 spec/public/fonts/Heuristica-Regular.woff                              | Bin 0 -> 141416 bytes
 spec/public/fonts/Heuristica-RegularItalic.woff                        | Bin 0 -> 104700 bytes
 spec/public/fonts/LuxiMono-Bold.woff                                   | Bin 0 -> 26560 bytes
 spec/public/fonts/LuxiMono-BoldOblique.woff                            | Bin 0 -> 29480 bytes
 spec/public/fonts/LuxiMono-Regular.woff                                | Bin 0 -> 26432 bytes
 spec/public/fonts/LuxiMono-RegularOblique.woff                         | Bin 0 -> 29300 bytes
 spec/public/fonts/LuxiSans-Bold.woff                                   | Bin 0 -> 13592 bytes
 spec/public/fonts/LuxiSans-Regular.woff                                | Bin 0 -> 13568 bytes
 spec/public/images/github-logo@2x.png                                  | Bin 0 -> 1753 bytes
 spec/public/images/scala-logo-red-spiral-dark.png                      | Bin 13021 -> 0 bytes
 spec/public/images/scala-spiral-white.png                              | Bin 0 -> 1442 bytes
 spec/public/{highlight/LICENSE => scripts/LICENSE-highlight}           |   4 +-
 spec/public/scripts/LICENSE-toc                                        |  18 +
 spec/public/{highlight => scripts}/highlight.pack.js                   |   0
 spec/public/scripts/main.js                                            |  57 +++
 spec/public/scripts/navigation.js                                      |  70 ---
 spec/public/scripts/toc.js                                             | 128 +++++
 spec/public/stylesheets/fonts.css                                      |  73 +++
 spec/public/stylesheets/screen-small.css                               |  57 +++
 spec/public/stylesheets/screen-toc.css                                 |  37 ++
 spec/public/stylesheets/screen.css                                     | 225 ++++++---
 src/compiler/scala/reflect/quasiquotes/Reifiers.scala                  |   2 +-
 src/compiler/scala/tools/ant/templates/tool-unix.tmpl                  |  10 +-
 src/compiler/scala/tools/nsc/PhaseAssembly.scala                       |   2 +-
 src/compiler/scala/tools/nsc/ast/parser/Parsers.scala                  |   2 +-
 src/compiler/scala/tools/nsc/backend/icode/ICodeCheckers.scala         |   8 +-
 .../scala/tools/nsc/backend/icode/analysis/TypeFlowAnalysis.scala      |   2 +-
 src/compiler/scala/tools/nsc/backend/jvm/BCodeAsmCommon.scala          |   6 +-
 src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala                  |   2 +-
 src/compiler/scala/tools/nsc/backend/opt/DeadCodeElimination.scala     |   4 +-
 src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala    |  10 +-
 src/compiler/scala/tools/nsc/transform/Constructors.scala              |   2 +-
 src/compiler/scala/tools/nsc/transform/Delambdafy.scala                |   4 +-
 src/compiler/scala/tools/nsc/transform/LazyVals.scala                  |   2 +-
 src/compiler/scala/tools/nsc/transform/Mixin.scala                     |   4 +-
 src/compiler/scala/tools/nsc/transform/SampleTransform.scala           |   2 +-
 src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala           |   4 +-
 src/compiler/scala/tools/nsc/typechecker/AnalyzerPlugins.scala         |   2 +-
 src/compiler/scala/tools/nsc/typechecker/Contexts.scala                |   8 +-
 src/compiler/scala/tools/nsc/typechecker/Infer.scala                   |   2 +-
 src/compiler/scala/tools/nsc/typechecker/Namers.scala                  |   2 +-
 src/compiler/scala/tools/nsc/typechecker/RefChecks.scala               |   2 +-
 src/compiler/scala/tools/nsc/typechecker/Typers.scala                  |   2 +-
 src/interactive/scala/tools/nsc/interactive/CompilerControl.scala      |   2 +-
 src/interactive/scala/tools/nsc/interactive/Global.scala               |   2 +-
 src/interactive/scala/tools/nsc/interactive/Lexer.scala                |   2 +-
 src/library/scala/Mutable.scala                                        |   2 +-
 src/library/scala/Predef.scala                                         |   4 +-
 src/library/scala/collection/SeqLike.scala                             |   2 +-
 src/library/scala/collection/concurrent/Map.scala                      |   2 +-
 src/library/scala/collection/immutable/Stream.scala                    |   2 +-
 src/library/scala/collection/mutable/AVLTree.scala                     |   4 +-
 src/library/scala/collection/mutable/HashTable.scala                   |   2 +-
 src/library/scala/collection/mutable/UnrolledBuffer.scala              |  14 +-
 src/library/scala/collection/mutable/WrappedArray.scala                |   2 +-
 src/library/scala/concurrent/JavaConversions.scala                     |   2 +-
 src/library/scala/concurrent/duration/Duration.scala                   |   5 +-
 src/library/scala/math/BigDecimal.scala                                |   2 +-
 src/library/scala/sys/process/BasicIO.scala                            |   2 +-
 src/library/scala/sys/process/ProcessLogger.scala                      |   2 +-
 src/library/scala/util/control/Exception.scala                         |   2 +-
 src/library/scala/util/hashing/MurmurHash3.scala                       |   2 +-
 src/library/scala/util/matching/Regex.scala                            |   2 +-
 src/partest-extras/scala/tools/partest/ASMConverters.scala             |   2 +-
 src/reflect/scala/reflect/api/Quasiquotes.scala                        |   2 +-
 src/reflect/scala/reflect/internal/Definitions.scala                   |   2 +-
 src/reflect/scala/reflect/internal/ReificationSupport.scala            |   2 +-
 src/reflect/scala/reflect/internal/Symbols.scala                       |   2 +-
 src/reflect/scala/reflect/internal/TreeGen.scala                       |   2 +-
 src/reflect/scala/reflect/internal/Types.scala                         |   4 +-
 src/reflect/scala/reflect/internal/tpe/FindMembers.scala               |   2 +-
 src/repl/scala/tools/nsc/interpreter/ConsoleReaderHelper.scala         |  15 +-
 src/scaladoc/scala/tools/nsc/doc/Index.scala                           |   2 +
 src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala                |   2 +
 src/scaladoc/scala/tools/nsc/doc/html/page/DeprecatedIndex.scala       |  58 +++
 src/scaladoc/scala/tools/nsc/doc/html/page/Index.scala                 |   7 +-
 src/scaladoc/scala/tools/nsc/doc/model/IndexModelFactory.scala         |   8 +-
 test/files/jvm/inner.scala                                             |   2 +-
 test/files/jvm/javaReflection/Test.scala                               |   4 +-
 test/files/pos/t7815.scala                                             |   2 +-
 test/files/run/classfile-format-51.scala                               |   2 +-
 test/files/run/classfile-format-52.scala                               |   2 +-
 test/files/run/t7741a/Test.scala                                       |   2 +-
 test/files/run/t9268.check                                             |   5 +
 test/files/run/t9268/Java.java                                         |  12 +
 test/files/run/t9268/Test.scala                                        |  40 ++
 test/files/run/valueClassSelfType.scala                                |  52 ++
 test/junit/scala/collection/mutable/UnrolledBufferTest.scala           |  25 +
 test/junit/scala/collection/mutable/VectorTest.scala                   |   1 -
 test/junit/scala/concurrent/duration/SerializationTest.scala           |  24 +
 test/junit/scala/tools/nsc/backend/jvm/opt/InlinerTest.scala           |   2 +-
 test/junit/scala/tools/nsc/interpreter/TabulatorTest.scala             |  20 +
 test/pending/jvm/javasigs.scala                                        |   2 +-
 test/scaladoc/resources/SI-4476.scala                                  |   9 +
 test/scaladoc/resources/Trac4420.scala                                 |   2 +-
 test/scaladoc/scalacheck/DeprecatedIndexTest.scala                     |  50 ++
 test/scaladoc/scalacheck/IndexTest.scala                               |   8 +-
 tools/scaladoc-compare                                                 |   2 +-
 127 files changed, 2561 insertions(+), 575 deletions(-)
 create mode 100644 build.sbt
 create mode 100644 compare-build-dirs-ignore-patterns
 create mode 100755 compare-build-dirs.sh
 create mode 100644 project/ScalaTool.scala
 create mode 100644 project/build.properties
 create mode 100644 project/plugins.sbt
 rename spec/{07-implicit-parameters-and-views.md => 07-implicits.md} (99%)
 rename spec/{11-user-defined-annotations.md => 11-annotations.md} (89%)
 create mode 100644 spec/15-changelog.md
 create mode 100644 spec/public/fonts/Heuristica-Bold.woff
 create mode 100644 spec/public/fonts/Heuristica-BoldItalic.woff
 create mode 100644 spec/public/fonts/Heuristica-Regular.woff
 create mode 100644 spec/public/fonts/Heuristica-RegularItalic.woff
 create mode 100644 spec/public/fonts/LuxiMono-Bold.woff
 create mode 100644 spec/public/fonts/LuxiMono-BoldOblique.woff
 create mode 100644 spec/public/fonts/LuxiMono-Regular.woff
 create mode 100644 spec/public/fonts/LuxiMono-RegularOblique.woff
 create mode 100644 spec/public/fonts/LuxiSans-Bold.woff
 create mode 100644 spec/public/fonts/LuxiSans-Regular.woff
 create mode 100644 spec/public/images/github-logo@2x.png
 delete mode 100644 spec/public/images/scala-logo-red-spiral-dark.png
 create mode 100644 spec/public/images/scala-spiral-white.png
 rename spec/public/{highlight/LICENSE => scripts/LICENSE-highlight} (98%)
 create mode 100644 spec/public/scripts/LICENSE-toc
 rename spec/public/{highlight => scripts}/highlight.pack.js (100%)
 create mode 100644 spec/public/scripts/main.js
 delete mode 100644 spec/public/scripts/navigation.js
 create mode 100644 spec/public/scripts/toc.js
 create mode 100644 spec/public/stylesheets/fonts.css
 create mode 100644 spec/public/stylesheets/screen-small.css
 create mode 100644 spec/public/stylesheets/screen-toc.css
 create mode 100755 src/scaladoc/scala/tools/nsc/doc/html/page/DeprecatedIndex.scala
 create mode 100644 test/files/run/t9268.check
 create mode 100644 test/files/run/t9268/Java.java
 create mode 100644 test/files/run/t9268/Test.scala
 create mode 100644 test/files/run/valueClassSelfType.scala
 create mode 100644 test/junit/scala/collection/mutable/UnrolledBufferTest.scala
 create mode 100644 test/junit/scala/concurrent/duration/SerializationTest.scala
 create mode 100644 test/scaladoc/resources/SI-4476.scala
 create mode 100644 test/scaladoc/scalacheck/DeprecatedIndexTest.scala
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @lrytz

**Comment by lrytz** [comment]
uuh, it's building all the sbt commits :(

maybe add `[ci: last-only]` to the pr title? https://github.com/scala/scala/pull/4455

**Comment by lrytz** [comment]
see the queue on https://scala-ci.typesafe.com/

**Comment by lrytz** [comment]
i'll close this and abort the jenkins jobs..

**Comment by lrytz** [comment]
re-submitted as #4480

**Pull request closed without merging**
