### PR TITLE
[WIP] Improve performance of traversing functions

### PR DESCRIPTION
**Pull request by pkukielka**
<sup>THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.
ONLY THE SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE, IF ANY, THAT ARE ATTACHED TO (OR OTHERWISE ACCOMPANY) THIS SUBMISSION (AND ORDINARY COURSE CONTRIBUTIONS OF FUTURES PATCHES THERETO) ARE TO BE CONSIDERED A CONTRIBUTION. NO OTHER SOFTWARE CODE OR MATERIALS ARE A CONTRIBUTION.</sup>

`mapOver` is one of the most often used methods in the typer.
It can be see very often and high on the list which we did when profiling [collections usage](https://raw.githubusercontent.com/pkukielka/scala-collections-usage/master/run1/invoked.csv) during build of akka-actor.
Also when I was profiling compilation with YourKit it showed that `mapOver` **took 18% of compilation time with over 5.5 millions of calls**.
Of course much of that time can be spend in the function used for mapping, but with so many calls even slight improvement to `mapOver` itself could be significant.

So I was looking at `mapOver` and its usage and noticed we are using it also for traversal.
But in this case all results from `mapOver` are unused.
That means that everything we do to create output types is unnecessary.
I tried to create simplified version of `mapOver` which would take that into consideration, and use it in all places where we don't care about mapped type. This should reduce both cpu cycles and memory pressure.
According to my tests during akka-actor compilation that new simplified `traverseOver` function is called **~3.5 millions** of times.

More detailed benchmarks will follow, but I would like to hear your opinion on this first.

### CODE REVIEW

**Comment by retronym** [comment]
mapOver, when used within a Traverser, doesn’t (or shouldn’t!) create new types, but rather return the input type. So I’m not convinced this will save allocations. The code is slightly simpler than the more general code in mapOver that has been copied, so there might be a perf benefit. I look forward to the benchmarks. 

Also be aware that mapOver has been refactored into a virtual method on the 2.13  branch. We’ll have to repeat benchmarking over there. It might make more sense to start the work there

**Comment by pkukielka** [comment]
@retronym you are right about copying, I just checked it exactly and for traversing functions the same value is not returned just in ~7000 cases. 
I will try to get some benchmarks today but I need to run quite a few of them to be sure (variance in compilation time normally can be up to few percent so it creates a lot of noise).

**Comment by pkukielka** [comment]
@retronym 
Since difference in speed is not very huge it's very hard to measure just by checking full compilation time. Because of that I have run `traverseOver` and `mapOver` in the loop.

More or less it looks like that:
```
after 0 best 90%, phase typer
                 Run Name          Cycle     samples           Wall time (ms)               All Wall time (ms)                 CPU(ms)                 Idle time (ms)        Allocated(MBs)
                     base              1          27      76,745.44 [-4.34% +3.65%]     76,745.44 [-4.34% +3.65%]     75,021.15 [-4.22% +2.78%]     0.00 [ NaN%  NaN%]    10,676.78 [-0.01% +0.02%]
                 improved              1          27      69,839.93 [-4.59% +3.73%]     69,839.93 [-4.59% +3.73%]     68,086.44 [-3.78% +3.52%]     0.00 [ NaN%  NaN%]    10,673.92 [-0.01% +0.01%]
```

```
after 0 best 90%, phase typer
                 Run Name          Cycle     samples           Wall time (ms)               All Wall time (ms)                  CPU(ms)                Idle time (ms)        Allocated(MBs)
             traverseOver              1             27   5,122.81 [-12.43% +20.85%]    5,122.81 [-12.43% +20.85%]    5,099.30 [-11.99% +21.39%]    0.00 [ NaN%  NaN%]    483.40 [-0.17% +0.23%]
```

So with added loops `traverseOver` was around 10% faster than `mapOver`.
Since it took 13.6 times more to execute than without loops, looks like real difference is around 0.7%.
Of course this is probably not fully scientifically correct, but should give us good estimate.

**Comment by retronym** [comment]
> Because of that I have run traverseOver and mapOver in the loop.

Could you share the benchmark?

**Comment by retronym** [comment]
Might I suggest that we move this work over to the 2.13.x branch? 

My reasons for this are:

  - the implementation of `mapOver` has been refactored heavily in that branch, and in the new formulation the duplication between the existing and proposed code would be okay, because we'd have pairs of small methods in `TypeRef`, `ExistentialType`, etc, so we'd be more likely to keep them in sync.
  - the performance gain seems pretty marginal, so the risk, albeit small, of making this change on 2.12.x doesn't seem worth it to me.

**Comment by pkukielka** [comment]
@retronym I created version for 2.13: https://github.com/scala/scala/pull/6426

**Pull request closed without merging**
