### PR TITLE
SI-6879 improves Context.freshName

### PR DESCRIPTION
**Pull request by xeno-by**
Instead of per-compilation unit unique counters, the freshName API now
uses a per-Global counter. Fresh names now also contain dollars to exclude
clashes with supported user-defined names (the ones without dollar signs).

This doesn’t fix the bug, because per-Global counters get created anew
every time a new Global is instantiated, and that provides some potential
for name clashes even for def macros, but at least it completely excludes
clashes in typical situations.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym /cc @densh

**Comment by retronym** [comment]
Does this apply to the full compiler, or just fresh names in macros? I'd be concerned about the former; I expect this could create (more) instability in mangled names in, for example, protected accessors. (Just using that example as I saw a use of freshname there recently while working on 8642a50da.)

**Comment by xeno-by** [comment]
The only client of `globalFreshNameCreator` is scala.reflect.macros.Names, so this is only going to affect macros.

**Comment by densh** [comment]
To be more precise: this will affect macros and quasiquotes at runtime but should not affect compiler.

**Comment by retronym** [comment]
Looks sensible.

LGTM

**Comment by retronym** [comment]
@xeno-by / @densh This change conflicts with my [current work](https://github.com/retronym/scalac-stability/issues/1) to make scalac output stable (e.g. same output regardless of order of source files or regardless of separate compilation of subsets of the source files.)

Neither https://github.com/scala/bug/issues/6879 nor https://groups.google.com/forum/#!topic/scala-internals/aE81MVdIhCk provides me with a motivating example to show that fresh-counters-per-compilation-unit is too fine-grained for macros. Surely this would only be an issue if snippets of code expanded by macros/quasiquotes in different compilation units were inlined together, untypechecked, then retypechecked. Is that use case actually possible?

My [proposal](https://github.com/scala/scala/compare/2.13.x...retronym:topic/stable-output?expand=1) is to to make all typer-generate fresh names (including macro and quasiquote) use a counter scoped at the closest enclosing "source method".

**Pull request merged**
