### PR TITLE
specialized `ValueOf`

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
scala/bug#11489

### CODE REVIEW

**Comment by jxnu-liguobin** [comment]
The `VerifyError` error was obtained. Did it lead to binary incompatibility? @SethTisue

**Comment by SethTisue** [comment]
@jxnu-liguobin I think we passed over this because it's still marked as draft. I see that there isn't a `VerifyError` anymore. Do you believe this is ready for review?

The CI failure will go away if you squash/rebase into a single commit.

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin I think we passed over this because it's still marked as draft. I see that there isn't a `VerifyError` anymore. Do you believe this is ready for review?
> 
> The CI failure will go away if you squash/rebase into a single commit.

I am not sure, the initial modification obtained `verifyError`, and then I abbreviated the scope of PR influence (making the conditions more stringent), but I'm not sure whether it is reasonable. So it didn't continue.

**Comment by SethTisue** [comment]
Closing for inactivity, since this seems stalled. (As always, we can reopen a stale PR if activity resumes.)

**Pull request closed without merging**
