### PR TITLE
SI-8627 make Stream.filterNot non-eager

### PR DESCRIPTION
**Pull request by lrytz**
The obvious fix, overriding `filterNot` in Stream, is not binary
compatible, see https://github.com/scala/scala/pull/3925

Instead, this makes `filterImpl` in TaversableLike private[scala],
which allows overriding it in Stream. The corresponding mima-failures
can be whitelisted, as the changes are only to private[scala].

In 2.12.x we can remove the override of `filter` in Stream, but in
2.11.x this is not binary compatible.

Eventually we'd also like to make filter / filterNot in
TraversableLike final, but that's not source compatible, so it cannot
be done in 2.12.x.

### CODE REVIEW

**Comment by lrytz** [comment]
Oh, I realize this is not binary compatible, because of mixin.

**Comment by lrytz** [comment]
Hm, actually, I'm not sure. Maybe this is OK. The mixed-in `filterImpl` methods are only ever called from within the collection library, but never from client code. So if you replace the scala library on the classpath, client code should always work. @gkossakowski wdyt?

**Comment by Ichoran** [comment]
@lrytz - It sounds to me like this should work, but if not it can certainly be caught via type-casting and putting the logic in TraversableLike.  I'm extremely reluctant to do that, though, given how much of a hack it is.

**Comment by gkossakowski** [comment]
@lrytz, yes your change is safe BC-wise for the reason you have given: scala-library is just one piece that can be replaced just entirely.

**Comment by lrytz** [comment]
So LGTY?

**Comment by gkossakowski** [comment]
Yep. LGTM.

**Comment by xuwei-k** [comment]
https://issues.scala-lang.org/browse/SI-8899
https://github.com/xuwei-k/SI-8899

**Pull request merged**
