### PR TITLE
SBT compiler interface now compiled in ant build.  Ensures those still u...

### PR DESCRIPTION
**Pull request by jsuereth**
...sing ant don't break the interface.

Review by @harrah, @xeno-by, @lrytz and anyone else interested.  

Note: This will break the build until Eugene's pull request is merged.

### CODE REVIEW

**Comment by lrytz** [comment]
Just checking: are you aware we already had https://scala-webapps.epfl.ch/jenkins/job/run-sbt-on-scala-snapshot/ ?

**Comment by lrytz** [comment]
I'm not saying we should not put your patch in, early prevention is probably better in this case.

**Comment by jsuereth** [comment]
@lrytz  This is for all the tests we have to prevent breakage to currently-released SBT.  It's going to force us to knowingly break dependent APIs.  With the release of zinc, maven, sbt + other build tools will all be depending on this interface, so it's going to be vital for us migrate with care.

**Comment by xeno-by** [comment]
Who will be responsible for updating compiler-interface? If we need to change compiler-interface, what's the procedure? How much downtime will this procedure cause?

**Comment by lrytz** [comment]
As fas as I understand: you're not supposed to change compiler-interface - the compiler-interface is supposed to change you(r code)!

**Comment by xeno-by** [comment]
I mean what do I do if I need to break compiler-interface?

**Comment by lrytz** [comment]
i think that part is not yet sorted out, so the goal of this pull request is to make sure we don't break it.

**Comment by xeno-by** [comment]
Then I don't like where this is going. We're not yet done polishing reflection, and I don't fancy having my hands tied.

**Comment by lrytz** [comment]
This pull request is not creating new constraints - it's just asserting we don't break existing ones. We'll discuss in the meeting tomorrow about a solution.

**Comment by jsuereth** [comment]
@xeno-by IT's too late to pretend we're not already tied by this interface.  If you used SBT full-time, you would have seen the problem already.   This just makes us fully aware of it.

FOR NOW, let's tie our hands by this.  You need to feed back fixes to SBT itself.  That involves a discussion between You/Scala, Me/The Diplomat and Mark/SBT.  Once we figure out how to proceed, we can.   However, SBT 0.12 was already released and if Scala 2.10 doesn't work with it, it's alienating a good portion of our users.   It also means I can't run the community build, which is our gatekeeper for release at this point.

The reality is we're _already in_ this situation.   Let's get 2.10.x out, and then _fix_ SBT/Scala or whatever is needed to avoid lock-down in the future.   We don't have enough resources for any solution but "don't move things around too much".  I hope that changes soon, but it's not something I control.

**Comment by jsuereth** [comment]
SO, do I have a LGTM?  I'd like to get this in ASAP to prevent any further breakages

**Comment by xeno-by** [comment]
yep LGTM

**Pull request merged**
