### PR TITLE
SI-7880 Fix infinite loop in ResizableArray#ensureSize

### PR DESCRIPTION
**Pull request by soc**
This issue was triggered for values greater than Int.MaxValue/2, which
caused the computation of the new array size to overflow and become
negative, leading to an infinite loop.

### CODE REVIEW

**Comment by soc** [comment]
I tried adding a test, but there seems to be no reasonable approach which wouldn't prevent the test from running/failing on machines with not enough memory (which seems to be considerably more than expected):

E. g.

```
import collection.mutable.ArrayBuffer
ArrayBuffer.fill(Int.MaxValue/2 +1)(0)
res0.append(1)
```

... fails ...

```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
  at scala.collection.mutable.ResizableArray$class.ensureSize(ResizableArray.scala:101)
  at scala.collection.mutable.ArrayBuffer.ensureSize(ArrayBuffer.scala:48)
  at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:99)
  at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
  at scala.collection.mutable.BufferLike$class.appendAll(BufferLike.scala:148)
  at scala.collection.mutable.AbstractBuffer.appendAll(Buffer.scala:49)
  at scala.collection.mutable.BufferLike$class.append(BufferLike.scala:143)
  at scala.collection.mutable.AbstractBuffer.append(Buffer.scala:49)
  ... 24 elided
```

... even with `-Xmx8G` on my machine.

**Comment by paulp** [comment]
```
scala> try { ArrayBuffer.fill(Int.MaxValue/2 +1)(0) ; sys.error("failed") } catch { case _: OutOfMemoryError => println("Success!") }
Success!
```

That's right, OutOfMemoryError == success. You win.

**Comment by paulp** [comment]
Actually I guess you can put "success" in both branches, and let timing out be the failure.

**Comment by soc** [comment]
Is there some kind of time out mechanism in partest?

**Comment by paulp** [comment]
Yes. Anyone's guess whether it works at any given point in time, but it's definitely there and definitely sometimes works. The entire test run might have to time out, but I don't think that's a big deal given that it'll fail somewhere around never.

**Comment by soc** [comment]
Added test. Review by @adriaanm, please!

**Comment by retronym** [comment]
LGTM

**Pull request merged**
