### PR TITLE
[backport][no-merge] Fix crash in -Xsource:3 varargs

### PR DESCRIPTION
**Pull request by som-snytt**
Fix crash in -Xsource:3 varargs.

### CODE REVIEW

**Comment by lrytz** [comment]
```
[error] /home/jenkins/workspace/scala-2.12.x-validate-main/src/reflect/scala/reflect/internal/Trees.scala:1250:27: ')' expected but identifier found.
[error]       case Seq(_, rest @ _*) => Block(stats.init.toList, stats.last)
[error]                           ^
```

**Comment by som-snytt** [comment]
Yes, sorry I did it wrong in earlier haste. I'll have a chance to switch branches in a little while.

**Comment by lrytz** [comment]
Thank you!

**Comment by SethTisue** [comment]
@som-snytt what is this a backport of?

**Comment by som-snytt** [comment]
The linked issue https://github.com/scala/bug/issues/12415

That was such a quickie, I don't remember it.

**Comment by SethTisue** [comment]
Ah, https://github.com/scala/scala/pull/9669

Okay. Mind updating the PR description on both PRs to something user-facing?

**Pull request merged**
