### PR TITLE
Implemented updatedWith in immutable Map.

### PR DESCRIPTION
**Pull request by michaeldaou**
See issue: https://github.com/scala/bug/issues/10949

### CODE REVIEW

**Comment by julienrf** [comment]
Hey @michaeldaou would you have time to add some tests?

**Comment by michaeldaou** [comment]
Yep I’ll be on it ASAP.

**Comment by szeiger** [comment]
I agree with the comments on the original ticket that this operation is too obscure. It should go into collections-contrib.

**Comment by julienrf** [comment]
OK, I’m closing it, then. Sorry @michaeldaou, thanks again for your work.

**Comment by AjBreidenbach** [comment]
Coming to scala from clojure, it's hard to understand why this function would be considered obscure.

**Comment by som-snytt** [comment]
There are more germane comments on the original PR to the superseding ticket.

**Pull request closed without merging**
