### PR TITLE
Deprecation of @BeanInfo

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
LGTM -- can you also create a ticket so that we don't forget to mention this in the 2.12 release notes? It should have the label deprecation, and the title should read like a bullet item in the release notes.

**Comment by retronym** [comment]
Better yet, let's start the 2.12 release notes.

**Comment by adriaanm** [comment]
Agreed. @lrytz, could you create 2.12.x branch over at make-release-notes? 

Longer term, it would be great to have JIRA & GitHub integration (could reuse the api code in typesafehub/ghpullrequest-validator and adriaanm/bbj) and some kind of templating so we can generate release notes more flexibly. I don't like the current automation because it generates really verbose notes. I'd rather link to jira/github for long lists, and just summarize them automatically in the release notes.

**Comment by lrytz** [comment]
I added it to the release notes. Should I still create a ticket, or is it enough to link to the PR?

**Comment by adriaanm** [comment]
Linking to the PR is fine with me.

**Pull request merged**
