### PR TITLE
Revert deprecations that break SBT

### PR DESCRIPTION
**Pull request by retronym**
This reverts commit 7e9c21ffd38711c23f89b5650cc5a32cafe4cd20.

This is still used by SBT; we'll give it a touch longer
to switch to Murmur3.

Also partially reverts ac990c1bc.

Review by @soc @huitseeker

### CODE REVIEW

**Comment by jsuereth** [comment]
Hey guys! -> SBT is relying on this class, which means for the IDE to build against 2.11.x, we need it back in master.   @harrah is currently on vacation, but once he's back we'll make sure SBT 0.13.x branch is up to speed for scala 2.11, and this can be removed again.

Sorry for the delay, but boy am I glad we're starting to see these things ripple down to projects before a full release!

**Comment by jsuereth** [comment]
Also, @retronym this LGTM

**Comment by huitseeker** [comment]
LGTM ! The revert should give SBT more room to breathe, and let the IDE (make PR validation) build(s) in the meantime.

**Comment by huitseeker** [comment]
LGTM again !

**Comment by gkossakowski** [comment]
@jsuereth: i tried to get rid of dependency on those deprecated hashing functionality but as long as sbt supports 2.9 we can't.

**Comment by retronym** [comment]
I'd suggest to just copy/paste MurmurHash into the SBT project.

**Comment by soc** [comment]
LGTM, good to see that a note was added to the code to make the next person aware of the issue.

**Pull request merged**
