### PR TITLE
Don't compute least upper bounds for if-like expressions in statement positions ...

### PR DESCRIPTION
**Pull request by dragos**
...inside blocks.

This may save huge amount of time (Fixes SI-5862) for complicated lubs. I had to remove the a check in adapt for
the part that transforms `<expr>` into { `<expr>`; () } when the expected type is Unit. The reason is in the 
code.

As a side effect, we get more warnings for pure expressions in statement positions (see the change in the test file).

Review by @odersky, @adriaanm.

### CODE REVIEW

**Comment by dragos** [comment]
@odersky sure, that is a good point. I'll add the comments and re-open the pull request when I fix the failing test.

**Comment by adriaanm** [comment]
please squash these commits and push -f to your pullreq branch (no need to submit a new request)
each commit should pass the test suite

**Comment by dragos** [comment]
done.

**Comment by adriaanm** [comment]
(reviewed by odersky, but comment was discarded due to the push -f I asked for)

**Pull request merged**
