### PR TITLE
SI-7006 Eliminate NOPs and unreachable code

### PR DESCRIPTION
**Pull request by JamesIry**
We were generating NOPs in two cases

1) If jump elision failed to eliminate a JUMP-only block that happened to JUMP to its next block then the code emitter would spit out a NOP. The answer was to fix jump elision to catch more jump-only blocks. Along the way a O(N*M) method was reduced to O(N)

2) Partly from jump elision and partly from other sources we were leaving behind unreachable code. ASM turned that into NOPs. The answer here was to get rid of the unreachable exception handler elision that would leave behind other unreachable code and replace it with full blown (and simpler) unreachable block elision.

PR is broken into several commits to make review a bit easier.

### CODE REVIEW

**Comment by JamesIry** [comment]
PLS SYNCH

**Comment by JamesIry** [comment]
review @gkossakowski

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
It seems like your branch became stale so you need to merge master into your branch.

I reviewed all other commits and they all get LGTM. Its' a great work!
I'm happy to review the merge commit and then push your PR through.

**Comment by JamesIry** [comment]
Yeah, @retronym did a big cleanup that that's creating small conflicts.

**Comment by gkossakowski** [comment]
LGTM.

@JamesIry: in the future I think for non-trivial patches I prefer merge instead of rebase. Otherwise I have to start reviewing from scratch instead of just reviewing merge conflict resolution.

**Comment by gkossakowski** [comment]
I'll merge as soon as all tests pass.

**Pull request merged**
