### PR TITLE
Read version 51 (JDK 7) class files.

### PR DESCRIPTION
**Pull request by JamesIry**
This commit makes the ClassFileReader/ICodeReader parse class files
from JDK 7 (class file version 51). It does that by skipping over
the method handle related entries in the constant pool and by doing
some dummy processing on invoke dynamic instructions. The inliner
is updated to not try to inline a method with an invoke dynamic
instruction. A place holder INVOKE_DYNAMIC instruction is added to ICode
but it is designed to create an error if there's ever any attempt to
analyze it. Because the inliner is the only phase that ever tries
to analyze ICode instructions not generated from Scala source and
because Scala source will never emit an INVOKE_DYNAMIC, the place
holder INVOKE_DYNAMIC should never cause any errors.

A test is included that generates a class file with INVOKE_DYNAMIC
and then compiles Scala code that depends on it.

### CODE REVIEW

**Comment by adriaanm** [comment]
Can the placeholder be encountered when inline Java-produced bytecode?

**Comment by JamesIry** [comment]
During class file reading a flag is set on a method if a jvm invoke dynamic instruction is encountered. The inliner checks that flag before attempting to analyze a method.

**Comment by JamesIry** [comment]
review @adriaanm . Should we consider sticking this in the 2.10.x branch?

**Comment by adriaanm** [comment]
Yes, as long as we're merging 2.10.x into master, I think we should do the work of interoperating with Java 7/8 on 2.10.x where possible.

**Pull request closed without merging**
