### PR TITLE
merge the patmat refactoring into master

### PR DESCRIPTION
**Pull request by adriaanm**
see #2120 -- nothing to see here but the merge commits:

``` patch
 -  def newTransformer(unit: CompilationUnit): Transformer =
 -    if (opt.virtPatmat) new MatchTransformer(unit)
 -    else noopTransformer
++  def newTransformer(unit: CompilationUnit): Transformer = new MatchTransformer(unit)
```

``` patch
+   // 2.10/2.11 compatibility
 -  protected final def dealiasWiden(tp: Type)   = tp.dealias                       // 2.11: dealiasWiden
 -  protected final def mkTRUE                   = CODE.TRUE_typed                  // 2.11: CODE.TRUE
 -  protected final def mkFALSE                  = CODE.FALSE_typed                 // 2.11: CODE.FALSE
 -  protected final def hasStableSymbol(p: Tree) = p.hasSymbol && p.symbol.isStable // 2.11: p.hasSymbolField && p.symbol.isStable
 -  protected final def devWarning(str: String)  = global.debugwarn(str)            // 2.11: omit
++  protected final def dealiasWiden(tp: Type)   = tp.dealiasWiden
++  protected final def mkTRUE                   = CODE.TRUE
++  protected final def mkFALSE                  = CODE.FALSE
++  protected final def hasStableSymbol(p: Tree) = p.hasSymbolField && p.symbol.isStable
```

### CODE REVIEW

**Comment by gkossakowski** [comment]
@adriaanm: Could we get 76f1673 as separate PR so we can resolve previous merge conflict independent from your refactorings and make jenkins job responsible for merges more happy?

Feel free to assign me as reviewer for that PR.
If you are wondering: github will figure out everything just fine if we do that.

**Comment by adriaanm** [comment]
it's pretty awesome that the commit stati carry over

**Comment by adriaanm** [comment]
see #2124 for the 2.10.x merge in isolation -- i assume once that's merged, the commit list here will get shorter

**Comment by gkossakowski** [comment]
@adriaanm: yes, that's awesome. Good job on kitten!

Now, I don't see shorter commit list which is weird. I'm used this features quite a few times before. Maybe this is a caching problem...

**Comment by adriaanm** [comment]
rebased on top of master to account for #2124

**Comment by JamesIry** [comment]
ping @gkossakowski

**Comment by gkossakowski** [comment]
@JamesIry: was I assigned as reviewer by @adriaanm?

I chimed in here just to suggest separating merging branches and actual patmat refactoring. I'm obviously fine to review if @adriaanm wants me to do it.

**Comment by JamesIry** [comment]
Nope, nobody was, so I spun the wheel of death.

**Comment by adriaanm** [comment]
I'm fine with whoever feels like reviewing it. It's really just moving code around, so anyone could do it.

**Comment by adriaanm** [comment]
there's one commit that is not marked as [refactor], which does some non-trivial simplification, but all the [refactor] commits are simply moving code around, etc.

**Comment by gkossakowski** [comment]
LGTM

All the refactoring was reviewed by @retronym in #2120 when merging to 2.10.x so my role here is diminished to merge conflict resolution which Looks Good To Me.

**Pull request merged**
