### PR TITLE
Fix emitting Array(1).clone() in GenBCode

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
`-Ybackend:GenBCode` build (without `-optimise`) running here: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1227/parameters/

The checkin-manual build now allows disabling optimise.

Review by @retronym

**Comment by retronym** [comment]
LGTM so long as you disable `-optimize` on a nightly build for `GenBCode`.

**Comment by retronym** [comment]
Oh, you've done that already.

**Comment by lrytz** [comment]
I did, they both failed beautifully this night.

**Comment by lrytz** [comment]
There were quite a number of test failures in the `-Ybackend:GenBCode` build. They are not introduced by this change though, but uncovered by the fact that we used the wrong compiler flags for testing before.
I merge this PR and will start working on the test failures.

**Pull request merged**
