### PR TITLE
SI-6439 Avoid spurious REPL warnings about companionship

### PR DESCRIPTION
**Pull request by retronym**
`val m` isn't a companion of `trait m`, check the pair of
eponymous symbols are a ((class|trait), object) pair before
emitting the warning.

In order to correctly check this one a type alias is involved,
`definedSymbols` must avoid normalizing through type aliases.
AFAICT this is an improvement to the other clients of that Map,
one such power mode progression is demonstrated at the end
of the test case.

Review by @paulp, /cc @som-snytt

### CODE REVIEW

**Comment by som-snytt** [comment]
2.10.x doesn't benefit from the MSRNR (Massively simplified repl name resolution), by the by.

I'm like, There's an apply method?

**Comment by paulp** [comment]
Lost the apply method in the great 'remove unused methods' purge in the interests of looking spectacularly impartial. Frequently regret this loss.

**Comment by paulp** [comment]
Looks good to me; but will have to be redone for master, which means if it's not done now it will be one of those surprises that mergers love to figure out. What do you say?

**Comment by som-snytt** [comment]
I will do it as part of SI-6980 for master, if that's kosher; but I was also concerned about backporting the other changes.

**Pull request merged**
