### PR TITLE
Eliminated lateMETHOD.

### PR DESCRIPTION
**Pull request by paulp**
Flushed out and documented some of the associated mysteries.

Review by @retronym.

### CODE REVIEW

**Comment by retronym** [comment]
```
scala> class C { object O }
defined class C
```

That part scares me a bit: under separate compilation the typer will see the module symbol as a method:

```
scala> exitingTyper(typeOf[c.O.type forSome { val c: C }].typeSymbol.module.isMethod)
warning: there were 1 feature warning(s); re-run with -feature for details
res8: Boolean = true // was false
```

Similarly, cloning that symbol results in a `MethodSymbol`:

```
scala> exitingTyper(typeOf[c.O.type forSome { val c: C }].typeSymbol.sourceModule.cloneSymbol).getClass
warning: there were 1 feature warning(s); re-run with -feature for details
res19: Class[_ <: $r.intp.global.Symbol#TypeOfClonedSymbol] = class scala.reflect.internal.Symbols$MethodSymbol // was ModuleSymbol
```

But, I can't provoke any problems on the back of this.

```
scala> val c = new C; def foo(cO: c.O.type) = cO; foo(c.O); import c.O._; c.O match { case c.O => }
c: C = C@27589aa5
foo: (cO: c.O.type)c.O.type
import c.O._
```

Can you allay my fears? I would prefer to eliminate differences between joint and separate compilation: can we set the METHOD flag earlier than `RefChecks`?

**Comment by paulp** [comment]
The clone-is-a-MethodSymbol issues looks like a pre-existing bug, with METHOD winning out over MODULE here where it should go the other way.

```
    final def newTermSymbol(name: TermName, pos: Position = NoPosition, newFlags: Long = 0L): TermSymbol = {
      if ((newFlags & METHOD) != 0)
        createMethodSymbol(name, pos, newFlags)
      else if ((newFlags & PACKAGE) != 0)
        createPackageSymbol(name, pos, newFlags | PackageFlags)
      else if ((newFlags & MODULE) != 0)
        createModuleSymbol(name, pos, newFlags)
      else if ((newFlags & PARAM) != 0)
        createValueParameterSymbol(name, pos, newFlags)
      else
        createValueMemberSymbol(name, pos, newFlags)
    }
```

I'll see what happens if I set METHOD when a nested module symbol is created.

**Comment by paulp** [comment]
Okay, clone is a ModuleSymbol again. I don't know how much earlier it's possible to set METHOD without digging into every spot that flag is used. I'm not too surprised if it doesn't cause any visible issues, because from the standpoint of the typer, I don't see how a stable method with a singleton type is any different from a module. The issues I run into trying it earlier are things like someone getting confused and putting an Apply(x, Nil) around a module, then realizing later that was a terrible mistake.

**Comment by paulp** [comment]
@retronym Where do you think I should go from here?

**Comment by retronym** [comment]
I'm still holding a little paranoia about potential for a separate compilation bug (a scenario that is somewhat under tested.) But that's as much due to my shallow knowledge of this area. I'll use this as an opportunity to fill in some gaps. Do you mind to sit on this one for another week? Or perhaps @adriaanm can chime in earlier?

**Comment by paulp** [comment]
I don't mind sitting on it. I just want to make sure I get most of the patch in even if we want to leave lateMETHOD alone.

**Comment by adriaanm** [comment]
I think @gkossakowski is best placed to estimate the impact on incremental compilation. I don't think the internal type of the symbol matters, as long as its flags, name and info are stable.

**Comment by retronym** [comment]
"I don't think the internal type of the symbol matters, as long as its flags, name and info are stable."

My specific concern is that the `METHOD` flag would unset during the typer phase for separate compilation, but set when compiling against the same module from a class file, and that this would trigger different behaviour. But perhaps the difference is benign.

**Comment by paulp** [comment]
Superseded by #2457.

**Pull request closed without merging**
