### PR TITLE
Now the test suite runs MIMA for compatibility testing.

### PR DESCRIPTION
**Pull request by jsuereth**
Failures are still not reported, thanks to MIMA not returnign non-0 exit codes on failure.  I'll be patching MiMA seprately, but at least
this will let us deal with failures in scala.   Currently, we need to adapt the Vector speed improvements for binary compatibility.

Review by @retronym

### CODE REVIEW

**Comment by jsuereth** [comment]
PLS REBUILD ALL

Thanks to @dotta for releasing new MIMA.  NOW the build breaks because we failed in binary compatibility.

**Comment by rkuhn** [comment]
Why not for the SBT build?

**Comment by xeno-by** [comment]
Is `scala-reflect.jar` excluded?

**Comment by jsuereth** [comment]
@xeno-by I haven't added it yet.  TBH - In the future I plan to only add features to SBT.   For now, this was in the hopper and needed to get in.  Feel free to enhance for scala-reflect as desired.

**Comment by adriaanm** [comment]
merging to get the ball rolling for scala-reflect

@xeno-by, could you please submit a follow-up PR that adds scala-reflect?

**Comment by xeno-by** [comment]
@adriaanm Will do.

**Pull request merged**
