### PR TITLE
Require and target Java 8

### PR DESCRIPTION
**Pull request by retronym**
- Require Java 8 in ant build
  - use -source 1.8 and -target 1.8 for javac
  - Default scalac's -target to `jvm-1.8`, ignore and deprecate attempts
    to use `jvm-1.{6.7}`
  - Remove fragile javap-app test. The feature itself is slated for removal.
  - Remove obsolete Java6 checkfile
  - Adapt DCE tests
    - Remove deprecated/redundant -target:jvm-1.6 from flags where the
      intent was to trigger generation of stack map frames.
  - Remove tests with -target:jvm-1.5 that tested without stack
    map frames

### CODE REVIEW

**Comment by retronym** [comment]
Needs Java 8 on Jenkins: https://github.com/scala/scala-jenkins-infra/pull/63, https://github.com/scala/scala-jenkins-infra/pull/64 and https://github.com/scala/scala-jenkins-infra/pull/65

**Comment by adriaanm** [comment]
Will need an upgrade for ant. http://stackoverflow.com/questions/23442621/ant-class-not-found-javac1-8

https://github.com/scala/scala-jenkins-infra/pull/65

**Comment by adriaanm** [comment]
Great, now we're failing because partest chokes on the OpenJDK VM warnings: https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/30/consoleFull

```
-OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
-OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
```

**Comment by adriaanm** [comment]
I'll rework

**Pull request closed without merging**
