### PR TITLE
Merge 2.12.x to 2.13.x [ci: last-only]

### PR DESCRIPTION
**Pull request by SethTisue**
I stopped at the point 2.12.8 was released, to see what Jenkins
thinks before continuing.

some manual merging was required, but there wasn't anything
problematic afaict

```
% git fetch origin; git checkout -b merge/2.12.x-to-2.13.x-20190128 origin/2.13.x
Branch 'merge/2.12.x-to-2.13.x-20190128' set up to track remote branch '2.13.x' from 'origin'.
Switched to a new branch 'merge/2.12.x-to-2.13.x-20190128'
% export MB=$(git merge-base origin/2.13.x origin/2.12.x)
% git log --oneline $MB..origin/2.12.x --graph --decorate | cat
*   dcd730fe81 (origin/2.12.x) Merge pull request #7679 from SethTisue/copyright-2018
|\
| * 60cf518caa bump copyright year to 2019
|/
*   7f1658e09a Merge pull request #7607 from smishmash/issue/11330
|\
| * 846ee2b1a4 [backport] 11330: Port fix for byte array hashcode
* |   d350c508d8 Merge pull request #7639 from diesalbla/bug_9485
|\ \
| * | 89287c4d1a Add regression test for Bugs 8584, 9485, 9963,
|/ /
* |   932b72ed75 Merge pull request #7599 from ashawley/rvm-2.2
|\ \
| * | b6fab5e6f3 Add caching for Ruby to Travis config
| * | 1a6c691ec0 Fix rvm in Travis config
| |/
* |   f6a28f0dc3 Merge pull request #7559 from ennru/extenstion-in-doc-source-url
|\ \
| |/
|/|
| * 9d792e0483 [backport] Scaladoc: Introduce new variables to create better links to source
|/
*   329deac9ab Merge pull request #7550 from wajda/2.12.x
|\
| * 49a7747765 Fix documentation on the Future.reduce() method
|/
*   a6692703aa Merge pull request #7459 from som-snytt/issue/11272-2.12
|\
| * 24d6fe8108 [squash] improve test
| * 75ceb79968 [no-merge] Iterator.flatMap clears reference
* |   00c135e0ed Merge pull request #7437 from ansvonwa/bug-11257
|\ \
| * | da229e1334 [nomerge] Fix bug in immutable.HashMap.split
* | |   14e043fccd Merge pull request #7483 from hrhino/t11277
|\ \ \
| * | | f98135015c Don't compactify Java inner class names.
| | |/
| |/|
* | |   7abb8dbcf5 Merge pull request #7493 from lrytz/bump-2.12.8
|\ \ \
| * | | 8b095a954b Bump starr to 2.12.8
|/ / /
* | |   38cd84d976 (tag: v2.12.8) Merge pull request #7469 from lrytz/b10812-2.12
|\ \ \
| |/ /
|/| |
| * | 3edeaac047 [backport] Don't emit forwarder in mirror class for bridge methods
|/ /
* |   25c7215844 Merge pull request #7429 from retronym/topic/rt-annotations
|\ \
| |/
|/|
| * 954c5d32d7 Stabilize order of annotations in the class file
* |   bd441b7b13 Merge pull request #7433 from retronym/backport/7313
|\ \
| * | 5e4d34aec8 [backport] Fix potential bugs in SpecializeTypes
|/ /
* |   068338b2fb Merge pull request #7428 from retronym/topic/null-safe-current-run-profile-trace
|\ \
| * | ca4b94f6a9 Make access to current run during Run.<init> safe for Global subclasses
| |/
* |   8f9fa5e336 Merge pull request #7422 from adriaanm/t11162
|\ \
| |/
|/|
| * 5f83efe507 Extractor type may depend on (implicit) arguments
|/
*   1e1a162980 Merge pull request #7383 from lrytz/b11207
|\
| * 8afd256521 [nomerge] No static forwarders for bridges implementing abstract methods
* |   85a82b022b Merge pull request #7407 from dwijnand/Apache-2.0-tail
|\ \
| * | b3ab8605c6 License.rtf parses
| * | c1e6ed6110 Finish re-licensing to Apache License 2.0
|/ /
* |   980655b9f5 Merge pull request #7381 from retronym/ticket/11235
|\ \
| * | f33d4e159e Fix crasher regression with implicit classes and default params
| |/
* |   49f65a5a75 Merge pull request #7394 from retronym/topic/strictfp-java-regression
|\ \
| * | eda5d59b3f Fix non-termination with java strictfp
|/ /
* | ff094cd40a Upgrade jekyll for spec
* |   5fca7b224f Merge pull request #7340 from adriaanm/eta-partial-212
|\ \
| * | 8dab041341 [backport] Review feedback
| * | 93cd804a78 [backport] Recover fun param types from (partial) eta-expansion
| * | 984502e54a [backport] Pull out `argsResProtosFromFun`,
| * | 9614c3a6d6 [backport] Do less in typedFunction after typer
| * | 210c296fbe [backport] Factor typedFunction.
|  /
* |   6da38fde13 Merge pull request #7376 from adriaanm/rework-7057
|\ \
| * | 5c90826c42 Ensure termination of BTS of RefinedType containing TypeVar
| * | d6de6d4705 TypeMap more conservative mapping over TypeVar
* | |   a76b7ce6e7 Merge pull request #7382 from retronym/topic/polysig-jep247
|\ \ \
| |_|/
|/| |
| * | 8d94ac63a7 Make detection of polymorphic signature methods work with -release 8
|/ /
* |   fc977031fe Merge pull request #7378 from adriaanm/faster/dev-warn-if
|\ \
| * | 0e36653901 Simplify implementation of isDeveloper
| * | 697701cb38 Don't evaluate devWarning conditions unless under -Xdev
| |/
* |   8b808152da Merge pull request #7347 from janekdb/issue/11166
|\ \
| * | 127c1ec399 When parsing a Scaladoc table do not consume non-table content
|  /
* |   ae8133c15c Merge pull request #7364 from retronym/topic/statify-chrome-trace
|\ \
| |/
|/|
| * 856c111449 Emit detailed compiler trace under -Yprofile-trace
|/
*   f4975a8c9f Merge pull request #7377 from hrhino/shame
|\
| * 46f0cfcbee fix jvm/strictfp checkfile now that compiler is deterministic
|/
*   bb1ce486df Merge pull request #7373 from hrhino/t11228
|\
| * bd82f0367b Put @implicitAmbiguous annotation on the getter, not the field
*   0f07cc18d3 Merge pull request #7370 from ashawley/option-doc
|\
| * f4f3fb6185 Add doc for Option.apply factory
* |   503dc14990 Merge pull request #7203 from retronym/backport/determinism
|\ \
| |/
|/|
| * 3dcbf474bd [forwardmerge] Rework change to scalap
| * e764204903 Make quasiquote pattern matching deterministic
| * f697224d28 Don't copy the OVERRIDE flag in refinement decls
| * 4e0cc97913 Defer parameter alias computation until the end of typechecking
| * e517c47508 Tone error down to a dev warning
| * f5c53edfaa Report an error on problematic use of unit.fresh
| * f50ec3c866 Stable names for lambda lifted method and fresh names
| * 99e8cda484 Update comment in test
| * 259a1cbf2d ConstructorDefault.defaults need not be a var
| * 9c08ebfef4 Eagerly enter default getters into scope
| * fc1e2f1f94 Refactor default getter synthesis
| * 1cff326767 Preserve order of decls through pickle/unpickle
| * e3722fa5b0 Refactor pickle phase
| * a7856fa51b scalap should not print class type param annots in decls
| * dd0b8c6d6f Unify scope lookup for companions and default getters
| * b79a623711 Fix lookup of default getter in scope
*   c4575fd03e Merge pull request #7356 from hrhino/t7954
|\
| * e412a12e31 More thorough treatment of @strictfp.
*   c0af89a13d Merge pull request #7363 from retronym/topic/print-args-plus-plus
|\
| * af46d2d94e Rework -Xprint-args to continue compiler and allow file output
* ed41f9659c Merge pull request #7314 from adriaanm/apache-backport
* 515916c42f [nomerge] Auto-update headers in `src/`
* 8baf5c3841 [nomerge] license headers for generated sources
* 7b02474c23 [nomerge] Apache License Version 2.0
% git merge -sours ed41f9659c
Merge made by the 'ours' strategy.
% git merge c4575fd03e
Auto-merging src/reflect/scala/reflect/internal/Symbols.scala
Auto-merging src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
Auto-merging src/compiler/scala/tools/nsc/javac/JavaParsers.scala
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
Auto-merging src/compiler/scala/tools/nsc/Global.scala
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1157 and retry the command.
Merge made by the 'recursive' strategy.
 src/compiler/scala/tools/nsc/CompilerCommand.scala               |  7 +----
 src/compiler/scala/tools/nsc/Global.scala                        | 16 ++++++++++
 src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala |  2 +-
 src/compiler/scala/tools/nsc/javac/JavaParsers.scala             |  4 ++-
 src/compiler/scala/tools/nsc/settings/ScalaSettings.scala        |  4 +--
 src/compiler/scala/tools/nsc/transform/ExtensionMethods.scala    |  4 +++
 src/reflect/scala/reflect/internal/Symbols.scala                 |  3 +-
 test/files/jvm/strictfp.check                                    | 33 ++++++++++++++++++++
 test/files/jvm/strictfp/Test_2.scala                             | 51 +++++++++++++++++++++++++++++++
 test/files/jvm/strictfp/strictfp_1.scala                         | 76 +++++++++++++++++++++++++++++++++++++++++++++++
 test/files/jvm/t7954.scala                                       | 14 +++++++++
 11 files changed, 203 insertions(+), 11 deletions(-)
 create mode 100644 test/files/jvm/strictfp.check
 create mode 100644 test/files/jvm/strictfp/Test_2.scala
 create mode 100644 test/files/jvm/strictfp/strictfp_1.scala
 create mode 100644 test/files/jvm/t7954.scala
% git merge -sours 503dc14990
Merge made by the 'ours' strategy.
% git merge 6da38fde13
Auto-merging src/scaladoc/scala/tools/nsc/doc/base/CommentFactoryBase.scala
Auto-merging src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
CONFLICT (content): Merge conflict in src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
Auto-merging src/reflect/scala/reflect/internal/Types.scala
CONFLICT (content): Merge conflict in src/reflect/scala/reflect/internal/Types.scala
Auto-merging src/reflect/scala/reflect/internal/SymbolTable.scala
CONFLICT (content): Merge conflict in src/reflect/scala/reflect/internal/SymbolTable.scala
Auto-merging src/reflect/scala/reflect/internal/Definitions.scala
Auto-merging src/reflect/scala/reflect/internal/BaseTypeSeqs.scala
CONFLICT (modify/delete): src/reflect/mima-filters/2.12.0.backwards.excludes deleted in HEAD and modified in 6da38fde13. Version 6da38fde13 of src/reflect/mima-filters/2.12.0.backwards.excludes left in tree.
Auto-merging src/library/scala/Option.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Typers.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/typechecker/Typers.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/PatternTypers.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Macros.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/Checkable.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/typechecker/Checkable.scala
Auto-merging src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala
Auto-merging src/compiler/scala/tools/nsc/transform/UnCurry.scala
Auto-merging src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
Auto-merging src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
Auto-merging src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
Auto-merging src/compiler/scala/tools/nsc/profile/Profiler.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/profile/Profiler.scala
Auto-merging src/compiler/scala/tools/nsc/Global.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/Global.scala
Auto-merging project/ScriptCommands.scala
CONFLICT (content): Merge conflict in project/ScriptCommands.scala
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1157 and retry the command.
Recorded preimage for 'project/ScriptCommands.scala'
Recorded preimage for 'src/compiler/scala/tools/nsc/Global.scala'
Recorded preimage for 'src/compiler/scala/tools/nsc/profile/Profiler.scala'
Recorded preimage for 'src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala'
Recorded preimage for 'src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala'
Recorded preimage for 'src/compiler/scala/tools/nsc/typechecker/Checkable.scala'
Recorded preimage for 'src/compiler/scala/tools/nsc/typechecker/Typers.scala'
Recorded preimage for 'src/reflect/scala/reflect/internal/SymbolTable.scala'
Recorded preimage for 'src/reflect/scala/reflect/internal/Types.scala'
Recorded preimage for 'src/reflect/scala/reflect/internal/tpe/TypeMaps.scala'
Automatic merge failed; fix conflicts and then commit the result.
% emacs   # manually resolve conflicts
% git add -u
% git commit
Recorded resolution for 'project/ScriptCommands.scala'.
Recorded resolution for 'src/compiler/scala/tools/nsc/Global.scala'.
Recorded preimage for 'src/compiler/scala/tools/nsc/profile/Profiler.scala'
Recorded resolution for 'src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala'.
Recorded resolution for 'src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala'.
Recorded resolution for 'src/compiler/scala/tools/nsc/typechecker/Checkable.scala'.
Recorded preimage for 'src/compiler/scala/tools/nsc/typechecker/Typers.scala'
Recorded resolution for 'src/reflect/scala/reflect/internal/SymbolTable.scala'.
Recorded resolution for 'src/reflect/scala/reflect/internal/Types.scala'.
Recorded resolution for 'src/reflect/scala/reflect/internal/tpe/TypeMaps.scala'.
[merge/2.12.x-to-2.13.x-20190128 03f15df5a9] Merge commit '6da38fde13' into merge/2.12.x-to-2.13.x-20190128
% git merge -sours 5fca7b224f
Merge made by the 'ours' strategy.
% git merge 85a82b022b
Auto-merging test/files/presentation/parse-invariants/Test.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/MethodSynthesis.scala
Auto-merging src/compiler/scala/tools/nsc/javac/JavaParsers.scala
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1157 and retry the command.
Merge made by the 'recursive' strategy.
 doc/License.rtf                                                 | 111 ++++++++++++++++++++++++++++++-----------------
 doc/README                                                      |   4 +-
 src/compiler/scala/tools/nsc/javac/JavaParsers.scala            |   1 +
 src/compiler/scala/tools/nsc/typechecker/MethodSynthesis.scala  |   7 +++
 src/manual/scala/man1/Command.scala                             |   2 +-
 test/files/jvm/strictfp/StrictFpJava.java                       |   5 +++
 test/files/presentation/parse-invariants.check                  |   7 +++
 test/files/presentation/parse-invariants/Test.scala             |  17 +++++---
 test/files/presentation/parse-invariants/src/a/A.java           |  16 +++++++
 test/files/run/implicit-class-implicit-param-with-default.check |   5 +++
 test/files/run/implicit-class-implicit-param-with-default.scala |  11 +++++
 11 files changed, 137 insertions(+), 49 deletions(-)
 create mode 100644 test/files/jvm/strictfp/StrictFpJava.java
 create mode 100644 test/files/presentation/parse-invariants/src/a/A.java
 create mode 100644 test/files/run/implicit-class-implicit-param-with-default.check
 create mode 100644 test/files/run/implicit-class-implicit-param-with-default.scala
% git merge -sours 1e1a162980
Merge made by the 'ours' strategy.
% git merge 068338b2fb
Auto-merging src/compiler/scala/tools/nsc/transform/patmat/PatternExpansion.scala
Auto-merging src/compiler/scala/tools/nsc/Global.scala
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1157 and retry the command.
Merge made by the 'recursive' strategy.
 src/compiler/scala/tools/nsc/Global.scala                            |  6 ++++--
 src/compiler/scala/tools/nsc/transform/patmat/PatternExpansion.scala | 16 ++++++++++------
 test/files/pos/t11162.scala                                          | 23 +++++++++++++++++++++++
 3 files changed, 37 insertions(+), 8 deletions(-)
 create mode 100644 test/files/pos/t11162.scala
% git merge -sours bd441b7b13
Merge made by the 'ours' strategy.
% git merge 25c7215844
Auto-merging test/junit/scala/tools/nsc/DeterminismTest.scala
Auto-merging src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1157 and retry the command.
Recorded preimage for 'src/compiler/scala/tools/nsc/typechecker/RefChecks.scala'
Automatic merge failed; fix conflicts and then commit the result.
% emacs   # manually resolve conflicts
% git add -u
% git commit
Recorded resolution for 'src/compiler/scala/tools/nsc/typechecker/RefChecks.scala'.
[merge/2.12.x-to-2.13.x-20190128 0a5dcd60c8] Merge commit '25c7215844' into merge/2.12.x-to-2.13.x-20190128
% git merge -sours 7abb8dbcf5
Merge made by the 'ours' strategy.
```

### CODE REVIEW

**Comment by SethTisue** [comment]
looks like a semantic merge conflict that will be easy to resolve:

```
!![0m  185 - run/implicit-class-implicit-param-with-default.scala  [output differs]
% [0mdiff /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/run/implicit-class-implicit-param-with-default.check /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/run/implicit-class-implicit-param-with-default-run.log
@@ -1,3 +1,4 @@
+warning: there was one deprecation warning (since 2.13.0); re-run with -deprecation for details
 default
 default
 default
```

and then I'll need to take a closer look at:

```
error] [0m[0m- testJDeps[0m
error] [0m[0m  - root/testJDeps failed: java.lang.RuntimeException: Detected dependency outside of compact1:[0m
error] [0m[0mscala-library.jar -> /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar (compact1)[0m
error] [0m[0mscala-reflect.jar -> /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar (compact3)[0m
error] [0m[0mscala-reflect.jar -> /home/jenkins/workspace/scala-2.13.x-validate-main@2/build/pack/lib/scala-library.jar[0m
```

**Comment by SethTisue** [comment]
I believe jdeps is complaining because:

```
src/reflect/scala/reflect/internal/util/ChromeTrace.scala:import java.lang.management.ManagementFactory
```

@retronym looks like your wheelhouse

**Comment by mkeskells** [comment]
@SethTisue this looks to be due to the addition of the tracing facilities, allowing scalac to produce flame charts etc

**Comment by retronym** [comment]
@SethTisue I've pushed a commit to use reflection with a backstop on exceptions. That means that scala-reflect will again only have hard dependencies on the compact1 profile.

**Comment by SethTisue** [comment]
the rest is in https://github.com/scala/scala/pull/7721

**Pull request merged**
