### PR TITLE
Revert "Fix erasure of the qualifier of ##"

### PR DESCRIPTION
**Pull request by adriaanm**
Reverts scala/scala#5658 to fix https://github.com/scala/scala-dev/issues/314

### CODE REVIEW

**Comment by som-snytt** [comment]
I can't believe it, I didn't break the community build again? I'll try harder next time.

**Comment by adriaanm** [comment]
If at first you succeed. Try once more!

**Comment by SethTisue** [comment]
I verified locally that this fixed scala-js in the community build. The full community build run on Jenkins is https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1282/consoleFull (404 til Jenkins finishes antiquing his endtable, like Albert Brooks)

**Comment by SethTisue** [comment]
2.12 community build is green again

**Pull request merged**
