### PR TITLE
SI-6725 `f` interpolator now supports %n tokens

### PR DESCRIPTION
**Pull request by xeno-by**
Currently the `f` interpolator supports format specifiers which
specify conversions for formatted arguments. However Java formatting
is not limited to argument-related conversions as explained in:
http://docs.oracle.com/javase/6/docs/api/java/util/Formatter.html#detail.

Conversions which don't correspond to any arguments are `%` (used to
emit verbatim `'%'` characters) and `n` (used to emit platform-specific
line separators). Of those only the former is supported, and this patch
fixes the oversight.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @odersky

**Comment by paulp** [comment]
Probably doesn't need review by odersky, but definitely needs test coverage (and at this point I shouldn't have to tell you that.)

**Comment by xeno-by** [comment]
Oh! I wanted to mention how important it is to write tests in the hacker guide, which was written around this pull request, but forgot to actually do that... Facepalm!

**Comment by xeno-by** [comment]
Superseded by https://github.com/scala/scala/pull/2222

**Pull request closed without merging**
