### PR TITLE
Prefer java Math methods

### PR DESCRIPTION
**Pull request by isaacl**
Replace scala math calls with the java.lang version.

Done with: sed -i 's/\([^.]\)math\.\([a-z]\)/\1Math.\2/g'

### CODE REVIEW

**Comment by Sciss** [comment]
why is that? is `scala.math` deprecated now?

**Comment by retronym** [comment]
There is currently a small performance penalty for calling methods in scala object vs calling a static method.

https://github.com/scala/scala/pull/6523 tries to remove that difference where possible.

**Comment by Sciss** [comment]
But if `scala.math` is not deprecated, using it is certainly the idiomatic way to do it. E.g. you have `math.Pi` not `Math.PI`. And mixing styles is bad. I think it's good that we get rid of `java.lang.*` paths in standard library and compiler. Doesn't that also involve scala.js, scala-native?

**Comment by sjrd** [comment]
> Doesn't that also involve scala.js, scala-native?

Scala.js and Scala Native both reimplement `java.lang.Math`.

**Comment by isaacl** [comment]
idk, I don't see the point of ignoring java.math or paying a penalty for Math.max, etc

**Comment by isaacl** [comment]
I'd suspect indirection on Math.max negatively affect C2 optimization as well, but I guess who knows

**Pull request closed without merging**
