### PR TITLE
[nomaster] SI-6773 Makes the SI-6150 changes binary compatible with 2.10

### PR DESCRIPTION
**Pull request by JamesIry**
The back ported fix of SI-6150 1f0e488 broke binary compatibility. This commit fixes that by removing the IndexedSeqFactory class and copy/pasting its one method around to everything that extended it then re-adds some inner classes needed by the binary compatibility checker.

review @retronym

### CODE REVIEW

**Comment by JamesIry** [comment]
NVM, this doesn't go far enough.

**Comment by retronym** [comment]
I'm proposing `[nomerge]` in the commit title for these ones, I think having something in the title makes it easier for the merge later one.

**Comment by JamesIry** [comment]
@retronym squashed and added [nomaster]

**Comment by retronym** [comment]
I'm assuming you've MiMa-ed this; so LGTM

**Pull request merged**
