### PR TITLE
Ant labour: osgi uptodate checking and better doc skipping 

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by dragos** [comment]
I'm not sure in exactly why, but this [broke](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/3330/console) the `ant deploy.local` step in the IDE validation script. It crashes after installing the `jar` and `-sources.jar`, so I wonder if it's something related to (skipping?) docs.

**Comment by retronym** [comment]
Let's try a small variation on the theme.

**Comment by dragos** [comment]
[Looks better](https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-integrate-ide/3335/console)

**Comment by adriaanm** [comment]
LGTM, thanks! I was going to work on something similar for dbuild, so that we can build in layers: 
1. dbuild "locker" (lib/reflect/comp), no docs, no tests, publish locally
2. build quick (including modules) with locally published "locker"
3. document and test everything
4. publish remotely

**Pull request merged**
