### PR TITLE
Update copyright notices in source code to 2014

### PR DESCRIPTION
**Pull request by retronym**
I used this command:

```
% git grep -l --null Copyright | xargs -0 -n 1 perl -p -i -e 's/(Copyright\s+(20..-|))(20(09|10|11|12|13))(\b.*(LAMP|Typesafe).*)/${1}2014$5/g'
```

### CODE REVIEW

**Comment by retronym** [comment]
Here's a condensed view of the diff, generated with `git show | egrep 'a/|Copyright' | gist`

https://gist.github.com/retronym/a5b0aeacf503fd09e5d5

**Comment by retronym** [comment]
Review by @lrytz

**Comment by som-snytt** [comment]
Updating copyright can be beautiful.

**Comment by gourlaysama** [comment]
What about all the files that have no copyright headers at all?
I found 224 with:

``` sh
# files with the first line starting with "package"
gawk 'FNR>1 {nextfile} /^package/ { print FILENAME ; nextfile }' src/**.scala
```

**Comment by retronym** [comment]
Well spotted! I've added the missing headers (and the tool I used) in #4056

**Comment by gourlaysama** [comment]
This didn't process the ASCII-art headers from the library, see `src/library/scala/App.scala` for example...

**Comment by retronym** [comment]
I'll reopen this shortly with better handling of the various notices.

**Pull request closed without merging**
