### PR TITLE
Add doc annotation `@shortDescription` to enable explicit synopsis

### PR DESCRIPTION
**Pull request by felixmulder**
Entities with this annotation will be able to control what is shown in
the method summary on entity pages as well as the hover text on search
results.

Review: @VladUreche

### CODE REVIEW

**Comment by felixmulder** [comment]
Added a test :+1:

**Comment by VladUreche** [comment]
LGTM. In fact it LVGTM.

**Comment by felixmulder** [comment]
Thanks @VladUreche!

**Comment by felixmulder** [comment]
Maybe @janekdb should know about this for the scaladoc tutorial? :)

**Comment by VladUreche** [comment]
Yep, thanks for pointing it out Felix!

**Comment by janekdb** [comment]
Add to list here: https://github.com/scala/scala-lang/pull/394

**Pull request merged**
