### PR TITLE
2.13.x: Windows CI (GHA): add JDK 17 (alongside 8)

### PR DESCRIPTION
**Pull request by SethTisue**
Initially let's try 11, and if that goes well, let's see if we can make the leap to 17.

### CODE REVIEW

**Comment by SethTisue** [comment]
Initially let's try 11, and if that goes well, let's see if we can make the leap to 17.

there's just one failure on 11:

```
[error] Test scala.tools.nsc.classpath.MultiReleaseJarTest.mrJar failed: java.nio.file.FileSystemException: C:\Users\RUNNER~1\AppData\Local\Temp\mr-jar-test-14229187050892520920.jar: The process cannot access the file because it is being used by another process.
[error] , took 0.509 sec
[error]     at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error]     at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
[error]     at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[error]     at java.nio.file.Files.deleteIfExists(Files.java:1181)
[error]     at scala.tools.nsc.classpath.MultiReleaseJarTest.mrJar(MultiReleaseJarTest.scala:51)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
120
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
```

I'll take a stab at fixing that, and then hopefully move on to 17.

**Comment by SethTisue** [comment]
I've pushed what I think is a fix for the test failing on 11. We'll see if CI agrees

This previous run has the JDK 17 failures: https://github.com/scala/scala/runs/2898898645

These failures are reproducible locally on MacOS:
* `junit/testOnly scala.collection.immutable.StringLikeTest`
  * easy fix, Oracle changed an error text
* `partest jvm/scala-concurrent-tck.scala` (which, gah, is an 1100 line monster)

**Comment by SethTisue** [comment]
> partest jvm/scala-concurrent-tck.scala

this one is meaty enough that I've opened a separate ticket on it: https://github.com/scala/bug/issues/12423

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/9679/checks?check_run_id=3089965147 is green. I'll rebase now to ready the PR for merge

**Review by retronym — APPROVED** [review]

**Pull request merged**
