### PR TITLE
Improve ExecutionContext implicitNotFound and docs

### PR DESCRIPTION
**Pull request by havocp**
It is not good practice to import a specific ExecutionContext all over the place; we shouldn't recommend that. People should allow callers to specify the context in most cases and only import the context in some central location in their code.

### CODE REVIEW

**Comment by adriaanm** [comment]
Throw in some newlines and you have my LGTM.

**Comment by jozic** [comment]
would be nice to repeat this text somewhere in scaladoc for `ExecutionContext`

**Comment by havocp** [comment]
I improved this a bit but in the process added some risk that it doesn't compile (or that the docs come out ugly) and my laptop does not currently have enough battery to try compiling it :-) so, please comment on these new docs if you have comments, but I'll have to check compilation later on.

**Comment by havocp** [comment]
So scala isn't compiling for me, probably for some silly reason (I don't regularly hack on it). It may be that I need JDK 1.5? 

It might be easier for someone with an already-working build to check this patch if anyone is feeling charitable but when I'm back home next week I can try to figure it out.

**Comment by retronym** [comment]
Assuming that you have pushed the latest commits to this PR, the build kitteh has already checked: https://scala-webapps.epfl.ch/jenkins/job/pr-scala/5995/

**Comment by havocp** [comment]
convenient! yes the latest I have is pushed here.

**Comment by jessitron** [comment]
Oh yay! This is an improvement.

What I'd like to see is some docs on the global execution context, specifying that it creates a thread pool that aims for your number of CPUs (unless specified properties are set) and that if code blocks inside blocking{...} such as in Await, additional threads may start.

I could write that up in a separate PR?

**Comment by retronym** [comment]
I'd vote to incorporate that into: http://docs.scala-lang.org/overviews/core/futures.html

`blocking` does confuse the hell out of people, so more docs are _very_ welcome.

**Comment by som-snytt** [comment]
Maybe this is too easy, but the fact that by default threads are daemon.

http://stackoverflow.com/a/21560453/1296806

**Comment by adriaanm** [comment]
LGTM, thanks @havocp. 

@jessitron, follow-up PR on https://github.com/scala/scala.github.com/blob/master/overviews/core/_posts/2012-09-20-futures.md very welcome!

**Pull request merged**
