### PR TITLE
Construct ClassBTypes from parsed classfiles

### PR DESCRIPTION
**Pull request by lrytz**
See individual commit messages.

### CODE REVIEW

**Comment by lrytz** [comment]
[`-Ybackend:GenBCode` build here](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/1371/) (the `jvm/unreachable` failure is expected, see #4211). Review by @gkossakowski.

**Comment by gkossakowski** [comment]
I'll be offline until January 7th. If a review is needed before that time, please reassign. Marry Christmas and Happy New Year! :christmas_tree: :gift: :fireworks:

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@3bbf6f01d3acb59894f0ef29e89ca54cf29200dd

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@3bbf6f01d3acb59894f0ef29e89ca54cf29200dd
No matter how hard I try, I cannot reproduce the failure.

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@3bbf6f0

**Comment by gkossakowski** [comment]
I've went through the whole code. Apart from the few nitpicks, it all looks good. When addressing the feedback please make sure to rebase. The PR doesn't merge cleanly anymore.

**Comment by lrytz** [comment]
Thanks for the review, @gkossakowski! Rebased on 2.11.x, reworded some commit messages, added one new commit that addresses the remaining feedback.

**Comment by lrytz** [comment]
IDE validation is broken (unrelated to my commits)

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@f3f9eb41aacc9731f8f00ed6c2bd52a30eb4ee76

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@91435f68d280071d286c9d0e13b279293843ae7e

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@afebceee78155c66564921eab7dd2170f820fdbf

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@45efefaa9b16532c1f61560bde09a7346dcfe5a1

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@7c1983d153a81ba43858a1bb5f0b59c5708bbfcf

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@ff9512812c6619d6ab5a1dde99c9569a3b27c813

**Comment by gkossakowski** [comment]
LGTM

Great work!

**Pull request merged**
