### PR TITLE
Correct position of import selector rename [ci: last-only]

### PR DESCRIPTION
**Pull request by som-snytt**
Follow up to https://github.com/scala/scala/pull/10447

https://github.com/scalameta/metals/issues/5975

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Thanks!

**Comment by som-snytt** [comment]
To recap, the message in 2.13.12 is imprecise and has a coarse position.
```
test/files/neg/t12813c.scala:6: error: a is renamed twice
import O.{a => abcdefghij, a => abcdefghij}
       ^
1 error
```

The updated message makes it clear, hopefully, that what's significant is the right of the arrows. (`import O.x` means `import O.{x => x}`) What matters is that two selectors introduce an ambiguity.

I wound up quoting the entire check file here. The possible "improvement" would be to notice line 8 that left of the arrows are also identical.
```
t12813.scala:5: error: a is imported twice
import O.{a, a}   // error
          ^
t12813.scala:8: error: b is an ambiguous name on import
import O.{a => b, a => b}   // error
               ^
t12813.scala:10: error: b is an ambiguous name on import
import O.{a => b, toString => b}    // error
               ^
t12813.scala:11: error: toString is an ambiguous name on import
import O.{a => toString, toString}  // error
               ^
t12813.scala:12: error: toString is an ambiguous name on import
import O.{toString, a => toString}  // error
          ^
5 errors
```
WWDD says use one message only and highlight the repeater, which is the offender:
```
-- [E122] Syntax Error: test/files/neg/t12813b.scala:10:30 -------------------------------------------------------------
10 |import O.{a => b, toString => b}    // error
   |                              ^
   |                              b is imported twice on the same import line.
```
One may quibble with the verb: `a is imported as b`.

**Comment by som-snytt** [comment]
Followed dotty in positioning at the duplicate, which is where an edit is (probably?) required. The case of exact duplicate could offer a quickfix to simply delete it. As a syntax error, perhaps IDEs do not offer to delete it as "unused".

Did not `last-only` because still burned by the original mistake.

**Comment by som-snytt** [comment]
OK I caved and last-only until scripted test is resolved:
```
[error]  Cause of test exception: {line 7}  Command failed: checkErrors failed
[info] Running reporter/warnings-reported
[info] [info] welcome to sbt 1.9.7 (Oracle Corporation Java 1.8.0_332)
[info] [info] loading project definition from /tmp/sbt_7ff225c7/project
[info] [info] compiling 1 Scala source to /tmp/sbt_7ff225c7/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] done compiling
[info] [info] set current project to sbt_7ff225c7 (in build file:/tmp/sbt_7ff225c7/)
[info] [success] Total time: 0 s, completed Dec 29, 2023 3:00:40 PM
[info] [info] welcome to sbt 1.9.7 (Oracle Corporation Java 1.8.0_332)
[info] [info] loading project definition from /tmp/sbt_7ff225c7/project
[info] [info] loading settings for project sbt_7ff225c7 from common.sbt ...
[info] [info] set current project to sbt_7ff225c7 (in build file:/tmp/sbt_7ff225c7/)
[info] [info] compiling 3 Scala sources to /tmp/sbt_7ff225c7/target/classes ...
[info] [error] ## Exception when compiling 3 sources to /tmp/sbt_7ff225c7/target/classes
[info] [error] scala.reflect.internal.FatalError: Error accessing /home/jenkins/.ivy2/local/org.scala-lang/scala-library/2.13.13-bin-SNAPSHOT/jars/scala-library.jar
[info] [error] scala.tools.nsc.classpath.AggregateClassPath.$anonfun$list$3(AggregateClassPath.scala:114)
```

**Comment by som-snytt** [comment]
Trying locally, why would it report error but complete with success?
```
[info] Running 1 / 1 (100.00%) scripted tests with RunFromSourceMain
[info] Running reporter/errors-reported
[error] x reporter/errors-reported [PENDING]
[error]  Cause of test exception: {line 7}  Command failed: checkErrors failed
[success] Total time: 40 s, completed Dec 29, 2023, 7:35:16 AM
```

**Review by lrytz — APPROVED** [review]
🙏

**Pull request merged**
