### PR TITLE
SI-6140 Scaladoc infinite recursion in wiki parser

### PR DESCRIPTION
**Pull request by VladUreche**
introduced by dc70d1b7.

Review by @heathermiller.

### CODE REVIEW

**Comment by VladUreche** [comment]
PLS REBUILD ALL

**Comment by heathermiller** [comment]
Aborted?

**Comment by jsuereth** [comment]
took too long is my guess.

PLS REBUILD pr-scala-testsuite-linux-opt  KTHX KITTEH!

**Comment by heathermiller** [comment]
LGTM

**Pull request merged**
