### PR TITLE
Optimize Vector.++:

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Ichoran** [comment]
Thank you for the interest in improving the performance of `++:`, but this actually does the opposite if the argument (`xs` in `xs ++: ys`) is not small compared to `ys`.  Please see `++` for an algorithm that can handle both cases.

**Comment by Atry** [comment]
@Ichoran Should `++:` call `++` internally?

**Comment by Ichoran** [comment]
The order of addition is opposite so I'm not sure there's a good way to make that work.

**Comment by SethTisue** [comment]
needs rebase

**Comment by szeiger** [comment]
Some benchmarks to back up @Ichoran's argument:

```
[info] Result "concatRightNew":
[info]   43228.221 ±(99.9%) 2049.271 ns/op [Average]
[info]   (min, avg, max) = (41434.150, 43228.221, 45225.468), stdev = 1355.466
[info]   CI (99.9%): [41178.950, 45277.491] (assumes normal distribution)
[info]
[info]
[info] # Run complete. Total time: 00:09:44
[info]
[info] Benchmark                             (size)  (size2)  Mode  Cnt      Score      Error  Units
[info] VectorConcatBenchmark.concatLeft          10       10  avgt   10    218.919 ±    4.187  ns/op
[info] VectorConcatBenchmark.concatLeft          10      100  avgt   10    654.739 ±   17.387  ns/op
[info] VectorConcatBenchmark.concatLeft          10     1000  avgt   10    371.211 ±    8.404  ns/op
[info] VectorConcatBenchmark.concatLeft         100       10  avgt   10    653.869 ±   10.432  ns/op
[info] VectorConcatBenchmark.concatLeft         100      100  avgt   10   1075.080 ±   19.087  ns/op
[info] VectorConcatBenchmark.concatLeft         100     1000  avgt   10   5217.454 ±   84.702  ns/op
[info] VectorConcatBenchmark.concatLeft        1000       10  avgt   10    357.815 ±    4.844  ns/op
[info] VectorConcatBenchmark.concatLeft        1000      100  avgt   10   5332.014 ±  177.232  ns/op
[info] VectorConcatBenchmark.concatLeft        1000     1000  avgt   10   9462.662 ±  269.920  ns/op
[info] VectorConcatBenchmark.concatRight         10       10  avgt   10    220.517 ±    5.185  ns/op
[info] VectorConcatBenchmark.concatRight         10      100  avgt   10    654.333 ±   13.420  ns/op
[info] VectorConcatBenchmark.concatRight         10     1000  avgt   10   4754.047 ±  164.608  ns/op
[info] VectorConcatBenchmark.concatRight        100       10  avgt   10    666.357 ±   16.762  ns/op
[info] VectorConcatBenchmark.concatRight        100      100  avgt   10   1091.400 ±   27.841  ns/op
[info] VectorConcatBenchmark.concatRight        100     1000  avgt   10   5247.419 ±  117.928  ns/op
[info] VectorConcatBenchmark.concatRight       1000       10  avgt   10   4874.079 ±  162.303  ns/op
[info] VectorConcatBenchmark.concatRight       1000      100  avgt   10   5277.027 ±  170.649  ns/op
[info] VectorConcatBenchmark.concatRight       1000     1000  avgt   10   9401.303 ±  161.331  ns/op
[info] VectorConcatBenchmark.concatRightNew      10       10  avgt   10    538.820 ±    9.096  ns/op
[info] VectorConcatBenchmark.concatRightNew      10      100  avgt   10    543.089 ±   11.635  ns/op
[info] VectorConcatBenchmark.concatRightNew      10     1000  avgt   10    552.551 ±   15.029  ns/op
[info] VectorConcatBenchmark.concatRightNew     100       10  avgt   10   4661.785 ±   51.378  ns/op
[info] VectorConcatBenchmark.concatRightNew     100      100  avgt   10   4570.104 ±  169.891  ns/op
[info] VectorConcatBenchmark.concatRightNew     100     1000  avgt   10   4730.184 ±   79.685  ns/op
[info] VectorConcatBenchmark.concatRightNew    1000       10  avgt   10  43562.154 ± 1758.716  ns/op
[info] VectorConcatBenchmark.concatRightNew    1000      100  avgt   10  43044.524 ± 1513.763  ns/op
[info] VectorConcatBenchmark.concatRightNew    1000     1000  avgt   10  43228.221 ± 2049.271  ns/op
```

Big improvements in some cases but even bigger losses in others, so I'm closing this.

BTW, it looks like overriding `++:` in `Vector` alone is not acceptable:

```
[error] /Users/szeiger/code/scala/test/benchmarks/src/main/scala/scala/collection/immutable/VectorConcatBenchmark.scala:34: ambiguous reference to overloaded definition,
[error] both method ++: in class Vector of type [B >: Any, That](that: scala.collection.TraversableOnce[B])(implicit bf: scala.collection.generic.CanBuildFrom[scala.collection.immutable.Vector[Any],B,That])That
[error] and  method ++: in trait TraversableLike of type [B >: Any, That](that: Traversable[B])(implicit bf: scala.collection.generic.CanBuildFrom[scala.collection.immutable.Vector[Any],B,That])That
[error] match argument types (scala.collection.immutable.Vector[Any])
[error]   @Benchmark def concatRight = values ++: values2
[error]                                       ^
```

Maybe a more elaborate scheme could disambiguate the methods again but I haven't explored this further.

**Pull request closed without merging**
