### PR TITLE
Dotless type application for infix operators.

### PR DESCRIPTION
**Pull request by paulp**
When you have an aesthetic expresion like

```
  def f(xs: Iterator[Int]) = (
    xs takeWhile (_ < 1000)
             map (_ * -1)
          filter (_ % 2 == 0)
         flatMap (x => List(x, x))
    reduceOption (_ + _)
           maxBy (_.toString)
  )
```

And then for whatever reason you have to perform explicit
type application in the midst of that expression, it's
aggravating in the extreme that it has (had) to be rewritten
in its entirety to accommodate that change.

So now you can perform type application in the middle of it.

For reasons not entirely clear to me postfix operators are
excluded. The discussion as well as the approval for the infix
variation of it can be found at:
  https://groups.google.com/forum/#!msg/scala-language/eJl1wnkEz9M/hR984-lqC5EJ

### CODE REVIEW

**Comment by paulp** [comment]
I guess half a loaf is better than none, or whatever loaf I can still squeeze from this. Review by @retronym ?

**Comment by soc** [comment]
This looks quite nice indeed!

**Comment by retronym** [comment]
Just ploughed through that thread. Here's a [shortcut](https://groups.google.com/d/msg/scala-language/eJl1wnkEz9M/QpSEt_mA6c8J) to @odersky's approval.

What is the change to the grammar? That should be reflected in the comments in the parser, and later, in the spec, and the third party parsers in IntelliJ and Scalariform.

**Comment by soc** [comment]
@retronym, @paulp I can take care of the spec part, if you want.

**Comment by paulp** [comment]
@soc yes please.

**Comment by adriaanm** [comment]
LGTM

**Comment by xeno-by** [comment]
Looks like we can merge this one?

**Comment by adriaanm** [comment]
Wanted to take another look at the impact on the grammar

**Comment by adriaanm** [comment]
@soc, gentle reminder regarding the spec PR, but I won't let that keep us from saving the dots

**Pull request merged**
