### PR TITLE
Backport/large scope soe

### PR DESCRIPTION
**Pull request by retronym**
Cherry pick of 09b1a31309c9cbf1394c317b87d2073d39a8cd56

### CODE REVIEW

**Comment by jsuereth** [comment]
Ok, I'm pulling this one in, assuming you've run tests.  I'll let you know if I run into an testing issues after I run the release process today.

**Comment by retronym** [comment]
I didn't get a full, clean run finished: the tests ran successfully for 40 minutes or but then exhausted PermGen. But the cherry-pick was cleanly merged, so I'm confident that it's okay.

**Comment by jsuereth** [comment]
I'm running them now, so we'll see.   Luckily for everyone, we don't do
binary compatibility in the compiler yet.   We need to make a BC interface
to it in the future, but for now, don't make assumptions on the compiler
itself....

**Comment by jsuereth** [comment]
Tests are passing.  I'll run the final binary check, but I'm not worried about this commit.  You're in for 2.9.x!  Thanks for the backport.

**Pull request merged**
