### PR TITLE
SI-4829 the :load command now fails if the command ends with a space (Pre-port)

### PR DESCRIPTION
**Pull request by jedesah**
The :load command now tries to be smart by detecting the presence of trailing spaces that might be insignificant.

On certain file systems, files with trailing whitespaces are permitted which is why we don't naively trim the argument.

Please review @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
Please add a rule like (depending on the direction)

```
    { matchName="scala.reflect.internal.util.StringOps.splitLeft"
      problemName=MissingMethodProblem }
```

to bincompat-*.whitelist.conf.

**Comment by adriaanm** [comment]
To test locally, use `ant test.bc`

**Comment by JamesIry** [comment]
RC-1 is approaching. If there's no action on this PR soon I'll kick to 2.10.4

**Comment by JamesIry** [comment]
Time has run out on 2.10.3, kicking down the road.

**Comment by retronym** [comment]
Closing due to test failures and need for rebase.

**Pull request closed without merging**
