### PR TITLE
SI-8133 Fix regression with package objects, overloading

### PR DESCRIPTION
**Pull request by retronym**
Review by @adriaanm.

/cc @paulp on the off chance you haven't scrubbed the part of
your memory that could confirm or disconfirm the "ostensibly"
part.

### CODE REVIEW

**Comment by retronym** [comment]
@adriaanm This one needn't hold up M8.

**Comment by paulp** [comment]
It's scrubbed. I'm leaning 55/45 toward unintentional.

**Comment by retronym** [comment]
Review also welcome from @xeno-by

**Comment by xeno-by** [comment]
@retronym Looks like a legitimate failure?

**Comment by retronym** [comment]
I'm happy enough to merge the first commit if that LGTY. The second might need coordination with scala-refactoring. /cc @misto

**Comment by xeno-by** [comment]
As I'm unfamiliar with this part of the compiler, I'll need to think a bit more about this PR. How about tomorrow I take a look at it again?

**Comment by retronym** [comment]
Sure thing.

**Comment by retronym** [comment]
> How come that separate compilation makes a difference here?

I don't have an thorough explanation for that. I suspect it has the same root cause as SI-8134, which I am working on at the moment. In that bug, we get into an sequence of:
- the completer for the package forces the completer on the package object (based on a class file from the first compilation) in `openPackageModule`. Members of package objects are also put into the scope of the enclosing package class. When the typechecker binds to such symbol in the package class owned by the package object, it retypechecks it as a selection from the package object. (In, for example, `makeAccessible` and `TreeGen`).
- later, we notice that the package object also exists in source, so we stick a source-based completer on it. But we haven't removed the original member symbols of the package object from the package class.

I'm not sure if this one has the same set of circumstances though.

**Comment by xeno-by** [comment]
LGTM

**Comment by xeno-by** [comment]
@retronym See https://github.com/scala/scala/pull/3389/files#r9029738

**Pull request merged**
