### PR TITLE
Revert `@static` annotation

### PR DESCRIPTION
**Pull request by gkossakowski**
This pull request reverts all changes related to `@static` feature.

As it has been discussed on scala-internals this feature should come with SIP in the first place. We need much more time hash out the details of `@static` semantics which we don't have at the moment given how close the RC1 is.

Review by @axel22.

### CODE REVIEW

**Comment by axel22** [comment]
LGTM

**Comment by allxiao** [comment]
Hi, is there any further plan for this `@static` feature? It's been nearly 3 years since the reversion.

**Comment by lrytz** [comment]
There's been a more recent discussion here: https://groups.google.com/forum/#!searchin/scala-internals/static$20annotation/scala-internals/Y3OlFWPvnyM/tGE5BQw4Pe0J

**Comment by lrytz** [comment]
the issues discussed there are blockers imo.

**Comment by dblsaiko** [comment]
Did anything else ever happen after this discussion?

**Comment by jvican** [comment]
Yes @MRebhan. A SIP was created: http://docs.scala-lang.org/sips/pending/static-members.html. The SIP is under implementation since a member of the SIP board volunteered to provide one.
  
This implementation would in theory target 2.12.x.

**Comment by SethTisue** [comment]
yes, see http://docs.scala-lang.org/sips/pending/static-members.html

plus it was discussed at a SIP meeting. ordinarily the minutes would be found at http://docs.scala-lang.org/sips/minutes-list.html, but I see that's fallen behind by some months — for now see https://github.com/scala/scala.github.com/pull/762

**Comment by jvican** [comment]
I beat you by 1 minute and 37 seconds @SethTisue. You're not as fast as you used to be 😜.

**Comment by SethTisue** [comment]
I spent the extra two minutes finding the minutes PR :-P :-P

**Comment by dblsaiko** [comment]
Thanks guys :'D

**Comment by Clyybber** [comment]
Any progress on this feature?

**Comment by NthPortal** [comment]
As of 2.13.0/2.12.9/2.11.12 (the latest versions of each of the last three releases), Scala generates static forwarder methods:

```scala
// Test.scala
object Test {
  val foo: String = "foo"
  def bar: String = "bar"
}
```

```java
// javap -c 'Test.class' # compiled with 2.13.0, 2.12.9 or 2.11.12
public final class Test {
  public static java.lang.String bar();
    Code:
       0: getstatic     #16                 // Field Test$.MODULE$:LTest$;
       3: invokevirtual #18                 // Method Test$.bar:()Ljava/lang/String;
       6: areturn

  public static java.lang.String foo();
    Code:
       0: getstatic     #16                 // Field Test$.MODULE$:LTest$;
       3: invokevirtual #21                 // Method Test$.foo:()Ljava/lang/String;
       6: areturn
}
```

```java
// javap -c -p 'Test$.class' # compiled with 2.13.0
public final class Test$ {
  public static final Test$ MODULE$;

  private static final java.lang.String foo;

  public static {};
    Code:
       0: new           #2                  // class Test$
       3: dup
       4: invokespecial #14                 // Method "<init>":()V
       7: putstatic     #16                 // Field MODULE$:LTest$;
      10: ldc           #17                 // String foo
      12: putstatic     #19                 // Field foo:Ljava/lang/String;
      15: return

  public java.lang.String foo();
    Code:
       0: getstatic     #19                 // Field foo:Ljava/lang/String;
       3: areturn

  public java.lang.String bar();
    Code:
       0: ldc           #23                 // String bar
       2: areturn

  private Test$();
    Code:
       0: aload_0
       1: invokespecial #24                 // Method java/lang/Object."<init>":()V
       4: return
}
```

```java
// javap -c -p 'Test$.class' # compiled with 2.12.9
public final class Test$ {
  public static Test$ MODULE$;

  private final java.lang.String foo;

  public static {};
    Code:
       0: new           #2                  // class Test$
       3: invokespecial #14                 // Method "<init>":()V
       6: return

  public java.lang.String foo();
    Code:
       0: aload_0
       1: getfield      #17                 // Field foo:Ljava/lang/String;
       4: areturn

  public java.lang.String bar();
    Code:
       0: ldc           #20                 // String bar
       2: areturn

  private Test$();
    Code:
       0: aload_0
       1: invokespecial #21                 // Method java/lang/Object."<init>":()V
       4: aload_0
       5: putstatic     #23                 // Field MODULE$:LTest$;
       8: aload_0
       9: ldc           #24                 // String foo
      11: putfield      #17                 // Field foo:Ljava/lang/String;
      14: return
}
```

```java
// javap -c -p 'Test$.class' # compiled with 2.11.12
public final class Test$ {
  public static final Test$ MODULE$;

  private final java.lang.String foo;

  public static {};
    Code:
       0: new           #2                  // class Test$
       3: invokespecial #12                 // Method "<init>":()V
       6: return

  public java.lang.String foo();
    Code:
       0: aload_0
       1: getfield      #17                 // Field foo:Ljava/lang/String;
       4: areturn

  public java.lang.String bar();
    Code:
       0: ldc           #20                 // String bar
       2: areturn

  private Test$();
    Code:
       0: aload_0
       1: invokespecial #21                 // Method java/lang/Object."<init>":()V
       4: aload_0
       5: putstatic     #23                 // Field MODULE$:LTest$;
       8: aload_0
       9: ldc           #24                 // String foo
      11: putfield      #17                 // Field foo:Ljava/lang/String;
      14: return
}
```

**Comment by HyukjinKwon** [comment]
Scala 2.13 is out. How do we plan this?

**Comment by NthPortal** [comment]
it's not obvious to me that there's still a need for this. given that the compiler already generates forwarders, what's your use case @HyukjinKwon?

**Comment by HyukjinKwon** [comment]
I would like to define an object that has a static field that can be accessed in Java as well, for example:

```scala
object Foo {
  val field = "abc"
}
```

and in Java side:

```java
Foo.field
```

The reason is that to provide the consistent API usages in both Scala and Java. Does it make snese?

**Comment by NthPortal** [comment]
as I mentioned, the compiler generates static forwarders that can be accessed from Java. please see the bytecode showing the static methods in my comment [immediately above](https://github.com/scala/scala/pull/1340#issuecomment-520252782). while they are methods rather than fields, they still permit access from Java (and are generally considered better practice anyway).

**Comment by HyukjinKwon** [comment]
The point here is to have a field instead of a method in Java side in order to support the same shape of the APIs. I want to support `Foo.field` in both Java and Scala instead of `Foo.field()` in Java alone.

Just allowing a way to access is not enough in particular in APIs. For example, you cannot do such things:

```scala
object Nations {
  object Korea {
    def localize = ...  
  }
  val korea = Korea

  object US {
    def localize = ...      
  }
  val us = US
}
```

In Scala:

```scala
Nations.us.localize(...)
```

In Java:

```java
Nations.us().localize(...)
```

**Comment by NthPortal** [comment]
that's part of the [Uniform Access Principle](https://docs.scala-lang.org/glossary/index.html#uniform-access-principle) - that is, it allows you to swap a `val` for a `def` with no parameter lists and vice versa in a binary and source compatible way. while it will look different in Java, because they both are methods and use `()`, they remain source compatible when you change the implementation.

**Comment by HyukjinKwon** [comment]
So just to clarify, there's no way to make Java to call `Nations.us.localize(...)` like Scala does, and this PR fixed it. Is it correct?

**Comment by HyukjinKwon** [comment]
So just to clarify, there's no way to make Java to call `Nations.us.localize(...)` like Scala does, and this reverted change fixed it. Is it correct?

**Comment by dwijnand** [comment]
Correct, there's no way to define a static field in Scala.  The proposal for that is SIP-30 (https://docs.scala-lang.org/sips/static-members.html) and it's "under review" but hasn't been discussed recently.  I think it lacks both a motivated implementer and a SIP committee champion, at this point.

**Pull request merged**
