### PR TITLE
SI-3235 math.round() returns wrong results for Int and Long

### PR DESCRIPTION
**Pull request by Ichoran**
Near-minimal fix for math.round() issue.  (Based on a more extensive fix proposed by soc.)

RichLong intercepts calls to the four floating-point-only methods of .math: round, rint, ceil, and floor.

Also catches round on Int/Long in scala.math.

### CODE REVIEW

**Comment by Ichoran** [comment]
Previous PR at https://github.com/scala/scala/pull/3435

**Comment by soc** [comment]
Not sure how this is supposed to be a near-minimal fix.
- It adds additional methods to floating-point types against which we have to play defense against.
- `rint`: no. Just no.
- The return types are all over the place. (What about `Byte`, `Short`, ...?)
- The deprecation messages don't make any sense imho. (Or are we supposed to yell at people who do `List(1,2,3).toList`, too?)

I think there are a lot of arguments for either keeping the sad state of the art as is or improving it. But making it even worse?

**Comment by non** [comment]
Given the bad place we're in, I think adding `round` methods to catch the `Int` and `Long` cases makes a ton of sense. The deprecation warning also makes sense, especially if there is a plan to eventually remove the methods (but also prevent the coercion from occurring).

I'm ambivalent about adding `rint`. I do think many users will prefer this method to `round`, but I doubt most of them realize that `round` has problems--Rex feels differently and I may be wrong here.

We don't need `rint` to fix the wart that Paul mentioned (`123456789.round == 123456792`) and it will not fix the next anticipated wart (`(1000000000000000000000000.0).round == 9223372036854775807`) so in my opinion the PR would be just as good without it. But I don't feel strongly either way.

I guess what I'm saying is that this LGTM although I share Simon's frustrations.

**Comment by non** [comment]
Also one more thing, unless `rint` is implemented in `RichInt` and `RichLong` too, you'll have the same bug you currently have with `round` there. So, I retract my LGTM, since that should be fixed or changed.

**Comment by Ichoran** [comment]
@soc - `rint` is there to give people access to something with the same behavior as `floor` and `ceil`.  That can be removed; it's why the fix is "near minimal".  Also, as long as `+` doesn't preserve the type of a `Byte`, I see no reason for other mathematical operations to do so.  The type system will let you know that the conversion has taken place.

@non - `RichLong` catches all of `floor`, `ceil`, `rint`, and `round`.  Since the point of these methods is for you to not use them, I didn't see a reason to add them to `RichInt` as well; `RichLong` will catch the `Int` case and warn you.

**Comment by soc** [comment]
It's kind of bizarre how this issue has evolved from a principled fix https://groups.google.com/d/topic/scala-internals/Gi-54GeWv-M/discussion into a hack https://github.com/scala/scala/pull/3435 into something which makes things even worse (this).

I kind of start to understand why people quit the project. It's stuff like this.

Really, either
- keep things the way they are or
- deprecate `Double#round` and `Float#round`.

**Comment by soc** [comment]
See #3561.

**Comment by adriaanm** [comment]
@soc, we're debating a solution -- I don't think that should be a reason to quit

**Comment by soc** [comment]
Every new proposal has been further away from a solution. I suggest trying to solve that first.

Just because I'm not paid doesn't mean my time is worthless. And the debate on this whole issue has been a perfect example of a glorious waste of my time.

What's the next proposal? Embedding a PHP interpreter into the language and deferring all mathematical operations to it?

**Comment by adriaanm** [comment]
I apologize for any time wasted! It's certainly not our intention. Maybe an easier way to explain the divergence from your proposed solution is a difference in opinion, or maybe even a misunderstanding (I'm no expert in math libraries, so it's hard for me to judge) rather than malice?

**Comment by Ichoran** [comment]
@soc - I agree the debate has wasted a lot of time; I apologize.  Your time is not the only one wasted, I'm not being paid for this fix either, and we can and have both done valuable things with our time.  So let's try to keep any more debate effective and brief.

The core disagreements seem to be (1) whether familiar naming is more important than maintaining working yet difficult code; and (2) whether it is worth using weird naming with improved behavior, or whether the weird name more than offsets the difference in behavior.

Nobody agrees that 123456789.round == 123456792 is a good thing, right?  The minimal fix there is an intercepting method in RichLong and in scala.math that blocks numeric promotion.  I had thought it would be better to encourage rint as a type-preserving alternative, but if your opinion is that the weird name isn't worth the more regular/explicit behavior, then I take that complaint seriously since you have more experience with the difficulties faced by new users than do I.

Do you see a problem with a genuinely minimal fix, which simply intercepts the at-best-useless at-worst-broken .round on Int/Long?  Do you have any suggestions for a better name for a type-preserving nearest-integer operation (which I think we agree is the better one to use), assuming that we can't use .round for that since it's already taken by a type-altering operation?  I don't see any problem providing a better-named alias for java.lang.Math.rint.

Most of all, I don't think we should make users suffer completely unhelpful behavior because we don't agree on the relative value of different tradeoffs.

**Comment by adriaanm** [comment]
@Ichoran, thanks for the detailed summary. I suggest you drop the addition of `rint`, and then I'd say this PR is ready to go, unless @soc speaks up in time (i.e., Monday).

**Comment by soc** [comment]
No, doesn't look good to me.

The return types are still all over the place, let's not keep repeating that mistake from `Double#round`, `Float#round`.

Have a look at it from that perspective:

If you ever wanted to have a useful `Numeric` typeclass, which included methods like `round`/`ceil`/`floor` you would basically have two options:
- Either decide on a common return type for _all_ existing numeric types and those still to be invented. I'd be excited to see how anyone manged to meaningfully implement the `round: Int` method of  `case class Complex(re: Double, im: Double)`. What is `round` supposed to return? What's the "similarly-sized integer type" here?
  The point is that there is no "similarly-sized integer type" for an arbitrary number type, and even if there was one, we wouldn't be able to support it with `Numeric` without an explosion of complexity.
  Plus even for those types, where a "similarly-sized integer type" exists, it can't represent the rounding faithfully.
- Or make the result type of `round`/`ceil`/`floor` consistent with the input type: `Int#round` returns `Int`, `Byte#round` returns `Byte`, `BigDecimal#round` returns `BigDecimal`, `Short#round` returns `Short`, `Float#round` returns `Float`, `Complex#round` returns `Complex`, `Double#round` returns `Double`, ... simple, consistent, logical and suffers from none of the issues mentioned above.

Summary:
- Don't make it any worse by repeating the mistakes of `Double#round:Long` and `Float#round:Int`.
- Don't annoy people with pointless deprecation warnings.
- Let's revisit the `Float`/`Double` case in time for 2.12 again.

Just cherry-pick https://github.com/soc/scala/commit/603293c068f09398669cf44bddb3d501bb69eecd and if you want to save you the additional future debate, probably cherry-pick https://github.com/soc/scala/commit/67d46d7e3973d7d3bfb456328a42b1df6f5a0b45?w=1, too.

**Comment by Ichoran** [comment]
You shouldn't have a `Numeric` typeclass that includes `round`, `ceil`, and `floor` because those operations are no-ops on integers.  Thus, if you're applying them to integers, you're almost certainly making a mistake.

It's fine on `Fractional` or the like, and there they ideally would return the same type.  (There's still the issue of Java compatibility, though.)

The only issue is the auto-promotion to `Float` and `Double`, which combined with `round` specifically is liable to yield nonsense.   The point of defining deprecated `round` on `Long` and possibly `Int` is to avoid errors.  This is not a "pointless deprecation warning".

The cherry-pick of 603293c is less useful for catching errors, but still solves the worst problem so is acceptable.

**Comment by adriaanm** [comment]
Regardless of whether it makes sense to have a type class include `round` etc, I don't understand why the return types have to be uniform. You could have a type member in the type class that denotes the target type of these operations (an associated type in Haskell), or use something like the CanBuildFrom pattern.

I still think it's good to cherry-pick the commit for the Rich\* integers and possibly to drop rint, but I didn't see @soc insisting on that anymore.

**Comment by soc** [comment]
> You could have a type member in the type class that denotes the target type of these operations (an associated type in Haskell), or use something like the CanBuildFrom pattern.

Which is exactly what I had in mind when I said "explosion of complexity".

> possibly to drop rint, but I didn't see @soc insisting on that anymore.

I assumed that this was a given. The name is a completely unacceptable.

**Comment by Ichoran** [comment]
This isn't minimal enough.  Opening a new PR at https://github.com/scala/scala/pull/3581

**Pull request closed without merging**
