### PR TITLE
SI-9264 combat intermittent disappearing valdefs

### PR DESCRIPTION
**Pull request by adriaanm**
review by @retronym

### CODE REVIEW

**Comment by adriaanm** [comment]
ugh, s/ticker/ticket/...

**Comment by adriaanm** [comment]
Hmm, not sure we can actually live with this -- see the `jvm/patmat_opt*` failures.

  jvm > patmat_opt_ignore_underscore-jvm.log

```
1  == TypeOp(NEW, SameBytecode$Foo)                                                                                 | TypeOp(NEW, SameBytecode$Foo)
2  == Op(DUP)                                                                                                       | Op(DUP)
3  == VarOp(ALOAD, 0)                                                                                               | VarOp(ALOAD, 0)
4  == Op(ICONST_1)                                                                                                  | Op(ICONST_1)
5  == Invoke(INVOKESTATIC, scala/runtime/BoxesRunTime, boxToInteger, (I)Ljava/lang/Integer;, false)                 | Invoke(INVOKESTATIC, scala/runtime/BoxesRunTime, boxToInteger, (I)Ljava/lang/Integer;, false)
6  == Ldc(LDC, a)                                                                                                   | Ldc(LDC, a)
7  == Invoke(INVOKESPECIAL, SameBytecode$Foo, <init>, (LSameBytecode;Ljava/lang/Object;Ljava/lang/String;)V, false) | Invoke(INVOKESPECIAL, SameBytecode$Foo, <init>, (LSameBytecode;Ljava/lang/Object;Ljava/lang/String;)V, false)
8  == VarOp(ASTORE, 1)                                                                                              | VarOp(ASTORE, 1)
9  == VarOp(ALOAD, 1)                                                                                               | VarOp(ALOAD, 1)
10 == Invoke(INVOKEVIRTUAL, SameBytecode$Foo, x, ()Ljava/lang/Object;, false)                                       | Invoke(INVOKEVIRTUAL, SameBytecode$Foo, x, ()Ljava/lang/Object;, false)
11 == TypeOp(INSTANCEOF, java/lang/String)                                                                          | TypeOp(INSTANCEOF, java/lang/String)
12 <> Jump(IFEQ, Label(19))                                                                                         | Jump(IFEQ, Label(15))
13 == VarOp(ALOAD, 1)                                                                                               | VarOp(ALOAD, 1)
14 <> Invoke(INVOKEVIRTUAL, SameBytecode$Foo, x, ()Ljava/lang/Object;, false)                                       | Invoke(INVOKEVIRTUAL, SameBytecode$Foo, y, ()Ljava/lang/String;, false)
15 <> TypeOp(CHECKCAST, java/lang/String)                                                                           | Op(ARETURN)
16 <> Op(POP)                                                                                                       | Label(15)
17 <> VarOp(ALOAD, 1)                                                                                               | FrameEntry(1, List(SameBytecode$Foo), List())
18 <> Invoke(INVOKEVIRTUAL, SameBytecode$Foo, y, ()Ljava/lang/String;, false)                                       | TypeOp(NEW, scala/MatchError)
19 <> Op(ARETURN)                                                                                                   | Op(DUP)
20 <> Label(19)                                                                                                     | VarOp(ALOAD, 1)
21 <> FrameEntry(1, List(SameBytecode$Foo), List())                                                                 | Invoke(INVOKESPECIAL, scala/MatchError, <init>, (Ljava/lang/Object;)V, false)
22 <> TypeOp(NEW, scala/MatchError)                                                                                 | Op(ATHROW)
23 <> Op(DUP)                                                                                                       | 
24 <> VarOp(ALOAD, 1)                                                                                               | 
25 <> Invoke(INVOKESPECIAL, scala/MatchError, <init>, (Ljava/lang/Object;)V, false)                                 | 
26 <> Op(ATHROW)                                                                                                    | 
```

  jvm > patmat_opt_no_nullcheck-jvm.log

```
1  == TypeOp(NEW, Foo)                                                                              | TypeOp(NEW, Foo)
2  == Op(DUP)                                                                                       | Op(DUP)
3  == Op(ICONST_1)                                                                                  | Op(ICONST_1)
4  == Invoke(INVOKESTATIC, scala/runtime/BoxesRunTime, boxToInteger, (I)Ljava/lang/Integer;, false) | Invoke(INVOKESTATIC, scala/runtime/BoxesRunTime, boxToInteger, (I)Ljava/lang/Integer;, false)
5  == Invoke(INVOKESPECIAL, Foo, <init>, (Ljava/lang/Object;)V, false)                              | Invoke(INVOKESPECIAL, Foo, <init>, (Ljava/lang/Object;)V, false)
6  == VarOp(ASTORE, 2)                                                                              | VarOp(ASTORE, 2)
7  == VarOp(ALOAD, 2)                                                                               | VarOp(ALOAD, 2)
8  == TypeOp(INSTANCEOF, Foo)                                                                       | TypeOp(INSTANCEOF, Foo)
9  <> Jump(IFEQ, Label(23))                                                                         | Jump(IFEQ, Label(19))
10 == VarOp(ALOAD, 2)                                                                               | VarOp(ALOAD, 2)
11 == TypeOp(CHECKCAST, Foo)                                                                        | TypeOp(CHECKCAST, Foo)
12 == VarOp(ASTORE, 1)                                                                              | VarOp(ASTORE, 1)
13 == VarOp(ALOAD, 1)                                                                               | VarOp(ALOAD, 1)
14 == Invoke(INVOKEVIRTUAL, Foo, x, ()Ljava/lang/Object;, false)                                    | Invoke(INVOKEVIRTUAL, Foo, x, ()Ljava/lang/Object;, false)
15 == TypeOp(INSTANCEOF, java/lang/String)                                                          | TypeOp(INSTANCEOF, java/lang/String)
16 <> Jump(IFEQ, Label(23))                                                                         | Jump(IFEQ, Label(19))
17 <> VarOp(ALOAD, 1)                                                                               | Field(GETSTATIC, scala/runtime/BoxedUnit, UNIT, Lscala/runtime/BoxedUnit;)
18 <> Invoke(INVOKEVIRTUAL, Foo, x, ()Ljava/lang/Object;, false)                                    | Op(POP)
19 <> TypeOp(CHECKCAST, java/lang/String)                                                           | Op(RETURN)
20 <> Op(POP)                                                                                       | Label(19)
21 <> Field(GETSTATIC, scala/runtime/BoxedUnit, UNIT, Lscala/runtime/BoxedUnit;)                    | FrameEntry(1, List(0, Foo), List())
22 <> Op(POP)                                                                                       | TypeOp(NEW, scala/MatchError)
23 <> Op(RETURN)                                                                                    | Op(DUP)
24 <> Label(23)                                                                                     | VarOp(ALOAD, 2)
25 <> FrameEntry(1, List(0, Foo), List())                                                           | Invoke(INVOKESPECIAL, scala/MatchError, <init>, (Ljava/lang/Object;)V, false)
26 <> TypeOp(NEW, scala/MatchError)                                                                 | Op(ATHROW)
27 <> Op(DUP)                                                                                       | 
28 <> VarOp(ALOAD, 2)                                                                               | 
29 <> Invoke(INVOKESPECIAL, scala/MatchError, <init>, (Ljava/lang/Object;)V, false)                 | 
30 <> Op(ATHROW)                                                                                    | 
```

  jvm > patmat_opt_primitive_typetest-jvm.log

```
1  == TypeOp(NEW, SameBytecode$Foo)                                                                | TypeOp(NEW, SameBytecode$Foo)
2  == Op(DUP)                                                                                      | Op(DUP)
3  == VarOp(ALOAD, 0)                                                                              | VarOp(ALOAD, 0)
4  == Op(ICONST_1)                                                                                 | Op(ICONST_1)
5  == Ldc(LDC, a)                                                                                  | Ldc(LDC, a)
6  == Invoke(INVOKESPECIAL, SameBytecode$Foo, <init>, (LSameBytecode;ILjava/lang/String;)V, false) | Invoke(INVOKESPECIAL, SameBytecode$Foo, <init>, (LSameBytecode;ILjava/lang/String;)V, false)
7  == VarOp(ASTORE, 1)                                                                             | VarOp(ASTORE, 1)
8  == VarOp(ALOAD, 1)                                                                              | VarOp(ALOAD, 1)
9  <> Invoke(INVOKEVIRTUAL, SameBytecode$Foo, x, ()I, false)                                       | Invoke(INVOKEVIRTUAL, SameBytecode$Foo, y, ()Ljava/lang/String;, false)
10 <> Op(POP)                                                                                      | Op(ARETURN)
11 <> VarOp(ALOAD, 1)                                                                              | 
12 <> Invoke(INVOKEVIRTUAL, SameBytecode$Foo, y, ()Ljava/lang/String;, false)                      | 
13 <> Op(ARETURN)                                                                                  | 
```

**Comment by adriaanm** [comment]
(Rotate screen to see full diffs...)

**Comment by retronym** [comment]
Agreed. We'll need to figure out the root cause...

**Pull request closed without merging**
