### PR TITLE
Remove resolveOverloaded

### PR DESCRIPTION
**Pull request by clhodapp**
At the reflection meeting, it was decided to delay resolveOverloaded until 2.10.1, where it will be unified with the compiler's overload resolution code. This commit removes it and the related tests.

### CODE REVIEW

**Comment by xeno-by** [comment]
Looks sad to me.

It is a shame that we have to give up essential parts of the metaprogramming API in this release. Let's do our best to catch up in 2.10.1!

@clhodapp Please accept my condolences.

**Comment by paulp** [comment]
There may be some consolation in the knowledge that it's a marathon, not a sprint.

**Comment by jsuereth** [comment]
anyone mind fixing this up to merge correctly?

**Comment by clhodapp** [comment]
I'll push a new version later.

**Comment by jsuereth** [comment]
Can I get a LGTM from someone?

**Comment by paulp** [comment]
TMLG!

**Comment by clhodapp** [comment]
Hold on, don't merge... I missed a doc comment!

**Comment by xeno-by** [comment]
LGTM!

**Comment by clhodapp** [comment]
That was a suspiciously short jenkins job...

**Comment by paulp** [comment]
I had the same suspicion, but it looks like it was email/message delay, not magically fast computer.

**Comment by clhodapp** [comment]
Thanks, kitten!

**Pull request merged**
