### PR TITLE
SI-7566 Remove items deprecated for 2.12

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by retronym** [comment]
We need to be a bit careful about this in light of: https://groups.google.com/forum/#!msg/scala-internals/rTNYUc5FWWw/sQYWTG2GjJkJ

**Comment by soc** [comment]
Ok, so we basically need to fix and release a new version of partest first, right?

**Comment by adriaanm** [comment]
I didn't look at the failures, but that sounds likely. The new partest should be backwards compatible.

**Comment by soc** [comment]
@adriaanm https://github.com/scala/scala-partest/pull/27

**Comment by adriaanm** [comment]
Merged. I'll cut a new release soon (this week normally).

**Comment by adriaanm** [comment]
Could I ask you to nurture this a while longer -- we need to have a discussion on what we can actually remove, since we promised full source compatibility, regardless of deprecation for 2.12, since we're going to have to support 2.11 a bit longer for Java 6 users.  

From http://www.scala-lang.org/news/2.12-roadmap:

> Hassle-free cross-building between 2.11 and 2.12 through full backward source compatibility (we won’t remove deprecated methods, but will support optional deprecation errors). Closely align 2.11 and 2.12 compiler and standard library code bases.

**Comment by soc** [comment]
Yes, the plan was to split the compatible parts from the rest after the merge of #4213 so that I wouldn't have to touch this PR multiple times. This is largely obsolete now after the main work happened multiple times; I'll rescue the remaining parts after #4294 is done.

**Comment by adriaanm** [comment]
Thank you! Sorry about the overhead / inefficiencies...

**Pull request closed without merging**
