### PR TITLE
Remove OldHashMap/OldHashSet

### PR DESCRIPTION
**Pull request by joshlemer**
This is a continuation of work started by @SethTisue , to remove the old hash implementations.

This depends on scala/bug#11143, because this removes the equivalent tests for OldHashMap

### CODE REVIEW

**Comment by SethTisue** [comment]
(you should make yourself the author of the commit, you did the hard parts)

**Comment by joshlemer** [comment]
Done!

**Comment by lrytz** [comment]
@joshlemer what's the status of https://github.com/scala/bug/issues/6253 and https://github.com/scala/bug/issues/7326 with respect to ChampHashSet/Map? (the tests are removed in this PR).

**Comment by joshlemer** [comment]
@lrytz an efficient `HashSet#concat` (which `union` is an alias of) hasn't been implemented yet, but it has been in `HashMap` and just needs to be translated over to the `HashSet` case yet. It will be though, before 2.13.0. Here's a ticket for it https://github.com/scala/bug/issues/11147

`HashSet#subsetOf` appears to have already been optimized by Michael Steindorfer

**Comment by lrytz** [comment]
Thanks, I only saw the ticket for filter/filterNot.

**Review by lrytz — APPROVED** [review]

**Comment by SethTisue** [comment]
thank you Josh, appreciate you volunteering for this

**Pull request merged**
