### PR TITLE
fixes SI-7636 NPE in typer

### PR DESCRIPTION
**Pull request by cvogt**
Not sure what lead to fn.tpe being null and if avoiding this "case" is the right solution, but it fixes the issue and all tests pass, except files/run/macro-typemacros-fifth-proto which did not pass before the change. 

**files/run/macro-typemacros-fifth-proto-run.log:**

<pre>
Impls_Macros_2.scala:71: error: `=', `&gt;:', or `&lt;:' expected
  type H2Db(url: String) = macro impl
           ^
one error found
</pre>

### CODE REVIEW

**Comment by cvogt** [comment]
review by @lrytz or @adriaanm

**Comment by xeno-by** [comment]
Could you please add tests? Also I think it'd be cool to figure out what leads to a null tpe.

**Comment by cvogt** [comment]
Right, sorry about that. I added a test. I agree it would be good to know where it came from, but I leave that for someone who is more familiar with the typer.

**Comment by retronym** [comment]
Reworked slightly as #2738.

**Pull request closed without merging**
