### PR TITLE
SI-6308 Specialize methods that have some unspecialized params

### PR DESCRIPTION
**Pull request by retronym**
This is a continuation of 1591c14e50, which didn't go far enough
to handle method calls with a mix of specialized and unspecialized
type parameters.

This commit modifies `specSym` to calculate the residual type
of the original method after specialized type parameters have
been removed and the type environment of the candidate specialized
variant has been subsituted.

For example, here is trace of `specSym` when searcing for the
specialized variant of `f4` in the enclosed test:

```
tree             = Main.this.f4[Nothing, Int]
tree.tpe         = (a: Int, b: List[(Int, Nothing)])String
fun.tpe          = [B, A](a: A, b: List[(A, B)])String
residualTreeType = [B](a: Int, b: List[(Int, B)])String
memberType       = [B](a: Int, b: List[(Int, B)])String
env              = Map(type A -> Int)
doesConform      = true
```

A few "todo" tests are included that highlight an endemic
issue with the current specialization implementation: type
parameters that show up after `uncurry` might be clones of
the original symbols from typer, if they have been through
a TypeMap (e.g. within a call to `uncurryTreeType`). So testing
them for existence with the `typeEnv` map is fruitless.

No amount of `atPhase` acrobatics can rescue us from this;
we need to transport this information in a symbol-cloning
resiliant manner. Maybe Symbol Attachments?

Review by @vladureche, /cc @d6

### CODE REVIEW

**Comment by gkossakowski** [comment]
@retronym: could you elaborate a little bit more on the problem with expanded type aliases after uncurry that confuse specialization? Why wouldn't specialization expand all type aliases when checking things in `TypeEnv` ?

**Comment by retronym** [comment]
`SpecializeTypes` uses symbol equality all over the place, e.g.

``` scala
specializedTypeVars(sym).intersect(env.keySet)
```

These break down if the one side of the equality refers to a type parameter symbol from `typer`, and another refers to one post-uncurry, which has been cloned during a `TypeMap`. If the type parameter is bound by an alias type, the TypeMap in `uncurry` is not an identity, so new symbols are allocated.

The easiest way to see what's happening is to remove the code the preserves symbols through identity type maps:

``` patch
     /** Called by mapOver to determine whether the original symbols can
       *  be returned, or whether they must be cloned.
       */
-    protected def noChangeToSymbols(origSyms: List[Symbol]): Boolean = {
-      @tailrec def loop(syms: List[Symbol]): Boolean = syms match {
-        case Nil     => true
-        case x :: xs => (x.info eq applyToSymbolInfo(x)) && loop(xs)
-      }
-      loop(origSyms)
-    }
+    protected def noChangeToSymbols(origSyms: List[Symbol]): Boolean = false
```

And witness the carnage.

```
/tools/partest-ack specialized
% tests-with-matching-paths      ...  20
% tests-with-matching-code       ...  115
# 117 tests to run.
...
70/117 passed, 47 failed (elapsed time: 00:00:49)
```

AFAIK nothing should be relying on `noChangeToSymbols` for correctness. Maybe @adriaanm or @paulp could confirm that claim.

Specialization isn't unique in this regard; other facets of the compiler have also grown accustomed to type and value parameter symbols being quasi-constant.

I don't really know how to fix this category of problems. I tried pretty hard a while back in uncurry but ran out of steam. Some interaction with caching of normalized types within `TypeRef`s finally killed off that effort.

**Comment by paulp** [comment]
I can't confirm any claim which requires knowledge of what the author was thinking. In principle (assuming a different set of principles than those actually in effect) the preservation of reference equality should not be a linchpin of correctness.

Maybe the easiest way to deal with this is to supplement clones with a pointer back to the symbol of origin. Then we can have a test for "== modulo cloning", and clone+"owner" is 'def clowner'.

Just follow the clowner chain and you'll be fine.

**Comment by VladUreche** [comment]
LGTM, thanks for the fix Jason!
Is there a bug for the left todos?

**Comment by retronym** [comment]
I've just filed: https://issues.scala-lang.org/browse/SI-7559

**Comment by gkossakowski** [comment]
@retronym: I have some more questions about the problem you describe. I'll continue the discussion on the ticket you filed.

**Pull request merged**
