### PR TITLE
Check file maintainence

### PR DESCRIPTION
**Pull request by retronym**
Removing the empty and orphaned.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski or @JamesIry

**Comment by JamesIry** [comment]
LGTM. But why do you hate orphans so much? Haven't they had a hard enough life already?

**Comment by retronym** [comment]
We can ship them off to Honest Bender's Orphanarium if you prefer.

**Comment by paulp** [comment]
I guess it's a little late, but tools/rm-orphan-checkfiles.

```
#!/bin/sh
#
# Scans for and removes .check and .flags files under test/
# which don't have an accompanying test.

shopt -s nullglob

echo "Scanning for orphan check files..."
for f in $(ls -1d test/{files,pending,disabled}/{jvm,neg,pos,run}/*.check); do
  base=${f%%.check}
  [[ -d $base ]] || [[ -f $base.scala ]] || git rm -f $f
done

echo "Scanning for orphan flags files..."
for f in $(ls -1d test/{files,pending,disabled}/{jvm,neg,pos,run}/*.flags); do
  base=${f%%.flags}
  [[ -d $base ]] || [[ -f $base.scala ]] || git rm -f $f
done
```

**Comment by retronym** [comment]
Much nicer. That directory needs a spring clean.

**Pull request merged**
