### PR TITLE
SI-8451 makes uncurry more forgiving

### PR DESCRIPTION
**Pull request by xeno-by**
Apparently even though the rhs of a secondary constructor looks like an expr,
it always gets wrapped in a block by the parser. This works just fine with
the typer, but crashes in uncurry. This commit brings quasiquotes in line with the parser.

### CODE REVIEW

**Comment by gkossakowski** [comment]
So what will be allowed now? Commit messages shouldn't leave questions unanswered. You look at commit messages for answers.

**Comment by xeno-by** [comment]
Updated the PR: fixed wording, added a quasiquote fix.

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
Removed the uncurry part per Jason's request.

**Comment by retronym** [comment]
LGTM, localised to quasiquotes.

**Pull request merged**
