### PR TITLE
SI-9408 Avoid capturing outer class in local classes.

### PR DESCRIPTION
**Pull request by retronym**
Review by @lrytz

### CODE REVIEW

**Comment by retronym** [comment]
Commit message error:

``` diff
-class NoSerializable$C(outer$: C)
+class NoSerializable$C(outer$: NoSerializable)
```

**Comment by retronym** [comment]
@lrytz Ready for re-review.

**Comment by retronym** [comment]
Previous review comments: 
https://github.com/retronym/scala/commit/a4dbd5738fcd34db7f4e04ad0c41d1dfead69e46
https://github.com/retronym/scala/commit/9c89d2063ab200ece4537c982eff7eab03338b49

**Comment by lrytz** [comment]
LGTM!

**Comment by retronym** [comment]
I've spun out a new ticket for the suggested improvements: https://issues.scala-lang.org/browse/SI-9414

**Pull request merged**
