### PR TITLE
SI-8531 Better space efficiency for patmat analysis

### PR DESCRIPTION
**Pull request by retronym**
By adding logging to `clause`, I found that the majority of
calls provide 0 or 1 elements. In SI-7020 / 69557da55, we changed this
method to use a `LinkedHashSet` to have deterministic results
for clauses with more elements. But I suspect that this
contributes to higher memory usage from the pattern matcher.

The enclosed test case, carefully whittled down by @oxbowlakes,
used to consume an inordinate amount of memory and time.
After this patch, it is back to 2.10.4 performance.

I have run `neg/t7020.scala` in a loop and it still is deterministic.

Review by @adriaanm

Resubmission of #3696 that included a test and uses `toSet` as
suggested.

### CODE REVIEW

**Comment by retronym** [comment]
```
% javac -d /tmp test/files/pos/t8531/MyEnum.java && time qbin/scalac -J-Xmx200M  -classpath /tmp -d /tmp test/files/pos/t8531/Test.scala

real    0m5.315s
user    0m10.541s
sys 0m0.543s


% javac -d /tmp test/files/pos/t8531/MyEnum.java && time scalac-hash v2.11.0 -J-Xmx700M -classpath /tmp -d /tmp test/files/pos/t8531/Test.scala
error: java.lang.OutOfMemoryError: Java heap space
    at scala.collection.mutable.LinkedHashSet.createNewEntry(LinkedHashSet.scala:105)


real    0m24.893s
user    0m35.425s
sys 0m1.102s
```

**Comment by oxbowlakes** [comment]
How come enough 0 (or 1) element LinkedHashSets were created to consume
800m of memory on this pattern match? I can create almost 75,000
single-element such LinkedHashSets with 16m of heap, suggesting that you
must be creating well upwards of a million of them. How can such a small
piece of code result in the creation of over a million sets?

Chris

**Comment by gkossakowski** [comment]
I share @oxbowlakes concerns.

@retronym, did you try to take a heap dump and analyze it?

**Comment by retronym** [comment]
I looked at a heap dump that @oxbowlakes sent me from his original codebase. That led me to change to `LinkedHashSet`. I analysed that with some smaller tests from our suite, noticed that the vast majority of cases where small sets, and optimized this.

Yesterday, he provided a minimized test case, and I confirmed that this regressed at the point I suspected, and that this patch restored its 2.10 performance.

I have just instrumented the pattern matcher to count the number of set creations through the two branches of `def clause`.

``` patch
diff --git a/src/compiler/scala/tools/nsc/transform/patmat/Solving.scala b/src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
index 31b1ffa..7627a74 100644
--- a/src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
+++ b/src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
@@ -11,6 +11,16 @@ import scala.reflect.internal.util.Statistics
 import scala.language.postfixOps
 import scala.reflect.internal.util.Collections._

+object Stats {
+  var clauseCount01 = 0
+  var clauseCount = 0
+  scala.sys.ShutdownHookThread {
+    println("clauseCount01 = " + clauseCount01)
+    println("clauseCount = " + clauseCount)
+  }
+
+}
+
 // naive CNF translation and simple DPLL solver
 trait Solving extends Logic {
   import PatternMatchingStats._
@@ -28,14 +38,16 @@ trait Solving extends Logic {

     type Clause  = collection.Set[Lit]
     // a clause is a disjunction of distinct literals
-    def clause(l: Lit*): Clause = (
+    def clause(l: Lit*): Clause = {
       if (l.lengthCompare(1) <= 0) {
+        Stats.clauseCount01 += 1
         l.toSet // SI-8531 Avoid LinkedHashSet's bulk for 0 and 1 element clauses
       } else {
+        Stats.clauseCount += 1
         // neg/t7020.scala changes output 1% of the time, the non-determinism is quelled with this linked set
         mutable.LinkedHashSet(l: _*)
       }
-    )
+    }

     type Lit
     def Lit(sym: Sym, pos: Boolean = true): Lit
```

```
% javac -d /tmp test/files/pos/t8531/MyEnum.java && qbin/scalac -J-Xmx700M -classpath /tmp -d /tmp test/files/pos/t8531/Test.scala
clauseCount01 = 337090
clauseCount = 0
```

We can get to approximately the same number of invocations with a smaller match:

``` scala
import foobar._
class `SI-8531` {
    //https://issues.scala-lang.org/browse/SI-8531

  import MyEnum._
  def foo(e1: MyEnum, e2: MyEnum) = (e1, e2) match {
    case (A1, x) => "a1"
    case (x, A1) => "a1"
  }
}

// clauseCount01 = 337114
// clauseCount = 10
```

A single to `removeVarEq` with

``` scala
props = List(Not(And(Not(Eq(V1,null)),Eq(V2,A1))), Not(And(Not(Eq(V1,null)),Eq(V3,A1))), Not(And(Not(Eq(V1,null)),Eq(V2,A2))), Not(And(Not(Eq(V1,null)),Eq(V3,A2))), Not(And(Not(Eq(V1,null)),Eq(V2,A3))), Not(And(Not(Eq(V1,null)),Eq(V3,A3))), Not(And(Not(Eq(V1,null)),Eq(V2,A4))), Not(And(Not(Eq(V1,null)),Eq(V3,A4))), Not(And(Not(Eq(V1,null)),Eq(V2,A5))), Not(And(Not(Eq(V1,null)),Eq(V3,A5))), Not(And(Not(Eq(V1,null)),Eq(V2,A6))), Not(And(Not(Eq(V1,null)),Eq(V3,A6))), Not(Not(Eq(V1,null))))
```

gathers:

``` scala
vars = Set(V1, V2, V3)
vars(V2).implications

List((V2=A180#103,List(),List(V2=A55#153, V2=A37#135, V2=A83#183, V2=A95#196, V2=A165#86, V2=A39#137, V2=A137#55, V2=A92#193, V2=A139#57, V2=A30#128, V2=A51#149, V2=A97#198, V2=A134#52, V2=A18#102, V2=A117#33, V2=A70#169, V2=A132#50, V2=A29#127, V2=A56#154, V2=A9#190, V2=A10#14, V2=A79#178, V2=A98#199, V2=A16#80, V2=A85#185, V2=A67#165, V2=A31#129, V2=A164#85, V2=A32#130, V2=A173#95, V2=A175#97, V2=A91#192, V2=A125#42, V2=A8#179, V2=A35#133, V2=A115#31, V2=A169#90, V2=A105#20, V2=A13#47, V2=A82#182, V2=A81#181, V2=A138#56, V2=A42#140, V2=A112#28, V2=A73#172, V2=A184#107, V2=A26#124, V2=A100#15, V2=A77#176, V2=A96#197, V2=A71#170, V2=A155#75, V2=A133#51, V2=A193#117, V2=A158#78, V2=A89#189, V2=A131#49, V2=A94#195, V2=A50#148, V2=A161#82, V2=A192#116, V2=A2#4, V2=A54#152, V2=A24#122, V2=A53#151, V2=A76#175, V2=A7#168, V2=A168#89, V2=A146#65, V2=A12#36, .........
```

We loop over this:

``` scala
        v.implications foreach { case (sym, implied, excluded) =>
          // when sym is true, what must hold...
          implied  foreach (impliedSym  => addAxiom(Or(Not(sym), impliedSym)))
          // ... and what must not?
          excluded foreach (excludedSym => addAxiom(Or(Not(sym), Not(excludedSym))))
        }
```

Here's the call stack that takes of from `addAxiom` to `clause`:

image

I'm about to get some input from @adriaanm about this one.

**Comment by retronym** [comment]
The size of `vars.flatMap(_.implications)` above is quadratic wrt the number of cases. This representation flattens out the knowledge that a variable can only be of one of the cases by saying that `V2 = Enum1 => V2 != Enum2, V2 != Enum3, ....`.

So while this patch improves the constant factor sufficiently to address the regression, we'll consider this case further as we improve the pattern matcher in future releases. There has been [some work](https://issues.scala-lang.org/browse/SI-7663) in this direction from @gbasler that we need to rebase and integrate, but I'm not sure if that is material for this problem. We could also seek out a richer solving algorithm that would directly admit the exclusion constraints.

**Comment by retronym** [comment]
Another angle to approach this from would be to consider the analysis budget holistically during:

``` scala
       v.implications foreach { case (sym, implied, excluded) =>
          // when sym is true, what must hold...
          implied  foreach (impliedSym  => addAxiom(Or(Not(sym), impliedSym)))
          // ... and what must not?
          excluded foreach (excludedSym => addAxiom(Or(Not(sym), Not(excludedSym))))
        }
```

If too many steps are required, we could bail out with our "pattern too complex to analyse" warning.

**Comment by retronym** [comment]
Review by @adriaanm (I thought that you had already reviewed the previous incarnation of this PR, but you hadn't actually stamped it with your seal of approval.)

**Comment by adriaanm** [comment]
LGTM, now official

**Pull request merged**
