### PR TITLE
Revert "Updates .gitignore files."

### PR DESCRIPTION
**Pull request by retronym**
This reverts commit c485095984fa675dfec1b4e749ab77bc1f8e7506.

Conflicts:
    .gitignore

Our root .gitignore file is not directly checked in;
instead one should `cp gitignore.SAMPLE .gitignore` after
cloning the repository.

This allows it to be customised locally. I'm not sure why
we don't use `.git/info/exclude` for local customizations
instead.

Review by @paulp @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
Why is not a good idea to have a checked in `.gitignore`? Seems useful to me to exclude those jars as we don't want them in the repo.

**Comment by retronym** [comment]
If we check it in, we should move the entire SAMPLE file. Hopefully Paul will remember the trade offs that led to the decision not to check it in. Personally I don't see a reason.

**Comment by adriaanm** [comment]
It makes sense to me to have a .gitignore file for stuff everybody sees but no-one should check in: http://stackoverflow.com/questions/6626136/best-practice-for-adding-gitignore-to-repo

So, I'd be in favor of changing this PR to remove the SAMPLE instead.

**Comment by retronym** [comment]
I've started a thread on -internals to see if anyone remembers the history. I'd also like to directly commit it.

**Comment by soc** [comment]
+1

**Comment by retronym** [comment]
Closing in favour of #2743

**Pull request closed without merging**
