### PR TITLE
 SI-7617 typedAssign no longer expands lhs

### PR DESCRIPTION
**Pull request by xeno-by**
review @retronym

### CODE REVIEW

**Comment by JamesIry** [comment]
What's the status on this PR?

**Comment by retronym** [comment]
Sorry for the slow review.

Test cases and the patch look okay to me but I need some more elaboration in the commit comment about how things went wrong before and how they are now fixed.

Oh, and one minor nitpick: can you please reference the ticket from the code comment with `SI-XXXX`?

**Comment by xeno-by** [comment]
Done

**Comment by retronym** [comment]
LGTM

**Pull request merged**
