### PR TITLE
When we strip tvars we should also recursively strip their instantiation...

### PR DESCRIPTION
**Pull request by hubertp**
...s

as they can be tvars as well.
Otherwise our list of lub base types can be empty.
After this fix value x3 in the test case compiles.

review by @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
awesome -- fix LGTM

for future commit messages, please consider using a title in this style:
"recurse into instantiations when stripping type vars"

the commit title should read as an action that the commit performs on our codebase

shorter titles == easier scanning through commit logs and tidier release notes

**Comment by hubertp** [comment]
Sure, sorry about that. I will change the name and push again.

**Comment by adriaanm** [comment]
thanks!

**Comment by hubertp** [comment]
Title updated, merge at will.

**Pull request merged**
