### PR TITLE
Use released STARR and skip locker by default.

### PR DESCRIPTION
**Pull request by adriaanm**
review by @retronym, please

### CODE REVIEW

**Comment by lrytz** [comment]
if we skip locker we need one more layer for stability testing, no?

**Comment by adriaanm** [comment]
> if we skip locker we need one more layer for stability testing, no?

True. Also, it seems STARR was doing something different for macros.

**Comment by gkossakowski** [comment]
How about we use released version of Scala for STARR and keep locker around for a while? One step at the time.

**Comment by adriaanm** [comment]
The failed macro test is because pickling of macro binding has changed since 2.11.0-M3 (starr&locker for this PR), namely in 82f0925b69.

Locker compiles partest (where src/partest/scala/tools/partest/package.scala defines the `traceImpl` macro introduced in c619f94a) but it's the quick compiler that tries to call that macro.

The easy fix is to compile partest with quick.
Since we're planning to modularize and develop partest as a separate module, we should probably find a more principled solution. Either stop changing the picking format, or compile the macro as part of test run. I'll see about implementing the latter.

/cc @retronym

**Comment by xeno-by** [comment]
How will restarring look in the new scheme of things?

**Comment by adriaanm** [comment]
For now we're only shifting around defaults, use them for PR validation and thus de facto refuse new STARRs (as they become irrelevant), unless we find something that is impossible without rolling a new STARR. I think it's better to only use release compilers. We should only introduce behavior that would require a new STARR under a switch whose default position can be flipped in a future release.

For example, want new pickling behavior? Support both old and new for a release, deprecate the old behavior, and remove it in the next release. This shouldn't even require a switch.

For now, STARR and locker will remain until we run the experiment long enough to gain confidence in the alternative.  If it goes well, we'll remove STARR and locker completely in 2.12.

**Comment by xeno-by** [comment]
What about for example changing the compiler to use quasiquotes? That would require restarring. /cc @densh

**Comment by densh** [comment]
@xeno-by I don't really see a problem here. Before quasiquotes are released it's a bad idea to use them within a compiler. And after they are released there would be a new publicly released compiler with quasiquotes. It might complicate fixing bugs in quasiquotes and using the fix at the same time if that's what you mean.

**Comment by xeno-by** [comment]
1) Why is it a bad idea to use them within the compiler? Should we have to wait until 2.12 (6 more months!) to begin simplifying our codebase?
2) Fixing bugs in quasiquotes is another valid reason. I haven't thought about it originally though.

**Comment by gkossakowski** [comment]
Everyone, I started a thread here: https://groups.google.com/d/topic/scala-internals/gp5JsM1E0Fo/discussion

**Comment by gkossakowski** [comment]
Let's discuss potential issues there. I'd like to understand them very well as I agree this is rather fundamental change (long-term).

**Comment by adriaanm** [comment]
> 1) Why is it a bad idea to use them within the compiler? Should we have to wait until 2.12 (6 more months!) to begin simplifying our codebase?

Yes, we should wait. Stability and performance of the compiler is our primary concern. Adopting new experimental features immediately when they come out is bound to break things. That's why we introduce new features as experimental first.

**Pull request closed without merging**
