### PR TITLE
Adds `movePointLeft` and `movePointRight` to `scala.BigDecimal`.

### PR DESCRIPTION
**Pull request by soc**
Fixes SI-4619.

### CODE REVIEW

**Comment by soc** [comment]
The private implicit looks scary, but I followed the pattern of the other methods in `BigDecimal`.

**Comment by jsuereth** [comment]
Review by @alex22 although this LGTM.

**Comment by paulp** [comment]
I'd rather be getting out of the BigDecimal business than giving it more surface area.  These methods aren't going to hurt anything, but on principle I'd rather channel these improvements into something outside the library.  Because you can now make

```
implicit class MyBigDecimal(bd: java.math.BigDecimal) extends AnyVal
```

and enjoy zero overhead, and decide corner cases according to your own personal corner layout.

**Comment by jsuereth** [comment]
@paulp that does sound the right thing to do for 2.11.

**Comment by soc** [comment]
I agree. I'm planning to have a look at `BigDecimal` when I'm done with a native `BigInt`, so `BigDecimal` could end up rewritten or completely unchanged in the future anyway.
Either way, we should get out of the wrapping-the-wrappers business on the long term for performance-critical types.

**Comment by paulp** [comment]
I'm going to close this in the interests of keeping the hallway clear, since no decision is probably forthcoming given the other urgent matters at hand.  It can be reopened perhaps after 2.10 is out.

**Comment by argv-minus-one** [comment]
Can we revisit this now? It's three years later, and `scala.math.BigDecimal` is still missing these methods.

**Comment by paulp** [comment]
I'll go out on a limb and say the resolution of the time has only gotten stronger.

**Comment by argv-minus-one** [comment]
Then can we please explicitly deprecate `s.m.BigDecimal` and related? This sort of silent, passive, unofficial deprecation is misleading to someone reading the documentation. It certainly misled me until I stumbled upon this bug.

**Comment by paulp** [comment]
I'm all for deprecating it (and I have no horse in the race regardless) but I read the scaladoc for BigDecimal and didn't feel misled, nor did I form the expectation that all the methods of java's BigDecimal would exist on scala's. Can you be more specific?

**Comment by SethTisue** [comment]
@Ichoran want to weigh in on the chances a new PR like this would currently have?

**Comment by Ichoran** [comment]
@SethTisue @paulp I haven't checked what other methods on BigDecimal and BigInteger might be missing.  I can see a point to adding missing methods in 2.12 to improve Java compatibility (with the rationale that going through underlying is pointless boilerplate, and error-prone due to Scala carrying MathContext along and Java not).

I'm less excited about having a single missing method out of several going in.  If there's an argument to be made that we are "done" in some sense with making BigDecimal reflect java.math.BigDecimal, it's a lot more compelling than the argument "by the way, we added another one".

I am not very happy about BigDecimal and BigInt overall, but without a replacement in sight, and without a significant push to add functionality via extension methods, I think the "make the best of it" stance has pragmatic value.  It won't prevent us from actually replacing it in 2.13 or whatever if we come up with something better.

**Pull request closed without merging**
