### PR TITLE
Remove extraneous null check in RedBlackTree

### PR DESCRIPTION
**Pull request by thorpe-dev**
This changes the RedBlackTree foreach method to be be a simple wrapper around
a slightly shorter function, without an unnecessary nullity check.

### CODE REVIEW

**Comment by jsuereth** [comment]
Review by @alex22

**Comment by gkossakowski** [comment]
@jsuereth: Our alex is @axel22 and not @alex22 :-)
Pinging @axel22 on this one.

**Comment by paulp** [comment]
I'll go out on a limb: this is fine.

**Comment by axel22** [comment]
I don't know all the internals of the red black trees, so I'd have to inspect this in more detail to check it, for which I'd need more time.

I think Daniel Sobral did some changes in red black trees, so he may be a better choice for reviewing this in a short notice.

**Comment by paulp** [comment]
The logic in the commit is independent of red, black, or trees.  Isomorphically, the code was "if (bloopie == 7 && bloopie == 7) fritzo" and he said "hey, let's just check bloopie once."

**Comment by axel22** [comment]
Ah, I see now - didn't even look at the diff 'cause I've been pushing it to the end of my list with other stuff on the menu.

Well, for what it's worth - LGTM.

**Pull request merged**
