### PR TITLE
SI-8415 Exception handling in REPL init

### PR DESCRIPTION
**Pull request by som-snytt**
Incremental robustness, and probe for typer phase.

The probe would be unnecessary if repl contributed a
terminal phase that "requires" whatever it needs; that
is checked when the Run is built.

### CODE REVIEW

**Comment by lexspoon** [comment]
Nice! This is an easy mistake to make, so it good to notice it and emit an explicit error message.

The REPL requires not just the typer, though, but a full compilation pipeline. As such, it would seem worth checking for any use of `-Ystop-after`. Alternatively, check for the bytecode generation phase rather than the typer; if that one is present, the typer must be as well.

As a possible tie breaker, checking the `-Ystop-after` flag directly leads to a superior error message, because it can tell the user exactly what to do (drop that option, dolt!).

**Comment by lexspoon** [comment]
As well, I would think it better to check and exit immediately, rather than waiting for someone to type something in. Once they specify `-Ystop-after`, they are doomed. So just bail.

**Comment by som-snytt** [comment]
@lexspoon Yes, I was trying to be minimal; the hard part was picking the spot to test a condition.

Note they can turn off stop-after after realizing their error, so there is an afterlife in the REPL. More of a resurrection.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
