### PR TITLE
Make the scalac Ant task recognise -Yrangepos

### PR DESCRIPTION
**Pull request by sgolodetz**
The scalac Ant task was not setting up the Scala compiler to produce
range positions when specifying the -Yrangepos flag in its addparams
property.

### CODE REVIEW

**Comment by sgolodetz** [comment]
Hope it's ok to put in a pull request for this. I've done my best to follow the guidelines w.r.t. commit messages and posting to scala-internals (see https://groups.google.com/forum/#!topic/scala-internals/3V4c8g6mJRM). I'm not sure whether or not a test case is required for this, and where to add one if so - please can someone advise? Judging by the page, the relevant reviewer for this may be @jsuereth (since it's a build issue), but I'm not 100%.

**Comment by xeno-by** [comment]
@dragos could you please take a look as well? Is this a correct way to start up a rangepos-enabled compiler?

**Comment by jsuereth** [comment]
Lgtm, assuming Iulian approves.

**Comment by retronym** [comment]
I'm not familiar with the Ant task, but I notice that `Global` is also [instantiated in `ForeignCompiler`](https://github.com/scala/scala/blob/v2.10.0-M7/src/compiler/scala/tools/ant/sabbus/ForeignCompiler.scala#L35). This appears to be used only by the [`sabmake` task](https://github.com/scala/scala/blob/v2.10.0-M7/src/compiler/scala/tools/ant/sabbus/Make.scala#L15), which might just be a historical relic.

One other place where range positions would be handy is in the [REPL](https://github.com/scala/scala/blob/v2.10.0-M7/src/compiler/scala/tools/nsc/interpreter/IMain.scala#L261).

**Comment by hubertp** [comment]
This is similar to what is done in https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/Main.scala#L72, so lgtm.

**Comment by jsuereth** [comment]
Well,  I'll make a note to stop using global directly in the future.   Thanks!

**Comment by retronym** [comment]
I've opened an issue to add these to the REPL, I'll submit a PR.

https://issues.scala-lang.org/browse/SI-6381

**Comment by som-snytt** [comment]
I'm glad this change worked out for Stu, the originator.  Maybe I misunderstood something after a martini lunch, but doesn't Josh's comment, "I'll make a note to stop using global directly," imply that the fix should sit inside Global.apply?  Does Global know about range pos?  I don't know the issues, and I don't want to know ATM, I'm just asking naively.

**Pull request merged**
