### PR TITLE
Improve efficiency of updated

### PR DESCRIPTION
**Pull request by rklaehn**
Added utility method to create a HashTrieSet with two leaf HashSets with different hash
Used said utility method instead of creating a temorary HashTrieSet with an empty elems array
Added assertions to HashTrieSet to validate tree

It is difficult to write a test for this, because the old behavior was not wrong, just inefficient. A good test of the HashTrieSet in general would be to run the test suite with both assertions enabled. But the assertion that tests that elems.length must be >1 unless the child element is a HashTrieSet itself must remain commented out until SI-6197 is implemented.

### CODE REVIEW

**Comment by lrytz** [comment]
Maybe it's possible to write an `instrumented` test for it? see 2ae253bea6

also, review by @axel22

**Comment by rklaehn** [comment]
Sounds interesting. I did not know about those. I will have to look into
them.

**Comment by axel22** [comment]
Looks good, but what it still lacks is a test which tests correctness - in particular, the case where you have once hashmap with N keys whose hashcodes collide, and then you add a key whose hash code does not collide.

Then iterate on this with various number of keys with colliding hashcodes (to hit the case where you have more than a single level).

When such tests are added, looks good to me.

**Comment by rklaehn** [comment]
OK. I will try to write a test tomorrow.. which is a holiday in bavaria.

Belated happy birthday, by the way.

**Comment by axel22** [comment]
Thanks!

**Comment by rklaehn** [comment]
Hi Aleksandar,

I added a simple test that just covers all code paths. It uses two ints
that are worst-case when fed through HashSet.improve and uses them to force
creation of a very deep HashTrieSet, either directly or with an
intermediate HashSetCollision1

I hope it is OK to leave some unused code in the test case that might be
useful when the test fails, like the "printStructure" method and the code
to generate two worst-case non-colliding ints...

cheers,

Rüdiger

**Comment by axel22** [comment]
LGTM!

**Comment by rklaehn** [comment]
Great. The worst-case integers will be useful for other hash-trie tests as
well...

**Comment by rklaehn** [comment]
Hi paul. 

Was this meant to go into master, or was that a mistake when I created the pull request? In any case, can you merge it into 2.10.x as well?

Thanks,

Rüdiger

**Comment by paulp** [comment]
The pull req was against master.  I'm buried, can you open another one against 2.10.x so I only have to click merge.

**Comment by rklaehn** [comment]
OK, will do. Sorry about doing the pull req against master. I must have
forgotten to change it, and master is the default.

**Comment by rklaehn** [comment]
Here is the pull request against 2.10.x: https://github.com/scala/scala/pull/1160

**Pull request merged**
