### PR TITLE
Fix SI-6306 on testcase

### PR DESCRIPTION
**Pull request by Blaisorblade**
Keep track of args which are passed in by-name positions, and avoid
inlining those.

Thanks to all commenters on SI-6306, in particular to Jason Zaugg for
diagnosing the underlying fault.

Moreover, clarify comment and add testcase.
Review by @lrytz.

### CODE REVIEW

**Comment by lrytz** [comment]
I really don't understand in which situations `deEta` is correct / useful. It basically converts

```
() => foo()
```

to

```
foo
```

which, as far as i can see, is only correct if `foo` is another `Function` node with an empty parameter list - otherwise the type of the expression changes from `Function0` to something else.

What happens in the bug is that

```
() => 1.toString()
```

gets converted to

```
1.toString
```

(the `Apply` node is dropped, and then probably added again later on by `adapt`).

We need some input here by @paulp or @odersky or @dragos

**Comment by retronym** [comment]
I came to a similar conclusion. Something might be gleaned by modifying the compiler to throw an exception rather than performing the dodgy transformation, and seeing what blows up in the test suite.

**Comment by Blaisorblade** [comment]
@lrytz: I also expressed the same question in SI-6306, but hadn't figured when the code could work. But you're right: the code is supposed to transform `() => foo()` to `foo`, that is, undo eta-expansion as the comment says, and that's only valid if `foo` is an inlinable expression returning `Function0` or a by-name argument. It seems to me that the transformation would be valid even when the expression is passed as a by-name argument - if that's the case, I'd retract the current patch and just check if the expression is a `Function0`.

I'm trying retronym's suggestion and waiting for any failure, but the test suite seems to succeed on at least the pos and neg series with this `deEta`:

``` scala
    def deEta(fun: Function): Tree = fun match {
      case Function(List(), appl @ Apply(expr, List())) if treeInfo.isExprSafeToInline(expr) =>
        Console.err.println("inByNameCallSite(appl) = %s, appl = %s, expr = %s, expr.tpe = %s" format (inByNameCallSite(appl), appl, expr, expr.tpe))
        throw new Throwable()
        if ((expr hasSymbolWhich (_.isLazy)) || inByNameCallSite(appl))
```

For the real archeologists: the code seems ultimately introduced in 2007 by @odersky in commit 
45bcd02f6ba099277bedbf83ec2bda07435c7797, and the testcase involves the '&' operator for by-name parameters.
[This](https://github.com/scala/scala/blob/45bcd02f6ba099277bedbf83ec2bda07435c7797/src/compiler/scala/tools/nsc/ast/TreeInfo.scala#L77) was `isPureExpr` at the time - not much different (apart a few bugfixes).

**Comment by Blaisorblade** [comment]
With retronym's suggestion the testsuite fails only on FutureTests on a copy of the testcase, namely on
`future { 14.toString }` (coming from `future { (7 * 2).toString }`). Since `future` takes a by-name argument, that's the same testcase as in the bug report, so nothing new there except maybe details of the stacktrace (which I'll post on request).
So, I would suggest dropping this code from 2.10.x; I would submit any fixed version of the optimization only onto master.

I instead do not get this exception on the following code, where the optimization is supposed to apply.

``` scala
  def foo() = ()
  def client(f: () => Unit) = f()
  def attempt2() {
    val bar: () => Unit = foo _
    client(() => bar ()) //####### this could just be client(bar).
  }
```

The problem seems to be that `() => bar ()`, after typer, has been rewritten to `() => bar.apply()`, as `-Xprint:typer` shows:

``` scala
      Test.this.client((() => bar.apply()))
```

and `isExprSafeToInline(bar.apply)` correctly returns `false`, so `deEta` skips the optimization. If this is always the case for `Function0` (and I guess), the optimization pattern is never going to match on `Function0`. And for by-name parameters, I guess Scalac already takes care not to construct code like the above.

**Comment by gkossakowski** [comment]
From the last comment I don't see what's the status of this pull request? Should it be superseded by the one that removes questionable optimization or something else should be done?

**Comment by retronym** [comment]
Yes, we need to amend this one to delete that code. @Blaisorblade, care to do so?

**Comment by Blaisorblade** [comment]
Thanks, I was waiting for a decision either way. Will push the fix ASAP (later today).

**Comment by retronym** [comment]
If you wanted to be super thorough (and nostalgic), you could try to build 45bcd02 and do the same experiment to see if that code was ever called.

**Comment by Blaisorblade** [comment]
This commit implements the required fix and replaces the old one. @retronym, it seems the code was dead even when introduced.

I just checked that even when it was introduced, that pattern didn't match either while bootstrapping the compiler or while building the original testcase; the code is transformed the same way. I'm now running the testsuite on the old compiler (I just found out how).
Pull request status: pending, will ping as soon as the testsuite is done.

**Comment by Blaisorblade** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
Fantastic sleuth work! Code coverage reporting for the compiler would be a godsend.

One tiny suggestion: can you tweak the commit comment in line with the pull request policy?

``` diff
-Fix SI-6306 on testcase, try #2
+SI-6306 Remove incorrect eta-expansion optimization in Uncurry
```

Otherwise, LGTM

**Comment by Blaisorblade** [comment]
Great!
I fixed the commit subject as requested, but the code is otherwise unchanged (to wit, git diff 39ca62f..9568dc9 gives empty output), so a retest shouldn't be needed.
The testsuite completed as expected (with a few completely unrelated failures); if anybody is interested, the code is at Blaisorblade/scala@09626729c7cb3a422ce99e169d1fd3bf7fd14d79.

**Comment by jsuereth** [comment]
Ok, @retronym gave it a LGTM, I'm for it, how bout you @paulp or @gkossakowski ?   Three amigos and she's in.

**Comment by paulp** [comment]
Looks bueno to me.

**Pull request merged**
