### PR TITLE
Unit companion is compileTimeOnly

### PR DESCRIPTION
**Pull request by som-snytt**
Rebase of https://github.com/scala/scala/pull/7567

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM for merge after squash/rebase

**Comment by som-snytt** [comment]
Refreshing my memory: previously, "flipping the switch" was a separate commit because it required a fresh starr. (A STARR is Born!) The innovation here is that the "group" mechanism only requires a type, so additional groups were added to cover the compiler and library.

**Comment by som-snytt** [comment]
Non-trivial merge makes you wonder how annotations became a hot spot for change.

Impossible to rely on communication over deltas when a PR sits for a year.

A useful feature would be for github to let me know in advance if there is already a PR that touches some code, or more precisely, warn someone else that their new PR will force me to rebase my existing PR. Americans don't care about universal health care or a just justice system, but by gum, "first come, first served" is inviolable.

**Comment by SethTisue** [comment]
thanks, Som, for your patience, as always.

**Pull request merged**
