### PR TITLE
Accept consecutive if in for loop

### LINKED ISSUE #12323: parser error: multiple if-guards on the same line in for-comprehensions
using Scala 2.13.4

According to scala syntax (https://www.scala-lang.org/files/archive/spec/2.13/13-syntax-summary.html)
```
Generator ::=  Pattern1 ‘<-’ Expr {[semi] Guard | semi Pattern1 ‘=’ Expr}
```
several guards on the same line is a valid code.
But unfortunately, if you place several guards on the same line, starting from a new line, a compilation error occurs.

```scala
for {
  x <- 1 to 5 if true if true
} yield x

for {
  x <- 1 to 5 if true
  if true
} yield x

for {
  x <- 1 to 5
  if true if true
} yield x

for {
  x <- 1 to 5
  if true
  if true
} yield x
```

image

related issue: https://youtrack.jetbrains.com/issue/SCL-13220

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12323

It looped in generator but not enumerator.

### CODE REVIEW

**Comment by SethTisue** [comment]
(as per the bug ticket, there is some question of whether the spec should instead be adjusted to match the implementation)

**Comment by SethTisue** [comment]
marking as draft pending the outcome of the discussions on https://github.com/scala/bug/issues/12323 and https://github.com/lampepfl/dotty/pull/11215 — let's not have a third discussion here :-)

**Comment by som-snytt** [comment]
@SethTisue this is just a bug. For the discussion, start a thread on contributors. In the context of Scala 3 syntax, the implementation is a better arbiter than the syntax doc.

**Comment by SethTisue** [comment]
> @SethTisue this is just a bug.

(that's my current understanding/leaning as well, but I want to be sure)

**Comment by som-snytt** [comment]
Are we ever really sure?

**Comment by SethTisue** [comment]
let's at-mention the @scala/epistemology team and see if we can get an expert ruling on that

**Comment by dwijnand** [comment]
> @SethTisue this is just a bug. For the discussion, start a thread on contributors. In the context of Scala 3 syntax, the implementation is a better arbiter than the syntax doc.

Personally I believe the opposite is true: the bug is in the Scala 2 spec and the Scala 3 impl.  I don't see why `if a; if b` isn't entirely fine (in lieu of multi-line).  Personally I'd go as far as always requiring a semicolon before guards as I find `x <- xs if p` to look like I'm filtering xs before taking an x, i.e. I mentally parse it as `x <- (xs if p)` (thereby `p` not having access to `x`) rather than `(x <- p) if p`, which is why I think `x <- xs; if p` (or better yet multi-line) makes more sense - but I assume it's too commonly used.

**Comment by SethTisue** [comment]
@dwijnand the discussion is on the other tickets

**Comment by SethTisue** [comment]
on the Dotty ticket, Martin confirmed that this PR should go forward, and the Scala 3 spec should be changed

> but I assume it's too commonly used

yeah, that sail has shipped :-)

**Review by SethTisue — APPROVED** [review]

**Comment by som-snytt** [comment]
@dwijnand my proposal in 2014 was to require explicit semi only after midstream assignment. The idea was that the if is distinctive after the left arrow but less distinctive after the imperative-looking assignment.

```scala
scala> for (x <- List(42) if x > 0 if x < 50) yield x
val res0: List[Int] = List(42)

scala> for (x <- List(42) ; y = 2 * x if x > 0 if y < 100) yield x
val res1: List[Int] = List(42)
```

Commenting here as a side bar to the third discussion.

What's really needed is `iff` for a condition that is evaluated before the generator:
```scala
for (x <- vs iff debug) println(x)
```

Edit: I guess the meaning of the comment on Dotty to "drop optional semi" is "disallow semi" and not "make it not-optional, i.e., require it".

**Comment by dwijnand** [comment]
Indeed, that `if` is even more insane, I agree.  But apparently the marina is empty.

**Review by lrytz — APPROVED** [review]

**Pull request merged**
