### PR TITLE
Extend documentation contacts

### PR DESCRIPTION
**Pull request by janekdb**
Review by @heathermiller, @dickwall, @som-snytt.

### CODE REVIEW

**Comment by janekdb** [comment]
:sparkles: I am quite happy to field the odd documentation question now and again :sparkles:

**Comment by janekdb** [comment]
Needs a rebuild after the repo problem is solved:

http://www.codehaus.org/mechanics/maven/ - Codehaus no longer serves up Maven repositories,

**Comment by som-snytt** [comment]
Just an idea, maybe it's time to enable reverse lookup. If I want to communicate with doc gurus, how do I pick one? Because frankly I'd always pick heathermiller as least scary. Maybe make the category "documentation" a mail link to all doc folks? And similarly for other areas of expertise.

Or maybe the link is a drop-down with the experts listed in random order with a default selected.

The experience on PRs of choosing someone to Review and then it's never that person, except back when paulp was the only person, makes you think you're doing it wrong.

**Comment by adriaanm** [comment]
:sparkles: yay! thanks, @janekdb! :sparkles: 

Infra issue tracked at https://github.com/scala/scala-jenkins-infra/issues/116

**Comment by SethTisue** [comment]
maybe we should photoshop fangs and weapons onto Heather until she's just as scary looking as the rest of us.

I agree that a better mechanism for finding reviewers would be good... but I don't have an idea for one. 

But @janekdb, thanks for the offer... expect an occasional "Hey @janekdb want to review this?" from me in the future.

I'll merge once I get the infra issue sorted out.

**Comment by janekdb** [comment]
Great news! Thanks.

**Comment by som-snytt** [comment]
The Scalawags pirate look would suffice to scarify potential reviewers. Who is the welcome-to-Scala experience contact?

Today my heart dropped because I thought I'd broken the vaunted welcome-to-Scala experience, until I realized I'd set an alias before going on vacation:

```
skala is aliased to `~/projects/scala/build/pack/bin/scala -Dscala.repl.welcome="Welcome to Scala %#.6s (%3\$s %2\$s)"'
```

**Comment by mpociecha** [comment]
I always thought that this list of contacts is also some kind of a hall of fame, and it contains people whose opinion is enough to decide whether PR should be merged or not. Otherwise you could expect many other PRs (I mean like this one) created by people who are eager to review something and would like to be added to this list. Anyway everyone can take a look and review all pull requests - there are notifications about all of them.

// Even though README.md contains this text: "If you have some spare time to help out around here, we would be delighted to add your name to this list!". Just my opinion. :) Maybe it's intended to have there a lot of people even if only part of them can really decide that something is okay and can be merged.

**Comment by janekdb** [comment]
One way of looking at this is that if the list did become unwieldy it would be a nice problem to have.

Along with the excerpt from the README.md above, CONTRIBUTING.md identifies this as a source of willing reviewers,

> Your PR will need to be assigned to one or more reviewers.  You can suggest reviewers yourself;
> if you're not sure, see the list in [README.md](README.md) or ask on scala-internals.

**Comment by SethTisue** [comment]
@mpociecha I see what you mean, but on the other hand, even veteran reviewers are often in a position where they don’t know if a single other human being besides the original submitter has sanity-checked the changes. it's useful to have multiple levels of review. and, some prospective contributors might actually be more comfortable with asking someone outside the “hall of fame” to take a first look.

for y’all who watch this repo and might therefore read this: comments and “LGTM”s (especially if accompanied by a brief description of the scrutiny given) are welcome and encouraged from anyone with a little spare time.

love, Seth.

**Comment by adriaanm** [comment]
:heart:++

**Comment by mpociecha** [comment]
@SethTisue Obviously it makes sense. Thanks for the explanation. :)

**Pull request merged**
