### PR TITLE
Toward more organized typer state.

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm or any of the usual malcontents

**Comment by paulp** [comment]
Feedbacks incorporated and rebased upon master. Any further comments solicited.

**Comment by xeno-by** [comment]
Some high-level questions, before I start looking into details:

1) What modes do you plan to eliminate in the long run? Is it literally every single mode, or you find some modes to be absolutely necessary?

2) In the new scheme of things how does one switch into a different mode? Something like `typer.inFooMode(_.typed(...))`?

3) What evolution path do you see for `typingXXXYYY` methods in `Mode.scala`? When do we add new methods there? What happens if we end up having a whole bunch of such methods?

**Comment by paulp** [comment]
Rebased and resolved merge conflicts, incorporated name change suggestions and other feedback.

**Comment by paulp** [comment]
Realized I was nuts for trying to rebase 7 commits for which the tests had already passed, and sensibly merged master into the branch.

**Comment by retronym** [comment]
Apologies, I just merged Adriaan's volatile type patch which conflicts with this one.

**Comment by xeno-by** [comment]
lgtm

**Comment by retronym** [comment]
:gift: Here's a merge https://github.com/retronym/scala/compare/merge/master-to-2492

**Comment by paulp** [comment]
Please don't hurt my code no more, sir. I'll do anything you say, just don't hurt my code no more.

**Comment by paulp** [comment]
NOLITTER

**Comment by paulp** [comment]
PLS SYNCH

**Comment by paulp** [comment]
Gasp, it is "good to merge" and "can be automatically merged", we must act! @retronym @adriaanm @xeno-by please object at your earliest convenience if there is any pressing matter I have not addressed.

**Comment by xeno-by** [comment]
LGTM

**Pull request merged**
