### PR TITLE
SI-6448 Collecting the spoils of PartialFun#runWith

### PR DESCRIPTION
**Pull request by retronym**
Avoids calling both `isDefinedAt` and `apply`. This pathological
case that would benefit the most looks like:

``` scala
  xs collect {
    case x if {expensive(); true} => x
  }
```

The typical change looks like:

``` diff
-    for (x <- this) if (pf.isDefinedAt(x)) b += pf(x)
+    foreach(pf.runWith(b += _))
```

Incorporates feedback provided by Pavel Pavlov:

  https://github.com/retronym/scala/commit/ef5430

A few more opportunities for optimization are noted in the
`Pending` section of the enclosed test. `Iterator.collect`
would be nice, but a solution eludes me.

Calling the guard less frequently does change the behaviour
of these functions in an obervable way, but not contravene
the documented semantics. That said, there is an alternative
opinion on the comment of the ticket:

  https://issues.scala-lang.org/browse/SI-6448

Review by @axel22 @pavelpavlov

### CODE REVIEW

**Comment by Blaisorblade** [comment]
I'm the one who gave the contrasting opinion - but I think that merging in master (hence in 2.11) is a good solution. By contrast, I would object against accepting such observable changes in 2.10.1 while guaranteeing binary compatibility with 2.10.0 (and I just figured that was also my conclusion one month ago, when we discussed the issue).

@jsuereth, what's the level of compatibility guaranteed between minor releases? My guess at it would imply that this can only go in in 2.11. But making this explicit is even more important than what the actual guarantee is and what is the consequence on this pull request (that is, where to merge).

I think that the release manager should publish whatever guideline we have, so that users can actually take advantage of any guarantees and developers can stick to them more easily and spend less debating time. How flexible these guidelines should be is a question for release managers and the community.

**Comment by axel22** [comment]
The change looks good to me from a correctness point of view.

It would be nice, however, if we could have a performance characterization for these changes. It's obvious that for the pathological cases there is a win, but I wonder what happens when the pattern match is inexpensive (and what's the ratio of such cases in the code in the wild).
Even if we ignore the extra method calls we will have with the change, note that we now create objects where we didn't create objects before - in patterns such as array traversal above, that means 2 object allocations per iteration. Unless escape analysis kicks in to do this allocation on the stack, we could be losing a lot. I'm not sure if we can just hope that it will happen.

For example, `runWith` creates 2 objects instead of no objects before - this affects `TraversableLike`, `RemainsIterator` and `ParArray`. Patterns with `lift` like the one in `Option` create 2 objects now instead of 1. `Stream`s create so much extra stuff that nobody cares, but `TraversableLike` users could care.

I would suggest writing a microbenchmark for the traversals above to see if there is a performance change, if any.

**Comment by retronym** [comment]
Agreed, benchmarks are needed.

One thing that isn't obvious af first glance is that the code above only allocates once the call to `collect`, not for each element.

**Comment by axel22** [comment]
Ah, sorry - I missed that bit.

**Comment by jsuereth** [comment]
@Blaisorblade I think the _only_ reasonable "default" position we can take to users expecting side-effects in functions where it is undocumented is potential future breakage in any release.   Tieing yourself to the internal implementation of a higher-order-function is dangerous and gives us less flexibility for fixing performance issues for everyone.

That said, we can't just go break anyone's code that hasn't read the documentation and works by example.

I think you're right, that this is a good fix for 2.11.  However, nothing in premise prevents this from going in 2.10.x, just the more loosey-goosey rule of "Try to avoid breaking user code".

**Comment by Blaisorblade** [comment]
I'm thinking of the use case where a user plans the effort for upgrading to
a minor release. Is there a policy for version compatibility on Scala's
website (or in any other single, prominent location)?
It doesn't have to give extremely strict rules. The more loosey-goosey rule
of "Try to avoid breaking user code" should also be in there in some form.
This way, users could know what to expect, and we would have less to
discuss each time.

Here's an extremely rough example to show which questions it should answer;
I don't get to decide the answers, so some of them are mostly (bad) jokes,
usually when I couldn't figure out a good answer. I can repost this on the
mailing list if there is at least some interest.

# 

Upgrading from 2.x.y to 2.x.y+1 (for x >= 10) does not require recompiling
(with the exceptions of features marked as experimental, such as reflection
in 2.10.0).

Your code should work as-is, except if it relied on undocumented behavior
of the Scala API. Bug fixes impacting undocumented behavior will be
discussed on a case-by-case basis, by considering for instance any known
reasonable use cases relying on the undocumented behavior.
If you rely on undocumented behavior and your code breaks, it's your
problem and you get to keep the pieces, and if you complain after release,
people will make fun of you. If you complain during RC time, you might be
able to convince us to fix the code.

If somebody breaks documented behavior, he'll have to walk on his/her arms
for one mile on a moving cruise boat.
[More reasonably, changes to documented behavior will be avoided at all
costs.]

# 

Instead, upgrading from 2.x to 2.x+1 means that
- Any functionality deprecated in 2.x might disappear in 2.x+1.
- Undocumented behavior will be changed wherever we see fit. We'll try to
  list the cases in release notes; since other changes might be found after
  release, those changes will also be on a wiki page.
- In fact, we'll also change documented behavior if we don't like it.
  Whenever we please. So you better rewrite your code from scratch each time.
  [Of course that's not the case, but what's the guarantee here?]
- Going from 2.x to 2.x+2 might imply bigger changes.

# 

When going from x.y to x+1.0, many things might change. See [Martin's
"Scala: a roadmap" email] for what might change in Scala 3.0, if it ever
appears (all of the features are hidden behind language.\* imports if you
use -feature).

**Comment by adriaanm** [comment]
ping @axel22 -- do we have LGTM?

@Blaisorblade, these are all good thoughts, though some of the jokes are dubious :-)
I'd love to see a discussion about this on the mailing list

(sorry, this slipped through!)

**Comment by axel22** [comment]
Yeah, lgtm!

**Pull request merged**
