### PR TITLE
Keep sbt's log level at info on travis / jenkins

### PR DESCRIPTION
**Pull request by lrytz**
Setting `--warn` hides the `downloading ... scala-compiler-2.12.4.jar`
messages (which I was looking for to ensure clearing the caches has
the intended effect).

Compared to the current state, it doesn't add a significant amount of
noise on travis. Note that the travis log has folded sections, so
it's easy to look at individual parts.

There are still `--warn` arguments in the pr validation and windows
scripts that I didn't touch here.

### CODE REVIEW

**Comment by lrytz** [comment]
There are no functional changes, so in principle the build for 89d79ddadc4de6bc5de2f359eca91aaf38f1daf0 should be fine. I just got (very) confused by the missing `[info] downloading ...` messages.

On the other hand, maybe we want to re-run it anyway: the build for 89d79ddadc4de6bc5de2f359eca91aaf38f1daf0 failed to download the `0xa9052b1b6d92e560` key from `pgp.mit.edu` in the `init.sh` script (https://travis-ci.org/scala/scala/jobs/353870602). This seems to happen from time to time. @adriaanm:
  - should we fail the build in this case? The init script should probably get an `-e` flag for its bash shebang.
  - the missing key didn't seem to affect the release process though - maybe it's not necessary after all, as suggested by the commet ("pgp signing doesn't work without public key??")

**Comment by adriaanm** [comment]
yeah, the public key is probably not needed -- the real fix was to explicitly set the pgp signing key to the secret subkey

**Comment by lrytz** [comment]
OK, then I declare 2.12.5 built - will do some more (manual) smoke testing / artifact diffing.

I updated this PR with a few more cleanups.

**Review by adriaanm — APPROVED** [review]
Double-plus :100:

**Pull request merged**
