### PR TITLE
SI-7475 use intersection type for pattern type

### PR DESCRIPTION
**Pull request by adriaanm**
Usually, the type of a pattern binder is an intersection of
the scrutinee type and the pattern type.

We used to "simplify" this intersection to eliminate
"redundancies", so that `intersect(Sub, Super)` will just
be `Sub` (where `Sub` <:< `Super`).

But, if we are nested in `Super` there is an observable difference
between `Sub` and `Sub with Super`. Only the latter will allow
use to select private members of `Super`.

### CODE REVIEW

**Comment by adriaanm** [comment]
Admittedly a bit of a shot in the dark, review by @retronym if tests pass.
Otherwise, I think we can let this one slide. People will have to annotate their patterns a bit more precisely if they hit this corner case.

**Comment by adriaanm** [comment]
Great, TrieMap strikes again. I'm getting flashbacks to my virtpatmat days.

**Comment by adriaanm** [comment]
One of them (and I assume the others as well) are fixed by adding a redundant self-type, which shows that the bug lies with tailcalls, which looks at pre-erasure types to reason about run-time behavior.

``` patch
-) extends MethodCache {
+) extends MethodCache { self: MethodCache with PolyMethodCache =>
```

**Comment by retronym** [comment]
I reckon doing this across the board is too risky. Better to have a special case to only do it when it could make a difference, or not at all.

**Comment by retronym** [comment]
```
[quick.partest-extras] Compiling 10 files to /localhome/jenkins/a/workspace/pr-scala-publish-core/scala/build/quick/classes/partest-extras
[quick.partest-extras] error: java.lang.ClassCastException cannot be cast to scala.reflect.internal.Types$TypeError
[quick.partest-extras] one error found
```

I wonder what this is? A binary incompatibility between the compiler and partest?

I had hoped that `intersectionDominator` (used to erase refined types) would have made your change binary compatible.

**Comment by adriaanm** [comment]
> I reckon doing this across the board is too risky. 

Yep (I just wanted to push it as far as I could on a Friday night and see what happened).

> Better to have a special case to only do it when it could make a difference, or not at all.

If we can't fix this properly now, I'd rather have people work around this until we can, as I understand it to be a tiny corner case that can easily be avoided by specifying `(C with D)` instead of `C`.

**Pull request closed without merging**
