### PR TITLE
SI-9375 add synthetic readResolve only for static modules

### PR DESCRIPTION
**Pull request by lrytz**
For inner modules, the synthetic readResolve method would cause the
module constructor to be invoked on de-serialization in certain
situations. See the discussion in the ticket.

Adds a comprehensive test around serializing and de-serializing
modules.

### CODE REVIEW

**Comment by lrytz** [comment]
review by @retronym, @axel22

**Comment by axel22** [comment]
I didn't closely inspect the unit test, but the change looks good to me overall.

**Comment by lrytz** [comment]
Here's one interesting part of the test - but that didn't change with this PR, it's the same before and after.

```
scala> object A {
     |   object a extends Serializable
     |   val b: Object = { object B extends Serializable; B }
     | }
defined object A

scala> serializeDeserialize(A.a) eq A.a
res0: Boolean = true

scala> serializeDeserialize(A.b) eq A.b
res1: Boolean = false
```

**Comment by axel22** [comment]
That makes sense to me - `object B` is local to the initializer block, so it's not top-level (i.e. static).

I took another look at the tests now - looks good.

**Comment by axel22** [comment]
LGTM

**Pull request merged**
