### PR TITLE
Making map2Conserve occupy constant stack space in spirit of SI-2411.

### PR DESCRIPTION
**Pull request by folone**
I recently discovered a StackOverflowError, caused by this function: https://gist.github.com/folone/7b2f2e2a16314ab28109
The circumstances are pretty extreme, still having a tail-recursive function seems to be a good idea.
The function behaves the same way old function did (supported by tests), which is not really how map2 behaves. I did not change this behavior to not introduce any regression. I actually tried to make it behave like map2, and it does introduce regression.
I also think, I found a better home for this function.

### CODE REVIEW

**Comment by folone** [comment]
review @adriaanm @retronym

**Comment by retronym** [comment]
Can you please submit this as two separate commits: one to refactor the implementation, and another to move move it to its new home? That makes the diff easier to review.

**Comment by folone** [comment]
@retronym done.

**Comment by gkossakowski** [comment]
@retronym: ping

**Comment by retronym** [comment]
I think this looks okay from a performance perspective. 

For perspective, here's how long the old version takes:

image

And the callers to it:

image

The one thing that is missing is a pair of comments in `List#mapConserve` and `map2Conserve` to note the duplication between them. That might help avoid drift between the implementations down the track.

For reference, SI-2411 was implemented in 54b5eacb56d21664e53b92d1e5c58195538caef4.

**Comment by retronym** [comment]
Can you please tidy up the commit comments in line with https://github.com/scala/scala/blob/master/CONTRIBUTING.md ?

Here's what they look like without word wrapping:

image

It would also be best if your git config `user.name` contained your full name.

**Comment by folone** [comment]
Alright, that should do it.

**Comment by folone** [comment]
And rebased it onto the latest master.

**Comment by folone** [comment]
Can I do anything to fix failing jobs in the previous two comments, or is this particular validation broken at the moment?

**Comment by adriaanm** [comment]
Thanks for looking into it, but there's nothing you're required to do.
These are mostly for stress-testing the new PR validation infrastructure.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
NOLITTER!

**Comment by folone** [comment]
PLS REBUILD ALL

**Comment by folone** [comment]
:crying_cat_face:

**Comment by folone** [comment]
PLS REBUILD/pr-scala@b145cb1

**Comment by folone** [comment]
PLS REBUILD/pr-scala@b741e8a

**Comment by adriaanm** [comment]
Jenkins slave ran out of disk space... (It's off-line now.)

**Comment by folone** [comment]
Yay! :smiley_cat:

**Comment by gkossakowski** [comment]
@adriaanm @retronym: what's the status of this PR?

**Comment by retronym** [comment]
LGTM

**Pull request merged**
