### PR TITLE
Disable 'unreachable' test for GenBCode

### PR DESCRIPTION
**Pull request by lrytz**
GenICode has some logic to eliminate some dead code directly at code
gen (introduced in b50a0d811f for SI-7006). This has not been ported
over to GenBCode.

GenBCode with the new optimizer (in Miguel's branch) also eliminates
such dead code. Before adding such functionality to GenBCode I'd like
to investigate the cost of running DCE. Maybe we can keep the code
generator simple.

I created SI-8568 to keep track of this.

### CODE REVIEW

**Comment by lrytz** [comment]
review by @gkossakowski

**Comment by dragos** [comment]
Just a note: in some cases dead code elimination is required for correctness. That was the reason for the _ignore_ mode in the old code generator. For example, after a method returning `Nothing`, if there's a merge, the verifier might fail.

```
  println(if (cond)
    error("...")
  else
    10)
```

The stack after `error` is empty, while the other branch has one value. This type-checks in Scala, but not on the JVM (who does not understand the type "Nothing"). So emitting any code after the call to error (especially the jump to a common block that merges the two branches) would fail verification.

**Comment by lrytz** [comment]
Thanks for the comment, Iulian. I'll keep the issue in mind.

GenBCode seems to work around the issue by generating an `athrow`.

``` scala
def adapt(from: BType, to: BType) {
  [...]
  } else if (from.isNothingType) {
    emit(asm.Opcodes.ATHROW) // ICode enters here into enterIgnoreMode, we'll rely instead on DCE at ClassNode level.
```

example:

``` scala
  def f(x: Boolean) {
    println(if (x)
      sys.error("")
    else
      10)
  }
```

gives

```
   0:  getstatic  #19; //Field scala/Predef$.MODULE$:Lscala/Predef$;
   3:  iload_1
   4:  ifne  10
   7:  goto  22
   10:  getstatic  #24; //Field scala/sys/package$.MODULE$:Lscala/sys/package$;
   13:  ldc  #26; //String 
   15:  invokevirtual  #30; //Method scala/sys/package$.error:(Ljava/lang/String;)Lscala/runtime/Nothing$;
   18:  athrow
   19:  nop
   20:  nop
   21:  athrow
   22:  bipush  10
   24:  invokestatic  #36; //Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
   27:  invokevirtual  #40; //Method scala/Predef$.println:(Ljava/lang/Object;)V
   30:  return
```

**Comment by dragos** [comment]
`athrow` should work as well, but generates some "garbage".

**Comment by lrytz** [comment]
right. it will be eliminated by the DCE. we'll see if performance of that approach is ok or if we need to push some DCE directly into the code generator.

**Comment by gkossakowski** [comment]
LGTM

Why in the listing above we have `athrow; nop; nop; athrow` sequence?

**Comment by lrytz** [comment]
i don't know, haven't dug deep enough into GenBCode yet.

**Comment by lrytz** [comment]
> Why in the listing above we have `athrow; nop; nop; athrow` sequence?

I figured that out now. When the (GenBCode) backend generates code for an expression of type `Nothing` and the expected type is not `Nothing`, it adds an `athrow`. The bytecode generated by `BCodeBodyBuilder` is

```
GETSTATIC scala/Predef$.MODULE$ : Lscala/Predef$;
  ILOAD 1
  IFNE L2
  GOTO L3
 L2
  LINENUMBER 4 L2
  GETSTATIC scala/sys/package$.MODULE$ : Lscala/sys/package$;
  LDC ""
  INVOKEVIRTUAL scala/sys/package$.error (Ljava/lang/String;)Lscala/runtime/Nothing$;
  ATHROW
  GOTO L4
 L3
  LINENUMBER 6 L3
  BIPUSH 10
  INVOKESTATIC scala/runtime/BoxesRunTime.boxToInteger (I)Ljava/lang/Integer;
 L4
  INVOKEVIRTUAL scala/Predef$.println (Ljava/lang/Object;)V
  RETURN
```

Note that code generation continues after the `ATHROW`, there's a `GOTO L4`. That's different than `GenICode`, which goes in "ignoreMode" after emitting an `athrow`.

When serializing the bytecode, the ASM library detects instructions that end the current basic block (returns and throws) and starts a new one. The `GOTO L4` is therefore emitted into a new basic block.

Note that the `goto` instruction uses three bytes in [serialized form](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5.goto): one for the instruction and two for the target.

A little bit later during serialization, the ASM library realizes that the basic block containing the `GOTO L4` is unreachable (dead code). For that reason it replaces all of its instrucitons by `nop`'s, and the final instruction by an `athrow` (both of them take one byte).

The code: search for "replaces instructions with NOP ... NOP ATHROW" in [MethodWriter.java](http://websvn.ow2.org/filedetails.php?repname=asm&path=%2Ftrunk%2Fasm%2Fsrc%2Forg%2Fobjectweb%2Fasm%2FMethodWriter.java).

The serialization does not actually remove the dead code, I guess that would be too complicated (shifting rest of the array and fixing up all indices).

Let me add that the example by @dragos actually does not trigger a verification error if we don't emit the `athrow`, but it has some relatives that show the problem:

```
def f(x: Boolean) {
  println(if (x) {
    sys.error("")
    20  // produces a VerifyError 'Inconsistent stack height'
  } else
    10)
}

def f: String = ??? // needs to throw after invoking ???, otherwise there's VerifyError 'Wrong return type'
```

**Comment by gkossakowski** [comment]
Thanks for detailed explanation! Makes sense now. Am I right that the optimizer Miguel implemented would get rid of the dead code and reshuffle bytecode appropriately?

**Comment by lrytz** [comment]
Yes

**Pull request merged**
