### PR TITLE
Do not use `rangeHash` when `rangeDiff` is 0 [ci: last-only]

### LINKED ISSUE #12826: MurmurHash3 produces the same hash for lists of repeated values, regardless of list length
## Reproduction steps

Scala version: 2.13.2

```scala
scala> println(Seq(17, 17).hashCode)
-1314960578
scala> println(Seq(17, 17, 17).hashCode)
-1314960578
```

## Problem

The implementation of [MurmurHash3.listHash](https://github.com/scala/scala/blob/e48c7888a0ae08b8d273f03bfc62452fc2ed886d/src/library/scala/util/hashing/MurmurHash3.scala#L274C19-L274C19) attempts to make the hashes of lists that are equivalent to a range the same as that of the range. It does this by recording the difference between the first and second item in the list, and then testing whether the difference between subsequent consecutive pairs in the list is the same or not. When all differences between consecutive pairs are the same, it recognizes this as a sequence and falls back on `rangeHash`, which only accounts for the first and last values in the "range", and the difference, which it treats as the step size of the range.

The current implementation does not correctly account for the case when the elements in the list are all the same. The difference between hashes of consecutive elements in this case is zero, and thus an invalid step size for a range. But since the difference is consistent between all pairs, it is still treated as a range for hashing purposes. With the first and last elements being the same regardless of the size of this list, this means that the hash will be the same regardless of the list size.

This seems like incorrect behavior as it violates the expectation that the algorithm produces well-distributed hashes, and the logical assumption that two lists with different lengths are _unlikely_ to produce the same hash, regardless of specific elements they contain. The algorithm should be modified to differentiate sequences of the same element so that they are not treated as potential ranges. I believe that simply checking that `rangeDiff` is not 0 may be sufficient.

Although the implementations vary, [arrayHash](https://github.com/scala/scala/blob/e48c7888a0ae08b8d273f03bfc62452fc2ed886d/src/library/scala/util/hashing/MurmurHash3.scala#L158), [orderedHash](https://github.com/scala/scala/blob/e48c7888a0ae08b8d273f03bfc62452fc2ed886d/src/library/scala/util/hashing/MurmurHash3.scala#L122C13-L122C24), and [indexedSeqHash](https://github.com/scala/scala/blob/e48c7888a0ae08b8d273f03bfc62452fc2ed886d/src/library/scala/util/hashing/MurmurHash3.scala#L237) all have similar optimizations, and appear to likely have the same issue.

### PR DESCRIPTION
**Pull request by Friendseeker**
Closes https://github.com/scala/bug/issues/12826 via implementing https://github.com/scala/bug/issues/12826#issuecomment-1631690002

### CODE REVIEW

**Comment by Friendseeker** [comment]
```
java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:346)
	at PluginClassLoader for git-client//org.eclipse.jgit.internal.storage.file.LockFile.write(LockFile.java:292)
	at PluginClassLoader for git-client//org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:205)
	at PluginClassLoader for git//jenkins.plugins.git.GitHooksConfiguration.disable(GitHooksConfiguration.java:138)
	at PluginClassLoader for git//jenkins.plugins.git.GitHooksConfiguration.lambda$configure$2f1f6402$1(GitHooksConfiguration.java:112)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:28)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:83)
```

https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/19241/console

Thanks CI

**Comment by Friendseeker** [comment]
@SethTisue Request for advice on the [CI failure](https://github.com/scala/scala/pull/10912#issuecomment-2455999268) due to CI machine running out of disk space. I tried rebase push but that did not resolve the CI failure (I was hoping a force push would allocate a different machine for `validate-main` but apparently not...)

`rebuild` command also did not help resolve the issue.

**Comment by SethTisue** [comment]
I deleted some community build caches, should be okay now.

**Comment by lrytz** [comment]
LGTM. Can we change `hashCode` in a minor release?

**Comment by SethTisue** [comment]
> LGTM. Can we change hashCode in a minor release?

Yes, as documented since 2020, as per #9051 and https://github.com/scala/bug/issues/11646 . Admittedly that issue and PR didn't attract much attention/discussion. But they also haven't attracted any pushback, either at the time or in the years since.  cc @scala/collections @Ichoran 

Let's release-note it regardless (especially since the 2.13.16 release notes won't be that long).

In a Scala 3 context, it's a bit less clear-cut. Normally Scala 3 takes our standard library _minor version_ bumps in their Scala LTS _patch version_ bumps. Does that change the answer here? I would argue it doesn't, because

* it's documented as being fair game (though I admit there is some ambiguity around the "patch version" wording; we normally say that Scala 2 versions are "epoch.major.minor" not "major.minor.patch", so the doc can be read as referring to Scala 2 minor versions even if it literally says "patch")
* it's a bugfix or refinement, not a feature addition or design change. we are bringing the implementation in line with an intention that has not changed
* people realllllllly shouldn't be relying on this stuff not changing — so if it changes once in a while (for a good reason), it's a good reminder of that

I don't doubt that some codebases will see some test failures because they were (perhaps inadvertently) relying on hash order, but IMO our stance should be that those tests were overly sensitive to begin with and it's normal to ask users to either 1) make them less sensitive, or 2) leave them sensitive for convenience but with the awareness that as a consequence they may need adjusting at Scala version bump time.

**Comment by OndrejSpanel** [comment]
How will this cope with `Seq(17)` compared to `17 to 17`?

**Comment by sjrd** [comment]
> How will this cope with `Seq(17)` compared to `17 to 17`?

In the changed code paths, we already know the `size >= 2`, so `Seq(17)` is not affected by this PR.

**Comment by lrytz** [comment]
@Friendseeker could you squash the changes in a single commit?

**Comment by Friendseeker** [comment]
> @Friendseeker could you squash the changes in a single commit?

Done!

**Pull request merged**
