### PR TITLE
Improve testing interactive experience.

### PR DESCRIPTION
**Pull request by vigdorchik**
Currently the exceptions that happen in the test are swallowed, as
the JVM is forced to exit before printing the stack trace.
Also assert message doesn't contain information about the problem.

The call to "sys.exit" masks bugs in the testing framework, that
has to be addressed more elaborately, so here we remove it. Also
add the message parameter to assert to make it more informative.

After removing "sys.exit" call, doc test starts failing. I suspect
there might be a problem when expanding doc variables, but this
should be addressed separately.

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @dotta.

**Comment by paulp** [comment]
LGTM

**Comment by dotta** [comment]
Ups, I forgot about this.

The only reason I can think of for that code to exist is that the running test didn't always terminate. For instance, it does happen from time to time that the Scala IDE freezes because code wait for an answer from a resetted (/no longer active) presentation compiler instance (e.g., https://scala-ide-portfolio.assembla.com/spaces/scala-ide/tickets/1001505#/activity/ticket:).

**Comment by dotta** [comment]
They are both bugs. The presentation compiler is definitely allowed to shutdown/reset as he believes its best, but pending requests should be cancelled and the callers should be notified. However, that doesn't always happen, as you can see in the linked ticket.

**Comment by dotta** [comment]
Absolutely. Though, I hope that if the presentation compiler tests start hanging, that won't result in all of the tests being disabled.

**Comment by dotta** [comment]
Then I'm super glad we get this merged! :)

**Pull request merged**
