### PR TITLE
SI-8185 Correct grammar for single-warning compilation run

### PR DESCRIPTION
**Pull request by huitseeker**
This is a re-issue of #3419

50-odd updated tests (!)
review by @retronym

### CODE REVIEW

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by huitseeker** [comment]
PLS REBUILD ALL

**Comment by huitseeker** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
LGTM.

**Comment by huitseeker** [comment]
\o/ Yay !

**Pull request merged**
