### PR TITLE
type safety: replaced getOrElse with fold

### PR DESCRIPTION
**Pull request by jyotisachdeva57**
Replaced getOrElse with fold for better type safety

### CODE REVIEW

**Comment by dwijnand** [comment]
Why do you say this is more type safe?  `getOrElse` is a perfectly safe operation.

**Comment by jyotisachdeva57** [comment]
> Why do you say this is more type safe? `getOrElse` is a perfectly safe operation.

@dwijnand 
getOrElse can mess with the type as when the value is not found the default value could be of any type.

```
scala> val value= Some(1).getOrElse("not found")
val value: Any = 1

scala> val value= Some(1).fold("not found")(identity)
                                            ^
       error: type mismatch;
        found   : Int
        required: String

```
fold will ensure that the default value is of the same type.

**Comment by dwijnand** [comment]
I see what you mean.  Yeah, that's type inference along with type widening, sometimes you want one behaviour sometimes you want the other.

But fold doesn't, exactly, "ensure that the default value is of the same type", it's that the fallback value determines the result type (and the type has no type relationship with Option's element type), as a counter-example:

```scala
scala> Some(1).fold("not found": Any)(identity)
val res9: Any = 1
```

And, just to round off, here's `getOrElse`'s type widening coming in handy:

```scala
scala> val xs = Some(IndexedSeq(1, 2))
val xs: Some[IndexedSeq[Int]] = Some(Vector(1, 2))

scala> val ys = Option.empty[IndexedSeq[Int]]
val ys: Option[IndexedSeq[Int]] = None

scala> xs.getOrElse(Nil)
val res5: Seq[Int] = Vector(1, 2)

scala> ys.getOrElse(Nil)
val res6: Seq[Int] = List()
```

compared to fold's strict type inference:

```scala
scala> xs.fold(Nil)(identity)
                    ^
       error: type mismatch;
        found   : scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type (with underlying type scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type)
        required: IndexedSeq[Int] => scala.collection.immutable.Nil.type

scala> ys.fold(Nil)(identity)
                    ^
       error: type mismatch;
        found   : scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type (with underlying type scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type)
        required: IndexedSeq[Int] => scala.collection.immutable.Nil.type
```

Personally I like to use `fold` in place of pattern matching (sometimes, not all the time).  But I don't feel that `getOrElse` is "unsafe" because of its widening capabilities, so I don't think we should move away from using it.

**Comment by jyotisachdeva57** [comment]
> I see what you mean. Yeah, that's type inference along with type widening, sometimes you want one behaviour sometimes you want the other.
> 
> But fold doesn't, exactly, "ensure that the default value is of the same type", it's that the fallback value determines the result type (and the type has no type relationship with Option's element type), as a counter-example:
> 
> ```scala
> scala> Some(1).fold("not found": Any)(identity)
> val res9: Any = 1
> ```
> 
> And, just to round off, here's `getOrElse`'s type widening coming in handy:
> 
> ```scala
> scala> val xs = Some(IndexedSeq(1, 2))
> val xs: Some[IndexedSeq[Int]] = Some(Vector(1, 2))
> 
> scala> val ys = Option.empty[IndexedSeq[Int]]
> val ys: Option[IndexedSeq[Int]] = None
> 
> scala> xs.getOrElse(Nil)
> val res5: Seq[Int] = Vector(1, 2)
> 
> scala> ys.getOrElse(Nil)
> val res6: Seq[Int] = List()
> ```
> 
> compared to fold's strict type inference:
> 
> ```scala
> scala> xs.fold(Nil)(identity)
>                     ^
>        error: type mismatch;
>         found   : scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type (with underlying type scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type)
>         required: IndexedSeq[Int] => scala.collection.immutable.Nil.type
> 
> scala> ys.fold(Nil)(identity)
>                     ^
>        error: type mismatch;
>         found   : scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type (with underlying type scala.collection.immutable.Nil.type => scala.collection.immutable.Nil.type)
>         required: IndexedSeq[Int] => scala.collection.immutable.Nil.type
> ```
> 
> Personally I like to use `fold` in place of pattern matching (sometimes, not all the time). But I don't feel that `getOrElse` is "unsafe" because of its widening capabilities, so I don't think we should move away from using it.

@dwijnand 
Thanks for the explanation. That is behavior dependent.

**Comment by dwijnand** [comment]
No problem.

**Pull request closed without merging**
