### PR TITLE
Fixes SI-6285 - ParIterableLike no longer says sequential foreach.

### PR DESCRIPTION
**Pull request by jsuereth**
Review by @alex22, @phaller or anyone into documentation + collections.

### CODE REVIEW

**Comment by phaller** [comment]
LGTM

**Comment by paulp** [comment]
It would be just wonderful if the pull request testing jobs would stop and declare victory before they start trying and failing to do this kind of thing:

```
sbt.libs:
      [get] Getting: http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/interface/0.12.0/jars/interface.jar
      [get] To: /localhome/jenkins/b/workspace/pr-scala-testsuite-linux-opt/build/sbt-interface/0.12.0/lib/interface.jar
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 503 for URL: http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/interface/0.12.0/jars/interface.jar
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 503 for URL: http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/interface/0.12.0/jars/interface.jar
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 503 for URL: http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/interface/0.12.0/jars/interface.jar
      [get] Can't get http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/interface/0.12.0/jars/interface.jar to /localhome/jenkins/b/workspace/pr-scala-testsuite-linux-opt/build/sbt-interface/0.12.0/lib/interface.jar

BUILD FAILED
/localhome/jenkins/b/workspace/pr-scala-testsuite-linux-opt/build.xml:2775: The following error occurred while executing this line:
/localhome/jenkins/b/workspace/pr-scala-testsuite-linux-opt/build.xml:2089: Can't get http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/interface/0.12.0/jars/interface.jar to /localhome/jenkins/b/workspace/pr-scala-testsuite-linux-opt/build/sbt-interface/0.12.0/lib/interface.jar
```

**Comment by jsuereth** [comment]
Having it download every time is bad.  However, we can't let 2.10.x break with SBT interface without _knowing_ and take appropriate actions to fix.   EVERYONE uses that SBT lib now, zinc/maven/sbt etc.   It's too critical not to test, and this is, once again, Artifactory breaking.

**Comment by paulp** [comment]
@jsuereth It's wonderful to test the sbt interface on every test run.  It's not so wonderful to test artifactory.

**Pull request merged**
