### PR TITLE
bug#10747 Improve thread safety of Enumeration

### PR DESCRIPTION
**Pull request by NthPortal**
Use the double-check idiom for Enumeration.values.

Synchronize Val's constructor, to prevent duplicate IDs.

Fixes 1, 2, and 3.ii in scala/bug#10747

### CODE REVIEW

**Comment by NthPortal** [comment]
I think this is binary compatible, because it only changes private things, but if not, I can change the target to 2.13.x

**Comment by som-snytt** [comment]
This appears to fix something, but without a test it's difficult to specify. For example, vmap is used when iterating over a ValueSet. It's not obvious that is safe.

This doesn't obviously break anything.

It's not obvious that it's not preferable to cut our losses and just document that `object X extends Enumeration` is the only use case. Init of X is in static init. This class has consumed excess brain and time share over the years.

Edit: i.e., this addresses the race on vset as described. It's not obvious that the use case should be supported in the waning years of Scala 2.

**Comment by som-snytt** [comment]
Here is a simple test that throws trying to calculate `values.size` (iterating over ValueSet), prints 66, or hangs. Add a 6 to get the number of the beast! Maybe this fix suffices, or maybe someone will link here from the future ticket.

```
package battling

class X extends Enumeration(0) {
  def init(base: Int, prefix: String): Unit = {
    for (i <- 0 to 32) Value(base + i, prefix + i)
  }
}

class Test {
  import concurrent._, ExecutionContext.Implicits._
  import java.util.concurrent.CountDownLatch

  // competing creation of values
  def run(): Unit = {
    val start = new CountDownLatch(1)
    val done  = new CountDownLatch(2)
    val xs = new X
    val f1 = Future {
      start.await()
      xs.init(100, "f1")
      done.countDown()
    }
    val f2 = Future {
      start.await()
      xs.init(200, "f2")
      done.countDown()
    }
    start.countDown()
    done.await()
    println(xs.values.size)
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    new Test().run()
  }
}
```

The stack trace was:
```
java.util.NoSuchElementException: key not found: 218
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
	at scala.Enumeration.apply(Enumeration.scala:137)
	at scala.Enumeration$ValueSet.$anonfun$iterator$1(Enumeration.scala:282)
	at scala.Enumeration$ValueSet.$anonfun$iterator$1$adapted(Enumeration.scala:282)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:457)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.size(TraversableOnce.scala:107)
	at scala.collection.TraversableOnce.size$(TraversableOnce.scala:105)
	at scala.collection.AbstractTraversable.size(Traversable.scala:104)
	at battling.Test.run(battling.scala:32)
	at battling.Test$.main(battling.scala:38)
	at battling.Test.main(battling.scala)

```

**Comment by NthPortal** [comment]
> For example, vmap is used when iterating over a ValueSet. It's not obvious that is safe.

`ValueSet` is backed by an `immutable.BitSet`, so I think once it's constructed, it should be safe. And `vmap` is only modified (I think) inside of the `synchronized` block, so it cannot be modified during the construction of the `ValueSet`

**Comment by NthPortal** [comment]
@som-snytt I'll have a look at turning that into a test of some sort - thanks!

**Comment by som-snytt** [comment]
It's hard to force a race condition, of course.

`vmap` is used by `Enum.apply`, so just `X.ValueSet.empty.iterator` uses `vmap`. I don't there are any guarantees there. 

I would LGTM this change to avoid the simple use case of weird construction on one thread with another thread calling `values`. There is an issue about recursive construction that results in null references -- IIRC due to default values. I also see that `nameOf` is synchronized, but without pulling on that thread (so to speak), probably a separate lock is worth it.

**Comment by NthPortal** [comment]
@som-snytt I'm inclined to agree with you that this is plugging a pinhole while the dam itself is broken; at the same time, I don't think it hurts, and once its written, might as well merge it? idk

**Comment by NthPortal** [comment]
I've changed my mind - I agree with Som

**Comment by som-snytt** [comment]
@SethTisue the release notes could add, "Enumeration still not thread-safe!" Maybe lead with that, or lede.

**Pull request closed without merging**
