### PR TITLE
Abstract parent `copy` does not suspend case `copy`

### LINKED ISSUE #12623: case class synthetic method generation when abstract method declaration is present
## Reproduction steps

Scala version: 2.13.8

```scala
trait MapI[C] {
  def i: Int
  def s: String
  def copy(i: Int = this.i, s: String = this.s): C
  def mapI(i: Int): C = copy(i)
}

case class C(i: Int, s: String) extends MapI[C]
```

## Problem

The compiler reports "class C needs to be abstract. Missing implementation for: def copy(i: Int, s: String): C inherited from trait MapI".

## Expectation

I'd appreciate the compiler not stopping synthetic method generation if an abstract method declaration is present. This way one would not need to implement `mapI` in every `case class`. I also checked Scala 3.1.2 which works fine.

## See also

https://contributors.scala-lang.org/t/continue-with-case-class-synthetic-method-generation-when-abstract-method-declaration-is-present/5826

### PR DESCRIPTION
**Pull request by som-snytt**
A case class may inherit an abstract `copy` method, which it will implement as usual.

Fixes scala/bug#12623

### CODE REVIEW

**Comment by SethTisue** [comment]
As 2.13.9 may be imminent, let's hold this one for 2.13.10.

**Review by lrytz — APPROVED** [review]
Thank you!

**Comment by SethTisue** [comment]
@som-snytt can you take a stab at writing a user-facing PR description? since we're release-noting this

alternately, you could argue that it isn't actually release-note-worthy :-)

**Comment by som-snytt** [comment]
I'd rather not argue, but what's wrong with "Let's see."

**Pull request merged**
