### PR TITLE
Don't lift try blocks into separate methods in boolean expressions

### PR DESCRIPTION
**Pull request by lrytz**
Boolean not/and/or are compiled to conditional jumps, so a `try-catch`
expression in argument position can be emitted directly, there is no
need to it into a synthetic method.

In general, `try-catch` expressions in argument position are emitted
in separate methods because the JVM clears the call stack when entering
a handler. This would discard stack values that are still used, e.g.,
the receiver of an invocation.

Fixes scala/bug#11127.

This PR is very similar to https://github.com/scala/scala/pull/1892.

### CODE REVIEW

**Comment by retronym** [comment]
I was wondering if we had the same problem for `synchronized`, but we don't seem to:

```
$ scalac-ref 2.13.x -Xprint:uncurry  <(echo 'class c { def b = true; def t3 = synchronized { try b catch { case _: ClassCastException => b }}}')
[[syntax trees at end of                   uncurry]] // 63
package <empty> {
  class c extends Object {
    def <init>(): c = {
      c.super.<init>();
      ()
    };
    def b(): Boolean = true;
    <synchronized> def t3(): Boolean = try {
      c.this.b()
    } catch {
      case (_: ClassCastException) => c.this.b()
    }
  }
}
```

I'm guessing we desugar that method call to the synchronized flag before we hit the `transformArgs` transform.

**Comment by retronym** [comment]
We could also special case calls to static methods:

```
$ scalac-pr 7132 -Xprint:uncurry  <(echo 'class c { def b = true; def t3 = java.util.Collections.singletonList(try b catch { case _: ClassCastException => b })}')
[[syntax trees at end of                   uncurry]] // 63
package <empty> {
  class c extends Object {
    def <init>(): c = {
      c.super.<init>();
      ()
    };
    def b(): Boolean = true;
    def t3(): java.util.List[Boolean] = java.util.Collections.singletonList[Boolean]({
      def liftedTree1(): Boolean = try {
        c.this.b()
      } catch {
        case (_: ClassCastException) => c.this.b()
      };
      liftedTree1()
    })
  }
}
```

We'd want to test this with a varargs static method, because that ends up with another method call.

```
$ scalac-pr 7132 -Xprint:uncurry  <(echo 'class c { def b = true; def t3 = java.util.Arrays.asList(try b catch { case _: ClassCastException => b })}')
[[syntax trees at end of                   uncurry]] // 63
package <empty> {
  class c extends Object {
    def <init>(): c = {
      c.super.<init>();
      ()
    };
    def b(): Boolean = true;
    def t3(): java.util.List[Boolean] = java.util.Arrays.asList[Boolean](scala.runtime.ScalaRunTime.toObjectArray(Array[Boolean]{{
      def liftedTree1(): Boolean = try {
        c.this.b()
      } catch {
        case (_: ClassCastException) => c.this.b()
      };
      liftedTree1()
    }}))
  }
}
```

**Review by retronym — APPROVED** [review]
Feel free to book the progress and improve static method handling in a followup PR or ticket.

**Comment by lrytz** [comment]
Thanks!

**Comment by som-snytt** [comment]
I just wanted to say I like how you all work together.

**Pull request merged**
