### PR TITLE
Add Java 1.6. and 1.8 java.lang.Math methods into scala.math.package (scala/bug#9813)

### PR DESCRIPTION
**Pull request by janekdb**
The same as #5382 but targeting 2.13.x branch.

### CODE REVIEW

**Comment by lrytz** [comment]
this got out of sync, needs a rebase.. thanks!

**Comment by janekdb** [comment]
@lrytz - rebased.

**Review by lrytz — APPROVED** [review]
Thank you!

**Comment by SethTisue** [comment]
thanks Janek for your patience on this

**Pull request merged**
