### PR TITLE
unset inappropriate execute bits

### PR DESCRIPTION
**Pull request by SethTisue**
I imagine these date back to old Subversion days and are probably the
result of inadvertent commits from Windows users with bad vcs client
configs.

having the bit set isn't really harmful most of the time,
but it's just not right, and it makes the files stand out in directory
listings for no reason

incidentally, here's an easy way to get a list of the remaining files with the bit:

```
find . -type f -perm +0100
```

### CODE REVIEW

**Comment by som-snytt** [comment]
It's not right! It's not just! What's the emoji for power fist? :fist: 

Actually, github autocompleted `power...` which raises the bar on @retronym for completion.

Though I can't distinguish that from the letter e: https://en.wikipedia.org/wiki/American_manual_alphabet#/media/File:E@InForward.jpg

Glad I'm not the bit-fiddling guy.

https://github.com/scala/scala/commit/76e35fa14104cc517f7ef7697507015bee7e0a89

Gee, sometimes I wish the commit had either a review or at least a comment.

I was kind of curious whether it's possible to see, based on @SethTisue 's comment, who works on Windoze, just from the github UI. Even SVN is a distant memory now.

**Comment by SethTisue** [comment]
ha. @lrytz, do you remember anything about 76e35fa14104cc517f7ef7697507015bee7e0a89?

**Comment by lrytz** [comment]
dug out some old email

the original commit was https://github.com/scala/scala/commit/0c97d8c73fdf4e1dd33ee98ea2e14bc51388bb5f

all i can see form the mails is that it broke some tests when running the test suite on windows. since the author didn't fix it in 3 weeks, we reverted to get a green build.

**Comment by SethTisue** [comment]
OK, let's hold off on merging until I can get set up to run the tests on Windows, then.

**Comment by SethTisue** [comment]
I'm able to run tests on Windows now (by ssh'ing to a Cygwin prompt on jenkins-worker-windows-publish), but I see a number of them are failing on 2.11.x, even without merging this PR. So I'm going to go ahead and merge it. I'll deal with any Windows-specific failures later, all at once.

**Pull request merged**
