### PR TITLE
Partial redesign of incremental compiler invalidation.

### PR DESCRIPTION
**Pull request by odersky**
We now do the right thing when packages are either newly created or deleted. Previously there was a problem when a new package was created inside a system package (and, unfortunately, root is a system package). That's fixed now. We also approximate more tightly now when packages are newly created (ie. the newly created symbol gets rescanned, instead of its owner). 

Review by @harrah, @pvlugter, @adriaanm

### CODE REVIEW

**Comment by odersky** [comment]
I added another commit which is logically separate.

**Comment by adriaanm** [comment]
ok, started another build: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-testsuite-linux-opt/192/
(the bot doesn't yet discover that pull requests have been updated)

**Comment by adriaanm** [comment]
build's ok

**Comment by pvlugter** [comment]
I tried this most recent version on some simple tests and most seem to work fine and invalidate correctly.

The canonical path matching fixes a problem I saw with yesterday's version (#640) where absolute paths were needed.

One thing that doesn't work for me is adding a new top-level package. Simple test that fails for me:

B0.scala:

``` scala
package b
object B { val x = 3 }
```

A1.java:

``` java
package a;
public class A { public static final int x = 3; }
```

B1.scala:

``` scala
package b
object B { val x = a.A.x }
```

Test:

``` bash
# clean up first
rm -f A.java B.scala
rm -rf target && mkdir target
fsc -shutdown

# B that doesn't depend on A
cp B0.scala B.scala

# compile B
fsc -classpath target -Yinvalidate target -d target B.scala

# B depends on A, new top-level package a
cp A1.java A.java
cp B1.scala B.scala

# compile A
javac -d target A.java

# recompile B
rm -f target/b/B*.class
fsc -classpath target -Yinvalidate target -d target B.scala
```

**Comment by odersky** [comment]
On Wed, May 30, 2012 at 7:11 AM, Peter Vlugter <
reply@reply.github.com

> wrote:
> 
> I tried this most recent version on some simple tests and most seem to
> work fine and invalidate correctly.
> 
> The canonical path matching fixes a problem I saw with yesterday's version
> (#640) where absolute paths were needed.
> 
> One thing that doesn't work for me is adding a new top-level package.
> Simple test that fails for me:
> 
> B0.scala:
> 
> ``` scala
> package b
> object B { val x = 3 }
> ```
> 
> A1.java:
> 
> ``` java
> package a;
> public class A { public static final int x = 3; }
> ```
> 
> B1.scala:
> 
> ``` scala
> package b
> object B { val x = a.A.x }
> ```
> 
> Test:
> 
> ``` bash
> # clean up first
> rm -f A.java B.scala
> rm -rf target && mkdir target
> fsc -shutdown
> 
> # B that doesn't depend on A
> cp B0.scala B.scala
> 
> # compile B
> fsc -classpath target -Yinvalidate target -d target B.scala
> 
> # B depends on A, new top-level package a
> cp A1.java A.java
> cp B1.scala B.scala
> 
> # compile A
> javac -d target A.java
> 
> # recompile B
> rm -f target/b/B*.class
> fsc -classpath target -Yinvalidate target -d target B.scala
> ```

Thanks for testing. I'll take a look. - Martin

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/scala/scala/pull/641#issuecomment-6002366

## 

Martin Odersky
Prof., EPFL http://www.epfl.ch and Chairman, Typesafehttp://www.typesafe.com
PSED, 1015 Lausanne, Switzerland
Tel. EPFL: +41 21 693 6863
Tel. Typesafe: +41 21 691 4967

**Pull request closed without merging**
