### PR TITLE
Proper constraints on CC types in collections

### PR DESCRIPTION
**Pull request by szeiger**
I started this in the hope of eventually fixing https://github.com/scala/bug/issues/11188 but after 2 days I'm giving up. This part here appears to be useful enough on its own. The type constraints are better than before and we don't need `AnyConstr` anymore.

I ran into several problems trying to take this further:
- Due to Views we can't have nice constraints such as `CC[X] <: Seq[X]` in `SeqOps`. The worst case is `MapOps` which requires `CC` to be not just `MapView` but even a tupled anonymous type function on `View`.
- There's a compiler bug that creates bad forwarders. I ran into it when trying to enforce constraints to `SortedMap` instead of only `Map` in `SortedMapOps`.
- What we really need for https://github.com/scala/bug/issues/11188 is a constraint `C <: CC[A]` (and similar ones for other kinds of `CC`) but this is not possible because of variance. We need `CC[+_]` for `+A` but `CC[_]` for `A`. This becomes a problem when we get to mutable (and therefore invariant) collection types that extend generic (covariant) collection types. We can't tie the knot anymore because the variance changes.
- `MapOps` uses a `CC` type constraint to coax the compiler into producing methods with return types that don't clash after erasure with inherited methods from `IterableOps` and `SeqOps`. Adding the "correct" constraints break this.
- I also tried to add proper self type constraints in the hope of getting rid of `coll` and some casts but it quickly gets very verbose because the compiler requires some excessive repetition of self types (in some cases but not others; this might be a bug) even when extending this type directly (so it should automatically be part of the self type).

### CODE REVIEW

**Comment by smarter** [comment]
I attempted something a bit like this for Sets in https://github.com/scala/scala/pull/6728/commits/2623ca84549a511aa72f2fecc25f13353c454c8a

> We can't tie the knot anymore because the variance changes.

I forgot the details but I don't recall having this problem in my PR, I did however introduce an InvariantSetOps for some operations: https://github.com/scala/scala/pull/6728/commits/b98ddb91effb9f0bd0a977d595e714adb74d2a24

**Comment by smarter** [comment]
(The context for these commits is https://github.com/scala/scala/pull/6728)

**Comment by julienrf** [comment]
> This part here appears to be useful enough on its own.

It’s not clear to me what the benefits of this PR are, given that it doesn’t fix scala/bug#11188. Can you also summarize them? It seems to me that it essentially adds narrower bounds on type parameters, which I think adds more constraints to the use site.

**Comment by julienrf** [comment]
I think it should be possible to get rid of some `.coll` calls or `.toIterable` calls maybe?

**Comment by szeiger** [comment]
The new constraints have no effect on users. For example, `IterableOps` was always intended to be an implementation trait for `Iterable` and is not used in any other context. Adding the proper constraints should avoid unnecessary casts but with the limited changes I was able to make I didn't come across any such case. There could be some in user code. The only direct benefit here is getting rid of `AnyConstr`.

**Comment by julienrf** [comment]
> The new constraints have no effect on users.

It might make it harder to abstract over `IterableOps`. For instance, the upper bound constraint is now propagated to the `Iterable.WithFilter` class definition. I think similar use cases may happen in user code bases. We can see another example in the `files/run/partialfun.scala` test.

That being said, we could argue that `IsIterable` is the recommended way to abstract over `IterableOps` (this is more true with `IsSeq`, for `SeqOps`), which are unaffected by this PR. So, there is still a way to write generic code without being bothered by bound constraints.

**Comment by SethTisue** [comment]
@szeiger needs rebase

after rebase, should we run the 2.13 community build on this before merging?

**Comment by Ichoran** [comment]
@SethTisue @julienrf - I'm leaving this one to you guys (and @szeiger of course) to get over the finish line.

**Comment by julienrf** [comment]
If the PR allows us to remove unnecessary calls to `.coll` or `.toIterable` then I see the value. But in its current state I don’t think it is worth it because it just makes things more constrained with the only value being that there is no need for `AnyConstr` (which is needed only for Dotty compatibility, btw).

**Comment by szeiger** [comment]
More constrained = more correct. But it's getting too late for such a big change and we still can't get the constraints exactly right so there's not a huge benefit.

**Pull request closed without merging**
