### PR TITLE
Rework method & val sig inference from overridden member.

### PR DESCRIPTION
**Pull request by adriaanm**
Keeping the last commit in a separate PR since this is a bit more controversial.

### CODE REVIEW

**Comment by adriaanm** [comment]
See #4842 for all but the last commit, which grew quite a bit since @retronym last looked at it.

**Comment by adriaanm** [comment]
@SethTisue, could you launch a community build on this PR, please?

**Comment by SethTisue** [comment]
[queued](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/218/console)  (EDIT: whoops, 216 was bad, 218 is the one)

**Comment by adriaanm** [comment]
thanks!

**Comment by adriaanm** [comment]
TODO items from @retronym's review:
- [x] Needs a test along the lines of:

```
scala> implicit def s2i(s: String): Int = s.length; trait Base { def foo: Int }; trait Sub extends Base { def foo = "" }
warning: there was one feature warning; re-run with -feature for details
s2i: (s: String)Int
defined trait Base
defined trait Sub

scala> implicit def s2i(s: String): Int = s.length; trait Base { def foo: Int }; trait Sub extends Base { val foo = "" }
<console>:9: error: overriding method foo in trait Base of type => Int;
 value foo has incompatible type
       implicit def s2i(s: String): Int = s.length; trait Base { def foo: Int }; trait Sub extends Base { val foo = "" }
```

I take it the second example will work after this change.
- [x] It might be worth spelling out in more detail that we're using the result type of the overrriden member as the expected type for the RHS of the val. We then use the type of the RHS (which may be more specific) as the result type of the overriding member.
- [x] This seems clever, but is different from the approach used when finding the overriden symbol of a DefDef. I'd like to unify the approach.

```
def overriddenSymbol(resTp: Type) = {
        lazy val schema: Type = methodTypeSchema(resTp) // OPT create once. Must be lazy to avoid cycles in neg/t5093.scala
        intersectionType(methOwner.info.parents).nonPrivateMember(meth.name).filter { sym =>
          sym != NoSymbol && (site.memberType(sym) matches schema)
        }
      }
```

**Comment by adriaanm** [comment]
The part that infers val return types broke shapeless. I can dial back its impact by only inferring result types for implicit vals, as this is most likely a strict improvement in those cases.

**Comment by milessabin** [comment]
What sort of breakage?

**Comment by adriaanm** [comment]
I haven't investigated yet, but here's the full error message:

```
[shapeless] Testing: core
[shapeless] [info] Compiling 1 Scala source to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/target/scala-2.12.0-dbuildx31508209527120dabcda5751a9df01c75462d090/classes...
[shapeless] [info] Compiling 35 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/target/scala-2.12.0-dbuildx31508209527120dabcda5751a9df01c75462d090/test-classes...
[shapeless] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/src/test/scala/shapeless/lenses.scala:304: polymorphic expression cannot be instantiated to expected type;
[shapeless] [error]  found   : [B]mkLens.Out
[shapeless] [error]  required: shapeless.Lens[shapeless.lensTestDataTypes.Person,String]
[shapeless] [error]   val nameLens     = lens[Person].name
[shapeless] [error]                          ^
[shapeless] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/src/test/scala/shapeless/lenses.scala:305: polymorphic expression cannot be instantiated to expected type;
[shapeless] [error]  found   : [B]mkLens.Out
[shapeless] [error]  required: shapeless.Lens[shapeless.lensTestDataTypes.Person,Int]
[shapeless] [error]   val ageLens      = lens[Person].age
[shapeless] [error]                          ^
[shapeless] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/src/test/scala/shapeless/lenses.scala:306: polymorphic expression cannot be instantiated to expected type;
[shapeless] [error]  found   : [B]mkLens.Out
[shapeless] [error]  required: shapeless.Lens[shapeless.lensTestDataTypes.Person,shapeless.lensTestDataTypes.Address]
[shapeless] [error]   val addressLens  = lens[Person].address
[shapeless] [error]                          ^
[shapeless] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/src/test/scala/shapeless/lenses.scala:307: polymorphic expression cannot be instantiated to expected type;
[shapeless] [error]  found   : [B]mkLens.Out
[shapeless] [error]  required: shapeless.Lens[shapeless.lensTestDataTypes.Person,String]
[shapeless] [error]   val streetLens   = lens[Person].address.street
[shapeless] [error]                          ^
[shapeless] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/src/test/scala/shapeless/lenses.scala:308: polymorphic expression cannot be instantiated to expected type;
[shapeless] [error]  found   : [B]mkLens.Out
[shapeless] [error]  required: shapeless.Lens[shapeless.lensTestDataTypes.Person,String]
[shapeless] [error]   val cityLens     = lens[Person].address.city
[shapeless] [error]                          ^
[shapeless] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/shapeless-4f9103112dd1708e765f9f40ece320a2944a92d8/core/src/test/scala/shapeless/lenses.scala:309: polymorphic expression cannot be instantiated to expected type;
[shapeless] [error]  found   : [B]mkLens.Out
[shapeless] [error]  required: shapeless.Lens[shapeless.lensTestDataTypes.Person,String]
[shapeless] [error]   val postcodeLens = lens[Person].address.postcode
[shapeless] [error]                          ^
[shapeless] [error] 6 errors found
```

**Comment by adriaanm** [comment]
I'd be grateful for any insights -- you can try out this build as follows:

```
resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
scalaVersion := "2.12.0-d2b219e-SNAPSHOT"
```

**Comment by milessabin** [comment]
A first, very superficial, observation is that this appears to be related to the use of `selectDynamic` in the cases which don't compile. There are exactly equivalent cases which don't use `selectDynamic` which are just fine with that compiler build.

**Comment by milessabin** [comment]
Also, the code which fails during a test compile is just fine on the REPL.

**Comment by milessabin** [comment]
OK, I have a hunch what might be going on here. In the expression,

``` scala
val nameLens = lens[Person].name
```

The `name` selection is matched by the following `selectDynamic`,

``` scala
def selectDynamic[B](k: String)
  (implicit mkLens: MkSelectDynamicOptic[Lens[S, A], A, Symbol @@ k.type, B]): mkLens.Out =
    mkLens(this)
```

Note that at this call site there isn't an explicit type parameter list, and I'm expecting `B` to be inferred as `Nothing`. By the looks of it, in the current compiler build this is leading to the result being inferred as a polytype (`[B]mkLens.Out`) rather than as the expected `mkLens.Out` (which should expand to `Lens[Person, String]`).

("inferred as a polytype" isn't right, is it? It's just that the compiler is refusing to instantiate the polytype at `Nothing`?).

**Comment by milessabin** [comment]
In support of that, if I change the call site to,

``` scala
val nameLens = lens[Person].name[Nothing]
```

Compilation succeeds.

**Comment by milessabin** [comment]
Please let me know if there's anything more I can do to help.

**Comment by adriaanm** [comment]
Thanks, @milessabin! That narrows it down nicely -- didn't think to test `selectDynamic`. I'll dig in this morning and let you know what I find.

**Comment by adriaanm** [comment]
> ("inferred as a polytype" isn't right, is it? It's just that the compiler is refusing to instantiate the polytype at Nothing?).

it sounds like we're typechecking the val's RHS in the wrong mode (it should be EXPRmode, so that it tries to infer a type of kind *, instead of POLYmode, which admits types of any kind)

**Comment by adriaanm** [comment]
Interestingly, this fails in M3 with the same error -- note the expected type:

```
package shapeless

import lens._, syntax.singleton._, tag.@@, test._

case class Person(name : String)

trait LensTests {
  val nameLens: Lens[Person, String]
}

class OpticTestsDynamic extends LensTests {
  val nameLens: Lens[Person, String] = lens[Person].name
}

```

**Comment by adriaanm** [comment]
After poking around some more, I conclude that this sensitivity to the expected typing being supplied (or inferred, after this PR is merged) is the true bug. When no type is supplied, the code below is generated (note that it computes the same type for the `val`).

@milessabin, does this ring a bell? Any thoughts on how to resolve this? Given the identical error in the presence of an explicit type ascription, I don't feel this issue should block this PR, which provides the same type through inference.

``` scala
private[this] val nameLens: shapeless.Lens[shapeless.examples.LenseExamples.Person,String] 
= shapeless.`package`.lens.apply[shapeless.examples.LenseExamples.Person].selectDynamic[Nothing]("name")(
  shapeless.this.MkSelectDynamicOptic.mkSelField[shapeless.Lens[shapeless.examples.LenseExamples.Person,shapeless.examples.LenseExamples.Person], shapeless.examples.LenseExamples.Person, shapeless.tag.@@[Symbol,String("name")], this.Elem](
    shapeless.this.MkFieldLens.mkFieldLens[shapeless.examples.LenseExamples.Person, shapeless.tag.@@[Symbol,String("name")], this.Repr, Nothing](
      shapeless.this.MkLabelledGenericLens.mkLabelledGenericLens[shapeless.examples.LenseExamples.Person](
        shapeless.this.LabelledGeneric.materializeProduct[shapeless.examples.LenseExamples.Person, shapeless.::[shapeless.tag.@@[Symbol,String("name")],shapeless.::[shapeless.tag.@@[Symbol,String("age")],shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil]]], shapeless.::[String,shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]]], this.Out](
          ({
      final class $anon extends AnyRef with shapeless.DefaultSymbolicLabelling[shapeless.examples.LenseExamples.Person] {
        def <init>(): <$anon: shapeless.DefaultSymbolicLabelling[shapeless.examples.LenseExamples.Person]> = {
          $anon.super.<init>();
          ()
        };
        type Out = shapeless.::[shapeless.tag.@@[Symbol,String("name")],shapeless.::[shapeless.tag.@@[Symbol,String("age")],shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil]]];
        def apply(): shapeless.::[shapeless.tag.@@[Symbol,String("name")],shapeless.::[shapeless.tag.@@[Symbol,String("age")],shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil]]] = shapeless.::.apply[shapeless.tag.@@[Symbol,String("name")], shapeless.::[shapeless.tag.@@[Symbol,String("age")],shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil.type]]](scala.Symbol.apply("name").asInstanceOf[shapeless.tag.@@[Symbol,String("name")]], shapeless.::.apply[shapeless.tag.@@[Symbol,String("age")], shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil.type]](scala.Symbol.apply("age").asInstanceOf[shapeless.tag.@@[Symbol,String("age")]], shapeless.::.apply[shapeless.tag.@@[Symbol,String("address")], shapeless.HNil.type](scala.Symbol.apply("address").asInstanceOf[shapeless.tag.@@[Symbol,String("address")]], shapeless.HNil)))
      };
      new $anon()
    }: shapeless.DefaultSymbolicLabelling.Aux[shapeless.examples.LenseExamples.Person,shapeless.::[shapeless.tag.@@[Symbol,String("name")],shapeless.::[shapeless.tag.@@[Symbol,String("age")],shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil]]]]), {
      final class anon$macro$1577 extends AnyRef with shapeless.Generic[shapeless.examples.LenseExamples.Person] {
        def <init>(): anon$macro$1577 = {
          anon$macro$1577.super.<init>();
          ()
        };
        type Repr = shapeless.::[String,shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]]];
        def to(p: shapeless.examples.LenseExamples.Person): anon$macro$1577.this.Repr = p match {
  case (name: String, age: Int, address: shapeless.examples.LenseExamples.Address)shapeless.examples.LenseExamples.Person((pat$macro$1574 @ _), (pat$macro$1575 @ _), (pat$macro$1576 @ _)) => shapeless.::.apply[String, shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil.type]]](pat$macro$1574, shapeless.::.apply[Int, shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil.type]](pat$macro$1575, shapeless.::.apply[shapeless.examples.LenseExamples.Address, shapeless.HNil.type](pat$macro$1576, shapeless.HNil)))
}.asInstanceOf[anon$macro$1577.this.Repr];
        def from(p: anon$macro$1577.this.Repr): shapeless.examples.LenseExamples.Person = p match {
          case (head: String, tail: shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]])shapeless.::[String,shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]]]((pat$macro$1574 @ _), (head: Int, tail: shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil])shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]]((pat$macro$1575 @ _), (head: shapeless.examples.LenseExamples.Address, tail: shapeless.HNil)shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]((pat$macro$1576 @ _), shapeless.HNil))) => LenseExamples.this.Person.apply(pat$macro$1574, pat$macro$1575, pat$macro$1576)
        }
      };
      (new anon$macro$1577(): shapeless.Generic.Aux[shapeless.examples.LenseExamples.Person,shapeless.::[String,shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]]]])
    }, 
    hlist.this.ZipWithKeys.hconsZipWithKeys[shapeless.tag.@@[Symbol,String("name")], String, shapeless.::[shapeless.tag.@@[Symbol,String("age")],shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil]], shapeless.::[Int,shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]]](
      hlist.this.ZipWithKeys.hconsZipWithKeys[shapeless.tag.@@[Symbol,String("age")], Int, shapeless.::[shapeless.tag.@@[Symbol,String("address")],shapeless.HNil], shapeless.::[shapeless.examples.LenseExamples.Address,shapeless.HNil]](hlist.this.ZipWithKeys.hconsZipWithKeys[shapeless.tag.@@[Symbol,String("address")], shapeless.examples.LenseExamples.Address, shapeless.HNil, shapeless.HNil](hlist.this.ZipWithKeys.hnilZipWithKeys, shapeless.Witness.mkWitness[Symbol with shapeless.tag.Tagged[String("address")]](scala.Symbol.apply("address").asInstanceOf[shapeless.tag.@@[Symbol,String("address")]].asInstanceOf[Symbol with shapeless.tag.Tagged[String("address")]])), shapeless.Witness.mkWitness[Symbol with shapeless.tag.Tagged[String("age")]](scala.Symbol.apply("age").asInstanceOf[shapeless.tag.@@[Symbol,String("age")]].asInstanceOf[Symbol with shapeless.tag.Tagged[String("age")]])), shapeless.Witness.mkWitness[Symbol with shapeless.tag.Tagged[String("name")]](scala.Symbol.apply("name").asInstanceOf[shapeless.tag.@@[Symbol,String("name")]].asInstanceOf[Symbol with shapeless.tag.Tagged[String("name")]])), scala.Predef.$conforms[this.Out])), 
      shapeless.this.MkRecordSelectLens.mkRecordSelectLens[this.Repr, shapeless.tag.@@[Symbol,String("name")], String](
        new shapeless.ops.record.UnsafeSelector(0).asInstanceOf[shapeless.ops.record.Selector.Aux[shapeless.::[String with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("name")],String],shapeless.::[Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("age")],Int],shapeless.::[shapeless.examples.LenseExamples.Address with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("address")],shapeless.examples.LenseExamples.Address],shapeless.HNil]]],Symbol with shapeless.tag.Tagged[String("name")],String]], new shapeless.ops.record.UnsafeUpdater(0).asInstanceOf[shapeless.ops.record.Updater.Aux[shapeless.::[String with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("name")],String],shapeless.::[Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("age")],Int],shapeless.::[shapeless.examples.LenseExamples.Address with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("address")],shapeless.examples.LenseExamples.Address],shapeless.HNil]]],String with shapeless.labelled.KeyTag[shapeless.tag.@@[Symbol,String("name")],String],shapeless.::[String with shapeless.labelled.KeyTag[shapeless.tag.@@[Symbol,String("name")],String],shapeless.::[Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("age")],Int],shapeless.::[shapeless.examples.LenseExamples.Address with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("address")],shapeless.examples.LenseExamples.Address],shapeless.HNil]]]]])), 
        shapeless.this.OpticComposer.composeLL[shapeless.examples.LenseExamples.Person, this.Elem, shapeless.examples.LenseExamples.Person]));
```

**Comment by adriaanm** [comment]
Miles, this may still be a scalac bug, though not with this PR. If you could narrow this down to a shapeless-less repro, happy to take a look (or could it be an issue with the materialization macro?)

I just filed a related issue that shows another problem with `selectDynamic`: https://issues.scala-lang.org/browse/SI-9558

**Comment by milessabin** [comment]
I'm fairly sure there are no macros directly involved in this. I'll see if I can come up with a zero dependency reproduction.

**Comment by milessabin** [comment]
Thanks for the M3 reproduction. Turns out that that also fails on 2.11.7, so this PR is definitely off the hook.

**Comment by milessabin** [comment]
FYI, I've just pushed [the following](https://github.com/milessabin/shapeless/commit/5ec8b6aeca63e4a0a8efc8135647c59c7513d120) to shapeless master which works around the problem for 2.10.x ... 2.12.0-d2b219e-SNAPSHOT.

**Comment by milessabin** [comment]
shapeless-free reproduction (from 2.11.x on ...),

``` scala
package repro

import scala.language.dynamics

object Foo extends Dynamic {
  def selectDynamic[T](s: String)(implicit bar: Bar[T]): bar.Out = bar.value
}

trait Bar[T] {
  type Out
  val value: Out
}

object Bar {
  type Aux[T, O] = Bar[T] { type Out = O }
  implicit def barNothing: Aux[Nothing, Int] = new Bar[Nothing] {
    type Out = Int
    val value = 23
  }
}

object Test {
  val f0 = Foo.name // OK
  val f1 = Foo.name[Nothing] // OK
  val f2: Int = Foo.name // error: polymorphic expression cannot be instantiated to expected type
}
```

**Comment by milessabin** [comment]
Hmm ... seems that `Dynamic` is a red-herring. The following is also a reproduction,

``` scala
package repro

object Foo {
  def foo[T](implicit bar: Bar[T]): bar.Out = bar.value
}

trait Bar[T] {
  type Out
  val value: Out
}

object Bar {
  type Aux[T, O] = Bar[T] { type Out = O }
  implicit def barNothing: Aux[Nothing, Int] = new Bar[Nothing] {
    type Out = Int
    val value = 23
  }
}

object Test {
  val f0 = Foo.foo // OK
  val f0a: Int = f0
  val f1 = Foo.foo[Nothing] // OK
  val f1a: Int = f1
  val f2: Int = Foo.foo // error: polymorphic expression cannot be instantiated to expected type
  val f3: Int = Foo.foo[Nothing] // OK
}
```

**Comment by adriaanm** [comment]
Thanks, @milessabin! I really appreciate the minimization. I'll see what we can do here as soon as I get my trait fields PR submitted (later this week).

**Comment by lrytz** [comment]
Here's a minimization of the scaladoc test; this code compiles before this change, but not after.

```
class C {
  def f: Object = this
}

class D extends C {
  override val f = new Object { def foo = 1 }
  def bar = f.foo
}
```

We should put this in the release notes. I think we should go ahead with the change as it unifies the behavior of `override val` and `override def`, so LGTM from my side.

**Comment by retronym** [comment]
- [x] Perhaps we should let people turn this off under `-Xsource:2.11`. Otherwise, I'm also in favour of this change.

**Comment by lrytz** [comment]
Here's another example that changes. The pattern is "whenever the expected type affects the type assigned to an expression" - are there others?

```
class A

class B extends A {
  def y: Int = 0
}

class B1 extends B
class B2 extends B

class C {
  def f: A = null
}

class D extends C {
  def s = ""
  override final val f = s match {
    case "" => new B1
    case _ => new B2
  }

  def m = f.y // doesn't compile anymore
}
```

**Comment by adriaanm** [comment]
Good point, @lrytz! If-else, implicit conversion would also be affects.
@retronym previously pointed out the implicit-conversion-through-view case, which I rendered as https://github.com/adriaanm/scala/blob/fields-prep-sig-infer/test/files/pos/val_infer.scala

**Comment by adriaanm** [comment]
I'm going to close this PR and resubmit as part of the trait encoding rework, since it turns out there are some subtle issues with the new encoding and this fix.

**Comment by adriaanm** [comment]
[Carrying over](https://github.com/scala/scala/compare/2.12.x...adriaanm:traits-late-fields?expand=1) tests and review feedback, of course.

**Pull request closed without merging**
