### PR TITLE
Move ASM out of the repository [ci: last-only]

### PR DESCRIPTION
**Pull request by lrytz**
Changes the build scripts to integrate the classfiles from the scala-asm dependency into scala-compiler.jar.

### CODE REVIEW

**Comment by lrytz** [comment]
review by @retronym

**Comment by retronym** [comment]
Can you post a transcript to show that scala-compiler.jar is byte-for-byte identical after this change? IT will LGTM then.

**Comment by lrytz** [comment]
```
lucmac:scala luc$ git lg -n 1
*   e12ba55 - (HEAD -> 2.11.x, upstream/2.11.x, origin/2.11.x) Merge pull request #4491 from som-snytt/issue/noassertions (5 days ago) <Lukas Rytz>
```

```
lucmac:scala luc$ rm -rf build

lucmac:scala luc$ ant -Dlocker.skip=1
[...]
BUILD SUCCESSFUL

lucmac:scala luc$ mv build sandbox/build-ant-with-asm
```

```
lucmac:scala luc$ sbt clean compiler/packageBin
[...]
[success] Total time: 173 s, completed May 11, 2015 2:42:55 PM

lucmac:scala luc$ mv build-sbt sandbox/build-sbt-with-asm
```

```
lucmac:scala luc$ git co removeAsm 

lucmac:scala luc$ git lg -n 1
* 6fc2a68 - (HEAD -> removeAsm) Remove ASM sources (13 minutes ago) <Lukas Rytz>
```

```
lucmac:scala luc$ ant -Dlocker.skip=1
[...]
BUILD SUCCESSFUL

lucmac:scala luc$ mv build sandbox/build-ant-no-asm
```

```
lucmac:scala luc$ sbt clean compiler/packageBin
[...]
[success] Total time: 179 s, completed May 11, 2015 2:51:28 PM

lucmac:scala luc$ mv build-sbt sandbox/build-sbt-no-asm
```

```
lucmac:scala luc$ cd sandbox/
```

The jars differ (versions in metadata)

```
lucmac:sandbox luc$ diff -r build-ant-with-asm/pack/ build-ant-no-asm/pack/
lucmac:sandbox luc$ diff -r build-ant-with-asm/pack/ build-ant-no-asm/pack/
diff -r build-ant-with-asm/pack/META-INF/MANIFEST.MF build-ant-no-asm/pack/META-INF/MANIFEST.MF
7c7
< Bundle-Version: 2.11.7-20150506-075011-e12ba55589
---
> Bundle-Version: 2.11.7-20150511-142534-6fc2a6897b
Binary files build-ant-with-asm/pack/lib/scala-actors.jar and build-ant-no-asm/pack/lib/scala-actors.jar differ
Binary files build-ant-with-asm/pack/lib/scala-compiler.jar and build-ant-no-asm/pack/lib/scala-compiler.jar differ
Binary files build-ant-with-asm/pack/lib/scala-library.jar and build-ant-no-asm/pack/lib/scala-library.jar differ
Binary files build-ant-with-asm/pack/lib/scala-partest-extras.jar and build-ant-no-asm/pack/lib/scala-partest-extras.jar differ
Binary files build-ant-with-asm/pack/lib/scala-partest-javaagent.jar and build-ant-no-asm/pack/lib/scala-partest-javaagent.jar differ
Binary files build-ant-with-asm/pack/lib/scala-reflect.jar and build-ant-no-asm/pack/lib/scala-reflect.jar differ
Binary files build-ant-with-asm/pack/lib/scalap.jar and build-ant-no-asm/pack/lib/scalap.jar differ
```

Unpack and compare

```
lucmac:sandbox luc$ unzip build-ant-with-asm/pack/lib/scala-compiler.jar -d build-ant-with-asm/pack/lib/scala-compiler
lucmac:sandbox luc$ unzip build-ant-no-asm/pack/lib/scala-compiler.jar -d build-ant-no-asm/pack/lib/scala-compiler
```

```
lucmac:sandbox luc$ diff -r build-ant-with-asm/pack/lib/scala-compiler/ build-ant-no-asm/pack/lib/scala-compiler/

diff -r build-ant-with-asm/pack/lib/scala-compiler/META-INF/MANIFEST.MF build-ant-no-asm/pack/lib/scala-compiler/META-INF/MANIFEST.MF
7c7
< Bundle-Version: 2.11.7-20150506-075011-e12ba55589
---
> Bundle-Version: 2.11.7-20150511-142534-6fc2a6897b


diff -r build-ant-with-asm/pack/lib/scala-compiler/compiler.properties build-ant-no-asm/pack/lib/scala-compiler/compiler.properties
1c1
< #Mon, 11 May 2015 14:28:42 +0200
---
> #Mon, 11 May 2015 14:34:45 +0200
3c3
< version.number=2.11.7-20150506-075011-e12ba55589
---
> version.number=2.11.7-20150511-142534-6fc2a6897b
5c5
< osgi.version.number=2.11.7.v20150506-075011-e12ba55589
---
> osgi.version.number=2.11.7.v20150511-142534-6fc2a6897b


diff -r build-ant-with-asm/pack/lib/scala-compiler/interactive.properties build-ant-no-asm/pack/lib/scala-compiler/interactive.properties
1c1
< #Mon, 11 May 2015 14:29:43 +0200
---
> #Mon, 11 May 2015 14:35:47 +0200
3c3
< version.number=2.11.7-20150506-075011-e12ba55589
---
> version.number=2.11.7-20150511-142534-6fc2a6897b
5c5
< osgi.version.number=2.11.7.v20150506-075011-e12ba55589
---
> osgi.version.number=2.11.7.v20150511-142534-6fc2a6897b


diff -r build-ant-with-asm/pack/lib/scala-compiler/repl.properties build-ant-no-asm/pack/lib/scala-compiler/repl.properties
1c1
< #Mon, 11 May 2015 14:29:04 +0200
---
> #Mon, 11 May 2015 14:35:08 +0200
3c3
< version.number=2.11.7-20150506-075011-e12ba55589
---
> version.number=2.11.7-20150511-142534-6fc2a6897b
5c5
< osgi.version.number=2.11.7.v20150506-075011-e12ba55589
---
> osgi.version.number=2.11.7.v20150511-142534-6fc2a6897b


Only in build-ant-no-asm/pack/lib/scala-compiler/: scala-asm.properties


diff -r build-ant-with-asm/pack/lib/scala-compiler/scaladoc.properties build-ant-no-asm/pack/lib/scala-compiler/scaladoc.properties
1c1
< #Mon, 11 May 2015 14:29:27 +0200
---
> #Mon, 11 May 2015 14:35:31 +0200
```

Comparing the sbt artifacts

```
lucmac:sandbox luc$ unzip build-sbt-with-asm/pack/lib/scala-compiler.jar -d build-sbt-with-asm/pack/lib/scala-compiler
lucmac:sandbox luc$ unzip build-sbt-no-asm/pack/lib/scala-compiler.jar -d build-sbt-no-asm/pack/lib/scala-compiler
```

Turns out, before my change, the asm classfiles were [not added to scala-compiler.jar](https://github.com/scala/scala/blob/2.11.x/build.sbt#L176) - that was an oversight.

```
lucmac:sandbox luc$ diff -r build-sbt-with-asm/pack/lib/scala-compiler build-sbt-no-asm/pack/lib/scala-compiler

diff -r build-sbt-with-asm/pack/lib/scala-compiler/compiler.properties build-sbt-no-asm/pack/lib/scala-compiler/compiler.properties
1c1
< #Mon May 11 14:40:03 CEST 2015
---
> #Mon May 11 14:48:29 CEST 2015
3,4c3,4
< version.number=2.11.6-SNAPSHOT-20150506-075011-e12ba55589
< osgi.version.number=2.11.6.v20150506-075011-e12ba55589
---
> version.number=2.11.6-SNAPSHOT-20150511-142534-6fc2a6897b
> osgi.version.number=2.11.6.v20150511-142534-6fc2a6897b


Only in build-sbt-no-asm/pack/lib/scala-compiler/scala/tools: asm


Only in build-sbt-no-asm/pack/lib/scala-compiler: scala-asm.properties
```

**Comment by lrytz** [comment]
pushed the intellij fix

**Comment by retronym** [comment]
LGTM

**Pull request merged**
