### PR TITLE
SI-3346 implicit parameters can now guide implicit view inference

### PR DESCRIPTION
**Pull request by xeno-by**
This simple patch makes it possible for implicit views to benefit from
fundep-guided type inference, eliminating a nasty special case in
implicit inference.

Here are the changes that I had to apply to the tests (they exposed
quite a number of interesting questions that I was happy to answer):

1) neg/t5845.scala now works, so I moved it to pos. That easily makes sense,
because the test was just a canary to track previous state of things.

2) neg/divergent_implicit.scala, neg/t5578.scala and neg/t7519.scala
changed their messages to less informative ones, because inapplicable
implicit views now get disqualified early and therefore don't display
their error messages to the user. This is an unfortunate but necessary
byproduct of this change, and one can argue that the behavior is now
completely consistent with implicit vals (that also don't explain why
this or that implicit val got disqualified, but rather display a generic
implicit value not found message).

3) scaladoc/implicits-chaining.scala and scaladoc/implicits-base.scala.
Immediate culling of apriori inapplicable implicit views messes things up
for Scaladoc, because it's interested in potentially applicable views,
having infrastructure to track various constraints (type bounds, requirements
for implicit parameters, etc) that guide applicability of views and then
present it to the user. Therefore, when scaladoc is detected, implicit search
reverts to the old behavior.

4) We still cannot have Jason's workaround to type constructor inference
mentioned in comments to SI-3346, because it's not really about implicit
parameters of implicit views, but about type inference flowing from the
implicit parameter list to a preceding parameter list in order to affect
inference of an implicit view. This is something that's still too ambitious.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @adriaanm

**Comment by xeno-by** [comment]
Allright we've seen Slick build fine with this PR.

**Comment by xeno-by** [comment]
I've also just successfully built and tested shapeless 2.0.0-M1 /cc @milessabin

**Comment by xeno-by** [comment]
I've been able to compile scalaz 7.0.5-SNAPSHOT, but I couldn't run tests, because they all depend on Specs2, which doesn't yet have a 2.11 build /cc @larsrh @etorreborre

**Comment by milessabin** [comment]
@xeno-by awesome :-)

**Comment by xeno-by** [comment]
Just built and tested the specs2 2.2.3 branch **with 2.11.0-M4**.

Everything went fine apart from a couple failures /cc @etorreborre:
1) `SimpleBuildManager` has been removed in 2.11, so `CompilerDependencyFinder` doesn't work now.
2) `setPosition` in `MatcherMacros` didn't check whether it's legal to do `setPos`. I inserted a check for `t.canHaveAttrs` and macros stopped crashing.
3) I also upgraded to shapeless 2.0, so I had to change `import shapeless.ToList` to `import shapeless.ops.hlist.ToList`.

```
[error] Error: Total 2175, Failed 5, Errors 1, Passed 2169
[error] Failed tests:
[error]      examples.GWTSpec
[error]      org.specs2.runner.TestInterfaceRunnerSpec
[error]      org.specs2.specification.GivenWhenThenSpec
[error] Error during tests:
[error]      org.specs2.DependenciesSpec
[error] (specs2/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 259 s, completed Oct 11, 2013 4:25:49 PM
```

**Comment by xeno-by** [comment]
However, when I tried to build specs2 2.2.3 with this pull request, I got several errors:

```
[error] /Users/xeno_by/Projects/specs2/src/main/scala/org/specs2/specification/script/GWT.scala:162: type arguments [Any,Any,Any,Any] do not conform to class Mapper's type parameter bounds [T,P <: shapeless.HList,U,R]
[error]                 val map = mapper.asInstanceOf[Mapper[Any, Any, Any, Any]]
[error]                     ^
[error] /Users/xeno_by/Projects/specs2/src/main/scala/org/specs2/specification/script/GWT.scala:162: type arguments [Any,Any,Any,Any] do not conform to class Mapper's type parameter bounds [T,P <: shapeless.HList,U,R]
[error]                 val map = mapper.asInstanceOf[Mapper[Any, Any, Any, Any]]
[error]                                               ^
[error] /Users/xeno_by/Projects/specs2/src/main/scala/org/specs2/specification/script/GWT.scala:175: type arguments [Any,Any,Any,Any] do not conform to class VerifyFunction's type parameter bounds [T,P <: shapeless.HList,U,R]
[error]                   val verifyFunction = verify.asInstanceOf[VerifyFunction[Any, Any, Any, Any]]
[error]                       ^
[error] /Users/xeno_by/Projects/specs2/src/main/scala/org/specs2/specification/script/GWT.scala:175: type arguments [Any,Any,Any,Any] do not conform to class VerifyFunction's type parameter bounds [T,P <: shapeless.HList,U,R]
[error]                   val verifyFunction = verify.asInstanceOf[VerifyFunction[Any, Any, Any, Any]]
[error]                                                            ^
```

In dismay, I tried to build specs2 with current master only to discover that it produces the same error. Looks like a regression that happened somewhere in-between M4 and today.

```
> show scala-instance
[info] Scala instance{version label 2.11.0-20131007-164305-acd77803f7, actual version 2.11.0-20131007-164305-acd77803f7, library jar: /Users/xeno_by/Projects/Master/build/pack/lib/scala-library.jar, compiler jar: /Users/xeno_by/Projects/Master/build/pack/lib/scala-compiler.jar}
```

/cc @retronym

**Comment by retronym** [comment]
I was in touch with Eric a few weeks ago suggesting that he tries to modularise specs2 a little such that specs2-core could have fewer dependencies. 

The dependencies we discussed:
- compiler internals / macro annotations
- scalaz (because scalaz itself needs specs2 to test.) Probably the correct way out of this cycle is to change Scalaz to just use Scalacheck to test, rather than specs2.
- shapeless (not really as big a problem because there is no cycle, shapeless is tested with JUnit.)

He said he would be busy for a little while but would look at this.

**Comment by xeno-by** [comment]
@retronym @larsrh @etorreborre Looks like we've got another regression on our hands. Can be reproduced with both 2.11.0-M4 and current master.

The following sequence of actions doesn't work:
1) Build and publish-local scalaz with 2.11.0-M4
2) Build and publish-local specs2 with 2.11.0-M4
3) Use the just built specs2 package to run sbt test for scalaz

```
> show scala-instance
...
[info] core/*:scalaInstance
[info]  Scala instance{version label 2.11.0-20131007-164305-acd77803f7, actual version 2.11.0-20131007-164305-acd77803f7, library jar: /Users/xeno_by/Projects/Master/build/pack/lib/scala-library.jar, compiler jar: /Users/xeno_by/Projects/Master/build/pack/lib/scala-compiler.jar}
..
> test
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: conforms is not a valid implicit value for (=> org.specs2.matcher.MatchResult[Option[List[Int]]]) => org.scalacheck.Prop because:
[info] hasMatchingSymbol reported error: type mismatch;
[info]  found   : <:<[=> org.specs2.matcher.MatchResult[Option[List[Int]]],=> org.specs2.matcher.MatchResult[Option[List[Int]]]]
[info]  required: (=> org.specs2.matcher.MatchResult[Option[List[Int]]]) => org.scalacheck.Prop
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                                ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: scalacheck.this.Arbitrary.arbContainer is not a valid implicit value for org.scalacheck.Arbitrary[Int] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [C[_], T]org.scalacheck.Arbitrary[C[T]]
[info]  required: org.scalacheck.Arbitrary[Int]
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                                ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: scalacheck.this.Shrink.shrinkContainer is not a valid implicit value for org.scalacheck.Shrink[Int] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [C[_], T]org.scalacheck.Shrink[C[T]]
[info]  required: org.scalacheck.Shrink[Int]
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                                ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: matchResultAsResult is not a valid implicit value for org.specs2.execute.AsResult[org.scalacheck.Prop] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [M[_] <: org.specs2.matcher.MatchResult[_]]org.specs2.execute.AsResult[M[_]]
[info]  required: org.specs2.execute.AsResult[org.scalacheck.Prop]
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: propAsResult is not a valid implicit value for org.specs2.execute.AsResult[org.scalacheck.Prop] because:
[info] hasMatchingSymbol reported error: could not find implicit value for parameter p: org.specs2.matcher.Parameters
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: scopeAsResult is not a valid implicit value for org.specs2.execute.AsResult[org.scalacheck.Prop] because:
[info] typing TypeApply reported errors for the implicit tree: type arguments [org.scalacheck.Prop] do not conform to method scopeAsResult's type parameter bounds [S <: org.specs2.specification.Scope]
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: conforms is not a valid implicit value for org.scalacheck.Prop => org.specs2.execute.Result because:
[info] hasMatchingSymbol reported error: type mismatch;
[info]  found   : <:<[org.scalacheck.Prop,org.scalacheck.Prop]
[info]  required: org.scalacheck.Prop => org.specs2.execute.Result
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: asResult is not a valid implicit value for org.scalacheck.Prop => org.specs2.execute.Result because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [M[_] <: org.specs2.matcher.MatchResult[_]](r: M[_])org.specs2.execute.Result
[info]  required: org.scalacheck.Prop => org.specs2.execute.Result
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: checkProp is not a valid implicit value for org.scalacheck.Prop => org.specs2.execute.Result because:
[info] hasMatchingSymbol reported error: could not find implicit value for parameter p: org.specs2.matcher.Parameters
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: execute.this.AsResult.asResult is not a valid implicit value for org.specs2.execute.AsResult[org.scalacheck.Prop] because:
[info] hasMatchingSymbol reported error: No implicit view available from org.scalacheck.Prop => org.specs2.execute.Result.
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[info] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: execute.this.AsResult.resultAsResult is not a valid implicit value for org.specs2.execute.AsResult[org.scalacheck.Prop] because:
[info] typing TypeApply reported errors for the implicit tree: type arguments [org.scalacheck.Prop] do not conform to method resultAsResult's type parameter bounds [R <: org.specs2.execute.Result]
[info]   "filterM is the same" ! prop { (l: List[Int]) =>
[info]                         ^
[error] /Users/xeno_by/Projects/scalaz/tests/src/test/scala/scalaz/ApplicativeTest.scala:30: could not find implicit value for evidence parameter of type org.specs2.execute.AsResult[org.scalacheck.Prop]
[error]   "filterM is the same" ! prop { (l: List[Int]) =>
[error]
```

**Comment by xeno-by** [comment]
@adriaanm A quick recap on how this PR works with community libraries:
1) Slick is fine
2) Shapeless is fine
3) Specs2 doesn't compile because of a regression in master => couldn't check the PR itself
4) Scalaz doesn't compile because of a regression in master => couldn't check the PR itself

**Comment by retronym** [comment]
I'm chasing this scalaz regression:

```
[error] /Users/jason/code/scalaz/core/src/main/scala/scalaz/Free.scala:203: could not find implicit value for evidence parameter of type scalaz.Functor[[+x](=> S) => x]
[error]           Return[({type f[+x] = (=> S) => x})#f, A](a))
[error]
```

**Comment by retronym** [comment]
SimpleBuildManager was deprecated in 2.10 and removed in 2.11. https://github.com/scala/scala/commit/b61a64ddb5700b5d77295df43af0e3feb3c46ac6

**Comment by retronym** [comment]
The regression is with code like:

```
object Test {
  trait Monad[M[_]] {
    def foo[A](ma: M[A])(f: M[A] => Any) = f(ma)
  }
  implicit def function1Covariant[T]: Monad[({type l[a] = (T => a)})#l] =
    new Monad[({type l[a] = (T => a)})#l] {}

  def main(args: Array[String]) {
    val m = implicitly[Monad[({type f[+x] = (=> Any) => x})#f]]
    println(m.foo[Int]((x => 0))(f => f(???)))
  }
}
```

The implicit search used to work, inferring `=> Any` as the type argument to `function1Covariant`. Since b6426bc4cdc3ce968044218ddee2b952e288030e this is not allowed, as it was shown to lead to ClassCastExceptions. You can't write that type explicitly:

```
scala> foo[(=> Int)](0)
<console>:1: error: no by-name parameter type allowed here
       foo[(=> Int)](0)
            ^
```

So the reasoning was that we shouldn't infer it.

There might be cases where it is safe to do this if the by-name type passes in and out of some abstraction without ever being observed internally by generic code. So maybe I'll have to put this behind a flag for a while.

**Comment by cvogt** [comment]
@retronym: The referenced commit b6426bc leads to page not found.

**Comment by etorreborre** [comment]
@retronym @xeno-by I came back from holidays last week and I've been a bit busy but I've now started to create modules for specs2. Don't expect anything too soon because:
- I have a few unwanted dependencies in my code. I was expecting this and it is good to finally remove them
- I need to understand how the sbt multi-project build works. I'm using scalaz as a guide but if you know other good examples of multi-projects please tell me

**Comment by xeno-by** [comment]
@retronym Shall we merge this one granted that it's proven to work with several important community libraries?

**Comment by retronym** [comment]
Scalaz also blends with this patch:

```
[info] Passed: Total 3721, Failed 0, Errors 0, Passed 3721
[success] Total time: 247 s, completed Oct 18, 2013 4:11:53 PM
> show scalaInstance
[info] scalacheck-binding/*:scalaInstance
[info]  Scala instance{version label 2.11.0-20131011-130349-210dbc7887, actual version 2.11.0-20131011-130349-210dbc7887, library jar: /code/scala/build/pack/lib/scala-library.jar, compiler jar: /code/scala/build/pack/lib/scala-compiler.jar}
```

LGTM

**Comment by retronym** [comment]
Thanks for this fix, and your patience in waiting for battle testing!

**Comment by xeno-by** [comment]
:)

**Comment by adriaanm** [comment]
Yep, good stuff -- thanks!

**Pull request merged**
