### PR TITLE
Merge v2.10.1-326-g4f8c306 into master

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
This is #2551 with the one stupid checkfile updated.

**Comment by xeno-by** [comment]
Looks like my stuff is merged correctly.

**Comment by retronym** [comment]
Thanks for this.

**Comment by xeno-by** [comment]
However I'm unsure why the FieldMirror commit is shown as a failure. Do master builds also check binary compatibility?

**Comment by retronym** [comment]
That's just the status of that commit, before the merge, with the BC breakage. Nothing to worry about.

**Comment by paulp** [comment]
I don't know if everything passed, but jenkins has called it a day. I think it passed. Wish I knew how to tell.

**Comment by retronym** [comment]
PLS SYNCH

**Comment by retronym** [comment]
I think this is fine, it's just complaining about that broken 2.10.x commit. Perhaps @adriaanm can give the all clear by merging this.

**Comment by adriaanm** [comment]
LGTM, @retronym's interpretation is correct

**Pull request merged**
