### PR TITLE
Quieting down a bunch of warnings.

### PR DESCRIPTION
**Pull request by paulp**
This should offer a more soothing building experience.

### CODE REVIEW

**Comment by paulp** [comment]
NOLITTER!

**Comment by paulp** [comment]
In case it's not clear, the only "failure" is the test I had to disable for demanding a gig of memory to pass.

**Comment by paulp** [comment]
Review @retronym

**Comment by retronym** [comment]
LGTM. Thank you! And apologies for merging the troublesome `BitSet` test.

**Comment by paulp** [comment]
I wouldn't have spotted what the test was doing either.

**Pull request merged**
