### PR TITLE
Change Doc to trait to allow it to be used as a cake slice.

### PR DESCRIPTION
**Pull request by vigdorchik**
Change the implementation of retrieve() method to make the right distinction between
library and source symbols.
Rename and privatize symbols in CommentFactoryBase to avoid clashes when cooking a cake.

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @dragos

**Comment by dragos** [comment]
Could you write a test for this behavior? Otherwise the code looks good.

**Comment by vigdorchik** [comment]
@dragos please see the updated CL: the test now also checks mixin with Global is possible.

**Comment by paulp** [comment]
There's a legit failure in there.

```
  [partest] testing: [...]/files/presentation/memory-leaks                        [FAILED]
  [partest] MemoryLeaksTest.scala:28: error: not found: value docSettings
  [partest]   override val settings: doc.Settings = docSettings
  [partest]                                         ^
  [partest] one error found
```

**Comment by paulp** [comment]
Closing temporarily pending test fix; it's a fire hazard having all these pull requests in close quarters.

**Pull request closed without merging**
