### PR TITLE
SI-7391 Always use ForkJoin in Scala actors on ...

### PR DESCRIPTION
**Pull request by soc**
... Java 6 and above (except when the porperty
actors.enableForkJoin says otherwise)

Like SI-7236 and SI-7237, the logic in
scala.actors.scheduler.ThreadPoolConfig.useForkJoin
(which resulted in a different thread pool implementation
being chosen) was causing random hangs in the test
concurrent-stream.scala when running on Avian.

### CODE REVIEW

**Comment by soc** [comment]
Considering that tectonic plates seem to move faster than the pull request queue recently, I'm cutting down on pull requests.

This one supersedes https://github.com/scala/scala/pull/2415 and https://github.com/scala/scala/pull/2414 and contains only the minimum necessary to stop actors from dead-locking based on the `javaVmVendor` string.

Review by @gkossakowski, @adriaanm, @phaller or anyone else, please.

**Comment by adriaanm** [comment]
For many reasons it's best to keep PRs minimal, especially those that "tweak stuff". Thanks. 

So, why does this no longer catch the SecurityException?

PS: I understand your frustration with the PR queue and I apologize. We're doing the best we can. Due to various circumstances (travel, conferences, vacation time,...) we've fallen behind a little recently, but I think we've made a good dent in the queue in the last couple of days.

**Comment by soc** [comment]
@adriaanm Sorry, I missed those lines when I put the old code back into the method. I fixed it now.

Hey, nothing to apologize for! Sometimes, stuff is just too busy. That's not the fault of anyone, that's just the way it is. (Although I'm sometimes a bit concerned about the bus factor of the people with merge privileges... but that's a different discussion)

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
