### PR TITLE
SIP-33 - Priority-based infix type precedence

### PR DESCRIPTION
**Pull request by soronpo**
Implements SIP33: Priority-based infix type precedence
https://docs.scala-lang.org/sips/priority-based-infix-type-precedence.html

### CODE REVIEW

**Comment by soronpo** [comment]
@milessabin or @SethTisue please trigger community-build check for this PR.

**Comment by SethTisue** [comment]
@soronpo I seem to have dropped the ball there, sorry. if you rebase this against current 2.13.x, I'll run the community build.

**Comment by dwijnand** [comment]
@soronpo Just a (re) heads up: this is currently failing on Jenkins and it has merge conflicts with the target branch. Given SIP-33 has been accepted, it would be lovely to actually ship it too! 😄

**Comment by soronpo** [comment]
Yeah, thanks. I was waiting for the 2.13-M4 community build to stabilize on green before resolving this issue (because I want to make sure I'm not breaking anything).

**Comment by soronpo** [comment]
@SethTisue can you please run a community build for this branch?

**Comment by SethTisue** [comment]
> I was waiting for the 2.13-M4 community build to stabilize on green

there are currently 46 green projects in the 2.13 build (out of ~170). that's enough to give some assurance. stronger additional assurance is available if you backport a change to 2.12.x (even if it's not intended to actually be merged there) and run the community build on that.

I'll trigger a build for you sometime today.

**Comment by SethTisue** [comment]
in progress: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1289/

**Comment by soronpo** [comment]
@SethTisue why was the build aborted?

**Comment by soronpo** [comment]
NM, I've now noticed the `parsed` outputs. Gives a much clearer picture of what is going on.

**Comment by SethTisue** [comment]
the build aborted because nscala-time's tests hung. might be related to the PR, or might be transient, let's try again: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1292/

**Comment by SethTisue** [comment]
```
[kind-projector] [info] ======= Position error
[kind-projector] [info] Enclosing tree [527] does not include tree [432]
[kind-projector] [info] == Enclosing tree [527] of type AppliedTypeTree at [450:454]hmm.scala
[kind-projector] [info] [L  16        ] #527    [450:454]       AppliedTypeTree // :: In
[kind-projector] [info] == Enclosed tree [432] of type Ident at [280:282]hmm.scala
[kind-projector] [info] [L  16        ] #432    [280:282]       Ident      // :: 
[kind-projector] [info] 
[kind-projector] [info] While validating #1217
[kind-projector] [info] [L   1        ] #1217   [0:1733]        PackageDef // hmm
[kind-projector] [info] 
[kind-projector] [info] Children:
[kind-projector] [info]   [L   1 P# 1217] #353    [8:11]          Ident      // hmm
[kind-projector] [info]   [L   3 P# 1217] #363    [13:24]         ClassDef   // TC[A]
[kind-projector] [info]   [L   5 P# 1217] #378    [26:65]         ModuleDef  // TC {
[kind-projector] [info]   [L   9 P# 1217] #1216   [67:1733]       ModuleDef  // test {
[kind-projector] [info] =======
```

**Comment by SethTisue** [comment]
@soronpo where do we stand, here?

**Comment by soronpo** [comment]
It's a bit problematic for me to debug the issue since the failure is in a compiler-plugin (kind-projector).
I'm currently overloaded with work, and hope to be getting back to this issue next month.

**Comment by SethTisue** [comment]
okay. we can reopen the ticket when work resumes.

> It's a bit problematic for me to debug the issue since the failure is in a compiler-plugin (kind-projector)

I see... feel free to ask for help (here, or on Gitter or Discourse) with workflow issues

**Pull request closed without merging**
