### PR TITLE
This commit fixes ticket SI-7026

### PR DESCRIPTION
**Pull request by mads-hartmann**
Hi there,

This pull request fixes SI-7026. I've confirmed that the tests fails
before the patch and that they succeed after. I tried to discuss the
ticket on the ML but no-one seemed interested (It was over christmas),
and given that I've already discussed and fixed the issue in the IDE
I thought it was better just to go ahead and fix the problem ;)

Solved it with an implementation that just parses the source every
time without trying to memorize anything. Added tests that checks
that
1. You get a new parse tree every time you ask for one.
2. You always get a parse tree, never a typed tree.
3. A parse tree should never contain any symbols or types [1].
4. If you ask for a parse tree and then ask for a typed tree it
   shouldn't change the parse tree you originally asked for, i.e.
   property 3 still holds.

[1] There is an exception to this though. Some of the nodes that
the compiler generates will actually contain symbols. I've
chosen to just ignore these special cases for now.

### CODE REVIEW

**Comment by mads-hartmann** [comment]
BTW, I've signed the CLA and sent it to Danielle but it appears that Danielle won't get back till the 1st of july. Should I send it someone else then?

**Comment by paulp** [comment]
You can click-sign the [CLA](http://www.typesafe.com/contribute/cla).

**Comment by mads-hartmann** [comment]
Oh, already click-signed that one, so I guess we're good :)

**Comment by dragos** [comment]
LGTM, but please open the pull request against the `2.10.x` branch. That should (eventually) make the patch appear both in the 2.10 and 2.11 versions.

**Comment by adriaanm** [comment]
Thanks, also please note that the commit title will go into release notes.
- SI-7026 unwedges the falangee from the maneehum

is more informative(*) than
- this commit fixes SI-7026

(*) well, if you reword it slightly so that it reads like the action this commit performs on the code base
please have a look at https://github.com/scala/scala/wiki/Pull-Request-Policy

**Comment by mads-hartmann** [comment]
Opened a new PR against 2.10.x here https://github.com/scala/scala/pull/1993

**Pull request closed without merging**
