### PR TITLE
SI-6778 scala.math.random should have parenthesis

### PR DESCRIPTION
**Pull request by kanielc**
There are side-effects as the internal seed is modified

Bringing together work previously done in #4236 (incorrectly based on 2.11.x) and #3741 (too many commits)

@retronym

### CODE REVIEW

**Comment by som-snytt** [comment]
LGTM

Today is when the "parens means side-effecting" rule finally struck me as vapid. Maybe that's just a side-effect of reviewing it.

Nit-pick: the plural is "parentheses", which is why sane people call them "parens". My trusty paper Webster's does say "parenthesis" means one or both of the enclosing marks. Well, a parenthesis is something inserted (such as this parenthetical). But it doesn't have that meaning in code.

**Comment by Ichoran** [comment]
What are the analyzer changes for?  Is that a sign that some rebasing/pushing-to-your-2.12.x was needed, or is that actually (surprisingly!) a consequence of the change to parens?

**Comment by kanielc** [comment]
The latter I assume, since I had started on a clean 2.12.x.

**Comment by som-snytt** [comment]
If you add parens to the test

```
math.random // some statement
```

the difference is that the count of Selects seen with pt ? doesn't change at line 31.

There are three `random` in the test, which is why diffs of 3 turn up. The diff is not surprising because adding the parens implicitly is work.

**Comment by lrytz** [comment]
LGTM, too. Thanks @kanielc and @som-snytt !

**Pull request merged**
