### PR TITLE
Respect -Dpartest.scalac_opts when running the test suite through ANT

### PR DESCRIPTION
**Pull request by lrytz**
Used to enable `-Xcheckinit` (now also `-Ybackend:GenBCode`) when
compiling tests in the respective jenkins builds. This is currently
broken, as you can see in [recent build logs](https://scala-webapps.epfl.ch/jenkins/view/nightlies/job/scala-nightly-checkinit/2058/consoleFull), `-Xcheckinit` is
missing:

```
[partest] Scalac options are:  -optimise
```

### CODE REVIEW

**Comment by lrytz** [comment]
review by @adriaanm

**Comment by lrytz** [comment]
hah, the fix unveiled a number of `rangepos` regressions. these need to be fixed first, otherwise all builds will go red.

**Comment by retronym** [comment]
I thought the decision to not pass `-Yrangepos` to all partest test cases under the rangepos build was by design. For example, some tests might rely on running with offset positions.

Macros expansions, for example, are no longer added to the presentation compiler's post-typer trees; only the computed types are. We don't expect macro authors to rangepos invariants.

Some of the other failures to look like legitimate problems, though. So it would be good to have a way to perform this validation for the 95% of tests that support them.

In 2.11, we can actually negate flags like `-Yrangepos:false` which I think we can use to override the global setting. Maybe we can use this facility here.

/cc @dotta who asked me about this a while ago.

**Comment by lrytz** [comment]
> I thought the decision to not pass `-Yrangepos` to all partest test cases under the rangepos build was by design

The command line that invokes ant suggests otherwise, it mentions `partest.scalac_opts` explicitly:

```
+ ant [...] -Dscalac.args.optimise=-optimise '-Dscalac.args="-Yrangepos"' '-Dpartest.scalac_opts="-Yrangepos"' test.suite test.scaladoc
```

Thanks for the idea to use check files, I take a look.

**Comment by lrytz** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
LGTM

**Comment by lrytz** [comment]
I forgot one `.flags` file, fixed now.

**Pull request closed without merging**
