### PR TITLE
SI-7517 type constructors too eagerly normalized.

### PR DESCRIPTION
**Pull request by paulp**
I think 403eadd0f1 was largely a symptomatic remedy (not that
we shouldn't harden against such outcomes) and that this commit
gets closer to the root causes. The unanticipated change to
test/files/run/t6113.check is like a cry of support from the jury box.

``` diff
-Foo[[X](Int, X)]
+Foo[AnyRef{type l[X] = (Int, X)}#l]
```

We should continue to look upon calls to normalize with grave suspicion.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @retronym

**Comment by retronym** [comment]
I don't feel all that confident in reviewing this. Can you share any more insights into the code you are touching in the commit comment?

**Comment by paulp** [comment]
Types like K[[T]A[B[T]]] shouldn't be created at all. That is a type constructor applied to a polytype. It is, at best, an internal representation; really it's malformed.

But it happens because of unnecessary calls to normalize.

If it provides an appealing sheen of authority, it was adriaan's suggestion to wipe out that map.

**Comment by JamesIry** [comment]
Worth a second set of eyes from @adriaanm as well.

**Comment by adriaanm** [comment]
I'll look into this tomorrow, but in the mean time: `K[[T]A[B[T]]]` is indeed not expressible in surface syntax, but it's not malformed

**Comment by adriaanm** [comment]
LGTM!

**Pull request merged**
