### PR TITLE
SI-8244 Fix raw type regression under separate compilation

### PR DESCRIPTION
**Pull request by retronym**
In #1901, handling of raw types encountered in signatures during class
file parsing was changed to work in the same manner as
`classExistentialType`, by using
`existentialAbstraction(cls.tparms, cls.tpe_*)`

But this never creates fresh existential symbols, and just sticks
the class type parameters it `quantified`:

```
scala> trait T[A <: String]
defined trait T

scala> val cls = typeOf[T[_]].typeSymbol
cls = trait T#101864

scala> cls.typeParams
res0 = List(type A#101865)

scala> cls.tpe_*
res1 = T#101864[A#101865]

scala> classExistentialType(cls)
res3 = T#101864[_ <: String#7209]

scala> val ExistentialType(quantified, result) = res3
List(type A#101865)
```

In the enclosed test case, this class type parameter was substituted
during `typeOf[X] memberType sym`, which led us unsoundly thinking
that `Raw[_]` was `Raw[X]`.

I've added a TODO comment to review the other usages of
`classExistentialType`.

Test variations include joint and separate compilation, and the
corresponding Scala-only code. All fail with type errors now,
as we expect.

Review by @adriaanm. /cc @paulp

### CODE REVIEW

**Comment by paulp** [comment]
It's a miracle that has held together for this long. For sure it should generate fresh existentials.

**Comment by adriaanm** [comment]
I'll adopt this one.

**Comment by retronym** [comment]
Thanks, sorry about leaving this in limbo.

Time for a new pinned tab for me: https://github.com/scala/scala/issues/created_by/retronym?milestone=&page=1&state=open

 (I don't use the `issues` view enough to get an overview of the status labels)

**Comment by adriaanm** [comment]
no worries -- i'm also trying to maintain the assignee field so you can easily find the PRs that need reviewing/merging

**Comment by adriaanm** [comment]
rebased and siamese tests cases separated

**Pull request closed without merging**
