### PR TITLE
SI-10033 First round of deprecation cleanups for 2.13

### PR DESCRIPTION
**Pull request by soc**
This addresses most of the low-hanging fruits in the standard library.

### CODE REVIEW

**Comment by SethTisue** [comment]
sweet! hope Jenkins likes it.

you meant to target the 2.13.x branch, I believe.

**Comment by soc** [comment]
@SethTisue Ouch ... can I change that somehow or do I need to close and open a new PR?

**Comment by soc** [comment]
https://github.com/scala/scala/pull/5515

**Comment by adriaanm** [comment]
For the record, you can change the target using the Edit button.

**Comment by soc** [comment]
Ah, I see it now, thanks! (Is that a recent new feature?)

**Comment by SethTisue** [comment]
> Is that a recent new feature

yes, added in recent months

**Pull request closed without merging**
