### PR TITLE
Revert PR #9818 (GroupedIterator improvements)

### PR DESCRIPTION
**Pull request by SethTisue**
This reverts commit d0474076619bcc64c3cf13a251afb4c056d679a6.

Because it caused community build failures; see scala/community-build#1519 for details

### CODE REVIEW

**Comment by som-snytt** [comment]
I commented on the PR that the community build just uncovers a bad test or assumption about the API. Make that two bad tests. I only looked at twitter-util which was straightforward.

**Comment by SethTisue** [comment]
Regardless, I'm still much more comfortable reverting the PR for 2.13.8, in keeping with the informal alternation we tend to have between big releases with months of changes (e.g. 2.13.7) and modest releases focused on addressing regressions (e.g. 2.13.8).

**Comment by lrytz** [comment]
... I agree.

**Review by joroKr21 — APPROVED** [review]
I agree with the revert. It's reasonable to expect that `smallCollection.grouped(hugeNumber)` won't actually allocate much memory. It's an edge case but a valid edge case IMO (same as `collection.take(negativeNumber)`). I'm now thinking about another approach where we reuse the initial buffer for everything. That should both reduce allocations overall and allow us to let it grow since it would be a one-time cost. I don't see a theoretical reason why we can't do that.

**Pull request merged**
