### PR TITLE
Add IterableOnceOps.fold

### PR DESCRIPTION
**Pull request by szeiger**
Fixes https://github.com/scala/collection-strawman/issues/537

### CODE REVIEW

**Review by julienrf — CHANGES_REQUESTED** [review]
In my opinion we should deprecate `fold`. It was useful only because the parallel collections implemented a parallel fold. But here it is just an alias to `foldLeft`. Or we should at least make it final and document it as an alias (but I see no point in having it).

See also https://github.com/scala/collection-strawman/issues/554

And we should add it to `ArrayOps` as well, since `ArrayOps` doesn’t inherit from `IterableOnceOps`.

**Comment by szeiger** [comment]
It can be implemented in terms of `foldLeft` but it is not the same. The signature of `fold` enforces the symmetry of the operation in the types. You could make a case for the removal of `fold` if there is never a more efficient implementation than `foldLeft` for sequential collection types. We don't have any such implementation in 2.12.

**Comment by julienrf** [comment]
Can you think of a more efficient implementation than `foldLeft` for sequential collection types?

**Comment by szeiger** [comment]
Maybe for some exotic `SortedSet` implementation that allows faster traversal in random order than in sorted order (unlike the red-black tree based structures that we use for `TreeSet` and `TreeMap`).

Also `fold` can be implemented with n-1 combining operations whereas `foldLeft` always needs n. Optimizing for this case could provide some benefit for small collection sizes.

**Review by julienrf — APPROVED** [review]
I’ve been convinced that it’s ok to have `fold` also on sequential collections.

**Comment by szeiger** [comment]
I've added another commit with `ArrayOps.fold`. Unfortunately I was not able to make it any faster than an inlined `foldLeft`. I tried a few variations of this to no avail:

```scala
  def fold[A1 >: A](z: A1)(op: (A1, A1) => A1): A1 = {
    if(xs.length == 0) z else {
      var v: A1 = xs(0)
      var i = 1
      while(i < xs.length) {
        v = op(v, xs(i))
        i += 1
      }
      v
    }
  }
```

They all ended up being twice as slow as `foldLeft`, for all array sizes, with or without scalac optimization, with standard JVM inlining or doubled MaxInlineSize and MaxInlineLevel.

**Comment by julienrf** [comment]
This is a funny result!

**Comment by mkeskells** [comment]
@szeiger is it the cost of length virtual call ?
length is a constant - but the compiler doesn't know that 
```
  def fold[A1 >: A](z: A1)(op: (A1, A1) => A1): A1 = {
    val length = xs.length    
    if(length == 0) z else {
      var v: A1 = xs(0)
      var i = 1
      while(i < length) {
        v = op(v, xs(i))
        i += 1
      }
      v
    }
  }
```

**Comment by Ichoran** [comment]
@mkeskells - That could be because the array is generic, which means it's actually cast as object and has to go through ScalaRunTime.array_length.

**Comment by szeiger** [comment]
Assigning `length` or `xs` to a local variable doesn't make any difference. Those are the first things I tried. Only having a single `xs.apply` call (with a conditional in the loop) doesn't help, either (in fact, it made it slower).

**Comment by viktorklang** [comment]
@szeiger Isn't that version broken since it doesn't use the zero in case the array is non-empty?

What about something like:

~~~scala
 def fold[A1 >: A](z: A1)(op: (A1, A1) => A1): A1 = {
    var v: A1 = z
    val length = xs.length    
    var i = 0
    while(i < length) {
      v = op(v, xs(i))
      i += 1
    }
    v
  }
~~~

**Comment by szeiger** [comment]
No, that's the whole point of it. `fold`, unlike `foldLeft` doesn't have to use the zero element.

**Comment by viktorklang** [comment]
@szeiger Ah, sorry, you're right. the zero cannot affect the outcome anyway.

**Comment by viktorklang** [comment]
I looked at Scala 2.12.3:

~~~scala
class Foo {
  def fold1[A, A1 >: A](xs: Array[A])(z: A1)(op: (A1, A1) => A1): A1 = {
    val length = xs.length
    var v: A1 = z
    if(length > 0) {
      v = xs(0)
      var i = 1
      while(i < length) {
        v = op(v, xs(i))
        i += 1
      }
    }
    v
  }

  def fold2[A,A1 >: A](xs: Array[A])(z: A1)(op: (A1, A1) => A1): A1 = {
    val length = xs.length    
    if(length == 0) z else {
      var v: A1 = xs(0)
      var i = 1
      while(i < length) {
        v = op(v, xs(i))
        i += 1
      }
      v
    }
  }
}
~~~

And it seems like the bytecode is slightly "bloated":

~~~txt
public class $line12.$read$$iw$$iw$Foo {
  public <A, A1> A1 fold1(java.lang.Object, A1, scala.Function2<A1, A1, A1>);
    descriptor: (Ljava/lang/Object;Ljava/lang/Object;Lscala/Function2;)Ljava/lang/Object;
    Code:
       0: getstatic     #24                 // Field scala/runtime/ScalaRunTime$.MODULE$:Lscala/runtime/ScalaRunTime$;
       3: aload_1
       4: invokevirtual #28                 // Method scala/runtime/ScalaRunTime$.array_length:(Ljava/lang/Object;)I
       7: istore        4
       9: aload_2
      10: astore        5
      12: iload         4
      14: iconst_0
      15: if_icmple     69
      18: getstatic     #24                 // Field scala/runtime/ScalaRunTime$.MODULE$:Lscala/runtime/ScalaRunTime$;
      21: aload_1
      22: iconst_0
      23: invokevirtual #32                 // Method scala/runtime/ScalaRunTime$.array_apply:(Ljava/lang/Object;I)Ljava/lang/Object;
      26: astore        5
      28: iconst_1
      29: istore        6
      31: iload         6
      33: iload         4
      35: if_icmpge     66
      38: aload_3
      39: aload         5
      41: getstatic     #24                 // Field scala/runtime/ScalaRunTime$.MODULE$:Lscala/runtime/ScalaRunTime$;
      44: aload_1
      45: iload         6
      47: invokevirtual #32                 // Method scala/runtime/ScalaRunTime$.array_apply:(Ljava/lang/Object;I)Ljava/lang/Object;
      50: invokeinterface #38,  3           // InterfaceMethod scala/Function2.apply:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
      55: astore        5
      57: iload         6
      59: iconst_1
      60: iadd
      61: istore        6
      63: goto          31
      66: goto          69
      69: aload         5
      71: areturn

  public <A, A1> A1 fold2(java.lang.Object, A1, scala.Function2<A1, A1, A1>);
    descriptor: (Ljava/lang/Object;Ljava/lang/Object;Lscala/Function2;)Ljava/lang/Object;
    Code:
       0: getstatic     #24                 // Field scala/runtime/ScalaRunTime$.MODULE$:Lscala/runtime/ScalaRunTime$;
       3: aload_1
       4: invokevirtual #28                 // Method scala/runtime/ScalaRunTime$.array_length:(Ljava/lang/Object;)I
       7: istore        4
       9: iload         4
      11: iconst_0
      12: if_icmpne     19
      15: aload_2
      16: goto          69
      19: getstatic     #24                 // Field scala/runtime/ScalaRunTime$.MODULE$:Lscala/runtime/ScalaRunTime$;
      22: aload_1
      23: iconst_0
      24: invokevirtual #32                 // Method scala/runtime/ScalaRunTime$.array_apply:(Ljava/lang/Object;I)Ljava/lang/Object;
      27: astore        5
      29: iconst_1
      30: istore        6
      32: iload         6
      34: iload         4
      36: if_icmpge     67
      39: aload_3
      40: aload         5
      42: getstatic     #24                 // Field scala/runtime/ScalaRunTime$.MODULE$:Lscala/runtime/ScalaRunTime$;
      45: aload_1
      46: iload         6
      48: invokevirtual #32                 // Method scala/runtime/ScalaRunTime$.array_apply:(Ljava/lang/Object;I)Ljava/lang/Object;
      51: invokeinterface #38,  3           // InterfaceMethod scala/Function2.apply:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
      56: astore        5
      58: iload         6
      60: iconst_1
      61: iadd
      62: istore        6
      64: goto          32
      67: aload         5
      69: areturn

  public $line12.$read$$iw$$iw$Foo();
    descriptor: ()V
    Code:
       0: aload_0
       1: invokespecial #51                 // Method java/lang/Object."<init>":()V
       4: return
}
~~~

**Comment by szeiger** [comment]
Yes, there's some overhead for polymorphic arrays in bytecode but hotspot seems to take care of it. My benchmarks showed no difference in performance.

I'm going to merge this and then try to simplify the benchmarking setup so it's easier to test this stuff. If anyone has a good idea how to make it faster and can prove that it actually works in a benchmark (unlike all my good ideas so far), please open a PR.

**Comment by szeiger** [comment]
Random thought: It would be very useful to be able to specialize on an existing type from the scope (not just a new type variable). These methods would be good candidates for specialization but if we specialize the whole class we lose the benefit of extension methods.

**Pull request merged**
