### PR TITLE
Upgrade pax-url-aether to 1.6.0.

### PR DESCRIPTION
**Pull request by adriaanm**
Since our jenkins uses mirrors with passwords,
we needed a fix for https://ops4j1.jira.com/browse/PAXURL-217
in order to run osgi.test on jenkins, now that we use maven more.
We didn't hit this bug before because we were using a standard
location for the maven local repository, but that causes problems
with concurrent jenkins jobs accessing it.

### CODE REVIEW

**Comment by adriaanm** [comment]
Ah, another instance of https://groups.google.com/d/msg/scala-internals/7R-Y5txP8NI/DX_JWFO2fu4J
Because we're skipping locker.... Let's see if bumping starr to 2.10.3 fixes it.

Alsooooo... does this mean we broke bin compat in 2.10.x for extension methods?

**Comment by adriaanm** [comment]
What do ya'll think about using 2.10.3 for STARR? Or, in general, using the last released version of Scala to build the next one? /cc @JamesIry, @gkossakowski, @retronym

**Comment by retronym** [comment]
I'd like to understand the incompatibility. That might point out an argument for/against moving Starr around during maintainence releases:

Here's the [build failure](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/3953/console):

```
[error] error: java.lang.AssertionError: assertion failed: 
[error]      while compiling: /tmp/sbt_aaeda3b2/CompilerInterface.scala
[error]         during phase: global=erasure, atPhase=refchecks
[error]      library version: version 2.10.4-79243c1-SNAPSHOT
[error]     compiler version: version 2.10.4-79243c1-SNAPSHOT
[error]   reconstructed args: -classpath /localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/./target-0.7.0/sbt-base-dir/runner/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.4/xsbti/interface-0.12.4.jar:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/./target-0.7.0/sbt-base-dir/runner/boot/scala-2.9.2/org.scala-sbt/sbt/0.12.4/compiler-interface-src/compiler-interface-src-0.12.4.jar:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-07cb816991c036b8740b19901baae694b50cbf2d/.dbuild/scala/58ea94255b3790d349b7e31601abf1cb932c0ac6/lib/scala-compiler.jar:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-07cb816991c036b8740b19901baae694b50cbf2d/.dbuild/scala/58ea94255b3790d349b7e31601abf1cb932c0ac6/lib/scala-library.jar:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-07cb816991c036b8740b19901baae694b50cbf2d/.dbuild/scala/58ea94255b3790d349b7e31601abf1cb932c0ac6/lib/scala-compiler.jar:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-07cb816991c036b8740b19901baae694b50cbf2d/.dbuild/scala/58ea94255b3790d349b7e31601abf1cb932c0ac6/lib/scala-reflect.jar -bootclasspath /home/jenkins/apps/jdk1.6.0_33-x64/jre/lib/resources.jar:/home/jenkins/apps/jdk1.6.0_33-x64/jre/lib/rt.jar:/home/jenkins/apps/jdk1.6.0_33-x64/jre/lib/sunrsasign.jar:/home/jenkins/apps/jdk1.6.0_33-x64/jre/lib/jsse.jar:/home/jenkins/apps/jdk1.6.0_33-x64/jre/lib/jce.jar:/home/jenkins/apps/jdk1.6.0_33-x64/jre/lib/charsets.jar:/home/jenkins/apps/jdk1.6.0_33-x64/jre/lib/modules/jdk.boot.jar:/home/jenkins/apps/jdk1.6.0_33-x64/jre/classes:/localhome/jenkins/b/workspace/pr-scala-integrate-ide/target/zinc/target-0.7.0/project-builds/sbinary-07cb816991c036b8740b19901baae694b50cbf2d/.dbuild/scala/58ea94255b3790d349b7e31601abf1cb932c0ac6/lib/scala-library.jar -nowarn -d /tmp/sbt_b359eb70
[error] 
[error]   last tree to typer: TypeTree(class CompilerCommand)
[error]               symbol: class CompilerCommand in package nsc (flags: )
[error]    symbol definition: class CompilerCommand extends Object
[error]                  tpe: tools.nsc.CompilerCommand
[error]        symbol owners: class CompilerCommand -> package nsc
[error]       context owners: method apply -> anonymous class $anonfun -> method run -> class CachedCompiler0 -> package xsbt
[error] 
[error] == Enclosing template or block ==
...
[error] TypeRef(TypeSymbol(class CompilerCommand extends Object))
[error] 
[error] no extension method found for:
[error] 
[error]   method toHexString:=> String
[error] 
[error]  Candidates:
[error] 
[error]  
[error] 
[error]  Candidates (signatures normalized):
[error] 
[error]  
[error] 
[error]  Eligible Names: toHexString$extension"
[error]     at scala.tools.nsc.transform.ExtensionMethods$$anonfun$extensionMethod$1.apply(ExtensionMethods.scala:77)
[error]     at scala.tools.nsc.transform.ExtensionMethods$$anonfun$extensionMethod$1.apply(ExtensionMethods.scala:73)
[error]     at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
```

**Comment by retronym** [comment]
I can't spot any obvious differences with javap or scalap:

```
% echo :javap scala.runtime.RichInt | scala-hash v2.10.0 | grep Hex; reset
    public static java.lang.String toHexString$extension(int);
    public java.lang.String toHexString();
% echo :javap scala.runtime.RichInt | scala-hash v2.10.3 | grep Hex; reset
    public static java.lang.String toHexString$extension(int);
    public java.lang.String toHexString();
% echo :javap scala.runtime.RichInt$ | scala-hash v2.10.0 | grep Hex; reset
    public final java.lang.String toHexString$extension(int);
% echo :javap scala.runtime.RichInt$ | scala-hash v2.10.3 | grep Hex; reset
    public final java.lang.String toHexString$extension(int);

% RUNNER=scalap scala-hash v2.10.0 scala.runtime.RichInt | grep -i hex
  def toHexString : scala.Predef.String = { /* compiled code */ }
  final def toHexString$extension($this : scala.runtime.RichInt) : scala.Predef.String = { /* compiled code */ }
% RUNNER=scalap scala-hash v2.10.3 scala.runtime.RichInt | grep -i hex
  def toHexString : scala.Predef.String = { /* compiled code */ }
  final def toHexString$extension($this : scala.runtime.RichInt) : scala.Predef.String = { /* compiled code */ }
```

Might have some more luck with this one in the meantime:

image

**Comment by retronym** [comment]
Any tips on how to run the failing build locally?

**Comment by adriaanm** [comment]
compiling with -Dlocker.skip=1 but without any changes to starr.number should do the trick

**Comment by adriaanm** [comment]
I think the sha to diff would be the original starr. Extracting library.properties from lib/scala-library.jar yields a non-existant sha...

```
version.number=2.10.0-20120919-182445-8e495bab82
maven.version.number=2.10.0-SNAPSHOT
osgi.version.number=2.10.0.v20120919-182445-8e495bab82
```

**Comment by adriaanm** [comment]
starr was last updated by d3095cbeb2, but javap'ing doesn't yield different signatures
I think Josh had a convincing explanation: it's the way we look for these methods that has changed incompatibly.

**Comment by adriaanm** [comment]
I verified that a build-opt produces identical contents for build/quick with current (never released) starr and when using 2.10.3

**Comment by som-snytt** [comment]
@retronym Actually, the guy on our right?  His left hand has six fingers.

**Comment by gkossakowski** [comment]
@adriaanm: what's the status of this PR?

I general, I think using the latest stable STARR for 2.10.x makes sense. I'm not entirely follow the failure you guys discussed. Was it real or caused by something unrelated to this pr?

**Comment by adriaanm** [comment]
The failure was caused by building SBT with a Scala that was built with starr (I.e, skipping locker). If you change starr to a more recent version of Scala, that works. Before this pr, the version of starr has a sha that doesn't even exist. It's 2.10.0-M7-....

**Comment by adriaanm** [comment]
Anyway, I think the pr is good to go

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
