### PR TITLE
Adds missing constructor on mutable.StringBuilder

### PR DESCRIPTION
**Pull request by Prithvirajbilla**
Fixes scala/bug#10991

### CODE REVIEW

**Review by julienrf — APPROVED** [review]
Thanks @Prithvirajbilla! Can you squash your commits?

**Comment by Prithvirajbilla** [comment]
squashed my commits. and resolved conflicts.

**Comment by nafg** [comment]
Hmm, should there be a bot that checks for serialization changes? (how would it do that?)

**Comment by NthPortal** [comment]
I'm pretty sure it's the constructor addition that breaks serialization, not the renaming.

@nafg that test is to check for serialization changes, and you update it (as long as you're not in a major release cycle) if you break serialization

**Comment by NthPortal** [comment]
incidentally, this PR also addresses scala/bug#10971 (though it's not in the commit message)

**Comment by nafg** [comment]
Should it have `@deprecatedName` in case someone used a named argument to the constructor?

**Comment by NthPortal** [comment]
This is actually just re-aligning with 2.12, where it was called `underlying`

**Pull request merged**
