### PR TITLE
easy way of writing not implemented macros

### PR DESCRIPTION
**Pull request by xeno-by**
Even though it's easy to mark regular method bodies as stubs (using ???),
there's no simple way of doing the same for macro methods. This patch
fixes the inconvenience.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @retronym

**Comment by xeno-by** [comment]
PLS REBUILD/pr-checkin-per-commit@36362bd

**Comment by xeno-by** [comment]
Hey how about this cute little PR for inclusion into 2.10.2? Makes our lives easier (better fast track), makes users' lives easier (can now write macro stubs), is consistent with pre-existing tradition + easy to review (essentially consists of three diffs of 3, 3 and 1 lines of code)

**Comment by xeno-by** [comment]
Hey! What's that? :(

```
Error downloading /home/jenkins/.sbt/cache/scala/43ce4e93168af8aed5354c9be8bd516413f214f9/lib/scala-compiler.jar: response code: 200
http://repo.typesafe.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/43ce4e93168af8aed5354c9be8bd516413f214f9/lib/scala-compiler.jar
```

**Comment by paulp** [comment]
> Hey! What's that? :(

Hard to believe you don't read scala-internals?

https://groups.google.com/forum/#!topic/scala-internals/zDMzX56oFT8
https://groups.google.com/forum/#!topic/scala-internals/uWPy5vslX1A

**Comment by xeno-by** [comment]
`response code: 200`

**Comment by paulp** [comment]
I agree it's a little weird to be failing on a 200, but I guess it comes naturally to group this with the other artifact-downloading failures now plaguing us.

**Comment by soc** [comment]
LGTM.

**Comment by adriaanm** [comment]
PLS REBUILD ALL
NOLITTER!

**Comment by retronym** [comment]
PLS REBUILD ALL
NOLITTER!

**Comment by retronym** [comment]
LGTM

**Comment by xeno-by** [comment]
Can we still have this in 2.10.2?

**Comment by xeno-by** [comment]
I removed the starr part from the pull request (which will be resubmitted into master), so everything's green now. Please please can we merge?

**Pull request merged**
