### PR TITLE
Cleanup tools.cmd, by moving most to partest

### PR DESCRIPTION
**Pull request by dwijnand**
This pull request is an idea to gather comments, as looks pretty niche, but at the same time I know it's also used by MiMa:

https://github.com/lightbend/migration-manager/blob/0.2.0/reporter/src/main/scala/com/typesafe/tools/mima/cli/Main.scala

WDYT should be done with this code?

### CODE REVIEW

**Comment by som-snytt** [comment]
What to do with `cmd`? Paulp liked it; I took a look once to polish it; but I concluded it was a bit over the top. I liked the idea of the DSL, but I recall snags around Spec vs Instance or whatever. I forget what I came up with, except that I called it "paulptional". soc installed it in partest, but partest is switching to sbt-only, so that ought not extend its life.

**Comment by dwijnand** [comment]
Now that you mention it MiMa is sbt-only these days too. Or does scala/scala still invoke MiMa via it's command-line interface?

I think what should be done is remove the usage of tools.cmd in partest and MiMa, and then it can all go. Even DemoSpec, as I don't think it's fair to call it a test for https://github.com/scala/bug/issues/7591.

**Comment by som-snytt** [comment]
soc wrote that issue, too.

I think there is a need to parse command lines, but I'm not sure where, off the cuff. Tell me again when the Dark Ages will pass and our progeny will tell their progeny how they used to try to get words expressing commands into the computer.

**Comment by dwijnand** [comment]
> remove the usage of tools.cmd in partest and MiMa

https://github.com/lightbend/migration-manager/pull/208

**Comment by SethTisue** [comment]
what happened here, why was this closed?

**Comment by dwijnand** [comment]
I thought it was best to first remoe the usages of tools.cmd both in mima and partest, instead of this move proposal.

**Comment by SethTisue** [comment]
ah okay. well the MiMa thing happened and partest is re-in-sourced, so feel free to take it on now :-)

**Comment by dwijnand** [comment]
Now I remember: partest's usage of tools.cmd is pretty hard-core (unlike mima's).

So.. maybe instead of "remove" we should go back to "move". Go go gadget re-open.

**Comment by dwijnand** [comment]
@som-snytt WDYT?

**Comment by som-snytt** [comment]
I haven't used CLI partest in a very long time now, so I would support just dropping the feature.  I remember it was necessary to run it as `test/partest` FSR...

**Comment by dwijnand** [comment]
I'll look to dropping the main part. But IIRC most of the use of tools.cmd is used by the sbt plugin too, for option parsing etc.

**Comment by lrytz** [comment]
Looks good to me, @SethTisue passing on to you :)

**Comment by dwijnand** [comment]
Issue status summary:

* most of scala.tools.cmd has been removed from the library
* most of it has survived by being repackaged into partest
* `PropertyMapper`/`Property` now live on only in `pos/t7591` alongside `DemoSpec` (for the rest of cmd.tools, t7591 works because it depends on partest and thus the repackaged code) 
* the CLI of partest (ConsoleRunner) was culled
* the use of scala.tools.cmd in mima has been culled

**Comment by dwijnand** [comment]
Merge conflicts with https://github.com/scala/scala/pull/6538, so rebased.

Review by @som-snytt, perhaps?

**Comment by som-snytt** [comment]
I'll give it :eyes: soon.

**Comment by dwijnand** [comment]
This change shouldn't hold back the 2.13.0-M5 milestone, and closing it is one way to do that.

If this change is of interest I'd be happy to take and respond to feedback in order to land this change.

**Comment by som-snytt** [comment]
Sorry, I had a busy weekend IRL.

**Comment by dwijnand** [comment]
That's OK. Feedback still very welcome.

**Comment by SethTisue** [comment]
@dwijnand @som-snytt interested in reviving this?

**Comment by som-snytt** [comment]
Sorry, I'm lame. No, literally! I had to hike five miles on the hottest day of the year with no gear! One way! It has left me lame. I'll limp toward a review.

**Comment by dwijnand** [comment]
@SethTisue What's your take on this change?

**Comment by som-snytt** [comment]
FTR, another hot weekend. 

I just noticed an improvement (file.setExecutable) worth improving https://github.com/scala/scala/compare/2.13.x...som-snytt:improve/file-setexec

but it's only used by tools.cmd. LOC are technical debt!

**Comment by som-snytt** [comment]
A subsequent PR can mv the parser to nsc.util.

Oh, I can't reopen because the branch has been zapped! Poor branch!

**Comment by som-snytt** [comment]
A subsequent PR can add the sbt tool for updating the parser under project, from settings, then migrate partest to use settings.

**Comment by SethTisue** [comment]
> I can't reopen because the branch has been zapped! Poor branch!

Dale the Branch Zapper strikes again. he's notorious!

nonetheless, `hub checkout https://github.com/scala/scala/pull/6639` summoned the commits out of some occult alternate dimension

rebased and resubmitted at #7804

**Pull request closed without merging**
