### PR TITLE
patmat tweaks: compiler performance, better error on unsupported pattern

### PR DESCRIPTION
**Pull request by adriaanm**
(rework of #1112)
- do not catch StackOverflowError: @gkossakowski diagnosed it to be killing compiler performance
  --> limit recursion depth in negationNormalForm in the same way we were already harnessing conjunctiveNormalForm -- configurable using -Dscalac.patmat.analysisBudget=N (N=256 by default)
- Roland reported hitting the unsupported pattern branch in translatePattern in akka code, so providing some diagnostics and a nicer error message to figure out what's going on

review by @gkossakowski (/cc @paulp)

### CODE REVIEW

**Comment by gkossakowski** [comment]
Apart from cleaning up things LGTM.

I think 256 recursion depth should be more than enough. I'd be very worried if we have formulas with more than 256 levels of nesting.

**Comment by adriaanm** [comment]
damn, forgot to push -f -- I already had a version without `AnalysisBudget.stackOverflow`

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
I'd say the formulae can get pretty big without cause for concern -- I have a prototype version that uses Sat4J for solving, where 10K formulae is routine. The main cost is my naive NNF/CNF transform. Should use a more efficient approach, but that requires more substantial rewrites to how the formulae are  constructed during the analyses. Will work on this for 2.10.1.

**Comment by gkossakowski** [comment]
I know it can get big in length but I'd be surprised if it gets very deeply nested. Or does it?

**Comment by adriaanm** [comment]
alternatives tend to blow up -- so does the encoding of the subtyping relation into binary proposition logic, especially when sealed classes are involved

**Comment by gkossakowski** [comment]
I see. Since you can customize this with an option then I think we are fine with default nesting limit.

I see you pushed cleaned up commit. LGTM.

**Pull request merged**
