### PR TITLE
SI-1503 don't assume unsound type for ident/literal patterns

### PR DESCRIPTION
**Pull request by adriaanm**
What type should a variable bound to the value matched by a pattern have?
To avoid CCEs, it should be a type that's implied by the matching
semantics of the pattern.

Usually, the type implied by a pattern matching a certain value
is the pattern's type, because pattern matching implies instance-of checks.

However, Stable Identifier and Literal patterns are matched using `==`,
which does not imply a type for the binder that binds the matched value.

The change in type checking due to this fix is that programs that used to crash with a CCE
(because we blindly cast to the type of the pattern, which a `==` check does not imply)
now get a weaker type instead (and no cast). They may still type check, or they may not.

To compensate for this fix, change `case x@Foo => x` to `case x: Foo.type => x`,
if it's important that `x` have type `Foo.type`.

NOTE: once  is fixed, matching of singleton type patterns will use `eq`,
not `==` (so that the types are not a lie).

See also: 

Review by @retronym

### CODE REVIEW

**Comment by adriaanm** [comment]
I'll see about adding some tests once the current test suite passes :)

**Comment by paulp** [comment]
Boy, if the current suite passes with no changes, something something.

**Comment by adriaanm** [comment]
Note that I'm opening this pr to start a discussion. I want to either merge a solution or mark the ticket won't fix by RC1. Happy to develop some heuristic to aid migration. I feel we should live up to the promise of static typing and not let these looming CCE sleep, though.

**Comment by adriaanm** [comment]
More coming, of course. I'll also endeavor to build the core ecosystem.

**Comment by adriaanm** [comment]
conservative wip: https://github.com/adriaanm/scala/compare/t1503-wip

**Comment by adriaanm** [comment]
Will reopen once I figure out how to only warn when it matters.

**Pull request closed without merging**
