### PR TITLE
Define Type.isLess and use it for computing LUBs

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Comment by SethTisue** [comment]
the failed test: https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/15844/testReport/scala.reflect.internal/TypesTest/testRefinedLubs/

```scala
    assertEquals(typeOf[Option[AnyVal]], lub(typeOf[Option[Int] with Option[Char]] :: typeOf[Option[Boolean] with Option[Short]] :: Nil))
```

**Comment by SethTisue** [comment]
@joroKr21 interested in taking a second look at this?

**Comment by joroKr21** [comment]
I don't know what goes wrong. The code around that uses `isLess` is too complicated to grok, even though `isLess` itself is straightforward.

**Comment by SethTisue** [comment]
closing for inactivity, but it's perfectly fine to reopen if activity resumes.

**Pull request closed without merging**
