### PR TITLE
Avoid partition in case equals synthesis

### PR DESCRIPTION
**Pull request by som-snytt**
Micro-optimise in the fine tradition that has been established here.

I thought I would prefer the second version:
```
val usefulEquals  = resultType != NothingTpe && resultType != NullTpe && resultType != UnitTpe
val usefulEquals  = resultType match { case NothingTpe | NullTpe | UnitTpe => false case _ => true }
```

Todo scala/bug#10536
Todo scala/bug#10539

### CODE REVIEW

**Comment by som-snytt** [comment]
:notes: Little boxes, on the hillside, little boxes made of ticky tacky... :notes:

**Comment by som-snytt** [comment]
Actually, it's happy to work with overloads of `==`, so the best you can do is fail correctly.

**Review by lrytz — APPROVED** [review]
LGTM, but how did you end up here...?

**Comment by som-snytt** [comment]
@lrytz I ask myself that every day. I have no idea what I was doing a month ago.

I do know that the super call ticket led me to look at a few issues.

What did I mean with those todos? I bet Diego got me on an optimization kick. Why did I erase the title "ensure equals equals equals"? That might be the best thing I've ever written.

**Pull request merged**
