### PR TITLE
A wrapper for selecting tests for partest.

### PR DESCRIPTION
**Pull request by paulp**
"partest-ack", just what it sounds like.

% tools/partest-ack
Usage: tools/partest-ack <regex> [ack options]

Given a regular expression (and optionally, any arguments accepted
by ack) runs all the tests for which any associated file matches
the regex. Associated files include .check and .flags files. Tests
in directories will match if any file matches. A file can match the
regex by its contents or by its name.

You must have ack installed:
  http://betterthangrep.com/ack-standalone

Examples:

  % tools/partest-ack monad
  Found 4 tests matching 'ack monad'

  Testing individual files
  testing: [...]/files/pos/tcpoly_boundedmonad.scala   [  OK  ]
  testing: [...]/files/pos/tcpoly_ticket2096.scala     [  OK  ]
  testing: [...]/files/run/tcpoly_monads.scala         [  OK  ]
  testing: [...]/files/presentation/callcc-interpreter [  OK  ]

  % tools/partest-ack monad -i  # -i == ignore case
  Found 12 tests matching 'ack monad -i'

  Testing individual files
  [etc]

### CODE REVIEW

**Comment by paulp** [comment]
Review by, oh, @jsuereth.

**Comment by retronym** [comment]
Wonderful! The only thing missing is the ability to pass options to partest.

Either of these would do, I'd probably go for the second to keep the script simple.

```
tools/parttest-ack monad -i -- --update-check --show-log
PARTEST_OPTS="--update-check --show-log" tools/partest-ack monad -i
```

**Comment by gkossakowski** [comment]
So how is this different from `./partest --grep` ?

**Comment by retronym** [comment]
I can field that one: it matches on file names in addition to file content, and supports all the options of `ack`.

**Comment by jsuereth** [comment]
+1 to @retronym's comments.  That can be a follow on.  Otherwise LGTM

**Comment by paulp** [comment]
OK, let me come back to it, as that's a ways from the most pressing thing I've got going.

**Pull request merged**
