### PR TITLE
SI-7020 Deterministic warnings for pattern matcher, take 2

### PR DESCRIPTION
**Pull request by retronym**
The previous swing at determinism, ebb01e05cbe4, made decent contact but
apparently didn't hit it out of the park. The test wavered every hundred or so
runs, as witnessed occasionally in nightly builds or pull request validation.

I setup a test to run neg/7020.scala a few hundred times, and could trigger
the failure reliably.

I then swept through the pattern matcher in search of HashMap and HashSet
creation, and changed them all to the Linked variety. The results of that are
published in retronym#ticket/7020-3 [1].

This commit represents the careful whittling down of that patch to the minimal
change required to exhibit determinism.

[1] https://github.com/retronym/scala/compare/ticket/7020-3

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
Awesome!!! /cc @gbasler --> this was probably the last missing piece for integrating part of https://github.com/adriaanm/scala/tree/patmat-tseitin-2.10-wip (should go to master now)

**Comment by adriaanm** [comment]
LGTM

**Comment by adriaanm** [comment]
Looks like you had an improvement to counter example pruning that didn't make it into this PR?

**Comment by retronym** [comment]
Looks like a whittled a bit too far. Just force pushed a change to make `type Model = SortedMap[Sym, Boolean]`

```
% for i in {1..100}; do (qbin/scalac test/files/neg/t7020.scala -Xfatal-warnings 2>&1) > sandbox/log.txt; (diff sandbox/log.txt sandbox/reference.txt && printf ".") || break; done;
....................................................................................................
```

**Comment by gbasler** [comment]
Excellent work!! I hope this was the last blocker for that branch.

**Pull request merged**
