### PR TITLE
Fixes scala/bug#10864

### PR DESCRIPTION
**Pull request by kamil-duda**
Fix doc error

### CODE REVIEW

**Review by hrhino — DISMISSED** [review]
There's also a reference in the doc comments to `type TypecheckMode` which you could change, as well.

**Comment by hrhino** [comment]
Also, if you want, this can be retargeted to the `2.12.x` branch so it will show up in the docs for 2.12.7 and later version in the 2.12 series.

**Comment by kamil-duda** [comment]
Thanks for pointing that out, made changes.
In order to retarget to `2.12.x` should I close this pull request and create a new one?

**Comment by hrhino** [comment]
Nope! Do you know how `git rebase` works? You can do

```bash
git rebase --onto 2.12.x issue/10864~2 issue/10864
git push --force-with-lease
```

and you should be able to change the target of this PR to `2.12.x` safely.

**Comment by SethTisue** [comment]
please squash into a single commit, and we'll merge.

not sure why the "combined" check is confused.

**Comment by SethTisue** [comment]
we're working on the Jenkins breakage.

**Comment by SethTisue** [comment]
hmm so Jenkins is back up, but Scabot isn't actually triggering jobs. we'll keep on it

**Comment by kamil-duda** [comment]
Can we merge this?

**Comment by SethTisue** [comment]
thanks @kamilduda, and welcome! sorry 'bout the CI troubles

**Pull request merged**
