### PR TITLE
Fix 2.13-only bug in Java collection converters that caused some operations to perform an extra pass

### LINKED ISSUE #11976: Regression in asScala methods for maps in 2.13
## reproduction steps

```scala
import collection.JavaConverters._

val myMap_1 = java.util.Collections.singletonMap("a", 1)
myMap_1.asScala.partition { case (key, value) =>
     println(key, value)
     true
}

val myMap_2 = Map("a" -> 1)
myMap_2.partition { case (key, value) =>
     println(key, value)
     true
}
```

## problem

Starting 2.13, the behavior for `asScala` methods for Java maps seems to have changed. When using the `partition` method with a Java map, the map is iterated twice as opposed to just once when using a Scala map.

```scala
// Using Scala 2.13
scala> import collection.JavaConverters._
import collection.JavaConverters._

scala> val myMap_1 = java.util.Collections.singletonMap("a", 1)
     | myMap_1.asScala.partition { case (key, value) =>
     |      println(key, value)
     |      true
     | }
       myMap_1.asScala.partition { case (key, value) =>
       ^
On line 2: warning: object JavaConverters in package collection is deprecated (since 2.13.0): Use `scala.jdk.CollectionConverters` instead
(a,1)
(a,1)
val myMap_1: java.util.Map[String,Int] = {a=1}
val res3: (scala.collection.mutable.Map[String,Int], scala.collection.mutable.Map[String,Int]) = (HashMap(a -> 1),HashMap())

scala> val myMap_2 = Map("a" -> 1)
     | myMap_2.partition { case (key, value) =>
     |      println(key, value)
     |      true
     | }
(a,1)
val myMap_2: scala.collection.immutable.Map[String,Int] = Map(a -> 1)
val res4: (scala.collection.immutable.Map[String,Int], scala.collection.immutable.Map[String,Int]) = (Map(a -> 1),Map())
```

## expectation
This is a regression from 2.12 where the Java map is iterated exactly once.

### PR DESCRIPTION
**Pull request by lrytz**
Fixes https://github.com/scala/bug/issues/11976

Quite a bunch of MiMa exceptions here...

### CODE REVIEW

**Comment by som-snytt** [comment]
`xkcd converters`.

**Comment by SethTisue** [comment]
If we can get this reviewed & merged within the next 1-2 days great, otherwise let's push it to 2.13.4.

**Comment by lrytz** [comment]
@retronym gave me an informal OK, so maybe he can do the formal one too :-)

**Comment by ijuma** [comment]
We use these adapters quite a bit in Apache Kafka, so it would be nice to get the fix. We have recently switched to Scala 2.13 as the default Scala version.

**Review by retronym — APPROVED** [review]

**Pull request merged**
