### PR TITLE
SI-4287 Corrected range positions for constructor's default arguments

### PR DESCRIPTION
**Pull request by dotta**
- First commit demonstrates the problem.
- Second commit fixes it.

review by @retronym

I would like this to be backported to 2.10.x. However, because this patch cannot be cleanly applied to 2.10.x, it would be convenient if we could first merge it in master, and then I'll take care of the backport.

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

Second opinion please by @densh

One minor point: could you limit your commit subject to 65 chars? It makes life easier for release notes and browsing git logs

``` diff
-SI-4827 Test to demonstrate wrong positions assigned to constructor's default arg
+SI-4827 Test to demonstrate wrong position of constructor default arg
```

**Comment by dotta** [comment]
> One minor point: could you limit your commit subject to 65 chars? It makes life easier for release notes and browsing git logs

Sure thing. If that is a general policy, could you guys add it to your [CONTRIBUTING](https://github.com/scala/scala/blob/master/CONTRIBUTING.md) doc (if it's already there, then I'm sorry I missed it).

**Comment by retronym** [comment]
> Following the single line description (ideally no more than 70 characters long) should be a blank line followed by an enumerated list with the details of the commit.

I was being a bit stingy.

**Comment by retronym** [comment]
```
  jvm > t5603-run.log
% diff /localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/t5603-run.log /localhome/jenkins/b/workspace/pr-scala-test/scala/test/files/run/t5603.check
@@ -9,11 +9,11 @@
   };
   [87:209]class C extends [94:209][151:159]Greeting {
     [119:139]val nameElse = _;
-    <95:101><paramaccessor> private[this] val i: <98:101>Int = _;
-    <95:139>def <init>([95:101]i: [98:101]Int) = <95:139>{
+    [95:101]<paramaccessor> private[this] val i: [98:101]Int = _;
+    <119:139>def <init>([95]i: [98]Int) = <119:139>{
       <119:139>val nameElse = <134:139>"Bob";
       [NoPosition][NoPosition][NoPosition]super.<init>();
-      <95:139>()
+      [94]()
     };
     [168:184]val name = [179:184]"avc";
     [191:203][191:198]println([199:202]msg)

```

**Comment by dotta** [comment]
So, only the title should be no more than 70 characters. Or, should I make sure the whole message is line wrapped at 70 characters?

**Comment by retronym** [comment]
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

(But we allow 70 in the title)

**Comment by densh** [comment]
LGTM. 

Every time I look at range position handling code I wonder if it would be a good idea to write a simple tool that would visualize connections between trees and positions better. i.e. UI with code on the left and trees on the right; hovering over a tree highlights appropriate region of text in the code.

**Comment by dotta** [comment]
@retronym I just run the whole partest suite on my machine and didn't get any failure, I'm confused.

```
15:59 mirco@Mircos-iMac /Users/mirco/Projects/ide/scala
% ./test/partest
...
3607/3607 passed (elapsed time: 00:35:36)
Test Run PASSED
```

**Comment by densh** [comment]
@dotta You've got failures in rangepos build. To simulate it locally you need to add -Yrangepos flag to build.xml:

```
<property name="scalac.args.always"    value="-feature -Yrangepos" />
```

Or alternatively launch ant with some extra params:

```
$ ant -Dscalac.args="-Yrangepos" -Dpartest.scalac_opts="-Yrangepos" build
```

**Comment by retronym** [comment]
or, individually

```
SCALAC_OPTS=-Yrange-pos ./test/partest path/to/test
```

**Comment by dotta** [comment]
Actually, the failure happens while compiling the scala library. I see the following in the log output:

```
[quick.library] Compiling 589 files to /localhome/jenkins/c/workspace/pr-scala-rangepos/scala/build/quick/classes/library
[quick.library] ======= Position error
[quick.library] Overlapping trees (108896,109260)
[quick.library] == Ancestor tree [109266] of type Template at [4749:7105]PagedSeq.scala
...
```

Am I right to think that this is failing while compiling `PagedSeq.scala`? Or may it be that the failure is caused by some other source file?

**Comment by dotta** [comment]
Ok, I could reproduce it, working on fixing it now.

**Comment by dotta** [comment]
I'm closing this as it needs more working. Will re-open it when it's ready.

**Comment by adriaanm** [comment]
Keeping this open so we know which PRs must be merged before we can release

**Comment by adriaanm** [comment]
Oh, actually this is the one for master. Was thinking it's 2.10.x

**Pull request closed without merging**
