### PR TITLE
Correct bounds for higher-kinded GADT skolems

### LINKED ISSUE #11692: "error during expansion of this match (this is a scalac bug)" error since Scala 2.13
How to reproduce

```
git clone https://github.com/scalaz/scalaz-deriving.git --branch maybe-scala-compiler-bug
cd scalaz-deriving
sbt compile
```

- https://github.com/scalaz/scalaz-deriving/commit/36946459b2fbe7c6a3819484fd8d37fe0c29a6be

build log

```
[error] /home/travis/build/scalaz/scalaz-deriving/scalaz-deriving/src/main/scala/scalaz/Deriving.scala:106:35: error during expansion of this match (this is a scalac bug).
[error] The underlying error was: type mismatch;
[error]  found   : x4._1.type (with underlying type <unapply-selector>.T)
[error]  required: x1.T
[error]       (g(z1), g(z2)).zip(tcs).all {
[error]                                   ^
[error] one error found
[error] (deriving / Compile / compileIncremental) Compilation failed
```

- https://travis-ci.org/scalaz/scalaz-deriving/builds/573382149
- https://travis-ci.org/scalaz/scalaz-deriving/jobs/573382151#L1911-L1918

travis-ci

compile success with Scala 2.12.8, 2.12.9 but fail with Scala 2.13.0.

(avoid `/~\.unapply` when support Scala 2.13 😢  https://github.com/scalaz/scalaz-deriving/commit/2b88b2965d2a6e3256ad67bfd70b5173f462de98#diff-da428bb5fa409a907cd8911128e9610aR106 )

### LINKED ISSUE #12295: error during expansion of this match (this is a scalac bug) on covariant type constructors
## reproduction steps

Using Scala 2.x (e.g. 2.11, 2.12, .2.13), not reproducible on Dotty M3.
Compile the following snippet:
```scala
object App {

  def main(xs: Array[String]) = ()
  
  def err[F[_]]: Unit = {

    sealed trait Foo[+A] // sealed or not doesn't matter
    case class ImplA[A](a: A) extends Foo[A]
    case class ImplAny[A](a: Any) extends Foo[A]

    trait Bar[+G[_]] // must be covariant 

    val x: Foo[Foo[Bar[F]]] = ???

    x match {
      case ImplAny(ImplAny(_)) => ??? // ok
      case ImplAny(ImplA(_))   => ??? // ok
      case ImplA(_)            => ??? // ok
      case ImplAny(_)          => ??? // ok
      case _                   => ???
    }

    x match {

      // error during expansion of this match (this is a scalac bug).
      case ImplA(ImplA(_)) => ???

      // error during expansion of this match (this is a scalac bug).
      case ImplA(ImplAny(_)) => ???

      // error during expansion of this match (this is a scalac bug).
      case ImplA(y) => y.toString

      // error during expansion of this match (this is a scalac bug).
      case ImplA(y) =>
        y match {
          case ImplA(_) => ???
          case _        => ???
        }

      // can't existentially abstract over parameterized type, ok
      // case ImplA(y) => y
      case _ => ???
    }
    ()
  }
}
```
Demo at https://scastie.scala-lang.org/tom91136/BSpEJgLrT7iKs6ofm6JAdw 

## problem

On Scala 2.x, the compiler reports something like:
```
error during expansion of this match (this is a scalac bug).
The underlying error was: type mismatch;
 found   : Foo[Bar[?F5]] where type ?F5 <: F (this is a GADT skolem)
 required: Foo[Bar[F]]
```
This occurs for all variants of the pattern as shown in the snippet.
Code compiles fine on Dotty M3.

The bug was discovered while attempting something loosely like the following which isn't even all that uncommon (!?):
```scala
sealed trait DecodeResult[+A] // something from circe/sttp
class Stream[+F[_], A] // something from fs2
val x : DecodeResult[Either[String, Stream[F, String]]] = ???
x match {
  case Success(Right(x)) => // touch x and it explodes
  ...
}
```

### PR DESCRIPTION
**Pull request by joroKr21**
Fixes scala/bug#12295
@xuwei-k can you check if this fixes scala/bug#11692?

### CODE REVIEW

**Comment by diesalbla** [comment]
Is there a way to try this out before the binary release `2.13.5`?  In `fs2` we have quite a few "work-arounds" to avoid compiler's bugs with pattern-matching Higher-Kinded covariant types. That could be quite a testbed.

**Comment by joroKr21** [comment]
It's described here: https://github.com/scala/scala#scala-ci

> You can use Scala builds in the validation repository locally by adding a resolver and specifying the corresponding scalaVersion:

```
$ sbt
> set resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
> set scalaVersion := "2.12.2-bin-abcd123-SNAPSHOT"
> console
```

So this one: https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.13.5-bin-69b04d1-SNAPSHOT/

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2344/

**Comment by SethTisue** [comment]
@xuwei-k have you had a chance yet to consider @joroKr21's question?

**Comment by SethTisue** [comment]
@diesalbla agree that sounds like a good testbed – let us know if you're able to try it

**Comment by dwijnand** [comment]
@joroKr21 so, knowing next to nothing about these parts of the compiler, how come in one case you genPolyType and then apply it and in the other case just genPolyType?

**Comment by joroKr21** [comment]
> In fs2 we have quite a few "work-arounds" to avoid compiler's bugs with pattern-matching Higher-Kinded covariant types.

@diesalbla, just by looking at source code of fs2 I'm not able to find the workarounds you mentioned.
Someone more familiar with the code base might have more success.

@SethTisue awesome, thank you 🙏 
> @xuwei-k have you had a chance yet to consider @joroKr21's question?

Actually if the branch with the reproduction is still there, I can check that too. 

> knowing next to nothing about these parts of the compiler, how come in one case you genPolyType and then apply it and in the other case just genPolyType?

@dwijnand good question, I want to try something and get back to you

**Comment by diesalbla** [comment]
> @diesalbla, just by looking at source code of fs2 I'm not able to find the workarounds you mentioned.
Someone more familiar with the code base might have more success.

Mostly on the `develop` branch, not the `main` branch. Several extra type variables and `asInstanceOf` conversions... https://github.com/typelevel/fs2/blob/develop/core/shared/src/main/scala/fs2/Pull.scala#L938-L992

I refer to having to use extra variables for the types and a few `asInstanceOf` conversions... and sometimes we get a Kinding errors, if it infers that the new type variable has kind `*` where it should have inferred `[_]`...

Will try to report on specific errors (or minimise that code), but don't let that delay you from merging this one 🙂

**Comment by joroKr21** [comment]
@dwijnand to build some intuition about how types work I like to fiddle with the console in `:power` mode:
```scala
class Foo[F[x] <: Seq[x]]
val f = symbolOf[Foo[List]].typeParams.head
```

Here are some interesting things you can try:

| Expression | Result | getClass | Explanation |
|-|-|-|-|
| `f.tpe` | `F[x]` | `TypeRef` | Same as `tpe_*` - applied to dummy args if higher-kinded |
| `f.tpeHK` | `F` | `TypeRef` | Unlike `tpe` and `tpe_*` - preserves the kind |
| `f.info` | `[x] <: Seq[x]` | `PolyType` | For a HKT parameter this is params -> bounds |
| `f.tpe.bounds` | ` <: Seq[x]` | `TypeBounds` | Unsurprisingly, the dummy args carry under |
| `f.tpeHK.bounds` | ` <: Seq[x]` | `TypeBounds` | ❌ Bad (until now) - kind is lost |
| `f.tpeHK.bounds` | ` <: [x]Seq[x]` | `TypeBounds` | ✅ Ok (this branch) - kind carries under |
| `f.info.bounds` | ` <: [x]Seq[x]` | `TypeBounds` | Kind carries under `PolyType` |
| `f.tpe.lowerBound` | `Nothing`  | `TypeRef` | |
| `f.tpe.upperBound` | `Seq[x]` | `TypeRef` | |
| `f.tpeHK.lowerBound` | `Nothing`  | `TypeRef` | ❌ Bad (until now) - kind is lost |
| `f.tpeHK.lowerBound` | `[x]Nothing`  | `PolyType` | ✅ Ok (this branch) - kind carries under |
| `f.tpeHK.upperBound` | `Seq[x]`  | `TypeRef` | ❌ Bad (until now) - kind is lost |
| `f.tpeHK.upperBound` | `[x]Seq[x]`  | `PolyType` | ✅ Ok (this branch) - kind carries under |
| `f.info.lowerBound` | `[x]Nothing`  | `PolyType` | Kind carries under `PolyType` |
| `f.info.upperBound` | `[x]Seq[x]`  | `PolyType` | Kind carries under `PolyType` |

Things to note:
 * `TypeRef` of a HKT without type arguments should be equivalent to its eta-expansion (a `PolyType`):
 i.e. `f` should be equivalent to `f.etaExpand` (in types: `F =:= [x]F[x]`)
 * Taking the bounds of equivalent types should yield equivalent bounds
 * We also learned that the kind carries under `PolyType` when we take its bounds.
 Therefore the type should also carry under `f.tpeHK` - thus the `relativeInfo` change.
 * `.bounds` return `TypeBounds` - but they are not suitable as the `info` of a higher-kinded type symbol.
 For example `f.info.bounds` return `TypeBounds` with `PolyType`s as `lo` and `hi`.
 Therefore we need to use `PolyType` to construct the `info` of a higher-kinded GADT skolem.

Sorry if that is too long, it helped me to do this systematically.

**Comment by joroKr21** [comment]
> TypeRef of a HKT without type arguments should be equivalent to its eta-expansion (a PolyType):
i.e. f should be equivalent to f.etaExpand (in types: F =:= [x]F[x])

case in point: lampepfl/dotty#9566

**Comment by dwijnand** [comment]
> Sorry if that is too long, it helped me to do this systematically.

Not at all - it was very helpful, thank you.

**Comment by dwijnand** [comment]
> queued: [scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2344](https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2344/)

Seth aborted that (I assume b/c of the disk space issues) and rescheduled it as https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2346/ (and it's still not finished, 5 hours in).

But that's using the previous SHA, we need a run for the cd13abc: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2348/ (404 link until the build starts).

**Review by dwijnand — APPROVED** [review]
LGTM from my point of view, hopefully the community build comes back clean.

**Review by diesalbla — APPROVED** [review]

**Comment by diesalbla** [comment]
Let's go ahead to the next phase. If something fails we can revert later on.

**Comment by dwijnand** [comment]
I would have preferred to wait for the confirmation first, that's what I implied.  I wish GitHub's review had a task completion system...  Perhaps I should approve less readily to avoid miscommunicating.

**Comment by SethTisue** [comment]
The failures in 2346 are known-intermittent, so it's a "green enough" run.

2348 is still running.

**Comment by joroKr21** [comment]
> @xuwei-k can you check if this fixes scala/bug#11692?

I checked that and it works btw 🎉

**Pull request merged**
