### PR TITLE
REPL: handle `.inputrc`

### LINKED ISSUE #12269: JLine 3: handle `.inputrc`?
at https://github.com/scala/scala/pull/8036#discussion_r317896657 , @retronym wrote:

> In our usage of JLine2, we picked up configuration from `~/.inputrc` [etc](https://github.com/jline/jline2/blob/12b98d94589e3bd6a60719c495b0ab911c571329/src/main/java/jline/console/ConsoleReader.java#L290-L306).

> JLine3 does have support for parsing this file since https://github.com/jline/jline3/commit/9ccfe0b121d2ea72a8524c84a9bda5abaa68d45a, but it looks like we need to [call `InputRC.configure`](https://github.com/jline/jline3/commit/9ccfe0b121d2ea72a8524c84a9bda5abaa68d45a#diff-b26d899b1659f142e858937634634a4bR56) after determining which config file to use ourselves.

> Furthermore, in the current configuration file, sections guarded with `$if JLine .... $endif` are interpreted by the Scala REPL. Under this change, config would need to be moved to `$if scala` (the `appname` used here. That's probably fine if release noted.

> Here's my `.inputrc` for reference.

```
$if Bash
	"\e[A": history-search-backward
	"\e[B": history-search-forward
    Space: magic-space
$endif

#set blink-matching-paren on
"\C-xq": "\eb\"\ef\""

"\C-x)": "\ea\(\ee\)"

$if JLine
	"\C-xu": "import scala.tools.reflect.ToolBox; val m = scala.reflect.runtime.currentMirror; val u = m.universe; import u._; val tb = m.mkToolBox()"
	"\C-x)": "\C-a(\C-e)"
	"\C-x}": "\C-a{\C-e}"
	"\C-x{": "{}\C-b"
	"\C-x(": "()\C-b"

$endif
```

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
Fixes scala/bug#12269

### CODE REVIEW

**Comment by SethTisue** [comment]
This is causing our OSGi tests to fail.

```
org.osgi.framework.BundleException: Unable to resolve org.scala-lang.scala-compiler [14](R 14.0): missing requirement [org.scala-lang.scala-compiler [14](R 14.0)] osgi.wiring.package; (osgi.wiring.package=org.jline.builtins) Unresolved requirements: [[org.scala-lang.scala-compiler [14](R 14.0)] osgi.wiring.package; (osgi.wiring.package=org.jline.builtins)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
```

Note that both Travis-CI and Jenkins are failing in the same way, and the failures are reproducible locally (with `osgiTestFelix/test` and `osgiTestEclipse/test`).

The clue seems to be `osgi.wiring.package; (osgi.wiring.package=org.jline.builtins)` — this PR adds `import org.jline.builtins.InputRC`

@jxnu-liguobin I have no real understanding of this stuff, but my guess is that what you need to do is add an `org.jline.builtins` entry to `Osgi.headers` in our `build.sbt`. Can you give that a try?

**Comment by SethTisue** [comment]
Also while I'm here I just want to thank you for all these great PRs you're sending. You're on fire! 🔥

**Comment by jxnu-liguobin** [comment]
@SethTisue I add it, but combined still failed, do I need attention?
btw, Thank you for your approval. I like Scala very much. I will continue.

**Comment by SethTisue** [comment]
> @SethTisue I add it, but combined still failed, do I need attention?

the scala/scala repo has an especially strict CI policy: _every_ commit in a PR must be green, not just the last one. that's what "combined" is checking. So the problem will go away when you squash this into fewer commits.

> btw, Thank you for your approval. I like Scala very much. I will continue.

❤️

**Comment by SethTisue** [comment]
@retronym hey `.inputrc` guy — want to take this for a spin?

**Comment by SethTisue** [comment]
merged, but maybe there's somebody out there who would like to try a nightly and make sure it works on Windows?

**Pull request merged**
