### PR TITLE
SI-7134: don't require doc.Settings in base api of scaladoc.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @VladUreche.

**Comment by VladUreche** [comment]
LGTM. So, IIUC, you'll stop using scaladoc settings for the presentation compiler and this should fix the sourcepath issue, right?

**Comment by VladUreche** [comment]
Great, it's better than all other solutions! Thanks Eugene! :+1: 
So, LGTM!

**Comment by dragos** [comment]
LGTM

**Pull request merged**
