### PR TITLE
SI-8129 Plug a leak in perRunCaches

### PR DESCRIPTION
**Pull request by retronym**
I guess we've never leaned to heavily on these, because the
registry of caches was forgetting about most of them
immediately if they compared == at the point of creation.

Consequently, maps like `treatedInfos` in Mixin were holding
onto old types and symbols and leaking memory.

You can reproduce the leak with:

```
(for i in {1..200}; do echo src/library/scala/collection/*.scala; done; printf "\n") | scalac-hash v2.11.0-M7 -J-Xmx256M -Xresident

nsc> warning: there were 6 deprecation warning(s); re-run with -deprecation for details

(... 15 times)

nsc> java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid90362.hprof ...
Heap dump file created [340635728 bytes in 7.993 secs]
^CException in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Review by @gkossakowski

### CODE REVIEW

**Comment by gkossakowski** [comment]
Huh, the test failure looks legit:

```
% diff /localhome/jenkins/c/workspace/pr-scala-test/scala/test/files/run/tpeCache-tyconCache-run.log /localhome/jenkins/c/workspace/pr-scala-test/scala/test/files/run/tpeCache-tyconCache.check
@@ -11,9 +11,9 @@ scala> :power
 scala> 

 scala> AnyRefClass.tpe eq AnyRefClass.typeConstructor
-res0: Boolean = false
+res0: Boolean = true

 scala> AnyRefClass.tpe eq AnyRefClass.typeConstructor
-res1: Boolean = false
+res1: Boolean = true
```

I haven't checked whether the test itself is correct but one way or another it looks like it should be rewritten as a junit unit test using just SymbolTable.

**Comment by paulp** [comment]
The test is correct.

**Comment by paulp** [comment]
Geez, why would someone want a mutable map to be "universally equal" to something which briefly had similar contents? Universal equality is such a crime.

**Comment by retronym** [comment]
That test seems to break now because we actually get around to clearing the uniques cache between runs. It passes under this patch:

``` patch
diff --git a/src/reflect/scala/reflect/internal/Types.scala b/src/reflect/scala/reflect/internal/Types.scala
index 99e6ae6..8a23804 100644
--- a/src/reflect/scala/reflect/internal/Types.scala
+++ b/src/reflect/scala/reflect/internal/Types.scala
@@ -3660,7 +3660,7 @@ trait Types
     if (Statistics.canEnable) Statistics.incCounter(rawTypeCount)
     if (uniqueRunId != currentRunId) {
       uniques = util.WeakHashSet[Type](initialUniquesCapacity)
-      perRunCaches.recordCache(uniques)
       uniqueRunId = currentRunId
     }
     (uniques findEntryOrUpdate tp).asInstanceOf[T]
```

**Comment by retronym** [comment]
I've just removed the eager clearing of the uniques cache to get that test working again.

**Comment by retronym** [comment]
PLS REBUILD/pr-scala@00e11ff

```
[artifact:deploy] An error has occurred while processing the Maven artifact tasks.
[artifact:deploy]  Diagnosis:
[artifact:deploy] 
[artifact:deploy] Error deploying artifact 'org.scala-lang:scala-dist:jar': Error installing artifact's metadata: Error while deploying metadata: Error transferring file
[artifact:deploy] Connection timed out

```

**Comment by retronym** [comment]
```
+ git fetch https://github.com/scala/jenkins-scripts.git HEAD
error: The requested URL returned error: 403 while accessing https://github.com/scala/jenkins-scripts.git/info/refs
fatal: HTTP request failed
Build step 'Execute shell' marked build as failure
```

PLS REBUILD ALL

PLS REWIRE INTERNET

**Comment by retronym** [comment]
PLS REBUILD ALL

(network problem reported to scala-internals)

**Comment by retronym** [comment]
Reviewers: all the failures you see above are now due to connectivity problems and can be ignored.

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
The build is now green.

**Comment by gkossakowski** [comment]
LGTM.

Thanks for leaving a note with explanation on symptoms even if we still don't understand the root cause. However, I agree that it doesn't seem to be harmful to leave uniques alone since they are a WeakSet now.

**Pull request merged**
