### PR TITLE
typedAnnotated no longer emits nulls

### PR DESCRIPTION
**Pull request by xeno-by**
Adds a null-check in original synthesis for the result of typedAnnotated.
Previously it was possible for the aforementioned result to look like
TypeTree(<tpe>) setOriginal Annotated(..., null). Not anymore.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
Would be useful to have this fix in 2.10.3-RC2, since it's very small and localized.

**Comment by retronym** [comment]
I don't understand this bug fully. Could you explain how it crops up in practice?

**Comment by xeno-by** [comment]
@retronym Every time a macro writer creates `Annotated(..., TypeTree(<tpe>))` without providing an original for the type tree, it's a sure NPE (more precisely speaking, a `MatchError: null`).

**Comment by retronym** [comment]
LGTM

**Pull request merged**
