### PR TITLE
fix broken links to Scala CLA

### PR DESCRIPTION
**Pull request by SethTisue**
reported by Sciss on Gitter

### CODE REVIEW

**Comment by retronym** [comment]
Not sure that they were actually broken, that URL redirects to the `www.` one.

```
⚡ curl --verbose typesafe.com/contribute/cla/scala
*   Trying 52.72.144.76...
* Connected to typesafe.com (52.72.144.76) port 80 (#0)
> GET /contribute/cla/scala HTTP/1.1
> Host: typesafe.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html
< Date: Mon, 01 Feb 2016 04:09:58 GMT
< Location: http://www.typesafe.com/contribute/cla/scala
< Server: nginx/1.8.0
< Content-Length: 184
< Connection: keep-alive
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
* Connection #0 to host typesafe.com left intact
```

I'll merge this in any case, it does no harm.

**Comment by retronym** [comment]
LGTM

**Comment by SethTisue** [comment]
Well, that's peculiar — I'm about 90% sure I tested the www-less links in my browser and they didn't work, and presumably Sciss had the same experience. But I tried just now and they work.

I'm only mildly curious what might have happened here, but I'll mention @edwardcallahan in case he wants to shed any light

**Comment by edwardcallahan** [comment]
Yes, typesafe.com and even https://typesafe.com will redirect. This is provided by the same service that redirects repo.typesafe.com and repo.scala-sbt.org that once had capybaras in a hot tub at its root. 

Maybe that service was not reachable at the time tested?

**Pull request merged**
