### PR TITLE
Resolves SI-7837, failure in quickSort.

### PR DESCRIPTION
**Pull request by Ichoran**
== instead of equiv (from Ordering) was used by mistake.  No tests; this is unlikely to revert.  (The problem with using == when one means equiv is likely to arise in other contexts, however.)

### CODE REVIEW

**Comment by retronym** [comment]
Could you please change the commit title of this and your other recent PRs to this format?

`SI-7837 failure in quickSort. == instead of equiv (from Ordering)`

**Comment by retronym** [comment]
I would like to see a test here too; showing that you can sort objects of a class that that have exception-throwing equals method would be a simple and strong test.

**Comment by Ichoran** [comment]
Sounds reasonable.

**Comment by Ichoran** [comment]
@retronym - Test added.  I think I've fixed the formatting on all pull requests that aren't problematic (e.g. failed tests, or have some uncertainty/problem with them).  Let me know if I missed any.

**Comment by retronym** [comment]
@Ichoran 

The commit title is still too long; it should be < 70 chars.

This makes the default output of `git log` hard to read on the terminal.

LGTM

**Comment by Ichoran** [comment]
It's not "still" too long, it's newly too long because I just copied from JIRA without paying attention to length.  I'll fix that also.

**Comment by retronym** [comment]
I'm going to merge as-is.

**Pull request merged**
