### PR TITLE
SI-8960 Bring back the SerialVersionUID to anonymous function classes

### PR DESCRIPTION
**Pull request by lrytz**
In PR #1673 / 4267444, the annotation `SerialVersionId` was changed
from a `StaticAnnotation` to `ClassFileAnnotation` in order to enforce
annotation arguments to be constants. That was 2.11.0.

The ID value in the AnnotationInfo moved from `args` to `assocs`, but
the backend was not adjusted. This was fixed in PR #3711 / ecbc9d0 for
2.11.1.

Unfortunately, the synthetic AnnotationInfo that is added to anonymous
function classes still used the old constructor (`args` instead of
`assocs`), so extracting the value failed, and no field was added to
the classfile.

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @retronym

**Comment by retronym** [comment]
The ghost of 4267444 comes back to haunt us again.

**Comment by retronym** [comment]
Let's expand the test with:
- functions of all arities
- specialized functions
- partial functions in the same variations
- check the value in the field is `0`

**Comment by lrytz** [comment]
Updated the tests.

**Comment by retronym** [comment]
LGTM. Could you proactively add a note about this to the release notes for 2.11.5?

**Comment by lrytz** [comment]
https://github.com/scala/scala-lang/pull/247

**Pull request merged**
