### PR TITLE
SI-7261 BooleanSetting to Boolean conversion

### PR DESCRIPTION
**Pull request by som-snytt**
Add an implicit for BooleanSetting to Boolean, since while we never expect the Spanish Inquisition, we do expect a boolean in an if clause.

The first cut put the implicit at AbsScalaSettings, but the more general case is at reflect/internal's MutableSettings. There was no particular desire to privilege mutability.

There is an additional implicit to convert BooleanSetting to BooleanFlag, in the second commit. Maybe you knew there was a BooleanFlag.

The second commit tries to be minimalist, just to 6x the .value. There are two or three spots where an expression has been restructured, but no intentional changes in behavior.

This PR is a rebase and resubmit of https://github.com/scala/scala/pull/2272.

Review by @paulp who liked the idea and @retronym who has already egged on.

### CODE REVIEW

**Comment by paulp** [comment]
It's bad style to mix anything else into the second commit. It should be nothing but the replacement of "settings.foo.value" with "settings.foo" - no introductions of string interpolation, no changing pattern matcher variable pattern names, no reworking whitespace, no refactoring error messages. All the changes which aren't that should be in a separate, third commit.

It's relatively easy to introduce subtle behavioral changes with a commit like this - for instance the inferred type of something might change from Boolean to BooleanSetting. This makes it important that the commit be as small and single-purpose as possible.

Here are the stats if I diff my more focused version of this against this PR:

```
git diff --stat refs/pull/2297/head
  src/compiler/scala/reflect/macros/util/Traces.scala                   |  4 ++--
  src/compiler/scala/reflect/reify/Phases.scala                         |  2 +-
  src/compiler/scala/reflect/reify/Reifier.scala                        | 23 ++++++++---------------
  src/compiler/scala/reflect/reify/phases/Metalevels.scala              |  2 +-
  src/compiler/scala/tools/ant/FastScalac.scala                         |  2 +-
  src/compiler/scala/tools/ant/sabbus/Compiler.scala                    |  2 +-
  src/compiler/scala/tools/nsc/CompileClient.scala                      |  3 +--
  src/compiler/scala/tools/nsc/CompilerCommand.scala                    |  7 +++----
  src/compiler/scala/tools/nsc/Driver.scala                             |  2 +-
  src/compiler/scala/tools/nsc/backend/icode/Repository.scala           |  2 +-
  src/compiler/scala/tools/nsc/backend/jvm/GenASM.scala                 |  4 ++--
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala   | 24 +++++++++++++-----------
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala          |  7 ++++---
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala                  |  4 ++--
  src/reflect/scala/reflect/internal/transform/Erasure.scala            |  2 +-
  src/scaladoc/scala/tools/nsc/doc/html/page/diagram/DiagramStats.scala |  2 +-
  16 files changed, 43 insertions(+), 49 deletions(-)
```

My version is available for you at dcf0be9b5e68 . I may not have caught everything, and I didn't test it. Can you rework this PR based on that commit (and fix its commit message, since the later things are no longer in it.)Anything which is in this PR and not that one can go in a third commit, if it stands on its own merits. But even "minor tweaks to s... for readability" and "trailing case ex: which confuse vi modelines" should have separate commits.

**Comment by som-snytt** [comment]
How about if I just propose the two implicits for BooleanSetting => Boolean and => BooleanFlag in one commit for this PR?  Or perhaps a separate commit for each.

I tried to strike a balance between minimal and Boy Scout rule in the 2nd commit, but this morning (while waiting on a build) I scanned it again and saw a s/.value// I'd meant to get back to.  That's benign, but demonstrates that eyeballing is limited.  Tests passing means nothing at this granularity of coverage.  Therefore, since the second commit is little better than a whitespace change in terms of utility, we can just skip it.  I've already rebased for conflicts, which is why such trivial deltas don't carry their weight.  I bet it messes up future merges from 2.10, too.

That said, the first commit does enable better-looking code.

OTOH, maybe some people prefer settings.foo.value.  Also, relying on the conversion in a def foo: Boolean = settings.foo is arguably confusing.  Since no advocates taking the devil's part are likely to chime in, I'll offer to resubmit without; come to think of it, I only did it at retronym's offhand instigation.

On the third hand, if you want it, I'll remunge it.  I appreciate that you've already spent too much time.

**Comment by paulp** [comment]
> Also, relying on the conversion in a def foo: Boolean = settings.foo is arguably confusing.

I agree that was gratuitous. I don't care if some people prefer settings.foo.value, it's so noisy that it obscures the code. But for a long lived "val foo = settings.bar.value", we can surely fade the .value. Please feel free to resubmit that way.

**Comment by paulp** [comment]
By the way, I didn't know there was a "BooleanFlag", even at this late date. Shows you how closely I'm managing to review this stuff.

**Pull request closed without merging**
