### PR TITLE
improvements to reflection API

### PR DESCRIPTION
**Pull request by xeno-by**
review by reflection meeting

### CODE REVIEW

**Comment by odersky** [comment]
LGTM

**Comment by jsuereth** [comment]
D'oh!  Merge conflicts.  IF you update I'll try to pull ASAP over other commits.  

Sorry, I've been going through by "unread comments", must have pulled in something else that conflicts with this.

**Comment by xeno-by** [comment]
Prepping a pullrequest that would unite https://github.com/scala/scala/pull/1017, https://github.com/scala/scala/pull/1031 and https://github.com/scala/scala/pull/1035. ETA: 15 minutes.

**Comment by xeno-by** [comment]
https://github.com/scala/scala/pull/1039

**Pull request closed without merging**
