### PR TITLE
SI-3600 Allow annotations on package objects

### PR DESCRIPTION
**Pull request by gzm0**
This will desugar annotations on package objects to the object `package` which is generated. Further, it will add the annotations to the package symbol.

### CODE REVIEW

**Comment by adriaanm** [comment]
See also https://issues.scala-lang.org/browse/SI-3115

**Comment by xeno-by** [comment]
ping @gzm0 

The build failure is non-spurious:

```
BUILD FAILED
/localhome/jenkins/a/workspace/pr-scala-rangepos/scala/build.xml:1420: The following error occurred while executing this line:
/localhome/jenkins/a/workspace/pr-scala-rangepos/scala/build-ant-macros.xml:488: Test suite finished with 1 case failing:
fail - neg/t3209.scala  [output differs]% scalac t3209.scala
t3209.scala:2: error: identifier expected but eof found.
package test
            ^
one error found

% diff /localhome/jenkins/a/workspace/pr-scala-rangepos/scala/test/files/neg/t3209-neg.log /localhome/jenkins/a/workspace/pr-scala-rangepos/scala/test/files/neg/t3209.check
@@ -1,4 +1,4 @@
-t3209.scala:2: error: identifier expected but eof found.
+t3209.scala:2: error: expected start of definition
 package test
-            ^
+^
 one error found
```

**Comment by gkossakowski** [comment]
@gzm0: ping again

**Comment by gzm0** [comment]
Hmmm... The Scaladoc seems to fail. When I execute this locally, I get (amongst tons of warnings) the following errors:

```
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/GenIterableLike.scala:128: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def zipAll[B](that: Iterable[B], thisElem: A, thatElem: B): $Coll[(A, B)]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/GenIterableLike.scala:101: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def zipWithIndex: $Coll[(A, Int)]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/GenIterableLike.scala:73: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def zip[B](that: GenIterable[B]): $Coll[(A, B)]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/parallel/ParIterableLike.scala:719: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def scan(z: T)(op: (T, T) => T): $Coll[T]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/GenTraversableLike.scala:265: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def ++[B](that: GenTraversableOnce[B]): $Coll[B]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/GenTraversableLike.scala:223: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def flatMap[B](f: A => GenTraversableOnce[B]): $Coll[B]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/GenTraversableLike.scala:202: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def collect[B](pf: PartialFunction[A, B]): $Coll[B]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/GenTraversableLike.scala:184: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def map[B](f: A => B): $Coll[B]
 [scaladoc]                ^
 [scaladoc] /Users/tschlatt/Documents/scala/src/library/scala/collection/generic/GenericTraversableTemplate.scala:148: error: Incorrect variable expansion for $Coll in use case. Does the variable expand to wiki syntax when documenting class ParHashSet?
 [scaladoc]    *  @usecase def flatten[B]: $Coll[B]
 [scaladoc]                ^
```

I currently fail to understand, how the changes in the PR influence that part of ScalaDoc.

**Comment by adriaanm** [comment]
weird, that shouldn't be an error unless you're compiling under -Xfatal-warnings, right?

**Comment by adriaanm** [comment]
RC1 deadline is around the corner. If you'd like this PR to be included, please submit a new one, motivating why it should block the release.

**Pull request closed without merging**
