### PR TITLE
SI-5508 Fix crasher with private[this] in nested traits

### PR DESCRIPTION
**Pull request by retronym**
Currently, this is done late in the game as the Mixin tree transformer
treats the trait.

```
// Mixin#addLateInterfaceMembers
val getter = member.getter(clazz)
if (getter == NoSymbol) addMember(clazz, newGetter(member))
```

`addMember` mutates the type of the interface to add the getter.

However, if an inner class or anonymous function of the trait
has been flattened to a spot where it precedes the trait in the
enclosing packages info, this code hasn't had a chance to run,
and the lookup of the getter crashes as mixins postTransform
runs over a selection of the not-yet-materialized getter.

```
// Mixin#postTransform
case Select(qual, name) if sym.owner.isImplClass && !isStaticOnly(sym) =>
  val iface  = toInterface(sym.owner.tpe).typeSymbol
  val ifaceGetter = sym getter iface
```

This commit removes ensures that Flatten lifts inner classes to
a position _after_ the enclosing class in the stats of the
enclosing package.

### CODE REVIEW

**Comment by retronym** [comment]
This is an alternative to #3199

**Comment by retronym** [comment]
Review by @JamesIry

**Comment by adriaanm** [comment]
ping

**Comment by JamesIry** [comment]
Good ol' NoPosition. If there's any position that doesn't know where it stands, it's NoPosition.

**Comment by xeno-by** [comment]
PLS REBUILD/pr-scala@c08fc4c

**Comment by retronym** [comment]
Closing in favour of "Third time's the charm", #3234

**Pull request closed without merging**
