### PR TITLE
2.11.5 bump

### PR DESCRIPTION
**Pull request by adriaanm**
review by @xeno-by

### CODE REVIEW

**Comment by xeno-by** [comment]
Why did the build fail?

**Comment by adriaanm** [comment]
jenkins problem: https://scala-webapps.epfl.ch/jenkins/job/pr-scala/9468/console

**Comment by adriaanm** [comment]
PLS REBUILD/pr-scala@4e77c51decb7090efe11d5c7960a4cd563a14fc0

**Comment by adriaanm** [comment]
@dragos gave the go ahead to merge.

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
LGTM

Let me take this one.

**Pull request merged**
