### PR TITLE
Backports for SI-2418 SI-4729 SI-5130 SI-5353 SI-5604 SI-5859 SI-6072 SI-6426 SI-6482 SI-6584 SI-6595

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
It's a little optimistic given that I haven't even tried to compile since cherry-picking those 11 commits, but my pull-request alias got a little ahead of me so I'll just see what jenkins says.

**Comment by adriaanm** [comment]
You have a PR alter ego?

**Comment by paulp** [comment]
That's right, my alias does the drudge work. I have to keep my hands free for superhero situations.

**Comment by som-snytt** [comment]
PR = Paul's Robin, to his Batman.  "Robin, go see if these merges compile."  "Holy pile, Batman, why did I ever sign up for a superhero internship?  I could've had a real job!"  "Yes, Robin, I, too, feel the occasional twinge.  But when I see the faces of those children who will grow up to be Scala programmers -- I know I'm fulfilling -- my destiny!"

**Comment by adriaanm** [comment]
build failed

**Comment by paulp** [comment]
Closing, will reincarnate with a version I actually believe to pass.

**Pull request closed without merging**
