### PR TITLE
Fixes SI-6551.

### PR DESCRIPTION
**Pull request by namin**
Don't rewrite an explicit apply method to dynamic polytypes.

### CODE REVIEW

**Comment by namin** [comment]
Review by @retronym.

Sorry, this fell off my radar. I am not sure what's the best way to express positively the condition for a rewrite to apply and why polytypes are not handled before. I would need to investigate. Let me know if that's necessary.

**Comment by retronym** [comment]
Could you please apply Paul's suggestion?

https://github.com/scala/scala/pull/1516#discussion_r1898814

**Comment by namin** [comment]
Applied Paul's suggestion.

**Comment by retronym** [comment]
Looks like an improvement to me. I won't be surprised if we have to refine this further in the future as this feature is used more widely, but I can't find a case right now that falls afoul of this code. So let's merge.

**Comment by adriaanm** [comment]
Could you please update the commit message's title to "SI-6551 don't insert apply call in polymorphic expression" or some such? As it stands, the log will only show the ticket number, which makes it harder to create nice release notes

**Comment by namin** [comment]
Done. Also rebased.

**Comment by adriaanm** [comment]
Thanks!

**Pull request merged**
