### PR TITLE
Make to able search FunctionN, ProductN and etc for N > 2

### LINKED ISSUE #10385: Scala documentation's search doesn't find FunctionN and ProductN for N > 2
For example, if I search `Function3` in Scala documentation, it [doesn't show any results](http://www.scala-lang.org/api/2.12.2/scala/index.html?search=Function3). If I search `Product`, it show [`Product`, `Product1` and `Product2`](http://www.scala-lang.org/api/2.12.2/scala/index.html?search=Product) (no Product3 and etc).

### PR DESCRIPTION
**Pull request by NomadBlacky**
Closes https://github.com/scala/bug/issues/10385

```shell
$ ./build/quick/bin/scaladoc src/library/scala/Function2.scala src/library/scala/Function3.scala
```

image

---

This P.R. made from [OSS Hackathon @ ScalaMatsuri 2019](https://scalaconfjp.doorkeeper.jp/events/91355).

### CODE REVIEW

**Comment by xuwei-k** [comment]
`def isExcluded(qname: String)` added by @VladUreche commit

https://github.com/scala/scala/pull/386/files#diff-05dedb334e5500ea12642e9089d91636R163

**Comment by dwijnand** [comment]
The original exclusion was https://github.com/scala/scala/commit/34bc787b0884dda9e6ad0a75f66ea88b43d8304e done in.  I'm guessing it was to reduce being overwhelmed.

**Comment by lrytz** [comment]
I'm fine with this PR, as we already include all Function / Tuple / Product Ns in the package member list in the sidebar.

image

Hiding them in the search result seems to cause confusion.

**Comment by lrytz** [comment]
However, it seems `hardcoded.isExcluded` is also used when generating diagrams, those classes just don't show up in diagrams. We should probably stop doing that too.

**Comment by lrytz** [comment]
Pushed my suggested change.

**Review by lrytz — APPROVED** [review]

**Comment by SethTisue** [comment]
thank you @NomadBlacky !

**Comment by NomadBlacky** [comment]
Thank you for helping me!

**Pull request merged**
