### PR TITLE
SI-8627 Override filterNot in Stream

### PR DESCRIPTION
**Pull request by ruippeixotog**
Fixes a bug in which `Stream#filterNot` performs an eager evaluation of
the `Stream` it is called on. Also adds an additional unit test that
exposes the bug.

Previously, commit 7a6905dc15 fixed this method, but commit 3059e3a0c03
broke it again. In my opinion, `Stream` should not rely on the fact
that `TraversableLike`’s implementation of `filterNot` uses `filter`,
as it is not mandatory in the method’s contract. Instead, the method
should be overriden in `Stream` - that way, `Stream` will be more
resilient to changes in its underlying traits.

### CODE REVIEW

**Comment by ruippeixotog** [comment]
The build failed because of binary compatibility issues, but the error message is not clear to me:

```
     [mima]  * method filterNot(scala.Function1)scala.collection.immutable.Stream in
     [mima]    class scala.collection.immutable.Stream has now a different result type;
     [mima]    was: scala.collection.immutable.Stream, is now: java.lang.Object
```

As I understand, the `Stream#filterNot(Function1)` method returned and still returns a `Stream` after this PR. Can anyone explain to me why this breaks compatibility or give me an example of such?

**Comment by som-snytt** [comment]
You also get a bridge method:

```
scala> :javap -public scala.collection.immutable.Stream#filter
  public scala.collection.immutable.Stream<A> filter(scala.Function1<A, java.lang.Object>);
  public java.lang.Object filter(scala.Function1);
```

The ticket has some very educational history.  The comments on SI-6440 show that they considered nailing down `filterNot` as you've done, then decided instead to leave it in `TraversableLike`, where it was subject to a repeat regression. (That is, 6440 was to fix the same obvious "optimization", or whatever the word is for an impossible balance between reuse, method size for inlining, and correctness.)

**Comment by ruippeixotog** [comment]
Thanks @som-snytt. Indeed, reading [SI-6440](https://issues.scala-lang.org/browse/SI-6440) (added link here for future reference) gave me a much better view of the problem.

In my opinion, making `filterNot` be always implemented in terms of `filter` in `TraversableLike` is probably the best option. But I can also understand why there are frequent regressions - a person trying to optimize little bits of code here and there, unaware of this discussion, may look at `TraversableLike` and find that writing a custom implementation of `filterNot` would bring performance improvements. As the `filterNot` contract (i.e. scaladoc) does not require it to be implemented in terms of `filter`, one can argue that `TraversableLike` implementations should not rely on that either.

Given that, I think `TraversableLike#filterNot` should be indeed reverted and that design choice should be documented in the scaladoc of `TraversableLike#filterNot`. In my view, this would make scala-library devs think twice before writing an implementation of `TraversableLike#filterNot` that is explicitly against the documentation. It would also give additional confidence to developers of custom collections.

What do you think of this solution?

**Comment by paulp** [comment]
"In my opinion, making filterNot be always implemented in terms of filter in TraversableLike is probably the best option."

When you want to enforce that some method is always implemented in terms of some other method, there is a keyword available which guarantees it. Nothing else works, especially not documentation.

**Comment by Ichoran** [comment]
Creating an extra function object really isn't a nice thing to do to users: "Hi, we have this tempting method here that will unexpectedly make your code run twice as slow just so it reads a little nicer--good luck figuring it out, too!"

So I'm afraid we need to keep the implementation as is for the time being.  I really wish we had a "must be overridden together" annotation so that when people override filter the compiler yells at them for not also overriding filterNot.

I'm not the right person to decide whether the bug is serious enough to warrant breaking bincompat--probably not?--but it can certainly go in 2.12.  I think the solution should not be this one (i.e. expensive), but rather replicating the logic of filterImpl of TraversableLike and then defining both filter and filterNot in terms of that method.

**Comment by paulp** [comment]
You could make both filter and filterNot final and route them through some protected overridable method like filterImpl. (I'm ignoring binary compat, it's just a way to achieve atomicity.)

**Comment by lrytz** [comment]
Re-submitted slightly differently in #3949, hope that's binary compatible enough.

**Pull request closed without merging**
