### PR TITLE
fix scala/bug#10810

### PR DESCRIPTION
**Pull request by remk**
Give the DefaultThreadFactory maxNoOfThreads + 2 * maxExtraThreads.
It's seem that the Forkjoinpool need this number of thread in order to avoid the thread starvation on a later execution without block context.
Also make the  DefaultThreadFactory to not implement ThreadFactory anymore as it's unused and can mess with the internal Thread count.

### CODE REVIEW

**Comment by remk** [comment]
fix scala/bug#10810

**Comment by remk** [comment]
I have just signed the CLA

**Comment by viktorklang** [comment]
@remk How does doubling the number of maxExtraThreads solve the problem? (If it does solve the problem, I suggest changing the default to 512 instead of modifying the calculation). Also, a regression test would be needed.

(I suspect a bug in FJP so forgive me if I am highly skeptical to this proposed change solving the problem)

**Comment by remk** [comment]
@viktorklang it seems that the thread factory need to have 2 times the number of extra thread that the fork join pool is supposed to have. Changing the default would solve nothing but the key to the fix is just to let the factory give 2 times the number of thread to the pool, in order that it don't get in the wrong state the gist put in exergue.
I don't say it's the best way to fix it. I think the root of the problem is in the FJP itself like you suspect.
But it seems like a reasonable default before the problem is solved in the JDK.
With this fix even for batch of 5000 the problem doesn't appear, and the memory don't blow by creating 5000 threads.

**Comment by remk** [comment]
@viktorklang forget what I have just said. It doesn't fix anything. 
I must have messed with my test cases. I think your are totally right, the problem is in the fork join pool, and can be solved only there.

**Pull request closed without merging**
