### PR TITLE
Duplicate license in /LICENSE for GitHub

### PR DESCRIPTION
**Pull request by adriaanm**
So that our license (in doc/LICENSE.md) is detected by `licensee`.
Also removed some cruft while I was at it... Bye bye svn mappings.

### CODE REVIEW

**Comment by adriaanm** [comment]
/nothingtoseehere -- this is not covered by CI

**Comment by adriaanm** [comment]
/nothingtoseehere -- this is not covered by CI

**Comment by SethTisue** [comment]
that TODO list looks like it was written by mastodons and saber-toothed tigers

**Comment by adriaanm** [comment]
On steam-powered type writers.

**Comment by SethTisue** [comment]
LGTM

also, way to pump up your “lines removed” numbers

**Comment by adriaanm** [comment]
🏌️

**Comment by SethTisue** [comment]
success

screen shot 2016-10-18 at 9 43 14 pm

**Comment by adriaanm** [comment]
So pretty.

**Pull request merged**
