### PR TITLE
script engine : better binding mechanism + reflexive access through bound variable "engine"

### PR DESCRIPTION
**Pull request by rjolly**

### CODE REVIEW

**Comment by JamesIry** [comment]
review @paulp

**Comment by paulp** [comment]
Looks like a winner to me.

**Comment by paulp** [comment]
...except the commit messages.  https://github.com/scala/scala/wiki/Pull-Request-Policy

**Comment by paulp** [comment]
Those subject lines are still too long but I really want this fix so here we go.

**Pull request merged**
