### PR TITLE
silences t6323a

### PR DESCRIPTION
**Pull request by xeno-by**
Tag materialization notices enabled with -Xlog-implicits are now warnings
not printlns. Therefore, they go into stderr, not stdout, getting logged
by partest and not spamming stdout of partest.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp

**Comment by paulp** [comment]
```
  -Xlog-implicits                Show more detail on why some implicits are not applicable.
```

I don't see anything in that description about issuing WARNINGS, which are not merely fancy printlns. The other usage site for the setting says

```
      if (settings.XlogImplicits.value)
        reporter.echo(pos, what+" is not a valid implicit value for "+pt+" because:\n"+reason)
```

which looks a lot more correct.

**Comment by xeno-by** [comment]
Right! Thank you, Paul. I'll correct the PR in a moment.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
