### PR TITLE
Bump version number in build.number to 2.11.4

### PR DESCRIPTION
**Pull request by gkossakowski**
This should happen every time we cut a new release. We don't touch
versions.properties files because that file specifies dependencies and
we don't want to depend on broken Scala 2.11.3 release.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @lrytz

**Comment by lrytz** [comment]
LGTM. Merging so we can move forward.

**Comment by adriaanm** [comment]
Hmm, how about scala.full.version=2.11.2 in versions properties?

**Comment by adriaanm** [comment]
Ah, nevermind. Same reasoning as for not bumping starr.

**Pull request merged**
