### PR TITLE
Preserve tab in caret line

### LINKED ISSUE #9438: Compiler's error reporting does not handle tabs properly
The column pointer will fall out of alignment with what it's supposed to be pointing to if the cli environment differs from scalac's expectations in one of two ways:
1: Tab width is not equivalent to 4 spaces
2: Something is prefixed to scalac's output for which prefix.length is not a multiple of 4
For instance,
```
[ant:scalac] /home/mako/programming/ ... /Code.scala:289: error: type mismatch;
[ant:scalac]  found   : Double
[ant:scalac]  required: Float
[ant:scalac] 				if(dt < 1) f(Math.pow(2, 10 * (dt - 1) - 1))
[ant:scalac]                                                      ^
```
In my terminals, comes out looking roughly like
```
[ant:scalac]                         if(dt < 1) f(Math.pow(2, 10 * (dt - 1) - 1))
[ant:scalac]                                                                ^
```
making it much harder to tell where the error is.

Easy fix, I think. For an error being reported against line:Int, column:Int, scalac's output for the pointer line should be 
```scala
codeAtLine(line).slice(0,column).map{ case '\t' => '\t'; case c:Char => ' ' }+'^'
```
This will always put the ^ in the right place.

### PR DESCRIPTION
**Pull request by som-snytt**
At least one test has interior tab chars.

Fixes scala/bug#9438

### CODE REVIEW

**Review by dwijnand — COMMENTED** [review]
Nice fix!  But could you shift it (see what I did there?) near `calculateColumn`, so they can stay similar after this?

**Review by dwijnand — APPROVED** [review]
ty!

**Comment by som-snytt** [comment]
It would be nice if deprecated `lineCarat` were repurposed to emit `<>` instead of `^`, then it could be called the "diamond" operator.

**Comment by SethTisue** [comment]
@som-snytt how much funding are you getting from the fat cats in Big Tabs

**Comment by som-snytt** [comment]
@SethTisue my workplace is tabs all the way down. Not describing the sodas in the fridge.

**Pull request merged**
