### PR TITLE
More fix for invalid companions.

### PR DESCRIPTION
**Pull request by paulp**
Eliminated InvalidCompanions exception entirely.  Anyone's
guess why we unholstered this exception every time someone
calls "isCodefinedWith" rather than when symbols are created.
I moved the check into Namers, where it can be done once and
with sufficient finesse not to crash so much.

With this patch in place, "playbench" can be built with java7.

### CODE REVIEW

**Comment by jsuereth** [comment]
CURSE YOU FOR ADDING USEFUL ERROR MESSAGES!

```
  [partest] testing: [...]/files/neg/t1286                                        [FAILED]
  [partest] a.scala:1: error: Companions 'trait Foo' and 'object Foo' must be defined in same file:
  [partest]   Found in t1286/a.scala and t1286/b.scala
  [partest] trait Foo {
  [partest]       ^
  [partest] one error found
```

Also 

```
  [partest] testing: [...]/files/neg/t5031b                                       [FAILED]
  [partest] a.scala:3: error: Companions 'class Bippy' and 'object Bippy' must be defined in same file:
  [partest]   Found in t5031b/a.scala and t5031b/b.scala
  [partest] class Bippy
  [partest]       ^
  [partest] one error found
```

The patch LGTM

**Comment by gkossakowski** [comment]
Well, it make tests fail so how come LGTM?

**Comment by paulp** [comment]
I don't understand the partest output.  These tests pass for me. The jenkins log seems to be the checkfile.  Does that mean they are compiling and there is no output? I have no way to debug this.

**Comment by jsuereth** [comment]
The patch LGTM assuming the tests pass.   It looks like the new error message is the cause of the issues.

I'm not sure what the issue is here. I can try locally.

**Comment by paulp** [comment]
But it isn't a new message.  One of the failing tests is a new test which emits that message; the other, t1286, is a pre-existing test which isn't even touched in this commit.

**Comment by jsuereth** [comment]
When I look at diffs, the additional "which file" in the error message is new.   That's what is failing these two tests, according to Jenkins.   I'll see if I can patch your pull

**Comment by paulp** [comment]
Look more closely. It is not new.

**Comment by jsuereth** [comment]
Right, but in a different spot, are you catching more cases?   I just got back to this, checking out now.

**Comment by jsuereth** [comment]
I reproduced locally.  I'll try to submit you a patch if I figure out what's up.

**Comment by jsuereth** [comment]
Ok, t1286  failure is because you warn on the object, not the trait now.  Simple fix.  Looking at the other.

**Comment by paulp** [comment]
@jsuereth did you decide that this failing test (which passes for me, and vice versa if we update the output) was an ordering issue introduced by the recent patch to partest? Does this pull req wait only on fixing that?

**Comment by jsuereth** [comment]
@paulp  That ordering fix, fixes this patch.  You can pull that one out separately if you want, but it has to go in before/with this patch.  It solves the issue on linux.

**Comment by jsuereth** [comment]
See #1260 which is this same fix, but with cross-platform issues fixed.

**Pull request closed without merging**
