### PR TITLE
SI-6575 Type ascribe partial function literals.

### PR DESCRIPTION
**Pull request by retronym**
Usually this isn't needed, as partial functions can only be
defined with an expected type. But if that expected type is
and inherited method return type, the actual type of the partial
function literal is used, and the implementation detail of
`AbstractPartialFunction[A, B] with Serializable` leaks out.

After this change, the inferred types match those from
Scala 2.9.2.

```
ticket/6575 ~/code/scala scalac29 -Xprint:typer test/files/pos/t6575a.scala | grep def > 29.txt
ticket/6575 ~/code/scala squalac -Xprint:typer test/files/pos/t6575a.scala | grep def > 210.txt
ticket/6575 ~/code/scala diff -u 29.txt 210.txt
--- 29.txt  2012-10-28 13:51:07.000000000 +0100
+++ 210.txt 2012-10-28 13:51:20.000000000 +0100
@@ -1,7 +1,16 @@
     def foo: PartialFunction[Int,Int]
     def /*Y*/$init$(): Unit = {
-    absoverride def foo: PartialFunction[Int,Int] = ((x0$1: Int) => x0$1 match {
+    absoverride def foo: PartialFunction[Int,Int] = {
+        def <init>(): anonymous class $anonfun = {
+        final override def applyOrElse[A1 >: Nothing <: Int, B1 >: Int <: Any](x$1: A1, default: A1 => B1): B1 = (x$1: A1 @unchecked) match {
+        final def isDefinedAt(x$1: Int): Boolean = (x$1: Int @unchecked) match {
     def /*Z*/$init$(): Unit = {
-    absoverride def foo: PartialFunction[Int,Int] = ((x0$2: Int) => x0$2 match {
+    absoverride def foo: PartialFunction[Int,Int] = {
+        def <init>(): anonymous class $anonfun = {
+        final override def applyOrElse[A1 >: Nothing <: Int, B1 >: Int <: Any](x$1: A1, default: A1 => B1): B1 = (x$1: A1 @unchecked) match {
+        final def isDefinedAt(x$1: Int): Boolean = (x$1: Int @unchecked) match {
     def /*Comb*/$init$(): Unit = {
-    absoverride def foo: PartialFunction[Int,Int] = ((x0$3: Int) => x0$3 match {
+    absoverride def foo: PartialFunction[Int,Int] = {
+        def <init>(): anonymous class $anonfun = {
+        final override def applyOrElse[A1 >: Nothing <: Int, B1 >: Int <: Any](x$1: A1, default: A1 => B1): B1 = (x$1: A1 @unchecked) match {
+        final def isDefinedAt(x$1: Int): Boolean = (x$1: Int @unchecked) match {
```

review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
Builds were aborted. (Why?)

PLS REBUILD ALL

**Comment by lrytz** [comment]
we still have no idea why jenkins keeps aborting builds. https://groups.google.com/forum/#!topic/jenkinsci-users/GN0N4mqaCa4/discussion

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
Closing for renovations.

**Comment by retronym** [comment]
Resubmitted as #1530

**Pull request closed without merging**
