### PR TITLE
fix bug in immutable.HashMap.split

### PR DESCRIPTION
**Pull request by ansvonwa**
Fixes scala/bug#11257

### CODE REVIEW

**Comment by SethTisue** [comment]
tempting to sneak this in, but decided to push it to 2.12.9, since 1) we've already QAed a 2.12.8 build and we're eager to get it out the door, and 2) we're trying to keep 2.12.8 focused on fixing 2.12.7's regressions

who knows this code best, to review the change? @Ichoran? @retronym?

(I don't have time to study the code before my December vacation)

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
Added a test and marked the commit message `[nomerge]`

**Comment by SethTisue** [comment]
@ansvonwa is some form of this needed in 2.13.x?

**Comment by ansvonwa** [comment]
Nope, the bug was in `split` which has been removed completely (maybe because nobody really used it). And, it was closely related to the implementation details, so even if someone would implement `split` it in the new `s.c.i.HashMap`, it is unlikely they would make the same mistake again.

**Pull request merged**
