### PR TITLE
Remove text that states CDATA sections or PIs are not supported

### PR DESCRIPTION
**Pull request by Philippus**
Fixes https://github.com/scala/bug/issues/5109

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @ashawley ?

**Comment by ashawley** [comment]
Yes, this checks out.  Had to inspect the tests in https://github.com/scala/scala/pull/6569 to verify.

**Review by ashawley — APPROVED** [review]

**Comment by som-snytt** [comment]
Thanks, I see from the ticket I dropped the ball twice in a row, which I think counts as dribbling.

The implementation PRs were quite sloggy, as is not unknown in software. I don't remember how this update got away from me, but my comment on the ticket is from last year, which I also don't remember.

**Comment by Philippus** [comment]
@ashawley @SethTisue let's merge this ?

**Pull request merged**
