### PR TITLE
SI-6963 Deprecates -Xmigration switch

### PR DESCRIPTION
**Pull request by JamesIry**
-Xmigration is specific to the 2.7 to 2.8 upgrade and is no longer
relevant. There is no plan to maintain it so it will be removed. This
commit deprecates it in anticipation.

review @gkossakowski

### CODE REVIEW

**Comment by retronym** [comment]
What's the schedule for removal? Can we swing it in 2.11.0? My vote is a resounding YES!.

**Comment by JamesIry** [comment]
@retronym 2.11 is what I have scheduled on the ticket. It could be moved, I guess, but I don't see any reason to unless somebody objects to deprecation in a .1 release followed by removal in the next major release.

**Comment by soc** [comment]
I don't want to hang on it, but what about fixing the existing issues with it?

**Comment by retronym** [comment]
It will remain in the history and can be resurrected if we need it again. Usually if people are using a feature, it will attract some questions on the mailing list. I've never seen one for this option, which suggests that we failed to educate users about it. If we invest time into fixing the technical issues, we should do so with a plan to fix this important non-technical issue.

**Comment by JamesIry** [comment]
The main problem with keeping it is that it would require a lot of care and feeding on an ongoing basis to keep it up to date and useful.

**Comment by gkossakowski** [comment]
@JamesIry, normally we do not deprecate in minor releases (.1) but since probability that somebody is doing anything useful with this option in 2.10.0 release is zero we should bend our rules in this case.

**Comment by paulp** [comment]
I think we're all agreed on this one.

**Pull request merged**
