### PR TITLE
Issue/5330

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
Review by @retronym, @odersky.

**Comment by retronym** [comment]
It might be problematic to overload the OVERRIDE flag in this way.

Firstly, it seems to make `Symbol#isOverride` unstable. One remedial measure might be to remove it from the public reflection API.

But more importantly, it is also used (indirectly via `isAnyOverride`) in RefChecks for various override checks; I worry that changing it's meaning will subvert these (e.g. preventing accidental overrides.)

**Comment by paulp** [comment]
1) To clarify, I based the existential fix on the override commit, but they're totally distinct; neither requires the other.  (I realize this means I shouldn't have mixed them, but they have common idea parentage.)

2) I acknowledge these override issues but they are easily addressable.  For one thing refchecks already traverses all that stuff, probably several times; it doesn't need to rely on the flag. I can separate the traversal from the flag check.  And as my commit message indicates, I'd rather set the flag at creation time anyway, which should deal with the instability problem.  If there is anything which stands in the way of this kind of sensible direct approach, I'm betting it's a thing which is already on the "problem" side of the ledger.

**Comment by retronym** [comment]
(continuing the discussion of OVERRIDE, seeing as we started here.)

My concern was based on the assumptions: 

1) OVERRIDE means that Joe programmer typed 'override' in his source code
2) The compiler predicates certain checks based on whether or not he did this.
3) Said checks might give the wrong results if they find that flag on a symbol that happens to match a method in a supertype and which has been the target of a call to `isOverridingSymbol` earlier in typechecking.

But I'm not able to construct an example to justify these fears, so I'm sort of assuming that these assumptions aren't quite right.

**Comment by paulp** [comment]
The OVERRIDE flag on Modifiers means Joe typed "override" in his source code.  The OVERRIDE flag on a symbol doesn't mean anything so far as I can tell.  Certainly it does not correspond to whether someone typed override.

But if we're issuing errors to Joe, it's based on source code, which means there is a DefDef with which he did or did not type "override".  ddef.mods.isOverride is the only reliable way to know that.  If that's not what refchecks does, refchecks is doing it wrong.

**Comment by paulp** [comment]
On consideration I have to temper that comment; still true is "OVERRIDE is not used to mean that." Not so true is that we will always have access to the tree we need.

**Comment by paulp** [comment]
Going to reopen with narrower focus.

**Pull request closed without merging**
