### PR TITLE
SI-7984 Issue unchecked warning for type aliases

### PR DESCRIPTION
**Pull request by retronym**
The unchecked nature of the type test was already noticed,
but because the type alias tripped up in rendering a sensible
message `CheckabilityChecker` chose to remain silent, other
than under `-Xdev.`

This commit:
- Dealiases pattern types before launching the CheckabilityChecker
- Sharpens the error messages to explain that the dealiased type
  is the expansion of the alias.

### CODE REVIEW

**Comment by jozic** [comment]
that was fast ) thanks Jason!

**Comment by retronym** [comment]
I'll fix the test failures tomorrow morning.

**Comment by retronym** [comment]
Review by @adriaanm.

I'm tossing up whether or not to suppress the longer error messages (`X[A] (underlying of Y[B])`) for "direct" aliases like `scala.Set`. Probably should. I can't find existing code to check for such an alias, but I suppose it won't be too tricky to write.

**Comment by adriaanm** [comment]
LGTM -- I don't know of any utility code lying around for detecting straight shot aliases

**Pull request merged**
