### PR TITLE
SI-9509 Interpolated identifiers must be alnums

### PR DESCRIPTION
**Pull request by som-snytt**
As per the spec, more or less, interpolated identifiers
(escaped words in the interpolated string) must consist
of letters or digits only.

This definition excludes underscore in particular, as well
as other characters that are valid identifier parts but
are neither letters nor digits.

### CODE REVIEW

**Comment by som-snytt** [comment]
Sorry, Jenkins, I missed an `--update-check`.

It would be very cool if Jenkins could suspend a job instead of failing it, wait for an updated .check file(s) then resume from there. With some smarts, you could also update test source.

**Comment by som-snytt** [comment]
@SethTisue This is a gatekeeper PR and you are the gatekeeper.

**Comment by som-snytt** [comment]
FTR, I needed this today.

```
        val adjusted = contextual.map(_.decodedName match {
            case "println" =>
              s"""def println(arg: Any) = { $ctx.context.getWriter.write(arg.toString) ; $ctx.context.getWriter.write('\n') }"""
            case name      =>
              s"""def $name = $ctx.$name
                  def $name_=(x: Object) = $ctx.$name = x"""
          }).mkString(preamble, "\n", "\n")
```

The `$name_=` does not currently mean `x_=` as it ought.

Now I must squander a pair of braces. Then what will hold my pants up?

**Comment by SethTisue** [comment]
Since the gate stands open, as usual, and the gatekeeper steps to one side, the man stoops to peer through the gateway into the interior. Observing that, the gatekeeper laughs and says: “If you are so drawn to it, just try to go in despite my veto. But take note: I am powerful. Yet I am only the least of the gatekeepers.”

**Comment by som-snytt** [comment]
Now I've forgotten how Dorothy got in to see the wizard. Did she gate-crash?

**Comment by SethTisue** [comment]
putting this on hold while we hash out, over at https://issues.scala-lang.org/browse/SI-9509, whether a change like this is even wanted

**Comment by SethTisue** [comment]
thanks, Som, for your effort and patience on this.

now let's sit down for a delicious meal of hash.

**Pull request closed without merging**
