### PR TITLE
Introduce Unliftable for Quasiquotes

### PR DESCRIPTION
**Pull request by densh**
Resubmission of https://github.com/scala/scala/pull/3118 with additional bugfixes for SI-8008,  SI-8016, SI-8009, SI-6842, SI-7979, SI-7980, SI-7996, SI-7789 and SI-7154. Best viewed per-commit. 

review by @retronym @xeno-by

### CODE REVIEW

**Comment by densh** [comment]
Wow, it finally builds as it should. Last commit in the list is actually green too if you click on it.

**Comment by retronym** [comment]
LGTM. Well constructed sequence of commits.

In addition to the my small suggestions above (which could be submitted in a followup, could you please expand the documentation: http://docs.scala-lang.org/overviews/macros/quasiquotes.html ?

**Comment by xeno-by** [comment]
@retronym @densh See my comments above

**Comment by densh** [comment]
PLS REBUILD/pr-scala@e9efd08

**Comment by densh** [comment]
PLS REBUILD/pr-scala@a83fe95

**Comment by densh** [comment]
PLS REBUILD/pr-scala@cf19f82

**Comment by densh** [comment]
PLS REBUILD/pr-scala@0047a96

**Comment by densh** [comment]
IDE integration really hates this pull request.

**Comment by retronym** [comment]
rebase it on master.

**Pull request closed without merging**
