### PR TITLE
Merge 2.12 to 2.13

### PR DESCRIPTION
**Pull request by lrytz**
```
$> git log HEAD --oneline -n 1 | cat
f093692f6e Merge pull request #10064 from som-snytt/issue/using

$> git log upstream/2.12.x --oneline -n 1 | cat
a23aabe49e Merge pull request #10075 from som-snytt/backport/using-args

$> export MB=$(git merge-base HEAD upstream/2.12.x)

$> git log --graph --oneline $MB..upstream/2.12.x | cat
*   a23aabe49e Merge pull request #10075 from som-snytt/backport/using-args
|\
| * 4424bdcf29 Accept and ignore using in args
|/
*   e8c390ae91 Merge pull request #10060 from SethTisue/sbt-1.7
|\
| * 3f0b62c8d2 sbt 1.7.1 (was 1.6.2)
* |   cbd995f72d Merge pull request #10073 from SethTisue/actions-sbt-cache
|\ \
| * | 1a78d3ede7 simplify Actions config with setup-java@v3 caching support
|/ /
* |   1823f5c46b Merge pull request #10028 from sjrd/preserve-patmat-trees-for-backend
|\ \
| |/
|/|
| * 2190befafd Prevent Erasure from pushing an adapt onto matchEnd labels.
| * b3a2a1c01f Remove a useless transform in LambdaLift, which damages patmat trees.
| * 85f5153e0d Add more bytecode tests with the status quo of codegen control flow.
* |   e3c1d4125c Merge pull request #10063 from lrytz/auto-application-attachment
|\ \
| * | a7433f80c4 Add a tree attachment to mark auto-applications
|/ /
* |   d0a9593d65 Merge pull request #10035 from scala-steward/update/2.12.x/jackson-core-2.13.3
|\ \
| |/
|/|
| * 615d87f0d7 Update jackson-annotations, jackson-core, ... to 2.13.3 in 2.12.x
*   689d72c0ce Merge pull request #10045 from lrytz/t12605
|\
| * 32854b6ab1 Only keep static members when looking up java static members
*   156b5aab83 Merge pull request #10052 from scala/revert-10049-travis-no-truncate
|\
| * 14c0f3591d Revert "Sleep after travis failure to avoid truncated logs"
|/
*   9d24f42f0b Merge pull request #10049 from lrytz/travis-no-truncate
|\
| * 8cc2447eb1 Sleep after travis failure to avoid truncated logs
* e1df25ce4c Merge pull request #10050 from retronym/topic/explicit-types-for-tags
* 159ca45f64 Explicitly type some implicit vals in the compiler

$> git merge d0a9593d65 -s ours
$> git merge e8c390ae91
$> git merge a23aabe49e -s ours
```

### CODE REVIEW

**Comment by lrytz** [comment]
@sjrd https://github.com/scala/scala/pull/10028 merged forward well, but the bytecode tests needed adjustments, see last commit. wdyt?

**Comment by sjrd** [comment]
> @sjrd #10028 merged forward well, but the bytecode tests needed adjustments, see last commit. wdyt?

I'm not sure why the bytecode is worse in 2.13 than in 2.12, but it seems orthogonal to the two improvements. The main features that the improvements brought in 2.12 can also be seen in the 2.13 final bytecode:

* For `m4`, we see the `IRETURN` in each of the cases.
* For `PatmatAdaptMatchEnd`, we see that there is no `STORE ; JUMP ; LABEL ; LOAD` sequence, and instead there is only `JUMP ; LABEL`.

So I think this is fine as is.

**Comment by lrytz** [comment]
Seems 2.12 rewrites `scala.Nil` to `collection.immutable.Nil`, but not 2.13.x (nudge @som-snytt, follow-up for https://github.com/scala/scala/pull/10054 / https://github.com/scala/scala/pull/9969 ?)

**Pull request merged**
