### PR TITLE
Remove ICode (re-submission)

### PR DESCRIPTION
**Pull request by lrytz**
Re-submission of #4830. The first commit is the same, and it LGTM. For the rest, review by @soc.

### CODE REVIEW

**Comment by lrytz** [comment]
build is green now :)

**Comment by soc** [comment]
@lrytz Wow, great! Thanks for the cleanup, you solved all the stuff that I wasn't sure how/if it can be removed/merged. :-)

**Comment by lrytz** [comment]
@soc so LGTY? BTW, i was wondering if there were not any other tests that depend on ICode - did you rewrite / move to pending all of them in https://github.com/scala/scala/pull/4814?

**Comment by soc** [comment]
LGTM, sorry. :-) I think most ICode tests were already taken care of in #4814, but there weren't many to begin with ...

**Comment by lrytz** [comment]
Thanks for your work! I also finished re-writing the disabled tests, but that patch depends on getting #4837 in first, because that cleans up the redundant stores / loads you observed in https://github.com/scala/scala/pull/4814/files#diff-ec86a146d335b3385d7b4046aa4712fc.

**Pull request merged**
