### PR TITLE
SI-7591 Migrate command-line parsing to s.t.cmd

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
If the test suite agrees, I think this should be pretty much good to go.

Review by @som-snytt, please.

**Comment by som-snytt** [comment]
Without DemoSpec, isn't the API impossible to fathom? Unless partest is the new demo.

Also, as an observation, ConsoleRunner looks strange with the clunky Spec with Instance.  I would rather see it on the companion object, or at least the companion could do `new ConsoleRunner { val parsed = ??? }`.  Not a big deal.

Anyway, I'm sure that if paulp were still with us, he would be pleased to see this stuff get some exercise.  But maybe wherever he is, he is still looking down on us, or looking up at us, as the case may be.

**Comment by som-snytt** [comment]
> If the test suite agrees

No one ever says, Review by Jenkins.

**Comment by soc** [comment]
Regarding `optPos`: That's the test/files/pos folder with a few thousand tests in it.

Regarding `DemoSpec`: I think the documentation needs to be improved, but shipping Demo applications with the compiler is not the right approach, imho ... maybe we should move the Demo to the test suite?

**Comment by som-snytt** [comment]
I thought you don't need `val optPos` (for example) because you get the list of kinds to run from `standardKinds filter parsed.isSet`, so you never ask if optPos.  Right?  `isSet` looks up in the args map, a val would be a convenience method.

You're right about not shipping demo; I don't suppose moving it to the scala-dist examples?  Or just putting it in a big comment block on Spec or wherever.  Or maybe -- make it a junit test!

Or maybe spin it off so the paulption community can take over maintenance...

**Comment by som-snytt** [comment]
So there are one or two would-be-nices, but not a blocker for a LGTM.

**Comment by soc** [comment]
Regarding scala-dist examples: I'd prefer to not add anything to that, because I'd prefer just deleting them completely. Not having them would be a net improvement over the current state.
If these code examples are the best we can come up with ... we have a huge problem.

**Comment by adriaanm** [comment]
Agreed on the examples. They'll be removed from the 2.11 distro.

**Comment by adriaanm** [comment]
LGTM!! Thanks very much.

**Comment by som-snytt** [comment]
> Unless partest is the new demo.

Actually, partest was the old demo!  albeit myopia-inducing.

https://github.com/scala/scala/commit/e93c1a93a2c8a40265b34bb9f1dd61b9470c908d

Introduces scala.tools.cmd providing command line tool infrastructure.
For a quick look at what can be done, see

  scala.tools.cmd.Demo

For a more involved, potentially eye-straining look, see

  scala.tools.partest.PartestSpec

To experience it through the eyes of Joe Partest User, run

  test/partest

Review by community.

**Pull request merged**
