### PR TITLE
SI-8642 Enable OSGi tests under Java 8

### PR DESCRIPTION
**Pull request by retronym**
Details in the commit messages.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @soc or @rkrzewski, please.

**Comment by adriaanm** [comment]
the worker is out of disk space.. please excuse the dust while I attach an EBS volume

**Comment by adriaanm** [comment]
You'll have to rebase on #4268 -- hopefully should work then.

**Comment by retronym** [comment]
See: https://github.com/adriaanm/scala-jenkins-infra/pull/14 for an attempt to fix the build errors.

**Comment by adriaanm** [comment]
Yeah! :fireworks:

**Comment by adriaanm** [comment]
LGTM!

**Comment by rkrzewski** [comment]
LGTM

**Pull request merged**
