### PR TITLE
SI-8394 Add zip method to Option [jvican]

### PR DESCRIPTION
**Pull request by jvican**
So this is the active pull request of #4437.
Review by @SethTisue.

### CODE REVIEW

**Comment by SethTisue** [comment]
I will try to figure out where the test failure is coming from.

**Comment by SethTisue** [comment]
I think the failure is probably real (I am able to reproduce it locally). it could be some unexpected consequence of this change not being source compatible. in Scala 2.11 we have:

``` scala
scala> Some(1).zip(Some("foo"))
res0: Iterable[(Int, String)] = List((1,foo))
```

but after this change we have:

``` scala
scala> Some(1).zip(Some("foo"))
res0: Option[(Int, String)] = Some((1,foo))
```

perhaps there is existing code in the compiler/library somewhere which this breaks, which then shows up in the scalap failure.

we might have to rethink whether we can accept this change for 2.12 given the 2.12 promise of "full backward source compatibility" with 2.11. and even for 2.13 it could be questionable. @retronym observes: "We had the same issue on 2.10 when we added something similar to option (flatten, I think). It was a big PITA to fix up in the code base I was working on. Small changes after the fact to widely used datatypes tend to be costly"

**Comment by SethTisue** [comment]
I did try to see if the existing code in the Scala repo was using `zip` on `Option`, but failed to turn up anything. I tried removing `option2Iterable` from `Option.scala` and looking at all the resulting compile errors to see if any of them involved `zip` calls, and I didn't see any.

@retronym I'm curious if you think there is any other possible way that this change could be resulting in the scalap error we're getting

**Comment by retronym** [comment]
Please rebase this on the tip of the 2.12.x branch. I believe the test failure will go away then.

(The test was removed in https://github.com/scala/scala/commit/8d2d3c702d2010d40ed6facb771add48999216c1)

**Comment by jvican** [comment]
I have rebased on top of the last commit on the 2.12.x branch. Is that okay?

**Comment by jvican** [comment]
I'm curious. What was the error that caused that weird behavior?

**Comment by SethTisue** [comment]
on the question of the desirability of the change for 2.12: I'll bring it up at the next Scala team meeting.

**Comment by SethTisue** [comment]
we discussed this and decided that it doesn't make sense for us to accept this in 2.12. it changes the meaning of existing code, in a release where we've already committed not to do that unless really necessary, and the benefit, while real, isn't that great.

the change might still have a chance in 2.13. its chances would be improved if either or both of these come true:
- by then we have a code-rewriting tool that helps mitigate the effect of breaking changes by providing automating assistance with migrating existing code
- it turns out that we're changing a bunch of Option and/or collections stuff in 2.13 anyway, and so it's easier for small-ish changes like this to get in under that umbrella

so, I am sorry! I should have realized earlier in the review process that this change was problematic — that could have spared @kubudi and @jvican some work.

**Comment by jozic** [comment]
@SethTisue is it a good time to resurrect this and accept in 2.13.x?

**Comment by SethTisue** [comment]
@jozic yes, I think so

**Comment by jozic** [comment]
@jvican Do you want to reopen this PR?

**Comment by jvican** [comment]
Yeah, this has been reopened and assigned to 2.13.x. I'll rebase it when I get some time.

**Comment by jozic** [comment]
oh, so we can get it in 2.12.5? that would be cool

**Comment by SethTisue** [comment]
not in 2.12.5 — in 2.13

**Comment by SethTisue** [comment]
@jvican interested in returning to this...?

**Comment by jvican** [comment]
Will try to rebase it successfully in the future. Putting this on the backburner for now.

**Pull request closed without merging**
