### PR TITLE
An ant property to skip building docs

### PR DESCRIPTION
**Pull request by retronym**
It can be situationally useful to run:

```
ant -Dskip.docs=1 dist-maven
```

When troubleshooting problems that require creation of a distribution, such as
pr-integrate-partest.

Scaladoc isn't incremental, so you burn a few minutes for a single file change
to the compiler or library.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @xeno-by (I'm sure you felt this pain, too.)

**Comment by xeno-by** [comment]
Yes, indeed. I just commented out that fragment, but your solution is much better. Thanks!

It looks like the first line after the if-not is misaligned, but otherwise lgtm.

**Comment by retronym** [comment]
contributed the desired whitespace

**Comment by paulp** [comment]
Thank you god for answering my prayers through your vessel @retronym.

**Pull request merged**
