### PR TITLE
SI-8316 SI-8318 SI-8248 reintroduces resetAllAttrs

### PR DESCRIPTION
**Pull request by xeno-by**
Unfortunately, due to the aforementioned bugs we have to delay our triumph
over resetAllAttrs.

Therefore, I'm rolling back the internal changes to scalac introduced in
https://github.com/scala/scala/pull/3485. Our public reflection API interface
in Scala 2.11 is still going to contain only resetLocalAttrs, but both
the reifier and the label typechecker are too heavily addicted to resetAllAttrs
to do away with it right now.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by xeno-by** [comment]
This + https://github.com/slick/slick/pull/686 makes slick work with RC1. Would be nice if we could run dbuild to verify that.

**Comment by szeiger** [comment]
Did you try the official 2.11 branch or retronym's without the part in QueryableTest that doesn't typecheck since M8?

**Comment by retronym** [comment]
LGTM. I'm going to merge this, then we are back in a state to characterize that last troublesome part of `QueryableTest`.

**Comment by retronym** [comment]
@szeiger I am building https://github.com/slick/slick/pull/686 against this PR now https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-retronym/

It also enables the tests for the continuations plugin, which was the subject of https://issues.scala-lang.org/browse/SI-8318.

**Comment by xeno-by** [comment]
Jason, Stefan, that last troublesome part of QueryableTest is also fixed.

**Comment by retronym** [comment]
Sweet. Continuations test suite compiles as per-M8 and pases for me locally. They failed on Jenkins for reasons described: https://github.com/retronym/community-builds/commit/964debeb52

**Comment by adriaanm** [comment]
Sweet indeed!

**Pull request merged**
