### PR TITLE
SI-8170 Fix regression in TypeRef#transform w. PolyTypes

### PR DESCRIPTION
**Pull request by retronym**
Regressed in SI-8046 / edc9edb7, by my hand.

At the time, I noticed the problem: transform wasn't accounting
for the potential Poly-Type-ness of its argument, and this would
lead to under-substituted types. The commit comment of edc9edb7
shows an example.

But the remedy wasn't the right one. The root problem is
that a TypeMap over a PolyType can return one with cloned
type parameter symbols, which means we've lose the ability
to substitute the type arguments into the result.

This commit detects up front whether the type-under-transform
is a PolyType with the current TypeRef's type parameters, and
just runs the `asSeenFrom` over its result type.

Review by @adriaanm

### CODE REVIEW

**Comment by retronym** [comment]
ping @adriaanm Do you need me to investigate any of the context of this method to make a call? This one is visible in Scalaz (although they have commented out the test code that blows up.)

**Comment by adriaanm** [comment]
Could you add a TODO comment that we should revisit this -- I agree this is an improvement over the status quo, but would (conceptually) like to get to the bottom of it later.

Then, LGTM.

**Comment by retronym** [comment]
@adriaanm so commented.

**Comment by adriaanm** [comment]
Thanks.

**Pull request merged**
