### PR TITLE
Merge from 2.12.x to 2.13.x

### PR DESCRIPTION
**Pull request by szeiger**
This is the next batch of (mostly non-)merges following https://github.com/scala/scala/pull/8763.

```
$ git log --graph --oneline 7da8ce26ec1f026ec9a8dd295894df49b530e56c..upstream/2.12.x
*   e1e2bfeaa9 Merge pull request #8778 from retronym/ticket/sd674
|\
| * 98a5944d4d TreeMap is serialization compat with 2.12.10 again
* |   da1bf678e8 Merge pull request #8772 from hrhino/backport/8670
|\ \
| * | d4e90625fb [backport] Build intellij task: don't prompt for confirmation (#8670)
* | |   7ca43d5e7e Merge pull request #8776 from hrhino/topic/align
|\ \ \
| * | | c90c71634f Encourage alignment
| |/ /
* | |   ed743e5be5 Merge pull request #8770 from hrhino/t9908
|\ \ \
| * | | 552510050a Emit advice that compiles
|  / /
* | |   d1e9ac0cc2 Merge pull request #8769 from SethTisue/tweak-8732
|\ \ \
| |/ /
|/| |
| * | 48d3ee23e3 partially revert #8732 to remove problematic isEmpty checks
|/ /
* |   49cec62535 Merge pull request #8764 from retronym/topic/hashmap-merge-regression
|\ \
| |/
|/|
| * cf3a6f1874 Align {add,merge}{Common,Distinct}.
| * 0c62e21014 Fix regression in HashMap.{merge, ++}
|/
*   f139b61e8e Merge pull request #8759 from SethTisue/comment-mini-bootstrap
|\
| * 0469b597b8 improve doc of bootstrapping in PR validation on Travis-CI
*   154215bc18 Merge pull request #8755 from retronym/review/8735
|\
| * 398a891c02 Don't populate Context.implicits for Java sources
| * ca7dc4d597 Use Java semantics for imports in .java files
* ab4d97e87b Merge pull request #8732 from rorygraves/mike/2.12.x_quickTraversable
* 501533adeb remove some refs in TraversableOnce

$ git merge -s ours 154215bc18
Merge made by the 'ours' strategy.

$ git merge f139b61e8e
Auto-merging .travis.yml
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1343 and retry the command.
Merge made by the 'recursive' strategy.
 .travis.yml | 5 +++++
 1 file changed, 5 insertions(+)

$ git merge -s ours 49cec62535
Merge made by the 'ours' strategy.

$ git merge -s ours d1e9ac0cc2
Merge made by the 'ours' strategy.

$ git merge ed743e5be5
Auto-merging test/files/presentation/infix-completion2.check
CONFLICT (content): Merge conflict in test/files/presentation/infix-completion2.check
Auto-merging test/files/presentation/infix-completion.check
CONFLICT (content): Merge conflict in test/files/presentation/infix-completion.check
Auto-merging test/files/neg/logImplicits.check
CONFLICT (content): Merge conflict in test/files/neg/logImplicits.check
Auto-merging test/files/neg/abstract-report2.scala
CONFLICT (content): Merge conflict in test/files/neg/abstract-report2.scala
Auto-merging test/files/neg/abstract-report2.check
CONFLICT (content): Merge conflict in test/files/neg/abstract-report2.check
Auto-merging src/reflect/scala/reflect/internal/Symbols.scala
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1343 and retry the command.
Automatic merge failed; fix conflicts and then commit the result.

$ git commit
[2.13.x 25107a110c] Merge commit 'ed743e5be5' into 2.13.x

$ git merge -s ours 7ca43d5e7e
Merge made by the 'ours' strategy.

$ git merge -s ours da1bf678e8
Merge made by the 'ours' strategy.

$ git merge -s ours e1e2bfeaa9
Merge made by the 'ours' strategy.
```

I skipped 7ca43d5e7e which is from https://github.com/scala/scala/pull/8776. 2.13.x currently does not have any of the code style configuration that was updated by this PR. Did we accidentally skip an earlier PR that introduced it or is it no longer relevant in 2.13.x?

### CODE REVIEW

**Comment by dwijnand** [comment]
> Did we accidentally skip an earlier PR that introduced it or is it no longer relevant in 2.13.x?

None of the above.  When taking the upgrade to sbt 1.3 that happened on 2.13.x (#8525), when backporting to 2.12.x (#8660), it appeared:  https://github.com/scala/scala/pull/8660/commits/e0d9ce6ce5bd3b494dfee4dcd781120bf6bd3086#diff-d2b3a58f33ed1308a0d41d44ed018ea2!

**Comment by szeiger** [comment]
Apparently you can't trust the PR/branch data that github shows. The commit says "2.13.x (#8660)" but this PR was really merged into 2.12.x.

**Comment by dwijnand** [comment]
Yeah, you're right.  I'm not even sure why.  Locally the info is right:

```
$ git branch --contains b8c33ad8f1d1238bc03c148854972522f0357f44
  2.12.x
  2.12/annotation-parsing-and-Deprecated
* 2.12/repl/class-based/outer-pointers
+ 2.13.x
  clarify-minus-e-and-howtorun-in-repl
```

**Comment by dwijnand** [comment]
@hrhino you might want to resubmit #8776 to 2.13.x.

**Comment by hrhino** [comment]
Thanks for the reminder. #8809

**Pull request merged**
