### PR TITLE
SI-4997 deprecate StringLike.linesIterator for StringLike.lines

### PR DESCRIPTION
**Pull request by Ichoran**
Deprecated.  lines is by far more consistent with the rest of the naming in the library.

### CODE REVIEW

**Comment by som-snytt** [comment]
Whew.  Thank goodness.

**Comment by paulp** [comment]
You're not going to do anything about this?

```

scala> import scala.sys.process._
import scala.sys.process._

scala> "abc".lines
<console>:11: error: type mismatch;
 found   : String("abc")
 required: ?{def lines: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method augmentString in object Predef of type (x: String)scala.collection.immutable.StringOps
 and method stringToProcess in trait ProcessImplicits of type (command: String)scala.sys.process.ProcessBuilder
 are possible conversion functions from String("abc") to ?{def lines: ?}
              "abc".lines
              ^
<console>:11: error: value lines is not a member of String
              "abc".lines
                    ^
```

**Comment by som-snytt** [comment]
`-Xfuture` ought to turn deprecated API into elidables.

```
scala> import scala.sys.process._
import scala.sys.process._

scala> "abc".lines
<console>:11: error: type mismatch;
 found   : String("abc")
 required: ?{def lines: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method augmentString in object Predef of type (x: String)scala.collection.immutable.StringOps
 and method stringToProcess in trait ProcessImplicits of type (command: String)scala.sys.process.ProcessBuilder
 are possible conversion functions from String("abc") to ?{def lines: ?}
              "abc".lines
              ^
<console>:11: error: value lines is not a member of String
              "abc".lines
                    ^

scala> :se -Xfuture

scala> "abc".lines
res0: Iterator[String] = non-empty iterator
```

Isn't the future, like, just around the corner?

Maybe `-Xfuture:strict`.

**Comment by Ichoran** [comment]
Paul, I'd love to just change Process outright without going through a deprecation cycle, but since we've said we deprecate things before removing them, I'm deprecating.  (That's on SI-5994.)

**Comment by paulp** [comment]
By "do anything about" I only meant deprecating something - I didn't realize it would be in a separate PR.

**Comment by adriaanm** [comment]
@som-snytt, I wouldn't go as far as eliding them, but would you like to invent an -Xfuture where deprecated members are invisible to the type checker? (They should still be emitted for binary compatibility, but implicit search should not pick them, and typedSelect should pretend they're not there either.)

**Comment by som-snytt** [comment]
@adriaanm let me get out my "invent the -Xfuture" t-shirt.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
