### PR TITLE
Merge 2.10.x into master

### PR DESCRIPTION
**Pull request by gkossakowski**
The merge started to fail mainly due to 2.10.3 release which modified `build.number`. Other than that, the merge was trivial.

### CODE REVIEW

**Comment by gkossakowski** [comment]
PLS SYNCH

**Comment by gkossakowski** [comment]
NO LITTER!

**Comment by gkossakowski** [comment]
PLS REBUILD/pr-scala@7aa7966

**Comment by retronym** [comment]
LGTM.

**Comment by gkossakowski** [comment]
@retronym: thanks! Do you understand those build failures we were seeing?

**Comment by retronym** [comment]
Nope.

**Comment by gkossakowski** [comment]
I believe there are spurious (those are commits already tested in 2.10.x branch) but maybe @adriaanm wants to have a look? I couldn't understand the output coming from bash script.

**Comment by adriaanm** [comment]
looking now

**Comment by adriaanm** [comment]
Those errors come from jenkins (the archive artifact step) and can be ignored. Not sure where they come from.

```
ERROR: No artifacts found that match the file pattern "scala/build/junit/TEST-*,scala/build/osgi/TEST-*". Configuration error?
ERROR: 'scala/build/junit/TEST-*' doesn't match anything: 'scala' exists but not 'scala/build/junit/TEST-*'
```

**Comment by retronym** [comment]
Those are fixed as of today. I added that step recently. Turns out some
builds are noops and generate no logs so the absence of the logs should not
fail the build.

**Pull request merged**
