### PR TITLE
Fix typo in log message.

### PR DESCRIPTION
**Pull request by darabos**

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks and welcome, @darabos! Please sign the [Scala CLA](http://typesafe.com/contribute/cla/scala) so we can include your contribution.

**Comment by darabos** [comment]
Signed, thanks!

**Comment by adriaanm** [comment]
Thank _you_!

**Comment by som-snytt** [comment]
Wait a sec, that's a blocker?

**Comment by adriaanm** [comment]
I was careful to specify _code_ PRs must fix blocker bugs. I also said (somewhat more explicitly) that fixes to documentation are always welcome. I won't hold up typo fixes like this since the only regressions they can cause are caught by PR validation.

**Comment by som-snytt** [comment]
OK, thx. Not trying to be snide, but wondering about when it's ok to PR again.  Meanwhile, I'll look for typos and obsolete example code.

**Comment by adriaanm** [comment]
Thanks :-) I'm rooting for a short RC cycle and timely creation of the 2.12.x branch!

**Comment by som-snytt** [comment]
That's when I'll resubmit `-language:foo` verify.  That could almost qualify as documentation...

**Pull request merged**
