### PR TITLE
Don't crash if cpsParam is not on the classpath.

### PR DESCRIPTION
**Pull request by dragos**
When checking if a piece of code needs the continuations plugin, the cpsParam classes may not be on the class path. Assume it does not need it in that case.

### CODE REVIEW

**Comment by jsuereth** [comment]
The cpsParam classes are part of the compiler, so they are only not compiled when working with the Scala library right?   funny we have to hack that use case in....

**Comment by dragos** [comment]
@jsuereth I'm not sure I understand your comment. I'll try to explain better what failed. That code path is taken during normal compilation just to print an error message if the `cps` plugin is not enabled, but the source code has `cps` types. 

If the classpath does not contain the cps plugin library, it crashes with `MissingRequirementError` (missing a `cps` type), even though your code never mentions it, nor needs it. This happened to me when compiling the standard library in the IDE, or when passing the `locker` library as the Scala library for a project.

**Comment by jsuereth** [comment]
@dragos That was my comment.   The only time I can see `@cps` and friends not on the classpath is when boot-strapping scala.   I just wanted to make sure I understood the fix.

**Comment by adriaanm** [comment]
LGTM

did you investigate the alternative fix of making hasCPSParamType never fail and putting in an explicit check that the cps classes are available when we actually need them?

these dual-purpose, supposedly side-effect-free methods that do other checks on the side and blow up are not good coding practice IMO

**Comment by dragos** [comment]
I did, but it seemed more trouble than it's worth. The CPS classes are lazy vals that throw on access if the required class is not there, so I'd need to refactor them, or duplicate their names and test for their existence separately. It seemed too much code for an exceptional case.

**Pull request merged**
