### PR TITLE
Use Using in ProcessTest

### PR DESCRIPTION
**Pull request by som-snytt**
Removes the windows disable from two tests, but untested.

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
LGTM, nice one.

**Comment by SethTisue** [comment]
not that one green run proves much, but let's put one in the bag anyway:
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/1347/ (queued)

**Comment by som-snytt** [comment]
`StandardOpenOption.DELETE_ON_CLOSE` couldn't hurt.

**Comment by SethTisue** [comment]
@som-snytt you want to try that, or should I just hit "merge"?

**Comment by som-snytt** [comment]
@SethTisue you may merge. I can follow up. What's the worse that can happen? A global pandemic?

**Comment by NthPortal** [comment]
the fact that `Using` is actually getting used makes me immensely happy 😄

**Comment by SethTisue** [comment]
[one failure so far](https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-windows/1358/):

```
[error] Test scala.sys.process.ProcessTest.t10823_short_circuit failed: java.lang.AssertionError: Expired after dormancy period 21250 waiting for termination condition test result, took 22.015 sec
[error]     at scala.tools.testkit.AssertUtil$.assertZeroNetThreads(AssertUtil.scala:240)
[error]     at scala.tools.testkit.NoTrace.run(AssertUtil.scala:273)
[error]     at scala.tools.testkit.NoTrace.apply(AssertUtil.scala:291)
[error]     at scala.sys.process.ProcessTest.t10823_short_circuit(ProcessTest.scala:125)
[error]     ...
```

**Comment by som-snytt** [comment]
Worth it making nth happy.

Edit: reminding myself, previously, it avoided the test altogether; but on the notion that it was failing because of deleting temp files "still in use", we avoided deleting temp files and re-enabled it; but really it fails because the "mock process" doesn't complete.

The test is file cat && dummy redirected to output file. The file does not exist, and it tests that the dummy doesn't run. The only live things are the I/O threads. Since fixing that is non-trivial work for no benefit, first I'll just PR restoring the exclusions Seth had installed.

**Pull request merged**
