### PR TITLE
fixes for class tags and manifests

### PR DESCRIPTION
**Pull request by xeno-by**
review by @jsuereth

### CODE REVIEW

**Comment by xeno-by** [comment]
@jsuereth note the second commit. I think this decision makes sense. On the one hand, it will break backward compatibility. On the other hand, why do we have to be compatible with buggy behaviors?

**Comment by jsuereth** [comment]
Just curious:  what exactly does this break and what was the buggy behavior?

I assume before you could mistakenly cast an anyref to Null and similar for Nothing?   Fixing that = awesome, and lgtm.

My question is what will break?   It seems like we should be OK here, but curious what I'm missing.

**Comment by xeno-by** [comment]
The linked discussion in the commit message sheds some light: https://groups.google.com/forum/#!topic/scala-internals/Y0ALGo7QPqE.

In short, previously you could have a type parameter inferred to Nothing and then successfully use the erasure of the generated manifest to perform a cast. Now this will blow up.

**Comment by jsuereth** [comment]
It seems, for that issue, we should see if we can get the type inference
not to resolve Nothing, but Int....

I think this LGTM.    It's a type inference issue they worked around with
misbehaving manifests.  Let's focus the attention on the right problem.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Pull request merged**
