### PR TITLE
Restore two blank lines bailing the REPL

### LINKED ISSUE #12266: JLine 3: restore behavior: "You typed two blank lines.  Starting a new command."?
this no longer triggers, but there's less need for it now that we have multiline editing, so not a blocker ... I think?

### PR DESCRIPTION
**Pull request by dwijnand**
LineReaderImpl handles EOFError (which is a subclass of SyntaxError) as
needing to read more input.  So in order for our non-JLine-specific "You
typed two blank lines. Starting a new command." behaviour in ILoop to
function we need to bail (with a regular SyntaxError) if we read two
newlines.

Perhaps we should also bail if we fail to parse (Error) but I left that
as is, to avoid breaking something.

Fixes https://github.com/scala/bug/issues/12266

### CODE REVIEW

**Comment by som-snytt** [comment]
I can't tell by looking if the blank lines test will work on Windows. (Sorry to steal the thunder of anyone who would have created the ticket later.)

Otherwise, nice tweak!

**Review by SethTisue — APPROVED** [review]
LGTM. (Dale and I worked on this together.)

**Comment by SethTisue** [comment]
> I can't tell by looking if the blank lines test will work on Windows

over in ILoop.scala we have long had:

```
        case Incomplete if in.interactive && code.endsWith("\n\n") =>
          echo("You typed two blank lines.  Starting a new command.")
          None
```

so it seems like it should work here as well, but it's hard to be 100% sure, a priori, that the strings being tested haven't been somehow processed differently. Other REPL changes will also land in 2.13.5, so I'm inclined to do a single round of manual testing on Windows, later.

Incidentally, it is admittedly a bit odd to have the same `endsWith` check in two places. The check in `Reader` is used to tell JLine to stop requesting more input. And then the second check, in `ILoop`, downstream, prevents any further processing of the incomplete input. All `ILoop` gets is an `Incomplete`, without further information. Is this worth DRYing? As far as I can see, that would involve modifying `scala.tools.nsc.interpreter.Results` to carry the additional information, but meh -- I wouldn't be opposed, but I'm not volunteering, either :-)

**Comment by dwijnand** [comment]
> Incidentally, it is admittedly a bit odd to have the same `endsWith` check in two places. The check in `Reader` is used to tell JLine to stop requesting more input. And then the second check, in `ILoop`, downstream, prevents any further processing of the incomplete input. All `ILoop` gets is an `Incomplete`, without further information. Is this worth DRYing? As far as I can see, that would involve modifying `scala.tools.nsc.interpreter.Results` to carry the additional information, but meh -- I wouldn't be opposed, but I'm not volunteering, either :-)

Still wouldn't help as JLine's readLine interface still gives you a String after you did all that hard work in Parser returning a ParsedLine (and even then, ParsedLine is Success only).  I've always been pro-DRY, but it's 1 line...

**Pull request merged**
