### PR TITLE
Fix for SI-5385.

### PR DESCRIPTION
**Pull request by hubertp**
Nodes which hit EOF with no whitespace afterward had
wrong position.

Stole commit from @paulp and adapted it to the current state of master. Needed to fix DirectTest as the original commit assumed that we only produce range positions.

Review by @paulp and @dotta.

### CODE REVIEW

**Comment by dotta** [comment]
I believe @misto is a more suited reviewer for this patch.

**Comment by adriaanm** [comment]
why was the build aborted?

**Comment by hubertp** [comment]
don't ask me. there were a bunch of aborts in the queue.

**Comment by paulp** [comment]
I wrote this and never checked it in? What did I do with it?

**Comment by hubertp** [comment]
AFAIK you didn't get +1 from Martin in making rangepos default.

**Comment by paulp** [comment]
Oh, it was mixed up in that commit.  Sigh indeeed.

On Tue, Jul 17, 2012 at 9:46 AM, Hubert Plociniczak <
reply@reply.github.com

> wrote:
> 
> AFAIK you didn't get +1 from Martin in making rangepos default.

**Comment by paulp** [comment]
I have the sudden feeling the build aborts are my doing.

**Comment by paulp** [comment]
https://github.com/scala/scala/pull/934

**Comment by misto** [comment]
Can I download the resulting artifacts from jenkins somewhere or should I build it myself to test the fix?

**Comment by adriaanm** [comment]
Good point. I've configured the pull request validator jenkins job to archive its artifacts. The next successful build should have them available at the link in scala-jenkins's comment.

**Comment by adriaanm** [comment]
I can't explain the build aborts as a partest problem, as other builds have been failing way later than that.
It's also weird it tends to happen after three hours, whereas the time-out was 240 (now upped it to 300 just to see what happens)

**Comment by adriaanm** [comment]
@misto, you can download the artifacts from the jenkins build page: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/595/

**Comment by adriaanm** [comment]
for this to go into M6 it needs to be merged (and thus be signed off by reviewer) today

**Comment by paulp** [comment]
Sorry: it looks spectacularly wonderful to my share of the reviewers, as if the author must be some kind of undiscovered genius.

**Pull request merged**
