### PR TITLE
[SIWIP] Accept case guard without trivial underscore

### PR DESCRIPTION
**Pull request by som-snytt**
`case if condition =>` seems easy and natural.

### CODE REVIEW

**Comment by SethTisue** [comment]
Does the spec already allow this and you’re just bringing the implementation up to date, or what?

If it isn’t already spec’ed this way, it isn’t clear to me that adding flexibility here is worth the loss of uniformity?

**Comment by som-snytt** [comment]
This would be a spec change to make "abuse of match" (as an if-alternative) look prettier.

The underscore doesn't add information and makes for a longer line, especially with slightly longer conditional expressions. Omitting underscore makes it easier to keep the alternatives on one line.

```
v match {
  case p => x
  case _ => if (b1) y else if (b2) z else ???
}
v match {
  case p => x
  case if b1 => y
  case if b2 => z
  case _ => ???
}
```
The syntax is straightforward.

**Comment by lrytz** [comment]
Since the proposal changes the syntax it affects various tools (scala meta, IntelliJ, etc) and needs some wider communication / discussion. Would you like to write a mini-SIP so the proposal and its cost/beneift can be discussed in a meeting?

**Comment by SethTisue** [comment]
closing for inactivity. can be reopened if activity resumes

**Comment by nafg** [comment]
I think it makes things less regular and orthogonal

**Pull request closed without merging**
