### PR TITLE
Value classes fixes

### PR DESCRIPTION
**Pull request by odersky**
I added to me previous pull request a patch that eliminates half boxing. That gets rid of several bad tests, including SI-6385. Review  by @paulp @harrah

### CODE REVIEW

**Comment by odersky** [comment]
PLS REBUILD ALL

**Comment by harrah** [comment]
This+other recent value class pull requests turn the runtime exceptions into compile-time errors, which is good.

However, the error message looks like:

```
N.scala:12: error: bridge generated for member method x: ()C[T] in class C
which overrides method x: ()C[T] in trait AA
clashes with definition of the member itself;
both have erased type ()Object
   def x = this
       ^
```

What the user probably needs to know is

```
a) this is a limitation the user has to workaround and is not a compiler bug
b) the cause
```

For b), the error message identifies the two methods, but is the link to what the user did wrong clear?  Also, that it is a bridge method is somewhat irrelevant to the user, right?  If it is difficult to improve this error message further, I think at least a) should be addressed so that the message says something that conveys "Compiler implementation: you must workaround this by tweaking the relationship between method C.x and AA.x, sorry".  Of course it would be nice to be more precise, but that might be asking too much.

**Comment by odersky** [comment]
I think Paul has volunteered to do something about the error message. If that's all we need to do let's get this pull request in. Things are pliling up around it.

**Comment by paulp** [comment]
True this.  However there is one thing which drives me nuts, which I had to fix.  I opened #1364, which is the same code as this, but with log messages I can actually see.

```
git filter-branch --msg-filter 'par 68' b9fd3f713d..
```

**Comment by paulp** [comment]
I mean, #1365.  So can we please merge that one.  This lgtm and I will follow up on the error.

**Pull request closed without merging**
