### PR TITLE
Use rawflags for checking FINAL flag.

### PR DESCRIPTION
**Pull request by hubertp**
Partially reverts 18efdedfb97de7ca9f6.

Review by @paulp.

### CODE REVIEW

**Comment by paulp** [comment]
Thanks. LGTM, I'll wait for kitteh.

**Comment by lrytz** [comment]
why this change? the commit message doesn't say.

**Comment by paulp** [comment]
It is restoring it to the way it was before the referenced commit.  The reason it was like that is explained in the comment in the source directly above it.

**Comment by lrytz** [comment]
kthx

**Pull request merged**
