### PR TITLE
typeCheck => typecheck

### PR DESCRIPTION
**Pull request by xeno-by**
This method has always been slightly bothering me, so I was really glad
when Denys asked me to rename it. Let’s see how it pans out.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by densh** [comment]
I'm really happy about it being renamed. That capitalized Check never felt right.

**Comment by som-snytt** [comment]
Wikipedia is also uncertain about the orthography.

http://en.wikipedia.org/wiki/Type_system#Type_checking
vs
http://en.wikipedia.org/wiki/Type_system#Static_type-checking

The hyphen is needed because you're not checking "static types" per se but "type-checking, statically."  Of course, the useful results of "static type-checking" are "static types."

I still endorse the camelization "classLoader" and "classPath" because there is also a `resourceLoader` and `filePath`, perhaps.

If the distinction were that we might also perform "name checking," then we would say `checkName` and `checkType`.  But we don't say that, in the way we might say, `loadResource` or `loadClass`.

In English, for instance, we no longer write "to-day".  We are no longer inclined to decompose the agglutination.

The Wikipedia article on agglutination provides a good example that could easily find application in a software development group meeting:

A very popular Turkish agglutination is Çekoslovakyalılaştıramadıklarımızdanmışsınız, meaning "You are said to be one of those that we couldn't manage to convert to a Czechoslovak". This historical reference is used as a joke for the individuals who are hard to change or those who stick out in a group.

**Comment by retronym** [comment]
LGTM, after recent discussion at the Scala meeting.

**Pull request merged**
