### PR TITLE
SAM Functions from scala-java8-compat [ci: last-only]

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
locally i get this alarming outcome:

```
quick.bin:
    [mkdir] Created dir: /Users/luc/scala/scala/build/quick/bin

BUILD FAILED
/Users/luc/scala/scala/build.xml:69: The following error occurred while executing this line:
/Users/luc/scala/scala/build-ant-macros.xml:8: The following error occurred while executing this line:
/Users/luc/scala/scala/build.xml:1126: The following error occurred while executing this line:
/Users/luc/scala/scala/build-ant-macros.xml:331: The following error occurred while executing this line:
/Users/luc/scala/scala/build-ant-macros.xml:350: Could not create type mk-bin due to java.lang.BootstrapMethodError: call site initialization exception
    at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
    at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
    at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
    at scala.sys.BooleanProp$.keyExists(BooleanProp.scala:72)
    at scala.sys.SystemProperties$.bool(SystemProperties.scala:78)
    at scala.sys.SystemProperties$.noTraceSupression$lzycompute(SystemProperties.scala:89)
    at scala.sys.SystemProperties$.noTraceSupression(SystemProperties.scala:89)
    at scala.util.control.NoStackTrace$.<init>(NoStackTrace.scala:31)
    at scala.util.control.NoStackTrace$.<clinit>(NoStackTrace.scala)
    at scala.util.control.NoStackTrace$class.fillInStackTrace(NoStackTrace.scala:22)
    at scala.util.control.BreakControl.fillInStackTrace(Breaks.scala:94)
    at java.lang.Throwable.<init>(Throwable.java:250)
    at scala.util.control.BreakControl.<init>(Breaks.scala:94)
    at scala.util.control.Breaks.<init>(Breaks.scala:29)
    at scala.collection.Traversable$.<init>(Traversable.scala:95)
    at scala.collection.Traversable$.<clinit>(Traversable.scala)
    at scala.package$.<init>(package.scala:40)
    at scala.package$.<clinit>(package.scala)
    at scala.Predef$.<init>(Predef.scala:89)
    at scala.Predef$.<clinit>(Predef.scala)
    at scala.tools.ant.ScalaTool.<init>(ScalaTool.scala:58)
[...]
Caused by: java.lang.invoke.LambdaConversionException: Incorrect number of parameters for static method invokeStatic scala.sys.BooleanProp$.scala$sys$BooleanProp$$$anonfun$2$adapted:(String)Object; 0 captured parameters, 0 functional interface method parameters, 1 implementation parameters
    at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:193)
    at java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:473)
    at java.lang.invoke.CallSite.makeSite(CallSite.java:325)
```

**Comment by lrytz** [comment]
[source code](https://github.com/scala/scala/blob/2.11.x/src/library/scala/sys/BooleanProp.scala#L72):

```
s => s == "" || s.equalsIgnoreCase("true")
```

bytecode:

```
    INVOKEDYNAMIC $init$()Lscala/compat/java8/JFunction1; [
      // handle kind 0x6 : INVOKESTATIC
      java/lang/invoke/LambdaMetafactory.altMetafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
      // arguments:
      ()V, 
      // handle kind 0x6 : INVOKESTATIC
      scala/sys/BooleanProp$.scala$sys$BooleanProp$$$anonfun$2$adapted(Ljava/lang/String;)Ljava/lang/Object;, 
      (Ljava/lang/String;)Ljava/lang/Object;, 
      3, 
      1, 
      Lscala/Serializable;.class, 
      0
    ]
    CHECKCAST scala/Function1
```

The mistake seems to be that the Scala compiler incorrectly selects `$init$` ([which is a default method](https://github.com/scala/scala/blob/640ffe7fceb5d573b2c12a7c7da09bfd751036a0/src/library/scala/compat/java8/JFunction1.java#L10)) as the abstract method of `JFunction1`, whereas it should be `apply` (inherited from `Function1`).

Since we're doing mixed compilation, this is almost certainly a problem of the Java parser. I'll take a look.

**Comment by retronym** [comment]
I think this is my bug in the backend. Try this:

``` diff
diff --git a/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala b/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
index 40ba0c0..06a7027 100644
--- a/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
+++ b/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
@@ -1299,7 +1299,7 @@ abstract class BCodeBodyBuilder extends BCodeSkelBuilder {
       val invokedType = asm.Type.getMethodDescriptor(asmType(functionalInterface), (receiver ::: capturedParams).map(sym => toTypeKind(sym.info).toASMType): _*)

       val constrainedType = new MethodBType(lambdaParams.map(p => toTypeKind(p.tpe)), toTypeKind(lambdaTarget.tpe.resultType)).toASMType
-      val sam = functionalInterface.info.decls.find(_.isDeferred).getOrElse(functionalInterface.info.member(nme.apply))
+      val sam = functionalInterface.info.decls.find(_.isDeferredNotDefault).getOrElse(functionalInterface.info.member(nme.apply))
       val samName = sam.name.toString
       val samMethodType = asmMethodType(sam).toASMType
```

**Comment by retronym** [comment]
Thanks for submitting this PR, BTW. I tried something similar but wasn't able to convince `<scalacfork>` to accept Java sources. I thought this was due to a limitation of our Ant tasks:

https://github.com/scala/scala/blob/v2.11.7/src/compiler/scala/tools/ant/sabbus/ScalacFork.scala#L82-L116

**Comment by lrytz** [comment]
ok, trying now. still, it's probably a bug in JavaParser: the symbol flags should be the same when reading from source or from classfile. `$init$` should not have the `DEFERRED` flag

**Comment by lrytz** [comment]
thanks for the ScalacFork link, i have to check what it chooses to recompile if a subset of the sources is modified.

**Comment by retronym** [comment]
My theory was that the order of the decls was different in joint vs separate compilation, and that the `decls.find` was only working by accident.

**Comment by lrytz** [comment]
The [java parser sets `DEFERRED`](https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/javac/JavaParsers.scala#L512) even if there's a default method. Checking the access flags of a javac-produced classfile, the flag should not be there:

```
  // access flags 0x1
  public default $init$()V
   L0
    RETURN
```

**Comment by lrytz** [comment]
pushed a fix to the java parser - note that the commits show in the wrong order on GitHub, the correct order is

```
* bdbc66c - (HEAD -> jfun, origin/jfun) Copy LambdaDeserializer from scala-java8-compat to scala.runtime (3 minutes ago) <Jason Zaugg>
* 2c0a5e1 - Copy SAM functions from java8-compat to src/library (3 minutes ago) <Lukas Rytz>
* 153beab - Fix Java parser for default methods (3 minutes ago) <Lukas Rytz>
* c8cf9f6 - Allow mixed builds in ant (2 hours ago) <Lukas Rytz>
* 18aa8af - Revert "Add scala-java8-compat to scala-library.jar" (5 hours ago) <Lukas Rytz>
* 80ee730 - (upstream/2.12.x, upstream-writable/2.12.x, scala/2.12.x, 2.12.x) Update README with required ant version on Java 8 (15 hours ago) <Adriaan Moors>
```

**Comment by retronym** [comment]
I have a slight preference to hide `JFunctionN` under `scala.runtime.java8`, rather than `scala.compat.java8`. Maybe this isn't too important as they should only be a temporary addition to the library.

**Comment by retronym** [comment]
```
osgi.core:
    [mkdir] Created dir: /home/jenkins/workspace/scala-2.12.x-validate-test@2/build/osgi
     [copy] Copying 1 file to /home/jenkins/workspace/scala-2.12.x-validate-test@2/build/osgi
      [bnd] # addAll '/home/jenkins/workspace/scala-2.12.x-validate-test@2/build/pack/lib/scala-library.jar' with :,
      [bnd] # addAll '/home/jenkins/workspace/scala-2.12.x-validate-test@2/build/osgi/scala-library.bnd' with ,
      [bnd] Updating classpath after classpathref setting
      [bnd] java.lang.ArrayIndexOutOfBoundsException: 15
      [bnd]     at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:448)
      [bnd]     at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:369)
      [bnd]     at aQute.lib.osgi.Clazz.parseClassFileWithCollector(Clazz.java:359)
      [bnd]     at aQute.lib.osgi.Clazz.parseClassFile(Clazz.java:349)
      [bnd]     at aQute.lib.osgi.Analyzer.analyzeJar(Analyzer.java:1725)
      [bnd]     at aQute.lib.osgi.Analyzer.analyzeBundleClasspath(Analyzer.java:1595)
      [bnd]     at aQute.lib.osgi.Analyzer.analyze(Analyzer.java:124)
      [bnd]     at aQute.lib.osgi.Builder.analyze(Builder.java:306)
      [bnd]     at aQute.lib.osgi.Analyzer.calcManifest(Analyzer.java:301)
      [bnd]     at aQute.lib.osgi.Builder.build(Builder.java:73)
      [bnd]     at aQute.lib.osgi.Builder.builds(Builder.java:970)
      [bnd]     at aQute.bnd.ant.BndTask.executeBackwardCompatible(BndTask.java:180)
      [bnd]     at aQute.bnd.ant.BndTask.execute(BndTask.java:87)
```

**Comment by lrytz** [comment]
yes, i'm looking into this - any intuitive ideas?

**Comment by retronym** [comment]
https://github.com/bndtools/bnd/issues/603

**Comment by lrytz** [comment]
https://issues.apache.org/jira/browse/FELIX-4005

**Comment by retronym** [comment]
The latest is [2.4.1](http://mvnrepository.com/artifact/biz.aQute.bnd/biz.aQute.bnd). We're using 1.50.0.

**Comment by lrytz** [comment]
yeah, the issue you link mentions we need 2.4, i'll give it a try.

**Comment by retronym** [comment]
This PR tentatively LGTM. I won't be around much to continue review for the next few days, but I think if you get through the Ant/SBT pain this ought to go in.

**Comment by lrytz** [comment]
```
      [bnd] # addAll '/Users/luc/scala/scala/build/pack/lib/scala-library.jar' with :,
      [bnd] # addAll '/Users/luc/scala/scala/build/osgi/scala-library.bnd' with ,
      [bnd] 1 ERRORS
      [bnd]  The default package '.' is not permitted by the Import-Package syntax. 
      [bnd]  This can be caused by compile errors in Eclipse because Eclipse creates 
      [bnd] valid class files regardless of compile errors.
      [bnd] The following package(s) import from the default package [scala.collection.generic, scala.sys.process, scala.collection.parallel.mutable, scala.util, scala.collection.parallel.immutable, scala.reflect, scala.concurrent.impl, scala.util.hashing, scala.collection.parallel, scala.collection.convert, scala.io, scala, scala.collection.concurrent, scala.util.control, scala.beans, scala.concurrent.duration, scala.collection, scala.runtime, scala.math, scala.collection.mutable, scala.concurrent, scala.sys, scala.collection.immutable, scala.ref, scala.util.matching]
      [bnd] /Users/luc/scala/scala/build/osgi/scala-library.bnd: bnd failed
```

**Comment by lrytz** [comment]
ok, thanks for your help!

**Comment by lrytz** [comment]
i'm running out of ideas for the bnd issue (see above), maybe @adriaanm knows more? scala-library.jar doesn't have any classfiles in the empty package. can it be due to other files, e.g., `versions.properties`? or due to a dependency of scala-library? what would that be?

**Comment by lrytz** [comment]
closing not to waist jenkins energy

**Comment by adriaanm** [comment]
From a clean (non-optimized) build, osgi.core succeeds for me. I did ant pack.done && ant osgi.done

```
osgi.core:
    [mkdir] Created dir: /Users/adriaan/git/scala/build/osgi
     [copy] Copying 1 file to /Users/adriaan/git/scala/build/osgi
      [bnd] # addAll '/Users/adriaan/git/scala/build/pack/lib/scala-library.jar' with :,
      [bnd] # addAll '/Users/adriaan/git/scala/build/osgi/scala-library.bnd' with ,
      [bnd] # org.scala-lang.scala-library (org.scala-lang.scala-library.jar) 4082 
      [jar] Building jar: /Users/adriaan/git/scala/build/osgi/scala-library-src.jar
     [copy] Copying 1 file to /Users/adriaan/git/scala/build/osgi
      [bnd] # addAll '/Users/adriaan/git/scala/build/pack/lib/scala-reflect.jar' with :,
      [bnd] # addAll '/Users/adriaan/git/scala/build/osgi/scala-reflect.bnd' with ,
      [bnd] # org.scala-lang.scala-reflect (org.scala-lang.scala-reflect.jar) 3049 
      [jar] Building jar: /Users/adriaan/git/scala/build/osgi/scala-reflect-src.jar
     [copy] Copying 1 file to /Users/adriaan/git/scala/build/osgi
      [bnd] # addAll '/Users/adriaan/git/scala/build/pack/lib/scala-compiler.jar' with :,
      [bnd] # addAll '/Users/adriaan/git/scala/build/osgi/scala-compiler.bnd' with ,
      [bnd] # org.scala-lang.scala-compiler (org.scala-lang.scala-compiler.jar) 10360 
      [jar] Building jar: /Users/adriaan/git/scala/build/osgi/scala-compiler-src.jar
[stopwatch] [osgi.core.timer: 16.066 sec]
```

**Comment by adriaanm** [comment]
osgi.done fails, though, since `2.0.0-M2` is not a valid osgi version (scala-swing). Urgh!
It needs to be `2.0.0.M2`.

Hacky fix:

``` diff
diff --git i/build-ant-macros.xml w/build-ant-macros.xml
index 795779193a..b090682fcc 100644
--- i/build-ant-macros.xml
+++ w/build-ant-macros.xml
@@ -488,7 +488,7 @@
           <filter token="SCALA_COMPILER_INTERACTIVE_VERSION" value="${scala-compiler-interactive.version.number}"/>
           <filter token="XML_VERSION"                value="${scala-xml.version.number}" />
           <filter token="PARSER_COMBINATORS_VERSION" value="${scala-parser-combinators.version.number}" />
-          <filter token="SCALA_SWING_VERSION"        value="${scala-swing.version.number}" />
+          <filter token="SCALA_SWING_VERSION"        value="${scala-swing.version.osgi}" />
         </filterset>
       </copy>
       <bnd classpath="${@{project}.jar}" eclipse="false" failok="false" exceptions="true" files="${build-osgi.dir}/${@{project}.name}.bnd" output="${build-osgi.dir}"/>
diff --git i/versions.properties w/versions.properties
index 5fd2ac4b71..ad3d659aee 100644
--- i/versions.properties
+++ w/versions.properties
@@ -25,6 +25,7 @@ scala.binary.version=2.12.0-M1
 scala-xml.version.number=1.0.4
 scala-parser-combinators.version.number=1.0.4
 scala-swing.version.number=2.0.0-M2
+scala-swing.version.osgi=2.0.0.M2
 jline.version=2.12.1
 scala-asm.version=5.0.4-scala-2


```

**Comment by lrytz** [comment]
> From a clean (non-optimized) build, osgi.core succeeds for me

With the revision of this PR? Doesn't work for me, i get the "default package" error.

```
➜  scala git:(jfun) ✗ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by adriaanm** [comment]
yep, f257f66c38

```
➜  scala git:(lrytz-jfun) ✗ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

➜  scala git:(lrytz-jfun) ✗ ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014
```

**Comment by adriaanm** [comment]
I do have `locker.skip=true` in build.properties, but otherwise, I just did `rm -rf build ; ant pack.done ; ant osgi.done`

**Comment by lrytz** [comment]
ah. if you do locker.skip then things change.

**Comment by adriaanm** [comment]
interesting

**Comment by lrytz** [comment]
ah. if you do locker.skip then things change. then you use starr, which doesn't generate indylambda yet

**Comment by adriaanm** [comment]
ok, I'll run with locker and diff the manifests / jars

**Comment by lrytz** [comment]
the diff will be that all closures are compiled differently. so bnd might trip over indylambda. maybe that uses some class in a top-level package?

**Comment by lrytz** [comment]
it seems to be a problem of the generated `$deserializeLambda$` function.

one example is `scala/App$class`. Its bytecode contains this:

```
  private static synthetic $deserializeLambda$(Ljava/lang/invoke/SerializedLambda;)Ljava/lang/Object;
    GETSTATIC scala$divApp$class.$deserializeLambdaCache$ : Ljava/util/Map;
    [...]
```

so it's a static field read of a top-level class. `$div` should obviously be `/`

**Comment by lrytz** [comment]
https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala#L718

**Comment by adriaanm** [comment]
Good find! Shittiest osgi error message ever :-p

**Comment by lrytz** [comment]
pushed a fix, and your scala-swing hack. now fails a bit later:

```
test.osgi:
     [echo] Running OSGi JUnit tests. Output in /Users/luc/scala/scala/build/osgi
     [echo] Test pass 1 of 2 using Apache Felix 4.4.0

BUILD FAILED
/Users/luc/scala/scala/build.xml:1365: Test tools.test.osgi.reflection.toolbox.ReflectionToolBoxTest failed
```

will continue tomorrow

**Comment by adriaanm** [comment]
ok, i'll also have a look

**Comment by adriaanm** [comment]
Upgrading to all the latest shit gets me a little further (no more AME due to logback incompats), but still failing.

``` diff
       <!-- Pax runner -->
-      <property name="pax.exam.version" value="3.5.0"/><!-- Last version which supports Java 6 -->
-      <property name="osgi.felix.version" value="4.4.0"/>
+      <property name="pax.exam.version" value="4.5.0"/>
+      <property name="osgi.felix.version" value="5.0.1"/>
       <property name="osgi.equinox.version" value="3.7.1"/>
       <artifact:dependencies pathId="pax.exam.classpath" filesetId="pax.exam.fileset">
         <dependency groupId="org.ops4j.pax.exam" artifactId="pax-exam-container-native" version="${pax.exam.version}">
@@ -291,11 +291,12 @@ TODO:
         </dependency>
         <dependency groupId="org.ops4j.pax.exam" artifactId="pax-exam-junit4" version="${pax.exam.version}"/>
         <dependency groupId="org.ops4j.pax.exam" artifactId="pax-exam-link-assembly" version="${pax.exam.version}"/>
-        <dependency groupId="org.ops4j.pax.url" artifactId="pax-url-aether" version="2.2.0"/>
-        <dependency groupId="org.ops4j.pax.swissbox" artifactId="pax-swissbox-tracker" version="1.8.0"/>
-        <dependency groupId="ch.qos.logback" artifactId="logback-core" version="1.1.2"/>
-        <dependency groupId="ch.qos.logback" artifactId="logback-classic" version="1.1.2"/>
+        <dependency groupId="org.ops4j.pax.url" artifactId="pax-url-aether" version="2.4.1"/>
+        <dependency groupId="org.ops4j.pax.swissbox" artifactId="pax-swissbox-tracker" version="1.8.1"/>
+        <dependency groupId="ch.qos.logback" artifactId="logback-core" version="1.1.3"/>
+        <dependency groupId="ch.qos.logback" artifactId="logback-classic" version="1.1.3"/>
         <dependency groupId="junit" artifactId="junit" version="${junit.version}"/>
+        <dependency groupId="org.slf4j" artifactId="slf4j-api" version="1.7.12"/>
       </artifact:dependencies>
```

Error in `ReflectionToolBoxTest`: 

```
java.lang.NoClassDefFoundError: Could not initialize class scala.tools.nsc.settings.ScalaVersion$
    at scala.tools.nsc.settings.ScalaSettings$class.$init$(ScalaSettings.scala:138)
    at scala.tools.nsc.settings.MutableSettings.&lt;init&gt;(MutableSettings.scala:20)
    at scala.tools.nsc.Settings.&lt;init&gt;(Settings.scala:12)
    at scala.tools.nsc.CompilerCommand.&lt;init&gt;(CompilerCommand.scala:12)
    at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$api$.liftedTree1$1(ToolBoxFactory.scala:333)
    at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$api$.compiler$lzycompute(ToolBoxFactory.scala:331)
    at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$api$.compiler(ToolBoxFactory.scala:330)
    at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:357)
    at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
    at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.parse(ToolBoxFactory.scala:414)
    at tools.test.osgi.reflection.toolbox.ReflectionToolBoxTest.basicMirrorThroughOsgi(ReflectionToolboxTest.scala:39)
    at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:68)
    at org.ops4j.pax.exam.invoker.junit.internal.ContainerTestRunner.runChild(ContainerTestRunner.java:37)
    at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.invokeViaJUnit(JUnitProbeInvoker.java:124)
    at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.findAndInvoke(JUnitProbeInvoker.java:97)
    at org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.call(JUnitProbeInvoker.java:73)
    at org.ops4j.pax.exam.nat.internal.NativeTestContainer.call(NativeTestContainer.java:109)
    at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:84)
    at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:267)
    at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:98)
    at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
```

I tried to eliminate the use of BootstrapMethods from the reasons for which class initialization failed by removing all uses of lambda from ScalaVersion$, but no dice.

**Comment by adriaanm** [comment]
Nice. The exception seems to have been triggered by properties files gone missing, which cause a NumberFormatException in ScalaVersion, which was then masked by a NoClassDefFoundError... Why so unhelpful, error message?

**Comment by adriaanm** [comment]
Well, beats me why those *.properties files are no longer included in the bundles. I confirmed that with bnd 1.50.0 all resources are copied over to the osgified jar (on 2.11.7). Changing nothing except for bumping the bnd version to 2.4.1 (or 2.4.0 or 2.1.0), the *.properties files are dropped from the bundles (jars in build/osgi). I've tried all kinds of bizarre formulations of `Include-Resource`, to no avail.

**Comment by adriaanm** [comment]
Btw, it looks like bndtools changed their artifactId moving to 2.4.1: mvnrepository.com/artifact/biz.aQute.bnd/biz.aQute.bnd/2.4.1

**Comment by adriaanm** [comment]
When I make ScalaVersion not throw an exception on empty version, the first set of tests pass, but the equinox run fails with another exception loading classes in scala.collection. The morale: don't believe that exception -- let's see if we can find a way to see the underlying one.

**Comment by adriaanm** [comment]
Some progress: `Include-Resource: /=../quick/classes/library;filter:=*.properties|*.txt`

**Comment by adriaanm** [comment]
(Pushed to https://github.com/adriaanm/scala/tree/lrytz-jfun)

**Comment by lrytz** [comment]
@adriaanm i looked a bit around on search.maven.org and found there's a more recent version of `org.eclipse.osgi` (3.10.100.v20150521-1310), but under a different groupId: `org.eclipse.tycho` instead of `org.eclipse.osgi`. that makes `test.osgi` pass

```
test.osgi:
     [echo] Running OSGi JUnit tests. Output in /Users/luc/scala/scala/build/osgi
     [echo] Test pass 1 of 2 using Apache Felix 5.0.1
     [echo] Test pass 2 of 2 using Eclipse Equinox 3.10.100.v20150521-1310
[stopwatch] [test.osgi.timer: 21.327 sec]
```

**Comment by lrytz** [comment]
your `Include-Resources` patch to the `bnd` files is still required

**Comment by lrytz** [comment]
phew.. let's see if this passes the test suite. cleaning up after.

**Comment by lrytz** [comment]
it builds green. cleaned up the commits, so running the test again.

i think we should keep this in [ci: last-only], because for the build to be green we'd have to squash everything, which would be a huge commit of many things.

review by @adriaanm.

**Comment by lrytz** [comment]
btw i marked these two as blockers for M2, but we can change this:
- https://issues.scala-lang.org/browse/SI-9374
- https://issues.scala-lang.org/browse/SI-9373

**Comment by adriaanm** [comment]
Sounds good to me. Let's give ourselves the rest of the week to polish M2. Does that sound like enough time? Stage on Monday/Tuesday?

**Comment by lrytz** [comment]
> macro to retrieve cross versioned artifact names

yes, but what i found gives you the full path to the jar, while we really need the filename only.

> document what swing's osgi version is for

yes!

**Comment by adriaanm** [comment]
I think we should squash this into, say, four commits: 
- one commit per bug fix (parser, deserializer) -- should be all green
- incorporating java sources + required build updates (mixed mode, osgi) -- can be red, to show failing tests
- move failing tests to pending (green)

**Comment by adriaanm** [comment]
Happy to do the rebasing this morning.

**Comment by lrytz** [comment]
#4597

**Pull request closed without merging**
