### PR TITLE
SI-8946: Fixes memory leak when using reflection

### PR DESCRIPTION
**Pull request by timcharper**
References to Threads would be retained long after their termination if
reflection is used in them. This led to a steady, long memory leak in
applications using reflection in thread pools.

Closes https://issues.scala-lang.org/browse/SI-8946

Mentioning @retronym @xeno-by

### CODE REVIEW

**Comment by timcharper** [comment]
Not sure why this failed after rebase; should've been harmless. Investigating.

**Comment by timcharper** [comment]
I'd forgotten to build against JDK6 locally :( My bad. I'll get this fixed soon.

**Comment by timcharper** [comment]
this should build against JDK6:

**Comment by timcharper** [comment]
@retronym @xeno-by the tests are now passing for this pull request.

**Comment by adriaanm** [comment]
Thanks!

**Comment by xeno-by** [comment]
LGTM. @retronym WDYT?

**Comment by retronym** [comment]
I had to look at this a few times to convince myself that it is okay. 

But I can now see that the fact we're running on thread which is the key to the map prevents usual problems with concurrent map mutation and with a weak reference being collected between the `containsKey` and `get` calls. So LGTM, too.

Thanks again, @timcharper!

**Comment by adriaanm** [comment]
Unfortunately the assert is [failing on jenkins](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin/9913/consoleFull) (under load, likely):

```
fail - run/t8946.scala  [non-zero exit code]% scalac t8946.scala
% /home/jenkins/apps/jdk1.6.0_33-x64/jre/bin/java \
  -classpath \
  /localhome/jenkins/c/workspace/scala-checkin/test/files/run/t8946-run.obj:/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-library.jar:/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-reflect.jar:/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-compiler.jar:/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scalap.jar:/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-actors.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/org/scala-lang/modules/scala-partest_2.11/1.0.1/scala-partest_2.11-1.0.1.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/org/apache/ant/ant/1.8.4/ant-1.8.4.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/org/apache/ant/ant-launcher/1.8.4/ant-launcher-1.8.4.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.2/scala-parser-combinators_2.11-1.0.2.jar:/localhome/jenkins/c/workspace/scala-checkin/m2repo/org/scalacheck/scalacheck_2.11/1.11.4/scalacheck_2.11-1.11.4.jar:/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-partest-extras.jar:/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-partest-javaagent.jar:/localhome/jenkins/c/workspace/scala-checkin/test/files/lib/annotations.jar:/localhome/jenkins/c/workspace/scala-checkin/test/files/lib/enums.jar:/localhome/jenkins/c/workspace/scala-checkin/test/files/lib/genericNest.jar:/localhome/jenkins/c/workspace/scala-checkin/test/files/lib/jsoup-1.3.1.jar:/localhome/jenkins/c/workspace/scala-checkin/test/files/lib/macro210.jar:/localhome/jenkins/c/workspace/scala-checkin/test/files/lib/methvsfield.jar:/localhome/jenkins/c/workspace/scala-checkin/test/files/lib/nest.jar \
  -Dfile.encoding=UTF-8 \
  -Djava.library.path=/localhome/jenkins/c/workspace/scala-checkin/test/files/run \
  -Dpartest.output=/localhome/jenkins/c/workspace/scala-checkin/test/files/run/t8946-run.obj \
  -Dpartest.lib=/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-library.jar \
  -Dpartest.reflect=/localhome/jenkins/c/workspace/scala-checkin/build/pack/lib/scala-reflect.jar \
  -Dpartest.cwd=/localhome/jenkins/c/workspace/scala-checkin/test/files/run \
  -Dpartest.test-path=/localhome/jenkins/c/workspace/scala-checkin/test/files/run/t8946.scala \
  -Dpartest.testname=t8946 \
  -Djavacmd=/home/jenkins/apps/jdk1.6.0_33-x64/jre/bin/java \
  -Djavaccmd=javac \
  -Duser.language=en \
  -Duser.country=US \
  scala.tools.nsc.MainGenericRunner \
  -usejavacp \
  Test \
  jvm > t8946-run.log
java.lang.AssertionError: assertion failed: 1 threads were retained; expected 0.
        at Test$.main(t8946.scala:27)
```

**Comment by som-snytt** [comment]
I haven't looked at this failure, but I have a different approach at

https://github.com/scala/scala/pull/4145

to checking that a ref is collectable.  There is no guarantee that refs are cleared in a particular order, so it's safer to wait on the ref queue.  In fact, the allocator could check the ref and short-circuit the wait: the docs say the ref is enqueued maybe later, after the ref is cleared.

I added a collectable assertion, which maybe should use the queue instead of the optimistic approach used here.

https://github.com/scala/scala/pull/4133

**Comment by timcharper** [comment]
Som-snytt - interesting approach. I'll review and incorporate your ideas, and will send another patch here soon (tonight). Sorry@adriaanm for the trouble!

**Comment by timcharper** [comment]
@som-snytt it looks like you are doing a very similar approach to mine for checking collectability; and, it looks like the tests in your examples may be prone to the same error as I am seeing.

I think a retry mechanism will work best. Also, if after a set amount of retries, one or more threads are garbage collector, I think victory can be declared

**Comment by timcharper** [comment]
Please see the following patch @som-snytt  @adriaanm  https://github.com/SpinGo/scala/commit/286538b949fda1c1fdd43f0873d855d86436767f

**Comment by som-snytt** [comment]
I like your idea of giving the gc many references and only caring if one is cleared, since that shows that they are all collectable in principle.

In fact, given a generator of a (new) reference, the test rig can invoke the generator any number of times, which can only increase our chances of noticing a collection.

I used your strategy (of checking for cleared ref after an arbitrary ref was cleared) in the first commit here:

https://github.com/scala/scala/pull/4133

but the second commit uses that other strategy of just blocking on the queue while a thread generates garbage. The thread stops generating garbage if the heap expands or the reference is cleared.

The docs say that when a ref is cleared, enqueuing happens at the same time or later.  So there is room for further improvement: if the allocator notices the ref is cleared, it should notify the test thread right away rather than let it wait for enqueuing. But that is very refined.

I tried to avoid arbitrary sleeps and retries, since tuning that is hard.  Tuning a timeout is fairly simple, though it suffers from long waits for failure.  Eventually, I'd want a long wait for Jenkins and a short wait when I run unit tests locally.

**Comment by som-snytt** [comment]
I hope a fix can get merged by someone not cooking a turkey today.  Even just relaxing the assert, n < 16 instead of n == 0.  @adriaanm @retronym

**Comment by retronym** [comment]
I would suggest moving the test case from `run` to `disabled`.

Then you can eat your fill of turkey _before_ reasoning about garbage collection as dessert.

**Comment by retronym** [comment]
https://github.com/scala/scala/pull/4170

**Comment by som-snytt** [comment]
There's a test at

https://github.com/som-snytt/scala/commit/7029bb7d7593e2706806655c4b8645609bbf7c24

https://github.com/scala/scala/pull/4133

The tests pass, but maybe I'll ask Jenkins nicely to retry a few times, just to confirm.

**Comment by som-snytt** [comment]
The reference from griggt is just a typo. I wonder why there isn't a way to hide or remove it.

**Pull request merged**
