### PR TITLE
A band-aid solution for SI-5803.

### PR DESCRIPTION
**Pull request by retronym**
Since ae5ff662, resetAttrs duplicates trees, which doesn't preserve ApplyConstructor.
My attempt to modify TreeCopier to do so proved trickier than expected.

In any case, ApplyConstructor is not long for this world, and is only used in tree printing
to distinguish `new X` from regular Apply trees, so this should suffice pending full surgery.

### CODE REVIEW

**Comment by jsuereth** [comment]
@burmako Should I just close this pull request for the one you're about to send for the fix?

**Comment by xeno-by** [comment]
If this bug is important, then let this pull request in. 

On a second thought, the assertion supports the invariant that `resetAttrs` has return type that is the same that the return type of the input:

`def resetAllAttrs[A <: Tree](x: A): A`

The invariant is no longer true, so the entire situation will need some thought, so I, probably, won't be able to resolve it quickly. So, if the bug is important, better to have the workaround now.

**Comment by jsuereth** [comment]
Ok, pulling this in.

**Comment by retronym** [comment]
@xeno-by Does this invariant also break down for trees other than `ApplyConstructor`?

**Comment by xeno-by** [comment]
Yes, for example, resetAllAttrs erases TypeApply nodes if any of their
arguments is erased.

On 17 May 2012 18:29, Jason Zaugg <
reply@reply.github.com

**Comment by xeno-by** [comment]
Okay, it seems that noone relied on the aforementioned invariant, so I just changed the signature of resetAttrs: https://github.com/scalamacros/kepler/commit/7813d660bea0fd9b987493baef019ea92f876a2f.

Submitting a pull request as soon as https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/17/console gives the green light.

**Pull request merged**
