### PR TITLE
SI-8219 Coherency for `{Any, Object}#==`; typer.context / infer.context

### PR DESCRIPTION
**Pull request by retronym**
- Make our ficticious == and != methods line up for overriding checks
  - Eliminate a major source of puzzling behaviour by ensuring Inferencer
    and Typer agree on what the current Context is.

Review by @adriaanm, @xeno-by @lrytz (or any number of people that have been puzzled about what a strange Context was doing in their inferencer over the years...)

These changes are independent, I can break them up if desired. The `==` parts are probably a touch riskier as I don't know the history of the divergent signatures.

### CODE REVIEW

**Comment by soc** [comment]
> I've left a TODO to note that we should really make `Any#{==, !=}`
> non-final and include a final override in `AnyVal`. But I don't think
> that is particularly urgent.

Agree, but if we touch this code already, it would be nice to add `eq` and `ne` to `Any`, too.

**Comment by adriaanm** [comment]
this needs a rebase unfortunately

**Comment by adriaanm** [comment]
LGTM'd & rebased

**Comment by adriaanm** [comment]
@soc, yep, it would be great to pull on this thread a little further, but let's not have the perfect be our enemy. Follow-up PRs appreciated, but I think we'll have to leave it at this for now

**Pull request closed without merging**
