### PR TITLE
Prefer internal.Reporter

### PR DESCRIPTION
**Pull request by som-snytt**
Complete the reporting refactor to use internal.Reporter.

The partest blocker was fixed in v1.0.14. sbt and IDE
are not validated, so reporters.Reporter is not removed.

Edit: Global takes `reporting.Reporter` so clients of Global are safe, including sbt's cancel and scaladoc's comment, and including macroAnnot.

`internal.Reporter` is adapted in `reporting.Reporter` companion.

`AbstractReporter` and `ConsoleReporter` innards are refactored to handy traits, which are used in the new paradigm.

Follow-up to https://github.com/scala/scala-partest/pull/56

### CODE REVIEW

**Comment by som-snytt** [comment]
This oughta be fun:
```
[test] [error] 1 of 12 test tasks failed:
[test] [error] - macroAnnot/test
[test] [error]   - macroAnnot/compile:compileIncremental failed: java.lang.NoSuchMethodError: scala.tools.nsc.Global.<init>(Lscala/tools/nsc/Settings;Lscala/tools/nsc/reporters/Reporter;)V
[test] java.lang.RuntimeException
[test] 	at $33f7ec16b05f4d72fd8b$$anonfun$root$26.apply(build.sbt:919)
[test] 	at $33f7ec16b05f4d72fd8b$$anonfun$root$26.apply(build.sbt:858)
[test] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[test] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[test] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[test] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[test] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[test] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[test] 	at sbt.Execute.work(Execute.scala:237)
[test] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[test] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[test] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[test] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[test] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[test] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[test] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[test] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[test] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[test] 	at java.lang.Thread.run(Thread.java:748)
[test] [error] (root/*:testAll) java.lang.RuntimeException
[test] [error] Total time: 1430 s, completed May 12, 2018 9:08:52 PM
```

**Comment by som-snytt** [comment]
Unrelatedly, I wanted to benchmark for refactor AbstractReporter to a filter, but managed to get jmh to fail with a VerifyError. I don't know if this is a usual interaction? When I'm more comfortable with jmh I'll update.
```
java.lang.VerifyError: Inconsistent stackmap frames at branch target 81
Exception Details:
  Location:
    scala/tools/nsc/reporters/ReportingBenchmark.init()V @81: aload_1
  Reason:
    Type 'scala/tools/nsc/reporters/ReportingBenchmark$$anon$1' (current frame, locals[1]) is not assignable to 'scala/reflect/internal/Reporter' (stack map, locals[1])
```
I guess it [happens sometimes](https://gitlab.ow2.org/asm/asm/issues/317586).

**Comment by som-snytt** [comment]
I did a quickie to restore the previous `Global` ctor, but now:

[test] [error]   - macroAnnot/compile:compileIncremental failed: java.lang.NoSuchMethodError: xsbt.CachedCompiler0$Compiler.reporter_$eq(Lscala/tools/nsc/reporters/Reporter;)V

I guess I'll cross that bridge, too, now that I've come to it.

**Comment by som-snytt** [comment]
I guess that was it. Not sure exactly what is different for sbt about macro-annot, or what a migration path would be; but maybe just leave it as-is.

**Comment by som-snytt** [comment]
@adriaanm re: https://github.com/scala/bug/issues/10869#issuecomment-392467390

This takes `internal.Reporter` so that you get error, warn, and echo. The built-in controls are `-Xmaxerrs`, `-Xmaxwarns`, and `-nowarn`, and `-Xfatal-warnings`.

A custom reporter could filter `echo` on some criterion if it wants to. Or maybe I already added `reporters.VerboseReporter`.

The compiler (after previous refactor) tests `-verbose` before echoing, rather than the reporter checking verbosity.

I think the simplicity will benefit any solution for "warning suppression", in avoiding the "where is my output?" moments you get with logging systems.

**Comment by adriaanm** [comment]
Regarding macroAnnot, Lukas diagnosed it as a limitation with the sbt compiler interface. The macro annot project uses the quick compiler for its scala instance, but the rest of the project uses starr. The macroAnnot tests should be ported to partest, and the quick scalaInstance dropped.

**Comment by som-snytt** [comment]
@adriaanm thx for the xplanation. Also, my previous pun, "cross that bridge [method]", was a good one. Maybe an old one.

**Comment by lrytz** [comment]
I'm not sure what to think of this PR. Maybe I misunderstand it / its goals.

The PR adds casts and type tests, and IMO doesn't make the code easier to understand, while `nsc.reporters.Reporter` is still there. It also duplicates some functionality (eg from `ConsoleReporter` into `DisplayReporter`). I fear that the resulting code we end up having is even more confusing than the current state, and it doesn't really bring us closer to removing `nsc.reporters.Reporter`, since sbt continues to use it (https://github.com/sbt/sbt/blob/1.x/main-actions/src/main/scala/sbt/compiler/Eval.scala#L15). I think it would be better work on the other end first (remove usages of `reporters.Reporter`, think what to do for `def comment`, `var cancelled`), and clean up the hierarchy when we actually can.

**Comment by som-snytt** [comment]
@lrytz I see there are two commits, one to address the TODO about fixing internal.Reporter when partest is fixed (which is possible now); the second refactors the AbstractReporter/ConsoleReporter.

The comments about sbt/ide/partest now just say sbt/ide. If you can't do anything because sbt, then I'd give up.

I could let `Global` still take `reporters.Reporter` natively and adapt `internal.Reporter`; that would avoid the downcasting for cancel and comment.

**Comment by lrytz** [comment]
That sounds better. Let's do the actual cleanups, but not anticipate future ones by adding more code.

**Comment by som-snytt** [comment]
My broom broke.

**Review by lrytz — APPROVED** [review]
Looks good, thank you!

**Comment by lrytz** [comment]
Ah, merge conflict.. Also maybe @adriaanm wants to take a quick scan of the change (maybe not).

**Comment by som-snytt** [comment]
Rebased, accommodated recent change to avoid `System.exit`.

**Comment by adriaanm** [comment]
Interesting failure in https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/2311/testReport/junit/scala.collection/FloatFormatTest/toOption/ 

Could this be due to recent changes to LazyList?

**Comment by som-snytt** [comment]
I think it's just a bug in https://github.com/scala/scala/pull/6726

/cc @martijnhoekstra 

https://github.com/scala/scala/pull/6746

**Comment by som-snytt** [comment]
Noting that this PR did not change the default for `-Xreporter`, since it would require adapting for `Global`.

**Comment by retronym** [comment]
I noticed that in the 2.13.x branch, the [benchmark harness](https://github.com/scala/compiler-benchmark/blob/39b6292037fda60dce49e3e74da2b1c0b2a607b1/compilation/src/main/scalac/scala/tools/benchmark/BenchmarkDriver.scala#L38) which sets `settings.nowarn = true` [no longer manages to suppress warnings](https://scala-ci.typesafe.com/view/scala-bench/job/compiler-benchmark/1378/console). I guessing that it is related to this PR, but haven't figured out the details.

**Comment by som-snytt** [comment]
@retronym I'll take a look. I also neglected to update ReplReporter, which I'm doing now.

**Comment by som-snytt** [comment]
@retronym Don't be mad, but apparently it was intentional to provide a minimal reporter for displaying errors before the compiler is built. Normally the real reporter is created with Global, and then Driver.process adopts global.reporter, replacing the temporary. In this case, Global is created with the current, minimal reporter; the benchmark global wouldn't respect `-Xreporter` if it were set, for instance.

I'll do the obvious thing and revert to creating a full-featured reporter for that start-up sequence. Not sure if there's a reason not to use Global.reporter (on the companion) right away.

**Pull request merged**
