### PR TITLE
SI-8369 resetAttrs now correctly accounts for skolems

### PR DESCRIPTION
**Pull request by xeno-by**
resetAttrs (née resetLocalAttrs) has been oblivious to existence of skolems.
Not anymore, which prevents us from reverting to the untyper nightmare.

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM -- good catch

**Comment by retronym** [comment]
@xeno-by is on fire today...

**Comment by retronym** [comment]
LGTM

**Comment by retronym** [comment]
@xeno-by I suspect that this bug was related to my failure to get the original "`resetLocalAttrs` and retypecheck" version of scala-async to handle the trickier existential tests (e.g. https://github.com/scala/async/pull/19/files#diff-b3a2948c5abb7206afe00f3ef333e75eR71)

**Pull request merged**
