### PR TITLE
patmat tweaks: compiler performance, better error on unsupported pattern

### PR DESCRIPTION
**Pull request by adriaanm**
- move a catch of a StackOverflowError up the call stack since @gkossakowski diagnosed it to be killing compiler performance
- Roland reported hitting the unsupported pattern branch in translatePattern in akka code, so providing some diagnostics and a nicer error message to figure out what's going on

review by @gkossakowski (/cc @paulp)

### CODE REVIEW

**Comment by gkossakowski** [comment]
I'll verify if this resolves the problem with performance. My performance testing infrastructure is still not fancy enough to automate this. :-/

**Comment by gkossakowski** [comment]
It seems like 7b6cc9f does not help. Only commenting out catching SOEs helps to improve compiler performance by 10-11%. I'll double check tomorrow.

**Comment by gkossakowski** [comment]
I checked again and I'm pretty sure 7b6cc9f doesn't help. Therefore I think this pull request should be closed (it doesn't bring fixes it promises).

**Comment by jsuereth** [comment]
Done.  Reopen upon solution.

**Pull request closed without merging**
