### PR TITLE
c.typeCheck(silent = true) now suppresses ambiguous errors

### PR DESCRIPTION
**Pull request by xeno-by**
Otherwise use cases like the one shown in the attached test (trying to
typecheck something, which leads to an ambiguous overload error) will
mysteriously fail compilation.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @hubertp

**Comment by aztek** [comment]
Will this patch make `c.typeCheck(Select(Literal(Constant(10)), TermName("$minus")), silent=false)` throw an exception?

**Comment by xeno-by** [comment]
Oh yeah it will. Sorry for misleading you in our email conversation - I looked at a different branch.

**Comment by xeno-by** [comment]
ping @hubertp

**Comment by hubertp** [comment]
lgtm. sorry for the delay.

**Pull request merged**
