### PR TITLE
SI-8638  Empty UnrolledBuffer hangs on prepend.

### PR DESCRIPTION
**Pull request by Ichoran**
Tracked down bug to incorrect recursion in insertAll.  Fixed by adding a missing case (which incidentally will provide better performance when adding to the end of a block).

No specific tests, as this is caught by quasi-complete collections tests.

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @lihaoyi, please

**Comment by lihaoyi** [comment]
This may seem a silly question, but does that mean that the collections tests are currently failing without this patch?

**Comment by lihaoyi** [comment]
More generally, where are the collections tests at all? Are they part of partest? 

This particular PR looks fine to me, and reasonably straightforward.

**Comment by Ichoran** [comment]
@lihaoyi - I have been writing quasi-comprehensive tests for collections that are not merged yet because until very recently they failed in many places (partly because the tests were broken, partly because the collections were).  The source is here: https://github.com/Ichoran/scala-collections-laws

**Comment by adriaanm** [comment]
LGTM echo for @lihaoyi 's review (the bot flags PR's that have a comment that start with LGTM as ready-to-merge) -- thanks! @Ichoran, that sounds very promising!

**Comment by lihaoyi** [comment]
I'm surprised we didn't already have fuzz tests for all these collections, since they're the ideal target with lots of inheritance and "same interface with different implementation" all over the place. It's cool that you're actually doing it =)

**Comment by Ichoran** [comment]
@lihaoyi - It's a little trickier with Scala than for most collections libraries because of CBFs that yield different results depending on static typing.  This requires a lot of explicit code (more than you'd expect from "lots of inheritance") to check properly.  Maybe that's why it hasn't been done before?

**Pull request merged**
