### PR TITLE
SI-7126 Account for the alias types that don't dealias.

### PR DESCRIPTION
**Pull request by retronym**
After this change:

```
qbin/scalac -Ydebug test/files/pos/t7126.scala 2>&1 | grep warning
warning: dropExistential did not progress dealiasing Test.this.T[Test.this.T], see SI-7126
one warning found
```

`T[T]`? Really? The true bug lies somewhere else; the comments of
the ticket illuminate the general areas of concern.

This is a shallow fix intended for 2.10.1. I'll keep investigating the deeper issue, to help inform the decision about whether we are comfortable releasing 2.10.1 with only this bandaid.

Review by @paulp

### CODE REVIEW

**Comment by retronym** [comment]
Review item: can we spot anything else in 3bf51189f979eb0dd41744ca844fd12dfdaa0dee that now recurses on `.dealias` that would also need the same protection?

**Comment by paulp** [comment]
Did somebody already take of getParts? That too must be a problem.

**Comment by paulp** [comment]
Ah, found the other PR.

**Comment by retronym** [comment]
Yep, that's addressed in #2166. But the reported issue there was the inability to progress through a HK alias. Which we should also keep in mind when re-reviewing 3bf5118.

**Comment by paulp** [comment]
Oh, "the same protection" you mean the infinite recursion.

By the way , I noticed, belatedly, that said protection IS in place on AliasTypeRef, on the auto-normalizers.

```
    override def prefix     = if (this ne normalize) normalize.prefix else pre
    override def termSymbol = if (this ne normalize) normalize.termSymbol else super.termSymbol
    override def typeSymbol = if (this ne normalize) normalize.typeSymbol else sym
```

Personally I think we should make it true by construction that (this ne normalize) when "this" is an AliasTypeRef.

**Comment by retronym** [comment]
The `T[T]` thing is coming out of `handlePolymorphicCall` in `Typers`, seems like a little kind checking is in order. But I got sidetracked with another ticket, so I'll just leave a breadcrumb for now.

``` scala
val lenientTargs = protoTypeArgs(tparams, formals, mt.resultApprox, pt)
                val strictTargs = map2(lenientTargs, tparams)((targ, tparam) =>
                  if (targ == WildcardType) tparam.tpeHK else targ)
                var remainingParams = paramTypes
                def typedArgToPoly(arg: Tree, formal: Type): Tree = { //TR TODO: cleanup
                  val lenientPt = formal.instantiateTypeParams(tparams, lenientTargs)
                  val newmode =
                    if (isByNameParamType(remainingParams.head)) POLYmode
                    else POLYmode | BYVALmode
                  if (remainingParams.tail.nonEmpty) remainingParams = remainingParams.tail
                  val arg1 = typedArg(arg, forArgMode(fun, mode), newmode, lenientPt)
                  val argtparams = context.extractUndetparams()
                  if (!argtparams.isEmpty) {
                    val strictPt = formal.instantiateTypeParams(tparams, strictTargs)
                    inferArgumentInstance(arg1, argtparams, strictPt, lenientPt)
                    arg1
                  } else arg1
                }
```

**Comment by retronym** [comment]
My working hypothesis is that such types only show up during failed lines of inquiry in type inference. So code that is called within inference is at risk of infinite recursion (e.g. `dropExistential` as we've modified here), but other places are not (e.g. `getParts`).

**Comment by retronym** [comment]
Review by @adriaanm for the `TypeVar` change.

**Comment by adriaanm** [comment]
LGTM in isolation (I assume the test case no longer warns?),
but I'm having second thoughts about switching from normalize to dealias between 2.10.0 and 2.10.1
i.e., should we revert e5da30b843?

**Comment by paulp** [comment]
I don't think we should revert it wholesale, not at this point. I can't remember how/why it went in between 2.10.0 and 2.10.1, that feels very wrong now? In any case, I think it is likely that one or more things depends on it by now. Maybe we should just take a good hard look at it for any more places where we need to see normalized type constructors.

**Comment by retronym** [comment]
Yep, the warning is eradicated.

I second Paul's suggestion to sweep the remaining places in e5da30b where we no longer call `normalize` for the possibility of type constructors. We'll have to do this anyway for master. If we can't reason well enough about some of those places, we can be cautious for 2.10.1 and switch them back.

**Comment by retronym** [comment]
I've started adding my comments to e5da30b843. I'll be a short on scalac time for the rest of the week, so any help is appreciated.

**Comment by adriaanm** [comment]
ok, the extra review pass over e5da30b has convinced me

LGTM

**Pull request merged**
