### PR TITLE
Fix access to empty package from the repl.

### PR DESCRIPTION
**Pull request by paulp**
It seems that way back in f5c336d566 three months ago I
booched the repl's ability to get at the empty package.
I've noticed this a hundred times but strangely it has not
been reported by anyone else. Perhaps you are all religious
package users. In any case, it is back.

### CODE REVIEW

**Comment by paulp** [comment]
Review by a cast of thousands!

**Comment by JamesIry** [comment]
I had some of the same tests fail on another PR and then pass with a PLS REBUILD ALL

**Comment by paulp** [comment]
Review by @JamesIry, have pity, don't make me spin the wheel every time.

**Comment by JamesIry** [comment]
Step right up, spin the wheel! Everybody's a winner! You look like a lucky young gentelman! Go ahead, give it a spin! 

Congratulations! It landed on LGTM!

**Comment by paulp** [comment]
Everyone's a winner!

**Pull request merged**
