### PR TITLE
Interactive / ScalaDoc housekeeping

### PR DESCRIPTION
**Pull request by huitseeker**
This is a re-issue of https://github.com/scala/scala/pull/3903 (closed during my leave)

Those are the leftovers of what should have been a larger bugfix PR, but that's finally not meant to be.
No issue, since the changes are straightforward & compiler warnings-driven, but I'd be happy to create one.
Should probably be merged into 2.12.

[reviewed & LGTM'ed](https://github.com/scala/scala/pull/3903#issuecomment-50616549) by @dragos 
Adaptation PR for refactoring is [open](https://github.com/scala-ide/scala-refactoring/pull/60)

Edit : non-trivial changes in the last commit post-review (but going in the direction of simplicity)

### CODE REVIEW

**Comment by gkossakowski** [comment]
PLS REBUILD 20cf83b

**Comment by gkossakowski** [comment]
@huitseeker, it looks like  20cf83b consistently hangs in presentation compiler tests. Could you have a look?

**Comment by huitseeker** [comment]
@gkossakowski on it, thks.

**Comment by huitseeker** [comment]
PLS REBUILD a6946ee

**Comment by huitseeker** [comment]
@gkossakowski Should be fixed (with a simpler last commit, now). Thanks for the heads up !

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
