### PR TITLE
Si 6987 2.10.x

### PR DESCRIPTION
**Pull request by JamesIry**
SI-6987 Fixes fsc compile server verbose output

Internally the fsc server code was setting a "verbose" flag, but it was
always false. Fixing that gives server's verbose output, but because the
output was buffered and not flushed the server's output wasn't seen
until the compile run was complete. This pull request fixes the verbose flag
and flushes the server side output.

Includes a test

review @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
a new era of testing has begun!

could you comment on the removal of `sys exit 0`? (just FMI)

LGTM

**Comment by JamesIry** [comment]
The commit has a comment on the removal

**Comment by paulp** [comment]
FYAEI, we should pretty much never call System.exit. It brings nothing but pain.

**Comment by paulp** [comment]
https://issues.scala-lang.org/browse/SI-5674

**Comment by JamesIry** [comment]
In this case, adding insult to the pain, it was a  redundant "sys exit 0" at the end of a main method.

**Comment by JamesIry** [comment]
Well, now, isn't that interesting.

  [partest] testing: [...]/files/run/t6987.scala                                  [FAILED]
  [partest] did not get the string expected, full results were:
  [partest] [Temp directory: /tmp/scala-devel/jenkins]
  [partest] Fast Scala compiler version 2.10.1-20130117-114654-1dce34d275 -- Copyright 2002-2013, LAMP/EPFL
  [partest] [Given arguments: -shutdown -verbose]
  [partest] [Transformed arguments: -shutdown -verbose -current-dir /localhome/jenkins/d/workspace/pr-scala-testsuite-linux-opt]
  [partest] [VM arguments: ]
  [partest] java.net.ConnectException: Connection refused
  [partest] [Connecting to compilation daemon at port 36598 failed; re-trying...]
  [partest] [No compilation server running.]

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
There's a race condition between starting the server and starting the client. It's easy enough to fix in testing. The surprising thing is that it never (hardly ever!) bites us on the command line.

**Comment by paulp** [comment]
An old era of testing has resumed!

**Comment by JamesIry** [comment]
failed with no explanation. awesome-sauce.

**Comment by JamesIry** [comment]
I give up, as it stands fsc is impossible to test this way. Both the client and server are trying to mutate System.out and it all goes sideways in peculiar, interesting, and non-deterministic ways when they're run in-process.

**Comment by paulp** [comment]
Can we salvage nothing from the effort for the next guy?

**Comment by JamesIry** [comment]
Oh, I'll still put this in. It just falls under that heading of "stuff we need to test from the command line"

**Pull request closed without merging**
