### PR TITLE
GenASM-based fix for SI-4804. Fix of the same for GenJVM pending.

### PR DESCRIPTION
**Pull request by magarciaEPFL**
review by @dragos
review by @VladUreche

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
It would be great if an "LGTM" review showed up before cutting M4. Thanks.

**Comment by adriaanm** [comment]
You may want to email the expected reviewers directly. Not sure everyone has their github notifications tuned correctly.

**Comment by VladUreche** [comment]
It looks good to me, but I'm nowhere near knowledgeable with the backend. So better wait for @dragos to decide.

**Comment by dragos** [comment]
Looks good to me :)

**Pull request merged**
