### PR TITLE
SI-10133 Require escaped single quote char lit

### PR DESCRIPTION
**Pull request by som-snytt**
The spec specifically requires `'\''` and not `'''`.
    
The error consumes all consecutive single quotes.

SI-10120 Extra advice on unclosed char literal
    
Folks from other languages might mistakenly enclose
a string in single quotes. Since this presents as
a symbol literal followed by the unpaired single
quote, we can add a syntax reminder.

### CODE REVIEW

**Comment by som-snytt** [comment]
/rebuild

Internal error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe (Write failed)

**Review by adriaanm — APPROVED** [review]
So much for scala being quote/unquote unfriendly to newcomers.

**Comment by adriaanm** [comment]
lets hope our 'communal' build reveals any accidental usages of `'''`

**Comment by som-snytt** [comment]
"quote/unquote unfriendly!" That was a good one.

**Comment by adriaanm** [comment]
Sadly, I'm going to have to revert this. Looks like `'''` exists in the wild, again illustrating the rule that any syntactically valid program exists in the wild.

**Comment by adriaanm** [comment]
Lets bring the spec-abidance back under -Xsource:2.13

**Comment by som-snytt** [comment]
Hold on, let's make triple-single-quotes analogous to triple-double-quotes, where it can hold 0xA etc! Multiline char literal.

**Comment by som-snytt** [comment]
Oh, this has a couple of commits; I'll resubmit separately.

**Pull request merged**
