### PR TITLE
SI-2038 make pt fully-defined when typing Typed

### PR DESCRIPTION
**Pull request by adriaanm**
dropExistential turns existentials in the expected type (pt) that's passed to `typed`
into `BoundedWildcardType`s, but those should not end up in trees

when typing a `Typed` node, we didn't check for the type being fully defined (`isFullyDefined`)
(and thus did not make it fully defined by turning these BWTs into existentials again using `makeFullyDefined`)

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @xeno-by

**Comment by xeno-by** [comment]
Since I believe I've been assigned as a reviewer for educational reasons (thanks for that btw!), I've got a few questions:
1) Why do we need to do `dropExistential` before calling `typed1`?
2) What's wrong with having bounded wildcards in trees?

**Comment by adriaanm** [comment]
excellent questions -- I'll try to answer but I can't speak with authority, unfortunately /cc @odersky 

(dropExistential landed together with existentials, 5 years ago in 8414ebada9 if you'd like to dig deeper)

1) I believe we dropExistential in the expected type (pt) as an optimization, since to compare the computed type for the tree to its expected type, we'd have to unpack existentials on both sides (if we leave the existentials in pt)

2) since a BoundedWildcardType is only an approximation we shouldn't have them in trees -- for example, we can't pack a BWT back into an existential type (that's what skolems are for, they remember their scope, so the skolemizeExistential is a reversible function, whereas dropExistential is not)

that said, I don't know why we don't skolemize the expected type instead of replacing existentials by BoundedWildcardType (except for performance?)

**Comment by adriaanm** [comment]
I asked Martin about BoundedWildcardType: skolemization doesn't make sense for a target type, because the type you'll derive from the tree will have different skolems (since you unpack existentials again while typing it).

**Comment by jsuereth** [comment]
waiting for a LGTM

**Pull request merged**
