### PR TITLE
Document BooleanSetting can be default false

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by som-snytt** [comment]
There are user-facing words due to paulp https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/CompilerCommand.scala#L36

I don't know if `-Y` only or any boolean setting can default true. With `-Y`, you could rename from `-Yfoo` to `-Ynofoo` without deprecation or advance notice.

**Comment by som-snytt** [comment]
Well, something broke and I don't see the help text in 2.13. Edit: only under a help option like `-V` or `-Y`?
```
scala -V
Usage: scala <options> <source files>

Verbose options:
  -Vbrowse:<phases>                 Browse the abstract syntax tree after <phases>
[snip]

-- Note --
Boolean settings are false unless set: -Xdev -Xcheck-init:true -Xprompt:false
Multi-valued settings are comma-separated: -Xlint:infer-any,unused,-missing-interpolator
Phases are a list of names, ids, or ranges of ids: -Vprint:parser,typer,5-10 -Ylog:-4
Use _ to enable all: -language:_ -Vprint:_
```

**Comment by dwijnand** [comment]
@som-snytt better, or am I still missing something?

**Review by som-snytt — APPROVED** [review]
Hard to quibble.

**Pull request merged**
