### PR TITLE
sbt-git-plugin has moved.

### PR DESCRIPTION
**Pull request by retronym**
We need to eliminate these sort of shifting sands to make
the SBT build a viable option.

Review by @jsuereth. Should we switch to dependencies on binary releases of these plugins?

### CODE REVIEW

**Comment by paulp** [comment]
lgtm.

**Comment by jozic** [comment]
+1

**Comment by puffnfresh** [comment]
+1. Ran into this yesterday.

**Comment by eed3si9n** [comment]
+1

**Pull request merged**
