### PR TITLE
Fix SI-7862: MANIFEST.MF file for Scala sources

### PR DESCRIPTION
**Pull request by dragos**
In order to be able to use published Scala jars as OSGi bundles in the
Eclipse build, Eclipse needs to match sources and binaries. That is
done by making source jars _source bundles_. This PR adds the required
manifest entries. Nothing else should be affected (file names remain
the same).

### CODE REVIEW

**Comment by retronym** [comment]
Can you please tweak your commits headers to:

Master:

```
SI-1234 ....
```

backport:

```
[nomaster] SI-1234 ...
```

The release notes look nicer if things are consistent.

**Comment by dragos** [comment]
Please have another look.

**Comment by retronym** [comment]
LGTM, thanks for refactoring!

**Comment by retronym** [comment]
Successful test run: https://scala-webapps.epfl.ch/jenkins/job/pr-scala/2447/

**Pull request merged**
