### PR TITLE
SI-8474  Inconsistent behavior of patch method

### PR DESCRIPTION
**Pull request by Ichoran**
SI-8474 Inconsistent behavior of patch method

Changed Iterator to be consistent with other collections.

Also fixed SeqViewLike to validate/constrain inputs.

No specific tests; quasi-comprehensive collection tests will cover this later.

### CODE REVIEW

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@fbb8c4c

**Comment by adriaanm** [comment]
Review by @lrytz

**Comment by lrytz** [comment]
Can this go in 2.11.x? It changes the current behavior of `Iterator.patch`. /cc @adriaanm 

Also, it would be good to have a few unit tests for the unified `patch` behavior.

**Comment by Ichoran** [comment]
I have the same question about going in 2.11.x, but it also solves a problem with views, IIRC...I'll document when I'm not quite so busy at conferences.

**Comment by gkossakowski** [comment]
@lchoran, what's the status of this PR?

**Comment by Ichoran** [comment]
@gkossakowski - I need to explain why I think this fixes enough bugs for it to make sense changing the behavior in 2.11 instead of waiting for 2.12.  Or maybe we'll decide that it doesn't fix enough.  I'll get to it shortly.

**Comment by Ichoran** [comment]
I've verified that this fixes both SI-8474 and SI-8688.  It affects Iterator, SeqView, and StreamView according to the quasi-comprehensive collections tests. Lhis line in particular:

``` scala
(n <= x.`size`) implies (x.`patch`(n, y, m).`drop`((0 max n)+y.`size`) theSameAs x.`drop`((0 max n)+(0 max m)))
```

where theSameAs is basically a == that is a little more robust to changes in order.

Negative indices for `n` fail the test without this patch; patching in an empty collection to views will cause a no next element exception for `n==0` (that is, using `patch(n,ys,m)` as `drop(m)`.  I think I could split this patch into two, one that fixes that aspect of views behavior, and the other which fixes iterator and thereby fixes views in ways that rely on iterators.  It might not make the code too ugly in the meantime.

Anyway, I would recommend classifying the current behavior as a just-plain-bug and fixing it, but I suppose we could also wait until my bytecode scanning tools are complete (doubt I'll get that far this month, but next month I should) and see if there's enough usage of Iterator.patch in the wild to be worried.

**Comment by gkossakowski** [comment]
LGTM.

@Ichoran, thanks for comprehensive summary. I think we should take a chance on this fix.

**Pull request merged**
