### PR TITLE
minor fixes scaladoc

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by VladUreche** [comment]
Hi @xuwei-k, thanks for your patch!

The [pull request rules](https://github.com/scala/scala/wiki/Pull-Request-Policy) state that you need to designate someone to review your patch. Since you didn't mention anyone, I appointed myself as the reviewer: the patch LGTM! (looks good to me)

And for the spurious failures for the testing jobs:
PLS REBUILD ALL

**Comment by jsuereth** [comment]
Whenever the CLA has been signed, let me know and i"ll merge.   Great patch!

**Comment by xuwei-k** [comment]
need CLA ? what should I do ?

**Comment by jsuereth** [comment]
Here's the CLA: http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf

Also, the typesafe CLA I _believe_ is compatible for Scala, which is easier to sign here: http://www.typesafe.com/contribute/cla

**Comment by xuwei-k** [comment]
I have ever signed typesafe CLA.
https://github.com/typesafehub/migration-manager/pull/10#issuecomment-5961586

**Comment by jsuereth** [comment]
Great, thanks!

**Pull request merged**
