### PR TITLE
undeprecates c.parse

### PR DESCRIPTION
**Pull request by xeno-by**
We never thought that c.parse is going to be completely subsumed by
quasiquotes, but hoped that the use cases that are going to be lost
aren’t going to be noticed by anyone.

Unfortunately, this isn’t the case, so I’m undeprecating c.parse until
we get a better story for those for whom quasiquotes are not enough.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
LGTM

**Comment by paulp** [comment]
For future reference, this commit message is pretty weak. It's five lines, but the same information content could be found in "I undeprecated c.parse." For someone who doesn't already know why "this isn't the case", there's nothing.

**Comment by xeno-by** [comment]
@paulp You're right, I'll do better next time. The use case I've been alluding to is the `illTyped` macro that parses the string that goes into it and then tries to typecheck it.

**Pull request merged**
