### PR TITLE
SI-7624 Fix -feature and some -Xlint warnings

### PR DESCRIPTION
**Pull request by soc**
Changes build.xml to build Scala with `-feature` enabled.

### CODE REVIEW

**Comment by soc** [comment]
I have not modified BCode-related source files, because I don't want to cause any trouble when @magarciaEPFL pushes the next round of improvements.

**Comment by soc** [comment]
Review by @adriaanm/@phaller.

**Comment by adriaanm** [comment]
Nice! We should really get to a state where people can compile with -fatal-warnings (this may include a switch that suppresses inliner warnings). Also, one improvement to deprecation warnings would be not to warn when a deprecated member is called from a member that is similarly  deprecated (as they will both disappear together)

**Comment by som-snytt** [comment]
@adriaanm Deprecation is already suppressed as you describe.  I don't know about "similarly".  If two members are differentially deprecated, one will disappear first.  In that case, -Xfuture -Xlint could emit the warning, "Don't you know that the method you're calling will be removed before you will?"

**Comment by adriaanm** [comment]
Sorry, this can't be merged anymore, and I didn't want to merge it right before a release.
Could your rebased and resubmit next week -- thanks!

**Comment by soc** [comment]
@adriaanm: Rebased and submitted: https://github.com/scala/scala/pull/2727

**Pull request closed without merging**
