### PR TITLE
removes pre-M4 compatibility stubs for the IDE

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @odersky

**Comment by dragos** [comment]
I'd be interested to know what they were supposed to achieve, because I didn't have to do anything special when they were removed. Maybe the IDE never used those definitions?

**Comment by xeno-by** [comment]
pre-M4 they were mentioned in Definitions.scala

**Comment by dragos** [comment]
The IDE would use only members of `Definitions`, so probably the extra indirection helped. Thanks for the explanations.

**Comment by xeno-by** [comment]
@dragos Iulian, could you, please, sign off the pull request?

**Comment by xeno-by** [comment]
Hey guys, could you, please, just accept this small patch that does nothing, but removes scaffolds?

**Pull request merged**
