### PR TITLE
Default true -Yrepl-{class-based,use-magic-imports}

### LINKED ISSUE #9076: Lambda in REPL (using object-wrappers) + concurrency = deadlock
The following code is a test of generating and using java.util.Spliterator to create a java.util.stream.Stream:

```scala
package xp

import java.util.Spliterator
import java.util.function.Consumer

class Aspi(a: Array[String], private val i0: Int, private var i1: Int) extends Spliterator[String] {
  private var i = i0
  def characteristics = Spliterator.SIZED | Spliterator.SUBSIZED | Spliterator.IMMUTABLE
  def estimateSize = i1-i
  override def getExactSizeIfKnown = i1-i
  def tryAdvance(f: Consumer[_ >: String]): Boolean = {
    println(s"Trying at $i [$i0, $i1)")
    if (i >= i1) false
    else { f.accept(a(i)); i += 1; true }
  }
  def trySplit(): Aspi = {
    if (i1-i < 4) {
      println(s"Could not split [$i $i1)")
      null
    }
    else {
      println(s"Splitting from [$i $i1)")
      val child = new Aspi(a, (i+i1+1)/2, i1)
      i1 = child.i0
      child
    }
  }
}

object Test { def main(args: Array[String]) {
  def nu = new xp.Aspi(Array("one", "two", "three", "four", "five"), 0, 5)
  val st = java.util.stream.StreamSupport.stream(nu, true)
  val c = new java.util.Comparator[String]{ def compare(s: String, t: String) = s compareTo t }
  println(st.map[String]((s: String) => s + s).max(c))
```

This compiles and runs successfully.  However, when the contents of `main` are entered in the REPL, the last line hangs.  Stack trace:

```
"ForkJoinPool.commonPool-worker-1" #14 daemon prio=5 os_prio=0 tid=0x00007f966855f800 nid=0x721f in Object.wait() [0x00007f964a18b000]
   java.lang.Thread.State: RUNNABLE
	at $line6.$read$$iw$$iw$$anonfun$1.apply(<console>:11)
	at $line6.$read$$iw$$iw$$anonfun$1.apply(<console>:11)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at xp.Aspi.tryAdvance(Test.scala:14)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        ...
```

Explicitly creating the SAM like so:

```scala
println(st.map[String](new java.util.function.Function[String, String] {
  def apply(s: String) = s + s
}).max(c))
```

solves the issue.  (Note: I have not tried this on 2.11.5; I assumed 2.12.x was up to date in anything relevant.)

### PR DESCRIPTION
**Pull request by dwijnand**
This makes the following changes to the REPL the default behaviour:

* it now uses the "class-based wrappers" implementation, see #8712
  * among other benefits, this reduces the tendency for e.g. parallel collections to deadlock in the REPL
* it now uses the "magic imports" implementation to reduce wrapping, see #8576
  * this improves performance in long sessions

Fixes scala/bug#9076

### CODE REVIEW

**Comment by som-snytt** [comment]
BTW, there's the old help text that explains boolean flags default to off. You could add, "except when they don't."

**Review by lrytz — APPROVED** [review]
✨

**Comment by SethTisue** [comment]
@dwijnand can I ask you to improve the PR description to make it clear to 2.13.2 users what the user-visible implications of this are?

**Comment by dwijnand** [comment]
Done.  (Gave short introductions but didn't duplicate the entire descriptions - feel free to adapt and/or ping me again about specifics.)

**Comment by SethTisue** [comment]
@dwijnand I added a couple highlights

**Pull request merged**
