### PR TITLE
SI-8050 [Avian] Skip instrumented tests

### PR DESCRIPTION
**Pull request by soc**
Instrumentation is (currently) not supported on Avian.
This causes
- tests instrumented/InstrumentationTest.scala and
- instrumented/inline-in-constructors
  to fail.

Let's skip these tests on Avian.

### CODE REVIEW

**Comment by soc** [comment]
Review by @JamesIry, please!

**Comment by adriaanm** [comment]
It just occurred to me that this filtering mechanism disables the --update-check approach to bulk updates, so this should be used sparingly.

Could we instead simply not run the whole "instrumented" category of tests? Introduce a test blacklist?

**Comment by soc** [comment]
@adriaanm I'm planning to add some `TestSkippedThrowable` to partest which should solve this issue for good, but I have currently dozens of other things which I want to fix in 2.11 first.

**Comment by adriaanm** [comment]
Fair enough -- merging under the assumption you'll clean this up when the partest functionality is there.

**Pull request merged**
