### PR TITLE
Scaladoc tool: fix handling of doc macros for inherited members

### PR DESCRIPTION
**Pull request by Lasering**
scala/bug#9785

### CODE REVIEW

**Comment by Lasering** [comment]
Change to a more thorough test.

@SethTisue I would say this is ready to be reviewed.

**Review by dwijnand — APPROVED** [review]
LGTM.  Thanks!

**Comment by SethTisue** [comment]
(I apologize for not reviewing or nominating a reviewer sooner.)

**Comment by SethTisue** [comment]
This caused a regression: https://github.com/scala/bug/issues/12339

@Lasering You certainly aren't on the hook for fixing it — none of us caught this during review, so we're all equally responsible or not responsible — but if you _want_ to look into it, let us know?

**Pull request merged**
