### PR TITLE
Issue/5604

### PR DESCRIPTION
**Pull request by paulp**
Review by @retronym, @harrah, @odersky .

### CODE REVIEW

**Comment by paulp** [comment]
Ignore unrelated failure; the tests will pass once jenkins figures out a CR from an LF.

**Comment by gkossakowski** [comment]
PLS REBUILD pr-rangepos

**Comment by retronym** [comment]
Vanquishes a pair of separate compilation crashers, documents what's there and what still needs to be done, and well tested. LVGTM, with the caveat that I haven't seen much of this code before.

Perhaps to make it a touch easier to review (given the lateness in the cycle), could you please add a few inline (github) comments to pinpoint the key changes and link them to a behaviour change? And, by contrast, highlight parts in which you simply invoked De Morgan.

**Comment by gkossakowski** [comment]
What about merging this into master instead and potentially cherry-picking for 2.10.1?

The bug is not marked critical and I feel rather uneasy merging related to package objects which have lots of delicate corner cases.

**Comment by paulp** [comment]
All right, I'm going to turn my attention to master.  It sucks having no real idea when 2.10.x will ship - it makes multiple branch management so much harder.  I can't trust any claims because I know how unrealistic they are and always have been. (Unless anyone would like to count the number of commits to 2.10.x since stockholm and compare it to "50" as was suggested as a ballpark figure before we release - keeping in mind we're still nowhere near it.)

It took me two hours to merge a single day's worth of 2.10.x activity into master a couple days ago. But, it will make my life easier in the short term to only worry about master, so sounds good.

**Comment by paulp** [comment]
@retronym: some comments in #1383.

**Comment by gkossakowski** [comment]
@paulp: I hear you. Believe me that I'm not satisfied with the current state of affairs but I don't think there's that much to be done. When it comes to release date of 2.10.0 the definitive answer can be found here:
https://issues.scala-lang.org/secure/IssueNavigator.jspa?mode=hide&requestId=11807

We are 12 blocker tickets away from RC1.

**Pull request closed without merging**
