### PR TITLE
WIP, don't merge: see if sbt 0.13.13-RC1 works

### PR DESCRIPTION
**Pull request by SethTisue**
in case this turns up anything we want to report to the sbt folks.
fyi @dwijnand

### CODE REVIEW

**Comment by dwijnand** [comment]
Cool, it went green.

**Comment by lrytz** [comment]
Should this be closed? Or should we merge the first of the two commits?

**Comment by dwijnand** [comment]
Btw, the first of the two commits is #5386.

**Comment by SethTisue** [comment]
closing, #5386 is the one to keep

**Comment by SethTisue** [comment]
reopening so we can see what Jenkins has to say about 0.13.13-RC3

**Comment by SethTisue** [comment]
reopening so we can see what Jenkins has to say about 0.13.13-RC3

rebased, also

**Comment by dwijnand** [comment]
green again 🎉

**Comment by retronym** [comment]
@SethTisue would be good to merge 61a5a6e ASAP to make it more convenient for us to try out 0.13.3-RCX locally.

**Comment by retronym** [comment]
Also, we should aim to get these changes back to 2.11.x.

**Comment by dwijnand** [comment]
Just need to merge #5386 to do that..

**Comment by SethTisue** [comment]
I merged #5386. Can't say backporting to 2.11 interests me.

**Pull request closed without merging**
