### PR TITLE
Merge/2.11 to 2.12 apr 1

### PR DESCRIPTION
**Pull request by lrytz**
A big one..

The conflict in `Promise.scala` is due to those two commits:
- 2.11.x: https://github.com/scala/scala/commit/1a7f4ec0961ffcddd283d0c372443983a87833dc
- 2.12.x: https://github.com/scala/scala/commit/fa0743c32338f147eaf7a5d69566bbc15d193f85

Please check if the result is correct: https://github.com/lrytz/scala/blob/f49b447cf9d08524c08ff9f57cf04938806f6f73/src/library/scala/concurrent/Promise.scala#L63

Conflict in `names-defaults-neg.check`:
- 2.11.x: https://github.com/scala/scala/commit/a4a892fb0196f2f66d86f9cfa508deabe7d2aaae
- 2.12.x: https://github.com/scala/scala/commit/e1c6f0eacd5372e5ee4fe267c6c5b7124cd162f3

Manual merge, should be fine.

Confilct in `Template.scala`
- 2.11.x: https://github.com/scala/scala/commit/c851a8d4bc432731242075c01f6f8ca500458e67#diff-14eb65dc1766bea637f449438d6a926aL106
- 2.12.x: https://github.com/scala/scala/commit/18233ec89b8bd629eccc0696ed7716e35e138224#diff-14eb65dc1766bea637f449438d6a926aL106

Manual merge, should be fine. The 2.12.x commit (https://github.com/scala/scala/pull/4407) should be backported to 2.11.x, in fact.

The conflict in build.number is expected, it's set to 2.12.0 in the 2.12.x branch.

```
lucmac:scala luc$ git log --pretty=oneline --decorate --abbrev-commit -n 1
ebf0976 (HEAD, upstream/2.12.x, origin/2.12.x, 2.12.x) Merge pull request #4406 from kzys/8940-scaladoc-alphabetic-button

lucmac:scala luc$ git checkout -b merge/2.11-to-2.12-apr-1

lucmac:scala luc$ export MB=$(git merge-base head upstream/2.11.x)

lucmac:scala luc$ git log --graph --oneline --decorate $MB..upstream/2.11.x
*   347c475 (upstream/2.11.x, 2.11.x) Merge pull request #4423 from lrytz/merge/2.10-to-2.11-apr-1
|\  
| *   cde62f1 (origin/merge/2.10-to-2.11-apr-1, merge/2.10-to-2.11-apr-1) Merge branch '2.10.x' into merge/2.10-to-2.11-apr-1
| |\  
|/ /  
| *   e02a2da (upstream/2.10.x, upstream-writable/2.10.x, origin/2.10.x, 2.10.x) Merge pull request #4417 from retronym/backport/flaky
| |\  
| | * 5d5de4d (retronym/backport/flaky) [backport] SI-8689 Make a Future test case determistic
| |/  
| * 8859afb Fix link...
| * a5770ac 2.10.5  is it for 2.10.x
| *   88c5407 (tag: v2.10.5) Merge pull request #4365 from adriaanm/2.10.x
| |\  
| | * 3285445 Publish to sonatype staging.
| |/  
| *   8f0819a Merge pull request #4359 from adriaanm/2.10.x
| |\  
| | * 132d99f Port old 2.10 release script to new CI.
| |/  



* |   a49ac23 (origin/2.11.x) Merge pull request #4422 from lrytz/t8940-2.11
|\ \  
| * | bb6a896 (origin/t8940-2.11, t8940-2.11) [nomerge] SI-8940 Scaladoc: Fix "Order by Alphabetical" button
|/ /  



* |   32f520f (upstream-writable/2.11.x) Merge pull request #4418 from lrytz/t8731-relax
|\ \  
| * | bf63988 (origin/t8731-relax, t8731-relax) SI-8731 don't issue a @switch warning for two-case matches
* | |   8108ed6 Merge pull request #4399 from lambdista/scaladoc-typo-1
|\ \ \  
| * | | 7c162d4 fix typo in scaladoc
* | | |   a25b3f7 Merge pull request #4375 from som-snytt/issue/8861
|\ \ \ \  
| * | | | d04cd7b (som-snytt/issue/8861) SI-8861 Handle alias when probing for Any
* | | | |   c8757cd Merge pull request #4414 from retronym/topic/flaky
|\ \ \ \ \  
| * | | | | b31098c (retronym/topic/flaky) SI-8689 Make a Future test case determistic
|/ / / / /  
* | | | |   955eb21 Merge pull request #4318 from soc/topic/remove-deprecation-warnings
|\ \ \ \ \  
| * | | | | d4546fd Removed warnings
| * | | | | 86999ed new{Term,Type}Name→{Term,Type}Name, tpename/nme→{type,term}Names
| * | | | | e5bfc1c Deprecations: Use of isPackage, hasSymbol, getter, setter...
* | | | | |   c505b6c Merge pull request #4410 from gourlaysama/wip/t9038-encoding-issues
|\ \ \ \ \ \  
| |_|_|_|/ /  
|/| | | | |   
| * | | | | 6e6632e (gourlaysama/wip/t9038-encoding-issues) SI-9038 fix scaladoc syntax highlightning to leave unicode alone
| | |_|/ /  
| |/| | |   
* | | | |   6372df7 Merge pull request #4361 from retronym/ticket/9182
|\ \ \ \ \  
| * | | | | 06e7e34 (retronym/ticket/9182) SI-9182 Fix runtime reflection with package object, overloads
* | | | | |   439b3eb Merge pull request #4358 from xeno-by/topic/names-defaults
|\ \ \ \ \ \  
| |_|_|/ / /  
|/| | | | |   
| * | | | | bb7f2b8 better errors for macro applications with wrong number of arguments
| |/ / / /  
* | | | |   4a3e937 Merge pull request #4310 from som-snytt/issue/9127-b
|\ \ \ \ \  
| * | | | | dcd4d67 (som-snytt/issue/9127-b) SI-9127 Xlint doesn't think spaces are significant
* | | | | |   de4edd4 Merge pull request #4397 from retronym/topic/icode-diagnostic
|\ \ \ \ \ \  
| |_|_|/ / /  
|/| | | | |   
| * | | | | bdc0b63 (retronym/topic/icode-diagnostic) Improve diagnostic error on failed genLoadIdent
* | | | | |   2dc40cc Merge pull request #4380 from retronym/ticket/9020
|\ \ \ \ \ \  
| * | | | | | bf01acd (retronym/ticket/9020) SI-9020 Avoid spurious value discarding warning post-typer
* | | | | | |   4f05b19 Merge pull request #4360 from retronym/ticket/9170
|\ \ \ \ \ \ \  
| * | | | | | | 8a332d9 (retronym/ticket/9170) SI-9170 Fix resident compilation / specialization NPE
| | |_|_|/ / /  
| |/| | | | |   
* | | | | | |   ee864c1 Merge pull request #4364 from som-snytt/issue/sessiontest
|\ \ \ \ \ \ \  
| * | | | | | | a180f5f (som-snytt/issue/sessiontest) SI-9170 More flexible SessionTest
| | |_|_|/ / /  
| |/| | | | |   
* | | | | | |   0abafb5 Merge pull request #4387 from retronym/ticket/9231
|\ \ \ \ \ \ \  
| * | | | | | | 2dc3b19 (retronym/ticket/9231) SI-9231 Don't attempt implicit search for erroneous parameter
| | |_|/ / / /  
| |/| | | | |   



* | | | | | |   f25a78e Merge pull request #4371 from adriaanm/2.11.6-bump
|\ \ \ \ \ \ \  
| * | | | | | | b1b7f89 Set scala.full.version during bootstrap,
| * | | | | | | 6b304a8 Bump versions after 2.11.6 release.



* | | | | | | |   fcc20fe Merge pull request #4378 from som-snytt/issue/9102
|\ \ \ \ \ \ \ \  
| * | | | | | | | 0a8dfd9 (som-snytt/issue/9102) SI-9102: Improve test
| * | | | | | | | d7b99c3 SI-9102: Reflect method invoke with mixed args
| | |_|_|_|_|/ /  
| |/| | | | | |   
* | | | | | | |   7741d3f Merge pull request #4381 from khernyo/issue/9219
|\ \ \ \ \ \ \ \  
| * | | | | | | | 8e0a386 SI-9219 Stream toString returns unexpected result
| | |_|/ / / / /  
| |/| | | | | |   
* | | | | | | |   eb05bea Merge pull request #4393 from soc/patch-2
|\ \ \ \ \ \ \ \  
| * | | | | | | | 96d1763 Move all modifiers to the same level
* | | | | | | | |   40e08ea Merge pull request #4389 from retronym/topic/jesper
|\ \ \ \ \ \ \ \ \  
| |_|_|_|_|_|_|/ /  
|/| | | | | | | |   
| * | | | | | | | d0181ab (retronym/topic/jesper) Resurrect a test for type inference
| | |/ / / / / /  
| |/| | | | | |   
* | | | | | | |   88d4c15 Merge pull request #4338 from Ichoran/opt-SeqLike-2.11.x
|\ \ \ \ \ \ \ \  
| * | | | | | | | 049e66c Performance optimization - SeqLike
* | | | | | | | |   3c7b1e3 Merge pull request #4312 from lrytz/opt/inlining
|\ \ \ \ \ \ \ \ \  
| * | | | | | | | | c2ab768 (origin/opt/inlining) Don't inline methods containing super calls into other classes
| * | | | | | | | | ba32512 Test case for SI-9111 workaround.
| * | | | | | | | | 2d88143 Ensure to re-write only trait method calls of actual trait methods
| * | | | | | | | | f8731c5 Issue inliner warnings for callsites that cannot be inlined
| * | | | | | | | | 57c0720 Limit the size of the ByteCodeRepository cache
| * | | | | | | | | a4e71b1 Cast receiver if necessary when rewriting trait calls to impl method
| * | | | | | | | | f8bb3d5 Inline final methods defined in traits
| * | | | | | | | | 027e979 Workaround for SI-9111
| * | | | | | | | | 4e98245 Don't crash the inliner in mixed compilation
| * | | | | | | | | 37c9165 After removing a live handler, need to re-run unreachableCode
| * | | | | | | | | ea10434 Looking up the ClassNode for an InternalName returns an Option
| * | | | | | | | | 37f7b76 Integrate the inliner into the backend pipeline
| * | | | | | | | | 0d8b324 Build a call graph for inlining decisions
| * | | | | | | | | 4ffe934 Reuse the same compiler instance for all tests in a JUnit class
| * | | | | | | | | b34a452 Tools to perform inlining.
| * | | | | | | | | ff67161 Find instructions that would cause an IllegalAccessError when inlined
* | | | | | | | | |   13ed362 Merge pull request #4391 from robertzk/2.11.x
|\ \ \ \ \ \ \ \ \ \  
| |_|_|_|/ / / / / /  
|/| | | | | | | | |   
| * | | | | | | | | b19c675 Fix typo in brutallyResetAttrs comment
|/ / / / / / / / /  
* | | | | | | | |   dfe66d4 Merge pull request #4388 from retronym/ticket/9223
|\ \ \ \ \ \ \ \ \  
| * | | | | | | | | 79c0537 (retronym/ticket/9223) SI-9223 By-name constructor params should not be aliased
| | |_|/ / / / / /  
| |/| | | | | | |   
* | | | | | | | |   f0993e5 Merge pull request #4383 from lrytz/upgrade-asm-squashed
|\ \ \ \ \ \ \ \ \  
| * | | | | | | | | 139a05c (origin/upgrade-asm-squashed) Upgrade ASM to 5.0.3
| * | | | | | | | | 992b58f Clarifications to src/asm/README
| |/ / / / / / / /  
* | | | | | | | |   9fd9323 Merge pull request #4384 from sschaef/issue9226-npe-in-gen-asm
|\ \ \ \ \ \ \ \ \  
| |/ / / / / / / /  
|/| | | | | | | |   
| * | | | | | | | edf954f SI-9226 Fix NPE in GenASM.writeIfNotTooBig
|/ / / / / / / /  
* | | | | | | |   fa33395 Merge pull request #4377 from lrytz/opt/scalaInlineInfo
|\ \ \ \ \ \ \ \  
| |/ / / / / / /  
| | | / / / / /   
| |_|/ / / / /    
|/| | | | | |     
| * | | | | | 42054a1 Emit the ScalaInlineInfo attribute under GenASM
| | |_|/ / /  
| |/| | | |   
* | | | | | e8e9c0d Quote `_` properly in lexical syntax.
| |_|/ / /  
|/| | | |   
* | | | | 52d4a5a (retronym/2.11.x) Fix links to EPFL CI and nightly downloads.
* | | | |   092690e (tag: v2.11.6) Merge pull request #4357 from retronym/merge/2.10.x-to-2.11.x-20150224
|\ \ \ \ \  
| |_|_|/ /  
|/| | | |   
| * | | |   ce68a97 (retronym/merge/2.10.x-to-2.11.x-20150224) Merge commit 'b2f5101' into merge/2.10.x-to-2.11.x-20150224
| |\ \ \ \  
| | | |_|/  
| | |/| |   
| | * | |   b2f5101 Merge pull request #4307 from som-snytt/issue/4339-2.10-b
| | |\ \ \  
| | | * | | b4e3bec (som-snytt/issue/4339-2.10-b) [backport] SI-9060 Backpatch fifth-edition names
| | | * | | fe7867f [backport] SI-4339 Event errors and attribute fix
| | * | | |   47be353 Merge pull request #4351 from adriaanm/scaladoc-2.10
| | |\ \ \ \  
| | | * | | | f95b5b9 Scaladoc js location synch more robust
| | |/ / / /  
| * | | | |   1a7f4ec Merge commit 'ad845ff' into merge/2.10.x-to-2.11.x-20150224
| |\ \ \ \ \  
| | |/ / / /  
| | * | | |   ad845ff (opt/2.10.x) Merge pull request #4289 from retronym/ticket/8689
| | |\ \ \ \  
| | | * | | | bf20737 (retronym/ticket/8689) SI-8689 Avoid internal error in Promise after sequence of completions
| | | |/ / /  
| * | | | |   5601a5b Merge commit 'fbbd1b2' into merge/2.10.x-to-2.11.x-20150224
| |\ \ \ \ \  
| | |/ / / /  
| | * | | |   fbbd1b2 Merge pull request #4303 from milessabin/topic/backport-7753
| | |\ \ \ \  
| | | |/ / /  
| | |/| | |   
| | | * | | 2f5ff59 Backported fix for SI-7753 to 2.10.x.
| | |/ / /  
| | * | |   ad0ddd4 Merge pull request #4290 from adriaanm/2.10.x
| | |\ \ \  
| | | * | | 706d68f New CI validation scripts
| | |/ / /  
| | * | | 3115f88 Merge pull request #4186 from som-snytt/issue/9027-backport
| | * | | 736293a (som-snytt/issue/9027-backport) SI-9027 Backport xml parser fix
| |  / /  
* | | |   dff4799 Merge pull request #4353 from xeno-by/topic/plugin-enter-stats
|\ \ \ \  
| * | | | 97f7f58 fixes pluginsEnterStats
| | |/ /  
| |/| |   
* | | |   9fb6760 Merge pull request #4354 from Ichoran/issue/9172
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | 8cc66b0 SI-9172  FlatMapped views throw exception on filter
|/ / /  
* | |   3a32ae3 Merge pull request #4350 from adriaanm/scaladoc
|\ \ \  
| * | | cafed1b Scaladoc js location synch more robust
|/ / /  
* | |   b07fab8 Merge pull request #4344 from Ichoran/issue/9126
|\ \ \  
| |_|/  
|/| |   
| * | 1d4a1f7 SI-9126  Missing .seqs causes problems with parallel GenXs
|/ /  
* |   1887009 Merge pull request #4347 from retronym/ticket/8801
|\ \  
| |/  
|/|   
| * cbdb95f (retronym/ticket/8801) SI-8801 Another test for fixed exponential-time compilation
* |   a3a794f Merge pull request #4340 from retronym/topic/infix-completion
|\ \  
| * | 9cd5c88 (retronym/topic/infix-completion) Remove incorrect completions: implicits can't add type members
| * | a8ec6c9 SI-9153 More complete and stable results for completions
| * | 5a89475 Cache name for dummy argument used in implicit search
* | |   2d26cac Merge pull request #4337 from Ichoran/opt-IterLike-2.11.x
|\ \ \  
| * | | ad7a2f2 Optimization of IterableLike.scala
| |/ /  
* | |   d93fc01 Merge pull request #4330 from Ichoran/issue/8917
|\ \ \  
| * | | c9930bf SI-8917  collection.mutable.BitSet's &= operator doesn't clear end
| |/ /  
* | |   812790a Merge pull request #4319 from axel22/fix-si-7943
|\ \ \  
| * | | da2d4ca Fix SI-7943 -- make `TrieMap.getOrElseUpdate` atomic.
* | | |   2b90b89 Merge pull request #4345 from retronym/topic/scaladoc-test-java8
|\ \ \ \  
| * | | | 808eca6 (retronym/topic/scaladoc-test-java8) Fix the Scaladoc tests under Java 8
* | | | |   9b9bd64 Merge pull request #4346 from retronym/ticket/9164
|\ \ \ \ \  
| |/ / / /  
|/| | | |   
| * | | | 6818009 (retronym/ticket/9164) SI-9164 Fix thread safety of Scaladoc diagram generator
|/ / / /  
* | | |   4262636 Merge pull request #4326 from JustinPihony/ticket/9148
|\ \ \ \  
| * | | | c851a8d SI-9148: Appends companion type to link tooltips
* | | | |   9a3ea24 Merge pull request #4329 from adriaanm/followup-4235
|\ \ \ \ \  
| * | | | | e53165c Correct dependency for test.junit.comp
| * | | | | bff8636 Use if/then/else to avoid box(unbox(_))
| * | | | | 788f388 Simplify `ClassTag.unapply`
| * | | | | f7bc59b Scala.js-friendly `ClassTag.unapply`
* | | | | |   7a872f4 Merge pull request #4335 from lylek/issue/4959
|\ \ \ \ \ \  
| * | | | | | 32c422a SI-4959 - UNIX bin scripts now work for paths with spaces
| | |_|_|/ /  
| |/| | | |   
* | | | | |   e8cf902 Merge pull request #4309 from som-snytt/issue/9116-b
|\ \ \ \ \ \  
| * | | | | | 5412766 (som-snytt/issue/9116-b) SI-9116 Set.subsets has a param list
| | |_|/ / /  
| |/| | | |   
* | | | | |   e6a8b64 Merge pull request #4299 from michaelpigg/si-7660
|\ \ \ \ \ \  
| * | | | | | d95269e SI-7660: Document behaviour of Set#++ for duplicate elements
* | | | | | |   ea17de1 Merge pull request #4341 from retronym/ticket/9157
|\ \ \ \ \ \ \  
| | |_|_|_|_|/  
| |/| | | | |   
| * | | | | | b6cbee9 (retronym/ticket/9157) SI-9157 Avoid exponential blowup with chained type projections
| | |_|/ / /  
| |/| | | |   
* | | | | |   3a3d0de (opt/2.11.x) Merge pull request #4328 from adriaanm/rework-4230
|\ \ \ \ \ \  
| |/ / / / /  
|/| | | | |   
| * | | | | 01fad26 SI-9059 Random.alphanumeric is inefficient
| | |_|/ /  
| |/| | |   
* | | | |   da49d9a Merge pull request #4296 from lrytz/t9105
|\ \ \ \ \  
| * | | | | c283ce1 (origin/t9105) Test java reflection on scala library / reflect / compiler jars
| * | | | | 357c157 IntelliJ project file fix
| * | | | | b2e22fa Fix InnerClass / EnclosingMethod for closures nested in value classes
| * | | | | cd8f2f3 Fix InnerClass/EnclosingMethod for trait impl and specialized classes
| * | | | | 1437aa8 SI-9124 fix EnclosingMethod of classes nested in implOnly trait defs
| * | | | | 0bcc871 SI-9105 Fix EnclosingMethod for classes defined in lambdas
* | | | | |   3b93e1f Merge pull request #4304 from adriaanm/rebase-4219
|\ \ \ \ \ \  
| |_|/ / / /  
|/| | | | |   
| * | | | | 51800ce SI-8818 FreshName extractor forgives suffix
* | | | | |   4554a10 Merge pull request #4195 from lrytz/t8841
|\ \ \ \ \ \  
| * | | | | | a4a892f SI-8841 report named arg / assignment ambiguity also in silent mode.
|  / / / / /  
* | | | | | 73478ea Some notes on reviewing.
* | | | | |   407db03 Merge pull request #4324 from adriaanm/jline-2.12.1
|\ \ \ \ \ \  
| |_|_|_|_|/  
|/| | | | |   
| * | | | | 70837e5 SI-8759 bump jline: support alt-gr-based keyboards
|/ / / / /  
* | | | |   d14e065 Merge pull request #4315 from adriaanm/talk-to-us
|\ \ \ \ \  
| |_|_|_|/  
|/| | | |   
| * | | | a5d9085 The talk-to-a-human option
* | | | |   41cee92 Merge pull request #4263 from lrytz/t9097
|\ \ \ \ \  
| |/ / / /  
|/| | | |   
| * | | | 486f92c (retronym/review/4263) Refactor transformStats impls for consistency
| * | | | a8bfa82 (som-snytt/review/9097) SI-9097 Consolidate test
| * | | | a8b6e36 SI-9097 Remove spurious warning about conflicting filenames
|  / / /  
* | | |   27988ca Merge pull request #4280 from kanielc/SI-9095
|\ \ \ \  
| * | | | f2d0231 SI-9095 Memory leak in LinkedHasMap and LinkedHashSet
* | | | |   e8365de Merge pull request #4209 from kanielc/SI-8988
|\ \ \ \ \  
| |_|/ / /  
|/| | | |   
| * | | | d1d3225 SI-8988 Escaping character in StringLike.split(c) prevents usage of optimized String.split code path
|  / / /  
* | | |   9d09247 Merge pull request #4288 from adriaanm/retronym-ticket/9041
|\ \ \ \  
| * | | | 1970a83 SI-9041 Avoid unreported type error with overloading, implicits
| |/ / /  
* | | |   2b6a197 Merge pull request #4274 from retronym/ticket/9123
|\ \ \ \  
| |_|/ /  
|/| | |   
| * | | 9735108 (retronym/ticket/9123) SI-9123 More coherent trees with patmat, dependent types
|  / /  
* | |   d7b1152 (som-snytt/2.11.x) Merge pull request #4298 from adriaanm/contrib
|\ \ \  
| |_|/  
|/| |   
| * | c88e232 IDE setup section
| * | 65599fc Load balance across CONTRIBUTING/README
| * | 55a7a71 Rewrite contrib guidelines: shorter & friendlier
* | |   efbaf1d Merge pull request #4213 from soc/topic/scala-partest-1.0.3
|\ \ \  
| * | | e4395f9 Update scala-partest dependency to 1.0.3
|  / /  
* | |   c23100b Merge pull request #4293 from BartoszJanota/patch-1
|\ \ \  
| * | | 720ce5d Scala doc update (sliding method). Added info about default step set to 1. Reading this doc (having no code) can be ambiguous.
| | |/  
| |/|   
* | |   e3a171d Merge pull request #4295 from retronym/ticket/9135
|\ \ \  
| * | | 6b26f3b (retronym/ticket/9135) SI-9135 Fix NPE, a regression in the pattern matcher
* | | |   e822886 Merge pull request #4251 from retronym/ticket/6502
|\ \ \ \  
| * \ \ \   c6c9565 (retronym/ticket/6502) Merge pull request #9 from som-snytt/review/6502
| |\ \ \ \  
| | * | | | 596c51c (som-snytt/review/6502) SI-6502 Convert test to asserts
| |/ / / /  
| * | | | a3c2b55 REPL: Tread EOF a "no" in the "yes"/"no" prompt.
| * | | | 09ce5c3 SI-6502 More robust REPL :require
|  / / /  
* | | |   73986e6 Merge pull request #4248 from retronym/ticket/9086
|\ \ \ \  
| |/ / /  
|/| | |   
| * | | 3c97888 (retronym/ticket/9086) SI-9086 Fix regression in implicit search
|  / /  
* | |   67fd655 Merge pull request #4133 from som-snytt/issue/8976
|\ \ \  
| |_|/  
|/| |   
| * | 6ba7068 (som-snytt/issue/8976) SI-8976 MutableList.tail.iterator.size is length
|  /  
* |   745ed5c Merge pull request #4204 from mpociecha/correct-decimal-marks-in-tests
|\ \  
| * | 7dc25f9 Fix problems with a locale-dependent decimal mark in StringContextTest
|  /  
* |   fc54427 Merge pull request #4233 from kanielc/SI-7770
|\ \  
| * | 08f27bb SI-7770 mutable.BitSet.toImmutable isn't immutable
|  /  
* |   92dce69 Merge pull request #4260 from retronym/ticket/9093
|\ \  
| * | c30ed29 (retronym/ticket/9093) SI-9093 Fix value discarding / multiple param list crasher
|  /  
* |   b605838 Merge pull request #4252 from retronym/ticket/9050
|\ \  
| * | 286dafb (retronym/ticket/9050) SI-9050 Fix crasher with value classes, recursion
|  /  
* |   fdb3d96 Merge pull request #4245 from dickwall/doc/scaladoc-concurrent-package
|\ \  
| * | 207b67a Added package scaladoc for the concurrent package.
|  /  
* |   c52083b Merge pull request #4292 from retronym/ticket/9133
|\ \  
| * | 41dbde9 (retronym/ticket/9133) Silence a feature warning in JUnit test code.
| * | 1a56eb3 SI-9133 Harden against infinite loop in NoSymbol.owner
| |/  
* |   f79b40e Merge pull request #4216 from som-snytt/issue/7623
|\ \  
| |/  
|/|   
| * 43818d4 (som-snytt/issue/7623) SI-7623 Trailing sequence wildcard warning
*   5d7098c Merge pull request #4259 from mzitnik/2.11.x
|\  
| * fb04376 SI-9072 Vector ++ concatenation of parallel collection cause inconsistent results
*   41a5f45 Merge pull request #4276 from romanowski/2.11.x
|\  
| * 06ba676 Fix intellij 14 setup script to read scala version from version.properties
*   c756d25 Merge pull request #4257 from 193s/2.11.x
|\  
| * 0a1b956 fix definition of TRY in the language spec
* af77f97 Merge pull request #4226 from jhegedus42/patch-1
* c0183ae Update 03-types.md


lucmac:scala luc$ git merge fcc20fe
CONFLICT (content): Merge conflict in test/files/neg/names-defaults-neg.check
CONFLICT (content): Merge conflict in src/scaladoc/scala/tools/nsc/doc/html/page/Template.scala
CONFLICT (content): Merge conflict in src/library/scala/concurrent/Promise.scala

[fix conflicts]

lucmac:scala luc$ git add -A
lucmac:scala luc$ git commit

lucmac:scala luc$ git merge f25a78e
CONFLICT (content): Merge conflict in build.number

[fix conflicts]

lucmac:scala luc$ git add -A
lucmac:scala luc$ git commit

lucmac:scala luc$ git merge 32f520f

lucmac:scala luc$ git merge a49ac23 -s ours

lucmac:scala luc$ git log --graph --pretty=oneline --decorate --abbrev-commit -n 4
*   4a41e81 (HEAD, merge/2.11-to-2.12-apr-1) Merge commit 'a49ac23' into merge/2.11-to-2.12-apr-1
|\  
| *   a49ac23 (origin/2.11.x) Merge pull request #4422 from lrytz/t8940-2.11
| |\  
| | * bb6a896 (origin/t8940-2.11, t8940-2.11) [nomerge] SI-8940 Scaladoc: Fix "Order by Alphabetical" button
| |/  
* |   3aea921 Merge commit '32f520f' into merge/2.11-to-2.12-apr-1
|\ \  
| |/  

lucmac:scala luc$ git diff 3aea921
lucmac:scala luc$ 

lucmac:scala luc$ git merge 347c475

lucmac:scala luc$ git diff 4a41e81
lucmac:scala luc$ 

lucmac:scala luc$ git log --graph --pretty=oneline --decorate --abbrev-commit -n 2
*   f49b447 (HEAD, merge/2.11-to-2.12-apr-1) Merge commit '347c475' into merge/2.11-to-2.12-apr-1
|\  
| *   347c475 (upstream/2.11.x, 2.11.x) Merge pull request #4423 from lrytz/merge/2.10-to-2.11-apr-1
```

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @retronym

**Comment by lrytz** [comment]
for some reason, scabot doesn't trigger any builds for the merge commits.

**Comment by retronym** [comment]
- [x] Promise.scala merge looks correct to me.

**Comment by retronym** [comment]
LGTM

**Comment by adriaanm** [comment]
Not sure why the bot isn't building those last few commits. Started https://scala-ci.typesafe.com/job/scala-2.11.x-validate-main/961/console manually

**Comment by adriaanm** [comment]
Last commit in the merge fails in the same way as we're seeing at other PRs: 

```

quick.comp:
    [mkdir] Created dir: /home/jenkins/workspace/scala-2.11.x-validate-test/build/quick/classes/compiler
[quick.compiler] Compiling 317 files to /home/jenkins/workspace/scala-2.11.x-validate-test/build/quick/classes/compiler
[quick.compiler] /home/jenkins/workspace/scala-2.11.x-validate-test/src/compiler/scala/tools/nsc/typechecker/AnalyzerPlugins.scala:372: warning: match may not be exhaustive.
[quick.compiler] It would fail on the following input: List(_)
[quick.compiler]       results.flatMap { case (p, Some(result)) => Some((p, result)); case _ => None } match {
[quick.compiler]                       ^
[quick.compiler] /home/jenkins/workspace/scala-2.11.x-validate-test/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala:868: warning: match may not be exhaustive.
[quick.compiler] It would fail on the following input: List(_)
[quick.compiler]         seenTypes(i) match {
[quick.compiler]                  ^
[quick.compiler] error: symbol value x5#781214 does not exist in scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$PatternBoundToUnderscore.unapply, which contains locals variable eqEqTemp$4#1279646,value x#781237,variable eqEqTemp$3#1279642,value x2#781208,value x1#781206,value pat#484460
[quick.compiler] error: scala.reflect.internal.FatalError: symbol value x5#781214 does not exist in scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$PatternBoundToUnderscore.unapply, which contains locals variable eqEqTemp$4#1279646,value x#781237,variable eqEqTemp$3#1279642,value x2#781208,value x1#781206,value pat#484460
[quick.compiler]    at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
[quick.compiler]    at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
[quick.compiler]    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.genLoadIdent$1(GenICode.scala:886)
```

**Comment by retronym** [comment]
That intermittent failure is being investigated as https://issues.scala-lang.org/browse/SI-9264.

**Comment by retronym** [comment]
We've got a tick on  f49b447 (after a retry to workaround SI-9264), so I'm going to merge this one now.

**Comment by lrytz** [comment]
woohoo

**Pull request merged**
