### PR TITLE
Respect `-Xlint:-multiarg-infix` to suppress lint at callsite

### LINKED ISSUE #12058: scalac -Xlint:-multiarg-infix does not suppress multiarg-infix linting as expected
Expect to be able to disable this linter, as it flags common idioms used by Slick.

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#12058

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
LGTM. The alternative would be to turn it into a deprecation, but multiarg-infix is not deprecated in dotty either (not even with `-source:3.1`).

**Comment by dwijnand** [comment]
(Feels like a too niche bug fix to be noteworthy to me...)

**Comment by som-snytt** [comment]
The hyphen `-Xlint:-multiarg-infix` means turn it off. Also chose a spelling-neutral word.

IIRC there was a warning difference between application and definition.

**Comment by dwijnand** [comment]
My point was it was always on (for applications or definitions) and it wouldn't respect a desire to switch it off, but I guess it was too terse to be communicate that clearly.

**Pull request merged**
