### PR TITLE
SI-6089 pt2: _ is tailpos in `_ || _` and `_ && _`

### PR DESCRIPTION
**Pull request by adriaanm**
pull #939 made tail position detection for matches more strict to fix SI-6089,
but became too strict: need to include the tail positions `_` in `_ || _` and `_ && _`.

review by @jsuereth

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM - Should we make a test?  I might be able to get to that, assuming this fixes community build.

**Comment by adriaanm** [comment]
I can add a test tomorrow, assuming this fixes the community build

**Comment by jsuereth** [comment]
Note:  This build lets me build Akka.   You sir, win a beer.   As long as you get that test in when you have time :)

**Comment by adriaanm** [comment]
Cool! I think we're roughly even, but I'll take you up on that anyway :-! Should have that test in tomorrow.

**Pull request merged**
