### PR TITLE
Based on Adriaan's pull request 402

### PR DESCRIPTION
**Pull request by VladUreche**
https://github.com/scala/scala/pull/402

Now it passes the stability check by disabling the code that changes the access rights in the inliner. We'll need a better mechanism for making fields public. See https://groups.google.com/forum/?hl=en&fromgroups#!topic/scala-internals/yGmOkBn9Gmk for more details.

### CODE REVIEW

**Comment by VladUreche** [comment]
I noticed the build fails 2 testcases, both in the normal and optimized builds. I think it's a false alarm because the changes are stacked on top of a broken commit. Nevertheless, @paulp and @adriaanm, be warned:

```
[partest] testing: [...]/files/neg/t5666.scala                                  [FAILED]
[partest] t5666.scala:2: error: class Any is abstract; cannot be instantiated
[partest]   new Any
[partest]   ^
[partest] t5666.scala:3: error: class AnyVal is abstract; cannot be instantiated
[partest]   new AnyVal
[partest]   ^
[partest] t5666.scala:13: error: trait Nothing is abstract; cannot be instantiated
[partest]   new Nothing
[partest]   ^
[partest] three errors found
```

and

```
[partest] testing: [...]/files/run/t3569.scala                                  [FAILED]
[partest] 1
[partest] private final int Test$X.val1
[partest] private final int Test$X.val2
[partest] private final int Test$X.val3
[partest] private int Test$X.lval1
[partest] private int Test$X.lval2
[partest] private int Test$X.lval3
[partest] private int Test$X.var1
[partest] private int Test$X.var2
[partest] private int Test$X.var3
[partest] private int Test$X.x
[partest] private volatile int Test$X.bitmap$priv$0
[partest] public volatile int Test$X.bitmap$0
[partest] private final int Test$Y.z1
[partest] private final int Test$Y.z2
[partest] private int Test$Y.x
[partest] private int Test$Y.y
```

**Comment by adriaanm** [comment]
thanks for working on this, @VladUreche, but isn't this then going to break a lot of other people's code that relies on inlining private fields? Also, the t3569 failure is new, but t5666 has since been fixed in trunk.

**Comment by VladUreche** [comment]
I hope nobody relied on the fields becoming private thanks to the inliner, that would be a very bad assumption to make. Also note that the chances of getting that working are pretty narrow, as type checker would reject code that accesses not-yet-public fields. The only get it working is to compile a part of the code with optimization and access a previously-private field from the rest of the code. That seems unlikely to me.

As for t3569, it produces the same output even without -optimize, so I don't think it's related to this patch.

**Comment by adriaanm** [comment]
sorry, i meant to say that people might be disappointed about having less code inlined
you say in the commit message that the inliner becomes nearly useless, which is a bit worrying, no?

anyway, as I said on scala-internals:
How about generating a name-mangled public forwarder to the private method that is needed elsewhere for inlining to succeed?

**Comment by paulp** [comment]
On Mon, Apr 16, 2012 at 10:37 AM, Adriaan Moors
reply@reply.github.com
wrote:

> sorry, i meant to say that people might be disappointed about having fewer code inlined
> you say in the commit message that the inliner becomes nearly useless, which is a bit worrying, no?
> 
> anyway, as I said on scala-internals:
> How about generating a name-mangled public forwarder to the private method that is needed elsewhere for inlining to succeed?

I think it's a lovely idea, but for the purposes of releasing
something in the next few hours, I think having virtpatmat on by
default is very important and that the inliner not operating at peak
efficiency is very unimportant.

**Pull request merged**
