### PR TITLE
Merge 2.12 to 2.13 [ci: last-only]

### PR DESCRIPTION
**Pull request by lrytz**
The only maybe interesting change is in fe5611a7cd9d9d3eca2a15c821c393f878ef7d0e which adds a few overrides to the iterators for small maps (to make the test pass).

```
➜  scala13 git:(merge-2.12-to-2.13-jun-19) git log HEAD --oneline -n 1 | cat
bc040e4c0b Merge pull request #9067 from jyotisachdeva57/docs-grammatical-error-correction

➜  scala13 git:(merge-2.12-to-2.13-jun-19) git log upstream/2.12.x --oneline -n 1 | cat
6e2f3364cf Merge pull request #9070 from lrytz/merge-2.11-to-2.12-jun-19

➜  scala13 git:(merge-2.12-to-2.13-jun-19) export MB=$(git merge-base HEAD upstream/2.12.x)

➜  scala13 git:(merge-2.12-to-2.13-jun-19) git log --graph --oneline $MB..upstream/2.12.x | cat
*   6e2f3364cf Merge pull request #9070 from lrytz/merge-2.11-to-2.12-jun-19
|\
| * a94e120232 Merge commit '2e2f65a201' into merge-2.11-to-2.12-jun-19
|/|
| * 2e2f65a201 Merge pull request #8595 from nevillelyh/neville/constant-pool
| * 79426c9c61 Add JDK 9 constant types to the ClassfileParser
*   d11aaa292f Merge pull request #8816 from retronym/topic/scala-integrate-async-review2
|\
| * 89f48d23a8 Refactor detection of ill nested await calls
| * ae91a3ca23 Address review comments (remove dead/debug code, +comments)
| * 0e27334b09 remove old ThicketTransformer
| * 230684dd5e Avoid generating dead code for terminal state
| * 7f22119a95 Rework async expression wrapping
| * c94951ea8b Fix an edge case for while in expr position
| * b76a0ec4a1 Fix an edge case for value classes
| * 923e57b7bb Add missing source file headers
| * db3ea69f74 Avoid exotic use of Labels to gain Scala.js compat
| * 5455445ce4 Tweak names in generated code
| * 215f173444 Move some async test cases to partest
| * f9d7952d60 Add a Scala.js compatible smoke test.
| * e63a133c65 Move async run tests to jvm category
| * 502c127bb0 Fixup remove stray .log files from partest suite
| * d81ef53361 Add an another example of a Writer/Option monad
| * bcb5dc65f2 Overhaul/fix live variables
| * e73f5020c3 Position synthetic trees accurately
| * 499296c8f9 Better integration with compiler fresh names
| * a5298c514d Support state getter/setter methods
| * 4d0f6bb37a Improve error reporting in asynj junit test.
| * 8c770f2b25 await in by-name function arg is repoted as ill-nested.
| * d1d3daab06 Avoid VerifyErrors wrapping Try in Assign.
| * 0775a0dbd6 erasure: push casts into LabelDefs to simplify async phase
| * b68e118b10 More granular fresh names.
| * 3a2882f6c5 Fix regression with non-awaiting patterns in tail position
| * 074b480a27 Add tests from scala/scala-async#206
| * 469cfc151a Add tests from scala/scala-async#210
| * 7d46e6b4ce Move ThicketTransformer to s.t.n.transform
| * de4fc23c08 Fix detection of ill-nested awaits
| * dd463d11a9 Test and simplify ANF transform of Nothing-typed if/match
| * 36d452ec71 Allow compilation of async's partest suite in Junit
| * d7a27646fd Local TypeDef no longer make it to the async phase.
| * 36ad222443 Remove dead code or make things more private.
| * 791c01539c Don't insert null assignments for the terminal state.
| * 11733cbe1d Overhaul integration with front end macros
| * 2631d47515 Be explicit about lambdaLift following the async phase.
| * c5bc867161 StateSet: Allocate caseSet lazily
| * 33ca19f144 Inline case class Awaitable
| * c89c21b5a9 More typed sub-trees avoiding working in `typed(...)`
| * 01a83cbb68 Limit UseFields transform to relevent subtrees.
| * aabe72383e Avoid overload resolution in typing default case of state handler.
| * 4124c2530b More efficient Contains-/No-Await cleanup
| * 1285669734 Comment out debugging toString.
| * a3aaeda558 Avoid logging string allocation
| * 02bbc1d11c Avoid allocating containsAwaitTraverser so often.
| * 0cea808904 Remove dead code.
| * 22014fcb1e Refactor addFutureSystemAttachment
| * 93748bd19a Refactor asyncTransform
| * 6f1546ce0f Use of AnfTransformer directly.
| * ef04e596bd Move AsyncTransform code into AsyncPhase.scala
| * 5755c7468f Remove dead cases from adaptToUnit
| * 60db8f9e2b Remove unused imports.
| * ad00a919ba Refactor field nulling.
| * dd0001b383 Refactor lifting to to change owner sooner
| * f512e2f396 Split some async implementation classes into files
| * bcf25d77fe Add a fast path to the async phase
| * 4753b3992f Merge AsyncTransformState with SymLookup
| * 2f75120373 Allow a nested TypingTransformer to use an existing local typer.
| * b86f2683dd Remove unused imports
| * 789811a016 Remove legacy future system methods.
| * ffc613b101 Remove PhasedTransform
| * c62fb75d82 Deal in typed trees in ExprBuilder.
| * 32e15bbe41 Use compiler APIs.
| * 1db7f9da37 Reinstate live variables test and fix null assignment
| * 7fdeed382c Use faster attachment lookups in ThicketTransformer
| * b61757586d Reduce number of states in async state machine
| * 528ffd2caa Avoid overhead in tree attachments
| * 588cab4cc1 Refactor and document UseFields transform
| * e276921141 Integrate async's logging into debuglog
| * 2d20aebb19 Harden Context.make debug logging against null trees.
| * 90568be3ae Cleanup AsyncPhase's transformer
| * 210bfacd94 Use reporter.error directly
| * c7cb301bb2 Fix .dot output when code contains ampersand
| * ee66301279 Sort cases by state ID
| * d0ac056f49 Fix broken attempt to elide nulling in final state
| * b1c43ce79b Reduce allocations in name freshening.
| * ec8166354f A simpler and faster ANF transform
| * 2b580edb39 Look for references in types as well as in terms.
| * 0619d4e876 Companion Detection should be post-erasure aware
| * e82ed14081 Live variables: detect usages in Awaitable.expr
| * 9666175e0d Deal with await in ArrayValue
| * 8de6b1bca3 We'll never see `isAsync` again in nested trees.
| * 50150ca8b0 Fix nested async transforms
| * 5a9517bd66 Convert tests to ScalaConcurrent Future System
| * b61e65b5f5 Delete dead code.
| * 3b38d951f7 Fix bug in StateSet and add a remove operation
| * 08fa083405 Add tests from scala-async
| * 5dd94954e0 Add JUnit support to partest
| * 008137d9f5 Move to scala.async.Async for compatibility with existing macros
| * a7bbec5ef6 Improvements to async phase
| * 6a665e97f9 Implement async transform with a macro and a post-erasure phase
| * 9535c942b9 patch for async debugging
| * 3d09049061 Import async
| * 9a0cbe8c6d make xprompt work in sbt's scalac task
* |   a072205367 Merge pull request #9065 from lrytz/bigDce
|\ \
| * | b9c828e8f5 Run DCE also on large methods
|/ /
* |   d84b7de184 Merge pull request #9052 from lrytz/html-escape-intelilj
|\ \
| |/
|/|
| * aec7942d7b [backport] decode html escapes in intellij dependency paths
|/
*   c0b47e62f0 Merge pull request #8983 from mkeskells/2.12.x_Map_Iterator
|\
| * ca329b2c34 allocaton hotspot in small Map iterators
*   58ce104566 Merge pull request #9006 from som-snytt/backport/12003
|\
| * 84360b57e3 [backport] Constructors handles private[this] var
*   61cf896c51 Merge pull request #8995 from retronym/topic/pure-expression-defer
|\
| * 58407eae2f Defer "pure expression .. in statement position" warnings until refchecks.
| * 85652a31fa Be more efficient in RefChecks
*   798705facb Merge pull request #8997 from retronym/topic/defensive-maxlocals
|\
| * e1a2d7dff7 [backport] targeted fix for potential missing max' computations
|/
* 1c3825bc0d Merge pull request #8999 from retronym/topic/red-black-tree-equals
* 8e95feae45 [nomerge] Revert backported RBTree changes that are 2.13.x only
```

```
➜  scala13 git:(merge-2.12-to-2.13-jun-19) git merge 798705facb -s ours

➜  scala13 git:(merge-2.12-to-2.13-jun-19) git merge 61cf896c51

➜  scala13 git:(merge-2.12-to-2.13-jun-19) ✗ git merge 58ce104566 -s ours

➜  scala13 git:(merge-2.12-to-2.13-jun-19) ✗ git merge c0b47e62f0

➜  scala13 git:(merge-2.12-to-2.13-jun-19) git merge d84b7de184 -s ours

➜  scala13 git:(merge-2.12-to-2.13-jun-19) git merge a072205367

➜  scala13 git:(merge-2.12-to-2.13-jun-19) ✗ git merge 6e2f3364cf
```

### CODE REVIEW

**Comment by lrytz** [comment]
Fixed the deadlock, this is ready for review @retronym

**Review by retronym — APPROVED** [review]
Thanks.

**Comment by SethTisue** [comment]
had to resolve a little merge conflict — let's hit "merge" as soon as CI likes it again

**Comment by SethTisue** [comment]
Scabot isn't triggering a Jenkins run because of the usual problem with PRs with a large number of commits

manually triggered run: https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/12278

UPDATE: yay, 🟢

**Pull request merged**
