### PR TITLE
Collection documentation fixes

### PR DESCRIPTION
**Pull request by vsalvis**
Some doc fixes for GenTraversableOnce, methods from aggregate to foreach in alphabetical order. I'm leaving EPFL, so somebody else will have to do the rest of the alphabet ;)

Types of corrections:
- rewordings, (hopefully) better explanations
- fixing type params and parameter names so doc gets inherited properly
- adjusting REPL output to what I get with 2.11
- moving documentation up to GenTraversableOnce (e.g. copyToArray was defined in GTO, but had no documentation there, only in TraversableLike)
- squashed some whitespace along the lines

### CODE REVIEW

**Comment by vsalvis** [comment]
Not sure if the script is general/useful enough to be committed as well? Will look in the failure tomorrow morning.

**Comment by vsalvis** [comment]
I'm at a loss... This is the test that's failing: https://github.com/scala-ide/scala-ide/blob/master/org.scala-ide.sdt.debug.expression.tests/src/org/scalaide/debug/internal/expression/features/NewKeywordTest.scala#L55 How can changes to documentation and type parameter names break this test?

**Comment by kiritsuku** [comment]
Maybe the IDE failure is just a flaky test.

But you are not allowed to just change the parameter names of a function, since they could be called from within user code. At least, you have to annotate them with `@deprecateName('previousName)`

**Comment by lrytz** [comment]
the changes are good, but we need to revert the parameter name changes. also, i'm not sure about merging this because it fixes only a part of the collection doc (methods a-f) and nobody seems seems to be doing the rest.. @SethTisue what do you think?

**Comment by SethTisue** [comment]
I keep hoping someone will magically appear and volunteer to finish it. @janekdb, maybe this one would interest you...?

**Comment by janekdb** [comment]
@SethTisue - Thanks for flagging this one up. I'll spend sometime to see how I can best contribute!

**Comment by janekdb** [comment]
- [x] Clone PR locally
- [x] Create initial as-is PR based on #4651 - See #4760

I've created a PR I own to allow me to push, following the guidelines here: https://help.github.com/articles/checking-out-pull-requests-locally/

Kindly let me know if there was a better way of approaching this.

**Comment by SethTisue** [comment]
> Kindly let me know if there was a better way of approaching this

This is fine. (An alternative would have been to ask @vsalvis for push access to their fork.)

**Pull request closed without merging**
