### PR TITLE
SI-6575 Plug inference leak of AbstractPartialFunction

### PR DESCRIPTION
**Pull request by retronym**
Usually this isn't needed, as partial functions can only be
defined with an expected type. But if that expected type is
and inherited method return type, the actual type of the partial
function literal is used, and the implementation detail of
`AbstractPartialFunction[A, B] with Serializable` leaks out.

After this change, the inferred types match those from
Scala 2.9.2.

```
ticket/6575 ~/code/scala scalac29 -Xprint:typer test/files/pos/t6575a.scala | grep def > 29.txt
ticket/6575 ~/code/scala squalac -Xprint:typer test/files/pos/t6575a.scala | grep def > 210.txt
ticket/6575 ~/code/scala diff -u 29.txt 210.txt
--- 29.txt  2012-10-28 13:51:07.000000000 +0100
+++ 210.txt 2012-10-28 13:51:20.000000000 +0100
@@ -1,7 +1,16 @@
     def foo: PartialFunction[Int,Int]
     def /*Y*/$init$(): Unit = {
-    absoverride def foo: PartialFunction[Int,Int] = ((x0$1: Int) => x0$1 match {
+    absoverride def foo: PartialFunction[Int,Int] = {
+        def <init>(): anonymous class $anonfun = {
+        final override def applyOrElse[A1 >: Nothing <: Int, B1 >: Int <: Any](x$1: A1, default: A1 => B1): B1 = (x$1: A1 @unchecked) match {
+        final def isDefinedAt(x$1: Int): Boolean = (x$1: Int @unchecked) match {
     def /*Z*/$init$(): Unit = {
-    absoverride def foo: PartialFunction[Int,Int] = ((x0$2: Int) => x0$2 match {
+    absoverride def foo: PartialFunction[Int,Int] = {
+        def <init>(): anonymous class $anonfun = {
+        final override def applyOrElse[A1 >: Nothing <: Int, B1 >: Int <: Any](x$1: A1, default: A1 => B1): B1 = (x$1: A1 @unchecked) match {
+        final def isDefinedAt(x$1: Int): Boolean = (x$1: Int @unchecked) match {
     def /*Comb*/$init$(): Unit = {
-    absoverride def foo: PartialFunction[Int,Int] = ((x0$3: Int) => x0$3 match {
+    absoverride def foo: PartialFunction[Int,Int] = {
+        def <init>(): anonymous class $anonfun = {
+        final override def applyOrElse[A1 >: Nothing <: Int, B1 >: Int <: Any](x$1: A1, default: A1 => B1): B1 = (x$1: A1 @unchecked) match {
+        final def isDefinedAt(x$1: Int): Boolean = (x$1: Int @unchecked) match {
```

review by @adriaanm
- submitting to 2.10.0-wip under the regression-discovered-in-RC1 banner.
- what's preferred, `tree.setType(tp)` or `Typed(tree, tp)`?

### CODE REVIEW

**Comment by paulp** [comment]
In principle, trees should be constructed such that you could null all the types after any phase and retype the trees and get the same types back.  At least, that's what I hear.  Presumably Typed(tree, tpt) might actually live up to that ambition, and "tree setType tpe" would not.  Supposedly this is what -Ycheck does; you will not be surprised to find that -Ycheck:all has not often been found in the "working flawlessly" circle.  Once long ago I got it there, but without it being part of the build, forget it.

It's always interesting to see how it fails though.  Random example:

```
% scalac3 -J-Xmx1g -Ycheck:all -d /tmp ./src/compiler/scala/tools/nsc/typechecker/*.scala
[Not checkable: parser]
[Not checkable: namer]
[Not checkable: packageobjects]
[Now checking: typer]

./src/compiler/scala/tools/nsc/typechecker/Checkable.scala:289: error: redefinition of hashCode method. See SIP-15, criterion 4. is not allowed in value class
private[typechecker] final class Checkability(val value: Int) extends AnyVal { }
                                 ^
./src/compiler/scala/tools/nsc/typechecker/PatternMatching.scala:1383: error: 
**** ERROR DURING INTERNAL CHECKING ****
type mismatch;
 found   : Class[(some other)?0(in method traverse)] where type (some other)?0(in method traverse) <: PatternMatching.this.global.Tree
 required: Class[?0(in method traverse)] where type ?0(in method traverse) <: PatternMatching.this.global.Tree
          patmatDebug("untouched "+ (t, t.getClass, t.symbol.ownerChain, currentOwner.ownerChain))
                                          ^
./src/compiler/scala/tools/nsc/typechecker/Typers.scala:2792: error: 
**** ERROR DURING INTERNAL CHECKING ****
type mismatch;
 found   : Class[(some other)?0(in method checkNoDoubleDefs)] where type (some other)?0(in method checkNoDoubleDefs) <: Typers.this.global.Symbol
 required: Class[?0(in method checkNoDoubleDefs)] where type ?0(in method checkNoDoubleDefs) <: Typers.this.global.Symbol
                    ((e1.sym.getClass, e1.sym.info, e1.sym.ownerChain)))
                             ^
three errors found
```

**Comment by retronym** [comment]
@paulp Next question: `typedPos(pos)(Typed(tree, TypeTree(newType))` or `atPos(pos)(Typed(tree, TypeTree(newType)) setType newType)`? I went with the former, but notice a mix in existing code.

**Comment by paulp** [comment]
The former must be the "right" way, but the latter will be cheaper.  One hopes a call to typed is not too expensive when it's a Typed(x, tpt) node where tpt carries an actual type already, but it's probably a habit in some circles to avoid calls to typed when possible.

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
