### PR TITLE
Improve namePos for type aliases and valdefs

### PR DESCRIPTION
**Pull request by lrytz**
Use namePos for symbol of derived trees like accessors

### CODE REVIEW

**Comment by SethTisue** [comment]
What's the context for this...?

**Comment by lrytz** [comment]
It's an internal improvement that was split out of https://github.com/scala/scala/pull/10520 / https://github.com/scala/scala/pull/10512

**Comment by som-snytt** [comment]
By internal improvement, we mean metals wanted the positions of named elements to be the name, such as a class would be its name and not the whole definition.

It's also funny that we can add API to `reflect.api` and nobody complains (such as mima).

The code looks vaguely familiar so I will probably lgtm.

**Review by som-snytt — APPROVED** [review]
This looks familiar.

**Pull request merged**
