### PR TITLE
Weed out remnants of early type defs

### PR DESCRIPTION
**Pull request by densh**
This commit removes the dead code that was originally intended for
implementation of early type definitions.

[Discussion on the scala-internals](https://groups.google.com/d/msg/scala-internals/k4DzIge9MJU/XecXvqkQDdYJ).

Review @adriaanm

### CODE REVIEW

**Comment by densh** [comment]
This might as well be a "fix" for [SI-3572](https://issues.scala-lang.org/browse/SI-3572).

**Comment by soc** [comment]
LGTM, but I think it would be nice to have some numbers whether anyone managed to use this in the wild as soon as dbuild is ready.

**Comment by adriaanm** [comment]
Wow, that was fast :-) In thinking about it, we should probably deprecate first. I don't know whose law this is, but if it parses, people are using it, and we shouldn't break source compatibility without deprecation.

**Comment by densh** [comment]
On the other hand migration path is trivial, all those who have used it just need to move typedef to the body of the class/trait (that's what was happening in mkTemplate). Unfortunate side-effect of keeping it is that quasiquotes have to support this special case if it's still around (undoing mkTemplate transformations is quite involved even without it). 

Maybe we can remove it but show a nice error message with migration recommendation?

**Comment by adriaanm** [comment]
Our source compatibility policy says we try our hardest to ensure anything compiling under 2.10 without deprecation warnings will compile as-is in 2.11. (We make exceptions for bugs, of course. Here, people could reasonably expect this worked, even though it didn't really.)

**Comment by adriaanm** [comment]
So, the only thing we can do is to deprecate in 2.11. Sorry about not making this clearer from the start. Please reopen when that's implemented. Would also be good to discuss during the next scala meeting.

**Pull request closed without merging**
