### PR TITLE
remove commented code

### PR DESCRIPTION
**Pull request by serkanerip**
Removed commented checkTable method in mutable.Hashset. Its commented long time ago.

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
@szeiger looks like you might have been keeping this around for occasional uncommenting during development, to help catch bugs — is this something we actually might want to keep, with an appropriate explanatory comment?

**Comment by SethTisue** [comment]
I suggest we keep the code and add a comment like:

```
// Verifies that expected invariants hold. During debugging, it may be useful to
// uncomment this method and insert calls to it in suspected-to-be-flawed code.
```

Even apart from debugging, the code may also have some value just as documentation of what invariants are _expected_ to hold.

**Comment by diesalbla** [comment]
> Even apart from debugging, the code may also have some value just as documentation of what invariants are expected to hold.

Perhaps we should write in text these invariants, at the top of the class: 

> The HashSet class holds the following internal invariants:
> - For each `i`, the bucket at `table(i)` only contains element whose index is `i`.
> - Every bucket is sorted in ascendent order by hash.  
> - The sum of the lengths of all buckets is equal to `contentSize`.

Coincidentally, are these the same invariants as the `HashMap`?

**Comment by diesalbla** [comment]
Opened https://github.com/scala/scala/pull/9010 to do the above.

**Comment by SethTisue** [comment]
@serkanerip interested in revising this based on the feedback? note that #9010 is merged now

**Review by diesalbla — APPROVED** [review]

**Comment by SethTisue** [comment]
@serkanerip ping! interested in revising this based on the feedback? note that #9010 is merged now

**Comment by som-snytt** [comment]
We might need a "not hacktober" label.

**Pull request closed without merging**
