### PR TITLE
[nomaster] corrects an error in reify’s documentation

### PR DESCRIPTION
**Pull request by xeno-by**
review @retronym

### CODE REVIEW

**Comment by retronym** [comment]
LGTM

**Comment by xeno-by** [comment]
@adriaanm Kitten is stuck. What do we do?

**Comment by adriaanm** [comment]
I restarted it. Not sure what's going on. The logs look normal.

**Comment by adriaanm** [comment]
Aha! There was no milestone mapping for the 2.10.x branch (the bot parses the milestone descriptions to figure out which target-branches take part in PR validation, and to set the milestone label). If there's no milestone with a description that starts with "Merge to B" for the target branch of your PR (e.g., gh-pages), it won't be built.

**Comment by adriaanm** [comment]
(This should probably be made less strict, as we don't get that many gh-pages PRs.)

**Pull request merged**
