### PR TITLE
Revert "SI-10133 Require escaped single quote char lit"

### PR DESCRIPTION
**Pull request by adriaanm**
Reverts scala/scala#5629

It broke projects in the community build (https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1276/consoleFull)

Lets bring the changes back, but under -Xsource:2.13

### CODE REVIEW

**Comment by som-snytt** [comment]
OK, scala-refactoring, that's pretty funny. akka-http is kind of off the hook because they were conditioned by writing `'''Caveat'''` in their docs.

**Comment by adriaanm** [comment]
Ok, I'll close this one in favor of your more surgical revert.

**Comment by adriaanm** [comment]
Ah I misunderstood. I'll merge this, and please resubmit the commit that had snuck in.

**Comment by som-snytt** [comment]
I just wound up resubmitting with the flag check, and see if I did it right. It doesn't seem to impact the other commits. I had intended on two PRs but I got lazy when I saw my chance. Sorry for the hassle. Later I'll verify with the dbuild, where I guess d stands for something so nasty they can show only one letter of it. I've run it once before. The dread build.

**Comment by adriaanm** [comment]
@SethTisue can help with running the community build to put a scala/scala PR through its paces. Speaking of community build, I was trying to get it green again on 2.11.x, and in my haste to get some jenkins capacity wrongfully stopped the CI builds for your PR

**Comment by som-snytt** [comment]
Yup, I just noticed. Jenkins was kind and told me so.

I'll use this as a learning experience, like don't mess with the syntax. Maybe I'll see if I can ask the community build only to parse the world.

I'll try to spare you further annoyance. How about if I backport this for 2.11.9? Just kidding.

**Comment by adriaanm** [comment]
😱

**Comment by SethTisue** [comment]
2.12 community build is green again

**Pull request merged**
