### PR TITLE
SI-6178 reflective invocation of magic symbols

### PR DESCRIPTION
**Pull request by xeno-by**
In Scala there are some methods that only exist in symbol tables,
but don't have corresponding method entries in Java class files.

To the best of my knowledge, these methods can be subdivided into four groups:
1) stuff weaved onto Any, AnyVal and AnyRef,
2) magic methods that Scala exposes to fix Java arrays,
3) compile-time methods (such as classOf and all kinds of macros),
4) miscellaneous stuff (currently only String_+).

To support these magic symbols, I've modified the `checkMemberOf` validator
to special case Any/AnyVal/AnyRef methods and adjusted MethodMirror and
ConstructorMirror classes to use special invokers for those instead of
relying on Java reflection.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @paulp, @odersky or @gkossakowski

**Comment by paulp** [comment]
My review is: https://github.com/paulp/scala/tree/scalamacros/ticket/6178

I'd have just added it to the pull request if I could figure out how.  Since I can't, can you add it?

It's a lot easier to avoid duplication as you go than it is to clean it up later (and a lot more likely to be done by someone other than me.) And bugs often turn obvious once all the noise is stripped away, as happened here.

**Comment by xeno-by** [comment]
Thanks! I'll add this commit to the ultimate pull request that will unify all the stuff currently in flight.

**Comment by xeno-by** [comment]
Will be resubmitted jointly with https://github.com/scala/scala/pull/1048, https://github.com/scala/scala/pull/1052, https://github.com/scala/scala/pull/1054 and https://github.com/scala/scala/pull/1057.

**Comment by xeno-by** [comment]
Superceded by https://github.com/scala/scala/pull/1067

**Pull request closed without merging**
