### PR TITLE
sbt 1.4.9 (was 1.4.7)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
looks like our jenkins needs an updated sbt launch script:

```
cat: /home/jenkins/.sbt/launchers/1.4.8/sbt-launch.jar.md5: No such file or directory
md5sum: 'standard input': no properly formatted MD5 checksum lines found
Checksum does not match
Could not download and verify the launcher. Obtain the jar manually and place it at /home/jenkins/.sbt/launchers/1.4.8/sbt-launch.jar
```

**Comment by SethTisue** [comment]
on all 3 behemoths, I sshed in as `admin` and did:

```
curl -Ls https://git.io/sbt -o sbt
chmod 0755 sbt
sudo mv sbt /usr/local/bin/sbt
```

and let's see how https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/14286 does

**Comment by SethTisue** [comment]
at https://github.com/sbt/sbt/issues/6372#issuecomment-794197549 Eugene said 1.4.9 will be along soon, so we should probably wait for that, rather than merging now

**Comment by SethTisue** [comment]
rebased because of flaky t7020 — if it fails again, ping Dale on #9540

**Pull request merged**
