### PR TITLE
Cope with adapted member name in dynamic invoke

### LINKED ISSUE #7606: updateDynamic with implicit conversion from String for "name" param
Given a Dynamic class/trait, with updateDynamic(name: Something)(...), and an implicit conversion from String to Something, the typechecker will report "reassignment to val" when trying to update a field using the = syntax. It does work fine for selectDynamic and applyDynamic.

Minimized test case:

```scala
import scala.language.{ dynamics, implicitConversions }

class ID(s: String)

class DynamicFields extends scala.Dynamic {
  def updateDynamic(name: ID)(value: Any): Unit = ???
}

object BugUpdateDynamic {
  implicit def string2id(s: String): ID = new ID(s)

  def bug(): Unit = {
    val o = new DynamicFields
    o.foo = "bar"
  }
}
```

Compiling with 2.10.1, 2.10.2 or 2.11.0-M3 yields the same output.

Expected output: compile fine, without error.

Actual output:

```scala
$ ~/opt/scala-2.11.0-M3/bin/scalac BugUpdateDynamic.scala
BugUpdateDynamic.scala:14: error: reassignment to val
    o.foo = "bar"
          ^
one error found
```

(manually calling updateDynamic works, btw)

### LINKED ISSUE #9310: Typer stack-overflow when Dynamic with implicit conversions are used
When compiling the `so.scala` file, scalac stack-overflows in the typer:

```
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPos(Typers.scala:5454)
        at scala.tools.nsc.typechecker.Typers$Typer.insertApply$1(Typers.scala:949)
        at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1115)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1166)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5410)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPos(Typers.scala:5454)
        at scala.tools.nsc.typechecker.Typers$Typer.insertApply$1(Typers.scala:949)
        at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1115)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1166)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5410)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
...
```

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#7606
Fixes scala/bug#9310

### CODE REVIEW

**Comment by som-snytt** [comment]
This affects transparency:
```
-        val t = Select(qual setPos tree.pos.makeTransparent, nme.apply)
-        wrapErrors(t, _.typedPos(tree.pos, mode, pt)(t))
+        val t = atPos(tree.pos)(Select(qual setPos tree.pos.makeTransparent, nme.apply))
+        wrapErrors(t, _.typed(t, mode, pt))
```
https://github.com/scala/bug/issues/8125
https://github.com/scala/bug/issues/8130
https://github.com/scala/bug/issues/9699

**Review by lrytz — APPROVED** [review]
Thanks! Very dynamic :)

**Comment by lrytz** [comment]
> [scala/bug#8125](https://github.com/scala/bug/issues/8125)
> [scala/bug#8130](https://github.com/scala/bug/issues/8130)
> [scala/bug#9699](https://github.com/scala/bug/issues/9699)

Does this PR fix all of those?

**Comment by som-snytt** [comment]
@lrytz those are just related issues around positions and transparency. Although I've worked with positions for error messaging, fragility around transparency was new to me. I'll try to follow up.

**Comment by som-snytt** [comment]
> I'll try to follow up.

Famous last words.

**Pull request merged**
