### PR TITLE
Allow `case` in pattern bindings even without `-Xsource:3`

### PR DESCRIPTION
**Pull request by smarter**
In #9558 (which shipped with 2.13.6) we added support for `case` bindings under -Xsource:3. Since this parser change does not break any existing code and since IntelliJ and scalameta/metals now understand this syntax in Scala 2 code, it should be safe to enable it by default to further ease cross-compilation between Scala 2 and 3.

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
needs spec change, IMO

**Comment by smarter** [comment]
Fair point, I'll edit the spec.

**Comment by smarter** [comment]
Spec updated.

**Review by SethTisue — APPROVED** [review]

**Comment by smarter** [comment]
What do you think of backporting this to 2.12 ?

**Comment by lrytz** [comment]
Sure, I don't see any reason against.

**Pull request merged**
