### PR TITLE
Fix SI-7107: scala now thinks every exception is polymorphic

### PR DESCRIPTION
**Pull request by gkossakowski**
We need to force info of the `throwableSym` in `addThrowsAnnotation`
because we call `Symbol.isMonomorphicType` that relies on a symbol
being initialized to give right answers.

In the future we should just clean up implementation of
`isMonomorphicType` method to not rely on a symbol being initialized
as there's no inherent reason for that in most cases. In cases where
there's reason for that we should just force the initialization.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @paulp.

Resubmission of #2116 that I tried to sneak into 2.10.1 branch. It was a bad idea and I'm glad we have vigilant @JamesIry.

**Comment by paulp** [comment]
"In cases where there's reason for that we should just force the initialization." It isn't going to be that easy in the general case of isMonomorphicType; the same cases where there's a reason for it will be the ones which you can't force. And though it isn't in the 2.10.x series, let's not forget about this little guy.

```
    /** Can we tell by inspecting the symbol that it will never
     *  at any phase have type parameters?
     */
    def neverHasTypeParameters(sym: Symbol) = sym match {
      case _: RefinementClassSymbol => true
      case _: ModuleClassSymbol     => true
      case _: ImplClassSymbol       => true
      case _                        =>
        (
             sym.isPrimitiveValueClass
          || sym.isAnonymousClass
          || sym.initialize.isMonomorphicType
        )
    }
```

To call initialize blindly like that, there should be a test case which exercises it better, or at all. I would not commit it like this to the stable branch.

**Comment by gkossakowski** [comment]
@paulp: When it comes to forcing my vision (might be completely stupid) is to require every symbol to declare its arity at creation time. I cannot think of a case where symbol can change arity over time. If there's one I'd love to hear about it. Also, I don't see scenario where you create a type symbol and you don't know its arity. I admit that I'm complete noob at Scala's frontend and I might be missing something obvious. If yes, please tell me. Obviously, all of that is master material.

When it comes to test-case there's already one that I added #2021 that should fail but it doesn't because for whatever reason exception's type is forced somewhere else. I could add a test-case for the situation you reported in SI-7107 but I'm afraid it's going to be very flaky because I'd rely on not forcing some symbols for exceptions defined in Java's std library.
In general I'd agree that forcing blindly is not a great idea but here we force very specific set of symbols: those corresponding to thrown exceptions. Also, calls to that method come from ClassfileParser and Scala reflection. I could force initialization in ClassfileParser if that sounds better.

**Comment by paulp** [comment]
Here are at least a couple symbols where you will be hard pressed to specify their arity: Any, Nothing.

How many type parameters does tv take? Careful: if you say "1" you have a problem, because this compiles.

```
class Dingus[T]
class Bippy[CC[X] <: Seq[X]]() extends Dingus[CC[Int]]
def f(x: Dingus[_]) = x match { case m: Bippy[tv] => }
```

They aren't insurmountable difficulties, I'm just telling you it won't be as easy as ruling by fiat that all symbols must declare their arity.

**Comment by paulp** [comment]
ClassfileParser would definitely be preferred.

**Comment by JamesIry** [comment]
@gkossakowski, @paulp what's the status on this PR?

**Comment by paulp** [comment]
I don't think this code belongs in AnnotationInfos, and would like to see it closer to symbol creation.

**Comment by gkossakowski** [comment]
I agree with @paulp. I just have a long list of things I have to take care of. I'll rework this patch tomorrow.

**Comment by gkossakowski** [comment]
@paulp: moved the logic to ClassfileParser and updated a commit message to reflect the new location and explain lack of test.

**Comment by paulp** [comment]
We don't have to relish side effects _quite_ so much. There are two other spots you could put initialize which don't depend on side effect semantics. Lgtm otherwise.

**Comment by gkossakowski** [comment]
@paulp: I avoided that side effect to be blended with the rest of the logic so I can show my dissatisfaction with the fact I have to put it. It expresses the hope that we'll be able to get rid of it eventually.

I can plug it into one of those two lines if that will make your day.

**Comment by paulp** [comment]
My day cannot be made so easily. It's fine the way it is.

**Comment by gkossakowski** [comment]
Ok, thanks. Merging.

**Pull request merged**
