### PR TITLE
Updated copyright dates throughout compiler and stdlib for upcoming release

### PR DESCRIPTION
**Pull request by heathermiller**
For the release, I thought that it'd be nice to have copyrights that are up-to-date. Most copyrights were 2011- which will soon be two years outdated. It was driving me nuts.
- commit 807dbe5 updates all copyrights in comments, so these should be harmless
- commit a47c2a3 updates copyrights in Scaladoc's manpage template, and in the footer of all Scaladoc pages. This should also be harmless- but since these technically touch code, and not comments, I separated them out for clarity.

### CODE REVIEW

**Comment by heathermiller** [comment]
Review by @jsuereth

**Comment by jsuereth** [comment]
LGTM

**Comment by adriaanm** [comment]
wow! sorry I apparently missed that much in 4eb9b8ec44

**Comment by jsuereth** [comment]
is the kitteh down?

PLS REBUILD ALL

**Comment by heathermiller** [comment]
Wow- I didn't realize that you already replaced a bunch. Just did some good ole fashioned greppin' and findin' and replacin'.

About kitteh- kitteh was weird for my earlier pull. I got notification of kitteh starting 5 minutes before kitteh sent the "Success" notification. Checking the console output on that pull (#1558) though showed that everything properly built and all tests passed- it just seems like the github notification was slow to happen.

**Comment by heathermiller** [comment]
et voilà. Less than 30 seconds after I post, kitteh is satisfied...

**Comment by heathermiller** [comment]
Odd- only rangepos so far...

**Comment by heathermiller** [comment]
Ack, nevermind, somehow I mixed up build bots. Ok- so kitteh is fine.

**Pull request merged**
