### PR TITLE
Fix documentation on the Future.reduce() method

### PR DESCRIPTION
**Pull request by wajda**
According to the issue #11308 - https://github.com/scala/bug/issues/11308

### CODE REVIEW

**Comment by wajda** [comment]
I have signed the CLA.

**Comment by viktorklang** [comment]
Thanks @wajda!

**Comment by viktorklang** [comment]
@lrytz What's the branch target strategy, should we target 2.13.x only and backport, or forwardport?

**Comment by lrytz** [comment]
2.12 is fine for improvements. it'll land in 2.13 as well, we merge forward.

**Pull request merged**
