### PR TITLE
typecheck(q"class C") no longer crashes

### PR DESCRIPTION
**Pull request by xeno-by**
MemberDefs alone can't be typechecked as is, because namer only names
contents of PackageDefs, Templates and Blocks. And, if not named, a tree
can't be typed.

This commit solves this problem by wrapping typecheckees in a trivial block
and then unwrapping the result when it returns back from the typechecker.

### CODE REVIEW

**Comment by densh** [comment]
Why not `build.SyntacticBlock`? It would take care of synthetic unit too.

**Comment by xeno-by** [comment]
Well, it looks like SyntacticBlock does a lot of other stuff, whereas this wrapping/unwrapping is really simple. How would the code look?

**Comment by densh** [comment]
``` scala
val build.SyntacticBlock(output) = typecheck(build.SyntacticBlock(input))
```

But I guess in this case benefit is minimal.

**Comment by xeno-by** [comment]
It actually looks nicer this way, so I updated the code.

**Comment by gkossakowski** [comment]
I thought we accept PRs that fix blocker bugs only at this point.

**Comment by xeno-by** [comment]
This is a really minor change that fixes an important misunderstanding that was (for yet another time) brought up today at SO, so I decided to give it a try. The risks are minimal, but you guys feel free to decide the target.

**Comment by retronym** [comment]
LGTM. It's isolated to toolboxes, so I think its okay to merge this.

**Pull request merged**
