### PR TITLE
SI-8437 macro runtime now also picks inherited macro implementations

### PR DESCRIPTION
**Pull request by xeno-by**
Previously it didn't matter much that we used Class.getDeclaredMethods
instead of just getMethods, but with the introduction of macro bundles
it can make a difference which is fixed in this commit.

I'd also like to note that the fact that getMethods only returns public
methods and getDeclaredMethods also sees private methods, doesn't make
a difference, because macro implementations must be public.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym 

This is a tiny change, so it might be worth considering for 2.11.0.

**Comment by retronym** [comment]
Needs a test, otherwise I'm okay with this for RC4

**Comment by xeno-by** [comment]
This is super weird. I must've forgotten to actually git add those tests to the PR :O

**Comment by xeno-by** [comment]
Fixed. What an embarassment!

**Comment by retronym** [comment]
LGTM

**Pull request merged**
