### PR TITLE
`par` with tasksupport implicit - now with a default implicit

### PR DESCRIPTION
**Pull request by axel22**
Exactly the same as in https://github.com/scala/scala/pull/930, only this time with a default implicit tasksupport parameter.

Review by @jsuereth.

### CODE REVIEW

**Comment by soc** [comment]
Won't we break code which used an `apply` right after `par`:

`Array(1,2,3).par(1) == 2` in 2.9.

With this change it will stop working in 2.10, right?

**Comment by axel22** [comment]
This is meant to go into 2.11.

**Comment by paulp** [comment]
But we'll have the same problem in 2.11, right? It only helps for them to be going into 2.11 if "using an apply after par" is deprecated in 2.10.0.  I don't think that's even possible.

**Comment by axel22** [comment]
No, I don't see how we could easily emit a deprecation warning for such a call pattern. The only alternative I see is introducing a new method name for the new version of `par`.

**Comment by soc** [comment]
As mentioned in https://github.com/scala/scala/pull/930, I think `parWith` would be good choice.

**Pull request closed without merging**
