### PR TITLE
Harden against synthetics being added more than once.

### PR DESCRIPTION
**Pull request by paulp**
Don't add synthetic methods if they already contain synthetic
methods from the set we're about to add.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @dotta .

**Comment by dotta** [comment]
LOL. If it's up to me, you'll have no problem getting this merged. 

From where I stand (i.e., very limited compiler's internal know-how), your fix looks good to me.

**Comment by jsuereth** [comment]
With no tests and no pressing bug, I'm not really certain why this is targetted against the RC branch.

**Comment by dotta** [comment]
Josh, this PR is a consequence of http://groups.google.com/group/scala-internals/browse_thread/thread/a102f31d3eae86f3. Unfortunately, it is hard to create a test.

**Comment by jsuereth** [comment]
Ok, Talked with @dotta .   Review by @adriaanm

**Comment by adriaanm** [comment]
I know this is an annoying problem and it's great we have a fix, but we're in paranoid RC mode here.

Only stuff that's either too important not to get in now (due to the now-or-never nature of binary incompatible fixes) so that we can risk the regression or that's a real blocker (something hit by a lot of people that cannot be worked around).

Please resubmit for 2.10.x.

**Comment by dotta** [comment]
It was worth trying ;-) Thanks Paul for the patch, let's make sure this goes into 2.10.x (Paul, if your attention is needed on something else, I can open the PR on your behalf)

**Comment by paulp** [comment]
I opened it yesterday, #1525.

**Comment by adriaanm** [comment]
How do we know the crashes are because of this bug? Or that they will be resolved by this fix?

Should we break our RC policy for something that may reduce the frequency of something by an unknown amount?

When we went into RC mode we all agreed we were basically ready to ship, except for some potentially extremely serious bugs that we didn't know of at the time (we knew the presentation compiler was unstable before going into RC mode AFAIK), and that could only be discovered by unleashing an RC on our users so that they can test it for us.

Should we have staid in Milestone mode longer?

**Comment by paulp** [comment]
"When we went into RC mode we all agreed we were basically ready to ship" Only for the record, you pretty much never have my agreement on this sort of thing.  I realize that renders my opinion irrelevant, I just don't want to be called out like I'm some kind of flipflopper.  I never think we're basically ready to ship.

As to this patch and the general question, I think having a rigid policy is probably effective at making people feel good about fair and equal treatment and ineffective at producing the best software.  I leave it to others how to prioritize those things, but I can't help but trust my own assessment more than I trust our Policy Overlords.

**Comment by adriaanm** [comment]
Yes. There's a lot of uncertainty everywhere. That's why comment was all questions.
The policy is meant to reduce the impact of uncertainty. I agree delivering the best possible software should be our highest priority, but it's not clear to me which decision leads us there with the highest probability.

**Comment by ijuma** [comment]
"How do we know the crashes are because of this bug? Or that they will be resolved by this fix?"

If the presentation compiler crashes happen as often as stated, isn't it just a matter of using this branch for a few days to see if it helps? It certainly is not as good as an isolated test case, but sometimes that is what it takes to produce software that is good for users.

**Comment by adriaanm** [comment]
Yes. I think that would be part of the due diligence for an RC-time bug fix.

If this pull request clearly improves the IDE experience for 2.10.0, I think we should consider merging it.

For the record, here's a list of what we need to fix by RC2: https://issues.scala-lang.org/secure/IssueNavigator.jspa?requestId=11901 -- every time we add something here, P(timelyRelease) decreases. P(goodRelease) may go up, though.

**Comment by adriaanm** [comment]
Copy/pasting my opinion on this from #1527 (deferring to Josh for the ultimate decision, as he's the release manager for 2.10.0). We are allowing some fixes in so that we can ship the best 2.10.0 we can within the timeframe we have, but only if someone can make a _convincing_ case this actually _fixes_ a _serious_ regression. The deadline for doing all this and having your fix merged is Wed Oct 31.

I agree this fix is not going to kill the release, but let's try to look at the bigger picture.
This is not the only change that someone wants to have merged.
All of them together amount to death by a million paper cuts.

We're in RC mode and that means everybody was comfortable with master being released. Maybe we weren't ready, but that ship has sailed, and it's good to keep in mind for next time when we make that switch. It's a serious decision.

Now we must focus on getting 2.10.0 out of the door in a reasonable amount of time and shift our focus to 2.10.1.

Every little non-blocking fix (and sorry, this is not a blocker) pushes the release date a little but further down the road.

First mentions of going into RC mode date back to April. Half a million "just one more feature/bugfix/hotfix/tweak/paper cut" later, it's almost november and we're at RC2. No more.

**Comment by jsuereth** [comment]
So, here we go: 

Martin,

As discussed w/ Adriaan and Martin, this will have to be targeted for 2.10.1, which already has RC1 dates.

For further notice:

The policy during an RC process is any blocker fixes. "Blocker" during RC refers to anything that has absolutely no workaround. Pull requests must include tests and be well written.

This PR is fine to target 2.10.1, but not 2.10.0 at this point. It's a few months behind the 8 ball. Doors have closed, but 2.10.x is open and inviting. They even have free cookies over there.

**Comment by dragos** [comment]
I think this should be considered a blocker, since it is a regression with no known workaround.

**Comment by odersky** [comment]
I think we should not be too formalistic here. We should be able to accept patches for spurious errors even if we do not have a test case for these. 

Paul and I looked at this. We both say the fix is a) harmless and b) will in all likelihood fix the errors.

What I propose is that Iulian will build the IDE against the patched version and try it for a day or two. If none of the spurious errors appears, we give it a go. OK?

Thanks - Martin

**Comment by ijuma** [comment]
+1 to @odersky's suggestion. I don't see what we will gain from releasing 2.10.0 that will result in bad publicity due to bugs that have a user-visible impact and have a relatively safe fix. It will simply encourage people to wait until .1 before they try new Scala releases.

**Comment by dragos** [comment]
Both me and Mirco have been using the patched build since Friday, without seeing this spurious error in the mean time. I suggest we keep doing that and report back on Wednesday 31.

I spent a few hours yesterday trying to write a test that reproduces this bug, but I didn't succeed.

**Comment by jsuereth** [comment]
@dragos @ijuma @odersky @paulp Please read: https://github.com/scala/scala/pull/1525#issuecomment-9868907 from other pull request.  Assuming your manual testing succeeds, we can take this patch as-is, albeit I'm not going to close the ticket, because I still believe we have some other poor behavior waiting to explode and with no test, there's no way for us to know what that underlying issue is.

**Comment by adriaanm** [comment]
For the record, I do not think we are being "formalistic". I would like to see one example of a successful engineering company that does not have a policy and a process similar to ours (I'd hope theirs is better, as we're just getting started here). Without process, I don't see how we can scale this project in a way appropriate for a company.

**Comment by lrytz** [comment]
A policy that we currently don't have is one that defines what kind of known issues we accept to go into a release, and which ones are too critical to be left unfixed.

**Comment by adriaanm** [comment]
I believe we are not willing to ship with regressions without a workaround. Everything else can be a "known issue".

**Pull request closed without merging**
