### PR TITLE
SI-7624 Fix -feature and some -Xlint warnings

### PR DESCRIPTION
**Pull request by soc**
Changes build.xml to build Scala with `-feature` enabled.

### CODE REVIEW

**Comment by soc** [comment]
New version of https://github.com/scala/scala/pull/2705.

Review by @adriaanm, please.

**Comment by gkossakowski** [comment]
I'll have a look into this tomorrow.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by gkossakowski** [comment]
@soc: excellent work. Please address my two comments.

**Comment by soc** [comment]
@gkossakowski @adriaanm I split the commit as mentioned (see 2nd and 3rd one). I also added a new one (6th) which fixes feature warnings is scala/tools/scalap, I must have missed that package the first time.

**Comment by soc** [comment]
7th is new, too, but has no semantic changes.

**Comment by adriaanm** [comment]
@soc, accidentally deleted your comment, sorry! We'll take care of rebasing this PR since it took us so long to get it merged

**Pull request closed without merging**
