### PR TITLE
showRaw can now print positions

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
Resubmission of #1762 against master.

**Comment by xeno-by** [comment]
review @paulp @retronym

**Comment by retronym** [comment]
Code change lgtm, but it might as well come with a test case.

**Comment by xeno-by** [comment]
After having a position test failing on windows (presumably because of line ending differences) I now prefer not to print positions in check files.

**Comment by paulp** [comment]
Looks good enough to me.

**Pull request merged**
