### PR TITLE
Java 8 agnostism for our test suite

### PR DESCRIPTION
**Pull request by retronym**
Continuing on from @gkossakowski's work in #3404.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @lrytz

**Comment by retronym** [comment]
Tested locally with Java 8. I can't figure out a clean way to parameterize `scala-checkin-manual` on the JDK.

But I will be able to add Java 8 to `scala-nightly-auxjvm-2.1{1,2}.x` after we merge this.

**Comment by retronym** [comment]
Testing on Jenkins: https://scala-webapps.epfl.ch/jenkins/job/test-scala-nightly-auxjvm/jdk=jdk8,label=auxjvm/9/console

**Comment by som-snytt** [comment]
I'll take a look at the javap failure later today (PST).

**Comment by retronym** [comment]
@som-snytt Much appreciated. I've pushed a new commit that disables the test for now, so we can bring this back in the fullness of time.

**Comment by adriaanm** [comment]
This needs a rebase.

**Comment by retronym** [comment]
I've dropped the conflicting, final commit. It is no longer necessary after #3818

**Comment by adriaanm** [comment]
LGTM

**Comment by retronym** [comment]
I've added jdk8 to https://scala-webapps.epfl.ch/jenkins/view/2.N.x/job/scala-nightly-auxjvm-2.11.x/ and https://scala-webapps.epfl.ch/jenkins/view/2.N.x/job/scala-nightly-auxjvm-2.12.x/.

The latter depends on merging 2.11.x to 2.12.x in #3821.

**Pull request merged**
