### PR TITLE
SI-7201 scala-library's pom points to scaladoc url

### PR DESCRIPTION
**Pull request by adriaanm**
The project/properties/info.apiURL pom property is used by SBT
to link to an artifact's scaladoc.

For scala-library version $v, the url is http://www.scala-lang.org/api/$v/

I verified the substitution works by inspecting the pom generated by `ant deploy.local`

review by @harrah or @jsuereth

### CODE REVIEW

**Comment by retronym** [comment]
We should do the same for `scala-actors`, `scala-swing`.... When we merge to master, we must also do take care of any extra modules we've sprouted.

**Comment by adriaanm** [comment]
agreed -- we should first get some agreement with EPFL on how these docs are hosted on scala-lang

**Comment by retronym** [comment]
`-actors` and `-swing` are at the same URL as `-library`; they are presented in a unified Scaladoc.

**Comment by adriaanm** [comment]
ah yes, of course -- I only looked for -reflect and then forgot there was more to -library

**Comment by adriaanm** [comment]
actors and swing's poms are now also scaladoc-aware

**Comment by harrah** [comment]
LGTM.  Thanks!

(A side note: scaladoc appears to add its own trailing slash so that it gets doubled in the links.  I don't know if scaladoc should check if it ends in '/' before adding one or what.)

**Comment by retronym** [comment]
`-reflect` is also at that URL.

**Comment by vigdorchik** [comment]
https://github.com/vigdorchik/scala/commit/2067db85356584ca442d276d31105f0857e10025
I can submit a PR if needed.

**Comment by adriaanm** [comment]
> -reflect is also at that URL.

oh man, I don't know how I misinterpreted the scaladoc and missed that
fixing...

**Pull request merged**
