### PR TITLE
11369:New implementation of LinkedHashSet/LinkedHashMap

### PR DESCRIPTION
**Pull request by mghildiy**
New implementation of LinkedHashSet/LinkedHashMap
 Summary:

collection/immutable/ListMap.scala :  minor change to adjut latest change according changes in mutable/LinkedHashMap.scala
collection/mutable/LinkedHashMap.scala : major changes as per the need of the issue 11369
collection/mutable/LinkedHashMapTest.scala : A minor test added

### CODE REVIEW

**Comment by mghildiy** [comment]
How to rebuild this?

**Comment by SethTisue** [comment]
would this need to target 2.14, now? or is it still a possible for 2.13.x?

**Comment by szeiger** [comment]
I think the way forward for this is the same as for the new `Vector`: We need benchmarks to show that the new implementation is worth using over the current one, and it needs to be binary compatible. If the latter is not possible, this will have to wait until some 3.x release (in which case I recommend closing the PR for now).

**Comment by mkeskells** [comment]
If the library if better (faster/smaller/cleaner etc) 
We could but this stuff in a separate jar, outside `scala-library`, and for optional import for those who don't need the strict binary compatability

That way the library code can improve at a faster cadance

**Comment by plokhotnyuk** [comment]
@mkeskells could you please take security in account too?

Currently, Scala and Java core libraries have a lot of weak algorithms that are vulnerable when exposed on the edge of systems.

Please, see https://github.com/scala/bug/issues/11203 for example.

**Comment by mkeskells** [comment]
> @mkeskells could you please take security in account too?
> Currently, Scala and Java core libraries have a lot of weak algorithms that are vulnerable when exposed on the edge of systems.
> Please, see scala/bug#11203 for example.

As I see it that's just a performance issue. I was not trying to define what better meant though, it very subjective. 
For me run time, allocations and retained memory are critical. For many other these are not issues

**Comment by SethTisue** [comment]
closing for inactivity, but we can reopen if activity resumes

**Pull request closed without merging**
