### PR TITLE
Fixing initialization order bug in ExecutionContextImpl, regression from...

### PR DESCRIPTION
**Pull request by viktorklang**
... 2.10

### CODE REVIEW

**Comment by retronym** [comment]
Oh, you already did. We will merge this change from from here to 2.10.x and master, just one PR is okay.

**Comment by retronym** [comment]
lgtm

**Comment by JamesIry** [comment]
The fix seems reasonable, but to get a stamp of approval it needs
- [ ] Ticket that shows the regression is important enough for the fix to be RC-worthy.
- [ ] Ticket number in the commit subject.
- [ ] Test that reproduces the problem being fixed if at all possible or if there already is such a test a referral to it in the commit message.

**Comment by viktorklang** [comment]
https://issues.scala-lang.org/browse/SI-7146

**Comment by retronym** [comment]
The change was detected by the `-Xcheck-init` build, which is a test case of sorts. But you are right, we must have been missing a test if this went otherwise undetected.

**Comment by viktorklang** [comment]
Added test, added commit with ticket reference and trying to make sure the global EC is what we expect.

**Comment by viktorklang** [comment]
Added yet another test

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
