### PR TITLE
Merge 2.12 jun 22

### PR DESCRIPTION
**Pull request by lrytz**
https://github.com/scala/scala/pull/10016 was already forward-ported in https://github.com/scala/scala/pull/10032

```
$> git log HEAD --oneline -n 1 | cat
f5e88e4e20 Merge pull request #10027 from som-snytt/issue/12586

$> git log upstream/2.12.x --oneline -n 1 | cat
35c6f5d026 Merge pull request #10040 from lrytz/t12597

$> export MB=$(git merge-base HEAD upstream/2.12.x)

$> git log --graph --oneline $MB..upstream/2.12.x | cat
*   35c6f5d026 Merge pull request #10040 from lrytz/t12597
|\
| * ee1bf4c6e6 Position test for selections from block, xml literals
| * f9dad18702 avoid unnecessary blocks for xml ASTs
| * d5f05667bc fix start position of selections from blocks
| * 85136e3f25 fix start positions of xml trees
| * 3b9c196bbb add range positions to blocks
* |   bac51a6ae3 Merge pull request #10042 from lrytz/infixAttachment
|\ \
| * | 81b66fafa4 Attachments for infix Apply and postifx Select
| |/
* |   347fd07d09 Merge pull request #10043 from SethTisue/restarr-onto-2.12.16
|\ \
| |/
|/|
| * 4e661f819b re-STARR onto 2.12.16
|/
* c850a83a72 Merge pull request #10016 from Jasper-M/backport-2.12/12565
* 1a33a74591 fix reading symbol of Select qualifier
* b2f0559759 Add synthetic constructors only to Java annotations

$> g merge 347fd07d09 -s ours
Merge made by the 'ours' strategy.

$> g merge 35c6f5d026
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
CONFLICT (content): Merge conflict in src/compiler/scala/tools/nsc/typechecker/Typers.scala
CONFLICT (content): Merge conflict in test/files/neg/t3604.check
CONFLICT (content): Merge conflict in test/files/neg/t3769.check
CONFLICT (content): Merge conflict in test/files/neg/xmltruncated7.check
CONFLICT (modify/delete): test/files/run/t3368-c.check deleted in HEAD and modified in 35c6f5d026.  Version 35c6f5d026 of test/files/run/t3368-c.check left in tree.
CONFLICT (modify/delete): test/files/run/t3368-d.check deleted in HEAD and modified in 35c6f5d026.  Version 35c6f5d026 of test/files/run/t3368-d.check left in tree.
```

### CODE REVIEW

**Comment by SethTisue** [comment]
@lrytz should this be held for 2.13.10?

**Comment by lrytz** [comment]
Either way is fine with me

**Comment by SethTisue** [comment]
I need to figure out whether I care enough to split this into a 2.13.9 PR and a 2.13.10 PR, or whether we should just YOLO it. Now that 2.13.9 is no longer coordinated with 2.12.16 (because we're waiting for Scala 3.2 land so 2.13.9 can include 3.2 TASTy support), maybe YOLOing is fine.

**Comment by lrytz** [comment]
It's only two PRs that are actually forward-ported here: the infix/postfix attachments (#10042) and the fixes to positions (#10040). So I don't think splitting would make sense, but I think we could just put them in 2.13.9.

**Pull request merged**
