### PR TITLE
SI-6286 IllegalArgumentException handling specialized method.

### PR DESCRIPTION
**Pull request by vigdorchik**
Specialize assigns SpecialOverride info to a specialized method
even when there is a further specialization that should be forwarded
to.

### CODE REVIEW

**Comment by vigdorchik** [comment]
Review by @paulp,

**Comment by VladUreche** [comment]
LGTM
I guess @paulp won't mind me doing his reviews.

**Comment by paulp** [comment]
@VladUreche You guess entirely correctly, at least when it comes to specialization! Thanks.

**Comment by VladUreche** [comment]
Glad to take some load off your sholders. :)

**Pull request merged**
