### PR TITLE
Delete unnecessary blank line

### PR DESCRIPTION
**Pull request by sh0hei**

### CODE REVIEW

**Comment by janekdb** [comment]
You may as well include all cases. I found more using this regex in IDEA 15.0.5

```
\*\/\n\n\n\npackage scala
```

One example: `BitSet`

blank-lines-regex

**Comment by sh0hei** [comment]
@janekdb That's right. I removed more blank lines.

**Comment by janekdb** [comment]
Next step is to squash the commits into one.

**Comment by janekdb** [comment]
LGTM

**Comment by sh0hei** [comment]
@janekdb Thank you for your reviewing :smile:

**Comment by SethTisue** [comment]
@adriaanm is usually down on accepting reformatting-only PRs on the grounds that it clutters history, clutters diffs, and causes merge conflicts. but, I dunno, this one seems like it might be acceptable, since the particular location of the changes makes it especially unlikely for any merge conflicts to result, and since 2.11.x is winding down?

**Comment by adriaanm** [comment]
What Seth said -- I prefer to avoid huge reformats because the potential for merge conflicts. An individual improvement here and there in this department is unlikely to cause issues, but a huge reformat won't happen until scalafmt is palatable and then it'll be enforced by the CI.

For this particular PR, I'd like to reflect on whether our assumption that blank lines don't affect merge conflicts holds before merging.

**Comment by SethTisue** [comment]
> particular location of the changes makes it especially unlikely for any merge conflicts to result

Now that I take a closer look, I see that most of the changes in the PR are in a “particular location”, namely, after the Scaladoc comment at the top of a file but before the package declarations — but not all, some of the diffs are elsewhere.

**Comment by lrytz** [comment]
Of course we prefer well-formatted code and consistent sources, so the intention is good. But I also think that changes like this don't bring enough value given the potential merge issues downstream, and the time we spend discussion them. But since we already went that far with this particular one, I'm also fine merging it.

**Comment by janekdb** [comment]
I did an experiment which shows that blank line removal on a topic branch followed by non-blank line edits on master, then rebasing the topic branch onto master does cause merge errors. A merge also causes conflicts.

Initial file on `master` then a non-blank line edited

```
$ git recent 
68881fc janekdb@gmail.com    5 minutes ago    D -> DD
7474829 janekdb@gmail.com    6 minutes ago    Add A.txt on master
$ git show HEAD~:A.txt 
A

B
C


D
E
F

$ git show HEAD:A.txt 
A

B
C


DD
E
F

```

A topic branch was taken from the initial commit (before the D -> DD edit on master). Then on this topic branch blank lines were removed and the change committed..

```
$ git show from-master-1:A.txt 
A
B
C
D
E
F
```

While on this topic branch rebasing to master fails.

```
$ git rebase master 
First, rewinding head to replay your work on top of it...
Applying: Removed all blank lines
Using index info to reconstruct a base tree...
M   A.txt
Falling back to patching base and 3-way merge...
Auto-merging A.txt
CONFLICT (content): Merge conflict in A.txt
Failed to merge in the changes.
```

After aborting the rebase, merging to master also fails.

```
$ git checkout master
Switched to branch 'master'
$ git merge from-master-1 
Auto-merging A.txt
CONFLICT (content): Merge conflict in A.txt
Automatic merge failed; fix conflicts and then commit the result.
$ cat A.txt 
A
B
C
<<<<<<< HEAD


DD
=======
D
>>>>>>> from-master-1
E
F
```

@sh0hei  - Wait for Seth's concluding comments but maybe your time would be better spent moving the `scalafmt` work along. I'm not certain what that is but I can guess and I'm sure it would have a greater impact and more lasting benefit than continuing this commit.

**Comment by sh0hei** [comment]
@janekdb Certainly.
@adriaanm @janekdb @SethTisue @lrytz Thank you for your kindness :smile:

**Comment by adriaanm** [comment]
Now that I've had some time to think about this, I would prefer not to risk merge conflicts. I really appreciate your intent to clean up our code (and I share the desire for orderliness!), but I think we have to accept the status quo for pragmatic reasons in this case.

When scalafmt or a similar tool is able to enforce consistent formatting automatically during CI, I will be very happy to receive a sweeping PR that cleans up our code (and keeps it that way from then on)!

**Pull request closed without merging**
