### PR TITLE
SI-8325 Accept infix star type outside patterns

### PR DESCRIPTION
**Pull request by som-snytt**
Also, do not take backticked star as the repeated
parameter marker in postfix position.

Note: not satisfied with the error messages yet. This is a test run for feedback.

### CODE REVIEW

**Comment by som-snytt** [comment]
My first idea was to use backticks to disambiguate, so for infix you'd have to use backticks.  I didn't pursue it, but maybe that's tidier.

**Comment by propensive** [comment]
Great! You made low-hanging fruit of that...

**Comment by adriaanm** [comment]
Let's come back to this after 2.11.0 is out. Low-hanging fruit may block passage, but not the RC, I'm afraid.

**Comment by propensive** [comment]
No worries - I hadn't expected such a quick fix, anyway...

**Comment by som-snytt** [comment]
I thought the workflow knew how to deal with PRs not intended for 2.11.0. Otherwise, I need to use a post-it note.

**Comment by som-snytt** [comment]
I'm not going to remember to resubmit this if it stays closed. Re-opening while I notice it.

**Comment by adriaanm** [comment]
The workflow knows. Assigned to 2.11.1-RC1 milestone

**Comment by som-snytt** [comment]
> Note: not satisfied with the error messages yet.

Dude, did you not encode your dissatisfaction in a failing test?

**Comment by som-snytt** [comment]
@adriaanm I have the same question about workflow. Sorry for grabbing your attention.  I could review this one myself, as I have totally fresh eyes.  Or what's the opposite of fresh?  Anyway, I no longer have any idea what's in the delta.

**Comment by adriaanm** [comment]
Might the commit message need more review than the code, then?

**Comment by som-snytt** [comment]
@adriaanm  When you put it that way...

**Comment by som-snytt** [comment]
Rebased with an improved commit message.

**Comment by retronym** [comment]
LGTM. Merging to master, which will in turn be merged to 2.11.x.

**Comment by propensive** [comment]
Great - thanks!

**Pull request merged**
