### PR TITLE
Documentation for split [ci: last-only]

### PR DESCRIPTION
**Pull request by martijnhoekstra**
The behaviour surprised me to the point I only understood what it did after reading the source

### CODE REVIEW

**Comment by soc** [comment]
Thanks for the PR! I think adding some code examples which demonstrate the behavior would also be extremely helpful for users (if you want to go the extra mile ...:-)).

**Comment by martijnhoekstra** [comment]
sure, no problem. Should that be an amend or a new commit?

**Comment by martijnhoekstra** [comment]
writing that out made me realize you can do really horrible things with half a surrogate pair as a separator. I'm not sure if that's a bug or that you just shouldn't do that.

**Comment by martijnhoekstra** [comment]
http://scastie.org/9531 shows that the "new" split implementation introduced in https://github.com/scala/scala/commit/d1d3225e28ed1847470d976ffeefbce40e90d9ac changed the behaviour of split when the input is half a surrogate pair

**Comment by lrytz** [comment]
Thanks for pointing out the bug. I think we should avoid implementing string functions ourselfs whenever possible, given unicode's complexity (reminds me of http://stackoverflow.com/questions/6162484/why-does-modern-perl-avoid-utf-8-by-default/6163129#6163129).

Maybe we could have a different fix for SI-8988: identify characters that don't need escaping:

```
def split(separator: Char): Array[String] = {
  if (needsEscaping(separator)) toString.split(escape(separator))
  else toString.split(separator)
}
```

That way we would benefit from the optimizations in JDK 7 mentioned in the ticket.

cc @kanielc

**Comment by martijnhoekstra** [comment]
Reading through the implementation of regular expressions in Java, patterns containing an unpaired surrogate character don't match that surrogate characters in the search string if it is paired, but do match it if it is unpaired (meaning the patch I provided is wrong as well).

It doesn't matter whether the surrogate character is escaped or not (but the surrogate character will never take the JDK7 fast path).

I'll update this PR to reflect the current JDK7 implementation

This is not publicly documented on the Java side of things. It also leads to the unintuitive situation that

val high: Char = somehigh
val low: Char = somelow

val surrogatepair = List(high, low).mkstring
val doublehigh = List(high, high).mkstring
val highstring = List(high).mkstring
val lowstring = List(low).mkstring

surrogatepair.contains(highstring) //true
surrogatepair.matches(highstring) //false
doublehigh.matches(highstring) //true

**Comment by lrytz** [comment]
Wouldn't the idea I proposed above work?

Unless there's a good reason, we should not re-implement functions that exist in the JDK in our standard library.

**Comment by martijnhoekstra** [comment]
Yes, your proposed idea would work, I was just referring to updating the documentation in this PR, not the implementation in the other one (sorry for making things complicated with two PRs, the other one should probably be closed and superseded with your far more straightforward proposal)

**Comment by lrytz** [comment]
OK, Sorry for the misunderstanding! I just realized that quoting would be required for `s.split('.')`, so this call would be slow. But given that the same is true in Java (you have to write `s.split("\\.")`), I think that is acceptable.

Ideally we'd have a PR that updates both the code and the scaladoc :)

**Comment by martijnhoekstra** [comment]
I just found out s.split("\.") does follow the fast path, but s.split("\Q.\E") does not. Implementing escape as

def escape(ch: Char) = if ((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9')) "\" + ch else ch.toString

would put us on the fast path wherever possible (that is always, except surrogate characters), but before I put that in this PR I first want to write some tests (tonight CET) to confirm that this would always give the same result as the \Q\E escape, as well as some microbenchmarks to confirm that would still give performance improvements.

**Comment by lrytz** [comment]
Excellent, thanks for helping out!!

**Comment by adriaanm** [comment]
Indeed! Thanks, and welcome back, @martijnhoekstra!

**Comment by martijnhoekstra** [comment]
I'm "only" getting a ~ 500%-600% performance increase. That sounds fancy, but it's also twice as slow as claimed in the original PR

**Comment by martijnhoekstra** [comment]
in the hopes its spurious and I'm not messing things up

**Comment by adriaanm** [comment]
Sorry! We had an unexpected failure on our CI. The ant version we were using doesn't support Java 8, and there's no update available on amazon linux... Working on a fix.

**Comment by adriaanm** [comment]
I'm going to set the old commits to green and force-rebuild the last commit. I haven't reviewed the code in-depth yet, but I think it will be useful to squash these commits before finalizing the PR.

**Comment by martijnhoekstra** [comment]
There is not much code depth to review really, it has become a lot more shallow. You might have some comments on the documentation though. It's hard to be correct and readable at the same time, especially with the exception-riddled behaviour of this method

**Comment by lrytz** [comment]
Looks good, thanks! Maybe you could mention in the doc that `split` is implemented using http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#split%28java.lang.String%29

**Comment by lrytz** [comment]
LGTM, thank you! now we just have to get our CI straight :) cc @adriaanm, test failures look like this:

```
fail - presentation/ide-t1001388  [output differs]% scalac ide-t1001388/Test.scala
[...]
% diff /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/presentation/ide-t1001388-presentation.log /home/jenkins/workspace/scala-2.12.x-validate-test/test/files/presentation/ide-t1001388.check
@@ -1,3 +1 @@
-OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
-OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
 Test OK
```

**Comment by adriaanm** [comment]
These were fixed in  #4526  AFAIK

**Comment by lrytz** [comment]
The PR needs a rebase then (re-running the tests [produces the same failures](https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/36/console)).

@martijnhoekstra could you rebase your change on top the current 2.12.x branch (and also squash the two commits into one, since you're rebasing anyway)? Thank you and sorry for the inconvenience..!

**Comment by adriaanm** [comment]
The build issues turned out to be a hotspot bug (see https://github.com/scala/scala/pull/4578#issuecomment-115051647). All green now!

**Comment by martijnhoekstra** [comment]
yay

**Comment by adriaanm** [comment]
:fireworks:!

**Pull request merged**
