### PR TITLE
SI-6987 Fixes fsc compile server verbose output

### PR DESCRIPTION
**Pull request by JamesIry**
Internally the fsc server code was setting a "verbose" flag, but it was
always false. Fixing that gives server's verbose output, but because the
output was buffered and not flushed the server's output wasn't seen
until the compile run was complete. This commit fixes the verbose flag
and flushes the server side output.

No reviewer requested until the build kitteh can verify the test works reliably.

### CODE REVIEW

**Comment by lrytz** [comment]
Hi James, you can test-run a kitty-build without creating a pull request using this job in jenkins: [https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/build?delay=0sec](https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/build?delay=0sec)

**Comment by JamesIry** [comment]
Nice. Especially as the kitteh is taking a catnap.

**Comment by JamesIry** [comment]
It's reliably run many, many times on my box and a couple of times on the EPFL Jenkins services. I think I'm ready for a reviewer.

@adriaanm , you reviewed last time, here it is again but this time with a test that appears to pass on more than just my system.

**Comment by adriaanm** [comment]
jenkins job pr-scala-testsuite-linux-opt: successful -- manually verified

**Comment by adriaanm** [comment]
jenkins job pr-rangepos: successful -- manually verified

**Comment by adriaanm** [comment]
LGTM!

**Pull request merged**
