### PR TITLE
[#11067] Implementing classes of Views are private[collection]

### LINKED ISSUE #11067: implementing classes of View, SeqView, IndexedSeqView, MapView should be made private
Unless the intention is that users are directly calling these classes, by exposing these implementation details, we're committing to not changing the implementation (or at least supporting these classes) for a long while

List follows:
```scala
View.Empty
View.Single
View.Elems
View.Fill
View.Tablulate
View.Iterate
View.Filter
View.DistinctBy
View.Partition
View.Partitioned
View.PartitionWith
View.LeftPartitionWith
View.RightPartitionWith
View.Drop
View.DropWhile
View.Take
View.TakeWhile
View.ScanLeft
View.Map
View.FlatMap
View.Collect
View.Concat
View.Zip
View.ZipAll
View.Appended
View.Prepended
View.Updated
View.ZipWithIndex
View.Unzip
View.Unzip3
View.PadTo

SeqView.Id
SeqView.Map
SeqView.Prepended
SeqView.Take

IndexedSeqView.Id
IndexedSeqView.Prepended
IndexedSeqView.Take
IndexedSeqView.TakeRight
IndexedSeqView.Drop
IndexedSeqView.DropRight
IndexedSeqView.Map
IndexedSeqView.Reverse
IndexedSeqView.Slice

MapView.Id
MapView.MapValues
MapView.FilterKeys
```

### PR DESCRIPTION
**Pull request by joshlemer**
closes scala/bug#11067

### CODE REVIEW

**Comment by NthPortal** [comment]
I don't think this can be done without creating factory methods for each of the views, because they may be needed by outside libraries in order to implement their own methods or add extension methods

**Comment by joshlemer** [comment]
@NthPortal the factory methods are now added

**Comment by joshlemer** [comment]
@julienrf are you ok with this ?

**Comment by julienrf** [comment]
I'm not sure of the benefits if all constructors are still public.

**Comment by joshlemer** [comment]
The benefits are:


* the implementing classes are an implementation detail and by exposing them as public, we're committing to maintaining them and not changing them. Whereas with the factory method approach, we can for 2.13.0 implement the factory methods as they are (with all the current implementing classes), or even change to a different implementation, without it being a breaking change. They are also a pretty large maintainance burden because each one can be extended publicly, have methods overridden, may affect type inference, etc. 

* factory methods allow for certain optimizations to be made which a class-based doesn't allow. See for instance https://github.com/scala/scala/pull/7048. Using the class-based API guarantees every single transformation must always allocate a new wrapper over the underlying collection, while in the factory based approach, we are open to use the classes underneath or to have something else.

If we expose these classes as public then we are effectively shutting the door to any future optimizations such as https://github.com/scala/scala/pull/7048 and etc. Even if that PR is not accepted, these sorts of implementation details would be nice to be able to be changed for other optimizations.

**Comment by julienrf** [comment]
> Whereas with the factory method approach, we can for 2.13.0 implement the factory methods as they are (with all the current implementing classes), or even change to a different implementation, without it being a breaking change

I don’t think this is really true: for some changes in the implementation classes, we might have to also change the factory methods accordingly.

That being said, I agree that it’s better to reduce the surface area of the public API.

**Comment by Ichoran** [comment]
I don't really like the idea of making these private.  They are implementation details, it's true, but the details are extremely important for the behavior of the collections, so I think it's a bit of a false premise that keeping them secret effectively reduces the surface area of the API.  You do, I think, need to know about these details (e.g. for stack safety), and by making them private you forbid people from optimizing them while still making them care about what's there.  If this was something that was only ever used as a user-facing part of the library, I'd see the point, but people implementing their own collections may very well need to understand this in more intimate detail.

**Comment by lrytz** [comment]
I also have a tendency to leave this as-is. It's not clear that this allows for substantial optimizations while staying binary compatible (#7048 for example would not be binary compatible).

Assigning to @szeiger for a decision.

**Comment by szeiger** [comment]
Agreed. We should leave these classes public. I'm suspicious of anything `private[collection]` in basic building blocks for the collections library. If other parts of the collections need to access it, 3rd-party collection implementations will have to do the same. The `View` classes implement a standard API and they hide their implementation details. Hiding the actual classes is not much of an improvement but comes with the added complexity of the new constructor methods.

**Pull request closed without merging**
