### PR TITLE
Remove the term "pimp" from the repository in favor of "enrich"

### PR DESCRIPTION
**Pull request by danielhopkins**
Small terminology change aimed at improving inclusion.

Discussion on scala-internal: https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/kVWg7HKldjs

I signed the CLA and sent it to the email address in the PDF.

### CODE REVIEW

**Comment by danielhopkins** [comment]
@som-snytt thanks, made the update. 

I left the "an", though it's probably debatable either way so let me know if you think it should be removed.

**Comment by som-snytt** [comment]
Thanks.  I forget if moot means debatable or not worth debating.  LGBTQIA.

**Comment by paulp** [comment]
@danielhopkins The CLA validator still does not show you as signed. Can you perhaps use the clickable variation? [Right here](http://www.typesafe.com/contribute/cla).

**Comment by paulp** [comment]
@som-snytt moot is one of those words which is its own opposite! It's its own worst enemy.

**Comment by danielhopkins** [comment]
@paulp Thanks, didn't see that.

Filled in a submitted.

**Comment by paulp** [comment]
Thanks.

**Pull request merged**
