### PR TITLE
fixes run/macroPlugins-namerHooks.scala

### PR DESCRIPTION
**Pull request by xeno-by**
Makes run/macroPlugins-namerHooks.scala work equally well on both
Unix and Windows machines.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
Testing here: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/30/console

**Comment by xeno-by** [comment]
Thank you!

**Comment by retronym** [comment]
Take 2: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/32/console

(I had whitespace in a build parameter before)

**Comment by retronym** [comment]
Ignoring the spurious failure (see my email to -internals about connectivity problems today.)

The test passed in the windows build.

**Pull request merged**
