### PR TITLE
Rename to FutureConverters#as{Java,Scala}

### PR DESCRIPTION
**Pull request by NthPortal**
Rename `FutureConverters#to{Java,Scala}` to
`FutureConverters#as{Java,Scala}`.

See https://github.com/scala/scala-dev/issues/628#issuecomment-496191304

### CODE REVIEW

**Comment by adriaanm** [comment]
```
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#CompletionStageOps.toScala"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#FutureOps.toJava"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#CompletionStageOps.toScala$extension"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#FutureOps.toJava$extension"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.javaapi.FutureConverters.toJava"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.javaapi.FutureConverters.toScala"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#CompletionStageOps.asScala"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#FutureOps.asJava"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#CompletionStageOps.asScala$extension"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.FutureConverters#FutureOps.asJava$extension"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.javaapi.FutureConverters.asJava"),
ProblemFilters.exclude[DirectMissingMethodProblem]("scala.jdk.javaapi.FutureConverters.asScala")
```

**Comment by dwijnand** [comment]
(Every single binary breaking PR is going to conflict with one another, 😄.)

**Review by lrytz — APPROVED** [review]
Thanks!

**Comment by adriaanm** [comment]
I think we can reduce the breakage somewhat by leaving empty lines between the blocks of filters that we're adding. Trying that in #8093

**Pull request merged**
