### PR TITLE
Right-associative arguments don't lose singleton type

### PR DESCRIPTION
**Pull request by hrhino**
`x :: y` becomes `{ val rassoc$1 = x ; y.::(rassoc$1) }` during parser. That `val` causes `rassoc$1` to get a non-singleton type, which isn't necessarily what you want. 

The secret handshake, of course, is to make `rassoc$1` a `final val`.

Fixes scala/bug#10726.

### CODE REVIEW

**Review by milessabin — APPROVED** [review]
Yes, this looks good to me.

**Comment by hrhino** [comment]
This only works once:

```scala
> scala
[info] Running scala.tools.nsc.MainGenericRunner -usejavacp
Welcome to Scala 2.13.0-20180216-202027-778b8fd (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> ("" :: Nil) : List[""]
res0: List[""] = List("")

scala> ("" :: "" :: Nil) : List[""]
           ^
       error: inferred type arguments [""] do not conform to method ::'s type parameter bounds [B >: String]
```

because `"" :: Nil` is typed as `List[String]`. I'm not sure what can be done about that. It's specced like that, so likely nothing, but it feels less than optimal.

Edit: and people say Scala has too many symbols:
```scala
scala> "" :: [""] "" :: [""] Nil
res3: List[""] = List("", "")
```

**Comment by milessabin** [comment]
Why is this being closed without merging?

**Comment by NthPortal** [comment]
I believe you got an answer on Gitter, @milessabin, but in case anyone else comes across this, it was due to legal issues, not because the PR is problematic.

**Comment by retronym** [comment]
@hrhino I've rebased this on your behalf to please the CI gods.

**Comment by hrhino** [comment]
ah, thanks! I tried that once but I forgot to anoint myself with blessed oils and force-push at the wax of the moon.

**Review by lrytz — APPROVED** [review]
`-f`-pushed again

**Comment by hrhino** [comment]
🙇 🙇

**Comment by lrytz** [comment]
@hrhino could you check why the patch in this PR (after rebasing) changes the output of `run/t10751.scala`?

**Comment by hrhino** [comment]
Good catch, thanks. Updated, and I added a handful of more cases for the positions around right-associative arguments and final vals.

**Comment by lrytz** [comment]
@hrhino pushed another commit that removes the unreferenced `rassoc$n` ValDefs, in case the references to them get constant-folded. Let me know what you think.

**Comment by hrhino** [comment]
That commit LGTM indeed. I considered doing that but decided it may have been too much scope creep for one (originally tiny) PR. Thanks!

**Comment by hrhino** [comment]
On June 1, 2018 4:28:59 PM EDT, Lukas Rytz <notifications@github.com> wrote:
>Merged #6336.

Thanks!

**Pull request merged**
