### PR TITLE
Topic/warnings

### PR DESCRIPTION
**Pull request by paulp**
Eliminated most non-deprecation warnings in trunk.

I didn't know if this would go in 2.10.x so I'm opening separate pull requests.

### CODE REVIEW

**Comment by non** [comment]
Looks good--getting rid of these kinds of warnings is really important!

**Comment by adriaanm** [comment]
lgtm

**Comment by paulp** [comment]
I merged it into 2.10.x, so closing this (but this would be a good time to merge 2.10.x into master.)

**Comment by adriaanm** [comment]
merge pending in #1006

**Pull request closed without merging**
