### PR TITLE
SI-6811 Remove scala.annotation.cloneable

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Review by @som-snytt, please.

Now that we have a new starr, we can finally get rid of `scala.annotation.cloneable`.

**Comment by paulp** [comment]
@soc based on the mailing list discussion, would you like to deprecate Cloneable? I'll do it if you are not inclined.

**Comment by soc** [comment]
I'd prefer replacing it by an type alias. That should be possible even without deprecating stuff (as far as I remember, `scala.Cloneable` is one of those magic traits which get erased to `java.lang.Cloneable` anyway.).

**Comment by paulp** [comment]
No, it is a regular trait.

**Comment by paulp** [comment]
I'll merge this, kicking the Cloneable question downfield.

**Pull request merged**
