### PR TITLE
SI-8861 Handle alias when probing for Any

### PR DESCRIPTION
**Pull request by som-snytt**
If args to a method are alias types, dealias to see if they
contain Any before warning about inferring it. Similarly for
return and expected types.

### CODE REVIEW

**Comment by retronym** [comment]
Here's another false positive for your consideration.

``` scala
scala> trait T[A]; class C extends T[Any];
defined trait T
defined class C

scala> def foo[A](t: T[A]) = ()
foo: [A](t: T[A])Unit

scala> foo(new C)
<console>:11: warning: a type was inferred to be `Any`; this may indicate a programming error.
              foo(new C)
                  ^
```

You could go and wander though `baseTypes` to find that one, but we should really be hooking in at a different spot.

I think the best spot is:

``` scala
        // solveOne
        val newInst = (
          if (up) {
            if (depth.isAnyDepth) glb(tvar.constr.hiBounds)
            else glb(tvar.constr.hiBounds, depth)
          }
          else {
            if (depth.isAnyDepth) lub(tvar.constr.loBounds)
            else lub(tvar.constr.loBounds, depth)
          }
          )
```

I've annotated the program below with the type constraints that are LUB-ed:

```
trait T[A]; class C extends T[Any];

object Test {
  def foo[A](t: T[A]) = ()
  foo/*[Any]*/(new C) // >: Any

  List/*[Any]*/("", 0) // >: String, >: Int

  List/*[Nothing]*/() // <no constraints>
}
```

We might need a bit of plumbing to move the check into there, but I think its well worth it.

I've considered this before in the context of Abide. Under a mode, type inference could record the constraints used for each inferred type for later analysis.

A word of warning: in the end such an effort might encounter the same sort of terrain trodden by @hubertp during work on his type debugger, so it would be good to wear a decent pair of shoes.

**Comment by som-snytt** [comment]
Thanks @retronym , I knew since #4000 that I had more to think about.  I might push -f to this open PR because 4004 is the chip.

**Comment by hubertp** [comment]
Usual classics for Nothing are:

```
class TConst[+T](x: T)
def test[A, B <: TConst[A]](x: B): Unit = ()
val x: TConst[Int] = new TConst(1)
test(x)

var x = Nil

def foo[T](x: Int)(y: T): T = y
foo(1) _
```

**Comment by hubertp** [comment]
And @retronym is right, it's definitely the kind of mud I am interested in.

**Comment by som-snytt** [comment]
Thanks @hubertp I started looking at your projects this morning.

**Comment by retronym** [comment]
@som-snytt It might be worth booking the progress on this ticket while we work towards the bulletproof version, I'd be happy to accept the PR if you spin out the harder cases to a new ticket.

**Pull request closed without merging**
