### PR TITLE
SI-9545 SyncVar doc and deboxing

### PR DESCRIPTION
**Pull request by som-snytt**
Is it Deboxing Day yet in the old country? I always forget when that is.

This follows up #4583 by removing use of Option.

Also fixes doc.

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM. @Ichoran, final sign-off?

**Comment by retronym** [comment]
LGTM, too.

**Comment by SethTisue** [comment]
thank you, Som, for your patience on this.

**Comment by som-snytt** [comment]
This PR rests on the shoulder of giants.

**Pull request merged**
