### PR TITLE
Partest warns about orphan flags or check

### PR DESCRIPTION
**Pull request by som-snytt**
When it scans a "kind" directory, it looks for detritus.

### CODE REVIEW

**Review by adriaanm — APPROVED** [review]
excellint!

**Comment by som-snytt** [comment]
Thanks for the heart emojis, but that's not what I meant by "kind" directory.

**Comment by som-snytt** [comment]
It needs a tweak:
```
[test] Extraneous file: /home/jenkins/workspace/scala-2.13.x-validate-main@2/test/files/res/t687.check
```

**Comment by ashawley** [comment]
Partest has a lot of output, so a warning could be missed.  

Maybe extraneous check and flags files should be an error?

**Comment by som-snytt** [comment]
@ashawley I think that's a feature! I didn't want to do something too annoying. Actually I was going to follow up the PR when/if I was awake, which I'll do here for `res` tests. https://github.com/scala/scala/pull/7302

Probably the res tests should just be made more uniform.

I agree ultimate goal would be to fail the build, but at least it's not a correctness issue. It's more like the signs in restrooms that say employees must wash their hands.

Contributors can keep a look out for this warning while they're scanning for deprecations.

**Pull request merged**
