### PR TITLE
SI-7003 Partest redirects stderr to log file

### PR DESCRIPTION
**Pull request by som-snytt**
Some scalac output is on stderr, and it's useful to see that
in the log file, especially for debugging.

Adds a line filter for logs, specified as "filter: pattern"
in the test source.

Backslashes are made forward only when detected as paths.

Test alignments:

Deprecations which do not pertain to the system under test
are corrected in the obvious way.

When testing deprecated API, suppress warnings by deprecating
the Test object.

Check files are updated with useful true warnings, instead of
running under -nowarn.

Language feature imports as required, instead of running under -language.

Language feature not required, such as casual use of postfix.

Heed useful warning.

Ignore broken warnings. (Rarely, -nowarn.)

Debug output from the test required an update.

Review by @khernyo since he originated the issue and has looked at the feature.

### CODE REVIEW

**Comment by huitseeker** [comment]
Isn't this expected to worsen [SI-7198](https://issues.scala-lang.org/browse/SI-7198) ?

**Comment by som-snytt** [comment]
@huitseeker see the line filter, second line of message. s/worsen/ameliorate/

I broke it at the last second last night by always filtering the log, which both runs the line filter and flips back slashes, which is an old issue Paul had amended and I unamended at some point.

Sorry about that.

**Comment by som-snytt** [comment]
Updated with filters on a handful of tests that produce inliner warnings under -optimise.

It's clear that a better filter mechanism is warranted; that is out of scope here; but probably the test wants a nicer way to express what it wants to assert about its log output (besides equality with check file).

Closer to scope is the ability to ignore all inliner warnings under -optimise (for all tests), but it's not obvious that that is desirable (though it does represent previous behavior).

**Comment by som-snytt** [comment]
You can't see it in the second commit message, but the "--" in the transcript for filtering is yellow to echo the yellow of a skipped test.

**Comment by paulp** [comment]
Yow, too much code for paulp to keep up with things. Well, it's partest, it's not like it could be getting any worse. But I will feel a lot better when we spin off partest into a separate component.

**Comment by paulp** [comment]
LGTMICRF

**Comment by som-snytt** [comment]
We could move it back to a branch of the improving repo.

The partest change is only capture stderr and use filters to cope.  I expected someone to say, Will this make it harder to get my tests passing? Yes, it will.  Maybe they'll say something when they can't figure out how to make their tests pass the validator.

Maybe I'll update the Par-Test readme.

**Pull request merged**
