### PR TITLE
[REWORK] Method calls get a line number

### PR DESCRIPTION
**Pull request by som-snytt**
As reported on dotty 17425

### CODE REVIEW

**Review by lrytz — APPROVED** [review]
Thanks!

**Comment by som-snytt** [comment]
The complaint on the dotty pr is that it is too noisy for debugging. I'll experiment in draft mode.

**Comment by lrytz** [comment]
I tried the exmaples brought up by @adpi2 at https://github.com/lampepfl/dotty/pull/17428#issuecomment-1540061510 (`list.foreach`, for comprehensions), here on Scala 2 the line numbers remain unchanged with this PR.

Here's the bytecode diff for src/library with this PR: https://gist.github.com/lrytz/f128b6617018ebf6c9ae1c839e73122f

**Comment by lrytz** [comment]
This PR also fixes this example:

```scala
object T {
  def void(arg: String): Unit =
    throw new Exception

  def main(args: Array[String]): Unit = {
    void( // line 6
      toString)
  }
}
```

```
java.lang.Exception
	at T$.void(Test.scala:3)
	at T$.main(Test.scala:7)  // before, fixed to 6 by this PR
	at T.main(Test.scala)
```

**Comment by lrytz** [comment]
The following is still not correct after this PR:

```scala
object T {
  def komb(a: => Unit)(b: => Unit): Unit = { a; b }

  def void(): Unit =
    throw new Exception

  def main(args: Array[String]): Unit = {
    komb {      // line 8
      println()
    } {
      void()
    }
  }
}
```


```
java.lang.Exception
	at T$.void(Test.scala:5)
	at T$.$anonfun$main$2(Test.scala:11)
	at T$.komb(Test.scala:2)
	at T$.main(Test.scala:10) // line 10 after this PR, was line 11 before this PR
	at T.main(Test.scala)
```

**Pull request closed without merging**
