### PR TITLE
Backport/4835

### PR DESCRIPTION
**Pull request by rjmac**
Cherry-pick of the fix for SI-4835 (Stream iterators retain a reference to the head of the stream) from master to 2.9.  The only change necessary was removing the inheritance from AbstractIterator.

### CODE REVIEW

**Comment by jsuereth** [comment]
I'd love to take this patch, but it appears to break binary compatibility in 2.9.x.  Both with changing the public constructor and with adding `()` to next (which breaks source compatibility).  If you have any binary compatible ideas to fix SI-4835, I'm willing to take em.

**Comment by rjmac** [comment]
It introduces a new private constructor -- the new public auxiliary constructor has the same signature as the old primary; that should still be binary compatible, shouldn't it?  You're right about the parens-on-next though.  I've removed them.

**Comment by jsuereth** [comment]
Looks good.  I'll try to merge and push it through the binary compat checker before merging to the public 2.9.x

**Comment by jsuereth** [comment]
Ok, passed binary compat.  taking it in.

**Pull request merged**
