### PR TITLE
Restarr on PR 5398, lzycompute performance fix

### PR DESCRIPTION
**Pull request by retronym**
Depends on:

  https://scala-ci.typesafe.com/view/scala-2.12.0/job/scala-2.12.0-release-main/69/console

doing as I hope and us promoting the build to Maven central.

### CODE REVIEW

**Comment by retronym** [comment]
Follow up to #5398

**Comment by retronym** [comment]
I forgot to include `-RC1-` in the version number of this, as we did before with `2.12.0-M4-9901daf` and `2.12.0-M3-dc9effe`.

image

I've dropped the staging repository.

**Comment by retronym** [comment]
Rerunning as https://scala-ci.typesafe.com/view/scala-2.12.0/job/scala-2.12.0-release-main/71/console

**Comment by retronym** [comment]
I've released https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala-compiler/2.12.0-RC1-be43eb5/

Once that appears https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.0-RC1-be43eb5/, we can rebuild this PR.

**Comment by retronym** [comment]
Review by @SethTisue

**Comment by SethTisue** [comment]
LGTM

**Pull request merged**
