### PR TITLE
Use ArrayBuilder for line indices

### PR DESCRIPTION
**Pull request by som-snytt**
Riff on https://github.com/scala/scala/pull/8489 responding to my comments.

### CODE REVIEW

**Comment by som-snytt** [comment]
Closing since Jenkins didn't even bother to complete. On the other PR, the supposition is that the preliminary pass to count lines is cheaper than an array allocation (that is, extra array allocation and copy).

**Comment by som-snytt** [comment]
Instead of pre-scanning the source to count EOL, pre-size an `ArrayBuilder` with a decent guess and incur at least one reallocation and copy when done with the "lines" table.

Conservatively guess 30 chars/line to avoid growing the array. `Typers` is 310KB and 6400 LOC, almost 50 chars/line.

Benchmarking to determine when pre-scanning for an exact allocation beats single scan but copying the result is left as a future exercise.

**Review by lrytz — COMMENTED** [review]
LGTM for 2.13.9

**Comment by som-snytt** [comment]
woo-hoo! Whenever lrytz says the L-word, I feel like I've won.

**Pull request merged**
