### PR TITLE
Constructors refactoring [Rebase of #2715]

### PR DESCRIPTION
**Pull request by adriaanm**
[Rebase of #2715]

Review by @JamesIry before 2.11.0-M5 window closes. I consider merging this PR a blocker.

The `constructors` phase has grown over time, with sub-transformations being added to the all-encompassing `transformClassTemplate()` on an as-needed basis.

This PR breaks that method apart, encapsulating each sub-transformation in a trait dedicated to it. Documentation has been thrown in, too.

This PR essentially plays again the commits of https://github.com/scala/scala/pull/2599
adapted to `Constructors.scala` in its current form.

Those commits were once merged into master, but had an ephemeral existence:
they were inadvertently _overwritten_ by the merge of 2.10.2 into master,
see commit 767a25fe2178b00f494d55bdaae53535cd7fb57d 

This PR is a pre-requisite for an upcoming re-submission of https://github.com/scala/scala/pull/2665 ,
to make anon-closures retain fewer heap objects (currently, in some cases, more objects are retained via outer-refs than really needed).

Please merge this PR before Constructors.scala drifts again.

### CODE REVIEW

**Comment by adriaanm** [comment]
ping @JamesIry

**Comment by magarciaEPFL** [comment]
What's the status of this PR?

**Comment by adriaanm** [comment]
I have been trying to get @JamesIry to review it because he and @gkossakowski spent quite a bit of time with this phase recently. I think it's great you cleaned this up, and I'd like to include it in M5. I'm unfortunately no expert about constructors, but I can have a look.

**Comment by soc** [comment]
Would be nice to get this merged, because I'd also like to fix some bugs in `Constructors.scala`.

**Comment by adriaanm** [comment]
Yay, thank you all!

@soc, would you like to include the suggested improvement in your upcoming PR?

**Comment by soc** [comment]
@adriaanm Yes, that's my plan.

**Pull request merged**
