### PR TITLE
SI-6908 FlatHashTable and things that depend on it can't store nulls

### PR DESCRIPTION
**Pull request by Ichoran**
Fixed ParFlatHashTable to use entryToElem which correctly converts sentinels to nulls.

### CODE REVIEW

**Comment by adriaanm** [comment]
while you're in the vicinity, would be good to avoid going through getters for itertable and his other private friends by making them private[this]

**Comment by Ichoran** [comment]
@adriaanm - Given that JVMs are good at eliding getters, I doubt this matters, but I've done it anyway as a second commit.

**Comment by adriaanm** [comment]
Thanks. I'm certainly not as expert as you when it comes to JVM performance, so my approximation is "if the JIT doesn't have to do it, it doesn't have to do it" (and for us it's easy).

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
