### PR TITLE
Remove deprecated Java collection conversions

### PR DESCRIPTION
**Pull request by som-snytt**
The conversions were deprecated in 2.12.

Some tests were about type inference,
one test was updated to use explicit adaptation.

In case the team is interested in jettisoning this old burden.

### CODE REVIEW

**Review by szeiger — CHANGES_REQUESTED** [review]
`ToScalaImplicits` and `ToJavaImplicits` are explicitly mentioned as replacements in the deprecation messages so we shouldn't remove them. (At least not yet -- should they be deprecated in favor of `JavaConverters`?)

**Comment by som-snytt** [comment]
I think those are just the migration path for much-maligned `JavaConversions`, suffering the same flaws but with less devious name. Modulo IIRC. I'll check it out.

**Comment by som-snytt** [comment]
OK, updated the commit message and left `ImplicitConversions`. I see `JavaConversions` and its buddies in `convert.package` were removed in strawman, so this commit just cleans up a bit more.

I think `ImplicitConversions` was intended as more explicit way to point a rifle at one's big toe, but I don't see in the conversation that it was intended only for migration. Lukas added a comment to prefer `JavaConverters` as usual; that could be a deprecation message without `forRemoval` as they say in latest Java, that is, it's the eternal reminder to prefer the explicit conversion.

(If folks insist on using eternally deprecated API, then they can use a warning-suppressant Reporter!)

The deprecation PR: https://github.com/scala/scala/pull/5109

**Review by lrytz — APPROVED** [review]
I think deprecating the remaining implicit conversions would be good - at least I don't see a good reason to keep them.

**Pull request merged**
