### PR TITLE
makes well-known packages and package classes consistent with each other

### PR DESCRIPTION
**Pull request by xeno-by**
As discovered in https://groups.google.com/forum/#!topic/scala-user/RckXE90LoXo,
RootClass.sourceModule and EmptyPackageClass.sourceModule used to incorrectly
return NoSymbol instead of RootModule and EmptyPackage. This is now fixed.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by som-snytt** [comment]
I wonder if the test is a candidate for junit, since it tests an invariant that doesn't require test isolation.

I don't have credentials here for a PR, but a sample `test/junit/scala/reflect/internal/MirrorsTest.scala`

```
package scala.reflect.internal

import org.junit.Assert._
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.JUnit4

@RunWith(classOf[JUnit4])
class MirrorsTest {
  @Test def rootCompanionsAreConnected(): Unit = {
    val cm = scala.reflect.runtime.currentMirror
    import cm._
    assertEquals("RootPackage.moduleClass == RootClass", RootClass, RootPackage.moduleClass)
    assertEquals("RootClass.module == RootPackage", RootPackage, RootClass.module)
    assertEquals("EmptyPackage.moduleClass == EmptyPackageClass", EmptyPackageClass, EmptyPackage.moduleClass)
    assertEquals("EmptyPackageClass.module == EmptyPackage", EmptyPackage, EmptyPackageClass.module)
  }
}
```

**Comment by xeno-by** [comment]
@som-snytt Thanks! Done.

**Comment by retronym** [comment]
LGTM

**Pull request merged**
