### PR TITLE
Merge 2.10.x into master

### PR DESCRIPTION
**Pull request by adriaanm**
- 78d15a1308: git merge 5d54cf9e37 -m"Merge 2.10.x into master. [...]"
- 21fc4c710f: git merge c4eede47d7 2cf6c5d7e5 387fbf459e [1]
- a941850c2e: git merge 1a84c86ce4 -m"Merge 2.10.x into master."
- 6dda983596: git merge 773f6a8df9 -m"Merge 2.10.x into master."
- c46f5ba694: git merge -s ours scala/2.10.x -m"No-op merge for [nomaster] part of 2.10.x"

The last merge was indeed ok to be no-op:

```
$ git log 6dda983596..scala/2.10.x --oneline --stat:
1176035f27 (scala/2.10.x) Merge pull request #2193 from adriaanm/patmat-refactor
f482d5bdd0 (scala/pr/2193) Merge 2.10.1 into 2.10.x
33e32179fd (tag: v2.10.1-RC3, scala/2.10.1) Merge pull request #2190 from adriaanm/test-runs-mima-2.10.1
54a9f1bb76 Merge pull request #2189 from adriaanm/ticket-7195
09130d55fd (scala/pr/2189) [nomaster] SI-7195 minor version mustn't introduce warnings
 src/compiler/scala/tools/nsc/typechecker/Typers.scala |  4 +++-
 test/files/neg/t5954.check                            | 16 ----------------
 test/files/neg/t5954.flags                            |  1 -
 test/files/neg/t5954.scala                            | 46 ----------------------------------------------
 4 files changed, 3 insertions(+), 64 deletions(-)
b775d8f16d (scala/pr/2190, adriaanm/test-runs-mima-2.10.1, test-runs-mima-2.10.1) test.done again checks bin compat (using mima 0.1.5)
 bincompat-backward.whitelist.conf | 4 ++++
 build.xml                         | 8 ++++----
 2 files changed, 8 insertions(+), 4 deletions(-)
440bf0a8c2 (2.10.1) Merge pull request #2168 from retronym/ticket/7183
0303e64efa (scala/pr/2168) SI-7183 Disable unreachability for withFilter matches.
 src/compiler/scala/tools/nsc/typechecker/PatternMatching.scala | 42 ++++++++++++++++++++++++++++--------------
 test/files/pos/t7183.flags                                     |  1 +
 test/files/pos/t7183.scala                                     | 13 +++++++++++++
 3 files changed, 42 insertions(+), 14 deletions(-)
```

[1] determined all commits in HEAD..scala/2.10.x that merged cleanly as follows:

``` bash
commits=$(for c in `git rev-list 78d15a1308..scala/2.10.x`; do if ( git merge -n $c &> /dev/null ); then echo "OK: $c" && grh HEAD^; else grh; fi; done | grep OK: | perl -pe 's/OK: //')
git merge $commits -m"Merge 2.10.x into master."
```

review by @gkossakowski, @paulp

### CODE REVIEW

**Comment by adriaanm** [comment]
Working on fixing the problem here.

**Comment by paulp** [comment]
I helped out by merging in the boolean-args patch. Hey, I already rebased it twice today, it seemed entitled.

**Comment by adriaanm** [comment]
Redid the merge. Verified by meta-diffing:

```
git diff 031c5be557ed49f02ab365d64e55f30c616a5939..scala/2.10.x > /tmp/a
git diff 32f04db672..59fbc0a32e > /tmp/b
```

**Comment by adriaanm** [comment]
it's broken:

```
 /Users/adriaan/git/scala-build/src/compiler/scala/tools/nsc/interactive/Picklers.scala:167: error: could not find implicit value for evidence parameter of type scala.tools.nsc.io.Pickler[List[(Picklers.this.Symbol, scala.reflect.internal.util.SourceFile)]]
[scalacfork]     (pkl[Symbol] ~ pkl[SourceFile] ~ pkl[Symbol] ~ pkl[List[(Symbol,SourceFile)]])
[scalacfork]                                                       ^
[scalacfork] one error found

```

looking into it

**Comment by adriaanm** [comment]
Well, that was unpleasant. I verified all kinds of ways that this merge is the one, after all kinds of fun little mishaps in the process.

**Comment by paulp** [comment]
If it's any consolation, I never figured it out.

**Comment by adriaanm** [comment]
Why it compiled in 2.10.x? I had to "Resurrect some undead code from 373ded2 (tuple2Pickler)."

**Comment by paulp** [comment]
Oh, the old undead code gambit. My bad.

**Comment by adriaanm** [comment]
For the record, I think the PR is good to go. There's one test failing whose check file I fixed in a later commit. I'm not redoing all these merges for a one-word change in a check file.

**Comment by paulp** [comment]
Yeah, I know that feeling. You know about rebase --preserve-merges, yes? I haven't had great luck with using it to fix up merge commits I admit.

**Comment by gkossakowski** [comment]
FYI: I'll try to do the fix up.

**Comment by gkossakowski** [comment]
@adriaanm: how to refresh status of those commits? I'd like to make sure that what we merge is all green.

**Comment by adriaanm** [comment]
Yep, I've never gotten --preserve-merges to work on anything non-trivial.

The status of the commits is accurate, except for the earlier ones: they are yellow because of that "race condition" bug in the build bot's reporting.

**Comment by adriaanm** [comment]
oh wait, now the 7185 fails again!? I have no idea what's going on. I confirmed that the check file needed a s/module/object/ on my machine

**Comment by adriaanm** [comment]
Ok, I'll go in one more time. Thanks for the offer @gkossakowski, but all the conflict resolutions are burned into my retina, so it probably makes more sense I fix it.

**Comment by gkossakowski** [comment]
@adriaanm: sure. I just wanted to see if I can somehow get amending merges to work because that would be handy in the future. In case you are feeling tired of dealing with this merge just let me know. I'm around the corner.

**Comment by adriaanm** [comment]
Feel free to give it a go -- would love to know how to use --preserve-merges in general.

**Comment by gkossakowski** [comment]
@adriaanm: sure, which commit the 758726a should amend?

**Comment by adriaanm** [comment]
it's the very first merge commit: 3827a09 :(

I redid the merge in the mean time. Running tests locally.

**Comment by adriaanm** [comment]
This is bizarre -- I redid the merge, diffed the new HEAD against this PR's HEAD --> empty, but the tests pass.

**Comment by adriaanm** [comment]
Ah yes, I forgot -- it's a reporting bug. Bah, these 2-bit commit statuses are really starting to annoy me.

**Comment by gkossakowski** [comment]
@adriaanm: I looked into that and you guys are right. There's no hope for git rebase to work in this case. I don't think that there's hope for anything else to work automatically for us (apart from rerere). The reason is that we use really non-trivial merge strategies (like -Xours) and I don't think git tools are capable of coping with those.

**Comment by gkossakowski** [comment]
@adriaanm: shall we close this PR and start from scratch with your corrected merge?

**Comment by adriaanm** [comment]
here are the jobs for the HEAD of this PR: https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/909/, https://scala-webapps.epfl.ch/jenkins/job/pr-rangepos-per-commit/915/

both passed

**Comment by adriaanm** [comment]
I'll just push -f my new branch here. The diff between their HEADs is zero, so I'm going to merge the PR after  that.

**Comment by adriaanm** [comment]
The bot should eventually sign off on this PR as all merges are now expected to pass. @paulp, I'll let you pull the trigger.

**Comment by paulp** [comment]
Triggerman deployed.

**Pull request merged**
