### PR TITLE
Statistics reorganization

### PR DESCRIPTION
**Pull request by adriaanm**
Statistics were broken since the move to reflect.internal. They are now
re-organized, made more robost and modular.

### CODE REVIEW

**Comment by adriaanm** [comment]
this is the rebased version of #740 /cc @odersky

**Comment by adriaanm** [comment]
for the record, here's my workflow to quickly rebase stuff like this:

```
hub checkout https://github.com/scala/scala/pull/740
git pull --rebase main master # pull in master and rebase
git mergetool # deal with merge conflict (I use FileMerge)
git add -u # stage files to continue rebase (not sure this is still needed, actually)
grc # alias for git rebase --continue
git show # check diff
git push origin HEAD:pullreq/740-rebased # push (current HEAD) to my own repo (as the branch pullreq/740-rebased) so I can submit a pull request
```

to double check the diff, I meta-diff the old and new diff as follows:

```
git show > /tmp/new
git show odersky/topic/stats-pullrequest > /tmp/old
diff /tmp/old /tmp/new
```

**Comment by odersky** [comment]
Thanks! I actually did rebase before I submitted, but it seems master moved faster.

**Comment by adriaanm** [comment]
You're welcome. Your original pull request was indeed going to merge cleanly, but there was a conflicting pull request in the queue.

**Pull request merged**
