### PR TITLE
SI-6335 More precise location of the implicit class synthetic method.

### PR DESCRIPTION
**Pull request by retronym**
One approach would be to disallow an implicit class in a template
that already has a member with the same name.

But this commit doesn't do this; instead it uses `isSynthetic` to
find the synthesized implicit conversion method from the potentially
overloaded alternatives.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @paulp, please.

**Comment by jsuereth** [comment]
Neato!  +1 from a guy who doesn't understand synthetic ramifications besides this code working.

 Note: would you like help writing more exhaustive tests?   I worry our implicit class testing isn't too thorough with this kind of interaction.

**Comment by retronym** [comment]
I've pushed a few more tests, including a `neg` test that shows what happens when an explicitly defined method has the same signature as the synthesized method.

**Comment by gkossakowski** [comment]
LGTM from me.

**Pull request merged**
