### PR TITLE
Fix for SI-6597, implicit case class crasher.

### PR DESCRIPTION
**Pull request by adriaanm**
[backport to 2.10.x of #1550]

It seems to me like every call to scope.lookup in the
compiler is a latent bug. If a symbol is overloaded, you
get one at random. (See the FIXME comment in f5c336d5660
for more on this.)

### CODE REVIEW

**Comment by paulp** [comment]
Re: the failure:

```
  [partest] testing: [...]/files/continuations-run/t5472.scala                    [  OK  ]
  [partest] testing: [...]/files/continuations-run/while0.scala                   [  OK  ]
  [partest] testing: [...]/files/continuations-run/trycatch1.scala                [  OK  ]
  [partest] testing: [...]/files/continuations-run/while1.scala                   [  OK  ]
  [partest] testing: [...]/files/continuations-run/while2.scala                   [  OK  ]
Build was aborted
Finished: ABORTED
```

There has to be a timeout set somewhere, something like that. If nothing else we should work backward from where the string "Build was aborted" occurs. It's ridiculous to have test runs which are on their way to success aborted and failed. and nobody knows why.

**Comment by lrytz** [comment]
it's still the same issue that communication between jenkins master and slaves fails. together with every abort (and they happen daily) comes always a stack trace in the jenkins log. For the one above:

```
INFO: pr-rangepos #811 aborted
java.lang.InterruptedException
    at java.lang.Object.wait(Native Method)
    at hudson.remoting.Request.call(Request.java:146)
    at hudson.remoting.Channel.call(Channel.java:663)
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:158)
    at $Proxy35.join(Unknown Source)
    at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:861)
    at hudson.Launcher$ProcStarter.join(Launcher.java:345)
    at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:82)
    at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:58)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:717)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
    at hudson.model.Run.execute(Run.java:1502)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:236)
```

i still have no idea how to fix it. see also here https://github.com/scala/scala/pull/1528#issuecomment-9846003

**Comment by paulp** [comment]
I picked through the jenkins source a while. There is something called CauseOfInterruption which is supposed to give us the missing hint here about what's going on. Not working so much apparently.

Have we tried disabling every possible plugin? In an architecture like jenkins, when you have a problem which is not widely shared, plugins should be the leading contenders.

**Comment by lrytz** [comment]
i did disable all plugins that we don't use, but for the ones we depend on i cannot really disable them (git, email ext, ssh slaves, build timeout, copy artifacts)...

**Comment by adriaanm** [comment]
imma go ahead and merge as a post-halloween gamble (for me, this is a gamble)

**Pull request merged**
