### PR TITLE
SI-7592 Replace s.t.n.u.TreeSet with s.c.m.TreeSet

### PR DESCRIPTION
**Pull request by soc**
This means
- migrating usages from the compiler-specific implementation to the
  one in the standard library
- removing the now unused compiler-specific implementation

### CODE REVIEW

**Comment by soc** [comment]
Maybe @lpereir4 can comment whether he sees any obstacles against using his implementation?
Review by @paulp? Paul, let me know if I should ask someone else, please.

**Comment by lpereir4** [comment]
@soc I see no obstacles at all. Moreover, s.c.m.TreeSet implementation is not based on an AVL tree anymore. AVLTree is now deprecated.

https://github.com/scala/scala/commit/39037798c94e6e862f39dacffc5e65bb08b78d6a
https://issues.scala-lang.org/browse/SI-7155

**Comment by soc** [comment]
@lpereir4 Ah right, didn't realize that your implementation was originally AVL-based. Thanks!

**Comment by adriaanm** [comment]
review by @JamesIry

**Comment by adriaanm** [comment]
ping @JamesIry

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
