### PR TITLE
Paring back the scope of our shared .gitignore

### PR DESCRIPTION
**Pull request by retronym**
Importantly, limit the exclusion of build.properties
to the file in the root directory, paving the way for
the return of an SBT build.
- Unignores .bak, .jar, and ~
- limit ignorance of qbin to the root directory

.log files, generated by partest, are still ignored.

To see ignored files in your workspace, try:

```
git ls-files --others --ignored --exclude-standard -- test | grep log
git status --ignored -- test
```

Review by @paulp

### CODE REVIEW

**Comment by paulp** [comment]
Actually *.jar was the one thing in the .gitignore I was glad to see. That extension is special in our repository thanks to pull-binary-libs - a completely git-cleaned repository isn't buildable, only a git-cleaned + a bunch of jars which are spread out in many directories. But people shouldn't have to add *.jar to their global gitignore.

**Comment by clhodapp** [comment]
I'll half-hearted start the already-lost battle of saying that there's no global gitignore, there's a global git excludes file.

In any case, there's an intermediate point between '_.jar' and no '_.jar'; There's a *\* wildcard, which you lets you put things like (e.g.) '/lib/*_/_.jar' in the .gitignore to avoid specifying each jar individually, while also avoiding showing clean when there are other jars around. This type of wildcard does require a fairly late-model build of git to work correctly.

**Comment by paulp** [comment]
@clhodapp interesting, I see you are right that there is no global gitignore. But it's not clear to me what distinction is being drawn.

It is no big deal to enumerate all the jars specifically, they don't change often and we shouldn't be adding more anyway. It makes no difference to me if it's `*.jar or all the jars or some **/* patterns`, the important thing is that as long as there's a gitignore, it ought to cover the jars.

```
find . -name '*.jar' | sed 's/^.//'
/lib/ant/ant-contrib.jar
/lib/ant/ant-dotnet-1.0.jar
/lib/ant/ant.jar
/lib/ant/maven-ant-tasks-2.1.1.jar
/lib/ant/vizant.jar
/lib/forkjoin.jar
/lib/scala-compiler-src.jar
/lib/scala-compiler.jar
/lib/scala-library-src.jar
/lib/scala-library.jar
/lib/scala-reflect-src.jar
/lib/scala-reflect.jar
/test/files/codelib/code.jar
/test/files/lib/annotations.jar
/test/files/lib/enums.jar
/test/files/lib/genericNest.jar
/test/files/lib/jsoup-1.3.1.jar
/test/files/lib/methvsfield.jar
/test/files/lib/nest.jar
/test/files/speclib/instrumented.jar
/tools/push.jar
```

**Comment by paulp** [comment]
@retronym A+ on your branch naming.

**Comment by retronym** [comment]
@paulp I've added the JARs back

**Comment by paulp** [comment]
LGTM, my bliss is complete.

**Pull request merged**
