### PR TITLE
Remove "will not terminate" from toStream doc

### PR DESCRIPTION
**Pull request by puffnfresh**
It's at least not always true:

```
scala> val example = Iterator.continually(1).toStream
example: scala.collection.immutable.Stream[Int] = Stream(1, ?)
```

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks, LGTM

Please sign the [Scala CLA](http://typesafe.com/contribute/cla/scala) so that we can include this.

**Comment by puffnfresh** [comment]
@adriaanm I have already signed that and already have commits in scalac.

**Comment by puffnfresh** [comment]
@adriaanm I just realised there's a new CLA GitHub application. Nice!

Just signed again, using that one.

**Comment by adriaanm** [comment]
Sorry about the over[sight|head], and thanks for signing again!

**Pull request merged**
