### PR TITLE
SI-6736 Range.contains is wrong

### PR DESCRIPTION
**Pull request by Ichoran**
Removed once-used private method that was calculating ranges in error and corrected the contains method (plus improved performance).

### CODE REVIEW

**Comment by adriaanm** [comment]
Related, what should `(Int.MinValue until 0).last` be? (Seems like the underlying problem to me.)

```
> set resolvers += "pr-scala" at "http://private-repo.typesafe.com/typesafe/scala-pr-validation-snapshots/"
> set scalaVersion :=  "2.11.0-bbf0a5d-SNAPSHOT"
> console
Welcome to Scala version 2.11.0-bbf0a5d-SNAPSHOT (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_65).
scala> (Int.MinValue until 0).last
res0: Int = 2147483646
```

**Comment by adriaanm** [comment]
Regardless, the fix itself is an improvement. We should probably also actively sanity-check the value of `step` (!= 0, nor perhaps the max/min values ints are cool with)

**Comment by Ichoran** [comment]
I should fix last as well while I'm at it.  (I wouldn't revert this change once last is fixed, though, as I got a 4-5x speedup on contains.)

**Comment by adriaanm** [comment]
Perfect.

**Comment by Ichoran** [comment]
Updated with a second commit to fix `last`.  In a manner of speaking.  (I will be so glad when we can remove those pointless vals.  Avoiding two long divisions on creation won't hurt anyone either.  But that's for 2.12, I guess.  Maybe I should open a ticket so I don't forget.)

**Comment by adriaanm** [comment]
I'm confused -- why isn't  `(Int.MinValue until 0).last == 0`?

**Comment by Ichoran** [comment]
@adriaanm - Because the range is too large, and it should be consistent with `apply(length - 1)` (which will give an error).

**Comment by adriaanm** [comment]
Then why override `last` at all? The documentation does not specify `last == apply(length-1)` (although that's the implementation). I of course was off by `step` above, but I still think `range.last == range.end - range.step` is more intuitive, especially since `range.head == range.start`.

**Comment by Ichoran** [comment]
Just going for consistency.  If that's not so important (or if the point of `Range` is to only act like a collection class that is size-limited when one must act that way), then I can change it.

**Comment by adriaanm** [comment]
I'm honestly not sure which is the more consistent choice. I tend to go for minimizing WTF/method call.

**Comment by adriaanm** [comment]
I think of a Range as a lazy collection that you can iterate over. Technically, we're not even breaking the invariant `xs.apply(xs.length-1) == xs.last` since `apply` is not defined, so all bets are off. I think it's more surprising to not be able to get the first/last element of a range than apply and last failing to fail consistently.

**Comment by Ichoran** [comment]
I think everything is surprising since there's no obvious expectation when creating something that acts as a collection but is outside the bounds of what a collection can contain.  But it's not hard to get `last` to work right, so I'll do that instead.

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
@Ichoran Wow, nice fixes! Having struggled with that code some time ago, I can imagine the pain you went through to fix this! Thanks a lot!

**Comment by adriaanm** [comment]
LGTM -- excellent code, nice tests, much fewer WTF/line for users!

**Comment by adriaanm** [comment]
soon some of these wishes will be granted

**Pull request merged**
