### PR TITLE
Fix problem assembling sources and docs of modules.

### PR DESCRIPTION
**Pull request by retronym**
A recent commit added 'overwrite=true' to all usages of the Ant copy task.

This was enough to show up a bug in our dist.src and dist.docs tasks, as was
seen on the Windows build:

```
Failed to copy:
```

C:\Users\scala.m2\repository\org\scala-lang\modules\scala-xml_2.11.0-M5\1.0-RC4\scala-xml_2.11.0-M5-1.0-RC4-javadoc.jar
to

H:\jenkins\workspace\scala-nightly-windows\dists\scala-2.11.0-20131019-064627-8848f24161\doc\scala-devel-docs\C:\Users\scala.m2\repository\org\scala-lang\modules\scala-xml_2.11.0-M5\1.0-RC4\scala-xml_2.11.0-M5-1.0-RC4-javadoc.jar
...

This commit uses a "flattening" copy to put the JARs directly into 
scala-devel-docs.

The Ant docs note [1] this gotcha:

> Note that some resources (for example the file resource) return
> absolute paths as names and the result of using them without
> using a nested mapper (or the flatten attribute) may not be what
> you expect.

These appear to be the only places we fell into the trap:

```
% ack '<file\b' --xml
build.xml
1948:      <file file="${scala-xml-javadoc}"/>
1949:      <file file="${scala-parser-combinators-javadoc}"/>
1992:        <file-sets/>
2007:      <file file="${scala-xml-sources}"/>
2008:      <file file="${scala-parser-combinators-sources}"/>
```

[1] http://ant.apache.org/manual/Tasks/copy.html

### CODE REVIEW

**Comment by retronym** [comment]
Manually triggered a windows build: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual-windows/27/console

**Comment by retronym** [comment]
review by @adriaanm

**Comment by retronym** [comment]
Process note: PRs that touch the build should be subjected to a manual Windows build.

**Comment by retronym** [comment]
It does look a bit half-finished with the JARs just dropped in there. What is the intended layout?

```
ls /Users/jason/code/scala/dists/scala-2.11.0-20131020-085639-509440d258/doc/scala-devel-docs/api/
index       index.js    package.html
index.html  lib     scala
topic/fix-dist ~/code/scala ls /Users/jason/code/scala/dists/scala-2.11.0-20131020-085639-509440d258/doc/scala-devel-docs
README.scala-swing
api
examples
scala-parser-combinators_2.11.0-M5-1.0-RC2-javadoc.jar
scala-xml_2.11.0-M5-1.0-RC4-javadoc.jar
tools
```

**Comment by adriaanm** [comment]
Yeah, it's not pretty in there. Cleaning it up here: https://github.com/adriaanm/scala/compare/modularize-scaladoc-wip

**Comment by retronym** [comment]
I'm going to take your lack of objection as approval and merge this to get the nightly going again.

**Comment by adriaanm** [comment]
yes, sorry, LGTM

**Pull request merged**
