### PR TITLE
SI-6090

### PR DESCRIPTION
**Pull request by odersky**
Sharpens the test so that only Object_== and Object_!= methods on valueclasses may be rewritten in posterasure, whereas user-defined methods are not rewritten. Review by @retronym.

### CODE REVIEW

**Comment by retronym** [comment]
This change looks good, but I also spotted another bug of the same ilk that you could fix while you're in the vicinity.

``` scala
scala> class X(val a: Int) extends AnyVal { def this(x: String) = this(0) }
defined class X

scala> new X("").a
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at
```

**Comment by retronym** [comment]
And another one:

``` scala

scala> class A(val x: Int) extends AnyVal { def this(s: String) = this(s.length) }
defined class A

scala> new A("a") == new A("b")
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at scala.runtime.BoxesRunTime.unboxToInt(Unknown Source)
    at .<init>(<console>:9)
    at .<clinit>(<console>)

```

All of these spots should be tightened up to only consider the primary constructor. An extractor for `s @ Select(New(tpt), nme.CONSTRUCTOR) if s.sym.isPrimaryConstructor` might be cleanest.

https://github.com/scala/scala/blob/39fc4aa84/src/compiler/scala/tools/nsc/transform/Erasure.scala#L362

https://github.com/scala/scala/blob/39fc4aa84/src/compiler/scala/tools/nsc/transform/Erasure.scala#L1003

https://github.com/scala/scala/blob/39fc4aa84/src/compiler/scala/tools/nsc/transform/PostErasure.scala#L36

https://github.com/scala/scala/blob/39fc4aa84/src/compiler/scala/tools/nsc/transform/PostErasure.scala#L46

**Comment by adriaanm** [comment]
@retronym, would you like to submit a separate pull request with your improvements? (Otherwise I'll do it by the end of the week. In any case, merging this one already.)

**Comment by retronym** [comment]
Yep, I started working on that yesterday, should have something to submit in two days.

**Comment by adriaanm** [comment]
Cool!

**Pull request merged**
