### PR TITLE
Eliminating allocations.

### PR DESCRIPTION
**Pull request by paulp**
```
At this commit the statistics when compiling src/library
are as follows. These counts are precise, collected by a
modified Function1 which counts every instantiation of every
implementing class. The net result is 27 million fewer
allocations, over a 20% drop.

  // master (5b5635ee9d), total and top five by count:
  Total Function1 allocations: 128,805,865

  scala.collection.immutable.$colon$colon 26781958
  scala.collection.mutable.ListBuffer 15365174
  scala.collection.TraversableLike$$anonfun$map$1 9127787
  scala.collection.generic.Growable$$anonfun$$plus$plus$eq$1 4636154
  scala.collection.mutable.StringBuilder 3531211

  // After these commits, total and top five by count:
  Total Function1 allocations: 101,865,721

  scala.collection.immutable.$colon$colon 26993704
  scala.collection.mutable.ListBuffer 15319656
  scala.collection.TraversableLike$$anonfun$map$1 7585019
  scala.reflect.internal.Types$MethodType$$anonfun$paramTypes$1 2447307
  scala.reflect.internal.Types$SubstSymMap 2436088
```

### CODE REVIEW

**Comment by soc** [comment]
This looks very impressive to me, but is it sure that the compiler won't be able to do this optimization automatically in the foreseeable future?

**Comment by paulp** [comment]
Would it matter if it did? It's not like these patches leave the wreckage of elegance in their wake.

But no, the compiler won't be performing these optimization(s) (there are at least three or four different approaches in here) anytime soon.

**Comment by paulp** [comment]
Perhaps @JamesIry would like to review this one.

**Comment by JamesIry** [comment]
LGTM, but also makes me sad.

**Comment by paulp** [comment]
We'll turn your sad panda face upside down eventually.

**Pull request merged**
