### PR TITLE
Don't use runtime reflection from the batch compiler.

### PR DESCRIPTION
**Pull request by retronym**
Not only does this save a big chunk of time on startup by avoiding
classloading and symbol table population, but it also seems to
improve steady state performance of the compiler.

Theory: JIT can optimize more aggressively without the
SynchronizedXxx decorators and the like being in the classloader.
See "Class Heirarchy Analyis" in [1]

This commit does this by:
- Avoiding use of FromString in pattern matcher, instead
  using an established mechanism to parse system properties.
- Changes FromString back to use OptManifest. AFAICT, this
  is now only a dependency of scala.tools.cmd.gen.Codegen,
  so this is just a defensive measure.

The REPL still uses runtime reflection, so will pay a little
performance tax.

Benchmark:

```
avg shortest 10 times 744ms  # before
avg shortest 10 times 675ms  # after
```

[1] https://wikis.oracle.com/display/HotSpotInternals/PerformanceTechniques

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski 

/cc @xeno-by @Ichoran

**Comment by som-snytt** [comment]
Or "class hierarchy analysis" at https://wiki.openjdk.java.net/display/HotSpot/PerformanceTechniques

So a plugin can have secondary effects that are not signalled by, "oops, I crashed the compiler."

**Comment by Ichoran** [comment]
Sounds good in principle; I didn't check the implementation.  For what it's worth, SynchronizedXxx and various other things are being deprecated, which may also help for 2.12.

**Comment by soc** [comment]
@retronym What happens when Manifests go away for good?

**Comment by retronym** [comment]
@Ichoran I was talking about `SynchronizedSymbol` et al under scala-reflect, not the similarly named collections traits. They share the same weaknesses, mind you.

**Comment by retronym** [comment]
@soc `scala.tools.cmd._` is only peripheral code. We don't really _need_ manifests or type tags there at all in any case.

**Comment by retronym** [comment]
ping @gkossakowski

**Comment by gkossakowski** [comment]
LGTM.

**Pull request merged**
