### PR TITLE
Closes SI-6227

### PR DESCRIPTION
**Pull request by odersky**
I added some general hook where one can add validation code before a name conflict involving at least one implicit symbol is reported. Review by @paulp

### CODE REVIEW

**Comment by xeno-by** [comment]
Have you forgot to commit a check file?

**Comment by odersky** [comment]
PLS REBUILD ALL.
Let's try again.

**Comment by jsuereth** [comment]
OK, now review by @paulp

**Comment by paulp** [comment]
LGTM.

**Pull request merged**
