### PR TITLE
SI-3936 - add test case to show that SI-3936 is already fixed

### PR DESCRIPTION
**Pull request by jannic**
These are exactly the examples given by Lukas Rytz in SI-3936.
They fail with 2.10.1 and compile with 2.10.2 as well as current master.

(And many thanks for fixing this bug and all the other great work the contributors are doing!)

### CODE REVIEW

**Comment by huitseeker** [comment]
[Valid](https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala/12/) w.r.t ScalaIDE PR validation

**Comment by adriaanm** [comment]
Welcome, @jannic! Could you please [sign the cla](typesafe.com/contribute/cla/scala/) -- it only takes a minute.

**Comment by adriaanm** [comment]
LGTM

**Comment by jannic** [comment]
Just signed the CLA. Sorry, I didn't notice that there are two CLAs now (typesafe / scala).

**Comment by adriaanm** [comment]
Thanks, sorry about the overhead!

**Pull request merged**
