### PR TITLE
[11047] Fix regression in {ArrayDeque,Queue,Stack}.sliding

### LINKED ISSUE #11047: Queue and ArrayStack drop underfilled sliding windows (unlike everything else)
```scala
Welcome to Scala 2.13.0-20180731-142616-329c477 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> List(1).sliding(2).size
res0: Int = 1

scala> collection.mutable.Queue(1).sliding(2).size
res1: Int = 0
```

I actually prefer the Queue behavior, but I guess it's too late to change it now without changing the name of the method. (Maybe we can add a new one, `window(size, advance)`, with the "correct" behavior?)

Anyway, `Queue` and `ArrayStack` need to be fixed.  (It's probably ArrayDeque which is wrong, but I don't have it in collections-laws yet.)

### PR DESCRIPTION
**Pull request by joshlemer**
fixes scala/bug#11047

### CODE REVIEW

**Comment by SethTisue** [comment]
needs rebase

**Comment by SethTisue** [comment]
@joshlemer I think scabot is now confused because we had some disk space trouble on Jenkins the other day. rebasing one more time will likely un-wedge it

**Comment by joshlemer** [comment]
@SethTisue rebased

**Pull request merged**
