### PR TITLE
Fixes syntax error in unix runner.

### PR DESCRIPTION
**Pull request by huitseeker**
review by @adriaanm, @jsuereth

### CODE REVIEW

**Comment by huitseeker** [comment]
I'm [stupid](https://github.com/scala/scala/pull/3608) >_<.

**Comment by adriaanm** [comment]
Weird, the one-line expression worked when I tried it on bash.

**Comment by adriaanm** [comment]
My bad, in any case -- that code was mine. I just verified it doesn't work without the `;`, but why do you need two?

**Comment by huitseeker** [comment]
@adriaanm It's the [spec'ed](https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html#index-case) terminator for `case`-s

**Comment by adriaanm** [comment]
Thanks. We clearly need bash validation :)

**Pull request merged**
