### PR TITLE
SI-874 JSR-223 compliance for the interpreter

### PR DESCRIPTION
**Pull request by rjolly**

### CODE REVIEW

**Comment by JamesIry** [comment]
@adriaanm you took the review of the previous incarnation, wanna continue here?

**Comment by adriaanm** [comment]
Sorry I didn't think of this before, but #2226 has made me painfully aware of the cost of adding new things to the compiler. I know it's small, but I'd prefer jarlister to be a separate project. We can't afford to grow our compiler codebase. On the bright side, moving it out frees it from the compiler's release cycle.

So, the first and last commit LGTM, but the middle two should be factored out.

**Comment by paulp** [comment]
Perhaps relevantly, I had intended my next move after #2226 (née #2208) would be to do the same for the repl.

**Comment by adriaanm** [comment]
This won't merge cleanly anymore, so I rebased it: #2238.

**Pull request closed without merging**
