### PR TITLE
Bump versions after release of Scala 2.11.0-RC4

### PR DESCRIPTION
**Pull request by retronym**
Based on:

   https://scala-webapps.epfl.ch/jenkins/view/scala-release-2.11.x/job/scala-release-2.11.x/52/artifact/scala/versions.properties

With a manual edit of the new property, scala.full.version, which
was not written out by `ant -Dupdate.versions`. That has since
been remedied.

Review by @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
Review by @adriaanm or @gkossakowski

**Comment by gkossakowski** [comment]
LGTM

**Pull request merged**
