### PR TITLE
SI-8911  scala.collection.convert.Wrappers$MapWrapper not serializable

### PR DESCRIPTION
**Pull request by Ichoran**
`with Serializable` added to MapWrapper and SetWrapper.

Test verifies that serialziation works in the simplest case.

### CODE REVIEW

**Comment by Ichoran** [comment]
@adriaanm - As expected, introducing serialization and keeping binary compatibility conflict.  Which one wins?

**Comment by adriaanm** [comment]
I'll have to think about this some more, but can existing code fail with a LinkageError because of this change? I can't think of a way, but sadly that's not a good proof.

**Comment by Ichoran** [comment]
@adriaanm - I'd think this would do it.

```
def foo(s: Serializable): Serializable = s
foo(Set(1).asJava)
```

The cast check won't work when you write that under 2.11.5 and then try to run it on a 2.11.4 library.

**Comment by adriaanm** [comment]
Ah yes, of course -- well, I think this means we need to wait until 2.12.

**Pull request closed without merging**
