### PR TITLE
Bug fix ! , if $color_opts is unset partest script does not work.

### PR DESCRIPTION
**Pull request by ScrapCodes**
Minor fix! to partest script.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @som-snytt, please.

**Comment by som-snytt** [comment]
Maybe import the warning from the scala runner,

```
# note that variables which may intentionally be empty must not
# be quoted: otherwise an empty string will appear as a command line
# argument, and java will think that is the program to run.
```

I assume that the #comment is due to paulp, who has ranted at length and with just cause.  Which is why this script bug is especially poignant.

**Comment by ScrapCodes** [comment]
I think I agree, adding that warning should be for good.

**Comment by ScrapCodes** [comment]
Failure has something to do with jenkins setup (may be)

sbt.ResolveException: unresolved dependency: org.scalacheck#scalacheck_2.11.0-862daae-SNAPSHOT;1.10.1: not found

**Comment by adriaanm** [comment]
Sorry about the noise, @ScrapCodes and thanks for the fix!

**Pull request merged**
