### PR TITLE
Merge 2.11.x to 2.12.x [ci:last-only]

### PR DESCRIPTION
**Pull request by retronym**
Don't merge this until #4956 is merged, as I've included
its commit in here.

```
% git co -b topic/merge-2.11.x-to-2.12.x-20160210
Switched to a new branch 'topic/merge-2.11.x-to-2.12.x-20160210'

% export MB=$(git merge-base head 2.11.x)

% transcript git log --oneline --graph $MB..2.11.x
https://gist.github.com/35e2008cd4b43c702ae0

% git merge 2.11.x
Auto-merging test/junit/scala/collection/IteratorTest.scala
Auto-merging src/scaladoc/scala/tools/nsc/doc/html/page/Template.scala
Auto-merging src/library/scala/collection/Iterator.scala
CONFLICT (content): Merge conflict in src/library/scala/collection/Iterator.scala
Auto-merging src/intellij/scala.ipr.SAMPLE
Auto-merging doc/License.rtf
Auto-merging doc/LICENSE.md
Auto-merging build.xml
Auto-merging build.sbt
Automatic merge failed; fix conflicts and then commit the result.

% git add .

% git commit
[topic/merge-2.11.x-to-2.12.x-20160210 fca51b2] Merge branch '2.11.x' into topic/merge-2.11.x-to-2.12.x-20160210


% git merge e134051
```

### CODE REVIEW

**Comment by retronym** [comment]
Review by @SethTisue

**Comment by retronym** [comment]
Found a mistake in #4956, will reopen soon.

**Comment by SethTisue** [comment]
LGTM

**Pull request merged**
