### PR TITLE
Always build scala-swing in java7 branch.

### PR DESCRIPTION
**Pull request by gkossakowski**
The 6dd90d349da6471c0a105c584798979f136d7d55 commit introduced a way
to skip building swing in case one is not using Java 6 (e.g. using
Java 7). That change was meant to make it easier to work with master
no matter if one is using Java 6 or Java 7 because for everything
apart from swing it doesn't matter.

However, that change propagated to java7 branch which exists only to
deal with Swing problems and is meant to be used with Java 7 only.
In this branch we should get rid of conditional building of Swing and
build all the time.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @jsuereth or @paulp 

The patch is easy to understand if you read the commit message. This fixes [java7 nightly builds](https://scala-webapps.epfl.ch/jenkins/job/scala-nightly-auxjvm/jdk=jdk7,label=auxjvm/) as verified locally.

**Comment by gkossakowski** [comment]
@jsuereth @paulp those failures can be ignored because PR validator does not handle java7 branch properly.

**Comment by jsuereth** [comment]
HA, so in this branch we _SHOULDN'T_ build if java6?  In any case, LGTM.  Wish we could do something better here...

**Comment by gkossakowski** [comment]
@jsuereth yes, that's correct but this is a separate issue and not very important one. If somebody checks out java7 it should be aware of the fact that it's meant to be build with Java 7.

**Pull request merged**
