### PR TITLE
SI-7402 List extends Serializable

### PR DESCRIPTION
**Pull request by soc**
While we are all aware of the issues around Serialization,
I think in this case it is perfectly sound and safe to make
List serializable:
- List is not an interface, it is the base type of an ADT.
  Common behavior of its members should be reflected in the base type.
- List is sealed, there is no chance of an user providing a new
  non-serializable subtype of List.

### CODE REVIEW

**Comment by soc** [comment]
I targeted this at 2.10.x because moving an interface to a super-type is binary compatible.
I'll ask for a reviewer as soon as it has been built and tested successfully on Jenkins (I'm having issues building Scala on 2.10.x right now).

**Comment by soc** [comment]
I'll fix the test failures as soon as I get past scalap again ...

**Comment by paulp** [comment]
LGTM, I agree.

**Comment by soc** [comment]
Can someone comment whether 

```
test.bc:
     [echo] Checking backward binary compatibility for scala-library (against 2.10.0)
     [mima] Found 0 binary incompatibiities (2 were filtered out)
     [mima] =====================================================
     [mima] Generated filter config definition
     [mima] ==================================
     [mima] 
     [mima]     filter {
     [mima]         problems=[]
     [mima]     }
     [echo] Checking forward binary compatibility for scala-library (against 2.10.0)
     [mima] Found 2 binary incompatibiities (3 were filtered out)
     [mima] =====================================================
     [mima]  * the type hierarchy of class scala.collection.immutable.List has changed
     [mima]    in new version. Missing types {java.io.Serializable}
     [mima]  * the type hierarchy of object scala.collection.immutable.List has changed
     [mima]    in new version. Missing types {scala.Serializable,java.io.Serializable}
     [mima] Generated filter config definition
     [mima] ==================================
     [mima]     filter {
     [mima]         problems=[
     [mima]             {
     [mima]                 matchName="scala.collection.immutable.List"
     [mima]                 problemName=MissingTypesProblem
     [mima]             },
     [mima]             {
     [mima]                 matchName="scala.collection.immutable.List$"
     [mima]                 problemName=MissingTypesProblem
     [mima]             }
     [mima]         ]
     [mima]     }
```

is acceptable or if the PR should be re-targeted against 2.11?

**Comment by retronym** [comment]
2.11.

Otherwise, one could compile this against 2.10.1 `def foo(s: Serializable) = (); foo(Nil)`, which will fail when run with the 2.10.0 standard library.

**Comment by soc** [comment]
Well, that would actually work, only `foo(List())` would fail.
I'll retarget against trunk.

**Comment by soc** [comment]
Ooops, looks like retargeting an existing PR does not work.

**Comment by soc** [comment]
New PR is https://github.com/scala/scala/pull/2441

**Pull request closed without merging**
