### PR TITLE
New Random Boolean

### PR DESCRIPTION
**Pull request by kclick91**
This additional Boolean allows for one value to have n times the probability of happening. Tested using the SBT shell in Intellij.

### CODE REVIEW

**Comment by sjrd** [comment]
Hello @kclick91, and thanks for your suggestion.

I'm not a maintainer of this repo, but I don't think this should be part of the standard library. It looks like a specific use case. If we put this one in, what's the rationale for *not* having many other combinations, such as a random Int with specific probabilities for each possible value? I don't see a rationale why this one is particularly important.

Also, I think your implementation is not correct. I'm not a probability expert, but I think your code is equivalent to always throwing `n+1` coins, and return `b` iff at least one of them is `b` (you are simply avoiding *actually* throwing more coins once you know the result). In other words, you return `!b` iff all of `n+1` random booleans are `!b`. But the probability of that happening is not 1/(n+1), it is 1 / (2^(n+1)).

An obviously correct and efficient solution is `(nextInt(n+1) != 0) == b`. It's also very short, so you could easily use that in your use case without having to put it in a library.

**Comment by kclick91** [comment]
Thanks for the feedback. The implementation would work if I made count start at 2, now that I think about it. The thinking is that if heads gets two throws to one then the final outcome of heads is twice as likely. It takes two tails opposed to one head. As for the rationale, why even have nextBoolean if you could have (nextInt(2) != 0) = b)? I’m trying to stick with Boolean. I think a use case that that takes into consideration “what are the odds of it being true or not true?” should have not have to be rewritten every time in the same way the use case of putting a minimum and a maximum to random numbers should be rewritten. Again, thanks for looking at my pull request.

**Comment by kclick91** [comment]
Also,nextBoolean is practical to have the values in parameters as opposed to ints.

**Comment by sjrd** [comment]
> The implementation would work if I made count start at 2, now that I think about it. The thinking is that if heads gets two throws to one then the final outcome of heads is twice as likely. It takes two tails opposed to one head.

I'm sorry, but that's not how probabilities work. By changing `count` to start at 2, all you've done is reduce the number of coin flips to n-1 instead of n+1. Hence the probability of returning `!b` is now `1 / (2^(n-1))` (instead of `1 / (2^(n+1))`), which is still not equal to the `1 / (n+1)` that you want.

> I think a use case that that takes into consideration “what are the odds of it being true or not true?” should have not have to be rewritten every time in the same way the use case of putting a minimum and a maximum to random numbers should be rewritten.

Most standard libraries will provide you with uniform distributions, which you can then use as building blocks to construct non-uniform ones in your application. Non-uniform distributions like yours are typically not provided by standard libraries (they can be provided by libraries dedicated to probability and statistics, but not standard libs).

(The exception here is `nextGaussian()`, which produces a normal distribution rather than uniform. AFAIK, the only reason we have it here is because it is also provided by `java.util.Random`.)

**Comment by kclick91** [comment]
!b does not count until the last time. So the possibilities for n = 3 are (!b and !b and !b, b the first time, b the second time, b the third time). So b has three times the possibility. I personally think this could be useful in the standard library and not in a separate package but ok. Thanks for looking though. You can close it if you want. Maybe I will work on my own library and add it.

**Pull request closed without merging**
