### PR TITLE
Convert Java throws clauses to @throws annotations

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
This is slightly WIP, as I'm looking for the best way to test this. Any suggestions?

**Comment by soc** [comment]
Maybe our testing expert @som-snytt has some advice? :-D

**Comment by adriaanm** [comment]
Feel free to use this PR for your WIP -- we'd like to open up a dedicated playground for this eventually.

**Comment by adriaanm** [comment]
Maybe you can use https://github.com/scala/scala-partest/blob/master/src/main/scala/scala/tools/partest/CompilerTest.scala?

**Comment by som-snytt** [comment]
I was thinking a macro that verifies the java method has the annotation.  Given foo.java and bar.scala, partest compiles both, then javac, then scala only.  The first round only is relevant.  Maybe the only way to know if you've run yet is to output a tmp file?

**Comment by gkossakowski** [comment]
I'll be offline until January 7th. If a review is needed before that time, please reassign. Marry Christmas and Happy New Year! :christmas_tree: :gift: :fireworks:

**Comment by retronym** [comment]
I'm going to close this one for now (the PR queue has grown a little large.) Feel free to reopen when you're back working on this and have any more questions!

**Pull request closed without merging**
