### PR TITLE
Backport of the 2.10 continuations plugin to 2.9

### PR DESCRIPTION
**Pull request by phaller**

### CODE REVIEW

**Comment by adriaanm** [comment]
could you please assign a reviewer as per https://github.com/scala/scala/wiki/Pull-Request-Policy

**Comment by phaller** [comment]
review by @lrytz

**Comment by lrytz** [comment]
ok, well, i cannot deeply review this change, that would have to be @TiarkRompf. I checked for typos and obvious mistakes, in that sense it lgtm.

**Comment by TiarkRompf** [comment]
what was the reason for disabling the test case infer0?

**Pull request merged**
