### PR TITLE
More retrofit of doc model factory.

### PR DESCRIPTION
**Pull request by vigdorchik**
Review by @VladUreche.

### CODE REVIEW

**Comment by VladUreche** [comment]
LGTM, thanks Eugene for cleaning up my ugly code!

**Comment by gkossakowski** [comment]
@VladUreche: @vigdorchik pushed a new commit after you gave LGTM. We need review once again. Thanks.

**Comment by VladUreche** [comment]
LGTM again, thanks Eugene!

**Comment by VladUreche** [comment]
PLS REBUILD ALL

**Pull request merged**
