### PR TITLE
Make comment consistent with code

### PR DESCRIPTION
**Pull request by ghost**
review by @phaller

### CODE REVIEW

**Comment by ghost** [comment]
I did sign the CLA

**Comment by som-snytt** [comment]
The Scala team, when they do comment, comment so literately, that they set a high bar.

The inconsistency was introduced by the paulp reduction c26a8db067e4f04ef959bb9a8402fa3e931c3cd7

The other plausible amendment would have been, "printing and, formerly, reading".

**Comment by ghost** [comment]
@som-snytt , thanks for link.

~~I saw that  `read*` functions doesn't mark as deprecated at [API documentation](https://github.com/scala/scala/blob/2.12.x/src/library/scala/Predef.scala#L30).~~

I was wrong. All `read*` functions marked as deprecated later.

**Comment by phaller** [comment]
LGTM. Thanks.

**Pull request merged**
