### PR TITLE
unspecialcase unicode escapes [WIP]

### PR DESCRIPTION
**Pull request by martijnhoekstra**
Explore removing the special status of unicode escapes.

In this PR, unicode escapes are treated like any other escape, except

* In triple quoted strings, unicode escapes are expanded, and a deprecation warning is issued
* In raw interpolations unicode escapes are expanded, and a deprecation warning is issued

### CODE REVIEW

**Comment by martijnhoekstra** [comment]
If CI is green, I'd like to request a community build to see what the fallout of such a change is, if any.

**Comment by martijnhoekstra** [comment]
Fixes https://github.com/scala/bug/issues/3220

**Comment by martijnhoekstra** [comment]
I would like to see community build for this PR, just to be sure, before I start polishing things up (right now there is a bunch of repeated code that needs cleaning up)

 But 2.13.x community build is AFAIK not really that far along. Is there an issue for that that I can watch?

**Comment by som-snytt** [comment]
Why isn't the change just dependent on `-Xno-uescape`? Or, since the point is to default that to true, you could also rename it something sane like, `-Xunicode-escapes`.

It's not obvious to me that the escape is great for interpolation.

**Comment by lrytz** [comment]
The 2.13 community build is currently not doing much because most projects don't compile yet for 2.13 (new collections, https://github.com/scala/community-builds/issues/710). You could however prepare a PR against 2.12.x with the change, then we can run the 2.12 community build.

**Comment by martijnhoekstra** [comment]
@som-snytt I knew `-Xno-uescape` existed in the back of my mind, but it escaped my attention. I'll look further in to that. That said, at least for now, I remain convinced that handling unicode escapes differently from other escapes, and special-casing that different handling for string and char literals, interpolations and comments brings a lot more complexity than justified. I may have to justify my position on that further.

**Comment by martijnhoekstra** [comment]
@lrytz porting to 2.12 for a community build sounds like a good idea. A different dummy PR for that is probably going to be easier than re-targeting this PR, and then re-targeting it back. Does that strike you as a reasonable course of action?

**Comment by lrytz** [comment]
Yes!

**Comment by adriaanm** [comment]
Unscheduling from M5 since this is WIP.

**Comment by SethTisue** [comment]
@martijnhoekstra interested in carrying on with this...?

**Comment by martijnhoekstra** [comment]
@SethTisue yes, once we can get a sizable community build going for 2.13. Some things could break, and if I carry on with this, I'd need to have a robust migration story.

Not sure whether this could realistically be targeted for a minor release, so this might have to go for 2.14 or 3

**Comment by SethTisue** [comment]
closing for inactivity, can be revived & reopened later.

the 2.13 community build currently only has about ~60 (out of ~190) projects, it'll probably won't be much larger until around the time RC1 comes out

**Comment by SethTisue** [comment]
I assume this will also resolve https://github.com/scala/bug/issues/10873

**Comment by SethTisue** [comment]
I put scala/bug#3220 on the RC1 milestone, to help us not forget

**Pull request closed without merging**
