### PR TITLE
makes Iterable.scan and IterableOnce.fold deprecated.

### PR DESCRIPTION
**Pull request by Prithvirajbilla**
Fixes scala/bug#10962

### CODE REVIEW

**Comment by julienrf** [comment]
Thanks!

**Comment by SethTisue** [comment]
congratulations on your first scala/scala PR!

**Comment by Prithvirajbilla** [comment]
Thank you!

**Comment by SethTisue** [comment]
well, after a lot of discussion (mostly on https://github.com/scala/bug/issues/11382), this ended up being reverted by #7719. but we got somewhere, the discussion was valuable.

**Pull request merged**
