### PR TITLE
SI-6289 Partest in technicolor and showing javac errors

### PR DESCRIPTION
**Pull request by som-snytt**
Paulptest includes color and simplified test scarfing.

The transcript feature handles errors in staged compilation.

This is work-in-progress, merged from paulp/partest-sprint, nearly done.  It touches build.xml, so more tweaking after the ant build refactor.

### CODE REVIEW

**Comment by paulp** [comment]
Close! At a glance it looks like you're missing the partest changes since it sprinted off into the woods, especially 1dd88d9291 .

**Comment by khernyo** [comment]
@som-snytt, take a look at my commits here: https://github.com/khernyo/scala/tree/unstable/topic/partest-sprint-master
At least some of the failing tests are fixed if not all. I know neg/t6446-show-phases.scala is fixed, but I also know that I won't have time to finish it in the near future, so take it if you want.

**Comment by som-snytt** [comment]
@khernyo thanks, interesting to see unsquashed history. That plug-in tweak was mine; I remember thinking last time how divergence and back-porting are a disincentive to touch code.  Or maybe the lesson is: only write code you will enjoy revisiting periodically like an old friend.  And as at those visits, you will marvel privately how he has changed for the worse and that time has not been kind.

**Comment by som-snytt** [comment]
I'll try reopening on the re-pushed branch and see if it shows only my commit.

I wanted to open it again to any available eyes, before it goes stale again.  Some people were drooling for their ascii art in color.  Ascii art?  No, ascii partest!

**Comment by som-snytt** [comment]
OK, nevermind, it shows other commits, presumably due to rebasing, or some other github quirk I don't understand.  I'll reopen clean.

**Pull request closed without merging**
