### PR TITLE
Removing controversial `either` method from Futures API.

### PR DESCRIPTION
**Pull request by jsuereth**
- Removes `either` from Future
- No tests need to change, since this was an untested method.

Review by @phaller

### CODE REVIEW

**Comment by phaller** [comment]
LGTM

**Comment by phaller** [comment]
I also submitted a corresponding update to the futures overview on the doc site (see above)

**Comment by adriaanm** [comment]
I'm fine merging this, but it would be good to know _why_ this is controversial (does it conflict with a method that is added on through implicits?) so that people who might be affected unbeknownst to us at least understand the change.

**Comment by heathermiller** [comment]
This has been long-discussed in this thread:
https://groups.google.com/forum/?fromgroups=#!topic/scala-sips/VRlDgX4yFKE

Here, the consensus was to remove it for now. Later, e.g. in 2.10.1, when some consensus is arrived at regarding naming and semantics of this method, we can add it without breaking binary compatibility.

**Comment by adriaanm** [comment]
Thanks for the link, Heather. Sorry I missed that discussion.

**Comment by phaller** [comment]
Great. Thanks, Heather and Adriaan.

**Pull request merged**
