### PR TITLE
SI-7605 Deprecate procedure syntax

### PR DESCRIPTION
**Pull request by soc**
This commit covers three cases:
- constructor definitions      (def this {...})
- concrete method definitions  (def foo {...})
- abstract method declarations (def foo)

The deprecation is currently hidden behind -Xfuture pending IDE support
for migrating users from procedures to methods.

### CODE REVIEW

**Comment by soc** [comment]
Review by @odersky / @jsuereth, please.

**Comment by JamesIry** [comment]
Would it make sense to remove the use of procedure syntax in the compiler and library in the same PR (separate commit) or is the job too big for one pass?

**Comment by soc** [comment]
@JamesIry My plan was to first do the minimal thing to get the warning so that I can start looking into IDE support. 
With IDE support working, I would have migrated our code. In some sense, it's eating our own dog food. If the IDE handles all migration cases from the standard library fine, I'd be optimistic that it is ready for prime-time.

So, yes, I could do it now manually, but I'd prefer using the IDE to verify that things work as expected.

**Comment by JamesIry** [comment]
LGTM, but would like some comment from the reviewers or @adriaanm

**Comment by adriaanm** [comment]
LGTM2 -- thanks, Simon!

**Comment by adriaanm** [comment]
In this area, we should also deprecate implicit definitions without return type. They cause much more confusion (and supposed type checker slowdown) than it's worth (not to mention binary/behaviorally incompatible changes due to changes in type inference...)

**Comment by soc** [comment]
@adriaanm Is this good to go or was your comment about adding a deprecation for implicit defs targeted at this commit?

**Comment by adriaanm** [comment]
this is good to go, just meant to say "while you're at it -- here's some more stuff I think we should deprecate"

**Comment by adriaanm** [comment]
Thanks!

**Pull request merged**
