### PR TITLE
MethodSymbol.params => MethodSymbol.paramss

### PR DESCRIPTION
**Pull request by xeno-by**
This matter was discussed at scala-internals:
http://groups.google.com/group/scala-internals/browse_thread/thread/6414d200cf31c357

And I am convinced with Paul's argument: consistency of the convention
is very important.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @paulp @odersky @jsuereth @gkossakowski

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by soc** [comment]
Imho consistency _and_ a good name would be preferable.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@soc What name would you propose?

**Comment by xeno-by** [comment]
For the record, the convention is not that ubiquitous in the API. We only have `MethodSymbol.paramss` and `DefDef.vparamss` to worry about.

**Comment by paulp** [comment]
paramss IS a good name.  So are xss and xs in local context.  Every parameter name doesn't have to be war and peace.

**Comment by paulp** [comment]
LGTM (and I already ran into this again, let's merge.)

**Comment by soc** [comment]
@xeno-by I'd say that `parameterLists`  (Martin also proposed that on the mailing list) or `paramLists` are good options. We don't do this "you have to know it and then it is obvious" stuff in the rest of the API, so why would we want it for `paramss`?

**Comment by paulp** [comment]
" We don't do this "you have to know it and then it is obvious" stuff in the rest of the API, so why would we want it for paramss?"

Well, I wish we would.  I am horrified at how all my code has doubled in size trying to use the reflection api rather than working within the compiler.  Some things which represent negative improvement:

```
tpe => typeSignature
typeArgs => typeArguments
substituteSymbols, substituteTypes, ...
asType, asMethod, ...
```

I have to use this stuff all day long. It is more important it be good to use than that it be "easy to learn", and I don't think it's any easier to learn anyway.  Consistency and conceptual integrity are what make something easy to learn.  And there is plenty of work to do there.  Stop trying to verbosify the names, because it won't help with the real work, and it does hurt by disinclining me to do it.

**Comment by som-snytt** [comment]
A closed PR is the least annoying place for me to mention:

"paramses" by analogy or folk etymology to parentheses, rhymes with Ramses.

**Pull request merged**
