### PR TITLE
SI-4714 Initialize history while initializing the REPL's reader

### PR DESCRIPTION
**Pull request by JamesIry**
It was possible to get a command into the REPL before the history
recording object was set and so the command would be lost in the sands
of time. This fix just moves the initialization of the history object
into the JLineReader constructor, out of the post-init hook.

@paulp how is this going to break things? Also, I don't have a clue how to automate the testing of this.

### CODE REVIEW

**Comment by paulp** [comment]
Thank you for the assistance. It will not break things that I am aware of. And this is not the place to start testing our frankensteinian jline. If you want to put that effort into something, I have a branch with jline 2.10 replacing our custom jline. It is 100% done except for windows fiddling (do not know how much if any is required, but it has stymied basically every major jline fix I've ever tried.)

**Comment by JamesIry** [comment]
Is that an LGTM?

**Comment by paulp** [comment]
IT SURE IS

**Comment by JamesIry** [comment]
STOP YELLING AT ME OR I'M GOING TO CRY

**Comment by paulp** [comment]
MY CAPS LOCK IS BROKEN I'M SO SORRY

**Pull request merged**
