### PR TITLE
SI-8554 Two-arg remove throws exception on large count

### PR DESCRIPTION
**Pull request by Ichoran**
SI-8554  Two-arg remove throws exception on large count

Made ArrayBuffer and BufferLike have same behavior, which is also consistent with single-arg remove.

### CODE REVIEW

**Comment by lrytz** [comment]
PLS REBUILD/pr-scala@0b32028

**Comment by adriaanm** [comment]
Review by @phaller

**Comment by lrytz** [comment]
Similarly to #3801, this patch changes the behaviour of an existing method. Can we be reasonably sure it is OK to just go ahead with that change? It may introduce crashes on user code.

Also, unit tests would be good to have some.

**Comment by gkossakowski** [comment]
@Ichoran: ping. What do you think about @lrytz's feedback?

**Comment by Ichoran** [comment]
@gkossakowski - I think @lrytz has a valid concern.  We should make these methods agree with each other, but maybe the way is to ignore non-positive counts instead of throwing an exception.  (That is, be more permissive instead of more restrictive.)  On the other hand, silently doing something nonsensical is often not good for correctness.  Opinions?  Or shall we just leave this well enough alone until 2.12?

**Comment by lrytz** [comment]
For the question of trowing vs being permissive, I personally prefer the defensive version implemented in this PR.

I think it should go to 2.12 though.

**Comment by gkossakowski** [comment]
Agreed. Let's target 2.12.x @Ichoran, can you retarget your PR?

**Comment by adriaanm** [comment]
Closing this PR as retargeting requires resubmission.

**Pull request closed without merging**
