### PR TITLE
Treat name in getResourceAsStream as resource path

### PR DESCRIPTION
**Pull request by Atry**
The parameter for getResourceAsStream is not a class name. It's a resource path!

### CODE REVIEW

**Comment by jsuereth** [comment]
We need a reviewer for this one, and possibly a test.  Tagging @paulp since I'm not exactly sure when it comes to AbstractFile what areas are hard to touch.

**Comment by paulp** [comment]
It looks right to me.

**Comment by adriaanm** [comment]
@Atry, thank you for your contribution! Have you signed the [CLA](http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf)?

**Comment by Atry** [comment]
Not yet. How can I signed it?

**Comment by adriaanm** [comment]
please email a pdf of the signed CLA (http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf) to danielle.chamberlain@epfl.ch

**Comment by adriaanm** [comment]
hi, have you had a chance to sign the cla? thanks!

**Comment by Atry** [comment]
I have just signed th CLA and emailed to danielle.chamberlain@epfl.ch

**Comment by paulp** [comment]
Thanks!

**Pull request merged**
