### PR TITLE
SI-7971 Handle static field initializers correctly

### PR DESCRIPTION
**Pull request by soc**
Before this fix, static fields where erroneuosly treated like instance
fields and the initialization was moved into the constructor.

With this fix, the static initializer statements go into the static
initializer of the class (called “<STATIC> def init” in Scala,
<clinit> in Java). The statements are added to an existing
static initializer method or, if no such method exists, a new static
initializer method is created and added to the class.

### CODE REVIEW

**Comment by soc** [comment]
The reason why I created the PR as-is is because of the code duplication which I want to fix. `findStaticCtor` and `addStaticInits` is basically copied from the private ones in `Cleanup`. I'd love to hear your opinion @JamesIry what's the best place to move this functionality to.

@xeno-by Do the changes fully address your issues raised?

**Comment by soc** [comment]
Review by @JamesIry, please.

**Comment by xeno-by** [comment]
@soc The comment looks good apart from a typo :-P

**Comment by soc** [comment]
This doesn't look like I'm the culprit:

`-Exception in thread "Reflector-456" scala.reflect.internal.FatalError: unsupported completer: [A <: <?>, +B <: <?>]scala.collection.immutable.Map[A,B] of class class scala.reflect.internal.Types$PolyType for symbol scala.Predef.Map`

**Comment by soc** [comment]
PLS REBUILD/pr-scala@cb75f8f

**Comment by soc** [comment]
Arrrgh, erronouesly, why do you make me writing things errenously?! This is madness!

**Comment by JamesIry** [comment]
Good catch. Needs a test, though. A simple bytecode based one would probably be sufficient. I'll have to think about the best place for the functionality to live.

**Comment by soc** [comment]
@JamesIry Is there a way to get a STATIC flag set without the help of macro paradise?

**Comment by soc** [comment]
@JamesIry Any ideas on about the right place to consolidate the duplicated functionality?

**Comment by adriaanm** [comment]
I'd suggest: factor out everything related to statics into a class `StaticsTransformer` nested in `scala.tools.nsc.transform.Statics`, and inherit that in `CleanUpTransformer` and `TemplateTransformer`.

**Comment by soc** [comment]
@adriaanm Thanks, I'll do that!

**Comment by soc** [comment]
@adriaanm I'm a bit confused, maybe I'm missing something... I added `extends Statics` to the outer classes and `extends StaticsTransfomer` to the transformer classes of `Constructors` and `CleanUp`. It works fine for `CleanUp` but it fails for `Constructors` with:

```
/home/soc/Entwicklung/scala/src/compiler/scala/tools/nsc/transform/Constructors.scala:461: error: not found: type StaticsTransformer
    extends StaticsTransformer
            ^
/home/soc/Entwicklung/scala/src/compiler/scala/tools/nsc/transform/Constructors.scala:727: error: not found: value addStaticInits
    val transformed: Template = addStaticInits(templateWithoutOmittables, classInitStatBuf, localTyper)
                                ^
two errors found
```

Maybe you see the issue immediately?

**Comment by soc** [comment]
Wow, what a stupid typo! Nevermind, thanks!

**Comment by soc** [comment]
PLS REBUILD/pr-scala@f7f80e8

**Comment by adriaanm** [comment]
LGTM. Excellent work!

**Pull request merged**
