### PR TITLE
SI-7582 Only inline accessible calls to package-private Java code

### PR DESCRIPTION
**Pull request by retronym**
The inliner was using `isPrivate` / `isProtected` to determine access.
The fallthrough considered things to be (bytecode) public. This is okay
in practice for Scala code, which never emits package private code.

This commit turns the logic around to use `!isPublic && !isProtected` to
equate to "don't inline". This alone is enough to pass `run/t7582`.

Secondly, we must check accessibility of the called symbol _and_ its
owner.

Review by @JamesIry

The change to `ClassFileParser` was reviewed in person by @odersky

### CODE REVIEW

**Comment by retronym** [comment]
@JamesIry I've got this to pass the build now.

**Comment by adriaanm** [comment]
ping @JamesIry

**Comment by soc** [comment]
LGTM

**Comment by JamesIry** [comment]
LGTM

**Pull request merged**
