### PR TITLE
SI-7264 Initialize owner when searching for companion.

### PR DESCRIPTION
**Pull request by retronym**
From ClassSymbol:

```
protected final def companionModule0: Symbol =
  flatOwnerInfo.decl(name.toTermName).suchThat(sym => sym.isModuleNotMethod && (sym isCoDefinedWith this))

protected final def flatOwnerInfo: Type = {
  if (needsFlatClasses)
    info
  owner.rawInfo
}
```

Note the call to `rawInfo`; in the enclosed test case, that gives
us back an uninitialized type for the module class of `Foo`, and
consequently we don't find the companion for `Foo.Values`.

This commit forces the initialization of the owning symbol if it
was compiled in a prior run.

In addition, it adds a special case to `Run#compiles` for early
initialized symbols, which start out in life with the wrong owner.
As best as I can see, that complexity stems from allowing early
initialized members _without_ return types to be used as value arguments
to the super call, which in turn is needed to infer parent type arguments.
The situation is described a little further in existing comments of
`typedPrimaryConstrBody`.

This bug is essentially another case of SI-6976. See the comments in pull
request of that patch (https://github.com/scala/scala/pull/1910) for
commit archaeology that shows why we're reluctant to force the owner
info more broadly than is done in this commit.

Review by @paulp / @lrytz

This PR is more a suggestion, rather than a final proposal. I lack confidence that the cycles we're afraid of are tested, and the intuition to craft said tests retrospectively.

### CODE REVIEW

**Comment by retronym** [comment]
Hey, we did have a test. Well, sort of.

t6666.scala shows that `currentRun.compiles(<<early>>)` for the code below always returns `false`. `early` is owned by the enclosing package; and there is no entry in `Global#symSource` for it.

``` scala
object O extends {
  val early = {
    object Nested
    ()    
  }
} with AnyRef
```

**Comment by retronym** [comment]
I've hacked together a fix for `compiles(earlySym)`. Before I try to clean it up, do you guys know whether that ownership chain is correct?

**Comment by retronym** [comment]
The test failure and comments above relate to to 55b5c973e, in which I used `!currentRun.compiles(sym)` to predicate forcing the owner's info. I have since pushed a new version that checks the owner chain in the provided `Context`. We should separately fix the interaction between `Run#compiles` and Early Definitions.

**Comment by paulp** [comment]
Where/how are you seeing early owned by the package? Do you mean "Nested" ?

**Comment by paulp** [comment]
And to elaborate slightly - I can't see how early can correctly be owned by anything other than "O" - and since that is also what I see happening, I sense I am misunderstanding what you're asking.

**Comment by retronym** [comment]
At this juncture:

```
main@1, prio=5, in group 'main', status: 'RUNNING'
      at scala.tools.nsc.typechecker.Namers$class.companionSymbolOf(Namers.scala:1690)
      at scala.tools.nsc.Global$$anon$1.companionSymbolOf(Global.scala:446)
      at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1871)
      at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5294)
      at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
      at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5408)
      at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2911)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$59.apply(Typers.scala:3015)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$59.apply(Typers.scala:3015)
      at scala.collection.immutable.List.loop$1(List.scala:172)
      at scala.collection.immutable.List.mapConserve(List.scala:188)
      at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3015)
      at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2471)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5280)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5280)
      at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:472)
      at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5280)
      at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
      at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5419)
      at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5510)
      at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:831)
      at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1299)
      at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1444)
      at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1453)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:733)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:732)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:732)
      at scala.tools.nsc.typechecker.Namers$Namer$LogTransitions.apply(Namers.scala:1471)
      at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1480)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:732)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:724)
      at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1595)
      at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1603)
      at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1593)
      at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1319)
      at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1455)
      at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4976)
      at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
      at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5408)
      at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2911)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$59.apply(Typers.scala:3015)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$59.apply(Typers.scala:3015)
      at scala.collection.immutable.List.loop$1(List.scala:172)
      at scala.collection.immutable.List.mapConserve(List.scala:188)
      at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3015)
      at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2471)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5280)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5280)
      at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:472)
      at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5280)
      at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
      at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5404)
      at scala.tools.nsc.typechecker.Typers$Typer.typedPrimaryConstrBody(Typers.scala:1649)
      at scala.tools.nsc.typechecker.Typers$Typer.typedParentTypes(Typers.scala:1725)
      at scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:870)
      at scala.tools.nsc.typechecker.Namers$Namer.classSig(Namers.scala:919)
      at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1435)
      at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1453)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:733)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:732)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:732)
      at scala.tools.nsc.typechecker.Namers$Namer$LogTransitions.apply(Namers.scala:1471)
      at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1480)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:732)
      at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:724)
      at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1595)
      at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1603)
      at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1593)
      at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1319)
      at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1455)
      at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4976)
      at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
      at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5408)
      at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2911)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$59.apply(Typers.scala:3015)
      at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$59.apply(Typers.scala:3015)
      at scala.collection.immutable.List.loop$1(List.scala:172)
      at scala.collection.immutable.List.mapConserve(List.scala:188)
      at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3015)
```

I observe:

```
(original, original.owner, original.owner.owner) // (object Nested,value early,package <empty>)
```

**Comment by retronym** [comment]
The symbol is created under the context:

```
Context(t6666.scala) {
   owner       = package <empty>
   tree        = Block:{ val early = { object Nested extends scala.AnyRef { def <init>() = { 
   scope       = 77 decls
   contextMode = AmbiguousErrors ImplicitsEnabled MacrosEnabled ReportErrors
   outer.owner = package <empty>
}
```

That context is `cscope` here:

``` scala
// typedPrimaryConstrBody
val cscope = context.outer.makeNewScope(ctor, context.outer.owner)
val cbody2 = { // called both during completion AND typing.
  val typer1 = newTyper(cscope)
  // XXX: see about using the class's symbol....
  clazz.unsafeTypeParams foreach (sym => typer1.context.scope.enter(sym))
  typer1.namer.enterValueParams(vparamss map (_.map(_.duplicate)))
  typer1.typed(cbody1)
}

val preSuperVals = treeInfo.preSuperFields(templ.body)
if (preSuperVals.isEmpty && preSuperStats.nonEmpty)
  devWarning("Wanted to zip empty presuper val list with " + preSuperStats)
else
  map2(preSuperStats, preSuperVals)((ldef, gdef) => gdef.tpt setType ldef.symbol.tpe)
```

**Comment by paulp** [comment]
Ah, okay. We should have better command line support for extracting this info. I don't think it's even within the realm of possibility that the correct owner for a val is a package class.

Speaking of better command line support...

maybe

**Comment by retronym** [comment]
It seems to be some half-retained, half-thrown-away typing job that goes down in `typedPrimaryConstructor` during which `early` is owned by the package. Eventually another `early` symbol pops us with the expected owner.

I'll ask around tomorrow. Originally commit: https://github.com/scala/scala/commit/28d40d21#L2R785

You can see things more directly with:

``` scala
scala> class C extends {
     |   private[C] val a = 0
     | } with AnyRef
<console>:8: error: C is not an enclosing class
         private[C] val a = 0
                        ^
```

**Comment by retronym** [comment]
It seems that the complexity might stem from allowing early definitions to have inferred return types and be used as super constructor arguments which factor into type argument inference.

``` scala
scala> class C[A](a: A); object E extends { val a = 0 } with C(a)
defined class C
defined module E

scala> typeOf[E.type].baseType(typeOf[C[_]].typeSymbol)
res2: $r.intp.global.Type = C[Int]
```

``` scala
// if that is required to infer the targs of a super call
// typedParentType calls typedPrimaryConstrBody to do the inferring typecheck
// as a side effect, that typecheck also assigns types to the fields underlying early vals
// however if inference is not required, the typecheck doesn't happen
// and therefore early fields have their type trees not assigned
// here we detect this situation and take preventive measures
if (treeInfo.hasUntypedPreSuperFields(templ.body))
  typedPrimaryConstrBody(templ)(EmptyTree)
```

**Comment by retronym** [comment]
@paulp I've updated this PR again. It now uses `Run#compiles` as it did originally. I've imbued `compiles` with knowledge of these transitory top-level early-initialized symbols. It's a bit of a hack.

Maybe a more principled way forward would be to require type annotations on early-initialized symbols to take some load of the compiler here.

**Comment by paulp** [comment]
It's a hack, but as a documented hack it's still in the top quartile of compiler elegance. I don't have any better ideas. I'm afraid requiring type annotations will cause more trouble than it's worth, especially if something like this will hold.

**Comment by retronym** [comment]
@paulp Can I take your assessment as a willingness to merge?

**Comment by paulp** [comment]
Yep.

**Pull request merged**
