### PR TITLE
Delay deprecating package object inheritance until 2.14

### PR DESCRIPTION
**Pull request by adriaanm**
Ref https://github.com/scala/scala-dev/issues/441

Delay deprecation proposed in #7662 to 2.14.

### CODE REVIEW

**Comment by som-snytt** [comment]
`s/proposed/foisted` to use the term from classical logic.

Sorry a module system based on package objects will have to wait for 2.17.

**Review by eed3si9n — APPROVED** [review]

**Comment by neko-kai** [comment]
@som-snytt
Might as well propose your design instead of being snarky. Maybe it's worth giving up package objects for ;)

**Comment by som-snytt** [comment]
@kaishh it's a follow-up to my comment when I approved the proposal PR.

**Comment by neko-kai** [comment]
@som-snytt 
If you mean the following comment, it's a bit too vague.
> The best part is that it blows the future wide open to re-introduce package objects as a module system.

Scala's objects and package objects already form a very powerful module system, a clarification might help convey what system you envision exactly.

**Comment by som-snytt** [comment]
(I never answered the question what are package objects good for. I always liked the original idea to use them to define API, like exports. I wonder if they could have interacted with Java modules.)

**Pull request merged**
