### PR TITLE
Fix `MatchError` when using `-sourcepath`

### LINKED ISSUE #1304: MatchError in `ApiPhase.processScalaUnit` with `-sourcepath` compiler option
Setup:
  - small sbt project with two source files for classes A and B
  - set the `-sourcepath` compiler flag
  - change source file B
  - touch (save) the source file A without modifications

Zinc's incremental compilation runs the compiler on the changed source file B. For class A, the compiler finds both a classfile and a source file. Because the [source file has a more recent timestamp it creates a SourcefileLoader](https://github.com/scala/scala/blob/v2.13.12/src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala#L190-L192) for symbol A, which invokes `compileLate` and creates a plain `BatchSourceFile`.

The API phase crashes because it expects an `xsbti.VirtualFile`: https://github.com/sbt/zinc/blob/v1.9.5/internal/compiler-bridge/src/main/scala/xsbt/API.scala#L62

I'm encountering this when switching branches in scala/scala.

(edit from Dale: switched A and B in the setup, to match the description below.)

### PR DESCRIPTION
**Pull request by Friendseeker**
Generate `AbstractZincFile` during `-sourcepath` workflow

This PR ports https://github.com/sbt/zinc/pull/1309 to fix https://github.com/sbt/zinc/issues/1304, as discussed in https://github.com/sbt/zinc/issues/1304#issuecomment-1877155832

> So in principle we should still go ahead with your PR to zinc, to make sure a VirtualFile is created when completing a SourceLoader.

### CODE REVIEW

**Comment by Friendseeker** [comment]
@som-snytt Would you like to review the PR? This PR is small so should be light to review.

**Comment by som-snytt** [comment]
I wouldn't mind, but there is a large surface area of "sbt stuff I always say I should learn about". lrytz may get to it before I am up to speed. (I'm actually in the middle of the "sbt-jmh stuff I always say I should learn about" learning curve.)

**Comment by Friendseeker** [comment]
> I wouldn't mind, but there is a large surface area of "sbt stuff I always say I should learn about". lrytz may get to it before I am up to speed. 

Makes sense. It is probably more efficient for lrytz to review the PR as lrytz is the one who initially looked into the issue.

**Comment by Friendseeker** [comment]
lrytz would you like to give this PR a quick look? This PR is small so should be light to review.

**Comment by som-snytt** [comment]
I clicked the review request link, which suggested lrytz. That notifies so you don't have to inline an at-notify (as we always had to do at one time). The unfortunate target of the review request can always decline.

**Review by lrytz — APPROVED** [review]
Thanks!

**Comment by SethTisue** [comment]
I haven't looked it too deeply but it appears that this PR prevents Scala 2.13.16 from working with older zinc versions that don't have `AnalysisCallback3`, as reported by @WojciechMazur: https://contributors.scala-lang.org/t/scala-2-13-16-release-planning/6773/11

Can we ameliorate this somehow before the release of 2.13.16? Like by accessing `AnalysisCallback3` or something like that?

Note that the community build doesn't catch this, because we compile everything with latest sbt.

**Comment by Friendseeker** [comment]
> I haven't looked it too deeply but it appears that this PR prevents Scala 2.13.16 from working with older zinc versions that don't have `AnalysisCallback3`, as reported by @WojciechMazur: https://contributors.scala-lang.org/t/scala-2-13-16-release-planning/6773/11
> 
> Can we ameliorate this somehow before the release of 2.13.16? Like by accessing `AnalysisCallback3` or something like that?
> 
> Note that the community build doesn't catch this, because we compile everything with latest sbt.

Working on it now.

**Pull request merged**
