### PR TITLE
SI-9206 REPL custom bits

### PR DESCRIPTION
**Pull request by som-snytt**
This supersedes #4447 and considers https://github.com/scala/scala/compare/2.11.x...iracic:topic/repl-customization--2nd-try

Introduces `scala.repl.continue` for continuation prompt, `scala.shell.histfile` for history file location, and `scala.repl.welcome` for its first impression, which is also available as a properties file entry, `shell.welcome`.

The welcome banner is turned off by setting it empty.

Review by @adriaanm the gaatkeeper.

### CODE REVIEW

**Comment by adriaanm** [comment]
You shall pass, once the build does!

**Comment by som-snytt** [comment]
It turns out that it's called BC test because it exists to make sure we're stuck in the Stone Age.

I accidentally enabled `prop or alt` which paulp somehow omitted from the trait. Commenting it out challenged my late-night gitfu.

Would also be nice if unit tests ran before BC. Usually BC is incidental and workaroundable, but failing tests are meaningful at least 50% of the time.

I'll work in a coffee break to get back to this today, in lieu of foosball.

**Comment by adriaanm** [comment]
good point regarding the order of tests -- tracked as https://github.com/scala/scala-jenkins-infra/issues/81

**Comment by som-snytt** [comment]
OMG, it passed. Sorry it didn't make 2.11.7. Wink, wink.

**Comment by adriaanm** [comment]
How about 2.11.7-1?

**Comment by som-snytt** [comment]
Is there a 2.11.7-2015-06-23-2050?

**Comment by som-snytt** [comment]
Does Jenkins, diligent though he may be, check that all authors have signed CLA or only the PR submitter?

Does he check whether the signator is just a shell corporation in the Cayman Islands?

**Comment by retronym** [comment]
[Looks like](https://github.com/scala/scabot/blob/ee4dfb64cf1719d630e4fbae606c7126dec4e96e/server/src/main/scala/Actors.scala#L505-L529) it is based on the PR submitter, not the commit author. That code also seems deficient with regards to the KYC principles of the anti-code-laundering regulators.

**Comment by som-snytt** [comment]
hey, I didn't at-sign retronym, but he is one of my favorite Scala dads.

I wonder if he has a dog, because Friday is Take your dog to work day. I wonder if Miles Shapeless is aware of that. He must be.

**Comment by retronym** [comment]
I think in his part of the world, that is statically overridden by the the spaniels' take-your-owner-to-the-rolling-green-hills friday.

**Comment by dragos** [comment]
Looks good as far as I'm concerned.

**Comment by som-snytt** [comment]
I might go retro.

```
$ /media/Software/scala-2.5.1-final/share/scala/bin/scala
This is a Scala shell.
Type in expressions to have them evaluated.
Type :help for more information.
```

**Comment by adriaanm** [comment]
I'd drop articles.

**Comment by SethTisue** [comment]
LGTM. @adriaanm, not sure if your comment is a joke I'm missing, or what.

**Comment by som-snytt** [comment]
```
$ scala
это Скала оболочка.
```

**Comment by adriaanm** [comment]
Yep, silly jokes is my middle name.

**Comment by som-snytt** [comment]
Where others use `grep`, Adriaan uses `grap`.

**Comment by adriaanm** [comment]
(How would a [group nap](http://www.urbandictionary.com/define.php?term=grap) help us find anything? Oh wait, I'm losing my dutch!)

**Comment by iracic** [comment]
I have just tested with scala-2.11.8-d792e35-nightly.tgz.
-Dscala.shell.histfile histfile relocated. OK
-Dscala.shell.welcome welcome customized. OK
-Dscala.shell.prompt PS1 prompt set.OK
-Dshell.repl.info quite verbosity change. OK

Option -Dscala.repl.continue is taken into account but also prepended with two spaces. 
For -Dscala.repl.continue="> " (no leading spaces), it adds 2 spaces indentation
(can't get formatting correctly here, hopefully point is clear)

Thank you for your work on these points. 
Regards, 
Igor

**Comment by som-snytt** [comment]
@iracic the code comment says continue prompt is adjusted for your primary prompt. So the code lines up.

https://github.com/scala/scala/blob/v2.12.0-M3/src/repl/scala/tools/nsc/interpreter/ReplProps.scala#L51

**Comment by iracic** [comment]
Personally I do not see the need for such rule.

**Comment by som-snytt** [comment]
The idea was that the common use case is to set the primary prompt and see aligned output. Dynamic prompts are any length.

I could see not aligning if both prompts are user-supplied. Or a different flag for it. Maybe ask on gitter and create an issue.

**Comment by iracic** [comment]
Thanks again for pushing this stuff forward.

**Comment by som-snytt** [comment]
So Ammonite has the bang from my original edit! No wonder everyone loves Ammonite!

```
Welcome to the Ammonite Scala REPL!
```

**Pull request merged**
