### PR TITLE
SI-8894 dealias when looking at tuple components

### PR DESCRIPTION
**Pull request by adriaanm**
[Shooting from the hip here: did not run test suite.]

Classic bait-and-switch: `isTupleType` dealiases, but `typeArgs` does not.
When deciding with `isTupleType`, process using `tupleComponents`.
Similar for other combos. We should really enforce this using extractors,
and only decouple when performance is actually impacted.

### CODE REVIEW

**Comment by adriaanm** [comment]
Something broke in the IDE tests.

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Thanks, @retronym. As your reward, I nominate you 'Reviewer of the PR'.

**Comment by retronym** [comment]
LGTM. I checked the rest of my offending commit a16a635b647, and its predecessor 3e9e2c65a. I didn't spot other incorrect use of `typeArgs`.

**Comment by milessabin** [comment]
I can confirm that with today's 2.11.3-SNAPSHOT build my original unreduced issue is also fixed. Many thanks for the quick response on this :-)

**Comment by adriaanm** [comment]
Thanks for checking! Glad it's fixed for realz

**Pull request merged**
