### PR TITLE
Fix for SI-6245 with workaround for SI-2296.

### PR DESCRIPTION
**Pull request by namin**
protected/super accessor issue: Don't subvert the creation of the
standard protected accessor with the java interop accessor. For
SI-2296, the compiler emits an error instead of causing an illegal
access error at runtime.

Adapted from e498fac7fdbda3187a2a4fffcdf7fa4f9ddb7ac8.

Conflicts:

```
src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala
```

Review by @jsuereth.

### CODE REVIEW

**Comment by namin** [comment]
PLS REBUILD pr-rangepos

**Comment by namin** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
LGTM - BTW ignore rangepos build failures for 2.9.x

**Comment by gkossakowski** [comment]
Are rangepos tests broken for 2.9.x?

**Comment by jsuereth** [comment]
It's not that they're broken, but that they aren't implemented.  However, the PR bot has no knowledge of this.  We should probably cusotmize the "PR" scripts to detect this and not fail...

**Comment by gkossakowski** [comment]
I see. Ok, merging this one.

**Pull request merged**
