### PR TITLE
Unused warnings: for macros, by default, look for usages in expansion

### LINKED ISSUE #12953: false positive unused warning implicit `Unliftable` instance
## Reproduction steps

Scala version: 2.13.12

`build.sbt`

```scala
scalaVersion := "2.13.12"

libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value

scalacOptions += "-Wunused:privates"
```

`A.scala`

```scala
package example

import scala.reflect.macros.blackbox

case class A(x: Int)

class MyMacro(val c: blackbox.Context) {
  import c.universe._

  def impl(tree: c.Tree): Tree = {
    tree match {
      case q"${a: A}" =>
        reify(()).tree
      case _ =>
        c.abort(c.enclosingPosition, "err")
    }
  }

  private implicit def instance: Unliftable[A] = ???
}
```

## Problem

```
[warn] Unliftable-unused-example-project-path/A.scala:19:24: private method instance in class MyMacro is never used
[warn]   private implicit def instance: Unliftable[A] = ???
[warn]                        ^
[warn] one warning found
```

buf compile error if remove `Unliftable[A]`

```
[error] Unliftable-unused-example-project-path/A.scala:12:12: Can't find MyMacro.this.c.universe.Unliftable[example.A], consider providing it
[error]       case q"${a: A}" =>
[error]            ^
[error] one error found
```

### PR DESCRIPTION
**Pull request by som-snytt**
By default, `-Wunused` can be satisfied by a usage introduced by a macro expansion.

This is the revised behavior under `-Wmacros:default`. Previously, the default setting was `-Wmacros:before`, to lint only before any macros are expanded. The new behavior may reduce the need to suppress warnings.

Previously, `-Wmacros:after` could be used to lint only the expansion, but if the expansion introduces more unused definitions, then those will generate warnings under that mode.

Note that linting the macro expansion will also warn for `-Xlint:missing-interpolator`, since 2.13.14. Macros for test assertions that capture interpolations as regular string literals will warn. For example, if a macro transforms
```
val world = "world"
assert(s"Hello, $world!".contains("Hell"))
```
into
```
assert(s"Hello, $world!".contains("Hell"), "Failed test: " + """s"Hello, $world!".contains("Hell")""")
```

Fixes scala/bug#12953

### CODE REVIEW

**Comment by som-snytt** [comment]
The missing interpolator lint should be in refchecks. The new motivation is that it only warns when the literal is typechecked, not after macro expansion. Since refchecks can check the expandee, it can warn more consistently.

**Review by lrytz — APPROVED** [review]

**Comment by SethTisue** [comment]
@som-snytt (now that we have an approval from Lukas, let's turn to the matter of documentation)

is there migration advice that could be in the PR description? as in, I am a Scala user, what do I do now?

**Comment by som-snytt** [comment]
> what do I do now?

That is what everyone is asking themselves. Let me know the results of the next community build.

**Comment by som-snytt** [comment]
I wonder if this PR ever saw that community build.

I updated the description to include the "missing interpolator" lint seen by some users of assert macros.

**Pull request merged**
