### PR TITLE
fix regression in handling of local `synchronized` methods

### PR DESCRIPTION
**Pull request by SethTisue**
references scala/bug#11331 (the original bug)
references scala/scala#7593 (PR that fixed the bug but also caused
  a regression)

### CODE REVIEW

**Comment by SethTisue** [comment]
@retronym many chefs have stirred this pot, but as the author of #5099 I think you might be best positioned to review this?

**Review by retronym — APPROVED** [review]

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4140/

**Comment by SethTisue** [comment]
`[info] Project better-files----------------: SUCCESS (project rebuilt ok)`

but,

`failed: kafka, playframework`

probably spurious/intermittent. regardless, re-run queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4144/

UPDATE: results are `unexpected FAILED: akka-http; unexpected FAILED: akka-more; unexpected FAILED: sbt`. the sbt is almost certainly intermittent, and I'm seeing the other two also in vanilla 2.12.x

**Comment by SethTisue** [comment]
thanks @rfkm for taking the initiative here — your code change and test cases pointed the way

**Comment by rfkm** [comment]
Oh, I somehow missed this. Thank you for following up it, @SethTisue !

**Pull request merged**
