### PR TITLE
Support def macros for constructors

### PR DESCRIPTION
**Pull request by soc**
Fixes an oversight that lasted from the times of 2.10.0-M3. Back then we
allowed defs to be a macro, but didn't think of constructors. Of course,
primary constructors can't be macros, because a class ought to have at
least one JVM-compatible ctor, but secondary constructors - why not?!

You might ask what's the point of turning constructors into macros.
After all, constructors have to expand into something that calls into
other constructors. Therefore even if one wants to hide a certain
constructor from the user by making that constructor private or protected,
it won't help because a public macro constructor would eventually have
to call that hidden constructor, producing a compilation error.

So we're stuck, right? Not really! Indeed, we can't expand into
a direct call to the hidden ctor, but what we can do is call a companion's
method and companions can see private constructors:

  class C private (x: Int) {
    def this(x: Int) = macro ??? // expands into `C(x)`
  }

  object C {
    def apply(x: Int) = new C(x)
  }

Now, you might point out that the signatures of the hidden ctor
and of the macro ctor are the same. So how do we disambiguate? Easy!
Let's wrap our state in a zero-overhead value class!

  class CState(val x: Int) extends AnyVal

  class C private (x: CState) {
    def this(x: Int) = macro ??? // expands into `C(x)`
  }

  object C {
    def apply(x: Int) = new C(new CState(x))
  }

### CODE REVIEW

**Comment by soc** [comment]
@xeno-by How does this look like?

**Comment by xeno-by** [comment]
Now I see why you had troubles with defining macro constructors when you applied my patch as is. Thanks for rebasing!

**Comment by soc** [comment]
@xeno-by I'm wondering why it seemed to work before ...

Anyway, who would you suggest as a reviewer, @xeno-by?

**Comment by xeno-by** [comment]
Maybe someone changed namers in the meanwhile?

**Comment by xeno-by** [comment]
As a reviewer? Anyone from Typesafe, really.

**Comment by retronym** [comment]
I believe we already reviewed and declined this patch. What has changed?

**Comment by som-snytt** [comment]
The reviewer has to be anyone _not_ from Typesafe.

**Comment by gkossakowski** [comment]
As follow up to @retronym's comment I link to previous PR: #3054.

I just read our discussion again and I have nothing to add.

**Comment by soc** [comment]
@retronym, @gkossakowski I'm aware of the past PR, and I agreed with the original decision back then. Having played with and hacked on virtual classes more deeply, I changed my opinion though:

Yes, the only real use-case is still virtual classes, but the perspective of being able to prototype a fix for the broken/inconsistent behavior of `new` for inner classes as well as probably eliminating a huge source of soundness bugs seems like a good reason to eliminate this inconsistency in macro handling.

**Comment by gkossakowski** [comment]
As said in #3054 we don't feel there's any inconsistency. The contract of `new` is well defined and we don't want to change that. Moreover, we tend to not introduce new features to the language based on a single use case.

@soc you are free to experiment with virtual classes in your own fork. When I was working on Scala+GWT (before I realized it's a dead end) I forked scala/scala and I was free to experiment on whatever made sense to me at the time. Only once I had something complete to show I'd go to Scala team and ask whether my modifications would make sense to merge upstream. I'd have leverage in discussion in terms of experience and working features. I recommend you doing the same.

**Comment by soc** [comment]
@gkossakowski Is there any description of the steps necessary to publish and distribute the binary artifacts of such a fork?

**Comment by gkossakowski** [comment]
@soc: let's discuss this on scala-internals. The short answer is: check `publish` target in `build.xml` file. You'll need to modify groupId and artifactId so you won't clash with regular scala releases/snapshots.

**Pull request closed without merging**
