### PR TITLE
relaxes attachment-matching rules

### PR DESCRIPTION
**Pull request by xeno-by**
It came as a surprise recently, but attachments.contains/get/update/remove
require the class of the payload to match the provided tag exactly, not
taking subclassing into account. This commit fixes the oversight.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by lrytz** [comment]
Is the empty `.check` file needed? LGTM otherwise.

**Comment by xeno-by** [comment]
Removed the check file

**Comment by xeno-by** [comment]
Everything's green. Let's merge?

**Comment by retronym** [comment]
LGTM. I ran into the need for this myself recently.

**Pull request merged**
