### PR TITLE
streamlines refchecking undesired symbol properties

### PR DESCRIPTION
**Pull request by xeno-by**
Unifies `checkDeprecated`, `checkMigration` and `checkCompileTimeOnly`
into a single centralized point of reference that is now consistently
called from `checkTypeRef`, `transformIdent` and `transformSelect`.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
LGTM, check one, check them all.

I'm curious: have you developed a use case for `compileTimeOnly` classes?

**Comment by xeno-by** [comment]
https://github.com/scalamacros/paradise/commit/1a15719053e263e9a0d59ffcf4f1322fe51dcfca :)

**Comment by adriaanm** [comment]
Looks like this broke the deprecation work-around. In itself perhaps not that bad, but curious nonetheless:

@som-snytt says:

```
It regressed in M8, BTW.

apm@mara:~$ ./scala-2.11.0-M7/bin/scala -deprecation
Welcome to Scala version 2.11.0-M7 (OpenJDK 64-Bit Server VM, Java 1.7.0_25).

Type in expressions to have them evaluated.
Type :help for more information.

scala> @deprecated("","") def f = 8
f: Int

scala> def g = { @deprecated("","") def _f = f ; _f }
g: Int

scala> :q
apm@mara:~$ ./scala-2.11.0-M8/bin/scala -deprecation
Welcome to Scala version 2.11.0-M8 (OpenJDK 64-Bit Server VM, Java 1.7.0_25).

Type in expressions to have them evaluated.
Type :help for more information.

scala> @deprecated("","") def f = 8
f: Int

scala> def g = { @deprecated("","") def _f = f ; _f }
<console>:8: warning: method _f is deprecated:

       def g = { @deprecated("","") def _f = f ; _f }
                                                 ^
g: Int
```

**Comment by som-snytt** [comment]
Continuing the thread, @som-snytt added:

```
I'm not sure the refactoring change (checkUndesiredProperties in RefChecks) intended to undermine this use case.

The use case would be: _f is not API, so don't warn when I use it.  That is analogous to suspending variance checking on private[this].
```

I tried a few counter-examples last but ran out of runway, where the runway is when the hero is trying to take off before the plane reaches the edge of the cliff, and the cliff is sleep.

**Pull request merged**
