### PR TITLE
spec: Add a link to the sources from the main page

### PR DESCRIPTION
**Pull request by smarter**
Alternatively, the link could be added to the header of each page, but this requires messing with the CSS which hardcodes the height of the header for some reason.

### CODE REVIEW

**Comment by adriaanm** [comment]
Good idea, thank you! I'd like to more explicitly invite contributions. Maybe something like

### [Contribute](https://github.com/scala/scala/tree/2.11.x/spec) your fixes and clarifications through GitHub!

Ideally, each html file would link directly to the corresponding markdown. Feel free to fix the CSS to remove the hardcoded header if necessary.

**Comment by adriaanm** [comment]
I guess I can ignore that mr. Perfect on my shoulder and merge. Even mr. Goodenough would like to refine at some point, though.

**Comment by smarter** [comment]
I wanted to implement your suggestion but lacked time to do it recently, I'll try to do it in a week or two.

**Comment by adriaanm** [comment]
Thanks! No worries

**Pull request merged**
