### PR TITLE
SI-5750 scala.reflect.makro => scala.reflect.macros

### PR DESCRIPTION
**Pull request by xeno-by**
Previously was https://github.com/scala/scala/pull/983

### CODE REVIEW

**Comment by xeno-by** [comment]
The only difference from https://github.com/scala/scala/pull/983 is removal of the @deprecation annotation on scala.reflect.makro.Context. review by @adriaanm and @odersky

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
It appears that the precursor of this pull request got positive reviews except for the deprecation part. Now when it's gone, and scala.reflect.makro.Context is no more, it's can be merged, right?

**Comment by odersky** [comment]
LGTM

**Comment by jsuereth** [comment]
Another merge conflict.    Let's get this one in quick, if we can before others continue to conflict.

**Comment by xeno-by** [comment]
Prepping a pullrequest that would unite https://github.com/scala/scala/pull/1017, https://github.com/scala/scala/pull/1031 and https://github.com/scala/scala/pull/1035. ETA: 15 minutes.

**Comment by xeno-by** [comment]
https://github.com/scala/scala/pull/1039

**Pull request closed without merging**
