### PR TITLE
(2.10.4) duplicates macro arguments before expansion

### PR DESCRIPTION
**Pull request by xeno-by**
As discussed with Jason, this is an important dimension of defenses that
we can build to ensure robustness of the macro engine.

This commit is important in the context of the upcoming patch to the
presentation compiler that will throw away expansions and keep original
macro applications (only when run in presentation compiler mode) so that
hyperlinking in macro arguments starts working in the IDE.

Duplication of macro arguments will make sure that macro arguments, which
are going to become exposed to the IDE, can’t become corrupted by possibly
misbehaving or misguided macros.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by adriaanm** [comment]
Just for planning purposes, any more 2.10.4 PRs planned? (I was planning to cut the release tomorrow, as the queue has technically been closed since last Friday.)

**Comment by xeno-by** [comment]
@adriaanm It's just today we got together with Jason and discussed some immediate fixes that can be applied to macros, so I decided to backport some of them to 2.10. I guess the PRs in flight are everything that we can do given binary compatibility constraints of 2.10.x, so the rest of PRs coming from me in the nearest future will target M8.

**Comment by adriaanm** [comment]
Ok, great!

**Comment by xeno-by** [comment]
Closes this PR for now until its master counterpart is merged.

**Pull request closed without merging**
