### PR TITLE
[ci: last-only] Merge 2.12.x to 2.13.x (September 28, 2021)

### PR DESCRIPTION
**Pull request by SethTisue**
these either merged cleanly, or were inapplicable, or the conflicts were trivial to resolve:

```
* 29b30fd468 - (origin/2.12.x) Merge pull request #9772 from SethTisue/jdk17-ga (19 minutes ago) <Seth Tisue>
* 704fbf1959 - Merge pull request #9766 from sjrd/remove-assert8-in-assertutil (6 days ago) <Seth Tisue>
* 1fccf71acf - Merge pull request #9761 from lrytz/infix-rangepos (12 days ago) <Lukas Rytz>
* afec194c1f - Merge pull request #9760 from SethTisue/restarr-on-2.12.15 (2 weeks ago) <Seth Tisue>
* 96a666989b - (tag: v2.12.15) Merge pull request #9759 from SethTisue/redo-secrets (2 weeks ago) <Seth Tisue>
```
but these two didn't merge cleanly and I skipped them (with `-sours`):

```
* ec0b07ffe2 - Merge pull request #9751 from GreenRecycleBin/issue-11253 (13 days ago) <Seth Tisue>
* 3522d0335d - Merge pull request #9762 from lrytz/wildcard-kind (12 days ago) <Lukas Rytz>
```

@lrytz can you submit a separate forward-port of #9762?

@GreenRecycleBin can you submit a separate forward-port of #9751?

### CODE REVIEW

**Comment by lrytz** [comment]
> @lrytz can you submit a separate forward-port of #9762?

This is 2.12 only, I should have marked it `[nomerge]`.

**Comment by lrytz** [comment]
```
[error] /home/jenkins/workspace/scala-2.13.x-validate-main/src/testkit/scala/tools/testkit/AssertUtil.scala:23:30: Unused import
[error] import scala.util.Properties.isJavaAtLeast
[error]                              ^
```

**Comment by SethTisue** [comment]
I've set a personal reminder to make sure #9751 doesn't get forgotten for 2.13.7. (@GreenRecycleBin if you're too busy or whatever, I can do the forward-port.)

**Comment by SethTisue** [comment]
forward port of #9751: https://github.com/scala/scala/pull/9784

**Pull request merged**
