### PR TITLE
SI-8478 Fix a performance regression in subtyping

### PR DESCRIPTION
**Pull request by retronym**
When checking `M[X] <:< M[Y]` for an `M` with an invariant
parameter, we have to check that `X <:< Y && Y <:< X`. This is
done in `isSubArgs`.

The compile time of the test in the ticket jumps from 20s in
2.10.4 to too-long-to-measure in 2.11.0. This commit reverts the
a subtle change to `isSubArgs` in ea93654 that was ultimately
responsible.

The search for this was unusually circuitious, even for scalac.
It appeared in 9c09c1709 due a tiny error that has since been
reverted in 58bfa19. But 58bfa19 still exhibited abysmal performance,
due to an intervening regression that I'm targeting here.

I haven't managed to extract a performance test from Slick. Using
the test that @cvogt provided, however, with this patch:

```
% time qbin/scalac -J-Xmx4G -classpath /Users/jason/code/slick-presentation/target/scala-2.10/classes:/Users/jason/.sbt/0.13/staging/b64b71d1228cdfe7b6d8/slick/target/scala-2.10/classes:/Users/jason/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.6.4.jar /Users/jason/code/slick-presentation/src/main/scala/SlickPresentation.scala

real    0m21.853s
user    0m33.625s
sys 0m0.878s
```

Which is back to 2.10.x style performance.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by retronym** [comment]
Note that this is only a side issue I discovered and doesn't close the ticket.

**Comment by adriaanm** [comment]
LGTM 

What happens when we special case invariance and check =:= directly?

**Comment by retronym** [comment]
Some tests break. I remember asking about this code once but can't dig up the details. Should be a comment in there if we can find it out.

```
test/partest --update-check \
  /Users/jason/code/scala/test/files/pos/raw-map \
  /Users/jason/code/scala/test/files/pos/t6499.scala \
  /Users/jason/code/scala/test/files/pos/t7517.scala \
  /Users/jason/code/scala/test/files/pos/t7983.scala \
  /Users/jason/code/scala/test/files/pos/t8146b.scala \
  /Users/jason/code/scala/test/files/pos/t8237.scala \
  /Users/jason/code/scala/test/files/pos/t8237b.scala
```

Example:

```
% pt --verbose test/files/pos/raw-map

% scalac raw-map/S_2.scala
S_2.scala:4: error: polymorphic expression cannot be instantiated to expected type;
 found   : [K, V]java.util.HashMap[K,V]
 required: java.util.Map[_, _]
Note: K <: Any (and [K, V]java.util.HashMap[K,V] <: java.util.HashMap[K,V]), but Java-defined trait Map is invariant in type K.
You may wish to investigate a wildcard type such as `_ <: Any`. (SLS 3.2.10)
Note: V <: Any (and [K, V]java.util.HashMap[K,V] <: java.util.HashMap[K,V]), but Java-defined trait Map is invariant in type V.
You may wish to investigate a wildcard type such as `_ <: Any`. (SLS 3.2.10)
    x.setRawType(new java.util.HashMap)
                 ^
```

**Comment by adriaanm** [comment]
Interesting -- maybe something else is broken, because in principle I think that should work.

**Comment by paulp** [comment]
You can find internals threads discussing the curiosity that (a <:< b) && (b <:< a) doesn't imply (a =:= b). There are multiple ways to witness the discrepancy.

**Comment by paulp** [comment]
The real funball in there is pos/t7517.scala, which comes through a couple times such that neither type is a subtype of the other, but comparing them with =:= returns true - and from that point forward each type IS a subtype of the other.

Printing the types before and after the answer-changing =:= call, one sees

```
?B[T]                                              =:= T
=?T[T]                                             =:= T

[A[x]]?K[[T]A[=?T[T]]]                             =:= Composed.this.Split
[A[x]]=?Composed.this.Split[A][[T]A[=?T[T]]]       =:= Composed.this.Split
```

**Pull request merged**
