### PR TITLE
SIP-11+: Default interpolator

### PR DESCRIPTION
**Pull request by som-snytt**
Git munges the test file when I try to rebase.

### CODE REVIEW

**Comment by adriaanm** [comment]
2.12.0-M1 is being cut soon, so I'm assigning to M2, unless others feel this should be in M1? What do others say?

**Comment by som-snytt** [comment]
@adriaanm This isn't close to consensus. The last commit is to virtualize ordinary string constants as a StringContext.apply macro, as somebody asked for. I was going to submit at typelevel first.

**Comment by adriaanm** [comment]
You're very welcome to keep it open here!

**Comment by som-snytt** [comment]
Thx, I'll finish off that last commit. I thought it would be a good trial for typelevel -> typesafe flow, but maybe not.

**Pull request closed without merging**
