### PR TITLE
blackbox and whitebox macros

### PR DESCRIPTION
**Pull request by xeno-by**
Documentation: http://docs.scala-lang.org/overviews/macros/blackbox-whitebox.html
Depends on: https://github.com/scala/scala/pull/2994. 
Review: @retronym @adriaanm

### CODE REVIEW

**Comment by xeno-by** [comment]
Oh boy, looks like today I'm particularly lucky with rebases :)

**Comment by adriaanm** [comment]
Is this intended for M6?

**Comment by xeno-by** [comment]
@adriaanm I wouldn't mind that.

**Comment by xeno-by** [comment]
I'll rebase this pull request tomorrow after addressing all the comments for the PR this one depends on. Would that be okay?

**Comment by adriaanm** [comment]
We're tagging at the end of next week, and will need a couple of days to review, so it should work.

**Comment by xeno-by** [comment]
We have a test failure stemming from a binary incompatibility that prevents macros compiled with this branch from being used by compilers of previous versions and vice versa:

```
/localhome/jenkins/b/workspace/pr-scala-test/scala/test/build-partest.xml:17: Test suite finished with 1 case failing:
fail - run/t6331b.scala  [compilation failed]% scalac t6331b.scala
error: bad macro impl binding: expected version format 6.0, actual 5.0
error: bad macro impl binding: expected version format 6.0, actual 5.0
```

@adriaanm What's the recommended course of action here?

**Comment by adriaanm** [comment]
Support both formats for a while.

**Comment by xeno-by** [comment]
@adriaanm Done

**Comment by xeno-by** [comment]
By the way, do you think we should support forward compatibility as well? For example, 2.11.0-M5 won't be able to expand macros compiled with 2.11.0-M6. Shall we go out of our way to make 2.11.0-M6 tolerate future, unanticipated changes in the macro pickle format?

**Comment by xeno-by** [comment]
@adriaanm @retronym How does one decypher one-liner errors from partest? Is it possible to ask it to print stack traces?

**Comment by retronym** [comment]
I had the same problem a few days back. Haven't fixed it yet in partest. Here are instructions to patch partest and use a local build of it to show exception stack traces:

https://issues.scala-lang.org/browse/SI-7839?focusedCommentId=65979&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-65979

**Comment by xeno-by** [comment]
Well I can also try to guess what the problem is. Most likely, macros in partest can't find the `scala.reflect.macros.Context` class, which is now gone. @adriaanm, is it possible to rebuild partest using the new macro engine?

**Comment by adriaanm** [comment]
Not immediately -- these things require deprecation (the cycle is short: a milestone-month).

**Comment by xeno-by** [comment]
How do we go about this? Now we have `BlackboxContext` and `WhiteboxContext`, but not `Context` anymore.

**Comment by xeno-by** [comment]
I could support both until M7, but that feels really awkward... Introducing ugliness into code in order to be backward compatible with a machine :( Maybe we could come up with another way?

**Comment by xeno-by** [comment]
@adriaanm @retronym Regardless of the compatibility verdict, could we have a review of this pull request for M6? 

If compatibility is the only blocker for this being merged, then as mentioned above I could support `Context` until M7, and I could implement that real fast.

**Comment by retronym** [comment]
I wonder if we should call them `Context` and `WhiteBoxContext`?

**Comment by xeno-by** [comment]
That would break whitebox macros from 2.10

**Comment by retronym** [comment]
Sure, but we have reserved the right to make breaking changes to macros. It will be a bit painful, but we have to figure balance that against the long term API that we end up living with.

I haven't given this enough thought to have a strong opinion, but wanted to discuss the options.

**Comment by xeno-by** [comment]
It doesn't have to inflict any pain with the solution proposed in the pr. Provide new contexts and deprecate the old one, so that everyone has time to migrate.

**Comment by xeno-by** [comment]
Rebased against master and split the pull request into a number of clearer commits.

**Comment by xeno-by** [comment]
Again rebased against master.

**Comment by xeno-by** [comment]
@retronym @adriaanm Allright, I managed to fix the compatibility issue with macros living in scala-partest.jar, but now I stumbled upon scala-integrate-partest, fixing which would require grokking how the build scripts work: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-partest/2602/console.

If you guys plan to merge this PR in M6, then I can try to figure out what's going on and fix it today. Otherwise, it would be probably better to discuss this with Jason in person (would it be okay, Jason?) on the next reflection meeting.

If you feel that this PR needs more discussion, then let's defer it, however personally I would prefer to have this PR merged into this milestone in order not to accumulate todo items for the final milestone, around which I will be travelling to/from Indianapolis.

**Comment by xeno-by** [comment]
Finally reproduced the pr-scala-integrate-partest problem locally. If someone faces something like that in the future, you might use my script to save some time: https://github.com/xeno-by/dotx/blob/master/integrate.

**Comment by xeno-by** [comment]
Apparently the build failure was caused by an issue with the scala-partest build and/or SBT. I fixed the jenkins script and submitted a pull request: https://github.com/scala/jenkins-scripts/pull/36.

**Comment by xeno-by** [comment]
Here's the result of running https://github.com/xeno-by/dotx/blob/bc7624209c245b684937f8048cee8728d0230227/integrate (a more or less precise approximation of scala-integrate-partest) on this pull request: https://gist.github.com/xeno-by/6991769.

**Comment by xeno-by** [comment]
Rebased because this PR was no longer mergeable.

**Comment by xeno-by** [comment]
PLS REBUILD/pr-scala@13bbea0

**Comment by xeno-by** [comment]
@retronym @adriaanm Hi folks, it looks like we're in a bit of a stalemate here with the pr-scala-integrate-partest problem. Since as close as in three days I'll be barely available until past the M7 deadline, how about we apply a workaround proposed by Jason in https://github.com/scala/jenkins-scripts/pull/36#issuecomment-26133931, and then at some later point revisit the underlying SBT issue?

**Comment by adriaanm** [comment]
@gkossakowski has been working on fixing a related problem in scala-xml -- assigned this PR to him so we can get this merged before you have to travel

**Comment by xeno-by** [comment]
Rebased because this PR was no longer mergeable.

**Comment by xeno-by** [comment]
@adriaanm @retronym @gkossakowski It looks like Greg's pull request got reverted. What do we do about this one then?

**Comment by gkossakowski** [comment]
@xeno-by: there were two commits related to dependencies:
- 053193f83a2e84996ac33e692322ea5b0b3e1321 (got reverted)
- 1d665334756b3990eea5f219dd0e54b237f0e7fe

The 1d665334756b3990eea5f219dd0e54b237f0e7fe is crucial for fixing the classpath used for testing scala-xml. I'm guessing we have similar problems in partest but this time for compiling and not testing. Let me comment on scala/jenkins-scripts#36.

**Comment by gkossakowski** [comment]
@adriaanm, @xeno-by: as I [mentioned](https://github.com/scala/jenkins-scripts/pull/36#issuecomment-26950946) I can't reproduce the problem that is blocking this PR. I don't have more time to spend on this at the moment so I'm unassigning myself from this PR.

**Comment by adriaanm** [comment]
I asked Toni to add support to dbuild for loading versions.properties files, which should fix the problem with the sbt build's version requirements for the scala modules being out of whack. Will be part of dbuild 0.7, which should land soon!

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@adriaanm How would a fix to dbuild help jenkins partest integration? I might be misunderstanding something, but I can't see the connection.

**Comment by adriaanm** [comment]
It wouldn't -- I guess I got my failures mixed up.

The failure I'm seeing for partest would (I guess) be fixed by supporting both formats, as I [suggested above](https://github.com/scala/scala/pull/3001#issuecomment-25381694)

```
[error] /localhome/jenkins/a/workspace/pr-scala-integrate-partest/scala-partest/src/main/scala/scala/tools/partest/package.scala:200: macro implementation has wrong shape:
[error]  required: (c: <notype>)(a: c.<none>[A]): c.<none>[A]
[error]  or      : (c: <notype>)(a: c.<none>[A]): c.<none>[A]
[error]  found   : (c: scala.reflect.macros.Context)(a: c.Expr[A])(implicit evidence$1: c.WeakTypeTag[A]): c.Expr[A]
[error] macro implementations cannot have implicit parameters other than WeakTypeTag evidences
[error]   def trace[A](a: A) = macro traceImpl[A]
[error]       ^
[error] one error found
[error] /localhome/jenkins/a/workspace/pr-scala-integrate-partest/scala-partest/src/main/scala/scala/tools/partest/package.scala:200: macro implementation has wrong shape:
[error]  required: (c: <notype>)(a: c.<none>[A]): c.<none>[A]
[error]  or      : (c: <notype>)(a: c.<none>[A]): c.<none>[A]
[error]  found   : (c: scala.reflect.macros.Context)(a: c.Expr[A])(implicit evidence$1: c.WeakTypeTag[A]): c.Expr[A]
[error] macro implementations cannot have implicit parameters other than WeakTypeTag evidences
[error]   def trace[A](a: A) = macro traceImpl[A]
[error]       ^
```

**Comment by xeno-by** [comment]
@adriaanm As mentioned in https://github.com/scala/jenkins-scripts/pull/36#issuecomment-26134187, the problem is in not the lack of backward compatibility, but rather the fact that our particular SBT setup somehow calls into an old version of the compiler that can't handle the new stuff.

We have a fix to the SBT build from @retronym mentioned in https://github.com/scala/jenkins-scripts/pull/36#issuecomment-26133931 that would remedy the failure. Can we get it merged?

**Comment by adriaanm** [comment]
Ah, sorry I forgot the root cause. I think you'll have to wait until we move to M6, which should fix that problem.
@gkossakowski is working on this

**Comment by xeno-by** [comment]
@adriaanm @gkossakowski When do you plan to perform the migration? Will it let this pull request to be merged into M7?

**Comment by adriaanm** [comment]
Yes, it should be fine for M7. Greg's in Lausanne this week, so you can ask him directly ;-)

**Comment by xeno-by** [comment]
Wow! Great news!

**Comment by xeno-by** [comment]
Hopefully, 7th rebase is a charm :)

**Comment by xeno-by** [comment]
@retronym Given that the recent Greg's pull request to scala-partest is supposed to unblock this one, can I get an LGTM, so that I can merge it right away when all the tests pass?

**Comment by gkossakowski** [comment]
@xeno-by: we haven't updated the partest version yet so I think this will still fail.

I'm working on releasing a new version of partest. Should be done today.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@adriaanm MWAHAHA!! I cannot believe that pr-scala-integrate-partest is now passing. Thanks to everyone who was involved in fixing it. Shall we merge?

**Comment by xeno-by** [comment]
Okay, I was too quick to declare victory... It's still the same...

```
[info] Set current project to scala-partest (in build file:/localhome/jenkins/c/workspace/pr-scala-integrate-partest/scala-partest/)
[info] Updating {file:/localhome/jenkins/c/workspace/pr-scala-integrate-partest/scala-partest/}scala-partest...
[warn] Binary version (2.11.0-f049393-SNAPSHOT) for dependency org.scala-lang#scala-compiler;2.11.0-f049393-SNAPSHOT
[warn]  in org.scala-lang.modules#scala-partest_2.11.0-M4;1.0-RC4 differs from Scala binary version in project (2.11.0-M4).
[warn] Binary version (2.11.0-f049393-SNAPSHOT) for dependency org.scala-lang#scala-library;2.11.0-f049393-SNAPSHOT
[warn]  in org.scala-lang.modules#scala-partest_2.11.0-M4;1.0-RC4 differs from Scala binary version in project (2.11.0-M4).
```

@gkossakowski Are the changes to scala-partest deployed?

**Comment by adriaanm** [comment]
versions.properties has not been changed yet in master -- there's another issue that's blocking this

**Comment by adriaanm** [comment]
I tried to bump it in #3108 earlier today and it broke like this: https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-distpack/3904/consoleText -- seems like the scala.reflect package class has lost its io member? I'll look into this next week

**Comment by adriaanm** [comment]
Closing in favor of #3129

**Pull request closed without merging**
