### PR TITLE
Bump sbt-jmh version to 0.2.16

### PR DESCRIPTION
**Pull request by monkey-mas**
It'd be good to use the latest version( with the latest JMH version `1.14.1`). From sbt-jmh version `0.2.10`, Flight Recorder / Java Mission Control is available[1], which would be nice.

[1] https://github.com/ktoso/sbt-jmh#using-oracle-flight-recorder

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @performantdata ?

**Comment by performantdata** [comment]
LGTM, as long as it compiles and runs, which I'd expect with a minor JMH release. You'll need to test that manually; the project tests don't check that automatically.

**Comment by lrytz** [comment]
I tested it by running `jmh:runMain scala.collection.mutable.OpenHashMapRunner` (which seems to be running for long time)

**Comment by SethTisue** [comment]
thanks @monkey-mas!

**Comment by monkey-mas** [comment]
Thanks alot for your review! :)

**Pull request merged**
