### PR TITLE
Enable inlining in constructors.

### PR DESCRIPTION
**Pull request by gkossakowski**
Inlining in constructors has been disabled a long
time ago due to some VerifyErrors. Unfortunately,
@dragos cannot recall what exactly was the problem.
I tried to enable inlining in constructors and I
didn't see any problem.

`Predef.assert` calls in class constructors are one
of the biggest contributors to closure allocation
in a compiler so we better off get rid of it.

Added a test-case that checks if inlining in
constructors works properly.

Review by @magarciaEPFL and @paulp.

### CODE REVIEW

**Comment by VladUreche** [comment]
Nice test!

**Comment by paulp** [comment]
LGTM.  I'm 100% in favor of beating the bushes around this sort of thing, where there are no tests which show us what a piece of code is protecting us from.

**Comment by ijuma** [comment]
Great stuff.

**Comment by magarciaEPFL** [comment]
LGTM

**Comment by magarciaEPFL** [comment]
(As I said, LGTM, the following is just additional discussion and should not be construed as objection)

@gkossakowski, now that you mention `assert()` creating closures, what level of `scalac -Xelide-below` have you been measuring with?

**Comment by gkossakowski** [comment]
@magarciaEPFL: The default one (`MINIMUM`) because I'm using builds from Jenkins.

**Pull request merged**
