### PR TITLE
Update docstring for Array.equals

### PR DESCRIPTION
**Pull request by iobtl**

### CODE REVIEW

**Comment by SethTisue** [comment]
Why does this method even exist? (I think the doc should answer that question.)

**Comment by SethTisue** [comment]
@iobtl interested in returning to this?

**Comment by dwijnand** [comment]
> Why does this method even exist? (I think the doc should answer that question.)

To answer Seth: because Array equals uses object identity (and Scala's `==` doesn't do anything).  So this method is handy (though a bit inconvenient, as shown below):

```scala
scala> val xs = Array[String]("foo")
vval xs: Array[String] = Array(foo)

scala> val ys = Array[String]("foo")
val ys: Array[String] = Array(foo)

scala> xs == ys
val res0: Boolean = false

scala> Array.equals(xs, ys)
       ^
       error: type mismatch;
        found   : Array.type
        required: ?{def equals(x$1: ? >: Array[String], x$2: ? >: Array[String]): ?}
       Note that implicit conversions are not applicable because they are ambiguous:
        both method ArrowAssoc in object Predef of type [A](self: A): ArrowAssoc[A]
        and method Ensuring in object Predef of type [A](self: A): Ensuring[A]
        are possible conversion functions from Array.type to ?{def equals(x$1: ? >: Array[String], x$2: ? >: Array[String]): ?}
                    ^
       error: type mismatch;
        found   : Array[String]
        required: Array[AnyRef]
       Note: String <: AnyRef, but class Array is invariant in type T.
       You may wish to investigate a wildcard type such as `_ <: AnyRef`. (SLS 3.2.10)
                        ^
       error: type mismatch;
        found   : Array[String]
        required: Array[AnyRef]
       Note: String <: AnyRef, but class Array is invariant in type T.
       You may wish to investigate a wildcard type such as `_ <: AnyRef`. (SLS 3.2.10)

scala> Array.equals(xs.asInstanceOf[Array[AnyRef]], ys.asInstanceOf[Array[AnyRef]])
val res2: Boolean = true
```

@iobtl could add a little phrase about this to the docs, please?

**Comment by SethTisue** [comment]
Why is the method declared to operate on `AnyRef` specifically and not on `[T <: AnyRef]`?

**Comment by SethTisue** [comment]
closing for inactivity. somebody else could pick it up

**Comment by som-snytt** [comment]
> Why is the method declared to operate on `AnyRef`

To answer Seth again:

```
scala> def e[A <: AnyRef](xs: Array[A], ys: Array[A]) = xs.sameElements(ys)
def e[A <: AnyRef](xs: Array[A], ys: Array[A]): Boolean

scala> val xs = Array(List(1,2,3))
val xs: Array[List[Int]] = Array(List(1, 2, 3))

scala> val ys = Array(Vector(1,2,3))
val ys: Array[scala.collection.immutable.Vector[Int]] = Array(Vector(1, 2, 3))

scala> e(xs, ys)
         ^
       error: type mismatch;
        found   : Array[List[Int]]
        required: Array[scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_(in type CC)]scala.collection.immutable.AbstractSeq[_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[_(in type CC),[(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[(some other)_(in type CC),[(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[_(in type CC),[(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A(in type CC)]scala.collection.immutable.AbstractSeq[A(in type CC)] with scala.collection.generic.DefaultSerializable]},scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[(some other)_(in type CC),[(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[(some other)(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A(in type CC)]scala.collection.immutable.AbstractSeq[A(in type CC)] with scala.collection.generic.DefaultSerializable]}] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[(some other)A(in type CC)]scala.collection.immutable.AbstractSeq[(some other)A(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[(some other)A(in type CC),[(some other)(some other)(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[(some other)A(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable]}]
       Note: List[Int] <: scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]},scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]}] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.immutable.StrictOptimizedSeqOps[A,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable]}, but class Array is invariant in type T.
       You may wish to investigate a wildcard type such as `_ <: scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]},scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]}] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.immutable.StrictOptimizedSeqOps[A,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable]}`. (SLS 3.2.10)
             ^
       error: type mismatch;
        found   : Array[scala.collection.immutable.Vector[Int]]
        required: Array[scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_(in type CC)]scala.collection.immutable.AbstractSeq[_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[_(in type CC),[(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[(some other)_(in type CC),[(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[_(in type CC),[(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A(in type CC)]scala.collection.immutable.AbstractSeq[A(in type CC)] with scala.collection.generic.DefaultSerializable]},scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[(some other)_(in type CC),[(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[(some other)(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A(in type CC)]scala.collection.immutable.AbstractSeq[A(in type CC)] with scala.collection.generic.DefaultSerializable]}] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[(some other)A(in type CC)]scala.collection.immutable.AbstractSeq[(some other)A(in type CC)] with scala.collection.immutable.StrictOptimizedSeqOps[(some other)A(in type CC),[(some other)(some other)(some other)(some other)(some other)_(in type CC)]scala.collection.immutable.AbstractSeq[(some other)(some other)(some other)(some other)(some other)_(in type CC)] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[(some other)A(in type CC)] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable]}]
       Note: scala.collection.immutable.Vector[Int] <: scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]},scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]}] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.immutable.StrictOptimizedSeqOps[A,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable]}, but class Array is invariant in type T.
       You may wish to investigate a wildcard type such as `_ <: scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]},scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.immutable.StrictOptimizedSeqOps[_,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.immutable.StrictOptimizedSeqOps[Int,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[Int] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable]}] with scala.collection.generic.DefaultSerializable{def iterableFactory: scala.collection.SeqFactory[[A]scala.collection.immutable.AbstractSeq[A] with scala.collection.immutable.StrictOptimizedSeqOps[A,[_]scala.collection.immutable.AbstractSeq[_] with scala.collection.generic.DefaultSerializable,scala.collection.immutable.AbstractSeq[A] with scala.collection.generic.DefaultSerializable] with scala.collection.generic.DefaultSerializable]}`. (SLS 3.2.10)

scala> def e[A <: AnyRef, B <: AnyRef](xs: Array[A], ys: Array[B]) = xs.sameElements(ys)
def e[A <: AnyRef, B <: AnyRef](xs: Array[A], ys: Array[B]): Boolean

scala> e(xs, ys)
val res1: Boolean = true

scala>
```
It's funnier in a terminal with wrapping, because each of the three lines (Required, Note, You may wish to investigate) goes on forever, and you get that twice.

The doc could mention that it's a more efficient alternative to `sameElements`. One could also ask why not overload `sameElements`, I guess that would be in `ArraySeq.ofRef`?

**Comment by som-snytt** [comment]
If you grep for `Array.equ`, where the dot is pattern, you also pick up `xs.toArray equals`,  `ArrayDeque`; my first attempt left off the `u` and matched `ArraySeq`...

**Comment by som-snytt** [comment]
To answer Som:

https://github.com/scala/scala/pull/9337

**Pull request closed without merging**
