### PR TITLE
SI-6605: extract TagKeys and other cleanup.

### PR DESCRIPTION
**Pull request by vigdorchik**

### CODE REVIEW

**Comment by adriaanm** [comment]
- Could you elaborate a bit on what this commit does? (This can be as simple as copy/pasting the message from the ticket into the commit body.)
- What should the reviewer pay particular attention to?
- What would you like to tell the future bug fixer that git bisects her way to this commit?
- Where does the cleanup end and the extraction begin? (This could be made precise by having two commits: one for pure cleanup, minor refactoring. The other that does the actual work. This helps for reviewing, merging, archeology,...)

**Comment by gkossakowski** [comment]
For inspiration, see #2169 where @JamesIry split his change into two commits and described very precisely what's going on.

**Comment by vigdorchik** [comment]
Review by @retronym

**Comment by paulp** [comment]
This looks like a pretty clear improvement to me, but unfortunately I can't figure out how to see the commit which @adriaanm and @gkossakowski were commenting on, and that makes it impossible to know to what extent if at all those comments were addressed. That's really freaking annoying, github.

Is there a way I'm not seeing to see whatever this looked like originally? Right now it says commit "dd46cd4" was "added" sometime after those comments were made, but it's the only commit, so it must have replaced what was here.

**Comment by paulp** [comment]
However, the fact that it's one commit and not two suggests that that's what's left to be done.

**Comment by adriaanm** [comment]
>  but unfortunately I can't figure out how to see the commit which @adriaanm and @gkossakowski were commenting on

I don't think we were commenting on the commit. We commented on the PR. If you do comment on a commit, and it disappears, GitHub will say "X commented on outdated patch" or some such and you can click to get your comments back.

**Comment by paulp** [comment]
Right, that you commented on the PR is what I meant. But you presumably commented on the PR having seen the commit and with the contents of the commit known to you, an environment I now cannot replicate.

**Comment by adriaanm** [comment]
I see. I guess we should add a comment that only make sense in the context of a commit on that commit.

**Comment by adriaanm** [comment]
Thanks for addressing the review comments, @vigdorchik, I think my main wish was to separate refactoring and actual fix. I'm sorry if I'm asking for the impossible. If you feel this is not possible, please add a comment explaining why.

Also, please keep in min commit subjects are supposed to be short. 
Right now you'll see: 

> "SI-6605: This change extracts TagKeys used currently as string consta… …
> …nts."

in the log, whereas it could just as easily be

> "SI-6605: Make TagKeys an enum (instead of string constants)"

**Comment by adriaanm** [comment]
Sorry, @vigdorchik, this PR can't be merged automatically anymore. I'm closing ir for now. Please rebase and reopen next week after the scaladoc refactoring is done.

**Pull request closed without merging**
