### PR TITLE
Merge 2.12.x to 2.13.x [ci: last-only]

### PR DESCRIPTION
**Pull request by SethTisue**
four merge conflicts, all trivially resolvable

motive: get the sbt version bump and the MathJax spec fix
onto 2.13.x.  performance improvements, too.  (note that
the partest version bump was already here.)

```
% git checkout -b merge-2.12-to-2.13-apr-24
% git hist -n 1 | cat
*   483be9a038 - (HEAD -> merge-2.12-to-2.13-apr-24, origin/2.13.x, 2.13.x) Merge pull request #5860 from lrytz/scalacheckUpdate (4 days ago) <Lukas Rytz>
% export mb=$(git merge-base origin/2.12.x 2.13.x)
% git log --graph --oneline --decorate $mb..origin/2.12.x | cat
*   709a75223f (origin/HEAD, origin/2.12.x) Merge pull request #5861 from lrytz/t5717-msg
|\
| * 3733536023 Update error message for t5717
|/
*   7cc1f86473 Merge pull request #5857 from retronym/ticket/10232
|\
| * 9f522c6b3c Fix lambda deserialization in classes with 252+ lambdas
| * d9343a7f10 Remove dead code catch in LambdaDeserializer
* |   81459e475c Merge pull request #5812 from retronym/faster/specialization
|\ \
| * | e416a259a4 Optimize specializedTypeVars
| * | fe4788b97b Only do specialation definalization once per run
| * | e65b714b48 Optimize SpecializeTypes#satisfiable
| * | 8ae0fdab1e Avoid needless work in the specialization info transform in the backend
| * | 5cd3442419 Better diagnostic for failing jvm/future-spec
|  /
* |   3009880b61 Merge pull request #5820 from retronym/faster/backend
|\ \
| * | 070ab67f39 Review feedback: resurrect assertion, use LabelDefFinder.apply
| * | bebb1886de Optimize method descriptor creation
| * | 1ae858cecf Remove expensive assertion in the backend
| * | 53dd4e430e Cache ClassSymbol.javaBinaryNameString
| * | 455729e6f5 Use AnyRefMap in labelReferences
| * | 7a6dc1abbf Avoid excessive file stats during classfile writing
| * | b3975a5a16 Optimize label defs finder in the backend
|  /
* |   6e7fd660d6 Merge pull request #5824 from retronym/faster/sourcefileattr
|\ \
| |/
|/|
| * 27be3a2ef2 Avoid excessive IO in classfile parser
*   db80860e11 Merge pull request #5856 from SethTisue/partest-1.1.1
|\
| * 7236da05f6 upgrade to partest 1.1.1
* |   a3ec4a08f4 Merge pull request #5855 from SethTisue/post-2.12.2-version-bump
|\ \
| * | 0c8bdf632f bump version to 2.12.3
| |/
* |   4efab51a1b Merge pull request #5775 from SethTisue/sbt-0.14
|\ \
| |/
|/|
| * 8b4a033f2c upgrade to sbt 0.13.15
* d61301de77 Merge pull request #5851 from adriaanm/2.12-catchup-2.11
*   771fe005b4 No-op merge 2.11.x into 2.12.x
|\
| *   8a413ba7cc (tag: v2.11.11) Merge pull request #5846 from adriaanm/t10261-2.11
| |\
| | * 77917e94c7 Actually retract clashing synthetic apply/unapply [backport]
| |/
* |   17e160d845 Merge 2.11.x into 2.12.x
|\ \
| |/
| * 5167b691bb MathJax CDN change and version bump
* | f668845a40 No-op merge 2.11.x into 2.12.x
|/
* 7a5df5702c Update README.md
* a3987d86ef Bump on 2.11.10 release
% git merge origin/2.12.x
Auto-merging versions.properties
CONFLICT (content): Merge conflict in versions.properties
Auto-merging src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
CONFLICT (content): Merge conflict in src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
Auto-merging src/reflect/scala/reflect/internal/Definitions.scala
CONFLICT (content): Merge conflict in src/reflect/scala/reflect/internal/Definitions.scala
Auto-merging src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/opt/BytecodeUtils.scala
Auto-merging src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala
Auto-merging build.sbt
CONFLICT (content): Merge conflict in build.sbt
Recorded preimage for 'build.sbt'
Recorded preimage for 'src/reflect/scala/reflect/internal/Definitions.scala'
Recorded preimage for 'src/reflect/scala/reflect/runtime/JavaUniverseForce.scala'
Recorded preimage for 'versions.properties'
Automatic merge failed; fix conflicts and then commit the result.
% emacs build.sbt
% emacs src/reflect/scala/reflect/internal/Definitions.scala
% emacs src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
% emacs versions.properties
% git add -u
% git commit
```

### CODE REVIEW

**Comment by SethTisue** [comment]
/nothingtoseehere

Scabot got confused (because I initially targeted the wrong branch), but there is a green validate-main run for 775bb11 at https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/196/console

@lrytz ready for review/merge

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
I double checked to use "Create Merge Commit" :)

**Pull request merged**
