### PR TITLE
SI-7638 Superaccessor lookup after specialization

### PR DESCRIPTION
**Pull request by VladUreche**
The crash was caused by a symbol lookup to rewire the super calls,
done after pickler, but specialization added new traits and new
members, thus making the super rewiring impossible. To avoid such
problems, this patch moves symbol lookup after specialization,
so the changes done by specialization (and miniboxing) become
visible to mixin.

NOTE: This patch will be followed by a similar patch to master.

Review by @adriaanm or @retronym.

### CODE REVIEW

**Comment by adriaanm** [comment]
2.10.3 is still a ways off -- focusing on releasing 2.11.0-M4 today

**Comment by adriaanm** [comment]
LGTM

**Comment by VladUreche** [comment]
Dank je wel!

**Comment by adriaanm** [comment]
Graag gedaan.

**Pull request merged**
