### PR TITLE
SI-8388 consistently match type trees by originals

### PR DESCRIPTION
**Pull request by densh**
Due to the fact that all TypTrees are transformed into TypeTrees
during typechecking one couldn't treat typed type trees in the same
way as they treat untyped type trees.

This change implements support for pattern matching of TypeTrees as their
corresponding TypTree equivalent using tree preserved in the original.

The implementation itself is a trivial wrapping of regular TypTree
extrarctors into MaybeTypeTreeOriginal.

review @retronym

### CODE REVIEW

**Comment by retronym** [comment]
Seems to me like pattern matching on the shapes of `TypTrees` is always going to be pretty flaky if one is trying to match semantically. When is it useful?

**Comment by densh** [comment]
It is flaky if you compare it to symbol/type-based approaches but at the same time it lowers barrier for new users. This way newbie macrowriters will be able to learn more advanced solutions as they grow rather than being confronted with a number of complex primitives all at once.

Also in long run we'll probably want to have very similar api when hygiene is ready:

```
val t = typecheckTyp(tq"Map[Int, Int]")

// current
t match { case tq"${typ: Type}" if typ =:= typeOf[Map[Int, Int]] => ... }

// after this pr
t match { case tq"scala.Predef.this.Map[scala.Int, scala.Int]" => }

// in future with hygiene
t match { case tq"Map[Int, Int]" => }
```

I can document type-based approach as recommended one but I think it's also good to have non-hygienic original-based matching as it's easier to understand and is only one step away from future hygienic version.

**Comment by retronym** [comment]
Lowering the barrier to flakiness doesn't sound like a good outcome to me.

**Comment by densh** [comment]
Another use case for it extracting structural parts as types or definitions which is not currently possible after typechecking:

```
scala> val tq"$_[..${argTpes: List[Type]}]" = typecheck(tq"List[Int]")
argTpes: List[reflect.runtime.universe.Type] = List(Int)

scala> val tq"$_ forSome { ..$defns }" = typecheck(tq"List[_]")
defns: List[reflect.runtime.universe.MemberDef] = List(<synthetic> type _$1)
```

**Comment by xeno-by** [comment]
@retronym I think this pull request is an important step forward given the state of the art, in which quasiquotes match trees syntactically, not hygienically. Not only it brings consistency with term matching, but it also covers an important use case that is requested by users. Imo, that's a good thing.

**Comment by retronym** [comment]
This needs a rebase.

**Comment by xeno-by** [comment]
Rebased

**Comment by adriaanm** [comment]
Still says it can't merge, btw.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scala/scala/pull/3657

**Pull request closed without merging**
