### PR TITLE
More clear implicitNotFound error for ExecutionContext

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by heathermiller** [comment]
Cool, much better! LGTM :)

**Comment by heathermiller** [comment]
Could also be useful for 2.11 – 2.10.x fixes are (eventually) being merged into 2.11, no?

**Comment by jamesward** [comment]
This one is a cherry-pick of my original PR to master: https://github.com/scala/scala/pull/3079

**Comment by heathermiller** [comment]
Gotcha, awesome then!

**Comment by retronym** [comment]
LGTM

**Pull request merged**
