### PR TITLE
SI-8362: AbstractPromise extends AtomicReference, avoids sun.misc.Unsafe

### PR DESCRIPTION
**Pull request by adriaanm**
Rebases and slightly reworks #4313.

### CODE REVIEW

**Comment by adriaanm** [comment]
Access was unfortunately relaxed to public because there's no way to emit default access in Scala...

```
Compiled from "AbstractPromise.scala"
public abstract class scala.concurrent.impl.AbstractPromise extends java.util.concurrent.atomic.AtomicReference<java.lang.Object>
  minor version: 0
  major version: 50
  flags: ACC_PUBLIC, ACC_SUPER, ACC_ABSTRACT
```

Before:

```
abstract class scala.concurrent.impl.AbstractPromise
  minor version: 0
  major version: 50
  flags: ACC_SUPER, ACC_ABSTRACT
```

**Comment by adriaanm** [comment]
/nothingtoseehere (just overriding validate-main which should be green since all its parts are)

**Comment by adriaanm** [comment]
I cannot explain the required change in bincompat-backward.whitelist.conf
Bizarrely, scala.concurrent.impl.Promise$DefaultPromise's signature changed?
Looking at it with the REPL's :javap:

``` patch
-public class scala.concurrent.impl.Promise$DefaultPromise<T extends java.lang.Object> extends scala.concurrent.impl.AbstractPromise implements scala.concurrent.impl.Promise<T>
+public class scala.concurrent.impl.Promise$DefaultPromise<T>                          extends scala.concurrent.impl.AbstractPromise implements scala.concurrent.impl.Promise<T>
```

Not sure why mima picks up the (irrelevant) change in generic signature (or even why there is a change...)

Checking backward binary compatibility for scala-library (against 2.11.0)
- the type hierarchy of class scala.concurrent.impl.Promise#DefaultPromise
  has changed in new version. Missing types {java.lang.Object}

```
 matchName="scala.concurrent.impl.Promise$DefaultPromise"
 problemName=MissingTypesProblem
```

Checking forward binary compatibility for scala-library (against 2.11.0)
(Note that messages are phrased for backwards compat checks, so flip their relative sense)
- the type hierarchy of class scala.concurrent.impl.Promise#DefaultPromise
  has changed in new version. Missing types {java.util.concurrent.atomic.AtomicReference}
- class scala.concurrent.impl.AbstractPromise was public;
  is inaccessible in new version
- method getState()java.lang.Object in class
  scala.concurrent.impl.AbstractPromise was public;
  is inaccessible in new version
- method updateState(java.lang.Object,java.lang.Object)Boolean in class
  scala.concurrent.impl.AbstractPromise was public;
  is inaccessible in new version
- method this()Unit in class scala.concurrent.impl.AbstractPromise was public;
  is inaccessible in new version

**Comment by adriaanm** [comment]
I hesitate to merge this after triple-checking. @retronym, @lrytz, any thoughts on the unexpected signature change for `scala.concurrent.impl.Promise$DefaultPromise`?

**Comment by retronym** [comment]
I didn't get to the bottom of the generic signature change yet. Will take another look tomorrow.

**Comment by lrytz** [comment]
I tried to reproduce the signature change but couldn't. Somehow it reminds me of https://github.com/scala/scala/pull/4403, and also https://github.com/scala/scala/pull/4080.

**Comment by gourlaysama** [comment]
@lrytz: I had the same thought, but I also can't reproduce the signature change.
I see the signature below both before and after this change for `Promise$DefaultPromise` (and in 2.11.0 too):

```
<T:Ljava/lang/Object;>Lscala/concurrent/impl/AbstractPromise;Lscala/concurrent/impl/Promise<TT;>;
```

**Comment by adriaanm** [comment]
I can no longer reproduce with javap, so can only assume it's a mima bug. I javap'ed `scala.concurrent.impl.Promise$DefaultPromise` from 2.11.4 (don't ask) and this commit:

``` diff
--- javap   2015-07-29 22:08:30.000000000 -0700
+++ 2.11.8-c201eac/javap    2015-07-29 22:12:17.000000000 -0700
@@ -1,6 +1,6 @@
-Classfile /private/tmp/scala/concurrent/impl/Promise$DefaultPromise.class
-  Last modified Oct 23, 2014; size 14881 bytes
-  MD5 checksum d44446cc4a9d37572aa489d9ff98d50e
+Classfile /private/tmp/2.11.8-c201eac/scala/concurrent/impl/Promise$DefaultPromise.class
+  Last modified Jul 29, 2015; size 15119 bytes
+  MD5 checksum 7491676e04834077829f40e3afe48f19
   Compiled from "Promise.scala"
 public class scala.concurrent.impl.Promise$DefaultPromise<T extends java.lang.Object> extends scala.concurrent.impl.AbstractPromise implements scala.concurrent.impl.Promise<T>
   Signature: #3                           // <T:Ljava/lang/Object;>Lscala/concurrent/impl/AbstractPromise;Lscala/concurrent/impl/Promise<TT;>;
@@ -11,6 +11,22 @@
        public static final #387= #184 of #7; //CompletionLatch=class scala/concurrent/impl/Promise$CompletionLatch of class scala/concurrent/impl/Promise
        public static #390= #189 of #389; //InternalCallbackExecutor$=class scala/concurrent/Future$InternalCallbackExecutor$ of class scala/concurrent/Future
 Error: unknown attribute
+    ScalaInlineInfo: length = 0xD6
```

Note there's no diff for `public class scala.concurrent.impl.Promise$DefaultPromise<T extends java.lang.Object> extends scala.concurrent.impl.AbstractPromise implements scala.concurrent.impl.Promise<T>
`

**Comment by adriaanm** [comment]
Any objections to merging, @retronym || @lrytz || @SethTisue? We've been down the "what could possibly be binary incompatible about this" street before, so just quadruple checking :-)

**Comment by retronym** [comment]
LGTM.

**Comment by SethTisue** [comment]
LGTM

**Pull request merged**
