### PR TITLE
SI-7729 Does Par-Test work?  Absolutely!

### PR DESCRIPTION
**Pull request by som-snytt**
Absolutize paths where possible; cherry-pick the fix for #ifdiff check files; and zap the log file before starting a run.

It also touches the partest script with the new voudou and to cd -P > /dev/null, to ignore the extra echo if CDPATH matches.

Why isn't this a problem with scalac? Presumably I never run it from that location.

In fact,

```
apm@mara:~/projects/snytt$ build/pack/bin/scala
Error: Could not find or load main class .home.apm.projects.snytt.build.pack.lib.diffutils.jar
```

Ha, I don't even know what that means.

My usual aliases have absolute paths.

Almost forgot:

Review by @paulp

### CODE REVIEW

**Comment by som-snytt** [comment]
You know that kitten toy which is just a feather on the end of a wire?

They'll chase that thing for hours and hours. They just love it.

It makes me miss my old cats Indie and Aria.

**Comment by adriaanm** [comment]
This time it's jenkins throwing a wrench in the litter.

**Comment by paulp** [comment]
LGTM with the usual caveats on TM.

**Comment by som-snytt** [comment]
If it turns out that LGTM is the French acronym for Le Greenwich-Temp Moyen or something, I'll be pretty devastated.  I'd have to go back and delete all the LGTM emails from paulp I've been saving for my scrapbook.  Or no, I'd have to print them all out, tear them into tiny bits, add incense and maybe some sort of accelerant, and set them alight in a soul-purifying blaze.  Then I'd feel compelled, as a person of scrupulous integrity, not only to remove them from the Professional Awards and Recognition section of my resume, but to track down and destroy every copy I've sent out bearing that misinformation.

**Pull request merged**
