### PR TITLE
showRaw now prints symbols of def trees

### PR DESCRIPTION
**Pull request by xeno-by**
A very useful addition that came in handy when hacking macro annotations

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
LGTM

**Comment by retronym** [comment]
You might want to check if we should update the docs that show examples of `showRaw`: http://docs.scala-lang.org/overviews/reflection/symbols-trees-types.html after this is released.

**Comment by xeno-by** [comment]
Yeah we'll definitely have to. Thanks for catching this!

**Pull request merged**
