### PR TITLE
Resolve several deprecation warnings

### PR DESCRIPTION
**Pull request by kmizu**
- Fix one warning in `Util.scala`
- Fix warnings against usage of `isPackage` method
  - Replace it with `hasPackageFlag` 
- Replace `SyncVar#set` with `SyncVar#put`

### CODE REVIEW

**Comment by kmizu** [comment]
I signed the Scala CLA after creating this pull request.

**Comment by kmizu** [comment]
@retronym Could you review this pull request?

**Comment by adriaanm** [comment]
Thank you, @kmizu!

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
