### PR TITLE
first step in making mirrors work with primitives  

### PR DESCRIPTION
**Pull request by xeno-by**
mirrors now carry a class tag of the receiver, so that they can detect
value classes being reflected upon and adjust accordingly (e.g. allow
Int_+ for ints, but disallow it for Integers). This is a first step
in fixing SI-6179.

However magic methods on primitives (e.g. Int_+ or Boolean_||) are not
implemented yet. There are a lot of them, and bruteforce solution
would produce a lot of code. Hence we'd better take time to think of a
better way to do it. Anyhow this commit is an improvement, because
it replaces a cryptic error message with a clearly stated error.

Suprisingly enough derived value classes (SIP-15 guys that inherit from AnyVal)
have been working all along, so no modification were required to fix them.

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @adriaanm or @odersky

**Comment by xeno-by** [comment]
This pull request depends on a https://github.com/scala/scala/pull/1048, which is wildly popular these days. It also won't merge cleanly with other pull requests, but this really can't be helped. 

However instead of integrating the offending commit into some pull request so that no merge is necessary, I decided to put it up as a standalone unit of discussion. Anyways, as experience shows, it's a good idea to unite all approved reflection pull request into an ultimate pull request rather than trying to merge them one by one.

**Comment by odersky** [comment]
non-symbolic methods on Any (Any_equals, Any_hashCode) should be mapped to same-named Objetc methods.
Optimize for speed by forming subclasses.

**Comment by xeno-by** [comment]
Will be resubmitted jointly with https://github.com/scala/scala/pull/1048, https://github.com/scala/scala/pull/1052, https://github.com/scala/scala/pull/1054 and https://github.com/scala/scala/pull/1057.

**Comment by xeno-by** [comment]
Superceded by https://github.com/scala/scala/pull/1067

**Pull request closed without merging**
