### PR TITLE
[master] assorted fixes for vampire macros

### PR DESCRIPTION
**Pull request by xeno-by**
Rebased version of https://github.com/scala/scala/pull/2902

### CODE REVIEW

**Comment by xeno-by** [comment]
@retronym This is essentially what we discussed on the reflection meeting, with the changes spanning only 4 lines. Can we have an lgtm?

**Comment by adriaanm** [comment]
A code comment to explain the irregularity for wildcard-parent structural types would be good.

**Comment by xeno-by** [comment]
@adriaanm Would this work?

**Comment by adriaanm** [comment]
That works, thanks. Thinking about it some more, the ad-hoc nature makes me a bit uneasy about making the HasMember a bit leakier, and the asymmetry between "regular" subtyping and subtyping to find members.

I was going to suggest making `object HasMember` an extractor:

```
    def unapply(pt: Type): Option[Name] = pt match {
      case RefinedType(List(WildcardType), decls) =>
        decls.toList match {
          case List(sym) => Some(sym.name)
          case _ => None
        }
    }
```

and replace `sym.isOnlyRefinementMember && sym.info != WildcardType` by `HasMember.unapply(tp2).isEmpty`, except `tp2` isn't known in specializesSym.

Backtracking all the way to thirdTry in isSubType, I wonder if it would be worthwhile to special-case the HasMember case there.

I'd love to hear @retronym and @paulp's thoughts before merging.

**Comment by paulp** [comment]
I agree that specializesSym seems awfully late to the party. I wouldn't let it get out of isSubType*.

**Comment by xeno-by** [comment]
Redid and reopened the pull request

**Pull request closed without merging**
