### PR TITLE
fixes the unchecked warning in quick.comp

### PR DESCRIPTION
**Pull request by xeno-by**
All those months when I thought it was yet another spurious error
in the new pattern matcher...

### CODE REVIEW

**Comment by paulp** [comment]
Hey,  I didn't call it [the world's most exciting trivial fix](https://issues.scala-lang.org/browse/SI-6338) for nothing.

**Comment by paulp** [comment]
....and there it is. Jenkins doesn't go back far enough for you to see I failed the same way about 500 pull requests ago.  https://scala-webapps.epfl.ch/jenkins/job/pr-rangepos/582/console (broken)

**Comment by xeno-by** [comment]
If you don't mind, I'll keep this hanging and will resubmit it later with the world's most exciting trivial fix.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by retronym** [comment]
Closing until the range pos fix is incorporated.

**Comment by xeno-by** [comment]
I've removed the workaround and suggest that we keep this hanging. Once the range pos fix is incorporated in 2.10.x, we can do a rebuild-all, it will pass, and then we can merge.

**Comment by xeno-by** [comment]
The error is expected. Waiting for https://github.com/scala/scala/pull/1704 to be merged. Afterwards a simple pleze rebuild all will be enough.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Ah I see the problem. `2.10.0-wip` hasn't yet been merged into `2.10.x`.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Pull request merged**
