### PR TITLE
SI-7961 Fix false positive procedure warnings

### PR DESCRIPTION
**Pull request by soc**
Two issues are fixed in this commit:
- `def foo: Unit` was detected as missing a return type
- The warning was emitted for constructors, but
  `def this(...): Unit = ...` is not valid Scala syntax

### CODE REVIEW

**Comment by soc** [comment]
Review by @adriaanm, please!

**Comment by adriaanm** [comment]
PLS REBUILD ALL

Sorry, the partest integration fail is my bad. Fixed by https://github.com/scala/jenkins-scripts/commit/766003ba7fbc94a76971018a282b9cbdd47d6df8. When #3129 was merged, I had to update partest, but forgot to bump the tag of partest against which we integrate.

I've rebuilt the pr-scala-integrate-partest job manually and it succeeded (see https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-partest/)

Should be all green soon!

**Comment by adriaanm** [comment]
Looks like something's wrong with the scripts that run the test. Stability cannot be affected by this PR. Investigating.

**Comment by adriaanm** [comment]
LGTM -- the stability tests fails because I was too eager in skipping locker
That's fine for running the test suite etc, but the stability test needs an additional iteration of building the compiler with itself. The goal is to spin this off to a parallel job.

**Comment by adriaanm** [comment]
I've disabled the stability test for now, will create a separate job soon. Not too worried -- stability test rarely fails anyway.

**Comment by adriaanm** [comment]
PLS REBUILD ALL

**Pull request merged**
