### PR TITLE
SI-6644 Account for varargs in extmethod forwarder

### PR DESCRIPTION
**Pull request by retronym**
Which sounded difficult, so instead I offshored the work
to the friendly republic of `TreeGen`.

Review by @paulp for content, @jsuereth for merge target.

It doesn't seem different from the multitude of prior "value classes + X
are broken" bugs that blocked earlier RCs.

### CODE REVIEW

**Comment by retronym** [comment]
:cat: https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/661/console

**Comment by paulp** [comment]
Always a thrill to see someone daring to reuse code. Lgtm.

**Comment by paulp** [comment]
irony: mkForwarder had zero callers before this commit. So I guess that isn't "reusing code" so much as it is "using code."

**Comment by retronym** [comment]
Double dose: it was added in that way originally in 2008 (562647a) by the author of the code I updated to use it. Prescient or what!

**Comment by jsuereth** [comment]
LGTM

**Pull request merged**
