### PR TITLE
SI-4695, package object separate compilation.

### PR DESCRIPTION
**Pull request by paulp**
The mechanism being used to notice when a package object
is being compiled from source does not appear to work at all.
I applied a different mechanism, which does appear to.

### CODE REVIEW

**Comment by retronym** [comment]
The test case doesn't exercise the part that logs `Unlinking...`. When is that triggered?

```
qbin/scalac sandbox/test.scala && rm pack1/T.class && qbin/scalac -Ylog:all sandbox/test.scala 2>&1 | egrep 'forcing|Unlinking|Early load'
[log <no phase>] forcing info of package scala to ensure there's no source.
[log <no phase>] forcing info of package reflect to ensure there's no source.
[log <no phase>] forcing info of package runtime to ensure there's no source.
[log <no phase>] forcing info of package collection to ensure there's no source.
[log namer] forcing info of package pack1 to ensure there's no source.
[log namer] Early load of source symbol for class T with file sandbox/test.scala
[log packageobjects] forcing info of package continuations to ensure there's no source.
[log typer] forcing info of package api to ensure there's no source.
[log typer] forcing info of package runtime to ensure there's no source.
[log typer] forcing info of package immutable to ensure there's no source.
[log erasure(->posterasure ->explicitouter ->parser)] forcing info of package parallel to ensure there's no source.
[log erasure(->posterasure ->explicitouter ->parser)] forcing info of package mutable to ensure there's no source.
[log erasure(->posterasure ->explicitouter ->typer ->parser)] forcing info of package generic to ensure there's no source.
[log erasure(->posterasure ->typer ->parser)] forcing info of package xml to ensure there's no source.
[log jvm] forcing info of package meta to ensure there's no source.
```

Could you share any insights you gleaned via the code- and commit- comments? I still have a lot of trouble in this part of the code.

**Comment by paulp** [comment]
I can't speak with enormous authority right now because here's when I actually wrote this patch:

```
 commit e37d022d5e (conifer/issue/4695)
 Author: Paul Phillips <paulp@improving.org>
 Date:   7 months ago

     Fix for SI-4695, package object separate compilation.
```

And it sat there because I wasn't up for coming up with a test. Then a few months later you used your magic do-what-I-need powers and attached a test case to the ticket, and then a few months after that I saw it.

I will have to find some time with this and with the remainder of the relevant work to summarize/explain it properly. Hopefully I can get through one day this week without having half of it derailed with all-new adventures like the stupid abstract companions.

**Comment by JamesIry** [comment]
SI-5954 is related. Here's some test code that reproduces that problem. Does it get fixed by this patch?

```
import scala.tools.partest._

object Test extends DirectTest {
  def code = ???

  def problemCode = """
    package object A {
      class B
      object B
      case class C()
    }
  """

  def compileProblemCode() = {
    val classpath = List(sys.props("partest.lib"), testOutput.path) mkString sys.props("path.separator")
    compileString(newCompiler("-cp", classpath, "-d", testOutput.path))(problemCode)
  }

  def show() : Unit = {
    for (i <- 0 until 2) {
      compileProblemCode()
      println(s"success ${i + 1}")
    }
  }
}
```

**Comment by retronym** [comment]
@JamesIry 

> Does it get fixed by this patch?

Nope:

```
uncaught exception during compilation: java.lang.AssertionError
java.lang.AssertionError: assertion failed: List(object package$B, object package$B)
    at scala.Predef$.assert(Predef.scala:179)
    at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:1669)
    at scala.reflect.internal.Symbols$ClassSymbol.companionModule0(Symbols.scala:2991)
    at scala.reflect.internal.Symbols$ClassSymbol.companionModule(Symbols.scala:2994)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1369)
    at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:119)
```

**Comment by paulp** [comment]
Yeah, it didn't get fixed by the rest of this patch either. I chased it pretty far. I need to get some input on names and symbols - I will try to summarize why this is so elusive today.

**Comment by paulp** [comment]
See https://groups.google.com/forum/#!topic/scala-internals/8bwPH8_65XE for elaboration.

**Comment by adriaanm** [comment]
unfortunately, this didn't get the LGTM in time
also, weren't we targeting 2.11 for this?

**Comment by paulp** [comment]
It started out as a fairly small patch for a fairly widespread issue, so I targeted 2.10. These days it has surely become 2.11 material.

**Comment by paulp** [comment]
Will reopen down the road for 2.11.

**Pull request closed without merging**
