### PR TITLE
reformulation of odersky/topic/pickledflags

### PR DESCRIPTION
**Pull request by paulp**
This is a 2.10.x-resolved version of https://github.com/scala/scala/pull/880 .

### CODE REVIEW

**Comment by odersky** [comment]
Thanks for the fix. I managed to pull 2.10.x now, but am still testing. Did you add the assert you proposed. I think that would be useful.

**Comment by paulp** [comment]
I did.  I also removed the special-casing of EXISTENTIAL in unpickler.

**Comment by adriaanm** [comment]
tested in https://scala-webapps.epfl.ch/jenkins/view/pr-validators/job/pr-scala-testsuite-linux-opt/508/consoleFull

**Comment by gkossakowski** [comment]
The assert addition is well-hidden in the merge commit:
https://github.com/paulp/scala/commit/30041d29545fc0596be6192882747c48f9b821e3#L31R294

In the future let's have a separate commit for that.

Other than that late(?) LGTM from me. Thanks!

Now I need to verify that specialization issue is gone.

**Pull request merged**
