### PR TITLE
Issue/si 4287

### PR DESCRIPTION
**Pull request by dotta**
This is a rework of https://github.com/scala/scala/pull/3210

review by @retronym, @densh

### CODE REVIEW

**Comment by dotta** [comment]
PLS REBUILD/pr-scala@7f4720c

**Comment by dotta** [comment]
PLS REBUILD/pr-scala@ccacb06

**Comment by dotta** [comment]
The validator job is failing for 4adee6ba51fd917e613a6ca696b268f57b797b29, but I really don't think the failure is due to my changes (in fact, the same test doesn't fail when I run it locally using the following command `SCALAC_OPTS="-Yrangepos" ./test/partest test/files/run/reflection-sync-potpourri.scala`).

Could somone have a look at it, please?

Below follows the reported error:

> +Exception in thread "Reflector-835" scala.reflect.internal.FatalError: unsupported completer: java.lang.reflect.AccessibleObject
> -        with java.lang.reflect.GenericDeclaration
> -        with java.lang.reflect.Member {

**Comment by dotta** [comment]
Let's give it another try (really don't know what else I should do)

PLS REBUILD/pr-scala@4adee6b

**Comment by adriaanm** [comment]
The rebuild fixed the fail in 4adee6b (never seen that error before!), but there's an earlier failure that should be resolved by https://github.com/scala-ide/uber-build/pull/26

**Comment by retronym** [comment]
```
% diff /localhome/jenkins/a/workspace/pr-scala-rangepos/scala/test/files/run/reflection-sync-potpourri-run.log /localhome/jenkins/a/workspace/pr-scala-rangepos/scala/test/files/run/reflection-sync-potpourri.check--- empty
+++ reflection-sync-potpourri-run.log
@@ -1,0 +1,84 @@
+Exception in thread "Reflector-835" scala.reflect.internal.FatalError: unsupported completer: java.lang.reflect.AccessibleObject
+        with java.lang.reflect.GenericDeclaration
+        with java.lang.reflect.Member {
+  private var clazz: java.lang.Class[_]
+  private var slot: Int
+  private var name: java.lang.String
+  private var returnType: java.lang.Class[_]
+  private var parameterTypes: Array[java.lang.Class[_]]
+  private var exceptionTypes: Array[java.lang.Class[_]]
+  private var modifiers: Int
+  private var signature: java.lang.String
+  private var genericInfo: sun.reflect.generics.repository.MethodRepository
+  private var annotations: Array[Byte]
+  private var parameterAnnotations: Array[Byte]
+  private var annotationDefault: Array[Byte]
+  private var methodAccessor: sun.reflect.MethodAccessor
+  private var root: java.lang.reflect.Method
+  private var securityCheckCache: java.lang.Class[_]
+  private var securityCheckTargetClassCache: java.lang.Class[_]
+  private var declaredAnnotations: java.util.Map[java.lang.Class[_],java.lang.annotation.Annotation]
+  def invoke(x$1: Any,x$2: <repeated...>[java.lang.Object]): java.lang.Object
+  def equals(x$1: Any): Boolean
+  def toString(): java.lang.String
+  def hashCode(): Int
+  def getModifiers(): Int
+  def getName(): java.lang.String
+  private def declaredAnnotations(): java.util.Map[java.lang.Class[_],java.lang.annotation.Annotation]
+  def getAnnotation[T <: java.lang.annotation.Annotation](x$1: java.lang.Class[T]): T
+  def getDeclaredAnnotations(): Array[java.lang.annotation.Annotation]
+  def getDeclaringClass(): java.lang.Class[_]
+  private def getFactory(): sun.reflect.generics.factory.GenericsFactory
+  private def getGenericInfo(): sun.reflect.generics.repository.MethodRepository
+  private def getGenericSignature(): java.lang.String
+  def getParameterTypes(): Array[java.lang.Class[_]]
+  def getReturnType(): java.lang.Class[_]
+  def getTypeParameters(): Array[java.lang.reflect.TypeVariable[java.lang.reflect.Method]]
+  def isSynthetic(): Boolean
+  private[package reflect] def copy(): java.lang.reflect.Method
+  def toGenericString(): java.lang.String
+  private def acquireMethodAccessor(): Unit
+  def getDefaultValue(): java.lang.Object
+  def getExceptionTypes(): Array[java.lang.Class[_]]
+  def getGenericExceptionTypes(): Array[java.lang.reflect.Type]
+  def getGenericParameterTypes(): Array[java.lang.reflect.Type]
+  def getGenericReturnType(): java.lang.reflect.Type
+  private[package reflect] def getMethodAccessor(): sun.reflect.MethodAccessor
+  def getParameterAnnotations(): Array[Array[java.lang.annotation.Annotation]]
+  def isBridge(): Boolean
+  def isVarArgs(): Boolean
+  private[package reflect] def setMethodAccessor(x$1: sun.reflect.MethodAccessor): Unit
+  def <init>(): java.lang.reflect.Method
+} of class class scala.reflect.internal.Types$ClassInfoType for symbol java.lang.reflect.Method
+   at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:55)
+   at scala.reflect.internal.Symbols$class.shouldTriggerCompleter(Symbols.scala:65)
+   at scala.reflect.runtime.JavaUniverse.scala$reflect$runtime$SymbolTable$$super$shouldTriggerCompleter(JavaUniverse.scala:11)
+   at scala.reflect.runtime.SymbolTable$class.shouldTriggerCompleter(SymbolTable.scala:44)
+   at scala.reflect.runtime.JavaUniverse.shouldTriggerCompleter(JavaUniverse.scala:11)
+   at scala.reflect.internal.Symbols$Symbol.needsInitialize(Symbols.scala:1512)
+   at scala.reflect.internal.Symbols$Symbol.hasFlag(Symbols.scala:618)
+   at scala.reflect.internal.Symbols$Symbol.hasFlag(Symbols.scala:621)
+   at scala.reflect.internal.Symbols$ClassSymbol.isPackageClass(Symbols.scala:3042)
+   at scala.reflect.internal.Types$TypeRef$.apply(Types.scala:2423)
+   at scala.reflect.internal.Types$class.typeRef(Types.scala:3476)
+   at scala.reflect.internal.SymbolTable.typeRef(SymbolTable.scala:14)
+   at scala.reflect.internal.Symbols$TypeSymbol.newTypeRef(Symbols.scala:2874)
+   at scala.reflect.internal.Symbols$TypeSymbol.typeConstructor(Symbols.scala:2896)
+   at scala.reflect.internal.Symbols$SymbolContextApiImpl.toTypeConstructor(Symbols.scala:126)
+   at scala.reflect.internal.Symbols$TypeSymbol.toTypeConstructor(Symbols.scala:2822)
+   at Test$$anonfun$2$$typecreator1$1.apply(reflection-sync-potpourri.scala:13)
+   at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe$lzycompute(TypeTags.scala:231)
+   at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe(TypeTags.scala:231)
+   at scala.reflect.api.TypeTags$class.typeOf(TypeTags.scala:335)
+   at scala.reflect.api.Universe.typeOf(Universe.scala:61)
+   at Test$$anonfun$2.apply(reflection-sync-potpourri.scala:13)
+   at Test$$anonfun$2.apply(reflection-sync-potpourri.scala:13)
+   at Test$.force(reflection-sync-potpourri.scala:19)
```

@xeno-by Looks like we've got another reflection sync bug. 

@dotta I think you can ignore that failure in this PR, and a rebuild _should_ fix it.

**Comment by xeno-by** [comment]
Thanks for reporting!

**Comment by dotta** [comment]
PLS REBUILD/pr-scala@ccacb06

**Comment by dotta** [comment]
All commits succeed (the build kitty seems to be confused about 4adee6ba51fd917e613a6ca696b268f57b797b29, but if you click on the related link all jobs are green).

**Comment by adriaanm** [comment]
PLS SYNCH

**Comment by dotta** [comment]
ping @retronym @densh - Still need someone to look at this ;-)

**Comment by dotta** [comment]
Please, can someone have a look at this? \cc @adriaanm

**Comment by retronym** [comment]
LGTM. I really appreciate the step-by-step presentation of the change and tests and detailed comments. And its so great having scala-refactoring in our PR validation chain so we don't have to be quite so paranoid about positions changes!

**Comment by dotta** [comment]
Whohooo! :clap: Thanks Jason!

**Pull request merged**
