### PR TITLE
2.11 is out now

### PR DESCRIPTION
**Pull request by jaceklaskowski**

### CODE REVIEW

**Comment by retronym** [comment]
Do you know what URL the gh-pages branch is published?

**Comment by retronym** [comment]
Found it here: http://docs.scala-lang.org/scala/

**Comment by retronym** [comment]
@adriaanm Is this page maintained? I've never seen it before.

**Comment by adriaanm** [comment]
We should probably remove it and move stuff to the real docs.scala-lang.org site.

**Pull request merged**
