### PR TITLE
Making VectorIterator a final class

### PR DESCRIPTION
**Pull request by viktorklang**
Also making the private[this] vars final

### CODE REVIEW

**Comment by joshlemer** [comment]
What does `final var` do, when the class is final?

**Comment by viktorklang** [comment]
@joshlemer I don't want the fields final-ness to be linked to the final-ness of the class, esp. since I assume that most un-final-ing of classes happen without knowing which of the fields or accessors etc should still be final?

**Review by joshlemer — APPROVED** [review]

**Comment by szeiger** [comment]
This could easily go through a deprecation cycle with `@deprecatedInheritance` instead of making a breaking change. Or go straight to `@deprecated`? Does the class have to be public at all?

**Comment by adriaanm** [comment]
In addition to addressing Stefan's question, this will also need a rebase.

**Comment by lrytz** [comment]
ping @viktorklang

**Comment by viktorklang** [comment]
@lrytz @szeiger @adriaanm Ok, so consensus is to not make the class itself final but instead make it deprecated?

**Comment by szeiger** [comment]
Since `Vector` itself is final, I can't think of a compelling reason for `VectorIterator` to be public.

**Comment by viktorklang** [comment]
@szeiger So you want me to make it private([this])?

**Comment by szeiger** [comment]
No, let's just deprecate it for now. There's no  need do this in one step without deprecation.

**Comment by viktorklang** [comment]
@szeiger Vector.iterator returns VectorIterator (type)

**Comment by SethTisue** [comment]
> @szeiger Vector.iterator returns VectorIterator (type)

that doesn't seem desirable to expose

**Comment by viktorklang** [comment]
@SethTisue Agreed. Is that safe/OK to change to Iterator without some sort of deprecation cycle?

**Comment by viktorklang** [comment]
@SethTisue Sorry, I spoke too soon, after a rebase that has been corrected on 2.13.x
So should I deprecate the VectorIterator class or just make it private?

**Comment by viktorklang** [comment]
@szeiger @SethTisue Changed to deprecating the class instead of making it final. Please review.

**Comment by SethTisue** [comment]
@szeiger you can make the call :-)

**Review by szeiger — APPROVED** [review]

**Comment by julienrf** [comment]
For information, making `VectorIterator` private is not convenient for `scala-parallel-collection`, which provides a `ParVector` whose iterator extends `VectorIterator` (and uses its internals). The only warning-free alternative that I see is to duplicate a lot of code (`VectorIterator` **and** `VectorPointer`).

**Comment by SethTisue** [comment]
@julienrf but `private[scala]` will be okay, right?

**Comment by julienrf** [comment]
Sure, even `private[collection]` works.

**Pull request merged**
