### PR TITLE
SI-6692 pickle one more flag bit: EXISTENTIAL

### PR DESCRIPTION
**Pull request by adriaanm**
before, PickledFlags & EXISTENTIAL == 0, so that an existential symbol would
lose the EXISTENTIAL bit when pickled, causing spurious incremental recompiles,
as pickled information and type-checking-from-source-based information differed

pickling this additional bit should be a compatible change, as older versions (pre-2.9.3)
will simply mask out the extra flag bits pickled as of now (2.9.3) so that their behavior
is not affected -- newer versions will see more flags, which might cause regressions,
but it's also the only way to fix SI-6692

this obviates the need to set the existential flag when unpickling an existential type's params

this is the smallest backport of a9b85dbaad and 3e2c31fbeb that I could think of

as 2.9 is in maintenance mode, I don't want to invest in testing infrastructure to test the pickler,
however, the fix is tested by the incremental compiler test 'inc-pickled-existential' in sbt

review by @paulp, still taking feasible testing-suggestions

### CODE REVIEW

**Comment by adriaanm** [comment]
genuine failure -- that'll teach me and my "what could possibly go wrong it's just one bit"-attitude

**Comment by paulp** [comment]
Ready for that FINAL REBASE?

**Comment by adriaanm** [comment]
rangepos has been failing on 2.9.x with some finality for a while now (where failing means "would have been failing, had it been running"), will look into that independently

**Comment by gkossakowski** [comment]
It's kitten's problem. Rangepos are _always_ failing on 2.9.x branch...

**Comment by gkossakowski** [comment]
Also, how about test?

**Comment by adriaanm** [comment]
i explained the absence of test in the commit message
i tried the scalap approach, but it won't fly

**Comment by adriaanm** [comment]
the rangepos failure is our problem -- not the kitten's.. there's a real bug causing that NPE, it's just going to be fun to diagnose since it's been broken for a while and jenkins hasn't been running that job on 2.9

**Comment by adriaanm** [comment]
i also updates the issue on jira to explain how it's tested indirectly in sbt

**Comment by gkossakowski** [comment]
I always thought rangepos tests are just broken when kitten tries to run them. I'm pretty sure that's what I heard from @jsuereth.

Oh, I noticed you saying:

> as 2.9 is in maintenance mode, I don't want to invest in testing infrastructure to test the pickler,
> however, the fix is tested by the incremental compiler test 'inc-pickled-existential' in sbt

Two questions then:
1. Do we have test in 2.10.x for that?
2. What happened to idea of using scalap for testing it?

**Comment by adriaanm** [comment]
i locally checked out the 2.9.x branch and ran the rangepos test suite using the jenkins-script used by jenkins

I went as far back as f0f0dfd9a3 (I also tried all the 2.9.x tags -- they all fail in the same way):

```
quick.lib:
    [mkdir] Created dir: /Users/adriaan/git/scala-build/build/quick/classes/library
    [javac] Compiling 25 source files to /Users/adriaan/git/scala-build/build/quick/classes/library
    [javac] Compiling 41 source files to /Users/adriaan/git/scala-build/build/quick/classes/library
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
[scalacfork] Compiling 649 files to /Users/adriaan/git/scala-build/build/quick/classes/library
[scalacfork] Exception in thread "main" java.lang.NullPointerException
[scalacfork]    at scala.tools.nsc.Global$Run.compileLate(Global.scala:980)
[scalacfork]    at scala.tools.nsc.interactive.Global$$anon$3.enterToplevelsFromSource(Global.scala:176)
[scalacfork]    at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$3.apply(SymbolLoaders.scala:167)
[scalacfork]    at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$3.apply(SymbolLoaders.scala:162)
```

**Comment by hubertp** [comment]
They all fail for 2.9.x. It is nothing with your commit. I think there were a number of rangepos commits which weren't backported to 2.9.x and even if you fix this one, others will show up certainly. I believe @dragos was ok with that.

**Comment by adriaanm** [comment]
Ok, thanks @hubertp -- I wasn't aware. The essence is that it works on the IDE. We shouldn't invest in 2.9.x any more than necessary, so I'm okay with the status quo.

**Comment by paulp** [comment]
LGTM.

**Comment by paulp** [comment]
And my testing suggestion is to forget it and put your testing energy into 2.10+, where there is plenty to do.

**Pull request merged**
