### PR TITLE
Deprecate auto-application of (non-Java-defined) methods with a single empty parameter list

### PR DESCRIPTION
**Pull request by dwijnand**
Auto-application is dropped in Scala 3:
https://dotty.epfl.ch/docs/reference/dropped-features/auto-apply.html

So it must be deprecated in 2.13 first.

Strongly related to deprecating overriding nullary (and the inverse, overriding nilary): #8846.

## Example

```
$ scala -deprecation -e 'println'
...
warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method println,
or remove the empty argument list from its definition (Java-defined methods are exempt).
In Scala 3, an unapplied method like this will be eta-expanded into a function.
println
^
```

## How to fix

It is recommended to add the missing parens:

```
$ scala -deprecation -e 'println()'
```

The change can be made manually or by using scala-rewrites' [`ExplicitNonNullaryApply`](https://github.com/scala/scala-rewrites/blob/master/rewrites/src/main/scala/fix/scala213/ExplicitNonNullaryApply.scala).

## How to suppress

Since 2.13.2, Scala offers [`-Wconf:...` and `@nowarn`](https://github.com/scala/scala/pull/8373) for warning suppression. You can suppress the new warning globally by passing `-Wconf:cat=deprecation&msg=Auto-application:silent` to the compiler, or you can suppress it locally by adding `@nowarn("cat=deprecation&msg=Auto-application")` at the call site.

### CODE REVIEW

**Comment by lrytz** [comment]
Is there (or could we write) a scalafix rule supporting this change? Scalafix exists for 2.13.1.

**Comment by SethTisue** [comment]
Let's leave this one for 2.13.3.

**Comment by dwijnand** [comment]
> Is there (or could we write) a scalafix rule supporting this change?

https://github.com/scala/scala-rewrites/pull/14

**Review by SethTisue — APPROVED** [review]
force-pushed to bump the deprecated-since from 2.13.2 to 2.13.3. let's merge as soon as CI likes it again

**Comment by SethTisue** [comment]
@dwijnand in the PR description, can you add the `-Wconf`/`@nowarn` incantations for suppressing this? (for inclusion in the release notes as well)

**Pull request merged**
