### PR TITLE
[rebase] blackbox and whitebox macros

### PR DESCRIPTION
**Pull request by adriaanm**
rebase of #3001

Documentation: http://docs.scala-lang.org/overviews/macros/blackbox-whitebox.html
Depends on: https://github.com/scala/scala/pull/2994. 
Review: @retronym @adriaanm

### CODE REVIEW

**Comment by xeno-by** [comment]
@adriaanm Thanks! It is definitely progress, because judging from the compilation errors now it's definitely using a correct build of the compiler. 

The version of scala-reflect.jar is still old, though, which causes awkward messages like this one (<notype>'s are BlackboxContexts, I believe):

```
[error] /localhome/jenkins/a/workspace/pr-scala-integrate-partest/scala-partest/src/main/scala/scala/tools/partest/package.scala:200: macro implementation has wrong shape:
[error]  required: (c: <notype>)(a: c.<none>[A]): c.<none>[A]
[error]  or      : (c: <notype>)(a: c.<none>[A]): c.<none>[A]
[error]  found   : (c: scala.reflect.macros.Context)(a: c.Expr[A])(implicit evidence$1: c.WeakTypeTag[A]): c.Expr[A]
[error] macro implementations cannot have implicit parameters other than WeakTypeTag evidences
[error]   def trace[A](a: A) = macro traceImpl[A]
[error]       ^
```

**Comment by xeno-by** [comment]
@adriaanm As for this failure: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-test/3578/console, I will try to take a look in the evening or tomorrow in the morning.

**Comment by adriaanm** [comment]
Gah, yeah, I realized I "missed a spot"... Rebasing again.

**Comment by adriaanm** [comment]
I re-ran the partest integration against adriaanm/scala-partest master and it passed, so this is good to go once all of these jobs go green: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-partest/3395/console (up to 3399).

You can do this yourself with the new PR validation by forking scala/jenkins-scripts and fiddling with the settings (in this case in jobs/pr-scala-integrate-partest) and then hitting rebuild on the failed jobs, changing the `scriptsRemote` parameter to your fork.

**Comment by adriaanm** [comment]
LGTM

Thanks, @xeno-by, this was very nice to review!
I think this is ready to go as-is, but I would appreciate some boy scout duty over at scala/scala-partest to remove the traceImpl macro there, as it seems this needs to stay with the compiler. EDIT: [Done](https://github.com/scala/scala-partest/pull/10)

**Comment by adriaanm** [comment]
I amended the first commit a little to fix the build so that partest-extras is compiled with quick, so that BlackboxContext is available to the trace macro in scala.tools.partest.Util.

**Comment by adriaanm** [comment]
Would be great to have a mechanism to configure PR validation from the PR so we could override a property. Here, we'd say: "partest.head=master" (rather than the default "v${partest_version_number}")

**Pull request merged**
