### PR TITLE
remove legacy bincompat stuff in two places

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @lrytz

**Comment by lrytz** [comment]
LGTM. Could have been a single commit for me :)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/224/console shows:

```
java.lang.NoSuchMethodError: scala.collection.immutable.Stream.filter(Lscala/Function1;)Lscala/collection/immutable/Stream;
    at scala.tools.partest.nest.PathSettings$.findJar(PathSettings.scala:31)
```

This is because the binary incompatible change to Stream broke the partest we're using.

As discussed with @lrytz, the fix steps are:
1. Patch partest so it works with both M2 and M2+4640. (In this case, maybe use Iterator instead or cast to TraversableLike, something like that.)
   - To test the patched partest locally: `++2.12.0-M2 sbt publishM2` in the scala-partest checkout, then uncomment https://github.com/scala/scala/blob/2.11.x/build.xml#L367 and change versions.properties
2. Release the patched partest.
3. In this PR, change version.properties to use the new partest.
4. (optional) If we don't like the way we had to hack partest, then wait until 2.12.0-M3 (with 4640) is out and make another new partest that depends on it and has the version of the code we like best.

**Comment by SethTisue** [comment]
afaict 1.0.9 was published successfully (https://travis-ci.org/scala/scala-partest/jobs/71990071) but just isn't on maven central yet (https://repo1.maven.org/maven2/org/scala-lang/modules/scala-partest_2.12.0-M2/)

**Pull request merged**
