### PR TITLE
ExistentialTypeTree.whereClauses are now MemberDefs

### PR DESCRIPTION
**Pull request by xeno-by**
Today’s flight back to Lausanne wasn’t as productive as the recent flight
to Minsk (https://github.com/scala/scala/pull/3305), but I noticed
one minor thingie: ExistentialTypeTree had an imprecise type specified
for its whereClauses. This is now fixed.

I didn’t increment PickleFormat.*Version numbers, because this change
introduces only a miniscule incompatibility with what would have been
a meaningless and most likely crash-inducing pickle anyway.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
LGTM

**Comment by xeno-by** [comment]
@retronym I've just updated the changes to the parser. Could you take a look again?

**Comment by retronym** [comment]
What source code leads to `refinement()` yielding `EmptyTree`? Is it okay to filter that out by way of the `flatMap`?

**Comment by xeno-by** [comment]
@retronym Only parse errors manifest themselves as empty trees, so it's okay to filter those out. Added a comment that explains that.

**Pull request merged**
