### PR TITLE
[backport] SI-6969, mishandling of SoftReferences in method cache.

### PR DESCRIPTION
**Pull request by soc**
More interesting to test than it was to fix. The soft
reference is now dereferenced once, the locally stored
underlying value ascertained to be non-null, and the
remainder of the references to the value use the local var.

The enclosed test reliably NPEs without this patch.

### CODE REVIEW

**Comment by soc** [comment]
@paulp I backported it as mentioned in https://issues.scala-lang.org/browse/SI-6969

I guess now the people in charge need to decide whether it is important enough. :-)

Backport of https://github.com/scala/scala/pull/1902

**Comment by soc** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Thanks for doing the backport! Unfortunately, the milestone was somehow set to 2.10.1-RC1, so I didn't see this when I cut  2.9.3-RC2. Apologies.

**Comment by JamesIry** [comment]
@adriaanm turns out the failure was genuine so it wouldn't have made it anyway.

**Comment by JamesIry** [comment]
Never mind, it's a test problem in 2.9.x and can be ignored.

**Comment by adriaanm** [comment]
LGTM. I'll merge it for the next 2.9.x release.

**Pull request merged**
