### PR TITLE
Remove "underlying" from being on primitive numbers

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
This fails with a _bunch_ of tests that look like this

```
[test] [error] Test scala.tools.nsc.typechecker.ImplicitsTests.implicitInfoHashCode failed: scala.MatchError: <error> (of class scala.reflect.internal.Types$ErrorType$), took 0.036 sec
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.fixupAsAnyTrait(Definitions.scala:279)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$ComparableClass$1(Definitions.scala:403)
[test] [error]     at scala.reflect.internal.Symbols$Symbol.modifyInfo(Symbols.scala:1569)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.ComparableClass$lzycompute(Definitions.scala:403)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.ComparableClass(Definitions.scala:403)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.hijackedCoreClasses$lzycompute(Definitions.scala:1491)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.hijackedCoreClasses(Definitions.scala:1490)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1500)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1500)
[test] [error]     at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1556)
[test] [error]     at scala.tools.nsc.Global$Run.<init>(Global.scala:1189)
[test] [error]     at scala.tools.nsc.typechecker.ImplicitsTests.implicitInfoHashCode(Implicits.scala:17)
```

I don't know why, or how to fix it.

**Comment by lrytz** [comment]
After trying for a while with bootstrapping, I found out it's actually easy to reproduce the problem here: just run `sbt test` on this PR (no need for bootstrapping). The difficulty is that the problem doesn't show up when running tests individually. There's some cross-talk between the toolbox compiler used in `PrimitiveNumberTest` and the compiler used in other tests, for example `NullnessAnalyzerTest`. I don't have time to figure out what's goin on, so I suggest to simply rewrite your test. For example a partest neg test.

**Comment by dwijnand** [comment]
Thanks, Lukas...  Shame I was trying to be a good citizen by using `RunTesting`.  I guess by being an early adopter I found an edge case.

**Review by Ichoran — APPROVED** [review]
Good to get rid of that, thanks!

**Pull request merged**
