### PR TITLE
SI-6424 Scaladoc: Use mapNodes.get(_) to avoid NoSuchElementException

### PR DESCRIPTION
**Pull request by kzys**
Use mapNodes.get(_) instead of mapNodes(_) to avoid NoSuchElementException.

### CODE REVIEW

**Comment by kzys** [comment]
Review by @heathermiller or @sjrd

**Comment by adriaanm** [comment]
PLS REBUILD ALL
NOLITTER!

**Comment by heathermiller** [comment]
Hmm, no good: 

```
Resolving [8bdac1cdd60b73ff7e12fd2b556355fa10343e2d/lib/scala-library-src.jar]
(23) Failed writing body
Error downloading /home/jenkins/.sbt/cache/scala/8bdac1cdd60b73ff7e12fd2b556355fa10343e2d/lib/scala-library-src.jar: response code: 200
http://repo.typesafe.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/8bdac1cdd60b73ff7e12fd2b556355fa10343e2d/lib/scala-library-src.jar
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by heathermiller** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
merging so that it can go into 2.10.2

**Pull request merged**
