### PR TITLE
remove Ant support, remove Eclipse support

### PR DESCRIPTION
**Pull request by SethTisue**
remove Ant tasks for building user code using Ant.  this is
now historical. hard to be sure absolutely nobody is using it anymore,
but regardless, it ought to be a separate project, if anyone still
wants it to exist in 2.13+ world.

support for building Scala itself using Eclipse is removed and
replaced with a note in the readme that says "Support for Eclipse has
decayed and been removed, but could be resurrected by a volunteer"

### CODE REVIEW

**Comment by SethTisue** [comment]
I have a sinking feeling somebody is going to come up with a reason the Ant stuff can't or shouldn't be removed?

**Comment by SethTisue** [comment]
this would fix scala/bug#10335, but that's gravy, the main motivation here is just general cruft reduction.

**Comment by SethTisue** [comment]
```
[info] 	delivering ivy file to /home/jenkins/workspace/scala-2.13.x-validate-publish-core/target/scala-dist/ivy-2.13.0-pre-e9b1730-SNAPSHOT.xml
[error] /home/jenkins/workspace/scala-2.13.x-validate-publish-core/src/manual/scala/tools/docutil/ManMaker.scala:9: object apache is not a member of package org
[error] import org.apache.tools.ant.Task
[error]            ^
[error] /home/jenkins/workspace/scala-2.13.x-validate-publish-core/src/manual/scala/tools/docutil/ManMaker.scala:13: not found: type Task
[error] class ManMaker extends Task {
[error]                        ^
[error] two errors found
```

**Comment by SethTisue** [comment]
this is now ready for review. @lrytz want to take the first look?

**Review by lrytz — APPROVED** [review]

**Comment by lrytz** [comment]
I googled a bit to see if there's anything recent on scala+ant, this [post is from July 2017](https://alvinalexander.com/scala/how-build-scala-project-with-apache-ant), but seems to be taken from his 2013 book. Also [stackoverflow for scala+ant](https://stackoverflow.com/questions/tagged/scala+ant?sort=newest&pageSize=30) seems to be calm. So 👍 from me.

**Comment by lrytz** [comment]
@SethTisue rebased to fix conflict with https://github.com/scala/scala/pull/6354 and pushed to your branch

**Comment by SethTisue** [comment]
@adriaanm wdyt?

**Comment by SethTisue** [comment]
discussion thread at https://users.scala-lang.org/t/scala-2-13-0-ant-support/4694/7

**Comment by SethTisue** [comment]
the removed code is now here: https://github.com/cigaly/scala-ant, thanks to @cigaly

**Pull request merged**
