### PR TITLE
Revert #2957

### PR DESCRIPTION
**Pull request by huitseeker**

### CODE REVIEW

**Comment by retronym** [comment]
I don't understand the reference in your comment to f6fcc4431f272c707d49de68add532c452dd4b0f.

**Comment by huitseeker** [comment]
@retronym That's an automated comment made by git when you revert a merge. It states the merge-base on which the merge was previously performed (which is indeed f6fcc44, hence, #2957 ws a change made "to" f6fcc44 - the master HEAD of the time). How would you like me to amend it ?

**Comment by retronym** [comment]
Okay, that explanation is enough.

**Comment by retronym** [comment]
LGTM. Look forward to sorting this out with more finesse before too long.

**Pull request merged**
