### PR TITLE
Fix up DEFAULTPARAM semantics.

### PR DESCRIPTION
**Pull request by paulp**
I foolishly believed the deprecation message on "hasDefaultFlag" which
suggested I use "hasDefault" instead. After lots of head scratching, I
hardened the semantics so it's like this:

```
 - A method parameter with a default value is PARAM | DEFAULTPARAM
 - A default getter for such a parameter is METHOD | DEFAULTPARAM
 - And "hasDefault" is has(DEFAULTPARAM) && has(PARAM | METHOD)
```

Why all the bonus logic, why not just hasFlag(DEFAULTPARAM)? For some reason
we have a handful of overloaded flags spanning uses which someone apparently
thinks can never intersect but I have not been so lucky overall. So since
DEFAULTPARAM is overloaded with TRAIT, unless we think it's fine that default
getters and method parameters with defaults will pose as traits all the time,
there has to be an anchor bit alongside it.

### CODE REVIEW

**Comment by paulp** [comment]
Review @retronym

**Comment by retronym** [comment]
Could you explain what was wrong/confusing before with a quick `:power` mode show?

Do we need a test to pin things down / document them?

**Comment by paulp** [comment]
hasDefaultFlag was only checking for DEFAULTPARAM; hasDefault was checking for both that and PARAM. One or more methods which was calling the deprecated hasDefaultFlag stopped working when I changed it over. So hasDefault had to either check for less or check for more - I opted for more so it doesn't go back to being indistinguishable from TRAIT.

I really do have to find a faster way through this territory or I'm going to throw up my hands.

**Comment by retronym** [comment]
Lgtm

**Pull request merged**
