### PR TITLE
Make WrappedString keep its self private

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by SethTisue** [comment]
confused... doesn't this just amount to a renaming of `self` to `unwrap`? does it matter?

**Comment by dwijnand** [comment]
No, this avoids that all `String`s get a `self` or an `unwrap` method, by using the fact that implicit conversions don't chain.

**Comment by SethTisue** [comment]
ah... (also, I didn't see the Slack thread until after my comment)

**Review by SethTisue — APPROVED** [review]
...and I see now that you added a test that makes sure the unwanted things don't compile

**Comment by dwijnand** [comment]
Yep!

**Pull request merged**
