### PR TITLE
use ne Nil for List end detection

### PR DESCRIPTION
**Pull request by feyman2016**
https://github.com/rorygraves/scalac_perf/issues/52

### CODE REVIEW

**Comment by szeiger** [comment]
Marking as WIP because it's not actually faster (yet?) according to the benchmarks over on https://github.com/rorygraves/scalac_perf/issues/52 and there's still ongoing discussion.

**Comment by lrytz** [comment]
We could also just add `override final def isEmpty = this eq Nil` to `List` (and remove the overrides in `::` / `Nil`). The JIT would then inline `isEmpty`.

**Comment by mkeskells** [comment]
I will have a look on my return. I have some ideas around this, and it relates to static final MODULE$ inlining

**Comment by lrytz** [comment]
I'll close this PR for now.

**Pull request closed without merging**
