### PR TITLE
SI-7356 - Source.mkString performs painfully slow (...)

### PR DESCRIPTION
**Pull request by Ichoran**
1. Wrote a custom mkString for BufferedSource.
2. Moved the logic for rescuing the iterator-buffered char out of
   BufferedLineIterator and into a private method in BufferedSource.

Speed test based on the one in the issue tracker (but written correctly)
indicates that performance is equal or better to getLines.  This resolves
SI-7356 in a minimal fashion.

### CODE REVIEW

**Comment by retronym** [comment]
LGTM. At last, a slurp! For future reference, it is recommended to name a reviewer as you submit the PR.

**Comment by gkossakowski** [comment]
Thanks.

**Comment by advancedxy** [comment]
@paulp @Ichoran hi, is there a new pr to change from charReader to allReader? 
In the scala 2.11.1 repl, I notice a bug due to this wrong code.

```
yexianjin@advancedxy's-pro:/Volumes/MacintoshHD/github/scala  git:(2.12.x) $ scala
Welcome to Scala version 2.11.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_55).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import scala.io.Source
import scala.io.Source

scala> val source = Source.fromFile("README.md","UTF-8");
source: scala.io.BufferedSource = non-empty iterator

scala> val content = source.mkString
content: String =
"his is the repository for the [Scala Programming Language](http://www.scala-lang.org).

  - [Report an issue](https://issues.scala-lang.org);
  - [Read about the development of the compiler and the standard library](http://docs.scala-lang.org/scala/);
  - [Check our Jenkins status](https://scala-webapps.epfl.ch/jenkins/);
  - [Download the latest nightly](https://scala-webapps.epfl.ch/jenkins/job/scala-nightly-main-master/ws/dists/latest/*zip*/latest.zip);
  - ... and contribute right here! Please, first read our [policy](http://docs.scala-lang.org/scala/pull-request-policy.html), our [development guidelines](CONTRIBUTING.md),
and [sign the contributor's license agreement](http://typesafe.com/contribute/cla/scala).
"

scala> content(0)
res0: Char = h

scala> val source = Source.fromFile("README.md","UTF-8"); val content = source.mkString
source: scala.io.BufferedSource = empty iterator
content: String =
"This is the repository for the [Scala Programming Language](http://www.scala-lang.org).

  - [Report an issue](https://issues.scala-lang.org);
  - [Read about the development of the compiler and the standard library](http://docs.scala-lang.org/scala/);
  - [Check our Jenkins status](https://scala-webapps.epfl.ch/jenkins/);
  - [Download the latest nightly](https://scala-webapps.epfl.ch/jenkins/job/scala-nightly-main-master/ws/dists/latest/*zip*/latest.zip);
  - ... and contribute right here! Please, first read our [policy](http://docs.scala-lang.org/scala/pull-request-policy.html), our [development guidelines](CONTRIBUTING.md),
and [sign the contributor's license agreement](http://typesafe.com/contribute/cla/scala).
"

scala> content(0)
res1: Char = T
```

use allReader should fix that.

**Comment by Ichoran** [comment]
@advancedxy - If you can file this as a bug on JIRA (https://issues.scala-lang.org), I'll fix it for 2.11.2.

**Comment by advancedxy** [comment]
hi, @Ichoran  I filed this on [JIRA](https://issues.scala-lang.org/browse/SI-8690).
I did want to fix it myself. But it will be great if you want to take it over. Hope it being fixed soon in the future versions.

**Pull request merged**
