### PR TITLE
Add second usage example for extending Value with attributes

### PR DESCRIPTION
**Pull request by Philippus**
closes https://github.com/scala/bug/issues/4803

### CODE REVIEW

**Comment by janekdb** [comment]
Checking the local build...

I am seeing a problem when pulling your branch on top of current 2.12 branch. Could you rebase?

**Comment by Philippus** [comment]
I think I did it :)

**Comment by janekdb** [comment]
image

Suggested changes,

1. Break apart these two example into two sections: Text introduction to example noting feature being illustrated then the example.

Motivation for example 1
Code for example 1
Motivation for example 2
Code for example 2

2. Drop wrapping of the existing example in `object Main extends App`.

Scaladoc examples should be executable in the console and dropping `object Main extends App` does not prevent this.

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

object Planet extends Enumeration {
  protected case class Val(name: String, mass: Double, radius: Double) extends super.Val(nextId, name) {
    def surfaceGravity: Double = Planet.G * mass / (radius * radius)
    def surfaceWeight(otherMass: Double): Double = otherMass * surfaceGravity
  }

  implicit def valueToPlanetVal(x: Value): Val = x.asInstanceOf[Val]
  val G: Double = 6.67300E-11
  val Mercury = Val("Mercury", 3.303e+23, 2.4397e6)
  val Venus = Val("Venus", 4.869e+24, 6.0518e6)
  val Earth = Val("Earth", 5.976e+24, 6.37814e6)
  val Mars = Val("Mars", 6.421e+23, 3.3972e6)
  val Jupiter = Val("Jupiter", 1.9e+27, 7.1492e7)
  val Saturn = Val("Saturn", 5.688e+26, 6.0268e7)
  val Uranus = Val("Uranus", 8.686e+25, 2.5559e7)
  val Neptune = Val("Neptune", 1.024e+26, 2.4746e7)
}
println(Planet.values.filter(_.radius > 7.0e6))

// Exiting paste mode, now interpreting.

warning: there was one feature warning; for details, enable `:setting -feature' or `:replay -feature'
Planet.ValueSet(Jupiter, Saturn, Uranus, Neptune)
defined object Planet
```

3. Reorder the examples

The new example is more complex so start with the original example.

**Comment by Philippus** [comment]
2. is done
3. does Scaladoc reverse the examples? In the code I used the proper order as far as I can tell. Looks like https://github.com/scala/bug/issues/10325 ?

**Comment by janekdb** [comment]
I had not noticed the use of ` @example`! This would account for the comma separating the examples. I was wondering where that came from.

I recommend generating the Scaladoc and reviewing it yourself. This is what I saw the first time,

image

The examples are in reverse of source code. I think that can stand assuming a fix for https://github.com/scala/bug/issues/10325 will arise.

Maybe 1. could be done by adding a comment to the code examples. Is there another way to provide some motivation for the example that allows the user to know what features is being shown?

**Review by janekdb — CHANGES_REQUESTED** [review]
If each example can have a comment added which mentions what the example is demonstrating then I think we will be ready to go.

**Comment by Philippus** [comment]
@janekdb have a look, if you have an idea for a good comment for the first example let me know.

**Comment by janekdb** [comment]
How about this?

     // Define a new enumeration with a type alias and work with the full set of enumerated values

**Comment by janekdb** [comment]
Looking good! Squash commits?

**Comment by Philippus** [comment]
should I squash all three commits into one commit?

**Comment by Philippus** [comment]
@janekdb done!

**Comment by janekdb** [comment]
LGTM

**Comment by janekdb** [comment]
image

**Review by janekdb — APPROVED** [review]

**Pull request merged**
