### PR TITLE
Merge Analyzer Plugins for Master

### PR DESCRIPTION
**Pull request by lrytz**
Review by @retronym. Includes the exact same commits as #2022, plus the merge.

### CODE REVIEW

**Comment by lrytz** [comment]
it seems :cat: only tested rangepos, but not the ordinary full build.

**Comment by lrytz** [comment]
PLS REBUILD pr-checkin-per-commit

**Comment by lrytz** [comment]
aaah it was still running! so currently the symptom is that the pull request is already green once the rangepos has finished, even if the main build is not yet done.

it would be nice if the links to both builds were available somewhere.

**Comment by retronym** [comment]
The merge lgtm.

**Comment by lrytz** [comment]
i beleive both builds succeeded, i saw "pr-checkin-per-commit" at some point in the green message bar. but now it's "rangepos" again. we'll have to ask @adriaanm how to figure out.

**Comment by adriaanm** [comment]
@lrytz, yes, that's why I want to run a single jenkins job that then forks the various jobs and joins them
github only shows the last status of a commit -- nothing we can do there, i thnk

**Comment by lrytz** [comment]
AFAICT this PR is good to go, both builds went fine:
- https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/68/consoleFull
- https://scala-webapps.epfl.ch/jenkins/job/pr-rangepos-per-commit/72/consoleFull

i think it only built the merge commit, but that's ok since the others are already in the repo anyway.

**Comment by adriaanm** [comment]
PLS SYNCH

(this makes the kitten synchronize state between jenkins and github)

**Comment by adriaanm** [comment]
PLS REBUILD/pr-checkin-per-commit@91c9c42

**Comment by adriaanm** [comment]
PLS REBUILD/pr-checkin-per-commit@a06d31f6

**Comment by adriaanm** [comment]
PLS REBUILD/pr-checkin-per-commit@7e836f83

**Comment by lrytz** [comment]
coooool :)

**Comment by adriaanm** [comment]
:-) next I wanna add some /DCC SEND support :sunglasses:

**Comment by adriaanm** [comment]
I think something is off here, but it could be jenkins:
https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/172/console

**Comment by adriaanm** [comment]
maybe there should be a git clean and a git reset --hard in there at the start to make sure we merge info a clean checkout

**Comment by adriaanm** [comment]
BUILDLOG?

**Comment by lrytz** [comment]
I think this cannot work - we have to think about the per-commit build logic.

The problem is that we first check out master, then try to merge the individual pull request of the commit. In this case, the intermediate commits of the PR have a parent in 2.10.x, and they don't merge cleanly into master. Obviously the merge conflicts were (manually) resolved in the merge commit of this PR, but the other commits don't merge cleanly into master.

**Comment by lrytz** [comment]
(the conflicts in https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/172/console are exactly those i had to manually resolve)

**Comment by lrytz** [comment]
maybe we should build the intermediate commits just by checking out their sha/revision, and only do the merge thing for the topmost commit?

**Comment by adriaanm** [comment]
hmm.. I guess, in general, if you rebase your commits on top of master, each individual commit should merge cleanly

in this case, the fact that pr-rangepos-per-commit worked for all commits indicates something else is wrong with pr-checkin-per-commit

either master had moved by the time the checkin jobs were running and the merge failed because of that, or the git scripts for the jenkins jobs are not ideal

**Comment by lrytz** [comment]
when we merge from 2.10 into master, we don't want to rebase on master because we want to have the same commits in the history of both master and 2.10.x.

the fail logs show that "checkin" and "rangepos" builds fail in the same way for intermediate commits, because they don't merge with master.

**Comment by adriaanm** [comment]
ok, sorry i missed that this is a forward port from 2.10.x -- now it finally all makes sense :hamster:

**Comment by adriaanm** [comment]
thanks for your patience -- merging

**Comment by lrytz** [comment]
NP - it was a good test case for the grown-up kitty.

What do you think of building intermediate commits without merging them into HEAD first? I think it would make sense, because that's what actually happens once a PR gets merged: the topmost commit is merged into HEAD, not each commit individually.

**Pull request merged**
