### PR TITLE
SI-4370 Range bug: Wrong result for Long.MinValue to Long.MaxValue by In...

### PR DESCRIPTION
**Pull request by Ichoran**
...t.MaxValue

Fixed by rewriting the entire logic for the count method.  This is necessary because the old code was making all kinds of assumptions about what numbers were, but the interface is completely generic.

Those assumptions still made have been explicitly specified.  Note that you have to make some or you end up doing a binary search, which is not exactly fast.

The existing routine is 10-20% slower than the old (broken) one in the worst cases.  This seems close enough to me to not bother special-casing Long and BigInt, though I note that this could be done for improved performance.

Note that ranges that end up in Int ranges defer to Range for count.

A new JUnit test has been added to verify that the test works.  It secretly contains an alternate BigInt implementation, but that is a lot slower (>5x) than Long.

### CODE REVIEW

**Comment by soc** [comment]
Wow, looks nice. :-)

**Comment by adriaanm** [comment]
A spurious commit snuck in.

Please do:

```
git checkout issue/4370
git pull --rebase https://github.com/scala/scala.git master
git push -f git@github.com:Ichoran/scala.git issue/4370:issue/4370
```

**Comment by Ichoran** [comment]
At least I figured out that my spurious commits were caused by careless use of rebase -i.  Should be good now.

**Comment by adriaanm** [comment]
There seems to be something to the rangepos failure. How could new deprecations be introduced by this commit, though? Btw, all jenkins jobs are on github. The [rangepos script](https://github.com/scala/jenkins-scripts/blob/master/job/pr-scala-rangepos#L24) should show how to repro locally

**Comment by Ichoran** [comment]
Doesn't have anything to do with this commit at all, or with rangepos; it's the () insertion thing.  And this is a really annoying case: you can't write "blah" -> () any more.  Ugh.

**Comment by Ichoran** [comment]
@adriaanm - How do we handle this sort of unexpected clobbering across commits?  Shall I just open a separate PR to fix the failure, or...?  t6200.scala needs ->() to be -> (()) on lines 13, 27, and 53; that's it.

**Comment by adriaanm** [comment]
Thanks for diagnosing (/cc @soc) -- please open a separate PR that fixes the deprecation warnings in t6200. Technically, we should merge this PR first and then rebase all outstanding ones on top of master, but we'll just keep in mind that where this failure came from and where it was fixed, and interpret PRs opened during this window of instability modulo this regression.

**Comment by Ichoran** [comment]
@adriaanm @soc - Should be back to sanity now.

**Comment by retronym** [comment]
LGTM. Thanks for the clear explanation and thorough tests.

Although as Paul once said, we really should find a way to get out of the numbers game. This sort of code is crazy hard to write and maintain unless you're doing it all the time.

**Comment by adriaanm** [comment]
.. and crazy hard to review -- thanks

**Comment by Ichoran** [comment]
@retronym - I think rather that we should commit to having or at least affiliating with people who understand numbers.  Given that computation is based on numbers, it's pretty hard to get out of the game completely, even if we try not to play it too often.  Thanks for the review.

**Comment by soc** [comment]
@Ichoran Wow, nicely done! Thanks a lot, this issue has annoyed me for a long time already!

**Pull request merged**
