### PR TITLE
Merge 2.10.x into master.

### PR DESCRIPTION
**Pull request by paulp**
These merges become more "interesting" all the time.  I had to resolve a scaladoc conflict with no real idea about the resolution.  We need some more natural way to put that kind of work in front of the people who wrote the conflicting code, and which doesn't block the whole repository from merging.  In any case, I took a stab at it.

### CODE REVIEW

**Comment by jsuereth** [comment]
Scaladoc merge review by @VladUreche and @vigdorchik

**Comment by paulp** [comment]
Fair warning, if this sits long enough not to merge cleanly I will be generously allowing someone else the opportunity to bring it back into line.

**Comment by VladUreche** [comment]
LGTM

Do you know any way to show only the conflict resolution instead of the entire diff? I had to browse through the entire set of changes... and this will become more and more common as master and 2.10.x diverge.

**Pull request merged**
