### PR TITLE
Alternate approach to coevolveSym

### PR DESCRIPTION
**Pull request by paulp**
This is a different variation on #3482. I'm opening a PR mostly to demonstrate that the tests pass.

### CODE REVIEW

**Comment by paulp** [comment]
Review by @adriaanm if that's not self apparent.

**Comment by adriaanm** [comment]
Thanks! When working on my old PR I spent quite some time trying to convince myself that neg/t0764.scala should type check, but I ended up concluding it shouldn't. Could you elaborate on your reasoning?

**Comment by adriaanm** [comment]
Same for t608, I don't think that should type check --  the `type s=Bifunctor.this.s` is not redundant.
(The comment that clarifies it's a type error was lost, but can still be seen here: https://code.google.com/p/kinded-scala/source/browse/trunk/experiments/bugs/typememberbugs/typememberbugs.scala?r=278#165)

**Comment by paulp** [comment]
Here you go. Send me a check.

These all compile with #3501 in place - there are 11 incorrect type errors with trunk. This code is a distilled version of t0764.scala with many permutations exercised. Convince yourself it's the same thing, because it is, and that it should compile, because it should.

```
// In all cases when calling "prepend" the receiver 'v'
// has static type NodeAlias[A] or (equivalently) Node { type T = A }.
// Since prepend explicitly returns a Node where T = outer.type,
// the return type of prepend in all cases has T = v.type, and so the call
// to "new Main" can be parameterized with any of the following, in order
// of decreasing specificity with a tie for second place:
//
//   new Main[v.type](v.prepend)
//   new Main[NodeAlias[A]](v.prepend)
//   new Main[Node { type T = A }](v.prepend)
//   new Main(v.prepend)

package p1 {
  object t0764 {
    type NodeAlias[A] = Node { type T = A }
    trait Node { outer =>
        type T <: Node
        def prepend: Node { type T = outer.type } = ???
    }

    class Main1[A <: Node](v: NodeAlias[A]) {
      private[this] def f1 = new Main1(v.prepend)                        // fail
      private[this] def f2 = new Main1[NodeAlias[A]](v.prepend)          // fail
      private[this] def f3 = new Main1[Node { type T = A }](v.prepend)   // fail
      private[this] def f4 = new Main1[v.type](v.prepend)                // ok
    }

    class Main2[A <: Node](v: Node { type T = A }) {
      private[this] def f1 = new Main2(v.prepend)                        // fail
      private[this] def f2 = new Main2[NodeAlias[A]](v.prepend)          // fail
      private[this] def f3 = new Main2[Node { type T = A }](v.prepend)   // fail
      private[this] def f4 = new Main2[v.type](v.prepend)                // ok
    }
  }
}

package p2 {
  object t0764 {
    type NodeAlias[A] = Node { type T = A }
    trait Node { outer =>
      type T <: Node
      def prepend: NodeAlias[outer.type] = ???
    }

    class Main1[A <: Node](v: NodeAlias[A]) {
      private[this] def f1 = new Main1(v.prepend)                        // ok!  <<========== WOT
      private[this] def f2 = new Main1[NodeAlias[A]](v.prepend)          // fail
      private[this] def f3 = new Main1[Node { type T = A }](v.prepend)   // fail
      private[this] def f4 = new Main1[v.type](v.prepend)                // ok
    }

    class Main2[A <: Node](v: Node { type T = A }) {
      private[this] def f1 = new Main2(v.prepend)                        // fail
      private[this] def f2 = new Main2[NodeAlias[A]](v.prepend)          // fail
      private[this] def f3 = new Main2[Node { type T = A }](v.prepend)   // fail
      private[this] def f4 = new Main2[v.type](v.prepend)                // ok
    }
  }
}
```

**Comment by paulp** [comment]
If I must I'll deconstruct t608 (on that one I put my faith in god, so I don't actually know how the story ends) but let's see if you buy this story first.

**Comment by paulp** [comment]
This is as far as I can figure out how to distill it. The reason it compiles for me and not master is that type inference has improved. Observe how master substitutes in "Node.this.type" and then can't find its way back out of the labyrinth.

```
object t0764 {
  trait Node { outer =>
    type T <: Node
    def prepend: Node { type T = outer.type } = ???
  }
  // found   : t0764.Node{type T = t0764.<refinement>.type}
  // required: t0764.Node{type T = t0764.Node{type T = A}}
  class Main1[A <: Node](v: Node { type T = A }) { new Main1(v.prepend) }
}
```

``````
/**** GOOD ****/
71  |    |    |-- new Main1(v.prepend) BYVALmode-EXPRmode (site: value <local Main1> in Main1)
82  |    |    |    solving for (A: =?t0764.<refinement>.type)
83  |    |    |    \-> t0764.Main1[t0764.Node{type T = A}]

/**** BAD ****/
71  |    |    |-- new Main1(v.prepend) BYVALmode-EXPRmode (site: value <local Main1> in Main1)
82  |    |    |    solving for (A: =?t0764.<refinement>.type)
83  |    |    |    |-- => t0764.Node{type T = Node.this.type} EXPRmode (site: value <local Main1> in Main1)
84  |    |    |    |    \-> t0764.Node{type T = t0764.<refinement>.type}
85  a.scala:8: error: type mismatch;
86   found   : t0764.Node{type T = t0764.<refinement>.type}
87   required: t0764.Node{type T = t0764.Node{type T = A}}
88    class Main1[A <: Node](v: Node { type T = A }) { new Main1(v.prepend) }
89                                                                 ^```
``````

**Comment by adriaanm** [comment]
Ok, I think I see what you mean now. I forgot the variance annotation when I reduced it to the type parameter-based version:

```
class Node[+T <: Node[_]] { outer =>
  def prepend = new Node[outer.type]
}

class Main[NextType <: Node[_]](value: Node[NextType]) {
  new Main[Node[NextType]]((value: Node[NextType]).prepend)
}
```

This compiles, and is identical to the original, so I agree it should compile as well.

**Comment by adriaanm** [comment]
> These all compile with #3501 in place - there are 11 incorrect type errors with trunk.

This is why this scares me. Multiply this by the IDE/SBT/ScalaTest/Scalacheck/Scalaz/Shapeless/Specs2 exposure we have out there, and extrapolate how long it will take us to catch up with the fall out before we can release 2.11.0 final.

**Comment by adriaanm** [comment]
I really am very open to fixing this in 2.12, but it seems like too much of a liability to fix a week before RC1. I'm sorry all I can offer is an apology for not having gotten to this sooner and an IOU. I used my last check for a quart of milk last night.

**Comment by paulp** [comment]
I'm not pressing to put this in 2.11. I don't know why I'm working on it at all.

I agree t608 shouldn't compile.

**Comment by adriaanm** [comment]
I think I know :-) perfectionism is a heavy burden
We'll get to this, I agree it's important.

**Pull request closed without merging**
