### PR TITLE
SI-7433 Fix spurious warning about catching control throwable

### PR DESCRIPTION
**Pull request by retronym**
In the same vein as SI-6994, such warnings should only be run
in the typer phase, and not in later typechecking (usually in
erasure.)

Why? After translation of pattern matching, we end up with:

```
case (ex8 @ _) => {
<synthetic> val x5: Throwable = ex8;
case11(){
  if ({
    case14(){
      if (x5.$isInstanceOf[NullPointerException]())
        matchEnd13(true)
      else
        case15()
    };
    case15(){
      if (x5.$isInstanceOf[RuntimeException]())
        matchEnd13(true)
      else
        case16()
    };
    case16(){
      matchEnd13(false)
    };
    matchEnd13(x: Boolean){
      x
    }
  })
```

Review by @gkossakowski

### CODE REVIEW

**Comment by gkossakowski** [comment]
@retronym: it seems like you have a real test failure:

```
/localhome/jenkins/b/workspace/pr-rangepos-per-commit/test/build-partest.xml:17: java.lang.RuntimeException: Test suite finished with 1 case failing:
fail - neg/nonlocal-warning.scala  [output differs]% scalac nonlocal-warning.scala
nonlocal-warning.scala:4: warning: This catches all Throwables. If this is really intended, use `case x : Throwable` to clear this warning.
    catch { case x => 11 }
                 ^
error: No warnings can be incurred under -Xfatal-warnings.
one warning found
one error found

% diff /localhome/jenkins/b/workspace/pr-rangepos-per-commit/test/files/neg/nonlocal-warning-neg.log /localhome/jenkins/b/workspace/pr-rangepos-per-commit/test/files/neg/nonlocal-warning.check
@@ -1,6 +1,9 @@
 nonlocal-warning.scala:4: warning: This catches all Throwables. If this is really intended, use `case x : Throwable` to clear this warning.
     catch { case x => 11 }
                  ^
+nonlocal-warning.scala:2: warning: catch block may intercept non-local return from method foo
+  def foo(l: List[Int]): Int = {
+                               ^
 error: No warnings can be incurred under -Xfatal-warnings.
-one warning found
+two warnings found
```

**Comment by gkossakowski** [comment]
Please reopen once the test failure is addressed.

**Comment by retronym** [comment]
@gkossakowski This patch has a better shot at correctness

**Comment by gkossakowski** [comment]
LGTM.

**Pull request merged**
