### PR TITLE
Merge 2.10.x to 2.11.x

### PR DESCRIPTION
**Pull request by retronym**
```
% export MB=$(git merge-base origin/2.11.x origin/2.10.x)

% transcript git log --graph --oneline --decorate $MB...origin/2.10.x

https://gist.github.com/3de48ff88c17803a222a

% git merge -sours fbbd1b2
Merge made by the 'ours' strategy.

% git merge ad845ff
Auto-merging test/files/jvm/future-spec/PromiseTests.scala
CONFLICT (content): Merge conflict in test/files/jvm/future-spec/PromiseTests.scala
Auto-merging src/library/scala/concurrent/Promise.scala
CONFLICT (content): Merge conflict in src/library/scala/concurrent/Promise.scala
Automatic merge failed; fix conflicts and then commit the result.
merge/2.10.x-to-2.11.x-20150224 ~/code/scala3 git status
On branch merge/2.10.x-to-2.11.x-20150224
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

    modified:   src/library/scala/concurrent/Promise.scala
    modified:   test/files/jvm/future-spec/PromiseTests.scala
    new file:   test/files/jvm/t8689.check
    new file:   test/files/jvm/t8689.scala

% git commit

[merge/2.10.x-to-2.11.x-20150224 1a7f4ec] Merge commit 'ad845ff' into merge/2.10.x-to-2.11.x-20150224

% git merge -sours b2f5101
Merge made by the 'ours' strategy.
```

### CODE REVIEW

**Comment by retronym** [comment]
Assigning to the 2.11.6 milestone, as the fix for SI-8869 should be included in that release.

**Comment by adriaanm** [comment]
jenkins master ran out of disk space (https://github.com/scala/scala-jenkins-infra/pull/37)

**Comment by adriaanm** [comment]
the IDE failed in the same way on #4354... 

I conclude this test is flaky -- where can we track this?

```
Failed tests:   testWithMultiplePartiallyAppliedFunctions(org.scalaide.ui.internal.editor.decorators.bynameparams.CallByNameParamAtCreationPresenterTest): expected:<Set(offset: 168, length: 2, offset: 230, length: 2, offset: 18, length: 2, offset: 208, length: 2, offset: 212, length: 2, offset: 244, length: 2, offset: 226, length: 2, offset: 190, length: 2)> but was:<Set(offset: 168, length: 2, offset: 230, length: 2, offset: 208, length: 2, offset: 212, length: 2, offset: 244, length: 2, offset: 226, length: 2, offset: 190, length: 2)>
```

**Comment by retronym** [comment]
> I conclude this test is flaky -- where can we track this?

I've submitted a [PR to scala-ide](https://github.com/scala-ide/scala-ide/pull/902) to enable retry for that test.

**Comment by adriaanm** [comment]
LGTM -- the other failures can safely be ignored

**Pull request merged**
