### PR TITLE
Use Java rules for member lookup in .java sources

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
Targetting at 2.13.x, but this would be a backport candidate for 2.12.9

**Review by adriaanm — APPROVED** [review]
I push -f'ed my review (just a small tweak). Let me know if this looks good to you. Let's squash the commits before merging.

**Comment by retronym** [comment]
Backport submitted in #7738

**Comment by som-snytt** [comment]
"Java rules!"

**Comment by adriaanm** [comment]
Awesome -- this also obviates the need for a leaky encoding in JavaParsers: https://github.com/scala/scala/blob/7c9e3724ee6553599a1ce008abfaf49e5a31476d/src/compiler/scala/tools/nsc/javac/JavaParsers.scala#L760-L770

Those forwarders attempt to encode the rules that this PR implements directly. They cause issues when refchecks becomes more accurate because they are inherited.

**Pull request merged**
