### PR TITLE
Wip sensible deprecation msgs √

### PR DESCRIPTION
**Pull request by viktorklang**
Some migration lube

### CODE REVIEW

**Comment by soc** [comment]
Would be nice to put `s around the code fragments to be consistent.

**Comment by viktorklang** [comment]
I don't know what you mean:

  @deprecated("Use sys.error(message) instead", "2.9.0")
  def error(message: String): Nothing = sys.error(message)

  @deprecated("Use sys.exit() instead", "2.9.0")
  def exit(): Nothing = sys.exit()

  @deprecated("Use sys.exit(status) instead", "2.9.0")
  def exit(status: Int): Nothing = sys.exit(status)

  @deprecated("Use formatString.format(args: _*) or arg.formatted(formatString) instead", "2.9.0")

I don't see the precedent

**Comment by soc** [comment]
I guess that just asks for fixing that file while you're at it. :-)

**Comment by viktorklang** [comment]
```
So you only want code-sections of deprecated messages to be in the form of: "Blah blah `code` blah blah" ?
```

**Comment by soc** [comment]
See http://www.scala-lang.org/archives/downloads/distrib/files/nightly/docs/library/index.html#scala.collection.immutable.List$ for instance. ScalaDoc can't figure out if something is code without any hints.

**Comment by jsuereth** [comment]
K, this LGTM, unless you want to fix up formatting.

**Comment by viktorklang** [comment]
I think it should be another PR to fix all the messages to be quoted.

**Comment by jsuereth** [comment]
another PR or close/flatten this one?   Doesn't matter to me.

**Comment by viktorklang** [comment]
Sprinkled backticks

**Comment by jsuereth** [comment]
rebuilding: https://scala-webapps.epfl.ch/jenkins/job/pr-scala-testsuite-linux-opt/279/console

**Comment by jsuereth** [comment]
Is this unrelated? 

```
  [partest] testing: [...]/files/neg/t3399.scala                                  [FAILED]
  [partest] t3399.scala:23: error: Cannot prove that `Nats.Add[Nats._1,Nats._1] =:= Nats._1`.
  [partest]     implicitly[ Add[_1, _1] =:= _1]
  [partest]               ^
  [partest] one error found
```

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Comment by viktorklang** [comment]
Badass
On Jun 14, 2012 8:39 PM, "Josh Suereth" <
reply@reply.github.com>
wrote:

**Comment by jsuereth** [comment]
Ok, looks like repeatable failure.   Closing this until fixed.

**Pull request closed without merging**
