### PR TITLE
SI-8315 Fix crash in dead code elimination

### PR DESCRIPTION
**Pull request by retronym**
This bug is blocking the under-consideration #3498.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @dragos

**Comment by Ichoran** [comment]
That was fast!  It's completely opaque to me how that fix works (since I'm not familiar at all with that part of the compiler), but I'm glad it's there.  Do you have a test case for it actually still eliminating code that it ought to eliminate?

**Comment by retronym** [comment]
I'm just relying on existing tests to pass.

Setting `touched = true` invalidates a cache to force the list of successors/predecessors of a basic block to be recomputed.

**Comment by retronym** [comment]
I believe that the interaction with the `inliner` was just that it happened to call `predecessors`, which cached the value that needs to be invalidated in `dce`.

**Comment by retronym** [comment]
@gkossakowski @magarciaEPFL / @lrytz 

I just realised that @dragos is on holidays. I wonder if either one you might be able to help with a review of this one?

**Comment by dragos** [comment]
LGTM

Your reasoning is correct, setting that flag marks certain caches as dirty. It can't hurt to set it, other than potentially slowing down the compiler. I think it would be nicer to encapsulate the flag, and set it from methods in IMethod, but it looks like DCE is manipulating internals freely. Since the optimizer is EOL'd, lgtm. 

I don't get why you need to set the dirty flag twice.. Is the first call necessary? Unfortunately I don't have a laptop with me so I can't read code other than what's in this PR.

**Comment by retronym** [comment]
> I don't get why you need to set the dirty flag twice.. Is the first call necessary? Unfortunately I don't have a laptop with me so I can't read code other than what's in this PR.

I did it after immediately after each of the two mutations of `code.blocks`.

**Pull request merged**
