### PR TITLE
Modularize: xml & parser-combinators

### PR DESCRIPTION
**Pull request by adriaanm**
[This PR depends on #2851]

These modules move to their own repositories:
- https://github.com/scala/scala-xml
- https://github.com/scala/scala-parser-combinators

The modularization depends on the new partest, as the old one's
classpath handling did not support a modularized scala.

The osgi tests take xml and parsers jars from the scaladoc dependencies,
and osgi-fy them, as they are no longer built locally.

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @gkossakowski, @retronym, @dragos / @huitseeker, @harrah

**Comment by adriaanm** [comment]
[Retrying IDE validation](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-integrate-ide/1519/) after https://github.com/scala-ide/scala-ide/pull/502#issuecomment-23011784 got merged. Still expect it to fail, just later. Working on fixing the build today.

**Comment by adriaanm** [comment]
Ah right, forgot the sbinary and sbt build fixes are still only in my forks.

**Comment by adriaanm** [comment]
I guess this is not going to make it for M5. More details here https://github.com/scala-ide/scala-ide/pull/502

**Comment by adriaanm** [comment]
Well, [it's alive](https://gist.github.com/adriaanm/6348061)!

To get the successful build linked to above, I currently need the hacks in the diffs below.
Most of them would disappear by switching to dbuild for sbt & sbinary.
- https://github.com/adriaanm/sbt/compare/0.13-2.11
- https://github.com/adriaanm/jenkins-scripts/compare/scala:master...modularize-211?expand=1

The other changes I had to make were reasonable, so I submitted the following PRs:
- mdr/scalariform#86
- scala-ide/scala-refactoring#28
- scala-ide/scala-ide#509

Finally, as @dotta said, we'll have to fix the scala-maven plugin properly. Currently, it works because the compiler jars are on the boot classpath, and the right ones come first... I'll look into fixing that ASAP, but would immensely appreciate help.

**Comment by gkossakowski** [comment]
I was wondering what's the status of this PR. I see the following steps that should be taken before we merge it:
- [x] review commits in this PR in isolation from IDE validation and make sure they make sense from scala repository point of view alone. I've done that and the only problem I found is adding Sonatype repo. I think we shouldn't rely on any other repos other than Maven central if possible
- [x] make sure that dependent projects like sbt and IDE are prepared for this PR to be merged

I think once we determine what to do with Sonatype repos in `build.xml` we'll be done with the first bullet.
@adriaanm: can you comment what's the status of the second bullet? From your comment above it seems like you fixed all downstream projects already but I wanted to make sure I interpret it correctly.

**Comment by adriaanm** [comment]
Once https://github.com/scala/jenkins-scripts/pull/23 is merged, PR validation will succeed for IDE integration.

**Comment by adriaanm** [comment]
The other remaining TODO is to properly fix the scala maven plugin,
but I honestly don't think we should hold up this PR -- it was broken before,
and it works, just not in a long-term confidence-inspiring way.

**Comment by adriaanm** [comment]
NOTE: the xml and parser modules are no longer included in the distribution.
I should probably change this.

**Comment by gkossakowski** [comment]
LGTM!

I assume this PR is still put on hold until other PRs are merged, right?

**Comment by adriaanm** [comment]
It's waiting for 
- [x] my commit that brings the jars back to the distribution, 
- [x] for the jenkins-scripts PR to be merged.

**Comment by gkossakowski** [comment]
@adriaanm: what's the status of this PR?

**Comment by adriaanm** [comment]
The [sbt dbuild PR](https://github.com/scala/jenkins-scripts/pull/24) just got merged. Now I need to rework [my PR](https://github.com/scala/jenkins-scripts/pull/23) to use dbuild.

**Comment by jsuereth** [comment]
note:  Fixes needed are here: https://github.com/adriaanm/scala/pull/7

**Comment by adriaanm** [comment]
@jsuereth I merged your changes from https://github.com/adriaanm/scala/pull/7

**Comment by jsuereth** [comment]
RAWK.  This gets a LGTM from me.  I tested by hand.  I can't merge https://github.com/typesafehub/sbt-builds-for-ide/pull/6 until this goes through and a 2.11.0-SNAPSHOT is publicly available with the change, so don't wait on that guy.

**Comment by adriaanm** [comment]
Ok. I tested IDE validation locally as well. @gkossakowski, all systems merge! 
The validation running right now on the last commit is irrelevant, the commit doesn't touch anything that's actually validated.

**Comment by adriaanm** [comment]
@jsuereth, please accept some :cake: as a token of my appreciation

**Comment by gkossakowski** [comment]
Thanks everybody.

Merging now.

**Comment by jsuereth** [comment]
AWESOME NEWS GUYS!  Thanks for being patient with us.  More than happy to help keep our stuff up to date :)

Also, glad to see this modularization progress.

**Pull request merged**
