### PR TITLE
fix t7668 test case on Windows

### PR DESCRIPTION
**Pull request by SethTisue**
in posh British accent: "CON you call something CON on Windows? No, you CONnot."

references https://github.com/scala/scala/pull/6037

### CODE REVIEW

**Comment by dwijnand** [comment]
RIP alignment.

Also: looks like partest is silent in failing to create the classfile, which could be improved.

**Comment by martijnhoekstra** [comment]
@dwijnand is there a ticket for that? If not, it's all but certain to not be picked up

**Comment by dwijnand** [comment]
No, I was just putting it out there. Do you think it's worrisome?

**Comment by martijnhoekstra** [comment]
@dwijnand like you said, it probably could be improved. Things that help hunting down partest cross-compat bugs are nice - not having to guess at what's gong wrong/which part has bitrotted but being pointed in the right direction is also nice.

**Comment by smarter** [comment]
I think scalac should just forbid emitting files whose names are illegal under Windows: https://stackoverflow.com/a/31976060/348497
As an aside, the same root cause once brought down the cargo registry: http://sasheldon.com/blog/2017/05/07/how-i-broke-cargo-for-windows/

**Comment by SethTisue** [comment]
this limitation/bug is from 1974: https://twitter.com/Foone/status/1058676834940776450

**Pull request merged**
