### PR TITLE
SI-5390 Detect forward reference of case class apply

### PR DESCRIPTION
**Pull request by retronym**
Refchecks performs (among others) two tasks at once:
- detecting forward references
- translating `qual.Case(...)` to `new qual.Case(...)`

As is often the case with such multi-tasking tree traversals,
completion of one task precluded the other.

Review by @adriaanm

One question: should this also be a forward reference?

``` scala
class A {
  case class B[A](s: String)
}

object X {
  def foo {
    val a = new A
    val b = new a.B[c.type]("")
    val c = ""
  }
}
```

### CODE REVIEW

**Comment by retronym** [comment]
PLS REBUILD ALL

```
ticket/5390 ~/code/scala ./test/partest test/files/run/macro-def-infer-return-type-a

Testing individual files
testing: [...]/files/run/macro-def-infer-return-type-a                [  OK  ]
All of 1 tests were successful (elapsed time: 00:00:09)

ticket/5390 ~/code/scala ./test/partest test/files/run/macro-def-infer-return-type-c

Testing individual files
testing: [...]/files/run/macro-def-infer-return-type-c                [  OK  ]
All of 1 tests were successful (elapsed time: 00:00:09)
```

**Comment by retronym** [comment]
ping @adriaanm

**Comment by adriaanm** [comment]
I think the second example need not be ruled out, as the `c.type` type argument does not have any run-time effect

**Comment by adriaanm** [comment]
thus, it would make for a good pos/ test

after that, LGTM

**Comment by adriaanm** [comment]
(apologies for the delay)

**Pull request merged**
