### PR TITLE
hardens DirectTest against missing -d settings

### PR DESCRIPTION
**Pull request by xeno-by**
And also explicitly specifies -d in a test where I forgot to do that.
Double checking never hurts.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp

**Comment by paulp** [comment]
There are a bunch of other tests using DirectTest; this will leave them passing -d twice.  Which may work, but is undesirable, especially because it leaves us vulnerable to the occasion when they aren't the same.

**Comment by xeno-by** [comment]
But then the last `-d` will win, right? This is exactly why I prepended the default `-d` to the settings, not appended.

**Comment by paulp** [comment]
It will, it's just that it invites trouble to be cavalier with the inputs to a test.  In fact, I would prefer this be more explicit about what it's doing and why, something like

```
val settings = newSettings((CommandLineParser tokenize extraSettings) ++ args.toList)
// make sure classfiles don't land in current directory
if (settings.d.value == settings.d.default)
  settings.d.value = testOutput.path
```

(I'm testing the value explicitly rather than .isSetByUser because I want to change the output path even if it has been passed "-d .".)

**Comment by xeno-by** [comment]
I suggest we put an assertion there: `assert(settings.d.value != settings.d.default, "explicitly specify -d")`

**Comment by paulp** [comment]
But isn't it going to be "-d testOutput.path" in 99% of cases? I'm not looking to offload this setting onto every individual test, I just don't want to count on composition by way of appending strings with known duplicates and feeding it all to an ad hoc parser and calling that testing.

**Comment by xeno-by** [comment]
Well the tests littering `.` weren't a problem before, so I assume everyone has `-d` set.

**Comment by xeno-by** [comment]
Doesn't look like a genuine failure. Can't reproduce on my machine

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by paulp** [comment]
"Well the tests littering . weren't a problem before, so I assume everyone has -d set."

Right, everyone did set it to the same thing, until now, which is a cautionary tale demonstrating why it's unwise to leave it for every test to do itself.  This is good for now.

**Pull request merged**
