### PR TITLE
Rebase #2727

### PR DESCRIPTION
**Pull request by adriaanm**
Rebased #2727. Should be good to go, @gkossakowski.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Thanks. I'll review once tests are run (which should be tomorrow).

**Comment by adriaanm** [comment]
ping @gkossakowski

**Comment by gkossakowski** [comment]
Thanks for pinging me. Last week was challenging when it comes to get any work done. I'll look into this today.

**Comment by gkossakowski** [comment]
@soc: please address the review comments. I promise to be more responsive this week.

**Comment by soc** [comment]
This one can be closed, but I lack the right to do it.

**Pull request closed without merging**
