### PR TITLE
Refactor ArrayBuffer.ensureSize for testing

### PR DESCRIPTION
**Pull request by som-snytt**

### CODE REVIEW

**Comment by som-snytt** [comment]
cf draconian measure at https://github.com/lampepfl/dotty/pull/10072

Note that the failure case is still "infinite loop", but this refactor mitigates the "false negative due to attempt at huge allocations", where long gc is indistinguishable from "allocation cannot possibly succeed."

**Comment by som-snytt** [comment]
The command we need is not "nothing to see" but WFM.

**Comment by som-snytt** [comment]
Maybe fool it by rebase and squash?

Maybe bootstrap with -optimize changes capturing and therefore signature of the local def?

Or maybe ordering of `array` and `array_=`.

**Comment by som-snytt** [comment]
Rebased for spurious travis.

**Comment by som-snytt** [comment]
Spuriouser and spuriouser!

[error] java.io.IOException: Server returned HTTP response code: 413 for URL: https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots;build.timestamp=1603910099540/org/scala-lang/scala-compiler/2.13.4-bin-7e46ad5-SNAPSHOT/scala-compiler-2.13.4-bin-7e46ad5-SNAPSHOT.pom

**Comment by SethTisue** [comment]
> Spuriouser and spuriouser 

https://github.com/scala/scala-dev/issues/732

**Comment by som-snytt** [comment]
Travis is quite inventive (sorry for extra lines, cut/paste on evil windows box):
```
skipping mrJar() on old JDK

skipping mrJar() on old JDK

# WARNING: Unable to attach Serviceability Agent. HotSpot Serviceability Agent attach skipped due to jol.skipHotspotSAAttach flag.

cost of tracking allocations - cost of Int   = 64

Unbounded generic level for Array[T] with Array[String] is: 0

Unbounded generic level for Array[T] with Array[U] is: 1

(file:/home/travis/build/scala/scala/build/quick/classes/library/ <no signer certificates>)

[info] Test scala.CollectTest.testFutureCollect ignored

[info] Test scala.CollectTest.testListViewCollect ignored

[info] Test scala.CollectTest.testIteratorCollect ignored

[info] Test scala.tools.nsc.async.AnnotationDrivenAsyncTest.testManualRunPartestUnderJUnit ignored

[info] Test scala.tools.nsc.async.AnnotationDrivenAsyncTest.testBoxedUnitNotImplemented ignored

#

# A fatal error has been detected by the Java Runtime Environment:

#

#  SIGSEGV (0xb) at pc=0x00007fb4bcccec54, pid=6116, tid=0x00007fb4a1350700

#

# JRE version: OpenJDK Runtime Environment (8.0_272-b10) (build 1.8.0_272-b10)

# Java VM: OpenJDK 64-Bit Server VM (25.272-b10 mixed mode linux-amd64 compressed oops)

# Problematic frame:

# V  [libjvm.so+0x2cec54]  MinINode::Ideal(PhaseGVN*, bool)+0x4e4

#

# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

#

# An error report file with more information is saved as:

# /home/travis/build/scala/scala/hs_err_pid6116.log

#

# Compiler replay data is saved as:

# /home/travis/build/scala/scala/replay_pid6116.log

#

# If you would like to submit a bug report, please visit:

#   https://github.com/AdoptOpenJDK/openjdk-support/issues

#

[error] Error: Total 0, Failed 0, Errors 0, Passed 0

[error] Error during tests:

[error] 	Running java with options -classpath /home/travis/build/scala/scala/target/junit/test-classes:/home/travis/build/scala/scala/build/quick/classes/junit:/home/travis/build/scala/scala/build/quick/classes/testkit:/home/travis/build/scala/scala/build/quick/classes/compiler:/home/travis/build/scala/scala/build/quick/classes/library:/home/travis/build/scala/scala/build/quick/classes/reflect:/home/travis/build/scala/scala/build/quick/classes/repl-frontend:/home/travis/build/scala/scala/build/quick/classes/repl:/home/travis/build/scala/scala/build/quick/classes/interactive:/home/travis/build/scala/scala/build/quick/classes/scaladoc:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjdk/jol/jol-core/0.13/jol-core-0.13.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/7.3.1-scala-1/scala-asm-7.3.1-scala-1.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.16.0/jline-3.16.0.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/webjars/jquery/3.5.1/jquery-3.5.1.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/travis/.sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.13/test-agent-1.3.13.jar:/home/travis/.sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.13/test-interface-1.0.jar sbt.ForkMain 41129 failed with exit code 134
```

**Comment by dwijnand** [comment]
`sbt -Dscala.build.compileWithDotty=true library/compile` fails with

```
[error] -- [E007] Type Mismatch Error: /home/travis/build/scala/scala/src/library/scala/collection/mutable/ArrayBuffer.scala:281:60 
[error] 281 |    else new Array(resizeEnsuring(array.length, end, n)).tap(Array.copy(array, 0, _, 0, end))
[error]     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |         Found:    Array[Nothing]
[error]     |         Required: Array[AnyRef]
[error] -- [E007] Type Mismatch Error: /home/travis/build/scala/scala/src/library/scala/collection/mutable/ArrayBuffer.scala:294:64 
[error] 294 |    else new Array(resizeDown(array.length, requiredLength)).tap(Array.copy(array, 0, _, 0, requiredLength))
[error]     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |         Found:    Array[Nothing]
[error]     |         Required: Array[AnyRef]
```

**Comment by som-snytt** [comment]
Thanks @dwijnand I tweaked the tweak. Also thanks for the TIL sbt-fu.

**Comment by SethTisue** [comment]
this looks plausible to me, but neither Dale nor I knows the ins and outs of `ArrayBuffer` resizing. @som-snytt do you want to suggest a reviewer, or shall we just merge it?

**Comment by som-snytt** [comment]
@SethTisue IIRC this was just a refactor in the narrow sense of not changing behavior. The purpose was to avoid the deleted test, which tested sizing by allocating a big array. That was failing on dotty CI, so they already deleted the old test there.

The new test just tests the resizing calculation.

Oh, I see this is from a month ago, no wonder I don't remember.

Edit: I see I added a test method for testing private methods. Isn't that helpful! I see from a comment on the test that I didn't change any behavior I found unusual, but just documented it.

**Comment by NthPortal** [comment]
not sure I'm seeing how this refactor improved testing

**Pull request merged**
