### PR TITLE
Fix SI-6208.  mutable.Queue now returns mutable.Queue for collection met...

### PR DESCRIPTION
**Pull request by jsuereth**
...hods rather than MutableList.

Review by @alex22.  In particular, not happy about code duplication for `tail`.  Suggestions welcome, or I can refactory to add a MutableListLike if you think that's best.

### CODE REVIEW

**Comment by jsuereth** [comment]
PLS REBUILD pr-rangepos KITTEH.  This time without terrible I/O failure, KTHX?

**Comment by adriaanm** [comment]
man, what is UP with all these spurious failures last night

PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by jsuereth** [comment]
Um.... build successful listed from the last failed build logs.    Anyone want to review?   Forgot to mention @phaller above.

**Comment by paulp** [comment]
Ugh to MutableListLike.  LGTM.

**Pull request merged**
