### PR TITLE
remove a bunch of old cruft

### PR DESCRIPTION
**Pull request by SethTisue**
the horror, the horror.

### CODE REVIEW

**Comment by SethTisue** [comment]
25048bc is the doozy here. this stuff clutters up my `git grep` output constantly

**Review by dwijnand — APPROVED** [review]
:+1:

You're going to jump 7 positions by deletions with this one, curtesy of test/disabled/coder/dict.txt. :-)

**Comment by lrytz** [comment]
agreed on 25048bc, i would even be in for `pending`.

**Comment by SethTisue** [comment]
> i would even be in for pending.

I didn't include that in the first cut because it isn't quiiiiiite as moldy and ancient as the others. But yes, I would definitely be in favor of axing pending too, if others agree as well.

**Comment by SethTisue** [comment]
one does sometimes see comments in the code like ` !!! Make pending/run/t5866b.scala work`, but even after wholesale removal, it doesn't take wizard-level git skills to find a particular file like that in the history

I went ahead and provisionally added an additional commit that removes `pending`.

**Comment by SethTisue** [comment]
Adriaan likes it (source: personal communication)

**Comment by SethTisue** [comment]
(there were no objections at the team meeting)

**Comment by SethTisue** [comment]
> You're going to jump 7 positions by deletions with this one

(it doesn't actually work that way, it turns out, it's still by number of commits, not lines deleted. I don't understand it exactly)

**Comment by SethTisue** [comment]
> You're going to jump 7 positions by deletions with this one

screen shot 2017-03-21 at 2 41 38 pm

🏅

**Pull request merged**
