### PR TITLE
SI-7362, crash in presentation compiler

### PR DESCRIPTION
**Pull request by paulp**

### CODE REVIEW

**Comment by paulp** [comment]
@retronym I have incorporated your wise feedback, please re-review

**Comment by retronym** [comment]
LGTM

**Comment by huitseeker** [comment]
LGTM

**Comment by som-snytt** [comment]
FWIW, I get the test failure sporadically on vanilla build of the branch, no optimise.

**Comment by paulp** [comment]
@huitseeker Any chance you can tell me why it is failing? I have a feeling it is due to completing on a package structure which is in the same file rather than on one previously compiled. I would really love to put this thing to bed.

**Comment by som-snytt** [comment]
I'll take a look, without promising. Without knowing anything, I assumed package problems were deterministic.

Since I realized incremental partest progress won't pass muster, I'm kind of looking for something to do.

Tonight is choir rehearsal with orchestra for Sunday's concert, so Scala must take a back seat to the Lord (in the driver's seat) and Calliope (riding shotgun).

I say Calliope, but I may have meant Polyhymnia or Terpsichore, depending on one's mood.

http://www.croninandcompany.com/nine-muses-names.aspx

And yes, the Net referred me to a greeting card company for the names of the muses.

I hope @huitseeker explains huitseeker somewhere.  I'm aware that 8 is lucky in Asian cultures, which I learned the hard way, by marrying into an Asian culture.

**Comment by paulp** [comment]
According to https://scala-webapps.epfl.ch/jenkins/job/pr-checkin-per-commit/1894/consoleText all tests passed, under -optimise, at 510901d42b which includes both commits. And they pass for me at home. Whatever form of non-determinism is at work here is outside my immediate grasp. @dragos, @huitseeker, @vigdorchik, any ideas?

**Comment by paulp** [comment]
Maybe I need some kind of guard on the expr in "case Import(expr, _) =>" ?

**Comment by vigdorchik** [comment]
@paulp  I think "+ERROR: Right(scala.tools.nsc.typechecker.DivergentImplicit$)" signals the problem is deeper in the compiler. Unfortunately it doesn't show the full stacktrace.

**Comment by retronym** [comment]
See also #2428.

**Comment by dragos** [comment]
@paulp, I don't have any guesses right now. `DivergentImplicit` is dark magic to me.

@som-snytt, was this test failing non-deterministically before this PR?

**Comment by som-snytt** [comment]
@dragos I didn't see a test or a failure before the PR

I turned on some debug yesterday; the magic is only slightly less dark at this point.  It's very interesting test infrastructure.  I'll keep looking (or staring) later today.  (After Giulio Cesare on the radio and then final dress.)

I did get a clean success-fail-success sequence. Annoying when it refuses to fail for several tries.

**Comment by huitseeker** [comment]
@paulp No idea either, and as much as I'd love necromantic implicit resolution to be the cause, I fail to get how this PR would be the trigger.

**Comment by hubertp** [comment]
After #2428 you won't get any DiverginImplicits because they disappear completely. Those exceptions should have never escaped the scope of inferImplicit but, as it is usually the case, they did.

**Comment by hubertp** [comment]
It is, in that PR.

**Comment by paulp** [comment]
Ha, I don't know whether to laugh or cry. Am I the only one who even after doing this for five years is never sure which way the partest diff is going?

Anyway, it's failing because "Right(scala.tools.nsc.typechecker.DivergentImplicit$)" is in the checkfile and it's NOT happening, not because it isn't in the checkfile and is happening.

**Comment by paulp** [comment]
This does kind of underscore the need to fix SI-7409.

**Comment by som-snytt** [comment]
The D.I. comes and goes for me.  I think more than half are with D.I.

I added debug to get/set OpenImplicits, and I noticed a diff on the first askTypeCompletion between passing and failing logs, so I assume the race happens there, before the immediate failure on the second ask, with:

< Pending implicit (scala.this.Function1[<root>.this.other.type,scala.this.Any],other) dominates scala.this.Function1[<root>.this.other.type,scala.this.Any]/List() with openImps List((scala.this.Function1[<root>.this.other.type,scala.this.Any],other))
< ERROR: Right(scala.tools.nsc.typechecker.DivergentImplicit$)

Sorry I haven't had a chance to look at it again yet.

I thought this underscored the utility of having stderr in logs?

**Comment by paulp** [comment]
@som-snytt You're still seeing DivergentImplicit after the class no longer exists? It's not utilitarian for the checkfile to be updated with the output of a compiler crash and for that test's success to be redefined as crashing in the same fashion.

**Comment by som-snytt** [comment]
No, of course that was the behavior a few days ago; merely reporting.

I was confused in the same way you were.  But isn't a D.I. sometimes the status quo?  Like the bug on Enum.values where you can't map without converting to List first.  Since the check was committed that way, I took it as suboptimal but status quo.  Probably in that case, the test would go in pending.

**Comment by hubertp** [comment]
@som-snytt reporting diverging implicit expansion is of course OK, but having an uncaught DivergentImplicit, which is/was an internal exception, is a different story.

**Pull request merged**
