### PR TITLE
update MiMa whitelist for infix annotation

### PR DESCRIPTION
**Pull request by SethTisue**
little missing piece of https://github.com/scala/scala/pull/5589

### CODE REVIEW

**Comment by SethTisue** [comment]
fixes the failure seen at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/806/consoleFull

~~it also made one of my own PRs fail validation, which leaves me even more puzzled why this wasn't caught during 5589's own validation~~ oh wait, this was already covered at https://github.com/scala/scala/pull/5589#issuecomment-266002912. so this is expected, it's because 5589 wasn't rebased before merge

**Comment by SethTisue** [comment]
```
Internal error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe (Write failed)
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Forked test harness failed: java.lang.NullPointerException
[error] 	at sbt.TestEvent$$anonfun$overallResult$1.apply(TestReportListener.scala:72)
[error] 	at sbt.TestEvent$$anonfun$overallResult$1.apply(TestReportListener.scala:71)
[error] 	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
[error] 	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
[error] 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
[error] 	at scala.collection.TraversableOnce$class./:(TraversableOnce.scala:138)
[error] 	at scala.collection.AbstractTraversable./:(Traversable.scala:105)
[error] 	at sbt.TestEvent$.overallResult(TestReportListener.scala:71)
[error] 	at sbt.TestEvent$$anon$1.<init>(TestReportListener.scala:66)
[error] 	at sbt.TestEvent$.apply(TestReportListener.scala:65)
[error] 	at sbt.React.react(ForkTests.scala:137)
[error] 	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:76)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
