### PR TITLE
remove some refs in TraversableOnce

### PR DESCRIPTION
**Pull request by mkeskells**

### CODE REVIEW

**Review by retronym — APPROVED** [review]
Would be neat if we could teach the optimizer to do this but it would be a serious job.

Back here in the real world, this LGTM.

Separately, it might also be worthwhile overriding the most commonly used ones of these in the most commonly used collections (`forSome { "common" }`). This could extract further performance gains by:
  - avoiding the lambda allocation altogether
  - avoiding the virtual call from, e.g. `List.foreach` to `counter.apply` inside the loop

**Comment by SethTisue** [comment]
this caused a community build regression; see https://github.com/scala/scala-dev/issues/673

**Comment by som-snytt** [comment]
If this is a worthwhile delta, then the lint is worth it. https://github.com/scala/scala/pull/8691

I wonder if a scalafix is feasible.

I wonder if `at SuppressWarning`... but in Javaland, it's annoying when folks add suppressions and then a linter (with a different compiler) says the suppression is spurious.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/8769 has the partial reversion

**Pull request merged**
