### PR TITLE
SI-6022 cleaner model of variable equality modulo <:

### PR DESCRIPTION
**Pull request by adriaanm**
centralized and improved the construction of the information needed to construct the boolean proposition that encodes the equality proposition (V = C) that models a type test pattern `_: C` or constant pattern `C`, where the type test gives rise to a TypeConst C, and the constant pattern yields a ValueConst C

for exhaustivity, we really only need implication (e.g., V = 1 implies that V = 1 /\ V = Int, if both tests occur in the match, and thus in this variable's equality symbols), but reachability also requires us to model things like V = 1 precluding V = "1"

### CODE REVIEW

**Comment by adriaanm** [comment]
review by @paulp (/cc @retronym --> feel free to grab the reviewer lock if you're around)

**Comment by paulp** [comment]
My only complaint about this commit is that having only a pos test is pretty close to having no test at all.  It's the "neg" side of logic like this which requires testing, using -Xfatal-warnings to induce failure if normal errors are not present.

**Comment by jsuereth** [comment]
is that a LGTM or not?  I can wait for more tests.

**Comment by paulp** [comment]
That's a LGTM + finger wagging.

**Comment by jsuereth** [comment]
I approve of finger wagging.  MOAR TESTS @adriaanm !!!

Still, I'm going to merge.  We can add those soon.

**Pull request merged**
