### PR TITLE
SI-8650 F-interpolator inlines literals

### PR DESCRIPTION
**Pull request by som-snytt**
Rebase of https://github.com/scala/scala/pull/4316

### CODE REVIEW

**Comment by soc** [comment]
Does it inline constants only from a local scope or also across different classes?

**Comment by som-snytt** [comment]
```
scala> f"${1}"
        private[this] val res0: String = ("1": String);
scala> f"${ Thread.State.NEW }"
        private[this] val res1: String = ("NEW": String);
scala> final val pi = 3.14
scala> f"Happy $pi Day!"
        private[this] val res2: String = ("Happy 3.14 Day!": String);
```

**Comment by lrytz** [comment]
/rebuild

```
Test suite finished with 1 case failing:
fail - jvm/t8689.scala  [output differs]% scalac t8689.scala
% diff /home/jenkins/workspace/scala-2.11.x-validate-test@3/test/files/jvm/t8689-jvm.log /home/jenkins/workspace/scala-2.11.x-validate-test@3/test/files/jvm/t8689.check
@@ -0,0 +1 @@
+success
```

probably caused by build yesterday's jenkins slowness

**Comment by som-snytt** [comment]
Since validation isn't working anyway, closing to clean that one unrelated test; and also add a commit for `Locale` processing.

**Comment by soc** [comment]
@som-snytt Mhh, I think this is concerning. Having things inlined is one of the major annoyances when trying to figure out what stuff needs to be recompiled. Java designers consider it a design mistake. We are currently also doing it in various places, but I think it would be better to decrease the number where this happens and not increase it. WDYT?

**Comment by retronym** [comment]
@soc The constants are already folded today.

```
scala> object O { final val const = "42" }
defined object O

scala> class C { def foo = s"${O.const}" }
defined class C

scala> :javap C#foo
  public java.lang.String foo();
    descriptor: ()Ljava/lang/String;
    flags: ACC_PUBLIC
    Code:
      stack=7, locals=1, args_size=1
         0: new           #9                  // class scala/StringContext
         3: dup
         4: getstatic     #15                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
         7: iconst_2
         8: anewarray     #17                 // class java/lang/String
        11: dup
        12: iconst_0
        13: ldc           #19                 // String
        15: aastore
        16: dup
        17: iconst_1
        18: ldc           #19                 // String
        20: aastore
        21: checkcast     #21                 // class "[Ljava/lang/Object;"
        24: invokevirtual #25                 // Method scala/Predef$.wrapRefArray:([Ljava/lang/Object;)Lscala/collection/mutable/WrappedArray;
        27: invokespecial #29                 // Method scala/StringContext."<init>":(Lscala/collection/Seq;)V
        30: getstatic     #15                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
        33: iconst_1
        34: anewarray     #4                  // class java/lang/Object
        37: dup
        38: iconst_0
        39: ldc           #31                 // String 42
        41: aastore
        42: invokevirtual #35                 // Method scala/Predef$.genericWrapArray:(Ljava/lang/Object;)Lscala/collection/mutable/WrappedArray;
        45: invokevirtual #39                 // Method scala/StringContext.s:(Lscala/collection/Seq;)Ljava/lang/String;
        48: areturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      49     0  this   LC;
      LineNumberTable:
        line 8: 0
```

This PR just evaluates the call to `String.format` at compile time if the parameters are statically known.

Which reminds me: we can't perform this optimization if for `f"%n"`, as this depends on the runtime value of the platform default line ending.

**Comment by som-snytt** [comment]
@retronym Hopefully it doesn't %n, but I don't recall why %%.

https://github.com/scala/scala/blob/47e454df545ed43e4d73298b1f7db52171020710/src/compiler/scala/tools/reflect/FormatInterpolator.scala#L343

@soc The ultimate goal was to reduce the cost of interpolating. Preformatting constants, but eventually not reparsing the format (and having a different backend; probably a similar goal for a regex interpolator).

Another thing I noticed is that there doesn't seem to be an obvious way to specify a Locale as a constant (too bad it's not an enum).  I haven't given it further thought yet, but it's an obvious feature to do it programmatically.

**Comment by som-snytt** [comment]
Obviously, %% could be inlined only if there was no other formatting; an edge case.

**Pull request closed without merging**
