### PR TITLE
SI-8023 Fix symbol-completion-order bug of type var patterns

### PR DESCRIPTION
**Pull request by retronym**
Removing the `isComplete` check altogether leads to cycles in,
for instance, F-bound type parameters:

```
trait LSO[+A, +Repr <: LSO[A, Repr]] // error: illegal cyclic reference involving type Repr
```

But, I believe that we can (and must) eagerly initialize the type
parameter symbols if we are typechecking a pattern.

While this appeared to regress in 2.11.x, but the problem was in fact
dormant and was merely uncovered in the fix for , 3df1d77fc.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @adriaanm

**Comment by adriaanm** [comment]
Congrats! You just unlocked the "Typechecker spooky action at a distance" badge! Your workaround in SBT blew my mind.

**Comment by adriaanm** [comment]
I think this is a good time to clean up this code. How about:

```
// When typing a type with an uninitialized symbol outside of a pattern,
// we don't don't know the allowed kind (based on `tparam.typeParams`,
// so we must defer kind checking until refchecks.
// In patterns, we can force the info because F-bounded polymorphism is not expressible
// (TODO: is this true?)

// force in pattern mode
if (mode.typingPatternOrTypePat)
  tparam.initialize

// when typing patterns, isComplete will be true because (of) the above
val pt =
  if (isComplete) GenPolyType(tparam.typeParams, AnyTpe)
  else WildcardType

val argsTyped = map2Conserve(args, tparams) { typedHigherKindedType(_, _, pt) }
```

PS: the refactoring would also a good time to hit ctrl-t 'altn[here]ernative' in the commit title

**Comment by retronym** [comment]
It will need a few tweaks:

First and easy one:
  `tparams foreach (_.initialize)`

The second issue is a touch more subtle: `typedHigherKindedType(a, b)` is not the same as `typedHigherKindedType(a, b, WildcardType)`, as `WildcardType` is taken to be kind *.

I did try something like your variation and I changed `typedHigherKindedType` to assume that `WildcardType` is kind-polymorphic (ie, don't prohibit type constructors), but thought that might be a tad riskier. But I'm happy to pursue that if you think it makes sense.

**Comment by adriaanm** [comment]
Ah, yes, I accidentally turned that loop inside out. I think it's a mistake to consider `WildcardType` of kind `*`. 
See e.g., `kindArityMismatchOk`, where kind arities are actually enforced, which treats `WildcardType` as kind polymorphic.

It probably also was a mistake to use `AnyTpe` to indicate kind `*`. (In my defense, I wanted a kind system from the start, but that was deemed too ambitious back then.)

Looking at this again, I also wonder why we're using `isComplete` on the whole type, rather than `tparam.hasCompleteInfo`.

```
val argsTyped = map2Conserve(args, tparams) { (arg, tparam) =>
  // force in pattern mode
  if (mode.typingPatternOrTypePat)
    tparam.initialize

  // when typing patterns, `hasCompleteInfo` will be true because (of) the above
  val pt =
    if (tparam.hasCompleteInfo) GenPolyType(tparam.typeParams, AnyTpe) // kind arity = pt.typeParams.length
    else WildcardType // kind polymorphic

  typedHigherKindedType(_, _, pt)
}
```

**Comment by adriaanm** [comment]
Maybe we should shove the nastiness with `pt` deeper down the rabbit hole:

```
val argsTyped = map2Conserve(args, tparams) { (arg, tparam) =>
  // force in pattern mode
  if (mode.typingPatternOrTypePat)
    tparam.initialize

  // when typing patterns, `hasCompleteInfo` will be true because (of) the above
  val pt =
    if (tparam.hasCompleteInfo) Kind.Arity(tparam.typeParams.length)
    else Kind.Wildcard

  typedHigherKindedType(_, _, pt)
}
```

**Comment by retronym** [comment]
> It probably also was a mistake to use AnyTpe to indicate kind *

You mean, kind _ ?

**Comment by retronym** [comment]
Is arity the only constraint represented by `GenPolyType`? What about bounds?

**Comment by retronym** [comment]
This comment suggests just arity is important there, but I'd like to know exactly what that entails in the implementation

``` scala
// @M: kind-arity checking is done here and in adapt, full kind-checking is in checkKindBounds (in Infer)
```

**Comment by retronym** [comment]
@adriaanm  I've taken a shot at addressing your comments in the latest commit.

**Comment by retronym** [comment]
Oh, and the suggestion to predicate on `tparam.hasCompleteInfo` rather than `tpt.symbol.hasCompleteInfo` didn't pan out, these tests failed:

```
  /Users/jason/code/scala3/test/files/pos/tcpoly_typeapp.scala
  /Users/jason/code/scala3/test/files/neg/t742.scala
```

**Comment by adriaanm** [comment]
> Is arity the only constraint represented by GenPolyType? What about bounds?

I think those are only checked in refchecks. IIRC (but it's been a while), all this does is check arities (around the `kindArityMismatchOk` spot)

**Comment by adriaanm** [comment]
> You mean, kind _ ?

Now I'm not sure which kind you mean  :-) 

My grammar for kinds is:

```
k ::= *(T, T)  // `*(LowerBound, UpperBound)`
      | k -(v)-> k // type constructor that takes a type argument of kind k, variance in that arg is given by `v` 
      | Top | Bottom
v ::= '+' | '-' | '0'
T ::= (a type)
```

We don't often speak of the top/bottom of the subkinding lattice (just kind of gloss over by making any/nothing kind polymorphic), but they are needed as there's no subkinding between *(T, U) and k -(v)-> k for any instantiation of the free variables in there.

**Comment by retronym** [comment]
I meant that in the context of:

> It probably also was a mistake to use AnyTpe to indicate kind *

It sounds like you're talking about `Top`, there.

**Comment by adriaanm** [comment]
I believe I was thinking of Wildcardtype as Top and Any as \* (with both conflations being mistakes). I haven't been the most coherent in this thread (thanks for bearing with me), so I'll leave it at "believe".

**Comment by adriaanm** [comment]
LGTM, most importantly

**Pull request merged**
