### PR TITLE
Remove traces of scala-actors

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Re-submission of #4507. Review by @cunei.

The formatting of `dbuild-meta.json` changed a bit. I checked the actual differences manually.

One difference is that `scala-actors` is no longer there (it was actually removed from `dbuild-meta-json-gen.scala` in 5b73e75943dd89dabda84b0fc3a651837c4a2113, but the json file was not re-generated).

~~The other difference is that the structure of the file is a bit different:~~ This is no longer the case, see below.

```
{
  "proj-info" : [
    {
      "projects": [ ... ],
      "subproj" : [],
      "version" : "2.12.0"
    }
  ]
}
```

~~Before it was:~~

```
{
  "version": "2.11.0",
  "subproj": [],
  "projects": [ ... ]
}
```

**Comment by lrytz** [comment]
@cunei: It seems dbuild doesn't expect the new format:

```
[scala] Extracting dependencies for: scala
[scala:error] Failed to read scala metadata file: /mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x-manual/./target-0.9.1/extraction/3281216bcbd42a0e6918c2ecb3e89bd6149f3e97/projects/a0cc2cd36eafeba3e035f98228850f651fd1bad3/projects/54274edafa757bbee560d8019c330c71ff0caf2c/dbuild-meta.json
[scala:error] com.fasterxml.jackson.databind.JsonMappingException: Property 'proj-info' is unknown at this position.
[scala:error] {"proj-info":[{"projects":[{"organization":"org....
[scala:error]  ^
[scala:error]   at distributed.project.model.Utils$$anonfun$readValueT$1.apply(Utils.scala:40)
[scala:error]   at distributed.project.model.ClassLoaderMadness$.withContextLoader(ClassLoaderMadness.scala:8)
[scala:error]   at distributed.project.model.Utils$.readValueT(Utils.scala:17)
[scala:error]   at distributed.project.model.Utils$.readValue(Utils.scala:43)
[scala:error]   at distributed.support.scala.ScalaBuildSystem$.readMeta(ScalaBuildSystem.scala:298)
[scala:error]   at distributed.support.scala.ScalaBuildSystem$.extractDependencies(ScalaBuildSystem.scala:42)
[scala:error]   at distributed.support.scala.ScalaBuildSystem$.extractDependencies(ScalaBuildSystem.scala:29)
[scala:error]   at distributed.project.dependencies.MultiBuildDependencyExtractor.extract(BuildDependencyExtractor.scala:38)
[scala:error]   at distributed.project.dependencies.Extractor$$anonfun$extractedResolvedWithCache$1.apply(Extractor.scala:100)
[scala:error] Falling back to default.
[scala] These subprojects will be built: continuations, jline, scala-partest, scala-actors, scala-compiler, scala-library, scala-reflect, scala-swing, scalap
```

https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/166/console

**Comment by lrytz** [comment]
I updated the generator to just create a `ProjMeta` (instead of a `ExtractedBuildMeta`), so the format of `dbuild-meta.json` stays the same.

**Comment by lrytz** [comment]
I ran a community build manually on this PR, the extraction and build of `[scala]` looks good in https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/167/consoleFull

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
