### PR TITLE
Made inliner work for @inline methods that access private variables.

### PR DESCRIPTION
**Pull request by odersky**
We need to disable the previous "potentiallyPublished" logic because that one disables inlining as long as the inlined method has a reference to a field with a $. But making fields public in @inline method will generate fields with $. 

We still need to complement this patch with reverting the previous publication logic completely. I leave that to Vlad or Miguel. 

Review by @VladUreche, @magarciaEPFL, @gkossakowski, @moors

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
PLS REBUILD ALL to see the new commit in action

**Comment by VladUreche** [comment]
The test that failed explicitly depends on the "move inline logic before pickler" commit:
https://github.com/scala/scala/commit/e6b4204604b667f070f61837a31cbb586107696e

```
  [partest] testing: [...]/files/pos/inline-access-levels                         [FAILED]
  [partest] Test_2.scala:7: error: Could not inline required method actOnX because access level required by callee not matched by caller.
  [partest]     A.actOnX(_ + 1)
  [partest]             ^
```

It looks like the variable x in [the test](https://github.com/scala/scala/blob/e6b4204604b667f070f61837a31cbb586107696e/test/files/pos/inline-access-levels/A_1.scala) becomes private on the second compilation run.

**Comment by odersky** [comment]
Retracted second commit. I must have gotten confused with my tests. PLS REBUILD ALL

**Comment by magarciaEPFL** [comment]
LGTM

**Pull request merged**
