### PR TITLE
Backport fix for detecting jar

### PR DESCRIPTION
**Pull request by som-snytt**
Backfixes scala/bug#12019 (https://github.com/scala/scala/pull/9034)

### CODE REVIEW

**Comment by SethTisue** [comment]
Note the Spark folks expressed (on the linked ticket) interest in seeing this fixed.

**Comment by som-snytt** [comment]
In fact, they came across my I.M.F. dossier while putting together a strike team.

**Comment by SethTisue** [comment]
(review-requesting Lukas since he reviewed the original 2.13 version: https://github.com/scala/scala/pull/9034)

**Comment by som-snytt** [comment]
Isn't that called "double jeopardy" or something?

**Review by lrytz — APPROVED** [review]
Thanks!

**Pull request merged**
