### PR TITLE
Fix [@spec A] to correctly induce AnyRef specialization.

### PR DESCRIPTION
**Pull request by non**
While [@specialized A] already tries to include specialization,
a bug in specializedOn prevented this from happening: any empty
list could mean that the type var was unspecialized, or that it
was specialized on everything.

The fix is to have this function create the full list of symbols
in the case where the @specialized annotation doesn't explicitly
include any types.

### CODE REVIEW

**Comment by non** [comment]
Actually, please hold on one second. I hadn't done a full test run before doing this, so now I'm doing all.clean and test again to verify that nothing else is broken.

Sorry... I know I should wait on these, but testing everything from scratch takes so long.

**Comment by non** [comment]
OK, yeah, there are some tests I forgot to update. Please disregard this pull request.

**Comment by paulp** [comment]
Great, I was hoping I might wake up with this fixed.

Did you notice that this didn't fix @specialized() (it's in the files/run/t3575.scala test.) Not that I think it's hugely important as I assume nobody writes that.

**Comment by non** [comment]
Oh, I hadn't noticed that. Should I try to update that as well?

I just fixed the t3575.check file so I was going to submit another pull request, but I can try to get that working as well.

**Comment by non** [comment]
Also, wait, when I did the all.clean and then ran tests, it _did_ catch that case! That was one of the tests I had to update.

Maybe I am doing something wrong?

**Comment by paulp** [comment]
You updated the checkfile with the part of the test which you fixed, but there is another part which remains unspecialized.

**Comment by paulp** [comment]
OIC, in the new pull request they're all updated.  Great.

**Pull request closed without merging**
