### PR TITLE
Require and target Java 8

### PR DESCRIPTION
**Pull request by adriaanm**
- Require Java 8 in ant build
- use -source 1.8 and -target 1.8 for javac
- Default scalac's -target to `jvm-1.8`, ignore and deprecate attempts
  to use `jvm-1.{6.7}`
- Remove fragile javap-app test. The feature itself is slated for removal.
- Remove obsolete Java6 checkfile
- Adapt DCE tests
  - Remove deprecated/redundant -target:jvm-1.6 from flags where the
    intent was to trigger generation of stack map frames.
  - Remove tests with -target:jvm-1.5 that tested without stack
    map frames
- Ignore OpenJDK JVM warnings (via test/files/filters).

### CODE REVIEW

**Comment by adriaanm** [comment]
Rework of #4523 (last bullet item above).

**Comment by adriaanm** [comment]
Meh, looks like not all tests use the filters. @retronym -- ideas on how to fix this without changing Java options? Maybe making them branch dependent is what we'll have to do, but that's a bit of work.

**Comment by retronym** [comment]
Unfortunately we need two copies of the filters file: the second is in `test/scaladoc/filters`

**Comment by adriaanm** [comment]
Aha! Thanks, missed that. Was on train home.

**Comment by adriaanm** [comment]
Almost there!  One failure for test introduced in 6097fe5d84 (#4486)

```
[partest] !! 21 - scalap/t8679.scala                        [output differs]
```

**Comment by adriaanm** [comment]
Weird -- spurious fail?

```
 jenkins@ip-172-31-12-38:~/workspace/scala-2.12.x-validate-test/test$ source /usr/local/share/jvm/jvm-select 
jenkins@ip-172-31-12-38:~/workspace/scala-2.12.x-validate-test/test$ jvmSelect openjdk 8
Java home: /usr/lib/jvm/java-1.8.0-openjdk-amd64
jenkins@ip-172-31-12-38:~/workspace/scala-2.12.x-validate-test/test$ cd ..
jenkins@ip-172-31-12-38:~/workspace/scala-2.12.x-validate-test$ test/partest test/files/scalap/t8679.scala
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
Partest version:     
Compiler under test: $baseDir/scala-compiler.jar
Scala version is:    Scala compiler version 2.12.0-20150526-180455-8d2d3c702d -- Copyright 2002-2013, LAMP/EPFL
Scalac options are:  
Compilation Path:    $baseDir/scala-library.jar:$baseDir/scala-reflect.jar:$baseDir/scala-compiler.jar:$baseDir/scalap.jar:/home/jenkins/workspace/scala-2.12.x-validate-test/m2repo/org/scala-lang/modules/scala-partest_2.12.0-M1/1.0.7/scala-partest_2.12.0-M1-1.0.7.jar:/home/jenkins/workspace/scala-2.12.x-validate-test/m2repo/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar:/home/jenkins/workspace/scala-2.12.x-validate-test/m2repo/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar:/home/jenkins/workspace/scala-2.12.x-validate-test/m2repo/org/scala-lang/modules/scala-xml_2.12.0-M1/1.0.4/scala-xml_2.12.0-M1-1.0.4.jar:/home/jenkins/workspace/scala-2.12.x-validate-test/m2repo/org/scala-lang/modules/scala-parser-combinators_2.12.0-M1/1.0.4/scala-parser-combinators_2.12.0-M1-1.0.4.jar:/home/jenkins/workspace/scala-2.12.x-validate-test/m2repo/org/scalacheck/scalacheck_2.12.0-M1/1.11.6/scalacheck_2.12.0-M1-1.11.6.jar:$baseDir/scala-partest-extras.jar:$baseDir/scala-partest-javaagent.jar:$sourceDir/lib/annotations.jar:$sourceDir/lib/enums.jar:$sourceDir/lib/genericNest.jar:$sourceDir/lib/jsoup-1.3.1.jar:$sourceDir/lib/macro210.jar:$sourceDir/lib/methvsfield.jar:$sourceDir/lib/nest.jar
Java binaries in:    /usr/lib/jvm/java-8-openjdk-amd64/jre/bin
Java runtime is:     OpenJDK 64-Bit Server VM (build 25.40-b13, mixed mode)
Java options are:    -Xmx1024M -Xms64M -XX:MaxPermSize=128M 
baseDir:             /home/jenkins/workspace/scala-2.12.x-validate-test/build/pack/lib
sourceDir:           /home/jenkins/workspace/scala-2.12.x-validate-test/test/files

Selected 1 tests drawn from specified tests

# starting 1 test in scalap
ok 1 - scalap/t8679.scala                      

1/1 passed (elapsed time: 00:00:04)
Test Run PASSED
```

**Comment by adriaanm** [comment]
Same with jenkins's JAVA_OPTS... retrying

**Comment by retronym** [comment]
Let's shunt that test to `disabled` and open a ticket if we can't figure this out immediately.

**Comment by adriaanm** [comment]
Looks like it was spurious -- no idea why (it's a huge file to compile -- could be that we regressed somehow in memory consumption on JDK 8?)

**Comment by adriaanm** [comment]
LGTM -- merging so other PRs can be rebased on top of it.

**Pull request merged**
