### PR TITLE
traverse does not take an IterableOnce of Futures

### PR DESCRIPTION
**Pull request by philipschwarz**
single-commit version of the following PR: https://github.com/scala/scala/pull/7484

### CODE REVIEW

**Comment by philipschwarz** [comment]
@viktorklang @lrytz happy new year! - just a reminder that instead of squashing the commits in https://github.com/scala/scala/pull/7484, as requested, I have just closed that PR and opened this one which consists of a single commit

**Comment by viktorklang** [comment]
@philipschwarz Looks good to me! @lrytz?

**Review by NthPortal — APPROVED** [review]

**Comment by SethTisue** [comment]
thank you @philipschwarz. congratulations on your first scala/scala PR! welcome

**Comment by philipschwarz** [comment]
@SethTisue thanks!

**Pull request merged**
