### PR TITLE
Merge 2.10.x to master (again)

### PR DESCRIPTION
**Pull request by retronym**
Merging eagerly to disable flaky tests.

### CODE REVIEW

**Comment by retronym** [comment]
Review by @gkossakowski 

Let's see how the Jenkins job goes this time...

**Comment by dragos** [comment]
The IDE failure is probably spurious: we changed the way the Scala library dependency is resolved, and the IDE validator was unlucky enough to start between merging changes to a dependency and merging changes to the IDE itself.

**Comment by retronym** [comment]
I found the problem. I recently changed `pr-scala-test` to archive the JUnit log files. But if there are none are produced Jenkins fails with "no artifacts to archive". This was the case when the commit 371bad2 was excluded from being built by `pr-scala-per-commit` as it is already a HEAD of 2.10.x and assumed to be tested, 

I have just changed it to not treat that as a fatal error.

PLS REBUILD ALL

/cc @gkossakowski @adriaanm

**Comment by dragos** [comment]
The IDE failure for e9307e1 is spurious.

**Comment by gkossakowski** [comment]
LGTM.

I'm ignoring the spurious failures.

**Pull request merged**
