### PR TITLE
sane printing of renamed imports

### PR DESCRIPTION
**Pull request by xeno-by**
Having a select named "foo" with an underlying symbol named "bar"
and trying to make sense of all that by prettyprinting is very confusing

### CODE REVIEW

**Comment by xeno-by** [comment]
review by @retronym

**Comment by retronym** [comment]
Could you add a test case for this one?

**Comment by xeno-by** [comment]
done

**Comment by retronym** [comment]
lgtm

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by jsuereth** [comment]
PLS REBUILD pr-scala-testsuite-linux-opt

**Comment by adriaanm** [comment]
please don't merge your own pull requests

we try to limit the merge delay to a couple of days; if there's a need to merge faster, please ping us
(letting it sit in the queue gives other people a chance to look at your code)

the idea is that (the evolution of) our codebase is witnessed by as many pairs of eyes as possible 
- the author
- the reviewer
- the committer

ps: see also http://www.washingtonpost.com/opinion/wait-the-art-and-science-of-delay-by-frank-partnoy/2012/09/14/ff9fb3f0-f759-11e1-8253-3f495ae70650_story.html

**Comment by paulp** [comment]
Can I only plead that we all understand that delay also exacts a heavy cost, especially on the guy who writes the most code and has to do the most merging. Delay with purpose, delay whose benefits are being constantly evaluated, delay which improves the outcome, those I can live with. Delay which is just delay, I can't. And there's only so far I can reasonably go in assuming that "delay of unknown character" is the former kind.

**Comment by xeno-by** [comment]
@adriaanm If I understand you correctly, now we're upgrading to 2 reviewers per PR instead of 1. Then can I merge my own pull requests if I find a second reviewer who will sign off a PR?

**Comment by paulp** [comment]
I don't think that's what he meant. He meant "don't railroad your code through."

**Comment by adriaanm** [comment]
I agree delays cost. I think I've been reasonably/fairy/pretty good about rebasing requests myself where possible to save the original submitter's time.

However, merging pull requests also has a cost (I'm not talking about the time spent ogling the code/docs/commit message. I'm referring to the repercussions when it turns out we should've polished the patch just a little more.)

The pull request mechanism tries to give more visibility to changes to our code base. The idea is that we learn about each other's code, one review at a time. Think of it as educating fixers of future bugs that you won't have to resolve yourself.

I hope we're all operating under the assumption I'm not here to increase anyone's work load (unnecessarily...).

I want us to be efficient in the long term. I'm aware that has an upfront cost, but I hope we can agree to an amount we all feel is reasonable. I'm happy to discuss how much is too much.

**Comment by paulp** [comment]
I am fine with all of this, even supportive if that's possible, as long as this is what is actually happening during delays. The world I wish to avoid is the one where I see my code repeatedly "pocket vetoed" by absent reviewers. Lots of eyes on the pull request is the best thing; the pull request drifting away into The Land Which Merge Forgot is not the next best thing. (At least not when it's mine.)

I'm not complaining about the present state of affairs, not in this message anyway. I just don't want to see too much praise heaped upon Professor Delay.

**Comment by adriaanm** [comment]
The article was not meant to promote some new policy. It just happened to be on my mind because someone sent me that link today.

**Comment by adriaanm** [comment]
I hope to optimize this process by having some bot prod reviewers when they don't reply in time.

(My first forays in automating the busy work of keeping the github flow going: https://github.com/adriaanm/gh/blob/master/github_api.scala) 

We should come up with SLAs for the various roles in the process.

**Comment by paulp** [comment]
I don't remember if it's any good, but you know I have some github-API scala code? https://github.com/paulp/libscala/blob/master/github-api/src/main/scala/pullreq.scala

**Comment by adriaanm** [comment]
thanks for the reminder, but that wasn't invented here at my desk

I was just play!ng around, a more serious effort (including code reuse) will follow next month

**Comment by xeno-by** [comment]
@adriaanm From what I understand, your messages boil down to the fact that we need better reviews than we're having now. I wholeheartedly support this sentiment, so let's come up with a deterministic scheme that will improve upon the state of the art.

One possibility would be to increase the number of lgtm's required, as I proposed above. To me it looks like this proposal goes along then lines with your delay idea, since both increase the mathematical expectation of the number of eyeballs having scanned merged PRs.

Another option would be to have a pool of people (I'll gladly volunteer to be a part of that pool), who have obligations towards reviewing the pull requests. Say, I don't know, 1 mandatory pull request per day. Most likely it would make sense to have multiple pools - at least, one for the library and one for the compiler.

The overarching theme in my suggestions is determinism. Pending pull requests impose a mental burden on their author and impair planning. So as an author I would like to have this burden well-defined. In this light, going the extra mile to get an additional lgtm is more preferable to me than waiting an undeterministic (I'm not saying huge, I'm saying undeterministic) amount of time.

Given that we manage to successfully increase the E[eyeballs], I suggest we unban self-committing. Authors and potential users of PRs (which most often include the authors) have higher motivation to closely watch the kitteh and fight spurious jenkins failures, which ultimately means smaller delays, especially taking into account the timezone differences.

**Pull request merged**
