### PR TITLE
SI-6558: typecheck lazy annotation info using non-silent context

### PR DESCRIPTION
**Pull request by retronym**
Resubmitting #1531 to `2.10.x`.

Patch by @hubertp, LGTM, with the extra test cases I added to the PR.

Review by @lrtyz

### CODE REVIEW

**Comment by lrytz** [comment]
why don't we get error messages for `@inargument` and `@infunction` in the test casse?

**Comment by retronym** [comment]
Damn, I was too quick with the `--update-check`. I might need to split those out to a separate tests; it seems the other errors prevent things getting that far. (Is that a problem of itself?)

**Comment by lrytz** [comment]
in principle it is a problem in itself i think. but it's a different one (i guess the two hidden errors come back once you work out the first three), and less severe than the one being fixed here. so i'd give it an lgtm

**Comment by retronym** [comment]
okay, i'll push the split tests in a minute.

**Comment by hubertp** [comment]
Yes, that is a problem. Can you open a ticket and assign to me, please?

**Comment by retronym** [comment]
https://issues.scala-lang.org/browse/SI-6758

**Comment by hubertp** [comment]
error is spurious so PLS REBUILD ALL

**Pull request merged**
