### PR TITLE
SI-8932 Fix dropRight/takeRight implementations

### PR DESCRIPTION
**Pull request by ruippeixotog**
I looked up at all the overrides of `IterableLike#takeRight` and
`IterableLike#dropRight` and replaced usages of its argument `n` with
`math.max(n, 0)` every time it was being used in an index subtraction.

Fixes [SI-8932](https://issues.scala-lang.org/browse/SI-8932).

### CODE REVIEW

**Comment by ruippeixotog** [comment]
It seems like the build is failing because [pr-scala-publish-core](https://scala-webapps.epfl.ch/jenkins/job/pr-scala-publish-core/) is failing since Nov 9. Do I need to do something on my part?

**Comment by lrytz** [comment]
We're still investigating the build issues, see https://groups.google.com/forum/#!topic/scala-internals/5hHIkPiMTkk

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by Ichoran** [comment]
LGTM save that most of the tests should be in the quasi-comprehensive collections tests if possible.  I would err on the side of leaving them in for now.

**Comment by Ichoran** [comment]
Note that scala-collections-laws now has a guide for how to use it, so adding such tests would be easier.  (I may do so myself, as it may require some fiddling to get the current release to pass.)

**Comment by ruippeixotog** [comment]
@Ichoran, I have just made [a pull request](https://github.com/scala/scala-collections-laws/pull/10) to scala-collections-laws modifying laws so that this issue is properly tested.

**Pull request merged**
