### PR TITLE
SI-6815 untangle isStable and hasVolatileType

### PR DESCRIPTION
**Pull request by adriaanm**
`Symbol::isStable` is now independent of `Symbol::hasVolatileType`,
so that we can allow stable identifiers that are volatile in ident patterns.

This split is validated by SI-6815 and the old logic in RefChecks,
which seems to assume this independence, and thus I don't think ever worked:

```
if (member.isStable && !otherTp.isVolatile) {
  if (memberTp.isVolatile)
    overrideError("has a volatile type; cannot override a member with non-volatile type")
```

Introduces `admitsTypeSelection` and `isStableIdentifierPattern` in treeInfo,
and uses them instead of duplicating that logic all over the place.

Since volatility only matters in the context of type application,
`isStableIdentifierPattern` is used to check patterns (resulting in `==` checks)
and imports.

review by @retronym & @paulp

I decided not to backport this to 2.10.x as it may introduce new errors.

### CODE REVIEW

**Comment by retronym** [comment]
Suggestions for additional tests:
- import from a stable-for-pattern-but-volatile qualifier
- pattern match test using the `emptyValDef` in the real reflection API.

Can you comment as to why you made `emptyValDef` and co. final?

**Comment by adriaanm** [comment]
> Can you comment as to why you made emptyValDef and co. final?

that was inherited from the original PR, will revert

**Comment by adriaanm** [comment]
> Suggestions for additional tests:
> 
> import from a stable-for-pattern-but-volatile qualifier

On it.

> pattern match test using the emptyValDef in the real reflection API.

Actually, I'd rather not have tests tango with the library if we can avoid it.

**Comment by retronym** [comment]
LGTM

**Comment by paulp** [comment]
I feel this could be broken up a lot more. Or at least a little more. There are places it can be subdivided which risk nothing; for instance the removal of now-dead methods could follow the rest of it. Every bit helps.

**Comment by adriaanm** [comment]
I don't see how splitting off the removal of 22 lines and two methods helps our future selves in any way.

**Comment by paulp** [comment]
It means when you bisect your way to this commit, there is N-22 lines to sift through rather than N. But that was only an example of the REALLY easy to break up code; there is more which is only "easy".

**Comment by paulp** [comment]
Also, I'm not any more of a fan of busywork than you are. I'm just trying to hold others to the standard to which I am held. I'm fine with loosening the restraints as long as they're loosened for everyone.

**Comment by adriaanm** [comment]
I'm not arguing we should weaken the standard, and I certainly don't expect to be held to a lower one. I just felt this time there was no reason to split out these methods, but I shall abide. Just been busy with other stuff.

**Comment by adriaanm** [comment]
hope this meets reviewer's demands

**Comment by paulp** [comment]
Reviewer thought he might have sent you over a cliff or something.

**Comment by paulp** [comment]
It isn't going to win any partitioning awards, but reviewer is sensitive to the burdens of command. LGTM.

**Comment by adriaanm** [comment]
LGTM echo

LGTM'er, please take note of the automation's sensitivities: only comments that startWith "LGTM" are considered unequivocal endorsements, the others taken for conditional (sorry, the kitten NLP does not)

**Comment by retronym** [comment]
LGTM, too.

**Comment by retronym** [comment]
This caused a regression in the stability of the self reference (at least wrt imports)

https://issues.scala-lang.org/browse/

**Comment by paulp** [comment]
@retronym And it was so much easier to bisect thanks to the efforts of pedantic reviewer! /cc @adriaanm

**Pull request merged**
