### PR TITLE
SI-9363 fix

### PR DESCRIPTION
**Pull request by triggerNZ**
I have had issues with serializing partial functions, and noticed SI-9363 - so this is a fix. This is my first PR to scala so all comments are welcome

### CODE REVIEW

**Comment by lrytz** [comment]
Hi @triggerNZ, thank for the submission!

It looks good already, I found another place to add Serializable: https://github.com/scala/scala/blob/543ebf6a0a930ec9e85bba1a4ad6df26ba541e6e/src/library/scala/PartialFunction.scala#L251-L258

```
scala> def assertSerializable[A,B](fn: A => B) = {
     |   import java.io._
     |   new ObjectOutputStream(new ByteArrayOutputStream()).writeObject(fn)
     | }
assertSerializable: [A, B](fn: A => B)Unit

scala> assertSerializable(PartialFunction.empty)
java.io.NotSerializableException: scala.PartialFunction$$anon$1
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
  at .assertSerializable(<console>:13)
  ... 32 elided
```

Also, there seems to be some merge commit in this PR - would you mind rebasing on top of the current 2.12.x, so we have a clean(er) history?

Finally, the actual commit with your changes somehow seems to be not linked to your github account - maybe you find a way to fix this? It would be better for us because our CLA database contains github usernames.

**Comment by triggerNZ** [comment]
@lrytz thank you for your comments. I have fixed up those things, so hopefully it's good to go now :D

**Comment by lrytz** [comment]
LGTM, thanks a lot!

**Comment by triggerNZ** [comment]
@lrytz I don't know if this is the correct forum to ask, but is it possible to get this merged into 2.11.8?

**Comment by lrytz** [comment]
We cannot do this in 2.11.8 for backwards compatibility reasons: code compiled with 2.11.8 is supposed to run on earlier 2.11.x releases. So an app compiled with 2.11.8 that runs `serialize(pf1 orElse pf2)` will crash when running with the 2.11.7 library on the classpath.

**Pull request merged**
