### PR TITLE
Nicer partest formatting of 4-digit test numbers

### PR DESCRIPTION
**Pull request by soc**
Because

  ...
  [partest] ok  999 - pos/t3534.scala
  [partest] ok 1000 - pos/t261-ba.scala
  ...

is so much nicer than

  ...
  [partest] ok 999 - pos/t3534.scala
  [partest] ok 1000 - pos/t261-ba.scala
  ...

### CODE REVIEW

**Comment by soc** [comment]
The example didn't survive GitHub's UI ... :-/

**Comment by som-snytt** [comment]
This version uses the test total to pick the field width:

https://github.com/som-snytt/scala/tree/topic/testwidth
https://github.com/som-snytt/scala/commit/732fb1556a948bd637d03ad0eb3e4476ca0b0ff9

I tried the triple-backtick for formatting, we'll see what it looks like on a PR.

If you like the commit, I'll add it to a PR pending for updating scalacheck.

**Comment by som-snytt** [comment]
I wasn't paying attention on my commit -- the hash comments

```
# starting 1341 tests in run
```

are ignored in the commit message, of course.

**Comment by soc** [comment]
@som-snytt Yes, please!

Considering your change is better, this PR can be closed, right?

**Comment by som-snytt** [comment]
Available for review, https://github.com/scala/scala/pull/2385

**Comment by soc** [comment]
I'm closing this in favor of #2385.

**Pull request closed without merging**
