### PR TITLE
Fixes Non-Iterators have iterator reuse warnings in scaladoc#11595

### PR DESCRIPTION
**Pull request by Jin-H**
detail : https://github.com/scala/bug/issues/11595
just remove `@note` annotation in IterableOnce.scala

### CODE REVIEW

**Review by diesalbla — APPROVED** [review]

**Comment by martijnhoekstra** [comment]
Does this retain the notes on `Iterator`?

**Comment by Jin-H** [comment]
@martijnhoekstra yes, I just remove the notes on `IterableOnceOps`, which contain `@note` on the methods such as `scanLeft`、`map` and etc. Both of these methods will not return a Iterator.

**Review by lrytz — COMMENTED** [review]
I guess you can remove the definition `@define consumesAndProducesIterator` then?

**Comment by Jin-H** [comment]
@lrytz you are right, I also find some methods who are Non-Iterators reference `@define consumesOneAndProducesTwoIterators`, Maybe I  need review it myself first.

**Comment by lrytz** [comment]
Looks good, thanks! Could you squash the two commits into one?

**Comment by Jin-H** [comment]
@lrytz I squashed it just now. 😄

**Review by lrytz — APPROVED** [review]
Thanks, @Jin-H!

**Comment by Jin-H** [comment]
It's my pleasure, thanks to review. @lrytz @diesalbla 😃

**Pull request merged**
