### PR TITLE
Prevent creation of Some(null) with Option.map function

### PR DESCRIPTION
**Pull request by enisher**
Current implementation of Option.map don't allow to simplify checks for nulls.

If I have something like `project.getUser.getAccount.getName` and need to prevent nullpointer exceptions I would write something like

``` scala
Option(project).map(_.getUser).map(_.getAccount).map(_.getName).orElse("Default name")
```

But the function is implemented in a way that lead to null pointer exceptions in this case.

### CODE REVIEW

**Comment by som-snytt** [comment]
`Option(project) flatMap (p => Option(p.getUser))`?

**Comment by retronym** [comment]
This is a tempting change, but actually violates an important contract of `map`, that `Some` always maps to `Some` and `None` always maps to `None`.

Perhaps you could create your own data type that serves as a null-collapsing version of `Option`, or add an extension method to `Option` like `mapNull`.

**Comment by enisher** [comment]
> This is a tempting change, but actually violates an important contract of map, that Some always maps to Some and None always maps to None.

Oh sorry, I didn't know about that contract. But what is it important for? 
I think `Some(null)` value does not have much sense, am I wrong?

BTW, `java.util.Optional` does not support that contract. 

Approach with `flatMap` definitely works, but it doesn't look that elegant. 
I could create my own method, but would be much better to have some commonly used approach.

**Comment by som-snytt** [comment]
The typelevel projects are around Nr 2 on my New Year's list, but an option-aware lens would help.

Cribbing the example at http://stackoverflow.com/a/16949289/1296806

```
scala> val fooBarL: Foo @> Option[Bar] = lensg(foo ⇒ bar ⇒ foo.copy(bar = bar.getOrElse(null)), x => Option(x.bar))
fooBarL: scalaz.@>[Foo,Option[Bar]] = scalaz.LensFunctions$$anon$5@2681dec0

scala> val barBlubL: Bar @> Option[String] = lensg(bar ⇒ blub ⇒ bar.copy(blub = blub.getOrElse(null)), x => Option(x.blub))
barBlubL: scalaz.@>[Bar,Option[String]] = scalaz.LensFunctions$$anon$5@30414542
```

then

```
scala> val a = Foo(Bar("hi"))
a: Foo = Foo(Bar(hi))

scala> val b = Foo(null)
b: Foo = Foo(null)

scala> fooBarBlubL.get(a)
res5: Option[String] = Some(hi)

scala> fooBarBlubL.get(b)
res6: Option[String] = None

```

**Pull request closed without merging**
