### PR TITLE
The new reflection

### PR DESCRIPTION
**Pull request by xeno-by**
Highlights:
- Architecture has undergone a dramatic rehash.
- Universes and mirrors are now separate entities:
  universes host reflection artifacts (trees, symbols, types, etc),
  mirrors abstract loading of those artifacts (e.g. JavaMirror loads stuff
  using a classloader and annotation unpickler, while GlobalMirror uses
  internal compiler classreader to achieve the same goal).
- No static reflection mirror is imposed on the user.
  One is free to choose between lightweight mirrors and full-blown
  classloader-based mirror (read below).
- Public reflection API is split into scala.reflect.base and scala.reflect.api.
  The former represents a minimalistic snapshot that is exactly enough to
  build reified trees and types. To build, but not to analyze - everything smart
  (for example, getting a type signature) is implemented in scala.reflect.api.
- Both reflection domains have their own universe: scala.reflect.basis and
  scala.reflect.runtime.universe. The former is super lightweight and doesn't
  involve any classloaders, while the latter represents a stripped down compiler.
- Classloader problems from 2.10.0-M3 are solved.
- Exprs and type tags are now bound to a mirror upon creation.
- However there is an easy way to migrate exprs and type tags between mirrors
  and even between universes.
- This means that no classloader is imposed on the user of type tags and exprs.
  If one doesn't like a classloader that's there (associated with tag's mirror),
  one can create a custom mirror and migrate the tag or the expr to it.
- There is a shortcut that works in most cases. Requesting a type tag from
  a full-blown universe will create that tag in a mirror that corresponds to
  the callsite classloader aka `getClass.getClassLoader`. This imposes no
  obligations on the programmer, since Type construction is lazy, so one
  can always migrate a tag into a different mirror.

Migration notes for 2.10.0-M3 users:
- Incantations in Predef are gone, some of them have moved to scala.reflect.
- Everything path-dependent requires implicit prefix (for example, to refer
  to a type tag, you need to explicitly specify the universe it belongs to,
  e.g. reflect.basis.TypeTag or reflect.runtime.universe.TypeTag).
- Some of the functions have been renamed or moved around.
  The rule of thumb is to look for anything non-trivial in scala.reflect.api.
  Some of tree build utils have been moved to Universe.build.
- staticModule and staticClass have been moved from universes to mirrors
- ClassTag.erasure => ClassTag.runtimeClass
- For the sake of purity, type tags no longer have erasures.
  Use multiple context bounds (e.g. def foo[T: ru.TypeTag : ClassTag](...) = ...)
  if you're interested in having both erasures and types for type parameters.
- reify now rolls back macro applications.
- Runtime evaluation is now explicit, requires import scala.tools.reflect.Eval
  and scala-compiler.jar on the classpath.
- Macro context now has separate universe and mirror fields.
- Most of the useful stuff is declared in c.universe,
  so be sure to change your "import c.universe._" to "import c.mirror._".
- Due to the changes in expressions and type tags, their regular factories
  are now really difficult to use. We acknowledge that macro users need to
  frequently create exprs and tags, so we added old-style factories to context.
  Bottom line: almost always prepend Expr(...)/TypeTag(...) with "c.".
- Expr.eval has been renamed to Expr.splice.
- Expr.value no longer splices (it can still be used to express cross-stage
  path-dependent types as specified in SIP-16).
- c.reifyTree now has a mirror parameter that lets one customize the initial
  mirror the resulting Expr will be bound to. If you provide EmptyTree, then
  the reifier will automatically pick a reasonable mirror (callsite classloader
  mirror for a full-blown universe and rootMirror for a basis universe).
  Bottom line: this parameter should be EmptyTree in 99% of cases.
- c.reifyErasure => c.reifyRuntimeClass.

Future work:
- Today/tomorrow I will move scala.reflect.api, scala.reflect.internal,
  scala.reflect.runtime and scala.reflect.makro into scala-reflect.jar.
  This is a new jar in Scala distribution and a new artifact in Maven.

Known issues:
- API is really raw, need your feedback.
- All reflection artifacts are now represented by abstract types.
  This means that pattern matching against them will emit unchecked warnings.
  Adriaan is working on a patch that will fix that.
- There is a noticeable performance degradation. We're working on fixing it.

### CODE REVIEW

**Comment by xeno-by** [comment]
Jenkins has failed to test the pull request, because it can't be merged cleanly with respect to already submitted pull requests (of course, this pull request merges and passes all the tests w.r.t `master`).

Please, let me know in what order you're going to merge this pull request, so that I can rebase it against the commits you tell me to.

**Comment by paulp** [comment]
I am not sure what you are using as master, but for me this pull request is a long ways from merging into master (where I mean 85cd96da35 .) Here are the conflicts.

```
both modified:      lib/scala-compiler.jar.desired.sha1
both modified:      lib/scala-library.jar.desired.sha1
deleted by us:      src/compiler/scala/reflect/internal/ClassfileModel.scala
deleted by us:      src/compiler/scala/reflect/internal/ConstantPool.scala
both modified:      src/compiler/scala/reflect/internal/Definitions.scala
both modified:      src/compiler/scala/reflect/internal/HasFlags.scala
deleted by us:      src/compiler/scala/reflect/internal/JvmClassInfo.scala
both modified:      src/compiler/scala/reflect/internal/StdNames.scala
deleted by us:      src/compiler/scala/reflect/internal/SymbolCreations.scala
deleted by us:      src/compiler/scala/reflect/internal/SymbolFlags.scala
both modified:      src/compiler/scala/reflect/internal/SymbolTable.scala
both modified:      src/compiler/scala/reflect/internal/Symbols.scala
both modified:      src/compiler/scala/reflect/internal/Trees.scala
both modified:      src/compiler/scala/reflect/internal/util/Origins.scala
both modified:      src/compiler/scala/reflect/makro/runtime/Typers.scala
both modified:      src/compiler/scala/reflect/reify/package.scala
deleted by us:      src/compiler/scala/tools/cmd/program/Simple.scala
both modified:      src/compiler/scala/tools/nsc/Global.scala
deleted by them:    src/compiler/scala/tools/nsc/ToolBoxes.scala
both modified:      src/compiler/scala/tools/nsc/ast/Trees.scala
deleted by us:      src/compiler/scala/tools/nsc/interpreter/Dossiers.scala
both modified:      src/compiler/scala/tools/nsc/interpreter/ILoop.scala
both modified:      src/compiler/scala/tools/nsc/interpreter/IMain.scala
deleted by us:      src/compiler/scala/tools/nsc/io/ClassAndJarInfo.scala
both modified:      src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
both modified:      src/compiler/scala/tools/nsc/typechecker/Implicits.scala
both modified:      src/compiler/scala/tools/nsc/typechecker/Macros.scala
both modified:      src/compiler/scala/tools/nsc/typechecker/PatternMatching.scala
both modified:      src/compiler/scala/tools/nsc/typechecker/Typers.scala
deleted by us:      src/compiler/scala/tools/nsc/util/ProxyReport.scala
deleted by us:      src/compiler/scala/tools/reflect/Invoked.scala
deleted by us:      src/compiler/scala/tools/reflect/Shield.scala
deleted by us:      src/compiler/scala/tools/reflect/SigParser.scala
both modified:      src/compiler/scala/tools/reflect/ToolBoxFactory.scala
deleted by us:      src/compiler/scala/tools/reflect/UniversalFn.scala
deleted by us:      src/compiler/scala/tools/reflect/package.scala
deleted by us:      src/compiler/scala/tools/util/SignalManager.scala
deleted by us:      src/compiler/scala/tools/util/color/ColorNames.scala
deleted by us:      src/compiler/scala/tools/util/color/package.scala
deleted by us:      src/library/scala/collection/interfaces/TraversableOnceMethods.scala
deleted by them:    src/library/scala/reflect/DummyMirror.scala
deleted by them:    src/library/scala/reflect/api/ToolBoxes.scala
both modified:      src/library/scala/reflect/api/Trees.scala
both modified:      src/library/scala/reflect/api/Universe.scala
both modified:      test/files/jvm/manifests-new.check
```

**Comment by xeno-by** [comment]
Thanks for the detailed list. Somehow the merge has gone wrong, and I effectively rebased myself on top of the original parent commit from early May. I do remember merging against the state of the art, though. Very weird. I'm on it.

**Comment by xeno-by** [comment]
See https://github.com/scala/scala/pull/662 and https://github.com/scala/scala/pull/663

**Pull request closed without merging**
