### PR TITLE
SI-6991 Emit warning about ClassfileAnnotation ...

### PR DESCRIPTION
**Pull request by soc**
... not being visible at run-time only under -Xdev.

It is now explicitly mentioned in the ScalaDoc documentation, too.

### CODE REVIEW

**Comment by lrytz** [comment]
i still think this is the wrong way to go about this problem, see the discussion on https://github.com/scala/scala/pull/1924 and https://issues.scala-lang.org/browse/SI-7041

**Comment by som-snytt** [comment]
From the @lrytz link, this is too long for a t-shirt, but maybe a further edit makes it wearable.

```
We should not punish people with spurious warnings which they cannot eliminate but if we do want to do that, I can think of better warnings to punish them with.
```

**Comment by lrytz** [comment]
sure, i agree with that, but fixing wrong with wrong doesn't make the overall situation much better.

concretely
- the error message should be improved
- deprecate  `ClassfileAnnotation` (and the warning)
- introduce `ConstantAnnotation` do to exactly what `ClassfileAnnotation` does now, but without a warning
- make `SerialVersionUID` extend `ConstantAnnotation`

we can also go ahead with https://issues.scala-lang.org/browse/SI-7041 now that we know type macros won't be in 2.11 (right?)

**Comment by soc** [comment]
This commit exists because nothing else happened for months. The warning doesn't make sense so I can't comment on any elaborate scheme to move/deprecate/create annotation traits, I just know that I won't suffer it any longer.

**Comment by xeno-by** [comment]
@soc With all due respect, I can't agree that this can serve as a justification for a merge.

**Comment by adriaanm** [comment]
I agree with @lrytz: https://issues.scala-lang.org/browse/SI-7041 is the way to go -- it's not that elaborate.

**Pull request closed without merging**
