### PR TITLE
SI-6696 removes "helper" tree factory methods

### PR DESCRIPTION
**Pull request by xeno-by**
As experience shows, these methods can easily be a source of confusion
for the newcomers: https://issues.scala-lang.org/browse/SI-6696.

I'm only leaving the `TypeTree(tp)` factory, since the facility to
set underlying types for type trees is not exposed in the public API,
as it's inherently mutable.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @retronym

**Comment by retronym** [comment]
I would miss these. We should make is convenient to use attributed trees rather than relying on names.

``` scala
def Ident(sym: Symbol): Ident
def Apply(sym: Symbol, args: Tree*): Tree
def New(sym: Symbol, args: Tree*): Tree
def This(sym: Symbol): Tree
def TypeTree(tp: Type): TypeTree
```

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@retronym I think `Apply` and `New` need to go.

The first one can be replaced `Apply(Ident(sym), args: _*)`.

The second one, I'm worried, can be quite misleading since we also expose a low-level constructor for `New` nodes.

wdyt?

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
The kitteh has gone rampant. It fails the same test over and over again despite that I already fixed it.

**Comment by retronym** [comment]
lgtm

**Comment by adriaanm** [comment]
I'll wait with merging this pending some feedback on the MIMA situation.

**Comment by retronym** [comment]
We need to clarify our position with regards to scala-reflect.jar, experimentality, and binary compatibility. Let's discuss this early next week.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
@adriaanm Deprecated the methods instead of removing them. Added some random doc entries.

**Comment by adriaanm** [comment]
awesome, @xeno-by!

**Comment by adriaanm** [comment]
LGTM

**Pull request merged**
