### PR TITLE
SI-7716 Exclude patmat synthetics from bounds checking

### PR DESCRIPTION
**Pull request by retronym**
Consider this pattern match translation, that occurs _before_ refchecks:

```
scala> val e: java.lang.Enum[_] = java.util.concurrent.TimeUnit.SECONDS

scala> e match { case x => x }
<console>:9: error: type arguments [_$1] do not conform to class Enum's type parameter bounds [E <: Enum[E]]
              e match { case x => x }
              ^
[[syntax trees at end of                 refchecks]] // <console>
package $line5 {
          case <synthetic> val x1: Enum[_$1] = $line3.$read.$iw.$iw.e;
          case4(){
            matchEnd3(x1)
          };
          matchEnd3(x: Enum[_$1]){
            x
          }
```

RefChecks turns a blind eye to the non-conformant type `Enum[_$1]` in
the label defs because of 65340ed4ad2. (Incidentally, that is far
too broad, as I've noted in SI-7756.)

This commit extends this exception to cover the synthetic ValDef `x1`.

Commit log watchers might notice the similarities to SI-7694.

Review by @adriaanm / @JamesIry. I think this one makes sense for 2.10.3. It was a regression from 2.9.x.

### CODE REVIEW

**Comment by retronym** [comment]
https://scala-webapps.epfl.ch/jenkins/job/pr-scala-rangepos/881/console

```
From github.com:scala/scala
 * [new branch]      refs/pull/2838/head -> pullreq/2838
+++ git rev-list 42e0f73311cfaf0883b85a1a41f400c3eb3cae96..pullreq/2838
++ '[' EMPTY = EMPTY ']'
++ echo 'Merging head 42e0f73311cfaf0883b85a1a41f400c3eb3cae96 of #2838 into 2.10.x.'
Merging head 42e0f73311cfaf0883b85a1a41f400c3eb3cae96 of #2838 into 2.10.x.
++ git fetch origin --depth 10000
++ git fetch origin 2.10.x
From github.com:scala/scala
 * branch            2.10.x     -> FETCH_HEAD
++ [[ -f /localhome/jenkins/c/workspace/pr-scala-rangepos/mergetarget ]]
++ git checkout --detach -f 5bdb828a2ef3fa874c2c19e8415d3d670c022ae1
Previous HEAD position was 8053c19... Merge pull request #2834 from retronym/ticket/7752
HEAD is now at 5bdb828... Merge pull request #2819 from som-snytt/issue/regextract-char
++ git clean -fxd
++ git merge 42e0f73311cfaf0883b85a1a41f400c3eb3cae96
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1229 and retry the command.
Auto-merging test/files/run/t6392b.check
CONFLICT (content): Merge conflict in test/files/run/t6392b.check
Auto-merging src/reflect/scala/reflect/runtime/SymbolLoaders.scala
Auto-merging src/reflect/scala/reflect/runtime/ReflectionUtils.scala
```

Do we have some cross talk on the line?

```
++ [[ -f /localhome/jenkins/c/workspace/pr-scala-rangepos/mergetarget ]]
++ git checkout --detach -f 5bdb828a2ef3fa874c2c19e8415d3d670c022ae1 // that's in another PR that targets master!!
```

**Comment by retronym** [comment]
PLS REBUILD ALL

**Comment by JamesIry** [comment]
I have to kick it down the road, I'm cutting 2.10.3-RC1 now.

**Comment by JamesIry** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Since we're waiting for #2842 anyway, maybe this can go in as well?

**Comment by adriaanm** [comment]
LGTM

**Comment by adriaanm** [comment]
@retronym, sorry about the cross-talk, should be fixed now
I was creating this mergetarget file to track the sha for master, and it was intended to be propagated from pr-scala-distpack to its downstream jobs, but I forgot to add it to the copy artifacts line (well, I added in pr-scala-test where it was truly necessary, but then wrongly decided that was enough, hoping to get back to some actual work)

**Pull request merged**
