### PR TITLE
Scaladoc implicit conversions

### PR DESCRIPTION
**Pull request by VladUreche**
See https://github.com/VladUreche/scala/tree/feature/doc-implicits for the history.
See https://scala-webapps.epfl.ch/jenkins/view/scaladoc/job/scaladoc-implicits-nightly/ for nightlies.

Many thanks fly out to Adriaan for his help with implicit search!

THIS PASSES THE TESTSUITE: https://scala-webapps.epfl.ch/jenkins/view/scaladoc/job/scaladoc-implicits-nightly/30/consoleFull

### CODE REVIEW

**Comment by jsuereth** [comment]
Just want to say, that looking at the generated Scaladocs, I love this feature already.   Kudos.

**Comment by lrytz** [comment]
excellent! from now on, people will think that implicits are green :)

where should we report bugs?

**Comment by VladUreche** [comment]
@jsuereth Thanks, I hope people will find it useful.
@lrytz For quick fixes before ScalaDays send me an email and I'll try to fix asap. For more complex bugs and layout stuff please file tickets on Jira.

**Comment by adriaanm** [comment]
cool!

one quick improvement suggestion: in e.g., "Implicit information:
This member is added by an implicit conversion from Array[T] to ArrayOps[T] performed by method genericArrayOps in scala.Predef." <-- could "genericArrayOps"  link to the method's entry in the scaladoc?

**Comment by VladUreche** [comment]
@adriaanm Thanks! I will do it as soon as we have support for links to methods (it's listed on the bug tracker, but I didn't get to it yet)

**Comment by dotta** [comment]
Applause!

**Comment by VladUreche** [comment]
@aborg0 sorry for the ridiculously long response time, I just noticed your comment (somehow, gmail archived the notification right away). What you show is indeed a bug -- it should be `Ordered[A] to Ordering[A] by method oderingToOrdered`.

Can you file it [on Jira](http://issues.scala-lang.org/) and assign it to me? I'll have a look at what's happening.

**Comment by aborg0** [comment]
@VladUreche [Done](https://issues.scala-lang.org/browse/SI-9585).

**Comment by VladUreche** [comment]
@aborg0 Thanks!

**Pull request merged**
