### PR TITLE
Added more variants to achieve getLinkPos

### PR DESCRIPTION
**Pull request by dragos**
Review by @lrytz

getLinkPos is known to be flakey. This commit tries some variants and logs what failed.
(cherry picked from commit 848756d47b980472996cd83409bda11f8fb5cac0)

Conflicts:

```
src/compiler/scala/tools/nsc/interactive/Global.scala
```

### CODE REVIEW

**Comment by xeno-by** [comment]
Could you be more specific about how exactly it is flakey? That could help us with Sublime as well.

**Comment by dragos** [comment]
@xeno-by, it would not find the target of a hyperlink sometimes, but I could not find a reproducible test case. Our assumption was that some symbols were not correctly adapted to a new run. Since this fix is in the presentation compiler, it would readily be available to any client, including esime or your sublime plugin.

Note that this is a backport to `2.9.x` of an existing commit from `2.10.x`.

**Comment by dragos** [comment]
I'll ask for the same tolerance as in the case of pull-req #1153. The rangepos test fails. It's not a spurious failure, but simply a different initialization sequence that breaks down in 2.9. I'd say it works _by chance_ in 2.10. 

Adding a few judicious `lazy` modifiers made the compiler lift off the ground, but failed immediately with range pos failures. Since we don't look into supporting 2.9 for too long, I'll leave it at that and ignore them in the 2.9.x branch, as my predecessors have done ;-)

**Comment by lrytz** [comment]
lgtm

**Pull request merged**
