### PR TITLE
Revise paragraph (a revised #3164)

### PR DESCRIPTION
**Pull request by Blaisorblade**
Revise text further, following suggestions in #3164 and part of the suggestions by @som-snytt. But I've kept "appear", since this paragraph documents the external behavior, not the implementation.

Review by @heathermiller.

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM -- glad we converged quickly :-)

**Comment by Blaisorblade** [comment]
That was fast! Thanks!

**Comment by adriaanm** [comment]
Thanks to all poets involved -- I just clicked a button :-)

**Comment by awl** [comment]
Sorry, but I really think that you guys got this one wrong. "For instance" is not the right wording here, which is exactly why I changed it from "e.g.," which essentially means "for instance," to "i.e.," which means, essentially, "that is." "For instance" should be used to give an example that clarifies a previous phrase, but here you are enumerating _the only two_ possible outcomes, not providing an example, and this means that you should replace "For instance" with something like "that is," "meaning," or, in fact, nothing at all.

Any of these are proper, but I adamantly believe that "for instance" is distinctly wrong. 

This means that two DefaultPromises that are linked will appear, to external callers, to have exactly the same state and behaviour -- both will appear as incomplete, or as complete with the same result value.

This means that two DefaultPromises that are linked will appear, to external callers, to have exactly the same state and behaviour, i.e. both will appear as incomplete, or as complete with the same result value.

This means that two DefaultPromises that are linked will appear, to external callers, to have exactly the same state and behaviour, meaning both will appear as incomplete, or as complete with the same result value.

**Comment by som-snytt** [comment]
I agreed with @awl on the other pr.

At least it doesn't show up in public scaladoc, so we won't be raked over the coals on hacker news because of it.

**Pull request merged**
