### PR TITLE
Si 6261

### PR DESCRIPTION
**Pull request by rklaehn**
This is basically the improvements made to HashSet in SI-6197, SI-6198, SI-6220 applied to HashMap.

The test case is the same as the test cases for SI-6197, SI-6198 and SI-6220 as well.

If you want this as a single commit, or if I should create a SI for each tiny change, let me know.

I am not sure if assertions are OK in scala collections, or if they should be commented out for test performance reasons. However just having them in there commented out is preferable to not having them at all because they show very concisely the assumptions made in the data structure.

### CODE REVIEW

**Comment by jsuereth** [comment]
Again, this LGTM.  As for asserts, I'm on the fence.  The compiler can remove them with the right elide settings, but they're in there by default.   I usually don't like asserts for user-facing exceptions because they don't tell a _user_ anything.  i.e. what does it mean if the bitCount is the wrong length?   How did I get in that situation?  How can I correct myself?

Error messages should clearly delineate what a user can do to fix things.   The asserts are great documentation as-is, but the errors are only really useful for us.  Let me mull it over and see if I can think of a way to phrase things that helps the common man, as well as a library dev.

Other than that, just wanted to say thank you for continuing to help improve performance.  I'm hoping with Gregk's work we'll soon have a good way to test the cost of (potentially) megamorphic method calls.

**Comment by rklaehn** [comment]
Is there still a chance of this going into 2.10, or do you want me to close and resubmit to master?

Regarding the assertions: the main benefit of having them is to have them enabled while running the test suite. I found some bugs that way. If they had been in there from the start something obvious like a HashSetCollision1 with one element would have been noticed from the beginning. Once a class passes the test suite you might as well comment them out. It would be great if you could somehow have something like an assertion that is just enabled during testing. 

The assertions are not user-facing. It should not be possible for a user of the collections to get one of the assertions to fail.

**Comment by jsuereth** [comment]
At this point, your hold-up is those asserts.   An assert error with no message is the most useless thing for a user.  I'd merge this immediately if the asserts held helpful information for the _USER_ of the collection.   If they're 'the world exploded' messages, then perhaps we need to find alternative ways to deal with that failure.   In that case, you want to print enough debugging info that a user can post a bug and we can fix it.  As is, they're better than nothing, but still not ideal.

**Pull request merged**
