### PR TITLE
SI-6485 stops creating extmethods for macros

### PR DESCRIPTION
**Pull request by xeno-by**
Macros don't correspond to bytecode-level methods, therefore
there's no need to undergo any transformations past typer.

### CODE REVIEW

**Comment by xeno-by** [comment]
review @paulp @retronym @gkossakowski

**Comment by xeno-by** [comment]
Submitting this against wip, since the fix is affecting value classes and is very-very simple.

**Comment by retronym** [comment]
lgtm

**Comment by paulp** [comment]
LGTM2.

**Pull request merged**
