### PR TITLE
Merge 2.10.x

### PR DESCRIPTION
**Pull request by paulp**
Since #950 created conflict between master and 2.10.x, I merged 2.10.x into master and offer it here.

### CODE REVIEW

**Comment by paulp** [comment]
PLS REBUILD ALL

**Comment by adriaanm** [comment]
Thanks for brokering peace between master&2.10. I had this commit pending as well and was about to push the old-fashioned way (https://github.com/adriaanm/scala/commit/078a1c5fae09970d22b886831e36745b7f7e25db). It's tested and ready to go.
It seems a bit cleaner to just push a merge commit that also packs the necessary conflict resolution, or should we standardize on pull requests for merges?

**Comment by adriaanm** [comment]
Closing as it introduces indentation changes (probably because someone has been using tabs instead of spaces).

`git diff e950312901..078a1c5fae -w` is empty, so I'll just push my merge instead.

**Comment by paulp** [comment]
Introduces indentation changes to whom? I merge with "-X ignore-space-change" so I think any "changes" are actually it ignoring the changes which shouldn't have been introduced in the 2.10.x branch.

**Comment by paulp** [comment]
I agree that one merge commit is the way to go, I'm really hamstrung by the workflow; to avoid testing everything myself, I have to push to github, but then once I do, I can't fix what the test run finds without a dribble of commits.

**Comment by paulp** [comment]
For reference, here is my whole merge command, all of which I think we should standardize on (although the "100" is obviously arbitrarily chosen.)

```
git merge --log=100 -s recursive -X ignore-space-change -X patience
```

**Comment by adriaanm** [comment]
[re: indentation] a biased statement, admittedly, but I checked the indentation was correct in my version

[re: hamstrung] i run `ant test-opt` locally before pushing -- you could also use https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/ after you've pushed to your own github repo (without creating a pull request) to run the exact same job as will be run on actual checkin

[re: merge-fu  ] noted & aliased

**Comment by paulp** [comment]
Yes, I am vaguely familiar with "ant test-opt", having run it more times than any human on earth.  It massively increases the friction to have to devote a machine for an hour to testing.  In my view all the things I could do are beside the point; life should, and could, be like this:

```
1) make change ; send untested pull request
2) if tests pass, the pull request enters "real" pull request queue
2b) if tests fail, notification of this is sent to pull requestor AND NOBODY ELSE
```

...and that's it.  Every additional manual step, test run, double checky thing which must be done on every pull request means that many fewer incremental things will be done.  Giant patches are bad; small patches are good; we should encourage small patches to the extent humanly possible.

**Comment by paulp** [comment]
And "tabs instead of spaces" should fail your test run; there's no reason we should even be reviewing pull requests which aren't fully tested and conform to all programmatically enforceable style.

**Comment by paulp** [comment]
Mmm, maybe ignore-space-change is actually the problem.  In our whitespace diff, there are several files where mine is right and yours is wrong; mine has a completely empty line and yours has a line with trailing spaces.  But where the code is misaligned, maybe it's self-inflicted - the code has been restructured and lines where only the indentation has changed are ignored.  That's too bad.  In that case I suggest ignore-space-at-eol, that would be the best of both worlds in this instance.

**Comment by adriaanm** [comment]
Yep, I kind of expected you to have heard of test-opt (and scala-checkin-manual?). Also, your vision of the pull request mechanism completely aligns with mine. We'll have this and other automation goodness (such as whitespace testing) before 2012 is over. I promise.

I felt that trailing space was preferable to missing leading space. Yes, let's ignore-space-at-eol.

**Comment by paulp** [comment]
I didn't mean to suggest that breaking the indentation was preferable to anything; at the time I thought "it's not me, it's you."

**Pull request closed without merging**
