### PR TITLE
SI-5353 Fix Array unsoundness

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
The first commit had to be adapted, because there were some moving parts due to the `Foo.tpe` -> `FooTpe` refactoring and @xeno-by's changes in https://github.com/scala/scala/commit/a45d3e5658a1ccb57d3b420eb36d84f7170404b5.
Could @xeno-by and @paulp have a look whether the end result is to their liking?

The second commit fails with this issue:

```
!! 1 - run/t5353c                                [output differs]
% diff test/files/run/t5353c-run.log test/files/run/t5353c.check
@@ -38,8 +38,8 @@ class SString
                   in J_0 def       javaVarargs_c():  void                  /  abstract void J_0.javaVarargs_c(T...)
               in SString def       javaVarargs_a():  void                  /  void SString.javaVarargs_a(scala.collection.Seq<jl.String>)
               in SString def       javaVarargs_a():  void                  /  void SString.javaVarargs_a(jl.String[])
-              in SString def       javaVarargs_c():  void                  /  void SString.javaVarargs_c(jl.String[])
               in SString def       javaVarargs_c():  void                  /  void SString.javaVarargs_c(scala.collection.Seq<jl.String>)
+              in SString def       javaVarargs_c():  void                  /  void SString.javaVarargs_c(jl.String[])
               in SString def    scalaArrayGet_aa():  jl.String             /  jl.String SString.scalaArrayGet_aa()
    bridge     in SString def    scalaArrayGet_aa():  jl.Object             /  jl.Object SString.scalaArrayGet_aa()
               in SString def    scalaArrayGet_ac():  jl.String             /  jl.String SString.scalaArrayGet_ac()
@@ -63,8 +63,8 @@ class SLong
                   in J_0 def       javaVarargs_c():  void                  /  abstract void J_0.javaVarargs_c(T...)
                 in SLong def       javaVarargs_a():  void                  /  void SLong.javaVarargs_a(scala.collection.Seq<jl.Object>)
                 in SLong def       javaVarargs_a():  void                  /  void SLong.javaVarargs_a(long[])
-                in SLong def       javaVarargs_c():  void                  /  void SLong.javaVarargs_c(long[])
                 in SLong def       javaVarargs_c():  void                  /  void SLong.javaVarargs_c(scala.collection.Seq<jl.Object>)
+                in SLong def       javaVarargs_c():  void                  /  void SLong.javaVarargs_c(long[])
                 in SLong def    scalaArrayGet_aa():  long                  /  long SLong.scalaArrayGet_aa()
    bridge       in SLong def    scalaArrayGet_aa():  jl.Object             /  jl.Object SLong.scalaArrayGet_aa()
                 in SLong def    scalaArrayGet_ac():  long                  /  long SLong.scalaArrayGet_ac()
@@ -88,8 +88,8 @@ class SLongBox
                   in J_0 def       javaVarargs_c():  void                  /  abstract void J_0.javaVarargs_c(T...)
              in SLongBox def       javaVarargs_a():  void                  /  void SLongBox.javaVarargs_a(scala.collection.Seq<jl.Long>)
              in SLongBox def       javaVarargs_a():  void                  /  void SLongBox.javaVarargs_a(jl.Long[])
-             in SLongBox def       javaVarargs_c():  void                  /  void SLongBox.javaVarargs_c(jl.Long[])
              in SLongBox def       javaVarargs_c():  void                  /  void SLongBox.javaVarargs_c(scala.collection.Seq<jl.Long>)
+             in SLongBox def       javaVarargs_c():  void                  /  void SLongBox.javaVarargs_c(jl.Long[])
              in SLongBox def    scalaArrayGet_aa():  jl.Long               /  jl.Long SLongBox.scalaArrayGet_aa()
    bridge    in SLongBox def    scalaArrayGet_aa():  jl.Object             /  jl.Object SLongBox.scalaArrayGet_aa()
              in SLongBox def    scalaArrayGet_ac():  jl.Long               /  jl.Long SLongBox.scalaArrayGet_ac()
```

I haven't looked into it yet, but maybe there was just code which was reordered without updating the check file?
@paulp, any insight?

**Comment by paulp** [comment]
The tests in the second commit were completely WIP, I just didn't want to waste them. I have no reason to believe they would pass without at the very least updating checkfiles.

**Comment by paulp** [comment]
It's sure to be to my liking if the existing tests pass and one or more of the new ones does. I've switched to a very results-oriented metric though.

**Comment by soc** [comment]
I think the issue might be caused because the methods are getting sorted in https://github.com/soc/scala/commit/964ba0a4ee6c94bf6e7ddab0eebfb91f3981c65d#L4R115, but the offending difference `toGenericString` is not part of the ordering tuple: `def methods(c: Class[_]) = c.getMethods filterNot (_.getDeclaringClass == classOf[Object]) sortBy (m => (m.getDeclaringClass.getName, m.getName, m.isBridge))`.

That way, if the JVM implementation returns the methods in a different order, they won't end up in a predictable order after sorting.

**Comment by soc** [comment]
Would it be possible to update the Java 6 which is running on the build machines to something more up-to-date?
The version there is more or less one year behind the last public release of Java 6 (1.6.0_33: 2012-06-12, 1.6.0_45: 2013-04-16).

**Comment by soc** [comment]
Weird, `test/files/run/t5353c.scala` doesn't seem to be executed (probably because of the `test/files/run/t5353c` ... the check file `test/files/run/t5353c.check` also belongs to the output of the folder, not to the output of the single scala file.)¹

I'll rename `test/files/run/t5353c.scala` to `test/files/run/t5353d.scala` and add a new checkfile for it.

¹ Is this a bug?

**Comment by soc** [comment]
Looks like the difference remains in the full range of Java 6 versions. I'm using partest's filters instead.

**Comment by soc** [comment]
Could @xeno-by and @paulp have a look?

**Comment by xeno-by** [comment]
I took a look, but I'm not sure that I'm qualified enough to comment on post-typer phases. Maybe @retronym or @JamesIry could chime in?

**Comment by adriaanm** [comment]
This needs a rebase.

**Pull request closed without merging**
