### PR TITLE
Harden DisplayReporter against null messages

### PR DESCRIPTION
**Pull request by retronym**
Relates to #6635

### CODE REVIEW

**Comment by som-snytt** [comment]
That code is also broken, I neglected to get back to it. But you can't beat checking for null.

**Comment by som-snytt** [comment]
In the old days,
```
scala 2.12.6> import scala.tools.nsc._, reporters._
import scala.tools.nsc._
import reporters._

scala 2.12.6> val r = new ConsoleReporter(new Settings)
r: scala.tools.nsc.reporters.ConsoleReporter = scala.tools.nsc.reporters.ConsoleReporter@78cfa264

scala 2.12.6> r.echo(null)
java.lang.NullPointerException
  at scala.collection.immutable.StringLike$$anon$1.<init>(StringLike.scala:113)
  at scala.collection.immutable.StringLike.linesWithSeparators(StringLike.scala:111)
  at scala.collection.immutable.StringLike.linesWithSeparators$(StringLike.scala:111)
  at scala.collection.immutable.StringOps.linesWithSeparators(StringOps.scala:29)
  at scala.collection.immutable.StringLike.lines(StringLike.scala:130)
  at scala.collection.immutable.StringLike.lines$(StringLike.scala:129)
  at scala.collection.immutable.StringOps.lines(StringOps.scala:29)
  at scala.reflect.internal.util.StringOps.trimAllTrailingSpace(StringOps.scala:48)
  at scala.reflect.internal.util.StringOps.trimAllTrailingSpace$(StringOps.scala:48)
  at scala.reflect.internal.util.StringOps$.trimAllTrailingSpace(StringOps.scala:95)
  at scala.tools.nsc.reporters.ConsoleReporter.echo(ConsoleReporter.scala:48)
  ... 28 elided
```
I guess `String.valueOf` never got you in trouble, like buying IBM.

**Review by som-snytt — APPROVED** [review]
Harden thy heart.

**Comment by retronym** [comment]
We have `reporter.error(tree.pos, ex.getMessage())` in a few places which is a source of null messages (fittingly, with `NullPointerException#getMessage`!)

**Pull request merged**
