### PR TITLE
BigInt tests

### PR DESCRIPTION
**Pull request by denisrosset**
All tests are passing and cover nearly all methods of BigInt except the `Range` methods.

~~That includes a failing test.~~

### CODE REVIEW

**Comment by denisrosset** [comment]
Why aren't the tests passing? They should now (had misinterpreted the hashCode contract).

**Comment by som-snytt** [comment]
The "combined" check indicates the "earlier commit marked failure" condition, but I agree that the icons are difficult to interpret. I wish it were easy to see the "hard" failure and then whether subsequent commits would otherwise pass.

**Comment by Jasper-M** [comment]
While your PR is still in development you can circumvent the combined check by adding `[ci: last-only]` in the title of your PR.

**Comment by denisrosset** [comment]
Thanks I squashed commits, the mistake I made when confusing `##` and `hashCode` is not relevant to the subproject.

**Comment by plokhotnyuk** [comment]
Just curious... Will having these tests merged open an ability to fix Java's algorithm of parsing from string representation to have `O(n)` complexity for the radix values 2,4,8,16,32 and `O(n^1.5)` for others instead of `O(n^2)` that we have currently?

**Comment by denisrosset** [comment]
@plokhotnyuk It's not my call to answer that, but indeed the goals of those tests is to introduce optimizations.

We want to make `BigInt` as cheap as a boxed `Long` when the number fits.

**Comment by plokhotnyuk** [comment]
@denisrosset ICYMI: [Here](https://github.com/plokhotnyuk/jsoniter-scala/blob/b369d940532ed46aa55dd0ba50454ef433da37ce/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1565-L1822) are routines for efficient and safe parsing from the decimal string representation for `BigInt` and `BigDecimal` which can be easily adopted for the future version of `BigInt` too.

**Comment by denisrosset** [comment]
@plokhotnyuk I've written an appropriate number of tests for the optimizations I want to apply, and those optimizations focus on Long-sized BigInts. Have you tried getting a Java version of your code merged in OpenJDK?

For the others: the CI is failing due to the 1.5h time limit. I've reduced the size of the BigInt in the tests. What is going on?

**Comment by denisrosset** [comment]
Thanks @SethTisue . I'll be progressing on the implementation front independently; for it makes sense to merge the tests before making implementation changes.

I'll open another PR for the "real work" once we get the tests running properly. Tell me if there's something I have to do, or that I have missed.

**Comment by som-snytt** [comment]
To coin a phrase, squash. Each commit should pass, not just the last, before merge. And probably granularity of one commit is appropriate here?

**Comment by denisrosset** [comment]
@som-snytt I squashed. The first commit in this chain fails because

`The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by som-snytt** [comment]
Thanks. Then the only remaining question is, how will the 49ers perform without Kittle?

Edit: you must `push -f` the squash.

**Comment by SethTisue** [comment]
Our Travis-CI build has been plagued by multiple issues lately. I hit "restart" and maybe it will squeak in under the time limit this time. But regardless, the important thing is that Jenkins (the "validate-main" job) passes, Travis is just a bonus as long as the failure doesn't appear related to the changes in the PR.

**Comment by som-snytt** [comment]
I can't even tell if all the commits passed main.

I see `Build [10228] scala/scala#8526 at 7857e4 (Nov 8...` is still blinking icon.

That's what I meant when I said I can't see what the status of each intermediate commit is. Also I'm not sure what the combined failure means: it doesn't link to "here is the first failure I noticed".

Also, I was distracted watching the 49ers lose in OT because they couldn't kick a FG.

Edit: jenkins needs a "bonus" plugin to run tasks which won't fail a stage but if they succeed will add 🎊  or 🎆 or :tada: or 🥇 or something.

**Comment by SethTisue** [comment]
Travis is green now. Something seems off in the GitHub/Jenkins integration, there shouldn't be a red X next to 9f8116 above given that https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/10229/ is green ; I expect any discrepancy there will go away once the commits are squashed/rebased.

**Comment by lrytz** [comment]
Squased the commits. This is good to go, no?

**Comment by denisrosset** [comment]
Indeed, can we get this merged?

In parallel, I'm working on the optimizations.

**Comment by som-snytt** [comment]
There is maybe a stray import added to a test, which should use `assertTrue` or whatever.

**Pull request merged**
