### PR TITLE
Merge/master to java7 2

### PR DESCRIPTION
**Pull request by retronym**
Trivial whitespace merge.

Review by @gkossakowski

### CODE REVIEW

**Comment by som-snytt** [comment]
I don't think I understand what [nomaster] means.

**Comment by retronym** [comment]
@som-snytt  Did you see wrong content in the diff, or are you just wondering about why those commits are in the merge?

I didn't think to check and exclude for `[nomaster]` commits as they (should) have already been excluded when merged from `2.10.x` to `master`. They still appear in the history (which git mandates), but we ignore they contents of the patch.

**Comment by som-snytt** [comment]
Thanks, now I understand what [nomaster] means.

**Comment by gkossakowski** [comment]
LGTM

Thanks.

**Pull request merged**
