### PR TITLE
Update Dotty to 0.16.0-RC3

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by lrytz** [comment]
There are some syntax errors: https://api.travis-ci.org/v3/job/543772959/log.txt

**Comment by SethTisue** [comment]
Jenkins being green this suggests that ff35e9361cf88f2493361711beba7f59259d2281 ought to be applied to `script/jobs/validate/test` (or to something it invokes). oh, and I see already said so once over at https://github.com/scala/scala/pull/7800#issuecomment-472077416, but nobody else weighed in

anyway, this is mergeable regardless, once the errors are addressed

**Comment by SethTisue** [comment]
@anatoliykmetyuk once you've slept off your post Scala Days hangover...

**Comment by smarter** [comment]
sbt-dotty in https://github.com/scala/scala/blob/2.13.x/project/plugins.sbt should be upgraded to 0.3.2 too.

**Comment by smarter** [comment]
Actually the latest release of sbt-dotty is 0.3.3, not 0.3.2.

**Comment by anatoliykmetyuk** [comment]
This should fix the syntactic errors.

**Comment by anatoliykmetyuk** [comment]
Is the Jenkins error related to this PR?

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Could not find artifact org.scala-lang:scala-library:jar:2.13.0-pre-69c1124-SNAPSHOT in temp (https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/)`

**Comment by adriaanm** [comment]
/rebuild 

We had some disk space issues on our artifactory.

**Pull request merged**
