### PR TITLE
Add support for running a specific Junit test/method.

### PR DESCRIPTION
**Pull request by gourlaysama**
Unless I really missed something, there is currently no way to run a
specific Junit test (class or method). Running the whole thing is going
to get worse and worse since Junit is supposed to be the preferred way,
so here it goes:

``` sh
# will run all methods in a test file
ant test.junit -Dtest.class=scala.WhateverTest

# will run a specific method (just an alias for the one below)
ant test.junit -Dtest.class=scala.WhateverTest -Dtest.method=mymethod

# will run several methods (comma separated)
ant test.junit -Dtest.class=scala.WhateverTest -Dtest.methods="foo,bar"
```

`test.method(s)` without `test.class` is just ignored (all tests are
run).

### CODE REVIEW

**Comment by gourlaysama** [comment]
@gkossakowski @som-snytt

**Comment by lrytz** [comment]
Note: You can run individual JUnit tests within IntelliJ. See https://github.com/scala/scala/tree/2.11.x/src/intellij on how to import the project.

**Comment by som-snytt** [comment]
A minute (on my machine) is already too long for TDD.  For f macro, I wound up with a separate Eclipse project, then copy over the couple of files when done. Big +1.

**Comment by gkossakowski** [comment]
LGTM.

Both IntelliJ and Eclipse offer running individual tests but having this functionality on command line makes sense too.

**Comment by retronym** [comment]
Great contribution! I'm ashamed to say I once spent a few hours trying (and failing) to do this as a custom JUnit runner after being unable to find the right incantation for the Ant task.

**Pull request merged**
