### PR TITLE
SI-5789 Removes assertion about implclass flag in Mixin.scala

### PR DESCRIPTION
**Pull request by JamesIry**
The assertion that the class being mixed from should be an implclass
seems reasonable, but the flag isn't always set. In order to stop the
bleeding this fix turns the assertion into a debug warning. Issue SI-6782
will track figuring out the root cause of the missing flag.

### CODE REVIEW

**Comment by JamesIry** [comment]
review @paulp

**Comment by paulp** [comment]
I hacked that test together as "fast path to reproduction" but as a matter of good practice I'd rather not have lines like

```
lines exists (_ contains "Abandoning crashed session")
```

in the test suite. And I only had to hack it because I was trying to avoid partest - for within partest, there's a class for repl tests. Look for tests which use [ReplTest](https://github.com/scala/scala/blob/master/src/partest/scala/tools/partest/ReplTest.scala) and do what they do.

**Comment by JamesIry** [comment]
@paulp much better

**Comment by paulp** [comment]
Much better indeed. LGTM.

**Pull request merged**
