### PR TITLE
Possible fix for SI-8782

### PR DESCRIPTION
**Pull request by Shiti**
Modified Range.Double to use NumericRange of Double instead of using BigDecimal internally and then converting it to Double.

Same change can be made on the other branches 2.9.x, 2.10.x and 2.11.x

### CODE REVIEW

**Comment by gkossakowski** [comment]
PLS REBUILD ALL

**Comment by Ichoran** [comment]
Same change can't be made with binary compatibility, so this is 2.12 only.  Also, have you checked that the various problems with Range aren't a problem with NumericRange?

**Comment by Shiti** [comment]
@Ichoran Can you please point me to the problems you were talking about?

**Comment by Ichoran** [comment]
See https://issues.scala-lang.org/browse/SI-8620 and related links.

**Comment by Shiti** [comment]
This does not fix any of the other issues related to Floating Point ranges. 
Will Floating Point ranges be deprecated from 2.12.x?

**Comment by Ichoran** [comment]
I think that was the consensus.  It's not finalized.  Also, since BigDecimal is really slow, deferring to BigDecimal ranges is really (surprisingly) slow.  So thank you for the patch!  But I am not sure this is the way we want to go (I need to have a final discussion with other maintainers about the issue).

**Comment by retronym** [comment]
Given the discussion above and the failed build, I'm going to close this pull request for now. Feel free to resubmit if we find a consensus on the right way forward.

**Pull request closed without merging**
