### PR TITLE
Preparation for using default methods in traits

### PR DESCRIPTION
**Pull request by retronym**
- Don't create specialized overrides in traits
- Enable emission of default methods in GenBCode

### CODE REVIEW

**Comment by retronym** [comment]
Getting the ball rolling...

Review by @adriaanm @SethTisue @lrytz 

The specialization change has been looked over by @VladUreche over in https://github.com/scala/scala-dev/issues/36

**Comment by adriaanm** [comment]
Excellent! Subsumes & improves the ugly hack in https://github.com/scala/scala/compare/2.12.x...adriaanm:defaults

The branch is super-wippy and I won't have much time to polish between JVMLS, customer stuff and speaking at SBTB on Friday, but I did try to flesh out the commit messages a bit as a start to coordinate.

**Comment by retronym** [comment]
@lrytz I don't think we should change `isDeferred` as part of this change; we need to consider the special meaning of `DEFERRED` in `findMember` to determine the whether or not to mark Java default interface methods in this way.

**Comment by lrytz** [comment]
OK, so you are saying we should push this work to a separate PR?

**Comment by retronym** [comment]
@lrytz Yep, I think we should merge this to open up the path to emit defaults, and leave the larger/harder question about whether to treat defaults as non-DEFERRED to future work.

**Comment by lrytz** [comment]
LGTM

**Pull request merged**
