### PR TITLE
SI-6240 synchronization for runtime reflection

### PR DESCRIPTION
**Pull request by xeno-by**
This is the first step in synchronizing reflection. First we get it working in multi-threaded environment, afterwards I'll look into making it fast (see the comments in `Gil.scala` for more information).

### CODE REVIEW

**Comment by xeno-by** [comment]
Supersedes https://github.com/scala/scala/pull/2018

**Comment by xeno-by** [comment]
review @retronym @paulp @adriaanm @gkossakowski

**Comment by xeno-by** [comment]
@adriaanm Any idea why the commits aren't ordered according to the history? `e9a9a47` is everyone's parent, but it's shown in the middle of the list.

**Comment by adriaanm** [comment]
github sorts them by date I think

**Comment by xeno-by** [comment]
@adriaanm The failures are spurious by the way, and the same tests were failing for some pull request nearby as well. Is there a problem with our new kitty?

**Comment by xeno-by** [comment]
@adriaanm Yes, indeed, it does sort them by date. `rebase` makes it so easy to violate this :)

**Comment by adriaanm** [comment]
are you sure they're spurious? it even has a list of failed tests..

**Comment by xeno-by** [comment]
Just did `git checkout 5aa932 && ant clean build && partest ...`.

**Comment by adriaanm** [comment]
that's not the same partest run by the kitty

SCALAC_OPTS="-optimize" test/partest is one difference

**Comment by xeno-by** [comment]
Wait, I ran tests in a different terminal window. Sorry, let me recheck :(

**Comment by xeno-by** [comment]
Will also do `ant all.clean build-opt`. Back in 10-20 minutes.

**Comment by adriaanm** [comment]
I'm calling it a day here :-)

**Comment by adriaanm** [comment]
this is the log of the failed run: https://scala-webapps.epfl.ch/jenkins/job/pr-rangepos-per-commit/13/

**Comment by paulp** [comment]
@xeno-by I've found I don't like it for reasons which I don't entirely remember, but you may be interested to know of

```
alias grmnow='git rebase --ignore-date master'
```

**Comment by xeno-by** [comment]
Thank you, guys! Good night, Adriaan!

**Comment by xeno-by** [comment]
The failure is indeed spurious.

**Comment by xeno-by** [comment]
PLS REBUILD ALL

**Comment by xeno-by** [comment]
Looks like a spurious error to me. Can't reproduce it locally. Kitty, PLS REBUILD ALL.

**Comment by xeno-by** [comment]
Jenkins has exploded :(

**Comment by xeno-by** [comment]
Anyways the PR still contains a logic error, and I'm going to retract it.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scala/scala/pull/2081

**Pull request closed without merging**
