### PR TITLE
Upgrade Dotty to 0.19.0-RC1

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Comment by lrytz** [comment]
@anatoliykmetyuk could you rebase on current 2.13.x? I tried to force-push to `dotty-staging:dotty-release-0.19.0-RC1`, but it was denied.

**Comment by anatoliykmetyuk** [comment]
@lrytz done

**Comment by lrytz** [comment]
I don't know why, but travis is not showing the output of the dotty compilation, probably related to the use df `travis_wait` (cc @retronym).

Locally, I get:

```
[info] Compiling 620 Scala sources and 148 Java sources to /Users/luc/scala/scala13/build/quick/classes/library ...
[warn] bad option '-Ynew-collections' was ignored
[error] -- Error: /Users/luc/scala/scala13/src/library/scala/collection/Iterable.scala:831:76
[error] 831 |  override def tapEach[U](f: A => U): C = fromSpecific(new View.Map(this, { a: A => f(a); a }))
[error]     |                                                                            ^^^^
[error]     |parentheses are required around the parameter of a lambda
[error]     |This construct can be rewritten automatically under -language:Scala2 -rewrite.
[error] -- Error: /Users/luc/scala/scala13/src/library/scala/collection/SeqView.scala:28:75
[error] 28 |  override def tapEach[U](f: A => U): SeqView[A] = new SeqView.Map(this, { a: A => f(a); a })
[error]    |                                                                           ^^^^
[error]    |parentheses are required around the parameter of a lambda
[error]    |This construct can be rewritten automatically under -language:Scala2 -rewrite.
[warn] one warning found
[error] two errors found
[error] (library / Compile / compileIncremental) Compilation failed
[error] Total time: 22 s, completed Sep 24, 2019 3:46:16 PM
```

**Comment by retronym** [comment]
Hmmm, [apparently](https://travis-ci.community/t/no-output-logged-when-using-travis-wait-command/1909/2) it is the `set -e` (which I added to `.travis.yml` 2.13.x in #7933)

**Comment by smarter** [comment]
> [warn] bad option '-Ynew-collections' was ignored

This option is no longer needed with dotty >= 0.18.1-RC1 and can just be removed from the build

**Comment by lrytz** [comment]
> Hmmm, [apparently](https://travis-ci.community/t/no-output-logged-when-using-travis-wait-command/1909/2) it is the `set -e`

On that discussion, there's a link to https://github.com/crazy-max/travis-wait-enhanced, which looks good. I'll give it a try.

**Pull request merged**
