### PR TITLE
SI-5045 - allow for using Regex without implicit anchors

### PR DESCRIPTION
**Pull request by LannyRipple**
Code changes to address SI-5045 (https://issues.scala-lang.org/browse/SI-5045)
- Add trait NoImplictAnchors to override Regex.unapplySeq
- Add .qr method to StringLike to create a Regex with NoImplicitAnchors
- Add tests of above

Have discussed in jira, scala-debate, and plan to raise the suggested change on scala-language.

### CODE REVIEW

**Comment by paulp** [comment]
Can you verify you have signed and submitted the contributor agreement at http://www.scala-lang.org/sites/default/files/contributor_agreement.pdf ?

**Comment by LannyRipple** [comment]
I'm sure I have not done so yet.  Will sign the PDF and mail it in.

  -ljr

**Comment by LannyRipple** [comment]
Ok.  I have emailed a signed PDF to Danielle.

  -ljr

**Comment by paulp** [comment]
I incorporated this in a modified form, thanks a lot.

**Pull request closed without merging**
