### PR TITLE
Remove hostile code from explicitouter.

### PR DESCRIPTION
**Pull request by paulp**
If that's the $outer accessor, what's that being created
in newOuterAccessor? Sketchy, sketchy business.

### CODE REVIEW

**Comment by paulp** [comment]
It's just a bonus to remove a "// 3" which refers to.... review by @retronym.

**Comment by paulp** [comment]
I thought I ran the tests on this, but my testing rig may have had a nervous breakdown. So it's a coin flip - if this explodes horribly, don't stone me to death.

**Comment by retronym** [comment]
Just to be sure, I dug up the original commit that added the call to `newOuterAccessor` and left the lonely `outerAcc`. https://github.com/scala/scala/commit/1237c520#L7R76

The `// 3` is still relevant.

That, and a test run, aside, lgtm.

**Comment by paulp** [comment]
I don't want to disturb jenkins on his nice vacation, but the tests passed at my house.

**Comment by paulp** [comment]
I'll bring back good old // 3 in the near future.

**Pull request merged**
