### PR TITLE
Travis-CI: add JDK 17 (replacing JDK 16)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
CI isn't testing this, because the JDK 16/17 job runs mergely.

I'll add a commit, not for merge, that adds it to PR validation.

**Comment by SethTisue** [comment]
hmm, can this be made to work for 17-ea without tweaking the logic in https://github.com/scala/scala-dev/blob/scala-dev/travis/default.yml ?

**Comment by SethTisue** [comment]
https://github.com/scala/scala-dev/blob/scala-dev/travis/default.yml is looking for AdoptOpenJDK only (`hs-adpt`), but here we want a Java.net build.

**Comment by SethTisue** [comment]
> we want a Java.net build

fixed by https://github.com/scala/scala-dev/pull/780

**Comment by SethTisue** [comment]
```
[error] /home/travis/build/scala/scala/src/partest/scala/tools/partest/SecurityTest.scala:19:35: class AccessControlExce
ption in package security is deprecated
[error]   def throwIt(x: Any) = throw new AccessControlException("" + x)
[error]                                   ^
[error] /home/travis/build/scala/scala/src/partest/scala/tools/partest/nest/DelegatingSecurityManager.scala:19:68: class
 SecurityManager in package lang is deprecated
[error] class DelegatingSecurityManager(delegate: SecurityManager) extends SecurityManager {
[error]                                                                    ^
[error] /home/travis/build/scala/scala/src/partest/scala/tools/partest/nest/DelegatingSecurityManager.scala:19:43: class
 SecurityManager in package lang is deprecated
[error] class DelegatingSecurityManager(delegate: SecurityManager) extends SecurityManager {
[error]                                           ^
[error] /home/travis/build/scala/scala/src/partest/scala/tools/partest/nest/TrapExit.scala:23:24: method getSecurityMana
ger in class System is deprecated
[error]     val saved = System.getSecurityManager
[error]                        ^
[error] /home/travis/build/scala/scala/src/partest/scala/tools/partest/nest/TrapExit.scala:24:12: method setSecurityManager in class System is deprecated
[error]     System.setSecurityManager(new DelegatingSecurityManager(saved) {
[error]            ^
[error] /home/travis/build/scala/scala/src/partest/scala/tools/partest/nest/TrapExit.scala:33:14: method setSecurityManager in class System is deprecated
[error]       System.setSecurityManager(saved)
[error]              ^
[error] 6 errors found
```

**Comment by SethTisue** [comment]
hmm `[info] welcome to sbt 1.5.4 (AdoptOpenJDK Java 1.8.0_292)` ?!

**Comment by SethTisue** [comment]
hey it's green! removing the "NOT FOR MERGE temporarily run jdk 17 cron in PR validation" commit now

**Review by dwijnand — APPROVED** [review]
LGTM, good work

**Pull request merged**
