### PR TITLE
Initial cut at running binary compatibility tests on the 2.9.x series

### PR DESCRIPTION
**Pull request by jsuereth**
Review by @lrytz or @gkossakowski

### CODE REVIEW

**Comment by jsuereth** [comment]
ping @gkossakowski or @lrytz here....

**Comment by gkossakowski** [comment]
This does not break the build yet but just prints MIMA output. It turns out that MIMA is not aware of some bytecode changes that are safe due to additional constraints (e.g. you can easily make method final in a sealed class if all subclasses are either sealed or final).

@jsuereth: Do we want to let change in that is half-baked? I mean, we don't want to end up with more noise that does not help a lot with detecting BC problems. WDYT?

**Comment by jsuereth** [comment]
Because MIMA _is_ noisy, it's a human-evaluation process every time.   This at least automates half of it.   I think it's more useful than not.   

I agree, we don't want more noise.  However, most of that work needs to be done on _MIMA_ not this commit.  Mima's silencing feature only works with SBT currently, hence the way this is integrated.

**Comment by gkossakowski** [comment]
I'll let @lrytz make final decision on it.

**Comment by lrytz** [comment]
this is fine with me

**Pull request merged**
