### PR TITLE
SI-2807 Avoid catch all warning for Stable Id patterns

### PR DESCRIPTION
**Pull request by retronym**
Review by @dragos

### CODE REVIEW

**Comment by adriaanm** [comment]
wouldn't it be possible to use `treeInfo.catchesAllOf` here?

**Comment by retronym** [comment]
That would flag `case x: Throwable`, which we want to allow. (Paul's original version of the warning used that method)

**Comment by adriaanm** [comment]
right you are

I still think it would be nice to factor out the test to TreeInfo
though it's not a show stopper for this pull request, as far as I'm concerned

**Comment by dragos** [comment]
LGTM!

**Pull request merged**
