### PR TITLE
Fix regression in HashMap.{merge, ++}

### PR DESCRIPTION
**Pull request by retronym**
Regressed in #8466

Fixes scala/scala-dev#672

### CODE REVIEW

**Comment by retronym** [comment]
This now aligns with the corresponding code in `HashSet` again.

image

**Comment by lrytz** [comment]
The link in the commit message is wrong, it regressed in https://github.com/scala/scala/pull/8466. Let's fix it to avoid future confusion.

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5542/

**Review by szeiger — APPROVED** [review]
LGTM as far as I understand the code. Clearly `allBits` was wrong because it's always 0 at that point.

**Comment by SethTisue** [comment]
community build run green except for unrelated failures (https://github.com/scala/scala-dev/issues/673)

**Pull request merged**
