### PR TITLE
Refactored example to Option.collect method.

### PR DESCRIPTION
**Pull request by jxcoder**
After refactoring:

``` scala
// Returns Some(HTTP) because the partial function covers the case.
Some("http") collect {case "http" => "HTTP"}

// Returns None because the partial function doesn't cover the case.
Some("ftp") collect {case "http" => "HTTP"}

// Returns None because None is passed to the collect method.
None collect {case value => value}
```

### CODE REVIEW

**Comment by jxcoder** [comment]
@vladureche, @heathermiller what do you think about this pull request?

Related issue [Issue #3861 Refactor example to Option.collect method](https://github.com/scala/scala/issues/3861)
Previous pull request [PR #3857 Added example to Option.collect method](https://github.com/scala/scala/pull/3857)

**Comment by adriaanm** [comment]
LGTM -- thanks, @jxcoder! Note that we use JIRA for issue tracking, so I've closed the issues that are not code.

**Comment by jxcoder** [comment]
@adriaanm, thank you! I will open issues in [issues.scala-lang.org](https://issues.scala-lang.org).

**Comment by VladUreche** [comment]
@jxcoder please have a look at the [contributing guide](https://github.com/scala/scala/blob/2.12.x/CONTRIBUTING.md) to see how commits have to be named when you're closing a bug. thx!

**Comment by jxcoder** [comment]
@vladureche, I thought that it is improvement not a bug. I'll see.

**Comment by gkossakowski** [comment]
The PR doesn't merge cleanly anymore. Please rebase.

**Comment by adriaanm** [comment]
I did the rebase -- see the referenced PR.

**Pull request closed without merging**
