### PR TITLE
SI-4602 Make fsc absolutize source file names

### PR DESCRIPTION
**Pull request by JamesIry**
The fsc server was using a path supplied by the client to turn things
like class path values into absolute paths. But it wasn't absolutizing
the source file names supplied to the compiler which lead to SI-4602.
This commit adds that absolutizing bit and cleans the logic up a bit
so that the settings object isn't told a path that it already knows.

A test is included that simulates changing directory by forcing two
different -current-dir settings on two different compile sessions on
the same server process.

review @paulp

### CODE REVIEW

**Comment by JamesIry** [comment]
This pull can't be merged as it will also have problem fixed by https://github.com/scala/scala/pull/1985

**Comment by JamesIry** [comment]
Oh the irony. PLS REBUILD ALL

**Comment by JamesIry** [comment]
That's more like it. How say you @paulp?

**Comment by paulp** [comment]
Well, I'm ready to gamble. Motion carried!

**Pull request merged**
