### PR TITLE
SI-4859 Step back from mis-optimizations in qualifiers

### PR DESCRIPTION
**Pull request by retronym**
Retargetting #1710 to master.

Widespread, invalid qualifier discarding in the apparent name of performance led to a variety of problems:

The compiler would crash in case of:

```
OuterCaseClass().InnerCaseClass()
```

And the side effect would be elided in:

```
{ println("!!"); Outer}.Inner
```

This change fixes these problems but stops short of fixing the last problem:

```
Outer.Inner.foo // module load of Outer is still elided.
```

This could be fixed use a stronger condition than `isExprSafeToInline` throughout this patch. (It would be `isExprSafeToElide` or `isPure`.)

Thoughts? Should that change be tackled in this ticket or separately?

Last time, @paulp [opined](https://github.com/scala/scala/pull/1710#discussion_r2458429):

> I don't see how we can fail to initialize Outer here if we wish to have at all predictable semantics.

Review by @paulp @magarcia

### CODE REVIEW

**Comment by magarciaEPFL** [comment]
As a sidenote, the experimental optimizer detects bytecode-level repeated reads of stable accessors, caching in a synthetic variable upon first access and reusing it afterwards (once per distinct control-flow path, which works pretty well for common cases).

**Comment by adriaanm** [comment]
/localhome/jenkins/a/workspace/pr-scala-testsuite-linux-opt/test/files/run/t0091.scala [FAILED]

**Comment by paulp** [comment]
This looks good to me if the verifier errors are gone. I think the idea of optimizer decisions being configurable at user level will also be necessary for a satisfying resolution to these inlining questions. A strict view that no behavioral change can take place rules out way too much; but how and where to relax the grip is another one-size-only-fits-some situations.

**Comment by retronym** [comment]
Rebased against master.

**Comment by paulp** [comment]
Eez good, mistah retronym.

**Comment by paulp** [comment]
But I guess somebody better run the tests since the kitteh is too good for us. I'll give them a whirl.

**Comment by retronym** [comment]
PLS REBUILD ALL

While we wait, Martin's viewpoint on whether `A.B.C.foo` should load modules `A` and `B` (reminder: it still doesn't under this patch):
- Accessing a nested Java static classes doesn't run the static initializer of the enclosing class
- People might be surprised by a performance difference between nested and top level modules
- But, the arguments for forcing initialization do make sense.
- We might investigate a scheme in which the constructor of a nested module initializes it's enclosing module. This would give us the desired semantics without the penalty of the outer module load at every access of the nested module.

I'll add these comments to SI-5304.

**Comment by paulp** [comment]
From the standpoint of performance, I think we should be a lot more worried about the impact the loading semantics have on the potential for optimization: ours, proguard's, and hotspot's. All of us have to allow for module loading side effects, because we offer no true statics. I'm not sure how large is the cumulative effect, but it rears its head in enough places to add up.

**Comment by paulp** [comment]
Since we're still waiting for a peep, i started a manual test run. https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/769/console

**Comment by paulp** [comment]
Yay, the tests passed. I'll fix the merge.

**Pull request merged**
