### PR TITLE
Add deprecated members `++:` and `repr` to `Iterable`

### PR DESCRIPTION
**Pull request by szeiger**
Fixes https://github.com/scala/bug/issues/10974

### CODE REVIEW

**Review by julienrf — APPROVED** [review]

**Comment by SethTisue** [comment]
lots of `java.lang.AssertionError: unsafe symbol Any (child of package scala) in runtime reflection universe` errors

**Comment by SethTisue** [comment]
@szeiger it was this PR's Jenkins job (https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/3709/) that generated a runaway logfile (as reported by Jason on Slack), so proceed with caution

**Comment by szeiger** [comment]
This harmless `++:` method is a nice scalac killer. It's marked `@inline final` in both `Iterable` and `SeqOps`. `Seq` inherits both definitions. The code should have never compiled but it does compile and produce invalid code (i.e. a non-working compiler that breaks during the bootstrapped tests).

**Comment by szeiger** [comment]
Hm, actually the one in `SeqOps` still takes an `Iterable` here so it doesn't conflict. It was correct that it compiled but it still produced bad code. I'm pushing an update that doesn't break the compiler in my local tests. Don't merge until it has been rebased on top of https://github.com/scala/scala/pull/7021 though. It will probably be mergeable but break the build.

**Comment by dwijnand** [comment]
> Don't merge until it has been rebased on top of #7021 though. It will probably be mergeable but break the build.

Marking as WIP

**Pull request merged**
