### PR TITLE
adds deprecation annotations on manifest incantations

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review by anyone

**Comment by adriaanm** [comment]
LGTM, though the messages could be shorter -- when you generate a lot of those, these things start to matter

**Comment by adriaanm** [comment]
also, doesn't it make more sense to start the message with the method they should use rather than the type?

**Comment by xeno-by** [comment]
I think it's better to cover the underlying cause first. Imho it's not good enough to just change, say, `manifest[T]` to `typeTag[T]` - existing context bounds would better be changed as well. Sure, manifests and type tags are interchangeable to a degree, but the conversion is not seamless.

**Comment by adriaanm** [comment]
i think pointing to the immediate solution first and then explaining in more detail makes more sense than starting with the underlying cause and then saying how to solve it. it's an error message -- in eclipse people will only see the first line in the tooltip

**Comment by odersky** [comment]
LGTM

**Comment by jsuereth** [comment]
PLS REBUILD ALL

**Pull request merged**
