### PR TITLE
SI-1909 SI-3832 SI-7007 SI-7223 Improved handling of larval objects

### PR DESCRIPTION
**Pull request by retronym**
Reclaims some ground lost in the first swing at SI-6666, and solves a few more issues to boot.

I'm hopeful that I'll be able to knock off the residuals of SI-6666 too, so I might push one or two more commits.

Review by @JamesIry

### CODE REVIEW

**Comment by retronym** [comment]
I'll close this temporarily until I address the failures.

**Comment by retronym** [comment]
Reopened for business.

**Comment by retronym** [comment]
I'm done with this one. I can't actually find anything residual from SI-6666, so we can close that one too.

**Comment by gkossakowski** [comment]
@JamesIry: ping

**Comment by magarciaEPFL** [comment]
What's the status of this PR? In particular, will it make to M5?

**Comment by gkossakowski** [comment]
@magarciaEPFL: I hope so. I'll try to steal @JamesIry's attention tomorrow.

**Comment by magarciaEPFL** [comment]
@gkossakowski Did you get @JamesIry 's attention yesterday?

**Comment by adriaanm** [comment]
I apologize on behalf of the reviewer for this not making the deadline.

**Comment by retronym** [comment]
This one isn't super urgent.

**Comment by gkossakowski** [comment]
@retronym: please fix a19e05371fb0a57263b68c1ced0ba88e830e4a61 (both commit message and test file names).

Other than that it can go in. Related to this PR: wouldn't make sense to perform all those checks at some late phase (genicode) when we see the final shape of trees and we perform checks that are very backend specific?

**Comment by retronym** [comment]
I've just rebased and fixed the last commit message and test file name.

**Pull request merged**
