### PR TITLE
Enable implicits to check completion enrichment

### PR DESCRIPTION
**Pull request by som-snytt**
Fixes scala/bug#10721

Conservatively retries applying a view with implicits enabled, for purposes of collecting enrichments. Not sure if that should be the initial attempt; the given implicit def has already been deemed applicable.

A test would be welcome.

### CODE REVIEW

**Comment by SethTisue** [comment]
@sh0hei want to try adding a test...?

**Comment by sh0hei** [comment]
@SethTisue Yes, I will try it 👍 should I submit it under a different PR?

**Comment by SethTisue** [comment]
@sh0hei GitHub doesn't make it super easy for multiple people to work on the same PR. you could ask Som to make you a collaborator on his fork, or you could submit a PR to this branch in his fork, and once he merged it, your commit would show up here.

**Comment by SethTisue** [comment]
another possibility is to make your own PR and include Som's commit in it

**Comment by som-snytt** [comment]
@sh0hei or submit a test that expects failure in a separate PR. Whichever PR is accepted last will have to correct the test. That way, your work isn't lost when my PR is rejected.

**Comment by sh0hei** [comment]
@SethTisue @som-snytt 
Thank you for your kind comments :)
I submit a PR (https://github.com/som-snytt/scala/pull/3) to Som's fork.
Thanks!

**Comment by SethTisue** [comment]
👍 thanks!

**Pull request merged**
